= 海龟和 CAPI 的 GitOps 最佳实践
:revdate: 2025-10-02
:page-revdate: {revdate}

ifeval::["{build-type}" == "product"]
本节将介绍使用 Turtles 和 Cluster API (CAPI) 实施 GitOps 的最佳实践，重点介绍如何将https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/index.html[Continuous Delivery]与*Cluster API Addon Provider Fleet*(`+CAAPF+`) 结合使用，以实现代理的自动配置和与`+CAPI+` 生态系统的集成。
endif::[]
ifeval::["{build-type}" == "community"]
本节介绍使用 Turtles 和 Cluster API (CAPI) 实施 GitOps 的最佳实践，重点介绍如何将https://fleet.rancher.io/[Fleet]与*Cluster API Addon Provider Fleet*(`+CAAPF+`) 结合使用，以实现代理供应自动化并集成到`+CAPI+` 生态系统中。
endif::[]

这些技巧具有可移植性，即使使用不同的 GitOps 解决方案也可适用。

== 常用提示

ifeval::["{build-type}" == "product"]
- **独立的 CAPI 集群和 ClusterClass 配置：**
  将 CAPI 集群配置 (`+clusters/+`) 与 CAPI`+ClusterClass+` 定义 (`+templates/+`) 区分开来。这种分离允许通过共享模板配置多个群集，同时降低意外更改基础设施的风险。
- **隔离插件配置：**
  将应用程序清单存储在`+applications/+` 中，确保它们独立于`+Clusters+` 和`+ClusterClasses+` 。这样就能根据用户需求或匹配选择器进行选择性或分组供应，防止干扰集群基础设施。请注意，在提供附加组件之前，需要Helm 图表依赖关系https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/gitrepo-content.html#_fleet_yaml[刷新] 。
- **利用嵌套 GitRepo 资源：**
  利用https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/gitrepo-content.html#_nested_gitrepo_crs[嵌套] `+GitRepo+` 资源，在 Fleet 中高效地构建资源库内容。这种方法允许模块化配置，将`+ClusterClass+` 定义、所需附加组件/应用程序和群集配置结合起来，同时保持关注点分离。
- **在可用时使用 GitOps 集成工具：**
  在配置 GitOps 设置时，要考虑到可用的工具及其提供的功能。例如https://rancher.github.io/cluster-api-addon-provider-fleet/00_intro.html[`+CAAPF+`]，它能在`+CAPI+` 集群上自动安装 Fleet GitOps，并提供便捷的自动化。
- **应用 Kustomize 叠加功能，实现特定环境的自定义：**
  使用`+overlays/+` 来存储不同环境下的 Kustomize 叠加效果。这确保了配置更改（如扩展调整、网络修改或组件升级）可以动态应用，而无需更改基础清单。
- **利用比较补丁：**
  如果捆绑包包含用于https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/troubleshooting.html#_suse_rancher_prime_continuous_delivery_deployment_stuck_in_modified_state[`+diff+` 检测的]适当规则，Fleet 可以有选择性地忽略资源差异。这将防止捆绑包陷入修改状态。
endif::[]
ifeval::["{build-type}" == "community"]
- **独立的 CAPI 集群和 ClusterClass 配置：**
  将 CAPI 集群配置 (`+clusters/+`) 与 CAPI`+ClusterClass+` 定义 (`+templates/+`) 区分开来。这种分离允许通过共享模板配置多个群集，同时降低意外更改基础设施的风险。
- **隔离插件配置：**
  将应用程序清单存储在`+applications/+` 中，确保它们独立于`+Clusters+` 和`+ClusterClasses+` 。这样就能根据用户需求或匹配选择器进行选择性或分组供应，防止干扰集群基础设施。请注意，在提供附加组件之前，需要Helm 图表依赖关系https://fleet.rancher.io/gitrepo-content#fleetyaml[刷新] 。
- **利用嵌套 GitRepo 资源：**
  利用https://fleet.rancher.io/gitrepo-content#nested-gitrepo-crs[嵌套] `+GitRepo+` 资源，在 Fleet 中高效地构建资源库内容。这种方法允许模块化配置，将`+ClusterClass+` 定义、所需附加组件/应用程序和群集配置结合起来，同时保持关注点分离。
- **在可用时使用 GitOps 集成工具：**
  在配置 GitOps 设置时，要考虑到可用的工具及其提供的功能。例如https://rancher.github.io/cluster-api-addon-provider-fleet/00_intro.html[`+CAAPF+`]，它能在`+CAPI+` 集群上自动安装 Fleet GitOps，并提供便捷的自动化。
- **应用 Kustomize 叠加功能，实现特定环境的自定义：**
  使用`+overlays/+` 来存储不同环境下的 Kustomize 叠加效果。这确保了配置更改（如扩展调整、网络修改或组件升级）可以动态应用，而无需更改基础清单。
- **利用比较补丁：**
  如果捆绑包包含用于https://fleet.rancher.io/troubleshooting#fleet-deployment-stuck-in-modified-state[`+diff+` 检测的]适当规则，Fleet 可以有选择性地忽略资源差异。这将防止捆绑包陷入修改状态。
endif::[]

== 文件夹分离战略

结构合理的资料库可简化管理，提高清晰度。建议采用以下文件夹分离策略：

----
repo-root/
│── fleet/
│   ├── providers/         # CAPIProvider files to use with templates
│   │   ├── core/          # Core provider configuration
│   │   ├── infra-docker/  # Docker provider configuration
│   │   ├── infra-aws/     # AWS provider configuration
│   ├── clusters/          # Cluster-specific configurations
│   │   ├── prod/          # Production clusters
│   │   ├── staging/       # Staging clusters
│   │   ├── dev/           # Development clusters
│   ├── addons/            # Application-specific manifests focused on cluster bootstrapping, like CNI, CCM, CPI configurations.
│   │   ├── cni/           # Group applications based on purpose. Provide fleet.yaml per each sub-directory to maintain bundle separation.
│   │   ├── ccm/
│   ├── templates/         # CAPI ClusterClass templates for cluster provisioning
│   ├── fleet.yaml         # Fleet bundle configuration
│── overlays/              # Kustomize overlays for different environments
│   ├── prod/.             # Kustomize overlays for production environments
│   ├── staging/.          # Kustomize overlays for staging environments
│   ├── dev/.              # Kustomize overlays for development environments
----

== 提供商配置

CAPI 提供商定义了群集配置所需的基础设施组件。简单的设置如下

----
repo-root/
│── fleet/
│   ├── providers/
│   │   ├── core/
│   │   |   ├── core.yaml  # Core `+CAPIProvider+` definition
│   │   |   ├── fleet.yaml # Fleet.yaml definition for the provider setup
----

其中包含核心供应商：

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: cluster-api
spec:
  type: core
----

== 模板配置

在`+fleet.yaml+` 中指定`+dependsOn+` ，用于特定的`+CAPIProvider+` 捆绑程序或外部`+GitRepo+` 组件。这可确保模板以正确的顺序推出，并防止出现组件控制器缺失或尚未准备好接受`+ClusterClass+` 定义的问题。

[source,yaml]
----
namespace: capa-clusters
dependsOn:
  - name: core      # Ensure core bundle is installed first
  - name: infra-aws # Wait for AWS provider installation
----

== 集群配置

使用标签将集群与所需的附加组件动态匹配，只允许部署必要的工作负载。

标签使用示例：

[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aws-cluster
  labels:
    cni: calico
    ccm: aws
    env: dev
----

[WARNING]
====
建议将群集定义与模板分开，因为这样删除群集捆绑包可以让 CAPI 控制器按照正确的顺序处理删除。同时删除`+Clusters+` 和`+ClusterClasses+` 可能会产生意想不到的结果。
====

== 插件配置

附加配置对于简化集群配置至关重要，可确保集群在无需人工干预或第三方工具的情况下达到`+Ready+` 状态。

集群插件应定义精确的选择规则，以便与适当标记的集群进行匹配。

下面的示例展示了一个需要安装`+Calico+` CNI 和`+AWS+` Cloud Controller Manager (CCM) 的群集：

[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aws-cluster
  labels:
    cni: calico
    ccm: aws
----

这种设置需要两个`+GitRepo+` 资源，每个资源负责根据特定标签配置附加组件\--一个用于`+cni: calico+` ，另一个用于`+ccm: aws+` 。

下面是`+GitRepo+` 资源的示例，用于部署`+Calico+` CNI：

[source,yaml]
----
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: calico
spec:
  branch: main
  paths:
  - /fleet/applications/calico
  repo: https://github.com/rancher-sandbox/cluster-api-addon-provider-fleet.git
  targets:
  - clusterSelector:
      matchLabels:
        cni: calico
        env: dev
----

这可确保`+Calico+` CNI 只部署在标有`+cni: calico+` 和`+env: dev+` 的集群上，从而实现有选择的环境配置。

=== 舵手图表值模板

插件配置需要根据匹配的群集定义和特定群集状态动态调整`+Calico+` 工作负载。这可以通过`+fleet.yaml+` 设置来实现，类似于以下结构：

----
repo-root/
│── fleet/
│   ├── applications/
│   │   ├── calico/
│   │   │   ├── fleet.yaml # Fleet configuration for the Calico setup
----

`+fleet.yaml+` 文件定义了模板规则和`+comparePatches+` ，以确保顺利推出，不受群集配置的影响。要了解有关`+CAAPF+` 模板的更多信息，请参阅https://rancher.github.io/cluster-api-addon-provider-fleet/04_reference/02_templating-strategy.html[文档] 官方。

[source,yaml]
----
helm:
  releaseName: projectcalico
  repo: https://docs.tigera.io/calico/charts
  chart: tigera-operator
  templateValues:
    installation: |-
      cni:
        type: Calico
        ipam:
          type: HostLocal
      calicoNetwork:
        bgp: Disabled
        mtu: 1350
        ipPools:
          ${- range $cidr := .ClusterValues.Cluster.spec.clusterNetwork.pods.cidrBlocks }
          - cidr: "${ $cidr }"
            encapsulation: None
            natOutgoing: Enabled
            nodeSelector: all()${- end}

diff:
  comparePatches:
  - apiVersion: operator.tigera.io/v1
    kind: Installation
    name: default
    operations:
    - {"op":"remove", "path":"/spec/kubernetesProvider"}
----
