= k8s 自定义密码设置（已废弃）
:revdate: 2025-10-27
:page-revdate: {revdate}

== 概述

SUSE Observability 代理支持指定包含 API 密钥和群集授权令牌的自定义密文名称。该功能对于希望管理自己的秘密并避免 Helm 图表自动创建秘密的用户非常有用。

[CAUTION]
====
*这种自定义秘密的方法已经过时，与 RBAC 功能不兼容。*

请使用xref:/setup/agent/k8s-custom-secrets-setup.adoc[新方法]使用外部机密。
====


== 舵手图

=== 配置选项

* `stackstate.manageOwnSecrets`:布尔标志，用于确定用户是否希望管理自己的秘密。默认值为`false` 。
* `stackstate.customSecretName`:(可选） 用户创建的自定义秘密的名称。如果`stackstate.manageOwnSecrets` 设置为`true` ，则为必填项。
* `stackstate.customApiKeySecretKey`:(可选）自定义密文中 API 密钥的密钥名称。如果`stackstate.manageOwnSecrets` 设置为`true` ，则为必填项。
* `stackstate.customClusterAuthTokenSecretKey`:(可选）自定义密文中群集授权令牌的密钥名称。如果`stackstate.manageOwnSecrets` 设置为`true` ，则为必填项。

=== 行为描述

* *自动创建秘密*：默认情况下，如果`stackstate.manageOwnSecrets` 设置为`false` ，图表将继续像以前一样自动创建秘密。
* *自定义秘密管理*：如果`stackstate.manageOwnSecrets` 设置为`true` ，图表会要求用户提供自定义密文的名称（`stackstate.customSecretName` ）以及 API 密钥和授权令牌的密钥（分别为`stackstate.customApiKeySecretKey` 和`stackstate.customClusterAuthTokenSecretKey` ）。
* *默示遗漏*：当指定要管理自己的机密时，图表将忽略`stackstate.apiKey` 和`stackstate.cluster.authToken` 的值。
+
== 如何在 values.yaml 中使用

. *使用自动创建密文（默认）*：
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *管理自己的秘密*
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
