= 用于请求跟踪侧车注入的证书
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

安装代理时使用`--set httpHeaderInjectorWebhook.enabled=true` 会启用xref:/setup/agent/k8sTs-agent-request-tracing.adoc#_enabling_the_trace_header_injection_sidecar[侧车注入机制]，该机制会创建自签名证书，并使用`ClusterRole` 授予对 Kubernetes 集群中`Secret` 和`MutatingWebhookConfiguration` 对象的写访问权限。

如果出于安全考虑，不希望创建授予整个集群写入权限的`ClusterRoles` ，或者有其他提供证书的方法：

. <<_generate_a_certificate_locally,在本地>>生成自签名证书。
. 使用 k8shttps://cert-manager.io/[cert-manager]（如果集群上已有）<<_generate_a_certificate_using_the_cert_manager,，`ClusterIssuer`>> 。

== 在本地生成证书

要在本地生成证书，请采取以下步骤：

. 下载证书生成脚本并运行，生成带有正确证书的 helm values (`tls_values.yaml`) 文件：
+
----
wget https://raw.githubusercontent.com/StackVista/http-header-injector/main/scripts/generate_ca_cert.sh
chmod +x generate_ca_cert.sh
./generate_ca_cert.sh <helm-agent-release-name> <helm-agent-namespace>
----
+
请确保使用将在 helm 命令中使用的版本名称和命名空间，否则证书将无效。

. 通过在 helm 调用命令中添加`--set httpHeaderInjectorWebhook.enabled=true -f tls_values.yaml` 来安装添加了附加配置的代理

== 使用证书管理器生成证书

如果集群安装了https://cert-manager.io/[cert-manager]，并配置了`ClusterIssuer` ，就可以在侧载注入器的代理中使用`ClusterIssuer` 签发的证书。为此，请添加以下命令行参数以安装代理：`--set httpHeaderInjectorWebhook.enabled=true --set-string httpHeaderInjectorWebhook.webhook.tls.mode="cert-manager" --set-string httpHeaderInjectorWebhook.webhook.tls.certManager.issuer="<my-cluster-issuer>"`.请务必将 my-cluster-issuer 替换为群集中的签发器名称。
