= Rollenbasierte Zugriffskontrolle (RBAC)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

Mit der Zugriffsverwaltung können Sie verwalten, wer Zugriff auf bestimmte Topologieelemente, Metrikdaten, Traces und UI-Elemente hat und welche APIs sie aufrufen können.

RBAC ist ein Autorisierungssystem, das eine fein abgestufte Zugriffsverwaltung für SUSE Observability-Ressourcen sowie eine saubere und einfache Möglichkeit zur Überprüfung von Benutzerrechten und zur Behebung von Problemen mit Zugriffsrechten bietet.

== Was können Sie mit RBAC tun?

Im Folgenden finden Sie Beispiele dafür, was Sie mit RBAC tun können:

* Erlauben Sie einem Benutzer nur den Zugriff auf den Entwicklungscluster, einem anderen sowohl auf den Produktions- als auch auf den Entwicklungscluster und einem dritten den Zugriff auf den Entwicklungscluster und nur einen Namensraum im Produktionscluster.
* Weisen Sie einer kleinen Gruppe von Benutzern eine Administratorrolle für die Einrichtung und Konfiguration von SUSE Observability zu. Alle Entwickler erhalten eine Troubleshooter-Rolle, mit der sie alle Topologie, Metriken, Traces, Protokolle und Ereignisse einsehen können, allerdings mit eingeschränkten Konfigurationsmöglichkeiten.

== Was ist eine Rolle in SUSE Observability?

Eine Rolle in SUSE Observability ist eine Kombination aus einem konfigurierten Subjekt und einer Reihe von xref:/setup/security/rbac/rbac_permissions.adoc[Berechtigungen]. Der Prozess der Einrichtung einer Rolle in SUSE Observability wird in xref:/setup/security/rbac/rbac_roles.adoc[Wie werden Rollen eingerichtet] beschrieben.

== Quellen für RBAC-Rollen

Sie können Rollen auf verschiedene Weise definieren.  Alle verwenden die gleichen xref:/setup/security/rbac/rbac_permissions.adoc[Berechtigungen].

* **Konfiguration** - in den xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[Steuerwerten] für SUSE Observability
* **Dynamisch** - xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[verwenden Sie die `+sts+` CLI]
* **Von Kubernetes abgebildet** - xref:/setup/security/rbac/rbac_rancher.adoc[Abbildung von Kubernetes `+Roles+` und] xref:/setup/security/rbac/rbac_rancher.adoc[ `+RoleBindings+`]

== Mehr zur RBAC-Konfiguration

* xref:/setup/security/rbac/rbac_permissions.adoc[Berechtigungen]
* xref:/setup/security/rbac/rbac_roles.adoc[Wie man Rollen einrichtet]
* xref:/setup/security/rbac/rbac_rancher.adoc[Verwendung mit Rancher]
* xref:/setup/security/rbac/rbac_scopes.adoc[Geltungsbereiche]
* xref:/setup/security/authentication/README.adoc[So konfigurieren Sie die Authentifizierung]
