= Balanceador de carga do cluster
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Esta seção descreve como instalar um balanceador de carga externo na frente dos nós de servidor de um cluster K3s de alta disponibilidade (HA). São fornecidos dois exemplos: Nginx e HAProxy.

[TIP]
====
Os balanceadores de carga externos não devem ser confundidos com o ServiceLB incorporado, que é um controlador incorporado que permite o uso dos serviços do Kubernetes LoadBalancer sem a implantação de um controlador de balanceador de carga de terceiros. Para obter mais detalhes, consulte xref:networking/networking-services.adoc#_service_load_balancer[Service Load Balancer].

Os balanceadores de carga externos podem ser usados para fornecer um endereço de registro fixo para registrar nós ou para acesso externo ao servidor da API do Kubernetes. Para expor os serviços do LoadBalancer, os balanceadores de carga externos podem ser usados junto com o ServiceLB ou no lugar dele, mas, na maioria dos casos, os controladores de balanceamento de carga de substituição, como o MetalLB ou o Kube-VIP, são uma opção melhor.
====


== Pré-requisitos

Todos os nós deste exemplo estão executando o Ubuntu 20.04.

Para ambos os exemplos, suponha que um xref:datastore/ha-embedded.adoc[cluster HA K3s com etcd incorporado] tenha sido instalado em 3 nós.

Cada servidor k3s é configurado com:

[,yaml]
----
# /etc/rancher/k3s/config.yaml
token: lb-cluster-gd
tls-san: 10.10.10.100
----

Os nós têm nomes de host e IPs de:

* server-1: `+10.10.10.50+`
* server-2: `+10.10.10.51+`
* server-3: `+10.10.10.52+`

Dois nós adicionais para balanceamento de carga são configurados com nomes de host e IPs de:

* lb-1: `+10.10.10.98+`
* lb-2: `+10.10.10.99+`

Existem três nós adicionais com nomes de host e IPs de:

* agente-1: `+10.10.10.101+`
* agent-2: `+10.10.10.102+`
* agent-3: `+10.10.10.103+`

== Configuração do balanceador de carga

[tabs,sync-group-id=ext-load-balancer]
======
HAProxy::
+
--
http://www.haproxy.org/[O HAProxy] é uma opção de código aberto que fornece um balanceador de carga TCP. Ele também oferece suporte a HA para o próprio balanceador de carga, garantindo redundância em todos os níveis. Consulte http://docs.haproxy.org/2.8/intro.html[Documentação] do HAProxy para obter mais informações.

Além disso, usaremos o KeepAlived para gerar um IP virtual (VIP) que será usado para acessar o cluster. Consulte https://www.keepalived.org/manpage.html[KeepAlived Documentation] para obter mais informações.

. Instale o HAProxy e o KeepAlived:
+
[,bash]
----
sudo apt-get install haproxy keepalived
----

. Adicione o seguinte a `+/etc/haproxy/haproxy.cfg+` em lb-1 e lb-2:
+
----
frontend k3s-frontend
    bind *:6443
    mode tcp
    option tcplog
    default_backend k3s-backend

backend k3s-backend
    mode tcp
    option tcp-check
    balance roundrobin
    default-server inter 10s downinter 5s
    server server-1 10.10.10.50:6443 check
    server server-2 10.10.10.51:6443 check
    server server-3 10.10.10.52:6443 check
----

. Adicione o seguinte a `+/etc/keepalived/keepalived.conf+` em lb-1 e lb-2:
+
----
global_defs {
  enable_script_security
  script_user root
}

vrrp_script chk_haproxy {
    script 'killall -0 haproxy' # faster than pidof
    interval 2
}

vrrp_instance haproxy-vip {
    interface eth1
    state <STATE> # MASTER on lb-1, BACKUP on lb-2
    priority <PRIORITY> # 200 on lb-1, 100 on lb-2

    virtual_router_id 51

    virtual_ipaddress {
        10.10.10.100/24
    }

    track_script {
        chk_haproxy
    }
}
----

. Reinicie o HAProxy e o KeepAlived em lb-1 e lb-2:
+
[,bash]
----
systemctl restart haproxy
systemctl restart keepalived
----

. No agente-1, agente-2 e agente-3, execute o seguinte comando para instalar o k3s e ingressar no cluster:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_TOKEN=lb-cluster-gd sh -s - agent --server https://10.10.10.100:6443
----
Onde `+INSTALL_K3S_ARTIFACT_URL+` é o https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[URL dos artefatos principais]
+
Agora você pode usar o site `+kubectl+` do nó do servidor para interagir com o cluster.
+
[,bash]
----
root@server-1 $ k3s kubectl get nodes -A
NAME       STATUS   ROLES                       AGE     VERSION
agent-1    Ready    <none>                      32s     v1.27.3+k3s1
agent-2    Ready    <none>                      20s     v1.27.3+k3s1
agent-3    Ready    <none>                      9s      v1.27.3+k3s1
server-1   Ready    control-plane,etcd,master   4m22s   v1.27.3+k3s1
server-2   Ready    control-plane,etcd,master   3m58s   v1.27.3+k3s1
server-3   Ready    control-plane,etcd,master   3m12s   v1.27.3+k3s1
----
--

Nginx::
+
--
[WARNING]
====
O Nginx não oferece suporte nativo a uma configuração de alta disponibilidade (HA). Se estiver configurando um cluster HA, ter um único balanceador de carga na frente do K3s reintroduzirá um único ponto de falha.
====

http://nginx.org/[O Nginx Open Source] fornece um balanceador de carga TCP. Consulte https://nginx.org/en/docs/http/load_balancing.html[Usando o nginx como balanceador de carga HTTP] para obter mais informações.

. Crie um arquivo `+nginx.conf+` no lb-1 com o seguinte conteúdo:
+
----
events {}

stream {
  upstream k3s_servers {
    server 10.10.10.50:6443;
    server 10.10.10.51:6443;
    server 10.10.10.52:6443;
  }

  server {
    listen 6443;
    proxy_pass k3s_servers;
  }
}
----

. Execute o balanceador de carga Nginx no lb-1:
+
Usando o docker:
+
[,bash]
----
docker run -d --restart unless-stopped \
    -v ${PWD}/nginx.conf:/etc/nginx/nginx.conf \
    -p 6443:6443 \
    nginx:stable
----
+
Ou https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/[install nginx] and then run:
+
[,bash]
----
cp nginx.conf /etc/nginx/nginx.conf
systemctl start nginx
----

. No agente-1, agente-2 e agente-3, execute o seguinte comando para instalar o k3s e ingressar no cluster:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_TOKEN=lb-cluster-gd sh -s - agent --server https://10.10.10.98:6443
----
+
Agora você pode usar o site `+kubectl+` do nó do servidor para interagir com o cluster.
+
[,bash]
----
root@server1 $ k3s kubectl get nodes -A
NAME       STATUS   ROLES                       AGE     VERSION
agent-1    Ready    <none>                      30s     v1.27.3+k3s1
agent-2    Ready    <none>                      22s     v1.27.3+k3s1
agent-3    Ready    <none>                      13s     v1.27.3+k3s1
server-1   Ready    control-plane,etcd,master   4m49s   v1.27.3+k3s1
server-2   Ready    control-plane,etcd,master   3m58s   v1.27.3+k3s1
server-3   Ready    control-plane,etcd,master   3m16s   v1.27.3+k3s1
----
--
======
