include::partial$variables.adoc[]
= Verteilung von Politiken
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Verteilen Sie Richtlinien sicher über eine OCI-konforme Registrierung mithilfe von Tools wie kwctl und gewährleisten Sie die Sicherheit des Clusters durch {project-name} Richtlinienverwaltung.
:doc-persona: ["kubewarden-operator", "kubewarden-policy-developer", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["distributing-policies"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "oci", "kubewarden", "policy", "wasm", "webassembly"]
:current-version: {page-origin-branch}

{project-name} Richtlinien sind WebAssembly (Wasm)-Binärdateien, die vom {short-project-name} Policy Server ausgewertet werden.

Der Richtlinienserver {short-project-name} lädt Richtlinien aus diesen Quellen:

* Lokales Dateisystem
* HTTP(s)-Server
* OCI-konforme Registrierungsstellen:
 ** https://github.com/distribution/distribution[Vertrieb]
 ** https://ghcr.io[GitHub-Container-Register]
 ** https://azure.microsoft.com/en-us/products/container-registry/[Azure-Container-Registrierung]
 ** https://aws.amazon.com/ecr/[Amazon ECR]
 ** https://cloud.google.com/artifact-registry/[Google Container-Register]

{short-project-name} empfiehlt, die Richtlinien von {short-project-name} über ein reguläres OCI-konformes Register zu verteilen. Container-Registrierungen sind eine zwingende Voraussetzung für jeden Kubernetes-Cluster. Es ist von Vorteil, alle für ein Cluster erforderlichen Artefakte an einem einzigen Ort zu speichern und zu sichern.

== Übermittlung von Richtlinien an ein OCI-konformes Register

Die https://github.com/opencontainers/image-spec[OCI-Image-Format-Spezifikation]ermöglicht die Speicherung beliebiger binärer Blob-Dateien in einer regulären OCI-konformen Container-Registry.

Die OCI-konforme Zielregistrierungsstelle *muss Artefakte unterstützen*, um eine {short-project-name} Richtlinie erfolgreich an sie weiterzuleiten.

Sie können mit der https://github.com/kubewarden/kwctl[`+kwctl+`] CLI können Sie eine{short-project-name} Richtlinie an eine OCI-konforme Registrierung übergeben.

== Kommentierung der Politik

Sie können eine Richtlinie auch mit `+kwctl+` kommentieren. Das Hinzufügen von Anmerkungen zu einer {short-project-name}-Richtlinie erfolgt durch das Hinzufügen von benutzerdefinierten Wasm-Abschnitten zur Binärdatei der Richtlinie. Das bedeutet, dass die Richtlinie ihre eigenen Metadaten verpackt.

Der Befehl `+kwctl annotate+` erfordert zwei Eingaben:

* die zu kommentierende {short-project-name} Richtlinie, eine lokale Datei im Dateisystem.
* die Annotations-Datei, eine Datei mit einer YAML-Beschreibung der Metadaten der Richtlinie.
Diese Datei befindet sich in der Regel im Stammordner des Projekts Ihrer Richtlinie.

Sie können diese Datei z. B. als `+metadata.yml+` im aktuellen Verzeichnis speichern:

[subs="+attributes",yaml]
----
rules:
- apiGroups: ["*"]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["*"]
mutating: false
annotations:
  io.kubewarden.policy.title: palindromify
  io.kubewarden.policy.version: 0.1.0
  io.kubewarden.policy.description: Allows you to reject palindrome names in resources and namespace names, or to only accept palindrome names
  io.kubewarden.policy.author: Name Surname <name.surname@example.com>
  io.kubewarden.policy.url: https://github.com/<org>/palindromify
  io.kubewarden.policy.source: https://github.com/<org>/palindromify
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
    This is markdown text and as such allows you to define a free form usage text.

    This policy allows you to reject requests if:
    - The name of the resource is a palindrome name.
    - The namespace name where this resource is created has a palindrome name.

    This policy accepts the following settings:

    - `+invert_behavior+`: bool that inverts the policy behavior. If enabled, only palindrome names will be accepted.
----

Lassen Sie uns nun die Police kommentieren:

[subs="+attributes",shell]
----
$ kwctl annotate policy.wasm \
    --metadata-path metadata.yml \
    --output-path annotated-policy.wasm
----

Bei der Kommentierung werden bestimmte Optimierungen an der Richtlinie vorgenommen, so dass die kommentierte Richtlinie oft kleiner ist als das Original. Dies hängt stark von der Toolchain ab, mit der das ursprüngliche Wasm-Objekt erstellt wurde.

[IMPORTANT]
====

.Verwenden Sie kwctl inspect, um Ihre Richtlinie zu überprüfen
[%collapsible]
======

[subs="+attributes",shell]
----
$ kwctl inspect annotated-policy.wasm
2023-08-24T12:06:27.986401Z  INFO sigstore::cosign::client_builder: Rekor public key not provided. Rekor integration disabled
2023-08-24T12:06:27.986449Z  INFO sigstore::cosign::client_builder: No Fulcio cert has been provided. Fulcio integration disabled
Details
title:                    palindromify
description:              Allows you to reject palindrome names in resources and namespace names, or to only accept palindrome names
author:                   Name Surname <name.surname@example.com>
url:                      https://github.com/<org>/palindromify
source:                   https://github.com/<org>/palindromify
license:                  Apache-2.0
mutating:                 false
background audit support: true
context aware:            false
execution mode:           kubewarden-wapc
protocol version:         1

Annotations
io.kubewarden.kwctl       1.7.0-rc2

Rules
────────────────────
- apiGroups:
  - '*'
  apiVersions:
  - '*'
  resources:
  - '*'
  operations:
  - '*'
────────────────────

Usage
This is markdown text and as such allows you to define a free form usage text.

This policy allows you to reject requests if:

• The name of the resource is a palindrome name.
• The namespace name where this resource is created has a palindrome name.

This policy accepts the following settings:

• invert_behavior: bool that inverts the policy behavior. If enabled, only palindrome names will be accepted.

Cannot determine if the policy has been signed. There was an error while attempting to fetch its signatures from the remote registry: invalid uri
----

======
====


== Die Politik vorantreiben

Sie können eine kommentierte Richtlinie wie folgt verschieben:

[subs="+attributes",shell]
----
$ kwctl push annotated-policy.wasm \
     <oci-registry>/kubewarden-policies/palindromify-policy:v0.0.1
----

Es ist nicht ratsam, unkommentierte Maßnahmen zu fördern. Der Richtlinienserver verwendet die durch Anmerkungen bereitgestellten Metadaten, um eine Richtlinie korrekt auszuführen. Standardmäßig weigert sich`+kwctl push+`, eine solche Richtlinie an ein OCI-Register zu übermitteln. Wenn Sie eine unkommentierte Richtlinie benötigen, verwenden Sie das `+-&#x200D;-&#x200D;force+` -Flag von `+kwctl push+`.

Sie können eine Richtlinie vom {short-project-name} Policy Server oder `+kwctl+` als`+registry://<oci-registry>/kubewarden-policies/palindromify-policy:v0.0.1+` referenzieren.
