include::partial$variables.adoc[]
= Politische Gruppen
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie mehr über die Erstellung komplexer Richtlinien, indem Sie einfachere Richtlinien mit Hilfe von Richtliniengruppen kombinieren, insbesondere mit AdmissionPolicyGroup- und ClusterAdmissionPolicyGroup-Definitionen.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["Erklärungen", "Policy-Group"]
:doc-type: ["explanation"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "policy groups", "clusteradmissionpolicygroup", "admissionpolicygroup"]
:sidebar_label: Politische Gruppen
:sidebar_position: 21
:current-version: {page-origin-branch}

Mit der Richtliniengruppenfunktion können Benutzer komplexe Richtlinien erstellen, indem sie einfachere Richtlinien kombinieren. Es werden zwei neue benutzerdefinierte Ressourcendefinitionen (CRDs) eingeführt:

* `+AdmissionPolicyGroup+`: für Zulassungsrichtlinien, die für bestimmte Namensräume gelten.
* `+ClusterAdmissionPolicyGroup+`: für Zulassungsrichtlinien, die für den gesamten Cluster gelten.

Diese Richtliniengruppen ermöglichen es den Benutzern, vorhandene Richtlinien zu verwenden, wodurch die Notwendigkeit der Erstellung eigener Richtlinien verringert und die Wiederverwendung verbessert wird. Durch die Vermeidung der Duplizierung von Richtlinienlogik können Benutzer die Verwaltung vereinfachen und benutzerdefinierte Richtlinien mit einer DSL-ähnlichen Konfiguration erstellen.

Richtliniengruppen ermöglichen die kombinierte Bewertung mehrerer Richtlinien mit Hilfe logischer Operatoren. Dies ermöglicht die Definition einer komplexen Logik. Während normale Richtlinien jedoch eine Mutationslogik enthalten können, um Ressourcen während der Zulassung zu ändern, führen Richtliniengruppen nur eine Validierung durch.

Die Konfiguration für Richtliniengruppen ist ähnlich wie die für normale Richtlinien. Der Unterschied besteht in der Hinzufügung der Felder `+expression+`, `+message+` und `+policies+`sowie in der Deklaration der kontextabhängigen Regeln an einer anderen Stelle.

Dies ist ein Beispiel für eine `+ClusterAdmissionPolicyGroup+`, die Sie in den nächsten Abschnitten zur Erläuterung der verschiedenen Felder verwenden können:

.Eine `+ClusterAdmissionPolicyGroup+`, die Pods ablehnt, die Bilder mit dem Tag `+latest+` verwenden, es sei denn, die Bilder sind von zwei vertrauenswürdigen Parteien signiert: Alice und Bob.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  policies:
    signed_by_alice:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
                yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
                -----END PUBLIC KEY-----
    signed_by_bob:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X
                urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==
                -----END PUBLIC KEY-----
    reject_latest:
      module: registry://ghcr.io/kubewarden/policies/trusted-repos:v0.2.0
      settings:
        tags:
          reject:
            - latest
  expression: "reject_latest() || (signed_by_alice() && signed_by_bob())"
  message: "the image is using the latest tag or is not signed by Alice and Bob"
----
======

== Wichtigste Konfigurationsfelder

In diesem Abschnitt werden die wichtigsten Konfigurationsfelder einer Richtliniengruppe behandelt.

=== Das Attribut `+policies+` 

Das Feld "Richtlinien" ist eine Abbildung der üblichen Richtlinien. {project-name} ruft die Richtlinien nach der Richtliniengruppe auf, um zu bestimmen, ob die zu bewertende Ressource akzeptiert oder abgelehnt werden soll. Die Definitionen dieser Policen sind eine vereinfachte Version der normalen {short-project-name} Policen und enthalten nur die Attribute `+module+`, `+settings+` und`+contextAwareResources+`. Diese Elemente sind notwendig, damit die Richtlinien innerhalb einer Richtliniengruppe funktionieren.

Ein eindeutiger Name identifiziert jede Richtlinie der Gruppenrichtlinie. Der folgende Ausschnitt definiert zum Beispiel drei Richtlinien: `+signed_by_alice+`, `+signed_by_bob+`und `+reject_latest_tag+`.

[,yaml]
----
policies:
  signed_by_alice:
    module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
    settings: {} # settings for the policy
  signed_by_bob:
    module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
    settings: {} # settings for the policy
  reject_latest_tag:
    module: ghcr.io/kubewarden/policies/trusted-repos-policy:v0.2.0
    settings: {} # settings for the policy
----

[TIP]
====

Eine Richtliniengruppe kann dieselbe Richtlinie mehrfach mit unterschiedlichen Einstellungen enthalten.

====


=== Das Attribut `+expression+` 

Das Attribut `+expression+` enthält eine Erklärung, die aus den durch logische Operatoren verbundenen Kennungen der Richtlinien besteht.

Die Auswertung der Anweisung `+expression+` muss einen booleschen Wert ergeben.

Policies werden als Funktion dargestellt, die nach dem in der `+.spec.policies+` map angegebenen Bezeichner benannt ist. Die Ergebnisse, die sich aus der Auswertung der Richtlinien ergeben, werden dann mit Hilfe der vom Benutzer angegebenen logischen Operatoren ausgewertet.

Dies sind die unterstützten Operatoren:

* `+&&+`: für die Durchführung von `+AND+` Operationen verwendet
* `+||+`: für die Durchführung von `+OR+` Operationen verwendet
* `+!+`: für die Durchführung von `+NOT+` Operationen verwendet

Sie können runde Klammern `+( )+` verwenden, um Auswertungsprioritäten zu definieren.

Nehmen wir zum Beispiel den folgenden Ausdruck:

[,console]
----
reject_latest() || (signed_by_alice() && signed_by_bob())
----

Die Richtlinie lehnt Workloads mit Bildern ab, die das Tag `+latest+` verwenden, es sei denn, sowohl Alice als auch Bob haben die Bilder signiert.

=== Das Attribut `+message+` und das Antwortformat

Das Feld `+message+` gibt die Meldung an, die zurückgegeben wird, wenn die Auswertung der`+expression+` eine Ablehnung ergibt. Die Antwort enthält die Nachricht zusammen mit den Ergebnissen der Bewertung der einzelnen Maßnahmen.

[IMPORTANT]
====

Eine Evaluierung der zur Gruppe gehörenden Politiken findet nur bei Bedarf statt.

Nehmen wir zum Beispiel den folgenden Ausdruck:

[,console]
----
reject_latest() || (signed_by_alice() && signed_by_bob())
----

Die Richtlinien `+signed_by_bob+` und `+signed_by_alice+` werden nicht ausgewertet, wenn die Richtlinie`+reject_latest+` den Wert `+true+` zurückgibt.

Auf die gleiche Weise wird die Richtlinie `+signed_by_bob+` nicht ausgewertet, wenn die Richtlinien`+signed_by_alice+` und `+reject_latest+` `+false+` zurückgeben.

Dadurch werden unnötige Bewertungen von Richtlinien in der Gruppe vermieden und schnelle Antworten auf die Zulassungsanfragen gewährleistet.

====

Das System sendet alle Bewertungsdetails der Gruppenrichtlinien als Teil der AdmissionResponse `+.status.details.causes+`, wenn eine Gruppenrichtlinie eine Ablehnung durchführt.

Sie können alle Einzelheiten eines abgelehnten Zulassungsantrags erhalten, indem Sie die Ausführlichkeitsstufe von `+kubectl+` erhöhen:

[,shell]
----
kubectl -v4 apply -f signed-pod.yml
I0919 18:29:40.251332    4330 helpers.go:246] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"signed-pod.yml\": admission webhook \"clusterwide-demo.kubewarden.admission\" denied the request: the image is using the latest tag or is not signed by Alice and Bob",
  "details": {
    "causes": [
      {
        "message": "Resource signed is not accepted: verification of image testing.registry.svc.lan/busybox:latest failed: Host error: Callback evaluation failure: Image verification failed: missing signatures\nThe following constraints were not satisfied:\nkind: pubKey\nowner: null\nkey: |\n  -----BEGIN PUBLIC KEY-----\n  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X\n  urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==\n  -----END PUBLIC KEY-----\nannotations: null\n",
        "field": "spec.policies.signed_by_bob"
      },
      {
        "message": "not allowed, reported errors: tags not allowed: latest",
        "field": "spec.policies.reject_latest"
      }
    ]
  },
  "code": 400
}]
Error from server: error when creating "signed-pod.yml": admission webhook "clusterwide-demo.kubewarden.admission" denied the request: the image is using the latest tag or is not signed by Alice and Bob
----

Die vollständige Zulassungsantwort ist in den Protokollen des Policy Servers verfügbar, wenn dieser im Debug-Modus läuft. Außerdem sind die Auswertungsdetails immer Teil der OpenTelemetry-Traces, die vom Policy Server ausgegeben werden.

== Kontextabhängige Politiken

Ein weiterer Unterschied zwischen Richtliniengruppen und normalen Richtlinien ist der Definitionsort der kontextabhängigen Ressourcenregeln. Jede Richtlinie in einer Gruppe akzeptiert ein optionales Feld `+contextAwareResources+` zur Angabe der Ressourcen, auf die die Richtlinie während der Bewertung zugreifen kann. Ähnlich wie bei gewöhnlichen Richtlinien können Sie kontextabhängige Fähigkeiten nur verwenden, indem Sie eine`+ClusterAdmissionPolicyGroup+` definieren. Dies geschieht aus Sicherheitsgründen, da nur unprivilegierte Benutzer `+AdmissionPolicyGroup+` Ressourcen bereitstellen können. Weitere Einzelheiten finden Sie in der Dokumentation zuxref:explanations/context-aware-policies.adoc[kontextabhängigen Richtlinien].

.Ein Beispiel für eine Richtliniengruppe, die eine kontextabhängige Richtlinie verwendet.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo-ctx-aware
spec:
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - services
      operations:
        - CREATE
        - UPDATE
  policies:
    unique_service_selector:
      module: registry://ghcr.io/kubewarden/policies/unique-service-selector-policy:v0.1.0
      contextAwareResources:
        - apiVersion: v1
          kind: Service
      settings:
        app.kubernetes.io/name: MyApp
    owned_by_foo_team:
      module: registry://ghcr.io/kubewarden/policies/safe-annotations:v0.2.9
      settings:
        mandatory_annotations:
          - owner
        constrained_annotations:
          owner: "foo-team"
  expression: "unique_service_selector() || (!unique_service_selector() && owned_by_foo_team())"
  message: "the service selector is not unique or the service is not owned by the foo team"
----
======

Im vorherigen Beispiel kann die Richtlinie `+unique_service_selector+` auf die Ressource`+Service+` zugreifen. Allerdings hat die `+owned_by_foo_team+` keinen Zugriff auf Kubernetes-Ressourcen.

== Validierung der Einstellungen

Wenn der Richtlinienserver startet, überprüft er die Einstellungen von Richtliniengruppen und normalen Richtlinien. Richtliniengruppen durchlaufen jedoch einen zusätzlichen Validierungsschritt, um zu prüfen, ob der Ausdruck gültig ist und einen booleschen Wert ergibt.

== Audit-Scanner

Ähnlich wie bei den CRDs AdmissionPolicy und ClusterAdmissionPolicy gibt das Feld`+backgroundAudit+` an, ob die Richtliniengruppe beixref:../explanations/audit-scanner/audit-scanner.adoc[Prüfungen] berücksichtigt werden soll.

== Policy Server

Sie können die Einstellungsdatei `+policies.yml+` so erweitern, dass sie neben normalen Richtlinien auch Richtliniengruppen enthält. Wie bei gewöhnlichen Policen erfolgt der Download der Module einmalig. Sie verwenden dasselbe Richtlinienmodul sowohl in einer Richtliniengruppe als auch in einer normalen Richtlinie.
