= Hostname anpassen
:revdate: 2025-09-08
:page-revdate: {revdate}

== {elemental-product-name} Übersicht über die Hostnamenverwaltung

Wenn ein Host von {elemental-product-name} ISO bootet, wird der Hostname vorübergehend auf den vom DHCP-Server bereitgestellten Namen gesetzt_(transienter Hostname_).
Wenn der DHCP-Server keinen Hostnamen bereitstellt, bietet {elemental-product-name} ISO einen vorübergehenden Hostnamen in der Form `+rancher-$\{RANDOM}+`.

Sobald der Bootvorgang abgeschlossen ist, beginnt die Registrierungsphase: Der Host verbindet sich mit dem {elemental-product-name} Operator, der eine `+MachineInventory+` für den Host erstellt.
Jeder beim {elemental-product-name} Operator registrierte Host wird von einer `+MachineInventory+` Ressource verfolgt.

*Die `+name+` der `+MachineInventory+` Ressource, die mit dem Knoten verbunden ist, ist der permanente (statische) Hostname**, der schließlich für den Host festgelegt wird*.
Dieser permanente Hostname *wird nur während der Bereitstellungsphase des K8s-Clusters auf dem Knoten festgelegt*.
Vor der K8s-Bereitstellungsphase ist der Knotenhostname entweder der per DHCP zugewiesene oder `+rancher-$\{RANDOM}+`.

Im weiteren Verlauf dieses Abschnitts beziehen wir uns auf `+hostname+` und meinen damit den _permanenten_ Hostnamen, d. h. den Hostnamen, der festgelegt wird, nachdem der Host als Teil eines K8s-Clusters bereitgestellt wurde.

== Standard-Hostname

Der Standardname, der jedem neu erstellten MachineInventory zugewiesen wird, hat die Form `+m-{$UUID}+`.
Wenn der Host als Teil eines Clusters bereitgestellt wird, wird der Name `+m-\{UUID}+` als Hostname des entsprechenden Hosts festgelegt und überschreibt den zuvor zugewiesenen Hostnamen (`+rancher-{$RANDOM}+` oder den per DHCP zugewiesenen).

== Einen benutzerdefinierten Hostnamen festlegen

Der Hostname kann über das Feld xref:references/machineregistration-reference.adoc#_machinename[`+machineName+`] Feld in der Ressourcexref:references/machineregistration-reference.adoc['MachineRegistration'] angegeben werden.

Es wird erwartet, dass der im Feld `+machineName+` angegebene Hostname in Form einer Vorlage vorliegt, damit er unter Verwendung von SMBIOS- und Hardware-Label-Daten für jeden registrierenden Knoten eindeutig generiert werden kann.

[IMPORTANT]
====
Das Feld `+machineName+` in der Ressource `+MachineRegistration+` dient nicht nur als Vorlage für den Hostnamen des registrierenden Hosts, sondern auch für den Namen der Ressource `+MachineInventory+`, die zur Nachverfolgung des Hosts erstellt wurde.

Das bedeutet, dass, wenn Sie keine Vorlage `+machineName+` verwenden, um einen eindeutigen Namen für jeden Rechner zu erzeugen, der mit denselben `+MachineRegistration+` Daten (d.h. derselben ISO) gebootet wird, nur der erste sich registrierende Rechner erfolgreich sein wird, während die anderen scheitern werden: der `+MachineInventory+` Name muss eindeutig sein.
====


importiere Registrierung von "!!raw-loader!@site/examples/quickstart/registration-hardware-dhcphostname.yaml"

== Beibehaltung des von DHCP zugewiesenen Hostnamens

Um den vom DHCP-Server zugewiesenen Hostnamen beizubehalten, bevor sich der Host beim Betreiber registriert, sollte die `+MachineRegistration+` xref:references/machineregistration-reference.adoc#_machinename[`+machineName field+`] auf das `+${System Data/Runtime/Hostname}+` Hardware Label gesetzt werden.

Auf diese Weise wird {elemental-product-name} während der Registrierungsphase den aktuellen Hostnamen als `+MachineInventory+` verwenden, der später während der Bereitstellungsphase als statischer Hostname des Hosts festgelegt wird.

.Registrierungsbeispiel mit Hostname und MachineInventory-Name, die auf den vom DHCP-Server erhaltenen Hostnamen eingestellt sind
[,yaml]
----
include::example$quickstart/registration-hardware-dhcphostname.yaml[]
----
