= Installation
:revdate: 2025-09-08
:page-revdate: {revdate}

== Übersicht

{elemental-product-name} Stack bietet OS-Management mit OCI-Containern und Kubernetes. Die {elemental-product-name}Stack-Installation umfasst die Installation von {elemental_operator_name} im Management-Cluster sowie die Erstellung und Verwendung von Installationsmedien, um das Betriebssystem auf den Cluster-Knoten bereitzustellen. Im Abschnitt xref:rancher-os-management/architecture/architecture.adoc[Architektur] finden Sie Informationen über das Zusammenspiel der Komponenten.

Die Installationskonfiguration wird in den meisten Fällen als Teil des Registrierungsprozesses angewendet und eingestellt.
Der Registrierungsprozess wird von `+elemental-register+` (dem {elemental_operator_name} Client-Teil) durchgeführt, der für die Registrierung von Knoten in einem Rancher-Management-Cluster und das Abrufen der Installationskonfiguration verantwortlich ist.

In der xref:quickstarts/quickstart-cli.adoc[Schnellstartanleitung] finden Sie eine einfache, schrittweise Anleitung zur Einrichtung.

== {elemental-product-name} Installation des Bedieners

Die {elemental_operator_name} ist verantwortlich für die Verwaltung der {elemental-product-name} Versionen und die Pflege eines Maschineninventars, um bei Edge- oder Bare-Metal-Installationen zu helfen. {elemental_operator_name}erfordert einen Cluster mit dem Rancher Manager und kann mit einem Helm Chart installiert werden.

Siehe {elemental_operator_name} xref:references/operatorchart-reference.adoc[helm chart reference] für Details zu Installation, Deinstallation, Upgrade und Konfiguration.

== Kubernetes-Ressourcen vorbereiten

Sobald {elemental_operator_name} innerhalb des Management-Clusters betriebsbereit ist, werden einige Kubernetes-Ressourcen benötigt, um eine {elemental-product-name} -basierte Cluster-Bereitstellung vorzubereiten.

* xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate]:
Diese Ressource gibt die Kriterien für den Abgleich registrierter Boxen (die als Teil des MachineInventory aufgelistet sind) mit verfügbaren Rancher 2.6 Clustern an. Sobald es eine Übereinstimmung gibt, übernimmt der ausgewählte Kubernetes-Cluster das Eigentum an der registrierten Box.
* xref:references/machineregistration-reference.adoc[MachineRegistration]:
Diese Ressource definiert Details zur Betriebssystembereitstellung für jeden Rechner, der sich zu registrieren versucht. Die Maschinenregistrierung ist der Eingang für {elemental-product-name} Knoten, da sie die Authentifizierung (basierend auf TPM), die Bereitstellung des Betriebssystems und die Aufnahme des Knotens in das MachineInventory abwickelt, so dass er zu einem Cluster hinzugefügt werden kann, wenn es eine Übereinstimmung basierend auf einem MachineInventorySelectorTemplate gibt. Das MachineRegistration-Objekt enthält die URL für die Maschinenregistrierung, die von den Knoten verwendet wird, um sich bei ihm zu registrieren.

Eine Rancher-Cluster-Ressource ist ebenfalls erforderlich, um {elemental-product-name} bereitzustellen. Sie kann manuell erstellt werden, wie in der xref:quickstarts/quickstart-cli.adoc[Schnellstartanleitung] beschrieben, oder über die Rancher 2.6-Benutzeroberfläche erstellt werden.

== Installationsmedien vorbereiten

Das Installationsmedium ist das Medium, das für den Start einer Betriebssystembereitstellung verwendet wird. Derzeit wird ein Live-ISO-Medium unterstützt. Die Live-ISO muss die Registrierungskonfiguration yaml enthalten, daher muss sie erstellt werden, sobald die MachineRegistration erstellt ist. Das Installationsmedium wird durch die Erstellung von xref:references/seedimage-reference.adoc[Seed-Image-Ressourcen]erzeugt (siehe xref:quickstarts/quickstart-cli.adoc#_preparing_the_installation_seed_image[Schnellstart] und xref:operator-operational-tasks/custom-images.adoc#_create_a_custom_bootable_installation_iso[benutzerdefinierte Images]).

Das Live-ISO unterstützt PXE-Booting für die direkte Integration mit https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/autoinst-distributions.html#based-on-iso-image[Manager] SUSE.

Innerhalb der MachineRegistration kann nur eine Teilmenge der OS-Installationsparameter konfiguriert werden, alle verfügbaren Parameter sind auf der xref:references/machineregistration-reference.adoc[MachineRegistration-Referenzseite] aufgeführt.

Um die Installation über die allgemeinen Optionen im Abschnittxref:references/machineregistration-reference.adoc#_config_elemental_install[`+elemental.install+`] Abschnitt angegebenen Optionen zu konfigurieren, kann eine `+config.yaml+`Konfigurationsdatei in die ISO-Datei aufgenommen werden (siehe xref:installation/customize-installation/custom-install.adoc#_custom_suse_rancher_prime_os_manager_client_configuration_file[Benutzerdefinierte Images]).
Beachten Sie, dass jede Konfiguration, die als Teil des `+elemental.install+` Abschnitts der Maschinenregistrierung angewendet wird, zusätzlich zu den Einstellungen angewendet wird, die in einer benutzerdefinierten `+config.yaml+` Datei enthalten sind.

In den meisten Fällen reicht die Cloud-Init-Konfiguration aus, um den bereitgestellten Knoten beim Booten zu konfigurieren und einzustellen. Wenn jedoch aus irgendeinem Grund Firstboot-Aktionen oder Skripte erforderlich sind, ist es möglich, auch Rancher System Agent-Pläne in das Installationsmedium aufzunehmen. Einzelheiten und einige Beispielpläne finden Sie im Abschnitt xref:rancher-os-management/plans.adoc[Pläne]. Die Pläne könnten in die gequetschten rootfs im Ordner `+/var/lib/elemental/agent/plans+`eingefügt werden und würden vom Systemagenten beim ersten Start gesehen werden.

== Installationsvorgang starten

Die Installation beginnt mit dem Booten des Installationsmediums auf einem Knoten. Sobald das Installationsmedium hochgefahren ist, versucht es, den Management-Cluster zu kontaktieren und sich bei ihm zu registrieren, indem es den Befehl `+elemental-register+` aufruft.
Da die yaml-Konfiguration für die Registrierung bereits in der ISO enthalten ist, kennt `+elemental-register+` die Registrierungs-URL und alle anderen erforderlichen Daten für die Registrierung.

Bei erfolgreicher Registrierung startet das Installationsmedium die Installation auf dem Host auf der Grundlage der bereits auf dem Medium enthaltenen Konfiguration und der MachineRegistration-Parameter. Sobald die Installation abgeschlossen ist, ist der Knoten zum Neustart bereit. Das bereitgestellte Betriebssystem enthält einen Systemagentenplan, der einen regulären Rancher-Bereitstellungsprozess zur Installation der ausgewählten Kubernetes-Version startet. Nach dem Booten wird die Knoteninstallation nach einigen Minuten abgeschlossen und der Knoten wird in den Cluster aufgenommen und ist über die Rancher-Benutzeroberfläche sichtbar.

== Eingesetzte Partitionstabelle

Sobald das Betriebssystem installiert ist, sieht die Partitionstabelle des Betriebssystems mit den Standardwerten wie folgt aus

|===
| Etikett | Standardgröße | Enthält

| COS_GRUB
| 64 MiB
| UEFI-Boot-Partition

| COS_STATE
| 8 GiB
| A/B bootfähige Dateisystem-Images, die aus OCI-Images erstellt wurden

| COS_OEM
| 64 MiB
| OEM-Cloud-Konfigurationsdateien und andere Daten

| COS_RECOVERY
| 4 GiB
| Wiederherstellung des Dateisystemabbilds, wenn COS_STATE zerstört ist

| COS_PERSISTENT
| Verbleibender Platz
| Alle Inhalte der persistenten Verzeichnisse
|===

Beachten Sie, dass dies die Grundstruktur eines jeden Betriebssystems ist, das von {elemental_toolkit_url}[{elemental_toolkit_name}] entwickelt wurde.

== {elemental-product-name} Unveränderliche Wurzel

Eines der Merkmale von {elemental-product-name} Betriebssystemen ist die Einrichtung eines unveränderlichen Root-Dateisystems, auf das einige ephemere oder persistente Speicherorte aufgebracht werden. Die Standard-Ordnerstruktur ist in der nachstehenden Matrix aufgeführt.

[cols=",^,^,^"]
|===
| Pfad | Schreibgeschützt | Ephemeral | Persistent

| /
| x
|
|

| /etc
|
| x
|

| /etc/cni
|
|
| x

| /etc/iscsi
|
|
| x

| /etc/rancher
|
|
| x

| /etc/ssh
|
|
| x

| /etc/systemd
|
|
| x

| /srv
|
| x
|

| /home
|
|
| x

| /opt
|
|
| x

| /Wurzel
|
|
| x

| /var
|
| x
|

| /usr/libexec
|
|
| x

| /var/lib/cni
|
|
| x

| /var/lib/kubelet
|
|
| x

| /var/lib/rancher
|
|
| x

| /var/lib/elemental
|
|
| x

| /var/lib/NetworkManager
|
|
| x

| /var/lib/calico
|
|
| x

| /var/log
|
|
| x
|===
