= Visão geral dos modelos de etiquetas
:revdate: 2025-09-08
:page-revdate: {revdate}

O Elemental permite especificar _modelos de rótulos_ nas seções `spec.machineInventoryLabels` e `spec.machineInventoryAnnotations` dos recursos xref:references/machineregistration-reference.adoc[MachineRegistration].

Seu formato é o canônico `key`:``value`` usado em rótulos e anotações do Kubernetes.

Esses modelos de etiquetas são convertidos em etiquetas e anotações reais anexadas a cada recurso xref:references/machineinventory-reference.adoc[do MachineInventory] criado durante a fase xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[de integração da máquina].

Os rótulos e anotações resultantes têm o mesmo `key` do modelo de rótulo.

O site `value` associado é gerado:

* *renderização do site <<_label_templates_variables,`label template variables`>>* (se houver)
* *`sanitizing`* o valor resultante (somente no caso dos rótulos)

[IMPORTANT]
====
A funcionalidade de modelagem do Elemental também abrange o campo xref:references/machineregistration-reference.adoc[MachineRegistration] `spec.machineName`, que define o nome de host resultante da máquina de registro e o `name` do recurso xref:references/machineinventory-reference.adoc[MachineInventory] associado.

Consulte a seção <<_custom_machine_names,Nome da máquina>> para obter mais detalhes.
====


== Variáveis de modelos de rótulos

O Elemental Label Templating inclui um conjunto de variáveis predefinidas que podem ser usadas no site `value` dos _modelos de rótulos_ especificados no xref:references/machineregistration-reference.adoc[MachineRegistration].

A sintaxe usada para especificar as variáveis dos modelos de rótulos é:

`${ _VARFAMILY_ \/ _VARPATH_ }`

em que _VARFAMILY_ define um grupo (família) de variáveis suportadas e _VARPATH_ define o nome real da variável dentro do grupo de famílias pertencentes.

Atualmente, o Elemental suporta as seguintes _famílias de variáveis de modelo_:

* xref:label-templates/label-templates-bios.adoc[*BIOS*]: *${ BIOS \/* _VARPATH_ *}*
* xref:label-templates/label-templates-baseboard.adoc[*Quadro de Base*]: *${ BaseBoard \/* _VARPATH_ *}*
* xref:label-templates/label-templates-cpu.adoc[*CPU*]: *${ CPU \/* _VARPATH_ *}*
* xref:label-templates/label-templates-chassis.adoc[*Chassi*]: *${ Chassi \/* _VARPATH_ *}*
* xref:label-templates/label-templates-gpu.adoc[*GPU*]: *${ GPU \/* _VARPATH_ *}*
* xref:label-templates/label-templates-memory.adoc[*Memória*]: *${ Memória \/* _VARPATH_ *}*
* xref:label-templates/label-templates-network.adoc[*Rede*]: *${ Rede \/* _VARPATH_ *}*
* xref:label-templates/label-templates-product.adoc[*Produto*]: *${ Product \/* _VARPATH_ *}*
* xref:label-templates/label-templates-runtime.adoc[*Tempo de execução*]: *${ Runtime \/* _VARPATH_ *}*
* xref:label-templates/label-templates-storage.adoc[*Armazenamento*]: *${ Storage \/* _VARPATH_ *}*

[CAUTION]
====
Todas as _famílias de variáveis de modelo_ (exceto _`Random`_) são ativadas somente se o campo `elemental.registration.no-smbios` do xref:references/machineregistration-reference.adoc[MachineRegistration] estiver definido como `false` (padrão).

Quando o campo `elemental.registration.no-smbios` é definido como `true`, as máquinas registradoras não enviam nenhum dado necessário para renderizar as variáveis de modelo, portanto, nenhuma variável estará disponível, exceto as variáveis *Random*, que são a única exceção notável.

As variáveis *aleatórias* estão sempre disponíveis, pois são incorporadas no lado do operador. Elas também são especiais, pois são computadas apenas uma vez: consulte a seção xref:label-templates/label-templates-random.adoc[Variáveis de modelo aleatório] para obter mais detalhes.
====


As variáveis de modelo podem ser misturadas com texto estático para formar os rótulos reais atribuídos axref:references/machineinventory-reference.adoc[(MachineInventories]).

[NOTE]
.Exemplos de renderização
====

* Modelo de rótulo que rastreia o número de núcleos de CPU do host de registro (suponha que o host tenha 4 núcleos):
 ** Etiqueta original: *cpu: ${CPU\/TotalCores}* -cores
 ** Etiqueta renderizada: *cpu: 4 núcleos*
* Modelo de rótulo que rastreia o SMBIOS UUID do host de registro:
 ** rótulo original: *sbios-UUID: ${Product\/UUID}*
 ** rótulo renderizado: *sbios-UUID: fd95324a-c26b-4e28-8727-1dcec293a0ec*
====


== Sanitização

Depois que o valor do modelo de rótulo tiver sido renderizado de acordo com as <<_label_templates_variables,variáveis de modelo de rótulo>> incluídas, o valor resultante será `sanitized` antes de ser atribuído ao rótulo resultante.

*O site `sanitization` impõe que o valor do rótulo contenha apenas letras (maiúsculas ou não), números e os caracteres hífen (`-`), ponto (`.`) e sublinhado (`_`*):

Todos os caracteres não incluídos são substituídos por um hífen.

Qualquer caractere no início e no final do valor do rótulo deve ser uma letra ou um número. Se não for, será descartado.

Dois hífens consecutivos são substituídos por um.

[NOTE]
.Exemplo de renderização
====

* Modelo de rótulo com sanitização de caracteres proibidos:
 ** rótulo original: *higienizado: isto: precisa de--higienização!*
 ** rótulo renderizado: *sanitized: this-needs-sanitizing*
====


== Uso de modelos de etiquetas

Os modelos de etiqueta permitem anexar e atualizar automaticamente etiquetas e anotações no xref:references/machineinventory-reference.adoc[MachineInventory] de cada host sempre que um host se registrar no Elemental Operator.

[IMPORTANT]
====
O registro não ocorre apenas durante a xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[fase de integração]: cada host se registra novamente a cada 30 minutos (e sempre que é reinicializado). Durante o novo registro, os modelos de etiqueta no xref:references/machineregistration-reference.adoc[MachineRegistration] associado são reavaliados e adicionados/atualizados no xref:references/machineinventory-reference.adoc[MachineInventory].
====


Há basicamente três casos principais em que os modelos de etiquetas podem ser úteis:

* para anexar dados de hardware ao Catálogo Elementar.
* para adicionar seletores para selecionar hosts para o Provisionamento de cluster.
* para definir um modelo personalizado para os nomes de máquinas.

=== Dados de hardware para o catálogo Elemental

As variáveis dos Label Templates podem ser usadas para anexar dados de hardware a cada recurso xref:references/machineinventory-reference.adoc[MachineInventory] (que formam o Catálogo Elementar).

Nesse caso, as anotações podem ser uma opção melhor, pois seus valores não são higienizados.

=== Seletores para provisionamento de cluster

O site `Label Templates` pode ser usado para gerar rótulos usados para identificar e selecionar máquinas com propriedades especiais de hardware para formar novos clusters do Kubernetes.

Os rótulos anexados a cada xref:references/machineinventory-reference.adoc[MachineInventory] são elegíveis para o _seletor_ do recurso xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate] (consulte a seção xref:rancher-os-management/architecture/services/architecture-clusterdeployment.adoc[de provisionamento do Kubernetes Cluster] para obter mais detalhes).

=== Nomes de máquinas personalizados

O nome do host da máquina de integração pode ser especificado usando o campo xref:references/machineregistration-reference.adoc[MachineRegistration] `spec.machineName`.

`spec.machineName` passa pelos mesmos processos `Label Templates' variables` e `sanitization` reservados ao campo `spec.machineInventoryLabels`.

[CAUTION]
====
Há uma diferença notável entre os campos xref:references/machineregistration-reference.adoc[MachineRegistration] `spec.machineName` e `spec.machineInventorylabels`: durante o processo <<_sanitization,de sanitização>>, o sublinhado (`_`) é substituído pelos outros caracteres proibidos (ou seja, é substituído por um hífen: `-`). Isso é necessário porque o sublinhado não é permitido nos nomes de host do Linux.
====


Para obter mais informações sobre como definir o nome de host para hosts do Elemental, consulte a seção xref:installation/hostname.adoc[HowTo/Customize hostname].

[NOTE]
.Exemplo de renderização
====
* Defina um modelo de nome de host como `SLE-Micro-[random string of 6 hexadecimal values]`:
 ** MachineRegistration spec: *machineName: SLE-Micro-${Random\/Hex\/6}*
 ** Nome do MachineInventory: *SLE-Micro-32ad41*
====


== Exemplo de modelos de etiquetas

.Exemplo de registro com variáveis de modelos de rótulos
[,yaml]
----
include::example$quickstart/registration-hardware-dhcphostname.yaml[]
----
