= Variáveis de modelo aleatórias
:revdate: 2025-09-08
:page-revdate: {revdate}

As variáveis de modelo aleatórias são incorporadas no Elemental Operator.

Eles permitem incluir valores aleatórios `Int`, `Hex` ou `UUID` em xref:label-templates/label-templates.adoc[modelos de rótulos] personalizados.

Os valores são computados em tempo real durante a renderização do `label template variables`.

[IMPORTANT]
.Os modelos de rótulos aleatórios são renderizados apenas uma vez
====

Um modelo de etiqueta que contém uma variável aleatória é renderizado somente se o xref:references/machineinventory-reference.adoc[MachineInventory] do host de registro ainda não tiver um valor para essa etiqueta (uma etiqueta com a mesma chave está faltando ou seu valor está vazio).

Portanto, os três casos em que um modelo de rótulo com uma variável aleatória é renderizado são

. o host está se registrando pela primeira vez e o xref:references/machineinventory-reference.adoc[MachineInventory] é criado novamente.
. o modelo de etiqueta foi adicionado ao MachineRegistration depois que o host se (re)registrou pela última vez.
. a etiqueta xref:references/machineinventory-reference.adoc[MachineInventory] que corresponde ao modelo de etiqueta (mesma chave de etiqueta) foi removida manualmente ou seu valor foi apagado.
====


|===
| Variável | Descrição | de

| `${Random/UUID}`
| UUID aleatório (por exemplo, fd95324a-c26b-4e28-8727-1dcec293a0ec)
| 1.7.0

| `${Random/Hex/[1-32]}`
| string hexadecimal aleatória do comprimento especificado (mínimo 1, máximo 32)
| 1.7.0

| `${Random/Int/[MAXINT]`
| número inteiro aleatório (mínimo 0, máximo MAXINT-1)
| 1.7.0
|===

[NOTE]
.Exemplos de renderização
====
|===
| valor do modelo | exemplo de valor renderizado

| `${Random/UUID}`
| fd95324a-c26b-4e28-8727-1dcec293a0ec

| `${Random/Hex/12}`
| acd231f222b8

| `${Random/Int/10000}` 
| 9432

|===
====


As variáveis de modelo aleatórias podem ser úteis para gerar nomes de host personalizados a serem atribuídos ao host de registro.

Como o nome do host deve ser exclusivo e é atribuído por meio do campo xref:references/machineregistration-reference.adoc[MachineRegistration] `spec.machineName`, as variáveis aleatórias podem ser usadas para garantir a exclusividade de um grupo de hosts que compartilham o mesmo prefixo e/ou sufixo personalizado.

Consulte a seção xref:installation/hostname.adoc[HowTo/Customize hostname] para obter mais informações.

.exemplo de registro Variáveis de modelo aleatórias
[,yaml]
----
include::example$quickstart/registration-random-hostname.yaml[]
----
