include::partial$variables.adoc[]

= プロキシ設定
:description: {project-name} でプロキシを使う .
:keywords: ["{project-name}", "kubewarden", "kubernetes", "proxy", "proxies"]
:doc-persona: ["kubewarden-user"、"kubewarden-operator"、"kubewarden-distributor"、"kubewarden-integrator"]]。
:doc-type: ["howto"]
:doc-topic: [オペレーターマニュアル」、「プロキシ」]。

`kwctl` と`policy-server` の両方で、HTTPとHTTPSのプロキシを設定でき、このプロキシ設定からドメインを除外することもできる。

これには2つの方法がある：* 環境変数`HTTP_PROXY` 、`HTTPS_PROXY` 、`NO_PROXY`（およびそれらの小文字の対応）を`kwctl` または`policy-server` に設定する。
  PolicyServer CR を構成するには、`spec.env` 配列を設定します。*`--sources-path` 引数で`sources.yaml` ファイルを指定します。
  `sources.yaml` ファイルは環境変数より優先される。
  `spec` フィールドを介してこの構成を消費することは、PolicyServer CR ではまだ公開されていません。

影響力のあるプロキシ設定の設定

* OCIレジストリから、あるいはOCIレジストリへのポリシーのプル、プッシュ、プルアンドラン。
* 以下のような、コンテキストを意識した呼び出しによるホスト機能：
** OCIマニフェストやマニフェスト・ダイジェストの取得のようなコンテナ登録。
   OCIレジストリを直接叩く代わりに、トラフィックは設定されたプロキシを経由する。
** キーレス署名の検証のようなシグストアの機能。
   Sigstoreで定義されたサービスにアクセスする代わりに、トラフィックは設定されたプロキシを経由する。

== 例

以下の環境変数を、`kwctl` または`policy-server` (PolicyServer`spec.env` を通して) 設定できます：

[source,bash]
----
HTTP_PROXY="http://proxy.corp:3128"
https_proxy="http://proxy.corp:3129"
NO_PROXY="localhost,.corp"
----

この構成では* 安全でないOCIレジストリとの間のようなHTTP経由の安全でないトラフィックは、`\http://proxy.corp:3128` を経由してルーティングされます。
  これは、引き抜きポリシー、およびそのリポジトリ内のコンテナの OCI イメージマニフェストダイジェストを持つコンテキスト対応機能を呼び出すポリシーに影響します。* HTTPS 経由の暗号化されたトラフィックは、`\https://proxy.corp:3129` を介してルーティングされます。
  たとえば、安全な OCI レジストリへのポリシーのプルやプッシュ、ポリシーのコンテキスト認識機能などが含まれます。* localhostまたは`.corp` 以下のドメインとのトラフィックは、前述の構成から除外されます。


== `sources.yaml` ファイル

詳細は xref:/reference/sources_yaml.adoc[`sources.yaml`]を参照してください。