= Depreciação da bandeira
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-09
:page-revdate: {revdate}

O K3s é um projeto em rápida evolução e, por isso, precisamos de uma maneira de descontinuar sinalizadores e opções de configuração. Esta página descreve o processo de preterição de sinalizadores e opções de configuração. Para garantir que os usuários não sejam surpreendidos pela remoção dos sinalizadores, o processo é semelhante à https://kubernetes.io/docs/reference/using-api/deprecation-policy/[Política de descontinuidade do Kubernetes].

== Processo

. Os sinalizadores podem ser declarados como "To Be Deprecated" a qualquer momento.
. Os sinalizadores "To Be Deprecated" devem ser rotulados como tal no próximo patch de todas as versões atualmente suportadas. Além disso, o sinalizador começará a avisar aos usuários que ele será descontinuado na próxima versão secundária.
. Na próxima versão secundária, um sinalizador será marcado como obsoleto na documentação e convertido em um sinalizador oculto no código. A bandeira continuará a operar e a emitir avisos aos usuários.
. Na ramificação de versão secundária seguinte, os sinalizadores obsoletos se tornarão "não operacionais", causando um erro fatal se forem usados. Esse erro deve explicar ao usuário qualquer novo sinalizador ou configuração que substitua esse sinalizador.
. Na próxima versão secundária, os sinalizadores não operacionais serão removidos da documentação e do código.

== Exemplo

Um exemplo do processo:

* `+--foo+` existe nas versões v1.22.14, v1.23.10 e v1.24.2.
* Após a versão v1.24.2, foi decidido descontinuar o `+--foo+` em favor do `+--new-foo+`.
* Nas versões v1.22.15, v1.23.11 e v1.24.3, o site `+--foo+` continua a existir, mas avisa os usuários:
+
----
[Warning] --foo will be deprecated in v1.25.0, use `+--new-foo+` instead
----
+
`+--foo+` continuará a existir como um sinalizador operacional durante a vida útil da v1.22, v1.23 e v1.24.

* Na versão 1.25.0, `+--foo+` está marcado como obsoleto na documentação e será ocultado no código. Ele continuará a funcionar e avisará os usuários para que mudem para `+--new-foo+`.
* Na versão 1.26.0, o site `+--foo+` causará um erro fatal se for usado. A mensagem de erro indicará:
+
----
[Fatal] exit 1: --foo is no longer supported, use --new-foo instead
----

* Na versão v1.27.0, o endereço `+--foo+` será completamente removido de todo o código e da documentação.
