= 组群参考
:revdate: 2025-09-08
:page-revdate: {revdate}

`Cluster` 定义包括`kubernetesVersion` 和要部署群集的`machinePools` 列表。

有关如何选择`kubernetesVersion` ，请查看我们的xref:references/kubernetesversions.adoc[Kubernetes 版本]页面。

`machinePool` 是带有`ObjectReference` 的配置捆绑包，因此群集会部署到具有适当角色（etcd、控制平面、工作者）的`machinePools`上，并带有数量（从该池部署多少节点）和一些额外配置（滚动更新配置、最大不健康节点等... ）。

.点击此处了解详情
[%collapsible]
====
.示例
[,yaml]
----
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: ...
  namespace: ...
spec:
  rkeConfig:
    machinePools:
      - name: ...
        controlPlaneRole: ...
        etcdRole: ...
        workerRole: ...
        quantity: ...
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: ...
      - name: ...
        controlPlaneRole: ...
        etcdRole: ...
        workerRole: ...
        quantity: ...
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: ...
----
====


例如，还可以通过`spec.rkeConfig.machineGlobalConfig` 中的`Cluster` 对象禁用群集组件：

.点击此处了解详情
[%collapsible]
====
.服务禁用示例
[,yaml]
----
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: ...
  namespace: ...
spec:
  rkeConfig:
    machinePools:
      - name: ...
        controlPlaneRole: ...
        etcdRole: ...
        workerRole: ...
        quantity: ...
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: ...
    machineGlobalConfig:
      disable:
        - servicelb
        - ...
----
====


== rkeConfig.machinePools

`machinePools`.部署群集至少需要 1 个`machinePools` 。

== machinePools 规范参考

|===
| 钥匙 | 类型 | 默认值 | 说明

| controlPlaneRole
| bool
| 错误
| 将该池中的机器设置为控制平面

| etcdRole
| bool
| 错误
| 将该池中的机器设置为 etcd

| workerRole
| bool
| 错误
| 将该池中的机器设置为工作站

| 名字
| 字符串
| 零
| 水池名称

| 数量
| int
| 零
| 从该池部署的机器数量

| unhealthyNodeTimeout
| int
| 零
| 不健康节点健康检查超时

| machineConfigRef
| int
| ObjectReference
| 用于了解哪些节点属于此节点池的对象的引用
|===

要使用该池，至少需要将`quantity` 设为 1。
基本上就是说，这个集群要从这个池中设置多少个节点。

.点击此处了解详情
[%collapsible]
====
.示例
[,yaml]
----
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: cluster-example
  namespace: example-default
spec:
  rkeConfig:
    machinePools:
      - name: examplePool 
        controlPlaneRole: true
        etcdRole: true
        workerRole: false
        quantity: 3
        unhealthyNodeTimeout: 0s
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: exampleSelector
----
====


== machineConfigRef Spec 参考

`machineConfigRef` 是一个通用的 k8s`ObjectReference` ，通常包含`kind` `name` 和`apiVersion` ，以指向不同的对象。

在{elemental-product-name} 中，我们将其设置为xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate]。
这样，我们就可以通过使用选择器来指向多个对象。

=== 示例

下面的示例创建了一个群集，该群集使用 2 个不同的``machinePool``，将不同的节点设置为控制平面节点和工作者节点，基于 2 个不同的`MachineInventorySelectorTemplate` ，这些节点根据`MachineInventory` 标签（位置）选择：

[CAUTION]
.警告
====
示例中的标签是手动设置的标签，并非由{elemental-product-name} 自动设置。
====

.具有多个机器池的群集示例
[,yaml]
----
include::example$clusters/clusters-several-machinepools.yml[]
----
