= ManagedOSImage 引用
:revdate: 2025-11-06
:page-revdate: {revdate}

ManagedOSImage 资源负责定义需要应用到一组目标集群中每个节点的操作系统映像或映像版本。一旦创建，ManagedOSImage 资源就可以用新的`osImage` 或`managedOSVersionName` 更新，以触发新的升级。同样，现有的 ManagedOSImage 也可以更新为新的集群目标。

`ManagedOSImage` 资源规范下可配置多个密钥。

.upgrade-cluster-target.yaml
[,yaml]
----
include::example$upgrade/upgrade-cluster-target.yaml[]
----

== `ManagedOSImageSpec` 参照

|===
| 钥匙 | 类型 | 默认值 | 说明

| osImage
| 字符串
| 空的
| 要将节点升级到的完全合格映像。如果同时配置了这两个值，则该值的优先级高于`managedOSVersionName` 。

| managedOSVersionName
| 字符串
| 空的
| 要将节点升级到的`ManagedOSVersion` 的名称。

| cloudConfig
| 反对
| 无效
| 在升级过程中应用于节点的 cloud-init 或 yip 配置。参见<<_cloudconfig,参考文献>>。

| nodeSelector
| 反对
| 无效
| 该选择器可用于定位`clusterTargets` 中的特定节点。参见<<_nodeselector,参考文献>>。

| 并发性
| int
| 1
| 同一群集中有多少个节点应同时升级。

| 警戒
| bool
| true
| 如果要在应用升级之前封锁节点，请将此设置为 true。当同时配置`drain` 时无效。

| 浍
| 反对
| 参见参考文献
| 配置在应用升级前是否以及如何排空节点。参见<<_drain,参考文献>>。

| 编写
| 反对
| 无效
| 如果指定了 prepare init 容器，它将在 cordon/drain 之前运行，而 cordon/drain 将在 upgrade 容器之前运行。参见<<_prepare,参考文献>>。

| upgradeContainer
| 反对
| 无效
| 将在节点上运行升级的升级容器。参见<<_upgradecontainer,参考文献>>。

| clusterRolloutStrategy
| 反对
| 无效
| RolloverStrategy 控制升级捆绑包在群集间的推广。参见<<_clusterrolloutstrategy,参考文献>>。

| clusterTargets
| 清单
| 无效
| 声明要将升级计划部署到的群集。参见<<_clustertargets,参考文献>>。
|===

== `cloudConfig`

此处描述的是云启动或 yip 配置，将被复制到每个升级节点的`/oem/90_operator.yaml` 路径。 +
系统将在重启后应用该配置。 +
有关详细信息和示例，请参阅`MachineRegistration` `spec.config.cloud-config` xref:references/cloud-config-reference.adoc[参考资料]。

== `nodeSelector`

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[标签选择器]可用于将升级限制在目标集群内的某一组节点上。

.点击此处了解详情
[%collapsible]
====
[,yaml]
----
nodeSelector:
  matchExpressions:
  - {key: my-node/label, operator: Exists}
----
====

== `drain`

配置是否以及如何排空节点。 +
要在升级过程中禁用泄放功能，可以将该字段配置为`null` 。 +
默认情况下已启用排水功能。

排水设置直接转换为升级前在节点上执行的https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drain] kubectl命令。

|===
| 钥匙 | 类型 | 默认值 | 说明

| 超时
| time.Duration
| 无效
| 放弃节点排水前等待的时间长度，零表示无限。

| gracePeriod
| int
| 无效
| 给每个 pod 从容终止的时间段（以秒为单位）。如果为负值，则使用 pod 中指定的默认值。

| deleteEmptydirData
| bool
| true
| 即使有 pod 使用 emptyDir（节点耗尽时将删除的本地数据），也要继续。

| ignoreDaemonSets
| bool
| true
| 忽略 DaemonSet 管理的 pod。

| force
| bool
| true
| 即使有 pod 没有声明控制器，也要继续。

| disableEviction
| bool
| 错误
| 强制排水道使用删除，即使支持驱逐。这将绕过 PodDisruptionBudgets 检查，请谨慎使用。

| skipWaitForDeleteTimeout
| int
| 60
| 如果 pod DeletionTimestamp 超过 N 秒，则跳过等待 pod。秒必须大于 0 才能跳过。

| podSelector
| 标签选择器
| 无效
| 标签选择器，用于过滤节点上的 pod。只有选定的 pod 才会被驱逐。
|===

== `prepare`

定义`prepare` Init 容器，它在节点上执行升级作业的`upgrade` 容器之前运行。 +
这些键可直接转化为https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container[容器]规范。 +
请注意，节点文件系统挂载在容器内的`/host` 。

|===
| 钥匙 | 类型 | 默认值 | 说明

| 图像
| 字符串
| 空的
| 容器图像名称。

| 指挥部
| 清单
| 空的
| 入口点数组。

| 参数
| 清单
| 空的
| 入口点的参数。

| 环境
| 清单
| 空的
| 要在容器中设置的环境变量列表。

| envFrom
| 清单
| 空的
| 用于填充容器中环境变量的来源列表。

| 流量
| 清单
| 空的
| `hostPath` 卷清单。参见<<_prepare_volumes,参考文献>>。

| securityContext
| 反对
| 无效
| 运行短暂容器时应使用的安全选项。
|===

=== `prepare.volumes`

每个卷定义都将转化为https://kubernetes.io/docs/concepts/storage/volumes/#hostpath-volume-types[hostPath]卷 (`source`) ，该卷将被挂载到容器 (`destination`) 中。 +
请注意，默认情况下，主机根文件系统`/` 将始终挂载在`/host` 上。

|===
| 钥匙 | 类型 | 默认值 | 说明

| 名字
| 字符串
| 空的
| 卷名。

| 消息来源
| 字符串
| 空的
| HostPath 磁盘卷路径。

| 目的地
| 字符串
| 空的
| HostPath 卷挂载路径。
|===

.点击此处了解详情
[%collapsible]
====
[,yaml]
----
volumes:
  - name: my-custom-volume
    source: /foo
    destination: /foo
----
====

== `upgradeContainer`

定义在节点上执行升级任务的`upgrade` 容器。 +
这些键可直接转化为https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container[容器]规范。 +
请注意，节点文件系统挂载在容器内的`/host` 。

[CAUTION]
====
在使用任何xref:operator-operational-tasks/custom-images.adoc[基于] {elemental-product-name} 或xref:operator-operational-tasks/custom-images.adoc[{elemental-product-name} 的图像]时，您只需编辑`env` 密钥，即可选择设置`FORCE` 、`UPGRADE_RECOVERY` 或`UPGRADE_RECOVERY_ONLY` 变量。 +
更多信息，请阅读xref:node-operational-tasks/upgrade.adoc#_upgrade_via_command_line_interface[升级]文档。 +
对`upgradeContainer` 的任何其他更改都可能导致升级时出现问题。 +
====

== `clusterRolloutStrategy`

这可以控制捆绑包在集群中的展开。如需了解更多信息，请阅读https://documentation.suse.com/cloudnative/continuous-delivery/v0.13/en/reference/ref-crds.html#_rolloutstrategy[参考文档]。

== `clusterTargets`

选择操作系统映像升级的目标群集。如需了解更多信息，请阅读https://documentation.suse.com/cloudnative/continuous-delivery/v0.13/en/reference/ref-crds.html#_bundletarget[参考文档]。

.点击此处了解详情
[%collapsible]
====
[,yaml]
----
clusterTargets:
  - clusterName: volcano
----
====
