include::partial$variables.adoc[]
= Erstellen und Ausführen einer Gatekeeper-Richtlinie
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Entwicklung und Bereitstellung einer Gatekeeper-Richtlinie unter Verwendung der bekannten Rego-Syntax und -Tools zur Durchsetzung der Zugangskontrolle in Kubernetes-Umgebungen.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "build-and-run"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "gatekeeper policy", "rego"]
:sidebar_label: Erstellen und ausführen
:current-version: {page-origin-branch}

Sie können die Richtlinie genauso erstellen und ausführen wie eine Rego-Richtlinie, die auf Open Policy Agent abzielt.
Die Struktur Ihres Projekts ist wie folgt:

----
.
├── data
│   ├── default-ns.json
│   └── other-ns.json
└── policy.rego

1 directory, 3 files
----

== Bauen Sie

Erstellen Sie die Richtlinie, indem Sie den Befehl `opa` ausführen:

[subs="+attributes",shell]
----
$ opa build -t wasm -e policy/violation policy.rego
----

Dies bildet die Rego-Politik, mit:

* `target`: `wasm`. Wir wollen die Politik auf das Ziel `wasm` ausrichten.
* `entrypoint`: `policy/violation`. Der Einstiegspunkt ist die Regel `violation`innerhalb des Pakets `policy`.
* `policy.rego`: Erstellen und Einbinden der Datei `policy.rego`.

Der frühere Befehl erzeugt eine Datei `bundle.tar.gz`.
Sie können das Wasm-Modul daraus extrahieren:

[subs="+attributes",shell]
----
$ tar -xf bundle.tar.gz /policy.wasm
----

Der Projektbaum sieht wie folgt aus:

----
.
├── bundle.tar.gz
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
└── policy.wasm

1 directory, 5 files
----

Sie können nun Ihre Richtlinie ausführen.

== ausführen.

Verwenden Sie `kwctl`, um Ihre Richtlinie wie folgt auszuführen:

 $ kwctl run -e gatekeeper --request-path data/other-ns.json policy.wasm | jq
 {
   "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
   "allowed": true
 }

Dies ist Ihre Ressource, die im Namespace `other` erstellt wurde und erwartungsgemäß akzeptiert wird.

Jetzt können Sie eine Anforderung ausführen, die von der Richtlinie abgelehnt wird:

[subs="+attributes",console]
----
$ kwctl run -e gatekeeper --request-path data/default-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "it is forbidden to use the default namespace"
  }
}
----

Sie können sehen, dass Ihre Gatekeeper-Richtlinie diese Ressource ablehnt.
