include::partial$variables.adoc[]
= Verteilen einer Gatekeeper-Richtlinie mit {project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Verteilen Sie Gatekeeper-Richtlinien über Kubernetes-Cluster, indem Sie die Richtliniendateien mit Metadaten versehen und sie über ClusterAdmissionPolicy bereitstellen.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "gatekeeper", "rego"]
:current-version: {page-origin-branch}

Richtlinien müssen mit Anmerkungen versehen werden, damit sie gepusht und schließlich von {project-name} `policy-server` in einem Kubernetes-Cluster ausgeführt werden können.

Das Kommentieren und Verteilen einer Gatekeeper-Richtlinie ist ähnlich wie das Verteilen einer Open Policy Agent-Richtlinie.

== Kommentierung der Politik

Sie schreiben eine Datei `metadata.yaml` in Ihr Richtlinienverzeichnis mit Inhalt:

[subs="+attributes",yaml]
----
rules:
- apiGroups: [""]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["CREATE"]
mutating: false
contextAware: false
executionMode: gatekeeper
annotations:
  io.kubewarden.policy.title: no-default-namespace
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: This policy will reject any resource created inside the default namespace
  io.kubewarden.policy.author: The {short-project-name} Authors
  io.kubewarden.policy.url: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.source: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
      This policy is just an example.

      You can write interesting descriptions about the policy here.
----

können Sie sehen, dass alles mit den Metadaten der Open Policy Agent-Version übereinstimmt, mit Ausnahme des Bits `executionMode: gatekeeper`.

Machen Sie weiter und kommentieren Sie die Richtlinie:

[subs="+attributes",console]
----
$ kwctl annotate policy.wasm --metadata-path metadata.yaml --output-path annotated-policy.wasm
----

== Die Politik vorantreiben

Übermitteln Sie Ihre Police an ein OCI-Register:

[subs="+attributes",console]
----
$ kwctl push annotated-policy.wasm registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
Policy successfully pushed
----

== Bereitstellung in Kubernetes

Sie müssen Ihre Police zuerst bei Ihrer `kwctl` Filiale abschließen:

[subs="+attributes",console]
----
$ kwctl pull registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
pulling policy...
----

Sie können nun eine Gerüstressource `ClusterAdmissionPolicy` erstellen:

[subs="+attributes",console]
----
$ kwctl scaffold manifest registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1 --type ClusterAdmissionPolicy
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Verwenden Sie nun diese `ClusterAdmissionPolicy` Ressource, um Ihre Richtlinie in einem Kubernetes-Cluster bereitzustellen.
