= Aplicativos Java
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

O Java SDK oferece suporte a aplicativos de instrumentação na JVM. Como resultado, ele não só oferece suporte a Java, mas também a outras linguagens JVM, como Kotlin e Scala.

== Instrumentação automática

A instrumentação automática para Java usa um JAR de agente Java que pode ser anexado a qualquer aplicativo Java 8+. Ele injeta dinamicamente bytecode para capturar a telemetria de muitas https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md[bibliotecas e estruturas], incluindo várias bibliotecas Kotlin e Scala. Ele pode ser usado para capturar dados de telemetria no site "`edges`" de um aplicativo ou serviço, como solicitações de entrada, chamadas HTTP de saída, chamadas de banco de dados e assim por diante.

A instrumentação automática não exige nenhuma modificação no aplicativo. Para configurá-lo, siga estas etapas:

. Faça o download de https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar[opentelemetry-javaagent.jar] em https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases[Releases] do repositório opentelemetry-java-instrumentation e inclua o arquivo JAR na imagem da janela de encaixe do seu aplicativo. O arquivo JAR contém o agente e as bibliotecas de instrumentação.
. Atualize o comando que inicia seu aplicativo para carregar o agente Java, seja atualizando o ponto de entrada ou o comando da imagem do Docker ou atualizando o `command` no manifesto do Kubernetes para seu aplicativo. Adicionar `-javaagent:/path/to/opentelemetry-javaagent.jar`:
+
[,bash]
----
java -javaagent:/path/to/opentelemetry-javaagent.jar -jar myapp.jar
----

. Implemente seu aplicativo com as variáveis de ambiente adicionais xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[para configurar o nome do serviço e o ponto de extremidade do exportador]; os protocolos compatíveis são gRPC e protobuf sobre HTTP.
. Verifique se o SUSE Observability está recebendo rastreamentos e/ou métricas, procurando as métricas/rastreamentos no explorador de métricas/rastreamentos para o nome do seu serviço

Para obter mais detalhes, consulte a https://opentelemetry.io/docs/languages/java/automatic/[documentação do].

== Instrumentação manual

A instrumentação manual pode ser usada quando você precisa de métricas, rastreamentos ou registros de partes do código que não são compatíveis com a instrumentação automática. Por exemplo, bibliotecas sem suporte, código interno ou métricas de nível comercial.

Para capturar esses dados, você precisa modificar seu aplicativo.

. Incluir o Open Telemetry SDK como uma dependência
. Adicione código ao seu aplicativo para capturar métricas, períodos ou registros quando necessário

Há uma documentação detalhada sobre isso nas https://opentelemetry.io/docs/languages/java/instrumentation/[páginas de documentos do].

Certifique-se de usar o exportador OTLP (esse é o padrão) e https://opentelemetry.io/docs/languages/java/instrumentation/#_autoconfiguration[a configuração automática do site]. Ao implantar o aplicativo, o nome do serviço e o exportador são xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[configurados por meio de variáveis de ambiente].

== Métricas no SUSE Observability

ifdef::ss-ff-stackpacks2_enabled[]
Para algumas métricas Java, por exemplo, métricas do coletor de lixo, o SUSE Observability definiu gráficos sobre os componentes relacionados. No Kubernetes, os gráficos estão disponíveis nos pods. É possível xref:/setup/custom-integrations/metric-bindings/index.adoc[adicionar gráficos para mais métricas], o que funciona para métricas de instrumentação automática, mas também para métricas específicas de aplicativos de instrumentação manual.
endif::[]

ifndef::ss-ff-stackpacks2_enabled[]
Para algumas métricas Java, por exemplo, métricas do coletor de lixo, o SUSE Observability definiu gráficos sobre os componentes relacionados. No Kubernetes, os gráficos estão disponíveis nos pods. É possível xref:/use/metrics/k8s-add-charts.adoc[adicionar gráficos para mais métricas], o que funciona para métricas de instrumentação automática, mas também para métricas específicas de aplicativos de instrumentação manual.
endif::[]
