= アーキテクチャー・コンポーネント
:revdate: 2025-09-08
:page-revdate: {revdate}

xref:rancher-os-management/architecture/services/architecture-services.adoc[{elemental-product-name} サービスの]提供に必要なコンポーネントは以下の通り：

* コマンドラインツール <<_elemental_command_line_tool,`+elemental+`>>コマンドラインツール
* その <<_elemental_operator_daemon,`+elemental-operator+`>>デーモン
* コマンドラインツール <<_elemental_register_command_line_tool,`+elemental-register+`>>コマンドラインツール
* その <<_elemental_system_agent_daemon,`+elemental-system-agent+`>>デーモン
* 1つ以上の<<_suse_rancher_prime_os_manager_os_container_image,{elemental-product-name} OSコンテナ・イメージ>>

== `+elemental+` コマンドラインツール

`+elemental+` 。link:{elemental_toolkit_url}[{elemental_toolkit_name}]プロジェクトの一部です。
OSのインストールとアップグレードをホスト上で実行し、xref:rancher-os-management/architecture/custom-resources.adoc[{elemental-product-name} CRDで]追加されたxref:references/cloud-config-reference.adoc[cloud-config]ディレクティブを実行するために使用される。

`+elemental+` のバイナリは、{elemental-product-name} とともに配布されるすべてのベース OS イメージに含まれています。

== `+elemental-operator+` ディーモン

*エレメンタル・オペレーター・デーモンは*、主に2つのタスクを実行する：

. {elemental-product-name} Kubernetesコントローラを組み込み、すべてのxref:rancher-os-management/architecture/custom-resources.adoc[{elemental-product-name} CRDを]管理する。
. ホストがxref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[マシンのオンボーディング]中にOSのインストール・コンフィギュレーションを登録し、ダウンロードできるようにするための_登録エンドポイントを_公開する。

`+elemental-operator+` デーモンはxref:references/operatorchart-reference.adoc[{elemental-product-name} Operator Helm Chart を介して] `+Deployment+` として Rancher クラスタにデプロイされる。

== `+elemental-register+` コマンドラインツール

*elemental-register*バイナリは、<<_elemental_operator_daemon,elemental-operatorが>>公開する_登録エンドポイントに対して_ホストを登録するために使用されるクライアントである。<<_elemental_operator_daemon,エレメンタルオペレーターが>>SMBIOSとハードウェアラベルテンプレートを埋めることができるように、ホストデータを収集し転送する。

登録フェーズが正常に実行されると、*elemental-registerは*、*elemental-operatorから* xref:references/machineregistration-reference.adoc[MachineRegistrationに]格納されている完全な構成を取得する。
最後のステップとして、*elemental-register*クライアントは、取得したコンフィギュレーションを渡して<<_elemental_command_line_tool,elemental>>バイナリを呼び出し、OSのインストールを開始する。

== `+elemental-system-agent+` ディーモン

`+elemental-system-agent+` はhttps://github.com/rancher/system-agent[System Agent プロジェクトから] Rancher構築されており、{elemental-product-name} がホストのプロビジョニングを支援する_プランを_デプロイできるようになっている。
特筆すべきは、xref:rancher-os-management/architecture/services/architecture-clusterdeployment.adoc[Kubernetes Clusterプロビジョニングサービスに]必要な`+rancher-system-agent+` のインストールと設定は、`+elemental-system-agent+` _プランを通じて_実行されることだ。

== {elemental-product-name} OSコンテナイメージ

OSイメージlink:{elemental_toolkit_url}[{elemental_toolkit_name}]OSイメージは、ターゲットホストのOSを構成するすべてのファイルを含むOCIコンテナイメージです。すべてのバイナリやライブラリだけでなく、カーネルやLinuxシステムに必要なブートファイルも含まれている。

{elemental-product-name} OSイメージは、 SLE Microをベースとしlink:{elemental_toolkit_url}[{elemental_toolkit_name}]OS イメージはhttps://www.suse.com/products/micro/[Micro] SLEをベースにしており、{elemental-product-name} の特定の設定とバイナリ（<<_elemental_command_line_tool,elemental>>と<<_elemental_register_command_line_tool,elemental-register の>>もの）を含んでいます。

{elemental-product-name} OSイメージはxref:references/managedosversion-reference.adoc[ManagedOSVersions]リソースで追跡される。xref:references/managedosversion-reference.adoc[ManagedOSVersions]リソースは、xref:references/managedosversionchannel-reference.adoc[ManagedOSVersionChannel]リソースから動的に作成される。デフォルトの`+ManagedOSVersionChannel+` リソースは、{elemental-product-name} Operator のインストールごとに展開されます。
