= Certification des prestataires 
:revdate: 2025-06-30
:page-revdate: {revdate}

== Qu'est-ce qu'un prestataire certifié ?

Comme la plupart des fournisseurs CAPI sont des projets en amont maintenus par la communauté ouverte, il n'y a pas de moyen sûr de garantir que tous les clusters provisionnés avec un fournisseur donné peuvent être importés dans Rancher via Turtles. Toutefois, nous mettons en œuvre un processus de certification pour les prestataires qui le sont :

* Testé activement dans le cadre de notre suite de tests E2E.
* Cette suite de tests E2E a été mise à jour pour valider les versions récentes du fournisseur.

== Certifiez votre fournisseur de services personnalisés

En outre, si vous êtes un développeur de fournisseurs ou si vous souhaitez simplement utiliser un fournisseur différent qui ne figure pas sur la liste des fournisseurs certifiés, vous avez deux possibilités :

* Réutiliser la suite E2E Turtles existante pour commencer à demander l'état de certification. Des informations plus détaillées sont disponibles ici dans la sectionxref:./certification.adoc#_provider_certification_using_turtles_test_suite[Certification des prestataires à l'aide de la suite de tests Turtles].
* Utilisez votre propre suite d'intégration pour certifier votre fournisseur. Des informations plus détaillées sont disponibles ici dans la sectionxref:./certification.adoc#_certify_provider_with_custom_integration_suite[Certifier le fournisseur avec Custom Integration Suite.] 

[discrete]
==== *Pourquoi voudrais-je valider mon fournisseur ?*

Le nombre de fournisseurs CAPI ne cesse de croître et la communauté propose de nouveaux projets pour différents hôtes d'infrastructure. Cette ouverture contribue à enrichir l'écosystème CAPI, mais il est impossible de contrôler et de tester tous les fournisseurs avec lesquels Turtles travaillera dans le cadre de l'ensemble du projet CAPI. Les développeurs de Turtles tiendront à jour une xref:../overview/certified.adoc[liste de fournisseurs certifiés] qui sont activement testés et validés par des mécanismes d'IC, mais cette liste sera limitée aux fournisseurs clés et bien connus. C'est pourquoi nous encourageons les utilisateurs de fournisseurs non listés à réutiliser la suite de tests de Turtles et à valider l'intégration entre le fournisseur et Turtles.

[discrete]
==== *Puis-je utiliser les Tortues avec un fournisseur non certifié ?*

Turtles est un projet qui vise à être agnostique et à s'intégrer à l'ensemble de l'écosystème CAPI et vous êtes libre de l'utiliser sans valider aucun fournisseur. Il y a de fortes chances que vous ne rencontriez aucun problème avec la plupart des projets en amont.

[discrete]
==== *Quelle est la différence entre certifié et soutenu ?*

Les fournisseurs CAPI étant des projets maintenus par la communauté Kubernetes, nous ne pouvons pas garantir la prise en charge d'un fournisseur donné. C'est pourquoi nous avons choisi de nous concentrer sur la validation constante des xref:../overview/certified.adoc[fournisseurs certifiés] et d'offrir aux utilisateurs la possibilité d'intégrer la suite de tests existante pour vérifier les fournisseurs de leur choix.

== Certification des prestataires à l'aide de la suite de tests Turtles

Le processus de certification est basé sur la vérification de l'intégration de {product_name} avec les fournisseurs CAPI. Pour simplifier cette tâche, nous avons préparé un test générique qui valide l'approvisionnement et l'importation d'un cluster CAPI en aval.

[TIP]
====
Nous vous recommandons de vous référer à cet https://github.com/rancher-sandbox/turtles-integration-suite-example[exemple] pour savoir comment utiliser la suite de tests Turtles.
====

=== Testez et certifiez votre fournisseur

La première étape pour valider que votre fournisseur est compatible avec Turtles et que vous pouvez provisionner des clusters CAPI et les importer dans Rancher via Turtles est de s'intégrer à notre suite de tests. Nous fournissons un référentiel avec un https://github.com/rancher-sandbox/turtles-integration-suite-example[exemple d'intégration] que vous pouvez utiliser comme référence pour votre intégration.

Turtles en tant que projet contient un https://github.com/rancher/turtles/tree/main/test/e2e/suites[nombre de suites] pour vérifier les différentes fonctionnalités et processus mais, pour la certification du fournisseur, nous vous demandons d'exécuter un seul test qui utilise un flux GitOps. Turtles est un projet qui s'intègre bien à une approche GitOps pour le provisionnement des clusters et c'est pourquoi c'est notre principal moyen de valider l'intégration des fournisseurs avec Rancher. L'exécution de la suite complète pour un fournisseur CAPI donné permettra :

* Créer un cluster de gestion dans l'environnement souhaité.
* Installez Rancher et Turtles avec tous les prérequis.
* Installer Gitea.
* Exécutez la suite qui créera un repo git, appliquera le modèle de cluster en utilisant Fleet et vérifiera que le cluster est créé et importé avec succès dans Rancher.

==== Configuration du test

Pour exécuter avec succès la suite de tests, vous devrez fournir un certain nombre de variables d'environnement. Certains d'entre eux sont agnostiques, ce qui signifie qu'ils sont nécessaires pour tout fournisseur que vous souhaitez tester, mais d'autres sont spécifiques au fournisseur que vous validez. Il convient de tenir compte des spécifications particulières du fournisseur testé, telles que les informations d'identification, les points de terminaison, etc.

[TIP]
====
Ensuite, nous vous recommandons de lire le xref:../operator/certificationsuite.adoc[guide de la suite de tests]
====

== Certifier un fournisseur grâce à une suite d'intégration personnalisée

Pour certifier votre fournisseur à l'aide d'une suite d'intégration personnalisée, assurez-vous qu'elle répond aux exigences clés suivantes :

=== Exigences

* Le fournisseur doit être déployé à l'aide de l'API `CAPIProvider`.
* Les clusters créés avec le fournisseur doivent être importés avec succès dans Rancher via Turtles.

=== Processus de certification

1. **Développer une suite d'intégration** 
   * Installer et configurer Rancher et Turtles.
   * Déployer le fournisseur CAPI.
   * Provisionner un cluster et l'importer dans Rancher.

2. **Exécuter et valider les tests**
   * S'assurer que les clusters sont créés et importés avec succès.

3. **Soumettre une demande de certification**
   * Fournir les résultats des tests, les journaux et les étapes suivies.
   * Soumettez un problème GitHub en utilisant le suivant https://github.com/rancher/turtles/issues/new?template=certification_request.yaml[modèle].

== Demande de certification

L'intégration de la suite de tests de Turtles et l'exécution de vérifications sur le fournisseur qui vous intéresse suffisent à valider sa compatibilité avec {product_name}. Comme il ne nous est pas possible de tester en permanence chaque fournisseur CAPI, ce processus de certification vous permettra, en tant qu'utilisateur, de vérifier les fonctionnalités attendues. Cependant, comme nous ne testons pas activement les nouvelles itérations du fournisseur (avec les nouvelles versions de Turtles), le soutien et la garantie pour le fournisseur donné sont limités, et vous serez responsable de la validation des versions futures.

Si, après avoir effectué des vérifications sur votre fournisseur, vous souhaitez demander qu'il soit ajouté à la liste des xref:../overview/certified.adoc[fournisseurs certifiés] et inclus dans la suite périodique E2E du projet, vous pouvez demander la certification en soumettant un problème GitHub à l'aide du https://github.com/rancher/turtles/issues/new?template=certification_request.yaml[modèle de demande de certification]. La communauté examinera la proposition et déterminera s'il est possible d'ajouter le prestataire à la matrice de certification.
