= Características
:revdate: 2026-03-05
:page-revdate: {revdate}

En esta sección se describen las características y las etapas de las características en {product_name}.

== Lista de características

|===
| Característica | Nombre de la función Helm | Subfunción | Por defecto | Escenario 

| *Proveedor de complementos para flotas*
| `addon-provider-fleet`
| _Ninguno_
| habilitado
| beta

| *Agente Modo TLS*
| `agent-tls-mode`
| _Ninguno_
| habilitado
| beta

| *No Cert Manager*
| `no-cert-manager`
| _Ninguno_
| habilitado
| beta

| *Utilizar el registro por defecto de Rancher*
| `use-rancher-default-registry`
| _Ninguno_
| habilitado
| beta

|===

=== Proveedor de complementos para flotas
Esta función instala Cluster API Add-on Provider for Fleet (CAAPF) para proporcionar integración con https://github.com/rancher/fleet[Fleet] y permitir el fácil despliegue de aplicaciones en clusters aprovisionados con CAPI. CAAPF instala automáticamente Fleet en el clúster de gestión y registra los clústeres CAPI recién aprovisionados con Fleet, de modo que las aplicaciones puedan desplegarse en estos clústeres a través de recursos GitOps, `Bundle` o `HelmOp`. CAAPF también incluye soporte para agrupar clusters CAPI que hacen referencia a la misma ClusterClass a través de ClusterGroup de Fleet, simplificando esencialmente el despliegue de aplicaciones en grandes grupos de clusters. Esta función se encuentra en fase GA y está activada por defecto.

=== Agente Modo TLS
Esta puerta de función se utiliza para indicar a Turtles si debe seguir la configuración de `agent-tls-mode` de Rancher, al recuperar manifiestos de registro de clústeres para importar clústeres. Cuando está activado, Turtles buscará el valor del ajuste `agent-tls-mode` de Rancher para determinar si se ha establecido en `system-store` o `strict`. Si se establece en `system-store`, Turtles confiará en cualquier certificado generado por una Autoridad de Certificación pública contenida en el almacén de confianza del sistema operativo, incluyendo aquellos firmados por autoridades como Let's Encrypt. Si se establece en `strict`, Turtles sólo confiará en los certificados generados por la Autoridad de Certificación contenida en la configuración `cacerts` de Rancher. Si se desactiva esta opción, las Tortugas volverán a funcionar en el modo `system-store`. Esta función se encuentra en fase beta y está activada por defecto.

=== No Cert Manager
Esta función convierte los manifiestos de los proveedores CAPI para sustituir el uso de cert-manager por https://github.com/rancher/wrangler/[] wrangler.

En particular, se actualizarán los webhooks de admisión de validación y mutación para utilizar certificados generados por wrangler, en lugar de cert-manager, lo que permitirá un entorno libre de cert-manager.

Tenga en cuenta que el uso de la Rancher `CATTLE_SYNC_ONLY_CHANGED_OBJECTS` https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/best-practices/tuning-rancher-at-scale.html#_reducing_event_handler_executions[funcionalidad] puede impedir que los certificados se renueven después del tiempo de expiración predeterminado de un año.

Es posible desactivar esta función para restaurar todos los manifiestos de proveedor al uso original de cert-manager.

=== Utilizar el registro por defecto de Rancher

Esta puerta de función indica a {product_name} que aproveche la configuración de gestión de `system-default-registry` de Rancher al construir referencias de imagen para componentes de proveedor CAPI. Cuando está activada, {product_name} lee esta configuración y, si hay un registro configurado, reescribe el repositorio de cada imagen de proveedor para que utilice ese registro.
Si el ajuste está vacío, {product_name} vuelve a las referencias de imagen por defecto. Las modificaciones de imagen definidas en el recurso `ClusterctlConfig` siempre tienen prioridad. Para obtener información detallada sobre el uso en entornos xref:operator/airgapped.adoc[con separación] por aire, consulte xref:operator/airgapped.adoc[Entorno con separación por aire]. Esta función se encuentra en fase alfa y está activada por defecto.

== Etapas de las características

{product_name} sigue el proceso de Kubernetes https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages[etapas de características de]. Una característica puede encontrarse en una de las siguientes fases: Alfa, Beta o Disponibilidad General (GA).

=== Fase Alfa
- Desactivado por defecto.
- Puede tener errores, sin soporte a largo plazo.
- La API puede cambiar sin previo aviso.
- Recomendado sólo para grupos de pruebas de corta duración.

=== Fase Beta
- Siempre activado por defecto.
- Bien probado y considerado seguro.
- El soporte es estable, pero el esquema puede cambiar en futuras versiones.
- Recomendado para usos no críticos debido a posibles cambios incompatibles.

[NOTE]
====
Envíenos sus comentarios sobre las funciones Alfa y Beta.
====

=== Etapa de disponibilidad general (GA)
- Siempre activado, no se puede desactivar.
- No se necesita puerta de características.
- Estable, con soporte a largo plazo en futuras versiones.