include::partial$variables.adoc[]
= Vorschlag zur Verbesserung der Dokumentation
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Starten Sie eine Verbesserung der Dokumentation, indem Sie einen GitHub-Problemfall mit klaren Details darüber eröffnen, was fehlt, veraltet oder fehlerhaft ist oder eine Qualitätsüberprüfung erfordert.
:doc-persona: ["kubewarden-developer", "kubewarden-operator", "kubewarden-manager"]
:doc-topic: ["contribution-guide", "docs-contribution", "improvement"]
:doc-type: ["howto"]
:keywords: ["kubewarden", "documentation", "suggesting an improvement"]
:sidebar_label: Verbesserungsvorschläge für Dokumente
:sidebar_position: 8
:current-version: {page-origin-branch}

Wenn Ihnen ein Problem in der Dokumentation von {short-project-name} auffällt oder Sie neue Inhalte vorschlagen möchten, dann öffnen Sie ein Problem. Sie benötigen lediglich Zugang zu einemhttps://github.com/join[GitHub-Konto] und einen Browser.

Normalerweise beginnt jede neue Dokumentationsarbeit für {short-project-name} mit einem Eintrag in GitHub.
ifeval::["{build-type}" == "community"]
Das https://github.com/orgs/kubewarden/teams/kubewarden-documentation[{short-project-name} Dokumentationsteam] prüft, kategorisiert und markiert sie. Dokumentationsteam] prüft, kategorisiert und markiert sie. ]
endif::[]
ifeval::["{build-type}" == "product"]
Das https://github.com/orgs/rancher/teams/docs[{short-project-name} Dokumentationsteam] prüft, kategorisiert und markiert sie. Dokumentationsteam] prüft, kategorisiert und markiert sie. ]
endif::[]
Jeder ist willkommen, an einem Thema zu arbeiten, auch der Berichterstatter, aber Sie sollten es sich selbst zuweisen, bevor Sie mit der Arbeit beginnen, um doppelte Arbeit zu vermeiden.

== Eröffnen einer Ausgabe

Wenn Sie Verbesserungen am Inhalt der Dokumentation vorschlagen oder einen Fehler melden möchten, öffnen Sie ein Problem.

* Klicken Sie oben auf das GitHub Octocat-Symbol. Dies leitet Sie weiter zur
ifeval::["{build-type}" == "community"]
  https://github.com/kubewarden/docs[Dokumentations-Repository für {short-project-name}].
endif::[]
ifeval::["{build-type}" == "product"]
  https://github.com/rancher/kubewarden-product-docs[Dokumentations-Repository für {short-project-name}].
endif::[]
* Navigieren Sie zur Registerkarte Probleme und klicken Sie auf *Neues Problem*.
* Beschreiben Sie das Problem oder den Verbesserungsvorschlag. Je mehr Details, desto besser.
* Klicken Sie auf *Neue Ausgabe einreichen*.
* Nachdem Sie das Problem eingereicht haben, können Sie es entweder sich selbst zuweisen oder darauf warten, dass ein Community-Mitglied es aufgreift. Die Mitglieder des Dokumentationsteams und der Gemeinschaft bitten möglicherweise um Klärung, bevor sie sich mit Ihrem Problem befassen können. Sie sollten Ihr Problem aktiv überprüfen oder https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications[GitHub-Benachrichtigungen einschalten].

== Vorschläge für neue Inhalte

Wenn Sie neue Inhalte vorschlagen möchten, reichen Sie bitte eine Meldung über einen der folgenden Mechanismen ein:

* Wählen Sie eine vorhandene Seite in dem Bereich, in den der Inhalt Ihrer Meinung nach gehört, und klicken Sie auf *Ausgabe erstellen*. OR
ifeval::["{build-type}" == "community"]
* Navigieren Sie zu https://github.com/kubewarden/docs/issues/new/choose[] GitHub und melden Sie das Problem direkt an.
endif::[]
ifeval::["{build-type}" == "product"]
* Navigieren Sie zu https://github.com/rancher/kubewarden-product-docs/issues/new/choose[] GitHub und melden Sie das Problem direkt an.
endif::[]

== Wie können Sie einen Beitrag leisten?

Kein Beitrag ist zu groß oder zu klein. Um jedoch den größtmöglichen Nutzen für die Gemeinschaft zu erzielen, bitten wir Sie, bei der Meldung eines Problems die folgenden Punkte zu beachten:

* Konzentrieren Sie sich auf eine klare Beschreibung des Problems. Einige wichtige Punkte, die es zu berücksichtigen gilt, sind die Beschreibung dessen, was fehlt, veraltet oder fehlerhaft ist, oder was qualitativ und technisch verbessert werden muss.
* Beschreiben Sie die spezifischen Auswirkungen des Problems auf die Nutzer.
* Begrenzen Sie den Umfang des Themas. Wenn der Umfang groß ist, unterteilen Sie ihn in kleinere Aufgaben innerhalb einer Ausgabe. Zum Beispiel ist "Erstellen eines Beitragsleitfadens" sehr weit gefasst, da es mehrere Aufgaben gibt, die mit dem Thema verbunden sind.
  Allerdings ist "Behebung eines grammatikalischen Fehlers auf der Schnellstartseite" ein enger gefassteres Problem, das nur einen einzigen Pull Request erfordern würde.
* Überprüfen Sie bestehende Probleme, um doppelte Arbeit zu vermeiden.
* Prüfen Sie, ob eine Pull-Anfrage oder ein Problem vorhanden ist. Stellen Sie sicher, dass Sie in dem Thema, das Sie eröffnen, auf das bestehende Thema oder die Pull-Anfrage verweisen, um den Kontext für Mitwirkende, die daran arbeiten möchten, zu vermitteln.
