= Solución de problemas de extensión
:revdate: 2025-11-03
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

Esta sección proporciona los pasos para solucionar cualquier problema de interoperabilidad entre {stackstate-product-name} y la extensión Rancher UI.

== Recoger un HAR (Http ARchive)

Http ARchive recoge detalles sobre las peticiones que son enviadas por el navegador a Rancher y {stackstate-product-name}.  También registra las respuestas recibidas.
Este archivo es específico de la página/pestaña del navegador con el error.  No necesita acceso a las instancias de respaldo de Rancher o {stackstate-product-name} (aunque sus registros pueden ser útiles en una etapa posterior).

* Abra la pestaña *Red* del panel "Herramientas de desarrollo".  Puede acceder a ella a través de `F12`.  La pestaña de red muestra un registro de todas las solicitudes que se realizan.
* Borre el registro y actualice la página que muestra el comportamiento problemático.
* Ahora debería ser visible un gran número de peticiones tanto a Rancher como a SUSE Observability.
* Exportar/Descargar/Guardar el HAR - los distintos navegadores utilizan aquí nombres diferentes.

== La agrupación no se observa

Para que el estado de salud del clúster sea visible en Rancher, es necesario que haya alineación entre estas configuraciones:

* El nombre (para mostrar) del clúster en la interfaz de usuario de Rancher.
* El conjunto `stackstate.cluster.name` en el agente desplegado en el clúster.
* El nombre del clúster en la configuración del stackpack de Kubernetes en SUSE Observability

Un desajuste tenderá a mostrarse como "sin datos recibidos" en la visión general del cluster en Rancher.

== Error de conexión

En ocasiones, la configuración de SUSE Observability puede no producir una conexión válida en la interfaz de usuario de Rancher debido a los siguientes motivos:

* El host Rancher no está configurado como origen permitido para SUSE Observability.  Puede solucionarlo añadiéndolo a la lista `stackstate.allowedOrigins` en los valores de helm, o pasando `--set stackstate.allowedOrigins={"https://<rancher-url>"}` al comando de despliegue.
* SUSE Observability no es accesible desde el navegador. Por ejemplo, no se ha instalado el certificado raíz.