= Solución de problemas
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

== Guía rápida para la resolución de problemas

Esta es una guía rápida para la resolución de problemas en el arranque de SUSE Observability:

. Compruebe que la instalación se ha completado correctamente y que la versión aparece en la lista:
+
[,text]
----
helm list --namespace suse-observability
----

. Compruebe que todos los pods del espacio de nombres de SUSE Observability se están ejecutando:
+
[,text]
----
kubectl get pods
----
+
En un primer despliegue puede ocurrir que los contenedores de varios pods se reinicien unas cuantas veces, porque están esperando a que otros pods arranquen y estén en el estado `ready`. Esto puede retrasarse debido a retrasos en la programación y en la extracción de imágenes docker.
+
Las vainas en estado `pending` suelen ser un indicio de un problema:

 ** El pod no es programable por falta de recursos en el cluster. Si un autoescalador de clúster está activo, a menudo será capaz de resolver esto automáticamente; de lo contrario, será necesaria la intervención manual para añadir más nodos al clúster.
 ** El pod no es programable, hay nodos en los que cabría, pero esos nodos tienen `taints` que el pod no tolera. Para solucionar esto se pueden añadir más nodos que no tengan las contaminaciones, pero SUSE Observability también se puede xref:/setup/install-stackstate/kubernetes_openshift/customize_config.adoc#_override_default_configuration[configurar] para tolerar ciertas contaminaciones y ejecutarse en los nodos contaminados.
 ** El pod está esperando a que se monten los Volúmenes Persistentes (PVs). Una causa puede ser que el cuadro de SUSE Observability Helm no especifique un `storageClassName`, sino que confíe en que el clúster tenga una clase de almacenamiento predeterminada. Cuando no existe un valor predeterminado para el clúster, es necesario xref:/setup/install-stackstate/kubernetes_openshift/storage.adoc[especificar una clase de almacenamiento] a través de los valores Helm de SUSE Observability.

+
Para los pods con estado `ImagePullBackOff` compruebe también el mensaje de error exacto, las causas más comunes son:

 ** Un nombre de usuario/contraseña incorrectos utilizados para extraer las imágenes.
 ** La conexión al registro docker ha fallado, esto puede deberse a problemas de autenticación o problemas de conectividad (cortafuegos, instalaciones aisladas).
 ** Un error tipográfico en la URL de registro de imágenes Docker anulada

+
Para averiguar una causa más detallada de los estados `Pending`, `ImagePullBackOff` o `CrashLoopBackOff` utilice este comando:
+
[,text]
----
kubectl describe pod <pod-name>
----
+
La salida contiene una sección `event` al final que suele contener el problema. También tiene una sección `State` para cada contenedor que tiene más detalles para la terminación del contenedor.

. Si es cliente principal, póngase en contacto con el servicio de asistencia técnica de SUSE Observability en https://scc.suse.com/ para obtener ayuda sobre la configuración de SUSE Observability en su clúster local. Utilice xref:/setup/install-stackstate/support-package-logs.adoc[Support Package (Logs)] para recopilar información sobre su instancia para el equipo de soporte.
. Si el problema está relacionado con el rendimiento, ejecute xref:/setup/install-stackstate/support-package-performance.adoc[Support Package (Performance)] para investigar activamente el rendimiento.
. En caso de que los pasos anteriores no resuelvan el problema, existe una xref:/setup/install-stackstate/advanced-troubleshooting.adoc[Guía avanzada para la resolución de problemas].
