= Fehlerbehebung bei der Authentifizierung und Autorisierung
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

Wenn die Authentifizierung oder Autorisierung fehlschlägt, liegt das in der Regel an einer Diskrepanz zwischen der Konfiguration des Providers und SUSE Observability. Um die Fehlersuche zu erleichtern, kann die Debug-Protokollierung in SUSE Observability speziell für die Authentifizierung und Autorisierung aktiviert werden.

[CAUTION]
====
Deaktivieren Sie die Debug-Protokollierung wieder, sobald Sie mit der Fehlersuche fertig sind, denn es ist sehr wahrscheinlich, dass die Debug-Protokollierung Geheimnisse und/oder persönliche Informationen enthält.
====


Um die Debug-Protokollierung zu aktivieren, kopieren Sie den folgenden yaml-Ausschnitt in eine `debug-auth.yaml` -Datei.

[,yaml]
----
stackstate:
  components:
    server:
      additionalLogging: |
        <logger name="org.pac4j.core.engine" level="DEBUG"/>
        <logger name="org.pac4j.oidc.profile.creator" level="DEBUG"/>
        <logger name="org.pac4j.oidc.credentials.authenticator" level="DEBUG"/>
    api:
      additionalLogging: |
        <logger name="org.pac4j.core.engine" level="DEBUG"/>
        <logger name="org.pac4j.oidc.profile.creator" level="DEBUG"/>
        <logger name="org.pac4j.oidc.credentials.authenticator" level="DEBUG"/>
----

Führen Sie nun den Befehl `helm upgrade` aus, den Sie zuvor verwendet haben, aber fügen Sie diese eine zusätzliche yaml-Datei ein (also `helm upgrade .... --values debug-auth.yaml`), um die Debug-Protokollierung zu aktivieren. Es werden keine Pods neu gestartet, die Änderungen der Logging-Konfiguration werden nach etwa 30 Sekunden automatisch geladen.

Um die Debug-Protokollierung zu deaktivieren, führen Sie den Befehl `helm upgrade ....` erneut aus, lassen aber das `--values debug-auth.yaml` weg. Nach 30 Sekunden wird die aktualisierte Protokollierungskonfiguration geladen und die Debug-Protokollierung beendet.


== Fehlerbehebung bei Problemen mit Berechtigungen

* xref:/setup/security/rbac/rbac_permissions.adoc#_list_subjects_for_a_user[Untersuchen Sie die Benutzersubjekte] (Benutzer und Rollen) und überprüfen Sie die Konfiguration je nach verwendetem Authentifizierungsmodell.
* xref:/setup/security/rbac/rbac_permissions.adoc#_show_granted_permissions[Untersuchen Sie eine Subjektberechtigung] und überprüfen Sie die Konfiguration je nach verwendetem Berechtigungsmodell.