= Como adicionar RPMs de terceiros no momento da instalação
:revdate: 2025-09-08
:page-revdate: {revdate}

Este exemplo abrange o caso em que RPMS adicionais (por exemplo, drivers de hardware específicos) são incluídos na ISO e, durante a instalação, são instalados sobre a imagem do sistema operacional.

Para esse caso de uso, os seguintes arquivos são necessários:

* RPMs adicionais para instalar
* arquivo cloud-config adicional que define ganchos para copiar e instalar binários como ganchos de instalação

Podemos lidar com tudo isso em uma única seção `+SeedImage.spec.cloud-config+`, supondo que o RPM adicional esteja disponível para download de um servidor remoto no momento da instalação.

Considere os seguintes dados de configuração de nuvem que podem ser usados como o conteúdo da seção `+cloud-config+` em um xref:references/seedimage-reference.adoc#_seedimagespec_reference[recurso SeedImage].

[,yaml]
----
name: "Install extra drivers"
stages:
  before-install:
  # Preload data to the persistent storage
  # During installation persistent partition is mounted at /run/elemental/persistent
  - downloads:
    - path: /tmp/some_package.rpm
      url: "<REMOTE_PACKAGE_URL>"
      permissions: 0777
  - commands:
    - mkdir -o /run/elemental/persistent/extra-pkgs
    - cp -p /tmp/some_package.rpm /run/elemental/persistent/extra-pkgs

  after-install-chroot:
  # Install the package at install time
  - commands:
    - rpm -iv /run/elemental/extra-pkgs/some_package.rpm

  # Include to the install system analog upgrade and reset hooks
  - files:
    - path: /oem/extra-pkg.yaml
      permissions: 0664
      content: |
        name: "Install extra drivers"
        stages:
          after-upgrade-chroot:
          # Install the package after upgrading to a new image
          - commands:
            - rpm -iv /run/elemental/extra-pkgs/some_package.rpm
          after-reset-chroot:
          # Install the package on reset
          - commands:
            - rpm -iv /run/elemental/extra-pkgs/some_package.rpm
----

Observe que os ganchos de instalação abrangem apenas os procedimentos de instalação, de modo que os dados adicionais de configuração da nuvem também devem fazer parte do sistema instalado para continuar instalando o pacote como parte dos processos de atualização ou redefinição.

== Reempacotamento de uma imagem ISO gerada com arquivos extras

Como alternativa, se o download dinâmico do conteúdo no momento da instalação não for um comportamento desejado e o objetivo real for uma ISO que já inclua todos os binários extras, isso também é possível, mas requer o reempacotamento manual da ISO. Usando o `+xorriso+`, o utilitário do Linux para criar ISOs, esse processo é relativamente fácil.

Vamos criar um diretório `+overlay+` para criar a árvore de diretórios que precisa ser adicionada à raiz ISO. Nesse caso, o diretório `+overlay+` poderia conter:

[,yaml]
----
overlay/
  data/
    extra-pkgs/
      some_package.rpm
  iso-config/
    install_hooks.yaml
----

Estamos assumindo que `+install_hooks.yaml+` é o conteúdo da configuração de nuvem real exposta na seção anterior, que é incluída manualmente na imagem em vez de ser incorporada em um recurso SeedImage. A pasta `+data+` acaba incluindo os binários que queremos anexar à ISO.

Supondo que já tenhamos baixado uma ISO do Elemental vinculada a um MachineRegistration específico com a seguinte chamada `+xorriso+`, todo o conteúdo da pasta `+overlay+` seria incluído em uma nova ISO:

[,bash]
----
xorriso -indev elemental.x86_64.iso -outdev elemental.custom.x86_64.iso -map overlay / -boot_image any replay
----

Requer `+xorriso+` igual ou superior à versão 1.5.

O conteúdo de `+install_hooks.yaml+` poderia ser o mesmo da seção anterior, mas omitindo o download do pacote RPM e também adaptando o caminho do RPM para `+/run/initramfs/live/data/extra-pkgs/some_package.rpm+`, pois a pasta raiz do ISO está montada em `+/run/initramfs/live+`.