= Plug-ins Multus e IPAM
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-16
:page-revdate: {revdate}

https://github.com/k8snetworkplumbingwg/multus-cni[O Multus CNI] é um plug-in de CNI que permite anexar várias interfaces de rede a pods. O Multus não substitui os plug-ins da CNI, mas atua como um multiplexador de plug-ins da CNI. O Multus é útil em determinados casos de uso, especialmente quando os pods são intensivos em rede e exigem interfaces de rede extras que suportam técnicas de aceleração de plano de dados, como SR-IOV.

Para obter mais informações sobre o Multus, consulte a documentação https://github.com/k8snetworkplumbingwg/multus-cni/tree/master/docs[do].

A Multus não pode ser implementada de forma autônoma. Ele sempre requer pelo menos um plug-in de CNI convencional que atenda aos requisitos de rede do cluster do Kubernetes. Esse plug-in da CNI se torna o padrão para o Multus e será usado para fornecer a interface principal para todos os pods. Ao implantar K3s com opções padrão, esse plug-in da CNI é o Flannel.

[NOTE]
.Versão Gate
====
O K3s usa um caminho binário CNI fixo a partir das versões de outubro de 2024: v1.28.15+k3s1, v1.29.10+k3s1, v1.30.6+k3s1, v1.31.2+k3s1.
====

O K3s consulta o site `$DATA_DIR/data/cni` para obter os binários do plug-in da CNI. Por padrão, é `/var/lib/rancher/k3s/data/cni`. Plug-ins adicionais da CNI devem ser instalados nesse local.

Antes das versões de outubro de 2024, os binários da CNI faziam parte do pacote de espaço de usuário do K3s em `$DATA_DIR/data/$HASH/bin`, onde o hash é exclusivo para cada versão do K3s.
Isso dificultava a implementação de plug-ins adicionais da CNI, pois o caminho mudava sempre que o K3s era atualizado.

Se estiver implantando o Multus em uma versão mais antiga do K3s, você deverá usar `/var/lib/rancher/k3s/data/current/bin/` como o diretório bin do CNI, mas espere que os plug-ins precisem ser reimplantados sempre que o K3s for atualizado.

== Implementar com um plug-in IPAM

É necessário um plug-in do IP Address Manager (IPAM) para atribuir endereços IP nas interfaces extras criadas pelo Multus. Um ou mais IPAMs podem ser instalados; os exemplos abaixo mostram o uso de um único plug-in de IPAM, mas eles podem ser combinados conforme necessário.

Os exemplos de implantação do helm abaixo implantarão um DaemonSet para criar pods do Multus para instalar os binários da CNI necessários em `/var/lib/rancher/k3s/data/cni/` e a configuração da CNI do Multus em `/var/lib/rancher/k3s/agent/etc/cni/net.d`.

[tabs,sync-group-id=MultusIPAMplugins]
======
host-local::
+
--
O plug-in IPAM local do host aloca endereços IP a partir de um conjunto de intervalos de endereços. Ele armazena o estado localmente no sistema de arquivos do host, garantindo assim a exclusividade dos endereços IP em um único host. Portanto, não o recomendamos para clusters com vários nós. Esse plug-in do IPAM não requer nenhuma implementação adicional. Para obter mais informações: https://www.cni.dev/plugins/current/ipam/host-local/.

Para usar o plug-in host-local, implemente o Multus com a seguinte configuração:

[,yaml]
----
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: multus
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-multus
  targetNamespace: kube-system
  valuesContent: |-
    config:
      fullnameOverride: multus
      cni_conf:
        confDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
        binDir: /var/lib/rancher/k3s/data/cni/
        kubeconfig: /var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig
          # Comment the following line when using rke2-multus < v4.2.202
          multusAutoconfigDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
----
--

Localização::
+
--
https://github.com/k8snetworkplumbingwg/whereabouts[O Whereabouts] é um plug-in CNI de gerenciamento de endereços IP (IPAM) que atribui endereços IP em todo o cluster.

Para usar o plug-in IPAM do Whereabouts, implemente o Multus com a seguinte configuração:

[,yaml]
----
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: multus
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-multus
  targetNamespace: kube-system
  valuesContent: |-
    config:
      fullnameOverride: multus
      cni_conf:
        confDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
        binDir: /var/lib/rancher/k3s/data/cni/
        kubeconfig: /var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig
          # Comment the following line when using rke2-multus < v4.2.202
          multusAutoconfigDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
    rke2-whereabouts:
      fullnameOverride: whereabouts
      enabled: true
      cniConf:
        confDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
        binDir: /var/lib/rancher/k3s/data/cni/
----

Ao usar whereabouts em K3s, `configuration_path` deve ser definido como `/var/lib/rancher/k3s/agent/etc/cni/net.d/whereabouts.d/whereabouts.conf` na configuração `ipam` da NetworkAttachmentDefinition.

Por exemplo, ao usar o whereabouts como IPAM com o plug-in macvlan:

[,yaml]
----
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-whereabouts
spec:
  config: |-
    {
      "cniVersion": "1.0.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "172.17.0.0/24",
        "gateway": "172.17.0.1",
        "configuration_path": "/var/lib/rancher/k3s/agent/etc/cni/net.d/whereabouts.d/whereabouts.conf"
      }
    }
----
--

Daemon DHCP do Multus::
+
--
O plug-in dhcp IPAM pode ser implementado quando já houver um servidor DHCP em execução na rede. Esse conjunto de daemons cuida da renovação periódica da concessão do DHCP. Para obter mais informações, consulte a documentação oficial do https://www.cni.dev/plugins/current/ipam/dhcp/[plug-in] DHCP.

Para usar o plug-in DHCP, implemente o Multus com a seguinte configuração:

[,yaml]
----
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: multus
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-multus
  targetNamespace: kube-system
  valuesContent: |-
    config:
      fullnameOverride: multus
      cni_conf:
        confDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
        binDir: /var/lib/rancher/k3s/data/cni/
        kubeconfig: /var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig
          # Comment the following line when using rke2-multus < v4.2.202
          multusAutoconfigDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
    manifests:
      dhcpDaemonSet: true
----
--
======

=== Usando o Multus

Depois que o Multus tiver sido implantado, você poderá criar recursos NetworkAttachmentDefinition e fazer referência a eles nas especificações do Pod para anexar interfaces adicionais.
Por exemplo, usando o exemplo de localização acima, você pode criar uma interface `eth1` em um Pod usando a anotação `k8s.v1.cni.cncf.io/networks`:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-demo
  labels:
    app: multus-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multus-demo
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-whereabouts@eth1
      labels:
        app: multus-demo
    spec:
      containers:
      - name: shell
        image: docker.io/rancher/mirrored-library-busybox:1.36.1
        imagePullPolicy: IfNotPresent
        command:
          - sleep
          - "3600"
----

Consulte a documentação upstream para obter mais informações e exemplos.
