= Serviços de rede
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

Esta página explica como o CoreDNS, o controlador Traefik Ingress, o controlador de política de rede e o controlador do balanceador de carga ServiceLB funcionam no K3s.

Consulte a página xref:networking/basic-network-options.adoc[Opções de rede de instalação] para obter detalhes sobre as opções de configuração do Flannel e a seleção de back-end, ou sobre como configurar seu próprio CNI.

Para obter informações sobre quais portas precisam ser abertas para os K3s, consulte os xref:installation/requirements.adoc#_networking[Requisitos de rede].

== CoreDNS

O CoreDNS é implantado automaticamente na inicialização do servidor. Para desativá-la, configure todos os servidores do cluster com a opção `--disable=coredns`.

Se não instalar o CoreDNS, você mesmo precisará instalar um provedor de DNS de cluster.

== Controlador de ingresso Traefik

https://traefik.io/[O Traefik] é um proxy reverso HTTP moderno e um balanceador de carga criado para implementar microsserviços com facilidade. Ele simplifica a complexidade da rede ao projetar, implantar e executar aplicativos.

O controlador de entrada do Traefik implementa um serviço de LoadBalancer que usa as portas 80 e 443 e anuncia os IPs externos do serviço de LoadBalancer no status dos recursos de entrada que gerencia.

Por padrão, o ServiceLB usará todos os nós do cluster para hospedar o serviço Traefik LoadBalancer, o que significa que as portas 80 e 443 não poderão ser usadas por outros pods HostPort ou NodePort, e o status dos recursos Ingress mostrará os IPs de nó de todos os membros do cluster.

Para restringir os nós usados pelo Traefik e, por extensão, os IPs dos nós anunciados no Ingress Status, você pode seguir as instruções da seção <<_controlling_servicelb_node_selection,Controlando a seleção de nós do ServiceLB>> abaixo para limitar os nós em que o ServiceLB é executado ou adicionar alguns nós a um pool do LoadBalancer e restringir o serviço do Traefik a esse pool, definindo rótulos correspondentes no Traefik HelmChartConfig.

O Traefik é implantado por padrão ao iniciar o servidor. Os valores padrão dos gráficos podem ser encontrados em `/var/lib/rancher/k3s/server/manifests/traefik.yaml`, mas esse arquivo não deve ser editado manualmente, pois o K3s substitui o arquivo pelos padrões na inicialização. Em vez disso, você deve personalizar o Traefik criando um manifesto `HelmChartConfig` adicional em `/var/lib/rancher/k3s/server/manifests`. Para obter mais detalhes e um exemplo, consulte xref:add-ons/helm.adoc#_customizing_packaged_components_with_helmchartconfig[Personalização de componentes empacotados com o HelmChartConfig]. Para obter mais informações sobre os possíveis valores de configuração, consulte `values.yaml` do https://github.com/k3s-io/k3s-charts/tree/main/charts/traefik[Traefik Helm Chart] incluído em sua versão do K3s.

Para remover o Traefik de seu cluster, inicie todos os servidores com o sinalizador `--disable=traefik`. Para obter mais informações, consulte xref:installation/packaged-components.adoc[Gerenciamento de componentes empacotados].

Para obter detalhes sobre a versão específica do Traefik incluída no K3s, consulte as Notas de versão da sua versão.

* As versões do K3s a partir da **1.32** incluem o Traefik v3. As instalações existentes do Traefik v2 são atualizadas automaticamente para a v3 quando o K3s é atualizado.
  O Traefik v3 deve ser compatível com a configuração da v2; consulte os documentos https://doc.traefik.io/traefik/migrate/v2-to-v3/[de migração do] v2 para obter mais informações.
* As versões **1.21** a **1.31** do K3s incluem o Traefik v2, a menos que seja encontrada uma instalação existente do Traefik v1, caso em que o Traefik não foi atualizado para a v2.
* As versões **1.20** e **anteriores** do K3s incluem o Traefik v1.

== Controlador de política de rede

O K3s inclui um controlador de política de rede incorporado. A implementação subjacente é a biblioteca do controlador netpol https://github.com/cloudnativelabs/kube-router[do] kube-router (nenhuma outra funcionalidade do kube-router está presente) e pode ser encontrada https://github.com/k3s-io/k3s/tree/main/pkg/agent/netpol[].

Para desativá-lo, inicie cada servidor com o sinalizador `--disable-network-policy`.

[NOTE]
====
As regras do iptables da política de rede não são removidas se a configuração do K3s for alterada para desativar o controlador de política de rede. Para limpar as regras de política de rede do kube-router configuradas após a desativação do controlador de política de rede, use o script `k3s-killall.sh` ou limpe-as usando `iptables-save` e `iptables-restore`. Essas etapas devem ser executadas manualmente em todos os nós do cluster.

----
iptables-save | grep -v KUBE-ROUTER | iptables-restore
ip6tables-save | grep -v KUBE-ROUTER | ip6tables-restore
----
====

[#_service_load_balancer]
== Balanceador de carga de serviço

Qualquer controlador do LoadBalancer pode ser implementado no cluster do K3s. Por padrão, o K3s fornece um balanceador de carga conhecido como https://github.com/k3s-io/klipper-lb[ServiceLB] (anteriormente Klipper LoadBalancer) que usa as portas de host disponíveis.

O Kubernetes upstream permite a criação de serviços do tipo LoadBalancer, mas não inclui uma implementação padrão de balanceador de carga, portanto esses serviços permanecerão em `pending` até que um seja instalado. Muitos serviços hospedados exigem que um provedor de nuvem, como o Amazon EC2 ou o Microsoft Azure, ofereça uma implementação de balanceador de carga externo. Por outro lado, o ServiceLB do K3s possibilita o uso de serviços de LoadBalancer sem um provedor de nuvem ou qualquer configuração adicional.

=== Como o ServiceLB funciona

O controlador ServiceLB observa os do Kubernetes https://kubernetes.io/docs/concepts/services-networking/service/[serviços] com o campo `spec.type` definido como `LoadBalancer`.

Para cada LoadBalancer Service, um link:https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSet] é criado no namespace `kube-system`. Esse DaemonSet, por sua vez, cria Pods do ServiceLB com um prefixo `svc-` em cada nó. Esses pods aproveitam o hostPort usando a porta de serviço e, portanto, só serão implantados em nós que tenham essa porta disponível. Se não houver nenhum nó com essa porta disponível, o LB permanecerá pendente. Observe que é possível expor vários serviços no mesmo nó, desde que eles usem portas diferentes.

Quando o pod ServiceLB é executado em um nó que tem um IP externo configurado, o IP externo do nó é preenchido na lista de endereços `status.loadBalancer.ingress` do serviço com `ipMode: VIP`. Caso contrário, será usado o IP interno do nó.

Se o tráfego para o IP externo estiver sujeito a link:https://en.wikipedia.org/wiki/Network_address_translation[Network Address Translation (NAT)], por exemplo, em nuvens públicas ao usar o IP público do nó como IP externo, o tráfego será roteado para o pod ServiceLB por meio da hostPort. Em seguida, o pod usa o iptables para encaminhar o tráfego para o endereço e a porta do ClusterIP do serviço. Se o tráfego não estiver sujeito a NAT e, em vez disso, chegar com o endereço de destino correspondente ao endereço do LoadBalancer, o tráfego será interceptado (normalmente por cadeias iptables ou ipvs do kube-proxy) e encaminhado para o endereço e a porta ClusterIP do serviço.

=== Uso

Crie um https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[serviço] no K3s.

[WARNING]
.Problema conhecido
====
Se o tráfego externo chegar ao nó usando um NAT (por exemplo, em nuvens públicas) e você precisar do `externalTrafficPolicy=local` para fins como preservação do IP de origem do cliente, não defina o k3s config `node-external-ip` para nenhum dos nós, pois isso não funcionará corretamente.
====

=== Controle da seleção de nós do ServiceLB

Adicionar o rótulo `svccontroller.k3s.cattle.io/enablelb=true` a um ou mais nós alterna o controlador ServiceLB para o modo de lista de permissões, em que somente os nós com o rótulo estão qualificados para hospedar pods do LoadBalancer. Os nós que permanecerem sem rótulo serão excluídos do uso pelo ServiceLB.

[NOTE]
====
Por padrão, os nós não são rotulados. Enquanto todos os nós permanecerem sem rótulo, todos os nós com portas disponíveis serão usados pelo ServiceLB.
====


=== Criação de pools de nós do ServiceLB

Para selecionar um subconjunto específico de nós para hospedar pods para um LoadBalancer, adicione o rótulo `enablelb` aos nós desejados e defina os valores correspondentes do rótulo `lbpool` nos nós e serviços. Por exemplo:

. Rotular o Nó A e o Nó B com `svccontroller.k3s.cattle.io/lbpool=pool1` e `svccontroller.k3s.cattle.io/enablelb=true`
. Rotular o Nó C e o Nó D com `svccontroller.k3s.cattle.io/lbpool=pool2` e `svccontroller.k3s.cattle.io/enablelb=true`
. Crie um serviço LoadBalancer na porta 443 com o rótulo `svccontroller.k3s.cattle.io/lbpool=pool1`. O DaemonSet para esse serviço só implementa Pods no Nó A e no Nó B.
. Crie outro serviço LoadBalancer na porta 443 com o rótulo `svccontroller.k3s.cattle.io/lbpool=pool2`. O DaemonSet só implantará Pods no Nó C e no Nó D.

=== Desativação do ServiceLB

Para desativar o ServiceLB, configure todos os servidores do cluster com o sinalizador `--disable=servicelb`.

Isso é necessário se você quiser executar um LB diferente, como o MetalLB.

== Implementação de um Cloud Controller Manager externo

O K3s fornece um Cloud Controller Manager (CCM) incorporado que faz o seguinte:

* Hospeda o controlador do <<_service_load_balancer, Service Load Balancer>> LoadBalancer.
* Limpa a mácula do `node.cloudprovider.kubernetes.io/uninitialized`.
* Define os campos de endereço de nó com base nos sinalizadores `--node-ip`, `--node-external-ip`, `--node-internal-dns` e `--node-external-dns`.

Antes de implantar um CCM externo, você deve iniciar todos os servidores K3s com o sinalizador `--disable-cloud-controller` para desativar o CCM incorporado. Ao usar um CCM externo, os endereços dos nós serão fornecidos pelas APIs de metadados da instância do provedor de nuvem, em vez dos valores do sinalizador K3s.

[NOTE]
====
Se você desativar o CCM integrado e não implantar e configurar corretamente um substituto externo, os nós permanecerão contaminados e não poderão ser verificados.
====

