include::partial$variables.adoc[]
= C#
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erforschen und schreiben Sie Validierungs- und Mutationsrichtlinien für die Zugangskontrolle mit dem .NET Core SDK mit WASI-Unterstützung auf WebAssembly-Plattformen wie Kubernetes.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "c#"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "c#", ".net"]
:sidebar_label: C#
:sidebar_position: 40
:current-version: {page-origin-branch}

Derzeit bietet .NET Core experimentelle Unterstützung für die WebAssembly-WASI-Plattform.
Dies ist aus dem https://github.com/SteveSandersonMS/dotnet-wasi-sdk[`dotnet-wasi-sdk`] Projekt.

[NOTE]
====

Sie benötigen keine Windows-Installation, um .NET Core-Code zu schreiben oder auszuführen.
Alles kann auch auf einem Linux- oder macOS-Rechner durchgeführt werden.
====


== Aktueller Stand

Die Verfasser von Richtlinien können die folgenden Ressourcen nutzen:

* https://github.com/kubewarden/policy-sdk-dotnet[{project-name}.NET Core SDK]: Es bietet eine Reihe von Objekten und Funktionen, die das Schreiben von Richtlinien vereinfachen.
* https://github.com/kubewarden/policy-sdk-dotnet/tree/main/example[{short-project-name} Beispiel für eine Politik]: Dies ist ein Beispiel für eine funktionierende Politik.

Es sind keine Einschränkungen bekannt.
Das SDK ermöglicht es, sowohl validierende als auch mutierende Richtlinien zu schreiben.

Es ist möglich, diehttps://www.nuget.org/packages/KubernetesClient.Models[`KubernetesClient.Models`]Bibliothek zu verwenden, um mit den Kubernetes-Objekten umzugehen.

== Projektvorlage

Zurzeit haben wir keine Projektvorlage, die eine C#-Richtlinie als Gerüst verwenden kann.

Bitteunter https://github.com/kubewarden/policy-sdk-dotnet/issues[eröffnen Sie], wenn Sie interessiert sind.
