= Installation
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-11
:page-revdate: {revdate}

Cette section contient des instructions pour l'installation des K3 dans différents environnements. Veuillez vous assurer que vous avez rempli les xref:installation/requirements.adoc[conditions requises] avant de commencer l'installation de K3s.

Les xref:installation/configuration.adoc[options de configuration] fournissent des indications sur les options disponibles lors de l'installation des K3.

xref:installation/private-registry.adoc[Private Registry Configuration] couvre l'utilisation de `registries.yaml` pour configurer l'authentification et la mise en miroir du registre des images de conteneurs.

xref:installation/registry-mirror.adoc[Embedded Registry Mirror (Miroir de] registre intégré) montre comment activer le miroir de registre d'images distribué intégré, pour le partage d'images d'égal à égal entre les nœuds.

L'xref:installation/airgap.adoc[installation dans l'espace aérien] explique comment installer les K3 dans des environnements qui n'ont pas d'accès direct à l'internet.

La xref:installation/server-roles.adoc[gestion des rôles de serveur] explique en détail comment configurer les K3 avec des serveurs dédiés `control-plane` ou `etcd`.

La xref:installation/packaged-components.adoc[gestion des composants empaquetés] explique comment désactiver les composants empaquetés ou installer les vôtres à l'aide de manifestes de déploiement automatique.

La xref:installation/uninstall.adoc[désinstallation de K3s] explique comment supprimer K3s d'un hôte.
