= Exigences
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-31
:page-revdate: {revdate}

K3s est très léger, mais il doit répondre à certaines exigences minimales, comme indiqué ci-dessous.

Que vous configuriez K3s pour qu'il fonctionne dans un conteneur ou en tant que service Linux natif, chaque nœud exécutant K3s doit répondre aux exigences minimales suivantes. Ces exigences sont basées sur K3s et ses composants et n'incluent pas les ressources consommées par la charge de travail elle-même.

== Conditions préalables

Deux nœuds ne peuvent pas avoir le même nom d'hôte.

Si plusieurs nœuds ont le même nom d'hôte, ou si les noms d'hôte peuvent être réutilisés par un système de provisionnement automatisé, utilisez l'option `--with-node-id` pour ajouter un suffixe aléatoire à chaque nœud, ou créez un nom unique à transmettre avec `--node-name` ou `$K3S_NODE_NAME` pour chaque nœud que vous ajoutez à la grappe.

== Architecture

K3s est disponible pour les architectures suivantes :

* x86_64
* armhf
* arm64/aarch64

[CAUTION]
.Taille de page ARM64
====

Avant les versions de mai 2023 (v1.24.14+k3s1, v1.25.10+k3s1, v1.26.5+k3s1, v1.27.2+k3s1), sur les systèmes `aarch64/arm64`, le noyau doit utiliser 4k pages. *RHEL9*, *Ubuntu*, *Raspberry PI OS* et *SLES* répondent tous à cette exigence.
====

[#_operating_systems]
== Systèmes d'exploitation

K3s devrait fonctionner sur la plupart des systèmes Linux modernes.

Certains systèmes d'exploitation ont des exigences supplémentaires en matière d'installation :

[tabs,sync-group-id=os,id=os]
======
SUSE Linux Enterprise / openSUSE::
+
--
[#_sle_opensuse_firewalld]
[pass]
<h3><a class="anchor" id="_sle_opensuse_firewalld" href="#_sle_opensuse_firewalld"></a>Firewalld</h3>

Il est recommandé de désactiver firewalld :

[,bash]
----
systemctl disable firewalld --now
----

Si vous souhaitez que firewalld reste activé par défaut, les règles suivantes sont nécessaires :

[,bash]
----
firewall-cmd --permanent --add-port=6443/tcp #apiserver
firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
firewall-cmd --reload
----

Il se peut que d'autres ports doivent être ouverts en fonction de votre configuration. Voir <<_inbound_rules_for_k3s_nodes,Règles de réception>> pour plus d'informations. Si vous modifiez le CIDR par défaut pour les pods ou les services, vous devrez mettre à jour les règles du pare-feu en conséquence.
--

Red Hat Enterprise Linux / CentOS / Fedora::
+
--
[#_rhel10]
[pass]
<h3><a class="anchor" id="_rhel10" href="#_rhel10"></a>RHEL 10</h3>

Sur RHEL 10, un paquetage supplémentaire est nécessaire :

[,bash]
----
sudo dnf install -y kernel-modules-extra
----

[#_rhel_centos_fedora_firewalld]
[pass]
<h3><a class="anchor" id="_rhel_centos_fedora_firewalld" href="#_rhel_centos_fedora_firewalld"></a>Firewalld</h3>

Il est recommandé de désactiver firewalld :

[,bash]
----
systemctl disable firewalld --now
----

Si vous souhaitez que firewalld reste activé par défaut, les règles suivantes sont nécessaires :

[,bash]
----
firewall-cmd --permanent --add-port=6443/tcp #apiserver
firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
firewall-cmd --reload
----

Il se peut que d'autres ports doivent être ouverts en fonction de votre configuration. Voir <<_inbound_rules_for_k3s_nodes,Règles de réception>> pour plus d'informations. Si vous modifiez le CIDR par défaut pour les pods ou les services, vous devrez mettre à jour les règles du pare-feu en conséquence.

[WARNING]
.Anciennes versions de RHEL/CentOS
====
Les versions du système d'exploitation antérieures à RHEL 8.4 intègrent NetworkManager avec un bogue connu qui interfère avec le réseau K3s. Si vous utilisez une version antérieure, il est nécessaire de désactiver nm-cloud-setup et de redémarrer le nœud :

[,bash]
----
systemctl disable nm-cloud-setup.service nm-cloud-setup.timer
reboot
----
====
--

Ubuntu / Debian::
+
--
[#_ubuntu_debian_ufw]
[pass]
<h3><a class="anchor" id="_ubuntu_debian_ufw" href="#_ubuntu_debian_ufw"></a>UFW</h3>

Les anciennes versions de Debian peuvent souffrir d'un bogue connu d'iptables. Voir les xref:known-issues.adoc#_iptables[problèmes connus.]

Il est recommandé de désactiver ufw (uncomplicated firewall) :

[,bash]
----
ufw disable
----

Si vous souhaitez que l'option ufw reste activée par défaut, les règles suivantes sont nécessaires :

[,bash]
----
ufw allow 6443/tcp #apiserver
ufw allow from 10.42.0.0/16 to any #pods
ufw allow from 10.43.0.0/16 to any #services
----

Il se peut que d'autres ports doivent être ouverts en fonction de votre configuration. Voir <<_inbound_rules_for_k3s_nodes,Règles de réception>> pour plus d'informations. Si vous modifiez le CIDR par défaut pour les pods ou les services, vous devrez mettre à jour les règles du pare-feu en conséquence.
--

[#os_tab_raspberry_pi]
Raspberry Pi::
+
--
Le système d'exploitation Raspberry Pi est basé sur Debian et peut souffrir d'un bogue connu d'iptables. Voir les xref:known-issues.adoc#_iptables[problèmes connus.]

[#_cgroups]
[pass]
<h3><a class="anchor" id="_cgroups" href="#_cgroups"></a>Cgroups</h3>

Les installations standard du Raspberry Pi OS ne démarrent pas avec `cgroups` activé. **K3S** a besoin de `cgroups` pour démarrer le service systemd. `cgroups`peut être activé en ajoutant `cgroup_memory=1 cgroup_enable=memory` à `/boot/firmware/cmdline.txt`.

[NOTE]
====
Sur Debian 11 et les versions plus anciennes de Pi OS, le fichier cmdline.txt se trouve à l'adresse `/boot/cmdline.txt`.
====

Exemple cmdline.txt :

----
console=serial0,115200 console=tty1 root=PARTUUID=58b06195-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait cgroup_memory=1 cgroup_enable=memory
----

[#_ubuntu_vxlan_module]
[pass]
<h3><a class="anchor" id="_ubuntu_vxlan_module" href="#_ubuntu_vxlan_module"></a>Module Vxlan Ubuntu</h3>

Avec Ubuntu 21.10 à Ubuntu 23.10, la prise en charge de vxlan sur Raspberry Pi a été déplacée dans un module de noyau séparé. Cette étape n'est pas nécessaire pour Ubuntu 24.04 et les versions ultérieures.

[,bash]
----
sudo apt install linux-modules-extra-raspi
----
--
======

Pour plus d'informations sur les systèmes d'exploitation testés avec les clusters K3s gérés par Rancher, consultez les Rancher à l' https://rancher.com/support-maintenance-terms/[conditions d'assistance et de maintenance de].

== Matériel

Les besoins en matériel évoluent en fonction de la taille de vos déploiements. Les exigences minimales sont les suivantes

|===
| Nœud | CPU | RAM

| Serveur
| 2 cœurs
| 2 GB

| Agent
| 1 noyau
| 512 MB
|===

Le xref:reference/resource-profiling.adoc[profilage des ressources] permet de saisir les résultats des tests et des analyses visant à déterminer les exigences minimales en matière de ressources pour l'agent K3s, le serveur K3s avec une charge de travail et le serveur K3s avec un agent.

=== Disques

Les performances de K3 dépendent de celles de la base de données. Pour garantir une vitesse optimale, nous recommandons d'utiliser un disque SSD lorsque cela est possible. 

Si vous déployez des K3 sur un Raspberry Pi ou d'autres appareils ARM, il est recommandé d'utiliser un disque SSD externe. etcd est très gourmand en écriture ; les cartes SD et eMMC ne peuvent pas gérer la charge IO.

=== Guide de dimensionnement des serveurs

Lorsque l'unité centrale et la mémoire vive du nœud serveur (plan de contrôle + etcd) sont limitées, le nombre de nœuds agents qui peuvent être joints dans des conditions de charge de travail standard est lui aussi limité.

|===
| Unité centrale du serveur | RAM du serveur | Nombre d'agents

| 2
| 4 GB
| 0-350

| 4
| 8 GB
| 351-900

| 8
| 16 GO
| 901-1800

| 16+
| 32 GB
| 1800+
|===

[TIP]
.Dimensionnement de la haute disponibilité
====
Lorsque l'on utilise une configuration à haute disponibilité de 3 nœuds de serveur, le nombre d'agents peut être augmenté d'environ ~50 % par rapport au tableau ci-dessus. Par exemple, 3 serveurs avec 4 vCPU/8 GB peuvent évoluer jusqu'à ~1200 agents.
====

Il est recommandé de joindre des nœuds d'agents par lots de 50 ou moins pour permettre à l'unité centrale de libérer de l'espace, car il y a un pic lors de la jointure des nœuds. N'oubliez pas de modifier la valeur par défaut de `cluster-cidr` si vous souhaitez plus de 255 nœuds !

Le xref:reference/resource-profiling.adoc#_server_sizing_requirements_for_k3s[profilage des ressources] contient plus d'informations sur la manière dont ces recommandations ont été formulées.

[#_networking]
== Mise en réseau

Le serveur K3s a besoin du port 6443 pour être accessible par tous les nœuds.

Les nœuds doivent pouvoir atteindre d'autres nœuds sur le port UDP 8472 lorsqu'ils utilisent le backend Flannel VXLAN, ou sur le port UDP 51820 (et 51821 si IPv6 est utilisé) lorsqu'ils utilisent le backend Flannel WireGuard. Le nœud ne doit pas écouter sur un autre port. K3s utilise un tunnel inversé de sorte que les nœuds établissent des connexions sortantes avec le serveur et que tout le trafic des kubelets passe par ce tunnel. Cependant, si vous n'utilisez pas Flannel et que vous fournissez votre propre CNI, les ports nécessaires à Flannel ne sont pas nécessaires à K3s.

Si vous souhaitez utiliser le serveur de métriques, tous les nœuds doivent être accessibles les uns aux autres sur le port 10250.

Si vous envisagez d'assurer une haute disponibilité avec etcd intégré, les nœuds de serveur doivent être accessibles l'un à l'autre sur les ports 2379 et 2380.

[TIP]
.Important
====
Le port VXLAN des nœuds ne doit pas être exposé au monde entier, car il permet à n'importe qui d'accéder au réseau de la grappe. Exécutez vos nœuds derrière un pare-feu/groupe de sécurité qui désactive l'accès au port 8472.
====


[WARNING]
====
Flannel s'appuie sur le https://www.cni.dev/plugins/current/main/bridge/[plugin] pour créer un réseau L2 qui commute le trafic. Les pods voyous dotés de capacités `NET_RAW` peuvent abuser de ce réseau L2 pour lancer des attaques telles que l'usurpation d'adresse ARP. Par conséquent, comme indiqué dans la https://kubernetes.io/docs/concepts/security/pod-security-standards/[documentation] Kubernetes, veuillez définir un profil restreint qui désactive `NET_RAW` sur les pods non fiables.
====

[#_inbound_rules_for_k3s_nodes]
=== Règles de réception pour les nœuds K3s

|===
| Protocole | Port | Source | Destination | Description

| TCP
| 2379-2380
| Serveurs
| Serveurs
| Nécessaire uniquement pour les HA avec etcd intégré

| TCP
| 6443
| Agents
| Serveurs
| Superviseur K3s et serveur API Kubernetes

| UDP
| 8472
| Tous les nœuds
| Tous les nœuds
| Requis uniquement pour Flannel VXLAN

| TCP
| 10250
| Tous les nœuds
| Tous les nœuds
| Métriques Kubelet

| UDP
| 51820
| Tous les nœuds
| Tous les nœuds
| Nécessaire uniquement pour Flannel Wireguard avec IPv4

| UDP
| 51821
| Tous les nœuds
| Tous les nœuds
| Nécessaire uniquement pour Flannel Wireguard avec IPv6

| TCP
| 5001
| Tous les nœuds
| Tous les nœuds
| Nécessaire uniquement pour le registre distribué intégré (Spegel)

| TCP
| 6443
| Tous les nœuds
| Tous les nœuds
| Nécessaire uniquement pour le registre distribué intégré (Spegel)
|===

En général, tout le trafic sortant est autorisé.

Des modifications supplémentaires du pare-feu peuvent être nécessaires en fonction du système d'exploitation utilisé.

== Grands groupes

La configuration matérielle requise dépend de la taille de votre cluster K3s. Pour la production et les grands clusters, nous recommandons d'utiliser une configuration à haute disponibilité avec une base de données externe. Les options suivantes sont recommandées pour la base de données externe en production :

* MySQL
* PostgreSQL
* etcd

=== Unité centrale et mémoire

Les exigences minimales en matière de CPU et de mémoire pour les nœuds d'un serveur K3s à haute disponibilité sont les suivantes :

[cols="^,^,^,^"]
|===
| Taille du déploiement | Nœuds | vCPUs | RAM

| Petit
| Jusqu'à 10
| 2
| 4 GB

| Moyen
| Jusqu'à 100
| 4
| 8 GB

| Grandes dimensions
| Jusqu'à 250
| 8
| 16 GO

| X-Large
| Jusqu'à 500
| 16
| 32 GB

| XX-Large
| 500+
| 32
| 64 GB
|===

=== Disques

Les performances de la grappe dépendent de celles de la base de données. Pour garantir une vitesse optimale, nous recommandons de toujours utiliser des disques SSD pour sauvegarder votre cluster K3s. Chez les fournisseurs de services en nuage, vous voudrez également utiliser la taille minimale qui permet d'obtenir le maximum d'IOPS.

=== Réseau

Vous devriez envisager d'augmenter la taille du sous-réseau pour le CIDR du cluster afin de ne pas manquer d'IP pour les pods. Vous pouvez le faire en passant l'option `--cluster-cidr` au serveur K3s lors de son démarrage.

=== Base de données

K3s prend en charge différentes bases de données, notamment MySQL, PostgreSQL, MariaDB et etcd.  Voir xref:datastore/datastore.adoc[Cluster Datastore] pour plus d'informations.

Vous trouverez ci-dessous un guide de dimensionnement des ressources de base de données nécessaires à l'exécution de clusters de grande taille :

[cols="^,^,^,^"]
|===
| Taille du déploiement | Nœuds | vCPUs | RAM

| Petit
| Jusqu'à 10
| 1
| 2 GB

| Moyen
| Jusqu'à 100
| 2
| 8 GB

| Grandes dimensions
| Jusqu'à 250
| 4
| 16 GO

| X-Large
| Jusqu'à 500
| 8
| 32 GB

| XX-Large
| 500+
| 16
| 64 GB
|===
