include::partial$variables.adoc[]
= Erstellen einer Richtlinie
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Lernen Sie, Validierungsrichtlinien zu erstellen und zu konfigurieren, die Pod-Erstellungsanfragen anhand von anpassbaren Ablehnungskriterien kontrollieren.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "creating-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "Richtlinienerstellung"]
:sidebar_label: Erstellen einer Richtlinie
:current-version: {page-origin-branch}

Als Beispiel erstellen Sie eine einfache Validierungsrichtlinie, die Anfragen zur Pod-Erstellung bearbeitet.

Die Richtlinie prüft das Attribut `+metadata.name+` des Pods und lehnt Pods mit ungültigem Namen ab.
Die Liste der ungültigen Namen sollte von den Endbenutzern der Richtlinie konfigurierbar sein.

Die Richtlinieneinstellungen sehen in etwa so aus:

[subs="+attributes",yaml]
----
invalid_names:
- bad_name1
- bad_name2
----

Die Richtlinie sollte die Erstellung eines Pods wie dem folgenden zulassen:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

Sie sollte die Schaffung eines Pods wie:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: bad_name1
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

== Das Gerüst für das neue politische Projekt

Sie können ein neues Richtlinienprojekt erstellen, indem Sie `+cargo generate+` mit demhttps://github.com/kubewarden/rust-policy-template[Vorlagenprojekt] verwenden.

Installieren Sie zunächst `+cargo-generate+`. Dies erfordert https://pkgs.org/download/openssl-devel[openssl-devel].

[subs="+attributes",shell]
----
cargo install cargo-generate
----

Rüsten Sie nun das Projekt wie folgt ein:

[subs="+attributes",shell]
----
cargo generate --git https://github.com/kubewarden/rust-policy-template \
               --branch main \
               --name demo
----

Der Befehl erzeugt eine Ausgabe wie diese:

[subs="+attributes",console]
----
🔧   Creating project called `+demo+`...
✨   Done! New project created /<some-path-name>/demo
----

Dadurch wird das neue Richtlinienprojekt im Unterverzeichnis `+demo+` erstellt.

[NOTE]
====

Wenn Sie die GitHub-Container-Registry-Funktionalität in der Demo nutzen möchten, müssen Sie unterhttps://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry#enabling-the-container-registry-for-your-personal-account[die verbesserte Container-Unterstützung aktivieren].
====


=== Prüfung

Sie können es versuchen:

[subs="+attributes",console]
----
cargo test
----

Damit wird das erstellte Gerüst getestet. Wenn alles korrekt ist, werden Sie eine Reihe von Kompilierungsmeldungen sehen, die mit einer Ausgabe wie dieser enden:

[subs="+attributes",console]
----
running 4 tests
test settings::tests::validate_settings ... ok
test tests::accept_request_with_non_pod_resource ... ok
test tests::accept_pod_with_valid_name ... ok
test tests::reject_pod_with_invalid_name ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
----
