include::partial$variables.adoc[]
= Festlegen von Richtlinieneinstellungen
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Definieren Sie Richtlinieneinstellungen und -strukturen in Ihrem Code, um eine Grundlage für die Validierung der Richtlinienintegrität durch eine effiziente Verwaltung der Einstellungen zu schaffen. Stellen Sie sicher, dass alle Änderungen nachverfolgt werden, z. B. wer die Änderung vorgenommen hat, wann und was geändert wurde.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "policy-settings"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "Richtlinien schreiben", "Richtlinieneinstellungen", "rust"]
:sidebar_label: Festlegen von Richtlinieneinstellungen
:current-version: {page-origin-branch}

== Die Struktur der Richtlinieneinstellungen

Definieren Sie zunächst die Struktur, die die Richtlinieneinstellungen enthält.

Öffnen Sie die Datei `+demo/src/settings.rs+` und ändern Sie die Definition der Datei `+Settings+``+struct+` so, dass sie wie folgt aussieht:

[subs="+attributes",rust]
----
pub(crate) struct Settings {
    pub invalid_names: HashSet<String>,
}
----

Dadurch wird die Liste der ungültigen Namen automatisch in eine Set-Sammlung aufgenommen.

== Die Funktion zur Überprüfung der Einstellungen

Schreiben Sie als nächstes eine Funktion zur Überprüfung der Einstellungen, um sicherzustellen, dass die Richtlinie immer mit mindestens einem ungültigen Namen ausgeführt wird.

Sie tun dies, indem Sie die Implementierung der Eigenschaft `+Validatable+` ändern.

Ändern Sie die in `+src/settings.rs+` definierte Gerüstimplementierung so, dass sie wie folgt aussieht:

[subs="+attributes",rust]
----
impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        if self.invalid_names.is_empty() {
            Err(String::from("No invalid name specified. Specify at least one invalid name to match"))
        } else {
            Ok(())
        }
    }
}
----

== Einheitstests hinzufügen

Jetzt können Sie einen Unit-Test schreiben, um sicherzustellen, dass die Validierung der Einstellungen funktioniert.
Sie können dies auf die https://doc.rust-lang.org/stable/book/ch11-00-testing.html[übliche Weise in Rust] tun.

Es gibt bereits einige Standardtests am Ende der Datei `+src/settings.rs+`. Ersetzen Sie den automatisch generierten Code, so dass er wie folgt aussieht:

[subs="+attributes",rust]
----
#[cfg(test)]
mod tests {
    use super::*;

    use kubewarden_policy_sdk::settings::Validatable;

    #[test]
    fn accept_settings_with_a_list_of_invalid_names() -> Result<(), ()> {
        let mut invalid_names = HashSet::new();
        invalid_names.insert(String::from("bad_name1"));
        invalid_names.insert(String::from("bad_name2"));

        let settings = Settings { invalid_names };

        assert!(settings.validate().is_ok());
        Ok(())
    }

    #[test]
    fn reject_settings_without_a_list_of_invalid_names() -> Result<(), ()> {
        let invalid_names = HashSet::<String>::new();
        let settings = Settings { invalid_names };

        assert!(settings.validate().is_err());
        Ok(())
    }
}
----

Sie können nun die Unit-Tests ausführen:

[subs="+attributes",console]
----
cargo test
----

Dies ergibt eine Ausgabe ähnlich der folgenden:

[subs="+attributes",console]
----
   Compiling demo v0.1.0 (/home/jhk/projects/suse/tmp/demo)
    Finished test [unoptimized + debuginfo] target(s) in 0.59s
     Running unittests src/lib.rs (target/debug/deps/demo-bea8e11b21717093)

running 5 tests
test settings::tests::accept_settings_with_a_list_of_invalid_names ... ok
test settings::tests::reject_settings_without_a_list_of_invalid_names ... ok
test tests::reject_pod_with_invalid_name ... ok
test tests::accept_request_with_non_pod_resource ... ok
test tests::accept_pod_with_valid_name ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
----
