include::partial$variables.adoc[]
= Rohe Politik
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Lernen Sie rohe Richtlinien kennen, die beliebige JSON-Dokumente auswerten, und sehen Sie sich Beispiele für die Implementierung von Richtlinien in Rust an.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["writing-policies", "rust", "raw-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "raw policies", "rust"]
:sidebar_label: Rohe Politik
:current-version: {page-origin-branch}

Rohe Richtlinien sind Richtlinien, die beliebige JSON-Dokumente auswerten können.
Weitere Informationen über Raw Policies finden Sie auf der Seite xref:howtos/raw-policies.adoc[Raw Policies].

== Beispiele

Die folgenden Beispiele sollten Ihnen bekannt vorkommen, wenn Sie die xref:tutorials/writing-policies/rust/05-mutation-policy.adoc[Validierungsseite] dieses Lehrgangs abgeschlossen haben.

[NOTE]
====
Denken Sie daran, die Richtlinie als `+raw+` zu kennzeichnen, indem Sie das Feld `+policyType+` in der Konfiguration `+metadata.yml+` verwenden.
Weitere Informationen entnehmen Sie bitte der xref:tutorials/writing-policies/metadata.adoc[Metadatenspezifikation].
====


=== Validierung

Schreiben wir eine Richtlinie, die eine Anfrage in folgendem Format annimmt:

[subs="+attributes",json]
----
{
  "request": {
    "user": "alice",
    "action": "delete",
    "resource": "products"
  }
}
----

und validiert das:

* `+user+` in der Liste der gültigen Benutzer steht
* `+action+` in der Liste der gültigen Aktionen enthalten ist
* `+resource+` in der Liste der gültigen Ressourcen enthalten ist

Beginnen Sie mit dem Gerüst der Richtlinie, indem Sie die https://github.com/kubewarden/rust-policy-template[rust policy template] verwenden.

Zunächst definieren wir die Typen, die die Nutzlast der Anfrage darstellen.
Wir werden einen benutzerdefinierten Typ `+RawValidationRequest+` deklarieren, der `+Request+` und `+Settings+` enthält, anstatt den Typ `+ValidationRequest+` zu verwenden, der vom SDK bereitgestellt wird:

[subs="+attributes",rust]
----
/// RawValidationRequest represents the request that is sent to the validate function by the Policy Server.
#[derive(Deserialize)]
pub(crate) struct RawValidationRequest {
    pub(crate) request: Request,
    pub(crate) settings: Settings,
}

#[derive(Serialize, Deserialize)]
/// Request represents the payload of the request.
pub(crate) struct Request {
    pub(crate) user: String,
    pub(crate) resource: String,
    pub(crate) action: String,
}
----

Dann müssen wir den Typ `+Settings+` definieren und den Trait `+Validatable+` implementieren:

[subs="+attributes",rust]
----
/// Settings represents the settings of the policy.
#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(default, rename_all = "camelCase")]
pub(crate) struct Settings {
    pub(crate) valid_users: Vec<String>,
    pub(crate) valid_actions: Vec<String>,
    pub(crate) valid_resources: Vec<String>,
}

impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        info!(LOG_DRAIN, "starting settings validation");

        if self.valid_users.is_empty() {
            return Err("validUsers cannot be empty".to_string());
        }

        if self.valid_actions.is_empty() {
            return Err("validActions cannot be empty".to_string());
        }

        if self.valid_resources.is_empty() {
            return Err("validResources cannot be empty".to_string());
        }

        Ok(())
    }
}
----

Schließlich definieren wir die Funktion `+validate+`:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: RawValidationRequest =
        if let Ok(validation_request) = serde_json::from_slice(payload) {
            validation_request
        } else {
            return kubewarden::reject_request(
                Some("cannot unmarshal request".to_string()),
                None,
                None,
                None,
            );
        };

    info!(LOG_DRAIN, "starting validation");

    let request = validation_request.request;
    let settings = validation_request.settings;

    if settings.valid_users.contains(&request.user)
        && settings.valid_actions.contains(&request.action)
        && settings.valid_resources.contains(&request.resource)
    {
        info!(LOG_DRAIN, "accepting resource");
        kubewarden::accept_request()
    } else {
        kubewarden::reject_request(
            Some("this request is not accepted".to_string()),
            None,
            None,
            None,
        )
    }
}
----

=== Mutation

Ändern wir das vorherige Beispiel, um die Anfrage zu ändern, anstatt sie abzulehnen.
In diesem Fall enthalten die Einstellungen die Werte `+defaultUser+`, `+defaultAction+` und `+defaultRequest+`, die verwendet werden, um die Anfrage zu ändern, wenn der Benutzer, die Aktion oder die Ressource nicht gültig ist.

Wir müssen den Typ `+Settings+` mit den neuen Feldern aktualisieren:

[subs="+attributes",rust]
----
/// Settings represents the settings of the policy.
#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(default, rename_all = "camelCase")]
pub(crate) struct Settings {
    pub(crate) valid_users: Vec<String>,
    pub(crate) valid_actions: Vec<String>,
    pub(crate) valid_resources: Vec<String>,
    pub(crate) default_user: String,
    pub(crate) default_action: String,
    pub(crate) default_resource: String,
}

impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        info!(LOG_DRAIN, "starting settings validation");

        if self.valid_users.is_empty() {
            return Err("validUsers cannot be empty".to_string());
        }

        if self.valid_actions.is_empty() {
            return Err("validActions cannot be empty".to_string());
        }

        if self.valid_resources.is_empty() {
            return Err("validResources cannot be empty".to_string());
        }

        if self.default_user.is_empty() {
            return Err("defaultUser cannot be empty".to_string());
        }

        if self.default_action.is_empty() {
            return Err("defaultAction cannot be empty".to_string());
        }

        if self.default_resource.is_empty() {
            return Err("defaultResource cannot be empty".to_string());
        }

        Ok(())
    }
}
----

und die Funktion `+validate+`, um die Mutation einzuführen:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: RawValidationRequest =
        if let Ok(validation_request) = serde_json::from_slice(payload) {
            validation_request
        } else {
            return kubewarden::reject_request(
                Some("cannot unmarshal request".to_string()),
                None,
                None,
                None,
            );
        };

    info!(LOG_DRAIN, "starting validation");

    let request = validation_request.request;
    let settings = validation_request.settings;

    if settings.valid_users.contains(&request.user)
        && settings.valid_actions.contains(&request.action)
        && settings.valid_resources.contains(&request.resource)
    {
        info!(LOG_DRAIN, "accepting request");
        return kubewarden::accept_request();
    }

    info!(LOG_DRAIN, "mutating request");
    let mut request = request;

    if !settings.valid_users.contains(&request.user) {
        request.user = settings.default_user;
    }

    if !settings.valid_actions.contains(&request.action) {
        request.action = settings.default_action;
    }

    if !settings.valid_resources.contains(&request.resource) {
        request.resource = settings.default_resource;
    }

    let mutated_request = serde_json::to_value(request)?;
    kubewarden::mutate_request(mutated_request)
}
----
