= Métricas
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-16
:page-revdate: {revdate}

K3s proporciona métricas para supervisar la salud y el rendimiento del clúster.

La mayoría de las métricas son proporcionadas por componentes individuales. Para más información, consulte la documentación específica de cada componente:

* https://coredns.io/plugins/metrics/[métricas coredns]
* https://etcd.io/docs/v3.5/metrics/[métricas etcd]

Otros componentes pueden proporcionar métricas adicionales. Consulte la documentación previa del proyecto para cualquier componente que no figure en la lista anterior.

== Métricas del supervisor

Cuando K3s se inicia con `+supervisor-metrics: true+`, las métricas son expuestas por el proceso K3s y se puede acceder a ellas a través del endpoint `+/metrics+` en cada nodo en el puerto `+6443+`:

[,sh]
----
kubectl get --server https://NODENAME:6443 --raw /metrics
----

El proceso supervisor K3s expone las siguientes métricas:

* Métricas de gestión del clúster K3s
* https://github.com/rancher/lasso/blob/main/README.md#lasso-controller[Métricas del controlador Lasso]
* https://github.com/kubernetes/client-go/blob/master/README.md[Métricas del cliente y de la cola de trabajo de Kubernetes]
* https://kubernetes.io/docs/reference/instrumentation/node-metrics/[Métricas del nodo Kubernetes]
* https://kubernetes.io/docs/reference/instrumentation/metrics/[Métricas de los componentes de Kubernetes]
* https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics[Métricas de tiempo de ejecución de Go]

Si el registro integrado de K3s está habilitado, el proceso supervisor de K3s también expone las siguientes métricas:

* https://spegel.dev/docs/metrics/[Métricas Spegel]
* https://github.com/libp2p/go-libp2p/blob/master/README.md[métricas libp2p]

K3s ejecuta todos los componentes de Kubernetes en el proceso principal de K3s. Dado que Kubernetes utiliza un único registro de métricas de Prometheus por proceso, las métricas de todos los componentes están disponibles a través de todos los puntos finales de métricas expuestos. Si rastrea todos los puntos finales de las métricas individuales, es posible que descubra que está recopilando métricas duplicadas. Solo es necesario raspar un único punto final de métricas K3s para obtener métricas de todos los componentes Kubernetes integrados.

== Métricas de gestión del clúster K3s

=== k3s_certificate_expiration_seconds

Tiempo de vida restante en segundos del certificado, etiquetado por asunto y usos del certificado.

* Tipo: Indicador
* Etiquetas: `+*subject*+`, `+*usage*+`

=== k3s_loadbalancer_server_connections

Recuento de conexiones actuales al servidor del equilibrador de carga, etiquetadas por el nombre del equilibrador de carga y la dirección del servidor.

* Tipo: Indicador
* Etiquetas: `+*name*+`, `+*server*+`

=== k3s_loadbalancer_server_health

Estado de salud actual de los servidores backend del equilibrador de carga, etiquetado por el nombre del equilibrador de carga y la dirección del servidor.

El estado es un enum de 0=INVALIDO, 1=FALLIDO, 2=EN ESPERA, 3=NO COMPROBADO, 4=RECUMPLIENDO, 5=SALUDABLE, 6=PREFERIDO, 7=ACTIVO.

* Tipo: Indicador
* Etiquetas: `+*name*+`, `+*server*+`

=== k3s_loadbalancer_dial_duration_seconds

Tiempo en segundos que se tarda en marcar una conexión a un servidor backend, etiquetado por el nombre del equilibrador de carga y el estado de éxito/fracaso.

* Tipo: Histograma
* Etiquetas: `+*name*+`, `+*status*+`

=== k3s_etcd_snapshot_save_duration_seconds

Tiempo total en segundos que tarda en completarse el proceso de instantánea etcd, etiquetado por estado de éxito/fracaso.

* Tipo: Histrograma
* Etiquetas: `+*status*+`

=== k3s_etcd_snapshot_save_local_duration_seconds

Tiempo total en segundos que se tarda en guardar un archivo de instantánea local, etiquetado por estado de éxito/fracaso.

* Tipo: Histrograma
* Etiquetas: `+*status*+`

=== k3s_etcd_snapshot_save_s3_duration_seconds

Tiempo total en segundos que se tarda en subir un archivo de instantánea a S3, etiquetado por estado de éxito/fracaso.

* Tipo: Histrograma
* Etiquetas: `+*status*+`

=== k3s_etcd_snapshot_reconcile_duration_seconds

Tiempo total en segundos que se tarda en sincronizar la lista de instantáneas etcd, etiquetadas por estado de éxito/fracaso.

* Tipo: Histrograma
* Etiquetas: `+*status*+`

=== k3s_etcd_snapshot_reconcile_local_duration_seconds

Tiempo total en segundos que se tarda en listar los archivos locales de instantáneas, etiquetados por estado de éxito/fracaso.

* Tipo: Histrograma
* Etiquetas: `+*status*+`

=== k3s_etcd_snapshot_reconcile_s3_duration_seconds

Tiempo total en segundos que se tarda en listar los archivos de instantáneas de S3, etiquetados por estado de éxito/fracaso.

* Tipo: Histrograma
* Etiquetas: `+*status*+`
