= Fehlersuche bei Monitoren
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: SUSE Observabilität

== Übersicht

* <<_the_result_of_the_monitor_isnt_showing_on_a_component,Das Ergebnis des Monitors wird bei einer Komponente nicht angezeigt>>
* <<_the_monitor_is_showing_an_error_in_the_monitor_status_overview,Der Monitor zeigt einen Fehler in der Monitorstatusübersicht an>>

=== Das Ergebnis des Monitors wird bei einer Komponente nicht angezeigt

Prüfen Sie zunächst, ob der Monitor xref:use/alerting/k8s-add-monitors-cli.adoc#_verify_the_execution_of_the_monitor[Ergebnisse liefert]. Wenn dies der Fall ist, aber die Monitorergebnisse nicht auf den Komponenten angezeigt werden, liegt möglicherweise ein Problem mit der Bindung vor. Verwenden Sie zunächst den folgenden Befehl, um dies zu überprüfen:

[,bash]
----
sts monitor status --id <id>
----

Wenn die Ausgabe `+Monitor health states with identifier which has no matching topology element (<nr>): ....+` lautet, zeigt dies, dass die `+urnTemplate+` möglicherweise keinen Bezeichner erzeugt, der zur Topologie passt. Um dies zu beheben, xref:use/alerting/k8s-add-monitors-cli.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[überarbeiten Sie Ihr urnTemplate].

=== Der Monitor zeigt einen Fehler in der Monitorstatusübersicht an

Abrufen des Status des Monitors über die CLI

[,bash]
----
sts monitor status --id <id>
----

Der Abschnitt `+Monitor Stream errors:+` zeigt die auf dem Monitor auftretenden Fehler an und bietet weitere Hilfe an.

