= Comment inclure des fichiers cloud-config à partir de périphériques amovibles ?
:revdate: 2025-09-08
:page-revdate: {revdate}

{elemental-product-name} prend en charge le chargement des fichiers de xref:references/cloud-config-reference.adoc[configuration du nuage à] partir de blocs spécifiques.
Il prend notamment en charge le chargement des fichiers de configuration du nuage à partir d'un ISO dont l'ID de volume est `+CIDATA+` ou de tout dispositif formaté vFAT étiqueté avec `+CIDATA+`. Si un périphérique correspondant à ces critères est trouvé au démarrage, le client {elemental-product-name} le lira et cherchera un fichier `+user-data+` dans sa racine.

A titre d'exemple, une ISO comprenant un fichier cloud-config peut être créée sur un hôte Linux en suivant la procédure ci-dessous.

Créez un fichier `+user-data+` contenant les données cloud-config. Dans l'exemple ci-dessous, nous définissons simplement un proxy :

.données de l'utilisateur
[,yaml]
----
#cloud-config
write_files:

* path: /etc/sysconfig/proxy
append: true
content: |
  PROXY_ENABLED="yes"
  HTTP_PROXY=http://some.domain.org:8080
  HTTPS_PROXY=https://some.domain.org:8080
  NO_PROXY="localhost, 127.0.0.1"
----

Une fois que le fichier `+user-data+` existe, créez une ISO contenant uniquement ce fichier en utilisant l'utilitaire Linux `+mkisofs+`:

[,bash]
----
mkisof -o cidata.iso -V CIDATA -J -r user-data
----

Le résultat est un ISO étiqueté avec `+CIDATA+` incluant le fichier `+user-data+`.

Au démarrage, le fichier `+user-data+` sera copié tel quel sur `+/oem/user-data+` et, s'il contient des données de configuration du nuage, une copie supplémentaire sera ajoutée en tant que `+/oem/user-data.yaml+`. Le fichier `+/oem/user-data.yaml+` sera analysé lors d'une étape ultérieure du "cloud-init".

Puisque les données sont copiées sur `+/oem+`, elles seront persistantes, ce qui signifie que lors des redémarrages suivants, il n'est plus nécessaire que le périphérique amovible soit présent. S'il est toujours présent lors des redémarrages suivants, il écrase simplement toutes les données préexistantes.

== Inclure les données non liées à la configuration du nuage

Si le site `+user-data+` ne contient pas de données de configuration du nuage, le client {elemental-product-name} se contentera de les copier telles quelles sur le site `+/oem/user-data+`. Seuls les fichiers `+*.yaml+` sont analysés lors de l'exécution des étapes de cloud-init. Dans ce cas, le fichier sera ignoré par les services de cloud-init.

Si le site `+user-data+` contient un script, le client {elemental-product-name} essaiera en outre de l'exécuter. La façon dont le client{elemental-product-name} détermine si `+user-data+` est un script ou non est la présence d'un _Shebang_ dans la première ligne. Par exemple, le fichier précédent `+user-data+` pourrait être réécrit comme suit :

.données de l'utilisateur
[,bash]
----
#!/bin/bash

cat <<EOF >> /etc/sysconfig/proxy
PROXY_ENABLED="yes"
HTTP_PROXY=http://some.domain.org:8080
HTTPS_PROXY=https://some.domain.org:8080
NO_PROXY="localhost, 127.0.0.1"
EOF
----
