= Permissões necessárias
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Visão geral

Todos os componentes próprios do SUSE Observability podem ser executados sem nenhuma permissão adicional. No entanto, para instalar o SUSE Observability com êxito, você precisa de alguns privilégios adicionais ou garantir que os requisitos descritos nesta página sejam atendidos.

== Autenticação e autorização de serviço para serviço

Para permitir a comunicação entre os serviços do SUSE Observability, o SUSE Observability usa contas de serviço do Kubernetes. Para poder verificar sua validade e funções, o mapa do leme cria os recursos `ClusterRole` e `ClusterRoleBinding`. A criação desses recursos em todo o cluster geralmente é proibida para usuários que não são administradores do Kubernetes/OpenShift. Nesse caso, a criação pode ser desativada e, em vez disso, as funções e as associações de funções precisam ser xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc#_manually_create_cluster_wide_resources[criadas manualmente] pelo administrador do cluster.

=== Desativar a criação automática de recursos em todo o cluster

A criação automática de recursos em todo o cluster durante a instalação do SUSE Observability pode ser desativada adicionando a seguinte seção ao arquivo `values.yaml` usado para instalar o SUSE Observability:

[tabs]
====
values.yaml::
+
--

[,yaml]
----
cluster-role:
  enabled: false
----

--
====

[NOTE]
====
Se a criação da função de cluster e da associação de função de cluster tiver sido desativada, siga as instruções abaixo para criá-las manualmente usando as xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc#_manually_create_cluster_wide_resources[instruções abaixo].
====


=== Criar manualmente recursos em todo o cluster

Se você precisar criar manualmente os recursos de todo o cluster, peça ao administrador do Kubernetes/OpenShift para criar os três recursos abaixo no cluster.

[NOTE]
====
Verifique se você especificou a conta de serviço e o namespace corretos para o `ServiceAccount` vinculado a ambos os recursos do `ClusterRoleBinding`. O exemplo pressupõe que o espaço de nome `suse-observability` seja usado e que `suse-observability` seja usado como a versão; se algum outro espaço de nome for usado, altere o espaço de nome nos exemplos. Além disso, as contas de serviço referenciadas precisam ser alteradas para `<release>-suse-observability-api`.
====


[tabs]
====
clusterrole-authorization.yaml::
+
--

[,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suse-observability-authorization
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
----

--
====

[tabs]
====
clusterrolebinding-authentication.yaml::
+
--

[,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suse-observability-authentication
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: suse-observability-api
  namespace: suse-observability
----

--
====

[tabs]
====
clusterrolebinding-authorization.yaml::
+
--

[,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suse-observability-authorization
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: suse-observability-authorization
subjects:
- kind: ServiceAccount
  name: suse-observability-api
  namespace: suse-observability
----

--
====

== Padrões de segurança de pods

Se o seu cluster do Kubernetes tiver https://kubernetes.io/docs/concepts/security/pod-security-standards/[os padrões de segurança do pod], você precisará configurar as políticas de segurança apropriadas para o namespace `suse-observability`. O SUSE Observability requer a linha de base do Pod Security Standard para funcionar corretamente.

=== Configurar padrões de segurança do pod

Aplique o padrão de segurança de linha de base do pod ao namespace `suse-observability`:

[,bash]
----
kubectl label ns suse-observability pod-security.kubernetes.io/enforce=baseline --overwrite
kubectl label ns suse-observability pod-security.kubernetes.io/audit=baseline --overwrite
kubectl label ns suse-observability pod-security.kubernetes.io/warn=baseline --overwrite
----

[NOTE]
====
Se os Padrões de segurança de pod estiverem ativados em seu cluster, você deverá garantir que os pré-requisitos do Elasticsearch estejam configurados corretamente antes de implantar o SUSE Observability.
Como a linha de base Pod Security Standard não permite contêineres privilegiados, é necessário seguir xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc#_elasticsearch[as instruções] para configurar o parâmetro de kernel `vm.max_map_count` necessário no nível do host.
====


== Elasticsearch

O SUSE Observability usa o Elasticsearch para armazenar seus índices. Há alguns requisitos adicionais para os nós em que o Elasticsearch é executado.

Como a configuração do sistema `vm.max_map_count` Linux geralmente é menor do que a necessária para que o Elasticsearch seja iniciado, é usado um contêiner de inicialização que é executado em modo privilegiado e como usuário raiz. O contêiner init é ativado por padrão para permitir que a configuração do sistema `vm.max_map_count` seja alterada.

=== Desabilitar o contêiner de inicialização privilegiado do Elasticsearch

Caso você ou seus administradores do Kubernetes/OpenShift não queiram que o contêiner de inicialização privilegiado do Elasticsearch seja ativado por padrão, é possível desativar esse comportamento no arquivo `values.yaml` usado para instalar o SUSE Observability:

[tabs]
====
values.yaml::
+
--

[,yaml]
----
elasticsearch:
  sysctlInitContainer:
    enabled: false
----

--
====

[NOTE]
====
Se isso estiver desativado, você precisará garantir que a configuração `vm.max_map_count` seja alterada de seu valor padrão comum de `65530` para `262144`. Se isso não for feito, o Elasticsearch falhará na inicialização e seus pods ficarão em um loop de reinicialização.
====


Para inspecionar a configuração atual de `vm.max_map_count`, execute o seguinte comando. Observe que ele executa um pod privilegiado:

[,text]
----
kubectl run -i --tty sysctl-check-max-map-count --privileged=true  --image=busybox --restart=Never --rm=true -- sysctl vm.max_map_count
----

Se a configuração atual de `vm.max_map_count` não for pelo menos `262144`, ela precisará ser aumentada de uma maneira diferente ou o Elasticsearch não conseguirá iniciar e seus pods ficarão em um loop de reinicialização. Os registros conterão uma mensagem de erro como esta:

[,text]
----
bootstrap checks failed
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
----

=== Aumentar as configurações do sistema Linux para o Elasticsearch

Dependendo da preferência dos administradores do Kubernetes/OpenShift, o `vm.max_map_count` pode ser definido como um padrão mais alto em todos os nós, alterando a configuração padrão do nó (por exemplo, por meio de scripts de inicialização) ou fazendo com que um DaemonSet faça isso logo após a inicialização do nó. O primeiro depende muito da configuração de seu computador, portanto, não há soluções gerais para isso.

Abaixo está um exemplo que pode ser usado como ponto de partida para que um DaemonSet altere a configuração `vm.max_map_count`:

[,yaml]
----
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: set-vm-max-map-count
  namespace: kube-system
  labels:
    k8s-app: set-vm-max-map-count
spec:
  selector:
    matchLabels:
      name: set-vm-max-map-count
  template:
    metadata:
      labels:
        name: set-vm-max-map-count
    spec:
      # Make sure the setting always gets changed as soon as possible:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
      # Optional node selector (assumes nodes for Elasticsearch are labeled `elasticsearch:yes`
      # nodeSelector:
      #  elasticsearch: yes
      initContainers:
        - name: set-vm-max-map-count
          image: busybox
          securityContext:
            runAsUser: 0
            privileged: true
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      # A pause container is needed to prevent a restart loop of the pods in the daemonset
      # See also this Kubernetes issue https://github.com/kubernetes/kubernetes/issues/36601
      containers:
        - name: pause
          image: busybox
          command: ["sleep", "infinity"]
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
----

Para limitar o número de nós aos quais isso é aplicado, os nós podem ser rotulados. Os NodeSelectors nesse DaemonSet, conforme mostrado no exemplo, e a implantação do Elasticsearch podem ser definidos para serem executados somente em nós com o rótulo específico. Para o Elasticsearch, o seletor de nó pode ser especificado por meio dos valores:

[,yaml]
----
elasticsearch:
  nodeSelector:
    elasticsearch: yes
  sysctlInitContainer:
    enabled: false
----

== Veja também

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[Instalar o SUSE Observability no Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[Instalar o SUSE Observability no OpenShift]
