= Anforderungen
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-31
:page-revdate: {revdate}

K3s ist sehr leichtgewichtig, hat aber einige Mindestanforderungen, die im Folgenden beschrieben werden.

Unabhängig davon, ob Sie K3s für die Ausführung in einem Container oder als nativen Linux-Dienst konfigurieren, sollte jeder Knoten, auf dem K3s ausgeführt wird, die folgenden Mindestanforderungen erfüllen. Diese Anforderungen beziehen sich auf K3s und die zugehörigen Komponenten und beinhalten nicht die vom Workload selbst verbrauchten Ressourcen.

== Voraussetzungen

Zwei Knoten können nicht denselben Hostnamen haben.

Wenn mehrere Knoten denselben Hostnamen haben werden oder wenn Hostnamen von einem automatischen Bereitstellungssystem wiederverwendet werden können, verwenden Sie die Option `--with-node-id`, um ein zufälliges Suffix für jeden Knoten anzuhängen, oder denken Sie sich einen eindeutigen Namen aus, den Sie mit `--node-name` oder `$K3S_NODE_NAME` für jeden Knoten übergeben, den Sie dem Cluster hinzufügen.

== Architektur

K3s ist für die folgenden Architekturen verfügbar:

* x86_64
* armhf
* arm64/aarch64

[CAUTION]
.ARM64 Seitengröße
====

Vor Mai 2023 (v1.24.14+k3s1, v1.25.10+k3s1, v1.26.5+k3s1, v1.27.2+k3s1) muss der Kernel auf `aarch64/arm64` Systemen 4k Seiten verwenden. *RHEL9*, *Ubuntu*, *Raspberry PI OS* und *SLES* erfüllen alle diese Anforderung.
====

[#_operating_systems]
== Betriebssysteme

Es wird erwartet, dass K3s auf den meisten modernen Linux-Systemen funktioniert.

Einige Betriebssysteme haben zusätzliche Einrichtungsanforderungen:

[tabs,sync-group-id=os,id=os]
======
SUSE Linux Enterprise/openSUSE::
+
--
[#_sle_opensuse_firewalld]
[pass]
<h3><a class="anchor" id="_sle_opensuse_firewalld" href="#_sle_opensuse_firewalld"></a>Firewalld</h3>

Es wird empfohlen, firewalld zu deaktivieren:

[,bash]
----
systemctl disable firewalld --now
----

Wenn Sie firewalld standardmäßig aktiviert lassen möchten, sind die folgenden Regeln erforderlich:

[,bash]
----
firewall-cmd --permanent --add-port=6443/tcp #apiserver
firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
firewall-cmd --reload
----

Je nach Ihrer Einrichtung müssen möglicherweise weitere Ports geöffnet werden. Weitere Informationen finden Sie unter <<_inbound_rules_for_k3s_nodes,Eingehende Regeln>>. Wenn Sie die Standard-CIDR für Pods oder Dienste ändern, müssen Sie die Firewall-Regeln entsprechend aktualisieren.
--

Red Hat Enterprise Linux / CentOS / Fedora::
+
--
[#_rhel10]
[pass]
<h3><a class="anchor" id="_rhel10" href="#_rhel10"></a>RHEL 10</h3>

Unter RHEL 10 ist ein zusätzliches Paket erforderlich:

[,bash]
----
sudo dnf install -y kernel-modules-extra
----

[#_rhel_centos_fedora_firewalld]
[pass]
<h3><a class="anchor" id="_rhel_centos_fedora_firewalld" href="#_rhel_centos_fedora_firewalld"></a>Firewalld</h3>

Es wird empfohlen, firewalld zu deaktivieren:

[,bash]
----
systemctl disable firewalld --now
----

Wenn Sie firewalld standardmäßig aktiviert lassen möchten, sind die folgenden Regeln erforderlich:

[,bash]
----
firewall-cmd --permanent --add-port=6443/tcp #apiserver
firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
firewall-cmd --reload
----

Je nach Ihrer Einrichtung müssen möglicherweise weitere Ports geöffnet werden. Weitere Informationen finden Sie unter <<_inbound_rules_for_k3s_nodes,Eingehende Regeln>>. Wenn Sie die Standard-CIDR für Pods oder Dienste ändern, müssen Sie die Firewall-Regeln entsprechend aktualisieren.

[WARNING]
.Ältere RHEL/CentOS-Versionen
====
Betriebssystemversionen vor RHEL 8.4 enthalten NetworkManager mit einem bekannten Fehler, der das Netzwerk von K3 beeinträchtigt. Wenn Sie eine ältere Version verwenden, ist es erforderlich, nm-cloud-setup zu deaktivieren und den Knoten neu zu starten:

[,bash]
----
systemctl disable nm-cloud-setup.service nm-cloud-setup.timer
reboot
----
====
--

Ubuntu/Debian::
+
--
[#_ubuntu_debian_ufw]
[pass]
<h3><a class="anchor" id="_ubuntu_debian_ufw" href="#_ubuntu_debian_ufw"></a>UFW</h3>

Ältere Debian-Veröffentlichungen leiden möglicherweise unter einem bekannten iptables-Fehler. Siehe xref:known-issues.adoc#_iptables["Bekannte Probleme"].

Es wird empfohlen, ufw (uncomplicated firewall) zu deaktivieren:

[,bash]
----
ufw disable
----

Wenn Sie ufw standardmäßig aktiviert lassen möchten, sind die folgenden Regeln erforderlich:

[,bash]
----
ufw allow 6443/tcp #apiserver
ufw allow from 10.42.0.0/16 to any #pods
ufw allow from 10.43.0.0/16 to any #services
----

Je nach Ihrer Einrichtung müssen möglicherweise weitere Ports geöffnet werden. Weitere Informationen finden Sie unter <<_inbound_rules_for_k3s_nodes,Eingehende Regeln>>. Wenn Sie die Standard-CIDR für Pods oder Dienste ändern, müssen Sie die Firewall-Regeln entsprechend aktualisieren.
--

[#os_tab_raspberry_pi]
Raspberry Pi::
+
--
Das Betriebssystem des Raspberry Pi basiert auf Debian und kann von einem bekannten iptables-Fehler betroffen sein. Siehe xref:known-issues.adoc#_iptables["Bekannte Probleme"].

[#_cgroups]
[pass]
<h3><a class="anchor" id="_cgroups" href="#_cgroups"></a>C-Gruppen</h3>

Standard Raspberry Pi OS Installationen starten nicht mit `cgroups`. **K3S** benötigt `cgroups`, um den systemd-Dienst zu starten. `cgroups`kann durch Anhängen von `cgroup_memory=1 cgroup_enable=memory` an `/boot/firmware/cmdline.txt` aktiviert werden.

[NOTE]
====
Unter Debian 11 und älteren Pi OS Versionen befindet sich die cmdline.txt unter `/boot/cmdline.txt`.
====

Beispiel cmdline.txt:

----
console=serial0,115200 console=tty1 root=PARTUUID=58b06195-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait cgroup_memory=1 cgroup_enable=memory
----

[#_ubuntu_vxlan_module]
[pass]
<h3><a class="anchor" id="_ubuntu_vxlan_module" href="#_ubuntu_vxlan_module"></a>Ubuntu Vxlan-Modul</h3>

Mit Ubuntu 21.10 bis Ubuntu 23.10 wurde die vxlan-Unterstützung auf dem Raspberry Pi in ein separates Kernelmodul verschoben. Dieser Schritt ist für Ubuntu 24.04 und höher nicht erforderlich.

[,bash]
----
sudo apt install linux-modules-extra-raspi
----
--
======

Weitere Informationen darüber, welche Betriebssysteme mit von Rancher verwalteten K3s-Clustern getestet wurden, finden Sie in den https://rancher.com/support-maintenance-terms/[Support- und Wartungsbedingungen.] Rancher

== Hardware

Die Hardware-Anforderungen sind abhängig von der Größe Ihrer Implementierungen. Die Mindestanforderungen sind:

|===
| Knotenpunkt | CPU | RAM

| Server
| 2 Kerne
| 2 GB

| Agent
| 1 Kern
| 512 MB
|===

xref:reference/resource-profiling.adoc[Resource Profiling] erfasst die Ergebnisse von Tests und Analysen, um die minimalen Ressourcenanforderungen für den K3s-Agenten, den K3s-Server mit einer Arbeitslast und den K3s-Server mit einem Agenten zu ermitteln.

=== Festplatten

Die Leistung von K3 hängt von der Leistung der Datenbank ab. Um eine optimale Geschwindigkeit zu gewährleisten, empfehlen wir, wenn möglich eine SSD zu verwenden. 

Wenn Sie K3s auf einem Raspberry Pi oder anderen ARM-Geräten einsetzen, empfiehlt sich die Verwendung einer externen SSD. etcd ist schreibintensiv; SD-Karten und eMMC können die IO-Last nicht bewältigen.

=== Leitfaden zur Servergrößenbestimmung

Wenn CPU und RAM auf dem Serverknoten (Steuerebene + etcd) begrenzt sind, gibt es Einschränkungen bei der Anzahl der Agentenknoten, die unter Standardarbeitslastbedingungen verbunden werden können.

|===
| Server-CPU | Server-RAM | Anzahl der Agenten

| 2
| 4 GB
| 0-350

| 4
| 8 GB
| 351-900

| 8
| 16 GB
| 901-1800

| 16+
| 32 GB
| 1800+
|===

[TIP]
.Sizing für hohe Verfügbarkeit
====
Bei einer Hochverfügbarkeitskonfiguration mit 3 Serverknoten kann die Anzahl der Agenten etwa ~50 % höher skaliert werden als in der obigen Tabelle angegeben. Z.B. können 3 Server mit 4 vCPU/8 GB auf ~1200 Agenten skalieren.
====

Es wird empfohlen, Agenten-Knoten in Stapeln von 50 oder weniger beizutreten, damit die CPU Speicherplatz freimachen kann, da beim Beitritt zu einem Knoten eine Spitzenbelastung auftritt. Denken Sie daran, die Standardeinstellung `cluster-cidr` zu ändern, wenn Sie mehr als 255 Knoten wünschen!

xref:reference/resource-profiling.adoc#_server_sizing_requirements_for_k3s[Resource Profiling] enthält weitere Informationen darüber, wie diese Empfehlungen gefunden wurden.

[#_networking]
== Vernetzung

Der K3s-Server benötigt Port 6443, um von allen Knoten aus erreichbar zu sein.

Die Knoten müssen in der Lage sein, andere Knoten über den UDP-Port 8472 zu erreichen, wenn sie das Flannel VXLAN-Backend verwenden, oder über den UDP-Port 51820 (und 51821, wenn IPv6 verwendet wird), wenn sie das Flannel WireGuard-Backend verwenden. Der Knoten sollte an keinem anderen Port lauschen. K3s verwendet Reverse Tunneling, d.h. die Knoten stellen ausgehende Verbindungen zum Server her und der gesamte Kubelet-Verkehr läuft durch diesen Tunnel. Wenn Sie jedoch Flannel nicht verwenden und Ihr eigenes benutzerdefiniertes CNI bereitstellen, dann werden die von Flannel benötigten Ports von K3s nicht benötigt.

Wenn Sie den Metriken-Server verwenden möchten, müssen alle Knoten untereinander über Port 10250 erreichbar sein.

Wenn Sie mit eingebettetem etcd Hochverfügbarkeit erreichen wollen, müssen die Serverknoten untereinander über die Ports 2379 und 2380 erreichbar sein.

[TIP]
.Wichtig
====
Der VXLAN-Port auf den Knoten sollte nicht öffentlich zugänglich sein, da er das Clusternetzwerk für jeden zugänglich macht. Betreiben Sie Ihre Knoten hinter einer Firewall/Sicherheitsgruppe, die den Zugriff auf Port 8472 deaktiviert.
====


[WARNING]
====
Flannel stützt sich auf das https://www.cni.dev/plugins/current/main/bridge/[Bridge CNI-Plugin], um ein L2-Netzwerk zu erstellen, das den Datenverkehr vermittelt. Abtrünnige Pods mit `NET_RAW` -Funktionen können dieses L2-Netzwerk für Angriffe wie ARP-Spoofing missbrauchen. Daher sollten Sie, wie in den https://kubernetes.io/docs/concepts/security/pod-security-standards/[Kubernetes-Dokumenten] dokumentiert, ein eingeschränktes Profil einrichten, das `NET_RAW` auf nicht vertrauenswürdigen Pods deaktiviert.
====

[#_inbound_rules_for_k3s_nodes]
=== Eingehende Regeln für K3s-Knoten

|===
| Protokoll | Port | Quelle | Reiseziel | Beschreibung

| TCP
| 2379-2380
| Server
| Server
| Nur für HA mit eingebettetem etcd erforderlich

| TCP
| 6443
| Agents
| Server
| K3s-Supervisor und Kubernetes-API-Server

| UDP
| 8472
| Alle Knotenpunkte
| Alle Knotenpunkte
| Nur für Flannel VXLAN erforderlich

| TCP
| 10250
| Alle Knotenpunkte
| Alle Knotenpunkte
| Kubelet-Metriken

| UDP
| 51820
| Alle Knotenpunkte
| Alle Knotenpunkte
| Nur für Flannel Wireguard mit IPv4 erforderlich

| UDP
| 51821
| Alle Knotenpunkte
| Alle Knotenpunkte
| Nur für Flannel Wireguard mit IPv6 erforderlich

| TCP
| 5001
| Alle Knotenpunkte
| Alle Knotenpunkte
| Nur für eingebettete verteilte Register erforderlich (Spegel)

| TCP
| 6443
| Alle Knotenpunkte
| Alle Knotenpunkte
| Nur für eingebettete verteilte Register erforderlich (Spegel)
|===

Normalerweise ist der gesamte ausgehende Verkehr erlaubt.

Je nach verwendetem Betriebssystem können zusätzliche Änderungen an der Firewall erforderlich sein.

== Große Cluster

Die Hardware-Anforderungen hängen von der Größe Ihres K3s-Clusters ab. Für die Produktion und große Cluster empfehlen wir die Verwendung einer Hochverfügbarkeitseinrichtung mit einer externen Datenbank. Die folgenden Optionen werden für die externe Datenbank in der Produktion empfohlen:

* MySQL
* PostgreSQL
* etcd

=== CPU und Speicher

Nachfolgend sind die Mindestanforderungen an CPU und Speicher für Knoten in einem hochverfügbaren K3s-Server aufgeführt:

[cols="^,^,^,^"]
|===
| Größe des Einsatzes | Knotenpunkte | vCPUs | RAM

| Small
| bis zu 10
| 2
| 4 GB

| Mittel
| bis zu 100
| 4
| 8 GB

| Groß
| Bis zu 250
| 8
| 16 GB

| X-Large
| bis zu 500
| 16
| 32 GB

| XX-Large
| 500+
| 32
| 64 GB
|===

=== Festplatten

Die Leistung des Clusters hängt von der Leistung der Datenbank ab. Um eine optimale Geschwindigkeit zu gewährleisten, empfehlen wir, für die Sicherung Ihres K3s-Clusters immer SSD-Festplatten zu verwenden. Bei Cloud-Anbietern sollten Sie auch die Mindestgröße verwenden, die die maximale IOPS erlaubt.

=== Netzwerk

Sie sollten in Erwägung ziehen, die Größe des Subnetzes für den Cluster-CIDR zu erhöhen, damit Sie nicht zu wenig IPs für die Pods haben. Sie können dies tun, indem Sie K3s Server beim Start die Option `--cluster-cidr` übergeben.

=== Datenbank

K3s unterstützt verschiedene Datenbanken wie MySQL, PostgreSQL, MariaDB und etcd.  Siehe xref:datastore/datastore.adoc[Cluster-Datenspeicher] für weitere Informationen.

Im Folgenden finden Sie einen Leitfaden für die Dimensionierung der Datenbankressourcen, die Sie für den Betrieb großer Cluster benötigen:

[cols="^,^,^,^"]
|===
| Größe des Einsatzes | Knotenpunkte | vCPUs | RAM

| Small
| bis zu 10
| 1
| 2 GB

| Mittel
| bis zu 100
| 2
| 8 GB

| Groß
| Bis zu 250
| 4
| 16 GB

| X-Large
| bis zu 500
| 8
| 32 GB

| XX-Large
| 500+
| 16
| 64 GB
|===
