== Instalar {elemental-product-name} Operador
:revdate: 2025-09-08
:page-revdate: {revdate}

`+elemental-operator+` es el punto final de gestión, que ejecuta el clúster de gestión y se encarga de crear inventarios, registros de máquinas y mucho más.

Utilizaremos el gestor de paquetes Helm para instalar la tabla elemental-operator en nuestro cluster.

[,console]
----
helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator-crds oci://registry.suse.com/rancher/elemental-operator-crds-chart

helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.suse.com/rancher/elemental-operator-chart
----

Ahora, después de unos segundos, debería ver aparecer el pod de operador en el espacio de nombres `+cattle-elemental-system+`:

[,console]
----
kubectl get pods -n cattle-elemental-system

NAME                                  READY   STATUS    RESTARTS   AGE
elemental-operator-64f88fc695-b8qhn   1/1     Running   0          16s
----

[IMPORTANT]
.Se requiere Helm v3.8.0+.
----
La carta del operador {elemental-product-name} se distribuye a través de un registro OCI: Helm soporta correctamente los registros basados en OCI a partir de la versión v3.8.0.
----


[CAUTION]
.Cambiar el orden de instalación de los gráficos al actualizar desde elemental-operator release < 1.2.4
----
Cuando se actualiza desde una versión de elemental-operator que incluye los CRD de {elemental-product-name} (versión < 1.2.4), la instalación del gráfico elemental-operator-crds fallará.
Primero tendrá que actualizar la carta elemental-operator, y sólo después instalar la carta elemental-operator-crds.
----

=== Instalaciones no estables

Además de las cartas Helm mencionadas, hay otras dos versiones disponibles en `+non-stable+`.

* *Staging:* se refiere a la última versión etiquetada de Github. Esto se documenta en las páginas xref:quickstarts/quickstart-ui.adoc[siguientes].
* *Desarrollo:* se refiere a la "punta de HEAD" de Github. Esta es la versión de desarrollo en curso y cambia constantemente.

[tabs]
=====
Versión de prueba (x86-64, ARM64 (Raspberry Pi 4))::
+
--
[,console]
----
helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator-crds oci://registry.opensuse.org/isv/rancher/elemental/staging/charts/rancher/elemental-operator-crds-chart 
helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/staging/charts/rancher/elemental-operator-chart
----
--

Versión de desarrollo (x86-64, ARM64 (Raspberry Pi 4))::
+
--
[WARNING]
.Recordatorio
====
La versión de desarrollo no se recomienda para entornos de producción. Agradecemos los comentarios a través de Slack o Github issues, pero podría ser inestable y contener características experimentales que pueden ser eliminadas sin previo aviso.
====

[,console]
----
helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator-crds oci://registry.opensuse.org/isv/rancher/elemental/dev/charts/rancher/elemental-operator-crds-chart
helm upgrade --create-namespace -n cattle-elemental-system --install --set image.imagePullPolicy=Always elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/dev/charts/rancher/elemental-operator-chart
----
--
=====

=== Opciones de instalación

Hay algunas opciones que se pueden configurar en la instalación de la carta, pero eso está fuera del alcance de este documento. Puede ver todos los valores en el gráfico https://github.com/rancher/elemental-operator/blob/main/.obs/chartfile/elemental-operator-helm/values.yaml[values.yaml].
