:sidebar_label: Référence CLI du serveur de politiques
:sidebar_position: 121
:title: CLI du serveur de politiques
:description: Explorez l'aide et les options de la ligne de commande de policy-server pour personnaliser et exécuter le programme \`+policy-server+`.
:keywords: [cli, reference, policy-server]
:doc-persona: [kubewarden-operator]
:doc-type: [référence]
:doc-topic: [operator-manual]
include::partial$variables.adoc[]
:revdate: 2026-03-18
:page-revdate: {revdate}

= {title}

== Aide en ligne de commande pour `+policy-server+`

Ce document contient le contenu de l'aide pour le programme de ligne de commande `+policy-server+`.

*Aperçu des commandes :*

* link:#policy-server[`+policy-server+`]
* link:#policy-server-docs[`+policy-server docs+`]

=== `+policy-server+`

*Utilisation :* `+policy-server ++[++OPTIONS++]++ ++[++COMMAND++]+++`

==== *Sous-commandes :*

* `+docs+` - Génère la documentation markdown pour les commandes du serveur de politique

==== *Options :*

* `+--addr ++<++BIND++_++ADDRESS++>+++` - Lier à l'adresse ADDRESS
+
Valeur par défaut : `+0.0.0.0+`
* `+--always-accept-admission-reviews-on-namespace ++<++NAMESPACE++>+++` - Accepter toujours les examens d'admission qui ciblent l'espace de noms donné
* `+--cert-file ++<++CERT++_++FILE++>+++` - Chemin d'accès à un fichier de certificat X.509 pour HTTPS
* `+--client-ca-file ++<++CLIENT++_++CA++_++FILE++>+++` - Chemin d'accès à un fichier de certificat de l'autorité de certification qui a émis le certificat du client. Requis pour activer mTLS
* `+--daemon+` - S'il est défini, le serveur de politique est exécuté en mode détaché en tant que démon.
* `+--daemon-pid-file ++<++DAEMON-PID-FILE++>+++` - Chemin d'accès au fichier PID, utilisé uniquement en mode démon
+
Valeur par défaut : `+policy-server.pid+`
* `+--daemon-stderr-file ++<++DAEMON-STDERR-FILE++>+++` - Chemin d'accès au fichier contenant stderr, utilisé uniquement en mode démon.
* `+--daemon-stdout-file ++<++DAEMON-STDOUT-FILE++>+++` - Chemin d'accès au fichier contenant stdout, utilisé uniquement en mode démon.
* `+--disable-timeout-protection+` - Désactiver la protection du délai d'attente de la politique
* `+--docker-config-json-path ++<++DOCKER++_++CONFIG++>+++` - Chemin d'accès à une configuration Docker de type config.json. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `+--enable-metrics+` - Activer les mesures
* `+--enable-pprof+` - Activer le profilage pprof
* `+--ignore-kubernetes-connection-failure+` - Ne pas sortir avec une erreur si la connexion Kubernetes échoue. Cela entraînera l'interruption des politiques contextuelles lorsqu'il n'y a pas de connexion avec Kubernetes.
* `+--key-file ++<++KEY++_++FILE++>+++` - Chemin d'accès à un fichier de clé privée X.509 pour HTTPS
* `+--log-fmt ++<++LOG++_++FMT++>+++` - Format de sortie du journal
+
Valeur par défaut : `+text+`
+
Valeurs possibles : `+text+`, `+json+`, `+otlp+`
* `+--log-level ++<++LOG++_++LEVEL++>+++` - Niveau d'enregistrement
+
Valeur par défaut : `+info+`
+
Valeurs possibles : `+trace+`, `+debug+`, `+info+`, `+warn+`, `+error+`
* `+--log-no-color+` - Désactiver la sortie colorée des journaux
* `+--policies ++<++POLICIES++_++FILE++>+++` - fichier YAML contenant les politiques à charger et leurs paramètres
+
Valeur par défaut : `+policies.yml+`
* `+--policies-download-dir ++<++POLICIES++_++DOWNLOAD++_++DIR++>+++` - Chemin de téléchargement des politiques
+
Valeur par défaut : `+.+`
* `+--policy-timeout ++<++MAXIMUM++_++EXECUTION++_++TIME++_++SECONDS++>+++`
- Interrompre l'évaluation de la politique après le temps donné
+
Valeur par défaut : `+2+`
* `+--port ++<++PORT++>+++` - Écouter sur PORT
+
Valeur par défaut : `+3000+`
* `+--readiness-probe-port ++<++READINESS++_++PROBE++_++PORT++>+++` —
Expose readiness endpoint on READINESS++_++PROBE++_++PORT
+
Valeur par défaut : `+8081+`
* `+--sigstore-cache-dir ++<++SIGSTORE++_++CACHE++_++DIR++>+++` - Répertoire utilisé pour mettre en cache les données sigstore
+
Valeur par défaut : `+sigstore-data+`
* `+--sources-path ++<++SOURCES++_++PATH++>+++` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, CA personnalisées\...)
* `+--verification-path ++<++VERIFICATION++_++CONFIG++_++PATH++>+++` - Fichier YAML contenant les informations de vérification (URI, clés, annotations\...)
* `+--workers ++<++WORKERS++_++NUMBER++>+++` - Nombre de threads de travailleur à créer

=== `+policy-server docs+`

Génère la documentation markdown pour les commandes du serveur de politique

*Utilisation :* `+policy-server docs --output ++<++FILE++>+++`

==== *Options :*

* `+-o+`, `+--output ++<++FILE++>+++` - chemin d'accès où le fichier de documentation sera stocké

Ce document a été généré automatiquement par clap-markdown.
