include::partial$variables.adoc[]
= Référence pour sources.yaml
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configurez votre fichier sources.yaml pour qu'il fonctionne avec les CR de PolicyServer en spécifiant le chemin et le format des autorités sources, ainsi que les sources non sécurisées.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "sources.yaml"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "sources.yaml"]
:sidebar_label: sources.yaml
:sidebar_position: 110
:current-version: {page-origin-branch}

Vous pouvez régler le comportement push-pull des binaires `+kwctl+` et `+policy-server+` à l'aide de l'argument `+--sources-path+`, en spécifiant le chemin d'accès au fichier`+sources.yaml+`.

Pour configurer un PolicyServer CR, définissez ses champs `+spec.insecureSources+` et`+spec.sourceAuthorities+`. Le format de ces champs correspond aux sections respectives ci-dessous.

== Le fichier `+sources.yaml+` 

Si vous omettez l'argument `+--sources-path+` dans la commande `+kwctl+`, celle-ci tente de charger le fichier `+sources.yaml+` à partir de ces dossiers :

* Linux : `+$HOME/.config/kubewarden/sources.yaml+`
* Mac : `$HOME/Bibliothèque/Application Support/io.kubewarden.kubewarden/sources.yaml`
* Fenêtres : `+$HOME\AppData\Roaming\kubewarden\config\sources.yaml+`

Sa structure est la suivante :

[subs="+attributes",yaml]
----
insecure_sources:
  - "registry-dev.example.com"
  - "registry-dev2.example.com:5500"
source_authorities:
  "registry-pre.example.com":
    - type: Path
      path: /opt/example.com/pki/ca-pre1-1.pem
    - type: Path
      path: /opt/example.com/pki/ca-pre1-2.der
  "registry-pre2.example.com:5500":
    - type: Data
      data: |
            -----BEGIN CERTIFICATE-----
            ca-pre2 PEM cert
            -----END CERTIFICATE-----
----

Ce fichier est au format YAML ou JSON. Toutes les clés sont facultatives, de sorte que le fichier suivant est un fichier `+sources.yaml+` valide :

[subs="+attributes",yaml]
----
insecure_sources: ["dev.registry.example.com"]
----

En l'état :

[subs="+attributes",json]
----
{
    "source_authorities": {
        "host.k3d.internal:5000": [
            {"type": "Data","data":"pem cert 1"},
            {"type": "Data","data":"pem cert 2"}
        ]
    }
}
----

=== Section des sources non sécurisées

Les hôtes figurant dans la section `+insecure_sources+` se comportent différemment de ceux qui ne figurent pas dans la liste.

* Les hôtes ne sont pas répertoriés, essayez :
 ** pour se connecter à l'aide de HTTPS, en vérifiant l'identité du serveur

+
Si la connexion échoue, l'opération s'arrête.* Hôtes répertoriés dans `+insecure_sources+`, essayez dans l'ordre : ** de vous connecter en HTTPS en vérifiant l'identité du serveur de ** vous connecter en HTTPS en ignorant la vérification de l'hôte ** de vous connecter en HTTP

+
L'opération s'arrête en cas d'échec.

[NOTE]
====

Il est généralement possible d'utiliser `+insecure_sources+` lors de l'utilisation de registres locaux ou de serveurs HTTP pour le développement. Il évite le fardeau de la gestion des certificats.
Il est clair qu'il ne s'agit pas d'une utilisation en production.

====


=== Section autorités sources

La section `+source_authorities+` contient des URI et des certificats d'autorité de certification. Il forme une chaîne de certificats pour cet URI. Il est utilisé pour vérifier l'identité des registres de l'OpenContainer Initiative (OCI) et des serveurs HTTPS.

Vous encodez ces certificats dans les formats Privacy Enhanced Mail (PEM) ou Distinguished Encoding Rule (DER). Pour spécifier les certificats au format DER, vous utilisez un chemin d'accès à un fichier contenant le certificat. Au format PEM, vous indiquez soit un chemin d'accès au fichier de certificat, soit une chaîne contenant le certificat proprement dit. Vous pouvez spécifier les deux à l'aide d'une clé `+type+`:

[subs="+attributes",yaml]
----
source_authorities:
  "registry-pre.example.com":
    - type: Path
      path: /opt/example.com/pki/ca-pre1-1.pem
    - type: Path
      path: /opt/example.com/pki/ca-pre1-2.der
    - type: Data
      data: |
            -----BEGIN CERTIFICATE-----
            A string with the ca-pre1-3 PEM cert
            -----END CERTIFICATE-----
  "registry-pre2.example.com:5500":
    - type: Path
      path: /opt/example.com/pki/ca-pre2-1.der
----

=== Section Proxies

La section `+proxies+` contient une configuration de proxy analogue aux variables d'environnement habituelles `+HTTP_PROXY+`, `+HTTPS_PROXY+`, `+NO_PROXY+` (et leurs équivalents en minuscules).

Cette configuration a la priorité sur la définition de ces variables d'environnement.

Voir sa xref:/howtos/proxy-configuration.adoc[page "Comment faire"] pour plus d'informations sur cette fonctionnalité.

Son format est le suivant :

[,yaml]
----
proxies:
  http_proxy: "http://proxy.corp:3128"
  https_proxy: "http://proxy.corp:3129"
  no_proxy: "localhost,.corp"
----