include::partial$variables.adoc[]
= Chemin de mise à niveau
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Mettez à jour votre pile {project-name} en utilisant les stratégies de versionnement prises en charge et les règles de compatibilité entre ses composants.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["operator-manual", "upgrade-path"].
:doc-type: ["reference"]
:keywords: ["upgrade path", "support"]
:sidebar_label: Chemin de mise à niveau
:sidebar_position: 20
:current-version: {page-origin-branch}

== {project-name} version de la pile

Le projet {short-project-name} utilise https://semver.org/[Semantic versioning] pour définir la version "stack" de tous ses composants : la version suit le modèle`+MAJOR.MINOR.PATCH+`. La version prise en charge est la plus récente.

Les composants du site {short-project-name} qui suivent les règles de la version "stack" sont les suivants :

* `+kubewarden-crds+` dans leur champ appVersion.

* `+kubewarden-controller+` dans leur champ appVersion.

* `+kubewarden-defaults+` dans leur champ appVersion.

* `+policy-server+` pour les images déployées manuellement. La ressource par défaut est déjà gérée par la carte `+kubewarden-defaults+`.

* `+kwctl+` binaire.

== Compatibilité des versions des piles entre les composants

Les graphiques `+kubewarden-crds+`, `+kubewarden-controller+`,`+kubewarden-defaults+`, toute image `+policy-server+` déployée manuellement et`+kwctl+` doivent utiliser la même version de `+MAJOR+`.`+MINOR+`.`+PATCH+`.

Par conséquent, si la version de `+kubewarden-controller+` utilisée est `+1.1.2+`, les versions``+policy-server++s`` et +`kwctl`+ utilisées doivent être`+1.1.2` également.

== Versions du tableau de bord

Les cartes de barre définissent le champ `+version+` et le champ `+appVersion+`. Le champ`+appVersion+` indique la version de la "pile" {short-project-name}, comme indiqué précédemment. Le champ `+version+` suit également https://semver.org/[semantic versioning] et décrit les changements rétrocompatibles dans les modèles de graphiques et `+values.yaml+`.

== Voies de mise à niveau

Lors de la mise à niveau des composants, vous pouvez mettre à niveau plusieurs versions de la pile `+PATCH+` en une seule opération. Cependant, la mise à niveau de plusieurs versions de la pile `+MAJOR+` ou `+MINOR+` en une seule mise à niveau n'est *pas* prise en charge.

Par exemple, vous pouvez mettre à niveau des composants de la version `+1.1.10+` à `+1.1.nn+` en une seule fois. Mais la mise à jour de `+1.1.10+` à `+1.5.0+` n'est pas prise en charge. Dans ce cas, vous devez effectuer une mise à niveau individuelle pour chaque version de `+MAJOR+`/`+MINOR+` entre les deux versions. Par conséquent, il est nécessaire de mettre à niveau `+1.1.10+` vers`+1.2.0+` puis `+1.3.0+` puis `+1.4.0+` et enfin `+1.5.0+`. Pour passer d'une version`+MAJOR+` à une autre, vous devez appliquer toutes les mises à jour de `+MINOR+` entre les deux versions `+MAJOR+`.

.Exemple de graphe de support de chemin de mise à niveau
[mermaid]
....
%%{init: "theme": "neutral"}%% organigramme LR ; accTitle : Graphique de support du chemin de mise à niveau accDescr : Un diagramme montrant les chemins de mise à niveau recommandés et pris en charge pour {short-project-name}.
  1.0.0(1.0.0)-->1.0.1(1.0.1) ; 1.0.1-->1.0.2(1.0.2) ; 1.0.2-->1.1.0(1.1.0) ; 1.1.0-->1.1.2(1.1.2) ; 1.1.0-->1.1.1 ; 1.1.1-->1.1.2 ; 1.1.2-->|Non recommandé|1.2.0(1.2.0) ; 1.0.2-->|Non pris en charge|1.2.0(1.2.0) ; 1.1.2-->1.2.1(1.2.1) ; 1.2.0-->1.2.1 ; linkStyle 6 color:brown,stroke-width:2px,stroke-dasharray : 3 5
  linkStyle 7 color:red,stroke-width:2px,stroke-dasharray: 3 5
....

== Commande de mise à niveau

{short-project-name} les utilisateurs doivent mettre à jour la pile en commençant par la carte `+kubewarden-crds+`, puis la carte `+kubewarden-controller+`. Ensuite, mettez à jour les fichiers`+policy-server+` (via le graphique `+kubewarden-defaults+` ou les images des fichiers personnalisés) et `+kwctl+`.

== Dégradations

Les rétrogradations *ne* sont *pas* prises en charge et {short-project-name} ne les teste pas. Néanmoins, on peut raisonnablement s'attendre à ce qu'ils fonctionnent.

== SDK, politiques

Les SDK de politiques pour les différentes langues et politiques gérées par l'équipe{short-project-name} suivent leur propre version sémantique. {short-project-name} prend en charge la dernière version. Il n'est pas nécessaire de prévoir un chemin de mise à niveau pour eux, il suffit de passer à la dernière version.

Les changements apportés à la pile {short-project-name} peuvent signifier que les politiques et les SDK sont mis à jour pour utiliser les dernières fonctionnalités de {short-project-name}. {short-project-name} prend soin d'effectuer ces mises à jour d'une manière rétrocompatible.

Par exemple, une version mineure de {short-project-name} ajoutant la prise en charge du scanner d'audit (`+v1.7.0+`) signifie que les politiques ont gagné un nouveau champ `+spec.backgroundAudit+`. Il s'agit d'un élément facultatif, rétrocompatible et fixé par défaut à `+true+`.
