include::partial$variables.adoc[]
:description: Configurer les formats de configuration de la vérification pour la signature sécurisée des images de conteneurs à l'aide d'un serveur de règles ou d'une règle pour vérifier la provenance et les signatures.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "verification-config"].
:doc-type: ["reference"]
:doctype: book
:keywords: ["kubewarden", "kubernetes", "verification configuration"].
:current-version: {page-origin-branch}

= Format de configuration de la vérification
:revdate: 2026-03-18
:page-revdate: {revdate}

== Introduction

Vous pouvez utiliser le format `+verification-config+` avec :

* `+policy-server+` vérifier la provenance des modules de politique
* `+verify-image-signatures+` politique de vérification de la provenance des images de la grappe

Se référer à la xref:/howtos/security-hardening/secure-supply-chain.adoc[chaîne d'approvisionnement sécurisée] pour plus d'informations.

== Format

La configuration comporte 2 clés racine :

* `+allOf+`: Vous devez satisfaire à toutes les informations de vérification énumérées ici pour vérifier que les images des conteneurs sont bien signées.
* `+anyOf+`: Vous devez satisfaire au moins `+anyOf.minimumMatches+` de toutes les informations de vérification énumérées pour accepter une image de conteneur comme étant signée.

Ces deux clés racines acceptent un tableau de clés de type `+kind+`. Vous trouverez ci-dessous une liste complète des clés acceptées en fonction des différents cas d'utilisation :

* `+pubKey+`: Pour les signatures réalisées avec la cryptographie traditionnelle à clé publique/privée.
* `+githubAction+`: Pour les signatures effectuées avec le flux de travail sans clé de Sigstore dans les actions GitHub, {short-project-name} vérifie ces informations par rapport à l'extension de certificat x509 `+workflow_repository+` créée par l'OpenID Connect de GitHub, et pas seulement par rapport aux certificats `+issuer+` et `+subject+`. Vous devriez utiliser cette adresse `+kind+`si vous avez affaire à des actions GitHub.
* `+genericIssuer+`: Pour les signatures réalisées avec le flux de travail sans clé de Sigstore, où l'utilisateur doit valider lui-même le certificat `+issuer+` et `+subject+`. Il accepte une adresse `+subject+`, qui peut être :

** `+equal+`: La valeur transmise ici doit correspondre exactement à `+subject+` dans le certificat de signature.
** `+urlPrefix+`: La valeur transmise ici est postfixée par `+/+` pour éviter les fautes de frappe, et doit être un préfixe de `+subject+` dans le certificat de signature.

La clé `+kind+` accepte une clé `+annotations+` facultative, avec une liste de valeurs de clé, qui doit être présente dans la signature.

== Exemple

Voici un exemple de configuration pour la vérification des signatures à l'aide du flux de travail Sigstore :

[subs="+attributes",yaml]
----
---
apiVersion: v1

allOf:
  - kind: githubAction
    owner: kubewarden   # mandatory
    repo: policy-server # optional
    annotations:  # optional
      env: prod

anyOf: # at least `+anyOf.minimumMatches+` are required to match
  minimumMatches: 2 # default is 1
  signatures:
  - kind: pubKey
    owner: alice # optional
    key: | # mandatory
         -----BEGIN PUBLIC KEY-----
         MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQiTy5S+2JFvVlhUwWPLziM7iTM2j
         byLgh2IjpNQN0Uio/9pZOTP/CsJmXoUNshfpTUHd3OxgHgz/6adtf2nBwQ==
         -----END PUBLIC KEY-----
    annotations:  # optional
      env: prod
  - kind: genericIssuer
    issuer: https://github.com/login/oauth
    subject:
      equal: alice@example.com
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      equal: https://github.com/bob/app-example/.github/workflows/release.yml@refs/heads/main
    annotations:  # optional
      env: prod
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/bob # <- it will be post-fixed with `+/+` for security reasons
----

== Référence de la configuration de la signature

Vous pouvez valider les exigences de signature contenues dans un fichier. Étendre pour un exemple :

.Un dossier sur les exigences en matière de signature
[%collapsible]
====
[subs="+attributes",yaml]
----
apiVersion: v1

allOf:
  - kind: githubAction
    owner: kubewarden   # mandatory
    annotations:
      env: prod

anyOf: # at least `+anyOf.minimumMatches+` are required to match
  minimumMatches: 2 # default is 1
  signatures:
  - kind: pubKey
    owner: flavio # optional
    key: .... # mandatory
    annotations:  # optional
      env: prod
      foo: bar
  - kind: pubKey
    owner: victor # optional
    key: .... # mandatory
  - kind: genericIssuer
    issuer: https://github.com/login/oauth
    subject:
      equal: alice@example.com
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      equal: https://github.com/flavio/policy-secure-pod-images/.github/workflows/release.yml@refs/heads/main
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/flavio/
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/kubewarden # <- it will be post-fixed with `+/+` for security reasons
  - kind: githubAction
    owner: flavio   # mandatory
    repo: policy1 # optional
  - kind: pubKey
    owner: alice # optional
    key: .... # mandatory
----
====


=== Validation de la signature

La configuration précédente contient les deux sections `+allOf+` et `+anyOf+`:

* `+allOf+`: Vous n'accordez votre confiance à la police que si toutes les conditions de signature sont remplies.
* `+anyOf+`: Vous faites confiance à la police si le critère `+minimumMatches+` est valide.

Dans l'exemple, le champ `+minimumMatches+` est 2. Vous devez donc satisfaire à au moins deux des exigences en matière de signature. La valeur par défaut du champ `+minimumMatches+`est `+1+`.

Pour la validation de la signature, vous devez satisfaire à toutes les exigences relatives à la signature énoncées à l'adresse `+allOf+` *et* au nombre minimum énoncé à l'adresse `+anyOf+`.

=== Validation de la clé publique

Pour vérifier qu'une politique comporte la bonne signature de clé publique, vous devez spécifier les données de la clé et le propriétaire de la clé. Dans cet exemple, `+kind+` est associé à `+pubKey+` et `+key+` possède la clé publique. Le champ "propriétaire" est facultatif, mais il peut être utile pour préciser à qui appartient la clé.

[subs="+attributes",yaml]
----
  - kind: pubKey
    owner: bob # optional
    key: |
      -----BEGIN PUBLIC KEY-----
      MBFKHFDGHKIJH0CAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbDE6HJSGAVD
      BVDF6SKFSF87AASUspkQsN3FO4iyWodCy5j3o0CdIJD/KJHDJFHDFIu6sA==
      -----END PUBLIC KEY-----
----

=== Validation de la signature sans clé

Une politique signée en mode sans clé n'a pas de clé publique que vous pouvez vérifier. Vous pouvez toujours vérifier la politique à l'aide des données OpenID Connect (OIDC) utilisées lors du processus de signature. Pour cela, il est nécessaire de définir la validation de la signature comme`+genericIssuer+`.

Il est possible de vérifier les informations contenues dans la signature :

* `+issuer+`(obligatoire) : correspond à l'attribut `+Issuer+` du certificat généré par Fulcio. Il s'agit de l'OIDC utilisé pour signer la politique.
* `+subject+`champ utilisé pour correspondre à l'attribut `+Subject+` du certificat de Fulcio. Le champ `+Subject+` (Fulcio) contient l'utilisateur utilisé pour s'authentifier auprès du fournisseur OIDC. Le champ de vérification, `+subject+`, peut avoir deux sous-champs :

** `+equal+`Le certificat doit être signé par un tiers : le `+Subject+` (Fulcio) du certificat doit être égal à la valeur de la validation de la signature ;
** `+urlPrefix+`Le champ `+Subject+` (Fulcio) du certificat doit être préfixé par la valeur définie dans la validation de la signature.

[NOTE]
====

Les sites `+cosign verify+` et `+kwctl inspect+` peuvent tous deux afficher des informations sur les signatures sans clé.

====


Par exemple, cette configuration signifie que la politique doit avoir une signature sans clé d'Alice utilisant l'OIDC de GitHub :

[subs="+attributes",yaml]
----
- kind: genericIssuer
  issuer: https://github.com/login/oauth
  subject:
    equal: alice@example.com
----

Cette configuration a besoin de la politique signée dans les actions GitHub, à partir d'un dépôt appartenant à l'utilisateur GitHub `+flavio+`:

[subs="+attributes",yaml]
----
- kind: genericIssuer
  issuer: https://token.actions.githubusercontent.com
  subject:
    urlPrefix: https://github.com/flavio
----

=== Actions GitHub vérification de la signature

Le "type", `+githubAction+`, permet de valider les politiques signées dans les actions GitHub.
Vous pouvez également le faire avec le type `+genericIssuer+`. Pour simplifier le processus de demande de signature, utilisez deux champs supplémentaires pour `+githubAction+`:

* `+owner+` (obligatoire) : ID GitHub de l'utilisateur ou de l'organisation à qui faire confiance.
* `+repo+`: Le nom du référentiel auquel il faut faire confiance.

Par exemple, le dernier extrait, utilisant `+genericIssuer+`, pourrait être réécrit comme suit :

[subs="+attributes",yaml]
----
- kind: githubAction
  owner: flavio
----

=== Validation des annotations de signature

Tous les types de signature peuvent comporter d'autres champs de validation facultatifs, `+annotations+`.
Ces champs sont des données clé/valeur ajoutées au cours du processus de signature.

Avec {short-project-name}, vous pouvez vérifier que les signatures de politiques proviennent d'utilisateurs de confiance *et qu'*elles comportent des annotations spécifiques.

La validation suivante vérifie deux conditions pour la politique :

* qu'il est signé avec une clé spécifique
* il a une annotation d'environnement de production.

[subs="+attributes",yaml]
----
- kind: pubKey
  key: |
    -----BEGIN PUBLIC KEY-----
    MBFKHFDGHKIJH0CAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbDE6HJSGAVD
    BVDF6SKFSF87AASUspkQsN3FO4iyWodCy5j3o0CdIJD/KJHDJFHDFIu6sA==
    -----END PUBLIC KEY-----
  annotations:
    environment: production
----

=== Utilisation d'un fichier de configuration de vérification de signature pour vérifier un artefact OCI de politique

Le fichier de configuration de la vérification permet de vérifier si une politique a passé le cap de la vérification. Utilisez l'option `+--verification-config-path+` de la commande `kwctl verify.` 

[subs="+attributes",console]
----
$ cat signatures_requirements.yaml
apiVersion: v1
allOf:
  - kind: pubKey
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5Q+cN1Jj2S7N05J4AXnqwP2DyzSg
      Mc+raYce2Wthrd30MSgFtoh5ADAkCd/nML2Nx8UD9KBuASRb0gG5jXqgMQ==
      -----END PUBLIC KEY-----

$ kwctl verify --verification-config-path signatures_requirements.yaml ghcr.io/kubewarden/policies/user-group-psp:latest
2022-03-29T17:34:37.847169Z  INFO kwctl::verify: Policy successfully verified
----

Ce dernier exemple permet de vérifier si une politique donnée provient de l'organisation {short-project-name}:

[subs="+attributes",console]
----
$ cat kubewarden_signatures.yaml
apiVersion: v1
allOf:
  - kind: githubAction
    owner: kubewarden

$ kwctl verify --verification-config-path kubewarden_signatures.yaml ghcr.io/kubewarden/policies/user-group-psp:latest
2022-03-29T18:07:39.062292Z  INFO kwctl::verify: Policy successfully verified
----
