= Identificadores
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

Los identificadores se utilizan en SUSE Observability para identificar objetos, como elementos de topología (componentes y relaciones) y funciones. Esta página describe los diferentes tipos de identificadores utilizados para los elementos de topología y cómo se estructuran los identificadores de ámbito global en SUSE Observability.

== Identificadores de topología

Los elementos de topología utilizan dos tipos de identificadores en SUSE Observability:

* *Identificadores del ámbito de integración*: se utilizan para identificar componentes y relaciones dentro de una integración. Cada componente o relación sólo tiene un identificador de ámbito de integración. El identificador es arbitrario, pero debe ser coherente dentro del ámbito de la propia integración.
* *Identificadores de ámbito global*: se utilizan para fusionar componentes entre integraciones, por ejemplo ServiceNow y el agente de SUSE Observability. Cada componente puede tener varios identificadores de ámbito global, mientras que las relaciones no tienen identificadores globales. Son asignados por SUSE Observability y formateados de acuerdo con la xref:/configure/topology/identifiers.adoc#_global_scope_identifiers[convención de identificadores globales de SUSE Observability].

El siguiente ejemplo de código muestra un componente con ambos tipos de identificadores.

* Identificador del ámbito de integración - `this-host-unique-identifier`
* Identificador de ámbito global - `urn:host:/this-host-fqdn`


[,text]
----
self.component("this-host-unique-identifier", "Host", {
    "name": "this-host",
    "domain": "Webshop",
    "layer": "Machines",
    "identifiers": ["urn:host:/this-host-fqdn"],
    "labels": ["host:this-host", "region:eu-west-1"],
    "environment": "Production"
})
----


== Identificadores del Agente de SUSE Observability

Los identificadores de ámbito global utilizados por el Agente de SUSE Observability para identificar elementos de topología sincronizados se enumeran en la siguiente tabla.

|===
| Tipo de recurso | Formato del identificador URN

| Anfitrión
| `urn:host:/[hostName]`

| Proceso
| `urn:process:/[hostName]:[pid]:[createTime]`

| Contenedor
| `urn:container:/[hostName]:[containerId]`

| Servicio descubierto con rastros
| `urn:service:/[serviceName]`

| Instancia de servicio descubierta con trazas
| `urn:service-instance:/[serviceName]:/[hostName]`
|===

Consulte el xref:/configure/topology/identifiers.adoc#_stackstate_agent[ejemplo de identificadores de ámbito global URN del Agente de SUSE Observability].

== Identificadores de ámbito mundial

Cuando SUSE Observability recibe componentes con identificadores de ámbito global coincidentes de diferentes fuentes externas, los componentes y sus propiedades (etiquetas, flujos, comprobaciones) se fusionan en un único componente. Esto permite combinar datos de distintas fuentes en una imagen única del panorama informático.

Los identificadores de ámbito global en SUSE Observability son un URN único global que se ajusta a la siguiente convención:

[,text]
----
urn:<prefix>:<type-name>:<free-form>
----

Tenga en cuenta que no todos los caracteres están permitidos en un identificador URN. Puede comprobar sus identificadores con la siguiente regex URN:

[,text]
----
^urn:[a-z0-9][a-z0-9-]{0,31}:[a-z0-9()+,\-.:=@;$_!*'%/?#]+$
----

A continuación se describe el formato de los segmentos `<prefix>` y `<type-name>:<free-form>`.

=== Prefijo

El segmento `prefix` es una parte obligatoria de un identificador global. Nombra el ámbito al que pertenece el identificador y se utiliza únicamente con fines organizativos.

[NOTE]
====
Cuando el prefijo incluye un nombre de StackPack, el objeto estará bajo el control de ese StackPack. Esto significa que el objeto se desinstalará cuando se desinstale el StackPack.
====


Los prefijos URN reconocidos son:

* `stackpack:<name>` - pertenecientes a StackPacks.
* `stackpack:<name>:shared` - compartidos entre instancias de un StackPack.
* `stackpack:<name>:instance:{{instanceId}}`- pertenecientes a una instancia específica de un StackPack, donde `{{instanceId}}` es un manejador que devuelve el ID proporcionado durante el proceso de instalación del StackPack para cada instancia específica del StackPack.
* `system:auto` - objetos creados por el sistema que no pertenecen a ningún StackPack específico.

=== Tipo-nombre y forma libre

El identificador se identifica unívocamente mediante los segmentos `<type-name>:<free-form>`.

* `<type-name>` coincide con el tipo de objeto de dominio del objeto al que se asigna el identificador (no distingue mayúsculas de minúsculas).
* `<free-form>` es arbitraria, pero debe ser única para el tipo. El formato del segmento de forma libre lo decide el usuario. No es necesario que coincida con el nombre del objeto (si existe) y puede estar formado por varios segmentos.

== Ejemplos de identificadores

=== Pila común

Ejemplo de identificadores de ámbito global URN del StackPack común. Los objetos se desinstalarán cuando se desinstale el StackPack común.

* Componente tipo servidor:
 ** `urn:stackpack:common:component-type:server`

=== Agente de observabilidad de SUSE

Ejemplo de identificadores de ámbito global URN del Agente de SUSE Observability.

* Anfitrión:
 ** `urn:host:/example.org`
* Proceso:
 ** `urn:process:/db.infra.company.org:161841:1602158335000`
* Contenedor:
 ** `urn:container:/compnode5.k8s.example.org:8b18c68a820904c55b4909d7f5a9a52756d45e866c07c92bf478bcf6cd240901`
* Servicio descubierto con rastros:
 ** `urn:service:/prod-db`
* Instancia de servicio descubierta con trazas:
 ** `urn:service-instance:/prod-db:/main.example.org`

=== Otros StackPacks

Ejemplo de identificadores de ámbito global URN de varios StackPacks. Los objetos se desinstalarán cuando se desinstale el StackPack nombrado.

* Función de comprobación del estado de ejecución de eventos de AWS compartido entre instancias de AWS StackPack:
 ** `urn:stackpack:aws:shared:check-function:aws-event-run-state`
* Componente tipo cmdb_ci_netgear en el StackPack de ServiceNow:
 ** `urn:stackpack:servicenow:componenttype:cmdb_ci_netgear`
