= .NETアプリケーション
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 自動計装

.NET の自動インスツルメンテーションは、さまざまなhttps://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/internal/instrumentation-libraries.md[ライブラリとフレームワークの]トレースとメトリクスを自動的にキャプチャできます。

自動計測は、アプリケーションを変更する必要はない。設定方法は以下の通り：

. opentelemetry-dotnet-instrumentationリポジトリのhttps://github.com/open-telemetry/opentelemetry-java-instrumentation/releases[Releasesから]、https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/latest/download/opentelemetry-dotnet-instrumentation-linux-glibc.zip[glibc]またはhttps://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/latest/download/opentelemetry-dotnet-instrumentation-linux-musl.zip[musl]バージョンの計測ライブラリ（Alpineではmusl、その他のほとんどのdockerイメージではglibc）をダウンロードしてください。ファイルを解凍し、アプリケーションの docker イメージのディレクトリに含めます。ここでは`+/autoinstrumentation+` を使用します。
. 以下のenvバーを設定する。ここでは、Kubernetes pod specのコンテナの`+env+` ：
+
[,yaml]
----
env:
- name: CORECLR_ENABLE_PROFILING
  value: "1"
- name: CORECLR_PROFILER
  value: "{918728DD-259F-4A6A-AC2B-B85E1B658318}"
- name: CORECLR_PROFILER_PATH
  # for glibc:
  value: "/autoinstrumentation/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so"
  # For musl use instead:
  # value: "/autoinstrumentation/linux-musl-x64/OpenTelemetry.AutoInstrumentation.Native.so"
- name: DOTNET_ADDITIONAL_DEPS
  value: "/autoinstrumentation/AdditionalDeps"
- name: DOTNET_SHARED_STORE
  value: "/autoinstrumentation/store"
- name: DOTNET_STARTUP_HOOKS
  value: "/autoinstrumentation/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll"
- name: OTEL_DOTNET_AUTO_HOME
  value: "/autoinstrumentation"
----

. また、追加の環境変数をxref:/setup/otel/languages/sdk-exporter-config.adoc[追加して、]ポッド上のxref:/setup/otel/languages/sdk-exporter-config.adoc[サービス名とエクスポータ・エンドポイントを設定]します。
. 変更したアプリケーションをデプロイする
. SUSE Observabilityがトレースやメトリクスを受信していることをxref:/setup/otel/languages/verify.adoc[確認します]。

詳細については、https://opentelemetry.io/docs/languages/java/automatic/[Open Telemetry のドキュメントを]参照してください。

== 手動計装

手動インストルメンテーションは、自動インストルメンテーションではサポートされていないコード部分からのメトリクス、トレース、またはログが必要な場合に使用できます。例えば、サポートされていないライブラリ、社内コード、ビジネスレベルのメトリクスなどだ。

そのデータを取得するには、アプリケーションを修正する必要がある。

. 依存関係として Open Telemetry SDK を含める
. アプリケーションにコードを追加して、必要に応じてメトリクス、スパン、ログをキャプチャします。

これについては、https://opentelemetry.io/docs/languages/net/instrumentation/[Open Telemetry .NET SDK doc pagesに]詳細なドキュメントがあります。

OTLPエクスポータ（これがデフォルト）とhttps://opentelemetry.io/docs/languages/java/instrumentation/#_autoconfiguration[自動コンフィギュレーションを]使用していることを確認してください。アプリケーションをデプロイする際、サービス名とエクスポーターはxref:/setup/otel/languages/sdk-exporter-config.adoc[環境変数によって設定される]。

== SUSE Observabilityのメトリクス

ifdef::ss-ff-stackpacks2_enabled[]
一部の.NETメトリクス、たとえばガベージコレクタメトリクスについては、SUSE Observabilityが関連コンポーネントのチャートを定義しています。Kubernetesの場合、チャートはポッド上で利用できる。xref:/setup/custom-integrations/metric-bindings/index.adoc[より多くのメトリクスにチャートを追加]することが可能で、これは自動計測によるメトリクスだけでなく、手動計測によるアプリケーション固有のメトリクスでも機能します。
endif::[]


ifndef::ss-ff-stackpacks2_enabled[]
一部の.NETメトリクス、たとえばガベージコレクタメトリクスについては、SUSE Observabilityが関連コンポーネントのチャートを定義しています。Kubernetesの場合、チャートはポッド上で利用できる。xref:/use/metrics/k8s-add-charts.adoc[より多くのメトリクスにチャートを追加]することが可能で、これは自動計測によるメトリクスだけでなく、手動計測によるアプリケーション固有のメトリクスでも機能します。
endif::[]

