= Node.jsアプリケーションのインスツルメンテーション
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 自動計装

Node.jsの自動インスツルメンテーションは、自動インスツルメンテーションJavascriptライブラリをアプリケーションに含めることによって行われます。幅広いhttps://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node#_supported_instrumentations[ライブラリとフレームワークがサポートされている]。

自動計測は、アプリケーションを変更する必要はない。設定方法は以下の通り：

. Open Telemetry instrumentation SDK をアプリケーションに追加します：
+
[,bash]
----
npm install --save @opentelemetry/api
npm install --save @opentelemetry/auto-instrumentations-node
----

. docker イメージのエントリポイントまたはコマンドを更新するか、アプリケーションの Kubernetes マニフェスト内の`+command+` を更新して、SDK をロードするようにアプリケーションを起動するコマンドを更新します。`+--require @opentelemetry/auto-instrumentations-node/register+` を追加する：
+
[,bash]
----
node --require @opentelemetry/auto-instrumentations-node/register app.js
----

. xref:/setup/otel/languages/sdk-exporter-config.adoc[サービス名とエクスポータ・エンドポイントを設定するための]環境変数を追加して、アプリケーションをデプロイしてください。
. SUSE Observabilityがトレースやメトリクスを受信していることをxref:/setup/otel/languages/verify.adoc[確認します]。

詳細については、https://opentelemetry.io/docs/languages/js/automatic/[Open Telemetry のドキュメントを]参照してください。

[CAUTION]
====
このhttps://github.com/open-telemetry/opentelemetry-js/issues/4551[Open Telemetry の問題が]解決されるまで、環境変数で設定された自動計測はトレースのみをサポートします。自動計測によるメトリクスを有効にするには、コードの変更が必要である。https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[Open Telemetry ドキュメントの]指示に従って変更してください。
====


== 手動計装

手動インストルメンテーションは、自動インストルメンテーションではサポートされていないコード部分からのメトリクス、トレース、またはログが必要な場合に使用できます。例えば、サポートされていないライブラリ、社内コード、ビジネスレベルのメトリクスなどだ。

そのデータを取得するには、アプリケーションを修正する必要がある。

. 依存関係として Open Telemetry SDK を含める
. アプリケーションにコードを追加して、必要に応じてメトリクス、スパン、ログをキャプチャします。

これについては、https://opentelemetry.io/docs/languages/js/instrumentation/[Open Telemetry Javascript SDK doc pagesに]詳細なドキュメントがあります。

OTLPエクスポータを使用し、コードからエクスポータのエンドポイントを正しく設定していることを確認してください。https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[Open Telemetry のドキュメントも]参照してください。エキスポーターをxref:/setup/otel/collector.adoc[ドキュメント]通りにセットアップしたと仮定すると、設定する必要があるエンドポイントは`+http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317+` で、gRPCを使用します。gRPCに問題がある場合は、xref:/setup/otel/languages/sdk-exporter-config.adoc#_grpc_vs_http[gRPC vs HTTPも]参照のこと。
