= Resolución de problemas de los monitores
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

* <<_the_result_of_the_monitor_isnt_showing_on_a_component,El resultado del monitor no se muestra en un componente>>
* <<_the_monitor_is_showing_an_error_in_the_monitor_status_overview,El monitor muestra un error en el resumen de estado del monitor>>

=== El resultado del monitor no se muestra en un componente

En primer lugar, compruebe si el monitor xref:use/alerting/k8s-add-monitors-cli.adoc#_verify_the_execution_of_the_monitor[produce resultados]. Si este es el caso, pero los resultados del monitor no aparecen en los componentes, puede que haya un problema con la unión. Primero utilice el siguiente comando para verificarlo:

[,bash]
----
sts monitor status --id <id>
----

Si la salida tiene `Monitor health states with identifier which has no matching topology element (<nr>): ....`, esto muestra que el `urnTemplate` puede no generar un identificador que coincida con la topología. Para remediarlo, xref:use/alerting/k8s-add-monitors-cli.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[revise su urnTemplate].

=== El monitor muestra un error en el resumen de estado del monitor

Obtener el estado del monitor a través de la CLI

[,bash]
----
sts monitor status --id <id>
----

La sección `Monitor Stream errors:` mostrará los errores que se producen en el monitor y ofrecerá más ayuda.

