= Activar copias de seguridad
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

[NOTE]
====
Esta página se aplica a {stackstate-product-name} v2.7.0 o posterior.
====

== Visión general

{stackstate-product-name} cuenta con un mecanismo de copia de seguridad integrado que puede configurarse para almacenar copias de seguridad en AWS S3, Azure Blob Storage o un volumen persistente de Kubernetes.

La mayoría de las copias de seguridad se activan con un único valor de Helm `+global.backup.enabled+`. Las copias de seguridad de la configuración siempre están activadas, pero se comportan de forma diferente en función de los siguientes valores:

=== Alcance de la copia de seguridad

Se pueden realizar copias de seguridad automáticas de los siguientes datos:

* *Ajustes* (StackPacks, monitores, vistas, tokens) - siempre activados:
** Cuando `+global.backup.enabled+` es `+true+`: las copias de seguridad se almacenan a través de MinIO en su backend de almacenamiento configurado.
** Cuando `+global.backup.enabled+` es `+false+`: las copias de seguridad se almacenan en un volumen persistente dedicado de Kubernetes, evitando MinIO.
* *Datos de topología y ajustes* almacenados en StackGraph - activado cuando `+global.backup.enabled+` es `+true+`
* *Métricas* almacenadas en {stackstate-product-name}'s Victoria Metrics instance(s) - activado cuando `+global.backup.enabled+` es `+true+`
* *Los datos de telemetría* almacenados en {stackstate-product-name}'s Elasticsearch instancia - habilitado cuando `+global.backup.enabled+` es `+true+`
* *Los datos de OpenTelemetry* almacenados en {stackstate-product-name}'s ClickHouse instancia - habilitado cuando `+global.backup.enabled+` es `+true+`

=== Opciones de almacenamiento

Las copias de seguridad utilizan https://min.io/[MinIO (min.io)] como pasarela compatible con S3 para su backend de almacenamiento. MinIO es desplegado automáticamente por el gráfico Helm cuando se activan las copias de seguridad.

La instancia MinIO incorporada puede configurarse para almacenar las copias de seguridad en tres ubicaciones:

* xref:/setup/data-management/backup_restore/backup_enable.adoc[AWS S3]
* xref:/setup/data-management/backup_restore/backup_enable.adoc[Almacenamiento Azure Blob]
* xref:/setup/data-management/backup_restore/backup_enable.adoc[Kubernetes storage]

== Activar copias de seguridad

=== AWS S3

[CAUTION]
====

*Cifrado*

Las claves gestionadas por Amazon S3 (SSE-S3) deben utilizarse al cifrar los buckets de S3 que almacenan las copias de seguridad.

⚠️ No se admite el cifrado con claves de AWS KMS almacenadas en AWS Key Management Service (SSE-KMS). Esto dará lugar a errores como éste en los registros de Elasticsearch:

`+Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: sdk_client_exception: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: ZX4D/ZDUzZWRhNDUyZTI1MTc= in base 64) didn't match hash (etag: c75faa31280154027542f6530c9e543e in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@5481a656, bucketName: suse-observability-elasticsearch-backup, key: tests-UG34QIV9s32tTzQWdPsZL/master.dat)\",+`
====


==== Uso de buckets S3 independientes

Para habilitar las copias de seguridad programadas en cubos AWS S3 separados (uno por datastore), añada el siguiente fragmento YAML al archivo Helm `+values.yaml+` utilizado para instalar {stackstate-product-name}:

[,yaml]
----
global:
  backup:
    enabled: true
backup:
  stackGraph:
    bucketName: AWS_STACKGRAPH_BUCKET
  elasticsearch:
    bucketName: AWS_ELASTICSEARCH_BUCKET
  configuration:
    bucketName: AWS_CONFIGURATION_BUCKET
victoria-metrics-0:
  backup:
    bucketName: AWS_VICTORIA_METRICS_BUCKET
victoria-metrics-1:
  backup:
    bucketName: AWS_VICTORIA_METRICS_BUCKET
clickhouse:
  backup:
    bucketName: AWS_CLICKHOUSE_BUCKET
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  s3gateway:
    enabled: true
    accessKey: AWS_ACCESS_KEY
    secretKey: AWS_SECRET_KEY
----

Sustituya los siguientes valores:

* `+YOUR_ACCESS_KEY+` y `+YOUR_SECRET_KEY+` son las credenciales que se utilizarán para asegurar el sistema MinIO. Estas credenciales se establecen en el sistema MinIO y son utilizadas por los trabajos de copia de seguridad automática y los trabajos de restauración. También son necesarios si quieres acceder manualmente al sistema MinIO.
 ** YOUR_ACCESS_KEY debe contener entre 5 y 20 caracteres alfanuméricos.
 ** YOUR_SECRET_KEY debe contener entre 8 y 40 caracteres alfanuméricos.
* `+AWS_ACCESS_KEY+` y `+AWS_SECRET_KEY+` son las credenciales de AWS para el usuario IAM que tiene acceso a los buckets de S3 donde se almacenarán las copias de seguridad. Consulte a continuación la política de permisos que debe adjuntarse a ese usuario.
* `+AWS_*_BUCKET+` son los nombres de los buckets de S3 donde deben almacenarse las copias de seguridad.
+
[Note]
====
Los nombres de los buckets de AWS S3 son globales en todo AWS. Por lo tanto, los buckets S3, con el nombre por defecto (`+sts-elasticsearch-backup+`, `+sts-configuration-backup+`, `+sts-stackgraph-backup+`, `+sts-victoria-metrics-backup+` y `+sts-clickhouse-backup+` ), probablemente no estarán disponibles.
====

==== Uso de un único bucket de S3 con prefijos

En lugar de utilizar buckets independientes para cada datastore, puede utilizar un único bucket de S3 con diferentes prefijos:

[,yaml]
----
global:
  backup:
    enabled: true
backup:
  elasticsearch:
    bucketName: BUCKET
    s3Prefix: elasticsearch
  stackGraph:
    bucketName: BUCKET
    s3Prefix: stackgraph
  configuration:
    bucketName: BUCKET
    s3Prefix: configuration
victoria-metrics-0:
  backup:
    bucketName: BUCKET
    s3Prefix: victoria-metrics-0
victoria-metrics-1:
  backup:
    bucketName: BUCKET
    s3Prefix: victoria-metrics-1
clickhouse:
  backup:
    bucketName: BUCKET
    s3Prefix: clickhouse
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  s3gateway:
    enabled: true
    accessKey: AWS_ACCESS_KEY
    secretKey: AWS_SECRET_KEY
----

Sustituya `+BUCKET+` por el nombre de su bucket de S3. Las copias de seguridad de los distintos almacenes de datos se organizan utilizando los valores configurados en `+s3Prefix+`. Aquí se aplican los mismos valores `+YOUR_ACCESS_KEY+`, `+YOUR_SECRET_KEY+`, `+AWS_ACCESS_KEY+`, y `+AWS_SECRET_KEY+` de la sección anterior.

=== Permisos de AWS S3

El usuario de IAM identificado por `+AWS_ACCESS_KEY+` y `+AWS_SECRET_KEY+` debe configurarse con la siguiente política de permisos para acceder a los buckets de S3:

[,javascript]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowListMinioBackupBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::AWS_STACKGRAPH_BUCKET",
                "arn:aws:s3:::AWS_ELASTICSEARCH_BUCKET",
                "arn:aws:s3:::AWS_VICTORIA_METRICS_BUCKET",
                "arn:aws:s3:::AWS_CLICKHOUSE_BUCKET",
                "arn:aws:s3:::AWS_CONFIGURATION_BUCKET"
            ]
        },
        {
            "Sid": "AllowWriteMinioBackupBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::AWS_STACKGRAPH_BUCKET/*",
                "arn:aws:s3:::AWS_ELASTICSEARCH_BUCKET/*",
                "arn:aws:s3:::AWS_VICTORIA_METRICS_BUCKET/*",
                "arn:aws:s3:::AWS_CLICKHOUSE_BUCKET/*",
                "arn:aws:s3:::AWS_CONFIGURATION_BUCKET"
            ]
        }
    ]
}
----

=== Almacenamiento Azure Blob

==== Utilizar recipientes separados

Para habilitar las copias de seguridad en contenedores Azure Blob Storage separados (uno por almacén de datos), añada el siguiente fragmento YAML al archivo Helm `+values.yaml+` utilizado para instalar {stackstate-product-name}:

[,yaml]
----
global:
  backup:
    enabled: true
minio:
  accessKey: AZURE_STORAGE_ACCOUNT_NAME
  secretKey: AZURE_STORAGE_ACCOUNT_KEY
  azuregateway:
    enabled: true
----

Sustituya los siguientes valores:

* `+AZURE_STORAGE_ACCOUNT_NAME+` - el https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal[nombre de la cuenta de almacenamiento Azure]
* `+AZURE_STORAGE_ACCOUNT_KEY+` - la https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal[clave de la cuenta de almacenamiento Azure] donde deben almacenarse las copias de seguridad.

Las copias de seguridad de StackGraph, Elasticsearch, Victoria Metrics y ClickHouse se almacenan en contenedores BLOB denominados `+sts-stackgraph-backup+`, `+sts-configuration-backup+`, `+sts-elasticsearch-backup+`, `+sts-victoria-metrics-backup+`, `+sts-clickhouse-backup+` respectivamente. Estos nombres pueden cambiarse configurando los valores de Helm `+backup.stackGraph.bucketName+`, `+backup.elasticsearch.bucketName+`, `+victoria-metrics-0.backup.bucketName+`, `+victoria-metrics-1.backup.bucketName+` y `+clickhouse.backup.bucketName+` respectivamente.

==== Utilización de un único contenedor con prefijos

En lugar de utilizar contenedores independientes para cada almacén de datos, puede utilizar un único contenedor Azure Blob Storage con diferentes prefijos:

[,yaml]
----
global:
  backup:
    enabled: true
backup:
  elasticsearch:
    bucketName: CONTAINER
    s3Prefix: elasticsearch
  stackGraph:
    bucketName: CONTAINER
    s3Prefix: stackgraph
  configuration:
    bucketName: CONTAINER
    s3Prefix: configuration
victoria-metrics-0:
  backup:
    bucketName: CONTAINER
    s3Prefix: victoria-metrics-0
victoria-metrics-1:
  backup:
    bucketName: CONTAINER
    s3Prefix: victoria-metrics-1
clickhouse:
  backup:
    bucketName: CONTAINER
    s3Prefix: clickhouse
minio:
  accessKey: AZURE_STORAGE_ACCOUNT_NAME
  secretKey: AZURE_STORAGE_ACCOUNT_KEY
  azuregateway:
    enabled: true
----

Sustituya `+CONTAINER+` por el nombre de su contenedor Azure Blob Storage. Las copias de seguridad de los distintos almacenes de datos se organizarán utilizando los valores configurados en `+s3Prefix+`. Aquí se aplican los mismos valores de `+AZURE_STORAGE_ACCOUNT_NAME+` y `+AZURE_STORAGE_ACCOUNT_KEY+` del apartado anterior.

=== Volumen persistente de Kubernetes

[CAUTION]
====
El uso de Kubernetes Persistent Volumes para copias de seguridad tiene limitaciones significativas:

* Caro: los proveedores de nube suelen utilizar almacenamiento en bloque (EBS/Azure Block), que es costoso para copias de seguridad de gran tamaño.
* No hay recuperación ante desastres: los PV se destruyen si se elimina el clúster.
* No portable - No se pueden restaurar las copias de seguridad en un cluster diferente

**Recomendación:** Utilice AWS S3 o Azure Blob Storage para los entornos de producción.
====

==== Configuración básica

Para habilitar las copias de seguridad en el almacenamiento local del clúster, habilite MinIO añadiendo el siguiente fragmento YAML al archivo Helm `+values.yaml+` utilizado para instalar {stackstate-product-name}:

[,yaml]
----
global:
  backup:
    enabled: true
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  persistence:
    enabled: true
----

Sustituya los siguientes valores:

* `+YOUR_ACCESS_KEY+` y `+YOUR_SECRET_KEY+` - las credenciales que se utilizarán para asegurar el sistema MinIO. Los trabajos de copia de seguridad automática y los trabajos de restauración los utilizarán. También son necesarios para acceder manualmente al almacenamiento MinIO. `+YOUR_ACCESS_KEY+` debe contener entre 5 y 20 caracteres alfanuméricos y `+YOUR_SECRET_KEY+` entre 8 y 40 caracteres alfanuméricos.

== Datos de configuración y topología (StackGraph)

Las copias de seguridad de los datos de configuración y topología (StackGraph) son copias de seguridad completas, almacenadas en un único archivo con la extensión `+.graph+`. Cada archivo contiene una copia de seguridad completa y puede moverse, copiarse o borrarse según sea necesario.

=== Programa de copias de seguridad

Por defecto, las copias de seguridad de StackGraph se crean diariamente a las 03:00 AM hora del servidor.

La programación de la copia de seguridad puede configurarse utilizando el valor de Helm `+backup.stackGraph.scheduled.schedule+`, especificado en https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#_cron_schedule_syntax[Kubernetes cron schedule syntax (kubernetes.io)].

=== Conservación de copias de seguridad

Por defecto, las copias de seguridad de StackGraph se conservan durante 30 días. Como las copias de seguridad de StackGraph son copias de seguridad completas, esto puede requerir mucho almacenamiento.

El delta de retención de copias de seguridad puede configurarse utilizando el valor de Helm `+backup.stackGraph.scheduled.backupRetentionTimeDelta+`, especificado en el formato de fecha GNU `+--date+` argumento. Por defecto es `+30 days ago+`. Consulte https://www.gnu.org/software/coreutils/manual/html_node/Relative-items-in-date-strings.html[Elementos relativos en cadenas de fechas] para ver más ejemplos.

=== Desactivar las copias de seguridad programadas

Para desactivar las copias de seguridad programadas de StackGraph, establezca la programación de la copia de seguridad en una fecha lejana en el pasado utilizando el valor de Helm `+backup.stackGraph.scheduled.schedule+`:

[,yaml]
----
backup:
  stackGraph:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Ajustes

Settings (Configuración previamente) incluye instancias instaladas de StackPacks con su configuración y otras personalizaciones creadas por el usuario, como monitores, vistas personalizadas y tokens de servicio.

Las copias de seguridad de la configuración son ligeras (normalmente sólo varios megabytes) y rápidas de restaurar, con un tiempo de inactividad mínimo. Tras restaurar una copia de seguridad de la configuración, los nuevos datos se procesarán como antes, recreando la topología, los estados de salud y las alertas. Sin embargo, el historial de topología (incluida la salud) no se conserva en las copias de seguridad de la configuración; para ello, utilice la copia de seguridad de StackGraph descrita anteriormente.

[NOTE]
====
*Las copias de seguridad de la configuración siempre están activadas*, independientemente del valor de `+global.backup.enabled+`:

* Cuando `+global.backup.enabled+` es `+true+`: Las copias de seguridad de la configuración se almacenan a través de MinIO en el backend de almacenamiento configurado (AWS S3, Azure Blob Storage o Kubernetes Persistent Volume).
* Cuando `+global.backup.enabled+` es `+false+`: Las copias de seguridad de la configuración se almacenan en un volumen persistente dedicado de Kubernetes, evitando MinIO.
====

=== Programa de copias de seguridad

Por defecto, las copias de seguridad de la configuración se crean diariamente a las 04:00 AM hora del servidor.

La programación de la copia de seguridad puede configurarse utilizando el valor de Helm `+backup.configuration.scheduled.schedule+`, especificado en https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#_cron_schedule_syntax[Kubernetes cron schedule syntax (kubernetes.io)].

=== Conservación de copias de seguridad

La conservación de las copias de seguridad depende de la configuración de `+global.backup.enabled+`:

**Cuando `+global.backup.enabled+` es `+true+`** (copias de seguridad almacenadas a través de MinIO):

* Por defecto, las copias de seguridad de la configuración se conservan durante 365 días
* Configurar la retención utilizando `+backup.configuration.scheduled.backupRetentionTimeDelta+` - especificado en el formato de la fecha GNU `+--date+` argumento. El valor por defecto es `+365 days ago+`

**Cuando `+global.backup.enabled+` es `+false+`** (copias de seguridad almacenadas en PV dedicado):

* Por defecto, los 10 últimos archivos de copia de seguridad se guardan en el Volumen persistente
* Configure el número máximo de archivos utilizando `+backup.configuration.maxLocalFiles+` (por defecto: `+10+`)
* Configure el tamaño de PV utilizando `+backup.configuration.scheduled.pvc.size+` (por defecto: `+1Gi+`)

Ejemplo de configuración para almacenamiento fotovoltaico dedicado:

[,yaml]
----
backup:
  configuration:
    maxLocalFiles: 10
    scheduled:
      pvc:
        size: '1Gi'
----

=== Desactivar las copias de seguridad programadas

Para desactivar las copias de seguridad programadas de la configuración, establezca la programación de la copia de seguridad en una fecha lejana en el pasado utilizando el valor de Helm `+backup.configuration.scheduled.schedule+`:

[,yaml]
----
backup:
  configuration:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Métricas (Victoria Metrics)

Victoria Metrics crea copias de seguridad tomando una instantánea de los datos métricos actuales y almacenando sólo los cambios desde la última copia de seguridad (enfoque incremental).

[WARNING]
====
*Limitación de las versiones de las copias de seguridad*

Las copias de seguridad de Victoria Metrics sustituyen a la copia de seguridad anterior cada vez que se ejecuta una nueva copia de seguridad. Esto significa que sólo tienes acceso a *la copia de seguridad más reciente*, no a un historial de múltiples versiones de copias de seguridad.

**Importante**: Si una copia de seguridad falla o los datos se corrompen, es posible que se pierdan los datos de la copia de seguridad anterior. Sólo se puede restaurar la última copia de seguridad realizada correctamente.

**Excepción**: Si el volumen de almacenamiento de Victoria Metrics se vacía o se reinicia (por ejemplo, el directorio `+/storage+` se monta vacío o se elimina), el sistema lo detectará y creará automáticamente una nueva serie de copias de seguridad. En este caso, tanto la copia de seguridad antigua (antes del reinicio) como la nueva se conservarán y estarán disponibles para su restauración.
====

[NOTE]
====
*Implantaciones de alta disponibilidad*

Los despliegues de alta disponibilidad utilizan dos instancias de Victoria Metrics (`+victoria-metrics-0+` y `+victoria-metrics-1+`). Las copias de seguridad se configuran independientemente para cada instancia.
====

=== Programa de copias de seguridad

Las copias de seguridad de Victoria Metrics se crean cada 1h:

* `+victoria-metrics-0+` - 25 minutos después de la hora
* `+victoria-metrics-1+` - 35 minutos después de la hora

=== Desactivar las copias de seguridad programadas

Para desactivar las copias de seguridad programadas de Victoria Metrics, establezca la programación de copias de seguridad para ambas instancias en una fecha muy lejana en el tiempo:

[,yaml]
----
victoria-metrics-0:
  backup:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
victoria-metrics-1:
  backup:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== OpenTelemetry (ClickHouse)

ClickHouse utiliza copias de seguridad incrementales y completas. Las copias de seguridad antiguas se eliminan en función de la política de retención configurada.

=== Programa de copias de seguridad

Se crean las copias de seguridad de ClickHouse:

* Copia de seguridad completa - a las 00:45 todos los días
* Copia de seguridad incremental - 45 minutos después de la hora (de 3 a 12 de la madrugada)

=== Conservación de copias de seguridad

Por defecto, la herramienta guarda las últimas 308 copias de seguridad (completas e incrementales), lo que equivale a unos 14 días.

La retención de copias de seguridad puede configurarse utilizando el valor de Helm `+clickhouse.backup.config.keep_remote+`.

=== Desactivar las copias de seguridad programadas

Para desactivar las copias de seguridad programadas de ClickHouse, establezca la programación de las copias de seguridad completas e incrementales en una fecha muy lejana en el tiempo:

[,yaml]
----
clickhouse:
  backup:
    scheduled:
      full_schedule: '0 0 1 1 1970'         # January 1, 1970 (epoch start)
      incremental_schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Datos de telemetría (Elasticsearch)

Las instantáneas de Elasticsearch son incrementales.

=== Calendario instantáneo

Las instantáneas de Elasticsearch se crean diariamente a las 03:00 AM hora del servidor.

=== Retención de instantáneas

Por defecto, las instantáneas de Elasticsearch se mantienen durante 30 días, con un mínimo de 5 instantáneas y un máximo de 30 instantáneas.

El tiempo de retención y el número de instantáneas conservadas pueden configurarse utilizando los siguientes valores de Helm:

* `+backup.elasticsearch.scheduled.snapshotRetentionExpireAfter+`, especificado en https://www.elastic.co/guide/en/elasticsearch/reference/7.6/common-options.html#_time_units[unidades de tiempo de Elasticsearch (elastic.co)].
* `+backup.elasticsearch.scheduled.snapshotRetentionMinCount+`
* `+backup.elasticsearch.scheduled.snapshotRetentionMaxCount+`

=== Desactivar las instantáneas programadas

Para desactivar las instantáneas programadas de Elasticsearch, establezca la programación de la instantánea en una fecha lejana en el pasado utilizando el valor de Helm `+backup.elasticsearch.scheduled.schedule+`:

[,yaml]
----
backup:
  elasticsearch:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----
