= Copia de seguridad de Kubernetes (Legacy)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

[WARNING]
====
*Esta página describe el enfoque de copia de seguridad heredado mediante scripts. Para {stackstate-product-name} v2.7.0 o posterior, utilice la nueva xref:/setup/data-management/backup_restore/backup_enable.adoc[CLI de copia de seguridad].*

**Cambios de última hora en v2.7.0:**

* `+backup.enabled+` se sustituye por `+global.backup.enabled+` - Los despliegues de Helm fallarán si `+backup.enabled+` se establece en `+true+`
* Todas las copias de seguridad se controlan con un único valor `+global.backup.enabled+` en lugar de habilitarlas por almacén de datos.
* `+*.restore.enabled+` se han eliminado los valores
====

== Visión general

{stackstate-product-name} cuenta con un mecanismo integrado de copia de seguridad y restauración que puede configurarse para almacenar las copias de seguridad en los clústeres locales, en AWS S3 o en Azure Blob Storage.

=== Alcance de la copia de seguridad

Se pueden realizar copias de seguridad automáticas de los siguientes datos:

* *Datos de configuración y topología* almacenados en StackGraph
* *Métricas* almacenadas en la(s) instancia(s) de Victoria Metrics de SUSE Observability
* *Datos de telemetría* almacenados en la instancia Elasticsearch de SUSE Observability
* *Datos de OpenTelemetry* almacenados en la instancia ClickHouse de SUSE Observability

*No* se realizará copia de seguridad de los siguientes datos:

* Actualizaciones de topología y telemetría en tránsito almacenadas en Kafka: sólo tienen valor temporal y no servirían de nada cuando se restaurase una copia de seguridad.
* Estado de las negociaciones del nodo maestro almacenado en ZooKeeper - este estado en tiempo de ejecución sería incorrecto al restaurarlo y se determinará automáticamente en tiempo de ejecución
* Estado de configuración de Kubernetes y estado de volumen persistente sin procesar: este estado se puede reconstruir volviendo a instalar SUSE Observability y restaurando las copias de seguridad.
* Registros de Kubernetes: son efímeros.

=== Opciones de almacenamiento

Las copias de seguridad se envían a una instancia de https://min.io/[MinIO (min.io)], que es iniciada automáticamente por el gráfico `+suse-observability+` Helm cuando se habilitan las copias de seguridad automáticas. MinIO es un sistema de almacenamiento de objetos con la misma API que AWS S3. Puede almacenar sus datos localmente o actuar como puerta de enlace a https://docs.min.io/docs/minio-gateway-for-s3.html[S3 (] AWS https://docs.min.io/docs/minio-gateway-for-azure.html[min.io] y otros sistemas.

La instancia MinIO incorporada puede configurarse para almacenar las copias de seguridad en tres ubicaciones:

* xref:/setup/data-management/backup_restore/kubernetes_backup.adoc[AWS S3]
* xref:/setup/data-management/backup_restore/kubernetes_backup.adoc[Almacenamiento Azure Blob]
* xref:/setup/data-management/backup_restore/kubernetes_backup.adoc[Kubernetes storage]

== Activar copias de seguridad

=== AWS S3

[CAUTION]
====

*Cifrado*

Las claves gestionadas por Amazon S3 (SSE-S3) deben utilizarse al cifrar los buckets de S3 que almacenan las copias de seguridad.

⚠️ No se admite el cifrado con claves de AWS KMS almacenadas en AWS Key Management Service (SSE-KMS). Esto dará lugar a errores como éste en los registros de Elasticsearch:

`+Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: sdk_client_exception: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: ZX4D/ZDUzZWRhNDUyZTI1MTc= in base 64) didn't match hash (etag: c75faa31280154027542f6530c9e543e in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@5481a656, bucketName: suse-observability-elasticsearch-backup, key: tests-UG34QIV9s32tTzQWdPsZL/master.dat)",+`
====


Para habilitar las copias de seguridad programadas en los buckets S3 de AWS, añada el siguiente fragmento YAML al archivo Helm `+values.yaml+` utilizado para instalar SUSE Observability:

[,yaml]
----
global:
  backup:
    enabled: true
backup:
  stackGraph:
    bucketName: AWS_STACKGRAPH_BUCKET
  elasticsearch:
    bucketName: AWS_ELASTICSEARCH_BUCKET
  configuration:
    bucketName: AWS_CONFIGURATION_BUCKET
victoria-metrics-0:
  backup:
    bucketName: AWS_VICTORIA_METRICS_BUCKET
victoria-metrics-1:
  backup:
    bucketName: AWS_VICTORIA_METRICS_BUCKET
clickhouse:
  backup:
    bucketName: AWS_CLICKHOUSE_BUCKET
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  s3gateway:
    enabled: true
    accessKey: AWS_ACCESS_KEY
    secretKey: AWS_SECRET_KEY
----

Sustituya los siguientes valores:

* `+YOUR_ACCESS_KEY+` y `+YOUR_SECRET_KEY+` son las credenciales que se utilizarán para asegurar el sistema MinIO. Estas credenciales se establecen en el sistema MinIO y son utilizadas por los trabajos de copia de seguridad automática y los trabajos de restauración. También son necesarios si quieres acceder manualmente al sistema MinIO.
 ** YOUR_ACCESS_KEY debe contener entre 5 y 20 caracteres alfanuméricos.
 ** YOUR_SECRET_KEY debe contener entre 8 y 40 caracteres alfanuméricos.
* `+AWS_ACCESS_KEY+` y `+AWS_SECRET_KEY+` son las credenciales de AWS para el usuario IAM que tiene acceso a los buckets de S3 donde se almacenarán las copias de seguridad. Consulte a continuación la política de permisos que debe adjuntarse a ese usuario.
* `+AWS_STACKGRAPH_BUCKET+`, `+AWS_CONFIGURATION_BUCKET+`, `+AWS_ELASTICSEARCH_BUCKET+`, `+AWS_VICTORIA_METRICS_BUCKET+` y `+AWS_CLICKHOUSE_BUCKET+` son los nombres de los buckets de S3 donde deben almacenarse las copias de seguridad. Nota: Los nombres de los buckets S3 de AWS son globales en todo AWS, por lo que los buckets S3 con el nombre por defecto (`+sts-elasticsearch-backup+`, `+sts-configuration-backup+`, `+sts-stackgraph-backup+`, `+sts-victoria-metrics-backup+` y `+sts-clickhouse-backup+` ) probablemente no estarán disponibles.

El usuario de IAM identificado por `+AWS_ACCESS_KEY+` y `+AWS_SECRET_KEY+` debe configurarse con la siguiente política de permisos para acceder a los buckets de S3:

[,javascript]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowListMinioBackupBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::AWS_STACKGRAPH_BUCKET",
                "arn:aws:s3:::AWS_ELASTICSEARCH_BUCKET",
                "arn:aws:s3:::AWS_VICTORIA_METRICS_BUCKET",
                "arn:aws:s3:::AWS_CLICKHOUSE_BUCKET",
                "arn:aws:s3:::AWS_CONFIGURATION_BUCKET"
            ]
        },
        {
            "Sid": "AllowWriteMinioBackupBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::AWS_STACKGRAPH_BUCKET/*",
                "arn:aws:s3:::AWS_ELASTICSEARCH_BUCKET/*",
                "arn:aws:s3:::AWS_VICTORIA_METRICS_BUCKET/*",
                "arn:aws:s3:::AWS_CLICKHOUSE_BUCKET/*",
                "arn:aws:s3:::AWS_CONFIGURATION_BUCKET"
            ]
        }
    ]
}
----

=== Almacenamiento Azure Blob

Para habilitar las copias de seguridad en una cuenta Azure Blob Storage, añada el siguiente fragmento YAML al archivo Helm `+values.yaml+` utilizado para instalar SUSE Observability:

[,yaml]
----
global:
  backup:
    enabled: true
minio:
  accessKey: AZURE_STORAGE_ACCOUNT_NAME
  secretKey: AZURE_STORAGE_ACCOUNT_KEY
  azuregateway:
    enabled: true
----

Sustituya los siguientes valores:

* `+AZURE_STORAGE_ACCOUNT_NAME+` - el https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal[nombre de la cuenta de almacenamiento Azure]
* `+AZURE_STORAGE_ACCOUNT_KEY+` - la https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal[clave de la cuenta de almacenamiento Azure] donde deben almacenarse las copias de seguridad.

Las copias de seguridad de StackGraph, Elasticsearch y Victoria Metrics se almacenan en contenedores BLOB llamados `+sts-stackgraph-backup+`, `+sts-configuration-backup+`, `+sts-elasticsearch-backup+`, `+sts-victoria-metrics-backup+`, `+sts-clickhouse-backup+` respectivamente. Estos nombres pueden cambiarse configurando los valores de Helm `+backup.stackGraph.bucketName+`, `+backup.elasticsearch.bucketName+`, `+victoria-metrics-0.backup.bucketName+`, `+victoria-metrics-1.backup.bucketName+` y `+clickhouse.backup.bucketName+` respectivamente.

=== Kubernetes storage

[CAUTION]
====
Si MinIO está configurado para almacenar sus datos en el almacenamiento de Kubernetes, se utiliza un PersistentVolumeClaim (PVC) para solicitar almacenamiento del clúster de Kubernetes. El tipo de almacenamiento asignado depende de la configuración del clúster.

Se recomienda utilizar AWS S3 para los clústeres que se ejecutan en Amazon AWS y Azure Blob Storage para los clústeres que se ejecutan en Azure por los siguientes motivos:

. Los clústeres de Kubernetes que se ejecutan en un proveedor de nube suelen asignar PVC al almacenamiento en bloque, como Elastic Block Storage para AWS o Azure Block Storage. El almacenamiento en bloques es caro, sobre todo para grandes volúmenes de datos.
. Los Volúmenes Persistentes se destruyen cuando se destruye el cluster que los creó. Esto significa que una eliminación (accidental) de su clúster también destruirá todas las copias de seguridad almacenadas en Volúmenes Persistentes.
. No se puede acceder a los Volúmenes Persistentes desde otro cluster. Esto significa que no es posible restaurar SUSE Observability a partir de una copia de seguridad realizada en otro clúster.
====


Para habilitar las copias de seguridad en el almacenamiento local del clúster, habilite MinIO añadiendo el siguiente fragmento YAML al archivo Helm `+values.yaml+` utilizado para instalar SUSE Observability:

[,yaml]
----
global:
  backup:
    enabled: true
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  persistence:
    enabled: true
----

Sustituya los siguientes valores:

* `+YOUR_ACCESS_KEY+` y `+YOUR_SECRET_KEY+` - las credenciales que se utilizarán para asegurar el sistema MinIO. Los trabajos de copia de seguridad automática y los trabajos de restauración los utilizarán. También son necesarios para acceder manualmente al almacenamiento MinIO. `+YOUR_ACCESS_KEY+` debe contener entre 5 y 20 caracteres alfanuméricos y `+YOUR_SECRET_KEY+` entre 8 y 40 caracteres alfanuméricos.

== Datos de configuración y topología (StackGraph)

Las copias de seguridad de los datos de configuración y topología (StackGraph) son copias de seguridad completas, almacenadas en un único archivo con la extensión `+.graph+`. Cada archivo contiene una copia de seguridad completa y puede moverse, copiarse o borrarse según sea necesario.

=== Programa de copias de seguridad

Por defecto, las copias de seguridad de StackGraph se crean diariamente a las 03:00 AM hora del servidor.

La programación de la copia de seguridad puede configurarse utilizando el valor de Helm `+backup.stackGraph.scheduled.schedule+`, especificado en https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#_cron_schedule_syntax[Kubernetes cron schedule syntax (kubernetes.io)].

=== Conservación de copias de seguridad

Por defecto, las copias de seguridad de StackGraph se conservan durante 30 días. Como las copias de seguridad de StackGraph son copias de seguridad completas, esto puede requerir mucho almacenamiento.

El delta de retención de copias de seguridad puede configurarse utilizando el valor de Helm `+backup.stackGraph.scheduled.backupRetentionTimeDelta+`, especificado en el formato de fecha GNU `+--date+` argumento. Por ejemplo, el valor por defecto es `+30 days ago+`. Consulte https://www.gnu.org/software/coreutils/manual/html_node/Relative-items-in-date-strings.html[Elementos relativos en cadenas de fechas] para ver más ejemplos.

=== Desactivar las copias de seguridad programadas

Para desactivar las copias de seguridad programadas de StackGraph, establezca la programación de la copia de seguridad en una fecha lejana en el pasado utilizando el valor de Helm `+backup.stackGraph.scheduled.schedule+`:

[,yaml]
----
backup:
  stackGraph:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Métricas (Victoria Metrics)

[WARNING]
====
Victoria Metrics utiliza copias de seguridad incrementales sin versionado de un bucket, esto significa que la nueva copia de seguridad *sustituye completamente a la anterior*.

En caso de que te encuentres en una de las siguientes situaciones:

* montar un volumen vacío en el directorio `+/storage+` de las instancias de Victoria Metrics
* eliminar el directorio `+/storage+` o los archivos que contiene de las instancias de Victoria Metrics

La siguiente copia de seguridad (vacía) creada se etiquetará con una nueva versión y la anterior, anterior al vaciado del volumen, se conservará.
A partir de ese momento, ambas copias de seguridad <<_list_victoria_metrics_backups,aparecerán como disponibles para su restauración>>.
====


Las métricas (Victoria Metrics) utilizan instantáneas para almacenar datos en copias de seguridad incrementales. Muchas instancias de Victoria Metrics pueden almacenar copias de seguridad en el mismo bucket, cada una de ellas se almacenará en directorios separados. Todos los archivos ubicados en el directorio deben tratarse como un todo único y sólo pueden moverse, copiarse o borrarse como un todo.

[NOTE]
====
Los despliegues de alta disponibilidad deben desplegarse con dos instancias de Victoria Metrics. Las copias de seguridad se activan/configuran independientemente para cada una de ellas.

Los siguientes fragmentos de código/comandos se proporcionan para la primera instancia de Victoria Metric `+victoria-metrics-0+`. Para hacer una copia de seguridad/configurar la segunda instancia debe utilizar `+victoria-metrics-1+`
====


=== Programa de copias de seguridad

Por defecto, las copias de seguridad de Victoria Metrics se crean cada 1h:

* `+victoria-metrics-0+` - 25 minutos después de la hora
* `+victoria-metrics-1+` - 35 minutos después de la hora

El calendario de copias de seguridad puede configurarse utilizando el valor de Helm `+victoria-metrics-0.backup.scheduled.schedule+` según https://github.com/aptible/supercronic/tree/master/cronexpr[el formato]

=== Desactivar las copias de seguridad programadas

Para desactivar las copias de seguridad programadas de Victoria Metrics, establezca la programación de copias de seguridad para ambas instancias en una fecha muy lejana en el tiempo:

[,yaml]
----
victoria-metrics-0:
  backup:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
victoria-metrics-1:
  backup:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== OpenTelemetry (ClickHouse)

ClickHouse utiliza copias de seguridad incrementales y completas. Por defecto, las copias de seguridad completas se ejecutan diariamente a las 00:45 horas, y las incrementales, cada hora. Cada copia de seguridad crea un nuevo directorio y las copias de seguridad antiguas (directorios) se eliminan automáticamente. Todos los archivos ubicados en un directorio de copia de seguridad se tratan como un grupo singular y sólo se pueden mover, copiar o eliminar como un grupo. Se recomienda utilizar la herramienta `+clickhouse-backup+` disponible en `+suse-observability-clickhouse-shard0-0+` Pod para gestionar las copias de seguridad.

=== Programa de copias de seguridad

Por defecto, se crean las copias de seguridad de ClickHouse:

* Copia de seguridad completa - a las 00:45 todos los días
* Copia de seguridad incremental - 45 minutos después de la hora (de 3 a 12 de la madrugada)

[CAUTION]
====
Las copias de seguridad luchan con la ejecución paralela. Si se inicia una segunda copia de seguridad antes de que finalice la primera, interrumpirá la primera. Por lo tanto, es crucial evitar la ejecución paralela. Por ejemplo, la primera copia de seguridad incremental debería ejecutarse tres horas después de la completa.
====


El calendario de copias de seguridad puede configurarse utilizando el valor Helm `+clickhouse.backup.scheduled.full_schedule+` y `+clickhouse.backup.scheduled.incremental_schedule+` según https://github.com/aptible/supercronic/tree/master/cronexpr[el formato]

=== Conservación de copias de seguridad

Por defecto, la herramienta guarda las últimas 308 copias de seguridad (completas e incrementales), lo que equivale a unos 14 días.

La retención de copias de seguridad puede configurarse utilizando el valor de Helm `+clickhouse.backup.config.keep_remote+`.

=== Desactivar las copias de seguridad programadas

Para desactivar las copias de seguridad programadas de ClickHouse, establezca la programación de las copias de seguridad completas e incrementales en una fecha muy lejana en el tiempo:

[,yaml]
----
clickhouse:
  backup:
    scheduled:
      full_schedule: '0 0 1 1 1970'         # January 1, 1970 (epoch start)
      incremental_schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Datos de telemetría (Elasticsearch)

Las instantáneas de los datos de telemetría (Elasticsearch) son incrementales y se almacenan en archivos con la extensión `+.dat+`. Los archivos de la ubicación de almacenamiento de la copia de seguridad de Elasticsearch deben tratarse como un todo único y sólo pueden moverse, copiarse o eliminarse como un todo.

Los fragmentos de configuración proporcionados en la sección xref:/setup/data-management/backup_restore/kubernetes_backup.adoc#_enable_backups[habilitar copias de seguridad] habilitarán las instantáneas diarias de Elasticsearch.

=== Desactivar las instantáneas programadas

Para desactivar las instantáneas programadas de Elasticsearch, establezca la programación de la instantánea en una fecha lejana en el pasado utilizando el valor de Helm `+backup.elasticsearch.scheduled.schedule+`:

[,yaml]
----
backup:
  elasticsearch:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

=== Calendario instantáneo

Por defecto, las instantáneas de Elasticsearch se crean diariamente a las 03:00 AM hora del servidor.

La programación de la copia de seguridad puede configurarse utilizando el valor de Helm `+backup.elasticsearch.scheduled.schedule+`, especificado en https://www.elastic.co/guide/en/elasticsearch/reference/7.6/cron-expressions.html[Elasticsearch cron schedule syntax (elastic.co)].

=== Retención de instantáneas

Por defecto, las instantáneas de Elasticsearch se mantienen durante 30 días, con un mínimo de 5 instantáneas y un máximo de 30 instantáneas.

El tiempo de retención y el número de instantáneas conservadas pueden configurarse utilizando los siguientes valores de Helm:

* `+backup.elasticsearch.scheduled.snapshotRetentionExpireAfter+`, especificado en https://www.elastic.co/guide/en/elasticsearch/reference/7.6/common-options.html#_time_units[unidades de tiempo de Elasticsearch (elastic.co)].
* `+backup.elasticsearch.scheduled.snapshotRetentionMinCount+`
* `+backup.elasticsearch.scheduled.snapshotRetentionMaxCount+`

[NOTE]
====
Por defecto, la propia tarea de retención https://www.elastic.co/guide/en/elasticsearch/reference/7.6/slm-settings.html#_slm_retention_schedule[se ejecuta diariamente a la 1:30 AM UTC (elastic.co)]. Si establece que las instantáneas caduquen antes de un día, por ejemplo, para realizar pruebas, deberá cambiar la programación de la tarea de retención.
====


=== Índices instantáneos

Por defecto, se crea una instantánea para los índices de Elasticsearch cuyos nombres comienzan por `+sts+`.

Los índices para los que se crea una instantánea pueden configurarse utilizando el valor de Helm `+backup.elasticsearch.scheduled.indices+`, especificado en JSON https://www.w3schools.com/js/js_json_arrays.asp[formato de matriz].

== Restaurar copias de seguridad e instantáneas

Los scripts para listar y restaurar copias de seguridad e instantáneas pueden descargarse de la https://github.com/StackVista/helm-charts/releases/latest[última versión de]. Descargue y extraiga `+backup-scripts-<version>.tar.gz+` para empezar.

[NOTE]
====
*Antes de utilizar los guiones, asegúrese de que:*

* El binario `+kubectl+` está instalado y configurado para conectarse:
 .. El clúster Kubernetes donde se ha instalado SUSE Observability.
 .. El espacio de nombres dentro de ese clúster donde se ha instalado SUSE Observability.
* El valor de Helm `+global.backup.enabled+` se establece en `+true+`.
====


=== Lista de copias de seguridad de StackGraph

Para listar las copias de seguridad de StackGraph, ejecute el siguiente comando:

[,bash]
----
./restore/list-stackgraph-backups.sh
----

El resultado debería ser el siguiente:

[,bash]
----
job.batch/stackgraph-list-backups-20210222t111942 created
Waiting for job to start...
=== Listing StackGraph backups in bucket "sts-stackgraph-backup"...
sts-backup-20210215-0300.graph
sts-backup-20210216-0300.graph
sts-backup-20210217-0300.graph
sts-backup-20210218-0300.graph
sts-backup-20210219-0300.graph
sts-backup-20210220-0300.graph
sts-backup-20210221-0300.graph
sts-backup-20210222-0300.graph
===
job.batch "stackgraph-list-backups-20210222t111942" deleted
----

La fecha y hora en que se realizó la copia de seguridad forma parte del nombre de la copia.

[NOTE]
====
Se esperan líneas en la salida que empiecen por `+Error from server (BadRequest):+`. Aparecen cuando el script está esperando a que se inicie el pod.
====


=== Restaurar una copia de seguridad de StackGraph

[CAUTION]
====
*Para evitar la pérdida inesperada de datos existentes, una copia de seguridad sólo puede restaurarse en un entorno limpio por defecto.*
Si estás completamente seguro de que cualquier dato existente puede sobrescribirse, puedes anular esta función de seguridad utilizando el comando `+-force+`.
Ejecute el comando de restauración sólo cuando esté seguro de que desea restaurar la copia de seguridad.
====


Para restaurar una copia de seguridad de StackGraph en un entorno limpio, seleccione un nombre de copia de seguridad y páselo como primer parámetro en el siguiente comando:

[,bash]
----
./restore/restore-stackgraph-backup.sh sts-backup-20210216-0300.graph
----

Para restaurar una copia de seguridad de StackGraph en un *entorno con datos existentes*, seleccione un nombre de copia de seguridad y páselo como primer parámetro en el siguiente comando junto a un segundo parámetro `+-force+`:
[NOTE]
====
*Tenga en cuenta que los datos existentes se sobrescribirán cuando se restaure la copia de seguridad.*

Hágalo sólo si está completamente seguro de que los datos existentes pueden sobrescribirse.
====


[,bash]
----
./restore/restore-stackgraph-backup.sh sts-backup-20210216-0300.graph -force
----

El resultado debería ser el siguiente:

[,bash]
----
job.batch/stackgraph-restore-20210222t112142 created
Waiting for job to start...
=== Downloading StackGraph backup "sts-backup-20210216-0300.graph" from bucket "sts-stackgraph-backup"...
download: s3://sts-stackgraph-backup/sts-backup-20210216-1252.graph to ../../tmp/sts-backup-20210216-0300.graph
=== Importing StackGraph data from "sts-backup-20210216-0300.graph"...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/opt/docker/lib/org.codehaus.groovy.groovy-2.5.4.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
===
job.batch "stackgraph-restore-20210222t112142" deleted
----

Si ejecuta un comando de restauración sin el indicador `+-force+` en una base de datos no vacía, aparecerá un error como el siguiente:

[,bash]
----
ERROR com.stackvista.graph.migration.Restore - Restore isn't possible in a non empty.
----

[NOTE]
====
Se esperan líneas que empiecen por `+WARNING:+`. Son generados por Groovy corriendo en JDK 11 y pueden ser ignorados.
====


=== Lista de copias de seguridad de Victoria Metrics

Para listar las copias de seguridad de Victoria Metrics, ejecute el siguiente comando:

[,bash]
----
./restore/list-victoria-metrics-backups.sh
----

El resultado debería ser el siguiente:

[,bash]
----
job.batch/victoria-metrics-list-backups-20231016t125557 created
Waiting for job to start...
Waiting for job to start...
=== Fetching timestamps of last completed incremental backups
victoria-metrics-0 victoria-metrics-0-20231128160000 "Wed, 29 Nov 2023 07:36:00 GMT"
victoria-metrics-0 victoria-metrics-0-20231129092200 "Wed, 29 Nov 2023 10:56:00 GMT"

===
job.batch "victoria-metrics-list-backups-20231016t125557" deleted
----

donde puede ver la instancia de métricas de Victoria, la versión específica de la copia de seguridad y la última vez que se completó una copia de seguridad.

=== Restaurar una copia de seguridad de Victoria Metrics

[CAUTION]
====
*La función de restauración siempre prevalece sobre los datos. Debe tener cuidado para evitar la pérdida inesperada de los datos existentes.*
====


[CAUTION]
====
*La funcionalidad de restauración requiere detener una instancia de Victoria Metric durante el proceso.*

Todas las nuevas métricas serán almacenadas en caché por `+vmagent+` durante el proceso de restauración, por favor asegúrese de que `+vmagent+` tiene suficiente memoria para almacenar en caché las métricas.
====


Para restaurar una copia de seguridad de Victoria Metrics, seleccione un nombre de instancia y una versión de copia de seguridad y páselos como parámetros en el siguiente comando:

[,bash]
----
./restore/restore-victoria-metrics-backup.sh victoria-metrics-0 victoria-metrics-0-20231128160000
----

El resultado debería ser el siguiente:

[,bash]
----
=== Scaling down the Victoria Metrics instance
statefulset.apps/suse-observability-victoria-metrics-0 scaled
=== Allowing pods to terminate
=== Starting restore job
job.batch/victoria-metrics-restore-backup-20231017t092607 created
=== Restore job started. Follow the logs with the following command:
kubectl logs --follow job/victoria-metrics-restore-backup-20231017t092607
=== After the job has completed clean up the job and scale up the Victoria Metrics instance pods again with the following commands:
kubectl delete job victoria-metrics-restore-backup-20231017t092607
kubectl scale statefulsets suse-observability-victoria-metrics-0 --replicas=1
----

A continuación, siga los registros para comprobar el estado del trabajo

----
2023-10-17T07:26:42.564Z    info    VictoriaMetrics/lib/backup/actions/restore.go:194    restored 53072307269 bytes from backup in 0.445 seconds; deleted 639118752 bytes; downloaded 1204539 bytes
2023-10-17T07:26:42.564Z    info    VictoriaMetrics/app/vmrestore/main.go:64    gracefully shutting down http server for metrics at ":8421"
2023-10-17T07:26:42.564Z    info    VictoriaMetrics/app/vmrestore/main.go:68    successfully shut down http server for metrics in 0.000 seconds
----

Después de la finalización*(asegúrese de que la copia de seguridad se ha restaurado correctamente*), es necesario seguir los comandos impresos por el comando anterior:

* eliminar la tarea de restauración
* Ampliar la instancia de Victoria Metrics

=== Lista de copias de seguridad de ClickHouse

[NOTE]
====
El siguiente script necesita permiso para ejecutar el comando `+kubectl exec+`.
====


Para listar las copias de seguridad de ClickHouse, ejecute el siguiente comando:

[,bash]
----
./restore/list-clickhouse-backups.sh
----

El resultado debería ser el siguiente:

[,bash]
----
full_2024-06-17T18-50-00          34.41KiB   17/06/2024 18:50:00   remote                                      tar, regular
incremental_2024-06-17T18-51-00   7.29KiB    17/06/2024 18:51:00   remote   +full_2024-06-17T18-50-00          tar, regular
incremental_2024-06-17T18-54-00   7.29KiB    17/06/2024 18:54:00   remote   +incremental_2024-06-17T18-51-00   tar, regular
incremental_2024-06-17T18-57-00   7.29KiB    17/06/2024 18:57:00   remote   +incremental_2024-06-17T18-54-00   tar, regular
full_2024-06-17T19-00-00          26.41KiB   17/06/2024 19:00:00   remote                                      tar, regular
incremental_2024-06-17T19-00-00   6.52KiB    17/06/2024 19:00:00   remote   +incremental_2024-06-17T18-57-00   tar, regular
incremental_2024-06-17T19-03-00   25.37KiB   17/06/2024 19:03:00   remote   +incremental_2024-06-17T19-00-00   tar, regular
incremental_2024-06-17T19-06-00   7.29KiB    17/06/2024 19:06:00   remote   +incremental_2024-06-17T19-03-00   tar, regular
----

donde está impreso:

* nombre, el nombre comenzó con `+full_+` - se trata de una copia de seguridad completa, `+incremental_+` - se trata de una copia de seguridad incremental
* tamaño,
* fecha de creación,
* `+remote+` - una copia de seguridad se sube a un almacenamiento remoto como S3
* copia de seguridad principal: utilizada por las copias de seguridad incrementales
* formato y compresión

=== Restaurar una copia de seguridad de ClickHouse

[CAUTION]
====
*La función de restauración sobrescribe los datos. Todas las tablas de la base de datos `+otel+` se eliminan y se restauran a partir de la copia de seguridad. Tenga cuidado para evitar pérdidas de datos inesperadas.*
====


[NOTE]
====
El siguiente script necesita permiso para ejecutar el comando `+kubectl exec+`.
====


[CAUTION]
====
*Restaurar la funcionalidad requiere detener todos los productores (como los exportadores de OpenTelemetry). El script reduce las cargas de trabajo antes de la copia de seguridad y las aumenta una vez finalizada.*
====


Para restaurar una copia de seguridad de ClickHouse, seleccione una versión de la copia de seguridad y pásela como parámetro en el siguiente comando:

[,bash]
----
./restore/restore-clickhouse-backup.sh incremental_2024-06-17T18-57-00
----

El resultado debería ser el siguiente:

[,bash]
----
...
2024/06/17 19:14:19.509498  info download object_disks start backup=incremental_2024-06-17T19-06-00 operation=restore_data table=otel.otel_traces_trace_id_ts_mv
2024/06/17 19:14:19.509530  info download object_disks finish backup=incremental_2024-06-17T19-06-00 duration=0s operation=restore_data size=0B table=otel.otel_traces_trace_id_ts_mv
2024/06/17 19:14:19.509549  info done                      backup=incremental_2024-06-17T19-06-00 duration=0s operation=restore_data progress=12/12 table=otel.otel_traces_trace_id_ts_mv
2024/06/17 19:14:19.509574  info done                      backup=incremental_2024-06-17T19-06-00 duration=66ms operation=restore_data
2024/06/17 19:14:19.509591  info done                      backup=incremental_2024-06-17T19-06-00 duration=167ms operation=restore version=2.5.13
2024/06/17 19:14:19.509684  info clickhouse connection closed logger=clickhouse
Data restored
----

=== Lista de instantáneas de Elasticsearch

Para listar las instantáneas de Elasticsearch, ejecute el siguiente comando:

[,bash]
----
./restore/list-elasticsearch-snapshots.sh
----

El resultado debería ser el siguiente:

[,bash]
----
job.batch/elasticsearch-list-snapshots-20210224t133115 created
Waiting for job to start...
Waiting for job to start...
=== Listing Elasticsearch snapshots in snapshot repository "sts-backup" in bucket "sts-elasticsearch-backup"...
sts-backup-20210219-0300-mref7yrvrswxa02aqq213w
sts-backup-20210220-0300-yrn6qexkrdgh3pummsrj7e
sts-backup-20210221-0300-p481sih8s5jhre9zy4yw2o
sts-backup-20210222-0300-611kxendsvh4hhkoosr4b7
sts-backup-20210223-0300-ppss8nx40ykppss8nx40yk
===
job.batch "elasticsearch-list-snapshots-20210224t133115" deleted
----

La fecha y hora en que se realizó la copia de seguridad forma parte del nombre de la copia.

=== Eliminar índices de Elasticsearch

[NOTE]
====
Puede utilizar el indicador `+--delete-all-indices+` con el script de restauración para eliminar automáticamente todos los índices antes de restaurar. Para obtener más información, consulte xref:/setup/data-management/backup_restore/kubernetes_backup.adoc#_restore_an_elasticsearch_snapshot[restaurar una instantánea de Elasticsearch].
====

Para eliminar manualmente los índices de Elasticsearch existentes y restaurar una instantánea, siga estos pasos:

. Detenga la indexación: reduzca a 0 todas las implementaciones que utilicen Elasticsearch:
+
[,bash]
----
kubectl scale --replicas=0 deployment -l observability.suse.com/scalable-during-es-restore="true"
----

. Abre un port-forward al master de Elasticsearch:
+
[,bash]
----
kubectl port-forward service/suse-observability-elasticsearch-master 9200:9200
----

. Obtener una lista de todos los índices:
+
[,bash]
----
curl "http://localhost:9200/_cat/indices?v=true"
----
+
El resultado debería ser el siguiente:
+
[,bash]
----
health status index                              uuid                   pri rep docs.count docs.deleted store.size pri.store.size dataset.size
green  open   .ds-sts_k8s_logs-2025.09.28-004619 9p7RZwNCR-aQwInTMr5Bow   3   1   24511032            0        6gb            3gb          3gb
green  open   sts_topology_events-2025.10.01     86I2JZIeRzqWkK1dolHzhg   1   1    1576132            0    111.6mb         55.8mb       55.8mb
green  open   sts_topology_events-2025.10.02     T-bcrok_S1uVPLusQuCMxw   1   1     999748            0     75.2mb         37.6mb       37.6mb
green  open   .ds-sts_k8s_logs-2025.09.30-004653 rwlcAr0sTPe9NaImtJLIiw   3   1   24387607            0        6gb            3gb          3gb
green  open   sts_topology_events-2025.09.10     T0x-qvyUR2-dg4fyvdZIaQ   1   1    1746143            0    131.6mb         65.8mb       65.8mb
----

. Elimina un índice con el siguiente comando:
+
[,bash]
----
curl -X DELETE "http://localhost:9200/INDEX_NAME?pretty"
----
+
Sustituya `+INDEX_NAME+` por el nombre del índice que desea eliminar, por ejemplo:
+
[,bash]
----
curl -X DELETE "http://localhost:9200/sts_internal_events-2021.02.19?pretty"
----

. La salida debería ser:
+
[,javascript]
----
{
"acknowledged" : true
}
----

=== Restaurar una instantánea de Elasticsearch

[WARNING]
====
*Cuando se restaura una instantánea, los índices existentes no se sobrescriben.*

Puede utilizar la bandera `+--delete-all-indices+` para eliminar automáticamente todos los índices mediante el script de restauración, o eliminarlos manualmente como se describe en xref:/setup/data-management/backup_restore/kubernetes_backup.adoc#_delete_elasticsearch_indices[eliminar índices de Elasticsearch].

====

[WARNING]
====
*Si Elasticsearch `+PersistentVolumes+` se ha vuelto a crear* (por ejemplo, por eliminación accidental y tras el reinicio del pod), debe volver a crear la configuración de la copia de seguridad de Elasticsearch mediante cualquiera de los dos métodos siguientes:

* Reinstalación del cuadro de SUSE Observability Helm con la misma configuración utilizada para la instalación inicial (OR)
* Activación manual de la inicialización de la copia de seguridad CronJob:
+
[,bash]
----
kubectl create job --from=cronjob.batch/suse-observability-backup-init "suse-observability-backup-init-$(date +%s)"
----
====
Para restaurar una instantánea de Elasticsearch, seleccione un nombre de instantánea y páselo como primer parámetro. Puede especificarlo opcionalmente:

* Una lista separada por comas de los índices a restaurar. Si no se especifica, se restaurarán todos los índices que coincidan con el valor de Helm `+backup.elasticsearch.scheduled.indices+`. El valor por defecto es `+"sts*"+`).
* Introducido en la versión `+2.6.1+`, puede utilizar el indicador "--delete-all-indices" para borrar automáticamente todos los índices existentes antes de restaurar.

==== Restauración básica

[,bash]
----
./restore/restore-elasticsearch-snapshot.sh \
  sts-backup-20210223-0300-ppss8nx40ykppss8nx40yk
----

==== Restaurar índices específicos

[,bash]
----
./restore/restore-elasticsearch-snapshot.sh \
  sts-backup-20210223-0300-ppss8nx40ykppss8nx40yk \
  "<INDEX_TO_RESTORE>,<INDEX_TO_RESTORE>"
----

==== Restauración con borrado automático de índices

[,bash]
----
./restore/restore-elasticsearch-snapshot.sh \
  sts-backup-20210223-0300-ppss8nx40ykppss8nx40yk \
  --delete-all-indices
----

Cuando utilice la bandera `+--delete-all-indices+`, confirme en el prompt para continuar la acción:

[,text]
----
WARNING: All indices will be deleted before restore!
Are you sure you want to continue? (yes/no): yes
=== Starting restore job
job.batch/elasticsearch-restore-20251003t115746 created
=== Restore job started. Follow the logs and clean up the job with the following commands:
kubectl logs --follow job/elasticsearch-restore-20251003t115746
kubectl delete job/elasticsearch-restore-20251003t115746
----

Sigue los registros para ver el progreso de borrado y restauración:

[,text]
----
kubectl logs --follow job/elasticsearch-restore-20251003t115746

=== Deleting all indices matching pattern "sts*"...
Found indices to delete:
.ds-sts_k8s_logs-2025.10.03-000007
.ds-sts_k8s_logs-2025.10.03-000004
sts_topology_events-2025.10.02
sts_topology_events-2025.10.03
...
=== All indices deleted successfully
=== Restoring ElasticSearch snapshot "sts-backup-20251003-0925-aby7d1tgs9whvbm6qj04ug" (indices = "sts*") from snapshot repository "sts-backup" in bucket "sts-elasticsearch-backup"...
{
  "snapshot" : {
    "snapshot" : "sts-backup-20251003-0925-aby7d1tgs9whvbm6qj04ug",
    "indices" : [
      ".ds-sts_k8s_logs-2025.10.02-000003",
      "sts_topology_events-2025.10.02",
      "sts_topology_events-2025.10.03"
    ],
    "shards" : {
      "total" : 15,
      "failed" : 0,
      "successful" : 15
    }
  }
}
===
----

Una vez restaurados los índices, escale todos los despliegues utilizando Elasticsearch:

[,bash]
----
kubectl scale --replicas=1 deployment -l observability.suse.com/scalable-during-es-restore="true"
----
