= Conservación de datos
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

== Visión general

SUSE Observability impone límites de retención de datos para ahorrar espacio de almacenamiento y mejorar el rendimiento. Puede configurar el período de retención de datos para equilibrar la cantidad de datos almacenados con el rendimiento de SUSE Observability y la disponibilidad de los datos.

== Conservación de los datos del gráfico topológico

Por defecto, los datos del gráfico de topología se conservarán durante 30 días. Esto funciona de manera que siempre se conservará el último estado del gráfico topológico; sólo se eliminará el historial de más de 30 días de antigüedad.
En algunos casos, puede ser útil conservar los datos históricos durante más de 30 días o reducirlos a menos de 30 días para ahorrar espacio en disco. La retención de topología puede configurarse a través del cuadro de mando:

[,yaml]
----
stackstate:
  topology:
    # Retention set to 1 week
    retentionHours: 144
----

Tenga en cuenta que al añadir más tiempo al periodo de conservación de datos, la cantidad de datos almacenados también va a crecer y requerirá más espacio de almacenamiento. Esto también puede afectar al rendimiento de las Vistas.

Al reducir el periodo de retención, puede pasar algún tiempo hasta que se libere espacio en disco (al menos 15 minutos).

=== Resolución de problemas de espacio en disco de topología
En caso de problemas de espacio en disco, aparece una línea de registro - `Not enough replicas was chosen. Reason: {NOT_ENOUGH_STORAGE_SPACE=1` en el namenode. Siga los pasos que se indican a continuación para hacer frente a esta situación:

* Disminuya la retención, prepare la instancia para recuperar espacio en disco inmediatamente y active una actualización del timón:
[,yaml]
----
stackstate:
  topology:
    # Retention set to 1 week in case you are running with the default 1 month
    retentionHours: 144
hbase:
  console:
    enabled: true
    replicaCount: 1
  hdfs:
    datanode:
      extraEnv:
        open:
          HDFS_CONF_dfs_datanode_du_reserved_pct: "0"
----

[NOTE]
====
Espere hasta que todos los pods hbase y hdfs estén estables antes de pasar al siguiente paso.
====

* Activar la compactación de datos históricos:
[,bash]
----
kubectl exec -t --namespace suse-observability  $(kubectl get pods --namespace suse-observability --no-headers | grep "console" | awk '{print $1}' | head -n 1) -- /bin/bash -c "stackgraph-console run println\(retention.removeExpiredDataImmediately\(\)\)"
----

* Sigue el progreso utilizando:
----
kubectl exec -t --namespace suse-observability  $(kubectl get pods --namespace suse-observability --no-headers | grep "console" | awk '{print $1}' | head -n 1) -- /bin/bash -c "stackgraph-console run println\(retention.removeExpiredDataImmediatelyStatus\(\)\)"
----

* En caso de que el espacio en disco presupuestado sea insuficiente, póngase en contacto con <support-portal-link>.

* Restaura la configuración. Una vez que el estado ya no está en curso - `Status(inProgress = false, lastFailure = null)`, desencadenar una actualización de timón para preservar la nueva retención como parte de sus valores.
[,yaml]
----
stackstate:
  topology:
    # Retention set to 1 week in case you are running with the default 1 month
    retentionHours: 144
----

== Conservación de eventos y registros

=== Almacén de datos de SUSE Observability

Si utiliza el almacén de eventos/registros proporcionado con SUSE Observability, sus datos se conservarán por defecto durante 30 días. En la mayoría de los casos, la configuración por defecto será suficiente para almacenar todos los índices durante este periodo de tiempo.

==== Configurar el espacio en disco para Elasticsearch

En algunas circunstancias, puede ser necesario ajustar el espacio en disco disponible para Elasticsearch y cómo se asigna a los registros y eventos, por ejemplo, si prevé que llegarán muchos datos para un tipo de datos específico.

Aquí hay un fragmento con la configuración completa de espacio en disco y retención para Elasticsearch, incluyendo los valores por defecto.

[,yaml]
----
elasticsearch:
  volumeClaimTemplate:
    resources:
      requests:
        storage: 250Gi
stackstate:
  components:
    receiver:
      esDiskSpaceShare: 70
      # Number of days to keep the logs data on Es
      retention: 7
    e2es:
      esDiskSpaceShare: 30
      # Number of days to keep the events data on Es
      retention: 30
----

El espacio en disco disponible para Elasticsearch se configura a través de la clave `elasticsearch.volumeClaimTemplate.resources.requests.storage`. Para cambiar este valor después de la instalación inicial xref:/setup/data-management/data_retention.adoc#_resizing_storage[se requieren] algunos xref:/setup/data-management/data_retention.adoc#_resizing_storage[pasos adicionales].

NOTE: este es el espacio en disco para cada instancia de ElasticSearch. Para no HA este es el espacio de disco total disponible, pero para HA hay 3 instancias y un factor de replicación de 1. El resultado final es que el almacenamiento total disponible de Elasticsearch será `(250Gi * 3) / 2 = 375Gi`.
En función de `esDiskSpaceShare` y `retention` se reserva una parte del espacio en disco de Elasticsearch para cada tipo de datos.

== Retención de métricas

SUSE Observability utiliza VictoriaMetrics para almacenar métricas. Está configurado con una retención por defecto de 30 días. El cuadro de mando asigna espacio en disco y configura el periodo de retención para las instancias de 1 o 2 métricas Victoria de esta forma:

----
victoria-metrics-0:
  server:
    persistentVolume:
      size: 250Gi
    retentionPeriod: 1 # month
# For HA setups:
victoria-metrics-1:
  server:
    persistentVolume:
      size: 250Gi
    retentionPeriod: 1 # month
----

Para cambiar el tamaño del volumen después de la instalación inicial xref:/setup/data-management/data_retention.adoc#_resizing_storage[se requieren] algunos xref:/setup/data-management/data_retention.adoc#_resizing_storage[pasos adicionales].

Para cambiar el periodo de retención, anule ambas claves `retentionPeriod` con el mismo valor en sus valores personalizados.yaml y xref:/setup/data-management/data_retention.adoc#_update_stackstate[actualice SUSE Observability]:

* Se admiten los siguientes sufijos opcionales: h (hora), d (día), w (semana), y (año). Si no se establece ningún sufijo, la duración se indica en meses.
* El periodo mínimo de conservación es de 24h o 1 día.

== Actualización de SUSE Observability

Después de realizar cambios en values.yaml, SUSE Observability debe actualizarse para aplicar esos cambios al tiempo de ejecución. Esto puede causar un breve tiempo de inactividad mientras se reinician los servicios. Para actualizar SUSE Observability utilice el mismo comando que se utilizó durante la instalación de SUSE Observability y asegúrese de incluir los mismos archivos de configuración con los cambios realizados:

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[OpenShift]:

== Redimensionamiento del almacenamiento

En la mayoría de los clústeres es posible redimensionar un volumen persistente después de haberlo creado y sin interrumpir en absoluto el funcionamiento de las aplicaciones. Sin embargo, esto no se puede hacer simplemente cambiando el tamaño de almacenamiento configurado en el values.yaml del cuadro de SUSE Observability Helm. En su lugar, se necesitan varios pasos:

. Compruebe que la clase de almacenamiento utilizada puede redimensionarse
. Redimensionar los volúmenes
. Actualizar values.yaml y aplicar el cambio (opcional pero recomendado)

Los ejemplos siguientes utilizan el almacenamiento VictoriaMetrics como ejemplo. SUSE Observability está instalado en el espacio de nombres `suse-observability`. El volumen va a ser redimensionado a 500Gi.

=== Compruebe que la clase de almacenamiento admite el cambio de tamaño

Utilice los siguientes comandos `kubectl` para obtener la clase de almacenamiento utilizada y comprobar que `allowVolumeExpansion` está establecido en true.

[,bash]
----
# Get the PVC's for SUSE Observability
kubectl get pvc --namespace suse-observability

# There is a storage class column in the output, copy it and use it to describe the storage class
kubectl describe storageclass <storage-class-name>
----

Compruebe que la salida contiene esta línea:

----
AllowVolumeExpansion:  True
----

Si la línea está ausente o si está configurada en `False` por favor consulte con su administrador de Kubernetes si el redimensionamiento es soportado y puede ser habilitado.

=== Redimensionar los volúmenes

El cuadro de SUSE Observability Helm crea un conjunto de estado, que tiene una plantilla para crear la reclamación de volumen persistente (PVC). Esta plantilla sólo se utiliza para crear el PVC una vez, después ya no se aplicará y tampoco está permitido cambiarla. Así que para hacer los PVC's más grandes hay que editar el propio PVC.

Para cambiar el tamaño del PVC utilice los siguientes comandos.

[,bash]
----
# Get the PVC's for SUSE Observability, allows us to check the current size and copy the name of the PVC to modify it with the next command
kubectl get pvc --namespace suse-observability

# Patch the PVC's specified size, change it to 500Gi
kubectl patch pvc server-volume-stackstate-victoria-metrics-0-0 -p '{"spec":{"resources": { "requests": { "storage": "500Gi" }}}}'

# Get the PVC's again to verify if it was resized, depending on the provider this can take a while
kubectl get pvc --namespace suse-observability
----

=== Actualizar values.yaml y aplicar el cambio

El cambio realizado en la reclamación de volumen persistente (PVC) se mantendrá durante la vida útil de la PVC, pero cuando se realice una instalación limpia se perderá. Sin embargo, lo que es más importante, después de redimensionar el PVC ahora hay una discrepancia entre el estado del cluster y la definición del estado deseado en el values.yaml. Por lo tanto, se recomienda actualizar también el archivo values.yaml. Para eludir el hecho de que este cambio no está permitido, primero elimine el conjunto de estados (pero mantenga los pods en ejecución) para volver a crearlo con la nueva configuración.

[NOTE]
====
Este paso no cambia el tamaño de la PVC en sí, por lo que sólo haciendo este paso no se producirá ningún cambio en el entorno de ejecución.
====


Primero edita tu values.yaml para actualizar el tamaño del volumen para los PVC que acabas de redimensionar. Consulte las secciones sobre xref:/setup/data-management/data_retention.adoc#_retention_of_metrics[Métricas] o xref:/setup/data-management/data_retention.adoc#_retention_of_events_traces_and_logs[Eventos y registros].

Ahora elimine el conjunto de estados para la(s) aplicación(es) para las que se ha cambiado el almacenamiento:

[,bash]
----
# List all stateful sets, check that all are ready, if not please troubleshoot that first
kubectl get statefulset --namespace suse-observability

# Delete the
kubectl delete statefulset --namespace suse-observability stackstate-victoria-metrics-0 --cascade=orphan
----

Por último, xref:/setup/data-management/data_retention.adoc#_update_[actualice SUSE Observability] con la nueva configuración.
