= Rancher 的操作系统管理
:revdate: 2026-01-16
:page-revdate: {revdate}

{elemental-product-name} 是一个利用 Kubernetes 实现集中式全云原生操作系统管理的软件栈。

xref:release-notes.adoc[**最新版本: v1.8.0**]

{elemental-product-name} Stack 由 SLE Micro 上的几个软件包组成：

* *elemental-toolkit*- 包含一套操作系统实用程序，可通过容器对操作系统进行管理。包括 dracut 模块、引导加载器配置、云启动式配置服务等。
* *elemental-operator*- 连接 Rancher 管理器并处理 MachineRegistration 和 MachineInventory CRD。
* *elemental-register*- 通过 machineRegistrations 注册机器，并通过 elemental-cli 安装。
* *elemental-cli*- 安装任何基于 elemental-toolkit 的衍生工具。基本上是基于我们 A/B 安装和升级系统的安装程序。
* *rancher-system-agent*- 在已安装的系统上运行，从 Rancher 管理器获取在系统上安装和运行的指令（"计划"）。

集群节点操作系统是通过{elemental_cli_name} 的容器镜像构建和维护的，可以使用https://www.rancher.com/products/rancher[Manager] Rancher的{elemental_ui_url}[{elemental_ui_name}] 或{elemental_cli_url}[{elemental_cli_name}] 将其安装到新主机上。

{elemental_operator_url}[{elemental_operator_name}] 和{ranchersystemagent_url}[{ranchersystemagent_name}] 使 Rancher Manager 能够完全控制{elemental-product-name} 集群，从安装和管理节点上的操作系统到集中配置新的 K3 或 RKE2 集群。

== {elemental-product-name} 在 x86-64 硬件上

{elemental-product-name} 从 Rancher v2.7.0 开始，它已准备就绪并完全支持 x86-64。

== {elemental-product-name} 在 ARM 硬件上

ARM (aarch64) 处于功能开发阶段。ARM 目前仅在使用 k3s 1.24.8（或更高版本）的 Raspberry Pi 4 Model B 上进行了测试。欢迎反馈意见。

== {elemental-product-name} 在其他硬件上

{elemental-product-name} 目前针对的是 "边缘 "场景，因此不支持其他硬件。随着市场的发展，我们将对此进行重新评估。

== 准备好试一试了吗？

使用首选方法启动并运行{elemental-product-name} 集群

* 使用 Rancher 管理器xref:quickstarts/quickstart-ui.adoc[{elemental-product-name} 插件]
* 使用xref:quickstarts/quickstart-cli.adoc[{elemental-product-name} CLI]

[NOTE]
.下一步是什么？
====
想要了解更多详情？请参阅 "xref:rancher-os-management/architecture/architecture.adoc[建筑 "]部分，或访问{elemental_slack_url}[{elemental_slack_name}]。
====

