= 動的閾値モニター
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 概要

時間とともに大きく変化し、サービスごとに異なるメトリクスに対して、動的しきい値モニターは、シンプルでパフォーマンスの高い異常検知を提供します。 これは、現在のデータを比較するためのコンテキストとして、最近の過去に加えて、1、2、3週間前のデータを使用します。

チェック・ウィンドウ」のデータは、アンダーソン・ダーリング・テストを用いて、歴史的背景から得られたデータと比較される。 これはデータ分布にほとんど仮定を課さない。 この検定は、分布の上端と下端の外れ値に特に敏感である。 データ値はモデル・フィッティングをすることなく直接比較されるため、動的しきい値モニターは非常にロバストである。

時間の経過とともに滑らかに変化する測定基準（例えば5分という時間スケール）の場合、有効なデータポイントの数は生の数よりも少なくなる。 DTはこれを補正するので、パラメータを調整する必要なく、同じモニターを幅広い測定基準に使用できる。

モニター機能に設定できるパラメーターはいくつかある：

* `falsePositiveRate``!!float 1e-8` - 逸脱した行動に対するモニターの感度。 値が低いほど、より多くの（偽の）陽性を抑制するが、偽陰性（気づかれない異常）につながる可能性もある。
* `checkWindowMinutes``10` チェックウィンドウは、迅速な警告（小さな値）と正しく識別された異常（大きな値）の間でバランスをとる必要がある。 一握りのデータポイントが、実際にはうまく機能する。
* `historicWindowMinutes`例えば、`120` （2時間） - 現在時刻を中心に、1週間以上前 - つまり、現在時刻の1時間前から1時間後まで。 また、チェック・ウィンドウの前の2時間も使用される。 ダイナミック閾値モニターは、この履歴データの分布とチェックウィンドウのデータポイントを比較する。
* `historySizeWeeks`:`2` - 歴史的な背景のためにデータを取得した週数。 `1`, `2` または`3` 。
* `removeTrend`絶対値が週によって異なるような傾向のあるメトリクス（例えばリクエスト数）については、この傾向（平均値）を考慮することができます。
* `includePreviousDay`通常、`false` - 週次ではなく日次パターンしかない指標の場合、より最近のデータを使用することができる。

== 動的しきい値モニターの例

動的しきい値機能を使って実装されたモニターは次のようになる：

----
  - _type: "Monitor"
    name: "<name of the monitor>"
    identifier: "urn:stackpack:<stackpack-name>:monitor:<identifier for the monitor>"
    status: "DISABLED"
    description: "<description>"
    function: {{ get "urn:stackpack:aad-v2:shared:monitor-function:dt" }}
    arguments:
      telemetryQuery:
        query: "<metric to bind to component>"
        unit: s
        aliasTemplate: "<name for the metric>"
      topologyQuery: <topology query for the components to bind to>
      falsePositiveRate: <floating point number, e.g. !!float 1e-8>
      checkWindowMinutes: <integer, e.g. 10>
      historicWindowMinutes: <integer, e.g. 120>
      historySizeWeeks: <integer: 1, 2 or 3>
      includePreviousDay: <boolean>
      removeTrend: <boolean>
    intervalSeconds: 60
    remediationHint: "<how to remediate deviating states>"
----

xref:use/alerting/k8s-dynamic-threshold-monitors.adoc[CLIを使用してコンポーネントに閾値モニターを追加する]。
