= 移住ガイド
:revdate: 2025-11-14
:page-revdate: {revdate}

== コンテクスト

Rancher v2.13から、{product_name} がRancherの一部としてインストールされるようになり、別途デプロイする必要がなくなった。Rancher v2.13にアップグレードする前に、ユーザーはこのガイドに従ってスムーズなアップグレードプロセスを行う必要があります。

== 移住

Rancher v2.13にアップグレードする_前に_、以下の手順を順番に実行してください：

. {product_name} を v0.24.3 にアップグレードしてください。v0.24のすべてのパッチリリースがRancher v2.13へのアップグレードのためにクラスタを準備するため、このステップは重要です。
. アンインストール{product_name}.Rancher v2.13以降、{product_name} はもはやオプトインアドオンではなく、Rancherシステムコンポーネントであるためです。そのため、Rancherは以前とは異なる名前空間にインストールするため、以前にインストールしたバージョンをまず手動でアンインストールする必要がある。{product_name} のv0.24.3をアンインストールすると、コアCAPIプロバイダ自体は削除されますが、コアCAPI CRDは保持されます。移行中、コアCAPIコントローラは管理クラスタ上で実行されませんが、ダウンストリームCAPIクラスタは通常どおり実行され、影響はありません。
. 以下のkubectlコマンドを実行する：
+
[source,bash]
----
kubectl patch crd capiproviders.turtles-capi.cattle.io --type=json -p='[{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "cattle-turtles-system"}]'
kubectl patch crd clusterctlconfigs.turtles-capi.cattle.io --type=json -p='[{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "cattle-turtles-system"}]'
----

これらのコマンドは`+capiprovider+` と`+clusterctlconfig+` CRD にパッチを当て、Rancher v2.13 の一部としてインストールされたときに{product_name} に採用されるようにします。

上記の移行は、{product_name} バージョン&le; v0.24.3を実行しているユーザーに必要であることに注意してください。Rancher v2.13をインストールする新規ユーザーは、マイグレーションを行う必要はありません。