include::partial$variables.adoc[]
= Distribuição de uma política OPA com {project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Anote sua política Rego com metadados relevantes e, em seguida, envie-a para um registro OCI para se preparar para a implantação.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "distributing", "open policy agent", "opa", "rego"]
:sidebar_label: Distribuir
:current-version: {page-origin-branch}

Você escreveu, criou e executou sua política Rego.
Agora é hora de distribuir a apólice.

As políticas precisam ser anotadas, para que possam ser executadas no site `policy-server`.
O `policy-server` é a parte que executa as políticas, quando executado em um cluster do Kubernetes.

== Anotação da política

Anotar uma política é um processo que enriquece os metadados da política com informações relevantes.
Informações como autoria, licença, localização do código-fonte, regras, que descrevem que tipo de recursos essa política entende e avalia.

Para anotar sua política, você precisa escrever um arquivo `metadata.yaml`:

[subs="+attributes",yaml]
----
rules:
- apiGroups: [""]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["CREATE"]
mutating: false
contextAware: false
executionMode: opa
annotations:
  io.kubewarden.policy.title: no-default-namespace
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: This policy will reject any resource created inside the default namespace
  io.kubewarden.policy.author: The {project-name} Authors
  io.kubewarden.policy.url: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.source: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
      This policy is just an example.

      You can write interesting descriptions about the policy here.
----

Você pode ver vários detalhes:

* Regras:
Quais recursos essa política está direcionando.
* Mutação:
Se essa política está sofrendo mutação.
Nesse caso, ele está apenas validando.
* Consciente do contexto:
Se essa política requer contexto do cluster para avaliar a solicitação.
* Modo de execução:
Como essa é uma política Rego, é obrigatório especificar o modo de execução esperado,`opa` ou `gatekeeper`.
Essa política é escrita no estilo `opa`, retornando um objeto `AdmissionReview` inteiro.
* Anotações: Metadados armazenados na própria política.

Vá em frente e faça anotações em sua apólice:

[subs="+attributes",console]
----
$ kwctl annotate policy.wasm --metadata-path metadata.yaml --output-path annotated-policy.wasm
----

Agora você pode inspecionar a política executando `kwctl inspect annotated-policy.wasm`.

== Impulsionando a política

Agora que a política está anotada, você pode enviá-la para um registro OCI.

[subs="+attributes",console]
----
$ kwctl push annotated-policy.wasm registry.my-company.com/kubewarden/no-default-namespace:v0.0.1
Policy successfully pushed
----

Sua política Rego, voltada para a estrutura OPA, tem tudo o que precisa para ser implantada na produção, criando um `ClusterAdmissionPolicy`.
Você pode preparar isso também.
Primeiramente, você precisa acessar a apólice na loja local `kwctl`:

[subs="+attributes",console]
----
$ kwctl pull registry://registry.my-company.com/kubewarden/no-default-namespace:v0.0.1
pulling policy...
----

Crie um `ClusterAdmissionPolicy` a partir dele.
Essa operação leva em conta os metadados que possui sobre a política:

[subs="+attributes",console]
----
$ kwctl manifest registry://registry.my-company.com/kubewarden/no-default-namespace:v0.0.1 --type ClusterAdmissionPolicy
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "registry://registry.my-company.com/kubewarden/no-default-namespace:v0.0.1"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Agora você pode usar o site `ClusterAdmissionPolicy` como base para direcionar os recursos que deseja ou implantar no Kubernetes como está.
