= Java-Anwendungen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

Das Java SDK unterstützt die Instrumentierung von Anwendungen auf der JVM. Daher unterstützt es nicht nur Java, sondern auch andere JVM-Sprachen wie Kotlin und Scala.

== Automatische Instrumentierung

Die automatische Instrumentierung für Java verwendet ein Java-Agent-JAR, das an jede Java 8+ Anwendung angehängt werden kann. Es injiziert dynamisch Bytecode, um Telemetrie von vielen https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md[populären Bibliotheken und Frameworks], einschließlich mehrerer Kotlin- und Scala-Bibliotheken, zu erfassen. Es kann verwendet werden, um Telemetriedaten auf der Website &quot;`+edges+`&quot; einer Anwendung oder eines Dienstes zu erfassen, z. B. eingehende Anfragen, ausgehende HTTP-Aufrufe, Datenbankaufrufe und so weiter.

Die automatische Instrumentierung erfordert keine Änderungen an der Anwendung. Führen Sie die folgenden Schritte aus, um sie einzurichten:

. Laden Sie https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar[opentelemetry-javaagent.jar] aus https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases[Releases] des opentelemetry-java-instrumentation Repository herunter und binden Sie die JAR-Datei in das Docker-Image Ihrer Anwendung ein. Die JAR-Datei enthält den Agenten und die Instrumentierungsbibliotheken.
. Aktualisieren Sie den Befehl, der Ihre Anwendung startet, um den Java-Agenten zu laden, indem Sie entweder den Einstiegspunkt oder den Befehl für das Docker-Image oder die `+command+` im Kubernetes-Manifest für Ihre Anwendung aktualisieren. `+-javaagent:/path/to/opentelemetry-javaagent.jar+` hinzufügen:
+
[,bash]
----
java -javaagent:/path/to/opentelemetry-javaagent.jar -jar myapp.jar
----

. Stellen Sie Ihre Anwendung mit den zusätzlichen Umgebungsvariablen bereit xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[, um den Dienstnamen und den Exporter-Endpunkt zu konfigurieren]. Unterstützte Protokolle sind gRPC und protobuf über HTTP.
. Vergewissern Sie sich, dass SUSE Observability Abläufe und/oder Metriken empfängt, indem Sie im Metrik-/Ablaufverfolgungsexplorer für Ihren Servicenamen nach den Metriken/Abläufen suchen.

Weitere Einzelheiten entnehmen Sie bitte der https://opentelemetry.io/docs/languages/java/automatic/[Dokumentation].

== Manuelle Instrumentierung

Manuelle Instrumentierung kann verwendet werden, wenn Sie Metriken, Traces oder Protokolle von Teilen des Codes benötigen, die von der automatischen Instrumentierung nicht unterstützt werden. Zum Beispiel nicht unterstützte Bibliotheken, firmeneigener Code oder Metriken auf Unternehmensebene.

Um diese Daten zu erfassen, müssen Sie Ihre Anwendung ändern.

. Einbindung des Open Telemetry SDK als Abhängigkeit
. Fügen Sie Ihrer Anwendung Code hinzu, um bei Bedarf Metriken, Spans oder Protokolle zu erfassen.

Eine ausführliche Dokumentation hierzu finden Sie auf den https://opentelemetry.io/docs/languages/java/instrumentation/[Dokumentseiten des].

Stellen Sie sicher, dass Sie den OTLP-Exporter (dies ist die Standardeinstellung) und die https://opentelemetry.io/docs/languages/java/instrumentation/#_autoconfiguration[automatische Konfiguration] verwenden. Bei der Bereitstellung der Anwendung werden der Dienstname und der Exporter xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[über Umgebungsvariablen konfiguriert].

== Metriken in SUSE Observability

ifdef::ss-ff-stackpacks2_enabled[]
Für einige Java-Metriken, z. B. für Garbage-Collector-Metriken, hat SUSE Observability Diagramme zu den entsprechenden Komponenten definiert. Bei Kubernetes sind die Diagramme auf den Pods verfügbar. Es ist möglich, xref:/setup/custom-integrations/metric-bindings/index.adoc[Diagramme für weitere Metriken hinzuzufügen], dies funktioniert für Metriken aus der automatischen Instrumentierung, aber auch für anwendungsspezifische Metriken aus der manuellen Instrumentierung.
endif::[]

ifndef::ss-ff-stackpacks2_enabled[]
Für einige Java-Metriken, z. B. für Garbage-Collector-Metriken, hat SUSE Observability Diagramme zu den entsprechenden Komponenten definiert. Bei Kubernetes sind die Diagramme auf den Pods verfügbar. Es ist möglich, xref:/use/metrics/k8s-add-charts.adoc[Diagramme für weitere Metriken hinzuzufügen], dies funktioniert für Metriken aus der automatischen Instrumentierung, aber auch für anwendungsspezifische Metriken aus der manuellen Instrumentierung.
endif::[]
