= SDK-Exporteure konfigurieren
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

Um Daten an SUSE Observability zu senden, verwenden die SDKs, die zur Instrumentierung Ihrer Anwendung verwendet werden, einen integrierten Exporter. Bei einem produktionsbereiten Setup werden die Daten über <<_with_a_collector_production_setup,einen Collector>> in der Nähe Ihrer instrumentierten Anwendungen an SUSE Observability gesendet. Es ist aber auch möglich, dass die instrumentierte Anwendung die Telemetriedaten <<_without_a_collector,direkt>> an SUSE Observability <<_without_a_collector,sendet>>.

== Mit einem Kollektor (Produktionsaufbau)

=== SDK-Exporter-Konfiguration für Kubernetes

Alle SDKs, unabhängig von der Sprache, verwenden dieselbe Grundkonfiguration für die Definition des Open Telemetry https://opentelemetry.io/docs/concepts/glossary/#_service[Dienstnamens] und des Exporter-Endpunkts (d. h. wohin die Telemetrie gesendet wird).

Diese können durch das Setzen von Umgebungsvariablen für Ihre instrumentierte Anwendung konfiguriert werden.

In Kubernetes setzen Sie diese Umgebungsvariablen im Manifest für Ihren Workload (ersetzen Sie `+<the-service-name>+` durch einen Namen für Ihren Anwendungsdienst):

[,yaml]
----
...
spec:
  containers:
  - env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317
    - name: OTEL_SERVICE_NAME
      value: <the-service-name>
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: grpc
...
----

Der im Beispiel angegebene Endpunkt setzt voraus, dass der Collector mit den Standardeinstellungen aus dem xref:/setup/otel/collector.adoc[Installationshandbuch] installiert wurde. Er verwendet den Anschluss `+4317+`, der die Version `+gRPC+` des OTLP-Protokolls verwendet. Einige Instrumente unterstützen nur HTTP, verwenden Sie in diesem Fall Port `+4318+`.

Der Dienstname kann auch von bereits vorhandenen Kubernetes-Labels abgeleitet werden. Zum Beispiel so:

[,yaml]
----
spec:
  containers:
  - env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['app.kubernetes.io/component']
----

=== SDK Exporter-Konfiguration für andere Installationen

Um das SDK zu konfigurieren, setzen Sie diese Umgebungsvariablen für Ihre Anwendung:

[,bash]
----
export OTEL_EXPORTER_OTLP_ENDPOINT="http://<the-host-for-the-collector>:4317"
export OTEL_EXPORTER_OTLP_PROTOCOL="grpc"
export OTEL_SERVICE_NAME="<the-service-name>"
export OTEL_RESOURCE_ATTRIBUTES='service.namespace=<the-namespace>'
----

Das Beispiel verwendet den Anschluss `+4317+`, der die Version `+gRPC+` des OTLP-Protokolls verwendet. Einige Instrumente unterstützen nur HTTP, das den Port `+4318+` verwendet, wobei das Protokoll auf `+http+` eingestellt ist. Verwenden Sie die SDK-Dokumentation für Ihre Sprache, um zu prüfen, welches Protokoll das SDK unterstützt. Die Angaben `+OTEL_EXPORTER_OLTP_ENDPOINT+` und `+OTEL_EXPORTER_OTLP_PROTOCOL+` können weggelassen werden, sie haben Standardwerte, die Daten an den bevorzugten Endpunkt auf dem localhost senden.

Die `+OTEL_RESOURCE_ATTRIBUTES+` ist optional und kann neben der Definition eines Dienstnamensraums dazu verwendet werden, weitere Ressourcenattribute in einer kommagetrennten Liste festzulegen.

=== gRPC gegenüber HTTP

OTLP, das Open Telemetry Protocol, unterstützt gRPC und protobuf über HTTP. Im vorigen Abschnitt wurde das Protokoll des Ausführers auf `+gRPC+` eingestellt, was in der Regel die beste Leistung ergibt. Neben der Tatsache, dass das SDK gRPC nicht unterstützt, kann es auch andere Gründe geben, HTTP zu bevorzugen:

* Einige Firewalls sind nicht für die Verarbeitung von gRPC eingerichtet
* (Reverse-)Proxys und Lastverteiler unterstützen gRPC möglicherweise nicht ohne zusätzliche Konfiguration
* Die langlebigen Verbindungen von gRPC können beim Lastausgleich Probleme verursachen.

Um zu HTTP anstelle von gRPC zu wechseln, ändern Sie das Protokoll auf `+http+` _und_ verwenden Sie den Port `+4318+`.

Zusammenfassend lässt sich sagen, dass Sie versuchen können, HTTP zu verwenden, wenn gRPC bei Ihnen nicht funktioniert:

* `+grpc+` Protokoll verwendet Port `+4317+` auf dem Kollektor
* `+http+` Protokoll verwendet Port `+4318+` auf dem Kollektor

== Ohne Kollektor

Bei kleinen Testkonfigurationen kann es praktisch sein, Daten von Ihrer instrumentierten Anwendung direkt an SUSE Observability zu senden. Der einzige Unterschied zum oben dokumentierten Kollektoraufbau besteht darin, dass ein anderer Wert für `+OTEL_EXPORTER_OTLP_ENDPOINT+` verwendet wird:

* Für gRPC verwenden Sie den OTLP-Endpunkt für SUSE Observability, siehe die xref:/setup/otel/otlp-apis.adoc[Seite OTLP-APIs].
* Für HTTP verwenden Sie den OTLP over HTTP-Endpunkt für SUSE Observability, siehe die xref:/setup/otel/otlp-apis.adoc[Seite OTLP-APIs].

[NOTE]
====
Ersetzen Sie sowohl die Kollektor-URL *als auch* den Port durch die SUSE Observability-Endpunkte. Je nach Ihrer SUSE Observability-Installation sind die Ports unterschiedlich.
====

