include::partial$variables.adoc[]
= Fortalecimento dos webhooks do site {short-project-name} 
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Webhooks
:description: Configure as políticas de rede e a autenticação para limitar o acesso aos webhooks em seu cluster do Kubernetes, restringindo especificamente as conexões de chamadores inválidos.
:keywords: kubewarden, kubernetes, segurança
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: referência
:doc-topic: referência, segurança

A pilha {project-name} usa webhooks para aplicar políticas em um cluster do Kubernetes.
Cada instância do `+PolicyServer+` expõe um webhook que o servidor da API do Kubernetes chama para validar e alterar recursos. Além disso, o `+kubewarden-controller+`expõe webhooks para validar e alterar os recursos personalizados fornecidos pelo projeto{short-project-name}.

Para diminuir a superfície de ataque, você deve limitar o acesso a esses webhooks aos únicos chamadores válidos que eles têm:

* o servidor da API do Kubernetes
* o componente xref:/explanations/audit-scanner/audit-scanner.adoc[do scanner de auditoria].

Você pode fazer isso usando políticas de rede e autenticação de forma independente, ou em conjunto, para proteger os webhooks contra ataques.

== Bloquear o tráfego externo usando políticas de rede

Espera-se que os webhooks aceitem apenas solicitações do servidor da API do Kubernetes e do componente do scanner de auditoria. No entanto, por padrão, os webhooks podem aceitar tráfego de qualquer origem. Se estiver usando uma CNI (Container Network Interface) compatível com políticas de rede, você poderá criar uma política que bloqueie o tráfego que não se origina do servidor de API.

O recurso NetworkPolicy integrado no Kubernetes não pode bloquear ou admitir o tráfego dos hosts do cluster. Além disso, o processo `+kube-apiserver+` está sempre em execução na rede do host. Portanto, você deve usar os recursos avançados de política de rede do CNI em uso. Seguem exemplos para Calico e Cilium. Consulte a documentação de seu CNI para obter mais detalhes.

=== Calico

Use o recurso NetworkPolicy no grupo `+crd.projectcalico.org/v1+` API para definir uma política de rede como a seguinte:

[source,yaml]
----
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-k8s-and-audit-scanner
  namespace: kubewarden
spec:
  selector: 'app.kubernetes.io/component in {"kubewarden-controller", "policy-server"}'
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      source:
        nets:
        - 192.168.42.0/24
      destination:
        selector: 'app.kubernetes.io/component in {"kubewarden-controller", "policy-server"}'
    - action: Allow
      protocol: TCP
      source:
        namespaceSelector: 'kubernetes.io/metadata.name == "kubewarden"'
      destination:
        selector: 'app.kubernetes.io/component in {"kubewarden-controller", "policy-server"}'
----

[NOTE]
====

Essa política de rede usa seletores de rótulos introduzidos em {short-project-name} 1.23.0. Se estiver usando uma versão mais antiga, atualize os rótulos na política para que correspondam à sua implantação.

Mais especificamente, escreva o

[source,yaml]
----
selector: 'app.kubernetes.io/component in {"kubewarden-controller", "policy-server"}'
----

seletores como:

[source,yaml]
----
selector: 'app.kubernetes.io/name == "kubewarden-controller" || has(kubewarden/policy-server)'
----
====

=== Cilium

Use o recurso CiliumNetworkPolicy no grupo `+cilium.io/v2+` API para definir uma política de rede como a seguinte:

[source,yaml]
----
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-k8s-and-audit-scanner
  namespace: kubewarden
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - policy-server
          - controller
  ingress:
    - fromEntities:
      - host
      - remote-node
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kubewarden
----

[NOTE]
====

Essa política de rede usa seletores de rótulos introduzidos em {short-project-name} 1.23.0. Se estiver usando uma versão mais antiga, atualize os rótulos na política para que correspondam à sua implantação.

Mais especificamente, escreva o

[source,yaml]
----
matchExpressions:
  - key: app.kubernetes.io/component
    operator: In
    values:
      - policy-server
      - controller
----

expressão como:

[source,yaml]
----
endpointSelector:
matchExpressions:
  - key: app.kubernetes.io/name
    operator: In
    values:
      - kubewarden-controller
  - key: kubewarden/policy-server
    operator: Exists
----
====

== Exigir que o servidor de API do Kubernetes se autentique no webhook

[TIP]
====

Consulte o xref:/howtos/security-hardening/webhook-mtls.adoc[webook mTLS how-to] para obter um guia passo a passo sobre como configurar o servidor de API do Kubernetes do K3s para autenticar o webhook.

====

Os webhooks expostos pela pilha {short-project-name} só devem aceitar solicitações do servidor da API do Kubernetes ou do componente do scanner de auditoria. Por padrão, esses webhooks não exigem que os clientes se autentiquem neles. Eles aceitam qualquer solicitação.

Você pode configurar os webhooks para exigir credenciais, de modo que somente o servidor de API e os processos do scanner de auditoria possam acessá-los. Consultehttps://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers[documentação do Kubernetes] para obter mais informações.

. Configure o servidor de API para apresentar um certificado de cliente ao webhook, apontando para um arquivo `+AdmissionConfiguration+` para configurar os plug-ins`+ValidatingAdmissionWebhook+` e `+MutatingAdmissionWebhook+`:
+
Crie um arquivo chamado `+admission.yaml+` com o seguinte conteúdo:
+
[source,yaml]
----
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
 configuration:
   apiVersion: apiserver.config.k8s.io/v1
   kind: WebhookAdmissionConfiguration
   kubeConfigFile: "/etc/k8s/admission/kubeconfig"
- name: MutatingAdmissionWebhook
 configuration:
   apiVersion: apiserver.config.k8s.io/v1
   kind: WebhookAdmissionConfiguration
   kubeConfigFile: "/etc/k8s/admission/kubeconfig"
----
+
Esse é o mesmo arquivo de configuração usado para configurar outros plug-ins, como o`+PodSecurity+`. Se a sua distribuição ou configuração usar plug-ins de admissão adicionais, você também deverá configurá-los.

. Crie o arquivo `+kubeconfig+` ao qual os plug-ins de admissão se referem. O {short-project-name} só oferece suporte à autenticação de certificado de cliente, portanto, gere um par de chaves TLS e defina o kubeconfig para usar client-certificate e client-key ou client-certificate-data e client-key-data.
+
Por exemplo:
+
[source,yaml]
----
apiVersion: v1
kind: Config
users:
- name: '*.kubewarden.svc'
  user:
    client-certificate: /path/to/client/cert
    client-key: /path/to/client/key
----

. Inicie o binário `+kube-apiserver+` com o sinalizador`+--admission-control-config-file+` apontando para seu arquivo `+AdmissionConfiguration+`. A maneira de fazer isso varia de acordo com a distribuição e não é suportada universalmente, como nos provedores de Kubernetes hospedados. Consulte a documentação de sua distribuição do Kubernetes.

. Disponibilize o certificado da CA raiz que emitiu o certificado do cliente do servidor de API para a pilha {short-project-name}.
+
Coloque seu conteúdo em um `+ConfigMap+` no espaço de nome `+kubewarden+`usando uma chave chamada `+client-ca.crt+`.
+
Supondo que a CA raiz esteja disponível em `+/etc/k8s/admission/certs/rootCA.crt+`, crie a `+ConfigMap+` com o seguinte comando:
+
[source,console]
----
kubectl create configmap -n kubewarden api-server-mtls \
   --from-file=client-ca.crt=/etc/k8s/admission/certs/rootCA.crt
----

. Por fim, ao instalar o gráfico do `+kubewarden-controller+` Helm, certifique-se de ativar os seguintes valores:
+
- Defina `+mTLS.enable+` como `+true+`.
- Defina `+mTLS.configMapName+` como o nome do `+ConfigMap+` que foi criado anteriormente.
+
O nome `+ConfigMap+` é `+api-server-mtls+`, portanto, o comando Helm para instalar o `+kubewarden-controller+` é:
+
[source,console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller \
   --set mTLS.enable=true \
   --set mTLS.configMapName=api-server-mtls
----
+
O controlador {short-project-name} cria um certificado de cliente para ser usado pelo componente do scanner de auditoria. O certificado é girado automaticamente pelo controlador quando necessário.
