= 用語集
:revdate: 2025-11-14
:page-revdate: {revdate}

== 目次

[cols=14*]
|===
| xref:./glossary.adoc#_a[A]
| xref:./glossary.adoc#_b[B]
| xref:./glossary.adoc#_c[C]
| xref:./glossary.adoc#_f[F]
| xref:./glossary.adoc#_i[I]
| xref:./glossary.adoc#_k[K]
| xref:./glossary.adoc#_m[M]
| xref:./glossary.adoc#_n[N]
| xref:./glossary.adoc#_o[O]
| xref:./glossary.adoc#_p[P]
| xref:./glossary.adoc#_r[R]
| xref:./glossary.adoc#_s[S]
| xref:./glossary.adoc#_t[T]
| xref:./glossary.adoc#_w[W]
|===

== A

=== アドオン

Kubernetes準拠のクラスタをデプロイするために必要な基本コンポーネントを超えるサービスで、2つのタイプに分類される：

* *コアアドオン*：Kubernetes準拠のクラスタをデプロイするために必要なアドオン：DNS、kube-proxy、CNI。
* *追加アドオン*：Kubernetes準拠クラスタに不要なアドオン（metrics/Heapster、Dashboardなど）。

=== エアギャップ環境

インターネットに直接アクセスすることなく、Kubernetesクラスタをセットアップして実行する。

== B

=== ブートストラップ

サーバーをKubernetesノードにするプロセス。これには、マシンをバックアップするサーバーを作成する際に提供するデータの組み立てや、そのサーバー上で実行されるソフトウェアのランタイム設定が含まれる。

=== ブートストラップ・クラスター

ターゲット管理クラスタのプロビジョニングに使用される一時クラスタ。

=== ブートストラップ・プロバイダー

<<_bootstrap,ブートストラップ・プロセスの>>ソリューションを実装する<<_provider,プロバイダーを>>指す。

== C

=== CAPI

コアクラスタAPI

=== CAPA

クラスタAPIプロバイダAWS

=== CAPD

クラスタAPIプロバイダ Docker

=== CAPG

クラスターAPI Google Cloud Provider

=== CAPIO

クラスタAPIオペレータ

=== CAPRKE2

クラスタAPIプロバイダRKE2。CAPRKE2の詳細については、https://caprke2.docs.rancher.com[] 。

=== CAPV

クラスタAPIプロバイダ vSphere

=== CAPZ

クラスタAPIプロバイダー Azure

=== CAPIプロバイダー

<<_cluster_api_operator,CAPI Operator>>および<<_cluster_api,クラスタAPI>>リソースのプロビジョニングと操作を容易にするパブリックAPIです。

=== 子どもクラスタ

<<_workload_cluster,ワークロードクラスターと>>同じ意味で使われる。

=== クラスター

完全なKubernetesデプロイメント。管理クラスタおよびワークロードクラスタを参照してください。

=== クラスタクラス

1つまたは複数のクラスタを継続的に調整するために使用されるトポロジー（制御プレーンとワーカー）を定義するテンプレートのコレクション。
xref:../user/clusterclass.adoc[ClusterClassを]参照。

=== クラスタAPI

または*クラスタAPIプロジェクト*

Cluster APIはSIG-cluster-lifecycleのサブプロジェクトである。また、ソフトウェア・コンポーネントやAPI、それらを生み出すコミュニティを指す場合にも使われる。

<<_core_provider,コア・プロバイダーを>>見る

=== クラスタAPIオペレータ

または*クラスタAPIオペレータプロジェクト*

Cluster API OperatorはSIG-cluster-lifecycleのサブプロジェクトです。クラスタ管理者が宣言的なアプローチを使って管理クラスタ内のクラスタAPIプロバイダのライフサイクルを処理できるように設計されている。

=== クラスタAPIプロバイダRKE2

<<_caprke2,クラスタAPIプロバイダRKE>>2は、KubernetesコントロールプレーンノードをプロビジョニングするためのクラスタAPIコントロールプレーンプロバイダと、<<_rke2,RKE2が>>Kubernetesディストロとして使用されているマシン上でKubernetesをブートストラップするためのクラスタAPIブートストラッププロバイダの2つのプロバイダタイプの組み合わせです。

=== 制御プレーン

クラスタの基盤となるKubernetesサービスのセット。参照：https://kubernetes.io/docs/concepts/#_kubernetes-control-plane 2つのバリエーションがある：

* *自前で用意する*：単一のCluster APIデプロイメントによって完全に管理されるポッドまたはマシンで構成されるKubernetesコントロールプレーン。
* *外部*または*マネージド*：クラスタAPI以外のシステム（例えば、GKE、AKS、EKS、IKS）によって提供され、制御されるコントロールプレーン。

=== 制御プレーン・プロバイダー

Kubernetesの<<_control_plane,コントロールプレーンを>>管理するソリューションを実装する<<_provider,プロバイダーを>>指す。

<<_caprke2,CAPRRKE2>>、<<_kcp,KCPを>>参照。

=== コア・プロバイダー

Cluster APIコアコントローラを実装する<<_provider,プロバイダを>>指します。管理クラスタにデプロイされなければならない最初のプロジェクトがCluster APIそのものであることを考えれば、Cluster APIプロジェクトがコアプロバイダとも呼ばれる理由は明らかでしょう。

<<_cluster_api,CAPIを>>参照。

== F

=== フリート

ifeval::["{build-type}" == "product"]
コンテナ管理およびデプロイ・エンジンで、ローカル・クラスターでより多くのコントロールをユーザーに提供し、GitOpsを通じて常時監視できるように設計されている。フリートについての詳細はhttps://documentation.suse.com/cloudnative/continuous-delivery/latest/en/index.html/[Fleet のドキュメントを]ご覧ください。
endif::[]
ifeval::["{build-type}" == "community"]
コンテナ管理およびデプロイ・エンジンで、ローカル・クラスターでより多くのコントロールをユーザーに提供し、GitOpsを通じて常時監視できるように設計されている。フリートについての詳細はhttps://fleet.rancher.io/[Fleet のドキュメントを]ご覧ください。
endif::[]

== I

=== インフラ・プロバイダー

クラスタまたはマシン（VM、ネットワークなど）が必要とするインフラストラクチャ/計算リソースのプロビジョニングを実施する<<_provider,プロバイダーを>>指す。
クラウド・インフラストラクチャ・プロバイダーには、AWS、Azure、Googleなどがあり、VMware、MAAS、metal3.ioなどはベアメタル・プロバイダーと定義できる。

=== IPAMプロバイダー

クラスタAPIをIPAMソリューションと相互作用させる<<_provider,プロバイダを>>指す。
IPAMプロバイダとCluster APIとのやりとりは、`+IPAddressClaim+` および`+IPAddress+` APIタイプに基づいている。

== K

=== Kubernetes-conformant

または*Kubernetes準拠*

Kubernetesの適合性テストに合格したクラスタ。

=== Kubernetes オペレーター

Kubernetes Operatorは、Kubernetesアプリケーションをパッケージング、デプロイ、管理する方法です。詳しくはhttps://kubernetes.io/docs/concepts/extend-kubernetes/operator/ 。

=== k/k

https://github.com/kubernetes/kubernetes[メインの Kubernetes git リポジトリ]、またはメインの Kubernetes プロジェクトを指します。

=== KCP

Kubeadm コントロール・プレーン・プロバイダー

== M

=== 機械

または*マシンリソース*

Kubernetesノードをホストするインフラストラクチャ・コンポーネントを表すKubernetes用のカスタムリソース。

=== クラスタの管理

クラスタの作成、スケール、アップグレード、または破棄操作を実行します。

=== マネージドKubernetes

マネージドKubernetesとは、Kubernetesクラスタのプロビジョニングとメンテナンスを抽象化したもので、通常はAPIとして公開され、クラウドプロバイダーでネイティブに利用可能なものを指す。例えばhttps://aws.amazon.com/eks/[EKS]例えば、、https://www.oracle.com/cloud/cloud-native/container-engine-kubernetes/[OKE]、https://azure.microsoft.com/en-us/products/kubernetes-service[] AKS、https://cloud.google.com/kubernetes-engine[] GKE、https://www.ibm.com/cloud/kubernetes-service[] IBM、https://www.digitalocean.com/products/kubernetes[Cloud Kubernetes Service] DOKSなど、Kubernetes Cloud Nativeエコシステム全体を通して多くのものがある。

=== マネージド・トポロジー

<<_topology,トポロジーを>>参照

=== 経営クラスタ

1つまたは複数のインフラストラクチャ・プロバイダが実行され、リソース（マシンなど）が保存されるクラスタ。通常、複数のワークロードクラスターをプロビジョニングする場合に参照される。

== N

=== ノードプール

ノードプールとは、クラスタ内のノードがすべて同じ構成を持つグループのことです。

== O

=== オペレーティングシステム

または*OS*

特定のディストリビューションではなく、LinuxやWindowsのようなカーネルとシステムレベルのユーザー空間インターフェースの一般的に理解される組み合わせ。

== P

=== ピボット

ピボットは、プロバイダコンポーネントと宣言されたクラスタAPIリソースをソース管理クラスタからターゲット管理クラスタに移動するプロセスです。

ピボット・プロセスは管理クラスターの削除にも使用され、管理クラスターのアップグレード時にも使用できる。

=== プロバイダー

または*クラスタAPIプロバイダ*

この用語はもともと<<_infrastructure_provider,インフラストラクチャ・プロバイダの>>略称として使われていましたが、現在はデプロイ可能でクラスタAPI管理クラスタに機能を提供するあらゆるプロジェクトを指すのに使われています。

<<_bootstrap_provider,ブートストラップ・プロバイダ>>、<<_control_plane_provider,コントロール・プレーン・プロバイダ>>、<<_core_provider,コア・プロバイダ>>、<<_infrastructure_provider,インフラストラクチャ・プロバイダ>>、<<_ipam_provider,IPAMプロバイダ>>、<<_runtime_extension_provider,ランタイム拡張プロバイダを>>参照のこと。

=== プロバイダーのコンポーネント

通常、カスタムリソース定義(CRD)、デプロイメント(コントローラマネージャの実行)、RBACなどが含まれます。

場合によっては、管理クラスタに配置された上記のコンポーネントのインスタンスを参照するために同じ表現が使用される。

<<_provider_repository,プロバイダー・リポジトリを>>参照

=== プロバイダーリポジトリ

<<_provider_components,プロバイダーコンポーネントの>>YAML がホストされる場所を指します。通常、プロバイダーリポジトリは多くのバージョンのプロバイダーコンポーネントをホストします。

== R

=== 牧場主

Kubernetes クラスタのデプロイと管理を簡素化するために設計された、オープンソースのhttps://www.rancher.com/[プラットフォーム]。

=== ランチャークラスターエージェント

Rancherが管理する各Kubernetesクラスタにデプロイされるコンポーネント。その主な役割は、RancherサーバーとKubernetesクラスターとの間に安全な通信チャネルを確立し、Rancherがクラスターを管理し対話できるようにすることです。

=== 牧場経営者

Rancher Manager（またはRancher Server）は、RancherのUIとAPIがホストされている場所で、<<_rancher_cluster_agent,Rancher Cluster Agentの>>ようなコンポーネントを通じて管理クラスタと通信します。これにより、ユーザーはKubernetesクラスター、アプリケーション、およびカタログ、ユーザー、グローバル・ロールなどのRancher固有のリソースを管理できる。

=== RKE2

ifeval::["{build-type}" == "product"]
Rancherの次世代Kubernetesディストリビューションは、米国内のセキュリティとコンプライアンスに完全に準拠している。連邦政府部門詳細はhttps://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html[のドキュメントを]参照。
endif::[]
ifeval::["{build-type}" == "community"]
Rancherの次世代Kubernetesディストリビューションは、米国内のセキュリティとコンプライアンスに完全に準拠している。連邦政府部門詳細はhttps://docs.rke2.io/[のドキュメントを]参照。
endif::[]

=== ランタイム・エクステンション

クラスタAPIの上に構築されたシステムの一部であり、特定のランタイムフックに対するリクエストを処理できる外部コンポーネント。

=== ランタイム・エクステンション・プロバイダ

1つ以上の<<_runtime_extension,ランタイム拡張を>>実装する<<_provider,プロバイダを>>指す。

== S

=== スケーリング

特に指定がない限り、これは水平方向のスケーリングを指す。

=== スタック制御プレーン

etcdがKubernetes APIサーバーとコロケーションされ、スタティックポッドとして実行されているコントロールプレーンノード。

=== サーバー

<<_machine,マシンリソースを>>バックアップするインフラストラクチャで、通常はクラウドインスタンス、仮想マシン、または物理ホストのいずれか。

=== {product_name}

Rancher ManagerとCluster API (CAPI)の統合を提供する<<_kubernetes_operator,Kubernetesオペレータで>>、Rancherに完全なCAPIサポートをもたらすことを目的としている。

== T

=== トポロジー

クラスタのコントロールプレーンとワーカーマシンの形状を単一の制御ポイントから定義し、管理することを可能にするクラスタオブジェクト仕様のフィールド。クラスタのトポロジーは<<_clusterclass,ClusterClassに基づいて>>います。
マネージド・トポロジーと呼ばれることもある。

<<_clusterclass,ClusterClassを>>参照。

ifeval::["{build-type}" == "product"]
=== カメ

とは <<_suse_rancher_prime_cluster_api,{product_name}>>
endif::[]

ifeval::["{build-type}" == "community"]
=== カメ

とは <<_rancher_turtles,{product_name}>>
endif::[]

== W

=== ワークロードクラスター

ClusterAPIコントローラによって作成されるクラスタで、ブートストラップクラスタでは_ありません_。

=== ワーカークラス

クラスタ内のワーカーノードのセットを定義するテンプレートのコレクション。ClusterClassには0個以上のWorkerClass定義が含まれます。

<<_clusterclass,ClusterClassを>>参照。
