include::partial$variables.adoc[]
:title: {project-name} artefactos
:description: Verifique los artefactos de {project-name} y acceda a los binarios relacionados, gráficos Helm, para una gestión eficaz de la seguridad.
:keywords: [artefactos, soporte, entrehierro, imágenes]
:doc-persona: [kubewarden-operator]
:doc-type: [referencia]
:doc-topic: [manual del operador, artefactos, registro, imágenes]

= {title}
:revdate: 2026-03-18
:page-revdate: {revdate}

== Verificación de {project-name}

Existe un tutorial sobre la xref:/tutorials/verifying-kubewarden.adoc[verificación] de xref:/tutorials/verifying-kubewarden.adoc[{short-project-name} en el que se muestra cómo verificar los artefactos de] {short-project-name}.

== Binarios

Nuestra herramienta `kwctl` CLI se publica a través de https://github.com/kubewarden/kwctl/releases[releases] GitHub.

== Artefactos OCI

Para los artefactos de la Open Container Initiative (OCI), el proyecto publica todo en `ghcr.io` bajo https://github.com/orgs/kubewarden/packages.

- https://github.com/orgs/kubewarden/packages/policies[`kubewarden/packages/policies/*`]
  son los artefactos Wasm OCI de la política.
- https://github.com/orgs/kubewarden/packages/charts[`kubewarden/packages/charts/*`]
  son los gráficos Helm como artefactos OCI. Siguen las normas de la SLSA.
- las imágenes de contenedores publicadas como imágenes OCI: `kubewarden-controller`, `policy-server`, `audit-scanner`, `kubectl`.
- también hay `packages/tests/*` que contiene artefactos utilizados en las pruebas e2e.

== Cartas de navegación a través de HTTPS

{short-project-name} publica gráficos Helm en el repositorio HTTPS de gráficos Helm enhttps://charts.kubewarden.io.. No tienen SLSA, ni firmas, pero este tipo de repositorio Helm proporciona búsquedas.
