include::partial$variables.adoc[]
= Modo monitor
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure ClusterAdmissionPolicies o AdmissionPolicies para el modo monitor para rastrear y analizar las acciones de las políticas sin modificar las peticiones entrantes.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "monitor-mode"]
:doc-type: ["reference"]
:keywords: ["kubernetes", "kubewarden", "monitor mode"]
:sidebar_label: Modo monitor
:sidebar_position: 50
:current-version: {page-origin-branch}

Al definir una política, se puede elegir entre dos modos, especificados en su etiqueta xref:reference/CRDs.adoc#admissionpolicyspec[`spec.mode`].
Por defecto, una política se despliega en `mode: protect`.
A continuación, la política acepta, rechaza o muta las solicitudes.

Se puede elegir desplegar una política en modo monitor. En modo monitor:

* La política acepta todas las solicitudes, como si la política no estuviera instalada.
* El `policy-server` traza la política normalmente. Si se rechaza una solicitud o una política propone una mutación, la traza contiene los detalles.
* Las métricas de `policy-server` se actualizan normalmente, con el modo incluido en el equipaje métrico. Por lo tanto, es fácil filtrar las políticas por modo y centrarse en las desplegadas utilizando el modo `monitor`.

`mode` es un atributo incluido en los recursos `ClusterAdmissionPolicy` y`AdmissionPolicy`. El atributo `mode` puede asumir dos valores: `monitor` y `protect`. Si se omite, el valor predeterminado de `mode` es `protect`.

Para crear una política en `monitor mode` es necesario incluir la declaración `mode: monitor` como parte de la especificación del recurso. Por ejemplo, en la sección`spec` (marcada con ➀), de este `ClusterAdmissionPolicy`:

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: psp-capabilities
spec:
  mode: monitor <1>
  policyServer: reserved-instance-for-tenant-a
  module: registry://ghcr.io/kubewarden/policies/psp-capabilities:v0.1.3
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    allowed_capabilities:
    - CHOWN
    required_drop_capabilities:
    - NET_ADMIN
----
<1> El atributo `mode: monitor` se encuentra en la sección `spec`.

== Cambiar el modo de política

Por motivos de seguridad, un usuario con permisos `UPDATE` sobre los recursos de la política puede hacer que ésta sea más restrictiva. Esto significa que puede cambiar el `mode` de un `ClusterAdmissionPolicy` o `AdmissionPolicy` existente de `monitor` a`protect`.

Sin embargo, no puede cambiar el `mode` de un `ClusterAdmissionPolicy` o`AdmissionPolicy` existente de `protect` a `monitor`.

Así, para cambiar el `mode` de una política de `protect` a `monitor`, es necesario eliminar la política y volver a crearla en el modo `monitor`. Cambiar una política de`protect` a `monitor` es lo mismo que borrar la política, por lo que este enfoque asume que el usuario tiene permisos de borrado de políticas.

== Nota sobre las políticas mutantes

La mutación de políticas en el modo `monitor` no realizará una mutación en el recurso.
En el modo `monitor` las políticas registran cuál habría sido su acción. También registran el parche de mutación que habrían producido en el modo `protect`.

[WARNING]
====
Cuando una política mutante está en modo `monitor`, las políticas posteriores evalúan un recurso sin cambios, y por tanto diferente, que cuando la política mutante está en modo`protect`.
====
