include::partial$variables.adoc[]
= Ruta de actualización
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Actualice su pila {project-name} utilizando estrategias de versionado compatibles y reglas de compatibilidad entre sus componentes.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["operator-manual", "upgrade-path"]
:doc-type: ["reference"]
:keywords: ["ruta de actualización", "soporte"]
:sidebar_label: Ruta de actualización
:sidebar_position: 20
:current-version: {page-origin-branch}

== {project-name} versionado de pilas

El proyecto {short-project-name} utiliza https://semver.org/[el versionado semántico] para definir la versión "pila" de todos sus componentes: la versión sigue el patrón`MAJOR.MINOR.PATCH`. La versión compatible es la más reciente.

Los componentes de {short-project-name} que siguen las normas de la versión "pila" son:

* `kubewarden-crds` en su campo appVersion.

* `kubewarden-controller` en su campo appVersion.

* `kubewarden-defaults` en su campo appVersion.

* `policy-server` etiqueta de imagen para las desplegadas manualmente. El recurso para el predeterminado ya está gestionado por el gráfico `kubewarden-defaults`.

* `kwctl` binario.

== Compatibilidad de versiones de pila entre componentes

El gráfico `kubewarden-crds`, el gráfico `kubewarden-controller`, el gráfico`kubewarden-defaults`, cualquier imagen `policy-server` desplegada manualmente y`kwctl` deben ejecutar la misma versión `MAJOR`.`MINOR`.`PATCH`.

Por lo tanto, si la versión de `kubewarden-controller` que se está ejecutando es `1.1.2`, la versión`` de \policy-server+s`` y +`kwctl`+ en uso también debería ser`+1.1.2`.

== Versiones de la carta del timón

Los cuadros de mando definen el campo `version` y el campo `appVersion`. El campo`appVersion` informa de la versión de la "pila" {short-project-name}, como ya se ha mencionado. El campo `version` también sigue https://semver.org/[semantic versioning] y describe cambios compatibles con versiones anteriores en las plantillas de gráficos y `values.yaml`.

== Vías de actualización

Al actualizar componentes, puede actualizar varias versiones de la pila `PATCH` en una sola operación. Sin embargo, *no* es posible actualizar varias versiones de `MAJOR` o `MINOR` en una sola actualización.

Por ejemplo, puede actualizar componentes de la versión `1.1.10` a `1.1.nn` en una sola actualización. Pero la actualización de `1.1.10` a `1.5.0` no está soportada. En estos casos, deberá actualizar individualmente cada versión de `MAJOR`/`MINOR` entre las dos versiones. Por lo tanto, es necesario actualizar `1.1.10` a`1.2.0` luego `1.3.0` luego `1.4.0` y finalmente a `1.5.0`. Para actualizar una versión de`MAJOR` a otra, es necesario aplicar todas las actualizaciones de `MINOR` entre las dos versiones de `MAJOR`.

.Ejemplo de gráfico de soporte de la ruta de actualización
[mermaid]
....
%%{init: "theme": "neutral"}%% diagrama de flujo LR; accTitle: Gráfico de soporte de ruta de actualización accDescr: Un diagrama que muestra las rutas de actualización recomendadas y compatibles para {short-project-name}.
  1.0.0(1.0.0)-->1.0.1(1.0.1); 1.0.1-->1.0.2(1.0.2); 1.0.2-->1.1.0(1.1.0); 1.1.0-->1.1.2(1.1.2); 1.1.0-->1.1.1; 1.1.1-->1.1.2; 1.1.2-->|No recomendado|1.2.0(1.2.0); 1.0.2-->|No recomendado|1.2.0(1.2.0); 1.1.2-->1.2.1(1.2.1); 1.2.0-->1.2.1; linkStyle 6 color:marron,stroke-width:2px,stroke-dasharray: 3 5
  linkStyle 7 color:red,stroke-width:2px,stroke-dasharray: 3 5
....

== Pedido de actualización

{short-project-name} los usuarios deben actualizar la pila empezando por el gráfico `kubewarden-crds`y, a continuación, el gráfico `kubewarden-controller`. Después de eso, actualice el`policy-server` (a través de `kubewarden-defaults` gráfico o bumping las imágenes de los personalizados) y `kwctl`.

== Rebajas

Los downgrades *no* son compatibles y {short-project-name} no los prueba. No obstante, existe una expectativa razonable de que funcionen.

== SDK, políticas

Los SDK de políticas para los distintos idiomas y políticas mantenidos por el equipo de{short-project-name} siguen su propio versionado semántico. {short-project-name} es compatible con la última versión. No hay necesidad de una ruta de actualización para ellos, sólo un salto a la última versión.

Los cambios en la pila {short-project-name} pueden implicar que las políticas y los SDK reciban actualizaciones para utilizar las últimas funciones de {short-project-name}. {short-project-name} se encarga de realizar estas actualizaciones de forma compatible con versiones anteriores.

Por ejemplo, una versión menor de {short-project-name} que añada soporte para Audit Scanner (`v1.7.0`) significa que las políticas ganaron un nuevo campo `spec.backgroundAudit`. Es opcional, compatible con versiones anteriores y está configurado por defecto en `true`.
