include::partial$variables.adoc[]
:description: Configure los formatos de configuración de verificación para la firma segura de imágenes de contenedor utilizando un servidor de políticas o una política para verificar la procedencia y las firmas.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operador-manual", "verificación-configuración"]
:doc-type: ["reference"]
:doctype: book
:keywords: ["kubewarden", "kubernetes", "verification configuration"]
:current-version: {page-origin-branch}

= Formato de configuración de la verificación
:revdate: 2026-03-18
:page-revdate: {revdate}

== Introducción

Puede utilizar el formato `verification-config` con:

* `policy-server` verificar la procedencia de los módulos de política
* `verify-image-signatures` política para verificar la procedencia de las imágenes de clúster

Más información en xref:/howtos/security-hardening/secure-supply-chain.adoc[Cadena de suministro segura].

== Formato

La configuración tiene 2 claves raíz:

* `allOf`: Debe satisfacer toda la información de verificación que aparece aquí para verificar que las imágenes del contenedor están firmadas.
* `anyOf`: Debe satisfacer al menos `anyOf.minimumMatches` de toda la información de verificación enumerada para aceptar una imagen de contenedor como firmada.

Estas dos claves raíz aceptan una matriz de claves de tipo `kind`. A continuación figura una lista completa de las claves aceptadas en función de los distintos casos de uso:

* `pubKey`: Para firmas realizadas con criptografía tradicional de clave pública/privada.
* `githubAction`: Para las firmas realizadas con el flujo de trabajo sin claves de Sigstore dentro de GitHub Actions. {short-project-name} comprueba esta información con la extensión del certificado x509 `workflow_repository` creado por el OpenID Connect de GitHub, y no solo con los `issuer` y `subject`. Deberías usar este `kind`si trabajas con Acciones de GitHub.
* `genericIssuer`: Para firmas realizadas con el flujo de trabajo sin clave de Sigstore, en el que el usuario necesita validar el certificado `issuer` y `subject` por sí mismo. Acepta un `subject`, que puede ser:

** `equal`: El valor introducido debe coincidir exactamente con `subject` en el certificado de firma.
** `urlPrefix`: El valor introducido se fija con `/` para evitar errores tipográficos y debe ser un prefijo de `subject` en el certificado de firma.

La clave `kind` acepta una clave opcional `annotations`, con una lista de valores clave, que debe estar presente en la firma.

== Ejemplo

Este es un ejemplo de configuración para verificar firmas utilizando el flujo de trabajo Sigstore:

[subs="+attributes",yaml]
----
---
apiVersion: v1

allOf:
  - kind: githubAction
    owner: kubewarden   # mandatory
    repo: policy-server # optional
    annotations:  # optional
      env: prod

anyOf: # at least `anyOf.minimumMatches` are required to match
  minimumMatches: 2 # default is 1
  signatures:
  - kind: pubKey
    owner: alice # optional
    key: | # mandatory
         -----BEGIN PUBLIC KEY-----
         MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQiTy5S+2JFvVlhUwWPLziM7iTM2j
         byLgh2IjpNQN0Uio/9pZOTP/CsJmXoUNshfpTUHd3OxgHgz/6adtf2nBwQ==
         -----END PUBLIC KEY-----
    annotations:  # optional
      env: prod
  - kind: genericIssuer
    issuer: https://github.com/login/oauth
    subject:
      equal: alice@example.com
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      equal: https://github.com/bob/app-example/.github/workflows/release.yml@refs/heads/main
    annotations:  # optional
      env: prod
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/bob # <- it will be post-fixed with `/` for security reasons
----

== Referencia de configuración de la firma

Puede validar los requisitos de firma contenidos en un fichero. Amplíe para ver un ejemplo:

.Un fichero de requisitos de firma
[%collapsible]
====
[subs="+attributes",yaml]
----
apiVersion: v1

allOf:
  - kind: githubAction
    owner: kubewarden   # mandatory
    annotations:
      env: prod

anyOf: # at least `anyOf.minimumMatches` are required to match
  minimumMatches: 2 # default is 1
  signatures:
  - kind: pubKey
    owner: flavio # optional
    key: .... # mandatory
    annotations:  # optional
      env: prod
      foo: bar
  - kind: pubKey
    owner: victor # optional
    key: .... # mandatory
  - kind: genericIssuer
    issuer: https://github.com/login/oauth
    subject:
      equal: alice@example.com
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      equal: https://github.com/flavio/policy-secure-pod-images/.github/workflows/release.yml@refs/heads/main
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/flavio/
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/kubewarden # <- it will be post-fixed with `/` for security reasons
  - kind: githubAction
    owner: flavio   # mandatory
    repo: policy1 # optional
  - kind: pubKey
    owner: alice # optional
    key: .... # mandatory
----
====


=== Validación de firmas

La configuración anterior contiene las dos secciones, `allOf` y `anyOf`:

* `allOf`: Sólo se confía en la política si todos los requisitos de firma son válidos.
* `anyOf`: Confía en la póliza si el criterio `minimumMatches` es válido.

En el ejemplo, el campo `minimumMatches` es 2. Por tanto, debe cumplir al menos dos de los requisitos de la firma. El valor por defecto del campo `minimumMatches`es `1`.

Para la validación de firmas, debe cumplir todos los requisitos de `allOf` *y* el número mínimo de `anyOf`.

=== Validación de clave pública

Para comprobar que una política tiene la firma de clave pública correcta, hay que especificar los datos de la clave y el propietario de la misma. En este ejemplo, se establece `kind` a `pubKey` y el `key` tiene la clave pública. El campo propietario es opcional, pero puede ser útil para aclarar a quién pertenece la clave.

[subs="+attributes",yaml]
----
  - kind: pubKey
    owner: bob # optional
    key: |
      -----BEGIN PUBLIC KEY-----
      MBFKHFDGHKIJH0CAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbDE6HJSGAVD
      BVDF6SKFSF87AASUspkQsN3FO4iyWodCy5j3o0CdIJD/KJHDJFHDFIu6sA==
      -----END PUBLIC KEY-----
----

=== Validación de firmas sin claves

Una política firmada en modo sin clave no tiene una clave pública que se pueda verificar. Puede seguir verificando la política con los datos de OpenID Connect (OIDC) utilizados durante el proceso de firma. Para ello, es necesario definir la validación de la firma como`genericIssuer`.

Es posible verificar la información de la firma:

* `issuer`(obligatorio): coincide con el atributo `Issuer` del certificado generado por Fulcio. Muestra el OIDC utilizado para firmar la política.
* `subject`campo utilizado para coincidir con el atributo `Subject` del certificado de Fulcio. El campo `Subject` (Fulcio) contiene el usuario utilizado para autenticarse contra el proveedor OIDC. El campo de verificación, `subject`, puede tener uno de dos subcampos:

** `equal`: el `Subject` (Fulcio) del certificado debe ser igual al valor en la validación de la firma;
** `urlPrefix`: el valor del campo `Subject` (Fulcio) del certificado debe ir precedido del valor definido en la validación de la firma.

[NOTE]
====

Tanto `cosign verify` como `kwctl inspect` pueden mostrar información sobre firmas sin llave.

====


Por ejemplo, esta configuración significa que la política debe tener una firma sin clave de Alice utilizando el OIDC de GitHub:

[subs="+attributes",yaml]
----
- kind: genericIssuer
  issuer: https://github.com/login/oauth
  subject:
    equal: alice@example.com
----

Esta configuración necesita la política firmada en acciones de GitHub, desde un repositorio propiedad del usuario de GitHub `flavio`:

[subs="+attributes",yaml]
----
- kind: genericIssuer
  issuer: https://token.actions.githubusercontent.com
  subject:
    urlPrefix: https://github.com/flavio
----

=== Verificación de la firma de las acciones de GitHub

El "tipo", `githubAction` es para validar políticas firmadas en GitHub Actions.
También puede hacerlo con el tipo `genericIssuer`. Para simplificar el proceso de solicitud de firma, utilice dos campos adicionales para `githubAction`:

* `owner` (obligatorio): ID de GitHub del usuario u organización en el que confiar.
* `repo`: El nombre del repositorio en el que confiar.

Por ejemplo, el último fragmento, utilizando `genericIssuer`, podría reescribirse como:

[subs="+attributes",yaml]
----
- kind: githubAction
  owner: flavio
----

=== Validación de anotaciones de firma

Todos los tipos de firma pueden tener otros campos de validación opcionales, `annotations`.
Estos campos son datos clave/valor añadidos durante el proceso de firma.

Con {short-project-name}, puede verificar que las firmas de las políticas proceden de usuarios de confianza *y*tienen anotaciones específicas.

La siguiente validación comprueba dos condiciones para la política:

* que está firmado con una clave específica
* tiene una anotación de entorno de producción.

[subs="+attributes",yaml]
----
- kind: pubKey
  key: |
    -----BEGIN PUBLIC KEY-----
    MBFKHFDGHKIJH0CAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbDE6HJSGAVD
    BVDF6SKFSF87AASUspkQsN3FO4iyWodCy5j3o0CdIJD/KJHDJFHDFIu6sA==
    -----END PUBLIC KEY-----
  annotations:
    environment: production
----

=== Uso de un archivo de configuración de verificación de firmas para comprobar un artefacto OCI de política

Puede comprobar si una política pasa la verificación utilizando el archivo de configuración de verificación. Utilice el indicador `--verification-config-path` del comando `kwctl verify`.

[subs="+attributes",console]
----
$ cat signatures_requirements.yaml
apiVersion: v1
allOf:
  - kind: pubKey
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5Q+cN1Jj2S7N05J4AXnqwP2DyzSg
      Mc+raYce2Wthrd30MSgFtoh5ADAkCd/nML2Nx8UD9KBuASRb0gG5jXqgMQ==
      -----END PUBLIC KEY-----

$ kwctl verify --verification-config-path signatures_requirements.yaml ghcr.io/kubewarden/policies/user-group-psp:latest
2022-03-29T17:34:37.847169Z  INFO kwctl::verify: Policy successfully verified
----

Este último ejemplo comprueba si una política determinada procede de la organización {short-project-name}:

[subs="+attributes",console]
----
$ cat kubewarden_signatures.yaml
apiVersion: v1
allOf:
  - kind: githubAction
    owner: kubewarden

$ kwctl verify --verification-config-path kubewarden_signatures.yaml ghcr.io/kubewarden/policies/user-group-psp:latest
2022-03-29T18:07:39.062292Z  INFO kwctl::verify: Policy successfully verified
----
