include::partial$variables.adoc[]
= Distribuição de políticas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Distribua políticas com segurança por meio de um registro compatível com OCI usando ferramentas como o kwctl e garanta a segurança do cluster por meio do gerenciamento de políticas do {project-name}.
:doc-persona: ["kubewarden-operator", "kubewarden-policy-developer", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["distributing-policies"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "oci", "kubewarden", "policy", "wasm", "webassembly"]
:current-version: {page-origin-branch}

{project-name} As políticas são binários do WebAssembly (Wasm) avaliados pelo {short-project-name} Policy Server.

O servidor de políticas {short-project-name} carrega políticas a partir dessas fontes:

* Sistema de arquivos local
* Servidor HTTP(s)
* Registros em conformidade com a OCI:
 ** https://github.com/distribution/distribution[Distribuição]
 ** https://ghcr.io[Registro de contêineres do GitHub]
 ** https://azure.microsoft.com/en-us/products/container-registry/[Registro de contêineres do Azure]
 ** https://aws.amazon.com/ecr/[Amazon ECR]
 ** https://cloud.google.com/artifact-registry/[Registro de contêineres do Google]

{short-project-name} recomenda a distribuição das políticas do {short-project-name} por meio de um registro regular em conformidade com a OCI. Os registros de contêineres são um requisito obrigatório para qualquer cluster do Kubernetes. É vantajoso ter um único local para armazenar e proteger todos os artefatos exigidos por um cluster.

== Enviar políticas para um registro compatível com OCI

A especificação https://github.com/opencontainers/image-spec[do formato de imagem]OCI permite armazenar qualquer blob binário dentro de um registro de contêiner regular compatível com OCI.

O registro de destino em conformidade com a OCI *deve suportar artefatos* para enviar com êxito uma política {short-project-name} para ele.

Você pode usar a https://github.com/kubewarden/kwctl[`kwctl`] CLI para enviar uma política{short-project-name} para um registro compatível com OCI.

== Anotação da política

Você também anota uma política com `kwctl`. A anotação de uma política do {short-project-name}é feita adicionando seções personalizadas do Wasm ao binário da política. Isso significa que a política empacota seus próprios metadados.

O comando `kwctl annotate` requer duas entradas:

* a política {short-project-name} a ser anotada, um arquivo local no sistema de arquivos.
* o arquivo de anotações, um arquivo que contém uma descrição YAML dos metadados da política.
Esse arquivo geralmente está localizado na pasta raiz do projeto de sua política.

Por exemplo, você pode salvar esse arquivo como `metadata.yml` no diretório atual:

[subs="+attributes",yaml]
----
rules:
- apiGroups: ["*"]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["*"]
mutating: false
annotations:
  io.kubewarden.policy.title: palindromify
  io.kubewarden.policy.version: 0.1.0
  io.kubewarden.policy.description: Allows you to reject palindrome names in resources and namespace names, or to only accept palindrome names
  io.kubewarden.policy.author: Name Surname <name.surname@example.com>
  io.kubewarden.policy.url: https://github.com/<org>/palindromify
  io.kubewarden.policy.source: https://github.com/<org>/palindromify
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
    This is markdown text and as such allows you to define a free form usage text.

    This policy allows you to reject requests if:
    - The name of the resource is a palindrome name.
    - The namespace name where this resource is created has a palindrome name.

    This policy accepts the following settings:

    - `invert_behavior`: bool that inverts the policy behavior. If enabled, only palindrome names will be accepted.
----

Agora, vamos anotar a política:

[subs="+attributes",shell]
----
$ kwctl annotate policy.wasm \
    --metadata-path metadata.yml \
    --output-path annotated-policy.wasm
----

O processo de anotação realiza determinadas otimizações na política, de modo que, muitas vezes, a política anotada é menor que a original. Isso depende consideravelmente da cadeia de ferramentas usada para produzir o objeto Wasm original.

[IMPORTANT]
====

.Use o kwctl inspect para verificar sua política
[%collapsible]
======

[subs="+attributes",shell]
----
$ kwctl inspect annotated-policy.wasm
2023-08-24T12:06:27.986401Z  INFO sigstore::cosign::client_builder: Rekor public key not provided. Rekor integration disabled
2023-08-24T12:06:27.986449Z  INFO sigstore::cosign::client_builder: No Fulcio cert has been provided. Fulcio integration disabled
Details
title:                    palindromify
description:              Allows you to reject palindrome names in resources and namespace names, or to only accept palindrome names
author:                   Name Surname <name.surname@example.com>
url:                      https://github.com/<org>/palindromify
source:                   https://github.com/<org>/palindromify
license:                  Apache-2.0
mutating:                 false
background audit support: true
context aware:            false
execution mode:           kubewarden-wapc
protocol version:         1

Annotations
io.kubewarden.kwctl       1.7.0-rc2

Rules
────────────────────
- apiGroups:
  - '*'
  apiVersions:
  - '*'
  resources:
  - '*'
  operations:
  - '*'
────────────────────

Usage
This is markdown text and as such allows you to define a free form usage text.

This policy allows you to reject requests if:

• The name of the resource is a palindrome name.
• The namespace name where this resource is created has a palindrome name.

This policy accepts the following settings:

• invert_behavior: bool that inverts the policy behavior. If enabled, only palindrome names will be accepted.

Cannot determine if the policy has been signed. There was an error while attempting to fetch its signatures from the remote registry: invalid uri
----

======
====


== Impulsionando a política

Você pode enviar uma política anotada como esta:

[subs="+attributes",shell]
----
$ kwctl push annotated-policy.wasm \
     <oci-registry>/kubewarden-policies/palindromify-policy:v0.0.1
----

Não é recomendável promover políticas não anotadas. O servidor de políticas usa os metadados fornecidos pelas anotações para executar corretamente uma política. Por padrão, o site`kwctl push` se recusa a enviar essa política para um registro OCI. Se você precisar de uma política não anotada, use o sinalizador `-&#x200D;-&#x200D;force` de `kwctl push`.

Você pode fazer referência a uma política do {short-project-name} Policy Server ou `kwctl` como`registry://<oci-registry>/kubewarden-policies/palindromify-policy:v0.0.1`.
