include::partial$variables.adoc[]
= Políticas mutantes
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Reconstrua solicitações configurando e gerenciando políticas de mutação dentro de ClusterAdmissionPolicy de acordo com configurações predefinidas.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["mutating-policies"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "policy mutating", "kubernetes", "clusteradmissionpolicy", "admissionpolicy"]
:sidebar_label: Políticas mutantes
:sidebar_position: 10
:current-version: {page-origin-branch}

As políticas de mutação recebem uma solicitação de objeto e a reconstroem (transformam-na) em uma nova solicitação. Isso está de acordo com os valores definidos nas configurações da política. A solicitação passa pela API do Kubernetes, podendo ser avaliada por outras políticas.

Para permitir a alteração do comportamento da solicitação, defina o campo `ClusterAdmissionPolicy.mutating`como `true`.

No entanto, se você definir o campo `ClusterAdmissionPolicy.mutating` como `false`, as solicitações alteradas serão rejeitadas.

== Por que a mutação de políticas pode ser perigosa

=== Políticas mutantes não revisadas podem introduzir vulnerabilidades

[WARNING]
====

Para evitar abuso do sistema, os administradores do {project-name} devem revisar as políticas de mutação. As políticas mutantes podem, por exemplo, modificar uma carga de trabalho, de modo que ela permita a criação de contêineres privilegiados.

====


==== Solução

Em caso de dúvida, divida as políticas em políticas de mutação e validação, em vez de escrever ou implantar políticas que validam e mutam. Isso é particularmente importante quando se usa uma DSL (como a Rego) para criar políticas complexas.

=== Políticas de mutação mal configuradas, juntamente com controladores Kubernetes de terceiros, podem ficar presas em um loop infinito

[WARNING]
====

As políticas de mutação retornam solicitações que passam pela API do Kubernetes. Se houver outros controladores do Kubernetes que escutam esses mesmos recursos, eles poderão mutá-los de volta em uma solicitação de acompanhamento. Isso pode levar a um ciclo de feedback infinito de mutações.

====


==== Solução

Executar a mutação contra:

. O tipo inferior de recurso (por exemplo Pod).
. O tipo mais alto de recurso (por exemplo Implantação). Observação: isso ainda pode levar a loops se um controlador estiver gerenciando esses recursos. Por exemplo, controladores de soluções GitOps (como fleet, flux, argo, ...) ou outros controladores de terceiros que traduzem seus próprios CRDs em objetos de implantação.

== Exemplos

Você pode ver uma política mutante em ação. Crie o seguinte`ClusterAdmissionPolicy` com o campo `mutating` definido como `true`:

[subs="+attributes",bash]
----
# Command
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: psp-user-group
spec:
  module: "registry://ghcr.io/kubewarden/policies/user-group-psp:v0.1.5"
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    run_as_user:
      rule: "MustRunAs"
      ranges:
        - min: 1000
          max: 2000
        - min: 3000
          max: 4000
    run_as_group:
      rule: "RunAsAny"
    supplemental_groups:
      rule: "RunAsAny"
EOF

# Output
clusteradmissionpolicy.policies.kubewarden.io/psp-user-group created
----

Você usa a políticahttps://github.com/kubewarden/user-group-psp-policy[`psp-user-group`] para controlar usuários e grupos em contêineres e pode alterar as solicitações. No exemplo anterior, você definiu o campo `runAsUser` e ele foi adicionado à seção do contêiner `securityContext`.

Como o campo `mutating` é `true`, a solicitação a seguir é bem-sucedida:

[subs="+attributes",bash]
----
# Command
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: pause-user-group
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause
EOF

# Output
pod/pause-user-group created
----

Você pode ver os resultados do contêiner `securityContext`:

[subs="+attributes",bash]
----
# Command
kubectl get pods pause-user-group -o jsonpath='{ .spec.containers[].securityContext }'

# Output
{"runAsUser":1000}
----

Agora, modifique o site `ClusterAdmissionPolicy` definindo o campo `mutating` para `false`:

[subs="+attributes",bash]
----
# Command
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: psp-user-group
spec:
  module: "registry://ghcr.io/kubewarden/policies/user-group-psp:v0.1.5"
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
  settings:
    run_as_user:
      rule: "MustRunAs"
      ranges:
        - min: 1000
          max: 2000
        - min: 3000
          max: 4000
    run_as_group:
      rule: "RunAsAny"
    supplemental_groups:
      rule: "RunAsAny"
EOF

# Output
clusteradmissionpolicy.policies.kubewarden.io/psp-user-group configured
----

Como o campo `mutating` é `false`, a solicitação a seguir falha:

[subs="+attributes",bash]
----
# Command
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: pause-user-group
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause
EOF

# Output
Error from server: error when creating ".\\pause-user-group.yaml": admission webhook "psp-user-group.kubewarden.admission" denied the request: Request rejected by policy psp-user-group. The policy attempted to mutate the request, but it is currently configured to not allow mutations.
----

Concluindo, você pode ver que o site {short-project-name} replica o mesmo comportamento que as políticas de segurança de pod (PSP) do Kubernetes obsoletas.
