include::partial$variables.adoc[]
= Grupos de políticas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprenda a criar políticas complexas combinando outras mais simples por meio de grupos de políticas, especificamente usando as definições de AdmissionPolicyGroup e ClusterAdmissionPolicyGroup.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["explanations", "policy-group"]
:doc-type: ["explanation"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "policy groups", "clusteradmissionpolicygroup", "admissionpolicygroup"]
:sidebar_label: Grupos de políticas
:sidebar_position: 21
:current-version: {page-origin-branch}

O recurso de grupo de políticas permite que os usuários criem políticas complexas combinando outras mais simples. Ele apresenta duas novas definições de recursos personalizados (CRDs):

* `AdmissionPolicyGroup`para políticas de admissão que se aplicam a namespaces específicos.
* `ClusterAdmissionPolicyGroup`para políticas de admissão que se aplicam a todo o cluster.

Esses grupos de políticas permitem que os usuários usem políticas existentes, reduzindo a necessidade de criação de políticas personalizadas e aumentando a reutilização. Ao evitar a duplicação da lógica da política, os usuários podem simplificar o gerenciamento e criar políticas personalizadas com uma configuração semelhante à DSL.

Os grupos de políticas permitem a avaliação combinada de várias políticas usando operadores lógicos. Isso permite a definição de uma lógica complexa. No entanto, enquanto as políticas comuns podem incluir lógica de mutação para modificar recursos durante a admissão, os grupos de políticas só fazem validação.

A configuração dos grupos de políticas é semelhante à das políticas comuns. A diferença é o acréscimo dos campos `expression`, `message` e `policies`e a declaração de regras com reconhecimento de contexto em um local diferente.

Este é um exemplo de um `ClusterAdmissionPolicyGroup` que pode ser usado nas próximas seções para explicar os diferentes campos:

.Um `ClusterAdmissionPolicyGroup` que rejeita Pods que usam imagens com a tag `latest`, a menos que as imagens sejam assinadas por duas partes confiáveis: Alice e Bob.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  policies:
    signed_by_alice:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
                yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
                -----END PUBLIC KEY-----
    signed_by_bob:
      module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
      settings:
        modifyImagesWithDigest: false
        signatures:
          - image: "*"
            pubKeys:
              - |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X
                urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==
                -----END PUBLIC KEY-----
    reject_latest:
      module: registry://ghcr.io/kubewarden/policies/trusted-repos:v0.2.0
      settings:
        tags:
          reject:
            - latest
  expression: "reject_latest() || (signed_by_alice() && signed_by_bob())"
  message: "the image is using the latest tag or is not signed by Alice and Bob"
----
======

== Principais campos de configuração

Esta seção aborda os principais campos de configuração de um grupo de políticas.

=== O atributo `policies` 

O campo policies é um mapa de políticas comuns. O site {project-name} chama as políticas pelo grupo de políticas, para determinar se aceita ou rejeita o recurso em avaliação. As definições dessas políticas são uma versão simplificada das políticas comuns de {short-project-name}, contendo apenas os atributos `module`, `settings` e`contextAwareResources`. Esses elementos são necessários para que as políticas funcionem em um grupo de políticas.

Um nome exclusivo identifica cada política da política de grupo. Por exemplo, o snippet a seguir define três políticas: `signed_by_alice`, `signed_by_bob`e `reject_latest_tag`.

[,yaml]
----
policies:
  signed_by_alice:
    module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
    settings: {} # settings for the policy
  signed_by_bob:
    module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
    settings: {} # settings for the policy
  reject_latest_tag:
    module: ghcr.io/kubewarden/policies/trusted-repos-policy:v0.2.0
    settings: {} # settings for the policy
----

[TIP]
====

Um grupo de políticas pode incluir a mesma política várias vezes com configurações diferentes.

====


=== O atributo `expression` 

O atributo `expression` contém uma declaração composta pelos identificadores de política unidos por operadores lógicos.

A avaliação da instrução `expression` deve ser avaliada como um valor booleano.

A representação de políticas é como uma função nomeada após o identificador especificado no mapa `.spec.policies`. Os resultados produzidos pela avaliação das políticas são então avaliados usando os operadores lógicos fornecidos pelo usuário.

Esses são os operadores suportados:

* `&&`: usado para executar as operações do `AND` 
* `||`: usado para executar as operações do `OR` 
* `!`: usado para executar as operações do `NOT` 

Você pode usar colchetes `( )` para definir as prioridades de avaliação.

Por exemplo, dada a seguinte expressão:

[,console]
----
reject_latest() || (signed_by_alice() && signed_by_bob())
----

A política rejeita cargas de trabalho que tenham imagens usando a tag `latest`, a menos que Alice e Bob tenham assinado as imagens.

=== O atributo `message` e o formato de resposta

O campo `message` especifica a mensagem retornada quando a avaliação do`expression` resulta em uma rejeição. A resposta inclui a mensagem, juntamente com os resultados da avaliação das políticas individuais.

[IMPORTANT]
====

A avaliação das políticas que pertencem ao grupo ocorre somente se necessário.

Por exemplo, dada a seguinte expressão:

[,console]
----
reject_latest() || (signed_by_alice() && signed_by_bob())
----

As políticas `signed_by_bob` e `signed_by_alice` não são avaliadas quando a política`reject_latest` retorna `true`.

Da mesma forma, a política `signed_by_bob` não é avaliada se as políticas`signed_by_alice` e `reject_latest` retornarem `false`.

Isso evita avaliações desnecessárias de políticas no grupo e garante respostas rápidas às solicitações de admissão.

====

O sistema envia todos os detalhes de avaliação das políticas de grupo como parte do AdmissionResponse `.status.details.causes` quando uma política de grupo realiza uma rejeição.

Você pode obter detalhes completos de uma solicitação de admissão rejeitada aumentando o nível de verbosidade de `kubectl`:

[,shell]
----
kubectl -v4 apply -f signed-pod.yml
I0919 18:29:40.251332    4330 helpers.go:246] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"signed-pod.yml\": admission webhook \"clusterwide-demo.kubewarden.admission\" denied the request: the image is using the latest tag or is not signed by Alice and Bob",
  "details": {
    "causes": [
      {
        "message": "Resource signed is not accepted: verification of image testing.registry.svc.lan/busybox:latest failed: Host error: Callback evaluation failure: Image verification failed: missing signatures\nThe following constraints were not satisfied:\nkind: pubKey\nowner: null\nkey: |\n  -----BEGIN PUBLIC KEY-----\n  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswA3Ec4w1ErOpeLPfCdkrh8jvk3X\n  urm8ZrXi4S3an70k8bf1OlGnI/aHCcGleewHbBk1iByySMwr8BabchXGSg==\n  -----END PUBLIC KEY-----\nannotations: null\n",
        "field": "spec.policies.signed_by_bob"
      },
      {
        "message": "not allowed, reported errors: tags not allowed: latest",
        "field": "spec.policies.reject_latest"
      }
    ]
  },
  "code": 400
}]
Error from server: error when creating "signed-pod.yml": admission webhook "clusterwide-demo.kubewarden.admission" denied the request: the image is using the latest tag or is not signed by Alice and Bob
----

A resposta de admissão completa está disponível nos registros do Servidor de políticas quando executado no modo de depuração. Além disso, os detalhes da avaliação sempre fazem parte dos rastros do OpenTelemetry emitidos pelo Policy Server.

== Políticas com reconhecimento de contexto

Outra distinção entre os grupos de políticas e as políticas comuns é o local de definição das regras de recursos com reconhecimento de contexto. Cada política em um grupo aceita um campo opcional `contextAwareResources` para especificar os recursos que a política pode acessar durante a avaliação. Da mesma forma que as políticas comuns, você só pode usar recursos com reconhecimento de contexto definindo um`ClusterAdmissionPolicyGroup`. Isso ocorre por motivos de segurança, pois somente usuários sem privilégios podem implementar recursos do `AdmissionPolicyGroup`. Para obter mais detalhes, consulte a documentaçãoxref:explanations/context-aware-policies.adoc[sobre políticas com reconhecimento de contexto].

.Um exemplo de um grupo de políticas que usa uma política com reconhecimento de contexto.
[%collapsible]
======
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicyGroup # or AdmissionPolicyGroup
metadata:
  name: demo-ctx-aware
spec:
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - services
      operations:
        - CREATE
        - UPDATE
  policies:
    unique_service_selector:
      module: registry://ghcr.io/kubewarden/policies/unique-service-selector-policy:v0.1.0
      contextAwareResources:
        - apiVersion: v1
          kind: Service
      settings:
        app.kubernetes.io/name: MyApp
    owned_by_foo_team:
      module: registry://ghcr.io/kubewarden/policies/safe-annotations:v0.2.9
      settings:
        mandatory_annotations:
          - owner
        constrained_annotations:
          owner: "foo-team"
  expression: "unique_service_selector() || (!unique_service_selector() && owned_by_foo_team())"
  message: "the service selector is not unique or the service is not owned by the foo team"
----
======

No exemplo anterior, a política `unique_service_selector` pode acessar o recurso`Service`. No entanto, o `owned_by_foo_team` não tem acesso aos recursos do Kubernetes.

== Validação de configurações

Quando o servidor de políticas é iniciado, ele valida as configurações dos grupos de políticas e das políticas comuns. No entanto, os grupos de políticas passam por uma etapa de validação adicional para verificar se a expressão é válida e se é avaliada como um valor booleano.

== Scanner de auditoria

Semelhante aos CRDs AdmissionPolicy e ClusterAdmissionPolicy, o campo`backgroundAudit` indica se o grupo de políticas deve ser incluído durantexref:../explanations/audit-scanner/audit-scanner.adoc[as verificações de auditoria].

== Servidor de políticas

Você pode estender o arquivo de configurações `policies.yml` para incluir grupos de políticas juntamente com políticas comuns. Assim como nas políticas comuns, o download dos módulos ocorre uma vez. Você usa o mesmo módulo de política em um grupo de políticas e em uma política comum.
