= Profil des ressources
:page-languages: [en, ja, ko, zh]
:revdate: 2025-01-06
:page-revdate: {revdate}

Cette section présente les résultats des tests visant à déterminer les ressources minimales requises pour les K3.

== Ressources minimales requises pour les K3

Les résultats sont résumés comme suit :

|===
| Composants | Processeur | Min CPU | RAM minimum avec Kine/SQLite | RAM minimale avec etcd intégré

| Serveur K3s avec une charge de travail
| Intel 8375C CPU, 2,90 GHz
| 6 % d'un noyau
| 1596 M
| 1606 M

| Cluster K3s avec un seul agent
| Intel 8375C CPU, 2,90 GHz
| 5% d'un noyau
| 1428 M
| 1450 M

| Agent K3s
| Intel 8375C CPU, 2,90 GHz
| 3% d'un noyau
| 275 M
| 275 M

| Serveur K3s avec une charge de travail
| Pi4B BCM2711, 1,50 GHz
| 30% d'un noyau
| 1588 M
| 1613 M

| Cluster K3s avec un seul agent
| Pi4B BCM2711, 1,50 GHz
| 25% d'un noyau
| 1215 M
| 1413 M

| Agent K3s
| Pi4B BCM2711, 1,50 GHz
| 10% d'un noyau
| 268 M
| 268 M
|===

=== Champ d'application du test des ressources

Les tests de ressources visaient à répondre aux problèmes suivants :

* Sur un cluster à un seul nœud, déterminez la quantité minimale légitime de CPU, de mémoire et d'IOP à mettre de côté pour exécuter l'ensemble de la pile de serveurs K3s, en supposant qu'une charge de travail réelle sera déployée sur le cluster.
* Sur un nœud agent (worker), déterminez la quantité minimale légitime de CPU, de mémoire et d'IOP qui doit être mise de côté pour les composants du plan de contrôle de Kubernetes et de K3s (le kubelet et l'agent k3s).

=== Composants inclus dans les mesures de référence

Les composants testés sont les suivants :

* K3s v1.26.5 avec tous les composants activés
* Pile de surveillance Prometheus + Grafana
* https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[Exemple de déploiement de Nginx dans Kubernetes]

Il s'agit de chiffres de référence pour un système stable utilisant uniquement des composants packagés K3s (Traefik Ingress, Klipper lb, stockage local) avec une pile de surveillance standard (Prometheus et Grafana) et l'application d'exemple Guestbook.

Les chiffres relatifs aux ressources, y compris les IOPS, concernent uniquement le datastore et le plan de contrôle de Kubernetes, et n'incluent pas les frais généraux pour les agents de gestion ou la journalisation au niveau du système, la gestion des images de conteneurs ou toute exigence spécifique à la charge de travail.

=== Méthodologie

Une instance autonome de Prometheus v2.43.0 a été utilisée pour collecter des statistiques sur l'unité centrale, la mémoire et les entrées-sorties de disque à l'aide de `+prometheus-node-exporter+` installé via apt.

`+systemd-cgtop+` a été utilisé pour vérifier l'utilisation du CPU et de la mémoire au niveau du cgroup systemd. `+system.slice/k3s.service+` suit l'utilisation des ressources pour les K3 et containerd, alors que les pods individuels sont sous la hiérarchie `+kubepods+`.

D'autres données détaillées sur l'utilisation de la mémoire du K3s ont été recueillies sur le site `+kubectl top node+` à l'aide du serveur de mesures intégré pour le serveur et les processus d'agent.

Les chiffres d'utilisation sont basés sur les relevés du 95e percentile d'un fonctionnement stable sur des nœuds exécutant les charges de travail décrites.

=== Environnement

|===
| Arche | OS | Système | CPU | RAM | Disque

| x86_64
| Ubuntu 22.04
| AWS c6id.xlarge
| Intel Xeon Platinum 8375C CPU, 4 Core 2.90 GHz
| 8 GB
| NVME SSD

| aarch64
| Raspberry Pi OS 11
| Raspberry Pi 4 Model B
| BCM2711, 4 cœurs 1,50 GHz
| 8 GB
| UHS-III SDXC
|===

=== Besoins en ressources de base

Cette section présente les résultats des tests visant à déterminer les ressources minimales requises pour le fonctionnement de base de K3s.

==== Serveur K3s avec une charge de travail

Il s'agit des conditions requises pour un cluster à nœud unique dans lequel le serveur K3s partage les ressources avec une https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[charge de travail simple].

Les exigences en matière de CPU sont les suivantes :

|===
| Système | Utilisation des cœurs de l'unité centrale

| Intel 8375C
| 6 % d'un noyau

| Pi4B
| 30% d'un noyau
|===

Les exigences en matière de mémoire sont les suivantes

|===
| Stock de données testé | Système | Mémoire

| Kine/SQLite
| Intel 8375C
| 1596 M

|
| Pi4B
| 1588 M

| etcd embarqué
| Intel 8375C
| 1606 M

|
| Pi4B
| 1613 M
|===

Les exigences en matière de disque sont les suivantes :

|===
| Stock de données testé | IOPS | KiB/sec | Temps de latence

| Kine/SQLite
| 10
| 500
| < 10 ms

| etcd embarqué
| 50
| 250
| < 5 ms
|===

==== Cluster K3s avec un seul agent

Il s'agit des exigences de base pour un cluster K3s avec un nœud de serveur K3s et un agent K3s, mais sans charge de travail.

===== Serveur K3s

Les exigences en matière de CPU sont les suivantes :

|===
| Système | Utilisation des cœurs de l'unité centrale

| Intel 8375C
| 5% d'un noyau

| Pi4B
| 25% d'un noyau
|===

Les exigences en matière de mémoire sont les suivantes

|===
| Stock de données testé | Système | Mémoire

| Kine/SQLite
| Intel 8375C
| 1428 M

|
| Pi4B
| 1215 M

| etcd embarqué
| Intel 8375C
| 1450 M

|
| Pi4B
| 1413 M
|===

===== Agent K3s

Les exigences sont les suivantes :

|===
| Système | Utilisation des cœurs de l'unité centrale | RAM

| Intel 8375C
| 3% d'un noyau
| 275 M

| Pi4B
| 5% d'un noyau
| 268 M
|===

=== Analyse des facteurs d'utilisation des ressources primaires

Les chiffres d'utilisation du serveur K3s sont principalement motivés par la prise en charge du datastore Kubernetes (kine ou etcd), du serveur API, du contrôleur-gestionnaire et des boucles de contrôle du planificateur, ainsi que de toutes les tâches de gestion nécessaires pour effectuer des changements dans l'état du système. Les opérations qui imposent une charge supplémentaire au plan de contrôle de Kubernetes, comme la création/modification/suppression de ressources, provoqueront des pics temporaires d'utilisation. L'utilisation d'opérateurs ou d'apps qui font un usage intensif du datastore Kubernetes (comme Rancher ou d'autres applications de type Operator) augmentera les besoins en ressources du serveur. La mise à l'échelle du cluster par l'ajout de nœuds supplémentaires ou la création de nombreuses ressources de cluster augmentera les besoins en ressources du serveur.

Les chiffres d'utilisation des agents K3 sont principalement dus à la prise en charge des boucles de contrôle de la gestion du cycle de vie des conteneurs. Les opérations qui impliquent la gestion des images, l'approvisionnement en espace de stockage ou la création/destruction de conteneurs provoqueront des pics temporaires d'utilisation. Les extractions d'images, en particulier, sont généralement fortement liées à l'unité centrale et aux entrées-sorties, car elles impliquent la décompression du contenu de l'image sur le disque. Si possible, le stockage de la charge de travail (stockage et volumes éphémères du pod) doit être isolé des composants de l'agent (/var/lib/rancher/k3s/agent) afin de garantir qu'il n'y a pas de conflits de ressources.

=== Empêcher les agents et les charges de travail d'interférer avec le datastore du cluster

Dans un environnement où le serveur héberge également des pods de charge de travail, il convient de veiller à ce que les IOPS de l'agent et de la charge de travail n'interfèrent pas avec le datastore.

La meilleure façon d'y parvenir est de placer les composants du serveur (/var/lib/rancher/k3s/server) sur un support de stockage différent de celui des composants de l'agent (/var/lib/rancher/k3s/agent), qui comprennent le magasin d'images containerd.

Le stockage de la charge de travail (stockage et volumes éphémères du pod) doit également être isolé du magasin de données.

Le non-respect des exigences en matière de débit et de latence du datastore peut entraîner un retard dans la réponse du plan de contrôle et/ou une incapacité du plan de contrôle à maintenir l'état du système.

[#_server_sizing_requirements_for_k3s]
== Exigences en matière de dimensionnement du serveur pour les K3

=== Environnement

* Tous les agents étaient des instances t3.medium AWS ec2.
** Un seul agent était une instance c5.4xlarge. Il héberge la pile de surveillance grafana et l'empêche d'interférer avec les ressources du plan de contrôle.
* Le serveur était une instance c5 AWS ec2. Au fur et à mesure que le nombre d'agents augmentait, le serveur a été mis à niveau vers des instances c5 plus importantes.

=== Méthodologie

Ces données ont été récupérées dans des conditions de test spécifiques. Elle varie en fonction de l'environnement et de la charge de travail. Les étapes ci-dessous donnent un aperçu du test qui a été effectué pour obtenir ce résultat. Il a été exécuté pour la dernière fois sur la version 1.31.0+k3s1. Toutes les machines ont été provisionnées dans AWS avec des volumes gp3 standard de 20 GiB. Le test s'est déroulé selon les étapes suivantes :

. Surveiller les ressources sur grafana en utilisant la source de données prometheus. 
. Déployer les charges de travail de manière à simuler une activité continue de la grappe :
** Une charge de travail de base qui évolue continuellement vers le haut et vers le bas
** Une charge de travail qui est supprimée et recréée en boucle
** Une charge de travail constante qui contient plusieurs autres ressources, y compris des CRD.
. Rejoignez les nœuds d'agents par lots de 50 à 100 à la fois.
. Arrêter l'ajout d'agents lorsque le CPU du serveur dépasse 90% d'utilisation lors de l'ajout d'un agent, ou si la RAM est utilisée à plus de 80%. 

=== Observations

* Lors de l'intégration d'agents, l'unité centrale du serveur a connu des pics d'environ 20 % par rapport à la ligne de base.
* Généralement, le facteur limitant était l'unité centrale, et non la mémoire vive. Pour la plupart des tests, lorsque le CPU atteignait une utilisation de 90 %, l'utilisation de la RAM était d'environ 60 %.

==== Une note sur la haute disponibilité (HA)

À la fin de chaque test, deux serveurs supplémentaires ont été ajoutés (formant un cluster HA de base à 3 nœuds) afin d'observer l'effet sur les ressources du serveur d'origine. L'effet a été le suivant :

* Une baisse sensible de l'utilisation du processeur, généralement de 30 à 50 %.
* L'utilisation de la mémoire vive est restée inchangée.

Bien que cela n'ait pas été testé, l'utilisation de l'unité centrale étant le facteur limitant sur un seul serveur, on s'attend à ce que le nombre d'agents pouvant être joints augmente d'environ 50 % avec un cluster HA à 3 nœuds.
