= Sincronización de salud de depuración
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

xref:/setup/cli/cli-sts.adoc[La CLI de SUSE] Observability puede utilizarse para solucionar problemas de sincronización de estado y corregir problemas que puedan impedir que los datos de estado se ingieran y muestren correctamente en SUSE Observability. En esta página se describen los pasos generales que se deben seguir para solucionar problemas al depurar una sincronización de estado, así como los comandos de la CLI utilizados y una descripción de los mensajes de error devueltos.

== Pasos generales para la resolución de problemas

Cuando se depura la sincronización de salud hay algunos pasos comunes de verificación que se pueden hacer sin importar cuál sea el problema específico:

. xref:/configure/health/debug-health-sync.adoc#_list_streams[Compruebe que el flujo existe].
. Si utiliza subflujos, xref:/configure/health/debug-health-sync.adoc#_list_sub_streams[compruebe que el subflujo existe]. La respuesta también mostrará el número de estados de comprobación en el subflujo. Esto le permite saber si los datos se están ingiriendo y procesando.
. Investiga más:
 ** *Corriente presente* - xref:/configure/health/debug-health-sync.adoc#_show_stream_status[Compruebe el estado de la corriente], esto mostrará la latencia métrica de la corriente y cualquier xref:/configure/health/debug-health-sync.adoc#_error_messages[error].
 ** *Streams / sub streams presentes, pero no hay estados de comprobación* - Confirme que la carga útil enviada a la API del receptor se adhiere a la xref:/configure/health/send-health-data/send-health-data.adoc[especificación de carga útil de salud].
 ** *No hay secuencias/subdirecciones presentes*: utilice el siguiente comando de la CLI para comprobar que los datos sanitarios enviados a la API de Receiver llegan a SUSE Observability:

[,sh]
----
$ sts topic describe --name sts_health_sync
----

== Problemas comunes

=== Estado de comprobación no visible en el componente

Puede haber dos razones para que un estado de comprobación no se muestre en un componente en SUSE Observability:

* No se ha creado el estado de chequeo. Siga los xref:/configure/health/debug-health-sync.adoc#_general_troubleshooting_steps[pasos generales de solución de problemas] para confirmar que se ha creado el flujo / subflujo y que los datos están llegando a SUSE Observability.
* Se ha creado el estado de comprobación de estado, pero su `+topologyElementIdentifier+` no coincide con ningún `+identifiers+` de la topología de SUSE Observability. Utilice el comando de la CLI xref:/configure/health/debug-health-sync.adoc#_show_substream_status[show substream status] para comprobar si hay alguna `+Check states with identifier which has no matching topology element+`.

=== El estado de comprobación tarda en actualizarse en SUSE Observability

La razón principal es que la latencia de la sincronización sanitaria es mayor de lo esperado. Utilice el comando CLI xref:/configure/health/debug-health-sync.adoc#_show_stream_status[show stream status] para confirmar la latencia del flujo, así como el rendimiento de los mensajes y las operaciones de comprobación específicas. Puede ser necesario ajustar los datos enviados a la sincronización de salud, o la frecuencia con la que se envían los datos.

== Comandos CLI útiles

=== Lista de flujos

Devuelve una lista de todos los flujos de salud sincronizados actuales y el número de subflujos incluidos en cada uno.

[,sh]
----
$ sts health list
STREAM URN                                              | STREAM CONSISTENCY MODEL | SUB STREAM COUNT
urn:health:sourceId:streamId                            | REPEAT_SNAPSHOTS         | 1
----

=== Lista de subflujos

Devuelve una lista de todos los subflujos para un URN de flujo dado, junto con el número de estados de comprobación en cada uno.

[,sh]
----
$ sts health list -u urn:health:sourceId:streamId
SUB STREAM ID  | CHECK STATE COUNT
subStreamId1   | 1
subStreamId2   | 1
----

=== Mostrar el estado del flujo

El comando de estado del flujo devuelve las métricas agregadas de latencia y rendimiento del flujo. Esto es útil cuando se depura por qué una comprobación de estado tarda mucho tiempo en aterrizar en los elementos de topología esperados. Ayudará a diagnosticar si debe ajustarse la frecuencia de envío de datos a SUSE Observability. La salida incluye una sección `+Errors for non-existing sub streams:+` ya que algunos errores sólo son relevantes cuando no se ha podido crear un subflujo, por ejemplo `+StreamMissingSubStream+`. Los errores de subflujo pueden ser cualquiera de los xref:/configure/health/debug-health-sync.adoc#_error_messages[mensajes de error] documentados.

[,sh]
----
$ sts health status -u urn:health:sourceId:streamId
----

=== Mostrar estado de subflujo

El estado de subflujo proporciona información útil para verificar que SUSE Observability podría vincular estados de comprobación enviados desde un sistema externo a elementos de topología existentes. Esta información es útil para depurar por qué una comprobación específica no es visible en el elemento de topología esperado.

[,sh]
----
$ sts health status -u urn:health:sourceId:streamId -sub-stream-urn subStreamId3
----

[NOTE]
====
El estado de un subflujo mostrará los metadatos relacionados con el modelo de coherencia:

* *Repetir instantáneas* - Mostrar intervalo de repetición y caducidad
* *Incrementos transaccionales* - Mostrar desplazamiento de punto de control e índice de lote de punto de control
====


El estado del subflujo puede ampliarse para incluir detalles de los estados de comprobación coincidentes y no coincidentes utilizando el argumento de línea de comandos `+-t+`. Esto es útil para identificar cualquier estado de salud que no esté unido a un elemento de topología.
En el ejemplo siguiente, `+checkStateId2+` aparece bajo `+Check states with identifier which has no matching topology element+`. Esto significa que no ha sido posible hacer coincidir el estado de comprobación con un elemento de topología con el identificador `+server-2+`.

[,sh]
----
$ sts health status -u urn:health:sourceId:streamId -sub-stream-urn subStreamId3 -t
----

=== Borrar un flujo de salud

La funcionalidad `+delete+` stream es útil a la hora de configurar una sincronización de salud en SUSE Observability. Puedes utilizarlo para experimentar, borrar los datos y volver a empezar de cero. También puedes borrar un flujo y eliminar sus datos cuando estés seguro de que no quieres seguir utilizándolo.

[,sh]
----
$ sts health delete -u urn:health:sourceId:streamId
----

=== Borrar errores del flujo sanitario

La opción `+clear-errors+` elimina todos los errores de un flujo de salud. Esto resulta útil al configurar una sincronización de estado en SUSE Observability o, en el caso del modelo de coherencia `+TRANSACTIONAL_INCREMENTS+`, cuando algunos errores no pueden eliminarse orgánicamente. Por ejemplo, una solicitud para eliminar un estado de comprobación podría generar un error si SUSE Observability no conoce el estado de comprobación. La única forma de suprimir un error de este tipo sería utilizar el comando `+clear-errors+`.

[,sh]
----
$ sts health clear-error -u urn:health:sourceId:streamId
----

== Mensajes de error

[NOTE]
====
Los errores se cerrarán una vez subsanado el problema descrito.

Por ejemplo, un `+SubStreamStopWithoutStart+` se cerrará una vez que la sincronización de salud observe un mensaje de instantánea de inicio seguido de un mensaje de instantánea de parada.
====


|===
| Error | Descripción

| *StreamMissingSubStream*
| Se activa cuando la sincronización de salud recibe mensajes sin un mensaje de configuración de flujo previo como `+start_snapshot+` o `+expiry+`.

| *StreamConsistencyModelMismatch*
| Aparece cuando se recibe un mensaje que pertenece a un modelo de consistencia distinto del especificado al crear el flujo.

| *StreamMissingSubStream*
| Se activa cuando la sincronización de salud recibe mensajes con una instantánea de inicio anterior.

| *SubStreamRepeatIntervalTooHigh*
| Se activa cuando la sincronización de salud recibe un `+repeat_interval_s+` mayor que el máximo configurado de 30 minutos.

| *SubStreamStartWithoutStop*
| Se activa cuando la sincronización de salud recibe un segundo mensaje para abrir una instantánea cuando una instantánea anterior aún estaba abierta.

| *SubStreamCheckStateOutsideSnapshot*
| Aparece cuando la sincronización de salud recibe estados de comprobación externos sin abrir previamente una instantánea.

| *SubStreamStopWithoutStart*
| Se activa cuando la sincronización de salud recibe un mensaje de parada de instantánea sin haber iniciado ninguna instantánea.

| *SubStreamMissingStop*
| Se activa cuando la sincronización de salud no recibe una instantánea de parada después de un período de tiempo de espera de dos veces el `+repeat_interval_s+` establecido en el mensaje de instantánea de inicio. En este caso, se aplicará una instantánea de parada automática.

| *SubStreamExpired*
| Se activa cuando la sincronización de salud deja de recibir datos en un subflujo concreto durante más tiempo del configurado en `+expiry_interval_s+`. En este caso, se borrará el subflujo.

| *SubStreamLateData*
| Se activa cuando la sincronización de salud no recibe una instantánea completa a tiempo según lo establecido en `+repeat_interval_s+`.

| *SubStreamTransformerError*
| Se activa cuando la sincronización de salud no puede interpretar la carga útil enviada al receptor. Por ejemplo, "Falta el campo obligatorio 'nombre'" con la carga útil `+{"checkStateId":"checkStateId3","health":"deviating","message":"Unable to provision the device. ","topologyElementIdentifier":"server-3"}+` y la transformación `+Default Transformation+`.

| *SubStreamMissingCheckpoint*
| Aparece cuando un subflujo de incrementos transaccionales ha observado previamente un punto de control, pero al mensaje recibido le falta el campo `+previous_checkpoint+`

| *SubStreamInvalidCheckpoint*
| Se produce cuando un subflujo de incrementos transaccionales ha observado previamente un punto de control, pero el mensaje recibido tiene un `+previous_checkpoint+` que no es equivalente al último observado.

| *SubStreamOutdatedCheckpoint*
| Se produce cuando un subflujo de incrementos transaccionales ha observado previamente un punto de control, pero el mensaje recibido tiene un `+checkpoint+` que precede al último observado, lo que significa que sus datos ya han sido recibidos por SUSE Observability.

| *SubStreamUnknownCheckState*
| Se produce cuando al borrar una transacción se incrementa check_state y `+check_state_id+` no está presente en el subflujo.
|===

== Ver también

* xref:/setup/cli/cli-sts.adoc[Instalar SUSE Observability CLI]
