include::partial$variables.adoc[]
= C#
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Explorer et écrire la validation et la mutation des politiques de contrôle d'admission en utilisant .NET Core SDK avec le support WASI sur les plateformes WebAssembly comme Kubernetes.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "c#"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "c#", ".net"]
:sidebar_label: C#
:sidebar_position: 40
:current-version: {page-origin-branch}

Actuellement, .NET Core offre une prise en charge expérimentale de la plateforme WebAssembly WASI.
Il s'agit du https://github.com/SteveSandersonMS/dotnet-wasi-sdk[`dotnet-wasi-sdk`] projet.

[NOTE]
====

Vous n'avez pas besoin d'une installation Windows pour écrire ou exécuter du code .NET Core.
Tout peut être fait aussi bien sur une machine Linux que sur une machine macOS.
====


== État actuel

Les auteurs de politiques peuvent utiliser les ressources suivantes :

* https://github.com/kubewarden/policy-sdk-dotnet[{project-name}.NET Core SDK]: il fournit un ensemble d'objets et de fonctions qui simplifient le processus de rédaction des politiques.
* https://github.com/kubewarden/policy-sdk-dotnet/tree/main/example[{short-project-name} exemple de] politique : il s'agit d'un exemple de politique opérationnelle.

Aucune limitation n'est connue.
Le SDK permet d'écrire des politiques de validation et de mutation.

Il est possible d'utiliser la bibliothèquehttps://www.nuget.org/packages/KubernetesClient.Models[`KubernetesClient.Models`]pour gérer les objets Kubernetes.

== Modèle de projet

Actuellement, nous ne disposons pas d'un modèle de projet permettant d'échafauder une politique C#.

S'il vous plaît, https://github.com/kubewarden/policy-sdk-dotnet/issues[ouvrez une question]si vous êtes intéressé.
