= Gerenciamento do sistema operacional para o Rancher
:revdate: 2026-01-16
:page-revdate: {revdate}

{elemental-product-name} é uma pilha de software que permite o gerenciamento centralizado e totalmente nativo da nuvem do sistema operacional com o Kubernetes.

xref:release-notes.adoc[**Última versão: v1.8.0**]

A pilha {elemental-product-name} consiste em um conjunto de pacotes sobre o SLE Micro:

* *elemental-toolkit* - Inclui um conjunto de utilitários do sistema operacional para permitir o gerenciamento do sistema operacional por meio de contêineres. Inclui módulos dracut, configuração do carregador de inicialização, serviços de configuração no estilo cloud-init, etc.
* *elemental-operator* - Conecta-se ao Rancher Manager e lida com os CRDs MachineRegistration e MachineInventory.
* *elemental-register* - Registra máquinas por meio de machineRegistrations e as instala por meio de elemental-cli.
* *elemental-cli* - Instala qualquer derivado baseado no elemental-toolkit. Basicamente, um instalador baseado em nosso sistema de instalação e atualização A/B.
* *rancher-system-agent* - É executado no sistema instalado e recebe instruções ("Planos") do Rancher Manager sobre o que instalar e executar no sistema.

Os sistemas operacionais do nó do cluster são criados e mantidos por meio de imagens de contêineres no site {elemental_cli_name} e podem ser instalados em novos hosts usando o {elemental_ui_url}[{elemental_ui_name}] para o https://www.rancher.com/products/rancher[Manager] Rancher ou o {elemental_cli_url}[{elemental_cli_name}].

O {elemental_operator_url}[{elemental_operator_name}] e o {ranchersystemagent_url}[{ranchersystemagent_name}] permitem que o Rancher Manager controle totalmente os clusters {elemental-product-name}, desde a instalação e o gerenciamento do sistema operacional nos nós até o provisionamento de novos clusters K3s ou RKE2 de forma centralizada.

== {elemental-product-name} em hardware x86-64

{elemental-product-name} está pronto para produção e é totalmente compatível com x86-64, começando com o Rancher v2.7.0.

== {elemental-product-name} em hardware ARM

O ARM (aarch64) é funcional no estágio de desenvolvimento. Atualmente, o ARM só é testado no Raspberry Pi 4 Modelo B com k3s 1.24.8 (ou posterior). Comentários são bem-vindos.

== {elemental-product-name} em outro hardware

{elemental-product-name} está atualmente voltado para cenários de "borda" e, portanto, não oferece suporte a outros hardwares. Reavaliaremos isso à medida que o mercado evoluir.

== Pronto para experimentar?

Coloque um cluster {elemental-product-name} em funcionamento com seu método preferido

* Com o gerenciador do Rancher xref:quickstarts/quickstart-ui.adoc[{elemental-product-name} plugin]
* Com a xref:quickstarts/quickstart-cli.adoc[CLI do{elemental-product-name} ]

[NOTE]
.O que vem a seguir?
====
Deseja mais detalhes? Dê uma olhada na seção xref:rancher-os-management/architecture/architecture.adoc[Arquitetura] ou entre em contato com o {elemental_slack_url}[{elemental_slack_name}].
====

