include::partial$variables.adoc[]
= Distribuir una política Gatekeeper con {project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Distribuya políticas Gatekeeper en clústeres Kubernetes anotando archivos de políticas con metadatos y desplegándolos mediante ClusterAdmissionPolicy.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "gatekeeper", "rego"]
:current-version: {page-origin-branch}

Las políticas tienen que ser anotadas para que puedan ser empujadas, y finalmente ejecutadas por el {project-name} `+policy-server+` en un clúster Kubernetes.

Anotar y distribuir una política Gatekeeper es similar a distribuir una de Agente de Open Policy.

== Anotar la política

Vas a escribir un archivo `+metadata.yaml+` en tu directorio de políticas con contenidos:

[subs="+attributes",yaml]
----
rules:
- apiGroups: [""]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["CREATE"]
mutating: false
contextAware: false
executionMode: gatekeeper
annotations:
  io.kubewarden.policy.title: no-default-namespace
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: This policy will reject any resource created inside the default namespace
  io.kubewarden.policy.author: The {short-project-name} Authors
  io.kubewarden.policy.url: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.source: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
      This policy is just an example.

      You can write interesting descriptions about the policy here.
----

puede ver que todo coincide con los metadatos de la versión del Agente de Open Policy, excepto el bit `+executionMode: gatekeeper+`.

Anote la política:

[subs="+attributes",console]
----
$ kwctl annotate policy.wasm --metadata-path metadata.yaml --output-path annotated-policy.wasm
----

== Impulsar la política

Envíe su póliza a un registro OCI:

[subs="+attributes",console]
----
$ kwctl push annotated-policy.wasm registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
Policy successfully pushed
----

== Despliegue en Kubernetes

Primero tiene que llevar su póliza a su tienda local `+kwctl+`:

[subs="+attributes",console]
----
$ kwctl pull registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
pulling policy...
----

Ahora puede crear un recurso de andamiaje `+ClusterAdmissionPolicy+`:

[subs="+attributes",console]
----
$ kwctl scaffold manifest registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1 --type ClusterAdmissionPolicy
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Ahora utilice este recurso `+ClusterAdmissionPolicy+` para desplegar su política en un clúster Kubernetes.
