include::partial$variables.adoc[]
= Configuración de la política
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure los parámetros de la política utilizando {project-name}'s para la validación y serialización de los datos de la política.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "settings"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "policy specification", "policy settings"]
:sidebar_label: Configuración de la política
:current-version: {page-origin-branch}

El comportamiento de la política no es rígido, puede configurarlo proporcionando detalles de configuración a la política en tiempo de ejecución. El autor de la política tiene libertad para definir la estructura de la configuración de la política.

{project-name} se encarga de serializar la configuración de la política en JSON y se la proporciona a la política cada vez que se invoca.

== Validación de la configuración

Las políticas deben validar las configuraciones que proporciona un usuario para comprobar que son correctas.

Cada política registra una función waPC llamada `validate_settings` que valida la configuración de la política.

La función `validate_settings` recibe como entrada una representación JSON de los ajustes proporcionados por el usuario. Esta función los valida y devuelve como respuesta un objeto `SettingsValidationResponse`.

La estructura del objeto `SettingsValidationResponse` es:

[subs="+attributes",yaml]
----
{
  # mandatory
  "valid": <boolean>,

  # optional, ignored if accepted - recommended for rejections
  "message": <string>,
}
----

Si la configuración proporcionada por el usuario es `valid`, `validate_settings` ignora el contenido de`message`. En caso contrario, `validate_settings` muestra el contenido de `message`.

[NOTE]
====

{short-project-name} https://github.com/chimera-kube/policy-server[El servidor de políticas de]valida todas las configuraciones de políticas proporcionadas por los usuarios en el momento del inicio. El servidor de políticas sale inmediatamente con un error si al menos una de sus políticas ha recibido parámetros de configuración erróneos.

====


== Ejemplo

Como ejemplo, considere la políticahttps://github.com/kubewarden/psp-capabilities[psp-capabilities] que tiene el siguiente formato de configuración:

[subs="+attributes",yaml]
----
allowed_capabilities:
- CHOWN

required_drop_capabilities:
- NET_ADMIN

default_add_capabilities:
- KILL
----

La función `validate_settings` recibe como entrada el siguiente documento JSON:

[subs="+attributes",json]
----
{
  "allowed_capabilities": [
    "CHOWN"
  ],
  "required_drop_capabilities": [
    "NET_ADMIN"
  ],
  "default_add_capabilities": [
    "KILL"
  ]
}
----

== Recapitulemos

Cada política debe registrar una función waPC, `validate_settings`.
