include::partial$variables.adoc[]
= Uso de autoridades de certificaĂ§ĂŁo personalizadas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure o PolicyServer para usar autoridades de certificaĂ§ĂŁo personalizadas ou fontes inseguras em conjunto com registros especificados.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "policy-servers", "custom-certificate-authorities"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "autoridades de certificaĂ§ĂŁo personalizadas"]
:sidebar_label: Uso de CAs personalizadas
:current-version: {page-origin-branch}

== Autoridades de certificaĂ§ĂŁo personalizadas para registros de polĂ­ticas

Ă possĂ­vel especificar e configurar as autoridades de certificaĂ§ĂŁo que um PolicyServer usa ao extrair os artefatos ClusterAdmissionPolicy do registro de polĂ­ticas. Os seguintes campos de `spec` configuram o executĂĄvel`policy-server` implantado para esse efeito.

=== Fontes inseguras

[IMPORTANT]
====

O comportamento padrĂŁo de `kwctl` e `policy-server` Ă© impor HTTPS com certificados confiĂĄveis que correspondam ao armazenamento da CA do sistema. VocĂȘ pode interagir com os registros usando certificados nĂŁo confiĂĄveis ou mesmo sem TLS, usando a configuraĂ§ĂŁo`insecure_sources`. Essa abordagem Ă© *altamente desaconselhada* para ambientes mais prĂłximos da produĂ§ĂŁo.

====

Para configurar o PolicyServer para aceitar conexĂ”es inseguras com registros especĂ­ficos, use o campo `spec.insecureSources` do PolicyServer. Esse campo aceita uma lista de URIs inseguros. Por exemplo:

[subs="+attributes",yaml]
----
spec:
  insecureSources:
    - localhost:5000
    - host.k3d.internal:5000
----

Consulte xref:howtos/custom-certificate-authorities.adoc[Autoridade de certificados personalizados] para obter mais informaĂ§Ă”es sobre como o executĂĄvel `policy-server` trata URIs inseguros.

=== Autoridades de certificaĂ§ĂŁo personalizadas

VocĂȘ pode configurar o PolicyServer com uma cadeia de certificados personalizada de 1 ou mais certificados para um URI especĂ­fico. Para fazer isso, use o campo`spec.sourceAuthorities`.

Esse campo Ă© um mapa de URIs, cada um com sua prĂłpria lista de cadeias de caracteres que contĂȘm certificados codificados em PEM (Privacy Enhanced Mail). Por exemplo:

[subs="+attributes",yaml]
----
spec:
  sourceAuthorities:
    "registry-pre.example.com":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-1 PEM cert
        -----END CERTIFICATE-----
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-2 PEM cert
        -----END CERTIFICATE-----
    "registry-pre2.example.com:5500":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre2 PEM cert
        -----END CERTIFICATE-----
----

Consulte xref:howtos/custom-certificate-authorities.adoc[Autoridades de certificaĂ§ĂŁo personalizadas] para obter mais informaĂ§Ă”es sobre como o executĂĄvel `policy-server` as trata.
