= Fehlerbehebung bei benutzerdefinierten metrischen Diagrammen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

== Übersicht

* <<_the_metric_chart_doesnt_show_on_the_highlights_page_of_a_component,Das metrische Diagramm wird auf der Seite Highlights einer Komponente nicht angezeigt>>
* <<_the_metric_chart_doesnt_show_on_the_metrics_perspective_of_a_component,Das Metrikdiagramm wird in der Metrikperspektive einer Komponente nicht angezeigt>>
* <<_the_metric_chart_on_a_component_remains_empty_no_data,Das metrische Diagramm einer Komponente bleibt leer ("keine Daten")>>

== Das metrische Diagramm wird auf der Seite Highlights einer Komponente nicht angezeigt

Zurzeit ist es nicht möglich, die metrischen Diagramme, die auf einer Komponenten-Highlights-Seite angezeigt werden, anzupassen. Die Diagramme für benutzerdefinierte metrische Bindungen werden nur in der Perspektive "Metriken" angezeigt.

== Das Metrikdiagramm wird in der Metrikperspektive einer Komponente nicht angezeigt

Die Abfrage `scope` auf eine metrische Bindung wird verwendet, um festzustellen, ob eine Komponente die metrische Bindung zeigt. Wenn eine Komponente keine metrische Bindung aufweist, überprüfen Sie, ob die Topologieabfrage im Bereich mit der Komponente übereinstimmt.

Prüfen Sie zunächst, ob die Komponente tatsächlich die erwarteten Bezeichnungen und/oder den erwarteten Komponententyp auf der Seite mit den Komponentenhervorhebungen hat; Name und Typ stehen oben, die Bezeichnungen befinden sich im Abschnitt "Über". Vergewissern Sie sich, dass keine Schreibfehler in den Etikettennamen oder -werten enthalten sind.

Prüfen Sie, ob die Bereichsabfrage die richtige Syntax hat:

. Öffnen Sie die Erkundungsansicht über das Menü Ansichten und die blaue Schaltfläche "Erkunden" auf der rechten Seite. Oder direkt über die URL: `https://<your-stackstate-instance>/#/views/explore`
. Öffnen Sie die Filter und wählen Sie `switch to STQL`
. Kopieren Sie nun die Abfrage aus dem Bereich in das STQL-Feld und führen Sie die Abfrage aus

In der Übersicht werden nun alle Komponenten angezeigt, die der Abfrage entsprechen und die das Diagramm erhalten werden.

== Das metrische Diagramm einer Komponente bleibt leer ("keine Daten")

Für das metrische Diagramm, das keine Daten enthält, während Daten erwartet wurden, öffnen Sie den Inspektor (das Symbol in der oberen rechten Ecke des Diagramms). Schalten Sie die Schaltfläche "Abfrage anzeigen" ein, um die Abfragen anzuzeigen.

Vergewissern Sie sich, dass die Abfrage keinen der Parameter mehr enthält (d.h. alle Werte wie `${tags.cluster-name}` oder `${name}`) wurden durch die Werte für die Komponente ersetzt. Wenn einige Parameter in der Abfrage zurückgelassen wurden, waren die Beschriftungen in dieser Komponente nicht verfügbar. Überprüfen Sie daher die verwendeten Namen (in diesem Beispiel `cluster-name`) mit den auf der Komponente vorhandenen Bezeichnungen. Achten Sie auch darauf, dass die Namen keine Tippfehler enthalten.

Wenn alle Parameter ausgefüllt sind, gibt es möglicherweise ein Problem mit der PromQL-Abfrage. Kopieren Sie dazu die PromQL-Abfrage und öffnen Sie den Metrics-Explorer (über das Hauptmenü von SUSE Observability). Fügen Sie die Abfrage in den Metrik-Explorer ein und führen Sie sie aus. Dies sollte immer noch ein leeres Ergebnis liefern.

Entweder existiert die Metrik nicht, sie hat keine der Bezeichnungen oder die Bezeichnung existiert, aber es gibt keine Zeitreihen, die dem Wert entsprechen. Die schnellste Methode, dieses Problem zu lösen, besteht darin, die Abfrage so umzuschreiben, dass sie nur den Namen der Metrik enthält, und diese Abfrage auszuführen; wenn es Ergebnisse gibt, ist die Metrik vorhanden (also keine Tippfehler). Anhand des Tabellenergebnisses kann auch überprüft werden, ob alle verwendeten Etiketten vorhanden sind. Achten Sie darauf, dass auch hier keine Tippfehler vorkommen.

Wenn es zwar Ergebnisse gibt, aber nicht für einen bestimmten Wert einer Kennzeichnung (z. B. für die Kennzeichnung `pod_name` ), ist die Abfrage in Ordnung, aber es gibt keine Zeitreihe für diese spezifische Metrik für diese spezifische Komponente. Was ist in diesem Fall zu prüfen?

* Werden die Daten für diese Komponente gesammelt (entweder über den SUSE Observability-Agent oder auf andere Weise)?
* Meldet die Komponente die Metrik überhaupt?

Wie dies geschieht, hängt davon ab, wie die Datenerfassung konfiguriert ist.
