= Autorisations
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability auto-hébergé

== Autorisations SUSE Observability

Il existe deux types de permissions dans SUSE Observability. *Les permissions système* déterminent les capacités des utilisateurs, telles que l'accès aux paramètres, l'exécution de requêtes et le scripting. *Autorisations à portée* déterminent l'accès aux données d'observabilité et à certains types de ressources comme les vues SUSE Observability.  Pour les opérations CRUD sur les vues SUSE Observability, ces autorisations peuvent être accordées pour une vue spécifique ou pour toutes les vues. Pour connaître les autorisations associées à chaque rôle prédéfini dans SUSE Observability, voir xref:/setup/security/rbac/rbac_roles.adoc#_predefined_roles[rôles prédéfinis]

Les permissions suivantes sont disponibles dans SUSE Observability :

.Autorisations
[cols="2,2,5"]
|===
|Ressources |Verbes |Description

|agents
|obtenir
|Agents connectés

|api-tokens
|obtenir
|La clé API à utiliser pour l'authentification avec l'interface CLI SUSE Observability.  Ceci est propre à chaque utilisateur.

|actions des composants
|execute
|xref:/use/views/k8s-topology-perspective.adoc#_actions[Actions des composants dans la perspective de topologie].

|liaisons métriques
|obtenir, créer, mettre à jour, supprimer
ifdef::ss-ff-stackpacks2_enabled[]
|xref:/setup/custom-integrations/metric-bindings/index.adoc[Liaisons pour visualiser les données dans la perspective des métriques].
endif::[]
ifndef::ss-ff-stackpacks2_enabled[]
|xref:/use/metrics/k8s-add-charts.adoc[Liaisons pour visualiser les données dans la perspective des métriques].
endif::[]

|métriques
|obtenir\^[1]^, mettre à jour
|Ingérer et interroger des données métriques à l'aide de PromQL

|topologie
|get\^[1]^
|xref:/use/views/k8s-views.adoc[Explorer les vues de topologie à périmètre défini].

|traces
|get\^[1]^
|xref:/use/traces/k8sTs-explore-traces.adoc[Explorer les traces].

|vues
|obtenir^[1]^, créer, mettre à jour^[1]^, supprimer^[1]^
|Utilisez ou gérez xref:/use/views/k8s-custom-views.adoc[les vues personnalisées].

|vues favorites
|créer, supprimer
|Ajouter et retirer des étoiles dans les vues.

|visualization
|update
|Modifier xref:/use/views/k8s-topology-perspective.adoc#_visualization_settings[les paramètres de visualisation].

|===
\^[1]^ Ceci est une *autorisation limitée*, l’interprétation du nom de la ressource dépend du contexte

=== Autorisations à portée limitée

Vous pouvez accorder certaines autorisations à l'échelle du système, ou vous pouvez les limiter à un sous-ensemble des ressources.  Vous pouvez leur donner un *Nom de ressource*, qui indique la portée.  L'interprétation de ce nom dépend du type de ressource.  Notez que la portée peut ne s'appliquer qu'à certains des verbes.

* `views` - Le nom de la vue
* `topology` - Toute étiquette de composant. Dans un environnement Kubernetes, cela peut être, par exemple, `cluster-name:<cluster-name>` ou `k8s-scope:<cluster-name>/<namespace>`
* `metrics` - Dans un environnement Kubernetes, soit `k8s:<cluster-name>:\\__any__`, soit `k8s:<cluster-name>:<namespace>`
* `traces` - Dans un environnement Kubernetes, soit `k8s.cluster.name:<cluster-name>`, soit `k8s.scope:<cluster-name>/<namespace>`
* `scoped-permissions` - Le nom du cluster pour lequel les autorisations sont gérées
