= Activación de ClusterClass
:revdate: 2025-06-30
:page-revdate: {revdate}

En esta sección cubriremos la habilitación de la https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/[*ClusterClass*] para un Proveedor CAPI.

[TIP]
====
Antes de utilizar la función ClusterClass, estudie la documentación del proveedor y confirme que la función es compatible. Esta documentación incluye una matriz en la sección xref:../overview/certified.adoc[Proveedores] certificados con el xref:../overview/certified.adoc#_clusterclass_support_for_certified_providers[estado de compatibilidad de la topología de clúster].
====

== Activar ClusterClass

Para poder utilizar la función ClusterClass, es necesario habilitarla para el núcleo de la Cluster API y para cualquier proveedor que la admita. Para ello, ajuste la variable `CLUSTER_TOPOLOGY` a `true`.

La carta {product_name} Helm habilitará automáticamente la función al instalar CAPI. Sin embargo, cuando habilite proveedores adicionales, asegúrese de que `CLUSTER_TOPOLOGY` está configurado en la configuración del proveedor. El recurso xref:../reference/capiprovider.adoc[CAPIProvider] de Turtles permite pasar parámetros de instalación al proveedor a través de `variables` de la siguiente manera:

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: azure
  namespace: capz-system
spec:
  type: infrastructure
  name: azure
  configSecret:
    name: azure-variables
  variables:
    CLUSTER_TOPOLOGY: "true"
    EXP_CLUSTER_RESOURCE_SET: "true"
    EXP_MACHINE_POOL: "true"
    EXP_AKS_RESOURCE_HEALTH: "true"
----

El recurso definido en este archivo YAML instalará CAPZ con soporte para una serie de características, incluyendo `CLUSTER_TOPOLOGY`.
