include::partial$variables.adoc[]
= 什么是审计扫描仪？
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 了解审计扫描仪在持续验证集群是否符合整个集群的准入控制器策略方面的作用。
:doc-persona: ["kubewarden-user"、"kubewarden-operator"、"kubewarden-policy-developer"、"kubewarden-integrator"]
:doc-topic: ["explanations", "audit-scanner"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "audit scanner", "kubernetes"]
:sidebar_label: 审计扫描仪
:sidebar_position: 50
:current-version: {page-origin-branch}

[NOTE]
====

审计扫描仪功能从{project-name} 1.7.0 版开始提供

====


`audit-scanner` 组件会不断检查群集中的资源。它会标记出不遵守集群中部署的{short-project-name} 策略的程序。

政策随着时间的推移而演变。有新的政策部署和政策更新。
版本和配置设置发生变化。这可能会导致已在群集内的资源不再符合要求。审计扫描功能为 Kubernetes 管理员提供了一个可持续验证集群合规性状态的工具。

为了解释审计扫描仪在{short-project-name} 中的使用，请考虑以下情况。

假设 Bob 正在集群中部署 WordPress Pod。鲍勃是 Kubernetes 的新手，他犯了一个错误，将 Pod 部署为特权容器运行。此时，没有任何策略可以阻止，因此 Pod 已在群集中成功创建。

几天后，Kubernetes 管理员 Alice 强制执行{short-project-name}政策，禁止创建权限容器。Bob 部署的 Pod 将继续在集群中运行，因为它已经存在。

审计扫描仪生成的报告可让 Alice 识别所有违反创建策略的工作负载。其中包括鲍勃创建的 WordPress Pod。

审计扫描仪通过以下方式运行

* 确定需要审计的所有资源
* 对于每个资源，它都会使用该资源的数据构建一个合成的接纳请求
* 它将每个准入请求发送到策略服务器端点，该端点只用于审核请求

就评估申请的政策而言，真实申请和审计申请没有区别。该审计策略服务器端点具有收集评估数据的工具。因此，用户可以使用他们的监控工具来分析审计扫描仪数据。

== 启用审计扫描仪

您可以从{short-project-name} 1.7.0 版开始启用审计扫描仪。

详细安装说明见xref:howtos/audit-scanner.adoc[审计扫描仪]使用说明。

== 政策

默认情况下，审计扫描仪会评估每个策略。要在审计扫描仪中跳过策略评估的操作员必须在策略定义中将`spec.backgroundAudit` 字段设置为`false` 。

此外，{short-project-name} 中的策略现在还支持两种可选注释：

* `io.kubewarden.policy.severity` 注释可让您指定违反策略的严重程度，如`critical`,`high`,`medium`,`low` 或`info` 。
* `io.kubewarden.policy.category` 注释可让您根据特定领域或目的对策略进行分类，如`PSP` 、`compliance` 或`performance` 。

更多信息，请参阅政策作者xref:tutorials/writing-policies/index.adoc[文档]。

== 权限和服务帐户

{short-project-name} 中的审计扫描仪需要特定的基于角色的访问控制（RBAC）配置，才能扫描 Kubernetes 资源并保存结果。安装会创建一个具有这些权限的正确默认服务账户。用户可以创建自己的 ServiceAccount 来配置对资源的访问。

默认审计扫描器`ServiceAccount` 与 Kubernetes 提供的`view` `ClusterRole`绑定。`ClusterRole` 允许只读访问命名空间内的各种 Kubernetes 资源。有关该角色的更多详情，请参阅https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles[Kubernetes 文档]。

审计扫描器绑定到`ClusterRole` ，该 授予对{short-project-name} 资源类型的读取访问权限和对`PolicyReport` CRD 的读写访问权限。 这些权限可让扫描仪获取资源，用于开展审计评估和根据评估结果创建政策报告。
