= Statisches Netzwerk mit nm-Konfigurator
:revdate: 2025-09-08
:page-revdate: {revdate}

[CAUTION]
.Warnung
====
Declarative Networking befindet sich im Stadium *der Technologievorschau* mit eingeschränkter Unterstützung. Daher wird es nicht für Produktionsumgebungen empfohlen.
====

Die `+nm-configurator+` https://github.com/suse-edge/nm-configurator?tab=readme-ov-file#per-node-configurations[Konfiguration] kann verwendet werden, um einzelnen Rechnern statisch IP-Adressen zuzuweisen, die auf den MAC-Adressen der NICs basieren.

Bei dieser Lösung ist kein IPAM-Provider erforderlich, sondern der Benutzer muss die Zuordnung zwischen bekannten MAC-Adressen und IP-Adressen selbst vornehmen.

In diesem Beispiel werden wir ein Elemental-Image anpassen und eine xref:references/cloud-config-reference.adoc#_configuration_syntax[yip-Konfiguration] einfügen, die die statische Netzwerkkonfiguration bereits beim Booten anwendet.

Die folgende Konfiguration umfasst 2 Knoten mit einer sehr einfachen Netzwerkkonfiguration.

.99_static_network_config.yaml
[,yaml]
----
include::example$network/yip-nmc-static-config.yaml[]
----

== Einbindung der statischen Netzwerkkonfiguration in ein benutzerdefiniertes Betriebssystem-Image

Wir können ein Elemental-Image erweitern, um die statische Netzwerkkonfiguration in `+/system/oem+` aufzunehmen. Jedes Elemental-betriebene Betriebssystem, auf dem das https://github.com/rancher/elemental-toolkit[Elemental Toolkit] läuft, wertet jede Konfiguration in diesem Verzeichnis aus, wenn eine Stufe ausgeführt wird.  Zusätzlich werden wir das Image anpassen, um die erforderliche `+nmc+` Binärdatei zu installieren.

[,shell]
----
# The version of Elemental to modify
FROM registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:latest

# Install the static network config
COPY 99_static_network_config.yaml /system/oem/99_static_network_config.yaml

# Install nmc
RUN curl -LO https://github.com/suse-edge/nm-configurator/releases/download/v0.3.1/nmc-linux-x86_64 && \
    install -o root -g root -m 0755 nmc-linux-x86_64 /usr/sbin/nmc

# IMPORTANT: /etc/os-release is used for versioning/upgrade.
ARG IMAGE_REPO=norepo
ARG IMAGE_TAG=latest
RUN \
    sed -i -e "s|^IMAGE_REPO=.*|IMAGE_REPO=\"${IMAGE_REPO}\"|g" /etc/os-release && \
    sed -i -e "s|^IMAGE_TAG=.*|IMAGE_TAG=\"${IMAGE_TAG}\"|g" /etc/os-release && \
    sed -i -e "s|^IMAGE=.*|IMAGE=\"${IMAGE_REPO}:${IMAGE_TAG}\"|g" /etc/os-release

# IMPORTANT: it is good practice to recreate the initrd and re-apply `+elemental-init+`
RUN elemental init --force elemental-rootfs,grub-config,dracut-config,cloud-config-essentials,elemental-setup
----

Der Betriebssystem-Container kann nun erstellt und in Ihre Registrierung übertragen werden:

[,shell]
----
docker build --build-arg IMAGE_REPO=myrepo/static-network-os \
             --build-arg IMAGE_TAG=v1.1.1 \
             -t myrepo/static-network-os:v1.1.1 .
docker push myrepo/static-network-os:v1.1.1
----

Da die statische Netzwerkkonfiguration im Image enthalten ist, müssen Sie verschiedene Images mit unterschiedlichen Konfigurationen erstellen und pflegen, wahrscheinlich eines pro Nodepool oder eines pro Cluster. Benutzerdefinierte Betriebssystem-Images müssen beibehalten werden, um das anfängliche bootfähige ISO-Image (über ein xref:references/seedimage-reference.adoc[SeedImage]) zu erstellen, aber auch, wenn die Rechner xref:node-operational-tasks/upgrade.adoc[aktualisiert werden]. Die gewünschte statische Netzwerkkonfiguration **muss** auf den mit dem xref:references/managedosimage-reference.adoc[ManagedOSImage] verwendeten Betriebssystem-Images vorhanden sein, andernfalls wird die Konfiguration beim Booten des aktualisierten Systems fehlen.

Das benutzerdefinierte Betriebssystem-Image kann auch zur Erstellung eines bootfähigen Raw-Disk-Images verwendet werden:

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: my-raw-image
  namespace: fleet-default
spec:
  type: raw
  baseImage: myrepo/static-network-os:v1.1.1
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: my-registration
    namespace: fleet-default
----

== Erstellen einer bootfähigen ISO-Datei

Sie können nun xref:operator-operational-tasks/custom-images.adoc#_create_a_custom_bootable_installation_iso[einen ISO-Container] aus diesem OS-Container-Image xref:operator-operational-tasks/custom-images.adoc#_create_a_custom_bootable_installation_iso[erstellen]. Weitere Informationen über die Anpassung von Elemental-Bildern finden Sie in der xref:operator-operational-tasks/custom-images.adoc[Dokumentation].

[,dockerfile]
----
FROM myrepo/static-network-os:v1.1.1 AS os
FROM myrepo/static-network-os:v1.1.1 AS builder

WORKDIR /iso
COPY --from=os / rootfs

# work around buildah issue: https://github.com/containers/buildah/issues/4242
RUN rm -f rootfs/etc/resolv.conf

RUN elemental build-iso \
        dir:rootfs \
        --bootloader-in-rootfs \
        --squash-no-compression \
        -o /output -n "elemental"

FROM busybox
COPY --from=builder /output /elemental-iso

ENTRYPOINT ["busybox", "sh", "-c"]
----

[,shell]
----
docker build -t myrepo/static-network-iso:v1.1.1 .
docker push myrepo/static-network-iso:v1.1.1
----

Sobald der ISO-Container in Ihrer Registry veröffentlicht ist, können Sie im xref:references/seedimage-reference.adoc[SeedImage] darauf verweisen, wie auf jedes andere von Elemental verteilte ISO-Image.

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: my-iso
  namespace: fleet-default
spec:
  type: iso
  baseImage: myrepo/static-network-iso:v1.1.1
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: my-registration
    namespace: fleet-default
----

Beachten Sie, dass die statische Netzwerkkonfiguration nun ausgewertet wird, wenn das Installationsmedium hochfährt, und dann als Teil des Basis-Images auf dem System installiert wird.
