= Migración de StackState 6.x a SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado
:page-toclevels: 3

Debido al cambio de nombre del producto y a los cambios en el formato de los datos de topología, no es posible actualizar de StackState a SUSE Observability mediante un comando estándar de actualización de Helm. Esta guía de migración le ayudará a configurar SUSE Observability exactamente igual que StackState.

SUSE Observability será una nueva instalación, sin los datos históricos ya existentes. *Opcionalmente,* los datos históricos pueden mantenerse accesibles hasta que SUSE Observability haya acumulado suficiente historial. Esta guía cubre ambos escenarios.

Dependiendo del escenario elegido, los pasos para migrar son diferentes. La ejecución en paralelo es algo más complicada y requerirá más recursos. Los pasos generales, aplicables a ambos escenarios son:

. Instale la última versión de StackState 6.x
. Crear y descargar una copia de seguridad de la configuración
. Instalar y configurar SUSE Observability, pasos específicos del escenario
. Actualizar la configuración de los colectores abiertos de telemetría
. Migrar el agente

[NOTE]
====
A lo largo de esta guía todos los ejemplos asumen la siguiente configuración, personalice los comandos para que coincidan con su configuración exacta:

* Se accede al clúster Kubernetes mediante un contexto denominado `+observability+`
* StackState está instalado en el espacio de nombres `+stackstate+` 
* SUSE Observability se instalará en el espacio de nombres `+suse-observability+` 
====


== Instale la última versión de StackState 6.x

Sólo la última versión de StackState 6.x dispone de una copia de seguridad de la configuración que contiene toda la configuración en un formato compatible con SUSE Observability. Asegúrese de que tiene instalada la última versión ejecutando `+helm list --namespace stackstate+` (utilice el espacio de nombres donde está instalado StackState):

* La versión de la carta del timón debe ser `+1.12.1+`
* La versión de la aplicación debe ser `+6.0.0-snapshot.20241023094532-stackstate-6.x-7be52ad+`

Si no tiene esa versión, actualícela primero siguiendo los estándar https://docs.stackstate.com/6.0/self-hosted-setup/upgrade-stackstate/steps-to-upgrade#_minor_or_maintenance_stackstate_release[pasos].

== Crear una copia de seguridad de la configuración y descargarla

En primer lugar creamos una copia de seguridad de la configuración de StackState, después de esto no debe realizar más cambios de configuración en StackState (no se transferirán a SUSE Observability). Para ello, primero familiarícese con la copia de la configuración y obtenga los scripts necesarios utilizando https://docs.stackstate.com/6.0/self-hosted-setup/data-management/backup_restore/configuration_backup#_working_with_configuration_backups[seguridad de].

Desde el directorio `+restore+` que contiene los scripts ejecute estos comandos:

. Establece el contexto y el espacio de nombres activos:
+
[,bash]
----
  kubectl config use-context observability
  kubectl config set-context --current --namespace=stackstate
----

. Crear una copia de seguridad (esto requerirá 1Gi de memoria y 1 núcleo en el clúster), esto puede tomar un tiempo para crear un trabajo de Kubernetes e iniciar el pod:
+
[,bash]
----
 ./backup-configuration-now.sh
----

. En la salida del comando verá el nombre de archivo de la copia de seguridad, algo así como `+sts-backup-20241024-1423.sty+`. Copie el nombre del archivo y utilícelo para descargar la copia de seguridad:
+
[,bash]
----
./download-configuration-backup.sh sts-backup-20241023-1423.sty
----

Ahora debería tener el archivo de copia de seguridad de la configuración en su ordenador.

== Instalar y configurar SUSE Observability

Aquí es donde las 2 opciones son diferentes. Siga las instrucciones de su escenario preferido.
Elige uno de:

* xref:#_replace_stackstate[]
* xref:#_run_side_by_side[].

=== Sustituir StackState

==== Desinstalar StackState

Desinstalar StackState antes de instalar SUSE Observability tiene 2 ventajas, en primer lugar libera recursos en el clúster, por lo que no se necesitan nodos adicionales temporales. En segundo lugar, elimina la configuración de entrada para StackState, liberando la URL de StackState para que pueda ser reutilizada por SUSE Observability. La única desventaja es que habrá un período desde este punto hasta la configuración de SUSE Observability en el que no dispondrá de supervisión con StackState ni con SUSE Observability.

La desinstalación de StackState también eliminará sus datos históricos (topología y todos los demás datos de telemetría también). Para desinstalar StackState siga la https://docs.stackstate.com/6.0/self-hosted-setup/uninstall[documentación de desinstalación de].

==== Instalar SUSE Observability

Instale SUSE Observability en un espacio de nombres distinto de StackState para evitar conflictos. Se recomienda utilizar el mismo espacio de nombres que en la documentación, `+suse-observability+`.

El mayor cambio para la instalación es que ahora hay soporte para perfiles, por favor seleccione el perfil que se ajuste a su cluster observado usando los xref:/setup/install-stackstate/requirements.adoc#_resource_requirements[requerimientos] y úselo para generar los valores como se documenta en la guía de instalación. Los valores personalizados de Helm para StackState son compatibles con SUSE Observability. Sin embargo, los valores para personalizar los recursos deben ser eliminados en favor de los nuevos perfiles, vamos a mantenerlos en un archivo llamado `+custom-values-no-resources.yaml+`. Puede utilizar la misma configuración de entrada, de forma que SUSE Observability sustituya efectivamente a StackState desde la perspectiva del usuario y del agente.

Para instalar SUSE Observability siga la xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[guía de instalación] con unas pequeñas modificaciones en la generación de valores para realizar la migración:

* utilice el perfil seleccionado que se ajuste a su entorno y a sus valores personalizados (actualizados).
* obtener el `+global.receiverApiKey+` de los valores de StackState y proporcionarlo como argumento extra a la generación de valores.
* para la URL base que debe proporcionarse utilizamos la misma URL que la instalación actual de StackState: `+https://stackstate.demo.stackstate.io+`

Así pues, el paso de generación de valores es el siguiente (utilizando de nuevo nuestro ejemplo, con el perfil más pequeño):

[,bash]
----
export VALUES_DIR=.
helm template \
  --set license='<your license>' \
  --set receiverApiKey='our-old-api-key' \
  --set baseUrl='https://stackstate.demo.stackstate.io' \
  --set sizing.profile='10-nonha' \
  suse-observability-values \
  suse-observability/suse-observability-values --output-dir $VALUES_DIR
----

El comando de instalación de Helm es el mismo que en los documentos de instalación, con la opción de incluir el archivo de valores `+custom-values-no-resources.yaml+` si lo tiene. También asegúrese de incluir los valores de configuración de entrada, este puede ser el mismo que se utilizó para StackState. En el ejemplo que utilizaremos:

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/ingress.yaml \
suse-observability \
suse-observability/suse-observability
----

[NOTE]
====
La instalación generará por defecto una nueva contraseña de administrador. Si está utilizando la autenticación estándar y desea mantener la misma contraseña de administrador que antes, deberá especificarla en el paso de generación de valores (o editarla después de generar los valores).
====


==== Restaurar la copia de seguridad de la configuración

Ahora que SUSE Observability está instalado, se puede restaurar la copia de seguridad de la configuración. El cuadro de SUSE Observability Helm viene con un conjunto similar de herramientas de copia de seguridad xref:/setup/data-management/backup_restore/configuration_backup.adoc[documentadas aquí]. *Estos no son los mismos que para StackState 6.x*, así que asegúrese de obtener los scripts del directorio `+restore+` de la *tabla SUSE Observability Helm* para restaurar la copia de seguridad.

Desde el directorio `+restore+` del cuadro de SUSE Observability Helm ejecute estos comandos para restaurar la copia de seguridad:

. Establece el contexto y el espacio de nombres activos:
+
[,bash]
----
  kubectl config use-context observability
  kubectl config set-context --current --namespace=suse-observability
----

. Cargue el archivo de copia de seguridad creado anteriormente, en este caso `+sts-backup-20241024-1423.sty+` (asegúrese de utilizar la ruta completa si es necesario):
+
[,bash]
----
./upload-configuration-backup.sh sts-backup-20241024-1423.sty
----

. Restaurar la copia de seguridad (esto requerirá 1Gi de memoria y 1 núcleo en el clúster), esto puede tomar un tiempo para crear un trabajo de Kubernetes e iniciar el pod:
+
[,bash]
----
 ./restore-configuration-backup.sh sts-backup-20241024-1423.sty
----
+
Asegúrese de responder a `+yes+` para confirmar que la eliminación de todos los datos es correcta.

. Vuelve a escalar todos los despliegues:
+
[,bash]
----
./scale-up.sh
----

Ahora SUSE Observability tiene exactamente la misma configuración que StackState y estamos listos para empezar a utilizarlo. Tenga en cuenta que, dado que se utiliza la misma URL, puede ser necesario actualizar el navegador la primera vez.

=== Correr lado a lado

En este escenario, SUSE Observability ingestará nuevos datos y se encargará de ejecutar monitores y enviar notificaciones. StackState sólo ofrecerá acceso a los datos históricos.

En algún momento será necesario cambiar el tráfico de StackState a SUSE Observability. La solución que limita el impacto en sus usuarios y en los agentes instalados es configurar SUSE Observability con la URL utilizada originalmente por StackState. Esta guía reutilizará la URL de StackState (`+stackstate.demo.stackstate.io+`) mientras que la "antigua" StackState será accesible bajo una nueva URL `+stackstate-old.demo.stackstate.io+`. Si se utiliza un proveedor OIDC para la autenticación, será necesario añadir/actualizar la URL `+stackstate-old+` en la configuración del proveedor OIDC y en la configuración de StackState.

También es posible instalar SUSE Observability bajo una nueva URL, en ese caso tendrá que actualizar el agente y los recopiladores de Open Telemetry para utilizar la nueva URL o utilizar otro método para redirigir el tráfico.

En resumen, antes de la migración la configuración es StackState ejecutándose en el espacio de nombres `+stackstate+` con la URL `+https://stackstate.demo.stackstate.io+`. Esto se migrará a:

* SUSE Observability en el espacio de nombres `+suse-observability+` con URL `+stackstate.demo.stackstate.io+`, esta será la nueva instancia activa
* StackState en el espacio de nombres `+stackstate+` con URL `+https://stackstate-old.demo.stackstate.io+`, esto sólo tendrá datos históricos

==== Instalar SUSE Observability

Instale SUSE Observability en un espacio de nombres distinto de StackState para evitar conflictos. Se recomienda utilizar el mismo espacio de nombres que en la documentación, `+suse-observability+`.

El mayor cambio para la instalación es que ahora hay soporte para perfiles, por favor seleccione el perfil que se ajuste a su cluster observado usando los xref:/setup/install-stackstate/requirements.adoc#_resource_requirements[requerimientos] y úselo para generar los valores como se documenta en la guía de instalación. Los valores personalizados de Helm para StackState son compatibles con SUSE Observability. Sin embargo, los valores para personalizar los recursos deben ser eliminados en favor de los nuevos perfiles, vamos a mantenerlos en un archivo llamado `+custom-values-no-resources.yaml+`. Por ahora, excluya también la configuración de entrada de la instalación de SUSE Observability.

Para instalar SUSE Observability siga la xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[guía de instalación] con unas pequeñas modificaciones en la generación de valores para realizar la migración:

* utilice el perfil seleccionado que se ajuste a su entorno y a sus valores personalizados (actualizados).
* obtener el `+global.receiverApiKey+` de los valores de StackState y proporcionarlo como argumento extra a la generación de valores.
* para la URL base que debe proporcionarse utilizamos la misma URL que la instalación actual de StackState: `+https://stackstate.demo.stackstate.io+`

Así pues, el paso de generación de valores es el siguiente (utilizando de nuevo nuestro ejemplo, con el perfil más pequeño):

[,bash]
----
export VALUES_DIR=.
helm template \
  --set license='<your license>' \
  --set receiverApiKey='our-old-api-key' \
  --set baseUrl='https://stackstate.demo.stackstate.io' \
  --set sizing.profile='10-nonha' \
  suse-observability-values \
  suse-observability/suse-observability-values --output-dir $VALUES_DIR
----

El comando de instalación de Helm es el mismo que en los documentos de instalación, con la opción de incluir el archivo de valores `+custom-values-no-resources.yaml+` si lo tiene.

[NOTE]
====
La instalación generará por defecto una nueva contraseña de administrador. Si está utilizando la autenticación estándar y desea mantener la misma contraseña de administrador que antes, deberá especificarla en el paso de generación de valores (o editarla después de generar los valores).
====


==== Restaurar la copia de seguridad de la configuración

Ahora que SUSE Observability está instalado, se puede restaurar la copia de seguridad de la configuración. El cuadro de SUSE Observability Helm viene con un conjunto similar de herramientas de copia de seguridad xref:/setup/data-management/backup_restore/configuration_backup.adoc[documentadas aquí]. *Estos no son los mismos que para StackState 6.x*, así que asegúrese de obtener los scripts del directorio `+restore+` de la *tabla SUSE Observability Helm* para restaurar la copia de seguridad.

Desde el directorio `+restore+` del cuadro de SUSE Observability Helm ejecute estos comandos para restaurar la copia de seguridad:

. Establece el contexto y el espacio de nombres activos:
+
[,bash]
----
  kubectl config use-context observability
  kubectl config set-context --current --namespace=suse-observability
----

. Cargue el archivo de copia de seguridad creado anteriormente, en este caso `+sts-backup-20241024-1423.sty+` (asegúrese de utilizar la ruta completa si es necesario):
+
[,bash]
----
./upload-configuration-backup.sh sts-backup-20241024-1423.sty
----

. Restaurar la copia de seguridad (esto requerirá 1Gi de memoria y 1 núcleo en el clúster), esto puede tomar un tiempo para crear un trabajo de Kubernetes e iniciar el pod:
+
[,bash]
----
 ./restore-configuration-backup.sh sts-backup-20241024-1423.sty
----
+
Comprueba que estás en el espacio de nombres suse-observability y no ya en el espacio de nombres StackState, sólo entonces responde a `+yes+` para confirmar que la eliminación de todos los datos está bien.

. Vuelve a escalar todos los despliegues:
+
[,bash]
----
./scale-up.sh
----

Ahora SUSE Observability tiene exactamente la misma configuración que StackState y estamos listos para empezar a utilizarlo.

==== Prepárate para reducir StackState

Para asegurarse de que nada cambia en la antigua configuración "StackState" y también para reducir su uso de recursos, un número de despliegues StackState debe ser reducido a 0 réplicas. La mejor manera de hacerlo es a través de los valores de Helm, de esa manera cualquier otro cambio de configuración no escalará accidentalmente algunos de los despliegues de nuevo.

Cree un nuevo archivo `+scaled-down.yaml+` y guárdelo junto a su StackState `+values.yaml+` (o edite su `+values.yaml+` existente para StackState para incluir o actualizar estas claves):

[,yaml]
----
common:
  deployment:
    replicaCount: 0
  statefulset:
    replicaCount: 0
anomaly-detection:
  enabled: false
backup:
  enabled: false
stackstate:
  components:
    correlate:
      replicaCount: 0
    checks:
      replicaCount: 0
    healthSync:
      replicaCount: 0
    e2es:
      replicaCount: 0
    notification:
      replicaCount: 0
    receiver:
      replicaCount: 0
    state:
      replicaCount: 0
    sync:
      replicaCount: 0
    slicing:
      replicaCount: 0
    vmagent:
      replicaCount: 0
  features:
    server:
      split: true
opentelemetry:
  enabled: false
----

Este archivo se utilizará cuando se cambie la entrada para StackState. Cuando ya no se reciben datos de agentes o telemetría abierta, estos servicios StackState no son necesarios.

==== Desviar el tráfico

El redireccionamiento del tráfico cambiará tanto el tráfico del agente como los usuarios de StackState a SUSE Observability. Para ello, se necesitan dos pasos: en primer lugar, cambie StackState a una nueva URL y, a continuación, configure la entrada de SUSE Observability para utilizar la URL original de StackState. Entre estos pasos, SUSE Observability/StackState estará temporalmente inaccesible, pero los agentes almacenarán en caché los datos y los enviarán cuando puedan conectarse de nuevo.

. Tome la configuración de entrada de StackState y cópiela en los valores que tiene para SUSE Observability, o haga una copia en un archivo de valores `+ingress.yaml+` separado, junto a los generados `+baseConfig_values.yaml+` y `+sizing_values.yaml+`.
. Actualizar los valores de entrada para StackState para utilizar una URL diferente, aquí lo cambiamos de `+stackstate+` a `+stackstate-old+`:
+
[,yaml]
----
 ingress:
   annotations:
     nginx.ingress.kubernetes.io/proxy-body-size: 100m
   enabled: true
   hosts:
     - host: "stackstate-old.demo.stackstate.io"
   tls:
     - hosts:
         - "stackstate-old.demo.stackstate.io"
       secretName: tls-secret-stackstate-old

 opentelemetry-collector:
   ingress:
     enabled: true
     annotations:
       nginx.ingress.kubernetes.io/proxy-body-size: "50m"
       nginx.ingress.kubernetes.io/backend-protocol: GRPC
     hosts:
       - host: otlp-stackstate-old.demo.stackstate.io
         paths:
           - path: /
             pathType: Prefix
             port: 4317
     tls:
       - hosts:
           - otlp-stackstate-old.demo.stackstate.io
         secretName: tls-secret-stackstate-old-otlp
----

. Edite el `+values.yaml+` original de StackState y actualice el valor `+stackstate.baseUrl+` para utilizar también la nueva URL (en este caso `+https://stackstate-old.demo.stackstate.io+`).
. Ejecute la actualización de helm para StackState e incluya la configuración de entrada actualizada para que comience a utilizar la entrada de `+stackstate-old.demo.stackstate.io+`. Incluya también los valores de `+scaled-down.yaml+` del paso anterior y asegúrese de incluir todos los archivos de valores utilizados durante la instalación de StackState:
+
----
  helm upgrade \
   --install \
   --namespace stackstate \
   --values stackstate-values/values.yaml \
   --values stackstate-values/stackstate-ingress.yaml \
   --values stackstate-values/scaled-down.yaml \
 stackstate \
 stackstate/stackstate-k8s
----

. Ejecute la xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[actualización] de xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[helm] para SUSE Observability, para empezar a utilizar la URL original `+stackstate.demo.stackstate.io+` (asegúrese de incluir todos los archivos de valores utilizados durante la instalación de SUSE Observability, pero ahora incluya también el `+ingress.yaml+`):
+
----
 export VALUES_DIR=.
 helm upgrade \
   --install \
   --namespace suse-observability \
   --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
   --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
   --values ingress.yaml \
 suse-observability \
 suse-observability/suse-observability
----

Ahora los usuarios pueden ir a `+https://stackstate.demo.stackstate.io+` para obtener SUSE Observability con todas las funciones conocidas de StackState y datos en directo. Es posible que la primera vez los usuarios tengan que pulsar actualizar para forzar la carga de la nueva aplicación.

Pueden consultar los datos históricos en `+https://stackstate-old.demo.stackstate.io+`.

==== Desinstalar StackState

Cuando la instalación de StackState ya no sea necesaria, puede desinstalarse utilizando el https://docs.stackstate.com/6.0/self-hosted-setup/uninstall[procedimiento de desinstalación de].


== Actualizar la configuración de los colectores abiertos de telemetría

SUSE Observability tiene un cambio en su autenticación. StackState utilizaba un token portador con el esquema `+StackState+`, pero SUSE Observability utiliza el esquema `+SUSEObservability+`. Actualice los valores de los colectores abiertos de telemetría instalados para cambiar de:

[,yaml]
----
config:
  extensions:
    bearertokenauth:
      scheme: StackState
      token: "${env:API_KEY}"
----

a

[,yaml]
----
config:
  extensions:
    bearertokenauth:
      scheme: SUSEObservability
      token: "${env:API_KEY}"
----

Utilice los valores actualizados para actualizar los recopiladores instalados con el comando `+helm upgrade+`, consulte también xref:/setup/otel/collector.adoc#_deploy_the_collector[desplegar el recopilador de telemetría abierto] para obtener más detalles.

== Actualizar mochilas

Vaya a `+https://your-stackstate-instance/#/stackpacks/+` o abra la vista general de StackPacks a través del menú principal. A partir de ahí, vaya a todas las mochilas instaladas y pulse el botón "Actualizar" para obtener la nueva versión de SUSE Observability de la mochila.

== Migrar agentes

El último paso en la migración a SUSE Observability es actualizar todos los agentes instalados. Esto no tiene que hacerse inmediatamente, sino que puede hacerse en un momento conveniente para cada clúster específico, ya que SUSE Observability es compatible con versiones anteriores del agente StackState.

La migración es un proceso sencillo de dos pasos:

. Desinstalar el agente StackState
. Instale el agente de SUSE Observability

Es importante desinstalar primero el agente antiguo, ya que no es posible ejecutar ambos agentes al mismo tiempo. La desinstalación del agente en un cluster se realiza de la siguiente manera:

[,bash]
----
helm uninstall -n stackstate stackstate-k8s-agent
----

Si ha utilizado un espacio de nombres o un nombre de versión diferentes, actualice el comando en consecuencia.

Navegue hasta `+https://your-stackstate-instance/#/stackpacks/kubernetes-v2+`. Busque el clúster en el que está actualizando el agente en la lista de instancias de StackPack y copie y ejecute el comando helm install para su distribución de Kubernetes. Si tiene valores personalizados puede incluirlos sin modificación con un argumento `+--values+`, los valores del agente SUSE Observability utilizan la misma nomenclatura que el agente StackState.
