include::partial$variables.adoc[]
= Publier des politiques dans Artifact Hub
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Publier les politiques {project-name} dans Artifact Hub en créant un dépôt Git bien formaté et en configurant les actions GitHub pour l'empaquetage automatisé, facilitant ainsi l'intégration continue.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-policy-developer", "kubewarden-distributor", "kubewarden-integrator"].
:doc-topic: ["distributing-policies", "publish-policy-to-artifacthub"].
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "publishing policies", "artifact hub"].
:sidebar_label: Publier dans Artifact Hub
:sidebar_position: 40
:current-version: {page-origin-branch}

https://artifacthub.io/[Artifact Hub] est un site web où les utilisateurs peuvent trouver, installer et publier des paquets et des configurations pour les projets https://cncf.io[CNCF].

{project-name} peuvent être publiées sur Artifact Hub et rendues accessibles à un large public d'utilisateurs de la CNCF.

[NOTE]
====
Artifact Hub est une plateforme d'agrégation de contenu qui n'héberge pas les artefacts qui y sont publiés.

Artifact Hub vous oblige à héberger physiquement des référentiels d'images de conteneurs sur un registre de conteneurs ou un serveur web.
Pour plus d'informations sur la manière d'héberger vos politiques, reportez-vous à la section relative xref:explanations/distributing-policies.adoc[à la distribution des politiques].
====


Ce document se concentre sur les étapes nécessaires pour rendre une politique {short-project-name} découvrable sur Artifact Hub.

== Préparez votre dépôt Git

Artifact Hub explore les dépôts Git à la recherche de fichiers de métadonnées spéciaux.

Il existe différents types de présentation pour le dépôt Git. Ils sont tous décrits en détail dans la https://artifacthub.io/docs/topics/repositories/#kubewarden-policies-repositories[documentation officielle de l'Artifact Hub sur le site].

Artifact Hub est flexible et vous permet d'organiser votre code de cette manière :

* Disposer d'un dépôt Git dédié à Artifact Hub : ce dépôt ne contiendra pas le code source de la politique. Il s'agit d'une collection de fichiers YAML requis par Artifact Hub.

* Ajoutez un répertoire Artifact Hub dans le dépôt Git contenant la source de votre politique. Il s'agit d'une itération de l'approche précédente, qui se concentre sur une seule politique, celle qui est définie dans le dépôt Git. Cette approche permet de conserver plusieurs versions de la politique publiée sur Artifact Hub.

* Ajoutez les fichiers `artifacthub-pkg.yml` et `artifacthub-repo.yml` à la racine du dépôt Git qui contient le code source de la politique. Cette approche est la plus simple. La seule limitation est que seule la dernière version de la politique sera visible sur Artifact Hub.

La dernière approche est utilisée dans nos modèles de politiques officielles. Le dépôt Git qui est échafaudé inclut le fichier `artifacthub-repo.yml`, et nos actions GitHub génèrent et poussent le `artifacthub-pkg.yml` vers une branche`artifacthub` pour que Artifact Hub puisse l'utiliser.

== Étapes de la publication

Avant de publier une politique dans Artifact Hub, vous devez créer un comptehttps://artifacthub.io/[].

Avant de publier la politique, assurez-vous que votre dépôt Git a la bonne mise en page, avec un `metadata.yml` bien formaté et les annotations obligatoires.

Si vous souhaitez le faire manuellement, vous pouvez créer le fichier `artifacthub-pkg.yml` en effectuant un `kwctl scaffold artifacthub` (avec la version `>= 1.23`). Cette commande prend le `metadata.yml` dans le chemin actuel et produit un`artifacthub-pkg.yml`. Le site `artifacthub-pkg.yml` contient des champs tels que`version:`, `createdAt:`, qui doivent correspondre à un format spécifique et être à jour. https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml[ici.]Le format du site `artifacthub-pkg.yml` est décrit

Si vous utilisez nos Actions GitHub >= `v4.0.0`, le flux de production peut être configuré avec l'entrée `artifacthub: true`. Si elle est configurée de la sorte, après une publication réussie (après que la politique a été construite, signée et poussée avec succès), nos actions GitHub ont un dernier travail qui génère le`artifacthub-pkg.yml` pour vous, puis commite et pousse les changements vers la branche`artifacthub`. Les fichiers canoniques sont toujours ceux de la branche `main`. Pour le comportement des versions précédentes de nos Actions GitHub, voir la documentation des versions antérieures à 1.23.

Enfin, veillez à ce que votre politique soit publiée dans un registre de conteneurs ou sur un serveur web.

[NOTE]
====
Pour l'instant, le contenu du fichier `artifacthub-repo.yml` n'est pas pertinent.
====


Une fois que tout est en place, connectez-vous à Artifact Hub et allez sur votrehttps://artifacthub.io/control-panel/repositories?page=1[plan de contrôle].

Décidez si vous voulez publier la politique en tant qu'utilisateur ou sous une organisation Artifact Hub à laquelle vous appartenez. Pour ce faire, il suffit de choisir le bon _"contexte du panneau de contrôle"._

Cliquez ensuite sur le bouton _"Ajouter"_ et remplissez le formulaire :

* Choisissez _"{short-project-name} policies"_ comme type.
* Saisissez un _"Nom"_ et un _"Nom d'affichage"_ de votre choix.
* Saisissez l'URL de votre dépôt Git.
* Saisissez `artifacthub` comme branche à suivre.

Enfin, appuyez sur le bouton _"Ajouter"_. Cela vous ramènera à la page _"Dépôts"_, où vous verrez votre dépôt fraîchement créé.

Chaque dépôt comporte plusieurs champs d'information. Trouvez la propriété _"ID"_ du référentiel que vous venez de créer et copiez-la.

Retournez dans votre dépôt Git et éditez le fichier `artifacthub-repo.yml`. Assurez-vous que la clé`repositoryID` qui se trouve dans le document a la valeur que vous venez de copier à partir de la page web Artifact Hub.

[TIP]
====
Le format du fichier `artifacthub-repo.yml` est définihttps://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml[ici].

Il est maintenant temps d'apporter d'autres modifications à ce fichier.
====


Une fois que vous avez terminé les modifications, livrez le fichier `artifacthub-repo.yml`mis à jour et poussez-le. Lors de la prochaine analyse, Artifact Hub trouvera ce fichier et ajoutera lehttps://artifacthub.io/docs/topics/repositories/#verified-publisher[badge]à votre dépôt Artifact Hub.

== Maintenir la synchronisation du Hub Artifact

N'oubliez pas de mettre à jour le contenu du fichier `artifacthub-pkg.yml` chaque fois que vous publiez une nouvelle version de votre politique. Par exemple, vous devez mettre à jour le champ`io.kubewarden.policy.version` (qui correspond généralement à la balise OCI de la politique) et toute autre annotation que vous souhaitez modifier.

[NOTE]
====
Le contenu du fichier `artifacthub-repo.yml` ne doit pas être modifié.
====

