include::partial$variables.adoc[]
= Introdução à CEL
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Conheça a CEL (Computation Expression Language) como uma linguagem de expressão rápida, portátil e segura, projetada para regras de validação do Kubernetes e extensões da API do Kubernetes.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "políticas de escrita", "introdução"].
:current-version: {page-origin-branch}

A https://cel.dev[Common Expression Language (CEL)] é uma linguagem de expressão de uso geral projetada para ser rápida, portátil e de execução segura. O CEL, como linguagem, é seguro para a memória, livre de efeitos colaterais, com terminação (os programas não podem fazer loop infinito) e com tipagem forte e dinâmica. Você pode saber mais sobre o CEL emhttps://cel.dev[cel.dev] e praticá-lo no https://playcel.undistro.io[CEL playground].

== CEL no Kubernetes

O CEL foi escolhido como a linguagem para as regras de validação do Kubernetes, pois as expressões do CEL podem ser facilmente incorporadas aos esquemas de CRD e compiladas e verificadas quanto ao tipo "antes do tempo" (quando os CRDs são criados e atualizados). Por esses motivos e por suas características gerais, ele é um candidato perfeito para estender a API do Kubernetes.

Marcado como estável com o Kubernetes 1.30, é possível usar o CEL emhttps://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy[ValidatingAdmissionPolicies]e outras regras de validação. Para obter mais informações, consulte os documentos do Kuberneteshttps://kubernetes.io/docs/reference/using-api/cel[aqui].

=== Bibliotecas de funções do Kubernetes

As regras de validação do Kubernetes CEL têm acesso a várias bibliotecas de funções:

* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#list-of-standard-definitions[Funções padrão da CEL]
* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#macros[Macros padrão CEL]
* https://pkg.go.dev/github.com/google/cel-go/ext#Strings[Biblioteca de funções de cadeia estendida CEL]
* https://kubernetes.io/docs/reference/using-api/cel/#kubernetes-cel-libraries[Bibliotecas de extensão Kubernetes CEL], com funções suplementares para listas, regex, URLs, autorizadores, quantidades, tipos opcionais, comparações numéricas etc.

== CEL em {project-name}: `+cel-policy+`

{short-project-name} fornece https://github.com/kubewarden/cel-policy[cel-policy].
Essa é uma política que cria e agrupa o interpretadorhttps://pkg.go.dev/github.com/google/cel-go[cel-go] upstream e também as diferentes bibliotecas listadas acima e disponíveis para CEL no Kubernetes em`+apiextensions-apiserver+`.

Além disso, o site `+cel-policy+` inclui uma *biblioteca de extensão CEL{short-project-name} * que expõe os recursos do host https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[como CEL nativo] do site{short-project-name}:

* Verificação do Sigstore
* Interação com a OCI
* Funções criptográficas
* Operações de rede
* Acesso aos recursos do Kubernetes

Isso significa que o `+cel-policy+` é um superconjunto do Kubernetes CEL e compatível com as versões anteriores. É possível reutilizar o CEL escrito para o Kubernetes básico e/ou usar os recursos adicionados por {short-project-name}.

O `+cel-policy+` é fornecido compilado e se comporta como um interpretador CEL. Os usuários da política passam as expressões CEL desejadas no site `+spec.settings+` do (Cluster)AdmissionPolicy e, graças aos recursos do CEL, a expressão é compilada e verificada por digitação quanto à exatidão ao criar ou atualizar o (Cluster)AdmissionPolicy. Isso significa que não há necessidade de compilações personalizadas do`+cel-policy+`.

=== Benefícios do {short-project-name}'s `+cel-policy+` em comparação com o ValidatingAdmissionPolicies

O {short-project-name} `+cel-policy+`:

* Seu código CEL é compatível com as versões anteriores de ValidatingAdmissionPolicies.
* Ao contrário do ValidatingAdmissionPolicies, ele não precisa de uma vinculação como o ValidatingAdmissionPolicyBinding, pois isso está incluído nas definições do {short-project-name}(Cluster)Admissionpolicies.
* Pode ser implantado em clusters que não oferecem suporte a ValidatingAdmissionPolicies.
* É sensível ao contexto e usa as permissões de granularidade fina do {short-project-name} para xref:../../../reference/spec/05-context-aware-policies.adoc[reconhecimento do contexto].
* É implantado como (Cluster)AdmissionPolicy.
* Beneficia-se do rastreamento e da telemetria das políticas do {short-project-name}.
* Ele será levado em consideração pelo Audit Scanner.
* Pode ser desenvolvido e testado fora do cluster graças ao kwctl.
