= 机器上机
:revdate: 2025-11-06
:page-revdate: {revdate}

机器入驻服务的目标是在{elemental-product-name} Operator 目录xref:references/machineinventory-reference.adoc[（MachineInventory]资源）中注册新机器，并为主机提供操作系统，应用所需的配置。

机器上机包括以下步骤：

* 用户创建xref:references/machineregistration-reference.adoc[机器注册]资源：机器注册包括操作系统安装所需的配置。
一旦创建了机器注册（MachineRegistration），{elemental-product-name} Operator 就会公开一个 HTTP_注册端点_：这是入网主机向操作员注册所需的入口点。
* 用户通过xref:references/seedimage-reference.adoc[SeedImage]资源请求自安装镜像：它只需要引用机器注册资源和与{elemental-product-name} Toolkit 兼容的操作系统容器镜像。
一旦创建了 SeedImage，{elemental-product-name} Operator 就会触发自安装image: once completed, the URL is exposed in the `+status.downloadURL+` field of the xref:references/seedimage-reference.adoc[SeedImage]资源的构建过程。
* 用户下载自安装镜像，并用它启动未配置的主机：主机https://documentation.suse.com/cloudnative/os-manager/latest/en/rancher-os-management/authentication.html[验证] {elemental-product-name} Operator 的_注册端点_，获取存储在 MachineRegistration 中的完整配置，并在本地存储设备上安装操作系统。一旦主机完成注册过程，{elemental-product-name} 操作员就会创建一个唯一的xref:references/machineinventory-reference.adoc[MachineInventory]资源来跟踪主机。
自安装镜像可用于搭载任意数量的主机。
