= agente k3s
:page-languages: [en, ja, ko, zh]
:revdate: 2025-01-15
:page-revdate: {revdate}

En esta sección, aprenderá a configurar el agente K3s.

Tenga en cuenta que los servidores también ejecutan un agente, por lo que todas las banderas enumeradas en esta página también son válidas para su uso en servidores.

Las opciones se documentan en esta página como indicadores de la CLI, pero también se pueden pasar como opciones del archivo de configuración. Consulte la documentación sobre xref:installation/configuration.adoc#_configuration_file[archivos] de configuración para obtener más información sobre el uso de archivos de configuración YAML.

== Registro

|===
| Bandera | Por defecto | Descripción

| `+-v+` valor
| 0
| Número para la verbosidad del nivel de registro

| `+--vmodule+` valor
| N/A
| Lista separada por comas de los parámetros FILE_PATTERN=LOG_LEVEL para el registro filtrado por archivos

| `+--log value, -l+` valor
| N/A
| Registrar en archivo

| `+--alsologtostderr+`
| N/A
| Registrar en el error estándar y en el archivo (si está configurado)
|===

== Opciones de clúster

|===
| Bandera | Variable de entorno | Descripción

| `+--token value, -t+` valor
| `+K3S_TOKEN+`
| Token que se utilizará para la autenticación

| `+--token-file+` valor
| `+K3S_TOKEN_FILE+`
| Archivo de token que se utilizará para la autenticación

| `+--server value, -s+` valor
| `+K3S_URL+`
| Servidor al que conectarse
|===

== Oyente

|===
| Bandera |  Por defecto | Descripción
| `+--bind-address+`
| 0.0.0.0
| k3s dirección de enlace
|===

== Data

|===
| Bandera | Por defecto | Descripción

| `+--data-dir value, -d+` valor
| "/var/lib/rancher/k3s"
| Carpeta para mantener el estado
|===

== Nodo

|===
| Bandera | Variable de entorno | Descripción

| `+--node-name+` valor
| `+K3S_NODE_NAME+`
| Nombre del nodo

| `+--with-node-id+`
| N/A
| Añadir id al nombre del nodo

| `+--node-label+` valor
| N/A
| Registro e inicio de kubelet con un conjunto de etiquetas

| `+--node-taint+` valor
| N/A
| Registro de kubelet con un conjunto de manchas

| `+--protect-kernel-defaults+`
| N/A
| Comportamiento del ajuste del núcleo. Si se establece, error si las sintonizables del kernel son diferentes de las predeterminadas por kubelet.

| `+--selinux+`
| `+K3S_SELINUX+`
| Habilitar SELinux en containerd

| `+--lb-server-port+` valor
| `+K3S_LB_SERVER_PORT+`
| Puerto local para el balanceador de carga del cliente supervisor. Si el supervisor y el apiserver no están colocados, se utilizará un puerto adicional 1 menor que este para el balanceador de carga del cliente apiserver. (por defecto: 6444)
|===

== Tiempo de ejecución

|===
| Bandera | Por defecto | Descripción

| `+--container-runtime-endpoint+`
| N/A
| Deshabilitar containerd incrustado y utilizar el socket CRI en la ruta dada; cuando se utiliza con --docker esto establece la ruta del socket docker

| `+--default-runtime+`
| N/A
| Establecer el tiempo de ejecución por defecto en containerd

| `+--image-service-endpoint+`
| N/A
| Desactiva el servicio de imagen containerd incrustado y utiliza el socket del servicio de imagen remoto en la ruta dada. Si no se especifica, por defecto es --container-runtime-endpoint.

| `+--pause-image+` valor
| "docker.io/rancher/pause:3.1"
| Imagen de pausa personalizada para containerd o docker sandbox

| `+--private-registry+` valor
| "/etc/rancher/k3s/registries.yaml"
| Archivo de configuración del registro privado
|===

== Red

|===
| Bandera | Variable de entorno | Descripción

| `+--node-ip value, -i+` valor
| N/A
| Dirección IP a anunciar para el nodo

| `+--node-external-ip+` valor
| N/A
| Dirección IP externa a anunciar para el nodo

| `+--node-internal-dns+`
| N/A
| direcciones DNS internas a anunciar para el nodo

| `+--node-external-dns+`
| N/A
| direcciones DNS externas a anunciar para el nodo

| `+--resolv-conf+` valor
| `+K3S_RESOLV_CONF+`
| Archivo resolv.conf de Kubelet

| `+--flannel-iface+` valor
| N/A
| Anular la interfaz de franela por defecto

| `+--flannel-conf+` valor
| N/A
| Anular el archivo de configuración por defecto de la franela

| `+--flannel-cni-conf+` valor
| N/A
| Anular el archivo de configuración por defecto de flannel cni
|===

== Banderas personalizadas

|===
| Bandera | Descripción

| `+--kubelet-arg+` valor
| Bandera personalizada para el proceso kubelet

| `+--kube-proxy-arg+` valor
| Bandera personalizada para el proceso kube-proxy
|===

== Experimental

|===
| Bandera | Descripción

| `+--rootless+`
| Ejecutar sin raíces

| `+--docker+`
| Utilice cri-dockerd en lugar de containerd

| `+--enable-pprof+`
| Habilitar punto final pprof en puerto supervisor

| `+--prefer-bundled-bin+`
| Preferir los binarios del espacio de usuario empaquetados a los binarios del host

| `+--disable-default-registry-endpoint+`
| Véase "xref:installation/private-registry.adoc#_default_endpoint_fallback[Repliegue del punto final por defecto]"

| `+--vpn-auth+`
| Véase "xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental[Integración con el proveedor VPN Tailscale]". 

| `+--vpn-auth-file+`
| Véase "xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental[Integración con el proveedor VPN Tailscale]".
|===

== Obsoleto

|===
| Bandera | Variable de entorno | Descripción

| `+--no-flannel+`
| N/A
| Utilice `+--flannel-backend=none+`

| `+--cluster-secret+` valor
| `+K3S_CLUSTER_SECRET+`
| Utilice `+--token+`
|===

[#_node_labels_and_taints_for_agents]
== Etiquetas de nodos y manchas para agentes

Los agentes K3s pueden configurarse con las opciones `+--node-label+` y `+--node-taint+` que añaden una etiqueta y una mancha al kubelet. Las dos opciones sólo añaden etiquetas y/o tintas en el momento del registro, por lo que sólo pueden añadirse una vez y no volver a cambiarse después ejecutando comandos K3s.

A continuación se muestra un ejemplo de cómo añadir etiquetas y una mancha:

[,bash]
----
     --node-label foo=bar \
     --node-label hello=world \
     --node-taint key1=value1:NoExecute
----

Si desea cambiar las etiquetas y tintas de los nodos después de registrarlos, debe utilizar `+kubectl+`. Consulte la documentación oficial de Kubernetes para obtener información detallada sobre cómo añadir https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[labels.] taints y https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#add-a-label-to-a-node[] node

== Ayuda CLI del Agente K3s

____
Si una opción aparece entre paréntesis a continuación, por ejemplo `+[$K3S_URL]+`, significa que la opción se puede pasar como una variable de entorno con ese nombre.
____

[,bash]
----
NAME:
   k3s agent - Run node agent

USAGE:
   k3s agent [OPTIONS]

OPTIONS:
   --config FILE, -c FILE                     (config) Load configuration from FILE (default: "/etc/rancher/k3s/config.yaml") [$K3S_CONFIG_FILE]
   --debug                                    (logging) Turn on debug logs [$K3S_DEBUG]
   -v value                                   (logging) Number for the log level verbosity (default: 0)
   --vmodule value                            (logging) Comma-separated list of FILE_PATTERN=LOG_LEVEL settings for file-filtered logging
   --log value, -l value                      (logging) Log to file
   --alsologtostderr                          (logging) Log to standard error as well as file (if set)
   --token value, -t value                    (cluster) Token to use for authentication [$K3S_TOKEN]
   --token-file value                         (cluster) Token file to use for authentication [$K3S_TOKEN_FILE]
   --server value, -s value                   (cluster) Server to connect to [$K3S_URL]
   --data-dir value, -d value                 (agent/data) Folder to hold state (default: "/var/lib/rancher/k3s") [$K3S_DATA_DIR]
   --node-name value                          (agent/node) Node name [$K3S_NODE_NAME]
   --with-node-id                             (agent/node) Append id to node name
   --node-label value                         (agent/node) Registering and starting kubelet with set of labels
   --node-taint value                         (agent/node) Registering kubelet with set of taints
   --image-credential-provider-bin-dir value  (agent/node) The path to the directory where credential provider plugin binaries are located (default: "/var/lib/rancher/credentialprovider/bin")
   --image-credential-provider-config value   (agent/node) The path to the credential provider plugin config file (default: "/var/lib/rancher/credentialprovider/config.yaml")
   --selinux                                  (agent/node) Enable SELinux in containerd [$K3S_SELINUX]
   --lb-server-port value                     (agent/node) Local port for supervisor client load-balancer. If the supervisor and apiserver are not colocated an additional port 1 less than this port will also be used for the apiserver client load-balancer. (default: 6444) [$K3S_LB_SERVER_PORT]
   --protect-kernel-defaults                  (agent/node) Kernel tuning behavior. If set, error if kernel tunables are different than kubelet defaults.
   --container-runtime-endpoint value         (agent/runtime) Disable embedded containerd and use the CRI socket at the given path; when used with --docker this sets the docker socket path
   --default-runtime value                    (agent/runtime) Set the default runtime in containerd
   --image-service-endpoint value             (agent/runtime) Disable embedded containerd image service and use remote image service socket at the given path. If not specified, defaults to --container-runtime-endpoint.
   --pause-image value                        (agent/runtime) Customized pause image for containerd or docker sandbox (default: "rancher/mirrored-pause:3.6")
   --snapshotter value                        (agent/runtime) Override default containerd snapshotter (default: "overlayfs")
   --private-registry value                   (agent/runtime) Private registry configuration file (default: "/etc/rancher/k3s/registries.yaml")
   --disable-default-registry-endpoint        (agent/containerd) Disables containerd fallback default registry endpoint when a mirror is configured for that registry
   --nonroot-devices                          (agent/containerd) Allows non-root pods to access devices by setting device_ownership_from_security_context=true in the containerd CRI config
   --node-ip value, -i value                  (agent/networking) IPv4/IPv6 addresses to advertise for node
   --bind-address value                       (listener) k3s bind address (default: 0.0.0.0)
   --node-external-ip value                   (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
   --node-internal-dns value                  (agent/networking) internal DNS addresses to advertise for node
   --node-external-dns value                  (agent/networking) external DNS addresses to advertise for node
   --resolv-conf value                        (agent/networking) Kubelet resolv.conf file [$K3S_RESOLV_CONF]
   --flannel-iface value                      (agent/networking) Override default flannel interface
   --flannel-conf value                       (agent/networking) Override default flannel config file
   --flannel-cni-conf value                   (agent/networking) Override default flannel cni config file
   --kubelet-arg value                        (agent/flags) Customized flag for kubelet process
   --kube-proxy-arg value                     (agent/flags) Customized flag for kube-proxy process
   --enable-pprof                             (experimental) Enable pprof endpoint on supervisor port
   --rootless                                 (experimental) Run rootless
   --prefer-bundled-bin                       (experimental) Prefer bundled userspace binaries over host binaries
   --docker                                   (agent/runtime) (experimental) Use cri-dockerd instead of containerd
   --vpn-auth value                           (agent/networking) (experimental) Credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH]
   --vpn-auth-file value                      (agent/networking) (experimental) File containing credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH_FILE]
   --disable-apiserver-lb                     (agent/networking) (experimental) Disable the agent client-side load-balancer and connect directly to the configured server address
----
