include::partial$variables.adoc[]

= Offenlegung der Sicherheit
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Investigative Sicherheitsforscher arbeiten mit dem Team von {project-name} zusammen, um Schwachstellen mithilfe von Protokollen zur verantwortungsvollen Offenlegung zu ermitteln.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["security", "disclosure"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "kubernetes", "security", "disclosure"]
:sidebar_label: Offenlegung der Sicherheit
:sidebar_position: 80
:current-version: {page-origin-branch}

Das Team von {project-name} schätzt die Untersuchungen von Sicherheitslücken, die von wohlmeinenden, ethischen Sicherheitsforschern durchgeführt werden. {short-project-name}folgt der Praxis der [verantwortungsvollen Offenlegung] (https://en.wikipedia.org/wiki/Responsible_disclosure), um die Benutzer von {short-project-name} bestmöglich vor den Auswirkungen von Sicherheitsproblemen zu schützen. Auf der Seite{short-project-name} bedeutet dies:

* {short-project-name} reagiert auf Sicherheitsvorfälle mit Vorrang.
* {short-project-name} Behebungen von Problemen werden so schnell wie möglich veröffentlicht, wobei die Prioritäten nach dem Risiko gesetzt werden.
* {short-project-name} informiert die Gemeinschaft stets transparent über alle Vorfälle, die sie betreffen.

Wenn Sie eine Sicherheitslücke in {short-project-name} gefunden haben, ist der einfachste Weg, eine Schwachstelle zu melden, diehttps://github.com/kubewarden/community/security/advisories[Registerkarte Sicherheit auf GitHub]. Dieser Mechanismus ermöglicht es den Betreuern, privat mit Ihnen zu kommunizieren, und Sie brauchen Ihre Nachrichten nicht zu verschlüsseln.

Alternativ können Sie sie verantwortungsbewusst offenlegen, indem Sie eine E-Mailxref:mailto:cncf-kubewarden-maintainers@lists.cncf.io.adoc[cncf-kubewarden-maintainers@lists.cncf.io]in einer *unverschlüsselten* Nachricht. Bitte diskutieren Sie mögliche Schwachstellen nicht in der Öffentlichkeit, ohne sie vorher mit uns abzustimmen.

Sie können sich auch in unseremhttps://kubernetes.slack.com/archives/C03L52JRAFM[] Slack-Room auf dem Kubernetes Slack Server unterhalten.

Nach dem Empfang das Sicherheitsteam:

* Er prüft den Bericht, verifiziert die Schwachstelle und antwortet mit einer Bestätigung und/oder fordert weitere Informationen an.
* Nach der Behebung des gemeldeten Sicherheitsproblems benachrichtigt {short-project-name} den Forscher, der dann die Möglichkeit hat, das Problem öffentlich zu machen.

Weitere Informationen über das Projekt Governance und Sicherheitspolitik finden Sie unter https://github.com/kubewarden/community[Community Repository].
