include::partial$variables.adoc[]
= Was ist {project-name}?
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie mehr über die Rolle von {project-name} bei der Verwaltung von Kubernetes-Richtlinien, die die Durchsetzung von Compliance und die Optimierung von Ressourcen umfasst.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["Einführung"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "cncf", "cncf sandbox", "kubernetes", "admission policy manager"]
:sidebar_label: Einführung
:sidebar_position: 1
:slug: /
:current-version: {page-origin-branch}

{project-name} ist eine Kubernetes Policy Engine.
Es soll die Universal Policy Engine für Kubernetes sein.

{intro-paragraph}

== Wie kann {project-name} helfen?

{short-project-name} bietet Flexibilität für die Zulassung und Durchsetzung von Richtlinien in einer Kubernetes-Umgebung.

=== Nutzen und Wert

- Verwenden Sie eine beliebige Programmiersprache, die https://webassembly.org[WebAssembly-Binärdateien] erzeugt, um Ihre Richtlinien zu schreiben.
- WebAssembly ermöglicht die Kompatibilität von Richtlinien für verschiedene Prozessoren und Betriebssysteme.
- Wiederverwendung von Richtlinien aus anderen Policy Engines, ohne dass diese neu geschrieben werden müssen.
- Verteilen Sie Richtlinien über standardisierte und sichere Mechanismen wie https://opencontainers.org[] OCI-konforme Register.
- Die Durchsetzung von Richtlinien bei der Zulassung stellt sicher, dass nur konforme Workloads ausgeführt werden.
- Der {short-project-name} Audit-Scanner überprüft aktiv und kontinuierlich die Durchsetzung von Richtlinien im Laufe der Zeit.
- Überprüfung der Richtlinien mit https://slsa.dev[SLSA] (Supply Chain Levels for Software Artifacts) Tools und Praktiken.
- {project-name} bietet einen umfassenden Ansatz für die Verwaltung der Zulassungspolitik.
- Die Mitgliedschaft in der CNCF und eine wachsende Open-Source-Community und ein Ökosystem helfen {short-project-name} bei Transparenz, Zusammenarbeit und Verbesserung.

=== Anwendungsfälle

- Sicherheitshärtung. Sie können beispielsweise Richtlinien zur Einschränkung von Containerrechten durchsetzen, Netzwerkrichtlinien durchsetzen oder unsichere Bildregistrierungen blockieren.
- Prüfung der Einhaltung der Vorschriften. Sicherstellen, dass die Arbeitslasten den organisatorischen oder gesetzlichen Standards und bewährten Verfahren entsprechen.
- Optimierung der Ressourcen. Durchsetzung von Ressourcenbeschränkungen und -quoten.

Eine weitere Dokumentation der Anwendungsfälle finden Sie auf der Seite xref:use-cases.adoc[Anwendungsfälle].

== Neu bei {short-project-name}?

Wenn Sie neu im Projekt {short-project-name} sind, beginnen Sie mit der xref:quick-start.adoc[Schnellstartanleitung] und der xref:explanations/architecture.adoc[Architekturseite].
Dann hängt es davon ab, wohin Ihre Interessen Sie führen. Für Richtlinienentwickler gibt es sprachspezifische Abschnitte in den Tutorials. Für Integratoren und Administratoren gibt es einen Abschnitt "How-Tos". Der Abschnitt "Erläuterungen" enthält nützliches Hintergrundmaterial. Außerdem gibt es ein xref:glossary.adoc[Glossar].

== Was ist WebAssembly?

Wie auf der https://webassembly.org/[offiziellen Website von] angegeben:

____
WebAssembly (abgekürzt Wasm) ist ein binäres Befehlsformat für eine stapelbasierte virtuelle Maschine. Wasm ist als portables Kompilierungsziel für Programmiersprachen konzipiert und ermöglicht den Einsatz im Web für Client- und Serveranwendungen.
____

Wasm wurde ursprünglich als Browser-"Erweiterung" konzipiert. Die WebAssembly-Gemeinschaft ist jedoch bestrebt, die Ausführung von Wasm-Code außerhalb von Browsern zu ermöglichen.

== Warum WebAssembly verwenden?

Benutzer können Kubernetes-Richtlinien in ihrer bevorzugten Programmiersprache schreiben, sofern die Toolchain Wasm-Binärdateien erzeugen kann.

Wasm-Module sind portabel, d.h. sie können auf allen Prozessorarchitekturen und Betriebssystemen laufen, sobald sie einmal erstellt wurden. So kann beispielsweise eine auf Apple Silicon entwickelte und erstellte Richtlinie ohne Konvertierung auf AMD64/Intel64-Linux laufen.

Die Verfasser von Politiken können ihre Fähigkeiten, Werkzeuge und bewährten Verfahren wiederverwenden. Policies sind "traditionelle" Programme, die wiederverwendbare Blöcke (reguläre Bibliotheken) haben können. Sie können sie lint und testen und in bestehende CI- und CD-Workflows integrieren.

== Verteilung der Politik

Sie können {short-project-name} Richtlinien mit einem Standard-Webserver bereitstellen oder, noch besser, sie in einem OCI-konformen Register alshttps://github.com/opencontainers/artifacts[OCI-Artefakte] veröffentlichen.

ifeval::["{build-type}" == "community"]

== Neutralität des Anbieters

{short-project-name} ist ein \link:https://contribute.cncf.io/maintainers/community/vendor-neutrality/[herstellerneutrales] Projekt, wie von der CNCF definiert.

endif::[]
