= FAQ
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

La FAQ est mise à jour périodiquement et vise à répondre aux questions les plus fréquemment posées par nos utilisateurs au sujet des K3.

== K3s peut-il remplacer Kubernetes ?

K3s est une distribution Kubernetes certifiée par la CNCF, et peut faire tout ce qui est requis d'un cluster Kubernetes standard. Il s'agit simplement d'une version plus légère. Voir la page de documentation xref:introduction.adoc[principale] pour plus de détails.

== Comment puis-je utiliser mon propre Ingress au lieu de Traefik ?

Il suffit de démarrer le serveur K3s avec `+--disable=traefik+` et de déployer votre ingress.

== K3s est-il compatible avec Windows ?

Pour l'instant, K3s n'est pas compatible avec Windows, mais nous sommes ouverts à cette idée dans le futur.

== Que sont exactement les serveurs et les agents ?

Pour en savoir plus sur les composants d'un serveur et d'un agent, voir la xref:architecture.adoc[page Architecture.]

== Comment puis-je construire à partir des sources ?

Veuillez vous référer au document K3s https://github.com/k3s-io/k3s/blob/main/BUILDING.md[BUILDING.md] pour les instructions.

== Où sont les journaux de bord des K3 ?

L'emplacement des journaux K3s varie en fonction du mode d'exécution de K3s et du système d'exploitation du nœud.

* Lorsqu'il est exécuté à partir de la ligne de commande, les journaux sont envoyés à stdout et stderr.
* Lors de l'exécution sous openrc, les journaux seront créés à l'adresse `+/var/log/k3s.log+`.
* Lorsqu'ils sont exécutés sous Systemd, les journaux sont envoyés à Journald et peuvent être consultés à l'aide de `+journalctl -u k3s+`.
* Les journaux de bord peuvent être consultés à l'adresse suivante : `+/var/log/pods+`.
* Les journaux de bord des conteneurs peuvent être consultés à l'adresse suivante : `+/var/lib/rancher/k3s/agent/containerd/containerd.log+`.

Vous pouvez générer des journaux plus détaillés en utilisant le drapeau `+--debug+` au démarrage de K3s (ou `+debug: true+` dans le fichier de configuration).

Kubernetes utilise un cadre de journalisation connu sous le nom de `+klog+`, qui utilise une configuration de journalisation unique pour tous les composants d'un processus.
Étant donné que K3s exécute tous les composants Kubernetes au sein d'un seul processus, il n'est pas possible de configurer différents niveaux de journaux ou destinations pour les composants Kubernetes individuels.
L'utilisation des args des composants `+-v=<level>+` ou `+--vmodule=<module>=<level>+` n'aura probablement pas l'effet escompté.

Voir xref:advanced.adoc#_additional_logging_sources[Sources de journalisation supplémentaires] pour plus d'options de journalisation.

== Puis-je utiliser les K3 dans Docker ?

Oui, il y a plusieurs façons d'exécuter les K3 dans Docker. Voir les xref:advanced.adoc#_running_k3s_in_docker[options avancées] pour plus de détails.

== Quelle est la différence entre le serveur K3s et les jetons d'agent ?

Pour plus d'informations sur la gestion des jetons de jointure K3, voir la xref:cli/token.adoc[documentation de la commande`+k3s token+` ].

== Quelle est la compatibilité des différentes versions de K3 ?

En général, la https://kubernetes.io/docs/setup/release/version-skew-policy/[politique d'asymétrie de version de] Kubernetes s'applique.

En bref, les serveurs peuvent être plus récents que les agents, mais les agents ne peuvent pas être plus récents que les serveurs.

== J'ai un problème, où puis-je trouver de l'aide ?

Si vous rencontrez des problèmes lors du déploiement des K3, vous devriez.. :

. Consultez la page des xref:known-issues.adoc[problèmes connus.] 
. Vérifiez que vous avez résolu toute xref:installation/requirements.adoc#_operating_systems[préparation supplémentaire du système d'exploitation]. Exécutez le site `+k3s check-config+` et assurez-vous qu'il passe.
. Recherchez dans les K3s https://github.com/k3s-io/k3s/issues[Issues] et https://github.com/k3s-io/k3s/discussions[Discussions] celui qui correspond à votre problème.
. Rejoignez le canal K3s de https://slack.rancher.io/[Slack] Rancher pour obtenir de l'aide.
. Soumettez un https://github.com/k3s-io/k3s/issues/new/choose[New Issue] sur le Github de K3s en décrivant votre installation et le problème que vous rencontrez.
