= Problèmes connus
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-15
:page-revdate: {revdate}

Les problèmes connus sont mis à jour périodiquement et ont pour but de vous informer de tout problème qui pourrait ne pas être résolu immédiatement dans la prochaine version. Pour obtenir les informations les plus récentes, consultez les problèmes ouverts et épinglés sur le site https://github.com/k3s-io/k3s/issues[Project Issue Tracker] K3s. Si vous n'utilisez pas la version la plus récente de K3s, assurez-vous de rechercher également les problèmes fermés et les notes de version pour vérifier que votre problème n'a pas déjà été résolu.

== Kine/SQL 2147483647 (MAX INT) Limite de révision

Lorsque vous utilisez K3s avec une xref:datastore/ha.adoc[base de données SQL externe] créée sur une version de K3s antérieure à mai 2024, vous devez appliquer des migrations de schéma à votre base de données pour permettre le stockage de plus de 2,1 millions de révisions dans la base de données. Les bases de données sans schéma mis à jour deviennent en lecture seule lorsque la révision actuelle du datastore atteint 2147483647.

Vous pouvez vérifier la révision actuelle de votre datastore en examinant le champ `+resourceVersion+` de la réponse à un appel de liste effectué avec l'API Kubernetes.
Par exemple, dans la sortie suivante, la révision actuelle est 12345 :

[,bash]
----
$ kubectl get --raw /api/v1/namespaces?labelSelector=none
{"kind":"NamespaceList","apiVersion":"v1","metadata":{"resourceVersion":"12345"},"items":[]}
----

== Docker Snap

Si vous prévoyez d'utiliser K3s avec l'exécution de conteneurs Docker, le paquetage Docker snap n'est pas recommandé car il est connu pour causer des problèmes d'exécution de K3s. Installez Docker à l'aide du système de gestion de paquets natif fourni par votre système d'exploitation.

== Iptables

Si votre nœud utilise iptables v1.6.1 ou plus ancien en mode nftables, vous pourriez rencontrer des problèmes. Nous recommandons d'utiliser des versions plus récentes d'iptables (telles que 1.6.1+), ou de faire fonctionner iptables en mode "legacy", afin d'éviter tout problème.

[,bash]
----
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
----

Les versions 1.8.0-1.8.4 d'Iptables présentent également des problèmes connus qui peuvent faire échouer les K3. Plusieurs distributions Linux populaires sont livrées avec ces versions par défaut. Un bogue provoque l'accumulation de règles dupliquées, ce qui affecte négativement les performances et la stabilité du nœud. Voir https://github.com/k3s-io/k3s/issues/3117[Issue #3117] pour savoir si vous êtes concerné par ce problème.

K3s inclut une version connue d'iptables (v1.8.8) qui a été testée pour fonctionner correctement. Vous pouvez demander à K3s d'utiliser sa version intégrée d'iptables en démarrant K3s avec l'option `+--prefer-bundled-bin+`, ou en désinstallant les paquets iptables/nftables de votre système d'exploitation.

[IMPORTANT]
.Version Gate
====

Le drapeau `+--prefer-bundled-bin+` est disponible à partir des versions 2022-12 (v1.26.0+k3s1, v1.25.5+k3s1, v1.24.9+k3s1, v1.23.15+k3s1).
====

== Mode sans racine

L'utilisation du K3s en mode sans racine est expérimentale et présente plusieurs xref:advanced.adoc#_known_issues_with_rootless_mode[problèmes connus.]

[#hardened-125]
== Mise à jour de Hardened Clusters de v1.24.x à v1.25.x

Kubernetes a supprimé PodSecurityPolicy à partir de la version 1.25 en faveur des normes de sécurité des pods. Vous pouvez en savoir plus sur PSS dans la https://kubernetes.io/docs/concepts/security/pod-security-standards/[documentation en amont de]. Pour K3S, certaines mesures manuelles doivent être prises si `+PodSecurityPolicy+` a été configuré sur les nœuds.

. Sur tous les nœuds, mettez à jour la valeur `+kube-apiserver-arg+` pour supprimer le plugin d'admission `+PodSecurityPolicy+`. Ajoutez la valeur arg suivante à la place : `+'admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml'+` mais ne redémarrez pas ou ne mettez pas à jour K3S pour l'instant. Voici un exemple de ce à quoi pourrait ressembler un fichier de configuration après cette mise à jour pour le nœud à durcir :
+
[,yaml]
----
protect-kernel-defaults: true
secrets-encryption: true
kube-apiserver-arg:
  - 'admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml'
  - 'audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log'
  - 'audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml'
  - 'audit-log-maxage=30'
  - 'audit-log-maxbackup=10'
  - 'audit-log-maxsize=100'
kube-controller-manager-arg:
  - 'terminated-pod-gc-threshold=10'
  - 'use-service-account-credentials=true'
kubelet-arg:
  - 'streaming-connection-idle-timeout=5m'
----

. Créez le fichier `+/var/lib/rancher/k3s/server/psa.yaml+` avec le contenu suivant. Vous pouvez également exempter d'autres espaces de noms. L'exemple ci-dessous exempte `+kube-system+` (obligatoire), `+cis-operator-system+` (facultatif, mais utile lors de l'exécution d'analyses de sécurité via Rancher) et `+system-upgrade+` (obligatoire si vous effectuez des xref:upgrades/automated.adoc[mises à niveau automatisées]).
+
[,yaml]
----
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
 apiVersion: pod-security.admission.config.k8s.io/v1beta1
 kind: PodSecurityConfiguration
 defaults:
   enforce: "restricted"
   enforce-version: "latest"
   audit: "restricted"
   audit-version: "latest"
   warn: "restricted"
   warn-version: "latest"
 exemptions:
   usernames: []
   runtimeClasses: []
   namespaces: [kube-system, cis-operator-system, system-upgrade]
----

. Effectuez la mise à niveau normalement. Si vous effectuez des xref:upgrades/automated.adoc[mises à jour automatisées], assurez-vous que l'espace de noms dans lequel le pod `+system-upgrade-controller+` est exécuté est configuré pour être privilégié conformément aux https://kubernetes.io/docs/concepts/security/pod-security-admission/#pod-security-levels[niveaux de sécurité du pod]:
+
[,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
  labels:
 # This value must be privileged for the controller to run successfully.
 pod-security.kubernetes.io/enforce: privileged
 pod-security.kubernetes.io/enforce-version: v1.25
 # We are setting these to our _desired_ `+enforce+` level, but note that these below values can be any of the available options.
 pod-security.kubernetes.io/audit: privileged
 pod-security.kubernetes.io/audit-version: v1.25
 pod-security.kubernetes.io/warn: privileged
 pod-security.kubernetes.io/warn-version: v1.25
----

. Une fois la mise à niveau terminée, supprimez toutes les ressources PSP restantes du cluster. Dans de nombreux cas, il peut y avoir des PodSecurityPolicies et des ressources RBAC associées dans les fichiers personnalisés utilisés pour le renforcement de `+/var/lib/rancher/k3s/server/manifests/+`. Supprimez ces ressources et k3s sera mis à jour automatiquement. Parfois, pour des raisons de temps, certains d'entre eux peuvent rester dans le cluster, auquel cas vous devrez les supprimer manuellement. Si le xref:security/hardening-guide.adoc[Guide de durcissement] a été suivi précédemment, vous devriez pouvoir les supprimer en procédant comme suit :

[,sh]
----
# Get the resources associated with PSPs
$ kubectl get roles,clusterroles,rolebindings,clusterrolebindings -A | grep -i psp

# Delete those resources:
$ kubectl delete clusterrole.rbac.authorization.k8s.io/psp:restricted-psp clusterrole.rbac.authorization.k8s.io/psp:svclb-psp clusterrole.rbac.authorization.k8s.io/psp:system-unrestricted-psp clusterrolebinding.rbac.authorization.k8s.io/default:restricted-psp clusterrolebinding.rbac.authorization.k8s.io/system-unrestricted-node-psp-rolebinding && kubectl delete -n kube-system rolebinding.rbac.authorization.k8s.io/svclb-psp-rolebinding rolebinding.rbac.authorization.k8s.io/system-unrestricted-svc-acct-psp-rolebinding
----
