= Projets connexes
:page-languages: [en, ja, ko, zh]
:revdate: 2025-03-31
:page-revdate: {revdate}

Les projets mettant en œuvre la distribution de K3s sont les bienvenus pour contribuer à l'expansion de la communauté. Ces projets contribuent à :

* Explorer les capacités et les applications potentielles du K3.
* Étendre les fonctionnalités de K3 à différentes plates-formes et environnements.
* Simplifier le processus de création de grands clusters K3s à haute disponibilité (HA).

== k3s-ansible

Pour les utilisateurs cherchant à démarrer un cluster K3s multi-nœuds et familiers avec ansible, jetez un œil à https://github.com/k3s-io/k3s-ansible[] k3s-io/k3s-ansible repository. Cet ensemble de playbooks ansible fournit un moyen pratique d'installer K3s sur vos nœuds, vous permettant de vous concentrer sur la configuration de votre cluster plutôt que sur le processus d'installation.

== k3sup

Un autre projet qui simplifie le processus de mise en place d'un cluster K3s est https://github.com/alexellis/k3sup[] k3sup. Ce projet, écrit en golang, ne nécessite qu'un accès ssh à vos nœuds. Il fournit également un moyen pratique de déployer les K3 avec des datastores externes, et pas seulement avec le etcd intégré.

== autok3s

Un autre outil de provisionnement, https://github.com/cnrancher/autok3s[autok3s], fournit une interface graphique pour provisionner le cluster k3s à travers une gamme de fournisseurs de cloud, de VM et de machines locales. Cet outil est utile pour les utilisateurs qui préfèrent une interface graphique pour la provocation des grappes K3s.

== hetzner-k3s

Pour les utilisateurs qui déploient sur Hetzner Cloud, consultez link:https://github.com/vitobotta/hetzner-k3s[hetzner-k3s]. Cet outil CLI, écrit en Crystal, gère les étapes supplémentaires nécessaires à la mise en place d'un cluster K3s sur Hetzner Cloud.
