ifdef::ss-ff-stackpacks2_enabled[]
= モニターのスキーマとリファレンス
:revdate: 2026-01-09
:page-revdate: {revdate}
:description: SUSE Observability

== 概要

このページでは、`+Monitor+` のスキーマを、構成要素、式の構文、セマンティクスの詳細な説明とともに説明します。

== モニター用スキーマ

モニターは、モニター関数の実行頻度と引数を指定する。

[,yaml]
----
_type: "Monitor"
name: string
description?: string
function: string
arguments:
  <dependent on monitor function>
intervalSeconds: integer
remediationHint?: string
status?: "ENABLED" | "DISABLED"       # defaults to "DISABLED"
tags:
  <key>: <value>
identifier?: string
----

* `+_type+`{stackstate-product-name} は、これがモニターであることを知る必要がある。 `+Monitor+`
* `+name+`:モニターの名前
* `+description+`:モニターの説明。
* `+function+`:モニターを実行するモニター関数への参照。
* `+intervalSeconds+`:モニターが実行される間隔。通常のリアルタイム測定では30秒を推奨する。より長時間の分析指標クエリーには、より大きな間隔を推奨する。
* `+remediationHint+`:モニターが故障したときにユーザーができることを説明したもの。フォーマットはマークダウンで、時系列やその他のデータに基づいてヒントをカスタマイズするために、オプションでハンドルバーの変数を使用することができるxref:use/alerting/k8s-add-monitors-cli.adoc#_write_the_remediation_hint[（詳細は後述]）。
* `+status+`:`+"DISABLED"+` もしくは`+"ENABLED"+` 。モニターを実行するかどうかを決定する。
* `+tags+`:モニターにタグを追加して、{stackstate-product-name} インスタンスのモニター概要で整理しやすくします、 http://your-instance/#/monitors
* `+identifier+`:コンフィギュレーションを更新する際にモニターを一意に識別する`+urn:stackpack:<stackpack-name>:monitor:....+` 形式の識別子。

== モニター機能

=== しきい値

指定されたメトリッククエリで指定されたしきい値を超えると、ヘルス状態をトリガする。xref:/use/alerting/k8s-override-monitor-arguments.adoc[注釈の助けを借りて]、特定のリソースに異なる閾値を設定することができる。

[,yaml]
----
function: {{ get "urn:stackpack:common:monitor-function:threshold" }}
arguments:
  metric:
    query: string
    unit: string
    aliasTemplate: string
  comparator: GTE | GT | LTE | LT     # how to compare metric value to threshold
  threshold: double
  failureState: CRITICAL | DEVIATING | UNKNOWN
  urnTemplate: string
  titleTemplate: string
----

* `+query+`:PromQLクエリ。{stackstate-product-name} インスタンスのxref:/use/metrics/k8sTs-explore-metrics.adoc[メトリックエクスプローラー]（http://your-instance/#/metrics, ）を使用し、目的のメトリックのクエリーを構築する。
* `+unit+`:チャートのY軸を表示するために使用される、クエリまたはクエリによって返される時系列の値の単位。すべてのユニットについては、xref:/develop/reference/k8sTs-chart-units.adoc[サポートされているユニットの]リファレンスを参照してください。
* `+aliasTemplate+`:メトリックス・チャートにおける時系列の別名。これは、`+${my_label}+` プレースホルダーを使用して、時系列からラベルを置き換えることができるテンプレートです。
* `+comparator+`:LTE/LT/GTE/GTのいずれかを選択し、メトリックに対する閾値を比較する。`+<metric> <comparator> <threshold>+` が真となる時系列は、故障状態を生み出す。
* `+threshold+`:比較する数値のしきい値。
* `+failureState+`:CRITICAL」か「DEVIATING」のどちらか。"CRITICAL "は{stackstate-product-name} 、"DEVIATING "はオレンジ色で表示され、深刻度が異なることを示す。
* `+urnTemplate+`:モニターの結果がxref:use/alerting/k8s-add-monitors-cli.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[バインドさ]れるコンポーネントのurnを構築するテンプレート。
* `+titleTemplate+`:モニター結果のタイトル。複数のモニター結果が同じコンポーネントにバインドできるため、`+${my_label}+` プレースホルダーを使用して時系列ラベルを置き換えることが可能です。

=== 派生状態

健康状態が観測に基づいているコンポーネントの依存関係から状態を導き出す。一番上の依存関係の最もクリティカルな状態を作り出す。
詳細は「xref:/setup/custom-integrations/monitors/derived-state-monitors.adoc[派生ステートモニター]」のページを参照。

[,yaml]
----
function: {{ get "urn:stackpack:common:monitor-function:derived-state-monitor" }}
arguments:
  componentTypes: string
----

* `+componentTypes+`:派生状態に寄与するコンポーネントタイプ。 `+,+` （カンマ）区切りの値からなる1つの文字列として指定される。

=== トポロジカル・スレッショルド

指定されたメトリッククエリで指定されたしきい値を超えると、ヘルス状態をトリガする。メトリッククエリは、トポロジークエリによって返されたコンポーネントの名前、タグ、およびプロパティを参照できる。xref:/use/alerting/k8s-override-monitor-arguments.adoc[注釈の助けを借りて]、特定のリソースに異なる閾値を設定することができる。

[,yaml]
----
function: {{ get "urn:stackpack:common:monitor-function:topological-threshold"  }}
arguments:
  queries:
    topologyQuery: string
    promqlQuery: string
    aliasTemplate: string
    unit: string
  comparator: GTE | GT | LTE | LT     # how to compare metric value to threshold
  threshold: double
  failureState: CRITICAL | DEVIATING | UNKNOWN
  titleTemplate: string
----

* `+queries+`:実行するクエリー
** `+topologyQuery+`:コンポーネントを選択するSTQLクエリ
** `+promqlQuery+`:コンポーネントのラベルとプロパティを使用して時系列を選択できるPromQLクエリ
** `+unit+`:チャートのY軸を表示するために使用される、クエリまたはクエリによって返される時系列の値の単位。すべてのユニットについては、xref:/develop/reference/k8sTs-chart-units.adoc[サポートされているユニットの]リファレンスを参照してください。
** `+aliasTemplate+`:メトリックス・チャートにおける時系列の別名。これは、`+${my_label}+` プレースホルダーを使用して、時系列からラベルを置き換えることができるテンプレートです。
* `+comparator+`:LTE/LT/GTE/GTのいずれかを選択し、メトリックに対する閾値を比較する。`+<metric> <comparator> <threshold>+` が真となる時系列は、故障状態を生み出す。
* `+threshold+`:比較する数値のしきい値。
* `+failureState+`:CRITICAL」か「DEVIATING」のどちらか。"CRITICAL "は{stackstate-product-name} 、"DEVIATING "はオレンジ色で表示され、深刻度が異なることを示す。
* `+titleTemplate+`:モニター結果のタイトル。複数のモニター結果が同じコンポーネントにバインドできるため、`+${my_label}+` プレースホルダーを使用して時系列ラベルを置き換えることが可能です。

=== 動的しきい値

現在値が予測基準間隔を外れた場合にアラートを表示。この基準間隔は、週ごとや日ごとの季節パターンを考慮し、過去のデータに基づいて動的に計算される。
このモニター機能は、自律型異常探知機スタックパックが装着されている場合のみ使用可能です。

詳細については、xref:/setup/custom-integrations/monitors/dynamic-threshold-monitors.adoc[動的しきい値モニターの]ページを参照してください。

[,yaml]
----
function: {{ get "urn:stackpack:aad-v2:shared:monitor-function:dt" }}
arguments:
  telemetryQuery:
    query: string
    unit: string
    aliasTemplate: string
  topologyQuery: string
  falsePositiveRate: float
  checkWindowMinutes: integer
  historicWindowMinutes: integer
  historySizeWeeks: 1 | 2 | 3 (integer)
  includePreviousDay: boolean
  removeTrend: boolean
----

* `+telemetryQuery+`テレメトリーによる評価
** `+query+`:ベースラインと異常検知に使用されるPromQLクエリ
** `+unit+`:チャートのY軸を表示するために使用される、クエリまたはクエリによって返される時系列の値の単位。すべてのユニットについては、xref:/develop/reference/k8sTs-chart-units.adoc[サポートされているユニットの]リファレンスを参照してください。
** `+aliasTemplate+`:メトリックス・チャートにおける時系列の別名。これは、`+${my_label}+` プレースホルダーを使用して、時系列からラベルを置き換えることができるテンプレートです。
* `+topologyQuery+`:コンポーネントを選択するSTQLクエリ
* `+falsePositiveRate+``+!!float 1e-8+` - 逸脱した行動に対するモニターの感度。 値が低いほど、より多くの（偽の）陽性を抑制するが、偽陰性（気づかれない異常）につながる可能性もある。
* `+checkWindowMinutes+``+10+` チェックウィンドウは、迅速な警告（小さな値）と正しく識別された異常（大きな値）の間でバランスをとる必要がある。 一握りのデータポイントが、実際にはうまく機能する。
* `+historicWindowMinutes+`例えば、`+120+` （2時間） - 現在時刻を中心に、1週間以上前 - つまり現在時刻の1時間前から1時間後まで。 また、チェック・ウィンドウの前の2時間も使用される。 ダイナミック閾値モニターは、この履歴データの分布とチェックウィンドウのデータポイントを比較する。
* `+historySizeWeeks+`:`+2+` - 歴史的な背景のためにデータを取得した週数。 `+1+`, `+2+` または`+3+` 。
* `+removeTrend+`絶対値が週によって異なるような傾向のあるメトリクス（例えばリクエスト数）については、この傾向（平均値）を考慮することができます。
* `+includePreviousDay+`通常、`+false+` - 週次ではなく日次パターンしかない指標の場合、より最近のデータを使用することができる。

endif::[]
