include::partial$variables.adoc[]
= Wiederverwendung von ValidatingAdmissionPolicies
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie mehr über die Wiederverwendung und Validierung von Zulassungsrichtlinien in Kubernetes mit {project-name}(cel-policy).
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "ValidatingAdmissionPolicies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "ValidatingAdmissionPolicies"]
:sidebar_label: Wiederverwendung von VAPs
:current-version: {page-origin-branch}

Kubernetes Vanille https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy[Validierung von Richtlinien] besteht aus den folgenden Ressourcen:

* ValidatingAdmissionPolicy: beschreibt die Logik in CEL. Er akzeptiert optional auch Parameter in `spec.paramKind`.
* ValidatingAdmissionPolicyBinding: legt den Geltungsbereich der Richtlinie fest.

Sehen wir uns ein konkretes Beispiel an. Diese und andere können mit {project-name}'s`cel-policy` mit wenig Aufwand wiederverwendet werden.

== ValidatingAdmissionPolicy

Die folgende ValidatingAdmissionPolicy ist derhttps://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#creating-a-validatingadmissionpolicy[Kubernetes docs] entnommen.

Diese Richtlinie prüft, ob die Anzahl der Replikate in Bereitstellungen kleiner oder gleich dem Standardwert `maxreplicas` von 5 ist. Benutzer können diese Vorgabe pro Namensraum oder Einsatz überschreiben und über einen Parameter eine kleinere Zahl wählen.

Es ist mit einer `ValidatingAdmissionPolicyBinding` gebunden. Es betrifft also nur Namespaces, deren Label `environment` auf `test` gesetzt ist.

../vap-policy-example.yaml
[,yaml]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "replicalimit-policy.example.com"
spec:
  failurePolicy: Fail # (1)
  matchConstraints: # (2)
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  variables: # (3)
    - name: maxReplicas # hardcoded global default
      expression: int(5)
  paramKind: # (4)
    apiVersion: v1
    kind: ConfigMap # user-provided override
  validations: # (5)
    - expression: |
        object.spec.replicas <= (
          has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
          ? int(params.data.overrideReplicas)
          : variables.maxReplicas
        )
      messageExpression: |
        'The number of replicas must be less than or equal to ' +
        string( has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
          ? int(params.data.overrideReplicas)
          : variables.maxReplicas)
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "replicalimit-binding-test.example.com"
spec:
  policyName: "replicalimit-policy.example.com"
  validationActions: [Deny] # (7)
  matchResources: # (8)
    namespaceSelector:
      matchLabels:
        environment: test
  paramRef: # (4)
    name: "replica-limit-override"
    namespace: "test"
    parameterNotFoundAction: Deny
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replica-limit-override
  namespace: test
data:
  overrideReplicas: "3"
----

Hier haben wir eine entsprechende {short-project-name} Politik:

### {short-project-name}'s `cel-policy`

../cel-policy-example.yaml
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: Resource validation # (9)
    io.kubewarden.policy.severity: low # (9)
  name: "cel-policy-replica-example"
spec:
  module: registry://ghcr.io/kubewarden/policies/cel-policy:v1.4.0
  failurePolicy: Fail # (6). Webhook behavior. Defaults to "Fail"
  mode: protect # (7). Defaults to "protect"
  rules: # (2)
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["deployments"]
  contextAwareResources: # (10). Fine-grained perms for accessing resources
    - apiVersion: v1
      kind: ConfigMap
  settings:
    failurePolicy: Fail # (1). CEL behavior. Defaults to "Fail"
    variables: # (3)
      - name: "replicas"
        expression: "object.spec.replicas"
      - name: maxReplicas
        expression: int(5)
    paramKind: # (4)
      apiVersion: v1
      kind: ConfigMap # user-provided override
    paramRef: # (4)
      name: "replica-limit-override"
      namespace: "test"
      parameterNotFoundAction: Deny
    validations: # (5)
      - expression: |
          object.spec.replicas <= (
            has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
            ? int(params.data.overrideReplicas)
            : variables.maxReplicas
          )
        messageExpression: |
          'The number of replicas must be less than or equal to ' +
          string( has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
            ? int(params.data.overrideReplicas)
            : variables.maxReplicas)
  backgroundAudit: true # (9). Defaults to "true"
  namespaceSelector: # (8)
    matchLabels:
      environment: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replica-limit-override
  namespace: test
data:
  overrideReplicas: "3"
----

Beachten Sie die kommentierten Zahlen in beiden YAML-Manifesten. Gehen wir näher darauf ein:

[cols="1,1,1,3", options="header"]
|===
| #   | VAP-Feld                         | `cel-policy` Feld                       | Beschreibung

| 1   | `failurePolicy`                   | `settings.failurePolicy`                 | CEL-Verhalten, wenn ein CEL-Ausdruck als falsch ausgewertet wird, wenn CEL-Laufzeitfehler auftreten oder wenn CEL ungültig oder falsch konfiguriert ist. Zum Beispiel ein CEL-Ausdruck, der false zurückgibt, fehlende Parameter oder fehlende Variablen. Nicht zu verwechseln mit (6).
| 2   | `matchConstraints`                | `rules`                                  | Beide akzeptieren dieselbe https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#rulewithoperations-v1-admissionregistration[] RuleWithOperations, die angibt, für welche Art von Ressource die Richtlinie gilt.
| 3   | `variables`                       | `settings.variables`                     | In {short-project-name}'s `cel-policy` stehen Ausdrücke, die Variablen definieren, in `settings.variables`. Davon abgesehen sind sie gleichwertig.
| 4   | `paramKind`,`paramRef`            | `settings.paramKind`,`settings.paramRef` | In {short-project-name}'s `cel-policy`, Parameterdefinitionen sind in `settings.paramKind`, `settings.paramRef`. Davon abgesehen sind sie gleichwertig.
| 5   | `validations`                     | `settings.validations`                   | In {short-project-name}'s `cel-policy`, Ausdrücke, die Validierungen definieren, sind in `settings.validations`. Davon abgesehen sind sie gleichwertig.
| 6   | `---`                             | `failurePolicy`                          | Webhook-Verhalten, für Kubernetes-API-Webhook-Fehler oder Timeout oder für matchConditions-Auswertung. Nicht zu verwechseln mit (1).
| 7   | `validationActions`               | `mode`                                   | `mode` hat als Optionen `protect` und `monitor`. Die Rechnungsprüfung ist in {short-project-name} ausführlicher dargestellt, siehe (9).
| 8   | `matchResources`                  | `namespaceSelector`, `objectSelector`    | Definieren Sie Wege zur Einschränkung mit Selektoren. {short-project-name}'s Richtlinien haben sie als `namespaceSelector` und `objectSelector`.
| 9   | `auditAnnotations` (nicht abgebildet) | `backgroundAudit`Anmerkungen           | Verwenden Sie stattdessen die Felder {short-project-name}, um die Richtlinienverwendung in xref:explanations/audit-scanner/audit-scanner.adoc[Audit Scanner] sowie die Kategorie und den Schweregrad für OpenReports festzulegen.
|10|`---`|`contextAwareResources` Berechtigungen|{short-project-name}} haben fein abgestufte Berechtigungen zum Lesen von Cluster-Ressourcen. Hier wird er zum Lesen der Parameter verwendet.
|     | `matchConditions`                 | `matchConditions`                        | {short-project-name}`matchConditions` (in diesem Beispiel nicht abgebildet).
|     | `---`                             | {short-project-name}-nur Merkmale                 | Weitere Funktionen finden Sie in den übrigen Beispielen des Tutorials CEL.
|===

[TIP]
====

Sie können das Tool `kwctl` verwenden, um eine VAP-Richtlinie nach {short-project-name} zu migrieren.

In dieser xref:howtos/vap-migration.adoc[Anleitung zur VAP-Migration] wird beschrieben, wie Sie dies tun können.

====


=== Noch nicht umgesetzte Äquivalenzen

Es gibt einige VAP-Funktionen, die noch nicht implementiert sind. Wenn Sie sich darauf freuen, setzen Sie sich bitte mit uns in Verbindung. Diese sind:

* VAP https://pkg.go.dev/k8s.io/apiserver/pkg/cel/library#Authz[Autorisierungsbibliothek].
* VAP https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/[Audit-Anmerkungen](ValidatingAdmissionPolicy `spec.auditAnnotations` wenn ValidatingAdmissionPolicyBinding `spec.validationActions` auf "Audit" eingestellt ist).
Dies wird durch {short-project-name}'s xref:explanations/audit-scanner/audit-scanner.adoc[Audit Scanner] und PolicyReports abgedeckt, die es erlauben, Ressourcen bereits im Cluster zu auditieren.
* CEL https://kubernetes.io/docs/reference/using-api/cel/#resource-constraints[Ressourcenbeschränkungen und geschätztes Kostenlimit].
Dies ist durch den allgemeinen xref:reference/policy-evaluation-timeout.adoc[Zeitüberschreitungsschutz] von {short-project-name} abgedeckt.

== Anwendung der Politik

Wie üblich können wir unsere Richtlinie einsetzen, indem wir ihr Manifest instanziieren:

[subs="+attributes",console]
----
$ kubectl apply -f ./cel-policy-example.yaml
----

Und dann testen Sie es, indem Sie eine Bereitstellung instanziieren:

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    environment: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
EOF

namespace/test created
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-cel-policy-replica-example.kubewarden.admission" denied the request:
  The number of replicas must be less than or equal to 5
----
