include::partial$variables.adoc[]
= 监测
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 通过与{project-name} 和 Prometheus 集成，为 Rancher 环境配置监控。
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "metrics-and-monitoring"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "user interface extension", "metrics", "monitoring"]
:current-version: {page-origin-branch}

Rancher 有一个使用 Grafana 和 Prometheus 进行监控的集群工具。您可以使用该工具，将其与{project-name} 整合，查看策略服务器的总体指标或给定策略的指标。

[CAUTION]
====

您需要一个至少有 4 个内核的集群来安装监控工具。

====


== 先决条件

你需要普罗米修斯操作器。请按照xref:howtos/telemetry/30-metrics-qs.adoc#_install_prometheus[以下说明]进行安装。

== 安装

=== 创建服务监控器

* 导入清单以创建 ServiceMonitors。
* 您需要指定{short-project-name} 安装命名空间

这些步骤是根据xref:howtos/telemetry/30-metrics-qs.adoc[遥测指标说明]改编的。

[subs="+attributes",yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubewarden-controller
  namespace: cattle-kubewarden-system
spec:
  endpoints:
    - interval: 10s
      port: metrics
  namespaceSelector:
    matchNames:
      - cattle-kubewarden-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kubewarden-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubewarden-policy-server
  namespace: cattle-kubewarden-system
spec:
  endpoints:
    - interval: 10s
      port: metrics
  namespaceSelector:
    matchNames:
      - cattle-kubewarden-system
  selector:
    matchLabels:
      app: kubewarden-policy-server-default
----

=== 启用`rancher-kubewarden-controller` 资源的遥测功能

* 导航至应用程序和市场 → 已安装的应用程序。
* 为`rancher-kubewarden-controller`资源选择`Edit/Upgrade` 操作。
* 编辑`telemetry` 的 YAML 为`enabled: "true"` ，并验证度量端口是否正确。

[,yml]
----
telemetry:
  metrics: true
  mode: sidecar
  sidecar:
    metrics:
      port: 8080
----

[NOTE]
====

您可能需要重新部署监控资源，以便加载新的 ConfigMap。您可以从工作负载 → 部署中执行此操作。选择`cattle-monitoring-system` 命名空间中的所有资源，然后选择`Redeploy` 操作。

====


=== 为策略和策略服务器创建 Grafana 仪表板 ConfigMap

[NOTE]
====
这种方法适用于气隙式安装。
====


仪表板在 Policy Server 和 Policies 之间是唯一的，因此需要分开创建。

在策略服务器或特定策略的详细视图中：

* 导航至 "度量 "选项卡。
* 根据提示创建 ConfigMap。
* 重新加载页面以更新 Grafana 视图（Grafana 可能会较慢地识别新的仪表板）。

您应该可以在每个资源的详细页面上查看策略服务器或任何给定策略的指标。您还可以在 Grafana UI 中查看{short-project-name} 仪表板，或在 Prometheus UI 中查看事件。
