= 手动升级
:page-languages: [EN, JA, KO, ZH]
:revdate: 2025-12-30
:page-revdate: {revdate}

您可以使用安装脚本或手动安装所需版本的二进制文件来升级 K3s。

[NOTE]
====
升级时，先逐个升级服务器节点，然后再升级任何代理节点。
====

[#_release_channels]
== 发布渠道

通过安装脚本或使用我们的xref:upgrades/automated.adoc[自动升级]功能进行的升级可与不同的发布渠道绑定。可使用以下频道

|===
| 频道 | 说明

| 稳定
| (默认） 建议在生产环境中使用稳定版。这些版本已经过一段时间的社区测试。

| 最新
| 根据 semver 排序规则，最新版本总是指向现有的最高非发布版本。这些版本尚未经过一段时间的社区测试。

| v1.33 （示例）
| Kubernetes 的每个次版本都有一个发布渠道，包括生命周期结束的版本。这些通道会选择该次要版本的最新版本，但不一定是稳定版本。
|===

如需详尽的最新频道列表，请访问https://update.k3s.io/v1-release/channels[频道服务 API] k3s。有关频道工作原理的更多技术细节，请参阅https://github.com/rancher/channelserver[channelserver 项目]。

[TIP]
====
当尝试升级到新版本的 K3s 时，https://kubernetes.io/docs/setup/release/version-skew-policy/[Kubernetes 版本倾斜策略]适用。确保您的计划在升级时不会跳过中间的次要版本。系统升级控制器本身无法防止 Kubernetes 版本发生不支持的变更。
====


== 使用安装脚本升级 K3s

要从旧版本升级 K3s，可以使用运行安装脚本时使用的相同配置选项重新运行安装脚本。

[IMPORTANT]
.备注
====
`+INSTALL_K3S_EXEC+` 变量、`+K3S_+` 变量和尾部 shell 参数都被安装脚本用于生成 systemd 单元和环境文件。
如果在最初运行安装脚本时设置了配置，但在重新运行安装脚本时没有再次设置，则原始值将丢失。

安装脚本不会管理xref:installation/configuration.adoc#_configuration_file[配置文件]的内容。
如果希望配置独立于安装脚本，则应使用配置文件，而不是向安装脚本传递环境变量或参数。
====


运行安装脚本将

. 下载新的 k3s 二进制文件
. 更新 systemd 单元或 openrc 启动脚本，以反映传递给安装脚本的参数
. 重启 k3s 服务

[NOTE]
====
即使 K3s 停止运行，Pod 的容器也会继续运行。在重新启动 K3s 之前，安装脚本不会排空或封锁节点。如果您的工作负载对短暂的 API 服务器中断很敏感，则应在重新运行安装脚本升级 K3s 或修改配置之前，使用`+kubectl+` 手动https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[排水并封锁]节点，之后再解除封锁。
====

例如，升级到当前的稳定版本：

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

如果要升级到特定通道（如最新版本）中的更新版本，可以指定通道：

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL=latest <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

如果想升级到特定版本，可以运行以下命令：

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Z+k3s1 <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

[TIP]
====
如果要下载新版本的 k3s，但不启动它，可以使用`+INSTALL_K3S_SKIP_START=true+` 环境变量。
====


== 使用二进制文件升级 K3

要手动升级 K3s，可以下载所需的 K3s 二进制版本，然后用新版本替换现有的二进制文件。

. 从https://github.com/k3s-io/k3s/releases[版本]中下载所需的 K3s 二进制版本
. 将下载的二进制文件复制到`+/usr/local/bin/k3s+` （或所需位置）
. 重启 k3s 或 k3s-agent 服务，或重启 k3s 进程（二进制）。

[NOTE]
====
即使 K3s 停止运行，Pod 的容器也会继续运行。一般来说，在不排空 pod 和封锁节点的情况下重新启动 K3 是安全的。如果您的工作负载对短暂的 API 服务器中断很敏感，则应在重启 K3s 之前使用`+kubectl+` 手动https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[排水并封锁]节点，之后再解除封锁。
====
