= Cluster Load Balancer
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

In diesem Abschnitt wird beschrieben, wie Sie einen externen Load Balancer vor den Serverknoten eines High Availability (HA) K3s-Clusters installieren. Es werden zwei Beispiele angeführt: Nginx und HAProxy.

[TIP]
====
Externe Load-Balancer sind nicht zu verwechseln mit dem eingebetteten ServiceLB, einem eingebetteten Controller, der die Nutzung von Kubernetes LoadBalancer Services ermöglicht, ohne dass ein Load-Balancer-Controller eines Drittanbieters eingesetzt werden muss. Weitere Einzelheiten finden Sie unter xref:networking/networking-services.adoc#_service_load_balancer[Service Load Balancer].

Externe Load-Balancer können verwendet werden, um eine feste Registrierungsadresse für die Registrierung von Knoten oder für den externen Zugriff auf den Kubernetes-API-Server bereitzustellen. Für die Bereitstellung von LoadBalancer-Diensten können externe Load-Balancer neben oder anstelle von ServiceLB verwendet werden, aber in den meisten Fällen sind Ersatz-Load-Balancer-Controller wie MetalLB oder Kube-VIP die bessere Wahl.
====


== Voraussetzungen

Auf allen Knoten in diesem Beispiel läuft Ubuntu 20.04.

Für beide Beispiele wird angenommen, dass ein xref:datastore/ha-embedded.adoc[HA K3s-Cluster mit eingebettetem etcd] auf 3 Knoten installiert wurde.

Jeder k3s-Server ist mit konfiguriert:

[,yaml]
----
# /etc/rancher/k3s/config.yaml
token: lb-cluster-gd
tls-san: 10.10.10.100
----

Die Knoten haben Hostnamen und IPs von:

* Server-1: `10.10.10.50`
* Server-2: `10.10.10.51`
* Server-3: `10.10.10.52`

Zwei zusätzliche Knoten für den Lastausgleich werden mit den Hostnamen und IPs von konfiguriert:

* lb-1: `10.10.10.98`
* lb-2: `10.10.10.99`

Es gibt drei weitere Knoten mit den folgenden Hostnamen und IP-Adressen:

* agent-1: `10.10.10.101`
* agent-2: `10.10.10.102`
* agent-3: `10.10.10.103`

== Load Balancer einrichten

[tabs,sync-group-id=ext-load-balancer]
======
HAProxy::
+
--
http://www.haproxy.org/[HAProxy] ist eine Open-Source-Option, die einen TCP-Load-Balancer bereitstellt. Es unterstützt auch HA für den Load Balancer selbst und gewährleistet Redundanz auf allen Ebenen. Weitere Informationen finden Sie unter http://docs.haproxy.org/2.8/intro.html[HAProxy-Dokumentation].

Außerdem werden wir KeepAlived verwenden, um eine virtuelle IP (VIP) zu erzeugen, die für den Zugriff auf den Cluster verwendet wird. Siehe https://www.keepalived.org/manpage.html[KeepAlived Dokumentation] für weitere Informationen.

. Installieren Sie HAProxy und KeepAlived:
+
[,bash]
----
sudo apt-get install haproxy keepalived
----

. Fügen Sie Folgendes zu `/etc/haproxy/haproxy.cfg` auf lb-1 und lb-2 hinzu:
+
----
frontend k3s-frontend
    bind *:6443
    mode tcp
    option tcplog
    default_backend k3s-backend

backend k3s-backend
    mode tcp
    option tcp-check
    balance roundrobin
    default-server inter 10s downinter 5s
    server server-1 10.10.10.50:6443 check
    server server-2 10.10.10.51:6443 check
    server server-3 10.10.10.52:6443 check
----

. Fügen Sie Folgendes zu `/etc/keepalived/keepalived.conf` auf lb-1 und lb-2 hinzu:
+
----
global_defs {
  enable_script_security
  script_user root
}

vrrp_script chk_haproxy {
    script 'killall -0 haproxy' # faster than pidof
    interval 2
}

vrrp_instance haproxy-vip {
    interface eth1
    state <STATE> # MASTER on lb-1, BACKUP on lb-2
    priority <PRIORITY> # 200 on lb-1, 100 on lb-2

    virtual_router_id 51

    virtual_ipaddress {
        10.10.10.100/24
    }

    track_script {
        chk_haproxy
    }
}
----

. Starten Sie HAProxy und KeepAlived auf lb-1 und lb-2 neu:
+
[,bash]
----
systemctl restart haproxy
systemctl restart keepalived
----

. Führen Sie auf Agent-1, Agent-2 und Agent-3 den folgenden Befehl aus, um k3s zu installieren und dem Cluster beizutreten:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_TOKEN=lb-cluster-gd sh -s - agent --server https://10.10.10.100:6443
----
Wobei `INSTALL_K3S_ARTIFACT_URL` die https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[URL von] ist.
+
Sie können nun `kubectl` vom Serverknoten aus verwenden, um mit dem Cluster zu interagieren.
+
[,bash]
----
root@server-1 $ k3s kubectl get nodes -A
NAME       STATUS   ROLES                       AGE     VERSION
agent-1    Ready    <none>                      32s     v1.27.3+k3s1
agent-2    Ready    <none>                      20s     v1.27.3+k3s1
agent-3    Ready    <none>                      9s      v1.27.3+k3s1
server-1   Ready    control-plane,etcd,master   4m22s   v1.27.3+k3s1
server-2   Ready    control-plane,etcd,master   3m58s   v1.27.3+k3s1
server-3   Ready    control-plane,etcd,master   3m12s   v1.27.3+k3s1
----
--

Nginx::
+
--
[WARNING]
====
Nginx unterstützt nicht von Haus aus eine Hochverfügbarkeitskonfiguration (HA). Bei der Einrichtung eines HA-Clusters führt ein einzelner Load Balancer vor K3s wieder zu einem Single Point of Failure.
====

http://nginx.org/[Nginx Open Source] bietet einen TCP-Load-Balancer. Siehe https://nginx.org/en/docs/http/load_balancing.html[Verwendung von nginx als HTTP-Loadbalancer] für weitere Informationen.

. Erstellen Sie auf lb-1 eine Datei `nginx.conf` mit folgendem Inhalt:
+
----
events {}

stream {
  upstream k3s_servers {
    server 10.10.10.50:6443;
    server 10.10.10.51:6443;
    server 10.10.10.52:6443;
  }

  server {
    listen 6443;
    proxy_pass k3s_servers;
  }
}
----

. Führen Sie den Nginx-Loadbalancer auf lb-1 aus:
+
Docker verwenden:
+
[,bash]
----
docker run -d --restart unless-stopped \
    -v ${PWD}/nginx.conf:/etc/nginx/nginx.conf \
    -p 6443:6443 \
    nginx:stable
----
+
Oder https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/[nginx installieren] und dann ausführen:
+
[,bash]
----
cp nginx.conf /etc/nginx/nginx.conf
systemctl start nginx
----

. Führen Sie auf Agent-1, Agent-2 und Agent-3 den folgenden Befehl aus, um k3s zu installieren und dem Cluster beizutreten:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_TOKEN=lb-cluster-gd sh -s - agent --server https://10.10.10.98:6443
----
+
Sie können nun `kubectl` vom Serverknoten aus verwenden, um mit dem Cluster zu interagieren.
+
[,bash]
----
root@server1 $ k3s kubectl get nodes -A
NAME       STATUS   ROLES                       AGE     VERSION
agent-1    Ready    <none>                      30s     v1.27.3+k3s1
agent-2    Ready    <none>                      22s     v1.27.3+k3s1
agent-3    Ready    <none>                      13s     v1.27.3+k3s1
server-1   Ready    control-plane,etcd,master   4m49s   v1.27.3+k3s1
server-2   Ready    control-plane,etcd,master   3m58s   v1.27.3+k3s1
server-3   Ready    control-plane,etcd,master   3m16s   v1.27.3+k3s1
----
--
======
