= Configuração do SUSE Observability para notificações por e-mail
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

[CAUTION]
====
Os usuários SaaS do SUSE Observability podem usar notificações por e-mail sem configuração adicional. Este guia só se aplica a instalações auto-hospedadas do SUSE Observability que planejam usar o canal de notificação por e-mail.
====


Para poder usar o canal de notificação por e-mail no SUSE Observability, primeiro você precisa seguir as etapas a seguir:

== Configurar o SUSE Observability com a configuração SMTP

O SUSE Observability precisa ser configurado com credenciais para se conectar ao servidor SMTP. Você pode fazer isso adicionando o seguinte ao arquivo `values.yaml` da instalação do SUSE Observability:

[,yaml]
----
stackstate:
  email:
    enabled: true
    sender: "<stackstate@example.com>"
    server:
      host: "<smtp.example.com>"
      auth:
        username: "<user name>"
        password: "<user password>"
----

Isso usará a porta `587` no servidor SMTP e usará o comando `STARTTLS` para estabelecer uma conexão segura. Essas são todas as outras opções que podem ser personalizadas:

[,yaml]
----
stackstate:
  email:
    additionalProperties:
      # Add needed Java email properties for your mail server (use string values), defaults are:
      "mail.smtp.auth": "true"
      "mail.smtp.starttls.enable": "true"
    server:
      protocol: smtp
      port: 587
----

=== Usando um segredo externo

Quando o nome de usuário e a senha não puderem ser fornecidos nos valores, mas tiverem que vir de um segredo externo, siga xref:/setup/security/external-secrets.adoc#_getting_username_and_password_for_email_sending_from_an_external_secret[estas etapas]
