= Variables aléatoires du modèle
:revdate: 2025-09-08
:page-revdate: {revdate}

Les variables aléatoires du modèle sont intégrées dans l'opérateur élémentaire.

Ils permettent d'inclure des valeurs aléatoires `+Int+`, `+Hex+` ou `+UUID+` dans les xref:label-templates/label-templates.adoc[modèles d'étiquettes] personnalisées.

Les valeurs sont calculées à la volée pendant le rendu de `+label template variables+`.

[IMPORTANT]
.Les modèles d'étiquettes aléatoires ne sont rendus qu'une seule fois
====

Un modèle d'étiquette contenant une variable aléatoire n'est rendu que si l' xref:references/machineinventory-reference.adoc[inventaire des machines de] l'hôte enregistreur n'a pas encore de valeur pour cette étiquette (une étiquette avec la même clé est manquante ou sa valeur est vide).

Les trois cas dans lesquels un modèle d'étiquette avec une variable aléatoire est rendu sont donc les suivants :

. l'hôte s'enregistre pour la première fois et l'xref:references/machineinventory-reference.adoc[inventaire des machines] est créé à nouveau.
. le modèle d'étiquette a été ajouté à l'enregistrement de la machine après le (ré)enregistrement de l'hôte la dernière fois.
. l'étiquette xref:references/machineinventory-reference.adoc[MachineInventory] correspondant au modèle d'étiquette (même clé d'étiquette) a été retirée manuellement ou sa valeur a été effacée.
====


|===
| Variable | Description | de

| `+${Random/UUID}+`
| UUID aléatoire (par exemple, fd95324a-c26b-4e28-8727-1dcec293a0ec)
| 1.7.0

| `+${Random/Hex/[1-32]}+`
| chaîne hexadécimale aléatoire de la longueur spécifiée (min 1, max 32)
| 1.7.0

| `+${Random/Int/[MAXINT]+`
| nombre entier aléatoire (min 0, max MAXINT-1)
| 1.7.0
|===

[NOTE]
.Exemples de rendu
====
|===
| valeur du modèle | exemple de valeur rendue

| `+${Random/UUID}+`
| fd95324a-c26b-4e28-8727-1dcec293a0ec

| `+${Random/Hex/12}+`
| acd231f222b8

| `+${Random/Int/10000}+` 
| 9432

|===
====


Les variables de modèle aléatoire peuvent être utiles pour générer des noms d'hôte personnalisés à attribuer à l'hôte d'enregistrement.

Étant donné que le nom d'hôte doit être unique et qu'il est attribué via le champ xref:references/machineregistration-reference.adoc[MachineRegistration] `+spec.machineName+`, des variables aléatoires peuvent être utilisées pour garantir l'unicité d'un groupe d'hôtes partageant le même préfixe et/ou suffixe personnalisé.

Consultez la section xref:installation/hostname.adoc[Comment faire/personnaliser le nom d'hôte] pour plus d'informations.

.exemple d'enregistrement Variables du modèle aléatoire
[,yaml]
----
include::example$quickstart/registration-random-hostname.yaml[]
----
