= {elemental-product-name} 操作员舵手图
:revdate: 2025-07-03
:page-revdate: {revdate}

{elemental_operator_url}[{elemental_operator_name}] 负责管理{elemental-product-name} 版本和维护机器库存，以协助边缘或裸机安装。

相关图表使用https://helm.sh[Helm]软件包管理器在https://rancher.com/docs/rancher/v2.6/[Manager v2.6] Rancher集群上启动元素操作器部署。

== 先决条件

* Rancher 管理器 v2.6 版
* Helm 客户端版本 v3.8.0+

== 获取舵手图信息

[,console]
----
helm pull oci://registry.suse.com/rancher/elemental-operator-chart
helm show all oci://registry.suse.com/rancher/elemental-operator-chart
----

== 安装图表

[,console]
----
helm install --create-namespace -n cattle-elemental-system elemental-operator-crds \
             oci://registry.suse.com/rancher/elemental-operator-crds-chart
helm install --create-namespace -n cattle-elemental-system elemental-operator \
             oci://registry.suse.com/rancher/elemental-operator-chart
----

该命令以默认配置在 Kubernetes 集群上部署 elemental-operator。

_请参见下面的<<_configuration,配置>>。_

_有关命令文档，请参见https://helm.sh/docs/helm/helm_install/[helm install]。_

== 卸载图表

[,console]
----
helm uninstall -n cattle-elemental-system elemental-operator
----

这会删除与图表相关的所有 Kubernetes 组件，并删除发布。

_有关命令文档，请参见https://helm.sh/docs/helm/helm_uninstall/[helm uninstall]。_

== 升级图表

[,console]
----
helm upgrade -n cattle-elemental-system \
             --install elemental-operator \
             oci://registry.suse.com/rancher/elemental-operator-chart
----

_有关命令文档，请参见https://helm.sh/docs/helm/helm_upgrade/[helm upgrade]。_

== 配置

请参阅https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing[安装前自定义图表]。要查看所有可配置选项及详细注释，请访问图表<<_values,值>>，或运行这些配置命令：

`console showLineNumbers helm show values oci://registry.suse.com/rancher/elemental-operator-chart `console showLineNumbers helm display values

== 价值观

[cols="2,1,2,2"]
|===
| 钥匙 | 类型 | 默认值 | 说明

| image.empty | 字符串 | `+rancher/pause:3.1+` |

| image.repository | 字符串 | `+registry.suse.com/rancher/elemental-operator-chart+` | 元素操作器的源图像，存储库名称为

| image.tag | 标签 | `+""+` |

| image.imagePullPolicy | 字符串 | `+IfNotPresent+` |

| noProxy | 字符串 | `+127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local+` | 以逗号分隔的不使用代理的域或 IP 地址列表 

| global.cattle.systemDefaultRegistry | 字符串 | `+""+` | 默认容器注册表名称

| sync_interval | 字符串 | `+"60m"+` | 升级通道的默认同步间隔 

| sync_namespaces | 清单 | `+[]+` | 操作符将监视的命名空间，留空表示所有 

| 排错 | bool | `+false+` | 为操作员启用调试输出 

| nodeSelector.kubernetes.io/os | 字符串 | `+linux+` |

| 容忍 | 反对 | `+{}+` |

| tolerations.key | 字符串 | `+cattle.io/os+` |

| tolerations.operator | 字符串 | `+"Equal"+` |

| tolerations.value | 字符串 | `+"linux"+` |

| tolerations.effect | 字符串 | `+NoSchedule+` |
|===
