= OpenMetrics
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

O SUSE Observability Agent V2 pode ser configurado para recuperar métricas de um ponto de extremidade do OpenMetrics e enviá-las para o SUSE Observability.

== Configuração

=== Instalação

A verificação do OpenMetrics está incluída no [Agent V2 StackPack].

=== Configuração

Para ativar a integração do OpenMetrics e começar a coletar dados de métricas de um ponto de extremidade do OpenMetrics, a verificação do OpenMetrics deve ser configurada no SUSE Observability Agent V2. A configuração de verificação fornece todos os detalhes necessários para que o Agente se conecte ao seu endpoint do OpenMetrics e recupere as métricas disponíveis.

[tabs]
====
Kubernetes, OpenShift::
+
--

. Implante o agente em seu cluster Kubernetes ou OpenShift.
. Adicione as anotações abaixo ao iniciar um pod que expõe métricas por meio de um endpoint do OpenMetrics. Adicione o seguinte:
 ** **+++<CONTAINER_NAME>+++** - o nome do contêiner que expõe o OpenMetrics. É possível processar vários pontos de extremidade em um único pod (é por isso que há uma lista no JSON).+++</CONTAINER_NAME>+++
 ** *prometheus_url* - o caminho (geralmente apenas `metrics`) e a porta na qual o ponto de extremidade do OpenMetrics está exposto.
 ** *namespace* - todas as métricas coletadas aqui receberão isso como um prefixo separado por pontos.
 ** *metrics* - use `["*"]` para coletar todas as métricas disponíveis. Também é possível especificar uma lista de métricas a serem obtidas. Deve ser uma cadeia de caracteres que representa o nome da métrica ou um mapeamento para renomear a métrica+``<EXPOSED_METRIC>:````<SENT_METRIC>+``
+
[,yaml]
----
 ...
 metadata:
   annotations:
     ad.stackstate.com/<CONTAINER_NAME>.check_names: '["openmetrics"]'
     ad.stackstate.com/<CONTAINER_NAME>.init_configs: '[{}]'
     ad.stackstate.com/<CONTAINER_NAME>.instances: |
       [
         {
           "prometheus_url": "http://%%host%%:<METRICS_PORT>/<METRICS_PATH>",
           "namespace": "<METRICS_NAMESPACE>",
           "metrics": ["*"]
         }
       ]
 ...
 # This already exists in the pod spec, the container name needs to match the container that is exposing the openmetrics endpoint
 spec:
   containers:
    - name: <CONTAINER_NAME>
 ...
----
. Você também pode adicionar filtros e configurações opcionais:
 ** *prometheus_metrics_prefix* - prefixo a ser adicionado às métricas OpenMetrics expostas.
 ** *health_service_check* - envia uma verificação de serviço `<NAMESPACE>.prometheus.health` informando a integridade do ponto de extremidade do OpenMetrics. Padrão `true`.
 ** *label_to_hostname* - substitui o nome do host pelo valor de um rótulo.
 ** *label_joins* - direciona uma métrica e recupera seu rótulo por meio de um mapeamento 1:1
 ** *labels_mapper* - renomeia rótulos. O formato é `<LABEL_TO_RENAME>: <NEW_LABEL_NAME>`.
 ** *type_overrides* - substitui um tipo na carga útil do OpenMetrics ou digita uma métrica não tipificada (que seria ignorada por padrão). Os sites `<METRIC_TYPE>` suportados são `gauge`, `count` e `rate`. O formato é `<METRIC_NAME>: <METRIC_TYPE>`.
 ** *tags* - lista de tags a serem anexadas a cada métrica, evento e verificação de serviço emitida por essa integração.
 ** *send_histograms_buckets* - envia o compartimento de histogramas. Padrão `true`.
 ** *send_monotonic_counter* - definido como `true` para converter contadores em uma taxa (observe que são necessárias duas execuções para produzir o primeiro resultado). Defina como `false` para enviar os contadores como um contador monotônico. Padrão `true`.
 ** *exclude_labels* - lista de rótulos a serem excluídos.
 ** *prometheus_timeout* - define um tempo limite para a consulta do OpenMetrics.
 ** *ssl_cert* - Se o ponto de extremidade do OpenMetrics estiver protegido, insira o caminho para o certificado e especifique a chave privada no parâmetro `ssl_private_key` ou forneça o caminho para um arquivo que contenha o certificado e a chave privada.
 ** *ssl_private_key* - necessário se o certificado vinculado em `ssl_cert` não incluir a chave privada. Observe que a chave privada do seu certificado local deve estar sem criptografia.
 ** *ssl_ca_cert* - o caminho para a CA confiável usada para gerar certificados personalizados.
 ** *extra_headers* - um dicionário que mapeia os nomes de cabeçalhos HTTP para seus valores correspondentes a serem enviados em consultas ao ponto de extremidade do OpenMetrics. Os valores podem incluir dinamicamente variáveis de ambiente usando a sintaxe `%%env_VARIABLE%%`. Por exemplo, `"Authorization: Bearer %%env_TOKEN%%"` substitui automaticamente o valor da variável de ambiente `TOKEN`.
. Aguarde até que o agente colete dados do ponto de extremidade do OpenMetrics e os envie para o SUSE Observability.

--
====

== Dados coletados

=== Métricas

Por padrão, todas as métricas são recuperadas do ponto de extremidade OpenMetrics especificado. Para otimizar o desempenho, um máximo de 2.000 métricas será recuperado. Se a verificação estiver tentando recuperar mais de 2.000 métricas, adicione um filtro `metrics` à <<_configuration,configuração>> para garantir que todas as métricas importantes possam ser recuperadas dentro do limite.

As métricas recuperadas não serão mapeadas automaticamente para os elementos da topologia, mas podem ser pesquisadas usando o xref:/use/metrics/k8sTs-explore-metrics.adoc[inspetor de telemetria] e, por fim, xref:/use/metrics/k8s-add-charts.adoc[adicionadas aos componentes por meio de uma vinculação de métrica].

=== Eventos

A integração do OpenMetrics não recupera nenhum dado de eventos.

=== Traços

A integração do OpenMetrics não recupera dados de rastreamento.
