include::partial$variables.adoc[]
= Introduction à l'Open Policy Agent
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Découvrez comment l'Open Policy Agent utilise le langage Rego pour écrire des politiques qui évaluent et produisent des résultats pour une prise de décision sécurisée.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "introduction"].
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "open policy agent", "opa", "rego"]
:sidebar_label: Introduction
:current-version: {page-origin-branch}

[NOTE]
====
La prise en charge de l'Open Policy Agent a été introduite à partir de ces versions :

* kwctl : v0.2.0
* serveur de politique : v0.2.0
====


Open Policy Agent (OPA) est un cadre de politique générale qui utilise le langage Rego pour écrire des politiques.

== Introduction

Les politiques de régulation fonctionnent en recevant une entrée à évaluer et en produisant une sortie en guise de réponse.
En ce sens, l'OPA n'a pas d'outil spécifique pour cibler l'écriture de politiques pour Kubernetes.

Plus précisément, les politiques de l'OPA reçoivent une entrée JSON et produisent une sortie JSON.
Le serveur OPA est configuré pour recevoir des demandes d'examen d'admission de la part de Kubernetes.
Les politiques reçoivent un objet Kubernetes `+AdmissionReview+` au format JSON.
Ils doivent renvoyer un objet `+AdmissionReview+` valide comme résultat de l'évaluation.

== Compatibilité avec les politiques existantes

Toutes les politiques peuvent être compilées vers la cible `+wasm+` (WebAssembly) à l'aide de l'outil CLI officiel `+opa+`.

En ce qui concerne l'exécution des politiques, vous pouvez en savoir plus sur le xref:tutorials/writing-policies/rego/02-builtin-support.adoc[support intégré de l'OPA] mis en œuvre à l'adresse {short-project-name}.
