include::partial$variables.adoc[]
= Élaborer et exécuter une politique OPA pour {short-project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Créez une politique OPA personnalisée pour votre projet en construisant un paquet de politiques Rego, en le compilant dans une cible WASM et en l'intégrant avec kwctl.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "build-and-run"].
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "build and run", "open policy agent", "opa", "rego"].
:current-version: {page-origin-branch}

Dans la section précédente, vous avez rédigé votre politique Rego.
La structure se présente comme suit :

[subs="+attributes",console]
----
.
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
└── request.rego

1 directory, 4 files
----

== Construire

Construire :

[subs="+attributes",console]
----
$ opa build -t wasm -e policy/main policy.rego request.rego
----

Cela permet d'élaborer la politique d'enregistrement, avec :

* `+target+`: `+wasm+`.
Vous souhaitez élaborer la politique pour la cible `+wasm+`.
* `+entrypoint+`: `+policy/main+`.
Le point d'entrée est la règle `+main+` à l'intérieur du paquet `+policy+`.
* `+policy.rego+`:
Construire et inclure le fichier `+policy.rego+`.
* `+request.rego+`:
Construire et inclure le fichier `+request.rego+`.

Une fois la construction terminée, `+opa build+` a généré un fichier `+bundle.tar.gz+`.
Vous pouvez l'extraire :

[subs="+attributes",console]
----
$ tar -xf bundle.tar.gz /policy.wasm
----

L'arbre ressemble maintenant à ce qui suit :

[subs="+attributes",console]
----
.
├── bundle.tar.gz
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
├── policy.wasm
└── request.rego

1 directory, 6 file
----

Vous avez votre fichier `+policy.wasm+`:

[subs="+attributes",console]
----
$ file policy.wasm
policy.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
----

Maintenant, vous l'exécutez.

== Exécuter

Utilisez `+kwctl+` pour exécuter la politique :

[subs="+attributes",console]
----
$ kwctl run -e opa --request-path data/other-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": true
}
----

Cette demande est acceptée par la politique, puisqu'il s'agit de la demande qui pointe vers l'espace de noms `+other+`.

* `+execution-mode+`: `+opa+`.
Les politiques de régulation peuvent être ciblées sur Open Policy Agent ou Gatekeeper.
Vous devez indiquer à `+kwctl+` le type de politique que vous menez.
* `+request-path+`:
Emplacement de la demande enregistrée à laquelle `+kwctl+` envoie la politique pour évaluation.

Essayez maintenant d'évaluer la requête qui crée le pod dans l'espace de noms `+default+`:

[subs="+attributes",console]
----
$ kwctl run -e opa --request-path data/default-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "it is forbidden to use the default namespace"
  }
}
----

La politique consiste à rejeter la demande, en donnant une raison au serveur de l'API qui est renvoyée à l'utilisateur ou au consommateur de l'API.
