= Frota do provedor complementar da API de cluster
:revdate: 2025-11-20
:page-revdate: {revdate}

== Visão geral

ifeval::["{build-type}" == "product"]
O Cluster API Add-on Provider for `Fleet` (CAAPF) é um provedor de API de cluster (CAPI) que oferece integração com https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/index.html[`Fleet`] para permitir a fácil implementação de aplicativos em um cluster provisionado por CAPI.
endif::[]
ifeval::["{build-type}" == "community"]
O Cluster API Add-on Provider for `Fleet` (CAAPF) é um provedor de API de cluster (CAPI) que oferece integração com https://fleet.rancher.io/[`Fleet`] para permitir a fácil implementação de aplicativos em um cluster provisionado por CAPI.
endif::[]

[TIP]
====
Para obter mais informações sobre o provedor, consulte o https://rancher.github.io/cluster-api-addon-provider-fleet/[site].
====

[WARNING]
====
O CAAPF depende do gate de recursos do `WatchList` Kubernetes. Esse recurso precisa ser ativado explicitamente nas versões do Kubernetes `1.33`. Consulte a https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/[documentação upstream do] para obter mais informações.
====

== Funcionalidade

* O provedor registrará um cluster CAPI recém-provisionado com `Fleet`, criando uma instância `Fleet` `Cluster` com os mesmos `name` e `namespace`. Os aplicativos podem ser implantados automaticamente no cluster criado usando `GitOps`.
* O provedor criará automaticamente um Fleet `ClusterGroup` para cada CAPI `ClusterClass` no espaço de nomes `ClusterClass`. Isso permite que você implemente os mesmos aplicativos em todos os clusters criados a partir do mesmo `ClusterClass`.
* O provedor criará automaticamente um Fleet `ClusterGroup` para cada CAPI `ClusterClass` referenciado por `Cluster` localizado em um namespace diferente de `ClusterClass`. Isso permite que você implemente os mesmos aplicativos em todos os clusters que fazem referência ao mesmo `ClusterClass` em um namespace específico.

ifeval::["{build-type}" == "product"]
Isso permite que o usuário especifique um recurso https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/reference/ref-bundle.html[`Bundle`] com cargas de trabalho de aplicativos brutas ou https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/reference/ref-gitrepo.html[`GitRepo`] para instalar aplicativos a partir do git. Cada um dos recursos pode fornecer https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/how-tos-for-users/gitrepo-targets.html#_defining_targets[`targets`] com qualquer combinação de:
endif::[]
ifeval::["{build-type}" == "community"]
Isso permite que o usuário especifique um recurso https://fleet.rancher.io/ref-bundle[`Bundle`] com cargas de trabalho de aplicativos brutas ou https://fleet.rancher.io/ref-gitrepo[`GitRepo`] para instalar aplicativos a partir do git. Cada um dos recursos pode fornecer https://fleet.rancher.io/gitrepo-targets#defining-targets[`targets`] com qualquer combinação de:
endif::[]

[source,yaml]
----
  targets:
  - clusterGroup: <cluster-class-name> # If the cluster is created from cluster-class
  - clusterName: <a specific CAPI cluster name>
----

Além disso, o site `CAAPF` propaga automaticamente os rótulos de cluster `CAPI` para o recurso de cluster `Fleet`, para que os usuários possam especificar um destino que corresponda a um rótulo de cluster comum:

[source,yaml]
----
  targets:
  - clusterSelector: <label selector for the cluster instances, inherited from CAPI clusters>
  - clusterGroupSelector: <label selector for the cluster group instances, labels inherited from ClusterClass>
----

== Modelos do Helm Chart baseados no CAPI `Cluster` e `ControlPlane`

ifeval::["{build-type}" == "product"]
O Cluster *API Addon Provider Fleet* automatiza do aplicativo https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/ref-fleet-yaml.html#_templating[o modelo] para clusters CAPI importados com base no estado do cluster correspondente. Esse recurso garante que o estado de um cluster e de recursos CAPI esteja sempre atualizado no campo `spec.templateValues.ClusterValues` do recurso de cluster Fleet. Isso permite que os usuários:
endif::[]
ifeval::["{build-type}" == "community"]
O Cluster *API Addon Provider Fleet* automatiza do aplicativo https://fleet.rancher.io/ref-fleet-yaml#templating[o modelo] para clusters CAPI importados com base no estado do cluster correspondente. Esse recurso garante que o estado de um cluster e de recursos CAPI esteja sempre atualizado no campo `spec.templateValues.ClusterValues` do recurso de cluster Fleet. Isso permite que os usuários:
endif::[]

- Faça referência a partes específicas do cluster CAPI diretamente ou por meio de padrões de substituição Helm que fazem referência aos dados do site `.ClusterValues.Cluster`.
- Substitua com base no estado do recurso do plano de controle por meio do campo `.ClusterValues.ControlPlane`.
- Substitua com base no estado do recurso do cluster de infraestrutura por meio do campo `.ClusterValues.InfrastructureCluster`.
- Manter um estado consistente do aplicativo em diferentes clusters.
- Use o mesmo modelo para vários clusters correspondentes para simplificar a implementação e o gerenciamento.

Para obter mais informações sobre o recurso, consulte a do site https://rancher.github.io/cluster-api-addon-provider-fleet/04_reference/02_templating-strategy.html[documentação sobre modelos] no livro.

== Exemplo - implementação da kindnet CNI

*Demonstração*: image:https://asciinema.org/a/seEFHKz5DVpUe5CQvWcddSJBp.svg[asciicast,link=https://asciinema.org/a/seEFHKz5DVpUe5CQvWcddSJBp]

== Exemplo - implantação do Calico CNI usando o GitRepo

*Demonstração*: image:https://asciinema.org/a/706570.svg[asciicast,link=https://asciinema.org/a/706570]

Para obter um tutorial e pré-requisitos, consulte a seção https://rancher.github.io/cluster-api-addon-provider-fleet/03_tutorials/04_installing_calico_via_gitrepo.html[tutorial] gitrepo no livro.
