include::partial$variables.adoc[]
= Autoridades de certificação personalizadas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure autoridades de certificação personalizadas para uso com as instalações do {project-name} para garantir comunicação e autenticação seguras.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["distributing-policies", "custom-certificate-authorities"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "autoridades de certificação personalizadas"]
:sidebar_label: Autoridades de certificação personalizadas
:sidebar_position: 50
:current-version: {page-origin-branch}

Com os sites `+kwctl+` e `+policy-server+`, é possível extrair políticas dos registros da Open Container Initiative (OCI) e dos servidores HTTP.
Só é possível enviar políticas para os registros da OCI.
Por padrão, o HTTPS é usado com a verificação TLS do host para isso.

O armazenamento da autoridade de certificação (CA) do sistema é usado para validar a cadeia confiável de certificados do registro da OCI.
Em uma instalação padrão do {project-name}, o `+policy-server+` usa o armazenamento da CA fornecido com o contêiner do Linux.
No lado do cliente, o `+kwctl+` usa o armazenamento de CA do sistema operacional.

Se estiver usando ohttps://github.com/kubewarden/kubewarden-controller[Controller], você poderá configurar o PolicyServer por meio dosxref:/howtos/policy-servers/01-custom-cas.adoc[campos`+spec+` ].

[NOTE]
====

O comportamento padrão de `+kwctl+` e `+policy-server+` impõe HTTPS com certificados confiáveis que correspondem ao armazenamento da CA do sistema.
Você pode interagir com os registros usando certificados não confiáveis ou mesmo sem TLS, usando a configuração `+insecure_sources+`.
Claramente, não se destina a ambientes de produção.
====


== O arquivo `+sources.yaml+` 

Você pode ajustar o comportamento push-pull de `+kwctl+` e `+policy-server+` usando o arquivo `+sources.yaml+`.

Para obter detalhes da referência, verifique a xref:../reference/sources_yaml.adoc[`+sources.yaml+`] referência.
