include::partial$variables.adoc[]
= {project-name} em um ambiente de grande escala
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure o {project-name}s com o {project-name} para garantir alta disponibilidade e desempenho em ambientes exigentes de grande escala.
:keywords: [kubewarden, "{project-name}", kubernetes, policyservers, production]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual do operador, servidores de políticas, produção
:sidebar_label: Implementação em escala
:sidebar_position: 21

Esta seção detalha uma implementação real do {project-name} em um ambiente exigente e de grande escala. Ele ilustra como configurar o site {short-project-name} para obter alta disponibilidade e desempenho e o que esperar sob carga pesada.

[IMPORTANT]
====
Se você quiser ver mais dicas sobre como executar o {short-project-name} na produção, consulte a documentação sobre xref:/howtos/production-deployments.adoc[implantações de produção].
====

== Visão geral do ambiente

A infraestrutura consiste em aproximadamente 20 clusters Kubernetes. Os maiores desses clusters são caracterizados por tamanho e volume de recursos significativos:

* Nós: ~400
* Namespaces: ~4.000
* Recursos gerenciados:
** Pods: 10,000
** RoleBindings: 13,000
** Ingressantes: 12,000
** Implantações: 8,000
** Serviços: 13,000

== {short-project-name} Configuração

Para atender às demandas desse ambiente, o {short-project-name} é configurado com foco no isolamento da carga de trabalho e na alta disponibilidade.

* Aplicação da política: 22 `+ClusterAdmissionPolicies+` são aplicadas em todos os clusters, sem nenhum namespace específico `+AdmissionPolicies+`.
* Arquitetura do PolicyServer: Duas implementações separadas do `+PolicyServer+` são usadas para isolar as cargas de trabalho:
** Um site `+PolicyServer+` é dedicado exclusivamente a políticas com reconhecimento de contexto.
** Um segundo site `+PolicyServer+` lida com todas as outras políticas sem reconhecimento de contexto.
* Escalabilidade e recursos:
** Réplicas: Cada implementação do `+PolicyServer+` executa 15 réplicas para lidar com o alto volume de solicitações.
** Alocação de recursos: A cada réplica são alocados 300 MB de memória e 4 núcleos de CPU.

== Métricas de desempenho

Essa configuração gerencia com êxito uma alta taxa de solicitações de admissão e mantém um desempenho previsível.

* Taxa de transferência da solicitação de admissão: Os clusters processam até 300 solicitações de admissão por segundo (incluindo validações de webhook e varreduras de auditoria).
* Latência da política:
** Latência típica: As políticas com reconhecimento de contexto geralmente levam cerca de 500 ms para serem executadas.
** Intervalos: Nesse ambiente de alto rendimento, os tempos limite do webhook são configurados em 2,5 segundos, enquanto o tempo limite do `+PolicyServer+` é definido em 10 segundos. Embora a maioria das solicitações seja rápida, a infraestrutura foi criada para lidar com operações lentas ocasionais sem comprometer a estabilidade do servidor de API.

== Auditoria do desempenho do scanner

O scanner de auditoria é utilizado para garantir a conformidade contínua em um grande número de recursos.

* Frequência: Uma auditoria em todo o cluster é realizada a cada 4 horas.
* Configuração: O trabalho de auditoria é ajustado para obter o máximo de paralelismo e reduzir o tempo de execução:

[source,shell]
----
--parallel-namespaces: "10"
--parallel-resources: "20"
--parallel-policies: "20"
--page-size: "1000"
----

* Duração da auditoria: Mesmo no maior cluster com dezenas de milhares de recursos, um trabalho de auditoria completo é concluído em
