include::partial$variables.adoc[]
= Configuração da pilha {project-name} para produção
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure tolerâncias e regras de afinidade para agendamento e confiabilidade ideais na pilha {project-name} em um cluster Kubernetes.
:keywords: ["{project-name}", kubewarden, kubernetes, policyservers, production, poddisruptionbudget, affinity, limits, tolerations, priorityclass]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual do operador, servidores de política, produção, orçamento de interrupção de pod, afinidade, limites, tolerâncias, classe de prioridade

{project-name} fornece recursos para confiabilidade e agendamento correto de seus componentes em um cluster Kubernetes. Algumas das dicas desta página foram dadas por membros da comunidade{short-project-name} que usam o {short-project-name} em escala.

[IMPORTANT]
====
Se quiser ver um exemplo real de execução do {short-project-name} em escala, consulte a página de documentação xref:/howtos/deploy-at-scale.adoc[{short-project-name} em um ambiente de grande escala].

====

== Configuração de tolerâncias e afinidade/antiafinidade

Usando os campos `+tolerations+` e `+affinity+`, as operadoras podem ajustar a programação e a confiabilidade da pilha {short-project-name}para atender às suas necessidades e restrições específicas de implantação. Para obter mais detalhes sobre os campos exatos e suas configurações, consultehttps://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[Kubernetes documentation on Taints and Tolerations] ehttps://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[Affinity and Anti-Affinity].

A partir da versão 1.15 da pilha {short-project-name}, os gráficos do{short-project-name} Helm são fornecidos com dois novos valores:

* `+.global.tolerations+`
* `+.global.affinity+`

Esses valores do Helm chart permitem que os usuários definam as tolerâncias do Kubernetes e as configurações de afinidade/antiafinidade para a pilha {short-project-name}, incluindo a implantação do controlador, o cronjob do scanner de auditoria e o recurso personalizado padrão`+PolicyServer+`.

=== Tolerâncias

O valor `+tolerations+` é uma matriz em que os usuários podem especificar as tolerâncias do Kubernetes para os componentes {short-project-name}. As tolerâncias permitem que os pods sejam agendados em nós com taints correspondentes. Isso é útil para gerenciar onde os pods podem ser agendados, especialmente em cenários que envolvem manutenção de nós, cargas de trabalho dedicadas ou requisitos específicos de hardware:

[source,yaml]
----
global:
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoSchedule"
    - key: "key2"
      operator: "Equal"
      value: "value2"
      effect: "NoExecute"
----

Neste exemplo, as tolerâncias definidas são aplicadas à implantação do controlador, ao cronjob do scanner de auditoria e ao recurso personalizado padrão `+PolicyServer+`.

=== Afinidade/Antiafinidade

O valor `+affinity+` permite que os usuários definam as regras de afinidade e antiafinidade do Kubernetes para os componentes {short-project-name}. As regras de afinidade restringem os pods a nós específicos, enquanto as regras de antiafinidade impedem que os pods sejam agendados em determinados nós ou próximos a outros pods. Essas configurações são úteis para garantir alta disponibilidade, tolerância a falhas e uso otimizado de recursos em um cluster.

[source,yaml]
----
global:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: security
                operator: In
                values:
                  - S1
          topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: security
                  operator: In
                  values:
                    - S2
            topologyKey: topology.kubernetes.io/zone
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: label-1
                operator: In
                values:
                  - key-1
        - weight: 50
          preference:
            matchExpressions:
              - key: label-2
                operator: In
                values:
                  - key-2
----

Neste exemplo, as regras de afinidade serão aplicadas à implantação do controlador, ao cronjob do scanner de auditoria e ao recurso personalizado padrão `+PolicyServer+`.

A configuração de afinidade anterior disponível no gráfico `+kubewarden-default+`Helm, que foi usada para definir a configuração de afinidade somente para o`+PolicyServer+`, foi removida em favor do valor global `+affinity+`. Essa alteração simplifica o processo de configuração, fornecendo uma abordagem única para definir regras de afinidade e antiafinidade para todos os componentes do site{short-project-name}.

[WARNING]
====
A antiga configuração do `+affinity+` no gráfico do `+kubewarden-default+` Helm foi removida. Os usuários agora devem usar o campo `+.global.affinity+` para definir as configurações de afinidade e antiafinidade para toda a pilha {short-project-name}.
====

== Configuração de priorityClasses

Ao usar priorityClasses, os operadores podem impor uma prioridade de agendamento para os pods de carga de trabalho da pilha {short-project-name}. Isso garante que a carga de trabalho do{short-project-name} esteja disponível em relação a outras cargas de trabalho, impedindo o despejo e garantindo a confiabilidade do serviço. Para obter mais informações, consultehttps://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/[Documentação do Kubernetes sobre Priorityclasses].

A partir da versão 1.25 da pilha {short-project-name}, os gráficos do{short-project-name} Helm são fornecidos com um novo valor:

* `+.global.priorityClassName+`

A priorityClass definida pelo nome nesse valor é aplicada aos pods de implantação do controlador e aos pods do recurso personalizado padrão `+PolicyServer+`.

O valor `+.global.priorityClassName+` espera um nome de uma PriorityClass existente. Como exemplo, poderíamos usar:

[source,yaml]
----
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubewarden-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
----

O Kubernetes já vem com duas PriorityClasses que são boas candidatas: `+system-cluster-critical+` e`+system-node-critical+`. Essas são classes comuns e são usadas parahttps://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/[garantir que os componentes críticos sejam sempre programados primeiro].

[WARNING]
====
Se você excluir uma PriorityClass, os Pods existentes que usam o nome da PriorityClass excluída permanecerão inalterados, mas os Pods seguintes que usam o nome da PriorityClass excluída não serão criados pelo Kubernetes.
====

== `+PolicyServer+` configuração da produção

`+PolicyServers+` são essenciais para o cluster. A confiabilidade deles é importante, pois eles processam solicitações de admissão destinadas à API do Kubernetes por meio dos Webhooks de validação e mutação.

Como acontece com outros controladores de admissão dinâmica, esse processo ocorre antes que as solicitações cheguem ao servidor da API do Kubernetes. A latência ou os atrasos no serviço pelo Dynamic Admission Controller podem introduzir inconsistência no cluster, negação de serviço ou deadlock.

{short-project-name} oferece várias maneiras de aumentar a confiabilidade do`+PolicyServers+`. As implementações de produção podem variar muito, cabendo ao operador configurar a implementação de acordo com suas necessidades.

=== PodDisruptionBudgets

O controlador {short-project-name} pode criar umhttps://kubernetes.io/docs/tasks/run-application/configure-pdb/[PodDisruptionBudget](PDB) para os `+PolicyServer+` Pods. Isso controla o intervalo de réplicas do pod `+PolicyServer+`associadas ao `+PolicyServer+`, garantindo alta disponibilidade e despejo controlado em caso de manutenção de nós, operações de dimensionamento ou upgrades de cluster.

Isso é feito por meio da configuração de `+spec.minAvailable+` ou `+spec.maxUnavailable+`do recurso `+PolicyServer+`:

* `+minAvailable+`Especifica o número mínimo de `+PolicyServer+` Pods que devem estar disponíveis o tempo todo. Pode ser um número inteiro ou uma porcentagem.

  Useful for maintaining the operational integrity of the `+PolicyServer+`,
  ensuring that policies are continuously enforced without interruption.

* `+maxUnavailable+`Especifica o número máximo de `+PolicyServer+` Pods que podem estar indisponíveis em um determinado momento. Pode ser um número inteiro ou uma porcentagem.

  Useful for performing rolling updates or partial maintenance without
  fully halting the policy enforcement mechanism.

[NOTE]
====
Você pode especificar apenas um dos endereços `+maxUnavailable+` e `+minAvailable+`.
====

==== Configuração de minAvailable ou maxUnavailable

.Exemplo: Definir minAvailable
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  minAvailable: 2 # ensure at least two policy-server Pods are available at all times
----

.Exemplo: Definir maxUnavailable
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  maxUnavailable: "30%" # ensure no more than 30% of policy-server Pods are unavailable at all times
----

=== Afinidade / Antiafinidade

O controlador {short-project-name} pode definir a afinidade dos Pods`+PolicyServer+`. Isso permite a restrição de Pods a nós específicos ou Pods contra outros Pods. Para obter mais informações sobre o Affinity, consulte o sitehttps://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[Kubernetes docs].

A configuração de afinidade do Kubernetes permite restringir Pods a nós (via`+spec.affinity.nodeAffinity+`) ou restringir Pods em relação a outros Pods (via `+spec.affinity.podAffinity+`). A afinidade pode ser definida como uma restrição branda (com `+preferredDuringSchedulingIgnoredDuringExecution+`) ou rígida (com `+requiredDuringSchedulingIgnoredDuringExecution+`).

Combinações de afinidade/antiafinidade com rótulos específicos, sejam eles rótulos de nós (por exemplo: `+topology.kubernetes.io/zone+` definido como `+antarctica-east1+`) ou rótulos de pods. Os pods criados a partir das definições de `+PolicyServer+` têm um rótulo`+kubewarden/policy-server+` definido como o nome do `+PolicyServer+`. (por exemplo:`+kubewarden/policy-server: default+`).

[NOTE]
====
A afinidade/antiafinidade entre nós requer quantidades substanciais de processamento e não é recomendada em clusters com mais de várias centenas de nós.
====

Para configurar a afinidade para um `+PolicyServer+`, defina seu campo `+spec.affinity+`. Esse campo aceita um objeto YAML que corresponda ao conteúdo do site`+spec.affinity+` de um pod.

==== Configuração de afinidade/antiafinidade

.Exemplo: Distribua os pods do `+PolicyServer+` entre zonas e nomes de host
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: kubewarden/policy-server
                operator: In
                values:
                  - your-policy-server
          topologyKey: topology.kubernetes.io/zone
        - labelSelector:
            matchExpressions:
              - key: kubewarden/policy-server
                operator: In
                values:
                  - your-policy-server
          topologyKey: kubernetes.io/hostname
----

.Exemplo: Agende apenas pods `+PolicyServer+` em nós do plano de controle
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: kubewarden/policy-server
                operator: In
                values:
                  - your-policy-server
          topologyKey: node-role.kubernetes.io/control-plane
----

=== Limites e solicitações

O controlador {short-project-name} pode definir os limites de recursos e as solicitações dos pods `+PolicyServer+`. Isso especifica a quantidade de cada recurso que cada um dos contêineres associados aos pods do `+PolicyServer+` precisa. Para`+PolicyServers+`, somente os recursos `+cpu+` e `+memory+` são relevantes. Consulte o sitehttps://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes[Kubernetes docs] sobre unidades de recursos para obter mais informações.

Isso é obtido com a configuração dos seguintes campos de recursos do site `+PolicyServer+`:

* `+spec.limits+`: Limites de recursos, impostos pelo tempo de execução do contêiner. Diferentes tempos de execução podem ter maneiras diferentes de implementar as restrições.
* `+spec.requests+`: Quantidade de recursos a serem reservados para cada contêiner. É possível e permitido que um contêiner use mais recursos do que o seu `+request+`.

  If omitted, it defaults to `+spec.limits+` if that is set (unless
  `+spec.requests+` of containers is set to some defaults via an admission
  mechanism).

[NOTE]
====
O subcomprometimento de recursos do site `+PolicyServers+` pode causar problemas de confiabilidade no cluster.
====

==== Configuração de limites e solicitações

.Exemplo: Defina limites rígidos para cada contêiner `+PolicyServer+` 
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  limits:
    cpu: 500m
    memory: 1Gi
----

=== Classes de prioridade

O controlador {short-project-name} pode definir a PriorityClass usada para os pods de `+PolicyServers+`. Isso significa que as cargas de trabalho do `+PolicyServer+` são agendadas com prioridade, impedindo o despejo e garantindo a confiabilidade do serviço. Consultehttps://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/[docs do Kubernetes para obter mais informações].

[WARNING]
====
Se você excluir uma PriorityClass, os Pods existentes que usam o nome da PriorityClass excluída permanecerão inalterados, mas os Pods seguintes que usam o nome da PriorityClass excluída não serão criados pelo Kubernetes.
====

==== Configuração de classes de prioridade

.Exemplo: Usando o padrão `+system-cluster-critical+` priorityClass:
[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: your-policy-server
spec:
  # Other configuration fields
  priorityClassName: system-cluster-critical
----

=== Isolar cargas de trabalho de políticas

Para garantir a estabilidade e o alto desempenho em escala, os usuários podem executar*`+PolicyServer+`* implementações separadas para isolar cargas de trabalho diferentes.

* *Dedique um site `+PolicyServer+` às políticas com reconhecimento de contexto:* Essas políticas consomem mais recursos porque consultam o servidor da API do Kubernetes ou outros serviços externos, como Sigstore, registros de OCI, entre outros. Isolá-las evita que uma política lenta crie um gargalo para outras políticas mais rápidas.
* *Use outro `+PolicyServer+` para Todas as outras políticas:* Execute políticas regulares e independentes em um servidor separado para garantir baixa latência para as solicitações de admissão mais comuns.

Você também pode considerar a possibilidade de dividir ainda mais a carga de trabalho. Por exemplo, se você tiver algumas políticas que são lentas e exigem um tempo limite de execução maior, considere movê-las para um site dedicado `+PolicyServer+`. Dessa forma, você garante que as políticas não bloquearão os funcionários para avaliar outras solicitações.

=== Alocação e dimensionamento de recursos

Para lidar com o alto tráfego e garantir a disponibilidade, forneça recursos suficientes e dimensione suas réplicas.

* *Alocar recursos suficientes:* Em ambientes de alto tráfego, aloque recursos generosos para cada réplica. Não sobrecarregue o site `+PolicyServers+`, pois a falta de CPU ou memória é a principal causa de timeouts de solicitação. Lembre-se de que o site `+PolicyServers+` receberá solicitações do plano de controle e do scanner de auditoria{short-project-name}.
* *Escalonamento para alta disponibilidade:* Para implementações que lidam com centenas de solicitações por segundo, execute um grande número de réplicas. Isso distribui a carga de forma eficaz e garante que a falha de alguns pods não afete a operação do cluster.

Comece com uma linha de base de 3 a 5 réplicas e monitore o uso da CPU e da memória. Dimensione a contagem de réplicas conforme necessário.

=== Auditoria eficaz em escala

Para executar auditorias com eficiência em grandes clusters, faça o ajuste fino do scanner de auditoria para obter desempenho e paralelismo.

* *Agendar auditorias periodicamente:* Executar uma varredura com frequência pode ser um bom equilíbrio entre a detecção de desvios de configuração e a minimização da carga no servidor de API.
* *Ajuste o paralelismo de forma agressiva:* A chave para auditorias rápidas é a paralelização. Com configurações de alto paralelismo, você pode reduzir os tempos de auditoria em clusters enormes para pouco mais de uma hora.

[WARNING]
====
É importante lembrar que o scanner de auditoria envia solicitações para`+PolicyServers+`. Portanto, seu paralelismo pode afetar o desempenho do site `+PolicyServer+`. Se você quiser ter um paralelismo agressivo para reduzir os tempos de varredura em grandes clusters, talvez seja necessário aumentar os recursos disponíveis do servidor de políticas para não afetar o desempenho do controlador de admissão.
====

Defina `+disableStore: true+` para reduzir a carga se você consumir resultados de auditoria de logs e não precisar da política `+Reports+` nem de `+ClusterReports+` recursos personalizados no cluster.
