include::partial$variables.adoc[]

= Configuraﾃｧﾃ｣o de proxy
:description: Uso de proxies com {project-name}.
:keywords: ["{project-name}", "kubewarden", "kubernetes", "proxy", "proxies"]
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-type: ["howto"]
:doc-topic: ["operator-manual", "proxy"]

Em `+kwctl+` e `+policy-server+`, vocﾃｪ pode configurar proxies HTTP e HTTPS, bem como isentar domﾃｭnios dessa configuraﾃｧﾃ｣o de proxy.

Vocﾃｪ pode fazer isso de duas maneiras:* Definindo as variﾃ｡veis de ambiente `+HTTP_PROXY+`, `+HTTPS_PROXY+`, `+NO_PROXY+`(e suas contrapartes em minﾃｺsculas) para `+kwctl+` ou `+policy-server+`.
  Para configurar um CR do PolicyServer, defina sua matriz `+spec.env+`.* Fornecendo um arquivo `+sources.yaml+` por meio do argumento `+--sources-path+`.
  Um arquivo `+sources.yaml+` tem precedﾃｪncia sobre as variﾃ｡veis de ambiente.
  O consumo dessa configuraﾃｧﾃ｣o por meio do campo `+spec+` ainda nﾃ｣o estﾃ｡ exposto nos CRs do PolicyServer.

A definiﾃｧﾃ｣o de uma configuraﾃｧﾃ｣o de proxy influencia:

* Polﾃｭtica pull, push e pull-and-run de e para o registro OCI.
* Recursos de host de chamadas com reconhecimento de contexto, como:
** Registro de contﾃｪineres, como a obtenﾃｧﾃ｣o de um manifesto OCI ou resumo de manifesto.
   Em vez de acessar o registro OCI diretamente, o trﾃ｡fego serﾃ｡ roteado por meio dos proxies configurados.
** Recursos do Sigstore, como a verificaﾃｧﾃ｣o de uma assinatura sem chave.
   Em vez de atingir os serviﾃｧos definidos pela Sigstore, o trﾃ｡fego serﾃ｡ roteado por meio dos proxies configurados.

== Exemplo

Vocﾃｪ pode definir as seguintes variﾃ｡veis de ambiente para `+kwctl+` ou`+policy-server+` (por meio do PolicyServer `+spec.env+`):

[source,bash]
----
HTTP_PROXY="http://proxy.corp:3128"
https_proxy="http://proxy.corp:3129"
NO_PROXY="localhost,.corp"
----

Com essa configuraﾃｧﾃ｣o:* O trﾃ｡fego nﾃ｣o seguro via HTTP, como o trﾃ｡fego de e para um registro OCI inseguro, ﾃｩ roteado por meio do site `+\http://proxy.corp:3128+`.
  Isso afeta as polﾃｭticas de extraﾃｧﾃ｣o e as polﾃｭticas que chamam recursos com reconhecimento de contexto que tﾃｪm resumos de manifesto de imagem OCI para contﾃｪineres nesse repositﾃｳrio.* O trﾃ｡fego criptografado via HTTPS ﾃｩ roteado por meio do site `+\https://proxy.corp:3129+`.
  Por exemplo, isso inclui a extraﾃｧﾃ｣o e o envio de polﾃｭticas para qualquer registro seguro da OCI e os recursos de polﾃｭticas com reconhecimento de contexto mencionados.* O trﾃ｡fego de e para o localhost ou qualquer domﾃｭnio em `+.corp+` estﾃ｡ isento das configuraﾃｧﾃｵes anteriores.


== O arquivo `+sources.yaml+` 

Para obter mais detalhes, consulte a xref:/reference/sources_yaml.adoc[`+sources.yaml+`] referﾃｪncia.