include::partial$variables.adoc[]
= Audit Scanner - Limitaciones
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Conozca las limitaciones a la hora de utilizar el Audit Scanner para evaluar políticas y tipos de eventos en un entorno Kubernetes, incluido su uso para la evaluación de políticas y tipos de eventos.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["explanations", "audit-scanner", "limitations"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "kubernetes", "audit scanner"]
:sidebar_label: Limitaciones
:current-version: {page-origin-branch}

== Tipos de eventos admitidos

Las políticas pueden inspeccionar los eventos `+CREATE+`, `+UPDATE+`, y `+DELETE+`.

El escáner de auditoría no puede simular eventos de `+UPDATE+`, ya que no sabe qué parte del recurso requiere cambios.

Así, el escáner de auditoría ignora una política que sólo se ocupa de los eventos de `+UPDATE+`. escáner.

[NOTE]
====

La versión audit-scanner v1.7.0 sólo admite eventos de `+CREATE+`. La gestión de los eventos de`+DELETE+` estará disponible próximamente.

====


== Políticas basadas en información sobre usuarios y grupos de usuarios

Cada objeto de solicitud de admisión de Kubernetes tiene información sobre qué usuario (o ServiceAccount) inició el evento y a qué grupo pertenece.

Todos los eventos simulados por el escáner de auditoría se originan en el mismo usuario y grupo codificados. Por eso, las políticas que se basan en estos valores para tomar sus decisiones no producirán resultados significativos.

Para estos casos, configure la política como no auditable. comprobaciones.

== Políticas basadas en datos externos

Las políticas pueden solicitar y utilizar datos externos al realizar una evaluación. Puede evaluar estas políticas con las comprobaciones de auditoría, pero sus resultados pueden cambiar en función de los datos externos.

== Utilización de `+*+` por las políticas

Tanto el recurso personalizado `+AdmissionPolicy+` como el `+ClusterAdmissionPolicy+` tienen los siguientes campos:

[subs="+attributes",yaml]
----
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
----

Los atributos `+apiGroups+`, `+apiVersions+` y `+resources+` pueden utilizar el comodín`+*+`. Este símbolo de comodín hace que la política coincida con todos los valores utilizados en el campo. El escáner de auditoría ignora las políticas que utilizan el símbolo `+*+`.
