= Primeiros passos com a telemetria aberta
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

image::otel/open-telemetry.svg[Coletor Open Telemetry e 2 aplicativos instrumentados que enviam métricas e rastreamentos para o SUSE Observability]

O SUSE Observability é compatível com o https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. O Open Telemetry é um conjunto de protocolos padronizados e uma estrutura de código aberto para coletar, transformar e enviar dados de telemetria, como rastreamentos, métricas e registros. A telemetria aberta é compatível com uma ampla variedade de linguagens de programação e plataformas.

O SUSE Observability tem suporte para métricas e rastreamentos e adiciona as métricas e os rastreamentos do Open Telemetry aos dados de topologia (Kubernetes) fornecidos pelo agente do SUSE Observability. Portanto, ainda é necessário instalar também o agente do SUSE Observability. Em breve, haverá suporte para registros e uso do Open Telemetry sem o agente SUSE Observability.

A Open Telemetry consiste em vários componentes diferentes. Para uso com o SUSE Observability, os xref:/setup/otel/languages/README.adoc[SDKs] para instrumentar seu aplicativo e o xref:/setup/otel/collector.adoc[coletor Open Telemetry] são as partes mais importantes. Mostraremos como configurar ambos para uso com o SUSE Observability.

Se o seu aplicativo já estiver instrumentado com o Open Telemetry ou com qualquer outra biblioteca compatível com o Open Telemetry, como Jaeger ou Zipkin, o coletor poderá ser usado para enviar esses dados para o SUSE Observability, sem necessidade de instrumentação adicional.

O SUSE Observability exige que o coletor seja configurado com processadores e autenticação específicos para garantir que todos os dados usados pelo SUSE Observability estejam disponíveis.

== Referências

* https://opentelemetry.io/docs/collector/[Coletor Open Telemetry] na documentação do Open Telemetry
* https://opentelemetry.io/docs/languages/[SDKs para instrumentar seu aplicativo] na documentação da Open Telemetry
