= Primeiros passos com a telemetria aberta
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

image::otel/open-telemetry.svg[Coletor Open Telemetry e 2 aplicativos instrumentados que enviam métricas e rastreamentos para o SUSE Observability]

O SUSE Observability é compatível com o https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. O Open Telemetry é um conjunto de protocolos padronizados e uma estrutura de código aberto para coletar, transformar e enviar dados de telemetria, como rastreamentos, métricas e registros. A telemetria aberta é compatível com uma ampla variedade de linguagens de programação e plataformas.

O SUSE Observability oferece suporte a métricas e rastreamentos. Quando usado em combinação com o stackpack do Kubernetes, os pods do Kubernetes serão enriquecidos com rastreamentos quando disponíveis. Ao instalar o pacote de pilha Open Telemetry, novas páginas de visão geral de serviços e instâncias de serviço ficam disponíveis, fornecendo acesso a rastreamentos e métricas de abrangência. As métricas do Open Telemetry podem ser usadas em monitores e associações de métricas. O stackpack vem com associações de métricas para métricas de extensão e métricas de memória .NET e JVM. Há também monitores prontos para uso para taxas de erro de span e duração.

A configuração recomendada para uso com o SUSE Observability é instrumentar os aplicativos com os xref:/setup/otel/instrumentation/README.adoc[SDKs] do Open Telemetry aplicáveis e instalar o xref:/setup/otel/collector.adoc[coletor do Open Telemetry] próximo aos aplicativos instrumentados para pré-processar os dados (enriquecer com rótulos do Kubernetes, amostragem em rastreamentos etc.) e enviar os dados para o SUSE Observability. O Open Telemetry Collector também pode ser usado para coletar métricas de vários tipos de fontes de telemetria sem instrumentar os aplicativos usando os SDKs. Consulte as https://opentelemetry.io/ecosystem/registry/?language=collector[integrações do coletor] para obter mais detalhes e saber se o seu banco de dados ou protocolo de telemetria é compatível.

Siga o guia xref:/setup/otel/getting-started/README.adoc[de introdução] para configurar tudo de modo que funcione melhor com o SUSE Observability.

== Referências

* https://opentelemetry.io/docs/collector/[Coletor Open Telemetry] na documentação do Open Telemetry
* https://opentelemetry.io/ecosystem/registry/?language=collector[Integrações com coletores de telemetria aberta]
* https://opentelemetry.io/docs/instrumentation/README.md[SDKs para instrumentar seu aplicativo] na documentação da Open Telemetry
