include::partial$variables.adoc[]

= {project-name} 対OPAゲートキーパー
:revdate: 2026-03-18
:page-revdate: {revdate}
:page-aliases: explanations/opa-comparison.adoc
:description: Kubernetes 環境向けの OPA Gatekeeper と{project-name} ポリシー管理を比較し、ユースケースに最適なアプローチを決定します。
:doc-persona: ["kubewarden-all"]
:doc-topic: ["explanations", "kubewarden-vs-opa_gatekeeper"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "opa gatekeeper", "comparison"]
:current-version: {page-origin-branch}

[IMPORTANT]
====

このページは2023年8月のものです。どちらのプロジェクトも、その後進化しているかもしれない。

何かが欠けていたり、不正確であったりする場合は、https://github.com/kubewarden/docs/[]、ページ下部のリンクからするか、PRを開設してください。

====

OPAゲートキーパーと、{project-name} から派生したKubewardenは、どちらもオープンソースプロジェクトであり、CNCFの一部である。

この表は、OPAゲートキーパーと{short-project-name} の比較です。より詳細な情報が必要なトピックには、さらに詳しい説明へのリンクがある。

|===
| 特徴 | OPAゲートキーパー | {short-project-name}

| バリデーション
| ✅
| ✅

| 突然変異
| ✅
| ✅

| ポリシー・ランゲージ<<_writing_policies,[1］>>
| レゴ
| レゴ、CEL、ゴー、ラスト、...

| コンテキスト・アウェア<<_context_aware,[2］>>
| ✅
| ✅

| Kubernetesの統合<<_kubernetes_integration,[3］>>
| クラスターワイドCRD
| クラスタワイドおよび名前空間CRD

| 政策配分<<_policy_distribution,[4］>>
| Kubernetes CRに組み込まれた
| コンテナレジストリ、またはKubernetes CR（CEL）への組み込み

| CI/CDの統合<<_cicd_integration,[5］>>
| ✅
| ✅

| ポリシー実施モード
| 拒否、警告
| 拒否、警告

| デプロイメント・モード<<_deployment_mode,[6］>>
| 単体評価サーバー
| 複数の評価サーバー

| バックグラウンド・チェック<<_background_checks,[7］>>
| ✅
| ✅
|===

== ポリシーの種類

OPA GatekeeperもKubernetesも、検証と変異のポリシーを書くことができる。

これらのポリシーは、カスタムリソースを含むあらゆる種類のKubernetesリソースを対象とすることができる。

== ポリシーの作成

https://www.openpolicyagent.org/docs/latest/#rego[Rego を]使用して、OPA Gatekeeper ポリシーを記述します。レゴは、オープン・ポリシー・エージェント・プロジェクトによって作られたクエリー言語である。

[IMPORTANT]
====

レゴを使えるのは、有効なポリシーを書くときだけだ。変異するポリシーはRegoを使わず、代わりにYAMLで定義されたアドホックなルールを使います(https://open-policy-agent.github.io/gatekeeper/website/docs/mutation[こちら])。

====


さまざまなパラダイムを使って、{short-project-name} ポリシーを書くことができる。ポリシー作成者は、GoやRustなどの伝統的なプログラミング言語も、RegoやCELなどのhttps://en.wikipedia.org/wiki/Domain-specific_language[Domain Specific Languages]も使うことができる。{short-project-name} では、検証ポリシーと変異ポリシーを同じように書く。

[CAUTION]
====

オープン・ポリシー・エージェント・プロジェクトの一部であるhttps://github.com/open-policy-agent/kube-mgmt[]kube-mgmtオープンソース・プロジェクトはRegoを使用している。

同じ言語を使用しているにもかかわらず、kube-mgmt 用に書かれたポリシーは OPA Gatekeeper と互換性がなく、その逆も同様です。

{short-project-name} は、Open Policy Agent 用と OPA Gatekeeper 用の両方に記述された Rego ポリシーを使用できます。詳細はxref:/tutorials/writing-policies/rego/01-intro-rego.adoc[こちら]。

====


== コンテキストを認識する

ポリシーが検証や突然変異の決定を下すために、クラスターの現在の状態に関するデータを必要とすることがある。例えば、Ingressリソースを検証するポリシーは、衝突が起きないように、クラスタ内ですでに定義されている他のIngressリソースを知る必要があるかもしれない。{short-project-name} 、これらのポリシーを「コンテキスト・アウェア」と呼ぶ。

OPA ゲートキーパーおよび{short-project-name} はいずれも、この種のポリシーに対応しています。

OPA Gatekeeperを導入する際、Kubernetes管理者は評価時にどのタイプのクラスタデータをポリシーで利用可能にするかを決定します。

このデータが、導入されたすべてのポリシーによってどのようにアクセスされるかを強調することが重要だ。

例えば、OPA GatekeeperポリシーがKubernetes Secretsへのアクセスを必要とする場合、配備された他の全てのポリシーは同様にこのデータを読み取ることができます。

逆に、{short-project-name} はクラスタ・リソースへのきめ細かいアクセスを提供する。
各ポリシーは、Kubernetes管理者が指定したリソースにのみアクセスできる。未承認のデータを読み込もうとすると即座にブロックされ、クラスタ管理者に報告される。

== Kubernetesの統合

OPA ゲートキーパーには、クラスタ全体のカスタムリソースがあり、ポリシーの定義と、それをどこでどのように実行するかを許可します。

{short-project-name} には、ポリシーを宣言するために使用される2つの異なるタイプのカスタム・リソースがあります。1つはクラスタレベルで動作し、もう1つは名前空間です。名前空間化されたカスタムリソースの名前は`+AdmissionPolicy+` です。

`+AdmissionPolicy+` リソースを介してデプロイされたポリシーは、それが属するネームスペース内で作成されたリソースにのみ影響します。そのため、管理者でないKubernetesユーザーがアクセスできる名前空間で、`+AdmissionPolicy+` リソースを管理するのに必要なRBAC権限を持つことを許可できる。

これにより、Kubernetes管理者はポリシー関連の作業を委任することができる。

== 政策配分

OPAゲートキーパーと{short-project-name} のポリシーは、Kubernetesでポリシーを定義するカスタムリソースにポリシーのソースコード（OPAゲートキーパーの場合はRego、{short-project-name} の場合はCEL）を持っています。

また、{short-project-name} ポリシーは、ポリシーのソースコードをコンテナ・イメージのように管理することができる（Rego、Go、Rust、... の場合）。ビルドされると、OCIアーティファクトとしてコンテナ・レジストリーにプッシュされる。

https://sigstore.dev[] Sigstoreプロジェクトの`+cosign+` のようなコンテナ・イメージ・ツールを使って、{short-project-name} ポリシーに署名し、検証することができる。

コンテナ・イメージに採用されている従来のツールとプロセスを使用して、地理的に分散したコンテナ・レジストリ間で{short-project-name} ポリシーを配布できる。

== CI/CD統合

OPAゲートキーパーと{short-project-name} の両方は、GitOps手法を用いて管理されている。

しかし、OPA Gatekeeperでは、ポリシーのRegoコードとKubernetesにデプロイするためのCustom Resourceの間にカップリングがある。
これはCI/CDパイプラインに余分なステップをもたらす。

レゴは、https://www.openpolicyagent.org/docs/latest/policy-testing/[テスト・ツール]を持っており、ユニット・テスト・スイートを作成することができる。テストを書き、CI/CDパイプラインで実行することは、ポリシーが期待通りに動作することを保証するために不可欠である。

これらのテスト・ツールを使うには、ポリシーのソース・コードが専用のテキスト・ファイルで利用可能でなければならない。OPAゲートキーパーのポリシーを宣言するために使用されるYAMLファイルからソースコードを読み取ることは不可能だ。CI/CD パイプラインは、テストする Rego ソースコードを OPA Gatekeeper Custom Resource に定義されたコードと同期させる必要があります。これはサードパーティ製のツールを使って行うことができる。

{short-project-name} ポリシーには、従来のマイクロサービスのようなCI/CDパイプラインがある。
通常、ソースコードはGitリポジトリに置かれ、伝統的なCI/CDシステムを使って、ユニットテストがそれに対して実行される。あなたは、ポリシーを記述するために使用される言語のテストフレームワークを使用してユニットテストを記述します。すべてのテストに合格したら、ポリシーをWebAssemblyにコンパイルし、コンテナ・レジストリにプッシュする。この種のパイプラインは通常、ポリシー作成者によって維持される。

Kubernetes管理者は通常、ポリシーの新しいリリースに反応する他の自動化パイプラインhttps://docs.github.com/en/code-security/dependabot/working-with-dependabot[（]、https://www.mend.io/renovate/[Dependabot]、https://www.updatecli.io/[Renovate bot]自動化ツールを使用）、またはポリシー構成の変更に反応する他の自動化パイプラインを維持する。

パイプラインは異なるタイプのリクエストに対してポリシーをテストする。テストはhttps://github.com/kubewarden/kwctl[`+kwctl+`]CLIツールを使ってテストを行うことができる。`+kwctl+` CLIツールは、Kubernetesクラスタにデプロイされた{short-project-name} スタックで使用されるのと同じ評価エンジンを使用する。

== ポリシー実施モード

OPAゲートキーパーと{short-project-name} は、2つの異なる操作モードを使用してポリシーを展開できます：

* `+deny+`ポリシー違反の場合、リクエストは拒否されます。
* `+warn+`ポリシー違反は拒否されず、ログに記録される。

== 展開モード

同じサーバーがすべてのOPAゲートキーパーのポリシーを評価します。逆に、{short-project-name} 、複数の評価サーバーを定義することができる。これらのサーバーは、`+PolicyServer+` というカスタムリソースで定義します。

{short-project-name} ポリシーを宣言する際、Kubernetes 管理者はどの`+PolicyServer+` がそれをホストするかを決定する。

[NOTE]
====

`+PolicyServer+` オブジェクトは、{short-project-name} によって導入された高レベルの抽象化である。
舞台裏では、特定のレプリカサイズを持つ`+Deployment+` 。

それぞれの`+PolicyServer+` 、他の選手とは異なるレプリカサイズを持つことができる。

====

これにより、次のような面白いシナリオが可能になる：

* 重要なポリシーを専用のPolicy Serverプールに展開する。
* うるさいテナントのポリシーを専用のPolicy Serverプールに展開する。

== バックグラウンド・チェック

ポリシーの追加、削除、再設定が行われると、クラスタ内のリソースが非準拠になる可能性がある。

OPAゲートキーパーと{short-project-name} はどちらも、バックグラウンドで動作するスキャナーを備えている。このスキャナーは、クラスタ内ですでに定義されているリソースを評価し、非準拠のものにフラグを立てる。

OPA Gatekeeper と{short-project-name} の唯一の違いは、スキャナ結果の保存方法である。

OPA ゲートキーパーは、違反の詳細を、指定された`+Constraint+` カスタムリソースの`+status+` フィールドに追加する（https://open-policy-agent.github.io/gatekeeper/website/docs/audit#constraint-status[を]参照）。

{short-project-name} の代わりに、https://openreports.io[openreports.ioによって]定義されたレポートカスタムリソースのセット内に結果を格納します。
