= Monitores
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

SUSE Observability tiene las mejores prácticas codificadas mediante monitores. Los monitores de SUSE Observability no sólo supervisan las métricas, los eventos o los registros, sino que también pueden supervisar la topología y los metadatos para detectar problemas comunes, garantizando la conformidad y el cumplimiento de las normas del sector.
Combinando los monitores con nuestra exclusiva inteligencia de solución de problemas, SUSE Observability detecta rápidamente los problemas relacionados y aconseja cómo solucionarlos. Este enfoque proactivo reduce el riesgo de problemas no detectados y ayuda a mantener un entorno Kubernetes sano y robusto.
Los monitores van acompañados de guías de solución específicas para el recurso sobre el que se alerta y la condición supervisada para orientar a nuestros usuarios en la resolución de problemas.

== Controlar los resultados

Los resultados del seguimiento se muestran en dos lugares:

. En las páginas destacadas de todos los recursos para ver inmediatamente qué está pasando y cómo remediarlo.
. En el panel de la derecha, si selecciona un elemento en la topología para darle una indicación rápida de los problemas de ese componente.

== Guías de reparación

Las guías de corrección se muestran en el cajón Estado del monitor, que aparece si abre un monitor haciendo clic en el mensaje de la perspectiva Resaltar de un recurso.

== Ver también

* xref:/use/alerting/kubernetes-monitors.adoc[Monitores listos para usar para Kubernetes]
