= マシン・オンボーディング
:revdate: 2025-11-06
:page-revdate: {revdate}

Machine Onboardingサービスの目的は、{elemental-product-name} Operatorカタログxref:references/machineinventory-reference.adoc[（MachineInventory]リソース）に新しいマシンを登録し、OSでホストをプロビジョニングし、必要な構成を適用することです。

マシン・オンボーディングには以下のステップがある：

* ユーザーはxref:references/machineregistration-reference.adoc[MachineRegistration]リソースを作成する。MachineRegistrationには、OSのインストールに必要なコンフィギュレーションが含まれている。
MachineRegistrationが作成されるとすぐに、{elemental-product-name} OperatorはHTTP_登録エンドポイントを_公開します。これは、オンボーディングホストがオペレータに登録するために必要なエントリポイントです。
* ユーザーは、xref:references/seedimage-reference.adoc[SeedImage]リソースを通じてセルフインストールイメージを要求します。SeedImageリソースが必要とするのは、MachineRegistrationリソースへの参照と、{elemental-product-name} Toolkitと互換性のあるOSコンテナイメージへの参照だけです。
SeedImageが作成されるとすぐに、{elemental-product-name} Operatorはセルフインストールimage: once completed, the URL is exposed in the `+status.downloadURL+` field of the xref:references/seedimage-reference.adoc[SeedImage]リソースのビルドプロセスをトリガーします。
* ユーザーはセルフインストールイメージをダウンロードし、それを使ってプロビジョニングされていないホストをブートする。ホストhttps://documentation.suse.com/cloudnative/os-manager/latest/en/rancher-os-management/authentication.html[]は、{elemental-product-name} オペレータの_登録エンドポイントに_、MachineRegistration に格納されている完全なコンフィギュレーションを取得し、OS をローカルストレージデバイスにインストールする。ホストが登録プロセスを完了するとすぐに、{elemental-product-name} オペレータはホストを追跡する一意のxref:references/machineinventory-reference.adoc[MachineInventory]リソースを作成します。
セルフインストールイメージは、任意の数のホストに搭載するために使用することができます。
