include::partial$variables.adoc[]
= Création d'une nouvelle politique de validation
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Créer une nouvelle politique de validation pour rejeter les noms d'hôtes non valides dans les objets Pod en configurant les paramètres de la politique et en les testant avec les outils fournis.
:keywords: {project-name}kubewarden, kubernetes, écrire des politiques en TypeScript, nouvelle politique de validation
:doc-type: tutoriel
:doc-topic: {project-name}kubewarden, writing-policies, typescript, création d'une nouvelle politique de validation
:doc-persona: kubewarden-policy-developer
:current-version: {page-origin-branch}

Ce tutoriel traite de la création d'une stratégie qui valide les noms d'hôte des objets Pod.

La politique consiste à rejeter tous les Pods qui utilisent un ou plusieurs noms d'hôtes figurant sur la liste de refus.
La configuration de la politique se fait à l'aide des paramètres d'exécution.

En résumé, les paramètres de la politique devraient ressembler à ceci :

[source,yaml]
----
denied_hostnames:
  - bad-host
  - forbidden-host
----

La politique rejette la création de ce pod :

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  hostname: bad-host
  containers:
    - name: nginx
      image: nginx:latest
----

Toutefois, il accepte la création de ce pod :

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  hostname: allowed-host
  containers:
    - name: nginx
      image: nginx:latest
----

== Échafaudage d'un nouveau projet politique

Vous pouvez créer un nouveau projet de politique à l'aide du https://github.com/kubewarden/js-policy-template[référentiel de modèles]. Sélectionnez le bouton vert "Utiliser ce modèle" en haut de la page et suivez l'assistant de GitHub.
Clonez le référentiel localement et mettez à jour le fichier `package.json` pour refléter les détails de votre politique :

[source,json]
----
{
  "name": "your-policy-name",
  "version": "1.0.0",
  "description": "Your policy description",
  "repository": {
    "type": "git",
    "url": "https://github.com/your-username/your-policy-name"
  }
}
----

Veillez à utiliser un chemin d'accès au dépôt qui corresponde à votre dépôt GitHub.

== Essais

Si les outils nécessaires sont en place, la commande `make all` construit la cible `annotated-policy.wasm`. La commande `make e2e` exécute des tests en utilisant `bats` avec `kwctl`.

.Résultats des commandes `make` 
[source,console]
----
make all
npx webpack --config webpack.config.cjs
asset bundled.js 5.52 KiB [compared for emit] [minimized] (name: main)
asset types.d.ts 430 bytes [compared for emit]
asset index.d.ts 11 bytes [compared for emit]
./src/index.ts 3.84 KiB [built] [code generated]
./node_modules/kubewarden-policy-sdk/dist/bundle.js 3.85 KiB [built] [code generated]
webpack 5.101.3 compiled successfully in 2280 ms
npm install
up to date, audited 400 packages in 2s
58 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
----

[source,console]
----
make e2e
npx webpack --config webpack.config.cjs
asset bundled.js 5.52 KiB [compared for emit] [minimized] (name: main)
asset types.d.ts 430 bytes [compared for emit]
asset index.d.ts 11 bytes [compared for emit]
./src/index.ts 3.84 KiB [built] [code generated]
./node_modules/kubewarden-policy-sdk/dist/bundle.js 3.85 KiB [built] [code generated]
webpack 5.101.3 compiled successfully in 1909 ms
bats e2e.bats
e2e.bats
 ✓ reject because hostname is on the deny list
 ✓ accept because hostname is not on the deny list
 ✓ accept because the deny list is empty
 ✓ accept because pod has no hostname set
 ✓ accept non-pod resources

5 tests, 0 failures
----