include::partial$variables.adoc[]

= Divulgación de la seguridad
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Investigadores de seguridad trabajan con el equipo de {project-name} para identificar vulnerabilidades utilizando protocolos de divulgación responsable.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["security", "disclosure"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "kubernetes", "security", "disclosure"]
:sidebar_label: Divulgación de la seguridad
:sidebar_position: 80
:current-version: {page-origin-branch}

El equipo de {project-name} aprecia el trabajo de investigación sobre vulnerabilidades de seguridad llevado a cabo por investigadores de seguridad éticos y bienintencionados. {short-project-name}sigue la práctica de [divulgación responsable](https://en.wikipedia.org/wiki/Responsible_disclosure) para proteger mejor a la base de usuarios de {short-project-name} del impacto de los problemas de seguridad. Por parte de{short-project-name}, esto significa:

* {short-project-name} responde prioritariamente a los incidentes de seguridad.
* {short-project-name} publica correcciones de los problemas tan pronto como resulta práctico, dando prioridad al riesgo.
* {short-project-name} siempre informa con transparencia a la comunidad de cualquier incidente que les afecte.

Si has encontrado una vulnerabilidad de seguridad en {short-project-name}, la forma más fácil de informar de una vulnerabilidad es a través dehttps://github.com/kubewarden/community/security/advisories[pestaña Seguridad en GitHub]. Este mecanismo permite a los mantenedores comunicarse en privado con usted, sin necesidad de cifrar sus mensajes.

Alternativamente, puede divulgarlo de forma responsable enviando un correo electrónico axref:mailto:cncf-kubewarden-maintainers@lists.cncf.io.adoc[cncf-kubewarden-maintainers@lists.cncf.io]en un mensaje *no cifrado*. Por favor, no hable de posibles vulnerabilidades en público sin validarlo antes con nosotros.

También puede venir a hablar en nuestrahttps://kubernetes.slack.com/archives/C03L52JRAFM[slack-room] en el servidor Kubernetes Slack.

Al recibir el equipo de seguridad:

* Revisa el informe, verifica la vulnerabilidad y responde con confirmaciones y/o solicitudes de información adicional.
* Una vez solucionado el fallo de seguridad notificado, {short-project-name} lo notifica al investigador, que puede optar por divulgarlo públicamente.

Consulte https://github.com/kubewarden/community[repositorio de la comunidad] para obtener más información sobre la Política de Gobernanza y Seguridad del proyecto.
