include::partial$variables.adoc[]
= Inicio rápido
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Comprenda la pila {project-name} aprendiendo a desplegar y gestionar sus componentes principales, incluidos los recursos PolicyServers y ClusterAdmissionPolicy.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["quick-start"]
:doc-type: ["tutorial"]
:keywords: ["{project-name}", "installation", "quick start", "policyserver", "clusteradmissionpolicy", "admissionpolicy"]
:sidebar_label: Inicio rápido
:sidebar_position: 20
:current-version: {page-origin-branch}

++++
<head>
<script async src="https://artifacthub.io/artifacthub-widget.js"></script>
</head>
++++

La pila {project-name} comprende:

* Uno o más recursos {cluster-admission-policy}: define políticas para clústeres Kubernetes.
* Uno o más recursos {policy-server}: representan un despliegue de un {short-project-name} `PolicyServer` . La página {short-project-name} `PolicyServer` carga y evalúa las políticas de su administrador.
* Uno o varios recursos {admission-policy}: políticas para un espacio de nombres definido.
* Un despliegue de un `kubewarden-controller`: este controlador supervisa los recursos {cluster-admission-policy} e interactúa con los componentes {short-project-name} {policy-server} .

[TIP]
====

{short-project-name} describexref:reference/CRDs.adoc[aquí] sus definiciones de recursos personalizadas (CRD) para Kubernetes.

{short-project-name} Los CRDs mencionados en este tutorial y en el resto de la documentación tienen nombres cortos, que son más fáciles de usar. Estos son los nombres abreviados de los CRD:

[cols="1,1"]
|===
| Recursos | shortName

| AdmissionPolicies
| *ap*

| ClusterAdmissionPolicies
| *tapa*

| AdmissionPolicyGroups
| *apg*

| ClusterAdmissionPolicyGroups
| *capg*

| PolicyServers
| *ps*

|===

====


== Instalación

[IMPORTANT]
.Autenticación
====

:gh-pat-url: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

Puedes recuperar las políticas de {short-project-name} desde el registro de contenedores de GitHub enhttps://ghcr.io.. Necesitas autenticación para usar el repositorio con la CLI{short-project-name}, un {gh-pat-url}[GitHub personal access token] (PAT). Si aún no lo has hecho, su documentación te guiará para crear uno.
Entonces te autentificas con un comando como:

[subs="+attributes",console]
----
echo $PAT | docker login ghcr.io --username <my-gh-username> --password-stdin
----

====


Despliegue la pila {short-project-name} utilizando los gráficos `helm` como se indica a continuación:

[subs="+attributes",console]
----
helm repo add kubewarden https://charts.kubewarden.io
----

[subs="+attributes",console]
----
helm repo update kubewarden
----

Instale las siguientes cartas Helm en el espacio de nombres `kubewarden` en su clúster Kubernetes:

* `kubewarden-crds`que registra las definiciones de recursos personalizados {cluster-admission-policy}, {admission-policy} y {policy-server}. También, las {report} Custom Resource Definitions utilizadas por el escáner de auditoría.
* `kubewarden-controller`que instala el controlador {short-project-name} y el escáner de auditoría
+
[NOTE]
====

Si necesita desactivar el componente del escáner de auditoría, consulte la xref:howtos/audit-scanner.adoc[página de documentación de la] instalación del escáner de auditoría.

====
+
* `kubewarden-defaults`que crea un recurso `PolicyServer` denominado `default`. También puede instalar un conjunto de políticas recomendadas para proteger su clúster aplicando las mejores prácticas conocidas.

[subs="+attributes",console]
----
helm install --wait -n kubewarden --create-namespace kubewarden-crds kubewarden/kubewarden-crds
----

[subs="+attributes",console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller
----

[subs="+attributes",console]
----
helm install --wait -n kubewarden kubewarden-defaults kubewarden/kubewarden-defaults
----

[CAUTION]
====

Desdehttps://github.com/kubewarden/kubewarden-controller/releases/tag/v0.4.0[`v0.4.0`]un recurso `PolicyServer` llamado `default` no se crea utilizando el gráfico`kubewarden-controller`. Ahora un gráfico Helm llamado `kubewarden-defaults`, instala el servidor de políticas por defecto.

Esto significa que si no se utiliza la última versión de `kubewarden-controller`al actualizar o eliminar, el servidor de políticas predeterminado no se actualiza ni se elimina. Por lo tanto, podría tener problemas si intenta instalar`kubewarden-defaults` con información contradictoria, por ejemplo, el mismo nombre de servidor de políticas. Para instalar futuras actualizaciones de la carta `kubewarden-defaults`Helm, elimine el recurso `PolicyServer` existente creado por`kubewarden-controller` antes de instalar la nueva carta. Ahora puede actualizar su servidor de políticas mediante actualizaciones de Helm sin conflictos de recursos. Al eliminar `PolicyServer`, también se eliminan todas las políticas vinculadas a él.

====


Los valores de configuración por defecto son suficientes para la mayoría de las implantaciones. Lahttps://charts.kubewarden.io/#configuration[documentación de] describe todas las opciones.

== Componentes principales

{short-project-name} tiene tres componentes principales con los que se interactúa:

* En {policy-server}
* En {cluster-admission-policy}
* En {admission-policy}

=== `PolicyServer`

La `kubewarden-controller` gestiona una {short-project-name} `PolicyServer`. Puede desplegar múltiples {policy-server}s en el mismo clúster Kubernetes.

`PolicyServer` valida las solicitudes entrantes ejecutando las políticas de {short-project-name}contra ellas.

Esta es la configuración por defecto de `PolicyServer`:

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: reserved-instance-for-tenant-a
spec:
  image: ghcr.io/kubewarden/policy-server:v1.3.0
  replicas: 2
  serviceAccountName: ~
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: debug
----

[NOTE]
====

Compruebehttps://github.com/kubewarden/policy-server/pkgs/container/policy-server[última versión publicada de `PolicyServer` ] y cambie la etiqueta para que coincida.

====

Resumen de los atributos del recurso `PolicyServer`:

[cols="^,,"]
|===
| Requerido | Marcador de posición | Descripción

| Y
| `image`
| El nombre de la imagen del contenedor

| Y
| `replicas`
| El número de instancias deseadas

| N
| `serviceAccountName`
| El nombre de la dirección `ServiceAccount` que se utilizará para la implantación de `PolicyServer`. Si no se proporciona ningún valor, se utilizará el valor predeterminado `ServiceAccount` del espacio de nombres de la instalación, `kubewarden-controller`.

| N
| `env`
| La lista de variables de entorno

| N
| `annotations`
| La lista de anotaciones

|===

El cambio de cualquiera de estos atributos provoca una implantación de `PolicyServer` con la nueva configuración.

=== ClusterAdmissionPolicy

El recurso {cluster-admission-policy} es el núcleo de la pila {short-project-name}. Define cómo las políticas evalúan las solicitudes.

La aplicación de políticas es la operación más común que realiza un administrador de Kubernetes. Puede declarar tantas políticas como desee, cada una dirigida a uno o más recursos de Kubernetes (es decir, `pods`, `Custom Resource`y otros). También se especifica el tipo de operaciones que se aplican a los recursos seleccionados. Las operaciones disponibles son `CREATE`, `UPDATE`, `DELETE` y`CONNECT`.

Configuración por defecto {cluster-admission-policy}:

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psp-capabilities
spec:
  policyServer: reserved-instance-for-tenant-a
  module: registry://ghcr.io/kubewarden/policies/psp-capabilities:v0.1.9
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  settings:
    allowed_capabilities:
      - CHOWN
    required_drop_capabilities:
      - NET_ADMIN
----

Resumen de los atributos del recurso {cluster-admission-policy}:

[cols="^,,"]
|===
| Requerido | Marcador de posición | Descripción

| N
| `policy-server`
| Identifica un objeto `PolicyServer` existente. Sólo esta instancia de `PolicyServer` sirve a la política. El servidor de políticas denominado `default` sirve un {cluster-admission-policy} sin un `PolicyServer` explícito.

| Y
| `module`
| La ubicación de la política {short-project-name}. Se permiten los siguientes esquemas:

| N
|
| - `registry`: Descarga de políticas desde un registro de contenedores compatible con OCI https://github.com/opencontainers/artifacts[artefactos]. Ejemplo: `registry://<OCI registry/policy URL>`

| N
|
| - `http`, `https`: Descarga de políticas desde un servidor HTTP(s) normal.
    Ejemplo: `\https://<website/policy URL>`

| N
|
| - `file`: Cargar la política desde un archivo en el sistema de archivos del ordenador.
    Ejemplo: `\file:///<policy WASM binary full path>`

| Y
| `resources`
| Los recursos de Kubernetes evaluados por la política

| Y
| `operations`
| Qué operaciones para los tipos dados previamente deben ser reenviadas a esta política de admisión por el servidor API para su evaluación.

| Y
| `mutating`
| Establezca este valor booleano `true` para las políticas que pueden mutar las solicitudes entrantes

| N
| `settings`
| Un objeto de forma libre que contiene los valores de configuración de la política

| N
| `failurePolicy`
| La acción a tomar si la solicitud evaluada por una política resulta en un error.
  Se permiten las siguientes opciones:

| N
|
| - `Ignore`: ignora un error al llamar al webhook y la petición API continúa.

| N
|
| - `Fail`: un error al llamar al webhook provoca el fallo de la admisión y el rechazo de la solicitud API.
|===

[NOTE]
====

El controlador registra los recursos {cluster-admission-policy} `*` webhook`scope`. Esto significa que los webhooks registrados reenvían todas las solicitudes que coincidan con los datos `resources` y `operations`, ya sean recursos de namespaced o de cluster-wide.

====


=== AdmissionPolicy

{admission-policy} es un recurso que abarca todo el espacio de nombres. La política procesa únicamente las solicitudes dirigidas al espacio de nombres con la dirección {admission-policy} definida.
Aparte de eso, no hay diferencias funcionales entre los recursos de{admission-policy} y {cluster-admission-policy}.

[IMPORTANT]
====

{admission-policy} requiere Kubernetes 1.21.0 o superior. Esto se debe a que{short-project-name} utiliza la etiqueta `kubernetes.io/metadata.name`, introducida en Kubernetes 1.21.0

====

La documentación completa de estos recursos personalizados se encuentra en https://github.com/kubewarden/kubewarden-controller/blob/main/docs/crds/README.asciidoc[docs.crds.dev] o en https://doc.crds.dev/github.com/kubewarden/kubewarden-controller[].

== Ejemplo: Haga cumplir su primera política

Utilizaremos la https://github.com/kubewarden/pod-privileged-policy[`pod-privileged`] política.
Queremos evitar la creación de contenedores privilegiados dentro de nuestro clúster Kubernetes mediante la aplicación de esta política.

Definamos un {cluster-admission-policy} para hacerlo:

[subs="+attributes",console]
----
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.2
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
EOF
----

El resultado es el siguiente:

[subs="+attributes",console]
----
clusteradmissionpolicy.policies.kubewarden.io/privileged-pods created
----

Después de instanciar un {cluster-admission-policy}, el estado pasa a ser `pending`, y fuerza un despliegue del `PolicyServer` objetivo. En el ejemplo, se trata de la dirección `PolicyServer` denominada `default`. Puede supervisar el despliegue ejecutando el siguiente comando:

[subs="+attributes",console]
----
kubectl get clusteradmissionpolicy.policies.kubewarden.io/privileged-pods
----

Debería ver la siguiente salida:

[subs="+attributes",console]
----
NAME              POLICY SERVER   MUTATING   STATUS
privileged-pods   default         false      pending
----

Una vez que la nueva política está lista, `kubewarden-controller`registra un objetohttps://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io[ValidatingWebhookConfiguration]para servirla.

El estado {cluster-admission-policy} se convierte en `active` una vez completada la Implantación para cada instancia `PolicyServer`. Muestra{validating-webhook-configuration}s con el siguiente comando:

[subs="+attributes",console]
----
kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io -l kubewarden
----

Debería ver la siguiente salida:

[subs="+attributes",console]
----
NAME                          WEBHOOKS   AGE
clusterwide-privileged-pods   1          9s
----

Una vez que {cluster-admission-policy} está activo y{validating-webhook-configuration} registrado, puede probar la política.

En primer lugar, puedes crear un Pod con un Contenedor _que no_ esté en modo `privileged`:

[subs="+attributes",console]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: unprivileged-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
EOF
----

El resultado es el siguiente:

[subs="+attributes",console]
----
pod/unprivileged-pod created
----

El Pod se ha creado correctamente.

Ahora, puede crear un Pod con al menos una bandera Container `privileged`:

[subs="+attributes",console]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
          privileged: true
EOF
----

La política deniega la creación del Pod y debería ver el siguiente mensaje:

[subs="+attributes",console]
----
Error from server: error when creating "STDIN": admission webhook "clusterwide-privileged-pods.kubewarden.admission" denied the request: Privileged container is not allowed
----

[NOTE]
====

Ambos ejemplos no definían un `namespace`, lo que significa que el espacio de nombres `default` era el objetivo. Sin embargo, como se puede ver en el segundo ejemplo, la política se sigue aplicando. Como se ha indicado anteriormente, esto se debe a que el ámbito de aplicación abarca todo el clúster y no se dirige a un espacio de nombres específico.

====


== Desinstalar

Puede eliminar los recursos creados al desinstalar las cartas `helm` del siguiente modo:

[subs="+attributes",console]
----
helm uninstall --namespace kubewarden kubewarden-defaults
----

[subs="+attributes",console]
----
helm uninstall --namespace kubewarden kubewarden-controller
----

[subs="+attributes",console]
----
helm uninstall --namespace kubewarden kubewarden-crds
----

Una vez eliminados los gráficos `helm`, elimine el espacio de nombres de Kubernetes utilizado para desplegar la pila {short-project-name}:

[subs="+attributes",console]
----
kubectl delete namespace kubewarden
----

[CAUTION]
====

{short-project-name} contiene un helm pre-delete hook que elimina todos los`PolicyServer`s y `kubewarden-controller`s. A continuación,`kubewarden-controller` borra todos los recursos, por lo que es importante que`kubewarden-controller` se esté ejecutando cuando se ejecute la desinstalación de helm.

====


{short-project-name} borra {validating-webhook-configuration}s y{mutating-webhook-configuration}s. Compruébalo:

[subs="+attributes",console]
----
kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io -l "kubewarden"
----

[subs="+attributes",console]
----
kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io -l "kubewarden"
----

Si estos recursos no se eliminan automáticamente, elimínelos manualmente mediante el siguiente comando:

[subs="+attributes",console]
----
kubectl delete -l "kubewarden" validatingwebhookconfigurations.admissionregistration.k8s.io
----

[subs="+attributes",console]
----
kubectl delete -l "kubewarden" mutatingwebhookconfigurations.admissionregistration.k8s.io
----

== Conclusión

{cluster-admission-policy} es el recurso principal que debe gestionar un operador de clúster. El módulo `kubewarden-controller` se encarga automáticamente de la configuración del resto de recursos necesarios para ejecutar las políticas.

== ¿Y ahora qué?

Ya está listo para desplegar {short-project-name}. Eche un vistazo a las políticas enhttps://artifacthub.io/packages/search?kind=13[artifacthub.io], enhttps://github.com/topics/kubewarden-policy[] GitHub, o reutilice las políticas de Rego existentes como se muestra en los xref:tutorials/writing-policies/rego/01-intro-rego.adoc[siguientes capítulos].

.Lista completa de políticas disponibles en ArtifactHub
[%collapsible,subs="+macros"]
======

++++

<div class="artifacthub-widget-group" data-url="https://artifacthub.io/packages/search?kind=13&sort=relevance&page=1" data-theme="light" data-header="false" data-stars="false" data-color="#fe7c3f" data-responsive="true" data-loading="true"></div>

++++

======
