include::partial$variables.adoc[]
= {project-name} casos prácticos
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Casos prácticos
:sidebar_position: 74
:description: Conozca varios casos de uso de {project-name} en diferentes entornos Kubernetes y personas, incluyendo múltiples escenarios.
:keywords: {project-name}Documentación, casos prácticos, estudios de casos
:doc-persona: kubewarden-todos
:doc-type: explicación
:doc-topic: explicación

Estos son algunos ejemplos de casos xref:/personas.adoc[de] uso de {project-name}.

== Caso A: Como operador de Kubernetes, quiero asegurarme de que mi clúster es seguro y cumple la normativa.

Despliego {project-name} y su configuración por defecto con su gráfico`kubewarden-defaults` Helm, en el espacio de nombres `kubewarden`. Esto despliega un PolicyServer predeterminado y ClusterAdmissionPolicies recomendadas en el espacio de nombres`kubewarden`, únicamente bajo el control del operador de Kubernetes.

Como operador, puedo añadir más PolicyServers bajo un Namespace gestionado (como`kubewarden`) para distribuir la carga y la tolerancia a fallos.

Los operadores pueden desplegar más ClusterAdmissionPolicies y ClusterAdmissionPolicyGroups. Estos comprueban todos los recursos de Kubernetes, para cualquier tipo de operación (GET, CREATE, UPDATE, PATCH, DELETE, PROXY). Esto garantiza que las operaciones en el clúster sean seguras y conformes.

Entre ellas figuran:

* seguridad
* cumplimiento (de las normas del sector o de los reglamentos de la empresa)
* optimización de recursos (mediante políticas mutantes)
* gobernanza de entornos Kubernetes (mediante etiquetas y convenciones de nomenclatura)
* buenas prácticas
* verificación de imágenes

Las expectativas de seguridad cambian con el tiempo. Los despliegues previamente correctos en el clúster pueden dejar de serlo. Sin embargo, {short-project-name} ya ha aceptado esas operaciones en la agrupación. En estas situaciones, el operador puede desplegar la función Audit Scanner, un CronJob que se ejecuta periódicamente y evalúa los recursos existentes en el clúster. Así se comprueba que el clúster es seguro y cumple las normas incluso con el paso del tiempo.

El operador puede configurar las políticas en modo `monitor` en lugar de en modo `protect`, para aprender del estado del clúster sin bloquear las operaciones.

Los operadores pueden recibir información de las políticas y de la pila {short-project-name} consumiendo registros e información de OpenTelemetry para métricas y rastreo.

== Caso B: Como operador de Kubernetes, quiero proporcionar un marco a mis usuarios de Kubernetes para que puedan autogestionar sus Namespaces.

Como operador, despliego {short-project-name} como en el caso A para un conjunto de políticas de mi elección. Esto me proporciona una línea de base segura en el clúster, que otros usuarios no pueden eludir.

Además del caso A, tengo diferentes personas por Namespaces: quizás equipos, administradores de equipos, despliegues de prueba y otros. Permito a cada administrador de Namespace auto-servicio permitiéndole desplegar PolicyServers en su Namespace, junto con AdmissionPolicies y AdmissionPolicyGroups namespaced.
Esta arquitectura les permite controlar su PolicyServer y sus políticas. Las políticas sólo se aplican a su espacio de nombres y limitan el uso de recursos a su espacio de nombres.

También permite al operador segregar a los inquilinos ruidosos, reservando PolicyServers de alto rendimiento para aquellos inquilinos y tareas que necesiten un alto rendimiento y una baja latencia, por ejemplo.

== Caso C: Como autor de políticas, quiero utilizar las herramientas y los lenguajes que conozco para escribir nuevas políticas.

{short-project-name} lo consigue admitiendo cualquier lenguaje que compile con WebAssembly como posible lenguaje de destino para las directivas. Esto significa que los autores de políticas pueden reutilizar sus flujos de trabajo (`git`, CI, editores, revisiones por pares, etc.), y herramientas: lenguajes, bibliotecas de lenguajes, arneses y marcos de pruebas, etc.

Permite reutilizar lenguajes de dominio específico (como Rego, CEL, YAML+macros de Kyverno) o lenguajes de propósito general (como Go, Rust, C#, Javascript, cualquiera que compile con Wasm). {short-project-name} proporcionaxref:/tutorials/writing-policies/index.adoc[SDKs] para algunos lenguajes como soporte de primera clase.

{short-project-name} pueden ser simples o complejas.
Las políticas conscientes del contexto también se utilizan para interactuar con cargas de trabajo independientes (por ejemplo, para obtener información de un servicio de larga duración de escáner de imágenes).

== Caso D: Como integrador de sistemas, quiero reutilizar {short-project-name} como parte de mi solución de seguridad y conformidad.

Como integrador de sistemas, quiero reutilizar {short-project-name}, y posiblemente reutilizar otras soluciones incluyéndolas en {short-project-name}.

Como integrador de sistemas, puedo reutilizar partes de {short-project-name}. Por ejemplo, el`policy-server`, para vigilar los recursos, internos o externos al clúster Kubernetes a través de la función xref:/howtos/raw-policies.adoc["raw policies"].

Los integradores de sistemas pueden optar por implantar `kubewarden-controller` o gestionar los CRD por su cuenta. Pueden elegir desplegar o ampliar el Escáner de Auditoría según sea necesario.

Los integradores de sistemas pueden crear nuevos componentes. Por ejemplo, un escáner de imágenes, e interactuar con él a través de una política consciente del contexto, sin tener una implementación monolítica en un controlador Kubernetes.

== No objetivos

{short-project-name} no tiene intención de hacerlo:

- Sustituye a las funciones de seguridad integradas en Kubernetes, sino que las complementa:
  - {short-project-name} facilita la migración desde los PSP.
  - Puede reutilizar las políticas ValidatingAdmissionPolicies y CEL con {short-project-name}'s `cel-policy`.
  - {short-project-name} las políticas pueden ser mutantes, mientras que Pod Security Admission no.
  - {short-project-name} las políticas se benefician de las funciones de la pila {short-project-name} (escáner de auditoría, telemetría, gestión de CRD).
- Proporcionar seguridad en tiempo de ejecución, como detección de intrusiones o aislamiento de contenedores en tiempo de ejecución.
- Proporcionar protección del sistema host de los clusters.
- Proporcionar una flexibilidad infinita en la ejecución de políticas. Para evitar ataques DoS, se limitan los tiempos de procesamiento de las políticas.