= Variables de entorno
:page-languages: [en, ja, ko, zh]
:revdate: 2024-12-05
:page-revdate: {revdate}

Como se menciona en la xref:quick-start.adoc[Guía de inicio rápido], puede utilizar el script de instalación disponible en https://get.k3s.io para instalar K3s como un servicio en sistemas basados en systemd y openrc.

La forma más sencilla de este comando es la siguiente:

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -
----

Cuando se utiliza este método para instalar K3s, se pueden utilizar las siguientes variables de entorno para configurar la instalación:

|===
| Variable de entorno | Descripción

| `INSTALL_K3S_SKIP_DOWNLOAD`
| Si se establece en true no descargará K3s hash o binario.

| `INSTALL_K3S_SYMLINK`
| Por defecto creará enlaces simbólicos para los binarios kubectl, crictl y ctr si los comandos no existen ya en la ruta. Si se establece en 'skip' no creará enlaces simbólicos y 'force' sobrescribirá.

| `INSTALL_K3S_SKIP_ENABLE`
| Si se establece en true no habilitará o iniciará el servicio K3s.

| `INSTALL_K3S_SKIP_START`
| Si se establece en true no se iniciará el servicio K3s.

| `INSTALL_K3S_VERSION`
| Versión de K3s para descargar de Github. Intentará descargar desde el canal estable si no se especifica.

| `INSTALL_K3S_BIN_DIR`
| Directorio en el que instalar el binario, los enlaces y el script de desinstalación de K3s, o utilizar `/usr/local/bin` por defecto.

| `INSTALL_K3S_BIN_DIR_READ_ONLY`
| Si se establece en true no se escribirán archivos en `INSTALL_K3S_BIN_DIR`, obliga a establecer `INSTALL_K3S_SKIP_DOWNLOAD=true`.

| `INSTALL_K3S_SYSTEMD_DIR`
| Directorio en el que instalar el servicio systemd y los archivos de entorno, o utilizar `/etc/systemd/system` por defecto.

| `INSTALL_K3S_EXEC`
| Comando con banderas a utilizar para lanzar K3s en el servicio. Si no se especifica el comando, y se establece `K3S_URL`, por defecto será "agente". Si `K3S_URL` no está configurado, por defecto será "servidor". Para obtener ayuda, consulte xref:installation/configuration.adoc#_configuration_with_install_script[este ejemplo.]

| `INSTALL_K3S_NAME`
| Nombre del servicio systemd a crear, por defecto será 'k3s' si se ejecuta k3s como servidor y 'k3s-agent' si se ejecuta k3s como agente. Si se especifica, el nombre llevará el prefijo 'k3s-'.

| `INSTALL_K3S_TYPE`
| Tipo de servicio systemd a crear, será el predeterminado del comando exec de K3s si no se especifica.

| `INSTALL_K3S_SELINUX_WARN`
| Si se establece en true continuará si no se encuentra la política k3s-selinux.

| `INSTALL_K3S_SKIP_SELINUX_RPM`
| Si se establece en true omitirá la instalación automática del RPM k3s.

| `INSTALL_K3S_CHANNEL_URL`
| URL del canal para obtener la URL de descarga de K3s. Por defecto https://update.k3s.io/v1-release/channels.

| `INSTALL_K3S_CHANNEL`
| Canal que se utilizará para obtener la URL de descarga de K3. Por defecto es "estable". Las opciones son: `stable`, `latest`, `testing`.
|===

Este ejemplo muestra dónde colocar las variables de entorno mencionadas como opciones (después de la tubería):

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL=latest sh -
----

Las variables de entorno que empiecen por `K3S_` se conservarán para que las utilicen los servicios systemd y openrc.

Si se establece `K3S_URL` sin establecer explícitamente un comando exec, el comando por defecto será "agente".

Al ejecutar el agente, también debe configurarse `K3S_TOKEN`.

[NOTE]
.Versión Puerta
====
Versiones disponibles a partir de octubre de 2024: v1.28.15+k3s1, v1.29.10+k3s1, v1.30.6+k3s1, v1.31.2+k3s1.
====

K3s utilizará ahora `PATH` para encontrar tiempos de ejecución de contenedores alternativos, además de comprobar las rutas por defecto utilizadas por los paquetes de tiempos de ejecución de contenedores. Para utilizar esta función, debe modificar la variable de entorno PATH del servicio K3s para añadir los directorios que contienen los binarios de ejecución del contenedor.

Se recomienda modificar uno de estos dos archivos de entorno:

* /etc/default/k3s # o k3s-agent
* /etc/sysconfig/k3s # o k3s-agent

Este ejemplo añadirá la dirección `PATH` en `/etc/default/k3s`:

[,bash]
----
echo PATH=$PATH >> /etc/default/k3s
----

[WARNING]
====
`PATH` los cambios deben hacerse con cuidado para evitar colocar binarios que no sean de confianza en la ruta de los servicios que se ejecutan como root.
====
