= Bandera Deprecation
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-09
:page-revdate: {revdate}

K3s es un proyecto que evoluciona rápidamente, y como tal, necesitamos una forma de eliminar las banderas y las opciones de configuración. En esta página se describe el proceso de eliminación de las opciones de configuración y las banderas obsoletas. Para garantizar que los usuarios no se vean sorprendidos por la eliminación de las banderas, el proceso es similar al de https://kubernetes.io/docs/reference/using-api/deprecation-policy/[Deprecation Policy] Kubernetes.

== Proceso

. Los indicadores pueden declararse como "To Be Deprecated" en cualquier momento.
. Las banderas que sean "To Be Deprecated" deben ser etiquetadas como tales en el próximo parche de todas las versiones actualmente soportadas. Además, la bandera empezará a avisar a los usuarios de que va a quedar obsoleta en la próxima versión menor.
. En la próxima versión menor, una bandera se marcará como obsoleta en la documentación y se convertirá en una bandera oculta en el código. La bandera seguirá funcionando y dando avisos a los usuarios.
. En la siguiente rama de versiones menores, las opciones obsoletas pasarán a ser "no operativas", provocando un error fatal si se utilizan. Este error debe explicar al usuario cualquier nueva bandera o configuración que sustituya a esta bandera.
. En la próxima versión menor, los indicadores no operativos se eliminarán de la documentación y del código.

== Ejemplo

Un ejemplo del proceso:

* `--foo` existe en las versiones v1.22.14, v1.23.10 y v1.24.2.
* Tras la versión v1.24.2, se ha decidido dejar de utilizar `--foo` en favor de `--new-foo`.
* En las versiones v1.22.15, v1.23.11 y v1.24.3, `--foo` sigue existiendo, pero advertirá a los usuarios:
+
----
[Warning] --foo will be deprecated in v1.25.0, use `--new-foo` instead
----
+
`--foo` seguirá existiendo como indicador operativo durante la vida de las versiones v1.22, v1.23 y v1.24.

* En la versión 1.25.0, `--foo` se marca como obsoleto en la documentación y se ocultará en el código. Seguirá funcionando y avisará a los usuarios para que pasen a `--new-foo`.
* En la versión 1.26.0, `--foo` provocará un error fatal si se utiliza. El mensaje de error dirá:
+
----
[Fatal] exit 1: --foo is no longer supported, use --new-foo instead
----

* En la versión 1.27.0, `--foo` se eliminará por completo de todo el código y la documentación.
