// This file was converted from Markdown to AsciiDoc.

include::partial$variables.adoc[]
= kwctl CLI
:revdate: 2026-03-18
:page-revdate: {revdate}
:title: kwctl CLI
:description: Erforschen Sie das \`+kwctl+` Kommandozeilenwerkzeug zur Verwaltung von {project-name} Richtlinien und zur DurchfГјhrung von Aufgaben wie das Laden von Richtlinien.
:keywords: CLI, Referenz, kwctl
:doc-persona: kubewarden-operator
:doc-type: Referenz
:doc-topic: Betriebsanleitung

== Kommandozeilenhilfe fГјr `+kwctl+`

Dieses Dokument enthГӨlt den Hilfetext fГјr das `+kwctl+` Kommandozeilenwerkzeug.

*Гңberblick Гјber den Befehl:*

* <<kwctl,`+kwctl+`>>
* <<kwctl-annotate,`+kwctl annotate+`>>
* <<kwctl-bench,`+kwctl bench+`>>
* <<kwctl-completions,`+kwctl completions+`>>
* <<kwctl-digest,`+kwctl digest+`>>
* <<kwctl-docs,`+kwctl docs+`>>
* <<kwctl-info,`+kwctl info+`>>
* <<kwctl-inspect,`+kwctl inspect+`>>
* <<kwctl-load,`+kwctl load+`>>
* <<kwctl-policies,`+kwctl policies+`>>
* <<kwctl-pull,`+kwctl pull+`>>
* <<kwctl-push,`+kwctl push+`>>
* <<kwctl-rm,`+kwctl rm+`>>
* <<kwctl-run,`+kwctl run+`>>
* <<kwctl-save,`+kwctl save+`>>
* <<kwctl-scaffold,`+kwctl scaffold+`>>
* <<kwctl-scaffold-admission-request,`+kwctl scaffold admission-request+`>>
* <<kwctl-scaffold-artifacthub,`+kwctl scaffold artifacthub+`>>
* <<kwctl-scaffold-manifest,`+kwctl scaffold manifest+`>>
* <<kwctl-scaffold-vap,`+kwctl scaffold vap+`>>
* <<kwctl-scaffold-verification-config,`+kwctl scaffold verification-config+`>>
* <<kwctl-verify,`+kwctl verify+`>>

[[kwctl]]
=== `+kwctl+`

Werkzeug zur Verwaltung von {project-name} Richtlinien

*Verwendung:* `+kwctl [OPTIONS] <COMMAND>+`

==== Unterbefehle

* `+annotate+` вҖ” FГјgt {short-project-name} Metadaten zu einem WebAssembly-Modul hinzu
* `+bench+` вҖ” FГјhrt Benchmarktests an einer {short-project-name} Richtlinie durch
* `+completions+` вҖ” Generiert Shell-VervollstГӨndigungen
* `+digest+` вҖ” Ruft den Digest aus dem OCI-Manifest einer Richtlinie ab
* `+docs+` вҖ” Generiert die Markdown-Dokumentation fГјr kwctl-Befehle
* `+info+` вҖ” Zeigt Systeminformationen an
* `+inspect+` вҖ” Untersucht die {short-project-name} Richtlinie
* `+load+` вҖ” LГӨdt Richtlinien aus einer tar.gz-Datei
* `+policies+` вҖ” Listet alle heruntergeladenen Richtlinien auf
* `+pull+` вҖ” Holt eine {short-project-name} Richtlinie von einer angegebenen URI
* `+push+` вҖ” Schiebt eine {short-project-name} Richtlinie in ein OCI-Registry
* `+rm+` вҖ” Entfernt eine {short-project-name} Richtlinie aus dem Speicher
* `+run+` вҖ” FГјhrt eine {short-project-name} Richtlinie von einer gegebenen URI aus
* `+save+` вҖ” Speichert Richtlinien in einer tar.gz-Datei
* `+scaffold+` вҖ” Erstellt eine Kubernetes-Ressource oder Konfigurationsdatei
* `+verify+` вҖ” ГңberprГјft eine {short-project-name} Richtlinie von einer gegebenen URI mit Sigstore

==== Optionen

* `+-v+`, `+--verbose <VERBOSE>+` вҖ” ErhГ¶ht die AusfГјhrlichkeit
* `+--no-color <NO-COLOR>+` вҖ” Deaktiviert die farbige Ausgabe

[[kwctl-annotate]]
=== `+kwctl annotate+`

FГјgen Sie {short-project-name} Metadaten zu einem WebAssembly-Modul hinzu

*Verwendung:* `+kwctl annotate [OPTIONS] --metadata-path <PATH> --output-path <PATH> <wasm-path>+`

==== Argumente

* `+<WASM-PATH>+` вҖ” Pfad zum zu annotierenden WebAssembly-Modul

==== Optionen

* `+-m+`, `+--metadata-path <PATH>+` вҖ” Datei, die die Metadaten enthГӨlt
* `+-o+`, `+--output-path <PATH>+` вҖ” Ausgabedatei
* `+-u+`, `+--usage-path <PATH>+` вҖ” Datei, die die Nutzungsinformationen der Richtlinie enthГӨlt

[[kwctl-bench]]
=== `+kwctl bench+`

FГјhrt Benchmarktests an einer {short-project-name} Richtlinie durch.

Die Richtlinie kann auf folgende Weise angegeben werden:
- URI: z.B. `+registry://ghcr.io/kubewarden/policies/psp-policy:latest+` oder `+\https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm+`
- SHA-PrГӨfix: z.B. `+c3b80a10f9c3+` (erfordert, dass die Richtlinie bereits abgerufen wurde)
- Lokale WASM-Datei: z.B. `+file://home/tux/new-policy/psp-policy.wasm+`
- Lokale YAML-Datei: z.B. `+file://home/tux/cluster-admission-policy.yaml+` (enthГӨlt Deklarationen von {short-project-name} benutzerdefinierten Ressourcen wie `+ClusterAdmissionPolicy+`, `+AdmissionPolicy+` usw.)

Standardverhalten:
Wenn das Schema weggelassen wird, wird `+file://+` angenommen, das im aktuellen Verzeichnis verwurzelt ist.

Hinweise zu {short-project-name} benutzerdefinierten Ressourcen:
- Flags `+--request-path+`, `+--settings-path+` und `+--settings-json+` werden ignoriert; Einstellungen werden aus der Definition der benutzerdefinierten Ressource gelesen.
- Das `+--execution-mode+` Flag gilt fГјr alle Richtlinien in der YAML-Datei.
- Das `+--raw+` Flag kann nicht verwendet werden, da die benutzerdefinierten Ressourcen von {short-project-name} `+raw+` Richtlinien nicht unterstГјtzen.

Nur die folgenden Attribute der Definition der benutzerdefinierten Ressource (CRD) werden bewertet: +
- Richtlinienmodul +
- Richtlinieneinstellungen +
- KontextabhГӨngige Ressourcen, auf die die Richtlinie zugreifen kann

Andere Felder, wie `+rules+`, `+matchConditions+`, `+objectSelector+` und `+namespaceSelector+`, werden ignoriert.

Eine YAML-Datei kann mehrere Deklarationen von benutzerdefinierten Ressourcen enthalten. In diesem Fall bewertet `+kwctl+` jede Richtlinie in der Datei mit derselben Anfrage wГӨhrend jeder Bewertung.

*Verwendung:* `+kwctl bench [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>+`

==== Argumente

* `+<URI_OR_SHA_PREFIX_OR_YAML_FILE>+` вҖ” Richtlinien-URI, SHA-PrГӨfix oder YAML-Datei, die {short-project-name} Richtlinienressourcen enthГӨlt. UnterstГјtzte Schemas: registry://, https://, file://. Wenn das Schema weggelassen wird, wird file:// angenommen, basierend auf dem aktuellen Verzeichnis.

==== Optionen

* `+--allow-context-aware <ALLOW-CONTEXT-AWARE>+` вҖ” GewГӨhrt Zugriff auf die Kubernetes-Ressourcen, die im `+contextAwareResources+` Abschnitt der Richtlinie definiert sind. Warnung: ГңberprГјfen Sie die Liste der Ressourcen sorgfГӨltig, um Missbrauch zu vermeiden. StandardmГӨГҹig deaktiviert
* `+--cert-email <VALUE>+` вҖ” Erwartete E-Mail im Fulcio-Zertifikat
* `+--cert-oidc-issuer <VALUE>+` вҖ” Erwarteter OIDC-Issuer in Fulcio-Zertifikaten
* `+--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>+` вҖ” Deaktiviert die Nutzung des wasmtime-Caches
* `+--docker-config-json-path <PATH>+` вҖ” Pfad zu einem Verzeichnis, das die Docker 'config.json'-Datei enthГӨlt. Kann verwendet werden, um Authentifizierungsdetails fГјr die Registry anzugeben
* `+--dump-results-to-disk <DUMP_RESULTS_TO_DISK>+` вҖ” Legt Ergebnisse in target/tiny-bench/label/.. ab, wenn das Ziel gefunden werden kann. Wird verwendet, um vorherige DurchlГӨufe zu vergleichen
* `+-e+`, `+--execution-mode <MODE>+` вҖ” Die Laufzeit, die verwendet werden soll, um diese Richtlinie auszufГјhren +
  MГ¶gliche Werte: `+opa+`, `+gatekeeper+`, `+kubewarden+`, `+wasi+`
* `+--github-owner <VALUE>+` вҖ” Erwarteter GitHub-Besitzer in den in CD-Pipelines generierten Zertifikaten
* `+--github-repo <VALUE>+` вҖ” Erwartetes GitHub-Repository in den in CD-Pipelines generierten Zertifikaten
* `+--measurement-time <SECONDS>+` вҖ” Wie lange der Benchmark 'laufen sollte', num_samples hat Vorrang, sodass das Benchmarking lГӨnger dauert, um num_samples zu sammeln, wenn der zu benchmarkende Code langsamer ist als dieses zulГӨssige Zeitlimit
* `+--num-resamples <NUM>+` вҖ” Wie viele Resamples durchgefГјhrt werden sollen
* `+--num-samples <NUM>+` вҖ” Wie viele Resamples durchgefГјhrt werden sollen. Empfohlen mindestens 50, Гјber 100 scheint kein signifikant anderes Ergebnis zu liefern.
* `+--raw <RAW>+` вҖ” Validiere eine rohe Anfrage +
  Standardwert: `+false+`
* `+--record-host-capabilities-interactions <FILE>+` вҖ” Protokolliere alle Richtlinien- und HostfГӨhigkeiten-Kommunikationen in die angegebene Datei. NГјtzlich, um spГӨter mit dem Flag '--replay-host-capabilities-interactions' kombiniert zu werden
* `+--replay-host-capabilities-interactions <FILE>+` вҖ” WГӨhrend des Austauschs von Richtlinien und HostfГӨhigkeiten gibt der Host die Antworten zurГјck, die in der bereitgestellten Datei gefunden wurden. Dies ist nГјtzlich, um Richtlinien auf reproduzierbare Weise zu testen, da keine externen Interaktionen mit OCI-Registrierungen, DNS, Kubernetes durchgefГјhrt werden.
* `+-r+`, `+--request-path <PATH>+` вҖ” Datei, die das Kubernetes-Zulassungsanfrageobjekt im JSON-Format enthГӨlt
* `+--settings-json <VALUE>+` вҖ” JSON-Zeichenfolge, die die Einstellungen fГјr diese Richtlinie enthГӨlt
* `+-s+`, `+--settings-path <PATH>+` вҖ” Datei, die die Einstellungen fГјr diese Richtlinie enthГӨlt
* `+--sigstore-trust-config <PATH>+` вҖ” JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschlieГҹlich der URIs, die zum Zugriff auf die CA und die Dienste fГјr die Transparenz von Artefakten verwendet werden, sowie des kryptografischen Vertrauensankers selbst.
* `+--sources-path <PATH>+` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Registrierungs-Hosts, benutzerdefinierte CAs...)
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` вҖ” Annotation im key=value-Format. Kann mehrfach wiederholt werden
* `+--verification-config-path <PATH>+` вҖ” YAML-Datei, die Informationen zur Verifizierungskonfiguration enthГӨlt (Signaturen, Г¶ffentliche SchlГјssel...)
* `+-k+`, `+--verification-key <PATH>+` вҖ” Pfad zum SchlГјssel, der zur ГңberprГјfung der Richtlinie verwendet wird. Kann mehrfach wiederholt werden
* `+--warm-up-time <SECONDS>+` вҖ” Wie lange die Benchmarks aufwГӨrmen sollen

[[kwctl-completions]]
=== `+kwctl completions+`

Generiere Shell-VervollstГӨndigungen

*Verwendung:* `+kwctl completions --shell <VALUE>+`

==== Optionen

* `+-s+`, `+--shell <VALUE>+` вҖ” Shell-Typ +
  MГ¶gliche Werte: `+bash+`, `+elvish+`, `+fish+`, `+powershell+`, `+zsh+`

[[kwctl-digest]]
=== `+kwctl digest+`

Ruft den Digest aus dem OCI-Manifest einer Richtlinie ab

*Verwendung:* `+kwctl digest [OPTIONS] <uri>+`

==== Argumente

* `+<URI>+` вҖ” Richtlinien-URI

==== Optionen

* `+--docker-config-json-path <PATH>+` вҖ” Pfad zu einem Verzeichnis, das die Docker 'config.json'-Datei enthГӨlt. Kann verwendet werden, um Authentifizierungsdetails fГјr die Registry anzugeben
* `+--sources-path <PATH>+` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Registrierungs-Hosts, benutzerdefinierte CAs...)

[[kwctl-docs]]
=== `+kwctl docs+`

Generiert die Markdown-Dokumentation fГјr kwctl-Befehle

*Verwendung:* `+kwctl docs --output <FILE>+`

==== Optionen

* `+-o+`, `+--output <FILE>+` вҖ” Pfad, wo die Dokumentationsdatei gespeichert wird

[[kwctl-info]]
=== `+kwctl info+`

Zeige Systeminformationen an

*Verwendung:* `+kwctl info+`

[[kwctl-inspect]]
=== `+kwctl inspect+`

Untersuche die {short-project-name} Richtlinie

*Verwendung:* `+kwctl inspect [OPTIONS] <uri_or_sha_prefix>+`

==== Argumente

* `+<URI_OR_SHA_PREFIX>+` вҖ” Richtlinien-URI oder SHA-PrГӨfix. UnterstГјtzte Schemes: registry://, https://, file://. Wenn das Schema weggelassen wird, wird file:// angenommen, basierend auf dem aktuellen Verzeichnis.

==== Optionen

* `+--docker-config-json-path <PATH>+` вҖ” Pfad zu einem Verzeichnis, das die Docker 'config.json'-Datei enthГӨlt. Kann verwendet werden, um Authentifizierungsdetails fГјr die Registry anzugeben
* `+-o+`, `+--output <FORMAT>+` вҖ” Ausgabeformat +
  MГ¶gliche Werte: `+yaml+`
* `+--show-signatures <SHOW-SIGNATURES>+` вҖ” Zeige Sigstore-Signaturen an
* `+--sources-path <PATH>+` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Registrierungs-Hosts, benutzerdefinierte CAs...)

[[kwctl-load]]
=== `+kwctl load+`

LГӨdt Richtlinien aus einer tar.gz-Datei

*Verwendung:* `+kwctl load --input <input>+`

==== Optionen

* `+--input <INPUT>+` вҖ” LГӨdt Richtlinien aus dem Tarball

[[kwctl-policies]]
=== `+kwctl policies+`

Listet alle heruntergeladenen Richtlinien auf

*Verwendung:* `+kwctl policies+`

[[kwctl-pull]]
=== `+kwctl pull+`

Holt eine {short-project-name} Richtlinie von einer gegebenen URI

*Verwendung:* `+kwctl pull [OPTIONS] <uri>+`

==== Argumente

* `+<URI>+` вҖ” Richtlinien-URI. UnterstГјtzte Schemes: registry://, https://, file://

==== Optionen

* `+--cert-email <VALUE>+` вҖ” Erwartete E-Mail im Fulcio-Zertifikat
* `+--cert-oidc-issuer <VALUE>+` вҖ” Erwarteter OIDC-Issuer in Fulcio-Zertifikaten
* `+--docker-config-json-path <DOCKER_CONFIG>+` вҖ” Pfad zu einem Verzeichnis, das die Docker 'config.json'-Datei enthГӨlt. Kann verwendet werden, um Authentifizierungsdetails fГјr das Registry anzugeben.
* `+--github-owner <VALUE>+` вҖ” Erwarteter GitHub-Besitzer in den in CD-Pipelines generierten Zertifikaten
* `+--github-repo <VALUE>+` вҖ” Erwartetes GitHub-Repository in den in CD-Pipelines generierten Zertifikaten
* `+-o+`, `+--output-path <PATH>+` вҖ” Ausgabedatei. Wenn nicht angegeben, wird sie im {short-project-name} Store heruntergeladen
* `+--sigstore-trust-config <PATH>+` вҖ” JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschlieГҹlich der URIs, die zum Zugriff auf die CA und die Dienste fГјr die Transparenz von Artefakten verwendet werden, sowie des kryptografischen Vertrauensankers selbst.
* `+--sources-path <PATH>+` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Registrierungs-Hosts, benutzerdefinierte CAs...)
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` вҖ” Annotation im key=value-Format. Kann mehrfach wiederholt werden
* `+--verification-config-path <PATH>+` вҖ” YAML-Datei, die Informationen zur Verifizierungskonfiguration enthГӨlt (Signaturen, Г¶ffentliche SchlГјssel...)
* `+-k+`, `+--verification-key <PATH>+` вҖ” Pfad zum SchlГјssel, der zur ГңberprГјfung der Richtlinie verwendet wird. Kann mehrfach wiederholt werden

[[kwctl-push]]
=== `+kwctl push+`

ГңbertrГӨgt eine {short-project-name} Richtlinie an das OCI-Registry

*Verwendung:* `+kwctl push [OPTIONS] <policy> <uri>+`

Die in den Metadaten der Richtlinie gefundenen Annotationen werden Teil des OCI-Manifests sein.
Die mehrzeiligen Annotationen werden Гјbersprungen, da sie nicht mit der OCI-Spezifikation kompatibel sind.
Die Annotation 'io.kubewarden.policy.source' wird als 'org.opencontainers.image.source' propagiert, um Tools wie renovatebot zu ermГ¶glichen, Richtlinienaktualisierungen zu erkennen.

==== Argumente

* `+<POLICY>+` вҖ” Richtlinie zum Pushen. Kann der Pfad zu einer lokalen Datei, eine Richtlinie-URI oder das SHA-PrГӨfix einer Richtlinie im Store sein.
* `+<URI>+` вҖ” Richtlinie-URI. UnterstГјtzte Schemes: registry://

==== Optionen

* `+--docker-config-json-path <PATH>+` вҖ” Pfad zu einem Verzeichnis, das die Docker 'config.json'-Datei enthГӨlt. Kann verwendet werden, um Authentifizierungsdetails fГјr das Registry anzugeben
* `+-f+`, `+--force <FORCE>+` вҖ” Auch eine nicht annotierte Richtlinie pushen
* `+-o+`, `+--output <PATH>+` вҖ” Ausgabeformat +
  Standardwert: `+text+` +
  MГ¶gliche Werte: `+text+`, `+json+`
* `+--sources-path <PATH>+` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Registrierungs-Hosts, benutzerdefinierte CAs...)

[[kwctl-rm]]
=== `+kwctl rm+`

Entfernt eine {short-project-name} Richtlinie aus dem Store

*Verwendung:* `+kwctl rm <uri_or_sha_prefix>+`

==== Argumente

* `+<URI_OR_SHA_PREFIX>+` вҖ” Richtlinie-URI oder SHA-PrГӨfix.

[[kwctl-run]]
=== `+kwctl run+`

FГјhren Sie eine oder mehrere {short-project-name} Richtlinien lokal aus.

Die Richtlinie kann auf folgende Weise angegeben werden:
- URI: z.B. `+registry://ghcr.io/kubewarden/policies/psp-policy:latest+` oder `+https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm+`
- SHA-PrГӨfix: z.B. `+c3b80a10f9c3+` (erfordert, dass die Richtlinie bereits abgerufen wurde)
- Lokale WASM-Datei: z.B. `+file://home/tux/new-policy/psp-policy.wasm+`
- Lokale YAML-Datei: z.B. `+file://home/tux/cluster-admission-policy.yaml+` (enthГӨlt Deklarationen von {short-project-name} benutzerdefinierten Ressourcen wie `+ClusterAdmissionPolicy+`, `+AdmissionPolicy+` usw.)

Standardverhalten:
Wenn das Schema weggelassen wird, wird `+file://+` angenommen, das im aktuellen Verzeichnis verwurzelt ist.

Hinweise zu {short-project-name} benutzerdefinierten Ressourcen:
- Flags `+--request-path+`, `+--settings-path+` und `+--settings-json+` werden ignoriert; Einstellungen werden aus der Definition der benutzerdefinierten Ressource gelesen.
- Das `+--execution-mode+` Flag gilt fГјr alle Richtlinien in der YAML-Datei.
- Das `+--raw+` Flag kann nicht verwendet werden, da die benutzerdefinierten Ressourcen von {short-project-name} `+raw+` Richtlinien nicht unterstГјtzen.

Nur die folgenden Attribute der Definition der benutzerdefinierten Ressource (CRD) werden bewertet:
- Richtlinienmodul
- Richtlinieneinstellungen
- KontextabhГӨngige Ressourcen, auf die die Richtlinie zugreifen kann

Andere Felder, wie `+rules+`, `+matchConditions+`, `+objectSelector+` und `+namespaceSelector+`, werden ignoriert.

Eine YAML-Datei kann mehrere Deklarationen von benutzerdefinierten Ressourcen enthalten. In diesem Fall bewertet `+kwctl+` jede Richtlinie in der Datei mit derselben Anfrage wГӨhrend jeder Bewertung.

*Verwendung:* `+kwctl run [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>+`

==== Argumente

* `+<URI_OR_SHA_PREFIX_OR_YAML_FILE>+` вҖ” Policy-URI, SHA-PrГӨfix oder YAML-Datei, die {short-project-name} Richtlinienressourcen enthГӨlt. UnterstГјtzte Schemas: registry://, https://, file://. Wenn das Schema weggelassen wird, wird file:// angenommen, basierend auf dem aktuellen Verzeichnis.

==== Optionen

* `+--allow-context-aware <ALLOW-CONTEXT-AWARE>+` вҖ” GewГӨhrt Zugriff auf die Kubernetes-Ressourcen, die im `+contextAwareResources+` Abschnitt der Richtlinie definiert sind. Warnung: ГңberprГјfen Sie die Liste der Ressourcen sorgfГӨltig, um Missbrauch zu vermeiden. StandardmГӨГҹig deaktiviert
* `+--cert-email <VALUE>+` вҖ” Erwartete E-Mail im Fulcio-Zertifikat
* `+--cert-oidc-issuer <VALUE>+` вҖ” Erwarteter OIDC-Issuer in Fulcio-Zertifikaten
* `+--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>+` вҖ” Deaktiviert die Nutzung des wasmtime-Caches
* `+--docker-config-json-path <PATH>+` вҖ” Pfad zu einem Verzeichnis, das die Docker 'config.json'-Datei enthГӨlt. Kann verwendet werden, um Authentifizierungsdetails fГјr das Registry anzugeben
* `+-e+`, `+--execution-mode <MODE>+` вҖ” Die Laufzeit, die verwendet werden soll, um diese Richtlinie auszufГјhren +
  MГ¶gliche Werte: `+opa+`, `+gatekeeper+`, `+kubewarden+`, `+wasi+`
* `+--github-owner <VALUE>+` вҖ” Erwarteter GitHub-Besitzer in den in CD-Pipelines generierten Zertifikaten
* `+--github-repo <VALUE>+` вҖ” Erwartetes GitHub-Repository in den in CD-Pipelines generierten Zertifikaten
* `+--raw <RAW>+` вҖ” Validiere eine rohe Anfrage +
  Standardwert: `+false+`
* `+--record-host-capabilities-interactions <FILE>+` вҖ” Protokolliere die gesamte Kommunikation der Richtlinien- und HostfГӨhigkeiten in die angegebene Datei. NГјtzlich, um spГӨter mit dem Flag '--replay-host-capabilities-interactions' kombiniert zu werden
* `+--replay-host-capabilities-interactions <FILE>+` вҖ” WГӨhrend des Austauschs von Richtlinien und HostfГӨhigkeiten gibt der Host die Antworten zurГјck, die in der bereitgestellten Datei gefunden wurden. Dies ist nГјtzlich, um Richtlinien auf reproduzierbare Weise zu testen, da keine externen Interaktionen mit OCI-Registries, DNS, Kubernetes durchgefГјhrt werden.
* `+-r+`, `+--request-path <PATH>+` вҖ” Datei, die das Kubernetes-Zulassungsanfrageobjekt im JSON-Format enthГӨlt
* `+--settings-json <VALUE>+` вҖ” JSON-Zeichenfolge, die die Einstellungen fГјr diese Richtlinie enthГӨlt
* `+-s+`, `+--settings-path <PATH>+` вҖ” Datei, die die Einstellungen fГјr diese Richtlinie enthГӨlt
* `+--sigstore-trust-config <PATH>+` вҖ” JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschlieГҹlich der URIs, die zum Zugriff auf die CA und die Dienste fГјr die Transparenz von Artefakten verwendet werden, sowie des kryptografischen Vertrauensankers selbst
* `+--sources-path <PATH>+` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Registrierungs-Hosts, benutzerdefinierte CAs...)
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` вҖ” Annotation im key=value-Format. Kann mehrfach wiederholt werden
* `+--verification-config-path <PATH>+` вҖ” YAML-Datei, die Informationen zur Verifizierungskonfiguration enthГӨlt (Signaturen, Г¶ffentliche SchlГјssel...)
* `+-k+`, `+--verification-key <PATH>+` вҖ” Pfad zum SchlГјssel, der zur ГңberprГјfung der Richtlinie verwendet wird. Kann mehrfach wiederholt werden

[[kwctl-save]]
=== `+kwctl save+`

Richtlinien in eine tar.gz-Datei speichern

*Verwendung:* `+kwctl save --output <FILE> <policies>...+`

==== Argumente

* `+<POLICIES>+` вҖ” Liste der zu speichernden Richtlinien

==== Optionen

* `+-o+`, `+--output <FILE>+` вҖ” Pfad, wo die Datei gespeichert wird

[[kwctl-scaffold]]
=== `+kwctl scaffold+`

Erstellen Sie eine Kubernetes-Ressource oder eine Konfigurationsdatei

*Verwendung:* `+kwctl scaffold <COMMAND>+`

==== Unterbefehle

* `+admission-request+` вҖ” Erstellen Sie ein AdmissionRequest-Objekt
* `+artifacthub+` вҖ” Erstellen Sie eine artifacthub-pkg.yml-Datei aus einer metadata.yml-Datei
* `+manifest+` вҖ” Geben Sie ein Kubernetes-Ressourcenmanifest aus
* `+vap+` вҖ” Konvertieren Sie ein Kubernetes `+ValidatingAdmissionPolicy+` in ein {short-project-name} `+ClusterAdmissionPolicy+`
* `+verification-config+` вҖ” Geben Sie eine Standard-Sigstore-Verifizierungskonfigurationsdatei aus

[[kwctl-scaffold-admission-request]]
=== `+kwctl scaffold admission-request+`

Erstellen Sie ein AdmissionRequest-Objekt

*Verwendung:* `+kwctl scaffold admission-request [OPTIONS] --operation <TYPE>+`

==== Optionen

* `+--object <PATH>+` вҖ” Die Datei, die das neue Objekt enthГӨlt, das zugelassen wird
* `+--old-object <PATH>+` вҖ” Die Datei, die das vorhandene Objekt enthГӨlt
* `+-o+`, `+--operation <TYPE>+` вҖ” {short-project-name} benutzerdefinierter Ressourcentyp +
  MГ¶gliche Werte: `+CREATE+`

[[kwctl-scaffold-artifacthub]]
=== `+kwctl scaffold artifacthub+`

Erstellen Sie eine artifacthub-pkg.yml-Datei aus einer metadata.yml-Datei

*Verwendung:* `+kwctl scaffold artifacthub [OPTIONS]+`

==== Optionen

* `+-m+`, `+--metadata-path <PATH>+` вҖ” Datei, die die Metadaten der Richtlinie enthГӨlt
* `+-o+`, `+--output <FILE>+` вҖ” Pfad, in dem die artifact-pkg.yml-Datei gespeichert wird
* `+-q+`, `+--questions-path <PATH>+` вҖ” Datei, die den Fragen-ui-Inhalt der Richtlinie enthГӨlt
* `+-v+`, `+--version <VALUE>+` вҖ” Semver-Version der Richtlinie

[[kwctl-scaffold-manifest]]
=== `+kwctl scaffold manifest+`

Geben Sie ein Kubernetes-Ressourcenmanifest aus

*Verwendung:* `+kwctl scaffold manifest [OPTIONS] --type <VALUE> <uri_or_sha_prefix>+`

==== Argumente

* `+<URI_OR_SHA_PREFIX>+` вҖ” Richtlinien-URI oder SHA-PrГӨfix. UnterstГјtzte Schemas: registry://, https://, file://. Wenn das Schema weggelassen wird, wird file:// angenommen, basierend auf dem aktuellen Verzeichnis.

==== Optionen

* `+--allow-context-aware <ALLOW-CONTEXT-AWARE>+` вҖ” Verwendet die Metadaten der Richtlinie, um zu definieren, auf welche Kubernetes-Ressourcen die Richtlinie zugreifen kann. Warnung: ГңberprГјfen Sie die Liste der Ressourcen sorgfГӨltig, um Missbrauch zu vermeiden. StandardmГӨГҹig deaktiviert
* `+--cert-email <VALUE>+` вҖ” Erwartete E-Mail im Fulcio-Zertifikat
* `+--cert-oidc-issuer <VALUE>+` вҖ” Erwarteter OIDC-Issuer in Fulcio-Zertifikaten
* `+--docker-config-json-path <DOCKER_CONFIG>+` вҖ” Pfad zu einem Verzeichnis, das die Docker 'config.json'-Datei enthГӨlt. Kann verwendet werden, um Authentifizierungsdetails fГјr das Registry anzugeben
* `+--fulcio-cert-path <PATH>+` вҖ” Pfad zum Fulcio-Zertifikat. Kann mehrfach wiederholt werden
* `+--github-owner <VALUE>+` вҖ” Erwarteter GitHub-Besitzer in den in CD-Pipelines generierten Zertifikaten
* `+--github-repo <VALUE>+` вҖ” Erwartetes GitHub-Repository in den in CD-Pipelines generierten Zertifikaten
* `+--rekor-public-key-path <PATH>+` вҖ” Pfad zum Rekor-Г¶ffentlichen SchlГјssel. Kann mehrfach wiederholt werden
* `+--settings-json <VALUE>+` вҖ” JSON-Zeichenfolge, die die Einstellungen fГјr diese Richtlinie enthГӨlt
* `+-s+`, `+--settings-path <PATH>+` вҖ” Datei, die die Einstellungen fГјr diese Richtlinie enthГӨlt
* `+--sigstore-trust-config <PATH>+` вҖ” JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschlieГҹlich der URIs, die zum Zugriff auf die CA und die Dienste fГјr die Transparenz von Artefakten verwendet werden, sowie des kryptografischen Vertrauensankers selbst
* `+--sources-path <PATH>+` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Registrierungs-Hosts, benutzerdefinierte CAs...)
* `+--title <VALUE>+` вҖ” Titel der Richtlinie
* `+-t+`, `+--type <VALUE>+` вҖ” {short-project-name} benutzerdefinierter Ressourcentyp +
  MГ¶gliche Werte: `+ClusterAdmissionPolicy+`, `+AdmissionPolicy+`
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` вҖ” Annotation im key=value-Format. Kann mehrfach wiederholt werden
* `+--verification-config-path <PATH>+` вҖ” YAML-Datei, die Informationen zur Verifizierungskonfiguration enthГӨlt (Signaturen, Г¶ffentliche SchlГјssel...)
* `+-k+`, `+--verification-key <PATH>+` вҖ” Pfad zum SchlГјssel, der zur ГңberprГјfung der Richtlinie verwendet wird. Kann mehrfach wiederholt werden

[[kwctl-scaffold-vap]]
=== `+kwctl scaffold vap+`

Konvertieren Sie ein Kubernetes `+ValidatingAdmissionPolicy+` in ein {short-project-name} `+ClusterAdmissionPolicy+`

*Verwendung:* `+kwctl scaffold vap [OPTIONS] --binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml> --policy <VALIDATING-ADMISSION-POLICY.yaml>+`

==== Optionen

* `+-b+`, `+--binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml>+` вҖ” Die Datei, die die Definition der ValidatingAdmissionPolicyBinding enthГӨlt
* `+--cel-policy <URI>+` вҖ” Das CEL-Richtlinienmodul, das verwendet werden soll +
  Standardwert: `+ghcr.io/kubewarden/policies/cel-policy:latest+`
* `+-p+`, `+--policy <VALIDATING-ADMISSION-POLICY.yaml>+` вҖ” Die Datei, die die Definition der ValidatingAdmissionPolicy enthГӨlt

[[kwctl-scaffold-verification-config]]
=== `+kwctl scaffold verification-config+`

Geben Sie eine Standardkonfigurationsdatei zur ГңberprГјfung von Sigstore aus

*Verwendung:* `+kwctl scaffold verification-config+`

[[kwctl-verify]]
=== `+kwctl verify+`

ГңberprГјfen Sie eine {short-project-name} Richtlinie von einer gegebenen URI unter Verwendung von Sigstore

*Verwendung:* `+kwctl verify [OPTIONS] <uri>+`

==== Argumente

* `+<URI>+` вҖ” Richtlinien-URI. UnterstГјtzte Schemes: registry://

==== Optionen

* `+--cert-email <VALUE>+` вҖ” Erwartete E-Mail im Fulcio-Zertifikat
* `+--cert-oidc-issuer <VALUE>+` вҖ” Erwarteter OIDC-Issuer in Fulcio-Zertifikaten
* `+--docker-config-json-path <PATH>+` вҖ” Pfad zu einem Verzeichnis, das die Docker 'config.json'-Datei enthГӨlt. Kann verwendet werden, um Authentifizierungsdetails fГјr die Registry anzugeben
* `+--github-owner <VALUE>+` вҖ” Erwarteter GitHub-Besitzer in den in CD-Pipelines generierten Zertifikaten
* `+--github-repo <VALUE>+` вҖ” Erwartetes GitHub-Repository in den in CD-Pipelines generierten Zertifikaten
* `+--sigstore-trust-config <PATH>+` вҖ” JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschlieГҹlich der URIs, die zum Zugriff auf die CA und die Dienste fГјr die Transparenz von Artefakten verwendet werden, sowie des kryptografischen Vertrauensankers selbst
* `+--sources-path <PATH>+` вҖ” YAML-Datei, die Quellinformationen enthГӨlt (https, unsichere Registrierungs-Hosts, benutzerdefinierte CAs...)
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` вҖ” Annotation im key=value-Format. Kann mehrfach wiederholt werden
* `+--verification-config-path <PATH>+` вҖ” YAML-Datei, die Informationen zur Verifizierungskonfiguration enthГӨlt (Signaturen, Г¶ffentliche SchlГјssel...)
* `+-k+`, `+--verification-key <PATH>+` вҖ” Pfad zum SchlГјssel, der zur ГңberprГјfung der Richtlinie verwendet wird. Kann mehrfach wiederholt werden

'''

Dieses Dokument wurde automatisch von https://crates.io/crates/clap-markdown[`+clap-markdown+`] generiert.
