include::partial$variables.adoc[]
:description: Konfigurieren Sie Verifizierungskonfigurationsformate für die sichere Signierung von Container-Images unter Verwendung eines Policy-Servers oder einer Policy zur Verifizierung der Herkunft und der Signaturen.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "verification-config"]
:doc-type: ["reference"]
:doctype: book
:keywords: ["kubewarden", "kubernetes", "verification configuration"]
:current-version: {page-origin-branch}

= Format der Überprüfungskonfiguration
:revdate: 2026-03-18
:page-revdate: {revdate}

== Einführung

Sie können das Format `+verification-config+` mit verwenden:

* `+policy-server+` zur Überprüfung der Herkunft von Richtlinienmodulen
* `+verify-image-signatures+` Richtlinie zur Überprüfung der Herkunft von Cluster-Bildern

Weitere Informationen finden Sie unter xref:/howtos/security-hardening/secure-supply-chain.adoc[Sichere Lieferkette].

== Format

Die Konfiguration hat 2 Stammschlüssel:

* `+allOf+`: Sie sollten alle hier aufgelisteten Überprüfungsinformationen erfüllen, um Container-Images als signiert zu verifizieren.
* `+anyOf+`: Sie müssen mindestens `+anyOf.minimumMatches+` aller aufgelisteten Überprüfungsinformationen erfüllen, um ein Container-Image als signiert zu akzeptieren.

Diese beiden Stammschlüssel akzeptieren ein Array von Schlüsseln des Typs `+kind+`. Nachstehend finden Sie eine vollständige Liste der akzeptierten Schlüssel für die verschiedenen Anwendungsfälle:

* `+pubKey+`: Für Signaturen, die mit herkömmlicher Kryptographie mit öffentlichem/privatem Schlüssel durchgeführt werden.
* `+githubAction+`: Für Signaturen, die mit dem schlüssellosen Workflow von Sigstore innerhalb von GitHub Actions durchgeführt werden, prüft {short-project-name} diese Informationen mit der x509-Zertifikatserweiterung `+workflow_repository+`, die von OpenID Connect von GitHub erstellt wurde, und nicht nur mit `+issuer+` und `+subject+`. Sie sollten diese `+kind+`verwenden, wenn Sie mit GitHub-Aktionen arbeiten.
* `+genericIssuer+`: Für Signaturen, die mit dem schlüssellosen Workflow von Sigstore durchgeführt werden, bei dem der Benutzer das Zertifikat `+issuer+` und `+subject+` selbst validieren muss. Es akzeptiert eine `+subject+`, die sein kann:

** `+equal+`: Der hier übergebene Wert muss genau mit dem `+subject+` im Signierzertifikat übereinstimmen.
** `+urlPrefix+`: Der hier übergebene Wert wird mit `+/+` nachfixiert, um Tippfehler zu vermeiden, und muss ein Präfix des `+subject+` im Signierzertifikat sein.

Der Schlüssel `+kind+` akzeptiert einen optionalen Schlüssel `+annotations+` mit einer Liste von Schlüsselwerten, die in der Signatur enthalten sein müssen.

== Beispiel

Dies ist ein Beispiel für eine Konfiguration zur Prüfung von Signaturen mit Hilfe des Sigstore-Workflows:

[subs="+attributes",yaml]
----
---
apiVersion: v1

allOf:
  - kind: githubAction
    owner: kubewarden   # mandatory
    repo: policy-server # optional
    annotations:  # optional
      env: prod

anyOf: # at least `+anyOf.minimumMatches+` are required to match
  minimumMatches: 2 # default is 1
  signatures:
  - kind: pubKey
    owner: alice # optional
    key: | # mandatory
         -----BEGIN PUBLIC KEY-----
         MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQiTy5S+2JFvVlhUwWPLziM7iTM2j
         byLgh2IjpNQN0Uio/9pZOTP/CsJmXoUNshfpTUHd3OxgHgz/6adtf2nBwQ==
         -----END PUBLIC KEY-----
    annotations:  # optional
      env: prod
  - kind: genericIssuer
    issuer: https://github.com/login/oauth
    subject:
      equal: alice@example.com
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      equal: https://github.com/bob/app-example/.github/workflows/release.yml@refs/heads/main
    annotations:  # optional
      env: prod
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/bob # <- it will be post-fixed with `+/+` for security reasons
----

== Referenz der Signaturkonfiguration

Sie können die in einer Datei enthaltenen Signaturanforderungen validieren. Erweitern Sie um ein Beispiel:

.Eine Datei mit Unterschriftsanforderungen
[%collapsible]
====
[subs="+attributes",yaml]
----
apiVersion: v1

allOf:
  - kind: githubAction
    owner: kubewarden   # mandatory
    annotations:
      env: prod

anyOf: # at least `+anyOf.minimumMatches+` are required to match
  minimumMatches: 2 # default is 1
  signatures:
  - kind: pubKey
    owner: flavio # optional
    key: .... # mandatory
    annotations:  # optional
      env: prod
      foo: bar
  - kind: pubKey
    owner: victor # optional
    key: .... # mandatory
  - kind: genericIssuer
    issuer: https://github.com/login/oauth
    subject:
      equal: alice@example.com
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      equal: https://github.com/flavio/policy-secure-pod-images/.github/workflows/release.yml@refs/heads/main
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/flavio/
  - kind: genericIssuer
    issuer: https://token.actions.githubusercontent.com
    subject:
      urlPrefix: https://github.com/kubewarden # <- it will be post-fixed with `+/+` for security reasons
  - kind: githubAction
    owner: flavio   # mandatory
    repo: policy1 # optional
  - kind: pubKey
    owner: alice # optional
    key: .... # mandatory
----
====


=== Validierung der Unterschrift

Die vorherige Konfiguration enthält die beiden Abschnitte `+allOf+` und `+anyOf+`:

* `+allOf+`: Sie vertrauen der Richtlinie nur, wenn alle Unterschriftsanforderungen erfüllt sind.
* `+anyOf+`: Sie vertrauen der Police, wenn die `+minimumMatches+` Kriterien gültig sind.

In diesem Beispiel ist das Feld `+minimumMatches+` gleich 2. Sie müssen also mindestens zwei der Unterschriftenanforderungen erfüllen. Der Standardwert für das Feld `+minimumMatches+`ist `+1+`.

Für die Signaturvalidierung müssen Sie alle Anforderungen an die Signatur aus `+allOf+` *und* die Mindestanzahl aus `+anyOf+` erfüllen.

=== Validierung des öffentlichen Schlüssels

Um zu prüfen, ob eine Richtlinie mit dem richtigen öffentlichen Schlüssel signiert ist, geben Sie die Schlüsseldaten und den Eigentümer des Schlüssels an. In diesem Beispiel setzen Sie `+kind+` auf `+pubKey+` und `+key+` hat den öffentlichen Schlüssel. Das Eigentümerfeld ist optional, kann aber nützlich sein, um zu klären, wer der Eigentümer des Schlüssels ist.

[subs="+attributes",yaml]
----
  - kind: pubKey
    owner: bob # optional
    key: |
      -----BEGIN PUBLIC KEY-----
      MBFKHFDGHKIJH0CAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbDE6HJSGAVD
      BVDF6SKFSF87AASUspkQsN3FO4iyWodCy5j3o0CdIJD/KJHDJFHDFIu6sA==
      -----END PUBLIC KEY-----
----

=== Schlüssellose Signaturvalidierung

Eine im Keyless-Modus signierte Richtlinie hat keinen öffentlichen Schlüssel, den Sie überprüfen können. Sie können die Richtlinie weiterhin mit den OpenID Connect (OIDC)-Daten überprüfen, die während des Signiervorgangs verwendet werden. Dazu ist es notwendig, die Signaturvalidierung als`+genericIssuer+` zu definieren.

Es ist möglich, Informationen anhand der Unterschrift zu überprüfen:

* `+issuer+`(obligatorisch): entspricht dem Attribut `+Issuer+` in dem von Fulcio generierten Zertifikat. Hier wird der OIDC angezeigt, der zur Unterzeichnung der Police verwendet wird.
* `+subject+`: Feld, das zum Abgleich mit dem Attribut `+Subject+` in Fulcios Zertifikat verwendet wird. Das Feld `+Subject+` (Fulcio) enthält den Benutzer, der für die Authentifizierung gegenüber dem OIDC-Anbieter verwendet wird. Das Verifizierungsfeld, `+subject+`, kann eines von zwei Unterfeldern haben:

** `+equal+`Die `+Subject+` (Fulcio) aus dem Zertifikat muss mit dem Wert in der Signaturprüfung übereinstimmen;
** `+urlPrefix+`: Dem Feld `+Subject+` (Fulcio) des Zertifikats muss der in der Signaturvalidierung definierte Wert vorangestellt werden.

[NOTE]
====

Sowohl auf `+cosign verify+` als auch auf `+kwctl inspect+` können Informationen über schlüssellose Signaturen angezeigt werden.

====


Diese Konfiguration bedeutet zum Beispiel, dass die Richtlinie eine schlüssellose Signatur von Alice unter Verwendung des GitHub OIDC haben muss:

[subs="+attributes",yaml]
----
- kind: genericIssuer
  issuer: https://github.com/login/oauth
  subject:
    equal: alice@example.com
----

Für diese Konfiguration muss die Richtlinie in GitHub-Aktionen signiert werden, und zwar von einem Repository, das dem GitHub-Benutzer `+flavio+` gehört:

[subs="+attributes",yaml]
----
- kind: genericIssuer
  issuer: https://token.actions.githubusercontent.com
  subject:
    urlPrefix: https://github.com/flavio
----

=== GitHub-Aktionen Signaturprüfung

Die "Art" `+githubAction+` dient dazu, in GitHub-Aktionen signierte Richtlinien zu validieren.
Sie können dies auch mit der Art `+genericIssuer+` tun. Um den Prozess der Unterschriftsanforderung zu vereinfachen, verwenden Sie zwei zusätzliche Felder für `+githubAction+`:

* `+owner+` (obligatorisch): GitHub-ID des Benutzers oder der Organisation, dem/der vertraut werden soll.
* `+repo+`: Der Name des zu vertrauenden Repositorys.

Zum Beispiel könnte der letzte Ausschnitt unter Verwendung von `+genericIssuer+` wie folgt umgeschrieben werden:

[subs="+attributes",yaml]
----
- kind: githubAction
  owner: flavio
----

=== Validierung von Unterschriftenvermerken

Alle Signaturtypen können weitere optionale Validierungsfelder haben, `+annotations+`.
Bei diesen Feldern handelt es sich um Schlüssel/Wert-Daten, die während des Signiervorgangs hinzugefügt werden.

Mit {short-project-name} können Sie überprüfen, ob die Richtliniensignatur von vertrauenswürdigen Benutzern stammt *und*bestimmte Anmerkungen enthält.

Bei der nächsten Validierung werden zwei Bedingungen für die Police geprüft:

* dass sie mit einem bestimmten Schlüssel signiert ist
* er hat eine Anmerkung zur Produktionsumgebung.

[subs="+attributes",yaml]
----
- kind: pubKey
  key: |
    -----BEGIN PUBLIC KEY-----
    MBFKHFDGHKIJH0CAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbDE6HJSGAVD
    BVDF6SKFSF87AASUspkQsN3FO4iyWodCy5j3o0CdIJD/KJHDJFHDFIu6sA==
    -----END PUBLIC KEY-----
  annotations:
    environment: production
----

=== Verwendung einer Signaturprüfungs-Konfigurationsdatei zur Prüfung eines OCI-Artefakts für Richtlinien

Sie können mit Hilfe der Verifizierungskonfigurationsdatei testen, ob eine Richtlinie die Überprüfung besteht. Verwenden Sie das Flag `+--verification-config-path+` des Befehls `kwctl verify`.

[subs="+attributes",console]
----
$ cat signatures_requirements.yaml
apiVersion: v1
allOf:
  - kind: pubKey
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5Q+cN1Jj2S7N05J4AXnqwP2DyzSg
      Mc+raYce2Wthrd30MSgFtoh5ADAkCd/nML2Nx8UD9KBuASRb0gG5jXqgMQ==
      -----END PUBLIC KEY-----

$ kwctl verify --verification-config-path signatures_requirements.yaml ghcr.io/kubewarden/policies/user-group-psp:latest
2022-03-29T17:34:37.847169Z  INFO kwctl::verify: Policy successfully verified
----

In diesem letzten Beispiel wird geprüft, ob eine bestimmte Richtlinie von der Organisation {short-project-name}stammt:

[subs="+attributes",console]
----
$ cat kubewarden_signatures.yaml
apiVersion: v1
allOf:
  - kind: githubAction
    owner: kubewarden

$ kwctl verify --verification-config-path kubewarden_signatures.yaml ghcr.io/kubewarden/policies/user-group-psp:latest
2022-03-29T18:07:39.062292Z  INFO kwctl::verify: Policy successfully verified
----
