include::partial$variables.adoc[]
= Soutien aux gardiens
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Accédez à des politiques centrales de gatekeeper et apprenez à les intégrer aux contrôleurs d'admission Kubernetes.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "rego", "gatekeeper"]
:current-version: {page-origin-branch}

[NOTE]
====
La prise en charge de Gatekeeper commence à partir de ces versions :

* kwctl : v0.2.0
* serveur de politique : v0.2.0
====


Gatekeeper est un projet ciblant Kubernetes avec des fonctionnalités prêtes à l'emploi pour l'intégration.

== Compatibilité avec les politiques existantes

Toutes les politiques Gatekeeper existantes doivent être compatibles avec {short-project-name} comme expliqué dans ce chapitre.

[IMPORTANT]
====
Si vous constatez que ce n'est pas le cas pour vos politiques Gatekeeper, signalez-le et nous ferons en sorte que votre politique Gatekeeper fonctionne avec {short-project-name}.
====


Les politiques doivent être compilées avec le CLI `opa` pour `wasm` target.

Pour l'exécution des politiques, vous pouvez en savoir plus sur lexref:tutorials/writing-policies/rego/02-builtin-support.adoc[support intégré de l'] Open Policy Agent à l'adresse {short-project-name}.
