include::partial$variables.adoc[]
= Distribuer une politique Gatekeeper avec {project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Distribuer les politiques Gatekeeper dans les clusters Kubernetes en annotant les fichiers de politiques avec des métadonnées et en les déployant via ClusterAdmissionPolicy.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "gatekeeper", "rego"]
:current-version: {page-origin-branch}

Les politiques doivent être annotées pour être poussées, et finalement exécutées par le site {project-name} `policy-server` dans un cluster Kubernetes.

L'annotation et la distribution d'une politique Gatekeeper est similaire à la distribution d'une politique Open Policy Agent.

== Annoter la politique

Vous allez écrire un fichier `metadata.yaml` dans votre répertoire de politiques avec un contenu :

[subs="+attributes",yaml]
----
rules:
- apiGroups: [""]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["CREATE"]
mutating: false
contextAware: false
executionMode: gatekeeper
annotations:
  io.kubewarden.policy.title: no-default-namespace
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: This policy will reject any resource created inside the default namespace
  io.kubewarden.policy.author: The {short-project-name} Authors
  io.kubewarden.policy.url: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.source: https://github.com/kubewarden/some-policy
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
      This policy is just an example.

      You can write interesting descriptions about the policy here.
----

vous pouvez voir que tout est identique aux métadonnées de la version de l'Open Policy Agent, à l'exception du bit `executionMode: gatekeeper`.

Allez-y et annotez la politique :

[subs="+attributes",console]
----
$ kwctl annotate policy.wasm --metadata-path metadata.yaml --output-path annotated-policy.wasm
----

== Pousser la politique

Transmettez votre politique à un registre OCI :

[subs="+attributes",console]
----
$ kwctl push annotated-policy.wasm registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
Policy successfully pushed
----

== Déploiement sur Kubernetes

Vous devez d'abord déposer votre police auprès de votre magasin local `kwctl`:

[subs="+attributes",console]
----
$ kwctl pull registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1
pulling policy...
----

Vous pouvez maintenant créer une ressource d'échafaudage `ClusterAdmissionPolicy`:

[subs="+attributes",console]
----
$ kwctl scaffold manifest registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1 --type ClusterAdmissionPolicy
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: generated-policy
spec:
  module: "registry://registry.my-company.com/kubewarden/no-default-namespace-gatekeeper:v0.0.1"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - "*"
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Utilisez maintenant cette ressource `ClusterAdmissionPolicy` pour déployer votre politique dans un cluster Kubernetes.
