= SUSE Observability-Kurzanleitungen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität
:doctype: book

== Übersicht

Sobald Ihre SUSE Observability SaaS-Instanz eingerichtet und konfiguriert ist, erhalten Sie eine E-Mail von SUSE Observability mit den erforderlichen Anmeldedaten. Diese Schnellstartanleitung hilft Ihnen, Ihre eigenen Daten in Ihre SUSE Observability SaaS-Instanz zu übertragen.

Um Ihre(n) Cluster mit SUSE Observability zu integrieren, können Sie einen dieser Leitfäden für Ihre entsprechende Umgebung befolgen.

* <<_amazon_eks,Amazon EKS>>
* <<_azure_aks,Azure AKS>>
* <<_google_gke,Google GKE>>
* <<_kubernetes,Kubernetes>>
* <<_kops,KOPS>>
* <<_openshift,OpenShift>>
* <<_self_hosted,Selbst gehostet>>


== Kubernetes

Richten Sie eine Kubernetes-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Kubernetes-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Unterstützte Kubernetes-Version

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Kubernetes

Um eine SUSE Observability-Kubernetes-Integration einzurichten, benötigen Sie folgende Voraussetzungen:

* Ein betriebsbereiter Kubernetes-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit der Berechtigung zu `+create privileged pods+`, `+ClusterRoles+` und `+ClusterRoleBindings+`:
 ** ClusterRole und ClusterRoleBinding werden benötigt, um SUSE Observability-Agenten Berechtigungen für den Zugriff auf die Kubernetes-API zu erteilen.
 ** SUSE Observability-Agenten müssen in einem privilegierten Pod ausgeführt werden, damit sie Informationen über Netzwerkverbindungen und Host-Informationen sammeln können.

=== Einrichten einer Kubernetes-Integration

[CAUTION]
====
Bevor Sie beginnen, prüfen Sie die <<_prerequisites_for_kubernetes,Voraussetzungen für Kubernetes>>.
====


Gehen Sie wie folgt vor, um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen:

. Fügen Sie das SUSE Observability helm-Repository zum lokalen helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability-Benutzeroberfläche das Hauptmenü, indem Sie oben links auf den Bildschirm klicken und zu `+StackPacks+` > `+Kubernetes+` gehen.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Festlegen eines *Kubernetes-Cluster-Namens*
  *** Dieser Name wird zur Identifizierung des Clusters in SUSE Observability verwendet.
 ** Klicken Sie auf *Installieren*.
. Stellen Sie den SUSE Observability-Agenten, den Cluster-Agenten, den Prüfagenten und kube-state-metrics mit dem Befehl helm in der SUSE Observability-Benutzeroberfläche auf Ihrem Cluster bereit, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten implementiert sind, beginnen sie mit der Datenerfassung und übermitteln diese an SUSE Observability

[CAUTION]
====
Wenn Sie in einer selbst gehosteten Air-Gapped-Umgebung arbeiten, bereiten Sie die Installation des Agenten zunächst anhand der xref:/k8s-suse-rancher-prime-agent-air-gapped.adoc[Air-Gapped-Anweisungen] vor.
====


== OpenShift

Richten Sie eine OpenShift-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten aus einem OpenShift-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| OpenShift-Version | Unterstützte Kubernetes-Version | OpenShift Ende der Unterstützung

| OpenShift 4.17
| Kubernetes 1.30
| 1. April 2026

| OpenShift 4.16
| Kubernetes 1.29
| 27. Dezember 2025

| OpenShift 4.15
| Kubernetes 1.28
| August 27, 2025

| OpenShift 4.14
| Kubernetes 1.27
| 1. Mai 2025

| OpenShift 4.13
| Kubernetes 1.26
| 17. November 2024

| OpenShift 4.12
| Kubernetes 1.25
| 17. Juli 2024

| OpenShift 4.11
| Kubernetes 1.24
| 10. Februar 2024

| OpenShift 4.10
| Kubernetes 1.23
| 10. September 2023

| OpenShift 4.9
| Kubernetes 1.22
| April 18, 2023
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für OpenShift

Um eine SUSE Observability OpenShift-Integration einzurichten, benötigen Sie folgende Voraussetzungen:

* Ein funktionierender OpenShift Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit der Berechtigung zu `+create privileged pods+`, `+ClusterRoles+` und `+ClusterRoleBindings+`:
 ** ClusterRole und ClusterRoleBinding werden benötigt, um SUSE Observability-Agenten Berechtigungen für den Zugriff auf die Kubernetes-API zu erteilen.
 ** SUSE Observability-Agenten müssen in einem privilegierten Pod ausgeführt werden, damit sie Informationen über Netzwerkverbindungen und Host-Informationen sammeln können.

=== Einrichten einer OpenShift-Integration

[CAUTION]
====
Bevor Sie beginnen, prüfen Sie die <<_prerequisites_for_openshift,Voraussetzungen für Kubernetes>>.
====


Gehen Sie wie folgt vor, um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen:

. Fügen Sie das SUSE Observability helm-Repository zum lokalen helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability-Benutzeroberfläche das Hauptmenü, indem Sie oben links auf den Bildschirm klicken und zu `+StackPacks+` > `+Integrations+` > `+Kubernetes+` gehen.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Festlegen eines *Kubernetes-Cluster-Namens*
  *** Dieser Name wird zur Identifizierung des Clusters in SUSE Observability verwendet.
 ** Klicken Sie auf *Installieren*.
. Stellen Sie den SUSE Observability-Agenten, den Cluster-Agenten, den Prüfagenten und kube-state-metrics mit dem Befehl helm in der SUSE Observability-Benutzeroberfläche auf Ihrem Cluster bereit, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten implementiert sind, beginnen sie mit der Datenerfassung und übermitteln diese an SUSE Observability


== Amazon EKS

Richten Sie eine Amazon EKS-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Amazon EKS-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Kubernetes-Version | Amazon EKS-Freigabe | Amazon EKS Ende der Unterstützung | Amazon EKS Ende des erweiterten Supports

| 1.32
| Januar 23, 2025
| März 23, 2026
| März 23, 2027

| 1.31
| 26. September 2024
| November 26, 2025
| 26. November 2026

| 1.30
| 23. Mai 2024
| Juli 23, 2025
| 23. Juli 2026

| 1.29
| 23. Januar 2024
| März 23, 2025
| März 23, 2026

| 1.28
| 26. September 2023
| 01. November 2024
| November 26, 2025

| 1.27
| Mai 24, 2023
| Juli 2024
| Juli 24, 2025

| 1.26
| 11. April 2023
| Juni 2024
| 11. Juni 2025

| 1.25
| 21. Februar 2023
| Mai 2024
| 1. Mai 2025

| 1.24
| November 15, 2022
| Januar 2024
| 31. Januar 2025

| 1.23
| 11. August 2022
| 11. Oktober 2023
| 11. Oktober 2024

| 1.22
| April 4, 2022
| 4. Juni 2023
| 1. September 2024

| 1.21
| Juli 19, 2021
| 15. Februar 2023
| 15. Juli 2024

| 1.20
| Mai 18, 2021
| 1. November 2022
| K.A.

| 1.19
| Februar 16, 2021
| 1. August 2022
| K.A.

| 1.18
| Oktober 13, 2020
| August 15, 2022
| K.A.
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Amazon EKS

Um eine SUSE Observability Amazon EKS-Integration einzurichten, benötigen Sie folgende Voraussetzungen:

* Ein funktionierender Amazon EKS Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit der Berechtigung zu `+create privileged pods+`, `+ClusterRoles+` und `+ClusterRoleBindings+`:
 ** ClusterRole und ClusterRoleBinding werden benötigt, um SUSE Observability-Agenten Berechtigungen für den Zugriff auf die Kubernetes-API zu erteilen.
 ** SUSE Observability-Agenten müssen in einem privilegierten Pod ausgeführt werden, damit sie Informationen über Netzwerkverbindungen und Host-Informationen sammeln können.

=== Einrichten einer Amazon EKS-Integration

[CAUTION]
====
Bevor Sie beginnen, prüfen Sie die <<_prerequisites_for_amazon_eks,Voraussetzungen für Kubernetes>>.
====


Gehen Sie wie folgt vor, um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen:

. Fügen Sie das SUSE Observability helm-Repository zum lokalen helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability-Benutzeroberfläche das Hauptmenü, indem Sie oben links auf den Bildschirm klicken und zu `+StackPacks+` > `+Integrations+` > `+Kubernetes+` gehen.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Festlegen eines *Kubernetes-Cluster-Namens*
  *** Dieser Name wird zur Identifizierung des Clusters in SUSE Observability verwendet.
 ** Klicken Sie auf *Installieren*.
. Stellen Sie den SUSE Observability-Agenten, den Cluster-Agenten, den Prüfagenten und kube-state-metrics mit dem Befehl helm in der SUSE Observability-Benutzeroberfläche auf Ihrem Cluster bereit, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten implementiert sind, beginnen sie mit der Datenerfassung und übermitteln diese an SUSE Observability


== Google GKE

Richten Sie eine Google GKE-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Google GKE-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Kubernetes Version | Google GKE Freigabe | Google GKE Ende der Unterstützung | Google GKE Ende des erweiterten Supports

| 1.32
| Februar, 2025
| Q2, 2026
| Q1, 2027

| 1.31
| 22. Oktober 2024
| 22. Dezember 2025
| 22. Oktober 2026

| 1.30
| 30. Juli 2024
| 30. September 2025
| 30. Juli 2026

| 1.29
| 25. Januar 2024
| März 21, 2025
| 25. Januar 2026

| 1.28
| 4. Dezember 2023
| Februar 4, 2025
| Dezember 4, 2025

| 1.27
| 14. Juni 2023
| 31. August 2024
| Juni 14, 2025

| 1.26
| April 14, 2023
| 30. Juni 2024
| K.A.
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Google GKE

Um eine SUSE Observability Google GKE-Integration einzurichten, benötigen Sie folgende Voraussetzungen:

* Ein funktionierender Google GKE-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit der Berechtigung zu `+create privileged pods+`, `+ClusterRoles+` und `+ClusterRoleBindings+`:
 ** ClusterRole und ClusterRoleBinding werden benötigt, um SUSE Observability-Agenten Berechtigungen für den Zugriff auf die Kubernetes-API zu erteilen.
 ** SUSE Observability-Agenten müssen in einem privilegierten Pod ausgeführt werden, damit sie Informationen über Netzwerkverbindungen und Host-Informationen sammeln können.

=== Einrichten einer Google GKE-Integration

[CAUTION]
====
Bevor Sie beginnen, prüfen Sie die <<_prerequisites_for_google_gke,Voraussetzungen für Kubernetes>>.
====


Gehen Sie wie folgt vor, um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen:

. Fügen Sie das SUSE Observability helm-Repository zum lokalen helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability-Benutzeroberfläche das Hauptmenü, indem Sie oben links auf den Bildschirm klicken und zu `+StackPacks+` > `+Integrations+` > `+Kubernetes+` gehen.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Festlegen eines *Kubernetes-Cluster-Namens*
  *** Dieser Name wird zur Identifizierung des Clusters in SUSE Observability verwendet.
 ** Klicken Sie auf *Installieren*.
. Stellen Sie den SUSE Observability-Agenten, den Cluster-Agenten, den Prüfagenten und kube-state-metrics mit dem Befehl helm in der SUSE Observability-Benutzeroberfläche auf Ihrem Cluster bereit, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten implementiert sind, beginnen sie mit der Datenerfassung und übermitteln diese an SUSE Observability


== Azure AKS

Richten Sie eine Azure AKS-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Azure AKS-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Kubernetes Version | AKS GA | Azure AKS Ende der Lebensdauer | Unterstützung der Plattform

| 1.32
| Juni 2024
| März 2026
| Bis 1.36 GA

| 1.31
| November 2024
| November 2025
| Bis 1.35 GA

| 1.30
| Juni 2024
| Juli 2025
| Bis 1.34 GA

| 1.29
| März 2024
| Januar 2025
| Bis 1.33 GA

| 1.28
| November 2023
| November 2024
| Bis 1.32 GA

| 1.27
| Juli 2023
| Juli 2024
| Juli 2025
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Azure AKS

Um eine SUSE Observability Azure AKS-Integration einzurichten, benötigen Sie folgende Voraussetzungen:

* Ein betriebsbereiter Azure AKS Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit der Berechtigung zu `+create privileged pods+`, `+ClusterRoles+` und `+ClusterRoleBindings+`:
 ** ClusterRole und ClusterRoleBinding werden benötigt, um SUSE Observability-Agenten Berechtigungen für den Zugriff auf die Kubernetes-API zu erteilen.
 ** SUSE Observability-Agenten müssen in einem privilegierten Pod ausgeführt werden, damit sie Informationen über Netzwerkverbindungen und Host-Informationen sammeln können.

=== Einrichten einer Azure AKS-Integration

[CAUTION]
====
Bevor Sie beginnen, prüfen Sie die <<_prerequisites_for_azure_aks,Voraussetzungen für Kubernetes>>.
====


Gehen Sie wie folgt vor, um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen:

. Fügen Sie das SUSE Observability helm-Repository zum lokalen helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability-Benutzeroberfläche das Hauptmenü, indem Sie oben links auf den Bildschirm klicken und zu `+StackPacks+` > `+Integrations+` > `+Kubernetes+` gehen.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Festlegen eines *Kubernetes-Cluster-Namens*
  *** Dieser Name wird zur Identifizierung des Clusters in SUSE Observability verwendet.
 ** Klicken Sie auf *Installieren*.
. Stellen Sie den SUSE Observability-Agenten, den Cluster-Agenten, den Prüfagenten und kube-state-metrics mit dem Befehl helm in der SUSE Observability-Benutzeroberfläche auf Ihrem Cluster bereit, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten implementiert sind, beginnen sie mit der Datenerfassung und übermitteln diese an SUSE Observability


== KOPS

Richten Sie eine KOPS-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem KOPS-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Unterstützte Kubernetes-Version

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für KOPS

Um eine SUSE Observability KOPS-Integration einzurichten, benötigen Sie folgende Voraussetzungen:

* Ein betriebsbereiter KOPS-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit der Berechtigung zu `+create privileged pods+`, `+ClusterRoles+` und `+ClusterRoleBindings+`:
 ** ClusterRole und ClusterRoleBinding werden benötigt, um SUSE Observability-Agenten Berechtigungen für den Zugriff auf die Kubernetes-API zu erteilen.
 ** SUSE Observability-Agenten müssen in einem privilegierten Pod ausgeführt werden, damit sie Informationen über Netzwerkverbindungen und Host-Informationen sammeln können.

=== Einrichten einer KOPS-Integration

[CAUTION]
====
Bevor Sie beginnen, prüfen Sie die <<_prerequisites_for_kops,Voraussetzungen für Kubernetes>>.
====


Gehen Sie wie folgt vor, um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen:

. Fügen Sie das SUSE Observability helm-Repository zum lokalen helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability-Benutzeroberfläche das Hauptmenü, indem Sie oben links auf den Bildschirm klicken und zu `+StackPacks+` > `+Integrations+` > `+Kubernetes+` gehen.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Festlegen eines *Kubernetes-Cluster-Namens*
  *** Dieser Name wird zur Identifizierung des Clusters in SUSE Observability verwendet.
 ** Klicken Sie auf *Installieren*.
. Stellen Sie den SUSE Observability-Agenten, den Cluster-Agenten, den Prüfagenten und kube-state-metrics mit dem Befehl helm in der SUSE Observability-Benutzeroberfläche auf Ihrem Cluster bereit, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten implementiert sind, beginnen sie mit der Datenerfassung und übermitteln diese an SUSE Observability


== Selbst gehostet

Richten Sie eine Self-hosted-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Self-hosted-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Unterstützte Kubernetes-Version

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Self-hosted

Um eine SUSE Observability Self-hosted-Integration einzurichten, benötigen Sie folgende Voraussetzungen:

* Ein selbst gehosteter Cluster, der sofort einsatzbereit ist.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit der Berechtigung zu `+create privileged pods+`, `+ClusterRoles+` und `+ClusterRoleBindings+`:
 ** ClusterRole und ClusterRoleBinding werden dazu benötigt:
  *** Erteilen Sie SUSE Observability-Agenten die Berechtigung zum Zugriff auf die Kubernetes-API
  *** Generierung eines Geheimnisses für den mutierenden Validierungs-Webhook, der Teil der xref:/setup/agent/k8sTs-agent-request-tracing.adoc[Anforderungsverfolgung] ist
 ** SUSE Observability-Agenten müssen in einem privilegierten Pod ausgeführt werden, damit sie Informationen über Netzwerkverbindungen und Host-Informationen sammeln können.

=== Einrichten einer selbst gehosteten Integration

[CAUTION]
====
Bevor Sie beginnen, prüfen Sie die <<_prerequisites_for_self_hosted,Voraussetzungen für Kubernetes>>.
====


Gehen Sie wie folgt vor, um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen:

. Fügen Sie das SUSE Observability helm-Repository zum lokalen helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability-Benutzeroberfläche das Hauptmenü, indem Sie oben links auf den Bildschirm klicken und zu `+StackPacks+` > `+Integrations+` > `+Kubernetes+` gehen.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Festlegen eines *Kubernetes-Cluster-Namens*
  *** Dieser Name wird zur Identifizierung des Clusters in SUSE Observability verwendet.
 ** Klicken Sie auf *Installieren*.
. Stellen Sie den SUSE Observability-Agenten, den Cluster-Agenten, den Prüfagenten und kube-state-metrics mit dem Befehl helm in der SUSE Observability-Benutzeroberfläche auf Ihrem Cluster bereit, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten implementiert sind, beginnen sie mit der Datenerfassung und übermitteln diese an SUSE Observability


== Was kommt als Nächstes?

* xref:/k8s-getting-started.adoc[SUSE Observability-Durchgang]
