include::partial$variables.adoc[]
= 情境感知政策
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 探索准入控制中的情境感知策略功能，包括资源访问和缓存，以优化策略评估。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "context-aware-policies"]
:doc-type: ["reference"]
:keywords: ["kubewarden"、"kubernetes"、"策略规范"、"上下文感知策略"]
:sidebar_label: 情境感知政策
:current-version: {page-origin-branch}

`policy-server` 具有向策略公开集群信息的功能，这样，策略就可以根据其他现有资源，而不仅仅是根据接纳请求提供的详细信息做出决定。

托管策略的策略服务器会检索 Kubernetes 资源。应用于策略服务器服务账户的 RBAC 规则对 Kubernetes 的访问进行管理。

`default` Policy Server 由{project-name} Helm charts 部署，可访问以下 Kubernetes 资源：

* 命名空间
* 服务
* 入侵

[CAUTION]
====

策略服务器会缓存从 Kubernetes API 服务器获取的结果，以减少 Kubernetes 核心部分的负载量。这意味着信息可能已经过时或丢失。

====


== 支持矩阵

[cols=",^,"]
|===
| 政策类型 | 支持 | 说明

| 传统编程语言
| ✅
| -

| 雷戈
| ✅
| 自{short-project-name} 1.9 版发布以来

| WASI
| ✅
| 自{short-project-name} 1.10.0 发布以来，仅适用于 Go SDK
|===

== 制约因素

{short-project-name}{short-project-name} 考虑了两个限制因素：

* 内存使用情况：策略服务器进程会将从 Kubernetes 获取的数据缓存在内存中。获取的数据越多，策略服务器 Pod 消耗的内存就越多。
* 一致性：策略服务器保存的缓存可能包含过期数据。新资源可能丢失，已删除的资源可能仍然可用，已更改的资源可能有旧数据。这可能会影响政策评估。

=== 列出多个资源

{short-project-name} 策略可以同时获取多个资源。例如，他们可以进行这样的查询："获取`default`命名空间内定义的、标签`color` 设置为``green`` 的所有 Pod"。

通过这种查询，策略服务器会获取符合用户条件的所有资源。资源获取是分批进行的，以减少 Kubernetes API 服务器的负载。在内存中存储资源之前，策略服务器会删除每个资源的`managedFields` 属性，以减少内存消耗量。该属性对策略并无用处，而且占用大量内存。

然后，策略服务器会创建一个https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes[Kubernetes watch]，以保持缓存对象列表的更新。策略服务器无法控制 Kubernetes API 服务器发送资源变更通知的速度。这取决于不同的外部因素，如针对 Kubernetes API 服务器创建的手表数量及其负载。

最后，目前的代码有以下限制。给定这两个查询：

* `kubectl get pods -n default`
* `kubectl get pods -n default -l color=green`

策略服务器会创建两个监视器，并复制第二个查询的所有 Pod。{short-project-name} 今后的版本将取消这一限制。

=== 获取特定资源

{short-project-name} 策略可以获取集群内部定义的特定资源。
例如，他们可以进行类似 "获取`db` 命名空间内定义的名为`psql-0` 的 Pod "的查询。

默认情况下，该查询会获取对象并将其存储在内存缓存中 5 秒钟。在这五秒钟内，策略会收到缓存数据。

策略制定者也可以决定直接查询，跳过缓存。
始终提供新鲜数据。这会增加 Kubernetes API 服务器的负载（取决于策略触发的频率），并增加评估接纳请求的延迟。

直接或缓存查询行为由策略作者使用{short-project-name} SDK 在每个查询级别上进行配置。

== ClusterAdmissionPolicies

ClusterAdmissionPolicies 的字段为https://doc.crds.dev/github.com/kubewarden/kubewarden-controller/policies.kubewarden.io/ClusterAdmissionPolicy/v1#spec-contextAwareResources[spec.contextAwareResources]。
此字段提供了策略需要访问的`GroupVersionKind` 资源列表。这样，政策编写者就可以将政策所需的 "权限 "与政策一起发送。此外，这还允许策略操作员在部署时审查策略所需的 "权限"。

=== 在本地测试情境感知政策

除了在群集中运行策略进行端到端测试外，还可以使用`kwctl` CLI 实用程序针对群集运行策略和模拟请求。

为此，`kwctl run` 可首先将与群集的所有交互记录到文件中：

[subs="+attributes",console]
----
kwctl run \
    --allow-context-aware \
    -r request.json \
    --record-host-capabilities-interactions replay-session.yml \
    annotated-policy.wasm
----

创建以下`replay-session.yml` 文件：

[subs="+attributes",yaml]
----
# replay-session.yml
---
- type: Exchange
  request: |
    !KubernetesGetResource
    api_version: /v1
    kind: Pod
    name: p-testing
    namespace: local
    disable_cache: true
  response:
    type: Success
    payload: '{"apiVersion":"","kind":"Pod", <snipped> }'
----

使用重放会话，您现在可以在不需要集群的情况下模拟集群交互，这是 CI 和端到端测试的理想选择：

[subs="+attributes",console]
----
kwctl run \
    --allow-context-aware \
    -r request.json \
    --replay-host-capabilities-interactions replay-session.yml \
    annotated-policy.wasm
----

== 语言 SDK

支持群集上下文的语言 SDK 会公开允许策略检索群集当前状态的函数。

[TIP]
====

如果您想了解有关 SDK 使用的 waPC 功能的更多信息，请查阅xref:reference/spec/host-capabilities/06-kubernetes.adoc[Kubernetes 功能]参考文档。

====


=== 生锈

请参阅https://docs.rs/kubewarden-policy-sdk/0.8.7/kubewarden_policy_sdk[Rust SDK 参考文档] 中公开此功能的函数。

=== 转到

请参阅https://pkg.go.dev/github.com/kubewarden/policy-sdk-go[Go SDK 参考文档] 中公开此功能的函数。

== 雷戈政策

=== 守门人

情境感知信息暴露在`data.inventory` 密钥下，就像 Gatekeeper 一样。

通过`spec.contextAwareResources` 字段，清单中的人口与政策可访问的资源有关。

=== 开放政策代理

上下文感知信息会在`data.kubernetes` 键下显示，就像https://github.com/open-policy-agent/kube-mgmt[`kube-mgmt`]一样。

通过`spec.contextAwareResources` 字段，清单中的人口与政策可访问的资源有关。
