include::partial$variables.adoc[]
= Definición de la configuración de las políticas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Modificar el código en el archivo settings.go para definir la configuración de políticas, incluyendo la implementación de funciones personalizadas para marshaling y unmarshaling expresiones regulares.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "go", "defining-policy-settings"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "defining policy settings", "Go"]
:sidebar_label: Definición de la configuración de las políticas
:sidebar_position: 24
:current-version: {page-origin-branch}

En primer lugar, es necesario definir la estructura que contiene la configuración de la política.

Para ello, modifique el código del archivo `settings.go` (de su versión local de la plantilla de política Go).
Es necesario añadir dos líneas adicionales a la sección `import`, cambiar la estructura `Settings` y añadir la estructura `RegularExpression`.

Debe coincidir con el siguiente código:

[,go]
----
import (
    "encoding/json"
    "fmt"
    "regexp"

    mapset "github.com/deckarep/golang-set/v2"
    kubewarden "github.com/kubewarden/policy-sdk-go"
    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
)

type Settings struct {
    DeniedLabels      mapset.Set[string]            `json:"denied_labels"`
    ConstrainedLabels map[string]*RegularExpression `json:"constrained_labels"`
}

type RegularExpression struct {
    *regexp.Regexp
}
----

[NOTE]
====
`DeniedNames` ya no es necesaria en la estructura `Settings` definida en `settings.go`.

Como `DeniedNames` ya no está definida, también debe eliminar la función `IsNameDefined` en `settings.go`.
También debe eliminar la función que hace referencia a ella en `settings_test.go`, `TestIsNameDenied`.
====


Está utilizando el paquete `regexp` para manejar objetos de expresión regular y el tipohttps://github.com/deckarep/golang-set[`mapset.Set`] para almacenar la lista de etiquetas denegadas.

Dado que `regexp.Regexp` no gestiona la deserialización, es necesario definir funciones personalizadas para gestionar el marshaling y unmarshaling de las expresiones regulares:

[,go]
----
// UnmarshalText satisfies the encoding.TextMarshaler interface,
// also used by json.Unmarshal.
func (r *RegularExpression) UnmarshalText(text []byte) error {
    nativeRegExp, err := regexp.Compile(string(text))
    if err != nil {
        return err
    }
    r.Regexp = nativeRegExp
    return nil
}

// MarshalText satisfies the encoding.TextMarshaler interface,
// also used by json.Marshal.
func (r *RegularExpression) MarshalText() ([]byte, error) {
    if r.Regexp != nil {
        return []byte(r.Regexp.String()), nil
    }

    return nil, nil
}
----

Además, necesitas el método `UnmarshalJSON` para manejar la deserialización de la estructura `Settings`:

[,go]
----
func (s *Settings) UnmarshalJSON(data []byte) error {
    rawSettings := struct {
        DeniedLabels      []string          `json:"denied_labels"`
        ConstrainedLabels map[string]*RegularExpression `json:"constrained_labels"`
    }{}

    err := json.Unmarshal(data, &rawSettings)
    if err != nil {
        return err
    }

    s.DeniedLabels = mapset.NewThreadUnsafeSet[string](rawSettings.DeniedLabels...)
    s.ConstrainedLabels = rawSettings.ConstrainedLabels

    return nil
}
----

== Creación de instancias `Settings` 

Una política {short-project-name} expone dos funciones diferentes que reciben la configuración de la política como entrada:

* `validate`: Utilice esta función cuando el objeto Kubernetes requiera validación por parte de la política.
Los ajustes forman parte de unhttps://pkg.go.dev/github.com/kubewarden/policy-sdk-go@v0.2.1/protocol#ValidationRequest[`ValidationRequest`]objeto.
* `validate_settings`: Llame a esta función cuando la política se carga por primera vez por {short-project-name}.
La función recibe la configuración de la política como entrada y comprueba su validez.

Es necesario crear una función de ayuda que cree un objeto `Settings` a partir de la carga útil JSON:

[,go]
----
func NewSettingsFromValidationReq(validationReq *kubewarden_protocol.ValidationRequest) (Settings, error) {
    settings := Settings{}
    err := json.Unmarshal(validationReq.Settings, &settings)
    if err != nil {
        return Settings{}, err
    }

    return settings, nil
}
----

[NOTE]
====
Todos los objetos de `mapset.Set` se crean utilizando lahttps://pkg.go.dev/github.com/deckarep/golang-set?utm_source=godoc#NewThreadUnsafeSet[variante thread-unsafe de].
El código WebAssembly se ejecuta en un único hilo, por lo que no hay problemas de concurrencia.

El estándar WebAssembly aún no cubre los hilos.
Para más detalles, consulte https://github.com/WebAssembly/threads[la propuesta oficial].
====


== Aplicación de la validación `Settings` 

Todas las políticas de {short-project-name} tienen que aplicar la validación de configuraciones.

Para ello, añada un método `Valid` a las instancias de `Settings`:

[,go]
----
func (s *Settings) Valid() (bool, error) {
    constrainedLabels := mapset.NewThreadUnsafeSet[string]()

    for label := range s.ConstrainedLabels {
        constrainedLabels.Add(label)
    }

    constrainedAndDenied := constrainedLabels.Intersect(s.DeniedLabels)
    if constrainedAndDenied.Cardinality() != 0 {
        return false,
            fmt.Errorf("These labels cannot be constrained and denied at the same time: %v", constrainedAndDenied)
    }

    return true, nil
}
----

El método `Valid` garantiza que ninguna etiqueta "denegada" forme parte también del mapa "restringido".
El uso del método `Intersect` proporcionado por `mapset.Set` simplifica la comprobación.

[NOTE]
====
La invocación al método `Valid` se realiza sobre un objeto `Setting` ya instanciado.
Esto significa que la validación de la expresión regular proporcionada por el usuario ya ha tenido lugar en `Settings` unmarshaler.
====


Por último, es necesario que la función `validateSettings`, proporcionada por el andamiaje, cambie para tener este aspecto:

[,go]
----
func validateSettings(payload []byte) ([]byte, error) {
    settings := Settings{}
    err := json.Unmarshal(payload, &settings)
    if err != nil {
        return kubewarden.RejectSettings(
            kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
    }

    valid, err := settings.Valid()
    if valid {
        return kubewarden.AcceptSettings()
    }

    return kubewarden.RejectSettings(
        kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
}
----

Puede ver que la función aprovecha las funciones de ayuda proporcionadas porhttps://github.com/kubewarden/policy-sdk-go[el SDK de]

== Prueba del código de configuración

Es importante tener una buena cobertura de pruebas del código que escribes.
El código que está utilizando, procedente del andamiaje, viene con una serie de pruebas unitarias definidas en el archivo `settings_test.go`.

Debe cambiar el contenido de este archivo para reflejar el nuevo comportamiento de la clase `Settings`.

Incluya los paquetes Go que está utilizando:

[,go]
----
import (
    "testing"

    "encoding/json"

    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
)
----

Puede empezar escribiendo una prueba unitaria que garantice que puede asignar una instancia de `Settings`desde un objeto `ValidationRequest`:

[,go]
----
func TestParseValidSettings(t *testing.T) {
    settingsJSON := []byte(`
        {
            "denied_labels": [ "foo", "bar" ],
            "constrained_labels": {
                    "cost-center": "cc-\\d+"
            }
        }`)

    settings := Settings{}
    err := json.Unmarshal(settingsJSON, &settings)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    expected_denied_labels := []string{"foo", "bar"}
    for _, exp := range expected_denied_labels {
        if !settings.DeniedLabels.Contains(exp) {
            t.Errorf("Missing value %s", exp)
        }
    }

    re, found := settings.ConstrainedLabels["cost-center"]
    if !found {
        t.Error("Didn't find the expected constrained label")
    }

    expected_regexp := `cc-\d+`
    if re.String() != expected_regexp {
        t.Errorf("Expected regexp to be %v - got %v instead",
            expected_regexp, re.String())
    }
}
----

A continuación, necesita una prueba que compruebe que no se genera una instancia de `Settings` cuando el usuario proporciona una expresión regular rota:

[,go]
----
func TestParseSettingsWithInvalidRegexp(t *testing.T) {
    settingsJSON := []byte(`
        {
            "denied_labels": [ "foo", "bar" ],
            "constrained_labels": {
                    "cost-center": "cc-[a+"
            }
        }`)

    err := json.Unmarshal(settingsJSON, &Settings{})
    if err == nil {
        t.Errorf("Didn't get expected error")
    }
}
----

Ahora, puede definir una prueba que compruebe el comportamiento del punto de entrada`validate_settings`.

Usted mira el objeto `SettingsValidationResponse` devuelto por su función `validateSettings`:

[,go]
----
func TestDetectValidSettings(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar" ],
        "constrained_labels": {
            "cost-center": "cc-\\d+"
        }
    }`)

    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if !response.Valid {
        t.Errorf("Expected settings to be valid: %s", *response.Message)
    }
}
----

Por último, escribe dos pruebas más para comprobar que la función `validateSettings` rechaza las configuraciones no válidas con los mensajes correctos:

[,go]
----
func TestDetectNotValidSettingsDueToBrokenRegexp(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar" ],
        "constrained_labels": {
            "cost-center": "cc-[a+"
        }
    }
    `)

    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if response.Valid {
        t.Error("Expected settings to not be valid")
    }

    if *response.Message != "Provided settings are not valid: error parsing regexp: missing closing ]: `[a+`" {
        t.Errorf("Unexpected validation error message: %s", *response.Message)
    }
}

func TestDetectNotValidSettingsDueToConflictingLabels(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar", "cost-center" ],
        "constrained_labels": {
            "cost-center": ".*"
        }
    }`)
    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if response.Valid {
        t.Error("Expected settings to not be valid")
    }

    if *response.Message != "Provided settings are not valid: These labels cannot be constrained and denied at the same time: Set{cost-center}" {
        t.Errorf("Unexpected validation error message: %s", *response.Message)
    }
}
----

Ahora puede ejecutar las pruebas que ha definido hasta ahora utilizando el siguiente comando:

[subs="+attributes",shell]
----
go test -v settings.go settings_test.go
----

Todas las pruebas pasarán con la siguiente salida:

[subs="+attributes",shell]
----
=== RUN   TestParseValidSettings
--- PASS: TestParseValidSettings (0.00s)
=== RUN   TestParseSettingsWithInvalidRegexp
--- PASS: TestParseSettingsWithInvalidRegexp (0.00s)
=== RUN   TestDetectValidSettings
--- PASS: TestDetectValidSettings (0.00s)
=== RUN   TestDetectNotValidSettingsDueToBrokenRegexp
--- PASS: TestDetectNotValidSettingsDueToBrokenRegexp (0.00s)
=== RUN   TestDetectNotValidSettingsDueToConflictingLabels
--- PASS: TestDetectNotValidSettingsDueToConflictingLabels (0.00s)
PASS
ok      command-line-arguments    0.002s
----

Ahora puede implementar el código de validación real en la siguiente sección.
