include::partial$variables.adoc[]
= Registro
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure la inicialización del registrador para el registro estructurado en su política utilizando la integración Go SDK del proyecto oneLog.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "logging"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "golang", "go", "logging"]
:current-version: {page-origin-branch}

El SDK de Go se integra con elhttps://github.com/francoispqt/onelog[`onelog`]proyecto, casi fuera de la caja.
// TODO: Last release 2019. Still good?

El proyecto ha elegido esta biblioteca como:

* Funciona con binarios WebAssembly.
Otras soluciones populares de registro no pueden compilar en WebAssembly.
* Ofrece un https://github.com/francoispqt/onelog#benchmarks[buen rendimiento].
* Admite el registro estructurado.

== Inicializar registrador

Es necesario inicializar una estructura de registro.
Al realizar esta inicialización en una variable global, puede iniciar sesión desde los dos puntos de entrada principales de la política: `validate` y`validate_settings`.

En el paquete principal, `main.go` hay una inicialización para el registrador:

[,go]
----
var (
    logWriter = kubewarden.KubewardenLogWriter{}
    logger    = onelog.New(
        &logWriter,
        onelog.ALL, // shortcut for onelog.DEBUG|onelog.INFO|onelog.WARN|onelog.ERROR|onelog.FATAL
    )
)
----

== Consumir el registrador

Ahora, puede utilizar el objeto `logger` para iniciar sesión desde cualquier lugar que requiera su política:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.Info("validating request")
    // ...
}
----

Puedes añadir un registro estructurado:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.WarnWithFields("logging something important", func(e onelog.Entry) {
        e.String("one_field", "a value")
        e.String("another_field", "another value")
    })
    // ...
}
----

Para más información, consulte lahttps://pkg.go.dev/github.com/francoispqt/onelog?utm_source=godoc[documentación de]

El registro de políticas va al evaluador de políticas (por ejemplo, `kwctl` o `policy-server`), y registran en nombre de la política.
Utilizan mecanismos interoperables con otros componentes que permiten el rastreo distribuido, comohttps://www.jaegertracing.io/[Jaeger].
