include::partial$variables.adoc[]
= Problème de rotation des certificats du Policy Server pour la version ≤ v1.16.0
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Résoudre les problèmes de rotation des certificats des serveurs de politiques dans {project-name}, à partir de la version 1.16.
:doc-persona: ["kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["howto", "workarounds", "policy server certificates"].
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "policy server certificates"]
:sidebar_label: Rotation des certificats
:sidebar_position: 10
:current-version: {page-origin-branch}

[IMPORTANT]
.Solution de contournement pour {project-name} v1.16.0 et les versions antérieures
====

Cette solution de contournement n'est nécessaire que pour {short-project-name} v1.16.0 et les versions antérieures.
À partir de la version 1.17.0, le contrôleur renouvelle automatiquement les certificats du serveur de politiques.

====

Au cours du processus de publication de la version 1.14, {short-project-name} a découvert un bogue lié à la rotation du certificat du serveur de politique. La configuration de l'autorité de certification racine prévoit une expiration de 10 ans, mais chaque secret de certificat du serveur de politique a une expiration d'un an. Toutefois, le contrôleur n'est actuellement pas en mesure de les renouveler automatiquement.

Dans la version v1.14, {short-project-name} a veillé à ce que les secrets du serveur de politique soient créés avec une expiration de 10 ans.

Un processus de renouvellement automatisé est en place pour la version ≥ v1.16.0.

En attendant, les utilisateurs peuvent supprimer manuellement le secret du certificat expiré (policy-server-default) et déclencher un rapprochement du contrôleur. Pour ce faire, vous pouvez ajouter, supprimer ou mettre à jour une politique ou ajuster le nombre de répliques d'un PolicyServer.
