include::partial$variables.adoc[]
= Criação e distribuição de políticas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Siga estas etapas essenciais para criar e distribuir políticas de forma eficaz em sua configuração do site {project-name}.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "build-and-distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "escrever políticas", "rust", "construir e distribuir"]
:sidebar_label: Criação e distribuição de políticas
:current-version: {page-origin-branch}

== Criação da política

Até agora, você criou a política com um alvo de compilação do mesmo sistema operacional e arquitetura da sua máquina de desenvolvimento.

Agora é hora de criar a política como um binário do WebAssembly, um arquivo `.wasm`.

Você usa o comando:

[subs="+attributes",console]
----
make policy.wasm
----

Esse comando cria o código no modo de liberação, com um destino de compilação do WebAssembly.

A compilação produz um arquivo `policy.wasm`:

[subs="+attributes",console]
----
$ file policy.wasm
policy.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
----

== Distribuição da política

{project-name} documenta a distribuição dexref:../../../explanations/distributing-policies.adoc[políticas]na seçãoxref:../../../explanations/distributing-policies.adoc[de distribuição de políticas].

== Mais exemplos

Você pode encontrar mais políticas do Rust {short-project-name} no espaço do GitHub de {short-project-name}.https://github.com/search?l=Rust&q=topic%3Apolicy-as-code+org%3Akubewarden&type=Repositories[This query] pode ajudá-lo a encontrá-las.

Os repositórios de políticas do {short-project-name}, mostrados por essa consulta, têm GitHub Actions que automatizam as seguintes tarefas:

* Executar testes de unidade e code linting em solicitações pull e após a fusão de códigos no branch principal.
* Crie a política no modo `release` e envie-a para um registro OCI como um artefato.
