= Vernetzungsdienste
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

Auf dieser Seite wird erklärt, wie CoreDNS, Traefik Ingress Controller, Network Policy Controller und ServiceLB Load Balancer Controller innerhalb von K3s funktionieren.

Weitere Informationen zu den Flannel-Konfigurationsoptionen und der Auswahl des Backends finden Sie auf der Seite xref:networking/basic-network-options.adoc[Netzwerkoptionen für die Installation] oder auf der Seite zum Einrichten Ihres eigenen CNI.

Informationen darüber, welche Ports für K3s geöffnet werden müssen, finden Sie in den xref:installation/requirements.adoc#_networking[Netzwerkanforderungen].

== CoreDNS

CoreDNS wird beim Starten des Servers automatisch bereitgestellt. Um sie zu deaktivieren, konfigurieren Sie alle Server des Clusters mit der Option `--disable=coredns`.

Wenn Sie CoreDNS nicht installieren, müssen Sie selbst einen Cluster-DNS-Anbieter installieren.

== Traefik Ingress Controller

https://traefik.io/[Traefik] ist ein moderner HTTP Reverse Proxy und Load Balancer für die einfache Bereitstellung von Microservices. Es vereinfacht die Komplexität von Netzwerken beim Entwerfen, Implementieren und Ausführen von Anwendungen.

Der Traefik-Ingress-Controller setzt einen LoadBalancer Service ein, der die Ports 80 und 443 verwendet und die externen IPs des LoadBalancer Service im Status der von ihm verwalteten Ingress-Ressourcen bekannt gibt.

Standardmäßig verwendet ServiceLB alle Knoten im Cluster, um den Traefik LoadBalancer Service zu hosten, was bedeutet, dass die Ports 80 und 443 nicht für andere HostPort- oder NodePort-Pods verwendet werden können und der Status der Ingress-Ressourcen die Knoten-IPs aller Cluster-Mitglieder anzeigt.

Um die von Traefik verwendeten Knoten und damit die im Ingress-Status angezeigten Knoten-IPs einzuschränken, können Sie die Anweisungen im Abschnitt <<_controlling_servicelb_node_selection,Steuerung der ServiceLB-Knotenauswahl>> unten befolgen, um einzuschränken, auf welchen Knoten ServiceLB läuft, oder indem Sie einige Knoten zu einem LoadBalancer-Pool hinzufügen und den Traefik-Service auf diesen Pool beschränken, indem Sie in der Traefik HelmChartConfig entsprechende Labels festlegen.

Traefik wird beim Start des Servers standardmäßig installiert. Die Standardwerte für das Diagramm finden Sie unter `/var/lib/rancher/k3s/server/manifests/traefik.yaml`. Diese Datei sollte jedoch nicht manuell bearbeitet werden, da K3s die Datei beim Start durch Standardwerte ersetzt. Stattdessen sollten Sie Traefik anpassen, indem Sie ein zusätzliches `HelmChartConfig` Manifest in `/var/lib/rancher/k3s/server/manifests` erstellen. Weitere Details und ein Beispiel finden Sie unter xref:add-ons/helm.adoc#_customizing_packaged_components_with_helmchartconfig[Anpassen von Paketkomponenten mit HelmChartConfig]. Weitere Informationen zu den möglichen Konfigurationswerten finden Sie unter `values.yaml` in der https://github.com/k3s-io/k3s-charts/tree/main/charts/traefik[Traefik Helm Chart], die Ihrer Version von K3s beiliegt.

Um Traefik aus Ihrem Cluster zu entfernen, starten Sie alle Server mit dem Flag `--disable=traefik`. Weitere Informationen finden Sie unter xref:installation/packaged-components.adoc[Verwalten von verpackten Komponenten].

Einzelheiten über die spezifische Version von Traefik, die in K3s enthalten ist, finden Sie in den Versionshinweisen für Ihre Version.

* K3s-Versionen ab **1.32** enthalten Traefik v3. Bestehende Installationen von Traefik v2 werden automatisch auf v3 aktualisiert, wenn K3s aktualisiert wird.
  Traefik v3 sollte mit der Konfiguration von v2 kompatibel sein; weitere Informationen finden Sie in den Upstream-Dokumenten zur https://doc.traefik.io/traefik/migrate/v2-to-v3/[Migration von] v2.
* Die K3-Versionen **1.21** bis **1.31** enthalten Traefik v2, es sei denn, es wurde eine bestehende Installation von Traefik v1 gefunden. In diesem Fall wurde Traefik nicht auf v2 aktualisiert.
* K3s Versionen **1.20** und **früher** enthalten Traefik v1.

== Netzwerk Policy Controller

K3s enthält einen integrierten Netzwerkrichtlinien-Controller. Die zugrundeliegende Implementierung ist https://github.com/cloudnativelabs/kube-router['s] kube-router netpol controller library (keine andere kube-router Funktionalität ist vorhanden) und kann gefunden werden https://github.com/k3s-io/k3s/tree/main/pkg/agent/netpol[hier].

Um sie zu deaktivieren, starten Sie jeden Server mit dem Flag `--disable-network-policy`.

[NOTE]
====
Die iptables-Regeln der Netzwerkrichtlinie werden nicht entfernt, wenn die K3s-Konfiguration so geändert wird, dass der Netzwerkrichtlinien-Controller deaktiviert wird. Um die konfigurierten kube-router-Netzwerkrichtlinien nach der Deaktivierung des Netzwerkrichtlinien-Controllers zu bereinigen, verwenden Sie das Skript `k3s-killall.sh`, oder bereinigen Sie sie mit `iptables-save` und `iptables-restore`. Diese Schritte müssen manuell auf allen Knoten des Clusters durchgeführt werden.

----
iptables-save | grep -v KUBE-ROUTER | iptables-restore
ip6tables-save | grep -v KUBE-ROUTER | ip6tables-restore
----
====

[#_service_load_balancer]
== Dienst Load Balancer

Jeder LoadBalancer-Controller kann in Ihrem K3s-Cluster eingesetzt werden. Standardmäßig bietet K3s einen Load Balancer mit der Bezeichnung https://github.com/k3s-io/klipper-lb[ServiceLB] (früher Klipper LoadBalancer), der verfügbare Host-Ports verwendet.

Upstream Kubernetes erlaubt die Erstellung von Diensten des Typs LoadBalancer, enthält aber keine Standard-Load-Balancer-Implementierung, so dass diese Dienste `pending` bleiben, bis einer installiert ist. Für viele gehostete Dienste muss ein Cloud-Anbieter wie Amazon EC2 oder Microsoft Azure eine externe Load-Balancer-Implementierung anbieten. Im Gegensatz dazu ermöglicht der K3s ServiceLB die Nutzung von LoadBalancer Services ohne einen Cloud-Provider oder zusätzliche Konfiguration.

=== So funktioniert ServiceLB

Der ServiceLB-Controller überwacht Kubernetes https://kubernetes.io/docs/concepts/services-networking/service/[Services], wobei das Feld `spec.type` auf `LoadBalancer` gesetzt ist.

Für jeden LoadBalancer Service wird ein link:https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSet] im `kube-system` Namespace erstellt. Dieses DaemonSet erstellt wiederum ServiceLB-Pods mit einem `svc-` -Präfix auf jedem Knoten. Diese Pods nutzen hostPort unter Verwendung des Service-Ports und werden daher nur auf Knoten bereitgestellt, die diesen Port zur Verfügung haben. Wenn keine Knoten mit diesem Anschluss verfügbar sind, bleibt der LB in der Schwebe. Beachten Sie, dass es möglich ist, mehrere Dienste auf demselben Knoten bereitzustellen, solange sie unterschiedliche Ports verwenden.

Wenn der ServiceLB-Pod auf einem Knoten läuft, der eine externe IP konfiguriert hat, wird die externe IP des Knotens mit `ipMode: VIP` in die Adressliste des Dienstes `status.loadBalancer.ingress` eingetragen. Andernfalls wird die interne IP des Knotens verwendet.

Wenn der Verkehr zur externen IP der link:https://en.wikipedia.org/wiki/Network_address_translation[Network Address Translation (NAT)] unterliegt - zum Beispiel in öffentlichen Clouds, wenn die öffentliche IP des Knotens als externe IP verwendet wird - wird der Verkehr über den hostPort in den ServiceLB-Pod geleitet. Der Pod verwendet dann iptables, um den Verkehr an die ClusterIP-Adresse und den Port des Dienstes weiterzuleiten. Wenn der Verkehr nicht NAT unterliegt und stattdessen mit einer Zieladresse ankommt, die mit der LoadBalancer-Adresse übereinstimmt, wird der Verkehr abgefangen (normalerweise durch kube-proxy iptables chains oder ipvs) und an die ClusterIP-Adresse und den Port des Dienstes weitergeleitet.

=== Verwendung

Erstellen Sie einen https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[Dienst vom Typ LoadBalancer] in K3s.

[WARNING]
.Bekanntes Problem
====
Wenn der externe Verkehr den Knoten über ein NAT erreicht (z. B. in öffentlichen Clouds) und Sie `externalTrafficPolicy=local` für Zwecke wie die Erhaltung der Quell-IP des Clients benötigen, definieren Sie bitte nicht die k3s-Konfiguration `node-external-ip` für einen der Knoten, da dies nicht korrekt funktionieren wird.
====

=== Steuerung der ServiceLB-Knotenauswahl

Das Hinzufügen des Labels `svccontroller.k3s.cattle.io/enablelb=true` zu einem oder mehreren Knoten schaltet den ServiceLB-Controller in den Modus "allow-list", in dem nur Knoten mit diesem Label LoadBalancer-Pods hosten können. Knoten, die nicht gekennzeichnet sind, werden von der Nutzung durch ServiceLB ausgeschlossen.

[NOTE]
====
Standardmäßig sind die Knoten nicht beschriftet. Solange alle Knoten nicht beschriftet sind, werden alle Knoten mit verfügbaren Ports von ServiceLB verwendet.
====


=== Erstellen von ServiceLB-Knotenpools

Um eine bestimmte Untergruppe von Knoten auszuwählen, auf denen Pods für einen LoadBalancer gehostet werden sollen, fügen Sie den gewünschten Knoten das Label `enablelb` hinzu und legen Sie auf den Knoten und Diensten passende Werte für das Label `lbpool` fest. Zum Beispiel:

. Beschriften Sie Knoten A und Knoten B mit `svccontroller.k3s.cattle.io/lbpool=pool1` und `svccontroller.k3s.cattle.io/enablelb=true`
. Beschriften Sie Knoten C und Knoten D mit `svccontroller.k3s.cattle.io/lbpool=pool2` und `svccontroller.k3s.cattle.io/enablelb=true`
. Erstellen Sie einen LoadBalancer Service auf Port 443 mit dem Label `svccontroller.k3s.cattle.io/lbpool=pool1`. Das DaemonSet für diesen Dienst stellt nur Pods auf Knoten A und Knoten B bereit.
. Erstellen Sie einen weiteren LoadBalancer Service auf Port 443 mit dem Label `svccontroller.k3s.cattle.io/lbpool=pool2`. Das DaemonSet stellt Pods nur auf Knoten C und Knoten D bereit.

=== Deaktivieren von ServiceLB

Um ServiceLB zu deaktivieren, konfigurieren Sie alle Server im Cluster mit dem Flag `--disable=servicelb`.

Dies ist notwendig, wenn Sie eine andere LB, wie z. B. MetalLB, verwenden möchten.

== Einsatz eines externen Cloud Controller Managers

K3s bietet einen eingebetteten Cloud Controller Manager (CCM), der die folgenden Aufgaben erfüllt:

* Hostet den <<_service_load_balancer, Service Load Balancer>> LoadBalancer-Controller.
* Beseitigt den `node.cloudprovider.kubernetes.io/uninitialized` Makel.
* Setzt Knotenadressfelder basierend auf den Flags `--node-ip`, `--node-external-ip`, `--node-internal-dns` und `--node-external-dns`.

Bevor Sie einen externen CCM einsetzen, müssen Sie alle K3s-Server mit dem Flag `--disable-cloud-controller` starten, um den eingebetteten CCM zu deaktivieren. Bei Verwendung eines externen CCM werden die Knotenadressen von den Instanz-Metadaten-APIs des Cloud-Anbieters bereitgestellt und nicht von den K3-Flag-Werten.

[NOTE]
====
Wenn Sie den eingebauten CCM deaktivieren und keinen externen Ersatz einsetzen und ordnungsgemäß konfigurieren, bleiben die Knoten beschädigt und können nicht bereinigt werden.
====

