include::partial$variables.adoc[]
= Erstellen und Ausführen einer OPA-Richtlinie für {short-project-name}
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erstellen Sie eine benutzerdefinierte OPA-Richtlinie für Ihr Projekt, indem Sie ein Rego-Richtlinienpaket erstellen, es in ein WASM-Ziel kompilieren und mit kwctl integrieren.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "build-and-run"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "build and run", "open policy agent", "opa", "rego"]
:current-version: {page-origin-branch}

Im vorigen Abschnitt haben Sie Ihre Rego-Police geschrieben.
Die Struktur sieht wie folgt aus:

[subs="+attributes",console]
----
.
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
└── request.rego

1 directory, 4 files
----

== Bauen Sie

Zum Bauen:

[subs="+attributes",console]
----
$ opa build -t wasm -e policy/main policy.rego request.rego
----

Dies bildet die Rego-Politik, mit:

* `target`: `wasm`.
Sie möchten die Richtlinie für das Ziel `wasm` erstellen.
* `entrypoint`: `policy/main`.
Der Einstiegspunkt ist die Regel `main` innerhalb des Pakets `policy`.
* `policy.rego`:
Erstellen Sie die Datei `policy.rego` und binden Sie sie ein.
* `request.rego`:
Erstellen Sie die Datei `request.rego` und binden Sie sie ein.

Nach Abschluss des Builds hat `opa build` eine Datei `bundle.tar.gz` erstellt.
Sie können es extrahieren:

[subs="+attributes",console]
----
$ tar -xf bundle.tar.gz /policy.wasm
----

Der Baum sieht nun wie folgt aus:

[subs="+attributes",console]
----
.
├── bundle.tar.gz
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
├── policy.wasm
└── request.rego

1 directory, 6 file
----

Sie haben Ihre `policy.wasm` Datei:

[subs="+attributes",console]
----
$ file policy.wasm
policy.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
----

Jetzt führen Sie es aus.

== ausführen.

Verwenden Sie `kwctl`, um die Richtlinie auszuführen:

[subs="+attributes",console]
----
$ kwctl run -e opa --request-path data/other-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": true
}
----

Diese Anfrage wird von der Richtlinie akzeptiert, da es sich um die Anfrage handelt, die auf den Namespace `other` verweist.

* `execution-mode`: `opa`.
Rego-Richtlinien können auf Open Policy Agent oder Gatekeeper ausgerichtet sein.
Sie müssen `kwctl` mitteilen, welche Art von Politik Sie betreiben.
* `request-path`:
Der Ort der aufgezeichneten Anfrage, an den `kwctl` die Richtlinie zur Bewertung sendet.

Versuchen Sie nun, die Anfrage auszuwerten, die den Pod im Namespace `default` erstellt:

[subs="+attributes",console]
----
$ kwctl run -e opa --request-path data/default-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "it is forbidden to use the default namespace"
  }
}
----

Die Richtlinie lehnt die Anfrage ab und gibt einen Grund an den API-Server zurück, der an den Benutzer oder API-Konsumenten zurückgegeben wird.
