include::partial$variables.adoc[]
= Paramètres de la politique
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configurer les paramètres de la politique en utilisant {project-name} pour la validation et la sérialisation des données de la politique.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "settings"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "policy specification", "policy settings"]
:sidebar_label: Paramètres de la politique
:current-version: {page-origin-branch}

Le comportement de la politique n'est pas rigide, vous pouvez le configurer en fournissant des détails de configuration à la politique au moment de l'exécution. L'auteur de la politique a la liberté de définir la structure des paramètres de la politique.

{project-name} se charge de sérialiser les paramètres de la politique en JSON et les fournit à la politique à chaque fois qu'elle est invoquée.

== Validation des paramètres

Les politiques doivent valider les paramètres fournis par un utilisateur afin d'en vérifier l'exactitude.

Chaque politique enregistre une fonction waPC appelée `validate_settings` qui valide les paramètres de la politique.

La fonction `validate_settings` reçoit en entrée une représentation JSON des paramètres fournis par l'utilisateur. Cette fonction les valide et renvoie en réponse un objet `SettingsValidationResponse`.

La structure de l'objet `SettingsValidationResponse` est la suivante

[subs="+attributes",yaml]
----
{
  # mandatory
  "valid": <boolean>,

  # optional, ignored if accepted - recommended for rejections
  "message": <string>,
}
----

Si les paramètres fournis par l'utilisateur sont `valid`, `validate_settings` ignore le contenu de`message`. Sinon, `validate_settings` affiche le contenu de `message`.

[NOTE]
====

{short-project-name}Le https://github.com/chimera-kube/policy-server[serveur de politiques de]valide tous les paramètres de politiques fournis par les utilisateurs au moment du démarrage. Le serveur de politiques sort immédiatement avec une erreur si au moins une de ses politiques a reçu des paramètres de configuration erronés.

====


== Exemple

Prenons l'exemple de la politiquehttps://github.com/kubewarden/psp-capabilities[psp-capabilities], dont le format de configuration est le suivant :

[subs="+attributes",yaml]
----
allowed_capabilities:
- CHOWN

required_drop_capabilities:
- NET_ADMIN

default_add_capabilities:
- KILL
----

La fonction `validate_settings` reçoit en entrée le document JSON suivant :

[subs="+attributes",json]
----
{
  "allowed_capabilities": [
    "CHOWN"
  ],
  "required_drop_capabilities": [
    "NET_ADMIN"
  ],
  "default_add_capabilities": [
    "KILL"
  ]
}
----

== Récapitulation

Chaque politique doit enregistrer une fonction waPC, `validate_settings`.
