include::partial$variables.adoc[]
= 变异政策
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 通过在 waPC（whatever-after Policy Configurator）中实施验证函数（validation 和 validate_settings）来配置突变策略，以便在 Kubernetes 集群中提出对象突变。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "mutating-policies"]
:doc-type: ["reference"]
:keywords: ["kubewarden"、"kubernetes"、"策略规范"、"突变策略"]
:sidebar_label: 变异政策
:current-version: {page-origin-branch}

变异策略的结构与验证策略相同：

* 他们必须注册`+validate+` 和`+validate_settings+` waPC 功能。
* 主机与策略之间使用的通信 API 与验证策略使用的 API 相同。

变异策略接受一个请求，并可以通过返回一个类似`+ValidationResponse+` 的对象对接收到的对象进行变异：

[subs="+attributes",json]
----
{
  "accepted": true,
  "mutated_object": <object to be created>
}
----

`+mutated_object+` 字段包含策略希望在 Kubernetes 集群中创建的对象，已序列化为 JSON 格式。

== 一个具体例子

假定保单收到此`+ValidationRequest+` ：

[subs="+attributes",json]
----
{
  "settings": {},
  "request": {
    "operation": "CREATE",
    "object": {
      "apiVersion": "v1",
      "kind": "Pod",
      "metadata": {
        "name": "security-context-demo-4"
      },
      "spec": {
        "containers": [
        {
          "name": "sec-ctx-4",
          "image": "gcr.io/google-samples/node-hello:1.0",
          "securityContext": {
            "capabilities": {
              "add": ["NET_ADMIN", "SYS_TIME"]
            }
          }
        }
        ]
      }
    }
  }
}
----

[NOTE]
====

本例中`+request+` 对象只包含重要字段。

====


之所以会产生这种请求，是因为有人试图创建一个看起来像这样的 Pod：

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
----

假设政策回复如下`+ValidationResponse+` ：

[subs="+attributes",json]
----
{
  "accepted": true,
  "mutated_object": {
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
      "name": "security-context-demo-4"
    },
    "spec": {
      "containers": [
        {
          "name": "sec-ctx-4",
          "image": "gcr.io/google-samples/node-hello:1.0",
          "securityContext": {
            "capabilities": {
              "add": [
                "NET_ADMIN",
                "SYS_TIME"
              ],
              "drop": [
                "BPF"
              ]
            }
          }
        }
      ]
    }
  }
}
----

这将导致请求被接受，但最终的 Pod 会是这样的：

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
        drop:
        - BPF
----

如您所见，该策略更改了 Pod 中声明的唯一容器的`+securityContext.capabilities.drop+`部分。

由于政策原因，容器现在放弃了`+BPF+` 功能。

== 回顾

这些都是变异策略必须实现的功能：

|===
| *waPC 功能名称*| *输入有效载荷*| *输出有效载荷*

| `+validate+`
| `+\{  "request": \{    // AdmissionReview.request data  \},  "settings": \{    // your policy configuration  \}\}+`
| `+\{  **// mandatory**  "accepted": boolean,  // optional, ignored if accepted  // recommended for rejections  "message": string,  // optional, ignored if accepted  "code": integer,   // JSON Object to be created  // Can be used only when the  // request is accepted  "mutated_object": object\}+`

| `+validate_settings+`
| `+\{  // your policy configuration\}+`
| `+\{  **// mandatory**  "validate": boolean,  // optional, ignored if accepted  // recommended for rejections  "message": string,\}+`
|===
