= MachineInventorySelectorTemplate reference
:revdate: 2025-09-08
:page-revdate: {revdate}

MachineInventorySelectorTemplate は、必要なxref:references/machineinventoryselector-reference.adoc[MachineInventorySelector を]作成するためのブループリントとして使用される、ユーザー定義のリソースです。

これは、インベントリに登録されたマシンとクラスターリソースをペアリングするためのマッチング基準を定義する責任を負うリソースです。

関連するキーは、ラベルセレクタ式を含む`selector` 。

.MachineInventorySelectorTemplate
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: my-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        ...
----

`template.spec.selector` には、`matchLabels` および`matchExpressions` のキーを含めることができる。

== `template.spec.selector.matchLabels`

これは`{key,value}` ペア`(map[string]string)` のマップである。複数のラベルが提供された場合、すべてのラベルが一致しなければならない。

.詳細はこちら
[%collapsible]
====
[yaml]
----
...
spec: template: spec: selector: matchLabels: element: fire manufacturer: somevalue
----
====

上記のセレクタで定義されたクラスタは、これら2つのラベルを含むインベントリのノードにのみプロビジョニングを試みます。

== `template.spec.selector.matchExpressions`

これはラベルセレクタのリストで、各ラベルセレクタは次のように定義できる：

|===
| キー | タイプ | 説明

| キー
| ストリング
| これはセレクタが適用されるラベルキーです。

| オペレーター
| ストリング
| キーと値のセットとの関係を表す。有効な演算子は 'In'、'NotIn'、'Exists'、'DoesNotExist' です。

| 価値観
| [文字列
| Valuesは文字列の配列です。演算子が 'In' または 'NotIn' の場合、 値の配列は空であってはならない。演算子が 'Exists' または 'DoesNotExist' の場合、 値の配列は空でなければならない。
|===

.詳細はこちら
[%collapsible]
====
[,yaml]
----
...
spec:
  template:
    spec:
      selector:
        matchExpressions:
        - key: element
          operator: In
          values: [ 'fire' ]
        - key: manufacturer
          operator: Exists
----
====

上記のセレクタで定義されたクラスタは、`element=fire` ラベルでインベントリ化され、任意の値で定義された`manufacturer` ラベルを含むノードにのみプロビジョニングを試みます。
