= Clúster híbrido o multicloud distribuido
:page-languages: [en, ja, ko, zh]
:revdate: 2025-05-26
:page-revdate: {revdate}

Un clúster K3s puede seguir desplegándose en nodos que no comparten una red privada común y no están conectados directamente (por ejemplo, nodos en diferentes nubes públicas). Hay dos opciones para conseguirlo: la solución integrada k3s multicloud y la integración con el proveedor de VPN `tailscale`.

[CAUTION]
====
La latencia entre nodos aumentará a medida que la conectividad externa requiera más saltos. Esto reducirá el rendimiento de la red y también podría afectar a la salud del clúster si la latencia es demasiado alta.
====


[CAUTION]
====
El etcd incrustado no es compatible con este tipo de despliegue. Si se utiliza etcd incrustado, todos los nodos del servidor deben ser accesibles entre sí a través de sus IPs privadas. Los agentes pueden estar distribuidos en varias redes, pero todos los servidores deben estar en la misma ubicación.
====


== Solución integrada k3s multicloud

K3s utiliza wireguard para establecer una malla VPN para el tráfico del clúster. Los nodos deben tener cada uno una IP única a través de la cual se pueda acceder a ellos (normalmente una IP pública). El tráfico del supervisor K3s utilizará un túnel websocket, y el tráfico del cluster (CNI) utilizará un túnel wireguard.

Para habilitar este tipo de despliegue, debe añadir los siguientes parámetros en los servidores:

[,bash]
----
--node-external-ip=<SERVER_EXTERNAL_IP> --flannel-backend=wireguard-native --flannel-external-ip
----

y en los agentes:

[,bash]
----
--node-external-ip=<AGENT_EXTERNAL_IP>
----

donde `SERVER_EXTERNAL_IP` es la IP a través de la cual podemos llegar al nodo servidor y `AGENT_EXTERNAL_IP` es la IP a través de la cual podemos llegar al nodo agente. Tenga en cuenta que el parámetro `K3S_URL` config en el agente debe utilizar el `SERVER_EXTERNAL_IP` para poder conectarse a él. Recuerde comprobar los xref:installation/requirements.adoc#_networking[requisitos de red] y permitir el acceso a los puertos de la lista tanto en direcciones internas como externas.

Tanto `SERVER_EXTERNAL_IP` como `AGENT_EXTERNAL_IP` deben tener conectividad entre ellas y normalmente son IP públicas.

[IMPORTANT]
.IP dinámicas
====
Si se asignan IP dinámicas a los nodos y la IP cambia (por ejemplo, en AWS), debe modificar el parámetro `--node-external-ip` para reflejar la nueva IP. Si ejecuta K3s como servicio, debe modificar `/etc/systemd/system/k3s.service` y luego ejecutarlo:

[,bash]
----
systemctl daemon-reload
systemctl restart k3s
----
====

[#_integration_with_the_tailscale_vpn_provider_experimental]
== Integración con el proveedor de VPN Tailscale (experimental)

Disponible en v1.27.3, v1.26.6, v1.25.11 y posteriores.

K3s puede integrarse con https://tailscale.com/[] Tailscale para que los nodos utilicen el servicio VPN de Tailscale para construir una malla entre nodos.

Hay que seguir cuatro pasos con Tailscale antes de desplegar los K3:

. Accede a tu cuenta Tailscale
. En `Settings > Keys`, genere una clave de autenticación ($AUTH-KEY), que puede ser reutilizable para todos los nodos de su cluster.
. Decida el podCIDR que utilizará el cluster (por defecto `10.42.0.0/16`). Añada el CIDR (o CIDRs para dual-stack) en Controles de acceso con la stanza:
+
[,yaml]
----
"autoApprovers": {
     "routes": {
         "10.42.0.0/16":        ["your_account@xyz.com"],
         "2001:cafe:42::/56": ["your_account@xyz.com"],
     },
 },
----

. Instala Tailscale en tus nodos:
+
[,bash]
----
curl -fsSL https://tailscale.com/install.sh | sh
----

Para desplegar K3s con la integración Tailscale activada, debes añadir el siguiente parámetro en cada uno de tus nodos:

[,bash]
----
--vpn-auth="name=tailscale,joinKey=$AUTH-KEY"
----

o proporcionar esa información en un archivo y utilizar el parámetro:

[,bash]
----
--vpn-auth-file=$PATH_TO_FILE
----

Opcionalmente, si tienes tu propio servidor Tailscale (por ejemplo headscale), puedes conectarte a él añadiendo `,controlServerURL=$URL` a los parámetros vpn-auth

A continuación, puede proceder a crear el servidor utilizando el siguiente comando:

[,bash]
----
k3s server --token <token> --vpn-auth="name=tailscale,joinKey=<joinKey>" --node-external-ip=<TailscaleIPOfServerNode>
----

Tras ejecutar este comando, accede a la consola de administración de Tailscale para aprobar el nodo y la subred de Tailscale (si no han sido ya aprobados a través de autoApprovers). 

Una vez configurado el servidor, conecte los agentes mediante:

[,bash]
----
k3s agent --token <token> --vpn-auth="name=tailscale,joinKey=<joinKey>" --server https://<TailscaleIPOfServerNode>:6443 --node-external-ip=<TailscaleIPOfAgentNode>
----

De nuevo, aprueba el nodo Tailscale y la subred como hiciste para el servidor.

Si tiene ACLs activadas en Tailscale, necesita añadir una regla "accept" para permitir que los pods se comuniquen entre sí. Suponiendo que la clave de autenticación que has creado etiquete automáticamente los nodos Tailscale con la etiqueta `testing-k3s`, la regla debería tener este aspecto:

[,yaml]
----
"acls": [
    {
        "action": "accept",
        "src":    ["tag:testing-k3s", "10.42.0.0/16"],
        "dst":    ["tag:testing-k3s:*", "10.42.0.0/16:*"],
    },
],
----

[CAUTION]
====
Si tiene previsto ejecutar varios clústeres K3s utilizando la misma red tailscale, cree las adecuadas https://tailscale.com/kb/1018/acls/[ACL] para evitar conflictos de IP o utilice subredes podCIDR diferentes para cada clúster.
====
