= Página de análisis
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

La página Analytics proporciona una interfaz potente y flexible para consultar y analizar sus datos de observabilidad mediante xref:/develop/reference/k8sTs-stql_reference.adoc[consultas STQL].
Este entorno interactivo le permite ir más allá de los cuadros de mando predefinidos y obtener información más detallada sobre el estado, el rendimiento y las dependencias de su entorno dinámico.

[CAUTION]
====
*La página Analytics está obsoleta, pero aún puede habilitarla configurando permisos específicos. Sin embargo, recomendamos encarecidamente aprovechar los StackPacks para mejorar la observabilidad y el análisis, ya que ofrecen una alternativa más sólida y activamente respaldada.*

Se requieren dos permisos para habilitar la Página de Análisis:

* `+access-analytics+`
* `+execute-scripts+`

Más información: xref:/setup/security/rbac/rbac_permissions.adoc[Gestión de permisos]

====

