= Cómo incluir archivos cloud-config desde dispositivos extraíbles
:revdate: 2025-09-08
:page-revdate: {revdate}

{elemental-product-name} nodos admite la carga de archivos xref:references/cloud-config-reference.adoc[cloud-config] desde dispositivos de bloque específicos.
En concreto, admite la carga de archivos cloud-config desde una ISO que tenga `CIDATA` como ID de volumen o cualquier dispositivo con formato vFAT etiquetado con `CIDATA`. Si se encuentra un dispositivo que coincida con estos criterios en el arranque temprano, el cliente {elemental-product-name} lo leerá y buscará un archivo `user-data` en su raíz.

Como ejemplo, se puede crear una ISO que incluya un archivo cloud-config en un host Linux con el procedimiento que se indica a continuación.

Cree un archivo `user-data` con los datos de configuración de la nube. En el ejemplo de abajo sólo establecemos un proxy:

.user-data
[,yaml]
----
#cloud-config
write_files:

* path: /etc/sysconfig/proxy
append: true
content: |
  PROXY_ENABLED="yes"
  HTTP_PROXY=http://some.domain.org:8080
  HTTPS_PROXY=https://some.domain.org:8080
  NO_PROXY="localhost, 127.0.0.1"
----

Una vez que exista el archivo `user-data` cree una ISO que incluya sólo este archivo utilizando la utilidad `mkisofs` Linux:

[,bash]
----
mkisof -o cidata.iso -V CIDATA -J -r user-data
----

El resultado es una ISO etiquetada con `CIDATA` que incluye el archivo `user-data`.

En el arranque, el archivo `user-data` se copiará tal cual en `/oem/user-data` y, en caso de que contenga datos de configuración de la nube, se añadirá una copia adicional como `/oem/user-data.yaml`. El archivo `/oem/user-data.yaml` será analizado en cualquier etapa posterior de cloud-init.

Dado que los datos se copian en `/oem`, serán persistentes, por lo que en los siguientes reinicios ya no será necesario que esté presente el dispositivo extraíble. Si sigue presente en los siguientes reinicios, simplemente sobrescribe los datos preexistentes.

== Incluir datos no configurados en la nube

Si `user-data` no contiene datos de configuración de la nube, el cliente {elemental-product-name} se limitará a copiarlos tal cual en `/oem/user-data`. Sólo se analizan los archivos `*.yaml` cuando se ejecutan las etapas de cloud-init, por lo que en ese caso el archivo será ignorado por los servicios de cloud-init.

Si `user-data` contiene un script, el cliente {elemental-product-name} intentará, además, ejecutarlo. La forma en que el cliente{elemental-product-name} determina si `user-data` es un script o no es por la presencia de un _Shebang_ en la primera línea. Por ejemplo, el archivo `user-data` anterior podría reescribirse como:

.user-data
[,bash]
----
#!/bin/bash

cat <<EOF >> /etc/sysconfig/proxy
PROXY_ENABLED="yes"
HTTP_PROXY=http://some.domain.org:8080
HTTPS_PROXY=https://some.domain.org:8080
NO_PROXY="localhost, 127.0.0.1"
EOF
----
