= Fournisseur CAPI
:revdate: 2025-08-25
:page-revdate: {revdate}

La ressource `CAPIProvider` permet de gérer les manifestes de l'opérateur de l'API de cluster de manière déclarative. Il est utilisé pour provisionner et configurer les fournisseurs d'API de cluster comme AWS, vSphere, etc.

`CAPIProvider` suit un modèle GitOps - les champs de spécification sont des entrées déclaratives de l'utilisateur. Le contrôleur ne fait que mettre à jour le statut.

Tous les champs fournis par la ressource `CAPIProviderSpec` de l'opérateur CAPI en amont sont également disponibles dans la spécification de la ressource `CAPIProvider`. N'hésitez pas à consulter les configuration en amont link:https://cluster-api-operator.sigs.k8s.io/03_topics/02_configuration/05_provider-spec-configuration[guides de] pour les scénarios avancés.

Tous les fournisseurs CAPI xref:../overview/certified.adoc[certifiés] sont configurés à l'aide d'une configuration intégrée. Pour le remplacer, il faut créer un xref:./clusterctlconfig.adoc#_override_a_certified_provider_version[ClusterctlConfig] personnalisé.

== Utilisation

Pour utiliser la ressource `CAPIProvider`:

. Créez une ressource `CAPIProvider` avec le nom, le type, les informations d'identification, la configuration et les caractéristiques du fournisseur souhaité.
. Le contrôleur `CAPIProvider` s'occupera de la mise en forme des manifestes Cluster API Operator requis, sur la base de la spécification `CAPIProvider`.
. Le champ "status" de la ressource `CAPIProvider` reflète l'état des manifestes générés.
. Gérer l'objet `CAPIProvider` de manière déclarative pour appliquer les changements aux manifestes de fournisseurs générés.

Voici un exemple de manifeste `CAPIProvider`:

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws-infra
  namespace: capi-providers
spec:
  name: aws
  type: infrastructure
  enableAutomaticUpdate: true
  credentials:
    rancherCloudCredential: aws-creds # Rancher credentials secret for AWS
  configSecret:
    name: aws-config
  features:
    clusterResourceSet: true
----

Cela générera un fournisseur d'infrastructure AWS avec le mappage fourni pour le secret d'authentification Rancher et les fonctions personnalisées activées.

Le contrôleur `CAPIProvider` possède toutes les ressources du fournisseur générées, ce qui permet de supprimer l'objet `CAPIProvider`.

== Spécifications

Les champs clés de la spécification `CAPIProvider` sont les suivants :

* `name` - Nom du fournisseur (aws, vsphere, etc.). Héritée de `metadata.name` si elle n'est pas spécifiée.
* `type` - Type de ressource du fournisseur (peut être défini comme `core`, `controlPlane`, `bootstrap`, `infrastructure`, `addon`, `ipam` ou `runtimeextension`).
* `credentials` - Références de la source pour la spécification du fournisseur.
* `configSecret` - Nom du secret de configuration du fournisseur, dans lequel les variables et les informations d'identification synchronisées seront stockées. Par défaut, s'il n'est pas spécifié, il hérite du nom de la ressource `CAPIProvider`.
* `features` - Fonctionnalités du fournisseur activées.
* `variables` - Variables est une carte des variables d'environnement à ajouter au contenu du site `configSecret`.
* `version` - Version indique la version du fournisseur.
* `enableAutomaticUpdate` - Autoriser la mise à jour automatique du fournisseur. Activé par défaut uniquement sur les fournisseurs installés dans les chartes des tortues.
* `fetchConfig` - FetchConfig détermine comment l'opérateur va récupérer les composants et les métadonnées du fournisseur.
** `oci` - OCI à utiliser pour récupérer les composants et les métadonnées du fournisseur à partir d'un artefact OCI. Vous devez définir le champ `providerSpec.Version` pour que l'opérateur puisse récupérer la version souhaitée sur GitHub. Si le providerSpec.Version est manquant, la dernière version du provider provenant des valeurs par défaut de clusterctl est utilisée.
** `selector` - Sélecteur à utiliser pour récupérer les composants et les métadonnées du fournisseur à partir des ConfigMaps stockés dans le cluster. Chaque ConfigMap est censé contenir des composants et des métadonnées pour une version spécifique uniquement.
** `url` - URL à utiliser pour récupérer les composants et les métadonnées du fournisseur à partir d'un dépôt Github distant.

== Épinglage des versions et mises à jour automatiques

Le site `CAPIProvider` `version` peut être défini à tout moment pour rattacher le fournisseur à une version spécifique. En outre, `automaticUpdates` peut être activé pour permettre des mises à jour automatiques vers la dernière version disponible. La dernière version disponible est déterminée par la configuration clusterctl intégrée pour les fournisseurs xref:../overview/certified.adoc[certifiés], et elle peut être remplacée ou configurée pour les fournisseurs personnalisés à l'aide de xref:../reference/clusterctlconfig.adoc[ClusterctlConfig].

== Suppression

Lorsqu'une ressource `CAPIProvider` est supprimée, le garbage collection de Kubernetes nettoie toutes les ressources fournisseurs générées qui lui appartiennent. Il s'agit notamment de

* Instance de ressources de l'opérateur API de cluster
* Secret référencé par le `configSecret`
