include::partial$variables.adoc[]
= 内蔵サポート
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: WebAssemblyモジュールで利用可能な組み込み関数を決定し、その実装とRegoポリシー開発での使用を理解する。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "built-in-support"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"ビルトインwasmサポート"]]。
:sidebar_label: 内蔵サポート
:current-version: {page-origin-branch}

さらに、`wasm` 。

オープン・ポリシー・エージェント（OPA）チームには、https://www.openpolicyagent.org/docs/latest/policy-reference/#built-in-functions[のビルトインサポートを]確認できるページがあります。

Rego ポリシーを WebAssembly モジュールにビルドする場合、これらの組み込み関数の一部は Wasm ファイル自体にあります。
リンク先のビルトインページで緑色のチェックマークがついているビルトインだ。
モジュールを評価するWebAssemblyランタイムは、その他を提供する。

`SDK-dependent` とマークされたビルトインは、ホストが実装しなければならないもので、この場合は{project-name} 。
OPAおよびゲートキーパーは、ポリシーのニーズに応じてこれらを使用することができる。
いずれにせよ、これらのビルトインはポリシーに公開され、新規または既存のポリシーはこれらに依存する可能性がある。

{short-project-name} 、まだ提供されていないビルドインがいくつかあるが、オープンな場で見られるポリシーに基づけば、すでにサポートされているものでほとんどのKubernetesユーザーには十分だろう。

https://github.com/kubewarden/policy-evaluator/issues/56[このGitHub issueは]、まだ実装していないRegoのビルトインを記録しています。
私たちの仕事に優先順位をつけるために、お気軽にコメントをお寄せください。

== ビルドインが欠落しているポリシーの実行

ポリシーが`kwctl` または`policy-server` で実行されるとき、ポリシーによって使用されるビルドインのリストが検査されます。
使用されているビルドインのいずれかが欠落している場合、プログラムは実行を停止し、欠落しているビルドインを報告する致命的なエラーを記録する。
