= Dépannage de la restauration
:revdate: 2025-07-03
:page-revdate: {revdate}

[WARNING]
====
Lorsqu'une restauration est effectuée, ne redémarrez pas le site `+rancher-system-agent+` sur les nœuds élémentaires, car il risque d'être périmé et de provoquer l'erreur suivante :

`+panic: error while connecting to Kubernetes cluster: the server has asked for the client to provide credentials+`

Si vous rencontrez ce problème, veuillez suivre la procédure ci-dessous.
====


Avant de lancer une restauration, vous devez copier `+/var/lib/rancher/agent/rancher2_connection_info.json+` depuis le nœud élémentaire vers un endroit auquel vous avez accès avec l'interface utilisateur de Rancher.

Une fois le fichier copié, téléchargez le script `+rancher-agent-token-update.sh+` à partir du https://github.com/rancher/elemental[dépôt]

[,shell]
----
wget -q https://raw.githubusercontent.com/rancher/elemental/main/scripts/rancher-agent-token-update && chmod +x rancher-agent-token-update
----

Exécute le script sans aucune option supplémentaire :

[,shell]
----
./rancher-agent-token-update
----

Une fois la restauration effectuée avec succès, copiez `+rancher2_connection_info.json+` vers le nœud élémentaire sur le chemin`+/var/lib/rancher/agent/rancher2_connection_info.json+`. Enfin, redémarrez le service `+rancher-system-agent+`:

[,shell]
----
systemctl restart rancher-system-agent
----
