= Übersicht Etikettenvorlagen
:revdate: 2025-09-08
:page-revdate: {revdate}

Elemental ermöglicht die Angabe von _Etikettenvorlagen_ in den Abschnitten `spec.machineInventoryLabels` und `spec.machineInventoryAnnotations` der xref:references/machineregistration-reference.adoc[MachineRegistration-Ressourcen].

Ihr Format ist das kanonische `key`:``value``, das in Kubernetes-Labels und -Anmerkungen verwendet wird.

Diese Beschriftungsvorlagen werden in tatsächliche Beschriftungen und Anmerkungen umgewandelt, die an jede xref:references/machineinventory-reference.adoc[MachineInventory-Ressource] angehängt werden, die während der xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[Onboarding-Phase der Maschine] erstellt wird.

Die resultierenden Beschriftungen und Anmerkungen haben die gleiche `key` der Beschriftungsvorlage.

Die zugehörige `value` wird erstellt:

* *die Darstellung der <<_label_templates_variables,`label template variables`>>* (falls vorhanden)
* *`sanitizing`* den sich daraus ergebenden Wert (nur im Falle der Etiketten)

[IMPORTANT]
====
Die Elemental Templating-Funktionalität umfasst auch das Feld xref:references/machineregistration-reference.adoc[MachineRegistration] `spec.machineName`, das den resultierenden Hostnamen der registrierenden Maschine und die `name` der zugehörigen xref:references/machineinventory-reference.adoc[MachineInventory-Ressource] definiert.

Weitere Informationen finden Sie im Abschnitt <<_custom_machine_names,Maschinenname>>.
====


== Variablen der Etikettenvorlagen

Elemental Label Templating enthält eine Reihe von vordefinierten Variablen, die innerhalb der `value` der in der xref:references/machineregistration-reference.adoc[MachineRegistration] angegebenen _Etikettenvorlagen_ verwendet werden können.

Die Syntax zur Angabe der Variablen von Etikettenvorlagen lautet:

`${ _VARFAMILY_ \/ _VARPATH_ }`

wobei _VARFAMILY_ eine Gruppe (Familie) von unterstützten Variablen definiert und _VARPATH_ den tatsächlichen Variablennamen innerhalb der zugehörigen Familiengruppe angibt.

Elemental unterstützt derzeit die folgenden _Template-Variablenfamilien_:

* xref:label-templates/label-templates-bios.adoc[*BIOS*]*${ BIOS \/* _VARPATH_ *}*
* xref:label-templates/label-templates-baseboard.adoc[*BaseBoard*]: *${ BaseBoard \/* _VARPATH_ *}*
* xref:label-templates/label-templates-cpu.adoc[*CPU*]*${ CPU \/* _VARPATH_ *}*
* xref:label-templates/label-templates-chassis.adoc[*Fahrgestell*]*Fahrgestell: ${ Fahrgestell \/* _VARPATH_ *}*
* xref:label-templates/label-templates-gpu.adoc[*GPU*]*${ GPU \/* _VARPATH_ *}*
* xref:label-templates/label-templates-memory.adoc[*Speicher*]: *${ Speicher \/* _VARPATH_ *}*
* xref:label-templates/label-templates-network.adoc[*Netzwerk*]: *${ Netzwerk \/* _VARPATH_ *}*
* xref:label-templates/label-templates-product.adoc[*Produkt*]: *${ Produkt \/* _VARPATH_ *}*
* xref:label-templates/label-templates-runtime.adoc[*Laufzeit*]: *${ Runtime \/* _VARPATH_ *}*
* xref:label-templates/label-templates-storage.adoc[*Lagerung*]: *${ Storage \/* _VARPATH_ *}*

[CAUTION]
====
Alle _Vorlagenvariablenfamilien_ (außer _`Random`_) sind nur aktiviert, wenn das Feld `elemental.registration.no-smbios` von xref:references/machineregistration-reference.adoc[MachineRegistration] auf `false` gesetzt ist (Standard).

Wenn das Feld `elemental.registration.no-smbios` auf `true` gesetzt ist, senden die registrierenden Rechner keine Daten, die für die Darstellung der Vorlagenvariablen erforderlich sind. Es sind also keine Variablen verfügbar, außer den *Zufallsvariablen*, die die einzige nennenswerte Ausnahme darstellen.

*Zufallsvariablen* sind immer verfügbar, da sie auf der Betreiberseite eingebaut sind. Sie sind auch etwas Besonderes, da sie nur einmal berechnet werden: siehe den Abschnitt xref:label-templates/label-templates-random.adoc[Zufallsvariablen für Vorlagen] für weitere Einzelheiten.
====


Schablonenvariablen können mit statischem Text gemischt werden, um die eigentlichen Beschriftungen zu bilden, die denxref:references/machineinventory-reference.adoc[(MachineInventories]) zugewiesen werden.

[NOTE]
.Rendering-Beispiele
====

* Label-Vorlage zur Verfolgung der Anzahl der CPU-Kerne des registrierenden Hosts (angenommen, der Host hat 4 Kerne):
 ** ursprüngliche Bezeichnung: *cpu: ${CPU\/TotalCores}* -cores
 ** gerendertes Etikett: *cpu: 4-Kern*
* Etikettenvorlage, die die SMBIOS UUID des registrierenden Hosts verfolgt:
 ** ursprüngliche Bezeichnung: *sbios-UUID: ${Product\/UUID}*
 ** rendered label: *sbios-UUID: fd95324a-c26b-4e28-8727-1dcec293a0ec*
====


== Desinfektion

Nachdem der Wert der Etikettenvorlage entsprechend den enthaltenen <<_label_templates_variables,Variablen der Etikettenvorlage>> gerendert wurde, wird der resultierende Wert unter `sanitized` angezeigt, bevor er dem resultierenden Etikett zugewiesen wird.

* `sanitization` erzwingt, dass der Etikettenwert nur Buchstaben (groß oder nicht groß geschrieben), Zahlen und die Zeichen Bindestrich (`-`), Punkt (`.`) und Unterstrich (`_`) enthält*:

Alle Zeichen, die nicht enthalten sind, werden durch einen Bindestrich ersetzt.

Jedes Zeichen am Anfang und am Ende des Etikettenwertes muss ein Buchstabe oder eine Zahl sein. Ist dies nicht der Fall, wird sie fallen gelassen.

Zwei aufeinanderfolgende Bindestriche werden durch einen ersetzt.

[NOTE]
.Rendering-Beispiel
====

* Etikettenvorlage mit Bereinigung von verbotenen Zeichen:
 ** Original-Etikett: *gereinigt: dies:muss--gereinigt werden!*
 ** gerenderte Kennzeichnung: *sanitized: this-needs-sanitizing*
====


== Verwendung von Etikettenvorlagen

Etikettenvorlagen ermöglichen das automatische Anbringen und Aktualisieren von Etiketten und Anmerkungen zum xref:references/machineinventory-reference.adoc[MachineInventory] eines jeden Hosts, sobald sich dieser bei Elemental Operator registriert.

[IMPORTANT]
====
Die Registrierung erfolgt nicht nur während der xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[Einführungsphase]: Jeder Host registriert sich alle 30 Minuten (und bei jedem Neustart) neu. Bei der Neuregistrierung werden die Etikettenvorlagen in der zugehörigen xref:references/machineregistration-reference.adoc[Maschinenregistrierung] neu bewertet und in das xref:references/machineinventory-reference.adoc[Maschineninventar] aufgenommen/aktualisiert.
====


Es gibt im Wesentlichen drei Fälle, in denen die Etikettenvorlagen von Nutzen sein können:

* um Hardware-Daten an den Elementarkatalog anzuhängen.
* um Selektoren für die Auswahl von Hosts für die Clusterbereitstellung hinzuzufügen.
* um eine benutzerdefinierte Vorlage für die Maschinennamen zu definieren.

=== Hardware-Daten für den Elemental-Katalog

Die Variablen der Etikettenvorlagen können verwendet werden, um Hardwaredaten an jede xref:references/machineinventory-reference.adoc[MachineInventory-Ressource] (die den Elementarkatalog bilden) anzuhängen.

In diesem Fall können Anmerkungen die bessere Wahl sein, da ihre Werte nicht bereinigt werden.

=== Selektoren für die Clusterbereitstellung

Die `Label Templates` kann verwendet werden, um Labels zu generieren, mit denen Maschinen mit speziellen Hardwareeigenschaften identifiziert und ausgewählt werden können, um neue Kubernetes-Cluster zu bilden.

Die an jedes xref:references/machineinventory-reference.adoc[MachineInventory] angehängten Bezeichnungen sind für den _Selektor_ der Ressource xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate] geeignet (weitere Informationen finden Sie im Abschnitt xref:rancher-os-management/architecture/services/architecture-clusterdeployment.adoc[Kubernetes-Cluster-Bereitstellung] ).

=== Benutzerdefinierte Maschinennamen

Der Hostname des Onboarding-Rechners kann über das Feld xref:references/machineregistration-reference.adoc[MachineRegistration] `spec.machineName` angegeben werden.

`spec.machineName` Wert durchläuft die gleichen Prozesse wie `Label Templates' variables` und `sanitization`, die dem Feld `spec.machineInventoryLabels` vorbehalten sind.

[CAUTION]
====
Es gibt einen bemerkenswerten Unterschied zwischen den Feldern xref:references/machineregistration-reference.adoc[MachineRegistration] `spec.machineName` und `spec.machineInventorylabels`: Während des <<_sanitization,Bereinigungsprozesses>> wird der Unterstrich (`_`) wie die anderen verbotenen Zeichen ersetzt (d. h. er wird durch einen Bindestrich ersetzt: `-`). Dies ist erforderlich, da der Unterstrich in Linux-Hostnamen nicht zulässig ist.
====


Weitere Informationen zur Definition des Hostnamens für Elemental-Hosts finden Sie im Abschnitt xref:installation/hostname.adoc[HowTo/Customize hostname].

[NOTE]
.Rendering-Beispiel
====
* Definieren Sie eine Hostnamenvorlage wie `SLE-Micro-[random string of 6 hexadecimal values]`:
 ** MachineRegistration spec: *machineName: SLE-Micro-${Random\/Hex\/6}*
 ** MachineInventory Name: *SLE-Micro-32ad41*
====


== Beispiel für Etikettenvorlagen

.Registrierungsbeispiel mit Variablen der Etikettenvorlagen
[,yaml]
----
include::example$quickstart/registration-hardware-dhcphostname.yaml[]
----
