= Sicherung
:revdate: 2025-11-06
:page-revdate: {revdate}

Da {elemental-product-name} als Teil von Rancher läuft, sind die {elemental-product-name} Ressourcen im Rancher-Backup gebündelt.
Weitere Details zu Rancher-Backups, Wiederherstellung und Disaster-Recovery-Optionen finden Sie in der offiziellen https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.html[Rancher-Dokumentation].

== Rancher-Backup-Operator für Rancher installieren

Folgen Sie der https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up.html[Backup-Anleitung] Rancher, um zu erfahren, wie Sie den Rancher Backup-Operator installieren und konfigurieren.


== Sicherung {elemental-product-name} mit rancher-backup operator

Erstellen Sie eine `+backup object+` (angepasst an Ihre Bedürfnisse) zur Sicherung von Rancher, das auf einem Kubernetes-Cluster läuft.

[,yaml]
----
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: rancher-backup
spec:
  resourceSetName: rancher-resource-set
  schedule: "10 3 * * *"
  retentionCount: 10
----

Der Rancher-Backup-Operator bietet mehrere Optionen für Zeitplan, Verschlüsselung und Speicherklassen.
Sie können alle Optionen in der https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.html[offiziellen Dokumentation von] nachlesen.

Prüfen Sie die Protokolle des Rancher-Backup-Betreibers.

[,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

Überprüfen Sie, ob die Sicherungsdatei auf einem Persistent Volume erstellt wurde.

[,shell]
----
...
INFO[2022/10/17 07:45:04] Finding files starting with /var/lib/backups/rancher-backup-430169aa-edde-4a61-85e8-858f625a755b*.tar.gz
INFO[2022/10/17 07:45:04] File rancher-backup-430169aa-edde-4a61-85e8-858f625a755b-2022-10-17T05-15-00Z.tar.gz was created at 2022-10-17 0
...
----
