include::partial$variables.adoc[]
= Politische Einstellungen
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Konfigurieren Sie Richtlinieneinstellungen unter Verwendung von {project-name} zur Validierung und Serialisierung von Richtliniendaten.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "settings"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "Richtlinienspezifikation", "Richtlinieneinstellungen"]
:sidebar_label: Politische Einstellungen
:current-version: {page-origin-branch}

Das Verhalten der Richtlinie ist nicht starr, Sie können es konfigurieren, indem Sie der Richtlinie zur Laufzeit Konfigurationsdetails zur Verfügung stellen. Der Verfasser der Richtlinie hat die Freiheit, die Struktur der Richtlinieneinstellungen zu definieren.

{project-name} kümmert sich um die Serialisierung der Richtlinieneinstellungen in JSON und stellt sie der Richtlinie bei jedem Aufruf zur Verfügung.

== Validierung der Einstellungen

Richtlinien sollten die Einstellungen, die ein Benutzer angibt, auf ihre Korrektheit hin überprüfen.

Jede Richtlinie registriert eine waPC-Funktion namens `+validate_settings+`, die die Richtlinieneinstellungen überprüft.

Die Funktion `+validate_settings+` erhält als Eingabe eine JSON-Darstellung der vom Benutzer angegebenen Einstellungen. Diese Funktion validiert sie und gibt als Antwort ein `+SettingsValidationResponse+` Objekt zurück.

Die Struktur des Objekts `+SettingsValidationResponse+` ist wie folgt:

[subs="+attributes",yaml]
----
{
  # mandatory
  "valid": <boolean>,

  # optional, ignored if accepted - recommended for rejections
  "message": <string>,
}
----

Wenn die vom Benutzer vorgenommenen Einstellungen `+valid+` lauten, ignoriert `+validate_settings+` den Inhalt von`+message+`. Andernfalls wird unter `+validate_settings+` der Inhalt von `+message+`angezeigt.

[NOTE]
====

{short-project-name}Der https://github.com/chimera-kube/policy-server[Richtlinienserver]validiert alle von den Benutzern beim Start angegebenen Richtlinieneinstellungen. Der Richtlinienserver beendet sich sofort mit einem Fehler, wenn mindestens eine seiner Richtlinien falsche Konfigurationsparameter erhalten hat.

====


== Beispiel

Nehmen wir als Beispiel die Richtliniehttps://github.com/kubewarden/psp-capabilities[] psp-capabilities, die das folgende Konfigurationsformat hat:

[subs="+attributes",yaml]
----
allowed_capabilities:
- CHOWN

required_drop_capabilities:
- NET_ADMIN

default_add_capabilities:
- KILL
----

Die Funktion `+validate_settings+` erhält als Eingabe das folgende JSON-Dokument:

[subs="+attributes",json]
----
{
  "allowed_capabilities": [
    "CHOWN"
  ],
  "required_drop_capabilities": [
    "NET_ADMIN"
  ],
  "default_add_capabilities": [
    "KILL"
  ]
}
----

== Rekapitulation

Jede Police muss eine waPC-Funktion registrieren, `+validate_settings+`.
