include::partial$variables.adoc[]
= Validierung von Richtlinien
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Bewerten Sie Ihre Validierungsanfragen anhand richtlinienspezifischer Einstellungen, um die Annahme oder Ablehnung von Kubernetes AdmissionReview-Objekten zu bestimmen.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "validating-policies"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "Richtlinienspezifikation", "Richtlinienvalidierung"]
:sidebar_label: Validierung von Richtlinien
:current-version: {page-origin-branch}

Der Richtlinienserver {project-name} empfängt:

* Kuberneteshttps://godoc.org/k8s.io/api/admission/v1#AdmissionReview[`+AdmissionReview+`]Objekte vom Kubernetes-API-Server.
Sie leitet dann den Wert ihres Attributs `+request+` vom Typhttps://godoc.org/k8s.io/api/admission/v1#AdmissionRequest[`+AdmissionRequest+`]zur Auswertung an die Richtlinie weiter.

oder:

* Ein JSON `+request+` -Attribut, das das Freiform-Anfragedokument enthält, wenn es sich um eine rohe Richtlinie handelt. Weitere Einzelheiten finden Sie im Abschnitt xref:../../howtos/raw-policies.adoc[Rohdatenpolitik].

Die Politik bewertet die `+request+` und entscheidet, ob sie sie annehmen soll oder nicht. Wenn eine Anfrage abgelehnt wird, kann die Richtlinie eine Erklärungsmeldung und einen Fehlercode enthalten, der dem Endbenutzer angezeigt wird.

Gemäß der Konvention des `+policy-server+` -Projekts muss der Gast eine Funktion mit dem Namen `+validate+` über das waPC-Gast-SDK zur Verfügung stellen, damit der`+policy-server+` (waPC-Host) diese aufrufen kann.

Die Funktion `+validate+` empfängt ein `+ValidationRequest+` JSON-Objekt und gibt ein `+ValidationResponse+` JSON-Objekt zurück.

== Das Objekt `+ValidationRequest+` 

`+ValidationRequest+` ist ein JSON-Objekt, das von der Funktion `+validate+` empfangen wird.
Sieht so aus:

[subs="+attributes",yaml]
----
{
  "request": <AdmissionReview.request data> | <RawReviewRequest.request data>,
  "settings": {
    # your policy configuration
  }
}
----

Der Schlüssel `+settings+` verweist auf ein frei formuliertes JSON-Dokument, das die richtlinienspezifischen Einstellungen enthält. Das vorangegangene Kapitel konzentrierte sich auf Maßnahmen und Einstellungen.

== Ein Beispiel

Angesichts der folgenden Kubernetes `+AdmissionReview+`:

.Erweitern um zu sehen `+AdmissionReview+`
[%collapsible]
======

[subs="+attributes",yaml]
----
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    # Random uid uniquely identifying this admission call
    "uid": "705ab4f5-6393-11e8-b7cc-42010a800002",

    # Fully-qualified group/version/kind of the incoming object
    "kind": {"group":"autoscaling","version":"v1","kind":"Scale"},
    # Fully-qualified group/version/kind of the resource being modified
    "resource": {"group":"apps","version":"v1","resource":"deployments"},
    # subresource, if the request is to a subresource
    "subResource": "scale",

    # Fully-qualified group/version/kind of the incoming object in the original request to the API server.
    # This only differs from `+kind+` if the webhook specified `+matchPolicy: Equivalent+` and the
    # original request to the API server was converted to a version the webhook registered for.
    "requestKind": {"group":"autoscaling","version":"v1","kind":"Scale"},
    # Fully-qualified group/version/kind of the resource being modified in the original request to the API server.
    # This only differs from `+resource+` if the webhook specified `+matchPolicy: Equivalent+` and the
    # original request to the API server was converted to a version the webhook registered for.
    "requestResource": {"group":"apps","version":"v1","resource":"deployments"},
    # subresource, if the request is to a subresource
    # This only differs from `+subResource+` if the webhook specified `+matchPolicy: Equivalent+` and the
    # original request to the API server was converted to a version the webhook registered for.
    "requestSubResource": "scale",

    # Name of the resource being modified
    "name": "my-deployment",
    # Namespace of the resource being modified, if the resource is namespaced (or is a Namespace object)
    "namespace": "my-namespace",

    # operation can be CREATE, UPDATE, DELETE, or CONNECT
    "operation": "UPDATE",

    "userInfo": {
      # Username of the authenticated user making the request to the API server
      "username": "admin",
      # UID of the authenticated user making the request to the API server
      "uid": "014fbff9a07c",
      # Group memberships of the authenticated user making the request to the API server
      "groups": ["system:authenticated","my-admin-group"],
      # Arbitrary extra info associated with the user making the request to the API server.
      # This is populated by the API server authentication layer and should be included
      # if any SubjectAccessReview checks are performed by the webhook.
      "extra": {
        "some-key":["some-value1", "some-value2"]
      }
    },

    # object is the new object being admitted.
    # It is null for DELETE operations.
    "object": {"apiVersion":"autoscaling/v1","kind":"Scale",...},
    # oldObject is the existing object.
    # It is null for CREATE and CONNECT operations.
    "oldObject": {"apiVersion":"autoscaling/v1","kind":"Scale",...},
    # options contains the options for the operation being admitted, like meta.k8s.io/v1 CreateOptions, UpdateOptions, or DeleteOptions.
    # It is null for CONNECT operations.
    "options": {"apiVersion":"meta.k8s.io/v1","kind":"UpdateOptions",...},

    # dryRun indicates the API request is running in dry run mode and will not be persisted.
    # Webhooks with side effects should avoid actuating those side effects when dryRun is true.
    # See http://k8s.io/docs/reference/using-api/api-concepts/#make-a-dry-run-request for more details.
    "dryRun": false
  }
}
----

======

Das Objekt `+ValidationRequest+` würde wie folgt aussehen:

.Erweitern, um die `+ValidationRequest+`
[%collapsible]
======

[subs="+attributes",yaml]
----
{
  "request": {
    # Random uid uniquely identifying this admission call
    "uid": "705ab4f5-6393-11e8-b7cc-42010a800002",

    # Fully-qualified group/version/kind of the incoming object
    "kind": {"group":"autoscaling","version":"v1","kind":"Scale"},
    # Fully-qualified group/version/kind of the resource being modified
    "resource": {"group":"apps","version":"v1","resource":"deployments"},
    # subresource, if the request is to a subresource
    "subResource": "scale",

    # Fully-qualified group/version/kind of the incoming object in the original request to the API server.
    # This only differs from `+kind+` if the webhook specified `+matchPolicy: Equivalent+` and the
    # original request to the API server was converted to a version the webhook registered for.
    "requestKind": {"group":"autoscaling","version":"v1","kind":"Scale"},
    # Fully-qualified group/version/kind of the resource being modified in the original request to the API server.
    # This only differs from `+resource+` if the webhook specified `+matchPolicy: Equivalent+` and the
    # original request to the API server was converted to a version the webhook registered for.
    "requestResource": {"group":"apps","version":"v1","resource":"deployments"},
    # subresource, if the request is to a subresource
    # This only differs from `+subResource+` if the webhook specified `+matchPolicy: Equivalent+` and the
    # original request to the API server was converted to a version the webhook registered for.
    "requestSubResource": "scale",

    # Name of the resource being modified
    "name": "my-deployment",
    # Namespace of the resource being modified, if the resource is namespaced (or is a Namespace object)
    "namespace": "my-namespace",

    # operation can be CREATE, UPDATE, DELETE, or CONNECT
    "operation": "UPDATE",

    "userInfo": {
      # Username of the authenticated user making the request to the API server
      "username": "admin",
      # UID of the authenticated user making the request to the API server
      "uid": "014fbff9a07c",
      # Group memberships of the authenticated user making the request to the API server
      "groups": ["system:authenticated","my-admin-group"],
      # Arbitrary extra info associated with the user making the request to the API server.
      # This is populated by the API server authentication layer and should be included
      # if any SubjectAccessReview checks are performed by the webhook.
      "extra": {
        "some-key":["some-value1", "some-value2"]
      }
    },

    # object is the new object being admitted.
    # It is null for DELETE operations.
    "object": {"apiVersion":"autoscaling/v1","kind":"Scale",...},
    # oldObject is the existing object.
    # It is null for CREATE and CONNECT operations.
    "oldObject": {"apiVersion":"autoscaling/v1","kind":"Scale",...},
    # options contains the options for the operation being admitted, like meta.k8s.io/v1 CreateOptions, UpdateOptions, or DeleteOptions.
    # It is null for CONNECT operations.
    "options": {"apiVersion":"meta.k8s.io/v1","kind":"UpdateOptions",...},

    # dryRun indicates the API request is running in dry run mode and will not be persisted.
    # Webhooks with side effects should avoid actuating those side effects when dryRun is true.
    # See http://k8s.io/docs/reference/using-api/api-concepts/#make-a-dry-run-request for more details.
    "dryRun": false
  },
  "settings": {
    # policy settings
  }
}
----

======

== Das Objekt `+ValidationResponse+` 

Die Funktion `+validate+` gibt das Ergebnis der Validierung in Form eines`+ValidationResponse+` Objekts zurück.

Die Website `+ValidationResponse+` hat diese Struktur:

[subs="+attributes",yaml]
----
{
  # mandatory
  "accepted": <boolean>,

  # optional, ignored if accepted - recommended for rejections
  "message": <string>,

  # optional, ignored if accepted
  "code": <integer>,

  # optional, used by mutation policies
  "mutated_object": <string>
}
----

Sie können diese `+message+` und `+code+` Attribute angeben, wenn die Anfrage nicht akzeptiert wird. Bei `+message+` handelt es sich um einen Freitextfehler und bei `+code+` um einen HTTP-Fehlercode.

Der Kubernetes-API-Server ignoriert die Werte `+message+` und `+code+` bei der Annahme von Anfragen.

Wenn die Anfrage abgelehnt wird und die `+message+` oder `+code+` vorhanden sind, gibt der Kubernetes-API-Server diese Informationen zurück. Die Informationen sind Teil des Fehlertextes und werden vom Server an den Kubernetes-API-Client zurückgesendet, der die abgelehnte Anfrage gestellt hat.

Die `+mutated_object+` ist ein optionales Feld, das nur bei der Mutation von Richtlinien verwendet wird.
Dies ist das Thema des nächsten Kapitels.
