include::partial$variables.adoc[]
= 証明書のローテーション
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: ダウンタイムを発生させることなく、{project-name} の証明書をローテーションする方法をご覧ください。
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["explanations", "certificates"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "certificate", "controller", "reconciliation"]
:sidebar_label: 証明書のローテーション
:sidebar_position: 21

{project-name} v1.17.0でcert-managerの依存性が削除された。コントローラは、すべてのコンポーネントが使用するすべての証明書を管理できる。これで、コントローラは、証明書が常に最新であり、Webhookの設定が正しいことを保証する、新しい照合ループを持つようになった。

Helmチャートのインストールは、最初の証明書生成を行う。これは、有効期限まで10年のルートCAを生成する。Helmチャートのインストールは、ルートCAによって署名されたコントローラウェブフックウェブサーバ証明書も生成します。APIサーバーはこれを使用して、{short-project-name} コントローラーと通信し、CRDを検証する。有効期限は1年。

コントローラが起動すると、リコンシラによって、証明書の有効期限が切れると自動的に更新される。また、{short-project-name} スタック全体で使用されるすべての証明書とウェブフックの設定も更新される。

[NOTE]
====
Helmチャートによって生成され、後にコントローラによって生成されるすべての証明書は、ECDSA P256キーを使用する。
====

照合ループは、有効期限の60日前に証明書を更新する。
証明書はダウンタイムなしにローテーションする。照合ループはルートCAも更新する。

コントローラは、有効期限の60日前に新しいルートCAを生成する。コントローラは、すべてのWebhookで使用されるCAバンドルを更新し、新しいルートCAと古いルートCAの両方を含める。

ルート CA の変更により、リコンシラリはウェブフックに発行された証明書を再作成する。新しい証明書の伝播には一定期間を要する。しかしこの間、更新されたCAバンドルによって、APIサーバーはダウンタイムなしにすべてのWebhookとの通信を継続できる。

新しい証明書の準備ができ、古い証明書が無効になると、コントローラは、最新のルートCAのみを含むように、Webhookで使用されるCAバンドルを更新する。

ポリシーサーバ、またはコントローラのWebサーバの証明書が更新されると、コントローラは、ルートCAによって署名された新しい証明書でシークレットを更新する。このリロード機能により、コントローラとポリシーサーバは、プロセスを再起動することなく新しい証明書を使用するため、ダウンタイムが発生しない。
