= 常见问题
:page-languages: [EN, JA, KO, ZH]
:revdate: 2024-09-11
:page-revdate: {revdate}

常见问题定期更新，旨在回答用户最常提出的有关 K3 的问题。

== K3s 是 Kubernetes 的合适替代品吗？

K3s 是经过 CNCF 认证的 Kubernetes 发行版，可以完成标准 Kubernetes 集群所需的一切功能。它只是一个更轻便的版本。更多详情，请参阅xref:introduction.adoc[主]文档页面。

== 如何使用自己的 Ingress 代替特拉菲克？

只需通过`--disable=traefik` 启动 K3s 服务器并部署您的入口。

== K3s 支持 Windows 吗？

目前，K3s 本身不支持 Windows，但我们对未来的想法持开放态度。

== 服务器和代理究竟是什么？

有关构成服务器和代理的组件的详细信息，请参阅xref:architecture.adoc[架构页面]。

== 如何从源代码构建？

请参考 K3shttps://github.com/k3s-io/k3s/blob/main/BUILDING.md[.md] BUILDING中的说明。

== K3s 的日志在哪里？

K3s 日志的位置因运行 K3s 的方式和节点的操作系统而异。

* 从命令行运行时，日志会被发送到 stdout 和 stderr。
* 在 openrc 下运行时，日志将在`/var/log/k3s.log`.
* 在 Systemd 下运行时，日志将发送到 Journald，并可使用`journalctl -u k3s` 查看。
* Pod 日志可在`/var/log/pods` 上找到。
* Containerd 日志可在`/var/lib/rancher/k3s/agent/containerd/containerd.log` 上找到。

您可以在启动 K3s 时使用`--debug` 标志（或在配置文件中使用`debug: true` ）生成更详细的日志。

Kubernetes 使用一种名为`klog` 的日志框架，它为进程内的所有组件使用单一日志配置。
由于 K3s 在单个进程中运行所有 Kubernetes 组件，因此无法为单个 Kubernetes 组件配置不同的日志级别或目的地。
使用`-v=<level>` 或`--vmodule=<module>=<level>` 组件参数很可能达不到预期效果。

有关更多日志选项，请参阅xref:advanced.adoc#_additional_logging_sources[附加日志源]。

== 我可以在 Docker 中运行 K3 吗？

是的，在 Docker 中运行 K3 有多种方法。详情请参阅xref:advanced.adoc#_running_k3s_in_docker[高级选项]。

== K3s 服务器和代理令牌有什么区别？

有关管理 K3s 连接令牌的更多信息，请参阅xref:cli/token.adoc[`k3s token` 命令文档]。

== 不同版本 K3 的兼容性如何？

一般来说，https://kubernetes.io/docs/setup/release/version-skew-policy/[Kubernetes 版本倾斜政策]。

简而言之，服务器可以比代理新，但代理不能比服务器新。

== 我遇到了问题，在哪里可以得到帮助？

如果您在部署 K3 时遇到问题，您应该这样做：

. 查看xref:known-issues.adoc[已知问题]页面。
. 检查是否已解决任何xref:installation/requirements.adoc#_operating_systems[附加操作系统准备工作]。运行`k3s check-config` 并确保通过。
. 在 K3shttps://github.com/k3s-io/k3s/issues[问题]和https://github.com/k3s-io/k3s/discussions[讨论]中搜索与您的问题相匹配的问题。
. 加入https://slack.rancher.io/[Slack] RancherK3s 频道获取帮助。
. 在 K3s Github 上提交https://github.com/k3s-io/k3s/issues/new/choose[新问题]，描述您的设置和遇到的问题。
