ifdef::ss-ff-stackpacks2_enabled[]
= Esquema y referencia de los enlaces métricos
:revdate: 2026-01-09
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

En esta página se describen los esquemas de `MetricBinding`, junto con explicaciones detalladas de las construcciones, la sintaxis de las expresiones y su semántica.

== Esquema para la vinculación métrica

Cada encuadernación métrica:

* Selecciona los componentes en los que puede aplicarse
* Define plantillas de consulta PromQL para recuperar datos
* Especifica cómo deben representarse los datos resultantes
* Incluye sugerencias de diseño para seleccionar un lugar adecuado en la interfaz de usuario para mostrar el gráfico.

[,yaml]
----
_type: "MetricBinding"
name: string
chartType: "line"                     # "line" is the only type for now
unit?: string
scope: string                         # Topology scope - components to bind to
enabled: boolean                      # default: true
description?: string
valuation?: "higher-is-better" | "lower-is-better"
priority?: "HIGH" | "MEDIUM" | "LOW" | "NONE"    # deprecated
queries:
  - _type: "MetricBindingQuery"
    expression: string                # promql query
    alias: string                     # name in legend
    componentIdentifierTemplate?: string    # URN template for linking
    primary?: boolean                 # is this query the primary one
tags:
  <key>: <value>
layout?:                              # where should chart be shown
  metricPerspective?:                 # the metrics perspective for a component
    tab: string
    section: string
    weight?: integer
  componentHighlight?:                # highlight perspective of a component
    section: string
    weight?: integer
  componentSummary?:                  # summary - supporting panel on the right
    weight?: integer
identifier?: string
----

* `_type`: {stackstate-product-name} necesita saber que se trata de una vinculación métrica, por lo que el valor siempre debe ser `MetricBinding`
* `name`: Nombre del enlace métrico
* `chartType`{stackstate-product-name} soportará diferentes tipos de gráficos (`line`, `bar`, etc.), actualmente sólo se soporta `line` 
* `unit`: La unidad de los valores de la serie temporal devuelta por la consulta o consultas, utilizada para representar el eje Y del gráfico. Consulte la referencia de xref:/develop/reference/k8sTs-chart-units.adoc[unidades compatibles] para ver todas las unidades
* `scope`: El ámbito topológico del enlace métrico, una consulta topológica que selecciona los componentes en los que se mostrará este enlace métrico.
* `enabled`: Establecer en `false` para mantener la métrica vinculante pero no mostrarla a los usuarios.
* `description`: Descripción opcional, que aparece sobre el nombre
* `valuation`: Si son "mejores" valores más altos o más bajos
* `priority`: [Deprecated] Uno de `HIGH`, `MEDIUM`, o `LOW`. Orden de clasificación principal para las métricas de un componente (en el orden en que se mencionan aquí), el orden de clasificación secundario es el `name`.
* `queries`: Una lista de las consultas que se mostrarán en el gráfico para el enlace métrico (véase xref:/setup/custom-integrations/metric-bindings/writing-promql.adoc[Escribir consultas PromQL])
** `expression`: La consulta promql (planificada)
** `alias`: Nombre de la consulta en la leyenda
** `componentIdentifierTemplate`: Plantilla para el identificador del componente relacionado, rellenada con etiquetas de series temporales resultantes de la consulta
** `primary`: ¿Es esta consulta la principal
* `tags`: Se utilizará para organizar las métricas en la interfaz de usuario, puede dejarse vacía utilizando `{}`
* `layout`: Cómo agrupar gráficos en diferentes perspectivas, por ejemplo, en xref:/use/views/k8s-metrics-perspective.adoc[la perspectiva de métricas]
** `metricPerspective` - Define las métricas que se mostrarán en `Metrics Perspective`. Las métricas se agrupan en pestañas y luego en secciones.
*** `tab` - Nombre de la pestaña. Las pestañas están ordenadas alfabéticamente
*** `section` - Nombre de la sección. Secciones ordenadas alfabéticamente
*** `weight` - Las métricas de una sección se ordenan principalmente por peso (ascendente) y, en segundo lugar, por nombre (alfabético).
** `componentHighlight` - Define las métricas que se mostrarán en `Component Highlight`. Las métricas se agrupan en secciones.
*** `section` - Nombre de la sección. Secciones ordenadas alfabéticamente
*** `weight` - Las métricas de una sección se ordenan principalmente por peso (ascendente) y, en segundo lugar, por nombre (alfabético).
** `componentSummary` - Especifica las métricas que se mostrarán en la barra lateral `Components details` al seleccionar un componente. Los gráficos sólo aparecen cuando esta propiedad está definida.
*** `weight` - Representa el peso del gráfico. Los gráficos se ordenan en orden ascendente por peso y, a continuación, muestra los tres primeros gráficos.
* `identifier`: Un URN (identificador universal de recursos), utilizado como identificador único del enlace métrico. Debe empezar por `urn:stackpack:<stackpack-name>:metric-binding:`, el resto es de formato libre siempre que sea único entre todos los enlaces métricos.

endif::ss-ff-stackpacks2_enabled[]
