= Substituir os argumentos de limite do monitor por meio de anotações do kubernetes
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

O SUSE Observability oferece xref:/use/alerting/k8s-monitors.adoc[monitores prontos para uso], que fornecem monitoramento de problemas comuns que podem ocorrer em um cluster do Kubernetes. Esses monitores funcionam com determinados argumentos padrão que atendem à maioria dos casos de uso, mas, às vezes, é necessário adaptar seu comportamento substituindo alguns desses argumentos padrão, como `threshold` ou `failureState`.
O mecanismo para declarar as substituições é por meio de anotações de recursos do kubernetes que indicam a qual monitor e componente elas devem ser aplicadas. Por exemplo, poderíamos substituir o `failureState` pelo monitor `Available service endpoints` para um serviço específico em que desejamos sinalizar um estado `CRITICAL` quando ele falhar, em vez do padrão `DEVIATING`.

== Como fazer

* <<_how_to_build_my_annotation,Como criar minha anotação>>
* <<_what_monitors_allow_overriding_arguments,Quais monitores permitem a substituição de argumentos?>>
* <<_build_an_override_for_a_custom_monitor,Criar uma substituição para um monitor personalizado>>

Como exemplo, as etapas substituirão os argumentos do monitor `Available service endpoints` dos serviços HTTP do Kubernetes.

== Como criar minha anotação

As chaves de anotações de substituição dos monitores do SUSE Observability seguem a seguinte convenção:

----
monitor.${owner}.stackstate.io/${monitorShorName}
----

A propriedade `owner` representa quem criou esse monitor; para os monitores prontos para uso, é `kubernetes-v2`, e a propriedade `monitorShorName` representa o ID do monitor e pode ser extraída da propriedade `identifier` de um monitor, que pode ser lida no cliente ao listar ou inspecionar monitores

----
sts monitor list

ID              | STATUS  | IDENTIFIER                                                                          | NAME                                        | FUNCTION ID     | TAGS
8051105457030   | ENABLED | urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:service-available-endpoint | Available service endpoints                 | 233276809885571 | [services]
----

Em nosso exemplo, o identificador é `urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:service-available-endpoint` e o `monitorShorName` corresponde ao último segmento, como em `service-available-endpoint`, portanto, a chave de anotação é:

[,bash]
----
monitor.kubernetes-v2.stackstate.io/service-available-endpoint
----

a carga útil da anotação é um objeto JSON em que os seguintes argumentos opcionais podem ser definidos:

* `threshold`Limite numérico para comparação: opcional.
* `failureState`: opcional. Ou "CRÍTICO" ou "DESVIADO". "CRITICAL" será exibido como lido no SUSE Observability e "DEVIATING" como laranja, para denotar gravidade diferente.
* `enabled`: opcional. Booleano que determina se o monitor produziria um estado de integridade para esse componente.

A anotação completa teria a seguinte aparência

[,bash]
----
    monitor.kubernetes-v2.stackstate.io/service-available-endpoint: |-
      {
        "threshold": 0.0,
        "failureState": "CRITICAL",
        "enabled": true
      }
----

== Quais monitores permitem a substituição de argumentos?

* xref:/use/alerting/kubernetes-monitors.adoc#_available_service_endpoints[Pontos de extremidade de serviço disponíveis]
* xref:/use/alerting/kubernetes-monitors.adoc#_cpu_limits_resourcequota[Limites de cpu cota de recursos]
* xref:/use/alerting/kubernetes-monitors.adoc#_cpu_requests_resourcequota[Cpu requests resourcequota]
* xref:/use/alerting/kubernetes-monitors.adoc#_memory_limits_resourcequota[Limites de memória resourcequota]
* xref:/use/alerting/kubernetes-monitors.adoc#_memory_requests_resourcequota[Solicitações de memória resourcequota]
* xref:/use/alerting/kubernetes-monitors.adoc#_node_disk_pressure[Pressão do disco do nó]
* xref:/use/alerting/kubernetes-monitors.adoc#_node_memory_pressure[Pressão da memória do nó]
* xref:/use/alerting/kubernetes-monitors.adoc#_node_pid_pressure[Nó Pressão PID]
* xref:/use/alerting/kubernetes-monitors.adoc#_node_readiness[Prontidão do nó]
* xref:/use/alerting/kubernetes-monitors.adoc#_orphaned_persistent_volumes[Volumes persistentes órfãos] (somente a propriedade `enabled` )
* xref:/use/alerting/kubernetes-monitors.adoc#_out_of_memory_for_containers[Falta de memória para contêineres]
* xref:/use/alerting/kubernetes-monitors.adoc#_http_5xx_error_ratio[HTTP - taxa de erro 5xx]
* xref:/use/alerting/kubernetes-monitors.adoc#_http_response_time_q95_is_above_3_seconds[HTTP - tempo de resposta - Q95 está acima de 3 segundos]

== Criar uma substituição para um monitor personalizado

Qualquer monitor de limite personalizado criado usando o guia em xref:/use/alerting/k8s-add-monitors-cli.adoc[Adicionar um monitor de limite a componentes usando a CLI] é adequado para substituir argumentos, pois xref:/use/alerting/k8s-add-monitors-cli.adoc#_write_the_outline_of_the_monitor[o exemplo mostra que] um identificador para um monitor personalizado é estruturado como ``+urn:custom:monitor:{monitorShortName}``+e espera-se que a chave de anotação de substituição para esse identificador seja

[,bash]
----
monitor.custom.stackstate.io/${monitorShortName}
----

O exemplo usa o identificador `urn:custom:monitor:deployment-has-replicas`, portanto, a chave de anotação seria

[,bash]
----
monitor.custom.stackstate.io/deployment-has-replicas
----

E a anotação completa seria semelhante a

[,bash]
----
    monitor.custom.stackstate.io/deployment-has-replicas: |-
      {
        "threshold": 0.0,
        "failureState": "CRITICAL"
        "enabled": true
      }
----
