= Monitores de estado derivados
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

Em cenários de observabilidade em que os componentes lógicos (comerciais) não têm monitores diretos, mas são afetados por problemas em suas dependências técnicas, você pode usar a função de monitor de estado derivado para derivar um estado dos componentes técnicos conectados para o componente lógico.
Esse monitor percorre as dependências dos componentes e seleciona o estado de integridade mais crítico com base em observações diretas (por exemplo, a partir de métricas), ignorando quaisquer estados já derivados. Ele aplicará o estado derivado a todos os componentes selecionados por meio do parâmetro `componentTypes`.
Durante a passagem, somente os componentes com estados de integridade observados (não derivados) são considerados para a derivação de integridade. Os componentes com estados derivados são ignorados na avaliação, mas ainda são percorridos para alcançar dependências mais profundas--por exemplo, componentes lógicos que dependem de outros componentes lógicos.

== Exemplo de monitor de estado de saúde derivado

Um Monitor implementado usando a função `derived-state-monitor` tem a seguinte aparência:

----
  - _type: "Monitor"
    name: "Aggregated health state of a Deployment, StatefulSet, ReplicaSet and DaemonSet"
    tags:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
      - derived
      - propagated
    identifier: "urn:custom:monitor:..."
    status: "DISABLED"
    description: "Description"
    function: {{ get "urn:stackpack:common:monitor-function:derived-state-monitor" }}
    arguments:
      componentTypes: "deployment, replicaset, statefulset, daemonset"
    intervalSeconds: 30
    remediationHint: "Investigate component [{{ causeComponentName }}](/#/components/{{ causeComponentUrnForUrl }}) as is causing the workload to be unhealthy."
----

* A função tem um único argumento `componentTypes`, no qual você pode expressar os diferentes tipos de componentes como uma única cadeia de valores separados por `,` 
* A função oferece três valores para serem usados no guia de correção
 ** `componentName` sendo o nome do componente lógico.
 ** `causeComponentName` sendo o nome do componente de onde o estado é propagado e seu endereço `causeComponentUrnForUrl` para poder criar um link.

O monitor pode ser implementado usando o guia em xref:/use/alerting/k8s-add-monitors-cli.adoc[Adicionar um monitor de limite aos componentes usando a CLI]
