= SLSA
:revdate: 2025-04-04
:page-revdate: {revdate}

== Visión general

https://slsa.dev/spec/v1.0/about[La SLSA] es un conjunto de directrices progresivamente adoptables para la seguridad de la cadena de suministro, establecidas por consenso del sector. La especificación establecida por SLSA es útil tanto para los productores de software como para los consumidores: los productores pueden seguir las directrices de SLSA para hacer más segura su cadena de suministro de software, y los consumidores pueden utilizar SLSA para decidir si confían en un paquete de software.

{product_name} cumple los requisitos https://slsa.dev/spec/v1.0/levels[del nivel 3 de la SLSA de].

|===
| Requisito | Obligatorio en SLSA L3 | Reunido por {product_name}

| Elija una plataforma de construcción adecuada
| Sí
| Sí

| Siga un proceso de construcción coherente
| Sí
| Sí

| Distribuir la procedencia
| Sí
| Sí
|===

== Plataforma de construcción

* El proyecto {product_name} utiliza Git para la gestión del código fuente.
* Todos los mantenedores de {product_name} deben tener habilitada la autenticación de dos factores, para firmar y dar el visto bueno a todas sus contribuciones.
* El proyecto {product_name} utiliza GitHub Actions y GitHub Runners para crear todos sus artefactos de publicación.
* El proceso de creación y publicación se ejecuta de forma aislada en un entorno efímero proporcionado por los ejecutores alojados en GitHub.

== Proceso de construcción

* El proceso de creación y publicación se define en el código y se mantiene bajo control de versiones.
* Los flujos de trabajo de GitHub utilizan acciones de GitHub ancladas a determinadas versiones y se mantienen actualizadas mediante GitHub Dependabot.
* Todos los cambios en el proceso de compilación y publicación se realizan mediante Pull Requests que deben ser aprobados por al menos un responsable de {product_name}.
* El proceso de publicación sólo puede iniciarlo un responsable de {product_name} enviando una etiqueta Git en formato semver.

== Procedencia

* El proyecto {product_name} utiliza el proyecto oficial https://github.com/slsa-framework/slsa-github-generator[SLSA GitHub Generator] para la generación y distribución de procedencias.
* La procedencia de los artefactos de lanzamiento publicados en GitHub Container Registry y en Rancher Prime Registry se genera utilizando el flujo de trabajo de GitHub generator_container_slsa3 proporcionado por el proyecto https://github.com/slsa-framework/slsa-github-generator[SLSA GitHub Generator].
* La procedencia identifica las imágenes del contenedor {product_name} utilizando su compendio en formato SHA-256.
* La procedencia es firmada por Sigstore Cosign utilizando la identidad GitHub OIDC, y la clave pública para verificar la procedencia se almacena en el público https://docs.sigstore.dev/logging/overview/[registro].
* El proceso de publicación y la generación de procedencias se ejecutan de forma aislada en un entorno efímero proporcionado por los ejecutores alojados en GitHub.
* La procedencia de las imágenes del contenedor {product_name} puede verificarse mediante la oficial https://github.com/slsa-framework/slsa-verifier[herramienta].
* Los flujos de trabajo de generación de procedencias se ejecutan en máquinas virtuales efímeras y aisladas, totalmente gestionadas por GitHub.
* Los secretos de firma de procedencia son efímeros y se generan mediante el procedimiento de firma de Sigstore https://github.com/sigstore/cosign/blob/main/KEYLESS.md[sin clave].
* El https://github.com/slsa-framework/slsa-github-generator[generador] se ejecuta en máquinas virtuales distintas de las del proceso de creación y publicación, de modo que los scripts de creación de {product_name} no tienen acceso a los secretos de firma.

== Aislamiento

* El proceso de publicación y la generación de procedencias se ejecutan de forma aislada en un entorno efímero proporcionado por los ejecutores alojados en GitHub.
* La generación de la procedencia está desacoplada del proceso de compilación; el https://github.com/slsa-framework/slsa-github-generator[generador] se ejecuta en máquinas virtuales independientes totalmente gestionadas por GitHub.
* El proceso de publicación no puede acceder a la clave de firma de procedencia porque el generador de procedencia se ejecuta de forma aislada en ejecutores separados alojados en GitHub.
