= 声明式网络的故障排除
:revdate: 2025-09-08
:page-revdate: {revdate}

给定以下登记样本：

.使用声明式网络的机器注册示例
[,yaml]
----
include::example$network/machineregistration.yaml[]
----

我们可以预期每个元素机器都将使用已定义的`nm-configurator` `_all.yaml` 模板进行配置。

首次启动时，`elemental-register` 会尝试联系 Rancher API 以注册一个新的`MachineInventory` 。

在此阶段，机器的网络尚未配置，默认为 DHCP。在此设置中，机器必须能够与 Rancher API 联系，否则无法进行注册。

`MachineInventory` 首次注册后，`elemental-operator` 将为网络配置中定义的每个`IPPool` 引用申请一个`IPAddress` 。

在`MachineInventory` 上，这将显示如下内容：

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  finalizers:
  - machineinventory.elemental.cattle.io
  name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c
  namespace: fleet-default
spec:
  ipAddressClaims:
    inventory-ip:
      apiVersion: ipam.cluster.x-k8s.io/v1beta1
      kind: IPAddressClaim
      name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c-inventory-ip
      namespace: fleet-default
      uid: 78f2d07a-7b6d-4b58-b615-c4108b7964b9
  ipAddressPools:
    inventory-ip:
      apiGroup: ipam.cluster.x-k8s.io
      kind: InClusterIPPool
      name: elemental-inventory-pool
  network:
    config:
      dns-resolver:
        config:
          search: []
          server:
          - 192.168.122.1
      interfaces:
      - description: Main-NIC
        ipv4:
          address:
          - ip: "{inventory-ip}"
            prefix-length: 24
          dhcp: false
          enabled: true
        ipv6:
          enabled: false
        name: eth0
        state: up
        type: ethernet
      routes:
        config:
        - destination: 0.0.0.0/0
          metric: 150
          next-hop-address: 192.168.122.1
          next-hop-interface: eth0
          table-id: 254
    ipAddresses:
      inventory-ip: 192.168.122.150
status:
  conditions:
  - lastTransitionTime: "2024-07-30T11:50:47Z"
    message: NetworkConfig is ready
    reason: ReconcilingNetworkConfig
    status: "True"
    type: NetworkConfigReady
----

您会注意到，`MachineInventory` 与`MachineRegistration` 的`network.config` 相同，不过，我们现在不再引用 IPAddressPools，而是一个真实 IPAddresses 的映射：

[,yaml]
----
    ipAddresses:
      inventory-ip: 192.168.122.150
----

这样，只要定义了`{inventory-ip}` ，就会在`nm-configurator` 配置中替换`inventory-ip` 。

还要注意的是，`MachineInventory` 引用并拥有与其相关的每个`IPAddressClaim` 。每项索赔都遵循可预测的`$MachineInventoryName-$IPPoolRefKey` 命名惯例：`m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c-inventory-ip` 。

这些索赔将遵循`MachineInventory` 对象的生命周期，并在级联时删除，例如在xref:node-operational-tasks/reset.adoc[重置工作流程]中删除。

如果`IPAddresses` 无法认领，则`NetworkConfigReady` 条件将被`False` ，阻止机器完成安装。如果`IPPool` 没有更多的`IPAddresses` 可用，就会出现这种情况。

== 机器方面

在安装阶段，机器上运行的`elemental-register` 进程将收到`nm-configurator` `_all.yaml` 配置模板和申请的 IPAddresses 及其密钥列表。这些信息将被消化为适用的`nm-configurator` 配置：

[,yaml]
----
config:
  dns-resolver:
    config:
      search: []
      server:
      - 192.168.122.1
  interfaces:
  - description: Main-NIC
    ipv4:
      address:
      - ip: "192.168.122.150"
        prefix-length: 24
      dhcp: false
      enabled: true
    ipv6:
      enabled: false
    name: eth0
    state: up
    type: ethernet
  routes:
    config:
    - destination: 0.0.0.0/0
      metric: 150
      next-hop-address: 192.168.122.1
      next-hop-interface: eth0
      table-id: 254
----

然后，`elemental-register` 将调用`nmc generate` 和`nmc apply` ，将此配置应用到运行系统中。

从此刻开始直至重置，机器将始终使用已应用的配置。

还需注意的是，在安装和重置之外，不再使用`nm-configurator` ，因为`elemental-register` 将保留`nmc` 生成的`/etc/NetworkManager/system-connection/*.nmconnection` 文件，而不是`nmc` 配置本身。

例如，在任何运行中的系统上，都可以找到一个https://github.com/rancher/yip[] yip 配置文件 (`/oem/elemental-network.yaml`) 来应用所需的`nmconnections` ：

[,yaml]
----
name: Apply network config
stages:
    initramfs:
        - files:
            - path: /etc/NetworkManager/system-connections/Wired connection 1.nmconnection
              permissions: 384
              owner: 0
              group: 0
              content: |
                [connection]
                id=Wired connection 1
                uuid=d26b4ae4-d525-3cbf-a557-33feb60343c0
                type=ethernet
                autoconnect-priority=-999
                interface-name=eth0
                timestamp=1722340245

                [ethernet]

                [ipv4]
                address1=192.168.122.150/24
                dhcp-timeout=2147483647
                dns=192.168.122.1;
                dns-options=
                dns-priority=40
                method=manual
                route1=0.0.0.0/0,192.168.122.1,150
                route1_options=table=254

                [ipv6]
                addr-gen-mode=eui64
                dhcp-timeout=2147483647
                method=disabled

                [proxy]

                [user]
                nm-configurator.interface.description=Main-NIC
              encoding: ""
              ownerstring: ""
----

=== 重置期间

每当触发xref:node-operational-tasks/reset.adoc[重置]，机器上运行的`elemental-register` 就会清除`/etc/NetworkManager/system-connection/*.nmconnection` 文件并重启网络协议栈。机器随后应恢复 DHCP，然后向管理端的`elemental-operator` 确认重置成功。

请注意，只有当`MachineInventory.spec.network.configurator` 的值不同于`none` 时才适用。否则在机器重置阶段不会采取任何重置网络的措施。

网络重置后，机器应重新启动进入恢复模式，执行实际重置，并接收要应用的新网络配置。如果`MachineRegistration` 没有更新，IP 地址可能与以前相同，也可能不同，因为以前的 IP 地址可能已被其他机器占用。

如果恢复到 DHCP 失败，或者机器无论如何都无法联系 Rancher API 进行确认，你会发现`MachineInventory` 不会被删除，尽管有一个删除时间戳。由于机器现在出现了网络问题，因此无法进行远程修复。

如果你打算让机器退役，你可以选择物理接触机器或通过任何方式修复 DHCP 驱动的网络配置，或者也可以从`MachineInventory` 中删除`machineinventory.elemental.cattle.io` finalizer，以允许删除。
