include::partial$variables.adoc[]
= Suporte ao Gatekeeper
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Acesse as políticas do gatekeeper central e saiba como integrá-las aos controladores de admissão do Kubernetes.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "rego", "gatekeeper"]
:current-version: {page-origin-branch}

[NOTE]
====
O suporte ao Gatekeeper começa a partir dessas versões:

* kwctl: v0.2.0
* Servidor de políticas: v0.2.0
====


O Gatekeeper é um projeto voltado para o Kubernetes com recursos prontos para integração.

== Compatibilidade com as políticas existentes

Todas as políticas existentes do Gatekeeper devem ser compatíveis com o site {short-project-name}, conforme explicado neste capítulo.

[IMPORTANT]
====
Se você achar que isso não é verdade para as políticas do Gatekeeper, informe e trabalharemos para garantir que a política do Gatekeeper seja executada com {short-project-name}.
====


As políticas precisam ser compiladas com a CLI `opa` para o destino `wasm`.

Para a execução de políticas, você pode ler mais sobre oxref:tutorials/writing-policies/rego/02-builtin-support.adoc[suporte integrado] do Open Policy Agent em {short-project-name}.
