= Referências de métricas 
:revdate: 2025-11-07
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

Esta página define métricas comuns relacionadas ao Kubernetes coletadas pelo SUSE Observability e explica como elas são computadas.

=== container_memory_usage

[horizontal]
Nome:: `+container_memory_usage+`
Tipo:: medidor
Unidade:: bytes
Fonte:: Leitura direta da hierarquia do cgroup do contêiner.

[cols="1,3"]
|===
|versão do cgroup | Arquivo de origem

|v1 | `+memory.usage_in_bytes+`
|v2 | `+memory.current+`
|===

Resumo:: A quantidade total de memória que está sendo usada no momento pelo cgroup e seus descendentes. Essa é uma soma que inclui a memória anônima (RSS), o cache de página e a memória do kernel. Use uma das métricas a seguir para obter mais detalhes sobre uma área de memória específica.

=== container_memory_kernel

[horizontal]
Nome:: `+container_memory_kernel+`
Tipo:: medidor
Unidade:: bytes
Fonte:: Leitura direta da hierarquia do cgroup do contêiner.

[cols="1,3"]
|===
|versão do cgroup | Arquivo de origem

|v1 | `+memory.kmem.usage_in_bytes+`
|v2 | `+memory.stat+` -> `+kernel+` dentro do arquivo
|===
Resumo:: Quantidade de memória total do kernel, incluindo (kernel_stack, pagetables, percpu, vmalloc, slab)

=== container_memory_rss

[horizontal]
Nome:: `+container_memory_rss+`
Tipo:: medidor
Unidade:: bytes
Fonte:: Leitura direta da hierarquia do cgroup do contêiner.

[cols="1,3"]
|===
|versão do cgroup | Arquivo de origem

|v1 | `+memory.stat+` -> `+total_rss+` dentro do arquivo
|v2 | `+memory.stat+` -> `+anon+` dentro do arquivo
|===
Resumo:: O tamanho do conjunto residente (RSS) da memória anônima. Essa é a memória sem suporte de arquivo (heap e pilha) usada ativamente pelos processos dentro do cgroup. Esse valor geralmente reflete o verdadeiro "conjunto de trabalho" do aplicativo. 

=== container_memory_cache

[horizontal]
Nome:: `+container_memory_cache+`
Tipo:: medidor
Unidade:: bytes
Fonte:: Leitura direta da hierarquia do cgroup do contêiner.

[cols="1,3"]
|===
|versão do cgroup | Arquivo de origem

|v1 | `+memory.stat+` -> `+total_cache+` dentro do arquivo
|v2 | `+memory.stat+` -> `+file+` dentro do arquivo
|===
Resumo:: O cache de página (memória usada para armazenar em cache os dados do sistema de arquivos, incluindo tmpfs e memória compartilhada).
