include::partial$variables.adoc[]
= Reutilização de ValidatingAdmissionPolicies
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Saiba como reutilizar e validar políticas de admissão no Kubernetes usando {project-name}'s (cel-policy).
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "ValidatingAdmissionPolicies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "ValidatingAdmissionPolicies"]
:sidebar_label: Reutilização de VAPs
:current-version: {page-origin-branch}

Kubernetes vanilla https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy[Validando políticas] consiste nos seguintes recursos:

* ValidatingAdmissionPolicy: descreve a lógica no CEL. Opcionalmente, ele também aceita parâmetros em `spec.paramKind`.
* ValidatingAdmissionPolicyBinding: define o escopo da política.

Vejamos um exemplo concreto. Esses e outros podem ser reutilizados com o {project-name}'s`cel-policy` com pouco esforço.

== ValidatingAdmissionPolicy (Política de validação de admissão)

A ValidatingAdmissionPolicy a seguir foi adaptada do sitehttps://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#creating-a-validatingadmissionpolicy[Kubernetes docs].

Essa política verifica se o número de réplicas em implantações é menor ou igual a um padrão `maxreplicas` de 5. Os usuários podem substituir esse padrão por Namespace ou Deployment e escolher um número menor por meio do uso de um parâmetro.

Ele é encadernado com um `ValidatingAdmissionPolicyBinding`. Portanto, isso afeta apenas os Namespaces que têm um rótulo `environment` definido como `test`.

../vap-policy-example.yaml
[,yaml]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "replicalimit-policy.example.com"
spec:
  failurePolicy: Fail # (1)
  matchConstraints: # (2)
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  variables: # (3)
    - name: maxReplicas # hardcoded global default
      expression: int(5)
  paramKind: # (4)
    apiVersion: v1
    kind: ConfigMap # user-provided override
  validations: # (5)
    - expression: |
        object.spec.replicas <= (
          has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
          ? int(params.data.overrideReplicas)
          : variables.maxReplicas
        )
      messageExpression: |
        'The number of replicas must be less than or equal to ' +
        string( has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
          ? int(params.data.overrideReplicas)
          : variables.maxReplicas)
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "replicalimit-binding-test.example.com"
spec:
  policyName: "replicalimit-policy.example.com"
  validationActions: [Deny] # (7)
  matchResources: # (8)
    namespaceSelector:
      matchLabels:
        environment: test
  paramRef: # (4)
    name: "replica-limit-override"
    namespace: "test"
    parameterNotFoundAction: Deny
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replica-limit-override
  namespace: test
data:
  overrideReplicas: "3"
----

Aqui, temos uma política equivalente em {short-project-name}:

### {short-project-name}'s `cel-policy`

../cel-policy-example.yaml
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: Resource validation # (9)
    io.kubewarden.policy.severity: low # (9)
  name: "cel-policy-replica-example"
spec:
  module: registry://ghcr.io/kubewarden/policies/cel-policy:v1.4.0
  failurePolicy: Fail # (6). Webhook behavior. Defaults to "Fail"
  mode: protect # (7). Defaults to "protect"
  rules: # (2)
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["deployments"]
  contextAwareResources: # (10). Fine-grained perms for accessing resources
    - apiVersion: v1
      kind: ConfigMap
  settings:
    failurePolicy: Fail # (1). CEL behavior. Defaults to "Fail"
    variables: # (3)
      - name: "replicas"
        expression: "object.spec.replicas"
      - name: maxReplicas
        expression: int(5)
    paramKind: # (4)
      apiVersion: v1
      kind: ConfigMap # user-provided override
    paramRef: # (4)
      name: "replica-limit-override"
      namespace: "test"
      parameterNotFoundAction: Deny
    validations: # (5)
      - expression: |
          object.spec.replicas <= (
            has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
            ? int(params.data.overrideReplicas)
            : variables.maxReplicas
          )
        messageExpression: |
          'The number of replicas must be less than or equal to ' +
          string( has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
            ? int(params.data.overrideReplicas)
            : variables.maxReplicas)
  backgroundAudit: true # (9). Defaults to "true"
  namespaceSelector: # (8)
    matchLabels:
      environment: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replica-limit-override
  namespace: test
data:
  overrideReplicas: "3"
----

Observe os números comentados em ambos os manifestos YAML. Vamos expandi-las:

[cols="1,1,1,3", options="header"]
|===
| #   | Campo VAP                         | `cel-policy` campo                       | Descrição

| 1   | `failurePolicy`                   | `settings.failurePolicy`                 | Comportamento do CEL, para quando a expressão do CEL for avaliada como falsa, houver erros de tempo de execução do CEL ou houver um CEL inválido ou mal configurado. Por exemplo, uma expressão CEL que retorna falso, parâmetros ausentes ou variáveis ausentes. Não confundir com (6).
| 2   | `matchConstraints`                | `rules`                                  | Ambos aceitam o mesmo https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#rulewithoperations-v1-admissionregistration[RuleWithOperations] que informa a que tipo de recurso a política se aplica.
| 3   | `variables`                       | `settings.variables`                     | Em {short-project-name}'s `cel-policy`, as expressões que definem variáveis estão em `settings.variables`. Fora isso, eles são equivalentes.
| 4   | `paramKind`,`paramRef`            | `settings.paramKind`,`settings.paramRef` | Em {short-project-name}'s `cel-policy`, as definições de parâmetros estão em `settings.paramKind`, `settings.paramRef`. Fora isso, eles são equivalentes.
| 5   | `validations`                     | `settings.validations`                   | Em {short-project-name}'s `cel-policy`, as expressões que definem validações estão em `settings.validations`. Fora isso, eles são equivalentes.
| 6   | `---`                             | `failurePolicy`                          | Comportamento do webhook, para erro ou tempo limite da API do Kubernetes, ou para avaliação de matchConditions. Não confundir com (1).
| 7   | `validationActions`               | `mode`                                   | `mode` tem como opções `protect` e `monitor`. A auditoria é um recurso mais completo em {short-project-name}, consulte (9).
| 8   | `matchResources`                  | `namespaceSelector`, `objectSelector`    | Defina maneiras de restringir usando seletores. As políticas de {short-project-name} têm os nomes `namespaceSelector` e `objectSelector`.
| 9   | `auditAnnotations` (não ilustrado) | `backgroundAudit`, anotações           | Em vez disso, use os campos {short-project-name} para definir o uso da política no xref:explanations/audit-scanner/audit-scanner.adoc[Audit Scanner] e sua categoria e gravidade no OpenReports.
|10|`---`|`contextAwareResources` permissões|{short-project-name}As políticas da } têm permissões refinadas para a leitura de recursos do cluster. Aqui ele é usado para ler os parâmetros.
|     | `matchConditions`                 | `matchConditions`                        | {short-project-name}`matchConditions` (não retratada neste exemplo).
|     | `---`                             | {short-project-name}-apenas recursos                 | Para outros recursos, consulte os demais exemplos do tutorial CEL.
|===

[TIP]
====

Você pode usar a ferramenta `kwctl` para migrar uma política VAP para {short-project-name}.

Este xref:howtos/vap-migration.adoc[guia de migração de VAP] descreve como fazer isso.

====


=== Equivalências ainda a serem implementadas

Há alguns recursos do VAP que ainda não foram implementados. Se estiver ansioso por eles, entre em contato conosco. São elas:

* VAP https://pkg.go.dev/k8s.io/apiserver/pkg/cel/library#Authz[biblioteca de autorizadores].
* VAP https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/[Anotações de auditoria](ValidatingAdmissionPolicy `spec.auditAnnotations` quando ValidatingAdmissionPolicyBinding `spec.validationActions` estiver definido como "Audit").
Isso é coberto pelo xref:explanations/audit-scanner/audit-scanner.adoc[Audit Scanner] e pelo PolicyReports do {short-project-name}, que permite auditar os recursos já existentes no cluster.
* CEL https://kubernetes.io/docs/reference/using-api/cel/#resource-constraints[restrições de recursos e limite de custo estimado].
Isso é coberto pela xref:reference/policy-evaluation-timeout.adoc[proteção de tempo limite da política] geral do {short-project-name}.

== Aplicação da política

Como de costume, podemos implementar nossa política instanciando seu manifesto:

[subs="+attributes",console]
----
$ kubectl apply -f ./cel-policy-example.yaml
----

E, em seguida, teste-o instanciando uma implantação:

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    environment: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
EOF

namespace/test created
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-cel-policy-replica-example.kubewarden.admission" denied the request:
  The number of replicas must be less than or equal to 5
----
