include::partial$variables.adoc[]
= Políticas de CEL com reconhecimento de contexto
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure políticas com reconhecimento de contexto para garantir regras de ingresso exclusivas entre hosts, evitando conflitos com as bibliotecas de extensão CEL do {project-name}.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "context-aware", "context", "awaree", "ingress"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "context-aware", "context", "aware", "ingress"].
:sidebar_label: Políticas com reconhecimento de contexto
:current-version: {page-origin-branch}

{project-name}'s `cel-policy` suporta o recurso de xref:reference/spec/05-context-aware-policies.adoc[reconhecimento de contexto]. A política tem a capacidade de ler as informações do cluster e tomar decisões com base em outros recursos existentes além do recurso que acionou a avaliação da política por meio da solicitação de admissão.

Para isso, podemos usar o https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[{short-project-name}'s CEL extension libraries for host capabilities] incluído na política.

== Exemplo: Ingresso exclusivo

Vamos escrever uma política que, na criação ou atualização de Ingresses, verifique se o Ingress é exclusivo, para que os hosts tenham no máximo uma regra de Ingress.

Para isso, declaramos que a política é sensível ao contexto. Também declaramos as permissões detalhadas de que precisamos para ler outros recursos do Ingress. Isso é obtido com`spec.contextAwareResources` (1). Podemos obter um ponto de partida, como de costume, usando `kwctl`:

[subs="+attributes",console]
----
$ kwctl scaffold manifest -t ClusterAdmissionPolicy \
  registry://ghcr.io/kubewarden/policies/cel-policy:v1.0.0` \
  --allow-context-aware
----

Que, então, podemos editar para ser relevante para nossos recursos do Ingress:

[subs="+attributes", yaml, title="./cel-policy-ingress.yaml"]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "unique-ingress"
  annotations:
    io.kubewarden.policy.category: Best practices
    io.kubewarden.policy.severity: low
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  failurePolicy: Fail
  rules:
    - apiGroups: ["networking.k8s.io"]
      apiVersions: ["v1"]
      resources: ["ingresses"]
      operations: ["CREATE", "UPDATE"]
  contextAwareResources: # (1)
    - apiVersion: networking.k8s.io/v1
      kind: Ingress

----

Agora, precisamos escrever o código CEL que buscará os Ingresses existentes no cluster. Para isso, usamos a [{short-project-name} CEL extension library](https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities).
Em especial, os recursos do host `kw.k8s`, que nos permitem consultar o cluster para GroupVersionKinds. Você pode ver os documentos disponíveis para as funções CEL [aqui] (https://pkg.go.dev/github.com/kubewarden/cel-policy/internal/cel/library).

A biblioteca usa um padrão de construtor, assim como as extensões do Kubernetes CEL upstream; chamar um método de função CEL retorna um objeto CEL que, por si só, tem métodos de função específicos. Isso simplifica a certeza do escopo e dos retornos do nosso código CEL.

Nesse caso, usaremos `kw.k8s.apiVersion("v1").kind("Ingress")`; aqui chamamos a função `apiVersion()` da biblioteca `kw.k8s`, que nos retorna um objeto`<ClientBuilder>`. Esse objeto tem o método `<ClientBuilder>.kind()`, que retorna uma lista de todos os recursos, em uma matriz chamada `items`.

Com isso, salvamos a lista de Ingresses no cluster em uma variável:

```yaml
variables:
  - name: knownIngresses
    expression: kw.k8s.apiVersion("networking.k8s.io/v1").kind("Ingress").list().items
```

Em seguida, criamos uma lista de hosts a partir desses Ingresses. Observe que pode haver vários hosts por Ingress, portanto, essa expressão contém uma matriz de matrizes (que é uma limitação atual da linguagem CEL):

[subs="+attributes",yaml]
----
variables:
  - name: knownHosts
    expression: |
      variables.knownIngresses.map(i, i.spec.rules.map(r, r.host))
----

No entanto, isso não cuida corretamente das operações UPDATE; para isso, precisamos remover o objeto atual e extrair os hosts dos Ingresses restantes.
Podemos fazer isso com um `filter()` no objeto atual em `object`.
Com isso, as operações UPDATE são verificadas corretamente. Isso também significa que a política também informará corretamente os resultados ao Audit Scanner. Ele terá a seguinte aparência:

[subs="+attributes",yaml]
----
variables:
  - name: knownHosts
    expression: |
      variables.knownIngresses
      .filter(i, (i.metadata.name != object.metadata.name) && (i.metadata.namespace != object.metadata.namespace))
      .map(i, i.spec.rules.map(r, r.host))
----

Também precisamos de uma lista de hosts na solicitação atual do Ingress para comparação:

[subs="+attributes",yaml]
----
variables:
  - name: desiredHosts
    expression: |
      object.spec.rules.map(r, r.host)
----

Com essas duas variáveis, podemos fazer uma interseção de conjuntos entre os hosts conhecidos e os hosts desejados e, se houver algum, rejeitamos:

[subs="+attributes",yaml]
----
validations:
  - expression: |
      !variables.knownHost.exists_one(hosts, sets.intersects(hosts, variables.desiredHosts))
    message: "Cannot reuse a host across multiple ingresses"
----

Juntando tudo isso, a política tem a seguinte aparência:

```yaml title="./cel-policy-ingress.yaml" apiVersion: policies.kubewarden.io/v1 kind: Metadados de ClusterAdmissionPolicy: nome: "unique-ingress" anotações: io.kubewarden.policy.category: Melhores práticas io.kubewarden.policy.severity: low spec: module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0 failurePolicy: Regras de falha:- apiGroups: ["networking.k8s.io"] apiVersions: ["v1"] recursos: ["ingresses"] operações: ["CREATE", "UPDATE"] contextAwareResources:- apiVersion: networking.k8s.io/v1 kind: Configurações do Ingress: variáveis: - name: knownIngresses expression: | kw.k8s.apiVersion("networking.k8s.io/v1").kind("Ingress").list().items - name: knownHosts expressão: | variables.knownIngresses .filter(i, (i.metadata.name != object.metadata.name) && (i.metadata.namespace != object.metadata.namespace)) .map(i, i.spec.rules.map(r, r.host)) - nome: desiredHosts expressão: | object.spec.rules.map(r, r.host) validações:- expressão: | !variables.knownHosts.exists_one(hosts, sets.intersects(hosts, variables.desiredHosts)) message: "Não é possível reutilizar um host em vários ingresses"

```

## Deploying the policy

As normal, we can deploy our policy by instantiating its manifest:

```console
$ kubectl apply -f ./cel-policy-example.yaml
```

Agora podemos testá-lo instanciando o Ingresses. O primeiro será bem-sucedido, pois não há nenhum outro alvo para esse host:

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host-foobar-1
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: service1
            port:
              number: 80
EOF
----

Mas a segunda resultará em uma rejeição:

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host-foobar-2
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service2
            port:
              number: 80
EOF
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-unique-ingress.kubewarden.admission" denied the request:
  Cannot reuse a host across multiple ingresses
----
