include::partial$variables.adoc[]
= Introdução ao agente de política aberta
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Saiba como o Open Policy Agent usa a linguagem Rego para escrever políticas que avaliam e produzem resultados para uma tomada de decisão segura.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "open policy agent", "opa", "rego"]
:sidebar_label: Introdução
:current-version: {page-origin-branch}

[NOTE]
====
O suporte ao Open Policy Agent foi introduzido a partir dessas versões:

* kwctl: v0.2.0
* Servidor de políticas: v0.2.0
====


O Open Policy Agent (OPA) é uma estrutura de política de uso geral que usa a linguagem Rego para escrever políticas.

== Introdução

As políticas Rego funcionam recebendo uma entrada para avaliar e produzem uma saída como resposta.
Nesse sentido, a OPA não tem ferramentas específicas para direcionar políticas de gravação para o Kubernetes.

Especificamente, as políticas na OPA recebem uma entrada JSON e produzem uma saída JSON.
O servidor OPA está configurado para receber solicitações de revisão de admissão do Kubernetes.
As políticas recebem um objeto Kubernetes `+AdmissionReview+` no formato JSON.
Eles precisam retornar um objeto `+AdmissionReview+` válido como resultado da avaliação.

== Compatibilidade com as políticas existentes

Todas as políticas podem ser compiladas para o destino `+wasm+` (WebAssembly) com a ferramenta oficial `+opa+` CLI.

Em termos de execução de políticas, você pode ler mais sobre o xref:tutorials/writing-policies/rego/02-builtin-support.adoc[suporte interno da OPA] implementado em {short-project-name}.
