= Instrumentação de aplicativos Node.js
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Instrumentação automática

A instrumentação automática para Node.js é feita com a inclusão das bibliotecas Javascript de instrumentação automática em seu aplicativo.  uma ampla variedade de https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node#_supported_instrumentations[Há suporte para].

A instrumentação automática não exige nenhuma modificação no aplicativo. Para configurá-lo, siga estas etapas:

. Adicione o SDK de instrumentação do Open Telemetry ao seu aplicativo:
+
[,bash]
----
npm install --save @opentelemetry/api
npm install --save @opentelemetry/auto-instrumentations-node
----

. Atualize o comando que inicia seu aplicativo para carregar o SDK, seja atualizando o ponto de entrada ou o comando da imagem do docker ou atualizando o endereço `+command+` no manifesto do Kubernetes para seu aplicativo. Adicionar `+--require @opentelemetry/auto-instrumentations-node/register+`:
+
[,bash]
----
node --require @opentelemetry/auto-instrumentations-node/register app.js
----

. Implemente seu aplicativo com as variáveis de ambiente adicionais xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[para configurar o nome do serviço e o ponto de extremidade do exportador]; os protocolos compatíveis são gRPC e protobuf sobre HTTP.
. Verifique se o SUSE Observability está recebendo rastreamentos e/ou métricas, procurando as métricas/rastreamentos no explorador de métricas/rastreamentos para o nome do seu serviço

Para obter mais detalhes, consulte a https://opentelemetry.io/docs/languages/js/automatic/[documentação do].

[CAUTION]
====
A instrumentação automática configurada por meio de variáveis de ambiente só oferece suporte a rastreamentos até que o https://github.com/open-telemetry/opentelemetry-js/issues/4551[problema do] seja resolvido. Para habilitar as métricas da instrumentação automática, são necessárias alterações no código. Siga as instruções na https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[documentação do] para fazer essas alterações.
====


== Instrumentação manual

A instrumentação manual pode ser usada quando você precisa de métricas, rastreamentos ou registros de partes do código que não são compatíveis com a instrumentação automática. Por exemplo, bibliotecas sem suporte, código interno ou métricas de nível comercial.

Para capturar esses dados, você precisa modificar seu aplicativo.

. Incluir o Open Telemetry SDK como uma dependência
. Adicione código ao seu aplicativo para capturar métricas, períodos ou registros quando necessário

Há uma documentação detalhada sobre isso nas https://opentelemetry.io/docs/languages/js/instrumentation/[páginas de documentos do].

Certifique-se de usar o exportador OTLP e configurar o endpoint do exportador corretamente no código. Consulte também a https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[documentação do]. Supondo que você tenha configurado o exportador conforme xref:/setup/otel/collector.adoc[documentado], o ponto de extremidade que precisa ser configurado é `+http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317+`, usando gRPC. Consulte também xref:/setup/otel/instrumentation/sdk-exporter-config.adoc#_grpc_vs_http[gRPC vs HTTP], caso o gRPC seja problemático.
