= Copia de seguridad
:revdate: 2025-11-06
:page-revdate: {revdate}

Dado que {elemental-product-name} se ejecuta como parte de Rancher, los recursos de {elemental-product-name} se incluyen en la copia de seguridad de Rancher.
Para obtener más información sobre las opciones de copia de seguridad, restauración y recuperación ante desastres de oficial https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.html[Rancher, consulte la documentación].

== Instalar el operador rancher-backup para Rancher

Siga la https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up.html[guía] para aprender a instalar y configurar el Rancher backup-operator.


== Copia de seguridad {elemental-product-name} con rancher-backup operator

Cree un `backup object` (adaptado a sus necesidades) para realizar copias de seguridad de Rancher ejecutándose en un clúster Kubernetes.

[,yaml]
----
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: rancher-backup
spec:
  resourceSetName: rancher-resource-set
  schedule: "10 3 * * *"
  retentionCount: 10
----

El operador de rancher-backup ofrece varias opciones de programación, encriptación y clases de almacenamiento.
Puede explorar todas las opciones leyendo la https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.html[documentación oficial de].

Compruebe los registros del operador de rancher-backup.

[,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

Verifique si el archivo de respaldo fue creado en el Volumen Persistente.

[,shell]
----
...
INFO[2022/10/17 07:45:04] Finding files starting with /var/lib/backups/rancher-backup-430169aa-edde-4a61-85e8-858f625a755b*.tar.gz
INFO[2022/10/17 07:45:04] File rancher-backup-430169aa-edde-4a61-85e8-858f625a755b-2022-10-17T05-15-00Z.tar.gz was created at 2022-10-17 0
...
----
