= Restaurar
:revdate: 2025-09-08
:page-revdate: {revdate}

Siga esta guía para restaurar una configuración de {elemental-product-name} a partir de una copia de seguridad con Rancher.

== Preparar el operador rancher-backup y los archivos de copia de seguridad para restaurar

Vaya a oficial https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher[la documentación] y asegúrese de que `rancher-backup operator` está instalado y tiene acceso a los archivos de copia de seguridad.

Para realizar una copia de seguridad de los recursos de {elemental-product-name}, primero debe seguir esta xref:operator-operational-tasks/backup.adoc[documentación].

== Restaurar la configuración de {elemental-product-name} con rancher-backup operator

Cree un `restore object` (adaptado a sus necesidades) para restaurar el tarball de copia de seguridad.

[,yaml]
----
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: elemental-restore
spec:
  backupFilename: rancher-backup-430169aa-edde-4a61-85e8-858f625a755b-2022-10-17T05-15-00Z.tar.gz
----

Aplicar manifiesto en Kubernetes.

[,shell]
----
kubectl apply -f elemental-restore.yaml
----

Compruebe los registros del operador de rancher-backup.

[,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

Compruebe si el archivo de copia de seguridad se ha restaurado correctamente.

[,shell]
----
...
INFO[2022/10/31 06:34:50] Processing controllerRef apps/v1/deployments/rancher
INFO[2022/10/31 06:34:50] Done restoring
...
----

Continúe con el procedimiento de la https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster[documentación de]
