= Registrar un SO no gestionado
:revdate: 2025-09-08
:page-revdate: {revdate}

Normalmente, el {elemental_operator_url}[{elemental_operator_name}] gestiona los sistemas operativos instalados y configurados por el {elemental_toolkit_url}[{elemental_toolkit_name}]. +
Por ejemplo, para automatizar la instalaciĂ³n, actualizaciĂ³n y restablecimiento del sistema operativo, `elemental-register` se basa en la CLI de `elemental` para ejecutar estas operaciones.

No obstante, tambiĂ©n es posible registrar y aprovisionar sistemas "Toolkitless" en {elemental-product-name}.

En este caso, es necesario instalar xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_register_command_line_tool[elemental-register] en el sistema. +
Opcionalmente, se puede instalar el xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent]. Tenga en cuenta que sin `elemental-system-agent`, {elemental_operator_name} no podrĂ¡ aprovisionar ningĂºn clĂºster k8s en la mĂ¡quina. En este caso, {elemental_operator_name} sĂ³lo puede utilizarse para fines de inventario del sistema operativo.

Por Ăºltimo, en el clĂºster de gestiĂ³n, `MachineRegistration` debe activar la bandera `spec.config.elemental.registration.no-toolkit`.

Una vez que `no-toolkit` estĂ© habilitado en el `MachineRegistration`, y se produzca un nuevo registro utilizando `elemental-register --install` en el sistema, se crearĂ¡ un nuevo `MachineInventory` en el clĂºster de gestiĂ³n:

[,bash]
----
kubectl -n fleet-default describe machineinventory my-unmanaged-os-machine
----

La direcciĂ³n `MachineInventory` llevarĂ¡ la anotaciĂ³n `elemental.cattle.io/os.unmanaged: "true"`, que indica que esta mĂ¡quina no estĂ¡ gestionada y tiene una funcionalidad limitada.

En el sistema, al registrarse correctamente, se crean automĂ¡ticamente los archivos `/etc/rancher/elemental/agent/config.yaml` y `/var/lib/elemental/agent/elemental_connection.json` para configurar el `elemental-system-agent`.
El componente `elemental-system-agent` es necesario para el aprovisionamiento de K8s y los activadores de Reinicio.

Cuando se activa un xref:node-operational-tasks/reset.adoc[reinicio de la mĂ¡quina], por ejemplo borrando directamente el `MachineInventory`, el `elemental-system-agent` ejecutarĂ¡ un plan de reinicio simple que crearĂ¡ el archivo centinela `/var/lib/elemental/.unmanaged_reset`. +
La presencia de este archivo indica que la mĂ¡quina necesita un reinicio. Esto puede implicar detener servicios, desinstalar paquetes, formatear dispositivos, etc., dependiendo de cĂ³mo se gestione la mĂ¡quina.

== Funciones compatibles

* Registro de un `MachineInventory`
* K8s provisioning (cuando el xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] estĂ¡ instalado y funcionando en la mĂ¡quina)
* Disparadores de reinicio (cuando el xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] estĂ¡ instalado y funcionando en la mĂ¡quina)

== Funciones no compatibles

* xref:references/cloud-config-reference.adoc[ConfiguraciĂ³n] impulsada por Cloud-init
* xref:node-operational-tasks/upgrade.adoc[Actualizaciones] del SO
* xref:node-operational-tasks/reset.adoc[Reinicio del] SO
