= Monitore
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

== Übersicht

SUSE Observability hat die besten Praktiken über Monitore kodiert. SUSE Observability überwacht nicht nur Metriken, Ereignisse oder Protokolle, sondern kann auch die Topologie und Metadaten überwachen, um allgemeine Probleme zu erkennen und die Einhaltung von Branchenstandards zu gewährleisten.
Durch die Kombination von Monitoren mit unserer einzigartigen Fehlerbehebungsintelligenz erkennt SUSE Observability schnell Probleme, die damit zusammenhängen, und gibt Ratschläge zu deren Behebung. Dieser proaktive Ansatz verringert das Risiko unentdeckter Probleme und trägt zur Aufrechterhaltung einer gesunden und robusten Kubernetes-Umgebung bei.
Die Monitore werden von Abhilfeleitfäden begleitet, die für die jeweilige Ressource und den überwachten Zustand spezifisch sind, um unsere Benutzer bei der Fehlersuche zu unterstützen.

== Ergebnisse überwachen

Die Monitorergebnisse werden an zwei Stellen angezeigt:

. Auf den Hervorhebungsseiten aller Ressourcen können Sie sofort sehen, was los ist und wie Sie es beheben können.
. Wenn Sie ein Element in der Topologie auswählen, erhalten Sie auf der rechten Seite einen schnellen Hinweis auf Probleme mit dieser Komponente.

== Sanierungsleitfäden

Abhilfemaßnahmen werden in der Schublade "Monitorstatus" angezeigt, die erscheint, wenn Sie einen Monitor öffnen, indem Sie auf die Meldung in der Highlight-Perspektive einer Ressource klicken.

== Siehe auch

* xref:/use/alerting/kubernetes-monitors.adoc[Sofort einsatzbereite Monitore für Kubernetes]
