= Autenticação
:revdate: 2025-09-08
:page-revdate: {revdate}

A autenticação ocorre durante a integração da máquina, quando a máquina _se registra_ no site {elemental_operator_name}.

{elemental-product-name} por padrão, autentica os hosts por meio do _Trusted Platform Module_ (TPM): a máquina é autenticada por meio de _atestado_, ou seja, a máquina comprova sua identidade por meio do dispositivo TPM.

Para que _o atestado_ funcione, cada máquina de integração*deve ter um dispositivo TPM 2.0*; caso contrário, não será possível registrar-se usando a autenticação segura do TPM.

== Alternativas ao TPM

*O único método de registro oficialmente suportado é baseado no atestado TPM e requer dispositivos com TPM 2.0 ativado.*

Se você quiser registrar dispositivos sem um chip TPM 2.0 ignorando a autenticação segura, há várias maneiras de _identificar_ exclusivamente essas máquinas e permitir o registro:

* emulação de um dispositivo TPM por meio de uma implementação simples de software
* identificando-se por meio de seu endereço MAC de rede
* identificando-se usando seu SMBIOS UUID

O método de autenticação/identificação pode ser especificado noxref:references/machineregistration-reference.adoc#_config_elemental_registration[campo config:elemental:registration:auth] do recurso MachineRegistration.

[CAUTION]
====
O único método *de autenticação* seguro e com suporte oficial no site {elemental-product-name} é o padrão, baseado no atestado do TPM.
As alternativas de TPM podem ser usadas para fins de demonstração ou implementações locais, mas não são recomendadas para uso em produção, pois a identidade dos computadores de integração não é verificada com segurança.
====

=== Emulação de TPM

A emulação do TPM realiza a autenticação usando um software que imita o comportamento do TPM e que está incorporado no site {elemental_register_name}.
As chaves do dispositivo TPM emulado são todas geradas por uma única semente de forma determinística: a mesma semente resulta nas mesmas chaves TPM, portanto, uma semente diferente deve ser coletada em cada host de registro.

A emulação de TPM é ativada configurando os campos `+emulate-tpm+` e `+emulated-tpm-seed+` na configuração `+MachineRegistration+` (consulte a xref:references/machineregistration-reference.adoc#_config_elemental_registration[seção config:elemental:registration na referência MachineRegistration] para obter mais detalhes).

.Exemplo de MachineRegistration usando emulação de TPM
[,yaml]
----
include::example$authentication/registration-emulate-tpm.yaml[]
----

A configuração da emulação TPM é detalhada na xref:operator-operational-tasks/tpm.adoc#_add_tpm_emulation_to_bare_metal_machine[seção Configuração da emulação TPM].

=== Identificação do endereço MAC

Ao usar a identificação de endereço MAC, o host se registra no site {elemental_operator_name} usando o endereço MAC da placa de interface de rede (NIC) como identificador.
Caso a máquina tenha mais de uma interface de rede, os endereços MAC são classificados lexicograficamente e o primeiro é selecionado.

Para substituir a autenticação TPM pela identificação do endereço MAC, basta definir o valor `+mac+` para o campo `+auth+` na xref:references/machineregistration-reference.adoc#_config_elemental_registration[seção config:elemental:registration na referência MachineRegistration].

.exemplo de MachineRegistration usando o endereço MAC como identificador de máquina
[,yaml]
----
include::example$authentication/registration-mac.yaml[]
----

[CAUTION]
====
O endereço MAC é considerado exclusivo pelo site {elemental_operator_name}.
Isso é verdadeiro para dispositivos físicos, mas se estiver usando máquinas virtuais de diferentes hipervisores e diferentes segmentos de rede, cabe ao administrador garantir que as VMs de registro tenham um endereço MAC exclusivo.
====


=== Identificação SMBIOS UUID

A especificação do BIOS de gerenciamento do sistema (SMBIOS) define estruturas de dados que podem ser usadas para ler informações de gerenciamento produzidas pelo BIOS de um host.

Ao usar o valor `+sys-uuid+` como o campo `+auth+` da xref:references/machineregistration-reference.adoc#_config_elemental_registration[seção config:elemental:registration no MachineRegistration], o host se registra no {elemental_operator_name} usando o valor `+UUID+` da tabela `+System Information+` dos dados SMBIOS do host.

.exemplo de MachineRegistration usando o UUID da tabela SMBIOS System Information como identificador da máquina
[,yaml]
----
include::example$authentication/registration-sys-uuid.yaml[]
----

[CAUTION]
====
O valor do SMBIOS `+System information/UUID+` deve ser preenchido pelo fornecedor do hardware como um UUID exclusivo para o host.

Os dados do SMBIOS nem sempre são confiáveis. Isso depende do fabricante. É possível que o UUID esteja ausente ou que o mesmo UUID seja aplicado a vários dispositivos no mesmo lote.

Cabe ao administrador garantir que as máquinas tenham valores SMBIOS exclusivos `+System information/UUID+` (a ferramenta `+dmidecode+` pode ser útil), caso contrário, as máquinas continuarão substituindo o mesmo recurso `+MachineInventory+` e o provisionamento {elemental-product-name} falhará.
====
