ifdef::ss-ff-stackpacks2_enabled[]
= カスタム統合の概要
:revdate: 2026-01-06
:page-revdate: {revdate}
:description:  カスタム統合の概要

[IMPORTANT]
====
Custom Integrationsはプレプロダクションで未発表の機能であるため、機能の進化に伴い変更される可能性があります。本番での使用は想定していない。しかし、非生産環境でテストすることができる。
====

== 概要

カスタム統合は、Open Telemetry を活用して、様々なソースからの遠隔測定データ（メトリクス、トレース、ログ）を収集し、{stackstate-product-name} に送信します。Open Telemetry を使用することで、ユーザーはアプリケーションやサービスを計測し、パフォーマンス、信頼性、運用の健全性についての洞察を得ることができます。
{stackstate-product-name} 側では、xref:setup/custom-integrations/otelmappings/README.adoc[Open Telemetry Mappings]は、受信したテレメトリデータを処理し、必要な変換を適用し、{stackstate-product-name} 内の適切なエンティティにマッピングする。xref:setup/custom-integrations/monitors/index.adoc[モニター]、xref:setup/custom-integrations/metric-bindings/index.adoc[メトリクス・バインディング]、xref:setup/custom-integrations/ui-presentation/README.adoc[UI プレゼンテーションを]定義することで、取り込まれたテレメトリを UI で表示し、アラートと観測可能性を追加することができる。すべてがxref:setup/custom-integrations/develop.adoc[スタックパックに]包まれて配布される。

== 開発セットアップ

カスタム統合は、{stackstate-product-name} プラットフォームのプリプロダクション・デプロイメントに対して開発する必要があります。カスタム統合の開発を開始するためのプリプロダクション・セットアップを取得するには、2つのオプションがあります：

=== SaaSインスタンス（推奨）：
社内SUSEチームの場合は、{stackstate-product-name} チームにSaaSインスタンスをリクエストすることをお勧めします。これらのインスタンスでは、カスタム統合が有効になっており、少なくとも新しいリリースごとに自動的に更新されます。場合によっては、重要なバグ修正や実験的な機能の追加を含むプレリリースを取得することもあります。
専用チャンネル（予定）にてお問い合わせください。

=== セルフホスト：
helm経由でインストールする際にいくつかの機能フラグを設定することで、自分でホストしている{stackstate-product-name} インストレーションでカスタム統合を有効にすることができます：

    . `custom_integrations_values.yaml` を生成する。このガイドでは、このファイルを `$VALUES_DIR`

+
.$VALUES_DIR/custom_integrations_values.yaml
[,yaml]
----
global:
  features:
    experimentalStackpacks: true
----
+

    . {stackstate-product-name} ヘルムチャートに、生成された値を加えて配置する。 `.$VALUES_DIR/custom_integrations_values.yaml`

+
.helm_deploy.sh
[,text]
----
helm upgrade --install \
    --namespace suse-observability \
    --create-namespace \
    --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
    --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
    --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
    --values $VALUES_DIR/custom_integrations_values.yaml \
    suse-observability \
    suse-observability/suse-observability
----
+

endif::ss-ff-stackpacks2_enabled[]
