include::partial$variables.adoc[]
= {project-name} 用例
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: 使用案例
:sidebar_position: 74
:description: 了解{project-name} 在不同 Kubernetes 环境和角色中的各种用例，包括多种场景。
:keywords: {project-name}文件、用例、案例研究
:doc-persona: kubewarden-all
:doc-type: 解释
:doc-topic: 解释

以下是{project-name}"xref:/personas.adoc[角色]"的几个用例。

== 案例 A：作为 Kubernetes 操作员，我希望确保我的集群安全、合规。

我在`kubewarden` 命名空间中部署了{project-name} 及其默认配置和`kubewarden-defaults` Helm 图表。这将在`kubewarden` 命名空间中部署默认的 PolicyServer 和推荐的 ClusterAdmissionPolicies，完全由 Kubernetes 操作员控制。

作为操作员，我可以在受管命名空间（如`kubewarden` ）下添加更多 PolicyServers，以分配负载和容错。

操作员可以部署更多的 ClusterAdmissionPolicies 和 ClusterAdmissionPolicyGroup。它们会针对任何类型的操作（GET、CREATE、UPDATE、PATCH、DELETE、PROXY）检查所有 Kubernetes 资源。这可确保进入集群的操作安全、合规。

其中包括

* 安全
* 符合（行业标准或公司规定）
* 资源优化（通过变异策略）
* 管理 Kubernetes 环境（通过标签和命名约定）
* 最佳做法
* 图像验证

安全预期会随着时间的推移而改变。群集中以前正确的部署可能不再正确。然而，{short-project-name} 已经接受了集群中的这些业务。在这种情况下，操作员可以部署审计扫描器功能，这是一个定期运行并评估群集中现有资源的 CronJob。这样，即使随着时间的推移，也能确保集群的安全性和合规性。

操作员可以在`monitor` 模式而不是`protect`模式下配置策略，以便在不阻塞操作的情况下了解群集的状态。

操作员可以通过消耗日志和 OpenTelemetry 信息，从策略和{short-project-name} 协议栈中获取信息，用于度量和跟踪。

== 案例 B：作为 Kubernetes 操作员，我想为我的 Kubernetes 用户提供一个框架，让他们可以在自己的命名空间中自助服务。

作为操作员，我按照案例 A 中的方法为自己选择的一组策略部署{short-project-name} 。这为我提供了一个安全的群集基线，其他用户无法逃避。

除了案例 A，我还为每个命名空间设置了不同的角色：可能是团队、团队管理员、测试部署等。我允许每个名称空间管理员在其名称空间中部署 PolicyServers 以及命名的 AdmissionPolicies 和 AdmissionPolicyGroups，从而实现自助服务。
这种架构意味着他们可以控制自己的 PolicyServer 和策略。这些策略只适用于其名称空间，并限制其名称空间的资源使用。

它还允许操作员隔离嘈杂的租户，例如，为需要高吞吐量和低延迟的租户和任务保留性能优越的 PolicyServers。

== 案例 C：作为政策作者，我希望使用我所掌握的工具和语言来编写新政策。

{short-project-name} 通过支持任何可编译为 WebAssembly 的语言作为策略的目标语言，来实现这一目标。这意味着政策作者可以重复使用他们的工作流程（`git` 、CI、编辑、同行评审等）和工具：语言、语言库、测试工具包和框架等。

它允许重新使用特定领域语言（如 Rego、CEL、Kyverno 的 YAML+macros）或通用语言（如 Go、Rust、C#、Javascript，以及任何可编译为 Wasm 的语言）。{short-project-name} 提供了几种语言的xref:/tutorials/writing-policies/index.adoc[SDK]作为一流支持。

{short-project-name} 政策可以是简单的，也可以是复杂的xref:/explanations/context-aware-policies.adoc[情境感知]政策。
情境感知策略还可用于连接不同的工作负载（例如，从长期运行的图像扫描仪服务中获取信息）。

== 案例 D：作为系统集成商，我希望重新使用{short-project-name} 作为安全和合规解决方案的一部分。

作为系统集成商，我希望重复使用{short-project-name} ，并可能通过将其他解决方案纳入{short-project-name} 来重复使用它们。

作为系统集成商，我可以重复使用{short-project-name}.NET Framework 的部分功能。例如，`policy-server` ，通过xref:/howtos/raw-policies.adoc["原始策略 "]功能对 Kubernetes 集群内部或外部的资源进行监管。

系统集成商可以选择部署`kubewarden-controller` 或自行管理 CRD。他们可以根据需要选择部署或扩展审计扫描仪。

系统集成商可以创建新的组件。例如，图像扫描仪，并通过上下文感知策略与之对接，而无需在 Kubernetes 控制器中进行单一实现。

== 非目标

{short-project-name} 并不打算这样做：

- 取代 Kubernetes 内置的安全功能，并对其进行补充：
  - {short-project-name} 提供从 PSP 的迁移。
  - 您可以通过{short-project-name} 的`cel-policy` 重用 ValidatingAdmissionPolicies 和 CEL 策略。
  - {short-project-name} 策略可以更改，而 Pod 安全接入则不能更改。
  - {short-project-name} {short-project-name} 堆栈功能（审计扫描仪、遥测、CRD 管理）使政策受益。
- 提供运行时安全性，如入侵检测或运行时容器隔离。
- 为集群提供主机系统保护。
- 提供无限的政策执行灵活性。为防止 DoS 攻击，策略的处理时间受到限制。