include::partial$variables.adoc[]
= {project-name} in einer groß angelegten Umgebung
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Konfigurieren Sie {project-name}s mit {project-name}, um hohe Verfügbarkeit und Leistung in anspruchsvollen großen Umgebungen zu gewährleisten.
:keywords: [kubewarden, "{project-name}", kubernetes, policyservers, production]
:doc-persona: kubewarden-Bediener, kubewarden-Integrator
:doc-type: howto
:doc-topic: bedienerhandbuch, policy-server, produktion
:sidebar_label: Einsatz in großem Maßstab
:sidebar_position: 21

In diesem Abschnitt wird ein realer Einsatz von {project-name} in einer anspruchsvollen, groß angelegten Umgebung beschrieben. Es wird erläutert, wie {short-project-name} für hohe Verfügbarkeit und Leistung konfiguriert werden kann und was bei hoher Belastung zu erwarten ist.

[IMPORTANT]
====
Weitere Tipps zum Betrieb von {short-project-name} in der Produktion finden Sie in der Dokumentation zu xref:/howtos/production-deployments.adoc[Produktionsimplementierungen].
====

== Überblick über die Umwelt

Die Infrastruktur besteht aus etwa 20 Kubernetes-Clustern. Die größten dieser Cluster zeichnen sich durch eine beträchtliche Größe und Ressourcenmenge aus:

* Knotenpunkte: ~400
* Namensräume: ~4.000
* Verwaltete Ressourcen:
** Schoten: 10,000
** RoleBindings: 13,000
** Eindringlinge: 12,000
** Einsätze: 8,000
** Dienstleistungen: 13,000

== {short-project-name} Konfiguration

Um den Anforderungen dieser Umgebung gerecht zu werden, ist {short-project-name} so konfiguriert, dass der Schwerpunkt auf Workload-Isolierung und Hochverfügbarkeit liegt.

* Durchsetzung der Politik: 22 `ClusterAdmissionPolicies` wird in allen Clustern durchgesetzt, ohne Namensraum-spezifische `AdmissionPolicies`.
* PolicyServer Architecture: Zur Isolierung von Arbeitslasten werden zwei separate `PolicyServer` -Bereitstellungen verwendet:
** Eine `PolicyServer` ist ausschließlich für kontextabhängige Richtlinien vorgesehen.
** Eine zweite `PolicyServer` behandelt alle anderen, nicht kontextabhängigen Richtlinien.
* Skalierbarkeit und Ressourcen:
** Replikate: Jede Bereitstellung von `PolicyServer` umfasst 15 Replikate, um das hohe Anfragevolumen zu bewältigen.
** Ressourcenzuteilung: Jeder Replik werden 300 MB Speicher und 4 CPU-Kerne zugewiesen.

== Leistungsmetriken

Mit dieser Konfiguration wird eine hohe Anzahl von Zulassungsanfragen erfolgreich bewältigt, während die Leistung vorhersehbar bleibt.

* Durchsatz der Zulassungsanfrage: Die Cluster verarbeiten bis zu 300 Zulassungsanfragen pro Sekunde (einschließlich Webhook-Validierungen und Audit-Scans).
* Latenzzeit der Richtlinie:
** Typische Latenzzeit: Die Ausführung kontextabhängiger Richtlinien dauert im Allgemeinen etwa 500 ms.
** Auszeit: In dieser Umgebung mit hohem Durchsatz sind die Webhook-Timeouts auf 2,5 Sekunden konfiguriert, während der `PolicyServer` -Timeout auf 10 Sekunden eingestellt ist. Die meisten Anfragen sind zwar schnell, aber die Infrastruktur ist so ausgelegt, dass gelegentlich langsame Vorgänge bewältigt werden können, ohne die Stabilität des API-Servers zu gefährden.

== Audit Scanner Leistung

Der Audit-Scanner wird eingesetzt, um die kontinuierliche Einhaltung der Vorschriften für die große Anzahl von Ressourcen zu gewährleisten.

* Häufigkeit: Alle 4 Stunden wird ein clusterweites Audit durchgeführt.
* Konfiguration: Der Prüfauftrag ist auf maximale Parallelität abgestimmt, um die Laufzeit zu verkürzen:

[source,shell]
----
--parallel-namespaces: "10"
--parallel-resources: "20"
--parallel-policies: "20"
--page-size: "1000"
----

* Dauer der Prüfung: Selbst auf dem größten Cluster mit Zehntausenden von Ressourcen wird ein vollständiger Prüfungsauftrag in
