include::partial$variables.adoc[]
= Notfall deaktivieren
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Notfall deaktivieren
:sidebar_position: 31
:title: Notfall deaktivieren
:description: Erfahren Sie, wie Sie {project-name} in Notfallsituationen deaktivieren, die zugehörigen Konfigurationen anhalten und löschen und anschließend wiederherstellen können.
:keywords: ["{project-name}", kubewarden, ClusterAdmissionPolicies, AdmissionPolicies, configuration]
:doc-persona: kubewarden-operator
:doc-type: howto
:doc-topic: Bedienungshandbuch

In einem Notfall müssen die Einsatzteams möglicherweise Aktionen durchführen, die {project-name} blockieren würde.

In diesem Dokument wird erklärt, wie Sie {short-project-name} deaktivieren, damit Betriebsteams Clusterausfälle beheben können. Nach Behebung der Situation können die Betriebsteams {short-project-name} neu starten.

== Deaktivieren Sie {short-project-name}

Halten Sie zunächst den {short-project-name} Controller an. Sie tun dies, indem Sie den Einsatz auf Null reduzieren:

[source,console]
----
kubectl scale deployment kubewarden-controller \
  --replicas=0 \
  -n kubewarden
----

[tip]
====
Stellen Sie sicher, dass Sie den Namen des Namespace verwenden, in dem der {short-project-name} Stack bereitgestellt wird.
Hier wird der Stack im `kubewarden` Namespace bereitgestellt.
====

Als nächstes löschen Sie alle `ValidatingWebhookConfigurations` und `MutatingWebhookConfigurations`, die von {short-project-name} erstellt wurden:

[source,console]
----
# Delete all the ValidatingWebhookConfiguration created by {short-project-name}
kubectl delete validatingwebhookconfigurations \
  -l app.kubernetes.io/part-of=kubewarden

# Delete all the MutatingWebhookConfiguration created by {short-project-name}
kubectl delete mutatingwebhookconfigurations \
  -l app.kubernetes.io/part-of=kubewarden
----

== Wiederherstellen {short-project-name}

Wenn der Notfall vorbei ist, stellen Sie den {short-project-name} Stack wieder her, indem Sie den {short-project-name} Controller zurückbringen:

[source,console]
----
kubectl scale deployment kubewarden-controller \
  --replicas=1 \
  -n kubewarden
----

[tip]
====
- Stellen Sie sicher, dass Sie den Namen des Namespace verwenden, in dem der {short-project-name} Stack bereitgestellt wird.
  Hier wird der Stack im `kubewarden` Namespace bereitgestellt.
- Vergewissern Sie sich, dass Sie den Controller auf seinen ursprünglichen Wert zurücksetzen. In diesem Beispiel wird davon ausgegangen, dass nur eine Replik des Controllers ausgeführt wird.
====
Sobald der Controller läuft, gleicht er die verteilten Richtlinien ab. Die zuvor gelöschten Ressourcen `ValidatingWebhookConfiguration` und `MutatingWebhookConfiguration` werden neu erstellt, so dass die Richtlinien durchgesetzt werden.