= Rollen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

== Übersicht

Jedem Benutzer in SUSE Observability muss ein Thema und eine Reihe von xref:/setup/security/rbac/rbac_permissions.adoc[Berechtigungen] zugewiesen werden; diese Kombination wird als Rolle bezeichnet. Eine Rolle beschreibt eine Gruppe von Benutzern, die auf einen bestimmten Datensatz zugreifen können. SUSE Observability wird mit einer Reihe von vordefinierten Rollen ausgeliefert, und Sie können auch Rollen erstellen, die Ihren Anforderungen entsprechen.

== Vordefinierte Rollen

Es gibt vier vordefinierte Rollen in SUSE Observability:

* *Administrator* - hat vollen Zugriff auf alle Ansichten und verfügt über alle Berechtigungen.
* *Hauptbenutzer* - wird in der Regel einem Benutzer gewährt, der SUSE Observability für ein oder mehrere Teams konfigurieren muss, aber nicht die gesamte SUSE Observability-Installation verwalten will.
* *Kubernetes Troubleshooter* - verfügt über alle Berechtigungen, die für die Verwendung von SUSE Observability zur Fehlerbehebung erforderlich sind, einschließlich der Möglichkeit, Monitore zu aktivieren/deaktivieren, benutzerdefinierte Ansichten zu erstellen und die Cli.
* *Gast* - hat nur Lesezugriff auf SUSE Observability.

Die den einzelnen vordefinierten SUSE Observability-Rollen zugewiesenen Berechtigungen finden Sie im Folgenden. Einzelheiten zu den verschiedenen Berechtigungen und deren Verwaltung über die `sts` CLI finden Sie unter xref:/setup/security/rbac/rbac_permissions.adoc[RBAC-Berechtigungen (Role based access control)]

[tabs]
====
Verwalter::
+
--

Die Rolle Administrator (`stackstate-admin`): verfügt über alle zugewiesenen Berechtigungen.

Die der vordefinierten Administratorrolle (`stackstate-admin`) zugewiesenen Berechtigungen sind im Folgenden aufgeführt. Diese wurden mit der `sts` CLI abgerufen. Einzelheiten zu den verschiedenen Berechtigungen und deren Verwaltung über die `sts` CLI finden Sie unter xref:/setup/security/rbac/rbac_permissions.adoc[RBAC-Berechtigungen].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-admin
Got subject from the following subject sources: Static

PERMISSION                      | RESOURCE
create-dashboards               | system
create-favorite-dashboards      | system
create-favorite-views           | system
create-ingestion-api-keys       | system
create-metric-bindings          | system
create-monitors                 | system
create-notifications            | system
create-service-tokens           | system
create-stackpack-configurations | system
create-views                    | system
delete-dashboards               | system
delete-favorite-dashboards      | system
delete-favorite-views           | system
delete-ingestion-api-keys       | system
delete-metric-bindings          | system
delete-monitors                 | system
delete-notifications            | system
delete-service-tokens           | system
delete-stackpack-configurations | system
delete-sync-data                | system
delete-views                    | system
execute-component-actions       | system
execute-monitors                | system
execute-restricted-scripts      | system
execute-scripts                 | system
get-agents                      | system
get-api-tokens                  | system
get-dashboards                  | system
get-ingestion-api-keys          | system
get-metric-bindings             | system
get-metrics                     | system
get-monitors                    | system
get-notifications               | system
get-permissions                 | system
get-service-tokens              | system
get-settings                    | system
get-stackpacks                  | system
get-sync-data                   | system
get-system-notifications        | system
get-topic-messages              | system
get-topology                    | system
get-traces                      | system
get-views                       | system
update-dashboards               | system
update-metric-bindings          | system
update-metrics                  | system
update-monitors                 | system
update-notifications            | system
update-permissions              | system
update-scoped-permissions       | system
update-settings                 | system
update-stackpack-configurations | system
update-stackpacks               | system
update-views                    | system
update-visualization            | system
----

--
Power User::
+
--

Die Hauptbenutzerrolle (`stackstate-power-user`) hat alle Administratorrechte mit Ausnahme der folgenden:

* `execute-restricted-scripts`
* `update-permissions`
* `update-stackpacks`

Die der vordefinierten Hauptbenutzerrolle (`stackstate-power-user`) zugewiesenen Berechtigungen sind im Folgenden aufgelistet. Diese wurden mit der `sts` CLI abgerufen. Einzelheiten zu den verschiedenen Berechtigungen und deren Verwaltung über die `sts` CLI finden Sie unter xref:/setup/security/rbac/rbac_permissions.adoc[RBAC-Berechtigungen].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-power-user
Got subject from the following subject sources: Static

PERMISSION                      | RESOURCE
create-dashboards               | system
create-favorite-dashboards      | system
create-favorite-views           | system
create-metric-bindings          | system
create-monitors                 | system
create-notifications            | system
create-stackpack-configurations | system
create-views                    | system
delete-dashboards               | system
delete-favorite-dashboards      | system
delete-favorite-views           | system
delete-metric-bindings          | system
delete-monitors                 | system
delete-notifications            | system
delete-stackpack-configurations | system
delete-sync-data                | system
execute-component-actions       | system
execute-monitors                | system
execute-scripts                 | system
get-agents                      | system
get-api-tokens                  | system
get-dashboards                  | system
get-metric-bindings             | system
get-metrics                     | system
get-monitors                    | system
get-notifications               | system
get-permissions                 | system
get-settings                    | system
get-stackpacks                  | system
get-sync-data                   | system
get-system-notifications        | system
get-topic-messages              | system
get-topology                    | system
get-traces                      | system
get-views                       | system
update-dashboards               | system
update-metric-bindings          | system
update-metrics                  | system
update-monitors                 | system
update-notifications            | system
update-settings                 | system
update-stackpack-configurations | system
update-views                    | system
update-visualization            | system
----

--
Störungssucher::
+
--

Die Troubleshooter-Rolle (`stackstate-k8s-troubleshooter`) hat Zugriff auf alle in SUSE Observability verfügbaren Daten und die Möglichkeit, Ansichten zu erstellen und Monitore zu aktivieren/deaktivieren.

Die der vordefinierten Troubleshooter-Rolle zugewiesenen Berechtigungen sind unten aufgelistet. Diese wurden mit der `sts` CLI abgerufen. Einzelheiten zu den verschiedenen Berechtigungen und deren Verwaltung über die `sts` CLI finden Sie unter xref:/setup/security/rbac/rbac_permissions.adoc[RBAC-Berechtigungen].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-k8s-troubleshooter
Got subject from the following subject sources: Static

PERMISSION                 | RESOURCE
create-dashboards          | system
create-favorite-dashboards | system
create-favorite-views      | system
create-monitors            | system
create-notifications       | system
create-views               | system
delete-dashboards          | system
delete-favorite-dashboards | system
delete-favorite-views      | system
delete-monitors            | system
delete-notifications       | system
delete-views               | system
execute-monitors           | system
get-agents                 | system
get-api-tokens             | system
get-dashboards             | system
get-metric-bindings        | system
get-metrics                | system
get-monitors               | system
get-notifications          | system
get-permissions            | system
get-settings               | system
get-stackpacks             | system
get-system-notifications   | system
get-topic-messages         | system
get-traces                 | system
get-views                  | system
update-dashboards          | system
update-monitors            | system
update-notifications       | system
update-stackpacks          | system
update-views               | system
update-visualization       | system
----

--
Gast::
+
--

Die Gastrolle (`stackstate-guest`) hat nur Lesezugriff auf SUSE Observability.

Die der vordefinierten Gastrolle zugewiesenen Berechtigungen sind im Folgenden aufgeführt. Diese wurden mit der `sts` CLI abgerufen. Einzelheiten zu den verschiedenen Berechtigungen und deren Verwaltung über die `sts` CLI finden Sie unter xref:/setup/security/rbac/rbac_permissions.adoc[RBAC-Berechtigungen].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-guest
Got subject from the following subject sources: Static

PERMISSION                 | RESOURCE
create-dashboards          | system
create-favorite-dashboards | system
create-favorite-views      | system
delete-dashboards          | system
delete-favorite-dashboards | system
delete-favorite-views      | system
get-api-tokens             | system
get-dashboards             | system
get-metric-bindings        | system
get-metrics                | system
get-monitors               | system
get-notifications          | system
get-permissions            | system
get-settings               | system
get-system-notifications   | system
get-topic-messages         | system
get-traces                 | system
get-views                  | system
update-dashboards          | system
update-visualization       | system
----

--
====

== Benutzerdefinierte Rollen (Konfiguration RBAC)

Zusätzlich zu den vordefinierten Rollen (`stackstate-admin`, `stackstate-power-user`, `stackstate-k8s-troubleshooter`, `stackstate-guest`), die immer verfügbar sind, können benutzerdefinierte Rollen hinzugefügt werden. Es gibt mehrere Möglichkeiten, benutzerdefinierte Rollen hinzuzufügen:

. über die Konfigurationsdatei, mit den gleichen Rechten wie die vordefinierten Rollen
. über die Konfigurationsdatei, mit einer benutzerdefinierten Berechtigung
. bei Verwendung der `sts` CLI werden die Subjekte und ihre Berechtigungen in der Datenbank gespeichert und können während der Laufzeit geändert werden

Rollen, die über die Konfigurationsdatei hinzugefügt werden, erfordern einen Neustart und führen daher zu einer kurzen Ausfallzeit. Mit der CLI erstellte Rollen werden in der Datenbank gespeichert und können zur Laufzeit geändert werden.

=== Benutzerdefinierte Namen für vordefinierte Rollen

Verwenden Sie diese Option, wenn die vordefinierten SUSE Observability-Rollen gut geeignet sind, der externe Authentifizierungsanbieter jedoch andere Namen für die Rollen verwendet. Wenn z.B. der LDAP-Authentifizierungsprovider über ähnliche, aber anders benannte Rollen verfügt, fügen Sie dieses YAML-Snippet in eine `authentication.yaml` ein, um den Rollen aus LDAP die gleichen Rechte und Geltungsbereiche zu geben wie den vordefinierten, gleichwertigen Rollen.

[,yaml]
----
stackstate:
  authentication:
    roles:
      guest: ["ldap-guest-role"]
      powerUser: ["ldap-power-user-role"]
      admin: ["ldap-admin-role"]
      k8sTroubleshooter: ["ldap-troubleshooter-role"]
----

Zur Verwendung in Ihrer SUSE Observability-Installation (oder bereits laufenden Instanz, beachten Sie, dass die API neu gestartet wird):

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

=== Benutzerdefinierte Rollen über die Konfigurationsdatei

Um eine neue Rolle namens `development-troubleshooter` einzurichten, die dieselben Berechtigungen wie die vordefinierte Troubleshooter-Rolle erlaubt, aber nur für den Cluster `dev-test`, fügen Sie dieses YAML-Snippet in ein `authentication.yaml` ein:

[,yaml]
----
stackstate:
  authentication:
    roles:
      custom:
        development-troubleshooter:
          systemPermissions:
          - create-dashboards
          - create-favorite-dashboards
          - create-favorite-views
          - create-monitors
          - create-notifications
          - create-views
          - delete-dashboards
          - delete-favorite-dashboards
          - delete-favorite-views
          - delete-monitors
          - delete-notifications
          - delete-views
          - execute-monitors
          - get-agents
          - get-api-tokens
          - get-dashboards
          - get-metric-bindings
          - get-metrics
          - get-monitors
          - get-notifications
          - get-permissions
          - get-settings
          - get-stackpacks
          - get-system-notifications
          - get-topic-messages
          - get-traces
          - get-views
          - update-dashboards
          - update-monitors
          - update-notifications
          - update-stackpacks
          - update-views
          - update-visualization
          resourcePermissions:
            get-topology:
            - "cluster-name:dev-test"
----

Zur Verwendung in Ihrer SUSE Observability-Installation (oder bereits laufenden Instanz, beachten Sie, dass die API neu gestartet wird):

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

=== Benutzerdefinierte Rollen über die CLI (Observability RBAC)

Um eine neue Rolle mit dem Namen `development-troubleshooter` einzurichten, die dieselben Berechtigungen wie die normale Troubleshooter-Rolle hat, aber nur für den Cluster `dev-test`, muss ein neuer Betreff erstellt werden. Darüber hinaus muss dieses Thema mit den erforderlichen Berechtigungen ausgestattet werden:

. Erstellen Sie das Subjekt (mit demselben Namen wie die Rolle, der Abgleich zwischen Rolle und Subjekt basiert auf dem Namen und unterscheidet Groß- und Kleinschreibung):
+
[,text]
----
sts rbac create-subject --subject development-troubleshooter
sts rbac grant --subject development-troubleshooter --permission get-topology --resource "cluster-name:dev-test"'
----
+

. Konfigurierte Subjekte benötigen Berechtigungen, um auf Teile der Benutzeroberfläche zuzugreifen und darin Aktionen auszuführen. Um die gleichen Berechtigungen wie die Rolle des Troubleshooters zu gewähren, folgen Sie dem folgenden Beispiel:
+
[,text]
----
sts rbac grant --subject development-troubleshooter --permission create-dashboards
sts rbac grant --subject development-troubleshooter --permission create-favorite-dashboards
sts rbac grant --subject development-troubleshooter --permission create-favorite-views
sts rbac grant --subject development-troubleshooter --permission create-monitors
sts rbac grant --subject development-troubleshooter --permission create-notifications
sts rbac grant --subject development-troubleshooter --permission create-views
sts rbac grant --subject development-troubleshooter --permission delete-dashboards
sts rbac grant --subject development-troubleshooter --permission delete-favorite-dashboards
sts rbac grant --subject development-troubleshooter --permission delete-favorite-views
sts rbac grant --subject development-troubleshooter --permission delete-monitors
sts rbac grant --subject development-troubleshooter --permission delete-notifications
sts rbac grant --subject development-troubleshooter --permission delete-views
sts rbac grant --subject development-troubleshooter --permission execute-monitors
sts rbac grant --subject development-troubleshooter --permission get-agents
sts rbac grant --subject development-troubleshooter --permission get-api-tokens
sts rbac grant --subject development-troubleshooter --permission get-dashboards
sts rbac grant --subject development-troubleshooter --permission get-metric-bindings
sts rbac grant --subject development-troubleshooter --permission get-metrics
sts rbac grant --subject development-troubleshooter --permission get-monitors
sts rbac grant --subject development-troubleshooter --permission get-notifications
sts rbac grant --subject development-troubleshooter --permission get-permissions
sts rbac grant --subject development-troubleshooter --permission get-settings
sts rbac grant --subject development-troubleshooter --permission get-stackpacks
sts rbac grant --subject development-troubleshooter --permission get-system-notifications
sts rbac grant --subject development-troubleshooter --permission get-topic-messages
sts rbac grant --subject development-troubleshooter --permission get-traces
sts rbac grant --subject development-troubleshooter --permission get-views
sts rbac grant --subject development-troubleshooter --permission update-dashboards
sts rbac grant --subject development-troubleshooter --permission update-monitors
sts rbac grant --subject development-troubleshooter --permission update-notifications
sts rbac grant --subject development-troubleshooter --permission update-stackpacks
sts rbac grant --subject development-troubleshooter --permission update-views
sts rbac grant --subject development-troubleshooter --permission update-visualization
----

Bitte beachten Sie, dass beim Namen des Betreffs und bei den Berechtigungen zwischen Groß- und Kleinschreibung unterschieden wird.
