include::partial$variables.adoc[]
= Rotación de certificados
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprenda a rotar certificados en su {project-name} sin causar tiempo de inactividad.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["explanations", "certificates"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "certificate", "controller", "reconciliation"]
:sidebar_label: Rotación de certificados
:sidebar_position: 21

{project-name} v1.17.0 eliminó la dependencia cert-manager. El controlador es capaz de gestionar todos los certificados utilizados por todos los componentes. Ahora, el controlador tiene un nuevo bucle de reconciliación que garantiza que los certificados estén siempre actualizados y que la configuración de webhook sea correcta.

La instalación del gráfico Helm realiza la primera generación de certificados. Genera la CA raíz con diez años hasta la expiración. La instalación del gráfico de Helm también genera el certificado del servidor web del webhook del controlador, firmado por la CA raíz. El servidor API lo utiliza para comunicarse con el controlador{short-project-name} y validar los CRD. Tiene un año de caducidad.

Una vez que el controlador se pone en marcha, su reconciliador renueva los certificados automáticamente cuando están a punto de caducar. También actualiza todos los certificados y configuraciones de webhook utilizados por toda la pila de {short-project-name}.

[NOTE]
====
Todos los certificados generados por el cuadro Helm y posteriormente por el controlador utilizan claves ECDSA P256.
====

El bucle de reconciliación renueva los certificados 60 días antes de su expiración.
Los certificados rotan sin tiempo de inactividad. El bucle de reconciliación también se encarga de renovar la CA raíz.

El controlador genera una nueva CA raíz 60 días antes de la expiración. El controlador actualiza el paquete de CA utilizado por todos los webhooks para incluir tanto la nueva CA raíz como la antigua.

El cambio de la CA raíz lleva al reconciliador a volver a crear los certificados emitidos para los webhooks. La propagación de los nuevos certificados requiere un periodo de tiempo. Sin embargo, durante este tiempo el paquete CA actualizado permite al servidor API seguir comunicándose con todos los webhooks sin ningún tiempo de inactividad.

Cuando un nuevo certificado está listo y el antiguo no es válido, el controlador actualiza el paquete de CA, utilizado por los webhooks, para incluir sólo la CA raíz más reciente.

Cuando se renueva un certificado de servidor de políticas o de servidor web del controlador, éste actualiza el secreto con el nuevo certificado firmado por la CA raíz. Gracias a esta función de recarga, el controlador y el servidor de directivas utilizan el nuevo certificado sin necesidad de reiniciar los procesos y, por tanto, sin tiempo de inactividad.
