= 通过 HTTP 发送健康数据
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

== 概述

SUSE Observability 可通过 HTTP 或xref:/setup/cli/cli-sts.adoc[SUSE Observability CLI] 从您自己的数据源同步健康信息。

== SUSE Observability 接收器 API

SUSE Observability Receiver API 接受通用 JSON 对象中的拓扑、度量、事件和健康数据。接收器 API 的默认位置是`<STACKSTATE_RECEIVER_API_ADDRESS>` ，使用`<STACKSTATE_BASE_URL>` 和``<+STACKSTATE_RECEIVER_API_KEY>+`` 构建。

部署在 Kubernetes 或 OpenShift 上的 SUSE Observability 的`<STACKSTATE_RECEIVER_API_ADDRESS>` 是：

[,text]
----
https://<STACKSTATE_BASE_URL>/receiver/stsAgent/intake?api_key=<STACKSTATE_RECEIVER_API_KEY>
----

`<STACKSTATE_BASE_URL>` 和`<STACKSTATE_RECEIVER_API_KEY>` 是在安装 SUSE Observability 时设置的，详情请参阅xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_generate_values_yaml[Kubernetes install - configuration parameters]。

== JSON

=== 普通 JSON 对象

拓扑、遥测和健康数据通过 HTTP POST 发送到接收器 API。所有信息都使用一个通用的 JSON 对象。

[,javascript]
----
{
  "collection_timestamp": 1548855554, // the epoch timestamp for the collection
  "events": {}, // used to send events data
  "internalHostname": "localdocker.test", // the host sending this data
  "metrics": [], // used to send metrics data
  "service_checks": [],
  "topologies": [], // used to send topology data
  "health": // used for sending health data
}
----

=== JSON 健康有效载荷

SUSE Observability 可根据所选的xref:/configure/health/health-synchronization.adoc#_consistency_models[一致性模型]接受健康数据。每种型号可发送的信息如下页所述：

* xref:/configure/health/send-health-data/repeat_snapshots.adoc[重复快照 JSON]
* xref:/configure/health/send-health-data/transactional_increments.adoc[事务增量 JSON]

== 另见

* xref:/setup/cli/cli-sts.adoc[安装 SUSE Observability CLI]
