= 交易要素
:revdate: 2025-10-27
:page-revdate: {revdate}
:description: SUSE 可观察性

== 概述

本页描述了健康同步事务增量一致性模型可发送的确切 JSON 消息。

== JSON 属性："健康"

健康状况可通过xref:/configure/health/send-health-data/send-health-data.adoc#_common_json_object[通用 JSON 对象]的`"health"` 属性发送到 SUSE Observability Receiver API。

[tabs]
====
健康`transactional_increments` JSON 示例::
+
--

[,javascript]
----
   "apiKey":"your api key",
   "collection_timestamp":1585818978,
   "internalHostname":"lnx-343242.srv.stackstate.com",
   "events":{},
   "metrics":[],
   "service_checks":[],
   "health":[
      {
        "consistency_model": "TRANSACTIONAL_INCREMENTS",
        "increment": {
              "checkpoint": {
                  "offset": 5,
                  "batch_index": 102
              },
              "previous_checkpoint": {
                  "offset": 5,
                  "batch_index": 100
              }
        },
        "stream": {
          "urn": "urn:health:sourceId:streamId"
          //"sub_stream_id": "subStreamId" Optional
        },
        "check_states": [
          {
            "checkStateId": "checkStateId1",
            "message": "Server Running out of disk space",
            "health": "Deviating",
            "topologyElementIdentifier": "server-1",
            "name": "Disk Usage"
          },
          {
            "checkStateId": "checkStateId2",
            "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
            "health": "critical",
            "topologyElementIdentifier": "server-2",
            "name": "Health monitor"
          },
          {
            "checkStateId": "checkStateId3",
            "delete": true
          }
        ]
      }
   ],
   "topologies":[]
----

--
====

每个健康事务增量数据有效载荷都有以下详细信息：

* *increment*- 每个报文都需要有一个增量对象。这样，SUSE Observability 就能跟踪完整的信息链，并能检测到数据重传或数据中出现意外缺口的时间。它包含以下作为增量元数据的字段：
 ** *检查点*- 提供属于`check_states` 的检查点的对象，它有两个字段：
  *** *offset*- 流式传输管道分配给报文的偏移量。例如，卡夫卡偏移量。
  *** *batch_index*- 可选。当使用一条消息累积多个`check_states` 时，批量索引代表消息中的最新索引，这样就可以通过单独的 api 调用发送大批量消息。
 ** *previous_checkpoint*- 可选。代表之前传送的检查点，在子数据流第一次传送时可以为空。它允许 SUSE Observability 跟踪上游数据是否丢失。
* *stream*- 提供有关快照和`check_states` 属于一起的标识的对象。它有以下字段：
 ** *urn*- 以 SUSE Observabilityxref:/configure/topology/identifiers.adoc[URN]编码的数据源和数据流 ID，符合以下约定：`urn:health:<sourceId>:<streamId>` ，其中`<sourceId>` 是外部数据源的名称，`<streamId>` 是健康数据流的唯一标识符。
 ** *sub_stream_id*- 可选。数据流健康数据子集的标识符。当数据流数据由多个代理分发和报告时，就可以实现每个代理的快照生命周期。 `sub_stream_id`
* *check_states*- 校验状态列表。每个检查状态都可以有以下字段：
 ** *checkStateId*- 外部系统中检查状态的标识符
 ** *message*- 可选。在 SUSE Observability UI 中显示的信息。数据将被解释为标记符，允许链接到生成外部检查状态的外部系统检查。
 ** *health*- 以下 SUSE Observability Health 状态值之一：`Clear`,`Deviating`,`Critical` 。
 ** *topologyElementIdentifier*- 用于将检查状态绑定到 SUSE Observability 拓扑元素。
 ** *name*- 外部校验状态的名称。
 ** *delete*- 标志，解释为相关`checkStateId` 的删除请求。例如，即使创建的其他字段都存在，`name, health, ...` ，删除也会优先。

== 向 SUSE Observability 发送健康状况

健康信息可通过 HTTP POST 在一个 JSON 信息中发送。在下面的示例中，包含两个检查状态的快照从一个外部监控系统发送到 SUSE Observability。

[,bash]
----
curl -X POST \
 '<STACKSTATE_RECEIVER_API_ADDRESS>' \
 -H 'Content-Type: application/json' \
 -d '{
  "collection_timestamp": 1548857167,
  "internalHostname": "local.test",
  "health": [
    {
      "consistency_model": "TRANSACTIONAL_INCREMENTS",
      "increment": {
            "checkpoint": {
                "offset": 5,
                "batch_index": 102
            },
            "previous_checkpoint": {
                "offset": 5,
                "batch_index": 100
            }
      },
      "stream": {
        "urn": "urn:health:sourceId:streamId"
      },
      "check_states": [
        {
          "checkStateId": "checkStateId1",
          "message": "Server Running out of disk space",
          "health": "Deviating",
          "topologyElementIdentifier": "server-1",
          "name": "Disk Usage"
        },
        {
          "checkStateId": "checkStateId2",
          "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
          "health": "critical",
          "topologyElementIdentifier": "server-2",
          "name": "Health monitor"
        },
        {
          "checkStateId": "checkStateId3",
          "delete": true
        }
      ]
    }
  ]
}'
----
