// This file was converted from Markdown to AsciiDoc.

include::partial$variables.adoc[]
= CLI kwctl
:revdate: 2026-03-18
:page-revdate: {revdate}
:title: CLI kwctl
:description: Explorez l'outil de ligne de commande \`kwctl` pour gérer les politiques {project-name} et effectuer des tâches telles que le chargement des politiques.
:keywords: cli, reference, kwctl
:doc-persona: kubewarden-operator
:doc-type: référence
:doc-topic: manuel de l'opérateur

== Aide en ligne de commande pour `kwctl`

Ce document contient le contenu de l'aide pour le programme de ligne de commande `kwctl`.

*Aperçu des commandes :*

* <<kwctl,`kwctl`>>
* <<kwctl-annotate,`kwctl annotate`>>
* <<kwctl-bench,`kwctl bench`>>
* <<kwctl-completions,`kwctl completions`>>
* <<kwctl-digest,`kwctl digest`>>
* <<kwctl-docs,`kwctl docs`>>
* <<kwctl-info,`kwctl info`>>
* <<kwctl-inspect,`kwctl inspect`>>
* <<kwctl-load,`kwctl load`>>
* <<kwctl-policies,`kwctl policies`>>
* <<kwctl-pull,`kwctl pull`>>
* <<kwctl-push,`kwctl push`>>
* <<kwctl-rm,`kwctl rm`>>
* <<kwctl-run,`kwctl run`>>
* <<kwctl-save,`kwctl save`>>
* <<kwctl-scaffold,`kwctl scaffold`>>
* <<kwctl-scaffold-admission-request,`kwctl scaffold admission-request`>>
* <<kwctl-scaffold-artifacthub,`kwctl scaffold artifacthub`>>
* <<kwctl-scaffold-manifest,`kwctl scaffold manifest`>>
* <<kwctl-scaffold-vap,`kwctl scaffold vap`>>
* <<kwctl-scaffold-verification-config,`kwctl scaffold verification-config`>>
* <<kwctl-verify,`kwctl verify`>>

[[kwctl]]
=== `kwctl`

Outil de gestion des politiques {project-name} 

*Utilisation :* `kwctl [OPTIONS] <COMMAND>`

==== Sous-commandes

* `annotate` - Ajouter les métadonnées {short-project-name} à un module WebAssembly
* `bench` - Repères une politique {short-project-name} 
* `completions` - Générer des complétions d'obus
* `digest` - Récupérer l'extrait du manifeste OCI d'une politique
* `docs` - Génère la documentation markdown pour les commandes kwctl
* `info` - Affichage des informations sur le système
* `inspect` - Inspecter la politique {short-project-name} 
* `load` - charger des politiques à partir d'un fichier tar.gz
* `policies` - Liste de toutes les politiques téléchargées
* `pull` - Extrait une politique {short-project-name} à partir d'un URI donné
* `push` - Envoi d'une politique {short-project-name} à un registre OCI
* `rm` - Supprime une politique {short-project-name} du magasin
* `run` - Exécute une politique {short-project-name} à partir d'un URI donné
* `save` - enregistrer les politiques dans un fichier tar.gz
* `scaffold` - Echafaudage d'une ressource Kubernetes ou d'un fichier de configuration.
* `verify` - Vérifier une politique {short-project-name} à partir d'un URI donné en utilisant Sigstore

==== Options

* `-v`, `--verbose <VERBOSE>` - Augmenter la verbosité
* `--no-color <NO-COLOR>` - Désactiver la sortie colorée

[[kwctl-annotate]]
=== `kwctl annotate`

Ajouter les métadonnées {short-project-name} à un module WebAssembly

*Utilisation :* `kwctl annotate [OPTIONS] --metadata-path <PATH> --output-path <PATH> <wasm-path>`

==== Arguments

* `<WASM-PATH>` - Chemin d'accès au module WebAssembly à annoter

==== Options

* `-m`, `--metadata-path <PATH>` - Fichier contenant les métadonnées
* `-o``--output-path <PATH>` - Fichier de sortie
* `-u``--usage-path <PATH>` - Fichier contenant les informations d'utilisation de la politique

[[kwctl-bench]]
=== `kwctl bench`

Les points de repère d'une politique {short-project-name}.

La politique peut être spécifiée de la manière suivante :- URI : par exemple, `registry://ghcr.io/kubewarden/policies/psp-policy:latest` ou `\https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm`- Préfixe SHA : par exemple, `c3b80a10f9c3` (exige que la politique soit déjà extraite) - Fichier WASM local : par exemple, `file://home/tux/new-policy/psp-policy.wasm`- Fichier YAML local : par exemple, `file://home/tux/cluster-admission-policy.yaml` (contient des déclarations de ressources personnalisées {short-project-name} comme `ClusterAdmissionPolicy`, `AdmissionPolicy`, etc.)

Comportement par défaut :
Si le schéma est omis, `file://` est supposé, ancré dans le répertoire actuel.

Notes sur les ressources personnalisées {short-project-name}:- Les indicateurs `--request-path`, `--settings-path` et `--settings-json` sont ignorés ; les paramètres sont lus à partir de la définition de la ressource personnalisée.- L'indicateur `--execution-mode` s'applique à toutes les politiques du fichier YAML.- L'indicateur `--raw` ne peut pas être utilisé, car les ressources personnalisées de {short-project-name} ne prennent pas en charge les politiques de `raw`.

Seuls les attributs suivants de la définition de ressource personnalisée (CRD) sont évalués :- Module de politique - Paramètres de politique - Ressources contextuelles auxquelles la politique peut accéder

Les autres champs, tels que `rules`, `matchConditions`, `objectSelector`, et `namespaceSelector`, sont ignorés.

Un fichier YAML peut contenir plusieurs déclarations de ressources personnalisées. Dans ce cas, `kwctl` évalue chaque politique du fichier en utilisant la même requête à chaque évaluation.

*Utilisation :* `kwctl bench [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>`

==== Arguments

* `<URI_OR_SHA_PREFIX_OR_YAML_FILE>` - URI de politique, préfixe SHA ou fichier YAML contenant des ressources de politique {short-project-name}. Schémas pris en charge : registry://, https://, file://. Si schema est omis, file:// est pris en compte, en se basant sur le répertoire actuel.

==== Options

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Accorder l'accès aux ressources Kubernetes définies dans la section `contextAwareResources` de la politique. Attention : lisez attentivement la liste des ressources pour éviter les abus. Désactivé par défaut
* `--cert-email <VALUE>` - Courriel attendu dans le certificat Fulcio
* `--cert-oidc-issuer <VALUE>` - Émetteur prévu de l'OIDC dans les certificats Fulcio
* `--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>` - Désactiver l'utilisation du cache wasmtime
* `--docker-config-json-path <PATH>` - Chemin d'accès au répertoire contenant le fichier 'config.json' de Docker. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `--dump-results-to-disk <DUMP_RESULTS_TO_DISK>` - Place les résultats dans target/tiny-bench/label/\... si la cible peut être trouvée. utilisé pour comparer les exécutions précédentes.
* `-e``--execution-mode <MODE>` - La durée d'exécution à utiliser pour exécuter cette politique +
  Valeurs possibles : `opa`, `gatekeeper`, `kubewarden`, `wasi`
* `--github-owner <VALUE>` - Propriétaire GitHub attendu dans les certificats générés dans les pipelines CD
* `--github-repo <VALUE>` - Dépôt GitHub attendu dans les certificats générés dans les pipelines CD
* `--measurement-time <SECONDS>` - Combien de temps le banc doit-il fonctionner ? Le nombre d'échantillons est prioritaire et le banc prendra plus de temps pour collecter le nombre d'échantillons si le code à tester est plus lent que la limite de temps autorisée.
* `--num-resamples <NUM>` - Combien de rééchantillons faut-il effectuer ?
* `--num-samples <NUM>` - Combien de rééchantillonnages doivent être effectués ? Recommandé au moins 50, plus de 100 ne semble pas donner un résultat significativement différent.
* `--raw <RAW>` - Valider une demande brute +
  Valeur par défaut : `false`
* `--record-host-capabilities-interactions <FILE>` - Enregistre toutes les communications relatives à la politique et aux capacités de l'hôte dans le fichier donné. Utile pour être combiné ultérieurement avec le drapeau '--replay-host-capabilities-interactions'.
* `--replay-host-capabilities-interactions <FILE>` - Lors des échanges de capacités entre la politique et l'hôte, l'hôte renvoie les réponses trouvées dans le fichier fourni. Ceci est utile pour tester les politiques de manière reproductible, étant donné qu'aucune interaction externe avec les registres OCI, DNS, Kubernetes n'est effectuée.
* `-r``--request-path <PATH>` - Fichier contenant l'objet de demande d'admission Kubernetes au format JSON
* `--settings-json <VALUE>` - Chaîne JSON contenant les paramètres de cette politique
* `-s``--settings-path <PATH>` - Fichier contenant les paramètres de cette politique
* `--sigstore-trust-config <PATH>` - Fichier au format JSON conforme au message ClientTrustConfig des spécifications Sigstore protobuf. Ce fichier configure l'ensemble de l'état de l'instance Sigstore, y compris les URI utilisés pour accéder aux services de transparence de l'autorité de certification et des artefacts, ainsi que la racine de confiance cryptographique elle-même.
* `--sources-path <PATH>` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, autorités de certification personnalisées...)
* `-a``--verification-annotation <KEY=VALUE>` - Annotation au format clé=valeur. Peut être répété plusieurs fois
* `--verification-config-path <PATH>` - Fichier YAML contenant les informations de configuration de la vérification (signatures, clés publiques...)
* `-k``--verification-key <PATH>` - Chemin d'accès à la clé utilisée pour vérifier la politique. Peut être répété plusieurs fois
* `--warm-up-time <SECONDS>` - Durée de l'échauffement du banc

[[kwctl-completions]]
=== `kwctl completions`

Générer des complétions d'obus

*Utilisation :* `kwctl completions --shell <VALUE>`

==== Options

* `-s``--shell <VALUE>` - Type de coque +
  Valeurs possibles : `bash`, `elvish`, `fish`, `powershell`, `zsh`

[[kwctl-digest]]
=== `kwctl digest`

Récupérer l'extrait du manifeste OCI d'une politique

*Utilisation :* `kwctl digest [OPTIONS] <uri>`

==== Arguments

* `<URI>` - URI de la politique

==== Options

* `--docker-config-json-path <PATH>` - Chemin d'accès au répertoire contenant le fichier 'config.json' de Docker. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `--sources-path <PATH>` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, autorités de certification personnalisées...)

[[kwctl-docs]]
=== `kwctl docs`

Génère la documentation markdown pour les commandes kwctl

*Utilisation :* `kwctl docs --output <FILE>`

==== Options

* `-o`, `--output <FILE>` - chemin d'accès où le fichier de documentation sera stocké

[[kwctl-info]]
=== `kwctl info`

Affichage des informations sur le système

*Utilisation :* `kwctl info`

[[kwctl-inspect]]
=== `kwctl inspect`

Inspecter la politique {short-project-name} 

*Utilisation :* `kwctl inspect [OPTIONS] <uri_or_sha_prefix>`

==== Arguments

* `<URI_OR_SHA_PREFIX>` - URI de la politique ou préfixe SHA. Schémas pris en charge : registry://, https://, file://. Si schema est omis, file:// est pris en compte, en se basant sur le répertoire actuel.

==== Options

* `--docker-config-json-path <PATH>` - Chemin d'accès au répertoire contenant le fichier 'config.json' de Docker. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `-o`, `--output <FORMAT>` - Format de sortie +
  Valeurs possibles : `yaml`
* `--show-signatures <SHOW-SIGNATURES>` - Afficher les signatures sigstore
* `--sources-path <PATH>` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, autorités de certification personnalisées...)

[[kwctl-load]]
=== `kwctl load`

charger des politiques à partir d'un fichier tar.gz

*Utilisation :* `kwctl load --input <input>`

==== Options

* `--input <INPUT>` - charger les politiques à partir de l'archive

[[kwctl-policies]]
=== `kwctl policies`

Liste de toutes les politiques téléchargées

*Utilisation :* `kwctl policies`

[[kwctl-pull]]
=== `kwctl pull`

Extrait une politique {short-project-name} à partir d'un URI donné

*Utilisation :* `kwctl pull [OPTIONS] <uri>`

==== Arguments

* `<URI>` - URI de la politique. Schémas pris en charge : registry://, https://, file://

==== Options

* `--cert-email <VALUE>` - Courriel attendu dans le certificat Fulcio
* `--cert-oidc-issuer <VALUE>` - Émetteur prévu de l'OIDC dans les certificats Fulcio
* `--docker-config-json-path <DOCKER_CONFIG>` - Chemin d'accès au répertoire contenant le fichier 'config.json' de Docker. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `--github-owner <VALUE>` - Propriétaire GitHub attendu dans les certificats générés dans les pipelines CD
* `--github-repo <VALUE>` - Dépôt GitHub attendu dans les certificats générés dans les pipelines CD
* `-o`, `--output-path <PATH>` - Fichier de sortie. S'il n'est pas fourni, il sera téléchargé sur le site {short-project-name}.
* `--sigstore-trust-config <PATH>` - Fichier au format JSON conforme au message ClientTrustConfig des spécifications Sigstore protobuf. Ce fichier configure l'ensemble de l'état de l'instance Sigstore, y compris les URI utilisés pour accéder aux services de transparence de l'autorité de certification et des artefacts, ainsi que la racine de confiance cryptographique elle-même.
* `--sources-path <PATH>` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, autorités de certification personnalisées...)
* `-a``--verification-annotation <KEY=VALUE>` - Annotation au format clé=valeur. Peut être répété plusieurs fois
* `--verification-config-path <PATH>` - Fichier YAML contenant les informations de configuration de la vérification (signatures, clés publiques...)
* `-k``--verification-key <PATH>` - Chemin d'accès à la clé utilisée pour vérifier la politique. Peut être répété plusieurs fois

[[kwctl-push]]
=== `kwctl push`

Envoi d'une politique {short-project-name} à un registre OCI

*Utilisation :* `kwctl push [OPTIONS] <policy> <uri>`

Les annotations contenues dans les métadonnées de la politique feront partie du manifeste OCI.
Les annotations multilignes sont ignorées car elles ne sont pas compatibles avec la spécification OCI.
L'annotation 'io.kubewarden.policy.source' est propagée en tant que 'org.opencontainers.image.source' pour permettre à des outils comme renovatebot de détecter les mises à jour de la politique.

==== Arguments

* `<POLICY>` - Politique à pousser. Il peut s'agir du chemin d'accès à un fichier local, de l'URI d'une politique ou du préfixe SHA d'une politique du magasin.
* `<URI>` - URI de la politique. Schémas pris en charge : registry://

==== Options

* `--docker-config-json-path <PATH>` - Chemin d'accès au répertoire contenant le fichier 'config.json' de Docker. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `-f``--force <FORCE>` - Pousser aussi une politique qui n'est pas annotée
* `-o`, `--output <PATH>` - Format de sortie +
  Valeur par défaut : `text` +
  Valeurs possibles : `text`, `json`
* `--sources-path <PATH>` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, autorités de certification personnalisées...)

[[kwctl-rm]]
=== `kwctl rm`

Supprime une politique {short-project-name} du magasin

*Utilisation :* `kwctl rm <uri_or_sha_prefix>`

==== Arguments

* `<URI_OR_SHA_PREFIX>` - URI de politique ou préfixe SHA

[[kwctl-run]]
=== `kwctl run`

Exécutez localement une ou plusieurs politiques {short-project-name}.

La politique peut être spécifiée de la manière suivante :- URI : par exemple, `registry://ghcr.io/kubewarden/policies/psp-policy:latest` ou `https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm`- Préfixe SHA : par exemple, `c3b80a10f9c3` (exige que la politique soit déjà extraite) - Fichier WASM local : par exemple, `file://home/tux/new-policy/psp-policy.wasm`- Fichier YAML local : par exemple, `file://home/tux/cluster-admission-policy.yaml` (contient des déclarations de ressources personnalisées {short-project-name} comme `ClusterAdmissionPolicy`, `AdmissionPolicy`, etc.)

Comportement par défaut :
Si le schéma est omis, `file://` est supposé, ancré dans le répertoire actuel.

Notes sur les ressources personnalisées {short-project-name}:- Les indicateurs `--request-path`, `--settings-path` et `--settings-json` sont ignorés ; les paramètres sont lus à partir de la définition de la ressource personnalisée.- L'indicateur `--execution-mode` s'applique à toutes les politiques du fichier YAML.- L'indicateur `--raw` ne peut pas être utilisé, car les ressources personnalisées de {short-project-name} ne prennent pas en charge les politiques de `raw`.

Seuls les attributs suivants de la définition de ressource personnalisée (CRD) sont évalués :- Module de politique - Paramètres de politique - Ressources contextuelles auxquelles la politique peut accéder

Les autres champs, tels que `rules`, `matchConditions`, `objectSelector`, et `namespaceSelector`, sont ignorés.

Un fichier YAML peut contenir plusieurs déclarations de ressources personnalisées. Dans ce cas, `kwctl` évalue chaque politique du fichier en utilisant la même requête à chaque évaluation.

*Utilisation :* `kwctl run [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>`

==== Arguments

* `<URI_OR_SHA_PREFIX_OR_YAML_FILE>` - URI de politique, préfixe SHA ou fichier YAML contenant des ressources de politique {short-project-name}. Schémas pris en charge : registry://, https://, file://. Si schema est omis, file:// est pris en compte, en se basant sur le répertoire actuel.

==== Options

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Accorder l'accès aux ressources Kubernetes définies dans la section `contextAwareResources` de la politique. Attention : lisez attentivement la liste des ressources pour éviter les abus. Désactivé par défaut
* `--cert-email <VALUE>` - Courriel attendu dans le certificat Fulcio
* `--cert-oidc-issuer <VALUE>` - Émetteur prévu de l'OIDC dans les certificats Fulcio
* `--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>` - Désactiver l'utilisation du cache wasmtime
* `--docker-config-json-path <PATH>` - Chemin d'accès au répertoire contenant le fichier 'config.json' de Docker. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `-e``--execution-mode <MODE>` - La durée d'exécution à utiliser pour exécuter cette politique +
  Valeurs possibles : `opa`, `gatekeeper`, `kubewarden`, `wasi`
* `--github-owner <VALUE>` - Propriétaire GitHub attendu dans les certificats générés dans les pipelines CD
* `--github-repo <VALUE>` - Dépôt GitHub attendu dans les certificats générés dans les pipelines CD
* `--raw <RAW>` - Valider une demande brute +
  Valeur par défaut : `false`
* `--record-host-capabilities-interactions <FILE>` - Enregistre toutes les communications relatives à la politique et aux capacités de l'hôte dans le fichier donné. Utile pour être combiné ultérieurement avec le drapeau '--replay-host-capabilities-interactions'.
* `--replay-host-capabilities-interactions <FILE>` - Lors des échanges de capacités entre la politique et l'hôte, l'hôte renvoie les réponses trouvées dans le fichier fourni. Ceci est utile pour tester les politiques de manière reproductible, étant donné qu'aucune interaction externe avec les registres OCI, DNS, Kubernetes n'est effectuée.
* `-r``--request-path <PATH>` - Fichier contenant l'objet de demande d'admission Kubernetes au format JSON
* `--settings-json <VALUE>` - Chaîne JSON contenant les paramètres de cette politique
* `-s``--settings-path <PATH>` - Fichier contenant les paramètres de cette politique
* `--sigstore-trust-config <PATH>` - Fichier au format JSON conforme au message ClientTrustConfig des spécifications Sigstore protobuf. Ce fichier configure l'ensemble de l'état de l'instance Sigstore, y compris les URI utilisés pour accéder aux services de transparence de l'autorité de certification et des artefacts, ainsi que la racine de confiance cryptographique elle-même.
* `--sources-path <PATH>` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, autorités de certification personnalisées...)
* `-a``--verification-annotation <KEY=VALUE>` - Annotation au format clé=valeur. Peut être répété plusieurs fois
* `--verification-config-path <PATH>` - Fichier YAML contenant les informations de configuration de la vérification (signatures, clés publiques...)
* `-k``--verification-key <PATH>` - Chemin d'accès à la clé utilisée pour vérifier la politique. Peut être répété plusieurs fois

[[kwctl-save]]
=== `kwctl save`

enregistrer les politiques dans un fichier tar.gz

*Utilisation :* `kwctl save --output <FILE> <policies>...`

==== Arguments

* `<POLICIES>` - liste des politiques à sauvegarder

==== Options

* `-o``--output <FILE>` - chemin d'accès où le fichier sera stocké

[[kwctl-scaffold]]
=== `kwctl scaffold`

Echafaudage d'une ressource Kubernetes ou d'un fichier de configuration.

*Utilisation :* `kwctl scaffold <COMMAND>`

==== Sous-commandes

* `admission-request` - Échafaudage d'un objet AdmissionRequest
* `artifacthub` - Produire un fichier artifacthub-pkg.yml à partir d'un fichier metadata.yml
* `manifest` - Produire un manifeste de ressources Kubernetes
* `vap` - Convertir un site Kubernetes `ValidatingAdmissionPolicy` en un site {short-project-name} `ClusterAdmissionPolicy`
* `verification-config` - Sortie d'un fichier de configuration par défaut de la vérification Sigstore

[[kwctl-scaffold-admission-request]]
=== `kwctl scaffold admission-request`

Échafaudage d'un objet AdmissionRequest

*Utilisation :* `kwctl scaffold admission-request [OPTIONS] --operation <TYPE>`

==== Options

* `--object <PATH>` - Le fichier contenant le nouvel objet admis
* `--old-object <PATH>` - Le fichier contenant l'objet existant
* `-o`, `--operation <TYPE>` - {short-project-name} Type de ressource personnalisée +
  Valeurs possibles : `CREATE`

[[kwctl-scaffold-artifacthub]]
=== `kwctl scaffold artifacthub`

Produire un fichier artifacthub-pkg.yml à partir d'un fichier metadata.yml

*Utilisation :* `kwctl scaffold artifacthub [OPTIONS]`

==== Options

* `-m``--metadata-path <PATH>` - Fichier contenant les métadonnées de la politique
* `-o`, `--output <FILE>` - Chemin où le fichier artifact-pkg.yml sera stocké
* `-q``--questions-path <PATH>` - Fichier contenant le contenu des questions-ui de la politique
* `-v``--version <VALUE>` - Version semestrielle de la politique

[[kwctl-scaffold-manifest]]
=== `kwctl scaffold manifest`

Produire un manifeste de ressources Kubernetes

*Utilisation :* `kwctl scaffold manifest [OPTIONS] --type <VALUE> <uri_or_sha_prefix>`

==== Arguments

* `<URI_OR_SHA_PREFIX>` - URI de la politique ou préfixe SHA. Schémas pris en charge : registry://, https://, file://. Si schema est omis, file:// est pris en compte, en se basant sur le répertoire actuel.

==== Options

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Utilise les métadonnées de la politique pour définir les ressources Kubernetes auxquelles la politique peut accéder. Attention : lisez attentivement la liste des ressources pour éviter les abus. Désactivé par défaut
* `--cert-email <VALUE>` - Courriel attendu dans le certificat Fulcio
* `--cert-oidc-issuer <VALUE>` - Émetteur prévu de l'OIDC dans les certificats Fulcio
* `--docker-config-json-path <DOCKER_CONFIG>` - Chemin d'accès au répertoire contenant le fichier 'config.json' de Docker. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `--fulcio-cert-path <PATH>` - Chemin d'accès au certificat Fulcio. Peut être répété plusieurs fois
* `--github-owner <VALUE>` - Propriétaire GitHub attendu dans les certificats générés dans les pipelines CD
* `--github-repo <VALUE>` - Dépôt GitHub attendu dans les certificats générés dans les pipelines CD
* `--rekor-public-key-path <PATH>` - Chemin d'accès à la clé publique de Rekor. Peut être répété plusieurs fois
* `--settings-json <VALUE>` - Chaîne JSON contenant les paramètres de cette politique
* `-s``--settings-path <PATH>` - Fichier contenant les paramètres de cette politique
* `--sigstore-trust-config <PATH>` - Fichier au format JSON conforme au message ClientTrustConfig des spécifications Sigstore protobuf. Ce fichier configure l'ensemble de l'état de l'instance Sigstore, y compris les URI utilisés pour accéder aux services de transparence de l'autorité de certification et des artefacts, ainsi que la racine de confiance cryptographique elle-même.
* `--sources-path <PATH>` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, autorités de certification personnalisées...)
* `--title <VALUE>` - Titre de la politique
* `-t`, `--type <VALUE>` - {short-project-name} Type de ressource personnalisée +
  Valeurs possibles : `ClusterAdmissionPolicy`, `AdmissionPolicy`
* `-a``--verification-annotation <KEY=VALUE>` - Annotation au format clé=valeur. Peut être répété plusieurs fois
* `--verification-config-path <PATH>` - Fichier YAML contenant les informations de configuration de la vérification (signatures, clés publiques...)
* `-k``--verification-key <PATH>` - Chemin d'accès à la clé utilisée pour vérifier la politique. Peut être répété plusieurs fois

[[kwctl-scaffold-vap]]
=== `kwctl scaffold vap`

Convertir un site Kubernetes `ValidatingAdmissionPolicy` en un site {short-project-name} `ClusterAdmissionPolicy`

*Utilisation :* `kwctl scaffold vap [OPTIONS] --binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml> --policy <VALIDATING-ADMISSION-POLICY.yaml>`

==== Options

* `-b`, `--binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml>` - Le fichier contenant la définition de ValidatingAdmissionPolicyBinding
* `--cel-policy <URI>` - Le module de politique CEL à utiliser +
  Valeur par défaut : `ghcr.io/kubewarden/policies/cel-policy:latest`
* `-p`, `--policy <VALIDATING-ADMISSION-POLICY.yaml>` - Le fichier contenant la définition de ValidatingAdmissionPolicy

[[kwctl-scaffold-verification-config]]
=== `kwctl scaffold verification-config`

Sortie d'un fichier de configuration par défaut de la vérification Sigstore

*Utilisation :* `kwctl scaffold verification-config`

[[kwctl-verify]]
=== `kwctl verify`

Vérifier une politique {short-project-name} à partir d'un URI donné en utilisant Sigstore

*Utilisation :* `kwctl verify [OPTIONS] <uri>`

==== Arguments

* `<URI>` - URI de la politique. Schémas pris en charge : registry://

==== Options

* `--cert-email <VALUE>` - Courriel attendu dans le certificat Fulcio
* `--cert-oidc-issuer <VALUE>` - Émetteur prévu de l'OIDC dans les certificats Fulcio
* `--docker-config-json-path <PATH>` - Chemin d'accès au répertoire contenant le fichier 'config.json' de Docker. Peut être utilisé pour indiquer les détails de l'authentification du registre
* `--github-owner <VALUE>` - Propriétaire GitHub attendu dans les certificats générés dans les pipelines CD
* `--github-repo <VALUE>` - Dépôt GitHub attendu dans les certificats générés dans les pipelines CD
* `--sigstore-trust-config <PATH>` - Fichier au format JSON conforme au message ClientTrustConfig des spécifications Sigstore protobuf. Ce fichier configure l'ensemble de l'état de l'instance Sigstore, y compris les URI utilisés pour accéder aux services de transparence de l'autorité de certification et des artefacts, ainsi que la racine de confiance cryptographique elle-même.
* `--sources-path <PATH>` - Fichier YAML contenant des informations sur la source (https, registre des hôtes non sécurisés, autorités de certification personnalisées...)
* `-a``--verification-annotation <KEY=VALUE>` - Annotation au format clé=valeur. Peut être répété plusieurs fois
* `--verification-config-path <PATH>` - Fichier YAML contenant les informations de configuration de la vérification (signatures, clés publiques...)
* `-k``--verification-key <PATH>` - Chemin d'accès à la clé utilisée pour vérifier la politique. Peut être répété plusieurs fois

'''

Ce document a été généré automatiquement par https://crates.io/crates/clap-markdown[`clap-markdown`].
