include::partial$variables.adoc[]
= Qu'est-ce que {project-name}?
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Découvrez le rôle de {project-name} dans la gestion des politiques Kubernetes, qui comprend l'application de la conformité et l'optimisation des ressources.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["introduction"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "cncf", "cncf sandbox", "kubernetes", "admission policy manager"].
:sidebar_label: Introduction
:sidebar_position: 1
:slug: /
:current-version: {page-origin-branch}

{project-name} est un moteur de politique Kubernetes.
Il vise à être le moteur de politique universelle pour Kubernetes.

{intro-paragraph}

== En quoi le site {project-name} est-il utile ?

{short-project-name} offre une flexibilité pour l'admission et l'application des politiques dans un environnement Kubernetes.

=== Avantages et valeur

- Utilisez n'importe quel langage de programmation qui génère des binaires https://webassembly.org[WebAssembly] pour écrire vos politiques.
- WebAssembly permet la compatibilité des politiques entre les processeurs et les systèmes d'exploitation.
- Réutilisation des politiques d'autres moteurs de politiques sans avoir à les réécrire.
- Distribuer les politiques à l'aide de mécanismes standard et sécurisés, tels que les registres conformes à l'OCI https://opencontainers.org[(] 
- L'application de règles à l'admission garantit que seules les charges de travail conformes sont exécutées.
- Le scanner d'audit {short-project-name} vérifie activement et continuellement l'application de la politique au fil du temps.
- Vérifier les politiques à l'aide des outils et pratiques (Supply Chain Levels for Software Artifacts) sur https://slsa.dev[SLSA].
- {project-name} offre une approche globale de la gestion des politiques d'admission.
- L'adhésion à la CNCF et la croissance de la communauté et de l'écosystème des logiciels libres aident {short-project-name} à assurer la transparence, la collaboration et l'amélioration.

=== Cas d'utilisation

- Renforcement de la sécurité. Par exemple, appliquer des politiques restreignant les privilèges des conteneurs, appliquer des politiques de réseau ou bloquer les registres d'images non sécurisés.
- Audit de conformité. Veiller à ce que les charges de travail soient conformes aux normes et aux meilleures pratiques de l'organisation ou de la réglementation.
- Optimisation des ressources. Appliquer les limites de ressources et les quotas.

La page consacrée aux cas d'utilisation contient une documentation plus détaillée sur les xref:use-cases.adoc[cas d'utilisation].

== Nouveau sur {short-project-name}?

Si vous ne connaissez pas le projet {short-project-name}, commencez par consulter le xref:quick-start.adoc[guide de démarrage rapide] et la page sur l xref:explanations/architecture.adoc['architecture].
Ensuite, tout dépend de ce qui vous intéresse. Pour les responsables de l'élaboration des politiques, les tutoriels comportent des sections spécifiques aux langues. Pour les intégrateurs et les administrateurs, il y a une section "comment faire". La section "Explications" contient des informations de base utiles. Il y a également un xref:glossary.adoc[glossaire].

== Qu'est-ce que WebAssembly ?

Comme indiqué sur le https://webassembly.org/[site officiel de]:

____
WebAssembly (abrégé Wasm) est un format d'instruction binaire pour une machine virtuelle basée sur la pile. Wasm est conçu comme une cible de compilation portable pour les langages de programmation, permettant le déploiement sur le web d'applications client et serveur.
____

Wasm a été conçu à l'origine comme une "extension" du navigateur. Cependant, la communauté WebAssembly s'efforce de permettre l'exécution du code Wasm en dehors des navigateurs.

== Pourquoi utiliser WebAssembly ?

Les utilisateurs peuvent écrire des politiques Kubernetes à l'aide de leur langage de programmation préféré, à condition que sa chaîne d'outils puisse générer des binaires Wasm.

Les modules Wasm sont portables, une fois construits, ils peuvent fonctionner sur n'importe quel type d'architecture de processeur et de système d'exploitation. Par exemple, une politique développée et construite sur Apple Silicon peut fonctionner sur AMD64/Intel64 Linux sans conversion.

Les auteurs de politiques peuvent réutiliser leurs compétences, leurs outils et leurs meilleures pratiques. Les politiques sont des programmes "traditionnels" qui peuvent avoir des blocs réutilisables (bibliothèques ordinaires). Vous pouvez les analyser et les tester et vous pouvez les intégrer dans les flux de travail actuels de CI et de CD.

== Distribution des politiques

Vous pouvez servir les politiques {short-project-name} à l'aide d'un serveur web standard ou, mieux encore, vous pouvez les publier dans un registre conforme à l'OCI en tant qu' OCIhttps://github.com/opencontainers/artifacts[artefacts].

ifeval::["{build-type}" == "community"]

== Neutralité vis-à-vis des fournisseurs

{short-project-name} est un projet \link:https://contribute.cncf.io/maintainers/community/vendor-neutrality/ [vendor neutral] tel que défini par la CNCF.

endif::[]
