include::partial$variables.adoc[]
= {project-name} cas d'utilisation
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Cas d'utilisation
:sidebar_position: 74
:description: Découvrez les différents cas d'utilisation de {project-name} dans différents environnements Kubernetes et personas, y compris plusieurs scénarios.
:keywords: {project-name}Documentation, cas d'utilisation, études de cas
:doc-persona: kubewarden-all
:doc-type: explanation
:doc-topic: explanation

Voici quelques exemples de cas d'utilisation des xref:/personas.adoc[personas de] {project-name}.

== Cas A : En tant qu'opérateur Kubernetes, je veux m'assurer que mon cluster est sûr et conforme.

Je déploie {project-name} et sa configuration par défaut avec son diagramme`+kubewarden-defaults+` Helm, dans l'espace de nommage `+kubewarden+`. Cela déploie un PolicyServer par défaut et des ClusterAdmissionPolicies recommandés dans l'espace de noms`+kubewarden+`, uniquement sous le contrôle de l'opérateur Kubernetes.

En tant qu'opérateur, je peux ajouter d'autres PolicyServers sous un espace de nommage géré (tel que`+kubewarden+`) pour répartir la charge et la tolérance aux pannes.

Les opérateurs peuvent déployer davantage de ClusterAdmissionPolicies et de ClusterAdmissionPolicyGroups. Elles vérifient toutes les ressources Kubernetes, pour tout type d'opération (GET, CREATE, UPDATE, PATCH, DELETE, PROXY). Cela permet de garantir la sécurité et la conformité des opérations dans le cluster.

Il s'agit notamment de

* sécurité
* la conformité (aux normes industrielles ou aux réglementations de l'entreprise)
* l'optimisation des ressources (par le biais de politiques de mutation)
* la gouvernance des environnements Kubernetes (via des labels et des conventions de nommage).
* meilleures pratiques
* vérification des images

Les attentes en matière de sécurité évoluent avec le temps. Les déploiements précédemment corrects dans le cluster peuvent ne plus l'être. Pourtant, {short-project-name} a déjà accepté ces opérations dans le cluster. Dans ces situations, l'opérateur peut déployer la fonction Audit Scanner, un CronJob qui s'exécute périodiquement et évalue les ressources existantes dans le cluster. Cela permet de vérifier que le cluster est sûr et conforme, même au fil du temps.

L'opérateur peut configurer les politiques en mode `+monitor+` plutôt qu'en mode `+protect+`, afin de connaître l'état de la grappe sans bloquer les opérations.

Les opérateurs peuvent recevoir des informations des politiques et de la pile {short-project-name} en consommant des journaux et des informations OpenTelemetry pour les mesures et le traçage.

== Cas B : En tant qu'opérateur Kubernetes, je veux fournir un cadre à mes utilisateurs Kubernetes pour qu'ils puissent faire du self-service dans leurs Namespaces.

En tant qu'opérateur, je déploie {short-project-name} comme dans le cas A pour un ensemble de politiques de mon choix. Je dispose ainsi d'une base de référence sûre dans le cluster, à laquelle les autres utilisateurs ne peuvent se soustraire.

Outre le cas A, j'ai différents personas par Namespaces : peut-être des équipes, des administrateurs d'équipe, des déploiements de tests, et d'autres. Je permets à chaque administrateur d'espace de nommage d'assurer le libre-service en lui permettant de déployer des serveurs de politiques dans son espace de nommage, ainsi que des politiques d'admission et des groupes de politiques d'admission dans l'espace de nommage.
Cette architecture signifie qu'ils contrôlent leur PolicyServer et leurs politiques. Les politiques ne s'appliquent qu'à leur espace de nommage et limitent l'utilisation des ressources à leur espace de nommage.

Il permet également à l'opérateur de séparer les locataires bruyants, en réservant les PolicyServers performants aux locataires et aux tâches qui ont besoin d'un débit élevé et d'une faible latence, par exemple.

== Cas C : En tant qu'auteur de politiques, je veux utiliser les outils et les langages que je connais pour rédiger de nouvelles politiques.

{short-project-name} y parvient en prenant en charge tous les langages qui se compilent en WebAssembly en tant que langages cibles possibles pour les politiques. Cela signifie que les auteurs de politiques peuvent réutiliser leurs flux de travail (`+git+`, CI, éditeurs, évaluations par les pairs, etc.) et leurs outils : langages, bibliothèques de langages, harnais de test et cadres, etc.

Il permet de réutiliser des langages spécifiques à un domaine (comme Rego, CEL, YAML+macros de Kyverno) ou des langages généraux (comme Go, Rust, C#, Javascript, tous ceux qui compilent vers Wasm). {short-project-name} fournitxref:/tutorials/writing-policies/index.adoc[des SDK] pour quelques langages en tant que support de première classe.

{short-project-name} Les politiques peuvent être des politiques simples ou complexesxref:/explanations/context-aware-policies.adoc[tenant compte du contexte].
Les politiques contextuelles sont également utilisées pour interfacer avec des charges de travail distinctes (par exemple, pour obtenir des informations d'un service de scanner d'images en cours d'exécution).

== Cas D : En tant qu'intégrateur de systèmes, je souhaite réutiliser {short-project-name} dans le cadre de ma solution de sécurité et de conformité.

En tant qu'intégrateur de systèmes, je souhaite réutiliser {short-project-name}, et éventuellement réutiliser d'autres solutions en les incluant dans {short-project-name}.

En tant qu'intégrateur de systèmes, je peux réutiliser des parties de {short-project-name}. Par exemple, le site`+policy-server+`, pour policer les ressources, internes ou externes au cluster Kubernetes via la fonctionnalité xref:/howtos/raw-policies.adoc["raw policies".] 

Les intégrateurs de systèmes peuvent choisir de déployer le site `+kubewarden-controller+` ou de gérer eux-mêmes les CRD. Ils peuvent choisir de déployer ou d'adapter le scanner d'audit en fonction des besoins.

Les intégrateurs de systèmes peuvent créer de nouveaux composants. Par exemple, un scanner d'images, et s'interfacer avec lui via une politique contextuelle, sans avoir une implémentation monolithique dans un contrôleur Kubernetes.

== Non-objectifs

{short-project-name} n'a pas l'intention de le faire :

- Remplacer les fonctionnalités de sécurité intégrées à Kubernetes, mais les compléter :
  - {short-project-name} assure la migration à partir des PSP.
  - Vous pouvez réutiliser les politiques de validation d'admission et les politiques CEL avec {short-project-name}'s `+cel-policy+`.
  - {short-project-name} peuvent être modifiées, ce qui n'est pas le cas de la politique d'admission à la sécurité du pod.
  - {short-project-name} bénéficient des fonctionnalités de la pile {short-project-name} (scanner d'audit, télémétrie, gestion des CRD).
- Fournir une sécurité d'exécution comme la détection d'intrusion ou l'isolation des conteneurs d'exécution.
- Assurer la protection du système hôte des grappes.
- Fournir une flexibilité infinie dans l'exécution des politiques. Pour éviter les attaques DoS, les délais de traitement des politiques sont limités.