= Gerenciamento de inventário
:revdate: 2025-08-15
:page-revdate: {revdate}

O operador do {elemental-product-name} pode manter um inventário de máquinas e o mapeamento da máquina para sua configuração e cluster atribuído.

== MachineInventory

O site `+MachineInventory+` contém todas as informações relevantes para uma máquina registrada. +
Após o registro bem-sucedido, o `+MachineInventory+` herdará todos os `+machineInventoryLabels+` definidos no `+MachineRegistration+` relacionado. +
Além disso, a máquina `+annotations+` também será atualizada a cada registro bem-sucedido.

Por padrão, as máquinas {elemental-product-name} tentarão uma atualização de registro a cada 24 horas para atualizar rótulos e anotações.

=== Referência

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  # Machine annotations can be useful to identify hosts
  annotations:
    elemental.cattle.io/auth: tpm
    elemental.cattle.io/registration-ip: 192.168.122.152
  labels:
    # A label inherited from the MachineRegistration definition
    element: fire
    # Generic SMBIOS labels that are typically populated with
    # the MachineRegister approach
    machineUUID: f266c64b-3972-40e7-9937-3dc4a311436c
    manufacturer: QEMU
    productName: Standard-PC-Q35-ICH9-2009
    serialNumber: Not-Specified
    # Custom labels can be applied to each MachineInventory
    myCustomLabel: foo
  name: m-479ab68e-00ff-4081-a731-5b1a76610289
  # The namespace must match the namespace of the cluster
  # assigned to the clusters.provisioning.cattle.io resource
  namespace: fleet-default
  # A reference to the MachineInventorySelector that links the
  # machine to a Cluster definition
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: MachineInventorySelector
    name: fire-machine-selector-qcn7d
    uid: 0a1f751e-4ca9-4a0d-919a-97ba1f434d12
spec:
  # The hash of the TPM EK public key. This is used if you are
  # using TPM2 to identify nodes. Nodes can report their TPM
  # hash by using the MachineRegistration.
  tpmHash: d68795c6192af9922692f050b...
----

== Registro de máquina

`+MachineRegistration+` contém informações sobre como instalar, redefinir e configurar todas as máquinas conectadas ao site {elemental-product-name}.

É possível atualizar os sites `+spec.machineInventoryLabels+` e `+spec.machineInventoryAnnotations+` e isso será aplicado a todas as máquinas registradas.
Por padrão, as máquinas {elemental-product-name} tentarão uma atualização de registro a cada 24 horas para atualizar rótulos e anotações.

Embora seja possível modificar a definição do site `+spec.config+`, as atualizações do site `+spec.config+` serão ignoradas pelos computadores que já concluíram a instalação.
Os computadores que não conseguirem concluir a instalação tentarão novamente a cada 30 minutos, recarregando a definição do site `+MachineRegistration+` remoto. Isso pode ser útil para corrigir erros do `+spec.config+` que impedem a instalação bem-sucedida (por exemplo, `+spec.config.elemental.install.device+`), sem precisar criar um novo `+MachineRegistration+` e um novo ISO.

=== Referência

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  # The namespace must match the namespace of the cluster
  # assigned to the clusters.provisioning.cattle.io resource
  namespace: fleet-default
spec:
  # The cloud config that will be used to provision the node
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
      reset:
        enabled: true
        debug: true
        reset-persistent: true
        reset-oem: true
        reboot: true
  # Labels to be added to the created MachineInventory object
  machineInventoryLabels:
    element: fire
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
  # Annotations to be added to the created MachineInventory object
  machineInventoryAnnotations: {}
----
