= Solução de problemas de extensão
:revdate: 2025-11-03
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

Esta seção fornece etapas de solução de problemas para qualquer problema de interoperabilidade entre {stackstate-product-name} e a extensão Rancher UI.

== Coletar um HAR (Http ARchive)

O Http ARchive coleta detalhes sobre as solicitações enviadas pelo navegador ao Rancher e ao site {stackstate-product-name}.  Ele também registra as respostas recebidas.
Esse arquivo é específico para a página/guia do navegador com o erro.  Ele não precisa acessar as instâncias de apoio do Rancher ou do {stackstate-product-name} (embora seus registros possam ser úteis em um estágio posterior).

* Abra a guia *Rede* no painel "Ferramentas do desenvolvedor".  Você pode acessá-lo usando `+F12+`.  A guia de rede mostra um registro de todas as solicitações feitas.
* Limpe o registro e atualize a página que está exibindo o comportamento problemático.
* Agora deve haver um grande número de solicitações visíveis para o Rancher e o SUSE Observability.
* Exportar/baixar/salvar o HAR - diferentes navegadores usam nomes diferentes aqui.

== O cluster não é observado

Para que o status de integridade do cluster seja visível no Rancher, é necessário haver alinhamento entre essas configurações:

* O nome (de exibição) do cluster na interface do usuário do Rancher.
* O conjunto `+stackstate.cluster.name+` no agente implantado no cluster
* O nome do cluster na configuração do stackpack do Kubernetes no SUSE Observability

Uma incompatibilidade tenderá a aparecer como "nenhum dado recebido" na visão geral do cluster no Rancher.

== Falha na conexão

Às vezes, a configuração do SUSE Observability pode não gerar uma conexão válida na interface do usuário do Rancher devido aos seguintes motivos:

* O host do Rancher não está configurado como uma origem permitida para o SUSE Observability.  Você pode corrigir isso adicionando-o à lista `+stackstate.allowedOrigins+` nos valores do helm ou passando `+--set stackstate.allowedOrigins={"https://<rancher-url>"}+` para o comando de implantação.
* O SUSE Observability não pode ser acessado pelo navegador. Por exemplo, o certificado raiz não foi instalado.