= Pacote de suporte do SUSE Observability (registros)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Visão geral

Esta página fornece ferramentas e orientações para a coleta de logs de um cluster do SUSE Observability. Esses logs são essenciais para diagnosticar problemas, identificar as causas principais e solucionar problemas em clusters que podem não estar funcionando conforme o esperado.
Se você estiver enfrentando um comportamento inesperado, desempenho degradado ou uma falha no cluster {stackstate-product-name}, esta página o ajudará a reunir os dados necessários para entender o que deu errado e tomar medidas corretivas. Ao lado do script detalhado aqui, há um pacote de xref:/setup/install-stackstate/support-package-performance.adoc[suporte] de script ativo xref:/setup/install-stackstate/support-package-performance.adoc[(Performance)] que executará ativamente medições de desempenho no cluster e no site {stackstate-product-name}.

== Notas

O script deve ser executado em um host que tenha o kubectl configurado com acesso ao cluster do SUSE Observability ou em qualquer outro host com as permissões necessárias e conectividade com o cluster.
Isso pode ser feito diretamente no host usando o usuário root ou via sudo.  Se o kubeconfig não estiver definido, use o comando `+export KUBECONFIG=$PATH-TO-YOUR/kubeconfig+`.

== Uso

O script precisa ser baixado e executado diretamente no host, usando o usuário `+root+` ou `+sudo+`.

=== Faça o download e execute o script

Faça o download do script xref::attachment$suse-observability_logs_collector.sh[suse-observability_logs_collector.sh].

* Salve o script como: `+suse-observability_logs_collector.sh+`
* Execute o script usando os seguintes comandos:
+
[,bash]
----
bash suse-observability_logs_collector.sh
----
+
Isso gerará um arquivo no diretório atual chamado `+suse-observability_logs_<date>.tar.gz+`. Faça o upload desse arquivo para o caso.

Argumentos adicionais podem ser especificados:
[,bash]
----
> bash suse-observability_logs_collector.sh -h
SUSE Observability support package collector.
Fetches details of a SUSE Observability instance for troubleshooting.

Usage: ./suse-observability_logs_collector.sh [options] [<namespace>]

options:
  -h  Print this help
  -e  Fetch logs for suse-observability pods from Elasticsearch
  -r  Time range for logs to fetch from Elasticsearch,
      when not specified "7d" is used

<namespace>:
  The namespace that is running SUSE Observability, or
  "suse-observability" when not specified
----

Por exemplo, para coletar 3 dias de registros do elasticsearch incorporado quando o {stackstate-product-name} for implantado no namespace `+my-observability+`:
[,bash]
----
bash suse-observability_logs_collector.sh -e -r 3d my-observability
----
