= {elemental-product-name} コマンドライン方式
:revdate: 2025-11-06
:page-revdate: {revdate}

このガイドに従って、rke2/k3s経由で自動デプロイされたクラスタを持ち、{elemental-product-name} ISOの助けだけでRancherで管理する。

include::partial$quickstart-prereqs.adoc[]

include::partial$operator-install.adoc[]

== kubernetesリソースを準備する

ノードのデプロイは、`MachineRegistration` 、同じ構成（ディスクドライブ、ネットワークなど）を共有するマシンのセットを識別することから始まる。

`MachineRegistration` は、{elemental-product-name} OS のターゲットホストへのデプロイを実行するために必要です。起動時、各ホストは`MachineInventory` リソースで新しいホストを追跡する{elemental-product-name} オペレータに登録する。

続いて、`MachineInventorySelectorTemplate` を使って、どのマシンがそのクラスタに属するかを知るクラスタ・リソースがある。

このセレクタは、`MachineInventory` で設定されたラベルに基づく単純なマッチャです。したがって、もしあなたのセレクタが`cluster-id` というラベルに`cluster-id-val`という値でマッチしていて、あなたの`MachineInventory` が同じ`cluster-id`:``cluster-id-val`` というラベルを持っていれば、それはマッチし、クラスタの一部としてブートストラップされます。

このクイックスタートでは、_element___:fireという__ラベルを持つ``MachineInventorysに``マッチする_volcanoという_名前のクラスタをプロビジョニングするためにリソースをデプロイする。

[tabs]
==========
手動でリソース・ヤムルを作成する::
+
========
以下のファイルを作成する必要がある：

.selector.yaml
[,yaml]
----
include::example$quickstart/selector.yaml[]
----

ご覧のように、これは`element` というキーと`fire` という値を持つラベルを持つ`MachineInventory`を探す、非常にシンプルなセレクタです。

.cluster.yaml
[,yaml]
----
include::example$quickstart/cluster.yaml[]
----

ご覧のように、`machineConfigRef` は、`MachineInventorySelectorTemplate` という種類で、`fire-machine-selector` という名前がついている。などのクラスタオプションの詳細情報を得ることができます。https://documentation.suse.com/cloudnative/rancher-manager/latest/en/cluster-deployment/configuration/rke2.html#_machineglobalconfig[`machineGlobalConfig`]またはhttps://documentation.suse.com/cloudnative/rancher-manager/latest/en/cluster-deployment/configuration/rke2.html#_machineselectorconfig[`machineSelectorConfig`]などのクラスタオプションに関する情報はhttps://documentation.suse.com/cloudnative/rancher-manager/latest/en/about-rancher/what-is-rancher.html[Manager ドキュメントを] Rancher参照してください。

[tabs]
======
参加登録::
+
====
.register.yaml
[,yaml]
----
include::example$quickstart/registration.yaml[]
----
====

ラズベリーパイ登録::
+
====
.rpi-registration.yaml
[,yaml]
----
include::example$quickstart/rpi-registration.yaml[]
----

Raspberry Piに導入するには、エミュレートされたTPMを有効にする必要があります（[Raspberry Pi用のハードウェアTPM](https://thepihut.com/products/letstrust-tpm-for-raspberry-pi)を持っている場合を除く）。また、EFIストアへの書き込みを無効にする必要がある（Raspberry PiにはEFIストアがないため）。`disable-boot-entry: true` 。
====
======

`MachineRegistration` 、登録とインストールの設定を定義する。一旦作成されると、{elemental-product-name} オペレータは、`elemental-register` バイナリで使用する一意の URL を公開し、管理クラスタにアクセスし、インストール中にマシンを登録する。登録が成功すると、オペレータはマシンを追跡する`MachineInventory` を作成し、これを使用してマシンをクラスタのノードとしてプロビジョニングできる。セレクタにマッチするラベルをここで定義するが、後で作成した`MachineInventory`sに追加することもできる。

[WARNING]
====
上記のregistration.yamlを修正して、ノードの設定に基づいた有効なデバイス（例：/dev/sda、/dev/vda、/dev/nvme0など）を指すように、適切なインストール・デバイスを設定してください。

Raspberry PiのSDカードは通常`/dev/mmcblk0` 。
====

[tabs]
======
シードイメージ (x86_64)::
+
====
.seedimage.yaml
[,yaml]
----
include::example$quickstart/seedimage.yaml[]
----

`SeedImage` は、ターゲットマシン上で{elemental-product-name} のプロビジョニングを開始するための*シードイメージ*（ブータブル ISO のようなもの）を生成するために必要です。

すべての設定ファイルを定義したので、Kubernetesに適切なリソースを作成するために適用してみよう：

[,console]
----
kubectl apply -f selector.yaml
kubectl apply -f cluster.yaml
kubectl apply -f registration.yaml
kubectl apply -f seedimage.yaml
----
====

ラズベリーパイ用シードイメージ::
+
====
{elemental-product-name} ブータブル・イメージ（*シード・イメージ*）の作成を自動化する`SeedImage` リソースは、まだ Raspberry Pi ISO をサポートしていません（raw ディスク・イメージの構築ガイドは [こちら](raspi-disk.md) をクリックしてください）。

次のセクション](quickstart-cli.md#preparing-the-installation-seed-image)で手動で*シードイメージを*生成します。

すべての設定ファイルを定義したので、Kubernetesに適切なリソースを作成するために適用してみよう：

[,console]
----
kubectl apply -f selector.yaml
kubectl apply -f cluster.yaml
kubectl apply -f registration.yaml
----
====
======
========

{elemental-product-name} docs repoからクイックスタートファイルを直接使用する。::
+
========
{elemental-product-name} docs リポジトリ](https://github.com/rancher/elemental-docs) からクイックスタート例のリソースファイルを直接適用できます。

[WARNING]
====
クイックスタートサンプルのリソースファイルは、ターゲットホストのデフォルトストレージが`/dev/sda` にマッピングされていると仮定しています。ホスト・ストレージ・デバイス・ファイルが異なる場合は、適用する前にregistration.yamlファイルを変更し、それに応じて`config.elemental.install.device` 。
====

[,console]
----
kubectl apply -f https://raw.githubusercontent.com/rancher/elemental-docs/main/examples/quickstart/selector.yaml
kubectl apply -f https://raw.githubusercontent.com/rancher/elemental-docs/main/examples/quickstart/cluster.yaml
kubectl apply -f https://raw.githubusercontent.com/rancher/elemental-docs/main/examples/quickstart/registration.yaml
kubectl apply -f https://raw.githubusercontent.com/rancher/elemental-docs/main/examples/quickstart/seedimage.yaml
----

[NOTE]
====
現在、`seedimage.yaml` は aarch64 をサポートしていない。
====
========
==========

== インストール（シード）イメージの準備

これは最後のステップだ。{elemental-product-name} 、初期登録設定を含むシードイメージが必要で、これにより自動登録、インストール、クラスタの一部としての完全なデプロイが可能になる。

[NOTE]
.備考
====
初期登録設定ファイルは、`Machine Registration` を作成するときに生成されます。

でダウンロードできる：

[,shell]
----
wget --no-check-certificate `kubectl get machineregistration -n fleet-default fire-nodes -o jsonpath="{.status.registrationURL}"` -O initial-registration.yaml
----
====

登録設定ファイルの内容は、ノードの登録に必要な登録URL、適切なサーバー証明書、登録プロセスに関するいくつかのオプションに過ぎない。

一度生成されたシードイメージは、任意の台数のマシンのプロビジョニングに使用できる。

[tabs]
========
クイックスタートISOのダウンロード::
+
======
上記の`SeedImage` リソースで作成したシードイメージは、以下のスクリプトで ISO としてダウンロードできます：

[,shell]
----
kubectl wait --for=condition=ready pod -n fleet-default fire-img 
wget --no-check-certificate `kubectl get seedimage -n fleet-default fire-img -o jsonpath="{.status.downloadURL}"` -O elemental.x86_64.iso 
----

最初のコマンドはISOがビルドされ準備が整うのを待ち、2番目のコマンドはカレントディレクトリに`elemental-x86_64.iso`.
======

シードイメージ（aarch64）を手動で準備する。::
+
======
{elemental-product-name}Raspberry Piのサポートは、現時点では主にデモンストレーション目的だ。そのため、インストール・プロセスはx86-64と同様にモデル化されている。シードイメージ（この場合はUSBメモリ）からブートし、記憶媒体（Raspberry Piの場合はSDカード）にインストールする。

*シード画像の取得*

[,shell]
----
wget -q https://download.opensuse.org/repositories/isv:/Rancher:/SUSE® Rancher Prime OS Manager:/Stable/containers/rpi.raw
----

_ダウンロードの確認_

ダウンロードした成果物の完全性を確認するために、チェックサム検証を行う必要があります：

[,shell]
----
wget -q https://download.opensuse.org/repositories/isv:/Rancher:/SUSE® Rancher Prime OS Manager:/Stable/containers/rpi.raw.sha256 sha256sum -c rpi.raw.sha256
----

出力として`rpi.raw: OK` 。

*登録情報の注入*

`initial-registration.yaml` の追加はまだスクリプト化されていない。これはまだ手作業だ：

書き込まれたUSBメモリには2つのパーティションがあります。`RPI_BOOT` にはブートローダーファイルが、`COS_LIVE` には{elemental-product-name} ファイルが格納されています。`COS_LIVE` パーティションをマウントし、このパーティションに`initial-registration.yaml` を`livecd-cloud-config.yaml` として書き込む。

ファイルマネージャーでUSBメモリーをマウントしていれば、このコマンドで登録情報をコピーできるはずだ：

[,shell]
----
sudo cp initial-registration.yaml /run/media/$USER/COS_LIVE/livecd-cloud-config.yaml
----

CLIツールを使いたい場合は

[,shell]
----
IMAGE=rpi.raw 
DEST=$(mktemp -d) 

SECTORSIZE=$(sfdisk -J $\{IMAGE} | jq '.partitiontable.sectorsize') 
DATAPARTITIONSTART=$(sfdisk -J $\{IMAGE} | jq '.partitiontable.partitions[1].start') 
sudo mount -o rw,loop,offset=$(($\{SECTORSIZE}*$\{DATAPARTITIONSTART})) $\{IMAGE} $\{DEST} 
sudo cp initial-registration.yaml $\{DEST}/livecd-cloud-config.yaml 
sudo umount $\{DEST} 
rmdir $\{DEST}
----

*シードイメージをUSBメモリに書き込む*

`.raw` イメージは、ブートするためにUSBスティックに書き込む必要がある。このコマンドに慣れていれば、Linux のコマンドラインから`dd` を使って行うことができます。[openSUSE](https://www.opensuse.org)には、[Linux](https://en.opensuse.org/SDB:Live_USB_stick)、[Windows](https://en.opensuse.org/SDB:Create_a_Live_USB_stick_using_Windows)、[OS X](https://en.opensuse.org/SDB:Create_a_Live_USB_stick_using_macOS)用に、イメージを記憶媒体に書き込む方法が書かれています。

*Raspberry Piの起動*

USBメモリをアンマウントし、Raspberry Piに差し込む。

大容量（32GB以上）で**高速な**（！）マイクロSDカードをそれぞれのスロットに差し込みます。

システムをイーサネットに接続する。

パワーサイクルはPiを再起動します。それ以外はすべてx86-64と同じだ。

[CAUTION]
====
マイクロSDカードのパーティションが解除されていることを確認してください。そうしないと、Piのブートローダーはそこからブートしようとして失敗する。
====

このイメージでノードを起動すれば、ノードは起動する：

* 指定されたregistrationURLで登録し、マシンごとに作成する。 `MachineInventory`
* 指定されたデバイスにSLE Microをインストールする
* リブート
======
========

=== クラスタに参加する適切なマシンを選択する

`MachineInventorySelectorTemplate` 、_element:fire_ラベルを持つ``MachineInventorysから``クラスタのプロビジョニングに必要なマシンを選択します。
`MachineRegistration` `machineInventoryLabels` 、「_element___:fire__」ラベルを追加しましたので、そこから生成された``MachineInventoryは``すべて、すでにこのラベルを持っています。
いずれにせよ、`MachineRegistration` からラベルをスキップして、後で追加することもできる：

[,shell]
----
kubectl -n fleet-default label machineinventory $(kubectl get machineinventory -n fleet-default --no-headers -o custom-columns=":metadata.name") element=fire
----

_element___:fireを__持つ``MachineInventoryが``存在するとすぐに、対応するマシンは選択したプロバイダ(k3s/rke)を経由してクラスタを自動配置する。

数分後、新しいクラスタは完全にプロビジョニングされます！

== クラスタのkubernetesのバージョンとデプロイヤーはどのように選択できますか？

cluster.yamlファイルの`Spec` に`kubernetesVersion` というキーがあります。これはクラスタに使用するバージョンとデプロイ先を設定するもので、例えばrke2のKubernetes+v1``.24.8++は`` +`v1.24.8+rke2r1`と+なり、k3sの+v1`.24.8+k3s`1となる。

互換性のあるすべてのバージョンを確認するには、https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/[]RancherPDF を参照してください。

これらのバージョンの入手方法については、xref:references/kubernetesversions.adoc[バージョン・ドックを]ご覧ください。

`Cluster` リソースの詳細については、xref:references/cluster-reference.adoc[Cluster Spec]ページをご覧ください。

== 舞台裏で何が起こっているのか、どうすれば追いかけることができますか？

マシンが何をやっているのか、その過程を追うことができるはずだ：

* ISOブート中：
 ** マシンにログインする（ユーザー/パス：root/ros）：
  *** `journalctl -f -t elemental` を実行すると、登録_(elemental-register_)と{elemental-product-name} のインストール_(elemental install_)の進行状況が表示されます。
* システムがインストールされると
 ** Rancher UI \->`Cluster Management` では、クラスタの詳細で新しいクラスタと`Provisioning Log` を確認できます。
 ** マシンにログインする（ユーザー/パス：`Spec.config.cloud-config.users` ）のregistration.yamlで設定したものであれば何でもよい：
  *** 実行中の`journalctl -f -u elemental-system-agent` は、最初のエレメンタル・コンフィグの出力と、そのインストールを示している。 `rancher-system-agent`
  *** `journalctl -f -u rancher-system-agent` 、k3sのようなクラスターコンポーネントのブートストラップの出力を示す。
  *** `journalctl -f -u k3s` を実行すると、k3sデプロイのログが表示される。

== オプションだ：CLI経由でElemental UIエクステンションをインストールする

新しいClusterRepoを作成して適用し、公式のRancher Extensionsリポジトリを追加します。

[source,yaml]
----
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-ui-charts
spec:
  gitBranch: main
  gitRepo: https://github.com/rancher/ui-plugin-charts
----

Rancher UI 拡張チャート用の helm リポジトリを追加しました。

[source,shell]
----
helm repo add rancher-ui-plugins https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/
----

Elemental UIエクステンションをインストールする。

[source,shell]
----
helm install elemental rancher-ui-plugins/elemental -n cattle-ui-plugin-system
----