= ManagedOSVersion-Referenz
:revdate: 2025-09-08
:page-revdate: {revdate}

Die Ressource `ManagedOSVersion` ist für die Definition einer Betriebssystem-Image-Version zuständig, die mit den Ressourcen `SeedImage` oder `ManagedOSImage` verwendet werden kann.

Es gibt mehrere Schlüssel, die unter einer `ManagedOSVersion` resource spec konfiguriert werden können.

.managedosversion-example.yaml
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  labels:
    elemental.cattle.io/channel: elemental-channel
  name: v2.0.2
  namespace: fleet-default
spec:
  metadata:
    displayName: SLE Micro
    upgradeImage: registry.suse.com/suse/sle-micro/5.5:2.0.2
  type: container
  version: v2.0.2
----

== `ManagedOSVersionSpec` Referenz

|===
| Schlüssel | Typ | Standardwert | Beschreibung

| metadata
| Objekt
| null
| Hier werden einige Daten über das Betriebssystem-Image definiert. Siehe [Referenz](#Metadaten)

| minVersion
| String
| null
| Nicht verwendet

| Typ
| String
| leer
| Definiert den OS-Image-Typ, kann `container` oder `iso`

| version
| String
| leer
| OS-Image-Version

| upgradeContainer
| Objekt
| null
| Ein Upgrade-Container, der definiert werden kann. Siehe [Referenz](#upgradecontainer)
|===

.Klicken Sie hier für Details
[%collapsible]
====
.ISO-Image Beispiel
[,yaml]
----
metadata:
  displayName: SLE Micro ISO x86_64
  uri: registry.suse.com/suse/sl-micro/6.0/baremetal-iso-image:2.2.0
type: iso
version: v2.2.0
----
====

.Klicken Sie hier für Details
[%collapsible]
====
.container image Beispiel
[,yaml]
----
metadata:
  displayName: SLE Micro upgrade
  upgradeImage: registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:2.2.0
type: container
version: v2.2.0
----
====

== metadata

Dies beschreibt die notwendigen Informationen, um ein Betriebssystem-Image in {elemental-product-name} zu definieren.

Wenn `type` auf `container` eingestellt ist:

|===
| Schlüssel | Typ | Standardwert | Beschreibung

| displayName
| String
| leer
| OS-Image-Name, wie in der Rancher-Benutzeroberfläche zu sehen

| upgradeImage
| String
| leer
| Vollständig qualifiziertes Container-Bild (OCI-Referenz oder HTTP URI)
|===

Wenn `type` auf `iso` eingestellt ist:

|===
| Schlüssel | Typ | Standardwert | Beschreibung

| displayName
| String
| leer
| OS-Image-Name, wie in der Rancher-Benutzeroberfläche zu sehen

| uri
| String
| leer
| Vollständig qualifiziertes ISO-Abbild
|===

== `upgradeContainer`

Dies ermöglicht das Überschreiben des Standardfeldes `upgrade` von System Upgrade Controller-Plänen (siehe xref:rancher-os-management/upgrade-lifecycle.adoc#_components[Upgrade-Komponenten]), die auf dieser ManagedOSVersion basieren.
Diese Schlüssel werden vom System Upgrade Controller in eine Kubernetes https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container[Container-Spezifikation] übersetzt.
Dies ist der Container, der für die Durchführung eines Betriebssystem-Upgrades verantwortlich ist.
