include::partial$variables.adoc[]
= Testes para operadores de cluster
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Teste as políticas do operador de cluster com o kwctl usando diferentes configurações e objetos de solicitação de validação para validar as configurações de política.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["testing-policies", "cluster-operators"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "operadores de cluster", "testing"]
:current-version: {page-origin-branch}

Como operador de cluster do Kubernetes, você deverá realizar testes para as políticas do {project-name} que deseja usar.

Você terá perguntas como:

* Quais são as configurações de política corretas para obter o resultado de validação/mutação necessário?
* Como posso ter certeza de que tudo continua funcionando como esperado quando eu..:
 ** atualizar a política para uma versão mais recente?
 ** adicionar/alterar recursos do Kubernetes?
 ** alterar os parâmetros de configuração da política?
 ** e assim por diante?

{short-project-name} tem um utilitário, https://github.com/kubewarden/kwctl[`+kwctl+`]que permite testar as políticas fora do Kubernetes.

Para usar o `+kwctl+`, você o invoca com as seguintes entradas:

. Um URI de arquivo binário do WebAssembly da política a ser executada.
A política {short-project-name} pode ser carregada a partir do site:
 ** sistema de arquivos local `+file://+`
 ** um servidor HTTP(s) `+https://+`
 ** um registro da OCI `+registry://+`.
. O objeto de solicitação de admissão a ser testado.
Você o apresenta com o argumento `+--request-path+`.
Use `+stdin+` definindo `+--request-path+` para `+-+`.
. As configurações de política para tempo de execução como um JSON em linha por meio do sinalizador `+--settings-json+`.
Ou um arquivo JSON ou YAML, carregado do sistema de arquivos via `+--settings-path+`.

Após o teste `+kwctl+`, imprime o objeto `+ValidationResponse+` na saída padrão.

Você pode fazer o download de binários pré-construídos do `+kwctl+`https://github.com/kubewarden/kwctl/releases[ aqui].

== Um exemplo de teste

Esta seção descreve como testar a políticahttps://github.com/kubewarden/psp-apparmor[psp-apparmor]com diferentes configurações e objetos de solicitação de validação.

=== Criar solicitações em `+AdmissionReview+` 

Você precisa criar arquivos que contenham os objetos `+AdmissionReview+` para testar a política.

Você pode criar um arquivo chamado `+pod-req-no-specific-apparmor-profile.json+` com o seguinte conteúdo:

.pod-req-no-specific-apparmor-profile.json
[%collapsible]
======

[subs="+attributes",json]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "kind": {
    "kind": "Pod",
    "version": "v1"
  },
  "object": {
    "metadata": {
      "name": "no-apparmor"
    },
    "spec": {
      "containers": [
        {
          "image": "nginx",
          "name": "nginx"
        }
      ]
    }
  },
  "operation": "CREATE",
  "requestKind": {"version": "v1", "kind": "Pod"},
  "userInfo": {
    "username": "alice",
    "uid": "alice-uid",
    "groups": ["system:authenticated"]
  }
}
----

======

Essa solicitação tenta criar um Pod que não especifica nenhum perfil AppArmor a ser usado.
Isso ocorre porque ele não tem um `+annotation+` com a chave`+container.apparmor.security.beta.kubernetes.io/<container-name>+`.

Você pode criar um arquivo chamado `+pod-req-apparmor-unconfined.json+` com o seguinte conteúdo:

.pod-req-apparmor-unconfined.json
[%collapsible]
======

[subs="+attributes",json]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "kind": {
    "kind": "Pod",
    "version": "v1"
  },
  "object": {
    "metadata": {
      "name": "privileged-pod",
      "annotations": {
        "container.apparmor.security.beta.kubernetes.io/nginx": "unconfined"
      }
    },
    "spec": {
      "containers": [
        {
          "image": "nginx",
          "name": "nginx"
        }
      ]
    }
  },
  "operation": "CREATE",
  "requestKind": {"version": "v1", "kind": "Pod"},
  "userInfo": {
    "username": "alice",
    "uid": "alice-uid",
    "groups": ["system:authenticated"]
  }
}
----

======

Essa solicitação tenta criar um Pod com um contêiner chamado `+nginx+` em execução com o perfil `+unconfined+` AppArmor.
Isso é apenas para fins de tutorial.
A execução no modo `+unconfined+` é uma prática de segurança ruim.

Agora você pode criar um arquivo chamado`+pod-req-apparmor-custom.json+` com o seguinte conteúdo:

.pod-req-apparmor-custom.json
[%collapsible]
======

[subs="+attributes",json]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "kind": {
    "kind": "Pod",
    "version": "v1"
  },
  "object": {
    "metadata": {
      "name": "privileged-pod",
      "annotations": {
        "container.apparmor.security.beta.kubernetes.io/nginx": "localhost/nginx-custom"
      }
    },
    "spec": {
      "containers": [
        {
          "image": "nginx",
          "name": "nginx"
        }
      ]
    }
  },
  "operation": "CREATE",
  "requestKind": {"version": "v1", "kind": "Pod"},
  "userInfo": {
    "username": "alice",
    "uid": "alice-uid",
    "groups": ["system:authenticated"]
  }
}
----

======

[NOTE]
====
Todos esses são objetos `+AdmissionReview+` simplificados.
Somente os campos relevantes para nossos testes da política são usados.
====


=== Teste a política

Agora você pode usar o site `+kwctl+` para testar a criação de um Pod que não especifique um perfil AppArmor:

[subs="+attributes",console]
----
$ kwctl run \
    --request-path pod-req-no-specific-apparmor-profile.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4 \
    | jq
----

A política aceita a solicitação e produz resultados como:

[subs="+attributes",console]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": true
}
----

A política rejeita a criação de um Pod com um perfil `+unconfined+` AppArmor:

[subs="+attributes",console]
----
$ kwctl run \
    --request-path pod-req-apparmor-unconfined.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4 \
    | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "These AppArmor profiles are not allowed: [\"unconfined\"]"
  }
}
----

Em ambas as ocasiões, você executou a política *sem* fornecer nenhum tipo de configuração.
Como afirma ahttps://github.com/kubewarden/psp-apparmor#configuration[documentação da política], isso resulta na prevenção do uso de perfis não padrão.

O POD que usa um perfil `+nginx+` personalizado também é rejeitado pela apólice:

[subs="+attributes",console]
----
$ kwctl run \
    --request-path pod-req-apparmor-custom.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4 \
    | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "These AppArmor profiles are not allowed: [\"localhost/nginx-custom\"]"
  }
}
----

Você pode alterar o comportamento padrão, permitindo que os perfis AppArmor escolhidos sejam usados:

[subs="+attributes",console]
----
$ kwctl run \
    --request-path pod-req-apparmor-custom.json \
    --settings-json '{"allowed_profiles": ["runtime/default", "localhost/nginx-custom"]}' \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4 \
    | jq
----

Agora a solicitação é bem-sucedida:

[subs="+attributes",console]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": true
}
----

== Automação

Você pode automatizar todas essas etapas usando ohttps://github.com/bats-core/bats-core[site] bats.

Você pode escrever uma série de testes e integrar a execução deles em seus pipelines de CI e CD existentes.

Os comandos podem ser "agrupados" em um teste `+bats+`:

.Um teste de bateria
[%collapsible]
======

[,bash]
----
@test "all is good" {
  run kwctl run \
    --request-path pod-req-no-specific-apparmor-profile.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # request accepted
  [ $(expr "$output" : '.*"allowed":true.*') -ne 0 ]
}

@test "reject" {
  run kwctl run \
    --request-path pod-req-apparmor-custom.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # request rejected
  [ $(expr "$output" : '.*"allowed":false.*') -ne 0 ]
}
----

======

Se o código `+bats+` estiver no arquivo `+e2e.bats+`, você poderá executar o teste como:

[subs="+attributes",console]
----
$ bats e2e.bats
 ✓ all is good
 ✓ reject

2 tests, 0 failures
----

xref:tutorials/writing-policies/go/05-e2e-tests.adoc[Esta]seção contém mais informações sobre como escrever testes de ponta a ponta para suas políticas.
