include::partial$variables.adoc[]
= Einführung in den Open Policy Agent
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie, wie der Open Policy Agent die Rego-Sprache verwendet, um Richtlinien zu schreiben, die bewertet werden und Ergebnisse für sichere Entscheidungen liefern.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "open policy agent", "opa", "rego"]
:sidebar_label: Einführung
:current-version: {page-origin-branch}

[NOTE]
====
Die Unterstützung von Open Policy Agent wurde mit diesen Versionen eingeführt:

* kwctl: v0.2.0
* policy-server: v0.2.0
====


Open Policy Agent (OPA) ist ein allgemeiner Richtlinienrahmen, der die Rego-Sprache zum Schreiben von Richtlinien verwendet.

== Einführung

Rego-Politiken funktionieren, indem sie eine Eingabe erhalten, die sie auswerten, und als Antwort eine Ausgabe produzieren.
In diesem Sinne verfügt OPA über kein spezifisches Tool für die Erstellung von Richtlinien für Kubernetes.

Konkret erhalten die Richtlinien in OPA eine JSON-Eingabe und erzeugen eine JSON-Ausgabe.
Der OPA-Server ist so konfiguriert, dass er Zulassungsprüfungsanfragen von Kubernetes erhält.
Die Richtlinien erhalten ein Kubernetes `+AdmissionReview+` Objekt im JSON-Format.
Sie müssen als Auswertungsergebnis ein gültiges `+AdmissionReview+` Objekt zurückgeben.

== Vereinbarkeit mit bestehenden Politiken

Alle Richtlinien können mit dem offiziellen `+opa+` CLI-Tool in das `+wasm+` Ziel (WebAssembly) kompiliert werden.

Was die Ausführung von Richtlinien betrifft, so können Sie mehr über die xref:tutorials/writing-policies/rego/02-builtin-support.adoc[in] {short-project-name}xref:tutorials/writing-policies/rego/02-builtin-support.adoc[implementierte OPA-Unterstützung] lesen.
