include::partial$variables.adoc[]
= Erstellen und fĂĽhren Sie eine OPA-Richtlinie fĂĽr {short-project-name} aus.
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erstellen Sie eine benutzerdefinierte OPA-Richtlinie fĂĽr Ihr Projekt, indem Sie ein Rego-Paket erstellen, es in ein WASM-Ziel kompilieren und mit kwctl integrieren.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "build-and-run"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "build and run", "open policy agent", "opa", "rego"]
:current-version: {page-origin-branch}

Im vorherigen Abschnitt haben Sie Ihre Rego-Richtlinie geschrieben.
Die Struktur sieht wie folgt aus:

[subs="+attributes",console]
----
.
â”śâ”€â”€ data
â”‚   â”śâ”€â”€ default-ns.json
â”‚   â””â”€â”€ other-ns.json
â”śâ”€â”€ policy.rego
â””â”€â”€ request.rego

1 directory, 4 files
----

== Erstellen

Zum Erstellen:

[subs="+attributes",console]
----
$ opa build -t wasm -e policy/main policy.rego request.rego
----

Dies erstellt die Rego-Richtlinie mit:

* `+target+`: `+wasm+`.
Sie mĂ¶chten die Richtlinie fĂĽr das `+wasm+` Ziel erstellen.
* `+entrypoint+`: `+policy/main+`.
Der Einstiegspunkt ist die `+main+` Regel innerhalb des `+policy+` Pakets.
* `+policy.rego+`:
Erstellen und fĂĽgen Sie die `+policy.rego+` Datei ein.
* `+request.rego+`:
Erstellen und fĂĽgen Sie die `+request.rego+` Datei ein.

Nachdem der Build abgeschlossen ist, hat `+opa build+` eine `+bundle.tar.gz+` Datei generiert.
Sie kĂ¶nnen sie extrahieren:

[subs="+attributes",console]
----
$ tar -xf bundle.tar.gz /policy.wasm
----

Jetzt sieht der Baum wie folgt aus:

[subs="+attributes",console]
----
.
â”śâ”€â”€ bundle.tar.gz
â”śâ”€â”€ data
â”‚   â”śâ”€â”€ default-ns.json
â”‚   â””â”€â”€ other-ns.json
â”śâ”€â”€ policy.rego
â”śâ”€â”€ policy.wasm
â””â”€â”€ request.rego

1 directory, 6 file
----

Sie haben Ihre `+policy.wasm+` Datei:

[subs="+attributes",console]
----
$ file policy.wasm
policy.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
----

Jetzt fĂĽhren Sie sie aus.

== FĂĽhren Sie folgendes Kommando aus:

Verwenden Sie `+kwctl+`, um die Richtlinie auszufĂĽhren:

[subs="+attributes",console]
----
$ kwctl run -e opa --request-path data/other-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": true
}
----

Diese Anfrage wird von der Richtlinie akzeptiert, da dies die Anfrage ist, die auf den `+other+` Namespace verweist.

* `+execution-mode+`: `+opa+`.
Rego-Richtlinien kĂ¶nnen auf Open Policy Agent oder Gatekeeper abzielen.
Sie mĂĽssen `+kwctl+` mitteilen, welche Art von Richtlinie Sie ausfĂĽhren.
* `+request-path+`:
Der Standort der aufgezeichneten Anfrage, an die `+kwctl+` die Richtlinie zur Bewertung sendet.

Versuchen Sie nun, die Anfrage zu bewerten, die den Pod im `+default+` Namespace erstellt:

[subs="+attributes",console]
----
$ kwctl run -e opa --request-path data/default-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "it is forbidden to use the default namespace"
  }
}
----

Die Richtlinie lehnt die Anfrage ab und gibt einen Grund an den API-Server zurĂĽck, der an den Benutzer oder API-Konsumenten weitergeleitet wird.
