= Überprüfen Sie die Funktionsfähigkeit der Instrumente
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

Wenn die Einrichtung des Kollektors und der Instrumente erfolgreich war, sollten die Daten innerhalb von ein oder zwei Minuten in SUSE Observability verfügbar sein.

Sie können überprüfen, ob SUSE Observability Spuren empfängt:

. SUSE Observability in einem Browser öffnen
. Finden Sie (einen) der Pods, die instrumentiert sind
. Wählen Sie den Pod, um die Seite Highlights zu öffnen
. Öffnen Sie die Trace-Perspektive. Wenn der Pod Daten überträgt, sollte er jetzt Spuren anzeigen

So überprüfen Sie, ob SUSE Observability Metriken empfängt:

. SUSE Observability in einem Browser öffnen
. Öffnen Sie den Metrik-Explorer über das Menü
. Suche nach den von Ihrer Anwendung bereitgestellten Metriken

Wenn nach 5 Minuten immer noch keine Metriken angezeigt werden, ist wahrscheinlich etwas falsch konfiguriert. Siehe xref:/setup/otel/troubleshooting.adoc[Fehlerbehebung] für Hilfe.
