= Funciones
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

== Visión general

Cada usuario de SUSE Observability necesita tener asignados un asunto y un conjunto de xref:/setup/security/rbac/rbac_permissions.adoc[permisos]; esta combinación se denomina rol. Un rol describe un grupo de usuarios que pueden acceder a un conjunto de datos específico. SUSE Observability incluye un conjunto de funciones predefinidas y también puede crear funciones que se adapten a sus necesidades.

== Funciones predefinidas

Existen cuatro funciones predefinidas en SUSE Observability:

* *Administrador*: tiene acceso completo a todas las vistas y dispone de todos los permisos.
* *Usuario avanzado*: normalmente se concede a un usuario que necesita configurar SUSE Observability para un equipo o equipos, pero que no gestionará toda la instalación de SUSE Observability.
* *Solucionador de problemas de Kubernetes*: tiene todos los permisos necesarios para utilizar SUSE Observability para la solución de problemas, incluida la capacidad de activar/desactivar monitores, crear vistas personalizadas y utilizar el Cli.
* *Invitado*: tiene acceso de sólo lectura a SUSE Observability.

A continuación se indican los permisos asignados a cada función predefinida de SUSE Observability. Para obtener más información sobre los distintos permisos y cómo gestionarlos mediante la CLI de `sts`, consulte xref:/setup/security/rbac/rbac_permissions.adoc[Permisos de control de acceso basado en funciones (RBAC)].

[tabs]
====
Administrador::
+
--

El rol Administrador (`stackstate-admin`): tiene todos los permisos asignados.

Los permisos asignados al rol predefinido de Administrador (`stackstate-admin`) se listan a continuación, estos fueron recuperados usando el CLI `sts`. Para obtener más información sobre los distintos permisos y cómo gestionarlos mediante la CLI `sts`, consulte xref:/setup/security/rbac/rbac_permissions.adoc[Permisos RBAC].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-admin
Got subject from the following subject sources: Static

PERMISSION                      | RESOURCE
create-dashboards               | system
create-favorite-dashboards      | system
create-favorite-views           | system
create-ingestion-api-keys       | system
create-metric-bindings          | system
create-monitors                 | system
create-notifications            | system
create-service-tokens           | system
create-stackpack-configurations | system
create-views                    | system
delete-dashboards               | system
delete-favorite-dashboards      | system
delete-favorite-views           | system
delete-ingestion-api-keys       | system
delete-metric-bindings          | system
delete-monitors                 | system
delete-notifications            | system
delete-service-tokens           | system
delete-stackpack-configurations | system
delete-sync-data                | system
delete-views                    | system
execute-component-actions       | system
execute-monitors                | system
execute-restricted-scripts      | system
execute-scripts                 | system
get-agents                      | system
get-api-tokens                  | system
get-dashboards                  | system
get-ingestion-api-keys          | system
get-metric-bindings             | system
get-metrics                     | system
get-monitors                    | system
get-notifications               | system
get-permissions                 | system
get-service-tokens              | system
get-settings                    | system
get-stackpacks                  | system
get-sync-data                   | system
get-system-notifications        | system
get-topic-messages              | system
get-topology                    | system
get-traces                      | system
get-views                       | system
update-dashboards               | system
update-metric-bindings          | system
update-metrics                  | system
update-monitors                 | system
update-notifications            | system
update-permissions              | system
update-scoped-permissions       | system
update-settings                 | system
update-stackpack-configurations | system
update-stackpacks               | system
update-views                    | system
update-visualization            | system
----

--
Usuario avanzado::
+
--

El rol de Power User (`stackstate-power-user`) tiene todos los permisos de Administrador, excepto:

* `execute-restricted-scripts`
* `update-permissions`
* `update-stackpacks`

Los permisos asignados al rol predefinido de Power User (`stackstate-power-user`) se listan a continuación, estos fueron recuperados usando el CLI `sts`. Para obtener más información sobre los distintos permisos y cómo gestionarlos mediante la CLI `sts`, consulte xref:/setup/security/rbac/rbac_permissions.adoc[Permisos RBAC].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-power-user
Got subject from the following subject sources: Static

PERMISSION                      | RESOURCE
create-dashboards               | system
create-favorite-dashboards      | system
create-favorite-views           | system
create-metric-bindings          | system
create-monitors                 | system
create-notifications            | system
create-stackpack-configurations | system
create-views                    | system
delete-dashboards               | system
delete-favorite-dashboards      | system
delete-favorite-views           | system
delete-metric-bindings          | system
delete-monitors                 | system
delete-notifications            | system
delete-stackpack-configurations | system
delete-sync-data                | system
execute-component-actions       | system
execute-monitors                | system
execute-scripts                 | system
get-agents                      | system
get-api-tokens                  | system
get-dashboards                  | system
get-metric-bindings             | system
get-metrics                     | system
get-monitors                    | system
get-notifications               | system
get-permissions                 | system
get-settings                    | system
get-stackpacks                  | system
get-sync-data                   | system
get-system-notifications        | system
get-topic-messages              | system
get-topology                    | system
get-traces                      | system
get-views                       | system
update-dashboards               | system
update-metric-bindings          | system
update-metrics                  | system
update-monitors                 | system
update-notifications            | system
update-settings                 | system
update-stackpack-configurations | system
update-views                    | system
update-visualization            | system
----

--
Solucionador de problemas::
+
--

El rol Troubleshooter (`stackstate-k8s-troubleshooter`) tiene acceso a todos los datos disponibles en SUSE Observability y la capacidad de crear vistas y activar/desactivar monitores.

A continuación se enumeran los permisos asignados al rol predefinido de solucionador de problemas, estos se recuperaron utilizando la CLI `sts`. Para obtener más información sobre los distintos permisos y cómo gestionarlos mediante la CLI `sts`, consulte xref:/setup/security/rbac/rbac_permissions.adoc[Permisos RBAC].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-k8s-troubleshooter
Got subject from the following subject sources: Static

PERMISSION                 | RESOURCE
create-dashboards          | system
create-favorite-dashboards | system
create-favorite-views      | system
create-monitors            | system
create-notifications       | system
create-views               | system
delete-dashboards          | system
delete-favorite-dashboards | system
delete-favorite-views      | system
delete-monitors            | system
delete-notifications       | system
delete-views               | system
execute-monitors           | system
get-agents                 | system
get-api-tokens             | system
get-dashboards             | system
get-metric-bindings        | system
get-metrics                | system
get-monitors               | system
get-notifications          | system
get-permissions            | system
get-settings               | system
get-stackpacks             | system
get-system-notifications   | system
get-topic-messages         | system
get-traces                 | system
get-views                  | system
update-dashboards          | system
update-monitors            | system
update-notifications       | system
update-stackpacks          | system
update-views               | system
update-visualization       | system
----

--
Invitado::
+
--

La función Invitado (`stackstate-guest`) tiene acceso de sólo lectura a SUSE Observability.

Los permisos asignados al rol predefinido de Invitado se listan a continuación, estos fueron recuperados usando el CLI `sts`. Para obtener más información sobre los distintos permisos y cómo gestionarlos mediante la CLI `sts`, consulte xref:/setup/security/rbac/rbac_permissions.adoc[Permisos RBAC].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-guest
Got subject from the following subject sources: Static

PERMISSION                 | RESOURCE
create-dashboards          | system
create-favorite-dashboards | system
create-favorite-views      | system
delete-dashboards          | system
delete-favorite-dashboards | system
delete-favorite-views      | system
get-api-tokens             | system
get-dashboards             | system
get-metric-bindings        | system
get-metrics                | system
get-monitors               | system
get-notifications          | system
get-permissions            | system
get-settings               | system
get-system-notifications   | system
get-topic-messages         | system
get-traces                 | system
get-views                  | system
update-dashboards          | system
update-visualization       | system
----

--
====

== Roles personalizados (Configuración RBAC)

Además de los roles predefinidos (`stackstate-admin`, `stackstate-power-user`, `stackstate-k8s-troubleshooter`, `stackstate-guest`), que siempre están disponibles, se pueden añadir roles personalizados. Hay varias formas de añadir roles personalizados:

. a través del archivo de configuración, con los mismos permisos que los roles predefinidos
. a través del archivo de configuración, con unos permisos personalizados
. utilizando la CLI `sts`, los sujetos y sus permisos se almacenan en la base de datos y pueden modificarse durante el tiempo de ejecución

Las funciones añadidas a través del archivo de configuración requieren un reinicio y, por tanto, provocan un breve periodo de inactividad. Las funciones creadas mediante la CLI se almacenan en la base de datos y pueden modificarse en tiempo de ejecución.

=== Nombres personalizados para funciones predefinidas

Utilice esta opción cuando las funciones predefinidas de SUSE Observability sean adecuadas pero el proveedor de autenticación externo tenga nombres diferentes para las funciones. Por ejemplo, cuando el proveedor de autenticación LDAP tiene roles similares pero con nombres diferentes, incluye este fragmento YAML en `authentication.yaml` para dar a los roles de LDAP los mismos permisos y ámbitos que los roles predefinidos equivalentes.

[,yaml]
----
stackstate:
  authentication:
    roles:
      guest: ["ldap-guest-role"]
      powerUser: ["ldap-power-user-role"]
      admin: ["ldap-admin-role"]
      k8sTroubleshooter: ["ldap-troubleshooter-role"]
----

Para utilizarlo en su instalación de SUSE Observability (o en una instancia ya en ejecución, tenga en cuenta que reiniciará la API):

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

=== Funciones personalizadas a través del archivo de configuración

Para configurar un nuevo rol llamado `development-troubleshooter`, que permitirá los mismos permisos que el rol predefinido de solucionador de problemas, pero sólo para el clúster `dev-test`, incluya este fragmento de YAML en un `authentication.yaml`:

[,yaml]
----
stackstate:
  authentication:
    roles:
      custom:
        development-troubleshooter:
          systemPermissions:
          - create-dashboards
          - create-favorite-dashboards
          - create-favorite-views
          - create-monitors
          - create-notifications
          - create-views
          - delete-dashboards
          - delete-favorite-dashboards
          - delete-favorite-views
          - delete-monitors
          - delete-notifications
          - delete-views
          - execute-monitors
          - get-agents
          - get-api-tokens
          - get-dashboards
          - get-metric-bindings
          - get-metrics
          - get-monitors
          - get-notifications
          - get-permissions
          - get-settings
          - get-stackpacks
          - get-system-notifications
          - get-topic-messages
          - get-traces
          - get-views
          - update-dashboards
          - update-monitors
          - update-notifications
          - update-stackpacks
          - update-views
          - update-visualization
          resourcePermissions:
            get-topology:
            - "cluster-name:dev-test"
----

Para utilizarlo en su instalación de SUSE Observability (o en una instancia ya en ejecución, tenga en cuenta que reiniciará la API):

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

=== Roles personalizados a través de la CLI (Observability RBAC)

Para configurar un nuevo rol llamado `development-troubleshooter`, que permitirá los mismos permisos que el rol normal de solucionador de problemas, pero sólo para el clúster `dev-test`, es necesario crear un nuevo tema. Además, es necesario asignar a este sujeto el conjunto de permisos necesarios:

. Crea el asunto (con el mismo nombre que el rol, la correspondencia rol-sujeto se basa en el nombre y distingue entre mayúsculas y minúsculas):
+
[,text]
----
sts rbac create-subject --subject development-troubleshooter
sts rbac grant --subject development-troubleshooter --permission get-topology --resource "cluster-name:dev-test"'
----
+

. Los sujetos configurados necesitan permisos para acceder a partes de la interfaz de usuario y ejecutar acciones en ella. Para conceder los mismos permisos que el rol de solucionador de problemas, siga el siguiente ejemplo:
+
[,text]
----
sts rbac grant --subject development-troubleshooter --permission create-dashboards
sts rbac grant --subject development-troubleshooter --permission create-favorite-dashboards
sts rbac grant --subject development-troubleshooter --permission create-favorite-views
sts rbac grant --subject development-troubleshooter --permission create-monitors
sts rbac grant --subject development-troubleshooter --permission create-notifications
sts rbac grant --subject development-troubleshooter --permission create-views
sts rbac grant --subject development-troubleshooter --permission delete-dashboards
sts rbac grant --subject development-troubleshooter --permission delete-favorite-dashboards
sts rbac grant --subject development-troubleshooter --permission delete-favorite-views
sts rbac grant --subject development-troubleshooter --permission delete-monitors
sts rbac grant --subject development-troubleshooter --permission delete-notifications
sts rbac grant --subject development-troubleshooter --permission delete-views
sts rbac grant --subject development-troubleshooter --permission execute-monitors
sts rbac grant --subject development-troubleshooter --permission get-agents
sts rbac grant --subject development-troubleshooter --permission get-api-tokens
sts rbac grant --subject development-troubleshooter --permission get-dashboards
sts rbac grant --subject development-troubleshooter --permission get-metric-bindings
sts rbac grant --subject development-troubleshooter --permission get-metrics
sts rbac grant --subject development-troubleshooter --permission get-monitors
sts rbac grant --subject development-troubleshooter --permission get-notifications
sts rbac grant --subject development-troubleshooter --permission get-permissions
sts rbac grant --subject development-troubleshooter --permission get-settings
sts rbac grant --subject development-troubleshooter --permission get-stackpacks
sts rbac grant --subject development-troubleshooter --permission get-system-notifications
sts rbac grant --subject development-troubleshooter --permission get-topic-messages
sts rbac grant --subject development-troubleshooter --permission get-traces
sts rbac grant --subject development-troubleshooter --permission get-views
sts rbac grant --subject development-troubleshooter --permission update-dashboards
sts rbac grant --subject development-troubleshooter --permission update-monitors
sts rbac grant --subject development-troubleshooter --permission update-notifications
sts rbac grant --subject development-troubleshooter --permission update-stackpacks
sts rbac grant --subject development-troubleshooter --permission update-views
sts rbac grant --subject development-troubleshooter --permission update-visualization
----

Tenga en cuenta que el nombre del sujeto, así como los permisos, distinguen entre mayúsculas y minúsculas.
