include::partial$variables.adoc[]
= Introducción al CEL
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Conozca CEL (Computation Expression Language) como un lenguaje de expresión rápido, portátil y seguro diseñado para las reglas de validación de Kubernetes y las extensiones de la API de Kubernetes.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "introduction"]
:current-version: {page-origin-branch}

https://cel.dev[Common Expression Language (CEL)] es un lenguaje de expresión de uso general diseñado para ser rápido, portátil y seguro de ejecutar. CEL es un lenguaje seguro en cuanto a memoria, sin efectos secundarios, terminante (los programas no pueden repetirse eternamente) y con tipado fuerte y dinámico. Puede obtener más información sobre CEL enhttps://cel.dev[cel.dev], y practicarlo en https://playcel.undistro.io[CEL playground].

== CEL en Kubernetes

Se eligió CEL como lenguaje para las reglas de validación de Kubernetes, ya que las expresiones CEL pueden incorporarse fácilmente a los esquemas CRD y compilarse y comprobarse "antes de tiempo" (cuando se crean y actualizan los CRD). Por estas razones y por sus características generales, es un candidato perfecto para ampliar la API de Kubernetes.

Marcado como estable con Kubernetes 1.30, se puede utilizar CEL enhttps://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy[ValidatingAdmissionPolicies]y otras reglas de validación. Para más información, consulte la documentación de Kuberneteshttps://kubernetes.io/docs/reference/using-api/cel[aquí].

=== Bibliotecas de funciones de Kubernetes

Las reglas de validación CEL de Kubernetes tienen acceso a varias bibliotecas de funciones:

* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#list-of-standard-definitions[Funciones estándar CEL]
* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#macros[Macros estándar CEL]
* https://pkg.go.dev/github.com/google/cel-go/ext#Strings[Biblioteca de funciones de cadena ampliada CEL]
* https://kubernetes.io/docs/reference/using-api/cel/#kubernetes-cel-libraries[Bibliotecas de extensión CEL de Kubernetes], con funciones suplementarias para listas, regex, URL, autorizadores, cantidades, tipos opcionales, comparaciones numéricas, etc.

== CEL en {project-name}: `+cel-policy+`

{short-project-name} proporciona https://github.com/kubewarden/cel-policy[cel-policy].
Se trata de una política que compila y agrupa el intérpretehttps://pkg.go.dev/github.com/google/cel-go[cel-go de], así como las distintas bibliotecas enumeradas anteriormente y disponibles para CEL en Kubernetes desde`+apiextensions-apiserver+`.

Además, `+cel-policy+` incluye una *biblioteca de extensión CEL{short-project-name} * que expone{short-project-name}'s https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[host capabilities as native CEL]:

* Verificación Sigstore
* Interacción OCI
* Funciones criptográficas
* Operaciones de red
* Acceso a los recursos de Kubernetes

Esto significa que `+cel-policy+` es un superconjunto de Kubernetes CEL, y compatible con versiones anteriores. Se puede reutilizar CEL escrito para Kubernetes vainilla, y/o hacer uso de las características añadidas por {short-project-name}.

`+cel-policy+` se envía compilado y se comporta como un intérprete CEL. Los usuarios de la política introducen las expresiones CEL deseadas en la dirección `+spec.settings+` de la (Cluster)AdmissionPolicy y, gracias a las funciones de CEL, la expresión se compila y se comprueba su corrección tipográfica al crear o actualizar la (Cluster)AdmissionPolicy. Esto significa que no es necesario personalizar`+cel-policy+`.

=== Ventajas de {short-project-name}'s `+cel-policy+` en comparación con ValidatingAdmissionPolicies

El sitio {short-project-name} `+cel-policy+`:

* Su código CEL es compatible con ValidatingAdmissionPolicies.
* Al contrario que ValidatingAdmissionPolicies, no necesita un enlace como ValidatingAdmissionPolicyBinding, ya que está incluido en las definiciones de (Cluster)Admissionpolicies de {short-project-name}.
* Puede desplegarse en clusters que no soporten ValidatingAdmissionPolicies.
* Es consciente del xref:../../../reference/spec/05-context-aware-policies.adoc[contexto] y utiliza los permisos detallados de {short-project-name} para xref:../../../reference/spec/05-context-aware-policies.adoc[conocer el contexto].
* Se despliega como (Cluster)AdmissionPolicy.
* Se beneficia de la trazabilidad y telemetría de las políticas de {short-project-name}.
* El escáner de auditoría lo tendrá en cuenta.
* Puede desarrollarse y probarse fuera del clúster gracias a kwctl.
