include::partial$variables.adoc[]
= 監査スキャナとは何ですか？
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: クラスタ全体のアドミッションコントローラポリシーに対するクラスタのコンプライアンスを継続的に検証するAudit Scannerの役割について説明します。
:doc-persona: ["kubewarden-user"、"kubewarden-operator"、"kubewarden-policy-developer"、"kubewarden-integrator"]]。
:doc-topic: ["explanations", "audit-scanner"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "audit scanner", "kubernetes" ]。
:sidebar_label: 監査スキャナー
:sidebar_position: 50
:current-version: {page-origin-branch}

[NOTE]
====

監査スキャナ機能は、{project-name} 1.7.0リリースから利用可能です。

====


`+audit-scanner+` コンポーネントはクラスタ内のリソースを常にチェックする。クラスタに展開された{short-project-name} ポリシーに準拠していないものにフラグを立てる。

政策は時間とともに進化する。新しいポリシーの導入とポリシーの更新がある。
バージョンとコンフィギュレーション設定が変わる。これにより、すでにクラスタ内にあるリソースがコンプライアンスに適合しなくなる事態が発生する可能性がある。監査スキャン機能は、Kubernetes管理者にクラスタのコンプライアンス状態を常時検証するツールを提供する。

{short-project-name} における監査スキャナーの使い方を説明するために、以下のシナリオを考えてみよう。

BobがクラスタにWordPress Podをデプロイしていると仮定する。ボブはKubernetesに慣れておらず、間違えて特権コンテナとして動作するPodをデプロイしてしまった。この時点では、それを妨げるポリシーはないので、Podはクラスタ内に正常に作成される。

数日後、Kubernetesの管理者であるAliceは、特権コンテナの作成を禁止する{short-project-name}。ボブによってデプロイされたPodは、すでに存在しているものとしてクラスタ内で実行され続ける。

監査スキャナによって生成されたレポートによって、アリスは作成ポリシーに違反しているすべてのワークロードを特定することができます。これにはボブが作成したWordPress Podも含まれる。

監査スキャナーは次のように動作する：

* 監査するすべてのリソースを特定する
* 各リソースについて、リソースのデータを使って合成アドミッション要求を構築する。
* 各入会リクエストを監査リクエスト専用のポリシーサーバーエンドポイントに送ります。

リクエストを評価する方針については、実際のリクエストと監査リクエストの間に違いはない。この監査ポリシー・サーバーのエンドポイントには、評価に関するデータを収集するインスツルメンテーションがある。そのため、ユーザーは監視ツールを使って監査スキャナーのデータを分析することができる。

== 監査スキャナを有効にする

{short-project-name} 1.7.0リリースから監査スキャナを有効にできます。

詳細なインストール手順は、xref:howtos/audit-scanner.adoc[監査スキャナのハウツーに]あります。

== ポリシー

デフォルトでは、監査スキャナはすべてのポリシーを評価します。監査スキャナでポリシー評価をスキップしたいオペレータは、ポリシー定義で`+spec.backgroundAudit+` フィールドを`+false+` に設定する必要があります。

また、{short-project-name} のポリシーは、2つのオプションの注釈をサポートするようになった：

* `+io.kubewarden.policy.severity+` 注釈では、ポリシー違反の重大度レベルを指定できます（`+critical+` 、`+high+` 、`+medium+` 、`+low+` 、`+info+` など）。
* `+io.kubewarden.policy.category+` アノテーションでは、`+PSP+` 、`+compliance+` 、`+performance+` など、特定のドメインや目的に基づいてポリシーを分類できます。

詳しくはポリシー作成者のxref:tutorials/writing-policies/index.adoc[ドキュメントを]参照。

== パーミッションとサービスアカウント

{short-project-name} の監査スキャナーは、Kubernetesリソースをスキャンして結果を保存できるようにするために、特定の役割ベースのアクセス制御（RBAC）設定を必要とする。インストールにより、これらの権限を持つ正しいデフォルトのサービスアカウントが作成されます。ユーザーは独自のServiceAccountを作成し、リソースへのアクセスを設定できる。

デフォルトの監査スキャナ`+ServiceAccount+` は、Kubernetes が提供する`+view+` `+ClusterRole+`にバインドする。この`+ClusterRole+` 、ネームスペース内の幅広いKubernetesリソースへの読み取り専用アクセスを許可する。この役割の詳細については、https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles[Kubernetes documentation]を参照されたい。

監査スキャナーは、{short-project-name} リソースタイプへの読み取りアクセスと、`+PolicyReport+` CRDへの読み取り/書き込みアクセスを許可する`+ClusterRole+` にバインドする。 これらの権限により、スキャナーは監査評価を実施するためのリソースを取得し、評価結果に基づいてポリシー・レポートを作成することができる。
