= Espelho de registro incorporado
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

[IMPORTANT]
.Versão Gate
====
O Embedded Registry Mirror está disponível como um recurso experimental a partir das versões de janeiro de 2024: v1.26.13+k3s1, v1.27.10+k3s1, v1.28.6+k3s1, v1.29.1+k3s1 e GA a partir das versões de dezembro de 2024: v1.29.12+k3s1, v1.30.8+k3s1, v1.31.4+k3s1.
====

O K3s incorpora o https://github.com/XenitAB/spegel[Spegel], um espelho de registro OCI distribuído e sem estado que permite o compartilhamento ponto a ponto de imagens de contêineres entre nós em um cluster do Kubernetes. O espelho de registro distribuído é desativado por padrão. Para que o K3s possa aproveitá-lo, é necessário ativar o xref:#_enabling_the_distributed_oci_registry_mirror[Distributed OCI Registry Mirror] e o xref:#_enabling_registry_mirroring[espelhamento de registro], conforme explicado nas subseções a seguir.

[#_enabling_the_distributed_oci_registry_mirror]
== Habilitando o espelho do registro distribuído da OCI

Para ativar o espelho de registro incorporado, os nós do servidor devem ser iniciados com o sinalizador `--embedded-registry` ou com `embedded-registry: true` no arquivo de configuração.
Essa opção ativa o espelho incorporado para uso em todos os nós do cluster.

Quando ativado em um nível de cluster, todos os nós hospedarão um registro OCI local na porta 6443 e publicarão uma lista de imagens disponíveis por meio de uma rede ponto a ponto na porta 5001.
Qualquer imagem disponível no armazenamento de imagens do containerd em qualquer nó pode ser obtida por outros membros do cluster sem acesso a um registro externo.
As imagens importadas por meio de xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[arquivos tar de imagem air-gap] são fixadas no containerd para garantir que permaneçam disponíveis e não sejam eliminadas pela coleta de lixo do Kubelet.

A porta ponto a ponto pode ser alterada de 5001 com a configuração da variável de ambiente `K3S_P2P_PORT` para o serviço K3s. A porta deve ser definida com o mesmo valor em todos os nós.
Não há suporte e não é recomendável alterar a porta.

=== Requisitos

Quando o espelho de registro incorporado está ativado, todos os nós devem ser capazes de alcançar uns aos outros por meio de seus endereços IP internos, nas portas TCP 5001 e 6443.
Se os nós não puderem se comunicar entre si, pode levar mais tempo para que as imagens sejam extraídas, pois o registro distribuído será tentado primeiro pelo containerd, antes de voltar para outros pontos de extremidade.

[#_enabling_registry_mirroring]
== Como ativar o espelhamento do registro

A ativação do espelhamento de um registro permite que um nó extraia imagens desse registro de outros nós e compartilhe as imagens do registro com outros nós.
Se um registro estiver ativado para espelhamento em alguns nós, mas não em outros, somente os nós com o registro ativado trocarão imagens desse registro.

Para ativar o espelhamento de imagens de um registro de contêiner upstream, os nós devem ter uma entrada na seção `mirrors` de `registries.yaml` para esse registro.
O registro não precisa ter nenhum ponto de extremidade listado, ele só precisa estar presente.
Por exemplo, para ativar o espelhamento distribuído de imagens de `docker.io` e `registry.k8s.io`, configure `registries.yaml` com o seguinte conteúdo em todos os nós do cluster:

[,yaml]
----
mirrors:
  docker.io:
  registry.k8s.io:
----

Os pontos de extremidade para espelhos de registro também podem ser adicionados como de costume.
Na configuração a seguir, as tentativas de extração de imagens tentarão primeiro o espelho incorporado, depois `mirror.example.com` e, por fim, `docker.io`:

[,yaml]
----
mirrors:
  docker.io:
    endpoint:
      - https://mirror.example.com
----

Se você estiver usando um registro privado diretamente, e não como espelho de um registro upstream, poderá ativar o espelhamento distribuído da mesma forma que os registros públicos são ativados, listando-o na seção de espelhos:

[,yaml]
----
mirrors:
  mirror.example.com:
----

[IMPORTANT]
.Versão Gate
====
O suporte a curingas está disponível a partir das versões de março de 2024: v1.26.15+k3s1, v1.27.12+k3s1, v1.28.8+k3s1, v1.29.3+k3s1
====


A entrada `"*"` wildcard mirror pode ser usada para ativar o espelhamento distribuído de todos os registros. Observe que o asterisco DEVE estar entre aspas:

[,yaml]
----
mirrors:
  "*":
----

Se nenhum registro estiver habilitado para espelhamento em um nó, esse nó não participará do registro distribuído em nenhuma capacidade.

Para obter mais informações sobre a estrutura do arquivo `registries.yaml`, consulte xref:installation/private-registry.adoc[Configuração do registro privado].

=== Fallback de ponto de extremidade padrão

Por padrão, o containerd voltará ao endpoint padrão ao extrair de registros com endpoints espelhados configurados. Se quiser desativar essa opção e extrair imagens apenas dos espelhos configurados e/ou do espelho incorporado, consulte a seção xref:installation/private-registry.adoc#_default_endpoint_fallback[Default Endpoint Fallback]da documentação Private Registry Configuration.

Observe que, se você estiver usando a opção `--disable-default-registry-endpoint` e quiser permitir a extração direta de um registro específico e não permitir o restante, poderá fornecer explicitamente um ponto de extremidade para permitir que a extração da imagem retorne ao próprio registro:

[,yaml]
----
mirrors:
  docker.io:           # no default endpoint, pulls will fail if not available on a node
  registry.k8s.io:     # no default endpoint, pulls will fail if not available on a node
  mirror.example.com:  # explicit default endpoint, can pull from upstream if not available on a node
    endpoint:
      - https://mirror.example.com
----

=== Última tag

Quando nenhuma tag é especificada para uma imagem de contêiner, a tag padrão implícita é `latest`. Essa tag é atualizada com frequência para indicar a versão mais recente da imagem. Como essa tag apontará para revisões diferentes de uma imagem, dependendo de quando ela for extraída, o registro distribuído *não extrairá* a tag `latest` de outros nós. Isso força o containerd a recorrer a um registro upstream ou espelho de registro para garantir uma visão consistente do que a tag `latest` se refere.

Isso se alinha com o https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting[padrão]observado pelo Kubernetes ao usar a tag `latest` para uma imagem de contêiner.

O espelhamento da tag `latest` pode ser ativado com a configuração da variável de ambiente `K3S_P2P_ENABLE_LATEST=true` para o serviço K3s.
Isso não é suportado e não é recomendado, pelos motivos discutidos acima.

== Segurança

=== Autenticação

O acesso à API de registro do espelho incorporado requer um certificado de cliente válido, assinado pela autoridade de certificação do cliente do cluster.

O acesso à rede ponto a ponto da tabela de hash distribuída requer uma chave pré-compartilhada que é controlada pelos nós do servidor.
Os nós se autenticam uns aos outros usando a chave pré-compartilhada e um certificado assinado pela autoridade de certificação do cluster.

=== Preocupações em potencial

[CAUTION]
====
O registro distribuído foi criado com base nos princípios ponto a ponto e pressupõe um nível igual de privilégio e confiança entre todos os membros do cluster.
Se isso não corresponder à postura de segurança do seu cluster, você não deve ativar o registro distribuído incorporado.
====


O registro incorporado pode disponibilizar imagens às quais um nó não teria acesso de outra forma.
Por exemplo, se algumas das suas imagens forem extraídas de um registro, projeto ou repositório que exija autenticação via Kubernetes Image Pull Secrets ou credenciais em `registries.yaml`, o registro distribuído permitirá que outros nós compartilhem essas imagens sem fornecer nenhuma credencial ao registro upstream.

Os usuários com acesso para enviar imagens para o armazenamento de imagens do containerd em um nó podem usar isso para "envenenar" a imagem para outros nós do cluster, pois outros nós confiarão na tag anunciada pelo nó e a usarão sem verificar o registro upstream.
Se a integridade da imagem for importante, você deve usar resumos de imagem em vez de tags, pois o resumo não pode ser envenenado dessa maneira.

== Compartilhamento de imagens com intervalo de ar ou carregadas manualmente

O compartilhamento de imagens é controlado com base no registro de origem.
As imagens carregadas diretamente no containerd por meio de xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[tarballs do air-gap], xref:add-ons/import-images.adoc#_pre_import_images[pré-importadas] ou carregadas diretamente no armazenamento de imagens do containerd usando a ferramenta de linha de comando `ctr` serão compartilhadas entre os nós se forem marcadas como sendo de um registro habilitado para espelhamento.

Observe que o registro upstream de onde as imagens parecem vir não precisa realmente existir ou ser acessível.
Por exemplo, você pode marcar imagens como sendo de um registro upstream fictício e importar essas imagens para o armazenamento de imagens do containerd.
Assim, você poderá extrair essas imagens de todos os membros do cluster, desde que esse registro esteja listado em `registries.yaml`

== Empurrando imagens

O registro incorporado é somente de leitura e não pode ser enviado diretamente por push usando `docker push` ou outras ferramentas comuns que interagem com registros OCI.

As imagens podem ser disponibilizadas manualmente por meio do registro incorporado, executando `ctr -n k8s.io image pull` para extrair uma imagem ou carregando arquivos de imagem criados por `docker save` por meio do comando `ctr -n k8s.io image import` ou do xref:add-ons/import-images.adoc#_pre_import_images[recurso de pré-importação].
Observe que o namespace `k8s.io` deve ser especificado ao gerenciar imagens via `ctr` para que elas fiquem visíveis para o kubelet.
