= Requisitos
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-31
:page-revdate: {revdate}

O K3s é muito leve, mas tem alguns requisitos mínimos, conforme descrito abaixo.

Se você estiver configurando o K3s para ser executado em um contêiner ou como um serviço Linux nativo, cada nó que estiver executando o K3s deverá atender aos seguintes requisitos mínimos. Esses requisitos são a linha de base para o K3s e seus componentes empacotados, e não incluem os recursos consumidos pela própria carga de trabalho.

== Pré-requisitos

Dois nós não podem ter o mesmo nome de host.

Se vários nós tiverem o mesmo nome de host ou se os nomes de host puderem ser reutilizados por um sistema de provisionamento automatizado, use a opção `--with-node-id` para acrescentar um sufixo aleatório a cada nó ou crie um nome exclusivo para passar com `--node-name` ou `$K3S_NODE_NAME` para cada nó adicionado ao cluster.

== Arquitetura

O K3s está disponível para as seguintes arquiteturas:

* x86_64
* armhf
* arm64/aarch64

[CAUTION]
.Tamanho da página do ARM64
====

Antes das versões de maio de 2023 (v1.24.14+k3s1, v1.25.10+k3s1, v1.26.5+k3s1, v1.27.2+k3s1), em sistemas `aarch64/arm64`, o kernel deve usar páginas de 4k. *O RHEL9*, o *Ubuntu*, *o Raspberry PI OS* e *o SLES* atendem a esse requisito.
====

[#_operating_systems]
== Sistemas operacionais

Espera-se que o K3s funcione na maioria dos sistemas Linux modernos.

Alguns sistemas operacionais têm requisitos de configuração adicionais:

[tabs,sync-group-id=os,id=os]
======
SUSE Linux Enterprise / openSUSE::
+
--
[#_sle_opensuse_firewalld]
[pass]
<h3><a class="anchor" id="_sle_opensuse_firewalld" href="#_sle_opensuse_firewalld"></a>Firewalld</h3>

Recomenda-se desativar o firewalld:

[,bash]
----
systemctl disable firewalld --now
----

Se você deseja manter o firewalld ativado, por padrão, as seguintes regras são necessárias:

[,bash]
----
firewall-cmd --permanent --add-port=6443/tcp #apiserver
firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
firewall-cmd --reload
----

Pode ser necessário abrir outras portas, dependendo de sua configuração. Consulte <<_inbound_rules_for_k3s_nodes,Regras de entrada>> para obter mais informações. Se você alterar o CIDR padrão para pods ou serviços, será necessário atualizar as regras de firewall de acordo.
--

Red Hat Enterprise Linux / CentOS / Fedora::
+
--
[#_rhel10]
[pass]
<h3><a class="anchor" id="_rhel10" href="#_rhel10"></a>RHEL 10</h3>

No RHEL 10, é necessário um pacote adicional:

[,bash]
----
sudo dnf install -y kernel-modules-extra
----

[#_rhel_centos_fedora_firewalld]
[pass]
<h3><a class="anchor" id="_rhel_centos_fedora_firewalld" href="#_rhel_centos_fedora_firewalld"></a>Firewalld</h3>

Recomenda-se desativar o firewalld:

[,bash]
----
systemctl disable firewalld --now
----

Se você deseja manter o firewalld ativado, por padrão, as seguintes regras são necessárias:

[,bash]
----
firewall-cmd --permanent --add-port=6443/tcp #apiserver
firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
firewall-cmd --reload
----

Pode ser necessário abrir outras portas, dependendo de sua configuração. Consulte <<_inbound_rules_for_k3s_nodes,Regras de entrada>> para obter mais informações. Se você alterar o CIDR padrão para pods ou serviços, será necessário atualizar as regras de firewall de acordo.

[WARNING]
.Versões mais antigas do RHEL/CentOS
====
As versões do sistema operacional anteriores ao RHEL 8.4 trazem o NetworkManager com um bug conhecido que interfere na rede do K3s. Se estiver usando uma versão mais antiga, é necessário desativar o nm-cloud-setup e reinicializar o nó:

[,bash]
----
systemctl disable nm-cloud-setup.service nm-cloud-setup.timer
reboot
----
====
--

Ubuntu / Debian::
+
--
[#_ubuntu_debian_ufw]
[pass]
<h3><a class="anchor" id="_ubuntu_debian_ufw" href="#_ubuntu_debian_ufw"></a>UFW</h3>

A versão mais antiga do Debian pode sofrer de um bug conhecido do iptables. Consulte xref:known-issues.adoc#_iptables[Problemas conhecidos].

Recomenda-se desativar o ufw (firewall descomplicado):

[,bash]
----
ufw disable
----

Se você deseja manter o ufw ativado, por padrão, as seguintes regras são necessárias:

[,bash]
----
ufw allow 6443/tcp #apiserver
ufw allow from 10.42.0.0/16 to any #pods
ufw allow from 10.43.0.0/16 to any #services
----

Pode ser necessário abrir outras portas, dependendo de sua configuração. Consulte <<_inbound_rules_for_k3s_nodes,Regras de entrada>> para obter mais informações. Se você alterar o CIDR padrão para pods ou serviços, será necessário atualizar as regras de firewall de acordo.
--

[#os_tab_raspberry_pi]
Raspberry Pi::
+
--
O Raspberry Pi OS é baseado no Debian e pode sofrer de um bug conhecido no iptables. Consulte xref:known-issues.adoc#_iptables[Problemas conhecidos].

[#_cgroups]
[pass]
<h3><a class="anchor" id="_cgroups" href="#_cgroups"></a>Grupos C</h3>

As instalações padrão do Raspberry Pi OS não são iniciadas com o `cgroups` ativado. **O K3S** precisa de `cgroups` para iniciar o serviço systemd. `cgroups`pode ser ativado anexando `cgroup_memory=1 cgroup_enable=memory` a `/boot/firmware/cmdline.txt`.

[NOTE]
====
No Debian 11 e em versões anteriores do Pi OS, o cmdline.txt está localizado em `/boot/cmdline.txt`.
====

Exemplo cmdline.txt:

----
console=serial0,115200 console=tty1 root=PARTUUID=58b06195-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait cgroup_memory=1 cgroup_enable=memory
----

[#_ubuntu_vxlan_module]
[pass]
<h3><a class="anchor" id="_ubuntu_vxlan_module" href="#_ubuntu_vxlan_module"></a>Módulo Vxlan do Ubuntu</h3>

Do Ubuntu 21.10 ao Ubuntu 23.10, o suporte a vxlan no Raspberry Pi foi transferido para um módulo separado do kernel. Essa etapa não é necessária no Ubuntu 24.04 e posterior.

[,bash]
----
sudo apt install linux-modules-extra-raspi
----
--
======

Para obter mais informações sobre quais sistemas operacionais foram testados com clusters K3s gerenciados pelo Rancher, consulte os do https://rancher.com/support-maintenance-terms/[termos de suporte e manutenção] Rancher

== Hardware

Os requisitos de hardware são dimensionados de acordo com o tamanho de suas implementações. Os requisitos mínimos são:

|===
| Nó | CPU | RAM

| Servidor
| 2 núcleos
| 2 GB

| Agente
| 1 núcleo
| 512 MB
|===

xref:reference/resource-profiling.adoc[A criação de perfis de recursos] captura os resultados de testes e análises para determinar os requisitos mínimos de recursos para o agente do K3s, o servidor do K3s com uma carga de trabalho e o servidor do K3s com um agente.

=== Discos

O desempenho do K3 depende do desempenho do banco de dados. Para garantir a velocidade ideal, recomendamos o uso de um SSD sempre que possível. 

Se estiver implantando o K3s em um Raspberry Pi ou em outros dispositivos ARM, é recomendável usar um SSD externo. O etcd faz uso intensivo de gravação; os cartões SD e o eMMC não conseguem lidar com a carga de E/S.

=== Guia de dimensionamento de servidores

Quando há limitação de CPU e RAM no nó do servidor (plano de controle + etcd), há limitações na quantidade de nós de agente que podem ser unidos sob condições de carga de trabalho padrão.

|===
| CPU do servidor | RAM do servidor | Número de agentes

| 2
| 4 GB
| 0-350

| 4
| 8 GB
| 351-900

| 8
| 16 GB
| 901-1800

| 16+
| 32 GB
| 1800+
|===

[TIP]
.Dimensionamento de alta disponibilidade
====
Ao usar uma configuração de alta disponibilidade de 3 nós de servidor, o número de agentes pode ser escalonado aproximadamente ~50% a mais do que a tabela acima. Por exemplo, 3 servidores com 4 vCPU/8 GB podem ser dimensionados para ~1200 agentes.
====

Recomenda-se ingressar em nós de agente em lotes de 50 ou menos para permitir que a CPU libere espaço, pois há um pico no ingresso de nós. Lembre-se de modificar o padrão `cluster-cidr` se desejar mais de 255 nós!

xref:reference/resource-profiling.adoc#_server_sizing_requirements_for_k3s[O perfil de recursos] contém mais informações sobre como essas recomendações foram encontradas.

[#_networking]
== Trabalho em rede

O servidor K3s precisa que a porta 6443 seja acessada por todos os nós.

Os nós precisam ser capazes de alcançar outros nós pela porta UDP 8472 ao usar o backend Flannel VXLAN ou pela porta UDP 51820 (e 51821 se for usado IPv6) ao usar o backend Flannel WireGuard. O nó não deve escutar em nenhuma outra porta. O K3s usa o tunelamento reverso, de modo que os nós fazem conexões de saída com o servidor e todo o tráfego do kubelet passa por esse túnel. Entretanto, se você não usar o Flannel e fornecer seu próprio CNI personalizado, as portas necessárias para o Flannel não serão necessárias para o K3s.

Se você deseja utilizar o servidor de métricas, todos os nós devem estar acessíveis uns aos outros na porta 10250.

Se você planeja obter alta disponibilidade com o etcd incorporado, os nós do servidor devem estar acessíveis uns aos outros nas portas 2379 e 2380.

[TIP]
.Importante
====
A porta VXLAN nos nós não deve ser exposta ao mundo, pois ela abre a rede do cluster para ser acessada por qualquer pessoa. Execute seus nós atrás de um firewall/grupo de segurança que desabilite o acesso à porta 8472.
====


[WARNING]
====
O Flannel conta com o https://www.cni.dev/plugins/current/main/bridge/[plug-in] para criar uma rede L2 que alterna o tráfego. Pods desonestos com recursos `NET_RAW` podem abusar dessa rede L2 para lançar ataques como ARP spoofing. Portanto, conforme documentado nos https://kubernetes.io/docs/concepts/security/pod-security-standards/[documentos do], defina um perfil restrito que desabilite o `NET_RAW` em pods não confiáveis.
====

[#_inbound_rules_for_k3s_nodes]
=== Regras de entrada para nós K3s

|===
| Protocolo | Porto | Fonte | Destino | Descrição

| TCP
| 2379-2380
| Servidores
| Servidores
| Necessário apenas para HA com etcd incorporado

| TCP
| 6443
| Agentes
| Servidores
| Supervisor do K3s e servidor de API do Kubernetes

| UDP
| 8472
| Todos os nós
| Todos os nós
| Necessário apenas para Flannel VXLAN

| TCP
| 10250
| Todos os nós
| Todos os nós
| Métricas de Kubelet

| UDP
| 51820
| Todos os nós
| Todos os nós
| Necessário apenas para o Flannel Wireguard com IPv4

| UDP
| 51821
| Todos os nós
| Todos os nós
| Necessário apenas para o Flannel Wireguard com IPv6

| TCP
| 5001
| Todos os nós
| Todos os nós
| Necessário apenas para registro distribuído incorporado (Spegel)

| TCP
| 6443
| Todos os nós
| Todos os nós
| Necessário apenas para registro distribuído incorporado (Spegel)
|===

Normalmente, todo o tráfego de saída é permitido.

Podem ser necessárias alterações adicionais no firewall, dependendo do sistema operacional utilizado.

== Grandes clusters

Os requisitos de hardware são baseados no tamanho do cluster do K3s. Para produção e clusters grandes, recomendamos o uso de uma configuração de alta disponibilidade com um banco de dados externo. As opções a seguir são recomendadas para o banco de dados externo em produção:

* MySQL
* PostgreSQL
* etcd

=== CPU e memória

Veja a seguir os requisitos mínimos de CPU e memória para nós em um servidor K3s de alta disponibilidade:

[cols="^,^,^,^"]
|===
| Tamanho da implantação | Nós | vCPUs | RAM

| Pequeno
| Até 10
| 2
| 4 GB

| Médio
| Até 100
| 4
| 8 GB

| Grande
| Até 250
| 8
| 16 GB

| X-Grande
| Até 500
| 16
| 32 GB

| XX-Large
| 500+
| 32
| 64 GB
|===

=== Discos

O desempenho do cluster depende do desempenho do banco de dados. Para garantir a velocidade ideal, recomendamos sempre usar discos SSD para fazer o backup do cluster do K3s. Nos provedores de nuvem, você também deve usar o tamanho mínimo que permite o máximo de IOPS.

=== Rede

Você deve considerar aumentar o tamanho da sub-rede para o CIDR do cluster para que não fique sem IPs para os pods. Você pode fazer isso passando a opção `--cluster-cidr` para o servidor K3s ao iniciar.

=== Banco de dados

O K3s é compatível com diferentes bancos de dados, incluindo MySQL, PostgreSQL, MariaDB e etcd.  Consulte xref:datastore/datastore.adoc[Cluster Datastore] para obter mais informações.

A seguir, um guia de dimensionamento dos recursos de banco de dados necessários para executar clusters grandes:

[cols="^,^,^,^"]
|===
| Tamanho da implantação | Nós | vCPUs | RAM

| Pequeno
| Até 10
| 1
| 2 GB

| Médio
| Até 100
| 2
| 8 GB

| Grande
| Até 250
| 4
| 16 GB

| X-Grande
| Até 500
| 8
| 32 GB

| XX-Large
| 500+
| 16
| 64 GB
|===
