= SLSA
:revdate: 2025-04-04
:page-revdate: {revdate}

== Vue d'ensemble

https://slsa.dev/spec/v1.0/about[ASLC]L' est un ensemble de lignes directrices pour la sûreté de la chaîne d'approvisionnement qui peuvent être adoptées progressivement et qui ont été établies par consensus au sein de l'industrie. Les spécifications établies par SLSA sont utiles à la fois pour les producteurs de logiciels et pour les consommateurs : les producteurs peuvent suivre les lignes directrices de SLSA pour rendre leur chaîne d'approvisionnement en logiciels plus sûre, et les consommateurs peuvent utiliser SLSA pour décider s'ils doivent faire confiance à un progiciel.

{product_name} répond aux exigences du https://slsa.dev/spec/v1.0/levels[niveau 3 de l'ASL].

|===
| Exigence | Requis à l'ASLC L3 | Rencontré par {product_name}

| Choisir une plateforme de construction appropriée
| Oui
| Oui

| Suivre un processus de construction cohérent
| Oui
| Oui

| Distribuer la provenance
| Oui
| Oui
|===

== Construire une plateforme

* Le projet {product_name} utilise Git pour la gestion du code source.
* Tous les responsables de {product_name} sont tenus d'activer l'authentification à deux facteurs pour signer et approuver toutes leurs contributions.
* Le projet {product_name} utilise GitHub Actions et GitHub Runners pour construire tous ses artefacts de publication.
* Le processus de construction et de publication s'exécute de manière isolée sur un environnement éphémère fourni par des exécutants hébergés par GitHub.

== Processus de construction

* Le processus de construction et de mise à disposition est défini dans le code et conservé sous contrôle de version.
* Les flux de travail GitHub utilisent les actions GitHub associées à certaines versions et sont maintenues à jour grâce à GitHub Dependabot.
* Toutes les modifications apportées au processus de construction et de publication sont effectuées par le biais de Pull Requests qui doivent être approuvées par au moins un mainteneur de {product_name}.
* Le processus de publication ne peut être lancé que par un mainteneur de {product_name} en insérant une étiquette Git au format semver.

== Provenance

* Le projet {product_name} utilise le projet officiel https://github.com/slsa-framework/slsa-github-generator[SLSA GitHub Generator] pour la génération et la distribution de la provenance.
* La provenance des artefacts publiés dans GitHub Container Registry et Rancher Prime Registry est générée en utilisant le workflow GitHub generator_container_slsa3 fourni par le projet https://github.com/slsa-framework/slsa-github-generator[SLSA GitHub Generator].
* La provenance identifie les images du conteneur {product_name} à l'aide de leur résumé au format SHA-256.
* La provenance est signée par Sigstore Cosign à l'aide de l'identité GitHub OIDC, et la clé publique permettant de vérifier la provenance est stockée dans le public https://docs.sigstore.dev/logging/overview/[journal de transparence].
* Le processus de publication et la génération de la provenance sont exécutés de manière isolée sur un environnement éphémère fourni par des exécutants hébergés par GitHub.
* La provenance des images du conteneur {product_name} peut être vérifiée à l'aide de l' officiel https://github.com/slsa-framework/slsa-verifier[outil].
* Les flux de génération de provenance s'exécutent sur des machines virtuelles éphémères et isolées, qui sont entièrement gérées par GitHub.
* Les secrets de signature de la provenance sont éphémères et sont générés par la procédure de signature Sigstore https://github.com/sigstore/cosign/blob/main/KEYLESS.md[sans clé de].
* Le https://github.com/slsa-framework/slsa-github-generator[générateur GitHub] s'exécute sur des machines virtuelles distinctes du processus de construction et de publication, de sorte que les scripts de construction de {product_name} n'ont pas accès aux secrets de signature.

== L'isolement

* Le processus de publication et la génération de la provenance sont exécutés de manière isolée sur un environnement éphémère fourni par des exécutants hébergés par GitHub.
* La génération de la provenance est découplée du processus de construction ; le https://github.com/slsa-framework/slsa-github-generator[générateur GitHub de] fonctionne sur des machines virtuelles distinctes entièrement gérées par GitHub.
* Le processus de validation ne peut pas accéder à la clé de signature de la provenance car le générateur de provenance fonctionne de manière isolée sur des runners distincts hébergés par GitHub.
