= 牧场主设置
:revdate: 2026-02-18
:page-revdate: {revdate}

== 安装 Rancher

_如果您已经在运行 Rancher v2.13 或更高版本，可以跳过本节，直接跳转到 "xref:tutorials/first-cluster.adoc[您的第一个群集"]。_

[NOTE]
====
从 Rancher v2.13 开始，{product_name} 已作为 Rancher 系统图预装。不再需要单独安装{product_name} 。只需安装 Rancher v2.13 或更高版本，即可开始使用集群 API (CAPI)。

====

Helm 是在现有或新 Kubernetes 集群中安装 Rancher 的推荐方法。

ifeval::["{build-type}" == "product"]
[TIP]
====
请务必遵循https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/installation-and-upgrade.html[安装指南] 官方提供的 Rancher。
====
endif::[]
ifeval::["{build-type}" == "community"]
[TIP]
====
请务必遵循https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade[安装指南] 官方提供的 Rancher。
====
endif::[]

下面是使用 Helm 安装 Rancher 的最小示例：

[source,bash]
----
helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --create-namespace \
    --set hostname=<rancher-hostname> \
    --version <rancher-version> \
    --wait
----

将`<rancher-hostname>` 替换为 Rancher 服务器的实际主机名，并使用`--version` 指定`v2.13.0` 或更高版本的 Rancher。

== 安装内容

安装 Rancher v2.13 或更高版本时，{product_name} 会作为系统组件自动部署到`cattle-turtles-system` 命名空间中。这包括

* `rancher-turtles-controller-manager` pod 处理所有与 CAPI 相关的资源
* 核心 CAPI CRD 和核心 CAPI 控制器
* `CAPIProvider` 自定义资源，可声明式定义 CAPI 提供商

[NOTE]
====
核心 CAPI 控制器清单嵌入在配置图中，从而简化了在空气屏蔽环境中的操作。
====

== 安装 CAPI 提供商

{product_name} 嵌入 Rancher 后，默认情况下不再捆绑 CAPI 提供商。提供程序可使用`CAPIProvider` 自定义资源进行声明式管理，另外还有一个单独的提供程序图表，用于安装经认证的提供程序。有关医疗服务提供者列表的更多信息，请参阅 "xref:user/providers.adoc[安装认证医疗服务提供者]"。

例如，定义提供商：

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws
  namespace: cattle-turtles-system
spec:
  type: infrastructure
  name: aws
----

有关配置选项的完整列表，请参阅xref:reference/capiprovider.adoc[CAPIProvider 参考资料]。

现在您可以使用{product_name} ！🎉