= .NET 应用程序
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

== 自动仪器

.NET的自动仪器可自动捕获各种https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/internal/instrumentation-libraries.md[库和框架]的跟踪和指标。

自动仪器不需要对应用程序进行任何修改。设置步骤如下

. 从https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases[Releases]of the opentelemetry-dotnet-instrumentation repository 下载https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/latest/download/opentelemetry-dotnet-instrumentation-linux-glibc.zip[glibc]或https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/latest/download/opentelemetry-dotnet-instrumentation-linux-musl.zip[musl]版本的仪器库（musl 用于 Alpine，glibc 用于大多数其他 docker 镜像）。解压文件，并将其包含在应用程序 docker 镜像的一个目录中，这里我们使用`+/autoinstrumentation+` 。
. 设置以下环境变量，这里我们通过 Kubernetes pod 规范中容器的`+env+` 进行设置：
+
[,yaml]
----
env:
- name: CORECLR_ENABLE_PROFILING
  value: "1"
- name: CORECLR_PROFILER
  value: "{918728DD-259F-4A6A-AC2B-B85E1B658318}"
- name: CORECLR_PROFILER_PATH
  # for glibc:
  value: "/autoinstrumentation/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so"
  # For musl use instead:
  # value: "/autoinstrumentation/linux-musl-x64/OpenTelemetry.AutoInstrumentation.Native.so"
- name: DOTNET_ADDITIONAL_DEPS
  value: "/autoinstrumentation/AdditionalDeps"
- name: DOTNET_SHARED_STORE
  value: "/autoinstrumentation/store"
- name: DOTNET_STARTUP_HOOKS
  value: "/autoinstrumentation/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll"
- name: OTEL_DOTNET_AUTO_HOME
  value: "/autoinstrumentation"
----

. 还可添加额外的环境变量xref:/setup/otel/languages/sdk-exporter-config.adoc[，以配置]pod 上的xref:/setup/otel/languages/sdk-exporter-config.adoc[服务名称和输出端点]。
. 根据更改部署应用程序
. xref:/setup/otel/languages/verify.adoc[验证]SUSE Observability 是否接收跟踪和/或度量信息

详情请参考https://opentelemetry.io/docs/languages/java/automatic/[Open Telemetry 文档]。

== 手动仪表

如果需要自动仪器不支持的代码部分的指标、跟踪或日志，可以使用手动仪器。例如，不支持的库，内部代码或业务级指标。

要获取这些数据，您需要修改您的应用程序。

. 将 Open Telemetry SDK 列入依赖项
. 在应用程序中添加代码，以便在需要时捕获指标、跨度或日志

https://opentelemetry.io/docs/languages/net/instrumentation/[Open Telemetry .NET SDK 文档页面]上有详细的相关文档。

确保使用 OTLP 输出程序（这是默认设置）和https://opentelemetry.io/docs/languages/java/instrumentation/#_autoconfiguration[自动配置]。部署应用程序时，可xref:/setup/otel/languages/sdk-exporter-config.adoc[通过环境变量配置]服务名称和出口程序。

== SUSE Observability 中的度量标准

ifdef::ss-ff-stackpacks2_enabled[]
对于某些 .NET 指标，例如垃圾收集器指标，SUSE Observability 已为相关组件定义了图表。对于 Kubernetes，图表可在 pod 上使用。可以xref:/setup/custom-integrations/metric-bindings/index.adoc[为更多指标添加图表]，这不仅适用于来自自动仪器的指标，也适用于来自手动仪器的特定应用指标。
endif::[]


ifndef::ss-ff-stackpacks2_enabled[]
对于某些 .NET 指标，例如垃圾收集器指标，SUSE Observability 已为相关组件定义了图表。对于 Kubernetes，图表可在 pod 上使用。可以xref:/use/metrics/k8s-add-charts.adoc[为更多指标添加图表]，这不仅适用于来自自动仪器的指标，也适用于来自手动仪器的特定应用指标。
endif::[]

