= 检测 Node.js 应用程序
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

== 自动仪器

Node.js 的自动仪表化是通过在应用程序中包含自动仪表化 Javascript 库来实现的。多种https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node#_supported_instrumentations[支持]。

自动仪器不需要对应用程序进行任何修改。设置步骤如下

. 将 Open Telemetry Instrumentation SDK 添加到您的应用程序中：
+
[,bash]
----
npm install --save @opentelemetry/api
npm install --save @opentelemetry/auto-instrumentations-node
----

. 通过更新 docker 镜像入口点或命令，或者更新应用程序 Kubernetes 清单中的`+command+` ，更新启动应用程序的命令，以加载 SDK。添加`+--require @opentelemetry/auto-instrumentations-node/register+` ：
+
[,bash]
----
node --require @opentelemetry/auto-instrumentations-node/register app.js
----

. 使用额外的环境变量部署应用程序xref:/setup/otel/languages/sdk-exporter-config.adoc[，以配置服务名称和输出端点]。
. xref:/setup/otel/languages/verify.adoc[验证]SUSE Observability 是否接收跟踪和/或度量信息

详情请参考https://opentelemetry.io/docs/languages/js/automatic/[Open Telemetry 文档]。

[CAUTION]
====
在https://github.com/open-telemetry/opentelemetry-js/issues/4551[Open Telemetry 问题]解决之前，通过环境变量配置的自动仪器仅支持跟踪。要启用自动仪器的度量指标，需要修改代码。请按照https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[Open Telemetry 文档]中的说明进行更改。
====


== 手动仪表

如果需要自动仪器不支持的代码部分的指标、跟踪或日志，可以使用手动仪器。例如，不支持的库，内部代码或业务级指标。

要获取这些数据，您需要修改您的应用程序。

. 将 Open Telemetry SDK 列入依赖项
. 在应用程序中添加代码，以便在需要时捕获指标、跨度或日志

https://opentelemetry.io/docs/languages/js/instrumentation/[Open Telemetry Javascript SDK 文档页面]上有详细的相关文档。

确保使用 OTLP 输出程序，并从代码中正确配置输出程序端点。另请参阅https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[Open Telemetry 文档]。假定您按照xref:/setup/otel/collector.adoc[文档说明]设置了出口程序，需要配置的端点是`+http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317+` ，使用 gRPC。如果 gRPC 有问题，请参阅 gRPCxref:/setup/otel/languages/sdk-exporter-config.adoc#_grpc_vs_http[vs HTTP]。
