include::partial$variables.adoc[]
= Problem mit der Rotation von Policy Server-Zertifikaten bei Freigabe ≤ v1.16.0
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Behebung von Problemen bei der Rotation von Policy-Server-Zertifikaten in {project-name}, beginnend mit Version 1.16.
:doc-persona: ["kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["Howto", "Workarounds", "Policy-Server-Zertifikate"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "policy server certificates"]
:sidebar_label: Zertifikat Rotation
:sidebar_position: 10
:current-version: {page-origin-branch}

[IMPORTANT]
.Abhilfe für {project-name} v1.16.0 und früher
====

Dieser Workaround ist nur für {short-project-name} v1.16.0 und früher erforderlich.
Ab v1.17.0 erneuert der Controller automatisch die Policy-Server-Zertifikate.

====

Während des Freigabeprozesses für v1.14 entdeckte {short-project-name} einen Fehler im Zusammenhang mit der Rotation des Policy-Server-Zertifikats. Die Konfiguration der Stammzertifizierungsstelle ist auf 10 Jahre ausgelegt, aber jedes geheime Zertifikat des Richtlinienservers hat eine einjährige Gültigkeitsdauer. Der Controller ist jedoch derzeit nicht in der Lage, diese automatisch zu erneuern.

In der Version v1.14 hat {short-project-name} dafür gesorgt, dass die Geheimnisse des Policy-Servers mit einem Ablaufdatum von 10 Jahren erstellt werden.

Für die Version ≥ v1.16.0 ist ein automatischer Erneuerungsprozess eingerichtet worden.

Bis dahin können die Benutzer das abgelaufene Zertifikatsgeheimnis manuell löschen (policy-server-default) und einen Controller-Abgleich auslösen. Dies geschieht durch Hinzufügen, Entfernen oder Aktualisieren einer Richtlinie oder durch Anpassen der Anzahl der Replikate eines PolicyServers.
