= 资源剖析
:page-languages: [EN, JA, KO, ZH]
:revdate: 2025-01-06
:page-revdate: {revdate}

本节记录了为确定 K3 最低资源要求而进行的测试结果。

== K3 的最低资源要求

结果概述如下

|===
| 组件 | 处理器 | 最小 CPU | 使用 Kine/SQLite 的最小内存 | 嵌入式 etcd 的最小 RAM

| 有工作量的 K3s 服务器
| Intel 8375C CPU, 2.90 GHz
| 6% 的核心
| 1596 M
| 1606 M

| 单个代理的 K3s 集群
| Intel 8375C CPU, 2.90 GHz
| 一个核心的 5
| 1428 M
| 1450 M

| K3s 代理商
| Intel 8375C CPU, 2.90 GHz
| 3% 的核心
| 275 M
| 275 M

| 有工作量的 K3s 服务器
| Pi4B BCM2711, 1.50 GHz
| 核心的 30
| 1588 M
| 1613 M

| 单个代理的 K3s 集群
| Pi4B BCM2711, 1.50 GHz
| 25% 的核心
| 1215 M
| 1413 M

| K3s 代理商
| Pi4B BCM2711, 1.50 GHz
| 核心的 10
| 268 M
| 268 M
|===

=== 资源测试的范围

资源测试旨在解决以下问题：

* 在单节点集群上，假定将在集群上部署实际工作负载，请确定运行整个 K3s 堆栈服务器堆栈所需的 CPU、内存和 IOP 的合法最小值。
* 在代理（工作者）节点上，确定应为 Kubernetes 和 K3s 控制平面组件（kubelet 和 k3s 代理）预留的 CPU、内存和 IOP 的合法最小值。

=== 基线测量包括的组件

测试的组件有

* K3s v1.26.5，已启用所有打包组件
* Prometheus + Grafana 监控栈
* https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[Kubernetes Nginx 部署示例]

这些是仅使用 K3s 打包组件（Traefik Ingress、Klipper lb、本地路径存储）运行标准监控堆栈（Prometheus 和 Grafana）和 Guestbook 示例应用的稳定系统的基准数据。

包括 IOPS 在内的资源数据仅适用于 Kubernetes 数据存储和控制平面，不包括系统级管理代理或日志记录、容器映像管理或任何特定工作负载要求的开销。

=== 方法

通过 apt 安装的`prometheus-node-exporter` ，使用 Prometheus v2.43.0 独立实例收集主机 CPU、内存和磁盘 IO 统计数据。

`systemd-cgtop` 用于抽查 systemd cgroup 级 CPU 和内存利用率。`system.slice/k3s.service` 跟踪 K3 和 containerd 的资源利用率，而单个 pod 处于`kubepods` 层次结构之下。

其他详细的 K3s 内存利用率数据是使用服务器和代理进程的集成指标服务器从`kubectl top node` 收集的。

利用率数据基于运行所述工作负载的节点上稳定运行时的第 95 百分位数读数。

=== 环境

|===
| 拱门 | OS | 系统 | CPU | RAM | 磁盘

| x86_64
| Ubuntu 22.04
| AWS c6id.xlarge
| 英特尔至强铂金 8375C CPU，4 核 2.90 GHz
| 8 GB
| NVME SSD

| aarch64
| Raspberry Pi OS 11
| 树莓派 4 B 型
| BCM2711，4 核 1.50 GHz
| 8 GB
| UHS-III SDXC
|===

=== 基准资源需求

本节记录了为确定 K3s 基本运行的最低资源要求而进行的测试结果。

==== 带工作负载的 K3s 服务器

这些是单节点集群的要求，其中 K3s 服务器与https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[简单工作负载]共享资源。

对 CPU 的要求是

|===
| 系统 | CPU 核心使用率

| 英特尔 8375C
| 6% 的核心

| Pi4B
| 核心的 30
|===

内存要求为

|===
| 测试过的数据存储 | 系统 | 内存

| Kine/SQLite
| 英特尔 8375C
| 1596 M

|
| Pi4B
| 1588 M

| 嵌入式 etcd
| 英特尔 8375C
| 1606 M

|
| Pi4B
| 1613 M
|===

磁盘要求如下

|===
| 测试过的数据存储 | IOPS | KiB/sec | 延迟

| Kine/SQLite
| 10
| 500
| < 10 ms

| 嵌入式 etcd
| 50
| 250
| < 5 ms
|===

==== 使用单个代理的 K3s 集群

这些是 K3s 集群的基本要求，其中有一个 K3s 服务器节点和一个 K3s 代理，但没有工作负载。

===== K3s 服务器

对 CPU 的要求是

|===
| 系统 | CPU 核心使用率

| 英特尔 8375C
| 一个核心的 5

| Pi4B
| 25% 的核心
|===

内存要求为

|===
| 测试过的数据存储 | 系统 | 内存

| Kine/SQLite
| 英特尔 8375C
| 1428 M

|
| Pi4B
| 1215 M

| 嵌入式 etcd
| 英特尔 8375C
| 1450 M

|
| Pi4B
| 1413 M
|===

===== K3s 代理

要求如下

|===
| 系统 | CPU 核心使用率 | RAM

| 英特尔 8375C
| 3% 的核心
| 275 M

| Pi4B
| 一个核心的 5
| 268 M
|===

=== 主要资源利用驱动因素分析

K3 的服务器利用率主要受 Kubernetes 数据存储（kine 或 etcd）、API 服务器、控制器管理器和调度器控制环路的支持，以及对系统状态进行更改所需的任何管理任务的驱动。给 Kubernetes 控制平面带来额外负载的操作（如创建/修改/删除资源）会导致利用率出现暂时性峰值。使用大量使用 Kubernetes 数据存储的操作员或应用程序（如 Rancher 或其他操作员类型的应用程序）会增加服务器的资源需求。通过添加更多节点或创建更多群集资源来扩展群集，会增加服务器的资源需求。

K3 的代理利用率数字主要由支持容器生命周期管理控制循环驱动。涉及管理映像、调配存储或创建/销毁容器的操作会导致利用率暂时激增。尤其是图像拉取，由于需要将图像内容解压到磁盘，因此通常需要大量 CPU 和 IO 资源。如果可能，工作负载存储（pod 临时存储和卷）应与代理组件（/var/lib/rancher/k3s/agent）隔离，以确保不发生资源冲突。

=== 防止代理和工作负载干扰群集数据存储

在服务器同时托管工作负载 pod 的环境中运行时，应注意确保代理和工作负载的 IOPS 不会干扰数据存储。

最好的办法是将服务器组件（/var/lib/rancher/k3s/server）放在与代理组件（/var/lib/rancher/k3s/agent）不同的存储介质上，后者包括 containerd 映像存储。

工作负载存储（pod 临时存储和卷）也应与数据存储隔离。

无法满足数据存储吞吐量和延迟要求可能会导致控制平面响应延迟和/或控制平面无法维持系统状态。

[#_server_sizing_requirements_for_k3s]
== K3 服务器规模要求

=== 环境

* 所有代理都是 t3.medium AWS ec2 实例。
** 单个代理是一个 c5.4xlarge 实例。这就托管了 grafana 监控栈，防止其干扰控制平面资源。
* 服务器是一个 c5 AWS ec2 实例。随着代理数量的增加，服务器升级为更大的 c5 实例。

=== 方法

这些数据是在特定测试条件下获取的。这取决于环境和工作量。下面的步骤概述了为检索此信息而进行的测试。最后一次执行是在 v1.31.0+k3s1 上。所有机器都在 AWS 中配置了标准的 20 GiB gp3 卷。测试的步骤如下

. 使用 prometheus 数据源监控 grafana 上的资源。
. 以模拟群集连续活动的方式部署工作负载：
** 持续增减的基本工作量
** 在循环中删除和重新创建的工作量
** 包含多个其他资源（包括 CRD）的恒定工作量。
. 分批加入代理节点，每次 50-100 个。
. 当代理加入时服务器 CPU 使用率超过 90% 或内存使用率超过 80% 时，停止添加代理。

=== 意见

* 加入代理时，服务器 CPU 会比基线高出约 20%。
* 通常，限制因素是 CPU，而不是内存。在大多数测试中，当 CPU 使用率达到 90% 时，内存使用率约为 60%。

==== 关于高可用性（HA）的说明

每次测试结束后，都会再加入两台服务器（形成一个基本的 3 节点 HA 集群），以观察这对原有服务器资源的影响。效果是

* CPU 使用率明显下降，通常为 30-50%。
* 内存使用率保持不变。

虽然没有进行测试，但由于 CPU 利用率是单台服务器的限制因素，预计在 3 节点 HA 集群中，可加入的代理数量将增加约 50%。
