= Guide de migration
:revdate: 2025-11-14
:page-revdate: {revdate}

== Context

Depuis Rancher v2.13, {product_name} est installé dans le cadre de Rancher, ce qui élimine le besoin d'un déploiement séparé. Avant de passer à la version 2.13 de Rancher, les utilisateurs doivent suivre ce guide pour garantir un processus de mise à niveau sans heurts.

== Migration

Suivez les étapes ci-dessous dans l'ordre, _avant de_ mettre à jour vers Rancher v2.13 :

. Veillez à mettre à jour {product_name} vers la version 0.24.3. Cette étape est importante car tous les correctifs de la v0.24 préparent le cluster à la mise à niveau vers Rancher v2.13.
. Désinstaller {product_name}. Ceci est nécessaire car à partir de Rancher v2.13, {product_name} n'est plus un addon opt-in mais un composant du système Rancher. En tant que tel, Rancher l'installe dans un espace de noms différent qu'auparavant et la version précédemment installée doit donc d'abord être désinstallée manuellement. La désinstallation de la version 0.24.3 de {product_name} supprime le fournisseur principal de l'ICPA, mais conserve les CRD de l'ICPA. Pendant la migration, le contrôleur CAPI principal ne fonctionnera pas sur le cluster de gestion, mais tous les clusters CAPI en aval devraient continuer à fonctionner comme d'habitude et ne pas être affectés.
. Exécutez les commandes kubectl suivantes :
+
[source,bash]
----
kubectl patch crd capiproviders.turtles-capi.cattle.io --type=json -p='[{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "cattle-turtles-system"}]'
kubectl patch crd clusterctlconfigs.turtles-capi.cattle.io --type=json -p='[{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "cattle-turtles-system"}]'
----

Ces commandes corrigeront les CRDs `capiprovider` et `clusterctlconfig` afin qu'ils soient adoptés par {product_name} lorsqu'ils seront installés dans le cadre de Rancher v2.13. 

Notez que la migration décrite ci-dessus est nécessaire pour les utilisateurs des versions {product_name} &le; v0.24.3. Les nouveaux utilisateurs qui installent Rancher v2.13 n'ont pas besoin d'effectuer de migration.