= Rancher Setup
:revdate: 2026-02-18
:page-revdate: {revdate}

== Installation de Rancher

_Si vous utilisez déjà Rancher v2.13 ou une version ultérieure, vous pouvez sauter cette section et passer à xref:tutorials/first-cluster.adoc[Votre premier cluster.]_

[NOTE]
====
Depuis Rancher v2.13, {product_name} est pré-installé en tant que carte système de Rancher. Il n'est plus nécessaire d'installer {product_name} séparément. Il suffit d'installer Rancher v2.13 ou une version ultérieure pour commencer à utiliser l'API Cluster (CAPI).

====

Helm est le moyen recommandé pour installer Rancher dans un cluster Kubernetes existant ou nouveau.

ifeval::["{build-type}" == "product"]
[TIP]
====
Veillez à suivre l'un des officiels https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/installation-and-upgrade.html[guides d'installation] pour Rancher.
====
endif::[]
ifeval::["{build-type}" == "community"]
[TIP]
====
Veillez à suivre l'un des officiels https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade[guides d'installation] pour Rancher.
====
endif::[]

Voici un exemple minimal d'installation de Rancher avec Helm :

[source,bash]
----
helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --create-namespace \
    --set hostname=<rancher-hostname> \
    --version <rancher-version> \
    --wait
----

Remplacez `<rancher-hostname>` par le nom d'hôte réel de votre serveur Rancher et utilisez `--version` pour spécifier une version de Rancher de `v2.13.0` ou ultérieure.

== Ce qui est installé

Lorsque Rancher v2.13 ou une version ultérieure est installé, {product_name} est automatiquement déployé en tant que composant système dans l'espace de noms `cattle-turtles-system`. Il s'agit notamment de

* Le pod `rancher-turtles-controller-manager`, qui gère toutes les ressources liées à l'interface CAPI
* Les CRD de l'ICPA de base et le contrôleur de l'ICPA de base
* La ressource personnalisée `CAPIProvider`, qui permet la définition déclarative des fournisseurs CAPI.

[NOTE]
====
Le manifeste principal du contrôleur CAPI est intégré dans un ConfigMap, ce qui simplifie le fonctionnement dans les environnements à air comprimé.
====

== Installation des fournisseurs CAPI

Avec {product_name} intégré à Rancher, les fournisseurs CAPI ne sont plus intégrés par défaut. Les fournisseurs sont gérés de manière déclarative à l'aide de la ressource personnalisée `CAPIProvider`, et un tableau des fournisseurs distinct est disponible pour l'installation des fournisseurs certifiés. Pour plus d'informations sur le tableau des fournisseurs, voir xref:user/providers.adoc[Installer des fournisseurs certifiés].

Par exemple, pour définir un fournisseur :

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws
  namespace: cattle-turtles-system
spec:
  type: infrastructure
  name: aws
----

Reportez-vous à la xref:reference/capiprovider.adoc[référence CAPIProvider] pour obtenir la liste complète des options de configuration.

Vous êtes maintenant prêt à utiliser {product_name}! 🎉