= 非推奨フラグ
:page-languages: [en、ja、ko、zh]。
:revdate: 2024-09-09
:page-revdate: {revdate}

K3sは動きの速いプロジェクトなので、フラグや設定オプションを非推奨にする方法が必要です。このページでは、非推奨フラグとコンフィギュレーション・オプションの廃止プロセスの概要を説明する。フラグの削除によってユーザーが驚かないようにするため、https://kubernetes.io/docs/reference/using-api/deprecation-policy/[] Kubernetes同様のプロセスを採用している。

== プロセス

. フラグはいつでも「非推奨」と宣言できる。
. 非推奨」とされたフラグは、現在サポートされているすべてのリリースの次のパッチで、そのように表示されなければならない。さらに、このフラグは次のマイナーリリースで非推奨となることをユーザーに警告するようになる。
. 次のマイナーリリースでは、フラグはドキュメントで非推奨とマークされ、コードでは隠しフラグに変換される。フラッグは引き続き作動し、ユーザーに警告を与える。
. 以下のマイナー・リリース・ブランチでは、非推奨フラグは「動作不能」となり、使用すると致命的なエラーとなる。このエラーは、このフラグに代わる新しいフラグやコンフィギュレーションをユーザーに説明しなければならない。
. 次のマイナーリリースでは、操作不能なフラグはドキュメントとコードから削除される。

== 例

プロセスの一例：

* `+--foo+` はv1.22.14、v1.23.10、v1.24.2に存在する。
* v1.24.2リリース後、`+--foo+` を廃止し、`+--new-foo+` を採用することに決定した。
* v1.22.15、v1.23.11、v1.24.3では、`+--foo+` は存在し続けますが、ユーザーに警告を表示します：
+
----
[Warning] --foo will be deprecated in v1.25.0, use `+--new-foo+` instead
----
+
`+--foo+` は、v1.22、v1.23、v1.24の存続期間中、運用フラグとして存在し続ける。

* v1.25.0では、`+--foo+` はドキュメントでは非推奨とされ、コードでは非表示になります。引き続き動作し、`+--new-foo+` に移行するようユーザーに警告する。
* v1.26.0では、`+--foo+` を使用すると致命的なエラーが発生します。エラーメッセージにはこう書かれている：
+
----
[Fatal] exit 1: --foo is no longer supported, use --new-foo instead
----

* v1.27.0では、すべてのコードとドキュメントから`+--foo+` 。
