= 資源プロファイリング
:page-languages: [en、ja、ko、zh]。
:revdate: 2025-01-06
:page-revdate: {revdate}

このセクションでは、K3の最小リソース要件を決定するためのテスト結果をキャプチャする。

== K3の最低必要リソース

結果は以下のように要約される：

|===
| コンポーネント | プロセッサー | 最小CPU | Kine/SQLiteで最小RAM | 組み込みetcdの最小RAM

| K3sサーバーとワークロード
| インテル8375C CPU、2.90 GHz
| コアの6
| 1596 M
| 1606 M

| シングルエージェントのK3sクラスタ
| インテル8375C CPU、2.90 GHz
| コアの5
| 1428 M
| 1450 M

| K3sエージェント
| インテル8375C CPU、2.90 GHz
| コアの3
| 275 M
| 275 M

| K3sサーバーとワークロード
| Pi4B BCM2711、1.50 GHz
| コアの30
| 1588 M
| 1613 M

| シングルエージェントのK3sクラスタ
| Pi4B BCM2711、1.50 GHz
| コアの25
| 1215 M
| 1413 M

| K3sエージェント
| Pi4B BCM2711、1.50 GHz
| コアの10
| 268 M
| 268 M
|===

=== 資源テストの範囲

リソーステストは、以下の問題意識を解決するためのものである：

* シングルノードクラスタ上で、実際のワークロードがクラスタ上に展開されると仮定して、K3sスタックサーバスタック全体を実行するために確保すべきCPU、メモリ、およびIOPの正当な最小量を決定します。
* エージェント（ワーカー）ノード上で、KubernetesとK3sのコントロールプレーンコンポーネント（kubeletとk3sエージェント）のために確保すべき、CPU、メモリ、IOPの正当な最小量を決定する。

=== ベースライン測定に含まれるコンポーネント

テストされたコンポーネントは以下の通り：

* K3s v1.26.5、すべてのパッケージ化されたコンポーネントを有効にする
* Prometheus + Grafanaモニタリングスタック
* https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[Kubernetes Nginxデプロイの例]

これらは、K3sのパッケージコンポーネント（Traefik Ingress、Klipper lb、ローカルパスストレージ）のみを使用し、標準的なモニタリングスタック（PrometheusとGrafana）とGuestbookのサンプルアプリを実行した安定したシステムのベースライン値です。

IOPSを含むリソース数値は、Kubernetesデータストアとコントロールプレーンのみのものであり、システムレベルの管理エージェントやロギング、コンテナイメージ管理、またはワークロード固有の要件のオーバーヘッドは含まれていません。

=== 方法論

プロメテウスv2.43.0のスタンドアロン・インスタンスを使用して、apt経由でインストールした`+prometheus-node-exporter+` 、ホストのCPU、メモリ、ディスクIO統計を収集した。

`+systemd-cgtop+` `+system.slice/k3s.service+` 、K3とcontainerdの両方のリソース使用率を追跡するが、個々のポッドは`+kubepods+` 階層の下にある。

追加の詳細なK3sメモリ使用率データは、サーバーとエージェントプロセスの統合されたメトリックスサーバーを使用して、`+kubectl top node+` 。

利用率の数値は、記述されたワークロードを実行するノードの定常動作から得られた95パーセンタイルの測定値に基づいている。

=== 環境

|===
| アーチ | OS | システム | CPU | RAM | ディスク

| x86_64
| Ubuntu 22.04
| AWS c6id.xlarge
| インテル Xeon Platinum 8375C CPU、4コア 2.90 GHz
| 8 GB
| NVME SSD

| aarch64
| ラズベリーパイOS 11
| ラズベリーパイ4モデルB
| BCM2711、4コア1.50 GHz
| 8 GB
| UHS-III SDXC
|===

=== ベースライン・リソース要件

このセクションでは、K3sの基本的な動作に必要な最小限のリソースを決定するためのテスト結果をキャプチャする。

==== K3sサーバーとワークロード

これらは、K3sサーバーがhttps://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[シンプルなワークロードと]リソースを共有するシングルノードクラスターの要件です。

CPU要件は以下の通り：

|===
| システム | CPUコア使用率

| インテル8375C
| コアの6

| Pi4B
| コアの30
|===

メモリ要件は以下の通り：

|===
| テスト済みデータストア | システム | メモリー

| Kine/SQLite
| インテル8375C
| 1596 M

|
| Pi4B
| 1588 M

| 組み込みetcd
| インテル8375C
| 1606 M

|
| Pi4B
| 1613 M
|===

ディスクの条件は以下の通り：

|===
| テスト済みデータストア | IOPS | キロバイト／秒 | レイテンシー

| Kine/SQLite
| 10
| 500
| < 10 ms

| 組み込みetcd
| 50
| 250
| < 5 ms
|===

==== 単一エージェントによるK3sクラスタ

これらは、K3sサーバノードとK3sエージェントを持つK3sクラスタのベースライン要件ですが、ワークロードはありません。

===== K3sサーバー

CPU要件は以下の通り：

|===
| システム | CPUコア使用率

| インテル8375C
| コアの5

| Pi4B
| コアの25
|===

メモリ要件は以下の通り：

|===
| テスト済みデータストア | システム | メモリー

| Kine/SQLite
| インテル8375C
| 1428 M

|
| Pi4B
| 1215 M

| 組み込みetcd
| インテル8375C
| 1450 M

|
| Pi4B
| 1413 M
|===

===== K3sエージェント

その条件とは

|===
| システム | CPUコア使用率 | RAM

| インテル8375C
| コアの3
| 275 M

| Pi4B
| コアの5
| 268 M
|===

=== 主要資源利用ドライバーの分析

K3のサーバー使用率の数値は、主にKubernetesデータストア（kineまたはetcd）、APIサーバー、コントローラー・マネージャー、スケジューラーの制御ループ、およびシステムの状態に変更を加えるために必要な管理タスクのサポートによって駆動されます。リソースの作成／変更／削除など、Kubernetesのコントロールプレーンに追加的な負荷をかける操作は、利用率の一時的なスパイクを引き起こす。Kubernetesデータストアを広範囲に使用するオペレーターやアプリ（Rancherやその他のオペレータータイプのアプリケーションなど）を使用すると、サーバーのリソース要件が増加します。ノードを追加したり、多くのクラスタ・リソースを作成したりしてクラスタをスケールアップすると、サーバーのリソース要件が増加します。

K3のエージェント利用率は、主にコンテナのライフサイクル管理制御ループのサポートによってもたらされている。イメージの管理、ストレージのプロビジョニング、コンテナの作成/破棄を伴う操作は、一時的に使用率が急上昇する。特に画像プルは、画像コンテンツをディスクに展開するため、一般的にCPUとIOの負荷が高い。可能であれば、ワークロードストレージ（ポッドエフェメラルストレージおよびボリューム）は、リソースの競合がないように、エージェントコンポーネント（/var/lib/rancher/k3s/agent）から分離されるべきである。

=== エージェントとワークロードがクラスター・データストアに干渉するのを防ぐ

サーバーがワークロードポッドもホストしている環境で実行する場合は、エージェントとワークロードのIOPSがデータストアに干渉しないように注意する必要があります。

これは、サーバーコンポーネント（/var/lib/rancher/k3s/server）を、containerdイメージストアを含むエージェントコンポーネント（/var/lib/rancher/k3s/agent）とは異なる記憶媒体に配置することで実現できる。

ワークロードストレージ（ポッドエフェメラルストレージやボリューム）もデータストアから分離すべきである。

データストアのスループットとレイテンシの要件を満たせない場合、コントロールプレーンからの応答が遅れたり、コントロールプレーンがシステム状態を維持できなかったりする可能性がある。

[#_server_sizing_requirements_for_k3s]
== K3のサーバサイジング要件

=== 環境

* エージェントはすべてt3.mediumのAWS ec2インスタンスである。
** 1人のエージェントがc5.4xlargeのインスタンスだった。これはgrafanaモニタリングスタックをホストし、制御プレーンリソースに干渉しないようにする。
* サーバーはc5のAWS ec2インスタンス。エージェントの数が増えるにつれて、サーバーはより大きなc5インスタンスにアップグレードされた。

=== 方法論

このデータは特定のテスト条件下で取得されたものである。環境やワークロードによって異なる。以下のステップは、この結果を得るために実行されたテストの概要である。最終確認はv1.31.0+k3s1で行われた。すべてのマシンは、標準的な20ギガバイトのgp3ボリュームでAWSにプロビジョニングされた。テストは以下の手順で行われた：

. prometheusデータソースを使ってgrafanaでリソースを監視する。
. クラスタの継続的な活動をシミュレートするようにワークロードをデプロイする：
** 連続的に増減する基本的なワークロード
** ループの中で削除され、再作成される作業負荷
** CRDを含む他の複数のリソースを含む一定のワークロード。
. 一度に50-100のバッチでエージェントノードに参加する。
. エージェント参加時にサーバ CPU の使用率が 90% を超えた場合、または RAM の使用率が 80% を超えた場合、エージェントの追加を停止します。

=== 観察

* エージェントに参加すると、サーバーのCPUがベースラインより20%程度上昇した。
* 通常、制限要因はRAMではなくCPUだった。ほとんどのテストでは、CPUの使用率が90％に達したとき、RAMの使用率は60％程度だった。

==== 高可用性（HA）に関する注意事項

各テストの最後に、2台のサーバーを追加して（基本的な3ノードHAクラスターを形成）、元のサーバーリソースにどのような影響があるかを観察した。効果はあった：

* CPU使用率が顕著に低下し、通常は30～50％低下する。
* RAMの使用率は変わらなかった。

テストはしていないが、CPU使用率が1台のサーバーの制限要因であることから、3ノードのHAクラスタでは、参加可能なエージェント数が〜50%増加すると予想される。
