= Segredos externos
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Segredos externos do SUSE Observability

== Visão geral

O SUSE Observability pode obter segredos como chave de licença, chave de API e chaves de autenticação por meio da instalação do helm, mas também pode obtê-los de segredos já provisionados.

Aqui está descrito como configurar isso.

== Obtendo a chave de licença de um segredo externo

Crie um segredo no namespace em que o SUSE Observability está instalado, com o seguinte formato, preenchendo os espaços em branco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

Adicione o seguinte ao comando de instalação do helm para usar o segredo:

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== Obtenção de nome de usuário e senha para notificações por e-mail de um segredo externo

Crie um segredo no namespace em que o SUSE Observability está instalado, com o seguinte formato, preenchendo os espaços em branco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

Adicione o seguinte ao comando de instalação do helm para usar o segredo:

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== Obtendo a chave da API de um segredo externo

Crie um segredo no namespace em que o SUSE Observability está instalado, com o seguinte formato, preenchendo os espaços em branco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

Adicione o seguinte ao comando de instalação do helm para usar o segredo:

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== Obtenção de dados de autenticação de um segredo externo

Crie um segredo no namespace em que o SUSE Observability está instalado, com o seguinte formato.

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

Dependendo do método de autenticação escolhido, o campo `+default_password+` é substituído por dados diferentes. Consulte as xref:/setup/security/authentication/authentication_options.adoc[opções de autenticação] para obter mais informações. Neste exemplo, é usada a configuração de xref:/setup/security/authentication/single_password.adoc[senha única].

Adicione o seguinte ao comando de instalação do helm para usar o segredo:

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
