include::partial$variables.adoc[]
= O que é {project-name}?
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Saiba mais sobre a função do {project-name} no gerenciamento de políticas do Kubernetes, que inclui a aplicação da conformidade e a otimização de recursos.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["introduction"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "cncf", "cncf sandbox", "kubernetes", "admission policy manager"]
:sidebar_label: Introdução
:sidebar_position: 1
:slug: /
:current-version: {page-origin-branch}

{project-name} é um mecanismo de política do Kubernetes.
Seu objetivo é ser o mecanismo de política universal para o Kubernetes.

{intro-paragraph}

== Como o site {project-name} ajuda?

{short-project-name} oferece flexibilidade para admissão e aplicação de políticas em um ambiente Kubernetes.

=== Benefícios e valor

- Use qualquer linguagem de programação que gere binários https://webassembly.org[do] para escrever suas políticas.
- O WebAssembly permite a compatibilidade de políticas entre processadores e sistemas operacionais.
- Reutilização de políticas de outros mecanismos de políticas sem a necessidade de reescrevê-las.
- Distribua políticas usando mecanismos padrão e seguros, como os registros compatíveis com https://opencontainers.org[] OCI.
- A aplicação de políticas na admissão garante que somente as cargas de trabalho em conformidade sejam executadas.
- O scanner de auditoria {short-project-name} verifica ativa e continuamente a aplicação da política ao longo do tempo.
- Verifique as políticas usando as ferramentas e práticas do https://slsa.dev[SLSA] (Supply Chain Levels for Software Artifacts).
- {project-name} oferece uma abordagem abrangente para o gerenciamento de políticas de admissão.
- A associação ao CNCF e uma crescente comunidade e ecossistema de código aberto ajudam o {short-project-name} com transparência, colaboração e aprimoramento.

=== Casos de uso

- Fortalecimento da segurança. Por exemplo, aplique políticas que restrinjam privilégios de contêineres, aplique políticas de rede ou bloqueie registros de imagens inseguros.
- Auditoria de conformidade. Garantir que as cargas de trabalho estejam em conformidade com os padrões e as práticas recomendadas organizacionais ou regulamentares.
- Otimização de recursos. Aplicar limites e cotas de recursos.

Há mais documentação sobre casos de uso na página de xref:use-cases.adoc[casos de uso].

== Novo no site {short-project-name}?

Se você for novo no projeto {short-project-name}, comece com o xref:quick-start.adoc[guia de início rápido] e a página de xref:explanations/architecture.adoc[arquitetura].
Depois, depende de onde seus interesses o levarem. Para os desenvolvedores de políticas, há seções específicas de idiomas nos tutoriais. Para integradores e administradores, há uma seção de "instruções". A seção de explicações contém material de apoio útil. Há também um xref:glossary.adoc[glossário].

== O que é o WebAssembly?

Conforme declarado no https://webassembly.org/[site oficial do]:

____
O WebAssembly (abreviado como Wasm) é um formato de instrução binária para uma máquina virtual baseada em pilha. O Wasm foi projetado como um alvo de compilação portátil para linguagens de programação, permitindo a implantação na Web de aplicativos de cliente e servidor.
____

O Wasm foi originalmente concebido como uma "extensão" do navegador. No entanto, a comunidade do WebAssembly está empenhada em permitir a execução do código Wasm fora dos navegadores.

== Por que usar o WebAssembly?

Os usuários podem escrever políticas do Kubernetes usando sua linguagem de programação favorita, desde que sua cadeia de ferramentas possa gerar binários Wasm.

Os módulos Wasm são portáteis e, uma vez construídos, podem ser executados em qualquer tipo de arquitetura de processador e sistema operacional. Por exemplo, uma política desenvolvida e construída no Apple Silicon pode ser executada no AMD64/Intel64 Linux sem conversão.

Os autores de políticas podem reutilizar suas habilidades, ferramentas e práticas recomendadas. As políticas são programas "tradicionais" que podem ter blocos reutilizáveis (bibliotecas regulares). Você pode fazer lint e testá-los e conectá-los aos fluxos de trabalho atuais de CI e CD.

== Distribuição de políticas

Você pode servir as políticas do {short-project-name} usando um servidor da Web padrão ou, melhor ainda, pode publicá-las em um registro compatível com OCI como dohttps://github.com/opencontainers/artifacts[artefatos] OCI.

ifeval::["{build-type}" == "community"]

== Neutralidade do fornecedor

{short-project-name} é um projeto \link:https://contribute.cncf.io/maintainers/community/vendor-neutrality/[vendor neutral] conforme definido pelo CNCF.

endif::[]
