= Colector de telemetría abierto
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

OpenTelemetry Collector ofrece una implementación independiente del proveedor para recibir, procesar y exportar datos de telemetría. Las aplicaciones instrumentadas con Open Telemetry SDK pueden utilizar el recopilador para enviar datos de telemetría a SUSE Observability (trazas y métricas).

Sus aplicaciones, una vez configuradas con los SDK de OpenTelemetry, pueden utilizar el recopilador para enviar datos de telemetría, como trazas y métricas, a SUSE Observability o a otro recopilador (para su posterior procesamiento). El colector está configurado para recibir estos datos por defecto a través de OTLP, el protocolo nativo de telemetría abierta. También puede recibir datos en otros formatos proporcionados por otros SDK de instrumentación como Jaeger y Zipkin para trazas, e Influx y Prometheus para métricas.

El recopilador se ejecuta cerca de su aplicación, en el mismo clúster de Kubernetes, en la misma máquina virtual, etc. Esto permite a los SDK descargar rápidamente los datos al recopilador, que a su vez puede realizar transformaciones, agrupaciones por lotes y filtrado. Puede ser utilizado por múltiples aplicaciones y permite realizar cambios fácilmente en su canal de procesamiento de datos.

Para las guías de instalación, utilice las diferentes xref:/setup/otel/getting-started/README.adoc[guías de inicio]. Las guías de introducción proporcionan una configuración básica del recopilador para comenzar, pero con el tiempo querrá personalizarla según sus necesidades y agregar receptores, procesadores y exportadores adicionales para personalizar su canal de ingesta según sus necesidades.

== Configuración

La configuración del colector define los conductos para procesar las distintas señales de telemetría. Los componentes de la cadena de procesamiento pueden dividirse en varias categorías, y cada componente tiene su propia configuración. A continuación le ofrecemos una visión general de las distintas secciones de configuración y de cómo utilizarlas.

=== Receptores

Los receptores aceptan datos telemétricos de aplicaciones instrumentadas, aquí a través de OTLP:

[,yaml]
----
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
----

Hay muchos más receptores que aceptan datos a través de otros protocolos, por ejemplo las trazas Zipkin, o que recogen activamente datos de diversas fuentes, por ejemplo:

* Métricas de host
* Métricas de Kubernetes
* Métricas Prometheus (OpenMetrics)
* Bases de datos

Algunos receptores admiten las 3 señales (trazas, métricas, registros), otros sólo admiten 1 o 2, por ejemplo el receptor Prometheus sólo puede recoger métricas. El repositorio opentelemetry-collector-contrib tiene https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver[todos los receptores] con documentación sobre su configuración.

=== Procesadores

Los datos de los receptores pueden ser transformados o filtrados por procesadores.

[,yaml]
----
processors:
  batch: {}
----

El procesador por lotes agrupa las 3 señales, lo que mejora la compresión y reduce el número de conexiones salientes. El repositorio opentelemetry-collector-contrib tiene https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[todos los procesadores] con documentación sobre su configuración.

=== Exportadores

Para enviar datos al backend de SUSE Observability, el recopilador dispone de exportadores. Existen exportadores para diferentes protocolos, basados en push o pull, y diferentes backends. Mediante los protocolos OTLP también es posible utilizar otro colector como destino para un procesamiento adicional.

[,yaml]
----
exporters:
  # The gRPC otlp exporter
  otlp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp endpoint
    endpoint: <otlp-suse-observability-endpoint>
    # Use snappy compression, if no compression specified the data will be uncompressed
    compression: snappy
----

El exportador de SUSE Observability requiere autenticación utilizando una clave api, para configurar que se utilice una <<_extensions,extensión de autenticación>>. El repositorio opentelemetry-collector-contrib tiene https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter[todos los exportadores] con documentación sobre su configuración.

Si el exportador gRPC no le funciona (véase también la xref:/setup/otel/troubleshooting.adoc#_some_proxies_and_firewalls_dont_work_well_with_grpc[resolución de problemas]), puede cambiar al protocolo OTLP sobre HTTP, ligeramente menos eficiente, utilizando en su lugar el exportador `otlphttp`. Sustituya todas las referencias a `otlp/suse-observability` en la sección `pipelines` y `exporter` por `otlphttp/suse-observability` y asegúrese de actualizar la configuración del exportador a:

[,yaml]
----
exporters:
  # The gRPC otlp exporter
  otlphttp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp HTTP endpoint
    endpoint: <otlp-http-suse-observability-endpoint>
    # Use snappy compression, if no compression specified the data will be uncompressed
    compression: snappy
----

[CAUTION]
====
El punto final HTTP OTLP para SUSE Observability es diferente del punto final OTLP. Utilice xref:/setup/otel/otlp-apis.adoc[las API OTLP] para encontrar la URL correcta.
====


=== Servicio de tuberías

Para cada señal de telemetría se configura una canalización independiente. Las canalizaciones se configuran en la sección `service.pipeline` y definen qué receptores, procesadores y exportadores deben utilizarse y en qué orden. Antes de utilizar un componente en la canalización, primero debe definirse en su sección de configuración. El procesador `batch`, por ejemplo, no tiene ninguna configuración, pero debe declararse en la sección `processors`. Los componentes configurados pero no incluidos en una canalización no estarán activos en absoluto.

[,yaml]
----
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, spanmetrics, otlp/suse-observability]
    metrics:
      receivers: [otlp, spanmetrics, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlp/suse-observability]
----

=== Extensiones

Las extensiones no se utilizan directamente en las cadenas de procesamiento de datos, sino que amplían las capacidades del recopilador de otras formas. Para SUSE Observability se utiliza para configurar la autenticación utilizando una clave api. Las extensiones deben definirse en una sección de configuración antes de que puedan utilizarse. Al igual que en el caso de los componentes de canalización, una extensión sólo está activa cuando está activada en la sección `service.extensions`.

[,yaml]
----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
service:
  extensions: [ bearertokenauth ]
----

El repositorio opentelemetry-collector-contrib tiene https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension[todas las extensiones] con documentación sobre su configuración.

== Transformar la telemetría

Hay muchos procesadores en el https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[repositorio]. Aquí tratamos de dar una visión general de los procesadores más utilizados y sus capacidades. Para más detalles y muchos más procesadores utilice el https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[repositorio].

=== Filtrado

Algunos instrumentos o aplicaciones pueden generar muchos datos de telemetría que son ruidosos e innecesarios para su caso de uso. El https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor[procesador de filtros] se puede utilizar para descartar los datos que no necesite en el recopilador, para evitar enviar los datos a SUSE Observability. Por ejemplo, para eliminar todos los datos de un servicio específico:

[,yaml]
----
processors:
  filter/ignore-service1:
    error_mode: ignore
    traces:
      span:
        - resource.attributes["service.name"] == "service1"
----

El procesador de filtros utiliza el https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md[Open Telemetry Transformation Lanuage (OTTL)] para definir los filtros.

=== Añadir, modificar o eliminar atributos

El https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor[procesador de atributos] puede cambiar atributos de spans, logs o métricas.

[,yaml]
----
processors:
  attributes/accountid:
    actions:
      - key: account_id
        value: 2245
        action: insert
----

El https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor[procesador de recursos] puede modificar los atributos de un xref:/setup/otel/concepts.adoc#_resources[recurso]. Por ejemplo, para añadir un nombre de clúster Kubernetes a cada recurso:

[,yaml]
----
  processors:
    resource/add-k8s-cluster:
      attributes:
      - key: k8s.cluster.name
        action: upsert
        value: my-k8s-cluster
----

Para cambiar los nombres de las métricas y otra información específica de las métricas también existe el https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor[transformador de métricas].

=== Transformaciones

El https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor[procesador de transformación] puede utilizarse, por ejemplo, para establecer un estado de span:

[,yaml]
----
processors:
  transform:
    error_mode: ignore
    trace_statements:
      - set(span.status.code, STATUS_CODE_OK) where span.attributes["http.request.status_code"] == 400
----

Admite muchas más transformaciones, como la modificación del nombre del tramo, la conversión de los tipos de métrica o la modificación de los eventos de registro. Consulte https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor[el archivo Léame en] para conocer todas las posibilidades. Utiliza el https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md[Open Telemetry Transformation Lanuage (OTTL)] para definir los filtros.

== Datos sensibles a los matorrales

El recopilador es el lugar ideal para eliminar u ofuscar datos confidenciales, ya que se sitúa justo entre sus aplicaciones y SUSE Observability y dispone de procesadores para <<_transforming_telemetry,filtrar y transformar sus datos>>. Junto a las funciones de filtrado y transformación ya comentadas, también se dispone de un https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/redactionprocessor[procesador de redacción] que puede enmascarar valores de atributos que coincidan con una lista de bloques. También puede eliminar los atributos que no coincidan con una lista especificada de atributos permitidos; sin embargo, si se utiliza esta opción, se pueden eliminar rápidamente la mayoría de los atributos, lo que da lugar a una capacidad de observación muy limitada. Tenga en cuenta que no procesa los atributos de los recursos.

Un ejemplo que sólo enmascara atributos y/o valores específicos:

[,yaml]
----
processors:
  redaction:
    allow_all_keys: true
    # attributes matching the regexes on the list are masked.
    blocked_key_patterns:
      - ".*token.*"
      - ".*api_key.*"
    blocked_values: # Regular expressions for blocking values of allowed span attributes
      - '4[0-9]{12}(?:[0-9]{3})?' # Visa credit card number
      - '(5[1-5][0-9]{14})' # MasterCard number
    summary: debug
----

== Probar el colector

Las guías de inicio muestran cómo implementar el recopilador en Kubernetes o utilizar paquetes de Linux para una configuración lista para la producción. También es posible ejecutarlo, por ejemplo para pruebas, directamente como un contenedor Docker para probarlo:

[,bash]
----
docker run \
  -p 127.0.0.1:4317:4317 \
  -p 127.0.0.1:4318:4318 \
  -v $(pwd)/config.yaml:/etc/otelcol-contrib/config.yaml \
  ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
----

Para ello se utiliza la imagen collector contrib que incluye todos los componentes aportados (receptores, procesadores, etc.). También existe una versión más pequeña y limitada de la imagen, pero sólo dispone de un conjunto muy limitado de componentes:

[,bash]
----
docker run \
  -p 127.0.0.1:4317:4317 \
  -p 127.0.0.1:4318:4318 \
  -v $(pwd)/config.yaml:/etc/otelcol/config.yaml \
  ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest
----

Tenga en cuenta que la instalación de Kubernetes por defecto a la distribución de Kubernetes de la imagen del colector, `ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s`, que tiene más componentes que la imagen básica, pero menos que la imagen contrib. Si se encuentra con componentes que faltan con esa imagen puede simplemente cambiar a utilizar la imagen contrib , `ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib`, en su lugar.

== Solución de problemas

=== Las peticiones HTTP del exportador son demasiado grandes

En algunos casos, las solicitudes HTTP de datos de telemetría pueden llegar a ser muy grandes y pueden ser rechazadas por SUSE Observability. SUSE Observability tiene un límite de 4 MB para el protocolo gRPC. Si se encuentra con límites de peticiones HTTP, puede reducir el tamaño de las peticiones cambiando el algoritmo de compresión y limitando el tamaño máximo del lote.

==== Compresión de peticiones HTTP

Las guías de introducción habilitan la compresión `snappy` en el recopilador, que no es la mejor compresión pero utiliza menos recursos de CPU que `gzip`. Si eliminó la compresión, puede volver a activarla o cambiar a un algoritmo de compresión que ofrezca una mejor https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md#_compression_comparison[relación de compresión]. Los mismos tipos de compresión están disponibles para los protocolos gRPC y HTTP.

==== Tamaño máximo del lote

Para reducir el tamaño de la petición HTTP puede reducirse añadiendo una configuración al procesador `batch` que limite el tamaño del lote:

[,yaml]
----
processor:
  batch: {}
    send_batch_size: 8192 # This is the default value
    send_batch_max_size: 10000 # The default is 0, meaning no max size at all
----

El tamaño del lote se define en número de tramos, puntos de datos métricos o registros (no en bytes), por lo que es posible que tenga que experimentar un poco para encontrar el ajuste correcto para su situación. Para más detalles, consulte la https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/README.md[documentación del procesador de lotes].

== Recursos relacionados

La documentación de Open Telemetry proporciona muchos más detalles sobre la configuración y las opciones alternativas de instalación:

* Abrir la configuración del colector de telemetría: https://opentelemetry.io/docs/collector/configuration/
* Instalación del colector en Kubernetes: https://opentelemetry.io/docs/kubernetes/helm/collector/
* Utilización del operador Kubernetes en lugar del gráfico del colector Helm: https://opentelemetry.io/docs/kubernetes/operator/
* Abrir muestreo de telemetría: https://opentelemetry.io/blog/2022/tail-sampling/
