= Conceptos de telemetría abierta
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

Este es un resumen de los conceptos más importantes en Telemetría Abierta y debería ser suficiente para empezar. Para una introducción más detallada utilice la https://opentelemetry.io/docs/concepts/[documentación de]

== Señales

Open Telemetry reconoce 3 señales de telemetría:

* Huellas
* Métricas
* Registros

Por el momento SUSE Observability soporta trazas y métricas, los logs serán soportados en una versión futura. Para los registros de Kubernetes es posible utilizar el xref:/k8s-quick-start-guide.adoc[agente de SUSE Observability] en su lugar.

=== Huellas

Las trazas nos permiten visualizar el recorrido de una solicitud a través de su aplicación. Una traza consiste en uno o más tramos que juntos forman un árbol, una sola traza puede estar enteramente dentro de un solo servicio, pero también puede ir a través de muchos servicios. Cada tramo representa una operación en el procesamiento de la solicitud y tiene:

* un nombre
* hora inicial y final, a partir de las cuales se puede calcular una duración
* estado
* atributos
* atributos de los recursos (véase <<_resources,recursos>>)
* eventos

Los atributos span se utilizan para proporcionar metadatos para el span, por ejemplo un span que para una operación que realiza un pedido puede tener el `orderId` como atributo, o un span para una operación HTTP puede tener el método HTTP y la URL como atributos.

Los eventos de tramo pueden utilizarse para representar un punto en el tiempo en el que ha ocurrido algo importante dentro del funcionamiento del tramo. Por ejemplo, si el span falló, puede haber un evento `exception` o `error` que capture el mensaje de error, un stacktrace y el punto exacto en el que se produjo el error.

=== Métricas

Las métricas son mediciones capturadas en tiempo de ejecución y dan lugar a un evento de métrica. Las métricas son indicadores importantes del rendimiento y la disponibilidad de las aplicaciones, y a menudo se utilizan para alertar sobre una interrupción o un problema de rendimiento. Métricas tiene:

* un nombre
* una marca de tiempo
* un tipo (contador, indicador, histograma, etc.)
* atributos
* atributos de los recursos (véase <<_resources,recursos>>)

Los atributos proporcionan los metadatos de una métrica.

== Recursos

Un recurso es la entidad que produce los datos de telemetría. Los atributos del recurso proporcionan los metadatos del recurso. Por ejemplo, un proceso que se ejecuta en un contenedor, en un pod, en un espacio de nombres en un clúster Kubernetes puede tener atributos de recursos para todas estas entidades.

Los atributos de los recursos suelen ser asignados automáticamente por los SDK. No obstante, se recomienda definir siempre explícitamente los atributos `service.name` y `service.namespace`. El primero es el nombre lógico para el servicio, si no se establece el SDK establecerá un valor `unknown_service` haciendo muy difícil utilizar los datos más tarde en SUSE Observability. El espacio de nombres es una forma práctica de organizar tus servicios, especialmente útil si tienes los mismos servicios ejecutándose en varias ubicaciones.

== Convenciones semánticas

Open Telemetry define nombres comunes para las operaciones y los datos, lo llaman las convenciones semánticas. Las convenciones semánticas siguen un esquema de nomenclatura que permite normalizar el tratamiento de los datos entre lenguajes, bibliotecas y bases de código. Existen convenciones semánticas para todas las señales y para los atributos de los recursos. Se definen para muchas plataformas y operaciones diferentes en el https://opentelemetry.io/docs/specs/semconv/attributes-registry/[sitio web]. Los SDK hacen uso de las convenciones semánticas para asignar estos atributos y SUSE Observability también respeta las convenciones y se basa en ellas, por ejemplo, para reconocer los recursos de Kubernetes.
