= Primeros pasos con Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

image::otel/open-telemetry.svg[Open Telemetry collector y 2 aplicaciones instrumentadas que envían métricas y trazas a SUSE Observability]

SUSE Observability es compatible con https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry es un conjunto de protocolos estandarizados y un marco de código abierto para recopilar, transformar y enviar datos de telemetría como trazas, métricas y registros. La telemetría abierta admite una amplia variedad de lenguajes de programación y plataformas.

SUSE Observability es compatible tanto con métricas como con trazas y añade las métricas y trazas de Open Telemetry a los datos de topología (Kubernetes) que proporciona el agente de SUSE Observability. Por lo tanto, sigue siendo necesario instalar también el agente de SUSE Observability. La compatibilidad con los registros y el uso de Open Telemetry sin el agente de SUSE Observability estará disponible próximamente.

Open Telemetry consta de varios componentes diferentes. Para el uso con SUSE Observability, los xref:/setup/otel/languages/README.adoc[SDKs] para instrumentar su aplicación y el xref:/setup/otel/collector.adoc[colector Open Telemetry] son las partes más importantes. Mostraremos cómo configurar ambos para su uso con SUSE Observability.

Si su aplicación ya está instrumentada con Open Telemetry o con cualquier otra biblioteca compatible con Open Telemetry, como Jaeger o Zipkin, el recopilador se puede utilizar para enviar esos datos a SUSE Observability y no se necesita instrumentación adicional.

SUSE Observability requiere que el recopilador esté configurado con procesadores y autenticación específicos para garantizar que todos los datos utilizados por SUSE Observability estén disponibles.

== Referencias

* https://opentelemetry.io/docs/collector/[Abrir el colector de telemetría] en la documentación de Open Telemetry
* https://opentelemetry.io/docs/languages/[SDK para instrumentar su aplicación] en la documentación de Open Telemetry
