= Solución de problemas de telemetría abierta
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

Hay muchas opciones de configuración, pero lo más importante es que cada entorno (Kubernetes) es ligeramente diferente. Para averiguar dónde está el problema, lo más rápido es elegir una cápsula de la que se esperen datos telemétricos:

. Compruebe el inicio de los registros del pod, los SDKs registrarán advertencias o errores cuando la instrumentación falle en el arranque.
. Compruebe también los registros en busca de errores relacionados con el envío de datos al recopilador
. Compruebe si hay errores de configuración o inicialización en los registros de los pods de recopiladores, que se registrarán justo después del inicio del pod.
. Compruebe también los registros del recopilador en busca de errores relacionados con el envío de datos a SUSE Observability

Los errores en los registros suelen dar una buena indicación del problema. Enumeramos las causas más comunes por las que los datos de Open Telemetry no están disponibles para algunas o todas sus aplicaciones instrumentadas. Si el problema no aparece aquí, también puede consultar https://opentelemetry.io/docs/languages/[la documentación del SDK específica del lenguaje] o https://opentelemetry.io/docs/collector/troubleshooting/[] de Open Telemetry.

== Utilizar el mismo nombre de clúster de Kubernetes

Asegúrese de utilizar el mismo nombre de clúster de Kubernetes para el mismo clúster cuando:

* Instalación del colector de telemetría abierto
* Instalación del agente de SUSE Observability
* Instalación de Kubernetes StackPack

Cuando se utilizan nombres diferentes para el mismo clúster, SUSE Observability no podrá hacer coincidir los datos de Open Telemetry con los datos del agente de SUSE Observability y la perspectiva de trazas permanecerá vacía.

== El recopilador no puede enviar datos a SUSE Observability

=== El punto final OTLP y la clave API de SUSE Observability están mal configurados

Si hay errores de conexión es posible que el punto final OTLP sea incorrecto. Si hay errores de autenticación/autorización (códigos de estado 401 y 403) es probable que la clave API ya no sea válida. Compruebe que el punto final OTLP configurado es la URL de su SUSE Observability, con el prefijo `otlp-` y el sufijo `:443`. Por ejemplo, el punto final OTLP para `play.stackstate.com` es `otlp-play.stackstate.com:443`.

Para asegurarse de que la clave api está configurada correctamente compruebe que:

. el secreto contiene una clave de API válida (verifíquelo en SUSE Observability)
. el secreto se utiliza como variables de entorno en el pod
. la extensión `bearertokenauth` está utilizando el esquema correcto y el valor de la variable de entorno `API_KEY` 
. la extensión `bearertokenauth` es utilizada por el exportador `otlp/suse-observability` 

=== Algunos proxies y cortafuegos no funcionan bien con gRPC

Si el recopilador necesita enviar datos a SUSE Observability a través de un proxy o un cortafuegos, es posible que estos bloqueen el tráfico por completo o que, posiblemente, eliminen algunas partes de los mensajes gRPC o que, inesperadamente, eliminen por completo la conexión gRPC de larga duración. La solución más sencilla es cambiar de gRPC a HTTP, sustituyendo la configuración del exportador `otlp/suse-observability` **y las referencias al mismo en la sección de canalizaciones** por el exportador `otlphttp/suse-observability`.

Aquí `<otlp-http-suse-observability-endpoint>` es similar a `<otlp-suse-observability-endpoint>`, pero en lugar de un prefijo `otlp-` tiene `otlp-http-` prefijo, por ejemplo, `otlp-http-play.stackstate.com`. Para más detalles, consulte la xref:/setup/otel/collector.adoc#_exporters[configuración del colector].

== La aplicación instrumentada no puede enviar datos al recopilador

=== La URL es incorrecta o el tráfico está bloqueado

Si el SDK registra errores sobre la imposibilidad de resolver el nombre DNS del recopilador, es posible que la URL configurada del recopilador sea incorrecta. En Kubernetes, la aplicación suele desplegarse en un espacio de nombres independiente del recopilador. Esto significa que el SDK debe configurarse con el nombre de dominio completo del servicio de recopilación:`http://<service-name>.<namespace>.svc.cluster.local:4317`. En los xref:/setup/otel/collector.adoc[pasos de instalación del recop]ilador, esto era `http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317`, pero si utilizaste un espacio de nombres o un nombre de versión diferente para el recopilador, esto puede ser diferente para tu situación.

Si el SDK registra tiempos de espera de la conexión de red, puede ser que haya una configuración incorrecta en el recopilador o que se utilice el <<_the_language_sdk_uses_the_wrong_port,puerto incorrecto>>. Pero también es posible que las políticas de red de Kubernetes estén bloqueando el tráfico de red desde su aplicación al recopilador. La mejor forma de comprobarlo es con el administrador de Kubernetes. Las políticas de red deben permitir al menos el tráfico TCP en el puerto configurado (4317 y/o 4318) desde todas sus aplicaciones hacia el recopilador.

=== El SDK del lenguaje no es compatible con gRPC

No todos los SDK de idiomas son compatibles con gRPC. Si OTLP sobre gRPC no está soportado es mejor cambiar a OTLP sobre HTTP. La xref:/setup/otel/instrumentation/sdk-exporter-config.adoc#_grpc_vs_http[configuración del exportador del SDK] describe cómo realizar este cambio.

=== El SDK del idioma utiliza el puerto incorrecto

El uso de un puerto incorrecto suele aparecer como un error de conexión, pero también puede manifestarse como el cierre inesperado de conexiones de red. Asegúrese de que el exportador del SDK utiliza el puerto correcto al enviar los datos. Consulte la xref:/setup/otel/instrumentation/sdk-exporter-config.adoc#_grpc_vs_http[configuración del exportador del SDK].

== Pods Kubernetes con hostNetwork activado

El recopilador Open Telemetry enriquece los datos de telemetría con metadatos de Kubernetes. Tal y como está configurado, todos los datos de telemetría que no pueden enriquecerse se descartan. Sin embargo, el recopilador no puede enriquecer los pods que se están ejecutando con `hostNetwork: true` configurado automáticamente. Esto no es posible porque la identificación del pod se produce utilizando la dirección IP del pod y los pods que utilizan la red del host utilizan la dirección IP del host.

Para ayudar al recolector a identificar un pod podemos añadir el atributo `k8s.pod.uid` a los metadatos indicando al SDK que lo añada directamente. Para ello, modifique las especificaciones de su pod y añada las siguientes variables de entorno a su contenedor de aplicaciones instrumentado:

[,yaml]
----
env:
  - name: POD_UID
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.uid
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: k8s.pod.uid=$(POD_UID)
----

Si la var env `OTEL_RESOURCE_ATTRIBUTES` ya está configurada, simplemente añada `k8s.pod.uid`, utilizando una coma como separador. El valor es una lista separada por comas.

== Aplicación Node.js en Google Kubernetes Engine

El SDK de Node.js, sólo en GKE, espera que el espacio de nombres de Kubernetes se establezca a través de la variable de entorno `NAMESPACE`. Si no se establece, seguirá añadiendo el atributo `k8s.namespace.name` pero con un valor vacío.  Esto impide que el procesador de atributos de Kubernetes inserte el nombre de espacio de nombres correcto. Hasta que esto se solucione, una solución es actualizar las especificaciones del pod y añadir esta variable de entorno a los contenedores instrumentados:

[,yaml]
----
env:
  - name: NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
----

== No hay métricas disponibles para la aplicación Node.js

La instrumentación automática para Node.js, configurada mediante variables de entorno, sólo admite trazas. Al menos hasta que se resuelva este https://github.com/open-telemetry/opentelemetry-js/issues/4551[problema de]. Para habilitar las métricas de la instrumentación automática se necesitan cambios en el código. Siga las instrucciones de la https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[documentación de] para realizar estos cambios.

== No se pueden añadir atributos Kubernetes

Durante la instalación del recopilador, se crea un rol de clúster y un enlace de rol de clúster en Kubernetes que permite al recopilador leer metadatos de los recursos de Kubernetes. Si esto falla o se eliminan, el recopilador ya no podrá consultar la API de Kubernetes. Esto aparecerá como errores en el registro del recopilador, los errores incluyen los tipos de recursos para los cuales no se pudieron recuperar los metadatos.

Para solucionarlo, vuelva a instalar el recopilador con el gráfico de Helm y asegúrese de tener los permisos necesarios para crear el rol de clúster y la vinculación del rol de clúster. Como alternativa, solicite al administrador del clúster que realice la instalación del recopilador con los permisos necesarios.
