include::partial$variables.adoc[]
= Glossar
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Weitere Informationen zu den wichtigsten Ressourcen und Konfigurationen im Zusammenhang mit {project-name} Richtlinien in Kubernetes-Umgebungen.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["glossary"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "glossary"]
:sidebar_label: Glossar
:sidebar_position: 90
:current-version: {page-origin-branch}

== A

=== AdmissionPolicy

Eine Namespace-weite Ressource. Die Richtlinie bearbeitet nur die Anfragen, die auf den Namensraum abzielen, in dem die AdmissionPolicy definiert ist.

== C

=== ClusterAdmissionPolicy

Eine <<_admissionpolicy,AdmissionPolicy>>, die auf clusterweite Ressourcen abzielt.

=== ClusterReport

Ein <<_report,Report>> und ein ClusterReport speichern die Ergebnisse von Richtlinien-Scans. Welcher davon verwendet wird, hängt vom Umfang der Ressource ab.

== K

=== kwctl

Ein CLI-Tool zum Erzeugen und Testen von Kubernetes-YAML-Dateien für die Bereitstellung von Richtlinien.

== M

=== MutatingWebhookConfiguration

Einehttps://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[Kubernetes-Ressource], die vom {short-project-name} Controller erstellt wird, damit Kubernetes weiß, wohin ein `AdmissionReview` gesendet werden soll.
Mit anderen Worten: Auf diese Weise teilt ein {short-project-name} Controller Kubernetes mit, wo es eine Richtlinie zur Ressourcenmutation finden kann.

== P

=== Bericht

Ein Report und ein <<_clusterreport,ClusterReport>> speichern die Ergebnisse von Richtlinien-Scans. Welcher davon verwendet wird, hängt vom Umfang der Ressource ab.

[#_policy_server]
=== PolicyServer

Ein PolicyServer validiert eingehende Anfragen, indem er {short-project-name} Richtlinien für Anfragen ausführt.

== V

=== ValidatingWebhookConfiguration

Einehttps://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[Kubernetes-Ressource], die vom {short-project-name} Controller erstellt wird, damit Kubernetes weiß, wohin eine `AdmissionReview` gesendet werden soll.
Mit anderen Worten: Auf diese Weise teilt {short-project-name} Kubernetes mit, wo es eine Richtlinie zur Ressourcenvalidierung finden kann.

== W

=== waPC

WebAssembly-Prozeduraufrufe. https://wapc.io.

=== WASI

WebAssembly-Systemschnittstelle. https://wasi.dev.

=== Wasm

Ein binäres Befehlsformat für eine stapelbasierte virtuelle Maschine. Entwickelt für den Einsatz im Internet. https://webassembly.org.

=== Wasmtime

Eine Laufzeitumgebung für WebAssembly. https://wasmtime.dev.
