= 自定义度量图表的故障排除
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

== 概述

* <<_the_metric_chart_doesnt_show_on_the_highlights_page_of_a_component,在组件的 "亮点 "页面上不显示度量表>>
* <<_the_metric_chart_doesnt_show_on_the_metrics_perspective_of_a_component,指标图表不显示在组件的指标视角中>>
* <<_the_metric_chart_on_a_component_remains_empty_no_data,组件上的度量图表仍然为空（"无数据）>>

== 在组件的 "亮点 "页面上不显示度量表

目前还无法自定义组件亮点页面上显示的度量图表。自定义度量绑定的图表将只显示在 "度量 "视角中。

== 指标图表不显示在组件的指标视角中

`scope` 公制绑定查询用于确定组件是否显示公制绑定。如果组件没有显示度量绑定，请检查作用域中的拓扑查询是否与组件匹配。

首先在组件高亮页面检查组件是否有预期的标签和/或组件类型，名称和类型在顶部，标签在 "关于 "部分。确保标签名称或值没有拼写错误。

检查作用域查询的语法是否正确：

. 通过菜单中的 "视图 "和右侧的蓝色 "探索 "按钮打开探索视图。或直接通过 URL： `https://<your-stackstate-instance>/#/views/explore`
. 打开筛选器并选择 `switch to STQL`
. 现在将查询从作用域复制/粘贴到 STQL 字段，然后运行查询

现在，概览会显示所有与查询匹配的组件，这些组件将获得图表。

== 组件上的度量图表仍然为空（"无数据）

对于没有数据而预期有数据的度量图表，打开检查器（图表右上角的图标）。切换 "显示查询 "按钮以显示查询。

确保查询不再包含任何参数（即`${tags.cluster-name}` 或`${name}` 等所有值都已替换为组件的值。如果在查询中留下了一些参数，该组件上就无法使用标签。因此，请对照组件上的标签核对所使用的名称（本例中为`cluster-name` ）。还要确保名字中没有错别字。

如果所有参数都已填写，则可能是 PromQL 查询出了问题。复制 PromQL 查询并打开 "度量资源管理器"（通过 SUSE Observability 的主菜单），以进行调查。将查询粘贴到度量资源管理器中并运行。结果应该还是空的。

要么指标不存在，要么没有标签，要么标签确实存在，但没有与该值匹配的时间序列。解决这个问题的最快方法是将查询重写为只有度量名称，然后运行，如果有结果，说明度量存在（因此没有错字）。表格结果还可用于验证所有使用的标签是否存在。确保这里也没有错别字。

如果有结果，但不是针对某个标签的特定值（例如`pod_name` 标签），则查询可以，但没有针对该特定组件的该特定指标的时间序列。在这种情况下需要检查的事项：

* 是否为该组件收集了数据（通过 SUSE Observability 代理或其他方式）？
* 组件是否报告了指标？

如何做到这一点取决于数据收集的配置方式。
