include::partial$variables.adoc[]
= 监控模式
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 为监控模式配置 ClusterAdmissionPolicies 或 AdmissionPolicies，以便在不修改传入请求的情况下跟踪和分析策略操作。
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "monitor-mode"]
:doc-type: ["reference"]
:keywords: ["kubernetes", "kubewarden", "monitor mode"]
:sidebar_label: 监控模式
:sidebar_position: 50
:current-version: {page-origin-branch}

定义策略时，可以在两种模式中进行选择，这两种模式在策略的 xref:reference/CRDs.adoc#admissionpolicyspec[`spec.mode`].
默认情况下，您可以在`mode: protect` 中部署策略。
然后，策略会接受、拒绝或更改请求。

可以选择在监控模式下部署策略。在监控模式下：

* 策略会接受所有请求，就像没有安装策略一样。
* `policy-server` 可正常跟踪政策。如果某个请求被拒绝或某个策略提出突变，那么跟踪信息中就会包含详细信息。
* `policy-server` 指标会正常更新，并将模式纳入指标包袱。因此，很容易按模式过滤策略，并将重点放在使用`monitor` 模式部署的策略上。

`mode` 是`ClusterAdmissionPolicy` 和`AdmissionPolicy` 资源中的一个属性。`mode` 属性可以有两个值：`monitor` 和`protect` 。如果省略`mode` ，则默认为`protect` 。

要在`monitor mode` 中创建策略，需要在资源说明中加入语句`mode: monitor`。例如，在本`ClusterAdmissionPolicy` 的`spec` 部分（标记为 ➀）：

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: psp-capabilities
spec:
  mode: monitor <1>
  policyServer: reserved-instance-for-tenant-a
  module: registry://ghcr.io/kubewarden/policies/psp-capabilities:v0.1.3
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    allowed_capabilities:
    - CHOWN
    required_drop_capabilities:
    - NET_ADMIN
----
<1> `mode: monitor` 属性位于`spec` 部分。

== 更改政策模式

为安全起见，对策略资源拥有`UPDATE` 权限的用户可以使策略更具限制性。这意味着您可以将现有`ClusterAdmissionPolicy` 或`AdmissionPolicy` 的`mode` 从`monitor` 更改为`protect` 。

但是，不能将现有`ClusterAdmissionPolicy` 或`AdmissionPolicy` 的`mode` 从`protect` 更改为`monitor` 。

因此，要将`mode` 从`protect` 改为`monitor` ，需要删除该策略，然后以`monitor` 模式重新创建。将策略从`protect` 切换到`monitor` 等同于删除策略，因此这种方法假定用户拥有策略删除权限。

== 关于变异政策的说明

在`monitor` 模式下突变策略不会对资源执行突变。
在`monitor` 模式下，政策会记录其本应采取的行动。它们还记录了在`protect` 模式下产生的突变补丁。

[WARNING]
====
当变异策略处于`monitor` 模式时，后面的策略会评估一个不变的资源，因此与变异策略处于`protect` 模式时不同。
====
