include::partial$variables.adoc[]
= sources.yaml 的参考资料
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 通过指定源授权的路径和格式以及不安全源，配置 sources.yaml 文件以便与 PolicyServer CR 配合使用。
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "sources.yaml"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "sources.yaml"]
:sidebar_label: sources.yaml
:sidebar_position: 110
:current-version: {page-origin-branch}

您可以使用`--sources-path` 参数调整`kwctl` 和`policy-server` 二进制文件的推拉行为，该参数用于指定`sources.yaml` 文件的路径。

要配置 PolicyServer CR，请设置其`spec.insecureSources` 和`spec.sourceAuthorities` 字段。这些字段的格式与下文各部分相对应。

== `sources.yaml` 文件

如果在`kwctl` 命令中省略`--sources-path` 参数，则会尝试从这些文件夹加载`sources.yaml` 文件：

* Linux `$HOME/.config/kubewarden/sources.yaml`
* Mac:`$HOME/Library/Application Support/io.kubewarden.kubewarden/sources.yaml`
* 视窗 `$HOME\AppData\Roaming\kubewarden\config\sources.yaml`

其结构如下

[subs="+attributes",yaml]
----
insecure_sources:
  - "registry-dev.example.com"
  - "registry-dev2.example.com:5500"
source_authorities:
  "registry-pre.example.com":
    - type: Path
      path: /opt/example.com/pki/ca-pre1-1.pem
    - type: Path
      path: /opt/example.com/pki/ca-pre1-2.der
  "registry-pre2.example.com:5500":
    - type: Data
      data: |
            -----BEGIN CERTIFICATE-----
            ca-pre2 PEM cert
            -----END CERTIFICATE-----
----

该文件为 YAML 或 JSON 格式。所有键都是可选的，因此下面是一个有效的`sources.yaml` 文件：

[subs="+attributes",yaml]
----
insecure_sources: ["dev.registry.example.com"]
----

原样

[subs="+attributes",json]
----
{
    "source_authorities": {
        "host.k3d.internal:5000": [
            {"type": "Data","data":"pem cert 1"},
            {"type": "Data","data":"pem cert 2"}
        ]
    }
}
----

=== 不安全资料来源部分

`insecure_sources` 部分中的主机与未列出的主机行为不同。

* 未列出主机，请尝试：
 ** 使用 HTTPS 进行连接，验证服务器身份

+
如果连接失败，则停止操作。*`insecure_sources` 中列出的主机，按以下顺序尝试：** 使用 HTTPS 连接 验证服务器身份 **使用 HTTPS 连接，跳过主机验证 ** 使用 HTTP 连接

+
如果全部失败，则停止运行。

[NOTE]
====

在使用本地注册表或 HTTP 服务器进行开发时，通常使用`insecure_sources` 就可以了。它避免了管理证书的负担。
显然，这不是用于生产的。

====


=== 资料来源部门

`source_authorities` 部分包含 URI 和 CA 证书。它为该 URI 形成一个证书链。它用于验证 OpenContainer Initiative (OCI) 注册表和 HTTPS 服务器的身份。

您可以使用隐私增强邮件 (PEM) 或区分编码规则 (DER) 格式对这些证书进行编码。要指定 DER 格式的证书，需要使用包含证书的文件的路径。在 PEM 格式中，您可以指定证书文件的路径，也可以指定包含实际证书的字符串。您可以使用`type` 键指定这两种方式：

[subs="+attributes",yaml]
----
source_authorities:
  "registry-pre.example.com":
    - type: Path
      path: /opt/example.com/pki/ca-pre1-1.pem
    - type: Path
      path: /opt/example.com/pki/ca-pre1-2.der
    - type: Data
      data: |
            -----BEGIN CERTIFICATE-----
            A string with the ca-pre1-3 PEM cert
            -----END CERTIFICATE-----
  "registry-pre2.example.com:5500":
    - type: Path
      path: /opt/example.com/pki/ca-pre2-1.der
----

=== 代理部分

`proxies` 部分包含代理配置，类似于通常的环境变量`HTTP_PROXY`,`HTTPS_PROXY`,`NO_PROXY` （及其小写对应变量）。

该配置优先于设置这些环境变量。

有关该功能的更多信息，请参阅xref:/howtos/proxy-configuration.adoc[如何操作页面]。

其格式为

[,yaml]
----
proxies:
  http_proxy: "http://proxy.corp:3128"
  https_proxy: "http://proxy.corp:3129"
  no_proxy: "localhost,.corp"
----