include::partial$variables.adoc[]
= 威胁模型
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 阅读并理解 "接纳控制威胁模型"，以设计您自己的特定环境威胁模型，确保 Kubernetes 中的安全默认值。
:doc-persona: ["kubewarden-all"]
:doc-topic: ["security", "threat-model"]
:doc-type: ["reference"]
:keywords: ["kubernetes"、"接纳控制威胁模型"、"kubewarden"]
:sidebar_label: 威胁模型
:sidebar_position: 80
:current-version: {page-origin-branch}

https://github.com/kubernetes/community/tree/master/sig-security[Kubernetes Security Special Interest Group (SIG)] 已为 Kubernetes 定义了一个准入控制威胁模型。{project-name} 团队不断根据这一威胁模型评估{short-project-name}，并努力提供安全的默认设置。建议{short-project-name} 管理员阅读并理解该威胁模型，并根据需要使用它来设计自己的特定环境威胁模型。

有关每种威胁的详细信息，请参阅https://github.com/kubernetes/sig-security/tree/main/sig-security-docs/papers/admission-control[SIG Security 发布的文件]。

== Kubernetes 威胁

=== 威胁 1 - 攻击者用流量淹没网络钩子，阻止其运行

==== 场景

在网络层访问 Webhook 端点的攻击者可以发送大量流量，从而有效地拒绝为接纳控制器提供服务。

==== 缓解

如果 Webhook 因任何原因未及时响应，API 服务器应拒绝该请求。
这是{short-project-name} 的默认行为。

关闭失败意味着，如果{short-project-name} 因任何原因停止响应或崩溃，API 服务器默认会拒绝请求。
即使{short-project-name} 通常接受请求，也是如此。

=== 威胁 2 - 攻击者传递需要复杂处理的工作负载，导致超时

==== 场景

攻击者可以在网络层访问准入控制器，向准入控制器发送需要复杂处理的请求，并在准入控制器使用计算能力处理工作负载时导致超时。

==== 缓解

Webhook 关闭和验证呼叫者失败。
这是{short-project-name} 的默认行为。

=== 威胁 3 - 攻击者利用网络钩子的错误配置来绕过

==== 场景

拥有在群集中创建工作负载权限的攻击者可以利用错误配置绕过预期的安全控制。

==== 缓解

定期检查 webhook 配置有助于发现问题。

=== 威胁 4 - 攻击者有权删除或修改 Kubernetes webhook 对象

==== 场景

拥有 Kubernetes API 访问权限的攻击者有足够权限删除群集中的 webhook 对象。

==== 缓解

应严格控制 RBAC 权限。

==== 待办事项

大部分 RBAC 并不在当前讨论的范围内。不过，以下内容将在适当的时候提供给{short-project-name} 用户：

* 围绕最小 RBAC 实施的方向。
* 提供并记录可检测和阻止 RBAC 更改的策略。

=== 威胁 5 - 攻击者获取网络钩子的有效凭证

==== 场景

攻击者可获取接纳控制器网络钩子的有效客户端凭据。

==== 缓解

Webhook 关闭失败。
这是{short-project-name} 的默认行为。

=== 威胁 6 - 攻击者获得访问群集管理员凭证的权限

==== 场景

攻击者可访问 Kubernetes 群集中的群集管理员级别凭据。

==== 缓解

N/A

=== 威胁 7 - 攻击者嗅探集装箱网络上的流量

==== 场景

可以访问容器网络的攻击者可以嗅探 API 服务器和接纳控制器 webhook 之间的流量。

==== 缓解

由于网络钩子使用 TLS 加密所有流量，因此{short-project-name} 是安全的。

=== 威胁 8 - 攻击者对网络钩子进行 MITM 攻击

==== 场景

容器网络上的攻击者如果可以访问 NET_RAW 功能，就可以尝试使用 MITM 工具拦截 API 服务器与接纳控制器 webhook 之间的流量。

==== 缓解

为 Webhooks 配置具有 mTLS 身份验证功能的群集，并在{short-project-name} 协议栈中启用 mTLS 功能。或者，使用支持网络策略的 CNI 设置 mTLS。更多信息，请参阅xref:/reference/security-hardening/webhooks-hardening.adoc["使用相互 TLS 确保网络钩子安全"]。

使用https://artifacthub.io/packages/kubewarden/capabilities-psp/capabilities-psp[capabilities-psp]策略，并将其配置为放弃 NET_RAW 功能。

=== 威胁 9 - 攻击者通过欺骗从网络钩子窃取流量

==== 场景

攻击者可以通过欺骗将流量从目标 API 服务器重定向到接纳控制器网络钩子。

==== 缓解

为 Webhooks 配置具有 mTLS 身份验证功能的群集，并在{short-project-name} 协议栈中启用 mTLS 功能。或者，使用支持网络策略的 CNI 设置 mTLS。更多信息，请参阅xref:/reference/security-hardening/webhooks-hardening.adoc["使用相互 TLS 确保网络钩子安全"]。

=== 威胁 10 - 滥用突变规则创建特权容器

==== 场景

攻击者可导致突变接纳控制器修改工作负载，从而允许创建特权容器。

==== 缓解

审查并测试所有规则。

=== 威胁 11 - 攻击者将工作负载部署到不受准入控制的命名空间中

==== 场景

攻击者能够将工作负载部署到不受许可控制器配置限制的 Kubernetes 命名空间。

==== 缓解

严格控制 RBAC 权限

==== 待办事项

关于这一决定，大多数 RBAC 都不在范围之内。不过，{short-project-name} 团队的目标是：

* 通过我们的文档警告用户，并_建议_使用最低限度的 RBAC。
* 提供*可*检测 RBAC 更改并阻止更改的策略。

=== 威胁 12 - 由于缺少匹配（例如缺少 initcontainers），可以绕过阻止规则

==== 场景

攻击者创建了一个工作负载清单，该清单使用了 Kubernetes API 的一项功能，而该功能不在许可控制器的覆盖范围内

==== 缓解

审查并测试所有规则。您应审查更改策略部署中任何规则的 PR。

=== 威胁 13 - 攻击者利用拦截列表上的不良字符串匹配绕过规则

==== 场景

攻击者拥有创建工作负载的权限，可利用糟糕的字符串匹配绕过规则。

==== 缓解

审查并测试所有规则。

==== 待办事项

引入测试来涵盖这一规则。
您应一如既往地审查政策部署中更改规则的 PR。

=== 威胁 14 - 攻击者使用没有规则的 Kubernetes API 新/旧功能

==== 场景

攻击者拥有创建工作负载的权限，可使用 Kubernetes API 的新功能（如更改 API 版本）绕过规则。

==== 缓解

审查并测试所有规则。有一项政策可以测试已废弃资源的使用情况。可从https://github.com/kubewarden/deprecated-api-versions-policy[the deprecated-api-versions-policy]获取。

NOTE: `deprecated-api-versions-policy` 只处理已知的自定义资源。威胁既包括已废弃的资源版本，也包括被滥用的未知新版本，因此该政策只能解决部分问题。

=== 威胁 15 - 攻击者在运行 Webhook 控制器的节点上部署特权容器

==== 场景

攻击者拥有在群集上部署特权容器的权限，他会在运行接纳控制器 webhook 的群集节点上创建一个特权容器。

==== 缓解

准入控制器使用限制性策略来防止特权工作负载。

=== 威胁 16 - 攻击者挂载特权节点主机路径，允许修改 Webhook 控制器配置

==== 场景

攻击者拥有部署带有工作负载的 hostPath 卷的权限，他创建的卷允许访问接纳控制器 pod 的文件。

部署`kubewarden-default` Helm 图表并启用其推荐策略，其中包括`hostpaths-psp` 策略。配置该策略是为了减少共享 hostPath 卷。

=== 威胁 17 - 攻击者有权限通过 SSH 访问运行接纳网络钩子的群集节点

==== 场景

攻击者可通过 SSH 以特权用户身份登录群集节点。

==== 缓解

N/A

=== 威胁 18 - 攻击者利用策略将接纳请求中的机密数据发送到外部系统

==== 场景

攻击者能够配置一个策略，该策略会监听接纳请求并将敏感数据发送到外部系统。

==== 缓解

* 为 Webhooks 配置具有 mTLS 身份验证功能的群集，并在{short-project-name} 协议栈中启用 mTLS 功能。或者，使用支持网络策略的 CNI 设置 mTLS。

* 默认情况下，{short-project-name} 策略没有网络访问权限，在限制性环境中运行，严格控制 Webhooks 的外部访问。

== {short-project-name} 威胁

=== {short-project-name} 威胁 1 - 为接入控制器建立信任引导

==== 场景

假定 Kubernetes 集群是新的，但值得信任，那么攻击者就能在部署和执行任何安全策略之前入侵{short-project-name} 堆栈。

例如：

* 使用未签名的恶意图像：
 ** {short-project-name}-控制器
 ** 政策服务器
 ** 任何{short-project-name} 依赖项
 ** 任何可选的依赖项（Grafana、Prometheus 等）
* 破坏舵手图有效载荷

==== 缓解

. {short-project-name} 提供软件材料清单，其中列出了所需的所有图像。这有助于实现零信任。Kubernetes 管理员必须在受信任的环境中验证{short-project-name} 镜像、其依赖的镜像以及 Kubernetes 集群的图表。例如，您可以通过`cosign` 实现这一功能。顺便提一下，这也是气隙装置所需的部分实施工作。
. 在{short-project-name}Helm 图表中使用签名的 Helm 图表和经过验证的摘要，而不是标签。但这并不能确保依赖关系的安全。