include::partial$variables.adoc[]
= 升级路径
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 使用支持的版本策略和组件间的兼容性规则升级{project-name} 堆栈。
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["operator-manual", "upgrade-path"]
:doc-type: ["reference"]
:keywords: ["upgrade path", "support"]
:sidebar_label: 升级路径
:sidebar_position: 20
:current-version: {page-origin-branch}

== {project-name} 堆栈版本管理

{short-project-name} 项目使用https://semver.org/[Semantic versioning]来定义其所有组件的 "堆栈 "版本：版本遵循`MAJOR.MINOR.PATCH` 模式。支持的版本为最新版本。

{short-project-name} 遵循 "堆栈 "版本规则的组件有

* `kubewarden-crds` 图表中的 appVersion 字段。

* `kubewarden-controller` 图表中的 appVersion 字段。

* `kubewarden-defaults` 图表中的 appVersion 字段。

* `policy-server` 手动部署的图像标签。默认资源已由`kubewarden-defaults` 图表管理。

* `kwctl` 二进制。

== 堆栈组件之间的版本兼容性

`kubewarden-crds` 图表、`kubewarden-controller` 图表、`kubewarden-defaults` 图表、任何手动部署的`policy-server` 映像和`kwctl` 应运行相同的`MAJOR`.`MINOR`.`PATCH` 版本。

因此，如果运行的`kubewarden-controller` 版本是`1.1.2` ，则使用的``policy-server+s`` 和+`kwctl`+版本也应为`+1.1.2`。

== 舵手图版本

舵手图定义了`version` 字段和`appVersion` 字段。`appVersion` 字段告知{short-project-name} "堆栈 "版本，如前所述。`version` 字段也遵循https://semver.org/[语义版本化]，描述图表模板和`values.yaml` 的向后兼容变化。

== 升级路径

在升级组件时，可以一次性升级多个`PATCH` 堆栈版本。但是，*不*支持在一次升级中升级多个`MAJOR` 或`MINOR` 堆栈版本。

例如，您可以在一次升级中将组件从`1.1.10` 升级到`1.1.nn` 。但不支持从`1.1.10` 升级到`1.5.0` 。在这种情况下，您必须在两个版本之间分别升级到每个`MAJOR`/`MINOR` 版本。因此，有必要将`1.1.10` 升级到`1.2.0` ，然后升级到`1.3.0` ，再升级到`1.4.0` ，最后升级到`1.5.0` 。要将一个`MAJOR` 版本升级到另一个版本，需要应用两个`MAJOR` 版本之间的所有`MINOR` 更新。

.升级路径支持图示例
[mermaid]
....
%%{init: "theme": "neutral"}%% 流程图 LR; accTitle：升级路径支持图 accDescr：{short-project-name} 推荐和支持的升级路径图。
  1.0.0(1.0.0)-->1.0.1(1.0.1); 1.0.1-->1.0.2(1.0.2); 1.0.2-->1.1.0(1.1.0); 1.1.0-->1.1.2(1.1.2); 1.1.0-->1.1.1; 1.1.1-->1.1.2; 1.1.2-->|不推荐|1.2.0(1.2.0); 1.0.2-->|不支持|1.2.0(1.2.0); 1.1.2-->1.2.1(1.2.1); 1.2.0-->1.2.1; linkStyle 6 color:brown,stroke-width:2px,stroke-dasharray：3 5
  linkStyle 7 color:red,stroke-width:2px,stroke-dasharray:3 5
....

== 升级订单

{short-project-name} 用户应从`kubewarden-crds`图表开始升级堆栈，然后是`kubewarden-controller` 图表。之后，升级`policy-server` （通过`kubewarden-defaults` 图表或碰撞自定义图表的图像）和`kwctl` 。

== 降级

*不*支持降级，{short-project-name} 也不对其进行测试。尽管如此，人们还是有理由期望它们能够发挥作用。

== SDK、政策

{short-project-name} {short-project-name} 支持最新版本。它们不需要升级路径，只需升级到最新版本即可。

{short-project-name} 协议栈的变更可能意味着策略和 SDK 会收到更新，以使用最新的{short-project-name} 功能。{short-project-name} 会注意以向后兼容的方式执行这些更新。

例如，一个{short-project-name} 次版本增加了对审计扫描仪 (`v1.7.0`) 的支持，这意味着策略获得了一个新的`spec.backgroundAudit` 字段。这是可选项，向后兼容，默认设置为`true` 。
