include::partial$variables.adoc[]
= Tests für Clusterbetreiber
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Testen Sie Cluster-Operator-Richtlinien mit kwctl unter Verwendung verschiedener Konfigurationen und Validierungsanforderungsobjekte, um die Richtlinieneinstellungen zu überprüfen.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["testing-policies", "cluster-operators"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "cluster operators", "testing"]
:current-version: {page-origin-branch}

Als Betreiber eines Kubernetes-Clusters sollten Sie Tests für die {project-name} Richtlinien durchführen, die Sie verwenden möchten.

Sie werden Fragen haben wie:

* Welches sind die richtigen Richtlinieneinstellungen, um das gewünschte Validierungs-/Mutationsergebnis zu erzielen?
* Wie kann ich sicher sein, dass alles weiterhin wie erwartet funktioniert, wenn ich:
 ** die Richtlinie auf eine neuere Version aktualisieren?
 ** Kubernetes-Ressourcen hinzufügen/ändern?
 ** die Konfigurationsparameter der Richtlinie ändern?
 ** und so weiter?

{short-project-name} hat ein Dienstprogramm, https://github.com/kubewarden/kwctl[`+kwctl+`]das das Testen der Richtlinien außerhalb von Kubernetes ermöglicht.

Um `+kwctl+` zu verwenden, rufen Sie es mit den folgenden Eingaben auf:

. Ein WebAssembly-Binärdatei-URI der auszuführenden Richtlinie.
Die Richtlinie {short-project-name} kann von der:
 ** lokales Dateisystem `+file://+`
 ** einen HTTP(s)-Server `+https://+`
 ** ein OCI-Register `+registry://+`.
. Das zu prüfende Objekt der Zulassungsanfrage.
Sie geben es mit dem `+--request-path+` Argument.
Verwenden Sie `+stdin+`, indem Sie `+--request-path+` auf `+-+` setzen.
. Die Richtlinieneinstellungen für die Laufzeit als Inline-JSON über das `+--settings-json+` -Flag.
Oder eine JSON- oder eine YAML-Datei, die über `+--settings-path+` aus dem Dateisystem geladen wird.

Nach dem Test `+kwctl+` wird das Objekt `+ValidationResponse+` auf der Standardausgabe ausgegeben.

Sie können vorgefertigte Binärdateien von `+kwctl+`https://github.com/kubewarden/kwctl/releases[ hier] herunterladen.

== Ein Testbeispiel

In diesem Abschnitt wird beschrieben, wie Sie die Richtliniehttps://github.com/kubewarden/psp-apparmor[] psp-apparmor mit verschiedenen Konfigurationen und Validierungsanforderungsobjekten testen.

=== `+AdmissionReview+` Anfragen erstellen

Sie müssen Dateien mit den `+AdmissionReview+` Objekten erstellen, um die Richtlinie zu testen.

Sie können eine Datei namens `+pod-req-no-specific-apparmor-profile.json+` mit folgendem Inhalt erstellen:

.pod-req-no-specific-apparmor-profile.json
[%collapsible]
======

[subs="+attributes",json]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "kind": {
    "kind": "Pod",
    "version": "v1"
  },
  "object": {
    "metadata": {
      "name": "no-apparmor"
    },
    "spec": {
      "containers": [
        {
          "image": "nginx",
          "name": "nginx"
        }
      ]
    }
  },
  "operation": "CREATE",
  "requestKind": {"version": "v1", "kind": "Pod"},
  "userInfo": {
    "username": "alice",
    "uid": "alice-uid",
    "groups": ["system:authenticated"]
  }
}
----

======

Diese Anfrage versucht, einen Pod zu erstellen, der kein zu verwendendes AppArmor-Profil angibt.
Der Grund dafür ist, dass es keine `+annotation+` mit der Taste`+container.apparmor.security.beta.kubernetes.io/<container-name>+` gibt.

Sie können eine Datei namens `+pod-req-apparmor-unconfined.json+` mit folgendem Inhalt erstellen:

.pod-req-apparmor-unconfined.json
[%collapsible]
======

[subs="+attributes",json]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "kind": {
    "kind": "Pod",
    "version": "v1"
  },
  "object": {
    "metadata": {
      "name": "privileged-pod",
      "annotations": {
        "container.apparmor.security.beta.kubernetes.io/nginx": "unconfined"
      }
    },
    "spec": {
      "containers": [
        {
          "image": "nginx",
          "name": "nginx"
        }
      ]
    }
  },
  "operation": "CREATE",
  "requestKind": {"version": "v1", "kind": "Pod"},
  "userInfo": {
    "username": "alice",
    "uid": "alice-uid",
    "groups": ["system:authenticated"]
  }
}
----

======

Diese Anfrage versucht, einen Pod mit einem Container namens `+nginx+` zu erstellen, der mit dem Profil `+unconfined+` AppArmor läuft.
Dies ist nur für Übungszwecke gedacht.
Die Ausführung im Modus `+unconfined+` ist eine schlechte Sicherheitspraxis.

Nun können Sie eine Datei namens`+pod-req-apparmor-custom.json+` mit folgendem Inhalt erstellen:

.pod-req-apparmor-custom.json
[%collapsible]
======

[subs="+attributes",json]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "kind": {
    "kind": "Pod",
    "version": "v1"
  },
  "object": {
    "metadata": {
      "name": "privileged-pod",
      "annotations": {
        "container.apparmor.security.beta.kubernetes.io/nginx": "localhost/nginx-custom"
      }
    },
    "spec": {
      "containers": [
        {
          "image": "nginx",
          "name": "nginx"
        }
      ]
    }
  },
  "operation": "CREATE",
  "requestKind": {"version": "v1", "kind": "Pod"},
  "userInfo": {
    "username": "alice",
    "uid": "alice-uid",
    "groups": ["system:authenticated"]
  }
}
----

======

[NOTE]
====
Dies sind alles vereinfachte `+AdmissionReview+` Objekte.
Es werden nur die Felder verwendet, die für die Prüfung der Richtlinie relevant sind.
====


=== Testen Sie die Politik

Jetzt können Sie `+kwctl+` verwenden, um die Erstellung eines Pods ohne Angabe eines AppArmor-Profils zu testen:

[subs="+attributes",console]
----
$ kwctl run \
    --request-path pod-req-no-specific-apparmor-profile.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4 \
    | jq
----

Die Richtlinie nimmt die Anfrage an und erzeugt eine Ausgabe wie diese:

[subs="+attributes",console]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": true
}
----

Die Richtlinie lehnt die Erstellung eines Pods mit einem `+unconfined+` AppArmor-Profil ab:

[subs="+attributes",console]
----
$ kwctl run \
    --request-path pod-req-apparmor-unconfined.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4 \
    | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "These AppArmor profiles are not allowed: [\"unconfined\"]"
  }
}
----

In beiden Fällen haben Sie die Richtlinie ausgeführt *, ohne* irgendeine Einstellung vorzunehmen.
Wie aus derhttps://github.com/kubewarden/psp-apparmor#configuration[Dokumentation der Richtlinie]hervorgeht, führt dies dazu, dass die Verwendung von nicht standardmäßigen Profilen verhindert wird.

Der Pod, der ein benutzerdefiniertes `+nginx+` Profil verwendet, wird ebenfalls von der Richtlinie abgelehnt:

[subs="+attributes",console]
----
$ kwctl run \
    --request-path pod-req-apparmor-custom.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4 \
    | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "These AppArmor profiles are not allowed: [\"localhost/nginx-custom\"]"
  }
}
----

Sie können das Standardverhalten ändern, so dass ausgewählte AppArmor-Profile verwendet werden können:

[subs="+attributes",console]
----
$ kwctl run \
    --request-path pod-req-apparmor-custom.json \
    --settings-json '{"allowed_profiles": ["runtime/default", "localhost/nginx-custom"]}' \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4 \
    | jq
----

Jetzt ist die Anfrage erfolgreich:

[subs="+attributes",console]
----
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": true
}
----

== Automatisierung

Sie können all diese Schritte mithttps://github.com/bats-core/bats-core[] bats automatisieren.

Sie können eine Reihe von Tests schreiben und deren Ausführung in Ihre bestehenden CI- und CD-Pipelines integrieren.

Die Befehle können in einen `+bats+` Test "verpackt" werden:

.Ein Fledermaus-Test
[%collapsible]
======

[,bash]
----
@test "all is good" {
  run kwctl run \
    --request-path pod-req-no-specific-apparmor-profile.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # request accepted
  [ $(expr "$output" : '.*"allowed":true.*') -ne 0 ]
}

@test "reject" {
  run kwctl run \
    --request-path pod-req-apparmor-custom.json \
    registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # request rejected
  [ $(expr "$output" : '.*"allowed":false.*') -ne 0 ]
}
----

======

Wenn sich der `+bats+` Code in der Datei `+e2e.bats+` befindet, können Sie den Test als ausführen:

[subs="+attributes",console]
----
$ bats e2e.bats
 ✓ all is good
 ✓ reject

2 tests, 0 failures
----

xref:tutorials/writing-policies/go/05-e2e-tests.adoc[In diesem]Abschnitt erfahren Sie mehr über das Schreiben von End-to-End-Tests für Ihre Richtlinien.
