include::partial$variables.adoc[]
= Prüfung der Politik
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie, wie Sie {project-name} Policies mit {project-name} für sicheres Cluster-Management erstellen und testen können.
:doc-persona: ["kubewarden-operator", "kubewarden-policy-developer"]
:doc-topic: ["testing-policies", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "persons", "policy author", "cluster operator"]
:sidebar_label: Prüfung der Politik
:current-version: {page-origin-branch}

== Personas für die Prüfung von Richtlinien

Dieser Abschnitt befasst sich mit der Prüfung von {project-name} Policies.
Es gibt zwei Personengruppen, die sich für Testmaßnahmen interessieren:

* *Richtlinienentwickler*: Sie schreiben eine {short-project-name} Richtlinie und möchten sicherstellen, dass sich Ihr Code so verhält, wie Sie es erwarten.
* *Cluster-Operator*: Sie haben eine {short-project-name} Policy gefunden und möchten die Policy-Einstellungen testen und anpassen, bevor Sie sie bereitstellen.
Sie möchten diese Einstellungen in Ihren CI/CD-Pipelines und anderen Verwaltungsaufgaben immer wieder testen.

Die nächsten Abschnitte der Dokumentation zeigen, wie diese Personas {short-project-name} Richtlinien testen können.
