= Tokens de serviço
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

Com o uso de tokens de serviço, é possível se autenticar no SUSE Observability sem ter uma conta de usuário associada. Isso é útil para situações em que você deseja usar o SUSE Observability a partir de serviços sem cabeça, como um servidor de CI. Nesse cenário, normalmente não se deseja provisionar uma conta de usuário no provedor de identidade.

== Gerenciar tokens de serviço

Os tokens de serviço podem ser gerenciados por meio da xref:/setup/cli/cli-sts.adoc[CLI do site`sts` ]. Os seguintes comandos estão disponíveis:

[,sh]
----
> sts service-token --help
Manage service tokens.

Usage:
  sts service-token [command]

Available Commands:
  create      Create a service token
  delete      Delete a service token
  list        List service tokens

Use "sts service-token [command] --help" for more information about a command.
----

Também é possível <<_set_up_a_bootstrap_service_token,configurar um token de serviço de bootstrap>> ao instalar o {stackstate-product-name}.

=== Criar tokens de serviço

[NOTE]
====
O Open Telemetry e o Kubernetes StackPacks permitem que você crie um assunto e um token de serviço com todas as permissões necessárias configuradas.
====

Para criar um token de serviço para {stackstate-product-name}, você pode usar a CLI `sts`.

[,sh]
----
sts service-token create
----

[NOTE]
====
Observe que o token de serviço será exibido apenas uma vez. Não é possível ver o token novamente.
====


Esse comando usa os seguintes argumentos de linha de comando:

|===
| Flag | Descrição

| `--name`
| O nome do token de serviço

| `--expiration`
| A data de expiração do token de serviço; o formato é aaaa-MM-dd. A expiração é opcional.

| `--roles`
| Uma lista separada por vírgulas de funções a serem atribuídas ao token de serviço
|===

Por exemplo, o comando abaixo criará um token de serviço com o nome `my-service-token` e a função `stackstate-k8s-troubleshooter`:

[,sh]
----
> sts service-token create --name my-service-token --roles stackstate-k8s-troubleshooter
✅ Service token created: svctok-aaaaa-bbbb-ccccc-ddddd
----

=== Configurar um token de serviço bootstrap

Ao instalar o {stackstate-product-name}, é possível inicializá-lo com um token de serviço (temporário). Isso permite usar a CLI sem interagir primeiro com {stackstate-product-name} e obter um token de API na interface do usuário. Para configurar isso, adicione o seguinte trecho ao arquivo de configuração {stackstate-product-name}:

Para configurar o {stackstate-product-name} para criar um token de serviço bootstrap no Kubernetes, os seguintes valores precisam ser adicionados ao arquivo `authentication.yaml`. Por exemplo:

[,yaml]
----
stackstate:
  authentication:
    serviceToken:
      bootstrap:
        token: <token>
        roles:
          - stackstate-admin
        ttl: 24h
----

Siga as etapas abaixo para configurar o site {stackstate-product-name} para criar um token de serviço bootstrap:

. Em `authentication.yaml` - adicione o token bootstrap:
 ** *token* - O token que é criado no início (inicial) de {stackstate-product-name}.
 ** *roles* - Uma matriz de funções que são atribuídas ao token bootstrap.
 ** *ttl* - Opcional. O tempo de vida do token de serviço, expresso como uma cadeia de caracteres de duração.
. Armazene o arquivo `authentication.yaml` junto com o `values.yaml` das instruções de instalação do {stackstate-product-name}.
. Execute um upgrade do Helm para aplicar as alterações.
+
[,text]
----
 helm upgrade \
   --install \
   --namespace suse-observability \
   --values values.yaml \
   --values authentication.yaml \
 suse-observability \
 suse-observability/suse-observability
----

[NOTE]
====
* A primeira execução do comando helm upgrade resultará na reinicialização dos pods, o que pode causar uma breve interrupção da disponibilidade.
* Inclua `authentication.yaml` em cada execução de `helm upgrade`.
* A configuração de autenticação é armazenada como um segredo do Kubernetes.
====


==== Configurar o token do serviço bootstrap a partir de um segredo externo

Em vez de especificar o token bootstrap por meio dos valores do Helm, você também pode ler o token bootstrap de um segredo que é criado e gerenciado fora do gráfico do Helm (um segredo externo). Para usar um token boostrap de um externo, siga xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[estas etapas] e adicione os seguintes dados:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  bootstrap_token: <base64 of token>
----

Esse token pode ser adicionado ao segredo ao lado dos dados que já estão lá.

=== Listar tokens de serviço

O ID, o nome, a data de validade e as funções de todos os tokens de serviço criados podem ser vistos usando a CLI do `sts`. Por exemplo:

[,sh]
----
> sts service-token list
ID              | NAME             | EXPIRATION | ROLES
107484341630693 | my-service-token |            | [stackstate-admin]
----

=== Excluir tokens de serviço

Um token de serviço pode ser excluído usando a CLI do `sts`. Passe o ID do token de serviço como argumento. Por exemplo:

[,sh]
----
> sts service-token delete 107484341630693
✅ Service token deleted: 107484341630693
----

== Usar tokens de serviço

Você usa tokens de serviço para se autenticar ao usar as APIs do SUSE Observability:* Ao usar a CLI * Ao usar as APIs HTTP diretamente * Ao ingerir dados de telemetria

=== SUSE Observability `sts` CLI

Um token de serviço é usado para autenticação com a CLI do `sts`. Para obter mais informações, consulte xref:/setup/cli/cli-sts.adoc#_authentication[a documentação da CLI].

=== APIs de observabilidade do SUSE

Para usar um token de serviço para se comunicar diretamente com a API do SUSE Observability, adicione-o ao cabeçalho da solicitação de uma das seguintes maneiras:

* No cabeçalho `Authorization`:
+
[,sh]
----
  > curl -X GET -H "Authorization: ApiKey <TOKEN>" http://localhost:8080/api/server/status
----

* No cabeçalho `X-API-Key`:
+
[,sh]
----
  > curl -X GET -H "X-API-Key: <TOKEN>" http://localhost:8080/api/server/status
----

=== Ingestão de dados de telemetria

Para criar um token de serviço para ingestão de dados de telemetria, você precisa primeiro criar uma função:
[,sh]
----
> sts rbac create-subject --subject my-agent
✅ Created subject 'my-agent'
> sts rbac grant --subject my-agent --permission update-metrics
✅ Granted permission 'update-metrics' on 'system' to subject 'my-agent'
PERMISSION   | RESOURCE
update-metrics | system
----

Se quiser usar o token de serviço para ingerir dados do Kubernetes RBAC, você também precisará conceder `update-scoped-permissions`:
[,sh]
----
> sts rbac grant --subject my-agent --permission update-scoped-permissions --resource my-cluster
✅ Granted permission 'update-scoped-permissions' on 'my-cluster' to subject 'my-agent'
PERMISSION                | RESOURCE
update-metrics            | system
update-scoped-permissions | my-cluster
----

Isso criará uma nova função no SUSE Observability chamada `my-agent` e concederá a ela a permissão `update-metrics`. Em seguida, você pode criar um ServiceToken para essa função:

[,sh]
----
> sts service-token create --name my-agent --roles my-agent
✅ Service token created: svctok-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
----

O token de serviço recém-criado pode ser usado como a chave de API para autenticação de dados de telemetria:

* {stackstate-product-name} xref:k8s-suse-rancher-prime.adoc#_installing_the_suse_observability_agent[Agente (incluindo o agente RBAC)]
* xref:setup/otel/getting-started/getting-started-k8s.adoc[Coletor OTel]


