= Référence de MachineInventorySelectorTemplate
:revdate: 2025-09-08
:page-revdate: {revdate}

Le MachineInventorySelectorTemplate est une ressource définie par l'utilisateur qui sera utilisée comme modèle pour créer les xref:references/machineinventoryselector-reference.adoc[MachineInventorySelectors] requis.

C'est la ressource responsable de la définition des critères de correspondance pour associer une machine inventoriée à une ressource du cluster.

La clé pertinente est le site `+selector+` qui comprend des expressions de sélection d'étiquettes.

.MachineInventorySelectorTemplate
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: my-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        ...
----

`+template.spec.selector+` peut inclure les clés `+matchLabels+` et/ou `+matchExpressions+`.

== `+template.spec.selector.matchLabels+`

Il s'agit d'une carte de `+{key,value}+` paires `+(map[string]string)+`. Lorsque plusieurs étiquettes sont fournies, elles doivent toutes correspondre.

.Cliquez ici pour plus d'informations
[%collapsible]
====
[yaml]
----
...
spec : template : spec : selector : matchLabels : element : fire manufacturer : somevalue
----
====

Un cluster défini avec le sélecteur ci-dessus ne tentera de provisionner que les nœuds inventoriés avec ces deux étiquettes.

== `+template.spec.selector.matchExpressions+`

Il s'agit d'une liste de sélecteurs d'étiquettes, chaque sélecteur d'étiquette pouvant être défini comme suit :

|===
| Clé | Type | Description

| clé
| chaîne de caractères
| Il s'agit de la clé d'étiquette sur laquelle le sélecteur s'applique

| opérateur
| chaîne de caractères
| Représente la relation entre la clé et un ensemble de valeurs. Les opérateurs valides sont "In", "NotIn", "Exists" et "DoesNotExist".

| valeurs
| []chaîne
| Valeurs est un tableau de chaînes de caractères. Si l'opérateur est "In" ou "NotIn", le tableau de valeurs doit être non vide. Si l'opérateur est "Exists" ou "DoesNotExist", le tableau de valeurs doit être vide.
|===

.Cliquez ici pour plus d'informations
[%collapsible]
====
[,yaml]
----
...
spec:
  template:
    spec:
      selector:
        matchExpressions:
        - key: element
          operator: In
          values: [ 'fire' ]
        - key: manufacturer
          operator: Exists
----
====

Un cluster défini avec le sélecteur ci-dessus ne tentera de provisionner que les nœuds inventoriés avec le label `+element=fire+` et incluant un label `+manufacturer+` défini avec n'importe quelle valeur.
