= Référence à ManagedOSVersion
:revdate: 2025-09-08
:page-revdate: {revdate}

La ressource `+ManagedOSVersion+` est chargée de définir une version de l'image du système d'exploitation qui peut être utilisée avec les ressources `+SeedImage+` ou `+ManagedOSImage+`.

Plusieurs clés peuvent être configurées sous une spécification de ressource `+ManagedOSVersion+`.

.managedosversion-example.yaml
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  labels:
    elemental.cattle.io/channel: elemental-channel
  name: v2.0.2
  namespace: fleet-default
spec:
  metadata:
    displayName: SLE Micro
    upgradeImage: registry.suse.com/suse/sle-micro/5.5:2.0.2
  type: container
  version: v2.0.2
----

== `+ManagedOSVersionSpec+` référence

|===
| Clé | Type | Valeur par défaut | Description

| métadonnées
| objet
| nul
| Elle définit certaines données relatives à l'image du système d'exploitation. Voir [référence](#métadonnées)

| minVersion
| chaîne de caractères
| nul
| Non utilisé

| type
| chaîne de caractères
| vide
| Définit le type d'image du système d'exploitation, qui peut être `+container+` ou `+iso+`

| version
| chaîne de caractères
| vide
| Version de l'image du système d'exploitation

| upgradeContainer
| objet
| nul
| Un conteneur de mise à niveau qui peut être défini. Voir [référence](#upgradecontainer)
|===

.Cliquez ici pour plus d'informations
[%collapsible]
====
Exemple d'image .ISO
[,yaml]
----
metadata:
  displayName: SLE Micro ISO x86_64
  uri: registry.suse.com/suse/sl-micro/6.0/baremetal-iso-image:2.2.0
type: iso
version: v2.2.0
----
====

.Cliquez ici pour plus d'informations
[%collapsible]
====
Exemple d'image .conteneur
[,yaml]
----
metadata:
  displayName: SLE Micro upgrade
  upgradeImage: registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:2.2.0
type: container
version: v2.2.0
----
====

== métadonnées

Cette section décrit les informations nécessaires pour définir une image de système d'exploitation dans {elemental-product-name}.

Si `+type+` est défini sur `+container+`:

|===
| Clé | Type | Valeur par défaut | Description

| displayName
| chaîne de caractères
| vide
| Nom de l'image du système d'exploitation tel qu'il apparaît dans l'interface utilisateur de Rancher

| upgradeImage
| chaîne de caractères
| vide
| Image du conteneur entièrement qualifiée (référence OCI ou URI HTTP)
|===

Si `+type+` est défini sur `+iso+`:

|===
| Clé | Type | Valeur par défaut | Description

| displayName
| chaîne de caractères
| vide
| Nom de l'image du système d'exploitation tel qu'il apparaît dans l'interface utilisateur de Rancher

| uri
| chaîne de caractères
| vide
| Image ISO entièrement qualifiée
|===

== `+upgradeContainer+`

Cela permet d'écraser le champ par défaut `+upgrade+` des plans du contrôleur de mise à niveau du système (voir xref:rancher-os-management/upgrade-lifecycle.adoc#_components[composants de mise à niveau]) sur la base de cette ManagedOSVersion.
Ces clés sont traduites par le contrôleur de mise à niveau du système en une spécification de Kubernetes https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container[conteneur].
Il s'agit du conteneur responsable de l'exécution d'une mise à jour du système d'exploitation.
