= Rancher-Einrichtung
:revdate: 2026-02-18
:page-revdate: {revdate}

== Installation von Rancher

_Wenn Sie bereits mit Rancher v2.13 oder höher arbeiten, können Sie diesen Abschnitt überspringen und zu xref:tutorials/first-cluster.adoc[Ihrem ersten Cluster] springen._

[NOTE]
====
Beginnend mit Rancher v2.13 ist {product_name} als Rancher-Systemdiagramm vorinstalliert. Es ist nicht mehr notwendig, {product_name} separat zu installieren. Eine einfache Installation von Rancher v2.13 oder höher reicht aus, um mit der Cluster-API (CAPI) zu beginnen.

====

Helm ist die empfohlene Methode zur Installation von Rancher in einem bestehenden oder neuen Kubernetes-Cluster.

ifeval::["{build-type}" == "product"]
[TIP]
====
Stellen Sie sicher, dass Sie einer der offiziellen https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/installation-and-upgrade.html[Installationsanleitungen] für Rancher folgen.
====
endif::[]
ifeval::["{build-type}" == "community"]
[TIP]
====
Stellen Sie sicher, dass Sie einer der offiziellen https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade[Installationsanleitungen] für Rancher folgen.
====
endif::[]

Hier ist ein Minimalbeispiel für die Installation von Rancher mit Helm:

[source,bash]
----
helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --create-namespace \
    --set hostname=<rancher-hostname> \
    --version <rancher-version> \
    --wait
----

Ersetzen Sie `<rancher-hostname>` durch den tatsächlichen Hostnamen Ihres Rancher-Servers und verwenden Sie `--version`, um eine Rancher-Version von `v2.13.0` oder höher anzugeben.

== Was wird installiert?

Wenn Rancher v2.13 oder höher installiert wird, wird {product_name} automatisch als Systemkomponente im `cattle-turtles-system` Namespace bereitgestellt. Dazu gehören:

* Der `rancher-turtles-controller-manager` pod, der alle CAPI-bezogenen Ressourcen verwaltet
* Kern-CAPI-CRDs und der Kern-CAPI-Controller
* Die benutzerdefinierte Ressource `CAPIProvider`, die die deklarative Definition von CAPI-Anbietern ermöglicht

[NOTE]
====
Der Kern des CAPI-Controller-Manifests ist in eine ConfigMap eingebettet, was den Betrieb in luftdichten Umgebungen vereinfacht.
====

== Installation von CAPI-Providern

Mit {product_name}, das in Rancher eingebettet ist, werden CAPI-Anbieter nicht mehr standardmäßig gebündelt. Anbieter werden deklarativ über die benutzerdefinierte Ressource `CAPIProvider` verwaltet, und für die Installation von zertifizierten Anbietern steht eine eigene Anbietertabelle zur Verfügung. Weitere Informationen über die Anbieterliste finden Sie unter xref:user/providers.adoc[Zertifizierte Anbieter installieren].

Zum Beispiel, um einen Anbieter zu definieren:

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws
  namespace: cattle-turtles-system
spec:
  type: infrastructure
  name: aws
----

Eine vollständige Liste der Konfigurationsoptionen finden Sie in der xref:reference/capiprovider.adoc[CAPIProvider-Referenz].

Sie sind jetzt bereit, {product_name} zu benutzen! 🎉