= 分布式混合云或多云集群
:page-languages: [EN, JA, KO, ZH]
:revdate: 2025-05-26
:page-revdate: {revdate}

K3s 集群仍可部署在不共用专用网络和不直接连接的节点上（如不同公有云中的节点）。实现这一目标有两种选择：嵌入式 k3s 多云解决方案和与`tailscale` VPN 提供商集成。

[CAUTION]
====
节点之间的延迟会增加，因为外部连接需要更多的跳数。这将降低网络性能，如果延迟过高，还可能影响群集的健康。
====


[CAUTION]
====
此类部署不支持嵌入式 etcd。如果使用嵌入式 etcd，所有服务器节点都必须能通过各自的私有 IP 相互连接。代理可以分布在多个网络上，但所有服务器都应位于同一地点。
====


== 嵌入式 k3s 多云解决方案

K3s 使用 wireguard 为集群流量建立 VPN 网状网络。每个节点都必须有一个唯一的 IP 地址（通常是公共 IP 地址）。K3s 监控流量将使用 websocket 隧道，群集（CNI）流量将使用 wireguard 隧道。

要启用这种部署类型，必须在服务器上添加以下参数：

[,bash]
----
--node-external-ip=<SERVER_EXTERNAL_IP> --flannel-backend=wireguard-native --flannel-external-ip
----

和代理人：

[,bash]
----
--node-external-ip=<AGENT_EXTERNAL_IP>
----

其中`SERVER_EXTERNAL_IP` 是我们可以到达服务器节点的 IP，`AGENT_EXTERNAL_IP` 是我们可以到达代理节点的 IP。请注意，代理中的`K3S_URL` 配置参数应使用`SERVER_EXTERNAL_IP` 才能连接到代理。切记检查 "xref:installation/requirements.adoc#_networking[联网要求]"，并允许访问内部和外部地址上列出的端口。

`SERVER_EXTERNAL_IP` 和`AGENT_EXTERNAL_IP` 之间都必须有连接，而且通常是公共 IP。

[IMPORTANT]
.动态 IP
====
如果节点被分配了动态 IP 且 IP 发生变化（例如在 AWS 中），则必须修改`--node-external-ip` 参数以反映新 IP。如果将 K3s 作为服务运行，则必须修改`/etc/systemd/system/k3s.service` 然后运行：

[,bash]
----
systemctl daemon-reload
systemctl restart k3s
----
====

[#_integration_with_the_tailscale_vpn_provider_experimental]
== 与 Tailscale VPN 提供商集成（试验性）

适用于 v1.27.3、v1.26.6、v1.25.11 及更新版本。

K3 可以与https://tailscale.com/[] Tailscale 集成，这样节点就可以使用 Tailscale VPN 服务在节点之间建立网状结构。

在部署 K3 之前，Tailscale 需要完成四个步骤：

. 登录您的 Tailscale 账户
. 在`Settings > Keys` 中，生成一个认证密钥 ($AUTH-KEY)，该密钥可重复用于集群中的所有节点
. 决定群集将使用的 podCIDR（默认为`10.42.0.0/16` ）。在 "访问控制 "中将 CIDR（或双协议栈的 CIDR）附加到 "说明 "中：
+
[,yaml]
----
"autoApprovers": {
     "routes": {
         "10.42.0.0/16":        ["your_account@xyz.com"],
         "2001:cafe:42::/56": ["your_account@xyz.com"],
     },
 },
----

. 在节点中安装 Tailscale：
+
[,bash]
----
curl -fsSL https://tailscale.com/install.sh | sh
----

要部署启用了 Tailscale 集成的 K3，必须在每个节点上添加以下参数：

[,bash]
----
--vpn-auth="name=tailscale,joinKey=$AUTH-KEY"
----

或在文件中提供该信息并使用该参数：

[,bash]
----
--vpn-auth-file=$PATH_TO_FILE
----

如果您有自己的 Tailscale 服务器（如 headscale），也可以通过在 vpn-auth 参数中添加`,controlServerURL=$URL` 来连接它。

接下来，可以使用以下命令创建服务器：

[,bash]
----
k3s server --token <token> --vpn-auth="name=tailscale,joinKey=<joinKey>" --node-external-ip=<TailscaleIPOfServerNode>
----

执行此命令后，访问 Tailscale 管理控制台，批准 Tailscale 节点和子网（如果尚未通过自动批准程序批准）。

服务器设置完成后，使用以下命令连接代理：

[,bash]
----
k3s agent --token <token> --vpn-auth="name=tailscale,joinKey=<joinKey>" --server https://<TailscaleIPOfServerNode>:6443 --node-external-ip=<TailscaleIPOfAgentNode>
----

再次，像对服务器那样批准 Tailscale 节点和子网。

如果在 Tailscale 中激活了 ACL，则需要添加一条 "接受 "规则，以允许 pod 相互通信。假设您创建的授权密钥会自动用`testing-k3s` 标记 Tailscale 节点，则规则应如下所示：

[,yaml]
----
"acls": [
    {
        "action": "accept",
        "src":    ["tag:testing-k3s", "10.42.0.0/16"],
        "dst":    ["tag:testing-k3s:*", "10.42.0.0/16:*"],
    },
],
----

[CAUTION]
====
如果计划使用同一个 tailscale 网络运行多个 K3s 群集，请创建适当的https://tailscale.com/kb/1018/acls/[ACL]以避免 IP 冲突，或为每个群集使用不同的 podCIDR 子网。
====
