= Enregistrer un système d'exploitation non géré
:revdate: 2025-09-08
:page-revdate: {revdate}

Normalement, {elemental_operator_url}[{elemental_operator_name}] gère les systèmes d'exploitation qui sont installés et configurés par {elemental_toolkit_url}[{elemental_toolkit_name}]. +
Par exemple, pour automatiser l'installation, la mise à niveau et la réinitialisation du système d'exploitation, le site `+elemental-register+` s'appuie sur le CLI `+elemental+` pour exécuter ces opérations.

Toutefois, il est également possible d'enregistrer et de fournir {elemental-product-name} des systèmes "sans boîte à outils".

Dans ce scénario, xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_register_command_line_tool[elemental-register] doit être installé sur le système. +
En option, l'xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[agent du système élémentaire] peut être installé. Notez que sans `+elemental-system-agent+`, {elemental_operator_name} ne sera pas en mesure de provisionner un cluster k8s sur la machine. Dans ce cas, le site {elemental_operator_name} ne peut être utilisé qu'à des fins d'inventaire du système d'exploitation.

Enfin, sur le cluster de gestion, le site `+MachineRegistration+` doit activer le drapeau `+spec.config.elemental.registration.no-toolkit+`.

Une fois que `+no-toolkit+` est activé sur le site `+MachineRegistration+` et qu'un nouvel enregistrement est effectué à l'aide de `+elemental-register --install+` sur le système, un nouveau `+MachineInventory+` est créé sur le cluster de gestion :

[,bash]
----
kubectl -n fleet-default describe machineinventory my-unmanaged-os-machine
----

Le site `+MachineInventory+` sera annoté avec l'annotation `+elemental.cattle.io/os.unmanaged: "true"+`, soulignant que cette machine n'est pas gérée et que ses fonctionnalités sont limitées.

Sur le système, lorsque l'enregistrement est réussi, les fichiers `+/etc/rancher/elemental/agent/config.yaml+` et `+/var/lib/elemental/agent/elemental_connection.json+` sont automatiquement créés pour configurer le système `+elemental-system-agent+`.
Le composant `+elemental-system-agent+` est nécessaire pour le provisionnement de K8s et les déclencheurs de réinitialisation.

Lorsqu'une xref:node-operational-tasks/reset.adoc[réinitialisation de la machine] est déclenchée, par exemple en supprimant directement le site `+MachineInventory+`, le site `+elemental-system-agent+` exécute un plan de réinitialisation simple qui crée le fichier sentinelle `+/var/lib/elemental/.unmanaged_reset+`. +
La présence de ce fichier indique que la machine doit être réinitialisée. Cela peut impliquer l'arrêt de services, la désinstallation de paquets, le formatage de périphériques, et ainsi de suite, en fonction de la manière dont la machine est gérée de manière personnalisée.

== Fonctionnalités prises en charge

* Enregistrement d'un `+MachineInventory+`
* Approvisionnement K8s (lorsque l'xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[agent elemental-system] est installé et fonctionne sur la machine)
* Déclencheurs de réinitialisation (lorsque l'xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[agent du système élémentaire] est installé et fonctionne sur la machine)

== Fonctionnalités non prises en charge

* xref:references/cloud-config-reference.adoc[Configuration] pilotée par Cloud-init
* xref:node-operational-tasks/upgrade.adoc[Mises à jour du] système d'exploitation
* xref:node-operational-tasks/reset.adoc[Réinitialisation du] système d'exploitation
