ifdef::ss-ff-stackpacks2_enabled[]
= UI-Präsentationskonzepte
:revdate: 2026-01-08
:page-revdate: {revdate}
:description: UI-Präsentationskonzepte

[IMPORTANT]
====
*Status:* In aktiver Entwicklung.

*Verfügbarkeit:* Hinter der Flagge der StackPacks 2.0-Funktion. Wie Sie die Funktion aktivieren, erfahren Sie in der xref:/setup/custom-integrations/overview.adoc[Übersicht über benutzerdefinierte Integrationen].

Diese Dokumentation beschreibt die aktuelle Entwurfsabsicht und die Konfigurationsoberfläche auf hoher Ebene.

Hinweis: Es wurden noch keine Verhaltensweisen und Fähigkeiten implementiert.

Da sich diese Funktion in aktiver Entwicklung befindet, können sich Verhalten, Schemata und Fähigkeiten mit der Weiterentwicklung des Modells ändern.
====

Dies ist eine Zusammenfassung der wichtigsten Konzepte im Zusammenhang mit der UI-Präsentation und sollte für den Einstieg ausreichen.

== KomponentePräsentation

Das zentrale Konzept des UI-Präsentationsmodells ist die *ComponentPresentation*.

Eine `+ComponentPresentation+` legt fest, wie eine oder mehrere übereinstimmende Komponenten in der Benutzeroberfläche in Abhängigkeit vom aktiven Kontext dargestellt werden.
Sie konzentriert sich ausschließlich auf die *Präsentation*, z. B. Benennung, Symbole, Tabellen, Übersichts- und Hervorhebungsseiten, Filter und die Platzierung von Menüpunkten.

Auf einer hohen Ebene ist eine ComponentPresentation:

* Wählt Komponenten über eine Bindung (eine einfache STQL-Abfrage) aus.
* Gilt für einen bestimmten Modus (z. B. Beobachtbarkeit).
* Definiert einen oder mehrere Präsentationsaspekte (z. B. Übersichtstabellen oder Hervorhebungen).
* Kann Präsentationseigenschaften teilweise definieren und mit anderen passenden Definitionen zusammenstellen.

Mehrere ComponentPresentations können sich auf dieselbe Komponente beziehen. In solchen Fällen werden ihre Definitionen kombiniert, um die endgültige Darstellung zu bestimmen.

endif::ss-ff-stackpacks2_enabled[]
