include::partial$variables.adoc[]
= Proposer une amélioration de la documentation
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Lancez une amélioration de la documentation en ouvrant un dossier GitHub avec des détails clairs sur ce qui est manquant, obsolète, erroné ou qui nécessite une révision de la qualité.
:doc-persona: ["kubewarden-developer", "kubewarden-operator", "kubewarden-manager"]
:doc-topic: ["contribution-guide", "docs-contribution", "improvement"]]
:doc-type: ["howto"]
:keywords: ["kubewarden", "documentation", "suggérer une amélioration"].
:sidebar_label: Proposer des améliorations au document
:sidebar_position: 8
:current-version: {page-origin-branch}

Si vous remarquez un problème dans la documentation de {short-project-name} ou si vous voulez suggérer un nouveau contenu, ouvrez un dossier. Il vous suffit d'avoir accès à un GitHubhttps://github.com/join[compte] et à un navigateur.

En général, tout nouveau travail de documentation pour {short-project-name} commence par une question sur GitHub.
ifeval::["{build-type}" == "community"]
L' https://github.com/orgs/kubewarden/teams/kubewarden-documentation[équipe de documentation] 
endif::[]
ifeval::["{build-type}" == "product"]
L' https://github.com/orgs/rancher/teams/docs[équipe de documentation] 
endif::[]
Tout le monde est invité à travailler sur n'importe quel sujet, y compris le rapporteur, mais vous devez vous attribuer le sujet avant de commencer le travail afin d'éviter les doubles emplois.

== Ouverture d'une question

Pour suggérer des améliorations au contenu de la documentation existante ou signaler une erreur, ouvrez un dossier.

* Cliquez sur l'icône GitHub Octocat en haut. Cela vous redirige vers la page
ifeval::["{build-type}" == "community"]
  https://github.com/kubewarden/docs[dépôt de documentation pour {short-project-name}].
endif::[]
ifeval::["{build-type}" == "product"]
  https://github.com/rancher/kubewarden-product-docs[dépôt de documentation pour {short-project-name}].
endif::[]
* Accédez à l'onglet Questions et cliquez sur *Nouvelle question*.
* Décrivez le problème ou la suggestion d'amélioration. Plus il y a de détails, mieux c'est.
* Cliquez sur *Soumettre un nouveau numéro*.
* Après avoir soumis le problème, vous pouvez vous l'attribuer ou attendre qu'un membre de la communauté le prenne en charge. Les membres de l'équipe de documentation et de la communauté peuvent demander des éclaircissements avant d'agir sur votre problème. Vous devriez vérifier activement votre problème ou https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications[activer les notifications GitHub].

== Nouvelles suggestions de contenu

Pour suggérer un nouveau contenu, veuillez déposer un problème en utilisant l'un de ces mécanismes :

* Choisissez une page existante dans la section dans laquelle vous pensez que le contenu a sa place et cliquez sur *Créer une question.* OR
ifeval::["{build-type}" == "community"]
* Naviguez vers https://github.com/kubewarden/docs/issues/new/choose[] GitHub et déposez le problème directement.
endif::[]
ifeval::["{build-type}" == "product"]
* Naviguez vers https://github.com/rancher/kubewarden-product-docs/issues/new/choose[] GitHub et déposez le problème directement.
endif::[]

== Comment faire en sorte que votre contribution compte ?

Aucune contribution n'est trop grande ou trop petite. Toutefois, pour que la communauté en tire le meilleur parti, nous vous demandons de suivre la procédure suivante lorsque vous signalez un problème :

* Concentrez-vous sur une description claire du problème. Les points clés à prendre en considération sont la description des éléments manquants, obsolètes, erronés ou nécessitant une amélioration qualitative et technique.
* Décrire l'impact spécifique du problème sur les utilisateurs.
* Limiter la portée de la question. Si le champ d'application est vaste, décomposez-le en tâches plus petites au sein d'une question. Par exemple, "Création d'un guide de contribution" a une portée très large car il y a plusieurs tâches associées à cette question.
  Cependant, "Corriger une erreur grammaticale sur la page Quickstart" est un problème plus restreint qui ne nécessiterait qu'une seule demande d'extraction.
* Vérifier les questions existantes afin d'éviter les doubles emplois.
* Vérifier s'il existe une demande d'extraction ou un problème. Vérifiez que vous faites référence au problème existant ou à la demande d'extraction dans le problème que vous ouvrez afin de donner un contexte aux contributeurs qui pourraient vouloir travailler dessus.
