= 开放式遥测概念
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

这是对开放式遥测技术最重要概念的总结，应该足以让您入门。如需更详细的介绍，请使用https://opentelemetry.io/docs/concepts/[Open Telemetry 文档]

== 信号

打开遥测功能可识别 3 种遥测信号：

* 痕迹
* 衡量标准
* 日志

目前，SUSE Observability 支持跟踪和度量，未来版本将支持日志。对于 Kubernetes 日志，可以使用xref:/k8s-quick-start-guide.adoc[SUSE Observability 代理]来代替。

=== 痕迹

通过跟踪，我们可以直观地看到请求通过应用程序的路径。一个跟踪由一个或多个跨度组成，共同构成一棵树，一个跟踪可以完全在一个服务内，但也可以跨越多个服务。每个跨度代表请求处理过程中的一个操作，并具有

* 一个名字
* 开始和结束时间，由此可以计算出持续时间
* 地位
* 属性
* 资源属性（见<<_resources,资源）>>
* 活动

跨度属性用于为跨度提供元数据，例如，下订单操作的跨度属性为`orderId` ，HTTP 操作的跨度属性为 HTTP 方法和 URL。

跨度事件可用于表示跨度运行中发生重要事件的时间点。例如，如果跨度失败，可以有一个`exception` 或`error` 事件来捕获错误信息、堆栈跟踪和错误发生的确切时间点。

=== 衡量标准

度量是在运行时捕获的测量结果，它们会导致度量事件。度量指标是应用程序性能和可用性的重要指标，通常用于对中断或性能问题发出警报。衡量标准有

* 一个名字
* 时间戳
* 种
* 属性
* 资源属性（见<<_resources,资源）>>

属性为度量提供元数据。

== 资源

资源是产生遥测数据的实体。资源属性提供了资源的元数据。例如，在 Kubernetes 集群的容器、pod 和命名空间中运行的进程可以拥有所有这些实体的资源属性。

资源属性通常由 SDK 自动分配。不过，建议始终明确设置`service.name` 和`service.namespace` 属性。第一个是服务的逻辑名称，如果不设置，SDK 将设置一个`unknown_service` 值，这样以后就很难在 SUSE Observability 中使用这些数据。命名空间是一种组织服务的便捷方法，尤其是在多个位置运行相同服务的情况下。

== 语义公约

Open Telemetry 为操作和数据定义了通用名称，他们称之为语义约定。语义约定遵循一种命名方案，可实现跨语言、库和代码库的数据处理标准化。所有信号和资源属性都有语义约定。https://opentelemetry.io/docs/specs/semconv/attributes-registry/[Open Telemetry 网站]上为许多不同的平台和操作定义了这些参数。SDK 利用语义约定来分配这些属性，SUSE Observability 也尊重并依赖这些约定，例如识别 Kubernetes 资源。
