ifdef::ss-ff-stackpacks2_enabled[]
= Topologia da OpenTelemetry
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Topologia da OpenTelemetry

{stackstate-product-name} pode derivar automaticamente a topologia do aplicativo e da infraestrutura a partir de dados de telemetria do OpenTelemetry (OTel).
Isso é obtido por meio de mapeamentos de topologia do OpenTelemetry que transformam declarativamente sinais de rastreamento e métricos em componentes de topologia (vértices) e relações (bordas).

== Visão geral

Em um nível mais alto, a geração de topologia do OpenTelemetry funciona da seguinte forma:

* A telemetria OpenTelemetry (métricas e/ou rastreamentos) é recebida pelo Collector.
* O coletor OTel usa um conector de topologia que avalia os mapeamentos configurados em relação à telemetria.
* Quando as condições de mapeamento correspondem à telemetria, são produzidos componentes e/ou relações.
* Esses objetos de topologia são consumidos pelo serviço `+sync+` e mesclados no gráfico de topologia.
* Os mapeamentos são declarativos, baseados em YAML e avaliados continuamente à medida que a telemetria flui pelo sistema.

Sinais atualmente suportados:

* Métricas
* Traços

[NOTE]
====
Ainda não há suporte para a geração de topologia baseada em registro.
====

Para obter mais informações sobre mapeamentos de componentes e relações, consulte a página de xref:/setup/custom-integrations/otelmappings/concepts.adoc[conceitos].

endif::ss-ff-stackpacks2_enabled[]
