= Certificação do provedor 
:revdate: 2025-06-30
:page-revdate: {revdate}

== O que é um provedor certificado?

Como a maioria dos provedores CAPI são projetos upstream mantidos pela comunidade aberta, não há uma maneira segura de garantir que todos os clusters provisionados com um determinado provedor possam ser importados para o Rancher por meio do Turtles. No entanto, implementamos um processo de certificação para os provedores que o são:

* Testado ativamente como parte de nosso conjunto de testes E2E.
* Mantivemos esse conjunto de testes E2E atualizado para validar versões recentes do provedor.

== Certificação de seu provedor personalizado

Além disso, se você for um desenvolvedor de provedores ou simplesmente quiser usar um provedor diferente que não esteja listado como certificado, você tem duas opções:

* Reutilize a suíte Turtles E2E existente para iniciar a solicitação de status de certificação. Informações mais detalhadas podem ser encontradas aqui na seçãoxref:./certification.adoc#_provider_certification_using_turtles_test_suite[Certificação de provedor usando o Turtles Test Suite].
* Use seu próprio pacote de integração para certificar seu provedor. Informações mais detalhadas podem ser encontradas aqui na seçãoxref:./certification.adoc#_certify_provider_with_custom_integration_suite[Certificar provedor com o Custom Integration Suite].

[discrete]
==== *Por que eu gostaria de validar meu provedor?*

O número de provedores de CAPI continua crescendo e a comunidade está criando novos projetos para diferentes hosts de infraestrutura. Essa abertura ajuda a enriquecer o ecossistema do CAPI, mas torna impossível controlar e testar todos os provedores com os quais o Turtles trabalhará em todo o projeto CAPI. Os desenvolvedores do Turtles manterão uma xref:../overview/certified.adoc[lista de provedores certificados] que são ativamente testados e validados por mecanismos de CI, mas essa lista será limitada a provedores importantes e conhecidos. É por isso que incentivamos os usuários de provedores não listados a reutilizar o conjunto de testes do Turtles e validar a integração entre o provedor e o Turtles.

[discrete]
==== *Posso usar o Turtles com um provedor não certificado?*

O Turtles é um projeto que visa ser agnóstico e se integrar a todo o ecossistema CAPI, e você pode usá-lo livremente sem validar nenhum provedor. É provável que você não encontre problemas na maioria dos projetos upstream.

[discrete]
==== *Qual é a diferença entre certificado e suportado?*

Como os provedores CAPI são projetos mantidos pela comunidade Kubernetes, não podemos garantir o suporte a um determinado provedor. É por isso que optamos por nos concentrar na validação constante dos xref:../overview/certified.adoc[Provedores Certificados] e oferecemos aos usuários a possibilidade de integração com o conjunto de testes existente para verificar os provedores de sua escolha.

== Certificação de provedores usando o Turtles Test Suite

O processo de certificação baseia-se na verificação da integração do {product_name} com os provedores de CAPI. Para simplificar essa tarefa, preparamos um teste genérico que valida o provisionamento e a importação de um cluster CAPI downstream.

[TIP]
====
Recomendamos que você consulte este https://github.com/rancher-sandbox/turtles-integration-suite-example[exemplo em] sobre como usar o conjunto de testes do Turtles.
====

=== Teste e certifique seu provedor

A primeira etapa para validar se o seu provedor é compatível com o Turtles e se você pode provisionar clusters CAPI e importá-los para o Rancher por meio do Turtles é integrar-se ao nosso conjunto de testes. Fornecemos um repositório com um https://github.com/rancher-sandbox/turtles-integration-suite-example[exemplo de integração] que você pode usar como referência para sua integração.

O Turtles, como projeto, contém um https://github.com/rancher/turtles/tree/main/test/e2e/suites[número] para verificar diferentes recursos e processos, mas, para a certificação do provedor, exigimos que você execute apenas um teste que use um fluxo do GitOps. O Turtles é um projeto que se integra bem a uma abordagem GitOps para provisionamento de cluster e é por isso que essa é a nossa principal maneira de validar a integração do provedor com o Rancher. A execução do conjunto completo para um determinado provedor de CAPI:

* Crie um cluster de gerenciamento no ambiente desejado.
* Instale o Rancher e o Turtles com todos os pré-requisitos.
* Instale o Gitea.
* Execute o conjunto que criará um repositório git, aplicará o modelo de cluster usando o Fleet e verificará se o cluster foi criado e importado com sucesso no Rancher.

==== Configuração de teste

Para executar o conjunto de testes com êxito, você precisará fornecer diversas variáveis de ambiente. Algumas delas são agnósticas, o que significa que são necessárias para qualquer provedor que você queira testar, mas outras são específicas para o provedor que você está validando. Esteja ciente das especificações específicas do provedor que está sendo testado, como credenciais, pontos de extremidade, etc.

[TIP]
====
Em seguida, recomendamos que você leia o xref:../operator/certificationsuite.adoc[guia do conjunto de testes]
====

== Certificar o provedor com o pacote de integração personalizado

Para certificar seu provedor usando um pacote de integração personalizado, certifique-se de que ele atenda aos seguintes requisitos principais:

=== Requisitos

* O provedor deve ser implantado usando a API `CAPIProvider`.
* Os clusters criados com o provedor devem ser importados com êxito para o Rancher por meio do Turtles.

=== Processo de certificação

1. **Desenvolver uma suíte de integração** 
   * Instale e configure o Rancher e o Turtles.
   * Implantar o provedor CAPI.
   * Provisione um cluster e importe-o para o Rancher.

2. **Executar e validar testes**
   * Assegure-se de que os clusters sejam criados e importados com êxito.

3. **Enviar uma solicitação de certificação**
   * Forneça os resultados dos testes, os registros e as etapas seguidas.
   * Envie um problema do GitHub usando o seguinte https://github.com/rancher/turtles/issues/new?template=certification_request.yaml[modelo].

== Solicitação de certificação

A integração com o conjunto de testes do Turtles e a execução de verificações em seu provedor de interesse são suficientes para validar que ele é compatível com {product_name}. Como não é possível testar continuamente todos os provedores de CAPI, esse fluxo de trabalho de certificação permitirá que você, como usuário, verifique a funcionalidade esperada. No entanto, como não estamos testando ativamente iterações mais recentes do provedor (com versões mais recentes do Turtles), o suporte e a garantia para o provedor em questão são limitados, e você será responsável por validar versões futuras.

Se, depois de executar com êxito as verificações em seu provedor, você quiser solicitar que ele seja adicionado à lista de xref:../overview/certified.adoc[provedores certificados] e incluído no conjunto periódico de E2E do projeto, poderá solicitar a certificação enviando um problema do GitHub usando o https://github.com/rancher/turtles/issues/new?template=certification_request.yaml[modelo]. A comunidade analisará a proposta e determinará a viabilidade de adicionar o provedor à matriz de certificação.
