= Ativação do ClusterClass
:revdate: 2025-06-30
:page-revdate: {revdate}

Nesta seção, abordaremos a ativação do https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/[*ClusterClass*] para um provedor de CAPI.

[TIP]
====
Antes de usar o recurso ClusterClass, estude os documentos do provedor e confirme se o recurso é compatível. Essa documentação inclui uma matriz na seção xref:../overview/certified.adoc[Provedores certificados] com o xref:../overview/certified.adoc#_clusterclass_support_for_certified_providers[status de suporte da topologia de cluster].
====

== Ativar ClusterClass

Para usar o recurso ClusterClass, ele precisa ser ativado para a API principal do Cluster e para qualquer provedor que o suporte. Isso é feito definindo a variável `CLUSTER_TOPOLOGY` como `true`.

O gráfico do {product_name} Helm ativará automaticamente o recurso ao instalar o CAPI. No entanto, ao ativar provedores adicionais, certifique-se de que `CLUSTER_TOPOLOGY` esteja definido na configuração do provedor. O recurso xref:../reference/capiprovider.adoc[CAPIProvider] do Turtles suporta a passagem de parâmetros de instalação para o provedor por meio do site `variables` da seguinte forma:

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: azure
  namespace: capz-system
spec:
  type: infrastructure
  name: azure
  configSecret:
    name: azure-variables
  variables:
    CLUSTER_TOPOLOGY: "true"
    EXP_CLUSTER_RESOURCE_SET: "true"
    EXP_MACHINE_POOL: "true"
    EXP_AKS_RESOURCE_HEALTH: "true"
----

O recurso definido nesse arquivo YAML instalará o CAPZ com suporte para vários recursos, incluindo `CLUSTER_TOPOLOGY`.
