include::partial$variables.adoc[]
= Erstellen einer neuen Validierungsrichtlinie
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Prüfen Sie, ob Sie eine neue Überprüfungsrichtlinie erstellen können, die Pods mit Ablehnungslisten-Labels ablehnt und gleichzeitig die Labels mit vom Benutzer bereitgestellten regulären Ausdrücken überprüft, um die Sicherheit zu gewährleisten.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "go", "Erstellen einer neuen Validierungsrichtlinie"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "Richtlinien in Go schreiben", "neue Validierungsrichtlinie"]
:current-version: {page-origin-branch}

Dieses Tutorial behandelt die Erstellung einer Richtlinie, die die Beschriftungen von Pod-Objekten validiert.

Die Richtlinie sieht vor, dass alle Pods abgelehnt werden, die eine oder mehrere Kennzeichnungen auf der Deny-Liste verwenden.
Die Richtlinie validiert auch bestimmte Bezeichnungen anhand eines vom Benutzer angegebenen regulären Ausdrucks.

Zusammengefasst sollten die Richtlinieneinstellungen wie folgt aussehen:

[subs="+attributes",yaml]
----
# List of labels that cannot be used
denied_labels:
- foo
- bar

# Labels that are validated with user-defined regular expressions
constrained_labels:
  priority: "[123]"
  cost-center: "^cc-\d+"
----

Die Politik lehnt die Schaffung dieses Pods ab:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    foo: hello world
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

Sie lehnt auch die Schaffung dieses Pods ab:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    cost-center: cc-marketing
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

Sie können die Einstellungen der Richtlinie verwenden, um die Verwendung einer Labelspezifikation unabhängig vom Inhalt zu erzwingen:

[subs="+attributes",yaml]
----
constrained_labels:
  mandatory-label: ".*" # <- this label must be present, we don't care about its value
----

== Gerüst für neues politisches Projekt

Sie können ein neues Richtlinienprojekt mit Hilfe deshttps://github.com/kubewarden/go-policy-template[Vorlagen-Repositorys] erstellen.
Wählen Sie die grüne Schaltfläche "Diese Vorlage verwenden" am oberen Rand der Seite und folgen Sie dem Assistenten von GitHub.

Klonen Sie das Repository lokal und setzen Sie die Direktive `module` in der Datei `go.mod` so, dass sie wie folgt aussieht:

[,go]
----
module <path to your repository>
----

[NOTE]
====
Eine echte Richtlinie würde einen Repository-Pfad verwenden, wie `github.com/kubewarden/go-policy-template`.
====


== Prüfung

Wenn die erforderlichen Tools vorhanden sind, verwendet der Befehl `make test` Docker, um ein TinyGo-Compiler-Image zu ziehen und damit die Richtlinienvorlage zu erstellen und zu testen.

Mit dem Standardbefehl `make` wird das Ziel `policy.wasm` erstellt. Dann führt `make test` die definierten Go-Tests aus.
Der Befehl `make e2e-tests` führt Tests mit https://github.com/bats-core/bats-core[] Fledermäusen innerhalb eines {short-project-name} Clusters durch.
Nachdem Sie `go-policy-template` geklont haben, können Sie mit diesen Befehlen überprüfen, ob Sie die Werkzeuge für den Lehrgang zur Verfügung haben.

.Ausgabe der Befehle `make` 
[%collapsible]
======

[subs="+attributes",console]
----
make test
docker run \
        --rm \
        -e GOFLAGS="-buildvcs=false" \
        -v /home/jhk/projects/suse/tmp/go-kw-demo:/src \
        -w /src tinygo/tinygo:0.30.0 \
        tinygo build -o policy.wasm -target=wasi -no-debug .
Unable to find image 'tinygo/tinygo:0.30.0' locally
0.30.0: Pulling from tinygo/tinygo
9aaefb8797c4: Pull complete
24ab7ca26e01: Pull complete
ca4ea8be6361: Pull complete
50380d0859d2: Pull complete
4f4fb700ef54: Pull complete
ea0ddd497f04: Pull complete
01ba28116afb: Pull complete
Digest: sha256:5cbf5e50aec3a00fcff8bb4ae070a07eea8198187a97b21dff6d873d2274ce7a
Status: Downloaded newer image for tinygo/tinygo:0.30.0
go test -v
=== RUN   TestParsingSettingsWithNoValueProvided
--- PASS: TestParsingSettingsWithNoValueProvided (0.00s)
=== RUN   TestIsNameDenied
--- PASS: TestIsNameDenied (0.00s)
=== RUN   TestEmptySettingsLeadsToApproval
NATIVE: |{"level":"debug","message":"validating pod object","name":"test-pod","namespace":"default"}
|
--- PASS: TestEmptySettingsLeadsToApproval (0.00s)
=== RUN   TestApproval
NATIVE: |{"level":"debug","message":"validating pod object","name":"test-pod","namespace":"default"}
|
--- PASS: TestApproval (0.00s)
=== RUN   TestApproveFixture
NATIVE: |{"level":"debug","message":"validating pod object","name":"test-pod","namespace":"default"}
|
--- PASS: TestApproveFixture (0.00s)
=== RUN   TestRejectionBecauseNameIsDenied
NATIVE: |{"level":"debug","message":"validating pod object","name":"test-pod","namespace":"default"}
|
NATIVE: |{"level":"info","message":"rejecting pod object","name":"test-pod","denied_names":"foo,test-pod"}
|
--- PASS: TestRejectionBecauseNameIsDenied (0.00s)
PASS
ok      github.com/kubewarden/go-policy-template        0.004s
----

und

[subs="+attributes",console]
----
make e2e-tests
bats e2e.bats
e2e.bats
 ✓ reject because name is on deny list
 ✓ accept because name is not on the deny list
 ✓ accept because the deny list is empty

3 tests, 0 failures
----

======
