include::partial$variables.adoc[]
= End-to-End-Tests
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Entdecken Sie, wie Sie mit bats und kwctl End-to-End-Tests schreiben und automatisieren können, die gegen das von TinyGo erzeugte WebAssembly-Binary laufen.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "end-to-end-testing"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "end-to-end testing", "golang", "go"]
:sidebar_label: End-to-End-Tests
:sidebar_position: 40
:current-version: {page-origin-branch}

Bislang haben Sie die Richtlinie mit einer Reihe von Go-Unit-Tests getestet.
In diesem Abschnitt wird gezeigt, wie Sie End-to-End-Tests schreiben können, die gegen das von TinyGo erzeugte WebAssembly-Binary laufen.

== Voraussetzungen

Denken Sie daran, dass Sie diese Werkzeuge auf Ihrem Entwicklungsrechner benötigen:

* Docker oder eine andere Container-Engine: Wird zur Erstellung der WebAssembly-Richtlinie verwendet.
Sie werden den Compiler verwenden, der im offiziellen TinyGo-Container-Image enthalten ist.
* https://github.com/bats-core/bats-core[Fledermäuse]:
Wird verwendet, um die Tests zu schreiben und ihre Ausführung zu automatisieren.
* https://github.com/kubewarden/kwctl/releases[`kwctl`]:
CLI-Tool, das von {project-name} bereitgestellt wird, um unter anderem seine Richtlinien außerhalb von Kubernetes auszuführen.
Dies wird in xref:tutorials/testing-policies/index.adoc[diesem Abschnitt] der Dokumentation behandelt.

== Tests schreiben

Sie werdenhttps://github.com/bats-core/bats-core[] bats verwenden, um Ihre Tests zu schreiben und zu automatisieren.
Jeder Test besteht aus den folgenden Schritten:

. Führen Sie die Richtlinie mit `kwctl` aus.
. Führen Sie Assertions gegen die von `kwctl` erzeugte Ausgabe durch.

Alle End-to-End-Tests werden in einer Datei namens `e2e.bats` gespeichert.
Das Projekt Gerüstbau enthält bereits ein Beispiel `e2e.bats`.
Sie müssen den Inhalt ändern, damit er das Verhalten Ihrer Richtlinie widerspiegelt.
Sie können die Inhalte aus der Gerüstdatei entfernen und durch die folgenden Inhalte ersetzen, während Sie dieses Lernprogramm durcharbeiten.

Für die End-to-End-Tests verwenden Sie die gleichen Test-Fixtures-Dateien, die Sie auch für die Go-Unit-Tests verwendet haben.

Der erste Test stellt sicher, dass der Antrag genehmigt wird, wenn keine Einstellungen vorhanden sind:

[,bash]
----
@test "accept when no settings are provided" {
  run kwctl run -r test_data/pod.json policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # request is accepted
  [ $(expr "$output" : '.*"allowed":true.*') -ne 0 ]
}
----

Mit diesem Befehl führen Sie die End-to-End-Tests durch:

[subs="+attributes",console]
----
make e2e-tests
----

Das Ergebnis ist die folgende Ausgabe:

[subs="+attributes",console]
----
bats e2e.bats
 ✓ accept when no settings are provided

1 test, 0 failures
----

Sie sollten einen Test schreiben, der sicherstellt, dass die Anfrage genehmigt wird, wenn eine benutzerdefinierte Einschränkung beachtet wird:

[,bash]
----
@test "accept because label is satisfying a constraint" {
  run kwctl run annotated-policy.wasm \
    -r test_data/pod.json \
    --settings-json '{"constrained_labels": {"cc-center": "\\d+"}}'

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}
----

Als Nächstes können Sie einen Test schreiben, der prüft, ob die Anfrage akzeptiert wird, wenn keines der Labels auf der Ablehnungsliste steht:

[,bash]
----
@test "accept labels are not on deny list" {
  run kwctl run \
    -r test_data/pod.json \
    --settings-json '{"denied_labels": ["foo", "bar"]}' \
    policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ $(expr "$output" : '.*"allowed":true.*') -ne 0 ]
}
----

Sie können die Testabdeckung verbessern, indem Sie einen Test hinzufügen, der eine Anfrage ablehnt, weil eine der Kennzeichnungen auf der Ablehnungsliste steht:

[,bash]
----
@test "reject because label is on deny list" {
  run kwctl run annotated-policy.wasm \
    -r test_data/pod.json \
    --settings-json '{"denied_labels": ["foo", "owner"]}'

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [ $(expr "$output" : ".*Label owner is on the deny list.*") -ne 0 ]
}
----

Der folgende Test stellt sicher, dass eine Anfrage abgelehnt wird, wenn eine ihrer Bezeichnungen nicht der vom Benutzer angegebenen Einschränkung entspricht.

[,bash]
----
@test "reject because label is not satisfying a constraint" {
  run kwctl run annotated-policy.wasm \
    -r test_data/pod.json \
    --settings-json '{"constrained_labels": {"cc-center": "team-\\d+"}}'

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [ $(expr "$output" : ".*The value of cc-center doesn't pass user-defined constraint.*") -ne 0 ]
}
----

Jetzt können Sie sicherstellen, dass die Validierung fehlschlägt, wenn eine der eingeschränkten Bezeichnungen nicht gefunden wird:

[,bash]
----
@test "reject because constrained label is missing" {
  run kwctl run annotated-policy.wasm \
    -r test_data/pod.json \
    --settings-json '{"constrained_labels": {"organization": "\\d+"}}'

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [ $(expr "$output" : ".*Constrained label organization not found inside of Pod.*") -ne 0 ]
}
----

Sie möchten überprüfen, ob die Validierung der Einstellungen korrekt funktioniert.
Sie können dies mit den folgenden Tests tun:

[,bash]
----
@test "fail settings validation because of conflicting labels" {
  run kwctl run \
    -r test_data/pod.json \
    --settings-json '{"denied_labels": ["foo", "cc-center"], "constrained_labels": {"cc-center": "^cc-\\d+$"}}' \
    policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # settings validation failed
  [ $(expr "$output" : ".*Provided settings are not valid: These labels cannot be constrained and denied at the same time: Set{cc-center}.*") -ne 0 ]
}

@test "fail settings validation because of invalid constraint" {
  run kwctl run \
    -r test_data/pod.json \
    --settings-json '{"constrained_labels": {"cc-center": "^cc-[12$"}}' \
    policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # settings validation failed
  [ $(expr "$output" : ".*Provided settings are not valid: error parsing regexp.*") -ne 0 ]
}
----

== Schlussfolgerung

Die acht End-to-End-Tests bieten nun ein gutes Maß an Abdeckung, Sie können sie alle durchführen:

[subs="+attributes",shell]
----
$ make e2e-tests
bats e2e.bats
e2e.bats
 ✓ accept when no settings are provided
 ✓ accept because label is satisfying a constraint
 ✓ accept labels are not on deny list
 ✓ reject because label is on deny list
 ✓ reject because label is not satisfying a constraint
 ✓ reject because constrained label is missing
 ✓ fail settings validation because of conflicting labels
 ✓ fail settings validation because of invalid constraint

8 tests, 0 failures
----
