include::partial$variables.adoc[]
= Protokollierung
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Konfigurieren Sie die Initialisierung des Loggers für die strukturierte Protokollierung in Ihrer Richtlinie mithilfe der Go SDK-Integration des oneLog-Projekts.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "logging"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "golang", "go", "logging"]
:current-version: {page-origin-branch}

Das Go SDK ist in dashttps://github.com/francoispqt/onelog[`onelog`]Projekt integriert, und zwar fast sofort nach dem Auspacken.
// TODO: Last release 2019. Still good?

Das Projekt hat sich für diese Bibliothek entschieden, weil:

* Es funktioniert mit WebAssembly-Binärdateien.
Andere gängige Protokollierungslösungen können nicht für WebAssembly kompiliert werden.
* Es bietet https://github.com/francoispqt/onelog#benchmarks[gute Leistung].
* Es unterstützt eine strukturierte Protokollierung.

== Logger initialisieren

Sie müssen eine Logger-Struktur initialisieren.
Wenn Sie diese Initialisierung in einer globalen Variablen vornehmen, können Sie von den beiden Haupteinstiegspunkten für Richtlinien protokollieren: `validate` und`validate_settings`.

Das Hauptpaket `main.go` enthält eine Initialisierung für den Logger:

[,go]
----
var (
    logWriter = kubewarden.KubewardenLogWriter{}
    logger    = onelog.New(
        &logWriter,
        onelog.ALL, // shortcut for onelog.DEBUG|onelog.INFO|onelog.WARN|onelog.ERROR|onelog.FATAL
    )
)
----

== Verbrauchen des Loggers

Jetzt können Sie das Objekt `logger` verwenden, um sich von jedem Ort aus anzumelden, der für Ihre Richtlinie erforderlich ist:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.Info("validating request")
    // ...
}
----

Sie können eine strukturierte Protokollierung hinzufügen:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.WarnWithFields("logging something important", func(e onelog.Entry) {
        e.String("one_field", "a value")
        e.String("another_field", "another value")
    })
    // ...
}
----

Weitere Informationen finden Sie in derhttps://pkg.go.dev/github.com/francoispqt/onelog?utm_source=godoc[Dokumentation]

Die Richtlinienprotokollierung geht an den Richtlinienauswerter (z. B. `kwctl` oder `policy-server`), der im Namen der Richtlinie protokolliert.
Sie verwenden Mechanismen, die mit anderen Komponenten, die verteiltes Tracing ermöglichen, wiehttps://www.jaegertracing.io/[Jaeger], interoperabel sind.
