include::partial$variables.adoc[]
= Rancherアプリケーションコレクションのイメージを確認する
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Docker Config Secretを使用して、Rancher Application Collectionからイメージを認証およびプルするようにPolicyServersを設定します。
:doc-persona: ["kubewarden-operator"、"kubewarden-integrator"]]。
:doc-topic: ["operator-manual", "rancher", "installation"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "rancher", "application collection", "appco", "signature", "verification", "verify" ]。
:sidebar_label: 画像の検証
:current-version: {page-origin-branch}

このセクションでは、{project-name} を使用してhttps://apps.rancher.io/[、]Rancherからアプリケーションとイメージを検証する方法について説明します。

https://artifacthub.io/packages/kubewarden/verify-image-signatures/verify-image-signatures[Verify Image Signatures] ポリシーを展開し、PolicyServers が Application Collection からイメージの署名レイヤをプルするように構成することで、イメージの検証を実行します。

[IMPORTANT]
====

Application Collectionを利用するには、アクセストークンまたはサービスアカウント認証が必要です。

====


== Rancherアプリケーションコレクションへの認証

https://docs.apps.rancher.io/get-started/authentication/[Application Collection documentation]に従って、アクセストークンを作成し、Docker Config Secretを使用してApplication Collectionレジストリからプルするようにクラスタを設定します：

[subs="+attributes",console]
----
$ kubectl create secret docker-registry application-collection \
  --docker-server=dp.apps.rancher.io \
  --docker-username=<mymail> \
  --docker-password=<mytoken>
----

== PolicyServerのSecretを作成し、Rancher Application Collectionからプルできるようにする。

使用するPolicyServerは、署名を含むイメージレイヤーをプルできるように設定が必要です。

Policy Serversのxref:/howtos/policy-servers/02-private-registry.adoc[プライベートレジストリのHow-toに従って]、*PolicyServer名前空間に*Docker Config Secretを作成します。シークレットをインスタンス化し、`+application-collection+` 。

`+kubewarden+` ネームスペースの下に`+kubewarden-defaults+` Helm チャートと一緒にインストールされた PolicyServer`+default+` の場合は、次のようになります：

[subs="+attributes",console]
----
$ kubectl create secret docker-registry application-collection-kw -n kubewarden \
  --docker-server=dp.apps.rancher.io \
  --docker-username=<mymail> \
  --docker-password=<mytoken>
----

== 新しいシークレットを使用するようにPolicyServersを設定する

`+kubewarden-defaults+` HelmチャートからPolicyServer`+default+` を使用する場合、imagePullSecret`+application-collection-kw+` で構成します。これは同じ名前空間にあり、チャートに以下の値を設定することで実行される：

[subs="+attributes",console]
----
$ helm upgrade -i --wait --namespace kubewarden \
  --create-namespace kubewarden-defaults kubewarden/kubewarden-defaults \
  --reuse-values \
  --set policyServer.imagePullSecret=application-collection-kw
----

他のPolicyServersを使用している場合は、そのPolicyServersのxref:reference/CRDs.adoc#_policyserverspec[`+spec.imagePullSecret+`].シークレットは PolicyServer と同じネームスペースになければなりません。

== ポリシーを適用する

https://artifacthub.io/packages/kubewarden/verify-image-signatures/verify-image-signatures[Verify Image Signatures]ポリシーを利用することで、ClusterAdmissionPolicyを適用できます。このポリシーは、`+dp.apps.rancher.io/containers/*+` からのすべてのコンテナ・イメージをチェックする。ポリシーはOCIレジストリとアーティファクトをサポートする。

`+pubKeys+`配列の Application Collection（執筆時点）のhttps://docs.apps.rancher.io/howto-guides/verify-signatures-with-kubewarden/[公開鍵] を使ってポリシー設定を行うことができます。

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    artifacthub/pkg: verify-image-signatures/verify-image-signatures/0.2.9
  name: check-appcollection-signatures
spec:
  backgroundAudit: true
  mode: protect
  module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.9
  mutating: true
  policyServer: default
  # On first policy call, the policy-server downloads the image layers to
  # verify the signatures. Later on it's cached. It may be useful to increase
  # this timeout:
  timeoutSeconds: 30 # default 10 seconds.
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["replicationcontrollers"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["batch"]
      apiVersions: ["v1"]
      resources: ["jobs", "cronjobs"]
      operations: ["CREATE", "UPDATE"]
  settings:
    modifyImagesWithDigest: true
    rule: PublicKey
    signatures:
      - image: dp.apps.rancher.io/containers/*
        pubKeys:
          # Note: this array constitutes an AND in validation, not an OR.
          - |-
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA02FtEt5gBywiyxbmkVsb
            CujcBg5lur0kpEbfDk10gCcs9shVEqEO3ZsOXHursgoaDAWqdPtsYhsgczGeJz9w
            Aw+r6BuRV8YOkE37A8s/7IOQUW0tlqtnt11OKhIiZ9+e5l3ed2H1ymKQO3dgreSy
            rShqYdA3hrItswyp41ApF6zhjSPlR6lAmq3X4wMYLAPptmzfxigTnR4hxB5UNPhs
            i2qA4vLrUM/i+NohECuLr1EAymvupH26HLEdM+eZnlQn+WbhIP5Grc4ba7XrBv7K
            kywgTC7CxkiJZR0mUcUD2wTX/Je8Ewj6oPSalx09e2jtzvmU5Kr9XUyMF7Zsj5CA
            IwIDAQAB
            -----END PUBLIC KEY-----
EOF
----

[subs="+attributes",console]
----
$ kubectl apply -f mypolicy.yml
$ kubectl get admissionpolicies -n default # wait for status active
----

これをテストするには、Application Collectionから署名付きイメージでPodをデプロイします：

[subs="+attributes",console]
----
$ kubectl run nginx --image [dp.apps.rancher.io/containers/nginx:1.24.0](http://dp.apps.rancher.io/containers/nginx:1.24.0) --overrides='{"spec": {"imagePullSecrets":[{"name": "application-collection"}]}}'
 pod/nginx created
----

ポリシーサーバPodのログを調べて、検証が行われたことを確認することができます。
