include::partial$variables.adoc[]
= Introduction à CEL
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Découvrez le CEL (Computation Expression Language), un langage d'expression rapide, portable et sûr conçu pour les règles de validation Kubernetes et les extensions de l'API Kubernetes.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "introduction"].
:current-version: {page-origin-branch}

Le https://cel.dev[langage d'expression commun (CEL)] est un langage d'expression à usage général conçu pour être rapide, portable et sûr à l'exécution. Le langage CEL est sûr pour la mémoire, sans effets secondaires, terminable (les programmes ne peuvent pas tourner en boucle indéfiniment), et fortement et dynamiquement typé. Vous pouvez en savoir plus sur CEL à l'https://cel.dev[adresse], et le mettre en pratique à l'adresse https://playcel.undistro.io[CEL playground].

== CEL dans Kubernetes

CEL a été choisi comme langage pour les règles de validation de Kubernetes, car les expressions CEL peuvent être facilement intégrées dans les schémas CRD, et compilées et vérifiées en amont (lors de la création et de la mise à jour des CRD). Pour ces raisons et ses caractéristiques générales, c'est un candidat parfait pour étendre l'API Kubernetes.

Marqué comme stable avec Kubernetes 1.30, on peut utiliser CEL surhttps://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy[ValidatingAdmissionPolicies]et d'autres règles de validation. Pour plus d'informations, consultez la documentation de Kuberneteshttps://kubernetes.io/docs/reference/using-api/cel[ici.]

=== Bibliothèques de fonctions Kubernetes

Les règles de validation de Kubernetes CEL ont accès à plusieurs bibliothèques de fonctions :

* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#list-of-standard-definitions[Fonctions standard du CEL]
* https://github.com/google/cel-spec/blob/v0.7.0/doc/langdef.md#macros[Macros standard CEL]
* https://pkg.go.dev/github.com/google/cel-go/ext#Strings[Bibliothèque de fonctions de chaînes de caractères étendue CEL]
* https://kubernetes.io/docs/reference/using-api/cel/#kubernetes-cel-libraries[Bibliothèques d'extension Kubernetes CEL], avec des fonctions supplémentaires pour les listes, les regex, les URL, les autorisateurs, les quantités, les types optionnels, les comparaisons numériques, etc.

== CEL sur {project-name}: `+cel-policy+`

{short-project-name} fournit https://github.com/kubewarden/cel-policy[cel-policy].
Il s'agit d'une politique qui construit et regroupe l'interpréteur en amonthttps://pkg.go.dev/github.com/google/cel-go[cel-go], ainsi que les différentes bibliothèques énumérées ci-dessus et disponibles pour CEL dans Kubernetes à partir de`+apiextensions-apiserver+`.

En outre, `+cel-policy+` comprend une *bibliothèque d'extension CEL{short-project-name} * qui expose les capacités de l'hôte{short-project-name}'s https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[en tant que CEL natif] :

* Vérification Sigstore
* Interaction avec l'OCI
* Fonctions cryptographiques
* Fonctionnement du réseau
* Accès aux ressources Kubernetes

Cela signifie que `+cel-policy+` est un surensemble de Kubernetes CEL, et qu'il est rétrocompatible. On peut réutiliser le CEL écrit pour vanilla Kubernetes, et/ou utiliser les fonctionnalités ajoutées par {short-project-name}.

Le site `+cel-policy+` est livré compilé et se comporte comme un interprète CEL. Les utilisateurs de la politique transmettent les expressions CEL souhaitées à l'adresse `+spec.settings+` de la politique d'admission (de groupe) et, grâce aux caractéristiques de la CEL, l'expression est compilée et son exactitude est vérifiée lors de la création ou de la mise à jour de la politique d'admission (de groupe). Cela signifie qu'il n'est pas nécessaire de créer des versions personnalisées du site`+cel-policy+`.

=== Avantages de {short-project-name}'s `+cel-policy+` par rapport à ValidatingAdmissionPolicies

Le site {short-project-name} `+cel-policy+`:

* Son code CEL est rétrocompatible avec celui de ValidatingAdmissionPolicies.
* Contrairement à ValidatingAdmissionPolicies, il n'a pas besoin d'une liaison telle que ValidatingAdmissionPolicyBinding, car celle-ci est incluse dans les définitions de {short-project-name}'s (Cluster)Admissionpolicies.
* Peut être déployé dans des clusters qui ne prennent pas en charge ValidatingAdmissionPolicies.
* Est sensible au contexte et utilise les autorisations à grain fin de {short-project-name} pour la xref:../../../reference/spec/05-context-aware-policies.adoc[prise en compte du contexte].
* Est déployé en tant que (Cluster)AdmissionPolicy.
* Bénéficie de la traçabilité et de la télémétrie de {short-project-name} sur les politiques.
* Il sera pris en compte par le scanner d'audit.
* Peut être développé et testé en dehors du cluster grâce à kwctl.
