include::partial$variables.adoc[]
= Pruebas para autores de políticas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprenda cómo probar autores de políticas con kwctl, ya sea usando bats o pruebas estándar, específicamente para políticas {project-name} en Wasm.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["testing-policies", "policy-authors"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "policy testing", "policy author", "rust", "go", "assemblyscript", "development environment"]
:current-version: {page-origin-branch}

{project-name} son programas normales compilados como WebAssembly (Wasm).
Como con cualquier tipo de programa, es importante una buena cobertura de las pruebas.

Los autores de las políticas pueden utilizar sus entornos de desarrollo favoritos.
Puede utilizar herramientas conocidas y marcos de pruebas para verificar el desarrollo.

Estas políticas {short-project-name} son ejemplos escritos enxref:tutorials/writing-policies/rust/01-intro-rust.adoc[Rust] yxref:tutorials/writing-policies/go/01-intro-go.adoc[Go]:

* https://github.com/kubewarden/psp-apparmor[psp-apparmor]
* https://github.com/kubewarden/ingress-policy[política de entrada]

Disponen de conjuntos de pruebas que utilizan pruebas estándar para sus entornos de desarrollo.

Las políticas utilizan GitHub Acciones para sus tuberías de CI.

== Pruebas de extremo a extremo

También puede escribir pruebas que se ejecuten contra el binario Wasm que contiene su política.
Para hacerlo sin tener que desplegar un clúster Kubernetes puedes utilizar estas herramientas:

* https://github.com/bats-core/bats-core[bats]: es escribir pruebas y automatizar su ejecución.
* https://github.com/kubewarden/kwctl[`+kwctl+`]: {short-project-name} herramienta CLI por defecto que le ayuda con las operaciones relacionadas con las políticas; extraer, inspeccionar, anotar, empujar y ejecutar.

Para utilizar `+kwctl run+` necesita lo siguiente:

. La referencia del archivo binario Wasm de la política a ejecutar.
La política {short-project-name} se puede cargar desde:
 ** el sistema de archivos local (`+file://+`)
 ** un servidor HTTP(s) (`+https://+`
 ** un registro OCI (`+registry://+`).
. El objeto de solicitud de admisión que se va a comprobar.
Se da a través del argumento `+--request-path+`, o en `+stdin+` ajustando `+--request-path+` a `+-+`.
. La configuración de la política para el tiempo de ejecución como un JSON en línea a través de `+--settings-json+` bandera.
O un archivo JSON, o YAML, cargado desde el sistema de archivos a través de `+--settings-path+`.

Después de la prueba `+kwctl+`, imprime el objeto `+ValidationResponse+` en la salida estándar.

Así es como se utiliza `+kwctl+` para probar el binario Wasm del https://github.com/kubewarden/ingress-policy[`+ingress-policy+`] mencionado anteriormente:

[subs="+attributes",console]
----
$ curl https://raw.githubusercontent.com/kubewarden/ingress-policy/v0.1.8/test_data/ingress-wildcard.json 2> /dev/null | \
    kwctl run \
        --settings-json '{"allowPorts": [80], "denyPorts": [3000]}' \
        --request-path - \
        registry://ghcr.io/kubewarden/policies/ingress:v0.1.8 | jq
----

Puede descargar los binarios precompilados de `+kwctl+`https://github.com/kubewarden/kwctl/releases[ aquí].

Utilizando `+bats+` puede escribir una prueba que ejecute este comando y busque los resultados esperados:

.Una prueba de murciélagos
[%collapsible]
======

[,bash]
----
@test "all is good" {
  run kwctl run \
    --request-path test_data/ingress-wildcard.json \
    --settings-json '{"allowPorts": [80], "denyPorts": [3000]}' \
    ingress-policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # settings validation passed
  [[ "$output" == *"valid: true"* ]]

  # request accepted
  [[ "$output" == *"allowed: true"* ]]
}
----

======

Puede poner el código en un archivo, `+e2e.bats+`, por ejemplo, y luego invocar `+bats+` mediante:

[subs="+attributes",console]
----
$ bats e2e.bats
 ✓ all is good

1 tests, 0 failures
----

xref:tutorials/writing-policies/go/05-e2e-tests.adoc[Esta]sección de la documentación contiene más información sobre cómo escribir pruebas de extremo a extremo de sus políticas.
