= k3s 代理
:page-languages: [EN, JA, KO, ZH]
:revdate: 2025-01-15
:page-revdate: {revdate}

在本节中，您将学习如何配置 K3s 代理。

请注意，服务器也运行代理，因此本页列出的所有标记也适用于服务器。

选项在本页中以 CLI 标志的形式记录，但也可以作为配置文件选项传递。有关使用 YAML 配置文件的更多信息，请参阅xref:installation/configuration.adoc#_configuration_file[配置文件]文档。

== 记录

|===
| 旗帜 | 默认值 | 说明

| `-v` 价值
| 0
| 日志级别冗余度的编号

| `--vmodule` 价值
| N/A
| 以逗号分隔的文件过滤日志 FILE_PATTERN=LOG_LEVEL 设置列表

| `--log value, -l` 价值
| N/A
| 记录到文件

| `--alsologtostderr`
| N/A
| 将日志记录到标准错误和文件中（如果已设置）
|===

== 集群选项

|===
| 旗帜 | 环境变量 | 说明

| `--token value, -t` 价值
| `K3S_TOKEN`
| 用于身份验证的令牌

| `--token-file` 价值
| `K3S_TOKEN_FILE`
| 用于身份验证的令牌文件

| `--server value, -s` 价值
| `K3S_URL`
| 要连接的服务器
|===

== 听众

|===
| 旗帜 |  默认值 | 说明
| `--bind-address`
| 0.0.0.0
| k3s 绑定地址
|===

== 数据

|===
| 旗帜 | 默认值 | 说明

| `--data-dir value, -d` 价值
| "/var/lib/rancher/k3s"
| 文件夹保持状态
|===

== 节点

|===
| 旗帜 | 环境变量 | 说明

| `--node-name` 价值
| `K3S_NODE_NAME`
| 节点名称

| `--with-node-id`
| N/A
| 将 id 添加到节点名称中

| `--node-label` 价值
| N/A
| 使用标签集注册和启动 kubelet

| `--node-taint` 价值
| N/A
| 使用污点集注册 kubelet

| `--protect-kernel-defaults`
| N/A
| 内核调整行为如果设置，则在内核可调性与 kubelet 默认值不同时出错。

| `--selinux`
| `K3S_SELINUX`
| 在 containerd 中启用 SELinux

| `--lb-server-port` 价值
| `K3S_LB_SERVER_PORT`
| 监控客户端负载平衡器的本地端口。如果监控程序和 apiserver 未位于同一地点，则 apiserver 客户端负载平衡器也将使用比该端口小 1 的额外端口。(默认值6444)
|===

== 运行时间

|===
| 旗帜 | 默认值 | 说明

| `--container-runtime-endpoint`
| N/A
| 禁用嵌入式 containerd 并使用给定路径下的 CRI 套接字；与--docker 一起使用时，设置 docker 套接字路径

| `--default-runtime`
| N/A
| 在 containerd 中设置默认运行时

| `--image-service-endpoint`
| N/A
| 禁用嵌入式 containerd 映像服务，并使用给定路径下的远程映像服务套接字。如果未指定，默认为--container-runtime-endpoint。

| `--pause-image` 价值
| "docker.io/rancher/pause:3.1"
| 为 containerd 或 docker 沙箱定制暂停镜像

| `--private-registry` 价值
| "/etc/rancher/k3s/registries.yaml"
| 专用注册表配置文件
|===

== 联网

|===
| 旗帜 | 环境变量 | 说明

| `--node-ip value, -i` 价值
| N/A
| 为节点做广告的 IP 地址

| `--node-external-ip` 价值
| N/A
| 为节点做广告的外部 IP 地址

| `--node-internal-dns`
| N/A
| 内部 DNS 地址，为节点

| `--node-external-dns`
| N/A
| 节点的外部 DNS 地址

| `--resolv-conf` 价值
| `K3S_RESOLV_CONF`
| Kubelet resolv.conf 文件

| `--flannel-iface` 价值
| N/A
| 覆盖默认通道接口

| `--flannel-conf` 价值
| N/A
| 覆盖默认法兰绒配置文件

| `--flannel-cni-conf` 价值
| N/A
| 覆盖默认的法兰绒 cni 配置文件
|===

== 定制旗帜

|===
| 旗帜 | 说明

| `--kubelet-arg` 价值
| 为库伯勒工艺定制的旗帜

| `--kube-proxy-arg` 价值
| 为 kube-proxy 进程定制的标志
|===

== 实验性

|===
| 旗帜 | 说明

| `--rootless`
| 无根运行

| `--docker`
| 使用 cri-dockerd 代替 containerd

| `--enable-pprof`
| 在监控端口上启用 pprof 端点

| `--prefer-bundled-bin`
| 优先选择捆绑的用户空间二进制文件，而不是主机二进制文件

| `--disable-default-registry-endpoint`
| 请参阅xref:installation/private-registry.adoc#_default_endpoint_fallback["默认端点回退]"。

| `--vpn-auth`
| 请参阅xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental["与 Tailscale VPN 提供商集成]"。 

| `--vpn-auth-file`
| 请参阅xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental["与 Tailscale VPN 提供商集成]"。
|===

== 已停用

|===
| 旗帜 | 环境变量 | 说明

| `--no-flannel`
| N/A
| 使用 `--flannel-backend=none`

| `--cluster-secret` 价值
| `K3S_CLUSTER_SECRET`
| 使用 `--token`
|===

[#_node_labels_and_taints_for_agents]
== 节点标签和代理污点

K3s 代理可使用`--node-label` 和`--node-taint` 选项进行配置，这两个选项可为 kubelet 添加标签和污点。这两个选项只能在注册时添加标签和/或污点，因此只能添加一次，之后就不能再通过运行 K3s 命令进行更改。

下面的示例展示了如何添加标签和污点：

[,bash]
----
     --node-label foo=bar \
     --node-label hello=world \
     --node-taint key1=value1:NoExecute
----

如果要在节点注册后更改节点标签和污点，应使用`kubectl` 。有关如何添加https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[标签] 污点和https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#add-a-label-to-a-node[] 节点的详情，请参阅 Kubernetes 官方文档。

== K3s Agent CLI 帮助

____
如果一个选项出现在下面的括号中，例如`[$K3S_URL]` ，则表示该选项可以作为该名称的环境变量传入。
____

[,bash]
----
NAME:
   k3s agent - Run node agent

USAGE:
   k3s agent [OPTIONS]

OPTIONS:
   --config FILE, -c FILE                     (config) Load configuration from FILE (default: "/etc/rancher/k3s/config.yaml") [$K3S_CONFIG_FILE]
   --debug                                    (logging) Turn on debug logs [$K3S_DEBUG]
   -v value                                   (logging) Number for the log level verbosity (default: 0)
   --vmodule value                            (logging) Comma-separated list of FILE_PATTERN=LOG_LEVEL settings for file-filtered logging
   --log value, -l value                      (logging) Log to file
   --alsologtostderr                          (logging) Log to standard error as well as file (if set)
   --token value, -t value                    (cluster) Token to use for authentication [$K3S_TOKEN]
   --token-file value                         (cluster) Token file to use for authentication [$K3S_TOKEN_FILE]
   --server value, -s value                   (cluster) Server to connect to [$K3S_URL]
   --data-dir value, -d value                 (agent/data) Folder to hold state (default: "/var/lib/rancher/k3s") [$K3S_DATA_DIR]
   --node-name value                          (agent/node) Node name [$K3S_NODE_NAME]
   --with-node-id                             (agent/node) Append id to node name
   --node-label value                         (agent/node) Registering and starting kubelet with set of labels
   --node-taint value                         (agent/node) Registering kubelet with set of taints
   --image-credential-provider-bin-dir value  (agent/node) The path to the directory where credential provider plugin binaries are located (default: "/var/lib/rancher/credentialprovider/bin")
   --image-credential-provider-config value   (agent/node) The path to the credential provider plugin config file (default: "/var/lib/rancher/credentialprovider/config.yaml")
   --selinux                                  (agent/node) Enable SELinux in containerd [$K3S_SELINUX]
   --lb-server-port value                     (agent/node) Local port for supervisor client load-balancer. If the supervisor and apiserver are not colocated an additional port 1 less than this port will also be used for the apiserver client load-balancer. (default: 6444) [$K3S_LB_SERVER_PORT]
   --protect-kernel-defaults                  (agent/node) Kernel tuning behavior. If set, error if kernel tunables are different than kubelet defaults.
   --container-runtime-endpoint value         (agent/runtime) Disable embedded containerd and use the CRI socket at the given path; when used with --docker this sets the docker socket path
   --default-runtime value                    (agent/runtime) Set the default runtime in containerd
   --image-service-endpoint value             (agent/runtime) Disable embedded containerd image service and use remote image service socket at the given path. If not specified, defaults to --container-runtime-endpoint.
   --pause-image value                        (agent/runtime) Customized pause image for containerd or docker sandbox (default: "rancher/mirrored-pause:3.6")
   --snapshotter value                        (agent/runtime) Override default containerd snapshotter (default: "overlayfs")
   --private-registry value                   (agent/runtime) Private registry configuration file (default: "/etc/rancher/k3s/registries.yaml")
   --disable-default-registry-endpoint        (agent/containerd) Disables containerd fallback default registry endpoint when a mirror is configured for that registry
   --nonroot-devices                          (agent/containerd) Allows non-root pods to access devices by setting device_ownership_from_security_context=true in the containerd CRI config
   --node-ip value, -i value                  (agent/networking) IPv4/IPv6 addresses to advertise for node
   --bind-address value                       (listener) k3s bind address (default: 0.0.0.0)
   --node-external-ip value                   (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
   --node-internal-dns value                  (agent/networking) internal DNS addresses to advertise for node
   --node-external-dns value                  (agent/networking) external DNS addresses to advertise for node
   --resolv-conf value                        (agent/networking) Kubelet resolv.conf file [$K3S_RESOLV_CONF]
   --flannel-iface value                      (agent/networking) Override default flannel interface
   --flannel-conf value                       (agent/networking) Override default flannel config file
   --flannel-cni-conf value                   (agent/networking) Override default flannel cni config file
   --kubelet-arg value                        (agent/flags) Customized flag for kubelet process
   --kube-proxy-arg value                     (agent/flags) Customized flag for kube-proxy process
   --enable-pprof                             (experimental) Enable pprof endpoint on supervisor port
   --rootless                                 (experimental) Run rootless
   --prefer-bundled-bin                       (experimental) Prefer bundled userspace binaries over host binaries
   --docker                                   (agent/runtime) (experimental) Use cri-dockerd instead of containerd
   --vpn-auth value                           (agent/networking) (experimental) Credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH]
   --vpn-auth-file value                      (agent/networking) (experimental) File containing credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH_FILE]
   --disable-apiserver-lb                     (agent/networking) (experimental) Disable the agent client-side load-balancer and connect directly to the configured server address
----
