= k3s server
:page-languages: [EN, JA, KO, ZH]
:revdate: 2025-05-26
:page-revdate: {revdate}

在本节中，您将学习如何配置 K3s 服务器。

请注意，服务器也运行代理，因此xref:cli/agent.adoc[`k3s agent` 文档]中列出的所有配置选项在服务器上也同样支持。

选项在本页中以 CLI 标志的形式记录，但也可以作为配置文件选项传递。有关使用 YAML 配置文件的更多信息，请参阅xref:installation/configuration.adoc#_configuration_file[配置文件]文档。

== 关键配置值

群集中所有服务器上的以下选项必须设置为相同值。否则，在使用嵌入式 etcd 时，会导致新服务器无法加入群集；在使用外部数据存储时，会导致群集运行不正确。

* `--agent-token`
* `--cluster-cidr`
* `--cluster-dns`
* `--cluster-domain`
* `--disable-cloud-controller`
* `--disable-helm-controller`
* `--disable-network-policy`
* `--disable=servicelb` _注：其他打包组件可按服务器禁用_
* `--egress-selector-mode`
* `--embedded-registry`
* `--flannel-backend`
* `--flannel-external-ip`
* `--flannel-ipv6-masq`
* `--secrets-encryption`
* `--secrets-encryption-provider`
* `--service-cidr`

== 常用选项

=== 数据库

|===
| 旗帜 | 环境变量 | 默认值 | 说明

| `--datastore-endpoint` 价值
| `K3S_DATASTORE_ENDPOINT`
|
| 指定 etcd、NATS、MySQL、Postgres 或 SQLite 数据源名称

| `--datastore-cafile` 价值
| `K3S_DATASTORE_CAFILE`
|
| 用于确保数据存储后端通信安全的 TLS 证书授权文件

| `--datastore-certfile` 价值
| `K3S_DATASTORE_CERTFILE`
|
| 用于确保数据存储后端通信安全的 TLS 认证文件

| `--datastore-keyfile` 价值
| `K3S_DATASTORE_KEYFILE`
|
| 用于确保数据存储后端通信安全的 TLS 密钥文件

| `--etcd-expose-metrics`
|
| 错误
| 在客户端界面公开 etcd 指标

| `--etcd-disable-snapshots`
|
| 错误
| 禁用自动 etcd 快照

| `--etcd-snapshot-name` 价值
|
| "etcd-snapshot-<unix-timestamp>"
| 设置 etcd 快照的基本名称。

| `--etcd-snapshot-schedule-cron` 价值
|
| "0 */12 * * *"
| 以 cron 规格表示的快照间隔时间，例如每 5 小时一次 '0 */5 _ * _'

| `--etcd-snapshot-retention` 价值
|
| 5
| 要保留的快照数量

| `--etcd-snapshot-dir` 价值
|
| ${data-dir}/db/snapshots
| 保存数据库快照的目录

| `--etcd-s3`
|
|
| 启用备份到 S3

| `--etcd-s3-endpoint` 价值
|
| "s3.amazonaws.com"
| S3 端点 url

| `--etcd-s3-endpoint-ca` 价值
|
|
| 连接到 S3 端点的 S3 自定义 CA 证书

| `--etcd-s3-skip-ssl-verify`
|
|
| 禁用 S3 SSL 证书验证

| `--etcd-s3-access-key` 价值
| `AWS_ACCESS_KEY_ID`
|
| S3 访问密钥

| `--etcd-s3-secret-key` 价值
| `AWS_SECRET_ACCESS_KEY`
|
| S3 密钥

| `--etcd-s3-bucket` 价值
|
|
| S3 桶名称

| `--etcd-s3-region` 价值
|
| "us-east-1"
| S3 区域/邮筒位置（可选）

| `--etcd-s3-folder` 价值
|
|
| S3 文件夹

| `--etcd-s3-proxy`
| 
| 
| 连接 S3 时使用的代理服务器，覆盖任何与代理相关的环境变量

| `--etcd-s3-config-secret`
| 
| 
| 如果启用了 etcd-s3，且未设置其他 etcd-s3 选项，用于配置 S3 的 kube-system 命名空间中的密文名称


| `--etcd-s3-insecure`
|
|
| 禁用通过 HTTPS 的 S3

| `--etcd-s3-timeout` 价值
|
| 5m0s
| S3 超时（默认值：5m0s)
|===

[#_cluster_options]
=== 集群选项

|===
| 旗帜 | 环境变量 | 说明

| `--token` 值，`-t` 值
| `K3S_TOKEN`
| 用于将服务器或代理加入群集的共享密文

| `--token-file` 价值
| `K3S_TOKEN_FILE`
| 包含群组机密/令牌的文件

| `--agent-token` 价值
| `K3S_AGENT_TOKEN`
| 共享秘密用于将代理加入群集，但不包括服务器

| `--agent-token-file` 价值
| `K3S_AGENT_TOKEN_FILE`
| 包含特工机密的文件

| `--server` 价值
| `K3S_URL`
| 连接的服务器，用于加入群集

| `--cluster-init`
| `K3S_CLUSTER_INIT`
| 使用嵌入式 Etcd 初始化新群集

| `--cluster-reset`
| `K3S_CLUSTER_RESET`
| 忘掉所有同行，成为新群集的唯一成员
|===

=== 管理 Kubeconfig 选项

|===
| 旗帜 | 环境变量 | 说明

| `--write-kubeconfig value, -o` 价值
| `K3S_KUBECONFIG_OUTPUT`
| 将管理员客户端的 kubeconfig 写入该文件

| `--write-kubeconfig-mode` 价值
| `K3S_KUBECONFIG_MODE`
| 使用此https://en.wikipedia.org/wiki/Chmod[模式]写入 kubeconfig。kubeconfig 文件由 root 拥有，默认模式为 600。将模式更改为 644 后，主机上的其他非特权用户就可以读取它。

| `--write-kubeconfig-group` 价值
| `K3S_KUBECONFIG_GROUP`
| 写入 kubeconfig 组。结合`--write-kubeconfig-mode` ，它将允许 k3s 管理员访问 kubeconfig 文件，但保持该文件为 root 所有。
|===

== 高级选项

=== 记录

|===
| 旗帜 | 默认值 | 说明

| `--debug`
| N/A
| 打开调试日志

| `-v` 价值
| 0
| 日志级别冗余度的编号

| `--vmodule` 价值
| N/A
| 以逗号分隔的文件过滤日志 FILE_PATTERN=LOG_LEVEL 设置列表

| `--log value, -l` 价值
| N/A
| 记录到文件

| `--alsologtostderr`
| N/A
| 将日志记录到标准错误和文件中（如果已设置）
|===

=== 听众

|===
| 旗帜 | 默认值 | 说明

| `--bind-address` 价值
| 0.0.0.0
| k3s 绑定地址

| `--https-listen-port` 价值
| 6443
| HTTPS 侦听端口

| `--advertise-address` 价值
| node-external-ip/node-ip
| apiserver 为其服务端点广告的 IPv4/IPv6 地址 +
请注意，主`service-cidr` IP 范围必须与广告地址属于同一地址系列。

| `--advertise-port` 价值
| listen-port/0
| apiserver 用于向群集成员发布广告的端口

| `--tls-san` 价值
| N/A
| 在 TLS 证书上添加其他主机名或 IPv4/IPv6 地址作为主题替代名称

| `--tls-san-security`
| true
| 拒绝添加与 kubernetes apiserver 服务、服务器节点或 tls-san 选项值无关的主题替代名称，从而保护服务器 TLS 证书 
|===

=== 数据

|===
| 旗帜 | 默认值 | 说明

| `--data-dir value, -d` 价值
| `/var/lib/rancher/k3s` 或`${HOME}/.rancher/k3s` （如果不是根用户
| 文件夹保持状态
|===

=== 秘密加密

|===
| 旗帜 | 默认值 | 说明

| `--secrets-encryption`
| 错误
| 启用静态密文加密

| `--secrets-encryption-provider`
| aescbc
| 使用的加密提供商
|===

=== 联网

|===
| 旗帜 | 默认值 | 说明

| `--cluster-cidr` 价值
| "10.42.0.0/16"
| 用于 pod IP 的 IPv4/IPv6 网络 CIDR

| `--service-cidr` 价值
| "10.43.0.0/16"
| 用于服务 IP 的 IPv4/IPv6 网络 CIDR

| `--service-node-port-range` 价值
| "30000-32767"
| 为具有 NodePort 可见性的服务预留的端口范围

| `--cluster-dns` 价值
| "10.43.0.10"
| 用于 coredns 服务的 IPv4 群集 IP。应在服务-cidr 范围内

| `--cluster-domain` 价值
| "cluster.local"
| 集群域

| `--flannel-backend` 价值
| "vxlan"
| 无"、"vxlan"、"ipsec"（已废弃）、"host-gw"、"wireguard-native "或 "wireguard"（已废弃）中的一个

| `--flannel-ipv6-masq`
| "N/A"
| 为 pod 启用 IPv6 伪装

| `--flannel-external-ip`
| "N/A"
| 为通道流量使用节点外部 IP 地址

| `--servicelb-namespace` 价值
| "kube-system"
| servicelb 组件 pod 的名称空间

| `--egress-selector-mode` 价值
| "agent"
a| 必须具备以下条件之一

* 残疾人：apiserver 不使用代理隧道与节点通信。要求服务器运行代理，并与代理上的 kubelet 直接连接，否则 apiserver 将无法访问服务端点或执行 kubectl 执行和 kubectl 日志。
* 代理：apiserver 使用代理隧道与节点通信。节点允许从环回地址进行隧道连接。要求服务器也运行代理，否则 apiserver 将无法访问服务端点。k3s 的历史默认值。
* 荚：apiserver 使用代理隧道与节点和服务端点通信，通过观察节点将端点连接路由到正确的代理。节点允许从环回地址或分配给其节点的 CIDR 进行隧道连接。
* 群集：apiserver 使用代理隧道与节点和服务端点通信，通过观察端点将端点连接路由到正确的代理。节点允许从环回地址或配置的群集 CIDR 范围进行隧道连接。
|===

=== 存储类

|===
| 旗帜 | 说明

| `--default-local-storage-path` 价值
| 本地供应器存储类的默认本地存储路径
|===

=== Kubernetes 组件

|===
| 旗帜 | 说明

| `--disable` 价值
| 请参阅xref:installation/packaged-components.adoc#_using_the_disable_flag["使用`--disable` 标志]"。

| `--disable-scheduler`
| 禁用 Kubernetes 默认调度程序

| `--disable-cloud-controller`
| 禁用 k3s 默认云控制器管理器

| `--disable-kube-proxy`
| 禁用运行中的 kube-proxy

| `--disable-network-policy`
| 禁用 k3s 默认网络策略控制器

| `--disable-helm-controller`
| 禁用 Helm 控制器
|===

=== 为 Kubernetes 进程定制标志

|===
| 旗帜 | 说明

| `--etcd-arg` 价值
| 为 etcd 进程定制的标志

| `--kube-apiserver-arg` 价值
| 为 kube-apiserver 进程定制的旗帜

| `--kube-scheduler-arg` 价值
| 为 kube-scheduler 进程定制的标记

| `--kube-controller-manager-arg` 价值
| 为 kube-controller-manager 进程定制的标记

| `--kube-cloud-controller-manager-arg` 价值
| 为 kube-cloud-controller-manager 进程定制的标记

| `--kubelet-arg` 价值
| 为库伯勒工艺定制的旗帜

| `--kube-proxy-arg` 价值
| 为 kube-proxy 进程定制的标志
|===

=== 实验选项

|===
| 旗帜 | 说明

| `--rootless`
| 无根运行

| `--enable-pprof`
| 在监控端口上启用 pprof 端点

| `--docker`
| 使用 cri-dockerd 代替 containerd

| `--prefer-bundled-bin`
| 优先选择捆绑的用户空间二进制文件，而不是主机二进制文件

| `--disable-agent`
| 请参阅xref:advanced.adoc#_running_agentless_servers_experimental["运行无代理服务器]"。

| `--embedded-registry`
| 请参阅xref:installation/registry-mirror.adoc["嵌入式注册表镜像]"。

| `--vpn-auth`
| 请参阅xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental["与 Tailscale VPN 提供商集成]"。 

| `--vpn-auth-file`
| 请参阅xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental["与 Tailscale VPN 提供商集成]"。 
|===

=== 过时的选项

|===
| 旗帜 | 环境变量 | 说明

| `--no-flannel`
| N/A
| 使用 `--flannel-backend=none`

| `--no-deploy` 价值
| N/A
| 使用 `--disable`

| `--cluster-secret` 价值
| `K3S_CLUSTER_SECRET`
| 使用 `--token`

| `--flannel-backend` 护线器
| N/A
| 使用 `--flannel-backend=wireguard-native`

| `--flannel-backend` value=option1=value
| N/A
| 使用`--flannel-conf` 指定带有后端配置的法兰绒配置文件
|===

== K3s 服务器 CLI 帮助

____
如果一个选项出现在下面的括号中，例如`[$K3S_TOKEN]` ，则表示该选项可以作为该名称的环境变量传入。
____

[,bash]
----
NAME:
   k3s server - Run management server

USAGE:
   k3s server [OPTIONS]

OPTIONS:
   --config FILE, -c FILE                     (config) Load configuration from FILE (default: "/etc/rancher/k3s/config.yaml") [$K3S_CONFIG_FILE]
   --debug                                    (logging) Turn on debug logs [$K3S_DEBUG]
   -v value                                   (logging) Number for the log level verbosity (default: 0)
   --vmodule value                            (logging) Comma-separated list of FILE_PATTERN=LOG_LEVEL settings for file-filtered logging
   --log value, -l value                      (logging) Log to file
   --alsologtostderr                          (logging) Log to standard error as well as file (if set)
   --bind-address value                       (listener) k3s bind address (default: 0.0.0.0)
   --https-listen-port value                  (listener) HTTPS listen port (default: 6443)
   --advertise-address value                  (listener) IPv4/IPv6 address that apiserver uses to advertise to members of the cluster (default: node-external-ip/node-ip)
   --advertise-port value                     (listener) Port that apiserver uses to advertise to members of the cluster (default: listen-port) (default: 0)
   --tls-san value                            (listener) Add additional hostnames or IPv4/IPv6 addresses as Subject Alternative Names on the server TLS cert
   --tls-san-security                         (listener) Protect the server TLS cert by refusing to add Subject Alternative Names not associated with the kubernetes apiserver service, server nodes, or values of the tls-san option (default: true)
   --data-dir value, -d value                 (data) Folder to hold state default /var/lib/rancher/k3s or ${HOME}/.rancher/k3s if not root [$K3S_DATA_DIR]
   --cluster-cidr value                       (networking) IPv4/IPv6 network CIDRs to use for pod IPs (default: 10.42.0.0/16)
   --service-cidr value                       (networking) IPv4/IPv6 network CIDRs to use for service IPs (default: 10.43.0.0/16)
   --service-node-port-range value            (networking) Port range to reserve for services with NodePort visibility (default: "30000-32767")
   --cluster-dns value                        (networking) IPv4 Cluster IP for coredns service. Should be in your service-cidr range (default: 10.43.0.10)
   --cluster-domain value                     (networking) Cluster Domain (default: "cluster.local")
   --flannel-backend value                    (networking) Backend (valid values: 'none', 'vxlan', 'host-gw', 'wireguard-native' (default: "vxlan")   --flannel-ipv6-masq                        (networking) Enable IPv6 masquerading for pod
   --flannel-external-ip                      (networking) Use node external IP addresses for Flannel traffic
   --egress-selector-mode value               (networking) One of 'agent', 'cluster', 'pod', 'disabled' (default: "agent")
   --servicelb-namespace value                (networking) Namespace of the pods for the servicelb component (default: "kube-system")
   --write-kubeconfig value, -o value         (client) Write kubeconfig for admin client to this file [$K3S_KUBECONFIG_OUTPUT]
   --write-kubeconfig-mode value              (client) Write kubeconfig with this mode [$K3S_KUBECONFIG_MODE]
   --write-kubeconfig-group value             (client) Write kubeconfig with this group [$K3S_KUBECONFIG_GROUP]
   --helm-job-image value                     (helm) Default image to use for helm jobs
   --token value, -t value                    (cluster) Shared secret used to join a server or agent to a cluster [$K3S_TOKEN]
   --token-file value                         (cluster) File containing the token [$K3S_TOKEN_FILE]
   --agent-token value                        (cluster) Shared secret used to join agents to the cluster, but not servers [$K3S_AGENT_TOKEN]
   --agent-token-file value                   (cluster) File containing the agent secret [$K3S_AGENT_TOKEN_FILE]
   --server value, -s value                   (cluster) Server to connect to, used to join a cluster [$K3S_URL]
   --cluster-init                             (cluster) Initialize a new cluster using embedded Etcd [$K3S_CLUSTER_INIT]
   --cluster-reset                            (cluster) Forget all peers and become sole member of a new cluster [$K3S_CLUSTER_RESET]
   --cluster-reset-restore-path value         (db) Path to snapshot file to be restored
   --kube-apiserver-arg value                 (flags) Customized flag for kube-apiserver process
   --etcd-arg value                           (flags) Customized flag for etcd process
   --kube-controller-manager-arg value        (flags) Customized flag for kube-controller-manager process
   --kube-scheduler-arg value                 (flags) Customized flag for kube-scheduler process
   --kube-cloud-controller-manager-arg value  (flags) Customized flag for kube-cloud-controller-manager process
   --datastore-endpoint value                 (db) Specify etcd, NATS, MySQL, Postgres, or SQLite (default) data source name [$K3S_DATASTORE_ENDPOINT]
   --datastore-cafile value                   (db) TLS Certificate Authority file used to secure datastore backend communication [$K3S_DATASTORE_CAFILE]
   --datastore-certfile value                 (db) TLS certification file used to secure datastore backend communication [$K3S_DATASTORE_CERTFILE]
   --datastore-keyfile value                  (db) TLS key file used to secure datastore backend communication [$K3S_DATASTORE_KEYFILE]
   --etcd-expose-metrics                      (db) Expose etcd metrics to client interface. (default: false)
   --etcd-disable-snapshots                   (db) Disable automatic etcd snapshots
   --etcd-snapshot-name value                 (db) Set the base name of etcd snapshots (default: etcd-snapshot-<unix-timestamp>) (default: "etcd-snapshot")
   --etcd-snapshot-schedule-cron value        (db) Snapshot interval time in cron spec. eg. every 5 hours '0 */5 * * *' (default: "0 */12 * * *")
   --etcd-snapshot-retention value            (db) Number of snapshots to retain (default: 5)
   --etcd-snapshot-dir value                  (db) Directory to save db snapshots. (default: $\{data-dir}/db/snapshots)
   --etcd-snapshot-compress                   (db) Compress etcd snapshot
   --etcd-s3                                  (db) Enable backup to S3
   --etcd-s3-endpoint value                   (db) S3 endpoint url (default: "s3.amazonaws.com")
   --etcd-s3-endpoint-ca value                (db) S3 custom CA cert to connect to S3 endpoint
   --etcd-s3-skip-ssl-verify                  (db) Disables S3 SSL certificate validation
   --etcd-s3-access-key value                 (db) S3 access key [$AWS_ACCESS_KEY_ID]
   --etcd-s3-secret-key value                 (db) S3 secret key [$AWS_SECRET_ACCESS_KEY]
   --etcd-s3-bucket value                     (db) S3 bucket name
   --etcd-s3-region value                     (db) S3 region / bucket location (optional) (default: "us-east-1")
   --etcd-s3-folder value                     (db) S3 folder
   --etcd-s3-proxy value                      (db) Proxy server to use when connecting to S3, overriding any proxy-releated environment variables
   --etcd-s3-config-secret value              (db) Name of secret in the kube-system namespace used to configure S3, if etcd-s3 is enabled and no other etcd-s3 options are set
   --etcd-s3-insecure                         (db) Disables S3 over HTTPS
   --etcd-s3-timeout value                    (db) S3 timeout (default: 5m0s)
   --default-local-storage-path value         (storage) Default local storage path for local provisioner storage class
   --disable value                            (components) Do not deploy packaged components and delete any deployed components (valid items: coredns, servicelb, traefik, local-storage, metrics-server, runtimes)
   --disable-scheduler                        (components) Disable Kubernetes default scheduler
   --disable-cloud-controller                 (components) Disable k3s default cloud controller manager
   --disable-kube-proxy                       (components) Disable running kube-proxy
   --disable-network-policy                   (components) Disable k3s default network policy controller
   --disable-helm-controller                  (components) Disable Helm controller
   --embedded-registry                        (experimental/components) Enable embedded distributed container registry; requires use of embedded containerd; when enabled agents will also listen on the supervisor port
   --supervisor-metrics                       (experimental/components) Enable serving k3s internal metrics on the supervisor port; when enabled agents will also listen on the supervisor port
   --node-name value                          (agent/node) Node name [$K3S_NODE_NAME]
   --with-node-id                             (agent/node) Append id to node name
   --node-label value                         (agent/node) Registering and starting kubelet with set of labels
   --node-taint value                         (agent/node) Registering kubelet with set of taints
   --image-credential-provider-bin-dir value  (agent/node) The path to the directory where credential provider plugin binaries are located (default: "/var/lib/rancher/credentialprovider/bin")
   --image-credential-provider-config value   (agent/node) The path to the credential provider plugin config file (default: "/var/lib/rancher/credentialprovider/config.yaml")
   --docker                                   (agent/runtime) (experimental) Use cri-dockerd instead of containerd
   --container-runtime-endpoint value         (agent/runtime) Disable embedded containerd and use the CRI socket at the given path; when used with --docker this sets the docker socket path
   --default-runtime value                    (agent/runtime) Set the default runtime in containerd
   --image-service-endpoint value             (agent/runtime) Disable embedded containerd image service and use remote image service socket at the given path. If not specified, defaults to --container-runtime-endpoint.
   --disable-default-registry-endpoint        (agent/containerd) Disables containerd fallback default registry endpoint when a mirror is configured for that registry
   --nonroot-devices                          (agent/containerd) Allows non-root pods to access devices by setting device_ownership_from_security_context=true in the containerd CRI config
   --pause-image value                        (agent/runtime) Customized pause image for containerd or docker sandbox (default: "rancher/mirrored-pause:3.6")
   --snapshotter value                        (agent/runtime) Override default containerd snapshotter (default: "overlayfs")
   --private-registry value                   (agent/runtime) Private registry configuration file (default: "/etc/rancher/k3s/registries.yaml")
   --system-default-registry value            (agent/runtime) Private registry to be used for all system images [$K3S_SYSTEM_DEFAULT_REGISTRY]
   --node-ip value, -i value                  (agent/networking) IPv4/IPv6 addresses to advertise for node
   --node-external-ip value                   (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
   --node-internal-dns value                  (agent/networking) internal DNS addresses to advertise for node
   --node-external-dns value                  (agent/networking) external DNS addresses to advertise for node
   --resolv-conf value                        (agent/networking) Kubelet resolv.conf file [$K3S_RESOLV_CONF]
   --flannel-iface value                      (agent/networking) Override default flannel interface
   --flannel-conf value                       (agent/networking) Override default flannel config file
   --flannel-cni-conf value                   (agent/networking) Override default flannel cni config file
   --vpn-auth value                           (agent/networking) (experimental) Credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH]
   --vpn-auth-file value                      (agent/networking) (experimental) File containing credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH_FILE]
   --kubelet-arg value                        (agent/flags) Customized flag for kubelet process
   --kube-proxy-arg value                     (agent/flags) Customized flag for kube-proxy process
   --protect-kernel-defaults                  (agent/node) Kernel tuning behavior. If set, error if kernel tunables are different than kubelet defaults.
   --secrets-encryption                       Enable secret encryption at rest
   --enable-pprof                             (experimental) Enable pprof endpoint on supervisor port
   --rootless                                 (experimental) Run rootless
   --prefer-bundled-bin                       (experimental) Prefer bundled userspace binaries over host binaries
   --selinux                                  (agent/node) Enable SELinux in containerd [$K3S_SELINUX]
   --lb-server-port value                     (agent/node) Local port for supervisor client load-balancer. If the supervisor and apiserver are not colocated an additional port 1 less than this port will also be used for the apiserver client load-balancer. (default: 6444) [$K3S_LB_SERVER_PORT]
----
