= CIS 1.8 Leitfaden zur Selbsteinschätzung
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-15
:page-revdate: {revdate}

== Übersicht

Dieses Dokument ist eine Ergänzung zum xref:security/hardening-guide.adoc[K3s-Leitfaden zur Sicherheitshärtung]. Der Härtungsleitfaden bietet eine präskriptive Anleitung für die Härtung einer K3-Produktionsinstallation, und dieser Benchmark-Leitfaden soll Ihnen helfen, das Sicherheitsniveau des gehärteten Clusters anhand der einzelnen Kontrollen im CIS Kubernetes Benchmark zu bewerten. Es soll von K3s-Betreibern, Sicherheitsteams, Prüfern und Entscheidungsträgern genutzt werden.

Dieser Leitfaden bezieht sich auf die Versionslinie *v1.26* von K3s und die Version *v1.8* des CIS Kubernetes Benchmark.

Weitere Informationen zu jeder Kontrolle, einschließlich detaillierter Beschreibungen und Abhilfemaßnahmen für fehlgeschlagene Tests, finden Sie im entsprechenden Abschnitt des CIS Kubernetes Benchmark v1.8. Sie können den Benchmark nach der Erstellung eines kostenlosen Kontos unter https://www.cisecurity.org/benchmark/kubernetes/[Center for Internet Security (CIS]) herunterladen.

=== Methodik für die Prüfung von Kontrollen

Jede Kontrolle im CIS Kubernetes Benchmark wurde mit einem K3s-Cluster evaluiert, der gemäß dem beiliegenden Härtungsleitfaden konfiguriert war.

Bei Kontrollprüfungen, die sich von der ursprünglichen CIS-Benchmark unterscheiden, werden die K3-spezifischen Prüfbefehle zum Testen bereitgestellt.

Dies sind die möglichen Ergebnisse für jede Kontrolle:

* *Bestanden* - Der getestete K3s-Cluster hat die im Benchmark beschriebene Prüfung bestanden.
* *Nicht anwendbar* - Die Steuerung ist aufgrund ihrer Funktionsweise nicht auf K3s anwendbar. Warum das so ist, wird im Abschnitt über Abhilfemaßnahmen erläutert.
* *Warnung* - Die Steuerung ist im CIS-Benchmark manuell und hängt vom Anwendungsfall des Clusters oder von anderen Faktoren ab, die vom Clusterbetreiber bestimmt werden müssen. Diese Kontrollen wurden evaluiert, um sicherzustellen, dass K3s ihre Implementierung nicht verhindert, aber es wurde keine weitere Konfiguration oder Prüfung des getesteten Clusters durchgeführt.

In dieser Anleitung wird davon ausgegangen, dass K3s als Systemd-Einheit ausgeführt wird. Ihre Installation kann davon abweichen und Sie müssen die "Audit"-Befehle an Ihr Szenario anpassen.

== 1.1 Konfigurationsdateien für Knoten der Steuerungsebene

=== 1.1.1 Vergewissern Sie sich, dass die Berechtigungen für die Pod-Spezifikationsdatei des API-Servers auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig bettet K3s den Api-Server in den k3s-Prozess ein. Es gibt keine API-Server-Pod-Spezifikationsdatei.

=== 1.1.2 Vergewissern Sie sich, dass der Eigentümer der API-Server-Pod-Spezifikationsdatei auf root:root gesetzt ist (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig bettet K3s den Api-Server in den k3s-Prozess ein. Es gibt keine API-Server-Pod-Spezifikationsdatei.

=== 1.1.3 Stellen Sie sicher, dass die Berechtigungen für die Pod-Spezifikationsdatei des Steuerungsmanagers auf 600 oder restriktiver (automatisiert) eingestellt sind.

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig bettet K3s den Controller-Manager in den k3s-Prozess ein. Es gibt keine Controller-Manager-Pod-Spezifikationsdatei.

=== 1.1.4 Sicherstellen, dass der Eigentümer der Pod-Spezifikationsdatei des Controllermanagers auf root:root gesetzt ist (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig bettet K3s den Controller-Manager in den k3s-Prozess ein. Es gibt keine Controller-Manager-Pod-Spezifikationsdatei.

=== 1.1.5 Sicherstellen, dass die Berechtigungen für die Scheduler-Pod-Spezifikationsdatei auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig bettet K3s den Scheduler in den k3s-Prozess ein. Es gibt keine Scheduler-Pod-Spezifikationsdatei.

=== 1.1.6 Sicherstellen, dass der Eigentümer der Scheduler-Pod-Spezifikationsdatei auf root:root gesetzt ist (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig bettet K3s den Scheduler in den k3s-Prozess ein. Es gibt keine Scheduler-Pod-Spezifikationsdatei.

=== 1.1.7 Stellen Sie sicher, dass die Berechtigungen für die etcd-Pod-Spezifikationsdatei auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig bettet K3s etcd in den k3s-Prozess ein. Es gibt keine etcd-Pod-Spezifikationsdatei.

=== 1.1.8 Sicherstellen, dass der Eigentümer der etcd-Pod-Spezifikationsdatei auf root:root gesetzt ist (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig bettet K3s etcd in den k3s-Prozess ein. Es gibt keine etcd-Pod-Spezifikationsdatei.

=== 1.1.9 Sicherstellen, dass die Dateiberechtigungen für die Container-Netzwerkschnittstelle auf 600 oder restriktiver eingestellt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
find /var/lib/cni/networks -type f ! -name lock 2> /dev/null | xargs --no-run-if-empty stat -c permissions=%a
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 600, erwartet 600 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
----
======

.*Abhilfe:*
[%collapsible]
======
K3s setzt die CNI-Dateiberechtigungen standardmäßig auf 600.
Beachten Sie, dass für viele CNI eine Sperrdatei mit der Berechtigung 750 erstellt wird. Dies ist zu erwarten und kann ignoriert werden.
Wenn Sie Ihre CNI-Konfiguration ändern, stellen Sie sicher, dass die Berechtigungen auf 600 gesetzt sind.
Zum Beispiel, `+chmod 600 /var/lib/cni/networks/<filename>+`
======

=== 1.1.10 Vergewissern Sie sich, dass das Eigentum an der Container-Netzwerkschnittstelle auf root:root gesetzt ist (manuell)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Führen Sie den folgenden Befehl (basierend auf dem Speicherort der Datei auf Ihrem System) auf dem Steuerebenen-Knoten aus.
Zum Beispiel,
`+chown root:root <path/to/cni/files>+`

=== 1.1.11 Stellen Sie sicher, dass die Berechtigungen für das etcd-Datenverzeichnis auf 700 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
if [ "$(journalctl -u k3s | grep -m1 'Managed etcd cluster' | wc -l)" -gt 0 ]; then
  stat -c permissions=%a /var/lib/rancher/k3s/server/db/etcd
else
  echo "permissions=700"
fi
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 700, erwartet 700 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=700
----
======

.*Abhilfe:*
[%collapsible]
======
Holen Sie sich auf dem etcd-Serverknoten das etcd-Datenverzeichnis, das als Argument --data-dir übergeben wird, mit dem Befehl 'ps -ef | grep etcd'.
Führen Sie den folgenden Befehl aus (basierend auf dem oben gefundenen etcd-Datenverzeichnis). Zum Beispiel,
`+chmod 700 /var/lib/etcd+`
======

=== 1.1.12 Stellen Sie sicher, dass die Eigentümerschaft des Datenverzeichnisses etcd auf etcd:etcd gesetzt ist (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Bei K3s ist etcd in den k3s-Prozess eingebettet. Es gibt keinen separaten etcd-Prozess.
Daher wird der Besitz des etcd-Datenverzeichnisses durch den k3s-Prozess verwaltet und sollte root:root sein.

=== 1.1.13 Stellen Sie sicher, dass die Berechtigungen für die Datei admin.conf auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test -e /var/lib/rancher/k3s/server/cred/admin.kubeconfig; then stat -c permissions=%a /var/lib/rancher/k3s/server/cred/admin.kubeconfig; fi'
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 600, erwartet 600 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=600
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Speicherort der Datei auf Ihrem System) auf dem Steuerebenen-Knoten aus.
Zum Beispiel, `+chmod 600 /var/lib/rancher/k3s/server/cred/admin.kubeconfig+`
======

=== 1.1.14 Sicherstellen, dass der Eigentümer der Datei admin.conf auf root:root gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test -e /var/lib/rancher/k3s/server/cred/admin.kubeconfig; then stat -c %U:%G /var/lib/rancher/k3s/server/cred/admin.kubeconfig; fi'
----

*Erwartetes Ergebnis:* 'root:root' ist gleich 'root:root'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
root:root
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Speicherort der Datei auf Ihrem System) auf dem Steuerebenen-Knoten aus.
Zum Beispiel, `+chown root:root /var/lib/rancher/k3s/server/cred/admin.kubeconfig+`
======

=== 1.1.15 Sicherstellen, dass die Berechtigungen für die Datei scheduler.conf auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test -e /var/lib/rancher/k3s/server/cred/scheduler.kubeconfig; then stat -c permissions=%a /var/lib/rancher/k3s/server/cred/scheduler.kubeconfig; fi'
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 600, erwartet 600 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=600
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Speicherort der Datei auf Ihrem System) auf dem Steuerebenen-Knoten aus.
Zum Beispiel,
`+chmod 600 /var/lib/rancher/k3s/server/cred/scheduler.kubeconfig+`
======

=== 1.1.16 Sicherstellen, dass der Eigentümer der Datei scheduler.conf auf root:root gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test -e /var/lib/rancher/k3s/server/cred/scheduler.kubeconfig; then stat -c %U:%G /var/lib/rancher/k3s/server/cred/scheduler.kubeconfig; fi'
----

*Erwartetes Ergebnis:* 'root:root' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
root:root
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Speicherort der Datei auf Ihrem System) auf dem Steuerebenen-Knoten aus.
Zum Beispiel,
`+chown root:root /var/lib/rancher/k3s/server/cred/scheduler.kubeconfig+`
======

=== 1.1.17 Sicherstellen, dass die Berechtigungen für die Datei controller-manager.conf auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test -e /var/lib/rancher/k3s/server/cred/controller.kubeconfig; then stat -c permissions=%a /var/lib/rancher/k3s/server/cred/controller.kubeconfig; fi'
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 600, erwartet 600 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=600
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Speicherort der Datei auf Ihrem System) auf dem Steuerebenen-Knoten aus.
Zum Beispiel,
`+chmod 600 /var/lib/rancher/k3s/server/cred/controller.kubeconfig+`
======

=== 1.1.18 Sicherstellen, dass der Eigentümer der Datei controller-manager.conf auf root:root gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
stat -c %U:%G /var/lib/rancher/k3s/server/cred/controller.kubeconfig
----

*Erwartetes Ergebnis:* 'root:root' ist gleich 'root:root'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
root:root
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Speicherort der Datei auf Ihrem System) auf dem Steuerebenen-Knoten aus.
Zum Beispiel,
`+chown root:root /var/lib/rancher/k3s/server/cred/controller.kubeconfig+`
======

=== 1.1.19 Sicherstellen, dass der Eigentümer des Kubernetes-PKI-Verzeichnisses und der Dateien auf root:root gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
stat -c %U:%G /var/lib/rancher/k3s/server/tls
----

*Erwartetes Ergebnis:* 'root:root' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
root:root
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Speicherort der Datei auf Ihrem System) auf dem Steuerebenen-Knoten aus.
Zum Beispiel,
`+chown -R root:root /var/lib/rancher/k3s/server/tls+`
======

=== 1.1.20 Sicherstellen, dass die Berechtigungen für die Kubernetes-PKI-Zertifikatsdatei auf 600 oder restriktiver eingestellt sind (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Führen Sie den folgenden Befehl (je nach Speicherort der Datei auf Ihrem System) auf dem Master-Knoten aus.
Zum Beispiel,
`+chmod -R 600 /var/lib/rancher/k3s/server/tls/*.crt+`

=== 1.1.21 Sicherstellen, dass die Berechtigungen für die PKI-Schlüsseldatei von Kubernetes auf 600 gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'stat -c permissions=%a /var/lib/rancher/k3s/server/tls/*.key'
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 600, erwartet 600 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
permissions=600
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (je nach Speicherort der Datei auf Ihrem System) auf dem Master-Knoten aus.
Zum Beispiel,
`+chmod -R 600 /var/lib/rancher/k3s/server/tls/*.key+`
======

== 1.2 API-Server

=== 1.2.1 Sicherstellen, dass das Argument --anonymous-auth auf false gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'anonymous-auth'
----

*Erwartetes Ergebnis:* '--anonymous-auth' ist gleich 'false'.

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
K3s setzt das Argument --anonymous-auth standardmäßig auf false.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alles, was dem Folgenden ähnelt.

----
kube-apiserver-arg:
  - "anonymous-auth=true"
----
======

=== 1.2.2 Sicherstellen, dass der Parameter --token-auth-file nicht gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--token-auth-file' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Befolgen Sie die Dokumentation und konfigurieren Sie alternative Mechanismen für die Authentifizierung.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alles, was dem Folgenden ähnelt.

----
kube-apiserver-arg:
  - "token-auth-file=<path>"
----
======

=== 1.2.3 Sicherstellen, dass die --DenyServiceExternalIPs nicht gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--enable-admission-plugins' hat nicht 'DenyServiceExternalIPs' ODER '--enable-admission-plugins' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s keine DenyServiceExternalIPs.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "enable-admission-plugins=DenyServiceExternalIPs"
----
======

=== 1.2.4 Stellen Sie sicher, dass die Argumente --kubelet-client-certificate und --kubelet-client-key entsprechend gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--kubelet-client-certificate' ist vorhanden UND '--kubelet-client-key' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig stellt K3s automatisch das Zertifikat und den Schlüssel des Kubelet-Clients bereit.
Sie werden generiert und befinden sich unter /var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt und /var/lib/rancher/k3s/server/tls/client-kube-apiserver.key. Wenn Sie aus irgendeinem Grund Ihr eigenes Zertifikat und Ihren eigenen Schlüssel bereitstellen müssen, können Sie die folgenden Parameter in der K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml festlegen.

----
kube-apiserver-arg:
  - "kubelet-client-certificate=<path/to/client-cert-file>"
  - "kubelet-client-key=<path/to/client-key-file>"
----
======

=== 1.2.5 Sicherstellen, dass das Argument --kubelet-certificate-authority entsprechend gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'kubelet-certificate-authority'
----

*Erwartetes Ergebnis:* '--kubelet-certificate-authority' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig stellt K3s automatisch die Kubelet-CA-Zertifizierungsdatei unter /var/lib/rancher/k3s/server/tls/server-ca.crt bereit.
Wenn Sie aus irgendeinem Grund ein eigenes Zertifikat benötigen, können Sie das Befehlszeilentool k3s certificate verwenden.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "kubelet-certificate-authority=<path/to/ca-cert-file>"
----
======

=== 1.2.6 Sicherstellen, dass das Argument --authorization-mode nicht auf AlwaysAllow (Automated) gesetzt ist

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'authorization-mode'
----

*Erwartetes Ergebnis:* '--authorization-mode' hat nicht 'AlwaysAllow'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s den --authorization-mode nicht auf AlwaysAllow.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "authorization-mode=AlwaysAllow"
----
======

=== 1.2.7 Sicherstellen, dass das Argument --authorization-mode Node (Automated) enthält

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'authorization-mode'
----

*Erwartetes Ergebnis:* '--authorization-mode' hat 'Node'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s den --Autorisierungsmodus auf Node und RBAC.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und stellen Sie sicher, dass Sie den Autorisierungsmodus nicht überschreiben.
======

=== 1.2.8 Sicherstellen, dass das Argument --authorization-mode RBAC (Automated) enthält

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'authorization-mode'
----

*Erwartetes Ergebnis:* '--authorization-mode' hat 'RBAC'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s den --Autorisierungsmodus auf Node und RBAC.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und stellen Sie sicher, dass Sie den Autorisierungsmodus nicht überschreiben.
======

=== 1.2.9 Sicherstellen, dass das Plugin EventRateLimit für die Zulassungskontrolle eingestellt ist (Manual)

*Ergebnis:* WARN

*Abhilfe:*
Folgen Sie der Kubernetes-Dokumentation und legen Sie die gewünschten Grenzen in einer Konfigurationsdatei fest.
Bearbeiten Sie dann die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und setzen Sie die folgenden Parameter.

----
kube-apiserver-arg:
  - "enable-admission-plugins=...,EventRateLimit,..."
  - "admission-control-config-file=<path/to/configuration/file>"
----

=== 1.2.10 Sicherstellen, dass das Plugin für die Zulassungskontrolle AlwaysAdmit nicht aktiviert ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'enable-admission-plugins'
----

*Erwartetes Ergebnis:* '--enable-admission-plugins' hat nicht 'AlwaysAdmit' ODER '--enable-admission-plugins' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s die --enable-admission-plugins nicht auf AlwaysAdmit.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "enable-admission-plugins=AlwaysAdmit"
----
======

=== 1.2.11 Sicherstellen, dass das Plugin AlwaysPullImages für die Zulassungskontrolle eingestellt ist (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Zulässig, gemäß CIS-Richtlinien: "Diese Einstellung könnte sich auf Offline- oder isolierte Cluster auswirken, in denen Images vorinstalliert sind und die keinen Zugriff auf eine Registry haben, um aktuelle Images abzurufen. Diese Einstellung ist nicht für Cluster geeignet, die diese Konfiguration verwenden."
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und setzen Sie die folgenden Parameter.

----
kube-apiserver-arg:
  - "enable-admission-plugins=...,AlwaysPullImages,..."
----

=== 1.2.12 Sicherstellen, dass das Zugangskontroll-Plugin SecurityContextDeny gesetzt ist, wenn PodSecurityPolicy nicht verwendet wird (manuell)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Die Aktivierung der Pod-Sicherheitsrichtlinie wird auf K3s v1.25+ nicht mehr unterstützt und führt dazu, dass Anwendungen unerwartet fehlschlagen.

=== 1.2.13 Sicherstellen, dass das Plugin ServiceAccount für die Zulassungskontrolle gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--disable-admission-plugins' ist vorhanden ODER '--disable-admission-plugins' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s die --disable-admission-plugins nicht auf irgendetwas.
Folgen Sie der Dokumentation und erstellen Sie ServiceAccount-Objekte entsprechend Ihrer Umgebung.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "disable-admission-plugins=ServiceAccount"
----
======

=== 1.2.14 Sicherstellen, dass das Zulassungskontroll-Plugin NamespaceLifecycle gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--disable-admission-plugins' ist vorhanden ODER '--disable-admission-plugins' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s die --disable-admission-plugins nicht auf irgendetwas.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "disable-admission-plugins=...,NamespaceLifecycle,..."
----
======

=== 1.2.15 Sicherstellen, dass das Plugin NodeRestriction für die Zulassungskontrolle gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'enable-admission-plugins'
----

*Erwartetes Ergebnis:* '--enable-admission-plugins' hat 'NodeRestriction'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
K3s setzt die --enable-admission-plugins standardmäßig auf NodeRestriction.
Wenn Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, stellen Sie sicher, dass Sie die Zulassungs-Plugins nicht überschreiben.
Wenn Sie dies tun, nehmen Sie NodeRestriction in die Liste auf.

----
kube-apiserver-arg:
  - "enable-admission-plugins=...,NodeRestriction,..."
----
======

=== 1.2.16 Sicherstellen, dass das Argument --profiling auf false gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'profiling'
----

*Erwartetes Ergebnis:* '--profiling' ist gleich 'false'.

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das Argument --profiling auf false.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "profiling=true"
----
======

=== 1.2.17 Sicherstellen, dass das Argument --audit-log-path gesetzt ist (manuell)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--audit-log-path' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und setzen Sie den Parameter audit-log-path auf einen geeigneten Pfad und eine Datei, in die z.B. Audit-Protokolle geschrieben werden sollen,

----
kube-apiserver-arg:
  - "audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log"
----
======

=== 1.2.18 Stellen Sie sicher, dass das Argument --audit-log-maxage auf 30 oder den entsprechenden Wert gesetzt ist (manuell).

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--audit-log-maxage' ist größer oder gleich 30

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml auf dem Steuerebenen-Knoten und setzen Sie den Parameter audit-log-maxage beispielsweise auf 30 oder eine entsprechende Anzahl von Tagen,

----
kube-apiserver-arg:
  - "audit-log-maxage=30"
----
======

=== 1.2.19 Stellen Sie sicher, dass das Argument --audit-log-maxbackup auf 10 oder den entsprechenden Wert gesetzt ist (manuell).

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--audit-log-maxbackup' ist größer oder gleich 10

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml auf dem Steuerebenen-Knoten und setzen Sie den Parameter audit-log-maxbackup auf 10 oder einen geeigneten Wert. Zum Beispiel,

----
kube-apiserver-arg:
  - "audit-log-maxbackup=10"
----
======

=== 1.2.20 Stellen Sie sicher, dass das Argument --audit-log-maxsize auf 100 oder den entsprechenden Wert gesetzt ist (manuell).

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--audit-log-maxsize' ist größer oder gleich 100

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml auf dem Steuerebenen-Knoten und setzen Sie den Parameter audit-log-maxsize auf eine geeignete Größe in MB. Zum Beispiel,

----
kube-apiserver-arg:
  - "audit-log-maxsize=100"
----
======

=== 1.2.21 Stellen Sie sicher, dass das Argument --request-timeout richtig gesetzt ist (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Zulässig, gemäß CIS-Leitlinien: "Es wird empfohlen, diesen Grenzwert nach Bedarf festzulegen und den Standardgrenzwert von 60 Sekunden nur bei Bedarf zu ändern".
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und setzen Sie bei Bedarf die folgenden Parameter. Zum Beispiel,

----
kube-apiserver-arg:
  - "request-timeout=300s"
----

=== 1.2.22 Sicherstellen, dass das Argument --service-account-lookup auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--service-account-lookup' ist nicht vorhanden ODER '--service-account-lookup' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das Argument --service-account-lookup nicht.
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und setzen Sie den service-account-lookup. Zum Beispiel,

----
kube-apiserver-arg:
  - "service-account-lookup=true"
----

Alternativ können Sie den Parameter service-account-lookup aus dieser Datei löschen, damit die Standardeinstellung wirksam wird.
======

=== 1.2.23 Sicherstellen, dass das Argument --service-account-key-file entsprechend gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1
----

*Erwartetes Ergebnis:* '--service-account-key-file' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
K3s erzeugt und setzt automatisch die Schlüsseldatei für das Dienstkonto.
Sie befindet sich unter /var/lib/rancher/k3s/server/tls/service.key.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie K3s Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "service-account-key-file=<path>"
----
======

=== 1.2.24 Stellen Sie sicher, dass die Argumente --etcd-certfile und --etcd-keyfile entsprechend gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
if [ "$(journalctl -u k3s | grep -m1 'Managed etcd cluster' | wc -l)" -gt 0 ]; then
  journalctl -D /var/log/journal -u k3s | grep -m1 'Running kube-apiserver' | tail -n1
else
  echo "--etcd-certfile AND --etcd-keyfile"
fi
----

*Erwartetes Ergebnis:* '--etcd-certfile' ist vorhanden UND '--etcd-keyfile' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
K3s erzeugt und setzt automatisch die etcd-Zertifikats- und Schlüsseldateien.
Sie befinden sich unter /var/lib/rancher/k3s/server/tls/etcd/client.crt und /var/lib/rancher/k3s/server/tls/etcd/client.key.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "etcd-certfile=<path>"
  - "etcd-keyfile=<path>"
----
======

=== 1.2.25 Sicherstellen, dass die Argumente --tls-cert-file und --tls-private-key-file entsprechend gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -D /var/log/journal -u k3s | grep -A1 'Running kube-apiserver' | tail -n2
----

*Erwartetes Ergebnis:* '--tls-cert-file' ist vorhanden UND '--tls-private-key-file' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-scheduler --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --profiling=false --secure-port=10259"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig generiert und liefert K3s automatisch das TLS-Zertifikat und den privaten Schlüssel für den Apiserver.
Sie werden generiert und befinden sich unter /var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt und /var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key. Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "tls-cert-file=<path>"
  - "tls-private-key-file=<path>"
----
======

=== 1.2.26 Sicherstellen, daß das Argument --client-ca-file entsprechend gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'client-ca-file'
----

*Erwartetes Ergebnis:* '--client-ca-file' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig stellt K3s automatisch die Client-Zertifizierungsstellendatei bereit.
Sie wird erzeugt und befindet sich unter /var/lib/rancher/k3s/server/tls/client-ca.crt.
Wenn Sie aus irgendeinem Grund ein eigenes Zertifikat benötigen, können Sie das Befehlszeilentool k3s certificate verwenden.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "client-ca-file=<path>"
----
======

=== 1.2.27 Stellen Sie sicher, dass das Argument --etcd-cafile entsprechend gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'etcd-cafile'
----

*Erwartetes Ergebnis:* '--etcd-cafile' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig stellt K3s automatisch die etcd-Zertifizierungsstellendatei bereit.
Sie wird erzeugt und befindet sich unter /var/lib/rancher/k3s/server/tls/client-ca.crt.
Wenn Sie aus irgendeinem Grund ein eigenes Zertifikat benötigen, können Sie das Befehlszeilentool k3s certificate verwenden.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-apiserver-arg:
  - "etcd-cafile=<path>"
----
======

=== 1.2.28 Vergewissern Sie sich, dass das Argument --encryption-provider-config richtig gesetzt ist (Manual)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'encryption-provider-config'
----

*Erwartetes Ergebnis:* '--encryption-provider-config' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
K3s kann so konfiguriert werden, dass es Verschlüsselungsanbieter zur Verschlüsselung von Geheimnissen im Ruhezustand verwendet.
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml auf dem Steuerebenen-Knoten und setzen Sie den folgenden Parameter. secrets-encryption: true Die Verschlüsselung von Geheimnissen kann dann mit dem Befehlszeilen-Tool k3s secrets-encrypt verwaltet werden.
Bei Bedarf können Sie die generierte Verschlüsselungskonfiguration unter /var/lib/rancher/k3s/server/cred/encryption-config.json finden.
======

=== 1.2.29 Sicherstellen, dass Verschlüsselungsanbieter angemessen konfiguriert sind (manuell)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
ENCRYPTION_PROVIDER_CONFIG=$(journalctl -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep -- --encryption-provider-config | sed 's%.*encryption-provider-config[= ]\([^ ]*\).*%\1%')
if test -e $ENCRYPTION_PROVIDER_CONFIG; then grep -o 'providers\"\:\[.*\]' $ENCRYPTION_PROVIDER_CONFIG | grep -o "[A-Za-z]*" | head -2 | tail -1  | sed 's/^/provider=/'; fi
----

*Erwartetes Ergebnis:* 'provider' enthält gültige Elemente aus 'aescbc,kms,secretbox'.

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
provider=aescbc
----
======

.*Abhilfe:*
[%collapsible]
======
K3s kann so konfiguriert werden, dass es Verschlüsselungsanbieter zur Verschlüsselung von Geheimnissen im Ruhezustand verwendet. K3s wird den aescbc-Anbieter nutzen.
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml auf dem Steuerebenen-Knoten und setzen Sie den folgenden Parameter. secrets-encryption: true Die Verschlüsselung von Geheimnissen kann dann mit dem Befehlszeilen-Tool k3s secrets-encrypt verwaltet werden.
Bei Bedarf können Sie die generierte Verschlüsselungskonfiguration unter /var/lib/rancher/k3s/server/cred/encryption-config.json finden
======

=== 1.2.30 Sicherstellen, dass der API-Server nur starke kryptografische Verschlüsselungen verwendet (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -D /var/log/journal -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'tls-cipher-suites'
----

*Erwartetes Ergebnis:* '--tls-cipher-suites' enthält gültige Elemente aus 'TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig erfüllt der K3s kube-apiserver diesen Test. Änderungen an diesen Werten können zu Regressionen führen. Stellen Sie daher sicher, dass alle apiserver-Clients die neue TLS-Konfiguration unterstützen, bevor Sie sie in Produktionsumgebungen anwenden.
Wenn eine benutzerdefinierte TLS-Konfiguration erforderlich ist, sollten Sie auch eine benutzerdefinierte Version dieser Regel erstellen, die Ihren Anforderungen entspricht.
Wenn diese Prüfung fehlschlägt, entfernen Sie alle benutzerdefinierten Konfigurationen rund um `+tls-cipher-suites+` oder aktualisieren Sie die Datei /etc/rancher/k3s/config.yaml, damit sie dem Standard entspricht, indem Sie Folgendes hinzufügen:

----
kube-apiserver-arg:
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
----
======

== 1.3 Controller-Manager

=== 1.3.1 Vergewissern Sie sich, dass das Argument --terminated-pod-gc-threshold richtig gesetzt ist (Manual)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-controller-manager' | tail -n1 | grep 'terminated-pod-gc-threshold'
----

*Erwartetes Ergebnis:* '--terminated-pod-gc-threshold' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --terminated-pod-gc-threshold=10 --use-service-account-credentials=true"
----
======

.*Abhilfe:*
[%collapsible]
======
Bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml auf dem Steuerebenen-Knoten und setzen Sie den Schwellenwert --terminated-pod-gc-threshold auf einen geeigneten Wert,

----
kube-controller-manager-arg:
  - "terminated-pod-gc-threshold=10"
----
======

=== 1.3.2 Stellen Sie sicher, dass das Argument --profiling auf false (Automatisiert) gesetzt ist.

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-controller-manager' | tail -n1 | grep 'profiling'
----

*Erwartetes Ergebnis:* '--profiling' ist gleich 'false'.

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --terminated-pod-gc-threshold=10 --use-service-account-credentials=true"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das Argument --profiling auf false.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-controller-manager-arg:
  - "profiling=true"
----
======

=== 1.3.3 Sicherstellen, dass das Argument --use-service-account-credentials auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-controller-manager' | tail -n1 | grep 'use-service-account-credentials'
----

*Erwartetes Ergebnis:* '--use-service-account-credentials' ist ungleich 'false'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --terminated-pod-gc-threshold=10 --use-service-account-credentials=true"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das Argument --use-service-account-credentials auf true.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-controller-manager-arg:
  - "use-service-account-credentials=false"
----
======

=== 1.3.4 Stellen Sie sicher, dass das Argument --service-account-private-key-file entsprechend gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-controller-manager' | tail -n1 | grep 'service-account-private-key-file'
----

*Erwartetes Ergebnis:* '--service-account-private-key-file' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --terminated-pod-gc-threshold=10 --use-service-account-credentials=true"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig stellt K3s automatisch die private Schlüsseldatei für das Dienstkonto bereit.
Er wird erzeugt und befindet sich unter /var/lib/rancher/k3s/server/tls/service.current.key.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-controller-manager-arg:
  - "service-account-private-key-file=<path>"
----
======

=== 1.3.5 Stellen Sie sicher, dass das Argument --root-ca-file entsprechend gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-controller-manager' | tail -n1 | grep 'root-ca-file'
----

*Erwartetes Ergebnis:* '--root-ca-file' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --terminated-pod-gc-threshold=10 --use-service-account-credentials=true"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig stellt K3s automatisch die Root-CA-Datei bereit.
Sie wird erzeugt und befindet sich unter /var/lib/rancher/k3s/server/tls/server-ca.crt.
Wenn Sie aus irgendeinem Grund ein eigenes Zertifikat benötigen, können Sie das Befehlszeilentool k3s certificate verwenden.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-controller-manager-arg:
  - "root-ca-file=<path>"
----
======

=== 1.3.6 Sicherstellen, dass das Argument RotateKubeletServerCertificate auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-controller-manager' | tail -n1
----

*Erwartetes Ergebnis:* '--feature-gates' ist vorhanden ODER '--feature-gates' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --terminated-pod-gc-threshold=10 --use-service-account-credentials=true"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das RotateKubeletServerCertificate Feature Gate nicht.
Wenn Sie diese Funktion aktiviert haben, sollten Sie sie entfernen.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-controller-manager-arg:
  - "feature-gate=RotateKubeletServerCertificate"
----
======

=== 1.3.7 Vergewissern Sie sich, dass das Argument --bind-address auf 127.0.0.1 (automatisiert) gesetzt ist.

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-controller-manager' | tail -n1
----

*Erwartetes Ergebnis:* '--bind-address' ist gleich '127.0.0.1' ODER '--bind-address' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --terminated-pod-gc-threshold=10 --use-service-account-credentials=true"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das --bind-address-Argument auf 127.0.0.1. Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-controller-manager-arg:
  - "bind-address=<IP>"
----
======

== 1.4 Planer

=== 1.4.1 Vergewissern Sie sich, dass das Argument --profiling auf false gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -D /var/log/journal -u k3s | grep 'Running kube-scheduler' | tail -n1 | grep 'profiling'
----

*Erwartetes Ergebnis:* '--profiling' ist gleich 'false'.

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-scheduler --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --profiling=false --secure-port=10259"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das Argument --profiling auf false.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-scheduler-arg:
  - "profiling=true"
----
======

=== 1.4.2 Vergewissern Sie sich, dass das Argument --bind-address auf 127.0.0.1 (Automated) gesetzt ist.

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s | grep 'Running kube-scheduler' | tail -n1 | grep 'bind-address'
----

*Erwartetes Ergebnis:* '--bind-address' ist gleich '127.0.0.1' ODER '--bind-address' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-scheduler --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --profiling=false --secure-port=10259"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das --bind-address-Argument auf 127.0.0.1. Wenn diese Prüfung fehlschlägt, bearbeiten Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml und entfernen Sie alle Zeilen wie unten.

----
kube-scheduler-arg:
  - "bind-address=<IP>"
----
======

== 2 Etcd-Knoten Konfiguration

=== 2.1 Stellen Sie sicher, dass die Argumente --cert-file und --key-file richtig gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
----

*Erwartetes Ergebnis:* '.client-transport-security.cert-file' ist gleich '/var/lib/rancher/k3s/server/tls/etcd/server-client.crt' AND '.client-transport-security.key-file' ist gleich '/var/lib/rancher/k3s/server/tls/etcd/server-client.key'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
advertise-client-urls: https://10.10.10.100:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
experimental-watch-progress-notify-interval: 5000000000
heartbeat-interval: 500
initial-advertise-peer-urls: https://10.10.10.100:2380
initial-cluster: server-0-11120bb0=https://10.10.10.100:2380
initial-cluster-state: new
listen-client-http-urls: https://127.0.0.1:2382
listen-client-urls: https://127.0.0.1:2379,https://10.10.10.100:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://10.10.10.100:2380
log-outputs:
- stderr
logger: zap
name: server-0-11120bb0
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
snapshot-count: 10000
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie mit Sqlite oder einer externen DB arbeiten, sind etcd-Prüfungen nicht anwendbar.
Wenn K3s mit embedded-etcd läuft, erzeugt es cert- und key-Dateien für etcd.
Diese befinden sich in /var/lib/rancher/k3s/server/tls/etcd/.
Wenn diese Prüfung fehlschlägt, stellen Sie sicher, dass die Konfigurationsdatei /var/lib/rancher/k3s/server/db/etcd/config nicht geändert wurde, um benutzerdefinierte Zertifikats- und Schlüsseldateien zu verwenden.
======

=== 2.2 Stellen Sie sicher, dass das Argument --client-cert-auth auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
----

*Erwartetes Ergebnis:* '.client-transport-security.client-cert-auth' ist gleich 'true'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
advertise-client-urls: https://10.10.10.100:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
experimental-watch-progress-notify-interval: 5000000000
heartbeat-interval: 500
initial-advertise-peer-urls: https://10.10.10.100:2380
initial-cluster: server-0-11120bb0=https://10.10.10.100:2380
initial-cluster-state: new
listen-client-http-urls: https://127.0.0.1:2382
listen-client-urls: https://127.0.0.1:2379,https://10.10.10.100:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://10.10.10.100:2380
log-outputs:
- stderr
logger: zap
name: server-0-11120bb0
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
snapshot-count: 10000
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie mit Sqlite oder einer externen DB arbeiten, sind etcd-Prüfungen nicht anwendbar.
Wenn K3s mit embedded-etcd läuft, setzt es den Parameter --client-cert-auth auf true.
Wenn diese Prüfung fehlschlägt, stellen Sie sicher, dass die Konfigurationsdatei /var/lib/rancher/k3s/server/db/etcd/config nicht geändert wurde, um die Client-Zertifikatsauthentifizierung zu deaktivieren.
======

=== 2.3 Stellen Sie sicher, dass das Argument --auto-tls nicht auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
----

*Erwartetes Ergebnis:* '.client-transport-security.auto-tls' ist vorhanden ODER '.client-transport-security.auto-tls' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
advertise-client-urls: https://10.10.10.100:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
experimental-watch-progress-notify-interval: 5000000000
heartbeat-interval: 500
initial-advertise-peer-urls: https://10.10.10.100:2380
initial-cluster: server-0-11120bb0=https://10.10.10.100:2380
initial-cluster-state: new
listen-client-http-urls: https://127.0.0.1:2382
listen-client-urls: https://127.0.0.1:2379,https://10.10.10.100:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://10.10.10.100:2380
log-outputs:
- stderr
logger: zap
name: server-0-11120bb0
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
snapshot-count: 10000
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie mit Sqlite oder einer externen DB arbeiten, sind etcd-Prüfungen nicht anwendbar.
Wenn K3s mit embedded-etcd läuft, wird der Parameter --auto-tls nicht gesetzt.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die etcd-Pod-Spezifikationsdatei /var/lib/rancher/k3s/server/db/etcd/config auf dem Master-Knoten und entfernen Sie entweder den Parameter --auto-tls oder setzen Sie ihn auf false. client-transport-security: auto-tls: false
======

=== 2.4 Stellen Sie sicher, dass die Argumente --peer-cert-file und --peer-key-file entsprechend gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
----

*Erwartetes Ergebnis:* '.peer-transport-security.cert-file' ist gleich '/var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt' AND '.peer-transport-security.key-file' ist gleich '/var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
advertise-client-urls: https://10.10.10.100:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
experimental-watch-progress-notify-interval: 5000000000
heartbeat-interval: 500
initial-advertise-peer-urls: https://10.10.10.100:2380
initial-cluster: server-0-11120bb0=https://10.10.10.100:2380
initial-cluster-state: new
listen-client-http-urls: https://127.0.0.1:2382
listen-client-urls: https://127.0.0.1:2379,https://10.10.10.100:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://10.10.10.100:2380
log-outputs:
- stderr
logger: zap
name: server-0-11120bb0
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
snapshot-count: 10000
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie mit Sqlite oder einer externen DB arbeiten, sind etcd-Prüfungen nicht anwendbar.
Wenn K3s mit embedded-etcd läuft, generiert es Peer-Cert- und Key-Dateien für etcd.
Diese befinden sich in /var/lib/rancher/k3s/server/tls/etcd/.
Wenn diese Prüfung fehlschlägt, stellen Sie sicher, dass die Konfigurationsdatei /var/lib/rancher/k3s/server/db/etcd/config nicht geändert wurde, um benutzerdefinierte Peer-Zertifizierungs- und Schlüsseldateien zu verwenden.
======

=== 2.5 Stellen Sie sicher, dass das Argument --peer-client-cert-auth auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
----

*Erwartetes Ergebnis:* '.peer-transport-security.client-cert-auth' ist gleich 'true'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
advertise-client-urls: https://10.10.10.100:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
experimental-watch-progress-notify-interval: 5000000000
heartbeat-interval: 500
initial-advertise-peer-urls: https://10.10.10.100:2380
initial-cluster: server-0-11120bb0=https://10.10.10.100:2380
initial-cluster-state: new
listen-client-http-urls: https://127.0.0.1:2382
listen-client-urls: https://127.0.0.1:2379,https://10.10.10.100:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://10.10.10.100:2380
log-outputs:
- stderr
logger: zap
name: server-0-11120bb0
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
snapshot-count: 10000
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie mit Sqlite oder einer externen DB arbeiten, sind etcd-Prüfungen nicht anwendbar.
Wenn K3s mit embedded-etcd läuft, setzt es den Parameter --peer-cert-auth auf true.
Wenn diese Prüfung fehlschlägt, stellen Sie sicher, dass die Konfigurationsdatei /var/lib/rancher/k3s/server/db/etcd/config nicht geändert wurde, um die Peer-Client-Zertifikatsauthentifizierung zu deaktivieren.
======

=== 2.6 Stellen Sie sicher, dass das Argument --peer-auto-tls nicht auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
----

*Erwartetes Ergebnis:* '.peer-transport-security.auto-tls' ist vorhanden ODER '.peer-transport-security.auto-tls' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
advertise-client-urls: https://10.10.10.100:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
experimental-watch-progress-notify-interval: 5000000000
heartbeat-interval: 500
initial-advertise-peer-urls: https://10.10.10.100:2380
initial-cluster: server-0-11120bb0=https://10.10.10.100:2380
initial-cluster-state: new
listen-client-http-urls: https://127.0.0.1:2382
listen-client-urls: https://127.0.0.1:2379,https://10.10.10.100:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://10.10.10.100:2380
log-outputs:
- stderr
logger: zap
name: server-0-11120bb0
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
snapshot-count: 10000
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie mit Sqlite oder einer externen DB arbeiten, sind etcd-Prüfungen nicht anwendbar.
Wenn K3s mit embedded-etcd läuft, wird der Parameter --peer-auto-tls nicht gesetzt.
Wenn diese Prüfung fehlschlägt, bearbeiten Sie die etcd-Pod-Spezifikationsdatei /var/lib/rancher/k3s/server/db/etcd/config auf dem Master-Knoten und entfernen entweder den Parameter --peer-auto-tls oder setzen ihn auf false. peer-transport-security: auto-tls: false
======

=== 2.7 Sicherstellen, dass eine eindeutige Zertifizierungsstelle für etcd verwendet wird (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
----

*Erwartetes Ergebnis:* '.peer-transport-security.trusted-ca-file' ist gleich '/var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt'.

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
advertise-client-urls: https://10.10.10.100:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
experimental-watch-progress-notify-interval: 5000000000
heartbeat-interval: 500
initial-advertise-peer-urls: https://10.10.10.100:2380
initial-cluster: server-0-11120bb0=https://10.10.10.100:2380
initial-cluster-state: new
listen-client-http-urls: https://127.0.0.1:2382
listen-client-urls: https://127.0.0.1:2379,https://10.10.10.100:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://10.10.10.100:2380
log-outputs:
- stderr
logger: zap
name: server-0-11120bb0
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
snapshot-count: 10000
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie mit Sqlite oder einer externen DB arbeiten, sind etcd-Prüfungen nicht anwendbar.
Wenn K3s mit embedded-etcd ausgeführt wird, generiert es eine eindeutige Zertifizierungsstelle für etcd.
Diese befindet sich unter /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt.
Wenn diese Prüfung fehlschlägt, stellen Sie sicher, dass die Konfigurationsdatei /var/lib/rancher/k3s/server/db/etcd/config nicht so geändert wurde, dass eine gemeinsame Zertifizierungsstelle verwendet wird.
======

== 4.1 Konfigurationsdateien für Arbeiterknoten

=== 4.1.1 Vergewissern Sie sich, dass die Berechtigungen für die Kubelet-Dienstdatei auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Das Kubelet ist in den k3s-Prozess eingebettet. Es gibt keine Kubelet-Service-Datei, die gesamte Konfiguration wird zur Laufzeit als Argumente übergeben.

=== 4.1.2 Sicherstellen, dass die Eigentümerschaft der Kubelet-Dienstdatei auf root:root gesetzt ist (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Das Kubelet ist in den k3s-Prozess eingebettet. Es gibt keine Kubelet-Service-Datei, die gesamte Konfiguration wird zur Laufzeit als Argumente übergeben.

Die gesamte Konfiguration wird zur Laufzeit des Containers als Argumente übergeben.

=== 4.1.3 Wenn die Proxy-Datei kubeconfig existiert, stellen Sie sicher, dass die Berechtigungen auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test -e /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig; then stat -c permissions=%a /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig; fi'
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 600, erwartet 600 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=600
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Dateispeicherort auf Ihrem System) auf jedem Arbeitsknoten aus.
Zum Beispiel,
`+chmod 600 /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig+`
======

=== 4.1.4 Wenn die Proxy-Datei kubeconfig existiert, stellen Sie sicher, dass der Eigentümer auf root:root gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test -e /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig; then stat -c %U:%G /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig; fi'
----

*Erwartetes Ergebnis:* 'root:root' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
root:root
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Dateispeicherort auf Ihrem System) auf jedem Arbeitsknoten aus.
Zum Beispiel, `+chown root:root /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig+`
======

=== 4.1.5 Vergewissern Sie sich, dass die Berechtigungen für die Datei --kubeconfig kubelet.conf auf 600 oder restriktiver gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test -e /var/lib/rancher/k3s/agent/kubelet.kubeconfig; then stat -c permissions=%a /var/lib/rancher/k3s/agent/kubelet.kubeconfig; fi'
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 600, erwartet 600 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=600
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Dateispeicherort auf Ihrem System) auf jedem Arbeitsknoten aus.
Zum Beispiel,
`+chmod 600 /var/lib/rancher/k3s/agent/kubelet.kubeconfig+`
======

=== 4.1.6 Vergewissern Sie sich, dass die --kubeconfig kubelet.conf Datei auf root:root gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
stat -c %U:%G /var/lib/rancher/k3s/agent/kubelet.kubeconfig
----

*Erwartetes Ergebnis:* 'root:root' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
root:root
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl (basierend auf dem Dateispeicherort auf Ihrem System) auf jedem Arbeitsknoten aus.
Zum Beispiel,
`+chown root:root /var/lib/rancher/k3s/agent/kubelet.kubeconfig+`
======

=== 4.1.7 Stellen Sie sicher, dass die Dateiberechtigungen für die Zertifizierungsstellen auf 600 oder restriktiver eingestellt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
stat -c permissions=%a /var/lib/rancher/k3s/agent/client-ca.crt
----

*Erwartetes Ergebnis:* Berechtigungen hat Berechtigungen 600, erwartet 600 oder restriktiver

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
permissions=600
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl aus, um die Dateiberechtigungen für die Datei--client-ca-file zu ändern `+chmod 600 /var/lib/rancher/k3s/agent/client-ca.crt+`
======

=== 4.1.8 Stellen Sie sicher, dass die Eigentümerschaft der Client-Zertifizierungsstellen-Datei auf root:root (automatisiert) gesetzt ist.

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
stat -c %U:%G /var/lib/rancher/k3s/agent/client-ca.crt
----

*Erwartetes Ergebnis:* 'root:root' ist gleich 'root:root'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
root:root
----
======

.*Abhilfe:*
[%collapsible]
======
Führen Sie den folgenden Befehl aus, um die Eigentumsrechte an der Datei --client-ca zu ändern.
`+chown root:root /var/lib/rancher/k3s/agent/client-ca.crt+`
======

=== 4.1.9 Vergewissern Sie sich, dass die Konfigurationsdatei kubelet --config die Berechtigungen 600 oder restriktiver eingestellt hat (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Das Kubelet ist in den k3s-Prozess eingebettet. Es gibt keine Kubelet-Konfigurationsdatei, die gesamte Konfiguration wird zur Laufzeit als Argumente übergeben.

=== 4.1.10 Sicherstellen, dass der Eigentümer der Konfigurationsdatei kubelet --config auf root:root gesetzt ist (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Das Kubelet ist in den k3s-Prozess eingebettet. Es gibt keine Kubelet-Konfigurationsdatei, die gesamte Konfiguration wird zur Laufzeit als Argumente übergeben.

== 4.2 Kubelet

=== 4.2.1 Sicherstellen, dass das Argument --anonymous-auth auf false gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test $(journalctl -D /var/log/journal -u k3s | grep "Running kube-apiserver" | wc -l) -gt 0; then journalctl -D /var/log/journal -u k3s | grep "Running kube-apiserver" | tail -n1 | grep "anonymous-auth" | grep -v grep; else echo "--anonymous-auth=false"; fi'
----

*Erwartetes Ergebnis:* '--anonymous-auth' ist gleich 'false'.

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
K3s setzt die --anonymous-auth standardmäßig auf false. Wenn Sie diesen Wert auf einen anderen Wert gesetzt haben, sollten Sie ihn auf false zurücksetzen. Wenn Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, entfernen Sie alle Zeilen, die der folgenden ähneln.

----
kubelet-arg:
  - "anonymous-auth=true"
----

Wenn Sie die Kommandozeile verwenden, bearbeiten Sie die K3s-Dienstdatei und entfernen Sie das unten stehende Argument.--kubelet-arg="anonymous-auth=true" Starten Sie den k3s-Dienst je nach System neu. Zum Beispiel: systemctl daemon-reload systemctl restart k3s.service
======

=== 4.2.2 Stellen Sie sicher, dass das Argument --authorization-mode nicht auf AlwaysAllow (Automated) gesetzt ist.

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test $(journalctl -D /var/log/journal -u k3s | grep "Running kube-apiserver" | wc -l) -gt 0; then journalctl -D /var/log/journal -u k3s | grep "Running kube-apiserver" | tail -n1 | grep "authorization-mode"; else echo "--authorization-mode=Webhook"; fi'
----

*Erwartetes Ergebnis:* '--authorization-mode' hat nicht 'AlwaysAllow'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s den --authorization-mode nicht auf AlwaysAllow.
Wenn Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, entfernen Sie alle Zeilen, die der folgenden ähneln.

----
kubelet-arg:
  - "authorization-mode=AlwaysAllow"
----

Wenn Sie die Kommandozeile verwenden, bearbeiten Sie die K3s-Dienstdatei und entfernen Sie das unten stehende Argument.--kubelet-arg="authorization-mode=AlwaysAllow" Starten Sie den k3s-Dienst je nach System neu. Zum Beispiel: systemctl daemon-reload systemctl restart k3s.service
======

=== 4.2.3 Stellen Sie sicher, dass das Argument --client-ca-file entsprechend gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
/bin/sh -c 'if test $(journalctl -D /var/log/journal -u k3s | grep "Running kube-apiserver" | wc -l) -gt 0; then journalctl -D /var/log/journal -u k3s | grep "Running kube-apiserver" | tail -n1 | grep "client-ca-file"; else echo "--client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt"; fi'
----

*Erwartetes Ergebnis:* '--client-ca-file' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:17 server-0 k3s[2357]: time="2024-08-09T19:06:17Z" level=info msg="Running kube-apiserver --admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml --advertise-address=10.10.10.100 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log --audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/k3s/server/cred/encryption-config.json --encryption-provider-config-automatic-reload=true --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig stellt K3s automatisch das Client-Ca-Zertifikat für das Kubelet bereit.
Sie wird erzeugt und befindet sich unter /var/lib/rancher/k3s/agent/client-ca.crt
======

=== 4.2.4 Überprüfen Sie, ob das Argument --read-only-port auf 0 gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s -u k3s-agent | grep 'Running kubelet' | tail -n1
----

*Erwartetes Ergebnis:* '--read-only-port' ist gleich '0' ODER '--read-only-port' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:19 server-0 k3s[2357]: time="2024-08-09T19:06:19Z" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --event-qps=0 --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=CloudDualStackNodeIPs=true --healthz-bind-address=127.0.0.1 --hostname-override=server-0 --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --make-iptables-util-chains=true --node-ip=10.10.10.100 --node-labels= --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --protect-kernel-defaults=true --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --streaming-connection-idle-timeout=5m --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s den --read-only-port auf 0. Wenn Sie diesen Wert auf einen anderen Wert gesetzt haben, sollten Sie ihn wieder auf 0 setzen. Wenn Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, entfernen Sie alle Zeilen, die der folgenden ähneln.

----
kubelet-arg:
  - "read-only-port=XXXX"
----

Wenn Sie die Kommandozeile verwenden, bearbeiten Sie die K3s-Dienstdatei und entfernen Sie das unten stehende Argument.--kubelet-arg="read-only-port=XXXX" Starten Sie den k3s-Dienst je nach Ihrem System neu. Zum Beispiel: systemctl daemon-reload systemctl restart k3s.service
======

=== 4.2.5 Stellen Sie sicher, dass das Argument --streaming-connection-idle-timeout nicht auf 0 gesetzt ist (Manual)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s -u k3s-agent | grep 'Running kubelet' | tail -n1
----

*Erwartetes Ergebnis:* '--streaming-connection-idle-timeout' ist ungleich '0' ODER '--streaming-connection-idle-timeout' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:19 server-0 k3s[2357]: time="2024-08-09T19:06:19Z" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --event-qps=0 --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=CloudDualStackNodeIPs=true --healthz-bind-address=127.0.0.1 --hostname-override=server-0 --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --make-iptables-util-chains=true --node-ip=10.10.10.100 --node-labels= --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --protect-kernel-defaults=true --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --streaming-connection-idle-timeout=5m --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, setzen Sie den folgenden Parameter auf einen geeigneten Wert.

----
kubelet-arg:
  - "streaming-connection-idle-timeout=5m"
----

Wenn Sie die Kommandozeile verwenden, führen Sie K3s mit --kubelet-arg="streaming-connection-idle-timeout=5m" aus.
Starten Sie den k3s-Dienst auf Ihrem System neu. Zum Beispiel: systemctl restart k3s.service
======

=== 4.2.6 Stellen Sie sicher, dass das Argument --make-iptables-util-chains auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s -u k3s-agent | grep 'Running kubelet' | tail -n1
----

*Erwartetes Ergebnis:* '--make-iptables-util-chains' ist gleich 'true' ODER '--make-iptables-util-chains' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:19 server-0 k3s[2357]: time="2024-08-09T19:06:19Z" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --event-qps=0 --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=CloudDualStackNodeIPs=true --healthz-bind-address=127.0.0.1 --hostname-override=server-0 --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --make-iptables-util-chains=true --node-ip=10.10.10.100 --node-labels= --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --protect-kernel-defaults=true --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --streaming-connection-idle-timeout=5m --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, setzen Sie den folgenden Parameter.

----
kubelet-arg:
  - "make-iptables-util-chains=true"
----

Wenn Sie die Kommandozeile verwenden, führen Sie K3s mit --kubelet-arg="make-iptables-util-chains=true" aus.
Starten Sie den k3s-Dienst auf Ihrem System neu. Zum Beispiel: systemctl restart k3s.service
======

=== 4.2.7 Sicherstellen, dass das Argument --hostname-override nicht gesetzt ist (automatisiert)

*Ergebnis:* Nicht anwendbar

*Begründung:*

Standardmäßig setzt K3s das Argument --hostname-override. Gemäß den CIS-Richtlinien dient dies der Einhaltung von Cloud-Anbietern, die dieses Flag verlangen, um sicherzustellen, dass der Hostname mit den Knotennamen übereinstimmt.

=== 4.2.8 Stellen Sie sicher, dass das Argument eventRecordQPS auf einen Wert gesetzt ist, der eine angemessene Erfassung von Ereignissen gewährleistet (manuell)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s -u k3s-agent | grep 'Running kubelet' | tail -n1
----

*Erwartetes Ergebnis:* '--event-qps' ist größer oder gleich 0 ODER '--event-qps' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:19 server-0 k3s[2357]: time="2024-08-09T19:06:19Z" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --event-qps=0 --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=CloudDualStackNodeIPs=true --healthz-bind-address=127.0.0.1 --hostname-override=server-0 --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --make-iptables-util-chains=true --node-ip=10.10.10.100 --node-labels= --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --protect-kernel-defaults=true --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --streaming-connection-idle-timeout=5m --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s die Ereignis-qps auf 0. Sollten Sie dies ändern wollen, setzen Sie bei Verwendung der K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml den folgenden Parameter auf einen geeigneten Wert.

----
kubelet-arg:
  - "event-qps=<value>"
----

Wenn Sie die Kommandozeile verwenden, führen Sie K3s mit --kubelet-arg="event-qps=<value>" aus.
Starten Sie den k3s-Dienst auf Ihrem System neu. Zum Beispiel: systemctl restart k3s.service
======

=== 4.2.9 Stellen Sie sicher, dass die Argumente --tls-cert-file und --tls-private-key-file entsprechend gesetzt sind (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s -u k3s-agent | grep 'Running kubelet' | tail -n1
----

*Erwartetes Ergebnis:* '--tls-cert-file' ist vorhanden UND '--tls-private-key-file' ist vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:19 server-0 k3s[2357]: time="2024-08-09T19:06:19Z" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --event-qps=0 --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=CloudDualStackNodeIPs=true --healthz-bind-address=127.0.0.1 --hostname-override=server-0 --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --make-iptables-util-chains=true --node-ip=10.10.10.100 --node-labels= --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --protect-kernel-defaults=true --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --streaming-connection-idle-timeout=5m --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig stellt K3s automatisch das TLS-Zertifikat und den privaten Schlüssel für das Kubelet bereit.
Sie werden generiert und befinden sich unter /var/lib/rancher/k3s/agent/serving-kubelet.crt und /var/lib/rancher/k3s/agent/serving-kubelet.key. Wenn Sie aus irgendeinem Grund Ihr eigenes Zertifikat und Ihren eigenen Schlüssel bereitstellen müssen, können Sie die folgenden Parameter in der K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml festlegen.

----
kubelet-arg:
  - "tls-cert-file=<path/to/tls-cert-file>"
  - "tls-private-key-file=<path/to/tls-private-key-file>"
----
======

=== 4.2.10 Sicherstellen, dass das Argument --rotate-certificates nicht auf false gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s -u k3s-agent | grep 'Running kubelet' | tail -n1
----

*Erwartetes Ergebnis:* '.rotateCertificates' ist vorhanden ODER '.rotateCertificates' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6443
    certificate-authority: /var/lib/rancher/k3s/agent/server-ca.crt
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate: /var/lib/rancher/k3s/agent/client-kubelet.crt
    client-key: /var/lib/rancher/k3s/agent/client-kubelet.key
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das Argument --rotate-certificates nicht. Wenn Sie dieses Kennzeichen mit einem Wert von `+false+` gesetzt haben, sollten Sie es entweder auf `+true+` setzen oder das Kennzeichen vollständig entfernen.
Wenn Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, entfernen Sie alle rotate-certificates-Parameter.
Wenn Sie die Kommandozeile verwenden, entfernen Sie das K3s-Flag --kubelet-arg="rotate-certificates".
Starten Sie den k3s-Dienst auf Ihrem System neu. Zum Beispiel: systemctl restart k3s.service
======

=== 4.2.11 Überprüfen, ob das Argument RotateKubeletServerCertificate auf true gesetzt ist (automatisiert)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s -u k3s-agent | grep 'Running kubelet' | tail -n1
----

*Erwartetes Ergebnis:* '.featureGates.RotateKubeletServerCertificate' ist vorhanden ODER '.featureGates.RotateKubeletServerCertificate' ist nicht vorhanden

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6443
    certificate-authority: /var/lib/rancher/k3s/agent/server-ca.crt
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate: /var/lib/rancher/k3s/agent/client-kubelet.crt
    client-key: /var/lib/rancher/k3s/agent/client-kubelet.key
----
======

.*Abhilfe:*
[%collapsible]
======
Standardmäßig setzt K3s das RotateKubeletServerCertificate Feature Gate nicht.
Wenn Sie diese Funktion aktiviert haben, sollten Sie sie entfernen.
Wenn Sie die K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, entfernen Sie den Parameter feature-gate=RotateKubeletServerCertificate.
Wenn Sie die Kommandozeile verwenden, entfernen Sie das K3s-Flag --kubelet-arg="feature-gate=RotateKubeletServerCertificate".
Starten Sie den k3s-Dienst auf Ihrem System neu. Zum Beispiel: systemctl restart k3s.service
======

=== 4.2.12 Sicherstellen, dass das Kubelet nur starke kryptographische Chiffren verwendet (manuell)

*Ergebnis:* PASS

*Prüfung:*

[,bash]
----
journalctl -u k3s -u k3s-agent | grep 'Running kubelet' | tail -n1
----

*Erwartetes Ergebnis:* '--tls-cipher-suites' enthält gültige Elemente aus 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256'

.*Zurückgegebener Wert:*
[%collapsible]
======
[,console]
----
Aug 09 19:06:19 server-0 k3s[2357]: time="2024-08-09T19:06:19Z" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --event-qps=0 --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=CloudDualStackNodeIPs=true --healthz-bind-address=127.0.0.1 --hostname-override=server-0 --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --make-iptables-util-chains=true --node-ip=10.10.10.100 --node-labels= --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --protect-kernel-defaults=true --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --streaming-connection-idle-timeout=5m --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
----
======

.*Abhilfe:*
[%collapsible]
======
Wenn Sie eine K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, bearbeiten Sie die Datei und setzen Sie `+TLSCipherSuites+` auf

----
kubelet-arg:
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
----

oder auf eine Teilmenge dieser Werte.
Wenn Sie die Befehlszeile verwenden, fügen Sie das K3s-Flag hinzu --kubelet-arg="tls-cipher-suites=<same values as above>" Starten Sie je nach System den k3s-Dienst neu. Zum Beispiel: systemctl restart k3s.service
======

=== 4.2.13 Sicherstellen, dass ein Grenzwert für Pod-PIDs festgelegt ist (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Wenn Sie eine K3s-Konfigurationsdatei /etc/rancher/k3s/config.yaml verwenden, bearbeiten Sie die Datei und setzen Sie `+podPidsLimit+` auf

----
kubelet-arg:
  - "pod-max-pids=<value>"
----

== 5.1 RBAC und Dienstkonten

=== 5.1.1 Sicherstellen, dass die Rolle "cluster-admin" nur bei Bedarf verwendet wird (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Identifizieren Sie alle Clusterrolebindings für die Rolle cluster-admin. Prüfen Sie, ob sie verwendet werden und ob sie diese Rolle benötigen oder ob sie eine Rolle mit weniger Rechten verwenden könnten.
Wenn möglich, binden Sie die Benutzer zunächst an eine weniger privilegierte Rolle und entfernen Sie dann die Clusterrolebindung an die Cluster-Admin-Rolle: kubectl delete clusterrolebinding [name]

=== 5.1.2 Zugang zu Geheimnissen minimieren (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Wenn möglich, entfernen Sie den Zugriff auf die geheimen Objekte im Cluster (get, list und watch).

=== 5.1.3 Minimierung der Verwendung von Platzhaltern in Rollen und ClusterRoles (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Ersetzen Sie nach Möglichkeit die Verwendung von Platzhaltern in Clusterrollen und Rollen durch spezifische Objekte oder Aktionen.

=== 5.1.4 Zugang zur Erstellung von Pods minimieren (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Wenn möglich, entfernen Sie den Zugriff auf Pod-Objekte im Cluster.

=== 5.1.5 Stellen Sie sicher, dass die Standarddienstkonten nicht aktiv verwendet werden. (Handbuch)

*Ergebnis:* WARN

*Abhilfe:*
Erstellen Sie explizite Dienstkonten, wenn eine Kubernetes-Arbeitslast spezifischen Zugriff auf den Kubernetes-API-Server erfordert.
Ändern Sie die Konfiguration jedes Standarddienstkontos, um diesen Wert aufzunehmen automountServiceAccountToken: false

=== 5.1.6 Sicherstellen, dass Service Account Tokens nur dort angebracht werden, wo es notwendig ist (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Ändern Sie die Definition von Pods und Dienstkonten, die keine Dienstkonten-Token einbinden müssen, um dies zu deaktivieren.

=== 5.1.7 Die Verwendung der Gruppe system:masters vermeiden (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Entfernen Sie die Gruppe system:masters aus allen Benutzern des Clusters.

=== 5.1.8 Beschränkung der Verwendung der Berechtigungen Bind, Impersonate und Escalate im Kubernetes-Cluster (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Entziehen Sie, wenn möglich, den betroffenen Personen die Rechte "Impersonate", "Bind" und "Escalate".

=== 5.1.9 Zugriff minimieren, um persistente Volumes zu erstellen (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Wenn möglich, entfernen Sie den Zugriff auf PersistentVolume-Objekte im Cluster.

=== 5.1.10 Minimierung des Zugriffs auf die Proxy-Subressource von Knoten (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Wenn möglich, entfernen Sie den Zugriff auf die Proxy-Sub-Ressource von Knotenobjekten.

=== 5.1.11 Minimierung des Zugriffs auf die Genehmigungs-Subressource von Zertifikatsignierungsanfragen-Objekten (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Wenn möglich, sollte der Zugriff auf die Genehmigungs-Subressource von certificatesigningrequest-Objekten entfernt werden.

=== 5.1.12 Zugriff auf Webhook-Konfigurationsobjekte minimieren (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Wenn möglich, entfernen Sie den Zugriff auf die Objekte validatingwebhookconfigurations oder mutatingwebhookconfigurations

=== 5.1.13 Zugriff auf die Token-Erstellung für das Dienstkonto minimieren (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Wenn möglich, entfernen Sie den Zugriff auf die Token-Subressource von serviceaccount-Objekten.

== 5.2 Sicherheitsstandards für Pods

=== 5.2.1 Sicherstellen, dass der Cluster über mindestens einen aktiven Richtlinienkontrollmechanismus verfügt (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Stellen Sie sicher, dass entweder Pod Security Admission oder ein externes Richtlinienkontrollsystem für jeden Namespace, der Benutzer-Workloads enthält, vorhanden ist.

=== 5.2.2 Minimierung der Zulassung privilegierter Container (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie jedem Namespace im Cluster, der Benutzer-Workloads enthält, Richtlinien hinzu, um die Zulassung von privilegierten Containern zu beschränken.

=== 5.2.3 Minimierung der Zulassung von Containern, die den Namespace der Host-Prozess-ID gemeinsam nutzen wollen (automatisiert)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie Richtlinien zu jedem Namespace im Cluster hinzu, der Benutzer-Workloads hat, um die Zulassung von `+hostPID+` Containern zu beschränken.

=== 5.2.4 Minimierung der Zulassung von Containern, die den IPC-Namensraum des Hosts gemeinsam nutzen wollen (automatisiert)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie Richtlinien zu jedem Namespace im Cluster hinzu, der Benutzer-Workloads hat, um die Zulassung von `+hostIPC+` Containern zu beschränken.

=== 5.2.5 Minimierung der Zulassung von Containern, die den Host-Netzwerk-Namensraum gemeinsam nutzen wollen (automatisiert)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie Richtlinien zu jedem Namespace im Cluster hinzu, der Benutzer-Workloads hat, um die Zulassung von `+hostNetwork+` Containern zu beschränken.

=== 5.2.6 Minimierung der Zulassung von Containern mit allowPrivilegeEscalation (automatisiert)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie Richtlinien zu jedem Namespace im Cluster hinzu, der Benutzer-Workloads hat, um die Zulassung von Containern mit `+.spec.allowPrivilegeEscalation+` auf `+true+` zu beschränken.

=== 5.2.7 Minimierung der Aufnahme von Wurzelbehältern (automatisiert)

*Ergebnis:* WARN

*Abhilfe:*
Erstellen Sie eine Richtlinie für jeden Namespace im Cluster und stellen Sie sicher, dass entweder `+MustRunAsNonRoot+`oder `+MustRunAs+` mit dem Bereich der UIDs, der 0 nicht einschließt, eingestellt ist.

=== 5.2.8 Minimierung der Zulassung von Containern mit der Fähigkeit NET_RAW (automatisiert)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie Richtlinien zu jedem Namespace im Cluster hinzu, der Benutzer-Workloads hat, um die Zulassung von Containern mit der Fähigkeit `+NET_RAW+` zu beschränken.

=== 5.2.9 Minimierung der Zulassung von Containern mit zusätzlichen Fähigkeiten (automatisiert)

*Ergebnis:* WARN

*Abhilfe:*
Stellen Sie sicher, dass `+allowedCapabilities+` in den Richtlinien für den Cluster nicht vorhanden ist, es sei denn, es wird auf ein leeres Array gesetzt.

=== 5.2.10 Minimierung der Zulassung von Containern mit zugewiesenen Fähigkeiten (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Überprüfen Sie die Verwendung von Fähigkeiten in Anwendungen, die auf Ihrem Cluster laufen. Wenn ein Namensraum Anwendungen enthält, die keine Linux-Fähigkeiten zum Betrieb benötigen, sollte ein PSP hinzugefügt werden, der die Zulassung von Containern verbietet, die nicht alle Fähigkeiten ablegen.

=== 5.2.11 Minimierung der Zulassung von Windows HostProcess-Containern (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie Richtlinien zu jedem Namespace im Cluster hinzu, der über Benutzer-Workloads verfügt, um die Zulassung von Containern zu beschränken, deren `+.securityContext.windowsOptions.hostProcess+` auf `+true+` eingestellt ist.

=== 5.2.12 Minimierung der Zulassung von HostPath-Volumes (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie Richtlinien zu jedem Namespace im Cluster hinzu, der Benutzer-Workloads hat, um die Zulassung von Containern mit `+hostPath+` Volumes zu beschränken.

=== 5.2.13 Minimierung der Zulassung von Containern, die HostPorts verwenden (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Fügen Sie Richtlinien zu jedem Namespace im Cluster hinzu, der Benutzer-Workloads hat, um die Zulassung von Containern zu beschränken, die `+hostPort+` Abschnitte verwenden.

== 5.3 Netzpolitiken und CNI

=== 5.3.1 Sicherstellen, dass die eingesetzte CNI NetworkPolicies (Manual) unterstützt

*Ergebnis:* WARN

*Abhilfe:*
Wenn das verwendete CNI-Plugin keine Netzwerkrichtlinien unterstützt, sollte die Verwendung eines anderen Plugins in Betracht gezogen oder ein alternativer Mechanismus zur Beschränkung des Datenverkehrs im Kubernetes-Cluster gefunden werden.

=== 5.3.2 Sicherstellen, dass in allen Namensräumen NetworkPolicies definiert sind (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Folgen Sie der Dokumentation und erstellen Sie NetworkPolicy-Objekte, wenn Sie sie benötigen.

== 5.4 Verwaltung von Geheimnissen

=== 5.4.1 Secrets als Dateien gegenüber Secrets als Umgebungsvariablen bevorzugen (Manual)

*Ergebnis:* WARN

*Abhilfe:*
Wenn möglich, schreiben Sie den Anwendungscode so um, dass er Geheimnisse aus eingebundenen geheimen Dateien und nicht aus Umgebungsvariablen liest.

=== 5.4.2 Externe geheime Speicherung in Betracht ziehen (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Informieren Sie sich über die Optionen zur Verwaltung von Geheimnissen, die Ihr Cloud-Anbieter oder eine Drittanbieterlösung zur Verwaltung von Geheimnissen anbietet.

== 5.5 Erweiterbare Zulassungskontrolle

=== 5.5.1 Image Provenance mit ImagePolicyWebhook-Zulassungssteuerung konfigurieren (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Befolgen Sie die Kubernetes-Dokumentation und richten Sie die Image-Provenance ein.

== 5.7 Allgemeine Politiken

=== 5.7.1 Administrative Grenzen zwischen Ressourcen mit Hilfe von Namensräumen erstellen (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Folgen Sie der Dokumentation und erstellen Sie bei Bedarf Namespaces für Objekte in Ihrem Einsatz.

=== 5.7.2 Stellen Sie sicher, dass das seccomp-Profil in Ihren Pod-Definitionen auf docker/default eingestellt ist (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Verwenden Sie `+securityContext+`, um das seccomp-Profil von docker/default in Ihren Pod-Definitionen zu aktivieren.
Ein Beispiel ist wie folgt: securityContext: seccompProfile: type: RuntimeDefault

=== 5.7.3 SecurityContext auf Ihre Pods und Container anwenden (manuell)

*Ergebnis:* WARN

*Abhilfe:*
Folgen Sie der Kubernetes-Dokumentation und wenden Sie SecurityContexts auf Ihre Pods an. Eine vorgeschlagene Liste von SecurityContexts finden Sie in der CIS Security Benchmark for Docker Containers.

=== 5.7.4 Der Standard-Namensraum sollte nicht verwendet werden (Manual)

*Ergebnis:* WARN

*Abhilfe:*
Stellen Sie sicher, dass Namespaces erstellt werden, um eine angemessene Trennung der Kubernetes-Ressourcen zu ermöglichen, und dass alle neuen Ressourcen in einem bestimmten Namespace erstellt werden.
