= Über StackPacks
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet v5.1.x

== Übersicht

StackPacks erweitern die Funktionen von SUSE Observability und bieten eine automatische Integration mit externen Systemen. Sie können einfach über die Seite StackPacks in SUSE Observability installiert und deinstalliert werden.

Es gibt zwei Arten von StackPack - Add-ons und Integrationen. Die verfügbaren StackPack-Add-ons und -Integrationen finden Sie auf der Seite *StackPacks* in der SUSE Observability-Benutzeroberfläche.

== Installieren oder Deinstallieren eines StackPacks

StackPacks können über die Seite *StackPacks* in SUSE Observability installiert und deinstalliert werden. Eine ausführliche Anleitung zur Installation und Deinstallation des StackPack wird bereitgestellt.

[NOTE]
====
*Beachten Sie das:*

* Ein StackPack kann *manuelle* Installationsschritte oder die Konfiguration des externen Systems erfordern. Bitte lesen Sie die mitgelieferten Anweisungen sorgfältig durch.
* Wenn ein StackPack oder eine StackPack-Instanz deinstalliert wird, *werden alle Daten, die über das StackPack (die Instanz) empfangen wurden, aus SUSE Observability entfernt.*
* Jede (manuelle) Konfiguration oder Installation von StackPack-Komponenten in einem externen System muss möglicherweise separat deinstalliert werden.

====


=== StackPack-Instanzen

Einige StackPacks ermöglichen es Ihnen, sich mit mehreren Konten auf einem externen System zu verbinden. Jedes Konto wird in einer eigenen Instanz des StackPack konfiguriert.

So kann das AWS StackPack beispielsweise eine Verbindung zu mehreren AWS-Konten herstellen und Informationen von allen Konten in SUSE Observability zusammenführen. Für jedes Konto wird eine separate SUSE Observability-Instanz mit den Informationen konfiguriert, die für den Empfang von Daten von diesem AWS-Konto erforderlich sind.

== Upgrade eines StackPacks

[CAUTION]
====
Wenn ein StackPack aktualisiert wird, *werden alle Änderungen, die an den Konfigurationselementen dieses StackPacks vorgenommen wurden, überschrieben*. Einzelheiten finden Sie unter xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[Gesperrte Konfigurationselemente].
====


Wenn eine neue StackPack-Version verfügbar ist, wird auf der SUSE Observability UI StackPack-Seite eine Warnung angezeigt und Sie haben die Möglichkeit, die Upgrade-Details anzuzeigen und die Versionshinweise zu lesen. Wenn es sich bei der neuen Version um ein kleineres Upgrade gegenüber der aktuell installierten Version handelt, können Sie das StackPack auch von hier aus aktualisieren.

=== Neue kleinere StackPack-Version

Um ein Upgrade auf eine neue Minor-Version eines StackPacks durchzuführen, klicken Sie auf der StackPack-Seite in der SUSE Observability-Benutzeroberfläche auf *JETZT UPGRADE*.

Beachten Sie, dass alle StackPack-Konfigurationselemente beim Upgrade überschrieben werden. Wenn Sie die vorgenommenen Änderungen beibehalten möchten, wählen Sie beim Upgrade des StackPack die Option *KEEP* the existing configuration. Einzelheiten finden Sie unter xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[Gesperrte Konfigurationselemente].

=== Neue Hauptversion von StackPack

[CAUTION]
====
Wenn ein StackPack aktualisiert wird, *werden alle Änderungen, die an den Konfigurationselementen dieses StackPacks vorgenommen wurden, überschrieben*. Einzelheiten finden Sie unter xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[Gesperrte Konfigurationselemente].
====


Um auf eine neue Hauptversion eines StackPacks zu aktualisieren, xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[deinstallieren Sie] das StackPack xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[und installieren Sie] es xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[neu].

[TIP]
====

Verwenden Sie nach dem Upgrade weiterhin die Änderungen, die an den benutzerdefinierten StackPack-Konfigurationsobjekten vorgenommen wurden:

. Bevor Sie ein Upgrade durchführen, exportieren Sie jedes benutzerdefinierte Element:
 ** Rufen Sie die Seite *Einstellungen* in der SUSE Observability-Benutzeroberfläche auf.
 ** Klicken Sie auf *Exportieren* im *...* Menü für jedes angepasste Element.
. Aktualisieren Sie das StackPack (deinstallieren und neu installieren).
. Ändern Sie die `name` und `identifier` für jeden exportierten Artikel:
 ** Öffnen Sie die Exportdatei in einem Texteditor.
 ** Bearbeiten Sie die Felder der obersten Ebene `name` und `identifier`.
 ** Speichern Sie den Export.
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[Importieren Sie] die aktualisierte(n) Exportdatei(en).
. Die angepassten Konfigurationselemente sind nun in SUSE Observability verfügbar und können in die neu installierten StackPack-Konfigurationselemente kopiert werden.

====


== Gesperrte Konfigurationselemente

StackPacks enthalten Konfigurationsinformationen für SUSE Observability, die bei der Installation des StackPacks (Instanz) installiert werden. Dabei kann es sich unter anderem um Komponentenvorlagen, Funktionen, Komponentenaktionen und Ansichten handeln. Wenn ein StackPack aktualisiert wird, *werden die Konfigurationselemente, die von der vorherigen Version des StackPacks installiert wurden, mit denen des neueren StackPacks überschrieben.* Das bedeutet, dass jede manuelle Änderung dieser Konfigurationselemente überschrieben wird, wenn das StackPack aktualisiert wird.

Um zu verhindern, dass ein Benutzer Änderungen an den von einem StackPack installierten Konfigurationselementen vornimmt, die bei einem Upgrade überschrieben werden, sind diese Konfigurationselemente standardmäßig *gesperrt*. Das bedeutet, dass sie vor Änderungen durch den Benutzer geschützt sind und explizit *freigeschaltet* werden müssen, bevor sie geändert werden können.

[TIP]
====

Sie können xref:/setup/data-management/backup_restore/configuration_backup.adoc[eine Sicherungskopie der Konfigurationsdaten erstellen]. Beachten Sie, dass der Sperrstatus von Konfigurationselementen nicht als Teil einer Konfigurationssicherung exportiert wird.
====

