= Parando o K3s
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-26
:page-revdate: {revdate}

Para permitir alta disponibilidade durante os upgrades, os contêineres do K3s continuam em execução quando o serviço do K3s é interrompido.

== Serviço K3s

A interrupção e a reinicialização do K3s são compatíveis com o script de instalação do systemd e do OpenRC.

[tabs]
======
systemd::
+
--
Para parar os servidores:

[,sh]
----
sudo systemctl stop k3s
----

Para reiniciar os servidores:

[,sh]
----
sudo systemctl start k3s
----

Para interromper os agentes:

[,sh]
----
sudo systemctl stop k3s-agent
----

Para reiniciar os agentes:

[,sh]
----
sudo systemctl start k3s-agent
----
--

OpenRC::
+
--
Para parar os servidores:

[,sh]
----
sudo rc-service k3s stop
----

Para reiniciar os servidores:

[,sh]
----
sudo rc-service k3s restart
----

Para interromper os agentes:

[,sh]
----
sudo rc-service k3s-agent stop
----

Para reiniciar os agentes:

[,sh]
----
sudo rc-service k3s-agent restart
----
--
======

== Script Killall

Para interromper todos os contêineres do K3s e redefinir o estado do containerd, o script `k3s-killall.sh` pode ser usado.

O script killall limpa contêineres, diretórios K3s e componentes de rede, além de remover a cadeia iptables com todas as regras associadas. Os dados do cluster não serão excluídos.

Para executar o script killall em um nó do servidor, execute:

[,bash]
----
/usr/local/bin/k3s-killall.sh
----
