= Atualizações
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

== Atualizando seu cluster K3s

xref:upgrades/manual.adoc[Upgrades manuais] descreve várias técnicas para fazer upgrade do cluster manualmente. Ele também pode ser usado como base para a atualização por meio de ferramentas de infraestrutura como código de terceiros, como o https://www.terraform.io/[Terraform].

xref:upgrades/automated.adoc[As atualizações automatizadas] descrevem como realizar atualizações automatizadas nativas do Kubernetes usando o https://github.com/rancher/system-upgrade-controller[controlador de atualização do sistema] do Rancher.

== Advertências específicas da versão

* *Traefik:* Se o Traefik não estiver desativado, as versões 1.20 e anteriores do K3s instalarão o Traefik v1, enquanto as versões 1.21 e posteriores do K3s instalarão o Traefik v2, se o v1 ainda não estiver presente. Para atualizar do Traefik v1 mais antigo para o Traefik v2, consulte a https://doc.traefik.io/traefik/migrate/v1-to-v2/[documentação do Traefik em] e use a https://github.com/traefik/traefik-migration-tool[].
* *Dados de bootstrap do K3s:* Se você estiver usando o K3s em uma configuração de HA com um datastore SQL externo e os nós do servidor (plano de controle) não tiverem sido iniciados com o sinalizador `--token` CLI, não será mais possível adicionar outros servidores K3s ao cluster sem especificar o token. Certifique-se de manter uma cópia desse token, pois ele é necessário ao restaurar a partir do backup. Anteriormente, o K3s não impunha o uso de um token ao usar repositórios de dados SQL externos.
 ** As versões afetadas são <= v1.19.12+k3s1, v1.20.8+k3s1, v1.21.2+k3s1; as versões corrigidas são v1.19.13+k3s1, v1.20.9+k3s1, v1.21.3+k3s1.
 ** Você pode recuperar o valor do token de qualquer servidor já associado ao cluster da seguinte forma:
+
[,bash]
----
cat /var/lib/rancher/k3s/server/token
----
