include::../common/generic-attributes.adoc[]

[#pr-helm-chart-override]
== Surcharge du graphique {productname} {helm}
:revdate: 2025-10-15
:page-revdate: {revdate}

Le graphique {productname} ({productnameshort}) {helm} est livrﾃｩ avec des valeurs par dﾃｩfaut.
Vous pouvez ajuster {helm} l'installation du graphique de l'une des maniﾃｨres suivantes :

* Ajoutez des paramﾃｨtres spﾃｩcifiques aux indicateurs `+--set+` sur la ligne de commande `+helm install+`, par exemple :
[source]
$ helm install <RELEASE_NAME> \
oci://registry.suse.com/private-registry/private-registry-helm \
--namespace <PRIVATE_REGISTRY_NAMESPACE> \
--set harborAdminPassword=<MY_PASSWORD> \
--set externalURL=https://<PRIVATE_REGISTRY_FQDN> \
--set expose.ingress.hosts.core=<PRIVATE_REGISTRY_FQDN>
* Create a {suse} custom `+suse_registry_override.yaml+` file and pass it to the `+--f+` flag, for example:
[source]
  $ helm install <RELEASE_NAME> \
  oci://registry.suse.com/private-registry/private-registry-helm \
  --namespace <PRIVATE_REGISTRY_NAMESPACE>
  -f suse_registry_override.yaml

[#pr-helm-chart-override-examples]
=== Exemples de fichiers de surcharge {sregistry} {helm}
.Dﾃｩploiement minimal avec {ingress}
[example]
----
expose : +
  type : ingress //<1> +
  ingress : +
    hosts : +
      core : <PRIVATE_REGISTRY_FQDN> //<2>

externalURL : https://<PRIVATE_REGISTRY_FQDN> //<3>

harborAdminPassword : "<MY_PASSWORD>" //<4>

database : +
  internal : +
    password : "<MY_PASSWORD_POSTGRESQL>"

redis : +
  internal : +
   password : "<MY_PASSWORD_REDIS>"
----
[callouts]
<1> Comment {sregistry} est exposﾃｩ. Peut ﾃｪtre `+ingress+`, `+loadBalancer+`, `+nodePort+` ou `+clusterIPhis+`. La valeur par dﾃｩfaut est `+ingress+`.
<2> Nom d'hﾃｴte pour la configuration rﾃｩseau interne {kube}.
<3> URL oﾃｹ l'application {sregistry} s'exﾃｩcute. Il est utilisﾃｩ pour gﾃｩnﾃｩrer des liens dans l'interface utilisateur, des redirections et ﾃｩgalement pour les rﾃｩponses API.
<4> Le mot de passe administrateur de l'application.

.Dﾃｩploiement typique avec `+loadBalancer+`
[example]
----
expose:
  type: loadBalancer //<1>
  tls:
    enabled: true
    certSource: secret //<2>
    secret:
      secretName: <SECRET_NAME>

    auto:
      commonName: <PRIVATE_REGISTRY_FQDN> //<3>

externalURL : https://<PRIVATE_REGISTRY_FQDN> //<4>

harborAdminPassword : "<MY_PASSWORD>" //<5>

database : +
  internal : +
    password : "<MY_PASSWORD_POSTGRESQL>"

redis : +
  internal : +
   password : "<MY_PASSWORD_REDIS>"
----
[callouts]
<1> Comment {sregistry} est exposﾃｩ. Peut ﾃｪtre `+ingress+`, `+loadBalancer+`, `+nodePort+` ou `+clusterIP+`. La valeur par dﾃｩfaut est `+ingress+`.
<2> Peut ﾃｪtre `+auto+`, `+secret+` ou `+none+`. Selon l'option, vous devrez peut-ﾃｪtre inclure des valeurs supplﾃｩmentaires.
<3> Lors de l'utilisation du chiffrement TLS, ce champ doit correspondre ﾃ la valeur `+externalURL+`.
<4> URL oﾃｹ l'application {sregistry} s'exﾃｩcute. Il est utilisﾃｩ pour gﾃｩnﾃｩrer des liens dans l'interface utilisateur, des redirections et ﾃｩgalement pour les rﾃｩponses API.
<5> Le mot de passe administrateur de l'application.

[#pr-helm-chart-override-parameters]
=== Surcharge {helm} des paramﾃｨtres et valeurs du graphique.

Les tableaux suivants ﾃｩnumﾃｨrent tous les paramﾃｨtres avec des descriptions que vous pouvez utiliser pour surcharger les valeurs d'installation par dﾃｩfaut.

.Paramﾃｨtres globaux
`+global.imageRegistry+`:: Dﾃｩfinit une surcharge globale pour le registre d'images de conteneurs utilisﾃｩ pour toutes les images.
`+global.imagePullSecrets+`:: Dﾃｩfinit des secrets de tirage globaux pour accﾃｩder au registre d'images de conteneurs.

.Paramﾃｨtres communs
`+harborAdminPassword+`:: Dﾃｩfinit le mot de passe initial pour l'administrateur {harbor}. Modifiez-le depuis le portail aprﾃｨs le dﾃｩploiement. La valeur par dﾃｩfaut est `+Harbor12345+`.
`+externalURL+`:: Spﾃｩcifie l'URL externe pour le service `+harbor-core+`. La valeur par dﾃｩfaut est `+\https://core.harbor.domain+`.
`+existingSecretAdminPasswordKey+`:: Dﾃｩfinit le nom de clﾃｩ dans le secret contenant le mot de passe de l'administrateur {harbor}. La valeur par dﾃｩfaut est `+HARBOR_ADMIN_PASSWORD+`.
`+imagePullSecrets+`:: Dﾃｩfinit les noms `+imagePullSecrets+` pour tous les dﾃｩploiements.
`+updateStrategy.type+`:: Dﾃｩfinit la stratﾃｩgie de mise ﾃ jour pour les dﾃｩploiements avec des volumes persistants. Accepte `+RollingUpdate+` ou `+Recreate+`. Utilisez `+Recreate+` lorsque RWM pour les volumes n'est pas pris en charge. La valeur par dﾃｩfaut est `+RollingUpdate+`.
`+logLevel+`:: Dﾃｩfinit le niveau de journalisation pour les services {harbor}. Accepte `+fatal+`, `+error+`, `+warn+`, `+info+`, `+debug+` ou `+trace+`. La valeur par dﾃｩfaut est `+debug+`.
`+enableMigratehelmHook+`:: Exﾃｩcute la tﾃ｢che de migration de base de donnﾃｩes via le hook {helm}. Lorsque `+true+`, sﾃｩpare la tﾃ｢che de migration de `+harbor-core+`. La valeur par dﾃｩfaut est `+false+`.
`+caSecretName+`:: Spﾃｩcifie le nom du secret contenant la clﾃｩ `+ca.crt+`.

.Paramﾃｨtres de proxy
`+proxy.httpProxy+`:: Spﾃｩcifie l'URL du serveur proxy HTTP. La valeur par dﾃｩfaut est `+""+`.
`+proxy.httpsProxy+`:: Spﾃｩcifie l'URL du serveur proxy HTTPS. La valeur par dﾃｩfaut est `+""+`.
`+proxy.noProxy+`:: Dﾃｩfinit les URL qui contournent la configuration du proxy. La valeur par dﾃｩfaut est `+127.0.0.1,localhost,.local,.internal+`.
`+proxy.components+`:: Dﾃｩfinit les composants qui utilisent la configuration du proxy. La valeur par dﾃｩfaut est `+["core","jobservice","trivy"]+`.

.Paramﾃｨtres d'exposition
`+expose.type+`:: Spﾃｩcifie le type d'exposition du service : `+ingress+`, `+clusterIP+`, `+nodePort+` ou `+loadBalancer+`. La valeur par dﾃｩfaut est `+ingress+`.
`+expose.tls.enabled+`:: Active TLS. La valeur par dﾃｩfaut est `+true+`.
`+expose.tls.certSource+`:: Dﾃｩfinit la source du certificat TLS comme `+auto+`, `+secret+` ou `+none+`. La valeur par dﾃｩfaut est `+auto+`.
`+expose.tls.auto.commonName+`:: Dﾃｩfinit le nom commun du certificat lorsque le type n'est pas `+ingress+`.
`+expose.tls.secret.secretName+`:: Spﾃｩcifie le nom du secret contenant `+tls.crt+` (certificat) et `+tls.key+` (clﾃｩ privﾃｩe).
`+expose.ingress.hosts.core+`:: Dﾃｩfinit l'hﾃｴte du service noyau {harbor} dans la rﾃｨgle {ingress}. La valeur par dﾃｩfaut est `+core.harbor.domain+`.
`+expose.ingress.controller+`:: Dﾃｩfinit le type de contrﾃｴleur {ingress}. Prend en charge `+default+`, `+gce+`, `+alb+`, `+f5-bigip+` et `+ncp+`. La valeur par dﾃｩfaut est `+default+`.
`+expose.ingress.kubeVersionOverride+`:: Surcharge la version {kube} pour le templating {ingress}.
`+expose.ingress.annotations+`:: Dﾃｩfinit les annotations {ingress}.
`+expose.ingress.labels+`:: Dﾃｩfinit des ﾃｩtiquettes spﾃｩcifiques ﾃ {ingress}. La valeur par dﾃｩfaut est `+{}+`.
`+expose.clusterIP.name+`:: Dﾃｩfinit le nom du service ClusterIP. La valeur par dﾃｩfaut est `+harbor+`.
`+expose.clusterIP.annotations+`:: Dﾃｩfinit les annotations du service ClusterIP. La valeur par dﾃｩfaut est `+{}+`.
`+expose.clusterIP.ports.httpPort+`:: Dﾃｩfinit le port du service HTTP. La valeur par dﾃｩfaut est `+80+`.
`+expose.clusterIP.ports.httpsPort+`:: Dﾃｩfinit le port du service HTTPS. La valeur par dﾃｩfaut est `+443+`.
`+expose.clusterIP.labels+`:: Dﾃｩfinit des ﾃｩtiquettes spﾃｩcifiques au ClusterIP. La valeur par dﾃｩfaut est `+{}+`.
`+expose.nodePort.name+`:: Dﾃｩfinit le nom du service NodePort. La valeur par dﾃｩfaut est `+harbor+`.
`+expose.nodePort.ports.http.port+`:: Dﾃｩfinit le port du service HTTP. La valeur par dﾃｩfaut est `+80+`.
`+expose.nodePort.ports.http.nodePort+`:: Dﾃｩfinit le port du nﾅ砥d HTTP. La valeur par dﾃｩfaut est `+30002+`.
`+expose.nodePort.ports.https.port+`:: Dﾃｩfinit le port du service HTTPS. La valeur par dﾃｩfaut est `+443+`.
`+expose.nodePort.ports.https.nodePort+`:: Dﾃｩfinit le port du nﾅ砥d HTTPS. La valeur par dﾃｩfaut est `+30003+`.
`+expose.nodePort.annotations+`:: Dﾃｩfinit les annotations NodePort.
`+expose.nodePort.labels+`:: Dﾃｩfinit des ﾃｩtiquettes spﾃｩcifiques au NodePort. La valeur par dﾃｩfaut est `+{}+`.
`+expose.loadBalancer.name+`:: Dﾃｩfinit le nom du service. La valeur par dﾃｩfaut est `+harbor+`.
`+expose.loadBalancer.IP+`:: Dﾃｩfinit l'IP du loadBalancer lorsque l'attribution d'IP est prise en charge. La valeur par dﾃｩfaut est `+""+`.
`+expose.loadBalancer.ports.httpPort+`:: Dﾃｩfinit le port du service HTTP. La valeur par dﾃｩfaut est `+80+`.
`+expose.loadBalancer.ports.httpsPort+`:: Dﾃｩfinit le port du service HTTPS. La valeur par dﾃｩfaut est `+30002+`.
`+expose.loadBalancer.annotations+`:: Dﾃｩfinit les annotations du service loadBalancer. La valeur par dﾃｩfaut est `+{}+`.
`+expose.loadBalancer.labels+`:: Dﾃｩfinit des ﾃｩtiquettes spﾃｩcifiques au loadBalancer. La valeur par dﾃｩfaut est `+{}+`.
`+expose.loadBalancer.sourceRanges+`:: Spﾃｩcifie les plages d'adresses IP pour loadBalancerSourceRanges. La valeur par dﾃｩfaut est `+[]+`.

[#helm-persistence-parameters]
.Paramﾃｨtres de persistance
`+persistence.enabled+`:: Active ou dﾃｩsactive la persistance des donnﾃｩes. La valeur par dﾃｩfaut est `+true+`.
`+persistence.resourcePolicy+`:: `+keep+` empﾃｪche la suppression des PVC lors d'une opﾃｩration de suppression {helm}. Une valeur vide supprime les PVC aprﾃｨs la suppression du graphique. La valeur par dﾃｩfaut est `+keep+`.
`+persistence.persistentVolumeClaim.registry.existingClaim+`:: Le PVC existant qui doit ﾃｪtre crﾃｩﾃｩ manuellement avant d'ﾃｪtre liﾃｩ. Nﾃｩcessite une spﾃｩcification de subPath si le PVC est partagﾃｩ avec d'autres composants.
`+persistence.persistentVolumeClaim.registry.storageClass+`:: Le `+storageClass+` qui provisionne le volume.
`+persistence.persistentVolumeClaim.registry.subPath+`:: Le sous-chemin dans le volume.
`+persistence.persistentVolumeClaim.registry.accessMode+`:: Le mode d'accﾃｨs du volume. La valeur par dﾃｩfaut est `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.registry.size+`:: La taille du volume. La valeur par dﾃｩfaut est `+5Gi+`.
`+persistence.persistentVolumeClaim.registry.annotations+`:: Les annotations du volume.
`+persistence.persistentVolumeClaim.jobservice.jobLog.existingClaim+`:: Le PVC existant qui doit ﾃｪtre crﾃｩﾃｩ manuellement avant d'ﾃｪtre liﾃｩ. Nﾃｩcessite une spﾃｩcification de subPath si le PVC est partagﾃｩ avec d'autres composants.
`+persistence.persistentVolumeClaim.jobservice.jobLog.storageClass+`:: Le `+storageClass+` qui provisionne le volume.
`+persistence.persistentVolumeClaim.jobservice.jobLog.subPath+`:: Le sous-chemin dans le volume.
`+persistence.persistentVolumeClaim.jobservice.jobLog.accessMode+`:: Le mode d'accﾃｨs du volume. La valeur par dﾃｩfaut est `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.jobservice.jobLog.size+`:: La taille du volume. La valeur par dﾃｩfaut est `+1Gi+`.
`+persistence.persistentVolumeClaim.jobservice.jobLog.annotations+`:: Les annotations du volume.
`+persistence.persistentVolumeClaim.database.existingClaim+`:: Le PVC existant qui doit ﾃｪtre crﾃｩﾃｩ manuellement avant d'ﾃｪtre liﾃｩ. Nﾃｩcessite une spﾃｩcification de subPath si le PVC est partagﾃｩ avec d'autres composants.
`+persistence.persistentVolumeClaim.database.storageClass+`:: Le `+storageClass+` qui provisionne le volume.
`+persistence.persistentVolumeClaim.database.subPath+`:: Le sous-chemin dans le volume. Ignorﾃｩ lorsqu'une base de donnﾃｩes externe est utilisﾃｩe.
`+persistence.persistentVolumeClaim.database.accessMode+`:: Le mode d'accﾃｨs du volume. Ignorﾃｩ lorsqu'une base de donnﾃｩes externe est utilisﾃｩe. La valeur par dﾃｩfaut est `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.database.size+`:: La taille du volume. Ignorﾃｩ lorsqu'une base de donnﾃｩes externe est utilisﾃｩe. La valeur par dﾃｩfaut est `+1Gi+`.
`+persistence.persistentVolumeClaim.database.annotations+`:: Les annotations du volume.
`+persistence.persistentVolumeClaim.redis.existingClaim+`:: Le PVC existant qui doit ﾃｪtre crﾃｩﾃｩ manuellement avant d'ﾃｪtre liﾃｩ. Nﾃｩcessite une spﾃｩcification de subPath si le PVC est partagﾃｩ avec d'autres composants.
`+persistence.persistentVolumeClaim.redis.storageClass+`:: Le `+storageClass+` qui provisionne le volume. Utilise la StorageClass par dﾃｩfaut si non spﾃｩcifiﾃｩe.
`+persistence.persistentVolumeClaim.redis.subPath+`:: Le sous-chemin dans le volume. Ignorﾃｩ lorsqu'un {valkey} externe est utilisﾃｩ.
`+persistence.persistentVolumeClaim.redis.accessMode+`:: Le mode d'accﾃｨs du volume. Ignorﾃｩ lorsqu'un {valkey} externe est utilisﾃｩ. La valeur par dﾃｩfaut est `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.redis.size+`:: La taille du volume. Ignorﾃｩ lorsqu'un {valkey} externe est utilisﾃｩ. La valeur par dﾃｩfaut est `+1Gi+`.
`+persistence.persistentVolumeClaim.redis.annotations+`:: Les annotations du volume.
`+persistence.persistentVolumeClaim.trivy.existingClaim+`:: Le PVC existant qui doit ﾃｪtre crﾃｩﾃｩ manuellement avant d'ﾃｪtre liﾃｩ. Nﾃｩcessite une spﾃｩcification de subPath si le PVC est partagﾃｩ avec d'autres composants.
`+persistence.persistentVolumeClaim.trivy.storageClass+`:: Le `+storageClass+` qui provisionne le volume. Utilise la StorageClass par dﾃｩfaut si non spﾃｩcifiﾃｩe.
`+persistence.persistentVolumeClaim.trivy.subPath+`:: Le sous-chemin dans le volume.
`+persistence.persistentVolumeClaim.trivy.accessMode+`:: Le mode d'accﾃｨs du volume. La valeur par dﾃｩfaut est `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.trivy.size+`:: La taille du volume. La valeur par dﾃｩfaut est `+1Gi+`.
`+persistence.persistentVolumeClaim.trivy.annotations+`:: Les annotations du volume.
`+persistence.imageChartStorage.disableredirect+`:: Contrﾃｴle la gestion des redirections depuis les back-ends de contenu. Dﾃｩfinir sur vrai pour dﾃｩsactiver les redirections pour les back-ends non pris en charge. La valeur par dﾃｩfaut est `+false+`.
`+persistence.imageChartStorage.caBundleSecretName+`:: Le nom du secret contenant le bundle CA pour les certificats de service de stockage auto-signﾃｩs.
`+persistence.imageChartStorage.type+`:: Le type de stockage pour les images et les graphiques : `+filesystem+`, `+azure+`, `+gcs+`, `+s3+`, `+swift+` ou `+oss+`. La valeur par dﾃｩfaut est `+filesystem+`.
`+persistence.imageChartStorage.gcs.existingSecret+`:: Le nom du secret existant contenant la clﾃｩ JSON du compte de service GCS. La clﾃｩ doit ﾃｪtre `+gcs-key.json+`. La valeur par dﾃｩfaut est `+""+`.
`+persistence.imageChartStorage.gcs.useWorkloadIdentity+`:: Active l'utilisation de l'identitﾃｩ de charge de travail dans un cluster GKE. La valeur par dﾃｩfaut est `+false+`.

.{nginx}Paramﾃｨtres de
[options="header"]
`+nginx.image.repository+`:: Le dﾃｩpﾃｴt d'images pour {nginx}. La valeur par dﾃｩfaut est `+private-registry/harbor-nginx+`.
`+nginx.image.tag+`:: La balise d'image pour {nginx}.
`+nginx.replicas+`:: Le nombre de rﾃｩpliques ﾃ exﾃｩcuter. La valeur par dﾃｩfaut est `+1+`.
`+nginx.revisionHistoryLimit+`:: Le nombre maximum de rﾃｩvisions anciennes de `+ReplicaSet+` ﾃ conserver. La valeur par dﾃｩfaut est `+10+`.
`+nginx.resources+`:: Les ressources de calcul allouﾃｩes au conteneur. La valeur par dﾃｩfaut est `+undefined+`.
`+nginx.automountServiceAccountToken+`:: Contrﾃｴle le montage automatique du jeton de compte de service. La valeur par dﾃｩfaut est `+false+`.
`+nginx.nodeSelector+`:: Les ﾃｩtiquettes de nﾅ砥d utilisﾃｩes pour l'attribution des pods. La valeur par dﾃｩfaut est `+{}+`.
`+nginx.tolerations+`:: Les tolﾃｩrances d'attribution des pods. La valeur par dﾃｩfaut est `+[]+`.
`+nginx.affinity+`:: Les rﾃｨgles d'affinitﾃｩ pour les nﾅ砥ds ou les pods. La valeur par dﾃｩfaut est `+{}+`.
`+nginx.topologySpreadConstraints+`:: Les rﾃｨgles pour rﾃｩpartir les pods sur des domaines de dﾃｩfaillance tels que les rﾃｩgions ou les zones de disponibilitﾃｩ. La valeur par dﾃｩfaut est `+[]+`.
`+nginx.podAnnotations+`:: Les annotations ajoutﾃｩes au {nginx} pod. La valeur par dﾃｩfaut est `+{}+`.


.Paramﾃｨtres du portail
`+portal.image.repository+`:: Emplacement du dﾃｩpﾃｴt pour l'image du portail. La valeur par dﾃｩfaut est `+private-registry/harbor-portal+`.
`+portal.image.tag+`:: Balise pour l'image du portail. La valeur par dﾃｩfaut est `+3.11+`.
`+portal.replicas+`:: Nombre de rﾃｩpliques ﾃ crﾃｩer. La valeur par dﾃｩfaut est `+1+`.
`+portal.revisionHistoryLimit+`:: Nombre maximum de rﾃｩvisions anciennes de `+ReplicaSet+` ﾃ conserver. La valeur par dﾃｩfaut est `+10+`.
`+portal.resources+`:: Ressources allouﾃｩes au conteneur. La valeur par dﾃｩfaut est `+undefined+`.
`+portal.automountServiceAccountToken+`:: Contrﾃｴle le montage automatique du jeton de compte de service. La valeur par dﾃｩfaut est `+false+`.
`+portal.nodeSelector+`:: ﾃ液iquettes de nﾅ砥d utilisﾃｩes pour l'attribution des pods. La valeur par dﾃｩfaut est `+{}+`.
`+portal.tolerations+`:: Tolﾃｩrances utilisﾃｩes pour l'attribution des pods. La valeur par dﾃｩfaut est `+[]+`.
`+portal.affinity+`:: Paramﾃｨtres d'affinitﾃｩ pour les nﾅ砥ds et les pods. La valeur par dﾃｩfaut est `+{}+`.
`+portal.topologySpreadConstraints+`:: Dﾃｩfinit la distribution des pods ﾃ travers les domaines de dﾃｩfaillance tels que les rﾃｩgions ou les zones de disponibilitﾃｩ. La valeur par dﾃｩfaut est `+[]+`.
`+portal.podAnnotations+`:: Annotations ajoutﾃｩes au pod du portail. La valeur par dﾃｩfaut est `+{}+`.
`+portal.serviceAnnotations+`:: Annotations ajoutﾃｩes au service du portail. La valeur par dﾃｩfaut est `+{}+`.
`+portal.priorityClassName+`:: Nom de la classe de prioritﾃｩ pour l'exﾃｩcution des pods.
`+portal.initContainers+`:: Les conteneurs d'initialisation ﾃ exﾃｩcuter avant le dﾃｩmarrage du conteneur du contrﾃｴleur. La valeur par dﾃｩfaut est `+[]+`.


.Paramﾃｨtres du noyau
`+core.image.repository+`:: Le dﾃｩpﾃｴt pour l'image {harbor} du noyau. La valeur par dﾃｩfaut est `+private-registry/harbor-core+`.
`+core.image.tag+`:: La balise pour l'image {harbor} du noyau. La valeur par dﾃｩfaut est `+2.11+`.
`+core.replicas+`:: Le nombre de rﾃｩpliques. La valeur par dﾃｩfaut est `+1+`.
`+core.revisionHistoryLimit+`:: La limite de l'historique des rﾃｩvisions. La valeur par dﾃｩfaut est `+10+`.
`+core.startupProbe.initialDelaySeconds+`:: Le dﾃｩlai initial en secondes pour la sonde de dﾃｩmarrage. La valeur par dﾃｩfaut est `+10+`.
`+core.resources+`:: Les ressources ﾃ allouer pour le conteneur. La valeur par dﾃｩfaut est `+undefined+`.
`+core.automountServiceAccountToken+`:: Monte le jeton du compte de service. La valeur par dﾃｩfaut est `+false+`.
`+core.nodeSelector+`:: Les ﾃｩtiquettes de nﾅ砥d pour l'attribution des pods. La valeur par dﾃｩfaut est `+{}+`.
`+core.tolerations+`:: Les tolﾃｩrances pour l'attribution des pods. La valeur par dﾃｩfaut est `+[]+`.
`+core.affinity+`:: Les affinitﾃｩs des nﾅ砥ds ou des pods. La valeur par dﾃｩfaut est `+{}+`.
`+core.topologySpreadConstraints+`:: Les contraintes qui dﾃｩfinissent comment les pods sont rﾃｩpartis ﾃ travers les domaines de dﾃｩfaillance tels que les rﾃｩgions ou les zones de disponibilitﾃｩ. La valeur par dﾃｩfaut est `+[]+`.
`+core.podAnnotations+`:: Les annotations ﾃ ajouter au pod du noyau. La valeur par dﾃｩfaut est `+{}+`.
`+core.serviceAnnotations+`:: Les annotations ﾃ ajouter au service du noyau. La valeur par dﾃｩfaut est `+{}+`.
`+core.configureUserSettings+`:: Une chaﾃｮne JSON dans la variable d'environnement CONFIG_OVERWRITE_JSON pour configurer les paramﾃｨtres utilisateur.
`+core.quotaUpdateProvider+`:: Le fournisseur pour mettre ﾃ jour l'utilisation du quota de projet, les options sont `+redis+` ou `+db+`. La valeur par dﾃｩfaut est `+db+`.
`+core.secret+`:: Utilisﾃｩ lorsque le serveur du noyau communique avec d'autres composants.
`+core.secretName+`:: Le nom d'un {kube} secret pour utiliser votre propre certificat TLS et clﾃｩ privﾃｩe pour le chiffrement ou le dﾃｩchiffrement des jetons.
`+core.tokenKey+`:: La clﾃｩ privﾃｩe RSA au format PEM utilisﾃｩe pour signer les jetons de service.
`+core.tokenCert+`:: Le certificat au format PEM signﾃｩ par `+core.tokenKey+` utilisﾃｩ pour valider les jetons de service.
`+core.xsrfKey+`:: La clﾃｩ XSRF, gﾃｩnﾃｩrﾃｩe automatiquement si elle n'est pas spﾃｩcifiﾃｩe.
`+core.priorityClassName+`:: La classe de prioritﾃｩ pour exﾃｩcuter le pod.
`+core.artifactPullAsyncFlushDuration+`:: La durﾃｩe pour mettre ﾃ jour de maniﾃｨre asynchrone le temps de tirage des artefacts et le nombre de tirages de dﾃｩpﾃｴt.
`+core.gdpr.deleteUser+`:: Active la suppression des utilisateurs conforme au RGPD. La valeur par dﾃｩfaut est `+false+`.
`+core.gdpr.auditLogsCompliant+`:: Active la conformitﾃｩ au RGPD pour les journaux d'audit en changeant le nom d'utilisateur en sa valeur CRC32 si cet utilisateur a ﾃｩtﾃｩ supprimﾃｩ du systﾃｨme. La valeur par dﾃｩfaut est `+false+`.
`+core.initContainers+`:: Les conteneurs d'initialisation ﾃ exﾃｩcuter avant le dﾃｩmarrage du conteneur du contrﾃｴleur. La valeur par dﾃｩfaut est `+[]+`.


.Paramﾃｨtres du service de travail.
`+jobservice.image.repository+`:: Le dﾃｩpﾃｴt pour l'image du jobservice. La valeur par dﾃｩfaut est `+private-registry/harbor-jobservice+`.
`+jobservice.image.tag+`:: La balise pour l'image du jobservice. La valeur par dﾃｩfaut est `+2.11+`.
`+jobservice.replicas+`:: Le nombre de rﾃｩpliques. La valeur par dﾃｩfaut est `+1+`.
`+jobservice.revisionHistoryLimit+`:: La limite de l'historique des rﾃｩvisions. La valeur par dﾃｩfaut est `+10+`.
`+jobservice.maxJobWorkers+`:: Le nombre maximum de workers. La valeur par dﾃｩfaut est `+10+`.
`+jobservice.jobLoggers+`:: Les enregistreurs pour les tﾃ｢ches : `+file+`, `+database+` ou `+stdout+`. La valeur par dﾃｩfaut est `+[file]+`.
`+jobservice.loggerSweeperDuration+`:: La durﾃｩe en jours pour conserver les journaux de travail (ignorﾃｩe si `+jobLoggers+` est dﾃｩfini sur `+stdout+`). La valeur par dﾃｩfaut est `+14+`.
`+jobservice.notification.webhook_job_max_retry+`:: Le nombre maximum de tentatives pour l'envoi de notifications webhook. La valeur par dﾃｩfaut est `+3+`.
`+jobservice.notification.webhook_job_http_client_timeout+`:: Le dﾃｩlai d'attente du client HTTP en secondes pour l'envoi de notifications webhook. La valeur par dﾃｩfaut est `+3+`.
`+jobservice.reaper.max_update_hours+`:: Le temps maximum en heures ﾃ attendre qu'une tﾃ｢che se termine. Si la tﾃ｢che n'est pas terminﾃｩe aprﾃｨs le nombre d'heures spﾃｩcifiﾃｩ, elle est marquﾃｩe comme une erreur mais continue de s'exﾃｩcuter. La valeur par dﾃｩfaut est `+24+`.
`+jobservice.reaper.max_dangling_hours+`:: Le temps maximum en heures pour l'exﾃｩcution dans un ﾃｩtat d'exﾃｩcution sans qu'une nouvelle tﾃ｢che soit crﾃｩﾃｩe. La valeur par dﾃｩfaut est `+168+`.
`+jobservice.resources+`:: Les [ressources] ﾃ allouer pour le conteneur. La valeur par dﾃｩfaut est `+undefined+`.
`+jobservice.automountServiceAccountToken+`:: Monte le jeton du compte de service. La valeur par dﾃｩfaut est `+false+`.
`+jobservice.nodeSelector+`:: Les ﾃｩtiquettes de nﾅ砥d pour l'attribution des pods. La valeur par dﾃｩfaut est `+{}+`.
`+jobservice.tolerations+`:: Les tolﾃｩrances pour l'attribution des pods. La valeur par dﾃｩfaut est `+[]+`.
`+jobservice.affinity+`:: Les affinitﾃｩs des nﾅ砥ds ou des pods. La valeur par dﾃｩfaut est `+{}+`.
`+jobservice.topologySpreadConstraints+`:: Les contraintes qui dﾃｩfinissent comment les pods sont rﾃｩpartis ﾃ travers les domaines de dﾃｩfaillance tels que les rﾃｩgions ou les zones de disponibilitﾃｩ. La valeur par dﾃｩfaut est `+[]+`.
`+jobservice.podAnnotations+`:: Les annotations ﾃ ajouter au pod du jobservice. La valeur par dﾃｩfaut est `+{}+`.
`+jobservice.priorityClassName+`:: La classe de prioritﾃｩ pour exﾃｩcuter le pod.
`+jobservice.secret+`:: Le secret utilisﾃｩ lorsque le jobservice communique avec d'autres composants. Si une clﾃｩ secrﾃｨte n'est pas spﾃｩcifiﾃｩe, {helm} la gﾃｩnﾃｨre. Doit ﾃｪtre une chaﾃｮne de 16 caractﾃｨres.
`+jobservice.initContainers+`:: Les conteneurs d'initialisation ﾃ exﾃｩcuter avant le dﾃｩmarrage du conteneur du contrﾃｴleur. La valeur par dﾃｩfaut est `+[]+`.


.Paramﾃｨtres du registre
`+registry.registry.image.repository+`:: L'emplacement du dﾃｩpﾃｴt pour l'image du registre. La valeur par dﾃｩfaut est `+private-registry/harbor-registry+`.
`+registry.registry.image.tag+`:: La balise pour l'image du registre. La valeur par dﾃｩfaut est `+2.11+`.
`+registry.registry.resources+`:: Les [ressources] ﾃ allouer pour le conteneur. La valeur par dﾃｩfaut est `+undefined+`.
`+registry.controller.image.repository+`:: L'emplacement du dﾃｩpﾃｴt pour l'image du contrﾃｴleur de registre. La valeur par dﾃｩfaut est `+private-registry/harbor-registryctl+`.
`+registry.controller.image.tag+`:: La balise pour l'image du contrﾃｴleur de registre. La valeur par dﾃｩfaut est `+2.11+`.
`+registry.controller.resources+`:: Les [ressources] ﾃ allouer pour le conteneur. La valeur par dﾃｩfaut est `+undefined+`.
`+registry.replicas+`:: Le nombre d'instances rﾃｩpliquﾃｩes. La valeur par dﾃｩfaut est `+1+`.
`+registry.revisionHistoryLimit+`:: Le nombre maximum de rﾃｩvisions ﾃ maintenir dans l'historique. La valeur par dﾃｩfaut est `+10+`.
`+registry.nodeSelector+`:: Les ﾃｩtiquettes de nﾅ砥d pour l'attribution des pods. La valeur par dﾃｩfaut est `+{}+`.
`+registry.automountServiceAccountToken+`:: Contrﾃｴle si le jeton de compte de service doit ﾃｪtre montﾃｩ. La valeur par dﾃｩfaut est `+false+`.
`+registry.tolerations+`:: Les tolﾃｩrances pour l'attribution des pods. La valeur par dﾃｩfaut est `+[]+`.
`+registry.affinity+`:: Les affinitﾃｩs des nﾅ砥ds ou des pods. La valeur par dﾃｩfaut est `+{}+`.
`+registry.topologySpreadConstraints+`:: Les contraintes qui dﾃｩfinissent la distribution des pods ﾃ travers les domaines d'ﾃｩchec tels que les rﾃｩgions ou les zones de disponibilitﾃｩ. La valeur par dﾃｩfaut est `+[]+`.
`+registry.middleware+`:: Support intermﾃｩdiaire pour un CDN entre le stockage back-end et {docker} le destinataire de tirage.
`+registry.podAnnotations+`:: Les annotations ﾃ ajouter au pod du registre. La valeur par dﾃｩfaut est `+{}+`.
`+registry.priorityClassName+`:: La classe de prioritﾃｩ pour l'exﾃｩcution du pod.
`+registry.secret+`:: Le secret qui sﾃｩcurise l'ﾃｩtat de tﾃｩlﾃｩchargement entre le client et le stockage back-end du registre.
`+registry.credentials.username+`:: Le nom d'utilisateur pour l'accﾃｨs au {harbor} registre interne du noyau. La valeur par dﾃｩfaut est `+harbor_registry_user+`.
`+registry.credentials.password+`:: Le mot de passe pour l'accﾃｨs au {harbor} registre interne du noyau. La valeur par dﾃｩfaut est `+harbor_registry_password+`.
`+registry.credentials.existingSecret+`:: Un secret existant contenant le mot de passe pour l'accﾃｨs ﾃ l'instance du registre en mode d'authentification htpasswd. La valeur par dﾃｩfaut est `+""+`.
`+registry.credentials.htpasswdString+`:: Le login et le mot de passe au format de chaﾃｮne htpasswd. Exclut `+registry.credentials.username+` et `+registry.credentials.password+`. La valeur par dﾃｩfaut est `+undefined+`.
`+registry.relativeurls+`:: Renvoie des URLﾂrelatives dans les en-tﾃｪtes de localisation lorsque c'est vrai. Requis si {harbor} est derriﾃｨre un proxy inverse. La valeur par dﾃｩfaut est `+false+`.
`+registry.upload_purging.enabled+`:: Active la purge des rﾃｩpertoires de tﾃｩlﾃｩchargement. La valeur par dﾃｩfaut est `+true+`.
`+registry.upload_purging.age+`:: La pﾃｩriode aprﾃｨs laquelle les fichiers dans les rﾃｩpertoires de tﾃｩlﾃｩchargement sont supprimﾃｩs, par dﾃｩfaut une semaine. La valeur par dﾃｩfaut est `+168h+`.
`+registry.upload_purging.interval+`:: L'intervalle de temps entre les opﾃｩrations de purge. La valeur par dﾃｩfaut est `+24h+`.
`+registry.upload_purging.dryrun+`:: Active le mode dryrun pour la purge des tﾃｩlﾃｩchargements. La valeur par dﾃｩfaut est `+false+`.
`+registry.initContainers+`:: Les conteneurs d'initialisation qui s'exﾃｩcutent avant le dﾃｩmarrage du conteneur du contrﾃｴleur. La valeur par dﾃｩfaut est `+[]+`.


.{trivy} Paramﾃｨtres de
`+trivy.enabled+`:: Active ou dﾃｩsactive le {trivy} scanner. La valeur par dﾃｩfaut est `+true+`.
`+trivy.image.repository+`:: Le dﾃｩpﾃｴt pour l'image de l'{trivy} adaptateur. La valeur par dﾃｩfaut est `+private-registry/harbor-trivy-adapter+`.
`+trivy.image.tag+`:: L'ﾃｩtiquette pour l'image de l'{trivy} adaptateur. La valeur par dﾃｩfaut est `+2.11+`.
`+trivy.resources+`:: Les ressources ﾃ allouer pour le conteneur de l'{trivy} adaptateur. La valeur par dﾃｩfaut est `+undefined+`.
`+trivy.automountServiceAccountToken+`:: Indique si le token du compte de service doit ﾃｪtre montﾃｩ. La valeur par dﾃｩfaut est `+false+`.
`+trivy.replicas+`:: Le nombre de rﾃｩpliques de Pod. La valeur par dﾃｩfaut est `+1+`.
`+trivy.debugMode+`:: Active le {trivy} mode de dﾃｩbogage pour le dﾃｩpannage. La valeur par dﾃｩfaut est `+false+`.
`+trivy.vulnType+`:: Liste des types de vulnﾃｩrabilitﾃｩs sﾃｩparﾃｩs par des virgules (`+os+` et `+library+`). La valeur par dﾃｩfaut est `+os,library+`.
`+trivy.severity+`:: Liste des sﾃｩvﾃｩritﾃｩs de vulnﾃｩrabilitﾃｩs ﾃ vﾃｩrifier, sﾃｩparﾃｩe par des virgules. La valeur par dﾃｩfaut est `+UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL+`.
`+trivy.ignoreUnfixed+`:: Affiche uniquement les vulnﾃｩrabilitﾃｩs corrigﾃｩes. La valeur par dﾃｩfaut est `+false+`.
`+trivy.insecure+`:: Ignore la vﾃｩrification du certificat du registre. La valeur par dﾃｩfaut est `+false+`.
`+trivy.skipUpdate+`:: Dﾃｩsactive les {trivy} tﾃｩlﾃｩchargements de bases de donnﾃｩes depuis GitHub. La valeur par dﾃｩfaut est `+false+`.
`+trivy.skipJavaDBUpdate+`:: Nﾃｩcessite le tﾃｩlﾃｩchargement manuel du `+trivy-java.db+` fichier lorsqu'il est activﾃｩ. La valeur par dﾃｩfaut est `+false+`.
`+trivy.offlineScan+`:: Empﾃｪche {trivy} d'envoyer des requﾃｪtes API pour identifier les dﾃｩpendances. La valeur par dﾃｩfaut est `+false+`.
`+trivy.securityCheck+`:: Liste des problﾃｨmes de sﾃｩcuritﾃｩ ﾃ dﾃｩtecter, sﾃｩparﾃｩe par des virgules. La valeur par dﾃｩfaut est `+vuln+`.
`+trivy.timeout+`:: La durﾃｩe d'attente pour l'achﾃｨvement du scan. La valeur par dﾃｩfaut est `+5m0s+`.
`+trivy.gitHubToken+`:: Le jeton d'accﾃｨs GitHub requis pour les tﾃｩlﾃｩchargements de bases de donnﾃｩes. La valeur par dﾃｩfaut est `+undefined+`.
`+trivy.priorityClassName+`:: La classe de prioritﾃｩ pour l'exﾃｩcution du pod. La valeur par dﾃｩfaut est `+undefined+`.
`+trivy.topologySpreadConstraints+`:: Dﾃｩfinit les contraintes de distribution des pods ﾃ travers les domaines d'ﾃｩchec. La valeur par dﾃｩfaut est `+undefined+`.
`+trivy.initContainers+`:: Liste des conteneurs d'initialisation ﾃ exﾃｩcuter avant le dﾃｩmarrage du conteneur principal. La valeur par dﾃｩfaut est `+[]+`.

.Paramﾃｨtres de la base de donnﾃｩes
`+database.type+`:: Le type de base de donnﾃｩes. Dﾃｩfinir sur `+external+` lors de l'utilisation d'une base de donnﾃｩes externe. La valeur par dﾃｩfaut est `+internal+`.
`+database.internal.image.repository+`:: Le dﾃｩpﾃｴt pour l'image de la base de donnﾃｩes. La valeur par dﾃｩfaut est `+private-registry/harbor-db+`.
`+database.internal.image.tag+`:: L'ﾃｩtiquette pour l'image de la base de donnﾃｩes. La valeur par dﾃｩfaut est `+2.11+`.
`+database.internal.password+`:: Le mot de passe pour la base de donnﾃｩes interne. La valeur par dﾃｩfaut est `+changeit+`.
`+database.internal.shmSizeLimit+`:: La limite de taille de la mﾃｩmoire partagﾃｩe pour {postgresql} (typiquement 50 % de la limite de mﾃｩmoire du conteneur). La valeur par dﾃｩfaut est `+512Mi+`.
`+database.internal.resources+`:: Les ressources allouﾃｩes pour le conteneur de base de donnﾃｩes. La valeur par dﾃｩfaut est `+undefined+`.
`+database.internal.automountServiceAccountToken+`:: Contrﾃｴle si le token du compte de service est montﾃｩ. La valeur par dﾃｩfaut est `+false+`.
`+database.internal.initContainer.migrator.resources+`:: Les ressources allouﾃｩes pour le conteneur d'initialisation du migrateur de base de donnﾃｩes. La valeur par dﾃｩfaut est `+undefined+`.
`+database.internal.initContainer.permissions.resources+`:: Les ressources allouﾃｩes pour le conteneur d'initialisation des permissions de la base de donnﾃｩes. La valeur par dﾃｩfaut est `+undefined+`.
`+database.internal.nodeSelector+`:: Les ﾃｩtiquettes de nﾅ砥d pour l'attribution des pods. La valeur par dﾃｩfaut est `+{}+`.
`+database.internal.tolerations+`:: Les tolﾃｩrances pour l'attribution des pods. La valeur par dﾃｩfaut est `+[]+`.
`+database.internal.affinity+`:: Les paramﾃｨtres d'affinitﾃｩ du nﾅ砥d ou du pod. La valeur par dﾃｩfaut est `+{}+`.
`+database.internal.priorityClassName+`:: La classe de prioritﾃｩ pour l'exﾃｩcution du pod. La valeur par dﾃｩfaut est `+undefined+`.
`+database.internal.livenessProbe.timeoutSeconds+`:: Le dﾃｩlai d'attente en secondes pour le probe de vivacitﾃｩ (plage : 1-5s). La valeur par dﾃｩfaut est `+1+`.
`+database.internal.readinessProbe.timeoutSeconds+`:: Le dﾃｩlai d'attente en secondes pour le probe de disponibilitﾃｩ (plage : 1-5s). La valeur par dﾃｩfaut est `+1+`.
`+database.internal.extrInitContainers+`:: Des conteneurs d'initialisation supplﾃｩmentaires qui s'exﾃｩcutent avant le dﾃｩmarrage du conteneur de base de donnﾃｩes. La valeur par dﾃｩfaut est `+[]+`.
`+database.external.host+`:: Le nom d'hﾃｴte de la base de donnﾃｩes externe. La valeur par dﾃｩfaut est `+192.168.0.1+`.
`+database.external.port+`:: Le numﾃｩro de port de la base de donnﾃｩes externe. La valeur par dﾃｩfaut est `+5432+`.
`+database.external.username+`:: Le nom d'utilisateur pour la base de donnﾃｩes externe. La valeur par dﾃｩfaut est `+user+`.
`+database.external.password+`:: Le mot de passe pour la base de donnﾃｩes externe. La valeur par dﾃｩfaut est `+password+`.
`+database.external.coreDatabase+`:: Le nom de la base de donnﾃｩes utilisﾃｩe par le noyau. La valeur par dﾃｩfaut est `+registry+`.
`+database.external.existingSecret+`:: Le secret existant contenant le mot de passe de la base de donnﾃｩes. La clﾃｩ doit ﾃｪtre `+password+`. La valeur par dﾃｩfaut est `+""+`.
`+database.external.sslmode+`:: La mﾃｩthode de connexion pour la base de donnﾃｩes externe. Options : `+require+`, `+verify-full+`, `+verify-ca+`, `+disable+`. La valeur par dﾃｩfaut est `+disable+`.
`+database.maxIdleConns+`:: Le nombre maximum de connexions inactives dans le pool (0 ou moins signifie qu'aucune connexion inactive n'est conservﾃｩe). La valeur par dﾃｩfaut est `+50+`.
`+database.maxOpenConns+`:: Le nombre maximum de connexions ouvertes ﾃ la base de donnﾃｩes (0 ou moins signifie illimitﾃｩ). La valeur par dﾃｩfaut est `+100+`.
`+database.podAnnotations+`:: Les annotations ﾃ ajouter au pod de la base de donnﾃｩes. La valeur par dﾃｩfaut est `+{}+`.


.Paramﾃｨtres {valkey} / {redis}
`+redis.type+`:: Le type de {redis} dﾃｩploiement. Dﾃｩfinir sur `+external+` pour {redis} externe. La valeur par dﾃｩfaut est `+internal+`.
`+redis.internal.image.repository+`:: Le dﾃｩpﾃｴt pour l'image {redis}. La valeur par dﾃｩfaut est `+private-registry/harbor-redis+`.
`+redis.internal.image.tag+`:: L'ﾃｩtiquette pour l'image {redis}. La valeur par dﾃｩfaut est `+7.2+`.
`+redis.internal.resources+`:: Les ressources allouﾃｩes pour le {redis} conteneur. La valeur par dﾃｩfaut est `+undefined+`.
`+redis.internal.automountServiceAccountToken+`:: Contrﾃｴle si le token du compte de service est montﾃｩ. La valeur par dﾃｩfaut est `+false+`.
`+redis.internal.nodeSelector+`:: Les ﾃｩtiquettes de nﾅ砥d pour l'attribution des pods. La valeur par dﾃｩfaut est `+{}+`.
`+redis.internal.tolerations+`:: Les tolﾃｩrances pour l'attribution des pods. La valeur par dﾃｩfaut est `+[]+`.
`+redis.internal.affinity+`:: Les paramﾃｨtres d'affinitﾃｩ du nﾅ砥d ou du pod. La valeur par dﾃｩfaut est `+{}+`.
`+redis.internal.priorityClassName+`:: La classe de prioritﾃｩ pour exﾃｩcuter {redis} le pod. La valeur par dﾃｩfaut est `+undefined+`.
`+redis.internal.jobserviceDatabaseIndex+`:: L'index de la base de donnﾃｩes pour jobservice. La valeur par dﾃｩfaut est `+1+`.
`+redis.internal.registryDatabaseIndex+`:: L'index de la base de donnﾃｩes pour le registre. La valeur par dﾃｩfaut est `+2+`.
`+redis.internal.trivyAdapterIndex+`:: L'index de la base de donnﾃｩes pour {trivy} l'adaptateur. La valeur par dﾃｩfaut est `+5+`.
`+redis.internal.harborDatabaseIndex+`:: L'index de la base de donnﾃｩes pour la logique mﾃｩtier {harbor} diverse. La valeur par dﾃｩfaut est `+0+`.
`+redis.internal.cacheLayerDatabaseIndex+`:: L'index de la base de donnﾃｩes pour la couche de cache de {harbor}. La valeur par dﾃｩfaut est `+0+`.
`+redis.internal.initContainers+`:: Les conteneurs d'initialisation qui s'exﾃｩcutent avant le dﾃｩmarrage du {redis} conteneur. La valeur par dﾃｩfaut est `+[]+`.
`+redis.external.addr+`:: L'adresse de l'{redis} instance externe. La valeur par dﾃｩfaut est `+192.168.0.2:6379+`.
`+redis.external.sentinelMasterSet+`:: Le nom de l'ensemble maﾃｮtre {redis} Sentinel (le cas ﾃｩchﾃｩant). La valeur par dﾃｩfaut est `+undefined+`.
`+redis.external.coreDatabaseIndex+`:: L'index de la base de donnﾃｩes pour le noyau. La valeur par dﾃｩfaut est `+0+`.
`+redis.external.jobserviceDatabaseIndex+`:: L'index de la base de donnﾃｩes pour jobservice. La valeur par dﾃｩfaut est `+1+`.
`+redis.external.registryDatabaseIndex+`:: L'index de la base de donnﾃｩes pour le registre. La valeur par dﾃｩfaut est `+2+`.
`+redis.external.trivyAdapterIndex+`:: L'index de la base de donnﾃｩes pour {trivy} l'adaptateur. La valeur par dﾃｩfaut est `+5+`.
`+redis.external.harborDatabaseIndex+`:: L'index de la base de donnﾃｩes pour la logique mﾃｩtier {harbor} diverse. La valeur par dﾃｩfaut est `+0+`.
`+redis.external.cacheLayerDatabaseIndex+`:: L'index de la base de donnﾃｩes pour la couche de cache de {harbor}. La valeur par dﾃｩfaut est `+0+`.
`+redis.external.username+`:: Le nom d'utilisateur pour {redis} l'authentification externe. La valeur par dﾃｩfaut est `+undefined+`.
`+redis.external.password+`:: Le mot de passe pour {redis} l'authentification externe. La valeur par dﾃｩfaut est `+undefined+`.
`+redis.external.existingSecret+`:: Le secret existant contenant le {redis} mot de passe. La clﾃｩ doit ﾃｪtre `+REDIS_PASSWORD+`. La valeur par dﾃｩfaut est `+""+`.
`+redis.podAnnotations+`:: Les annotations ﾃ ajouter au {redis} pod. La valeur par dﾃｩfaut est `+{}+`.

.Paramﾃｨtres de l'exportateur
`+exporter.replicas+`:: Le nombre de rﾃｩpliques ﾃ exﾃｩcuter. La valeur par dﾃｩfaut est `+1+`.
`+exporter.revisionHistoryLimit+`:: La limite de l'historique des rﾃｩvisions. La valeur par dﾃｩfaut est `+10+`.
`+exporter.podAnnotations+`:: Annotations ﾃ ajouter au pod de l'exportateur. La valeur par dﾃｩfaut est `+{}+`.
`+exporter.image.repository+`:: Le dﾃｩpﾃｴt pour l'image de l'exportateur. La valeur par dﾃｩfaut est `+private-registry/harbor-exporter+`.
`+exporter.image.tag+`:: L'ﾃｩtiquette pour l'image de l'exportateur. La valeur par dﾃｩfaut est `+2.11+`.
`+exporter.nodeSelector+`:: ﾃ液iquettes de nﾅ砥d pour l'attribution de pod. La valeur par dﾃｩfaut est `+{}+`.
`+exporter.tolerations+`:: Tolﾃｩrances pour l'attribution de pod. La valeur par dﾃｩfaut est `+[]+`.
`+exporter.affinity+`:: Affinitﾃｩs de nﾅ砥d ou de pod. La valeur par dﾃｩfaut est `+{}+`.
`+exporter.topologySpreadConstraints+`:: Contraintes qui dﾃｩfinissent comment les pods se rﾃｩpartissent sur des domaines de dﾃｩfaillance tels que les rﾃｩgions ou les zones de disponibilitﾃｩ. La valeur par dﾃｩfaut est `+[]+`.
`+exporter.automountServiceAccountToken+`:: Contrﾃｴle si le serviceAccountToken doit ﾃｪtre montﾃｩ. La valeur par dﾃｩfaut est `+false+`.
`+exporter.cacheDuration+`:: La durﾃｩe de mise en cache pour les informations collectﾃｩes par l'exportateur. La valeur par dﾃｩfaut est `+30+`.
`+exporter.cacheCleanInterval+`:: L'intervalle de nettoyage du cache pour les informations collectﾃｩes par l'exportateur. La valeur par dﾃｩfaut est `+14400+`.
`+exporter.priorityClassName+`:: La classe de prioritﾃｩ pour exﾃｩcuter le pod. La valeur par dﾃｩfaut est `+undefined+`.

.Paramﾃｨtres des mﾃｩtriques
`+metrics.enabled+`:: Active {harbor} les mﾃｩtriques. La valeur par dﾃｩfaut est `+false+`.
`+metrics.core.path+`:: Le chemin URL pour les mﾃｩtriques du noyau. La valeur par dﾃｩfaut est `+/metrics+`.
`+metrics.core.port+`:: Le port pour les mﾃｩtriques du noyau. La valeur par dﾃｩfaut est `+8001+`.
`+metrics.registry.path+`:: Le chemin URL pour les mﾃｩtriques de registre. La valeur par dﾃｩfaut est `+/metrics+`.
`+metrics.registry.port+`:: Le port pour les mﾃｩtriques de registre. La valeur par dﾃｩfaut est `+8001+`.
`+metrics.exporter.path+`:: Le chemin URL pour les mﾃｩtriques de l'exportateur. La valeur par dﾃｩfaut est `+/metrics+`.
`+metrics.exporter.port+`:: Le port pour les mﾃｩtriques de l'exportateur. La valeur par dﾃｩfaut est `+8001+`.
`+metrics.serviceMonitor.enabled+`:: Permet la crﾃｩation d'un {prometheus} ServiceMonitor (requiert {prometheus} CRD). La valeur par dﾃｩfaut est `+false+`.
`+metrics.serviceMonitor.additionalLabels+`:: ﾃ液iquettes supplﾃｩmentaires ﾃ appliquer au manifeste ServiceMonitor. La valeur par dﾃｩfaut est `+""+`.
`+metrics.serviceMonitor.interval+`:: L'intervalle de collecte pour {harbor} les mﾃｩtriques. La valeur par dﾃｩfaut est `+""+`.
`+metrics.serviceMonitor.metricRelabelings+`:: Les rﾃｨgles de re-ﾃｩtiquetage pour les mﾃｩtriques avant ingestion. La valeur par dﾃｩfaut est `+[]+`.
`+metrics.serviceMonitor.relabelings+`:: Les rﾃｨgles de re-ﾃｩtiquetage pour les mﾃｩtriques avant collecte. La valeur par dﾃｩfaut est `+[]+`.

.Paramﾃｨtres de trace
`+trace.enabled+`:: Active la fonctionnalitﾃｩ de traﾃｧage. La valeur par dﾃｩfaut est `+false+`.
`+trace.provider+`:: Le fournisseur de traﾃｧage (`+jaeger+` ou `+otel+`). La version de Jaeger doit ﾃｪtre 1.26 ou supﾃｩrieure. La valeur par dﾃｩfaut est `+jaeger+`.
`+trace.sample_rate+`:: Le taux d'ﾃｩchantillonnage pour les donnﾃｩes de trace. `+1+` ﾃｩchantillonne 100 %, `+0.5+` ﾃｩchantillonne 50 %. La valeur par dﾃｩfaut est `+1+`.
`+trace.namespace+`:: L'espace de noms pour diffﾃｩrencier les diffﾃｩrents {harbor} services.
`+trace.attributes+`:: Un dictionnaire clﾃｩ-valeur pour les attributs dﾃｩfinis par l'utilisateur lors de l'initialisation du fournisseur de trace.
`+trace.jaeger.endpoint+`:: Le point de terminaison pour le traﾃｧage Jaeger. La valeur par dﾃｩfaut est `+\http://hostname:14268/api/traces+`.
`+trace.jaeger.username+`:: Le nom d'utilisateur pour l'authentification Jaeger.
`+trace.jaeger.password+`:: Le mot de passe pour l'authentification Jaeger.
`+trace.jaeger.agent_host+`:: L'hﾃｴte de l'agent pour Jaeger.
`+trace.jaeger.agent_port+`:: Le port de l'agent pour Jaeger. La valeur par dﾃｩfaut est `+6831+`.
`+trace.otel.endpoint+`:: Le point de terminaison pour le {otelemetry} traﾃｧage. La valeur par dﾃｩfaut est `+hostname:4318+`.
`+trace.otel.url_path+`:: Le chemin URL pour {otelemetry}. La valeur par dﾃｩfaut est `+/v1/traces+`.
`+trace.otel.compression+`:: Active la compression pour {otelemetry}. La valeur par dﾃｩfaut est `+false+`.
`+trace.otel.insecure+`:: ﾃ液ablit une connexion non sﾃｩcurisﾃｩe pour {otelemetry}. La valeur par dﾃｩfaut est `+true+`.
`+trace.otel.timeout+`:: Le dﾃｩlai d'attente en secondes pour {otelemetry}. La valeur par dﾃｩfaut est `+10+`.

.Paramﾃｨtres de cache
`+cache.enabled+`:: Active la couche de cache. La valeur par dﾃｩfaut est `+false+`.
`+cache.expireHours+`:: Le temps d'expiration en heures pour la couche de cache. La valeur par dﾃｩfaut est `+24+`.
