ifdef::ss-ff-stackpacks2_enabled[]
= Esquema y referencia de los monitores
:revdate: 2026-01-09
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

En esta página se describen los esquemas de `+Monitor+`, junto con explicaciones detalladas de las construcciones, la sintaxis de las expresiones y su semántica.

== Esquema del monitor

Un monitor especifica con qué frecuencia debe ejecutarse una función de monitorización y con qué argumentos.

[,yaml]
----
_type: "Monitor"
name: string
description?: string
function: string
arguments:
  <dependent on monitor function>
intervalSeconds: integer
remediationHint?: string
status?: "ENABLED" | "DISABLED"       # defaults to "DISABLED"
tags:
  <key>: <value>
identifier?: string
----

* `+_type+`: {stackstate-product-name} necesita saber que se trata de un monitor por lo que, el valor siempre debe ser `+Monitor+`
* `+name+`: El nombre del monitor
* `+description+`: Descripción del monitor.
* `+function+`: Una referencia a la función del monitor que ejecutará el monitor.
* `+intervalSeconds+`: El intervalo en el que se ejecuta el monitor. Para una métrica regular en tiempo real se aconsejan 30 segundos. Para consultas métricas analíticas de larga duración se recomienda un intervalo mayor.
* `+remediationHint+`: Descripción de lo que puede hacer el usuario cuando falla el monitor. El formato es markdown, con el uso opcional de variables handlebars para personalizar la sugerencia basada en series temporales u otros datosxref:use/alerting/k8s-add-monitors-cli.adoc#_write_the_remediation_hint[(más explicaciones a continuación]).
* `+status+`: O `+"DISABLED"+` o `+"ENABLED"+`. Determina si el monitor se ejecutará o no.
* `+tags+`: Añada etiquetas a los monitores para organizarlos mejor en la vista general de monitores de su instancia {stackstate-product-name}, http://your-instance/#/monitors
* `+identifier+`: Un identificador de la forma `+urn:stackpack:<stackpack-name>:monitor:....+` que identifica unívocamente al monitor al actualizar su configuración.

== Funciones del monitor

=== Umbral

Activa un estado de salud cuando se supera un umbral determinado para una consulta métrica especificada. Se pueden establecer diferentes umbrales en determinados recursos con la xref:/use/alerting/k8s-override-monitor-arguments.adoc[ayuda de anotaciones].

[,yaml]
----
function: {{ get "urn:stackpack:common:monitor-function:threshold" }}
arguments:
  metric:
    query: string
    unit: string
    aliasTemplate: string
  comparator: GTE | GT | LTE | LT     # how to compare metric value to threshold
  threshold: double
  failureState: CRITICAL | DEVIATING | UNKNOWN
  urnTemplate: string
  titleTemplate: string
----

* `+query+`: Una consulta PromQL. Utilice el xref:/use/metrics/k8sTs-explore-metrics.adoc[explorador de métricas] de su instancia {stackstate-product-name}, http://your-instance/#/metrics, y utilícelo para construir la consulta de la métrica de interés.
* `+unit+`: La unidad de los valores de la serie temporal devuelta por la consulta o consultas, utilizada para representar el eje Y del gráfico. Consulte la referencia de xref:/develop/reference/k8sTs-chart-units.adoc[unidades compatibles] para ver todas las unidades.
* `+aliasTemplate+`: Un alias para las series temporales en el gráfico métrico. Se trata de una plantilla que puede sustituir las etiquetas de las series temporales utilizando el marcador de posición `+${my_label}+`.
* `+comparator+`: Elija una de las opciones LTE/LT/GTE/GT para comparar el umbral con la métrica. Las series temporales para las que `+<metric> <comparator> <threshold>+` sea cierta producirán el estado de fallo.
* `+threshold+`: Un umbral numérico con el que comparar.
* `+failureState+`: O "CRÍTICO" o "DESVIADO". "CRÍTICO" se mostrará como leído en {stackstate-product-name} y "DESVIADO" como naranja, para denotar diferente gravedad.
* `+urnTemplate+`: Una plantilla para construir la urna del componente xref:use/alerting/k8s-add-monitors-cli.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[al que se vinculará] el resultado del monitor.
* `+titleTemplate+`: Título para el resultado de un monitor. Dado que varios resultados de monitor pueden vincularse al mismo componente, es posible sustituir las etiquetas de las series temporales utilizando el marcador de posición `+${my_label}+`.

=== Estado derivado

Deriva su estado de las dependencias de los componentes cuyo estado de salud se basa en observaciones. Produce el estado más crítico de las dependencias superiores.
Para más detalles, consulte la página xref:/setup/custom-integrations/monitors/derived-state-monitors.adoc[Monitores de estado derivados].

[,yaml]
----
function: {{ get "urn:stackpack:common:monitor-function:derived-state-monitor" }}
arguments:
  componentTypes: string
----

* `+componentTypes+`: Los tipos de componentes que contribuyen a los estados derivados.  Especificado como una única cadena de valores separados por comas `+,+` 

=== Umbral topológico

Activa un estado de salud cuando se supera un umbral determinado para una consulta métrica especificada. La consulta métrica puede hacer referencia al nombre, las etiquetas y las propiedades de los componentes devueltos por la consulta topológica. Se pueden establecer diferentes umbrales en determinados recursos con la xref:/use/alerting/k8s-override-monitor-arguments.adoc[ayuda de anotaciones].

[,yaml]
----
function: {{ get "urn:stackpack:common:monitor-function:topological-threshold"  }}
arguments:
  queries:
    topologyQuery: string
    promqlQuery: string
    aliasTemplate: string
    unit: string
  comparator: GTE | GT | LTE | LT     # how to compare metric value to threshold
  threshold: double
  failureState: CRITICAL | DEVIATING | UNKNOWN
  titleTemplate: string
----

* `+queries+`: Las consultas a ejecutar
** `+topologyQuery+`: Consulta STQL para seleccionar componentes
** `+promqlQuery+`: Consulta PromQL que puede utilizar etiquetas y propiedades de componentes para seleccionar series temporales
** `+unit+`: La unidad de los valores de la serie temporal devuelta por la consulta o consultas, utilizada para representar el eje Y del gráfico. Consulte la referencia de xref:/develop/reference/k8sTs-chart-units.adoc[unidades compatibles] para ver todas las unidades.
** `+aliasTemplate+`: Un alias para las series temporales en el gráfico métrico. Se trata de una plantilla que puede sustituir las etiquetas de las series temporales utilizando el marcador de posición `+${my_label}+`.
* `+comparator+`: Elija una de las opciones LTE/LT/GTE/GT para comparar el umbral con la métrica. Las series temporales para las que `+<metric> <comparator> <threshold>+` sea cierta producirán el estado de fallo.
* `+threshold+`: Un umbral numérico con el que comparar.
* `+failureState+`: O "CRÍTICO" o "DESVIADO". "CRÍTICO" se mostrará como leído en {stackstate-product-name} y "DESVIADO" como naranja, para denotar diferente gravedad.
* `+titleTemplate+`: Título para el resultado de un monitor. Dado que varios resultados de monitor pueden vincularse al mismo componente, es posible sustituir las etiquetas de las series temporales utilizando el marcador de posición `+${my_label}+`.

=== Umbral dinámico

Alerta cuando el valor actual está fuera del intervalo base previsto, que se calcula dinámicamente a partir de los datos históricos, teniendo en cuenta los patrones estacionales semanales y diarios.
Esta función de monitorización sólo está disponible cuando está instalada la mochila del Detector Autónomo de Anomalías.

Para más detalles, consulte la página xref:/setup/custom-integrations/monitors/dynamic-threshold-monitors.adoc[Monitores de umbral dinámico].

[,yaml]
----
function: {{ get "urn:stackpack:aad-v2:shared:monitor-function:dt" }}
arguments:
  telemetryQuery:
    query: string
    unit: string
    aliasTemplate: string
  topologyQuery: string
  falsePositiveRate: float
  checkWindowMinutes: integer
  historicWindowMinutes: integer
  historySizeWeeks: 1 | 2 | 3 (integer)
  includePreviousDay: boolean
  removeTrend: boolean
----

* `+telemetryQuery+`telemetría para evaluar
** `+query+`: Consulta PromQL que se utiliza para la línea de base y la detección de anomalías
** `+unit+`: La unidad de los valores de la serie temporal devuelta por la consulta o consultas, utilizada para representar el eje Y del gráfico. Consulte la referencia de xref:/develop/reference/k8sTs-chart-units.adoc[unidades compatibles] para ver todas las unidades.
** `+aliasTemplate+`: Un alias para las series temporales en el gráfico métrico. Se trata de una plantilla que puede sustituir las etiquetas de las series temporales utilizando el marcador de posición `+${my_label}+`.
* `+topologyQuery+`: Consulta STQL para seleccionar componentes
* `+falsePositiveRate+`: digamos `+!!float 1e-8+` - la sensibilidad del monitor al comportamiento desviado.  Un valor más bajo suprime más (falsos) positivos, pero también puede dar lugar a falsos negativos (anomalías inadvertidas).
* `+checkWindowMinutes+`digamos `+10+` minutos - la ventana de comprobación debe estar equilibrada entre la alerta rápida (valores pequeños) y las anomalías correctamente identificadas (valores altos).  Un puñado de puntos de datos funciona bien en la práctica.
* `+historicWindowMinutes+`: digamos `+120+` (2 horas) - entre paréntesis alrededor de la hora actual, pero luego una o más semanas atrás - así desde 1 hora antes de la hora actual hasta 1 hora después.  También se utilizan las 2 horas anteriores a la ventana de control.  El monitor de umbral dinámico compara la distribución de estos datos históricos con los puntos de datos de la ventana de comprobación.
* `+historySizeWeeks+`: diga `+2+` - el número de semanas de las que se toman los datos para el contexto histórico.  Puede ser `+1+`, `+2+` o `+3+`.
* `+removeTrend+`para las métricas que tienen un comportamiento tendencial (por ejemplo, el número de solicitudes), de forma que el valor absoluto difiere de una semana a otra, se puede tener en cuenta esta tendencia (el valor medio).
* `+includePreviousDay+``+false+` - para las métricas que no tienen un patrón semanal sino diario, esto permite utilizar datos más recientes.

endif::[]
