= Fournisseurs certifiés de l'IPAO
:revdate: 2025-10-14
:page-revdate: {revdate}

== Qu'entend-on par "prestataires certifiés" ?

Les fournisseurs certifiés sont des fournisseurs CAPI qui sont **activement testés** par les flux de travail CI de l'équipe Turtles pour valider qu'ils fonctionnent correctement avec l'extension CAPI pour Rancher. Cependant, comme la plupart des fournisseurs CAPI sont des projets en amont maintenus par la communauté ouverte Kubernetes, **nous ne pouvons pas garantir** qu'aucun problème n'est introduit au fur et à mesure que de nouvelles versions du fournisseur sont publiées.

== Liste des fournisseurs certifiés

[NOTE]
====
Cette liste est en constante évolution pour refléter le développement continu du projet.
====


Il s'agit d'une liste des fournisseurs CAPI officiellement certifiés par Turtles. Ces fournisseurs sont couverts par notre suite de tests et nous nous assurons activement qu'ils fonctionnent correctement avec l'extension CAPI pour Rancher.

|===
| Plate-forme | Nom du code | Type de prestataire | Docs

| *RKE2*
| CAPRKE2
| Bootstrap/Plan de contrôle
| https://rancher.github.io/cluster-api-provider-rke2[Livre CAPRKE2]

| *Kubeadm*
| Kubeadm
| Bootstrap/Plan de contrôle
| https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap[CABPK docs]

| *AWS*
| CAPA
| Infrastructure
| https://cluster-api-aws.sigs.k8s.io[Livre du CAPA]

| *Docker**
| CAPD
| Infrastructure
| https://cluster-api.sigs.k8s.io[Livre CAPI]

| *vSphere*
| CAPV
| Infrastructure
| https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/getting_started.md[Documents de la CAPV]

| *Azure*
| CAPZ
| Infrastructure
| https://capz.sigs.k8s.io/[Livre du CAPZ]

| *GCP* (uniquement pour les clusters gérés par GKE)
| CAPG
| Infrastructure
| https://cluster-api-gcp.sigs.k8s.io/[Livre de la CAPG]

| *Flotte de fournisseurs d'addons*
| CAAPF
| Addon
| https://rancher.github.io/cluster-api-addon-provider-fleet/[Livre CAAPF]
|===

*Recommandé uniquement à des fins de développement.

== Liste des fournisseurs en mode expérimental

Il s'agit d'une liste de fournisseurs qui sont à un stade avancé de développement et qui seront bientôt certifiés.

|===
| Plate-forme | Nom du code | Type de prestataire | Docs
|===

== Prise en charge de ClusterClass pour les fournisseurs certifiés

Vous trouverez ci-dessous une matrice de prise en charge pour chaque fournisseur certifié et leur prise en charge de la fonction de topologie de cluster :

[tabs]
======
CAPZ::
+
--
- **Prise en charge complète de** `ClusterClass`: les clusters gérés (AKS) et non gérés (machines virtuelles) peuvent être approvisionnés par le biais de la topologie.
--

CAPA::
+
--
- **Prise en charge complète de** `ClusterClass`: les clusters gérés (EKS) et non gérés (basés sur EC2) peuvent être approvisionnés via la topologie.
--

CAPG::
+
--
- **Prise en charge complète de** `ClusterClass`: les clusters gérés (GKE) et non gérés (machines virtuelles) peuvent être approvisionnés par le biais de la topologie.
--

CAPRKE2::
+
--
- **Soutien total à** `ClusterClass`.
--

CABPK::
+
--
- **Soutien total à** `ClusterClass`.
--

CAPV::
+
--
- **Soutien total à** `ClusterClass`.
--

CAPD::
+
--
- **Soutien total à** `ClusterClass`.
--
======
