= Fornecedor de CAPI
:revdate: 2025-08-25
:page-revdate: {revdate}

O recurso `+CAPIProvider+` permite gerenciar manifestos do Operador da API de Cluster de forma declarativa. Ă utilizado para provisionar e configurar provedores da API de Cluster como AWS, vSphere etc.

`+CAPIProvider+` segue um modelo GitOps - os campos de especificaĂ§ĂŁo sĂŁo entradas declarativas do usuĂĄrio. O controlador apenas atualiza o status.

Todos os campos fornecidos pelo recurso upstream do CAPI Operator `+CAPIProviderSpec+` tambĂ©m estĂŁo disponĂ­veis na especificaĂ§ĂŁo do recurso `+CAPIProvider+`. Sinta-se Ă  vontade para consultar os link:https://cluster-api-operator.sigs.k8s.io/03_topics/02_configuration/05_provider-spec-configuration[guias] de configuraĂ§ĂŁo upstream para cenĂĄrios avanĂ§ados.

Todos os Provedores CAPI xref:../overview/certified.adoc[certificados] sĂŁo configurados usando uma configuraĂ§ĂŁo incorporada. Para substituĂ­-la, uma xref:./clusterctlconfig.adoc#_override_a_certified_provider_version[ClusterctlConfig] personalizada precisa ser criada.

== Uso

Para usar o recurso `+CAPIProvider+`:

. Crie um recurso `+CAPIProvider+` com o nome do provedor desejado, tipo, credenciais, configuraĂ§ĂŁo e recursos.
. O controlador `+CAPIProvider+` cuidarĂĄ da geraĂ§ĂŁo dos manifestos necessĂĄrios do Operador da API de Cluster com base na especificaĂ§ĂŁo do `+CAPIProvider+`.
. O campo de status no recurso `+CAPIProvider+` refletirĂĄ o estado dos manifestos gerados.
. Gerencie o objeto `+CAPIProvider+` de forma declarativa para aplicar alteraĂ§Ă”es aos manifestos do provedor gerados.

Aqui estĂĄ um exemplo de manifesto `+CAPIProvider+`:

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws-infra
  namespace: capi-providers
spec:
  name: aws
  type: infrastructure
  enableAutomaticUpdate: true
  credentials:
    rancherCloudCredential: aws-creds # Rancher credentials secret for AWS
  configSecret:
    name: aws-config
  features:
    clusterResourceSet: true
----

Isso irĂĄ gerar um provedor de infraestrutura AWS com o mapeamento fornecido para o segredo de credencial do Rancher e recursos personalizados habilitados.

O controlador `+CAPIProvider+` serĂĄ responsĂĄvel por todos os recursos do provedor gerados, permitindo a coleta de lixo ao excluir o objeto `+CAPIProvider+`.

== EspecificaĂ§ĂŁo

Os campos-chave na especificaĂ§ĂŁo do `+CAPIProvider+` sĂŁo:

* `+name+` - Nome do provedor (aws, vsphere etc). Herdado de `+metadata.name+` se nĂŁo especificado.
* `+type+` - Tipo de recurso do provedor (pode ser definido como `+core+`, `+controlPlane+`, `+bootstrap+`, `+infrastructure+`, `+addon+`, `+ipam+` ou `+runtimeextension+`).
* `+credentials+` - Credenciais de origem para a especificaĂ§ĂŁo do provedor.
* `+configSecret+` - Nome do segredo de configuraĂ§ĂŁo do provedor, onde as variĂĄveis e credenciais sincronizadas serĂŁo armazenadas. Por padrĂŁo, se nĂŁo especificado, herdarĂĄ o nome do recurso `+CAPIProvider+`.
* `+features+` - Recursos do provedor habilitados.
* `+variables+` - VariĂĄveis Ă© um mapa de variĂĄveis de ambiente a serem adicionadas ao conteĂșdo do `+configSecret+`.
* `+version+` - Indica a versĂŁo do provedor.
* `+enableAutomaticUpdate+` - Permitir que o provedor atualize automaticamente. Somente habilitado por padrĂŁo em provedores instalados do grĂĄfico Turtles.
* `+fetchConfig+` - FetchConfig determina como o operador buscarĂĄ os componentes e metadados para o provedor.
** `+oci+` - OCI a ser usado para buscar os componentes e metadados do provedor a partir de um artefato OCI. VocĂȘ deve definir o campo `+providerSpec.Version+` para que o operador escolha a versĂŁo desejada do lanĂ§amento no GitHub. Se o providerSpec.Version estiver ausente, a versĂŁo mais recente do provedor dos padrĂ”es do clusterctl Ă© utilizada.
** `+selector+` - Seletor a ser usado para buscar os componentes e metadados do provedor a partir de ConfigMaps armazenados dentro do cluster. Cada ConfigMap deve conter componentes e metadados apenas para uma versĂŁo especĂ­fica.
** `+url+` - URL a ser usada para buscar os componentes e metadados do provedor de um repositĂłrio remoto do GitHub.

== FixaĂ§ĂŁo de versĂ”es e atualizaĂ§Ă”es automĂĄticas

O `+CAPIProvider+` `+version+` pode ser definido a qualquer momento para fixar o provedor a uma versĂŁo especĂ­fica. AlĂ©m disso, `+automaticUpdates+` pode ser alternado para permitir atualizaĂ§Ă”es automĂĄticas para a versĂŁo mais recente disponĂ­vel. A versĂŁo mais recente disponĂ­vel Ă© determinada pela configuraĂ§ĂŁo incorporada do clusterctl para provedores xref:../overview/certified.adoc[certificados], e pode ser substituĂ­da ou configurada para provedores personalizados usando xref:../reference/clusterctlconfig.adoc[ClusterctlConfig].

== ExclusĂŁo

Quando um recurso `+CAPIProvider+` Ă© excluĂ­do, a coleta de lixo do Kubernetes limparĂĄ todos os recursos de provedor gerados dos quais ele Ă© proprietĂĄrio. Ela inclui:

* InstĂąncia de recurso do Operador da API do Cluster
* Segredo referenciado pelo `+configSecret+`
