= Metriken
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-16
:page-revdate: {revdate}

K3s liefert Metriken zur Überwachung des Zustands und der Leistung des Clusters.

Die meisten Metriken werden von einzelnen Komponenten bereitgestellt. Weitere Informationen finden Sie in der folgenden komponentenspezifischen Dokumentation:

* https://coredns.io/plugins/metrics/[Coredns Metriken]
* https://etcd.io/docs/v3.5/metrics/[etcd-Metriken]

Zusätzliche Metriken können von anderen Komponenten bereitgestellt werden. Konsultieren Sie die vorgelagerte Projektdokumentation für alle oben nicht aufgeführten Komponenten.

== Metriken für Vorgesetzte

Wenn K3s mit `+supervisor-metrics: true+` gestartet wird, werden die Metriken durch den K3s-Prozess offengelegt und können über den Endpunkt `+/metrics+` auf jedem Knoten an Port `+6443+` abgerufen werden:

[,sh]
----
kubectl get --server https://NODENAME:6443 --raw /metrics
----

Der K3s-Überwachungsprozess legt die folgenden Metriken offen:

* K3s Cluster Management Metriken
* https://github.com/rancher/lasso/blob/main/README.md#lasso-controller[Lasso-Controller-Metriken]
* https://github.com/kubernetes/client-go/blob/master/README.md[Kubernetes-Client und Workqueue-Metriken]
* https://kubernetes.io/docs/reference/instrumentation/node-metrics/[Kubernetes-Knoten-Metriken]
* https://kubernetes.io/docs/reference/instrumentation/metrics/[Kubernetes-Komponente Metriken]
* https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics[Go-Laufzeit-Metriken]

Wenn die eingebettete K3s-Registrierung aktiviert ist, stellt der K3s-Supervisor-Prozess auch die folgenden Metriken zur Verfügung:

* https://spegel.dev/docs/metrics/[Spegel-Metriken]
* https://github.com/libp2p/go-libp2p/blob/master/README.md[libp2p-Metriken]

K3s führt alle Kubernetes-Komponenten im Hauptprozess von K3s aus. Da Kubernetes eine einzige Prometheus-Metrikenregistrierung pro Prozess verwendet, sind die Metriken für alle Komponenten über alle exponierten Metrik-Endpunkte verfügbar. Wenn Sie alle einzelnen Metrik-Endpunkte scrapen, stellen Sie möglicherweise fest, dass Sie doppelte Metriken sammeln. Es muss nur ein einziger K3s-Metrik-Endpunkt abgefragt werden, um Metriken für alle eingebetteten Kubernetes-Komponenten zu erhalten.

== K3s Cluster Management Metriken

=== k3s_certificate_expiration_seconds

Verbleibende Lebensdauer des Zertifikats in Sekunden, gekennzeichnet durch Zertifikatsgegenstand und Verwendungen.

* Art: Messgerät
* Etiketten: `+*subject*+`, `+*usage*+`

=== k3s_loadbalancer_server_connections

Anzahl der aktuellen Verbindungen zum Load-Balancer-Server, gekennzeichnet durch den Namen des Load-Balancers und die Serveradresse.

* Art: Messgerät
* Etiketten: `+*name*+`, `+*server*+`

=== k3s_loadbalancer_server_health

Aktueller Status der Lastverteiler-Backend-Server, gekennzeichnet durch den Lastverteilernamen und die Serveradresse.

Status ist eine Aufzählung von 0=INVALID, 1=FAILED, 2=STANDBY, 3=UNCHECKED, 4=RECOVERING, 5=HEALTHY, 6=PREFERRED, 7=ACTIVE.

* Art: Messgerät
* Etiketten: `+*name*+`, `+*server*+`

=== k3s_loadbalancer_dial_duration_seconds

Zeit in Sekunden, die benötigt wird, um eine Verbindung zu einem Backend-Server zu wählen, gekennzeichnet durch den Namen des Load Balancers und den Erfolgs-/Misserfolgsstatus.

* Art: Histogramm
* Etiketten: `+*name*+`, `+*status*+`

=== k3s_etcd_snapshot_save_duration_seconds

Gesamtzeit in Sekunden, die für den Abschluss des etcd-Snapshot-Prozesses benötigt wurde, gekennzeichnet durch den Status Erfolg/Fehlschlag.

* Art: Histrogramm
* Etiketten: `+*status*+`

=== k3s_etcd_snapshot_save_local_duration_seconds

Gesamtzeit in Sekunden, die zum Speichern einer lokalen Snapshot-Datei benötigt wird, gekennzeichnet durch den Status Erfolg/Misserfolg.

* Art: Histrogramm
* Etiketten: `+*status*+`

=== k3s_etcd_snapshot_save_s3_duration_seconds

Gesamtzeit in Sekunden, die für das Hochladen einer Snapshot-Datei auf S3 benötigt wird, gekennzeichnet durch den Status "Erfolg/Misserfolg".

* Art: Histrogramm
* Etiketten: `+*status*+`

=== k3s_etcd_snapshot_reconcile_duration_seconds

Gesamtzeit in Sekunden, die für die Synchronisierung der Liste der etcd-Snapshots benötigt wurde, gekennzeichnet durch den Erfolgs-/Fehlerstatus.

* Art: Histrogramm
* Etiketten: `+*status*+`

=== k3s_etcd_snapshot_reconcile_local_duration_seconds

Gesamtzeit in Sekunden, die für die Auflistung der lokalen Snapshot-Dateien benötigt wird, gekennzeichnet durch den Status "erfolgreich/fehlgeschlagen".

* Art: Histrogramm
* Etiketten: `+*status*+`

=== k3s_etcd_snapshot_reconcile_s3_duration_seconds

Gesamtzeit in Sekunden, die für die Auflistung der S3-Snapshot-Dateien benötigt wird, gekennzeichnet durch den Status "erfolgreich/fehlgeschlagen".

* Art: Histrogramm
* Etiketten: `+*status*+`
