= Ressourcenprofilierung
:page-languages: [en, ja, ko, zh]
:revdate: 2025-01-06
:page-revdate: {revdate}

In diesem Abschnitt werden die Ergebnisse von Tests zur Ermittlung der Mindestanforderungen an die Ressourcen für K3s festgehalten.

== Mindestanforderungen an die Ressourcen für K3s

Die Ergebnisse lassen sich wie folgt zusammenfassen:

|===
| Komponenten | Prozessor | Min CPU | Mindest-RAM mit Kine/SQLite | Min. RAM mit eingebettetem etcd

| K3s-Server mit einer Arbeitslast
| Intel 8375C CPU, 2,90 GHz
| 6% eines Kerns
| 1596 M
| 1606 M

| K3s-Cluster mit einem einzigen Agenten
| Intel 8375C CPU, 2,90 GHz
| 5% eines Kerns
| 1428 M
| 1450 M

| K3s-Agent
| Intel 8375C CPU, 2,90 GHz
| 3% eines Kerns
| 275 M
| 275 M

| K3s-Server mit einer Arbeitslast
| Pi4B BCM2711, 1,50 GHz
| 30 % eines Kerns
| 1588 M
| 1613 M

| K3s-Cluster mit einem einzigen Agenten
| Pi4B BCM2711, 1,50 GHz
| 25% eines Kerns
| 1215 M
| 1413 M

| K3s-Agent
| Pi4B BCM2711, 1,50 GHz
| 10% eines Kerns
| 268 M
| 268 M
|===

=== Umfang der Ressourcenprüfung

Mit den Ressourcentests sollten die folgenden Problemstellungen angegangen werden:

* Bestimmen Sie auf einem Einzelknoten-Cluster die legitime Mindestmenge an CPU, Speicher und IOPs, die für die Ausführung des gesamten K3s-Stack-Server-Stacks beiseite gelegt werden sollte, unter der Annahme, dass eine echte Arbeitslast auf dem Cluster bereitgestellt wird.
* Bestimmen Sie auf einem Agenten- (Arbeits-) Knoten die legitime Mindestmenge an CPU, Speicher und IOPs, die für die Kubernetes- und K3s-Kontrollebene-Komponenten (das Kubelet und den k3s-Agenten) reserviert werden sollte.

=== Komponenten, die für die Baseline-Messungen einbezogen wurden

Die geprüften Komponenten sind:

* K3s v1.26.5 mit allen aktivierten Paketkomponenten
* Prometheus + Grafana Überwachung Stack
* https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[Kubernetes-Beispiel für die Nginx-Bereitstellung]

Dies sind die Basiszahlen für ein stabiles System, das nur K3-Komponenten (Traefik Ingress, Klipper lb, Local-Path-Storage), einen Standard-Monitoring-Stack (Prometheus und Grafana) und die Guestbook-Beispiel-App verwendet.

Ressourcenzahlen, einschließlich IOPS, gelten nur für den Kubernetes-Datenspeicher und die Steuerebene und beinhalten nicht den Overhead für Verwaltungsagenten oder Protokollierung auf Systemebene, Container-Image-Verwaltung oder andere arbeitslastspezifische Anforderungen.

=== Methodik

Eine Standalone-Instanz von Prometheus v2.43.0 wurde verwendet, um Host-CPU-, Speicher- und Festplatten-IO-Statistiken mit `+prometheus-node-exporter+` zu sammeln, das über apt installiert wurde.

`+systemd-cgtop+` wurde verwendet, um die CPU- und Speicherauslastung auf der Ebene der systemd cgroup zu überprüfen. `+system.slice/k3s.service+` verfolgt die Ressourcenauslastung sowohl für K3s als auch für containerd, während die einzelnen Pods unter der Hierarchie `+kubepods+` liegen.

Zusätzliche detaillierte K3s-Speicherauslastungsdaten wurden von `+kubectl top node+` unter Verwendung des integrierten Metrics-Servers für die Server- und Agentenprozesse gesammelt.

Die Auslastungszahlen basieren auf 95-prozentigen Werten aus dem Dauerbetrieb auf Knoten, auf denen die beschriebenen Workloads ausgeführt werden.

=== Umwelt

|===
| Arch | OS | System | CPU | RAM | Festplatte

| x86_64
| Ubuntu 22.04
| AWS c6id.xlarge
| Intel Xeon Platinum 8375C CPU, 4 Kerne 2,90 GHz
| 8 GB
| NVME SSD

| aarch64
| Raspberry Pi OS 11
| Raspberry Pi 4 Modell B
| BCM2711, 4 Kerne 1,50 GHz
| 8 GB
| UHS-III SDXC
|===

=== Grundlegende Ressourcenanforderungen

In diesem Abschnitt werden die Ergebnisse von Tests zur Ermittlung der Mindestanforderungen an die Ressourcen für den grundlegenden K3s-Betrieb aufgeführt.

==== K3s-Server mit einer Arbeitslast

Dies sind die Anforderungen für einen Single-Node-Cluster, in dem sich der K3s-Server die Ressourcen mit einer https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[einfachen Arbeitslast] teilt.

Die CPU-Anforderungen sind:

|===
| System | CPU-Kernauslastung

| Intel 8375C
| 6% eines Kerns

| Pi4B
| 30 % eines Kerns
|===

Die Speicheranforderungen sind:

|===
| Getesteter Datenspeicher | System | Speicher

| Kine/SQLite
| Intel 8375C
| 1596 M

|
| Pi4B
| 1588 M

| Eingebettetes etcd
| Intel 8375C
| 1606 M

|
| Pi4B
| 1613 M
|===

Die Anforderungen an die Festplatte sind:

|===
| Getesteter Datenspeicher | IOPS | KiB/sec | Latenzzeit

| Kine/SQLite
| 10
| 500
| < 10 ms

| Eingebettetes etcd
| 50
| 250
| < 5 ms
|===

==== K3s Cluster mit einem einzelnen Agenten

Dies sind die grundlegenden Anforderungen für einen K3s-Cluster mit einem K3s-Serverknoten und einem K3s-Agenten, aber ohne Arbeitslast.

===== K3s Server

Die CPU-Anforderungen sind:

|===
| System | CPU-Kernauslastung

| Intel 8375C
| 5% eines Kerns

| Pi4B
| 25% eines Kerns
|===

Die Speicheranforderungen sind:

|===
| Getesteter Datenspeicher | System | Speicher

| Kine/SQLite
| Intel 8375C
| 1428 M

|
| Pi4B
| 1215 M

| Eingebettetes etcd
| Intel 8375C
| 1450 M

|
| Pi4B
| 1413 M
|===

===== K3s Agent

Die Anforderungen sind:

|===
| System | CPU-Kernauslastung | RAM

| Intel 8375C
| 3% eines Kerns
| 275 M

| Pi4B
| 5% eines Kerns
| 268 M
|===

=== Analyse der wichtigsten Faktoren für die Ressourcennutzung

Die Serverauslastung von K3 wird in erster Linie durch die Unterstützung des Kubernetes-Datenspeichers (kine oder etcd), des API-Servers, des Controller-Managers und der Scheduler-Kontrollschleifen sowie durch alle Verwaltungsaufgaben bestimmt, die erforderlich sind, um Änderungen am Zustand des Systems vorzunehmen. Vorgänge, die die Kubernetes-Kontrollebene zusätzlich belasten, wie z. B. das Erstellen/Ändern/Löschen von Ressourcen, führen zu vorübergehenden Auslastungsspitzen. Die Verwendung von Operatoren oder Anwendungen, die den Kubernetes-Datenspeicher intensiv nutzen (z. B. Rancher oder andere Anwendungen vom Typ Operator), erhöht den Ressourcenbedarf des Servers. Die Skalierung des Clusters durch das Hinzufügen zusätzlicher Knoten oder das Erstellen vieler Cluster-Ressourcen erhöht den Ressourcenbedarf des Servers.

Die Auslastung der K3-Agenten ist in erster Linie auf die Unterstützung von Regelkreisen für das Container-Lebenszyklusmanagement zurückzuführen. Vorgänge, die die Verwaltung von Images, die Bereitstellung von Speicherplatz oder die Erstellung/Löschung von Containern beinhalten, führen zu vorübergehenden Auslastungsspitzen. Insbesondere Image-Pulls sind in der Regel sehr CPU- und IO-lastig, da sie die Dekomprimierung von Bildinhalten auf der Festplatte beinhalten. Wenn möglich, sollte der Workload-Speicher (ephemerer Pod-Speicher und Volumes) von den Agentenkomponenten (/var/lib/rancher/k3s/agent) isoliert werden, um sicherzustellen, dass keine Ressourcenkonflikte entstehen.

=== Verhindern der Beeinträchtigung des Cluster-Datenspeichers durch Agenten und Workloads

Bei der Ausführung in einer Umgebung, in der der Server auch Workload-Pods hostet, sollte darauf geachtet werden, dass die IOPS von Agenten und Workloads den Datenspeicher nicht beeinträchtigen.

Dies lässt sich am besten erreichen, indem die Serverkomponenten (/var/lib/rancher/k3s/server) auf einem anderen Speichermedium abgelegt werden als die Agentenkomponenten (/var/lib/rancher/k3s/agent), die den Containerd-Image-Speicher enthalten.

Der Workload-Speicher (ephemerer Pod-Speicher und Volumes) sollte ebenfalls vom Datenspeicher isoliert werden.

Werden die Anforderungen an den Durchsatz und die Latenzzeit des Datenspeichers nicht erfüllt, kann dies zu einer verzögerten Reaktion der Steuerungsebene führen und/oder dazu, dass die Steuerungsebene den Systemzustand nicht aufrechterhalten kann.

[#_server_sizing_requirements_for_k3s]
== Anforderungen an die Servergröße für K3s

=== Umwelt

* Alle Agenten waren t3.medium AWS ec2-Instanzen.
** Ein einzelner Agent war eine c5,4xgroße Instanz. Dadurch wurde der Grafana-Monitoring-Stack gehostet und verhindert, dass er die Ressourcen der Steuerungsebene beeinträchtigt.
* Der Server war eine c5 AWS ec2-Instanz. Als die Zahl der Agenten stieg, wurde der Server auf größere c5-Instanzen aufgerüstet.

=== Methodik

Diese Daten wurden unter bestimmten Testbedingungen abgerufen. Dies hängt von der Umgebung und der Arbeitsbelastung ab. Die folgenden Schritte geben einen Überblick über den Test, der durchgeführt wurde, um dies zu ermitteln. Sie wurde zuletzt mit v1.31.0+k3s1 durchgeführt. Alle Rechner wurden in AWS mit standardmäßigen 20-GiB-gp3-Volumes bereitgestellt. Der Test wurde mit den folgenden Schritten durchgeführt:

. Überwachen Sie Ressourcen auf Grafana mit der Datenquelle Prometheus. 
. Stellen Sie Workloads so bereit, dass eine kontinuierliche Clusteraktivität simuliert wird:
** Eine Basis-Arbeitslast, die kontinuierlich nach oben und unten skaliert
** Eine Arbeitslast, die in einer Schleife gelöscht und neu erstellt wird
** Eine konstante Arbeitslast, die mehrere andere Ressourcen einschließlich CRDs enthält.
. Verbinden Sie Agenten-Knoten in Stapeln von 50-100 auf einmal.
. Beenden Sie das Hinzufügen von Agenten, wenn die CPU-Auslastung des Servers beim Beitritt eines Agenten 90 % übersteigt oder wenn der Arbeitsspeicher zu mehr als 80 % ausgelastet ist. 

=== Beobachtungen

* Beim Beitritt von Agenten kam es bei der Server-CPU zu Spitzen von ~20 % gegenüber dem Basiswert.
* In der Regel war der begrenzende Faktor die CPU, nicht der Arbeitsspeicher. Bei den meisten Tests, bei denen die CPU zu 90 % ausgelastet war, lag die RAM-Auslastung bei etwa 60 %.

==== Ein Hinweis zur Hochverfügbarkeit (HA)

Am Ende jedes Tests wurden zwei weitere Server hinzugefügt (die einen einfachen HA-Cluster mit drei Knoten bildeten), um zu beobachten, wie sich dies auf die ursprünglichen Serverressourcen auswirkte. Die Wirkung war:

* Ein spürbarer Rückgang der CPU-Auslastung, in der Regel 30-50 %.
* Die RAM-Auslastung ist gleich geblieben.

Es wurde zwar nicht getestet, aber mit der CPU-Auslastung als limitierendem Faktor auf einem einzelnen Server wird erwartet, dass die Anzahl der Agenten, die verbunden werden können, mit einem 3-Knoten-HA-Cluster um ~50% steigen würde.
