= certificado k3s
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-30
:page-revdate: {revdate}

[#_client_and_server_certificates]
== Certificados de cliente y servidor

Los certificados de cliente y servidor de K3 tienen una validez de 365 días a partir de su fecha de emisión.
Los certificados caducados o a 120 días de caducar se renuevan automáticamente cada vez que se inicia K3s.
Esta renovación reutiliza las claves existentes y prolonga la vida útil de los certificados existentes.
Si desea generar nuevos certificados y claves, en lugar de ampliar la validez de los certificados existentes, utilice el subcomando xref:#_rotating_client_and_server_certificates[`rotate`] documentado a continuación.

Cuando un certificado está a menos de 120 días de caducar se crea un Evento de Advertencia de Kubernetes con `reason: CertificateExpirationWarning`, con una relación al Nodo que utiliza el certificado.

Antes de las versiones de mayo de 2025 (v1.33.1+k3s1, v1.32.5+k3s1, v1.31.9+k3s1, v1.30.13+k3s1), las alertas y la rotación se activaban a los 90 días, en lugar de a los 120 días.

=== Comprobación de las fechas de caducidad

[IMPORTANT]
.Versión Puerta
====
El formato de salida es configurable a partir de las versiones de enero de 2025: v1.32.0+k3s1, v1.31.5+k3s1, v1.30.9+k3s1, v1.30.13+k3s1.

Un nuevo formato con más información está disponible a partir de las versiones de mayo de 2025: v1.33.1+k3s1, v1.32.5+k3s1, v1.31.9+k3s1, v1.29.13+k3s1.
====

Para comprobar los certificados de nodo y su fecha de caducidad utilice la página `k3s certificate check --output table`:

[,bash]
----
FILENAME                    SUBJECT                     USAGES       EXPIRES                  RESIDUAL TIME   STATUS
--------                    -------                     ------       -------                  -------------   ------
client-kube-proxy.crt       system:kube-proxy           ClientAuth   Jun 09, 2026 10:17 UTC   1 year          OK
client-kube-proxy.crt       k3s-client-ca@1749464211    CertSign     Jun 07, 2035 10:16 UTC   10 years        OK
client-kubelet.crt          system:node:ip-10-11-0-14   ClientAuth   Jun 09, 2026 10:17 UTC   1 year          OK
client-kubelet.crt          k3s-client-ca@1749464211    CertSign     Jun 07, 2035 10:16 UTC   10 years        OK
serving-kubelet.crt         ip-10-11-0-14               ServerAuth   Jun 09, 2026 10:17 UTC   1 year          OK
serving-kubelet.crt         k3s-server-ca@1749464211    CertSign     Jun 07, 2035 10:16 UTC   10 years        OK
client-k3s-controller.crt   system:k3s-controller       ClientAuth   Jun 09, 2026 10:17 UTC   1 year          OK
client-k3s-controller.crt   k3s-client-ca@1749464211    CertSign     Jun 07, 2035 10:16 UTC   10 years        OK
----

[NOTE]
.EL MISMO CERTIFICADO DOS VECES
====
Cada archivo de certificado`(` columna`FILENAME ` ) contiene al menos dos certificados: el certificado de cliente/servidor de la hoja (o entidad final), cualquier certificado de entidad emisora de certificados intermedio y el certificado de entidad emisora de certificados raíz.
====

En caso de salida inesperada, asegúrese de que está especificando el directorio de datos correcto con la bandera `--data-dir` (si utiliza un directorio de datos personalizado), o utilice la bandera `--debug` para obtener salida adicional del proceso de comprobación.

[#_rotating_client_and_server_certificates]
=== Rotación de certificados de cliente y servidor

Para rotar manualmente los certificados de cliente y servidor, utilice el subcomando `k3s certificate rotate`:

[,bash]
----
# Stop K3s
systemctl stop k3s

# Rotate certificates
k3s certificate rotate

# Start K3s
systemctl start k3s
----

Se pueden rotar certificados individuales o listas de certificados especificando el nombre del certificado:

[,bash]
----
k3s certificate rotate --service <SERVICE>,<SERVICE>
----

Se pueden rotar los siguientes certificados: `admin`, `api-server`, `controller-manager`, `scheduler`, `k3s-controller`, `k3s-server`, `cloud-controller`, `etcd`, `auth-proxy`, `kubelet`, `kube-proxy`.

[#_certificate_authority_ca_certificates]
== Certificados de autoridad de certificación (CA)

Kubernetes requiere una serie de certificados CA para su correcto funcionamiento. Para obtener más información sobre cómo Kubernetes utiliza los certificados de CA, consulte la documentación de PKI de Kubernetes https://kubernetes.io/docs/setup/best-practices/certificates/#all-certificates[Certificados y requisitos].

Por defecto, K3s genera certificados CA autofirmados durante el arranque del primer nodo servidor. Estos certificados de CA son válidos durante 10 años a partir de la fecha de emisión y no se renuevan automáticamente.

Los certificados de CA autoritativos y las claves se almacenan dentro de la clave de arranque del almacén de datos, cifrados utilizando el xref:cli/token.adoc#_server[token del servidor] como frase de contraseña PBKDF2 con AES256-GCM y HMAC-SHA1.
Las copias de los certificados CA y las claves se extraen al disco durante el arranque del servidor K3s.
Cualquier servidor puede generar certificados de hoja para los nodos a medida que se unen al clúster, y los controladores de Kubernetes https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/[la API de certificados de] pueden emitir certificados adicionales en tiempo de ejecución.

Para rotar certificados y claves CA, utilice el comando `k3s certificate rotate-ca`.
El comando realiza comprobaciones de integridad para confirmar que los certificados y claves actualizados son utilizables.
Si los datos actualizados son aceptables, se actualiza la clave de arranque cifrada del almacén de datos, y los nuevos certificados y claves se utilizarán la próxima vez que se inicie K3s.
Si surgen problemas al validar los certificados y las claves, se informa de un error en el registro del sistema y se cancela la operación sin cambios.

[IMPORTANT]
.Versión Puerta
====
La compatibilidad con el comando `k3s certificate rotate-ca` y la posibilidad de utilizar certificados CA firmados por una CA externa está disponible a partir de las versiones 2023-02 (v1.26.2+k3s1, v1.25.7+k3s1, v1.24.11+k3s1, v1.23.17+k3s1).
====


=== Uso de certificados de CA personalizados

==== Precauciones contra la reutilización de CA

[WARNING]
====
No se recomienda compartir CA raíz o intermedias entre varios clústeres, ni utilizar una CA privada existente como CA de clúster.
====

Cuando varios clusters comparten una raíz de confianza común, cualquier certificado de cliente o servidor emitido por un cluster también será fiable para todos los demás clusters, ya que todos los certificados se encadenan al mismo anclaje de confianza: la Autoridad de Certificación Raíz común.
Esto significa que cualquier usuario con un certificado de cliente válido (o kubeconfig) para un clúster también puede autenticarse en otros clústeres, y cualquier RBAC que coincida con el usuario o grupo de un cliente también se aplica en esos otros clústeres.
Del mismo modo, los certificados de servidor emitidos por un clúster también son de confianza en todos los demás clústeres, y por todas las demás infraestructuras o clientes que confían en esa CA raíz.

Kubernetes no admite el uso de listas de revocación de certificados.
Si alguna vez necesita revocar un certificado por cualquier motivo (por ejemplo, debido a una kubeconfig de administrador comprometida), debe realizar una sustitución completa de la Autoridad de Certificación del clúster para invalidar la confianza del certificado.

==== Uso de certificados de CA personalizados

Si los certificados CA y las claves se encuentran en la ubicación correcta durante el arranque inicial del primer servidor del clúster, se omitirá la generación automática de certificados CA.

Hay disponible un script de ejemplo para crear previamente los certificados y claves adecuados https://github.com/k3s-io/k3s/blob/main/contrib/util/generate-custom-ca-certs.sh[en el repositorio de K3s en `contrib/util/generate-custom-ca-certs.sh`].
Este script debe ejecutarse antes de iniciar K3s por primera vez, y creará un conjunto completo de certificados de CA de hoja firmados por certificados de CA Raíz e Intermedia comunes.
Si dispone de una CA raíz o intermedia existente, puede utilizar este script (o utilizarlo como punto de partida) para crear los certificados de CA correctos para aprovisionar un clúster K3s con PKI arraigada en una autoridad existente.

Los archivos de la autoridad de certificación personalizada deben colocarse en `/var/lib/rancher/k3s/server/tls`. Se necesitan los siguientes archivos:

* `server-ca.crt`
* `server-ca.key`
* `client-ca.crt`
* `client-ca.key`
* `request-header-ca.crt`
* `request-header-ca.key` +
_// nota: los archivos etcd son necesarios incluso si el etcd incrustado no está en uso._
* `etcd/peer-ca.crt`
* `etcd/peer-ca.key`
* `etcd/server-ca.crt`
* `etcd/server-ca.key` +
_// nota: Es la clave privada utilizada para firmar los tokens de cuenta de servicio. No dispone del certificado correspondiente._
* `service.key`

==== Topología de CA personalizada

Los certificados CA personalizados generados por el script de ejemplo tienen la siguiente topología:

[mermaid]
....
gráfico TD root("CA raíz") intermediate("CA intermedia") server-ca("CA servidor") client-ca("CA cliente") request-header-ca("CA agregación API") etcd-peer-ca("CA par etcd") etcd-server-ca("CA servidor etcd")

  root-hash>"Join token CA hash"]

  kube-server-certs[["Kubernetes servers<br/>(control-plane and kubelet listeners)"]]kube-client-certs[["Kubernetes clients<br/>(apiserver and kubelet clients)"]]request-header-certs[["Kubernetes API aggregation<br/>(apiserver proxy client)"]]etcd-peer-certs[["etcd peer client/server<br/>(etcd replication)"]]etcd-server-certs[["etcd client/server certificates<br/>(Kubernetes <-> etcd)"]]

  root -.-|SHA256| root-hash
  root ---> intermediate
  intermediate --> server-ca ==> kube-server-certs
  intermediate --> client-ca ==> kube-client-certs
  intermediate --> request-header-ca ==> request-header-certs
  intermediate --> etcd-peer-ca ==> etcd-peer-certs
  intermediate --> etcd-server-ca ==> etcd-server-certs
....

==== Uso del script de ejemplo

[IMPORTANT]
.Importante
====
Si desea firmar los certificados de CA de clúster con una CA raíz existente utilizando el script de ejemplo, debe colocar los archivos raíz e intermedio en el directorio de destino antes de ejecutar el script.
Si los archivos no existen, el script creará nuevos certificados de CA raíz e intermedios.
====


Si sólo desea utilizar un certificado de CA raíz existente, proporcione los siguientes archivos:

* `root-ca.pem`
* `root-ca.key`

Si desea utilizar certificados de CA raíz e intermedios existentes, proporcione los siguientes archivos:

* `root-ca.pem`
* `intermediate-ca.pem`
* `intermediate-ca.key`

El script de ejemplo utiliza las CA proporcionadas como raíz para todos los paquetes de CA de clúster: servidor, cliente, agregación de API y etcd Peer/Server.
Para casos de uso avanzados, como el uso de las CA proporcionadas sólo para determinados paquetes, o el uso de diferentes CA para diferentes paquetes, el script de ejemplo debe modificarse para satisfacer las necesidades específicas de su organización.

Para utilizar el script de ejemplo para generar certificados y claves personalizados antes de iniciar K3s, ejecute los siguientes comandos:

[,bash]
----
# Create the target directory for cert generation.
mkdir -p /var/lib/rancher/k3s/server/tls

# Copy your root CA cert and intermediate CA cert+key into the correct location for the script.
# For the purposes of this example, we assume you have existing root and intermediate CA files in /etc/ssl.
# If you do not have an existing root and/or intermediate CA, the script will generate them for you.
cp /etc/ssl/certs/root-ca.pem /etc/ssl/certs/intermediate-ca.pem /etc/ssl/private/intermediate-ca.key /var/lib/rancher/k3s/server/tls

# Generate custom CA certs and keys.
curl -sL https://github.com/k3s-io/k3s/raw/main/contrib/util/generate-custom-ca-certs.sh | bash -
----

Si el comando se completa con éxito, puede instalar y/o iniciar K3s por primera vez.
Si la secuencia de comandos generó archivos de CA raíz y/o intermedios, debe realizar una copia de seguridad de estos archivos para poder reutilizarlos si es necesario rotar los certificados de CA más adelante.

=== Rotación de certificados CA personalizados

Para rotar certificados CA personalizados, utilice el subcomando `k3s certificate rotate-ca`.
Los archivos actualizados deben colocarse en un directorio temporal, cargarse en el almacén de datos y reiniciarse k3s en todos los nodos para utilizar los certificados actualizados.

[CAUTION]
====
No debe sobrescribir los datos actualmente en uso en `/var/lib/rancher/k3s/server/tls`. +
Coloca los certificados y claves actualizados en un directorio aparte.
====


Un clúster que se haya iniciado con certificados de CA personalizados puede renovar o rotar los certificados y claves de CA sin interrupciones, siempre que se utilice la misma CA raíz.

Si se requiere una nueva CA raíz, la rotación será perjudicial. Debe utilizarse la opción `k3s certificate rotate-ca --force`, todos los nodos que se unieron con un xref:cli/token.adoc#_secure[token seguro] (incluidos los servidores) deberán reconfigurarse para utilizar el nuevo valor del token, y los pods deberán reiniciarse para confiar en la nueva CA raíz.

==== Uso del script de ejemplo

El script de ejemplo `generate-custom-ca-certs.sh` enlazado anteriormente también puede utilizarse para generar certificados actualizados en un nuevo directorio temporal, copiando los archivos en la ubicación correcta y estableciendo la variable de entorno `DATA_DIR`.
Para utilizar el script de ejemplo para generar certificados y claves actualizados, ejecute los siguientes comandos:

[,bash]
----
# Create a temporary directory for cert generation.
mkdir -p /opt/k3s/server/tls

# Copy your root CA cert and intermediate CA cert+key into the correct location for the script.
# Non-disruptive rotation requires the same root CA that was used to generate the original certificates.
# If the original files are still in the data directory, you can just run:
cp /var/lib/rancher/k3s/server/tls/root-ca.* /var/lib/rancher/k3s/server/tls/intermediate-ca.* /opt/k3s/server/tls

# Copy the current service-account signing key, so that existing service-account tokens are not invalidated.
cp /var/lib/rancher/k3s/server/tls/service.key /opt/k3s/server/tls

# Generate updated custom CA certs and keys.
curl -sL https://github.com/k3s-io/k3s/raw/main/contrib/util/generate-custom-ca-certs.sh | DATA_DIR=/opt/k3s bash -

# Load the updated CA certs and keys into the datastore.
k3s certificate rotate-ca --path=/opt/k3s/server
----

Si el comando `rotate-ca` devuelve un error, compruebe si hay errores en el registro de servicio.
Si el comando se completa correctamente, reinicie los K3 en todos los nodos del clúster: primero los servidores y después los agentes.

Si ha utilizado la opción `--force` o ha cambiado la CA raíz, asegúrese de que todos los nodos que se unieron con un xref:cli/token.adoc#_secure[token] seguro se reconfiguran para utilizar el nuevo valor del token, antes de reiniciarse.
El token puede almacenarse en un archivo `.env`, una unidad systemd o config.yaml, dependiendo de cómo se configuró el nodo durante la instalación inicial.

=== Rotación de certificados CA autofirmados

Para girar los certificados CA autofirmados generados por K3s, utilice el subcomando `k3s certificate rotate-ca`.
Los archivos actualizados deben colocarse en un directorio temporal, cargarse en el almacén de datos y reiniciarse k3s en todos los nodos para utilizar los certificados actualizados.

[CAUTION]
====
No debe sobrescribir los datos actualmente en uso en `/var/lib/rancher/k3s/server/tls`. +
Coloca los certificados y claves actualizados en un directorio aparte.
====


Si el clúster se ha iniciado con certificados CA autofirmados por defecto, la rotación será perjudicial. Todos los nodos que se unieron con un xref:cli/token.adoc#_secure[token] seguro necesitarán ser reconfigurados para confiar en el nuevo hash de la CA.
Si los nuevos certificados de CA no tienen firma cruzada con los certificados de CA antiguos, tendrá que utilizar la opción `--force` para saltarse las comprobaciones de integridad, y será necesario reiniciar los pods para que confíen en la nueva CA raíz.

==== Topología CA por defecto

Los certificados CA autofirmados por defecto tienen la siguiente topología:

[mermaid]
....
graph TD server-ca("CA del servidor") client-ca("CA del cliente") request-header-ca("CA de agregación de API") etcd-peer-ca("CA del par etcd") etcd-server-ca("CA del servidor etcd")

  root-hash>"Join token CA hash"]

  kube-server-certs[["Kubernetes servers<br/>(control-plane and kubelet listeners)"]]kube-client-certs[["Kubernetes clients<br/>(apiserver and kubelet clients)"]]request-header-certs[["Kubernetes API aggregation<br/>(apiserver proxy client)"]]etcd-peer-certs[["etcd peer client/server<br/>(etcd replication)"]]etcd-server-certs[["etcd client/server certificates<br/>(Kubernetes <-> etcd)"]]

  server-ca -.-|SHA256| root-hash
  server-ca ===> kube-server-certs
  client-ca ===> kube-client-certs
  request-header-ca ===> request-header-certs
  etcd-peer-ca ===> etcd-peer-certs
  etcd-server-ca ===> etcd-server-certs
....

Al rotar las CA autofirmadas por defecto, se puede utilizar una topología de certificados modificada con CA intermedias y una nueva CA raíz con firma cruzada de la CA antigua, de modo que exista una cadena de confianza continua entre la CA antigua y la nueva:

[mermaid]
....
graph TD server-ca-old("CA de servidor<br/>(antigua)") client-ca-old("CA de cliente<br/>(antigua)") request-header-ca-old("CA de agregación de API<br/>(antigua)") etcd-peer-ca-old("CA de par etcd<br/>(antigua)") etcd-server-ca-old("CA de servidor etcd<br/>(antigua)")

  root-hash>"Join token CA hash"]

  server-ca-xsigned("CA de servidor<br/>(con firma cruzada)") client-ca-xsigned("CA de cliente<br/>(con firma cruzada)") request-header-ca-xsigned("API Aggregation CA<br/>(cross-signed)") etcd-peer-ca-xsigned("etcd Peer CA<br/>(cross-signed)") etcd-server-ca-xsigned("etcd Server CA<br/>(cross-signed)")

  server-ca-ssigned("Server CA<br/>(self-signed)")
  client-ca-ssigned("Client CA<br/>(self-signed)")
  request-header-ca-ssigned("API Aggregation CA<br/>(self-signed)")
  etcd-peer-ca-ssigned("etcd Peer CA<br/>(self-signed)")
  etcd-server-ca-ssigned("etcd Server CA<br/>(self-signed)")

  server-ca("CA intermedia de servidor<br/>") client-ca("CA intermedia de cliente<br/>") request-header-ca("CA intermedia de agregación de API<br/>") etcd-peer-ca("CA intermedia de pares<br/>etcd") etcd-server-ca("CA intermedia de servidor<br>etcd")

  kube-server-certs[["Kubernetes servers<br/>(control-plane and kubelet listeners)"]]
  kube-client-certs[["Kubernetes clients<br/>(apiserver and kubelet clients)"]]
  request-header-certs[["Kubernetes API aggregation<br/>(apiserver proxy client)"]]
  etcd-peer-certs[["etcd peer client/server<br/>(etcd replication)"]]
  etcd-server-certs[["etcd client/server certificates<br/>(Kubernetes <-> etcd)"]]

  server-ca-ssigned -.-|SHA256| root-hash server-ca-ssigned --> server-ca ==> kube-server-certs server-ca\--old --> server-ca-xsigned --> server-ca client-ca-ssigned -->. client-ca ==> kube-client-certs client-ca-old --> client-ca-xsigned --> client-ca request-header-ca-ssigned --> request-header-ca ==> request-header-certs request-header-ca-old --> request-header-ca-xsigned --> request-header-ca etcd-peer-ca-signed --> etcd-peer-ca ==> etcd-peer-certs etcd-peer-ca-old --> etcd-peer-ca-xsigned --> etcd-peer-ca etcd-server-ca-signed --> etcd-server-ca ==> etcd-server-certs etcd-server-ca-old --> etcd-server-ca-xsigned --> etcd-server-ca
....

==== Uso del script de ejemplo

Un script de ejemplo para crear certificados CA actualizados y claves con firma cruzada de las CA existentes está disponible https://github.com/k3s-io/k3s/blob/main/contrib/util/rotate-default-ca-certs.sh[en el repositorio K3s en `contrib/util/rotate-default-ca-certs.sh`].

Para utilizar el script de ejemplo para generar certificados autofirmados actualizados que cuenten con la firma cruzada de las CA existentes, ejecute los siguientes comandos:

[,bash]
----
# Create updated CA certs and keys, cross-signed by the current CAs.
# This script will create a new temporary directory containing the updated certs, and output the new token values.
curl -sL https://github.com/k3s-io/k3s/raw/main/contrib/util/rotate-default-ca-certs.sh | bash -

# Load the updated certs into the datastore; see the script output for the updated token values.
k3s certificate rotate-ca --path=/var/lib/rancher/k3s/server/rotate-ca
----

Si el comando `rotate-ca` devuelve un error, compruebe si hay errores en el registro de servicio.
Si el comando se completa correctamente, reinicie los K3 en todos los nodos del clúster: primero los servidores y después los agentes.

Asegúrese de que todos los nodos que se unieron con un xref:cli/token.adoc#_secure[token seguro], incluidos otros nodos de servidor, se reconfiguran para utilizar el nuevo valor del token antes de reiniciarse.
El token puede almacenarse en un archivo `.env`, una unidad systemd o config.yaml, dependiendo de cómo se configuró el nodo durante la instalación inicial.

== Rotación de claves del emisor de la cuenta de servicio

La clave del emisor de la cuenta de servicio es una clave privada RSA utilizada para firmar los tokens de la cuenta de servicio.
Al rotar la clave del emisor de la cuenta de servicio, debe conservarse en el archivo al menos una clave antigua para que no se invaliden los tokens de cuenta de servicio existentes.
Se puede rotar independientemente de las CA del clúster utilizando `k3s certificate rotate-ca` para instalar sólo un archivo `service.key` actualizado que incluya tanto las claves nuevas como las antiguas.

[CAUTION]
====
No debe sobrescribir los datos actualmente en uso en `/var/lib/rancher/k3s/server/tls`. +
Coloque la clave actualizada en un directorio aparte.
====


Por ejemplo, para rotar sólo la clave de emisor de la cuenta de servicio, ejecute los siguientes comandos:

[,bash]
----
# Create a temporary directory for cert generation
mkdir -p /opt/k3s/server/tls

# Check OpenSSL version
openssl version | grep -qF 'OpenSSL 3' && OPENSSL_GENRSA_FLAGS=-traditional

# Generate a new key
openssl genrsa ${OPENSSL_GENRSA_FLAGS:-} -out /opt/k3s/server/tls/service.key 2048

# Append the existing key to avoid invalidating current tokens
cat /var/lib/rancher/k3s/server/tls/service.key >> /opt/k3s/server/tls/service.key

# Load the updated key into the datastore
k3s certificate rotate-ca --path=/opt/k3s/server
----

Es normal que aparezcan advertencias sobre archivos que no se están actualizando. Si el comando `rotate-ca` devuelve un error, compruebe si hay errores en el registro de servicio.
Si el comando se completa correctamente, reinicie los K3 en todos los servidores del clúster. No es necesario reiniciar los agentes ni reiniciar ningún pod.
