include::partial$variables.adoc[]
= C#
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Explore e escreva a validação e a mutação de políticas de controle de admissão usando o SDK do .NET Core com suporte a WASI em plataformas WebAssembly, como o Kubernetes.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "c#"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "políticas de escrita", "c#", ".net"]
:sidebar_label: C#
:sidebar_position: 40
:current-version: {page-origin-branch}

Atualmente, o .NET Core tem suporte experimental para a plataforma WASI do WebAssembly.
Isso é do projeto https://github.com/SteveSandersonMS/dotnet-wasi-sdk[`dotnet-wasi-sdk`] projeto.

[NOTE]
====

Você não precisa de uma instalação do Windows para escrever ou executar o código do .NET Core.
Tudo pode ser feito também em uma máquina Linux ou macOS.
====


== Estado atual

Os autores de políticas podem usar os seguintes recursos:

* https://github.com/kubewarden/policy-sdk-dotnet[{project-name}.NET Core SDK]: fornece um conjunto de objetos e funções que simplificam o processo de criação de políticas.
* https://github.com/kubewarden/policy-sdk-dotnet/tree/main/example[{short-project-name} exemplo de política]: este é um exemplo de uma política em funcionamento.

Não há limitações conhecidas.
O SDK permite escrever políticas de validação e de mutação.

É possível usar a bibliotecahttps://www.nuget.org/packages/KubernetesClient.Models[`KubernetesClient.Models`]para lidar com os objetos do Kubernetes.

== Modelo de projeto

No momento, não temos um modelo de projeto que possa estruturar uma política em C#.

Por favor, https://github.com/kubewarden/policy-sdk-dotnet/issues[abra uma edição]se estiver interessado.
