include::partial$variables.adoc[]
= Metadados da política
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure os metadados da política no arquivo metadata.yaml para definir as configurações da política, as informações do autor e as permissões de recursos.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "policy-metadata"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "desenvolvimento de política de kubernetes", "metadados de política"]
:current-version: {page-origin-branch}

O arquivo de metadados {project-name}, `metadata.yaml`, é um arquivo de configuração que contém informações e configurações importantes relacionadas às políticas usadas em {short-project-name}.
Esta documentação é uma visão geral da finalidade e do uso do arquivo de metadados.

O arquivo `metadata.yaml` da política tem padrões para a política, bem como metadados, como autor e descrição, definidos pelo autor da política.
O comando `kwctl annotate` usa o arquivo para anotar o arquivo `.wasm` que contém a política.
Portanto, todas as informações relevantes necessárias para executar a política estão disponíveis.
Mais informações sobre como fazer anotações na política estão no guiaxref:../../explanations/distributing-policies.adoc[Distribuindo políticas].

Quando os usuários de políticas desejam usar uma política, eles geram um manifesto YAML usando `kwctl scaffold`.
Esse comando lê os metadados da política incorporados no módulo Wasm enviado, realiza verificações e retorna um manifesto YAML que o autor pode usar como está ou modificar.

Como autor de uma política, você pode adaptar o arquivo `metadata.yaml` fornecido durante a estruturação da sua política.

Veja o exemplo a seguir de um `metadata.yaml`:

[subs="+attributes",yaml]
----
rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations: ["CREATE"]
mutating: false
contextAwareResources: []
executionMode: kubewarden-wapc
policyType: kubernetes
backgroundAudit: true
annotations:
  # kubewarden specific:
  io.kubewarden.policy.title: My policy
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: Short description
  io.kubewarden.policy.author: myself
  io.kubewarden.policy.url: https://github.com/yourorg/my-policy
  io.kubewarden.policy.source: https://github.com/yourorg/my-policy
  io.kubewarden.policy.license: Apache-2.0
  # The next two annotations are used in the policy report generated by the
  # Audit scanner. Severity indicates policy check result criticality and
  # Category indicates policy category. See more here at docs.kubewarden.io
  io.kubewarden.policy.severity: medium
  io.kubewarden.policy.category: Resource validation
  # artifacthub specific: (optional, to release in Artifact Hub)
  io.kubewarden.policy.ociUrl: ghcr.io/myorg/my-policy
  io.artifacthub.displayName: Policy Name
  io.artifacthub.resources: Pod
  io.artifacthub.keywords: pod, cool policy, kubewarden
----

== Ativação de verificações de auditoria em segundo plano

O arquivo de metadados inclui um sinalizador, `backgroundAudit`, que ativa as verificações de auditoria em segundo plano para uma política específica.
Por padrão, esse sinalizador é definido como `true`.

Há políticas que, devido à maneira como funcionam ou ao tipo de eventos com os quais se preocupam, devem ter esse campo definido como `false`.
É possível encontrar mais informações naxref:explanations/audit-scanner/limitations.adoc[documentação do scanner de auditoria], na seção de limitações.

== Definição dos recursos do Kubernetes que as políticas podem acessar

No arquivo de metadados, usando o campo `contextAwareResources`, os usuários podem definir quais recursos do Kubernetes a política pode acessar.
Por exemplo, se a política precisar de acesso ao recurso `Namespace`.
O autor da política pode definir o `contextAwareResources` como:

[subs="+attributes",yaml]
----
[...]
contextAwareResources:
  - apiVersion: v1 kind: Namespace
[...]
----

== Especificação de políticas como mutantes ou não mutantes

O arquivo de metadados tem um sinalizador, `mutating`, que permite aos usuários configurar uma política como mutante ou não mutante.
Uma política mutante modifica as solicitações recebidas ou os recursos que estão sendo gerenciados.
Uma política sem mutação observa e aplica restrições sem fazer nenhuma alteração.
Essa distinção é crucial para determinar como as políticas interagem com os recursos do Kubernetes e seu impacto no cluster.

== Especificar o tipo de política como Kubernetes ou Raw

O arquivo de metadados tem um sinalizador, `policyType`, que permite que os usuários marquem uma política como `kubernetes` ou `raw`.
Uma política do Kubernetes é uma política que valida os recursos do Kubernetes.
Uma política Raw é uma política que valida documentos JSON arbitrários.
Por padrão, se não for especificado pelo usuário, esse campo será definido como `kubernetes` ao anotar uma política.
Consulte a seção xref:../../howtos/raw-policies.adoc[Políticas brutas] para obter mais informações.

== Definição de alvos de tipo de recurso

O arquivo de metadados oferece aos usuários a capacidade de definir as regras no campo `rules`, que determina os tipos de recursos aos quais a política se aplica.
Esse recurso permite que os usuários exerçam um controle preciso sobre a aplicação da política, garantindo que as políticas sejam aplicadas somente aos tipos de recursos pretendidos.
Com esse controle refinado, os usuários podem garantir que as políticas sejam direcionadas com precisão, alinhando-se aos seus requisitos específicos e evitando qualquer aplicação não intencional de políticas a tipos de recursos não relacionados.
