include::partial$variables.adoc[]
= Rápido
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Saiba como usar o compilador Swift com suporte ao WebAssembly por meio do SwiftWasm para acessar ferramentas de criação de políticas do {project-name}.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "swift"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "políticas de escrita", "swift"]
:sidebar_label: Rápido
:sidebar_position: 50
:current-version: {page-origin-branch}

Conforme declarado no https://swift.org/[site oficial]

____
Swift é uma linguagem de programação de uso geral que é acessível para iniciantes e poderosa para especialistas.
Ele é rápido, moderno, seguro e muito agradável de escrever.
____

O compilador swift ainda não tem suporte ao WebAssembly, mas o projetohttps://swiftwasm.org/[SwiftWasm] fornece um compilador corrigido com esse recurso.

A equipe do SwiftWasm está trabalhando para mesclar essas alterações no projeto Swift.
Enquanto isso, você pode usar a cadeia de ferramentas fornecida pelo projeto SwiftWasm para criar políticas {project-name}.

[NOTE]
====

Você não precisa de um sistema Apple para escrever ou executar o código Swift. Tudo pode ser feito também em uma máquina Linux ou no Windows (usando o Docker para Windows).
====


== Estado atual

Os autores de políticas podem usar os seguintes recursos:

* https://github.com/kubewarden/policy-sdk-swift[{short-project-name} Swift SDK]: fornece um conjunto de ``estruturas``e funções que simplificam o processo de criação de políticas.
* https://github.com/kubewarden/swift-policy-template[{short-project-name} Projeto de modelo Swift]: use esse modelo para estruturar uma política baseada em Swift.
O modelo vem com uma política de trabalho e um conjunto de GitHub Actions para automatizar seu ciclo de vida.

Não há limitações graves com o Swift, apenas alguns problemas menores:

* É fundamental realizar algumas otimizações pós-compilação antes de usar a política _"em produção":_
 .. Remova o módulo Wasm por meio do site `wasm-strip` para reduzir seu tamanho
 .. Otimize o módulo Wasm por meio de `wasm-opt`

A ação do GitHub fornecida pelo repositório de modelos já cuida disso.

== Mais exemplos

https://github.com/kubewarden/pod-runtime-class-policy/tree/swift-implementation[Este ramo do repositório do GitHub]tem uma política {short-project-name} escrita em Swift.
