= Caractéristiques
:revdate: 2026-03-05
:page-revdate: {revdate}

Cette section décrit les caractéristiques et les étapes des caractéristiques sur le site {product_name}.

== Liste des caractéristiques

|===
| Fonctionnalité | Nom de l'élément de barre | Sous-fonction | Défaut | Stade 

| *Fournisseur de services complémentaires pour la flotte*
| `+addon-provider-fleet+`
| _Aucun_
| activée
| bêta

| *Mode TLS de l'agent*
| `+agent-tls-mode+`
| _Aucun_
| activée
| bêta

| *Pas de gestionnaire de certificat*
| `+no-cert-manager+`
| _Aucun_
| activée
| bêta

| *Utiliser le registre par défaut de Rancher*
| `+use-rancher-default-registry+`
| _Aucun_
| activée
| bêta

|===

=== Fournisseur de services complémentaires pour la flotte
Cette fonctionnalité installe le Cluster API Add-on Provider for Fleet (CAAPF) pour assurer l'intégration avec https://github.com/rancher/fleet[Fleet] et faciliter le déploiement d'applications sur des clusters provisionnés par CAPI. CAAPF installe automatiquement Fleet dans le cluster de gestion et enregistre les clusters CAPI nouvellement provisionnés avec Fleet, afin que les applications puissent être déployées sur ces clusters via les ressources GitOps, `+Bundle+` ou `+HelmOp+`. CAAPF prend également en charge le regroupement des clusters CAPI qui font référence à la même ClusterClass par l'intermédiaire du ClusterGroup de Fleet, ce qui simplifie considérablement les déploiements d'applications sur de grands groupes de clusters. Cette fonctionnalité est au stade de l'AG et est activée par défaut.

=== Mode TLS de l'agent
Cette porte de fonctionnalité est utilisée pour indiquer à Turtles s'il doit suivre le paramètre `+agent-tls-mode+` de Rancher lorsqu'il récupère les manifestes d'enregistrement des clusters pour l'importation de clusters. Lorsque cette option est activée, Turtles consulte la valeur du paramètre `+agent-tls-mode+` de Rancher pour déterminer s'il a été réglé sur `+system-store+` ou `+strict+`. S'il est défini sur `+system-store+`, Turtles fera confiance à tout certificat généré par une autorité de certification publique contenue dans le magasin de confiance du système d'exploitation, y compris ceux signés par des autorités telles que Let's Encrypt. S'il est défini sur `+strict+`, Turtles ne fera confiance qu'aux certificats générés par l'autorité de certification contenue dans le paramètre `+cacerts+` de Rancher. Lorsque ce paramètre est désactivé, les tortues fonctionnent en mode `+system-store+`. Cette fonctionnalité est en phase bêta et est activée par défaut.

=== Pas de gestionnaire de certificat
Ce portail de fonctionnalités convertit les manifestes des fournisseurs CAPI afin de remplacer l'utilisation de cert-manager par https://github.com/rancher/wrangler/[wrangler].

En particulier, les webhooks de validation et de mutation d'admission seront mis à jour pour utiliser les certificats générés par wrangler, au lieu de cert-manager, ce qui permettra d'avoir un environnement sans cert-manager.

Attention, l'utilisation de la Rancher `+CATTLE_SYNC_ONLY_CHANGED_OBJECTS+` https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/best-practices/tuning-rancher-at-scale.html#_reducing_event_handler_executions[fonctionnalité] peut empêcher le renouvellement des certificats après le délai d'expiration par défaut d'un an.

Il est possible de désactiver cette fonctionnalité afin de restaurer tous les manifestes de fournisseurs en fonction de l'utilisation originale du gestionnaire de certificats.

=== Utiliser le registre par défaut de Rancher

Ce portail de fonctionnalités indique à {product_name} d'exploiter le paramètre de gestion `+system-default-registry+` de Rancher lors de la construction de références d'images pour les composants du fournisseur CAPI. Lorsqu'il est activé, {product_name} lit ce paramètre et, si un registre est configuré, réécrit le référentiel pour chaque image de fournisseur afin d'utiliser ce registre.
Si le paramètre est vide, {product_name} revient aux références d'image par défaut. Les remplacements d'images définis dans la ressource `+ClusterctlConfig+` sont toujours prioritaires. Pour plus de détails sur l'utilisation dans les environnements à air comprimé, voir xref:operator/airgapped.adoc[Environnement à air comprimé.] Cette fonctionnalité est en phase alpha et est activée par défaut.

== Étapes du projet

{product_name} suit le processus Kubernetes https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages[des étapes des fonctionnalités de]. Une caractéristique peut se trouver à l'un des stades suivants : Alpha, Beta ou disponibilité générale (GA).

=== Stade Alpha
- Désactivé par défaut.
- Peut être bogué et ne pas bénéficier d'un soutien à long terme.
- L'API peut être modifiée sans préavis.
- Recommandé uniquement pour les groupes de tests de courte durée.

=== Phase bêta
- Toujours activé par défaut.
- Bien testé et considéré comme sûr.
- Le support est stable, mais le schéma peut changer dans les versions futures.
- Recommandé pour les utilisations non critiques pour l'entreprise en raison des changements incompatibles potentiels.

[NOTE]
====
N'hésitez pas à nous faire part de vos commentaires sur les fonctionnalités des versions Alpha et Beta !
====

=== Phase de disponibilité générale (GA)
- Toujours activé, ne peut être désactivé.
- Aucun portillon n'est nécessaire.
- Stable, avec un soutien à long terme dans les versions futures.