= Glossaire
:revdate: 2025-11-14
:page-revdate: {revdate}

== Table des matières

[cols=14*]
|===
| xref:./glossary.adoc#_a[A]
| xref:./glossary.adoc#_b[B]
| xref:./glossary.adoc#_c[C]
| xref:./glossary.adoc#_f[F]
| xref:./glossary.adoc#_i[I]
| xref:./glossary.adoc#_k[K]
| xref:./glossary.adoc#_m[M]
| xref:./glossary.adoc#_n[N]
| xref:./glossary.adoc#_o[O]
| xref:./glossary.adoc#_p[P]
| xref:./glossary.adoc#_r[R]
| xref:./glossary.adoc#_s[S]
| xref:./glossary.adoc#_t[T]
| xref:./glossary.adoc#_w[W]
|===

== A

=== Compléments

Les services au-delà des composants fondamentaux nécessaires au déploiement d'un cluster conforme à Kubernetes et classés en deux catégories :

* *Compléments de base*: Addons nécessaires au déploiement d'un cluster conforme à Kubernetes : DNS, kube-proxy, CNI.
* *Autres compléments*: Les modules complémentaires qui ne sont pas nécessaires pour un cluster conforme à Kubernetes (par exemple, metrics/Heapster, Dashboard).

=== Environnement aéré

Mise en place et fonctionnement de clusters Kubernetes sans accès direct à internet.

== B

=== Bootstrap

Le processus de transformation d'un serveur en nœud Kubernetes. Il peut s'agir de rassembler les données à fournir lors de la création du serveur qui soutient la machine, ainsi que de la configuration du logiciel fonctionnant sur ce serveur.

=== Cluster Bootstrap

Un cluster temporaire utilisé pour provisionner un cluster de gestion des cibles.

=== Fournisseur Bootstrap

Désigne un <<_provider,fournisseur>> qui met en œuvre une solution pour le processus d'<<_bootstrap,amorçage>>.

== C

=== CAPI

API de la grappe de base

=== CAPA

Fournisseur d'API de cluster AWS

=== CAPD

Cluster API Provider Docker

=== CAPG

Cluster API Google Cloud Provider

=== CAPIO

Opérateur API pour les clusters

=== CAPRKE2

Fournisseur d'API de cluster RKE2. Pour des informations détaillées sur CAPRKE2, consultez sa documentation https://caprke2.docs.rancher.com[ici.]

=== CAPV

Fournisseur d'API de cluster vSphere

=== CAPZ

Fournisseur d'API de cluster Azure

=== Fournisseur CAPI

Une API publique qui facilite le provisionnement et les opérations sur les ressources <<_cluster_api_operator,CAPI Operator>> et <<_cluster_api,Cluster API>>.

=== Groupe d'enfants

Terme couramment utilisé de manière interchangeable avec le <<_workload_cluster,cluster de charge de travail>>.

=== Groupement d'entreprises

Un déploiement complet de Kubernetes. Voir Management Cluster et Workload Cluster.

=== ClusterClass

Une collection de modèles qui définissent une topologie (plan de contrôle et travailleurs) à utiliser pour réconcilier en continu un ou plusieurs clusters.
Voir xref:../user/clusterclass.adoc[ClusterClass]

=== API pour les clusters

Ou *projet Cluster API*

L'API Cluster est un sous-projet du SIG-cluster-lifecycle. Il est également utilisé pour désigner les composants logiciels, les API et la communauté qui les produit.

Voir <<_core_provider,fournisseur principal>>

=== Opérateur API pour les clusters

Ou *projet Cluster API Operator*

Le Cluster API Operator est un sous-projet du SIG-cluster-lifecycle. Il est conçu pour permettre aux administrateurs de clusters de gérer le cycle de vie des fournisseurs d'API de clusters au sein d'un cluster de gestion à l'aide d'une approche déclarative.

=== Fournisseur d'API pour les clusters RKE2

<<_caprke2,Cluster API Provider RKE2>> est une combinaison de deux types de fournisseurs : un Cluster API Control Plane Provider pour le provisionnement des nœuds du plan de contrôle Kubernetes et un Cluster API Bootstrap Provider pour le démarrage de Kubernetes sur une machine où <<_rke2,RKE2>> est utilisé comme distro Kubernetes.

=== Plan de contrôle

L'ensemble des services Kubernetes qui constituent la base d'un cluster. Voir aussi https://kubernetes.io/docs/concepts/#_kubernetes-control-plane Il existe deux variantes :

* *Auto-approvisionnement*: Un plan de contrôle Kubernetes composé de pods ou de machines entièrement gérés par un seul déploiement d'API de cluster.
* *Externe* ou *géré*: Un plan de contrôle offert et contrôlé par un système autre que l'API de cluster (par exemple, GKE, AKS, EKS, IKS).

=== Fournisseur du plan de contrôle

Désigne un <<_provider,fournisseur>> qui met en œuvre une solution pour la gestion d'un <<_control_plane,plan de contrôle>> Kubernetes.

Voir <<_caprke2,CAPRRKE2>>, <<_kcp,KCP>>.

=== Fournisseur principal

Désigne un <<_provider,fournisseur>> qui met en œuvre les contrôleurs de base de l'API de cluster ; si vous considérez que le premier projet qui doit être déployé dans un cluster de gestion est l'API de cluster elle-même, la raison pour laquelle le projet API de cluster est également désigné comme le fournisseur de base devrait être claire.

Voir <<_cluster_api,CAPI>>.

== F

=== La flotte

ifeval::["{build-type}" == "product"]
Un moteur de gestion et de déploiement de conteneurs conçu pour offrir aux utilisateurs plus de contrôle sur le cluster local et une surveillance constante grâce à GitOps. Consultez la https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/index.html/[documentation de] pour en savoir plus sur Fleet.
endif::[]
ifeval::["{build-type}" == "community"]
Un moteur de gestion et de déploiement de conteneurs conçu pour offrir aux utilisateurs plus de contrôle sur le cluster local et une surveillance constante grâce à GitOps. Consultez la https://fleet.rancher.io/[documentation de] pour en savoir plus sur Fleet.
endif::[]

== I

=== Fournisseur d'infrastructure

Se réfère à un <<_provider,fournisseur>> qui met en œuvre le provisionnement des ressources d'infrastructure/de calcul requises par le cluster ou par les machines (par exemple, VM, réseau, etc.).
Les fournisseurs d'infrastructure en nuage comprennent AWS, Azure ou Google, tandis que VMware, MAAS ou metal3.io peuvent être définis comme des fournisseurs d'infrastructure en nuage.

=== Fournisseur IPAM

Désigne un <<_provider,fournisseur>> qui permet à l'API Cluster d'interagir avec les solutions IPAM.
L'interaction du fournisseur IPAM avec l'API Cluster est basée sur les types d'API `+IPAddressClaim+` et `+IPAddress+`.

== K

=== Kubernetes-conformant

Ou *compatible avec Kubernetes*

Un cluster qui passe les tests de conformité de Kubernetes.

=== Opérateur Kubernetes

Un opérateur Kubernetes est une méthode de conditionnement, de déploiement et de gestion d'une application Kubernetes. Voir également https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ pour plus d'informations.

=== k/k

Renvoie au https://github.com/kubernetes/kubernetes[dépôt git principal de] ou au projet Kubernetes principal.

=== KCP

Fournisseur de plan de contrôle Kubeadm

== M

=== Machine

Ou *ressource machine*

La ressource personnalisée pour Kubernetes qui représente un composant d'infrastructure qui héberge un nœud Kubernetes.

=== Gérer un cluster

Effectuer des opérations de création, de mise à l'échelle, de mise à niveau ou de destruction sur le cluster.

=== Kubernetes géré

Managed Kubernetes fait référence à toute abstraction de provisionnement et de maintenance de cluster Kubernetes, généralement exposée sous forme d'API, qui est nativement disponible chez un fournisseur de Cloud. Par exemple : https://aws.amazon.com/eks/[EKS], https://www.oracle.com/cloud/cloud-native/container-engine-kubernetes/[OKE], https://azure.microsoft.com/en-us/products/kubernetes-service[IBM Cloud Kubernetes Service] AKS, https://cloud.google.com/kubernetes-engine[DOKS] GKE, https://www.ibm.com/cloud/kubernetes-service[], https://www.digitalocean.com/products/kubernetes[], et bien d'autres dans tout l'écosystème Kubernetes Cloud Native.

=== Topologie gérée

Voir <<_topology,Topologie>>

=== Groupe de gestion

Le cluster où un ou plusieurs fournisseurs d'infrastructure s'exécutent et où les ressources (par exemple les machines) sont stockées. On y fait généralement référence lorsqu'il s'agit de provisionner plusieurs clusters de charge de travail.

== N

=== Pools de nœuds

Un pool de nœuds est un groupe de nœuds au sein d'un cluster qui ont tous la même configuration.

== O

=== Système d'exploitation

Ou *OS*

Combinaison générique d'un noyau et d'une interface utilisateur au niveau du système, telle que Linux ou Windows, par opposition à une distribution particulière.

== P

=== Pivot

Pivot est un processus de déplacement des composants du fournisseur et des ressources cluster-api déclarées d'un cluster de gestion source vers un cluster de gestion cible.

Le processus de pivot est également utilisé pour supprimer un groupe de gestion et pourrait également être utilisé lors d'une mise à niveau du groupe de gestion.

=== Fournisseur

Ou *fournisseur d'API de cluster*

Ce terme était à l'origine l'abréviation de <<_infrastructure_provider,fournisseur d'infrastructure>>, mais il est aujourd'hui utilisé pour désigner tout projet pouvant être déployé et fournissant des fonctionnalités au cluster de gestion de l'API du cluster.

Voir <<_bootstrap_provider,Fournisseur d'amorçage>>, <<_control_plane_provider,Fournisseur de plan de contrôle>>, <<_core_provider,Fournisseur de base>>,<<_infrastructure_provider,Fournisseur d'infrastructure>>, <<_ipam_provider,Fournisseur IPAM>>, <<_runtime_extension_provider,Fournisseur d'extension d'exécution>>.

=== Composants du fournisseur

Désigne l'artefact YAML publié dans le cadre du processus de mise à disposition des <<_provider,fournisseurs>>; il comprend généralement des définitions de ressources personnalisées (CRD), des déploiements (pour exécuter le gestionnaire de contrôleurs), des RBAC, etc.

Dans certains cas, la même expression est utilisée pour désigner les instances des composants ci-dessus déployés dans un cluster de gestion.

Voir <<_provider_repository,référentiel des fournisseurs>>

=== Référentiel du fournisseur

Désigne l'emplacement où sont hébergés les YAML des <<_provider_components,composants du fournisseur>>; en général, un référentiel de fournisseurs héberge plusieurs versions des composants du fournisseur, une pour chaque version publiée.

== R

=== Rancher

Une open-source https://www.rancher.com/[plateforme] conçue pour simplifier le déploiement et la gestion des clusters Kubernetes.

=== Agent de cluster Rancher

Un composant déployé par Rancher dans chaque cluster Kubernetes qu'il gère. Son rôle principal est d'établir un canal de communication sécurisé entre le serveur Rancher et le cluster Kubernetes, permettant à Rancher de gérer et d'interagir avec le cluster.

=== Gestionnaire de l'élevage

Le Rancher Manager (ou Rancher Server) est l'endroit où l'interface utilisateur et l'API de Rancher sont hébergées, et il communique avec les clusters gérés par le biais de composants tels que le <<_rancher_cluster_agent,Rancher Cluster Agent>>. Il permet aux utilisateurs de gérer leurs clusters Kubernetes, leurs applications et les ressources spécifiques au Rancher, telles que les catalogues, les utilisateurs, les rôles globaux, et plus encore.

=== RKE2

ifeval::["{build-type}" == "product"]
La distribution Kubernetes de nouvelle génération de Rancher, entièrement conforme, qui met l'accent sur la sécurité et la conformité aux États-Unis. Secteur du gouvernement fédéral. Voir la https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html[documentation de] pour plus de détails.
endif::[]
ifeval::["{build-type}" == "community"]
La distribution Kubernetes de nouvelle génération de Rancher, entièrement conforme, qui met l'accent sur la sécurité et la conformité aux États-Unis. Secteur du gouvernement fédéral. Voir la https://docs.rke2.io/[documentation de] pour plus de détails.
endif::[]

=== Extension du temps d'exécution

Un composant externe qui fait partie d'un système construit au-dessus de l'API de cluster et qui peut traiter des demandes pour un Runtime Hook spécifique.

=== Fournisseur de l'extension Runtime

Fait référence à un <<_provider,fournisseur>> qui met en œuvre une ou plusieurs <<_runtime_extension,extensions d'exécution>>.

== S

=== Mise à l'échelle

Sauf indication contraire, il s'agit d'une mise à l'échelle horizontale.

=== Plan de contrôle empilé

Un nœud de plan de contrôle où etcd est colocalisé avec le serveur API Kubernetes, et fonctionne comme un pod statique.

=== Serveur

L'infrastructure qui soutient une <<_machine,ressource machine>>, généralement une instance cloud, une machine virtuelle ou un hôte physique.

=== {product_name}

Un <<_kubernetes_operator,opérateur Kubernetes>> qui fournit une intégration entre Rancher Manager et Cluster API (CAPI) dans le but d'apporter un support CAPI complet à Rancher.

== T

=== Topologie

Champ de la spécification de l'objet Cluster qui permet de définir et de gérer la forme du plan de contrôle du Cluster et des machines de travail à partir d'un point de contrôle unique. La topologie du cluster est basée sur une <<_clusterclass,ClusterClass>>.
On parle aussi parfois de topologie gérée.

Voir <<_clusterclass,ClusterClass>>

ifeval::["{build-type}" == "product"]
=== Tortues

Se réfère à <<_suse_rancher_prime_cluster_api,{product_name}>>
endif::[]

ifeval::["{build-type}" == "community"]
=== Tortues

Se réfère à <<_rancher_turtles,{product_name}>>
endif::[]

== W

=== Groupement de charge de travail

Cluster créé par un contrôleur ClusterAPI, qui _n'_ est _pas_ un cluster d'amorçage et qui est destiné à être utilisé par les utilisateurs finaux, par opposition à l'outil CAPI.

=== WorkerClass

Collection de modèles définissant un ensemble de nœuds de travail dans la grappe. Une ClusterClass contient zéro ou plusieurs définitions de WorkerClass.

Voir <<_clusterclass,ClusterClass>>
