= Arquitectura
:page-languages: [en, ja, ko, zh]
:revdate: 2025-01-06
:page-revdate: {revdate}

== Servidores y agentes

* Un nodo servidor se define como un host que ejecuta el comando `+k3s server+`, con componentes de plano de control y datastore gestionados por K3s.
* Un nodo agente se define como un host que ejecuta el comando `+k3s agent+`, sin ningún componente de datastore o plano de control.
* Tanto los servidores como los agentes ejecutan el kubelet, el tiempo de ejecución del contenedor y CNI. Consulte la documentación xref:advanced.adoc#_running_agentless_servers_experimental[Opciones avanzadas] para obtener más información sobre la ejecución de servidores sin agente.

image:how-it-works-k3s-revised.svg[]

== Configuración de un solo servidor con una base de datos integrada

El siguiente diagrama muestra un ejemplo de un cluster que tiene un servidor K3s de un solo nodo con una base de datos SQLite incrustada.

En esta configuración, cada nodo agente está registrado en el mismo nodo servidor. Un usuario de K3s puede manipular los recursos de Kubernetes llamando a la API de K3s en el nodo servidor.

image:k3s-architecture-single-server.svg[Arquitectura K3s con un único servidor]

[#_high_availability_k3s]
== K3 de alta disponibilidad

Los clústeres de un solo servidor pueden satisfacer una variedad de casos de uso, pero para entornos en los que el tiempo de actividad del plano de control de Kubernetes es crítico, puede ejecutar K3 en una configuración de HA. Un clúster HA K3s se compone de:

[tabs]
======
BD integrada::
+
--
* Tres o más *nodos de servidor* que servirán a la API de Kubernetes y ejecutarán otros servicios del plano de control.
* Un *almacén de datos etcd incrustado* (a diferencia del almacén de datos SQLite incrustado que se utiliza en las configuraciones de servidor único).

image:k3s-architecture-ha-embedded.svg[Arquitectura K3s con servidores de alta disponibilidad]
--

BD externa::
+
--
* Dos o más *nodos de servidor* que servirán a la API de Kubernetes y ejecutarán otros servicios del plano de control.
* Un *almacén de datos externo* (como MySQL, PostgreSQL o etcd)

image:k3s-architecture-ha-external.svg[Arquitectura K3s con servidores de alta disponibilidad y una base de datos externa]
--
======

== Dirección de registro fija para los nodos agentes

En la configuración de servidor de alta disponibilidad, cada nodo también puede registrarse en la API de Kubernetes utilizando una dirección de registro fija, como se muestra en el diagrama siguiente.

Tras el registro, los nodos agentes establecen una conexión directa con uno de los nodos servidores.

image:k3s-production-setup.svg[Registro de agentes HA]

[#_how_agent_node_registration_works]
== Cómo funciona el registro de nodo agente

Los nodos del agente se registran con una conexión websocket iniciada por el proceso `+k3s agent+`, y la conexión es mantenida por un equilibrador de carga del lado del cliente que se ejecuta como parte del proceso del agente. Inicialmente, el agente se conecta al supervisor (y kube-apiserver) a través del balanceador de carga local en el puerto 6443. El equilibrador de carga mantiene una lista de puntos finales disponibles a los que conectarse. El punto final por defecto (y el único inicialmente) es sembrado por el nombre de host de la dirección `+--server+`. Una vez que se conecta al clúster, el agente recupera una lista de direcciones kube-apiserver de la lista de puntos finales del servicio Kubernetes en el espacio de nombres predeterminado. Esos puntos finales se añaden al equilibrador de carga, que luego mantiene conexiones estables con todos los servidores del clúster, proporcionando una conexión al kube-apiserver que tolera las interrupciones de los servidores individuales.

Los agentes se registrarán en el servidor utilizando el secreto de clúster del nodo junto con una contraseña generada aleatoriamente para el nodo, almacenada en `+/etc/rancher/node/password+`. El servidor almacenará las contraseñas de los nodos individuales como secretos de Kubernetes, y cualquier intento posterior deberá utilizar la misma contraseña. Los secretos de contraseña de nodo se almacenan en el espacio de nombres `+kube-system+` con nombres que utilizan la plantilla `+<host>.node-password.k3s+`. Esto se hace para proteger la integridad de los ID de los nodos.

Si se elimina el directorio `+/etc/rancher/node+` de un agente, o se desea reincorporar un nodo utilizando un nombre existente, el nodo debe eliminarse del clúster. Esto limpiará tanto la antigua entrada del nodo, como la contraseña secreta del nodo, y permitirá al nodo (re)unirse al cluster.

Si reutiliza con frecuencia los nombres de host, pero no puede eliminar los secretos de contraseña de nodo, se puede añadir automáticamente un ID de nodo único al nombre de host iniciando los servidores o agentes K3s utilizando el indicador `+--with-node-id+`. Cuando está activado, el ID del nodo también se almacena en `+/etc/rancher/node/+`.
