= PREGUNTAS FRECUENTES
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

Las FAQ se actualizan periódicamente y están diseñadas para responder a las preguntas más frecuentes de nuestros usuarios sobre los K3.

== ¿Es K3s un sustituto adecuado de Kubernetes?

K3s es una distribución de Kubernetes certificada por CNCF, y puede hacer todo lo que se requiere de un clúster Kubernetes estándar. Es sólo una versión más ligera. Consulte la página xref:introduction.adoc[principal] de documentación para obtener más información.

== ¿Cómo puedo utilizar mi propio Ingress en lugar de Traefik?

Simplemente inicie el servidor K3s con `+--disable=traefik+` y despliegue su ingress.

== ¿Es compatible el K3s con Windows?

En este momento K3s no soporta Windows de forma nativa, sin embargo estamos abiertos a la idea en el futuro.

== ¿Qué son exactamente los servidores y los agentes?

Para un desglose de los componentes que forman un servidor y un agente, consulte la xref:architecture.adoc[página Arquitectura].

== ¿Cómo puedo construir a partir del código fuente?

Por favor, consulte el K3s https://github.com/k3s-io/k3s/blob/main/BUILDING.md[BUILDING.md] con instrucciones.

== ¿Dónde están los registros de los K3?

La ubicación de los registros de K3s variará en función de cómo ejecute K3s y del SO del nodo.

* Cuando se ejecuta desde la línea de comandos, los registros se envían a stdout y stderr.
* Cuando se ejecuta bajo openrc, los registros se crearán en `+/var/log/k3s.log+`.
* Cuando se ejecuta bajo Systemd, los registros se enviarán a Journald y se pueden ver utilizando `+journalctl -u k3s+`.
* Los registros de vainas pueden consultarse en `+/var/log/pods+`.
* Los registros de Containerd pueden consultarse en `+/var/lib/rancher/k3s/agent/containerd/containerd.log+`.

Puede generar registros más detallados utilizando el indicador `+--debug+` al iniciar K3s (o `+debug: true+` en el archivo de configuración).

Kubernetes utiliza un marco de registro conocido como `+klog+`, que utiliza una única configuración de registro para todos los componentes dentro de un proceso.
Dado que K3s ejecuta todos los componentes de Kubernetes dentro de un único proceso, no es posible configurar diferentes niveles de registro o destinos para componentes individuales de Kubernetes.
El uso de los argumentos de los componentes `+-v=<level>+` o `+--vmodule=<module>=<level>+` probablemente no tendrá el efecto deseado.

Consulte xref:advanced.adoc#_additional_logging_sources[Fuentes de registro adicionales] para conocer aún más opciones de registro.

== ¿Puedo ejecutar K3s en Docker?

Sí, hay múltiples maneras de ejecutar K3s en Docker. Consulte xref:advanced.adoc#_running_k3s_in_docker[Opciones avanzadas] para obtener más información.

== ¿Cuál es la diferencia entre K3s Server y Agent Tokens?

Para obtener más información sobre la gestión de las fichas de unión de K3s, consulte la xref:cli/token.adoc[documentación del comando`+k3s token+` ].

== ¿Cuál es la compatibilidad entre las distintas versiones del K3?

En general, se aplica la Kubernetes https://kubernetes.io/docs/setup/release/version-skew-policy/[política de desviación de versiones de].

En resumen, los servidores pueden ser más nuevos que los agentes, pero los agentes no pueden ser más nuevos que los servidores.

== Tengo un problema, ¿dónde puedo obtener ayuda?

Si tiene problemas con el despliegue de los K3, debería hacerlo:

. Consulta la página de xref:known-issues.adoc[problemas conocidos].
. Compruebe que ha resuelto cualquier xref:installation/requirements.adoc#_operating_systems[Preparación adicional del sistema operativo]. Ejecute `+k3s check-config+` y asegúrese de que pasa.
. Busque en la K3s https://github.com/k3s-io/k3s/issues[página] and https://github.com/k3s-io/k3s/discussions[Issues] uno que coincida con su problema.
. Únete al canal K3s de https://slack.rancher.io/[Slack] para obtener ayuda.
. Envíe un https://github.com/k3s-io/k3s/issues/new/choose[New Issue] en el Github de K3s describiendo su configuración y el problema que está experimentando.
