= agent k3s
:page-languages: [en, ja, ko, zh]
:revdate: 2025-01-15
:page-revdate: {revdate}

Dans cette section, vous apprendrez à configurer l'agent K3s.

Notez que les serveurs exécutent également un agent, de sorte que tous les drapeaux énumérés sur cette page sont également valables pour une utilisation sur les serveurs.

Les options sont documentées sur cette page comme des drapeaux CLI, mais peuvent également être transmises en tant qu'options de fichier de configuration. Voir la documentation sur les xref:installation/configuration.adoc#_configuration_file[fichiers de configuration] pour plus d'informations sur l'utilisation des fichiers de configuration YAML.

== Enregistrement

|===
| Drapeau | Défaut | Description

| `+-v+` valeur
| 0
| Nombre pour la verbosité du niveau du journal

| `+--vmodule+` valeur
| N/A
| Liste de paramètres FILE_PATTERN=LOG_LEVEL, séparés par des virgules, pour la journalisation avec filtrage des fichiers.

| `+--log value, -l+` valeur
| N/A
| Enregistrer dans un fichier

| `+--alsologtostderr+`
| N/A
| Journaliser l'erreur standard ainsi que le fichier (si défini)
|===

== Options de la grappe

|===
| Drapeau | Variable d'environnement | Description

| `+--token value, -t+` valeur
| `+K3S_TOKEN+`
| Jeton à utiliser pour l'authentification

| `+--token-file+` valeur
| `+K3S_TOKEN_FILE+`
| Fichier de jetons à utiliser pour l'authentification

| `+--server value, -s+` valeur
| `+K3S_URL+`
| Serveur auquel se connecter
|===

== Auditeur

|===
| Drapeau |  Défaut | Description
| `+--bind-address+`
| 0.0.0.0
| k3s bind address
|===

== Données

|===
| Drapeau | Défaut | Description

| `+--data-dir value, -d+` valeur
| "/var/lib/rancher/k3s"
| Dossier pour maintenir l'état
|===

== Nœud

|===
| Drapeau | Variable d'environnement | Description

| `+--node-name+` valeur
| `+K3S_NODE_NAME+`
| Nom du nœud

| `+--with-node-id+`
| N/A
| Ajouter l'identifiant au nom du nœud

| `+--node-label+` valeur
| N/A
| Enregistrement et démarrage d'un kubelet avec un ensemble d'étiquettes

| `+--node-taint+` valeur
| N/A
| Enregistrement d'un kubelet avec un ensemble de taches

| `+--protect-kernel-defaults+`
| N/A
| Comportement de réglage du noyau. Si défini, erreur si les paramètres du noyau sont différents des valeurs par défaut des kubelets.

| `+--selinux+`
| `+K3S_SELINUX+`
| Activer SELinux dans containerd

| `+--lb-server-port+` valeur
| `+K3S_LB_SERVER_PORT+`
| Port local de l'équilibreur de charge du client superviseur. Si le superviseur et l'apiserver ne sont pas colocalisés, un port supplémentaire 1 de moins que ce port sera également utilisé pour l'équilibreur de charge client de l'apiserver. (par défaut : 6444)
|===

== Temps d'exécution

|===
| Drapeau | Défaut | Description

| `+--container-runtime-endpoint+`
| N/A
| Désactive le containerd intégré et utilise le socket CRI au chemin donné ; lorsqu'il est utilisé avec --docker, il définit le chemin du socket docker.

| `+--default-runtime+`
| N/A
| Définir la durée d'exécution par défaut dans containerd

| `+--image-service-endpoint+`
| N/A
| Désactive le service d'image intégré à containerd et utilise le socket du service d'image distant au chemin donné. Si elle n'est pas spécifiée, la valeur par défaut est --container-runtime-endpoint.

| `+--pause-image+` valeur
| "docker.io/rancher/pause:3.1"
| Image de pause personnalisée pour containerd ou docker sandbox

| `+--private-registry+` valeur
| "/etc/rancher/k3s/registries.yaml"
| Fichier de configuration du registre privé
|===

== Mise en réseau

|===
| Drapeau | Variable d'environnement | Description

| `+--node-ip value, -i+` valeur
| N/A
| Adresse IP à annoncer pour le nœud

| `+--node-external-ip+` valeur
| N/A
| Adresse IP externe à annoncer pour le nœud

| `+--node-internal-dns+`
| N/A
| adresses DNS internes à annoncer pour le nœud

| `+--node-external-dns+`
| N/A
| adresses DNS externes à annoncer pour le nœud

| `+--resolv-conf+` valeur
| `+K3S_RESOLV_CONF+`
| Fichier resolv.conf de Kubelet

| `+--flannel-iface+` valeur
| N/A
| Remplacer l'interface de canal par défaut

| `+--flannel-conf+` valeur
| N/A
| Remplacer le fichier de configuration par défaut du canal

| `+--flannel-cni-conf+` valeur
| N/A
| Remplacer le fichier de configuration par défaut de l'interface utilisateur
|===

== Drapeaux personnalisés

|===
| Drapeau | Description

| `+--kubelet-arg+` valeur
| Drapeau personnalisé pour le processus kubelet

| `+--kube-proxy-arg+` valeur
| Drapeau personnalisé pour le processus kube-proxy
|===

== Expérimental

|===
| Drapeau | Description

| `+--rootless+`
| Courir sans racines

| `+--docker+`
| Utiliser cri-dockerd au lieu de containerd

| `+--enable-pprof+`
| Activer le point de terminaison pprof sur le port du superviseur

| `+--prefer-bundled-bin+`
| Préférer les binaires de l'espace utilisateur regroupés aux binaires de l'hôte

| `+--disable-default-registry-endpoint+`
| Voir "xref:installation/private-registry.adoc#_default_endpoint_fallback[Retrait du point de terminaison par défaut]"

| `+--vpn-auth+`
| Voir "xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental[Intégration avec le fournisseur VPN Tailscale]" 

| `+--vpn-auth-file+`
| Voir "xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental[Intégration avec le fournisseur VPN Tailscale]"
|===

== Déclassé

|===
| Drapeau | Variable d'environnement | Description

| `+--no-flannel+`
| N/A
| Utilisation `+--flannel-backend=none+`

| `+--cluster-secret+` valeur
| `+K3S_CLUSTER_SECRET+`
| Utilisation `+--token+`
|===

[#_node_labels_and_taints_for_agents]
== Étiquettes de nœuds et plaintes pour les agents

Les agents K3s peuvent être configurés avec les options `+--node-label+` et `+--node-taint+` qui ajoutent une étiquette et une taint au kubelet. Les deux options n'ajoutent des étiquettes et/ou des taches qu'au moment de l'enregistrement, de sorte qu'elles ne peuvent être ajoutées qu'une seule fois et ne peuvent plus être modifiées par la suite en exécutant les commandes K3.

L'exemple ci-dessous montre comment ajouter des étiquettes et une tare :

[,bash]
----
     --node-label foo=bar \
     --node-label hello=world \
     --node-taint key1=value1:NoExecute
----

Si vous souhaitez modifier les étiquettes de nœuds et les taches après l'enregistrement du nœud, vous devez utiliser `+kubectl+`. Reportez-vous à la documentation officielle de Kubernetes pour plus de détails sur l'ajout de https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[node labels.] taints et https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#add-a-label-to-a-node[]

== Aide CLI K3s Agent

____
Si une option apparaît entre parenthèses ci-dessous, par exemple `+[$K3S_URL]+`, cela signifie que l'option peut être transmise sous la forme d'une variable d'environnement portant ce nom.
____

[,bash]
----
NAME:
   k3s agent - Run node agent

USAGE:
   k3s agent [OPTIONS]

OPTIONS:
   --config FILE, -c FILE                     (config) Load configuration from FILE (default: "/etc/rancher/k3s/config.yaml") [$K3S_CONFIG_FILE]
   --debug                                    (logging) Turn on debug logs [$K3S_DEBUG]
   -v value                                   (logging) Number for the log level verbosity (default: 0)
   --vmodule value                            (logging) Comma-separated list of FILE_PATTERN=LOG_LEVEL settings for file-filtered logging
   --log value, -l value                      (logging) Log to file
   --alsologtostderr                          (logging) Log to standard error as well as file (if set)
   --token value, -t value                    (cluster) Token to use for authentication [$K3S_TOKEN]
   --token-file value                         (cluster) Token file to use for authentication [$K3S_TOKEN_FILE]
   --server value, -s value                   (cluster) Server to connect to [$K3S_URL]
   --data-dir value, -d value                 (agent/data) Folder to hold state (default: "/var/lib/rancher/k3s") [$K3S_DATA_DIR]
   --node-name value                          (agent/node) Node name [$K3S_NODE_NAME]
   --with-node-id                             (agent/node) Append id to node name
   --node-label value                         (agent/node) Registering and starting kubelet with set of labels
   --node-taint value                         (agent/node) Registering kubelet with set of taints
   --image-credential-provider-bin-dir value  (agent/node) The path to the directory where credential provider plugin binaries are located (default: "/var/lib/rancher/credentialprovider/bin")
   --image-credential-provider-config value   (agent/node) The path to the credential provider plugin config file (default: "/var/lib/rancher/credentialprovider/config.yaml")
   --selinux                                  (agent/node) Enable SELinux in containerd [$K3S_SELINUX]
   --lb-server-port value                     (agent/node) Local port for supervisor client load-balancer. If the supervisor and apiserver are not colocated an additional port 1 less than this port will also be used for the apiserver client load-balancer. (default: 6444) [$K3S_LB_SERVER_PORT]
   --protect-kernel-defaults                  (agent/node) Kernel tuning behavior. If set, error if kernel tunables are different than kubelet defaults.
   --container-runtime-endpoint value         (agent/runtime) Disable embedded containerd and use the CRI socket at the given path; when used with --docker this sets the docker socket path
   --default-runtime value                    (agent/runtime) Set the default runtime in containerd
   --image-service-endpoint value             (agent/runtime) Disable embedded containerd image service and use remote image service socket at the given path. If not specified, defaults to --container-runtime-endpoint.
   --pause-image value                        (agent/runtime) Customized pause image for containerd or docker sandbox (default: "rancher/mirrored-pause:3.6")
   --snapshotter value                        (agent/runtime) Override default containerd snapshotter (default: "overlayfs")
   --private-registry value                   (agent/runtime) Private registry configuration file (default: "/etc/rancher/k3s/registries.yaml")
   --disable-default-registry-endpoint        (agent/containerd) Disables containerd fallback default registry endpoint when a mirror is configured for that registry
   --nonroot-devices                          (agent/containerd) Allows non-root pods to access devices by setting device_ownership_from_security_context=true in the containerd CRI config
   --node-ip value, -i value                  (agent/networking) IPv4/IPv6 addresses to advertise for node
   --bind-address value                       (listener) k3s bind address (default: 0.0.0.0)
   --node-external-ip value                   (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
   --node-internal-dns value                  (agent/networking) internal DNS addresses to advertise for node
   --node-external-dns value                  (agent/networking) external DNS addresses to advertise for node
   --resolv-conf value                        (agent/networking) Kubelet resolv.conf file [$K3S_RESOLV_CONF]
   --flannel-iface value                      (agent/networking) Override default flannel interface
   --flannel-conf value                       (agent/networking) Override default flannel config file
   --flannel-cni-conf value                   (agent/networking) Override default flannel cni config file
   --kubelet-arg value                        (agent/flags) Customized flag for kubelet process
   --kube-proxy-arg value                     (agent/flags) Customized flag for kube-proxy process
   --enable-pprof                             (experimental) Enable pprof endpoint on supervisor port
   --rootless                                 (experimental) Run rootless
   --prefer-bundled-bin                       (experimental) Prefer bundled userspace binaries over host binaries
   --docker                                   (agent/runtime) (experimental) Use cri-dockerd instead of containerd
   --vpn-auth value                           (agent/networking) (experimental) Credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH]
   --vpn-auth-file value                      (agent/networking) (experimental) File containing credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH_FILE]
   --disable-apiserver-lb                     (agent/networking) (experimental) Disable the agent client-side load-balancer and connect directly to the configured server address
----
