= Compatibilidad con el protocolo abierto de telemetría de SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

SUSE Observability admite 2 versiones del protocolo OTLP, la versión `+grpc+` (también denominada OTLP) y `+http/protobuf+` (también denominada OTLP sobre HTTP). En la configuración del recopilador puede elegir qué exportador utilizar, pero asegúrese de configurar la URL correcta para SUSE Observability. Se prefiere la versión `+grpc+` del protocolo, que permite cargas útiles más grandes y un mayor rendimiento. Pero en caso de que su infraestructura no soporte `+grpc+`, puede cambiar a la versión HTTP. Véase también la xref:/setup/otel/troubleshooting.adoc#_some_proxies_and_firewalls_dont_work_well_with_grpc[resolución de problemas]

== SUSE Cloud Observability

Los puntos finales de SUSE Cloud Observability son:

* OTLP: `+otlp-<your-suse-observability>.app.stackstate.io:443+` (sin el esquema URL)
* OTLP sobre HTTP: `+https://otlp-http-<your-suse-observability>.app.stackstate.io+` (con el esquema URL: `+https+`)

== SUSE Observability autoalojado

Para una instalación autoalojada, debe habilitar uno de los puntos finales, o ambos, configurando la entrada para SUSE Observability como xref:/setup/install-stackstate/kubernetes_openshift/ingress.adoc#_configure_ingress_rule_for_open_telemetry[se describe aquí].

Cuando SUSE Observability se ejecuta en el mismo clúster que el recopilador, también puede utilizarlo sin entrada mediante los puntos finales de servicio; sin embargo, esto sólo es posible mediante el protocolo HTTP:

* OTLP sobre HTTP: `+http://suse-observability-otel-collector.<namespace>.svc.cluster.local:4318+`

Asegúrese de configurar `+insecure: true+` en la configuración del recopilador (consulte la sección siguiente) para permitir el uso de puntos finales http simples en lugar de https. 

El protocolo GRPC no admite el envío de credenciales a través de una conexión insegura, por lo que sólo se puede utilizar en combinación con una configuración de entrada segura.

== Configuración del colector

=== Protocolo OTLP

Los ejemplos de la configuración del recopilador utilizan el protocolo OTLP de la siguiente manera:

----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
exporters:
  otlp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp endpoint, for example otlp-suse-observability.my.company.com:443
    endpoint: <otlp-suse-observability-endpoint>
    # Optional TLS configurations:
    #tls:
    # To disable certificate verification (but still use TLS):
    #  insecure_skip_verify: true
----

=== Protocolo OTLP HTTP

Para utilizar el protocolo OTLP sobre HTTP, utilice en su lugar el exportador `+otlphttp+`. Actualice también todas las referencias de los exportadores de `+otlp/suse-observability+` a `+otlphttp/suse-observability+`. Utilice la función buscar/reemplazar para asegurarse de que cambia todas las ocurrencias.

----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
exporters:
  otlphttp/stackstate:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp-http endpoint, for example https://otlp-http-suse-observability.my.company.com:443
    endpoint: <otlp-http-suse-observability-endpoint>
    # Optional TLS configurations:
    #tls:
    # To disable TLS entirely:
    #  insecure: true
    # To disalbe certificate verification (but still use TLS):
    #  insecure_skip_verify: true
----

Hay más configuraciones disponibles para controlar los requisitos exactos y el comportamiento del exportador. Por ejemplo, también es posible utilizar un certificado raíz CA personalizado o habilitar certificados de cliente. Para más detalles, consulte https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md[la documentación del exportador OTLP en].
