= Primeros pasos con Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

image::otel/open-telemetry.svg[Open Telemetry collector y 2 aplicaciones instrumentadas que envían métricas y trazas a SUSE Observability]

SUSE Observability es compatible con https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry es un conjunto de protocolos estandarizados y un marco de código abierto para recopilar, transformar y enviar datos de telemetría como trazas, métricas y registros. La telemetría abierta admite una amplia variedad de lenguajes de programación y plataformas.

SUSE Observability es compatible tanto con métricas como con trazas. Cuando se utiliza en combinación con el stackpack de Kubernetes, los pods de Kubernetes se enriquecerán con trazas cuando estén disponibles. Al instalar el paquete de Telemetría Abierta, las nuevas páginas de resumen para servicios e instancias de servicio están disponibles, proporcionando acceso a trazas y métricas de alcance. Las métricas de Open Telemetry pueden utilizarse en monitores y enlaces métricos. El stackpack viene con bindings métricos para métricas span y métricas de memoria .NET y JVM. También hay monitores listos para usar para las tasas de error de tramo y la duración.

La configuración recomendada para el uso con SUSE Observability es instrumentar las aplicaciones con xref:/setup/otel/instrumentation/README.adoc[los SDK de] telemetría abierta aplicables e instalar el xref:/setup/otel/collector.adoc[recopilador de telemetría abierta] cerca de las aplicaciones instrumentadas para preprocesar los datos (enriquecer con etiquetas Kubernetes, muestreo de trazas, etc.) y enviar los datos a SUSE Observability. El Open Telemetry Collector también puede utilizarse para recopilar métricas de muchos tipos de fuentes de telemetría sin instrumentar las aplicaciones utilizando los SDK. Consulte https://opentelemetry.io/ecosystem/registry/?language=collector[las integraciones del recopilador Open Telemetry en] para obtener más detalles y saber si su base de datos o protocolo de telemetría es compatible.

Siga la guía de xref:/setup/otel/getting-started/README.adoc[inicio] para configurar todo de forma que funcione mejor con SUSE Observability.

== Referencias

* https://opentelemetry.io/docs/collector/[Abrir el colector de telemetría] en la documentación de Open Telemetry
* https://opentelemetry.io/ecosystem/registry/?language=collector[Integraciones de colectores abiertos de telemetría]
* https://opentelemetry.io/docs/instrumentation/README.md[SDK para instrumentar su aplicación] en la documentación de Open Telemetry
