include::partial$variables.adoc[]
= Definição de configurações de política
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Modifique o código no arquivo settings.go para definir as configurações de política, incluindo a implementação de funções personalizadas para combinar e cancelar a combinação de expressões regulares.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "go", "defining-policy-settings"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "definir configurações de política", "Go"].
:sidebar_label: Definição de configurações de política
:sidebar_position: 24
:current-version: {page-origin-branch}

Em primeiro lugar, você precisa definir a estrutura que contém as configurações de política.

Para isso, modifique o código no arquivo `+settings.go+` (da sua versão local do modelo de política do Go).
É necessário adicionar duas linhas extras à seção `+import+`, alterar a estrutura `+Settings+` e adicionar a estrutura `+RegularExpression+`.

Ele deve corresponder ao código a seguir:

[,go]
----
import (
    "encoding/json"
    "fmt"
    "regexp"

    mapset "github.com/deckarep/golang-set/v2"
    kubewarden "github.com/kubewarden/policy-sdk-go"
    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
)

type Settings struct {
    DeniedLabels      mapset.Set[string]            `+json:"denied_labels"+`
    ConstrainedLabels map[string]*RegularExpression `+json:"constrained_labels"+`
}

type RegularExpression struct {
    *regexp.Regexp
}
----

[NOTE]
====
`+DeniedNames+` não é mais necessário na estrutura `+Settings+` definida em `+settings.go+`.

Como `+DeniedNames+` não está mais definido, você também deve excluir a função `+IsNameDefined+` em `+settings.go+`.
Você também deve remover a função que faz referência a ela em `+settings_test.go+`, `+TestIsNameDenied+`.
====


Você está usando o pacote `+regexp+` para manipular objetos de expressão regular e o tipohttps://github.com/deckarep/golang-set[`+mapset.Set+`] para armazenar a lista de rótulos negados.

Como o site `+regexp.Regexp+` não lida com a desserialização, você precisa definir funções personalizadas para lidar com o empacotamento e o desempacotamento de expressões regulares:

[,go]
----
// UnmarshalText satisfies the encoding.TextMarshaler interface,
// also used by json.Unmarshal.
func (r *RegularExpression) UnmarshalText(text []byte) error {
    nativeRegExp, err := regexp.Compile(string(text))
    if err != nil {
        return err
    }
    r.Regexp = nativeRegExp
    return nil
}

// MarshalText satisfies the encoding.TextMarshaler interface,
// also used by json.Marshal.
func (r *RegularExpression) MarshalText() ([]byte, error) {
    if r.Regexp != nil {
        return []byte(r.Regexp.String()), nil
    }

    return nil, nil
}
----

Além disso, você precisa do método `+UnmarshalJSON+` para lidar com a desserialização da estrutura `+Settings+`:

[,go]
----
func (s *Settings) UnmarshalJSON(data []byte) error {
    rawSettings := struct {
        DeniedLabels      []string          `+json:"denied_labels"+`
        ConstrainedLabels map[string]*RegularExpression `+json:"constrained_labels"+`
    }{}

    err := json.Unmarshal(data, &rawSettings)
    if err != nil {
        return err
    }

    s.DeniedLabels = mapset.NewThreadUnsafeSet[string](rawSettings.DeniedLabels...)
    s.ConstrainedLabels = rawSettings.ConstrainedLabels

    return nil
}
----

== Criação de instâncias do `+Settings+` 

Uma política {short-project-name} expõe duas funções diferentes que recebem as configurações da política como entrada:

* `+validate+`: Use essa função quando o objeto Kubernetes exigir validação pela política.
As configurações fazem parte de um objetohttps://pkg.go.dev/github.com/kubewarden/policy-sdk-go@v0.2.1/protocol#ValidationRequest[`+ValidationRequest+`]objeto.
* `+validate_settings+`: Chame essa função quando a política for carregada pela primeira vez pelo site {short-project-name}.
A função recebe as configurações de política como entrada e verifica a validade.

Você precisa criar uma função auxiliar que crie um objeto `+Settings+` a partir da carga útil JSON:

[,go]
----
func NewSettingsFromValidationReq(validationReq *kubewarden_protocol.ValidationRequest) (Settings, error) {
    settings := Settings{}
    err := json.Unmarshal(validationReq.Settings, &settings)
    if err != nil {
        return Settings{}, err
    }

    return settings, nil
}
----

[NOTE]
====
Todos os objetos `+mapset.Set+` são criados usando ahttps://pkg.go.dev/github.com/deckarep/golang-set?utm_source=godoc#NewThreadUnsafeSet[variante].
O código do WebAssembly é executado em um único thread, portanto, não há problemas de concorrência.

O padrão WebAssembly ainda não abrange os threads.
Consulte https://github.com/WebAssembly/threads[a proposta oficial] para obter mais detalhes.
====


== Implementação da validação `+Settings+` 

Todas as políticas do site {short-project-name} precisam implementar a validação das configurações.

Para isso, adicione um método `+Valid+` às instâncias de `+Settings+`:

[,go]
----
func (s *Settings) Valid() (bool, error) {
    constrainedLabels := mapset.NewThreadUnsafeSet[string]()

    for label := range s.ConstrainedLabels {
        constrainedLabels.Add(label)
    }

    constrainedAndDenied := constrainedLabels.Intersect(s.DeniedLabels)
    if constrainedAndDenied.Cardinality() != 0 {
        return false,
            fmt.Errorf("These labels cannot be constrained and denied at the same time: %v", constrainedAndDenied)
    }

    return true, nil
}
----

O método `+Valid+` garante que nenhum rótulo "negado" também faça parte do mapa "restrito".
O uso do método `+Intersect+` fornecido por `+mapset.Set+` simplifica a verificação.

[NOTE]
====
A invocação do método `+Valid+` é feita em um objeto `+Setting+` já instanciado.
Isso significa que a validação da expressão regular fornecida pelo usuário já ocorreu no unmarshaler `+Settings+`.
====


Por fim, você precisa que a função `+validateSettings+`, fornecida pelo scaffolding, seja alterada para ter a seguinte aparência:

[,go]
----
func validateSettings(payload []byte) ([]byte, error) {
    settings := Settings{}
    err := json.Unmarshal(payload, &settings)
    if err != nil {
        return kubewarden.RejectSettings(
            kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
    }

    valid, err := settings.Valid()
    if valid {
        return kubewarden.AcceptSettings()
    }

    return kubewarden.RejectSettings(
        kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
}
----

Você pode ver que a função tira proveito das funções auxiliares fornecidas pelohttps://github.com/kubewarden/policy-sdk-go[SDK do]

== Teste do código de configurações

É importante ter uma boa cobertura de teste do código que você escreve.
O código que você está usando, a partir do scaffolding, vem com uma série de testes de unidade definidos no arquivo `+settings_test.go+`.

Você precisa alterar o conteúdo desse arquivo para refletir o novo comportamento da classe `+Settings+`.

Inclua os pacotes Go que você está usando:

[,go]
----
import (
    "testing"

    "encoding/json"

    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
)
----

Você pode começar escrevendo um teste de unidade que garanta que você possa atribuir uma instância de `+Settings+`a partir de um objeto `+ValidationRequest+`:

[,go]
----
func TestParseValidSettings(t *testing.T) {
    settingsJSON := []byte(`
        {
            "denied_labels": [ "foo", "bar" ],
            "constrained_labels": {
                    "cost-center": "cc-\\d+"
            }
        }`)

    settings := Settings{}
    err := json.Unmarshal(settingsJSON, &settings)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    expected_denied_labels := []string{"foo", "bar"}
    for _, exp := range expected_denied_labels {
        if !settings.DeniedLabels.Contains(exp) {
            t.Errorf("Missing value %s", exp)
        }
    }

    re, found := settings.ConstrainedLabels["cost-center"]
    if !found {
        t.Error("Didn't find the expected constrained label")
    }

    expected_regexp := `+cc-\d++`
    if re.String() != expected_regexp {
        t.Errorf("Expected regexp to be %v - got %v instead",
            expected_regexp, re.String())
    }
}
----

Em seguida, você precisa de um teste que verifique se uma instância do `+Settings+` não é gerada quando o usuário fornece uma expressão regular quebrada:

[,go]
----
func TestParseSettingsWithInvalidRegexp(t *testing.T) {
    settingsJSON := []byte(`
        {
            "denied_labels": [ "foo", "bar" ],
            "constrained_labels": {
                    "cost-center": "cc-[a+"
            }
        }`)

    err := json.Unmarshal(settingsJSON, &Settings{})
    if err == nil {
        t.Errorf("Didn't get expected error")
    }
}
----

Agora, você pode definir um teste que verifique o comportamento do ponto de entrada`+validate_settings+`.

Você olha para o objeto `+SettingsValidationResponse+` retornado por sua função `+validateSettings+`:

[,go]
----
func TestDetectValidSettings(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar" ],
        "constrained_labels": {
            "cost-center": "cc-\\d+"
        }
    }`)

    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if !response.Valid {
        t.Errorf("Expected settings to be valid: %s", *response.Message)
    }
}
----

Por fim, você escreve mais dois testes para verificar se a função `+validateSettings+` rejeita configurações inválidas com as mensagens corretas:

[,go]
----
func TestDetectNotValidSettingsDueToBrokenRegexp(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar" ],
        "constrained_labels": {
            "cost-center": "cc-[a+"
        }
    }
    `)

    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if response.Valid {
        t.Error("Expected settings to not be valid")
    }

    if *response.Message != "Provided settings are not valid: error parsing regexp: missing closing ]: `+[a++`" {
        t.Errorf("Unexpected validation error message: %s", *response.Message)
    }
}

func TestDetectNotValidSettingsDueToConflictingLabels(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar", "cost-center" ],
        "constrained_labels": {
            "cost-center": ".*"
        }
    }`)
    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if response.Valid {
        t.Error("Expected settings to not be valid")
    }

    if *response.Message != "Provided settings are not valid: These labels cannot be constrained and denied at the same time: Set{cost-center}" {
        t.Errorf("Unexpected validation error message: %s", *response.Message)
    }
}
----

Agora você pode executar os testes que definiu até agora usando o seguinte comando:

[subs="+attributes",shell]
----
go test -v settings.go settings_test.go
----

Todos os testes serão aprovados com o seguinte resultado:

[subs="+attributes",shell]
----
=== RUN   TestParseValidSettings
--- PASS: TestParseValidSettings (0.00s)
=== RUN   TestParseSettingsWithInvalidRegexp
--- PASS: TestParseSettingsWithInvalidRegexp (0.00s)
=== RUN   TestDetectValidSettings
--- PASS: TestDetectValidSettings (0.00s)
=== RUN   TestDetectNotValidSettingsDueToBrokenRegexp
--- PASS: TestDetectNotValidSettingsDueToBrokenRegexp (0.00s)
=== RUN   TestDetectNotValidSettingsDueToConflictingLabels
--- PASS: TestDetectNotValidSettingsDueToConflictingLabels (0.00s)
PASS
ok      command-line-arguments    0.002s
----

Agora você pode implementar o código de validação real na próxima seção.
