include::partial$variables.adoc[]
= Registro em log
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure a inicialização do registrador para registro estruturado em sua política usando a integração do Go SDK do projeto oneLog.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "logging"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "golang", "go", "logging"]
:current-version: {page-origin-branch}

O Go SDK se integra ao projetohttps://github.com/francoispqt/onelog[`+onelog+`]quase pronto para uso.
// TODO: Last release 2019. Still good?

O projeto escolheu essa biblioteca porque:

* Ele funciona com binários do WebAssembly.
Outras soluções de registro populares não podem compilar para o WebAssembly de destino.
* Ele oferece https://github.com/francoispqt/onelog#benchmarks[bom desempenho].
* Oferece suporte ao registro estruturado.

== Inicializar o registrador

É necessário inicializar uma estrutura de registrador.
Ao executar essa inicialização em uma variável global, é possível fazer o logon nos dois principais pontos de entrada da política: `+validate+` e`+validate_settings+`.

No pacote principal, `+main.go+`, há uma inicialização para o registrador:

[,go]
----
var (
    logWriter = kubewarden.KubewardenLogWriter{}
    logger    = onelog.New(
        &logWriter,
        onelog.ALL, // shortcut for onelog.DEBUG|onelog.INFO|onelog.WARN|onelog.ERROR|onelog.FATAL
    )
)
----

== Consumir o registrador

Agora, você pode usar o objeto `+logger+` para fazer logon de qualquer lugar que seja exigido pela sua política:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.Info("validating request")
    // ...
}
----

Você pode adicionar o registro estruturado:

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.WarnWithFields("logging something important", func(e onelog.Entry) {
        e.String("one_field", "a value")
        e.String("another_field", "another value")
    })
    // ...
}
----

Você pode consultar ahttps://pkg.go.dev/github.com/francoispqt/onelog?utm_source=godoc[documentação]

O registro de política vai para o avaliador de política (por exemplo, `+kwctl+` ou `+policy-server+`), e ele registra em nome da política.
Eles usam mecanismos que são interoperáveis com outros componentes que permitem o rastreamento distribuído, como ohttps://www.jaegertracing.io/[Jaeger].
