include::partial$variables.adoc[]
= Webhooks seguros con TLS mutuo con K3s
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Habilitar mTLS con K3s
:description: Implante protocolos de seguridad mutua de la capa de transporte (mTLS) para webhooks seguros con K3 en su distribución de SUSE Kubernetes.
:keywords: ["{project-name}", kubewarden, kubernetes, security]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: cómo
:doc-topic: manual del operador, seguridad

Esta guía muestra cómo habilitar la seguridad mutua de la capa de transporte (mTLS) para los webhooks de la pila{project-name} cuando se utiliza https://k3s.io/[] K3s como distribución de Kubernetes.

Para más información sobre cómo reforzar los webhooks, consulte laxref:/reference/security-hardening/webhooks-hardening.adoc[página de referencia].

== Requisitos previos

Antes de instalar el K3s, debe crear una autoridad de certificación (CA) y un certificado de cliente. Se utiliza para proteger la comunicación entre los webhooks de{short-project-name} y el servidor API de Kubernetes.

Como primer paso, cree el directorio `/etc/rancher/k3s/admission/certs`:

[source,console]
----
sudo mkdir -p /etc/rancher/k3s/admission/certs
----

=== Crear una CA raíz y el certificado de cliente

Como usuario de `root`, cambie al directorio `/etc/rancher/k3s/admission/certs`y cree todos los certificados necesarios:

[source,console]
----
export FQDN=mtls.kubewarden.io

# Create openssl config file
cat > openssl.cnf <<EOL
[ req ]
default_keyfile     = rootCA.key
distinguished_name  = req_distinguished_name
x509_extensions     = v3_ca
string_mask         = utf8only

[ req_distinguished_name ]
countryName         = Country Name (2 letter code)
countryName_default = US
stateOrProvinceName = State or Province Name (full name)
localityName        = Locality Name (eg, city)
organizationName    = Organization Name (eg, company)
commonName          = Common Name (eg, your domain or your CA name)

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true, pathlen:1
keyUsage = critical, keyCertSign, cRLSign
EOL

# Create CA
openssl req -nodes -batch -x509 -sha256 -days 3650 -newkey rsa:4096 -keyout rootCA.key -out rootCA.crt \
  -config openssl.cnf

# Create CSR
openssl req -nodes -batch -newkey rsa:4096 -keyout client.key -out client.csr \
    -addext "subjectAltName = DNS:$FQDN"  -config openssl.cnf

# Create CRT
openssl x509 -req -CA rootCA.crt -CAkey rootCA.key -in client.csr -out client.crt -days 3650 -CAcreateserial \
    -extfile <(echo "subjectAltName=DNS:$FQDN")

# Print CRT

openssl x509 -text -noout -in client.crt
----

Esto crea los siguientes archivos:

* `client.crt`
* `client.csr`
* `client.key`
* `rootCA.crt`
* `rootCA.key`
* `rootCA.srl`

=== Crear el archivo de configuración de Kubernetes

Cree el archivo `/etc/rancher/k3s/admission/admission.yaml` con el siguiente contenido:

[source,yaml]
----
# /etc/rancher/k3s/admission/admission.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
- name: MutatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
----

Por último, cree un archivo `kubeconfig` en `/etc/rancher/k3s/admission/kubeconfig`:

[source,yaml]
----
# /etc/rancher/admission/kubeconfig
apiVersion: v1
kind: Config
users:
- name: "*.kubewarden.svc" # namespace where the kubewarden stack is deployed
  user:
    client-certificate: /etc/rancher/k3s/admission/certs/client.crt
    client-key: /etc/rancher/k3s/admission/certs/client.key
----

=== Crear un archivo de configuración K3s

Cree un archivo de configuración K3s en `/etc/rancher/k3s/config.yaml`:

[source,yaml]
----
# /etc/rancher/k3s/config.yaml
kube-apiserver-arg:
- admission-control-config-file=/etc/rancher/k3s/admission/admission.yaml
----

== Instalar K3s

Instale K3s utilizando el siguiente comando:

[source,console]
----
curl -sfL https://get.k3s.io | sh -
----

Espere a que finalice la instalación.

== Instale la pila {short-project-name} 

=== Requisitos previos

El certificado de la CA raíz, que emitió el certificado de cliente de Kubernetes, debe estar disponible para la pila {short-project-name}.

La CA raíz está disponible en `/etc/rancher/k3s/admission/certs/rootCA.crt` en el nodo Kubernetes. Necesita su contenido en un `ConfigMap` bajo el espacio de nombres`kubewarden`. El contenido del archivo `rootCA.crt` se almacena en la clave `client-ca.crt`.

En primer lugar, cree el espacio de nombres `kubewarden`:

[source,console]
----
kubectl create namespace kubewarden
----

A continuación, cree en él la dirección `ConfigMap`. El siguiente comando, ejecutado en el nodo Kubernetes, lo hace:

[source,console]
----
kubectl create configmap -n kubewarden api-server-mtls \
    --from-file=client-ca.crt=/etc/rancher/k3s/admission/certs/rootCA.crt
----

El nombre de la `ConfigMap` resultante es `api-server-mtls`.

=== Instale la pila {short-project-name} 

Instale la pila {short-project-name} tal y como se describe en laxref:/quick-start.adoc[guía de inicio rápido]. Siga todos los pasos, pero cuando instale la carta `kubewarden-controller` Helm, asegúrese de activar los siguientes valores:

* `mTLS.enable`: debe ser `true`.
* `mTLS.configMapName`: debe el nombre del `ConfigMap` creado anteriormente .

El nombre de `ConfigMap` es `api-server-mtls`. El comando Helm para instalar el`kubewarden-controller` es:

[source,console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller \
    --set mTLS.enable=true \
    --set mTLS.configMapName=api-server-mtls
----

Una vez finalizado este comando, mTLS asegura la instalación de la pila{short-project-name} y sus webhooks.