= Konfigurieren von SUSE Observability Kubernetes Agent für Proxy-Verbindungen
:revdate: 2025-07-10
:page-revdate: {revdate}

Mit dem SUSE Observability Kubernetes Agent können Sie HTTP- oder HTTPS-Proxy-Einstellungen für die von ihm initiierten Verbindungen konfigurieren.

== Proxy für die Kommunikation mit SUSE Observability

Um den Agenten für Proxy-Verbindungen zum SUSE Observability-Backend zu konfigurieren, können Sie die Helm-Konfiguration verwenden.

=== Helm-Konfiguration

==== Über `values.yaml` Datei

. Öffnen Sie Ihre Helm Chart `values.yaml` Datei.
. Suchen Sie die Konfiguration `global.proxy.url` und geben Sie die Proxy-URL an:
+
[,yaml]
----
 global:
   proxy:
     url: "https://proxy.example.com:8080"
----

. Wenn der Proxy kein signiertes Zertifikat hat, können Sie optional die SSL-Verifizierung deaktivieren, indem Sie `global.skipSslValidation` auf `true` setzen:
+
[,yaml]
----
 global:
   skipSslValidation: true
----

==== Über Kommandozeilen-Flag

. Verwenden Sie während der Installation des Helm-Diagramms das Flag `--set`, um die Proxy-URL anzugeben:
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.proxy.url="https://proxy.example.com:8080"
----

. Um die SSL-Validierung über die Befehlszeile zu deaktivieren, verwenden Sie:
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.skipSslValidation=true
----
