= Acerca de StackPacks
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado v5.1.x

== Visión general

StackPacks amplía la funcionalidad de SUSE Observability y ofrece integración automatizada con sistemas externos. Pueden instalarse y desinstalarse fácilmente desde la página StackPacks en SUSE Observability.

Existen dos tipos de StackPack: Complementos e Integraciones. Los complementos e integraciones StackPack disponibles se pueden encontrar en la página *StackPacks* de la interfaz de usuario de SUSE Observability.

== Instalar o desinstalar un StackPack

StackPacks puede instalarse y desinstalarse desde la página *StackPacks* en SUSE Observability. Se proporcionan instrucciones completas para instalar y desinstalar el StackPack.

[NOTE]
====
*Tenga en cuenta que:*

* Un StackPack puede requerir pasos *manuales* de instalación o configuración del sistema externo. Lea atentamente las instrucciones.
* Cuando se desinstala un StackPack o una instancia de StackPack, *todos los datos recibidos a través del StackPack (instancia) se eliminarán de SUSE Observability.*
* Cualquier configuración o instalación (manual) de componentes StackPack en un sistema externo puede necesitar ser desinstalado por separado.

====


=== Instancias StackPack

Algunos StackPacks permiten conectarse a varias cuentas de un sistema externo. Cada cuenta se configura en una instancia separada del StackPack.

Por ejemplo, AWS StackPack puede conectarse a varias cuentas de AWS y combinar la información de todas ellas en SUSE Observability. Para cada cuenta, se configura una instancia independiente de SUSE Observability con la información necesaria para recibir datos de esa cuenta de AWS.

== Actualizar un StackPack

[CAUTION]
====
Cuando se actualiza un StackPack, *cualquier cambio realizado en los elementos de configuración de ese StackPack se sobrescribirá*. Para más detalles, consulte xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[los elementos de configuración bloqueados].
====


Si hay disponible una nueva versión de StackPack, se mostrará una alerta en la página de SUSE Observability UI StackPack y tendrá la opción de ver los detalles de la actualización y leer las notas de la versión. Si la nueva versión es una actualización menor de la versión actualmente instalada, también puede actualizar el StackPack desde aquí.

=== Nueva versión menor de StackPack

Para actualizar a una nueva versión menor de un StackPack, haga clic en *ACTUALIZAR AHORA* en la página StackPack de la interfaz de usuario de SUSE Observability.

Tenga en cuenta que todos los elementos de configuración de StackPack se sobrescribirán al actualizar. Para seguir utilizando cualquier cambio realizado en ellas, elija *MANTENER* la configuración existente cuando actualice el StackPack. Para más detalles, consulte xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[los elementos de configuración bloqueados].

=== Nueva versión principal de StackPack

[CAUTION]
====
Cuando se actualiza un StackPack, *cualquier cambio realizado en los elementos de configuración de ese StackPack se sobrescribirá*. Para más detalles, consulte xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[los elementos de configuración bloqueados].
====


Para actualizar a una nueva versión principal de un StackPack, xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[desinstale y vuelva a instalar] el StackPack.

[TIP]
====

Continúe utilizando los cambios realizados en los elementos de configuración personalizados de StackPack después de la actualización:

. Antes de actualizar, exporte cada elemento personalizado:
 ** Vaya a la página *Configuración* de la interfaz de usuario de SUSE Observability.
 ** Haga clic en *Exportar* en el menú *...* para cada elemento personalizado.
. Actualizar el StackPack (desinstalar y volver a instalar).
. Cambie `name` y `identifier` para cada artículo exportado:
 ** Abra el archivo de exportación en un editor de texto.
 ** Edite los campos de nivel superior `name` y `identifier`.
 ** Guarda la exportación.
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[Importe] los archivos de exportación actualizados.
. Los elementos de configuración personalizados estarán ahora disponibles en SUSE Observability y podrán copiarse en los elementos de configuración de StackPack recién instalados.

====


== Elementos de configuración bloqueados

Los StackPacks contienen información de configuración para SUSE Observability que se instala cuando se instala el StackPack (instancia). Entre otras cosas, puede tratarse de plantillas de componentes, funciones, acciones de componentes y vistas. Cuando se actualiza un StackPack, *los elementos de configuración instalados por la versión anterior del StackPack serán sobrescritos por los del StackPack más reciente.* Esto significa que cualquier cambio manual realizado en estos elementos de configuración se sobrescribirá cuando se actualice el StackPack.

Para evitar que un usuario realice cambios en los elementos de configuración instalados por un StackPack que se sobrescribirán al actualizar, estos elementos de configuración están *bloqueados* por defecto. Esto significa que están protegidos para que el usuario no pueda modificarlos y que deben *desbloquearse* explícitamente para poder cambiarlos.

[TIP]
====

Puede xref:/setup/data-management/backup_restore/configuration_backup.adoc[hacer una copia de seguridad de los elementos de configuración]. Tenga en cuenta que el estado de bloqueo de los elementos de configuración no se exportará como parte de una copia de seguridad de la configuración.
====

