include::partial$variables.adoc[]

= 使用牵引器安装气隙
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 使用 Hauler 在气隙环境中安装{project-name} 。
:keywords: ["{project-name}", kubewarden, kubernetes, air gap installation, hauler]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: 如何
:doc-topic: 操作手册、气隙、安装、运输机

本指南向您介绍如何使用link:https://docs.hauler.dev/docs/intro[Hauler] 在气隙环境中安装{project-name} 。Hauler 是一款帮助用户在气隙环境中运行工作负载的工具。它将应用程序所需的资源移至这些空气屏蔽环境中。

{short-project-name} 提供了一个清单文件，其中包含在私有环境中运行{short-project-name} 所需的所有资源。本文档将介绍如何使用它。请参阅 Hauler 文档了解更多信息。

使用运输工具清单的基本工作流程是

. 从{short-project-name} 发布页面获取
. 将运行{short-project-name} 所需的所有资源加载到本地存储中
. 将它们导出到文件中
. 将文件移入专用环境
. 将资源加载到在专用环境中运行的 Hauler 中
. 将所有内容复制到注册表中，以便在安装过程中在空气密封环境中使用

== 从舵手图发布页面下载运输船清单

从{short-project-name}link:https://github.com/kubewarden/helm-charts/releases/[ 发布页面]下载`hauler_manifest.yml` 。

将清单中定义的资源同步到 Hauler 商店：

[source,shell]
----
hauler store sync --filename hauler_manifest.yaml
----

运输器将清单中的所有资源下载到本地存储空间。这一过程只需几分钟。完成后，可以使用`hauler store info` 命令查看同步资源。

== 生成包含所有{short-project-name} 资源的压缩包文件

运行 "Hauler "命令，将之前加载到存储区的所有资源导出到文件中：

[source,shell]
----
hauler store save --filename kubewarden-resources.tar.zst
----

[NOTE]
====

{short-project-name} 容器镜像支持 x86_64 和 Arm 架构。因此，当您将资源保存到文件中时，会看到如下警告信息：

[source,shell]
----
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kyverno/policy-reporter:3.3.3]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kyverno/policy-reporter-ui:2.4.1]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/policy-server:v1.27.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/audit-scanner:v1.27.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/rancher/kuberlr-kubectl:v5.0.0]
2025-08-12 18:55:54 WRN specify an export platform to prevent potential platform mismatch on import of index [ghcr.io/kubewarden/kubewarden-controller:v1.27.0]
----

为避免出现此警告信息，可以设置`--platform` CLI 标志来定义要保存到文件中的平台架构。

====

== 将压缩包转移到隔离环境中

现在，您已经在`kubewarden-resources.tar.zst` 中获得了所有{short-project-name} 资源，请将其复制到您的气隙环境中，并加载到那里的运输器存储中：

[source,shell]
----
hauler store load --filename kubewarden-resources.tar.zst
# Check if the resources are loaded
hauler store info
----

现在，安装{short-project-name} 所需的所有资源都在隔离环境中的 Hauler 存储器中。

== 填充私人登记册

要使用 Hauler 商店中的资源，必须在内部注册表中提供这些资源。您可以使用 Hauler 命令将它们复制到您的私人注册表中。

[source,shell]
----
hauler store copy registry://localhost:5000
----

您还可以运行 Hauler 启动一个注册表，其中包含商店中的所有资源。该注册表不安全，需要调整群集配置：

[source,shell]
----
# Find IP address of your host
# hostname -I

# Update registries.yaml for k3s based cluster to allow insecure access
# mirrors:
#   "<HOST_IP>:5000":
#     endpoint:
#       - "http://<HOST_IP>:5000"
# configs:
#   "<HOST_IP>:5000":
#     tls:
#       insecure_skip_verify: true

# Configure policy-server to allow pulling policies from insecure sources
# helm install .. kubewarden-defaults .. --set policyServer.insecureSources[0]=<HOST_IP:5000>

hauler store serve registry
----

这将在`localhost:5000` 地址启动一个注册表。从这一点出发，您可以使用 Skopeo 等其他命令将{short-project-name} 使用的所有容器映像、策略模块和 Helm 图表复制到您的专用注册表中。

== 安装 {short-project-name}

现在，您的私人注册表已经具备了所需的一切，您可以安装{short-project-name}.NET Framework 3.0。与标准{short-project-name}安装的区别在于，需要将容器映像和策略中的注册表更改为私有注册表。此外，您还需要从 OCI 工具中安装 Helm 图表。

安装{short-project-name} 堆栈：

[source,shell]
----
helm install --wait -n kubewarden kubewarden-crds --create-namespace \
    oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-crds
helm install --wait -n kubewarden kubewarden-controller \
    --set "global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>" \
    oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-controller
----

[CAUTION]
====

要使用`kubewarden-controller`图表中的 PolicyReporter 子图表，您需要在空气屏蔽环境中为子图表定义其他特定值。请看下面的例子：

[source,shell]
----
helm install --wait -n kubewarden kubewarden-controller oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-controller \
    --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set auditScanner.policyReporter=true \
    --set policy-reporter.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.image.repository=kyverno/policy-reporter \
    --set policy-reporter.ui.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.ui.image.repository=kyverno/policy-reporter-ui
----

有必要定义`auditScanner.policyReporter` 和其他四个值，以启用子图表，并将注册表和存储库配置为 Policy Reporter 映像存储的位置。有关策略报告子图表值的更多信息，请参阅 \link:https://kyverno.github.io/policy-reporter-docs/getting-started/helm.html[Policy Reporter documentation]。

====

[source,shell]
----
helm install --wait -n kubewarden \
  kubewarden-defaults oci://<REGISTRY.YOURDOMAIN.COM:PORT>/hauler/kubewarden-defaults \
  --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>
----

最后，配置每个策略服务器，以便从专用注册表中获取策略。请参阅文档中的xref:/howtos/policy-servers/02-private-registry.adoc[使用私人注册表]部分。

现在在群集中创建{short-project-name} 策略。您的私人注册表中必须有相关政策。

[source,yaml]
----
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://<REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policies/pod-privileged:v0.2.2
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
  mutating: false
EOF
----

[CAUTION]
====

`PolicyServer` 资源必须使用私人注册表中的图像。
例如

[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: reserved-instance-for-tenant-a
spec:
  image: <REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policy-server:v1.3.0
  replicas:
----

====