= Instalación del entrehierro
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Esta guía le guiará a través de la instalación de K3s en un entorno de ventilación mediante un proceso de tres pasos.

[IMPORTANT]
====
Puede utilizar cualquier versión de K3s Prime que aparezca en la URL de Prime Artifacts para los activos mencionados en estos pasos. Para obtener más información sobre la URL de Prime Artifacts, consulte nuestra https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[documentación exclusiva de Prime en]. Se requiere autenticación. Utilice sus credenciales SUSE https://scc.suse.com/home[del Centro de servicios al cliente de] para iniciar sesión.
====

== Cargar imágenes

Cada método de carga de imágenes tiene requisitos diferentes y es adecuado para distintos escenarios de air-gapped. Elija el método que mejor se adapte a sus requisitos de infraestructura y seguridad.

[tabs,sync-group-id=airgap-load-images]
======
Método de registro privado::
+
--
Estos pasos asumen que ya has creado nodos en tu entorno air-gap, estás usando el containerd incluido como el tiempo de ejecución del contenedor, y tienes un registro privado compatible con OCI disponible en tu entorno.

Si aún no ha configurado un registro Docker privado, consulte la https://docs.docker.com/registry/deploying/#run-an-externally-accessible-registry[documentación oficial de].

[#_create_the_registry_yaml_and_push_images]
[pass]
<h3><a class="anchor" id="_create_the_registry_yaml_and_push_images" href="#_create_the_registry_yaml_and_push_images"></a>Crear el Registro YAML y Push Images</h3>


. Obtenga el archivo de imágenes para su arquitectura de la página https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL] para la versión de K3s que va a ejecutar.
. Utilice `+docker image load k3s-airgap-images-amd64.tar.zst+` para importar imágenes desde el archivo tar a docker.
. Utilice `+docker tag+` y `+docker push+` para reetiquetar y enviar las imágenes cargadas a su registro privado.
. Siga la guía de xref:installation/private-registry.adoc[Configuración del Registro Privado] para crear y configurar el archivo `+registries.yaml+`.
. Continúe con la sección <<_install_k3s,Instalar K3s>> a continuación.
--

Método de despliegue manual de imágenes::
+
--
Estos pasos asumen que ya has creado nodos en tu entorno air-gap, estás usando el containerd incluido como tiempo de ejecución del contenedor, y no puedes o no quieres usar un registro privado.

Este método requiere desplegar manualmente las imágenes necesarias en cada nodo, y es apropiado para despliegues periféricos en los que no resulta práctico ejecutar un registro privado.

[#_prepare_the_images_directory_and_airgap_image_tarball]
[pass]
<h3><a class="anchor" id="_prepare_the_images_directory_and_airgap_image_tarball" href="#_prepare_the_images_directory_and_airgap_image_tarball"></a>Prepare el directorio de imágenes y el tarball de imágenes Airgap</h3>

. En una máquina accesible desde Internet, descargue el archivo de imágenes para su arquitectura desde la página https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL] para la versión de K3s que planea instalar. Por ejemplo:
+
[,bash]
----
curl -L -o k3s-airgap-images-amd64.tar.zst "<PRIME-ARTIFACTS-URL>/k3s/v1.35.1%2Bk3s1/k3s-airgap-images-amd64.tar.zst"
----

. Transfiere el archivo de imágenes a los nodos airgap. Colóquelos en el directorio de imágenes del agente, por ejemplo:
+
[,bash]
----
sudo mkdir -p /var/lib/rancher/k3s/agent/images/
sudo curl -L -o /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.zst ""https://github.com/k3s-io/k3s/releases/download/v1.33.1%2Bk3s1/k3s-airgap-images-amd64.tar.zst"
sudo cp k3s-airgap-images-amd64.tar.zst /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.zst
----

. Continúe con la sección <<_install_k3s,Instalar K3s>> a continuación.
 
[#_enable_conditional_image_imports]
[pass]
<h3><a class="anchor" id="_enable_conditional_image_imports" href="#_enable_conditional_image_imports"></a>Activar la importación condicional de imágenes</h3>

[IMPORTANT]
.Versión Puerta
====
La importación condicional de imágenes está disponible a partir de las versiones de mayo de 2025: v1.33.1+k3s1, v1.32.5+k3s1, v1.31.9+k3s1, v1.30.13+k3s1.
====

Los archivos de imágenes se importan cada vez que se inicia k3s. Esto se hace para garantizar que todas las imágenes estén disponibles de forma consistente, incluso si algunas imágenes han sido eliminadas o podadas desde la última puesta en marcha. Sin embargo, esto retrasa el inicio, ya que el kubelet no se inicia hasta que se han procesado todos los archivos. Para aliviar este retraso, existe la opción de importar únicamente los archivos tar que hayan cambiado desde la última vez que se importaron, incluso tras reinicios.

Para activar esta función, cree un archivo `+.cache.json+` en el directorio de imágenes:

[,bash]
----
touch /var/lib/rancher/k3s/agent/images/.cache.json
----

El archivo caché almacenará metadatos de archivo a medida que se procesen los ficheros. Los reinicios posteriores del K3s no importarán las imágenes, siempre que el tamaño y el tiempo de modificación del archivo sigan siendo los mismos.

[WARNING]
====
Cuando esta función esté activada, no será posible garantizar que todas las imágenes estén disponibles cada vez que se inicie k3s. Si una imagen ha sido eliminada o podada desde el último inicio, realice una acción manual para reimportar la imagen. Cualquiera:

* Importe manualmente el archivo con `+ctr image import+`.
* Utilice `+touch+` para modificar la marca de tiempo del archivo que contiene la imagen.
* Borre el contenido del archivo `+.cache.json+`, y reinicie k3s.
====
--

Espejo de registro integrado::
+
--
K3s incluye una réplica de registro distribuida incrustada compatible con OCI.
Cuando se activa y se configura correctamente, las imágenes disponibles en el almacén de imágenes containerd de cualquier nodo pueden ser extraídas por otros miembros del clúster sin necesidad de acceder a un registro de imágenes externo.

Las imágenes reflejadas pueden proceder de un registro ascendente, una réplica del registro o un tarball de imágenes airgap.
Para obtener más información sobre la activación de la xref:installation/registry-mirror.adoc[réplica] del registro distribuido incrustado, consulte la documentación de xref:installation/registry-mirror.adoc[la réplica del registro incrustado].
--
======

[#_install_k3s]
== Instalar K3s

=== Requisitos previos

Antes de instalar K3s, elija una de las opciones de xref:#_load_images[carga de imágenes] anteriores para rellenar previamente las imágenes que K3s necesita instalar.

==== Descargar el binario y el script

* Descargue el binario K3s de la página https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL], que coincide con la misma versión utilizada para obtener las imágenes del entrehierro. Coloque el binario en `+/usr/local/bin+` en cada nodo con air-gap y asegúrese de que es ejecutable.
+
[,bash]
----
sudo curl -Lo /usr/local/bin/k3s <PRIME-ARTIFACTS-URL>/k3s/v1.35.1%2Bk3s1/k3s
sudo chmod +x /usr/local/bin/k3s
----

* Descarga el script de instalación de K3s en https://get.k3s.io[get.k3s.io]. Coloque el script de instalación en cualquier lugar de cada nodo air-gapped y nómbrelo `+install.sh+`.
+
[,bash]
----
curl -Lo install.sh https://get.k3s.io
chmod +x install.sh
----

.**Establecer ruta de red por defecto** - necesario para nodos sin ruta por defecto
[%collapsible]
======
Si sus nodos no tienen una interfaz con una ruta por defecto, se debe configurar una ruta por defecto; incluso una ruta de agujero negro a través de una interfaz ficticia será suficiente. K3s requiere una ruta por defecto para auto-detectar la IP primaria del nodo, y para que el enrutamiento kube-proxy ClusterIP funcione correctamente. Para añadir una ruta ficticia, haga lo siguiente:

[,bash]
----
ip link add dummy0 type dummy
ip link set dummy0 up
ip addr add 203.0.113.254/31 dev dummy0
ip route add default via 203.0.113.255 dev dummy0 metric 1000
----
======

.**Descargar SELinux RPM** - necesario para nodos airgapped con SELinux activado
[%collapsible]
======
Si se ejecuta en un nodo air-gapped con SELinux habilitado, debe instalar manualmente el RPM k3s-selinux antes de instalar K3s. Este RPM incluye las políticas SELinux necesarias para que K3s funcione correctamente. La última versión del RPM se encuentra https://github.com/k3s-io/k3s-selinux/releases/latest[en]. Por ejemplo, en CentOS 8:

[,bash]
----
# On an internet accessible machine:
curl -LO https://github.com/k3s-io/k3s-selinux/releases/download/v1.6.stable.1/k3s-selinux-1.6-1.el8.noarch.rpm

# Transfer RPM to air-gapped machine
sudo yum install ./k3s-selinux-1.6-1.el8.noarch.rpm
----

La instalación del RPM k3s-selinux requiere que las siguientes dependencias estén disponibles en el sistema operativo:

* container-selinux
* policycoreutils
* selinux-policy

Consulte la sección xref:advanced.adoc#_selinux_support[SELinux] para obtener más información.
======

=== Ejecución del script de instalación

Puede instalar K3s en uno o más servidores como se describe a continuación.

[tabs,sync-group-id=airgap-install]
======
Configuración de servidor único::
+
--
Para instalar K3s en un único servidor, simplemente haga lo siguiente en el nodo servidor:

[,bash]
----
INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh
----

Para añadir agentes adicionales, haga lo siguiente en cada nodo agente:

[,bash]
----
INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://<SERVER_IP>:6443 K3S_TOKEN=<YOUR_TOKEN> ./install.sh
----
--

Configuración de alta disponibilidad::
+
--
Consulte las guías xref:datastore/ha.adoc[Alta disponibilidad] xref:datastore/ha-embedded.adoc[con base] xref:datastore/ha.adoc[de datos externa] o xref:datastore/ha-embedded.adoc[Alta disponibilidad con base de datos integrada]. Estarás modificando los comandos de instalación para que especifiques `+INSTALL_K3S_SKIP_DOWNLOAD=true+` y ejecutes tu script de instalación localmente en lugar de a través de curl. También utilizará `+INSTALL_K3S_EXEC='args'+` para suministrar cualquier argumento a k3s.

Por ejemplo, el paso dos de la guía Alta disponibilidad con una BD externa menciona lo siguiente:

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server \
  --token=SECRET \
  --datastore-endpoint="mysql://username:password@tcp(hostname:3306)/database-name"
----

En su lugar, modificaría estos ejemplos como se indica a continuación:

[,bash]
----
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server --token=SECRET' \
K3S_DATASTORE_ENDPOINT='mysql://username:password@tcp(hostname:3306)/database-name' \
./install.sh
----
--
======

[NOTE]
====
La bandera `+--resolv-conf+` de K3s se transmite al kubelet, lo que puede ayudar a configurar la resolución DNS del pod en redes de espacio aéreo en las que el host no tiene configurados servidores de nombres ascendentes.
====

== Actualización de

[tabs,sync-group-id=airgap-upgrade]
======
Actualización manual::
+
--
La actualización de un entorno con cámara de aire puede realizarse de la siguiente manera:

. Descargue las nuevas imágenes de entrehierro (archivo tar) de la página https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[URL] correspondiente a la versión de K3s a la que vaya a actualizar. Coloque el tar en el directorio `+/var/lib/rancher/k3s/agent/images/+` de cada nodo. Borra el archivo tar antiguo.
. Copie y reemplace el antiguo binario K3s en `+/usr/local/bin+` en cada nodo. Copie el script de instalación en https://get.k3s.io (ya que es posible que haya cambiado desde la última versión). Vuelva a ejecutar el script tal y como lo hizo en el pasado con las mismas variables de entorno.
. Reinicie el servicio K3s (si el instalador no lo ha reiniciado automáticamente).
--

Método de actualización automática::
+
--
K3s admite xref:upgrades/automated.adoc[actualizaciones automáticas]. Para habilitar esto en entornos con air-gapped, debe asegurarse de que las imágenes requeridas están disponibles en su registro privado.

Necesitará la versión de rancher/k3s-upgrade que corresponda a la versión de K3s a la que pretende actualizar. Tenga en cuenta que la etiqueta de imagen sustituye `+++` en la versión K3s por `+-+` porque las imágenes Docker no admiten `+++`.

También necesitará las versiones de system-upgrade-controller y kubectl que se especifican en el manifiesto YAML de system-upgrade-controller que desplegará. Busque la última versión de system-upgrade-controller https://github.com/rancher/system-upgrade-controller/releases/latest[aquí] y descargue system-upgrade-controller.yaml para determinar las versiones que necesita enviar a su registro privado. Por ejemplo, en la versión v0.4.0 del system-upgrade-controller, estas imágenes se especifican en el manifiesto YAML:

----
rancher/system-upgrade-controller:v0.4.0
rancher/kubectl:v0.17.0
----

Una vez que haya añadido las imágenes necesarias rancher/k3s-upgrade, rancher/system-upgrade-controller y rancher/kubectl a su registro privado, siga la guía de xref:upgrades/automated.adoc[actualizaciones automáticas].
--
======
