= Espejo de registro integrado
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

[IMPORTANT]
.Versión Puerta
====
El Embedded Registry Mirror está disponible como función experimental a partir de las versiones de enero de 2024: v1.26.13+k3s1, v1.27.10+k3s1, v1.28.6+k3s1, v1.29.1+k3s1 y GA a partir de las versiones de diciembre de 2024: v1.29.12+k3s1, v1.30.8+k3s1, v1.31.4+k3s1.
====

K3s incorpora https://github.com/XenitAB/spegel[Spegel], una réplica de registro OCI distribuida y sin estado que permite compartir imágenes de contenedores entre nodos de un clúster Kubernetes. La réplica distribuida del registro está desactivada por defecto. Para que K3s lo aproveche, debe habilitar tanto la xref:#_enabling_the_distributed_oci_registry_mirror[réplica distribuida del Registro OCI] como xref:#_enabling_registry_mirroring[la réplica del Registro], tal y como se explica en las siguientes subsecciones.

[#_enabling_the_distributed_oci_registry_mirror]
== Activación de la réplica distribuida del registro OCI

Para habilitar la réplica del registro incrustado, los nodos del servidor deben iniciarse con la bandera `+--embedded-registry+`, o con `+embedded-registry: true+` en el archivo de configuración.
Esta opción habilita la réplica incrustada para su uso en todos los nodos del clúster.

Cuando se activa a nivel de clúster, todos los nodos alojarán un registro OCI local en el puerto 6443, y publicarán una lista de imágenes disponibles a través de una red peer to peer en el puerto 5001.
Cualquier imagen disponible en el almacén de imágenes containerd en cualquier nodo, puede ser extraída por otros miembros del cluster sin acceso a un registro externo.
Las imágenes importadas a través de xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[archivos tar de imágenes air-gap] se fijan en containerd para garantizar que permanezcan disponibles y no sean eliminadas por la recolección de basura de Kubelet.

El puerto peer to peer puede cambiarse de 5001 configurando la variable de entorno `+K3S_P2P_PORT+` para el servicio K3s. El puerto debe tener el mismo valor en todos los nodos.
Cambiar el puerto no está soportado y no se recomienda.

=== Requisitos

Cuando la réplica de registro integrada está activada, todos los nodos deben poder comunicarse entre sí a través de sus direcciones IP internas, en los puertos TCP 5001 y 6443.
Si los nodos no pueden comunicarse entre sí, las imágenes pueden tardar más en ser extraídas, ya que containerd intentará primero el registro distribuido, antes de recurrir a otros puntos finales.

[#_enabling_registry_mirroring]
== Activación de la duplicación de registros

Activar la réplica de un registro permite a un nodo extraer imágenes de ese registro de otros nodos y compartir las imágenes del registro con otros nodos.
Si un registro está habilitado para la réplica en algunos nodos, pero no en otros, sólo los nodos con el registro habilitado intercambiarán imágenes de ese registro.

Para habilitar la réplica de imágenes de un registro de contenedores ascendente, los nodos deben tener una entrada en la sección `+mirrors+` de `+registries.yaml+` para ese registro.
No es necesario que el registro contenga ningún punto final, sólo tiene que estar presente.
Por ejemplo, para habilitar la réplica distribuida de imágenes de `+docker.io+` y `+registry.k8s.io+`, configure `+registries.yaml+` con el siguiente contenido en todos los nodos del clúster:

[,yaml]
----
mirrors:
  docker.io:
  registry.k8s.io:
----

También pueden añadirse, como de costumbre, puntos finales para réplicas del registro.
En la siguiente configuración, los intentos de extracción de imágenes probarán primero el espejo incrustado, luego `+mirror.example.com+`, y finalmente `+docker.io+`:

[,yaml]
----
mirrors:
  docker.io:
    endpoint:
      - https://mirror.example.com
----

Si está utilizando un registro privado directamente, en lugar de como réplica de un registro ascendente, puede activar la réplica distribuida de la misma forma que se activan los registros públicos: listándolo en la sección de réplicas:

[,yaml]
----
mirrors:
  mirror.example.com:
----

[IMPORTANT]
.Versión Puerta
====
La compatibilidad con comodines está disponible a partir de las versiones de marzo de 2024: v1.26.15+k3s1, v1.27.12+k3s1, v1.28.8+k3s1, v1.29.3+k3s1
====


La entrada comodín de réplica `+"*"+` puede utilizarse para activar la réplica distribuida de todos los registros. Tenga en cuenta que el asterisco DEBE ir entre comillas:

[,yaml]
----
mirrors:
  "*":
----

Si no hay registros habilitados para la réplica en un nodo, ese nodo no participa en el registro distribuido en ninguna capacidad.

Para obtener más información sobre la estructura del archivo `+registries.yaml+`, consulte xref:installation/private-registry.adoc[Configuración del registro privado].

=== Endpoint Fallback por defecto

De forma predeterminada, containerd recurrirá al punto final predeterminado cuando se extraiga de registros con puntos finales de réplica configurados. Si desea deshabilitar esto, y sólo extraer imágenes de las réplicas configuradas y/o de la réplica incrustada, consulte la sección xref:installation/private-registry.adoc#_default_endpoint_fallback[Default Endpoint Fallback]de la documentación Configuración del Registro Privado.

Tenga en cuenta que si está utilizando la opción `+--disable-default-registry-endpoint+` y desea permitir la extracción directamente de un registro en particular, mientras que no permite el resto, puede proporcionar explícitamente un punto final para permitir que la extracción de la imagen vuelva al propio registro:

[,yaml]
----
mirrors:
  docker.io:           # no default endpoint, pulls will fail if not available on a node
  registry.k8s.io:     # no default endpoint, pulls will fail if not available on a node
  mirror.example.com:  # explicit default endpoint, can pull from upstream if not available on a node
    endpoint:
      - https://mirror.example.com
----

=== Última etiqueta

Cuando no se especifica ninguna etiqueta para una imagen contenedora, la etiqueta implícita por defecto es `+latest+`. Esta etiqueta se actualiza con frecuencia para señalar la versión más reciente de la imagen. Dado que esta etiqueta apuntará a diferentes revisiones de una imagen dependiendo de cuándo se extraiga, el registro distribuido *no* extraerá la etiqueta `+latest+` de otros nodos. Esto obliga a containerd a ir a un registro upstream o a una réplica del registro para asegurar una visión consistente de a qué se refiere la etiqueta `+latest+`.

Esto se alinea con la https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting[especial `+imagePullPolicy+` predeterminada]observada por Kubernetes cuando se utiliza la etiqueta `+latest+` para una imagen de contenedor.

La duplicación de la etiqueta `+latest+` puede activarse configurando la variable de entorno `+K3S_P2P_ENABLE_LATEST=true+` para el servicio K3s.
Esto no está respaldado y no se recomienda, por las razones expuestas anteriormente.

== Seguridad

=== Autenticación

El acceso a la API de registro de la réplica integrada requiere un certificado de cliente válido, firmado por la autoridad de certificación de cliente del clúster.

El acceso a la red de pares de la tabla hash distribuida requiere una clave precompartida que controlan los nodos servidores.
Los nodos se autentican entre sí utilizando tanto la clave precompartida como un certificado firmado por la autoridad de certificación del clúster.

=== Posibles problemas

[CAUTION]
====
El registro distribuido se basa en los principios peer-to-peer, y asume un mismo nivel de privilegio y confianza entre todos los miembros del clúster.
Si esto no coincide con la postura de seguridad de su clúster, no debe habilitar el registro distribuido incrustado.
====


El registro integrado puede poner a disposición imágenes a las que un nodo no tendría acceso de otro modo.
Por ejemplo, si algunas de sus imágenes se extraen de un registro, proyecto o repositorio que requiere autenticación a través de Kubernetes Image Pull Secrets, o credenciales en `+registries.yaml+`, el registro distribuido permitirá a otros nodos compartir esas imágenes sin proporcionar ninguna credencial al registro ascendente.

Los usuarios con acceso para insertar imágenes en el almacén de imágenes containerd en un nodo pueden utilizar esto para "envenenar" la imagen para otros nodos del clúster, ya que otros nodos confiarán en la etiqueta anunciada por el nodo, y la utilizarán sin comprobar con el registro upstream.
Si la integridad de la imagen es importante, debe utilizar compendios de imágenes en lugar de etiquetas, ya que el compendio no puede ser envenenado de esta manera.

== Compartir imágenes cargadas manualmente o en el aire

La compartición de imágenes se controla en función del registro de origen.
Las imágenes cargadas directamente en containerd mediante xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[tarballs air-gap], xref:add-ons/import-images.adoc#_pre_import_images[preimportadas] o cargadas directamente en el almacén de imágenes de containerd mediante la herramienta de línea de comandos `+ctr+` se comparten entre nodos si están etiquetadas como procedentes de un registro habilitado para la réplica.

Tenga en cuenta que el registro ascendente del que parecen proceder las imágenes no tiene por qué existir o ser accesible.
Por ejemplo, podrías etiquetar imágenes como procedentes de un registro upstream ficticio, e importar esas imágenes al almacén de imágenes de containerd.
A continuación, podrá extraer esas imágenes de todos los miembros del clúster, siempre y cuando ese registro esté listado en `+registries.yaml+`

== Empujar imágenes

El registro incrustado es de sólo lectura y no se puede acceder a él directamente utilizando `+docker push+` u otras herramientas comunes que interactúan con registros OCI.

Las imágenes pueden estar disponibles manualmente a través del registro integrado ejecutando `+ctr -n k8s.io image pull+` para extraer una imagen, o cargando archivos de imagen creados por `+docker save+` mediante el comando `+ctr -n k8s.io image import+` o la xref:add-ons/import-images.adoc#_pre_import_images[función de preimportación].
Tenga en cuenta que el espacio de nombres `+k8s.io+` debe especificarse al gestionar imágenes a través de `+ctr+` para que sean visibles para el kubelet.
