= Kubernetes-Sicherung (Legacy)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

[WARNING]
====
*Auf dieser Seite wird das Legacy-Backup-Konzept mit Skripten beschrieben. Für {stackstate-product-name} v2.7.0 oder neuer, verwenden Sie stattdessen die neue xref:/setup/data-management/backup_restore/backup_enable.adoc[Backup-CLI].*

**Einschneidende Änderungen in v2.7.0:**

* `+backup.enabled+` wird durch `+global.backup.enabled+` ersetzt - Helm-Einsätze schlagen fehl, wenn `+backup.enabled+` eingestellt ist auf `+true+`
* Alle Backups werden mit einem einzigen Wert `+global.backup.enabled+` gesteuert, anstatt pro Datenspeicher aktiviert zu werden.
* `+*.restore.enabled+` Werte wurden entfernt
====

== Übersicht

{stackstate-product-name} verfügt über einen integrierten Sicherungs- und Wiederherstellungsmechanismus, der so konfiguriert werden kann, dass er Backups in den lokalen Clustern, in AWS S3 oder in Azure Blob Storage speichert.

=== Sicherungsbereich

Die folgenden Daten können automatisch gesichert werden:

* In StackGraph gespeicherte *Konfigurations- und Topologiedaten* 
* *Metriken*, die in der/den Victoria Metrics-Instanz(en) von SUSE Observability gespeichert sind
* *Telemetriedaten*, die in der Elasticsearch-Instanz von SUSE Observability gespeichert werden
* *OpenTelemetry-Daten*, die in der ClickHouse-Instanz von SUSE Observability gespeichert sind

Die folgenden Daten werden *nicht* gesichert:

* Topologie- und Telemetrie-Updates, die in Kafka gespeichert sind, haben nur einen vorübergehenden Wert und wären bei der Wiederherstellung eines Backups nicht mehr von Nutzen.
* Der Verhandlungsstatus des Master-Knotens ist im ZooKeeper gespeichert - dieser Laufzeitstatus wäre bei der Wiederherstellung falsch und wird zur Laufzeit automatisch ermittelt.
* Kubernetes-Konfigurationsstatus und Raw-Persistent-Volume-Status - dieser Status kann durch Neuinstallation von SUSE Observability und Wiederherstellung der Backups wiederhergestellt werden.
* Kubernetes-Protokolle - diese sind flüchtig.

=== Speicheroptionen

Backups werden an eine Instanz von https://min.io/[MinIO (min.io)] gesendet, die automatisch vom `+suse-observability+` Helm-Diagramm gestartet wird, wenn automatische Backups aktiviert sind. MinIO ist ein Objektspeichersystem mit der gleichen API wie AWS S3. Es kann seine Daten lokal speichern oder als Gateway zu https://docs.min.io/docs/minio-gateway-for-s3.html[AWS S3 (min.io)], https://docs.min.io/docs/minio-gateway-for-azure.html[Azure BLob Storage (min.io)] und anderen Systemen fungieren.

Die integrierte MinIO-Instanz kann so konfiguriert werden, dass die Backups an drei Orten gespeichert werden:

* xref:/setup/data-management/backup_restore/kubernetes_backup.adoc[AWS S3]
* xref:/setup/data-management/backup_restore/kubernetes_backup.adoc[Azure Blob-Speicher]
* xref:/setup/data-management/backup_restore/kubernetes_backup.adoc[Kubernetes-Speicher]

== Aktivieren von Backups

=== AWS S3

[CAUTION]
====

*Verschlüsselung*

Für die Verschlüsselung der S3-Buckets, in denen die Backups gespeichert sind, sollten von Amazon S3 verwaltete Schlüssel (SSE-S3) verwendet werden.

⚠️ Verschlüsselung mit AWS KMS-Schlüsseln, die im AWS Key Management Service (SSE-KMS) gespeichert sind, wird nicht unterstützt. Dies führt zu Fehlern wie diesem in den Elasticsearch-Protokollen:

`+Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: sdk_client_exception: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: ZX4D/ZDUzZWRhNDUyZTI1MTc= in base 64) didn't match hash (etag: c75faa31280154027542f6530c9e543e in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@5481a656, bucketName: suse-observability-elasticsearch-backup, key: tests-UG34QIV9s32tTzQWdPsZL/master.dat)",+`
====


Um geplante Backups in AWS S3-Buckets zu aktivieren, fügen Sie das folgende YAML-Fragment in die Helm `+values.yaml+` -Datei ein, die zur Installation von SUSE Observability verwendet wird:

[,yaml]
----
global:
  backup:
    enabled: true
backup:
  stackGraph:
    bucketName: AWS_STACKGRAPH_BUCKET
  elasticsearch:
    bucketName: AWS_ELASTICSEARCH_BUCKET
  configuration:
    bucketName: AWS_CONFIGURATION_BUCKET
victoria-metrics-0:
  backup:
    bucketName: AWS_VICTORIA_METRICS_BUCKET
victoria-metrics-1:
  backup:
    bucketName: AWS_VICTORIA_METRICS_BUCKET
clickhouse:
  backup:
    bucketName: AWS_CLICKHOUSE_BUCKET
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  s3gateway:
    enabled: true
    accessKey: AWS_ACCESS_KEY
    secretKey: AWS_SECRET_KEY
----

Ersetzen Sie die folgenden Werte:

* `+YOUR_ACCESS_KEY+` und `+YOUR_SECRET_KEY+` sind die Anmeldedaten, die zur Sicherung des MinIO-Systems verwendet werden. Diese Anmeldedaten werden auf dem MinIO-System festgelegt und von den automatischen Sicherungs- und Wiederherstellungsaufträgen verwendet. Sie sind auch erforderlich, wenn Sie manuell auf das MinIO-System zugreifen möchten.
 ** DEIN_ZUGRIFFSSCHLÜSSEL sollte 5 bis 20 alphanumerische Zeichen enthalten.
 ** YOUR_SECRET_KEY sollte 8 bis 40 alphanumerische Zeichen enthalten.
* `+AWS_ACCESS_KEY+` und `+AWS_SECRET_KEY+` sind die AWS-Anmeldeinformationen für den IAM-Benutzer, der Zugriff auf die S3-Buckets hat, in denen die Backups gespeichert werden. Siehe unten für die Berechtigungsrichtlinie, die diesem Benutzer zugewiesen werden muss.
* `+AWS_STACKGRAPH_BUCKET+`, `+AWS_CONFIGURATION_BUCKET+`, `+AWS_ELASTICSEARCH_BUCKET+`, `+AWS_VICTORIA_METRICS_BUCKET+` und `+AWS_CLICKHOUSE_BUCKET+` sind die Namen der S3-Buckets, in denen die Backups gespeichert werden sollen. Anmerkung: Die Namen von AWS S3-Buckets sind für ganz AWS global, daher werden die S3-Buckets mit dem Standardnamen (`+sts-elasticsearch-backup+`, `+sts-configuration-backup+`, `+sts-stackgraph-backup+`, `+sts-victoria-metrics-backup+` und `+sts-clickhouse-backup+` ) wahrscheinlich nicht verfügbar sein.

Der durch `+AWS_ACCESS_KEY+` und `+AWS_SECRET_KEY+` identifizierte IAM-Benutzer muss mit der folgenden Berechtigungsrichtlinie konfiguriert werden, um auf die S3-Buckets zugreifen zu können:

[,javascript]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowListMinioBackupBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::AWS_STACKGRAPH_BUCKET",
                "arn:aws:s3:::AWS_ELASTICSEARCH_BUCKET",
                "arn:aws:s3:::AWS_VICTORIA_METRICS_BUCKET",
                "arn:aws:s3:::AWS_CLICKHOUSE_BUCKET",
                "arn:aws:s3:::AWS_CONFIGURATION_BUCKET"
            ]
        },
        {
            "Sid": "AllowWriteMinioBackupBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::AWS_STACKGRAPH_BUCKET/*",
                "arn:aws:s3:::AWS_ELASTICSEARCH_BUCKET/*",
                "arn:aws:s3:::AWS_VICTORIA_METRICS_BUCKET/*",
                "arn:aws:s3:::AWS_CLICKHOUSE_BUCKET/*",
                "arn:aws:s3:::AWS_CONFIGURATION_BUCKET"
            ]
        }
    ]
}
----

=== Azure Blob-Speicher

Um Backups auf einem Azure Blob Storage-Konto zu aktivieren, fügen Sie das folgende YAML-Fragment in die Helm `+values.yaml+` -Datei ein, die zur Installation von SUSE Observability verwendet wird:

[,yaml]
----
global:
  backup:
    enabled: true
minio:
  accessKey: AZURE_STORAGE_ACCOUNT_NAME
  secretKey: AZURE_STORAGE_ACCOUNT_KEY
  azuregateway:
    enabled: true
----

Ersetzen Sie die folgenden Werte:

* `+AZURE_STORAGE_ACCOUNT_NAME+` - den https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal[Azure-Speicher-Kontonamen (learn.microsoft.com)]
* `+AZURE_STORAGE_ACCOUNT_KEY+` - den https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal[Azure-Speicherkontoschlüssel (learn.microsoft.com)], unter dem die Backups gespeichert werden sollen.

Die Backups von StackGraph, Elasticsearch und Victoria Metrics werden in BLOB-Containern mit den Bezeichnungen `+sts-stackgraph-backup+`, `+sts-configuration-backup+`, `+sts-elasticsearch-backup+`, `+sts-victoria-metrics-backup+`, `+sts-clickhouse-backup+` gespeichert. Diese Namen können durch Setzen der Helm-Werte `+backup.stackGraph.bucketName+`, `+backup.elasticsearch.bucketName+`, `+victoria-metrics-0.backup.bucketName+`, `+victoria-metrics-1.backup.bucketName+` und `+clickhouse.backup.bucketName+` geändert werden.

=== Kubernetes-Speicher

[CAUTION]
====
Wenn MinIO so konfiguriert ist, dass seine Daten im Kubernetes-Speicher gespeichert werden, wird ein PersistentVolumeClaim (PVC) verwendet, um Speicher vom Kubernetes-Cluster anzufordern. Die Art des zugewiesenen Speichers hängt von der Konfiguration des Clusters ab.

Aus den folgenden Gründen wird empfohlen, AWS S3 für Cluster auf Amazon AWS und Azure Blob Storage für Cluster auf Azure zu verwenden:

. Kubernetes-Cluster, die bei einem Cloud-Anbieter laufen, ordnen PVCs in der Regel einem Blockspeicher zu, z. B. Elastic Block Storage für AWS oder Azure Block Storage. Blockspeicher sind teuer, insbesondere bei großen Datenmengen.
. Persistent Volumes werden zerstört, wenn der Cluster, der sie erstellt hat, zerstört wird. Das bedeutet, dass eine (versehentliche) Löschung Ihres Clusters auch alle in Persistent Volumes gespeicherten Backups zerstört.
. Auf Persistent Volumes kann von einem anderen Cluster aus nicht zugegriffen werden. Das bedeutet, dass es nicht möglich ist, SUSE Observability aus einer Sicherung wiederherzustellen, die auf einem anderen Cluster erstellt wurde.
====


Um Backups auf clusterlokalem Storage zu ermöglichen, aktivieren Sie MinIO, indem Sie das folgende YAML-Fragment zur Helm `+values.yaml+` -Datei hinzufügen, die zur Installation von SUSE Observability verwendet wird:

[,yaml]
----
global:
  backup:
    enabled: true
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  persistence:
    enabled: true
----

Ersetzen Sie die folgenden Werte:

* `+YOUR_ACCESS_KEY+` und `+YOUR_SECRET_KEY+` - die Anmeldedaten, die zur Sicherung des MinIO-Systems verwendet werden. Die automatischen Sicherungsaufträge und die Wiederherstellungsaufträge verwenden sie. Sie werden auch für den manuellen Zugriff auf den MinIO-Speicher benötigt. `+YOUR_ACCESS_KEY+` sollte 5 bis 20 alphanumerische Zeichen und `+YOUR_SECRET_KEY+` sollte 8 bis 40 alphanumerische Zeichen enthalten.

== Konfigurations- und Topologiedaten (StackGraph)

Sicherungen von Konfigurations- und Topologiedaten (StackGraph) sind Vollsicherungen, die in einer einzigen Datei mit der Erweiterung `+.graph+` gespeichert werden. Jede Datei enthält eine vollständige Sicherung und kann nach Bedarf verschoben, kopiert oder gelöscht werden.

=== Sicherungszeitplan

Standardmäßig werden die StackGraph-Backups täglich um 03:00 Uhr Serverzeit erstellt.

Der Sicherungszeitplan kann mit dem Helm-Wert `+backup.stackGraph.scheduled.schedule+` konfiguriert werden, der in der https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#_cron_schedule_syntax[Syntax] Kubernetes angegeben wird.

=== Aufbewahrung von Sicherungskopien

Standardmäßig werden die Backups von StackGraph 30 Tage lang aufbewahrt. Da es sich bei den StackGraph-Sicherungen um Vollsicherungen handelt, kann dies viel Speicherplatz erfordern.

Das Delta der Sicherungsaufbewahrung kann mit dem Helm-Wert `+backup.stackGraph.scheduled.backupRetentionTimeDelta+` konfiguriert werden, der im Format des GNU-Datums `+--date+` angegeben wird. Der Standardwert ist zum Beispiel `+30 days ago+`. Weitere Beispiele finden Sie unter https://www.gnu.org/software/coreutils/manual/html_node/Relative-items-in-date-strings.html[Relative Elemente in Datumsstrings].

=== Geplante Backups deaktivieren

Um geplante StackGraph-Backups zu deaktivieren, setzen Sie den Backup-Zeitplan mit dem Helm-Wert `+backup.stackGraph.scheduled.schedule+` auf ein weit zurückliegendes Datum:

[,yaml]
----
backup:
  stackGraph:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Metriken (Victoria Metriken)

[WARNING]
====
Victoria Metrics verwendet inkrementelle Backups ohne Versionierung eines Buckets, d. h., das neue Backup *ersetzt das vorherige vollständig*.

Für den Fall, dass Sie in eine der folgenden Situationen geraten:

* ein leeres Volume in das Verzeichnis `+/storage+` von Victoria Metrics-Instanzen mounten
* das Verzeichnis `+/storage+` oder darin enthaltene Dateien aus Victoria Metrics-Instanzen löschen

Das nächste (leere) Backup wird mit einer neuen Version versehen und das vorherige, bevor der Datenträger geleert wurde, bleibt erhalten.
Beide Sicherungen werden von diesem Moment an <<_list_victoria_metrics_backups,als für die Wiederherstellung verfügbar aufgelistet>>.
====


Metrics (Victoria Metrics) verwendet sofortige Snapshots, um Daten in inkrementellen Backups zu speichern. Mehrere Instanzen von Victoria Metrics können Backups im selben Bucket speichern, wobei jedes dieser Backups in einem eigenen Verzeichnis gespeichert wird. Alle Dateien, die sich in diesem Verzeichnis befinden, sollten als ein Ganzes behandelt werden und können nur als Ganzes verschoben, kopiert oder gelöscht werden.

[NOTE]
====
Hochverfügbare Bereitstellungen sollten mit zwei Instanzen von Victoria Metrics bereitgestellt werden. Die Backups werden für jedes dieser Systeme unabhängig voneinander aktiviert/konfiguriert.

Die folgenden Codeschnipsel/Befehle sind für die erste Instanz von Victoria Metric `+victoria-metrics-0+` vorgesehen. Zum Sichern/Konfigurieren der zweiten Instanz sollten Sie `+victoria-metrics-1+`
====


=== Sicherungszeitplan

Standardmäßig werden die Victoria Metrics-Backups alle 1 Stunde erstellt:

* `+victoria-metrics-0+` - 25 Minuten nach der vollen Stunde
* `+victoria-metrics-1+` - 35 Minuten nach der vollen Stunde

Der Sicherungszeitplan kann mit dem Helm-Wert `+victoria-metrics-0.backup.scheduled.schedule+` gemäß https://github.com/aptible/supercronic/tree/master/cronexpr[cronexpr-Format] konfiguriert werden.

=== Geplante Backups deaktivieren

Um geplante Victoria Metrics-Sicherungen zu deaktivieren, setzen Sie den Sicherungszeitplan für beide Instanzen auf ein Datum, das weit in der Vergangenheit liegt:

[,yaml]
----
victoria-metrics-0:
  backup:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
victoria-metrics-1:
  backup:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== OpenTelemetry (KlickHaus)

ClickHouse verwendet sowohl inkrementelle als auch vollständige Backups. Standardmäßig werden vollständige Backups täglich um 00:45 Uhr und inkrementelle Backups stündlich durchgeführt. Bei jeder Sicherung wird ein neues Verzeichnis angelegt und alte Sicherungen (Verzeichnisse) werden automatisch gelöscht. Alle Dateien, die sich in einem Sicherungsverzeichnis befinden, werden als eine einzige Gruppe behandelt und können nur als Gruppe verschoben, kopiert oder gelöscht werden. Es wird empfohlen, für die Verwaltung von Sicherungen das Tool `+clickhouse-backup+` zu verwenden, das auf dem `+suse-observability-clickhouse-shard0-0+` Pod verfügbar ist.

=== Sicherungszeitplan

Standardmäßig werden die ClickHouse-Backups erstellt:

* Vollständige Datensicherung - jeden Tag um 00:45 Uhr
* Inkrementelle Sicherung - 45 Minuten nach der vollen Stunde (von 3 Uhr morgens bis 12 Uhr nachts)

[CAUTION]
====
Backups haben Probleme mit der parallelen Ausführung. Wenn eine zweite Sicherung beginnt, bevor die erste abgeschlossen ist, wird die erste Sicherung unterbrochen. Deshalb ist es wichtig, eine parallele Ausführung zu vermeiden. Beispielsweise sollte die erste inkrementelle Sicherung drei Stunden nach der vollständigen Sicherung durchgeführt werden.
====


Der Backup-Zeitplan kann mit den Helm-Werten `+clickhouse.backup.scheduled.full_schedule+` und `+clickhouse.backup.scheduled.incremental_schedule+` entsprechend dem https://github.com/aptible/supercronic/tree/master/cronexpr[Format] konfiguriert werden.

=== Aufbewahrung von Sicherungskopien

Standardmäßig behält das Tool die letzten 308 Backups (vollständig und inkrementell), was etwa 14 Tagen entspricht.

Die Backup-Aufbewahrung kann mit dem Helm-Wert `+clickhouse.backup.config.keep_remote+` konfiguriert werden.

=== Geplante Backups deaktivieren

Um geplante ClickHouse-Sicherungen zu deaktivieren, setzen Sie sowohl die Zeitpläne für vollständige als auch für inkrementelle Sicherungen auf ein Datum, das weit in der Vergangenheit liegt:

[,yaml]
----
clickhouse:
  backup:
    scheduled:
      full_schedule: '0 0 1 1 1970'         # January 1, 1970 (epoch start)
      incremental_schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Telemetriedaten (Elasticsearch)

Die Snapshots der Telemetriedaten (Elasticsearch) werden inkrementell in Dateien mit der Erweiterung `+.dat+` gespeichert. Die Dateien im Elasticsearch-Backup-Speicherort sollten als ein einziges Ganzes behandelt werden und können nur als Ganzes verschoben, kopiert oder gelöscht werden.

Die Konfigurationsschnipsel im Abschnitt xref:/setup/data-management/backup_restore/kubernetes_backup.adoc#_enable_backups[enable backups] ermöglichen tägliche Elasticsearch-Snapshots.

=== Geplante Schnappschüsse deaktivieren

Um geplante Elasticsearch-Snapshots zu deaktivieren, setzen Sie den Snapshot-Zeitplan mit dem Helm-Wert `+backup.elasticsearch.scheduled.schedule+` auf ein weit zurückliegendes Datum:

[,yaml]
----
backup:
  elasticsearch:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

=== Schnappschuss-Zeitplan

Standardmäßig werden Elasticsearch-Snapshots täglich um 03:00 Uhr Serverzeit erstellt.

Der Backup-Zeitplan kann mit dem Helm-Wert `+backup.elasticsearch.scheduled.schedule+` konfiguriert werden, der in https://www.elastic.co/guide/en/elasticsearch/reference/7.6/cron-expressions.html[Elasticsearch cron schedule syntax (elastic.co)] angegeben wird.

=== Speicherung von Schnappschüssen

Standardmäßig werden Elasticsearch-Snapshots 30 Tage lang aufbewahrt, mit einem Minimum von 5 Snapshots und einem Maximum von 30 Snapshots.

Die Aufbewahrungszeit und die Anzahl der aufbewahrten Snapshots können mit den folgenden Helm-Werten konfiguriert werden:

* `+backup.elasticsearch.scheduled.snapshotRetentionExpireAfter+`, angegeben in https://www.elastic.co/guide/en/elasticsearch/reference/7.6/common-options.html#_time_units[Elasticsearch-Zeiteinheiten (elastic.co)].
* `+backup.elasticsearch.scheduled.snapshotRetentionMinCount+`
* `+backup.elasticsearch.scheduled.snapshotRetentionMaxCount+`

[NOTE]
====
Die Aufbewahrungsaufgabe selbst https://www.elastic.co/guide/en/elasticsearch/reference/7.6/slm-settings.html#_slm_retention_schedule[läuft] standardmäßig. Wenn Sie festlegen, dass Snapshots schneller als innerhalb eines Tages ablaufen, z. B. zu Testzwecken, müssen Sie den Zeitplan für die Aufbewahrungsaufgabe ändern.
====


=== Schnappschuss-Indizes

Standardmäßig wird ein Snapshot für Elasticsearch-Indizes mit Namen, die mit `+sts+` beginnen, erstellt.

Die Indizes, für die ein Snapshot erstellt wird, können mit dem Helm-Wert `+backup.elasticsearch.scheduled.indices+` konfiguriert werden, der im https://www.w3schools.com/js/js_json_arrays.asp[JSON-Array-Format] angegeben wird.

== Wiederherstellung von Backups und Snapshots

Skripte zum Auflisten und Wiederherstellen von Backups und Snapshots können von der https://github.com/StackVista/helm-charts/releases/latest[neuesten Version der SUSE Observability Helm-Karte] heruntergeladen werden. Laden Sie die `+backup-scripts-<version>.tar.gz+` herunter und entpacken Sie sie, um loszulegen.

[NOTE]
====
*Bevor Sie die Skripte verwenden, stellen Sie sicher, dass:*

* Die Binärdatei `+kubectl+` ist installiert und so konfiguriert, dass eine Verbindung zu ihr hergestellt werden kann:
 .. Der Kubernetes-Cluster, in dem SUSE Observability installiert wurde.
 .. Der Namespace innerhalb dieses Clusters, in dem SUSE Observability installiert wurde.
* Der Helmwert `+global.backup.enabled+` ist auf `+true+` eingestellt.
====


=== StackGraph-Sicherungen auflisten

Um die StackGraph-Backups aufzulisten, führen Sie den folgenden Befehl aus:

[,bash]
----
./restore/list-stackgraph-backups.sh
----

Die Ausgabe sollte wie folgt aussehen:

[,bash]
----
job.batch/stackgraph-list-backups-20210222t111942 created
Waiting for job to start...
=== Listing StackGraph backups in bucket "sts-stackgraph-backup"...
sts-backup-20210215-0300.graph
sts-backup-20210216-0300.graph
sts-backup-20210217-0300.graph
sts-backup-20210218-0300.graph
sts-backup-20210219-0300.graph
sts-backup-20210220-0300.graph
sts-backup-20210221-0300.graph
sts-backup-20210222-0300.graph
===
job.batch "stackgraph-list-backups-20210222t111942" deleted
----

Der Zeitstempel, zu dem die Sicherung erstellt wurde, ist Teil des Sicherungsnamens.

[NOTE]
====
Es werden Zeilen in der Ausgabe erwartet, die mit `+Error from server (BadRequest):+` beginnen. Sie erscheinen, wenn das Skript auf den Start des Pods wartet.
====


=== Wiederherstellen einer StackGraph-Sicherung

[CAUTION]
====
*Um den unerwarteten Verlust vorhandener Daten zu vermeiden, kann eine Sicherung standardmäßig nur in einer sauberen Umgebung wiederhergestellt werden.*
Wenn Sie ganz sicher sind, dass vorhandene Daten überschrieben werden können, können Sie diese Sicherheitsfunktion mit dem Befehl `+-force+` außer Kraft setzen.
Führen Sie den Wiederherstellungsbefehl nur aus, wenn Sie sicher sind, dass Sie die Sicherung wiederherstellen wollen.
====


Um ein StackGraph-Backup in einer sauberen Umgebung wiederherzustellen, wählen Sie einen Backup-Namen aus und übergeben ihn als ersten Parameter im folgenden Befehl:

[,bash]
----
./restore/restore-stackgraph-backup.sh sts-backup-20210216-0300.graph
----

Um ein StackGraph-Backup in einer *Umgebung mit vorhandenen Daten* wiederherzustellen, wählen Sie einen Backup-Namen aus und übergeben ihn als ersten Parameter im folgenden Befehl neben einem zweiten Parameter `+-force+`:
[NOTE]
====
*Beachten Sie, dass vorhandene Daten beim Wiederherstellen der Sicherung überschrieben werden.*

Tun Sie dies nur, wenn Sie ganz sicher sind, dass vorhandene Daten überschrieben werden können.
====


[,bash]
----
./restore/restore-stackgraph-backup.sh sts-backup-20210216-0300.graph -force
----

Die Ausgabe sollte wie folgt aussehen:

[,bash]
----
job.batch/stackgraph-restore-20210222t112142 created
Waiting for job to start...
=== Downloading StackGraph backup "sts-backup-20210216-0300.graph" from bucket "sts-stackgraph-backup"...
download: s3://sts-stackgraph-backup/sts-backup-20210216-1252.graph to ../../tmp/sts-backup-20210216-0300.graph
=== Importing StackGraph data from "sts-backup-20210216-0300.graph"...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/opt/docker/lib/org.codehaus.groovy.groovy-2.5.4.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
===
job.batch "stackgraph-restore-20210222t112142" deleted
----

Wenn Sie einen Wiederherstellungsbefehl ohne das `+-force+` Flag auf einer nicht leeren Datenbank ausführen, wird die Ausgabe einen Fehler wie diesen enthalten:

[,bash]
----
ERROR com.stackvista.graph.migration.Restore - Restore isn't possible in a non empty.
----

[NOTE]
====
Es werden Zeilen erwartet, die mit `+WARNING:+` beginnen. Sie werden von Groovy in JDK 11 erzeugt und können ignoriert werden.
====


=== Liste Victoria Metrics-Sicherungen

Um die Victoria Metrics-Sicherungen aufzulisten, führen Sie den folgenden Befehl aus:

[,bash]
----
./restore/list-victoria-metrics-backups.sh
----

Die Ausgabe sollte wie folgt aussehen:

[,bash]
----
job.batch/victoria-metrics-list-backups-20231016t125557 created
Waiting for job to start...
Waiting for job to start...
=== Fetching timestamps of last completed incremental backups
victoria-metrics-0 victoria-metrics-0-20231128160000 "Wed, 29 Nov 2023 07:36:00 GMT"
victoria-metrics-0 victoria-metrics-0-20231129092200 "Wed, 29 Nov 2023 10:56:00 GMT"

===
job.batch "victoria-metrics-list-backups-20231016t125557" deleted
----

wo Sie die Victoria-Metriken-Instanz, die spezifische Sicherungsversion und das letzte Mal, dass eine Sicherung abgeschlossen wurde, sehen können.

=== Wiederherstellung einer Victoria Metrics-Sicherung

[CAUTION]
====
*Die Wiederherstellungsfunktion hat immer Vorrang vor den Daten. Sie müssen vorsichtig sein, um den unerwarteten Verlust von Daten zu vermeiden.*
====


[CAUTION]
====
*Die Wiederherstellungsfunktion erfordert das Anhalten einer Instanz von Victoria Metric während des Prozesses.*

Alle neuen Metriken werden während des Wiederherstellungsprozesses von `+vmagent+` zwischengespeichert. Bitte stellen Sie sicher, dass `+vmagent+` über genügend Speicherplatz verfügt, um die Metriken zwischenzuspeichern.
====


Um eine Victoria Metrics-Sicherung wiederherzustellen, wählen Sie einen Instanznamen und eine Sicherungsversion aus und übergeben diese als Parameter im folgenden Befehl:

[,bash]
----
./restore/restore-victoria-metrics-backup.sh victoria-metrics-0 victoria-metrics-0-20231128160000
----

Die Ausgabe sollte wie folgt aussehen:

[,bash]
----
=== Scaling down the Victoria Metrics instance
statefulset.apps/suse-observability-victoria-metrics-0 scaled
=== Allowing pods to terminate
=== Starting restore job
job.batch/victoria-metrics-restore-backup-20231017t092607 created
=== Restore job started. Follow the logs with the following command:
kubectl logs --follow job/victoria-metrics-restore-backup-20231017t092607
=== After the job has completed clean up the job and scale up the Victoria Metrics instance pods again with the following commands:
kubectl delete job victoria-metrics-restore-backup-20231017t092607
kubectl scale statefulsets suse-observability-victoria-metrics-0 --replicas=1
----

Folgen Sie dann den Protokollen, um den Auftragsstatus zu überprüfen

----
2023-10-17T07:26:42.564Z    info    VictoriaMetrics/lib/backup/actions/restore.go:194    restored 53072307269 bytes from backup in 0.445 seconds; deleted 639118752 bytes; downloaded 1204539 bytes
2023-10-17T07:26:42.564Z    info    VictoriaMetrics/app/vmrestore/main.go:64    gracefully shutting down http server for metrics at ":8421"
2023-10-17T07:26:42.564Z    info    VictoriaMetrics/app/vmrestore/main.go:68    successfully shut down http server for metrics in 0.000 seconds
----

Nach der Fertigstellung*(stellen Sie sicher, dass die Sicherung erfolgreich wiederhergestellt wurde*), müssen Sie die Befehle befolgen, die durch den früheren Befehl ausgegeben wurden:

* den Wiederherstellungsauftrag löschen
* die Victoria Metrics-Instanz aufstocken

=== ClickHouse-Sicherungen auflisten

[NOTE]
====
Das folgende Skript benötigt die Berechtigung, den Befehl `+kubectl exec+` auszuführen.
====


Um ClickHouse-Backups aufzulisten, führen Sie den folgenden Befehl aus:

[,bash]
----
./restore/list-clickhouse-backups.sh
----

Die Ausgabe sollte wie folgt aussehen:

[,bash]
----
full_2024-06-17T18-50-00          34.41KiB   17/06/2024 18:50:00   remote                                      tar, regular
incremental_2024-06-17T18-51-00   7.29KiB    17/06/2024 18:51:00   remote   +full_2024-06-17T18-50-00          tar, regular
incremental_2024-06-17T18-54-00   7.29KiB    17/06/2024 18:54:00   remote   +incremental_2024-06-17T18-51-00   tar, regular
incremental_2024-06-17T18-57-00   7.29KiB    17/06/2024 18:57:00   remote   +incremental_2024-06-17T18-54-00   tar, regular
full_2024-06-17T19-00-00          26.41KiB   17/06/2024 19:00:00   remote                                      tar, regular
incremental_2024-06-17T19-00-00   6.52KiB    17/06/2024 19:00:00   remote   +incremental_2024-06-17T18-57-00   tar, regular
incremental_2024-06-17T19-03-00   25.37KiB   17/06/2024 19:03:00   remote   +incremental_2024-06-17T19-00-00   tar, regular
incremental_2024-06-17T19-06-00   7.29KiB    17/06/2024 19:06:00   remote   +incremental_2024-06-17T19-03-00   tar, regular
----

wo gedruckt wird:

* Name, der Name beginnt mit `+full_+` - es handelt sich um eine Vollsicherung, `+incremental_+` - es handelt sich um eine inkrementelle Sicherung
* Größe,
* Erstellungsdatum,
* `+remote+` - eine Sicherung wird auf einen entfernten Speicher wie S3 hochgeladen
* übergeordnetes Backup - wird von inkrementellen Backups verwendet
* Format und Komprimierung

=== Wiederherstellen einer ClickHouse-Sicherung

[CAUTION]
====
*Die Wiederherstellungsfunktion überschreibt die Daten. Alle Tabellen in der Datenbank `+otel+` werden gelöscht und aus der Sicherung wiederhergestellt. Seien Sie vorsichtig, um unerwarteten Datenverlust zu vermeiden.*
====


[NOTE]
====
Das folgende Skript benötigt die Berechtigung, den Befehl `+kubectl exec+` auszuführen.
====


[CAUTION]
====
*Die Wiederherstellung der Funktionalität erfordert das Anhalten aller Produzenten (wie OpenTelemetry-Exporteure). Das Skript skaliert die Workloads vor dem Backup herunter und skaliert die Workloads nach Beendigung des Backups wieder hoch.*
====


Um ein ClickHouse-Backup wiederherzustellen, wählen Sie eine Backup-Version aus und übergeben Sie diese als Parameter in dem folgenden Befehl:

[,bash]
----
./restore/restore-clickhouse-backup.sh incremental_2024-06-17T18-57-00
----

Die Ausgabe sollte wie folgt aussehen:

[,bash]
----
...
2024/06/17 19:14:19.509498  info download object_disks start backup=incremental_2024-06-17T19-06-00 operation=restore_data table=otel.otel_traces_trace_id_ts_mv
2024/06/17 19:14:19.509530  info download object_disks finish backup=incremental_2024-06-17T19-06-00 duration=0s operation=restore_data size=0B table=otel.otel_traces_trace_id_ts_mv
2024/06/17 19:14:19.509549  info done                      backup=incremental_2024-06-17T19-06-00 duration=0s operation=restore_data progress=12/12 table=otel.otel_traces_trace_id_ts_mv
2024/06/17 19:14:19.509574  info done                      backup=incremental_2024-06-17T19-06-00 duration=66ms operation=restore_data
2024/06/17 19:14:19.509591  info done                      backup=incremental_2024-06-17T19-06-00 duration=167ms operation=restore version=2.5.13
2024/06/17 19:14:19.509684  info clickhouse connection closed logger=clickhouse
Data restored
----

=== Elasticsearch-Schnappschüsse auflisten

Um die Elasticsearch-Snapshots aufzulisten, führen Sie den folgenden Befehl aus:

[,bash]
----
./restore/list-elasticsearch-snapshots.sh
----

Die Ausgabe sollte wie folgt aussehen:

[,bash]
----
job.batch/elasticsearch-list-snapshots-20210224t133115 created
Waiting for job to start...
Waiting for job to start...
=== Listing Elasticsearch snapshots in snapshot repository "sts-backup" in bucket "sts-elasticsearch-backup"...
sts-backup-20210219-0300-mref7yrvrswxa02aqq213w
sts-backup-20210220-0300-yrn6qexkrdgh3pummsrj7e
sts-backup-20210221-0300-p481sih8s5jhre9zy4yw2o
sts-backup-20210222-0300-611kxendsvh4hhkoosr4b7
sts-backup-20210223-0300-ppss8nx40ykppss8nx40yk
===
job.batch "elasticsearch-list-snapshots-20210224t133115" deleted
----

Der Zeitstempel, zu dem die Sicherung erstellt wurde, ist Teil des Sicherungsnamens.

=== Elasticsearch-Indizes löschen

[NOTE]
====
Sie können das Flag `+--delete-all-indices+` mit dem Wiederherstellungsskript verwenden, um alle Indizes vor der Wiederherstellung automatisch zu löschen. Weitere Informationen finden Sie unter xref:/setup/data-management/backup_restore/kubernetes_backup.adoc#_restore_an_elasticsearch_snapshot[Wiederherstellen eines Elasticsearch-Snapshots].
====

Um die vorhandenen Elasticsearch-Indizes manuell zu löschen und einen Snapshot wiederherzustellen, gehen Sie folgendermaßen vor:

. Beenden Sie die Indizierung - reduzieren Sie alle Bereitstellungen, die Elasticsearch verwenden, auf 0:
+
[,bash]
----
kubectl scale --replicas=0 deployment -l observability.suse.com/scalable-during-es-restore="true"
----

. Öffnen Sie eine Port-Weiterleitung zum Elasticsearch-Master:
+
[,bash]
----
kubectl port-forward service/suse-observability-elasticsearch-master 9200:9200
----

. Abrufen einer Liste aller Indizes:
+
[,bash]
----
curl "http://localhost:9200/_cat/indices?v=true"
----
+
Die Ausgabe sollte wie folgt aussehen:
+
[,bash]
----
health status index                              uuid                   pri rep docs.count docs.deleted store.size pri.store.size dataset.size
green  open   .ds-sts_k8s_logs-2025.09.28-004619 9p7RZwNCR-aQwInTMr5Bow   3   1   24511032            0        6gb            3gb          3gb
green  open   sts_topology_events-2025.10.01     86I2JZIeRzqWkK1dolHzhg   1   1    1576132            0    111.6mb         55.8mb       55.8mb
green  open   sts_topology_events-2025.10.02     T-bcrok_S1uVPLusQuCMxw   1   1     999748            0     75.2mb         37.6mb       37.6mb
green  open   .ds-sts_k8s_logs-2025.09.30-004653 rwlcAr0sTPe9NaImtJLIiw   3   1   24387607            0        6gb            3gb          3gb
green  open   sts_topology_events-2025.09.10     T0x-qvyUR2-dg4fyvdZIaQ   1   1    1746143            0    131.6mb         65.8mb       65.8mb
----

. Löschen Sie einen Index mit dem folgenden Befehl:
+
[,bash]
----
curl -X DELETE "http://localhost:9200/INDEX_NAME?pretty"
----
+
Ersetzen Sie `+INDEX_NAME+` durch den Namen des zu löschenden Indexes, zum Beispiel:
+
[,bash]
----
curl -X DELETE "http://localhost:9200/sts_internal_events-2021.02.19?pretty"
----

. Die Ausgabe sollte sein:
+
[,javascript]
----
{
"acknowledged" : true
}
----

=== Wiederherstellen eines Elasticsearch-Snapshots

[WARNING]
====
*Wenn ein Snapshot wiederhergestellt wird, werden vorhandene Indizes nicht überschrieben.*

Sie können das `+--delete-all-indices+` Flag verwenden, um alle Indizes automatisch durch das Wiederherstellungsskript zu löschen, oder sie manuell löschen, wie in xref:/setup/data-management/backup_restore/kubernetes_backup.adoc#_delete_elasticsearch_indices[Elasticsearch-Indizes löschen] beschrieben.

====

[WARNING]
====
*Wenn die Elasticsearch `+PersistentVolumes+` neu erstellt wurde* (z.B. durch versehentliches Löschen und anschließenden Pod-Neustart), müssen Sie die Elasticsearch-Backup-Konfiguration mit einer der beiden folgenden Methoden neu erstellen:

* Neuinstallation des SUSE Observability Helm-Diagramms mit der gleichen Konfiguration wie bei der Erstinstallation (OR)
* Manuelles Auslösen der Backup-Initialisierung CronJob:
+
[,bash]
----
kubectl create job --from=cronjob.batch/suse-observability-backup-init "suse-observability-backup-init-$(date +%s)"
----
====
Um einen Elasticsearch-Snapshot wiederherzustellen, wählen Sie einen Snapshot-Namen und übergeben ihn als ersten Parameter. Sie können optional angeben:

* Eine durch Kommata getrennte Liste von Indizes, die wiederhergestellt werden sollen. Wenn nicht angegeben, werden alle Indizes, die mit dem Helm-Wert `+backup.elasticsearch.scheduled.indices+` übereinstimmen, wiederhergestellt. Der Standardwert ist `+"sts*"+`).
* Seit der Version `+2.6.1+` können Sie das Flag "--delete-all-indices" verwenden, um alle vorhandenen Indizes vor der Wiederherstellung automatisch zu löschen.

==== Grundlegende Wiederherstellung

[,bash]
----
./restore/restore-elasticsearch-snapshot.sh \
  sts-backup-20210223-0300-ppss8nx40ykppss8nx40yk
----

==== Wiederherstellung bestimmter Indizes

[,bash]
----
./restore/restore-elasticsearch-snapshot.sh \
  sts-backup-20210223-0300-ppss8nx40ykppss8nx40yk \
  "<INDEX_TO_RESTORE>,<INDEX_TO_RESTORE>"
----

==== Wiederherstellung mit automatischer Indexlöschung

[,bash]
----
./restore/restore-elasticsearch-snapshot.sh \
  sts-backup-20210223-0300-ppss8nx40ykppss8nx40yk \
  --delete-all-indices
----

Wenn Sie das Kennzeichen `+--delete-all-indices+` verwenden, bestätigen Sie die Eingabeaufforderung, um die Aktion fortzusetzen:

[,text]
----
WARNING: All indices will be deleted before restore!
Are you sure you want to continue? (yes/no): yes
=== Starting restore job
job.batch/elasticsearch-restore-20251003t115746 created
=== Restore job started. Follow the logs and clean up the job with the following commands:
kubectl logs --follow job/elasticsearch-restore-20251003t115746
kubectl delete job/elasticsearch-restore-20251003t115746
----

Verfolgen Sie die Protokolle, um den Verlauf der Löschung und Wiederherstellung zu sehen:

[,text]
----
kubectl logs --follow job/elasticsearch-restore-20251003t115746

=== Deleting all indices matching pattern "sts*"...
Found indices to delete:
.ds-sts_k8s_logs-2025.10.03-000007
.ds-sts_k8s_logs-2025.10.03-000004
sts_topology_events-2025.10.02
sts_topology_events-2025.10.03
...
=== All indices deleted successfully
=== Restoring ElasticSearch snapshot "sts-backup-20251003-0925-aby7d1tgs9whvbm6qj04ug" (indices = "sts*") from snapshot repository "sts-backup" in bucket "sts-elasticsearch-backup"...
{
  "snapshot" : {
    "snapshot" : "sts-backup-20251003-0925-aby7d1tgs9whvbm6qj04ug",
    "indices" : [
      ".ds-sts_k8s_logs-2025.10.02-000003",
      "sts_topology_events-2025.10.02",
      "sts_topology_events-2025.10.03"
    ],
    "shards" : {
      "total" : 15,
      "failed" : 0,
      "successful" : 15
    }
  }
}
===
----

Nachdem die Indizes wiederhergestellt worden sind, skalieren Sie alle Bereitstellungen mit Elasticsearch:

[,bash]
----
kubectl scale --replicas=1 deployment -l observability.suse.com/scalable-during-es-restore="true"
----
