= ホスト名のカスタマイズ
:revdate: 2025-09-08
:page-revdate: {revdate}

== {elemental-product-name} ホスト名管理の概要

{elemental-product-name} ISOからホストが起動すると、ホスト名は一時的にDHCPサーバーから提供されたものに設定されます_（transient hostname_）。
DHCPサーバーがホスト名を提供しない場合、{elemental-product-name} ISOは一時的なホスト名を`+rancher-$\{RANDOM}+` の形式で提供します。

ブートプロセスが終了するとすぐに、登録フェーズが開始される。ホストは{elemental-product-name} オペレータに接続し、ホストの`+MachineInventory+` を作成する。
{elemental-product-name} Operatorに登録された各ホストは、`+MachineInventory+` リソースによって追跡される。

*ノードに関連付けられた`+MachineInventory+` リソースの`+name+` は、**最終的にホストに設定される**恒久的な（静的な）ホスト名である*。
この永続的なホスト名は*、K8sクラスタのプロビジョニング段階でのみノードに設定さ*れます。
K8sのプロビジョニングフェーズの前では、ノードのホスト名はDHCPで割り当てられたものか、`+rancher-$\{RANDOM}+` 。

このセクションの残りの部分では、`+hostname+` 、_永続的な_ホスト名、つまりホストがK8sクラスタの一部としてプロビジョニングされた後に設定されるホスト名を意味します。

== デフォルトのホスト名

新しく作成された MachineInventory に割り当てられるデフォルトの名前は、`+m-{$UUID}+` という形式です。
ホストがクラスタの一部としてプロビジョニングされると、その`+m-\{UUID}+` 名が対応するホストのホスト名として設定され、以前に割り当てられていたホスト名 (`+rancher-{$RANDOM}+` または DHCP で割り当てられたもの) を上書きします。

== カスタムホスト名を設定する

ホスト名は xref:references/machineregistration-reference.adoc#_machinename[`+machineName+`]フィールドを設定することができる。

`+machineName+` フィールドに設定されるホスト名は、SMBIOSとハードウェアラベルのデータを使って、登録する各ノードに対して一意に生成されるように、テンプレート形式であることが期待される。

[IMPORTANT]
====
`+MachineRegistration+` リソースの`+machineName+` フィールドは、登録ホストのホスト名だけでなく、そのホストを追跡するために作成された`+MachineInventory+` リソースの名前の設計図としても使用されます。

つまり、同じ`+MachineRegistration+` データ（つまり同じISO）を使ってブートする各ホストに対して一意な名前を生成するような、テンプレート化された`+machineName+` を使わなければ、最初に登録するホストだけが成功し、他のホストは失敗します。`+MachineInventory+` の名前は一意でなければなりません。
====


インポート Registration from "!!raw-loader!@site/examples/quickstart/registration-hardware-dhcphostname.yaml"

== DHCPから割り当てられたホスト名を保持する

ホストがオペレータに登録する前にDHCPサーバーから割り当てられたホスト名を保持するために、`+MachineRegistration+` 。 xref:references/machineregistration-reference.adoc#_machinename[`+machineName field+`]を`+${System Data/Runtime/Hostname}+` ハードウェア・ラベルに設定する必要があります。

こうすることで、{elemental-product-name} は登録段階で現在のホスト名を`+MachineInventory+` 名として使用し、後にプロビジョニング段階でホストの静的ホスト名として設定される。

.ホスト名とMachineInventory名をDHCPサーバーが取得したホスト名に設定した登録例
[,yaml]
----
include::example$quickstart/registration-hardware-dhcphostname.yaml[]
----
