= Recursos
:revdate: 2026-03-05
:page-revdate: {revdate}

Esta seção descreve os recursos e os estágios dos recursos em {product_name}.

== Lista de recursos

|===
| Recurso | Nome do recurso do timão | Sub-recurso | Padrão | Estágio 

| *Provedor de complemento para frota*
| `+addon-provider-fleet+`
| _Nenhum_
| habilitado
| beta

| *Modo TLS do agente*
| `+agent-tls-mode+`
| _Nenhum_
| habilitado
| beta

| *Não há gerente de certificados*
| `+no-cert-manager+`
| _Nenhum_
| habilitado
| beta

| *Usar o registro padrão do Rancher*
| `+use-rancher-default-registry+`
| _Nenhum_
| habilitado
| beta

|===

=== Provedor de complemento para frota
Esse recurso instala o Cluster API Add-on Provider for Fleet (CAAPF) para fornecer integração com o https://github.com/rancher/fleet[Fleet] e permitir a fácil implementação de aplicativos em clusters provisionados pelo CAPI. O CAAPF instala automaticamente o Fleet no cluster de gerenciamento e registra os clusters CAPI recém-provisionados com o Fleet, para que os aplicativos possam ser implantados nesses clusters por meio de recursos do GitOps, `+Bundle+` ou `+HelmOp+`. O CAAPF também inclui suporte ao agrupamento de clusters CAPI que fazem referência à mesma ClusterClass por meio do ClusterGroup do Fleet, simplificando essencialmente as implementações de aplicativos em grandes grupos de clusters. Esse recurso está no estágio GA e é ativado por padrão.

=== Modo TLS do agente
Essa porta de recurso é usada para instruir o Turtles sobre se ele deve seguir a configuração `+agent-tls-mode+` do Rancher ao recuperar manifestos de registro de cluster para importar clusters. Quando ativado, o Turtles pesquisará o valor da configuração `+agent-tls-mode+` do Rancher para determinar se ele foi definido como `+system-store+` ou `+strict+`. Se definido como `+system-store+`, o Turtles confiará em qualquer certificado gerado por uma Autoridade de Certificação pública contida no armazenamento de confiança do sistema operacional, incluindo aqueles assinados por autoridades como a Let's Encrypt. Se definido como `+strict+`, o Turtles só confiará em certificados gerados pela Autoridade de Certificação contida na configuração `+cacerts+` do Rancher. Quando essa configuração estiver desativada, o Turtles voltará a funcionar no modo `+system-store+`. Esse recurso está em fase beta e é ativado por padrão.

=== Não há gerente de certificados
Esse portão de recursos converte os manifestos dos provedores de CAPI para substituir o uso do cert-manager pelo https://github.com/rancher/wrangler/[] wrangler.

Em particular, os webhooks de admissão de validação e mutação serão atualizados para usar certificados gerados pelo wrangler, em vez do cert-manager, permitindo um ambiente livre de cert-manager.

Observe que o uso da do Rancher `+CATTLE_SYNC_ONLY_CHANGED_OBJECTS+` https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/best-practices/tuning-rancher-at-scale.html#_reducing_event_handler_executions[funcionalidade] pode impedir que os certificados sejam renovados após o tempo de expiração padrão de um ano.

É possível desativar esse recurso para restaurar todos os manifestos do provedor para o uso original do cert-manager.

=== Usar o registro padrão do Rancher

Esse portão de recurso instrui o site {product_name} a aproveitar a configuração de gerenciamento `+system-default-registry+` do Rancher ao criar referências de imagem para componentes do provedor CAPI. Quando ativado, o site {product_name} lê essa configuração e, se houver um registro configurado, reescreve o repositório de cada imagem de provedor para usar esse registro.
Se a configuração estiver vazia, o site {product_name} voltará a usar as referências de imagem padrão. As substituições de imagem definidas no recurso `+ClusterctlConfig+` sempre têm precedência. Para obter informações detalhadas sobre o uso em ambientes com ar comprimido, consulte xref:operator/airgapped.adoc[Ambiente com ar comprimido]. Esse recurso está em fase alfa e é ativado por padrão.

== Estágios dos recursos

{product_name} segue o processo de do Kubernetes https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages[estágios de recursos]. Um recurso pode estar em um dos seguintes estágios: Alfa, Beta ou Disponibilidade geral (GA).

=== Estágio Alfa
- Desativado por padrão.
- Pode apresentar bugs, sem suporte de longo prazo.
- A API pode ser alterada sem aviso prévio.
- Recomendado apenas para clusters de teste de curta duração.

=== Fase Beta
- Sempre ativado por padrão.
- Bem testado e considerado seguro.
- O suporte é estável, mas o esquema pode mudar em versões futuras.
- Recomendado para usos não críticos para os negócios devido a possíveis mudanças incompatíveis.

[NOTE]
====
Dê seu feedback sobre os recursos Alfa e Beta!
====

=== Estágio de disponibilidade geral (GA)
- Sempre ativado, não pode ser desativado.
- Não é necessário um portão de recursos.
- Estável, com suporte de longo prazo em versões futuras.