= Glossário
:revdate: 2025-11-14
:page-revdate: {revdate}

== Índice

[cols=14*]
|===
| xref:./glossary.adoc#_a[A]
| xref:./glossary.adoc#_b[B]
| xref:./glossary.adoc#_c[C]
| xref:./glossary.adoc#_f[F]
| xref:./glossary.adoc#_i[I]
| xref:./glossary.adoc#_k[K]
| xref:./glossary.adoc#_m[M]
| xref:./glossary.adoc#_n[N]
| xref:./glossary.adoc#_o[O]
| xref:./glossary.adoc#_p[P]
| xref:./glossary.adoc#_r[R]
| xref:./glossary.adoc#_s[S]
| xref:./glossary.adoc#_t[T]
| xref:./glossary.adoc#_w[W]
|===

== A

=== Complementos

Serviços além dos componentes fundamentais necessários para implantar um cluster em conformidade com o Kubernetes e categorizados em dois tipos:

* *Complementos principais*: Complementos necessários para implantar um cluster em conformidade com o Kubernetes: DNS, kube-proxy, CNI.
* *Complementos adicionais*: Complementos que não são necessários para um cluster em conformidade com o Kubernetes (por exemplo, metrics/Heapster, Dashboard).

=== Ambiente com porta de ar

Configuração e execução de clusters do Kubernetes sem acesso direto à Internet.

== B

=== Bootstrap

O processo de transformar um servidor em um nó do Kubernetes. Isso pode envolver a montagem de dados a serem fornecidos ao criar o servidor que faz o backup da máquina, bem como a configuração do tempo de execução do software executado nesse servidor.

=== Cluster de bootstrap

Um cluster temporário que é usado para provisionar um cluster do Target Management.

=== Provedor de bootstrap

Refere-se a um <<_provider,provedor>> que implementa uma solução para o processo de <<_bootstrap,bootstrap>>.

== C

=== CAPI

API do cluster principal

=== CAPA

Provedor de API de cluster AWS

=== CAPD

Provedor de API de cluster Docker

=== CAPG

API de cluster Google Cloud Provider

=== CAPIO

Operador de API de cluster

=== CAPRKE2

Provedor de API de cluster RKE2. Para obter informações detalhadas sobre o CAPRKE2, consulte a documentação https://caprke2.docs.rancher.com[aqui].

=== CAPV

Provedor de API de cluster vSphere

=== CAPZ

Provedor de API de cluster do Azure

=== Provedor de CAPI

Uma API pública que facilita o provisionamento e as operações sobre os recursos do <<_cluster_api_operator,Operador CAPI>> e da <<_cluster_api,API do cluster>>.

=== Grupo de crianças

Termo comumente usado de forma intercambiável com o <<_workload_cluster,cluster de carga de trabalho>>.

=== Grupo

Uma implantação completa do Kubernetes. Consulte Cluster de gerenciamento e Cluster de carga de trabalho.

=== ClusterClass

Uma coleção de modelos que definem uma topologia (plano de controle e trabalhadores) a ser usada para reconciliar continuamente um ou mais clusters.
Consulte xref:../user/clusterclass.adoc[ClusterClass]

=== API de cluster

Ou *projeto de API de cluster*

A API do cluster é um subprojeto do SIG-cluster-lifecycle. Também é usado para se referir aos componentes de software, às APIs e à comunidade que os produz.

Ver <<_core_provider,provedor principal>>

=== Operador de API de cluster

Ou *projeto de operador de API de cluster*

O operador da API de cluster é um subprojeto do SIG-cluster-lifecycle. Ele foi projetado para capacitar os administradores de cluster a lidar com o ciclo de vida dos provedores de API de cluster em um cluster de gerenciamento usando uma abordagem declarativa.

=== Provedor de API de cluster RKE2

<<_caprke2,O provedor de API de cluster RKE2>> é uma combinação de dois tipos de provedor: um provedor de plano de controle de API de cluster para provisionar nós do plano de controle do Kubernetes e um provedor de bootstrap de API de cluster para inicializar o Kubernetes em uma máquina em que <<_rke2,o RKE2>> é usado como a distribuição do Kubernetes.

=== Plano de controle

O conjunto de serviços do Kubernetes que formam a base de um cluster. Consulte também https://kubernetes.io/docs/concepts/#_kubernetes-control-plane Há duas variantes:

* *Auto-provisionado*: Um plano de controle do Kubernetes que consiste em pods ou máquinas totalmente gerenciados por uma única implantação da API de cluster.
* *Externo* ou *gerenciado*: Um plano de controle oferecido e controlado por algum sistema que não seja a API do cluster (por exemplo, GKE, AKS, EKS, IKS).

=== Provedor de plano de controle

Refere-se a um <<_provider,provedor>> que implementa uma solução para o gerenciamento de um <<_control_plane,plano de controle>> do Kubernetes.

Consulte <<_caprke2,CAPRRKE2>>, <<_kcp,KCP>>.

=== Provedor principal

Refere-se a um <<_provider,provedor>> que implementa os controladores principais da API de cluster; se você considerar que o primeiro projeto que deve ser implantado em um cluster de gerenciamento é a própria API de cluster, deve ficar claro por que o projeto da API de cluster também é chamado de provedor principal.

Consulte <<_cluster_api,CAPI>>.

== F

=== Frota

ifeval::["{build-type}" == "product"]
Um mecanismo de gerenciamento e implantação de contêineres projetado para oferecer aos usuários mais controle sobre o cluster local e monitoramento constante por meio do GitOps. Dê uma olhada na https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/index.html/[documentação do] para saber mais sobre o Fleet.
endif::[]
ifeval::["{build-type}" == "community"]
Um mecanismo de gerenciamento e implantação de contêineres projetado para oferecer aos usuários mais controle sobre o cluster local e monitoramento constante por meio do GitOps. Dê uma olhada na https://fleet.rancher.io/[documentação do] para saber mais sobre o Fleet.
endif::[]

== I

=== Provedor de infraestrutura

Refere-se a um <<_provider,provedor>> que implementa o provisionamento de recursos de infraestrutura/computacionais exigidos pelo cluster ou por máquinas (por exemplo, VMs, rede etc.).
Os provedores de infraestrutura em nuvem incluem AWS, Azure ou Google, enquanto VMware, MAAS ou metal3.io podem ser definidos como provedores bare metal.

=== Provedor de IPAM

Refere-se a um <<_provider,provedor>> que permite que a API do cluster interaja com as soluções IPAM.
A interação do provedor do IPAM com a API do cluster é baseada nos tipos de API `+IPAddressClaim+` e `+IPAddress+`.

== K

=== Kubernetes-conformant

Ou *compatível com Kubernetes*

Um cluster que passa nos testes de conformidade do Kubernetes.

=== Operador de Kubernetes

Um Operador do Kubernetes é um método de empacotamento, implantação e gerenciamento de um aplicativo do Kubernetes. Consulte também https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ para obter mais informações.

=== k/k

Refere-se ao https://github.com/kubernetes/kubernetes[repositório git principal do Kubernetes] ou ao projeto principal do Kubernetes.

=== KCP

Provedor de plano de controle do Kubeadm

== M

=== Máquina

Ou *recurso de máquina*

O recurso personalizado do Kubernetes que representa um componente de infraestrutura que hospeda um nó do Kubernetes.

=== Gerenciar um cluster

Executar operações de criação, dimensionamento, upgrade ou destruição no cluster.

=== Kubernetes gerenciado

Kubernetes gerenciado refere-se a qualquer abstração de provisionamento e manutenção de cluster do Kubernetes, geralmente exposta como uma API, que está nativamente disponível em um provedor de nuvem. Por exemplo: https://aws.amazon.com/eks/[EKS], https://www.oracle.com/cloud/cloud-native/container-engine-kubernetes/[OKE], https://azure.microsoft.com/en-us/products/kubernetes-service[IBM Cloud Kubernetes Service] AKS, https://cloud.google.com/kubernetes-engine[DOKS] GKE, https://www.ibm.com/cloud/kubernetes-service[], https://www.digitalocean.com/products/kubernetes[] e muitos outros em todo o ecossistema Kubernetes Cloud Native.

=== Topologia gerenciada

Consulte <<_topology,Topologia>>

=== Cluster de gerenciamento

O cluster onde um ou mais provedores de infraestrutura são executados e onde os recursos (por exemplo, máquinas) são armazenados. Normalmente, é usado quando você está provisionando vários clusters de carga de trabalho.

== N

=== Piscinas de nós

Um pool de nós é um grupo de nós em um cluster que têm a mesma configuração.

== O

=== Sistema operacional

Ou *sistema operacional*

Uma combinação genericamente compreendida de um kernel e de uma interface de espaço de usuário no nível do sistema, como Linux ou Windows, em oposição a uma distribuição específica.

== P

=== Pivô

Pivotar é um processo para mover os componentes do provedor e os recursos declarados de API de cluster de um cluster de gerenciamento de origem para um cluster de gerenciamento de destino.

O processo de pivô também é usado para excluir um cluster de gerenciamento e também pode ser usado durante um upgrade do cluster de gerenciamento.

=== Provedor

Ou *provedor de API de cluster*

Esse termo foi originalmente usado como abreviação de <<_infrastructure_provider,provedor de infraestrutura>>, mas atualmente é usado para se referir a qualquer projeto que possa ser implantado e forneça funcionalidade ao Cluster de gerenciamento da API do Cluster.

Consulte <<_bootstrap_provider,Provedor de bootstrap>>, Provedor <<_control_plane_provider,de plano de controle>>, Provedor <<_core_provider,principal>>, Provedor<<_infrastructure_provider,de infraestrutura>>, Provedor <<_ipam_provider,de IPAM>>, Provedor <<_runtime_extension_provider,de extensão de tempo de execução>>.

=== Componentes do provedor

Refere-se ao artefato YAML publicado como parte do processo de liberação de <<_provider,provedores>>; geralmente inclui CRDs (Custom Resource Definitions), implementações (para executar o gerenciador de controladores), RBAC etc.

Em alguns casos, a mesma expressão é usada para se referir às instâncias dos componentes acima implementados em um cluster de gerenciamento.

Consulte <<_provider_repository,Repositório do provedor>>

=== Repositório do provedor

Refere-se ao local em que o YAML dos <<_provider_components,componentes do provedor>> está hospedado; normalmente, um repositório de provedor hospeda várias versões de componentes do provedor, uma para cada versão lançada.

== R

=== Fazendeiro

Uma de código aberto https://www.rancher.com/[plataforma] projetada para simplificar a implantação e o gerenciamento de clusters do Kubernetes.

=== Agente de cluster do Rancher

Um componente implantado pelo Rancher em cada cluster do Kubernetes que ele gerencia. Sua função principal é estabelecer um canal de comunicação seguro entre o servidor Rancher e o cluster Kubernetes, permitindo que o Rancher gerencie e interaja com o cluster.

=== Gerente de Rancheiro

O Rancher Manager (ou Rancher Server) é onde a interface do usuário e a API do Rancher estão hospedadas e se comunica com os clusters gerenciados por meio de componentes como o <<_rancher_cluster_agent,Rancher Cluster Agent>>. Ele permite que os usuários gerenciem seus clusters do Kubernetes, aplicativos e recursos específicos do Rancher, como catálogos, usuários, funções globais e muito mais.

=== RKE2

ifeval::["{build-type}" == "product"]
A distribuição Kubernetes de última geração e totalmente compatível da Rancher que se concentra em segurança e conformidade nos EUA. Setor do governo federal. Consulte https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html[a documentação do site] para obter mais detalhes.
endif::[]
ifeval::["{build-type}" == "community"]
A distribuição Kubernetes de última geração e totalmente compatível da Rancher que se concentra em segurança e conformidade nos EUA. Setor do governo federal. Consulte https://docs.rke2.io/[a documentação do site] para obter mais detalhes.
endif::[]

=== Extensão de tempo de execução

Um componente externo que faz parte de um sistema criado com base na API do cluster que pode lidar com solicitações de um Hook de tempo de execução específico.

=== Provedor de extensão de tempo de execução

Refere-se a um <<_provider,provedor>> que implementa uma ou mais <<_runtime_extension,extensões de tempo de execução>>.

== S

=== Dimensionamento

A menos que especificado de outra forma, isso se refere à escala horizontal.

=== Plano de controle empilhado

Um nó do plano de controle em que o etcd é colocado com o servidor de API do Kubernetes e é executado como um pod estático.

=== Servidor

A infraestrutura que faz o backup de um <<_machine,recurso de máquina>>, geralmente uma instância de nuvem, uma máquina virtual ou um host físico.

=== {product_name}

Um <<_kubernetes_operator,operador de Kubernetes>> que fornece integração entre o Rancher Manager e a API de cluster (CAPI) com o objetivo de trazer suporte completo de CAPI para o Rancher.

== T

=== Topologia

Um campo na especificação de objeto do Cluster que permite definir e gerenciar a forma do plano de controle do Cluster e das máquinas de trabalho a partir de um único ponto de controle. A topologia do cluster é baseada em uma <<_clusterclass,ClusterClass>>.
Às vezes, ela também é chamada de topologia gerenciada.

Consulte <<_clusterclass,ClusterClass>>

ifeval::["{build-type}" == "product"]
=== Tartarugas

Refere-se a <<_suse_rancher_prime_cluster_api,{product_name}>>
endif::[]

ifeval::["{build-type}" == "community"]
=== Tartarugas

Refere-se a <<_rancher_turtles,{product_name}>>
endif::[]

== W

=== Cluster de carga de trabalho

Um cluster criado por um controlador ClusterAPI, que _não_ é um cluster bootstrap e deve ser usado por usuários finais, e não por ferramentas CAPI.

=== Classe de trabalhador

Uma coleção de modelos que definem um conjunto de nós de trabalho no cluster. Uma ClusterClass contém zero ou mais definições de WorkerClass.

Consulte <<_clusterclass,ClusterClass>>
