include::partial$variables.adoc[]

= ArgoCD 安装
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: ArgoCD 安装
:sidebar_position: 35
:description: 通过为证书的安全创建和更新设置特定的配置选项，配置您的 ArgoCD 应用程序以有效管理 Kubernetes 资源。
:keywords: ["{project-name}", gitops, argocd]
:doc-persona: [kubewarden-operator]
:doc-type: [howto]
:doc-topic: [argocd-installation]

如果使用 ArgoCD 管理 Kubernetes 资源，则可能需要使用 ArgoCD 安装{project-name} 。这是可能的，但也有一些考虑因素。自{short-project-name} v1.17.0 起，删除了对 cert-manager 的依赖。有一个新的证书调节器可以自动更新证书。这意味着{short-project-name} 控制器会为您创建和更新证书。这包括根 CA 和所有 webhook 证书。

初始根 CA 和网络钩子证书的创建是在 Helm 图表安装过程中使用可用的 Helm 功能进行的。因此，在渲染 Helm 图表时，安装程序会检查是否已创建证书，如果没有，就会创建证书。

这就给 ArgoCD 的使用带来了问题，因为它只使用 Helm 来渲染模板，而所有的资源生命周期管理都由 ArgoCD 负责。每当 ArgoCD 渲染 Helm 图表以检查群集应用程序是否偏离图表定义时，它都会再次尝试创建证书。因此，它会将存储证书和 webhook 配置的机密标记为不同步。

要解决这个问题，有必要对 ArgoCD 应用程序进行配置，使其忽略：

* `+data+` 领域的秘密
* 中的`+caBundle+` 字段。 `+MutatingWebhookConfiguration+`
* `+ValidatingWebhookConfiguration+` 资源

为此，您可以在 ArgoCD 应用程序中添加`+ignoreDifferences+` 字段：

[subs="+attributes", yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewarden-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kubewarden.io
    chart: kubewarden-crds
    targetRevision: 1.13.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewarden-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewarden-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kubewarden.io
    chart: kubewarden-controller
    targetRevision: 4.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewarden-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     # Sync options which modifies sync behavior
      # When syncing changes, respect fields ignored by the ignoreDifferences configuration
      - RespectIgnoreDifferences=true
  # ignoreDifferences is the important configuration to avoid ArgoCD marking
  # the secrets and # webhook configurations as unsynchronized
  ignoreDifferences:
  - group: ""
    kind: "Secret"
    name: kubewarden-ca
    namespace: kubewarden-system
    jsonPointers:
      - /data
  - group: ""
    kind: "Secret"
    name: kubewarden-webhook-server-cert
    namespace: kubewarden-system
    jsonPointers:
      - /data
  - group: ""
    kind: "Secret"
    name: kubewarden-audit-scanner-client-cert
    namespace: kubewarden-system
    jsonPointers:
      - /data
  - group: "admissionregistration.k8s.io"
    kind: "MutatingWebhookConfiguration"
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  - group: "admissionregistration.k8s.io"
    kind: "ValidatingWebhookConfiguration"
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewarden-defaults
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kubewarden.io
    chart: kubewarden-defaults
    targetRevision: 2.8.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewarden-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
----

[NOTE]
====

在示例中，关键是{short-project-name} 控制器应用的`+ignoreDifferences+` 配置。其余内容将介绍如何配置 ArgoCD 应用程序，并提供一个完整的示例。

====
