include::partial$variables.adoc[]
= 配置政策
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 通过选择特定命名空间或设置自定义拒绝信息来配置策略，并使用 AdmissionPolicyGroup 否定结果。
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "policies"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "policies", "ClusterAdmissionPolicies", "AdmissionPolicies", "configuration", "namespaces"]
:sidebar_label: 配置政策
:sidebar_position: 90
:current-version: {page-origin-branch}

== 跳过特定策略的命名空间

默认情况下，策略适用于`+PolicyServer+` 配置的所有命名空间。
如果希望策略只针对特定命名空间，可以在每个命名空间部署多个`+AdmissionPolicies+` 。

另一种方法是通过设置`+spec.namespaceSelector+` 来配置`+ClusterAdmissionPolicies+` （参见xref:reference/CRDs.adoc#clusteradmissionpolicy[CRD 文档]）。`+spec.namespaceSelector+` 会根据对象的命名空间是否与选择器匹配，决定是否在该对象上运行策略。

例如，这里有一个只针对`+kube-system+` 和`+my-namespace+` 命名空间的策略：

[subs="+attributes",yaml]
----
---
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-privileged-namespaces
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v1.0.3
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["namespaces"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: In
        values: [kube-system, my-namespace]
  settings:
    modes:
      enforce: "privileged"
----

下面是一个针对除`+kube-system+` 和`+my-namespace+` 之外的所有命名空间的策略：

[subs="+attributes",yaml]
----
---
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-default-mode
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v1.0.3
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["namespaces"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: NotIn
        values: [kube-system, my-namespace]
  settings:
    modes:
      enforce: "restricted"
----

== 自定义拒绝信息

当策略拒绝资源时，显示给用户的信息就是策略作者编写的信息。有时，群组操作员可能希望设置自定义的拒绝信息。例如，可用于指向内部维基或提供更具体的错误代码。

`+ClusterAdmissionPolicy+` 和`+AdmissionPolicy+` 类型中的`+message+` 字段可用于实现这一目的。

[NOTE]
====
`+ClusterAdmissionPolicyGroup+` 和`+AdmissionPolicyGroup+` 已有一个`+message+` 字段，其行为方式相同。
====

`+message+` 字段允许群集操作员定义自定义拒绝信息，以覆盖策略返回的信息。使用此配置时，可在响应的`+causes+` 字段中找到原始拒绝信息。

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: pod-privileged-with-message
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:1.0.2
  policyServer: default
  mode: protect
  message: "Nops! You cannot do that"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

您可以通过提高 kubectl 的冗长程度来获取被拒绝的接纳请求的全部详细信息：

[subs="verbatim,attributes"]
----
$ kubectl -v4 run pod-privileged2 --image=registry.k8s.io/pause --privileged
I0612 16:32:43.647601   48424 cert_rotation.go:137] Starting client certificate rotation controller
I0612 16:32:43.662550   48424 helpers.go:246] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "admission webhook \"clusterwide-pod-privileged-with-message.kubewarden.admission\" denied the request: Nops! You cannot do that",
  "details": {
    "causes": [
      {
        "message": "Privileged container is not allowed"
      }
    ]
  },
  "code": 400
}]
----

== 用策略组包装策略结果，从而否定策略结果

有时，在使用策略时，它还不能实现你所需要的反向逻辑。

例如，您想使用 link:https://artifacthub.io/packages/kubewarden/priority-class-policy/priority-class-policy[`+priority-class+`policy] 拒绝一组优先级类别。但在撰写本文时，`+priority-class+` 策略只支持 allowlists，不支持 denylist。

常见的模式是在`+AdmissionPolicyGroup+` 或`+ClusterAdmissionPolicyGroup+` 中封装策略，并在`+spec.expression+` 中否定策略的结果。

例如，假设我们希望用户使用群集内部定义的所有优先级，但以下优先级除外：`+low-priority+`,`+med-priority+` 和`+high-priority+` 。

目前，策略设置只允许表达允许的优先级列表。以下组策略克服了这一限制。

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: AdmissionPolicyGroup
metadata:
  name: priority-class-denylist
  namespace: your-namespace # or use a CLusterAdmissionPolicyGroup and set spec.namespaceSelector
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["replicationcontrollers"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["batch"]
      apiVersions: ["v1"]
      resources: ["jobs", "cronjobs"]
      operations: ["CREATE", "UPDATE"]
  policies:
    is_a_denied_priority_class:
      module: ghcr.io/kubewarden/policies/priority-class-policy:v1.0.4
      settings:
        allowed_priority_classes:
          - low-priority
          - med-priority
          - high-priority
  expression: "!is_a_denied_priority_class()" # negated result
  message: "the Pod is using a priorityClass that is not allowed"
----