= エアギャップ設置
:page-languages: [en、ja、ko、zh]。
:revdate: 2026-03-03
:page-revdate: {revdate}

このガイドでは、3つのステップでK3をエアギャップ環境に設置する方法を説明します。

[IMPORTANT]
====
Prime Artifacts URLに記載されているK3s Primeバージョンは、このステップで紹介するアセットに使用できます。Prime Artifacts URLの詳細については、https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime専用ドキュメントを]ご覧ください。認証が必要である。https://scc.suse.com/home[SUSE Customer Center(SCC)の]認証情報を使用してログインします。
====

== 画像を読み込む

それぞれの画像ロード方法には異なる要件があり、異なるエアギャップ・シナリオに適している。インフラとセキュリティ要件に最も適した方法を選択する。

[tabs,sync-group-id=airgap-load-images]
======
プライベート・レジストリ方式::
+
--
これらの手順は、すでにエアギャップ環境にノードを作成し、バンドルされているcontainerdをコンテナー・ランタイムとして使用し、環境内でOCI準拠のプライベート・レジストリーが利用可能であることを前提としている。

プライベートDockerレジストリをまだセットアップしていない場合は、https://docs.docker.com/registry/deploying/#run-an-externally-accessible-registry[公式レジストリのドキュメントを]参照してください。

[#_create_the_registry_yaml_and_push_images]
[pass]
<h3><a class="anchor" id="_create_the_registry_yaml_and_push_images" href="#_create_the_registry_yaml_and_push_images"></a>レジストリYAMLの作成とイメージのプッシュ</h3>


. https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL]ページから、実行するK3sのバージョンに対応するアーキテクチャのイメージアーカイブを取得します。
. `+docker image load k3s-airgap-images-amd64.tar.zst+` を使って tar ファイルから docker にイメージをインポートする。
. `+docker tag+` と`+docker push+` を使って、読み込んだ画像をリタグし、プライベートレジストリにプッシュします。
. xref:installation/private-registry.adoc[プライベートレジストリ設定]ガイドに従って、`+registries.yaml+` ファイルを作成し、設定する。
. 以下の<<_install_k3s,K3sのインストール>>セクションに進んでください。
--

手動でイメージを配置する方法::
+
--
これらの手順は、エアギャップ環境ですでにノードを作成しており、コンテナ・ランタイムとしてバンドルされているcontainerdを使用しており、プライベート・レジストリを使用できない、または使用したくないことを前提としている。

この方法は、各ノードに必要なイメージを手動でデプロイする必要があり、プライベートレジストリを実行するのが現実的でないエッジデプロイメントに適している。

[#_prepare_the_images_directory_and_airgap_image_tarball]
[pass]
<h3><a class="anchor" id="_prepare_the_images_directory_and_airgap_image_tarball" href="#_prepare_the_images_directory_and_airgap_image_tarball"></a>ImagesディレクトリとAirgap Image Tarballの準備</h3>

. インターネットにアクセス可能なマシンで、https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL]ページから、インストールするK3sのバージョンのイメージアーカイブをダウンロードしてください。例えば、こうだ：
+
[,bash]
----
curl -L -o k3s-airgap-images-amd64.tar.zst "<PRIME-ARTIFACTS-URL>/k3s/v1.35.1%2Bk3s1/k3s-airgap-images-amd64.tar.zst"
----

. 画像アーカイブをエアギャップノードに転送する。例えば、エージェントのイメージディレクトリに置いてください：
+
[,bash]
----
sudo mkdir -p /var/lib/rancher/k3s/agent/images/
sudo curl -L -o /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.zst ""https://github.com/k3s-io/k3s/releases/download/v1.33.1%2Bk3s1/k3s-airgap-images-amd64.tar.zst"
sudo cp k3s-airgap-images-amd64.tar.zst /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.zst
----

. 以下の<<_install_k3s,K3sのインストール>>セクションに進んでください。
 
[#_enable_conditional_image_imports]
[pass]
<h3><a class="anchor" id="_enable_conditional_image_imports" href="#_enable_conditional_image_imports"></a>条件付き画像インポートを有効にする</h3>

[IMPORTANT]
.バージョン・ゲート
====
条件付き画像のインポートは、2025年5月のリリースで利用可能です：v1.33.1+k3s1、v1.32.5+k3s1、v1.31.9+k3s1、v1.30.13+k3s1。
====

画像アーカイブはk3sが起動するたびにインポートされます。これは、前回の起動以降に一部の画像が削除されたり刈り込まれたとしても、すべての画像が一貫して利用可能であることを保証するために行われる。ただし、すべてのアーカイブが処理されるまでkubeletが起動しないため、起動が遅れます。この遅延を軽減するために、再起動をまたいでも、最後にインポートしたときから変更されたtarballだけをインポートするオプションがある。

この機能を有効にするには、imagesディレクトリに`+.cache.json+` ：

[,bash]
----
touch /var/lib/rancher/k3s/agent/images/.cache.json
----

キャッシュファイルは、ファイルが処理されるときにアーカイブのメタデータを保存する。アーカイブのサイズと更新時間が変わらない限り、K3sを再起動しても画像はインポートされません。

[WARNING]
====
この機能が有効な場合、k3sが起動するたびにすべての画像が利用可能であることを保証することはできません。前回の起動以降に画像が削除されたり刈り込まれたりした場合は、手動で画像を再インポートしてください。どちらかだ：

* `+ctr image import+` を使って手動でアーカイブをインポートする。
* `+touch+` を使って、画像を含むアーカイブのタイムスタンプを変更する。
* `+.cache.json+` ファイルの内容をクリアし、k3s を再起動する。
====
--

埋め込みレジストリミラー::
+
--
K3sには、分散OCI準拠のレジストリミラーが組み込まれています。
有効にして適切に設定すると、任意のノードのcontainerdイメージストアで利用可能なイメージは、外部のイメージレジストリにアクセスすることなく、他のクラスタメンバーから引き出すことができる。

ミラー化されたイメージは、アップストリーム・レジストリ、レジストリのミラー、またはairgapイメージのtarballから取得することができる。
埋め込み分散レジストリのミラーを有効にする方法の詳細については、xref:installation/registry-mirror.adoc[埋め込みレジストリのミラーの]ドキュメントを参照してください。
--
======

[#_install_k3s]
== K3を設置する

=== 前提条件

K3sをインストールする前に、上記のxref:#_load_images[Load Images]オプションのいずれかを選択し、K3sのインストールに必要なイメージを事前に入力してください。

==== バイナリとスクリプトをダウンロードする

* https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL]ページからK3sのバイナリをダウンロードし、エアギャップ画像の取得に使用したものと同じバージョンに合わせる。エアギャップされた各ノードの`+/usr/local/bin+` にバイナリを置き、実行可能であることを確認する。
+
[,bash]
----
sudo curl -Lo /usr/local/bin/k3s <PRIME-ARTIFACTS-URL>/k3s/v1.35.1%2Bk3s1/k3s
sudo chmod +x /usr/local/bin/k3s
----

* https://get.k3s.io[get.k3s.ioから]K3sインストールスクリプトをダウンロードしてください。各エアギャップ・ノード上の任意の場所にインストール・スクリプトを配置し、名前を`+install.sh+` とします。
+
[,bash]
----
curl -Lo install.sh https://get.k3s.io
chmod +x install.sh
----

.**デフォルト・ネットワーク・ルートの設定**- デフォルト・ルートのないノードに必要
[%collapsible]
======
ノードにデフォルトルートを持つインターフェイスがない場合、デフォルトルートを設定する必要があります。ダミーインターフェイス経由のブラックホールルートでも十分です。K3sは、ノードのプライマリIPを自動検出し、kube-proxy ClusterIPルーティングを正しく機能させるために、デフォルトルートを必要とします。ダミールートを追加するには、以下のようにする：

[,bash]
----
ip link add dummy0 type dummy
ip link set dummy0 up
ip addr add 203.0.113.254/31 dev dummy0
ip route add default via 203.0.113.255 dev dummy0 metric 1000
----
======

.**SELinux RPMのダウンロード**- SELinuxが有効なairgappedノードに必要です。
[%collapsible]
======
SELinuxが有効なair-gappedノードで実行する場合は、K3sをインストールする前にk3s-selinux RPMを手動でインストールする必要があります。このRPMには、K3が正しく動作するために必要なSELinuxポリシーが含まれています。RPMの最新版はhttps://github.com/k3s-io/k3s-selinux/releases/latest[] 。例えば、CentOS 8の場合：

[,bash]
----
# On an internet accessible machine:
curl -LO https://github.com/k3s-io/k3s-selinux/releases/download/v1.6.stable.1/k3s-selinux-1.6-1.el8.noarch.rpm

# Transfer RPM to air-gapped machine
sudo yum install ./k3s-selinux-1.6-1.el8.noarch.rpm
----

k3s-selinux RPMのインストールには、以下の依存関係がOSで利用可能であることが必要です：

* container-selinux
* ポリシーコアユーティル
* selinux-ポリシー

詳しくはxref:advanced.adoc#_selinux_support[SELinuxの]セクションを参照のこと。
======

=== インストールスクリプトの実行

以下に説明するように、1台または複数のサーバーにK3sをインストールすることができます。

[tabs,sync-group-id=airgap-install]
======
単一サーバー構成::
+
--
K3sを1台のサーバーにインストールするには、サーバー・ノード上で次の操作を行うだけです：

[,bash]
----
INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh
----

エージェントを追加するには、各エージェントノードで以下を実行します：

[,bash]
----
INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://<SERVER_IP>:6443 K3S_TOKEN=<YOUR_TOKEN> ./install.sh
----
--

高可用性構成::
+
--
xref:datastore/ha.adoc[外部DBによる高可用性]またはxref:datastore/ha-embedded.adoc[組み込みDBによる高可用性]ガイドを参照してください。`+INSTALL_K3S_SKIP_DOWNLOAD=true+` 、curl経由ではなくローカルでインストールスクリプトを実行するように、インストールコマンドを調整することになる。また、`+INSTALL_K3S_EXEC='args'+` 、k3sに引数を与える。

例えば、『High Availability with an External DB』ガイドのステップ2では、次のように述べられている：

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server \
  --token=SECRET \
  --datastore-endpoint="mysql://username:password@tcp(hostname:3306)/database-name"
----

その代わりに、このような例を以下のように修正する：

[,bash]
----
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server --token=SECRET' \
K3S_DATASTORE_ENDPOINT='mysql://username:password@tcp(hostname:3306)/database-name' \
./install.sh
----
--
======

[NOTE]
====
K3sの`+--resolv-conf+` フラグがkubeletに渡され、ホストに上流のネームサーバーが設定されていないエアギャップネットワークでポッドのDNS解決を設定するのに役立つかもしれない。
====

== アップグレード

[tabs,sync-group-id=airgap-upgrade]
======
手動アップグレード::
+
--
エアギャップ環境のアップグレードは、以下の方法で行うことができる：

. アップグレードするK3sのバージョンのhttps://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL]ページから、新しいエアギャップイメージ（tarファイル）をダウンロードしてください。各ノードの`+/var/lib/rancher/k3s/agent/images/+` ディレクトリに tar を置く。古いtarファイルを削除する。
. 各ノードの`+/usr/local/bin+` 、古いK3sのバイナリをコピーして置き換える。https://get.k3s.io にあるインストールスクリプトをコピーしてください（前回のリリースから変更されている可能性があります）。同じ環境変数を使って、以前と同じようにスクリプトを再度実行する。
. K3sサービスを再起動します（インストーラーによって自動的に再起動されていない場合）。
--

自動アップグレード方法::
+
--
K3sはxref:upgrades/automated.adoc[自動アップグレードを]サポートしています。エアギャップ環境でこれを有効にするには、プライベートレジストリに必要なイメージがあることを確認する必要があります。

アップグレードするK3sのバージョンに対応するrancher/k3s-upgradeのバージョンが必要です。なお、Dockerイメージは`+++` をサポートしていないため、imageタグはK3sリリースの`+++` を`+-+` に置き換えています。

また、デプロイする system-upgrade-controller マニフェスト YAML で指定されている system-upgrade-controller と kubectl のバージョンも必要です。system-upgrade-controllerhttps://github.com/rancher/system-upgrade-controller/releases/latest[ここで] の最新リリースを確認し、system-upgrade-controller.yamlをダウンロードして、プライベートレジストリにプッシュする必要があるバージョンを決定する。例えば、system-upgrade-controller のリリース v0.4.0 では、これらのイメージはマニフェスト YAML で指定されています：

----
rancher/system-upgrade-controller:v0.4.0
rancher/kubectl:v0.17.0
----

必要なrancher/k3s-upgrade、rancher/system-upgrade-controller、rancher/kubectlイメージをプライベートレジストリに追加したら、xref:upgrades/automated.adoc[自動アップグレードガイドに従って]ください。
--
======
