= Referencias métricas 
:revdate: 2025-11-07
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

Esta página define las métricas comunes relacionadas con Kubernetes recopiladas por SUSE Observability y explica cómo se calculan.

=== container_memory_usage

[horizontal]
Nombre:: `+container_memory_usage+`
Tipo:: calibre
Unidad:: bytes
Fuente:: Lectura directa de la jerarquía cgroup del contenedor.

[cols="1,3"]
|===
|Versión de cgroup | Archivo fuente

|v1 | `+memory.usage_in_bytes+`
|v2 | `+memory.current+`
|===

Resumen:: La cantidad total de memoria utilizada actualmente por el cgroup y sus descendientes. Se trata de una suma que incluye la memoria anónima (RSS), la caché de páginas y la memoria del núcleo. Utilice una de las siguientes métricas para obtener más detalles sobre un área de memoria específica.

=== container_memory_kernel

[horizontal]
Nombre:: `+container_memory_kernel+`
Tipo:: calibre
Unidad:: bytes
Fuente:: Lectura directa de la jerarquía cgroup del contenedor.

[cols="1,3"]
|===
|Versión de cgroup | Archivo fuente

|v1 | `+memory.kmem.usage_in_bytes+`
|v2 | `+memory.stat+` -> `+kernel+` dentro del archivo
|===
Resumen:: Cantidad de memoria total del núcleo, incluyendo (kernel_stack, pagetables, percpu, vmalloc, slab)

=== container_memory_rss

[horizontal]
Nombre:: `+container_memory_rss+`
Tipo:: calibre
Unidad:: bytes
Fuente:: Lectura directa de la jerarquía cgroup del contenedor.

[cols="1,3"]
|===
|Versión de cgroup | Archivo fuente

|v1 | `+memory.stat+` -> `+total_rss+` dentro del archivo
|v2 | `+memory.stat+` -> `+anon+` dentro del archivo
|===
Resumen:: El tamaño del conjunto residente (RSS) de la memoria anónima. Esta es la memoria no respaldada por archivos (heap y stack) utilizada activamente por los procesos dentro del cgroup. Este valor suele reflejar el verdadero "conjunto de trabajo" de la aplicación. 

=== container_memory_cache

[horizontal]
Nombre:: `+container_memory_cache+`
Tipo:: calibre
Unidad:: bytes
Fuente:: Lectura directa de la jerarquía cgroup del contenedor.

[cols="1,3"]
|===
|Versión de cgroup | Archivo fuente

|v1 | `+memory.stat+` -> `+total_cache+` dentro del archivo
|v2 | `+memory.stat+` -> `+file+` dentro del archivo
|===
Resumen:: La caché de páginas (memoria utilizada para almacenar en caché los datos del sistema de archivos, incluidos tmpfs y la memoria compartida).
