= Verificar que la instrumentación funciona
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

Si el colector y la configuración de la instrumentación se han realizado correctamente, los datos deberían estar disponibles en SUSE Observability en uno o dos minutos.

Puede comprobar que SUSE Observability está recibiendo trazas:

. Abrir SUSE Observability en un navegador
. Encontrar (uno de) los pods instrumentados
. Seleccione el pod para abrir la página de destacados
. Abra la perspectiva de rastreo. Si el pod está sirviendo tráfico ahora debería mostrar trazas

Para comprobar que SUSE Observability está recibiendo métricas:

. Abrir SUSE Observability en un navegador
. Abra el explorador de métricas desde el menú
. Buscar las métricas expuestas por su aplicación

Si después de 5 minutos sigue sin haber métricas, es probable que algo esté mal configurado. Consulte la xref:/setup/otel/troubleshooting.adoc[sección de solución de problemas] para obtener ayuda.
