include::partial$variables.adoc[]

= Configuración del proxy
:description: Utilización de proxies con {project-name}.
:keywords: ["{project-name}", "kubewarden", "kubernetes", "proxy", "proxies"]
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-type: ["howto"]
:doc-topic: ["operator-manual", "proxy"]

Tanto para `kwctl` como para `policy-server` puede configurar proxies HTTP y HTTPS, así como eximir dominios de esta configuración de proxy.

Puede hacerlo de dos maneras:* Estableciendo las variables de entorno `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`(y sus equivalentes en minúsculas) para `kwctl` o `policy-server`.
  Para configurar un CR PolicyServer, configure su matriz `spec.env`.* Proporcionando un archivo `sources.yaml` mediante el argumento `--sources-path`.
  Un archivo `sources.yaml` tiene prioridad sobre las variables de entorno.
  El consumo de esta configuración a través del campo `spec` aún no está expuesto en los CR de PolicyServer.

Establecer una configuración de proxy influye:

* Política pull, push y pull-and-run desde y hacia el registro OCI.
* Capacidades del host a partir de llamadas contextuales, como:
** Registro de contenedores, como la obtención de un manifiesto OCI o un resumen de manifiesto.
   En lugar de acceder directamente al registro OCI, el tráfico se dirigirá a través de los proxies configurados.
** Capacidades de Sigstore, como verificar una firma sin clave.
   En lugar de acceder a los servicios definidos por Sigstore, el tráfico se dirigirá a través de los proxies configurados.

== Ejemplo

Puede establecer las siguientes variables de entorno, tanto para `kwctl` como para`policy-server` (a través del PolicyServer `spec.env`):

[source,bash]
----
HTTP_PROXY="http://proxy.corp:3128"
https_proxy="http://proxy.corp:3129"
NO_PROXY="localhost,.corp"
----

Con esta configuración:* El tráfico no seguro a través de HTTP, como el que va y viene de un registro OCI inseguro, se enruta a través de `\http://proxy.corp:3128`.
  Esto afecta a las políticas de extracción y a las políticas que llaman a capacidades conscientes del contexto que tienen compendios de manifiesto de imagen OCI para contenedores en ese repositorio.* El tráfico cifrado a través de HTTPS se enruta a través de `\https://proxy.corp:3129`.
  Por ejemplo, esto incluye tirar y empujar políticas a cualquier registro OCI seguro, y las mencionadas capacidades de contexto de las políticas.* El tráfico hacia y desde localhost o cualquier dominio bajo `.corp` está exento de las configuraciones anteriores.


== El archivo `sources.yaml` 

Para más detalles, consulte la xref:/reference/sources_yaml.adoc[`sources.yaml`] referencia.