= オープン テレメトリコレクタ
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

OpenTelemetryコレクターは、テレメトリーデータを受信、処理、エクスポートするために、ベンダーにとらわれない実装を提供します。Open Telemetry SDKでインスツルメンテーションされたアプリケーションは、コレクタを使用してSUSE Observabilityにテレメトリ・データ（トレースとメトリクス）を送信できます。

アプリケーションは、OpenTelemetry SDK をセットアップすると、コレクターを使用して、トレースやメトリクスのような遠隔測定データを SUSE Observability や他のコレクターに（さらに処理するために）送信することができます。コレクタは、ネイティブのオープン・テレメトリ・プロトコルである OTLP を介してこのデータを受信するようにデフォルトで設定されています。トレース用のJaegerやZipkin、メトリクス用のInfluxやPrometheusなど、他のインスツルメンテーションSDKが提供する他のフォーマットのデータを受け取ることもできる。

コレクターは、同じKubernetesクラスタや同じ仮想マシン上など、アプリケーションの近くで稼働している。これにより、SDKはデータをコレクターに素早くオフロードすることができ、コレクターは変換、バッチ処理、フィルタリングを行うことができる。複数のアプリケーションで使用でき、データ処理パイプラインを簡単に変更できる。

インストールガイドについては、それぞれのxref:/setup/otel/getting-started/README.adoc[スタートガイドを]参照してください。スタートガイドでは、始めるための基本的なコレクター構成を提供していますが、時間の経過とともに、ニーズに合わせてカスタマイズし、インジェストパイプラインをカスタマイズするために、レシーバー、プロセッサー、エクスポーターを追加していくことになるでしょう。

== 構成

コレクタ構成は、異なるテレメトリ信号を処理するためのパイプラインを定義する。処理パイプラインのコンポーネントはいくつかのカテゴリーに分けることができ、それぞれのコンポーネントには独自の設定がある。ここでは、さまざまな設定セクションの概要と使い方を説明します。

=== レシーバー

レシーバーは、OTLPを介して、計測されたアプリケーションからのテレメトリーデータを受け取ります：

[,yaml]
----
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
----

例えばジプキントレースなど、他のプロトコルを介してデータを受け取ったり、様々なソースから積極的にデータを収集したりするレシーバーはもっとたくさんある：

* ホスト・メトリクス
* Kubernetesメトリクス
* プロメテウス・メトリクス（OpenMetrics）
* データベース

3つのシグナル（トレース、メトリクス、ログ）すべてをサポートするレシーバーもあれば、1つまたは2つのシグナルのみをサポートするレシーバーもある。opentelemetry-collector-contrib リポジトリにはhttps://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver[全てのレシーバーと]その設定に関するドキュメントがあります。

=== プロセッサー

レシーバーからのデータは、プロセッサーによって変換されたり、フィルタリングされたりする。

[,yaml]
----
processors:
  batch: {}
----

バッチプロセッサーは、3つの信号をすべてバッチ処理し、圧縮率を高め、発信コネクション数を減らす。opentelemetry-collector-contrib リポジトリには、https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[全てのプロセッサの]設定に関するドキュメントがあります。

=== 輸出業者

SUSE Observabilityバックエンドにデータを送信するために、コレクタにはエクスポータがあります。さまざまなプロトコル、プッシュまたはプルベース、さまざまなバックエンドに対応するエクスポータがある。OTLPプロトコルを使用すると、追加処理の宛先として別のコレクタを使用する こともできる。

[,yaml]
----
exporters:
  # The gRPC otlp exporter
  otlp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp endpoint
    endpoint: <otlp-suse-observability-endpoint>
    # Use snappy compression, if no compression specified the data will be uncompressed
    compression: snappy
----

SUSE Observabilityエクスポータでは、<<_extensions,api>>キーを使用した認証が必要です。opentelemetry-collector-contrib リポジトリには、https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter[全てのエクスポーターと]その設定に関するドキュメントがあります。

もしgRPCエクスポータがうまくいかない場合は（xref:/setup/otel/troubleshooting.adoc#_some_proxies_and_firewalls_dont_work_well_with_grpc[トラブルシューティングも]参照してください）、代わりに`+otlphttp+` 、少し効率の悪いOTLP over HTTPプロトコルに切り替えることができます。`+pipelines+` と`+exporter+` セクションの`+otlp/suse-observability+` への参照をすべて`+otlphttp/suse-observability+` に置き換え、エクスポータの設定を更新する：

[,yaml]
----
exporters:
  # The gRPC otlp exporter
  otlphttp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp HTTP endpoint
    endpoint: <otlp-http-suse-observability-endpoint>
    # Use snappy compression, if no compression specified the data will be uncompressed
    compression: snappy
----

[CAUTION]
====
SUSE ObservabilityのOTLP HTTPエンドポイントは、OTLPエンドポイントとは異なります。正しいURLを見つけるには、xref:/setup/otel/otlp-apis.adoc[OTLP APIを使って]ください。
====


=== サービスパイプライン

各テレメトリ信号に対して、個別のパイプラインが構成される。パイプラインは`+service.pipeline+` セクションで設定し、どのレシーバー、プロセッサー、エクスポーターをどの順番で使うかを定義する。パイプラインでコンポーネントを使用する前に、まずコンフィギュレーションセクションで定義する必要があります。例えば、`+batch+` プロセッサーはコンフィギュレーションを持たないが、`+processors+` セクションで宣言する必要がある。構成されていてもパイプラインに含まれていないコンポーネントは、まったくアクティブになりません。

[,yaml]
----
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, spanmetrics, otlp/suse-observability]
    metrics:
      receivers: [otlp, spanmetrics, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlp/suse-observability]
----

=== エクステンション

拡張は、データを処理するパイプラインでは直接使用されないが、他の方法でコレ クタの機能を拡張する。SUSE Observabilityでは、apiキーを使用した認証の設定に使用します。拡張機能を使用するには、設定セクションで定義する必要があります。パイプラインコンポーネントと同様に、エクステンションは、`+service.extensions+` セクションで有効になっているときのみアクティブになります。

[,yaml]
----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
service:
  extensions: [ bearertokenauth ]
----

opentelemetry-collector-contrib リポジトリには、https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension[すべての拡張]機能とその設定に関するドキュメントがあります。

== テレメトリーの変革

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[opentelemetry-collector-contrib リポジトリには]多くのプロセッサがある。ここでは、一般的に使用されているプロセッサーとその機能の概要を説明する。詳細とその他多くのプロセッサについては、https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[opentelemetry-collector-contrib リポジトリを]使用してください。

=== フィルタリング

計測器やアプリケーションの中には、ノイズが多く、ユースケースには不要なテレメトリーデータを大量に生成するものがあります。https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor[フィルタプロセッサを]使用すると、コレクタに不要なデータをドロップして、SUSE Observability にデータを送信しないようにできます。例えば、ある特定のサービスのデータをすべて削除する：

[,yaml]
----
processors:
  filter/ignore-service1:
    error_mode: ignore
    traces:
      span:
        - resource.attributes["service.name"] == "service1"
----

フィルタープロセッサーは、https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md[Open Telemetry Transformation Lanuage (OTTL)]を使用してフィルターを定義します。

=== 属性の追加、変更、削除

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor[attributes processorは]、スパン、ログ、メトリクスの属性を変更できる。

[,yaml]
----
processors:
  attributes/accountid:
    actions:
      - key: account_id
        value: 2245
        action: insert
----

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor[リソースプロセッサは]、xref:/setup/otel/concepts.adoc#_resources[リソースの]属性を変更することができる。例えば、すべてのリソースにKubernetesクラスタ名を追加する：

[,yaml]
----
  processors:
    resource/add-k8s-cluster:
      attributes:
      - key: k8s.cluster.name
        action: upsert
        value: my-k8s-cluster
----

メトリック名やその他のメトリック固有の情報を変更するには、https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor[メトリック・トランスフォーマーも]あります。

=== トランスフォーメーション

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor[トランスフォーム・プロセッサーは]、例えばスパン・ステータスの設定に使用できる：

[,yaml]
----
processors:
  transform:
    error_mode: ignore
    trace_statements:
      - set(span.status.code, STATUS_CODE_OK) where span.attributes["http.request.status_code"] == 400
----

スパン名の変更、メトリックタイプの変換、ログイベントの変更など、さらに多くの変換をサポートしている。すべての可能性については、https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor[のreadmeを]参照。フィルタの定義には、https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md[Open Telemetry Transformation Lanuage (OTTL)]を使用します。

== スクラブ感受性データ

コレクタは、アプリケーションとSUSE Observabilityの間に配置され、<<_transforming_telemetry,データをフィルタリングおよび変換>>するプロセッサを備えているため、機密データを削除または難読化するのに理想的な場所です。すでに説明したフィルタリングと変換機能のほかに、https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/redactionprocessor[]、ブロックリストに一致する属性値をマスクできるある。また、指定された許容属性リストに一致しない属性を削除することもできるが、これを使用すると、すぐにほとんどの属性を削除することになり、その結果、観測能力は非常に制限されることになる。なお、リソース属性は処理しない。

特定の属性や値のみをマスクする例：

[,yaml]
----
processors:
  redaction:
    allow_all_keys: true
    # attributes matching the regexes on the list are masked.
    blocked_key_patterns:
      - ".*token.*"
      - ".*api_key.*"
    blocked_values: # Regular expressions for blocking values of allowed span attributes
      - '4[0-9]{12}(?:[0-9]{3})?' # Visa credit card number
      - '(5[1-5][0-9]{14})' # MasterCard number
    summary: debug
----

== コレクターを試す

スタートガイドでは、Kubernetesにコレクターをデプロイする方法、またはLinuxパッケージを使用して本番環境用のセットアップを行う方法を紹介している。また、テストなどのために、ドッカーコンテナとして直接実行して試すことも可能だ：

[,bash]
----
docker run \
  -p 127.0.0.1:4317:4317 \
  -p 127.0.0.1:4318:4318 \
  -v $(pwd)/config.yaml:/etc/otelcol-contrib/config.yaml \
  ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
----

これは、すべての貢献されたコンポーネント（レシーバ、プロセッサなど）を含むcollector contribイメージを使用します。より小さく、より限定されたバージョンの画像も用意されているが、利用できるコンポーネントは非常に限られている：

[,bash]
----
docker run \
  -p 127.0.0.1:4317:4317 \
  -p 127.0.0.1:4318:4318 \
  -v $(pwd)/config.yaml:/etc/otelcol/config.yaml \
  ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest
----

Kubernetesのインストールのデフォルトは、コレクターイメージのKubernetesディストリビューションである`+ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s+` 、基本イメージよりはコンポーネントが多いが、contribイメージよりは少ないことに注意。このイメージでコンポーネントの欠落が発生した場合は、代わりにcontribイメージ（`+ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib+` ）を使用するように切り替えるだけです。

== トラブルシューティング

=== エクスポーターからのHTTPリクエストが大きすぎる

場合によっては、遠隔測定データのHTTPリクエストが非常に大きくなり、SUSE Observabilityによって拒否されることがあります。SUSE ObservabilityのgRPCプロトコルの制限は4MBです。HTTPリクエストの制限に遭遇した場合は、圧縮アルゴリズムを変更し、最大バッチサイズを制限することで、リクエストサイズを小さくすることができます。

==== HTTPリクエスト圧縮

スタートガイドでは、コレクターで`+snappy+` 圧縮を有効にしている。これは最良の圧縮ではないが、`+gzip+` よりも CPU リソースを使用しない。圧縮を解除した場合は、再度有効にするか、より良い圧縮 https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md#_compression_comparison[率（]提供する圧縮アルゴリズムに切り替えることができます。gRPCとHTTPプロトコルでは、同じ圧縮タイプが利用できる。

==== 最大バッチサイズ

HTTPリクエスト・サイズを小さくするには、`+batch+` ・プロセッサーにバッチ・サイズを制限するコンフィギュレーションを追加する：

[,yaml]
----
processor:
  batch: {}
    send_batch_size: 8192 # This is the default value
    send_batch_max_size: 10000 # The default is 0, meaning no max size at all
----

バッチサイズは、スパン数、メトリックデータポイント数、またはログレコード数で定義されます（バイト数ではありません）。詳細については、https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/README.md[] バッチ参照してください。

== 関連リソース

Open Telemetry のドキュメントには、コンフィギュレーションと代替インストール・オプションの詳細が記載されています：

* テレメトリコレクタの構成を開く： https://opentelemetry.io/docs/collector/configuration/
* コレクターのKubernetesインストール： https://opentelemetry.io/docs/kubernetes/helm/collector/
* コレクターのHelmチャートの代わりにKubernetesオペレーターを使用する： https://opentelemetry.io/docs/kubernetes/operator/
* テレメトリーサンプリングを開く： https://opentelemetry.io/blog/2022/tail-sampling/
