= オープン・テレメトリーを始める
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[メトリックスとトレースをSUSE Observabilityに送信するOpen Telemetryコレクターと2つのインスツルメンテッド・アプリケーション]

SUSE Observabilityは、https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetryを]サポートしています。オープンテレメトリーは、トレース、メトリクス、ログなどのテレメトリーデータを収集、変換、出荷するための標準化されたプロトコルとオープンソースのフレームワークのセットです。オープン・テレメトリーは、多様なプログラミング言語とプラットフォームをサポートする。

SUSE Observabilityはメトリクスとトレースの両方をサポートしており、SUSE Observabilityエージェントが提供する（Kubernetesの）トポロジーデータにOpen Telemetryのメトリクスとトレースを追加します。したがって、SUSE Observabilityエージェントもインストールする必要があります。ログと、SUSE Observability エージェントなしで Open Telemetry を使用するためのサポートは、まもなく提供されます。

オープンテレメトリーは、いくつかの異なるコンポーネントで構成されています。SUSE Observability を使用する場合、アプリケーションを計測するxref:/setup/otel/languages/README.adoc[SDK]とxref:/setup/otel/collector.adoc[Open Telemetry コレクターが]最も重要な部分です。SUSE Observabilityで使用するための両方の設定方法を紹介します。

アプリケーションが既に Open Telemetry や、Jaeger や Zipkin のような Open Telemetry がサポートしているライブラリでインスツルメンテーションされている場合、コレクターを使ってそのデータを SUSE Observability に送ることができ、追加のインスツルメンテーションは必要ありません。

SUSE Observabilityは、SUSE Observabilityで使用されるすべてのデータが利用可能であることを確認するために、特定のプロセッサと認証でコレクタを設定する必要があります。

== 参考文献

* https://opentelemetry.io/docs/collector/[テレメトリ・コレクタを]オープン・オープン・テレメトリ・ドキュメントで見る
* https://opentelemetry.io/docs/languages/[アプリケーションを計測するための SDK]Open Telemetry ドキュメントで
