= オープン・テレメトリーを始める
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[メトリックスとトレースをSUSE Observabilityに送信するOpen Telemetryコレクターと2つのインスツルメンテッド・アプリケーション]

SUSE Observabilityは、https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetryを]サポートしています。オープンテレメトリーは、トレース、メトリクス、ログなどのテレメトリーデータを収集、変換、出荷するための標準化されたプロトコルとオープンソースのフレームワークのセットです。オープン・テレメトリーは、多様なプログラミング言語とプラットフォームをサポートする。

SUSE Observabilityは、メトリクスとトレースの両方をサポートしています。Kubernetesスタックパックと組み合わせて使用すると、Kubernetesポッドは、利用可能なときにトレースで豊かになります。Open Telemetry stackpack をインストールすることで、サービスとサービスインスタンスの新しい概要ページが利用可能になり、トレースとスパンメトリクスにアクセスできるようになります。Open Telemetry のメトリクスは、モニターやメトリクス・バインディングで使用できます。stackpackには、スパン・メトリクスと.NETおよびJVMのメモリ・メトリクスのメトリック・バインディングが付属しています。また、スパンのエラー率や持続時間のモニターもすぐに使える。

SUSE Observability で使用するための推奨セットアップは、該当する Open Telemetryxref:/setup/otel/instrumentation/README.adoc[SDK]でアプリケーションを計測し、計測したアプリケーションの近くにxref:/setup/otel/collector.adoc[Open Telemetry コレクターを]インストールして、データを前処理（Kubernetes ラベルでリッチ化、トレースでサンプリングなど）し、SUSE Observability にデータを送信することです。Open Telemetry Collector は、SDK を使用してアプリケーションにインスツルメンテーションを行うことなく、多くのタイプのテレメトリ・ソースからメトリクスを収集するためにも使用できます。詳細については、https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry collector integrations を]参照してください。また、データベースや遠隔測定プロトコルがサポートされているかどうかも確認してください。

xref:/setup/otel/getting-started/README.adoc[スタート]ガイドに従って、SUSE Observabilityで最適に動作するようにすべてを設定してください。

== 参考文献

* https://opentelemetry.io/docs/collector/[テレメトリ・コレクタを]オープン・オープン・テレメトリ・ドキュメントで見る
* https://opentelemetry.io/ecosystem/registry/?language=collector[オープン・テレメトリー・コレクターの統合]
* https://opentelemetry.io/docs/instrumentation/README.md[アプリケーションを計測するための SDK]Open Telemetry ドキュメントで
