= サンプリング
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

サンプリングは、SUSE Observabilityにエクスポートされるデータ量を減らしつつ、遠隔測定データの品質をできるだけ損なわないようにするために使用されます。サンプリングを適用する主な理由は、（ネットワークやストレージなどの）コストを削減するためだ。

アプリケーションが生成するデータが少なければ、サンプリングは不要であり、テレメトリーデータの不足による観測可能性の妨げになることさえある。しかし、アプリケーションのトラフィック量が多い場合、たとえば1秒間に1000スパンを超えるような場合は、サンプリングを適用する意味があります。

サンプリングには大きく分けて、ヘッド・サンプリングとテール・サンプリングの2種類がある。

== ヘッドサンプリング

ヘッドサンプリングは、サンプリングの決定（データをエクスポートするかどうか）をできるだけ早い段階で行う。したがって、トレース全体に基づいて判断することはできず、入手可能なごく限られた情報に基づいて判断することになる。otel コレクターには、一貫した確率サンプリングを実装するhttps://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/probabilisticsamplerprocessor[確率サンプリングプロセッサが]あります。サンプラーは設定可能で、トレースID（トレースに有効）または属性のハッシュ（ログに有効）に基づいてサンプリングを決定する。これにより、トレースのすべてのスパンが常にサンプリングされ、SUSE Observabilityで完全なトレースが得られるようになります。

ヘッドサンプリングの利点は

* わかりやすい
* 効率的
* 設定が簡単

しかしマイナス面は、トレース全体に対してサンプリングの決定を下すことが不可能なことである。例えば、失敗したトレースはすべてサンプリングし、成功したトレースはごく一部だけサンプリングするといった具合である。

ヘッドサンプリングを有効にするには、プロセッサーを設定し、パイプラインに含める。この例では、トレース ID に基づいて、4 つのトレースのうち 1 つをサンプリングしています：

[,yaml]
----
processors:
  probabilistic_sampler:
    sampling_percentage: 25
    mode: "proportional"
----

== テールサンプリング

テールサンプリングは、トレースが（ほぼ）完了するまでサンプリングの決定を先送りする。これにより、テールサンプラーは、トレース全体に基づいてサンプリングを決定することができ、例えば、故障トレースや低速トレースを常にサンプリングすることができる。特定の属性やサービス参加に基づくサンプリングなど、他にも多くの可能性がある。

OpenTelemetry Collector は、テールサンプリングポリシーを適用するために使用できるhttps://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor[テールサンプリングプロセッサを]提供します。

テールサンプリングの主な利点は、個々のスパンが作成されたときに利用可能な部分的な情報ではなく、完全なトレースデータに基づいてサンプリングの決定を行うことで、さらなる柔軟性が得られることである。


[WARNING]
====
有利ではあるが、テールサンプリングには以下のような欠点がある：

* 設定も理解も難しい。
* サンプリングが決定されるまでトレースのスパンを保存するため、ステートフルでなければならない。
* したがって、リソースの使用量も（かなり）多くなる
* サンプラーが追いつかないかもしれないので、特別なモニタリングとスケーリングが必要だ。
====

テールサンプリングを有効にするには、プロセッサーを設定し、パイプラインに含める。

[,yaml]
----
processors:
  tail_sampling:
    decision_wait: 10s
    policies:
    - name: rate-limited-composite
      type: composite
      composite:
        max_total_spans_per_second: 500
        policy_order: [errors, slow-traces, rest]
        composite_sub_policy:
        - name: errors
          type: status_code
          status_code:
            status_codes: [ ERROR ]
        - name: slow-traces
          type: latency
          latency:
            threshold_ms: 1000
        - name: rest
          type: always_sample
        rate_allocation:
        - policy: errors
          percent: 33
        - policy: slow-traces
          percent: 33
        - policy: rest
          percent: 34
----

サンプルの例：

* 最大500スパン/秒
* 最大誤差の33%までのトレースのすべてのスパン
* 1秒より遅いトレースのすべてのスパンが、最大33%に達するまで。
* その他のスパンは最大許容レートまで

設定オプションやさまざまなポリシーの詳細については、https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor[tail sampling readmeを]参照のこと。

しかし、完全にセット・アンド・フォーゲットというわけではない。リソースの使用量が増え始めたら、テールサンプリングを処理するために複数のコレクターを使用するようにスケールアウトする必要があります。その場合、トレースIDに基づいてトラフィックをルーティングするために、https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/routingconnector/README.md[ルーティングも]必要になります。

== スパン・メトリクスと組み合わせたサンプリング・トレース

getting started セクションでは、コレクタの設定にサンプリングが含まれていません。サンプリングを追加する際には、トレースから計算されるメトリクスを可能な限り正確に保つように注意したい。特にテールサンプリングは、一般的に相対的なエラー量がはるかに多いため、メトリクスが非常に歪んでしまう可能性がある。これを避けるために、トレースパイプラインを複数の部分に分割し、それらをフォワードコネクターで接続する。追加コネクターとサンプリングプロセッサーを含むようにコンフィグを変更する。そして、ここに示すようにパイプラインを修正する：

[,yaml]
----
connectors:
  # enable the forwarder
  forward:
processors:
  # Configure the probabilistic sampler to sample 25% of the traffic
  probabilistic_sampler:
    sampling_percentage: 25
    mode: "proportional"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource]
      exporters: [forward]
    traces/spanmetrics:
      receivers: [forward]
      processors: []
      exporters: [spanmetrics]
    traces/sampling:
      receivers: [forward]
      processors: [probabilistic_sampler, batch]
      exporters: [debug, otlp/stackstate]
    metrics:
      receivers: [otlp, spanmetrics, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlp/stackstate]
----

この例では、トラフィックの25%をサンプリングするように設定された確率的サンプラーを使用しています。あなたの状況に合わせてパーセンテージを調整するか、代わりに<<_tail_sampling,テールサンプラーに>>切り替えることになるだろう。パイプラインの設定はテールサンプラーも同じで、`+probabilistic_sampler+` の参照を`+tail_sampling+` に置き換えるだけである。
