// This file was converted from Markdown to AsciiDoc.

include::partial$variables.adoc[]
= kwctl CLI
:revdate: 2026-03-18
:page-revdate: {revdate}
:title: kwctl CLI
:description: Explore la herramienta de línea de comandos \`+kwctl+` para gestionar las políticas de {project-name} y realizar tareas como la carga de políticas.
:keywords: cli, referencia, kwctl
:doc-persona: kubewarden-operator
:doc-type: referencia
:doc-topic: manual del operador

== Ayuda en línea de comandos para `+kwctl+`

Este documento contiene el contenido de la ayuda del programa de línea de comandos `+kwctl+`.

*Visión general del mando:*

* <<kwctl,`+kwctl+`>>
* <<kwctl-annotate,`+kwctl annotate+`>>
* <<kwctl-bench,`+kwctl bench+`>>
* <<kwctl-completions,`+kwctl completions+`>>
* <<kwctl-digest,`+kwctl digest+`>>
* <<kwctl-docs,`+kwctl docs+`>>
* <<kwctl-info,`+kwctl info+`>>
* <<kwctl-inspect,`+kwctl inspect+`>>
* <<kwctl-load,`+kwctl load+`>>
* <<kwctl-policies,`+kwctl policies+`>>
* <<kwctl-pull,`+kwctl pull+`>>
* <<kwctl-push,`+kwctl push+`>>
* <<kwctl-rm,`+kwctl rm+`>>
* <<kwctl-run,`+kwctl run+`>>
* <<kwctl-save,`+kwctl save+`>>
* <<kwctl-scaffold,`+kwctl scaffold+`>>
* <<kwctl-scaffold-admission-request,`+kwctl scaffold admission-request+`>>
* <<kwctl-scaffold-artifacthub,`+kwctl scaffold artifacthub+`>>
* <<kwctl-scaffold-manifest,`+kwctl scaffold manifest+`>>
* <<kwctl-scaffold-vap,`+kwctl scaffold vap+`>>
* <<kwctl-scaffold-verification-config,`+kwctl scaffold verification-config+`>>
* <<kwctl-verify,`+kwctl verify+`>>

[[kwctl]]
=== `+kwctl+`

Herramienta de gestión de las políticas {project-name} 

*Uso:* `+kwctl [OPTIONS] <COMMAND>+`

==== Subcomandos

* `+annotate+` - Añadir metadatos {short-project-name} a un módulo WebAssembly
* `+bench+` - Benchmarks a {short-project-name} policy
* `+completions+` - Generar terminaciones de shell
* `+digest+` - Obtención del resumen del manifiesto OCI de una póliza
* `+docs+` - Genera la documentación markdown para los comandos kwctl
* `+info+` - Mostrar información del sistema
* `+inspect+` - Inspeccione {short-project-name} policy
* `+load+` - cargar políticas desde un archivo tar.gz
* `+policies+` - Lista todas las políticas descargadas
* `+pull+` - Extrae una política de {short-project-name} de un URI determinado
* `+push+` - Envía una política {short-project-name} a un registro OCI
* `+rm+` - Elimina una póliza de {short-project-name} del almacén
* `+run+` - Ejecuta una política {short-project-name} a partir de un URI determinado
* `+save+` - guardar las políticas en un archivo tar.gz
* `+scaffold+` - Andamiaje de un recurso o archivo de configuración de Kubernetes
* `+verify+` - Verificación de una política {short-project-name} a partir de un URI determinado mediante Sigstore

==== Opciones

* `+-v+`, `+--verbose <VERBOSE>+` - Aumentar la verbosidad
* `+--no-color <NO-COLOR>+` - Desactivar salida de color

[[kwctl-annotate]]
=== `+kwctl annotate+`

Añadir metadatos {short-project-name} a un módulo WebAssembly

*Uso:* `+kwctl annotate [OPTIONS] --metadata-path <PATH> --output-path <PATH> <wasm-path>+`

==== Argumentos

* `+<WASM-PATH>+` - Ruta al módulo WebAssembly que se va a anotar

==== Opciones

* `+-m+`, `+--metadata-path <PATH>+` - Archivo que contiene los metadatos
* `+-o+`, `+--output-path <PATH>+` - Archivo de salida
* `+-u+`, `+--usage-path <PATH>+` - Fichero que contiene la información de uso de la política

[[kwctl-bench]]
=== `+kwctl bench+`

Compara una política {short-project-name}.

La política puede especificarse de las siguientes maneras:- URI: por ejemplo, `+registry://ghcr.io/kubewarden/policies/psp-policy:latest+` o `+\https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm+`- Prefijo SHA: por ejemplo, `+c3b80a10f9c3+` (requiere que la política ya esté extraída) - Archivo WASM local: por ejemplo, `+file://home/tux/new-policy/psp-policy.wasm+`- Archivo YAML local: por ejemplo, `+file://home/tux/cluster-admission-policy.yaml+` (contiene declaraciones de {short-project-name} Recursos personalizados como `+ClusterAdmissionPolicy+`, `+AdmissionPolicy+`, etc.)

Comportamiento por defecto:
Si se omite el esquema, se asume `+file://+`, enraizado en el directorio actual.

Notas sobre los recursos personalizados {short-project-name}:- Las banderas `+--request-path+`, `+--settings-path+`, y `+--settings-json+` se ignoran; las configuraciones se leen de la definición del Recurso Personalizado.- La bandera `+--execution-mode+` se aplica a todas las políticas del archivo YAML.- El indicador `+--raw+` no puede utilizarse, ya que los recursos personalizados de {short-project-name} no son compatibles con las políticas de `+raw+`.

Sólo se evalúan los siguientes atributos de la definición personalizada de recursos (CRD):- Módulo de política - Configuración de la política - Recursos contextuales a los que puede acceder la política.

Otros campos, como `+rules+`, `+matchConditions+`, `+objectSelector+`, y `+namespaceSelector+`, se ignoran.

Un archivo YAML puede contener varias declaraciones de recursos personalizados. En este caso, `+kwctl+` evalúa cada política del archivo utilizando la misma solicitud durante cada evaluación.

*Uso:* `+kwctl bench [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>+`

==== Argumentos

* `+<URI_OR_SHA_PREFIX_OR_YAML_FILE>+` - URI de la política, prefijo SHA o archivo YAML que contiene los recursos de la política {short-project-name}. Esquemas admitidos: registry://, https://, file://. Si se omite schema, se asume file://, enraizado en el directorio actual.

==== Opciones

* `+--allow-context-aware <ALLOW-CONTEXT-AWARE>+` - Concede acceso a los recursos de Kubernetes definidos en la sección `+contextAwareResources+` de la política. Atención: revise atentamente la lista de recursos para evitar abusos. Desactivado por defecto
* `+--cert-email <VALUE>+` - Correo electrónico previsto en el certificado Fulcio
* `+--cert-oidc-issuer <VALUE>+` - Emisor OIDC previsto en los certificados Fulcio
* `+--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>+` - Desactivar el uso de la caché wasmtime
* `+--docker-config-json-path <PATH>+` - Ruta a un directorio que contenga el archivo 'config.json' de Docker. Puede utilizarse para indicar los datos de autenticación del registro
* `+--dump-results-to-disk <DUMP_RESULTS_TO_DISK>+` - Pone los resultados en target/tiny-bench/label/.. si se puede encontrar el objetivo. se utiliza para comparar ejecuciones anteriores
* `+-e+`, `+--execution-mode <MODE>+` - El tiempo de ejecución que se utilizará para ejecutar esta política +
  Valores posibles: `+opa+`, `+gatekeeper+`, `+kubewarden+`, `+wasi+`
* `+--github-owner <VALUE>+` - Propietario de GitHub previsto en los certificados generados en las canalizaciones de CD
* `+--github-repo <VALUE>+` - Repositorio de GitHub esperado en los certificados generados en las canalizaciones de CD
* `+--measurement-time <SECONDS>+` - Cuánto tiempo 'debería' durar el bench, num_samples se prioriza por lo que el benching tardará más en poder recoger num_samples si el código a benchear es más lento que este límite de tiempo permitido.
* `+--num-resamples <NUM>+` - ¿Cuántas remuestreos hay que hacer?
* `+--num-samples <NUM>+` - ¿Cuántas remuestreos deben realizarse? Recomendado al menos 50, por encima de 100 no parece producir un resultado significativamente diferente
* `+--raw <RAW>+` - Validar una solicitud sin procesar +
  Valor por defecto: `+false+`
* `+--record-host-capabilities-interactions <FILE>+` - Registra todas las comunicaciones de políticas y capacidades del host en el archivo dado. Útil para ser combinado más tarde con '--replay-host-capabilities-interactions' flag
* `+--replay-host-capabilities-interactions <FILE>+` - Durante los intercambios de capacidades entre la política y el host, el host reproduce las respuestas encontradas en el archivo proporcionado. Esto es útil para probar políticas de forma reproducible, dado que no se realizan interacciones externas con registros OCI, DNS, Kubernetes.
* `+-r+`, `+--request-path <PATH>+` - Archivo que contiene el objeto de solicitud de admisión de Kubernetes en formato JSON.
* `+--settings-json <VALUE>+` - Cadena JSON que contiene la configuración de esta política
* `+-s+`, `+--settings-path <PATH>+` - Archivo que contiene la configuración de esta política
* `+--sigstore-trust-config <PATH>+` - Archivo con formato JSON conforme al mensaje ClientTrustConfig de las especificaciones Sigstore protobuf. Este archivo configura todo el estado de la instancia Sigstore, incluidos los URI utilizados para acceder a los servicios de transparencia de CA y artefactos, así como la propia raíz criptográfica de confianza
* `+--sources-path <PATH>+` - Archivo YAML con información de origen (https, registro de hosts inseguros, CA personalizadas...)
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` - Anotación en formato clave=valor. Puede repetirse varias veces
* `+--verification-config-path <PATH>+` - Archivo YAML que contiene la información de configuración de la verificación (firmas, claves públicas...)
* `+-k+`, `+--verification-key <PATH>+` - Ruta a la clave utilizada para verificar la política. Puede repetirse varias veces
* `+--warm-up-time <SECONDS>+` - Cuánto tiempo debe calentar el banco

[[kwctl-completions]]
=== `+kwctl completions+`

Generar terminaciones de shell

*Uso:* `+kwctl completions --shell <VALUE>+`

==== Opciones

* `+-s+`, `+--shell <VALUE>+` - Tipo de carcasa +
  Valores posibles: `+bash+`, `+elvish+`, `+fish+`, `+powershell+`, `+zsh+`

[[kwctl-digest]]
=== `+kwctl digest+`

Obtención del resumen del manifiesto OCI de una póliza

*Uso:* `+kwctl digest [OPTIONS] <uri>+`

==== Argumentos

* `+<URI>+` - Política URI

==== Opciones

* `+--docker-config-json-path <PATH>+` - Ruta a un directorio que contenga el archivo 'config.json' de Docker. Puede utilizarse para indicar los datos de autenticación del registro
* `+--sources-path <PATH>+` - Archivo YAML con información de origen (https, registro de hosts inseguros, CA personalizadas...)

[[kwctl-docs]]
=== `+kwctl docs+`

Genera la documentación markdown para los comandos kwctl

*Uso:* `+kwctl docs --output <FILE>+`

==== Opciones

* `+-o+`, `+--output <FILE>+` - ruta donde se almacenará el archivo de documentación

[[kwctl-info]]
=== `+kwctl info+`

Mostrar información del sistema

*Uso:* `+kwctl info+`

[[kwctl-inspect]]
=== `+kwctl inspect+`

Inspeccione {short-project-name} policy

*Uso:* `+kwctl inspect [OPTIONS] <uri_or_sha_prefix>+`

==== Argumentos

* `+<URI_OR_SHA_PREFIX>+` - URI de la política o prefijo SHA. Esquemas admitidos: registry://, https://, file://. Si se omite schema, se asume file://, enraizado en el directorio actual.

==== Opciones

* `+--docker-config-json-path <PATH>+` - Ruta a un directorio que contenga el archivo 'config.json' de Docker. Puede utilizarse para indicar los datos de autenticación del registro
* `+-o+`, `+--output <FORMAT>+` - Formato de salida +
  Valores posibles: `+yaml+`
* `+--show-signatures <SHOW-SIGNATURES>+` - Mostrar firmas sigstore
* `+--sources-path <PATH>+` - Archivo YAML con información de origen (https, registro de hosts inseguros, CA personalizadas...)

[[kwctl-load]]
=== `+kwctl load+`

cargar políticas desde un archivo tar.gz

*Uso:* `+kwctl load --input <input>+`

==== Opciones

* `+--input <INPUT>+` - cargar políticas desde tarball

[[kwctl-policies]]
=== `+kwctl policies+`

Lista todas las políticas descargadas

*Uso:* `+kwctl policies+`

[[kwctl-pull]]
=== `+kwctl pull+`

Extrae una política de {short-project-name} de un URI determinado

*Uso:* `+kwctl pull [OPTIONS] <uri>+`

==== Argumentos

* `+<URI>+` - Política URI. Esquemas admitidos: registry://, https://, file://

==== Opciones

* `+--cert-email <VALUE>+` - Correo electrónico previsto en el certificado Fulcio
* `+--cert-oidc-issuer <VALUE>+` - Emisor OIDC previsto en los certificados Fulcio
* `+--docker-config-json-path <DOCKER_CONFIG>+` - Ruta a un directorio que contenga el archivo 'config.json' de Docker. Puede utilizarse para indicar los datos de autenticación del registro
* `+--github-owner <VALUE>+` - Propietario de GitHub previsto en los certificados generados en las canalizaciones de CD
* `+--github-repo <VALUE>+` - Repositorio de GitHub esperado en los certificados generados en las canalizaciones de CD
* `+-o+`, `+--output-path <PATH>+` - Archivo de salida. Si no se proporciona se descargará en la tienda {short-project-name} 
* `+--sigstore-trust-config <PATH>+` - Archivo con formato JSON conforme al mensaje ClientTrustConfig de las especificaciones Sigstore protobuf. Este archivo configura todo el estado de la instancia Sigstore, incluidos los URI utilizados para acceder a los servicios de transparencia de CA y artefactos, así como la propia raíz criptográfica de confianza
* `+--sources-path <PATH>+` - Archivo YAML con información de origen (https, registro de hosts inseguros, CA personalizadas...)
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` - Anotación en formato clave=valor. Puede repetirse varias veces
* `+--verification-config-path <PATH>+` - Archivo YAML que contiene la información de configuración de la verificación (firmas, claves públicas...)
* `+-k+`, `+--verification-key <PATH>+` - Ruta a la clave utilizada para verificar la política. Puede repetirse varias veces

[[kwctl-push]]
=== `+kwctl push+`

Envía una política {short-project-name} a un registro OCI

*Uso:* `+kwctl push [OPTIONS] <policy> <uri>+`

Las anotaciones que se encuentran dentro de los metadatos de la política van a formar parte del manifiesto OCI.
Las anotaciones multilínea se omiten porque no son compatibles con la especificación OCI.
La anotación 'io.kubewarden.policy.source' se propaga como 'org.opencontainers.image.source' para permitir que herramientas como renovatebot detecten actualizaciones de políticas.

==== Argumentos

* `+<POLICY>+` - Política a impulsar. Puede ser la ruta a un archivo local, un URI de política o el prefijo SHA de una política en el almacén.
* `+<URI>+` - Política URI. Esquemas admitidos: registry://

==== Opciones

* `+--docker-config-json-path <PATH>+` - Ruta a un directorio que contenga el archivo 'config.json' de Docker. Puede utilizarse para indicar los datos de autenticación del registro
* `+-f+`, `+--force <FORCE>+` - Empuje también una política que no esté anotada
* `+-o+`, `+--output <PATH>+` - Formato de salida +
  Valor por defecto: `+text+` +
  Valores posibles: `+text+`, `+json+`
* `+--sources-path <PATH>+` - Archivo YAML con información de origen (https, registro de hosts inseguros, CA personalizadas...)

[[kwctl-rm]]
=== `+kwctl rm+`

Elimina una póliza de {short-project-name} del almacén

*Uso:* `+kwctl rm <uri_or_sha_prefix>+`

==== Argumentos

* `+<URI_OR_SHA_PREFIX>+` - URI de la política o prefijo SHA

[[kwctl-run]]
=== `+kwctl run+`

Ejecute localmente una o varias políticas de {short-project-name}.

La política puede especificarse de las siguientes maneras:- URI: por ejemplo, `+registry://ghcr.io/kubewarden/policies/psp-policy:latest+` o `+https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm+`- Prefijo SHA: por ejemplo, `+c3b80a10f9c3+` (requiere que la política ya esté extraída) - Archivo WASM local: por ejemplo, `+file://home/tux/new-policy/psp-policy.wasm+`- Archivo YAML local: por ejemplo, `+file://home/tux/cluster-admission-policy.yaml+` (contiene declaraciones de {short-project-name} Recursos personalizados como `+ClusterAdmissionPolicy+`, `+AdmissionPolicy+`, etc.)

Comportamiento por defecto:
Si se omite el esquema, se asume `+file://+`, enraizado en el directorio actual.

Notas sobre los recursos personalizados {short-project-name}:- Las banderas `+--request-path+`, `+--settings-path+`, y `+--settings-json+` se ignoran; las configuraciones se leen de la definición del Recurso Personalizado.- La bandera `+--execution-mode+` se aplica a todas las políticas del archivo YAML.- El indicador `+--raw+` no puede utilizarse, ya que los recursos personalizados de {short-project-name} no son compatibles con las políticas de `+raw+`.

Sólo se evalúan los siguientes atributos de la definición personalizada de recursos (CRD):- Módulo de política - Configuración de la política - Recursos contextuales a los que puede acceder la política.

Otros campos, como `+rules+`, `+matchConditions+`, `+objectSelector+`, y `+namespaceSelector+`, se ignoran.

Un archivo YAML puede contener varias declaraciones de recursos personalizados. En este caso, `+kwctl+` evalúa cada política del archivo utilizando la misma solicitud durante cada evaluación.

*Uso:* `+kwctl run [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>+`

==== Argumentos

* `+<URI_OR_SHA_PREFIX_OR_YAML_FILE>+` - URI de la política, prefijo SHA o archivo YAML que contiene los recursos de la política {short-project-name}. Esquemas admitidos: registry://, https://, file://. Si se omite schema, se asume file://, enraizado en el directorio actual.

==== Opciones

* `+--allow-context-aware <ALLOW-CONTEXT-AWARE>+` - Concede acceso a los recursos de Kubernetes definidos en la sección `+contextAwareResources+` de la política. Atención: revise atentamente la lista de recursos para evitar abusos. Desactivado por defecto
* `+--cert-email <VALUE>+` - Correo electrónico previsto en el certificado Fulcio
* `+--cert-oidc-issuer <VALUE>+` - Emisor OIDC previsto en los certificados Fulcio
* `+--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>+` - Desactivar el uso de la caché wasmtime
* `+--docker-config-json-path <PATH>+` - Ruta a un directorio que contenga el archivo 'config.json' de Docker. Puede utilizarse para indicar los datos de autenticación del registro
* `+-e+`, `+--execution-mode <MODE>+` - El tiempo de ejecución que se utilizará para ejecutar esta política +
  Valores posibles: `+opa+`, `+gatekeeper+`, `+kubewarden+`, `+wasi+`
* `+--github-owner <VALUE>+` - Propietario de GitHub previsto en los certificados generados en las canalizaciones de CD
* `+--github-repo <VALUE>+` - Repositorio de GitHub esperado en los certificados generados en las canalizaciones de CD
* `+--raw <RAW>+` - Validar una solicitud sin procesar +
  Valor por defecto: `+false+`
* `+--record-host-capabilities-interactions <FILE>+` - Registra todas las comunicaciones de políticas y capacidades del host en el archivo dado. Útil para ser combinado más tarde con '--replay-host-capabilities-interactions' flag
* `+--replay-host-capabilities-interactions <FILE>+` - Durante los intercambios de capacidades entre la política y el host, el host reproduce las respuestas encontradas en el archivo proporcionado. Esto es útil para probar políticas de forma reproducible, dado que no se realizan interacciones externas con registros OCI, DNS, Kubernetes.
* `+-r+`, `+--request-path <PATH>+` - Archivo que contiene el objeto de solicitud de admisión de Kubernetes en formato JSON.
* `+--settings-json <VALUE>+` - Cadena JSON que contiene la configuración de esta política
* `+-s+`, `+--settings-path <PATH>+` - Archivo que contiene la configuración de esta política
* `+--sigstore-trust-config <PATH>+` - Archivo con formato JSON conforme al mensaje ClientTrustConfig de las especificaciones Sigstore protobuf. Este archivo configura todo el estado de la instancia Sigstore, incluidos los URI utilizados para acceder a los servicios de transparencia de CA y artefactos, así como la propia raíz criptográfica de confianza
* `+--sources-path <PATH>+` - Archivo YAML con información de origen (https, registro de hosts inseguros, CA personalizadas...)
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` - Anotación en formato clave=valor. Puede repetirse varias veces
* `+--verification-config-path <PATH>+` - Archivo YAML que contiene la información de configuración de la verificación (firmas, claves públicas...)
* `+-k+`, `+--verification-key <PATH>+` - Ruta a la clave utilizada para verificar la política. Puede repetirse varias veces

[[kwctl-save]]
=== `+kwctl save+`

guardar las políticas en un archivo tar.gz

*Uso:* `+kwctl save --output <FILE> <policies>...+`

==== Argumentos

* `+<POLICIES>+` - lista de pólizas para guardar

==== Opciones

* `+-o+`, `+--output <FILE>+` - ruta donde se almacenará el archivo

[[kwctl-scaffold]]
=== `+kwctl scaffold+`

Andamiaje de un recurso o archivo de configuración de Kubernetes

*Uso:* `+kwctl scaffold <COMMAND>+`

==== Subcomandos

* `+admission-request+` - Andamiaje de un objeto AdmissionRequest
* `+artifacthub+` - Generar un archivo artifacthub-pkg.yml a partir de un archivo metadata.yml
* `+manifest+` - Generar un manifiesto de recursos Kubernetes
* `+vap+` - Convertir un Kubernetes `+ValidatingAdmissionPolicy+` en un {short-project-name} `+ClusterAdmissionPolicy+`
* `+verification-config+` - Salida de un archivo de configuración de verificación Sigstore por defecto

[[kwctl-scaffold-admission-request]]
=== `+kwctl scaffold admission-request+`

Andamiaje de un objeto AdmissionRequest

*Uso:* `+kwctl scaffold admission-request [OPTIONS] --operation <TYPE>+`

==== Opciones

* `+--object <PATH>+` - El fichero que contiene el nuevo objeto admitido
* `+--old-object <PATH>+` - El archivo que contiene el objeto existente
* `+-o+`, `+--operation <TYPE>+` - {short-project-name} Tipo de recurso personalizado +
  Valores posibles: `+CREATE+`

[[kwctl-scaffold-artifacthub]]
=== `+kwctl scaffold artifacthub+`

Generar un archivo artifacthub-pkg.yml a partir de un archivo metadata.yml

*Uso:* `+kwctl scaffold artifacthub [OPTIONS]+`

==== Opciones

* `+-m+`, `+--metadata-path <PATH>+` - Archivo que contiene los metadatos de la política
* `+-o+`, `+--output <FILE>+` - Ruta donde se almacenará el archivo artifact-pkg.yml
* `+-q+`, `+--questions-path <PATH>+` - Archivo que contiene el contenido de las preguntas-ui de la política
* `+-v+`, `+--version <VALUE>+` - Versión Semver de la política

[[kwctl-scaffold-manifest]]
=== `+kwctl scaffold manifest+`

Generar un manifiesto de recursos Kubernetes

*Uso:* `+kwctl scaffold manifest [OPTIONS] --type <VALUE> <uri_or_sha_prefix>+`

==== Argumentos

* `+<URI_OR_SHA_PREFIX>+` - URI de la política o prefijo SHA. Esquemas admitidos: registry://, https://, file://. Si se omite schema, se asume file://, enraizado en el directorio actual.

==== Opciones

* `+--allow-context-aware <ALLOW-CONTEXT-AWARE>+` - Utiliza los metadatos de la política para definir a qué recursos de Kubernetes puede acceder la política. Atención: revise atentamente la lista de recursos para evitar abusos. Desactivado por defecto
* `+--cert-email <VALUE>+` - Correo electrónico previsto en el certificado Fulcio
* `+--cert-oidc-issuer <VALUE>+` - Emisor OIDC previsto en los certificados Fulcio
* `+--docker-config-json-path <DOCKER_CONFIG>+` - Ruta a un directorio que contenga el archivo 'config.json' de Docker. Puede utilizarse para indicar los datos de autenticación del registro
* `+--fulcio-cert-path <PATH>+` - Camino hacia el certificado Fulcio. Puede repetirse varias veces
* `+--github-owner <VALUE>+` - Propietario de GitHub previsto en los certificados generados en las canalizaciones de CD
* `+--github-repo <VALUE>+` - Repositorio de GitHub esperado en los certificados generados en las canalizaciones de CD
* `+--rekor-public-key-path <PATH>+` - Ruta a la clave pública de Rekor. Puede repetirse varias veces
* `+--settings-json <VALUE>+` - Cadena JSON que contiene la configuración de esta política
* `+-s+`, `+--settings-path <PATH>+` - Archivo que contiene la configuración de esta política
* `+--sigstore-trust-config <PATH>+` - Archivo con formato JSON conforme al mensaje ClientTrustConfig de las especificaciones Sigstore protobuf. Este archivo configura todo el estado de la instancia Sigstore, incluidos los URI utilizados para acceder a los servicios de transparencia de CA y artefactos, así como la propia raíz criptográfica de confianza
* `+--sources-path <PATH>+` - Archivo YAML con información de origen (https, registro de hosts inseguros, CA personalizadas...)
* `+--title <VALUE>+` - Título de la política
* `+-t+`, `+--type <VALUE>+` - {short-project-name} Tipo de recurso personalizado +
  Valores posibles: `+ClusterAdmissionPolicy+`, `+AdmissionPolicy+`
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` - Anotación en formato clave=valor. Puede repetirse varias veces
* `+--verification-config-path <PATH>+` - Archivo YAML que contiene la información de configuración de la verificación (firmas, claves públicas...)
* `+-k+`, `+--verification-key <PATH>+` - Ruta a la clave utilizada para verificar la política. Puede repetirse varias veces

[[kwctl-scaffold-vap]]
=== `+kwctl scaffold vap+`

Convertir un Kubernetes `+ValidatingAdmissionPolicy+` en un {short-project-name} `+ClusterAdmissionPolicy+`

*Uso:* `+kwctl scaffold vap [OPTIONS] --binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml> --policy <VALIDATING-ADMISSION-POLICY.yaml>+`

==== Opciones

* `+-b+``+--binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml>+` - Archivo que contiene la definición de ValidatingAdmissionPolicyBinding
* `+--cel-policy <URI>+` - El módulo de política CEL que debe utilizarse +
  Valor por defecto: `+ghcr.io/kubewarden/policies/cel-policy:latest+`
* `+-p+`, `+--policy <VALIDATING-ADMISSION-POLICY.yaml>+` - El archivo que contiene la definición de ValidatingAdmissionPolicy.

[[kwctl-scaffold-verification-config]]
=== `+kwctl scaffold verification-config+`

Salida de un archivo de configuración de verificación Sigstore por defecto

*Uso:* `+kwctl scaffold verification-config+`

[[kwctl-verify]]
=== `+kwctl verify+`

Verificación de una política {short-project-name} a partir de un URI determinado mediante Sigstore

*Uso:* `+kwctl verify [OPTIONS] <uri>+`

==== Argumentos

* `+<URI>+` - Política URI. Esquemas admitidos: registry://

==== Opciones

* `+--cert-email <VALUE>+` - Correo electrónico previsto en el certificado Fulcio
* `+--cert-oidc-issuer <VALUE>+` - Emisor OIDC previsto en los certificados Fulcio
* `+--docker-config-json-path <PATH>+` - Ruta a un directorio que contenga el archivo 'config.json' de Docker. Puede utilizarse para indicar los datos de autenticación del registro
* `+--github-owner <VALUE>+` - Propietario de GitHub previsto en los certificados generados en las canalizaciones de CD
* `+--github-repo <VALUE>+` - Repositorio de GitHub esperado en los certificados generados en las canalizaciones de CD
* `+--sigstore-trust-config <PATH>+` - Archivo con formato JSON conforme al mensaje ClientTrustConfig de las especificaciones Sigstore protobuf. Este archivo configura todo el estado de la instancia Sigstore, incluidos los URI utilizados para acceder a los servicios de transparencia de CA y artefactos, así como la propia raíz criptográfica de confianza
* `+--sources-path <PATH>+` - Archivo YAML con información de origen (https, registro de hosts inseguros, CA personalizadas...)
* `+-a+`, `+--verification-annotation <KEY=VALUE>+` - Anotación en formato clave=valor. Puede repetirse varias veces
* `+--verification-config-path <PATH>+` - Archivo YAML que contiene la información de configuración de la verificación (firmas, claves públicas...)
* `+-k+`, `+--verification-key <PATH>+` - Ruta a la clave utilizada para verificar la política. Puede repetirse varias veces

'''

Este documento ha sido generado automáticamente por https://crates.io/crates/clap-markdown[`+clap-markdown+`].
