= Configurar Keycloak (OIDC)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-08
:page-revdate: {revdate}
:community-path: procedimentos/guias-para-novos-usuĂĄrios/autenticaĂ§ĂŁo-permissĂ”es-e-configuraĂ§ĂŁo-global/configuraĂ§ĂŁo-de-autenticaĂ§ĂŁo/configurar-keycloak-oidc.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-keycloak-oidc.adoc
:description: Crie um cliente OpenID Connect (OIDC) no Keycloak e configure o Rancher para trabalhar com o Keycloak. Ao final, seus usuĂĄrios poderĂŁo fazer login no Rancher usando suas credenciais do Keycloak.
ifeval::["{build-type}" != "community"]
:xref-keycloak-saml: xref:rancher-admin/users/authn-and-authz/configure-keycloak-saml.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-keycloak-saml: xref:procedimentos/guias-para-novos-usuĂĄrios/autenticaĂ§ĂŁo-permissĂ”es-e-configuraĂ§ĂŁo-global/configuraĂ§ĂŁo-de-autenticaĂ§ĂŁo/configurar-keycloak-saml.adoc
endif::[]

Se sua organizaĂ§ĂŁo usa o https://www.keycloak.org[Provedor de Identidade Keycloak (IdP)] para autenticaĂ§ĂŁo de usuĂĄrios, vocĂȘ pode configurar o Rancher para permitir que seus usuĂĄrios faĂ§am login usando suas credenciais do IdP. O Rancher suporta integraĂ§ĂŁo com o Keycloak usando o protocolo OpenID Connect (OIDC) e o protocolo SAML. Ambas as implementaĂ§Ă”es sĂŁo funcionalmente equivalentes quando usadas com o Rancher. Esta pĂĄgina descreve o processo para configurar o Rancher para trabalhar com o Keycloak usando o protocolo OIDC.

Se vocĂȘ preferir usar o Keycloak com o protocolo SAML, consulte {xref-keycloak-saml}[esta pĂĄgina].

Se vocĂȘ tiver uma configuraĂ§ĂŁo existente usando o protocolo SAML e quiser mudar para o protocolo OIDC, consulte <<_migrating_from_saml_to_oidc,esta seĂ§ĂŁo>>.

[#_prerequisites]
== PrĂ©-requisitos

* No Rancher, o Keycloak (SAML) estĂĄ desativado.
* VocĂȘ deve ter um https://www.keycloak.org/guides#getting-started[servidor Keycloak IdP] configurado.
* Siga a https://www.keycloak.org/docs/latest/server_admin/#proc-creating-oidc-client_server_administration_guide[documentaĂ§ĂŁo do Keycloak] para criar um novo cliente OIDC com as configuraĂ§Ă”es abaixo.
+
|===
| ConfiguraĂ§ĂŁo | Valor

| `+Client ID+`
| <client-id> (ex. `+rancher+`)

| `+Name+`
| <client-name> (ex. `+rancher+`)

| `+Client type+`
| `+OpenID Connect+`

| `+Client authentication+`
| `+ON+`

| `+Valid Redirect URI+`
| `+https://yourRancherHostURL/verify-auth+`
|===

* No novo cliente OIDC, crie https://www.keycloak.org/docs/latest/server_admin/#_protocol-mappers[Mappers] para expor os campos dos usuĂĄrios.
.. No menu de navegaĂ§ĂŁo, clique em **Clientes**.
.. Clique na aba **Lista de Clientes**.
.. Encontre e clique no cliente que vocĂȘ criou.
.. Clique na aba **Escopos do Cliente**.
.. Encontre e clique no link rotulado como `+<client-name>-dedicated+`. Por exemplo, se vocĂȘ nomeou seu cliente como `+rancher+`, procure o link chamado `+rancher-dedicated+`.
.. Clique na aba **Mappers**.
.. Clique em **Configurar um novo mapper**. Se vocĂȘ jĂĄ tiver mappers existentes configurados, clique na seta ao lado de **Adicionar mapper** e selecione **Por configuraĂ§ĂŁo**. Repita este processo e crie estes mappers:
*** Na tabela de mapeamentos, selecione **AssociaĂ§ĂŁo ao Grupo** e configure um novo "Mapper de Grupos" com as configuraĂ§Ă”es abaixo. Para configuraĂ§Ă”es que nĂŁo sĂŁo mencionadas, use o valor padrĂŁo.
+
|===
| ConfiguraĂ§ĂŁo | Valor

| `+Name+`
| `+Groups Mapper+`

| `+Mapper Type+`
| `+Group Membership+`

| `+Token Claim Name+`
| `+groups+`

| `+Full group path+`
| `+OFF+`

| `+Add to ID token+`
| `+OFF+`

| `+Add to access token+`
| `+OFF+`

| `+Add to user info+`
| `+ON+`
|===

*** Na tabela de mapeamentos, selecione **PĂșblico** e configure um novo "PĂșblico do Cliente" com as configuraĂ§Ă”es abaixo. Para configuraĂ§Ă”es que nĂŁo sĂŁo mencionadas, use o valor padrĂŁo.
+
|===
| ConfiguraĂ§ĂŁo | Valor

| `+Name+`
| `+Client Audience+`

| `+Mapper Type+`
| `+Audience+`

| `+Included Client Audience+`
| <client-name>

| `+Add to ID token+`
| `+OFF+`

| `+Add to access token+`
| `+ON+`
|===

*** Na tabela de mapeamentos, selecione **AssociaĂ§ĂŁo ao Grupo** e configure um novo "Caminho de Grupos" com as configuraĂ§Ă”es abaixo. Para configuraĂ§Ă”es que nĂŁo sĂŁo mencionadas, use o valor padrĂŁo.
+
|===
| ConfiguraĂ§ĂŁo | Valor

| `+Name+`
| `+Group Path+`

| `+Mapper Type+`
| `+Group Membership+`

| `+Token Claim Name+`
| `+full_group_path+`

| `+Full group path+`
| `+ON+`

| `+Add to ID token+`
| `+ON+`

| `+Add to access token+`
| `+ON+`

| `+Add to user info+`
| `+ON+`
|===

* Adicione os seguintes mapeamentos de funĂ§ĂŁo a todos os usuĂĄrios ou grupos que precisam consultar os usuĂĄrios do Keycloak.
+
[tabs]
======
UsuĂĄrios::
+
--
.. No menu de navegaĂ§ĂŁo, clique em **UsuĂĄrios**.
.. Clique no usuĂĄrio ao qual vocĂȘ deseja adicionar mapeamentos de funĂ§ĂŁo.
.. Clique na aba **Mapeamento de funĂ§ĂŁo**.
.. Clique em **Designar funĂ§ĂŁo**.
.. Selecione as seguintes funĂ§Ă”es:
*** consultar-usuĂĄrios
*** query-groups
*** ver-usuĂĄrios
.. Clique em **Designar**.
--

Grupos::
+
--
.. No menu de navegaĂ§ĂŁo, clique em **Grupos**.
.. Clique no grupo ao qual vocĂȘ deseja adicionar mapeamentos de funĂ§ĂŁo.
.. Clique na aba **Mapeamento de funĂ§ĂŁo**.
.. Clique em **Designar funĂ§ĂŁo**.
.. Selecione as seguintes funĂ§Ă”es:
*** consultar-usuĂĄrios
*** query-groups
*** ver-usuĂĄrios
.. Clique em **Designar**.
--
======

[#_configuring_keycloak_in_rancher]
== Configurando o Keycloak no Rancher

. Na interface do Rancher, clique em *â° > UsuĂĄrios e AutenticaĂ§ĂŁo*.
. Na barra de navegaĂ§ĂŁo Ă  esquerda, clique em *Provedor de AutenticaĂ§ĂŁo*.
. Selecione *Keycloak (OIDC)*.
. Preencha o formulĂĄrio *Configurar uma conta OIDC do Keycloak*. Para ajuda com o preenchimento do formulĂĄrio, consulte a <<_configuration_reference,referĂȘncia de configuraĂ§ĂŁo>>.
+
[NOTE]
====
Ao configurar a seĂ§ĂŁo **Pontos de Extremidade** usando a opĂ§ĂŁo **Gerar**, o Rancher inclui `+/auth+` como parte do caminho de contexto nos campos **Emissor** e **Endpoint de AutenticaĂ§ĂŁo**, que Ă© vĂĄlido apenas para o Keycloak 16 ou anterior. VocĂȘ deve configurar os pontos de extremidade usando a opĂ§ĂŁo **Especificar** para https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-17-0-0[Keycloak 17] e versĂ”es mais novas, que https://www.keycloak.org/migration/migrating-to-quarkus[migraram para o Quarkus].
====

. ApĂłs completar o formulĂĄrio *Configurar uma conta OIDC do Keycloak*, clique em *Habilitar*.
+
O Rancher redireciona vocĂȘ para a pĂĄgina de login do IdP. Insira as credenciais que autenticam com o IdP Keycloak para validar sua configuraĂ§ĂŁo do Keycloak no Rancher.
+

[NOTE]
====
VocĂȘ pode precisar desativar seu bloqueador de pop-ups para ver a pĂĄgina de login do IdP.
====


*Resultado:* O Rancher estĂĄ configurado para trabalhar com o Keycloak usando o protocolo OIDC. Seus usuĂĄrios agora podem fazer login no Rancher usando suas credenciais do Keycloak.

[#_configuration_reference]
== ReferĂȘncia de configuraĂ§ĂŁo

|===
| Campo | DescriĂ§ĂŁo

| ID do cliente
| O `+Client ID+` do seu cliente Keycloak.

| Segredo do Cliente
| O `+Secret+` gerado do seu cliente Keycloak. No console do Keycloak, selecione *Clientes*, selecione o cliente que vocĂȘ criou, selecione a aba *Credenciais* e copie o valor do campo `+Secret+`.

| Chave Privada / Certificado
| Um par chave/certificado para criar um shell seguro entre o Rancher e seu IdP. NecessĂĄrio se HTTPS/SSL estiver habilitado em seu servidor Keycloak.

| seguros
| Escolha se deseja usar os valores gerados para os campos `+Rancher URL+`, `+Issue+` e `+Auth Endpoint+` ou fornecer substituiĂ§Ă”es manuais se estiverem incorretos.

| URL do Keycloak
| A URL do seu servidor Keycloak.

| DomĂ­nio do Keycloak
| O nome do domĂ­nio em que o cliente Keycloak foi criado.

| URL do Rancher
| A URL do seu Servidor Rancher.

| Emissor
| A URL do seu IdP.

| Endpoint de AutenticaĂ§ĂŁo
| A URL para onde os usuĂĄrios sĂŁo redirecionados para autenticaĂ§ĂŁo.
|===

[#_migrating_from_saml_to_oidc]
== Migrando de SAML para OIDC

Esta seĂ§ĂŁo descreve o processo de transiĂ§ĂŁo de usar o Rancher com Keycloak (SAML) para Keycloak (OIDC).

. Reconfigurar o Keycloak.
.. Configure um novo `+OpenID Connect+` cliente de acordo com os <<_prerequisites,PrĂ©-requisitos>>. Certifique-se de que os mesmos `+Valid Redirect URIs+` estĂŁo configurados.
.. Configure mapeadores para o novo cliente de acordo com os <<_prerequisites,PrĂ©-requisitos>>.
. Antes de configurar o Rancher para usar o Keycloak (OIDC), o Keycloak (SAML) deve ser desabilitado primeiro.
.. Na interface do Rancher, clique em **â° > UsuĂĄrios e AutenticaĂ§ĂŁo**.
.. Na barra de navegaĂ§ĂŁo Ă  esquerda, clique em **Provedor de AutenticaĂ§ĂŁo**.
.. Selecione **Keycloak (SAML)**.
.. Clique em **Desabilitar**.
. Siga os passos em <<_configuring_keycloak_in_rancher,Configurando o Keycloak no Rancher>>.
+
[WARNING]
====
ApĂłs a configuraĂ§ĂŁo ser concluĂ­da, as permissĂ”es de usuĂĄrio do Rancher precisam ser reaplicadas, pois nĂŁo sĂŁo migradas automaticamente.
====

[#_oidc_support_for_pkce_extension]
== Suporte OIDC para ExtensĂŁo PKCE

include::shared:ROOT:partial$en/oidc-pkce-support.adoc[]

[#_annex_troubleshooting]
== Anexo: SoluĂ§ĂŁo de problemas

Se vocĂȘ estiver enfrentando problemas ao testar a conexĂŁo com o servidor Keycloak, primeiro verifique as opĂ§Ă”es de configuraĂ§ĂŁo do seu cliente OIDC. VocĂȘ tambĂ©m pode inspecionar os logs do Rancher para ajudar a identificar o que estĂĄ causando os problemas. Os logs de depuraĂ§ĂŁo podem conter informaĂ§Ă”es mais detalhadas sobre o erro. Por favor, consulte xref:faq/technical-items.adoc#_how_can_i_enable_debug_logging[Como posso habilitar o registro de depuraĂ§ĂŁo] nesta documentaĂ§ĂŁo.

Todas as entradas de log relacionadas ao Keycloak sĂŁo precedidas por `+[generic oidc]+` ou `+[keycloak oidc]+`.

[#_you_are_not_redirected_to_keycloak]
=== VocĂȘ nĂŁo Ă© redirecionado para o Keycloak.

Quando vocĂȘ preenche o formulĂĄrio *Configurar uma conta OIDC do Keycloak* e clica em *Habilitar*, vocĂȘ nĂŁo Ă© redirecionado para seu IdP.

Verifique a configuraĂ§ĂŁo do seu cliente Keycloak.

[#_the_generated_issuer_and_auth_endpoint_are_incorrect]
=== Os `+Issuer+` e `+Auth Endpoint+` gerados estĂŁo incorretos

No formulĂĄrio *Configurar uma conta OIDC do Keycloak*, altere *Endpoints* para `+Specify (advanced)+` e substitua os valores de `+Issuer+` e `+Auth Endpoint+`. Para encontrar os valores, vĂĄ para o console do Keycloak e selecione *ConfiguraĂ§Ă”es do DomĂ­nio*, selecione a aba *Geral* e clique em *ConfiguraĂ§ĂŁo do Endpoint OpenID*. A saĂ­da JSON exibe valores para `+issuer+` e `+authorization_endpoint+`.

[#_keycloak_error_invalid_grant_type]
=== Erro do Keycloak: "Invalid grant_type"

Em alguns casos, esta mensagem de erro pode ser enganosa e Ă© causada por configurar o `+Valid Redirect URI+` incorretamente.

[#_unable_to_see_groups_when_assigning_global_roles]
=== NĂŁo Ă© possĂ­vel ver grupos ao atribuir funĂ§Ă”es globais.

Se vocĂȘ usar um usuĂĄrio que nĂŁo faz parte de nenhum grupo para a configuraĂ§ĂŁo inicial, entĂŁo nĂŁo poderĂĄ pesquisar grupos ao tentar atribuir uma funĂ§ĂŁo global. Para resolver isso, vocĂȘ pode:

. Editar manualmente o objeto `+authconfig/keycloakoidc+` para habilitar a pesquisa de grupos.
 .. No servidor Rancher:
+
[,bash]
----
  kubectl edit authconfigs.management.cattle.io keycloakoidc
----
 .. Defina `+groupSearchEnabled: true+`.
 .. Grave as mudanĂ§as feitas.
. Reconfigure sua configuraĂ§ĂŁo do Keycloak OIDC usando um usuĂĄrio que esteja atribuĂ­do a pelo menos um grupo no Keycloak.

[#_configuring_oidc_single_logout_slo]
== Configurando o logout Ășnico OIDC (SLO)

include::shared:ROOT:partial$en/configure-slo-oidc.adoc[]
