= Plantillas de etiquetas
:revdate: 2025-09-08
:page-revdate: {revdate}

Elemental permite especificar _plantillas de etiquetas_ en las secciones `+spec.machineInventoryLabels+` y `+spec.machineInventoryAnnotations+` de los recursos xref:references/machineregistration-reference.adoc[MachineRegistration].

Su formato es el canónico `+key+`:``+value+`` utilizado en las etiquetas y anotaciones de Kubernetes.

Estas plantillas de etiquetas se convierten en etiquetas y anotaciones reales adjuntas a cada recurso xref:references/machineinventory-reference.adoc[de MachineInventory] creado durante la fase xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[de incorporación de la máquina].

Las etiquetas y anotaciones resultantes tienen el mismo `+key+` de la plantilla de etiquetas.

Se genera la dirección `+value+` asociada:

* *renderización de <<_label_templates_variables,`+label template variables+`>>* (si existe)
* *`+sanitizing+`* el valor resultante (sólo en el caso de las etiquetas)

[IMPORTANT]
====
La funcionalidad de plantillas de Elemental cubre también el campo xref:references/machineregistration-reference.adoc[MachineRegistration] `+spec.machineName+`, que define el nombre de host resultante de la máquina que se registra y el `+name+` del recurso xref:references/machineinventory-reference.adoc[MachineInventory] asociado.

Consulte la sección <<_custom_machine_names,Nombre de la máquina>> para obtener más detalles.
====


== Variables de las plantillas de etiquetas

Elemental Label Templating incluye un conjunto de variables predefinidas que pueden utilizarse dentro de `+value+` de las _plantillas de etiquetas_ especificadas en xref:references/machineregistration-reference.adoc[MachineRegistration].

La sintaxis utilizada para especificar las variables de las plantillas de etiquetas es:

`+${ _VARFAMILY_ \/ _VARPATH_ }+`

donde _VARFAMILY_ define un grupo (familia) de variables soportadas y _VARPATH_ define el nombre real de la variable dentro del grupo de familia perteneciente.

Elemental soporta actualmente las siguientes _familias de variables de plantilla_:

* xref:label-templates/label-templates-bios.adoc[*BIOS*]: *${ BIOS \/* _VARPATH_ *}*
* xref:label-templates/label-templates-baseboard.adoc[*BaseBoard*]: *${ BaseBoard \/* _VARPATH_ *}*
* xref:label-templates/label-templates-cpu.adoc[*CPU*]: *${ CPU \/* _VARPATH_ *}*
* xref:label-templates/label-templates-chassis.adoc[*Chasis*]: *${ Chasis \/* _VARPATH_ *}*
* xref:label-templates/label-templates-gpu.adoc[*GPU*]: *${ GPU \/* _VARPATH_ *}*
* xref:label-templates/label-templates-memory.adoc[*Memoria*]: *${ Memoria \/* _VARPATH_ *}*
* xref:label-templates/label-templates-network.adoc[*Red*]: *${ Red \/* _VARPATH_ *}*
* xref:label-templates/label-templates-product.adoc[*Producto*]: *${ Producto \/* _VARPATH_ *}*
* xref:label-templates/label-templates-runtime.adoc[*Tiempo de ejecución*]: *${ Runtime \/* _VARPATH_ *}*
* xref:label-templates/label-templates-storage.adoc[*Almacenamiento*]: *${ Storage \/* _VARPATH_ *}*

[CAUTION]
====
Todas las _familias de variables de plantilla_ (excepto _`+Random+`_) sólo están habilitadas si el campo `+elemental.registration.no-smbios+` de xref:references/machineregistration-reference.adoc[MachineRegistration] está configurado como `+false+` (por defecto).

Cuando el campo `+elemental.registration.no-smbios+` se establece en `+true+`, las máquinas registradoras no envían ningún dato necesario para renderizar las variables de plantilla, por lo que no habrá variables disponibles, salvo las variables *Aleatorias*, que son la única excepción notable.

Las variables *aleatorias* siempre están disponibles, ya que están incorporadas en el lado del operador. También son especiales, ya que se calculan una sola vez: véase la sección xref:label-templates/label-templates-random.adoc[Variables aleatorias de plantilla] para más detalles.
====


Las variables de plantilla se pueden mezclar con texto estático para formar las etiquetas reales asignadas axref:references/machineinventory-reference.adoc[(MachineInventories]).

[NOTE]
.Ejemplos de renderizado
====

* Etiqueta Plantilla de seguimiento del número de núcleos de CPU del host de registro (supongamos que el host tiene 4 núcleos):
 ** etiqueta original: *cpu: ${CPU\/TotalCores}* -cores
 ** etiqueta renderizada: *cpu: 4 núcleos*
* Etiqueta Plantilla de seguimiento del UUID SMBIOS del host de registro:
 ** etiqueta original: *sbios-UUID: ${Product\/UUID}*
 ** rendered label: *sbios-UUID: fd95324a-c26b-4e28-8727-1dcec293a0ec*
====


== Desinfección

Una vez que el valor de la plantilla <<_label_templates_variables,de>> etiqueta se ha renderizado de acuerdo con las <<_label_templates_variables,variables de plantilla de etiqueta>> incluidas, el valor resultante es `+sanitized+` antes de ser asignado a la etiqueta resultante.

* `+sanitization+` obliga a que el valor de la etiqueta sólo contenga letras (mayúsculas o minúsculas), números y los caracteres guión (`+-+`), punto (`+.+`) y guión bajo (`+_+`*):

Todos los caracteres no incluidos se sustituyen por un guión.

Cualquier carácter al principio y al final del valor de la etiqueta debe ser una letra o un número. Si no es así, se abandona.

Dos guiones consecutivos se sustituyen por uno.

[NOTE]
.Ejemplo de renderizado
====

* Plantilla de etiquetas con saneamiento de caracteres prohibidos:
 ** ¡etiqueta original: *sanitized: this:needs--sanitizing!*
 ** rendered label: *desinfectado: esto-necesita-desinfección*
====


== Uso de plantillas de etiquetas

Las Plantillas de etiquetas permiten adjuntar y actualizar automáticamente etiquetas y anotaciones al xref:references/machineinventory-reference.adoc[Inventario de máquinas] de cada anfitrión cada vez que un anfitrión se registra en el Operador Elemental.

[IMPORTANT]
====
El registro no sólo se produce durante la xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[fase de incorporación]: cada host se vuelve a registrar cada 30 minutos (y cada vez que se reinicia). Durante el nuevo registro, las plantillas de etiquetas del xref:references/machineregistration-reference.adoc[registro de máquinas] asociado se vuelven a evaluar y se añaden/actualizan en xref:references/machineinventory-reference.adoc[el inventario de máquinas].
====


Hay básicamente tres casos principales en los que las plantillas de etiquetas pueden ser útiles:

* para adjuntar datos de hardware al Catálogo Elemental.
* para añadir selectores que seleccionen hosts para el aprovisionamiento de clústeres.
* para definir una plantilla personalizada para los Nombres de Máquina.

=== Datos de hardware para el catálogo Elemental

Las variables de las Plantillas de Etiquetas se pueden utilizar para adjuntar datos de hardware a cada recurso xref:references/machineinventory-reference.adoc[MachineInventory] (que forman el Catálogo Elemental).

En este caso, las anotaciones pueden ser una mejor opción, ya que sus valores no están desinfectados.

=== Selectores para el aprovisionamiento de clústeres

El `+Label Templates+` se puede utilizar para generar etiquetas utilizadas para identificar y seleccionar máquinas con propiedades de hardware especiales para formar nuevos Kubernetes Clusters.

Las etiquetas adjuntas a cada xref:references/machineinventory-reference.adoc[MachineInventory] son elegibles para el _selector_ del recurso xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate] (consulte la sección xref:rancher-os-management/architecture/services/architecture-clusterdeployment.adoc[Aprovisionamiento de Kubernetes Cluster] para obtener más detalles).

=== Nombres de máquinas personalizados

El nombre de host de la máquina de embarque puede especificarse utilizando el campo xref:references/machineregistration-reference.adoc[MachineRegistration] `+spec.machineName+`.

`+spec.machineName+` se somete a los mismos procesos `+Label Templates' variables+` y `+sanitization+` reservados al campo `+spec.machineInventoryLabels+`.

[CAUTION]
====
Hay una diferencia notable entre los campos xref:references/machineregistration-reference.adoc[MachineRegistration] `+spec.machineName+` y `+spec.machineInventorylabels+`: durante el proceso <<_sanitization,de sanitización>> el guión bajo (`+_+`) es sustituido como los otros caracteres prohibidos (es decir, es sustituido por un guión: `+-+`). Esto es necesario ya que el guión bajo no está permitido en los nombres de host linux.
====


Para obtener más información sobre cómo definir el nombre de host para los hosts Elemental, consulte la sección xref:installation/hostname.adoc[Cómo/Personalizar el nombre de host].

[NOTE]
.Ejemplo de renderizado
====
* Defina una plantilla de nombre de host como `+SLE-Micro-[random string of 6 hexadecimal values]+`:
 ** MachineRegistration spec: *machineName: SLE-Micro-${Random\/Hex\/6}*
 ** Nombre de MachineInventory: *SLE-Micro-32ad41*
====


== Ejemplo de plantillas de etiquetas

.ejemplo de registro con variables de plantillas de etiquetas
[,yaml]
----
include::example$quickstart/registration-hardware-dhcphostname.yaml[]
----
