= 建築
:page-languages: [en、ja、ko、zh]。
:revdate: 2025-01-06
:page-revdate: {revdate}

== サーバーとエージェント

* サーバーノードは、`+k3s server+` コマンドを実行するホストとして定義され、コントロールプレーンとデータストア・コンポーネントはK3によって管理される。
* エージェント・ノードとは、`+k3s agent+` コマンドを実行するホストとして定義され、データストアやコントロールプレーンのコンポーネントは含まれない。
* サーバーもエージェントも、kubelet、コンテナランタイム、CNIを実行する。エージェントレスサーバーの実行に関する詳細は、xref:advanced.adoc#_running_agentless_servers_experimental[Advanced Optionsの]ドキュメントを参照してください。

image:how-it-works-k3s-revised.svg[]

== 組み込みDBによる単一サーバーのセットアップ

次の図は、SQLiteデータベースを組み込んだシングルノードのK3sサーバーを持つクラスタの例を示しています。

この構成では、各エージェントノードは同じサーバーノードに登録される。K3sユーザーは、サーバーノード上でK3s APIを呼び出すことで、Kubernetesリソースを操作することができる。

image:k3s-architecture-single-server.svg[単一サーバーによるK3sアーキテクチャ]

[#_high_availability_k3s]
== 高可用性K3

シングルサーバークラスタは様々なユースケースに対応できるが、Kubernetesコントロールプレーンのアップタイムが重要な環境では、HA構成でK3を実行できる。HA K3sクラスタは、以下のように構成される：

[tabs]
======
組み込みDB::
+
--
* Kubernetes APIを提供し、その他のコントロールプレーンサービスを実行する3つ以上の*サーバーノード*
* *組み込みetcdデータストア*（単一サーバー・セットアップで使用される組み込みSQLiteデータストアとは異なる）

image:k3s-architecture-ha-embedded.svg[高可用性サーバーによるK3sアーキテクチャ]
--

外部DB::
+
--
* Kubernetes APIを提供し、他のコントロールプレーンサービスを実行する2つ以上の*サーバーノード*
* *外部データストア*（MySQL、PostgreSQL、etcdなど）

image:k3s-architecture-ha-external.svg[高可用性サーバーと外部DBによるK3sアーキテクチャ]
--
======

== エージェントノードの固定登録アドレス

高可用性サーバー構成では、下図に示すように、各ノードは固定登録アドレスを使用してKubernetes APIに登録することもできる。

登録後、エージェントノードはサーバーノードの1つに直接接続を確立する。

image:k3s-production-setup.svg[エージェント登録 HA]

[#_how_agent_node_registration_works]
== エージェントノード登録の仕組み

エージェントノードは、`+k3s agent+` プロセスによって開始されるウェブソケット接続で登録され、接続はエージェントプロセスの一部として実行されるクライアント側のロードバランサによって維持される。最初は、エージェントはポート6443でローカルのロードバランサを介してスーパーバイザ（およびkube-apiserver）に接続します。ロードバランサは接続可能なエンドポイントのリストを保持する。デフォルトの（そして最初は唯一の）エンドポイントは、`+--server+` アドレスのホスト名によってシードされる。クラスタに接続すると、エージェントはデフォルト名前空間のKubernetesサービスエンドポイントリストからkube-apiserverアドレスのリストを取得します。これらのエンドポイントはロードバランサーに追加され、ロードバランサーはクラスタ内のすべてのサーバーへの安定した接続を維持し、個々のサーバーの停止を許容するkube-apiserverへの接続を提供します。

エージェントは、`+/etc/rancher/node/password+` に格納されているノードのクラスター秘密鍵とランダムに生成されたパスワードを使用してサーバーに登録します。サーバーは個々のノードのパスワードをKubernetesシークレットとして保存し、それ以降の試行では同じパスワードを使用する必要があります。ノードのパスワード秘密は、`+kube-system+` 名前空間に、`+<host>.node-password.k3s+` というテンプレートを使った名前で格納されます。これはノードIDの完全性を保護するためである。

エージェントの`+/etc/rancher/node+` ディレクトリが削除された場合、または既存の名前を使用してノードに再参加したい場合は、そのノードをクラスタから削除する必要があります。これで古いノード・エントリとノード・パスワードの秘密の両方がクリーンアップされ、ノードがクラスタに（再）参加できるようになります。

ホスト名を頻繁に再利用するが、ノードパスワードの秘密を削除できない場合、`+--with-node-id+` フラグを使用して K3s サーバーまたはエージェントを起動することで、一意のノード ID をホスト名に自動的に付加することができます。有効にすると、ノードIDも`+/etc/rancher/node/+` に格納される。
