= よくあるご質問
:page-languages: [en、ja、ko、zh]。
:revdate: 2024-09-11
:page-revdate: {revdate}

FAQは定期的に更新され、K3sについてユーザーからよく寄せられる質問にお答えしています。

== K3sはKubernetesの代替となるか？

K3sはCNCF認定のKubernetesディストリビューションであり、標準的なKubernetesクラスタに要求されるすべてのことができる。より軽量化されただけだ。詳しくはxref:introduction.adoc[メイン・]ドキュメントのページをご覧ください。

== Traefikの代わりに自分のIngressを使うには？

`+--disable=traefik+` 、K3sサーバーを起動し、イングレスをデプロイするだけです。

== K3sはWindowsに対応していますか？

現時点では、K3sはWindowsをネイティブにサポートしていませんが、将来的にはこのアイデアを受け入れるつもりです。

== サーバーとエージェントとは何ですか？

サーバとエージェントを構成するコンポーネントの内訳については、xref:architecture.adoc[アーキテクチャのページを]参照してください。

== ソースからビルドするには？

K3shttps://github.com/k3s-io/k3s/blob/main/BUILDING.md[.mdを] BUILDINGご参照ください。

== K3のログは？

K3sのログの保存場所は、K3sの実行方法やノードのOSによって異なります。

* コマンドラインから実行すると、ログは標準出力と標準エラーに送られる。
* openrc で実行している場合、ログは`+/var/log/k3s.log+` に作成されます。
* Systemd の下で実行されている場合、ログは Journald に送られ、`+journalctl -u k3s+` を使って見ることができる。
* ポッドのログは`+/var/log/pods+` で見ることができる。
* コンテナのログは`+/var/lib/rancher/k3s/agent/containerd/containerd.log+` で見ることができる。

K3sを起動するときに`+--debug+` フラグを使用することで、より詳細なログを生成することができます（または設定ファイルで`+debug: true+` ）。

Kubernetesは、`+klog+` として知られるロギングフレームワークを使用しており、プロセス内のすべてのコンポーネントに対して単一のロギング設定を使用している。
K3sはすべてのKubernetesコンポーネントを単一のプロセス内で実行するため、個々のKubernetesコンポーネントに対して異なるログレベルや宛先を設定することはできません。
`+-v=<level>+` 、`+--vmodule=<module>=<level>+` コンポーネントの引数を使っても、期待した効果は得られないだろう。

その他のログオプションについては、xref:advanced.adoc#_additional_logging_sources[追加のログソースを]参照してください。

== K3をDockerで実行できますか？

はい、DockerでK3を実行する方法は複数あります。詳しくは「xref:advanced.adoc#_running_k3s_in_docker[詳細オプション]」をご覧ください。

== K3sサーバーとエージェント・トークンの違いは何ですか？

K3のジョイントークンの管理については、xref:cli/token.adoc[`+k3s token+` コマンドのドキュメントを]参照してください。

== K3の異なるバージョンの互換性は？

一般的には、https://kubernetes.io/docs/setup/release/version-skew-policy/[]Kubernetesの適用される。

つまり、サーバーはエージェントより新しくてもよいが、エージェントはサーバーより新しくすることはできない。

== 問題があるのですが、どこに助けを求めればいいですか？

K3のデプロイに問題があるのなら、そうすべきだ：

. xref:known-issues.adoc[既知の問題の]ページを確認してください。
. xref:installation/requirements.adoc#_operating_systems[OSの追加準備が]完了していることを確認してください。`+k3s check-config+` を実行し、パスすることを確認する。
. K3shttps://github.com/k3s-io/k3s/issues[Issues]andhttps://github.com/k3s-io/k3s/discussions[Discussionsを]検索して、あなたの問題と一致するものを探してください。
. https://slack.rancher.io/[]RancherK3s チャンネルに参加して、助けを求めてください。
. K3s Githubにhttps://github.com/k3s-io/k3s/issues/new/choose[New Issueを]投稿してください。
