include::partial$variables.adoc[]

= Autoriser les évaluations dans l'espace de noms du contrôleur d'admission
:description: Comment configurer le contrôleur d'admission pour qu'il autorise l'évaluation des politiques dans son propre espace de noms ?
:keywords: ["policies", "ClusterAdmissionPolicies", "ClusterAdmissionPoliciesGroup", "configuration", "namespaces"].
:doc-persona: ["kubewarden-operator"]
:doc-type: ["howto"]
:doc-topic: ["operator-manual", "policies"]

Par défaut, le contrôleur d'admission n'autorise pas les politiques à évaluer les ressources dans son propre espace de noms. Cela permet d'éviter les erreurs de configuration qui pourraient interrompre l'installation de {short-project-name}.

Cette mesure de sécurité est mise en œuvre à deux niveaux. La première couche est contrôlée par l'indicateur CLI `+--always-accept-admission-reviews-on-deployments-namespace+`.
Cette option, activée par défaut dans les diagrammes Helm, permet au contrôleur de configurer la variable d'environnement `+KUBEWARDEN_ALWAYS_ACCEPT_ADMISSION_REVIEWS_ON_NAMESPACE+`dans les déploiements de PolicyServer. Cette variable indique au serveur de politiques de toujours accepter les examens d'admission provenant de l'espace de noms défini dans la variable. La deuxième couche est le contrôleur d'admission lui-même, qui ajoute par défaut un sélecteur d'espace de noms aux politiques applicables à l'ensemble du cluster afin d'ignorer l'espace de noms dans lequel le contrôleur s'exécute.

Toutefois, dans certains scénarios, les administrateurs de clusters peuvent souhaiter que les politiques évaluent les ressources dans cet espace de noms. Cette page explique comment y parvenir en désactivant les deux couches de protection.

== Supprimer la variable d'environnement PolicyServer protection

La première étape consiste à configurer le contrôleur pour qu'il ne définisse pas la variable d'environnement`+KUBEWARDEN_ALWAYS_ACCEPT_ADMISSION_REVIEWS_ON_NAMESPACE+` dans les déploiements de PolicyServer.

Pour ce faire, mettez à jour votre installation {short-project-name} et définissez la valeur`+alwaysAcceptAdmissionReviewsOnDeploymentsNamespace+` de la carte`+kubewarden-controller+` Helm sur `+false+`:

[source,console]
----
helm upgrade -n kubewarden
  --set "alwaysAcceptAdmissionReviewsOnDeploymentsNamespace=false"
  kubewarden-controller kubewarden/kubewarden-controller
----

Cette modification permet aux serveurs de politiques d'évaluer des ressources provenant de n'importe quel espace de noms.
Une fois cela fait, les politiques peuvent être configurées pour évaluer les examens d'admission à partir de l'espace de noms {short-project-name}.

== Configurer les politiques pour évaluer les ressources dans l'espace de noms du contrôleur d'admission

Pour permettre à une politique d'évaluer les ressources créées dans l'espace de noms du contrôleur d'admission, déployez des politiques à l'échelle du cluster avec le champ `+allowInsideAdmissionControllerNamespace+`de la spécification défini sur `+true+`:

[NOTE]
.Et les politiques d'espacement des noms ?
====
Ce champ de spécification n'est disponible que dans les politiques applicables à l'ensemble d'un cluster.
Comme les politiques d'espace de noms évaluent les ressources dans l'espace de noms où elles sont déployées, il n'est pas utile d'ajouter ce champ à leurs CRD.
En outre, l'espace de noms du contrôleur d'admission devrait être géré par les opérateurs de grappes, qui peuvent décider d'y déployer une politique.
====

[source,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: PSP
    io.kubewarden.policy.severity: medium
  name: pod-privileged-policy
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:v1.0.10
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
  mutating: false
  allowInsideAdmissionControllerNamespace: true
----

Cette option de configuration, qui est `+false+` par défaut, permet au contrôleur de ne pas ajouter le sélecteur d'espace de noms qui exclut l'espace de noms du contrôleur d'admission, ce qui permet à la stratégie d'évaluer les ressources de tous les espaces de noms, y compris cet espace de noms.

[NOTE]
.Qu'en est-il de mes sélecteurs d'espace de noms personnalisés ?
====
Les politiques CRD permettent également aux utilisateurs de définir leurs propres sélecteurs d'espace de noms. Ces sélecteurs ne sont pas modifiés. Cela signifie que si un utilisateur définit un sélecteur qui ne tient pas compte de l'espace de noms {short-project-name}, la politique continuera d'ignorer cet espace de noms comme prévu.
====