= StackPacksについて
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilityセルフホストv5.1.x

== 概要

StackPackは、SUSE Observabilityの機能を拡張し、外部システムとの自動統合を提供します。これらは、SUSE ObservabilityのStackPacksページから簡単にインストールおよびアンインストールできます。

StackPackにはアドオンとインテグレーションの2種類があります。利用可能なStackPackアドオンと統合は、SUSE Observability UIの*StackPacks*ページで確認できます。

== StackPackのインストールまたはアンインストール

StackPackは、SUSE Observabilityの*StackPacks*ページからインストールおよびアンインストールできます。StackPackのインストールとアンインストールの完全な手順が提供されています。

[NOTE]
====
*注意してほしい：*

* StackPackは、*手動での*インストール手順や外部システムの設定を必要とする場合があります。説明書をよくお読みください。
* StackPackまたはStackPackインスタンスをアンインストールすると、*そのStackPack(インスタンス)を介して受信したすべてのデータがSUSE Observabilityから削除されます。*
* 外部システムにStackPackコンポーネントを（手動で）設定またはインストールする場合は、別途アンインストールする必要があります。

====


=== StackPackインスタンス

StackPackの中には、外部システムの複数のアカウントに接続できるものもあります。各アカウントは、StackPackの個別のインスタンスで設定される。

たとえば、AWS StackPackは複数のAWSアカウントに接続し、すべてのアカウントの情報をSUSE Observabilityにまとめることができます。アカウントごとに、そのAWSアカウントからデータを受信するために必要な情報を使用して、別のSUSE Observabilityインスタンスが構成されます。

== StackPackのアップグレード

[CAUTION]
====
StackPackがアップグレードされると、*そのStackPackの設定項目に加えられた変更は上書きさ*れます。詳細は、xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[ロックされた設定項目を]参照。
====


新しいStackPackのバージョンが利用可能になると、SUSE Observability UIのStackPackページにアラートが表示され、アップグレードの詳細を表示したり、リリースノートを読んだりすることができます。新しいリリースが現在インストールされているバージョンからのマイナーアップグレードの場合は、ここからStackPackをアップグレードすることもできます。

=== StackPack新マイナーバージョン

StackPackの新しいマイナーバージョンにアップグレードするには、SUSE Observability UIのStackPackページで*UPGRADE NOWを*クリックします。

アップグレードすると、すべての StackPack 設定項目が上書きされることに注意してください。これらに加えられた変更を引き続き使用するには、StackPack をアップグレードする際に既存の設定を*保持*するを選択してください。詳細は、xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[ロックされた設定項目を]参照。

=== StackPackの新しいメジャーバージョン

[CAUTION]
====
StackPackがアップグレードされると、*そのStackPackの設定項目に加えられた変更は上書きさ*れます。詳細は、xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[ロックされた設定項目を]参照。
====


StackPackの新しいメジャーバージョンにアップグレードするには、StackPackをxref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[アンインストールして再インストール]します。

[TIP]
====

アップグレード後も、カスタマイズされたStackPack設定項目への変更を引き続き使用できます：

. アップグレードする前に、各カスタマイズ項目をエクスポートしてください：
 ** SUSE Observability UIの*設定*ページに移動します。
 ** 各カスタマイズ項目の *...*をクリックします。
. StackPackをアップグレードする（アンインストールと再インストール）。
. エクスポートされた各アイテムの`+name+` と`+identifier+` を変更する：
 ** テキストエディターでエクスポートファイルを開く。
 ** トップレベルの`+name+` 、`+identifier+` フィールドを編集する。
 ** エクスポートを保存します。
. 更新されたエクスポートファイルをxref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[インポート]します。
. カスタマイズされた設定項目はSUSE Observabilityで利用できるようになり、新しくインストールされたStackPack設定項目にコピーできます。

====


== ロックされた設定項目

StackPackには、StackPack(インスタンス)のインストール時にインストールされるSUSE Observabilityの設定情報が含まれています。とりわけ、コンポーネント・テンプレート、関数、コンポーネント・アクション、ビューがこれにあたる。StackPackがアップグレードされると、*以前のバージョンのStackPackがインストールした設定項目は、新しいバージョンのStackPackの項目で上書きされます。*つまり、これらの設定項目に手動で加えられた変更は、StackPackがアップグレードされたときに上書きされます。

アップグレード時に上書きされるような、StackPackによってインストールされた設定項目にユーザーが変更を加えることを防ぐため、これらの設定項目はデフォルトで*ロック*されています。つまり、ユーザーによる変更から保護されており、変更する前に明示的に*ロックを解除する*必要がある。

[TIP]
====

xref:/setup/data-management/backup_restore/configuration_backup.adoc[設定項目のバックアップを取る]ことができます。設定項目のロック状態は、設定バックアップの一部としてエクスポートされないことに注意してください。
====

