= 网络服务
:page-languages: [EN, JA, KO, ZH]
:revdate: 2026-01-05
:page-revdate: {revdate}

本页介绍 CoreDNS、Traefik 入口控制器、网络策略控制器和 ServiceLB 负载平衡器控制器在 K3s 中的工作原理。

有关 Flannel 配置选项和后端选择的详情，或如何设置自己的 CNI，请参阅 "xref:networking/basic-network-options.adoc[安装网络]选项 "页面。

有关需要为 K3 打开哪些端口的信息，请参阅xref:installation/requirements.adoc#_networking[网络要求]。

== CoreDNS

CoreDNS 会在服务器启动时自动部署。要禁用它，请使用`+--disable=coredns+` 选项配置群集中的所有服务器。

如果不安装 CoreDNS，则需要自行安装集群 DNS 提供商。

== 特拉菲克入侵控制器

https://traefik.io/[Traefik]是一款现代 HTTP 反向代理和负载平衡器，可轻松部署微服务。它简化了设计、部署和运行应用程序时的网络复杂性。

特拉菲克入口控制器部署了一个使用 80 和 443 端口的负载平衡器服务，并在其管理的入口资源状态中公布负载平衡器服务的外部 IP。

默认情况下，ServiceLB 将使用群集中的所有节点来托管特捷飞克负载平衡器服务，这意味着端口 80 和 443 将无法用于其他 HostPort 或 NodePort pod，并且入口资源的状态将显示所有群组成员的节点 IP。

要限制特拉菲克使用的节点，并进而限制入口状态中公布的节点 IP，可以按照下面 "<<_controlling_servicelb_node_selection,控制 ServiceLB 节点选择>>"一节中的说明来限制 ServiceLB 在哪些节点上运行，或者将某些节点添加到负载平衡器池中，并通过在特拉菲克 HelmChartConfig 中设置匹配标签将特拉菲克服务限制在该池中。

特拉菲克默认在启动服务器时部署。默认图表值可在`+/var/lib/rancher/k3s/server/manifests/traefik.yaml+` 中找到，但不应手动编辑该文件，因为 K3s 会在启动时用默认值替换该文件。相反，您应该在`+/var/lib/rancher/k3s/server/manifests+` 中创建一个额外的`+HelmChartConfig+` 清单来定制特拉菲克。有关详细信息和示例，请参阅xref:add-ons/helm.adoc#_customizing_packaged_components_with_helmchartconfig[使用 HelmChartConfig 自定义打包组件]。有关可能配置值的更多信息，请参阅`+values.yaml+` https://github.com/k3s-io/k3s-charts/tree/main/charts/traefik[ Traefik 舵手图]，该图随 K3s 版本一起提供。

要从集群中移除特拉菲克，请使用`+--disable=traefik+` 标志启动所有服务器。更多信息，请参阅xref:installation/packaged-components.adoc[管理打包组件]。

有关 K3s 随附的特拉菲克特定版本的详细信息，请查阅您的版本的发行说明。

* 从**1.32**开始的 K3s 版本包含特拉菲克 v3。K3s 升级时，现有的特拉菲克 v2 会自动升级到 v3。
  特拉菲克 v3 应与 v2 的配置兼容；更多信息请查阅上游https://doc.traefik.io/traefik/migrate/v2-to-v3/[到 v3 的迁移] v2文档。
* K3s**1.21**至**1.31**版本包含特拉菲克 v2，除非已安装了特拉菲克 v1，在这种情况下，特拉菲克尚未升级到 v2。
* K3s**1.20**及**更早**版本包含特拉菲克 v1。

== 网络策略控制器

K3s 包括一个嵌入式网络策略控制器。底层实现是https://github.com/cloudnativelabs/kube-router[的] kube-routernetpol 控制器库（没有其他 kube-router 功能），可在https://github.com/k3s-io/k3s/tree/main/pkg/agent/netpol[] 找到。

要禁用它，请使用`+--disable-network-policy+` 标志启动每个服务器。

[NOTE]
====
如果更改 K3s 配置禁用网络策略控制器，则不会删除网络策略 iptables 规则。要在禁用网络策略控制器后清理已配置的 kube-router 网络策略规则，请使用`+k3s-killall.sh+` 脚本，或使用`+iptables-save+` 和`+iptables-restore+` 进行清理。必须在群集中的所有节点上手动运行这些步骤。

----
iptables-save | grep -v KUBE-ROUTER | iptables-restore
ip6tables-save | grep -v KUBE-ROUTER | ip6tables-restore
----
====

[#_service_load_balancer]
== 服务负载平衡器

任何 LoadBalancer 控制器都可以部署到 K3s 集群。默认情况下，K3s 提供一个名为https://github.com/k3s-io/klipper-lb[ServiceLB]（原 Klipper LoadBalancer）的负载平衡器，它使用可用的主机端口。

上游 Kubernetes 允许创建 LoadBalancer 类型的服务，但不包括默认的负载平衡器实现，因此在安装之前，这些服务将保持`+pending+` 。许多托管服务需要亚马逊 EC2 或微软 Azure 等云提供商提供外部负载平衡器。相比之下，K3s ServiceLB 无需云提供商或任何额外配置，即可使用负载平衡器服务。

=== ServiceLB 如何工作

ServiceLB 控制器会监控将`+spec.type+` 字段设置为`+LoadBalancer+` 的 Kuberneteshttps://kubernetes.io/docs/concepts/services-networking/service/[服务]。

`+kube-system+` 命名空间中为每个 LoadBalancer 服务创建了link:https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSet]。该 DaemonSet 会在每个节点上创建带有`+svc-+` 前缀的 ServiceLB Pod。这些 pod 使用服务端口来利用 hostPort，因此只能部署在有该端口的节点上。如果没有任何具有该端口的节点可用，则 LB 将保持 "待定 "状态。请注意，只要使用不同的端口，就可以在同一节点上公开多个服务。

当 ServiceLB Pod 在配置了外部 IP 的节点上运行时，该节点的外部 IP 会通过`+ipMode: VIP+` 填充到服务的`+status.loadBalancer.ingress+` 地址列表中。否则，将使用节点的内部 IP。

如果外部 IP 的流量受link:https://en.wikipedia.org/wiki/Network_address_translation[网络地址转换 (NAT)]限制（例如，在公共云中使用节点的公共 IP 作为外部 IP），则流量会通过 hostPort 路由进入 ServiceLB pod。然后，pod 使用 iptables 将流量转发到服务的 ClusterIP 地址和端口。如果流量不受 NAT 限制，而是以与 LoadBalancer 地址匹配的目标地址到达，则流量会被拦截（通常由 kube-proxy iptables 链或 ipvs 拦截），并转发到服务的 ClusterIP 地址和端口。

=== 使用方法

在 K3s 中创建 https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[负载平衡器类型的]。

[WARNING]
.已知问题
====
如果外部流量通过 NAT 到达节点（如在公共云中），并且您需要`+externalTrafficPolicy=local+` 来保存客户端源 IP，请不要为任何节点定义 k3s 配置`+node-external-ip+` ，因为这样做无法正常工作
====

=== 控制服务 LB 节点选择

将`+svccontroller.k3s.cattle.io/enablelb=true+` 标签添加到一个或多个节点后，ServiceLB 控制器就会切换到允许列表模式，只有带有该标签的节点才有资格托管 LoadBalancer pod。仍未标记的节点将被 ServiceLB 排除在外。

[NOTE]
====
默认情况下，节点不带标签。只要所有节点都未标记，ServiceLB 就会使用所有端口可用的节点。
====


=== 创建 ServiceLB 节点池

要为 LoadBalancer 选择特定的节点子集来托管 pod，可将`+enablelb+` 标签添加到所需的节点，并在节点和服务上设置匹配的`+lbpool+` 标签值。例如

. 用`+svccontroller.k3s.cattle.io/lbpool=pool1+` 和 `+svccontroller.k3s.cattle.io/enablelb=true+`
. 将节点 C 和节点 D 标为`+svccontroller.k3s.cattle.io/lbpool=pool2+` 和 `+svccontroller.k3s.cattle.io/enablelb=true+`
. 在 443 端口上创建一个 LoadBalancer 服务，标签为`+svccontroller.k3s.cattle.io/lbpool=pool1+` 。该服务的 DaemonSet 只能将 Pod 部署到节点 A 和节点 B。
. 在 443 端口上创建另一个 LoadBalancer 服务，标签为`+svccontroller.k3s.cattle.io/lbpool=pool2+` 。DaemonSet 只会将 Pod 部署到节点 C 和节点 D。

=== 禁用 ServiceLB

要禁用 ServiceLB，请使用`+--disable=servicelb+` 标志配置群集中的所有服务器。

如果要运行不同的 LB，如 MetalLB，则必须这样做。

== 部署外部云控制器管理器

K3s 提供嵌入式云控制器管理器 (CCM)，其功能如下：

* 托管<<_service_load_balancer, 服务负载平衡器>>LoadBalancer 控制器。
* 清除`+node.cloudprovider.kubernetes.io/uninitialized+` 污点。
* 根据`+--node-ip+`,`+--node-external-ip+`,`+--node-internal-dns+` 和`+--node-external-dns+` 标志设置节点地址字段。

在部署外部 CCM 之前，必须使用`+--disable-cloud-controller+` 标志启动所有 K3s 服务器，以禁用嵌入式 CCM。使用外部 CCM 时，节点地址将由云提供商实例元数据 API 提供，而不是 K3s 标志值。

[NOTE]
====
如果禁用内置 CCM，并且不部署和正确配置外部替代品，节点将继续受到污染，无法chedulable。
====

