= Optionen zur Authentifizierung
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

SUSE Observability ist standardmäßig mit einer xref:/setup/security/authentication/file.adoc[Einzelpasswort-Authentifizierung] mit dem Benutzer admin und einem Zufallspasswort konfiguriert xref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[, das während der Installation festgelegt wird]. Dadurch werden die Benutzer mit einem einfachen Geheimnis auf dem Server authentifiziert. Dies ist jedoch keine produktionsreife Einrichtung.

Zur Verbesserung der Sicherheit kann SUSE Observability so konfiguriert werden, dass genau einer der folgenden Authentifizierungsmechanismen verwendet wird (anstelle des Standard-Admin-Benutzers):

* xref:/setup/security/authentication/single_password.adoc[Einzelnes Passwort]
* xref:/setup/security/authentication/file.adoc[Datei-basiert]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[Offene ID-Verbindung (OIDC)]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak (eine spezialisierte Version von OIDC)]

[NOTE]
====
Die Authentifizierungskonfiguration ist Teil des Helm-Diagramms, und jede Änderung löst automatisch einen Neustart der Pods aus, die dies erfordern.
====


== Benutzerrollen

Wenn ein Benutzer authentifiziert wurde, werden ihm in der Regel Berechtigungen zugewiesen, die auf den Rollen basieren, die er innehat. Die Dokumentation für die spezifischen Authentifizierungsmechanismen enthält auch Beispiele für die Zuordnung der Rollen oder Gruppen aus den externen Systemen zu den 4 Standardrollen von SUSE Observability:

* *Gast* - kann Informationen einsehen, aber keine Änderungen vornehmen.
* *Kubernetes Troubleshooter* - kann alle Informationen einsehen und die Konfiguration von Monitoren und Metriken einsehen und ändern.
* *Power User* - kann alle Konfigurationen einsehen und ändern und StackPacks installieren.
* *Administrator* - kann den Inhalt von SUSE Observability anzeigen und ändern. So können Sie beispielsweise die gesamte Konfiguration einsehen, StackPacks installieren, Benutzerberechtigungen erteilen und entziehen und (neue Versionen von) StackPacks hochladen.

Wenn Sie entscheiden, welche Rollen Sie Ihren Benutzern zuweisen, sollten Sie nur eine kleine Gruppe von Plattformadministratoren und Administratoren haben. Zum Beispiel nur die Techniker, die für die Installation von SUSE Observability und die Erstkonfiguration zuständig sind. Administratorbenutzer können den Zugriff auf SUSE Observability verwalten und entscheiden, welche StackPacks verwendet werden können. Sie können die Installation von StackPacks und andere Feinabstimmungen der Konfiguration an eine größere Anzahl von Benutzern mit der Power-User-Rolle delegieren. Plattformadministratoren können die Datenbank löschen, die Einstellungen für die Datenaufbewahrung ändern, Protokolle einsehen und andere Aufgaben der Plattformverwaltung durchführen.

Es ist auch möglich, weitere Rollen hinzuzufügen, siehe die Seite xref:/setup/security/rbac/rbac_roles.adoc[Rollen (RBAC)] und die anderen xref:/setup/security/rbac/README.adoc[RBAC-Dokumentationsseiten]
