include::partial$variables.adoc[]
= 脅威モデル
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: アドミッション・コントロールの脅威モデルを読み、理解することで、Kubernetes内の安全なデフォルトを確保しながら、状況に応じた独自の脅威モデルを考案することができます。
:doc-persona: ["kubewarden-all"]
:doc-topic: ["security", "threat-model"]
:doc-type: ["reference"]
:keywords: [kubernetes」、「入場制御脅威モデル」、「kubewarden」]。
:sidebar_label: 脅威モデル
:sidebar_position: 80
:current-version: {page-origin-branch}

https://github.com/kubernetes/community/tree/master/sig-security[Kubernetes Security Special Interest Group (SIG)]は、Kubernetesのアドミッションコントロール脅威モデルを定義した。{project-name} チームは、この脅威モデルに照らして{short-project-name}を継続的に評価し、安全なデフォルトを提供するよう努めている。{short-project-name} 、管理者はこの脅威モデルを読み、理解し、必要に応じて状況別の脅威モデルを独自に考案するために利用することを推奨する。

各脅威の詳細は、https://github.com/kubernetes/sig-security/tree/main/sig-security-docs/papers/admission-control[SIGセキュリティが発表した文書]に記載されている。

== Kubernetesの脅威

=== 脅威 1 - 攻撃者がトラフィックでウェブフックの操作を妨害する

==== シナリオ

ネットワークレベルでWebhookエンドポイントにアクセスできる攻撃者は、大量のトラフィックを送信し、アドミッション・コントローラに効果的なサービス拒否を引き起こす可能性がある。

==== 緩和

Webhookのクローズに失敗しました。何らかの理由でWebhookが時間内に応答しない場合、APIサーバーはリクエストを拒否する必要があります。
これは{short-project-name} のデフォルトの動作である。

Failing closedとは、何らかの理由で{short-project-name} が応答しなくなったりクラッシュしたりした場合、APIサーバーがデフォルトでリクエストを拒否することを意味する。
これは、{short-project-name} によってリクエストが通常受け入れられる場合でも同様である。

=== 脅威2 - 攻撃者は、タイムアウトを引き起こす複雑な処理を必要とするワークロードを渡す。

==== シナリオ

ネットワークレベルでアドミッション・コントローラにアクセスできる攻撃者は、複雑な処理を必要とするリクエストをアドミッション・コントローラに渡し、アドミッション・コントローラがワークロードを処理するために計算能力を使用するため、タイムアウトを引き起こす。

==== 緩和

Webhookのクローズと発信者の認証に失敗しました。
これは{short-project-name} のデフォルトの動作である。

=== 脅威 3 - 攻撃者がウェブフックの設定ミスを悪用して迂回する。

==== シナリオ

クラスタ内にワークロードを作成する権限を持つ攻撃者は、誤設定を悪用して意図したセキュリティ制御をバイパスすることができる。

==== 緩和

ウェブフックの設定を定期的に見直すことで、問題を発見することができます。

=== 脅威4 - 攻撃者がKubernetesのWebhookオブジェクトを削除または修正する権限を持っている

==== シナリオ

Kubernetes APIにアクセスできる攻撃者は、クラスタ内のWebhookオブジェクトを削除するのに十分な権限を持っている。

==== 緩和

RBACの権限は厳密に管理されるべきである。

==== やるべきこと

RBACのほとんどは、今回の議論の範囲外だ。しかし、{short-project-name} ユーザーを支援するために、次のようなことが順次行われる予定である：

* 最低限実装すべきRBACの方向性。
* RBACの変更を検出し、ブロックするポリシーの提供と文書化。

=== 脅威 5 - 攻撃者がウェブフックの有効な認証情報にアクセスする

==== シナリオ

攻撃者は、アドミッションコントローラWebhookの有効なクライアント認証情報へのアクセスを得る。

==== 緩和

Webhookのクローズに失敗しました。
これは{short-project-name} のデフォルトの動作である。

=== 脅威6 - 攻撃者がクラスタ管理者クレデンシャルにアクセスする

==== シナリオ

攻撃者がKubernetesクラスタのクラスタ管理者レベルのクレデンシャルにアクセスする。

==== 緩和

N/A

=== 脅威7 - 攻撃者がコンテナ・ネットワーク上のトラフィックをスニッフィングする。

==== シナリオ

コンテナネットワークにアクセスできる攻撃者は、APIサーバーとアドミッションコントローラーのウェブフック間のトラフィックを盗聴できる。

==== 緩和

ウェブフックはすべてのトラフィックにTLS暗号化を使用しているため、{short-project-name} 。

=== 脅威8 - 攻撃者はウェブフックに対してMITM攻撃を行う。

==== シナリオ

NET_RAW機能にアクセスできるコンテナネットワーク上の攻撃者は、MITMツールを使用して、APIサーバーとアドミッションコントローラウェブフック間のトラフィックを傍受しようとすることができる。

==== 緩和

Webhooks用のmTLS認証でクラスタを構成し、{short-project-name} スタックでmTLS機能を有効にします。あるいは、Network PoliciesをサポートするCNIを使ってmTLSをセットアップする。詳細については、xref:/reference/security-hardening/webhooks-hardening.adoc[「相互TLSによる安全なウェブフック]」を参照してください。

https://artifacthub.io/packages/kubewarden/capabilities-psp/capabilities-psp[capabilities-psp]ポリシーを使用し、NET_RAW 機能をドロップするように設定します。

=== 脅威 9 - 攻撃者はなりすましによってウェブフックからトラフィックを盗む

==== シナリオ

攻撃者は、なりすましによって、アドミッションコントローラWebhookのための意図されたAPIサーバからトラフィックをリダイレクトすることができる。

==== 緩和

Webhooks用のmTLS認証でクラスタを構成し、{short-project-name} スタックでmTLS機能を有効にします。あるいは、Network PoliciesをサポートするCNIを使ってmTLSをセットアップする。詳細については、xref:/reference/security-hardening/webhooks-hardening.adoc[「相互TLSによる安全なウェブフック]」を参照してください。

=== 脅威 10 - 変異ルールを悪用して特権コンテナを作成する

==== シナリオ

攻撃者は、変異型アドミッションコントローラにワークロードを変更させ、特権コンテナの作成を許可させることができる。

==== 緩和

すべてのルールを見直し、テストする。

=== 脅威 11 - 攻撃者は、アドミッション・コントロールの対象外となるネームスペースにワークロードを展開する。

==== シナリオ

攻撃者は、アドミッションコントローラーの設定から除外されたKubernetesのネームスペースにワークロードをデプロイできる。

==== 緩和

RBACの権限は厳密に管理される

==== やるべきこと

この決定に関しては、RBACの大半は対象外である。しかし、{short-project-name} ：

* ドキュメントを通じてユーザーに警告し、使用すべき最小限のRBACを_提案_する。
* RBACの変更を検出し、*おそらく*それをブロックするポリシーを提供する。

=== 脅威 12 - ブロックルールが一致しないためにバイパスされる可能性がある（例えば、initcontainers が見つからない）。

==== シナリオ

攻撃者が、アドミッションコントローラでカバーされていないKubernetes APIの機能を使用するワークロードマニフェストを作成した。

==== 緩和

すべてのルールを見直し、テストする。ポリシー展開のルールを変更するPRを確認する必要があります。

=== 脅威 13 - 攻撃者がブロックリストの不正な文字列マッチングを悪用してルールをバイパスする

==== シナリオ

ワークロードを作成する権限を持つ攻撃者が、不正な文字列マッチングを悪用してルールを回避する。

==== 緩和

すべてのルールを見直し、テストする。

==== やるべきこと

このルールをカバーするテストを導入する。
いつものように、ポリシー展開のルールを変更するPRを確認する必要がある。

=== 脅威14 - 攻撃者はルールのないKubernetes APIの新機能/旧機能を使用する

==== シナリオ

ワークロードを作成する権限を持つ攻撃者が、Kubernetes APIの新機能（たとえばAPIのバージョンが変更されたなど）を使用してルールを回避する。

==== 緩和

すべてのルールを見直し、テストする。非推奨リソースの使用をテストするポリシーがある。https://github.com/kubewarden/deprecated-api-versions-policy[the deprecated-api-versions-policy] から入手できる。

NOTE: `deprecated-api-versions-policy` は、既知のカスタム・リソースのみを扱う。脅威は、非推奨のリソースバージョンと、悪用される新しい未知のリソースの両方である。

=== 脅威 15 - 攻撃者が Webhook コントローラを実行しているノードに特権コンテナを配置する。

==== シナリオ

特権コンテナをクラスタにデプロイする権限を持つ攻撃者は、アドミッションコントローラWebhookが動作するクラスタノード上に特権コンテナを作成します。

==== 緩和

アドミッションコントローラは、特権ワークロードを防ぐために制限的なポリシーを使用する。

=== 脅威 16 - 攻撃者は特権ノードのホストパスをマウントし、Webhook コントローラーの設定を変更できるようにする。

==== シナリオ

ワークロードとhostPathボリュームを展開する権限を持つ攻撃者が、アドミッションコントローラポッドのファイルにアクセスできるボリュームを作成します。

`kubewarden-default` Helm chart を展開し、その推奨ポリシー（`hostpaths-psp` ポリシーを含む）を有効にする。このポリシーは、共有hostPathボリュームを削減するように設定されている。

=== 脅威 17 - 攻撃者が、アドミッションウェブフックを実行しているクラスタノードに特権的なSSHアクセス権を持っている。

==== シナリオ

攻撃者はSSH経由で特権ユーザーとしてクラスタノードにログインできる。

==== 緩和

N/A

=== 脅威 18 - 攻撃者はポリシーを使用して、入場要求から機密データを外部システムに送信する。

==== シナリオ

攻撃者は、入場要求をリッスンし、機密データを外部システムに送信するポリシーを設定することができる。

==== 緩和

* Webhooks用のmTLS認証でクラスタを構成し、{short-project-name} スタックでmTLS機能を有効にします。あるいは、Network PoliciesをサポートするCNIを使ってmTLSをセットアップする。

* デフォルトでは、{short-project-name} ポリシーはネットワーク・アクセスを持たず、制限された環境で実行され、Webhooks の外部アクセスを厳密に制御します。

== {short-project-name} 脅威

=== {short-project-name} 脅威1 - アドミッションコントローラーの信頼のブートストラップ

==== シナリオ

信頼されているが新しいKubernetesクラスタを想定すると、攻撃者はデプロイ前に{short-project-name} スタックを侵害し、ポリシーのいずれかをセキュアに実施することができる。

例えば、こうだ：

* 署名のない悪意のある画像を使用する：
 ** {short-project-name}-コントローラー
 ** ポリシーサーバー
 ** {short-project-name} のいずれかの依存関係
 ** 任意の依存関係（Grafana、Prometheus、その他）
* ヘルムチャートのペイロードを危険にさらして

==== 緩和

. {short-project-name} は、必要なすべての画像をリストアップしたソフトウェア部品表を提供します。これはゼロ・トラストを助けるものだ。Kubernetes管理者は、信頼できる環境で、{short-project-name} イメージ、その依存関係のイメージ、およびKubernetesクラスタからのチャートを検証する必要があります。例えば、`cosign` 。ちなみに、これはエアギャップの設置に必要な実装の一部である。
. 署名入りのヘルムチャートと、ヘルムチャート内の{short-project-name}、タグの代わりに検証済みのダイジェストを使用する。しかし、これでは依存関係は確保できない。