= Kubernetes 日志
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自助托管版 v5.1.x

== 概述

在 Kubernetes 设置中，SUSE Observability 功能分布在不同的 pod 中，每个功能的日志存储在每个 pod 和容器中。您可以使用`kubectl` 访问最近的日志，不过为了长期存储，建议设置日志聚合。

== 用于记录日志的 Kubernetes pod

SUSE Observability 日志按 pod 和容器存储。下表显示了与特定 SUSE Observability 功能有关的日志的访问 pod。请注意，实际 pod 名称将包括一个数字或随机字符串后缀（例如`stackstate-receiver-5b9d79db86-h2hkz` ），还可能包括部署 SUSE Observability 时指定的版本名称作为前缀。

[NOTE]
====
请注意，存储在 pod 上的日志会被定期删除。要长期访问日志，建议您为 Kubernetes 集群设置<<_log_aggregation,日志聚合>>。
====


|===
| SUSE 可观察性功能 | 吊舱日志

| 应用程序接口（包括拓扑、图表和设置）
| `stackstate-api`

| 为 Elasticsearch 编制数据索引
| `stackstate-e2es` (活动)

| 数据摄取
| `stackstate-receiver`

| 事件处理程序
| `stackstate-view-health`

| 监控器
| `stackstate-checks`

| 状态传播
| `stackstate-state`

| 同步
| `stackstate-sync`

| 查看健康状态
| `stackstate-view-health`
|===

您可以使用`kubectl logs` 命令访问特定 pod 上的日志。

例如

[,sh]
----
$ kubectl logs stackstate-api-0
----

== 访问最近的日志

=== 荚膜或容器原木

可使用`kubectl logs` 命令从 Kubernetes 检索最新日志。选中<<_kubernetes_pods_for_logging,需要监控的 pod>>以检索特定日志。

例如

[,sh]
----
# Snapshot of logs for all containers of <pod-name>
$ kubectl logs <pod-name> --all-containers=true

# Stream logs for all containers of <pod-name>
$ kubectl logs -f <pod-name> --all-containers=true

# Snapshot of logs for a specific container of <pod-name>
$ kubectl logs -c <container-name> <pod-name>

# Snapshot of logs for previous terminated container of <pod-name>
$ kubectl logs -p -c <container-name> <pod-name>
----

=== 同步日志

所有同步日志可在 pod`stackstate-sync-<suffix>` 中找到。您可以使用同步名称查找日志快照中的特定日志信息。

例如

[,sh]
----
# Logs of the synchronization for a specific Kubernetes cluster
$ kubectl logs stackstate-sync-0 | grep "Kubernetes - \<cluster-name\>"

# Logs of the Agent synchronization
$ kubectl logs stackstate-sync-0 | grep "Agent"
----

== 日志汇总

为了长期存储 SUSE Observability 日志数据，建议您在 Kubernetes 集群上设置日志聚合。可以使用 Elasticsearch、Splunk 或 Logz.io 等第三方存储系统和 Logstash 或 Fluentd 等日志传输器来实现。

有关如何做到这一点的详细信息，请查阅

* 使用https://docs.fluentd.org/container-deployment/kubernetes[Fluentd (fluentd.org)]发送日志
*  https://docs.bitnami.com/tutorials/integrate-logging-kubernetes-kibana-elasticsearch-fluentd/[将]完整设置概述

== 另见

* https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands[kubectl 命令参考（kubernetes.io/docs）]
