= プロバイダー認証 
:revdate: 2025-06-30
:page-revdate: {revdate}

== 認定プロバイダーとは？

ほとんどのCAPIプロバイダーはオープンコミュニティによってメンテナンスされているアップストリームプロジェクトであるため、特定のプロバイダーでプロビジョニングされたクラスタがタートルズ経由でRancherにインポートできることを保証する安全な方法はない。しかし、そのようなプロバイダーに対しては、認証プロセスを導入している：

* E2Eテストスイートの一部として積極的にテスト。
* プロバイダーの最新バージョンを検証するため、このE2Eテスト・スイートを常に最新の状態に保つ。

== カスタムプロバイダーの認証

さらに、あなたがプロバイダー開発者である場合、または単に認定としてリストされていない別のプロバイダーを使用したい場合は、2つのオプションがあります：

* 既存のTurtles E2Eスイートを再利用して、認証ステータスリクエストを開始します。より詳細な情報は、「xref:./certification.adoc#_provider_certification_using_turtles_test_suite[Turtles Test Suiteを使用したプロバイダー認証]」セクションをご覧ください。
* 独自の統合スイートを使用してプロバイダーを認証する。より詳細な情報は、「xref:./certification.adoc#_certify_provider_with_custom_integration_suite[Custom Integration Suite でプロバイダを認証する]」セクションを参照してください。

[discrete]
==== *なぜプロバイダーを検証したいのか？*

CAPIプロバイダーの数は増え続けており、コミュニティはさまざまなインフラホストのために新しいプロジェクトを立ち上げている。このオープン性は、CAPIのエコシステムを豊かにするのに役立つが、CAPIプロジェクト全体でタートルズが協力するすべてのプロバイダーを管理し、テストすることは不可能である。タートルズの開発者は、CIメカニズムによって積極的にテストされ、検証されたxref:../overview/certified.adoc[認定プロバイダーのリストを]維持するが、このリストは主要で有名なプロバイダーに限定される。そのため、リストに掲載されていないプロバイダーのユーザーには、タートルズのテストスイートを再利用し、プロバイダーとタートルズの統合を検証することを推奨しています。

[discrete]
==== *未認証のプロバイダーでタートルズを使用できますか？*

タートルズは、不可知であること、そしてCAPIエコシステム全体と統合することを目的としたプロジェクトであり、プロバイダーを検証することなく自由に使用することができる。おそらく、ほとんどの上流プロジェクトで問題は見つからないだろう。

[discrete]
==== *認定とサポートの違いは何ですか？*

CAPIプロバイダーはKubernetesコミュニティによってメンテナンスされているプロジェクトであるため、特定のプロバイダーのサポートを保証することはできません。このため、私たちはxref:../overview/certified.adoc[認定プロバイダーの]絶え間ない検証を重視し、ユーザーが選択したプロバイダーを検証するために既存のテスト・スイートと統合する可能性を提供しています。

== Turtles Test Suiteを使用したプロバイダー認定

認証のプロセスは、{product_name} CAPIプロバイダーとの統合を検証することに基づいている。この作業を単純化するため、ダウンストリームCAPIクラスタのプロビジョニングとインポートを検証する汎用テストを用意した。

[TIP]
====
タートルズのテスト・スイートの使用方法については、https://github.com/rancher-sandbox/turtles-integration-suite-example[の例を]参照することをお勧めします。
====

=== プロバイダーのテストと認証

あなたのプロバイダがTurtlesと互換性があり、CAPIクラスタをプロビジョニングし、Turtles経由でRancherにインポートできることを検証する最初のステップは、私たちのテストスイートと統合することです。https://github.com/rancher-sandbox/turtles-integration-suite-example[、統合の]リファレンスとして使用できるリポジトリで提供しています。

プロジェクトとしてのTurtlesには、さまざまな機能やプロセスを検証するための https://github.com/rancher/turtles/tree/main/test/e2e/suites[スイートが]含まれていますが、プロバイダー認証のためには、GitOpsフローを使用するテストを1つだけ実行していただく必要があります。Turtlesはクラスタ・プロビジョニングのためのGitOpsアプローチとうまく統合するプロジェクトであり、これがプロバイダーとRancherの統合を検証する私たちの主要な方法である理由だ。指定されたCAPIプロバイダーのために完全なスイートを実行する：

* 目的の環境に管理クラスターを作成する。
* RancherとTurtlesをすべての前提条件とともにインストールする。
* ギテアをインストールする。
* git repoを作成するスイートを実行し、Fleetを使用してクラスタテンプレートを適用し、クラスタが作成され、Rancherに正常にインポートされたことを確認します。

==== テスト構成

テスト・スイートをうまく実行するためには、いくつかの環境変数を指定する必要がある。これらのいくつかは不可知論的なもので、テストしたいプロバイダーに必要なものだが、検証するプロバイダーに固有のものもある。認証情報、エンドポイントなど、テストされるプロバイダーの特定の仕様に注意してください。

[TIP]
====
次に、xref:../operator/certificationsuite.adoc[テストスイートガイドを]読むことをお勧めします。
====

== カスタム統合スイートでプロバイダーを認証

カスタム統合スイートを使用してプロバイダーを認証するには、それが以下の主要要件を満たしていることを確認してください：

=== 必要条件

* プロバイダーは、`CAPIProvider` APIを使用してデプロイされなければならない。
* プロバイダで作成されたクラスタは、タートルズ経由でRancherに正常にインポートされなければならない。

=== 認証プロセス

1. **統合スイートの開発**
   * RancherとTurtlesをインストールし、設定する。
   * CAPIプロバイダを配置する。
   * クラスタをプロビジョニングし、Rancherにインポートする。

2. **テストの実行と検証**
   * クラスタが正常に作成され、インポートされていることを確認する。

3. **認証リクエストの送信**
   * テスト結果、ログ、実施手順を提出すること。
   * 以下のhttps://github.com/rancher/turtles/issues/new?template=certification_request.yaml[テンプレートを使って] GitHub issue を投稿してください。

== 認証のお願い

Turtles のテスト・スイートと統合し、対象のプロバイダーでチェックを実行するだけで、{product_name} と互換性があることを検証できる。すべてのCAPIプロバイダーを継続的にテストすることは不可能であるため、この認証ワークフローにより、ユーザーとして期待される機能を検証することができます。しかし、私たちはプロバイダの新しいバージョン（タートルズの新しいバージョン）を積極的にテストしていないため、指定されたプロバイダのサポートと保証は限られており、将来のリリースの検証はお客様の責任となります。

プロバイダのチェックに成功した後、そのプロバイダをxref:../overview/certified.adoc[認定プロバイダの]リストに追加し、プロジェクトの定期的なE2Eスイートに含めるよう要請したい場合は、https://github.com/rancher/turtles/issues/new?template=certification_request.yaml[Request for Certificationテンプレートを]使用してGitHub issueを提出することで、認定を要請することができます。地域社会はこの提案を検討し、そのプロバイダーを認証マトリックスに追加することの実現可能性を判断する。
