= プロバイダー・テスト・スイート
:revdate: 2025-09-16
:page-revdate: {revdate}

このセクションでは、既存のE2Eスイートを活用して、任意のCAPIプロバイダをTurtlesと統合し、クラスタのプロビジョニングとインポートが期待通りに動作することを確認する方法について説明します。バリデーションは以下の動作を行う：

* 目的の環境に管理クラスターを作成する。
* RancherとTurtlesをすべての前提条件とともにインストールする。
* ギテアをインストールする。
* git repoを作成するスイートを実行し、Fleetを使用してクラスタテンプレートを適用し、クラスタが作成され、Rancherに正常にインポートされたことを確認します。

このテスト・スイートは、「xref:../operator/certification.adoc[プロバイダー認証]」に詳述されているように、xref:../overview/certified.adoc[認証表に]記載されていないプロバイダーの認証に使用することができる。

== 使い方

テスト・スイートを再利用するための主なリファレンスは、https://github.com/rancher-sandbox/turtles-integration-suite-example[このリポジトリ]です。このリポジトリには、指定されたCAPIプロバイダを{product_name} と統合し、GitOpsワークフローに基づいて一連のチェックを適用する方法の例が含まれています。

== 実行前

タートルズで使用されているエンドツーエンドのテスト環境では、実行するテストの種類やチェックの種類に応じて、さまざまな設定が可能です。テスト・スイートを使い始める場合は、できるだけ設定をシンプルにし、カスタマイズの数を制限して、プロセスと設定の詳細を理解できるようにすることをお勧めします。サンプルリポジトリをクローンすることで、プロバイダーテストの旅を始めることができます：

----
git clone https://github.com/rancher-sandbox/turtles-integration-suite-example.git
----

最も単純なテスト実行では、インターネットに面したエンドポイントを使用しないローカル環境を作成します。これにより、チェック対象がローカルのダウンストリームクラスタ（事実上、CAPD経由でプロビジョニングされたCAPIクラスタ）に限定されますが、統合例を実行するには十分です。このローカル・バージョンを実行するには、ローカルで実行することを指定するだけでよい。

----
MANAGEMENT_CLUSTER_ENVIRONMENT="isolated-kind" make test
----

他のインフラプロバイダー（クラウドベンダーのプロバイダーなど）との連携を確認する場合、Rancherインスタンスをエンドポイント経由で、もはやローカル環境にはない下流のクラスタから利用できるようにする必要があります。以前使用した`MANAGEMENT_CLUSTER_ENVIRONMENT` 変数は、以下の値をサポートしている：

----
MANAGEMENT_CLUSTER_ENVIRONMENT: "kind" # supported options are eks, isolated-kind, kind
----

`isolated-kind``kind` 、同等のローカル環境をデプロイする。違いは、`kind`  https://ngrok.com/[、] ngrokを介して一般にアクセス可能なエンドポイントも設定することだ。無料の（制限付き）`ngrok` エンドポイントを取得し、テストの実行に使用することができます。`make test` を実行する前に、以下の環境変数を設定する必要がある：

----
NGROK_API_KEY: ""
NGROK_AUTHTOKEN: ""
----

この設定を使用すると、環境作成時に、Rancherインスタンスは`ngrok` エンドポイント経由でアクセスできるように設定され、ダウンストリームクラスタはそれと通信できるようになる。

<<_other_options,その他のオプション>>」セクションには、実行前に設定できる内容についての詳細が記載されています。

== 基本的なワークフロー

前のセクションでは、テスト統合のサンプルで実行される主な動作を紹介しました：

[discrete]
==== 目的の環境に管理クラスターを作成する。

* CAPIを使用する場合、下流のクラスタを表すリソースを作成するために使用される管理クラスタが必要であるため、これはタートルズ固有の要件ではありません。これはテスト環境の主要部分であり、テストスイートに渡される環境変数に応じて、ローカル（`kind` を使用）またはクラウド（`eks` ）でホストすることができます。

[discrete]
==== RancherとTurtlesをすべての前提条件とともにインストールする。

* TurtlesはRancherの拡張機能であるため、導入にはRancherのインストールが必要です。Rancher Managerは最初のステップで作成した管理クラスターで実行され、Rancherが利用可能になるとタートルズチャートがインストールされる。インターネットに面した構成を使用する場合、イングレスコントローラーは外部ネットワーク（クラウドに配置されたクラスタなど）からRancherに到達可能にする。

[discrete]
==== git repoを作成するスイートを実行し、Fleetを使用してクラスタテンプレートを適用し、クラスタが作成され、Rancherに正常にインポートされたことを確認します。

* メインのテスト・スイート、そして例として使われるテスト・スイートはGitOpsフローに基づいており、GitOpsオーケストレーター・ツールとしてhttps://github.com/rancher/fleet[Fleetを]使用している。提供されたクラスタテンプレート(サンプルの統合https://github.com/rancher-sandbox/turtles-integration-suite-example/tree/main/suites/data/cluster-templates[])に基づいて、YAMLファイルで定義されたCAPIクラスタを作ります。このクラスタ/クラスタが利用可能になったら、xref:../tutorials/first-cluster.adoc[Turtlesを使用してRancherにインポート]するように設定し、ダウンストリームのクラスタ/クラスタがRancher経由でアクセス可能かどうかを確認する。また、削除がダウンストリームクラスタで実行可能かどうか、Rancherで利用できなくなったかどうかも確認する。

== その他のオプション
:kubernetes-version: v1.31.4

`turtles-integration-suite-example` リポジトリの`config.yaml` https://github.com/rancher-sandbox/turtles-integration-suite-example/blob/main/config/config.yaml[ファイルを見て]ください。このファイルには、テスト環境のデプロイとテストの実行中に使用される環境変数のリストが含まれています。以下は上記のYAMLファイルを切り詰めたものです：

[source,yaml,subs=attributes+]
----
...
variables:
  CLUSTERCTL_BINARY_PATH: ""
  USE_EXISTING_CLUSTER: "false"
  SKIP_RESOURCE_CLEANUP: "false"
  ARTIFACTS_FOLDER: "_artifacts"
  MANAGEMENT_CLUSTER_ENVIRONMENT: "kind" # supported options are eks, isolated-kind, kind
  RANCHER_VERSION: "{rancher_version}"
  KUBERNETES_VERSION: "{kubernetes-version}"
  KUBERNETES_MANAGEMENT_VERSION: "{kubernetes-version}"
  KUBERNETES_MANAGEMENT_AWS_REGION: "eu-west-2"
  RKE2_VERSION: "{kubernetes-version}+rke2r1"
  TURTLES_PATH: "turtles/rancher-turtles"
  TURTLES_REPO_NAME: "turtles"
  TURTLES_URL: https://rancher.github.io/turtles
  TURTLES_VERSION: "{turtles_version}"
  RANCHER_HOSTNAME: "localhost"
  RANCHER_FEATURES: ""
  RANCHER_PATH: "rancher-latest/rancher"
  RANCHER_REPO_NAME: "rancher-latest"
  RANCHER_URL: "https://releases.rancher.com/server-charts/latest"
  CERT_MANAGER_URL: "https://charts.jetstack.io"
  CERT_MANAGER_REPO_NAME: "jetstack"
  CERT_MANAGER_PATH: "jetstack/cert-manager"
  ...
  ...
  ...
  HELM_BINARY_PATH: "helm"
  HELM_EXTRA_VALUES_FOLDER: "/tmp"
  # Additional setup for establishing rancher ingress
  NGROK_REPO_NAME: "ngrok"
  NGROK_URL: "https://ngrok.github.io/kubernetes-ingress-controller"
  NGROK_PATH: "ngrok/kubernetes-ingress-controller"
  NGROK_API_KEY: ""
  NGROK_AUTHTOKEN: ""
  GITEA_REPO_NAME: "gitea-charts"
  GITEA_REPO_URL: "https://dl.gitea.com/charts/"
  GITEA_CHART_NAME: "gitea"
  GITEA_CHART_VERSION: "10.6.0"
  ...
----

[TIP]
====
テストの実行をカスタマイズするために使用できるすべてのスイートとパラメータについては、https://github.com/rancher/turtles/tree/main/test/e2e#e2e-tests[]Turtles参照してください。テスト環境のデプロイ/設定に精通しており、特定の統合要件がある場合にのみ、この方法をとることを推奨します。
====

