= 外部の秘密
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilityの外部秘密

== 概要

SUSE Observabilityは、helmインストールによってライセンスキー、apiキー、認証キーなどのシークレットを取得できますが、すでにプロビジョニングされているシークレットから取得することもできます。

ここではその設定方法を説明する。

== 外部秘密からライセンスキーを取得する

SUSE Observabilityがインストールされているネームスペースに、以下の形式で空白を埋めてシークレットを作成します：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

このシークレットを使用するには、helmのインストールコマンドに以下を追加してください：

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== 外部シークレットからメール通知用のユーザー名とパスワードを取得する

SUSE Observabilityがインストールされているネームスペースに、以下の形式で空白を埋めてシークレットを作成します：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

このシークレットを使用するには、helmのインストールコマンドに以下を追加してください：

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== 外部秘密からapiキーを取得する

SUSE Observabilityがインストールされているネームスペースに、以下の形式で空白を埋めてシークレットを作成します：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

このシークレットを使用するには、helmのインストールコマンドに以下を追加してください：

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== 外部秘密から認証データを取得する

SUSE Observabilityがインストールされている名前空間に、以下の形式のシークレットを作成します。

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

選択された認証方法に応じて、`+default_password+` フィールドは異なるデータに置き換えられる。詳しくはxref:/setup/security/authentication/authentication_options.adoc[認証]オプションをご覧ください。この例では、xref:/setup/security/authentication/single_password.adoc[Single passwordを]使用しています。

このシークレットを使用するには、helmのインストールコマンドに以下を追加してください：

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
