= Jetons de service
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Vue d'ensemble

Grâce aux jetons de service, il est possible de s'authentifier auprès de SUSE Observability sans avoir de compte utilisateur associé. Ceci est utile dans les situations où vous souhaitez utiliser SUSE Observability à partir de services sans tête tels qu'un serveur CI. Dans un tel scénario, vous ne voulez généralement pas provisionner un compte d'utilisateur dans votre fournisseur d'identité.

== Gérer les jetons de service

Les jetons de service peuvent être gérés via le xref:/setup/cli/cli-sts.adoc[CLI de`+sts+` ]. Les commandes suivantes sont disponibles :

[,sh]
----
> sts service-token --help
Manage service tokens.

Usage:
  sts service-token [command]

Available Commands:
  create      Create a service token
  delete      Delete a service token
  list        List service tokens

Use "sts service-token [command] --help" for more information about a command.
----

Il est également possible de <<_set_up_a_bootstrap_service_token,mettre>> en <<_set_up_a_bootstrap_service_token,place un jeton de service bootstrap>> lors de l'installation de {stackstate-product-name}.

=== Créer des jetons de service

[NOTE]
====
Les StackPacks Open Telemetry et Kubernetes vous permettent de créer un sujet et un jeton de service avec toutes les autorisations requises.
====

Pour créer un jeton de service pour {stackstate-product-name}, vous pouvez utiliser le CLI `+sts+`.

[,sh]
----
sts service-token create
----

[NOTE]
====
Notez que le jeton de service ne sera affiché qu'une seule fois. Il n'est pas possible de revoir le jeton.
====


Cette commande prend en compte les arguments de ligne de commande suivants :

|===
| Drapeau | Description

| `+--name+`
| Le nom du jeton de service

| `+--expiration+`
| La date d'expiration du jeton de service, au format aaaa-MM-jj. L'expiration est facultative.

| `+--roles+`
| Une liste de rôles séparés par des virgules à attribuer au jeton de service
|===

Par exemple, la commande ci-dessous créera un jeton de service avec le nom `+my-service-token+` et le rôle `+stackstate-k8s-troubleshooter+`:

[,sh]
----
> sts service-token create --name my-service-token --roles stackstate-k8s-troubleshooter
✅ Service token created: svctok-aaaaa-bbbb-ccccc-ddddd
----

=== Mise en place d'un jeton de service d'amorçage

Lors de l'installation de {stackstate-product-name}, il est possible de l'amorcer avec un jeton de service (temporaire). Cela permet d'utiliser l'interface de programmation sans avoir à interagir avec {stackstate-product-name} et à obtenir un jeton d'API à partir de l'interface utilisateur. Pour ce faire, ajoutez l'extrait suivant au fichier de configuration de {stackstate-product-name}:

Pour configurer {stackstate-product-name} afin de créer un jeton de service bootstrap sur Kubernetes, les valeurs suivantes doivent être ajoutées au fichier `+authentication.yaml+`. Par exemple :

[,yaml]
----
stackstate:
  authentication:
    serviceToken:
      bootstrap:
        token: <token>
        roles:
          - stackstate-admin
        ttl: 24h
----

Suivez les étapes ci-dessous pour configurer {stackstate-product-name} afin de créer un jeton de service bootstrap :

. Dans `+authentication.yaml+` - ajoutez le jeton d'amorçage :
 ** *token* - Le token qui est créé au début (initial) de {stackstate-product-name}.
 ** *roles* - Tableau des rôles attribués au jeton d'amorçage.
 ** *ttl* - Facultatif. Durée de vie du jeton de service, exprimée sous la forme d'une chaîne de durée.
. Stockez le fichier `+authentication.yaml+` avec le fichier `+values.yaml+` à partir des instructions d'installation {stackstate-product-name}.
. Exécutez une mise à jour de Helm pour appliquer les changements.
+
[,text]
----
 helm upgrade \
   --install \
   --namespace suse-observability \
   --values values.yaml \
   --values authentication.yaml \
 suse-observability \
 suse-observability/suse-observability
----

[NOTE]
====
* La première exécution de la commande helm upgrade entraînera le redémarrage des pods, ce qui peut provoquer une brève interruption de la disponibilité.
* Inclure `+authentication.yaml+` dans chaque course `+helm upgrade+`.
* La configuration d'authentification est stockée en tant que secret Kubernetes.
====


==== Configurer le jeton du service d'amorçage à partir d'un secret externe

Au lieu de spécifier le jeton d'amorçage via les valeurs Helm, vous pouvez également lire le jeton d'amorçage à partir d'un secret créé et géré en dehors de la charte Helm (un secret externe). Pour utiliser un jeton boostrap provenant d'une entité externe, suivez xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[ces étapes] et ajoutez les données suivantes :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  bootstrap_token: <base64 of token>
----

Ce jeton peut être ajouté au secret à côté des données qui s'y trouvent déjà.

=== Liste des jetons de service

L'ID, le nom, la date d'expiration et les rôles de tous les jetons de service créés peuvent être consultés à l'aide du CLI `+sts+`. Par exemple :

[,sh]
----
> sts service-token list
ID              | NAME             | EXPIRATION | ROLES
107484341630693 | my-service-token |            | [stackstate-admin]
----

=== Supprimer les jetons de service

Un jeton de service peut être supprimé à l'aide du CLI `+sts+`. Passez l'ID du jeton de service en argument. Par exemple :

[,sh]
----
> sts service-token delete 107484341630693
✅ Service token deleted: 107484341630693
----

== Utiliser des jetons de service

Vous utilisez les jetons de service pour vous authentifier lorsque vous utilisez les API de SUSE Observability :* Lors de l'utilisation de la CLI * Lors de l'utilisation directe des API HTTP * Lors de l'ingestion de données télémétriques

=== SUSE Observability `+sts+` CLI

Un jeton de service est utilisé pour l'authentification avec la CLI de `+sts+`. Pour plus d'informations, voir xref:/setup/cli/cli-sts.adoc#_authentication[la documentation CLI.]

=== SUSE Observability APIs

Pour utiliser un jeton de service afin de communiquer directement avec l'API SUSE Observability, ajoutez-le à l'en-tête de la requête de l'une des manières suivantes :

* Dans l'en-tête `+Authorization+`:
+
[,sh]
----
  > curl -X GET -H "Authorization: ApiKey <TOKEN>" http://localhost:8080/api/server/status
----

* Dans l'en-tête `+X-API-Key+`:
+
[,sh]
----
  > curl -X GET -H "X-API-Key: <TOKEN>" http://localhost:8080/api/server/status
----

=== Ingestion de données télémétriques

Afin de créer un jeton de service pour l'ingestion de données télémétriques, vous devez d'abord créer un rôle :
[,sh]
----
> sts rbac create-subject --subject my-agent
✅ Created subject 'my-agent'
> sts rbac grant --subject my-agent --permission update-metrics
✅ Granted permission 'update-metrics' on 'system' to subject 'my-agent'
PERMISSION   | RESOURCE
update-metrics | system
----

Si vous souhaitez utiliser le jeton de service pour ingérer les données RBAC de Kubernetes, vous devez également accorder `+update-scoped-permissions+`:
[,sh]
----
> sts rbac grant --subject my-agent --permission update-scoped-permissions --resource my-cluster
✅ Granted permission 'update-scoped-permissions' on 'my-cluster' to subject 'my-agent'
PERMISSION                | RESOURCE
update-metrics            | system
update-scoped-permissions | my-cluster
----

Cela créera un nouveau rôle dans SUSE Observability appelé `+my-agent+` et lui accordera l'autorisation `+update-metrics+`. Vous pouvez ensuite créer un ServiceToken pour ce rôle :

[,sh]
----
> sts service-token create --name my-agent --roles my-agent
✅ Service token created: svctok-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
----

Le jeton de service nouvellement créé peut être utilisé comme clé api pour l'authentification des données télémétriques :

* {stackstate-product-name} xref:k8s-suse-rancher-prime.adoc#_installing_the_suse_observability_agent[Agent (y compris l'agent RBAC)]
* xref:setup/otel/getting-started/getting-started-k8s.adoc[Collecteur OTel]


