= Como adicionar discos extras do grupo de volumes LVM durante a instalação
:revdate: 2025-09-08
:page-revdate: {revdate}

Este exemplo aborda a configuração de um host com vários discos e alguns deles usados como parte de uma configuração LVM.

Como exemplo, temos um host com três discos (`/dev/sda`, `/dev/sdb` e `/dev/sdc`). 

O primeiro disco é usado para uma instalação regular do Elemental e os outros dois restantes são usados como parte de um grupo LVM em que volumes lógicos arbitrários são criados, formatados e montados no momento da inicialização por meio de um arquivo `fstab` estendido.

Para este exemplo, as etapas de configuração da nuvem são necessárias em dois estágios diferentes. Primeiro, são necessários alguns xref:references/cloud-config-reference.adoc#_elemental_client_cloud_config_hooks[ganchos de instalação] para preparar e manipular os volumes LVM durante a instalação. Em segundo lugar, uma configuração de nuvem é necessária no momento da inicialização para garantir que os volumes LVM criados sejam incluídos em `/etc/fstab` e, consequentemente, montados.

Os ganchos de instalação podem ser incluídos na seção `SeedImage.spec.cloud-config` com algo como:

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: custom-seed
  namespace: fleet-default
spec:
  ...
  cloud-config:
    name: "Create LVM logic volumes over some physical disks"
    stages:
      post-install:
      - name: "Create physical volume, volume group and logical volumes"
        if: '[ -e "/dev/sdb" ] && [ -e "/dev/sdc" ]'
        commands:
        - | 
          # Create the physical volume, volume group and logical volumes
          pvcreate /dev/sdb /dev/sdc
          vgcreate elementalLVM /dev/sdb /dev/sdc
          lvcreate -L 8G -n elementalVol1 elementalLVM
          lvcreate -l 100%FREE -n elementalVol2 elementalLVM
          # Trigger udev detection
          if [ ! -e "/dev/elementalLVM/elementalVol1" ] || [ ! -e "/dev/elementalLVM/elementalVol2" ]; then
            sleep 10
            udevadm settle
          fi
          # Ensure devices are already available
          [ -e "/dev/elementalLVM/elementalVol1" ] || exit 1
          [ -e "/dev/elementalLVM/elementalVol2" ] || exit 1
          # Format logical volumes with a known label for later use in fstab
          mkfs.xfs -L eVol1 /dev/elementalLVM/elementalVol1
          mkfs.xfs -L eVol2 /dev/elementalLVM/elementalVol2
----

Os dispositivos LVM são criados e formatados conforme desejado. Esse é um bom exemplo de um gancho de instalação, pois essa configuração só é necessária uma vez, no momento da instalação. Como alternativa, a mesma ação poderia ser realizada na primeira inicialização, mas isso exigiria uma lógica mais sofisticada para garantir que fosse aplicada apenas uma vez na primeira inicialização. Por fim, os dados de configuração da nuvem no momento da inicialização contêm as configurações do ponto de montagem para acionar as montagens. O arquivo Elemental OS `fstab` é efêmero e é criado dinamicamente no momento da inicialização. É por isso que ele não existe durante a instalação e não pode ser usado em um gancho de instalação.

Considere o exemplo a seguir para personalizar o arquivo `/etc/fstab` usando a seção `cloud-config` de um recurso MachineRegistration:

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  ...
  config:
    ...
    cloud-config:
      stages:
        initramfs:
        - name: "Extend fstab to mount LVM logical volumes at boot"
          commands:
          - |
            echo "LABEL=eVol1 /run/elemental/eVol1  xfs defaults  0 0" >> /etc/fstab
            echo "LABEL=eVol2 /run/elemental/eVol2  xfs defaults  0 0" >> /etc/fstab
----

[NOTE]
====
O xref:references/cloud-config-reference.adoc[estágio] `initramfs` é o último estágio antes de mudar para a árvore raiz real. Nesse estágio, o arquivo `/etc/fstab` já existe e pode ser adaptado antes de mudar para a raiz. Após a execução na árvore raiz final, o SystemD cuidará do restante da inicialização e a aplicará.
====