include::partial$variables.adoc[]
= Durcissement des webhooks de {short-project-name} 
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Crochets Web
:description: Configurez les stratégies réseau et l'authentification pour limiter l'accès aux webhooks dans votre cluster Kubernetes, en restreignant spécifiquement les connexions des appelants non valides.
:keywords: kubewarden, kubernetes, sécurité
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: référence
:doc-topic: référence, sécurité

La pile {project-name} utilise des webhooks pour appliquer des politiques dans un cluster Kubernetes.
Chaque instance `+PolicyServer+` expose un webhook que le serveur API de Kubernetes appelle pour valider et muter les ressources. De plus, le site `+kubewarden-controller+`expose des webhooks pour valider et modifier les ressources personnalisées fournies par le projet{short-project-name}.

Pour réduire leur surface d'attaque, vous devez limiter l'accès à ces webhooks aux seuls appelants valides qu'ils ont :

* le serveur API Kubernetes
* la composante xref:/explanations/audit-scanner/audit-scanner.adoc[scanner]d xref:/explanations/audit-scanner/audit-scanner.adoc['audit].

Pour ce faire, vous pouvez utiliser des stratégies de réseau et d'authentification, indépendamment ou conjointement, afin de protéger les webhooks contre les attaques.

== Bloquer le trafic externe à l'aide de politiques de réseau

Les webhooks ne sont censés accepter que les demandes du serveur API Kubernetes et du composant d'analyseur d'audit. Par défaut, cependant, les webhooks peuvent accepter du trafic provenant de n'importe quelle source. Si vous utilisez une interface réseau de conteneur (CNI) qui prend en charge les stratégies de réseau, vous pouvez créer une stratégie qui bloque le trafic qui ne provient pas du serveur API.

La ressource NetworkPolicy intégrée dans Kubernetes ne peut pas bloquer ou admettre le trafic des hôtes du cluster. En outre, le processus `+kube-apiserver+` est toujours en cours d'exécution sur le réseau hôte. Par conséquent, vous devez utiliser les ressources de stratégie réseau avancée de la CNI en cours d'utilisation. Suivent des exemples pour Calico et Cilium. Consultez la documentation de votre CNI pour plus de détails.

=== Calico

Utilisez la ressource NetworkPolicy dans le groupe `+crd.projectcalico.org/v1+` API, pour définir une politique de réseau comme la suivante :

[source,yaml]
----
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-k8s-and-audit-scanner
  namespace: kubewarden
spec:
  selector: 'app.kubernetes.io/component in {"kubewarden-controller", "policy-server"}'
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      source:
        nets:
        - 192.168.42.0/24
      destination:
        selector: 'app.kubernetes.io/component in {"kubewarden-controller", "policy-server"}'
    - action: Allow
      protocol: TCP
      source:
        namespaceSelector: 'kubernetes.io/metadata.name == "kubewarden"'
      destination:
        selector: 'app.kubernetes.io/component in {"kubewarden-controller", "policy-server"}'
----

[NOTE]
====

Cette politique de réseau utilise les sélecteurs d'étiquettes introduits dans {short-project-name} 1.23.0. Si vous utilisez une version plus ancienne, mettez à jour les étiquettes de la politique pour qu'elles correspondent à votre déploiement.

Plus précisément, écrivez le

[source,yaml]
----
selector: 'app.kubernetes.io/component in {"kubewarden-controller", "policy-server"}'
----

sous forme de sélecteurs :

[source,yaml]
----
selector: 'app.kubernetes.io/name == "kubewarden-controller" || has(kubewarden/policy-server)'
----
====

=== Cilium

Utilisez la ressource CiliumNetworkPolicy dans le groupe `+cilium.io/v2+` API pour définir une politique de réseau comme la suivante :

[source,yaml]
----
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-k8s-and-audit-scanner
  namespace: kubewarden
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - policy-server
          - controller
  ingress:
    - fromEntities:
      - host
      - remote-node
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kubewarden
----

[NOTE]
====

Cette politique de réseau utilise les sélecteurs d'étiquettes introduits dans {short-project-name} 1.23.0. Si vous utilisez une version plus ancienne, mettez à jour les étiquettes de la politique pour qu'elles correspondent à votre déploiement.

Plus précisément, écrivez le

[source,yaml]
----
matchExpressions:
  - key: app.kubernetes.io/component
    operator: In
    values:
      - policy-server
      - controller
----

expression comme :

[source,yaml]
----
endpointSelector:
matchExpressions:
  - key: app.kubernetes.io/name
    operator: In
    values:
      - kubewarden-controller
  - key: kubewarden/policy-server
    operator: Exists
----
====

== Exiger que le serveur API Kubernetes s'authentifie auprès du webhook

[TIP]
====

Reportez-vous à xref:/howtos/security-hardening/webhook-mtls.adoc[webook mTLS how-to] pour un guide étape par étape sur la configuration du serveur API Kubernetes de K3s pour s'authentifier auprès du webhook.

====

Les webhooks exposés par la pile {short-project-name} ne doivent accepter que les demandes provenant du serveur API Kubernetes ou du composant d'analyse d'audit. Par défaut, ces webhooks ne demandent pas aux clients de s'authentifier. Ils acceptent toutes les demandes.

Vous pouvez configurer les webhooks pour qu'ils requièrent des informations d'identification afin que seuls le serveur API et les processus d'analyse d'audit puissent y accéder. Pour plus d'informations, consultez le sitehttps://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers[documentation Kubernetes].

. Configurez le serveur API pour qu'il présente un certificat client au webhook, en pointant vers un fichier `+AdmissionConfiguration+` pour configurer les plug-ins`+ValidatingAdmissionWebhook+` et `+MutatingAdmissionWebhook+`:
+
Créez un fichier nommé `+admission.yaml+` avec le contenu suivant :
+
[source,yaml]
----
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
 configuration:
   apiVersion: apiserver.config.k8s.io/v1
   kind: WebhookAdmissionConfiguration
   kubeConfigFile: "/etc/k8s/admission/kubeconfig"
- name: MutatingAdmissionWebhook
 configuration:
   apiVersion: apiserver.config.k8s.io/v1
   kind: WebhookAdmissionConfiguration
   kubeConfigFile: "/etc/k8s/admission/kubeconfig"
----
+
Il s'agit du même fichier de configuration que celui utilisé pour configurer d'autres plug-ins, tels que`+PodSecurity+`. Si votre distribution ou votre installation utilise des plug-ins d'admission supplémentaires, vous devez également les configurer.

. Créez le fichier `+kubeconfig+` auquel les plug-ins d'admission font référence. {short-project-name} ne supporte que l'authentification par certificat client, générez donc une paire de clés TLS et configurez kubeconfig pour utiliser soit client-certificate et client-key, soit client-certificate-data et client-key-data.
+
Par exemple :
+
[source,yaml]
----
apiVersion: v1
kind: Config
users:
- name: '*.kubewarden.svc'
  user:
    client-certificate: /path/to/client/cert
    client-key: /path/to/client/key
----

. Lancez le binaire `+kube-apiserver+` avec le drapeau`+--admission-control-config-file+` pointant vers votre fichier `+AdmissionConfiguration+`. La façon de procéder varie selon la distribution, et elle n'est pas prise en charge de façon universelle, comme dans les fournisseurs Kubernetes hébergés. Consultez la documentation de votre distribution Kubernetes.

. Mettez le certificat de l'autorité de certification racine qui a émis le certificat du client du serveur API à la disposition de la pile {short-project-name}.
+
Placez son contenu dans un site `+ConfigMap+` sous l'espace de noms `+kubewarden+`à l'aide d'une clé nommée `+client-ca.crt+`.
+
En supposant que l'autorité de certification racine soit disponible à l'adresse `+/etc/k8s/admission/certs/rootCA.crt+`, créez l'adresse `+ConfigMap+` à l'aide de la commande suivante :
+
[source,console]
----
kubectl create configmap -n kubewarden api-server-mtls \
   --from-file=client-ca.crt=/etc/k8s/admission/certs/rootCA.crt
----

. Enfin, lors de l'installation de la carte `+kubewarden-controller+` Helm, veillez à activer les valeurs suivantes :
+
- Définir `+mTLS.enable+` à `+true+`.
- Attribuez à `+mTLS.configMapName+` le nom de `+ConfigMap+` qui a été créé précédemment.
+
Le nom de `+ConfigMap+` est `+api-server-mtls+`, donc la commande Helm pour installer `+kubewarden-controller+` est :
+
[source,console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller \
   --set mTLS.enable=true \
   --set mTLS.configMapName=api-server-mtls
----
+
Le contrôleur {short-project-name} crée un certificat client destiné à être utilisé par le composant d'analyseur d'audit. Le certificat est automatiquement tourné par le contrôleur en cas de besoin.
