= Embarquement de la machine
:revdate: 2025-11-06
:page-revdate: {revdate}

L'objectif du service Machine Onboarding est d'enregistrer une nouvelle machine dans le catalogue de l'opérateur {elemental-product-name} xref:references/machineinventory-reference.adoc[(] ressourcesxref:references/machineinventory-reference.adoc[MachineInventory] ) et d'approvisionner l'hôte avec le système d'exploitation, en appliquant la configuration souhaitée.

L'embarquement dans la machine comprend les étapes suivantes :

* L'utilisateur crée une ressource xref:references/machineregistration-reference.adoc[MachineRegistration]: la MachineRegistration comprend la configuration requise pour l'installation du système d'exploitation.
Dès que le MachineRegistration est créé, l'opérateur {elemental-product-name} expose un _point de terminaison d'enregistrement_ HTTP : c'est le point d'entrée requis par les hôtes d'accueil pour s'enregistrer auprès de l'opérateur.
* L'utilisateur demande une image d'auto-installation par l'intermédiaire d'une ressource xref:references/seedimage-reference.adoc[SeedImage]: il a seulement besoin d'une référence à une ressource MachineRegistration et à une image de conteneur de système d'exploitation compatible avec la boîte à outils {elemental-product-name}.
Dès que la SeedImage est créée, l'opérateur {elemental-product-name} déclenche le processus de construction de la ressource image: once completed, the URL is exposed in the `status.downloadURL` field of the xref:references/seedimage-reference.adoc[SeedImage] auto-installable.
* L'utilisateur télécharge l'image d'auto-installation et l'utilise pour démarrer un hôte non approvisionné : l'hôte https://documentation.suse.com/cloudnative/os-manager/latest/en/rancher-os-management/authentication.html[s'authentifie] auprès du _point final d'enregistrement_ de l'opérateur {elemental-product-name}, obtient la configuration complète stockée dans MachineRegistration et installe le système d'exploitation sur le périphérique de stockage local. Dès que l'hôte a terminé la procédure d'enregistrement, l'opérateur {elemental-product-name} crée une ressource xref:references/machineinventory-reference.adoc[MachineInventory] unique qui suit l'hôte.
L'image auto-installable peut être utilisée pour embarquer n'importe quel nombre d'hôtes.
