include::partial$variables.adoc[]
= Richtlinien im Artifact Hub veröffentlichen
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Veröffentlichen Sie {project-name} Richtlinien in Artifact Hub, indem Sie ein gut formatiertes Git-Repository-Layout erstellen und GitHub-Aktionen für die automatische Paketierung konfigurieren, um die kontinuierliche Integration zu erleichtern.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-policy-developer", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["distributing-policies", "publish-policy-to-artifacthub"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "Veröffentlichungsrichtlinien", "Artefakt-Hub"]
:sidebar_label: Auf Artifact Hub veröffentlichen
:sidebar_position: 40
:current-version: {page-origin-branch}

https://artifacthub.io/[Artifact Hub] ist eine Website, auf der Benutzer Pakete und Konfigurationen für https://cncf.io[CNCF-Projekte] finden, installieren und veröffentlichen können.

{project-name} Richtlinien können auf Artifact Hub veröffentlicht und für ein breites Publikum von CNCF-Nutzern zugänglich gemacht werden.

[NOTE]
====
Artifact Hub ist eine Plattform zur Aggregation von Inhalten und beherbergt nicht die Artefakte, die auf ihr veröffentlicht werden.

Artifact Hub erfordert, dass Sie die Container-Image-Repositories physisch auf einer Container-Registry oder einem Webserver hosten.
Weitere Informationen darüber, wie Sie Ihre Richtlinien hosten können, finden Sie im Abschnitt über xref:explanations/distributing-policies.adoc[die Verteilung von Richtlinien].
====


Dieses Dokument konzentriert sich auf die Schritte, die erforderlich sind, um eine {short-project-name} Richtlinie auf Artifact Hub auffindbar zu machen.

== Bereiten Sie Ihr Git-Repository vor

Artifact Hub durchsucht Git-Repositories auf der Suche nach speziellen Metadaten-Dateien.

Es gibt verschiedene Arten von Layouts, die ein Git-Repository haben kann. Sie alle sind in der https://artifacthub.io/docs/topics/repositories/#kubewarden-policies-repositories[offiziellen Dokumentation des Artifact Hub] ausführlich dokumentiert.

Artifact Hub ist flexibel und ermöglicht es Ihnen, Ihren Code auf diese Weise zu organisieren:

* Verfügen Sie über ein Git-Repository für Artifact Hub: Dieses Repository wird keinen Richtlinien-Quellcode enthalten. Es handelt sich um eine Sammlung von YAML-Dateien, die von Artifact Hub benötigt werden.

* Fügen Sie ein Artifact Hub-Verzeichnis in das Git-Repository ein, das die Quelle Ihrer Richtlinie enthält. Dies ist eine Wiederholung des vorherigen Ansatzes, die sich auf eine einzige Richtlinie konzentriert, nämlich die, die im Git-Repository definiert ist. Dieser Ansatz ermöglicht es, mehrere Versionen der auf Artifact Hub veröffentlichten Richtlinie aufzubewahren.

* Fügen Sie die Dateien `artifacthub-pkg.yml` und `artifacthub-repo.yml` in das Stammverzeichnis des Git-Repositorys ein, das den Quellcode der Richtlinie enthält. Dieser Ansatz ist der einfachste. Die einzige Einschränkung ist, dass nur die neueste Version der Richtlinie auf Artifact Hub sichtbar ist.

Der letzte Ansatz wird in unseren offiziellen Politikvorlagen verwendet. Das gerüstete Git-Repository enthält die Datei `artifacthub-repo.yml`, und unsere GitHub-Aktionen generieren und pushen die `artifacthub-pkg.yml` in einen`artifacthub` -Zweig, der von Artifact Hub genutzt werden kann.

== Schritte zur Veröffentlichung

Bevor Sie eine Richtlinie in Artifact Hub veröffentlichen, müssen Sie ein Kontohttps://artifacthub.io/[dort] erstellen.

Bevor Sie die Richtlinie veröffentlichen, stellen Sie sicher, dass Ihr Git-Repository das richtige Layout hat, mit einer gut formatierten `metadata.yml` mit den obligatorischen Anmerkungen.

Wenn Sie dies manuell tun möchten, können Sie die Datei `artifacthub-pkg.yml` erstellen, indem Sie eine `kwctl scaffold artifacthub` (mit der Version `>= 1.23`) ausführen. Dieser Befehl nimmt die `metadata.yml` im aktuellen Pfad und gibt eine`artifacthub-pkg.yml` aus. Die `artifacthub-pkg.yml` enthält Felder wie`version:`, `createdAt:`, die einem bestimmten Format entsprechen und aktuell sein müssen. Das Format der Website `artifacthub-pkg.yml` isthttps://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml[unter] beschrieben.

Wenn Sie unsere GitHub-Aktionen >= `v4.0.0` verwenden, kann der Freigabe-Workflow mit der Eingabe `artifacthub: true` konfiguriert werden. Wenn dies so konfiguriert ist, wird nach einer erfolgreichen Freigabe (nachdem die Richtlinie erfolgreich erstellt, signiert und gepusht wurde) ein letzter Job in unseren GitHub-Aktionen ausgeführt, der die`artifacthub-pkg.yml` für Sie generiert und dann die Änderungen an den`artifacthub` -Zweig überträgt und pusht. Die kanonischen Dateien sind immer die im `main`Zweig. Das Verhalten früherer Versionen unserer GitHub-Aktionen finden Sie in den Dokumentationsversionen vor 1.23.

Stellen Sie schließlich sicher, dass Ihre Richtlinie in einer Container-Registrierung oder auf einem Webserver veröffentlicht wird.

[NOTE]
====
Im Moment ist der Inhalt der Datei `artifacthub-repo.yml` nicht relevant.
====


Sobald alles eingerichtet ist, melden Sie sich bei Artifact Hub an und gehen zu Ihrerhttps://artifacthub.io/control-panel/repositories?page=1[Kontrollebene].

Entscheiden Sie, ob Sie die Richtlinie als Benutzer oder unter einer Artifact Hub-Organisation, der Sie angehören, veröffentlichen möchten. Dies geschieht durch die Wahl des richtigen _"Systemsteuerungskontextes"._

Drücken Sie dann auf die Schaltfläche _"Hinzufügen"_ und füllen Sie das Formular aus:

* Wählen Sie _"{short-project-name} policies"_ als Art.
* Geben Sie einen _"Namen"_ und einen _"Anzeigenamen"_ Ihrer Wahl ein.
* Geben Sie die URL zu Ihrem Git-Repository ein.
* Geben Sie `artifacthub` als zu verfolgenden Zweig ein.

Drücken Sie schließlich die Schaltfläche _"Hinzufügen"_. Dies bringt Sie zurück zur Seite _"Repositories"_, wo Sie Ihr frisch erstelltes Repository sehen.

Jedes Repository hat mehrere Informationsfelder. Suchen Sie die Eigenschaft _"ID"_ des soeben erstellten Repositorys und kopieren Sie sie.

Gehen Sie zurück zu Ihrem Git-Repository und bearbeiten Sie die `artifacthub-repo.yml`. Vergewissern Sie sich, dass der Schlüssel`repositoryID`, der sich im Dokument befindet, den Wert hat, den Sie gerade von der Artifact Hub-Webseite kopiert haben.

[TIP]
====
Das Format der Datei `artifacthub-repo.yml` isthttps://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml[unter] definiert.

Jetzt ist es an der Zeit, einige weitere Anpassungen an dieser Datei vorzunehmen.
====


Sobald Sie mit den Änderungen fertig sind, übertragen Sie die aktualisierte Datei `artifacthub-repo.yml`und pushen sie. Während des nächsten Scans wird Artifact Hub diese Datei finden und dashttps://artifacthub.io/docs/topics/repositories/#verified-publisher[_"Verified Publisher"_ Abzeichen]zu Ihrem Artifact Hub Repository hinzufügen.

== Synchronisierung von Artifact Hub

Vergessen Sie nicht, den Inhalt der Datei `artifacthub-pkg.yml` jedes Mal zu aktualisieren, wenn Sie eine neue Version Ihrer Richtlinie veröffentlichen. Sie müssen zum Beispiel das Feld`io.kubewarden.policy.version` (das in der Regel mit dem OCI-Tag der Richtlinie übereinstimmt) und alle anderen Anmerkungen, die Sie ändern möchten, aktualisieren.

[NOTE]
====
Der Inhalt der Datei `artifacthub-repo.yml` muss nicht geändert werden.
====

