= SLSA
:revdate: 2025-04-04
:page-revdate: {revdate}

== Visão geral

https://slsa.dev/spec/v1.0/about[O SLSA] é um conjunto de diretrizes que podem ser adotadas de forma incremental para a segurança da cadeia de suprimentos, estabelecidas por consenso do setor. A especificação definida pelo SLSA é útil tanto para produtores quanto para consumidores de software: os produtores podem seguir as diretrizes do SLSA para tornar sua cadeia de suprimentos de software mais segura, e os consumidores podem usar o SLSA para tomar decisões sobre a confiança em um pacote de software.

{product_name} atende aos requisitos https://slsa.dev/spec/v1.0/levels[do].

|===
| Requisito | Exigido na SLSA L3 | Conhecido por {product_name}

| Escolha uma plataforma de compilação apropriada
| Sim
| Sim

| Siga um processo de compilação consistente
| Sim
| Sim

| Distribuir a procedência
| Sim
| Sim
|===

== Criar plataforma

* O projeto {product_name} usa o Git para o gerenciamento do código-fonte.
* Todos os mantenedores do {product_name} precisam ter a autenticação de dois fatores ativada para assinar e aprovar todas as suas contribuições.
* O projeto {product_name} usa o GitHub Actions e o GitHub Runners para criar todos os seus artefatos de lançamento.
* O processo de criação e lançamento é executado isoladamente em um ambiente efêmero fornecido por executores hospedados no GitHub.

== Processo de construção

* O processo de criação e liberação é definido no código e mantido sob controle de versão.
* Os fluxos de trabalho do GitHub usam o GitHub Actions fixado em determinadas versões e são mantidos atualizados usando o GitHub Dependabot.
* Todas as alterações no processo de compilação e lançamento são feitas por meio de Pull Requests que devem ser aprovadas por pelo menos um mantenedor do {product_name}.
* O processo de lançamento só pode ser iniciado por um mantenedor do {product_name}, enviando uma tag Git no formato semver.

== Proveniência

* O projeto {product_name} usa o projeto oficial https://github.com/slsa-framework/slsa-github-generator[SLSA GitHub Generator] para geração e distribuição de procedência.
* A procedência dos artefatos de lançamento publicados no Registro de contêineres do GitHub e no Registro do Rancher Prime é gerada usando o fluxo de trabalho do GitHub generator_container_slsa3 fornecido pelo projeto https://github.com/slsa-framework/slsa-github-generator[SLSA GitHub Generator].
* A proveniência identifica as imagens do contêiner {product_name} usando seu resumo no formato SHA-256.
* A procedência é assinada pelo Sigstore Cosign usando a identidade OIDC do GitHub, e a chave pública para verificar a procedência é armazenada no público https://docs.sigstore.dev/logging/overview/[registro].
* O processo de lançamento e a geração de proveniência são executados isoladamente em um ambiente efêmero fornecido por executores hospedados no GitHub.
* A procedência das imagens do contêiner {product_name} pode ser verificada usando a oficial https://github.com/slsa-framework/slsa-verifier[ferramenta].
* Os fluxos de trabalho de geração de procedência são executados em máquinas virtuais efêmeras e isoladas, que são totalmente gerenciadas pelo GitHub.
* Os segredos de assinatura de procedência são efêmeros e são gerados por meio do procedimento de assinatura https://github.com/sigstore/cosign/blob/main/KEYLESS.md[sem chave] da Sigstore.
* O https://github.com/slsa-framework/slsa-github-generator[SLSA GitHub Generator] é executado em máquinas virtuais separadas do processo de criação e lançamento, de modo que os scripts de criação do {product_name} não tenham acesso aos segredos de assinatura.

== Isolamento

* O processo de lançamento e a geração de proveniência são executados isoladamente em um ambiente efêmero fornecido por executores hospedados no GitHub.
* A geração de procedência é desacoplada do processo de construção; o https://github.com/slsa-framework/slsa-github-generator[SLSA GitHub Generator] é executado em máquinas virtuais separadas totalmente gerenciadas pelo GitHub.
* O processo de lançamento não pode acessar a chave de assinatura de procedência porque o gerador de procedência é executado isoladamente em executores separados hospedados no GitHub.
