include::partial$variables.adoc[]
= Ouvrir le guide de démarrage rapide de la télémétrie
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configurer et déployer le collecteur OpenTelemetry en mode sidecar en utilisant la charte officielle Kubernetes Helm pour un déploiement simple et amélioré.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "telemetry", "opentelemetry", "quick-start"].
:doc-type: ["howto"]
:keywords: ["kubewarden", "kubernetes", "opentelemetry", "open telemetry", "quickstart"].
:sidebar_label: Ouvrir la télémétrie
:current-version: {page-origin-branch}

https://opentelemetry.io/[OpenTelemetry] est un cadre de la Cloud Native Computing Foundation (CNCF) pour l'observabilité. Il permet à vos microservices de fournir des mesures, des journaux et des traces.

{project-name}Les composants d'OpenTelemetry, qui utilisent le SDK OpenTelemetry, transmettent des données à un collecteur OpenTelemetry, appelé agent.

Ce guide explique comment déployer le collecteur OpenTelemetry en mode `+sidecar+` en utilisant la carte officielle Kubernetes Helm.

Il s'agit d'un modèle de déploiement simple utilisant OpenTelemetry. La configuration finale est la suivante :

* Chaque Pod de la pile {short-project-name} (serveur de politique, contrôleur) possède un sidecar OpenTelemetry.
* Le sidecar reçoit des informations de suivi et de surveillance du composant {short-project-name} via le protocole OpenTelemetry (OTLP).
* Le collecteur OpenTelemetry :
 ** Envoi des événements de traçage à une instance centrale de Jaeger
 ** Expose les métriques Prometheus sur un port spécifique

Le tableau {short-project-name} Helm ne couvre pas tous les scénarios de déploiement possibles du collecteur OpenTelemetry. Il est également possible de configurer{short-project-name} pour qu'il envoie des données à un collecteur OpenTelemetry. La documentation pour ce scénario se trouve dans le xref:./40-custom-otel-collector.adoc[guide OpenTelemetry personnalisé.]

Vous commencez par déployer OpenTelemetry dans un cluster Kubernetes, afin de pouvoir l'utiliser dans les sections suivantes traitant spécifiquement du traçage et des métriques.

== Mise en place d'un cluster Kubernetes

[NOTE]
====
Cette section contient des instructions étape par étape pour créer un cluster Kubernetes pour les démarrages rapides de télémétrie.

N'hésitez pas à sauter cette section si vous disposez déjà d'un cluster Kubernetes.
====

Vous pouvez créer un cluster Kubernetes pour les tests en utilisant https://minikube.sigs.k8s.io/docs/[minikube].

Minikube dispose de nombreux backends, dans ce cas vous pouvez utiliser le pilotehttps://minikube.sigs.k8s.io/docs/drivers/kvm2/[] kvm2 qui s'appuie sur libvirt.

En supposant que `+libvirtd+` fonctionne correctement sur votre machine, lancez la commande suivante :

[subs="+attributes",console]
----
minikube start --driver=kvm2
----

La commande produit une sortie similaire à la suivante :

[subs="+attributes",console]
----
$ minikube start --driver=kvm2
😄  minikube v1.23.2 on Opensuse-Leap 15.3
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.22.2 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
----

Une fois que le cluster est prêt, vous pouvez continuer avec le reste du guide.

=== Installer Traefik

Les guides de télémétrie suivants utilisent https://traefik.io/traefik/[Traefik] comme contrôleur Ingress lors de l'exposition de l'interface utilisateur Jaeger avec les ressources Kubernetes `+Ingress+`.

Installez Traefik en utilisant sa carte Helm :

[,console]
----
helm repo add traefik https://traefik.github.io/charts
helm repo update

helm install --wait \
  --namespace traefik \
  --create-namespace \
  traefik traefik/traefik
----

Les guides suivants créent un site Kubernetes standard `+Ingress+` avec`+ingressClassName: traefik+` et acheminent l'interface utilisateur Jaeger Query via le service Traefik.

Si vous préférez ne pas installer Traefik, les guides de traçage conservent également`+kubectl port-forward+` comme solution de rechange pour accéder directement à Jaeger.

[#install-opentelemetry]
== Installer OpenTelemetry

[NOTE]
====
Voir la xref:/reference/dependency-matrix.adoc[matrice des dépendances] pour connaître les dernières versions des composants pris en charge.
====

Vous utilisez le sitehttps://github.com/open-telemetry/opentelemetry-operator[OpenTelemetry Operator] pour gérer l'injection automatique du sidecar OpenTelemetry Collector dans le pod PolicyServer.

L'opérateur OpenTelemetry nécessite l'installation dehttps://cert-manager.io/docs/installation/[cert-manager] dans le cluster.


[subs="+attributes",console]
----
helm repo add jetstack https://charts.jetstack.io

helm install --wait \
    --namespace cert-manager \
    --create-namespace \
    --set crds.enabled=true \
    --version 1.18.2 \
    cert-manager jetstack/cert-manager
----

Une fois que cert-manager fonctionne, vous pouvez installer la carte Helm de l'opérateur OpenTelemetry :

[NOTE]
====

Au moment où nous écrivons ces lignes (2024-11-11), la dernière version de la carte d'opérateur OpenTelemetry est la suivante `+0.65.0+`

====

[subs="+attributes",console]
----
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts

helm install --wait \
  --namespace open-telemetry \
  --create-namespace \
  --version 0.97.1 \
  --set "manager.collectorImage.repository=otel/opentelemetry-collector-contrib" \
  my-opentelemetry-operator open-telemetry/opentelemetry-operator
----

== Intégration d'OpenTelemetry

Vous pouvez maintenant passer aux chapitres suivants pour activer les métriques d'application (via l'intégration de Prometheus) et le traçage d'application (via l'intégration de Jaeger).
