= Deaktivieren der TLS-Überprüfung
:revdate: 2025-08-25
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

== SUSE Observability Agent

Um die SSL-Validierung für Ihren xref:/use/security/self-signed-certificates.adoc#_suse_observability_agent[SUSE Observability-Agenten] zu deaktivieren, müssen Sie den Helm-Zeichenfolgenwert wie unten dargestellt konfigurieren:

[,bash]
----
--set-string 'global.skipSslValidation'=true \
----

== SUSE Observability CLI

Um die SSL-Validierung über die xref:/use/security/self-signed-certificates.adoc#_suse_observability_cli[SUSE Observability CLI] zu deaktivieren, müssen Sie das Flag `+--skip-ssl+` mit den Befehlen `+sts CLI+` angeben. Dies kann mit einer der beiden folgenden Methoden geschehen:

*Methode 1*: 

Geben Sie das Flag `+--skip-ssl+` in der PEM-kodierten CA-Zertifikatsdatei für eine dauerhafte Konfiguration an:

[,bash]
----
sts context save \
 --name staging \
 --url https://staging.internal \
 --api-token YOUR_API_TOKEN \
 --skip-ssl
----

*Methode 2*:

Geben Sie das Flag `+--skip-ssl+` in jedem CLI-Befehl an, der für die einmalige Zertifikatsvalidierung verwendet wird:

[,bash]
----
# Using certificate file path
sts agent list \
 --url https://staging.internal \
 --api-token YOUR_API_TOKEN \
 —-skip-ssl


# Using base64-encoded certificate data
sts settings list \
 --url https://staging.internal \
 --api-token YOUR_API_TOKEN \
 —-skip-ssl
----

[WARNING]
====
Bei Verwendung des Flags `+--skip-ssl+` werden die Einstellungen `+STS_CA_CERT_PATH+` und `+STS_CA_CERT_BASE64_DATA+` ignoriert. Dies ist mit Vorsicht zu genießen, da es die Sicherheit verringert.
====

== Rancher UI-Erweiterung für SUSE Observability

Um die SSL-Validierung in der Rancher UI-Erweiterung zu deaktivieren, müssen Sie die Einstellung `+agent-tls-mode+` ändern. 

Um den Wert der Einstellung über die Benutzeroberfläche zu ändern, navigieren Sie zur Seite Globale Einstellungen und suchen Sie die Einstellung `+agent-tls-mode+` am unteren Rand der Seite. Nachdem die Einstellung über die Benutzeroberfläche geändert wurde, wird geprüft, ob die Bedingung `+AgentTlsStrictCheck+` auf "True" gesetzt ist, bevor die Anfrage zugelassen wird. Dies verhindert Ausfälle aufgrund einer Fehlanpassung des Zertifikats.
