include::partial$variables.adoc[]
= 分发政策
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 使用 kwctl 等工具，通过符合 OCI 标准的注册表安全地分发策略，并通过{project-name} 策略管理确保集群安全。
:doc-persona: ["kubewarden-operator"、"kubewarden-policy-developer"、"kubewarden-distributor"、"kubewarden-integrator"]
:doc-topic: ["distributing-policies"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "oci", "kubewarden", "policy", "wasm", "webassembly"]
:current-version: {page-origin-branch}

{project-name} 策略是由{short-project-name} 策略服务器评估的 WebAssembly (Wasm) 二进制文件。

{short-project-name} 策略服务器从这些来源加载策略：

* 本地文件系统
* HTTP 服务器
* 符合 OCI 标准的登记册：
 ** https://github.com/distribution/distribution[分发]
 ** https://ghcr.io[GitHub 容器注册表]
 ** https://azure.microsoft.com/en-us/products/container-registry/[Azure 容器注册表]
 ** https://aws.amazon.com/ecr/[亚马逊 ECR]
 ** https://cloud.google.com/artifact-registry/[谷歌容器注册表]

{short-project-name} 建议通过符合 OCI 标准的常规注册表发布{short-project-name} 政策。容器注册是任何 Kubernetes 集群的必备条件。在一个地方存储集群所需的所有人工制品并确保其安全是非常有益的。

== 将策略推送到符合 OCI 标准的注册中心

https://github.com/opencontainers/image-spec[]OCI规范允许在符合 OCI 标准的常规容器注册表中存储任何二进制 Blob。

符合 OCI 标准的目标注册表*必须支持工件*，才能成功将{short-project-name} Policy 推送到该注册表。

您可以使用https://github.com/kubewarden/kwctl[`+kwctl+`]CLI 将{short-project-name} 策略推送到符合 OCI 标准的注册中心。

== 注释政策

您还可以使用`+kwctl+` 对政策进行注释。注释{short-project-name}政策的方法是在政策二进制文件中添加 Wasm 自定义部分。这意味着政策会打包自己的元数据。

`+kwctl annotate+` 命令需要两个输入端：

* 要注释的{short-project-name} 策略，文件系统中的本地文件。
* 注释文件，该文件包含策略元数据的 YAML 描述。
该文件通常位于策略的项目根文件夹中。

例如，您可以将该文件保存为`+metadata.yml+` ，放在当前目录下：

[subs="+attributes",yaml]
----
rules:
- apiGroups: ["*"]
  apiVersions: ["*"]
  resources: ["*"]
  operations: ["*"]
mutating: false
annotations:
  io.kubewarden.policy.title: palindromify
  io.kubewarden.policy.version: 0.1.0
  io.kubewarden.policy.description: Allows you to reject palindrome names in resources and namespace names, or to only accept palindrome names
  io.kubewarden.policy.author: Name Surname <name.surname@example.com>
  io.kubewarden.policy.url: https://github.com/<org>/palindromify
  io.kubewarden.policy.source: https://github.com/<org>/palindromify
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.usage: |
    This is markdown text and as such allows you to define a free form usage text.

    This policy allows you to reject requests if:
    - The name of the resource is a palindrome name.
    - The namespace name where this resource is created has a palindrome name.

    This policy accepts the following settings:

    - `+invert_behavior+`: bool that inverts the policy behavior. If enabled, only palindrome names will be accepted.
----

现在，让我们对政策进行注释：

[subs="+attributes",shell]
----
$ kwctl annotate policy.wasm \
    --metadata-path metadata.yml \
    --output-path annotated-policy.wasm
----

注释过程会对策略进行某些优化，因此注释后的策略往往比原始策略更小。这在很大程度上取决于制作原始 Wasm 对象所使用的工具链。

[IMPORTANT]
====

.使用 kwctl inspect 检查策略
[%collapsible]
======

[subs="+attributes",shell]
----
$ kwctl inspect annotated-policy.wasm
2023-08-24T12:06:27.986401Z  INFO sigstore::cosign::client_builder: Rekor public key not provided. Rekor integration disabled
2023-08-24T12:06:27.986449Z  INFO sigstore::cosign::client_builder: No Fulcio cert has been provided. Fulcio integration disabled
Details
title:                    palindromify
description:              Allows you to reject palindrome names in resources and namespace names, or to only accept palindrome names
author:                   Name Surname <name.surname@example.com>
url:                      https://github.com/<org>/palindromify
source:                   https://github.com/<org>/palindromify
license:                  Apache-2.0
mutating:                 false
background audit support: true
context aware:            false
execution mode:           kubewarden-wapc
protocol version:         1

Annotations
io.kubewarden.kwctl       1.7.0-rc2

Rules
────────────────────
- apiGroups:
  - '*'
  apiVersions:
  - '*'
  resources:
  - '*'
  operations:
  - '*'
────────────────────

Usage
This is markdown text and as such allows you to define a free form usage text.

This policy allows you to reject requests if:

• The name of the resource is a palindrome name.
• The namespace name where this resource is created has a palindrome name.

This policy accepts the following settings:

• invert_behavior: bool that inverts the policy behavior. If enabled, only palindrome names will be accepted.

Cannot determine if the policy has been signed. There was an error while attempting to fetch its signatures from the remote registry: invalid uri
----

======
====


== 推动政策

您可以像这样推送注释策略：

[subs="+attributes",shell]
----
$ kwctl push annotated-policy.wasm \
     <oci-registry>/kubewarden-policies/palindromify-policy:v0.0.1
----

不鼓励推行未注明的政策。策略服务器使用注释提供的元数据来正确执行策略。默认情况下，`+kwctl push+` 拒绝将此类政策推送到 OCI 注册表。如果需要未加注释的策略，请使用`+kwctl push+` 的`+-&#x200D;-&#x200D;force+` 标志。

您可以将{short-project-name} Policy Server 或`+kwctl+` 中的策略引用为`+registry://<oci-registry>/kubewarden-policies/palindromify-policy:v0.0.1+` 。
