= k8s Custom Secret Management
:revdate: 2025-10-27
:page-revdate: {revdate}

== Übersicht

Der SUSE Observability Agent unterstützt die Angabe des Namens eines benutzerdefinierten Geheimnisses, das den API-Schlüssel und das Cluster-Autorisierungs-Token enthält. Diese Funktion ist nützlich für Benutzer, die ihre eigenen Geheimnisse verwalten und die automatische Erstellung von Geheimnissen durch das Helm-Diagramm vermeiden möchten.

NOTE: *Es gab eine frühere Methode, dies zu spezifizieren, die jetzt veraltet ist, siehe die xref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[veraltete Methode].*

== Die Steuerkarte

=== Konfigurationsoptionen

* `+global.apiKey.fromSecret+`: Geben Sie einen bereits existierenden geheimen Namen an, der sich im gleichen Namensraum befindet und ein Feld `+STS_API_KEY+` enthält, das den API-Schlüssel enthält.
* `+global.clusterAgentAuthToken.fromSecret+`: Geben Sie einen bereits vorhandenen geheimen Namen an, der sich im gleichen Namensraum befindet und ein Feld `+STS_CLUSTER_AGENT_AUTH_TOKEN+` enthält, das ein Token zur Sicherung von Verbindungen zwischen dem Cluster und den Knotenagenten enthält.

=== Verhaltensbeschreibung

* *Automatische Erstellung von Geheimnissen*: Standardmäßig muss für das Diagramm ein `+stackstate.apiKey+` angegeben werden, und es erstellt selbständig ein Geheimnis. Die Seite `+STS_CLUSTER_AGENT_AUTH_TOKEN+` wird automatisch erstellt.
* *Benutzerdefinierte Verwaltung von Geheimnissen*: Wenn die Felder von `+fromSecret+` überschrieben werden, werden der API-Schlüssel und das Cluster-Auth-Token aus diesen Geheimnissen übernommen.
* *Stillschweigende Unterlassung*: Wenn Sie angeben, dass Sie Ihre eigenen Geheimnisse verwalten möchten, ignoriert das Diagramm die Werte für `+stackstate.apiKey+` und `+stackstate.cluster.authToken+`.

== Wie man in values.yaml verwendet

. *Automatische Geheimniserstellung verwenden (Standard)*:
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *Eigene Geheimnisse verwalten*:
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
