= Aplicaciones Java
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

El SDK de Java permite instrumentar aplicaciones en la JVM. Como resultado, no sólo es compatible con Java, sino también con otros lenguajes JVM como Kotlin y Scala.

== Instrumentación automática

La instrumentación automática para Java utiliza un JAR de agente Java que puede adjuntarse a cualquier aplicación Java 8+. Inyecta dinámicamente bytecode para capturar telemetría de muchas https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md[bibliotecas y frameworks populares de], incluidas varias bibliotecas de Kotlin y Scala. Puede utilizarse para capturar datos de telemetría en "`edges`" de una aplicación o servicio, como solicitudes entrantes, llamadas HTTP salientes, llamadas a bases de datos, etc.

La instrumentación automática no requiere ninguna modificación de la aplicación. Para configurarlo, sigue estos pasos:

. Descargue https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar[opentelemetry-javaagent.jar] de https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases[Releases] del repositorio opentelemetry-java-instrumentation e incluya el archivo JAR en la imagen docker de su aplicación. El archivo JAR contiene el agente y las bibliotecas de instrumentación.
. Actualice el comando que inicia su aplicación para cargar el agente Java, ya sea actualizando el punto de entrada o el comando de la imagen Docker o actualizando `command` en el manifiesto de Kubernetes para su aplicación. Añadir `-javaagent:/path/to/opentelemetry-javaagent.jar`:
+
[,bash]
----
java -javaagent:/path/to/opentelemetry-javaagent.jar -jar myapp.jar
----

. Despliega tu aplicación con las variables de entorno adicionales xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[para configurar el nombre del servicio y el punto final del exportador], los protocolos soportados son gRPC y protobuf sobre HTTP.
. Verifique que SUSE Observability está recibiendo trazas y/o métricas buscando las métricas / trazas en el explorador de métricas / trazas para su nombre de servicio

Para más detalles, consulte la https://opentelemetry.io/docs/languages/java/automatic/[documentación de].

== Instrumentación manual

La instrumentación manual puede utilizarse cuando se necesitan métricas, trazas o registros de partes del código que no son compatibles con la instrumentación automática. Por ejemplo, bibliotecas no compatibles, código interno o métricas a nivel empresarial.

Para capturar esos datos es necesario modificar la aplicación.

. Incluya el SDK de telemetría abierta como dependencia
. Añada código a su aplicación para capturar métricas, intervalos o registros cuando sea necesario

Existe documentación detallada al respecto en https://opentelemetry.io/docs/languages/java/instrumentation/[las páginas de documentación de].

Asegúrese de utilizar el exportador OTLP (es el predeterminado) y https://opentelemetry.io/docs/languages/java/instrumentation/#_autoconfiguration[auto-configuration]. Al desplegar la aplicación, el nombre del servicio y el exportador se xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[configuran mediante variables de entorno].

== Métricas en SUSE Observability

ifdef::ss-ff-stackpacks2_enabled[]
Para algunas métricas de Java, por ejemplo, las métricas del recolector de basura, SUSE Observability ha definido gráficos sobre los componentes relacionados. Para Kubernetes, los gráficos están disponibles en los pods. Es posible xref:/setup/custom-integrations/metric-bindings/index.adoc[añadir gráficos para más métricas], esto funciona para métricas de instrumentación automática pero también para métricas específicas de la aplicación de instrumentación manual.
endif::[]

ifndef::ss-ff-stackpacks2_enabled[]
Para algunas métricas de Java, por ejemplo, las métricas del recolector de basura, SUSE Observability ha definido gráficos sobre los componentes relacionados. Para Kubernetes, los gráficos están disponibles en los pods. Es posible xref:/use/metrics/k8s-add-charts.adoc[añadir gráficos para más métricas], esto funciona para métricas de instrumentación automática pero también para métricas específicas de la aplicación de instrumentación manual.
endif::[]
