= Configuración de exportadores SDK
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

Para enviar datos a SUSE Observability, los SDK que se utilizan para instrumentar su aplicación utilizan un exportador integrado. Una configuración lista para producción utiliza <<_with_a_collector_production_setup,un recopilador>> cercano a sus aplicaciones instrumentadas para enviar los datos a SUSE Observability, pero también es posible hacer que la aplicación instrumentada <<_without_a_collector,envíe directamente>> los datos de telemetría a SUSE Observability.

== Con un colector (configuración de producción)

=== Configuración del exportador SDK para Kubernetes

Todos los SDK, independientemente del idioma, utilizan la misma configuración básica para definir el Open Telemetry https://opentelemetry.io/docs/concepts/glossary/#_service[nombre del servicio] y el punto final del exportador (es decir, dónde se envía la telemetría).

Éstas pueden configurarse estableciendo variables de entorno para su aplicación instrumentada.

En Kubernetes, establezca estas variables de entorno en el manifiesto de su carga de trabajo (sustituya `<the-service-name>` por el nombre de su servicio de aplicación):

[,yaml]
----
...
spec:
  containers:
  - env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317
    - name: OTEL_SERVICE_NAME
      value: <the-service-name>
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: grpc
...
----

El punto final especificado en el ejemplo supone que el recopilador se instaló utilizando los valores predeterminados de xref:/setup/otel/collector.adoc[la guía de instalación]. Utiliza el puerto `4317` que utiliza la versión `gRPC` del protocolo OTLP. Algunas instrumentaciones sólo admiten HTTP, en ese caso, utilice el puerto `4318`.

El nombre del servicio también puede derivarse de las etiquetas de Kubernetes que ya puedan estar presentes. Por ejemplo, así:

[,yaml]
----
spec:
  containers:
  - env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['app.kubernetes.io/component']
----

=== Configuración del exportador del SDK para otras instalaciones

Para configurar el SDK establezca estas variables de entorno para su aplicación:

[,bash]
----
export OTEL_EXPORTER_OTLP_ENDPOINT="http://<the-host-for-the-collector>:4317"
export OTEL_EXPORTER_OTLP_PROTOCOL="grpc"
export OTEL_SERVICE_NAME="<the-service-name>"
export OTEL_RESOURCE_ATTRIBUTES='service.namespace=<the-namespace>'
----

El ejemplo utiliza el puerto `4317` que utiliza la versión `gRPC` del protocolo OTLP. Algunos instrumentos sólo admiten HTTP, que utiliza el puerto `4318` con el protocolo configurado en `http`. Utilice la documentación del SDK de su idioma para comprobar qué protocolo admite el SDK. Los campos `OTEL_EXPORTER_OLTP_ENDPOINT` y `OTEL_EXPORTER_OTLP_PROTOCOL` pueden omitirse, tienen valores por defecto que envían los datos al endpoint preferido en el localhost.

`OTEL_RESOURCE_ATTRIBUTES` es opcional y, además de definir un espacio de nombres de servicio, puede utilizarse para establecer más atributos de recursos en una lista separada por comas.

=== gRPC frente a HTTP

OTLP, el Protocolo Abierto de Telemetría, soporta gRPC y protobuf sobre HTTP. En la sección anterior, el protocolo del exportador se establece en `gRPC`, que suele ofrecer el mejor rendimiento. Además de que el SDK no soporta gRPC puede haber otras razones para preferir HTTP:

* Algunos cortafuegos no están configurados para gestionar gRPC
* Es posible que los proxies (inversos) y los equilibradores de carga no admitan gRPC sin una configuración adicional.
* Las conexiones de larga duración de gRPC pueden causar problemas al equilibrar la carga.

Para cambiar a HTTP en lugar de gRPC cambie el protocolo a `http` _y_ utilice el puerto `4318`.

En resumen, puede intentar utilizar HTTP en caso de que gRPC no le funcione:

* `grpc` utiliza el puerto `4317` en el recopilador
* `http` utiliza el puerto `4318` en el recopilador

== Sin colector

En configuraciones de prueba pequeñas, puede ser conveniente enviar directamente los datos de su aplicación instrumentada a SUSE Observability. La única diferencia con respecto a la configuración del colector documentada anteriormente es utilizar un valor diferente para `OTEL_EXPORTER_OTLP_ENDPOINT`:

* Para gRPC utilice el punto final OTLP para SUSE Observability, consulte la xref:/setup/otel/otlp-apis.adoc[página de APIs OTLP].
* Para HTTP utilice el punto final OTLP sobre HTTP para SUSE Observability, consulte la xref:/setup/otel/otlp-apis.adoc[página de APIs OTLP].

[NOTE]
====
Sustituya la URL del recopilador *y* el puerto por los extremos de SUSE Observability. Dependiendo de su instalación de SUSE Observability los puertos serán diferentes.
====

