= Certificados autofirmados
:revdate: 2025-07-29
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

== Servidor SUSE Observability

=== Exposición de SUSE Observability Server con certificados autofirmados

Los componentes de xref:k8s-suse-rancher-prime.adoc#_installation[SUSE Observability Server] no pueden terminar SSL por sí mismos y deben utilizar un Ingress Controller o LoadBalancer protegido por SSL para exponer el servicio con HTTPS. Esta sección explica cómo configurar un controlador de entrada con certificados autofirmados.

==== Uso de Ingress Controller con TLS

Para exponer SUSE Observability Server mediante https://kubernetes.github.io/ingress-nginx/[Ingress Controller] Nginx con certificados autofirmados, es necesario:

1. Cree secretos TLS de Kubernetes a partir del certificado y la clave de su servidor
2. Configurar el recurso Ingress con ajustes TLS
3. Implantar SUSE Observability Server con Ingress activado

===== Creación de secretos TLS

Cree secretos TLS de Kubernetes a partir de sus archivos de certificado y clave privada:

[,bash]
----
# Create TLS secret for main SUSE Observability Server
kubectl create secret tls tls-secret \
  --cert=server.crt \
  --key=server.key \
  --namespace suse-observability

# Create TLS secret for OTLP GRPC endpoint
kubectl create secret tls otlp-tls-secret \
  --cert=otlp-server.crt \
  --key=otlp-server.key \
  --namespace suse-observability

# Create TLS secret for OTLP HTTP endpoint
kubectl create secret tls otlp-http-tls-secret \
  --cert=otlp-http-server.crt \
  --key=otlp-http-server.key \
  --namespace suse-observability
----

===== Configuración de los valores del timón

Cree un archivo de valores (por ejemplo, `ingress-with-tls-values.yaml`) con la configuración de Ingress:

[NOTE]
====
*Nota:*
Esta configuración es específica del Nginx https://kubernetes.github.io/ingress-nginx/[controlador de entrada]. Si utiliza un Ingress Controller diferente, ajuste las anotaciones y la configuración en consecuencia.
====

[,yaml]
----
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: suse-observability.MY_DOMAIN
  tls:
    - hosts:
        - suse-observability.MY_DOMAIN
      secretName: tls-secret

opentelemetry-collector:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
    hosts:
      - host: otlp-suse-observability.MY_DOMAIN
        paths:
          - path: /
            pathType: Prefix
            port: 4317
    tls:
      - hosts:
          - otlp-suse-observability.MY_DOMAIN
        secretName: otlp-tls-secret
    additionalIngresses:
      - name: otlp-http
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        hosts:
          - host: otlp-http-suse-observability.MY_DOMAIN
            paths:
              - path: /
                pathType: Prefix
                port: 4318
        tls:
          - hosts:
              - otlp-http-suse-observability.MY_DOMAIN
            secretName: otlp-http-tls-secret
----

===== Instalación con Ingress

Implante SUSE Observability Server utilizando la configuración Ingress:

[,bash]
----
helm upgrade --install \
  --namespace suse-observability \
  --create-namespace \
  --values ingress-with-tls-values.yaml \
  suse-observability \
  suse-observability/suse-observability
----

Para obtener instrucciones completas de instalación, consulte xref:k8s-suse-rancher-prime.adoc#_installation[Instalación].

=== SUSE Observability Server se conecta a sistemas externos con certificados autofirmados

[NOTE]
====
Esta sección sirve para configurar SUSE Observability Server para que confíe en sistemas externos que utilicen certificados autofirmados. Esto se aplica cuando el servidor necesita hacer conexiones salientes a servicios externos (como webhooks) que están asegurados con certificados autofirmados.
====

SUSE Observability Server tiene varios puntos de interacción con sistemas externos. Por ejemplo, los controladores de eventos pueden llamar a webhooks de otros sistemas. Con la configuración predeterminada, SUSE Observability Server no podrá comunicarse con estos sistemas si están protegidos con TLS utilizando un certificado autofirmado o un certificado que no sea de confianza por defecto para la JVM.

Para mitigar esto, SUSE Observability Server permite la configuración de un almacén de confianza personalizado.

=== Crear un almacén de confianza personalizado

Es necesario disponer del certificado TLS personalizado. Si no lo tienes, tendrás que xref:/use/security/self-signed-certificates.adoc#_retrieve_certificate_via_the_browser[recuperarlo a través del navegador].

Utilice la herramienta keytool y el archivo `cacerts` incluido en la instalación de JVM (Java Virtual Machine) para convertir un archivo de certificado TLS existente al formato que necesita SUSE Observability Server. Puede ejecutarlo en cualquier máquina, independientemente del tipo de sistema operativo.

Si no tiene la JVM instalada en su ordenador, también puede xref:/use/security/self-signed-certificates.adoc#_using_a_docker_jvm[utilizar una imagen Docker de la JVM].

==== Uso de una JVM instalada

Con la JVM instalada en tu ordenador y el certificado guardado como archivo `site.cert`, puedes crear un nuevo almacén de confianza tomando el almacén de confianza de la JVM y añadiendo el certificado extra.

. Cree un directorio de trabajo `workdir` y copie el archivo de certificado `site.cert` en este directorio.
. Cambie de directorio a `workdir` y haga una copia del archivo `cacerts` de su instalación de Java. `$JAVA_HOME` es una variable de entorno que contiene la ubicación de su instalación de Java. Normalmente se configura al instalar Java.
+
[,bash]
----
cd workdir
cp $JAVA_HOME/lib/security/cacerts ./custom_cacerts
----

. Ejecute el siguiente comando keytool para añadir el certificado. La contraseña requerida es `changeit`. El alias tiene que ser un alias único para el certificado, por ejemplo el propio nombre del dominio sin puntos.
+
[,bash]
----
keytool -import -keystore custom_cacerts -alias <a-name-for-the-certificate>  -file site.cert
----

. El archivo de almacenamiento `custom_cacerts` incluirá ahora el certificado `site.cert`. Puede comprobarlo buscando el alias en la salida de
+
[,bash]
----
keytool -list -keystore custom_cacerts
----

==== Uso de una JVM Docker

Si no tienes JVM instalada en tu ordenador, puedes utilizar una imagen Docker de JVM. El certificado debe recuperarse y guardarse como archivo `site.cert`.

. Cree un directorio de trabajo `workdir` y copie el archivo de certificado `site.cert` en este directorio.
. Inicie el contenedor Java Docker con `workdir` montado como un volumen para que se pueda acceder a él:
+
[,bash]
----
docker run -it -v `pwd`/workdir:/workdir  adoptopenjdk:11 bash
----

. Cambie de directorio a `workdir` y haga una copia del archivo `cacerts`:
+
[,bash]
----
cd /workdir
cp $JAVA_HOME/lib/security/cacerts ./custom_cacerts
----

. Ejecute el siguiente comando keytool para añadir el certificado. La contraseña requerida es `changeit`. El alias tiene que ser un alias único para el certificado, por ejemplo el propio nombre del dominio sin puntos.
+
[,bash]
----
keytool -import -keystore custom_cacerts -alias <a-name-for-the-certificate>  -file site.cert
----

. El archivo de almacenamiento `custom_cacerts` incluirá ahora el certificado `site.cert`. Puede comprobarlo buscando el alias en la salida de
+
[,bash]
----
 keytool -list -keystore custom_cacerts
----

=== Utilizar un almacén de confianza personalizado

El almacén de confianza y la contraseña pueden especificarse como valores. El almacén de confianza sólo puede especificarse desde la línea de comandos de helm, ya que se trata de un archivo. El valor de la contraseña se especifica de la misma forma que en el ejemplo, pero también se puede proporcionar a través de un archivo `values.yaml`.

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --set-file 'stackstate.java.trustStore'=custom_cacerts \
  --set 'stackstate.java.trustStorePassword'=changeit \
suse-observability \
suse-observability/suse-observability
----

[NOTE]
====
*Nota:*

* La primera ejecución del comando helm upgrade provocará el reinicio de los pods, lo que puede causar una breve interrupción de la disponibilidad.
* Incluya estos argumentos en cada ejecución de `helm upgrade`.
* La contraseña y el almacén de confianza se almacenan como secreto de Kubernetes.
====


[discrete]
==== Almacenes de confianza codificados en Base64

Si es necesario, el almacén de confianza de Java también puede configurarse pasando cadenas codificadas en Base64 a los valores de Helm.

[tabs]
====
Linux::
+
--

Para utilizar un almacén de confianza codificado en base64, ejecute el siguiente comando `helm upgrade`:

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --set 'stackstate.java.trustStoreBase64Encoded'=$(cat custom_cacerts | base64 -w0) \
  --set 'stackstate.java.trustStorePassword'=changeit \
suse-observability \
suse-observability/suse-observability
----

--
MacOs::
+
--

Para utilizar un almacén de confianza codificado en base64, ejecute el siguiente comando `helm upgrade`:

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --set 'stackstate.java.trustStoreBase64Encoded'=$(cat custom_cacerts | base64) \
  --set 'stackstate.java.trustStorePassword'=changeit \
suse-observability \
suse-observability/suse-observability
----

--
====

=== Recuperar certificado a través del navegador

El certificado puede descargarse directamente desde el navegador Chrome. Los pasos a seguir pueden variar ligeramente en función de la versión que utilice:

. Navegue hasta la URL de la que necesita el certificado.
. Haga clic en el icono del candado de la barra de direcciones.
. Haga clic en *Certificado*.
. Seleccione *Detalles*.
. Seleccione *Exportar*.
. Guarde utilizando el tipo de archivo de exportación por defecto (codificado ASCII Base64).

== Agente de observabilidad de SUSE

xref:k8s-suse-rancher-prime.adoc#_installing_the_suse_observability_agent[El agente de SUSE Observ] ability se conecta al servidor de SUSE Observability mediante HTTPS. Si su servidor utiliza un certificado autofirmado, debe configurar el Agente para que confíe en este certificado para establecer conexiones seguras.

[NOTE]
====
Esta configuración también es necesaria cuando su servidor utiliza certificados firmados por una Autoridad de Certificación (CA) privada. En este caso, añada el certificado CA privado utilizando los mismos métodos descritos a continuación.
====

=== Configurar certificados personalizados

Configure certificados personalizados a través de los valores del gráfico de Helm utilizando uno de estos dos métodos:

==== Método 1: Datos PEM directos

Incruste los datos del certificado directamente en su configuración de Helm:

[,yaml]
----
global:
  customCertificates:
    enabled: true
    pemData: |
      -----BEGIN CERTIFICATE-----
      MIIDrzCCApegAwIBAgIUDMPkLOLGJ12438MbI32eykbw2xowDQYJKoZIhvcNAQEL
      BQAwKTEnMCUGA1UEAwwedmlsaWFrb3Yuc2FuZGJveC5zdGFja3N0YXRlLmlvMB4X
      DTI1MDcxNzEzMjgzN1oXDTI2MDcxNzEzMjgzN1owKTEnMCUGA1UEAwwedmlsaWFr
      b3Yuc2FuZGJveC5zdGFja3N0YXRlLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
      MIIBCgKCAQEA0MIdPOxrCpXB+F6P6NY7MyOimuViVWJGDW9ckz4mXZYCJD4iqrKS
      Y4bP6ODO4BgWxKFElxNdwNIqhLmI7RR1MWSRo47oxwPLnqw3INlsX0t1rBp6k6zK
      K4YY+wGdUH/keug03uMS7HxBXEmhCaMnGPj2BBfB4URc41DkFexGU/Fi1cyv0aCq
      CgxbThN/fGSGN2evLuabk9mfw4AH3K8isQ+kS9i3O459BgDGH8yjbrWfBUdPXVx5
      iFiYjGJjVM0pTP1dNriTc88lpajXRK++6O2gmjL9kbf0PGzRsvqqVgI07yR8uV1I
      0MaUwM2/VJrVB6t80wBuC1Tiv+RiYmtJXwIDAQABo4HOMIHLMB0GA1UdDgQWBBSh
      iKBCmrp8jHSCMvUnHv/Wgg7LyDAfBgNVHSMEGDAWgBShiKBCmrp8jHSCMvUnHv/W
      gg7LyDAPBgNVHRMBAf8EBTADAQH/MHgGA1UdEQRxMG+CHnZpbGlha292LnNhbmRi
      b3guc3RhY2tzdGF0ZS5pb4Ijb3RscC12aWxpYWtvdi5zYW5kYm94LnN0YWNrc3Rh
      dGUuaW+CKG90bHAtaHR0cC12aWxpYWtvdi5zYW5kYm94LnN0YWNrc3RhdGUuaW8w
      DQYJKoZIhvcNAQELBQADggEBAIuBFVqJsJImOB4thRk+FFd7UJlK1kQna9woKv23
      ju+fpEWgZZQ0U/xGS9f3JvxCUJv8oj3HYkfPQQgtPmewATVBx2cTRpogV6JFcAo7
      fPSLCzOuSt3c4SM1OtDnyToUaAf6YQQT4m+V4IKb6Qo0XWfCxhkuKJlOfmDtqNg/
      uVYjfG7KOZs6CTJwqdIwpNDbLD+DNfo3b/c731Qa1b9o8Z8rIrNrYXj4kly3D1
      97QiVJCL0u/fC+/KsUxq9ynAYSPgyd2CBnxnQDcq8aQATVTlAafSfk0shvucgQmJ
      KIL9xaM3iTdvrWGtWeAiEQocsRBJM5xjqtnu0R5xDlLU/TQ=
      -----END CERTIFICATE-----
----

==== Método 2: Referencia ConfigMap

Cree un Kubernetes ConfigMap con su certificado y haga referencia a él en la configuración de Helm:

[,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: tls-config
data:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    [Your certificate content here]
    -----END CERTIFICATE-----
----

Haga referencia al ConfigMap en su configuración de Helm:

[,yaml]
----
global:
  customCertificates:
    enabled: true
    configMapName: "tls-config"
----

=== Despliegue con certificados personalizados

==== Utilización de datos PEM directos

Para el enfoque directo de datos PEM, primero almacene su certificado en una variable shell:

[,bash]
----
export CERT_DATA=$(cat <<'EOF'
-----BEGIN CERTIFICATE-----
[Your certificate content here]
-----END CERTIFICATE-----
EOF
)
----

Despliegue el Agente con la configuración del certificado:

[,bash]
----
helm upgrade --install \
  --namespace suse-observability \
  --create-namespace \
  --set-string 'stackstate.apiKey'='YOUR_API_KEY' \
  --set-string 'stackstate.cluster.name'='YOUR_CLUSTER_NAME' \
  --set-string 'stackstate.url'='YOUR_SUSE_OBSERVABILITY_URL' \
  --set 'global.customCertificates.enabled'=true \
  --set 'global.customCertificates.pemData'="$CERT_DATA" \
  suse-observability-agent suse-observability/suse-observability-agent
----

==== Uso de la referencia ConfigMap

Para el enfoque ConfigMap, cree el ConfigMap que contenga su certificado:

[,bash]
----
kubectl create configmap tls-config \
  --from-file=tls.crt=your-certificate.crt \
  --namespace suse-observability
----

Despliegue el Agente con la referencia ConfigMap:

[,bash]
----
helm upgrade --install \
  --namespace suse-observability \
  --create-namespace \
  --set-string 'stackstate.apiKey'='YOUR_API_KEY' \
  --set-string 'stackstate.cluster.name'='YOUR_CLUSTER_NAME' \
  --set-string 'stackstate.url'='YOUR_SUSE_OBSERVABILITY_URL' \
  --set 'global.customCertificates.enabled'=true \
  --set 'global.customCertificates.configMapName'='tls-config' \
  suse-observability-agent suse-observability/suse-observability-agent
----

== CLI de SUSE Observability

xref:setup/cli/cli-sts.adoc[La CLI de SUSE Observability] se conecta al servidor de SUSE Observability mediante HTTPS. Si el servidor utiliza certificados autofirmados o certificados de una entidad emisora de certificados (CA) privada, configure la CLI para que confíe en estos certificados.

=== Configurar certificados CA personalizados

Configure certificados CA personalizados utilizando uno de estos métodos:

* **Configuración persistente**: Utilice `sts context save` para almacenar la configuración del certificado para futuros comandos.
* **Uso único**: Añadir indicadores de certificado a comandos CLI individuales cuando sea necesario

==== Método 1: Ruta del archivo del certificado CA

Especifique la ruta a su archivo de certificado CA codificado en PEM:

[,bash]
----
sts context save \
  --name staging \
  --url https://staging.internal \
  --api-token YOUR_API_TOKEN \
  --ca-cert-path /path/to/ca.crt
----

==== Método 2: Datos del certificado CA codificados en Base64

Proporcione los datos del certificado CA como una cadena codificada en base64:

[,bash]
----
sts context save \
  --name staging \
  --url https://staging.internal \
  --api-token YOUR_API_TOKEN \
  --ca-cert-base64-data BASE64_ENCODED_CERTIFICATE_DATA
----

==== Uso de certificados CA con otros comandos

Utilice los indicadores de certificado con cualquier comando de la CLI para validar el certificado una sola vez:

[,bash]
----
# Using certificate file path
sts agent list \
  --url https://staging.internal \
  --api-token YOUR_API_TOKEN \
  --ca-cert-path /path/to/ca.crt

# Using base64-encoded certificate data
sts settings list \
  --url https://staging.internal \
  --api-token YOUR_API_TOKEN \
  --ca-cert-base64-data BASE64_ENCODED_CERTIFICATE_DATA
----

=== Prioridad de configuración

Cuando se proporcionan ambas opciones de certificado, la ruta del archivo (`--ca-cert-path`) tiene prioridad sobre los datos base64 (`--ca-cert-base64-data`).

=== Almacenamiento

Las configuraciones de los certificados se almacenan en: `~/.config/stackstate-cli/config.yaml`

[NOTE]
====
**Importante**: La bandera `--skip-ssl` desactiva toda verificación SSL e ignora las configuraciones de certificados. Utilice siempre las opciones de certificado CA para conexiones seguras con certificados personalizados.
====

== Telemetría abierta de SUSE Observability

=== Crear un configmap para la Autoridad de Certificación personalizada

----
kubectl create configmap tls-config \
  --namespace open-telemetry \
  --from-file=tls.crt=<your-certificate>
----

. Monte el configmap añadiendo lo siguiente en el nivel superior de `otel-collector.yaml`:

----
# Mounting volume for CA certificate
extraVolumes: 
  - name: tls-config
    configMap:
      items:
        - key: tls.crt
          path: tls.crt
      name: tls-config
extraVolumeMounts:
  - mountPath: "/certs"
    name: tls-config
    readOnly: true
----

. Actualice la configuración del exportador en `otel-collector.yaml` para utilizar el certificado *ca_file* añadiendo la clave `tls.ca_file`:

----
otlp/suse-observability:
  auth:
    authenticator: bearertokenauth
  # Put in your own otlp endpoint, for example suse-observability.my.company.com:443
  endpoint: <your-endpoint>
  compression: snappy
  tls:
    ca_file: /certs/tls.crt
----

. Instale (o actualice) su colector Open Telemetry.

== Extensión de Rancher UI para SUSE Observability

Al instalar la extensión Rancher UI para SUSE Observability (consulte xref:/k8s-suse-rancher-prime.adoc#_installing_ui_extensions[Instalación de extensiones UI]), la extensión debe comunicarse con su servidor SUSE Observability. Si su servidor utiliza certificados autofirmados, la instalación de la extensión fallará.

**Solución**: Añada su certificado personalizado a Rancher antes de instalar la extensión. Siga la documentación de Rancher: https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/custom-ca-root-certificates[configuring custom CA root certificates^].

Tras configurar el certificado en Rancher, la extensión se conectará correctamente a su servidor de SUSE Observability.
