= リピート・スナップショット
:revdate: 2025-10-27
:page-revdate: {revdate}
:description: SUSE Observability

== 概要

このページでは、ヘルス同期リピートのスナップショット一貫性モデルで送信できる正確なJSONメッセージについて説明します。

== JSONプロパティ: "health"

ヘルスは、xref:/configure/health/send-health-data/send-health-data.adoc#_common_json_object[共通 JSON オブジェクトの] `+"health"+` プロパティを使用して SUSE Observability Receiver API に送信できます。

[tabs]
====
健康状態の例`+repeat_snapshots+` JSON::
+
--
[,javascript]
----
{
   "apiKey":"<STACKSTATE_RECEIVER_API_KEY>",
   "collection_timestamp":1585818978,
   "internalHostname":"lnx-343242.srv.stackstate.com",
   "health":[
      {
        "consistency_model": "REPEAT_SNAPSHOTS",
        "start_snapshot": {
          "repeat_interval_s": 50
          //"expiry_interval_s": 200 Optional
        },
        "stop_snapshot": {},
        "stream": {
          "urn": "urn:health:sourceId:streamId"
          //"sub_stream_id": "subStreamId" Optional
        },
        "check_states": [
          {
            "checkStateId": "checkStateId1",
            "message": "Server Running out of disk space",
            "health": "Deviating",
            "topologyElementIdentifier": "server-1",
            "name": "Disk Usage"
          },
          {
            "checkStateId": "checkStateId2",
            "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
            "health": "critical",
            "topologyElementIdentifier": "server-2",
            "name": "Health monitor"
          }
        ]
      }
   ]
}
----
--
====

すべてのヘルスリピートスナップショットデータペイロードには、以下の詳細があります：

* *start_snapshot* - Optional.`+check_states+` を処理する前に、スナップショットの開始を処理する必要がある。これにより、SUSE Observabilityは、以前に受信したスナップショットとストリームスナップショットを差分し、スナップショットに存在しなくなったチェック状態を削除できます。スナップショットのメタデータとして以下のフィールドを持つ：
 ** *repeat_interval_s*- 秒単位の時間．外部ソースがSUSE Observabilityにヘルスデータを送信する頻度。最大許容値は1800（30分）。
 ** *expiry_interval_s*- 秒単位の時間。SUSE Observabilityによって外部チェックが削除されるまでの、最終更新後の待機時間。サブストリームを使用する場合は必須。
* *stop_snapshot* - Optional.スナップショットの終了は、+``check``_states+の処理後に処理されます。
* *stream*- どのスナップショットと`+check_states+` が一緒になっているかという識別を提供するオブジェクト。以下のフィールドがある：
 ** *urn*- 以下の規約に一致するSUSE Observabilityxref:/configure/topology/identifiers.adoc[URNとして]エンコードされたデータソースおよびストリームID:`+urn:health:<sourceId>:<streamId>+` `+<sourceId>+` は外部データソースの名前、`+<streamId>+` はヘルスデータストリームの一意の識別子です。
 ** *sub_stream_id* - Optional.ストリームの健全性データのサブセットの識別子。ストリームデータが分散され、複数のAgentによって報告される場合、以下のようなスナップショットライフサイクルが可能になる。 `+sub_stream_id+`
* *check_states*- チェック状態のリスト。各チェック状態は以下のフィールドを持つことができる：
 ** *checkStateId*- 外部システムにおけるチェック状態の識別子。
 ** *message*- オプション。SUSE Observability UIに表示するメッセージ。データはマークダウンとして解釈され、外部チェック状態を生成した外部システムチェックへのリンクを持つことができる。
 ** *health*- 以下のSUSE Observability Health状態値のいずれか：`+Clear+`,`+Deviating+`,`+Critical+`.
 ** *topologyElementIdentifier*- チェック状態をSUSE Observabilityトポロジ要素にバインドするために使用されます。
 ** *name*- 外部チェック状態の名前。

== ヘルスをSUSE Observabilityに送信する

健康状態は、HTTP POSTを介して1つのJSONメッセージで送信することができます。以下の例では、2つのチェック状態を含むスナップショットが、1つの外部監視システムからSUSE Observabilityに送信されます。

[,bash]
----
curl -X POST \
 '<STACKSTATE_RECEIVER_API_ADDRESS>' \
 -H 'Content-Type: application/json' \
 -d '{
  "collection_timestamp": 1548857167,
  "internalHostname": "local.test",
  "health": [
    {
      "consistency_model": "REPEAT_SNAPSHOTS",
      "start_snapshot": {
        "repeat_interval_s": 300
      },
      "stop_snapshot": {},
      "stream": {
        "urn": "urn:health:sourceId:streamId"
      },
      "check_states": [
        {
          "checkStateId": "checkStateId1",
          "message": "Server Running out of disk space",
          "health": "Deviating",
          "topologyElementIdentifier": "server-1",
          "name": "Disk Usage"
        },
        {
          "checkStateId": "checkStateId2",
          "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
          "health": "critical",
          "topologyElementIdentifier": "server-2",
          "name": "Health monitor"
        }
      ]
    }
  ]
}'
----
