= Referência do cluster
:revdate: 2025-09-08
:page-revdate: {revdate}

Uma definição de `Cluster` inclui um `kubernetesVersion` e uma lista de `machinePools` para implementar o cluster.

Para saber como selecionar um `kubernetesVersion`, consulte nossa página xref:references/kubernetesversions.adoc[Versões do Kubernetes].

Um `machinePool` é um pacote de configuração com um `ObjectReference` para que o cluster seja implantado nesses `machinePools`com as funções adequadas (etcd, control-plane, worker) com uma quantidade (quantos nós devem ser implantados a partir desse pool) e algumas configurações extras (configuração de atualização contínua, máximo de nós insalubres etc.)...).

.Clique aqui para obter detalhes
[%collapsible]
====
Exemplo
[,yaml]
----
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: ...
  namespace: ...
spec:
  rkeConfig:
    machinePools:
      - name: ...
        controlPlaneRole: ...
        etcdRole: ...
        workerRole: ...
        quantity: ...
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: ...
      - name: ...
        controlPlaneRole: ...
        etcdRole: ...
        workerRole: ...
        quantity: ...
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: ...
----
====


Também é possível desativar os componentes do cluster por meio do objeto `Cluster` em `spec.rkeConfig.machineGlobalConfig`, por exemplo:

.Clique aqui para obter detalhes
[%collapsible]
====
Exemplo de desativação de serviço
[,yaml]
----
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: ...
  namespace: ...
spec:
  rkeConfig:
    machinePools:
      - name: ...
        controlPlaneRole: ...
        etcdRole: ...
        workerRole: ...
        quantity: ...
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: ...
    machineGlobalConfig:
      disable:
        - servicelb
        - ...
----
====


== rkeConfig.machinePools

Uma lista de `machinePools`. É necessário um mínimo de 1 `machinePools` para o cluster a ser implantado.

== Referência de especificações de machinePools

|===
| Chave | Tipo | Valor padrão | Descrição

| controlPlaneRole
| bool
| falso
| Definir máquinas nesse pool como plano de controle

| etcdRole
| bool
| falso
| Definir máquinas nesse pool como etcd

| workerRole
| bool
| falso
| Definir máquinas nesse pool como trabalhadores

| nome
| string
| nulo
| Nome para essa piscina

| quantidade
| int
| nulo
| Número de máquinas a serem implementadas a partir desse pool

| unhealthyNodeTimeout
| int
| nulo
| Tempo limite para verificações de integridade de nós não saudáveis

| machineConfigRef
| int
| ObjectReference
| Referência a um objeto usado para saber quais nós fazem parte desse pool
|===

É necessário um mínimo de `quantity` definido como um para que esse pool seja usado.
Basicamente, isso se traduz em quantos nós desse pool serão configurados para esse cluster.

.Clique aqui para obter detalhes
[%collapsible]
====
Exemplo
[,yaml]
----
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: cluster-example
  namespace: example-default
spec:
  rkeConfig:
    machinePools:
      - name: examplePool 
        controlPlaneRole: true
        etcdRole: true
        workerRole: false
        quantity: 3
        unhealthyNodeTimeout: 0s
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: exampleSelector
----
====


== machineConfigRef Spec Reference

Um `machineConfigRef` é um k8s `ObjectReference` genérico que geralmente contém um`kind` `name` e um `apiVersion` para apontar para um objeto diferente.

Em {elemental-product-name}, definimos isso como um xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate].
Isso nos permite apontar para mais de um objeto usando o seletor.

=== Exemplo

O exemplo abaixo cria um cluster que usa 2 ``machinePool`` diferentes para definir diferentes nós para o plano de controle e nós de trabalho, com base em 2 `MachineInventorySelectorTemplate` diferentes que selecionam seus nós com base em um rótulo `MachineInventory` (local):

[CAUTION]
.aviso
====
Os rótulos do exemplo são rótulos definidos manualmente, não são definidos automaticamente pelo site {elemental-product-name}..
====

.Exemplo de um cluster com mais de um machinePool
[,yaml]
----
include::example$clusters/clusters-several-machinepools.yml[]
----
