= 宣言型ネットワーキングのトラブルシューティング
:revdate: 2025-09-08
:page-revdate: {revdate}

次のような登録例がある：

.宣言的ネットワーキングを使用したMachineRegistrationの例
[,yaml]
----
include::example$network/machineregistration.yaml[]
----

各エレメンタルマシンは、定義された`nm-configurator` `_all.yaml` テンプレートを使用してコンフィギュレーションされることが予想される。

最初の起動時に、`elemental-register` は Rancher API にコンタクトして新しい`MachineInventory` を登録しようとする。

この段階では、マシンのネットワークは設定されておらず、DHCPがデフォルトとなる。このセットアップでは、マシンがRancher APIとコンタクトできることが必須条件であり、そうでなければ登録は行われない。

`MachineInventory` が最初に登録されると、`elemental-operator` は、ネットワーク・コンフィギュレーションで定義された`IPPool` 参照ごとに、`IPAddress` を要求することになる。

`MachineInventory` では以下のように表示される：

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  finalizers:
  - machineinventory.elemental.cattle.io
  name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c
  namespace: fleet-default
spec:
  ipAddressClaims:
    inventory-ip:
      apiVersion: ipam.cluster.x-k8s.io/v1beta1
      kind: IPAddressClaim
      name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c-inventory-ip
      namespace: fleet-default
      uid: 78f2d07a-7b6d-4b58-b615-c4108b7964b9
  ipAddressPools:
    inventory-ip:
      apiGroup: ipam.cluster.x-k8s.io
      kind: InClusterIPPool
      name: elemental-inventory-pool
  network:
    config:
      dns-resolver:
        config:
          search: []
          server:
          - 192.168.122.1
      interfaces:
      - description: Main-NIC
        ipv4:
          address:
          - ip: "{inventory-ip}"
            prefix-length: 24
          dhcp: false
          enabled: true
        ipv6:
          enabled: false
        name: eth0
        state: up
        type: ethernet
      routes:
        config:
        - destination: 0.0.0.0/0
          metric: 150
          next-hop-address: 192.168.122.1
          next-hop-interface: eth0
          table-id: 254
    ipAddresses:
      inventory-ip: 192.168.122.150
status:
  conditions:
  - lastTransitionTime: "2024-07-30T11:50:47Z"
    message: NetworkConfig is ready
    reason: ReconcilingNetworkConfig
    status: "True"
    type: NetworkConfigReady
----

`MachineInventory` は`MachineRegistration` と同じ`network.config` を持つが、IPAddressPools を参照する代わりに、実際の IPAddresses のマップを持っていることに気づくだろう：

[,yaml]
----
    ipAddresses:
      inventory-ip: 192.168.122.150
----

この`inventory-ip` は、`{inventory-ip}` が定義されるたびに、`nm-configurator` のコンフィグに代入される。

また、`MachineInventory` 、それに関連する各`IPAddressClaim` を参照し、所有していることに注意。各クレームは、`$MachineInventoryName-$IPPoolRefKey` の命名規則に従っている：`m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c-inventory-ip` 。

これらのクレームは、`MachineInventory` オブジェクトのライフサイクルに従 い、カスケード時に、例えばxref:node-operational-tasks/reset.adoc[リセットワークフロー]中に削除される。

`IPAddresses` を請求できない場合、`NetworkConfigReady` の状態が`False` となり、マシンがインストールを完了できなくなる。`IPPool` 、`IPAddresses` 。

== マシン側

インストール段階で、マシン上で実行されている`elemental-register` プロセスは、`nm-configurator` `_all.yaml` の設定テンプレートと、請求された IPAddresses のリストとそのキーを受け取る。この情報は、該当する`nm-configurator` のコンフィギュレーションにダイジェストされる：

[,yaml]
----
config:
  dns-resolver:
    config:
      search: []
      server:
      - 192.168.122.1
  interfaces:
  - description: Main-NIC
    ipv4:
      address:
      - ip: "192.168.122.150"
        prefix-length: 24
      dhcp: false
      enabled: true
    ipv6:
      enabled: false
    name: eth0
    state: up
    type: ethernet
  routes:
    config:
    - destination: 0.0.0.0/0
      metric: 150
      next-hop-address: 192.168.122.1
      next-hop-interface: eth0
      table-id: 254
----

その後、`elemental-register` が`nmc generate` と`nmc apply` を起動し、このコンフィギュレーションを実行中のシステムに適用する。

この瞬間からリセットされるまで、マシンは常に適用された設定を使用します。

また、インストールとリセット以外では、`nm-configurator` はもはや使用されないことに注意してください。`elemental-register` は、`nmc` コンフィギュレーションそのものではなく、`nmc` によって生成された`/etc/NetworkManager/system-connection/*.nmconnection` ファイルを永続化するからです。

例えば、稼働中のシステムには、https://github.com/rancher/yip[]yipコンフィギュレーション・ファイル（`/oem/elemental-network.yaml` ）があり、希望の`nmconnections` を適用することができる：

[,yaml]
----
name: Apply network config
stages:
    initramfs:
        - files:
            - path: /etc/NetworkManager/system-connections/Wired connection 1.nmconnection
              permissions: 384
              owner: 0
              group: 0
              content: |
                [connection]
                id=Wired connection 1
                uuid=d26b4ae4-d525-3cbf-a557-33feb60343c0
                type=ethernet
                autoconnect-priority=-999
                interface-name=eth0
                timestamp=1722340245

                [ethernet]

                [ipv4]
                address1=192.168.122.150/24
                dhcp-timeout=2147483647
                dns=192.168.122.1;
                dns-options=
                dns-priority=40
                method=manual
                route1=0.0.0.0/0,192.168.122.1,150
                route1_options=table=254

                [ipv6]
                addr-gen-mode=eui64
                dhcp-timeout=2147483647
                method=disabled

                [proxy]

                [user]
                nm-configurator.interface.description=Main-NIC
              encoding: ""
              ownerstring: ""
----

=== リセット中

xref:node-operational-tasks/reset.adoc[リセットが]トリガーされるたびに、マシン上で実行されている`elemental-register` 、すべての`/etc/NetworkManager/system-connection/*.nmconnection` ファイルをクリアし、ネットワークスタックを再起動する。その後、マシンはDHCPに戻り、その後、管理側の`elemental-operator` 、リセットが成功したことを確認する。

これは、`MachineInventory.spec.network.configurator` の値が`none` と異なる場合にのみ適用されることに注意。そうでなければ、マシン・リセット・フェーズの間、ネットワークをリセットするアクションは取られない。

ネットワークリセットの後、マシンはリカバリーモードに再起動し、実際のリセットを実行し、適用される新しいネットワーク構成を受信する必要があります。`MachineRegistration` が更新されていない場合）これは以前と同じである可能性もあるし、以前のIPはその間に他のマシンによって主張された可能性があるため、異なるIPを持つ可能性もある。

DHCPへの復帰が失敗した場合、またはマシンが確認のためにRancher APIに連絡できない場合、削除のタイムスタンプがあるにもかかわらず、`MachineInventory` が削除されないことがわかります。このマシンはネットワークに問題があるため、リモートで修理することはできない。

マシンに物理的にアクセスするか、DHCP駆動のネットワーク設定を修正するか、あるいは、マシンを廃棄するつもりなら、`MachineInventory` から`machineinventory.elemental.cattle.io` ファイナライザを削除して、削除できるようにすることもできます。
