include::partial$variables.adoc[]
= Suporte integrado
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Determinar quais funções internas estão disponíveis para os módulos do WebAssembly e entender sua implementação e uso no desenvolvimento de políticas do Rego.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "built-in-support"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "builtin wasm support"]
:sidebar_label: Suporte integrado
:current-version: {page-origin-branch}

Além disso, para criar uma política para o alvo `+wasm+`, ela precisa ser executada.

A equipe do Open Policy Agent (OPA) tem uma página que você pode consultar para obterhttps://www.openpolicyagent.org/docs/latest/policy-reference/#built-in-functions[o suporte incorporado do].

Ao criar uma política Rego em um módulo do WebAssembly, algumas dessas funções integradas estão no próprio arquivo Wasm.
Eles são os itens incorporados marcados com uma marca verde na página incorporada vinculada.
O tempo de execução do WebAssembly, que avalia o módulo, fornece os outros.

Os built-ins marcados como `+SDK-dependent+` são aqueles que o host precisa implementar, neste caso, {project-name}.
O OPA e o Gatekeeper podem usá-los, dependendo das necessidades da política.
De qualquer forma, esses itens incorporados são expostos à política e qualquer política nova ou existente pode depender deles.

Ainda existem alguns built-ins que ainda não são fornecidos pelo {short-project-name}, no entanto, com base nas políticas vistas em aberto, os já suportados devem ser suficientes para a maioria dos usuários do Kubernetes.

https://github.com/kubewarden/policy-evaluator/issues/56[Esta edição do GitHub]mantém o controle dos built-ins do Rego que ainda precisamos implementar.
Sinta-se à vontade para fazer comentários para ajudar a priorizar nosso trabalho.

== Execução de políticas com built-ins ausentes

Quando uma política é executada com `+kwctl+` ou com `+policy-server+`, a lista de suplementos integrados usados pela política é inspecionada.
Se algum dos componentes básicos usados estiver faltando, o programa interrompe a execução registrando um erro fatal que informa os componentes básicos ausentes.
