include::partial$variables.adoc[]
= 政策元数据
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 在 metadata.yaml 文件中配置策略元数据，以定义策略设置、作者信息和资源权限。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "policy-metadata"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes 政策开发"、"政策元数据"]
:current-version: {page-origin-branch}

{project-name} 元数据文件`+metadata.yaml+` 是一个配置文件，包含与{short-project-name} 中使用的策略有关的重要信息和设置。
本文档概述了元数据文件的目的和用法。

策略`+metadata.yaml+` 文件包含策略的默认值，以及由策略作者设置的作者和描述等元数据。
`+kwctl annotate+` 命令使用该文件来注释包含策略的`+.wasm+` 文件。
因此，运行政策所需的所有相关信息都可以获得。
有关如何注释策略的更多信息，请参阅 "xref:../../explanations/distributing-policies.adoc[分发]策略 "指南。

当策略用户要使用策略时，他们会使用`+kwctl scaffold+` 生成 YAML 清单。
该命令读取嵌入在已发布 Wasm 模块中的策略元数据，执行检查并返回 YAML 清单，作者可按原样使用或修改。

作为政策作者，您可以调整政策脚手架期间提供的`+metadata.yaml+` 文件。

请参见以下`+metadata.yaml+` 示例：

[subs="+attributes",yaml]
----
rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations: ["CREATE"]
mutating: false
contextAwareResources: []
executionMode: kubewarden-wapc
policyType: kubernetes
backgroundAudit: true
annotations:
  # kubewarden specific:
  io.kubewarden.policy.title: My policy
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: Short description
  io.kubewarden.policy.author: myself
  io.kubewarden.policy.url: https://github.com/yourorg/my-policy
  io.kubewarden.policy.source: https://github.com/yourorg/my-policy
  io.kubewarden.policy.license: Apache-2.0
  # The next two annotations are used in the policy report generated by the
  # Audit scanner. Severity indicates policy check result criticality and
  # Category indicates policy category. See more here at docs.kubewarden.io
  io.kubewarden.policy.severity: medium
  io.kubewarden.policy.category: Resource validation
  # artifacthub specific: (optional, to release in Artifact Hub)
  io.kubewarden.policy.ociUrl: ghcr.io/myorg/my-policy
  io.artifacthub.displayName: Policy Name
  io.artifacthub.resources: Pod
  io.artifacthub.keywords: pod, cool policy, kubewarden
----

== 启用背景审计检查

元数据文件包括一个标志`+backgroundAudit+` ，用于启用特定策略的后台审计检查。
默认情况下，该标志设置为`+true+` 。

有些政策由于其工作方式或所涉及的事件类型，应将该字段设置为`+false+` 。
您可以在xref:explanations/audit-scanner/limitations.adoc[审计扫描仪文档的]限制部分找到更多信息。

== 定义策略可访问的 Kubernetes 资源

在元数据文件中，用户可以使用`+contextAwareResources+` 字段定义策略可以访问哪些 Kubernetes 资源。
例如，如果策略需要访问`+Namespace+` 资源。
政策制定者可将`+contextAwareResources+` 定义为

[subs="+attributes",yaml]
----
[...]
contextAwareResources:
  - apiVersion: v1 kind: Namespace
[...]
----

== 指定政策为变异或非变异政策

元数据文件中有一个标志`+mutating+` ，用户可将策略配置为突变或非突变。
变异策略会修改接收到的请求或正在管理的资源。
非变异策略遵守并执行限制，不做任何更改。
这种区别对于确定策略如何与 Kubernetes 资源交互及其对集群的影响至关重要。

== 指定策略类型为 Kubernetes 或 Raw

元数据文件中有一个标志`+policyType+` ，用户可将政策标记为`+kubernetes+` 或`+raw+` 。
Kubernetes 策略是验证 Kubernetes 资源的策略。
原始策略是一种验证任意 JSON 文档的策略。
默认情况下，如果用户未指定，则在注释策略时将该字段设置为`+kubernetes+` 。
更多信息请参阅 "xref:../../howtos/raw-policies.adoc[原始政策]"部分。

== 定义资源类型目标

元数据文件为用户提供了在`+rules+` 字段中定义规则的功能，该字段决 定了政策适用的资源类型。
这一功能使用户能够对策略执行进行精确控制，确保策略只应用于预定的资源类型。
有了这种细粒度的控制，用户就能确保政策目标准确，符合他们的具体要求，并避免对不相关的资源类型意外应用政策。
