include::partial$variables.adoc[]
= Politiques tenant compte du contexte
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Les développeurs peuvent créer des politiques contextuelles qui récupèrent des informations sur les clusters Kubernetes au moment de l'exécution pour déterminer les critères d'acceptation d'AdmissionRequest.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["explanations", "context-aware-policies"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "context-aware policy", "clusteradmissionpolicy", "admissionpolicy", "admissionrequest", "cluster administrator"]
:sidebar_label: Politiques tenant compte du contexte
:sidebar_position: 20
:current-version: {page-origin-branch}

Les développeurs peuvent créer des politiques qui récupèrent des informations d'un cluster Kubernetes au moment de l'exécution. Il s'agit de politiques tenant compte du contexte. Les politiques tenant compte du contexte peuvent déterminer si une adresse `AdmissionRequest` est acceptable à l'aide d'informations provenant des ressources déployées dans la grappe.

[NOTE]
====
Les politiques contextuelles ne sont disponibles que dans les versions {project-name} ≥ v1.6.0.
====

Le contrôle des ressources auxquelles une politique peut accéder dans le cluster est assuré par le compte de service (https://kubernetes.io/docs/concepts/security/service-accounts/) du serveur de politique. Un administrateur de cluster contrôle ce à quoi une politique peut accéder via les règles RBAC de Kubernetes. Les politiques tenant compte du contexte n'ont qu'un accès *en lecture* aux ressources demandées.

Pour des raisons de sécurité, seules les politiques `ClusterAdmissionPolicy` peuvent extraire des informations du cluster Kubernetes. En effet, des utilisateurs non privilégiés peuvent déployer des ressources sur le site `AdmissionPolicy`.

Si un utilisateur non privilégié déploie une politique contextuelle en tant que`AdmissionPolicy`, le système :

- Bloque toutes les tentatives d'accès aux ressources Kubernetes.
- Les signale à l'administrateur du cluster.

Par défaut, {short-project-name} bloque toutes les ressources du cluster. Un administrateur {project-name} définit les ressources Kubernetes que chaque politique contextuelle peut lire.`contextAwareResources` pour ce faire.

L'exemple suivant déploie une politique qui exige l'accès aux ressources `Deployment`et `Pod`:

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: context-aware-policy
  namespace: default
spec:
  policyServer: default
  module: "registry://ghcr.io/kubewarden/policies/context-aware-policy:v1.0.0"
  settings: {}
  contextAwareResources:
    - apiVersion: "apps/v1"
      kind: "deployment"
    - apiVersion: "v1"
      kind: "pod"
  rules:
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployment"]
      operations:
        - CREATE
        - UPDATE
  mutating: false
----

Une fois déployée, cette politique peut lire les données des ressources `deployment` et `pod`.

Les auteurs de politiques fournissent des listes de ressources Kubernetes pour leur politique contextuelle. Les auteurs de politiques le font en annotant la politique. Les administrateurs de {project-name}visualisent les métadonnées des politiques à l'aide de la commande `kwctl inspect`. Ils peuvent obtenir une liste des ressources auxquelles la politique doit avoir accès. Un administrateur utilise cette liste pour remplir la définition de `ClusterAdmissionPolicy`.

[WARNING]
====

Pour éviter les abus, les administrateurs de {project-name} doivent examiner les ressources auxquelles la politique accède.

Par exemple, une politique évaluant les objets entrants aurait de bonnes raisons de lire les ressources `Ingress` définies dans le cluster. La même politique ne peut justifier l'accès aux ressources de `Secret`.

Les politiques doivent disposer du minimum d'accès nécessaire pour fonctionner correctement.

====


[NOTE]
====

L'identification des ressources Kubernetes utilise `apiVersion` et `kind`.

En général, `apiVersion` est une chaîne de caractères au format `<api>/<version>`. Les ressources du groupe d'API `core` (Pod, Service et autres) ne doivent pas définir le nom du groupe, `<api>`. Ils ne doivent définir que le `<version>` (par exemple, `v1`).

Pour une ressource de base, la première solution ne fonctionnera pas, la seconde oui.

[subs="+attributes",console]
----
- apiVersion: "core/v1"
  kind: "pod"
----

[subs="+attributes",console]
----
- apiVersion: "v1"
  kind: "pod"
----

Toutes les autres ressources Kubernetes ont besoin de la définition complète : `<api>/<version>`.
====


== Autres lectures

Vous trouverez des informations plus détaillées sur les politiques contextuelles dansxref:../reference/spec/05-context-aware-policies.adoc[cette section] de la documentation de référence.
