include::partial$variables.adoc[]

= {project-name} vs OPA Gatekeeper
:revdate: 2026-03-18
:page-revdate: {revdate}
:page-aliases: explanations/opa-comparison.adoc
:description: Compare o OPA Gatekeeper e o gerenciamento de políticas do {project-name} para ambientes Kubernetes para determinar a melhor abordagem para seu caso de uso.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["explanations", "kubewarden-vs-opa_gatekeeper"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "opa gatekeeper", "comparison"]
:current-version: {page-origin-branch}

[IMPORTANT]
====

Esta página é de agosto de 2023. Ambos os projetos podem ter evoluído desde então.

Se você achar que algo está faltando ou é impreciso, por favor,https://github.com/kubewarden/docs/[registre um problema] ou abra um PR usando o link na parte inferior da página.

====

Tanto o OPA Gatekeeper quanto o Kubewarden, do qual o {project-name} é derivado, são projetos de código aberto e fazem parte do CNCF.

Esta tabela fornece uma comparação entre o OPA Gatekeeper e o site {short-project-name}. Os tópicos que exigem mais informações têm links para explicações adicionais.

|===
| Recurso | Gatekeeper da OPA | {short-project-name}

| Validação
| ✅
| ✅

| Mutação
| ✅
| ✅

| Linguagem da política <<_writing_policies,[1]>>
| Rego
| Rego, CEL, Go, Rust,...

| Consciente do contexto <<_context_aware,[2]>>
| ✅
| ✅

| Integração do Kubernetes <<_kubernetes_integration,[3]>>
| CRD em todo o cluster
| CRDs de cluster e namespaced

| Distribuição de políticas <<_policy_distribution,[4]>>
| incorporado ao Kubernetes CR
| Registro de contêineres ou incorporado ao Kubernetes CR (CEL)

| Integração de CI/CD <<_cicd_integration,[5]>>
| ✅
| ✅

| Modos de aplicação de políticas
| negar, avisar
| negar, avisar

| Modo de implantação <<_deployment_mode,[6]>>
| servidor de avaliação único
| vários servidores de avaliação

| Verificações de antecedentes <<_background_checks,[7]>>
| ✅
| ✅
|===

== Tipos de políticas

Tanto o OPA Gatekeeper quanto o Kubernetes podem escrever políticas de validação e mutação.

Essas políticas podem ter como alvo qualquer tipo de recurso do Kubernetes, incluindo recursos personalizados.

== Políticas de redação

Você escreve políticas do OPA Gatekeeper usando ohttps://www.openpolicyagent.org/docs/latest/#rego[site]. Rego é uma linguagem de consulta criada pelo projeto Open Policy Agent.

[IMPORTANT]
====

Você só pode usar o Rego para escrever políticas de validação. As políticas de mutação não usam o Rego, mas sim regras ad-hoc definidas em YAML (consultehttps://open-policy-agent.github.io/gatekeeper/website/docs/mutation[aqui]).

====


Você pode escrever políticas {short-project-name} usando diferentes paradigmas. Os autores de políticas podem usar linguagens de programação tradicionais (como Go, Rust e outras) ouhttps://en.wikipedia.org/wiki/Domain-specific_language[Domain Specific Languages], como Rego e CEL. Em {short-project-name}, você escreve políticas de validação e mutação da mesma forma.

[CAUTION]
====

O projeto de código aberto https://github.com/open-policy-agent/kube-mgmt[] kube-mgmt, parte do projeto Open Policy Agent, usa o Rego.

Apesar de usarem a mesma linguagem, as políticas escritas para o kube-mgmt não são compatíveis com o OPA Gatekeeper e vice-versa.

{short-project-name} pode usar políticas Rego escritas tanto para o Open Policy Agent quanto para o OPA Gatekeeper. Mais informações estão disponíveisxref:/tutorials/writing-policies/rego/01-intro-rego.adoc[aqui].

====


== Consciente do contexto

Às vezes, uma política precisa de dados sobre o estado atual do cluster para tomar uma decisão de validação ou mutação. Por exemplo, uma política que valida os recursos do Ingress pode precisar conhecer outros recursos do Ingress já definidos no cluster para garantir que não ocorram conflitos. {short-project-name} chama essas políticas de "sensíveis ao contexto".

Tanto o OPA Gatekeeper quanto o {short-project-name} são compatíveis com esses tipos de políticas.

Ao implantar o OPA Gatekeeper, um administrador do Kubernetes decide que tipo de dados do cluster deve ser disponibilizado para as políticas no momento da avaliação.

É importante destacar como esses dados podem ser acessados por todas as políticas implementadas.

Por exemplo, se uma política do Gatekeeper da OPA exigir acesso aos segredos do Kubernetes, todas as outras políticas implantadas também poderão ler esses dados.

Por outro lado, o site {short-project-name} fornece um acesso granular aos recursos do cluster.
Cada política tem acesso apenas aos recursos que o administrador do Kubernetes especifica. A tentativa de leitura de dados não autorizados é imediatamente bloqueada e informada aos administradores do cluster.

== Integração do Kubernetes

O OPA Gatekeeper tem um recurso personalizado em todo o cluster, que permite a definição de políticas e como e onde aplicá-las.

{short-project-name} tem dois tipos diferentes de recursos personalizados usados para declarar políticas. Um funciona no nível do cluster, o outro é namespaced. O nome do recurso personalizado namespaced é `+AdmissionPolicy+`.

As políticas implementadas por meio de um recurso `+AdmissionPolicy+` afetam apenas os recursos criados dentro do namespace ao qual pertencem. Por isso, você pode permitir que usuários não administradores do Kubernetes tenham os privilégios RBAC necessários para gerenciar os recursos do `+AdmissionPolicy+`, nos namespaces que eles podem acessar.

Isso permite que os administradores do Kubernetes deleguem o trabalho relacionado à política.

== Distribuição de políticas

As políticas OPA Gatekeeper e {short-project-name} têm código-fonte de política (Rego para OPA Gatekeeper, CEL para {short-project-name}) no recurso personalizado que define uma política no Kubernetes.

Além disso, as políticas do {short-project-name} podem ter o código-fonte da política gerenciado como imagens de contêiner (para Rego, Go, Rust, ...). Depois de criados, eles são enviados para os registros de contêineres como artefatos OCI.

Você pode assinar e verificar as políticas {short-project-name} usando ferramentas de imagem de contêiner como`+cosign+`, do https://sigstore.dev[projeto].

É possível distribuir políticas do {short-project-name} entre registros de contêineres distribuídos geograficamente usando as ferramentas e os processos tradicionais adotados para imagens de contêineres.

== Integração de CI/CD

Tanto o OPA Gatekeeper quanto o {short-project-name} são gerenciados usando metodologias GitOps.

No entanto, para o OPA Gatekeeper, há um acoplamento entre o código Rego da política e o recurso personalizado usado para implantá-lo no Kubernetes.
Isso introduz etapas extras nos pipelines de CI/CD.

A Rego tem o site https://www.openpolicyagent.org/docs/latest/policy-testing/[ferramentas de teste] que permite a criação de conjuntos de testes unitários. Escrever testes e executá-los em um pipeline de CI/CD é essencial para garantir que as políticas se comportem conforme o esperado.

Para usar essas ferramentas de teste, o código-fonte da política deve estar disponível em arquivos de texto dedicados. É impossível ler o código-fonte dos arquivos YAML usados para declarar a política do OPA Gatekeeper. O pipeline de CI/CD deve sincronizar o código-fonte do Rego para testar com o código definido no recurso personalizado do Gatekeeper da OPA. Você pode fazer isso usando ferramentas de terceiros.

{short-project-name} As políticas têm pipelines de CI/CD como os microsserviços tradicionais.
Normalmente, o código-fonte fica em um repositório do Git e, em seguida, usando os sistemas tradicionais de CI/CD, os testes de unidade são executados com base nele. Você escreve testes de unidade usando as estruturas de teste da linguagem usada para escrever a política. Quando todos os testes forem aprovados, compile a política no WebAssembly e envie-a para um registro de contêiner. Esse tipo de pipeline geralmente é mantido pelo autor da política.

Os administradores do Kubernetes normalmente mantêm outros pipelines de automação que reagem a novas versões da política (usando ferramentas de automação comohttps://docs.github.com/en/code-security/dependabot/working-with-dependabot[Dependabot],https://www.mend.io/renovate/[Renovate bot],https://www.updatecli.io/[updatecli] e outras) ou a alterações na configuração da política.

O pipeline testa a política em relação a diferentes tipos de solicitações. Você pode fazer o teste usando a ferramenta https://github.com/kubewarden/kwctl[`+kwctl+`] CLI, sem precisar de um cluster Kubernetes em execução. A ferramenta `+kwctl+` CLI usa o mesmo mecanismo de avaliação usado pela pilha {short-project-name} implantada em um cluster do Kubernetes.

== Modos de aplicação de políticas

Tanto o OPA Gatekeeper quanto o {short-project-name} podem implementar políticas usando dois modos de operação diferentes:

* `+deny+`violação de uma política rejeita a solicitação
* `+warn+`: a violação de uma política não causa rejeição e é registrada

== Modo de implantação

O mesmo servidor avalia todas as políticas do OPA Gatekeeper. Por outro lado, o site{short-project-name} permite a definição de vários servidores de avaliação. Você define esses servidores por meio de um recurso personalizado chamado `+PolicyServer+`.

Ao declarar uma política de {short-project-name}, o administrador do Kubernetes decide qual`+PolicyServer+` a hospeda.

[NOTE]
====

O objeto `+PolicyServer+` é uma abstração de alto nível introduzida por {short-project-name}.
Nos bastidores, é criado um `+Deployment+` com um tamanho de réplica específico.

Cada `+PolicyServer+` pode ter um tamanho de réplica diferente dos outros.

====

Isso permite cenários interessantes, como os seguintes:

* Implemente políticas críticas em um pool dedicado de servidores de políticas.
* Implemente as políticas de um locatário barulhento em um pool de servidores de políticas dedicado.

== Verificações de antecedentes

À medida que as políticas são adicionadas, removidas e reconfiguradas, os recursos que já estão no cluster podem ficar fora de conformidade.

Tanto o OPA Gatekeeper quanto o {short-project-name} têm um scanner que opera em segundo plano. Esse scanner avalia os recursos já definidos no cluster e sinaliza os que não estão em conformidade.

A única diferença entre o OPA Gatekeeper e o {short-project-name} é como os resultados do scanner são salvos.

O OPA Gatekeeper adiciona os detalhes da violação ao campo `+status+` de um determinado recurso personalizado`+Constraint+` (consultehttps://open-policy-agent.github.io/gatekeeper/website/docs/audit#constraint-status[aqui]).

{short-project-name} em vez disso, armazena os resultados dentro de um conjunto de recursos personalizados de relatórios definidos por https://openreports.io[openreports.io].
