= Guía de ejecución inicial
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

== Visión general

Esta página proporciona toda la información necesaria para instalar y ejecutar SUSE Observability.

== Instrucciones de instalación

[tabs]
====
Kubernetes::
+
--
Instale SUSE Observability en xref:/setup/install-stackstate/kubernetes_openshift/README.adoc[Kubernetes].
--

OpenShift::
+
--
Instale SUSE Observability en xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift].
--
====

== Dirección y puerto

[tabs]
====
Kubernetes::
+
--
Para acceder a la interfaz de usuario de SUSE Observability:

. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_access_the_suse_observability_ui[Activar un reenvío de puerto].
. Acceda a la interfaz de usuario de SUSE Observability en: https://localhost:8080
--

OpenShift::
+
--
Para acceder a la interfaz de usuario de SUSE Observability:

. xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_access_the_suse_observability_ui[Activar un reenvío de puerto].
. Acceda a la interfaz de usuario de SUSE Observability en: https://localhost:8080
--
====

== Nombre de usuario y contraseña por defecto

[tabs]
====
Kubernetes::
+
--
SUSE Observability está configurado por defecto con la siguiente cuenta de administrador:

* *nombre de usuario:* `+admin+`
* *contraseña:* Se ajusta durante la instalación. El script `+generate_values.sh+` lo recopila y almacena en formato hash MD5 en `+values.yaml+`
--

OpenShift::
+
--
SUSE Observability está configurado por defecto con la siguiente cuenta de administrador:

* *nombre de usuario:* `+admin+`
* *contraseña:* Se ajusta durante la instalación. El script `+generate_values.sh+` lo recopila y almacena en formato hash MD5 en `+values.yaml+`
--
====

== Solución de problemas

Si tiene algún problema durante la instalación de SUSE Observability o durante la primera ejecución, consulte la xref:/setup/install-stackstate/troubleshooting.adoc[guía de solución de problemas de instalación de SUSE Observability].

== Próximos pasos

Una vez que tenga SUSE Observability en funcionamiento, puede empezar a configurar las integraciones

* xref:/k8s-quick-start-guide.adoc[Instalar StackPacks para integrarlos con sistemas externos]
* xref:/use/views/k8s-views.adoc[Explore su clúster Kubernetes]
