ifdef::ss-ff-stackpacks2_enabled[]
= 公制绑定的模式和参考文献
:revdate: 2026-01-09
:page-revdate: {revdate}
:description: SUSE 可观察性

== 概述

本页介绍了`MetricBinding` 的模式，以及对构造、表达式语法和语义的详细解释。

== 公制绑定模式

每个公制绑定：

* 选择可应用的组件
* 定义用于检索数据的 PromQL 查询模板
* 指定结果数据的渲染方式
* 包括布局提示，用于选择用户界面中显示图表的适当位置

[,yaml]
----
_type: "MetricBinding"
name: string
chartType: "line"                     # "line" is the only type for now
unit?: string
scope: string                         # Topology scope - components to bind to
enabled: boolean                      # default: true
description?: string
valuation?: "higher-is-better" | "lower-is-better"
priority?: "HIGH" | "MEDIUM" | "LOW" | "NONE"    # deprecated
queries:
  - _type: "MetricBindingQuery"
    expression: string                # promql query
    alias: string                     # name in legend
    componentIdentifierTemplate?: string    # URN template for linking
    primary?: boolean                 # is this query the primary one
tags:
  <key>: <value>
layout?:                              # where should chart be shown
  metricPerspective?:                 # the metrics perspective for a component
    tab: string
    section: string
    weight?: integer
  componentHighlight?:                # highlight perspective of a component
    section: string
    weight?: integer
  componentSummary?:                  # summary - supporting panel on the right
    weight?: integer
identifier?: string
----

* `_type`：{stackstate-product-name} 需要知道这是一个度量绑定，因此，值始终需要是 `MetricBinding`
* `name`:度量绑定的名称
* `chartType`：{stackstate-product-name} 将支持不同的图表类型（`line` 、`bar` 等），目前只支持`line` 
* `unit`:查询返回的时间序列中数值的单位，用于渲染图表的 Y 轴。有关所有单位，请参阅xref:/develop/reference/k8sTs-chart-units.adoc[支持的]单位参考
* `scope`:度量绑定的拓扑范围，即拓扑查询，用于选择显示该度量绑定的组件
* `enabled`:设置为`false` 以保持度量绑定，但不向用户显示
* `description`:可选描述，显示在名称的上方
* `valuation`:数值越高或越低越 "好"
* `priority`:[已废弃]`HIGH`,`MEDIUM`, 或`LOW` 中的一个。组件指标的主要排序顺序（按此处提及的顺序），次要排序顺序是`name` 。
* `queries`:图表中要显示的度量绑定查询列表（请参阅xref:/setup/custom-integrations/metric-bindings/writing-promql.adoc[编写 PromQL 查询）]
** `expression`:（模板化的）promql 查询
** `alias`:图例中查询的名称
** `componentIdentifierTemplate`:相关组件标识符模板，由查询得出的时间序列标签填充
** `primary`:这个问题是主要问题吗？
* `tags`:将用于在用户界面中组织度量指标，可以使用 `{}`
* `layout`:如何在不同视角（如 "xref:/use/views/k8s-metrics-perspective.adoc[度量衡 "视角]）下分组图表
** `metricPerspective` - 定义要在`Metrics Perspective` 上显示的指标。指标按选项卡和章节分组。
*** `tab` - 选项卡名称。标签按字母顺序排序
*** `section` - 科室名称。章节按字母顺序排序
*** `weight` - 章节内的度量指标主要按权重（升序）排序，其次按名称（字母顺序）排序
** `componentHighlight` - 定义要在`Component Highlight` 上显示的指标。指标按章节分组。
*** `section` - 科室名称。章节按字母顺序排序
*** `weight` - 章节内的度量指标主要按权重（升序）排序，其次按名称（字母顺序）排序
** `componentSummary` - 指定在选择组件时在`Components details` 侧边栏中显示的指标。只有定义了该属性，图表才会出现。
*** `weight` - 这表示图表的重量。图表按权重升序排序，然后显示前三个图表。
* `identifier`:URN（通用资源标识符），用作度量绑定的唯一标识符。必须以`urn:stackpack:<stackpack-name>:metric-binding:` 开头，其余部分可自由格式化，只要在所有公制绑定中是唯一的即可。

endif::ss-ff-stackpacks2_enabled[]
