ifdef::ss-ff-stackpacks2_enabled[]
= Visão geral das integrações personalizadas
:revdate: 2026-01-06
:page-revdate: {revdate}
:description:  Visão geral das integrações personalizadas

[IMPORTANT]
====
As integrações personalizadas são um recurso em pré-produção e não lançado e, portanto, podem sofrer alterações significativas à medida que o recurso evolui. Ele não se destina ao uso em produção. Mas pode ser testado em ambientes que não sejam de produção.
====

== Visão geral

As integrações personalizadas aproveitam o Open Telemetry para coletar e enviar dados de telemetria (métricas, rastreamentos, registros) de várias fontes para {stackstate-product-name}. Ao usar o Open Telemetry, os usuários podem instrumentar seus aplicativos e serviços para obter insights sobre desempenho, confiabilidade e integridade operacional.
No site {stackstate-product-name}, o xref:setup/custom-integrations/otelmappings/README.adoc[Open Telemetry Mappings] processa os dados de telemetria recebidos, aplica as transformações necessárias e os mapeia para as entidades apropriadas em {stackstate-product-name}. xref:setup/custom-integrations/monitors/index.adoc[Monitores], xref:setup/custom-integrations/metric-bindings/index.adoc[associações de métricas] e xref:setup/custom-integrations/ui-presentation/README.adoc[apresentação da IU] podem ser definidos para apresentar a telemetria ingerida na IU, adicionar alertas e observabilidade. Tudo é embalado em uma xref:setup/custom-integrations/develop.adoc[mochila] para distribuição.

== Configuração do desenvolvimento

As integrações personalizadas devem ser desenvolvidas em uma implementação de pré-produção da plataforma {stackstate-product-name}. Para obter uma configuração de pré-produção e começar a desenvolver sua integração personalizada, há duas opções:

=== Instância SaaS (recomendada):
Para equipes internas da SUSE, recomendamos solicitar uma instância de SaaS à equipe {stackstate-product-name}. Essas instâncias têm as integrações personalizadas ativadas e são atualizadas automaticamente pelo menos a cada nova versão; em alguns casos, receberiam pré-lançamentos contendo correções de bugs importantes ou incrementos em recursos experimentais.
Entre em contato conosco por meio do canal dedicado (a ser anunciado).

=== Auto-hospedado:
Você pode ativar as integrações personalizadas em sua própria instalação auto-hospedada do {stackstate-product-name} definindo alguns sinalizadores de recursos ao instalar via helm:

    . Gerar o `+custom_integrations_values.yaml+`. Este guia pressupõe que você o salvou no diretório `+$VALUES_DIR+`

+
.$VALUES_DIR/custom_integrations_values.yaml
[,yaml]
----
global:
  features:
    experimentalStackpacks: true
----
+

    . Implemente o gráfico de leme {stackstate-product-name} com os valores gerados mais o `+.$VALUES_DIR/custom_integrations_values.yaml+`

+
.helm_deploy.sh
[,text]
----
helm upgrade --install \
    --namespace suse-observability \
    --create-namespace \
    --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
    --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
    --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
    --values $VALUES_DIR/custom_integrations_values.yaml \
    suse-observability \
    suse-observability/suse-observability
----
+

endif::ss-ff-stackpacks2_enabled[]
