= Configurar el almacenamiento
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

== Almacenamiento por defecto

SUSE Observability no especifica una clase de almacenamiento específica en sus PVC (persistent volume claims) por defecto, para proveedores de nube como EKS y AKS esto significa que se utilizará la clase de almacenamiento por defecto.

Los valores predeterminados para esas clases de almacenamiento suelen ser eliminar el PV (volumen persistente) cuando se elimina el PVC. Sin embargo, aunque se ejecute `+helm delete+` para eliminar una versión de stackstate, los PVC seguirán presentes en el espacio de nombres y se reutilizarán si se ejecuta `+helm install+` en el mismo espacio de nombres con el mismo nombre de versión.

Para eliminar los PVC, elimínelos manualmente con `+kubectl delete pvc+` o elimine todo el espacio de nombres.

[NOTE]
====
SUSE Observability requiere que el almacenamiento subyacente se base en memoria flash (SSD) o de rendimiento similar.
====
[NOTE]
====
Para entornos de producción, NFS no se recomienda ni se admite para la provisión de almacenamiento en SUSE Observability debido al riesgo potencial de corrupción de datos.
====
[NOTE]
====
En caso de duda, es posible ejecutar el xref:/setup/install-stackstate/support-package-performance.adoc[script de rendimiento] y compararlo con el xref:/setup/install-stackstate/support-package-performance.adoc#_reference_performance[rendimiento de referencia].
====

== Personalizar el almacenamiento

Puede personalizar los ajustes de `+storageClass+` y `+size+` para distintos volúmenes en el gráfico de Helm. Estos archivos de valores de ejemplo muestran cómo cambiar la clase de almacenamiento o el tamaño del volumen. Pueden fusionarse para cambiar ambos al mismo tiempo.
En el caso de `+size+`, proporcionamos la muestra tanto para `+HA+` como para `+NonHa+` en función del perfil de dimensionamiento elegido durante el proceso de instalación.

[tabs]
====
Cambio de clase de almacenamiento::
+
--

[,yaml]
----
global:
  # The storage class for all of the persistent volumes
  storageClass: "standard"
----

--

Cambio del tamaño del volumen para HA::
+
--

[,yaml]
----
clickhouse:
  persistence:
    # Size of persistent volume for each clickhouse pod
    size: 50Gi
elasticsearch:
  volumeClaimTemplate:
    resources:
      requests:
        # size of volume for each Elasticsearch pod
        storage: 250Gi

hbase:
  hdfs:
    datanode:
      persistence:
        # size of volume for HDFS data nodes
        size: 250Gi

    namenode:
      persistence:
        # size of volume for HDFS name nodes
        size: 20Gi


kafka:
  persistence:
    # size of persistent volume for each Kafka pod
    size: 100Gi


zookeeper:
  persistence:
    # size of persistent volume for each Zookeeper pod
    size: 8Gi

victoria-metrics-0:
  server:
    persistentVolume:
      size: 250Gi
victoria-metrics-1:
  server:
    persistentVolume:
      size: 250Gi

stackstate:
  components:
    checks:
      tmpToPVC:
        volumeSize: 2Gi
    healthSync:
      tmpToPVC:
        volumeSize: 2Gi
    state:
      tmpToPVC:
        volumeSize: 2Gi
    sync:
      tmpToPVC:
        volumeSize: 2Gi
    vmagent:
      persistence:
        size: 10Gi
  features:
    storeTransactionLogsToPVC:
      volumeSize: 600Mi
  stackpacks:
    pvc:
      size: 1Gi

backup:
  configuration:
    scheduled:
      pvc:
        size: 1Gi
minio:
  persistence:
    size: 500Gi
----

--
Cambio del tamaño del volumen No-Ha::
+
--

[,yaml]
----
clickhouse:
  persistence:
    # Size of persistent volume for each clickhouse pod
    size: 50Gi

elasticsearch:
  volumeClaimTemplate:
    resources:
      requests:
        # size of volume for each Elasticsearch pod
        storage: 250Gi

hbase:
  stackgraph:
    persistence:
      # Size of persistent volume for the single stackgraph hbase pod
      size: 100Gi

kafka:
  persistence:
    # size of persistent volume for each Kafka pod
    size: 100Gi


zookeeper:
  persistence:
    # size of persistent volume for each Zookeeper pod
    size: 8Gi

victoria-metrics-0:
  server:
    persistentVolume:
      size: 50Gi

stackstate:
  components:
    checks:
      tmpToPVC:
        volumeSize: 2Gi
    healthSync:
      tmpToPVC:
        volumeSize: 2Gi
    state:
      tmpToPVC:
        volumeSize: 2Gi
    sync:
      tmpToPVC:
        volumeSize: 2Gi
    vmagent:
      persistence:
        size: 10Gi
  features:
    storeTransactionLogsToPVC:
      volumeSize: 600Mi
  stackpacks:
    localpvc:
      size: 1Gi
    pvc:
      size: 1Gi

backup:
  configuration:
    scheduled:
      pvc:
        size: 1Gi
minio:
  persistence:
    size: 500Gi
----

--
====

[NOTE]
====
El ejemplo de NonHa pertenece a la mayor instancia de NonHa destinada a observar 100 nodos y retener datos durante 2 semanas.
====
