= Installation
:revdate: 2025-09-08
:page-revdate: {revdate}

== Vue d'ensemble

{elemental-product-name} stack assure la gestion du système d'exploitation à l'aide de conteneurs OCI et de Kubernetes. L'installation de la pile {elemental-product-name}comprend l'installation de {elemental_operator_name} dans le cluster de gestion et la création et l'utilisation de supports d'installation pour fournir le système d'exploitation aux nœuds du cluster. Voir la section xref:rancher-os-management/architecture/architecture.adoc[Architecture] pour en savoir plus sur l'interaction des composants.

La configuration d'installation est généralement appliquée et définie dans le cadre du processus d'enregistrement.
Le processus d'enregistrement est effectué par `elemental-register` (la partie client de {elemental_operator_name} ) qui est responsable de l'enregistrement des nœuds dans un cluster de gestion Rancher et de la récupération de la configuration d'installation.

Veuillez consulter le guide de xref:quickstarts/quickstart-cli.adoc[démarrage rapide] pour obtenir des instructions de déploiement simples, étape par étape.

== {elemental-product-name} Installation de l'opérateur

Le site {elemental_operator_name} est chargé de gérer les versions de {elemental-product-name} et de maintenir un inventaire des machines afin de faciliter les installations en périphérie ou à nu. {elemental_operator_name}nécessite un cluster comprenant le Rancher Manager et peut être installé avec un diagramme helm.

Voir {elemental_operator_name} xref:references/operatorchart-reference.adoc[helm chart reference] pour les détails d'installation, de désinstallation, de mise à niveau et de configuration.

== Préparer les ressources Kubernetes

Une fois que le site {elemental_operator_name} est opérationnel au sein du cluster de gestion, quelques ressources Kubernetes sont nécessaires pour préparer le déploiement d'un cluster basé sur le site {elemental-product-name}.

* xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate]:
Cette ressource identifie les critères pour faire correspondre les boîtes enregistrées (listées dans l'inventaire des machines) avec les clusters Rancher 2.6 disponibles. Dès qu'il y a une correspondance, le cluster kubernetes sélectionné devient propriétaire de la boîte enregistrée.
* xref:references/machineregistration-reference.adoc[MachineRegistration]:
Cette ressource définit les détails du déploiement du système d'exploitation pour toute machine tentant de s'enregistrer. L'enregistrement de la machine est l'entrée pour les nœuds {elemental-product-name} car il gère l'authentification (basée sur TPM), le déploiement du système d'exploitation et l'inclusion du nœud dans l'inventaire des machines afin qu'il puisse être ajouté à un cluster lorsqu'il y a une correspondance basée sur un MachineInventorySelectorTemplate. L'objet MachineRegistration comprend l'URL d'enregistrement de la machine que les nœuds utilisent pour s'enregistrer.

Une ressource Rancher Cluster est également nécessaire pour déployer {elemental-product-name}, elle peut être créée manuellement comme illustré dans le guide de xref:quickstarts/quickstart-cli.adoc[démarrage rapide] ou créée à partir de l'interface utilisateur de Rancher 2.6.

== Préparation du support d'installation

Le support d'installation est le support qui sera utilisé pour démarrer le déploiement d'un système d'exploitation. Actuellement, le support pris en charge est un ISO vivant. L'ISO live doit inclure le yaml de configuration de l'enregistrement et doit donc être créé une fois que le MachineRegistration est créé. Le support d'installation est généré par la création de ressources xref:references/seedimage-reference.adoc[Seed Image](voir xref:quickstarts/quickstart-cli.adoc#_preparing_the_installation_seed_image[démarrage rapide] et xref:operator-operational-tasks/custom-images.adoc#_create_a_custom_bootable_installation_iso[images personnalisées]).

L'ISO en direct prend en charge l'amorçage PXE pour une intégration directe avec https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/autoinst-distributions.html#based-on-iso-image[Manager.] SUSE

Dans MachineRegistration, seul un sous-ensemble de paramètres d'installation du système d'exploitation peut être configuré. Tous les paramètres disponibles sont répertoriés sur la page de référence de xref:references/machineregistration-reference.adoc[MachineRegistration].

Afin de configurer l'installation au-delà des options communes fournies dans la sectionxref:references/machineregistration-reference.adoc#_config_elemental_install[`elemental.install`] un fichier de configuration `config.yaml`peut être inclus dans l'ISO (voir xref:installation/customize-installation/custom-install.adoc#_custom_suse_rancher_prime_os_manager_client_configuration_file[Images personnalisées]).
Notez que toute configuration appliquée dans le cadre de la section `elemental.install` de l'enregistrement de la machine sera appliquée en plus des paramètres inclus dans tout fichier personnalisé `config.yaml`.

Cependant, si pour une raison quelconque des actions ou des scripts de démarrage sont nécessaires, il est possible d'inclure les plans de Rancher System Agent dans le média d'installation. Voir la section xref:rancher-os-management/plans.adoc[Plans] pour plus de détails et quelques exemples de plans. Les plans pourraient être inclus dans le dossier "squashed rootfs at `/var/lib/elemental/agent/plans`" et ils seraient vus par l'agent du système au premier démarrage.

== Démarrer le processus d'installation

L'installation commence par le démarrage du média d'installation sur un nœud. Une fois le support d'installation démarré, il tentera de contacter le cluster de gestion et de s'y enregistrer en appelant la commande `elemental-register`.
Comme la configuration yaml d'enregistrement est déjà incluse dans l'ISO, `elemental-register` connaît l'URL d'enregistrement et toutes les autres données requises pour l'enregistrement.

Si l'enregistrement est réussi, le support d'installation démarre l'installation sur l'hôte en fonction de la configuration déjà incluse dans le support et des paramètres MachineRegistration. Dès que l'installation est terminée, le nœud est prêt à redémarrer. Le système d'exploitation déployé comprend un plan d'agent système pour lancer un processus de provisionnement rancher régulier afin d'installer la version kubernetes sélectionnée. Une fois démarré, après quelques minutes, l'installation du nœud est finalisée et le nœud est inclus dans le cluster et visible à travers l'interface utilisateur de Rancher.

== Table de partition déployée

Une fois le système d'exploitation installé, la table de partition du système d'exploitation, selon les valeurs par défaut, se présente comme suit

|===
| Étiquette | Taille par défaut | Contient

| COS_GRUB
| 64 MiB
| Partition de démarrage UEFI

| COS_STATE
| 8 GiB
| Images de systèmes de fichiers amorçables A/B construites à partir d'images OCI

| COS_OEM
| 64 MiB
| Fichiers de configuration du nuage OEM et autres données

| COS_RECOVERY
| 4 GiB
| Image du système de fichiers de récupération si COS_STATE est détruit

| COS_PERSISTENT
| Espace restant
| Tous les contenus des dossiers persistants
|===

Il s'agit de la structure de base de tout système d'exploitation conçu par {elemental_toolkit_url}[{elemental_toolkit_name}].

== {elemental-product-name} Racine immuable

L'une des caractéristiques des systèmes d'exploitation {elemental-product-name} est la mise en place d'un système de fichiers racine immuable sur lequel sont appliqués des emplacements éphémères ou persistants. La structure des dossiers par défaut est présentée dans la matrice ci-dessous.

[cols=",^,^,^"]
|===
| Chemin d'accès | En lecture seule | Ephémère | Persistant

| /
| x
|
|

| /etc
|
| x
|

| /etc/cni
|
|
| x

| /etc/iscsi
|
|
| x

| /etc/rancher
|
|
| x

| /etc/ssh
|
|
| x

| /etc/systemd
|
|
| x

| /srv
|
| x
|

| /home
|
|
| x

| /opt
|
|
| x

| /root
|
|
| x

| /var
|
| x
|

| /usr/libexec
|
|
| x

| /var/lib/cni
|
|
| x

| /var/lib/kubelet
|
|
| x

| /var/lib/rancher
|
|
| x

| /var/lib/elemental
|
|
| x

| /var/lib/NetworkManager
|
|
| x

| /var/lib/calico
|
|
| x

| /var/log
|
|
| x
|===
