= Comment construire des images de disque brutes pour Raspberry Pi
:revdate: 2024-09-24
:page-revdate: {revdate}

Ce guide montre comment construire une image disque brute qui peut être écrite sur une carte SD et démarrée sans aucun autre support d'installation.

[CAUTION]
====
Toutes les données contenues dans la carte SD seront effacées. N'utilisez qu'une carte SD ne contenant rien d'important.

La carte SD doit être d'une taille raisonnable (32 Go ou plus) et *rapide* ( !!).
====

.Ressource SeedImage
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-img
  namespace: fleet-default
spec:
  type: raw
  baseImage: registry.opensuse.org/isv/rancher/elemental/staging/containers/suse/sl-micro/6.0/baremetal-os-container:latest
  targetPlatform: linux/arm64
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: fire-nodes
    namespace: fleet-default
----

Vérifier les logs du pod de construction utilisé :

[,shell]
----
kubectl logs -n fleet-default fire-img -f -c build
----

Lorsque la construction est terminée, nous pouvons télécharger le fichier image à l'aide de wget :

[,shell]
----
wget --no-check-certificate $(kubectl get seedimage -n fleet-default fire-img -o jsonpath="{.status.downloadURL}") -O sle-micro.arm64.raw
----

Nous pouvons maintenant écrire l'image `.raw` sur la carte SD. Cela peut être fait avec `dd` sur la ligne de commande Linux si vous êtes à l'aise avec cette commande.https://www.opensuse.org[openSUSE] a de bonnes instructions sur la façon d'écrire une image sur un support de stockage pour https://en.opensuse.org/SDB:Live_USB_stick[Linux],https://en.opensuse.org/SDB:Create_a_Live_USB_stick_using_Windows[Windows], et https://en.opensuse.org/SDB:Create_a_Live_USB_stick_using_macOS[OS X.]

== Démarrage de la machine

L'image disque brute ne comprendra que la partition EFI, la partition OEM et la partition de récupération. Au premier démarrage, le système démarre dans le système de récupération afin d'étendre et d'ajouter les partitions manquantes. Après l'expansion, il s'enregistrera avec rancher et redémarrera.

Si une erreur se produit pendant la phase d'enregistrement, le journal peut être retrouvé en utilisant`journalctl -u elemental-register-reset`.
