= Instalar proveedores certificados
:revdate: 2026-02-17
:page-revdate: {revdate}

Esta sección describe cómo instalar la tabla {product_name} Providers, que instala los xref:overview/certified.adoc[proveedores certificados].

== Requisitos previos

* Asegúrese de que se ha instalado {product_name}.

== Instale el cuadro de proveedores {product_name} 

Para instalar todos los proveedores certificados, ejecute el siguiente comando:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.bootstrapKubeadm.enabled=true \
    --set providers.controlplaneKubeadm.enabled=true \
    --set providers.infrastructureDocker.enabled=true \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAzure.enabled=true \
    --set providers.infrastructureGCP.enabled=true \
    --set providers.infrastructureGCP.variables.GCP_B64ENCODED_CREDENTIALS="" \
    --set providers.infrastructureVSphere.enabled=true \
    --set providers.bootstrapRKE2.enabled=true \
    --set providers.controlplaneRKE2.enabled=true \
    --set providers.addonFleet.enabled=true \
    --wait
----

El comando anterior se utiliza para instalar todos los proveedores certificados. Puede personalizar los proveedores que se instalan estableciendo los indicadores correspondientes en true. Tenga en cuenta que los proveedores CAPRKE2 y Fleet Addon están activados por defecto y se instalarán a menos que se desactiven explícitamente.

Por ejemplo, para poder aprovisionar clústeres RKE2 en AWS, basta con instalar el proveedor de AWS como se indica a continuación:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAWS.variables.AWS_B64ENCODED_CREDENTIALS=${AWS_B64ENCODED_CREDENTIALS} \
    --wait
----

Para poder aprovisionar clústeres RKE2 en Azure, basta con instalar el proveedor de Azure como se indica a continuación:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAzure.enabled=true \
    --wait
----