= Upgrades manuais
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-30
:page-revdate: {revdate}

Você pode atualizar o K3s usando o script de instalação ou instalando manualmente o binário da versão desejada.

[NOTE]
====
Ao fazer o upgrade, atualize primeiro os nós do servidor, um de cada vez, e depois os nós do agente.
====

[#_release_channels]
== Canais de liberação

Os upgrades realizados por meio do script de instalação ou usando nosso recurso de xref:upgrades/automated.adoc[upgrades automatizados] podem ser vinculados a diferentes canais de lançamento. Os seguintes canais estão disponíveis:

|===
| Canal | Descrição

| estável
| (Padrão) Stable é recomendado para ambientes de produção. Essas versões passaram por um período de testes da comunidade.

| mais recente
| O Latest sempre aponta para a versão de não liberação mais alta disponível, conforme determinado pelas regras de ordenação do semver. Essas versões ainda não passaram por um período de testes da comunidade.

| v1.33 (exemplo)
| Há um canal de lançamento vinculado a cada versão secundária do Kubernetes, incluindo versões que estão no fim da vida útil. Esses canais selecionam a versão mais recente disponível para essa versão secundária, não necessariamente uma versão estável.
|===

Para obter uma lista exaustiva e atualizada de canais, acesse a https://update.k3s.io/v1-release/channels[API do serviço de canais] k3s. Para obter mais detalhes técnicos sobre como os canais funcionam, consulte o https://github.com/rancher/channelserver[projeto].

[TIP]
====
Ao tentar atualizar para uma nova versão do K3s, aplica-se a https://kubernetes.io/docs/setup/release/version-skew-policy/[política de distorção de versão do]. Certifique-se de que seu plano não ignore versões secundárias intermediárias ao fazer o upgrade. O controlador de atualização do sistema em si não protegerá contra alterações não compatíveis com a versão do Kubernetes.
====


== Faça upgrade do K3s usando o script de instalação

Para atualizar o K3s a partir de uma versão mais antiga, você pode executar novamente o script de instalação usando as mesmas opções de configuração que usou originalmente ao executar o script de instalação.

[IMPORTANT]
.Observação
====
A variável `+INSTALL_K3S_EXEC+`, as variáveis `+K3S_+` e os argumentos finais do shell são usados pelo script de instalação para gerar a unidade do systemd e o arquivo de ambiente.
Se você definir a configuração ao executar originalmente o script de instalação, mas não a definir novamente ao reexecutar o script de instalação, os valores originais serão perdidos.

O conteúdo do xref:installation/configuration.adoc#_configuration_file[arquivo de configuração] não é gerenciado pelo script de instalação.
Se quiser que sua configuração seja independente do script de instalação, use um arquivo de configuração em vez de passar variáveis de ambiente ou argumentos para o script de instalação.
====


A execução do script de instalação fará isso:

. Faça o download do novo binário do k3s
. Atualize a unidade do systemd ou o script de inicialização do openrc para refletir os argumentos passados para o script de instalação
. Reinicie o serviço k3s

[NOTE]
====
Os contêineres para pods continuam em execução mesmo quando o K3s é interrompido. O script de instalação não drena ou monitora o nó antes de reiniciar o K3s. Se a sua carga de trabalho for sensível a breves interrupções do servidor de API, você deve manualmente o nó https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drenar e isolar] usando `+kubectl+` antes de executar novamente o script de instalação para atualizar o K3s ou modificar a configuração e, depois, desbloqueá-lo.
====

Por exemplo, para atualizar para a versão estável atual:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

Se quiser atualizar para uma versão mais recente em um canal específico (como o mais recente), você poderá especificar o canal:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL=latest <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

Se quiser fazer upgrade para uma versão específica, você pode executar o seguinte comando:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Z+k3s1 <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

[TIP]
====
Se quiser fazer o download da nova versão do k3s, mas não iniciá-lo, você pode usar a variável de ambiente `+INSTALL_K3S_SKIP_START=true+`.
====


== Atualizar o K3s usando o binário

Para atualizar o K3s manualmente, você pode fazer o download da versão desejada do binário do K3s e substituir o binário existente pelo novo.

. Faça o download da versão desejada do binário do K3s em https://github.com/k3s-io/k3s/releases[releases]
. Copie o binário baixado para `+/usr/local/bin/k3s+` (ou para o local desejado)
. Reinicie o serviço k3s ou k3s-agent ou reinicie o processo k3s (binário)

[NOTE]
====
Os contêineres para pods continuam em execução mesmo quando o K3s é interrompido. Em geral, é seguro reiniciar os K3s sem drenar os pods e isolar o nó. Se a sua carga de trabalho for sensível a breves interrupções do servidor de API, você deverá manualmente o nó https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drenar e isolar] usando `+kubectl+` antes de reiniciar o K3s e, em seguida, desbloqueá-lo.
====
