= Actualizaciones manuales
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-30
:page-revdate: {revdate}

Puede actualizar K3s utilizando el script de instalación, o instalando manualmente el binario de la versión deseada.

[NOTE]
====
Cuando actualice, actualice primero los nodos servidor de uno en uno y después los nodos agente.
====

[#_release_channels]
== Canales de liberación

Las actualizaciones realizadas mediante el script de instalación o utilizando nuestra función xref:upgrades/automated.adoc[de actualizaciones automáticas] pueden vincularse a diferentes canales de publicación. Están disponibles los siguientes canales:

|===
| Canal | Descripción

| estable
| (Predeterminado) Estable se recomienda para entornos de producción. Estas versiones se han sometido a un periodo de pruebas por parte de la comunidad.

| última
| Latest siempre apunta a la versión más alta disponible no liberada, según determinan las reglas de ordenación de semver. Estas versiones aún no han sido sometidas a un periodo de pruebas por parte de la comunidad.

| v1.33 (ejemplo)
| Existe un canal de lanzamiento vinculado a cada versión menor de Kubernetes, incluidas las versiones que han llegado al final de su ciclo de vida. Estos canales seleccionan la última versión disponible para esa versión menor, no necesariamente una versión estable.
|===

Para obtener una lista exhaustiva y actualizada de los canales, puede visitar la https://update.k3s.io/v1-release/channels[API del servicio de canales] k3s. Para más detalles técnicos sobre el funcionamiento de los canales, consulte el https://github.com/rancher/channelserver[proyecto].

[TIP]
====
Al intentar actualizar a una nueva versión de K3s, se aplica la Kubernetes https://kubernetes.io/docs/setup/release/version-skew-policy/[política de desviación de versión de]. Asegúrese de que su plan no se salta versiones menores intermedias al actualizar. El propio system-upgrade-controller no protegerá contra cambios no soportados en la versión de Kubernetes.
====


== Actualización del K3s mediante el script de instalación

Para actualizar K3s desde una versión anterior puede volver a ejecutar el script de instalación utilizando las mismas opciones de configuración que utilizó originalmente al ejecutar el script de instalación.

[IMPORTANT]
.Nota
====
La variable `INSTALL_K3S_EXEC`, las variables `K3S_` y los argumentos de shell finales son utilizados por el script de instalación para generar la unidad systemd y el archivo de entorno.
Si establece la configuración al ejecutar originalmente el script de instalación, pero no la establece de nuevo al volver a ejecutar el script de instalación, se perderán los valores originales.

El contenido del xref:installation/configuration.adoc#_configuration_file[archivo de configuración] no es gestionado por el script de instalación.
Si desea que su configuración sea independiente del script de instalación, debe utilizar un archivo de configuración en lugar de pasar variables de entorno o argumentos al script de instalación.
====


Ejecutando el script de instalación:

. Descargar el nuevo binario k3s
. Actualice la unidad systemd o el script de inicio openrc para reflejar los argumentos pasados al script de instalación.
. Reinicie el servicio k3s

[NOTE]
====
Los contenedores para Pods continúan ejecutándose incluso cuando se detiene K3s. El script de instalación no drena ni acordona el nodo antes de reiniciar K3s. Si su carga de trabajo es sensible a breves caídas del servidor API, debería manualmente https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drenar] el nodo utilizando `kubectl` antes de volver a ejecutar el script de instalación para actualizar K3s o modificar la configuración, y acordonarlo después.
====

Por ejemplo, para actualizar a la versión estable actual:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

Si desea actualizar a una versión más reciente en un canal específico (como el más reciente), puede especificar el canal:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL=latest <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

Si desea actualizar a una versión específica puede ejecutar el siguiente comando:

[,sh]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION=vX.Y.Z+k3s1 <EXISTING_K3S_ENV> sh -s - <EXISTING_K3S_ARGS>
----

[TIP]
====
Si desea descargar la nueva versión de k3s, pero no iniciarla, puede utilizar la variable de entorno `INSTALL_K3S_SKIP_START=true`.
====


== Actualizar K3s utilizando el binario

Para actualizar K3s manualmente, puede descargar la versión deseada del binario de K3s y sustituir el binario existente por el nuevo.

. Descargue la versión deseada del binario K3s desde https://github.com/k3s-io/k3s/releases[releases]
. Copie el archivo binario descargado en `/usr/local/bin/k3s` (o en la ubicación que desee).
. Reinicie el servicio k3s o k3s-agent o reinicie el proceso k3s (binario)

[NOTE]
====
Los contenedores para Pods continúan ejecutándose incluso cuando se detiene K3s. Por lo general, es seguro reiniciar los K3 sin vaciar las vainas y acordonar el nodo. Si su carga de trabajo es sensible a breves caídas del servidor API, debería manualmente https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drenar] el nodo usando `kubectl` antes de reiniciar K3s, y acordonarlo después.
====
