= オープンIDコネクト（OIDC）
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability セルフホスト

== 概要

SUSE Observabilityは、OIDC認証プロバイダを使用して認証できます。これを有効にするには、SUSE ObservabilityとOIDCプロバイダの両方が互いに通信できるように設定する必要があります。以下のセクションでは、それぞれのセットアップについて説明する。

== OIDCプロバイダーの設定

OIDCを使用して認証するようにSUSE Observabilityを設定する前に、OIDCプロバイダにSUSE Observability用のクライアントを作成する必要があります。

=== 牧場主

[NOTE]
Rancher 2.12以降でのみ動作します。 https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/users/authn-and-authz/configure-oidc-provider.html[RancherをOIDCプロバイダとして設定する]必要がある。

RancherローカルクラスタにOIDCClientリソースを作成します：
[,yaml]
----
apiVersion: management.cattle.io/v3
kind: OIDCClient
metadata:
  name: oidc-observability
spec:
  tokenExpirationSeconds: 600
  refreshTokenExpirationSeconds: 3600
  redirectURIs:
    - "https://<observability-base-url>/loginCallback?client_name=StsOidcClient"
----

Rancher はそのステータスフィールドでクライアント ID とシークレットを利用できるようにします：
[,yaml]
----
apiVersion: management.cattle.io/v3
kind: OIDCClient
metadata:
  name: oidc-observability
spec:
  tokenExpirationSeconds: 600
  refreshTokenExpirationSeconds: 3600
  redirectURIs:
    - "https://<observability-base-url>/loginCallback?client_name=StsOidcClient"
status:
  clientID: <oidc-client-id>
  clientSecrets:
    client-secret-1:
      createdAt: "xxx"
      lastFiveCharacters: xxx
----

で秘密の値を得ることができる。
[,bash]
----
kubectl get secret <oidc-client-id> -n cattle-oidc-client-secrets -o jsonpath="{.data.client-secret-1}" | base64 -d
----


=== その他のOIDCプロバイダー

OIDCプロバイダーが必要であれば）クライアントには以下の設定を使用する：

* OIDC認可フローを使用する。これはしばしば認可コードフローとも呼ばれる。SUSE Observabilityは暗黙的グラントとハイブリッドフローをサポートしていないため、これらのサポートを有効にする必要はありません。
* *リダイレクトURIに*、SUSE ObservabilityのベースURLに`+/loginCallback?client_name=StsOidcClient+` を付けたものを設定します。例えば`+https://stackstate.acme.com/loginCallback?client_name=StsOidcClient+` 。Google や Azure Entra ID など、一部の OIDC プロバイダでは、クエリパラメータを含め、リダイレクト URI が正確に一致する必要があります。その場合は、次のようにURIを設定する必要がある`+https://stackstate.acme.com/loginCallback?client_name=StsOidcClient+` 。
* SUSE Observabilityに、少なくともOIDCプロバイダのスコープ`+openid+` 、`+email+` 、またはこれらに相当するものへのアクセス権を与えます。プロバイダーによっては、より多くのスコープが必要な場合もある。もし、別の`+profile+` が存在する場合は、それも含めること。
* SUSE ObservabilityにはOIDCオフラインアクセスが必要です。一部の ID プロバイダでは、これには通常`+offline_access+` と呼ばれる追加スコープが必要である。

この設定の結果、*clientIdと* *secretが*生成されるはずである。これらをコピーして、SUSE Observabilityを設定するために保管しておいてください。また、プロバイダーの*DiscoveryUriも書き留めて*おくこと。通常は同じ画面に表示されるか、ドキュメントに記載されています。

== OIDC用のSUSE Observabilityの設定

=== 牧場主

[NOTE]
Rancher 2.12以降でのみ動作します。 https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/users/authn-and-authz/configure-oidc-provider.html[RancherをOIDCプロバイダとして設定する]必要がある。

SUSE ObservabilityのOIDCプロバイダとしてRancherを設定するには、認証値にOIDCの詳細を追加する必要があります：
[,yaml]
----
stackstate:
  authentication:
    rancher:
      clientId: "<oidc-client-id>"
      secret: "<oidc-secret>"
      baseUrl: "<rancher-url>"
----
Rancher 用の OIDC 設定は、以下のフィールドをオーバーライドして拡張することができます：

* **discoveryUri**- OIDCプロバイダを発見するために使用できるURI。通常、OIDCプロバイダでクライアントを作成する際にも文書化されるか、返される。
* **redirectUri**- オプション（例にはない）：SUSE Observabilityのログインコールバックエンドポイントに到達可能なURI。デフォルトでは`+stackstate.baseUrl+` を使って入力されるが、オーバーライドすることもできる。これは、`+/loginCallback+` のパスを指す完全修飾URLでなければならない。
* **customParameters**- OIDCプロバイダにカスタムリクエストパラメータとして送るキーと値のペアのマップ（オプション）。特定のOIDCプロバイダーは、デフォルトでは送信されない追加のリクエストパラメーターを要求します。

検証可能なSSL証明書を使用していないセットアップのためにTLS検証を無効にする必要がある場合は、アプリケーション設定でSSLチェックを無効にできます（本番環境では使用しないでください）：

**非HA**セットアップの場合：
[,yaml]
----
stackstate:
  components:
    server:
      extraEnv:
        open:
          CONFIG_FORCE_stackstate_misc_sslCertificateChecking: false
----
**HA（高可用性）**セットアップ用：
[,yaml]
----
stackstate:
  components:
    api:
      extraEnv:
        open:
          CONFIG_FORCE_stackstate_misc_sslCertificateChecking: false
----

HAデプロイメントでは、apiコンポーネントは異なるコンフィギュレーションを処理する。以下を使用する：=== Kubernetes

KubernetesでOIDC認証プロバイダを使用するようにSUSE Observabilityを設定するには、ファイル`+authentication.yaml+` にOIDCの詳細とユーザーロールマッピングを追加する必要があります。例えば、こうだ：

[,yaml]
----
stackstate:
  authentication:
    oidc:
      clientId: "<client-id-from-oidc-provider>"
      secret: "<secret-from-oidc-provider>"
      discoveryUri: "https://oidc.acme.com/.well-known/openid-configuration"
      jwsAlgorithm: RS256
      scope: ["openid", "email"]
      jwtClaims:
        usernameField: email
        displayNameField: name
        groupsField: groups
      customParameters:
        access_type: offline

    # map the groups from OIDC provider
    # to the 4 standard roles in SUSE Observability (guest, powerUser, k8sTroubleshooter and admin)
    roles:
      guest: ["guest-group-in-oidc-provider"]
      powerUser: ["powerUser-group-in-oidc-provider"]
      admin: ["admin-group-in-oidc-provider"]
      k8sTroubleshooter: ["troubleshooter-group-in-oidc-provider"]
----

以下の手順に従って、OIDCを使用して認証するようにSUSE Observabilityを設定します：

. `+authentication.yaml+` - OIDC認証プロバイダーの詳細を追加する（上記の例を参照）：
 ** *clientId*-xref:/setup/security/authentication/oidc.adoc#_configure_the_oidc_provider[SUSE Observability用に作成したOIDCクライアントの]ID。
 ** *secret*-xref:/setup/security/authentication/oidc.adoc#_configure_the_oidc_provider[SUSE Observability用に作成したOIDCクライアントの]秘密です。
 ** *discoveryUri*- OIDCプロバイダを発見するために使用できるURI。通常、OIDCプロバイダでクライアントを作成する際にも文書化されるか、または返される。
 ** *jwsAlgorithm*- OIDC のデフォルトは`+RS256+` です。OIDCプロバイダーが別のものを使用している場合は、ここで設定できます。
 ** *scope*- OIDC プロバイダ構成で提供されるスコープと一致するか、そのサブセットでなければならない。SUSE Observabilityはこれを使用して、OIDCプロバイダのユーザプロファイルのこれらの部分へのアクセスを要求します。
 ** *redirectUri*- オプション（例にはない）：SUSE Observabilityのログインコールバックエンドポイントに到達可能なURI。デフォルトでは`+stackstate.baseUrl+` を使って入力されるが、オーバーライドすることもできる。これは、`+/loginCallback+` のパスを指す完全修飾URLでなければならない。
 ** *customParameters*- OIDCプロバイダにカスタムリクエストパラメータとして送られるキーと値のペアのマップ（オプション）。一部のOIDCプロバイダーは、デフォルトでは送信されない追加のリクエストパラメーターを要求します。
 ** *jwtClaims* -
  *** *usernameField*- OIDCユーザープロファイルの中で、ユーザー名として使用するフィールド。デフォルトでは、これは`+preferred_username+` となるが、多くのプロバイダーはこのフィールドを省略している。良い代替案は`+email+` 。
  *** *displayNameField*- 表示名として使用されるOIDCユーザープロファイルのフィールド。デフォルトでは、`+name+` 。
  *** *groupsField*- SUSE Observabilityがユーザのロール/グループを読み取るフィールド。
. `+authentication.yaml+` -`+roles.guest+`,`+roles.powerUser+`,`+roles.admin+` または`+roles.platformAdmin+` 設定を使用して、OIDCから正しいSUSE Observabilityサブジェクトにユーザロールをマッピングします（上記の例を参照してください）。詳細については、xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[デフォルトのSUSE Observabilityロールを]参照してください。その他のSUSE Observabilityロールも作成できます。xref:/setup/security/rbac/README.adoc[RBACドキュメントを]参照してください。
. SUSE Observabilityのインストール手順にある`+values.yaml+` ファイルと一緒に`+authentication.yaml+` 。
. Helmアップグレードを実行して変更を適用します：
+
[,text]
----
 helm upgrade \
   --install \
   --namespace suse-observability \
   --values values.yaml \
   --values authentication.yaml \
 suse-observability \
 suse-observability/suse-observability
----

[NOTE]
====
*注：*

* helm upgrade コマンドを最初に実行するとポッドが再起動し、可用性が短時間中断する可能性があります。
* `+helm upgrade+` 実行するたびに`+authentication.yaml+` を含める。
* 認証設定はKubernetesシークレットとして保存される。
====


== セットアップガイド

* xref:/setup/security/authentication/oidc/microsoft-entra-id.adoc[Microsoft Entra ID]

== 外部秘密の使用

oidc シークレットを外部シークレットから取得する場合は、xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[以下の手順に]従いますが、以下のデータを記入してください：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  oidc_client_id: <base64 of client id>
  oidc_secret: <base64 of secret>
----

== 参照

* xref:/setup/security/authentication/troubleshooting.adoc[認証と認可のトラブルシューティング]
* xref:/setup/security/authentication/authentication_options.adoc[認証オプション]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[定義済みのSUSE Observabilityロールの権限]
* xref:/setup/security/rbac/rbac_roles.adoc[RBACロールの作成]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[外部の秘密]
