= Contraseña única
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Autoalojado

Nada más sacarlo de la caja, {stackstate-product-name} se configura con una sola contraseña, xref:/k8s-suse-rancher-prime.adoc#_installation[configurada durante la instalación]. Esto autentica a los usuarios con una única contraseña que debe proporcionarse durante la instalación. 

Esta es la forma más sencilla de empezar a utilizar {stackstate-product-name}, pero para producción se recomienda una de las otras xref:/setup/security/authentication/authentication_options.adoc[opciones de autenticación].

== Obtener la contraseña de un secreto externo

Cuando la contraseña por defecto deba proceder de un secreto externo, siga xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[estos pasos] pero rellene los siguientes datos:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

La codificación de la contraseña puede ser una de estas:* Para una contraseña en texto plano, indique: `+$plain$your-password+` (`+$plain$+` es un prefijo que indica texto sin formato) * Para una contraseña bcifrada proporcione: `+bcrypt-hashed-password+`. Se puede crear un hash bcifrado de la contraseña utilizando `+htpasswd -bnBC 10 "" <password> | tr -d ':\n'+`.

== Ver también

* xref:/setup/security/authentication/authentication_options.adoc[Opciones de autenticación]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permisos para funciones predefinidas {stackstate-product-name} ]
* xref:/setup/security/rbac/rbac_roles.adoc[Crear roles RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Secretos externos]
