= Resolución de problemas de autenticación y autorización
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

Cuando falla la autenticación o la autorización suele deberse a un desajuste en la configuración del proveedor y SUSE Observability. Para facilitar la resolución de problemas, es posible habilitar el registro de depuración en SUSE Observability para autenticación y autorización específicamente.

[CAUTION]
====
Vuelva a desactivar el registro de depuración en cuanto termine de solucionar el problema, ya que es muy probable que el registro de depuración contenga secretos y/o información personal.
====


Para habilitar el registro de depuración copie/pegue el siguiente fragmento yaml en un archivo `+debug-auth.yaml+`.

[,yaml]
----
stackstate:
  components:
    server:
      additionalLogging: |
        <logger name="org.pac4j.core.engine" level="DEBUG"/>
        <logger name="org.pac4j.oidc.profile.creator" level="DEBUG"/>
        <logger name="org.pac4j.oidc.credentials.authenticator" level="DEBUG"/>
    api:
      additionalLogging: |
        <logger name="org.pac4j.core.engine" level="DEBUG"/>
        <logger name="org.pac4j.oidc.profile.creator" level="DEBUG"/>
        <logger name="org.pac4j.oidc.credentials.authenticator" level="DEBUG"/>
----

Ahora ejecute el comando `+helm upgrade+` que utilizó antes pero incluya este archivo yaml extra (así `+helm upgrade .... --values debug-auth.yaml+`) para habilitar el registro de depuración. No se reiniciará ningún pod, los cambios de configuración de registro se cargarán automáticamente transcurridos unos 30 segundos.

Para desactivar el registro de depuración ejecute de nuevo el comando `+helm upgrade ....+` pero omita el `+--values debug-auth.yaml+`. Transcurridos 30 segundos, se carga la configuración de registro actualizada y se detiene el registro de depuración.


== Resolución de problemas con los permisos

* xref:/setup/security/rbac/rbac_permissions.adoc#_list_subjects_for_a_user[Inspeccione los temas de usuario] (usuario y roles) y verifique la configuración en función del modelo de autenticación utilizado.
* xref:/setup/security/rbac/rbac_permissions.adoc#_show_granted_permissions[Inspeccionar un permiso de sujeto] y verificar la configuración dependiendo del modelo de autorización que se esté utilizando.