= Upgrades
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

== Aufrüsten Ihres K3s-Clusters

xref:upgrades/manual.adoc[Manuelle Upgrades] beschreibt verschiedene Techniken für die manuelle Aktualisierung Ihres Clusters. Sie kann auch als Grundlage für Upgrades durch Infrastructure-as-Code-Tools von Drittanbietern wie https://www.terraform.io/[Terraform] verwendet werden.

xref:upgrades/automated.adoc[Automatisierte Upgrades] beschreibt, wie man Kubernetes-native automatisierte Upgrades mit dem https://github.com/rancher/system-upgrade-controller[system-upgrade-controller] von Rancher durchführt.

== Versionsspezifische Vorbehalte

* *Traefik:* Wenn Traefik nicht deaktiviert ist, installieren die K3s-Versionen 1.20 und früher Traefik v1, während die K3s-Versionen 1.21 und später Traefik v2 installieren, wenn v1 nicht bereits vorhanden ist. Um ein Upgrade von der älteren Traefik v1 auf Traefik v2 durchzuführen, lesen Sie bitte die https://doc.traefik.io/traefik/migrate/v1-to-v2/[Traefik-Dokumentation] und verwenden Sie das https://github.com/traefik/traefik-migration-tool[Migrationstool].
* *K3s-Bootstrap-Daten:* Wenn Sie K3s in einer HA-Konfiguration mit einem externen SQL-Datenspeicher verwenden und Ihre Server (Control-Plane)-Knoten nicht mit dem `--token` CLI-Flag gestartet wurden, können Sie dem Cluster keine zusätzlichen K3s-Server mehr hinzufügen, ohne das Token anzugeben. Stellen Sie sicher, dass Sie eine Kopie dieses Tokens aufbewahren, da es für die Wiederherstellung von der Sicherung benötigt wird. Bisher hat K3s die Verwendung eines Tokens bei der Verwendung externer SQL-Datenspeicher nicht erzwungen.
 ** Die betroffenen Versionen sind <= v1.19.12+k3s1, v1.20.8+k3s1, v1.21.2+k3s1; die gepatchten Versionen sind v1.19.13+k3s1, v1.20.9+k3s1, v1.21.3+k3s1.
 ** Sie können den Token-Wert von jedem Server, der dem Cluster bereits beigetreten ist, wie folgt abrufen:
+
[,bash]
----
cat /var/lib/rancher/k3s/server/token
----
