= Equilibrador de carga de clúster
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

En esta sección se describe cómo instalar un equilibrador de carga externo delante de los nodos de servidor de un clúster K3s de alta disponibilidad (HA). Se ofrecen dos ejemplos: Nginx y HAProxy.

[TIP]
====
Los equilibradores de carga externos no deben confundirse con el ServiceLB incrustado, que es un controlador incrustado que permite utilizar los servicios del equilibrador de carga de Kubernetes sin desplegar un controlador de equilibrador de carga de terceros. Para más detalles, consulte xref:networking/networking-services.adoc#_service_load_balancer[Service Load Balancer].

Los equilibradores de carga externos pueden utilizarse para proporcionar una dirección de registro fija para registrar nodos, o para el acceso externo al servidor API de Kubernetes. Para exponer Servicios de LoadBalancer, se pueden utilizar load-balancer externos junto o en lugar de ServiceLB, pero en la mayoría de los casos, los controladores de load-balancer de reemplazo como MetalLB o Kube-VIP son una mejor opción.
====


== Requisitos previos

Todos los nodos de este ejemplo ejecutan Ubuntu 20.04.

Para ambos ejemplos, supongamos que se ha instalado un xref:datastore/ha-embedded.adoc[clúster HA K3s con etcd integrado] en 3 nodos.

Cada servidor k3s está configurado con:

[,yaml]
----
# /etc/rancher/k3s/config.yaml
token: lb-cluster-gd
tls-san: 10.10.10.100
----

Los nodos tienen nombres de host e IP de:

* servidor-1: `+10.10.10.50+`
* servidor-2: `+10.10.10.51+`
* servidor-3: `+10.10.10.52+`

Se configuran dos nodos adicionales para el equilibrio de carga con nombres de host e IP de:

* lb-1: `+10.10.10.98+`
* lb-2: `+10.10.10.99+`

Existen tres nodos adicionales con nombres de host e IP de:

* agente-1: `+10.10.10.101+`
* agente-2: `+10.10.10.102+`
* agente-3: `+10.10.10.103+`

== Configurar el equilibrador de carga

[tabs,sync-group-id=ext-load-balancer]
======
HAProxy::
+
--
http://www.haproxy.org/[HAProxy] es una opción de código abierto que proporciona un equilibrador de carga TCP. También admite HA para el propio equilibrador de carga, lo que garantiza la redundancia a todos los niveles. Consulte HAProxy http://docs.haproxy.org/2.8/intro.html[la documentación de] para obtener más información.

Además, utilizaremos KeepAlived para generar una IP virtual (VIP) que se utilizará para acceder al clúster. Consulte https://www.keepalived.org/manpage.html[la documentación de KeepAlived en] para obtener más información.

. Instale HAProxy y KeepAlived:
+
[,bash]
----
sudo apt-get install haproxy keepalived
----

. Añada lo siguiente a `+/etc/haproxy/haproxy.cfg+` en lb-1 y lb-2:
+
----
frontend k3s-frontend
    bind *:6443
    mode tcp
    option tcplog
    default_backend k3s-backend

backend k3s-backend
    mode tcp
    option tcp-check
    balance roundrobin
    default-server inter 10s downinter 5s
    server server-1 10.10.10.50:6443 check
    server server-2 10.10.10.51:6443 check
    server server-3 10.10.10.52:6443 check
----

. Añada lo siguiente a `+/etc/keepalived/keepalived.conf+` en lb-1 y lb-2:
+
----
global_defs {
  enable_script_security
  script_user root
}

vrrp_script chk_haproxy {
    script 'killall -0 haproxy' # faster than pidof
    interval 2
}

vrrp_instance haproxy-vip {
    interface eth1
    state <STATE> # MASTER on lb-1, BACKUP on lb-2
    priority <PRIORITY> # 200 on lb-1, 100 on lb-2

    virtual_router_id 51

    virtual_ipaddress {
        10.10.10.100/24
    }

    track_script {
        chk_haproxy
    }
}
----

. Reinicie HAProxy y KeepAlived en lb-1 y lb-2:
+
[,bash]
----
systemctl restart haproxy
systemctl restart keepalived
----

. En el agente-1, agente-2 y agente-3, ejecute el siguiente comando para instalar k3s y unirse al clúster:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_TOKEN=lb-cluster-gd sh -s - agent --server https://10.10.10.100:6443
----
Donde `+INSTALL_K3S_ARTIFACT_URL+` es la https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[URL de]
+
Ahora puede utilizar `+kubectl+` desde el nodo servidor para interactuar con el clúster.
+
[,bash]
----
root@server-1 $ k3s kubectl get nodes -A
NAME       STATUS   ROLES                       AGE     VERSION
agent-1    Ready    <none>                      32s     v1.27.3+k3s1
agent-2    Ready    <none>                      20s     v1.27.3+k3s1
agent-3    Ready    <none>                      9s      v1.27.3+k3s1
server-1   Ready    control-plane,etcd,master   4m22s   v1.27.3+k3s1
server-2   Ready    control-plane,etcd,master   3m58s   v1.27.3+k3s1
server-3   Ready    control-plane,etcd,master   3m12s   v1.27.3+k3s1
----
--

Nginx::
+
--
[WARNING]
====
Nginx no soporta de forma nativa una configuración de Alta Disponibilidad (HA). Si se configura un cluster HA, tener un único balanceador de carga delante de los K3 reintroducirá un único punto de fallo.
====

http://nginx.org/[Nginx Open Source] proporciona un equilibrador de carga TCP. Consulte https://nginx.org/en/docs/http/load_balancing.html[Usar nginx como equilibrador de carga HTTP] para obtener más información.

. Cree un archivo `+nginx.conf+` en lb-1 con el siguiente contenido:
+
----
events {}

stream {
  upstream k3s_servers {
    server 10.10.10.50:6443;
    server 10.10.10.51:6443;
    server 10.10.10.52:6443;
  }

  server {
    listen 6443;
    proxy_pass k3s_servers;
  }
}
----

. Ejecute el equilibrador de carga Nginx en lb-1:
+
Usando docker:
+
[,bash]
----
docker run -d --restart unless-stopped \
    -v ${PWD}/nginx.conf:/etc/nginx/nginx.conf \
    -p 6443:6443 \
    nginx:stable
----
+
O https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/[instalar nginx] y luego ejecutar:
+
[,bash]
----
cp nginx.conf /etc/nginx/nginx.conf
systemctl start nginx
----

. En el agente-1, agente-2 y agente-3, ejecute el siguiente comando para instalar k3s y unirse al clúster:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_TOKEN=lb-cluster-gd sh -s - agent --server https://10.10.10.98:6443
----
+
Ahora puede utilizar `+kubectl+` desde el nodo servidor para interactuar con el clúster.
+
[,bash]
----
root@server1 $ k3s kubectl get nodes -A
NAME       STATUS   ROLES                       AGE     VERSION
agent-1    Ready    <none>                      30s     v1.27.3+k3s1
agent-2    Ready    <none>                      22s     v1.27.3+k3s1
agent-3    Ready    <none>                      13s     v1.27.3+k3s1
server-1   Ready    control-plane,etcd,master   4m49s   v1.27.3+k3s1
server-2   Ready    control-plane,etcd,master   3m58s   v1.27.3+k3s1
server-3   Ready    control-plane,etcd,master   3m16s   v1.27.3+k3s1
----
--
======
