= Conjunto de pruebas para proveedores
:revdate: 2025-09-16
:page-revdate: {revdate}

Esta sección contiene información sobre cómo puede aprovechar la suite E2E existente para integrar cualquier proveedor CAPI con Turtles y verificar que el aprovisionamiento y la importación de clusters funcionan como se espera. La validación realiza las siguientes acciones:

* Cree un clúster de gestión en el entorno deseado.
* Instale Rancher y Turtles con todos los requisitos previos.
* Instala Gitea.
* Ejecute la suite que creará un repositorio git, aplique la plantilla de clúster utilizando Fleet y verifique que el clúster se ha creado y se ha importado correctamente en Rancher.

El conjunto de pruebas puede utilizarse para la certificación de proveedores que no figuren en la xref:../overview/certified.adoc[tabla de certificación], como se detalla en xref:../operator/certification.adoc[Certificación de proveedores].

== Cómo utilizarlo

La principal referencia para reutilizar el conjunto de pruebas es https://github.com/rancher-sandbox/turtles-integration-suite-example[este repositorio], que contiene un ejemplo sobre cómo integrar un determinado proveedor CAPI con {product_name} y aplica una serie de comprobaciones basadas en un flujo de trabajo de GitOps.

== Antes de la ejecución

El entorno de pruebas de extremo a extremo utilizado en Turtles ofrece una serie de alternativas de configuración en función del tipo de prueba que esté ejecutando y del tipo de comprobaciones que esté realizando. Si está empezando con el conjunto de pruebas, le recomendamos que mantenga su configuración lo más simple posible y limite el número de personalizaciones para que pueda entender el proceso y sus detalles de configuración. Puede empezar a probar proveedores clonando el repositorio de muestras:

----
git clone https://github.com/rancher-sandbox/turtles-integration-suite-example.git
----

La ejecución de prueba más sencilla que puede realizar crea un entorno local que no utiliza un punto final orientado a Internet. Esto limita las comprobaciones a los clústeres locales (efectivamente, los clústeres CAPI aprovisionados a través de CAPD), pero es suficiente para ejecutar el ejemplo de integración. Puede simplemente ejecutar esta versión local especificando que pretende ejecutarla localmente.

----
MANAGEMENT_CLUSTER_ENVIRONMENT="isolated-kind" make test
----

Al comprobar la integración con otros proveedores de infraestructura (por ejemplo, proveedores para proveedores de nube), tendrá que hacer que su instancia de Rancher esté disponible a través de endpoint para los clústeres descendentes, que ya no se encuentran en su entorno local. La variable `+MANAGEMENT_CLUSTER_ENVIRONMENT+` que utilizamos antes, admite los siguientes valores:

----
MANAGEMENT_CLUSTER_ENVIRONMENT: "kind" # supported options are eks, isolated-kind, kind
----

`+isolated-kind+`que es el valor que utilizamos para las pruebas locales, y `+kind+` desplegará entornos locales equivalentes. La diferencia es que `+kind+` también configurará un punto final de acceso público a través de https://ngrok.com/[] ngrok. Puede obtener un endpoint gratuito (limitado) `+ngrok+` y utilizarlo para ejecutar pruebas. Antes de ejecutar `+make test+`, también deberá configurar las siguientes variables de entorno:

----
NGROK_API_KEY: ""
NGROK_AUTHTOKEN: ""
----

Con esta configuración, durante la creación del entorno, la instancia de Rancher se configurará para que sea accesible a través de su endpoint `+ngrok+` y los clústeres descendentes podrán comunicarse con ella.

La sección <<_other_options,Otras opciones>> contiene más información sobre lo que puede configurar antes de la ejecución.

== Flujo de trabajo básico

En las secciones anteriores hemos presentado las principales acciones realizadas en la integración de la prueba de muestra:

[discrete]
==== Cree un clúster de gestión en el entorno deseado.

* No se trata de un requisito específico de Turtles, ya que, cuando se trabaja con CAPI, es necesario que exista un clúster de gestión que se utilizará para crear recursos que representen clústeres descendentes. Se trata de la parte principal del entorno de pruebas y, en función de las variables de entorno que se pasen al conjunto de pruebas, puede alojarse localmente (mediante `+kind+`) o en la nube (`+eks+`).

[discrete]
==== Instale Rancher y Turtles con todos los requisitos previos.

* Turtles es una extensión de Rancher y, como tal, necesita una instalación de Rancher para ser desplegada. Rancher Manager se ejecutará en el clúster de gestión que creamos en el primer paso y el gráfico de Tortugas se instalará cuando Rancher esté disponible. Si se utiliza una configuración orientada a Internet, un controlador de entrada hará que Rancher sea accesible desde una red externa (por ejemplo, un clúster desplegado en la nube).

[discrete]
==== Ejecute la suite que creará un repositorio git, aplique la plantilla de clúster utilizando Fleet y verifique que el clúster se ha creado y se ha importado correctamente en Rancher.

* El conjunto de pruebas principal, y el utilizado como ejemplo, se basa en un flujo GitOps y utiliza https://github.com/rancher/fleet[Fleet] como herramienta orquestadora de GitOps. Basándose en las plantillas de cluster proporcionadas (puede consultar las que vienen con el ejemplo de integración https://github.com/rancher-sandbox/turtles-integration-suite-example/tree/main/suites/data/cluster-templates[aquí]), creará los clusters CAPI definidos en los archivos YAML. Una vez que este/estos clúster/es estén disponibles, se configurarán para ser xref:../tutorials/first-cluster.adoc[importados a Rancher utilizando Turtles] y se verificará que el/los clúster/es descendente/s es/son accesible/s a través de Rancher. También comprobará que la eliminación se puede realizar en los clústeres descendentes y que ya no están disponibles en Rancher.

== Otras opciones
:kubernetes-version: v1.31.4

Puede consultar el `+config.yaml+` https://github.com/rancher-sandbox/turtles-integration-suite-example/blob/main/config/config.yaml[archivo] en el repositorio `+turtles-integration-suite-example+`, que contiene una lista de variables de entorno utilizadas durante el despliegue del entorno de prueba y la ejecución de la prueba. A continuación se muestra una versión truncada del mencionado archivo YAML:

[source,yaml,subs=attributes+]
----
...
variables:
  CLUSTERCTL_BINARY_PATH: ""
  USE_EXISTING_CLUSTER: "false"
  SKIP_RESOURCE_CLEANUP: "false"
  ARTIFACTS_FOLDER: "_artifacts"
  MANAGEMENT_CLUSTER_ENVIRONMENT: "kind" # supported options are eks, isolated-kind, kind
  RANCHER_VERSION: "{rancher_version}"
  KUBERNETES_VERSION: "{kubernetes-version}"
  KUBERNETES_MANAGEMENT_VERSION: "{kubernetes-version}"
  KUBERNETES_MANAGEMENT_AWS_REGION: "eu-west-2"
  RKE2_VERSION: "{kubernetes-version}+rke2r1"
  TURTLES_PATH: "turtles/rancher-turtles"
  TURTLES_REPO_NAME: "turtles"
  TURTLES_URL: https://rancher.github.io/turtles
  TURTLES_VERSION: "{turtles_version}"
  RANCHER_HOSTNAME: "localhost"
  RANCHER_FEATURES: ""
  RANCHER_PATH: "rancher-latest/rancher"
  RANCHER_REPO_NAME: "rancher-latest"
  RANCHER_URL: "https://releases.rancher.com/server-charts/latest"
  CERT_MANAGER_URL: "https://charts.jetstack.io"
  CERT_MANAGER_REPO_NAME: "jetstack"
  CERT_MANAGER_PATH: "jetstack/cert-manager"
  ...
  ...
  ...
  HELM_BINARY_PATH: "helm"
  HELM_EXTRA_VALUES_FOLDER: "/tmp"
  # Additional setup for establishing rancher ingress
  NGROK_REPO_NAME: "ngrok"
  NGROK_URL: "https://ngrok.github.io/kubernetes-ingress-controller"
  NGROK_PATH: "ngrok/kubernetes-ingress-controller"
  NGROK_API_KEY: ""
  NGROK_AUTHTOKEN: ""
  GITEA_REPO_NAME: "gitea-charts"
  GITEA_REPO_URL: "https://dl.gitea.com/charts/"
  GITEA_CHART_NAME: "gitea"
  GITEA_CHART_VERSION: "10.6.0"
  ...
----

[TIP]
====
Puede consultar el https://github.com/rancher/turtles/tree/main/test/e2e#e2e-tests[repositorio] para ver todas las suites y parámetros que puede utilizar para personalizar la ejecución de las pruebas. Recomendamos hacer esto sólo si está familiarizado con el despliegue/configuración del entorno de pruebas y tiene requisitos específicos de integración.
====

