= 必要条件
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability セルフホスト

== 概要

<<_client_browser,SUSE Observabilityクライアント（ブラウザ>>）の要件は、ページの下部にあります。

=== RancherおよびKubernetesとの互換性
互換性ページはこちらxref:setup/install-stackstate/Compatibility Self Hosted.adoc[RancherとKubernetesの互換性]

=== リソース要件

SUSE Observabilityには、さまざまなインストールオプションがあります。SUSE Observabilityは、高可用性(HA)またはシングルインスタンス(非HA)のセットアップでインストールできます。HA以外のセットアップは、テスト目的のみにお勧めします。本番環境では、HAセットアップでSUSE Observabilityをインストールすることをお勧めします。標準的な本番環境のデプロイでは、SUSE Observability Helmチャートは、各サービスを3つのインスタンスで冗長化して多数のサービスをデプロイします。

以下の表で、さまざまなインストール・オプションに必要なリソースを確認できます。HAセットアップでは、観測される環境の規模に応じて、さまざまなインストールプロファイルを見つけることができる。
このサイジングテーブルで観測されるノードは、4つのvCPUと16GBのメモリとされ、我々の`default node size` 。
観測クラスタ内のノードがより大きい場合、それらは複数の`default nodes` 、12vCPUと48GBのノードは、プロファイルを選択する際に3`default nodes` としてカウントされます。

|===
|  | トライアル | 10ノンHA | 20ノンHA | 50ノンHA | 100ノンHA | 150 HA | 250 HA | 500 HA | 4000 HA

| *CPUリクエスト*
| 7.0
| 7.0
| 9.3
| 14.0
| 23.6
| 49.6
| 61.6
| 85.1
| 212.1

| *CPUリミット*
| 15.1
| 15.1
| 19.4
| 28.8
| 47.9
| 105.2
| 128.3
| 176.2
| 281

| *メモリーのリクエスト*
| 22.7Gi
| 22.7Gi
| 26.5Gi
| 30.9Gi
| 47.0Gi
| 127.0Gi
| 142.1Gi
| 166.4Gi
| 263.9Gi

| *メモリーの制限*
| 23.3Gi
| 23.3Gi
| 27.2Gi
| 31.0Gi
| 47.2Gi
| 131.8Gi
| 146.7Gi
| 171.2Gi
| 321.7Gi
|===

[NOTE]
====
プロファイルに表示されている要件は、Suse Observabilityサーバーを実行するために必要なリソースの総量を表しています。
Suse Observabilityサーバーのすべてのサービスが割り当てられるようにする：

* HA以外のインストールでは、推奨ノードサイズは4VCPU、8GB
* 500ノードまでのHAインストールでは、最小推奨ノードサイズは8VCPU、16GBです。
* 4000ノードのHAインストールでは、最小推奨ノードサイズは16VCPU、32GBです。
====


これらは、さまざまなインストールオプションでSUSE Observabilityが消費できるリソースの上限と下限にすぎません。実際のリソース使用量は、使用される機能、設定されたリソース制限、およびDeploymentまたはDaemonSetスケーリングなどの動的な使用パターンに依存します。セルフホスティングのお客様には、デフォルトの要件で開始し、SUSE Observabilityコンポーネントのリソース使用量を監視することをお勧めします。

[NOTE]
====
最小要件には、アプリケーションのスムーズなローリングアップデートを保証するための予備のCPU/メモリ容量は含まれていません。
====


SUSE Observabilityのインストールについては、以下のインストール手順に従ってください：

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift]

=== ストレージ

SUSE Observabilityは、データの保存が必要なサービスに永続ボリュームクレームを使用します。コマンドラインまたは`values.yaml` ファイルで指定された値によって上書きされない限り、クラスタのデフォルト・ストレージ・クラスがすべてのサービスに使用されます。すべてのサービスには、使い始めに最適なボリュームサイズがあらかじめ設定されていますが、必要に応じて変数を使用して後でカスタマイズすることができます。

[NOTE]
====
本番環境では、データが破損する可能性があるため、SUSE ObservabilityのストレージプロビジョニングにはNFSを推奨およびサポートしません。
====


私たちのさまざまなインストールプロファイルでは、以下がデフォルトのストレージ要件です：

|===
|  | トライアル | 10ノンHA | 20ノンHA | 50ノンHA | 100ノンHA | 150 HA | 250 HA | 500 HA | 4000 HA

| *保持日数（日）*
| 3
| 30
| 30
| 30
| 30
| 30
| 30
| 30
| 30

| *保管条件*
| 163GB
| 358GB
| 401GB
| 508GB
| 562GB
| 2.8TB
| 2.9TB
| 3.9TB
| 7.5TB
|===

[NOTE]
====
提示された保管の見積もりは、NONHAの場合は14日間、HAの場合は1ヶ月の保管の既定値を考慮している。短時間のテストインスタンスの場合、ストレージサイズをさらに小さくすることができる。
====


使用されるデフォルト値の詳細については、xref:/setup/install-stackstate/kubernetes_openshift/storage.adoc[ストレージの構成]ページを参照。

=== 名前空間リソースの制限

ResourceQuotaを設定することは、リソースリクエストの妨げになる可能性があるため、推奨されません。SUSE Observabilityが必要とするリソースは、使用する機能、設定済みのリソース制限、およびDeploymentやDaemonSetのスケーリングなどの動的な使用パターンによって異なります。

実装にResourceQuotaを設定する必要がある場合は、ネームスペースのリソース上限をノードのxref:/setup/install-stackstate/requirements.adoc#_resource_requirements[サイズ要件に合わせて]設定する必要があります。

== クライアント（ブラウザ）

SUSE Observability GUIを使用するには、次のWebブラウザのいずれかを使用する必要があります：

* クローム
* ファイアフォックス
