include::partial$variables.adoc[]
= 定义策略设置
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 修改 settings.go 文件中的代码，以定义策略设置，包括执行用于正则表达式 marshaling 和 unmarshaling 的自定义函数。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "go", "defining-policy-settings"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"定义策略设置"、"Go"]
:sidebar_label: 定义策略设置
:sidebar_position: 24
:current-version: {page-origin-branch}

首先，需要定义保存策略设置的结构。

要做到这一点，需要修改`+settings.go+` 文件（来自本地版本的 Go 策略模板）中的代码。
您需要在`+import+` 部分增加两行，更改`+Settings+` 结构，并添加`+RegularExpression+` 结构。

它应与以下代码一致：

[,go]
----
import (
    "encoding/json"
    "fmt"
    "regexp"

    mapset "github.com/deckarep/golang-set/v2"
    kubewarden "github.com/kubewarden/policy-sdk-go"
    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
)

type Settings struct {
    DeniedLabels      mapset.Set[string]            `+json:"denied_labels"+`
    ConstrainedLabels map[string]*RegularExpression `+json:"constrained_labels"+`
}

type RegularExpression struct {
    *regexp.Regexp
}
----

[NOTE]
====
`+DeniedNames+` 不再需要`+settings.go+` 中定义的`+Settings+` 结构。

由于不再定义`+DeniedNames+` ，因此也应删除`+settings.go+` 中的函数`+IsNameDefined+` 。
您还应删除`+settings_test.go+`,`+TestIsNameDenied+` 中引用它的函数。
====


您使用`+regexp+` 软件包来处理正则表达式对象，并使用https://github.com/deckarep/golang-set[`+mapset.Set+`]类型来存储拒绝标签列表。

由于`+regexp.Regexp+` 不处理反序列化，因此需要定义自定义函数来处理正则表达式的 marshaling 和 unmarshaling：

[,go]
----
// UnmarshalText satisfies the encoding.TextMarshaler interface,
// also used by json.Unmarshal.
func (r *RegularExpression) UnmarshalText(text []byte) error {
    nativeRegExp, err := regexp.Compile(string(text))
    if err != nil {
        return err
    }
    r.Regexp = nativeRegExp
    return nil
}

// MarshalText satisfies the encoding.TextMarshaler interface,
// also used by json.Marshal.
func (r *RegularExpression) MarshalText() ([]byte, error) {
    if r.Regexp != nil {
        return []byte(r.Regexp.String()), nil
    }

    return nil, nil
}
----

此外，您还需要`+UnmarshalJSON+` 方法来处理`+Settings+` 结构的反序列化：

[,go]
----
func (s *Settings) UnmarshalJSON(data []byte) error {
    rawSettings := struct {
        DeniedLabels      []string          `+json:"denied_labels"+`
        ConstrainedLabels map[string]*RegularExpression `+json:"constrained_labels"+`
    }{}

    err := json.Unmarshal(data, &rawSettings)
    if err != nil {
        return err
    }

    s.DeniedLabels = mapset.NewThreadUnsafeSet[string](rawSettings.DeniedLabels...)
    s.ConstrainedLabels = rawSettings.ConstrainedLabels

    return nil
}
----

== 建立`+Settings+` 实例

{short-project-name} 政策提供两种不同的功能，它们接收政策设置作为输入：

* `+validate+`:当 Kubernetes 对象需要策略验证时使用此功能。
设置是https://pkg.go.dev/github.com/kubewarden/policy-sdk-go@v0.2.1/protocol#ValidationRequest[`+ValidationRequest+`]对象的一部分。
* `+validate_settings+`:{short-project-name} 首次加载策略时调用该函数。
该函数接收策略设置作为输入，并检查其有效性。

您需要创建一个辅助函数，从 JSON 有效负载开始创建`+Settings+` 对象：

[,go]
----
func NewSettingsFromValidationReq(validationReq *kubewarden_protocol.ValidationRequest) (Settings, error) {
    settings := Settings{}
    err := json.Unmarshal(validationReq.Settings, &settings)
    if err != nil {
        return Settings{}, err
    }

    return settings, nil
}
----

[NOTE]
====
所有`+mapset.Set+` 对象都是使用https://pkg.go.dev/github.com/deckarep/golang-set?utm_source=godoc#NewThreadUnsafeSet[线程不安全变体]创建的。
WebAssembly 代码在单线程中执行，因此不存在并发问题。

WebAssembly 标准尚未涵盖线程。
详见https://github.com/WebAssembly/threads[正式提案]。
====


== 实施`+Settings+` 验证

所有{short-project-name} 政策都必须执行设置验证。

为此，您可以在`+Settings+` 实例中添加`+Valid+` 方法：

[,go]
----
func (s *Settings) Valid() (bool, error) {
    constrainedLabels := mapset.NewThreadUnsafeSet[string]()

    for label := range s.ConstrainedLabels {
        constrainedLabels.Add(label)
    }

    constrainedAndDenied := constrainedLabels.Intersect(s.DeniedLabels)
    if constrainedAndDenied.Cardinality() != 0 {
        return false,
            fmt.Errorf("These labels cannot be constrained and denied at the same time: %v", constrainedAndDenied)
    }

    return true, nil
}
----

`+Valid+` 方法确保 "受限 "地图中没有 "拒绝 "标签。
使用`+mapset.Set+` 提供的`+Intersect+` 方法可简化检查。

[NOTE]
====
`+Valid+` 方法的调用对象是已经实例化的`+Setting+` 对象。
这意味着`+Settings+` unmarshaler 已经对用户提供的正则表达式进行了验证。
====


最后，您需要将脚手架提供的`+validateSettings+` 函数改成下面的样子：

[,go]
----
func validateSettings(payload []byte) ([]byte, error) {
    settings := Settings{}
    err := json.Unmarshal(payload, &settings)
    if err != nil {
        return kubewarden.RejectSettings(
            kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
    }

    valid, err := settings.Valid()
    if valid {
        return kubewarden.AcceptSettings()
    }

    return kubewarden.RejectSettings(
        kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
}
----

您可以看到，该函数利用了https://github.com/kubewarden/policy-sdk-go[{short-project-name} 的 SDK] 提供的辅助函数。

== 测试设置代码

对您编写的代码进行良好的测试覆盖非常重要。
您正在使用的脚手架代码在`+settings_test.go+` 文件中定义了一系列单元测试。

您必须更改该文件的内容，以反映`+Settings+` 类的新行为。

包括您正在使用的 Go 软件包：

[,go]
----
import (
    "testing"

    "encoding/json"

    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
)
----

您可以先编写一个单元测试，确保可以从`+ValidationRequest+` 对象分配一个`+Settings+`实例：

[,go]
----
func TestParseValidSettings(t *testing.T) {
    settingsJSON := []byte(`
        {
            "denied_labels": [ "foo", "bar" ],
            "constrained_labels": {
                    "cost-center": "cc-\\d+"
            }
        }`)

    settings := Settings{}
    err := json.Unmarshal(settingsJSON, &settings)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    expected_denied_labels := []string{"foo", "bar"}
    for _, exp := range expected_denied_labels {
        if !settings.DeniedLabels.Contains(exp) {
            t.Errorf("Missing value %s", exp)
        }
    }

    re, found := settings.ConstrainedLabels["cost-center"]
    if !found {
        t.Error("Didn't find the expected constrained label")
    }

    expected_regexp := `+cc-\d++`
    if re.String() != expected_regexp {
        t.Errorf("Expected regexp to be %v - got %v instead",
            expected_regexp, re.String())
    }
}
----

下一步需要进行一个测试，检查当用户提供了一个错误的正则表达式时是否生成了`+Settings+` 实例：

[,go]
----
func TestParseSettingsWithInvalidRegexp(t *testing.T) {
    settingsJSON := []byte(`
        {
            "denied_labels": [ "foo", "bar" ],
            "constrained_labels": {
                    "cost-center": "cc-[a+"
            }
        }`)

    err := json.Unmarshal(settingsJSON, &Settings{})
    if err == nil {
        t.Errorf("Didn't get expected error")
    }
}
----

现在，您可以定义一个测试来检查`+validate_settings+` 入口点的行为。

您可以查看`+validateSettings+` 函数返回的`+SettingsValidationResponse+` 对象：

[,go]
----
func TestDetectValidSettings(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar" ],
        "constrained_labels": {
            "cost-center": "cc-\\d+"
        }
    }`)

    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if !response.Valid {
        t.Errorf("Expected settings to be valid: %s", *response.Message)
    }
}
----

最后，你还要编写两个测试来检查`+validateSettings+` 函数是否以正确的信息拒绝无效设置：

[,go]
----
func TestDetectNotValidSettingsDueToBrokenRegexp(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar" ],
        "constrained_labels": {
            "cost-center": "cc-[a+"
        }
    }
    `)

    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if response.Valid {
        t.Error("Expected settings to not be valid")
    }

    if *response.Message != "Provided settings are not valid: error parsing regexp: missing closing ]: `+[a++`" {
        t.Errorf("Unexpected validation error message: %s", *response.Message)
    }
}

func TestDetectNotValidSettingsDueToConflictingLabels(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar", "cost-center" ],
        "constrained_labels": {
            "cost-center": ".*"
        }
    }`)
    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if response.Valid {
        t.Error("Expected settings to not be valid")
    }

    if *response.Message != "Provided settings are not valid: These labels cannot be constrained and denied at the same time: Set{cost-center}" {
        t.Errorf("Unexpected validation error message: %s", *response.Message)
    }
}
----

现在，您可以使用以下命令运行目前已定义的测试：

[subs="+attributes",shell]
----
go test -v settings.go settings_test.go
----

所有测试都将通过，输出结果如下

[subs="+attributes",shell]
----
=== RUN   TestParseValidSettings
--- PASS: TestParseValidSettings (0.00s)
=== RUN   TestParseSettingsWithInvalidRegexp
--- PASS: TestParseSettingsWithInvalidRegexp (0.00s)
=== RUN   TestDetectValidSettings
--- PASS: TestDetectValidSettings (0.00s)
=== RUN   TestDetectNotValidSettingsDueToBrokenRegexp
--- PASS: TestDetectNotValidSettingsDueToBrokenRegexp (0.00s)
=== RUN   TestDetectNotValidSettingsDueToConflictingLabels
--- PASS: TestDetectNotValidSettingsDueToConflictingLabels (0.00s)
PASS
ok      command-line-arguments    0.002s
----

现在，您可以在下一节中执行实际的验证代码。
