= {k3s-product-name}
:page-languages: [en, ja, ko, zh]
:revdate: 2024-10-23
:page-revdate: {revdate}
:page-role: -toc

K3s ist ein offizielles https://www.cncf.io[CNCF-Sandbox-Projekt], das eine leichtgewichtige und dennoch leistungsstarke zertifizierte Kubernetes-Distribution bereitstellt, die für Produktions-Workloads an ressourcenbeschränkten, entfernten Standorten oder auf IoT-Geräten konzipiert ist. In Verbindung mit SUSE Rancher Prime ist K3s eine einfach zu installierende, leichtgewichtige und dennoch hochverfügbare Kubernetes-Distribution, die sich problemlos innerhalb der Rancher-Orchestrierungsplattform verwalten lässt.

== Wesentliche Merkmale

* Wird als einzelne Binärdatei oder minimales Container-Image verteilt.
* Leichtgewichtiger Datenspeicher basierend auf sqlite3 als Standard-Speicher-Backend. etcd3, MySQL und Postgres sind ebenfalls verfügbar.
* Verpackt in einem einfachen Launcher, der einen Großteil der Komplexität von TLS und Optionen handhabt.
* Standardmäßig sicher mit vernünftigen Standardeinstellungen für leichtgewichtige Umgebungen.
* Der Betrieb aller Komponenten der Kubernetes-Kontrollebene ist in einer einzigen Binärdatei und einem einzigen Prozess gekapselt, sodass K3s komplexe Clusteroperationen wie die Verteilung von Zertifikaten automatisieren und verwalten kann.
* Externe Abhängigkeiten wurden auf ein Minimum reduziert; die einzigen Anforderungen sind ein moderner Kernel und cgroup mounts.
* Pakete mit den erforderlichen Abhängigkeiten für die einfache Erstellung von "batteries-included"-Clustern:
 ** containerd / cri-dockerd Container-Laufzeitumgebung (CRI)
 ** Flannel Container Network Interface (CNI)
 ** CoreDNS Cluster DNS
 ** Traefik Ingress Controller
 ** ServiceLB-Load-Balancer-Steuerung
 ** Kube-Router Netzwerkrichtlinien-Controller
 ** Local-path-provisioner Persistent Volume Controller
 ** Spegel verteilte Container-Image-Registrierungsspiegel
 ** Host-Dienstprogramme (iptables, socat, usw.)

== Ideal für:

* Kante
* Homelab
* Internet der Dinge (IoT)
* Kontinuierliche Integration (CI)
* Entwicklung
* Einplatinencomputer (ARM)
* Umgebungen mit Luftschleusen
* Eingebettete K8s
* Situationen, in denen eine Promotion in K8s-Clusterologie nicht durchführbar ist
