include::partial$variables.adoc[]
= Problema de rotação do certificado do servidor de políticas para a versão ≤ v1.16.0
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Resolver problemas de rotação de certificados do servidor de políticas em {project-name}, a partir da versão 1.16.
:doc-persona: ["kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["howto", "workarounds", "policy server certificates"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "policy server certificates"]
:sidebar_label: Rotação de certificados
:sidebar_position: 10
:current-version: {page-origin-branch}

[IMPORTANT]
.Solução alternativa para {project-name} v1.16.0 e versões anteriores
====

Essa solução alternativa é necessária apenas para o site {short-project-name} v1.16.0 e versões anteriores.
A partir da versão 1.17.0, o controlador renova automaticamente os certificados do servidor de políticas.

====

Durante o processo de lançamento da versão 1.14, o site {short-project-name} descobriu um bug relacionado à rotação do certificado do servidor de políticas. A configuração da CA raiz tem validade de 10 anos, mas cada segredo de certificado do servidor de políticas tem validade de um ano. No entanto, no momento, o controlador não consegue renová-los automaticamente.

Na versão v1.14, o site {short-project-name} garantiu que os segredos do servidor de políticas fossem criados com um prazo de validade de 10 anos.

Um processo de renovação automatizado está em vigor para a versão ≥ v1.16.0.

Até lá, os usuários podem excluir manualmente o segredo do certificado expirado (policy-server-default) e acionar uma reconciliação do controlador. Você faz isso adicionando, removendo ou atualizando uma política ou ajustando o número de réplicas de um PolicyServer.
