include::partial$variables.adoc[]
= Scanner de auditoria - Limitações
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Saiba mais sobre as limitações ao usar o Audit Scanner para avaliar políticas e tipos de eventos em um ambiente Kubernetes, incluindo seu uso para avaliação de políticas e tipos de eventos.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["explanations", "audit-scanner", "limitations"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "kubernetes", "audit scanner"]
:sidebar_label: Limitações
:current-version: {page-origin-branch}

== Tipos de eventos suportados

As políticas podem inspecionar os eventos `+CREATE+`, `+UPDATE+` e `+DELETE+`.

O scanner de auditoria não pode simular eventos do `+UPDATE+`, pois não sabe qual parte do recurso precisa ser alterada.

Portanto, o scanner de auditoria ignora uma política que se preocupa apenas com os eventos do `+UPDATE+`. scanner.

[NOTE]
====

A versão v1.7.0 do audit-scanner é compatível apenas com os eventos `+CREATE+`. O manuseio dos eventos do`+DELETE+` será feito em breve.

====


== Políticas que dependem de informações de usuários e grupos de usuários

Cada objeto de solicitação de admissão do Kubernetes tem informações sobre qual usuário (ou ServiceAccount) iniciou o evento e a qual grupo ele pertence.

Todos os eventos simulados pelo scanner de auditoria são originados do mesmo usuário e grupo codificados. Por isso, as políticas que se baseiam nesses valores para tomar suas decisões não produzirão resultados significativos.

Para esses casos, configure a política como não auditável. verificações.

== Políticas que dependem de dados externos

As políticas podem solicitar e usar dados externos ao realizar uma avaliação. Você pode avaliar essas políticas com as verificações de auditoria, mas seus resultados podem mudar dependendo dos dados externos.

== Uso do site `+*+` por políticas

Os recursos personalizados `+AdmissionPolicy+` e `+ClusterAdmissionPolicy+` têm os seguintes campos:

[subs="+attributes",yaml]
----
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
----

Os atributos `+apiGroups+`, `+apiVersions+` e `+resources+` podem usar o curinga`+*+`. Esse símbolo curinga faz com que a política corresponda a todos os valores usados no campo. O scanner de auditoria ignora as políticas que usam o símbolo `+*+`.
