= Komponenten der Architektur
:revdate: 2025-09-08
:page-revdate: {revdate}

Die für die Bereitstellung der xref:rancher-os-management/architecture/services/architecture-services.adoc[Dienste von{elemental-product-name} ] erforderlichen Komponenten sind:

* das <<_elemental_command_line_tool,`+elemental+`>> Kommandozeilenprogramm
* der <<_elemental_operator_daemon,`+elemental-operator+`>> Daemon
* das <<_elemental_register_command_line_tool,`+elemental-register+`>> Kommandozeilenprogramm
* der <<_elemental_system_agent_daemon,`+elemental-system-agent+`>> Daemon
* ein oder mehrere <<_suse_rancher_prime_os_manager_os_container_image,{elemental-product-name} OS-Container-Images>>

== `+elemental+` Kommandozeilenprogramm

Das Tool `+elemental+` ist Teil des link:{elemental_toolkit_url}[{elemental_toolkit_name}] Projekts.
Sie führt die eigentliche Betriebssysteminstallation und -aktualisierung auf dem Host durch und wird zur Ausführung der xref:references/cloud-config-reference.adoc[Cloud-Config-Direktiven] verwendet, die in den xref:rancher-os-management/architecture/custom-resources.adoc[{elemental-product-name} CRDs] hinzugefügt wurden.

Die Binärdatei `+elemental+` ist in allen Basis-OS-Images enthalten, die mit {elemental-product-name} verteilt werden.

== `+elemental-operator+` Daemon

Der *elemental-operator-Daemon* erfüllt zwei Hauptaufgaben:

. bettet die {elemental-product-name} Kubernetes-Controller ein, um alle xref:rancher-os-management/architecture/custom-resources.adoc[{elemental-product-name} CRDs] zu verwalten
. stellt die _Registrierungsendpunkte_ zur Verfügung, damit der Host sich registrieren und die Betriebssystemkonfiguration während der xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[Inbetriebnahme des Rechners] herunterladen kann

Der `+elemental-operator+` Daemon wird auf dem Rancher-Cluster als `+Deployment+` über das xref:references/operatorchart-reference.adoc[{elemental-product-name} Operator Helm Chart] bereitgestellt.

== `+elemental-register+` Kommandozeilenprogramm

Die Binärdatei *elemental-register* ist der Client, der zur Registrierung des Hosts an den vom <<_elemental_operator_daemon,elemental-operator>> bereitgestellten _Registrierungsendpunkten_ verwendet wird. Er sammelt die Host-Daten und leitet sie weiter, damit der <<_elemental_operator_daemon,Elementaroperator>> die SMBIOS- und die Hardware-Label-Vorlagen ausfüllen kann.

Wenn die Registrierungsphase erfolgreich durchgeführt wurde, erhält das *elemental-register* die vollständige Konfiguration, die in der xref:references/machineregistration-reference.adoc[MachineRegistration] gespeichert ist, vom *elemental-operator*.
Im letzten Schritt ruft der *elemental-register-Client* das <<_elemental_command_line_tool,elemental-Binary>> auf und übergibt die abgerufene Konfiguration, um die Betriebssysteminstallation zu starten.

== `+elemental-system-agent+` Daemon

Die `+elemental-system-agent+` basiert auf dem https://github.com/rancher/system-agent[System Agent Projekt] Rancher und ermöglicht {elemental-product-name} die Bereitstellung von _Plänen_ zur Unterstützung der Hostbereitstellung.
Die Installation und Konfiguration von `+rancher-system-agent+`, die für den xref:rancher-os-management/architecture/services/architecture-clusterdeployment.adoc[Kubernetes-Cluster-Bereitstellungsdienst] erforderlich ist, wird über einen `+elemental-system-agent+` _Plan_ durchgeführt.

== {elemental-product-name} OS-Container-Image

Ein link:{elemental_toolkit_url}[{elemental_toolkit_name}] OS-Image ist ein OCI-Container-Image, das alle Dateien enthält, aus denen das Betriebssystem des Zielhosts besteht. Sie enthält nicht nur alle Binärdateien und Bibliotheken, sondern auch den Kernel und die Bootdateien, die für ein Linux-System erforderlich sind.

Das {elemental-product-name} Betriebssystem-Image ist ein kommentiertes link:{elemental_toolkit_url}[{elemental_toolkit_name}] Betriebssystem-Image, das auf https://www.suse.com/products/micro/[Micro] SLE basiert und spezifische {elemental-product-name} Konfigurationen und Binärdateien (die <<_elemental_command_line_tool,elementaren>> und die <<_elemental_register_command_line_tool,elementaren Register>> ) enthält.

Die {elemental-product-name} OS-Images werden in den xref:references/managedosversion-reference.adoc[ManagedOSVersions-Ressourcen] nachverfolgt. Die xref:references/managedosversion-reference.adoc[ManagedOSVersions-Ressourcen] werden dynamisch aus xref:references/managedosversionchannel-reference.adoc[ManagedOSVersionChannel-Ressourcen] erstellt. Bei jeder Installation von {elemental-product-name} Operator wird eine Standardressource `+ManagedOSVersionChannel+` bereitgestellt.
