include::partial$variables.adoc[]
= ドキュメントの改善提案
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 足りないもの、古いもの、間違っているもの、品質レビューが必要なものなど、明確な詳細を添えて GitHub issue を開き、ドキュメントの改善を開始しましょう。
:doc-persona: ["kubewarden-developer", "kubewarden-operator", "kubewarden-manager"]
:doc-topic: ["contribution-guide", "docs-contribution", "improvement"]
:doc-type: ["howto"]
:keywords: ["kubewarden"、"documentation"、"suggesting an improvement"]。
:sidebar_label: ドキュメントの改善提案
:sidebar_position: 8
:current-version: {page-origin-branch}

{short-project-name} のドキュメントに問題があることに気づいたり、新しいコンテンツを提案したりしたい場合は、issue を開いてください。必要なのは、https://github.com/join[GitHubアカウントへの]アクセスとブラウザだけだ。

通常、{short-project-name} の新しいドキュメンテーション作業は、GitHubのissueから始まる。
ifeval::["{build-type}" == "community"]
https://github.com/orgs/kubewarden/teams/kubewarden-documentation[{short-project-name} ドキュメンテーション・チームが]レビューし、分類し、タグ付けを行う。[ドキュメンテーション・チーム]がレビューし、分類し、タグ付けを行う。]
endif::[]
ifeval::["{build-type}" == "product"]
https://github.com/orgs/rancher/teams/docs[{short-project-name} ドキュメンテーション・チームが]レビューし、分類し、タグ付けを行う。[ドキュメンテーション・チーム]がレビューし、分類し、タグ付けを行う。]
endif::[]
記者を含め、誰でもどのような問題にも取り組むことができるが、重複作業を避けるため、作業を開始する前に自分に割り当てておくべきである。

== イシューを開く

既存のドキュメントの内容の改善を提案したり、エラーを報告したりするには、issueを開いてください。

* 上部のGitHub Octocatアイコンをクリックします。にリダイレクトされます。
ifeval::["{build-type}" == "community"]
  https://github.com/kubewarden/docs[ {short-project-name} のドキュメント・リポジトリ]。
endif::[]
ifeval::["{build-type}" == "product"]
  https://github.com/rancher/kubewarden-product-docs[ {short-project-name} のドキュメント・リポジトリ]。
endif::[]
* issue]タブに移動し、[*New issue]*をクリックします。
* 問題または改善提案を記述する。詳細は多ければ多いほどいい。
* *新しいissueを送信*]をクリックします。
* issueを提出した後、そのissueをあなた自身に割り当てるか、コミュニティ・メンバーがピックアップするのを待つことができます。ドキュメンテーションチームやコミュニティのメンバーは、あなたの問題に対処する前に、説明を求めるかもしれません。自分の課題やhttps://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications[GitHubの通知をオンにする]を積極的にチェックしてください。

== 新コンテンツの提案

新しいコンテンツを提案するには、以下のいずれかの方法でissueを提出してください：

* コンテンツが属すると思われるセクションの既存のページを選択し、*issueの作成を*クリックします。または
ifeval::["{build-type}" == "community"]
* https://github.com/kubewarden/docs/issues/new/choose[GitHubに]移動し、直接issueを提出してください。
endif::[]
ifeval::["{build-type}" == "product"]
* https://github.com/rancher/kubewarden-product-docs/issues/new/choose[GitHubに]移動し、直接issueを提出してください。
endif::[]

== どのように寄付をするのか？

貢献の大小はない。ただし、コミュニティが最大限の価値を得られるよう、問題を報告する際には以下の点にご注意ください：

* 問題を明確に説明することに集中する。考慮すべき重要なポイントは、何が欠けているか、古くなっているか、間違っているか、質的・技術的な改善が必要かを説明することだろう。
* その問題がユーザーに与える具体的な影響について説明してください。
* 問題の範囲を限定する。スコープが大きい場合は、課題内の小さなタスクに分割する。例えば、「貢献ガイドの作成」は、課題に関連する複数のタスクがあるため、範囲が広い。
  しかし、「クイックスタートページの文法ミスの修正」は、プルリクエスト1つで済むような、より狭い範囲の問題である。
* 重複作業を避けるため、既存の問題をクロスチェックする。
* 既存のプルリクエストまたは課題をチェックします。既存の課題またはプルリクエストを参照し、その課題に取り組みたいと思うコントリビューターにコンテキストを提供できるようにしてください。
