= 如何构建和使用自定义操作系统镜像
:revdate: 2025-09-08
:page-revdate: {revdate}

== 使用自定义 Dockerfile 重制操作系统镜像

由于{elemental-product-name} 提供的操作系统镜像是容器镜像，因此它们也可用作 Dockerfile 中的基础镜像，以创建新的容器镜像。

元素 "项目发布了几种不同风格的图像：

* 裸金属：包含适合裸机部署的固件和驱动程序的映像。
* rt：基于裸机镜像，但包含实时内核。
* kvm：适合虚拟机的更薄图像。
* 基地元素》所需的基础系统，供其他口味使用。

假设需要从额外的软件源中添加一些软件包，下面的示例展示了如何添加这些软件包：

[,docker]
----
# The version of Elemental to modify.
FROM registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:latest

# Custom commands
RUN rpm --import <repo-signing-key-url> && \
    zypper addrepo --refresh <repo_url> extra_repo && \
    zypper install -y <extra_package>

# IMPORTANT: /etc/os-release is used for versioning/upgrade. The
# values here should reflect the tag of the image currently being built
ARG IMAGE_REPO=norepo
ARG IMAGE_TAG=latest
RUN \
    sed -i -e "s|^IMAGE_REPO=.*|IMAGE_REPO=\"${IMAGE_REPO}\"|g" /etc/os-release && \
    sed -i -e "s|^IMAGE_TAG=.*|IMAGE_TAG=\"${IMAGE_TAG}\"|g" /etc/os-release && \
    sed -i -e "s|^IMAGE=.*|IMAGE=\"${IMAGE_REPO}:${IMAGE_TAG}\"|g" /etc/os-release

# IMPORTANT: it is good practice to recreate the initrd and re-apply `elemental-init`
# command that was used in the base image. This ensures that any eventual change that should
# be synced in initrd included binaries is also applied there and consistent.
RUN elemental init --force elemental-rootfs,grub-config,dracut-config,cloud-config-essentials,elemental-setup
----

其中`latest` 是我们要定制的基本版本。

然后执行以下命令

[,bash]
----
docker build --build-arg IMAGE_REPO=myrepo/custom-build \
             --build-arg IMAGE_TAG=v1.1.1 \
             -t myrepo/custom-build:v1.1.1 .
docker push myrepo/custom-build:v1.1.1
----

新的定制操作系统以 Docker 镜像的形式提供`myrepo/custom-build:v1.1.1` ，可以使用 docker 运行和验证，使用时使用

[,bash]
----
docker run -it myrepo/custom-build:v1.1.1 bash
----

## 创建自定义可启动安装 ISO

{elemental-product-name} 利用容器映像来构建根文件系统；因此，可以在多阶段环境中使用它来创建捆绑了自定义容器映像的自定义可启动媒体。

[,docker]
----
FROM registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:latest AS os

# Check the previous section on building custom images

# The released OS already includes the toolchain for building ISOs
FROM registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:latest AS builder

ARG TARGETARCH
WORKDIR /iso
COPY --from=os / rootfs

# work around buildah issue: https://github.com/containers/buildah/issues/4242
RUN rm -f rootfs/etc/resolv.conf

RUN elemental build-iso \
        dir:rootfs \
        --bootloader-in-rootfs \
        --squash-no-compression \
        -o /output -n "elemental-${TARGETARCH}"

FROM busybox
COPY --from=builder /output /elemental-iso

ENTRYPOINT ["busybox", "sh", "-c"]
----

使用常规的`docker build` 命令构建它：

[,bash]
----
docker build -t myrepo/custom-build:v1.1.1 \
              --build-arg IMAGE_REPO=myrepo/custom-build-iso \
              --build-arg IMAGE_TAG=v1.1.1 \
              .
----

生成的容器映像实际上是一个包括 ISO 的容器映像，这个容器映像也可以推送到 OCI 注册表。ISO 映像可以通过以如下方式执行容器，从容器中提取到当前文件夹：

[,bash]
----
docker run --rm -v $(pwd):/host mytest-image "busybox cp /elemental-iso/*.iso /host"
----

新的定制安装介质可在`elemental-<arch>.iso` 中找到。

上述容器运行等同于_元素操作器_从容器中提取 ISO 以构建一个新容器（包括注册 URL）的操作，因此这也是一个很好的检查标记，可以验证容器是否可以推送到注册表，并被_元素操作器_用作xref:references/seedimage-reference.adoc[种子图像]资源的`baseImage` 。

== 将自定义图像作为 ManagedOSVersion 资源列出

在{elemental-product-name} 中，将操作系统容器映像和 ISO 容器映像列为 ManagedOSVersion 资源不是必须的，但很方便。特别是从用户界面的角度来看，这使得自定义图片在{elemental-product-name} UI 扩展中可见并易于使用。

继续上一节的示例，我们构建了一个自定义操作系统容器（引用为`myrepo/custom-build:v1.1.1` ），并最终将其推送到注册表中。然后，就可以将该镜像添加为 ManagedOSVersion 资源了：

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  name: v1.1.1-custom-build
  namespace: fleet-default
spec:
  metadata:
    displayName: Custom build image
    upgradeImage: myrepo/custom-build:v1.1.1
  type: container
  version: v1.1.1
----

请注意，`type: container` 说明这是一个容器操作系统。这样，映像`myrepo/custom-build:v1.1.1` 就可以通过用户界面进行操作系统升级。

最后，ISO`myrepo/custom-build-iso:v1.1.1` 的自定义容器也可以作为 ManagedOSVersion 资源包含在内：

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  name: v1.1.1-custom-build-iso
  namespace: fleet-default
spec:
  metadata:
    displayName: Custom build ISO image
    uri: myrepo/custom-build-iso:v1.1.1
  type: iso
  version: v1.1.1
----

请注意`type: iso` 说明这是 ISO。这样，图像`myrepo/custom-build-iso:v1.1.1` 就有资格从用户界面生成种子图像。

== 自定义分区大小

在创建自定义镜像时，必须考虑磁盘分区的大小，以确保镜像和升级快照能长期正确安装。

分区配置可以包含在自定义映像中，也可以方便地应用到用于生成安装介质的xref:references/seedimage-reference.adoc[种子]映像中。

请注意，所有`size` 的值都以兆字节为单位，`0` 的值将占用磁盘的剩余空间。如果`persistent` 分区未定义`size` ，则默认执行此操作。更多信息，请参阅https://github.com/rancher/elemental-toolkit/blob/main/config.yaml.example[配置示例]全文。

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: custom-partitions-iso
  namespace: fleet-default
spec:
  cloud-config:
    write_files:
    - path: /etc/elemental/config.d/partitions.yaml
      content: |
        install:
          partitions:
            recovery:
              size: 8192
            state:
              size: 16384
    - path: /etc/elemental/config.d/snapshotter.yaml
      content: |
        snapshotter:
          max-snaps: 2
  baseImage: myrepo/custom-build-iso:v1.1.1
  registrationRef:
    name: my-machine-registration
    namespace: fleet-default
----

`state` 分区将保存所有系统快照。因此，在确定分区的大小时，可以考虑以下公式：`$image_size * ($max_number_of_snapshots + 1 + 1)`.`$max_number_of_snapshots` 也可以通过自定义配置文件进行类似的配置，如上面的示例所示。

请注意，默认情况下`btrfs` 快照程序类型为`4` ，`loopdevice` 类型为`2` 。您可以通过编辑xref:references/machineregistration-reference.adoc#_config_elemental_install_snapshotter[机器注册]来配置所使用的快照器类型。由于状态分区也用于link:{elemental_toolkit_url}[{elemental_toolkit_name}]工作目录，因此最好额外留出`$image_size` 的可用空间，以便在运行升级时正确解压映像。

最后，额外的`$image_size` 可用来保留安全余量。这一点在使用`loopdevice` snapshotter 类型时尤为重要，以防较新的图像比最初安装的图像更大。相反，可以使用`btrfs` snapshotter 来节省`state` 分区的空间，或使用相同的空间来保存更多快照。

== 查找{elemental-product-name} 基本图像

使用起重机，我们可以找到以下适合扩展的 SL-Micro 图像：

[,shell]
----
$ crane catalog registry.suse.com | grep -i "suse/sl-micro"
suse/sl-micro/6.0/baremetal-iso-image
suse/sl-micro/6.0/baremetal-os-container
suse/sl-micro/6.0/base-iso-image
suse/sl-micro/6.0/base-os-container
suse/sl-micro/6.0/kvm-iso-image
suse/sl-micro/6.0/kvm-os-container
suse/sl-micro/6.0/rt-iso-image
suse/sl-micro/6.0/rt-os-container
suse/sl-micro/6.1/baremetal-iso-image
suse/sl-micro/6.1/baremetal-os-container
suse/sl-micro/6.1/base-iso-image
suse/sl-micro/6.1/base-os-container
suse/sl-micro/6.1/kvm-iso-image
suse/sl-micro/6.1/kvm-os-container
suse/sl-micro/6.1/rt-iso-image
suse/sl-micro/6.1/rt-os-container
----

后缀名为`-iso-image` 的镜像包含一个预制的 ISO 镜像和一个 busybox 系统，以便将内容复制到卷中。后缀名为`-os-container` 的图像包含一个根文件系统，可用作自定义图像的基础。