= 配置 K3s 和 RKE2 内部和外部 IP 地址
:revdate: 2025-09-08
:page-revdate: {revdate}

K3s 和 RKE2 允许通过`--node-ip` 和`--node-external-ip` 参数指定节点的内部和外部 IP 地址。

Rancher Provisioning 允许从每个节点的网络接口收集 IP 地址来填充这些参数。

无论如何，_自定义_牧场主集群和_元素_牧场主集群收集这些选项的方法是不同的。

== 在 Rancher 集群配置中配置 K3s 和 RKE2 内部和外部 IP 地址

Rancher 配置允许在 Rancher 代理部分指定应绑定到每个配置节点的内部和外部 IP 地址的网络接口。

具体做法是在`CATTLE_INTERNAL_ADDRESS` 和`CATTLE_ADDRESS` 代理环境变量（https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/rancher-agent-options#ip-address-options[参见 Rancher 文档]）中添加网络接口名称，并从中提取 IP 地址。

[NOTE]
====
`CATTLE_INTERNAL_ADDRESS` 和`CATTLE_ADDRESS` Agent 环境变量可直接填入所需的 IP 地址。总之，由于内部和外部 IP 地址都是_按节点计算的_，因此除了单节点集群外，这种方法是行不通的。
====


[CAUTION]
====
虽然在创建 Elemental Cluster 时可以添加代理环境变量，但`CATTLE_ADDRESS` 和`CATTLE_INTERNAL_ADDRESS` 会被忽略，不会导致配置节点的内部和外部 IP 地址。
====


== 在元素集群中配置 K3 和 RKE2 的内部和外部 IP 地址

Elemental 允许配置集群节点的内部和外部 IP 地址，将`elemental.cattle.io/InternalIP` 和`elemental.cattle.io/ExternalIP` 标签附加到跟踪目标节点的xref:references/machineinventory-reference.adoc[MachineInventory]资源上。

这些标签在附加到xref:references/machineinventory-reference.adoc[MachineInventory]资源时，用于填写相关节点的内部和外部 IP 地址。

可以使用xref:label-templates/label-templates-network.adoc[网络标签模板]IP 地址变量作为值，将标签添加到xref:references/machineregistration-reference.adoc[机器注册] `machineInventoryLabels` 字段中，以便收集每个节点的 IP 地址。

例如xref:references/machineregistration-reference.adoc[机器注册]，其中节点的内部 IP 地址由接口 eth0 设置，外部 IP 地址由 eth1 设置。

.registration.yaml
[,yaml]
----
include::example$labeltemplates/registration.yaml[]
----
