= SUSE Observability 支持软件包（日志）
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自助托管

== 概述

本页提供从 SUSE Observability 集群收集日志的工具和指南。这些日志对于诊断问题、找出根本原因和排除集群中可能未按预期运行的问题至关重要。
如果您的{stackstate-product-name} 集群出现意外行为、性能下降或故障，本页将帮助您收集必要的数据，以了解问题所在并采取纠正措施。在此处详细介绍的脚本旁边，还有一个活动脚本xref:/setup/install-stackstate/support-package-performance.adoc[支持包（性能）]，它将在群集和{stackstate-product-name} 上主动运行性能测量。

== 说明

该脚本应在已配置 kubectl 并可访问 SUSE Observability 群集的主机上执行，或在具有必要权限并可连接群集的任何其他主机上执行。
这可以直接在主机上使用 root 用户或通过 sudo 完成。 如果未设置 kubeconfig，请使用命令`+export KUBECONFIG=$PATH-TO-YOUR/kubeconfig+` 。

== 使用方法

需要下载该脚本，并使用`+root+` 用户或`+sudo+` 直接在主机上运行。

=== 下载并运行脚本

下载xref::attachment$suse-observability_logs_collector.sh[suse-observability_logs_collector.sh]脚本。

* 将脚本另存为 `+suse-observability_logs_collector.sh+`
* 使用以下命令运行脚本
+
[,bash]
----
bash suse-observability_logs_collector.sh
----
+
这将在当前目录下生成一个名为`+suse-observability_logs_<date>.tar.gz+` 的文件。请将此文件上传到案件中。

可以指定其他参数：
[,bash]
----
> bash suse-observability_logs_collector.sh -h
SUSE Observability support package collector.
Fetches details of a SUSE Observability instance for troubleshooting.

Usage: ./suse-observability_logs_collector.sh [options] [<namespace>]

options:
  -h  Print this help
  -e  Fetch logs for suse-observability pods from Elasticsearch
  -r  Time range for logs to fetch from Elasticsearch,
      when not specified "7d" is used

<namespace>:
  The namespace that is running SUSE Observability, or
  "suse-observability" when not specified
----

例如，当{stackstate-product-name} 部署在命名空间`+my-observability+` 时，从嵌入式 elasticsearch 收集 3 天的日志：
[,bash]
----
bash suse-observability_logs_collector.sh -e -r 3d my-observability
----
