= Volumes e armazenamento
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}
:page-aliases: storage.adoc

Ao implantar um aplicativo que precisa reter dados, você precisará criar um armazenamento persistente. O armazenamento persistente permite que você armazene dados do aplicativo fora do pod que executa o aplicativo. Essa prática de armazenamento permite que você mantenha os dados do aplicativo, mesmo que o pod do aplicativo falhe.

Um volume persistente (PV) é uma parte do armazenamento no cluster do Kubernetes, enquanto uma reivindicação de volume persistente (PVC) é uma solicitação de armazenamento. Para obter detalhes sobre como os PVs e PVCs funcionam, consulte a documentação oficial do Kubernetes sobre o https://kubernetes.io/docs/concepts/storage/volumes/[armazenamento]

O K3s, como uma distribuição compatível do Kubernetes, usa a https://github.com/container-storage-interface/spec/blob/master/spec.md[CSI (Container Storage Interface, Interface de armazenamento de contêineres)] e a https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/[] para gerenciar o armazenamento persistente.

Esta página descreve como configurar o armazenamento persistente com um provedor de armazenamento local ou com o <<_setting_up_longhorn,Longhorn.>>

[#_setting_up_the_local_storage_provider]
== Configuração do provedor de armazenamento local

O K3s é fornecido com o Local Path Provisioner do Rancher, o que permite criar reivindicações de volume persistente imediatamente, usando o armazenamento local no respectivo nó. Abaixo, apresentamos um exemplo simples. Para obter mais informações, consulte a documentação oficial https://github.com/rancher/local-path-provisioner/blob/master/README.md#usage[aqui].

Crie uma reivindicação de volume persistente com suporte do hostPath e um pod para utilizá-lo:

=== pvc.yaml

[,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
----

=== pod.yaml

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc
----

Aplique o yaml:

[,bash]
----
kubectl create -f pvc.yaml
kubectl create -f pod.yaml
----

Confirme se o PV e o PVC foram criados:

[,bash]
----
kubectl get pv
kubectl get pvc
----

O status deve ser Bound para cada um.

== Configurando o Longhorn

[CAUTION]
====
O Longhorn não oferece suporte ao ARM32.
====


O K3s é compatível com o https://github.com/longhorn/longhorn[Longhorn], um sistema de armazenamento de blocos distribuídos de código aberto para o Kubernetes.

Abaixo, apresentamos um exemplo simples. Para obter mais informações, consulte a https://documentation.suse.com/cloudnative/storage/{longhorn_docs_version}/en/longhorn-documentation.html[documentação oficial do site].

Aplique o longhorn.yaml para instalar o Longhorn:

[,bash]
----
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.8.1/deploy/longhorn.yaml
----

O Longhorn será instalado no namespace `longhorn-system`.

Crie uma reivindicação de volume persistente e um pod para utilizá-lo:

=== pvc.yaml

[,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
----

=== pod.yaml

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
----

Aplique o yaml para criar o PVC e o pod:

[,bash]
----
kubectl create -f pvc.yaml
kubectl create -f pod.yaml
----

Confirme se o PV e o PVC foram criados:

[,bash]
----
kubectl get pv
kubectl get pvc
----

O status deve ser Bound para cada um.
