include::partial$variables.adoc[]
= Rego
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Conozca los conceptos básicos del lenguaje Rego, incluido su uso junto con los marcos Open Policy Agent y Gatekeeper para implementar políticas como código.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "rego"]
:sidebar_label: Rego
:current-version: {page-origin-branch}

[NOTE]
====
La compatibilidad con Rego está disponible a partir de estas versiones:

* kwctl: v0.2.0
* servidor de políticas: v0.2.0

Las políticas de Rego admiten datos contextuales a partir de la versión {project-name} 1.9.
====


El lenguaje Rego es un lenguaje específico de dominio para hacer posibles las políticas como código.https://www.openpolicyagent.org/docs/latest/policy-language/[]Rego es un lenguaje inspirado en https://en.wikipedia.org/wiki/Datalog[] Datalog.

Existen dos formas de escribir políticas Rego para implementar políticas como código en Kubernetes, Open Policy Agent y Gatekeeper.

En las secciones siguientes se muestra cómo ambos marcos son diferentes, aunque utilicen el mismo lenguaje.
Si está más interesado en la implementación de {short-project-name}, puede visitar directamente la documentación específica del marco enlazada más abajo.

* xref:tutorials/writing-policies/rego/open-policy-agent/01-intro.adoc[Agente de Política Abierta]
* xref:tutorials/writing-policies/rego/gatekeeper/01-intro.adoc[Gatekeeper]

== Una lengua, dos marcos

=== Agente de Política Abierta (OPA)

Open Policy Agent es un proyecto que permite implementar políticas como código en cualquier proyecto.
Puede utilizar OPA para cualquier política basada en comprobar sus necesidades de aplicación.

En este contexto, escribir políticas para Kubernetes es simplemente ejercitar OPA.
Mediante el uso de webhooks de admisión de Kubernetes, es posible evaluar las solicitudes utilizando OPA, que ejecuta las políticas escritas en Rego.

OPA dispone de integración opcional con Kubernetes a través de su sidecar `kube-mgmt`.
Cuando se despliega en Kubernetes, y con el servidor OPA evaluando las políticas de Rego, es capaz de replicar los recursos Kubernetes configurados en Rego.
Así, esos recursos Kubernetes son visibles para todas las políticas.
Con OPA puedes definir políticas dentro de los objetos ConfigMap de Kubernetes.
Puede obtener más información enhttps://github.com/open-policy-agent/kube-mgmt[la página del proyecto].

=== Gatekeeper

Gatekeeper se centra, únicamente, en su uso en Kubernetes, y lo aprovecha al máximo, haciendo que los flujos de trabajo en Kubernetes sean más sencillos que en OPA en ciertos casos.

== Las diferencias

Tanto las políticas de OPA como las de Gatekeeper utilizan Rego para describir las políticas como código.
Cada solución presenta diferencias a la hora de redactar pólizas en Rego, como se muestra en las siguientes secciones.

== Punto de entrada

El punto de entrada es el nombre de una regla dentro de un paquete, y es la regla invocada por el tiempo de ejecución cuando se ejecuta la política.

== Limitaciones actuales

=== Políticas sensibles al contexto

Las políticas conscientes del contexto son políticas que no evalúan la solicitud de entrada de forma aislada.
Tienen en cuenta otros factores para tomar una decisión.
Por ejemplo, una política que evalúa recursos con espacio de nombres, y utiliza una anotación, en el espacio de nombres padre para configurar algo en la política.
Otro ejemplo sería una política que evalúa los recursos de `Ingress`, pero que para tomar una decisión dispone también de la lista de los recursos existentes en `Ingress`.

La idea de las políticas sensibles al contexto también puede extenderse a los recursos personalizados, por lo que es posible que su política también quiera evaluar una solicitud basándose en los recursos personalizados utilizados actualmente.

Tanto OPA como Gatekeeper soportan políticas contextuales a partir de la versión {short-project-name} 1.9.

xref:reference/spec/05-context-aware-policies.adoc[Aquí] encontrará más información sobre las políticas contextuales.

=== Políticas mutantes

Gatekeeper tiene soporte para políticas mutantes, pero {short-project-name} aún no ha implementado políticas mutantes compatibles con Gatekeeper.
Puede utilizar políticas que utilicen el SDK de {short-project-name} para escribir políticas mutantes, pero actualmente no puede ejecutar políticas mutantes de Gatekeeper en {short-project-name}.
