include::partial$variables.adoc[]
= Vérifier les images de la collection d'applications Rancher
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configurer les PolicyServers pour qu'ils s'authentifient auprès de Rancher Application Collection et en tirent des images à l'aide d'un Docker Config Secret.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "rancher", "installation"].
:doc-type: ["howto"]
:keywords: ["{project-name}", " rancher ", " application collection ", " appco ", " signature ", " verification ", " verify "].
:sidebar_label: Vérifier les images
:current-version: {page-origin-branch}

Cette section décrit comment vérifier les applications et les images de lahttps://apps.rancher.io/[collection d'applications] Rancher avec {project-name}.

Vous effectuez la vérification des images en déployant la politiquehttps://artifacthub.io/packages/kubewarden/verify-image-signatures/verify-image-signatures[Verify Image Signatures] et en configurant les PolicyServers pour qu'ils extraient les couches de signatures des images de la Collection d'applications.

[IMPORTANT]
====

Vous avez besoin d'un jeton d'accès ou d'une authentification de compte de service pour appliquer la collection.

====


== Authentification à Rancher Application Collection

En suivant le sitehttps://docs.apps.rancher.io/get-started/authentication/[Application Collection documentation], créez un jeton d'accès et configurez le cluster pour qu'il puise dans le registre Application Collection, avec un Docker Config Secret :

[subs="+attributes",console]
----
$ kubectl create secret docker-registry application-collection \
  --docker-server=dp.apps.rancher.io \
  --docker-username=<mymail> \
  --docker-password=<mytoken>
----

== Créer un Secret pour le PolicyServer afin qu'il puisse tirer de Rancher Application Collection

Le PolicyServer utilisé doit être configuré pour pouvoir extraire les couches d'images contenant les signatures.

Suivez le xref:/howtos/policy-servers/02-private-registry.adoc[mode d'emploi des registres privés] pour les serveurs de politiques afin de créer un Docker Config Secret *dans l'espace de noms PolicyServer*. Pour ce faire, vous instanciez un Secret avec le même contenu que le précédent `+application-collection+`.

Pour PolicyServer `+default+`, installé avec la carte `+kubewarden-defaults+` Helm sous l'espace de noms `+kubewarden+`, ce serait :

[subs="+attributes",console]
----
$ kubectl create secret docker-registry application-collection-kw -n kubewarden \
  --docker-server=dp.apps.rancher.io \
  --docker-username=<mymail> \
  --docker-password=<mytoken>
----

== Configurer les PolicyServers pour qu'ils utilisent le nouveau Secret

Si vous utilisez le PolicyServer `+default+` du tableau de bord `+kubewarden-defaults+`, configurez-le avec l'imagePullSecret `+application-collection-kw+`. Elle se situe dans le même espace de noms et s'effectue en définissant les valeurs suivantes pour le graphique :

[subs="+attributes",console]
----
$ helm upgrade -i --wait --namespace kubewarden \
  --create-namespace kubewarden-defaults kubewarden/kubewarden-defaults \
  --reuse-values \
  --set policyServer.imagePullSecret=application-collection-kw
----

Si vous utilisez d'autres PolicyServers, définissez leurxref:reference/CRDs.adoc#_policyserverspec[`+spec.imagePullSecret+`]. Le Secret doit se trouver dans le même espace de noms que le PolicyServer.

== Appliquer la politique

Vous pouvez appliquer une ClusterAdmissionPolicy en utilisant la stratégiehttps://artifacthub.io/packages/kubewarden/verify-image-signatures/verify-image-signatures[Verify Image Signatures]. Cette politique vérifie toutes les images de conteneurs à partir de`+dp.apps.rancher.io/containers/*+`. La politique soutient les registres et les artefacts de l'OCI.

Vous pouvez configurer les paramètres de la politique à l'aide de la [clé publique]https://docs.apps.rancher.io/howto-guides/verify-signatures-with-kubewarden/ de la Collection d'applications (au moment de la rédaction) dans le tableau `+pubKeys+`.

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    artifacthub/pkg: verify-image-signatures/verify-image-signatures/0.2.9
  name: check-appcollection-signatures
spec:
  backgroundAudit: true
  mode: protect
  module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.9
  mutating: true
  policyServer: default
  # On first policy call, the policy-server downloads the image layers to
  # verify the signatures. Later on it's cached. It may be useful to increase
  # this timeout:
  timeoutSeconds: 30 # default 10 seconds.
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["replicationcontrollers"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["batch"]
      apiVersions: ["v1"]
      resources: ["jobs", "cronjobs"]
      operations: ["CREATE", "UPDATE"]
  settings:
    modifyImagesWithDigest: true
    rule: PublicKey
    signatures:
      - image: dp.apps.rancher.io/containers/*
        pubKeys:
          # Note: this array constitutes an AND in validation, not an OR.
          - |-
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA02FtEt5gBywiyxbmkVsb
            CujcBg5lur0kpEbfDk10gCcs9shVEqEO3ZsOXHursgoaDAWqdPtsYhsgczGeJz9w
            Aw+r6BuRV8YOkE37A8s/7IOQUW0tlqtnt11OKhIiZ9+e5l3ed2H1ymKQO3dgreSy
            rShqYdA3hrItswyp41ApF6zhjSPlR6lAmq3X4wMYLAPptmzfxigTnR4hxB5UNPhs
            i2qA4vLrUM/i+NohECuLr1EAymvupH26HLEdM+eZnlQn+WbhIP5Grc4ba7XrBv7K
            kywgTC7CxkiJZR0mUcUD2wTX/Je8Ewj6oPSalx09e2jtzvmU5Kr9XUyMF7Zsj5CA
            IwIDAQAB
            -----END PUBLIC KEY-----
EOF
----

[subs="+attributes",console]
----
$ kubectl apply -f mypolicy.yml
$ kubectl get admissionpolicies -n default # wait for status active
----

Pour le tester, déployez un pod avec une image signée à partir de la collection d'applications :

[subs="+attributes",console]
----
$ kubectl run nginx --image [dp.apps.rancher.io/containers/nginx:1.24.0](http://dp.apps.rancher.io/containers/nginx:1.24.0) --overrides='{"spec": {"imagePullSecrets":[{"name": "application-collection"}]}}'
 pod/nginx created
----

Vous pouvez consulter les journaux de votre serveur de stratégie Pod pour vérifier que la vérification a bien eu lieu.
