include::partial$variables.adoc[]
= 创建新的网守 Rego 策略
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 通过创建和测试新策略，实施网守 Rego 策略，拒绝以默认命名空间为目标的资源。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "create-policy"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"gatekeeper rego policy"]。
:sidebar_label: 创建新政策
:current-version: {page-origin-branch}

在本教程中，你将执行与使用xref:tutorials/writing-policies/rego/open-policy-agent/02-create-policy.adoc[Open Policy Agent] 编写的策略相同的策略。
也就是说，如果资源以`default` 命名空间为目标，则拒绝该资源的策略。

[NOTE]
====
https://github.com/kubewarden/gatekeeper-policy-template[资源库模板]，可用作移植现有策略的基础。
====


== 要求

您需要以下工具：

* `opa`
* `kwctl`

== 政策

网守策略必须返回一个或多个违规对象。
如果没有违规报告，则接受申请。
如果报告了一项或多项违规行为，申请将被拒绝。

创建一个新文件夹，命名为`rego-policy` 。
在其中创建一个`policy.rego` 文件，内容如下：

[,rego]
----
package policy

violation[{"msg": msg}] {
        input.review.object.metadata.namespace == "default"
        msg := "it is forbidden to use the default namespace"
}
----

在这种情况下，入口点是`policy/violation` ，由于 Rego 的工作原理，该策略可能有以下结果：

* 返回 1 次违规：审查的对象以默认命名空间为目标。
* 返回 0 次违规：审查的对象符合政策规定。

请花点时间将此政策与 "开放式政策代理 "部分所写的政策进行比较。
那一个必须建立整个`AdmissionReview` 响应，而输入则略有不同。
在网守模式下，`AdmissionRequest` 对象带有`input.review` 属性。
`AdmissionRequest` 的所有属性都可与`object` 一起读取。

现在，您可以创建请求，以便在下一节中进行评估。

首先在`data` 目录下创建一个`default-ns.json` 文件，内容如下：

[subs="+attributes",json]
----
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
    "operation": "CREATE",
    "object": {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata": {
        "name": "nginx",
        "namespace": "default",
        "uid": "04dc7a5e-e1f1-4e34-8d65-2c9337a43e64"
      }
    }
  }
}
----

现在，创建另一个`AdmissionReview` 对象，这一次的目标命名空间与`default` 不同。
将此文件命名为`other-ns.json` 。
其内容如下

[subs="+attributes",json]
----
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
    "operation": "CREATE",
    "object": {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata": {
        "name": "nginx",
        "namespace": "other",
        "uid": "04dc7a5e-e1f1-4e34-8d65-2c9337a43e64"
      }
    }
  }
}
----

您可以看到，这模拟了另一个 pod 创建请求，这次是在名为`other` 的命名空间下。
