= Composants de l'architecture
:revdate: 2025-09-08
:page-revdate: {revdate}

Les composants nécessaires pour fournir les xref:rancher-os-management/architecture/services/architecture-services.adoc[services{elemental-product-name} ] sont les suivants :

* l'outil <<_elemental_command_line_tool,`elemental`>> outil en ligne de commande
* le <<_elemental_operator_daemon,`elemental-operator`>> démon
* l'outil <<_elemental_register_command_line_tool,`elemental-register`>> outil en ligne de commande
* le <<_elemental_system_agent_daemon,`elemental-system-agent`>> démon
* une ou plusieurs <<_suse_rancher_prime_os_manager_os_container_image,images de conteneurs du système d'exploitation{elemental-product-name} >>

== `elemental` outil de ligne de commande

L'outil `elemental` fait partie du link:{elemental_toolkit_url}[{elemental_toolkit_name}] projet.
Il effectue les opérations d'installation et de mise à niveau du système d'exploitation sur l'hôte et est utilisé pour exécuter les directives xref:references/cloud-config-reference.adoc["cloud-config"] ajoutées dans les xref:rancher-os-management/architecture/custom-resources.adoc[CRD de{elemental-product-name} ].

Le binaire `elemental` est inclus dans toutes les images de base du système d'exploitation distribuées avec {elemental-product-name}.

== `elemental-operator` démon

Le démon *elemental-operator* effectue deux tâches principales :

. intègre les contrôleurs Kubernetes de {elemental-product-name} pour gérer tous les xref:rancher-os-management/architecture/custom-resources.adoc[CRDs de{elemental-product-name} ]
. expose les _points de terminaison d'enregistrement_ pour permettre à l'hôte de s'enregistrer et de télécharger la configuration d'installation du système d'exploitation lors de l'xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[accueil de la machine.]

Le démon `elemental-operator` est déployé sur le cluster Rancher en tant que `Deployment` via le xref:references/operatorchart-reference.adoc[tableau de bord de l'opérateur{elemental-product-name} ].

== `elemental-register` outil de ligne de commande

Le binaire *elemental-register* est le client utilisé pour enregistrer l'hôte par rapport aux _points finaux d'enregistrement_ exposés par l'<<_elemental_operator_daemon,opérateur elemental>>. Il collecte et transmet les données de l'hôte pour permettre à l'<<_elemental_operator_daemon,opérateur élémentaire>> de remplir les modèles d'étiquettes SMBIOS et Matériel.

Si la phase d'enregistrement s'est déroulée avec succès, l'*opérateur élémentaire* reçoit de l'*opérateur élémentaire* la configuration complète stockée dans xref:references/machineregistration-reference.adoc[MachineRegistration].
En dernière étape, le client *elemental-register* appelle le binaire <<_elemental_command_line_tool,elemental>> en lui transmettant la configuration récupérée pour lancer l'installation du système d'exploitation.

== `elemental-system-agent` démon

Le site `elemental-system-agent` est construit à partir du https://github.com/rancher/system-agent[projet] Rancher et permet à {elemental-product-name} de déployer des _plans_ pour aider au provisionnement des hôtes.
Notamment, l'installation et la configuration de `rancher-system-agent` requises pour le xref:rancher-os-management/architecture/services/architecture-clusterdeployment.adoc[service de provisionnement de Kubernetes Cluster] sont effectuées par le biais d'un _plan_ `elemental-system-agent`.

== {elemental-product-name} Image de conteneur du système d'exploitation

Une image OS link:{elemental_toolkit_url}[{elemental_toolkit_name}] est une image de conteneur OCI contenant tous les fichiers qui constitueront le système d'exploitation de l'hôte cible. Il contient non seulement tous les binaires et les bibliothèques, mais aussi le noyau et les fichiers de démarrage nécessaires à un système linux.

L'image du système d'exploitation {elemental-product-name} est une image du système d'exploitation link:{elemental_toolkit_url}[{elemental_toolkit_name}] OS qui est basée sur https://www.suse.com/products/micro/[Micro] SLE et contient des configurations et des binaires {elemental-product-name} spécifiques (les binaires <<_elemental_command_line_tool,elemental>> et <<_elemental_register_command_line_tool,elemental-register>> ).

Les images du système d'exploitation {elemental-product-name} sont suivies dans les ressources xref:references/managedosversion-reference.adoc[ManagedOSVersions]. Les ressources xref:references/managedosversion-reference.adoc[ManagedOSVersions] sont créées dynamiquement à partir des ressources xref:references/managedosversionchannel-reference.adoc[ManagedOSVersionChannel]. Une ressource `ManagedOSVersionChannel` par défaut est déployée avec chaque installation de {elemental-product-name} Operator.
