= CĂ³mo crear y utilizar imĂ¡genes de SO personalizadas
:revdate: 2025-09-08
:page-revdate: {revdate}

== RemasterizaciĂ³n de una imagen del sistema operativo con un archivo Docker personalizado

Dado que las imĂ¡genes de SO proporcionadas por {elemental-product-name} son imĂ¡genes de contenedor, tambiĂ©n pueden utilizarse como imagen base en un Dockerfile para crear una nueva imagen de contenedor.

El proyecto Elemental publica varios sabores para las imĂ¡genes:

* baremetal: Una imagen que contiene el firmware y los controladores adecuados para el despliegue baremetal.
* rt: Basada en la imagen baremetal, pero contiene el kernel en tiempo real.
* kvm: Una imagen mĂ¡s delgada adecuada para mĂ¡quinas virtuales.
* base: El sistema base necesario para Elemental utilizado por los otros sabores.

Imagina que se necesitan algunos paquetes adicionales de un repositorio extra, el siguiente ejemplo muestra cĂ³mo se podrĂ­an aĂ±adir:

[,docker]
----
# The version of Elemental to modify.
FROM registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:latest

# Custom commands
RUN rpm --import <repo-signing-key-url> && \
    zypper addrepo --refresh <repo_url> extra_repo && \
    zypper install -y <extra_package>

# IMPORTANT: /etc/os-release is used for versioning/upgrade. The
# values here should reflect the tag of the image currently being built
ARG IMAGE_REPO=norepo
ARG IMAGE_TAG=latest
RUN \
    sed -i -e "s|^IMAGE_REPO=.*|IMAGE_REPO=\"${IMAGE_REPO}\"|g" /etc/os-release && \
    sed -i -e "s|^IMAGE_TAG=.*|IMAGE_TAG=\"${IMAGE_TAG}\"|g" /etc/os-release && \
    sed -i -e "s|^IMAGE=.*|IMAGE=\"${IMAGE_REPO}:${IMAGE_TAG}\"|g" /etc/os-release

# IMPORTANT: it is good practice to recreate the initrd and re-apply `+elemental-init+`
# command that was used in the base image. This ensures that any eventual change that should
# be synced in initrd included binaries is also applied there and consistent.
RUN elemental init --force elemental-rootfs,grub-config,dracut-config,cloud-config-essentials,elemental-setup
----

Donde `+latest+` es la versiĂ³n base que queremos personalizar.

A continuaciĂ³n, ejecute los siguientes comandos

[,bash]
----
docker build --build-arg IMAGE_REPO=myrepo/custom-build \
             --build-arg IMAGE_TAG=v1.1.1 \
             -t myrepo/custom-build:v1.1.1 .
docker push myrepo/custom-build:v1.1.1
----

El nuevo SO personalizado estĂ¡ disponible como imagen Docker `+myrepo/custom-build:v1.1.1+` y puede ejecutarse y verificarse utilizando docker con

[,bash]
----
docker run -it myrepo/custom-build:v1.1.1 bash
----

## Crear una ISO de instalaciĂ³n de arranque personalizada

{elemental-product-name} aprovecha las imĂ¡genes de contenedor para construir sus sistemas de archivos raĂ­z; por lo tanto, es posible utilizarlo en un entorno multietapa para crear medios de arranque personalizados que incluyan una imagen de contenedor personalizada.

[,docker]
----
FROM registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:latest AS os

# Check the previous section on building custom images

# The released OS already includes the toolchain for building ISOs
FROM registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:latest AS builder

ARG TARGETARCH
WORKDIR /iso
COPY --from=os / rootfs

# work around buildah issue: https://github.com/containers/buildah/issues/4242
RUN rm -f rootfs/etc/resolv.conf

RUN elemental build-iso \
        dir:rootfs \
        --bootloader-in-rootfs \
        --squash-no-compression \
        -o /output -n "elemental-${TARGETARCH}"

FROM busybox
COPY --from=builder /output /elemental-iso

ENTRYPOINT ["busybox", "sh", "-c"]
----

ConstrĂºyalo con el comando normal `+docker build+`:

[,bash]
----
docker build -t myrepo/custom-build:v1.1.1 \
              --build-arg IMAGE_REPO=myrepo/custom-build-iso \
              --build-arg IMAGE_TAG=v1.1.1 \
              .
----

La imagen de contenedor resultante es en realidad una imagen de contenedor que incluye la ISO, esta imagen de contenedor puede ser empujada a un registro OCI tambiĂ©n. La imagen ISO puede extraerse del contenedor a la carpeta actual ejecutando el contenedor como:

[,bash]
----
docker run --rm -v $(pwd):/host mytest-image "busybox cp /elemental-iso/*.iso /host"
----

Los nuevos soportes de instalaciĂ³n personalizados se encuentran en `+elemental-<arch>.iso+`.

La ejecuciĂ³n del contenedor anterior es equivalente a lo que _elemental-operator_ hace para extraer la ISO de un contenedor para construir uno nuevo incluyendo la URL de registro, por lo tanto esta es tambiĂ©n una buena marca de verificaciĂ³n para comprobar que el contenedor puede ser empujado a un registro y utilizado por _elemental-operator_ como `+baseImage+` para un recurso xref:references/seedimage-reference.adoc[SeedImage].

== Listar imĂ¡genes personalizadas como recurso ManagedOSVersion

En {elemental-product-name} listar imĂ¡genes de contenedor OS e imĂ¡genes de contenedor ISO como recursos ManagedOSVersion no es obligatorio pero sĂ­ prĂ¡ctico. Especialmente desde la perspectiva de la interfaz de usuario, esto hace que las imĂ¡genes personalizadas sean visibles y fĂ¡ciles de usar desde la extensiĂ³n {elemental-product-name} UI.

Continuando con el ejemplo de la secciĂ³n anterior, se construyĂ³ un contenedor de SO personalizado al que se hizo referencia como `+myrepo/custom-build:v1.1.1+` y que finalmente se enviĂ³ a un registro. Entonces esta imagen estĂ¡ lista para ser aĂ±adida como un recurso ManagedOSVersion con:

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  name: v1.1.1-custom-build
  namespace: fleet-default
spec:
  metadata:
    displayName: Custom build image
    upgradeImage: myrepo/custom-build:v1.1.1
  type: container
  version: v1.1.1
----

En `+type: container+` se indica que se trata de un sistema operativo contenedor. Esto hace que la imagen `+myrepo/custom-build:v1.1.1+` pueda actualizarse desde la interfaz de usuario.

Por Ăºltimo, el contenedor personalizado para la ISO `+myrepo/custom-build-iso:v1.1.1+` tambiĂ©n puede incluirse como recurso ManagedOSVersion con:

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  name: v1.1.1-custom-build-iso
  namespace: fleet-default
spec:
  metadata:
    displayName: Custom build ISO image
    uri: myrepo/custom-build-iso:v1.1.1
  type: iso
  version: v1.1.1
----

En `+type: iso+` se indica que se trata de una ISO. Esto hace que la imagen `+myrepo/custom-build-iso:v1.1.1+` sea elegible para la generaciĂ³n de SeedImages desde UI.

== TamaĂ±o de particiĂ³n personalizado

Al crear imĂ¡genes personalizadas, es importante tener en cuenta el tamaĂ±o de las particiones de disco, para garantizar que la imagen y las instantĂ¡neas de actualizaciĂ³n se ajusten correctamente a lo largo del tiempo.

La configuraciĂ³n de las particiones puede incluirse en su imagen personalizada o, alternativamente, puede aplicarse convenientemente a la xref:references/seedimage-reference.adoc[SeedImage] utilizada para generar el medio de instalaciĂ³n.

Tenga en cuenta que todos los valores de `+size+` se expresan en megabytes, y un valor de `+0+` ocuparĂ¡ el resto del disco. Este es el comportamiento por defecto de la particiĂ³n `+persistent+` si no se ha definido `+size+` para ella. Para mĂ¡s informaciĂ³n, consulte el completo https://github.com/rancher/elemental-toolkit/blob/main/config.yaml.example[ejemplo].

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: custom-partitions-iso
  namespace: fleet-default
spec:
  cloud-config:
    write_files:
    - path: /etc/elemental/config.d/partitions.yaml
      content: |
        install:
          partitions:
            recovery:
              size: 8192
            state:
              size: 16384
    - path: /etc/elemental/config.d/snapshotter.yaml
      content: |
        snapshotter:
          max-snaps: 2
  baseImage: myrepo/custom-build-iso:v1.1.1
  registrationRef:
    name: my-machine-registration
    namespace: fleet-default
----

La particiĂ³n `+state+` contendrĂ¡ todas las instantĂ¡neas del sistema. Por lo tanto, a la hora de dimensionar esta particiĂ³n, se puede considerar la siguiente fĂ³rmula: `+$image_size * ($max_number_of_snapshots + 1 + 1)+`. La direcciĂ³n `+$max_number_of_snapshots+` puede configurarse de forma similar con un archivo de configuraciĂ³n personalizado, como se muestra en el ejemplo anterior.

Tenga en cuenta que por defecto es `+4+` para el tipo de snapshotter `+btrfs+`, y `+2+` para el tipo `+loopdevice+`. Puede configurar el tipo de snapshotter en uso editando el xref:references/machineregistration-reference.adoc#_config_elemental_install_snapshotter[MachineRegistration]. Dado que la particiĂ³n de estado tambiĂ©n se utiliza para el directorio de trabajo link:{elemental_toolkit_url}[{elemental_toolkit_name}] directorio de trabajo, es mejor dejar un espacio libre adicional de `+$image_size+`, para que la imagen pueda descomprimirse correctamente, por ejemplo, al ejecutar actualizaciones.

Por Ăºltimo, se puede utilizar un espacio libre adicional de `+$image_size+` como margen de seguridad. Esto es especialmente importante cuando se utiliza el tipo de snapshotter `+loopdevice+`, en caso de que las nuevas imĂ¡genes aumenten de tamaĂ±o con respecto a la instalada originalmente. Por el contrario, el snapshotter `+btrfs+` puede utilizarse en su lugar para ahorrar espacio en la particiĂ³n `+state+`, o para utilizar el mismo espacio para guardar mĂ¡s snapshots.

== Encontrar imĂ¡genes base {elemental-product-name} 

Utilizando la grĂºa podemos encontrar las siguientes imĂ¡genes SL-Micro adecuadas para la ampliaciĂ³n:

[,shell]
----
$ crane catalog registry.suse.com | grep -i "suse/sl-micro"
suse/sl-micro/6.0/baremetal-iso-image
suse/sl-micro/6.0/baremetal-os-container
suse/sl-micro/6.0/base-iso-image
suse/sl-micro/6.0/base-os-container
suse/sl-micro/6.0/kvm-iso-image
suse/sl-micro/6.0/kvm-os-container
suse/sl-micro/6.0/rt-iso-image
suse/sl-micro/6.0/rt-os-container
suse/sl-micro/6.1/baremetal-iso-image
suse/sl-micro/6.1/baremetal-os-container
suse/sl-micro/6.1/base-iso-image
suse/sl-micro/6.1/base-os-container
suse/sl-micro/6.1/kvm-iso-image
suse/sl-micro/6.1/kvm-os-container
suse/sl-micro/6.1/rt-iso-image
suse/sl-micro/6.1/rt-os-container
----

Las imĂ¡genes con el sufijo `+-iso-image+` contienen una imagen ISO preconstruida y un sistema busybox para poder copiar el contenido a un volumen. Las imĂ¡genes con el sufijo `+-os-container+` contienen un sistema de archivos raĂ­z que puede utilizarse como base para imĂ¡genes personalizadas.