include::partial$variables.adoc[]
= Rego
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Apprenez les bases du langage Rego, y compris son utilisation en conjonction avec les cadres Open Policy Agent et Gatekeeper pour mettre en œuvre des politiques en tant que code.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["politiques d'écriture", "rego", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "rego"]
:sidebar_label: Rego
:current-version: {page-origin-branch}

[NOTE]
====
Le soutien de Rego est disponible à partir de ces versions :

* kwctl : v0.2.0
* serveur de politique : v0.2.0

Les politiques de Rego prennent en charge les données contextuelles à partir de la version 1.9 de {project-name}.
====


Le langage Rego est un langage spécifique à un domaine qui permet d'élaborer des politiques sous forme de code.https://www.openpolicyagent.org/docs/latest/policy-language/[Rego]est un langage inspiré de https://en.wikipedia.org/wiki/Datalog[Datalog].

Il existe deux façons d'écrire des politiques Rego pour mettre en œuvre des politiques sous forme de code dans Kubernetes, Open Policy Agent et Gatekeeper.

Les deux sections suivantes montrent comment les deux cadres sont différents, même s'ils utilisent le même langage.
Si vous êtes plus intéressé par l'implémentation de {short-project-name}, vous pouvez directement consulter la documentation spécifique au cadre de travail dont le lien figure ci-dessous.

* xref:tutorials/writing-policies/rego/open-policy-agent/01-intro.adoc[Agent de la politique ouverte]
* xref:tutorials/writing-policies/rego/gatekeeper/01-intro.adoc[Gatekeeper]

== Une langue, deux cadres

=== Agent de politique ouverte (OPA)

Open Policy Agent est un projet qui vous permet de mettre en œuvre des politiques sous forme de code dans n'importe quel projet.
Vous pouvez utiliser l'OPA pour n'importe quelle politique en fonction des besoins de votre application.

Dans ce contexte, écrire des politiques pour Kubernetes revient simplement à exercer l'OPA.
En utilisant les webhooks d'admission de Kubernetes, il est possible d'évaluer les demandes à l'aide d'OPA, qui exécute les politiques écrites dans Rego.

OPA dispose d'une intégration optionnelle avec Kubernetes via son sidecar `kube-mgmt`.
Lorsqu'il est déployé sur Kubernetes et que le serveur OPA évalue les politiques Rego, il est en mesure de répliquer les ressources Kubernetes configurées dans Rego.
Ainsi, ces ressources Kubernetes sont visibles par toutes les politiques.
Avec OPA, vous pouvez définir des politiques à l'intérieur des objets ConfigMap de Kubernetes.
Pour en savoir plus, consultezhttps://github.com/open-policy-agent/kube-mgmt[la page du projet sur].

=== Gatekeeper

Gatekeeper se concentre, uniquement, sur l'utilisation dans Kubernetes, et en tire parti autant que possible, rendant les flux de travail Kubernetes plus faciles que l'OPA dans certains cas.

== Examiner les différences

Les politiques OPA et Gatekeeper utilisent Rego pour décrire les politiques en tant que code.
Chaque solution présente des différences lorsqu'il s'agit de rédiger des politiques en Rego, comme le montrent les sections suivantes.

== Point d'entrée

Le point d'entrée est le nom d'une règle au sein d'un paquet et est la règle invoquée par le moteur d'exécution lorsque la politique s'exécute.

== Limites actuelles

=== Politiques tenant compte du contexte

Les politiques tenant compte du contexte sont des politiques qui n'évaluent pas la demande d'entrée de manière isolée.
Ils prennent en compte d'autres facteurs pour prendre une décision.
Par exemple, une politique qui évalue les ressources à espace de noms et utilise une annotation sur l'espace de noms parent pour configurer quelque chose dans la politique.
Un autre exemple serait une politique qui évalue les ressources `Ingress`, mais qui, pour prendre une décision, dispose également de la liste des ressources `Ingress` existantes.

L'idée de politiques tenant compte du contexte peut également s'étendre aux ressources personnalisées, de sorte que votre politique peut également vouloir évaluer une demande sur la base des ressources personnalisées actuellement utilisées.

OPA et Gatekeeper supportent tous deux les politiques contextuelles, à partir de la version 1.9 de {short-project-name}.

Pour en savoir plus sur les politiques contextuelles,xref:reference/spec/05-context-aware-policies.adoc[cliquez ici.]

=== Mutation des politiques

Gatekeeper prend en charge les politiques de mutation, mais {short-project-name} n'a pas encore mis en œuvre de politiques de mutation compatibles avec Gatekeeper.
Vous pouvez utiliser des politiques qui utilisent le SDK {short-project-name} pour écrire des politiques de mutation, mais actuellement, vous ne pouvez pas exécuter les politiques de mutation de Gatekeeper dans {short-project-name}.
