= Registros do Kubernetes
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted v5.1.x

== Visão geral

Em uma configuração do Kubernetes, as funções do SUSE Observability são distribuídas em diferentes pods e os registros de cada função são armazenados por pod e contêiner. Você pode acessar os registros recentes usando `kubectl`, embora, para armazenamento de longo prazo, seja recomendável configurar a agregação de registros.

== Pods do Kubernetes para registro em log

Os logs do SUSE Observability são armazenados por pod e contêiner. A tabela abaixo mostra o pod para acessar os registros relacionados a funções específicas do SUSE Observability. Observe que os nomes reais dos pods incluirão um número ou um sufixo de cadeia aleatória (por exemplo, `stackstate-receiver-5b9d79db86-h2hkz`) e também poderão incluir o nome da versão especificado quando o SUSE Observability foi implantado como um prefixo.

[NOTE]
====
Observe que os registros armazenados nos pods serão removidos regularmente. Para obter acesso de longo prazo aos registros, é recomendável configurar <<_log_aggregation,a agregação de registros>> para o seu cluster do Kubernetes.
====


|===
| Função de observabilidade do SUSE | Registros no pod

| API (incluindo topologia, gráficos e configurações)
| `stackstate-api`

| Indexação de dados no Elasticsearch
| `stackstate-e2es` (eventos)

| Ingestão de dados
| `stackstate-receiver`

| Manipuladores de eventos
| `stackstate-view-health`

| Monitor
| `stackstate-checks`

| Propagação de estado
| `stackstate-state`

| Sincronização
| `stackstate-sync`

| Visualizar o estado de saúde
| `stackstate-view-health`
|===

Você pode acessar os registros em um pod específico usando o comando `kubectl logs`.

Por exemplo:

[,sh]
----
$ kubectl logs stackstate-api-0
----

== Acesse os registros recentes

=== Logs de cápsulas ou contêineres

Os registros mais recentes podem ser recuperados do Kubernetes usando o comando `kubectl logs`. Marque o <<_kubernetes_pods_for_logging,pod que você precisa monitorar>> para recuperar um registro específico.

Por exemplo:

[,sh]
----
# Snapshot of logs for all containers of <pod-name>
$ kubectl logs <pod-name> --all-containers=true

# Stream logs for all containers of <pod-name>
$ kubectl logs -f <pod-name> --all-containers=true

# Snapshot of logs for a specific container of <pod-name>
$ kubectl logs -c <container-name> <pod-name>

# Snapshot of logs for previous terminated container of <pod-name>
$ kubectl logs -p -c <container-name> <pod-name>
----

=== Registros de sincronização

Todos os registros de sincronização podem ser encontrados em um pod `stackstate-sync-<suffix>`. É possível usar o nome da sincronização para localizar informações de registro específicas em um instantâneo de registro.

Por exemplo:

[,sh]
----
# Logs of the synchronization for a specific Kubernetes cluster
$ kubectl logs stackstate-sync-0 | grep "Kubernetes - \<cluster-name\>"

# Logs of the Agent synchronization
$ kubectl logs stackstate-sync-0 | grep "Agent"
----

== Agregação de registros

Para o armazenamento de longo prazo dos dados de registro do SUSE Observability, é recomendável configurar a agregação de registros no cluster do Kubernetes. Isso pode ser feito usando um sistema de terceiros para armazenamento, como Elasticsearch, Splunk ou Logz.io, e um expedidor de registros, como Logstash ou Fluentd.

Para obter mais detalhes sobre como isso pode ser feito, consulte:

* Envio de registros com https://docs.fluentd.org/container-deployment/kubernetes[Fluentd (fluentd.org)]
* Uma visão geral completa da configuração da https://docs.bitnami.com/tutorials/integrate-logging-kubernetes-kibana-elasticsearch-fluentd/[agregação de registros do]

== Veja também

* https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands[Referência do comando kubectl (kubernetes.io/docs)]
