= Uso da CLI para associações de métricas
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

Você pode usar a CLI do {stackstate-product-name} para inspecionar e modificar as ligações métricas.  Elas são tratadas como outras configurações usando o comando `sts settings`.

== Inspeção de fixações métricas

=== Listagem de fixações métricas

O comando `sts settings` pode listar todos os vínculos de métrica:

[,bash]
----
sts settings list --type MetricBinding
TYPE          | ID              | IDENTIFIER         | NAME               | OWNED BY           | LAST UPDATED
MetricBinding | 190567588459765 | urn:stackpack:kube | .NET GC Allocated  | urn:stackpack:kube | Sun Jan 11 01:28:2
              |                 | rnetes-v2:shared:m |                    | rnetes-v2:shared   | 8 2026 CET
              |                 | etric-binding:pod: |                    |                    |
              |                 | dotnet-gc-allocate |                    |                    |
              |                 | d                  |                    |                    |
MetricBinding | 247972504900226 | urn:stackpack:kube | .NET GC Allocated  | urn:stackpack:kube | Sun Jan 11 01:28:2
              |                 | rnetes-v2:shared:m |                    | rnetes-v2:shared   | 8 2026 CET
              |                 | etric-binding:depl |                    |                    |
              |                 | oyment:dotnet-gc-a |                    |                    |
              |                 | llocated           |                    |                    |
MetricBinding | 109239589408271 | urn:stackpack:open | .NET GC Allocated  | urn:stackpack:open | Wed Jan 7 00:20:48
              |                 | -telemetry:shared: |                    | -telemetry:shared  |  2026 CET
              |                 | metric-binding:ser |                    |                    |
              |                 | vice:dotnet-gc-all |                    |                    |
              |                 | ocated             |                    |                    |
...
----

=== Descrevendo ligações métricas

Você pode obter a definição de uma ligação métrica existente usando o comando `describe`:

[,bash]
----
sts settings describe --ids 190567588459765
_version: 1.0.93
nodes:
- _type: MetricBinding
  chartType: line
  description: Bytes allocated to GC Heap
  enabled: true
  id: -1
  identifier: urn:stackpack:kubernetes-v2:shared:metric-binding:pod:dotnet-gc-allocated
  layout:
    metricPerspective:
      section: GC
      tab: .NET
      weight: 3
  name: .NET GC Allocated
  priority: high
  queries:
  - alias: allocated
    expression: rate(process_runtime_dotnet_gc_allocations_size_bytes_total{k8s_cluster_name="${tags.cluster-name}", k8s_namespace_name="${tags.namespace}", k8s_pod_name="${name}"}[${__rate_interval}])
  scope: (label = "stackpack:kubernetes" and type = "pod")
  unit: bytes(IEC)
timestamp: 2026-01-14T13:11:07.575662922Z[Etc/UTC]
----

== Modificação de vínculos métricos

[NOTE]
====
A maneira recomendada de trabalhar é armazenar as ligações métricas (e quaisquer outros recursos personalizados criados em {stackstate-product-name}) como arquivos YAML em xref:/setup/custom-integrations/overview.adoc[um StackPack]. A partir daí, as alterações podem ser aplicadas manualmente ou podem ser totalmente automatizadas usando a CLI do SUSE Observability em um sistema de CI/CD, como ações do GitHub ou pipelines do GitLab.
====

=== Criar/atualizar um Metric Binding
Crie um arquivo `metric-bindings.yaml` com a seguinte aparência:

[source,bash]
----
nodes:
- _type: MetricBinding
  chartType: line
  enabled: true
  tags: {}
  unit: short
  name: Replica counts
  priority: MEDIUM
  identifier: urn:stackpack:my-stackpack:metric-binding:my-deployment-replica-counts
  queries:
    - expression: max_over_time(kubernetes_state_deployment_replicas{cluster_name="${tags.cluster-name}", namespace="${tags.namespace}", deployment="${name}"}[${__interval}])
      alias: Total replicas
  scope: type = "deployment" and label = "stackpack:kubernetes"
----

Use a xref:/setup/cli/cli-sts.adoc[CLI do SUSE Observability] para criar a associação de métricas:

[,bash]
----
sts settings apply -f metric-bindings.yaml
----

Verifique os resultados no SUSE Observability abrindo a perspectiva de métricas para uma implantação. Se você não estiver satisfeito com o resultado, basta alterar a vinculação da métrica no arquivo YAML e executar o comando novamente para atualizá-lo. A lista de nós permite adicionar muitos vínculos métricos. Basta adicionar outra entrada de vinculação métrica à matriz YAML usando as mesmas etapas anteriores.

[CAUTION]
====
O identificador é usado como a chave exclusiva de uma ligação métrica. A alteração do identificador criará uma nova ligação métrica em vez de atualizar a existente.
====

=== Excluir uma vinculação de métrica

Por fim, para excluir uma ligação métrica, use

[,bash]
----
sts settings delete --ids <id>
----

O `<id>` nesse comando não é o identificador, mas o número na coluna `Id` da saída `sts settings list`.

