ifdef::ss-ff-stackpacks2_enabled[]
= メトリックバインディングのスキーマとリファレンス
:revdate: 2026-01-09
:page-revdate: {revdate}
:description: SUSE Observability

== 概要

このページでは、`+MetricBinding+` のスキーマを、構成要素、式の構文、セマンティクスの詳細な説明とともに説明します。

== メトリックバインディングのスキーマ

各メトリックバインディング：

* 適用可能なコンポーネントを選択する
* データを取得するためのPromQLクエリー・テンプレートを定義する
* 結果のデータをどのようにレンダリングするかを指定する。
* UI内でチャートを表示する適切な場所を選択するためのレイアウトヒントを含む。

[,yaml]
----
_type: "MetricBinding"
name: string
chartType: "line"                     # "line" is the only type for now
unit?: string
scope: string                         # Topology scope - components to bind to
enabled: boolean                      # default: true
description?: string
valuation?: "higher-is-better" | "lower-is-better"
priority?: "HIGH" | "MEDIUM" | "LOW" | "NONE"    # deprecated
queries:
  - _type: "MetricBindingQuery"
    expression: string                # promql query
    alias: string                     # name in legend
    componentIdentifierTemplate?: string    # URN template for linking
    primary?: boolean                 # is this query the primary one
tags:
  <key>: <value>
layout?:                              # where should chart be shown
  metricPerspective?:                 # the metrics perspective for a component
    tab: string
    section: string
    weight?: integer
  componentHighlight?:                # highlight perspective of a component
    section: string
    weight?: integer
  componentSummary?:                  # summary - supporting panel on the right
    weight?: integer
identifier?: string
----

* `+_type+`{stackstate-product-name} は、このバインディングがメトリックバインディングであることを知る必要がある。 `+MetricBinding+`
* `+name+`:メトリックバインディングの名前
* `+chartType+`:{stackstate-product-name} は、異なるチャート・タイプ（`+line+` 、`+bar+` など）をサポートする。現在サポートされているのは`+line+` のみ。
* `+unit+`:チャートのY軸を表示するために使用される、クエリまたはクエリによって返される時系列の値の単位。すべてのユニットについては、xref:/develop/reference/k8sTs-chart-units.adoc[サポートされているユニットの]リファレンスを参照してください。
* `+scope+`:このメトリックバインディングが表示されるコンポーネントを選択するトポロジークエリ。
* `+enabled+`:`+false+` に設定すると、メトリックのバインディングは維持されるが、ユーザーには表示されない。
* `+description+`:名前の上に表示される説明文（オプション
* `+valuation+`:数値が高い方が "良い "のか、低い方が "良い "のか
* `+priority+`:[非推奨]`+HIGH+`,`+MEDIUM+`,`+LOW+` のいずれか。コンポーネントのメトリクスの主なソート順（ここに記載されている順）。副次的なソート順は`+name+` 。
* `+queries+`:メトリックバインディングのチャートに表示するクエリのリスト (xref:/setup/custom-integrations/metric-bindings/writing-promql.adoc[PromQL クエリの記述] を参照)
** `+expression+`:テンプレート化された）promqlクエリ
** `+alias+`:凡例におけるクエリの名前
** `+componentIdentifierTemplate+`:関連するコンポーネントの識別子のテンプレートで、クエリの結果得られたタイムスケリーのラベルが入力される。
** `+primary+`:このクエリは主要なものですか？
* `+tags+`:ユーザー・インターフェイスでメトリクスを整理するために使用されます。 `+{}+`
* `+layout+`:異なるパースペクティブ・ビュー（例：xref:/use/views/k8s-metrics-perspective.adoc[メトリクス・パースペクティブ]）でチャートをグループ化する方法
** `+metricPerspective+` -`+Metrics Perspective+` に表示するメトリクスを定義する。指標はタブとセクションに分類される。
*** `+tab+` - タブ名。タブはアルファベット順にソートされる
*** `+section+` - セクション名セクションはアルファベット順に並んでいる
*** `+weight+` - セクション内の指標は、主に重み（昇順）、次に名前（アルファベット順）でソートされる。
** `+componentHighlight+` -`+Component Highlight+` に表示するメトリクスを定義する。指標はセクションごとに分類されている。
*** `+section+` - セクション名セクションはアルファベット順に並んでいる
*** `+weight+` - セクション内の指標は、主に重み（昇順）、次に名前（アルファベット順）でソートされる。
** `+componentSummary+` - コンポーネント選択時に`+Components details+` サイドバーに表示するメトリクスを指定します。チャートは、このプロパティが定義されている場合にのみ表示される。
*** `+weight+` - これはチャートの重さを表している。チャートは重量の昇順にソートされ、最初の3つのチャートが表示される。
* `+identifier+`:メトリックバインディングの一意な識別子として使われるURN（ユニバーサルリソース識別子）。それは`+urn:stackpack:<stackpack-name>:metric-binding:+` で始まらなければならない。残りの部分は、すべてのメートル法バインディングの中でユニークである限り、フリーフォーマットである。

endif::ss-ff-stackpacks2_enabled[]
