= Onboarding von Maschinen
:revdate: 2025-11-06
:page-revdate: {revdate}

Das Ziel des Machine Onboarding Service ist es, eine neue Maschine im {elemental-product-name} Operator-Katalogxref:references/machineinventory-reference.adoc[(MachineInventory-Ressourcen] ) zu registrieren und den Host mit dem Betriebssystem zu versorgen, indem die gewünschte Konfiguration angewendet wird.

Das Machine Onboarding umfasst die folgenden Schritte:

* Der Benutzer erstellt eine xref:references/machineregistration-reference.adoc[MachineRegistration-Ressource]: Die MachineRegistration enthält die für die Betriebssysteminstallation erforderliche Konfiguration.
Sobald die MachineRegistration erstellt ist, stellt der {elemental-product-name} Operator einen _HTTP-Registrierungsendpunkt_ zur Verfügung: Dies ist der Einstiegspunkt, der von den Onboarding-Hosts benötigt wird, um sich beim Operator zu registrieren.
* Der Benutzer fordert ein selbstinstallierendes Abbild über eine xref:references/seedimage-reference.adoc[SeedImage-Ressource] an: Er benötigt lediglich einen Verweis auf eine MachineRegistration-Ressource und auf ein mit dem {elemental-product-name} Toolkit kompatibles Betriebssystem-Container-Abbild.
Sobald das SeedImage erstellt ist, stößt der {elemental-product-name} Operator den Build-Prozess der selbstinstallierenden image: once completed, the URL is exposed in the `+status.downloadURL+` field of the xref:references/seedimage-reference.adoc[SeedImage-Ressource] an.
* Der Benutzer lädt das selbstinstallierende Image herunter und verwendet es zum Booten eines unprovisionierten Hosts: Der Host https://documentation.suse.com/cloudnative/os-manager/latest/en/rancher-os-management/authentication.html[authentifiziert sich] beim _Registrierungsendpunkt_ des {elemental-product-name} Operators, erhält die vollständige Konfiguration, die in der MachineRegistration gespeichert ist, und installiert das Betriebssystem auf dem lokalen Speichergerät. Sobald der Host den Registrierungsprozess abgeschlossen hat, erstellt der {elemental-product-name} Operator eine eindeutige xref:references/machineinventory-reference.adoc[MachineInventory-Ressource] zur Verfolgung des Hosts.
Das selbstinstallierende Image kann zum Einbinden einer beliebigen Anzahl von Hosts verwendet werden.
