= Mises à jour automatisées
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-16
:page-revdate: {revdate}

== Vue d'ensemble

Vous pouvez gérer les mises à jour des clusters K3s à l'aide du contrôleur de mise à jour du système de Rancher. Il s'agit d'une approche native de Kubernetes pour les mises à niveau de clusters. Il s'appuie sur une https://github.com/rancher/system-upgrade-controller/blob/master/doc/plan.md#planspec[`+Plan+`] Custom Resource pour décrire de manière déclarative les nœuds à mettre à niveau et leur version.

Le plan définit les politiques et les exigences en matière de mise à niveau. Il définit également les nœuds qui doivent être mis à niveau au moyen d'un https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[sélecteur d'étiquettes (]. Voir ci-dessous les plans avec les valeurs par défaut appropriées pour la mise à niveau d'un cluster K3s. Pour des options de configuration de plan plus avancées, voir la documentation sur le plan dont le lien figure ci-dessus.

Le contrôleur de mise à niveau du système planifie les mises à niveau en surveillant les plans et en sélectionnant les nœuds sur lesquels exécuter les mise à niveau https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/[tâches de]. Lorsqu'un travail a été exécuté avec succès, le contrôleur étiquette le nœud sur lequel il a été exécuté en conséquence.

[WARNING]
====
Si le cluster K3s est géré par Rancher, vous devez utiliser l'interface utilisateur de Rancher pour gérer les mises à jour.

* Si le cluster K3s est importé (enregistré) dans Rancher, Rancher gère par défaut le déploiement et les plans du contrôleur de mise à niveau du système. Ne suivez pas les étapes de cette page si vous n'avez pas désactivé la gestion des versions dans Rancher.
  Voir https://rancher.github.io/product-docs-playbook/rancher-manager/latest/en/cluster-deployment/register-existing-clusters.html#_configuring_version_management_for_suse_rancher_prime_rke2_and_suse_rancher_prime_k3s_clusters[Configuring Version Management for RKE2 and K3s Clusters] pour plus d'informations.
* Si le cluster K3s est provisionné par Rancher, Rancher utilise l'agent système pour gérer les mises à jour de version. Ne suivez pas les étapes de cette page.
* Si le cluster K3s *n'* est *pas* géré par Rancher, vous pouvez suivre les étapes ci-dessous.
====

== Utilisation du contrôleur de mise à niveau du système

Pour automatiser les mises à niveau, vous devez procéder comme suit :

. Installer le contrôleur de mise à niveau du système dans votre cluster
. Créer des plans décrivant les groupes de nœuds à mettre à niveau et la manière de le faire.

Pour plus de détails sur la conception et l'architecture du contrôleur de mise à niveau du système ou son intégration avec K3s, voir les dépôts Git suivants :

* https://github.com/rancher/system-upgrade-controller[contrôleur de mise à niveau du système]
* https://github.com/k3s-io/k3s-upgrade[k3s-upgrade]

[TIP]
====
Lors d'une tentative de mise à niveau vers une nouvelle version de K3s, la https://kubernetes.io/docs/setup/release/version-skew-policy/[politique] Kubernetes s'applique. Veillez à ce que votre plan ne saute pas les versions mineures intermédiaires lors de la mise à niveau. Le contrôleur de mise à niveau du système lui-même ne protège pas contre les modifications non prises en charge de la version de Kubernetes.
====


=== Installation

Le manifeste system-upgrade-controller installe une définition de ressource personnalisée, un déploiement, un compte de service, une liaison de rôle de cluster et une carte de configuration. Pour installer ces composants, exécutez la commande suivante :

[,bash]
----
kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/latest/download/crd.yaml -f https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
----

Le contrôleur peut être configuré et personnalisé via le configmap mentionné précédemment, mais le pod du contrôleur doit être supprimé pour que les changements soient appliqués.

=== Configuration

Les nœuds de serveur doivent toujours être mis à niveau avant les nœuds d'agent. C'est pourquoi il est recommandé de créer au moins deux plans : un plan de mise à niveau des nœuds de serveur (plan de contrôle) et un plan de mise à niveau des nœuds d'agent. Vous pouvez créer des plans supplémentaires si nécessaire pour contrôler le déploiement de la mise à niveau sur les nœuds. Une fois les plans créés, le contrôleur les récupère et commence à mettre à niveau votre cluster. 

Les deux exemples de plans suivants maintiennent continuellement votre cluster à jour avec la version stable actuelle, en ciblant le xref:upgrades/manual.adoc#_release_channels[canal de la version] stable :

[,yaml]
----
# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
----

Il y a quelques points importants à souligner en ce qui concerne ces plans :

. Les plans doivent être créés dans le même espace de noms que celui dans lequel le contrôleur est déployé.
. Le champ `+concurrency+` indique le nombre de nœuds pouvant être mis à niveau simultanément. 
. Le plan de serveur cible les nœuds de serveur en spécifiant un sélecteur d'étiquettes qui sélectionne les nœuds portant l'étiquette `+node-role.kubernetes.io/control-plane+`. Le plan-agent cible les nœuds de l'agent en spécifiant un sélecteur d'étiquette qui sélectionne les nœuds sans cette étiquette.
. L'étape `+prepare+` du plan d'agent fait en sorte que les tâches de mise à niveau de ce plan attendent la fin du plan du serveur avant de s'exécuter. Cette logique est intégrée dans l'image utilisée pour l'étape de préparation et ne fait pas partie du contrôleur de mise à niveau du système lui-même.
. Dans les deux plans, le champ `+channel+` correspond à l'URL du canal de la version stable. Le contrôleur surveille alors cette URL et met à jour la grappe chaque fois qu'elle passe à une nouvelle version. Cela fonctionne bien avec les xref:upgrades/manual.adoc#_release_channels[canaux de libération]. Ainsi, vous pouvez configurer vos plans avec le canal suivant pour vous assurer que votre cluster est toujours automatiquement mis à niveau vers la dernière version stable de K3s. Vous pouvez également omettre le champ `+channel+` et définir le champ `+version+` en fonction d'une version spécifique de K3s :
+
[,yaml]
----
apiVersion: upgrade.cattle.io/v1
kind: Plan
# ...
spec:
  # ...
  version: v1.33.4+k3s1
----

La mise à niveau commence dès que le contrôleur détecte que la version cible d'un plan a été résolue, soit à partir du champ de la version, soit en interrogeant le serveur de canaux. La modification d'un plan amène le contrôleur à réévaluer le plan et à déterminer si une autre mise à niveau est nécessaire. Si un canal a été configuré, l'URL est également interrogée périodiquement pour vérifier la présence de nouvelles versions.

Vous pouvez surveiller la progression d'une mise à niveau en affichant le plan et les tâches via kubectl :

[,bash]
----
kubectl -n system-upgrade get plans -o wide
kubectl -n system-upgrade get jobs
----

=== Programmation des mises à niveau

Les plans peuvent être limités à une fenêtre temporelle spécifique en définissant le champ `+window+` dans les spécifications du plan. Les champs de la fenêtre temporelle sont compatibles avec les https://kured.dev/docs/configuration/#setting-a-schedule[options de calendrier] kured et prennent le même format. Par exemple :

[,yaml]
----
apiVersion: upgrade.cattle.io/v1
kind: Plan
# ...
spec:
  # ...
  window:
    days:
      - monday
      - tuesday
      - wednesday
      - thursday
      - friday
    startTime: 19:00
    endTime: 21:00
    timeZone: UTC
----

Les tâches visant à exécuter les mises à niveau d'un plan ne sont pas créées en dehors de la fenêtre temporelle. Une fois les travaux créés, les plans peuvent continuer à être exécutés après la fermeture de la fenêtre.

== Prévention du déclassement

[IMPORTANT]
.Version Gate
====
A partir des versions 2023-07 (https://github.com/k3s-io/k3s-upgrade/releases/tag/v1.27.4%2Bk3s1[v1.27.4+k3s1], https://github.com/k3s-io/k3s-upgrade/releases/tag/v1.26.7%2Bk3s1[.26.7+k3s1] v1, https://github.com/k3s-io/k3s-upgrade/releases/tag/v1.25.12%2Bk3s1[.25.12+k3s1] v1, https://github.com/k3s-io/k3s-upgrade/releases/tag/v1.24.16%2Bk3s1[.24.16+k3s1] v1)
====


Kubernetes ne prend pas en charge les rétrogradations des composants du plan de contrôle. L'image k3s-upgrade utilisée par les plans de mise à niveau refusera de rétrograder les K3, ce qui entraînera l'échec du plan. Les nœuds pour lesquels `+cordon: true+` est configuré dans leur plan resteront isolés après la panne.

Voici un exemple de cluster, avec des pods de mise à niveau défaillants et des nœuds isolés :

[,console]
----
$ kubectl get pods -n system-upgrade
NAME                                                              READY   STATUS    RESTARTS   AGE
apply-k3s-server-on-ip-172-31-0-16-with-7af95590a5af8e8c3-2cdc6   0/1     Error     0          9m25s
apply-k3s-server-on-ip-172-31-10-23-with-7af95590a5af8e8c-9xvwg   0/1     Error     0          14m
apply-k3s-server-on-ip-172-31-13-213-with-7af95590a5af8e8-8j72v   0/1     Error     0          18m
system-upgrade-controller-7c4b84d5d9-kkzr6                        1/1     Running   0          20m
$ kubectl get nodes
NAME               STATUS                     ROLES                       AGE   VERSION
ip-172-31-0-16     Ready,SchedulingDisabled   control-plane,etcd,master   19h   v1.27.4+k3s1
ip-172-31-10-23    Ready,SchedulingDisabled   control-plane,etcd,master   19h   v1.27.4+k3s1
ip-172-31-13-213   Ready,SchedulingDisabled   control-plane,etcd,master   19h   v1.27.4+k3s1
ip-172-31-2-13     Ready                      <none>                      19h   v1.27.4+k3s1
----

Vous pouvez remettre en service vos nœuds isolés en utilisant l'une des méthodes suivantes :

* Modifiez la version ou le canal de votre plan pour cibler une version identique ou plus récente que celle qui est actuellement en cours d'exécution sur le cluster, afin que le plan réussisse.
* Supprimez le plan et déconnectez manuellement les nœuds.
Utilisez `+kubectl get plan -n system-upgrade+` pour trouver le nom du plan, puis `+kubectl delete plan -n system-upgrade PLAN_NAME+` pour le supprimer. Une fois le plan supprimé, utilisez `+kubectl uncordon NODE_NAME+` pour déconnecter chacun des nœuds.

== Sécurité

La tâche de mise à niveau lancée doit bénéficier de privilèges élevés pour pouvoir modifier les nœuds sous-jacents. Par défaut, il est configuré avec les éléments suivants :

* Hôte `+IPC+`, `+NET+`, et `+PID+` espaces de noms
* La capacité `+CAP_SYS_BOOT+` 
* La racine de l'hôte est montée sur `+/host+` avec des autorisations de lecture et d'écriture.
