= Améliorations
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

== Mise à niveau de votre cluster K3s

Les xref:upgrades/manual.adoc[mises à niveau manuelles] décrivent plusieurs techniques de mise à niveau manuelle de votre cluster. Il peut également servir de base à la mise à niveau au moyen d'outils tiers d'infrastructure en tant que code, tels que https://www.terraform.io/[Terraform].

xref:upgrades/automated.adoc[Automated Upgrades] décrit comment effectuer des mises à niveau automatisées natives de Kubernetes à l'aide du https://github.com/rancher/system-upgrade-controller[contrôleur de mise à niveau du système] de Rancher.

== Mises en garde spécifiques à une version

* *Traefik :* Si Traefik n'est pas désactivé, les versions 1.20 et antérieures de K3s installeront Traefik v1, tandis que les versions 1.21 et ultérieures installeront Traefik v2, si v1 n'est pas déjà présent. Pour passer de l'ancien Traefik v1 à Traefik v2, veuillez vous référer à la https://doc.traefik.io/traefik/migrate/v1-to-v2/[documentation de] et utiliser l' https://github.com/traefik/traefik-migration-tool[Traefik].
* *Données d'amorçage K3s :* Si vous utilisez K3s dans une configuration HA avec un datastore SQL externe, et que vos nœuds serveurs (control-plane) n'ont pas été démarrés avec le drapeau CLI `+--token+`, vous ne pourrez plus ajouter de serveurs K3s supplémentaires au cluster sans spécifier le token. Veillez à conserver une copie de ce jeton, car il est nécessaire lors de la restauration à partir d'une sauvegarde. Auparavant, K3s n'imposait pas l'utilisation d'un jeton lors de l'utilisation de datastores SQL externes.
 ** Les versions concernées sont <= v1.19.12+k3s1, v1.20.8+k3s1, v1.21.2+k3s1 ; les versions corrigées sont v1.19.13+k3s1, v1.20.9+k3s1, v1.21.3+k3s1.
 ** Vous pouvez récupérer la valeur du jeton à partir de n'importe quel serveur déjà joint au cluster de la manière suivante :
+
[,bash]
----
cat /var/lib/rancher/k3s/server/token
----
