include::partial$variables.adoc[]
= Especificación de las capacidades del host
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Durante la evaluación, comprenda las capacidades de host que ofrece el entorno para las políticas de {project-name}.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "introduction"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "especificación de políticas", "capacidades de host"]
:sidebar_label: Especificación de las capacidades del host
:current-version: {page-origin-branch}

Durante la evaluación, las políticas de {project-name} pueden acceder a capacidades adicionales ofrecidas por el entorno anfitrión.
Este mecanismo utiliza un enfoque similar al RPC tradicionalhttps://en.wikipedia.org/wiki/Remote_procedure_call[de].

Esto es lo que ocurre cuando una política {short-project-name} emite una solicitud:

* {short-project-name} política:
 ** Invoca la capacidad ofrecida por el entorno anfitrión.
 ** La invocación es una operación de bloqueo, por lo que el código de la política esperará hasta que el host proporcione una respuesta.
* Entorno de acogida:
 ** Se recibe una invocación de capacidad.
 ** El host realiza la operación.
 ** El anfitrión proporciona una respuesta a la política, que puede ser un éxito o un fracaso.
* {short-project-name} política:
 ** El código recibe la respuesta del host y reanuda la ejecución.
 ** La respuesta del host se gestiona en consecuencia.

La función de capacidades de host se implementa utilizandohttps://wapc.io/[waPC].
Cada capacidad utiliza estos detalles:

* waPC nombre de la función: El nombre de la capacidad expuesta por el host.
* Carga útil de entrada: El cuerpo de la solicitud realizada por la política.
Siempre se codifica en formato JSON.
* Carga útil de salida: El cuerpo de la respuesta procedente del anfitrión. Siempre se codifica en formato JSON.

Cuando algo va mal, el host responde con un error.
Para ello se utiliza el tipo de error del lenguaje de programación utilizado por la política.
El error es una cadena UTF-8 que contiene un mensaje explicativo.
