include::partial$variables.adoc[]
= Especificação dos recursos do host
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Durante a avaliação, entenda os recursos de host oferecidos pelo ambiente para as políticas do {project-name}.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "introduction"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "especificação de política", "recursos de host"]
:sidebar_label: Especificação dos recursos do host
:current-version: {page-origin-branch}

Durante a avaliação, as políticas do {project-name} podem acessar recursos adicionais oferecidos pelo ambiente do host.
Esse mecanismo usa uma abordagem semelhante à RPC tradicionalhttps://en.wikipedia.org/wiki/Remote_procedure_call[do site].

Isso é o que acontece quando uma solicitação é emitida por uma política {short-project-name}:

* {short-project-name} política:
 ** Invoca o recurso oferecido pelo ambiente do host.
 ** A invocação é uma operação de bloqueio, portanto, o código de política aguardará até que o host forneça uma resposta.
* Ambiente do host:
 ** Uma invocação de capacidade é recebida.
 ** O host executa a operação.
 ** O host fornece uma resposta à política, que pode ser um sucesso ou uma falha.
* {short-project-name} política:
 ** O código recebe a resposta do host e retoma a execução.
 ** A resposta do host é tratada adequadamente.

O recurso de recursos do host é implementado usando ohttps://wapc.io/[waPC].
Cada recurso usa esses detalhes:

* Nome da função waPC: O nome do recurso exposto pelo host.
* Carga útil de entrada: O corpo da solicitação feita pela política.
Isso é sempre codificado no formato JSON.
* Carga útil de saída: O corpo da resposta proveniente do host. Isso é sempre codificado no formato JSON.

Quando algo dá errado, o host responde com um erro.
Isso é feito usando o tipo de erro da linguagem de programação usada pela política.
O erro é uma cadeia de caracteres UTF-8 que contém uma mensagem explicativa.
