include::partial$variables.adoc[]
= Políticas do verificador de assinaturas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Implemente políticas seguras para seu cluster usando a política de verificador fornecida ou desenvolva-a com o SDK da linguagem escolhida.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "signature-verifier-policies"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "especificação de política", "verificador de assinatura"]
:sidebar_label: Políticas do verificador de assinaturas
:current-version: {page-origin-branch}

{project-name} implementa o suporte ao projetohttps://www.sigstore.dev/[Sigstore].
Isso permite implementar uma "cadeia de suprimentos segura" para seu cluster.

Parte da função da cadeia de suprimentos segura é garantir que todas as imagens de contêineres em execução no cluster sejam assinadas e verificadas.
Isso prova que eles vêm de seus autores declarados, sem adulteração.
Para ler mais, consulte os documentos sobrexref:/howtos/security-hardening/secure-supply-chain.adoc[como implementamos uma cadeia de suprimentos segura para as próprias políticas].

As assinaturas Sigstore são armazenadas dentro de registros de contêineres, ao lado do objeto OCI que está sendo assinado.
Eles podem ser uma imagem de contêiner ou um artefato OCI mais genérico, como uma política {short-project-name}.
Quando um objeto é assinado, suas assinaturas são armazenadas como camadas de um objeto OCI criado pelo Sigstore.
As políticas que precisam verificar as assinaturas dos contêineres precisam verificar essas camadas e precisam extrair as camadas de assinatura para verificar as próprias assinaturas.

A obtenção e a operação com essas camadas de OCI precisam ocorrer fora do convidado do WebAssembly (a política).
Portanto, isso é feito pelo tempo de execução do WebAssembly,{short-project-name}'s `+policy-server+` ou `+kwctl+`.

Os SDKs de diferentes idiomas para as políticas do {short-project-name} cuidam disso.
Eles fornecem funções para verificação da imagem do contêiner, políticas do{short-project-name}, gráficos do Helm e outros tipos de artefatos da OCI.
Isso garante um caminho de código seguro e testado para verificação.

Extrair dados de um registro e verificar assinaturas criptograficamente pode ser demorado e caro do ponto de vista computacional, portanto, o tempo de execução do WebAssembly (PolicyServer, `+kwctl+`) garante que as extrações de assinaturas e os cálculos de verificação sejam armazenados em cache.
As entradas em cache são automaticamente expiradas após 60 segundos para ajudar a evitar que dados obsoletos sejam servidos.

== Armazenamento em cache

Os resultados da verificação de assinatura são armazenados em cache por um minuto.

Os SDKs oferecem funções semelhantes às seguintes:

* {blank}
+
[subs="+attributes",rust]
----
verify_pub_keys_image(
    image_url: string,
    vector_of_pub_keys: vector<string>,
    vector_of_sigstore_annotations: Vector<(key, value: string)>
    )
    returns (is_trusted: bool, digest_of_verified_image: string)
----

* {blank}
+
[subs="+attributes",rust]
----
verify_keyless_exact_match(
    image_url: string,
    vector_of_tuples_issuer_and_subject: vector<(issuer, subject: string)>,
    vector_of_sigstore_annotations: vector<(key, value: string)>
    )
    returns (is_trusted: bool, digest_of_verified_image: string)
----

Ambas as funções verificam se a imagem está assinada e satisfazem as restrições.

[NOTE]
====
Em caso de sucesso, as funções retornam o resumo da imagem verificada.
Agora é responsabilidade da política garantir que os contêineres sejam instanciados a partir desse resumo, e não de uma tag que possa não corresponder a esse resumo de soma de verificação (e, portanto, estar comprometida).
====


== Um exemplo

A equipe do {short-project-name}https://github.com/kubewarden/verify-image-signatures[ fornece uma política de verificador]que impõe assinaturas Sigstore para todos os contêineres.
Ele foi desenvolvido usando o Rust e com o Rust SDK.
A política garante que os contêineres sejam assinados e, opcionalmente, altera as solicitações. A mutação anexa a soma de verificação verificada à tag da imagem.
Consulte a documentação para obter informações específicas.

Essa política pode atender a todas as suas necessidades, mas, caso prefira uma experiência de usuário diferente, é claro que você pode criar com base nela ou em qualquer outro SDK.

== Contrato de protocolo WaPC

Caso esteja implementando seu próprio SDK de linguagem, essas são as funções que uma política, que verifica assinaturas, pode usar:

=== Função waPC - `+v2/verify+`

==== `+SigstorePubKeyVerify+` entrada

[,hcl]
----
{
  type: "SigstorePubKeyVerify",

  # **mandatory**: image URI to verify
  "image": string,
  "pub_keys": [
    # PEM-encoded public keys
    string
    ],
  # optional:
  "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
}
----

==== `+SigstorePubKeyVerify+` saída

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessVerify+` entrada

[,hcl]
----
{
  type: "SigstoreKeylessVerify",

  # mandatory: image URI to verify
  "image": string,
  "keyless": [
    # list of (issuer, subject) tuples
    {
      # OIDC issuer
      "issuer": string,
      # signature subject (mail, CI URL, ...)
      "subject": string
    }
  ],
  # optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreKeylessVerify+` saída

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessPrefixVerify+` entrada

[,hcl]
----
{
  type: "SigstoreKeylessPrefixVerify",

  # mandatory: image URI to verify
  "image": string,
  "keyless_prefix": [
    # list of (issuer, url_prefix) tuples
    {
      # OIDC issuer
      "issuer": string,
      # URL Prefix of subject (CI URL, ...)
      "url_prefix": string
    }
  ],
  # optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreKeylessPrefixVerify+` saída

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreGithubActionsVerify+` entrada

[,hcl]
----
{
  type: "SigstoreGithubActionsVerify",

  # mandatory: image URI to verify
  "image": string,
  # GitHub owner
  "owner": string,
  # optional:
  # GitHub repository
  "repo": string
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreGithubActionsVerify+` saída

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreCertificateVerify+` entrada

[,hcl]
----
{
  type: "SigstoreCertificateVerify",

  # mandatory: image URI to verify
  "image": string,
  # PEM-encoded certificated used to
  # verify the signature.
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM encoded
  # certificate string.
  "certificate": [byte(int), ..., byte(int)],
  # Optional - certificate chain used to
  # verify the provided certificate.
  # When not specified, the certificate
  # is assumed to be trusted.
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM encoded
  # certificate string.
  "certificate_chain": [
    [byte(int), ..., byte(int)],
    ...
    [byte(int), ..., byte(int)]
  ],
  # Require the signature layer to have
  # a Rekor bundle.
  # Having a Rekor bundle allows further
  # checks to be performed, e.g. ensuring
  # the signature has been produced during
  # the validity time frame of the cert.
  # Recommended to set to `+true+`
  require_rekor_bundle: bool,
  # Optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreCertificateVerify+` saída

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

=== Função waPC - `+v1/verify+`

==== `+SigstorePubKeyVerify+` entrada

[,hcl]
----
{
  "SigstorePubKeyVerify": {
    # **mandatory**: image URI to verify
    "image": string,
    "pub_keys": [
      # PEM-encoded public keys
      string
    ],
    # optional:
    "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
  }
}
----

==== `+SigstorePubKeyVerify+` saída

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessVerify+` entrada

[,hcl]
----
{
  "SigstoreKeylessVerify": {
    # mandatory: image URI to verify
    "image": string,
    "keyless": [
      # list of (issuer, subject) tuples
      {
        # OIDC issuer
        "issuer": string,
        # signature subject (mail, CI URL, ...)
        "subject": string
      }
    ],
    # optional:
    "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
  }
}
----

==== `+SigstoreKeylessVerify+` saída

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----
