include::partial$variables.adoc[]
= Rédiger des politiques en TypeScript/JavaScript
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Apprenez à rédiger des politiques de validation {project-name} efficaces à l'aide de TypeScript/JavaScript.
:keywords: kubewarden, kubernetes, écrire des politiques en TypeScript, écrire des politiques en JavaScript
:doc-type: tutoriel
:doc-topic: kubewarden, writing-policies, typescript, javascript, introduction
:doc-persona: kubewarden-policy-developer
:current-version: {page-origin-branch}

[NOTE]
====
La prise en charge de WebAssembly par TypeScript/JavaScript évolue rapidement.
Cette page a été révisée pour la dernière fois en novembre 2025.
====

Comme indiqué sur le https://www.typescriptlang.org/[site officiel]:

[quote]
TypeScript étend JavaScript en y ajoutant des types.

En comprenant JavaScript, TypeScript vous permet de gagner du temps en détectant les erreurs et en proposant des correctifs avant l'exécution du code.

{project-name} utilise https://github.com/bytecodealliance/javy[Javy] (un projet de la Bytecode Alliance) pour construire des binaires WebAssembly à partir de JavaScript et TypeScript.

[quote]
Javy prend votre code JavaScript et l'exécute dans un contexte WebAssembly.

Il intègre un moteur QuickJS compilé en WebAssembly qui peut exécuter du JavaScript.

Le projet fournit à la fois un CLI et un ensemble d'API pour intégrer et personnaliser le comportement lors de l'exécution de JavaScript dans WebAssembly.

Le projet {short-project-name} utilise actuellement Javy pour ces raisons :

* Moteur JavaScript mature (QuickJS) compilé en WebAssembly.
* Prise en charge de l'xref:/tutorials/writing-policies/wasi/01-intro-wasi.adoc[interface WASI] par le biais de fonctions hôtes personnalisées.
* Taille réduite des binaires par rapport à d'autres solutions JavaScript-to-WebAssembly.
* Développement et maintenance actifs par la Bytecode Alliance.

== Limites de Javy

Javy exécute JavaScript dans un environnement sandboxed WebAssembly avec certaines contraintes :

* *Environnement WASI uniquement :* Accès limité à stdin/stdout/stderr et aux capacités de l'hôte explicitement fournies.
* *Pas d'API Node.js*: Les modules Node.js standard tels que `+fs+`, `+http+`, ou `+crypto+` ne sont pas disponibles.
* *Bibliothèque standard limitée*: Seules les fonctions JavaScript de base et les API explicitement activées sont accessibles.
* *Exécution à un seul fil :* Pas de prise en charge des travailleurs Web ni du multithreading.

Malgré ces limites, Javy offre suffisamment de possibilités pour rédiger des politiques de validation {short-project-name} efficaces grâce au système des capacités d'accueil.

[WARNING]
====
L'écriture sur STDOUT ne respecte pas les règles - utilisez plutôt STDERR pour la journalisation.
====

== Outillage

La rédaction des politiques {short-project-name} nécessite :

* *Node.js*: Exécution de JavaScript.
* *npm*: Pour la gestion des dépendances.
* *TypeScript*: Recommandé pour la sécurité du type (en option).

[WARNING]
====
Assurez-vous que vous utilisez Node.js 18 ou plus. Les versions antérieures peuvent ne pas être compatibles avec la chaîne d'outils de compilation.
====

Ces bibliothèques TypeScript/JavaScript sont utiles pour rédiger une politique {short-project-name}:

* https://github.com/kubewarden/policy-sdk-js[{short-project-name} JavaScript SDK]: Fournit des structures et des fonctions réduisant la quantité de code nécessaire. Il fournit également des aides au test et un accès à toutes les capacités de l'hôte.
* https://github.com/silverlyra/kubernetes-types[Types TypeScript pour Kubernetes]: Fournit des définitions TypeScript pour toutes les ressources Kubernetes, ce qui permet de développer des politiques sans risque de type.

Le projet {short-project-name} fournit un https://github.com/kubewarden/js-policy-template[modèle de projet de politique JavaScript/TypeScript] que vous pouvez utiliser pour créer des politiques {short-project-name}.

== Obtenir la chaîne d'outils

La façon la plus simple d'obtenir la chaîne d'outils est d'utiliser le SDK JavaScript de {short-project-name}, qui comprend le plug-in de compilation Javy :

[source,console]
----
npm install kubewarden-policy-sdk
----

Le binaire du plug-in Javy est automatiquement inclus et vous pouvez le trouver à l'adresse suivante :

[source,console]
----
node_modules/kubewarden-policy-sdk/plugin/javy-plugin-kubewarden.wasm
----

== Prérequis du tutoriel

Pour ce tutoriel, vous avez besoin de ces outils sur votre machine de développement :

* *Node.js*: Version 18 ou supérieure avec npm pour la gestion des dépendances.
* https://github.com/bats-core/bats-core[`+bats+`]: Utilisé pour écrire les tests et automatiser leur exécution.
* https://github.com/kubewarden/kwctl/releases[`+kwctl+` ] ≥ : Outil CLI fourni par {short-project-name} pour exécuter ses politiques en dehors de Kubernetes, entre autres actions. Cette question est abordée dans la xref:/tutorials/testing-policies/index.adoc[section de] la documentation consacrée xref:/tutorials/testing-policies/index.adoc[aux politiques de test].
* https://github.com/bytecodealliance/javy[`+javy+` ≥ 6.0.0]: Outil CLI pour compiler le code JavaScript en modules WebAssembly.