= Monitores
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

En esta sección se describen los monitores listos para usar que se suministran con SUSE Observability. Los monitores suministrados con el producto se añaden constantemente. Consulte la lista completa en la sección Monitores del menú principal.

== Monitores de Kubernetes listos para usar

=== Puntos finales de servicio disponibles

Es importante garantizar que sus servicios estén disponibles y sean accesibles para los usuarios. Para controlar esto, SUSE Observability ha establecido una comprobación que verifica si un servicio tiene al menos un punto final disponible. Los puntos finales son direcciones de red que permiten la comunicación entre los distintos componentes de un sistema distribuido, y deben estar disponibles para que el servicio funcione correctamente.
Si en los últimos 10 minutos hay cero puntos finales disponibles, el monitor seguirá desviándose, lo que indica que puede haber un problema con el servicio que debe solucionarse.
Permite xref:/use/alerting/k8s-override-monitor-arguments.adoc[anular los argumentos del monitor]

=== Cpu limits resourcequota

Los usuarios crean recursos (pods, servicios, etc.) en el espacio de nombres, y el sistema de cuotas realiza un seguimiento del uso para garantizar que no excede los límites de recursos duros para Cpu definidos en un ResourceQuota. El monitor alertará cuando el límite total de Cpu en el espacio de nombres llegue al 90% o más de lo establecido por la cuota. Cada `+resourcequota+` en el espacio de nombres produce un estado de salud del monitor.

=== Cpu requests resourcequota

Los usuarios crean recursos (pods, servicios, etc.) en el espacio de nombres, y el sistema de cuotas realiza un seguimiento del uso para garantizar que no excede las solicitudes de recursos duros para Cpu definidas en una ResourceQuota. El monitor alertará cuando el total de peticiones de Cpu en el espacio de nombres llegue al 90% o más de lo establecido por la cuota. Cada `+resourcequota+` en el espacio de nombres produce un estado de salud del monitor.

=== Réplicas deseadas Daemonset

Es importante que se cumpla el número deseado de réplicas para un Daemonset. Los conjuntos de demonios se utilizan para gestionar un conjunto de pods que deben ejecutarse en todos o en un subconjunto de nodos de un clúster, garantizando que se ejecute una copia del pod en cada nodo que cumpla los criterios especificados. Esto es útil para tareas como el registro, la supervisión y otras tareas a nivel de clúster que deben ejecutarse en cada nodo del clúster. 

Para controlar esto, SUSE Observability ha configurado una comprobación que verifica si las réplicas disponibles coinciden con el número de réplicas deseado. Esta comprobación sólo se aplicará a los DaemonSets que tengan un número deseado de réplicas superior a cero. 

* Si el número de réplicas disponibles es menor que el deseado, el monitor señalará un estado de salud DEVIATING, indicando que puede haber un problema con el StatefulSet.
* Si el número de réplicas disponibles es cero, el monitor señalará un estado de salud CRÍTICO, indicando que el StatefulSet no está funcionando en absoluto. 

Para conocer la definición completa del monitor, consulte los detalles.

=== Desviación del espacio en disco

Es importante supervisar el uso de las reclamaciones de volumen persistentes (PVC) en su clúster Kubernetes a lo largo del tiempo. Los PVC se utilizan para almacenar datos que deben persistir más allá de la vida útil de un contenedor, y es crucial asegurarse de que tienen espacio suficiente para almacenar los datos.
Para rastrear esto, configuramos una comprobación que utiliza la predicción lineal para pronosticar la tendencia de uso del volumen de Kubernetes durante un período de 4 días. Si la tendencia indica que los PVC se quedarán sin espacio dentro de este plazo, recibirás una notificación, lo que te permitirá tomar medidas para evitar la pérdida de datos o el tiempo de inactividad.

=== Espacio en disco crítico

Es importante supervisar el uso de las reclamaciones de volumen persistentes (PVC) en su clúster Kubernetes. Los PVC se utilizan para almacenar datos que deben persistir más allá de la vida útil de un contenedor, y es crucial asegurarse de que tienen espacio suficiente para almacenar los datos. Para realizar un seguimiento de esto, hemos configurado una comprobación que utiliza la predicción lineal para pronosticar la tendencia de uso del volumen de Kubernetes durante un período de 12 horas. Si la tendencia indica que los PVC se quedarán sin espacio dentro de este plazo, recibirás una notificación, lo que te permitirá tomar medidas para evitar la pérdida de datos o el tiempo de inactividad.

=== Despliegue réplicas deseadas

Es importante que se cumpla el número de réplicas deseado para un despliegue. Los despliegues se utilizan para gestionar el despliegue y escalado de un conjunto de Pods idénticos en un clúster Kubernetes. Al garantizar que el número deseado de réplicas se está ejecutando y está disponible, los despliegues pueden ayudar a mantener la disponibilidad y fiabilidad de una aplicación o servicio Kubernetes. Para controlar esto, SUSE Observability ha configurado una comprobación que verifica si las réplicas disponibles coinciden con el número de réplicas deseado.

Esta comprobación sólo se aplicará a los Despliegues que tengan un número deseado de réplicas superior a cero.

* Si el número de réplicas disponibles es inferior al deseado, el monitor señalará un estado de salud DEVIATING, indicando que puede haber un problema con los Despliegues.
* Si el número de réplicas disponibles es cero, el monitor señalará un estado de salud CRÍTICO, indicando que el StatefulSet no está funcionando en absoluto.

Para conocer la definición completa del monitor, consulte los detalles.

=== HTTP - Proporción de errores 5xx

Las respuestas HTTP con un código de estado en el rango 5xx indican errores del lado del servidor como una mala configuración, sobrecarga o errores internos del servidor.
Para garantizar una buena experiencia de usuario, el porcentaje de respuestas 5xx debe ser inferior al 5% del total de respuestas HTTP de un servicio Kubernetes.

Dado que el umbral exacto y la gravedad pueden depender de la aplicación, los umbrales se pueden xref:/use/alerting/k8s-override-monitor-arguments.adoc[anular mediante una anotación de Kubernetes] en el servicio. Por ejemplo, para anular el umbral de desviación preconfigurado y, en su lugar, tener un umbral crítico del 6%, ponga esta anotación en su servicio:
```
monitor.kubernetes-v2.stackstate.io/http-error-ratio-for-service: | 
  { 
    "criticalThreshold": 0.06,
    "deviatingThreshold": null
  }
```

La omisión del umbral de desviación de este fragmento json lo habría mantenido en el 5% configurado, con el umbral crítico en el 6%, lo que significa que el monitor sólo daría lugar a un estado de desviación para un ratio de error entre el 5% y el 6%.

=== HTTP - tiempo de respuesta - Q95 es superior a 3 segundos

El seguimiento del tiempo de respuesta HTTP del percentil 95 (Q95) para sus servicios Kubernetes le ayuda a detectar solicitudes lentas y valores atípicos de rendimiento que podrían afectar a los usuarios. Si el tiempo de respuesta del Q95 supera los 3 segundos durante una ventana de tiempo especificada, el monitor le alertará con un estado de desviación.

Puede adaptar este monitor a las necesidades de su aplicación xref:/use/alerting/k8s-override-monitor-arguments.adoc[anulando la configuración predeterminada], como la ventana de tiempo, el umbral o el cuantil, mediante una anotación de Kubernetes en su servicio. Esta flexibilidad es útil si su servicio tiene requisitos de rendimiento únicos. Por ejemplo, servicios de sondeo largos.

Para personalizar el monitor, añada una anotación como la siguiente a su servicio y ajuste los valores según sea necesario:

```
monitor.kubernetes-v2.stackstate.io/http-response-time/overrides: |
  {
    "deviatingTimeWindow": "10m",            // Time window for a deviating state (e.g., "10m", "1h")
    "deviatingThreshold": 1.2,               // Threshold in seconds for a deviating state
    "criticalTimeWindow": "30m",             // Time window for a critical state
    "criticalThreshold": 2.0,                // Threshold in seconds for a critical state
    "quantile": 0.99,                        // Quantile to monitor (e.g., 0.95, 0.99)
    "nameTemplate": "API latency (p{{ quantile }}) > {{ threshold }}", // Custom monitor name
    "enabled": true                          // Set to false to disable this monitor for the service
  }
```

- Puede omitir cualquier campo para utilizar su valor por defecto.
- El monitor evalúa el cuantil elegido del tiempo de respuesta en la ventana especificada. Si el valor está por encima del umbral, el monitor se activa.
- En el ejemplo anterior, el monitor señalará un estado de desviación si el tiempo de respuesta del percentil 99 (Q99) es superior a 1,2 segundos (en los últimos 10 minutos), y un estado crítico si es superior a 2,0 segundos (en los últimos 30 minutos).

=== Tendencia de uso del volumen de Kubernetes durante 12 horas

Es importante supervisar el uso de las reclamaciones de volumen persistentes (PVC) en su clúster Kubernetes. Los PVC se utilizan para almacenar datos que deben persistir más allá de la vida útil de un contenedor, y es crucial asegurarse de que tienen espacio suficiente para almacenar los datos. Para realizar este seguimiento, SUSE Observability ha establecido una comprobación que utiliza la predicción lineal para pronosticar la tendencia de uso del volumen de Kubernetes en un periodo de 12 horas. Si la tendencia indica que los PVC se quedarán sin espacio dentro de este plazo, recibirás una notificación, lo que te permitirá tomar medidas para evitar la pérdida de datos o el tiempo de inactividad.

=== Tendencia de uso del volumen de Kubernetes durante 4 días

Es importante supervisar el uso de las reclamaciones de volumen persistentes (PVC) en su clúster Kubernetes a lo largo del tiempo. Los PVC se utilizan para almacenar datos que deben persistir más allá de la vida útil de un contenedor, y es crucial asegurarse de que tienen espacio suficiente para almacenar los datos.
Para realizar este seguimiento, SUSE Observability estableció una comprobación que utiliza la predicción lineal para pronosticar la tendencia de uso del volumen de Kubernetes durante un periodo de 4 días. Si la tendencia indica que los PVC se quedarán sin espacio dentro de este plazo, recibirás una notificación, lo que te permitirá tomar medidas para evitar la pérdida de datos o el tiempo de inactividad.

=== Límites de memoria resourcequota

Los usuarios crean recursos (pods, servicios, etc.) en el espacio de nombres, y el sistema de cuotas realiza un seguimiento del uso para garantizar que no excede los límites de recursos duros para la memoria definidos en un ResourceQuota. El monitor alertará cuando el límite total de memoria en el espacio de nombres llegue al 90% o más de lo establecido por la cuota. Cada `+resourcequota+` en el espacio de nombres produce un estado de salud del monitor.

=== Peticiones de memoria resourcequota

Los usuarios crean recursos (pods, servicios, etc.) en el espacio de nombres, y el sistema de cuotas realiza un seguimiento del uso para garantizar que no excede las solicitudes de recursos duros para la memoria definida en un ResourceQuota. El monitor alertará cuando el total de peticiones de memoria en el espacio de nombres llegue al 90% o más de lo establecido por la cuota. Cada `+resourcequota+` en el espacio de nombres produce un estado de salud del monitor.

=== Presión del disco del nodo

La presión del disco de nodo se refiere a una situación en la que los discos conectados a un nodo experimentan una tensión excesiva. Aunque es poco probable que se produzca presión en los discos de los nodos gracias a las medidas preventivas integradas en Kubernetes, puede ocurrir de forma esporádica. Hay dos razones principales por las que puede surgir la presión del disco nodal. La primera razón está relacionada con el hecho de que Kubernetes no limpia las imágenes no utilizadas. En circunstancias normales, Kubernetes comprueba y elimina regularmente las imágenes que no están en uso. Por lo tanto, se trata de una causa infrecuente de presión discal nodular, pero debe reconocerse. El problema más probable es la acumulación de troncos. En Kubernetes, los registros se guardan normalmente en dos escenarios: cuando los contenedores se están ejecutando y cuando los registros del contenedor que ha salido más recientemente se conservan para solucionar problemas. Este enfoque pretende lograr un equilibrio entre la conservación de los registros importantes y el descarte de los innecesarios con el paso del tiempo. Sin embargo, si un contenedor de larga ejecución genera un gran volumen de registros, éstos pueden acumularse hasta el punto de sobrecargar la capacidad del disco del nodo. Para conocer la definición completa del monitor, consulte los detalles.
Permite xref:/use/alerting/k8s-override-monitor-arguments.adoc[anular los argumentos del monitor]

=== Presión de la memoria del nodo

La presión de memoria del nodo se refiere a una situación en la que los recursos de memoria de un nodo Kubernetes están excesivamente sobrecargados. Si bien es poco común encontrar presión de memoria en los nodos debido a los mecanismos de gestión de recursos incorporados de Kubernetes, aún puede ocurrir en circunstancias específicas. Hay dos razones principales por las que puede surgir la presión de la memoria del nodo. La primera razón está relacionada con solicitudes y límites de recursos mal configurados o insuficientes para los contenedores que se ejecutan en el nodo. Kubernetes se basa en solicitudes y límites de recursos para asignarlos y gestionarlos de forma eficaz. Si los contenedores no están configurados con precisión en cuanto a sus requisitos de memoria, pueden consumir más memoria de la esperada, provocando una presión de memoria en los nodos. La segunda razón es la presencia de aplicaciones o procesos que consumen mucha memoria. Ciertas cargas de trabajo o aplicaciones pueden tener mayores demandas de memoria, lo que resulta en una mayor utilización de memoria en el nodo. Si se programan varios pods o contenedores con requisitos de memoria sustanciales en el mismo nodo sin una asignación de recursos adecuada, puede producirse una presión de memoria. Para mitigar la presión sobre la memoria de los nodos, es crucial revisar y ajustar las solicitudes y límites de recursos para los contenedores, asegurándose de que se alinean con las necesidades reales de memoria de las aplicaciones. Supervisar y optimizar el uso de la memoria dentro de las propias aplicaciones también puede ayudar a reducir el consumo de memoria. Además, considere el autoescalado horizontal de pods para escalar dinámicamente el número de pods en función de la utilización de la memoria. La supervisión periódica, el análisis de las métricas relacionadas con la memoria y la asignación proactiva de recursos de memoria pueden ayudar a mantener un estado de memoria saludable en los nodos Kubernetes. Es esencial comprender los requisitos específicos de sus cargas de trabajo y ajustar la asignación de recursos en consecuencia para evitar la presión de la memoria y garantizar un rendimiento óptimo.
Permite xref:/use/alerting/k8s-override-monitor-arguments.adoc[anular los argumentos del monitor]

=== Nodo PID Presión

La presión de los PID de nodo se produce cuando los recursos de identificación de procesos (PID) disponibles en un nodo Kubernetes se ven sometidos a una presión excesiva. La primera razón está relacionada con solicitudes y límites de recursos mal configurados o insuficientes para los contenedores que se ejecutan en el nodo. Kubernetes se basa en solicitudes y límites de recursos precisos para asignar y gestionar los recursos de forma eficaz. Si los contenedores no están configurados correctamente con sus requerimientos de PIDs, pueden consumir más PIDs de los esperados, resultando en una presión de PIDs en los nodos. La segunda razón es la presencia de aplicaciones o procesos intensivos en PID. Algunas cargas de trabajo o aplicaciones tienen mayores demandas de identificación de procesos, lo que conduce a una mayor utilización de PID en el nodo. Si se programan varios pods o contenedores con requisitos de PID significativos en el mismo nodo sin una asignación de recursos adecuada, puede producirse una presión de PID. Para hacer frente a la presión de los PID de los nodos, es importante revisar y ajustar las solicitudes y límites de recursos de los contenedores para garantizar que se ajustan a las necesidades reales de PID de las aplicaciones. Supervisar y optimizar el uso de PID dentro de las propias aplicaciones también puede ayudar a reducir el consumo de PID. Además, considerando el autoescalado horizontal de pods se puede escalar dinámicamente el número de pods en función de la utilización del PID. La supervisión periódica, el análisis de las métricas relacionadas con los PID y la asignación proactiva de recursos de PID son cruciales para mantener un estado saludable del uso de PID en los nodos Kubernetes. Es esencial comprender los requisitos específicos de sus cargas de trabajo y ajustar la asignación de recursos en consecuencia para evitar la presión del EPI y garantizar un rendimiento óptimo.
Permite xref:/use/alerting/k8s-override-monitor-arguments.adoc[anular los argumentos del monitor]

=== Preparación de los nodos

Comprueba si el Nodo está funcionando como se esperaba.
Permite xref:/use/alerting/k8s-override-monitor-arguments.adoc[anular los argumentos del monitor]

=== Volúmenes persistentes huérfanos

Compruebe que no hay volúmenes persistentes huérfanos. Un volumen persistente huérfano es un volumen persistente que no está asociado a una reclamación de volumen persistente. Un volumen persistente huérfano puede ser un riesgo para la seguridad, ya que puede contener datos sensibles que no se están utilizando. Un volumen persistente huérfano también puede ser un desperdicio de recursos, ya que no se está utilizando.
Permite xref:/use/alerting/k8s-override-monitor-arguments.adoc[anular los argumentos del monitor] pero sólo la propiedad `+enabled+` 

=== Sin memoria para contenedores

Es importante asegurarse de que los contenedores que se ejecutan en su clúster Kubernetes tienen suficiente memoria para funcionar correctamente. Las condiciones de falta de memoria (OOM) pueden hacer que los contenedores se bloqueen o dejen de responder, lo que provoca reinicios y posibles pérdidas de datos.
Para supervisar estas condiciones, SUSE Observability estableció una comprobación que detecta y notifica eventos OOM en los contenedores que se ejecutan en el clúster. Esta comprobación le ayudará a identificar cualquier contenedor que se esté quedando sin memoria y le permitirá tomar medidas para evitar problemas antes de que se produzcan.
Permite xref:/use/alerting/k8s-override-monitor-arguments.adoc[anular los argumentos del monitor]

=== Estado Pod Ready

Comprueba si un Pod programado se está ejecutando y está listo para recibir tráfico en el plazo previsto.

=== Duración de la vaina

Controla la duración de los espacios del servidor y del consumidor. Cuando el percentil 95 de la duración es mayor que el umbral (por defecto 5000ms) el monitor tiene un estado de Desviación. Este monitor admite la anulación de ajustes mediante xref:/use/alerting/k8s-override-monitor-arguments.adoc[anulaciones de argumentos de monitor].

=== Ratio de error de la vaina

Supervisa el porcentaje de tramos del servidor y del consumidor que tienen un estado de error. Si el porcentaje de intervalos de error supera el umbral (por defecto 5), el monitor pasa a un estado Desviado. Este monitor admite la anulación de ajustes mediante xref:/use/alerting/k8s-override-monitor-arguments.adoc[anulaciones de argumentos de monitor].

=== Pods en estado de espera

Si un pod se encuentra en estado de espera y contiene un motivo de CreateContainerConfigError, CreateContainerError, CrashLoopBackOff o ImagePullBackOff se considerará desviado.

=== Replicaset réplicas deseadas

Es importante asegurarse de que se cumple el número deseado de réplicas para su ReplicaSet (y despliegue). ReplicaSets y Deployments se utilizan para gestionar el número de réplicas de un pod concreto en un clúster Kubernetes.

Para controlar esto, SUSE Observability ha configurado una comprobación que verifica si las réplicas disponibles coinciden con el número de réplicas deseado. Esta comprobación sólo se aplicará a ReplicaSets y Despliegues que tengan un número deseado de réplicas superior a cero.

* Si el número de réplicas disponibles es inferior al deseado, el monitor señalará un estado de salud DEVIATING, indicando que puede haber un problema con el ReplicaSet o la implementación.
* Si el número de réplicas disponibles es cero, el monitor señalará un estado de salud CRÍTICO, indicando que el ReplicaSet o Despliegue no está funcionando en absoluto.

Además, el estado de salud del ReplicaSet se propagará a la implantación para una supervisión más exhaustiva.

=== Reinicios de contenedores

Es importante supervisar los reinicios de cada contenedor en un clúster Kubernetes. Los contenedores pueden reiniciarse por diversas razones, como problemas con la aplicación o la infraestructura.
Para garantizar que la aplicación se ejecuta sin problemas, SUSE Observability ha configurado un monitor que realiza un seguimiento del número de reinicios del contenedor durante un período de 10 minutos. Si se producen más de 3 reinicios durante este periodo de tiempo, el estado de salud del contenedor se establecerá en DEVIATING, lo que indica que puede haber un problema que deba investigarse.

=== Puntos finales de servicio disponibles

Es importante garantizar que sus servicios estén disponibles y sean accesibles para los usuarios. Para controlar esto, hemos establecido una comprobación que verifica si un servicio tiene al menos un punto final disponible. Los puntos finales son direcciones de red que permiten la comunicación entre los distintos componentes de un sistema distribuido, y deben estar disponibles para que el servicio funcione correctamente.
Si en los últimos 10 minutos no hay ningún punto final disponible, el monitor permanecerá en un estado de desviación, lo que indica que puede haber un problema con el servicio que debe solucionarse.
Para conocer la definición completa del monitor, consulte los detalles.

=== Duración del servicio

Controla la duración de los espacios del servidor y del consumidor. Cuando el percentil 95 de la duración es mayor que el umbral (por defecto 5000ms) el monitor tiene un estado de Desviación. Este monitor admite la anulación de ajustes mediante xref:/use/alerting/k8s-override-monitor-arguments.adoc[anulaciones de argumentos de monitor].

=== Ratio de error de tramo de servicio

Porcentaje de tramos de servidores y consumidores que se encuentran en estado de error para un servicio Kubernetes. Este monitor admite la anulación de ajustes mediante xref:/use/alerting/k8s-override-monitor-arguments.adoc[anulaciones de argumentos de monitor].

=== Statefulset réplicas deseadas

Es importante que se cumpla el número de réplicas deseado para un StatefulSet. Los StatefulSets se utilizan para gestionar aplicaciones con estado y requieren un número específico de réplicas para funcionar correctamente.

Para controlar esto, SUSE Observability ha configurado una comprobación que verifica si las réplicas disponibles coinciden con el número de réplicas deseado. Esta comprobación sólo se aplicará a StatefulSets que tengan un número deseado de réplicas superior a cero.

* Si el número de réplicas disponibles es menor que el deseado, el monitor señalará un estado de salud DEVIATING, indicando que puede haber un problema con el StatefulSet.
* Si el número de réplicas disponibles es cero, el monitor señalará un estado de salud CRÍTICO, indicando que el StatefulSet no está funcionando en absoluto.

=== Nodo no programable

Si se encuentra con un evento "NodeNotSchedulable" en Kubernetes, significa que el programador de Kubernetes no pudo colocar un pod en un nodo específico debido a algunas restricciones o problemas con el nodo. Este evento se produce cuando el programador no puede encontrar un nodo adecuado para ejecutar el pod de acuerdo con sus requisitos de recursos y otras restricciones.

=== Estado de salud agregado de un Cluster

El racimo no tiene salud por sí mismo. Pero un clúster se construye a partir de pocos componentes, algunos de los cuales son críticos para el funcionamiento normal. El monitor agrega estados de estos componentes:

* todos los pods en el espacio de nombres 'kube-system
* todos los nodos y, a continuación, toma el estado de salud más crítico.

=== Estado de las cargas de trabajo derivadas (Deployment, DaemonSet, ReplicaSet, StatefulSet)

El monitor agrega los estados de todas las dependencias superiores y, a continuación, devuelve el estado de salud más crítico basándose en observaciones directas (por ejemplo, a partir de métricas).
Este enfoque garantiza que las señales de salud se propaguen desde los componentes técnicos de bajo nivel (como los Pods) a los componentes lógicos de nivel superior, pero sólo cuando el propio componente carezca de un estado de salud observado.
Para utilizar este monitor con eficacia, asegúrese de que algunas o todas las comprobaciones de salud siguientes están desactivadas:

* Despliegue réplicas deseadas
* DaemonSet réplicas deseadas
* ReplicaSet réplicas deseadas
* StatefulSet réplicas deseadas

Si tiene un caso de uso en el que los componentes lógicos no tienen monitores directos, puede utilizar la función xref:/use/alerting/k8s-derived-state-monitors.adoc[Monitor de estado derivado] para inferir su estado basándose en los componentes técnicos de los que dependen.

== Ver también

* xref:/use/alerting/k8s-monitors.adoc[Monitores]
