include::partial$variables.adoc[]
= Sécuriser les webhooks avec TLS mutuel avec K3s
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Activer mTLS avec K3s
:description: Mettez en œuvre les protocoles mutual Transport Layer Security (mTLS) pour sécuriser les webhooks avec K3s dans votre distribution SUSE Kubernetes.
:keywords: ["{project-name}", kubewarden, kubernetes, security]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manuel de l'opérateur, sécurité

Ce guide vous montre comment activer la sécurité mutuelle de la couche transport (mTLS) pour les webhooks de la pile{project-name} lorsque vous utilisez https://k3s.io/[] K3s comme distribution Kubernetes.

Pour plus d'informations sur la manière de durcir les webhooks, consultez laxref:/reference/security-hardening/webhooks-hardening.adoc[page de référence].

== Conditions préalables

Avant d'installer K3s, vous devez créer une autorité de certification (AC) et un certificat client. Vous l'utilisez pour sécuriser la communication entre les webhooks{short-project-name} et le serveur API Kubernetes.

Dans un premier temps, créez le répertoire `+/etc/rancher/k3s/admission/certs+`:

[source,console]
----
sudo mkdir -p /etc/rancher/k3s/admission/certs
----

=== Créer une autorité de certification racine et le certificat du client

En tant qu'utilisateur de `+root+`, changez de répertoire pour aller dans le répertoire `+/etc/rancher/k3s/admission/certs+`et créez tous les certificats nécessaires :

[source,console]
----
export FQDN=mtls.kubewarden.io

# Create openssl config file
cat > openssl.cnf <<EOL
[ req ]
default_keyfile     = rootCA.key
distinguished_name  = req_distinguished_name
x509_extensions     = v3_ca
string_mask         = utf8only

[ req_distinguished_name ]
countryName         = Country Name (2 letter code)
countryName_default = US
stateOrProvinceName = State or Province Name (full name)
localityName        = Locality Name (eg, city)
organizationName    = Organization Name (eg, company)
commonName          = Common Name (eg, your domain or your CA name)

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true, pathlen:1
keyUsage = critical, keyCertSign, cRLSign
EOL

# Create CA
openssl req -nodes -batch -x509 -sha256 -days 3650 -newkey rsa:4096 -keyout rootCA.key -out rootCA.crt \
  -config openssl.cnf

# Create CSR
openssl req -nodes -batch -newkey rsa:4096 -keyout client.key -out client.csr \
    -addext "subjectAltName = DNS:$FQDN"  -config openssl.cnf

# Create CRT
openssl x509 -req -CA rootCA.crt -CAkey rootCA.key -in client.csr -out client.crt -days 3650 -CAcreateserial \
    -extfile <(echo "subjectAltName=DNS:$FQDN")

# Print CRT

openssl x509 -text -noout -in client.crt
----

Cette opération crée les fichiers suivants :

* `+client.crt+`
* `+client.csr+`
* `+client.key+`
* `+rootCA.crt+`
* `+rootCA.key+`
* `+rootCA.srl+`

=== Créer le fichier de configuration de Kubernetes

Créez le fichier `+/etc/rancher/k3s/admission/admission.yaml+` avec le contenu suivant :

[source,yaml]
----
# /etc/rancher/k3s/admission/admission.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
- name: MutatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
----

Enfin, créez un fichier `+kubeconfig+` à l'adresse `+/etc/rancher/k3s/admission/kubeconfig+`:

[source,yaml]
----
# /etc/rancher/admission/kubeconfig
apiVersion: v1
kind: Config
users:
- name: "*.kubewarden.svc" # namespace where the kubewarden stack is deployed
  user:
    client-certificate: /etc/rancher/k3s/admission/certs/client.crt
    client-key: /etc/rancher/k3s/admission/certs/client.key
----

=== Créer un fichier de configuration K3s

Créez un fichier de configuration K3s à l'adresse `+/etc/rancher/k3s/config.yaml+`:

[source,yaml]
----
# /etc/rancher/k3s/config.yaml
kube-apiserver-arg:
- admission-control-config-file=/etc/rancher/k3s/admission/admission.yaml
----

== Installer les K3

Installez K3s en utilisant la commande suivante :

[source,console]
----
curl -sfL https://get.k3s.io | sh -
----

Attendez la fin de l'installation.

== Installer la pile {short-project-name} 

=== Conditions préalables

Le certificat de l'autorité de certification racine, qui a émis le certificat du client Kubernetes, doit être disponible pour la pile {short-project-name}.

L'autorité de certification racine est disponible à l'adresse `+/etc/rancher/k3s/admission/certs/rootCA.crt+` sur le nœud Kubernetes. Vous avez besoin de son contenu dans un `+ConfigMap+` sous l'espace de noms`+kubewarden+`. Vous stockez le contenu du fichier `+rootCA.crt+` dans la clé nommée `+client-ca.crt+`.

Commencez par créer l'espace de noms `+kubewarden+`:

[source,console]
----
kubectl create namespace kubewarden
----

Créez ensuite le site `+ConfigMap+` à l'intérieur de celui-ci. C'est ce que fait la commande suivante, exécutée sur le nœud Kubernetes :

[source,console]
----
kubectl create configmap -n kubewarden api-server-mtls \
    --from-file=client-ca.crt=/etc/rancher/k3s/admission/certs/rootCA.crt
----

Le nom du fichier résultant `+ConfigMap+` est `+api-server-mtls+`.

=== Installer la pile {short-project-name} 

Installez la pile {short-project-name} comme décrit dans lexref:/quick-start.adoc[guide de démarrage rapide.] Suivez toutes les étapes, mais lors de l'installation de la carte `+kubewarden-controller+` Helm, veillez à activer les valeurs suivantes :

* `+mTLS.enable+`Le texte de l'article 2 est le suivant : "Le texte de l'article 2 doit être `+true+`".
* `+mTLS.configMapName+`Le nom de l'application : doit être le nom de l'application précédemment créée `+ConfigMap+`.

Le nom `+ConfigMap+` est `+api-server-mtls+`. La commande Helm pour installer le site`+kubewarden-controller+` est la suivante :

[source,console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller \
    --set mTLS.enable=true \
    --set mTLS.configMapName=api-server-mtls
----

Une fois cette commande terminée, mTLS sécurise l'installation de la pile{short-project-name} et de ses webhooks.