include::partial$variables.adoc[]
= ポリシーをArtifact Hubに公開する
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 整形された Git リポジトリのレイアウトを作成し、自動パッケージングのための GitHub Actions を設定することで、{project-name} ポリシーを Artifact Hub に公開し、継続的インテグレーションを促進する。
:doc-persona: ["kubewarden-user"、"kubewarden-operator"、"kubewarden-policy-developer"、"kubewarden-distributor"、"kubewarden-integrator"]]。
:doc-topic: ["distributing-policies", "publish-policy-to-artifacthub"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"publishing policies"、"artifact hub"]。
:sidebar_label: アーティファクト・ハブへの公開
:sidebar_position: 40
:current-version: {page-origin-branch}

https://artifacthub.io/[Artifact Hubは]、ユーザーがhttps://cncf.io[CNCF]プロジェクトのパッケージや設定を検索、インストール、公開できるウェブサイトである。

{project-name} ポリシーはArtifact Hubで公開され、CNCFの幅広いユーザーに発見してもらうことができる。

[NOTE]
====
アーティファクト・ハブはコンテンツ集約プラットフォームであり、実際に公開されるアーティファクトをホストしているわけではない。

Artifact Hubでは、コンテナ・イメージのリポジトリをコンテナ・レジストリまたはWebサーバーに物理的にホストする必要がある。
ポリシーをホストする方法の詳細については、「xref:explanations/distributing-policies.adoc[ポリシーの配布]」のセクションを参照してください。
====


このドキュメントでは、{short-project-name} ポリシーを Artifact Hub で検出可能にするために必要な手順を中心に説明します。

== Gitリポジトリの準備

Artifact Hubは、特別なメタデータ・ファイルを探してGitリポジトリをクロールする。

Gitリポジトリにはさまざまなレイアウトがあります。これらはすべて、https://artifacthub.io/docs/topics/repositories/#kubewarden-policies-repositories[公式 Artifact Hub ドキュメントに]詳しく記載されている。

Artifact Hubは柔軟性があり、このような方法でコードを整理することができる：

* Artifact Hub専用のGitリポジトリを用意する：このリポジトリにはポリシーのソースコードは含まれない。これは、Artifact Hubが必要とするYAMLファイルのコレクションとなる。

* ポリシーのソースを格納するGitリポジトリにArtifact Hubディレクトリを追加します。これは以前のアプローチの繰り返しで、Gitリポジトリで定義されている1つのポリシーだけに焦点を当てたものだ。このアプローチでは、Artifact Hubに公開されたポリシーの複数のバージョンを保持することができる。

* ポリシーのソースコードを格納するGitリポジトリのルートに、`+artifacthub-pkg.yml+` と`+artifacthub-repo.yml+` ファイルを追加します。このアプローチは最もシンプルなものだ。唯一の制限は、ポリシーの最新バージョンだけがArtifact Hubに表示されることです。

最後のアプローチは、公式の政策テンプレートで使われている。scaffoldされたGitリポジトリには`+artifacthub-repo.yml+` 。GitHub Actionsは`+artifacthub-pkg.yml+` を生成して`+artifacthub+` ブランチにプッシュし、Artifact Hubが利用できるようにする。

== 出版ステップ

Artifact Hub にポリシーを公開する前に、https://artifacthub.io/[] アカウントを作成する必要があります。

ポリシーを公開する前に、Git リポジトリが適切なレイアウトになっていることを確認しましょう。`+metadata.yml+` には、必要な注釈がきちんと書かれています。

これを手動で行いたい場合は、`+kwctl scaffold artifacthub+` （バージョンは`+>= 1.23+` ）を実行して、`+artifacthub-pkg.yml+` ファイルを作成することができます。このコマンドは、現在のパスの`+metadata.yml+` を取り、`+artifacthub-pkg.yml+` を出力する。`+artifacthub-pkg.yml+` には、`+version:+` 、`+createdAt:+` などのフィールドがあり、特定の書式に合致し、最新である必要がある。`+artifacthub-pkg.yml+` https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml[、] 。

GitHub Actions >=`+v4.0.0+` を使用している場合、リリースワークフローは入力`+artifacthub: true+` で設定できます。このように設定すると、リリースが成功した後（ポリシーが正常にビルドされ、署名され、プッシュされた後）、GitHub Actions は最後のジョブとして`+artifacthub-pkg.yml+` を生成し、コミットして`+artifacthub+` ブランチに変更をプッシュします。正規のファイルは常に`+main+`ブランチにあるものだ。以前のリリースの GitHub Actions の動作については、1.23 より前のバージョンのドキュメントを参照してください。

最後に、ポリシーがコンテナ・レジストリ内またはウェブ・サーバー上で公開されていることを確認する。

[NOTE]
====
今現在、`+artifacthub-repo.yml+` ファイルの内容は関係ない。
====


すべてが整ったら、Artifact Hubにログインし、https://artifacthub.io/control-panel/repositories?page=1[コントロール・プレーンに]アクセスする。

ポリシーをユーザーとして公開するか、所属するArtifact Hub組織の下で公開するかを決定します。これは、正しい_「コントロールパネルのコンテキスト」を_選択することによって行われる。

次に_「追加」_ボタンを押し、フォームに必要事項を記入する：

* 種類として_「{short-project-name} ポリシー」を_選択する。
* _名前_」と「_表示名」を_任意で入力してください。
* GitリポジトリのURLを入力してください。
* 追跡するブランチに`+artifacthub+` 。

最後に_「追加」_ボタンを押す。_リポジトリ」_ページに戻り、作成したばかりのリポジトリが表示されます。

各リポジトリにはいくつかの情報フィールドがある。先ほど作成したリポジトリの_「ID」_プロパティを見つけてコピーします。

Git リポジトリに戻り、`+artifacthub-repo.yml+` を編集します。ドキュメント内の`+repositoryID+` キーが、Artifact Hub Web ページからコピーした値であることを確認します。

[TIP]
====
`+artifacthub-repo.yml+` 、ファイルのフォーマットはhttps://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml[] 。

さて、このファイルをさらにカスタマイズする良い機会だ。
====


変更が終わったら、更新した`+artifacthub-repo.yml+`ファイルをコミットし、プッシュする。次のスキャンで、Artifact Hubはこのファイルを検出し、https://artifacthub.io/docs/topics/repositories/#verified-publisher[_ 「Verified Publisher」_バッジを]Artifact Hubリポジトリに追加します。

== アーティファクト・ハブを同期させる

ポリシーの新バージョンをリリースするたびに、`+artifacthub-pkg.yml+` ファイルの内容を更新することを忘れないでください。たとえば、`+io.kubewarden.policy.version+` フィールド（通常、ポリシーの OCI タグと一致する）、および変更したいその他の注釈を更新する必要があります。

[NOTE]
====
`+artifacthub-repo.yml+` ファイルの内容を変更する必要はない。
====

