= 特点
:revdate: 2026-03-05
:page-revdate: {revdate}

本节介绍{product_name} 中的功能和功能阶段。

== 功能列表

|===
| 特点 | 舵手功能名称 | 子功能 | 默认值 | 舞台 

| *车队附加服务提供商*
| `+addon-provider-fleet+`
| _无_
| 启用
| 测试版

| *代理 TLS 模式*
| `+agent-tls-mode+`
| _无_
| 启用
| 测试版

| *无证书管理员*
| `+no-cert-manager+`
| _无_
| 启用
| 测试版

| *使用 Rancher 默认注册表*
| `+use-rancher-default-registry+`
| _无_
| 启用
| 测试版

|===

=== 车队附加服务提供商
该功能安装了 Cluster API Add-on Provider for Fleet (CAAPF)，以提供与https://github.com/rancher/fleet[Fleet]的集成，并使应用程序能够轻松部署到 CAPI 配置的集群中。CAAPF 会自动在管理集群中安装 Fleet，并将新配置的 CAPI 集群注册到 Fleet 中，以便通过 GitOps、`+Bundle+` 或`+HelmOp+` 资源将应用程序部署到这些集群中。CAAPF 还支持通过 Fleet 的 ClusterGroup 对引用相同 ClusterClass 的 CAPI 群集进行分组，从根本上简化了向大型群集组部署应用程序的过程。该功能处于 GA 阶段，默认情况下已启用。

=== 代理 TLS 模式
该功能门用于指示 Turtles 在检索群集注册清单以导入群集时，是否应遵循 Rancher 的`+agent-tls-mode+` 设置。启用后，Turtles 将查询 Rancher 的`+agent-tls-mode+` 设置值，以确定是设置为`+system-store+` 还是`+strict+` 。如果设置为`+system-store+` ，海龟将信任由操作系统信任存储中的公共证书颁发机构生成的任何证书，包括由 Let's Encrypt 等颁发机构签署的证书。如果设置为`+strict+` ，Turtles 将只信任由 Rancher 的`+cacerts+` 设置中包含的证书颁发机构生成的证书。禁用该设置后，海龟将退回到`+system-store+` 模式下工作。该功能处于测试阶段，默认情况下已启用。

=== 无证书管理员
该功能门可转换 CAPI Providers 清单，以https://github.com/rancher/wrangler/[wrangler] 代替 cert-manager 的使用。

特别是，验证和更改接纳 webhooks 将更新为使用由 wrangler 生成的证书，而不是证书管理器，从而实现无证书管理器环境。

请注意，使用 Rancher`+CATTLE_SYNC_ONLY_CHANGED_OBJECTS+` https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/best-practices/tuning-rancher-at-scale.html#_reducing_event_handler_executions[功能]可能会阻止证书在默认的一年到期时间后续期。

可以禁用此功能，将所有提供程序清单恢复为原来的 cert-manager 使用方式。

=== 使用 Rancher 默认注册表

此功能门指示{product_name} 在为 CAPI 提供程序组件构建映像引用时，利用 Rancher 的`+system-default-registry+` 管理设置。启用后，{product_name} 会读取该设置，如果配置了注册表，则会重写每个提供程序映像的存储库，以使用该注册表。
如果设置为空，{product_name} 将返回默认图像引用。`+ClusterctlConfig+` 资源中定义的图像重载始终优先。有关在空气密封环境中的详细使用方法，请参阅xref:operator/airgapped.adoc[空气密封环境]。该功能处于 alpha 阶段，默认情况下已启用。

== 功能阶段

{product_name} 遵循 Kuberneteshttps://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages[功能阶段]流程。功能可以处于以下阶段之一：阿尔法、贝塔或一般可用性 (GA)。

=== Alpha Stage
- 默认已禁用。
- 可能存在漏洞，没有长期支持。
- API 可能会更改，恕不另行通知。
- 建议仅用于短期测试群组。

=== 测试阶段
- 默认情况下始终启用。
- 久经考验，安全可靠。
- 支持稳定，但模式可能会在未来版本中发生变化。
- 由于可能出现不相容的变化，建议用于非关键业务用途。

[NOTE]
====
请就 Alpha 和 Beta 版功能提供反馈意见！
====

=== 一般可用性（GA）阶段
- 始终启用，无法禁用。
- 无需功能门。
- 稳定，未来版本将提供长期支持。