= Monitores de limiar dinĂ˘mico
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== VisĂŁo geral

Para mĂŠtricas que variam significativamente ao longo do tempo e diferem de serviĂ§o para serviĂ§o, um monitor Dynamic Threshold oferece detecĂ§ĂŁo de anomalias simples e eficiente.  Ele usa dados de 1, 2 ou 3 semanas atrĂĄs, alĂŠm do passado recente, como contexto para comparar os dados atuais.

Os dados da "janela de verificaĂ§ĂŁo" sĂŁo comparados com os dados fornecidos pelo contexto histĂłrico usando o teste de Anderson-Darling.  Isso impĂľe muito poucas suposiĂ§Ăľes sobre a distribuiĂ§ĂŁo de dados.  O teste ĂŠ particularmente sensĂ­vel a valores discrepantes nas extremidades superior e inferior da distribuiĂ§ĂŁo.  A mĂŠtrica pode ser suave, pontiaguda ou ter alguns "nĂ­veis" - como os valores dos dados sĂŁo comparados diretamente, sem nenhum ajuste de modelo, o monitor Dynamic Threshold ĂŠ muito robusto.

Para mĂŠtricas que variam suavemente ao longo do tempo (por exemplo, em uma escala de tempo de cinco minutos), o nĂşmero efetivo de pontos de dados ĂŠ menor do que o nĂşmero bruto.  O DT compensa isso para que o mesmo monitor possa ser usado para uma ampla gama de mĂŠtricas sem a necessidade de ajustar seus parĂ˘metros.

HĂĄ alguns parĂ˘metros que podem ser definidos para a funĂ§ĂŁo de monitor:

* `+falsePositiveRate+`: digamos `+!!float 1e-8+` - a sensibilidade do monitor a desvios de comportamento.  Um valor mais baixo suprime mais (falsos) positivos, mas tambĂŠm pode levar a falsos negativos (anomalias nĂŁo percebidas).
* `+checkWindowMinutes+`: digamos `+10+` minutos - a janela de verificaĂ§ĂŁo precisa ser equilibrada entre alertas rĂĄpidos (valores pequenos) e anomalias corretamente identificadas (valores altos).  Um punhado de pontos de dados funciona bem na prĂĄtica.
* `+historicWindowMinutes+`: digamos `+120+` (2 horas) - entre parĂŞnteses em torno do horĂĄrio atual, mas uma ou mais semanas atrĂĄs - portanto, de uma hora antes do horĂĄrio atual atĂŠ uma hora depois.  TambĂŠm sĂŁo usadas as duas horas anteriores Ă  janela de verificaĂ§ĂŁo.  O monitor de limite dinĂ˘mico compara a distribuiĂ§ĂŁo desses dados histĂłricos com os pontos de dados na janela de verificaĂ§ĂŁo.
* `+historySizeWeeks+`: diga `+2+` - o nĂşmero de semanas das quais os dados sĂŁo extraĂ­dos para o contexto histĂłrico.  Pode ser `+1+`, `+2+` ou `+3+`.
* `+removeTrend+`Para mĂŠtricas que tĂŞm comportamento de tendĂŞncia (por exemplo, nĂşmero de solicitaĂ§Ăľes), de modo que o valor absoluto difere de uma semana para outra, essa tendĂŞncia (o valor mĂŠdio) pode ser levada em conta.
* `+includePreviousDay+`: normalmente `+false+` - para mĂŠtricas que nĂŁo tĂŞm um padrĂŁo semanal, mas apenas diĂĄrio, isso permite o uso de dados mais recentes

== Exemplo de monitor de limiar dinĂ˘mico

Um Monitor implementado usando a funĂ§ĂŁo Dynamic Threshold tem a seguinte aparĂŞncia:

----
  - _type: "Monitor"
    name: "<name of the monitor>"
    identifier: "urn:stackpack:<stackpack-name>:monitor:<identifier for the monitor>"
    status: "DISABLED"
    description: "<description>"
    function: {{ get "urn:stackpack:aad-v2:shared:monitor-function:dt" }}
    arguments:
      telemetryQuery:
        query: "<metric to bind to component>"
        unit: s
        aliasTemplate: "<name for the metric>"
      topologyQuery: <topology query for the components to bind to>
      falsePositiveRate: <floating point number, e.g. !!float 1e-8>
      checkWindowMinutes: <integer, e.g. 10>
      historicWindowMinutes: <integer, e.g. 120>
      historySizeWeeks: <integer: 1, 2 or 3>
      includePreviousDay: <boolean>
      removeTrend: <boolean>
    intervalSeconds: 60
    remediationHint: "<how to remediate deviating states>"
----

O monitor pode ser implementado usando o guia em xref:use/alerting/k8s-dynamic-threshold-monitors.adoc[Adicionar um monitor de limite aos componentes usando a CLI]
