= Solução de problemas de monitores
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

* <<_the_result_of_the_monitor_isnt_showing_on_a_component,O resultado do monitor não está sendo exibido em um componente>>
* <<_the_monitor_is_showing_an_error_in_the_monitor_status_overview,O monitor está mostrando um erro na visão geral do status do monitor>>

=== O resultado do monitor não está sendo exibido em um componente

Primeiro, verifique se o monitor está xref:use/alerting/k8s-add-monitors-cli.adoc#_verify_the_execution_of_the_monitor[produzindo resultados]. Se esse for o caso, mas os resultados do monitor não aparecerem nos componentes, pode haver um problema com a ligação. Primeiro, use o seguinte comando para verificar:

[,bash]
----
sts monitor status --id <id>
----

Se a saída tiver `+Monitor health states with identifier which has no matching topology element (<nr>): ....+`, isso mostra que o `+urnTemplate+` pode não gerar um identificador que corresponda à topologia. Para solucionar esse problema xref:use/alerting/k8s-add-monitors-cli.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[, revise seu urnTemplate].

=== O monitor está mostrando um erro na visão geral do status do monitor

Obter o status do monitor por meio da CLI

[,bash]
----
sts monitor status --id <id>
----

A seção `+Monitor Stream errors:+` mostrará os erros que estão ocorrendo no monitor e oferecerá ajuda adicional.

