= Microsoft Entra ID
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted
:experimental:

== Criação de um aplicativo no Entra ID

. Registre um aplicativo no Entra ID seguindo https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app?tabs=client-secret[este guia]
 .. Como um nome de exibição, você pode usar, por exemplo, `SUSE Observability`
 .. Selecione a plataforma `Web` e especifique o URL de redirecionamento: `https://<your-stackstate-installation>/loginCallback?client_name=StsOidcClient`
 .. Ao adicionar credenciais, use as credenciais `client secret` e certifique-se de armazenar o segredo
. As outras seções da seção `Prepare for development` não são obrigatórias, mas, para uma instalação de produção, você deve segui-las para definir um proprietário e possivelmente pré-aprovar determinados escopos (consulte a próxima seção para saber quais escopos o SUSE Observability solicitará)
. Por fim, certifique-se de que o SUSE Observability receberá os grupos de um usuário (necessários para a autorização) adicionando a reivindicação de grupos ao registro do aplicativo usando https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims?tabs=appui#_configure_groups_optional_claims[este guia]. Selecione os tipos de grupos que deseja expor; o restante deste documento pressupõe que você não personalizou as propriedades do token e que o SUSE Observability recebe o ID do grupo.

== Configuração do SUSE Observability

Usando as informações de registro do aplicativo, crie um novo arquivo `authentication.yaml` para o SUSE Observability:

----
stackstate:
  authentication:
    oidc:
      # The client id is in the list of essentials on the overview page of the App registration
      clientId: "<Application (client) ID>"
      secret: "<Application (client) secret>"
      # The Directory (Tenant) ID is in the list of essentials on the overview page of the App registration
      discoveryUri: "https://login.microsoftonline.com/<Directory (tenant) ID>/v2.0/.well-known/openid-configuration"
      jwsAlgorithm: RS256
      scope: ["openid", "email", "profile", "offline_access"]
      jwtClaims:
        usernameField: "email"
        groupsField: groups
    roles:
      guest: []
      powerUser: []
      admin: [ "aaaaaaaa-bbbb-1111-2222-aabbccddeeff", "eeeeeeeeee-bbbb-1111-2222-aabbccddeeff" ]
      k8sTroubleshooter: []
----

Obter os valores para:

* ID do aplicativo (cliente): na seção Essentials na página Visão geral do registro do aplicativo
* Segredo do aplicativo (cliente): criado na etapa 1 da seção anterior e salvo em algum lugar
* ID do diretório (locatário): na seção Essentials na página Overview (Visão geral) do registro do aplicativo
* Os IDs de grupo para as diferentes funções: no Entra ID admin, navegue até menu:IdentityAll[Groups]. Os IDs de grupo estão na segunda coluna, denominada `Object Id`. Decida quais grupos do Entra ID devem ter qual nível de permissões e atribua-os a suas respectivas funções no exemplo de yaml acima (removendo os dois exemplos de ids de grupo).

Agora, reimplante o SUSE Observability com o comando helm usado para instalar, mas agora inclua o novo arquivo `authentication.yaml`, `helm upgrade ... --values authentication.yaml`. Certifique-se de sempre incluir esse arquivo ao fazer a atualização.

=== Escopos usados

O SUSE Observability está configurado para solicitar 4 escopos:

* openid, para fazer a autenticação
* e-mail, para identificar usuários
* para poder solicitar o perfil de usuário que contém os grupos para os usuários
* offline_access, para poder manter um usuário conectado por mais tempo sem reautenticação e para permitir que o usuário use tokens da API do SUSE Observabilities.

Para obter mais detalhes, consulte https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent[Permissões e consentimento na plataforma de identidade da Microsoft (learn.microsoft.com)].
