= k3s etcd-snapshot
:page-languages: [EN, JA, KO, ZH]
:revdate: 2025-09-17
:page-revdate: {revdate}

本页介绍如何使用`+k3s etcd-snapshot+` CLI 工具管理 etcd 快照，以及如何从 etcd 快照中还原。

K3s etcd 快照存储在节点文件系统中，也可选择上传到 S3 兼容对象存储区，用于灾难恢复。快照既可以按重复性计划自动执行，也可以按需手动执行。`+k3s etcd-snapshot+` CLI 工具提供一组子命令，可用于创建、删除和管理快照。

|===
| 子命令 | 说明

| `+delete+`
| 删除给定快照

| `+ls+`, `+list+`, `+l+`
| 列出快照

| `+prune+`
| 删除超过配置保留次数的快照

| `+save+`
| 按需触发 etcd 快照
|===

有关 etcd 快照子命令的更多信息，请运行`+k3s etcd-snapshot --help+` 。

== 创建快照

[tabs,sync-group-id=snapshots]
======
计划::
+
--
默认情况下，在系统时间 00:00 和 12:00 启用计划快照，保留 5 个快照。计划快照的名称以`+etcd-snapshot+` 开头，后面是节点名称和时间戳。

以下选项可控制计划快照的操作：

|===
| 旗帜 | 说明

| `+--etcd-disable-snapshots+`
| 禁用计划快照。

| `+--etcd-snapshot-name+`
| 设置 etcd 计划快照的基本名称。(默认值：`+etcd-snapshot+`)

| `+--etcd-snapshot-compress+`
| 压缩 etcd 快照

| `+--etcd-snapshot-dir+`
| 保存数据库快照的目录。(默认位置：`+$<data-dir>/db/snapshots+`)

| `+--etcd-snapshot-retention+`
| 要保留的快照数量。(默认值：5)

| `+--etcd-snapshot-schedule-cron+`
| cron 规格中的快照间隔时间。例如，每 5 小时`+0 */5 * * *+` （默认值：`+0 */12 * * *+` ）。
|===

data-dir 值默认为`+/var/lib/rancher/k3s+` ，可通过设置`+--data-dir+` 标志单独更改。

计划快照会保存到服务器`+--etcd-snapshot-dir+` 值所设置的路径。如果希望在兼容 S3 的对象存储中进行复制，请参阅xref:#_s3_compatible_object_store_support[S3 配置选项]。
--

按需::
+
--
可通过运行`+k3s etcd-snapshot save+` 命令手动保存快照。这些按需快照不会保留，用户需要使用`+k3s etcd-snapshot delete+` 或`+k3s etcd-snapshot prune+` 命令手动删除它们。按需快照的名称以`+on-demand+` 开头，后面是节点名称和时间戳。

以下选项可控制按需快照的操作：

|===
| 旗帜 | 说明

| `+--name+`
| 设置 etcd 按需快照的基本名称。(默认值：`+on-demand+`)

| `+--etcd-snapshot-compress+`
| 压缩 etcd 快照

| `+--etcd-snapshot-dir+`
| 保存数据库快照的目录。(默认位置：`+$<data-dir>/db/snapshots+`)
|===

data-dir 值默认为`+/var/lib/rancher/k3s+` ，可通过设置`+--data-dir+` 标志单独更改。

`+--name+` 标志只能在运行`+k3s etcd-snapshot save+` 命令时设置。另外两个也可以是`+k3s server+` xref:installation/configuration.adoc#_configuration_file[配置文件]的一部分。

按需快照会保存到服务器`+--etcd-snapshot-dir+` 值所设置的路径。如果希望在兼容 S3 的对象存储中进行复制，请参阅xref:#_s3_compatible_object_store_support[S3 配置选项]。
--
======

== 删除快照

当快照数量超过配置的保留次数（默认为 5 次）时，计划快照会被自动删除。首先删除最旧的快照。

要手动删除计划快照或按需快照，可以使用`+k3s etcd-snapshot delete+` 命令：

[,bash]
----
k3s etcd-snapshot delete <SNAPSHOT-NAME-1> <SNAPSHOT-NAME-2> ...
----

`+prune+` 子命令会删除与名称前缀匹配（默认为`+on-demand+` ）且超过配置保留次数的快照。它包括用于设置保留计数的标志`+--snapshot-retention+` 。对于计划快照，它会覆盖默认保留策略。按需快照没有保留策略，因此需要使用此标记。

将 "按需 "快照剪裁到较小的数量：

[,bash]
----
k3s etcd-snapshot prune --snapshot-retention  <NUM-OF-SNAPSHOTS-TO-RETAIN>
----

将 "计划 "快照剪裁到较小的数量：

[,bash]
----
k3s etcd-snapshot prune --name etcd-snapshot --etcd-snapshot-retention <NUM-OF-SNAPSHOTS-TO-RETAIN>
----

=== 支持 S3 兼容对象存储

K3s 支持将 etcd 快照复制到与 S3 兼容的对象存储并从中恢复 etcd 快照。S3 支持按需快照和计划快照。

|===
| 旗帜 | 说明

| `+--etcd-s3+`
| 启用备份到 S3

| `+--etcd-s3-endpoint+`
| S3 端点 url

| `+--etcd-s3-endpoint-ca+`
| 连接到 S3 端点的 S3 自定义 CA 证书

| `+--etcd-s3-skip-ssl-verify+`
| 禁用 S3 SSL 证书验证

| `+--etcd-s3-access-key+`
| S3 访问密钥

| `+--etcd-s3-secret-key+`
| S3 密钥

| `+--etcd-s3-bucket+`
| S3 桶名称

| `+--etcd-s3-region+`
| S3 区域/邮筒位置（可选）。默认为`+us-east-1+` 。

| `+--etcd-s3-folder+`
| S3 文件夹

| `+--etcd-s3-proxy+`
| 连接 S3 时使用的代理服务器，覆盖任何代理重置的环境变量

| `+--etcd-s3-insecure+`
| 禁用通过 HTTPS 的 S3

| `+--etcd-s3-timeout+`
| S3 超时（默认值：`+5m0s+`)

| `+--etcd-s3-config-secret+`
| 如果启用了 etcd-s3，且未设置其他 etcd-s3 选项，用于配置 S3 的 kube-system 命名空间中的密文名称
|===

例如，在 S3 中按需创建和删除 etcd 快照的工作原理是这样的：

[,shell-session]
----
$ k3s etcd-snapshot --s3 --s3-bucket=test-bucket --s3-access-key=test --s3-secret-key=secret save
INFO[0155] Snapshot on-demand-server-0-1753178523 saved. 
INFO[0155] Snapshot on-demand-server-0-1753178523 saved. 

$ k3s etcd-snapshot --s3 --s3-bucket=test-bucket --s3-access-key=test --s3-secret-key=secret ls
Name                              Location                                                                          Size    Created
on-demand-server-0-1753178523     s3://test-bucket/test-folder/on-demand-server-0-1753178523                        5062688 2025-07-22T10:02:03Z
on-demand-server-0-1753178523     file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-server-0-1753178523     5062688 2025-07-22T10:02:03Z

$ k3s etcd-snapshot --s3 --s3-bucket=test-bucket --s3-access-key=test --s3-secret-key=secret delete on-demand-server-0-1753178523
INFO[0000] Snapshot on-demand-server-0-1753178523 deleted.

$ k3s etcd-snapshot --s3 --s3-bucket=test-bucket --s3-access-key=test --s3-secret-key=secret ls
Name                              Location                                                                          Size    Created
----

=== S3 保留

[NOTE]
.版本闸门
====
从版本 v1.34.0+k3s1、v1.33.4+k3s1、v1.32.8+k3s1、v1.31.12+k3s1 开始，K3s 包含一个用于 S3 保留的新标记。它的默认值与本地快照保留相同。
====

|===
| 旗帜 | 说明

| `+--etcd-s3-retention+`
| 要保留的 S3 快照数量。(默认值：`+5+`)
|===

=== S3 配置密文支持

[NOTE]
.版本闸门
====
2024 年 8 月发布的版本：v1.30.4+k3s1、v1.29.8+k3s1、v1.28.13+k3s1 支持 S3 配置机密。
====

K3s 支持从 Kubernetes Secret 读取 etcd S3 快照配置。
出于安全考虑，或需要在不重启 K3s 的情况下轮换凭据时，这可能比在 K3s CLI 标志或配置文件中硬编码凭据更可取。
要通过 Secret 传递 S3 快照配置，请使用`+--etcd-s3+` 和`+--etcd-s3-config-secret=<SECRET-NAME>+` 启动 K3s 。
在 K3s 启动时，该秘密并不需要存在，但每次执行快照保存/列表/删除/修剪操作时，都会对其进行检查。

还原快照时不能使用 S3 配置密文，因为 apiserver 无法在还原过程中提供密文。
恢复存储在 S3 上的快照时，必须通过 CLI 传递 S3 配置。

[NOTE]
====
仅通过`+--etcd-s3+` 和`+--etcd-s3-config-secret+` 标志启用秘密。
如果设置了任何其他 S3 配置标志，该 Secret 将被忽略。
====

密文中的键与上述`+--etcd-s3-*+` CLI 标志相对应。
`+etcd-s3-endpoint-ca+` 密钥可接受 PEM 编码的 CA 捆绑包，或`+etcd-s3-endpoint-ca-name+` 密钥可用于指定`+kube-system+` 名称空间中包含一个或多个 PEM 编码 CA 捆绑包的 ConfigMap 名称。

[,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: k3s-etcd-snapshot-s3-config
  namespace: kube-system
type: etcd.k3s.cattle.io/s3-config-secret
stringData:
  etcd-s3-endpoint: ""
  etcd-s3-endpoint-ca: ""
  etcd-s3-endpoint-ca-name: ""
  etcd-s3-skip-ssl-verify: "false"
  etcd-s3-access-key: "AWS_ACCESS_KEY_ID"
  etcd-s3-secret-key: "AWS_SECRET_ACCESS_KEY"
  etcd-s3-bucket: "bucket"
  etcd-s3-folder: "folder"
  etcd-s3-region: "us-east-1"
  etcd-s3-insecure: "false"
  etcd-s3-timeout: "5m"
  etcd-s3-proxy: ""
----

== 恢复快照

恢复快照时，K3s 会执行几个步骤：

. 如果快照存储在 S3 上，文件会下载到快照目录中。
. 如果快照是压缩的，则会被解压缩。
. 如果存在，当前 etcd 数据库文件将被移至`+<data-dir>/server/db/etcd-old-$TIMESTAMP/+` 。
. 快照的内容会被提取到磁盘上，并对校验和进行验证。
. 启动 Etcd，并从集群中删除除当前节点外的所有 etcd 集群成员。
. CA 证书和其他机密数据会从数据存储中提取并写入磁盘，以供日后使用。
. 还原完成后，就可以在执行还原的服务器上重新启动并正常使用 K3。
. (可选）可正常启动代理和控制平面服务器。
. (可选）删除旧数据库文件后，可重新启动 Etcd 服务器以重新加入群集。

还原快照时，不需要使用创建快照的相同 K3s 版本；也可以使用更高的次版本。

[#_snapshot_restore_steps]
=== 快照恢复步骤

选择下面与您的群集配置相匹配的选项卡。

[tabs,sync-group-id=etcdsnap]
======
单服务器::
+
--
. 停止 K3s 服务：
+
[,bash]
----
systemctl stop k3s
----

. 使用`+--cluster-reset+` 标志运行`+k3s server+` ，`+--cluster-reset-restore-path+` 表示要还原的快照的路径。
   如果快照存储在 S3 上，请提供 S3 配置标志（`+--etcd-s3+` 、`+--etcd-s3-bucket+` 等），并只提供快照的文件名作为还原路径。
+
[NOTE]
====
使用`+--cluster-reset+` 标志而不指定要还原的快照，只会将 etcd 集群重置为单一成员，而不会还原快照。
====
+
[,bash]
----
k3s server \
  --cluster-reset \
  --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>
----
+
**结果**K3s 会恢复快照并重置群集成员资格，然后打印一条信息，说明已准备好重新启动：
`+Managed etcd cluster membership has been reset, restart without --cluster-reset flag now.+`

. 再次启动 K3s：
+
[,bash]
----
systemctl start k3s
----

如果在 K3s 配置文件中定义了 etcd-s3 备份配置，K3s 还原会尝试从配置的 S3 存储桶中提取快照文件。在这种情况下，参数`+--cluster-reset-restore-path+` 中只需传递快照文件名。要从存在 etcd-s3 备份配置的本地快照文件还原，请添加参数`+--etcd-s3=false+` ，并在参数`+--cluster-reset-restore-path+` 中传递本地快照文件的完整路径。

作为一种安全机制，当 K3s 重置群集时，它会在`+/var/lib/rancher/k3s/server/db/reset-flag+` 上创建一个空文件，防止用户意外连续运行多个群集重置。K3s 正常启动后，该文件将被删除。
--

多个服务器::
+
--
本例中有 3 台服务器，分别是`+S1+` 、`+S2+` 和`+S3+` 。快照位于`+S1+` 。

. 停止所有服务器上的 K3
+
[,bash]
----
systemctl stop k3s
----

. 在 S1 上，使用`+--cluster-reset+` 选项运行`+k3s server+` ，`+--cluster-reset-restore-path+` 表示要还原的快照的路径。
   如果快照存储在 S3 上，请提供 S3 配置标志（`+--etcd-s3+` 、`+--etcd-s3-bucket+` 等），并只提供快照的文件名作为还原路径。
+
[NOTE]
====
使用`+--cluster-reset+` 标志而不指定要还原的快照，只会将 etcd 集群重置为单一成员，而不会还原快照。
====
+
[,bash]
----
k3s server \
  --cluster-reset \
  --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>
----
+
**结果**K3s 会恢复快照并重置群集成员资格，然后打印一条信息，说明已准备好重新启动：
`+Managed etcd cluster membership has been reset, restart without --cluster-reset flag now.+`
`+Backup and delete $\{datadir}/server/db on each peer etcd server and rejoin the nodes.+`

. 在 S1，再次开始 K3：
+
[,bash]
----
systemctl start k3s
----

. 在 S2 和 S3 上，删除数据目录`+/var/lib/rancher/k3s/server/db/+` ：
+
[,bash]
----
rm -rf /var/lib/rancher/k3s/server/db/
----

. 在 S2 和 S3 上，再次启动 K3，加入已恢复的群集：
+
[,bash]
----
systemctl start k3s
----

如果在 K3s 配置文件中定义了 etcd-s3 备份配置，K3s 还原会尝试从配置的 S3 存储桶中提取快照文件。在这种情况下，参数`+--cluster-reset-restore-path+` 中只需传递快照文件名。要从存在 etcd-s3 备份配置的本地快照文件还原，请添加参数`+--etcd-s3=false+` ，并在参数`+--cluster-reset-restore-path+` 中传递本地快照文件的完整路径。

作为一种安全机制，当 K3s 重置群集时，它会在`+/var/lib/rancher/k3s/server/db/reset-flag+` 上创建一个空文件，防止用户意外连续运行多个群集重置。K3s 正常启动后，该文件将被删除。
--
======

==== 恢复到新主机

可以将 etcd 快照还原到不同的主机上。这样做时，您必须传递拍摄快照时最初使用的xref:cli/token.adoc#_server[服务器令牌]，因为它用于解密快照内的引导数据。过程与上述相同，但将第 2 步改为

. 在拍摄快照的节点中保存以下值：`+/var/lib/rancher/k3s/server/token+` 。在第 3 步中，`+<BACKED-UP-TOKEN-VALUE>+` 。
. 将快照复制到新节点。节点中的路径在步骤 3 中为`+<PATH-TO-SNAPSHOT>+` 。
. 使用以下命令从第一个服务器节点上的快照启动还原：
+
[,bash]
----
k3s server \
  --cluster-reset \
  --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>
  --token=<BACKED-UP-TOKEN-VALUE>
----
+
令牌值也可以在 K3s 配置文件中设置。


[WARNING]
======
. 节点资源也包含在 etcd 快照中。如果恢复到一组新节点，则需要手动删除群集中已不存在的旧节点。
. 如果 K3s 配置文件中设置了令牌，请确保该令牌与`+<BACKED-UP-TOKEN-VALUE>+` 相同，否则 K3s 无法启动。
======

== ETCDSnapshotFile 自定义资源

[NOTE]
.版本闸门
====
ETCDSnapshotFiles 已于 2023 年 11 月发布：v1.28.4+k3s2、v1.27.8+k3s2、v1.26.11+k3s2、v1.25.16+k3s4。
====

通过列出或描述群集范围内的`+ETCDSnapshotFile+` 资源，可使用任何 Kubernetes 客户端远程查看快照。`+k3s etcd-snapshot list+` 命令只显示该节点可见的快照，而`+ETCDSnapshotFile+` 资源则跟踪群集成员上存在的所有快照。

[,shell-session]
----
$ kubectl get etcdsnapshotfile
NAME                                             SNAPSHOTNAME                        NODE           LOCATION                                                                            SIZE      CREATIONTIME
local-on-demand-k3s-server-1-1730308816-3e9290   on-demand-k3s-server-1-1730308816   k3s-server-1   file:///var/lib/rancher/k3s/server/db/snapshots/on-demand-k3s-server-1-1730308816   2891808   2024-10-30T17:20:16Z
s3-on-demand-k3s-server-1-1730308816-79b15c      on-demand-k3s-server-1-1730308816   s3             s3://etcd/k3s-test/on-demand-k3s-server-1-1730308816                                2891808   2024-10-30T17:20:16Z
----

[,shell-session]
----
$ kubectl describe etcdsnapshotfile s3-on-demand-k3s-server-1-1730308816-79b15c
Name:         s3-on-demand-k3s-server-1-1730308816-79b15c
Namespace:
Labels:       etcd.k3s.cattle.io/snapshot-storage-node=s3
Annotations:  etcd.k3s.cattle.io/snapshot-token-hash: b4b83cda3099
API Version:  k3s.cattle.io/v1
Kind:         ETCDSnapshotFile
Metadata:
  Creation Timestamp:  2024-10-30T17:20:16Z
  Finalizers:
    wrangler.cattle.io/managed-etcd-snapshots-controller
  Generation:        1
  Resource Version:  790
  UID:               bec9a51c-dbbe-4746-922e-a5136bef53fc
Spec:
  Location:   s3://etcd/k3s-test/on-demand-k3s-server-1-1730308816
  Node Name:  s3
  s3:
    Bucket:           etcd
    Endpoint:         s3.example.com
    Prefix:           k3s-test
    Region:           us-east-1
    Skip SSL Verify:  true
  Snapshot Name:      on-demand-k3s-server-1-1730308816
Status:
  Creation Time:  2024-10-30T17:20:16Z
  Ready To Use:   true
  Size:           2891808
Events:
  Type    Reason               Age   From            Message
  ----    ------               ----  ----            -------
  Normal  ETCDSnapshotCreated  113s  k3s-supervisor  Snapshot on-demand-k3s-server-1-1730308816 saved on S3
----
