= k3s 秘密加密
:page-languages: [EN, JA, KO, ZH]
:revdate: 2026-01-05
:page-revdate: {revdate}

K3s 支持启用静态机密加密。更多信息，请参阅xref:security/secrets-encryption.adoc[机密加密]。

== 秘密加密工具

[IMPORTANT]
.版本闸门
====
自https://github.com/k3s-io/k3s/releases/tag/v1.21.8%2Bk3s1[v1.21.8+k3s1]起可用
====


K3s 包含一个 CLI 工具`+secrets-encrypt+` ，可以自动控制以下内容：

* 禁用/启用机密加密
* 添加新的加密密钥
* 旋转和删除加密密钥
* 重新加密机密

[CAUTION]
====
如果不按照正确的程序旋转加密密钥，可能会导致群集永久损坏。谨慎行事。
====

[#_encryption_key_rotation]
=== 加密密钥轮换

[IMPORTANT]
.版本闸门
====
2024 年 9 月发布的版本：v1.30.5+k3s1、v1.31.1+k3s1。
====

[tabs,sync-group-id=se]
======
单服务器::
+
--
在单服务器群集上轮换机密加密密钥：

. 使用标志启动 K3s 服务器 `+--secrets-encryption+`
+
[NOTE]
====
目前_不_支持在未加密的情况下启动 K3s 并在稍后启用加密。
====

. 旋转机密加密密钥
+
----
k3s secrets-encrypt rotate-keys
----

. 等待重新加密完成。观察服务器日志，或者等待：
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
--

高可用性::
+
--
在 HA 设置中轮换机密加密密钥：

. 使用`+--secrets-encryption+` 标志启动所有三个 K3s 服务器。为简洁起见，服务器分别称为 S1、S2 和 S3。
+
[NOTE]
====
目前_不_支持在未加密的情况下启动 K3s 并在稍后启用加密。
====

. 在 S1 上旋转机密加密密钥
+
[,bash]
----
k3s secrets-encrypt rotate-keys
----

. 等待重新加密完成。观察服务器日志，或者等待：
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
+
[NOTE]
====
K3 可以每秒重新加密 ~5 个机密。拥有大量机密的群集可能需要数分钟才能重新加密。您可以在服务器日志中跟踪进度。
====

. 在 S1 上重新启动 K3，参数不变。如果将 K3s 作为服务运行：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. S1 启动后，重新启动 S2 和 S3 上的 K3
--
======

=== 传统加密密钥轮换

[TIP]
.新程序
====
如果使用 K3s 版本 v1.30 以上，建议改用xref:#_encryption_key_rotation[加密密钥旋转]。
====

[tabs,sync-group-id=se]
======
单服务器::
+
--
在单服务器群集上轮换机密加密密钥：

. 使用标志启动 K3s 服务器 `+--secrets-encryption+`
+
[NOTE]
====
目前_不_支持在未加密的情况下启动 K3s 并在稍后启用加密。
====

. 准备
+
[,bash]
----
k3s secrets-encrypt prepare
----

. 使用相同参数杀死并重新启动 K3s 服务器。如果将 K3s 作为服务运行：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. 旋转
+
[,bash]
----
k3s secrets-encrypt rotate
----

. 使用相同参数杀死并重新启动 K3s 服务器
. 重新加密
+
[NOTE]
====
K3 可以每秒重新加密 ~5 个机密。 +
拥有大量机密的群集可能需要数分钟才能重新加密。
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----
--

高可用性::
+
--
嵌入式 DB 和外部 DB 集群的步骤相同。

在 HA 设置中轮换机密加密密钥：

. 使用`+--secrets-encryption+` 标志启动所有三个 K3s 服务器。为简洁起见，服务器分别称为 S1、S2 和 S3。
+
[NOTE]
====
* 目前_不_支持在未加密的情况下启动 K3s 并在稍后启用加密。
* 虽然不是必须的，但建议您选择一个服务器节点来运行`+secrets-encrypt+` 命令。
====
. 准备 S1
+
[,bash]
----
k3s secrets-encrypt prepare
----

. 使用相同参数杀死并重新启动 S1。如果将 K3s 作为服务运行：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. S1 启动后，杀死并重新启动 S2 和 S3
. 在 S1 上旋转
+
[,bash]
----
k3s secrets-encrypt rotate
----

. 使用相同参数杀死并重新启动 S1
. S1 启动后，杀死并重新启动 S2 和 S3
. 在 S1 上重新加密
+
[NOTE]
====
K3 可以每秒重新加密 ~5 个机密。 +
拥有大量机密的群集可能需要数分钟才能重新加密。
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----

. 使用相同参数杀死并重新启动 S1
. S1 启动后，杀死并重新启动 S2 和 S3
--
======

=== 秘密加密 禁用/重新启用

[tabs,sync-group-id=se]
======
单服务器::
+
--
使用`+--secrets-encryption+` 标志启动服务器后，可禁用机密加密。

在单节点群集上禁用机密加密：

. 禁用
+
[,bash]
----
k3s secrets-encrypt disable
----

. 使用相同参数杀死并重新启动 K3s 服务器。如果将 K3s 作为服务运行：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. 使用标记重新加密
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

在单节点群集上重新启用机密加密：

. 启用
+
[,bash]
----
k3s secrets-encrypt enable
----

. 使用相同参数杀死并重新启动 K3s 服务器
. 使用标记重新加密
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--

高可用性::
+
--
使用`+--secrets-encryption+` 标志启动 HA 群集后，可禁用机密加密。

[NOTE]
====
虽然不是必须的，但建议您选择一个服务器节点来运行`+secrets-encrypt+` 命令。
====

为简洁起见，本指南中使用的三台服务器将分别称为 S1、S2 和 S3。

要在 HA 群集上禁用机密加密：

. 在 S1 上禁用
+
[,bash]
----
k3s secrets-encrypt disable
----

. 使用相同参数杀死并重新启动 S1。如果将 K3s 作为服务运行：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. S1 启动后，杀死并重新启动 S2 和 S3
. 使用 S1 上的标记重新加密
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

要在 HA 群集上重新启用机密加密：

. 启用 S1
+
[,bash]
----
k3s secrets-encrypt enable
----

. 使用相同参数杀死并重新启动 S1
. S1 启动后，杀死并重新启动 S2 和 S3
. 使用 S1 上的标记重新加密
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--
======

=== 秘密 加密状态

secrets-encrypt 工具包括一个`+status+` 命令，可显示节点上当前秘密加密状态的信息。

单服务器节点上的命令示例：

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
----

另一个关于 HA 集群的例子，在旋转密钥之后，但在重新启动服务器之前：

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: rotate
Server Encryption Hashes: hash does not match between node-1 and node-2

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2021-12-10T22:54:38Z
        AES-CBC   aescbckey
----

各部分详情如下：

* *加密状态*：显示节点上是否禁用或启用了机密加密
* *当前轮换阶段*：表示节点当前的旋转阶段。 +
阶段是`+start+`,`+prepare+`,`+rotate+`,`+reencrypt_request+`,`+reencrypt_active+` 、 `+reencrypt_finished+`
* *服务器加密哈希*值：对于 HA 集群很有用，它表示所有服务器的本地文件是否处于同一阶段。这可用于确定在进入下一阶段之前是否需要重新启动服务器。在上面的 HA 示例中，节点-1 和节点-2 的哈希值不同，表明它们目前没有相同的加密配置。重启服务器将同步它们的配置。
* *主要表格*：汇总节点上发现的机密加密密钥信息。
 ** *活跃*：*"表示当前用于机密加密的密钥（如果有）。Kubernetes 使用活动密钥对任何新机密进行加密。
 ** *钥匙类型*：使用该工具的所有按键均为`+AES-CBC+` 类型。更多信息，请访问https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers[。]
 ** *名称*：加密密钥的名称。
