include::partial$variables.adoc[]
= Audit Scanner - Limites
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Découvrez les limites de l'utilisation du scanner d'audit pour évaluer les politiques et les types d'événements dans un environnement Kubernetes, y compris son utilisation pour l'évaluation des politiques et des types d'événements.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-policy-developer", "kubewarden-integrator"].
:doc-topic: ["explications", "audit-scanner", "limitations"].
:doc-type: ["explanation"]
:keywords: ["kubewarden", "kubernetes", "audit scanner"].
:sidebar_label: Limites
:current-version: {page-origin-branch}

== Types d'événements pris en charge

Les politiques peuvent inspecter les événements `+CREATE+`, `+UPDATE+` et `+DELETE+`.

Le scanner d'audit ne peut pas simuler les événements `+UPDATE+`, car il ne sait pas quelle partie de la ressource doit être modifiée.

Ainsi, le scanner d'audit ignore une politique qui ne concerne que les événements `+UPDATE+`. scanner.

[NOTE]
====

La version 1.7.0 de l'audit-scanner ne prend en charge que les événements `+CREATE+`. Le traitement des événements`+DELETE+` sera bientôt disponible.

====


== Politiques reposant sur les informations relatives aux utilisateurs et aux groupes d'utilisateurs

Chaque objet de demande d'admission Kubernetes contient des informations sur l'utilisateur (ou ServiceAccount) à l'origine de l'événement et sur le groupe auquel il appartient.

Tous les événements simulés par le scanner d'audit proviennent du même utilisateur et du même groupe codés en dur. C'est pourquoi les politiques qui s'appuient sur ces valeurs pour prendre leurs décisions ne produiront pas de résultats significatifs.

Dans ce cas, configurez la politique comme n'étant pas auditable. contrôles.

== Politiques reposant sur des données externes

Les politiques peuvent demander et utiliser des données externes lors d'une évaluation. Vous pouvez évaluer ces politiques à l'aide des contrôles d'audit, mais leurs résultats peuvent changer en fonction des données externes.

== Utilisation de `+*+` par les politiques

Les ressources personnalisées `+AdmissionPolicy+` et `+ClusterAdmissionPolicy+` comportent les champs suivants :

[subs="+attributes",yaml]
----
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
----

Les attributs `+apiGroups+`, `+apiVersions+` et `+resources+` peuvent utiliser le caractère de remplacement`+*+`. Ce symbole générique fait en sorte que la politique corresponde à toutes les valeurs utilisées dans le champ. Le scanner d'audit ignore les politiques qui utilisent le symbole `+*+`.
