= 机密加密配置
:page-languages: [EN, JA, KO, ZH]
:revdate: 2026-03-03
:page-revdate: {revdate}

K3s 支持启用静态机密加密。首次启动服务器时，通过`+--secrets-encryption+` 标志将自动执行以下操作：

* 生成 AES-CBC 密钥
* 用生成的密钥生成加密配置文件
* 将配置作为 encryption-provider-config 传递给 KubeAPI

[TIP]
====
如果不重启现有服务器，则无法启用保密加密功能。 +
如果从脚本安装，请使用`+curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server --secrets-encryption+` ，或使用xref:installation/configuration.adoc#_configuration_with_install_script[配置选项]中描述的其他方法。
====

== 选择加密提供商

[IMPORTANT]
.版本闸门
====
2025 年 4 月发布的版本包括：v1.30.12+k3s1、v1.31.8+k3s1、v1.32.4+k3s1、v1.33.0+k3s1。
====

使用`+--secrets-encryption-provider+` 标志，可以从以下 K3 支持的加密提供商中进行选择：

* `+aescbc+`:AES-CBC 带 PKCS#7 填充。这是默认提供程序。
* `+secretbox+`:XSalsa20 和 Poly1305

### 迁移提供商

您可以按照以下步骤从`+aescbc+` 提供商迁移到`+secretbox+` 提供商：

. 确保 K3s 版本支持`+secretbox+` 提供商。
. 将 K3s 配置文件中的`+secrets-encryption-provider+` 标志更新为`+secretbox+` 。
. 按照下面的加密密钥旋转部分xref:cli/secrets-encrypt.adoc#_encryption_key_rotation[旋转]加密密钥。

== 生成加密配置文件

使用`+--secrets-encryption+` 启动服务器时，K3s 将在`+/var/lib/rancher/k3s/server/cred/encryption-config.json+` 生成加密配置文件。

下面是使用默认`+aescbc+` 提供商生成加密配置文件的示例：

[,json]
----
{
  "kind": "EncryptionConfiguration",
  "apiVersion": "apiserver.config.k8s.io/v1",
  "resources": [
    {
      "resources": [
        "secrets"
      ],
      "providers": [
        {
          "aescbc": {
            "keys": [
              {
                "name": "aescbckey",
                "secret": "xxxxxxxxxxxxxxxxxxx"
              }
            ]
          }
        },
        {
          "identity": {}
        }
      ]
    }
  ]
}
----

== 秘密加密工具

K3s 包含一个实用工具`+secrets-encrypt+` ，可以自动控制以下方面：

* 禁用/启用机密加密
* 添加新的加密密钥
* 旋转和删除加密密钥
* 重新加密机密

更多信息，请参阅xref:cli/secrets-encrypt.adoc[`+k3s secrets-encrypt+` 命令文档]。
