include::partial$variables.adoc[]
= 情境感知的 CEL 政策
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 配置上下文感知策略，确保跨主机的唯一入口规则，防止与{project-name} 的 CEL 扩展库发生冲突。
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "context-aware", "context", "awaree", "ingress"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "context-aware", "context", "aware", "ingress"]
:sidebar_label: 情境感知政策
:current-version: {page-origin-branch}

{project-name}`cel-policy` 支持xref:reference/spec/05-context-aware-policies.adoc[上下文感知]功能。除了通过接纳请求触发政策评估的资源外，该政策还能读取集群信息，并根据其他现有资源做出决策。

为此，我们可以使用策略中包含的https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[{short-project-name}'s CEL extension libaries for host capabilities]。

== 例如独特的入侵

让我们编写一个策略，在创建或更新 Ingresses 时检查 Ingress 是否唯一，这样主机就最多只有一条 Ingress 规则。

为此，我们声明该政策是情境感知的。我们还声明了读取其他 Ingress 资源所需的细粒度权限。`spec.contextAwareResources` (1)来实现。我们可以像往常一样使用`kwctl` 得到一个起点：

[subs="+attributes",console]
----
$ kwctl scaffold manifest -t ClusterAdmissionPolicy \
  registry://ghcr.io/kubewarden/policies/cel-policy:v1.0.0` \
  --allow-context-aware
----

然后我们就可以对其进行编辑，使其与我们的 Ingress 资源相关：

[subs="+attributes", yaml, title="./cel-policy-ingress.yaml"]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "unique-ingress"
  annotations:
    io.kubewarden.policy.category: Best practices
    io.kubewarden.policy.severity: low
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  failurePolicy: Fail
  rules:
    - apiGroups: ["networking.k8s.io"]
      apiVersions: ["v1"]
      resources: ["ingresses"]
      operations: ["CREATE", "UPDATE"]
  contextAwareResources: # (1)
    - apiVersion: networking.k8s.io/v1
      kind: Ingress

----

现在，我们需要编写 CEL 代码，以获取集群中现有的 Ingresses。为此，我们使用 [{short-project-name} CEL 扩展库](https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities)。
尤其是`kw.k8s` 主机功能，它允许我们查询群集的 GroupVersionKinds。您可以查看 CEL 功能的可用文档 [此处](https://pkg.go.dev/github.com/kubewarden/cel-policy/internal/cel/library)。

与上游 Kubernetes CEL 扩展一样，该库也使用构建器模式；调用 CEL 函数方法会返回一个 CEL 对象，该对象本身也有特定的函数方法。这简化了确定 CEL 代码范围和返回值的过程。

在这种情况下，我们将使用`kw.k8s.apiVersion("v1").kind("Ingress")` ；在这里，我们调用`kw.k8s` 库的`apiVersion()` 函数，它将返回一个`<ClientBuilder>` 对象。该对象具有`<ClientBuilder>.kind()` 方法，可返回一个名为`items` 的数组中的所有资源列表。

这样，我们就可以在一个变量中保存集群中的 Ingresses 列表：

```yaml
variables:
  - name: knownIngresses
    expression: kw.k8s.apiVersion("networking.k8s.io/v1").kind("Ingress").list().items
```

然后，我们从这些 Ingresses 中建立一个主机列表。请注意，每个入口可以有多个主机，因此该表达式包含一个数组的数组（这是目前 CEL 语言的一个限制）：

[subs="+attributes",yaml]
----
variables:
  - name: knownHosts
    expression: |
      variables.knownIngresses.map(i, i.spec.rules.map(r, r.host))
----

然而，这并不能正确处理 UPDATE 操作；为此，我们需要移除当前对象，并从剩余的 Ingresses 中提取主机。
我们可以在`object` 上对当前对象进行`filter()` 。
这样就能正确检查 UPDATE 操作。这也意味着策略也会正确地向审计扫描仪报告结果。它看起来是这样的

[subs="+attributes",yaml]
----
variables:
  - name: knownHosts
    expression: |
      variables.knownIngresses
      .filter(i, (i.metadata.name != object.metadata.name) && (i.metadata.namespace != object.metadata.namespace))
      .map(i, i.spec.rules.map(r, r.host))
----

我们还需要当前 Ingress 请求中的主机列表来进行比较：

[subs="+attributes",yaml]
----
variables:
  - name: desiredHosts
    expression: |
      object.spec.rules.map(r, r.host)
----

有了这两个变量，我们就可以在已知主机和所需主机之间进行集合交集，如果有任何交集，我们就会拒绝：

[subs="+attributes",yaml]
----
validations:
  - expression: |
      !variables.knownHost.exists_one(hosts, sets.intersects(hosts, variables.desiredHosts))
    message: "Cannot reuse a host across multiple ingresses"
----

综上所述，该政策如下：

```yaml title="./cel-policy-ingress.yaml"
apiVersion: policies.kubewarden.io/v1
kind:ClusterAdmissionPolicy 元数据：name："unique-ingress" 注释：io.kubewarden.policy.category：最佳实践 io.kubewarden.policy.severity: low 规格：模块：ghcr.io/kubewarden/policies/cel-policy:v1.0.0 failurePolicy：失败规则：- apiGroups: ["networking.k8s.io"] apiVersions：["v1"] 资源：[操作：[contextAwareResources：- apiVersion: networking.k8s.io/v1 kind：Ingress 设置：变量： - name: knownIngresses expression：| kw.k8s.apiVersion("networking.k8s.io/v1").kind("Ingress").list().items - name: knownHosts 表达式：| variables.knownIngresses .filter(i, (i.metadata.name != object.metadata.name) && (i.metadata.namespace != object.metadata.namespace)) .map(i, i.spec.rules.map(r, r.host)) - name: desiredHosts 表达式：| object.spec.rules.map(r, r.host) validations：- expression：| !variables.knownHosts.exists_one(hosts, sets.intersects(hosts, variables.desiredHosts)) 消息："无法在多个入口重复使用主机"

```

## Deploying the policy

As normal, we can deploy our policy by instantiating its manifest:

```console
$ kubectl apply -f ./cel-policy-example.yaml
```

现在，我们可以通过实例化 Ingresses 对其进行测试。第一个会成功，因为没有其他人瞄准那个主机：

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host-foobar-1
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: service1
            port:
              number: 80
EOF
----

但第二次就会被拒绝：

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host-foobar-2
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service2
            port:
              number: 80
EOF
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-unique-ingress.kubewarden.admission" denied the request:
  Cannot reuse a host across multiple ingresses
----
