= Desactivación de la verificación TLS
:revdate: 2025-08-25
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

== Agente de observabilidad de SUSE

Para desactivar la validación SSL para su xref:/use/security/self-signed-certificates.adoc#_suse_observability_agent[Agente de SUSE Observability], debe configurar el valor de la cadena Helm como se muestra a continuación:

[,bash]
----
--set-string 'global.skipSslValidation'=true \
----

== CLI de SUSE Observability

Para desactivar la validación SSL desde xref:/use/security/self-signed-certificates.adoc#_suse_observability_cli[la CLI de SUSE Observability], debe especificar el indicador `+--skip-ssl+` con los comandos `+sts CLI+`. Para ello, utilice uno de los dos métodos siguientes:

*Método 1*: 

Especifique la bandera `+--skip-ssl+` en el archivo de certificado de CA codificado con PEM para una configuración persistente:

[,bash]
----
sts context save \
 --name staging \
 --url https://staging.internal \
 --api-token YOUR_API_TOKEN \
 --skip-ssl
----

*Método 2*:

Especifique el indicador `+--skip-ssl+` en cualquier comando de la CLI que se utilice para la validación única de certificados:

[,bash]
----
# Using certificate file path
sts agent list \
 --url https://staging.internal \
 --api-token YOUR_API_TOKEN \
 —-skip-ssl


# Using base64-encoded certificate data
sts settings list \
 --url https://staging.internal \
 --api-token YOUR_API_TOKEN \
 —-skip-ssl
----

[WARNING]
====
Si se utiliza la opción `+--skip-ssl+`, se ignorarán las opciones `+STS_CA_CERT_PATH+` y `+STS_CA_CERT_BASE64_DATA+`. Utilícelo con precaución, ya que reduce la seguridad.
====

== Extensión de Rancher UI para SUSE Observability

Para desactivar la validación SSL desde la extensión Rancher UI, debe cambiar la configuración `+agent-tls-mode+`. 

Para cambiar el valor del ajuste a través de la interfaz de usuario, vaya a la página de Ajustes globales y busque el ajuste `+agent-tls-mode+` en la parte inferior de la página. Después de cambiar la configuración a través de la interfaz de usuario, se comprueba que los clusters tengan la condición `+AgentTlsStrictCheck+` establecida en "True" antes de permitir la solicitud. De este modo se evitan las interrupciones debidas a una falta de coincidencia de certificados.
