= Mot de passe unique
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Auto-hébergé

Au départ, {stackstate-product-name} est configuré avec un seul mot de passe, xref:/k8s-suse-rancher-prime.adoc#_installation[configuré lors de l'installation]. Cela permet d'authentifier les utilisateurs à l'aide d'un mot de passe unique qui doit être fourni lors de l'installation. 

C'est la façon la plus simple de commencer avec {stackstate-product-name}, mais pour la production, l'une des autres xref:/setup/security/authentication/authentication_options.adoc[options d'authentification] est recommandée.

== Obtenir le mot de passe d'un secret externe

Si le mot de passe par défaut doit provenir d'un secret externe, suivez xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[ces étapes] mais complétez les données suivantes :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

Le codage du mot de passe peut être l'un des suivants :* Pour un mot de passe en texte brut, indiquez : * Pour un mot de passe crypté, indiquez `$plain$your-password` (`$plain$` est un préfixe indiquant un texte en clair) * Pour un mot de passe crypté, fournir : `bcrypt-hashed-password`. La création d'un hachage crypté du mot de passe peut être réalisée à l'aide de `htpasswd -bnBC 10 "" <password> | tr -d ':\n'`.

== Voir aussi

* xref:/setup/security/authentication/authentication_options.adoc[Options d'authentification]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permissions pour les rôles prédéfinis {stackstate-product-name} ]
* xref:/setup/security/rbac/rbac_roles.adoc[Créer des rôles RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Secrets externes]
