= Identifikatoren
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

== Übersicht

In SUSE Observability werden Bezeichner zur Identifizierung von Objekten verwendet, z. B. von Topologieelementen (Komponenten und Beziehungen) und Funktionen. Auf dieser Seite werden die verschiedenen Arten von Bezeichnern beschrieben, die für Topologieelemente verwendet werden, und es wird erläutert, wie globale Bereichsbezeichner in SUSE Observability strukturiert sind.

== Topologie-Bezeichner

Topologieelemente verwenden in SUSE Observability zwei Arten von Bezeichnern:

* *Identifikatoren für den Integrationsbereich* - dienen der Identifizierung von Komponenten und Beziehungen innerhalb einer Integration. Jede Komponente oder Beziehung hat nur einen Integrationsbereichskennzeichen. Der Bezeichner ist frei wählbar, muss aber im Rahmen der Integration selbst konsistent sein.
* *Globale Bereichskennungen* - werden für die Zusammenführung von Komponenten zwischen Integrationen verwendet, z. B. ServiceNow und SUSE Observability Agent. Jede Komponente kann mehrere globale Bereichsbezeichner haben, während Beziehungen keine globalen Bezeichner haben. Sie werden von SUSE Observability zugewiesen und in Übereinstimmung mit der xref:/configure/topology/identifiers.adoc#_global_scope_identifiers[SUSE Observability-Konvention für globale Bezeichner] formatiert.

Das folgende Codebeispiel zeigt eine Komponente mit beiden Arten von Bezeichnern.

* Kennung des Integrationsbereichs - `this-host-unique-identifier`
* Kennung des globalen Geltungsbereichs - `urn:host:/this-host-fqdn`


[,text]
----
self.component("this-host-unique-identifier", "Host", {
    "name": "this-host",
    "domain": "Webshop",
    "layer": "Machines",
    "identifiers": ["urn:host:/this-host-fqdn"],
    "labels": ["host:this-host", "region:eu-west-1"],
    "environment": "Production"
})
----


== Kennungen für den SUSE Observability Agent

Die globalen Bereichskennungen, die vom SUSE Observability Agent zur Identifizierung synchronisierter Topologieelemente verwendet werden, sind in der folgenden Tabelle aufgeführt.

|===
| Art der Ressource | URN-Bezeichner-Format

| Gastgeber
| `urn:host:/[hostName]`

| Prozess
| `urn:process:/[hostName]:[pid]:[createTime]`

| Container
| `urn:container:/[hostName]:[containerId]`

| Dienst mit Spuren entdeckt
| `urn:service:/[serviceName]`

| Service-Instanz mit Traces entdeckt
| `urn:service-instance:/[serviceName]:/[hostName]`
|===

Siehe die xref:/configure/topology/identifiers.adoc#_stackstate_agent[URN-Beispiele für globale Bereichskennungen aus dem SUSE Observability Agent].

== Globale Geltungsbereichskennungen

Wenn SUSE Observability Komponenten mit übereinstimmenden globalen Bereichskennungen aus verschiedenen externen Quellen empfängt, werden die Komponenten und ihre Eigenschaften (Labels, Streams, Prüfungen) zu einer einzigen Komponente zusammengeführt. Dies ermöglicht es, Daten aus verschiedenen Quellen zu einem einzigen Bild einer IT-Landschaft zu kombinieren.

Globale Bereichskennungen in SUSE Observability sind eine global eindeutige URN, die der folgenden Konvention entspricht:

[,text]
----
urn:<prefix>:<type-name>:<free-form>
----

Beachten Sie, dass nicht alle Zeichen in einem URN-Bezeichner zulässig sind. Sie können Ihre Bezeichner mit dem folgenden URN-Regex überprüfen:

[,text]
----
^urn:[a-z0-9][a-z0-9-]{0,31}:[a-z0-9()+,\-.:=@;$_!*'%/?#]+$
----

Das Format der Segmente `<prefix>` und `<type-name>:<free-form>` wird im Folgenden beschrieben.

=== Prefix

Das Segment `prefix` ist ein obligatorischer Teil eines globalen Identifikators. Er benennt den Bereich, zu dem der Bezeichner gehört, und wird rein zu organisatorischen Zwecken verwendet.

[NOTE]
====
Wenn das Präfix einen StackPack-Namen enthält, unterliegt das Objekt der Kontrolle dieses StackPacks. Dies bedeutet, dass das Objekt deinstalliert wird, wenn das StackPack deinstalliert wird.
====


Anerkannte URN-Präfixe sind:

* `stackpack:<name>` - Objekte, die zu StackPacks gehören.
* `stackpack:<name>:shared` - Objekte, die von Instanzen eines StackPack gemeinsam genutzt werden.
* `stackpack:<name>:instance:{{instanceId}}`- Objekte, die zu einer bestimmten Instanz eines StackPacks gehören, wobei `{{instanceId}}` ein Handlebar ist, der die ID zurückgibt, die während des StackPack-Installationsprozesses für jede bestimmte Instanz des StackPacks bereitgestellt wurde.
* `system:auto` - vom System erstellte Objekte, die zu keinem bestimmten StackPack gehören.

=== Typ-Name und Freiform

Der Identifikator wird durch die Segmente `<type-name>:<free-form>` eindeutig identifiziert.

* `<type-name>` mit dem Domänenobjekttyp des Objekts übereinstimmt, dem der Bezeichner zugewiesen ist (Groß- und Kleinschreibung wird nicht beachtet).
* `<free-form>` ist willkürlich, muss aber für den Typ eindeutig sein. Das Format des Freiform-Segments wird vom Benutzer festgelegt. Er muss nicht mit dem Namen des Objekts übereinstimmen (falls einer vorhanden ist) und kann selbst aus mehreren Segmenten bestehen.

== Beispiel-Identifikatoren

=== Gemeinsames StackPack

Beispiel für URN Global Scope Identifier aus dem gemeinsamen StackPack. Die Objekte werden deinstalliert, wenn das gemeinsame StackPack deinstalliert wird.

* Komponententyp Server:
 ** `urn:stackpack:common:component-type:server`

=== SUSE Observability Agent

Beispiel für URN-Identifikatoren für den globalen Bereich vom SUSE Observability Agent.

* Gastgeber:
 ** `urn:host:/example.org`
* Prozess:
 ** `urn:process:/db.infra.company.org:161841:1602158335000`
* Container:
 ** `urn:container:/compnode5.k8s.example.org:8b18c68a820904c55b4909d7f5a9a52756d45e866c07c92bf478bcf6cd240901`
* Dienst mit Spuren entdeckt:
 ** `urn:service:/prod-db`
* Dienstinstanz mit Spuren entdeckt:
 ** `urn:service-instance:/prod-db:/main.example.org`

=== Andere StackPacks

Beispiel für URN Global Scope Identifier aus verschiedenen StackPacks. Die Objekte werden deinstalliert, wenn das benannte StackPack deinstalliert wird.

* Überprüfen Sie die Funktion AWS Event Run State, die von allen AWS StackPack-Instanzen gemeinsam genutzt wird:
 ** `urn:stackpack:aws:shared:check-function:aws-event-run-state`
* Komponententyp cmdb_ci_netgear im ServiceNow StackPack:
 ** `urn:stackpack:servicenow:componenttype:cmdb_ci_netgear`
