= Authentifizierung
:revdate: 2025-09-08
:page-revdate: {revdate}

Die Authentifizierung erfolgt beim Einschalten der Maschine, wenn _sich_ die Maschine bei {elemental_operator_name}_registriert_.

{elemental-product-name} authentifiziert Hosts standardmäßig über das _Trusted Platform Module_ (TPM): Der Rechner wird durch _Attestierung_ authentifiziert, d. h. der Rechner weist seine Identität über sein TPM-Gerät nach.

Damit _die Bescheinigung_ funktioniert,*muss* jeder Rechner, der an Bord kommt,*ein TPM 2.0-Gerät haben*, sonst kann er sich nicht mit der sicheren TPM-Authentifizierung registrieren.

== TPM-Alternativen

*Die einzige offiziell unterstützte Registrierungsmethode basiert auf der TPM-Attestierung und erfordert Geräte mit aktiviertem TPM 2.0.*

Wenn Sie Geräte ohne TPM 2.0-Chip unter Umgehung der sicheren Authentifizierung registrieren möchten, gibt es mehrere Möglichkeiten, diese Geräte eindeutig _zu identifizieren_ und die Registrierung zu ermöglichen:

* Emulation eines TPM-Geräts durch eine einfache Software-Implementierung
* sich über ihre Netzwerk-MAC-Adresse zu identifizieren
* sich mit ihrer SMBIOS-UUID zu identifizieren

Die Authentifizierungs-/Identifizierungsmethode kann imxref:references/machineregistration-reference.adoc#_config_elemental_registration[Feld config:elemental:registration:auth] der Ressource MachineRegistration angegeben werden.

[CAUTION]
====
Die einzige sichere und offiziell unterstützte *Authentifizierungsmethode* in {elemental-product-name} ist die Standardmethode, die auf der TPM-Bestätigung basiert.
Die TPM-Alternativen können für Demozwecke oder lokale Implementierungen verwendet werden, sind aber für den Produktionseinsatz nicht zu empfehlen, da die Identität des Onboarding-Rechners nicht sicher überprüft wird.
====

=== TPM-Emulation

Die TPM-Emulation führt die Authentifizierung mithilfe einer Software durch, die das TPM-Verhalten nachahmt und in die {elemental_register_name} eingebettet ist.
Die Schlüssel des emulierten TPM-Geräts werden alle von einem einzigen Seed auf deterministische Weise generiert: derselbe Seed führt zu denselben TPM-Schlüsseln, so dass auf jedem registrierenden Host ein anderer Seed verwendet werden sollte.

Die TPM-Emulation wird durch die Konfiguration der Felder `+emulate-tpm+` und `+emulated-tpm-seed+` in der Konfiguration `+MachineRegistration+` aktiviert (weitere Einzelheiten finden Sie im xref:references/machineregistration-reference.adoc#_config_elemental_registration[Abschnitt config:elemental:registration in der MachineRegistration-Referenz] ).

.Beispiel MachineRegistration mit TPM-Emulation
[,yaml]
----
include::example$authentication/registration-emulate-tpm.yaml[]
----

Die Konfiguration der TPM-Emulation wird im xref:operator-operational-tasks/tpm.adoc#_add_tpm_emulation_to_bare_metal_machine[Abschnitt über die Konfiguration der TPM-Emulation] beschrieben.

=== Identifizierung der MAC-Adresse

Bei Verwendung der MAC-Adressen-Identifikation meldet sich der Host bei {elemental_operator_name} an und verwendet dabei die MAC-Adresse seiner Netzwerkkarte (NIC) als Identifikator.
Wenn der Rechner mehr als eine Netzwerkschnittstelle hat, werden die MAC-Adressen lexikografisch sortiert und die erste ausgewählt.

Um die TPM-Authentifizierung durch eine MAC-Adressen-Identifizierung zu ersetzen, reicht es aus, den Wert `+mac+` in das Feld `+auth+` im xref:references/machineregistration-reference.adoc#_config_elemental_registration[Abschnitt config:elemental:registration in der MachineRegistration-Referenz] zu setzen.

.Beispiel MachineRegistration unter Verwendung der MAC-Adresse als Maschinenkennzeichnung
[,yaml]
----
include::example$authentication/registration-mac.yaml[]
----

[CAUTION]
====
Die MAC-Adresse wird von {elemental_operator_name} als eindeutig betrachtet.
Dies gilt für physische Geräte, während es bei der Verwendung von VirtualMachines von verschiedenen Hypervisors und verschiedenen Netzwerksegmenten dem Administrator obliegt, sicherzustellen, dass die registrierenden VMs eine eindeutige MAC-Adresse haben.
====


=== SMBIOS UUID-Kennung

Die Spezifikation für das System Management BIOS (SMBIOS) definiert Datenstrukturen, die zum Lesen von Verwaltungsinformationen verwendet werden können, die vom BIOS eines Hosts erzeugt werden.

Wenn der Wert `+sys-uuid+` als Feld `+auth+` des xref:references/machineregistration-reference.adoc#_config_elemental_registration[Abschnitts config:elemental:registration in der MachineRegistration] verwendet wird, registriert sich der Host auf {elemental_operator_name} mit dem Wert `+UUID+` aus der Tabelle `+System Information+` der SMBIOS-Daten des Hosts.

.Beispiel MachineRegistration unter Verwendung der UUID aus der SMBIOS-Systeminformationstabelle als Maschinenkennung
[,yaml]
----
include::example$authentication/registration-sys-uuid.yaml[]
----

[CAUTION]
====
Der SMBIOS-Wert `+System information/UUID+` sollte vom Hardwarehersteller als eindeutige UUID für den Host eingegeben werden.

Die SMBIOS-Daten sind nicht immer zuverlässig. Dies hängt vom jeweiligen Hersteller ab. Es kann vorkommen, dass die UUID fehlt oder dass dieselbe UUID auf mehrere Geräte innerhalb desselben Stapels angewendet wird.

Der Administrator muss sicherstellen, dass die Rechner eindeutige `+System information/UUID+` SMBIOS-Werte haben (das Tool `+dmidecode+` kann dabei helfen), da die Rechner sonst immer wieder dieselbe `+MachineInventory+` Ressource überschreiben und die Bereitstellung von {elemental-product-name} fehlschlägt.
====
