= Seite Analytik
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

Die Analytics-Seite bietet eine leistungsstarke und flexible Schnittstelle zur Abfrage und Analyse Ihrer Beobachtbarkeitsdaten mit xref:/develop/reference/k8sTs-stql_reference.adoc[STQL-Abfragen].
Diese interaktive Umgebung ermöglicht es Ihnen, über vorgefertigte Dashboards hinauszugehen und tiefere Einblicke in den Zustand, die Leistung und die Abhängigkeiten Ihrer dynamischen Umgebung zu gewinnen.

[CAUTION]
====
*Die Analyseseite ist veraltet, aber Sie können sie immer noch aktivieren, indem Sie bestimmte Berechtigungen konfigurieren. Wir empfehlen jedoch dringend die Nutzung von StackPacks für eine bessere Beobachtbarkeit und Analyse, da sie eine robustere und aktiv unterstützte Alternative darstellen.*

Zur Aktivierung der Analytics-Seite sind zwei Berechtigungen erforderlich:

* `+access-analytics+`
* `+execute-scripts+`

Weitere Einzelheiten: xref:/setup/security/rbac/rbac_permissions.adoc[Verwaltung von Berechtigungen]

====

