= Conditions des nÅuds
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Les conditions des nÅuds dÃĐcrivent l'ÃĐtat de tous les nÅuds de travail et sont utilisÃĐes pour vÃĐrifier les paramÃĻtres d'environnement des nÅuds de travail afin d'identifier les problÃĻmes potentiels avant tout impact sur le systÃĻme.

Conditions des nÅuds :

* `+Ready+`Â : Indique que le nÅud est prÃŠt pour les opÃĐrations Longhorn, y compris qu'un `+longhorn-manager+` pod est en cours d'exÃĐcution sur ce nÅud, que le nÅud Kubernetes est prÃŠt et qu'il n'y a pas de pression sur les ressources physiques.
+
* `+Schedulable+`Â : Indique que le nÅud n'est pas cordonnÃĐ et que la charge de travail peut ÃŠtre planifiÃĐe sur ce nÅud.
+
* `+MountPropagation+`Â : Indique que le nÅud prend en charge la propagation des montages. Ceci est nÃĐcessaire pour le partage des volumes montÃĐs par un conteneur avec d'autres conteneurs dans le mÃŠme pod Longhorn, ou avec d'autres pods Longhorn sur le mÃŠme nÅud.
+ 
* `+Multipathd+`Â : VÃĐrifie si le service `+multipathd+` n'est pas en cours d'exÃĐcution sur le nÅud, ce qui peut affecter le pod avec le dÃĐmarrage du volume. Voir link:https://longhorn.io/kb/troubleshooting-volume-with-multipath/[DÃĐpannage : `+MountVolume.SetUp failed for volume+` en raison de multipathd sur le nÅud].
* `+RequiredPackages+`Â : VÃĐrifie si tous les paquets requis (xref:installation-setup/requirements.adoc#_installing_nfsv4_client[client NFS], xref:installation-setup/requirements.adoc#_installing_open-_scsi[outil iSCSI], xref:installation-setup/requirements.adoc#_installing_cryptsetup_and_luks[cryptsetup], xref:installation-setup/requirements.adoc#_installing_device_mapper_userspace_tool[dmsetup]) existent pour Longhorn
+
* `+NFSClientInstalled+`Â : VÃĐrifie si l'un des clients NFS suivants est pris en charge : `+v4.2+`, `+v4.1+` ou `+v4.0+`. Le client NFS est requis pour le volume RWX et la sauvegarde.
+
* `+KernelModulesLoaded+`Â : VÃĐrifie si les modules de kernel suivants sont chargÃĐs :
+
** `+dm_crypt+`Â : Requis pour le chiffrement des volumes et des images de sauvegarde.
** `+vfio_pci+`Â : Requis pour la gestion des dispositifs SPDK et PCI (V2 Data Engine).
** `+uio_pci_generic+`Â : Requis pour la prise en charge UIO de SPDK (V2 Data Engine).
** `+nvme_tcp+`Â : Requis pour l'utilisation des dispositifs NVMe-over-TCP (V2 Data Engine).
+
* `+HugePagesAvailable+`Â : Indique si le nÅud est correctement configurÃĐ avec des HugePages (2Mi) comme requis par le Longhorn V2 Data Engine. Cela inclut la vÃĐrification des ÃĐlÃĐments suivants :
+
** Les HugePages (2Mi) sont enregistrÃĐes en tant que ressource Kubernetes (`+hugepages-2Mi+`).
** La capacitÃĐ de HugePages configurÃĐe rÃĐpond ou dÃĐpasse la valeur dÃĐfinie dans le paramÃĻtre `+v2-data-engine-hugepage-limit+`.

Les conditions des nÅuds ne bloquent pas le dÃĐploiement de Longhorn, mais elles entraÃŪnent des avertissements dans la ressource Longhorn `+Node+`. Pour plus d'informations, voir xref:installation-setup/requirements.adoc#_requirements[Exigences d'installation de Longhorn].
