= Mﾃｩtodos de instalaﾃｧﾃ｣o
:page-languages: [en, zh]
:revdate: 2025-08-06
:page-revdate: {revdate}

[IMPORTANT] 
====
Se o seu nﾃｳ tiver o NetworkManager instalado e habilitado, xref:known_issues.adoc#_networkmanager[certifique-se de que ele estﾃ｡ configurado para ignorar interfaces gerenciadas pelo CNI].
====

[IMPORTANT]
====
Vocﾃｪ pode usar qualquer versﾃ｣o do RKE2 Prime listada na URL de Artefatos Prime para os ativos mencionados nestes passos. Para saber mais sobre a URL de Artefatos Prime, consulte nossa https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[documentaﾃｧﾃ｣o exclusiva do Prime]. A autenticaﾃｧﾃ｣o ﾃｩ necessﾃ｡ria. Use suas credenciais do https://scc.suse.com/home[Centro de Clientes SUSE (SCC)] para fazer login.
====

O RKE2 pode ser instalado em um sistema de vﾃ｡rias maneiras, duas das quais sﾃ｣o os mﾃｩtodos preferidos e suportados. Esses mﾃｩtodos sﾃ｣o tarball e RPM. O script de instalaﾃｧﾃ｣o mencionado no Inﾃｭcio Rﾃ｡pido ﾃｩ um agrupador em torno desses dois mﾃｩtodos.

Este documento explica esses mﾃｩtodos de instalaﾃｧﾃ｣o em maior detalhe.

== Tarball

Para instalar o RKE2 via instalaﾃｧﾃ｣o, vocﾃｪ primeiro precisa obter o script de instalaﾃｧﾃ｣o. Isso pode ser feito de vﾃ｡rias maneiras.

Isso obtﾃｩm o script e inicia imediatamente o processo de instalaﾃｧﾃ｣o.

[,sh]
----
# curl -sfL https://get.rke2.io | sudo sh -
curl -sfL https://get.rke2.io | sh -
----

Alternativamente, vocﾃｪ pode baixar o script de instalaﾃｧﾃ｣o e tornﾃ｡-lo executﾃ｡vel.

[,sh]
----
curl -sfL https://get.rke2.io --output install.sh
chmod +x install.sh
----

=== Instalaﾃｧﾃ｣o

Execute o instalador, onde `+INSTALL_RKE2_ARTIFACT_URL+` ﾃｩ a URL de Artefatos Prime e `+INSTALL_RKE2_CHANNEL+` ﾃｩ um canal de lanﾃｧamento ao qual vocﾃｪ pode se inscrever e que por padrﾃ｣o ﾃｩ estﾃ｡vel. Neste exemplo, `+INSTALL_RKE2_CHANNEL="latest"+` fornece a versﾃ｣o mais recente do RKE2.

[,bash]
----
sudo INSTALL_RKE2_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/rke2 INSTALL_RKE2_CHANNEL="latest" ./install.sh
----

Se vocﾃｪ quiser especificar uma versﾃ｣o, defina a variﾃ｡vel de ambiente `+INSTALL_RKE2_VERSION+`.

[,bash]
----
sudo INSTALL_RKE2_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/rke2 INSTALL_RKE2_VERSION="<VERSION>" ./install.sh
----

Isso instalarﾃ｡ o serviﾃｧo `+rke2-server+` e o binﾃ｡rio `+rke2+` na sua mﾃ｡quina. Devido ﾃ sua natureza, ele falharﾃ｡ a menos que seja executado como usuﾃ｡rio root ou atravﾃｩs de `+sudo+`.

Quando o script de instalaﾃｧﾃ｣o ﾃｩ executado, ele determina que tipo de sistema ﾃｩ. Se for um sistema operacional que usa RPMs (como CentOS ou RHEL), ele realizarﾃ｡ uma instalaﾃｧﾃ｣o baseada em RPM, caso contrﾃ｡rio, o script padrﾃ｣o ﾃｩ tarball. A instalaﾃｧﾃ｣o baseada em RPM ﾃｩ abordada abaixo.

Em seguida, o script de instalaﾃｧﾃ｣o baixa o tarball, verifica-o comparando os hashes SHA256 e, por ﾃｺltimo, extrai o conteﾃｺdo para `+/usr/local+`. Um operador pode mover os arquivos apﾃｳs a instalaﾃｧﾃ｣o, se desejar. Esta operaﾃｧﾃ｣o simplesmente extrai o tarball e nenhuma outra modificaﾃｧﾃ｣o no sistema ﾃｩ feita.

Estrutura / conteﾃｺdo do tarball:

* bin - contﾃｩm o executﾃ｡vel RKE2, bem como os scripts `+rke2-killall.sh+` e `+rke2-uninstall.sh+`.
* lib - contﾃｩm os arquivos de unidade systemd para o servidor e o agente.
* share - contﾃｩm a licenﾃｧa do RKE2, bem como um arquivo de configuraﾃｧﾃ｣o sysctl usado quando o RKE2 ﾃｩ executado em modo CIS.

Para configurar o sistema ainda mais, vocﾃｪ vai querer consultar a documentaﾃｧﾃ｣o do xref:reference/server_config.adoc[servidor] ou xref:reference/linux_agent_config.adoc[agente].

== RPM

Para iniciar o processo de instalaﾃｧﾃ｣o do RPM, vocﾃｪ precisa obter o script de instalaﾃｧﾃ｣o que foi abordado acima. O script verificarﾃ｡ seu sistema em busca de `+rpm+`, `+yum+` ou `+dnf+` e, se algum deles existir, determina que o sistema ﾃｩ baseado em Redhat e inicia o processo de instalaﾃｧﾃ｣o do RPM.

Os arquivos sﾃ｣o instalados com o prefixo `+/usr+` em vez de `+/usr/local+`.

=== Repositﾃｳrios

RPMs assinados sﾃ｣o publicados para o RKE2 dentro dos repositﾃｳrios RPM `+rpm-testing.rancher.io+` e `+rpm.rancher.io+`. Se vocﾃｪ executar o script https://get.rke2.io em nﾃｳs que suportam RPMs, ele usarﾃ｡ esses repositﾃｳrios RPM por padrﾃ｣o. Mas vocﾃｪ tambﾃｩm pode instalﾃ｡-los vocﾃｪ mesmo.

Os RPMs fornecem as unidades `+systemd+` para gerenciar `+rke2+`, mas precisarﾃ｣o ser configuradas via arquivo de configuraﾃｧﾃ｣o antes de iniciar os serviﾃｧos pela primeira vez.

=== Enterprise Linux 7/8/9

Para usar o repositﾃｳrio RPM, em um sistema CentOS ou RHEL, execute o seguinte trecho de bash:

[,bash]
----
export RKE2_MINOR=28
export LINUX_MAJOR=7 # or 8 or 9 etc
cat << EOF > /etc/yum.repos.d/rancher-rke2-1-${RKE2_MINOR}-latest.repo
[rancher-rke2-common-latest]
name=Rancher RKE2 Common Latest
baseurl=https://rpm.rancher.io/rke2/latest/common/centos/${LINUX_MAJOR}/noarch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key

[rancher-rke2-1-${RKE2_MINOR}-latest]
name=Rancher RKE2 1.${RKE2_MINOR} Latest
baseurl=https://rpm.rancher.io/rke2/latest/1.${RKE2_MINOR}/centos/${LINUX_MAJOR}/x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

=== Instalaﾃｧﾃ｣o

Apﾃｳs o repositﾃｳrio ser configurado, vocﾃｪ pode executar um dos seguintes comandos:

[,sh]
----
yum -y install rke2-server
----

ou

[,sh]
----
yum -y install rke2-agent
----

O RPM instalarﾃ｡ uma unidade systemd `+rke2-server.service+` ou `+rke2-agent.service+` correspondente que pode ser invocada como: `+systemctl start rke2-server+`. Certifique-se de configurar `+rke2+` antes de iniciﾃ｡-lo, seguindo as instruﾃｧﾃｵes `+Configuration File+` abaixo.

== Regressﾃ｣o

O binﾃ｡rio RKE2 ﾃｩ compilado e vinculado estaticamente, o que permite que o binﾃ｡rio RKE2 seja portﾃ｡til entre distribuiﾃｧﾃｵes Linux sem a preocupaﾃｧﾃ｣o com problemas de dependﾃｪncia. A instalaﾃｧﾃ｣o mais simples ﾃｩ baixar o binﾃ｡rio, garantir que ele seja executﾃ｡vel e copiﾃ｡-lo para o `+${PATH}+`, geralmente `+/usr/local/bin+`. Apﾃｳs a primeira execuﾃｧﾃ｣o, o RKE2 criarﾃ｡ todos os diretﾃｳrios e arquivos necessﾃ｡rios. Para configurar o sistema ainda mais, vocﾃｪ vai querer consultar a documentaﾃｧﾃ｣o do xref:install/configuration.adoc[arquivo de configuraﾃｧﾃ｣o].
