= k3s-geheimnisse-verschlüsseln
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

K3s unterstützt die Aktivierung der Verschlüsselung von Geheimnissen im Ruhezustand. Weitere Informationen finden Sie unter xref:security/secrets-encryption.adoc[Geheimnisse Verschlüsselung].

== Secrets Verschlüsselungstool

[IMPORTANT]
.Version Tor
====
Verfügbar ab https://github.com/k3s-io/k3s/releases/tag/v1.21.8%2Bk3s1[.21.8+k3s1] v1
====


K3s enthält ein CLI-Tool `secrets-encrypt`, das die automatische Steuerung der folgenden Funktionen ermöglicht:

* Deaktivieren/Aktivieren der Verschlüsselung von Geheimnissen
* Hinzufügen neuer Verschlüsselungscodes
* Rotieren und Löschen von Verschlüsselungsschlüsseln
* Geheimnisse wieder verschlüsseln

[CAUTION]
====
Die Nichtbeachtung des korrekten Verfahrens zur Rotation der Verschlüsselungsschlüssel kann dazu führen, dass Ihr Cluster dauerhaft beschädigt wird. Gehen Sie mit Vorsicht vor.
====

[#_encryption_key_rotation]
=== Rotation der Verschlüsselungsschlüssel

[IMPORTANT]
.Version Tor
====
Erhältlich ab den Versionen vom September 2024: v1.30.5+k3s1, v1.31.1+k3s1.
====

[tabs,sync-group-id=se]
======
Einzelner Server::
+
--
So rotieren Sie die Verschlüsselungsschlüssel für Geheimnisse auf einem Einzelserver-Cluster:

. Starten Sie den K3s-Server mit dem Flag `--secrets-encryption`
+
[NOTE]
====
Das Starten von K3s ohne Verschlüsselung und das spätere Aktivieren der Verschlüsselung wird derzeit _nicht_ unterstützt.
====

. Geheimnisse rotieren Verschlüsselungsschlüssel
+
----
k3s secrets-encrypt rotate-keys
----

. Warten Sie, bis die Neuverschlüsselung abgeschlossen ist. Beobachten Sie die Serverprotokolle, oder warten Sie ab:
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
--

Hochverfügbarkeit::
+
--
Zum Rotieren von Geheimnissen Verschlüsselungsschlüssel auf HA-Setups:

. Starten Sie alle drei K3s-Server mit dem Kennzeichen `--secrets-encryption`. Der Einfachheit halber werden die Server als S1, S2, S3 bezeichnet.
+
[NOTE]
====
Das Starten von K3s ohne Verschlüsselung und das spätere Aktivieren der Verschlüsselung wird derzeit _nicht_ unterstützt.
====

. Drehen der Geheimnisse Verschlüsselungsschlüssel auf S1
+
[,bash]
----
k3s secrets-encrypt rotate-keys
----

. Warten Sie, bis die Neuverschlüsselung abgeschlossen ist. Beobachten Sie die Serverprotokolle, oder warten Sie ab:
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
+
[NOTE]
====
Die K3s verschlüsseln ~5 Geheimnisse pro Sekunde neu. Bei Clustern mit einer großen Anzahl von Geheimnissen kann die Wiederverschlüsselung mehrere Minuten dauern. Sie können den Fortschritt in den Serverprotokollen verfolgen.
====

. Starten Sie K3s auf S1 mit denselben Argumenten neu. Wenn K3s als Dienst ausgeführt wird:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Sobald S1 in Betrieb ist, starten Sie die K3s auf S2 und S3 neu.
--
======

=== Legacy-Verschlüsselung Schlüsselrotation

[TIP]
.Neues Verfahren
====
Wenn Sie die K3s-Versionen v1.30+ verwenden, empfehlen wir Ihnen, stattdessen die xref:#_encryption_key_rotation[Encryption Key Rotation] zu verwenden.
====

[tabs,sync-group-id=se]
======
Einzelner Server::
+
--
So rotieren Sie die Verschlüsselungsschlüssel für Geheimnisse auf einem Einzelserver-Cluster:

. Starten Sie den K3s-Server mit dem Flag `--secrets-encryption`
+
[NOTE]
====
Das Starten von K3s ohne Verschlüsselung und das spätere Aktivieren der Verschlüsselung wird derzeit _nicht_ unterstützt.
====

. Vorbereiten
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Beenden Sie den K3s-Server und starten Sie ihn mit denselben Argumenten neu. Wenn K3s als Dienst ausgeführt wird:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Drehen Sie
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Beenden und starten Sie den K3s-Server mit denselben Argumenten neu
. Neu verschlüsseln
+
[NOTE]
====
Die K3s verschlüsseln ~5 Geheimnisse pro Sekunde neu. +
Bei Clustern mit einer großen Anzahl von Geheimnissen kann die Wiederverschlüsselung mehrere Minuten dauern.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----
--

Hochverfügbarkeit::
+
--
Die Schritte sind für eingebettete DB- und externe DB-Cluster identisch.

Zum Rotieren von Geheimnissen Verschlüsselungsschlüssel auf HA-Setups:

. Starten Sie alle drei K3s-Server mit dem Kennzeichen `--secrets-encryption`. Der Einfachheit halber werden die Server als S1, S2, S3 bezeichnet.
+
[NOTE]
====
* Das Starten von K3s ohne Verschlüsselung und das spätere Aktivieren der Verschlüsselung wird derzeit _nicht_ unterstützt.
* Es ist zwar nicht erforderlich, aber empfehlenswert, einen Serverknoten auszuwählen, von dem aus Sie die `secrets-encrypt` Befehle ausführen.
====
. Vorbereiten auf S1
+
[,bash]
----
k3s secrets-encrypt prepare
----

. S1 mit denselben Argumenten beenden und neu starten. Wenn K3s als Dienst ausgeführt wird:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Sobald S1 hochgefahren ist, beenden Sie S2 und S3 und starten Sie sie neu.
. Drehen an S1
+
[,bash]
----
k3s secrets-encrypt rotate
----

. S1 mit denselben Argumenten beenden und neu starten
. Sobald S1 hochgefahren ist, beenden Sie S2 und S3 und starten Sie sie neu.
. Erneute Verschlüsselung auf S1
+
[NOTE]
====
Die K3s verschlüsseln ~5 Geheimnisse pro Sekunde neu. +
Bei Clustern mit einer großen Anzahl von Geheimnissen kann die Wiederverschlüsselung mehrere Minuten dauern.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----

. S1 mit denselben Argumenten beenden und neu starten
. Sobald S1 hochgefahren ist, beenden Sie S2 und S3 und starten Sie sie neu.
--
======

=== Geheimnisse Verschlüsselung Deaktivieren/Aktivieren

[tabs,sync-group-id=se]
======
Einzelner Server::
+
--
Nach dem Start eines Servers mit dem Flag `--secrets-encryption` kann die Verschlüsselung der Geheimnisse deaktiviert werden.

So deaktivieren Sie die Verschlüsselung von Geheimnissen in einem Single-Node-Cluster:

. Deaktivieren Sie
+
[,bash]
----
k3s secrets-encrypt disable
----

. Beenden Sie den K3s-Server und starten Sie ihn mit denselben Argumenten neu. Wenn K3s als Dienst ausgeführt wird:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Wiederverschlüsseln mit Flaggen
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

Um die Verschlüsselung von Geheimnissen auf einem Einzelknoten-Cluster wieder zu aktivieren:

. Aktivieren Sie
+
[,bash]
----
k3s secrets-encrypt enable
----

. Beenden und starten Sie den K3s-Server mit denselben Argumenten neu
. Wiederverschlüsseln mit Flaggen
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--

Hochverfügbarkeit::
+
--
Nach dem Start eines HA-Clusters mit `--secrets-encryption` -Flags kann die Verschlüsselung von Geheimnissen deaktiviert werden.

[NOTE]
====
Es ist zwar nicht erforderlich, aber empfehlenswert, einen Serverknoten auszuwählen, von dem aus Sie die `secrets-encrypt` Befehle ausführen.
====

Der Einfachheit halber werden die drei in diesem Leitfaden verwendeten Server als S1, S2 und S3 bezeichnet.

So deaktivieren Sie die Verschlüsselung von Geheimnissen in einem HA-Cluster:

. Deaktivieren auf S1
+
[,bash]
----
k3s secrets-encrypt disable
----

. S1 mit denselben Argumenten beenden und neu starten. Wenn K3s als Dienst ausgeführt wird:
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Sobald S1 hochgefahren ist, beenden Sie S2 und S3 und starten Sie sie neu.
. Erneute Verschlüsselung mit Flaggen auf S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

Um die Verschlüsselung von Geheimnissen auf einem HA-Cluster wieder zu aktivieren:

. Aktivieren auf S1
+
[,bash]
----
k3s secrets-encrypt enable
----

. S1 mit denselben Argumenten beenden und neu starten
. Sobald S1 hochgefahren ist, beenden Sie S2 und S3 und starten Sie sie neu.
. Erneute Verschlüsselung mit Flaggen auf S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--
======

=== Geheimnisse Verschlüsselungsstatus

Das Werkzeug secrets-encrypt enthält einen Befehl `status`, der Informationen über den aktuellen Status der Verschlüsselung von Geheimnissen auf dem Knoten anzeigt.

Ein Beispiel für den Befehl auf einem Knoten mit einem Server:

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
----

Ein weiteres Beispiel für einen HA-Cluster, nachdem die Schlüssel rotiert wurden, aber bevor die Server neu gestartet wurden:

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: rotate
Server Encryption Hashes: hash does not match between node-1 and node-2

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2021-12-10T22:54:38Z
        AES-CBC   aescbckey
----

Einzelheiten zu den einzelnen Abschnitten finden Sie im Folgenden:

* *Status der Verschlüsselung*: Zeigt an, ob die Verschlüsselung von Geheimnissen auf dem Knoten deaktiviert oder aktiviert ist
* *Aktuelle Rotationsphase*: Zeigt die aktuelle Rotationsstufe des Knotens an. +
Die Etappen sind: `start`, `prepare`, `rotate`, `reencrypt_request`, `reencrypt_active`, `reencrypt_finished`
* *Server-Verschlüsselungshashes*: Nützlich für HA-Cluster, da dies anzeigt, ob alle Server mit ihren lokalen Dateien auf der gleichen Stufe sind. Auf diese Weise lässt sich feststellen, ob ein Neustart der Server erforderlich ist, bevor man zur nächsten Stufe übergehen kann. Im obigen HA-Beispiel haben Knoten-1 und Knoten-2 unterschiedliche Hashes, was bedeutet, dass sie derzeit nicht die gleiche Verschlüsselungskonfiguration haben. Durch einen Neustart der Server wird deren Konfiguration synchronisiert.
* *Schlüssel-Tabelle*: Fasst die Informationen über die auf dem Knoten gefundenen geheimen Verschlüsselungsschlüssel zusammen.
 ** *Aktiv*: Der "*" zeigt an, ob und welche der Schlüssel derzeit für die Verschlüsselung von Geheimnissen verwendet werden. Ein aktiver Schlüssel wird von Kubernetes verwendet, um neue Geheimnisse zu verschlüsseln.
 ** *Schlüssel-Typ*: Alle Schlüssel, die dieses Tool verwenden, sind vom Typ `AES-CBC`. Weitere Informationen finden Sie unter https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers[.]
 ** *Name*: Name des Verschlüsselungsschlüssels.
