= k3s-Marke
:page-languages: [en, ja, ko, zh]
:revdate: 2025-05-26
:page-revdate: {revdate}

K3s verwendet Token, um den Knotenverbindungsprozess zu sichern und um vertrauliche Informationen zu verschlüsseln, die im Datenspeicher gespeichert werden. Token authentifizieren den Cluster gegenüber dem beitretenden Knoten und den Knoten gegenüber dem Cluster.

== Token-Format

K3s-Tokens können entweder im sicheren oder im kurzen Format angegeben werden. Das sichere Format wird bevorzugt, da es dem Client ermöglicht, die Identität des Clusters, dem er beitritt, zu authentifizieren, bevor er Anmeldedaten sendet.

=== Sicher

Das Format des sicheren Tokens (gelegentlich auch als "vollständiger" Token bezeichnet) enthält die folgenden Teile:

`<prefix><cluster CA hash>::<credentials>`

* `prefix`: ein festes `K10` Präfix, das das Token-Format identifiziert
* `cluster CA hash`: Der Hash des Server-CA-Zertifikats des Clusters, das zur Authentifizierung des Servers gegenüber dem beitretenden Knoten verwendet wird.
 ** Bei selbstsignierten CA-Zertifikaten ist dies die SHA256-Summe des PEM-formatierten Zertifikats, wie es auf der Festplatte gespeichert ist.
 ** Bei benutzerdefinierten CA-Zertifikaten ist dies die SHA256-Summe der DER-Kodierung des Stammzertifikats; allgemein bekannt als der Zertifikatsfingerabdruck.
* `credentials`: Der Benutzername und das Kennwort bzw. das Träger-Token, die zur Authentifizierung des beitretenden Knotens beim Cluster verwendet werden.

==== TLS-Bootstrapping

Wenn ein sicheres Token angegeben wird, führt der beitretende Knoten die folgenden Schritte durch, um die Identität des Servers, mit dem er verbunden ist, zu überprüfen, bevor er die Anmeldeinformationen übermittelt:

. Wenn die TLS-Verifizierung deaktiviert ist, laden Sie das CA-Bundle von `/cacerts` auf den Server herunter, dem es beitreten soll.
. Berechnen Sie den SHA256-Hash des CA-Zertifikats, wie oben beschrieben.
. Vergleichen Sie den berechneten SHA256-Hash mit dem Hash aus dem Token.
. Wenn der Hash übereinstimmt, überprüfen Sie, ob das vom Server vorgelegte Zertifikat durch das CA-Bündel des Servers validiert werden kann.
. Wenn das Serverzertifikat gültig ist, legen Sie die Anmeldeinformationen vor, um dem Cluster beizutreten, indem Sie je nach Token-Typ entweder die einfache oder die Bearer-Token-Authentifizierung verwenden.

=== Kurz

Das kurze Token-Format enthält nur das Kennwort oder das Träger-Token, das zur Authentifizierung des beitretenden Knotens im Cluster verwendet wird.

Wenn ein kurzes Token verwendet wird, vertraut der beitretende Knoten implizit dem vom Server vorgelegten CA-Bündel; die Schritte 2 bis 4 des TLS-Bootstrapping-Prozesses werden übersprungen. Die erste Verbindung kann anfällig sein für https://en.wikipedia.org/wiki/Man-in-the-middle_attack[Man-in-the-Middle-Angriffe].

== Token-Typen

K3s unterstützt drei Arten von Token. Standardmäßig ist nur der Server-Token verfügbar; weitere Token-Typen müssen vom Administrator konfiguriert oder erstellt werden.

|===
| Typ | CLI-Option | Umgebungsvariable

| Server
| `--token`
| `K3S_TOKEN`

| Agent
| `--agent-token`
| `K3S_AGENT_TOKEN`

| Bootstrap
| `n/a`
| `n/a`
|===

[#_server]
=== Server

Wenn beim Starten des ersten Servers im Cluster kein Token angegeben wird, wird ein Token mit einem zufälligen Passwort erstellt. Der Server-Token wird immer in einem sicheren Format auf `/var/lib/rancher/k3s/server/token` geschrieben.

Das Server-Token kann verwendet werden, um sowohl Server- als auch Agentenknoten dem Cluster beizutreten. Jeder, der Zugriff auf das Server-Token hat, hat im Wesentlichen vollen Administrator-Zugriff auf den Cluster. Dieses Zeichen sollte sorgfältig gehütet werden.

Das Server-Token wird auch als https://en.wikipedia.org/wiki/PBKDF2[PBKDF2-Passphrase] verwendet, um vertrauliche Informationen zu verschlüsseln, die im Datenspeicher als Bootstrap-Daten gespeichert werden. Bootstrap-Daten sind unerlässlich, um neue Serverknoten einzurichten oder von einem Snapshot wiederherzustellen. Aus diesem Grund muss das Token zusammen mit dem Cluster-Datenspeicher selbst gesichert werden.

[CAUTION]
====
Sofern keine benutzerdefinierten CA-Zertifikate verwendet werden, kann beim Starten des ersten Servers im Cluster nur das kurze (nur Passwort) Token-Format verwendet werden. Dies liegt daran, dass der Cluster-CA-Hash erst dann bekannt ist, wenn der Server die selbstsignierten Cluster-CA-Zertifikate generiert hat.
====


Weitere Informationen zur Verwendung benutzerdefinierter CA-Zertifikate finden Sie in der xref:cli/certificate.adoc[Dokumentation`k3s certificate` ]. +
Weitere Informationen zum Sichern Ihres Clusters finden Sie in der Dokumentation xref:datastore/backup-restore.adoc[Backup und Restore].

=== Agent

Standardmäßig ist das Agenten-Token dasselbe wie das Server-Token. Das Agenten-Token kann vor oder nach dem Start des Clusters festgelegt werden, indem die CLI-Option oder die Umgebungsvariable auf allen Servern des Clusters geändert wird. Das Agenten-Token ist dem Server-Token insofern ähnlich, als es statisch konfiguriert ist und nicht abläuft.

Das Agenten-Token wird in einem sicheren Format auf `/var/lib/rancher/k3s/server/agent-token` geschrieben. Wenn kein Agenten-Token angegeben ist, ist diese Datei ein Link zum Server-Token.

=== Bootstrap

[IMPORTANT]
.Version Tor
====
Unterstützung für den Befehl `k3s token` und die Möglichkeit, Knoten mit Bootstrap-Tokens zu verbinden, ist ab den Versionen 2023-02 (v1.26.2+k3s1, v1.25.7+k3s1, v1.24.11+k3s1, v1.23.17+k3s1) verfügbar.
====

K3s unterstützt dynamisch generierte, automatisch ablaufende https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/[Bootstrap-Tokens] für Agenten.

[#_k3s_token_1]
== k3s-Marke

Das k3s-Token-CLI-Tool verwaltet:

* Der Lebenszyklus von Bootstrap-Tokens unter Verwendung desselben Generierungs- und Validierungscodes wie `kubeadm token` bootstrap tokens. Beachten Sie, dass beide CLIs ähnlich sind.
* Die Rotation des Server-Tokens

----
NAME:
   k3s token - Manage tokens

USAGE:
   k3s token command [command options] [arguments...]

COMMANDS:
   create    Create bootstrap tokens on the server
   delete    Delete bootstrap tokens on the server
   generate  Generate and print a bootstrap token, but do not create it on the server
   list      List bootstrap tokens on the server
   rotate    Rotate original server token with a new token

OPTIONS:
   --help, -h  show help
----

[discrete]
=== `k3s token create [token]`

Erstellen Sie ein neues Token. `[token]` ist das zu schreibende Token, das von `k3s token generate` generiert wird. Wenn kein Token angegeben wird, wird ein zufälliger Token generiert.

Ein Token im sicheren Format, einschließlich des Cluster-CA-Hashs, wird in stdout geschrieben. Die Ausgabe dieses Befehls sollte gespeichert werden, da der geheime Teil des Tokens nicht mehr angezeigt werden kann.

|===
| Flagge | Beschreibung

| `--data-dir` Wert
| Ordner für den Status (Standard: /var/lib/rancher/k3s oder ${HOME}/.rancher/k3s, wenn Sie nicht root sind)

| `--kubeconfig` Wert
| Server, zu dem eine Verbindung hergestellt werden soll [$KUBECONFIG]

| `--description` Wert
| Eine menschenfreundliche Beschreibung, wie dieses Token verwendet wird

| `--groups` Wert
| Zusätzliche Gruppen, für die dieses Token bei der Authentifizierung verwendet wird. (Standard: Standard: "system:bootstrappers:k3s:default-node-token")

| `--ttl` Wert
| Die Dauer, bevor das Token automatisch gelöscht wird (z. B. 1s, 2m, 3h). Bei einem Wert von '0' läuft das Token nie ab (Standardwert: 24h0m0s)

| `--usages` Wert
| Beschreibt die Art und Weise, wie dieses Token verwendet werden kann. (Standardwert: "Signierung, Authentifizierung")
|===

[discrete]
=== `k3s token delete`

Ein oder mehrere Token löschen. Es kann das vollständige Token oder nur die Token-ID angegeben werden.

|===
| Flagge | Beschreibung

| `--data-dir` Wert
| Ordner für den Status (Standard: /var/lib/rancher/k3s oder ${HOME}/.rancher/k3s, wenn Sie nicht root sind)

| `--kubeconfig` Wert
| Server, zu dem eine Verbindung hergestellt werden soll [$KUBECONFIG]
|===

[discrete]
=== `k3s token generate`

Erzeugen Sie ein zufällig generiertes Bootstrap-Token.

Sie müssen diesen Befehl nicht verwenden, um ein Token zu erzeugen. Sie können dies selbst tun, solange es das Format `[a-z0-9]\{6}.[a-z0-9]\{16}` hat, wobei der erste Teil die Token-ID und der zweite Teil das Geheimnis ist.

|===
| Flagge | Beschreibung

| `--data-dir` Wert
| Ordner für den Status (Standard: /var/lib/rancher/k3s oder ${HOME}/.rancher/k3s, wenn Sie nicht root sind)

| `--kubeconfig` Wert
| Server, zu dem eine Verbindung hergestellt werden soll [$KUBECONFIG]
|===

[discrete]
=== `k3s token list`

Auflistung der Bootstrap-Token mit Angabe ihrer ID, Beschreibung und verbleibenden Lebenszeit.

|===
| Flagge | Beschreibung

| `--data-dir` Wert
| Ordner für den Status (Standard: /var/lib/rancher/k3s oder ${HOME}/.rancher/k3s, wenn Sie nicht root sind)

| `--kubeconfig` Wert
| Server, zu dem eine Verbindung hergestellt werden soll [$KUBECONFIG]

| `--output` Wert
| Ausgabeformat. Gültige Optionen: text, json (Standard: "text")
|===

[discrete]
=== `k3s token rotate`

[IMPORTANT]
.Version Tor
====
Verfügbar ab den Versionen vom Oktober 2023 (v1.28.2+k3s1, v1.27.7+k3s1, v1.26.10+k3s1, v1.25.15+k3s1).
====


Ersetzen Sie den ursprünglichen Server-Token durch einen neuen Server-Token. Nach Ausführung dieses Befehls müssen alle Server und Agenten, die ursprünglich mit dem alten Token verbunden waren, mit dem neuen Token neu gestartet werden.

Wenn Sie kein neues Token angeben, wird eines für Sie generiert.

|===
| Flagge | Beschreibung

| `--data-dir` Wert
| Ordner für den Status (Standard: /var/lib/rancher/k3s oder ${HOME}/.rancher/k3s, wenn Sie nicht root sind)

| `--kubeconfig` Wert
| Server, zu dem eine Verbindung hergestellt werden soll [$KUBECONFIG]

| `--server` Wert
| Server, zu dem eine Verbindung hergestellt werden soll (Standard: "https://127.0.0.1:6443") [$K3S_URL]

| `--token` Wert
| Vorhandenes Token zum Beitritt eines Servers oder Agenten zu einem Cluster [$K3S_TOKEN]

| `--new-token` Wert
| Neuer Token, der den bestehenden Token ersetzt
|===

[WARNING]
====
Für Snapshots, die vor der Rotation erstellt wurden, wird bei der Wiederherstellung des Clusters das alte Server-Token benötigt.
====
