= Instalação
:revdate: 2025-09-08
:page-revdate: {revdate}

== Visão geral

{elemental-product-name} A pilha fornece gerenciamento de sistema operacional usando contêineres OCI e Kubernetes. A instalação da pilha {elemental-product-name}abrange a instalação do {elemental_operator_name} no cluster de gerenciamento e a criação e o uso da mídia de instalação para fornecer o sistema operacional aos nós do cluster. Consulte a seção xref:rancher-os-management/architecture/architecture.adoc[Arquitetura] para ler sobre a interação dos componentes.

A configuração de instalação é aplicada e definida principalmente como parte do processo de registro.
O processo de registro é feito pelo `+elemental-register+` (a parte do cliente {elemental_operator_name} ), que é responsável por registrar os nós em um cluster de gerenciamento do Rancher e buscar a configuração de instalação.

Consulte o guia de xref:quickstarts/quickstart-cli.adoc[início rápido] para obter instruções simples de implementação passo a passo.

== {elemental-product-name} Instalação do operador

O {elemental_operator_name} é responsável por gerenciar as versões do {elemental-product-name} e manter um inventário de máquinas para auxiliar nas instalações de borda ou bare metal. O {elemental_operator_name}requer um cluster que inclua o Rancher Manager e pode ser instalado com um helm chart.

Consulte {elemental_operator_name} xref:references/operatorchart-reference.adoc[helm chart reference] para obter detalhes sobre instalação, desinstalação, upgrade e configuração.

== Preparar recursos do Kubernetes

Quando o {elemental_operator_name} estiver em funcionamento no cluster de gerenciamento, serão necessários alguns recursos do Kubernetes para preparar uma implementação de cluster baseada no {elemental-product-name}.

* xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate]:
Esse recurso identifica os critérios de correspondência entre as caixas registradas (listadas como parte do MachineInventory) e os clusters disponíveis do Rancher 2.6. Assim que houver uma correspondência, o cluster de kubernetes selecionado assume a propriedade da caixa registrada.
* xref:references/machineregistration-reference.adoc[Registro de máquina]:
Esse recurso define os detalhes da implantação do sistema operacional para qualquer máquina que tente se registrar. O registro da máquina é a entrada para os nós do {elemental-product-name}, pois ele lida com a autenticação (com base no TPM), a implantação do sistema operacional e a inclusão do nó no MachineInventory para que ele possa ser adicionado a um cluster quando houver uma correspondência com base em um MachineInventorySelectorTemplate. O objeto MachineRegistration inclui o URL de registro da máquina que os nós usam para se registrar nele.

Um recurso do Rancher Cluster também é necessário para implantar o site {elemental-product-name}. Ele pode ser criado manualmente, conforme exemplificado no guia xref:quickstarts/quickstart-cli.adoc[Quick Start], ou a partir da interface do usuário do Rancher 2.6.

== Preparar a mídia de instalação

A mídia de instalação é a mídia que será usada para iniciar a implantação de um sistema operacional. Atualmente, a mídia suportada é uma ISO ativa. O ISO ativo deve incluir o yaml de configuração de registro, portanto, ele deve ser criado assim que o MachineRegistration for criado. A mídia de instalação é gerada pela criação de recursos xref:references/seedimage-reference.adoc[Seed Image](consulte xref:quickstarts/quickstart-cli.adoc#_preparing_the_installation_seed_image[início rápido] e xref:operator-operational-tasks/custom-images.adoc#_create_a_custom_bootable_installation_iso[imagens personalizadas]).

O ISO ao vivo oferece suporte à inicialização PXE para integração direta com o https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/autoinst-distributions.html#based-on-iso-image[SUSE Manager].

No MachineRegistration, somente um subconjunto de parâmetros de instalação do sistema operacional pode ser configurado; todos os parâmetros disponíveis estão listados na página de referência xref:references/machineregistration-reference.adoc[do MachineRegistration].

Para configurar a instalação além das opções comuns fornecidas na seçãoxref:references/machineregistration-reference.adoc#_config_elemental_install[`+elemental.install+`] um arquivo de configuração `+config.yaml+`pode ser incluído na ISO (consulte xref:installation/customize-installation/custom-install.adoc#_custom_suse_rancher_prime_os_manager_client_configuration_file[Imagens personalizadas]).
Observe que qualquer configuração aplicada como parte da seção `+elemental.install+` do MachineRegistration será aplicada sobre as configurações incluídas em qualquer arquivo `+config.yaml+` personalizado.

Provavelmente, a configuração de inicialização na nuvem é suficiente para configurar e definir o nó implantado na inicialização; no entanto, se por algum motivo forem necessárias ações ou scripts de primeira inicialização, também é possível incluir planos do Rancher System Agent na mídia de instalação. Consulte a seção xref:rancher-os-management/plans.adoc[Planos] para obter detalhes e alguns exemplos de planos. Os planos poderiam ser incluídos nos rootfs esmagados na pasta `+/var/lib/elemental/agent/plans+`e seriam vistos pelo agente do sistema na primeira inicialização.

== Iniciar o processo de instalação

A instalação começa com a inicialização da mídia de instalação em um nó. Depois que a mídia de instalação for inicializada, ela tentará entrar em contato com o cluster de gerenciamento e se registrará nele chamando o comando `+elemental-register+`.
Como a configuração do yaml de registro já está incluída na ISO, o `+elemental-register+` conhece o URL de registro e quaisquer outros dados necessários para o registro.

Em um registro bem-sucedido, a mídia de instalação iniciará a instalação no host com base na configuração já incluída na mídia e nos parâmetros MachineRegistration. Assim que a instalação for concluída, o nó estará pronto para ser reinicializado. O sistema operacional implantado inclui um plano de agente do sistema para iniciar um processo regular de provisionamento do Rancher para instalar a versão selecionada do Kubernetes. Uma vez inicializado, após alguns minutos, a instalação do nó é finalizada e o nó é incluído no cluster e fica visível na interface do usuário do Rancher.

== Tabela de partição implantada

Quando o sistema operacional estiver instalado, a tabela de partição do sistema operacional, de acordo com os valores padrão, terá a seguinte aparência

|===
| Rótulo | Tamanho padrão | Contém

| COS_GRUB
| 64 MiB
| Partição de inicialização UEFI

| COS_STATE
| 8 GiB
| Imagens de sistema de arquivos inicializáveis A/B construídas a partir de imagens OCI

| COS_OEM
| 64 MiB
| Arquivos de configuração de nuvem OEM e outros dados

| COS_RECOVERY
| 4 GiB
| Imagem do sistema de arquivos de recuperação se COS_STATE for destruído

| COS_PERSISTENT
| Espaço restante
| Todo o conteúdo das pastas persistentes
|===

Observe que essa é a estrutura básica de qualquer sistema operacional criado pelo {elemental_toolkit_url}[{elemental_toolkit_name}].

== {elemental-product-name} Raiz imutável

Uma das características dos sistemas operacionais {elemental-product-name} é a configuração de um sistema de arquivos raiz imutável em que alguns locais efêmeros ou persistentes são aplicados sobre ele. A estrutura padrão das pastas está listada na matriz abaixo.

[cols=",^,^,^"]
|===
| Caminho | Somente leitura | Efêmera | Persistente

| /
| x
|
|

| /etc
|
| x
|

| /etc/cni
|
|
| x

| /etc/iscsi
|
|
| x

| /etc/rancher
|
|
| x

| /etc/ssh
|
|
| x

| /etc/systemd
|
|
| x

| /srv
|
| x
|

| /home
|
|
| x

| /opt
|
|
| x

| /root
|
|
| x

| /var
|
| x
|

| /usr/libexec
|
|
| x

| /var/lib/cni
|
|
| x

| /var/lib/kubelet
|
|
| x

| /var/lib/rancher
|
|
| x

| /var/lib/elemental
|
|
| x

| /var/lib/NetworkManager
|
|
| x

| /var/lib/calico
|
|
| x

| /var/log
|
|
| x
|===
