include::partial$variables.adoc[]
= 監査スキャナ - 制限
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Kubernetes環境でポリシーやイベントタイプを評価するためにAudit Scannerを使用する際の制限について学びます。
:doc-persona: ["kubewarden-user"、"kubewarden-operator"、"kubewarden-policy-developer"、"kubewarden-integrator"]]。
:doc-topic: ["explanations", "audit-scanner", "limitations"]
:doc-type: ["explanation"]
:keywords: ["kubewarden"、"kubernetes"、"監査スキャナ"]]。
:sidebar_label: 制限事項
:current-version: {page-origin-branch}

== 対応イベントタイプ

ポリシーは`CREATE` 、`UPDATE` 、`DELETE` イベントを検査することができる。

監査スキャナーは、`UPDATE` イベントをシミュレートできない。なぜなら、リソースのどの部分に変更が必要なのかわからないからである。

そのため、監査スキャナは、`UPDATE` イベントのみに関係するポリシーを無視する。

[NOTE]
====

audit-scanner v1.7.0リリースでは、`CREATE` イベントのみをサポートしています。`DELETE` 。

====


== ユーザーおよびユーザーグループの情報に依存するポリシー

各Kubernetesアドミッションリクエストオブジェクトは、どのユーザー（またはServiceAccount）がイベントを開始し、どのグループに属しているかについての情報を持っています。

監査スキャナーによってシミュレートされるすべてのイベントは、同じハードコードされたユーザーとグループから発生する。そのため、このような価値観に頼った政策では、意味のある結果は生まれない。

このような場合は、ポリシーを監査不可に設定する。

== 外部データに依存する政策

ポリシーは、評価を行う際に外部データを要求し、使用することができる。これらのポリシーは監査チェックで評価できるが、その結果は外部データによって変わる可能性がある。

== ポリシーによる`*` の使用

`AdmissionPolicy` 、`ClusterAdmissionPolicy` の両カスタム・リソースには以下のフィールドがある：

[subs="+attributes",yaml]
----
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
----

`apiGroups`,`apiVersions` および`resources` 属性は、ワイルドカード`*` を使用できます。このワイルドカード記号は、ポリシーがフィールドで使用されているすべての値と一致するようにする。監査スキャナは、`*` シンボルを使用するポリシーを無視します。
