= Gestión de componentes empaquetados
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

== Despliegue automático de manifiestos (AddOns)

En los nodos servidor, cualquier archivo que se encuentre en `/var/lib/rancher/k3s/server/manifests` se desplegará automáticamente en Kubernetes de forma similar a `kubectl apply`, tanto al iniciarse como cuando se modifique el archivo en el disco. La eliminación de archivos de este directorio no eliminará los recursos correspondientes del clúster.

Los manifiestos se rastrean como recursos personalizados de `AddOn` en el espacio de nombres `kube-system`. Cualquier error o advertencia que se encuentre al aplicar el archivo de manifiesto puede verse utilizando `kubectl describe` en el correspondiente `AddOn`, o utilizando `kubectl get event -n kube-system` para ver todos los eventos de ese espacio de nombres, incluidos los del controlador de despliegue.

=== Componentes embalados

K3s viene con una serie de componentes empaquetados que se despliegan como AddOns a través del directorio manifests: `coredns`, `traefik`, `local-storage`, y `metrics-server`. El controlador integrado `servicelb` LoadBalancer no tiene un archivo de manifiesto, pero puede desactivarse como si fuera un `AddOn` por razones históricas.

Los manifiestos de los componentes empaquetados son gestionados por K3s, y no deben ser alterados. Los archivos se reescriben en el disco cada vez que se inicia K3s, para garantizar su integridad.

=== Complementos de usuario

Puede colocar archivos adicionales en el directorio de manifiestos para su despliegue como `AddOn`. Cada archivo puede contener varios recursos Kubernetes, delimitados por el separador de documentos YAML `---`. Para obtener más información sobre la organización de recursos en manifiestos, consulte la sección https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/[Managing Resources] de la documentación de Kubernetes.

==== Requisitos de denominación de archivos

El nombre `AddOn` de cada archivo del directorio de manifiesto se deriva del nombre base del archivo.
Asegúrese de que todos los archivos dentro del directorio de manifiestos (o dentro de cualquier subdirectorio) tienen nombres que son únicos, y se adhieren a Kubernetes https://kubernetes.io/docs/concepts/overview/working-with-objects/names/[restricciones de nomenclatura de objetos].
También se debe tener cuidado de no entrar en conflicto con los nombres utilizados por los componentes por defecto del paquete K3s, incluso si estos componentes están desactivados.

A continuación se muestra un ejemplo de error si el nombre del archivo contiene guiones bajos:

____
`Fallo al procesar config: fallo al procesar /var/lib/rancher/k3s/server/manifests/example_manifest.yaml:
   Addon.k3s.cattle.io "example_manifest" no es válido: metadata.name: Valor no válido: "ejemplo_manifiesto": un subdominio RFC 1123 en minúsculas debe constar de caracteres alfanuméricos en minúsculas, '-' o '.', y debe empezar y terminar con un carácter alfanumérico (p. ej., 'ejemplo.com', el regex utilizado para la validación es '[a-z0-9]([-a-z0-9]*[a-z0-9])??(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?*)`
____

[WARNING]
====
Si tiene varios nodos de servidor y coloca manifiestos AddOn adicionales en más de un servidor, es su responsabilidad asegurarse de que los archivos permanezcan sincronizados en todos esos nodos. K3s no sincroniza el contenido AddOn entre nodos, y no puede garantizar un comportamiento correcto si diferentes servidores intentan desplegar manifiestos conflictivos.
====


== Desactivación de manifiestos

Hay dos formas de desactivar el despliegue de contenidos específicos desde el directorio de manifiestos.

[#_using_the_disable_flag]
=== Utilización de la bandera `--disable` 

Los complementos para componentes empaquetados enumerados anteriormente, además de los complementos para cualquier manifiesto adicional colocado en el directorio `manifests`, pueden desactivarse con la bandera `--disable`. Los complementos deshabilitados se desinstalan activamente del clúster y los archivos de origen se eliminan del directorio `manifests`.

Por ejemplo, para deshabilitar la instalación de traefik en un nuevo clúster, o para desinstalarlo y eliminar el manifiesto de un clúster existente, puede iniciar K3s con `--disable=traefik`. Se pueden desactivar varios elementos separando sus nombres con comas o repitiendo el indicador.

=== Uso de archivos .skip

Para cualquier archivo bajo `/var/lib/rancher/k3s/server/manifests`, puede crear un archivo `.skip` que hará que K3s ignore el manifiesto correspondiente. El contenido del archivo `.skip` no importa, sólo se comprueba su existencia. Tenga en cuenta que la creación de un archivo `.skip` después de que se haya creado un AddOn no lo eliminará ni modificará los recursos creados por él; el archivo se tratará como si no existiera.

Por ejemplo, si se crea un archivo `traefik.yaml.skip` vacío en el directorio de manifiestos antes de iniciar K3s por primera vez, K3s omitirá el despliegue de `traefik.yaml`:

[,bash]
----
$ ls /var/lib/rancher/k3s/server/manifests
ccm.yaml      local-storage.yaml  rolebindings.yaml  traefik.yaml.skip
coredns.yaml  traefik.yaml

$ kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   local-path-provisioner-64ffb68fd-xx98j   1/1     Running   0          74s
kube-system   metrics-server-5489f84d5d-7zwkt          1/1     Running   0          74s
kube-system   coredns-85cb69466-vcq7j                  1/1     Running   0          74s
----

Si Traefik ya se había desplegado antes de crear el archivo `traefik.skip`, Traefik se quedaría como está, y no se vería afectado por futuras actualizaciones cuando se actualice K3s.

== Complementos de Helm

Para obtener información sobre la gestión de cartas Helm mediante el despliegue automático de manifiestos, consulte la sección sobre xref:add-ons/helm.adoc[Helm.]
