= Gestión de roles de servidor
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Al iniciar el servidor K3s con `--cluster-init` se ejecutarán todos los componentes del plano de control, incluidos apiserver, controller-manager, scheduler y etcd. Es posible desactivar componentes específicos para dividir las funciones de plano de control y etcd en nodos separados.

[IMPORTANT]
====
Este documento sólo es relevante cuando se utiliza etcd incrustado. Cuando no se utiliza etcd incrustado, todos los servidores tendrán el rol de plano de control y ejecutarán componentes de plano de control.
====


== Nodos dedicados `etcd` 

Para crear un servidor con sólo el rol `etcd`, inicie K3s con todos los componentes del plano de control deshabilitados:

----
curl -fL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server --cluster-init --disable-apiserver --disable-controller-manager --disable-scheduler
----
Donde `INSTALL_K3S_ARTIFACT_URL` es la https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[URL de]

Este primer nodo iniciará etcd y esperará a que se unan otros nodos `etcd` y/o `control-plane`. El cluster no será utilizable hasta que se una un servidor adicional con los componentes `control-plane` habilitados.

== Nodos dedicados `control-plane` 

[NOTE]
====
Un nodo dedicado `control-plane` no puede ser el primer servidor del clúster; debe haber un nodo existente con el rol `etcd` antes de unirse a los nodos dedicados `control-plane`.
====


Para crear un servidor sólo con el rol `control-plane`, inicie k3s con etcd deshabilitado:

[,bash]
----
curl -fL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server --token <token> --disable-etcd --server https://<etcd-only-node>:6443
----

Una vez creados los nodos de servidor dedicados, los roles seleccionados serán visibles en `kubectl get node`:

[,bash]
----
$ kubectl get nodes
NAME           STATUS   ROLES                       AGE     VERSION
k3s-server-1   Ready    etcd                        5h39m   v1.20.4+k3s1
k3s-server-2   Ready    control-plane,master        5h39m   v1.20.4+k3s1
----

== Añadir roles a servidores existentes

Se pueden añadir funciones a los nodos dedicados existentes reiniciando los K3 con los indicadores de desactivación eliminados. Por ejemplo, si desea añadir la función `control-plane` a un nodo dedicado `etcd`, puede eliminar los indicadores `--disable-apiserver --disable-controller-manager --disable-scheduler` de la unidad systemd o del archivo config y reiniciar el servicio.

== Sintaxis del archivo de configuración

Al igual que con todos los demás indicadores de la CLI, puede utilizar el xref:installation/configuration.adoc#_configuration_file[archivo de configuración] para desactivar componentes, en lugar de pasar las opciones como indicadores de la CLI. Por ejemplo, para crear un nodo dedicado a `etcd`, puede colocar los siguientes valores en `/etc/rancher/k3s/config.yaml`:

[,yaml]
----
cluster-init: true
disable-apiserver: true
disable-controller-manager: true
disable-scheduler: true
----
