= Desinstalación de K3s
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

[CAUTION]
====
La desinstalación del K3s puede provocar la pérdida de datos.
====

Si instaló K3s utilizando el script de instalación, se generó un script para desinstalar K3s durante la instalación.

La ejecución del script de desinstalación detiene K3s y todos los pods en ejecución, y elimina el datastore local del cluster, los datos del xref:add-ons/storage.adoc#_setting_up_the_local_storage_provider[Local Storage] Persistent Volume, la configuración del nodo, y todos los scripts y herramientas CLI.

No elimina ningún dato de datastores externos, o creados por pods que utilicen Kubernetes Persistent Volumes externos.

Si está planeando volver a unir un nodo a un clúster existente después de desinstalar y volver a instalar, asegúrese de eliminar el nodo del clúster para garantizar que se elimina el secreto de contraseña del nodo. Consulte la documentación xref:architecture.adoc#_how_agent_node_registration_works[Registro de nodos] para obtener más información.

== Desinstalación de servidores

Para desinstalar K3s de un nodo servidor, ejecute:

[,bash]
----
/usr/local/bin/k3s-uninstall.sh
----

== Desinstalación de agentes

Para desinstalar K3s de un nodo agente, ejecute:

[,bash]
----
/usr/local/bin/k3s-agent-uninstall.sh
----
