include::partial$variables.adoc[]
= Validation à l'aide de requêtes JSON
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Mettre en œuvre une logique de validation à l'aide de requêtes JSON en extrayant les données pertinentes de la représentation JSON d'un objet Kubernetes.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "validation-using-json"].
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "validation using JSON queries"].
:current-version: {page-origin-branch}

Une section précédente montre comment écrire une politique dexref:tutorials/writing-policies/go/04-validation.adoc[validation]en utilisant des types Go décrivant des objets Kubernetes.

Il existe une autre façon d'écrire la logique de validation, en extrayant les données pertinentes du document JSON à l'aide de requêtes ad hoc.

Cette approche _"jq-like"_ peut être utile lorsque la politique doit regarder profondément à l'intérieur d'un objet Kubernetes.
Elle est particulièrement utile lorsqu'il s'agit d'objets internes optionnels.

Ce document réimplémente le code précédent en utilisant des requêtes JSON au lieu de décomposer la charge utile JSON en types Go.

== La fonction `+validate+` 

Vous pouvez utiliser la politique que vous venez de créer et modifier sa fonction `+validate+` pour ne pas utiliser les types Go qui définissent les objets Kubernetes.

Vous pouvez utiliser la bibliothèque https://github.com/tidwall/gjson[`+gjson+`] pour extraire les données de l'objet JSON brut.

Tout d'abord, vous devez modifier la section des exigences.
Voici à quoi devrait ressembler le code :

[,go]
----
import (
    "encoding/json"
    "fmt"

    mapset "github.com/deckarep/golang-set/v2"
    kubewarden "github.com/kubewarden/policy-sdk-go"
    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
    "github.com/tidwall/gjson"
)
----

Modifiez la fonction `+validate+` pour qu'elle ressemble à ce qui suit :

.`+validate+` fonction
[%collapsible]
======

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // Create a ValidationRequest instance from the incoming payload
    validationRequest := kubewarden_protocol.ValidationRequest{}
    err := json.Unmarshal(payload, &validationRequest)
    if err != nil {
        return kubewarden.RejectRequest(
            kubewarden.Message(err.Error()),
            kubewarden.Code(400))
    }

    // Create a Settings instance from the ValidationRequest object
    settings, err := NewSettingsFromValidationReq(&validationRequest)
    if err != nil {
        return kubewarden.RejectRequest(
            kubewarden.Message(err.Error()),
            kubewarden.Code(400))
    }

    // Access the **raw** JSON that describes the object
    podJSON := validationRequest.Request.Object

    // NOTE 1
    data := gjson.GetBytes(
        podJSON,
        "metadata.labels")

    var validationErr error
    labels := mapset.NewThreadUnsafeSet[string]()
    data.ForEach(func(key, value gjson.Result) bool {
        // NOTE 2
        label := key.String()
        labels.Add(label)

        // NOTE 3
        validationErr = validateLabel(label, value.String(), &settings)

        // keep iterating if there are no errors
        return validationErr == nil
    })

    // NOTE 4
    if validationErr != nil {
        return kubewarden.RejectRequest(
            kubewarden.Message(validationErr.Error()),
            kubewarden.NoCode)
    }

    // NOTE 5
    for requiredLabel := range settings.ConstrainedLabels {
        if !labels.Contains(requiredLabel) {
            return kubewarden.RejectRequest(
                kubewarden.Message(fmt.Sprintf("Constrained label %s not found inside of Pod", requiredLabel)),
                kubewarden.NoCode)
        }
    }

    return kubewarden.AcceptRequest()
}
----

======

La première partie de la fonction `+validate+` est similaire à la précédente.
NOTE : marquons les changements.

. Vous utilisez un sélecteur `+gjson+` pour obtenir la carte `+label+` fournie par l'objet intégré dans la requête
. Vous utilisez une aide `+gjson+` pour parcourir les résultats de la requête.
Si la requête n'aboutit à aucun résultat, la boucle n'a jamais lieu.
. Vous utilisez la fonction `+validateLabel+` pour valider l'étiquette et sa valeur, comme précédemment.
Vous ajoutez également les étiquettes trouvées dans le pod à un site préalablement défini : `+mapset.Set+`.
. Si la validation produit une erreur, vous renvoyez immédiatement une réponse de rejet de la validation.
. Comme précédemment, vous itérez sur les `+constrainedLabels+` pour vérifier qu'ils sont tous spécifiés dans le Pod.
Le code a été légèrement modifié afin d'utiliser les données précédemment renseignées sur le site `+mapset.Set+`.

== Test du code de validation

Les tests unitaires et les tests de bout en bout n'ont pas besoin d'être modifiés, vous pouvez les exécuter comme avant :

[subs="+attributes",console]
----
make test
----

[subs="+attributes",console]
----
go test -v
=== RUN   TestParseValidSettings
--- PASS: TestParseValidSettings (0.00s)
=== RUN   TestParseSettingsWithInvalidRegexp
--- PASS: TestParseSettingsWithInvalidRegexp (0.00s)
=== RUN   TestDetectValidSettings
--- PASS: TestDetectValidSettings (0.00s)
=== RUN   TestDetectNotValidSettingsDueToBrokenRegexp
--- PASS: TestDetectNotValidSettingsDueToBrokenRegexp (0.00s)
=== RUN   TestDetectNotValidSettingsDueToConflictingLabels
--- PASS: TestDetectNotValidSettingsDueToConflictingLabels (0.00s)
=== RUN   TestValidateLabel
--- PASS: TestValidateLabel (0.00s)
PASS
ok      github.com/kubewarden/go-policy-template    0.002s
----

[subs="+attributes",console]
----
make e2e-tests
----

[subs="+attributes",console]
----
bats e2e.bats
e2e.bats
 ✓ accept when no settings are provided
 ✓ accept because label is satisfying a constraint
 ✓ accept labels are not on deny list
 ✓ reject because label is on deny list
 ✓ reject because label is not satisfying a constraint
 ✓ reject because constrained label is missing
 ✓ fail settings validation because of conflicting labels
 ✓ fail settings validation because of invalid constraint

8 tests, 0 failures
----

Tous les tests fonctionnent comme prévu.
