= Envío de troncos
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Instalación de agentes

=== Openshift

En Openshift no se admiten fácilmente cargadores de logs de terceros, la plataforma tiene opciones para el reenvío de logs, que se utiliza en lugar de la configuración promtail incluida en el cuadro de mando de SUSE Observability.  Para obtener instrucciones detalladas sobre cómo configurar esto, consulte la documentación de Kubernetes stackpack en su instancia de SUSE Observability en ejecución.

=== Kubernetes

La configuración por defecto de la carta helm del Agente k8s de SUSE Observability establece el envío de registros como habilitado a través de los valores de helm suministrados con la carta:

[,yaml]
----
logsAgent:
  # logsAgent.enabled -- Enable / disable k8s pod log collection
  enabled: true
----

Lo anterior garantizará que se implante un contenedor promtail en cada nodo para recopilar registros y enviarlos a SUSE Observability.  Para implantaciones en las que no es deseable enviar registros a SUSE Observability, establezca el valor anterior en `false`.

=== Ejecutar Promtail Pods adicionales

SUSE Observability utiliza una configuración ajustada para la ingestión de registros, y esto no suele ajustarse a los requisitos auxiliares.  Por lo tanto, no es posible ejecutar una configuración independiente para la ingestión de registros en otros puntos finales de destino; en su lugar, se recomienda ejecutar un segundo pod de promtail que se ocupe de estos requisitos como un asunto independiente del promtail que despliega el gráfico del timón del agente.
