= Verifique se a instrumentação está funcionando
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

Se a configuração do coletor e da instrumentação tiver sido bem-sucedida, os dados deverão estar disponíveis no SUSE Observability em cerca de um ou dois minutos.

Você pode verificar se o SUSE Observability está recebendo rastreamentos:

. Abra o SUSE Observability em um navegador
. Localizar (um dos) pods que está instrumentado
. Selecione o pod para abrir a página Destaques
. Abra a perspectiva de rastreamento. Se o pod estiver atendendo ao tráfego, ele deverá mostrar os traços

Para verificar se o SUSE Observability está recebendo métricas:

. Abra o SUSE Observability em um navegador
. Abra o explorador de métricas no menu
. Pesquise as métricas expostas por seu aplicativo

Se ainda não houver métricas após 5 minutos, é provável que algo esteja mal configurado. Consulte a xref:/setup/otel/troubleshooting.adoc[solução de problemas] para obter ajuda.
