include::partial$variables.adoc[]
= Rouille
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Apprenez à rédiger des politiques de contrôle d'admission dans Rust avec le SDK simplifié des contrôleurs d'admission de sécurité de SUSE et des projets modèles.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "introduction"].
:sidebar_label: Rouille
:current-version: {page-origin-branch}

https://www.rust-lang.org/[Rust] est le langage de programmation le plus mature capable de générer des modules WebAssembly.
WebAssembly est un citoyen de première classe dans le monde Rust, de sorte que de nombreux outils et caisses de l'écosystème Rust fonctionnent dès le départ.

{project-name} fournit un Rust https://crates.io/crates/kubewarden-policy-sdk[SDK] qui simplifie le processus d'écriture des politiques.
Il existe également un https://github.com/kubewarden/rust-policy-template[projet modèle] qui sert d'échafaudage à un projet de politique utilisant l'utilitaire https://github.com/cargo-generate/cargo-generate[] utilitaire.

Cette documentation montre comment utiliser ces projets pour écrire des politiques {short-project-name} en utilisant Rust.
Il ne couvre pas les détails du SDK Rust de {short-project-name}.
Les détails se trouvent dans la https://docs.rs/kubewarden-policy-sdk/0.1.0[documentation de la caisse].

== Obtenir les dépendances Rust

Installez le compilateur Rust et ses outils en utilisanthttps://github.com/rust-lang/rustup[] rustup.
Reportez-vous à la rustup https://rust-lang.github.io/rustup/installation/index.html[documentation d'installation de].

Une fois que vous avez installé `rustup`, ajoutez la cible WebAssembly System Interface (WASI) :

[subs="+attributes",console]
----
rustup target add wasm32-wasip1
----

== Dépendances OSX

Pour utiliser `cargo-generate`, vous devez ajouter le jeu d'outils Xcode.
S'il n'est pas installé par Xcode, la commande suivante vous donne les dépendances nécessaires :

[subs="+attributes",console]
----
xcode-select --install
----
