include::partial$variables.adoc[]
= Création d'une politique
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Apprenez à créer et à configurer des politiques de validation qui contrôlent les demandes de création de pods en fonction de critères de rejet personnalisables.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "creating-policies"].
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "policy creation"]
:sidebar_label: Création d'une politique
:current-version: {page-origin-branch}

Par exemple, vous créez une politique de validation simple qui traite les demandes de création de pods.

La politique examine l'attribut `metadata.name` du pod et rejette les pods dont le nom n'est pas valide.
La liste des noms non valides doit pouvoir être configurée par les utilisateurs finaux de la politique.

Les paramètres de la politique ressemblent à quelque chose comme :

[subs="+attributes",yaml]
----
invalid_names:
- bad_name1
- bad_name2
----

La politique doit accepter la création d'un pod comme le suivant :

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

Il devrait rejeter la création d'un pod comme :

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: bad_name1
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

== Échafaudage du nouveau projet politique

Vous pouvez créer un nouveau projet de politique en utilisant `cargo generate` avec lehttps://github.com/kubewarden/rust-policy-template[projet modèle].

Tout d'abord, installez `cargo-generate`. Cela nécessite https://pkgs.org/download/openssl-devel[openssl-devel].

[subs="+attributes",shell]
----
cargo install cargo-generate
----

Il s'agit maintenant d'échafauder le projet de la manière suivante :

[subs="+attributes",shell]
----
cargo generate --git https://github.com/kubewarden/rust-policy-template \
               --branch main \
               --name demo
----

La commande produit des résultats tels que

[subs="+attributes",console]
----
🔧   Creating project called `demo`...
✨   Done! New project created /<some-path-name>/demo
----

Le nouveau projet de politique est ainsi créé dans le sous-répertoire `demo`.

[NOTE]
====

Si vous envisagez d'utiliser la fonctionnalité du registre de conteneurs GitHub dans la démo, vous devezhttps://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry#enabling-the-container-registry-for-your-personal-account[activer la prise en charge améliorée des conteneurs à l'adresse].
====


=== Essais

Vous pouvez essayer :

[subs="+attributes",console]
----
cargo test
----

Cela permet de tester l'échafaudage généré. Si tout est correctement en place, vous verrez une série de messages de compilation se terminant par une sortie comme :

[subs="+attributes",console]
----
running 4 tests
test settings::tests::validate_settings ... ok
test tests::accept_request_with_non_pod_resource ... ok
test tests::accept_pod_with_valid_name ... ok
test tests::reject_pod_with_invalid_name ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
----
