include::partial$variables.adoc[]
= Élaboration et diffusion des politiques
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Suivez ces étapes essentielles pour élaborer et distribuer des politiques de manière efficace pour votre installation {project-name}.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "build-and-distribute"].
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "rust", "build and distribute"]
:sidebar_label: Élaboration et diffusion des politiques
:current-version: {page-origin-branch}

== Élaboration de la politique

Jusqu'à présent, vous avez construit la politique avec une cible de compilation du même système d'exploitation et de la même architecture que votre machine de développement.

Il est maintenant temps de construire la politique en tant que binaire WebAssembly, un fichier `.wasm`.

Vous utilisez la commande :

[subs="+attributes",console]
----
make policy.wasm
----

Cette commande construit le code en mode release, avec une cible de compilation WebAssembly.

La compilation produit un fichier `policy.wasm`:

[subs="+attributes",console]
----
$ file policy.wasm
policy.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
----

== Diffusion de la politique

{project-name} documente la distribution des politiques dans la sectionxref:../../../explanations/distributing-policies.adoc[distribution des politiques].

== Plus d'exemples

Vous pouvez trouver d'autres politiques de Rust {short-project-name} dans l'espace GitHub de {short-project-name}.https://github.com/search?l=Rust&q=topic%3Apolicy-as-code+org%3Akubewarden&type=Repositories[Cette requête] peut vous aider à les trouver.

Les référentiels de politiques {short-project-name}, indiqués par cette requête, ont des actions GitHub qui automatisent les tâches suivantes :

* Exécuter les tests unitaires et le code linting sur les pull requests et après les fusions de code dans la branche principale.
* Construire la politique en mode `release` et la pousser vers un registre OCI en tant qu'artefact.
