= 开始使用开放式遥测技术
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

image::otel/open-telemetry.svg[向 SUSE Observability 发送指标和跟踪的开放式遥测采集器和 2 个仪器应用程序]

SUSE Observability 支持https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]。开放遥测是一套标准化协议和开源框架，用于收集、转换和传输跟踪、度量和日志等遥测数据。开放式遥测技术支持多种编程语言和平台。

SUSE Observability 支持指标和跟踪，并将 Open Telemetry 指标和跟踪添加到 SUSE Observability 代理提供的（Kubernetes）拓扑数据中。因此，还需要安装 SUSE Observability 代理。即将支持日志和在没有 SUSE Observability 代理的情况下使用 Open Telemetry。

开放式遥测技术由几个不同的组件组成。要与 SUSE Observability 配合使用，最重要的部分是用于检测应用程序的xref:/setup/otel/languages/README.adoc[SDK]和xref:/setup/otel/collector.adoc[Open Telemetry 收集器]。我们将展示如何配置这两种软件以便与 SUSE Observability 配合使用。

如果您的应用程序已经使用 Open Telemetry 或 Open Telemetry 支持的任何其他库（如 Jaeger 或 Zipkin）进行了仪表化，则可使用收集器将数据传输到 SUSE Observability，而无需额外的仪表化。

SUSE Observability 要求收集器配置特定的处理器和身份验证，以确保 SUSE Observability 使用的所有数据都可用。

== 参考资料

* https://opentelemetry.io/docs/collector/[采集器]打开遥测文件上的遥测
* https://opentelemetry.io/docs/languages/[用于]在开放式遥测文件上
