= 支持 SUSE Observability 开放式遥测协议
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

SUSE Observability 支持两个版本的 OTLP 协议，即`+grpc+` 版本（也称为 OTLP）和`+http/protobuf+` （也称为 HTTP 上的 OTLP）。在收集器配置中，您可以选择要使用的导出器，但一定要为 SUSE Observability 配置正确的 URL。`+grpc+` 版本的协议更受青睐，因为它允许更大的有效载荷和更高的吞吐量。但是，如果您的基础设施对`+grpc+` 的支持较差，您可以切换到 HTTP 版本。另请参见xref:/setup/otel/troubleshooting.adoc#_some_proxies_and_firewalls_dont_work_well_with_grpc[故障排除]

== SUSE 云计算可观察性

SUSE Cloud Observability 的端点是

* OTLP:`+otlp-<your-suse-observability>.app.stackstate.io:443+` （不含 URL 方案）
* 通过 HTTP 传输的 OTLP：`+https://otlp-http-<your-suse-observability>.app.stackstate.io+` （URL 方案：`+https+`)

== 自托管 SUSE Observability

对于自托管安装，您需要通过为 SUSE Observability 配置入口，启用xref:/setup/install-stackstate/kubernetes_openshift/ingress.adoc#_configure_ingress_rule_for_open_telemetry[其中]一个端点，或同时启用两个端点。

当 SUSE Observability 与收集器在同一集群中运行时，您也可以通过使用服务端点在没有入口的情况下使用它，但这只能通过 HTTP 协议实现：

* 通过 HTTP 的 OTLP： `+http://suse-observability-otel-collector.<namespace>.svc.cluster.local:4318+`

确保在收集器配置中设置`+insecure: true+` （见下一节），以允许使用普通 http 端点而不是 https。

GRPC 协议不支持通过不安全连接发送凭证，因此只能与安全入口设置结合使用。

== 收集器配置

=== OTLP 协议

采集器配置中的示例是这样使用 OTLP 协议的：

----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
exporters:
  otlp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp endpoint, for example otlp-suse-observability.my.company.com:443
    endpoint: <otlp-suse-observability-endpoint>
    # Optional TLS configurations:
    #tls:
    # To disable certificate verification (but still use TLS):
    #  insecure_skip_verify: true
----

=== OTLP HTTP 协议

要使用 HTTP 上的 OTLP 协议，请使用`+otlphttp+` 输出程序。同时将管道中的所有出口商引用从`+otlp/suse-observability+` 更新为`+otlphttp/suse-observability+` ！使用查找/替换确保更改所有出现的内容。

----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
exporters:
  otlphttp/stackstate:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp-http endpoint, for example https://otlp-http-suse-observability.my.company.com:443
    endpoint: <otlp-http-suse-observability-endpoint>
    # Optional TLS configurations:
    #tls:
    # To disable TLS entirely:
    #  insecure: true
    # To disalbe certificate verification (but still use TLS):
    #  insecure_skip_verify: true
----

有更多的配置可用于控制输出程序的确切要求和行为。例如，也可以使用自定义 CA 根证书或启用客户端证书。详情请查看https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md[输出程序文档] OTLP。
