= 开始使用开放式遥测技术
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

image::otel/open-telemetry.svg[向 SUSE Observability 发送指标和跟踪的开放式遥测采集器和 2 个仪器应用程序]

SUSE Observability 支持https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]。开放遥测是一套标准化协议和开源框架，用于收集、转换和传输跟踪、度量和日志等遥测数据。开放式遥测技术支持多种编程语言和平台。

SUSE Observability 支持度量和跟踪。当与 Kubernetes 堆栈包结合使用时，Kubernetes pod 将在可用的情况下丰富痕迹。通过安装 Open Telemetry 堆栈包，可为服务和服务实例提供新的概览页面，从而访问跟踪和跨度指标。开放式遥测指标可用于监控器和指标绑定。堆栈包带有跨度指标、.NET 和 JVM 内存指标的指标绑定。此外，还可对跨度误差率和持续时间进行开箱即用的监控。

与 SUSE Observability 配合使用的建议设置是，使用适用的 Open Telemetryxref:/setup/otel/instrumentation/README.adoc[SDK]对应用程序进行仪器化，并在仪器化应用程序附近安装xref:/setup/otel/collector.adoc[Open Telemetry 收集器]，以预处理数据（使用 Kubernetes 标签丰富数据、对跟踪进行采样等），然后将数据发送到 SUSE Observability。开放式遥测收集器还可用于从多种类型的遥测源收集指标，而无需使用 SDK 对应用程序进行检测。请参阅https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry 收集器集成]，了解更多详情以及是否支持您的数据库或遥测协议。

请按照xref:/setup/otel/getting-started/README.adoc[入门]指南进行设置，以便与 SUSE Observability 配合使用。

== 参考资料

* https://opentelemetry.io/docs/collector/[采集器]打开遥测文件上的遥测
* https://opentelemetry.io/ecosystem/registry/?language=collector[开放式遥测采集器集成]
* https://opentelemetry.io/docs/instrumentation/README.md[用于]在开放式遥测文件上
