= 役割
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability セルフホスト

== 概要

SUSE Observabilityのすべてのユーザには、サブジェクトとxref:/setup/security/rbac/rbac_permissions.adoc[パーミッションの]セットが割り当てられる必要があります。ロールは、特定のデータセットにアクセスできるユーザーのグループを表す。SUSE Observabilityには定義済みのロールが同梱されていますが、ニーズに合わせてロールを作成することもできます。

== 定義済みの役割

SUSE Observabilityには4つのロールがあらかじめ定義されています：

* *管理者*- すべてのビューにフルアクセスでき、すべての権限を持ちます。
* *パワーユーザ*- 通常は、チームのSUSE Observabilityを設定する必要があるユーザに付与されますが、SUSE Observabilityのインストール全体を管理することはありません。
* *Kubernetes Troubleshooter*- モニターの有効化/無効化、カスタムビューの作成、Cliの使用など、トラブルシューティングにSUSE Observabilityを使用するために必要なすべての権限があります。
* *ゲスト*- SUSE Observabilityに読み取り専用でアクセスできます。

各定義済みSUSE Observabilityロールに割り当てられている権限は、以下のとおりです。さまざまなパーミッションの詳細と、`sts` CLI を使用したパーミッションの管理方法については、xref:/setup/security/rbac/rbac_permissions.adoc[役割ベースのアクセス制御（RBAC）パーミッションを]参照してください。

[tabs]
====
管理者::
+
--

管理者ロール（`stackstate-admin` ）：すべての権限が割り当てられています。

事前に定義された管理者ロール（`stackstate-admin` ）に割り当てられた権限を以下に示す。これらは、`sts` CLIを使用して取得された。さまざまなパーミッションの詳細と、`sts` CLIを使用した管理方法については、xref:/setup/security/rbac/rbac_permissions.adoc[RBACパーミッションを]参照してください。

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-admin
Got subject from the following subject sources: Static

PERMISSION                      | RESOURCE
create-dashboards               | system
create-favorite-dashboards      | system
create-favorite-views           | system
create-ingestion-api-keys       | system
create-metric-bindings          | system
create-monitors                 | system
create-notifications            | system
create-service-tokens           | system
create-stackpack-configurations | system
create-views                    | system
delete-dashboards               | system
delete-favorite-dashboards      | system
delete-favorite-views           | system
delete-ingestion-api-keys       | system
delete-metric-bindings          | system
delete-monitors                 | system
delete-notifications            | system
delete-service-tokens           | system
delete-stackpack-configurations | system
delete-sync-data                | system
delete-views                    | system
execute-component-actions       | system
execute-monitors                | system
execute-restricted-scripts      | system
execute-scripts                 | system
get-agents                      | system
get-api-tokens                  | system
get-dashboards                  | system
get-ingestion-api-keys          | system
get-metric-bindings             | system
get-metrics                     | system
get-monitors                    | system
get-notifications               | system
get-permissions                 | system
get-service-tokens              | system
get-settings                    | system
get-stackpacks                  | system
get-sync-data                   | system
get-system-notifications        | system
get-topic-messages              | system
get-topology                    | system
get-traces                      | system
get-views                       | system
update-dashboards               | system
update-metric-bindings          | system
update-metrics                  | system
update-monitors                 | system
update-notifications            | system
update-permissions              | system
update-scoped-permissions       | system
update-settings                 | system
update-stackpack-configurations | system
update-stackpacks               | system
update-views                    | system
update-visualization            | system
----

--
パワーユーザー::
+
--

パワーユーザー・ロール（`stackstate-power-user` ）は、以下を除くすべてのアドミニストレーター権限を持つ：

* `execute-restricted-scripts`
* `update-permissions`
* `update-stackpacks`

事前に定義されたパワー・ユーザー・ロール（`stackstate-power-user` ）に割り当てられた権限を以下に示す。これらは、`sts` CLIを使用して取得された。さまざまなパーミッションの詳細と、`sts` CLIを使用した管理方法については、xref:/setup/security/rbac/rbac_permissions.adoc[RBACパーミッションを]参照してください。

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-power-user
Got subject from the following subject sources: Static

PERMISSION                      | RESOURCE
create-dashboards               | system
create-favorite-dashboards      | system
create-favorite-views           | system
create-metric-bindings          | system
create-monitors                 | system
create-notifications            | system
create-stackpack-configurations | system
create-views                    | system
delete-dashboards               | system
delete-favorite-dashboards      | system
delete-favorite-views           | system
delete-metric-bindings          | system
delete-monitors                 | system
delete-notifications            | system
delete-stackpack-configurations | system
delete-sync-data                | system
execute-component-actions       | system
execute-monitors                | system
execute-scripts                 | system
get-agents                      | system
get-api-tokens                  | system
get-dashboards                  | system
get-metric-bindings             | system
get-metrics                     | system
get-monitors                    | system
get-notifications               | system
get-permissions                 | system
get-settings                    | system
get-stackpacks                  | system
get-sync-data                   | system
get-system-notifications        | system
get-topic-messages              | system
get-topology                    | system
get-traces                      | system
get-views                       | system
update-dashboards               | system
update-metric-bindings          | system
update-metrics                  | system
update-monitors                 | system
update-notifications            | system
update-settings                 | system
update-stackpack-configurations | system
update-views                    | system
update-visualization            | system
----

--
トラブルシューター::
+
--

トラブルシュータロール(`stackstate-k8s-troubleshooter`)は、SUSE Observabilityで利用可能なすべてのデータにアクセスでき、ビューの作成やモニタの有効化/無効化を行うことができます。

事前に定義されたトラブルシューター・ロールに割り当てられたパーミッションを以下に示します。これらは`sts` CLI を使用して取得されました。さまざまなパーミッションの詳細と、`sts` CLIを使用した管理方法については、xref:/setup/security/rbac/rbac_permissions.adoc[RBACパーミッションを]参照してください。

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-k8s-troubleshooter
Got subject from the following subject sources: Static

PERMISSION                 | RESOURCE
create-dashboards          | system
create-favorite-dashboards | system
create-favorite-views      | system
create-monitors            | system
create-notifications       | system
create-views               | system
delete-dashboards          | system
delete-favorite-dashboards | system
delete-favorite-views      | system
delete-monitors            | system
delete-notifications       | system
delete-views               | system
execute-monitors           | system
get-agents                 | system
get-api-tokens             | system
get-dashboards             | system
get-metric-bindings        | system
get-metrics                | system
get-monitors               | system
get-notifications          | system
get-permissions            | system
get-settings               | system
get-stackpacks             | system
get-system-notifications   | system
get-topic-messages         | system
get-traces                 | system
get-views                  | system
update-dashboards          | system
update-monitors            | system
update-notifications       | system
update-stackpacks          | system
update-views               | system
update-visualization       | system
----

--
ゲスト::
+
--

ゲストロール(`stackstate-guest`)は、SUSE Observabilityへの読み取り専用アクセス権を持っています。

事前に定義されたGuestロールに割り当てられたパーミッションを以下に示します。これらは、`sts` CLIを使用して取得されました。さまざまなパーミッションの詳細と、`sts` CLIを使用した管理方法については、xref:/setup/security/rbac/rbac_permissions.adoc[RBACパーミッションを]参照してください。

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-guest
Got subject from the following subject sources: Static

PERMISSION                 | RESOURCE
create-dashboards          | system
create-favorite-dashboards | system
create-favorite-views      | system
delete-dashboards          | system
delete-favorite-dashboards | system
delete-favorite-views      | system
get-api-tokens             | system
get-dashboards             | system
get-metric-bindings        | system
get-metrics                | system
get-monitors               | system
get-notifications          | system
get-permissions            | system
get-settings               | system
get-system-notifications   | system
get-topic-messages         | system
get-traces                 | system
get-views                  | system
update-dashboards          | system
update-visualization       | system
----

--
====

== カスタムロール（構成RBAC）

常に利用可能な定義済みのロール（`stackstate-admin`,`stackstate-power-user`,`stackstate-k8s-troubleshooter`,`stackstate-guest` ）に加えて、カスタムロールを追加することができます。カスタムロールを追加する方法は複数あります：

. 設定ファイルを介して、定義済みのロールと同じパーミッションで実行されます。
. 設定ファイルを介して、カスタムパーミッションで
. `sts` CLIを使用すると、サブジェクトとその権限はデータベースに保存され、実行時に変更することができます。

設定ファイルを介して追加されたロールは再起動を必要とするため、短時間のダウンタイムが発生する。CLIを使って作成されたロールはデータベースに保存され、実行時に変更することができる。

=== 定義済みロールのカスタム名

このオプションは、定義済みのSUSE Observabilityロールが適しているが、外部認証プロバイダのロールの名前が異なる場合に使用します。たとえば、LDAP認証プロバイダが似ているが異なる名前のロールを持つ場合、`authentication.yaml` にこのYAMLスニペットを含めることで、LDAPからのロールに定義済みの同等のロールと同じパーミッションとスコープを与えることができます。

[,yaml]
----
stackstate:
  authentication:
    roles:
      guest: ["ldap-guest-role"]
      powerUser: ["ldap-power-user-role"]
      admin: ["ldap-admin-role"]
      k8sTroubleshooter: ["ldap-troubleshooter-role"]
----

SUSE Observabilityのインストール(またはすでに実行中のインスタンス)で使用するには、APIを再起動する必要があります：

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

=== 設定ファイルによるカスタム・ロール

`development-troubleshooter` という新しいロールを設定するには、`dev-test` クラスタに対してのみ、定義済みのトラブルシューター・ロールと同じパーミッションを許可する、次のYAMLスニペットを`authentication.yaml` に含めます：

[,yaml]
----
stackstate:
  authentication:
    roles:
      custom:
        development-troubleshooter:
          systemPermissions:
          - create-dashboards
          - create-favorite-dashboards
          - create-favorite-views
          - create-monitors
          - create-notifications
          - create-views
          - delete-dashboards
          - delete-favorite-dashboards
          - delete-favorite-views
          - delete-monitors
          - delete-notifications
          - delete-views
          - execute-monitors
          - get-agents
          - get-api-tokens
          - get-dashboards
          - get-metric-bindings
          - get-metrics
          - get-monitors
          - get-notifications
          - get-permissions
          - get-settings
          - get-stackpacks
          - get-system-notifications
          - get-topic-messages
          - get-traces
          - get-views
          - update-dashboards
          - update-monitors
          - update-notifications
          - update-stackpacks
          - update-views
          - update-visualization
          resourcePermissions:
            get-topology:
            - "cluster-name:dev-test"
----

SUSE Observabilityのインストール(またはすでに実行中のインスタンス)で使用するには、APIを再起動する必要があります：

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

=== CLIによるカスタムロール（Observability RBAC）

`development-troubleshooter` という新しいロールを設定するには、通常のトラブルシューター・ロールと同じパーミッションを許可しますが、`dev-test` クラスタに対してのみ許可されます。さらにこの被写体には、必要な一連の権限を割り当てる必要がある：

. サブジェクトを作成します（ロールと同じ名前で、ロールとサブジェクトのマッチングは名前ベースで大文字と小文字を区別します）：
+
[,text]
----
sts rbac create-subject --subject development-troubleshooter
sts rbac grant --subject development-troubleshooter --permission get-topology --resource "cluster-name:dev-test"'
----
+

. 設定されたサブジェクトは、UIの一部にアクセスし、その中でアクションを実行するためのパーミッションが必要です。トラブルシューター・ロールと同じ権限を付与するには、以下の例に従います：
+
[,text]
----
sts rbac grant --subject development-troubleshooter --permission create-dashboards
sts rbac grant --subject development-troubleshooter --permission create-favorite-dashboards
sts rbac grant --subject development-troubleshooter --permission create-favorite-views
sts rbac grant --subject development-troubleshooter --permission create-monitors
sts rbac grant --subject development-troubleshooter --permission create-notifications
sts rbac grant --subject development-troubleshooter --permission create-views
sts rbac grant --subject development-troubleshooter --permission delete-dashboards
sts rbac grant --subject development-troubleshooter --permission delete-favorite-dashboards
sts rbac grant --subject development-troubleshooter --permission delete-favorite-views
sts rbac grant --subject development-troubleshooter --permission delete-monitors
sts rbac grant --subject development-troubleshooter --permission delete-notifications
sts rbac grant --subject development-troubleshooter --permission delete-views
sts rbac grant --subject development-troubleshooter --permission execute-monitors
sts rbac grant --subject development-troubleshooter --permission get-agents
sts rbac grant --subject development-troubleshooter --permission get-api-tokens
sts rbac grant --subject development-troubleshooter --permission get-dashboards
sts rbac grant --subject development-troubleshooter --permission get-metric-bindings
sts rbac grant --subject development-troubleshooter --permission get-metrics
sts rbac grant --subject development-troubleshooter --permission get-monitors
sts rbac grant --subject development-troubleshooter --permission get-notifications
sts rbac grant --subject development-troubleshooter --permission get-permissions
sts rbac grant --subject development-troubleshooter --permission get-settings
sts rbac grant --subject development-troubleshooter --permission get-stackpacks
sts rbac grant --subject development-troubleshooter --permission get-system-notifications
sts rbac grant --subject development-troubleshooter --permission get-topic-messages
sts rbac grant --subject development-troubleshooter --permission get-traces
sts rbac grant --subject development-troubleshooter --permission get-views
sts rbac grant --subject development-troubleshooter --permission update-dashboards
sts rbac grant --subject development-troubleshooter --permission update-monitors
sts rbac grant --subject development-troubleshooter --permission update-notifications
sts rbac grant --subject development-troubleshooter --permission update-stackpacks
sts rbac grant --subject development-troubleshooter --permission update-views
sts rbac grant --subject development-troubleshooter --permission update-visualization
----

被写体名とアクセス許可は、大文字と小文字が区別されることにご注意ください。
