= 役割ベースのアクセス制御（RBAC）
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability セルフホスト

アクセス管理は、特定のトポロジー要素、測定データ、トレース、UI要素、およびどのAPIを呼び出すことができるかを管理するのに役立ちます。

RBACは、SUSE Observabilityリソースのきめ細かなアクセス管理、ユーザ権限のクリーンで簡単な監査方法、およびアクセス権に関する特定された問題の修正方法を提供する認証システムです。

== RBACで何ができるのか？

RBACでできることの例を挙げよう：

* あるユーザが開発クラスタのみにアクセスできるようにし、別のユーザが本番クラスタと開発クラスタの両方にアクセスできるようにし、3人目が開発クラスタと本番クラスタの1つのネームスペースのみにアクセスできるようにする。
* 少人数のユーザに管理者ロールを与えて、SUSE Observabilityを設定および構成します。すべての開発者に、トポロジー、メトリクス、トレース、ログ、イベントをすべて閲覧できるトラブルシューターとしての役割を与える一方で、コンフィギュレーション機能は制限されている。

== SUSE Observabilityの役割とは？

SUSE Observabilityのロールは、設定されたサブジェクトとxref:/setup/security/rbac/rbac_permissions.adoc[権限]セットの組み合わせです。SUSE Observabilityでロールを設定する手順については、xref:/setup/security/rbac/rbac_roles.adoc[ロールの設定方法を]参照してください。

== RBACロールのソース

ロールはいくつかの方法で定義できます。 すべて同じxref:/setup/security/rbac/rbac_permissions.adoc[パーミッションを使って]いる。

* **設定**- SUSE Observabilityのxref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[ヘルム値で]
* **ダイナミック**-xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[ `sts` CLIを使用]
* **Kubernetes からマッピング**-xref:/setup/security/rbac/rbac_rancher.adoc[Kubernetes`Roles` をマッピングする]。xref:/setup/security/rbac/rbac_rancher.adoc[ `RoleBindings`]

== RBAC設定の詳細

* xref:/setup/security/rbac/rbac_permissions.adoc[アクセス許可]
* xref:/setup/security/rbac/rbac_roles.adoc[役割の設定方法]
* xref:/setup/security/rbac/rbac_rancher.adoc[ランチャーとの併用]
* xref:/setup/security/rbac/rbac_scopes.adoc[スコープ]
* xref:/setup/security/authentication/README.adoc[認証の設定方法]
