include::partial$variables.adoc[]
= 使用自定义证书颁发机构
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 配置 PolicyServer 以使用自定义证书颁发机构或与指定注册表结合使用的不安全来源。
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "policy-servers", "custom-certificate-authorities"]
:doc-type: ["howto"]
:keywords: ["{project-name}"、"kubewarden"、"kubernetes"、"自定义证书颁发机构"]
:sidebar_label: 使用自定义 CA
:current-version: {page-origin-branch}

== 政策注册机构的自定义证书颁发机构

可以指定和配置 PolicyServer 从策略注册表中提取 ClusterAdmissionPolicy 工具时使用的证书颁发机构。以下`+spec+` 字段会对已部署的`+policy-server+` 可执行文件进行相应配置。

=== 来源不安全

[IMPORTANT]
====

`+kwctl+` 和`+policy-server+` 的默认行为是使用与系统 CA 存储匹配的受信任证书执行 HTTPS。您可以使用`+insecure_sources+` 设置，使用不受信任的证书甚至不使用 TLS 与注册表进行交互。在更接近生产的环境中，*不建议*采用这种方法。

====

要配置 PolicyServer 以接受指向特定注册表的不安全连接，请使用 PolicyServer 的`+spec.insecureSources+` 字段。该字段接受不安全 URI 列表。例如

[subs="+attributes",yaml]
----
spec:
  insecureSources:
    - localhost:5000
    - host.k3d.internal:5000
----

有关`+policy-server+` 可执行文件如何处理不安全 URI 的更多信息，请参阅xref:howtos/custom-certificate-authorities.adoc[自定义证书授权]。

=== 自定义证书颁发机构

您可以为特定 URI 配置由 1 个或多个证书组成的自定义证书链。为此，您可以使用字段`+spec.sourceAuthorities+` 。

该字段是 URI 的映射，每个 URI 都有自己的字符串列表，其中包含隐私增强邮件 (PEM) 编码证书。例如

[subs="+attributes",yaml]
----
spec:
  sourceAuthorities:
    "registry-pre.example.com":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-1 PEM cert
        -----END CERTIFICATE-----
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-2 PEM cert
        -----END CERTIFICATE-----
    "registry-pre2.example.com:5500":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre2 PEM cert
        -----END CERTIFICATE-----
----

有关`+policy-server+` 可执行文件如何处理xref:howtos/custom-certificate-authorities.adoc[自定义证书颁发机构]的更多信息，请参阅xref:howtos/custom-certificate-authorities.adoc[自定义证书颁发机构]。
