= Componentes de arquitetura
:revdate: 2025-09-08
:page-revdate: {revdate}

Os componentes necessários para fornecer os xref:rancher-os-management/architecture/services/architecture-services.adoc[serviços do{elemental-product-name} ] são:

* a <<_elemental_command_line_tool,`elemental`>> ferramenta de linha de comando
* o <<_elemental_operator_daemon,`elemental-operator`>> daemon
* a <<_elemental_register_command_line_tool,`elemental-register`>> ferramenta de linha de comando
* o <<_elemental_system_agent_daemon,`elemental-system-agent`>> daemon
* uma ou mais <<_suse_rancher_prime_os_manager_os_container_image,imagens de contêiner do sistema operacional{elemental-product-name} >>

== `elemental` ferramenta de linha de comando

A ferramenta `elemental` faz parte do link:{elemental_toolkit_url}[{elemental_toolkit_name}] projeto.
Ele realiza as operações reais de instalação e atualização do sistema operacional no host e é usado para executar as diretivas xref:references/cloud-config-reference.adoc[de configuração de nuvem] adicionadas nos xref:rancher-os-management/architecture/custom-resources.adoc[CRDs do site{elemental-product-name} ].

O binário `elemental` está incluído em todas as imagens do sistema operacional básico distribuídas com {elemental-product-name}.

== `elemental-operator` daemon

O daemon *elemental-operator* executa duas tarefas principais:

. incorpora os controladores do Kubernetes do {elemental-product-name} para gerenciar todos os xref:rancher-os-management/architecture/custom-resources.adoc[CRDs do{elemental-product-name} ]
. expõe os _pontos de extremidade de registro_ para permitir que o host se registre e faça download da configuração de instalação do sistema operacional durante a xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[integração da máquina]

O daemon `elemental-operator` é implantado no cluster do Rancher como um `Deployment` por meio do xref:references/operatorchart-reference.adoc[{elemental-product-name} Operator Helm Chart].

== `elemental-register` ferramenta de linha de comando

O binário *elemental-register* é o cliente usado para registrar o host nos _pontos de extremidade de registro_ expostos pelo <<_elemental_operator_daemon,elemental-operator>>. Ele coleta e encaminha os dados do host para permitir que o <<_elemental_operator_daemon,operador elementar>> preencha o SMBIOS e os modelos de etiqueta de hardware.

Se a fase de registro for realizada com êxito, o *elemental-register* obtém a configuração completa armazenada no xref:references/machineregistration-reference.adoc[MachineRegistration] do *elemental-operator*.
Como última etapa, o cliente *elemental-register* chama o binário <<_elemental_command_line_tool,elementar>> passando a configuração recuperada para iniciar a instalação do sistema operacional.

== `elemental-system-agent` daemon

O `elemental-system-agent` foi criado a partir do https://github.com/rancher/system-agent[projeto] Rancher e permite que o {elemental-product-name} implemente _planos_ para auxiliar no provisionamento do host.
Notavelmente, a instalação e a configuração do `rancher-system-agent` necessárias para o xref:rancher-os-management/architecture/services/architecture-clusterdeployment.adoc[serviço de provisionamento do Kubernetes Cluster] são realizadas por meio de um _plano_ `elemental-system-agent`.

== {elemental-product-name} Imagem do contêiner do sistema operacional

Uma link:{elemental_toolkit_url}[{elemental_toolkit_name}] A imagem do sistema operacional é uma imagem de contêiner da OCI que contém todos os arquivos que compõem o sistema operacional do host de destino. Ele contém não apenas todos os binários e bibliotecas, mas também o kernel e os arquivos de inicialização exigidos por um sistema Linux.

A imagem do sistema operacional {elemental-product-name} é uma imagem de sistema operacional link:{elemental_toolkit_url}[{elemental_toolkit_name}] baseada no https://www.suse.com/products/micro/[Micro] SLE e contém configurações e binários específicos do {elemental-product-name} (o <<_elemental_command_line_tool,elementar>> e o <<_elemental_register_command_line_tool,de registro elementar>> ).

As imagens do sistema operacional {elemental-product-name} são rastreadas nos recursos xref:references/managedosversion-reference.adoc[ManagedOSVersions]. Os recursos xref:references/managedosversion-reference.adoc[ManagedOSVersions] são criados dinamicamente a partir dos recursos xref:references/managedosversionchannel-reference.adoc[ManagedOSVersionChannel]. Um recurso padrão do `ManagedOSVersionChannel` é implementado com cada instalação do {elemental-product-name} Operator.
