= モニター
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 概要

このセクションでは、SUSE Observabilityで提供されるすぐに使えるモニタについて説明します。製品に同梱されるモニターは随時追加される。メインメニューの「モニター」セクションをご覧ください。

== すぐに使えるKubernetesモニター

=== 利用可能なサービス・エンドポイント

サービスが利用可能で、利用者がアクセスしやすいようにすることが重要です。これを監視するために、SUSE Observabilityは、サービスに少なくとも1つのエンドポイントが利用可能かどうかを確認するチェックを設定しました。エンドポイントは、分散システムの異なるコンポーネント間の通信を可能にするネットワークアドレスであり、サービスが適切に機能するためには利用可能である必要がある。
過去10分以内に利用可能なエンドポイントがゼロになった場合、モニターは乖離したままとなり、対処が必要なサービスに問題がある可能性を示す。
xref:/use/alerting/k8s-override-monitor-arguments.adoc[オーバーライド・モニターの引数を]許可する

=== リソースクォータ

ユーザーはネームスペースにリソース（ポッド、サービスなど）を作成し、クォータシステムが使用量を追跡して、ResourceQuotaで定義されたCpuのハードリソース制限を超えないようにする。モニターは、ネームスペースのCpu制限の合計がクォータによって確立された90％以上になると警告を発します。名前空間内の各`+resourcequota+` は、モニターの健康状態を生成する。

=== リソースクォータ

ユーザーはネームスペースにリソース（ポッド、サービスなど）を作成し、クォータシステムが使用量を追跡して、ResourceQuotaで定義されたCpuのハードリソースリクエストを超えないようにする。ネームスペースのCpu要求の合計がクォータで設定された値の90%以上になると、モニターは警告を発します。名前空間内の各`+resourcequota+` は、モニターの健康状態を生成する。

=== デーモンセット希望のレプリカ

デーモンセットに必要なレプリカの数が満たされていることが重要である。デーモンセットは、クラスタ内のすべてのノードまたはサブセットのノードで実行する必要があるポッドのセットを管理するために使用され、指定された条件を満たす各ノードでポッドのコピーが実行されるようにします。これは、ロギングやモニタリングなど、クラスタ内のすべてのノードで実行する必要があるクラスタレベルのタスクに便利です。

これを監視するために、SUSE Observabilityは、利用可能なレプリカが目的のレプリカ数と一致するかどうかを検証するチェックを設定しました。このチェックは、希望するレプリカ数がゼロを超えるデーモンセットにのみ適用されます。

* 利用可能なレプリカの数が希望する数より少ない場合、モニターは、StatefulSetに問題がある可能性があることを示すDEVIATING健全性状態を通知する。
* 利用可能なレプリカの数がゼロの場合、モニターはCRITICALヘルス状態を通知し、StatefulSetがまったく機能していないことを示す。

モニターの完全な定義を理解するには、詳細を確認してほしい。

=== ディスクスペースの乖離

KubernetesクラスタのPersistent Volume Claim（PVC）の使用状況を長期的に監視することが重要です。PVCは、コンテナのライフタイムを超えて持続する必要があるデータを保存するために使用され、データを保存するのに十分な容量を確保することが極めて重要です。
これを追跡するために、線形予測を使用して4日間のKubernetesボリューム使用量の傾向を予測するチェックを設定しました。この時間内にPVCが容量不足になることがトレンドで示された場合、通知を受け取ることができ、データ損失やダウンタイムを防ぐための措置を取ることができます。

=== ディスク容量が重要

KubernetesクラスタのPersistent Volume Claim（PVC）の使用状況を監視することが重要です。PVCは、コンテナのライフタイムを超えて持続する必要があるデータを保存するために使用され、データを保存するのに十分な容量を確保することが極めて重要です。これを追跡するために、線形予測を使用して12時間にわたるKubernetesのボリューム使用量の傾向を予測するチェックを設定しました。この時間内にPVCが容量不足になることがトレンドで示された場合、通知を受け取ることができ、データ損失やダウンタイムを防ぐための措置を取ることができます。

=== 希望するレプリカの配置

デプロイメントに必要なレプリカ数が満たされていることが重要です。デプロイは、Kubernetesクラスタ内の同一のPodのセットのデプロイとスケーリングを管理するために使用される。必要な数のレプリカが稼働し、利用可能であることを保証することで、DeploymentsはKubernetesアプリケーションやサービスの可用性と信頼性を維持するのに役立ちます。これを監視するために、SUSE Observabilityは、利用可能なレプリカが目的のレプリカ数と一致するかどうかを検証するチェックを設定しました。

このチェックは、希望するレプリカ数が0を超えるデプロイメントにのみ適用されます。

* 利用可能なレプリカの数が希望する数より少ない場合、モニターはDEVIATING健全性状態を通知し、デプロイメントに問題がある可能性を示します。
* 利用可能なレプリカの数がゼロの場合、モニターはCRITICALヘルス状態を通知し、StatefulSetがまったく機能していないことを示す。

モニターの完全な定義を理解するには、詳細を確認してほしい。

=== HTTP - 5xx エラーの割合

ステータスコードが5xxのHTTPレスポンスは、設定ミス、過負荷、サーバー内部のエラーなど、サーバー側のエラーを示します。
良好なユーザーエクスペリエンスを確保するためには、5xxレスポンスの割合は、KubernetesサービスのHTTPレスポンス全体の5%未満であるべきです。

正確な閾値と重大度はアプリケーションに依存する可能性があるため、サービス上のxref:/use/alerting/k8s-override-monitor-arguments.adoc[Kubernetesアノテーションを介して]閾値をxref:/use/alerting/k8s-override-monitor-arguments.adoc[オーバーライドする]ことができる。例えば、事前に設定された乖離しきい値をオーバーライドし、代わりに6%の臨界しきい値のみを設定するには、サービスにこの注釈を付けてください：
```
monitor.kubernetes-v2.stackstate.io/http-error-ratio-for-service: | 
  { 
    "criticalThreshold": 0.06,
    "deviatingThreshold": null
  }
```

このjsonスニペットから逸脱しきい値を省略すれば、設定された5％のままとなり、クリティカルしきい値が6％であれば、モニターは5％から6％のエラー比率でのみ逸脱状態となることを意味する。

=== HTTP - レスポンスタイム - Q95 が3秒以上

Kubernetesサービスの95パーセンタイル（Q95）HTTPレスポンスタイムを追跡することで、ユーザーに影響を与える可能性のある遅いリクエストやパフォーマンスの異常値を発見することができます。Q95の応答時間が指定時間内に3秒を超えると、モニターは逸脱状態で警告を発します。

サービス上のKubernetesアノテーションを使用して、時間ウィンドウ、しきい値、分位値などのxref:/use/alerting/k8s-override-monitor-arguments.adoc[デフォルト設定をオーバーライドする]ことで、アプリケーションのニーズに合わせてこのモニターを調整することができます。この柔軟性は、サービスに独自のパフォーマンス要件がある場合に便利です。例えば、ロング・ポーリング・サービス。

モニターをカスタマイズするには、以下のような注釈をサービスに追加し、必要に応じて値を調整する：

```
monitor.kubernetes-v2.stackstate.io/http-response-time/overrides: |
  {
    "deviatingTimeWindow": "10m",            // Time window for a deviating state (e.g., "10m", "1h")
    "deviatingThreshold": 1.2,               // Threshold in seconds for a deviating state
    "criticalTimeWindow": "30m",             // Time window for a critical state
    "criticalThreshold": 2.0,                // Threshold in seconds for a critical state
    "quantile": 0.99,                        // Quantile to monitor (e.g., 0.95, 0.99)
    "nameTemplate": "API latency (p{{ quantile }}) > {{ threshold }}", // Custom monitor name
    "enabled": true                          // Set to false to disable this monitor for the service
  }
```

- どのフィールドもデフォルト値を使用するために省略することができます。
- モニターは、指定されたウィンドウにわたって、選択された応答時間の分位値を評価する。値がしきい値を超えていれば、モニターはトリガーする。
- 上記の例では、99パーセンタイル（Q99）の応答時間が1.2秒以上（過去10分間）であれば、モニターは逸脱状態を通知し、2.0秒以上（過去30分間）であれば、クリティカル状態を通知する。

=== 12時間におけるKubernetesの使用量推移

KubernetesクラスタのPersistent Volume Claim（PVC）の使用状況を監視することが重要です。PVCは、コンテナのライフタイムを超えて持続する必要があるデータを保存するために使用され、データを保存するのに十分な容量を確保することが極めて重要です。これを追跡するために、SUSE Observabilityは、線形予測を使用して12時間のKubernetesボリューム使用量の傾向を予測するチェックを設定しました。この時間内にPVCが容量不足になることがトレンドで示された場合、通知を受け取ることができ、データ損失やダウンタイムを防ぐための措置を取ることができます。

=== 4日間のKubernetes使用量推移

KubernetesクラスタのPersistent Volume Claim（PVC）の使用状況を長期的に監視することが重要です。PVCは、コンテナのライフタイムを超えて持続する必要があるデータを保存するために使用され、データを保存するのに十分な容量を確保することが極めて重要です。
これを追跡するために、SUSE Observabilityは線形予測を使用して4日間のKubernetesボリューム使用量の傾向を予測するチェックを設定しました。この時間内にPVCが容量不足になることがトレンドで示された場合、通知を受け取ることができ、データ損失やダウンタイムを防ぐための措置を取ることができます。

=== メモリ制限 resourcequota

ユーザーはネームスペースにリソース（ポッド、サービスなど）を作成し、クォータシステムが使用量を追跡して、ResourceQuotaで定義されたメモリのハードリソース制限を超えないようにします。モニターは、ネームスペースの合計メモリ制限がクォータによって確立された90%以上になると警告を発します。名前空間内の各`+resourcequota+` は、モニターの健康状態を生成する。

=== メモリ要求数 resourcequota

ユーザーはネームスペースにリソース（ポッド、サービスなど）を作成し、クォータシステムが使用量を追跡して、ResourceQuotaで定義されたメモリのハードリソースリクエストを超えないようにする。ネームスペースの総メモリ要求がクォータで設定された値の90%以上になると、モニターは警告を発します。名前空間内の各`+resourcequota+` は、モニターの健康状態を生成する。

=== ノードディスク圧力

ノードディスクの圧力とは、ノードに接続されたディスクが過度のひずみを受ける状況を指す。Kubernetesには予防策が組み込まれているため、ノードのディスクが圧迫されることはまずないが、それでも散発的に発生する可能性はある。ノードディスク圧が生じる主な理由は2つある。最初の理由は、Kubernetesが未使用イメージのクリーンアップに失敗することだ。通常、Kubernetesは定期的に使用されていないイメージをチェックし、削除します。従って、これは結節ディスク圧のまれな原因であるが、認識されるべきである。より可能性の高い問題は、ログの蓄積である。Kubernetesでは通常、コンテナが実行されているときと、直近に終了したコンテナのログがトラブルシューティングのために保持されているときの2つのシナリオでログが保存される。このアプローチは、重要なログを保存することと、時間の経過とともに不要なログを破棄することのバランスをとることを目的としている。しかし、長時間稼動するコンテナで大量のログが生成されると、ノードディスクの容量をオーバーするほど蓄積される可能性がある。モニターの完全な定義を理解するには、詳細を確認してほしい。
xref:/use/alerting/k8s-override-monitor-arguments.adoc[オーバーライド・モニターの引数を]許可する

=== ノードメモリー圧力

ノードのメモリ圧迫とは、Kubernetesノードのメモリリソースが過度に圧迫されている状況を指す。Kubernetesの組み込みリソース管理メカニズムにより、ノードのメモリ圧迫に遭遇することはまれだが、それでも特定の状況下では発生する可能性がある。ノードメモリープレッシャーが発生する主な理由は2つある。1つ目の理由は、ノード上で実行されているコンテナに対するリソースの要求と制限が誤って設定されているか、不十分であることに関連している。Kubernetesは、リソースの割り当てと管理を効率的に行うために、リソースの要求と制限に依存している。コンテナのメモリ要件が正確に設定されていない場合、コンテナは予想以上にメモリを消費し、ノードのメモリを圧迫する可能性がある。2つ目の理由は、メモリを大量に消費するアプリケーションやプロセスが存在することである。特定のワークロードやアプリケーションではメモリ需要が高く、ノードのメモリ使用率が高くなることがあります。大量のメモリを必要とする複数のポッドやコンテナが、適切なリソース割り当てなしに同じノードにスケジューリングされると、メモリが圧迫される可能性があります。ノードのメモリ圧迫を緩和するには、コンテナに対するリソース要求と制限を見直し、調整することが極めて重要であり、アプリケーションの実際のメモリニーズと一致するようにする必要がある。アプリケーション自体のメモリ使用量を監視し、最適化することも、メモリ消費量の削減に役立つ。さらに、メモリの使用率に基づいてポッド数を動的にスケールする水平ポッド・オートスケーリングを検討する。定期的なモニタリング、メモリ関連メトリクスの分析、メモリリソースのプロアクティブな割り当てを行うことで、Kubernetesノードの健全なメモリ状態を維持することができます。ワークロードの具体的な要件を理解し、それに応じてリソースの割り当てを調整することで、メモリの圧迫を防ぎ、最適なパフォーマンスを確保することが不可欠です。
xref:/use/alerting/k8s-override-monitor-arguments.adoc[オーバーライド・モニターの引数を]許可する

=== ノード PID 圧力

ノードのPIDプレッシャーは、Kubernetesノードで利用可能なプロセス識別（PID）リソースが過度に緊張した場合に発生します。1つ目の理由は、ノード上で実行されているコンテナに対するリソースの要求と制限が誤って設定されているか、不十分であることに関連している。Kubernetesは、リソースを効果的に割り当てて管理するために、正確なリソース要求と制限に依存している。コンテナのPID要件が正しく設定されていない場合、予想以上にPIDが消費され、ノードのPIDが圧迫される可能性がある。第二の理由は、PIDを多用するアプリケーションやプロセスの存在である。ワークロードやアプリケーションによっては、プロセス識別に対する要求が高く、ノードのPID使用率が上昇する。大きなPIDを必要とする複数のポッドやコンテナが、適切なリソース割り当てなしに同じノードにスケジューリングされると、PIDプレッシャーが発生する可能性があります。ノードのPIDプレッシャーに対処するには、コンテナのリソース要求と制限を見直し、アプリケーションの実際のPIDニーズと一致するように調整することが重要です。アプリケーション自体でPIDの使用状況を監視し、最適化することも、PIDの消費を抑えるのに役立つ。さらに、水平ポッドのオートスケーリングを考慮することで、PID利用率に基づいてポッド数を動的にスケーリングできる。定期的なモニタリング、PID関連メトリクスの分析、およびPIDリソースのプロアクティブな割り当ては、KubernetesノードにおけるPIDの使用状況を健全な状態に維持するために非常に重要です。PIDプレッシャーを防ぎ、最適なパフォーマンスを確保するためには、ワークロードの具体的な要件を理解し、それに応じてリソースの割り当てを調整することが不可欠です。
xref:/use/alerting/k8s-override-monitor-arguments.adoc[オーバーライド・モニターの引数を]許可する

=== ノードの準備

ノードが期待通りに稼働しているか確認します。
xref:/use/alerting/k8s-override-monitor-arguments.adoc[オーバーライド・モニターの引数を]許可する

=== 孤児化した永続ボリューム

永続ボリュームが孤児になっていないことを確認する。孤児化された永続ボリュームとは、永続ボリューム請求に関連付けられていない永続ボリュームのことです。使用されていない機密データが含まれている可能性があるためです。オーファン化した永続ボリュームも、使用されていないため、リソースの無駄遣いになる可能性があります。
xref:/use/alerting/k8s-override-monitor-arguments.adoc[オーバーライド・モニターの引数を]許可するが、`+enabled+` プロパティのみ。

=== コンテナのメモリ不足

Kubernetesクラスターで稼働しているコンテナが適切に機能するのに十分なメモリを確保しておくことが重要だ。OOM（Out-of-Memory）状態は、コンテナのクラッシュや応答不能を引き起こし、再起動や潜在的なデータ損失につながる可能性があります。
このような状態を監視するために、SUSE Observabilityは、クラスタで実行されているコンテナのOOMイベントを検出して報告するチェックを設定しました。このチェックにより、メモリ不足に陥っているコンテナを特定し、問題が発生する前に対策を講じることができる。
xref:/use/alerting/k8s-override-monitor-arguments.adoc[オーバーライド・モニターの引数を]許可する

=== ポッド・レディ状態

スケジューリングされたPodが実行され、予定された時間内にトラフィックを受け取る準備ができているかどうかをチェックする。

=== ポッドスパンの持続時間

サーバーと消費者のスパンを監視する。継続時間の95パーセンタイルがしきい値（デフォルト5000ms）より大きい場合、モニターはDeviating状態になる。このモニターは、xref:/use/alerting/k8s-override-monitor-arguments.adoc[モニター引数のオーバーライドによる]設定のオーバーライドをサポートしている。

=== ポッド・スパン・エラー・レシオ

サーバーとコンシューマーのスパンのうち、エラーステータスを持つスパンの割合を監視する。エラースパンのパーセンテージがしきい値（デフォルト5）を超えた場合、モニターはDeviating状態になる。このモニターは、xref:/use/alerting/k8s-override-monitor-arguments.adoc[モニター引数のオーバーライドによる]設定のオーバーライドをサポートしている。

=== 待機状態のポッド

ポッドが待機状態にあり、CreateContainerConfigError、CreateContainerError、CrashLoopBackOff、または ImagePullBackOff の理由が含まれている場合、逸脱していると見なされます。

=== 希望するレプリカセット

ReplicaSet（およびDeployment）に必要なレプリカ数が満たされていることを確認することが重要です。ReplicaSetsとDeploymentsは、Kubernetesクラスタ内の特定のPodのレプリカ数を管理するために使用される。

これを監視するために、SUSE Observabilityは、利用可能なレプリカが目的のレプリカ数と一致するかどうかを検証するチェックを設定しました。このチェックは、希望するレプリカ数が0を超えるReplicaSetsとDeploymentにのみ適用されます。

* 利用可能なレプリカの数が希望する数より少ない場合、モニタはDEVIATINGヘルス状態を通知し、ReplicaSetまたはDeploymentに問題がある可能性を示します。
* 利用可能なレプリカの数がゼロの場合、モニタはCRITICAL健全性状態を通知し、ReplicaSetまたはDeploymentがまったく機能していないことを示します。

さらに、ReplicaSetの健全性の状態は、より包括的な監視のためにDeploymentに伝搬されます。

=== コンテナの再起動

Kubernetesクラスタ内の各コンテナの再起動を監視することは重要である。コンテナは、アプリケーションやインフラの問題など、さまざまな理由で再起動する可能性がある。
アプリケーションがスムーズに実行されていることを確認するために、SUSE Observabilityは、10分間のコンテナ再起動の回数を追跡するモニターを設定しました。この期間中に3回以上の再起動があった場合、コンテナの健全性状態は「DEVIATING」に設定され、調査が必要な問題がある可能性があることを示す。

=== サービス利用可能なエンドポイント

サービスが利用可能で、利用者がアクセスしやすいようにすることが重要です。これを監視するために、サービスに少なくとも1つのエンドポイントが利用可能かどうかを確認するチェックを設定しました。エンドポイントは、分散システムの異なるコンポーネント間の通信を可能にするネットワークアドレスであり、サービスが適切に機能するためには利用可能である必要がある。
過去10分以内に利用可能なエンドポイントがゼロになった場合、モニターは逸脱状態のままとなり、対処が必要な問題がサービスに存在する可能性があることを示す。
モニターの完全な定義を理解するには、詳細を確認してほしい。

=== サービス期間

サーバーと消費者のスパンを監視する。継続時間の95パーセンタイルがしきい値（デフォルト5000ms）より大きい場合、モニターはDeviating状態になる。このモニターは、xref:/use/alerting/k8s-override-monitor-arguments.adoc[モニター引数のオーバーライドによる]設定のオーバーライドをサポートしている。

=== サービススパン誤差率

Kubernetesサービスのエラー状態にあるサーバとコンシューマのスパンの割合。このモニターは、xref:/use/alerting/k8s-override-monitor-arguments.adoc[モニター引数のオーバーライドによる]設定のオーバーライドをサポートしている。

=== ステートフルセット希望のレプリカ

StatefulSetに必要なレプリカの数が満たされていることが重要である。StatefulSetsはステートフルなアプリケーションを管理するために使用され、正しく機能するためには特定の数のレプリカが必要です。

これを監視するために、SUSE Observabilityは、利用可能なレプリカが目的のレプリカ数と一致するかどうかを検証するチェックを設定しました。このチェックは、希望するレプリカ数が0を超えるStatefulSetにのみ適用されます。

* 利用可能なレプリカの数が希望する数より少ない場合、モニターは、StatefulSetに問題がある可能性があることを示すDEVIATING健全性状態を通知する。
* 利用可能なレプリカの数がゼロの場合、モニターはCRITICALヘルス状態を通知し、StatefulSetがまったく機能していないことを示す。

=== 不可算ノード

Kubernetesで "NodeNotSchedulable "イベントに遭遇した場合、それはKubernetesスケジューラが、ノードの何らかの制約や問題のために、特定のノードにPodを配置できなかったことを意味する。このイベントは、スケジューラがリソース要件やその他の制約に従ってポッドを実行する適切なノードを見つけられないときに発生する。

=== クラスタの集約された健康状態

クラスターには健康そのものがない。しかし、クラスタはいくつかのコンポーネントから構成されており、そのうちのいくつかは通常の運用に不可欠である。モニターはこれらのコンポーネントの状態を集約する：

* kube-system」ネームスペース内のすべてのポッド
* 全ノードの健康状態を調べ、最も重要な健康状態を取る。

=== 派生ワークロードの健全性状態（Deployment、DaemonSet、ReplicaSet、StatefulSet）

モニターは、すべての最上位の依存関係の状態を集約し、次に（例えばメトリクスからの）直接的な観察に基づいて、最もクリティカルな健全性の状態を返す。
このアプローチは、健全性シグナルが（Podのような）低レベルの技術コンポーネントから高レベルの論理コンポーネントに伝搬することを保証するが、コンポーネント自体が観測された健全性ステートを欠いている場合に限られる。
このモニターを効果的に使用するには、以下のヘルスチェックの一部または全部が無効になっていることを確認してください：

* 希望するレプリカの配置
* Daemon希望のレプリカを設定
* レプリカセット
* StatefulSet希望のレプリカ

論理コンポーネントに直接のモニタがないユースケースの場合、xref:/use/alerting/k8s-derived-state-monitors.adoc[Derived State Monitor]機能を使用して、依存する技術コンポーネントに基づいて健全性を推測することができます。

== 参照

* xref:/use/alerting/k8s-monitors.adoc[モニター]
