include::partial$variables.adoc[]
= Verwendung benutzerdefinierter Zertifizierungsstellen
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Konfigurieren Sie den PolicyServer so, dass er entweder benutzerdefinierte Zertifizierungsstellen oder unsichere Quellen in Verbindung mit bestimmten Registern verwendet.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "policy-servers", "custom-certificate-authorities"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "benutzerdefinierte Zertifizierungsstellen"]
:sidebar_label: Benutzerdefinierte CAs verwenden
:current-version: {page-origin-branch}

== Benutzerdefinierte Zertifizierungsstellen für Richtlinienregistrierungen

Es ist möglich, die Zertifizierungsstellen anzugeben und zu konfigurieren, die ein PolicyServer beim Abrufen der ClusterAdmissionPolicy-Artefakte aus der Richtlinienregistrierung verwendet. Die folgenden `spec` Felder konfigurieren die bereitgestellte ausführbare Datei`policy-server` zu diesem Zweck.

=== Unsichere Quellen

[IMPORTANT]
====

Das Standardverhalten von `kwctl` und `policy-server` besteht darin, HTTPS mit vertrauenswürdigen Zertifikaten zu erzwingen, die mit dem System-CA-Speicher übereinstimmen. Sie können mit Registern mit nicht vertrauenswürdigen Zertifikaten oder sogar ohne TLS interagieren, indem Sie die Einstellung`insecure_sources` verwenden. Für produktionsnahe Umgebungen *wird von* diesem Ansatz *dringend abgeraten*.

====

Um den PolicyServer so zu konfigurieren, dass er unsichere Verbindungen zu bestimmten Registern akzeptiert, verwenden Sie das Feld `spec.insecureSources` von PolicyServer. Dieses Feld akzeptiert eine Liste von unsicheren URIs. Zum Beispiel:

[subs="+attributes",yaml]
----
spec:
  insecureSources:
    - localhost:5000
    - host.k3d.internal:5000
----

Weitere Informationen darüber, wie die ausführbare Datei `policy-server` mit unsicheren URIs umgeht, finden Sie unter xref:howtos/custom-certificate-authorities.adoc[Benutzerdefinierte Zertifizierungsstelle].

=== Benutzerdefinierte Zertifizierungsstellen

Sie können den PolicyServer mit einer benutzerdefinierten Zertifikatskette aus 1 oder mehreren Zertifikaten für einen bestimmten URI konfigurieren. Dazu verwenden Sie das Feld`spec.sourceAuthorities`.

Bei diesem Feld handelt es sich um eine Zuordnung von URIs, die jeweils eine eigene Liste von Strings enthalten, die mit Privacy Enhanced Mail (PEM) kodierte Zertifikate enthalten. Zum Beispiel:

[subs="+attributes",yaml]
----
spec:
  sourceAuthorities:
    "registry-pre.example.com":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-1 PEM cert
        -----END CERTIFICATE-----
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-2 PEM cert
        -----END CERTIFICATE-----
    "registry-pre2.example.com:5500":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre2 PEM cert
        -----END CERTIFICATE-----
----

Weitere Informationen darüber, wie die ausführbare Datei `policy-server` diese behandelt, finden Sie unter xref:howtos/custom-certificate-authorities.adoc[Benutzerdefinierte Zertifizierungsstellen].
