= 嵌入式注册表镜像
:page-languages: [EN, JA, KO, ZH]
:revdate: 2026-01-05
:page-revdate: {revdate}

[IMPORTANT]
.版本闸门
====
嵌入式注册表镜像在 2024 年 1 月发布的以下版本中作为实验功能提供：v1.26.13+k3s1、v1.27.10+k3s1、v1.28.6+k3s1、v1.29.1+k3s1；在 2024 年 12 月发布的以下版本中作为 GA 提供：v1.29.12+k3s1、v1.30.8+k3s1、v1.31.4+k3s1。
====

K3s 嵌入了https://github.com/XenitAB/spegel[Spegel]，这是一个无状态分布式 OCI 注册镜像，允许 Kubernetes 集群中节点之间点对点共享容器镜像。分布式注册表镜像默认为禁用。如以下各小节所述，K3s 必须同时启用xref:#_enabling_the_distributed_oci_registry_mirror[分布式 OCI 注册表镜像]和xref:#_enabling_registry_mirroring[注册表镜像]才能利用它。

[#_enabling_the_distributed_oci_registry_mirror]
== 启用分布式 OCI 注册镜像

要启用嵌入式注册表镜像，服务器节点必须使用`+--embedded-registry+` 标志或配置文件中的`+embedded-registry: true+` 启动。
此选项可启用嵌入式镜像，供群集中的所有节点使用。

在集群级别启用后，所有节点都将在 6443 端口上托管本地 OCI 注册表，并通过对等网络在 5001 端口上发布可用映像列表。
其他群集成员无需访问外部注册表，就可以调用任何节点上 containerd 映像存储中的任何可用映像。
通过xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[air-gap 映像 tar 文件]导入的xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[映像]被固定在 containerd 中，以确保它们始终可用，不会被 Kubelet 垃圾收集程序剪枝。

可通过设置 K3s 服务的`+K3S_P2P_PORT+` 环境变量，将对等端口从 5001 改为对等端口。所有节点上的端口必须设置为相同的值。
不支持也不建议更改端口。

=== 要求

启用嵌入式注册表镜像后，所有节点必须能够通过其内部 IP 地址、TCP 端口 5001 和 6443 互相连接。
如果节点之间无法相互连接，可能需要更长的时间才能提取映像，因为 containerd 会首先尝试使用分布式注册表，然后再返回到其他端点。

[#_enabling_registry_mirroring]
== 启用注册表镜像

为注册表启用镜像功能后，节点既可以从其他节点调用该注册表的镜像，也可以与其他节点共享注册表的镜像。
如果某个注册表在某些节点上启用了镜像功能，而在其他节点上未启用，则只有启用了该注册表的节点才能交换该注册表中的映像。

要启用来自上游容器注册表的镜像，节点必须在`+registries.yaml+` 的`+mirrors+` 部分有该注册表的条目。
注册表无需列出任何端点，只需存在即可。
例如，要从`+docker.io+` 和`+registry.k8s.io+` 启用分布式镜像，请在所有群集节点上用以下内容配置`+registries.yaml+` ：

[,yaml]
----
mirrors:
  docker.io:
  registry.k8s.io:
----

也可以像往常一样添加注册表镜像的端点。
在以下配置中，图像提取尝试将首先尝试嵌入式镜像，然后是`+mirror.example.com+` ，最后是`+docker.io+` ：

[,yaml]
----
mirrors:
  docker.io:
    endpoint:
      - https://mirror.example.com
----

如果你是直接使用私有注册表，而不是将其作为上游注册表的镜像，你可以按照启用公共注册表的方式启用分布式镜像，即在镜像部分列出私有注册表：

[,yaml]
----
mirrors:
  mirror.example.com:
----

[IMPORTANT]
.版本闸门
====
通配符支持从 2024 年 3 月发布的以下版本开始提供：v1.26.15+k3s1、v1.27.12+k3s1、v1.28.8+k3s1、v1.29.3+k3s1
====


`+"*"+` 通配符镜像条目可用于启用所有注册表的分布式镜像。注意星号必须加引号：

[,yaml]
----
mirrors:
  "*":
----

如果节点上未启用镜像注册表，则该节点不会以任何身份参与分布式注册表。

有关`+registries.yaml+` 文件结构的更多信息，请参阅xref:installation/private-registry.adoc[专用注册表配置]。

=== 默认端点回退

默认情况下，当从配置了镜像端点的注册表中提取数据时，containerd 会退回到默认端点。如果要禁用此功能，只从配置的镜像和/或嵌入式镜像中提取图像，请参阅专用注册表配置文档中的xref:installation/private-registry.adoc#_default_endpoint_fallback[默认端点回退]部分。

请注意，如果您使用`+--disable-default-registry-endpoint+` 选项，并希望允许直接从特定注册表中提取，而不允许从其他注册表中提取，您可以明确提供一个端点，以允许图像提取返回注册表本身：

[,yaml]
----
mirrors:
  docker.io:           # no default endpoint, pulls will fail if not available on a node
  registry.k8s.io:     # no default endpoint, pulls will fail if not available on a node
  mirror.example.com:  # explicit default endpoint, can pull from upstream if not available on a node
    endpoint:
      - https://mirror.example.com
----

=== 最新标签

如果没有为容器图像指定标签，隐含的默认标签是`+latest+` 。该标签会经常更新，以指向图像的最新版本。由于该标签将根据调用时间指向图像的不同版本，因此分布式注册表*不会*从其他节点调用`+latest+` 标签。这样，containerd 就必须访问上游注册表或注册表镜像，以确保对`+latest+` 标记所指内容的一致看法。

这与 Kubernetes 在为容器映像使用`+latest+` 标签时观察到的https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting[特殊`+imagePullPolicy+` 默认值]一致。

可通过为 K3s 服务设置`+K3S_P2P_ENABLE_LATEST=true+` 环境变量来启用镜像`+latest+` 标签。
由于上述原因，这种做法是不支持的，也是不建议的。

== 安全

=== 认证

访问嵌入式镜像的注册表 API 需要由群集客户证书授权机构签署的有效客户证书。

访问分布式哈希表的点对点网络需要一个由服务器节点控制的预共享密钥。
节点使用预共享密钥和集群证书颁发机构签署的证书相互验证。

=== 潜在问题

[CAUTION]
====
分布式注册表基于点对点原则，并假定所有集群成员之间的权限和信任程度相同。
如果这与群集的安全状况不符，则不应启用嵌入式分布式注册表。
====


嵌入式注册表可提供节点可能无法访问的图像。
例如，如果你的一些映像是从注册表、项目或资源库中提取的，而这些注册表、项目或资源库需要通过 Kubernetes Image Pull Secrets 或`+registries.yaml+` 中的凭据进行身份验证，那么分布式注册表将允许其他节点共享这些映像，而无需向上游注册表提供任何凭据。

有权限将镜像推送到某个节点上的 containerd 镜像存储中的用户可能会利用这一点为其他集群节点 "毒化 "镜像，因为其他节点会信任该节点所宣传的标签，并在不向上游注册表检查的情况下使用它。
如果图像完整性很重要，则应使用图像摘要而不是标记，因为摘要不会以这种方式中毒。

== 共享空隙或手动加载的图像

根据源注册表控制图像共享。
通过xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[air-gap tar 包]直接加载到 containerd 的映像、xref:add-ons/import-images.adoc#_pre_import_images[预先导入的]映像或使用`+ctr+` 命令行工具直接加载到 containerd 的映像存储中的映像，如果被标记为来自启用了镜像功能的注册表，则可在节点之间共享。

请注意，图像看似来自上游注册表，但实际上并不一定存在或可以访问。
例如，你可以将图像标记为来自虚构的上游注册表，然后将这些图像导入 containerd 的图像存储区。
然后，只要注册表列在 `+registries.yaml+`

== 推送图片

嵌入式注册表是只读的，无法使用`+docker push+` 或其他与 OCI 注册表交互的常用工具直接推送。

可通过运行`+ctr -n k8s.io image pull+` 提取图像，或通过`+ctr -n k8s.io image import+` 命令xref:add-ons/import-images.adoc#_pre_import_images[或预导入功能]加载`+docker save+` 创建的图像存档，从而通过嵌入式注册表手动提供图像。
请注意，在通过`+ctr+` 管理图像时，必须指定`+k8s.io+` 命名空间，这样 kubelet 才能看到这些图像。
