= k3s secrets-encrypt
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

K3s permet d'activer le cryptage des secrets au repos. Pour plus d'informations, voir xref:security/secrets-encryption.adoc[Chiffrement des secrets.]

== Outil de cryptage des secrets

[IMPORTANT]
.Version Gate
====
Disponible à partir de https://github.com/k3s-io/k3s/releases/tag/v1.21.8%2Bk3s1[.21.8+k3s1] v1
====


K3s contient un outil CLI `secrets-encrypt`, qui permet de contrôler automatiquement les éléments suivants :

* Désactivation/activation du cryptage des secrets
* Ajout de nouvelles clés de chiffrement
* Rotation et suppression des clés de chiffrement
* Recryptage des secrets

[CAUTION]
====
Si la procédure de rotation des clés de chiffrement n'est pas respectée, votre cluster risque d'être définitivement corrompu. Procédez avec prudence.
====

[#_encryption_key_rotation]
=== Chiffrement Rotation des clés

[IMPORTANT]
.Version Gate
====
Disponible à partir des versions de septembre 2024 : v1.30.5+k3s1, v1.31.1+k3s1.
====

[tabs,sync-group-id=se]
======
Serveur unique::
+
--
Pour faire tourner les clés de chiffrement des secrets sur un cluster à serveur unique :

. Démarrer le serveur K3s avec le drapeau `--secrets-encryption`
+
[NOTE]
====
Démarrer K3s sans cryptage et l'activer ultérieurement n'est actuellement _pas_ possible.
====

. Rotation des clés de cryptage des secrets
+
----
k3s secrets-encrypt rotate-keys
----

. Attendez que le recryptage soit terminé. Observez les journaux du serveur ou attendez :
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
--

Haute disponibilité::
+
--
Pour faire tourner les clés de cryptage des secrets sur les configurations HA :

. Démarrez les trois serveurs K3s avec le drapeau `--secrets-encryption`. Par souci de concision, les serveurs seront désignés par S1, S2, S3.
+
[NOTE]
====
Démarrer K3s sans cryptage et l'activer ultérieurement n'est actuellement _pas_ possible.
====

. Rotation des clés de cryptage des secrets sur S1
+
[,bash]
----
k3s secrets-encrypt rotate-keys
----

. Attendez que le recryptage soit terminé. Observez les journaux du serveur ou attendez :
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
+
[NOTE]
====
Les K3 recryptent environ 5 secrets par seconde. Le recryptage des grappes contenant un grand nombre de secrets peut prendre plusieurs minutes. Vous pouvez suivre l'évolution de la situation dans les journaux du serveur.
====

. Redémarrer les K3 sur S1 avec les mêmes arguments. Si vous utilisez K3s en tant que service :
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Une fois que S1 est en place, recommencez les K3 sur S2 et S3.
--
======

=== Chiffrement de l'héritage Rotation des clés

[TIP]
.Nouvelle procédure
====
Si vous utilisez les versions v1.30+ de K3s, nous vous recommandons d'utiliser plutôt la xref:#_encryption_key_rotation[rotation de la clé de chiffrement].
====

[tabs,sync-group-id=se]
======
Serveur unique::
+
--
Pour faire tourner les clés de chiffrement des secrets sur un cluster à serveur unique :

. Démarrer le serveur K3s avec le drapeau `--secrets-encryption`
+
[NOTE]
====
Démarrer K3s sans cryptage et l'activer ultérieurement n'est actuellement _pas_ possible.
====

. Préparer
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Tuer et redémarrer le serveur K3s avec les mêmes arguments. Si vous utilisez K3s en tant que service :
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Rotation
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Tuer et redémarrer le serveur K3s avec les mêmes arguments
. Réencrypter
+
[NOTE]
====
Les K3 recryptent environ 5 secrets par seconde. +
Le recryptage des grappes contenant un grand nombre de secrets peut prendre plusieurs minutes.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----
--

Haute disponibilité::
+
--
Les étapes sont les mêmes pour les clusters DB intégrés et DB externes.

Pour faire tourner les clés de cryptage des secrets sur les configurations HA :

. Démarrez les trois serveurs K3s avec le drapeau `--secrets-encryption`. Par souci de concision, les serveurs seront désignés par S1, S2, S3.
+
[NOTE]
====
* Démarrer K3s sans cryptage et l'activer ultérieurement n'est actuellement _pas_ possible.
* Bien que cela ne soit pas obligatoire, il est recommandé de choisir un nœud de serveur à partir duquel exécuter les commandes `secrets-encrypt`.
====
. Préparer le S1
+
[,bash]
----
k3s secrets-encrypt prepare
----

. Tuer et redémarrer S1 avec les mêmes arguments. Si vous utilisez K3s en tant que service :
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Une fois que le S1 est en place, tuer et redémarrer le S2 et le S3.
. Rotation sur S1
+
[,bash]
----
k3s secrets-encrypt rotate
----

. Tuer et redémarrer S1 avec les mêmes arguments
. Une fois que le S1 est en place, tuer et redémarrer le S2 et le S3.
. Recryptage sur S1
+
[NOTE]
====
Les K3 recryptent environ 5 secrets par seconde. +
Le recryptage des grappes contenant un grand nombre de secrets peut prendre plusieurs minutes.
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----

. Tuer et redémarrer S1 avec les mêmes arguments
. Une fois que le S1 est en place, tuer et redémarrer le S2 et le S3.
--
======

=== Cryptage des secrets Désactiver/Réactiver

[tabs,sync-group-id=se]
======
Serveur unique::
+
--
Après avoir lancé un serveur avec l'option `--secrets-encryption`, le cryptage des secrets peut être désactivé.

Pour désactiver le cryptage des secrets sur un cluster à nœud unique :

. Désactiver
+
[,bash]
----
k3s secrets-encrypt disable
----

. Tuer et redémarrer le serveur K3s avec les mêmes arguments. Si vous utilisez K3s en tant que service :
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Recryptage avec drapeaux
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

Pour réactiver le cryptage des secrets sur un cluster à nœud unique :

. Activer
+
[,bash]
----
k3s secrets-encrypt enable
----

. Tuer et redémarrer le serveur K3s avec les mêmes arguments
. Recryptage avec drapeaux
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--

Haute disponibilité::
+
--
Après avoir lancé un cluster HA avec les drapeaux `--secrets-encryption`, le cryptage des secrets peut être désactivé.

[NOTE]
====
Bien que cela ne soit pas obligatoire, il est recommandé de choisir un nœud de serveur à partir duquel exécuter les commandes `secrets-encrypt`.
====

Par souci de concision, les trois serveurs utilisés dans ce guide seront appelés S1, S2, S3.

Pour désactiver le cryptage des secrets sur un cluster HA :

. Désactivé sur S1
+
[,bash]
----
k3s secrets-encrypt disable
----

. Tuer et redémarrer S1 avec les mêmes arguments. Si vous utilisez K3s en tant que service :
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. Une fois que le S1 est en place, tuer et redémarrer le S2 et le S3.
. Recryptage avec drapeaux sur S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

Pour réactiver le cryptage des secrets sur un cluster HA :

. Activation sur S1
+
[,bash]
----
k3s secrets-encrypt enable
----

. Tuer et redémarrer S1 avec les mêmes arguments
. Une fois que le S1 est en place, tuer et redémarrer le S2 et le S3.
. Recryptage avec drapeaux sur S1
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--
======

=== Secrets État du cryptage

L'outil secrets-encrypt comprend une commande `status` qui affiche des informations sur l'état actuel du chiffrement des secrets sur le nœud.

Exemple de commande sur un nœud à serveur unique :

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
----

Autre exemple sur un cluster HA, après la rotation des clés, mais avant le redémarrage des serveurs :

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: rotate
Server Encryption Hashes: hash does not match between node-1 and node-2

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2021-12-10T22:54:38Z
        AES-CBC   aescbckey
----

Les détails de chaque section sont les suivants :

* *État du cryptage*: Indique si le cryptage des secrets est désactivé ou activé sur le nœud.
* *Stade de rotation actuel*: Indique l'étape de rotation actuelle du nœud. +
Les étapes sont les suivantes : `start`, `prepare`, `rotate`, `reencrypt_request`, `reencrypt_active`, `reencrypt_finished`
* *Hachures de chiffrement du serveur*: Utile pour les clusters HA, elle indique si tous les serveurs sont sur la même longueur d'onde avec leurs fichiers locaux. Cela permet d'identifier si un redémarrage des serveurs est nécessaire avant de passer à l'étape suivante. Dans l'exemple HA ci-dessus, le nœud 1 et le nœud 2 ont des hachages différents, ce qui indique qu'ils n'ont pas la même configuration de chiffrement. Le redémarrage des serveurs synchronisera leur configuration.
* *Tableau clé*: Résume les informations sur les clés de chiffrement des secrets trouvées sur le nœud.
 ** *Actif*: Le "*" indique, le cas échéant, laquelle des clés est actuellement utilisée pour le cryptage des secrets. Une clé active est utilisée par Kubernetes pour chiffrer tout nouveau secret.
 ** *Type de clé*: Toutes les clés utilisant cet outil sont de type `AES-CBC`. Plus d'informations sur https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers[ici.]
 ** *Nom*: Nom de la clé de cryptage.
