include::partial$variables.adoc[]
= Installation von kwctl ({project-name} CLI)
:revdate: 2026-03-18
:page-revdate: {revdate}
:title: Installation von kwctl
:description: Installieren Sie kwctl (die {project-name} CLI), indem Sie die Installationsanweisungen für verschiedene Betriebssysteme befolgen, und aktivieren Sie dann die Shell-Vervollständigung.
:keywords: ["{project-name}", kubewarden, kubernetes, kwctl installieren, installieren, kwctl]
:doc-persona: kubewarden-all
:doc-type: howto
:doc-topic: install-kwctl

`+kwctl+` ist die Befehlszeilenschnittstelle (CLI) für {project-name}. Im Folgenden finden Sie Installationsanweisungen für einige Betriebssysteme.

[tabs]
====
Linux::
+
--
Installieren für Linux

. Selbstgebrautes
+
Wenn Sie den Homebrew-Paketmanager unter Linux verwenden, dann:
+
[source,console]
----
brew install kwctl
----
+
Überprüfen Sie die Installation:
+
[source,console]
----
kwctl --version
----

. Zypper (openSUSE)
+
[source,console]
----
zypper install kwctl
----

. AUR
+
Wenn Sie Arch Linux oder eine Arch-basierte Distribution verwenden, können Sie kwctl aus dem AUR installieren.
+
.. Verwendung eines AUR-Helferchens (juhu):
+
[source,console]
----
yay -S kwctl
----
+
.. Verwendung von makepkg:
+
[source,console]
----
# Clone the AUR package
git clone https://aur.archlinux.org/kwctl.git
cd kwctl

# Build and install the package
makepkg -si
----
+
.. Überprüfen Sie die Installation:
+
[source,console]
----
kwctl --version
----

. Manuelle Installation
+
.. Laden Sie die neueste Version von `+kwctl+` für Linux herunter:
+
[source,console]
----
curl -LO https://github.com/kubewarden/kwctl/releases/latest/download/kwctl-linux-x86_64.zip
----
+
Für ARM64-Systeme (z. B. Raspberry Pi), verwenden Sie:
+
[source,console]
----
curl -LO https://github.com/kubewarden/kwctl/releases/latest/download/kwctl-linux-aarch64.zip
----
+
.. Extrahieren Sie die Dateien aus der heruntergeladenen Datei `+.zip+`:
+
[source,console]
----
unzip kwctl-linux-x86_64.zip
----
+
Dies extrahiert die folgenden Dateien:
+
* `+kwctl-linux-x86_64+`: Die Binärdatei `+kwctl+` 
* `+kwctl-linux-x86_64.sig+`: Eine Signaturdatei zur Verifizierung der Binärdatei
* `+kwctl-linux-x86_64.pem+`: Eine Zertifikatsdatei zur Überprüfung der Signatur
+
.. Verschieben Sie die Binärdatei in ein Verzeichnis in Ihrem PATH, benennen Sie sie in `+kwctl+` um und machen Sie sie ausführbar.
+
.. Überprüfen Sie die Installation:
+
[source,console]
----
kwctl --version
----

--
macOS::
+
--
Für macOS installieren.

. Homebrew verwenden
+
.. Installieren Sie `+kwctl+`:
+
[source,shell]
----
brew install kwctl
----
+
Überprüfen Sie die Installation:
+
[source,console]
----
kwctl --version
----
+
. Manuelle Installation
+
.. Laden Sie die neueste Version von `+kwctl+` für macOS herunter:
+
... Für **Apple Silicon (ARM64)** Systeme, verwenden Sie:
+
[source,console]
----
curl -LO https://github.com/kubewarden/kwctl/releases/latest/download/kwctl-darwin-aarch64.zip
----
...  Für **Intel (x86_64)** Systeme, verwenden Sie:
+
[source,console]
----
curl -LO https://github.com/kubewarden/kwctl/releases/latest/download/kwctl-darwin-x86_64.zip
----
+
... Extrahieren Sie die Dateien aus der heruntergeladenen Datei `+.zip+`:
+
[source,console]
----
unzip kwctl-darwin-x86_64.zip
----
+
Dies extrahiert die folgenden Dateien:
+
* `+kwctl-darwin-x86_64+`: Die Binärdatei `+kwctl+` 
* `+kwctl-darwin-x86_64.sig+`: Eine Signaturdatei zur Verifizierung der Binärdatei
* `+kwctl-darwin-x86_64.pem+`: Eine Zertifikatsdatei zur Überprüfung der Signatur
+
.. Verschieben Sie die Binärdatei in ein Verzeichnis in Ihrem PATH, benennen Sie sie in `+kwctl+` um und machen Sie sie ausführbar.
+
.. Überprüfen Sie die Installation:
+
[source,console]
----
kwctl --version
----

--
Windows::
+
--
Installation für Windows

. Herunterladen `+kwctl+`:
    .. Öffnen Sie Ihren Browser und rufen Sie die https://github.com/kubewarden/kwctl/releases/latest[Seite] auf.
    .. Laden Sie die Datei `+kwctl-windows-x86_64.zip+` herunter.

. Entpacken Sie die Dateien aus der heruntergeladenen Zip-Datei. Sie wird enthalten:
+
* `+kwctl-windows-x86_64.exe+`: die `+kwctl+` binary.
* `+kwctl-windows-x86_64.sig+`: eine Signaturdatei zur Überprüfung der Binärdatei.
* `+kwctl-windows-x86_64.pem+`: eine Zertifikatsdatei zur Überprüfung der Signatur.

. Benennen Sie die Binärdatei zur einfacheren Verwendung von `+kwctl-windows-x86_64.exe+` in `+kwctl.exe+` um.

. Verschieben Sie die Binärdatei an einen Ort, der von Ihrer Umgebungsvariablen `+PATH+` abgedeckt wird.

. Überprüfen Sie die Installation. Öffnen Sie eine neue Eingabeaufforderung oder ein PowerShell-Fenster und überprüfen Sie die Installation von `+kwctl+`:
+
[source,console]
----
kwctl --version
----
--
====

== Installation von Shell-Ergänzungen

Die `+kwctl+` CLI verfügt über die Option `+--shell+`, um Shell-Vervollständigungsbefehle für Ihre Shell zu erzeugen. Sie können die Ausgabe dieses Befehls verwenden, um Vervollständigungen in Ihre Shell zu integrieren.

[source,console]
----
kwctl completions --shell [bash|elvish|fish|powershell|zsh]
----