include::partial$variables.adoc[]
= Verwaltung von {project-name} mit Rancher Fleet
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Verwalten Sie {project-name} Helm-Charts mit Rancher Fleet und Kubernetes Custom Resource Definitions (CRDs), um einen GitOps-Ansatz zu implementieren.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "rancher-fleet"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubernetes", "kubewarden", "rancher fleet"]
:sidebar_label: Rancher-Flotte
:sidebar_position: 130
:current-version: {page-origin-branch}

Sie können {project-name} Helm-Karten wie andere Helm-Karten mit https://fleet.rancher.io/[Fleet] Rancher verwalten.
Rancher Fleet verwendet Kubernetes CRDs, um einen GitOps-Ansatz zur Verwaltung von Kubernetes-Clustern zu definieren.
Dies geschieht durch die Definition von https://fleet.rancher.io/concepts[Flottenbündeln].

== Installation von

Die {short-project-name} Horoskope sind Standardhoroskope, sie hängen transitiv voneinander ab:

`+kubewarden-crds+` ← `+kubewarden-controller+` ← `+kubewarden-defaults+`

Weitere Informationen finden Sie in den xref:/quick-start.adoc[Quickstart-Dokumenten].

Mit Rancher Fleet können Sie die Diagrammabhängigkeiten mit`+dependsOn+` in der https://fleet.rancher.io/ref-fleet-yaml[`+fleet.yaml+`] Datei.

Bis die Diagramme fertig sind, können vorübergehende Fehler auftreten, wie z. B.:

[subs="+attributes",console]
----
ErrApplied(1) [Cluster fleet-local/local: dependent bundle(s) are not ready:
[kubewarden-example-helm-kubewarden-controller]]
----

Diese Fehler stellen kein Problem dar, und sobald die Bereitstellung der Karten abgeschlossen ist, werden sie nicht mehr angezeigt.

== Entfernen von

[CAUTION]
====

Beim Entfernen des GitRepo werden alle 3 {short-project-name} Diagramme auf einmal entfernt.
Das bedeutet, dass die Karte `+kubewarden-crds+` entfernt wird.

{short-project-name} verwendet einen Pre-Delete-Helm-Hook-Job in `+kubewarden-controller+` chart, der den Standard-Richtlinienserver löscht.
Dieser Pre-Delete-Hook ist notwendig, um die Webhooks der Policies zu leeren, bevor der PolicyServer gelöscht wird.
Dies gilt für jede Policy Engine.
Ist dies nicht der Fall, kann es sein, dass der Cluster Webhooks für Richtlinien hat, die nicht mehr existieren, so dass er alles ablehnt und sich in einem gescheiterten Zustand befindet.

Wenn Sie das GitRepo und damit das Diagramm `+kubewarden-crds+` gleichzeitig mit dem Diagramm `+kubewarden-controller+` entfernen, schlägt der Hook-Job vor dem Löschen fehl.
Dies bedeutet, dass die Entfernung unvollständig ist und "Trümmer" im Cluster zurückbleiben.
====


Die automatische Deinstallation von CRDs wird normalerweise von keinem Tool unterstützt, und Rancher Fleet ist da keine Ausnahme.

Um eine korrekte Entfernung durchzuführen, müssen Sie zuerst das Bundle für `+kubewarden-defaults+` aus dem Cluster entfernen.
Übertragen Sie dazu die Änderungen in das Repository mit der Fleet-Konfiguration und warten Sie dann, bis sie angewendet werden.
Entfernen Sie dann `+kubewarden-controller+` auf die gleiche Weise, und zuletzt `+kubewarden-crds+`.

Eine andere Möglichkeit besteht darin, 2 GitRepos hinzuzufügen, eines nur für die CRDs und ein weiteres für den Rest der {short-project-name} Charts.
Auf diese Weise können Sie zuerst die {short-project-name} Karten und zuletzt die {short-project-name} CRDs entfernen.

== Beispiel

Ein Beispiel für eine Fleet-Bundle-Definition finden Sie unterhttps://github.com/kubewarden/fleet-example[.com/kubewarden/fleet-example] github.
