include::partial$variables.adoc[]
= アップグレードパス
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: サポートされているバージョン戦略およびコンポーネント間の互換性ルールを使用して、{project-name} スタックをアップグレードします。
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["operator-manual", "upgrade-path"]
:doc-type: ["reference"]
:keywords: [アップグレードパス」、「サポート」]。
:sidebar_label: アップグレードパス
:sidebar_position: 20
:current-version: {page-origin-branch}

== {project-name} スタックバージョニング

{short-project-name} プロジェクトは、すべてのコンポーネントの「スタック」バージョンを定義するために、https://semver.org/[セマンティック・バージョニングを]使用しています：バージョンは、`+MAJOR.MINOR.PATCH+` パターンに従います。対応バージョンは最新リリースです。

スタック」バージョンのルールに従う{short-project-name} コンポーネントは以下の通り：

* `+kubewarden-crds+` チャートのappVersionフィールドにある。

* `+kubewarden-controller+` チャートのappVersionフィールドにある。

* `+kubewarden-defaults+` チャートのappVersionフィールドにある。

* `+policy-server+` 手動で配置されたものについては、画像タグを使用する。デフォルトのリソースはすでに`+kubewarden-defaults+` 。

* `+kwctl+` バイナリー

== コンポーネント間のスタック・バージョンの互換性

`+kubewarden-crds+` チャート、`+kubewarden-controller+` チャート、`+kubewarden-defaults+` チャート、手動でデプロイされた`+policy-server+` イメージ、および`+kwctl+` は、同じ`+MAJOR+`.`+MINOR+`.`+PATCH+` バージョンを実行する必要があります。

したがって、実行されている`+kubewarden-controller+` のバージョンが`+1.1.2+` である場合、使用されている``+policy-server++s`` と+`kwctl` の+バージョンも +1`.1.2`でなければならない。

== ヘルムチャートバージョン

ヘルム海図は`+version+` フィールドと`+appVersion+` フィールドを定義している。`+appVersion+` フィールドは、前述したように{short-project-name} "スタック "のバージョンを示す。`+version+` フィールドもhttps://semver.org/[semantic versioning] に従い、チャート・テンプレートと`+values.yaml+` の後方互換性のある変更を記述する。

== アップグレードパス

コンポーネントをアップグレードする場合、`+PATCH+` スタックの複数のバージョンを 1 回の操作でアップグレードできます。ただし、1回のアップグレードで複数の`+MAJOR+` または`+MINOR+` スタックのバージョンをアップグレードすることはサポートされて*いません*。

例えば、1回のアップグレードで、コンポーネントをバージョン`+1.1.10+` から`+1.1.nn+` にアップグレードできます。しかし、`+1.1.10+` から`+1.5.0+` へのアップグレードはサポートされていない。このような場合、2つのバージョンの間で、`+MAJOR+`/`+MINOR+` の各バージョンに個別にアップグレードする必要があります。従って、`+1.1.10+` を`+1.2.0+` に、次に`+1.3.0+` に、次に`+1.4.0+` に、そして最後に`+1.5.0+` にアップグレードする必要がある。ある`+MAJOR+` バージョンを別の`+MAJOR+` バージョンにアップグレードするには、2つの バージョンの間にある`+MINOR+` アップデートをすべて適用する必要があります。

.アップグレード・パス・サポート・グラフの例
[mermaid]
....
%%{init: "theme": "neutral"}%% フローチャート LR; accTitle：アップグレードパス対応グラフ accDescr：{short-project-name} の推奨アップグレードパスとサポートされるアップグレードパスを示した図。
  1.0.0(1.0.0)-->1.0.1(1.0.1); 1.0.1-->1.0.2(1.0.2); 1.0.2-->1.1.0(1.1.0); 1.1.0-->1.1.2(1.1.2); 1.1.0-->1.1.1; 1.1.1-->1.1.2; 1.1.2-->|推奨しない|1.2.0(1.2.0); 1.0.2-->|サポートされていません|1.2.0(1.2.0); 1.1.2-->1.2.1(1.2.1); 1.2.0-->1.2.1; linkStyle 6 color:brown,stroke-width:2px,stroke-dasharray：3 5 linkStyle 7 color:red,stroke-width:2px,stroke-dasharray：3 5
....

== アップグレード注文

{short-project-name} ユーザーは、`+kubewarden-crds+`のチャートからスタックをアップグレードし、次に`+kubewarden-controller+` のチャートをアップグレードする必要がある。その後、`+policy-server+` （`+kubewarden-defaults+` チャートまたはカスタムの画像をバンプする）をアップグレードし、`+kwctl+` 。

== 格下げ

ダウングレードはサポートされて*おらず*、{short-project-name} 。とはいえ、それが機能するはずだという合理的な期待はある。

== SDK、ポリシー

{short-project-name} チームによって維持されているさまざまな言語とポリシー用のポリシーSDKは、独自のセマンティック・バージョニングに従っている。{short-project-name} 、最新リリースをサポートしている。アップグレードパスは必要なく、最新リリースにアップグレードするだけだ。

{short-project-name} スタックへの変更は、ポリシーと SDK が最新の{short-project-name} 機能を使用するためのアップデートを受けることを意味するかもしれない。{short-project-name} は、後方互換性のある方法でこれらのアップデートを実行するように注意する。

たとえば、{short-project-name} のマイナーバージョンで Audit Scanner (`+v1.7.0+`) のサポートが追加されたということは、ポリシーに新しいフィールド`+spec.backgroundAudit+` が追加されたということです。これはオプションで、後方互換性があり、デフォルトでは`+true+` 。
