include::partial$variables.adoc[]
= Politiques relatives aux vérificateurs de signature
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Mettez en œuvre des politiques sécurisées pour votre cluster en utilisant la politique de vérification fournie, ou développez-la avec le SDK du langage de votre choix.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "signature-verifier-policies"].
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "policy specification", "signature verifier"].
:sidebar_label: Politiques relatives aux vérificateurs de signature
:current-version: {page-origin-branch}

{project-name} met en œuvre la prise en charge du projethttps://www.sigstore.dev/[Sigstore].
Cela permet de mettre en œuvre une "chaîne d'approvisionnement sécurisée" pour votre cluster.

Une partie de la fonction de la chaîne d'approvisionnement sécurisée consiste à s'assurer que toutes les images de conteneurs exécutées dans le cluster sont signées et vérifiées.
Cela prouve qu'ils proviennent de leurs auteurs déclarés, sans aucune altération.
Pour en savoir plus, consultez la documentation surxref:/howtos/security-hardening/secure-supply-chain.adoc[la mise en œuvre d'une chaîne d'approvisionnement sécurisée pour les politiques elles-mêmes].

Les signatures Sigstore sont stockées dans les registres des conteneurs, à côté de l'objet OCI signé.
Il peut s'agir d'une image de conteneur ou d'un artefact OCI plus générique, comme une politique {short-project-name}.
Lorsqu'un objet est signé, ses signatures sont stockées sous forme de couches d'un objet OCI créé par Sigstore.
Les politiques qui doivent vérifier les signatures des conteneurs doivent vérifier ces couches, et doivent extraire les couches de signature pour vérifier les signatures elles-mêmes.

L'obtention et l'utilisation de ces couches OCI doivent se faire en dehors de l'invité WebAssembly (la politique).
C'est donc le moteur d'exécution de WebAssembly,{short-project-name}'s `+policy-server+` ou `+kwctl+`, qui s'en charge.

Les différents SDK linguistiques pour les politiques {short-project-name} s'en chargent.
Ils fournissent des fonctions de vérification de l'image du conteneur, des politiques{short-project-name}, des diagrammes Helm et d'autres types d'artefacts OCI.
Cela garantit un chemin de code sûr et testé pour la vérification.

L'extraction de données d'un registre et la vérification cryptographique des signatures peuvent être coûteuses en termes de temps et de calcul, c'est pourquoi le moteur d'exécution de WebAssembly (PolicyServer, `+kwctl+`) veille à ce que l'extraction des signatures et les calculs de vérification soient mis en cache.
Les entrées mises en cache expirent automatiquement au bout de 60 secondes afin d'éviter que des données périmées ne soient servies.

== Mise en cache

Les résultats de la vérification de la signature sont mis en cache pendant une minute.

Les SDK offrent des fonctions similaires aux suivantes :

* {blank}
+
[subs="+attributes",rust]
----
verify_pub_keys_image(
    image_url: string,
    vector_of_pub_keys: vector<string>,
    vector_of_sigstore_annotations: Vector<(key, value: string)>
    )
    returns (is_trusted: bool, digest_of_verified_image: string)
----

* {blank}
+
[subs="+attributes",rust]
----
verify_keyless_exact_match(
    image_url: string,
    vector_of_tuples_issuer_and_subject: vector<(issuer, subject: string)>,
    vector_of_sigstore_annotations: vector<(key, value: string)>
    )
    returns (is_trusted: bool, digest_of_verified_image: string)
----

Les deux fonctions vérifient que l'image est signée et qu'elle satisfait aux contraintes.

[NOTE]
====
En cas de succès, les fonctions renvoient le condensé de l'image vérifiée.
Il incombe désormais à la politique de s'assurer que les conteneurs sont instanciés à partir de ce résumé, et non à partir d'une balise qui pourrait ne pas correspondre à ce résumé de somme de contrôle (et donc être compromise).
====


== Un exemple

L'équipe {short-project-name}https://github.com/kubewarden/verify-image-signatures[ fournit une politique de vérification]qui applique les signatures Sigstore à tous les conteneurs.
Il est construit en Rust et avec le SDK Rust.
La politique veille à ce que les conteneurs soient signés et, éventuellement, à ce que les demandes soient modifiées. La mutation ajoute la somme de contrôle vérifiée à la balise de l'image.
Consultez la documentation pour plus de détails.

Cette politique peut couvrir tous vos besoins, mais au cas où vous préféreriez une UX différente, vous pouvez bien sûr construire au-dessus de ce SDK ou de n'importe quel autre SDK.

== Contrat de protocole WaPC

Si vous mettez en œuvre votre propre SDK linguistique, il s'agit des fonctions qu'une politique qui vérifie les signatures peut utiliser :

=== Fonction waPC - `+v2/verify+`

==== `+SigstorePubKeyVerify+` entrée

[,hcl]
----
{
  type: "SigstorePubKeyVerify",

  # **mandatory**: image URI to verify
  "image": string,
  "pub_keys": [
    # PEM-encoded public keys
    string
    ],
  # optional:
  "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
}
----

==== `+SigstorePubKeyVerify+` sortie

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessVerify+` entrée

[,hcl]
----
{
  type: "SigstoreKeylessVerify",

  # mandatory: image URI to verify
  "image": string,
  "keyless": [
    # list of (issuer, subject) tuples
    {
      # OIDC issuer
      "issuer": string,
      # signature subject (mail, CI URL, ...)
      "subject": string
    }
  ],
  # optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreKeylessVerify+` sortie

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessPrefixVerify+` entrée

[,hcl]
----
{
  type: "SigstoreKeylessPrefixVerify",

  # mandatory: image URI to verify
  "image": string,
  "keyless_prefix": [
    # list of (issuer, url_prefix) tuples
    {
      # OIDC issuer
      "issuer": string,
      # URL Prefix of subject (CI URL, ...)
      "url_prefix": string
    }
  ],
  # optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreKeylessPrefixVerify+` sortie

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreGithubActionsVerify+` entrée

[,hcl]
----
{
  type: "SigstoreGithubActionsVerify",

  # mandatory: image URI to verify
  "image": string,
  # GitHub owner
  "owner": string,
  # optional:
  # GitHub repository
  "repo": string
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreGithubActionsVerify+` sortie

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreCertificateVerify+` entrée

[,hcl]
----
{
  type: "SigstoreCertificateVerify",

  # mandatory: image URI to verify
  "image": string,
  # PEM-encoded certificated used to
  # verify the signature.
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM encoded
  # certificate string.
  "certificate": [byte(int), ..., byte(int)],
  # Optional - certificate chain used to
  # verify the provided certificate.
  # When not specified, the certificate
  # is assumed to be trusted.
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM encoded
  # certificate string.
  "certificate_chain": [
    [byte(int), ..., byte(int)],
    ...
    [byte(int), ..., byte(int)]
  ],
  # Require the signature layer to have
  # a Rekor bundle.
  # Having a Rekor bundle allows further
  # checks to be performed, e.g. ensuring
  # the signature has been produced during
  # the validity time frame of the cert.
  # Recommended to set to `+true+`
  require_rekor_bundle: bool,
  # Optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreCertificateVerify+` sortie

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

=== Fonction waPC - `+v1/verify+`

==== `+SigstorePubKeyVerify+` entrée

[,hcl]
----
{
  "SigstorePubKeyVerify": {
    # **mandatory**: image URI to verify
    "image": string,
    "pub_keys": [
      # PEM-encoded public keys
      string
    ],
    # optional:
    "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
  }
}
----

==== `+SigstorePubKeyVerify+` sortie

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessVerify+` entrée

[,hcl]
----
{
  "SigstoreKeylessVerify": {
    # mandatory: image URI to verify
    "image": string,
    "keyless": [
      # list of (issuer, subject) tuples
      {
        # OIDC issuer
        "issuer": string,
        # signature subject (mail, CI URL, ...)
        "subject": string
      }
    ],
    # optional:
    "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
  }
}
----

==== `+SigstoreKeylessVerify+` sortie

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----
