include::partial$variables.adoc[]
= Capacités cryptographiques
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Découvrez les capacités et les fonctions cryptographiques de l'hôte Wasm pour évaluer les certificats PKI utilisés.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "cryptographic-capabilities"].
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "policy specification", "cryptographic capabilities"]
:sidebar_label: Capacités cryptographiques
:current-version: {page-origin-branch}

En raison des contraintes liées à Wasm au moment de la rédaction de ce document, certaines bibliothèques cryptographiques ne peuvent pas être compilées dans Wasm. Entre-temps, les politiques {project-name} qui ont besoin de ces bibliothèques peuvent effectuer des rappels pour évaluer les fonctions cryptographiques du côté de l'hôte. Ils reçoivent le résultat et poursuivent leurs tâches.

== Comportement

L'hôte Wasm s'appuie sur `+rustls-wepki+` pour la mise en œuvre des certificats x.509 et PKI. Cela signifie que :

- Utilisation principale : Nous avons choisi d'accepter toute utilisation de clé, ce qui permet de couvrir plusieurs cas d'utilisation (comme d'habitude, n'hésitez pas à nous contacter si vous souhaitez discuter de différentes approches).
- Chaînes de certificats : Un certificat sera considéré comme non fiable si son autorité de certification intermédiaire a expiré.
- Dates d'expiration du certificat : Si une chaîne de certificats est fournie, nous validerons toujours la totalité de la période de validité du certificat. Wepki ne vérifie pas l'expiration de l'autorité de certification racine.
- Nous validons toujours le certificat, et si aucune chaîne n'est fournie, l'autorité de certification de Mozilla est utilisée.

== Contrat de protocole WaPC

Si vous mettez en œuvre votre propre SDK linguistique, il s'agit des fonctions qui effectuent les contrôles cryptographiques exposés par l'hôte :

=== Fonction waPC - `+v1/is_certificate_trusted+` input

[,hcl]
----
# Certificate:
{
  # **mandatory**: Which encoding is used by the certificate
  # Either the string "Pem" or "Der".
  "encoding": string,
  # Actual certificate
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM/DER encoded
  # certificate string.
  "data": [byte(int), ..., byte(int)]
}

{
  # **mandatory**: PEM-encoded certificate to verify
  "cert": Certificate,
  # optional:
  "cert_chain": [
      # list of certs, ordered by trust
      # usage (intermediates first, root last)
      # If not provided, Mozilla's CA is used.
      Certificate,
      ...
      Certificate,
    ],
  # RFC 3339 time format string, to check expiration
  # against.
  # If missing, time is now.
  "not_after": string
}
----

=== Fonction waPC - `+v1/is_certificate_trusted+` sortie

[,hcl]
----
{
   # true if certificate verified:
   "trusted": boolean,
   # empty if trusted == true:
   "reason": string
}
----
