= {rancher-product-name} OpĂ§Ăľes do Helm Chart
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-22
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc 
:product-path: installation-and-upgrade/references/helm-chart-options.adoc
:keywords: ["rancher helm chart", "rancher helm options", "rancher helm chart options", "helm chart rancher", "helm options rancher", "helm chart options rancher"]
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-logging: xref:observability/logging/logging.adoc
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
:xref-tls-secrets: xref:installation-and-upgrade/resources/tls-secrets.adoc
:xref-enable-api-audit-log: xref:observability/logging/enable-api-audit-log.adoc
:xref-bootstrap-password: xref:installation-and-upgrade/resources/bootstrap-password.adoc
:xref-tls-settings: xref:installation-and-upgrade/references/tls-settings.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
:xref-air-gap: xref:comeĂ§ando/instalaĂ§ĂŁo-e-atualizaĂ§ĂŁo/outros-mĂŠtodos-de-instalaĂ§ĂŁo/air-gapped-helm-cli-install/index.adoc
:xref-tls-secrets: xref:getting-started/installation-and-upgrade/resources/add-tls-secrets.adoc
:xref-enable-api-audit-log: xref:how-to-guides/advanced-user-guides/enable-api-audit-log.adoc
:xref-bootstrap-password: xref:getting-started/installation-and-upgrade/resources/bootstrap-password.adoc
:xref-tls-settings: xref:getting-started/installation-and-upgrade/installation-references/tls-settings.adoc
endif::[]

Esta pĂĄgina ĂŠ uma referĂŞncia de configuraĂ§ĂŁo para o Rancher Helm chart.

Para informaĂ§Ăľes sobre como habilitar recursos experimentais, consulte {xref-experimental-features}[Habilitando Recursos Experimentais].

[#_common_options]
== OpĂ§Ăľes comuns

|===
| OpĂ§ĂŁo | Valor PadrĂŁo | DescriĂ§ĂŁo

| `+bootstrapPassword+`
| " "
| `+string+` - Defina a <<_bootstrap_password,senha bootstrap>> para o primeiro usuĂĄrio administrador. ApĂłs fazer login, o administrador deve redefinir sua senha. Uma senha bootstrap gerada aleatoriamente ĂŠ usada se este valor nĂŁo estiver definido.

| `+hostname+`
| " "
| `+string+` - o Nome de DomĂ­nio Completo e Qualificado para o seu Servidor Rancher

| `+ingress.tls.source+`
| "rancher"
| `+string+` - Onde obter o certificado para o ingress. - "rancher, letsEncrypt, secret"

| `+letsEncrypt.email+`
| " "
| `+string+` - Seu endereĂ§o de e-mail

| `+letsEncrypt.environment+`
| "produĂ§ĂŁo"
| `+string+` - OpĂ§Ăľes vĂĄlidas: "staging, produĂ§ĂŁo"

| `+privateCA+`
| falso
| `+bool+` - Defina como verdadeiro se seu certificado for assinado por uma CA privada
|===

{blank}

[#_advanced_options]
== OpĂ§Ăľes AvanĂ§adas

|===
| OpĂ§ĂŁo | Valor PadrĂŁo | DescriĂ§ĂŁo

| `+additionalTrustedCAs+`
| falso
| `+bool+` - Veja <<_additional_trusted_cas,CAs Adicionais ConfiĂĄveis>>

| `+addLocal+`
| "true"
| `+string+` - FaĂ§a o Rancher detectar e importar o cluster do servidor Rancher "local" (upstream).  _ObservaĂ§ĂŁo: Esta opĂ§ĂŁo nĂŁo estĂĄ mais disponĂ­vel na v2.5.0. Considere usar a opĂ§ĂŁo `+restrictedAdmin+` para impedir que os usuĂĄrios modifiquem o cluster local._

| `+agentTLSMode+`
| ""
| `+string+` - ou `+system-store+` ou `+strict+`. Veja xref:./tls-settings.adoc#_agent_tls_enforcement[AplicaĂ§ĂŁo de TLS do Agente]

| `+antiAffinity+`
| "preferred"
| `+string+` - Regra de AntiAffinity para pods do Rancher - "preferred, required"

| `+auditLog.destination+`
| "sidecar"
| `+string+` - Transmitir para o console do contĂŞiner sidecar ou volume hostPath - "sidecar, hostPath"

| `+auditLog.hostPath+`
| "/var/log/rancher/audit"
| `+string+` - destino do arquivo de registro no host (aplica-se apenas quando `+auditLog.destination+` estĂĄ definido como `+hostPath+`)

| `+auditLog.enabled+`
| falso
| `+bool+` - Habilita / desabilita o registro de auditoria.

| `+auditLog.level+`
| 0
| `+int+` - defina o nĂ­vel de {xref-enable-api-audit-log}[Registro de Auditoria da API]. [0-3]

| `+auditLog.maxAge+`
| 1
| `+int+` - nĂşmero mĂĄximo de dias para reter arquivos de registro de auditoria antigos (aplica-se apenas quando `+auditLog.destination+` estĂĄ definido como `+hostPath+`)

| `+auditLog.maxBackup+`
| 1
| `+int+` - nĂşmero mĂĄximo de arquivos de registro de auditoria a serem retidos (aplica-se apenas quando `+auditLog.destination+` estĂĄ definido como `+hostPath+`)

| `+auditLog.maxSize+`
| 100
| `+int+` - tamanho mĂĄximo em megabytes do arquivo de registro de auditoria antes de ser rotacionado (aplica-se apenas quando `+auditLog.destination+` estĂĄ definido como `+hostPath+`)

| `+auditLog.image.repository+`
| "registry.suse.com/bci/bci-micro"
| `+string+` - LocalizaĂ§ĂŁo da imagem usada para coletar arquivos de registro de auditoria.

| `+auditLog.image.tag+`
| "15.4.14.3"
| `+string+` - Tag para a imagem usada para coletar arquivos de registro de auditoria.

| `+auditLog.image.pullPolicy+`
| "IfNotPresent"
| `+string+` - Substitui a polĂ­tica de pull da imagem para imagens de arquivo de registro de auditoria - "Always", "Never", "IfNotPresent".

| `+busyboxImage+`
| ""
| `+string+` - LocalizaĂ§ĂŁo da imagem busybox usada para coletar registros de auditoria. _ObservaĂ§ĂŁo: Esta opĂ§ĂŁo estĂĄ descontinuada; use `+auditLog.image.repository+` para controlar a imagem do sidecar de auditoria._

| `+certmanager.version+`
| ""
| `+string+` - defina a compatibilidade com o cert-manager

| `+debug+`
| falso
| `+bool+` - defina a flag de depuraĂ§ĂŁo no servidor Rancher

| `+extraEnv+`
| []
| `+list+` - defina variĂĄveis de ambiente adicionais para o Rancher

| `+imagePullSecrets+`
| []
| `+list+` - lista de nomes do recurso Secret contendo credenciais de registro privado

| `+ingress.configurationSnippet+`
| ""
| `+string+` - configuraĂ§ĂŁo adicional do Nginx. Pode ser usado para configuraĂ§ĂŁo de proxy.

| `+ingress.extraAnnotations+`
| {}
| `+map+` - anotaĂ§Ăľes adicionais para personalizar o ingress.

| `+ingress.enabled+`
| true
| `+string+` - Quando definido como falso, o Helm nĂŁo instalarĂĄ um ingress do Rancher. Defina a opĂ§ĂŁo como falsa para implantar seu prĂłprio ingress.

| `+letsEncrypt.ingress.class+`
| ""
| `+string+` - classe de ingress opcional para o ingress do cert-manager acmesolver que responde aos desafios ACME do Let's Encrypt. OpĂ§Ăľes: traefik, nginx.

| `+noProxy+`
| "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,cattle-system.svc"
| `+string+` - lista de nomes de host ou endereĂ§os IP separados por vĂ­rgula que nĂŁo devem usar o proxy

| `+proxy+`
| ""
| `+string+` - servidor proxy HTTP[S] para o Rancher

| `+image.registry+`
| ""
| `+string+` - Substituir o registro especĂ­fico da imagem do Rancher, por exemplo, `+\http://registry.example.com/+`

| `+image.repository+`
| "rancher/rancher"
| `+string+` - fonte da imagem do Rancher

| `+image.pullPolicy+`
| "IfNotPresent"
| `+string+` - Substituir a polĂ­tica de pull da imagem para imagens do servidor Rancher - "Always", "Never", "IfNotPresent"

| `+image.tag+`
| ""
| `+string+` - PadrĂŁo para .Chart.appVersion para a tag da imagem Rancher/Rancher

| `+replicas+`
| 3
| `+int+` - NĂşmero de rĂŠplicas do servidor Rancher. Definir como -1 escolherĂĄ dinamicamente 1, 2 ou 3 com base no nĂşmero de nĂłs disponĂ­veis no cluster.

| `+resources+`
| {}
| `+map+` - solicitaĂ§Ăľes e limites de recursos do pod do Rancher

| `+systemDefaultRegistry+`
| ""
| `+string+` - registro privado a ser usado para todas as imagens de contĂŞiner do sistema, por exemplo, `+\https://registry.example.com/+`

| `+tls+`
| "ingress"
| `+string+` - Veja <<_external_tls_termination,TerminaĂ§ĂŁo TLS Externa>> para detalhes. - "ingress, external"

| `+useBundledSystemChart+`
| `+false+`
| `+bool+` - selecione para usar os charts do sistema empacotados com o servidor Rancher. Esta opĂ§ĂŁo ĂŠ usada para instalaĂ§Ăľes air-gapped.
|===

[#_bootstrap_password]
=== Senha Bootstrap

VocĂŞ pode {xref-bootstrap-password}[definir uma senha bootstrap especĂ­fica] durante a instalaĂ§ĂŁo do Rancher. Se vocĂŞ nĂŁo definir uma senha bootstrap especĂ­fica, o Rancher gera aleatoriamente uma senha para a primeira conta de administrador.

Quando vocĂŞ fizer login pela primeira vez, use a senha bootstrap que vocĂŞ definiu para acessar. Se vocĂŞ nĂŁo definiu uma senha bootstrap, a interface do Rancher mostra comandos que podem ser usados para {xref-bootstrap-password}#_retrieving_the_bootstrap_password[recuperar a senha bootstrap]. Execute esses comandos e faĂ§a login na conta. ApĂłs fazer login pela primeira vez, vocĂŞ serĂĄ solicitado a redefinir a senha do administrador.

[#_api_audit_log]
=== Registro de Auditoria da API

Habilitando o {xref-enable-api-audit-log}[Registro de Auditoria da API].

VocĂŞ pode coletar este registro como faria com qualquer registro de contĂŞiner. Ative {xref-logging}[o registro] para o `+System+` Projeto no cluster do servidor Rancher.

[,plain]
----
--set auditLog.enabled=true --set auditLog.level=1
----

Por padrĂŁo, habilitar o Registro de Auditoria criarĂĄ um contĂŞiner sidecar no pod do Rancher. Este contĂŞiner (`+rancher-audit-log+`) transmitirĂĄ o registro para `+stdout+`. VocĂŞ pode coletar este registro como faria com qualquer registro de contĂŞiner. Ao usar o sidecar como destino do registro de auditoria, as opĂ§Ăľes `+hostPath+`, `+maxAge+`, `+maxBackups+` e `+maxSize+` nĂŁo se aplicam. Ă aconselhĂĄvel usar os recursos de rotaĂ§ĂŁo de registro do seu sistema operacional ou do daemon do Docker para controlar o uso do espaĂ§o em disco. Ative {xref-logging}[o registro] para o cluster do servidor Rancher ou Projeto do Sistema.

Defina o `+auditLog.destination+` como `+hostPath+` para encaminhar registros para um volume compartilhado com o sistema host em vez de transmitir para um contĂŞiner sidecar. Ao definir o destino como `+hostPath+`, vocĂŞ pode querer ajustar os outros parĂ˘metros de auditLog para rotaĂ§ĂŁo de registros.

[#_setting_extra_environment_variables]
=== Configurando VariĂĄveis de Ambiente Extras

VocĂŞ pode definir variĂĄveis de ambiente extras para o servidor Rancher usando `+extraEnv+`. Esta lista ĂŠ passada para a implantaĂ§ĂŁo do Rancher em seu formato YAML. EstĂĄ embutido sob `+env+` para o contĂŞiner Rancher. Consulte a documentaĂ§ĂŁo do Kubernetes para definir variĂĄveis de ambiente do contĂŞiner, `+extraEnv+` pode usar qualquer uma das chaves referenciadas em https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#define-an-environment-variable-for-a-container[Definir VariĂĄveis de Ambiente para um ContĂŞiner].

Considere um exemplo que usa as chaves `+name+` e `+value+`:

[,plain]
----
--set 'extraEnv[0].name=CATTLE_TLS_MIN_VERSION'
--set 'extraEnv[0].value=1.0'
----

Se passar dados sensĂ­veis como valor para uma variĂĄvel de ambiente, como credenciais de autenticaĂ§ĂŁo de proxy, ĂŠ altamente recomendĂĄvel que uma referĂŞncia a um segredo seja utilizada. Isso evitarĂĄ que dados sensĂ­veis sejam expostos no Helm ou na implantaĂ§ĂŁo do Rancher.

Considere um exemplo que usa as chaves `+name+`, `+valueFrom.secretKeyRef.name+` e `+valueFrom.secretKeyRef.key+`. Veja o exemplo em <<_http_proxy,HTTP Proxy>>

[#_tls_settings]
=== ConfiguraĂ§Ăľes de TLS

Quando vocĂŞ instala o Rancher dentro de um cluster Kubernetes, o TLS ĂŠ descarregado no controlador de entrada do cluster. As possĂ­veis configuraĂ§Ăľes de TLS dependem do controlador de entrada utilizado.

Consulte {xref-tls-settings}[TLS settings] para mais informaĂ§Ăľes e opĂ§Ăľes.

[#_import_local_cluster]
=== Importar `+local+` Cluster

Por padrĂŁo, o servidor Rancher detectarĂĄ e importarĂĄ o cluster `+local+` em que estĂĄ sendo executado. O usuĂĄrio com acesso ao cluster `+local+` terĂĄ essencialmente acesso "root" a todos os clusters gerenciados pelo servidor Rancher.

[CAUTION]
====

Se vocĂŞ desativar addLocal, a maioria dos recursos do Rancher v2.5 nĂŁo funcionarĂĄ, incluindo o provisionador EKS.
====


Se isso for uma preocupaĂ§ĂŁo em seu ambiente, vocĂŞ pode definir essa opĂ§ĂŁo como "falso" na sua instalaĂ§ĂŁo inicial.

Essa opĂ§ĂŁo ĂŠ eficaz apenas na instalaĂ§ĂŁo inicial do Rancher. Consulte https://github.com/rancher/rancher/issues/16522[Issue 16522] para mais informaĂ§Ăľes.

[,plain]
----
--set addLocal="false"
----

[#_customizing_your_ingress]
=== Personalizando seu Ingress

Para personalizar ou usar um ingress diferente com o servidor Rancher, vocĂŞ pode definir suas prĂłprias anotaĂ§Ăľes de Ingress.

Por favor, consulte a documentaĂ§ĂŁo do Traefik para a lista completa de anotaĂ§Ăľes do Ingress NGINX que sĂŁo https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/ingress-nginx/#annotations-support[suportadas] e https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/ingress-nginx/#unsupported-annotations[nĂŁo suportadas] pelo provedor kubernetesIngressNginx do Traefik.

Exemplo de configuraĂ§ĂŁo de um emissor de certificado personalizado:

[,plain]
----
--set ingress.extraAnnotations.'cert-manager\.io/cluster-issuer'=issuer-name
----

[#_http_proxy]
=== Proxy HTTP

O Rancher requer acesso Ă  internet para algumas funcionalidades (Helm charts). Use `+proxy+` para definir seu servidor proxy ou use `+extraEnv+` para definir a variĂĄvel de ambiente `+HTTPS_PROXY+` para apontar para seu servidor proxy.

Adicione suas exceĂ§Ăľes de IP ao valor do grĂĄfico `+noProxy+` como uma lista separada por vĂ­rgulas. Certifique-se de adicionar os seguintes valores:

* Intervalo de IP do cluster de Pods (padrĂŁo: `+10.42.0.0/16+`).
* Intervalo de IP do cluster de ServiĂ§os (padrĂŁo: `+10.43.0.0/16+`).
* DomĂ­nios internos do cluster (padrĂŁo: `+.svc,.cluster.local+`).
* Qualquer nĂł `+controlplane+` do cluster de trabalhadores.
O Rancher suporta intervalos em notaĂ§ĂŁo CIDR nesta lista.

Quando nĂŁo incluir dados sensĂ­veis, as opĂ§Ăľes de grĂĄfico `+proxy+` ou `+extraEnv+` podem ser usadas. Ao usar `+extraEnv+`, a opĂ§ĂŁo Helm `+noProxy+` ĂŠ ignorada. Portanto, a variĂĄvel de ambiente `+NO_PROXY+` tambĂŠm deve ser definida com `+extraEnv+`.

O seguinte ĂŠ um exemplo de configuraĂ§ĂŁo de proxy usando a opĂ§ĂŁo de grĂĄfico `+proxy+`:

[,plain]
----
--set proxy="http://<proxy_url:proxy_port>/"
----

Exemplo de configuraĂ§ĂŁo de proxy usando a opĂ§ĂŁo de grĂĄfico `+extraEnv+`:

[,plain]
----
--set extraEnv[1].name=HTTPS_PROXY
--set extraEnv[1].value="http://<proxy_url>:<proxy_port>/"
--set extraEnv[2].name=NO_PROXY
--set extraEnv[2].value="127.0.0.0/8\,10.0.0.0/8\,172.16.0.0/12\,192.168.0.0/16\,.svc\,.cluster.local"
----

Ao incluir dados sensĂ­veis, como credenciais de autenticaĂ§ĂŁo de proxy, use a opĂ§ĂŁo `+extraEnv+` com `+valueFrom.secretRef+` para evitar que dados sensĂ­veis sejam expostos no Helm ou na implantaĂ§ĂŁo do Rancher.

O seguinte ĂŠ um exemplo de uso de `+extraEnv+` para configurar o proxy. Este segredo de exemplo conteria o valor `+"http://<username>:<password>@<proxy_url>:<proxy_port>/"+` na chave `+"https-proxy-url"+` do segredo:

[,plain]
----
--set extraEnv[1].name=HTTPS_PROXY
--set extraEnv[1].valueFrom.secretKeyRef.name=secret-name
--set extraEnv[1].valueFrom.secretKeyRef.key=https-proxy-url
--set extraEnv[2].name=NO_PROXY
--set extraEnv[2].value="127.0.0.0/8\,10.0.0.0/8\,172.16.0.0/12\,192.168.0.0/16\,.svc\,.cluster.local"
----

Para saber mais sobre como configurar variĂĄveis de ambiente, consulte https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#define-an-environment-variable-for-a-container[Definir VariĂĄveis de Ambiente para um ContĂŞiner].

[#_additional_trusted_cas]
=== CAs ConfiĂĄveis Adicionais

Se vocĂŞ tiver registros privados, catĂĄlogos ou um proxy que intercepta certificados, pode ser necessĂĄrio adicionar mais CAs confiĂĄveis ao Rancher.

[,plain]
----
--set additionalTrustedCAs=true
----

Uma vez que a implantaĂ§ĂŁo do Rancher ĂŠ criada, copie seus certificados CA em formato pem para um arquivo chamado `+ca-additional.pem+` e use `+kubectl+` para criar o segredo `+tls-ca-additional+` no namespace `+cattle-system+`.

[,plain]
----
kubectl -n cattle-system create secret generic tls-ca-additional --from-file=ca-additional.pem=./ca-additional.pem
----

[#_private_registry_and_air_gap_installs]
=== InstalaĂ§Ăľes de Registro Privado e Air Gap

Para detalhes sobre a instalaĂ§ĂŁo do Rancher com um registro privado, consulte a {xref-air-gap}[documentaĂ§ĂŁo de instalaĂ§ĂŁo air gap.]

[#_external_tls_termination]
== TerminaĂ§ĂŁo TLS Externa

Recomendamos configurar seu balanceador de carga como um balanceador de camada 4, encaminhando trĂĄfego simples nas portas 80/tcp e 443/tcp para os nĂłs do cluster de Gerenciamento do Rancher. O controlador de Ingress no cluster redirecionarĂĄ o trĂĄfego http na porta 80 para https na porta 443.

VocĂŞ pode terminar o SSL/TLS em um balanceador de carga L7 externo ao cluster do Rancher (ingress). Use a opĂ§ĂŁo `+--set tls=external+` e aponte seu balanceador de carga para a porta http 80 em todos os nĂłs do cluster do Rancher. Isso exporĂĄ a interface do Rancher na porta http 80. Esteja ciente de que os clientes que tĂŞm permissĂŁo para se conectar diretamente ao cluster do Rancher nĂŁo estarĂŁo criptografados. Se vocĂŞ optar por fazer isso, recomendamos que restrinja o acesso direto ao nĂ­vel da rede apenas ao seu balanceador de carga.

[NOTE]
====

Se vocĂŞ estiver usando um certificado assinado por uma CA Privada (ou se `+agent-tls-mode+` estiver definido como `+strict+`), adicione `+--set privateCA=true+` e consulte {xref-tls-secrets}[Adicionando Segredos TLS - Usando um Certificado Assinado por uma CA Privada] para adicionar o certificado CA para o Rancher.
====


Seu balanceador de carga deve suportar conexĂľes websocket de longa duraĂ§ĂŁo e precisarĂĄ inserir cabeĂ§alhos proxy para que o Rancher possa rotear links corretamente.

[#_required_headers]
=== CabeĂ§alhos NecessĂĄrios

* `+Host+`
* `+X-Forwarded-Proto+`
* `+X-Forwarded-Port+`
* `+X-Forwarded-For+`

[#_recommended_timeouts]
=== Timeouts Recomendados

* Tempo de Espera de Leitura: `+1800 seconds+`
* Tempo de Espera de GravaĂ§ĂŁo: `+1800 seconds+`
* Tempo de Espera de ConexĂŁo: `+30 seconds+`

[#_health_checks]
=== VerificaĂ§Ăľes de saĂşde

O Rancher responderĂĄ `+200+` Ă s verificaĂ§Ăľes de saĂşde no endpoint `+/healthz+`.
