= Perfil de recursos
:page-languages: [en, ja, ko, zh]
:revdate: 2025-01-06
:page-revdate: {revdate}

Esta seção captura os resultados dos testes para determinar os requisitos mínimos de recursos para os K3s.

== Requisitos mínimos de recursos para K3s

Os resultados estão resumidos a seguir:

|===
| Componentes | Processador | CPU mínima | RAM mínima com Kine/SQLite | RAM mínima com etcd incorporado

| Servidor K3s com uma carga de trabalho
| CPU Intel 8375C, 2,90 GHz
| 6% de um núcleo
| 1596 M
| 1606 M

| Cluster do K3s com um único agente
| CPU Intel 8375C, 2,90 GHz
| 5% de um núcleo
| 1428 M
| 1450 M

| Agente K3s
| CPU Intel 8375C, 2,90 GHz
| 3% de um núcleo
| 275 M
| 275 M

| Servidor K3s com uma carga de trabalho
| Pi4B BCM2711, 1.50 GHz
| 30% de um núcleo
| 1588 M
| 1613 M

| Cluster do K3s com um único agente
| Pi4B BCM2711, 1.50 GHz
| 25% de um núcleo
| 1215 M
| 1413 M

| Agente K3s
| Pi4B BCM2711, 1.50 GHz
| 10% de um núcleo
| 268 M
| 268 M
|===

=== Escopo do teste de recursos

Os testes de recursos foram planejados para abordar as seguintes declarações de problemas:

* Em um cluster de nó único, determine a quantidade mínima legítima de CPU, memória e IOPs que deve ser reservada para executar toda a pilha de servidores do K3s, supondo que uma carga de trabalho real será implantada no cluster.
* Em um nó de agente (worker), determine a quantidade mínima legítima de CPU, memória e IOPs que deve ser reservada para os componentes do plano de controle do Kubernetes e do K3s (o kubelet e o agente do k3s).

=== Componentes incluídos para medições de linha de base

Os componentes testados são:

* K3s v1.26.5 com todos os componentes do pacote ativados
* Pilha de monitoramento Prometheus + Grafana
* https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[Exemplo de implantação do Nginx no Kubernetes]

Esses são números de linha de base para um sistema estável usando apenas componentes empacotados do K3s (Traefik Ingress, Klipper lb, armazenamento de caminho local) executando uma pilha de monitoramento padrão (Prometheus e Grafana) e o aplicativo de exemplo Guestbook.

Os números de recursos, incluindo IOPS, são apenas para o datastore e o plano de controle do Kubernetes e não incluem a sobrecarga para agentes de gerenciamento ou registro em nível de sistema, gerenciamento de imagem de contêiner ou quaisquer requisitos específicos de carga de trabalho.

=== Metodologia

Uma instância autônoma do Prometheus v2.43.0 foi usada para coletar estatísticas de CPU, memória e E/S de disco do host usando o site `prometheus-node-exporter` instalado via apt.

`systemd-cgtop` foi usado para verificar a utilização da CPU e da memória no nível do cgroup do systemd. O site `system.slice/k3s.service` rastreia a utilização de recursos para K3s e containerd, enquanto os pods individuais estão na hierarquia `kubepods`.

Outros dados detalhados de utilização de memória do K3s foram coletados em `kubectl top node` usando o servidor de métricas integrado para os processos do servidor e do agente.

Os números de utilização foram baseados em leituras de percentil 95 da operação de estado estável em nós que executam as cargas de trabalho descritas.

=== Meio ambiente

|===
| Arco | OS | Sistema | CPU | RAM | Disco

| x86_64
| Ubuntu 22.04
| AWS c6id.xlarge
| CPU Intel Xeon Platinum 8375C, 4 núcleos, 2,90 GHz
| 8 GB
| SSD NVME

| aarch64
| Raspberry Pi OS 11
| Raspberry Pi 4 Modelo B
| BCM2711, 4 núcleos de 1,50 GHz
| 8 GB
| UHS-III SDXC
|===

=== Requisitos de recursos de linha de base

Esta seção apresenta os resultados dos testes para determinar os requisitos mínimos de recursos para a operação básica do K3s.

==== Servidor K3s com uma carga de trabalho

Esses são os requisitos para um cluster de nó único no qual o servidor K3s compartilha recursos com uma https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/[carga de trabalho simples do].

Os requisitos da CPU são:

|===
| Sistema | Uso do núcleo da CPU

| Intel 8375C
| 6% de um núcleo

| Pi4B
| 30% de um núcleo
|===

Os requisitos de memória são:

|===
| Banco de dados testado | Sistema | Memória

| Kine/SQLite
| Intel 8375C
| 1596 M

|
| Pi4B
| 1588 M

| etcd incorporado
| Intel 8375C
| 1606 M

|
| Pi4B
| 1613 M
|===

Os requisitos do disco são:

|===
| Banco de dados testado | IOPS | KiB/seg | Latência

| Kine/SQLite
| 10
| 500
| < 10 ms

| etcd incorporado
| 50
| 250
| < 5 ms
|===

==== Cluster do K3s com um único agente

Esses são os requisitos de linha de base para um cluster do K3s com um nó de servidor do K3s e um agente do K3s, mas sem carga de trabalho.

===== K3s Server

Os requisitos da CPU são:

|===
| Sistema | Uso do núcleo da CPU

| Intel 8375C
| 5% de um núcleo

| Pi4B
| 25% de um núcleo
|===

Os requisitos de memória são:

|===
| Banco de dados testado | Sistema | Memória

| Kine/SQLite
| Intel 8375C
| 1428 M

|
| Pi4B
| 1215 M

| etcd incorporado
| Intel 8375C
| 1450 M

|
| Pi4B
| 1413 M
|===

===== Agente K3s

Os requisitos são:

|===
| Sistema | Uso do núcleo da CPU | RAM

| Intel 8375C
| 3% de um núcleo
| 275 M

| Pi4B
| 5% de um núcleo
| 268 M
|===

=== Análise dos fatores determinantes da utilização de recursos primários

Os números de utilização do servidor do K3s são impulsionados principalmente pelo suporte ao armazenamento de dados do Kubernetes (kine ou etcd), ao API Server, ao Controller-Manager e aos loops de controle do Scheduler, bem como a quaisquer tarefas de gerenciamento necessárias para efetuar alterações no estado do sistema. As operações que colocam carga adicional no plano de controle do Kubernetes, como a criação/modificação/exclusão de recursos, causarão picos temporários na utilização. O uso de operadores ou aplicativos que fazem uso extensivo do repositório de dados do Kubernetes (como o Rancher ou outros aplicativos do tipo Operator) aumentará os requisitos de recursos do servidor. O dimensionamento do cluster por meio da adição de nós adicionais ou da criação de muitos recursos de cluster aumentará os requisitos de recursos do servidor.

Os números de utilização do agente do K3s são impulsionados principalmente pelo suporte de loops de controle de gerenciamento do ciclo de vida do contêiner. As operações que envolvem o gerenciamento de imagens, o provisionamento de armazenamento ou a criação/destruição de contêineres causarão picos temporários de utilização. Os pulls de imagem, em particular, costumam ser altamente vinculados à CPU e à E/S, pois envolvem a descompactação do conteúdo da imagem no disco. Se possível, o armazenamento da carga de trabalho (armazenamento e volumes efêmeros do pod) deve ser isolado dos componentes do agente (/var/lib/rancher/k3s/agent) para garantir que não haja conflitos de recursos.

=== Impedindo que agentes e cargas de trabalho interfiram no armazenamento de dados do cluster

Ao executar em um ambiente em que o servidor também está hospedando pods de carga de trabalho, deve-se tomar cuidado para garantir que o IOPS do agente e da carga de trabalho não interfira no armazenamento de dados.

A melhor maneira de fazer isso é colocar os componentes do servidor (/var/lib/rancher/k3s/server) em uma mídia de armazenamento diferente dos componentes do agente (/var/lib/rancher/k3s/agent), que incluem o armazenamento de imagens do containerd.

O armazenamento da carga de trabalho (armazenamento e volumes efêmeros do pod) também deve ser isolado do armazenamento de dados.

O não cumprimento dos requisitos de latência e taxa de transferência do datastore pode resultar em atraso na resposta do plano de controle e/ou falha do plano de controle em manter o estado do sistema.

[#_server_sizing_requirements_for_k3s]
== Requisitos de dimensionamento de servidor para K3s

=== Meio ambiente

* Todos os agentes eram instâncias t3.medium do AWS ec2.
** Um único agente era uma instância c5.4xlarge. Isso hospedou a pilha de monitoramento do Grafana e impediu que ela interferisse nos recursos do plano de controle.
* O servidor era uma instância c5 ec2 do AWS. À medida que o número de agentes aumentou, o servidor foi atualizado para instâncias maiores do c5.

=== Metodologia

Esses dados foram recuperados em condições de teste específicas. Isso varia de acordo com o ambiente e as cargas de trabalho. As etapas abaixo fornecem uma visão geral do teste que foi executado para obter isso. Foi realizada pela última vez na versão v1.31.0+k3s1. Todas as máquinas foram provisionadas no AWS com volumes padrão de 20 GiB gp3. O teste foi executado com as seguintes etapas:

. Monitore os recursos no grafana usando a fonte de dados prometheus. 
. Implemente cargas de trabalho de forma a simular a atividade contínua do cluster:
** Uma carga de trabalho básica que aumenta e diminui continuamente
** Uma carga de trabalho que é excluída e recriada em um loop
** Uma carga de trabalho constante que contém vários outros recursos, incluindo CRDs.
. Junte-se aos nós de agente em lotes de 50 a 100 por vez.
. Interrompa a adição de agentes quando a CPU do servidor atingir um pico de utilização acima de 90% ao ingressar no agente ou se a RAM estiver acima de 80% de utilização. 

=== Observações

* Ao unir agentes, a CPU do servidor registrou picos de ~20% em relação à linha de base.
* Normalmente, o fator limitante era a CPU, não a RAM. Na maioria dos testes, quando a CPU atingiu 90% de utilização, a utilização da RAM ficou em torno de 60%.

==== Uma observação sobre alta disponibilidade (HA)

No final de cada teste, dois servidores adicionais foram unidos (formando um cluster HA básico de 3 nós) para observar o efeito que isso teve sobre os recursos originais do servidor. O efeito foi o seguinte:

* Uma queda perceptível na utilização da CPU, geralmente de 30 a 50%.
* A utilização da RAM permaneceu a mesma.

Embora não tenha sido testado, com a utilização da CPU como fator limitante em um único servidor, espera-se que o número de agentes que podem ser unidos aumente em cerca de 50% com um cluster HA de 3 nós.
