= Grundlegende Netzwerkoptionen
:page-languages: [en, ja, ko, zh]
:revdate: 2025-12-31
:page-revdate: {revdate}

Auf dieser Seite werden die Optionen für die Netzwerkkonfiguration des K3s beschrieben, einschließlich der Konfiguration oder des Austauschs von Flannel und der Konfiguration von IPv6 oder DualStack.

== Flanell-Optionen

https://github.com/flannel-io/flannel/blob/master/README.md[Flannel] ist ein leichtgewichtiger Anbieter einer Layer-3-Netzwerkstruktur, die das Kubernetes Container Network Interface (CNI) implementiert. Es handelt sich um ein so genanntes CNI-Plugin.

* Flannel-Optionen können nur auf Serverknoten eingestellt werden und müssen auf allen Servern des Clusters identisch sein.
* Das Standard-Backend für Flannel ist `+vxlan+`. Um die Verschlüsselung zu aktivieren, verwenden Sie das Backend `+wireguard-native+`.
* Die Verwendung von `+vxlan+` auf dem Rasperry Pi mit neueren Versionen von Ubuntu erfordert xref:installation/requirements.adoc#os_tab_raspberry_pi[zusätzliche Vorbereitungen].
* Die Verwendung von `+wireguard-native+` als Flannel-Backend kann bei einigen Linux-Distributionen zusätzliche Module erfordern. Weitere Informationen finden Sie in der https://www.wireguard.com/install/[WireGuard-Installationsanleitung].
Die WireGuard-Installationsschritte stellen sicher, dass die entsprechenden Kernel-Module für Ihr Betriebssystem installiert werden.
Sie müssen sicherstellen, dass die WireGuard-Kernelmodule auf jedem Knoten verfügbar sind, sowohl auf den Servern als auch auf den Agenten, bevor Sie versuchen, das WireGuard Flannel-Backend zu verwenden.

|===
| CLI-Flag und Wert | Beschreibung

| `+--flannel-ipv6-masq+`
| Wenden Sie Masquerading-Regeln auf IPv6-Datenverkehr an (Standard für IPv4). Gilt nur für Dual-Stack- oder IPv6-only-Cluster. Kompatibel mit jedem Flannel-Backend außer `+none+`.

| `+--flannel-external-ip+`
| Verwenden Sie externe IP-Adressen des Knotens als Ziel für den Flannel-Verkehr anstelle von internen IPs. Gilt nur, wenn --node-external-ip auf einem Knoten eingestellt ist.

| `+--flannel-backend=vxlan+`
| Verwenden Sie VXLAN, um die Pakete zu kapseln. Kann zusätzliche Kernel-Module auf dem Raspberry Pi erfordern.

| `+--flannel-backend=host-gw+`
| Verwenden Sie IP-Routen zu Pod-Subnetzen über Knoten-IPs. Erfordert eine direkte Layer-2-Verbindung zwischen allen Knoten des Clusters.

| `+--flannel-backend=wireguard-native+`
| Verwenden Sie WireGuard, um den Netzwerkverkehr zu kapseln und zu verschlüsseln. Kann zusätzliche Kernelmodule erfordern.

| `+--flannel-backend=ipsec+`
| Verwenden Sie strongSwan IPSec über das `+swanctl+` Binary, um den Netzwerkverkehr zu verschlüsseln. (Veraltet; wird in v1.27.0 entfernt)

| `+--flannel-backend=none+`
| Deaktivieren Sie Flannel vollständig.
|===

[IMPORTANT]
.Version Tor
====

K3s enthält ab den Versionen 2022-12 (v1.26.0+k3s1, v1.25.5+k3s1, v1.24.9+k3s1, v1.23.15+k3s1) keine strongSwan `+swanctl+` und `+charon+` Binaries mehr. Bitte installieren Sie die richtigen Pakete auf Ihrem Node, bevor Sie auf diese Versionen aktualisieren oder diese installieren, wenn Sie das `+ipsec+` Backend verwenden möchten.
====

[#_migrating_from_wireguard_or_ipsec_to_wireguard_native]
=== Umstellung von `+wireguard+` oder `+ipsec+` auf `+wireguard-native+`

Das alte Backend `+wireguard+` erfordert die Installation des Tools `+wg+` auf dem Host. Dieses Backend ist in K3s v1.26 und höher nicht verfügbar, zugunsten des `+wireguard-native+` Backends, das direkt mit dem Kernel verbunden ist.

Das alte Backend `+ipsec+` erfordert die Installation der Binärdateien `+swanctl+` und `+charon+` auf dem Host. Dieses Backend ist in K3s v1.27 und höher nicht verfügbar und wird durch das `+wireguard-native+` Backend ersetzt.

Wir empfehlen den Nutzern, so bald wie möglich auf das neue Backend zu migrieren. Die Migration erfordert eine kurze Ausfallzeit, während die Knoten mit der neuen Konfiguration arbeiten. Sie sollten diese beiden Schritte befolgen:

. Aktualisieren Sie die K3s-Konfiguration auf allen Serverknoten. Wenn Sie Konfigurationsdateien verwenden, sollte `+/etc/rancher/k3s/config.yaml+` `+flannel-backend: wireguard-native+` anstelle von `+flannel-backend: wireguard+` oder `+flannel-backend: ipsec+` enthalten. Wenn Sie K3s über CLI-Flags in der systemd-Unit konfigurieren, sollten die entsprechenden Flags geändert werden.
. Starten Sie alle Knoten neu, beginnend mit den Servern.

=== Optionen für Flanellagenten

Diese Optionen stehen für jeden Agenten zur Verfügung und sind spezifisch für die Flannel-Instanz, die auf diesem Knoten läuft.

|===
| CLI-Flagge | Beschreibung

| `+--flannel-iface+` Wert
| Standardflanschschnittstelle außer Kraft setzen

| `+--flannel-conf+` Wert
| Standardkonfigurationsdatei für Flanell überschreiben

| `+--flannel-cni-conf+` Wert
| Standardkonfigurationsdatei von Flannel cni außer Kraft setzen
|===

== Benutzerdefinierte CNI

Starten Sie K3s mit `+--flannel-backend=none+` und installieren Sie das CNI Ihrer Wahl. Die meisten CNI-Plugins verfügen über eine eigene Netzwerkrichtlinien-Engine, so dass es empfehlenswert ist, auch `+--disable-network-policy+` einzustellen, um Konflikte zu vermeiden. Einige wichtige Informationen, die zu berücksichtigen sind:

[tabs,,sync-group-id=cni]
======
Kanal::
+
--
Besuchen Sie die Website https://docs.tigera.io/calico/latest/getting-started/kubernetes/flannel/install-for-flannel#installing-calico-for-policy-and-flannel-aka-canal-for-networking[Canal Docs]. Folgen Sie den Schritten zur Installation von Canal. Ändern Sie die Canal YAML so, dass z.B. im Abschnitt `+container_settings+` die IP-Weiterleitung erlaubt ist:

[,yaml]
----
"container_settings": {
  "allow_ip_forwarding": true
}
----

Wenden Sie den Kanal YAML an.

Stellen Sie sicher, dass die Einstellungen übernommen wurden, indem Sie den folgenden Befehl auf dem Host ausführen:

[,bash]
----
cat /etc/cni/net.d/10-canal.conflist
----

Sie sollten sehen, dass die IP-Weiterleitung auf true gesetzt ist.
--

Kattun::
+
--
Folgen Sie dem https://docs.tigera.io/calico/latest/reference/configure-cni-plugins[Calico CNI Plugins Guide]. Ändern Sie die Calico-YAML so, dass z. B. im Abschnitt `+container_settings+` die IP-Weiterleitung erlaubt ist:

[,yaml]
----
"container_settings": {
  "allow_ip_forwarding": true
}
----

Wenden Sie die Calico YAML an.

Stellen Sie sicher, dass die Einstellungen übernommen wurden, indem Sie den folgenden Befehl auf dem Host ausführen:

[,bash]
----
cat /etc/cni/net.d/10-calico.conflist
----

Sie sollten sehen, dass die IP-Weiterleitung auf true gesetzt ist.
--

Cilium::
+
--
Bevor Sie `+k3s-killall.sh+` oder `+k3s-uninstall.sh+` ausführen, müssen Sie die Schnittstellen `+cilium_host+`, `+cilium_net+` und `+cilium_vxlan+` manuell entfernen. Wenn Sie dies nicht tun, können Sie die Netzwerkverbindung zum Host verlieren, wenn K3s beendet wird.

[,bash]
----
ip link delete cilium_host
ip link delete cilium_net
ip link delete cilium_vxlan
----

Außerdem sollten die iptables-Regeln für cilium entfernt werden:

[,bash]
----
iptables-save | grep -iv cilium | iptables-restore
ip6tables-save | grep -iv cilium | ip6tables-restore
----
--
======

== Control-Plane-Egress-Selector-Konfiguration

K3s-Agenten und -Server unterhalten Websocket-Tunnel zwischen den Knoten, die zur Kapselung der bidirektionalen Kommunikation zwischen den Komponenten der Steuerungsebene (Apiserver) und den Agenten (Kubelet und Containerd) verwendet werden.
Dadurch können Agenten arbeiten, ohne die Kubelet- und Container-Laufzeit-Streaming-Ports für eingehende Verbindungen freizugeben, und die Steuerungsebene kann sich mit Clusterdiensten verbinden, wenn der Agent deaktiviert ist.
Diese Funktionalität entspricht dem https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/[Konnectivity-Dienst], der häufig in anderen Kubernetes-Distributionen verwendet wird, und wird über die Egress-Selector-Konfiguration des Apiserver verwaltet.

Der Standardmodus ist `+agent+`. Die Modi `+pod+` oder `+cluster+` werden für den Betrieb von xref:advanced.adoc#_running_agentless_servers_experimental[agentenlosen Servern] empfohlen, um dem Apiserver den Zugang zu den Endpunkten der Clusterdienste zu ermöglichen, wenn Flannel und Kube-Proxy nicht vorhanden sind.

Der Egress-Selector-Modus kann auf Servern über das Flag `+--egress-selector-mode+` konfiguriert werden und bietet vier Modi:

* `+disabled+`: Der Apiserver verwendet keine Agenten-Tunnel zur Kommunikation mit Kubelets oder Cluster-Endpunkten.
Dieser Modus setzt voraus, dass auf den Servern kubelet, CNI und kube-proxy laufen und eine direkte Verbindung zu den Agenten besteht. Andernfalls kann der apiserver nicht auf Service-Endpunkte zugreifen oder `+kubectl exec+` und `+kubectl logs+` ausführen.
* `+agent+` (Voreinstellung): Der Apiserver verwendet Agententunnel zur Kommunikation mit Kubelets.
Dieser Modus setzt voraus, dass auf den Servern auch kubelet, CNI und kube-proxy laufen, sonst kann der Apiserver nicht auf Service-Endpunkte zugreifen.
* `+pod+`: Der Apiserver verwendet Agententunnel, um mit Kubelets und Service-Endpunkten zu kommunizieren und leitet Endpunktverbindungen an den richtigen Agenten weiter, indem er Nodes und Endpoints beobachtet. +
*HINWEIS*: Dieser Modus funktioniert nicht, wenn eine CNI verwendet wird, die ihr eigenes IPAM verwendet und die PodCIDR-Zuweisung des Knotens nicht respektiert. Bei diesen CNIs sollte stattdessen der Modus `+cluster+` oder `+agent+` verwendet werden.
* `+cluster+`: Der Apiserver verwendet Agententunnel, um mit Kubelets und Service-Endpunkten zu kommunizieren und leitet Endpunktverbindungen an den richtigen Agenten weiter, indem er Pods und Endpunkte beobachtet. Dieser Modus bietet die beste Übertragbarkeit über verschiedene Clusterkonfigurationen hinweg, allerdings auf Kosten eines erhöhten Overheads.

== Dual-Stack-Vernetzung (IPv4 + IPv6)

[IMPORTANT]
.Version Tor
====

Experimentelle Unterstützung ist ab https://github.com/k3s-io/k3s/releases/tag/v1.21.0%2Bk3s1[.21.0+k3s1] v1 verfügbar. +
Stabile Unterstützung ist ab https://github.com/k3s-io/k3s/releases/tag/v1.23.7%2Bk3s1[.23.7+k3s1] v1 verfügbar.
====


[CAUTION]
.Bekanntes Problem
====

Vor Version 1.27 führt Kubernetes https://github.com/kubernetes/kubernetes/issues/111695[Issue #111695] dazu, dass das Kubelet die IPv6-Adressen der Knoten ignoriert, wenn Sie eine Dual-Stack-Umgebung haben und nicht die primäre Netzwerkschnittstelle für den Clusterverkehr verwenden. Um diesen Fehler zu vermeiden, verwenden Sie 1.27 oder eine neuere Version oder fügen Sie das folgende Flag zu K3s Servern und Agenten hinzu:

----
--kubelet-arg="node-ip=0.0.0.0" # To proritize IPv4 traffic
#OR
--kubelet-arg="node-ip=::" # To proritize IPv6 traffic
----
====


Das Dual-Stack-Netzwerk muss bei der ersten Erstellung des Clusters konfiguriert werden. Es kann nicht in einem bestehenden Cluster aktiviert werden, wenn dieser als IPv4-only gestartet wurde.

Um Dual-Stack in K3s zu aktivieren, müssen Sie gültige Dual-Stack `+cluster-cidr+` und `+service-cidr+` auf allen Serverknoten bereitstellen. Dies ist ein Beispiel für eine gültige Konfiguration:

----
--cluster-cidr=10.42.0.0/16,2001:db8:42::/56 --service-cidr=10.43.0.0/16,2001:db8:43::/112
----

Beachten Sie, dass Sie alle gültigen Werte für `+cluster-cidr+` und `+service-cidr+` konfigurieren können, aber die oben genannten Masken werden empfohlen. Wenn Sie die Maske `+cluster-cidr+` ändern, sollten Sie auch die Werte `+node-cidr-mask-size-ipv4+` und `+node-cidr-mask-size-ipv6+` so ändern, dass sie mit den geplanten Pods pro Knoten und der Gesamtanzahl der Knoten übereinstimmen. Die größte unterstützte `+service-cidr+` Maske ist /12 für IPv4 und /112 für IPv6. Denken Sie daran, ipv6-Verkehr zuzulassen, wenn Sie in einer öffentlichen Cloud bereitstellen.

Wenn Sie IPv6-Adressen verwenden, die nicht öffentlich geroutet sind, z. B. im ULA-Bereich, sollten Sie die Option `+--flannel-ipv6-masq+` hinzufügen, um IPv6-NAT zu aktivieren, da Pods standardmäßig ihre Pod-IPv6-Adresse für ausgehenden Verkehr verwenden.
Wenn jedoch öffentlich geroutete IPv6-Adressen verwendet werden, müssen Sie sicherstellen, dass diese Adressen zu Ihrem Cluster geroutet werden. Andernfalls können die Pods keine Antworten auf Pakete empfangen, die von ihrer IPv6-Adresse stammen. Es liegt zwar außerhalb der Möglichkeiten von K3s, der externen Routing-Infrastruktur automatisch mitzuteilen, welche Adressen auf welchem Knoten verwendet werden, aber die Cluster-Mitglieder können den Pod-Verkehr korrekt weiterleiten, so dass Sie Ihre Routen auf jeden Knoten des Clusters richten können.

Wenn Sie ein benutzerdefiniertes CNI-Plugin verwenden, d. h. ein anderes CNI-Plugin als Flannel, kann eine zusätzliche Konfiguration erforderlich sein. Bitte konsultieren Sie die Dual-Stack-Dokumentation Ihres Plugins und überprüfen Sie, ob Netzwerkrichtlinien aktiviert werden können.

[CAUTION]
.Bekanntes Problem
====
Bei der Definition von cluster-cidr und service-cidr mit IPv6 als primäre Familie sollte die node-ip aller Clustermitglieder explizit gesetzt werden, wobei die gewünschte IPv6-Adresse des Knotens als erste Adresse platziert wird. Standardmäßig verwendet das Kubelet immer IPv4 als primäre Adressfamilie.
====

== Single-Stack-IPv6-Netzwerke

[IMPORTANT]
.Version Tor
====
Verfügbar ab https://github.com/k3s-io/k3s/releases/tag/v1.22.9%2Bk3s1[.22.9+k3s1] v1
====


[CAUTION]
.Bekanntes Problem
====
Wenn Ihre IPv6-Standardroute durch ein Router-Advertisement (RA) festgelegt ist, müssen Sie sysctl `+net.ipv6.conf.all.accept_ra=2+` setzen; andernfalls wird der Knoten die Standardroute verwerfen, sobald sie abläuft. Beachten Sie, dass die Annahme von RAs das Risiko von https://github.com/kubernetes/kubernetes/issues/91507[Man-in-the-Middle-Angriffen] erhöhen kann.
====


Single-Stack-IPv6-Cluster (Cluster ohne IPv4) werden auf K3s unter Verwendung der Flags `+--cluster-cidr+` und `+--service-cidr+` unterstützt. Dies ist ein Beispiel für eine gültige Konfiguration:

[,bash]
----
--cluster-cidr=2001:db8:42::/56 --service-cidr=2001:db8:43::/112
----

Wenn Sie IPv6-Adressen verwenden, die nicht öffentlich geroutet sind, z. B. im ULA-Bereich, sollten Sie die Option `+--flannel-ipv6-masq+` hinzufügen, um IPv6-NAT zu aktivieren, da Pods standardmäßig ihre Pod-IPv6-Adresse für ausgehenden Verkehr verwenden.

== Knoten ohne Hostname

Einige Cloud-Anbieter, wie z. B. Linode, erstellen Maschinen mit "localhost" als Hostname, während bei anderen überhaupt kein Hostname festgelegt ist. Dies kann zu Problemen bei der Auflösung von Domänennamen führen. Sie können K3s mit der Flagge `+--node-name+` oder der Umgebungsvariablen `+K3S_NODE_NAME+` ausführen, wodurch der Name des Knotens übergeben wird, um dieses Problem zu beheben.
