= Enviar datos sanitarios a través de HTTP
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidad de SUSE

== Visión general

SUSE xref:/setup/cli/cli-sts.adoc[Observability] puede sincronizar la información sanitaria de sus propias fuentes de datos a través de HTTP o de la xref:/setup/cli/cli-sts.adoc[CLI de SUSE Observability].

== API de SUSE Observability Receiver

La API de SUSE Observability Receiver acepta datos de topología, métricas, eventos y estado en un objeto JSON común. La ubicación por defecto para la API del receptor es `<STACKSTATE_RECEIVER_API_ADDRESS>`, construida usando `<STACKSTATE_BASE_URL>` y ``<+STACKSTATE_RECEIVER_API_KEY>+``.

La dirección `<STACKSTATE_RECEIVER_API_ADDRESS>` para SUSE Observability implantado en Kubernetes u OpenShift es:

[,text]
----
https://<STACKSTATE_BASE_URL>/receiver/stsAgent/intake?api_key=<STACKSTATE_RECEIVER_API_KEY>
----

`<STACKSTATE_BASE_URL>` y `<STACKSTATE_RECEIVER_API_KEY>` se configuran durante la instalación de SUSE Observability; para obtener más información, consulte xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_generate_values_yaml[Instalación de Kubernetes: parámetros de configuración].

== JSON

=== Objeto JSON común

Los datos de topología, telemetría y salud se envían a la API receptora a través de HTTP POST. Existe un objeto JSON común utilizado para todos los mensajes.

[,javascript]
----
{
  "collection_timestamp": 1548855554, // the epoch timestamp for the collection
  "events": {}, // used to send events data
  "internalHostname": "localdocker.test", // the host sending this data
  "metrics": [], // used to send metrics data
  "service_checks": [],
  "topologies": [], // used to send topology data
  "health": // used for sending health data
}
----

=== Carga útil de salud JSON

SUSE Observability acepta datos sanitarios basados en un xref:/configure/health/health-synchronization.adoc#_consistency_models[modelo de coherencia] elegido. Los mensajes que pueden enviarse para cada modelo se describen en las páginas siguientes:

* xref:/configure/health/send-health-data/repeat_snapshots.adoc[Repetir instantáneas JSON]
* xref:/configure/health/send-health-data/transactional_increments.adoc[Incrementos transaccionales JSON]

== Ver también

* xref:/setup/cli/cli-sts.adoc[Instalar SUSE Observability CLI]
