include::partial$variables.adoc[]
= {project-name} 是什么？
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 了解{project-name} 在 Kubernetes 策略管理中的作用，包括执行合规性和优化资源。
:doc-persona: ["kubewarden-all"]
:doc-topic: ["introduction"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "cncf", "cncf sandbox", "kubernetes", "admission policy manager"]
:sidebar_label: 导言
:sidebar_position: 1
:slug: /
:current-version: {page-origin-branch}

{project-name} 是 Kubernetes 策略引擎。
它旨在成为 Kubernetes 的通用策略引擎。

{intro-paragraph}

== {project-name} 有何帮助？

{short-project-name} 为 Kubernetes 环境中的策略接纳和执行提供了灵活性。

=== 效益和价值

- 使用任何可生成https://webassembly.org[WebAssembly]二进制文件的编程语言编写策略。
- WebAssembly 支持跨处理器和操作系统的策略兼容性。
- 可重复使用其他策略引擎的策略，无需重新编写。
- 使用标准、安全的机制分发策略，如https://opencontainers.org[] OCI 兼容注册表。
- 在接入时执行策略，确保只有符合要求的工作负载才能运行。
- {short-project-name} 审计扫描仪会随着时间的推移主动、持续地检查策略执行情况。
- 使用https://slsa.dev[SLSA]（软件工件供应链级别）工具和实践验证政策。
- {project-name} 提供了一种全面的录取策略管理方法。
- CNCF 的成员资格以及不断壮大的开源社区和生态系统有助于{short-project-name} 实现透明、协作和改进。

=== 使用案例

- 安全加固。例如，执行限制容器权限的策略、执行网络策略或阻止不安全的映像注册。
- 合规审计。确保工作负载符合组织或监管标准和最佳实践。
- 资源优化。执行资源限制和配额。

xref:use-cases.adoc[使用案例]页面上有更多关于xref:use-cases.adoc[使用案例]的文档。

== {short-project-name} 的新用户？

如果您是{short-project-name} 项目的新手，请从xref:quick-start.adoc[快速入门指南]和xref:explanations/architecture.adoc[架构]页面开始。
那就看你的兴趣所在了。对于政策制定者，教程中有专门的语言章节。为集成商和管理员提供了 "操作方法 "部分。解释部分包含有用的背景材料。此外还有xref:glossary.adoc[词汇表]。

== 什么是 WebAssembly？

正如https://webassembly.org/[WebAssembly 官方网站]上所述：

____
WebAssembly （缩写为 Wasm）是一种二进制指令格式，用于基于堆栈的虚拟机。Wasm 被设计为编程语言的可移植编译目标，可在网络上部署客户端和服务器应用程序。
____

Wasm 最初是一个浏览器 "扩展"。不过，WebAssembly 社区正在努力允许在浏览器之外执行 Wasm 代码。

== 为什么使用 WebAssembly？

用户可以使用自己喜欢的编程语言编写 Kubernetes 策略，前提是其工具链能够生成 Wasm 二进制文件。

Wasm 模块具有可移植性，一旦构建完成，即可在任何类型的处理器架构和操作系统上运行。例如，在 Apple Silicon 上开发和构建的策略无需转换即可在 AMD64/Intel64 Linux 上运行。

政策制定者可以重复使用他们的技能、工具和最佳实践。策略是 "传统 "程序，可以有可重复使用的块（常规库）。您可以对它们进行检查和测试，还可以将它们插入当前的 CI 和 CD 工作流程。

== 政策分配

您可以使用标准网络服务器提供{short-project-name} 策略，或者将其作为https://github.com/opencontainers/artifacts[工具] OCI发布到符合 OCI 标准的注册表中。

ifeval::["{build-type}" == "community"]

== 供应商中立

{short-project-name} 是 CNCF 定义的 \link:https://contribute.cncf.io/maintainers/community/vendor-neutrality/[供应商中立]项目。

endif::[]
