= K3S シークレット・エンクリプト
:page-languages: [en、ja、ko、zh]。
:revdate: 2026-01-05
:page-revdate: {revdate}

K3sは、静止時に秘密の暗号化を有効にすることをサポートしています。詳細はxref:security/secrets-encryption.adoc[秘密の暗号]化を参照。

== 秘密の暗号化ツール

[IMPORTANT]
.バージョン・ゲート
====
https://github.com/k3s-io/k3s/releases/tag/v1.21.8%2Bk3s1[]v11で利用可能。
====


K3sには、以下の自動制御を可能にするCLIツール`secrets-encrypt` が含まれています：

* 秘密の暗号化の無効化／有効化
* 新しい暗号化キーの追加
* 暗号化キーのローテーションと削除
* 秘密の再暗号化

[CAUTION]
====
暗号化キーのローテーションを適切な手順で行わないと、クラスタが永久に破損したままになる可能性があります。慎重に進め。
====

[#_encryption_key_rotation]
=== 暗号化キーのローテーション

[IMPORTANT]
.バージョン・ゲート
====
2024年9月のリリースで利用可能：v1.30.5+k3s1、v1.31.1+k3s1。
====

[tabs,sync-group-id=se]
======
シングルサーバー::
+
--
単一サーバー・クラスタで秘密暗号鍵をローテーションする：

. フラグでK3sサーバーを起動する `--secrets-encryption`
+
[NOTE]
====
暗号化なしでK3sを起動し、後で暗号化を有効にすることは現在サポートされて_いません_。
====

. 暗号化キーのローテーション
+
----
k3s secrets-encrypt rotate-keys
----

. 再暗号化が完了するまで待つ。サーバーのログを見るか、待つ：
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
--

高可用性::
+
--
HAセットアップで秘密の暗号鍵をローテーションする：

. `--secrets-encryption` 、3台のK3sサーバーをすべて立ち上げる。簡潔にするため、サーバーをS1、S2、S3と呼ぶ。
+
[NOTE]
====
暗号化なしでK3sを起動し、後で暗号化を有効にすることは現在サポートされて_いません_。
====

. S1で秘密の暗号鍵をローテーションする
+
[,bash]
----
k3s secrets-encrypt rotate-keys
----

. 再暗号化が完了するまで待つ。サーバーのログを見るか、待つ：
+
[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
----
+
[NOTE]
====
K3は1秒間に〜5個の秘密を再暗号化する。大量の秘密を持つクラスタは、再暗号化に数分かかることがある。進捗状況はサーバーのログで確認できる。
====

. 同じ引数でS1上のK3を再起動する。K3sをサービスとして実行している場合：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. S1が立ち上がったら、S2とS3のK3を再起動する。
--
======

=== レガシー暗号化キーのローテーション

[TIP]
.新規手続き
====
K3sのバージョンv1.30以上を使用する場合は、代わりにxref:#_encryption_key_rotation[暗号化キーのローテーションを]使用することをお勧めします。
====

[tabs,sync-group-id=se]
======
シングルサーバー::
+
--
単一サーバー・クラスタで秘密暗号鍵をローテーションする：

. フラグでK3sサーバーを起動する `--secrets-encryption`
+
[NOTE]
====
暗号化なしでK3sを起動し、後で暗号化を有効にすることは現在サポートされて_いません_。
====

. 準備する
+
[,bash]
----
k3s secrets-encrypt prepare
----

. K3sサーバーを終了し、同じ引数で再起動する。K3sをサービスとして実行している場合：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. 回転
+
[,bash]
----
k3s secrets-encrypt rotate
----

. K3sサーバーを終了し、同じ引数で再起動する。
. 再エンクリプト
+
[NOTE]
====
K3は1秒間に〜5個の秘密を再暗号化する。 +
大量の秘密を持つクラスタは、再暗号化に数分かかることがある。
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----
--

高可用性::
+
--
組み込みDBクラスタでも外部DBクラスタでも手順は同じです。

HAセットアップで秘密の暗号鍵をローテーションする：

. `--secrets-encryption` 、3台のK3sサーバーをすべて立ち上げる。簡潔にするため、サーバーをS1、S2、S3と呼ぶ。
+
[NOTE]
====
* 暗号化なしでK3sを起動し、後で暗号化を有効にすることは現在サポートされて_いません_。
* 必須ではありませんが、`secrets-encrypt` コマンドを実行するサーバーノードを1つ選ぶことをお勧めします。
====
. S1の準備
+
[,bash]
----
k3s secrets-encrypt prepare
----

. S1を終了し、同じ引数で再起動する。K3sをサービスとして実行している場合：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. S1が立ち上がったら、S2とS3を終了させ、再起動させる。
. S1で回転
+
[,bash]
----
k3s secrets-encrypt rotate
----

. 同じ引数でS1を終了させ、再起動させる
. S1が立ち上がったら、S2とS3を終了させ、再起動させる。
. S1で再暗号化
+
[NOTE]
====
K3は1秒間に〜5個の秘密を再暗号化する。 +
大量の秘密を持つクラスタは、再暗号化に数分かかることがある。
====
+
[,bash]
----
k3s secrets-encrypt reencrypt
----

. 同じ引数でS1を終了させ、再起動させる
. S1が立ち上がったら、S2とS3を終了させ、再起動させる。
--
======

=== 秘密の暗号化 無効化／再有効化

[tabs,sync-group-id=se]
======
シングルサーバー::
+
--
`--secrets-encryption` フラグを付けてサーバーを起動した後、秘密の暗号化を無効にすることができる。

シングル・ノード・クラスタで秘密の暗号化を無効にするには

. 無効
+
[,bash]
----
k3s secrets-encrypt disable
----

. K3sサーバーを終了し、同じ引数で再起動する。K3sをサービスとして実行している場合：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. フラグによる再暗号化
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

単一ノード・クラスタで秘密の暗号化を再度有効にするには、以下の手順に従います：

. 有効にする
+
[,bash]
----
k3s secrets-encrypt enable
----

. K3sサーバーを終了し、同じ引数で再起動する。
. フラグによる再暗号化
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--

高可用性::
+
--
HAクラスタを`--secrets-encryption` フラグで起動した後、秘密の暗号化を無効にすることができます。

[NOTE]
====
必須ではありませんが、`secrets-encrypt` コマンドを実行するサーバーノードを1つ選ぶことをお勧めします。
====

簡潔にするため、このガイドで使用する3つのサーバーをS1、S2、S3と呼ぶ。

HAクラスタで秘密の暗号化を無効にするには

. S1で無効
+
[,bash]
----
k3s secrets-encrypt disable
----

. S1を終了し、同じ引数で再起動する。K3sをサービスとして実行している場合：
+
[,bash]
----
# If using systemd
systemctl restart k3s
# If using openrc
rc-service k3s restart
----

. S1が立ち上がったら、S2とS3を終了させ、再起動させる。
. S1のフラグで再暗号化
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----

HAクラスタで秘匿暗号化を再度有効にするには、以下の手順に従います：

. S1で有効
+
[,bash]
----
k3s secrets-encrypt enable
----

. 同じ引数でS1を終了させ、再起動させる
. S1が立ち上がったら、S2とS3を終了させ、再起動させる。
. S1のフラグで再暗号化
+
[,bash]
----
k3s secrets-encrypt reencrypt --force --skip
----
--
======

=== 秘密の暗号化ステータス

secrets-encryptツールには、ノード上のsecrets暗号化の現在のステータスに関する情報を表示する`status` コマンドが含まれています。

単一サーバー・ノードでのコマンドの例：

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
----

HAクラスタでの別の例。鍵をローテーションした後、サーバーを再起動する前：

[,bash]
----
$ k3s secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: rotate
Server Encryption Hashes: hash does not match between node-1 and node-2

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2021-12-10T22:54:38Z
        AES-CBC   aescbckey
----

各セクションの詳細は以下の通り：

* *暗号化ステータス*：ノードで秘密の暗号化が無効か有効かが表示される。
* *現在のローテーション・ステージ*ノードの現在の回転ステージを示す。 +
ステージは以下の通り：`start` `prepare`,`rotate`,`reencrypt_request`,`reencrypt_active` 、 `reencrypt_finished`
* *サーバーの暗号化ハッシュ*：HAクラスタに便利で、すべてのサーバーがローカルファイルと同じステージにあるかどうかを示します。これは、次の段階に進む前に、サーバーの再起動が必要かどうかを特定するために使用できる。上記のHAの例では、node-1とnode-2は異なるハッシュを持ち、現在同じ暗号化コンフィギュレーションを持っていないことを示している。サーバーを再起動すると、設定が同期される。
* *キー・テーブル*ノードで見つかった秘密の暗号化キーに関する情報を要約する。
 ** *アクティブ*だ：は、秘密の暗号化に現在使用されている鍵があれば、それを示す。アクティブキーは、Kubernetesが新しい秘密を暗号化するために使用する。
 ** *キータイプ*このツールを使用するキーはすべて`AES-CBC` 。詳しくは https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers[こちら]
 ** *名前*暗号化キーの名前。
