= Cloud-config Referencia
:revdate: 2025-10-21
:page-revdate: {revdate}

Se espera que las imágenes de SO de nodo creadas con el https://github.com/elemental-toolkit[kit de herramientas] https://github.com/rancher/yip[{elemental-product-name} se inicialicen y configuren con] yip. Yip es una pequeña utilidad para aplicar un conjunto de acciones y configuraciones al sistema descrito con archivos yaml. Yip se integra y consume como una biblioteca dentro del binario del cliente elemental (véase `elemental run-stage --help`). Yip agrupa las configuraciones y acciones a aplicar en _etapas_ arbitrarias, por ejemplo la llamada al comando `elemental run-stage network` sólo aplicaría las acciones y configuración definidas para la etapa denominada `network`. Desde la perspectiva de Yip, las etapas pueden ejecutarse en cualquier momento, ya que simplemente agrupan un conjunto de acciones bajo un nombre arbitrario.

{elemental-product-name} Toolkit integra cinco etapas predefinidas en el proceso de arranque del sistema operativo.

. *`pre-rootfs`*: Esta etapa se ejecuta en el arranque temprano dentro del disco init ram, justo antes de montar el dispositivo raíz (normalmente en `/sysroot`). Esta etapa se puede utilizar para definir los pasos de primer arranque necesarios antes de montar el dispositivo raíz. Un buen ejemplo es ampliar la partición raíz del dispositivo. Ejecutado como parte de la `initrd-root-device.target`.
. *`rootfs`*: Esta etapa se ejecuta en el arranque temprano dentro del disco init ram, justo después de montar el dispositivo raíz (normalmente en `/sysroot`). Esta etapa se puede utilizar para definir los pasos del primer arranque, como la creación de nuevas particiones. En esta fase suelen definirse las vías efímeras y persistentes. Ejecutado como parte de la `initrd-root-fs.target`.
. *`initramfs`*: Esta etapa se ejecuta dentro del disco init ram también, pero en una etapa posterior justo antes de cambiar a root. Esta etapa se ejecuta en un entorno chroot al dispositivo raíz real. Esta etapa es útil para establecer algunos parámetros del sistema que podrían ser relevantes para systemd después de cambiar a root. Por ejemplo, aquí se podrían añadir archivos de unidad systemd adicionales antes de que se ejecute el systemd de la raíz real. Ejecutado como parte de la `initrd.target`.
. *`fs`*: Esta etapa es la primera que se ejecuta después de cambiar de root y se ejecuta como parte de `sysinit.target` que se ejecuta una vez que todos los sistemas de archivos locales y puntos de montaje definidos en fstab están montados y listos.
. *`network`*: Esta etapa se ejecuta como parte de la `multi-user.target` y después de alcanzar la `network-online.target`. Esta etapa puede utilizarse para ejecutar acciones y configuraciones que requieran conectividad de red. Por ejemplo, esta etapa se utiliza para ejecutar el primer registro de nodo y la instalación de una ISO en vivo.
. *`boot`*: Esta etapa se ejecuta como parte del multiusuario.target y antes del getty.target. Esta es la etapa por defecto para ejecutar los datos cloud-config proporcionados utilizando la sintaxis cloud-init soportada. Consulte la sección de xref:references/cloud-config-reference.adoc#_compatibility_with_cloud_init_format[compatibilidad de Cloud-init].

Por defecto, `elemental` lee los archivos de configuración yaml de las siguientes rutas en orden: `/system/oem`, `/oem` y `/usr/local/cloud-config`.

En {elemental-product-name} Operator, todos los recursos kubernetes que incluyen un campo `cloud-config` pueden expresarse en sintaxis <<_compatibility_with_cloud_init_format,compatible con>> <<_configuration_syntax,yip>> o <<_compatibility_with_cloud_init_format,cloud-init>>. Esto incluye recursos como `MachineRegistration`, `SeedImage` y `ManagedOSImage`.

[NOTE]
====
A diferencia de proyectos similares como _Cloud Init_, Yip no guarda registros o cachés de etapas y pasos ejecutados, todas las etapas y su configuración asociada se ejecuta en cada arranque.
====

== Ganchos de configuración de nube de cliente elemental

Además de las etapas definidas de cloud-config en el arranque descritas en la sección anterior, el cliente Elemental también honra algunas etapas específicas, referenciadas como hooks, para personalizar el comportamiento de estos subcomandos: `install`, `upgrade`, `reset` y `build-disk`. Cada uno de estos subcomandos tiene su propio conjunto de cuatro etapas diferentes de configuración de la nube que se ejecutan en fases análogas de la ejecución del subcomando específico.

Los ganchos son esencialmente una forma de proporcionar cambios permanentes al sistema que no pueden expresarse fácilmente como parte de un contenedor OCI o que no son fácilmente realizables con las opciones de configuración del cliente `elemental`. Un buen ejemplo podría ser el manejo del firmware en la partición EFI para dispositivos Raspberry Pi.

[WARNING]
====
Tenga en cuenta que la mayoría de los hooks se ejecutan en el entorno host con privilegios, por lo que son operaciones potencialmente destructivas. En la mayoría de los casos, las operaciones regulares de configuración de la nube en el momento del arranque son suficientes para configurar el sistema. También para incluir software adicional en una imagen la opción preferida es construir una xref:operator-operational-tasks/custom-images.adoc[imagen derivada] y no abusar de los hooks para instalar software adicional.
====

=== Etapas del gancho

Etapas previas: before-install, before-upgrade, before-reset, before-disk Estas etapas se ejecutan una vez preparados los directorios de trabajo y el entorno, pero antes de iniciar la acción propiamente dicha. En los pasos de instalación, actualización y reinicio esto ocurre una vez que todas las particiones asociadas están creadas y montadas, pero antes de indicar el despliegue de cualquier imagen.

Estas etapas se ejecutan después de desplegar el sistema de destino en el área de trabajo en un entorno chroot enraizado en la imagen desplegada real. Dado que esto ocurre en un entorno chroot, el cliente elemental analiza los ganchos presentes en la imagen desplegada, no en el host. Sólo /oem se comparte con el host si está disponible.

Etapas posteriores: after-install, after-upgrade, after-reset, after-disk Estas etapas se ejecutan después de desplegar el sistema de destino en el área de trabajo desde el entorno host. En esta fase, todas las particiones siguen montadas y disponibles en modo RW. Este conjunto particular de etapas analiza los ganchos presentes en el host y en el conjunto equivalente de rutas chroot a la imagen desplegada. Sin embargo, el gancho no se ejecuta en un entorno chroot. Esto es útil para proporcionar `after-*` ganchos dentro de la imagen desplegada.

Etapas posteriores: post-install, post-upgrade, post-reset, post-disk Estas etapas se ejecutan al final antes de salir del comando y ejecutar un proceso de limpieza. En esta fase, la imagen ya está desplegada y bloqueada en un subvolumen o sistema de archivos de sólo lectura. Las particiones siguen montadas en esta fase.

[NOTE]
====
Nota ganchos de instalación no se aplican como parte de la xref:references/machineregistration-reference.adoc#_config_cloud_config[`MachineRegistration.config.cloud-config`]. Para proporcionar ganchos de instalación pueden incluirse como parte del xref:[`SeedImage.cloud-config`]ya que deben estar presentes en el medio de instalación.
====

== Sintaxis de configuración

Yip tiene su propia sintaxis, esencialmente requiere definir _etapas_ y una lista de pasos para cada etapa. Los pasos se ejecutan en orden y cada paso puede ser una combinación de diferentes tipos de acción (por ejemplo, ejecutar comandos, crear archivos, establecer nombre de host, etc.).

Considere el siguiente ejemplo:

[,yaml]
----
stages:
  initramfs:
  - name: "Setup users"
    ensure_entities:
    - path: /etc/shadow
      entity: |
          kind: "shadow"
          username: "root"
          password: "root"
  boot:
  - files:
    - path: /tmp/script.sh
      content: |
        #!/bin/sh
        echo "test"
      permissions: 0777
      owner: 1000
      group: 100
  - commands:
    - /tmp/script.sh
----

En el ejemplo anterior hay dos etapas: `initramfs` y `boot`. La etapa `initramfs` inicializa un usuario de muestra. La etapa `boot` incluye dos pasos, uno para crear un archivo de script ejecutable y un segundo que realmente ejecuta el script.

Yip también admite modificadores de sufijo `*.before` y `*.after` para cualquier etapa. Por ejemplo, si se ejecuta la etapa `network`, primero se ejecutan las etapas `network.before` que se encuentran en los archivos de configuración y, a continuación, `network` y, por último, `network.after`.

Consulte la referencia completa de las claves aplicables en los pasos documentados en el propiohttps://github.com/rancher/yip?tab=readme-ov-file#configuration-reference[proyecto] yip.

A continuación se muestra un ejemplo de la configuración anterior incrustada en un recurso MachineRegistration.

.Haga clic aquí para más detalles
[%collapsible]
====
Ejemplo de .MachineRegistration
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      name: "A registration driven config"
      stages:
        after-install-chroot:
        - name: "Set serial console"
          commands:
          - grub2-editenv /oem/grubenv set extra_cmdline="console=ttyS0"
        initramfs:
        - name: "Setup users"
          ensure_entities:
          - path: /etc/shadow
            entity: |
                kind: "shadow"
                username: "root"
                password: "root"
        boot:
        - files:
          - path: /tmp/script.sh
            content: |
              #!/bin/sh
              echo "test"
            permissions: 0777
            owner: 1000
            group: 100
        - commands:
          - /tmp/script.sh
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
  machineName: my-machine
  machineInventoryLabels:
    element: fire
----
====

== Sincronización

Durante la ejecución de una etapa se cargan todos los archivos, se calcula un gráfico y luego se ejecuta. Esto significa que cabe esperar que los pasos de una misma etapa se ejecuten en cualquier orden e independientemente del nombre del archivo.

Para sincronizar la ejecución, el usuario puede utilizar las etapas post/pre o consultar la palabra clave `after` en la https://github.com/rancher/yip/blob/ee4051d9ec2782989344f813bc6a0975bbd8f3fe/pkg/executor/default_test.go#L222[sintaxis de] yip.

== Compatibilidad con el formato Cloud Init

Yip implementa un subconjunto de la oficial http://cloudinit.readthedocs.org/en/latest/topics/format.html#cloud-config-data[especificación]. Más concretamente, las claves cloud-init soportadas son: `users`, `ssh_authorized_keys`, `runcmd`, `hostname` y `write_files`.

Si un archivo yaml empieza por `#cloud-config` se analiza como un cloud-init estándar, asociándolo a la etapa yip `boot`.

Por ejemplo:

[,yaml]
----
#cloud-config
# Note groups are delivered as list, not as comma separated values
users:
- name: "bar"
  passwd: "foo"
  groups:
  - "users"
  homedir: "/home/foo"
  shell: "/bin/bash"
  ssh_authorized_keys:
  - faaapploo
# Assigns these keys to the first user in users or root if there
# is none
ssh_authorized_keys:
- asddadfafefa
# Run these commands once the system has fully booted
# Each command is expressed as a sinlge string, no nested lists
runcmd:
- echo hello world
# Hostname
hostname: myserver
# Write arbitrary files
write_files:
- encoding: b64
  content: CiMgVGhpcyBmaWxlIGNvbnRyb2xzIHRoZSBzdGF0ZSBvZiBTRUxpbnV4
  path: /foo/bar
  permissions: "0644"
  owner: "bar"
----

A continuación se muestra un ejemplo de la configuración anterior incrustada en un recurso MachineRegistration.

.Haga clic aquí para más detalles
[%collapsible]
====
Ejemplo de .MachineRegistration
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: "bar"
        passwd: "foo"
        groups: "users"
        homedir: "/home/foo"
        shell: "/bin/bash"
        ssh_authorized_keys:
        - faaapploo
      ssh_authorized_keys:
      - asdd
      runcmd:
      - foo
      write_files:
      - encoding: b64
        content: CiMgVGhpcyBmaWxlIGNvbnRyb2xzIHRoZSBzdGF0ZSBvZiBTRUxpbnV4
        path: /foo/bar
        permissions: "0644"
        owner: "bar"
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
  machineName: my-machine
  machineInventoryLabels:
    element: fire
----
====
