= Referencia ManagedOSVersion
:revdate: 2025-09-08
:page-revdate: {revdate}

El recurso `ManagedOSVersion` se encarga de definir una versión de imagen del sistema operativo que puede utilizarse con los recursos `SeedImage` o `ManagedOSImage`.

Hay varias claves que pueden configurarse en una especificación de recursos `ManagedOSVersion`.

.managedosversion-example.yaml
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  labels:
    elemental.cattle.io/channel: elemental-channel
  name: v2.0.2
  namespace: fleet-default
spec:
  metadata:
    displayName: SLE Micro
    upgradeImage: registry.suse.com/suse/sle-micro/5.5:2.0.2
  type: container
  version: v2.0.2
----

== `ManagedOSVersionSpec` referencia

|===
| Clave | Tipo | Valor por defecto | Descripción

| metadata
| objeto
| null
| Define algunos datos sobre la imagen del sistema operativo. Véase [referencia](#metadatos)

| minVersion
| cadena
| null
| No se utiliza

| tipo
| cadena
| vacío
| Define el tipo de imagen del sistema operativo, puede ser `container` o `iso`

| versión
| cadena
| vacío
| Versión de la imagen del sistema operativo

| upgradeContainer
| objeto
| null
| Un contenedor de actualización que se puede definir. Ver [referencia](#upgradecontainer)
|===

.Haga clic aquí para más detalles
[%collapsible]
====
Ejemplo de imagen .ISO
[,yaml]
----
metadata:
  displayName: SLE Micro ISO x86_64
  uri: registry.suse.com/suse/sl-micro/6.0/baremetal-iso-image:2.2.0
type: iso
version: v2.2.0
----
====

.Haga clic aquí para más detalles
[%collapsible]
====
Ejemplo de imagen .container
[,yaml]
----
metadata:
  displayName: SLE Micro upgrade
  upgradeImage: registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:2.2.0
type: container
version: v2.2.0
----
====

== metadata

Aquí se describe la información necesaria para definir una imagen del sistema operativo en {elemental-product-name}.

Si `type` se establece en `container`:

|===
| Clave | Tipo | Valor por defecto | Descripción

| displayName
| cadena
| vacío
| Nombre de la imagen del SO como se ve en Rancher UI

| actualizarImagen
| cadena
| vacío
| Imagen completa del contenedor (referencia OCI o URI HTTP)
|===

Si `type` se establece en `iso`:

|===
| Clave | Tipo | Valor por defecto | Descripción

| displayName
| cadena
| vacío
| Nombre de la imagen del SO como se ve en Rancher UI

| uri
| cadena
| vacío
| Imagen ISO completa
|===

== `upgradeContainer`

Permite sobrescribir el campo `upgrade` predeterminado de los planes del controlador de actualización del sistema (consulte xref:rancher-os-management/upgrade-lifecycle.adoc#_components[los componentes de actualización]) en función de esta ManagedOSVersion.
El controlador de actualización del sistema traduce estas claves a una especificación de Kubernetes https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container[contenedor].
Este es el contenedor responsable de ejecutar una actualización del sistema operativo.
