include::partial$variables.adoc[]
= スウィフト
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: {project-name} ポリシーを構築するためのツールにアクセスするために、SwiftWasm を通して WebAssembly をサポートする Swift コンパイラを使用する方法を学ぶ。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "swift"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"writing policies"、"swift"]]。
:sidebar_label: スウィフト
:sidebar_position: 50
:current-version: {page-origin-branch}

https://swift.org/[：]

____
Swiftは、初心者には親しみやすく、熟練者には強力な汎用プログラミング言語だ。
速くて、モダンで、安全で、書くのが楽しい。
____

swiftコンパイラはまだWebAssemblyをサポートしていませんが、https://swiftwasm.org/[SwiftWasm]プロジェクトがこの機能を持つパッチ付きコンパイラを提供しています。

SwiftWasmチームはこれらの変更をSwiftプロジェクトにマージする作業を行っている。
その間、{project-name} ポリシーを構築するために SwiftWasm プロジェクトによって提供されるツールチェーンを使用することができます。

[NOTE]
====

Swiftのコードを書いたり実行したりするのにAppleのシステムは必要ない。すべてはLinuxマシン上でも、Windows上でも（Docker for Windowsを使えば）可能だ。
====


== 現状

ポリシー作成者は以下のリソースを利用できる：

* https://github.com/kubewarden/policy-sdk-swift[{short-project-name} Swift SDK]: これは、ポリシーの記述プロセスを簡素化する、``structs``と関数のセットを提供する。
* https://github.com/kubewarden/swift-policy-template[{short-project-name} Swiftテンプレートプロジェクト]：このテンプレートを使って、Swiftベースのポリシーの足場を作る。
テンプレートには、動作するポリシーと、ライフサイクルを自動化するためのGitHub Actionsのセットが付属しています。

スウィフトには深刻な制限はなく、ちょっとした問題があるだけだ：

* ポリシーを_"本番 "で_使用する前に、ビルド後の最適化を行うことが重要である：
 .. `wasm-strip` 、Wasmモジュールのサイズを縮小する。
 .. Wasmモジュールの最適化 `wasm-opt`

テンプレート・リポジトリが提供するGitHub Actionが、すでにその面倒を見てくれる。

== その他の例

https://github.com/kubewarden/pod-runtime-class-policy/tree/swift-implementation[このGitHubリポジトリのブランチには]、Swiftで書かれた{short-project-name} Policyがある。
