= Configuraﾃｧﾃ｣o
:revdate: 2025-07-23
:page-revdate: {revdate}

Uma lista de referﾃｪncia de opﾃｧﾃｵes de configuraﾃｧﾃ｣o, principalmente internas.

[[configure-install-options-in-rancher]]
== Configurar {product_name} Opﾃｧﾃｵes de Instalaﾃｧﾃ｣o no Rancher

O Rancher procura valores do Helm em um ConfigMap chamado `+rancher-config+` no namespace `+cattle-system+`.
Qualquer valor de grﾃ｡fico do Helm para {product_name} pode ser especificado sob o nome do grﾃ｡fico. Observe que o valor da chave Fleet ﾃｩ uma string.

Um `+rancher-config+` pode parecer assim, apﾃｳs adicionar algumas opﾃｧﾃｵes:

[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: rancher-config
  namespace: cattle-system
data:
  fleet: |
    controller:
      reconciler:
        workers:
          gitrepo: "50"
          bundle: "50"
          bundledeployment: "50"
  priorityClassName: rancher-critical
----

O recurso `+rancher-config+` ﾃｩ criado pelo grﾃ｡fico do Rancher e pode ser patchado:

[source,shell]
----
kubectl patch cm -n cattle-system rancher-config --type merge \
  --patch '{"data":{"fleet": "controller:\n  reconciler:\n    workers:\n      gitrepo: \"200\"\n      bundle: \"200\"\n      bundledeployment: \"200\"\n"}}'
----

== Grﾃ｡ficos do Helm

Os grﾃ｡ficos do Helm aceitam, pelo menos, as opﾃｧﾃｵes mostradas com seus padrﾃｵes em `+values.yaml+`:

* https://github.com/rancher/fleet/blob/main/charts/fleet/values.yaml
* https://github.com/rancher/fleet/blob/main/charts/fleet-crd/values.yaml
* https://github.com/rancher/fleet/blob/main/charts/fleet-agent/values.yaml

== Variﾃ｡veis de Ambiente

Os controladores podem ser iniciados com essas variﾃ｡veis de ambiente:

* `+CATTLE_DEV_MODE+` - usado para depurar o wrangler, nﾃ｣o utilizﾃ｡vel
* `+FLEET_BUNDLE_CREATION_MAX_CONCURRENCY+` - configura o nﾃｺmero de rotinas de criaﾃｧﾃ｣o de pacotes concorrentes para `+fleet apply+`. O padrﾃ｣o ﾃｩ 4. Tambﾃｩm pode ser definido via a flag CLI `+--bundle-creation-max-concurrency+`
* `+FLEET_CLUSTER_ENQUEUE_DELAY+` - ajusta com que frequﾃｪncia clusters nﾃ｣o prontos sﾃ｣o verificados
* `+FLEET_CPU_PPROF_PERIOD+` - usado para ativar https://github.com/rancher/fleet/blob/main/docs/performance.md[profiling de desempenho]

== Configuraﾃｧﾃ｣o

Na configuraﾃｧﾃ｣o do cluster para o agente e Fleet Manager. Alterar isso pode levar a reimplantaﾃｧﾃ｣o completa.

A configuraﾃｧﾃ｣o https://github.com/rancher/fleet/blob/main/internal/config/config.go#L57[struct] ﾃｩ usada em ambos os mapas de configuraﾃｧﾃ｣o:

* cattle-fleet-system/fleet-agent
* cattle-fleet-system/fleet-controller

== Rﾃｳtulos

Rﾃｳtulos usados pela Fleet:

* `+fleet.cattle.io/agent=true+` - rﾃｳtulo NodeSelector para configuraﾃｧﾃ｣o de afinidade de implantaﾃｧﾃ｣o do agente
* `+fleet.cattle.io/non-managed-agent+` - pacote de agente gerenciado nﾃ｣o direcionarﾃ｡ clusters com este rﾃｳtulo
* `+fleet.cattle.io/repo-name+` - usado no Bundle para referenciar o recurso do repositﾃｳrio git
* `+fleet.cattle.io/bundle-namespace+` - usado no BundleDeployment para referenciar o recurso do Bundle
* `+fleet.cattle.io/bundle-name+` - usado no BundleDeployment para referenciar o recurso do Bundle
* `+fleet.cattle.io/managed=true+` - namespaces de cluster com este rﾃｳtulo serﾃ｣o limpos. Outros recursos serﾃ｣o limpos se estiverem em um rﾃｳtulo. Usado no Rancher para identificar namespaces da Fleet.
* `+fleet.cattle.io/bootstrap-token+` - nﾃ｣o utilizado
* `+fleet.cattle.io/shard-id=<shard-id>+` - O ID da partiﾃｧﾃ｣o de um pod do Fleet controller.
* `+fleet.cattle.io/shard-default=true+` - verdadeiro se este for o controlador gerenciando recursos sem um rﾃｳtulo de referﾃｪncia de partiﾃｧﾃ｣o.
* `+fleet.cattle.io/shard-ref=<shard-id>+` - referencia o ID da partiﾃｧﾃ｣o atribuﾃｭdo por {product_name} aos recursos, herdado de um `+GitRepo+`, que determina qual implantaﾃｧﾃ｣o do controlador {product_name} irﾃ｡ reconciliﾃ｡-los.
 ** Se este rﾃｳtulo nﾃ｣o for fornecido ou tiver um valor vazio, entﾃ｣o o controlador {product_name} nﾃ｣o particionado processarﾃ｡ o recurso.
 ** Se este rﾃｳtulo tiver um valor que nﾃ｣o corresponda a nenhum ID de partiﾃｧﾃ｣o para o qual um controlador {product_name} estﾃ｡ implantado, entﾃ｣o o recurso nﾃ｣o serﾃ｡ processado.

== Anotaﾃｧﾃｵes

Anotaﾃｧﾃｵes usadas pela Fleet:

* `+fleet.cattle.io/agent-namespace+`
* `+fleet.cattle.io/bundle-id+`
* `+fleet.cattle.io/cluster+`, `+fleet.cattle.io/cluster-namespace+` - usado em um namespace de cluster para referenciar o namespace de registro do cluster e o nome do cluster
* `+fleet.cattle.io/cluster-group+`
* `+fleet.cattle.io/cluster-registration-namespace+`
* `+fleet.cattle.io/cluster-registration+`
* `+fleet.cattle.io/commit+`
* `+fleet.cattle.io/managed+` - aparece nﾃ｣o utilizado
* `+fleet.cattle.io/service-account+`

== {product_name} Configuraﾃｧﾃ｣o do agente

Tolerﾃ｢ncias, afinidade e recursos podem ser personalizados para o {product_name} agente. Esses campos podem ser fornecidos ao criar um xref:reference/ref-crds.adoc#_clusterspec[Cluster], veja xref:how-tos-for-operators/cluster-registration.adoc[Registrando Downstream Cluster] para mais informaﾃｧﾃｵes sobre como criar clusters. A configuraﾃｧﾃ｣o padrﾃ｣o serﾃ｡ utilizada se esses campos nﾃ｣o forem fornecidos.

Se vocﾃｪ alterar os limites de recursos, certifique-se de que os limites permitam que o Fleet agent funcione normalmente.

Tenha em mente que se vocﾃｪ rebaixar {product_name} para uma versﾃ｣o anterior ﾃ v0.7.0, {product_name} voltarﾃ｡ para os padrﾃｵes incorporados.
Os agentes serﾃ｣o reimplantados se tiverem afinidade personalizada. Se o nﾃｺmero da versﾃ｣o {product_name} nﾃ｣o mudar, a reimplantaﾃｧﾃ｣o pode nﾃ｣o ser imediata.
