= Test de performance de SUSE Observability Cluster
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Vue d'ensemble

Cette page propose une méthode pour établir le profil d'une grappe en cours d'exécution afin de vérifier qu'elle fonctionne conformément aux attentes. Cette fonction peut être utilisée en cas de dégradation des performances afin d'étudier activement le fonctionnement de plusieurs éléments. Il s'agit d'un complément au collecteur xref:/setup/install-stackstate/support-package-logs.adoc[Support Package (Logs)] pour la collecte des journaux en général.

== Notes

Le script doit être exécuté à partir d'un hôte sur lequel kubectl est configuré et qui a accès au cluster {stackstate-product-name} ou à partir de tout autre hôte disposant des autorisations nécessaires et de la connectivité au cluster.
Cela peut être fait directement sur l'hôte en utilisant l'utilisateur root ou via sudo. Si kubeconfig n'est pas défini, utilisez la commande `+export KUBECONFIG=$PATH-TO-YOUR/kubeconfig+`.

== Utilisation

Le script doit être téléchargé et exécuté directement sur l'hôte, en utilisant l'utilisateur `+root+` ou `+sudo+`.

=== Télécharger et exécuter le script

Téléchargez le script xref::attachment$suse-observability_performance_collector.sh[suse-observability_performance_collector.sh.] 

* Enregistrer le script sous : `+suse-observability_performance_collector.sh+`
* Exécutez le script à l'aide des commandes suivantes :
+
[,bash]
----
bash suse-observability_performance_collector.sh
----
+
Cela génère un fichier dans le répertoire actuel nommé `+suse-observability_performance_<date>.tar.gz+`. Téléchargez ce fichier dans le dossier.

Des arguments supplémentaires peuvent être spécifiés. Par exemple, pour choisir un espace de noms différent :
[,bash]
----
> bash suse-observability_performance_collector.sh -h
SUSE Observability performance measurement tool.
Runs some rudimentary performance tests on a deployed instance to validate performance.

Usage: $0 [options] [<namespace>]

options:
  -h  Print this help

<namespace>:
  The namespace that is running SUSE Observability, or
  "suse-observability" when not specified
----

== Performance de référence

Vous trouverez ci-dessous un résultat que nous utilisons comme référence pour les performances d'un système, et que nous utilisons également pour ajuster nos propres profils. Les disques et les vitesses des clients devraient s'approcher de ces chiffres.

----
=== SUSE Observability Performance Summary ===
Date: 2026-03-09T09:46:18Z

--- Hdfs Disk Buffered ---
  suse-observability-hbase-hdfs-dn-0                           151 MB/s
  suse-observability-hbase-hdfs-dn-1                           150 MB/s
  suse-observability-hbase-hdfs-dn-2                           150 MB/s

--- Hdfs Disk Direct ---
  suse-observability-hbase-hdfs-dn-0                           58.3 MB/s
  suse-observability-hbase-hdfs-dn-1                           56.6 MB/s
  suse-observability-hbase-hdfs-dn-2                           56.7 MB/s

--- Kafka Disk Buffered ---
  suse-observability-kafka-0                                   173 MB/s
  suse-observability-kafka-1                                   142 MB/s
  suse-observability-kafka-2                                   143 MB/s

--- Kafka Disk Direct ---
  suse-observability-kafka-0                                   59.2 MB/s
  suse-observability-kafka-1                                   59.2 MB/s
  suse-observability-kafka-2                                   59.4 MB/s

--- Kafka Producer Local ---
  suse-observability-kafka-0                                   50241.157556 records/sec (49.06 MB/sec), 557.44 ms avg latency
  suse-observability-kafka-1                                   31422.825540 records/sec (30.69 MB/sec), 903.49 ms avg latency
  suse-observability-kafka-2                                   31703.760066 records/sec (30.96 MB/sec), 893.00 ms avg latency

--- Kafka Producer Remote ---
  suse-observability-kafka-0                                   59765.718384 records/sec (58.36 MB/sec), 453.19 ms avg latency
  suse-observability-kafka-1                                   54656.755575 records/sec (53.38 MB/sec), 500.53 ms avg latency
  suse-observability-kafka-2                                   39503.831872 records/sec (38.58 MB/sec), 703.39 ms avg latency

--- Hdfs Network ---
  suse-observability-hbase-hdfs-dn-0 -> suse-observability-hbase-hdfs-dn-1 571 MB/s
  suse-observability-hbase-hdfs-dn-1 -> suse-observability-hbase-hdfs-dn-2 524 MB/s
  suse-observability-hbase-hdfs-dn-2 -> suse-observability-hbase-hdfs-dn-0 597 MB/s
----

Précisions :

- L'IO en mémoire tampon est liée au débit brut du disque, ce qui permet aux données d'être mises en mémoire tampon dans le noyau.
- Le disque direct mesure le débit du disque en utilisant O_DIRECT, sans tenir compte de la mise en mémoire tampon, ce qui se rapproche davantage de nos bases de données utilisant fsync() et donne un aperçu de la latence du stockage sous-jacent.
- Kafka Producer local met les données dans kafka sur localhost, à distance sur le réseau. La commande à distance peut être plus rapide que la commande locale lorsque l'unité centrale est le goulot d'étranglement plutôt que le réseau (ce qui était le cas ici, la commande à distance étant donc plus efficace).