include::partial$variables.adoc[]

= 代理配置
:description: 使用{project-name} 代理 .
:keywords: ["{project-name}", "kubewarden", "kubernetes", "proxy", "proxies"]
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-type: ["howto"]
:doc-topic: ["operator-manual", "proxy"]

对于`kwctl` 和`policy-server` ，您可以配置 HTTP 和 HTTPS 代理，也可以将域排除在代理配置之外。

您可以通过两种方式实现这一目标：* 为`kwctl` 或`policy-server` 设置环境变量`HTTP_PROXY`,`HTTPS_PROXY`,`NO_PROXY`（及其小写对应变量）。
  要配置 PolicyServer CR，请设置其`spec.env` 数组。* 通过`--sources-path` 参数提供`sources.yaml` 文件。
  `sources.yaml` 文件优先于环境变量。
  PolicyServer CR 中尚未公开通过`spec` 字段消耗此配置。

设置代理配置影响：

* 从 OCI 登记处拉出、推入和拉动并运行政策。
* 通过情境感知调用实现主机功能，例如
** 集装箱登记，如获取 OCI 清单或清单摘要。
   流量将通过配置的代理路由，而不是直接访问 OCI 注册表。
** Sigstore 功能，如验证无密钥签名。
   流量将通过配置的代理路由，而不是访问 Sigstore-defined 服务。

== 示例

您可以为`kwctl` 或`policy-server` （通过 PolicyServer`spec.env` ）设置以下环境变量：

[source,bash]
----
HTTP_PROXY="http://proxy.corp:3128"
https_proxy="http://proxy.corp:3129"
NO_PROXY="localhost,.corp"
----

使用这种配置：* 通过 HTTP 传输的不安全流量，如进出不安全 OCI 注册表的流量，通过`\http://proxy.corp:3128` 路由。
  这将影响拉取策略和调用上下文感知功能的策略，这些功能具有该资源库中容器的 OCI 映像清单摘要。* 通过 HTTPS 加密的流量将通过`\https://proxy.corp:3129` 路由。
  例如，这包括向任何安全的 OCI 注册表拉取和推送策略，以及所提及的策略上下文感知功能。* 往来于本地主机或`.corp` 下任何域的流量不受前面配置的限制。


== `sources.yaml` 文件

有关详细信息，请查阅 xref:/reference/sources_yaml.adoc[`sources.yaml`]参考资料。