include::partial$variables.adoc[]
= 原始政策
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 使用{project-name} 将原始策略配置为通用策略评估引擎。
:doc-persona: ["kubewarden-经销商"、"kubewarden-集成商"、"kubewarden-运营商"、"kubewarden-政策制定者"]
:doc-topic: ["kubewarden", "kubernetes", "raw-policies"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "support", "raw policies"]
:sidebar_label: 原始政策
:sidebar_position: 60
:current-version: {page-origin-branch}

从`v1.9.0` 开始，{project-name} 作为通用策略评估引擎，支持在 Kubernetes 集群之外编写和执行策略。
策略服务器提供`/validate_raw` 端点，可用于根据{short-project-name} 策略验证任意 JSON 文档。

在本指南中，我们将使用以下原始政策：

* https://github.com/kubewarden/raw-validation-policy[原始验证策略]
* https://github.com/kubewarden/raw-mutation-policy[原始突变策略]

[NOTE]
====
请确保政策作者已在元数据中将政策标记为`policyType: raw` 。
您可以使用 `kwctl`

[subs="+attributes",bash]
----
kwctl inspect ghcr.io/kubewarden/tests/raw-mutation-policy:v0.1.0
----
====


== 在 Kubernetes 外部运行策略服务器

策略服务器可以作为独立容器在 Kubernetes 外部运行。

首先，创建一个`policies.yml` 文件，内容如下：

[subs="+attributes",yaml]
----
raw-validation:
  module: ghcr.io/kubewarden/tests/raw-validation-policy:v0.1.0
  settings:
    validUsers:
      - alice
      - bob
    validActions:
      - read
      - write
    validResources:
      - orders
      - products

raw-mutation:
  module: ghcr.io/kubewarden/tests/raw-mutation-policy:v0.1.0
  allowedToMutate: true
  settings:
    forbiddenResources:
      - privateResource
      - secretResource
    defaultResource: publicResource
----

启动策略服务器：

[subs="+attributes",bash]
----
# Create a docker volume to store the policies
docker volume create --driver local \
                --opt type=tmpfs \
                --opt device=tmpfs \
                --opt o=ui=65533 \
                policy-store

# Start the policy server
docker run --rm -it \
    -p 3000:3000 \
    -v $(pwd)/policies.yml:/policies.yml \
    -v policy-store:/registry \
    ghcr.io/kubewarden/policy-server:1.9.0 \
    --ignore-kubernetes-connection-failure=true
----

NOTE: 要在不使用 Kubernetes 的情况下启动策略服务器，需要使用`--ignore-kubernetes-connection-failure=true` 作为标记。
不过，也可以在 Kubernetes 内部启动策略服务器，并使用原始验证端点。
原始策略可以像标准策略一样访问上下文xref:../explanations/context-aware-policies.adoc[感知]功能。

== 在没有{short-project-name} 控制器的情况下在 Kubernetes 内运行策略服务器

无法使用{short-project-name} 控制器管理的策略服务器实例来托管原始策略。
控制器不允许用户更改策略服务器配置表以添加原始策略，因为它会尝试对其进行调节，以恢复更改。
因此，必须启动专门的策略服务器。

创建`policy-server.yaml` 文件，内容如下：

[subs="+attributes",yaml]
----
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-server
  template:
    metadata:
      labels:
        app: policy-server
    spec:
      containers:
        - name: policy-server
          image: ghcr.io/kubewarden/policy-server:v1.9.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: policy-store
              mountPath: /registry
            - name: policies-config
              mountPath: /policies.yml
              subPath: policies.yml
      volumes:
        - name: policy-store
          emptyDir: {}
        - name: policies-config
          configMap:
            name: policies-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: policy-server-service
spec:
  selector:
    app: policy-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-configmap
data:
  policies.yml: |
    raw-validation:
      module: ghcr.io/kubewarden/tests/raw-validation-policy:v0.1.0
      settings:
        validUsers:
          - alice
          - bob
        validActions:
          - read
          - write
        validResources:
          - orders
          - products
    raw-mutation:
      module: ghcr.io/kubewarden/tests/raw-mutation-policy:v0.1.0
      allowedToMutate: true
      settings:
        forbiddenResources:
          - privateResource
          - secretResource
        defaultResource: publicResource
----

应用配置：

[subs="+attributes",bash]
----
kubectl apply -f policy-server.yaml
----

[IMPORTANT]
====
部署的策略服务器实例可以访问上下文感知策略可以使用的 Kubernetes 资源。
Kubernetes 资源的访问级别由用于运行策略服务器工作负载的服务账户决定。

在前面的示例中，部署规范中没有定义服务账户，因此将使用`default` 服务账户。
====


== 使用 validate_raw 端点

=== 验证

原始验证端点通过`/validate_raw` 公开，接受`POST` 请求。
既然我们已经部署了一项服务，就可以设置端口转发，通过`kubectl port-forward service/policy-server-service 3000:3000 -n default` 访问该服务。

让我们尝试根据`raw-validation` 策略验证 JSON 文档：

[subs="+attributes",bash]
----
curl -X POST \
  http://localhost:3000/validate_raw/raw-validation \
  -H 'Content-Type: application/json' \
  -d '{
  "request": {
    "user": "alice",
    "action": "read",
    "resource": "customers"
  }
}'
----

由于`alice` 尚未获准访问`customers` 资源，该请求将不被接受：

[subs="+attributes",json]
----
{
  "response": {
    "uid": "",
    "allowed": false,
    "auditAnnotations": null,
    "warnings": null
  }
}
----

让我们用有效的资源再试一次：

[subs="+attributes",bash]
----
curl -X POST \
  http://localhost:3000/validate_raw/raw-validation \
  -H 'Content-Type: application/json' \
  -d '{
  "request": {
    "user": "alice",
    "action": "read",
    "resource": "orders"
  }
}'
----

这一次，请求将被接受：

[subs="+attributes",json]
----
{
  "response": {
    "uid": "",
    "allowed": true,
    "auditAnnotations": null,
    "warnings": null
  }
}
----

[NOTE]
====
如果在请求有效载荷中提供了`uid` 字段，它将作为响应的一部分返回。
====


=== 突变

现在，让我们尝试根据`raw-mutation` 策略对 JSON 文档进行变异：

[subs="+attributes",bash]
----
curl -X POST \
  http://localhost:3000/validate_raw/raw-mutation \
  -H 'Content-Type: application/json' \
  -d '{
  "request": {
    "user": "alice",
    "action": "read",
    "resource": "privateResource"
  }
}'
----

请求将被更改，响应将包含一个 JSONPatch：

[subs="+attributes",json]
----
{
  "response": {
    "uid": "",
    "allowed": true,
    "patchType": "JSONPatch",
    "patch": "W3sib3AiOiJyZXBsYWNlIiwicGF0aCI6Ii9yZXNvdXJjZSIsInZhbHVlIjoicHVibGljUmVzb3VyY2UifV0=",
    "auditAnnotations": null,
    "warnings": null
  }
}
----

== 编写原始政策

与验证 Kubernetes 资源的策略类似，原始策略也是使用{short-project-name} SDK 在 WebAssembly 中编写的。
如果您有兴趣编写原始策略，请参阅特定语言的文档以获取更多信息：

* xref:../tutorials/writing-policies/go/10-raw-policies.adoc[转到]
* xref:../tutorials/writing-policies/rust/08-raw-policies.adoc[生锈]
* xref:../tutorials/writing-policies/rego/open-policy-agent/05-raw-policies.adoc[邮政管理处]
* xref:../tutorials/writing-policies/wasi/02-raw-policies.adoc[WASI]
