// This file was converted from Markdown to AsciiDoc.

include::partial$variables.adoc[]
= CLI do kwctl
:revdate: 2026-03-18
:page-revdate: {revdate}
:title: CLI do kwctl
:description: Explore a ferramenta de linha de comando \`kwctl` para gerenciar as políticas do {project-name} e executar tarefas como carregar políticas.
:keywords: cli, referência, kwctl
:doc-persona: operador de cubículo
:doc-type: referência
:doc-topic: operator-manual

== Ajuda da linha de comando para `kwctl`

Este documento contém o conteúdo da ajuda do programa de linha de comando `kwctl`.

*Visão geral do comando:*

* <<kwctl,`kwctl`>>
* <<kwctl-annotate,`kwctl annotate`>>
* <<kwctl-bench,`kwctl bench`>>
* <<kwctl-completions,`kwctl completions`>>
* <<kwctl-digest,`kwctl digest`>>
* <<kwctl-docs,`kwctl docs`>>
* <<kwctl-info,`kwctl info`>>
* <<kwctl-inspect,`kwctl inspect`>>
* <<kwctl-load,`kwctl load`>>
* <<kwctl-policies,`kwctl policies`>>
* <<kwctl-pull,`kwctl pull`>>
* <<kwctl-push,`kwctl push`>>
* <<kwctl-rm,`kwctl rm`>>
* <<kwctl-run,`kwctl run`>>
* <<kwctl-save,`kwctl save`>>
* <<kwctl-scaffold,`kwctl scaffold`>>
* <<kwctl-scaffold-admission-request,`kwctl scaffold admission-request`>>
* <<kwctl-scaffold-artifacthub,`kwctl scaffold artifacthub`>>
* <<kwctl-scaffold-manifest,`kwctl scaffold manifest`>>
* <<kwctl-scaffold-vap,`kwctl scaffold vap`>>
* <<kwctl-scaffold-verification-config,`kwctl scaffold verification-config`>>
* <<kwctl-verify,`kwctl verify`>>

[[kwctl]]
=== `kwctl`

Ferramenta para gerenciar as políticas do {project-name} 

*Uso:* `kwctl [OPTIONS] <COMMAND>`

==== Subcomandos

* `annotate` - Adicionar metadados do {short-project-name} a um módulo do WebAssembly
* `bench` - Benchmarks a {short-project-name} policy
* `completions` - Gerar conclusões de shell
* `digest` - Obter resumo do manifesto OCI de uma política
* `docs` - Gera a documentação markdown para os comandos kwctl
* `info` - Exibir informações do sistema
* `inspect` - Inspecione a política do site {short-project-name} 
* `load` - carregar políticas de um arquivo tar.gz
* `policies` - Lista todas as políticas baixadas
* `pull` - Extrai uma política {short-project-name} de um determinado URI
* `push` - Envia uma política de {short-project-name} para um registro de OCI
* `rm` - Remove uma política de {short-project-name} do armazenamento
* `run` - Executa uma política {short-project-name} a partir de um determinado URI
* `save` - salvar políticas em um arquivo tar.gz
* `scaffold` - Scaffold de um recurso ou arquivo de configuração do Kubernetes
* `verify` - Verificar uma política de {short-project-name} a partir de um determinado URI usando Sigstore

==== Opções

* `-v`, `--verbose <VERBOSE>` - Aumentar a verbosidade
* `--no-color <NO-COLOR>` - Desativar a saída colorida

[[kwctl-annotate]]
=== `kwctl annotate`

Adicionar metadados do {short-project-name} a um módulo do WebAssembly

*Uso:* `kwctl annotate [OPTIONS] --metadata-path <PATH> --output-path <PATH> <wasm-path>`

==== Argumentos

* `<WASM-PATH>` - Caminho para o módulo do WebAssembly a ser anotado

==== Opções

* `-m`, `--metadata-path <PATH>` - Arquivo que contém os metadados
* `-o`, `--output-path <PATH>` - Arquivo de saída
* `-u`, `--usage-path <PATH>` - Arquivo que contém as informações de uso da política

[[kwctl-bench]]
=== `kwctl bench`

Referenciais de uma política {short-project-name}.

A política pode ser especificada das seguintes maneiras:- URI: por exemplo, `registry://ghcr.io/kubewarden/policies/psp-policy:latest` ou `\https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm`- Prefixo SHA: por exemplo, `c3b80a10f9c3` (requer que a política já tenha sido extraída) - Arquivo WASM local: por exemplo, `file://home/tux/new-policy/psp-policy.wasm`- Arquivo YAML local: por exemplo, `file://home/tux/cluster-admission-policy.yaml` (contém declarações de {short-project-name} Recursos personalizados como `ClusterAdmissionPolicy`, `AdmissionPolicy`, etc.)

Comportamento padrão:
Se o esquema for omitido, será assumido o endereço `file://`, com raiz no diretório atual.

Observações sobre {short-project-name} Recursos personalizados:- Os sinalizadores `--request-path`, `--settings-path` e `--settings-json` são ignorados; as configurações são lidas na definição do recurso personalizado.- O sinalizador `--execution-mode` aplica-se a todas as políticas no arquivo YAML.- O sinalizador `--raw` não pode ser usado, pois os recursos personalizados do {short-project-name} não são compatíveis com as políticas do `raw`.

Somente os seguintes atributos da Definição de Recurso Personalizado (CRD) são avaliados:- Módulo de política - Configurações de política - Recursos com reconhecimento de contexto que a política pode acessar

Outros campos, como `rules`, `matchConditions`, `objectSelector` e `namespaceSelector`, são ignorados.

Um arquivo YAML pode conter várias declarações de recursos personalizados. Nesse caso, o site `kwctl` avalia cada política no arquivo usando a mesma solicitação durante cada avaliação.

*Uso:* `kwctl bench [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>`

==== Argumentos

* `<URI_OR_SHA_PREFIX_OR_YAML_FILE>` - URI de política, prefixo SHA ou arquivo YAML contendo recursos de política do {short-project-name}. Esquemas compatíveis: registry://, https://, file://. Se o esquema for omitido, será assumido file://, com base no diretório atual.

==== Opções

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Conceda acesso aos recursos do Kubernetes definidos dentro da seção `contextAwareResources` da política. Aviso: analise a lista de recursos cuidadosamente para evitar abusos. Desativado por padrão
* `--cert-email <VALUE>` - E-mail esperado no certificado Fulcio
* `--cert-oidc-issuer <VALUE>` - Emissor de OIDC esperado em certificados Fulcio
* `--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>` - Desativar o uso do cache do wasmtime
* `--docker-config-json-path <PATH>` - Caminho para um diretório que contém o arquivo "config.json" do Docker. Pode ser usado para indicar detalhes de autenticação do registro
* `--dump-results-to-disk <DUMP_RESULTS_TO_DISK>` - Coloca os resultados em target/tiny-bench/label/\... se o destino puder ser encontrado. usado para comparar execuções anteriores
* `-e`, `--execution-mode <MODE>` - O tempo de execução a ser usado para executar essa política +
  Valores possíveis: `opa`, `gatekeeper`, `kubewarden`, `wasi`
* `--github-owner <VALUE>` - Proprietário do GitHub esperado nos certificados gerados nos pipelines de CD
* `--github-repo <VALUE>` - Repositório do GitHub esperado nos certificados gerados nos pipelines de CD
* `--measurement-time <SECONDS>` - Por quanto tempo o banco "deve" ser executado, num_samples é priorizado, de modo que o banco levará mais tempo para coletar num_samples se o código a ser avaliado for mais lento do que esse limite de tempo permitido
* `--num-resamples <NUM>` - Quantas reamostras devem ser feitas
* `--num-samples <NUM>` - Quantas reamostras devem ser feitas. Recomendado pelo menos 50, acima de 100 não parece produzir um resultado significativamente diferente
* `--raw <RAW>` - Validar uma solicitação bruta +
  Valor padrão: `false`
* `--record-host-capabilities-interactions <FILE>` - Registra todas as comunicações de recursos de política e host no arquivo fornecido. Útil para ser combinado posteriormente com o sinalizador '--replay-host-capabilities-interactions'
* `--replay-host-capabilities-interactions <FILE>` - Durante as trocas de recursos de política e host, o host reproduz as respostas encontradas no arquivo fornecido. Isso é útil para testar políticas de forma reproduzível, uma vez que não são realizadas interações externas com registros de OCI, DNS e Kubernetes.
* `-r`, `--request-path <PATH>` - Arquivo que contém o objeto de solicitação de admissão do Kubernetes no formato JSON
* `--settings-json <VALUE>` - Cadeia de caracteres JSON contendo as configurações para essa política
* `-s`, `--settings-path <PATH>` - Arquivo que contém as configurações para essa política
* `--sigstore-trust-config <PATH>` - Arquivo formatado em JSON em conformidade com a mensagem ClientTrustConfig nas especificações do Sigstore protobuf. Esse arquivo configura todo o estado da instância do Sigstore, incluindo os URIs usados para acessar a CA e os serviços de transparência de artefatos, bem como a própria raiz criptográfica de confiança
* `--sources-path <PATH>` - Arquivo YAML que contém informações de origem (https, hosts inseguros de registro, CAs personalizadas...)
* `-a`, `--verification-annotation <KEY=VALUE>` - Anotação no formato chave=valor. Pode ser repetido várias vezes
* `--verification-config-path <PATH>` - Arquivo YAML que contém informações de configuração de verificação (assinaturas, chaves públicas...)
* `-k`, `--verification-key <PATH>` - Caminho para a chave usada para verificar a política. Pode ser repetido várias vezes
* `--warm-up-time <SECONDS>` - Quanto tempo o banco deve aquecer

[[kwctl-completions]]
=== `kwctl completions`

Gerar conclusões de shell

*Uso:* `kwctl completions --shell <VALUE>`

==== Opções

* `-s`, `--shell <VALUE>` - Tipo de concha +
  Valores possíveis: `bash`, `elvish`, `fish`, `powershell`, `zsh`

[[kwctl-digest]]
=== `kwctl digest`

Obter resumo do manifesto OCI de uma política

*Uso:* `kwctl digest [OPTIONS] <uri>`

==== Argumentos

* `<URI>` - URI da política

==== Opções

* `--docker-config-json-path <PATH>` - Caminho para um diretório que contém o arquivo "config.json" do Docker. Pode ser usado para indicar detalhes de autenticação do registro
* `--sources-path <PATH>` - Arquivo YAML que contém informações de origem (https, hosts inseguros de registro, CAs personalizadas...)

[[kwctl-docs]]
=== `kwctl docs`

Gera a documentação markdown para os comandos kwctl

*Uso:* `kwctl docs --output <FILE>`

==== Opções

* `-o`, `--output <FILE>` - caminho onde o arquivo de documentação será armazenado

[[kwctl-info]]
=== `kwctl info`

Exibir informações do sistema

*Uso:* `kwctl info`

[[kwctl-inspect]]
=== `kwctl inspect`

Inspecione a política do site {short-project-name} 

*Uso:* `kwctl inspect [OPTIONS] <uri_or_sha_prefix>`

==== Argumentos

* `<URI_OR_SHA_PREFIX>` - URI da política ou prefixo SHA. Esquemas compatíveis: registry://, https://, file://. Se o esquema for omitido, será assumido file://, com base no diretório atual.

==== Opções

* `--docker-config-json-path <PATH>` - Caminho para um diretório que contém o arquivo "config.json" do Docker. Pode ser usado para indicar detalhes de autenticação do registro
* `-o`, `--output <FORMAT>` - Formato de saída +
  Valores possíveis: `yaml`
* `--show-signatures <SHOW-SIGNATURES>` - Mostrar assinaturas da sigstore
* `--sources-path <PATH>` - Arquivo YAML que contém informações de origem (https, hosts inseguros de registro, CAs personalizadas...)

[[kwctl-load]]
=== `kwctl load`

carregar políticas de um arquivo tar.gz

*Uso:* `kwctl load --input <input>`

==== Opções

* `--input <INPUT>` - carregar políticas do tarball

[[kwctl-policies]]
=== `kwctl policies`

Lista todas as políticas baixadas

*Uso:* `kwctl policies`

[[kwctl-pull]]
=== `kwctl pull`

Extrai uma política {short-project-name} de um determinado URI

*Uso:* `kwctl pull [OPTIONS] <uri>`

==== Argumentos

* `<URI>` - URI da política. Esquemas suportados: registry://, https://, file://

==== Opções

* `--cert-email <VALUE>` - E-mail esperado no certificado Fulcio
* `--cert-oidc-issuer <VALUE>` - Emissor de OIDC esperado em certificados Fulcio
* `--docker-config-json-path <DOCKER_CONFIG>` - Caminho para um diretório que contém o arquivo "config.json" do Docker. Pode ser usado para indicar detalhes de autenticação do registro
* `--github-owner <VALUE>` - Proprietário do GitHub esperado nos certificados gerados nos pipelines de CD
* `--github-repo <VALUE>` - Repositório do GitHub esperado nos certificados gerados nos pipelines de CD
* `-o`, `--output-path <PATH>` - Arquivo de saída. Se não for fornecido, o download será feito no repositório {short-project-name} 
* `--sigstore-trust-config <PATH>` - Arquivo formatado em JSON em conformidade com a mensagem ClientTrustConfig nas especificações do Sigstore protobuf. Esse arquivo configura todo o estado da instância do Sigstore, incluindo os URIs usados para acessar a CA e os serviços de transparência de artefatos, bem como a própria raiz criptográfica de confiança
* `--sources-path <PATH>` - Arquivo YAML que contém informações de origem (https, hosts inseguros de registro, CAs personalizadas...)
* `-a`, `--verification-annotation <KEY=VALUE>` - Anotação no formato chave=valor. Pode ser repetido várias vezes
* `--verification-config-path <PATH>` - Arquivo YAML que contém informações de configuração de verificação (assinaturas, chaves públicas...)
* `-k`, `--verification-key <PATH>` - Caminho para a chave usada para verificar a política. Pode ser repetido várias vezes

[[kwctl-push]]
=== `kwctl push`

Envia uma política de {short-project-name} para um registro de OCI

*Uso:* `kwctl push [OPTIONS] <policy> <uri>`

As anotações encontradas dentro dos metadados da política farão parte do manifesto da OCI.
As anotações de várias linhas são ignoradas porque não são compatíveis com a especificação OCI.
A anotação "io.kubewarden.policy.source" é propagada como "org.opencontainers.image.source" para permitir que ferramentas como o renovatebot detectem atualizações de políticas.

==== Argumentos

* `<POLICY>` - Política a ser promovida. Pode ser o caminho para um arquivo local, um URI de política ou o prefixo SHA de uma política no armazenamento.
* `<URI>` - URI da política. Esquemas suportados: registry://

==== Opções

* `--docker-config-json-path <PATH>` - Caminho para um diretório que contém o arquivo "config.json" do Docker. Pode ser usado para indicar detalhes de autenticação do registro
* `-f`, `--force <FORCE>` - Empurre também uma política que não esteja anotada
* `-o`, `--output <PATH>` - Formato de saída +
  Valor padrão: `text` +
  Valores possíveis: `text`, `json`
* `--sources-path <PATH>` - Arquivo YAML que contém informações de origem (https, hosts inseguros de registro, CAs personalizadas...)

[[kwctl-rm]]
=== `kwctl rm`

Remove uma política de {short-project-name} do armazenamento

*Uso:* `kwctl rm <uri_or_sha_prefix>`

==== Argumentos

* `<URI_OR_SHA_PREFIX>` - URI de política ou prefixo SHA

[[kwctl-run]]
=== `kwctl run`

Execute uma ou mais políticas do {short-project-name} localmente.

A política pode ser especificada das seguintes maneiras:- URI: por exemplo, `registry://ghcr.io/kubewarden/policies/psp-policy:latest` ou `https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm`- Prefixo SHA: por exemplo, `c3b80a10f9c3` (requer que a política já tenha sido extraída) - Arquivo WASM local: por exemplo, `file://home/tux/new-policy/psp-policy.wasm`- Arquivo YAML local: por exemplo, `file://home/tux/cluster-admission-policy.yaml` (contém declarações de {short-project-name} Recursos personalizados como `ClusterAdmissionPolicy`, `AdmissionPolicy`, etc.)

Comportamento padrão:
Se o esquema for omitido, será assumido o endereço `file://`, com raiz no diretório atual.

Observações sobre {short-project-name} Recursos personalizados:- Os sinalizadores `--request-path`, `--settings-path` e `--settings-json` são ignorados; as configurações são lidas na definição do recurso personalizado.- O sinalizador `--execution-mode` aplica-se a todas as políticas no arquivo YAML.- O sinalizador `--raw` não pode ser usado, pois os recursos personalizados do {short-project-name} não são compatíveis com as políticas do `raw`.

Somente os seguintes atributos da Definição de Recurso Personalizado (CRD) são avaliados:- Módulo de política - Configurações de política - Recursos com reconhecimento de contexto que a política pode acessar

Outros campos, como `rules`, `matchConditions`, `objectSelector` e `namespaceSelector`, são ignorados.

Um arquivo YAML pode conter várias declarações de recursos personalizados. Nesse caso, o site `kwctl` avalia cada política no arquivo usando a mesma solicitação durante cada avaliação.

*Uso:* `kwctl run [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>`

==== Argumentos

* `<URI_OR_SHA_PREFIX_OR_YAML_FILE>` - URI de política, prefixo SHA ou arquivo YAML contendo recursos de política do {short-project-name}. Esquemas compatíveis: registry://, https://, file://. Se o esquema for omitido, será assumido file://, com base no diretório atual.

==== Opções

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Conceda acesso aos recursos do Kubernetes definidos dentro da seção `contextAwareResources` da política. Aviso: analise a lista de recursos cuidadosamente para evitar abusos. Desativado por padrão
* `--cert-email <VALUE>` - E-mail esperado no certificado Fulcio
* `--cert-oidc-issuer <VALUE>` - Emissor de OIDC esperado em certificados Fulcio
* `--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>` - Desativar o uso do cache do wasmtime
* `--docker-config-json-path <PATH>` - Caminho para um diretório que contém o arquivo "config.json" do Docker. Pode ser usado para indicar detalhes de autenticação do registro
* `-e`, `--execution-mode <MODE>` - O tempo de execução a ser usado para executar essa política +
  Valores possíveis: `opa`, `gatekeeper`, `kubewarden`, `wasi`
* `--github-owner <VALUE>` - Proprietário do GitHub esperado nos certificados gerados nos pipelines de CD
* `--github-repo <VALUE>` - Repositório do GitHub esperado nos certificados gerados nos pipelines de CD
* `--raw <RAW>` - Validar uma solicitação bruta +
  Valor padrão: `false`
* `--record-host-capabilities-interactions <FILE>` - Registra todas as comunicações de recursos de política e host no arquivo fornecido. Útil para ser combinado posteriormente com o sinalizador '--replay-host-capabilities-interactions'
* `--replay-host-capabilities-interactions <FILE>` - Durante as trocas de recursos de política e host, o host reproduz as respostas encontradas no arquivo fornecido. Isso é útil para testar políticas de forma reproduzível, uma vez que não são realizadas interações externas com registros de OCI, DNS e Kubernetes.
* `-r`, `--request-path <PATH>` - Arquivo que contém o objeto de solicitação de admissão do Kubernetes no formato JSON
* `--settings-json <VALUE>` - Cadeia de caracteres JSON contendo as configurações para essa política
* `-s`, `--settings-path <PATH>` - Arquivo que contém as configurações para essa política
* `--sigstore-trust-config <PATH>` - Arquivo formatado em JSON em conformidade com a mensagem ClientTrustConfig nas especificações do Sigstore protobuf. Esse arquivo configura todo o estado da instância do Sigstore, incluindo os URIs usados para acessar a CA e os serviços de transparência de artefatos, bem como a própria raiz criptográfica de confiança
* `--sources-path <PATH>` - Arquivo YAML que contém informações de origem (https, hosts inseguros de registro, CAs personalizadas...)
* `-a`, `--verification-annotation <KEY=VALUE>` - Anotação no formato chave=valor. Pode ser repetido várias vezes
* `--verification-config-path <PATH>` - Arquivo YAML que contém informações de configuração de verificação (assinaturas, chaves públicas...)
* `-k`, `--verification-key <PATH>` - Caminho para a chave usada para verificar a política. Pode ser repetido várias vezes

[[kwctl-save]]
=== `kwctl save`

salvar políticas em um arquivo tar.gz

*Uso:* `kwctl save --output <FILE> <policies>...`

==== Argumentos

* `<POLICIES>` - lista de políticas a serem salvas

==== Opções

* `-o`, `--output <FILE>` - caminho onde o arquivo será armazenado

[[kwctl-scaffold]]
=== `kwctl scaffold`

Scaffold de um recurso ou arquivo de configuração do Kubernetes

*Uso:* `kwctl scaffold <COMMAND>`

==== Subcomandos

* `admission-request` - Scaffold de um objeto AdmissionRequest
* `artifacthub` - Gerar um arquivo artifacthub-pkg.yml a partir de um arquivo metadata.yml
* `manifest` - Saída de um manifesto de recursos do Kubernetes
* `vap` - Converta um Kubernetes `ValidatingAdmissionPolicy` em um {short-project-name} `ClusterAdmissionPolicy`
* `verification-config` - Saída de um arquivo de configuração de verificação Sigstore padrão

[[kwctl-scaffold-admission-request]]
=== `kwctl scaffold admission-request`

Scaffold de um objeto AdmissionRequest

*Uso:* `kwctl scaffold admission-request [OPTIONS] --operation <TYPE>`

==== Opções

* `--object <PATH>` - O arquivo que contém o novo objeto que está sendo admitido
* `--old-object <PATH>` - O arquivo que contém o objeto existente
* `-o`, `--operation <TYPE>` - {short-project-name} Tipo de recurso personalizado +
  Valores possíveis: `CREATE`

[[kwctl-scaffold-artifacthub]]
=== `kwctl scaffold artifacthub`

Gerar um arquivo artifacthub-pkg.yml a partir de um arquivo metadata.yml

*Uso:* `kwctl scaffold artifacthub [OPTIONS]`

==== Opções

* `-m`, `--metadata-path <PATH>` - Arquivo que contém os metadados da política
* `-o`, `--output <FILE>` - Caminho onde o arquivo artifact-pkg.yml será armazenado
* `-q`, `--questions-path <PATH>` - Arquivo que contém o conteúdo das perguntas-ui da política
* `-v`, `--version <VALUE>` - Versão semver da política

[[kwctl-scaffold-manifest]]
=== `kwctl scaffold manifest`

Saída de um manifesto de recursos do Kubernetes

*Uso:* `kwctl scaffold manifest [OPTIONS] --type <VALUE> <uri_or_sha_prefix>`

==== Argumentos

* `<URI_OR_SHA_PREFIX>` - URI da política ou prefixo SHA. Esquemas compatíveis: registry://, https://, file://. Se o esquema for omitido, será assumido file://, com base no diretório atual.

==== Opções

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Usa os metadados da política para definir quais recursos do Kubernetes podem ser acessados pela política. Aviso: analise a lista de recursos cuidadosamente para evitar abusos. Desativado por padrão
* `--cert-email <VALUE>` - E-mail esperado no certificado Fulcio
* `--cert-oidc-issuer <VALUE>` - Emissor de OIDC esperado em certificados Fulcio
* `--docker-config-json-path <DOCKER_CONFIG>` - Caminho para um diretório que contém o arquivo "config.json" do Docker. Pode ser usado para indicar detalhes de autenticação do registro
* `--fulcio-cert-path <PATH>` - Caminho para o certificado Fulcio. Pode ser repetido várias vezes
* `--github-owner <VALUE>` - Proprietário do GitHub esperado nos certificados gerados nos pipelines de CD
* `--github-repo <VALUE>` - Repositório do GitHub esperado nos certificados gerados nos pipelines de CD
* `--rekor-public-key-path <PATH>` - Caminho para a chave pública do Rekor. Pode ser repetido várias vezes
* `--settings-json <VALUE>` - Cadeia de caracteres JSON contendo as configurações para essa política
* `-s`, `--settings-path <PATH>` - Arquivo que contém as configurações para essa política
* `--sigstore-trust-config <PATH>` - Arquivo formatado em JSON em conformidade com a mensagem ClientTrustConfig nas especificações do Sigstore protobuf. Esse arquivo configura todo o estado da instância do Sigstore, incluindo os URIs usados para acessar a CA e os serviços de transparência de artefatos, bem como a própria raiz criptográfica de confiança
* `--sources-path <PATH>` - Arquivo YAML que contém informações de origem (https, hosts inseguros de registro, CAs personalizadas...)
* `--title <VALUE>` - Título da política
* `-t`, `--type <VALUE>` - {short-project-name} Tipo de recurso personalizado +
  Valores possíveis: `ClusterAdmissionPolicy`, `AdmissionPolicy`
* `-a`, `--verification-annotation <KEY=VALUE>` - Anotação no formato chave=valor. Pode ser repetido várias vezes
* `--verification-config-path <PATH>` - Arquivo YAML que contém informações de configuração de verificação (assinaturas, chaves públicas...)
* `-k`, `--verification-key <PATH>` - Caminho para a chave usada para verificar a política. Pode ser repetido várias vezes

[[kwctl-scaffold-vap]]
=== `kwctl scaffold vap`

Converta um Kubernetes `ValidatingAdmissionPolicy` em um {short-project-name} `ClusterAdmissionPolicy`

*Uso:* `kwctl scaffold vap [OPTIONS] --binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml> --policy <VALIDATING-ADMISSION-POLICY.yaml>`

==== Opções

* `-b`, `--binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml>` - O arquivo que contém a definição de ValidatingAdmissionPolicyBinding
* `--cel-policy <URI>` - O módulo de política CEL a ser usado +
  Valor padrão: `ghcr.io/kubewarden/policies/cel-policy:latest`
* `-p`, `--policy <VALIDATING-ADMISSION-POLICY.yaml>` - O arquivo que contém a definição de ValidatingAdmissionPolicy

[[kwctl-scaffold-verification-config]]
=== `kwctl scaffold verification-config`

Saída de um arquivo de configuração de verificação Sigstore padrão

*Uso:* `kwctl scaffold verification-config`

[[kwctl-verify]]
=== `kwctl verify`

Verificar uma política de {short-project-name} a partir de um determinado URI usando Sigstore

*Uso:* `kwctl verify [OPTIONS] <uri>`

==== Argumentos

* `<URI>` - URI da política. Esquemas suportados: registry://

==== Opções

* `--cert-email <VALUE>` - E-mail esperado no certificado Fulcio
* `--cert-oidc-issuer <VALUE>` - Emissor de OIDC esperado em certificados Fulcio
* `--docker-config-json-path <PATH>` - Caminho para um diretório que contém o arquivo "config.json" do Docker. Pode ser usado para indicar detalhes de autenticação do registro
* `--github-owner <VALUE>` - Proprietário do GitHub esperado nos certificados gerados nos pipelines de CD
* `--github-repo <VALUE>` - Repositório do GitHub esperado nos certificados gerados nos pipelines de CD
* `--sigstore-trust-config <PATH>` - Arquivo formatado em JSON em conformidade com a mensagem ClientTrustConfig nas especificações do Sigstore protobuf. Esse arquivo configura todo o estado da instância do Sigstore, incluindo os URIs usados para acessar a CA e os serviços de transparência de artefatos, bem como a própria raiz criptográfica de confiança
* `--sources-path <PATH>` - Arquivo YAML que contém informações de origem (https, hosts inseguros de registro, CAs personalizadas...)
* `-a`, `--verification-annotation <KEY=VALUE>` - Anotação no formato chave=valor. Pode ser repetido várias vezes
* `--verification-config-path <PATH>` - Arquivo YAML que contém informações de configuração de verificação (assinaturas, chaves públicas...)
* `-k`, `--verification-key <PATH>` - Caminho para a chave usada para verificar a política. Pode ser repetido várias vezes

'''

Este documento foi gerado automaticamente pelo https://crates.io/crates/clap-markdown[`clap-markdown`].
