:sidebar_label: ReferĂŞncia da CLI do servidor de polĂ­ticas
:sidebar_position: 121
:title: CLI do servidor de polĂ­ticas
:description: Explore a ajuda e as opĂ§Ăľes da linha de comando do policy-server para personalizar e executar o programa \`policy-server`.
:keywords: [cli, referĂŞncia, servidor de polĂ­ticas]
:doc-persona: [kubewarden-operator]
:doc-type: [referĂŞncia].
:doc-topic: [operator-manual]
include::partial$variables.adoc[]
:revdate: 2026-03-18
:page-revdate: {revdate}

= {title}

== Ajuda da linha de comando para `policy-server`

Este documento contĂŠm o conteĂşdo da ajuda do programa de linha de comando `policy-server`.

*VisĂŁo geral do comando:*

* link:#policy-server[`policy-server`]
* link:#policy-server-docs[`policy-server docs`]

=== `policy-server`

*Uso:* `policy-server ++[+OPTIONS+]++ ++[+COMMAND+]++`

==== *Subcomandos:*

* `docs` - Gera a documentaĂ§ĂŁo markdown para os comandos do servidor de polĂ­ticas

==== *OpĂ§Ăľes:*

* `--addr ++<+BIND_ADDRESS+>++` - Vincular ao ADDRESS
+
Valor padrĂŁo: `0.0.0.0`
* `--always-accept-admission-reviews-on-namespace ++<+NAMESPACE+>++` - Sempre aceite AdmissionReviews que tenham como alvo o namespace fornecido
* `--cert-file ++<+CERT_FILE+>++` - Caminho para um arquivo de certificado X.509 para HTTPS
* `--client-ca-file ++<+CLIENT_CA_FILE+>++` - Caminho para um arquivo de certificado de CA que emitiu o certificado do cliente. NecessĂĄrio para ativar o mTLS
* `--daemon` - Se definido, executa o policy-server no modo desconectado como um daemon
* `--daemon-pid-file ++<+DAEMON-PID-FILE+>++` - Caminho para o arquivo PID, usado somente durante a execuĂ§ĂŁo no modo daemon
+
Valor padrĂŁo: `policy-server.pid`
* `--daemon-stderr-file ++<+DAEMON-STDERR-FILE+>++` - Caminho para o arquivo que contĂŠm o stderr, usado somente quando executado no modo daemon
* `--daemon-stdout-file ++<+DAEMON-STDOUT-FILE+>++` - Caminho para o arquivo que contĂŠm o stdout, usado somente quando executado no modo daemon
* `--disable-timeout-protection` - Desativar a proteĂ§ĂŁo de tempo limite da polĂ­tica
* `--docker-config-json-path ++<+DOCKER_CONFIG+>++` - Caminho para um caminho semelhante ao config.json do Docker. Pode ser usado para indicar detalhes de autenticaĂ§ĂŁo do registro
* `--enable-metrics` - Ativar mĂŠtricas
* `--enable-pprof` - Ativar a criaĂ§ĂŁo de perfil pprof
* `--ignore-kubernetes-connection-failure` - NĂŁo saia com um erro se a conexĂŁo com o Kubernetes falhar. Isso farĂĄ com que as polĂ­ticas com reconhecimento de contexto sejam interrompidas quando nĂŁo houver conexĂŁo com o Kubernetes.
* `--key-file ++<+KEY_FILE+>++` - Caminho para um arquivo de chave privada X.509 para HTTPS
* `--log-fmt ++<+LOG_FMT+>++` - Formato de saĂ­da de registro
+
Valor padrĂŁo: `text`
+
Valores possĂ­veis: `text`, `json`, `otlp`
* `--log-level ++<+LOG_LEVEL+>++` - NĂ­vel de registro
+
Valor padrĂŁo: `info`
+
Valores possĂ­veis: `trace`, `debug`, `info`, `warn`, `error`
* `--log-no-color` - Desativar a saĂ­da colorida para os registros
* `--policies ++<+POLICIES_FILE+>++` - Arquivo YAML que contĂŠm as polĂ­ticas a serem carregadas e suas configuraĂ§Ăľes
+
Valor padrĂŁo: `policies.yml`
* `--policies-download-dir ++<+POLICIES_DOWNLOAD_DIR+>++` - Caminho de download das polĂ­ticas
+
Valor padrĂŁo: `.`
* `--policy-timeout ++<+MAXIMUM_EXECUTION_TIME_SECONDS+>++`
- Interromper a avaliaĂ§ĂŁo da polĂ­tica apĂłs o tempo determinado
+
Valor padrĂŁo: `2`
* `--port ++<+PORT+>++` - OuĂ§a no PORT
+
Valor padrĂŁo: `3000`
* `--readiness-probe-port ++<+READINESS_PROBE_PORT+>++` â
Expose readiness endpoint on READINESS+_PROBE_+PORT
+
Valor padrĂŁo: `8081`
* `--sigstore-cache-dir ++<+SIGSTORE_CACHE_DIR+>++` - DiretĂłrio usado para armazenar em cache os dados do sigstore
+
Valor padrĂŁo: `sigstore-data`
* `--sources-path ++<+SOURCES_PATH+>++` - Arquivo YAML que contĂŠm informaĂ§Ăľes de origem (https, hosts inseguros de registro, CAs personalizadas\...)
* `--verification-path ++<+VERIFICATION_CONFIG_PATH+>++` - Arquivo YAML que contĂŠm informaĂ§Ăľes de verificaĂ§ĂŁo (URIs, chaves, anotaĂ§Ăľes\...)
* `--workers ++<+WORKERS_NUMBER+>++` - NĂşmero de threads de trabalho a serem criados

=== `policy-server docs`

Gera a documentaĂ§ĂŁo markdown para os comandos do servidor de polĂ­ticas

*Uso:* `policy-server docs --output ++<+FILE+>++`

==== *OpĂ§Ăľes:*

* `-o`, `--output ++<+FILE+>++` - caminho onde o arquivo de documentaĂ§ĂŁo serĂĄ armazenado

Este documento foi gerado automaticamente pelo clap-markdown.
