include::partial$variables.adoc[]
= 生政策
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 任意の JSON ドキュメントを評価する生のポリシーについて学び、Rust によるポリシーの実装例をご覧ください。
:doc-persona: ["kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["writing-policies", "rust", "raw-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"raw policies"、"rust"]]。
:sidebar_label: 生政策
:current-version: {page-origin-branch}

生ポリシーは、任意のJSONドキュメントを評価できるポリシーである。
生政策の詳細については、xref:howtos/raw-policies.adoc[生政策の]ページを参照してください。

== 例

以下の例は、このチュートリアルのxref:tutorials/writing-policies/rust/05-mutation-policy.adoc[検証]ページを完了した人なら見覚えがあるはずだ。

[NOTE]
====
`metadata.yml` 設定の`policyType` フィールドを使用して、ポリシーを`raw` としてマークすることを忘れないでください。
詳しくはxref:tutorials/writing-policies/metadata.adoc[メタデータの]仕様を参照されたい。
====


=== バリデーション

次のような形式のリクエストを受け付けるポリシーを書いてみよう：

[subs="+attributes",json]
----
{
  "request": {
    "user": "alice",
    "action": "delete",
    "resource": "products"
  }
}
----

と検証している：

* `user` が有効なユーザーリストにある
* `action` は有効なアクションのリストにある
* `resource` は有効なリソースのリストにある

https://github.com/kubewarden/rust-policy-template[rust policy templateを]使用して、ポリシーの足場を作ることから始めます。

最初に、リクエストのペイロードを表す型を定義する。
SDKが提供する`ValidationRequest` 型を使用する代わりに、`Request` と`Settings` を含むカスタム`RawValidationRequest` 型を宣言します：

[subs="+attributes",rust]
----
/// RawValidationRequest represents the request that is sent to the validate function by the Policy Server.
#[derive(Deserialize)]
pub(crate) struct RawValidationRequest {
    pub(crate) request: Request,
    pub(crate) settings: Settings,
}

#[derive(Serialize, Deserialize)]
/// Request represents the payload of the request.
pub(crate) struct Request {
    pub(crate) user: String,
    pub(crate) resource: String,
    pub(crate) action: String,
}
----

次に、`Settings` 型を定義し、`Validatable` 特性を実装する必要がある：

[subs="+attributes",rust]
----
/// Settings represents the settings of the policy.
#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(default, rename_all = "camelCase")]
pub(crate) struct Settings {
    pub(crate) valid_users: Vec<String>,
    pub(crate) valid_actions: Vec<String>,
    pub(crate) valid_resources: Vec<String>,
}

impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        info!(LOG_DRAIN, "starting settings validation");

        if self.valid_users.is_empty() {
            return Err("validUsers cannot be empty".to_string());
        }

        if self.valid_actions.is_empty() {
            return Err("validActions cannot be empty".to_string());
        }

        if self.valid_resources.is_empty() {
            return Err("validResources cannot be empty".to_string());
        }

        Ok(())
    }
}
----

最後に、`validate` 関数を定義する：

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: RawValidationRequest =
        if let Ok(validation_request) = serde_json::from_slice(payload) {
            validation_request
        } else {
            return kubewarden::reject_request(
                Some("cannot unmarshal request".to_string()),
                None,
                None,
                None,
            );
        };

    info!(LOG_DRAIN, "starting validation");

    let request = validation_request.request;
    let settings = validation_request.settings;

    if settings.valid_users.contains(&request.user)
        && settings.valid_actions.contains(&request.action)
        && settings.valid_resources.contains(&request.resource)
    {
        info!(LOG_DRAIN, "accepting resource");
        kubewarden::accept_request()
    } else {
        kubewarden::reject_request(
            Some("this request is not accepted".to_string()),
            None,
            None,
            None,
        )
    }
}
----

=== 突然変異

リクエストを拒否する代わりに変異させるために、前の例を修正しよう。
この場合、設定には`defaultUser` 、`defaultAction` 、`defaultRequest` が含まれ、ユーザー、アクション、リソースが有効でない場合、リクエストを変更するために使用されます。

新しいフィールドで`Settings` タイプを更新する必要がある：

[subs="+attributes",rust]
----
/// Settings represents the settings of the policy.
#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(default, rename_all = "camelCase")]
pub(crate) struct Settings {
    pub(crate) valid_users: Vec<String>,
    pub(crate) valid_actions: Vec<String>,
    pub(crate) valid_resources: Vec<String>,
    pub(crate) default_user: String,
    pub(crate) default_action: String,
    pub(crate) default_resource: String,
}

impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        info!(LOG_DRAIN, "starting settings validation");

        if self.valid_users.is_empty() {
            return Err("validUsers cannot be empty".to_string());
        }

        if self.valid_actions.is_empty() {
            return Err("validActions cannot be empty".to_string());
        }

        if self.valid_resources.is_empty() {
            return Err("validResources cannot be empty".to_string());
        }

        if self.default_user.is_empty() {
            return Err("defaultUser cannot be empty".to_string());
        }

        if self.default_action.is_empty() {
            return Err("defaultAction cannot be empty".to_string());
        }

        if self.default_resource.is_empty() {
            return Err("defaultResource cannot be empty".to_string());
        }

        Ok(())
    }
}
----

と`validate` 関数で突然変異を導入する：

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: RawValidationRequest =
        if let Ok(validation_request) = serde_json::from_slice(payload) {
            validation_request
        } else {
            return kubewarden::reject_request(
                Some("cannot unmarshal request".to_string()),
                None,
                None,
                None,
            );
        };

    info!(LOG_DRAIN, "starting validation");

    let request = validation_request.request;
    let settings = validation_request.settings;

    if settings.valid_users.contains(&request.user)
        && settings.valid_actions.contains(&request.action)
        && settings.valid_resources.contains(&request.resource)
    {
        info!(LOG_DRAIN, "accepting request");
        return kubewarden::accept_request();
    }

    info!(LOG_DRAIN, "mutating request");
    let mut request = request;

    if !settings.valid_users.contains(&request.user) {
        request.user = settings.default_user;
    }

    if !settings.valid_actions.contains(&request.action) {
        request.action = settings.default_action;
    }

    if !settings.valid_resources.contains(&request.resource) {
        request.resource = settings.default_resource;
    }

    let mutated_request = serde_json::to_value(request)?;
    kubewarden::mutate_request(mutated_request)
}
----
