include::partial$variables.adoc[]
= Testes de ponta a ponta
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Descubra como escrever e automatizar testes de ponta a ponta executados no binário do WebAssembly produzido pelo TinyGo com bats e kwctl.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "end-to-end-testing"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "escrever políticas", "teste de ponta a ponta", "golang", "go"]
:sidebar_label: Testes de ponta a ponta
:sidebar_position: 40
:current-version: {page-origin-branch}

Até agora, você testou a política usando um conjunto de testes unitários em Go.
Esta seção mostra como você pode escrever testes de ponta a ponta executados no binário real do WebAssembly produzido pelo TinyGo.

== Pré-requisitos

Lembre-se de que você precisa dessas ferramentas em sua máquina de desenvolvimento:

* Docker ou outro mecanismo de contêiner: Usado para criar a política do WebAssembly.
Você usará o compilador fornecido com a imagem oficial do contêiner do TinyGo.
* https://github.com/bats-core/bats-core[morcegos]:
Usado para escrever os testes e automatizar sua execução.
* https://github.com/kubewarden/kwctl/releases[`kwctl`]:
Ferramenta CLI fornecida por {project-name} para executar suas políticas fora do Kubernetes, entre outras ações.
Isso é abordado xref:tutorials/testing-policies/index.adoc[nesta seção] da documentação.

== Testes de redação

Você usará ohttps://github.com/bats-core/bats-core[] bats para escrever e automatizar seus testes.
Cada teste tem as seguintes etapas:

. Execute a política usando `kwctl`.
. Realizar asserções em relação à saída produzida pelo `kwctl`.

Todos os testes de ponta a ponta estão em um arquivo chamado `e2e.bats`.
O projeto scaffolding do projeto já inclui um exemplo `e2e.bats`.
Você precisa alterar seu conteúdo para refletir como sua política se comporta.
Você pode remover o conteúdo do arquivo de andaimes e substituí-lo pelo conteúdo abaixo à medida que for trabalhando neste tutorial.

Para os testes de ponta a ponta, você usa os mesmos arquivos de dispositivos de teste que usou nos testes de unidade Go.

O primeiro teste garante a aprovação da solicitação quando não há configurações fornecidas:

[,bash]
----
@test "accept when no settings are provided" {
  run kwctl run -r test_data/pod.json policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # request is accepted
  [ $(expr "$output" : '.*"allowed":true.*') -ne 0 ]
}
----

Você executa os testes de ponta a ponta usando esse comando:

[subs="+attributes",console]
----
make e2e-tests
----

Isso produz o seguinte resultado:

[subs="+attributes",console]
----
bats e2e.bats
 ✓ accept when no settings are provided

1 test, 0 failures
----

Você deve escrever um teste que garanta a aprovação da solicitação ao respeitar uma restrição definida pelo usuário:

[,bash]
----
@test "accept because label is satisfying a constraint" {
  run kwctl run annotated-policy.wasm \
    -r test_data/pod.json \
    --settings-json '{"constrained_labels": {"cc-center": "\\d+"}}'

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*true') -ne 0 ]
}
----

Em seguida, você pode escrever um teste para verificar a aceitação da solicitação quando nenhum dos rótulos estiver na lista de negação:

[,bash]
----
@test "accept labels are not on deny list" {
  run kwctl run \
    -r test_data/pod.json \
    --settings-json '{"denied_labels": ["foo", "bar"]}' \
    policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ $(expr "$output" : '.*"allowed":true.*') -ne 0 ]
}
----

Você pode melhorar a cobertura do teste adicionando um teste que rejeite uma solicitação porque um dos rótulos está na lista de negação:

[,bash]
----
@test "reject because label is on deny list" {
  run kwctl run annotated-policy.wasm \
    -r test_data/pod.json \
    --settings-json '{"denied_labels": ["foo", "owner"]}'

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [ $(expr "$output" : ".*Label owner is on the deny list.*") -ne 0 ]
}
----

O teste a seguir garante a rejeição de uma solicitação quando um de seus rótulos não satisfaz a restrição fornecida pelo usuário.

[,bash]
----
@test "reject because label is not satisfying a constraint" {
  run kwctl run annotated-policy.wasm \
    -r test_data/pod.json \
    --settings-json '{"constrained_labels": {"cc-center": "team-\\d+"}}'

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [ $(expr "$output" : ".*The value of cc-center doesn't pass user-defined constraint.*") -ne 0 ]
}
----

Agora você pode garantir que a validação falhe se um dos rótulos restritos não for encontrado:

[,bash]
----
@test "reject because constrained label is missing" {
  run kwctl run annotated-policy.wasm \
    -r test_data/pod.json \
    --settings-json '{"constrained_labels": {"organization": "\\d+"}}'

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  [ "$status" -eq 0 ]
  [ $(expr "$output" : '.*allowed.*false') -ne 0 ]
  [ $(expr "$output" : ".*Constrained label organization not found inside of Pod.*") -ne 0 ]
}
----

Você deseja verificar se a validação das configurações está funcionando corretamente.
Você pode fazer isso com os seguintes testes:

[,bash]
----
@test "fail settings validation because of conflicting labels" {
  run kwctl run \
    -r test_data/pod.json \
    --settings-json '{"denied_labels": ["foo", "cc-center"], "constrained_labels": {"cc-center": "^cc-\\d+$"}}' \
    policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # settings validation failed
  [ $(expr "$output" : ".*Provided settings are not valid: These labels cannot be constrained and denied at the same time: Set{cc-center}.*") -ne 0 ]
}

@test "fail settings validation because of invalid constraint" {
  run kwctl run \
    -r test_data/pod.json \
    --settings-json '{"constrained_labels": {"cc-center": "^cc-[12$"}}' \
    policy.wasm

  # this prints the output when one the checks below fails
  echo "output = ${output}"

  # settings validation failed
  [ $(expr "$output" : ".*Provided settings are not valid: error parsing regexp.*") -ne 0 ]
}
----

== Conclusão

Os oito testes de ponta a ponta agora oferecem um bom nível de cobertura, você pode executar todos eles:

[subs="+attributes",shell]
----
$ make e2e-tests
bats e2e.bats
e2e.bats
 ✓ accept when no settings are provided
 ✓ accept because label is satisfying a constraint
 ✓ accept labels are not on deny list
 ✓ reject because label is on deny list
 ✓ reject because label is not satisfying a constraint
 ✓ reject because constrained label is missing
 ✓ fail settings validation because of conflicting labels
 ✓ fail settings validation because of invalid constraint

8 tests, 0 failures
----
