include::partial$variables.adoc[]
= Integração com GitHub Actions
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprenda a integrar o GitHub Actions para tarefas automatizadas, testes de unidade, testes de ponta a ponta e fluxos de trabalho de CI/CD.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "github-action-integration"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "github", "integration"]
:sidebar_label: Ações do GitHub
:sidebar_position: 56
:current-version: {page-origin-branch}

== Automação

Esta seção descreve como você pode usar GitHub Actions para automatizar tarefas.

A estrutura do projeto já inclui todas as ações do GitHub de que você precisa.
Você pode encontrar as ações nos arquivos `.github/workflows/test.yml` e `.github/workflows/release.yml`.

Você pode adaptar esses princípios para usar um sistema de CI diferente.

== Testes

A automação dos testes de unidade e dos testes de ponta a ponta funciona imediatamente.
Ele usa os trabalhos definidos em `.github/workflows/test.yml`.

== Liberação

O projeto de andaimes tem um trabalho `release` em `.github/workflows/release.yml`.

Esse trabalho executa as seguintes etapas:

* Código de checkout
* Criar a política do WebAssembly
* Impulsionar a política para um registro de Iniciativa de Recipientes Abertos (OCI)
* Criar uma nova versão do GitHub

Para ativar o trabalho, ajuste a entrada da ação `oci-target` para o fluxo de trabalho reutilizável (`reusable-release-policy-go.yml`) chamado no arquivo `release.yml`.

O trabalho age de forma diferente com base no commit que acionou sua execução.

Os commits regulares levam à criação de um artefato OCI chamado `<policy-name>:latest`.
Uma versão do GitHub não é criada para esses commits.

A criação de uma tag que corresponda ao padrão `v*` leva a:

* Criação de um artefato OCI chamado `<policy-name>:<tag>`.
* Criação de uma versão do GitHub chamada `Release <full tag name>`.
A versão inclui os ativos, o código-fonte da política e o binário do WebAssembly.

=== Um exemplo

Suponha que haja uma política chamada `safe-labels` e que ela precise ser publicada como `ghcr.io/kubewarden/policies/safe-labels`.

O conteúdo da seção `jobs.push-to-oci-registry.env` de `ci.yml` deve ter a seguinte aparência:

[subs="+attributes",yaml]
----
jobs:
  push-to-oci-registry:
    runs-on: ubuntu-latest
    env:
      WASM_BINARY_NAME: policy.wasm
      OCI_TARGET: ghcr.io/kubewarden/policies/safe-labels
----

O envio de uma tag chamada `v0.1.0` leva à criação e publicação do artefato OCI chamado `ghcr.io/kubewarden/policies/safe-labels:v0.1.0`.

Ele cria uma versão do GitHub chamada `Release v0.1.0`.
A versão inclui os seguintes ativos:

* Código-fonte compactado como `zip` e `tar.gz`
* Um arquivo chamado `policy.wasm`; essa é a política real do WebAssembly
