= Repetição de instantâneos
:revdate: 2025-10-27
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

Esta página descreve as mensagens JSON exatas que podem ser enviadas para o modelo de consistência Repetir instantâneos de sincronização de integridade.

== Propriedade JSON: "health" (saúde)

A integridade pode ser enviada para a API do SUSE Observability Receiver usando a propriedade `+"health"+` do xref:/configure/health/send-health-data/send-health-data.adoc#_common_json_object[objeto JSON comum].

[tabs]
====
Exemplo de saúde `+repeat_snapshots+` JSON::
+
--
[,javascript]
----
{
   "apiKey":"<STACKSTATE_RECEIVER_API_KEY>",
   "collection_timestamp":1585818978,
   "internalHostname":"lnx-343242.srv.stackstate.com",
   "health":[
      {
        "consistency_model": "REPEAT_SNAPSHOTS",
        "start_snapshot": {
          "repeat_interval_s": 50
          //"expiry_interval_s": 200 Optional
        },
        "stop_snapshot": {},
        "stream": {
          "urn": "urn:health:sourceId:streamId"
          //"sub_stream_id": "subStreamId" Optional
        },
        "check_states": [
          {
            "checkStateId": "checkStateId1",
            "message": "Server Running out of disk space",
            "health": "Deviating",
            "topologyElementIdentifier": "server-1",
            "name": "Disk Usage"
          },
          {
            "checkStateId": "checkStateId2",
            "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
            "health": "critical",
            "topologyElementIdentifier": "server-2",
            "name": "Health monitor"
          }
        ]
      }
   ]
}
----
--
====

Cada carga útil de dados de Snapshots de repetição de integridade tem os seguintes detalhes:

* *start_snapshot* - Optional. O início de um instantâneo precisa ser processado antes do processamento de `+check_states+`. Isso permite que o SUSE Observability difira um instantâneo de fluxo com o instantâneo recebido anteriormente e exclua os estados de verificação que não estão mais presentes no instantâneo. Ele carrega os seguintes campos como metadados de instantâneos:
 ** *repeat_interval_s* - Tempo em segundos. A frequência com que a fonte externa enviará dados de integridade para o SUSE Observability. O valor máximo permitido é 1800 (30 minutos).
 ** *expiry_interval_s* - Tempo em segundos. O tempo de espera após a última atualização antes que uma verificação externa seja excluída pelo SUSE Observability. Necessário ao usar subfluxos.
* *stop_snapshot* - Opcional. O fim de um instantâneo será processado após o processamento `` do+check_states+``.
* *fluxo* - Objeto que fornece identificação sobre quais instantâneos e `+check_states+` pertencem um ao outro. Ele tem os seguintes campos:
 ** *urn* - ID da fonte de dados e do fluxo codificado como um xref:/configure/topology/identifiers.adoc[URN] do SUSE Observability que corresponde à seguinte convenção: `+urn:health:<sourceId>:<streamId>+` em que `+<sourceId>+` é o nome da fonte de dados externa e `+<streamId>+` é um identificador exclusivo do fluxo de dados de integridade.
 ** *sub_stream_id* - Optional. Identificador de um subconjunto de dados de integridade do fluxo. Quando os dados de fluxo são distribuídos e relatados por vários agentes, isso permite ciclos de vida de instantâneos por agente. `+sub_stream_id+`
* *check_states* - Uma lista de estados de verificação. Cada estado de verificação pode ter os seguintes campos:
 ** *checkStateId* - Identificador do estado de verificação no sistema externo
 ** *mensagem* - opcional. Mensagem a ser exibida na interface do usuário do SUSE Observability. Os dados serão interpretados como markdown, permitindo que haja links para a verificação do sistema externo que gerou o estado da verificação externa.
 ** *health* - Um dos seguintes valores de estado do SUSE Observability Health: `+Clear+`, `+Deviating+`, `+Critical+`.
 ** *topologyElementIdentifier* - Usado para vincular o estado de verificação a um elemento de topologia do SUSE Observability.
 ** *name* - Nome do estado de verificação externo.

== Enviar saúde para o SUSE Observability

A integridade pode ser enviada em uma mensagem JSON via HTTP POST. No exemplo abaixo, um instantâneo contendo dois estados de verificação é enviado ao SUSE Observability a partir de um único sistema de monitoramento externo.

[,bash]
----
curl -X POST \
 '<STACKSTATE_RECEIVER_API_ADDRESS>' \
 -H 'Content-Type: application/json' \
 -d '{
  "collection_timestamp": 1548857167,
  "internalHostname": "local.test",
  "health": [
    {
      "consistency_model": "REPEAT_SNAPSHOTS",
      "start_snapshot": {
        "repeat_interval_s": 300
      },
      "stop_snapshot": {},
      "stream": {
        "urn": "urn:health:sourceId:streamId"
      },
      "check_states": [
        {
          "checkStateId": "checkStateId1",
          "message": "Server Running out of disk space",
          "health": "Deviating",
          "topologyElementIdentifier": "server-1",
          "name": "Disk Usage"
        },
        {
          "checkStateId": "checkStateId2",
          "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
          "health": "critical",
          "topologyElementIdentifier": "server-2",
          "name": "Health monitor"
        }
      ]
    }
  ]
}'
----
