include::partial$variables.adoc[]
= Gatekeeper-Unterstützung
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Greifen Sie auf zentrale Gatekeeper-Richtlinien zu und erfahren Sie, wie Sie diese in Kubernetes-Zugangssteuerungen integrieren können.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "rego", "gatekeeper"]
:current-version: {page-origin-branch}

[NOTE]
====
Die Gatekeeper-Unterstützung beginnt mit diesen Versionen:

* kwctl: v0.2.0
* policy-server: v0.2.0
====


Gatekeeper ist ein Projekt, das auf Kubernetes abzielt und sofort einsatzbereite Funktionen für die Integration bietet.

== Vereinbarkeit mit bestehenden Politiken

Alle bestehenden Gatekeeper-Richtlinien sollten mit {short-project-name} kompatibel sein, wie in diesem Kapitel beschrieben.

[IMPORTANT]
====
Wenn Sie feststellen, dass dies für Ihre Gatekeeper-Richtlinien nicht zutrifft, melden Sie es, und wir werden daran arbeiten, dass Ihre Gatekeeper-Richtlinie mit {short-project-name} läuft.
====


Policies müssen mit der `+opa+` CLI zu `+wasm+` Ziel kompiliert werden.

Für die Ausführung von Richtlinien können Sie mehr über diexref:tutorials/writing-policies/rego/02-builtin-support.adoc[integrierte Unterstützung] des Open Policy Agent unter {short-project-name} lesen.
