= Sichern und Wiederherstellen
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

Die Art und Weise, wie K3s gesichert und wiederhergestellt wird, hängt davon ab, welche Art von Datenspeicher verwendet wird.

[CAUTION]
====
Zusätzlich zur Sicherung des Datenspeichers selbst müssen Sie auch die Server-Token-Datei unter `+/var/lib/rancher/k3s/server/token+` sichern.
Sie müssen diese Datei wiederherstellen oder ihren Wert in der Option `+--token+` übergeben, wenn Sie von einem Backup wiederherstellen.
Wenn Sie bei der Wiederherstellung nicht denselben Token-Wert verwenden, ist der Snapshot unbrauchbar, da der Token zur Verschlüsselung vertraulicher Daten im Datenspeicher selbst verwendet wird.
====


== Sicherung und Wiederherstellung mit SQLite

Zum Sichern oder Wiederherstellen des SQLite-Datenspeichers sind keine besonderen Befehle erforderlich.

* Um den SQLite-Datenspeicher zu sichern, erstellen Sie eine Kopie von `+/var/lib/rancher/k3s/server/db/+`.
* Um den SQLite-Datenspeicher wiederherzustellen, stellen Sie den Inhalt von `+/var/lib/rancher/k3s/server/db+` (und das Token, wie oben beschrieben) wieder her.

== Sicherung und Wiederherstellung mit externem Datenspeicher

Bei Verwendung eines externen Datenspeichers werden die Sicherungs- und Wiederherstellungsvorgänge außerhalb von K3s durchgeführt. Der Datenbankadministrator muss eine Sicherungskopie der externen Datenbank erstellen oder sie von einem Snapshot oder Dump wiederherstellen.

Wir empfehlen, die Datenbank so zu konfigurieren, dass wiederkehrende Snapshots erstellt werden.

Einzelheiten zur Erstellung von Datenbank-Snapshots und zur Wiederherstellung Ihrer Datenbank aus diesen Snapshots finden Sie in der offiziellen Datenbankdokumentation:

* https://dev.mysql.com/doc/refman/8.0/en/replication-snapshot-method.html[Offizielle MySQL-Dokumentation]
* https://www.postgresql.org/docs/8.3/backup-dump.html[Offizielle PostgreSQL-Dokumentation]
* https://etcd.io/docs/latest/op-guide/recovery/[Offizielle etcd-Dokumentation]

== Sicherung und Wiederherstellung mit eingebettetem etcd-Datenspeicher

Informationen zur Durchführung von Sicherungs- und Wiederherstellungsvorgängen auf dem eingebetteten etcd-Datenspeicher finden Sie in der xref:cli/etcd-snapshot.adoc[Dokumentation des Befehls`+k3s etcd-snapshot+` ].
