= Control de acceso basado en roles (RBAC)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

La gestión de accesos le ayuda a gestionar quién tiene acceso a los elementos específicos de la topología, los datos métricos, las trazas, los elementos de la interfaz de usuario y a qué API pueden llamar.

RBAC es un sistema de autorización que proporciona una gestión de acceso detallada de los recursos de SUSE Observability, una forma limpia y sencilla de auditar los privilegios de los usuarios y de solucionar los problemas identificados con los derechos de acceso.

== ¿Qué se puede hacer con RBAC?

Estos son algunos ejemplos de lo que puede hacer con RBAC:

* Permitir que un usuario tenga acceso sólo al clúster de desarrollo, otro tanto al clúster de producción como al de desarrollo y un tercero pueda acceder al clúster de desarrollo y sólo a 1 espacio de nombres en el clúster de producción.
* Asigne a un pequeño grupo de usuarios una función de administrador para instalar y configurar SUSE Observability. A la vez que se ofrece a todos los desarrolladores un rol de solucionador de problemas para ver toda la topología, métricas, trazas, registros y eventos, pero con una capacidad de configuración limitada.

== ¿Qué es una función en SUSE Observability?

Una función en SUSE Observability es una combinación de un asunto configurado y un conjunto de xref:/setup/security/rbac/rbac_permissions.adoc[permisos]. El proceso de configuración de una función en SUSE Observability se describe en xref:/setup/security/rbac/rbac_roles.adoc[Cómo configurar funciones].

== Fuentes de roles RBAC

Puede definir las funciones de varias maneras.  Todos utilizan los mismos xref:/setup/security/rbac/rbac_permissions.adoc[permisos].

* **Configuración** - en los xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[valores del timón] para SUSE Observability
* **Dinámico** - xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[utilice la CLI `+sts+` ]
* **Mapeado desde Kubernetes** - xref:/setup/security/rbac/rbac_rancher.adoc[mapear Kubernetes `+Roles+` y] xref:/setup/security/rbac/rbac_rancher.adoc[ `+RoleBindings+`]

== Más información sobre la configuración de RBAC

* xref:/setup/security/rbac/rbac_permissions.adoc[Permisos]
* xref:/setup/security/rbac/rbac_roles.adoc[Cómo configurar las funciones]
* xref:/setup/security/rbac/rbac_rancher.adoc[Utilizar con Rancher]
* xref:/setup/security/rbac/rbac_scopes.adoc[Visores]
* xref:/setup/security/authentication/README.adoc[Cómo configurar la autenticación]
