= Referencia MachineRegistration
:revdate: 2025-09-08
:page-revdate: {revdate}

El recurso MachineRegistration permite:

* para configurar el proceso de registro
* para proporcionar los parámetros de instalación del sistema operativo
* para definir los xref:rancher-os-management/architecture/services/architecture-services.adoc[servicios{elemental-product-name} ] habilitados para la máquina de registro Una vez creado genera la URL de registro utilizada por los nodos para registrarse e iniciar el proceso de xref:rancher-os-management/architecture/services/architecture-machineonboarding.adoc[onboarding de] la máquina.

El MachineRegistration tiene una condición `+Ready+` que se convierte en true cuando el {elemental_operator_name} ha generado con éxito la URL de registro y un `+ServiceAccount+` asociado. A partir de este momento, el host de destino puede conectarse a la URL de registro para iniciar el proceso de aprovisionamiento.

Una petición HTTP GET contra la URL de registración devuelve el _archivo de registración_: un archivo .yaml que contiene los datos de registración (es decir, la sección _spec:config:elemental:registration_ de la recién creada MachineRegistration).
El archivo de registro contiene todos los datos necesarios para permitir que el host de destino realice el autorregistro e inicie el aprovisionamiento de {elemental-product-name}.

Hay varias claves que pueden configurarse en una especificación de recursos `+MachineRegistration+`.

.MachineRegistration
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  machineName: name
  machineInventoryLabels:
    label: value
  machineInventoryAnnotations:
    annotation: value
  config:
    cloud-config:
        ...
    elemental:
        registration:
            ...
        install:
            ...
----

== `+config.cloud-config+`

Contiene la configuración de la nube que se inyectará en el nodo.
Se admiten las sintaxis yip y cloud-init. Consulte la xref:references/cloud-config-reference.adoc[Referencia de configuración de la nube] para obtener más información.

== `+config.network+`

Contiene la configuración de red declarativa que soporta la integración con https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220125-ipam-integration.md#ipam-provider[los proveedores IPAM de]. +
Consulte la xref:operator-operational-tasks/declarative-networking/networking.adoc[Referencia de redes declarativas] para obtener más información.

|===
| Clave | Tipo | Valor por defecto | Descripción

| configurador
| cadena
| nmc
| El configurador de red a utilizar (`+nmc+`, `+nmstate+`, o `+nmconnections+`)

| ipAddresses
| objRefMap
| vacío
| Un mapa de referencias `+IPPool+`. Las claves de mapa pueden utilizarse para la sustitución de direcciones IPA en la plantilla de configuración de red.

| config
| obj
| vacío
| La plantilla de configuración de red. La sintaxis varía en función de la dirección `+configurator+` utilizada.
|===

== `+config.elemental.registration+`

Contiene la configuración utilizada para la conexión y el registro inicial en {elemental_operator_name}.

Admite los siguientes valores:

|===
| Clave | Tipo | Valor por defecto | Descripción

| url
| cadena
| vacío
| URL para conectarse al {elemental_operator_name}

| ca-cert
| cadena
| vacío
| CA para validar el certificado proporcionado por el servidor en "url" (necesario si el certificado no está firmado por una CA pública)

| no-smbios
| bool
| falso
| Si los datos SMBIOS deben enviarse al {elemental_operator_name}

| no-toolkit
| bool
| falso
| Desactiva la compatibilidad con {elemental_toolkit_url}[{elemental_toolkit_name"}] y permite el registro de un xref:operator-operational-tasks/unmanaged-os.adoc[SO no gestionado].
|===

[CAUTION]
====
Los siguientes valores son sólo para fines de desarrollo.
====

|===
| Clave | Tipo | Valor por defecto | Descripción

| auth
| cadena
| tpm
| Método de autenticación a utilizar durante el registro, uno de `+tpm+`, `+mac+` o `+sys-uuid+`. Para más información, consulte xref:rancher-os-management/authentication.adoc[Autenticación]  

| emulate-tpm
| bool
| falso
| Esto utilizará la emulación de software del TPM (necesario para hosts sin hardware TPM)

| emulated-tpm-seed
| int64
| 1
| Corregida la semilla para usar con 'emulate-tpm'. Establecer en -1 para obtener una semilla aleatoria. Más información en xref:operator-operational-tasks/tpm.adoc[TPM] 
|===

== `+config.elemental.install+`

Contiene la configuración de instalación que se aplicaría a través de `+elemental-register --install+` cuando se arranca desde una ISO y se pasa a https://github.com/rancher/elemental-toolkit/blob/main/docs/elemental_install.md[`+elemental install+`]

Admite los siguientes valores:

|===
| Clave | Tipo | Valor por defecto | Descripción

| firmware
| cadena
| efi
| Firmware a instalar ('efi' o 'bios')

| dispositivo
| cadena
| vacío
| Dispositivo en el que instalar el sistema

| selector de dispositivos
| cadena
| vacío
| Reglas para elegir el dispositivo en el que instalar el sistema

| no-format
| bool
| falso
| No formatees los discos. Se supone que las particiones COS_STATE, COS_RECOVERY, COS_PERSISTENT, COS_OEM ya existen en el disco de destino.

| config-urls
| lista
| vacío
| Ubicación de los archivos de configuración de Cloud-init

| iso
| cadena
| vacío
| Realiza una instalación desde la url ISO en lugar de la ISO en ejecución.

| system-uri
| cadena
| vacío
| Establece el origen de la imagen del sistema y su tipo (por ejemplo, 'docker:registry.org/image:tag') en lugar de utilizar la ISO en ejecución.

| depurar
| bool
| falso
| Activar salida de depuración

| tty
| cadena
| vacío
| Añadir el nombre tty a grub

| poweroff
| bool
| falso
| Apagar el sistema tras la instalación

| reiniciar
| bool
| falso
| Reiniciar el sistema después de la instalación

| snapshotter
| obj
| vacío
| Configuración del Snapshotter. Véase <<#_config_elemental_install_snapshotter,la referencia`+config.elemental.install.snapshotter+` >>.

| eject-cd
| bool
| falso
| Intenta expulsar el cd al reiniciar
|===

[CAUTION]
====
En caso de utilizar tanto `+iso+` como `+system-uri+`, el valor de `+iso+` tiene prioridad.
====

Sólo es necesario especificar los campos `+device+` o `+device-selector+` para que la instalación se realice correctamente, el resto de parámetros son opcionales.

Si se especifica `+device+` y `+device-selector+`, se utiliza el valor de `+device+` y se ignora `+device-selector+`.

.Haga clic aquí para más detalles
[%collapsible]
====
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  config:
    elemental:
      install:
        device: /dev/sda
        debug: true
        reboot: true
        eject-cd: true
        system-uri: registry.suse.com/rancher/sle-micro/5.5:latest
----
====

== `+config.elemental.install.device-selector+`

El campo `+device-selector+` se puede utilizar para elegir dinámicamente el dispositivo durante la instalación. El campo contiene una lista de reglas con el siguiente aspecto:

.Haga clic aquí para más detalles
[%collapsible]
====
.Example selector de dispositivos basado en el nombre del dispositivo
[,yaml]
----
device-selector:
  - key: Name
    operator: In
    values:
      - /dev/sda
      - /dev/vda
      - /dev/nvme0
----
====

.Haga clic aquí para más detalles
[%collapsible]
====
.Example selector de dispositivos basado en el tamaño del dispositivo
[,yaml]
----
device-selector:
  - key: Size
    operator: Lt
    values:
      - 100Gi
  - key: Size
    operator: Gt
    values:
      - 30Gi
----
====

Los operadores admitidos actualmente son:

|===
| Operador | Descripción

| En
| La clave coincide con uno de los valores proporcionados

| NotIn
| La clave no coincide con ninguno de los valores proporcionados

| Gt
| La clave es mayor que un único valor proporcionado

| Lt
| La clave es menor que un único valor proporcionado
|===

Las teclas admitidas actualmente son:

|===
| Clave | Descripción

| Nombre
| El nombre del dispositivo (por ejemplo, /dev/sda)

| Talla
| El tamaño del dispositivo (los valores pueden especificarse utilizando recursos kubernetes, por ejemplo 100Gi)
|===

Las reglas se juntan, lo que significa que todas las reglas deben coincidir con el dispositivo objetivo.

== `+config.elemental.install.snapshotter+`

Puede configurar cómo Elemental gestiona las instantáneas en la máquina instalada. Las nuevas instantáneas se crean, por ejemplo, al xref:node-operational-tasks/upgrade.adoc[actualizar] la máquina con una nueva imagen del sistema operativo.

El snapshotter de loopdevice desempaquetará nuevas imágenes en un sistema de archivos ext4, mientras que el snapshotter de btrfs hará uso de la funcionalidad subyacente https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/SysadminGuide.html#Snapshots[de snapshots de] 

|===
| Clave | Tipo | Valor por defecto | Descripción

| tipo
| cadena
| dispositivo de bucle
| Tipo de dispositivo utilizado para gestionar instantáneas en imágenes del SO ('loopdevice' o 'btrfs').

|===

== `+config.elemental.reset+`

Contiene la configuración de reinicio que se aplicaría a través de `+elemental-register --reset+`, cuando se arranca desde la partición de recuperación y se pasa a https://github.com/rancher/elemental-toolkit/blob/main/docs/elemental_reset.md[`+elemental reset+`]

Admite los siguientes valores:

|===
| Clave | Tipo | Valor por defecto | Descripción

| habilitado
| bool
| falso
| Los inventarios de máquinas creados a partir de este registro de máquinas tendrán activada la función de restablecimiento.

| reset-persistent
| bool
| verdadero
| Formatear la partición COS_PERSISTENT

| reset-oem
| bool
| verdadero
| Formatear la partición COS_OEM

| config-urls
| lista
| vacío
| Archivos de configuración de Cloud-init

| system-uri
| cadena
| vacío
| Establece el origen de la imagen del sistema y su tipo (por ejemplo, 'docker:registry.org/image:tag') en lugar de utilizar la ISO en ejecución.

| depurar
| bool
| falso
| Activar salida de depuración

| poweroff
| bool
| falso
| Apagar el sistema después de reiniciarlo

| reiniciar
| bool
| verdadero
| Reiniciar el sistema tras el reinicio
|===

.Haga clic aquí para más detalles
[%collapsible]
====
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  config:
    elemental:
      reset:
        enabled: true
        reset-persistent: true
        reset-oem: true
        reboot: true
        system-uri: registry.suse.com/rancher/sle-micro/5.5:latest
----
====

== `+machineName+`

Esto se refiere al nombre que se establecerá en el nodo y los recursos kubernetes que requieren un nombre de host (pods desplegados rke2 por ejemplo, utilizan el nombre de host del nodo como parte de los nombres de pod)`+String+` tipo.

[NOTE]
====
Cuando `+elemental:registration:no-smbios+` se establece en `+false+` (por defecto), machineName se interpola con https://www.dmtf.org/standards/smbios[SMBIOS] datos que le permite almacenar información de hardware.

Si no se especifica `+machineName+`, se establecerá uno por defecto de la forma `+m-$UUID+`.
El UUID se recuperará de los datos SMBIOS si están disponibles, de lo contrario se generará un UUID aleatorio.
====

.Haga clic aquí para más detalles
[%collapsible]
====
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  machineName: hostname-test-4
----
====

== `+machineInventoryLabels+`

Etiquetas que se pondrán en el `+MachineInventory+` que se cree a partir de este tipo de `+MachineRegistration+``+Key: value+` . Estas etiquetas se utilizarán para establecer un criterio de selección en xref:references/machineinventoryselectortemplate-reference.adoc[MachineInventorySelectorTemplate].

{elemental-product-name} Los nodos ejecutarán `+elemental-register+` cada 24 horas. +
Es posible actualizar `+machineInventoryLabels+` para que todos los nodos registrados apliquen las nuevas etiquetas en la siguiente actualización de registro correcta.

[IMPORTANT]
====
Cuando `+elemental:registration:no-smbios+` está ajustado a `+false+` (por defecto), las etiquetas se interpolan con los datos https://www.dmtf.org/standards/smbios[SMBIOS de]. Permite almacenar información de hardware en etiquetas personalizadas.
====

.Haga clic aquí para más detalles
[%collapsible]
====
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  machineInventoryLabels:
    my.prefix.io/element: fire
    my.prefix.io/cpus: 32
    my.prefix.io/manufacturer: "${System Information/Manufacturer}"
    my.prefix.io/productName: "${System Information/Product Name}"
    my.prefix.io/serialNumber: "${System Information/Serial Number}"
    my.prefix.io/machineUUID: "${System Information/UUID}"
----
====

== `+machineInventoryAnnotations+`

Anotaciones que se asignarán a la página `+MachineInventory+` creada a partir de este tipo `+MachineRegistration+``+Key: value+` 

.Haga clic aquí para más detalles
[%collapsible]
====
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  machineInventoryAnnotations:
    owner: bob
    version: 1.0.0
----
====
