= Referencia a MachineInventorySelectorTemplate
:revdate: 2025-09-08
:page-revdate: {revdate}

El MachineInventorySelectorTemplate es un recurso definido por el usuario que se utilizará como modelo para crear los xref:references/machineinventoryselector-reference.adoc[MachineInventorySelectors] necesarios.

Es el recurso encargado de definir los criterios de correspondencia para emparejar una máquina inventariada con un recurso Cluster.

La clave relevante es `+selector+`, que incluye expresiones de selección de etiquetas.

.MachineInventorySelectorTemplate
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: my-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        ...
----

`+template.spec.selector+` puede incluir las claves `+matchLabels+` y/o `+matchExpressions+`.

== `+template.spec.selector.matchLabels+`

Es un mapa de `+{key,value}+` pares `+(map[string]string)+`. Cuando se proporcionan varias etiquetas, todas deben coincidir.

.Haga clic aquí para más detalles
[%collapsible]
====
[yaml]
----
...
especificación: plantilla: especificación: selector: matchLabels: elemento: fuego fabricante: somevalue
----
====

Un Cluster definido con el selector anterior sólo intentará aprovisionar nodos inventariados que incluyan estas dos etiquetas.

== `+template.spec.selector.matchExpressions+`

Es una lista de selectores de etiqueta, cada selector de etiqueta se puede definir como:

|===
| Clave | Tipo | Descripción

| clave
| cadena
| Esta es la tecla de etiqueta sobre la que se aplica el selector

| operador
| cadena
| Representa la relación de la clave con un conjunto de valores. Los operadores válidos son "In", "NotIn", "Exists" y "DoesNotExist".

| valores
| []cadena
| Values es una matriz de valores de cadena. Si el operador es "In" o "NotIn", la matriz de valores no debe estar vacía. Si el operador es "Existe" o "No existe", la matriz de valores debe estar vacía.
|===

.Haga clic aquí para más detalles
[%collapsible]
====
[,yaml]
----
...
spec:
  template:
    spec:
      selector:
        matchExpressions:
        - key: element
          operator: In
          values: [ 'fire' ]
        - key: manufacturer
          operator: Exists
----
====

Un Cluster definido con el selector anterior sólo intentará aprovisionar nodos inventariados con la etiqueta `+element=fire+` y que incluyan una etiqueta `+manufacturer+` definida con cualquier valor.
