= {elemental-product-name} Cuadro de mando del operador
:revdate: 2025-07-03
:page-revdate: {revdate}

El {elemental_operator_url}[{elemental_operator_name}] es responsable de gestionar las versiones {elemental-product-name} y de mantener un inventario de máquinas para ayudar con las instalaciones edge o bare metal.

El gráfico asociado arranca un despliegue elemental-operator en el cluster https://rancher.com/docs/rancher/v2.6/[Rancher Manager v2.6] utilizando el gestor de paquetes https://helm.sh[Helm].

== Requisitos previos

* Rancher Manager versión v2.6
* Cliente Helm versión v3.8.0+

== Obtener información sobre la carta de Helm

[,console]
----
helm pull oci://registry.suse.com/rancher/elemental-operator-chart
helm show all oci://registry.suse.com/rancher/elemental-operator-chart
----

== Cuadro de instalación

[,console]
----
helm install --create-namespace -n cattle-elemental-system elemental-operator-crds \
             oci://registry.suse.com/rancher/elemental-operator-crds-chart
helm install --create-namespace -n cattle-elemental-system elemental-operator \
             oci://registry.suse.com/rancher/elemental-operator-chart
----

El comando despliega elemental-operator en el clúster Kubernetes con la configuración por defecto.

_Véase la <<_configuration,configuración>> más abajo._

_Consulte https://helm.sh/docs/helm/helm_install/[helm install] para ver la documentación del comando._

== Cuadro de desinstalación

[,console]
----
helm uninstall -n cattle-elemental-system elemental-operator
----

Esto elimina todos los componentes de Kubernetes asociados al gráfico y borra la versión.

_Consulte https://helm.sh/docs/helm/helm_uninstall/[helm uninstall] para ver la documentación del comando._

== Cuadro de actualización

[,console]
----
helm upgrade -n cattle-elemental-system \
             --install elemental-operator \
             oci://registry.suse.com/rancher/elemental-operator-chart
----

_Consulte la documentación del comando en https://helm.sh/docs/helm/helm_upgrade/[helm upgrade]._

== Configuración

Consulte https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing[Personalizar el gráfico antes de instalarlo]. Para ver todas las opciones configurables con comentarios detallados, visite los <<_values,valores>> del gráfico o ejecute estos comandos de configuración:

`console showLineNumbers helm show values oci://registry.suse.com/rancher/elemental-operator-chart `

== Valores

[cols="2,1,2,2"]
|===
| Clave | Tipo | Por defecto | Descripción

| imagen.vacía | cadena | `+rancher/pause:3.1+` |

| image.repository | cadena | `+registry.suse.com/rancher/elemental-operator-chart+` | Imagen de origen para elemental-operator con nombre de repositorio

| image.tag | etiqueta | `+""+` |

| image.imagePullPolicy | cadena | `+IfNotPresent+` |

| noProxy | cadena | `+127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local+` | Lista separada por comas de dominios o direcciones IP que no utilizarán el proxy 

| global.cattle.systemDefaultRegistry | cadena | `+""+` | Nombre predeterminado del registro de contenedores

| sync_interval | cadena | `+"60m"+` | Intervalo de sincronización predeterminado para el canal de actualización 

| sync_namespaces | lista | `+[]+` | Espacio de nombres que el operador vigilará, dejar vacío para todos 

| depurar | bool | `+false+` | Activar la salida de depuración para el operador 

| nodeSelector.kubernetes.io/os | cadena | `+linux+` |

| tolerancias | objeto | `+{}+` |

| tolerations.key | cadena | `+cattle.io/os+` |

| tolerations.operator | cadena | `+"Equal"+` |

| tolerations.value | cadena | `+"linux"+` |

| tolerancias.efecto | cadena | `+NoSchedule+` |
|===
