include::partial$variables.adoc[]
= Webhooks seguros com TLS mútuo com K3s
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Ativar o mTLS com o K3s
:description: Implemente protocolos de segurança mútua da camada de transporte (mTLS) para webhooks seguros com K3s em sua distribuição SUSE Kubernetes.
:keywords: ["{project-name}", kubewarden, kubernetes, segurança]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual do operador, segurança

Este guia mostra como ativar a segurança mútua da camada de transporte (mTLS) para webhooks da pilha{project-name} ao usar o https://k3s.io/[] K3s como sua distribuição do Kubernetes.

Para obter mais informações sobre como fortalecer os webhooks, consulte axref:/reference/security-hardening/webhooks-hardening.adoc[página de referência].

== Pré-requisitos

Antes de instalar o K3s, você precisa criar uma autoridade de certificação (CA) e um certificado de cliente. Você usa para proteger a comunicação entre os webhooks{short-project-name} e o servidor da API do Kubernetes.

Como primeira etapa, crie o diretório `/etc/rancher/k3s/admission/certs`:

[source,console]
----
sudo mkdir -p /etc/rancher/k3s/admission/certs
----

=== Criar uma CA raiz e o certificado do cliente

Como usuário `root`, altere o diretório para o diretório `/etc/rancher/k3s/admission/certs`e crie todos os certificados necessários:

[source,console]
----
export FQDN=mtls.kubewarden.io

# Create openssl config file
cat > openssl.cnf <<EOL
[ req ]
default_keyfile     = rootCA.key
distinguished_name  = req_distinguished_name
x509_extensions     = v3_ca
string_mask         = utf8only

[ req_distinguished_name ]
countryName         = Country Name (2 letter code)
countryName_default = US
stateOrProvinceName = State or Province Name (full name)
localityName        = Locality Name (eg, city)
organizationName    = Organization Name (eg, company)
commonName          = Common Name (eg, your domain or your CA name)

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true, pathlen:1
keyUsage = critical, keyCertSign, cRLSign
EOL

# Create CA
openssl req -nodes -batch -x509 -sha256 -days 3650 -newkey rsa:4096 -keyout rootCA.key -out rootCA.crt \
  -config openssl.cnf

# Create CSR
openssl req -nodes -batch -newkey rsa:4096 -keyout client.key -out client.csr \
    -addext "subjectAltName = DNS:$FQDN"  -config openssl.cnf

# Create CRT
openssl x509 -req -CA rootCA.crt -CAkey rootCA.key -in client.csr -out client.crt -days 3650 -CAcreateserial \
    -extfile <(echo "subjectAltName=DNS:$FQDN")

# Print CRT

openssl x509 -text -noout -in client.crt
----

Isso cria os seguintes arquivos:

* `client.crt`
* `client.csr`
* `client.key`
* `rootCA.crt`
* `rootCA.key`
* `rootCA.srl`

=== Criar o arquivo de configuração do Kubernetes

Crie o arquivo `/etc/rancher/k3s/admission/admission.yaml` com o seguinte conteúdo:

[source,yaml]
----
# /etc/rancher/k3s/admission/admission.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
- name: MutatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "/etc/rancher/k3s/admission/kubeconfig"
----

Por fim, crie um arquivo `kubeconfig` em `/etc/rancher/k3s/admission/kubeconfig`:

[source,yaml]
----
# /etc/rancher/admission/kubeconfig
apiVersion: v1
kind: Config
users:
- name: "*.kubewarden.svc" # namespace where the kubewarden stack is deployed
  user:
    client-certificate: /etc/rancher/k3s/admission/certs/client.crt
    client-key: /etc/rancher/k3s/admission/certs/client.key
----

=== Criar um arquivo de configuração do K3s

Crie um arquivo de configuração do K3s em `/etc/rancher/k3s/config.yaml`:

[source,yaml]
----
# /etc/rancher/k3s/config.yaml
kube-apiserver-arg:
- admission-control-config-file=/etc/rancher/k3s/admission/admission.yaml
----

== Instalar o K3s

Instale o K3s usando o seguinte comando:

[source,console]
----
curl -sfL https://get.k3s.io | sh -
----

Aguarde a conclusão da instalação.

== Instale a pilha {short-project-name} 

=== Pré-requisitos

O certificado da CA raiz, que emitiu o certificado do cliente Kubernetes, precisa estar disponível para a pilha {short-project-name}.

A CA raiz está disponível em `/etc/rancher/k3s/admission/certs/rootCA.crt` no nó do Kubernetes. Você precisa de seu conteúdo em um `ConfigMap` sob o namespace`kubewarden`. Você armazena o conteúdo do arquivo `rootCA.crt` na chave denominada `client-ca.crt`.

Primeiro, crie o namespace `kubewarden`:

[source,console]
----
kubectl create namespace kubewarden
----

Em seguida, crie o site `ConfigMap` nele. O comando a seguir, executado no nó do Kubernetes, faz isso:

[source,console]
----
kubectl create configmap -n kubewarden api-server-mtls \
    --from-file=client-ca.crt=/etc/rancher/k3s/admission/certs/rootCA.crt
----

O nome do site `ConfigMap` resultante é `api-server-mtls`.

=== Instale a pilha {short-project-name} 

Instale a pilha {short-project-name} conforme descrito noxref:/quick-start.adoc[guia de início rápido]. Siga todas as etapas, mas ao instalar o gráfico do `kubewarden-controller` Helm, certifique-se de ativar os seguintes valores:

* `mTLS.enable`: deve ser `true`.
* `mTLS.configMapName`Deve ser o nome do site `ConfigMap` criado anteriormente.

O nome `ConfigMap` é `api-server-mtls`. O comando Helm para instalar o`kubewarden-controller` é:

[source,console]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller \
    --set mTLS.enable=true \
    --set mTLS.configMapName=api-server-mtls
----

Quando esse comando for concluído, o mTLS protegerá a instalação da pilha{short-project-name} e de seus webhooks.