= Configuração de NTP com {elemental-product-name}
:revdate: 2025-07-03
:page-revdate: {revdate}

== Visão geral

O canal padrão do sistema operacional fornecido com {elemental-product-name} oferece suporte a NTP via `systemd-timesyncd`.

Esta página aborda a configuração do `systemd-timesyncd` com as imagens fornecidas do SLE Micro, que são pré-configuradas com alguns servidores NTP padrão (fallback): (_[0-3].suse.pool.ntp.org_).

A maneira mais fácil de configurar um servidor NTP específico é colocar um arquivo de configuração no diretório`/etc/systemd/timesyncd.conf.d`.
O diretório e o arquivo de configuração devem ser acessíveis pelo usuário `systemd-timesync`.

== Configurar um servidor NTP estático

A configuração NTP pode ser fornecida por meio de um snippet cloud-config adicionado à configuração MachineRegistration.

Precisaremos de:

* garantir que o diretório `timesyncd.conf.d` possa ser lido pelo usuário `systemd-timesync` 
* gravar o arquivo de configuração personalizado no diretório `timesyncd.conf.d` 
* Reinicie o serviço `systemd-timesyncd` para usar a nova configuração

Como exemplo, vamos ver como configurar `ntp.ripe.net` como o servidor NTP primário (linhas 6-14):

[,yaml]
----
config:
  cloud-config:
    users:
      - name: root
        passwd: root
    write_files:
      - content: |
          [Time]
          NTP=ntp.ripe.net
        path: /etc/systemd/timesyncd.conf.d/custom-ntp.conf
        permissions: 644
    runcmd:
      - chmod 755 /etc/systemd/timesyncd.conf.d
      - systemctl restart systemd-timesyncd
  elemental:
    install:
      device: /dev/vda
      reboot: true
machineInventoryLabels:
  element: fire
----

== Configurar o NTP a partir do DHCP

Para obter o servidor NTP da rede por meio da opção NTP DHCP, precisamos de um script de despachante do NetworkManager para reconfigurar dinamicamente o serviço `systemd-timesync` quando necessário.

Teremos que:* fornecer o script do despachante que cria e exclui os arquivos de configuração do systemd-timesyncd * habilitar o serviço NetworkManager-dispatcher

Veja as linhas 6-34 no exemplo de configuração MachineRegistration a seguir:

[,yaml]
----
config:
  cloud-config:
    users:
      - name: root
        passwd: root
    write_files:
      - content: |
          #! /usr/bin/bash

          [ -n "$CONNECTION_UUID" ] || exit

          INTERFACE=$1
          ACTION=$2

          case $ACTION in
              up | dhcp4-change | dhcp6-change)
                  [ -n "$DHCP4_NTP_SERVERS" ] || exit
                  mkdir -p /etc/systemd/timesyncd.conf.d/
                  cat<<EOF > /etc/systemd/timesyncd.conf.d/$CONNECTION_UUID.conf
          [Time]
          NTP=$DHCP4_NTP_SERVERS
          RootDistanceMaxSec=15
          EOF
                  systemctl restart systemd-timesyncd
                  ;;
              down)
                  rm -f /etc/systemd/timesyncd.conf.d/$CONNECTION_UUID.conf
                  systemctl restart systemd-timesyncd
                  ;;
          esac
        path: /etc/NetworkManager/dispatcher.d/10-update-timesyncd
        permissions: 700
    runcmd:
      - systemctl enable NetworkManager-dispatcher
  elemental:
    install:
      device: /dev/vda
      reboot: true
machineInventoryLabels:
  element: fire
----
