= 自定义主机名
:revdate: 2025-09-08
:page-revdate: {revdate}

== {elemental-product-name} 主机名管理概述

当主机从{elemental-product-name} ISO 启动时，主机名会临时设置_（暂存主机名_）为 DHCP 服务器提供的主机名。
如果 DHCP 服务器没有提供主机名，{elemental-product-name} ISO 会提供一个临时主机名，格式为：`+rancher-$\{RANDOM}+` 。

启动过程一结束，注册阶段就开始了：主机连接到{elemental-product-name} Operator，后者会为主机创建一个`+MachineInventory+` 。
{elemental-product-name} Operator 注册的每台主机都由`+MachineInventory+` 资源跟踪。

*与节点相关的`+MachineInventory+` 资源的`+name+` 是**最终设置给主机的**永久（静态）主机名*。
此永久主机名*仅在 K8s 群集配置阶段在节点上设置*。
在 K8s 配置阶段之前，节点主机名要么是 DHCP 分配的主机名，要么是`+rancher-$\{RANDOM}+` 。

在本节其余部分，我们将`+hostname+` 指_永久_主机名，即主机作为 K8s 群集的一部分进行配置后设置的主机名。

== 默认主机名

分配给每个新创建的 MachineInventory 的默认名称格式为`+m-{$UUID}+` 。
当主机被配置为群集的一部分时，该`+m-\{UUID}+` 名称将被设置为相应主机的主机名，取代先前分配的主机名（`+rancher-{$RANDOM}+` 或 DHCP 分配的主机名）。

== 设置自定义主机名

主机名可通过设置 xref:references/machineregistration-reference.adoc#_machinename[`+machineName+`]字段。

`+machineName+` 字段中设置的主机名应为模板形式，以便使用 SMBIOS 和硬件标签数据为每个注册节点生成唯一的主机名。

[IMPORTANT]
====
`+MachineRegistration+` 资源中的`+machineName+` 字段不仅是注册主机的主机名蓝本，也是为跟踪主机而创建的`+MachineInventory+` 资源的名称蓝本。

这意味着，如果不使用模板化的`+machineName+` 来为每台使用相同`+MachineRegistration+` 数据（即相同 ISO）启动的主机生成唯一的名称，则只有第一台注册主机会成功，其他主机都会失败：`+MachineInventory+` 名称必须是唯一的。
====


从"！！raw-loader！@site/examples/quickstart/registration-hardware-dhcphostname.yaml "导入注册信息

== 保留 DHCP 分配的主机名

为了在主机向操作员注册之前保留 DHCP 服务器分配的主机名，`+MachineRegistration+` 。 xref:references/machineregistration-reference.adoc#_machinename[`+machineName field+`]应设置为`+${System Data/Runtime/Hostname}+` 硬件标签。

这样，{elemental-product-name} 将在注册阶段使用当前主机名作为`+MachineInventory+` 名称，随后在配置阶段将其设置为主机的静态主机名。

.注册示例，主机名和机器清单名称设置为 DHCP 服务器获取的主机名
[,yaml]
----
include::example$quickstart/registration-hardware-dhcphostname.yaml[]
----
