= 单密码
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} 自托管

{stackstate-product-name} 开箱即用，只有一个密码配置，xref:/k8s-suse-rancher-prime.adoc#_installation[在安装时配置]。这样，用户就可以使用安装时必须提供的单个密码进行身份验证。

这是开始使用{stackstate-product-name} 的最简单方法，但对于生产而言，建议使用其他xref:/setup/security/authentication/authentication_options.adoc[身份验证选项]之一。

== 从外部秘密中获取密码

如果默认密码来自外部秘密，请按照以下xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[步骤]操作，但要填写以下数据：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

密码编码可以是其中之一：* 对于纯文本密码，请提供 `+$plain$your-password+` (`+$plain$+` 是表示纯文本的前缀） * 对于加密密码，提供`+bcrypt-hashed-password+`.使用`+htpasswd -bnBC 10 "" <password> | tr -d ':\n'+` 可以创建密码的加密哈希值。

== 另见

* xref:/setup/security/authentication/authentication_options.adoc[验证选项]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[预定义{stackstate-product-name} 角色的权限]
* xref:/setup/security/rbac/rbac_roles.adoc[创建 RBAC 角色]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[外部秘密]
