= Schnappschüsse wiederholen
:revdate: 2025-10-27
:page-revdate: {revdate}
:description: SUSE Observabilität

== Übersicht

Auf dieser Seite werden die genauen JSON-Nachrichten beschrieben, die für das Konsistenzmodell der Health-Synchronisierung Repeat Snapshots gesendet werden können.

== JSON-Eigenschaft: "Gesundheit"

Der Gesundheitszustand kann über die Eigenschaft `"health"` des xref:/configure/health/send-health-data/send-health-data.adoc#_common_json_object[gemeinsamen JSON-Objekts] an die SUSE Observability Receiver API gesendet werden.

[tabs]
====
Beispiel Gesundheit `repeat_snapshots` JSON::
+
--
[,javascript]
----
{
   "apiKey":"<STACKSTATE_RECEIVER_API_KEY>",
   "collection_timestamp":1585818978,
   "internalHostname":"lnx-343242.srv.stackstate.com",
   "health":[
      {
        "consistency_model": "REPEAT_SNAPSHOTS",
        "start_snapshot": {
          "repeat_interval_s": 50
          //"expiry_interval_s": 200 Optional
        },
        "stop_snapshot": {},
        "stream": {
          "urn": "urn:health:sourceId:streamId"
          //"sub_stream_id": "subStreamId" Optional
        },
        "check_states": [
          {
            "checkStateId": "checkStateId1",
            "message": "Server Running out of disk space",
            "health": "Deviating",
            "topologyElementIdentifier": "server-1",
            "name": "Disk Usage"
          },
          {
            "checkStateId": "checkStateId2",
            "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
            "health": "critical",
            "topologyElementIdentifier": "server-2",
            "name": "Health monitor"
          }
        ]
      }
   ]
}
----
--
====

Jeder Health Repeat Snapshot Daten-Payload hat die folgenden Details:

* *start_snapshot* - Optional. Der Beginn eines Schnappschusses muss vor der Verarbeitung von `check_states` verarbeitet werden. Dadurch kann SUSE Observability einen Stream-Snapshot mit dem zuvor empfangenen vergleichen und Prüfzustände löschen, die im Snapshot nicht mehr vorhanden sind. Sie enthält die folgenden Felder als Snapshot-Metadaten:
 ** *repeat_interval_s* - Zeit in Sekunden. Die Häufigkeit, mit der die externe Quelle Zustandsdaten an SUSE Observability senden soll. Der maximal zulässige Wert ist 1800 (30 Minuten).
 ** *expiry_interval_s* - Zeit in Sekunden. Die Zeit, die nach der letzten Aktualisierung gewartet werden muss, bevor eine externe Prüfung von SUSE Observability gelöscht wird. Erforderlich bei Verwendung von Substreams.
* *stop_snapshot* - Optional. Das Ende eines Schnappschusses wird nach der Verarbeitung `` descheck_states`` verarbeitet.
* *stream* - Objekt, das Aufschluss darüber gibt, welche Snapshots und `check_states` zusammengehören. Sie umfasst die folgenden Felder:
 ** *urn* - Datenquellen- und Stream-ID, kodiert als SUSE Observability xref:/configure/topology/identifiers.adoc[URN], die der folgenden Konvention entspricht: `urn:health:<sourceId>:<streamId>`, wobei `<sourceId>` der Name der externen Datenquelle und `<streamId>` ein eindeutiger Bezeichner für den Gesundheitsdatenstrom ist.
 ** *sub_stream_id* - Optional. Kennung für eine Teilmenge der Stream-Health-Daten. Wenn die Datenströme von mehreren Agenten verteilt und gemeldet werden, ermöglicht dies Snapshot-Lebenszyklen pro `sub_stream_id`
* *check_states* - Eine Liste von Prüfzuständen. Jeder Prüfstatus kann die folgenden Felder enthalten:
 ** *checkStateId* - Kennung für den Prüfstatus im externen System
 ** *Nachricht* - Optional. Meldung, die in der SUSE Observability-Benutzeroberfläche angezeigt werden soll. Die Daten werden als Markdown interpretiert, so dass Links zu der externen Systemprüfung, die den Status der externen Prüfung erzeugt hat, möglich sind.
 ** *health* - Einer der folgenden SUSE Observability Health-Statuswerte: `Clear`, `Deviating`, `Critical`.
 ** *topologyElementIdentifier* - Wird verwendet, um den Prüfstatus an ein SUSE Observability-Topologieelement zu binden.
 ** *name* - Name des externen Prüfstatus.

== Senden von Daten an SUSE Observability

Der Gesundheitszustand kann in einer JSON-Nachricht per HTTP POST übermittelt werden. Im folgenden Beispiel wird ein Snapshot mit zwei Prüfstatus von einem einzigen externen Überwachungssystem an SUSE Observability gesendet.

[,bash]
----
curl -X POST \
 '<STACKSTATE_RECEIVER_API_ADDRESS>' \
 -H 'Content-Type: application/json' \
 -d '{
  "collection_timestamp": 1548857167,
  "internalHostname": "local.test",
  "health": [
    {
      "consistency_model": "REPEAT_SNAPSHOTS",
      "start_snapshot": {
        "repeat_interval_s": 300
      },
      "stop_snapshot": {},
      "stream": {
        "urn": "urn:health:sourceId:streamId"
      },
      "check_states": [
        {
          "checkStateId": "checkStateId1",
          "message": "Server Running out of disk space",
          "health": "Deviating",
          "topologyElementIdentifier": "server-1",
          "name": "Disk Usage"
        },
        {
          "checkStateId": "checkStateId2",
          "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
          "health": "critical",
          "topologyElementIdentifier": "server-2",
          "name": "Health monitor"
        }
      ]
    }
  ]
}'
----
