include::partial$variables.adoc[]
= {project-name} 大規模環境における
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: {project-name} で{project-name}s を構成し、要求の厳しい大規模環境における高可用性とパフォーマンスを確保します。
:keywords: [kubewarden, "{project-name}", kubernetes, policyservers, production].
:doc-persona: キューブウォーデンオペレーター、キューブウォーデンインテグレーター
:doc-type: ハウツー
:doc-topic: オペレーターマニュアル、ポリシーサーバー、プロダクション
:sidebar_label: 規模に応じた展開
:sidebar_position: 21

このセクションでは、要求の厳しい大規模環境における{project-name} の実際の展開について詳述する。高可用性とパフォーマンスのために{short-project-name} を設定する方法と、高負荷時に期待されることを説明しています。

[IMPORTANT]
====
本番環境で{short-project-name} を実行するためのヒントをもっと見たい場合は、xref:/howtos/production-deployments.adoc[本番環境でのデプロイメントに関する]ドキュメントをご覧ください。
====

== 環境概要

インフラは約20のKubernetesクラスタで構成されている。これらのクラスターのうち最大のものは、その規模と資源量が大きいという特徴がある：

* ノード数：～400
* 名前空間: ~4,000
* 管理されたリソース：
** ポッドだ：10,000
** ロールバインディング13,000
** イングレス：12,000
** 配備：8,000
** サービス13,000

== {short-project-name} 構成

このような環境の要求に応えるため、{short-project-name} 、ワークロードの分離と高可用性に重点を置いて構成されている。

* ポリシーの実施：22`+ClusterAdmissionPolicies+` はクラスタ全体で実施され、名前空間固有の`+AdmissionPolicies+` はない。
* PolicyServerアーキテクチャ：ワークロードを分離するために、2つの別々の`+PolicyServer+` ：
** `+PolicyServer+` のひとつは、コンテキストを意識したポリシー専用である。
** 第二の`+PolicyServer+` 、その他の、コンテキストを意識しないポリシーを処理する。
* スケーラビリティとリソース：
** レプリカ：`+PolicyServer+` の各デプロイメントでは、大量のリクエストを処理するために15個のレプリカを実行している。
** 資源配分：各レプリカには300MBのメモリと4つのCPUコアが割り当てられている。

== パフォーマンス指標

このコンフィギュレーションは、予測可能なパフォーマンスを維持しながら、高率のアドミッション・リクエストの管理に成功している。

* 入場要求スループット：クラスタは、毎秒最大300の入場リクエスト（ウェブフックの検証と監査スキャンの両方を含む）を処理する。
* ポリシーの待ち時間：
** 典型的な待ち時間：コンテキストを考慮したポリシーの実行には通常500ミリ秒程度かかる。
** タイムアウト：この高スループット環境では、ウェブフックのタイムアウトは2.5秒、`+PolicyServer+` のタイムアウトは10秒に設定されている。ほとんどのリクエストは高速だが、インフラはAPIサーバーの安定性を損なうことなく、時折低速のオペレーションを処理できるように構築されている。

== スキャナー性能の監査

監査スキャナーは、膨大な数のリソースにおける継続的なコンプライアンスを保証するために利用される。

* 頻度：クラスタ全体の監査は4時間ごとに行われる。
* コンフィギュレーション：監査ジョブは、実行時間を短縮するために最大限の並列性が得られるように調整されている：

[source,shell]
----
--parallel-namespaces: "10"
--parallel-resources: "20"
--parallel-policies: "20"
--page-size: "1000"
----

* 監査期間：何万ものリソースを持つ最大のクラスタでも、完全な監査ジョブは以下の時間で完了します。
