include::partial$variables.adoc[]
= ValidatingAdmissionPolicy マイグレーション
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: ValidatingAdmissionPolicyを{project-name} 、kwctlコマンドのマイグレーション・ステップで移行し、ポリシーをスムーズに移行する。
:doc-persona: ["kubewarden-user"、"kubewarden-operator"、"kubewarden-distributor"、"kubewarden-integrator"]]。
:doc-topic: ["vap-migration"]
:doc-type: ["howto"]
:doctype: book
:keywords: ["{project-name}", "kubewarden", "kubernetes", "cel", "vap", "validatingadmissionpolicy"]
:current-version: {page-origin-branch}

Kubernetes v1.26から、https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/[ValidatingAdmissionPolicyは]、Kubernetesでカスタムアドミッションポリシーを記述する方法を提供します。ポリシーは、https://cel.dev/[Common Expression Language (CEL)]で記述され、https://kubernetes.io/docs/reference/using-api/cel/[] Kubernetes固有のいる。
Kubernetes v1.30でValidatingAdmissionPolicyが安定に達した。

{project-name} は、KubernetesのVAPポリシーをそのまま実行できるCELポリシーを提供する。
CELポリシーの詳細については、{short-project-name} のxref:../tutorials/writing-policies/CEL/01-intro-cel.adoc[ドキュメントを]ご覧ください。
xref:tutorials/writing-policies/CEL/01-intro-cel.adoc#_benefits_of_kubewardens_cel_policy_in_comparison_with_validatingadmissionpolicies[この段落では]、{short-project-name} を使用して VAP ポリシーを実行する利点について説明します。

このガイドでは、`+kwctl+` ツールを使用して、VAP ポリシーを{short-project-name} に移行する方法について説明します。

== マイグレーション手順

[NOTE]
====
このガイドに従うには、`+kwctl+` バージョン1.14.0以降を使用する必要があります。
====


`+ValidatingAdmissionPolicy+` のYAML定義を含むファイルが与えられたとする：

.`+ValidatingAdmissionPolicy+` 定義
[%collapsible]
======
[subs="+attributes",yaml]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "force-liveness-probe"
spec:
  failurePolicy: Fail
  variables:
    - name: containers_without_liveness_probe
      expression: |
        object.spec.template.spec.containers.filter(c, !has(c.livenessProbe)).map(c, c.name)
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  validations:
    - expression: |
        size(variables.containers_without_liveness_probe) == 0
      messageExpression: |
        'These containers are missing a liveness probe: ' + variables.containers_without_liveness_probe.join(' ')
      reason: Invalid
----
======

そして、`+ValidatingAdmissionPolicyBinding+` リソースを含むファイル：

.`+ValidatingAdmissionPolicyBinding+` 定義
[%collapsible]
======
[subs="+attributes",shell]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "kw-scaffold-demo"
spec:
  policyName: "force-liveness-probe"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchLabels:
        docs.kubewarden.io/vap-migration: enabled
----

======

以下の手順で、ポリシーを{short-project-name} に移行できます：

.`+kwctl+` ポリシー移行コマンド
[%collapsible]
======

[subs="+attributes",shell]
----
$ kwctl scaffold vap \
    -p vap.yml \
    -b vap-binding.yml
----

======

このコマンドは次のような出力を生成する：

.マイグレーションからのアウトプット
[%collapsible]
======

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: kw-scaffold-demo
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:latest
  settings:
    failurePolicy: Fail
    variables:
      - expression: |
          object.spec.template.spec.containers.filter(c, !has(c.livenessProbe)).map(c, c.name)
        name: containers_without_liveness_probe
    validations:
      - expression: |
          size(variables.containers_without_liveness_probe) == 0
        messageExpression: |
          'These containers are missing a liveness probe: ' + variables.containers_without_liveness_probe.join(' ')
        reason: Invalid
  rules:
    - apiGroups:
        - apps
      apiVersions:
        - v1
      resources:
        - deployments
      operations:
        - CREATE
        - UPDATE
  mutating: false
  namespaceSelector:
    matchLabels:
      docs.kubewarden.io/vap-migration: enabled
----
======

[NOTE]
====

このコマンドは、`+latest+` バージョンの CEL ポリシーの使用について警告する：

[subs="+attributes",console]
----
024-06-24T16:00:16.516062Z  WARN kwctl::scaffold:
  Using the 'latest' version of the CEL policy could lead to unexpected behavior.
  It is recommended to use a specific version to avoid breaking changes.
----

変更を壊さないためにも、特定のバージョンを使用することが推奨される。

これは、`+--cel-policy+` フラグを使って、次のように行うことができる：

[subs="+attributes",console]
----
$ kwctl scaffold vap \
    --cel-policy ghcr.io/kubewarden/policies/cel-policy:v1.0.1 \
    -p vap.yml \
    -b vap-binding.yml
----

====
