ifdef::ss-ff-stackpacks2_enabled[]
= Apresentação da interface do usuário
:revdate: 2026-01-08
:page-revdate: {revdate}
:description: Apresentação da interface do usuário

[IMPORTANT]
====
*Status:* Em desenvolvimento ativo.

*Disponibilidade:* Por trás da bandeira de recursos do StackPacks 2.0. Consulte a xref:/setup/custom-integrations/overview.adoc[Visão geral das integrações personalizadas] para saber como ativar o recurso.

Esta documentação descreve a intenção do projeto atual e a superfície de configuração de alto nível.

Observação: nenhum comportamento e recurso foi implementado ainda.

Como esse recurso está em desenvolvimento ativo, o comportamento, os esquemas e os recursos podem mudar à medida que o modelo evolui.
====

Esta seção documenta o modelo de *apresentação da interface do usuário* introduzido como parte do *StackPacks 2.0*.

== Visão geral

O modelo de apresentação de componentes documentado aqui declara como os componentes (por exemplo, pods, VMs, serviços) são apresentados na interface de usuário do {stackstate-product-name}.
Ele se concentra exclusivamente em *questões de apresentação*, como nomes, ícones, tabelas, páginas de visão geral e de destaque, filtros e posicionamento de itens de menu.

O objetivo desse modelo é fornecer uma maneira mais flexível e extensível de definir o comportamento da interface do usuário para os componentes, em comparação com a abordagem existente e mais fragmentada.

endif::ss-ff-stackpacks2_enabled[]
