= Solução de problemas de restauração
:revdate: 2025-07-03
:page-revdate: {revdate}

[WARNING]
====
Quando uma restauração for executada, não reinicie o site `+rancher-system-agent+` em nós elementares, pois ele pode ficar obsoleto e terminar com o seguinte erro:

`+panic: error while connecting to Kubernetes cluster: the server has asked for the client to provide credentials+`

Se você tiver esse problema, siga o procedimento abaixo.
====


Antes de iniciar uma restauração, você precisa copiar `+/var/lib/rancher/agent/rancher2_connection_info.json+` do nó elementar para um local onde você tenha acesso com a interface do usuário do Rancher.

Depois que o arquivo for copiado, faça o download do script `+rancher-agent-token-update.sh+` do https://github.com/rancher/elemental[repositório]

[,shell]
----
wget -q https://raw.githubusercontent.com/rancher/elemental/main/scripts/rancher-agent-token-update && chmod +x rancher-agent-token-update
----

Executar o script sem nenhuma opção adicional:

[,shell]
----
./rancher-agent-token-update
----

Após a conclusão bem-sucedida da restauração, copie `+rancher2_connection_info.json+` de volta ao nó elementar para o caminho`+/var/lib/rancher/agent/rancher2_connection_info.json+`. Por fim, reinicie o serviço `+rancher-system-agent+`:

[,shell]
----
systemctl restart rancher-system-agent
----
