include::partial$variables.adoc[]
= 集装箱登记能力
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 探索容器注册表功能，包括计算 OCI 清单摘要和获取 OCI 对象清单。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "container-registry"]
:doc-type: ["reference"]
:keywords: ["kubewarden"、"kubernetes"、"策略规范"、"注册表功能"]
:sidebar_label: 集装箱登记能力
:current-version: {page-origin-branch}

容器注册可用于分发多种类型的 OCI 对象。
从众所周知的容器映像到通用的 OCI 工件。
OCI 工件用于存储{project-name} 策略、Helm 图表等对象。

这些功能由{short-project-name} 主机提供，用于与容器注册表交互。

== 获取 OCI 清单摘要

该回调会计算 OCI 清单的摘要。摘要可用于识别 OCI 注册表中存储的对象。这是一种不可变的方式，而`+tags+` 是可变的。

=== 缓存

计算摘要涉及{short-project-name} 策略主机和远程注册表之间的一系列网络请求。
这些操作可能会耗费大量时间，因此会将结果缓存 1 分钟。

=== 认证

与私有注册表的交互要求{short-project-name} 策略主机对远程注册表进行身份验证。

策略主机将使用用于从远程注册表获取策略的同一组凭据。

=== 通信协议

这是用于公开此功能的 waPC 协议的说明：

==== waPC 功能 -`+v1/manifest_digest+` 输入

[,hcl]
----
# OCI URI - JSON encoded string
string
----

==== waPC 功能 -`+v1/manifest_digest+` 输出

[,hcl]
----
{
  # digest of the OCI object
  "digest": string
}
----

例如，在请求`+busybox:latest+` 图像的清单摘要时，有效载荷为

* 输入有效载荷： `+"busybox:latest"+`
* 输出有效载荷： `+{ "digest": "sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f"}+`

== OCI 清单

该回调将获取 OCI 对象清单。这些信息可用来识别一个或多个平台的具体图像清单。或图像的单一图像清单。

=== 缓存

获取这些信息涉及{short-project-name}策略主机和远程注册表之间的网络请求。这些操作耗时较长，因此会将结果缓存 1 分钟。

=== 认证

与私有注册表的交互要求{short-project-name} 策略主机对远程注册表进行身份验证。

策略主机使用的凭证集与从远程注册表获取策略时使用的凭证集相同。

=== 通信协议

这是用于公开此功能的 waPC 协议的说明：

==== waPC 功能 -`+v1/oci_manifest+` 输入

[,hcl]
----
# OCI URI - JSON encoded string
string
----

==== waPC 功能 -`+v1/oci_manifest+` 输出

[,hcl]
----
{
    "schemaVersion": 2,
        "mediaType": "application/vnd.oci.image.index.v1+json",
        "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:7d5e84b9314ba7058bfa209881919146ffc4a89c5ba14cfa8270a18c8d418c44",
            "size": 1048,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:ae1e98105555f3983496c15c70dafc87639b77830953d6470694b47e0e063e25",
            "size": 1048,
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:e9fc0f86e26366abf29fd29e8c09d00df717f9038fd4298eaa39a0a2b4361fa4",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:7d5e84b9314ba7058bfa209881919146ffc4a89c5ba14cfa8270a18c8d418c44",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:e8904ebb2841dc19ae458436eb01ddea3e8d6ea653c7d9476537f4029b1f45a2",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:ae1e98105555f3983496c15c70dafc87639b77830953d6470694b47e0e063e25",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        }
    ]
}

OR

{
    "schemaVersion": 2,
        "mediaType": "application/vnd.oci.image.manifest.v1+json",
        "config": {
            "mediaType": "application/vnd.oci.image.config.v1+json",
            "digest": "sha256:61dc3269b9e8faeea32128560cdbd355e8c1dff31e32abc0223be039c5cc5e2d",
            "size": 1775
        },
        "layers": [
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:67d998e418791ec2955ec99753eb55f03ca96538976e5ccebfec08eae20056b5",
            "size": 57033795
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:be6185edcab66334dd5c7c2273fd6254100ece960e087541f3dba0616c440038",
            "size": 188411978
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:58a13f6770904193ca67beb50d424e69a39579e1581dbf8e02e1751f3b75f932",
            "size": 70078992
        }
        ],
        "annotations": {
            "org.opencontainers.image.base.digest": "sha256:67a7c41ccd5dfcb08face86546f0d25c0740f0d0225e39fecb8bbae8b95b847a",
            "org.opencontainers.image.base.name": "docker.io/library/debian:latest"
        }
}
----

例如，在请求`+ghcr.io/kubewarden/policy-server:v1.10.0+` 图像的清单时，有效载荷将是

* 输入有效载荷： `+"ghcr.io/kubewarden/policy-server:v1.10.0"+`
* 输出有效载荷：从注册表获得的成功响应的正文。
它可以是https://github.com/opencontainers/image-spec/blob/main/image-index.md[索引图像] OCI，也可以是https://github.com/opencontainers/image-spec/blob/main/manifest.md[图像清单] OCI。
具体内容可能会根据注册表和图像的不同而有所变化。

== OCI 清单和配置

该回调会获取 OCI 图像清单及其配置。这些信息可用于获取容器映像清单和容器运行时用于运行容器映像的配置信息。

=== 缓存

获取这些信息涉及{short-project-name}策略主机和远程注册表之间的网络请求。这些操作耗时较长，因此会将结果缓存 1 分钟。

=== 认证

与私有注册表的交互要求{short-project-name} 策略主机对远程注册表进行身份验证。

策略主机使用的凭证集与从远程注册表获取策略时使用的凭证集相同。

=== 通信协议

这是用于公开此功能的 waPC 协议的说明：

==== waPC 功能 -`+v1/oci_manifest_config+` 输入

[,hcl]
----
# OCI URI - JSON encoded string
string
----

==== waPC 功能 -`+v1/oci_manifest_config+` 输出

[,hcl]
----
{
  "manifest": {
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "config": {
      "mediaType": "application/vnd.oci.image.config.v1+json",
      "digest": "sha256:bc3511804cb29da6333f0187a333eba13a43a3a0a1737e9b50227a5cf057af74",
      "size": 1592
    },
    "layers": [
      {
        "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
        "digest": "sha256:294efa324e89a020b06df261f77903fb9f46fdee79c54e4f6589f786f6c31bec",
        "size": 428
      },
      {
        "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
        "digest": "sha256:f0936413f7d0757b41777a624e5be83da28789d0c4b8b3f46853ca9c3bb6300f",
        "size": 422
      },
      {
        "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
        "digest": "sha256:cd2adfe5e808335e0c30eff616a9852a94cfbf8ecd455d1b893e1c858ddc3aeb",
        "size": 22357278
      },
      {
        "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
        "digest": "sha256:6c7ec51ccec3d4438c94e697258085ddf825c1e711df4d923b1794794196cf06",
        "size": 37415
      }
    ]
  },
  "digest": "sha256:6ebc3e17a9804a8d385fee819554ad95a05072d022c5bd2dd27556a5752d47f5",
  "config": {
    "created": "2024-06-05T13:48:01.671482413Z",
    "architecture": "amd64",
    "os": "linux",
    "config": {
      "User": "65533:65533",
      "ExposedPorts": {
        "3000/tcp": {}
      },
      "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ],
      "Entrypoint": [
        "/policy-server"
      ],
      "WorkingDir": "/"
    },
    "rootfs": {
      "type": "layers",
      "diff_ids": [
        "sha256:79f61adc25589b7b467a6becca5756f3b722ab7f9d0c18c205e89c08fdc8d45d",
        "sha256:2a5e7791442784b3614921dcb51afdbe94ae9bfd3752e22e5eb81ce731f5bfbf",
        "sha256:0d893e5416389fd105bc81d3694a5d5dbffc41237291df0aaa4efbc26632e91c",
        "sha256:018ce7bd6fd46306e129aca44c1c103675dbe29e3aa842a0b7fb01507e8d02d2"
      ]
    },
    "history": [
      {
        "created": "2024-06-05T13:48:00.432722149Z",
        "created_by": "COPY /etc/passwd /etc/passwd # buildkit",
        "comment": "buildkit.dockerfile.v0"
      },
      {
        "created": "2024-06-05T13:48:00.469118621Z",
        "created_by": "COPY /etc/group /etc/group # buildkit",
        "comment": "buildkit.dockerfile.v0"
      },
      {
        "created": "2024-06-05T13:48:01.653480931Z",
        "created_by": "COPY --chmod=0755 policy-server-x86_64 /policy-server # buildkit",
        "comment": "buildkit.dockerfile.v0"
      },
      {
        "created": "2024-06-05T13:48:01.671482413Z",
        "created_by": "ADD Cargo.lock /Cargo.lock # buildkit",
        "comment": "buildkit.dockerfile.v0"
      },
      {
        "created": "2024-06-05T13:48:01.671482413Z",
        "created_by": "USER 65533:65533",
        "comment": "buildkit.dockerfile.v0",
        "empty_layer": true
      },
      {
        "created": "2024-06-05T13:48:01.671482413Z",
        "created_by": "EXPOSE map[3000/tcp:{}]",
        "comment": "buildkit.dockerfile.v0",
        "empty_layer": true
      },
      {
        "created": "2024-06-05T13:48:01.671482413Z",
        "created_by": "ENTRYPOINT [\"/policy-server\"]",
        "comment": "buildkit.dockerfile.v0",
        "empty_layer": true
      }
    ]
  }
}
----

例如，在请求`+ghcr.io/kubewarden/policy-server:v1.13.0+` 图像的图像清单和配置时，有效载荷应为

* 输入有效载荷： `+"ghcr.io/kubewarden/policy-server:v1.13.0"+`
* 输出有效载荷：从注册表获得的成功响应的正文。它将包含https://github.com/opencontainers/image-spec/blob/main/manifest.md[OCI 图像清单]、图像摘要和https://github.com/opencontainers/image-spec/blob/main/config.md[OCI 图像配置]。
