= Senha única
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Auto-hospedado

O site {stackstate-product-name} vem pronto para uso com uma configuração de senha única, xref:/k8s-suse-rancher-prime.adoc#_installation[configurada durante a instalação]. Isso autentica os usuários com uma única senha que deve ser fornecida durante a instalação. 

Essa é a maneira mais simples de começar a usar o {stackstate-product-name}, mas, para produção, recomenda-se uma das outras xref:/setup/security/authentication/authentication_options.adoc[opções de autenticação].

== Obter a senha de um segredo externo

Quando a senha padrão for proveniente de um segredo externo, siga xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[estas etapas], mas preencha os dados a seguir:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

A codificação da senha pode ser uma das seguintes:* Para uma senha de texto simples, forneça: `+$plain$your-password+` (`+$plain$+` é um prefixo que indica texto simples) * Para uma senha criptografada, forneça: `+bcrypt-hashed-password+`. A criação de um hash criptografado da senha pode ser feita usando `+htpasswd -bnBC 10 "" <password> | tr -d ':\n'+`.

== Veja também

* xref:/setup/security/authentication/authentication_options.adoc[Opções de autenticação]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permissões para funções predefinidas em {stackstate-product-name} ]
* xref:/setup/security/rbac/rbac_roles.adoc[Criar funções RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Segredos externos]
