= SUSE Observabilityのドキュメント
:revdate: 2025-07-10
:page-revdate: {revdate}

これは最新のSUSE Observabilityドキュメントです。左のコンテンツメニューからトピックを選択します。

古いバージョンのドキュメントは、https://archivedocs.stackstate.com[アーカイブを]ご利用ください。

== スタート

Rancher Primeユーザの方はxref:/k8s-suse-rancher-prime.adoc[Rancher Prime getting started guideを]、SUSE Cloud Observabilityユーザの方はxref:/k8s-quick-start-guide.adoc[クイックスタートガイドを]、AWS上でSUSE Cloud Observabilityを実行している方はxref:/suse-cloud-observability-quick-start-guide.adoc[SUSE Cloud Observabilityクイックスタートガイドを]ご覧ください。

== 何かが見つからない？

右上の検索バーをご利用ください。ドキュメントが不足していると思われる場合は、https://scc.suse.com/[SUSE Observabilityサポートサイト]でお知らせください。

== トラブルシューティングとサポート

質問は？私たちがお手伝いします。https://scc.suse.com/[SUSE Observabilityサポート]サイトでサポートチームを検索してください。

== SUSE Observability セルフホスト

SUSE Observability Self-hostedを使用して、自社のデータセンターまたはクラウドから広範なテクノロジーを監視できます。

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability セルフホスト]

== SUSE Cloud Observability

SUSE Cloud Observabilityを使用して、KubernetesやAWSサービスなどのクラウド技術を監視します。

xref:/suse-cloud-observability/user-management.adoc[SUSE Cloud Observabilityのドキュメント]
