= SUSE Observabilityクイックスタートガイド
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability
:doctype: book

== 概要

SUSE Observability SaaSインスタンスのセットアップと設定が完了すると、SUSE Observabilityから必要なログイン情報が記載されたメールが送信されます。このクイックスタートガイドでは、SUSE Observability SaaSインスタンスに自分のデータを取り込む方法を説明します。

クラスタをSUSE Observabilityに統合するには、適切な環境に合わせて、次のいずれかのガイドに従ってください。

* <<_amazon_eks,Amazon EKS>>
* <<_azure_aks,Azure AKS>>
* <<_google_gke,Google GKE>>
* <<_kubernetes,Kubernetes>>
* <<_kops,KOPS>>
* <<_openshift,OpenShift>>
* <<_self_hosted,セルフホスト>>


== Kubernetes

Kubernetesクラスタからトポロジ、イベント、ログ、変更、およびメトリックデータを収集し、SUSE Observabilityで利用できるようにするために、Kubernetes統合を設定します。

=== 対応バージョン

|===
| 対応Kubernetesバージョン

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
|===

=== 対応ランタイム

|===
| 対応ランタイム

| コンテナD
| CRI-O
|===

=== Kubernetesの前提条件

SUSE Observability Kubernetesインテグレーションを設定するには、以下のものが必要です：

* 稼働中のKubernetesクラスタ。
* Helmバージョン3.13.1以上。
* `create privileged pods` 、`ClusterRoles` 、`ClusterRoleBindings` の権限を持つユーザー：
 ** ClusterRoleとClusterRoleBindingは、SUSE ObservabilityエージェントにKubernetes APIへのアクセス権限を付与するために必要です。
 ** SUSE Observability Agentは、ネットワーク接続とホスト情報の情報を収集できるように、特権ポッドで実行する必要があります。

=== Kubernetes統合のセットアップ

[CAUTION]
====
始める前に、<<_prerequisites_for_kubernetes,Kubernetesの前提条件を>>確認してください。
====


KubernetesクラスタからSUSE Observabilityにデータを取得するには、以下の手順に従ってください：

. SUSE Observability helmリポジトリをローカルのhelmクライアントに追加します：
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. SUSE Observability UIで、画面左上をクリックしてメインメニューを開き、`StackPacks` >`Kubernetes` に進みます。
. Kubernetes StackPackの新しいインスタンスをインストールする：
 ** *Kubernetesクラスタ名の*指定
  *** この名前は、SUSE Observabilityでクラスタを識別するために使用されます。
 ** *インストールを*クリックする。
. StackPackをインストールした後、SUSE Observability UIで提供されるhelmコマンドを使用して、SUSE Observability Agent、Cluster Agent、Checks Agent、およびkube-state-metricsをクラスタに展開します。
 ** Agentがデプロイされると、データの収集が開始され、SUSE Observabilityにプッシュされます。

[CAUTION]
====
セルフホスト型のエアギャップ環境で実行する場合は、xref:/k8s-suse-rancher-prime-agent-air-gapped.adoc[エアギャップ手順書に従って]、エージェントのインストールを最初に準備します。
====


== OpenShift

OpenShiftクラスタからトポロジー、イベント、ログ、変更、メトリクスデータを収集し、SUSE Observabilityで利用できるようにするために、OpenShift統合を設定します。

=== 対応バージョン

|===
| OpenShift Version | 対応Kubernetesバージョン | OpenShiftサポート終了

| OpenShift 4.17
| Kubernetes 1.30
| 2026年4月1日

| OpenShift 4.16
| Kubernetes 1.29
| 2025年12月27日

| OpenShift 4.15
| Kubernetes 1.28
| 2025年8月27日

| OpenShift 4.14
| Kubernetes 1.27
| 2025年5月1日

| OpenShift 4.13
| Kubernetes 1.26
| 2024年11月17日

| OpenShift 4.12
| Kubernetes 1.25
| 2024年7月17日

| OpenShift 4.11
| Kubernetes 1.24
| 2024年2月10日

| OpenShift 4.10
| Kubernetes 1.23
| 2023年9月10日

| OpenShift 4.9
| Kubernetes 1.22
| 2023年4月18日
|===

=== 対応ランタイム

|===
| 対応ランタイム

| コンテナD
| CRI-O
|===

=== OpenShiftの前提条件

SUSE Observability OpenShiftインテグレーションをセットアップするには、以下のものが必要です：

* 稼働中のOpenShiftクラスタ。
* Helmバージョン3.13.1以上。
* `create privileged pods` 、`ClusterRoles` 、`ClusterRoleBindings` の権限を持つユーザー：
 ** ClusterRoleとClusterRoleBindingは、SUSE ObservabilityエージェントにKubernetes APIへのアクセス権限を付与するために必要です。
 ** SUSE Observability Agentは、ネットワーク接続とホスト情報の情報を収集できるように、特権ポッドで実行する必要があります。

=== OpenShiftとの統合を設定する

[CAUTION]
====
始める前に、<<_prerequisites_for_openshift,Kubernetesの前提条件を>>確認してください。
====


KubernetesクラスタからSUSE Observabilityにデータを取得するには、以下の手順に従ってください：

. SUSE Observability helmリポジトリをローカルのhelmクライアントに追加します：
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. SUSE Observability UIで、画面左上をクリックしてメインメニューを開き、`StackPacks` >`Integrations` >`Kubernetes` に進みます。
. Kubernetes StackPackの新しいインスタンスをインストールする：
 ** *Kubernetesクラスタ名の*指定
  *** この名前は、SUSE Observabilityでクラスタを識別するために使用されます。
 ** *インストールを*クリックする。
. StackPackをインストールした後、SUSE Observability UIで提供されるhelmコマンドを使用して、SUSE Observability Agent、Cluster Agent、Checks Agent、およびkube-state-metricsをクラスタに展開します。
 ** Agentがデプロイされると、データの収集が開始され、SUSE Observabilityにプッシュされます。


== Amazon EKS

Amazon EKSクラスタからトポロジ、イベント、ログ、変更、メトリクスのデータを収集し、SUSE Observabilityで利用できるようにするために、Amazon EKS統合を設定します。

=== 対応バージョン

|===
| Kubernetesバージョン | アマゾンEKSリリース | アマゾンEKSサポート終了 | アマゾンEKS延長サポート終了

| 1.32
| 2025年1月23日
| 2026年3月23日
| 2027年3月23日

| 1.31
| 2024年9月26日
| 2025年11月26日
| 2026年11月26日

| 1.30
| 2024年5月23日
| 2025年7月23日
| 2026年7月23日

| 1.29
| 2024年1月23日
| 2025年3月23日
| 2026年3月23日

| 1.28
| 2023年9月26日
| 2024年11月01日
| 2025年11月26日

| 1.27
| 2023年5月24日
| 2024年7月
| 2025年7月24日

| 1.26
| 2023年4月11日
| 2024年6月
| 2025年6月11日

| 1.25
| 2023年2月21日
| 2024年5月
| 2025年5月1日

| 1.24
| 2022年11月15日
| 2024年1月
| 2025年1月31日

| 1.23
| 2022年8月11日
| 2023年10月11日
| 2024年10月11日

| 1.22
| 2022年4月4日
| 2023年6月4日
| 2024年9月1日

| 1.21
| 2021年7月19日
| 2023年2月15日
| 2024年7月15日

| 1.20
| 2021年5月18日
| 2022年11月1日
| N/A

| 1.19
| 2021年2月16日
| 2022年8月1日
| N/A

| 1.18
| 2020年10月13日
| 2022年8月15日
| N/A
|===

=== 対応ランタイム

|===
| 対応ランタイム

| コンテナD
| CRI-O
|===

=== Amazon EKSの前提条件

SUSE Observability Amazon EKS統合を設定するには、次のものが必要です：

* 稼働中のAmazon EKSクラスタ。
* Helmバージョン3.13.1以上。
* `create privileged pods` 、`ClusterRoles` 、`ClusterRoleBindings` の権限を持つユーザー：
 ** ClusterRoleとClusterRoleBindingは、SUSE ObservabilityエージェントにKubernetes APIへのアクセス権限を付与するために必要です。
 ** SUSE Observability Agentは、ネットワーク接続とホスト情報の情報を収集できるように、特権ポッドで実行する必要があります。

=== Amazon EKSとの統合を設定する

[CAUTION]
====
始める前に、<<_prerequisites_for_amazon_eks,Kubernetesの前提条件を>>確認してください。
====


KubernetesクラスタからSUSE Observabilityにデータを取得するには、以下の手順に従ってください：

. SUSE Observability helmリポジトリをローカルのhelmクライアントに追加します：
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. SUSE Observability UIで、画面左上をクリックしてメインメニューを開き、`StackPacks` >`Integrations` >`Kubernetes` に進みます。
. Kubernetes StackPackの新しいインスタンスをインストールする：
 ** *Kubernetesクラスタ名の*指定
  *** この名前は、SUSE Observabilityでクラスタを識別するために使用されます。
 ** *インストールを*クリックする。
. StackPackをインストールした後、SUSE Observability UIで提供されるhelmコマンドを使用して、SUSE Observability Agent、Cluster Agent、Checks Agent、およびkube-state-metricsをクラスタに展開します。
 ** Agentがデプロイされると、データの収集が開始され、SUSE Observabilityにプッシュされます。


== Google GKE

Google GKE統合を設定して、Google GKEクラスタからトポロジ、イベント、ログ、変更、メトリクスのデータを収集し、SUSE Observabilityで利用できるようにします。

=== 対応バージョン

|===
| Kubernetesバージョン | グーグルGKEリリース | Google GKE サポート終了のお知らせ | Google GKE延長サポート終了のお知らせ

| 1.32
| 2025年2月
| Q2, 2026
| Q1, 2027

| 1.31
| 2024年10月22日
| 2025年12月22日
| 2026年10月22日

| 1.30
| 2024年7月30日
| 2025年9月30日
| 2026年7月30日

| 1.29
| 2024年1月25日
| 2025年3月21日
| 2026年1月25日

| 1.28
| 2023年12月4日
| 2025年2月4日
| 2025年12月4日

| 1.27
| 2023年6月14日
| 2024年8月31日
| 2025年6月14日

| 1.26
| 2023年4月14日
| 2024年6月30日
| N/A
|===

=== 対応ランタイム

|===
| 対応ランタイム

| コンテナD
| CRI-O
|===

=== Google GKE の前提条件

SUSE Observability Google GKE統合を設定するには、次のものが必要です：

* 稼働中のGoogle GKEクラスタ。
* Helmバージョン3.13.1以上。
* `create privileged pods` 、`ClusterRoles` 、`ClusterRoleBindings` の権限を持つユーザー：
 ** ClusterRoleとClusterRoleBindingは、SUSE ObservabilityエージェントにKubernetes APIへのアクセス権限を付与するために必要です。
 ** SUSE Observability Agentは、ネットワーク接続とホスト情報の情報を収集できるように、特権ポッドで実行する必要があります。

=== Google GKE統合の設定

[CAUTION]
====
始める前に、<<_prerequisites_for_google_gke,Kubernetesの前提条件を>>確認してください。
====


KubernetesクラスタからSUSE Observabilityにデータを取得するには、以下の手順に従ってください：

. SUSE Observability helmリポジトリをローカルのhelmクライアントに追加します：
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. SUSE Observability UIで、画面左上をクリックしてメインメニューを開き、`StackPacks` >`Integrations` >`Kubernetes` に進みます。
. Kubernetes StackPackの新しいインスタンスをインストールする：
 ** *Kubernetesクラスタ名の*指定
  *** この名前は、SUSE Observabilityでクラスタを識別するために使用されます。
 ** *インストールを*クリックする。
. StackPackをインストールした後、SUSE Observability UIで提供されるhelmコマンドを使用して、SUSE Observability Agent、Cluster Agent、Checks Agent、およびkube-state-metricsをクラスタに展開します。
 ** Agentがデプロイされると、データの収集が開始され、SUSE Observabilityにプッシュされます。


== Azure AKS

Azure AKSクラスタからトポロジー、イベント、ログ、変更、およびメトリクスデータを収集し、SUSE Observabilityで利用できるようにするために、Azure AKS統合を設定します。

=== 対応バージョン

|===
| Kubernetesバージョン | AKS GA | Azure AKS エンド・オブ・ライフ | プラットフォームのサポート

| 1.32
| 2024年6月
| 2026年3月
| 1.36GAまで

| 1.31
| 2024年11月
| 2025年11月
| 1.35GAまで

| 1.30
| 2024年6月
| 2025年7月
| 1.34GAまで

| 1.29
| 2024年3月
| 2025年1月
| 1.33GAまで

| 1.28
| 2023年11月
| 2024年11月
| 1.32GAまで

| 1.27
| 2023年7月
| 2024年7月
| 2025年7月
|===

=== 対応ランタイム

|===
| 対応ランタイム

| コンテナD
| CRI-O
|===

=== Azure AKSの前提条件

SUSE Observability Azure AKSインテグレーションをセットアップするには、以下のものが必要です：

* 稼働中のAzure AKS Cluster。
* Helmバージョン3.13.1以上。
* `create privileged pods` 、`ClusterRoles` 、`ClusterRoleBindings` の権限を持つユーザー：
 ** ClusterRoleとClusterRoleBindingは、SUSE ObservabilityエージェントにKubernetes APIへのアクセス権限を付与するために必要です。
 ** SUSE Observability Agentは、ネットワーク接続とホスト情報の情報を収集できるように、特権ポッドで実行する必要があります。

=== Azure AKSインテグレーションをセットアップする

[CAUTION]
====
始める前に、<<_prerequisites_for_azure_aks,Kubernetesの前提条件を>>確認してください。
====


KubernetesクラスタからSUSE Observabilityにデータを取得するには、以下の手順に従ってください：

. SUSE Observability helmリポジトリをローカルのhelmクライアントに追加します：
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. SUSE Observability UIで、画面左上をクリックしてメインメニューを開き、`StackPacks` >`Integrations` >`Kubernetes` に進みます。
. Kubernetes StackPackの新しいインスタンスをインストールする：
 ** *Kubernetesクラスタ名の*指定
  *** この名前は、SUSE Observabilityでクラスタを識別するために使用されます。
 ** *インストールを*クリックする。
. StackPackをインストールした後、SUSE Observability UIで提供されるhelmコマンドを使用して、SUSE Observability Agent、Cluster Agent、Checks Agent、およびkube-state-metricsをクラスタに展開します。
 ** Agentがデプロイされると、データの収集が開始され、SUSE Observabilityにプッシュされます。


== KOPS

KOPSクラスタからトポロジ、イベント、ログ、変更、メトリクスのデータを収集し、SUSE Observabilityで利用できるようにするために、KOPS統合を設定します。

=== 対応バージョン

|===
| 対応Kubernetesバージョン

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== 対応ランタイム

|===
| 対応ランタイム

| コンテナD
| CRI-O
|===

=== KOPSの前提条件

SUSE Observability KOPSインテグレーションを設定するには、以下のものが必要です：

* 稼働中のKOPSクラスタ。
* Helmバージョン3.13.1以上。
* `create privileged pods` 、`ClusterRoles` 、`ClusterRoleBindings` の権限を持つユーザー：
 ** ClusterRoleとClusterRoleBindingは、SUSE ObservabilityエージェントにKubernetes APIへのアクセス権限を付与するために必要です。
 ** SUSE Observability Agentは、ネットワーク接続とホスト情報の情報を収集できるように、特権ポッドで実行する必要があります。

=== KOPS統合の設定

[CAUTION]
====
始める前に、<<_prerequisites_for_kops,Kubernetesの前提条件を>>確認してください。
====


KubernetesクラスタからSUSE Observabilityにデータを取得するには、以下の手順に従ってください：

. SUSE Observability helmリポジトリをローカルのhelmクライアントに追加します：
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. SUSE Observability UIで、画面左上をクリックしてメインメニューを開き、`StackPacks` >`Integrations` >`Kubernetes` に進みます。
. Kubernetes StackPackの新しいインスタンスをインストールする：
 ** *Kubernetesクラスタ名の*指定
  *** この名前は、SUSE Observabilityでクラスタを識別するために使用されます。
 ** *インストールを*クリックする。
. StackPackをインストールした後、SUSE Observability UIで提供されるhelmコマンドを使用して、SUSE Observability Agent、Cluster Agent、Checks Agent、およびkube-state-metricsをクラスタに展開します。
 ** Agentがデプロイされると、データの収集が開始され、SUSE Observabilityにプッシュされます。


== セルフホスト

セルフホスト型クラスタからトポロジ、イベント、ログ、変更、メトリクスデータを収集し、SUSE Observabilityで利用できるようにするために、セルフホスト型統合を設定します。

=== 対応バージョン

|===
| 対応Kubernetesバージョン

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== 対応ランタイム

|===
| 対応ランタイム

| コンテナD
| CRI-O
|===

=== セルフホスティングの前提条件

SUSE Observability Self-hostedインテグレーションをセットアップするには、以下のものが必要です：

* 稼働中のセルフホスト型クラスタ。
* Helmバージョン3.13.1以上。
* `create privileged pods` 、`ClusterRoles` 、`ClusterRoleBindings` の権限を持つユーザー：
 ** ClusterRoleとClusterRoleBindingが必要である：
  *** SUSE Observability AgentにKubernetes APIへのアクセス権限を付与します。
  *** xref:/setup/agent/k8sTs-agent-request-tracing.adoc[リクエストトレースの]一部である変異検証ウェブフック用のシークレットを生成する
 ** SUSE Observability Agentは、ネットワーク接続とホスト情報の情報を収集できるように、特権ポッドで実行する必要があります。

=== セルフホスト・インテグレーションをセットアップする

[CAUTION]
====
始める前に、<<_prerequisites_for_self_hosted,Kubernetesの前提条件を>>確認してください。
====


KubernetesクラスタからSUSE Observabilityにデータを取得するには、以下の手順に従ってください：

. SUSE Observability helmリポジトリをローカルのhelmクライアントに追加します：
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. SUSE Observability UIで、画面左上をクリックしてメインメニューを開き、`StackPacks` >`Integrations` >`Kubernetes` に進みます。
. Kubernetes StackPackの新しいインスタンスをインストールする：
 ** *Kubernetesクラスタ名の*指定
  *** この名前は、SUSE Observabilityでクラスタを識別するために使用されます。
 ** *インストールを*クリックする。
. StackPackをインストールした後、SUSE Observability UIで提供されるhelmコマンドを使用して、SUSE Observability Agent、Cluster Agent、Checks Agent、およびkube-state-metricsをクラスタに展開します。
 ** Agentがデプロイされると、データの収集が開始され、SUSE Observabilityにプッシュされます。


== 次はどうする？

* xref:/k8s-getting-started.adoc[SUSE Observabilityウォークスルー]
