include::partial$variables.adoc[]
= Test de la politique
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Apprenez à créer et à tester les politiques {project-name} avec {project-name} pour une gestion sécurisée des clusters.
:doc-persona: ["kubewarden-operator", "kubewarden-policy-developer"]
:doc-topic: ["testing-policies", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "persons", "policy author", "cluster operator"].
:sidebar_label: Test de la politique
:current-version: {page-origin-branch}

== Personnages de test de la politique

Cette section traite du test des politiques {project-name}.
Deux personas s'intéressent à l'expérimentation des politiques :

* *Développeur de politique*: vous écrivez une politique {short-project-name} et vous voulez vous assurer que votre code se comporte comme vous le souhaitez.
* *Opérateur de cluster*: vous avez trouvé une politique {short-project-name} et vous voulez tester et régler les paramètres de la politique avant de la déployer.
Vous souhaitez continuer à tester ces paramètres dans vos pipelines CI/CD et dans d'autres tâches administratives.

Les sections suivantes de la documentation montrent comment ces personas peuvent tester les politiques {short-project-name}.
