= Opções de autenticação
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

O SUSE Observability é configurado imediatamente com xref:/setup/security/authentication/file.adoc[autenticação de senha única] com usuário administrador e senha aleatória xref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[configurada durante a instalação]. Isso autentica os usuários com um segredo simples no servidor. No entanto, essa não é uma configuração pronta para produção.

Para aumentar a segurança, o SUSE Observability pode ser configurado para usar exatamente um dos seguintes mecanismos de autenticação (substituindo o usuário administrador padrão):

* xref:/setup/security/authentication/single_password.adoc[Senha única]
* xref:/setup/security/authentication/file.adoc[Baseado em arquivo]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[Open ID Connect (OIDC)]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak (uma versão especializada do OIDC)]

[NOTE]
====
A configuração da autenticação faz parte do gráfico do Helm; qualquer alteração acionará automaticamente uma reinicialização dos pods que exigem isso.
====


== Funções do usuário

Quando um usuário é autenticado, as permissões para esse usuário geralmente são atribuídas com base nas funções que ele tem. A documentação dos mecanismos de autenticação específicos também contém exemplos de como mapear as funções ou os grupos dos sistemas externos para as 4 funções padrão do SUSE Observability:

* *Convidado* - pode ver informações, mas não pode fazer alterações.
* *Solucionador de problemas do Kubernetes* - capaz de ver todas as informações e ver e alterar a configuração de monitores e métricas.
* *Usuário avançado* - capaz de ver e alterar todas as configurações e instalar StackPacks.
* *Administrador* - pode ver e alterar o conteúdo do SUSE Observability. Por exemplo, ver todas as configurações, instalar StackPacks, conceder e revogar permissões de usuário e fazer upload de (novas versões de) StackPacks.

Ao decidir sobre as funções a serem atribuídas aos usuários, é altamente recomendável ter apenas um pequeno grupo de Platform Administrators e Administrators. Por exemplo, somente os engenheiros responsáveis por instalar o SUSE Observability e fazer a configuração inicial. Os usuários administradores podem gerenciar o acesso ao SUSE Observability e decidir quais StackPacks podem ser usados. Você pode delegar a instalação de StackPacks e outros ajustes finos da configuração a um número maior de usuários com a função Power User. Os usuários do Platform Administrator podem limpar o banco de dados, alterar as configurações de retenção de dados, visualizar os registros e executar outras tarefas de gerenciamento da plataforma.

Também é possível adicionar mais funções, consulte a página xref:/setup/security/rbac/rbac_roles.adoc[Funções (RBAC)] e as outras xref:/setup/security/rbac/README.adoc[páginas de documentação do RBAC]
