= LDAP
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== VisĂŁo geral

O SUSE Observability pode usar um servidor LDAP (incluindo o AD) para autenticaĂ§ĂŁo e para obter funĂ§Ăµes/grupos. Ele requer um servidor LDAP em execuĂ§ĂŁo que seja acessĂ­vel ao SUSE Observability.

O diretĂłrio principal do LDAP e todos os subdiretĂłrios serĂŁo verificados quanto a arquivos de usuĂˇrio. As credenciais de associaĂ§ĂŁo na configuraĂ§ĂŁo do SUSE Observability sĂŁo usadas para autenticar o SUSE Observability no servidor LDAP. ApĂłs a autenticaĂ§ĂŁo, o SUSE Observability passa o nome do diretĂłrio LDAP superior para o usuĂˇrio que deseja fazer login no SUSE Observability.

== Configurar o SUSE Observability para LDAP

=== Kubernetes

Para configurar o SUSE Observability para autenticar usando um servidor de autenticaĂ§ĂŁo LDAP no Kubernetes, os detalhes do LDAP e o mapeamento da funĂ§ĂŁo do usuĂˇrio precisam ser adicionados ao arquivo `authentication.yaml`. Por exemplo:

[tabs]
====
authentication.yaml::
+
--

[,yaml]
----
stackstate:
  authentication:
    ldap:
      host: sts-ldap
      port: 10389 # For most LDAP servers 389 for plain, 636 for ssl connections
      #ssl:
      #  sslType: ssl
      #  trustStore: <see below>
      #  trustCertificates <see below>
      bind:
        dn: "cn=admin,ou=employees,dc=acme,dc=com"
        password: "password"
      userQuery:
        parameters:
          - ou: employees
          - dc: acme
          - dc: com
        usernameKey: cn
        emailKey: mail
      groupQuery:
        parameters:
          - ou: groups
          - dc: acme
          - dc: com
        rolesKey: cn
        groupMemberKey: member
        # to return all nested groups, use:
        # groupMemberKey: "member:1.2.840.113556.1.4.1941:"

    # map the groups from LDAP to the
    # standard subjects in SUSE Observability (guest, powerUser and admin)
    roles:
      guest: ["ldap-guest-role-for-stackstate"]
      powerUser: ["ldap-power-user-role-for-stackstate"]
      admin: ["ldap-admin-role-for-stackstate"]
----

--
====

Siga as etapas abaixo para configurar o SUSE Observability para autenticar usando LDAP:

. Em `authentication.yaml` - adicione detalhes do LDAP (veja o exemplo acima):
 ** *host* - O nome do host do servidor LDAP.
 ** *port* - A porta em que o servidor LDAP estĂˇ escutando.
 ** *sslType* - opcional. O tipo de conexĂŁo segura LDAP `ssl` ou `startTls`. Omitir se for usada uma conexĂŁo LDAP simples.
 ** *trustCertificates* - Opcional, arquivo de certificado para SSL. Os formatos PEM, DER e PKCS7 sĂŁo compatĂ­veis.
 ** *trustStore* - Opcional, arquivo de armazenamento de confianĂ§a Java para SSL. Se ambos `trustCertificates` e `trustStore` forem especificados, `trustCertificatesPath` terĂˇ precedĂŞncia.
 ** *bind* - Opcional, usado para autenticar o SUSE Observability no servidor LDAP se o servidor LDAP nĂŁo for compatĂ­vel com pesquisas LDAP anĂ´nimas.
 ** *ParĂ˘metros userQuery e parĂ˘metros groupQuery* - O conjunto de parĂ˘metros internos corresponde ao dn de base do seu LDAP onde os usuĂˇrios e grupos podem ser encontrados. O primeiro Ă© usado para autenticar usuĂˇrios no SUSE Observability, enquanto o segundo Ă© usado para recuperar o grupo desse usuĂˇrio para determinar se ele Ă© um administrador, um usuĂˇrio avanĂ§ado ou um convidado.
 ** *usernameKey* - O nome do atributo que armazena o nome de usuĂˇrio; o valor Ă© comparado com o nome de usuĂˇrio fornecido na tela de login.
 ** *emailKey* - O nome do atributo que Ă© usado como endereĂ§o de e-mail no SUSE Observability.
 ** *rolesKey* - O nome do atributo que armazena o nome do grupo.
 ** *groupMemberKey* - O nome do atributo que indica se um usuĂˇrio Ă© membro de um grupo. O filtro LDAP construĂ­do segue este padrĂŁo: `<groupMemberKey>=<user.dn>,ou=groups,dc=acme,dc=com`. Para retornar todos os grupos aninhados, use `groupMemberKey: "member:1.2.840.113556.1.4.1941:"`.
. Em `authentication.yaml` - mapeie as funĂ§Ăµes de usuĂˇrio do LDAP para os assuntos corretos do SUSE Observability (veja o exemplo acima):
 ** *funĂ§Ăµes* - para obter detalhes, consulte as xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[funĂ§Ăµes padrĂŁo do SUSE Observability]. Mais funĂ§Ăµes do SUSE Observability tambĂ©m podem ser criadas, consulte a xref:/setup/security/rbac/README.adoc[documentaĂ§ĂŁo do RBAC].
. Armazene o arquivo `authentication.yaml` junto com o `values.yaml` das instruĂ§Ăµes de instalaĂ§ĂŁo do SUSE Observability.
. Execute um upgrade do Helm para aplicar as alteraĂ§Ăµes. Se vocĂŞ estiver usando SSL com certificados personalizados, os arquivos de certificado binĂˇrio que devem ser usados ao se conectar ao LDAP devem ser definidos na linha de comando; use o comando em *SSL com certificados personalizados*:

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

*trustCertificates*

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
  --set-file stackstate.authentication.ldap.ssl.trustCertificates=./ldap-certificate.pem \
suse-observability \
suse-observability/suse-observability
----

*trustStore*

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
  --set-file stackstate.authentication.ldap.ssl.trustStore=./ldap-cacerts \
suse-observability \
suse-observability/suse-observability
----

[NOTE]
====
*ObservaĂ§ĂŁo:*

* A primeira execuĂ§ĂŁo do comando helm upgrade resultarĂˇ na reinicializaĂ§ĂŁo dos pods, o que pode causar uma breve interrupĂ§ĂŁo da disponibilidade.
* Inclua `authentication.yaml` em cada execuĂ§ĂŁo de `helm upgrade`.
* A configuraĂ§ĂŁo de autenticaĂ§ĂŁo Ă© armazenada como um segredo do Kubernetes.
====


=== Usando um segredo externo

Quando a senha do ldap tiver que vir de um segredo externo, siga xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[estas etapas], mas preencha os dados a seguir:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  ldap_password: <base64 of ldap password>
----

== Veja tambĂ©m

* xref:/setup/security/authentication/authentication_options.adoc[OpĂ§Ăµes de autenticaĂ§ĂŁo]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[PermissĂµes para funĂ§Ăµes predefinidas do SUSE Observability]
* xref:/setup/security/rbac/rbac_roles.adoc[Criar funĂ§Ăµes RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Segredos externos]
