= Open ID Connect (OIDC)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== VisĂŁo geral

O SUSE Observability pode se autenticar usando um provedor de autenticaĂ§ĂŁo OIDC. Para habilitar isso, vocĂȘ precisarĂĄ configurar o SUSE Observability e o provedor OIDC para que possam se comunicar entre si. As seĂ§Ă”es a seguir descrevem as respectivas configuraĂ§Ă”es.

== Configurar o provedor OIDC

Antes de configurar o SUSE Observability para autenticar usando o OIDC, vocĂȘ precisa criar um cliente para o SUSE Observability em seu provedor OIDC.

=== Fazendeiro

[NOTE]
Isso sĂł funciona com o Rancher 2.12 ou posterior.  VocĂȘ precisa https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/users/authn-and-authz/configure-oidc-provider.html[configurar o Rancher como um provedor OIDC].

Crie um recurso OIDCClient no cluster local do Rancher:
[,yaml]
----
apiVersion: management.cattle.io/v3
kind: OIDCClient
metadata:
  name: oidc-observability
spec:
  tokenExpirationSeconds: 600
  refreshTokenExpirationSeconds: 3600
  redirectURIs:
    - "https://<observability-base-url>/loginCallback?client_name=StsOidcClient"
----

O Rancher disponibilizarĂĄ o ID e o segredo do cliente em seu campo de status:
[,yaml]
----
apiVersion: management.cattle.io/v3
kind: OIDCClient
metadata:
  name: oidc-observability
spec:
  tokenExpirationSeconds: 600
  refreshTokenExpirationSeconds: 3600
  redirectURIs:
    - "https://<observability-base-url>/loginCallback?client_name=StsOidcClient"
status:
  clientID: <oidc-client-id>
  clientSecrets:
    client-secret-1:
      createdAt: "xxx"
      lastFiveCharacters: xxx
----

E vocĂȘ pode obter o valor secreto com
[,bash]
----
kubectl get secret <oidc-client-id> -n cattle-oidc-client-secrets -o jsonpath="{.data.client-secret-1}" | base64 -d
----


=== Outros provedores de OIDC

Use as seguintes configuraĂ§Ă”es para o cliente (se necessĂĄrio pelo provedor do OIDC):

* Use o fluxo de autorizaĂ§ĂŁo do OIDC, que tambĂ©m costuma ser chamado de fluxo de cĂłdigo de autorizaĂ§ĂŁo. O SUSE Observability nĂŁo oferece suporte Ă  concessĂŁo implĂ­cita e aos fluxos hĂ­bridos, portanto, nĂŁo hĂĄ necessidade de ativar o suporte a eles.
* Defina o *URI de redirecionamento* para o URL base do SUSE Observability com o sufixo `/loginCallback?client_name=StsOidcClient`. Por exemplo, `https://stackstate.acme.com/loginCallback?client_name=StsOidcClient`. Para alguns provedores de OIDC, como o Google e o Azure Entra ID, o URI de redirecionamento deve corresponder exatamente, incluindo todos os parĂąmetros de consulta. Nesse caso, vocĂȘ deve configurar o URI da seguinte forma `https://stackstate.acme.com/loginCallback?client_name=StsOidcClient`.
* Conceda ao SUSE Observability acesso a pelo menos os escopos `openid` e `email` ou o equivalente a eles para seu provedor OIDC. Dependendo do provedor, podem ser necessĂĄrios mais escopos; se houver um `profile` separado, inclua-o tambĂ©m.
* O SUSE Observability precisa de acesso off-line ao OIDC. Para alguns provedores de identidade, isso requer um escopo extra, geralmente chamado `offline_access`.

O resultado dessa configuraĂ§ĂŁo deve produzir um *clientId* e um *segredo*. Copie-os e mantenha-os por perto para configurar o SUSE Observability. Anote tambĂ©m o *discoveryUri* do provedor. Normalmente, isso estĂĄ na mesma tela ou pode ser encontrado na documentaĂ§ĂŁo.

== Configurar o SUSE Observability para OIDC

=== Fazendeiro

[NOTE]
Isso sĂł funciona com o Rancher 2.12 ou posterior.  VocĂȘ precisa https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/users/authn-and-authz/configure-oidc-provider.html[configurar o Rancher como um provedor OIDC].

Para configurar o Rancher como o provedor de OIDC para o SUSE Observability, vocĂȘ precisa adicionar os detalhes do OIDC aos valores de autenticaĂ§ĂŁo:
[,yaml]
----
stackstate:
  authentication:
    rancher:
      clientId: "<oidc-client-id>"
      secret: "<oidc-secret>"
      baseUrl: "<rancher-url>"
----
VocĂȘ pode substituir e estender a configuraĂ§ĂŁo do OIDC para o Rancher com os seguintes campos:

* **discoveryUri** - URI que vocĂȘ pode usar para descobrir o provedor OIDC. Normalmente, tambĂ©m documentado ou retornado ao criar o cliente no provedor OIDC.
* **redirectUri** - Opcional (nĂŁo estĂĄ no exemplo): O URI em que o ponto de extremidade de retorno de chamada de login do SUSE Observability pode ser acessado. Preenchido por padrĂŁo usando o endereĂ§o `stackstate.baseUrl`, mas pode ser substituĂ­do. Esse deve ser um URL totalmente qualificado que aponte para o caminho `/loginCallback`.
* **customParameters** - Mapa opcional de pares de chave/valor que vocĂȘ envia ao provedor OIDC como parĂąmetros de solicitaĂ§ĂŁo personalizados. Alguns provedores de OIDC exigem parĂąmetros de solicitaĂ§ĂŁo adicionais que nĂŁo sĂŁo enviados por padrĂŁo.

Se vocĂȘ precisar desativar a verificaĂ§ĂŁo de TLS devido a uma configuraĂ§ĂŁo que nĂŁo usa certificados SSL verificĂĄveis, poderĂĄ desativar as verificaĂ§Ă”es de SSL com a configuraĂ§ĂŁo do aplicativo (nĂŁo use em produĂ§ĂŁo):

Para configuraĂ§ĂŁo **nĂŁo HA**:
[,yaml]
----
stackstate:
  components:
    server:
      extraEnv:
        open:
          CONFIG_FORCE_stackstate_misc_sslCertificateChecking: false
----
Para a configuraĂ§ĂŁo de **HA (alta disponibilidade)**:
[,yaml]
----
stackstate:
  components:
    api:
      extraEnv:
        open:
          CONFIG_FORCE_stackstate_misc_sslCertificateChecking: false
----

Em implementaĂ§Ă”es de HA, o componente api lida com a configuraĂ§ĂŁo de forma diferente. Use o seguinte:=== Kubernetes

Para configurar o SUSE Observability para usar um provedor de autenticaĂ§ĂŁo OIDC no Kubernetes, Ă© necessĂĄrio adicionar os detalhes do OIDC e o mapeamento da funĂ§ĂŁo do usuĂĄrio ao arquivo `authentication.yaml`. Por exemplo:

[,yaml]
----
stackstate:
  authentication:
    oidc:
      clientId: "<client-id-from-oidc-provider>"
      secret: "<secret-from-oidc-provider>"
      discoveryUri: "https://oidc.acme.com/.well-known/openid-configuration"
      jwsAlgorithm: RS256
      scope: ["openid", "email"]
      jwtClaims:
        usernameField: email
        displayNameField: name
        groupsField: groups
      customParameters:
        access_type: offline

    # map the groups from OIDC provider
    # to the 4 standard roles in SUSE Observability (guest, powerUser, k8sTroubleshooter and admin)
    roles:
      guest: ["guest-group-in-oidc-provider"]
      powerUser: ["powerUser-group-in-oidc-provider"]
      admin: ["admin-group-in-oidc-provider"]
      k8sTroubleshooter: ["troubleshooter-group-in-oidc-provider"]
----

Siga as etapas abaixo para configurar o SUSE Observability para autenticar usando o OIDC:

. Em `authentication.yaml` - adicione detalhes do provedor de autenticaĂ§ĂŁo OIDC (veja o exemplo acima):
 ** *clientId* - O ID do xref:/setup/security/authentication/oidc.adoc#_configure_the_oidc_provider[cliente OIDC que vocĂȘ criou para o SUSE Observability].
 ** *secret* - O segredo do xref:/setup/security/authentication/oidc.adoc#_configure_the_oidc_provider[cliente OIDC que vocĂȘ criou para o SUSE Observability]
 ** *discoveryUri* - URI que pode ser usado para descobrir o provedor OIDC. Normalmente tambĂ©m documentado ou retornado ao criar o cliente no provedor OIDC.
 ** *jwsAlgorithm* - O padrĂŁo para o OIDC Ă© `RS256`. Se o seu provedor de OIDC usar um diferente, ele poderĂĄ ser definido aqui.
 ** *escopo* - Deve corresponder ou ser um subconjunto do escopo fornecido na configuraĂ§ĂŁo do provedor do OIDC. O SUSE Observability usa isso para solicitar acesso a essas partes de um perfil de usuĂĄrio no provedor OIDC.
 ** *redirectUri* - Opcional (nĂŁo estĂĄ no exemplo): O URI em que o ponto de extremidade de retorno de chamada de login do SUSE Observability pode ser acessado. Preenchido por padrĂŁo usando o endereĂ§o `stackstate.baseUrl`, mas pode ser substituĂ­do. Esse deve ser um URL totalmente qualificado que aponte para o caminho `/loginCallback`.
 ** *customParameters* - Mapa opcional de pares de chave/valor que sĂŁo enviados ao provedor OIDC como parĂąmetros de solicitaĂ§ĂŁo personalizados. Alguns provedores de OIDC exigem parĂąmetros de solicitaĂ§ĂŁo adicionais que nĂŁo sĂŁo enviados por padrĂŁo.
 ** *jwtClaims* -
  *** *usernameField* - O campo no perfil de usuĂĄrio do OIDC que deve ser usado como nome de usuĂĄrio. Por padrĂŁo, esse serĂĄ o `preferred_username`, no entanto, muitos provedores omitem esse campo. Uma boa alternativa Ă© o site `email`.
  *** *displayNameField* - O campo no perfil de usuĂĄrio do OIDC que deve ser usado como o displayName. Por padrĂŁo, esse serĂĄ o `name`.
  *** *groupsField* - O campo do qual o SUSE Observability lerĂĄ a funĂ§ĂŁo/grupo de um usuĂĄrio.
. Em `authentication.yaml` - mapeie as funĂ§Ă”es de usuĂĄrio do OIDC para os assuntos corretos do SUSE Observability usando as configuraĂ§Ă”es `roles.guest`, `roles.powerUser`, `roles.admin` ou `roles.platformAdmin` (veja o exemplo acima). Para obter detalhes, consulte as xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[funĂ§Ă”es padrĂŁo do SUSE Observability]. Mais funĂ§Ă”es do SUSE Observability tambĂ©m podem ser criadas, consulte a xref:/setup/security/rbac/README.adoc[documentaĂ§ĂŁo do RBAC].
. Armazene o arquivo `authentication.yaml` junto com o arquivo `values.yaml` das instruĂ§Ă”es de instalaĂ§ĂŁo do SUSE Observability.
. Execute um upgrade do Helm para aplicar as alteraĂ§Ă”es:
+
[,text]
----
 helm upgrade \
   --install \
   --namespace suse-observability \
   --values values.yaml \
   --values authentication.yaml \
 suse-observability \
 suse-observability/suse-observability
----

[NOTE]
====
*ObservaĂ§ĂŁo:*

* A primeira execuĂ§ĂŁo do comando helm upgrade resultarĂĄ na reinicializaĂ§ĂŁo dos pods, o que pode causar uma breve interrupĂ§ĂŁo da disponibilidade.
* Inclua `authentication.yaml` em cada execuĂ§ĂŁo de `helm upgrade`.
* A configuraĂ§ĂŁo de autenticaĂ§ĂŁo Ă© armazenada como um segredo do Kubernetes.
====


== Guias de configuraĂ§ĂŁo

* xref:/setup/security/authentication/oidc/microsoft-entra-id.adoc[Microsoft Entra ID]

== Usando um segredo externo

Quando os segredos do oidc forem provenientes de um segredo externo, siga xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[estas etapas], mas preencha os dados a seguir:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  oidc_client_id: <base64 of client id>
  oidc_secret: <base64 of secret>
----

== Veja tambĂ©m

* xref:/setup/security/authentication/troubleshooting.adoc[SoluĂ§ĂŁo de problemas de autenticaĂ§ĂŁo e autorizaĂ§ĂŁo]
* xref:/setup/security/authentication/authentication_options.adoc[OpĂ§Ă”es de autenticaĂ§ĂŁo]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[PermissĂ”es para funĂ§Ă”es predefinidas do SUSE Observability]
* xref:/setup/security/rbac/rbac_roles.adoc[Criar funĂ§Ă”es RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Segredos externos]
