= Sauvegarde et restauration
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

La façon dont K3s est sauvegardé et restauré dépend du type de datastore utilisé.

[CAUTION]
====
Outre la sauvegarde du datastore lui-même, vous devez également sauvegarder le fichier de jetons du serveur à l'adresse `/var/lib/rancher/k3s/server/token`.
Vous devez restaurer ce fichier, ou passer sa valeur dans l'option `--token`, lors d'une restauration à partir d'une sauvegarde.
Si vous n'utilisez pas la même valeur de jeton lors de la restauration, l'instantané sera inutilisable, car le jeton est utilisé pour crypter les données confidentielles dans le magasin de données lui-même.
====


== Sauvegarde et restauration avec SQLite

Aucune commande spéciale n'est nécessaire pour sauvegarder ou restaurer le datastore SQLite.

* Pour sauvegarder le datastore SQLite, prenez une copie de `/var/lib/rancher/k3s/server/db/`.
* Pour restaurer le magasin de données SQLite, restaurez le contenu de `/var/lib/rancher/k3s/server/db` (et le jeton, comme indiqué ci-dessus).

== Sauvegarde et restauration avec Datastore externe

Lorsqu'un datastore externe est utilisé, les opérations de sauvegarde et de restauration sont gérées en dehors de K3s. L'administrateur de la base de données devra sauvegarder la base de données externe ou la restaurer à partir d'un instantané ou d'un vidage.

Nous recommandons de configurer la base de données pour qu'elle prenne des clichés récurrents.

Pour plus de détails sur la prise d'instantanés de la base de données et la restauration de votre base de données à partir de ces instantanés, reportez-vous à la documentation officielle de la base de données :

* https://dev.mysql.com/doc/refman/8.0/en/replication-snapshot-method.html[Documentation officielle de MySQL]
* https://www.postgresql.org/docs/8.3/backup-dump.html[Documentation officielle de PostgreSQL]
* https://etcd.io/docs/latest/op-guide/recovery/[Documentation officielle etcd]

== Sauvegarde et restauration avec le datastore etcd intégré

Consultez la xref:cli/etcd-snapshot.adoc[documentation de la commande`k3s etcd-snapshot` ] pour obtenir des informations sur l'exécution d'opérations de sauvegarde et de restauration sur le datastore etcd intégré.
