= Stockage de données en grappe
:page-languages: [en, ja, ko, zh]
:revdate: 2025-06-16
:page-revdate: {revdate}

La possibilité d'exécuter Kubernetes en utilisant un datastore autre qu'etcd distingue K3s des autres distributions Kubernetes. Cette fonctionnalité offre de la flexibilité aux opérateurs Kubernetes. Les options disponibles pour le datastore vous permettent de sélectionner le datastore qui correspond le mieux à votre cas d'utilisation. Par exemple :

* Si votre équipe n'a pas d'expertise dans l'exploitation d'etcd, vous pouvez choisir une base de données SQL de qualité professionnelle comme MySQL ou PostgreSQL.
* Si vous avez besoin d'un simple cluster de courte durée dans votre environnement CI/CD, vous pouvez utiliser la base de données SQLite intégrée.
* Si vous souhaitez déployer Kubernetes en périphérie et que vous avez besoin d'une solution hautement disponible, mais que vous ne pouvez pas vous permettre les frais généraux opérationnels liés à la gestion d'une base de données en périphérie, vous pouvez utiliser le datastore HA intégré de K3s, construit au-dessus d'etcd intégré.

K3s prend en charge les options de stockage de données suivantes :

* *Embarqué https://www.sqlite.org/index.html[SQLite]* +
SQLite ne peut pas être utilisé sur des clusters avec plusieurs serveurs. +
SQLite est le magasin de données par défaut et sera utilisé si aucune autre configuration de magasin de données n'est présente et si aucun fichier de base de données etcd intégré n'est présent sur le disque.
* *etcd embarqué* +
Voir la documentation xref:datastore/ha-embedded.adoc[High Availability Embedded etc] d pour plus d'informations sur l'utilisation d'embedded etcd avec plusieurs serveurs.
Embedded etcd sera automatiquement sélectionné si K3s est configuré pour initialiser un nouveau cluster etcd, rejoindre un cluster etcd existant, ou si des fichiers de base de données etcd sont présents sur le disque lors du démarrage.
* *Base de données externe* +
Voir la documentation xref:datastore/ha.adoc[High Availability External DB] pour plus d'informations sur l'utilisation de datastores externes avec plusieurs serveurs. +
Les magasins de données externes suivants sont pris en charge :
 ** https://etcd.io/[etcd] (certifié contre la version 3.5.21)
 ** https://www.mysql.com/[MySQL] (certifié pour les versions 5.7 et 8.0)
 ** https://mariadb.org/[MariaDB] (certifié pour les versions 10.11 et 11.4)
 ** https://www.postgresql.org/[PostgreSQL] (certifié pour les versions 15.12, 16.7 et 17.3)

[CAUTION]
.Soutien à la déclaration préparée
====
K3s nécessite le soutien de la DB pour les déclarations préparées. Cela signifie que les pools de connexion tels que https://www.pgbouncer.org/faq.html#how-to-use-prepared-statements-with-transaction-pooling[] PgBouncer peuvent nécessiter une configuration supplémentaire pour fonctionner avec les K3.
====

[WARNING]
.Installations multimaster
====
Les bases de données multi-maîtres dont les valeurs `auto_increment_increment` ou `auto_increment_offset` sont supérieures à 1 ne sont pas prises en charge. Kine s'attend à ce que la révision commence à 0 à 0 et avance toujours d'exactement 1 lorsqu'une clé est insérée avec succès. Cela concerne des produits tels que Galera pour MySQL/MariaDB. 
====

[#_external_datastore_configuration_parameters]
== Paramètres de configuration du magasin de données externe

Si vous souhaitez utiliser un magasin de données externe tel que PostgreSQL, MySQL ou etcd, vous devez définir le paramètre `datastore-endpoint` afin que K3s sache comment s'y connecter. Vous pouvez également spécifier des paramètres pour configurer l'authentification et le cryptage de la connexion. Le tableau ci-dessous résume ces paramètres, qui peuvent être transmis en tant qu'indicateurs CLI ou variables d'environnement.

|===
| Drapeau CLI | Variable d'environnement | Description

| `--datastore-endpoint`
| `K3S_DATASTORE_ENDPOINT`
| Spécifiez une chaîne de connexion PostgreSQL, MySQL ou etcd. Il s'agit d'une chaîne de caractères utilisée pour décrire la connexion au magasin de données. La structure de cette chaîne est spécifique à chaque backend et est détaillée ci-dessous.

| `--datastore-cafile`
| `K3S_DATASTORE_CAFILE`
| Fichier de l'autorité de certification (CA) TLS utilisé pour sécuriser la communication avec le datastore. Si votre magasin de données envoie des requêtes via TLS en utilisant un certificat signé par une autorité de certification personnalisée, vous pouvez spécifier cette autorité de certification à l'aide de ce paramètre afin que le client K3s puisse vérifier correctement le certificat.

| `--datastore-certfile`
| `K3S_DATASTORE_CERTFILE`
| Fichier de certificat TLS utilisé pour l'authentification basée sur le certificat du client à votre magasin de données. Pour utiliser cette fonctionnalité, votre magasin de données doit être configuré pour prendre en charge l'authentification basée sur le certificat du client. Si vous spécifiez ce paramètre, vous devez également spécifier le paramètre `datastore-keyfile`.

| `--datastore-keyfile`
| `K3S_DATASTORE_KEYFILE`
| Fichier de clé TLS utilisé pour l'authentification basée sur le certificat du client à votre magasin de données. Voir le paramètre précédent `datastore-certfile` pour plus de détails.
|===

Nous vous recommandons de définir ces paramètres comme des variables d'environnement plutôt que comme des arguments de ligne de commande, afin que les informations d'identification de votre base de données ou d'autres informations sensibles ne soient pas exposées dans le cadre des informations sur le processus.

[#_datastore_endpoint_format_and_functionality]
== Format et fonctionnalité des points de terminaison du magasin de données

Comme indiqué, le format de la valeur transmise au paramètre `datastore-endpoint` dépend du backend du magasin de données. Les paragraphes suivants décrivent en détail ce format et cette fonctionnalité pour chaque magasin de données externe pris en charge.

[tabs,sync-group-id=ext-db]
======
PostgreSQL::
+
--
Dans sa forme la plus courante, le paramètre datastore-endpoint de PostgreSQL a le format suivant :

`postgres://username:password@hostname:port/database-name`

Des paramètres de configuration plus avancés sont disponibles. Pour plus d'informations, voir https://godoc.org/github.com/lib/pq.

Si vous indiquez le nom d'une base de données et qu'elle n'existe pas, le serveur tentera de la créer.

Si vous ne fournissez que `postgres://` comme point d'arrivée, K3s tentera de faire ce qui suit :

* Se connecter à localhost en utilisant `postgres` comme nom d'utilisateur et mot de passe
* Créer une base de données nommée `kubernetes`
--

MySQL / MariaDB::
+
--
Dans sa forme la plus courante, le paramètre `datastore-endpoint` pour MySQL et MariaDB a le format suivant :

`mysql://username:password@tcp(hostname:3306)/database-name`

Des paramètres de configuration plus avancés sont disponibles. Pour plus d'informations, voir https://github.com/go-sql-driver/mysql#dsn-data-source-name

Notez qu'en raison d'un https://github.com/k3s-io/k3s/issues/1093[problème connu sur] dans les K3, vous ne pouvez pas régler le paramètre `tls`. La communication TLS est prise en charge, mais vous ne pouvez pas, par exemple, définir ce paramètre sur "skip-verify" pour que K3s ignore la vérification du certificat.

Si vous indiquez le nom d'une base de données et qu'elle n'existe pas, le serveur tentera de la créer.

Si vous ne fournissez que `mysql://` comme point de terminaison, K3s tentera de faire ce qui suit :

* Se connecter au socket MySQL à l'adresse `/var/run/mysqld/mysqld.sock` en utilisant l'utilisateur `root` et sans mot de passe.
* Créer une base de données avec le nom `kubernetes`
--

etcd::
+
--
Dans sa forme la plus courante, le paramètre `datastore-endpoint` pour etcd a le format suivant :

`\https://etcd-host-1:2379,https://etcd-host-2:2379,https://etcd-host-3:2379\`

Ce qui précède suppose un cluster etcd typique à trois nœuds. Le paramètre peut accepter une ou plusieurs URL etcd séparées par des virgules.
--
======
