include::partial$variables.adoc[]

= Instalação do entreferro
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure um registro privado com imagens e políticas do {project-name} para instalar o {project-name} em um ambiente com air-gap.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["manual do operador", "air gap", "instalação"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "air gap installation"]
:current-version: {page-origin-branch}

Para uma instalação air-gapped do {project-name}, você precisa de um registro privado da Open Container Initiative (OCI) acessível pelo seu cluster do Kubernetes.
{short-project-name} As políticas são módulos do WebAssembly, portanto, você pode armazená-las em um registro compatível com OCI como artefatos OCI. Você precisa adicionar as imagens e políticas do{short-project-name}a esse registro da OCI. Você pode consultar uma lista de artefatos do site {short-project-name} na páginaxref:/reference/artifacts.adoc[de referência de artefatos]. As seções a seguir descrevem o processo.

[NOTE]
====
Recomendamos o uso do link:https://docs.hauler.dev/docs/intro[site].
Consulte nossa xref:/howtos/airgap/03-hauler.adoc[página de documentação do Hauler].

Como alternativa, você pode usar o processo manual listado abaixo.
====


== Salvar gráficos do Helm localmente

Você precisa fazer o download dos seguintes diagramas de leme para sua estação de trabalho:

[,console]
----
helm pull kubewarden/kubewarden-crds
helm pull kubewarden/kubewarden-controller
helm pull kubewarden/kubewarden-defaults
helm pull kubewarden/sbomscanner
----

[NOTE]
====
Opcionalmente, você pode verificar as assinaturas dosxref:/tutorials/verifying-kubewarden.adoc#_helm_charts[helm charts] e dasxref:/tutorials/verifying-kubewarden.adoc#_container_images[imagens de contêineres].
====

== Salvar imagens de contêineres localmente

. Cada um dos nossos gráficos do Helm contém um `+imagelist.txt+` com as imagens de contêineres consumidas por ele e, quando aplicável, um `+policylist.txt+` com os módulos OCI Wasm das políticas que ele também consome.
+
Para obtê-los, você pode fazer o seguinte:
+
[,console]
----
helm pull --untar \
  kubewarden/kubewarden-crds \
  kubewarden/kubewarden-controller \
  kubewarden/kubewarden-defaults \
  kubewarden/sbomscanner
----
+
E, em seguida, concatene-os em um único arquivo:
+
[,console]
----
cat */imagelist.txt > kubewarden-images.txt
----

. Faça o download de `+kubewarden-save-images.sh+` e `+kubewarden-load-images.sh+` do https://github.com/kubewarden/utils[repositório de utilitários].
. Salve as imagens do contêiner {short-project-name} em um arquivo `+.tar.gz+`:
+
[,shell]
----
 ./kubewarden-save-images.sh \
   --image-list ./kubewarden-images.txt \
   --images kubewarden-images.tar.gz
----
+
O Docker começa a extrair as imagens usadas para uma instalação de air gap. Esse processo pode levar alguns minutos. Quando concluído, seu diretório atual, onde você executou o comando, terá um tarball, `+kubewarden-images.tar.gz+`.

== Salvar políticas localmente

. Adicione todas as políticas que deseja usar a um arquivo `+policies.txt+`:
+
[,console]
----
cat */policylist.txt > policies.txt
----
+
Um arquivo com uma lista de políticas padrão está na {short-project-name} defaultshttps://github.com/kubewarden/helm-charts/releases/[página de versão].

. Faça o download de `+kubewarden-save-policies.sh+` e `+kubewarden-load-policies.sh+` do https://github.com/kubewarden/kubewarden-controller/blob/main/scripts[repositório]

. Salve as políticas em um arquivo `+.tar.gz+`:
+
[,shell]
----
./kubewarden-save-policies.sh --policies-list policies.txt
----
+
Use `+kwctl+` para fazer o download das políticas. O arquivo `+kubewarden-policies.tar.gz+`contém as políticas.

== Gráficos do leme

Você precisa fazer o download dos seguintes diagramas de leme para sua estação de trabalho:

[,shell]
----
helm pull kubewarden/kubewarden-crds
helm pull kubewarden/kubewarden-controller
helm pull kubewarden/kubewarden-defaults
----

== Preencher o registro privado

Mova esses arquivos para o ambiente do air gap:

* Gráficos do leme no formato `+tgz+` (por exemplo, `+kubewarden-crds-1.23.0.tgz+`)
* `+kubewarden-policies.tar.gz+`,
* `+kubewarden-images.tar.gz+`,
* `+kubewarden-load-images.sh+`,
* `+kubewarden-load-policies.sh+` e
* `+policies.txt+`

. Carregue as imagens do {short-project-name} no registro privado. Você precisa autenticar o cliente Docker no registro local.
+
[,shell]
----
 ./kubewarden-load-images.sh \
   --image-list ./kubewarden-images.txt \
   --images kubewarden-images.tar.gz \
   --registry <REGISTRY.YOURDOMAIN.COM:PORT>
----

. Carregue as políticas do {short-project-name} no registro privado. Você deve autenticar `+kwctl+` no registro local (`+kwctl+` usa o mesmo mecanismo de autenticação que `+docker+`, um arquivo `+~/.docker/config.json+` )
+
[,shell]
----
 ./kubewarden-load-policies.sh \
   --policies-list policies.txt \
   --policies kubewarden-policies.tar.gz \
   --registry <REGISTRY.YOURDOMAIN.COM:PORT> \
   --sources-path sources.yml
----

[CAUTION]
====

O comando `+kwctl+` precisa do arquivo `+sources.yaml+` para se conectar aos registros dessas categorias:

* A autenticação é necessária
* O certificado autoassinado está sendo usado
* Nenhuma terminação de TLS é feita

Consulte a xref:howtos/custom-certificate-authorities.adoc[seção sobre autoridades de certificação personalizadas] na documentação para saber mais sobre como configurar o arquivo `+sources.yaml+`.

====


== Instalar {short-project-name}

Agora que o seu registro privado tem tudo o que é necessário, você pode instalar o{short-project-name}. A única diferença em relação a uma instalação padrão do {short-project-name} é que você precisa alterar o registro nas imagens e políticas do contêiner para que seja o registro privado.

Instale a pilha {short-project-name}:

[,shell]
----
helm install --wait -n kubewarden \
  kubewarden-crds kubewarden-crds.tgz
----

[,shell]
----
helm install --wait -n kubewarden \
  kubewarden-controller kubewarden-controller.tgz \
  --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>
----

[CAUTION]
====

Para usar o subgráfico do Policy Reporter disponível no gráfico `+kubewarden-controller+`, é necessário definir outros valores específicos para o subgráfico em um ambiente com air-gap. Um exemplo está abaixo:

[,shell]
----
helm install --wait -n kubewarden kubewarden-controller kubewarden-controller.tgz \
    --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set auditScanner.policyReporter=true \
    --set policy-reporter.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.ui.image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set policy-reporter.image.repository=kyverno/policy-reporter \
    --set policy-reporter.ui.image.repository=kyverno/policy-reporter-ui
----

É necessário definir `+auditScanner.policyReporter+` para ativar o subgráfico e mais 4 valores para configurar o registro e o repositório onde são armazenadas as imagens do Policy Reporter. Para obter mais informações sobre os valores do subgráfico do relatório de política, consultehttps://github.com/kyverno/policy-reporter/tree/policy-reporter-2.19.4/charts/policy-reporter[Policy Reporter documentation].

====


[,shell]
----
helm install --wait -n kubewarden \
  kubewarden-defaults kubewarden-defaults.tgz \
  --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>
----

[CAUTION]
====

Para fazer download das políticas recomendadas instaladas pelo `+kubewarden-defaults+`Helm Chart de um registro diferente de `+global.cattle.systemDefaultRegistry+`, use a configuração `+recommendedPolicies.defaultPoliciesRegistry+`.
Essa configuração permite que os usuários especifiquem um registro dedicado a extrair os artefatos OCI das políticas. É particularmente útil quando o repositório de imagens de contêineres não é compatível com artefatos OCI.

Para instalar e aguardar a conclusão da instalação, use o seguinte comando:

[,console]
----
helm install --wait -n kubewarden \
  kubewarden-defaults kubewarden-defaults.tgz \
  --set global.cattle.systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \
  --set recommendedPolicies.defaultPoliciesRegistry=<REGISTRY.YOURDOMAIN.COM:PORT>
----

Se a configuração `+recommendedPolicies.defaultPoliciesRegistry+` não for definida, o `+global.cattle.systemDefaultRegistry+` será usado como registro padrão.

====


Por fim, você precisa configurar o Policy Server para obter políticas do seu registro privado. Consulte a seçãoxref:howtos/policy-servers/02-private-registry.adoc[de uso do registro privado]da documentação.

Agora você pode criar políticas {short-project-name} em seu cluster. As políticas devem estar disponíveis em seu registro privado.

[,console]
----
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://<REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policies/pod-privileged:v0.2.2
  rules:
  - apiGroups: [""]
    apiVersions: [“v1”]
    resources: [“pods”]
    operations:
    - CREATE
  mutating: false
EOF
----

[CAUTION]
====

`+PolicyServer+` Os recursos devem usar a imagem disponível em seu registro privado.
Por exemplo:

[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: reserved-instance-for-tenant-a
spec:
  image: <REGISTRY.YOURDOMAIN.COM:PORT>/kubewarden/policy-server:v1.3.0
  replicas: 2
  serviceAccountName: sa
----

====

