= Cluster hybride ou multicloud distribué
:page-languages: [en, ja, ko, zh]
:revdate: 2025-05-26
:page-revdate: {revdate}

Un cluster K3s peut toujours être déployé sur des nœuds qui ne partagent pas un réseau privé commun et ne sont pas directement connectés (par exemple, des nœuds dans différents nuages publics). Il existe deux options pour y parvenir : la solution multicloud intégrée de k3s et l'intégration avec le fournisseur de VPN `+tailscale+`.

[CAUTION]
====
La latence entre les nœuds augmentera à mesure que la connectivité externe nécessitera davantage de sauts. Cela réduit les performances du réseau et peut également avoir un impact sur la santé de la grappe si la latence est trop élevée.
====


[CAUTION]
====
Embedded etcd n'est pas pris en charge dans ce type de déploiement. Si vous utilisez etcd intégré, tous les nœuds de serveur doivent être joignables les uns aux autres via leurs adresses IP privées. Les agents peuvent être répartis sur plusieurs réseaux, mais tous les serveurs doivent se trouver au même endroit.
====


== Solution embarquée k3s multicloud

K3s utilise Wireguard pour établir un maillage VPN pour le trafic du cluster. Chaque nœud doit disposer d'une adresse IP unique par laquelle il est possible de le joindre (généralement une adresse IP publique). Le trafic du superviseur K3s utilisera un tunnel websocket, et le trafic du cluster (CNI) utilisera un tunnel wireguard.

Pour activer ce type de déploiement, vous devez ajouter les paramètres suivants sur les serveurs :

[,bash]
----
--node-external-ip=<SERVER_EXTERNAL_IP> --flannel-backend=wireguard-native --flannel-external-ip
----

et sur les agents :

[,bash]
----
--node-external-ip=<AGENT_EXTERNAL_IP>
----

où `+SERVER_EXTERNAL_IP+` est l'IP par laquelle nous pouvons atteindre le nœud du serveur et `+AGENT_EXTERNAL_IP+` est l'IP par laquelle nous pouvons atteindre le nœud de l'agent. Notez que le paramètre de configuration `+K3S_URL+` de l'agent doit utiliser le site `+SERVER_EXTERNAL_IP+` pour pouvoir s'y connecter. N'oubliez pas de vérifier les xref:installation/requirements.adoc#_networking[conditions de mise en réseau] et d'autoriser l'accès aux ports répertoriés sur les adresses internes et externes.

Les adresses `+SERVER_EXTERNAL_IP+` et `+AGENT_EXTERNAL_IP+` doivent être connectées entre elles et sont normalement des adresses IP publiques.

[IMPORTANT]
.IP dynamiques
====
Si des IP dynamiques sont attribuées aux nœuds et que l'IP change (par exemple dans AWS), vous devez modifier le paramètre `+--node-external-ip+` pour refléter la nouvelle IP. Si vous utilisez K3s en tant que service, vous devez modifier `+/etc/systemd/system/k3s.service+` puis l'exécuter :

[,bash]
----
systemctl daemon-reload
systemctl restart k3s
----
====

[#_integration_with_the_tailscale_vpn_provider_experimental]
== Intégration avec le fournisseur de VPN Tailscale (expérimental)

Disponible dans les versions v1.27.3, v1.26.6, v1.25.11 et plus récentes.

K3s peut s'intégrer à https://tailscale.com/[] Tailscale de sorte que les nœuds utilisent le service VPN de Tailscale pour construire un maillage entre les nœuds.

Il y a quatre étapes à réaliser avec Tailscale avant de déployer K3s :

. Connectez-vous à votre compte Tailscale
. Dans `+Settings > Keys+`, générez une clé d'authentification ($AUTH-KEY), qui peut être réutilisée pour tous les nœuds de votre cluster.
. Décidez du podCIDR que le cluster utilisera (par défaut `+10.42.0.0/16+`). Ajoutez le CIDR (ou les CIDR pour la double pile) dans les contrôles d'accès avec la strophe :
+
[,yaml]
----
"autoApprovers": {
     "routes": {
         "10.42.0.0/16":        ["your_account@xyz.com"],
         "2001:cafe:42::/56": ["your_account@xyz.com"],
     },
 },
----

. Installez Tailscale dans vos nœuds :
+
[,bash]
----
curl -fsSL https://tailscale.com/install.sh | sh
----

Pour déployer des K3 avec l'intégration Tailscale activée, vous devez ajouter le paramètre suivant sur chacun de vos nœuds :

[,bash]
----
--vpn-auth="name=tailscale,joinKey=$AUTH-KEY"
----

ou fournir ces informations dans un fichier et utiliser le paramètre :

[,bash]
----
--vpn-auth-file=$PATH_TO_FILE
----

En option, si vous avez votre propre serveur Tailscale (par exemple headscale), vous pouvez vous y connecter en ajoutant `+,controlServerURL=$URL+` aux paramètres vpn-auth.

Ensuite, vous pouvez créer le serveur à l'aide de la commande suivante :

[,bash]
----
k3s server --token <token> --vpn-auth="name=tailscale,joinKey=<joinKey>" --node-external-ip=<TailscaleIPOfServerNode>
----

Après avoir exécuté cette commande, accédez à la console d'administration Tailscale pour approuver le nœud et le sous-réseau Tailscale (s'ils n'ont pas déjà été approuvés par les autoApprovers). 

Une fois le serveur configuré, connectez les agents en utilisant :

[,bash]
----
k3s agent --token <token> --vpn-auth="name=tailscale,joinKey=<joinKey>" --server https://<TailscaleIPOfServerNode>:6443 --node-external-ip=<TailscaleIPOfAgentNode>
----

De nouveau, approuvez le nœud et le sous-réseau Tailscale comme vous l'avez fait pour le serveur.

Si vous avez activé des ACL dans Tailscale, vous devez ajouter une règle "accept" pour permettre aux pods de communiquer entre eux. En supposant que la clé d'authentification que vous avez créée marque automatiquement les nœuds Tailscale avec la balise `+testing-k3s+`, la règle devrait ressembler à ceci :

[,yaml]
----
"acls": [
    {
        "action": "accept",
        "src":    ["tag:testing-k3s", "10.42.0.0/16"],
        "dst":    ["tag:testing-k3s:*", "10.42.0.0/16:*"],
    },
],
----

[CAUTION]
====
Si vous prévoyez de faire fonctionner plusieurs clusters K3s en utilisant le même réseau tailscale, veuillez créer des https://tailscale.com/kb/1018/acls/[ACLs] appropriés pour éviter les conflits d'IP ou utiliser des sous-réseaux podCIDR différents pour chaque cluster.
====
