include::partial$variables.adoc[]
= Uso de autoridades de certificação personalizadas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure o PolicyServer para usar autoridades de certificação personalizadas ou fontes inseguras em conjunto com registros especificados.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "policy-servers", "custom-certificate-authorities"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "autoridades de certificação personalizadas"]
:sidebar_label: Uso de CAs personalizadas
:current-version: {page-origin-branch}

== Autoridades de certificação personalizadas para registros de políticas

É possível especificar e configurar as autoridades de certificação que um PolicyServer usa ao extrair os artefatos ClusterAdmissionPolicy do registro de políticas. Os seguintes campos de `+spec+` configuram o executável`+policy-server+` implantado para esse efeito.

=== Fontes inseguras

[IMPORTANT]
====

O comportamento padrão de `+kwctl+` e `+policy-server+` é impor HTTPS com certificados confiáveis que correspondam ao armazenamento da CA do sistema. Você pode interagir com os registros usando certificados não confiáveis ou mesmo sem TLS, usando a configuração`+insecure_sources+`. Essa abordagem é *altamente desaconselhada* para ambientes mais próximos da produção.

====

Para configurar o PolicyServer para aceitar conexões inseguras com registros específicos, use o campo `+spec.insecureSources+` do PolicyServer. Esse campo aceita uma lista de URIs inseguros. Por exemplo:

[subs="+attributes",yaml]
----
spec:
  insecureSources:
    - localhost:5000
    - host.k3d.internal:5000
----

Consulte xref:howtos/custom-certificate-authorities.adoc[Autoridade de certificados personalizados] para obter mais informações sobre como o executável `+policy-server+` trata URIs inseguros.

=== Autoridades de certificação personalizadas

Você pode configurar o PolicyServer com uma cadeia de certificados personalizada de 1 ou mais certificados para um URI específico. Para fazer isso, use o campo`+spec.sourceAuthorities+`.

Esse campo é um mapa de URIs, cada um com sua própria lista de cadeias de caracteres que contêm certificados codificados em PEM (Privacy Enhanced Mail). Por exemplo:

[subs="+attributes",yaml]
----
spec:
  sourceAuthorities:
    "registry-pre.example.com":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-1 PEM cert
        -----END CERTIFICATE-----
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-2 PEM cert
        -----END CERTIFICATE-----
    "registry-pre2.example.com:5500":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre2 PEM cert
        -----END CERTIFICATE-----
----

Consulte xref:howtos/custom-certificate-authorities.adoc[Autoridades de certificação personalizadas] para obter mais informações sobre como o executável `+policy-server+` as trata.
