include::partial$variables.adoc[]
= Ferrugem
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Saiba como escrever políticas de controlador de admissão no Rust com o SDK simplificado de controladores de admissão de segurança do SUSE e projetos de modelo.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "políticas de escrita", "introdução"].
:sidebar_label: Ferrugem
:current-version: {page-origin-branch}

https://www.rust-lang.org/[Rust] é a linguagem de programação mais madura que pode gerar módulos do WebAssembly.
O WebAssembly é um cidadão de primeira classe no mundo Rust, portanto, muitas das ferramentas e caixas do ecossistema Rust funcionam imediatamente.

{project-name} fornece um https://crates.io/crates/kubewarden-policy-sdk[SDK] Rust que simplifica o processo de criação de políticas.
Há também um https://github.com/kubewarden/rust-policy-template[projeto de modelo] para fornecer andaimes para um projeto de política usando o https://github.com/cargo-generate/cargo-generate[] utilitário.

Esta documentação mostra como usar esses projetos para escrever políticas {short-project-name} usando Rust.
Ele não aborda os detalhes do Rust SDK do {short-project-name}.
Os detalhes estão na https://docs.rs/kubewarden-policy-sdk/0.1.0[documentação da caixa].

== Obtendo as dependências do Rust

Instale o compilador Rust e suas ferramentas usandohttps://github.com/rust-lang/rustup[] rustup.
Consulte a rustup https://rust-lang.github.io/rustup/installation/index.html[documentação de instalação do].

Depois de instalar o site `+rustup+`, adicione o alvo WebAssembly System Interface (WASI):

[subs="+attributes",console]
----
rustup target add wasm32-wasip1
----

== Dependências do OSX

Para usar o site `+cargo-generate+`, você precisa adicionar o conjunto de ferramentas do Xcode.
Se ele não for instalado pelo Xcode, o comando a seguir fornecerá as dependências necessárias:

[subs="+attributes",console]
----
xcode-select --install
----
