include::partial$variables.adoc[]
= Criação de uma política
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprenda a criar e configurar políticas de validação que controlam as solicitações de criação de POD com base em critérios de rejeição personalizáveis.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "creating-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "criação de política"]
:sidebar_label: Criação de uma política
:current-version: {page-origin-branch}

Como exemplo, você cria uma política de validação simples que processa solicitações de criação de POD.

A política analisa o atributo `+metadata.name+` do pod e rejeita pods com um nome inválido.
Sua lista de nomes inválidos deve ser configurada pelos usuários finais da política.

As configurações de política são semelhantes:

[subs="+attributes",yaml]
----
invalid_names:
- bad_name1
- bad_name2
----

A política deve aceitar a criação de um POD como o seguinte:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

Ele deve rejeitar a criação de um POD do tipo:

[subs="+attributes",yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: bad_name1
spec:
  containers:
    - name: nginx
      image: nginx:latest
----

== Montando os andaimes do novo projeto de política

Você pode criar um novo projeto de política usando `+cargo generate+` com ohttps://github.com/kubewarden/rust-policy-template[projeto de modelo].

Primeiro, instale o site `+cargo-generate+`. Isso requer https://pkgs.org/download/openssl-devel[openssl-devel].

[subs="+attributes",shell]
----
cargo install cargo-generate
----

Agora, monte o projeto da seguinte forma:

[subs="+attributes",shell]
----
cargo generate --git https://github.com/kubewarden/rust-policy-template \
               --branch main \
               --name demo
----

O comando produz resultados como:

[subs="+attributes",console]
----
🔧   Creating project called `+demo+`...
✨   Done! New project created /<some-path-name>/demo
----

Isso cria o novo projeto de política no subdiretório `+demo+`.

[NOTE]
====

Se você planeja usar a funcionalidade de registro de contêiner do GitHub na demonstração, é necessáriohttps://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry#enabling-the-container-registry-for-your-personal-account[ativar o suporte aprimorado a contêineres].
====


=== Testes

Você pode tentar:

[subs="+attributes",console]
----
cargo test
----

Isso testa o andaime gerado. Se tudo estiver no lugar certo, você verá uma série de mensagens de compilação que terminam com um resultado como:

[subs="+attributes",console]
----
running 4 tests
test settings::tests::validate_settings ... ok
test tests::accept_request_with_non_pod_resource ... ok
test tests::accept_pod_with_valid_name ... ok
test tests::reject_pod_with_invalid_name ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
----
