= Java 应用程序
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

Java SDK 支持在 JVM 上检测应用程序。因此，它不仅支持 Java，还支持 Kotlin 和 Scala 等其他 JVM 语言。

== 自动仪器

Java 自动仪器使用 Java 代理 JAR，可附加到任何 Java 8+ 应用程序。它可动态注入字节码，以捕获来自许多https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md[流行库和框架（]包括几个 Kotlin 和 Scala 库）的遥测数据。它可用于捕获&quot;`+edges+`&quot; 应用程序或服务的遥测数据，如入站请求、出站 HTTP 调用、数据库调用等。

自动仪器不需要对应用程序进行任何修改。设置步骤如下

. 从https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases[Releases]of资源库下载https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar[opentelemetry-java-instrumentation]-，并将 JAR 文件包含在应用程序的 docker 镜像中。JAR 文件包含代理和仪器库。
. 通过更新 docker 镜像入口点或命令，或者更新 Kubernetes 清单中应用程序的`+command+` ，更新启动应用程序的命令以加载 Java 代理。添加`+-javaagent:/path/to/opentelemetry-javaagent.jar+` ：
+
[,bash]
----
java -javaagent:/path/to/opentelemetry-javaagent.jar -jar myapp.jar
----

. 使用额外的环境变量部署应用程序xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[，以配置服务名称和输出端点]，支持的协议有 gRPC 和 HTTP 上的 protobuf。
. 通过在指标/跟踪资源管理器中搜索服务名称的指标/跟踪，验证 SUSE Observability 是否接收跟踪和/或指标。

详情请参考https://opentelemetry.io/docs/languages/java/automatic/[Open Telemetry 文档]。

== 手动仪表

如果需要自动仪器不支持的代码部分的指标、跟踪或日志，可以使用手动仪器。例如，不支持的库，内部代码或业务级指标。

要获取这些数据，您需要修改您的应用程序。

. 将 Open Telemetry SDK 列入依赖项
. 在应用程序中添加代码，以便在需要时捕获指标、跨度或日志

https://opentelemetry.io/docs/languages/java/instrumentation/[Open Telemetry Java SDK 文档页面]上有详细的相关文档。

确保使用 OTLP 输出程序（这是默认设置）和https://opentelemetry.io/docs/languages/java/instrumentation/#_autoconfiguration[自动配置]。部署应用程序时，可xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[通过环境变量配置]服务名称和出口程序。

== SUSE Observability 中的度量标准

ifdef::ss-ff-stackpacks2_enabled[]
对于某些 Java 指标，例如垃圾收集器指标，SUSE Observability 已为相关组件定义了图表。对于 Kubernetes，图表可在 pod 上查看。可以xref:/setup/custom-integrations/metric-bindings/index.adoc[为更多指标添加图表]，这不仅适用于来自自动仪器的指标，也适用于来自手动仪器的特定应用指标。
endif::[]

ifndef::ss-ff-stackpacks2_enabled[]
对于某些 Java 指标，例如垃圾收集器指标，SUSE Observability 已为相关组件定义了图表。对于 Kubernetes，图表可在 pod 上查看。可以xref:/use/metrics/k8s-add-charts.adoc[为更多指标添加图表]，这不仅适用于来自自动仪器的指标，也适用于来自手动仪器的特定应用指标。
endif::[]
