= LDAP
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Visão geral

O SUSE Observability pode usar um servidor LDAP (incluindo o AD) para autenticação e para obter funções/grupos. Ele requer um servidor LDAP em execução que seja acessível ao SUSE Observability.

O diretório principal do LDAP e todos os subdiretórios serão verificados quanto a arquivos de usuário. As credenciais de associação na configuração do SUSE Observability são usadas para autenticar o SUSE Observability no servidor LDAP. Após a autenticação, o SUSE Observability passa o nome do diretório LDAP superior para o usuário que deseja fazer login no SUSE Observability.

== Configurar o SUSE Observability para LDAP

=== Kubernetes

Para configurar o SUSE Observability para autenticar usando um servidor de autenticação LDAP no Kubernetes, os detalhes do LDAP e o mapeamento da função do usuário precisam ser adicionados ao arquivo `+authentication.yaml+`. Por exemplo:

[tabs]
====
authentication.yaml::
+
--

[,yaml]
----
stackstate:
  authentication:
    ldap:
      host: sts-ldap
      port: 10389 # For most LDAP servers 389 for plain, 636 for ssl connections
      #ssl:
      #  sslType: ssl
      #  trustStore: <see below>
      #  trustCertificates <see below>
      bind:
        dn: "cn=admin,ou=employees,dc=acme,dc=com"
        password: "password"
      userQuery:
        parameters:
          - ou: employees
          - dc: acme
          - dc: com
        usernameKey: cn
        emailKey: mail
      groupQuery:
        parameters:
          - ou: groups
          - dc: acme
          - dc: com
        rolesKey: cn
        groupMemberKey: member
        # to return all nested groups, use:
        # groupMemberKey: "member:1.2.840.113556.1.4.1941:"

    # map the groups from LDAP to the
    # standard subjects in SUSE Observability (guest, powerUser and admin)
    roles:
      guest: ["ldap-guest-role-for-stackstate"]
      powerUser: ["ldap-power-user-role-for-stackstate"]
      admin: ["ldap-admin-role-for-stackstate"]
----

--
====

Siga as etapas abaixo para configurar o SUSE Observability para autenticar usando LDAP:

. Em `+authentication.yaml+` - adicione detalhes do LDAP (veja o exemplo acima):
 ** *host* - O nome do host do servidor LDAP.
 ** *port* - A porta em que o servidor LDAP está escutando.
 ** *sslType* - opcional. O tipo de conexão segura LDAP `+ssl+` ou `+startTls+`. Omitir se for usada uma conexão LDAP simples.
 ** *trustCertificates* - Opcional, arquivo de certificado para SSL. Os formatos PEM, DER e PKCS7 são compatíveis.
 ** *trustStore* - Opcional, arquivo de armazenamento de confiança Java para SSL. Se ambos `+trustCertificates+` e `+trustStore+` forem especificados, `+trustCertificatesPath+` terá precedência.
 ** *bind* - Opcional, usado para autenticar o SUSE Observability no servidor LDAP se o servidor LDAP não for compatível com pesquisas LDAP anônimas.
 ** *Parâmetros userQuery e parâmetros groupQuery* - O conjunto de parâmetros internos corresponde ao dn de base do seu LDAP onde os usuários e grupos podem ser encontrados. O primeiro é usado para autenticar usuários no SUSE Observability, enquanto o segundo é usado para recuperar o grupo desse usuário para determinar se ele é um administrador, um usuário avançado ou um convidado.
 ** *usernameKey* - O nome do atributo que armazena o nome de usuário; o valor é comparado com o nome de usuário fornecido na tela de login.
 ** *emailKey* - O nome do atributo que é usado como endereço de e-mail no SUSE Observability.
 ** *rolesKey* - O nome do atributo que armazena o nome do grupo.
 ** *groupMemberKey* - O nome do atributo que indica se um usuário é membro de um grupo. O filtro LDAP construído segue este padrão: `+<groupMemberKey>=<user.dn>,ou=groups,dc=acme,dc=com+`. Para retornar todos os grupos aninhados, use `+groupMemberKey: "member:1.2.840.113556.1.4.1941:"+`.
. Em `+authentication.yaml+` - mapeie as funções de usuário do LDAP para os assuntos corretos do SUSE Observability (veja o exemplo acima):
 ** *funções* - para obter detalhes, consulte as xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[funções padrão do SUSE Observability]. Mais funções do SUSE Observability também podem ser criadas, consulte a xref:/setup/security/rbac/README.adoc[documentação do RBAC].
. Armazene o arquivo `+authentication.yaml+` junto com o `+values.yaml+` das instruções de instalação do SUSE Observability.
. Execute um upgrade do Helm para aplicar as alterações. Se você estiver usando SSL com certificados personalizados, os arquivos de certificado binário que devem ser usados ao se conectar ao LDAP devem ser definidos na linha de comando; use o comando em *SSL com certificados personalizados*:

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

*trustCertificates*

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
  --set-file stackstate.authentication.ldap.ssl.trustCertificates=./ldap-certificate.pem \
suse-observability \
suse-observability/suse-observability
----

*trustStore*

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
  --set-file stackstate.authentication.ldap.ssl.trustStore=./ldap-cacerts \
suse-observability \
suse-observability/suse-observability
----

[NOTE]
====
*Observação:*

* A primeira execução do comando helm upgrade resultará na reinicialização dos pods, o que pode causar uma breve interrupção da disponibilidade.
* Inclua `+authentication.yaml+` em cada execução de `+helm upgrade+`.
* A configuração de autenticação é armazenada como um segredo do Kubernetes.
====


=== Usando um segredo externo

Quando a senha do ldap tiver que vir de um segredo externo, siga xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[estas etapas], mas preencha os dados a seguir:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  ldap_password: <base64 of ldap password>
----

== Veja também

* xref:/setup/security/authentication/authentication_options.adoc[Opções de autenticação]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permissões para funções predefinidas do SUSE Observability]
* xref:/setup/security/rbac/rbac_roles.adoc[Criar funções RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Segredos externos]
