= kubernetesアノテーションでモニターしきい値の引数をオーバーライドする
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 概要

SUSE Observabilityは、Kubernetesクラスタで発生する可能性のある一般的な問題を監視するxref:/use/alerting/k8s-monitors.adoc[モニターをすぐに]提供します。これらのモニターは、ほとんどのユースケースに適した特定のデフォルト引数で動作するが、`threshold` や`failureState` のようなデフォルト引数をオーバーライドすることによって、その動作を適応させる必要がある場合もある。
オーバーライドを宣言するメカニズムは、どのモニターとコンポーネントに適用するかを示すkubernetesリソースアノテーションを介して行われる。例えば、デフォルトの`DEVIATING` ではなく、失敗したときに`CRITICAL` の状態を通知したい特定のサービスに対して、`Available service endpoints` モニタの`failureState` をオーバーライドすることができる。

== どのように

* <<_how_to_build_my_annotation,アノテーションの作り方>>
* <<_what_monitors_allow_overriding_arguments,引数を上書きできるモニターは？>>
* <<_build_an_override_for_a_custom_monitor,カスタムモニターのオーバーライドを構築する>>

例として、Kubernetes HTTPサービスの`Available service endpoints` モニター用の引数を上書きします。

== アノテーションの作り方

SUSE Observabilityモニタのオーバーライドアノテーションキーは、次の規則に従います：

----
monitor.${owner}.stackstate.io/${monitorShorName}
----

`owner` プロパティは、そのようなモニターを誰が作成したかを表し、アウトオブボックス・モニターの場合は`kubernetes-v2` である。また、`monitorShorName` プロパティはモニターの ID を表し、モニターの一覧表示や検査時に cli から読み取ることができるモニターの`identifier` プロパティから抽出することができる。

----
sts monitor list

ID              | STATUS  | IDENTIFIER                                                                          | NAME                                        | FUNCTION ID     | TAGS
8051105457030   | ENABLED | urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:service-available-endpoint | Available service endpoints                 | 233276809885571 | [services]
----

この例では、識別子は`urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:service-available-endpoint` であり、`monitorShorName` は`service-available-endpoint` のように最後のセグメントに対応する：

[,bash]
----
monitor.kubernetes-v2.stackstate.io/service-available-endpoint
----

アノテーションのペイロードはJSONオブジェクトで、以下のオプション引数を定義できます：

* `threshold`オプション。比較する数値のしきい値。
* `failureState`オプション。CRITICAL」か「DEVIATING」のどちらか。SUSEのObservabilityでは "CRITICAL "と表示され、"DEVIATING "はオレンジ色で表示されます。
* `enabled`オプション。モニターがそのコンポーネントの健康状態を生成するかどうかを決定するブール値。

完全な注釈は次のようになる。

[,bash]
----
    monitor.kubernetes-v2.stackstate.io/service-available-endpoint: |-
      {
        "threshold": 0.0,
        "failureState": "CRITICAL",
        "enabled": true
      }
----

== 引数を上書きできるモニターは？

* xref:/use/alerting/kubernetes-monitors.adoc#_available_service_endpoints[利用可能なサービス・エンドポイント]
* xref:/use/alerting/kubernetes-monitors.adoc#_cpu_limits_resourcequota[リソースクォータ]
* xref:/use/alerting/kubernetes-monitors.adoc#_cpu_requests_resourcequota[リソースクォータ]
* xref:/use/alerting/kubernetes-monitors.adoc#_memory_limits_resourcequota[メモリ制限 resourcequota]
* xref:/use/alerting/kubernetes-monitors.adoc#_memory_requests_resourcequota[メモリ要求数 resourcequota]
* xref:/use/alerting/kubernetes-monitors.adoc#_node_disk_pressure[ノードディスク圧力]
* xref:/use/alerting/kubernetes-monitors.adoc#_node_memory_pressure[ノードメモリー圧力]
* xref:/use/alerting/kubernetes-monitors.adoc#_node_pid_pressure[ノード PID 圧力]
* xref:/use/alerting/kubernetes-monitors.adoc#_node_readiness[ノードの準備]
* xref:/use/alerting/kubernetes-monitors.adoc#_orphaned_persistent_volumes[孤児化した永続ボリューム]（`enabled` プロパティのみ）
* xref:/use/alerting/kubernetes-monitors.adoc#_out_of_memory_for_containers[コンテナのメモリ不足]
* xref:/use/alerting/kubernetes-monitors.adoc#_http_5xx_error_ratio[HTTP - 5xx エラーの割合]
* xref:/use/alerting/kubernetes-monitors.adoc#_http_response_time_q95_is_above_3_seconds[HTTP - レスポンスタイム - Q95 が3秒以上]

== カスタムモニターのオーバーライドを構築する

xref:/use/alerting/k8s-add-monitors-cli.adoc[CLI を使用してコンポーネントにしきい値モニターを追加する]」のガイドを使用して作成されたカスタムしきい値モニターはすべて、引数をオーバーライドするのに適しています。このxref:/use/alerting/k8s-add-monitors-cli.adoc#_write_the_outline_of_the_monitor[例が示すように]、カスタムモニターの識別子は``+urn:custom:monitor:{monitorShortName}``という構造になっており、このような識別子のオーバーライド注釈キーは次のようになることが期待されます。

[,bash]
----
monitor.custom.stackstate.io/${monitorShortName}
----

この例では、`urn:custom:monitor:deployment-has-replicas` という識別子を使用しているため、アノテーションキーは次のようになります。

[,bash]
----
monitor.custom.stackstate.io/deployment-has-replicas
----

そして、完全な注釈は次のようになる。

[,bash]
----
    monitor.custom.stackstate.io/deployment-has-replicas: |-
      {
        "threshold": 0.0,
        "failureState": "CRITICAL"
        "enabled": true
      }
----
