= Fehlersuche bei Erweiterungen
:revdate: 2025-11-03
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

Dieser Abschnitt enthält Schritte zur Fehlerbehebung bei Interoperabilitätsproblemen zwischen {stackstate-product-name} und der Rancher UI-Erweiterung.

== Sammeln Sie ein HAR (Http ARchive)

Http ARchive sammelt Details zu Anfragen, die vom Browser an Rancher und {stackstate-product-name} gesendet werden.  Sie protokolliert auch die eingegangenen Antworten.
Dieses Archiv ist spezifisch für die Seite/Browser-Registerkarte mit dem Fehler.  Es benötigt keinen Zugriff auf die Rancher- oder {stackstate-product-name} -Instanzen (obwohl deren Protokolle zu einem späteren Zeitpunkt nützlich sein können).

* Öffnen Sie die Registerkarte *Netzwerk* im Fenster "Entwicklertools".  Sie können dies über `+F12+` aufrufen.  Auf der Registerkarte "Netzwerk" wird ein Protokoll aller gestellten Anfragen angezeigt.
* Löschen Sie das Protokoll und aktualisieren Sie die Seite, auf der das problematische Verhalten auftritt, (hart).
* Es sollte nun eine große Anzahl von Anfragen an Rancher und SUSE Observability sichtbar sein.
* Exportieren/Downloaden/Speichern der HAR - verschiedene Browser verwenden hier unterschiedliche Namen.

== Cluster ist unbeobachtet

Damit der Gesundheitszustand des Clusters in Rancher sichtbar ist, müssen diese Konfigurationen aufeinander abgestimmt sein:

* Der (Anzeige-)Name des Clusters in der Rancher-Benutzeroberfläche.
* Die `+stackstate.cluster.name+` auf dem Agenten, der auf dem Cluster eingesetzt wird
* Der Clustername in der Konfiguration des Kubernetes-Stackpacks in SUSE Observability

Eine Fehlanpassung wird in der Regel als "keine Daten empfangen" in der Clusterübersicht in Rancher angezeigt.

== Verbindung fehlgeschlagen

Die Konfiguration für SUSE Observability kann aus den folgenden Gründen manchmal keine gültige Verbindung in der Rancher-Benutzeroberfläche ergeben:

* Der Rancher-Host ist nicht als zulässiger Ursprung für SUSE Observability konfiguriert.  Sie können dies beheben, indem Sie es in die Liste `+stackstate.allowedOrigins+` in den Helm-Werten aufnehmen oder `+--set stackstate.allowedOrigins={"https://<rancher-url>"}+` an den Bereitstellungsbefehl übergeben.
* SUSE Observability ist nicht über den Browser zugänglich. Zum Beispiel wurde das Stammzertifikat nicht installiert.