= Anleitung für den ersten Lauf
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

== Übersicht

Auf dieser Seite finden Sie alle Informationen, die Sie zur Installation und Ausführung von SUSE Observability benötigen.

== Einbauanleitung

[tabs]
====
Kubernetes::
+
--
Installieren Sie SUSE Observability auf xref:/setup/install-stackstate/kubernetes_openshift/README.adoc[Kubernetes].
--

OpenShift::
+
--
Installieren Sie SUSE Observability auf xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift].
--
====

== Adresse und Hafen

[tabs]
====
Kubernetes::
+
--
So greifen Sie auf die SUSE Observability-Benutzeroberfläche zu:

. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_access_the_suse_observability_ui[Aktivieren Sie eine Port-Weiterleitung].
. Zugriff auf die SUSE Observability UI unter: https://localhost:8080
--

OpenShift::
+
--
So greifen Sie auf die SUSE Observability-Benutzeroberfläche zu:

. xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_access_the_suse_observability_ui[Aktivieren Sie eine Port-Weiterleitung].
. Zugriff auf die SUSE Observability UI unter: https://localhost:8080
--
====

== Standard-Benutzername und -Passwort

[tabs]
====
Kubernetes::
+
--
SUSE Observability wird standardmäßig mit dem folgenden Administratorkonto konfiguriert:

* *Benutzernamen:* `+admin+`
* *Kennwort:* Wird bei der Installation eingestellt. Diese wird vom Skript `+generate_values.sh+` gesammelt und im MD5-Hash-Format in `+values.yaml+`
--

OpenShift::
+
--
SUSE Observability wird standardmäßig mit dem folgenden Administratorkonto konfiguriert:

* *Benutzernamen:* `+admin+`
* *Kennwort:* Wird bei der Installation eingestellt. Diese wird vom Skript `+generate_values.sh+` gesammelt und im MD5-Hash-Format in `+values.yaml+`
--
====

== Fehlersuche

Wenn Sie während der Installation von SUSE Observability oder bei der ersten Ausführung auf Probleme stoßen, lesen Sie die xref:/setup/install-stackstate/troubleshooting.adoc[Anleitung zur Fehlerbehebung bei der Installation von SUSE Observability].

== Nächste Schritte

Sobald Sie SUSE Observability eingerichtet haben, können Sie mit der Einrichtung von Integrationen beginnen

* xref:/k8s-quick-start-guide.adoc[Installation von StackPacks zur Integration mit externen Systemen]
* xref:/use/views/k8s-views.adoc[Erkunden Sie Ihren Kubernetes-Cluster]
