= Anforderungen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

== Übersicht

Die Anforderungen für den <<_client_browser,SUSE Observability-Client (Browser)>> finden Sie am Ende der Seite.

=== Kompatibilität mit Rancher und Kubernetes
Sehen Sie sich die Kompatibilitätsseite hier an xref:setup/install-stackstate/Compatibility Self Hosted.adoc[Rancher/Kubernetes-Kompatibilität]

=== Anforderungen an die Ressourcen

Für SUSE Observability gibt es verschiedene Installationsoptionen. SUSE Observability kann entweder in einem Hochverfügbarkeits- (HA) oder einem Einzelinstanz-Setup (nicht HA) installiert werden. Die Nicht-HA-Einrichtung wird nur zu Testzwecken empfohlen. Für Produktionsumgebungen wird empfohlen, SUSE Observability in einem HA-Setup zu installieren. Bei einer Standard-Produktionsimplementierung stellt das SUSE Observability Helm-Diagramm viele Services in einer redundanten Konfiguration mit 3 Instanzen jedes Services bereit.

In der nachstehenden Tabelle finden Sie die Ressourcenanforderungen für die verschiedenen Installationsoptionen. Für das HA-Setup gibt es verschiedene Installationsprofile, die von der Größe der zu beobachtenden Umgebung abhängen.
Ein beobachteter Knoten wird in dieser Dimensionierungstabelle mit 4 vCPUs und 16 GB Arbeitsspeicher angenommen, unsere `+default node size+`.
Wenn Knoten in Ihrem beobachteten Cluster größer sind, können sie für mehrere `+default nodes+` zählen, so dass ein Knoten mit 12vCPU und 48GB als 3 `+default nodes+` unter Beobachtung zählt, wenn Sie ein Profil auswählen.

|===
|  | Versuch | 10 Nicht-HA | 20 Nicht-HA | 50 Nicht-HA | 100 nicht-HA | 150 HA | 250 HA | 500 HA | 4000 HA

| *CPU-Anforderungen*
| 7.0
| 7.0
| 9.3
| 14.0
| 23.6
| 49.6
| 61.6
| 85.1
| 212.1

| *CPU-Grenzwerte*
| 15.1
| 15.1
| 19.4
| 28.8
| 47.9
| 105.2
| 128.3
| 176.2
| 281

| *Speicheranfragen*
| 22.7Gi
| 22.7Gi
| 26.5Gi
| 30.9Gi
| 47.0Gi
| 127,0Gi
| 142.1Gi
| 166,4Gi
| 263,9Gi

| *Speicherbegrenzungen*
| 23.3Gi
| 23.3Gi
| 27.2Gi
| 31.0Gi
| 47.2Gi
| 131.8Gi
| 146,7Gi
| 171.2Gi
| 321.7Gi
|===

[NOTE]
====
Die für das Profil angezeigten Anforderungen stellen die Gesamtmenge an Ressourcen dar, die für den Betrieb des Suse Observability-Servers erforderlich sind.
Um sicherzustellen, dass alle verschiedenen Dienste des Suse Observability-Servers zugewiesen werden können:

* Für Nicht-HA-Installationen beträgt die empfohlene Knotengröße 4VCPU, 8GB
* Für HA-Installationen mit bis zu 500 Knoten wird eine Mindestknotengröße von 8 VCPU und 16 GB empfohlen.
* Für HA-Installationen mit 4000 Knoten beträgt die empfohlene Mindestknotengröße 16 VCPU, 32 GB
====


Dies sind nur die Ober- und Untergrenzen für die Ressourcen, die von SUSE Observability bei den verschiedenen Installationsoptionen verbraucht werden können. Die tatsächliche Ressourcennutzung hängt von den verwendeten Funktionen, den konfigurierten Ressourcengrenzen und den dynamischen Nutzungsmustern ab, z. B. der Skalierung von Deployment oder DaemonSet. Für unsere Self-Hosted-Kunden empfehlen wir, mit den Standardanforderungen zu beginnen und die Ressourcennutzung der SUSE Observability-Komponenten zu überwachen.

[NOTE]
====
Die Mindestanforderungen beinhalten keine zusätzliche CPU-/Speicherkapazität, um eine reibungslose Aktualisierung der Anwendung zu gewährleisten.
====


Für die Installation von SUSE Observability folgen Sie bitte den unten stehenden Installationsanweisungen:

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift]

=== Lagerung

SUSE Observability verwendet persistente Volume-Ansprüche für die Services, die Daten speichern müssen. Die Standardspeicherklasse für den Cluster wird für alle Dienste verwendet, es sei denn, sie wird durch Werte überschrieben, die in der Befehlszeile oder in einer Datei `+values.yaml+` angegeben werden. Alle Dienste werden mit einer vorkonfigurierten Volume-Größe ausgeliefert, die für den Anfang ausreichen sollte, die aber später mit Hilfe von Variablen nach Bedarf angepasst werden kann.

[NOTE]
====
Für Produktionsumgebungen wird NFS für das Storage-Provisioning in SUSE Observability aufgrund des potenziellen Risikos einer Datenbeschädigung nicht empfohlen und unterstützt.
====


Für unsere verschiedenen Installationsprofile gelten die folgenden Standard-Speicheranforderungen:

|===
|  | Versuch | 10 Nicht-HA | 20 Nicht-HA | 50 Nicht-HA | 100 nicht-HA | 150 HA | 250 HA | 500 HA | 4000 HA

| *Verbleib (Tage)*
| 3
| 30
| 30
| 30
| 30
| 30
| 30
| 30
| 30

| *Speicherbedarf*
| 163GB
| 358GB
| 401GB
| 508GB
| 562GB
| 2.8TB
| 2.9TB
| 3.9TB
| 7.5TB
|===

[NOTE]
====
Die vorgelegten Schätzungen für die Aufbewahrung berücksichtigen eine Standardaufbewahrung von 14 Tagen für NONHA- und 1 Monat für HA-Anlagen. Für kurzlebige Testinstanzen können die Speichergrößen weiter reduziert werden.
====


Weitere Einzelheiten zu den verwendeten Standardeinstellungen finden Sie auf der Seite xref:/setup/install-stackstate/kubernetes_openshift/storage.adoc[Speicher konfigurieren].

=== Begrenzung der Ressourcen des Namensraums

Es wird nicht empfohlen, eine ResourceQuota festzulegen, da dies Ressourcenanfragen beeinträchtigen kann. Die von SUSE Observability benötigten Ressourcen variieren je nach den verwendeten Funktionen, den konfigurierten Ressourcenlimits und den dynamischen Nutzungsmustern, wie z. B. der Skalierung von Deployment oder DaemonSet.

Wenn es notwendig ist, eine ResourceQuota für Ihre Implementierung festzulegen, sollte das Namespace-Ressourcenlimit so festgelegt werden, dass es den xref:/setup/install-stackstate/requirements.adoc#_resource_requirements[Anforderungen an die Knotengröße] entspricht.

== Kunde (Browser)

Um die SUSE Observability-GUI zu verwenden, müssen Sie einen der folgenden Webbrowser benutzen:

* Chrom
* Firefox
