= OS-Management für Rancher
:revdate: 2026-01-16
:page-revdate: {revdate}

{elemental-product-name} ist ein Software-Stack, der ein zentralisiertes, vollständig cloud-natives OS-Management mit Kubernetes ermöglicht.

xref:release-notes.adoc[**Latest Release: v1.8.0**]

Der {elemental-product-name} Stack besteht aus einer Handvoll von Paketen, die auf SLE Micro aufsetzen:

* *elemental-toolkit* - Enthält eine Reihe von Betriebssystem-Dienstprogrammen, die die Verwaltung des Betriebssystems über Container ermöglichen. Enthält Dracut-Module, Bootloader-Konfiguration, Konfigurationsdienste im Stil von Cloud-Init usw.
* *elemental-operator* - Stellt eine Verbindung zum Rancher Manager her und bearbeitet die CRDs MachineRegistration und MachineInventory.
* *elemental-register* - Registriert Maschinen über machineRegistrations und installiert sie über elemental-cli.
* *elemental-cli* - Installiert jedes elemental-toolkit-basierte Derivat. Im Grunde ein Installationsprogramm, das auf unserem A/B-Installations- und Upgrade-System basiert.
* *rancher-system-agent* - Läuft auf dem installierten System und erhält Anweisungen ("Pläne") vom Rancher Manager, was auf dem System zu installieren und auszuführen ist.

Cluster-Node-Betriebssysteme werden über Container-Images durch die {elemental_cli_name} erstellt und gewartet und können auf neuen Hosts mit dem {elemental_ui_url}[{elemental_ui_name}] für https://www.rancher.com/products/rancher[Manager] Rancher oder dem {elemental_cli_url}[{elemental_cli_name}] installiert werden.

{elemental_operator_url}[{elemental_operator_name}] und {ranchersystemagent_url}[{ranchersystemagent_name}] ermöglichen es dem Rancher Manager, {elemental-product-name} -Cluster vollständig zu kontrollieren, von der Installation und Verwaltung des Betriebssystems auf den Nodes bis hin zur Bereitstellung neuer K3- oder RKE2-Cluster auf zentralisierte Weise.

== {elemental-product-name} auf x86-64-Hardware

{elemental-product-name} ist produktionsreif und wird ab Rancher v2.7.0 vollständig auf x86-64 unterstützt.

== {elemental-product-name} auf ARM-Hardware

ARM (aarch64) ist im Entwicklungsstadium funktionsfähig. ARM wird derzeit nur auf Raspberry Pi 4 Model B mit k3s 1.24.8 (oder höher) getestet. Rückmeldungen sind willkommen.

== {elemental-product-name} auf anderer Hardware

{elemental-product-name} ist derzeit auf "Edge"-Szenarien ausgerichtet und unterstützt daher keine andere Hardware. Wir werden dies in Abhängigkeit von der Entwicklung des Marktes neu bewerten.

== Sind Sie bereit, es auszuprobieren?

Richten Sie einen {elemental-product-name} Cluster mit der von Ihnen bevorzugten Methode ein und starten Sie ihn

* Mit dem Rancher-Manager xref:quickstarts/quickstart-ui.adoc[{elemental-product-name} plugin]
* Mit der xref:quickstarts/quickstart-cli.adoc[{elemental-product-name} CLI]

[NOTE]
.Was kommt als Nächstes?
====
Möchten Sie weitere Einzelheiten erfahren? Werfen Sie einen Blick in die Rubrik xref:rancher-os-management/architecture/architecture.adoc[Architektur] oder wenden Sie sich an {elemental_slack_url}[{elemental_slack_name}].
====

