= Base de données externe à haute disponibilité
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Cette section décrit comment installer un cluster {k3s-product-name} à haute disponibilité avec une base de données externe.

[NOTE]
====
Pour déployer rapidement de grands clusters HA, voir xref:related-projects.adoc[Projets connexes]
====


Les clusters de serveurs uniques peuvent répondre à divers cas d'utilisation, mais pour les environnements où le temps de disponibilité du plan de contrôle Kubernetes est critique, vous pouvez exécuter les K3 dans une configuration HA. Un cluster HA K3s est composé de :

* Deux *nœuds de serveur* ou plus qui serviront l'API Kubernetes et exécuteront d'autres services du plan de contrôle.
* Un *magasin de données externe* (par opposition au magasin de données SQLite intégré utilisé dans les configurations à serveur unique).
* En option : Zéro ou plusieurs *nœuds d'agent* désignés pour exécuter vos applications et services.
* En option : Une *adresse d'enregistrement fixe* pour que les nœuds agents s'enregistrent auprès du cluster.

Pour plus de détails sur le fonctionnement de ces composants, voir la xref:architecture.adoc#_high_availability_k3s[section architecture.]

== Schéma d'installation

La mise en place d'un cluster HA nécessite les étapes suivantes :

=== 1. Créer un magasin de données externe

Vous devez d'abord créer un magasin de données externe pour le cluster. Pour plus de détails, voir la documentation sur xref:datastore/datastore.adoc[les options de stockage en cluster].

=== 2. Lancer les nœuds de serveur

{k3s-product-name} nécessite au moins deux nœuds de serveur pour cette configuration HA. Voir le guide des xref:installation/requirements.adoc[exigences] pour les exigences minimales de la machine.

Lorsque vous exécutez la commande `+k3s server+` sur ces nœuds, vous devez définir le paramètre `+datastore-endpoint+` afin que K3s sache comment se connecter au magasin de données externe. Le paramètre `+token+` peut également être utilisé pour définir un jeton déterministe lors de l'ajout de nœuds. S'il est vide, ce jeton sera généré automatiquement pour une utilisation ultérieure.

Par exemple, une commande comme la suivante pourrait être utilisée pour installer le serveur K3s avec une base de données MySQL comme dépôt de données externe et xref:cli/server.adoc#_cluster_options[définir un jeton]:

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server \
  --token=SECRET \
  --datastore-endpoint="mysql://username:password@tcp(hostname:3306)/database-name" \
  --tls-san=<FIXED_IP> # Optional, needed if using a fixed registration address
----

Où `+INSTALL_K3S_ARTIFACT_URL+` est l' https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[URL de]

Le format du point de terminaison du magasin de données diffère selon le type de base de données. Pour plus d'informations, reportez-vous à la section sur les xref:datastore/datastore.adoc#_datastore_endpoint_format_and_functionality[formats des points de terminaison des magasins de données.]

Pour configurer les certificats TLS lors du lancement des nœuds de serveur, reportez-vous au xref:datastore/datastore.adoc#_external_datastore_configuration_parameters[guide de configuration du datastore].

[NOTE]
====
Les options d'installation disponibles pour les installations à serveur unique le sont également pour les installations à haute disponibilité. Pour plus de détails, voir la documentation sur les xref:installation/configuration.adoc[options de configuration].
====


Par défaut, les nœuds de serveur sont programmables et vos charges de travail peuvent donc être lancées sur ces nœuds. Si vous souhaitez disposer d'un plan de contrôle dédié dans lequel aucune charge de travail utilisateur ne s'exécutera, vous pouvez utiliser les taints. Le paramètre `+node-taint+` vous permet de configurer des nœuds avec des taches, par exemple `+--node-taint CriticalAddonsOnly=true:NoExecute+`.

Une fois que vous avez lancé le processus `+k3s server+` sur tous les nœuds de serveur, assurez-vous que le cluster s'est correctement mis en place avec `+k3s kubectl get nodes+`. Les nœuds de votre serveur doivent être prêts.

=== 3. En option : Joindre des nœuds de serveur supplémentaires

Le même exemple de commande de l'étape 2 peut être utilisé pour joindre des nœuds de serveur supplémentaires, où le jeton du premier nœud doit être utilisé.

Si le premier nœud de serveur a été démarré sans l'indicateur CLI `+--token+` ou la variable `+K3S_TOKEN+`, la valeur du jeton peut être récupérée à partir de n'importe quel serveur déjà joint au cluster :

[,bash]
----
cat /var/lib/rancher/k3s/server/token
----

Des nœuds de serveur supplémentaires peuvent ensuite être ajoutés à xref:cli/server.adoc#_cluster_options[l'aide du jeton]:

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server \
  --token=SECRET \
  --datastore-endpoint="mysql://username:password@tcp(hostname:3306)/database-name"
----

Quelques drapeaux de configuration doivent être identiques dans tous les nœuds du serveur :

* Drapeaux liés au réseau : `+--cluster-dns+`, `+--cluster-domain+`, `+--cluster-cidr+`, `+--service-cidr+`
* Drapeaux contrôlant le déploiement de certains composants : `+--disable-helm-controller+`, `+--disable-kube-proxy+`, `+--disable-network-policy+` et tout composant passé à `+--disable+`
* Drapeaux liés à la fonctionnalité : `+--secrets-encryption+`

[NOTE]
====
Veillez à conserver une copie de ce jeton, car il est nécessaire lors de la restauration à partir d'une sauvegarde et de l'ajout de nœuds. Auparavant, K3s n'imposait pas l'utilisation d'un jeton lors de l'utilisation de datastores SQL externes.
====


=== 4. En option : Configurer une adresse d'enregistrement fixe

Les nœuds d'agents ont besoin d'une URL pour s'enregistrer. Il peut s'agir de l'adresse IP ou du nom d'hôte de n'importe quel nœud de serveur, mais dans de nombreux cas, ces adresses peuvent changer au fil du temps. Par exemple, si vous exécutez votre cluster dans un nuage qui prend en charge les groupes de mise à l'échelle, des nœuds peuvent être créés et détruits au fil du temps, et changer d'adresse IP par rapport à l'ensemble initial de nœuds de serveur. Il est préférable de disposer d'un point final stable devant les nœuds de serveur, qui ne changera pas au fil du temps. Ce point d'accès peut être mis en place en utilisant un certain nombre d'approches, comme par exemple :

* Un équilibreur de charge de couche 4 (TCP)
* DNS à la ronde
* Adresses IP virtuelles ou élastiques

Voir xref:datastore/cluster-loadbalancer.adoc[Cluster Loadbalancer] pour des exemples de configuration.

Ce point d'accès peut également être utilisé pour accéder à l'API de Kubernetes. Vous pouvez donc, par exemple, modifier votre fichier https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[] kubeconfig pour qu'il pointe vers lui au lieu d'un nœud spécifique.

Pour éviter les erreurs de certificat dans une telle configuration, vous devez configurer le serveur avec l'option `+--tls-san=YOUR_IP_OR_HOSTNAME_HERE+`. Cette option ajoute un nom d'hôte ou une adresse IP supplémentaire en tant que nom alternatif du sujet dans la certification TLS. Elle peut être spécifiée plusieurs fois si vous souhaitez accéder à la fois par l'adresse IP et le nom d'hôte.

=== 5. En option : Rejoindre des nœuds d'agents

Les nœuds de serveur K3s étant planifiables par défaut, les nœuds d'agent ne sont pas nécessaires pour un cluster K3s HA. Toutefois, vous pouvez souhaiter disposer de nœuds d'agents dédiés pour exécuter vos applications et services.

La jonction de nœuds d'agent dans un cluster HA est identique à la jonction de nœuds d'agent dans un cluster à serveur unique. Il vous suffit de spécifier l'URL à laquelle l'agent doit s'enregistrer (soit l'une des IP du serveur, soit une adresse d'enregistrement fixe) et le jeton qu'il doit utiliser.

[,bash]
----
K3S_TOKEN=SECRET k3s agent --server https://server-or-fixed-registration-address:6443
----
