include::partial$variables.adoc[]
= Redacción de políticas {project-name} 
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Desarrolle políticas de controlador de admisión mediante la exposición de funcionalidades bien definidas a través de una API específica utilizando cualquier lenguaje de programación compatible.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies"]
:sidebar_label: Políticas de redacción
:current-version: {page-origin-branch}

Esta sección presenta las políticas de {project-name} utilizando analogías informáticas tradicionales.

Una política {short-project-name} es como un programa que hace un solo trabajo.
Recibe datos de entrada, realiza un cálculo con esos datos y devuelve un resultado.

Los datos de entrada son las solicitudes de admisión de Kubernetes.
El resultado del cálculo es una respuesta de validación, que indica a Kubernetes si debe aceptar, rechazar o mutar los datos de entrada, la solicitud de admisión.

El componente https://github.com/kubewarden/policy-server[policy-server]de {short-project-name} realiza estas operaciones.

El servidor de políticas no incluye ninguna capacidad de procesamiento de datos.
Se añaden capacidades de procesamiento en tiempo de ejecución con complementos.
Estos complementos son las pólizas {short-project-name}.

Así, una política {short-project-name} es como unhttps://en.wikipedia.org/wiki/Plug-in_%28computing%29[complemento tradicional]del programa "servidor de políticas".

Recapitulemos:

* {short-project-name} las políticas son complementos que exponen un conjunto de funcionalidades bien definidas (validar un objeto de solicitud de Kubernetes, validar la configuración de políticas proporcionada por el usuario y otras funciones) mediante una API bien definida
* El servidor de políticas es el programa "principal" que carga los plug-ins (también conocidos como políticas) y utiliza sus funcionalidades expuestas para aceptar, rechazar o modificar las solicitudes de Kubernetes.

Escribir políticas {short-project-name} consiste en escribir la lógica de negocio de validación y luego exponerla a través de una API bien definida.

== Requisitos del lenguaje de programación

Las directivas {short-project-name} se suministran como binarioshttps://webassembly.org/[WebAssembly].

Los autores de políticas pueden escribirlas utilizando cualquier lenguaje de programación que admita WebAssembly como objetivo de compilación.
La lista de lenguajes soportados está en constante evolución, https://github.com/appcypher/awesome-wasm-langs[esta página] proporciona una buena visión general del panorama WebAssembly.

Actualmente, WebAssembly no dispone de una forma oficial de compartir tipos de datos complejos entre el host y un invitado WebAssembly.
Para superar esta limitación, las políticas de {short-project-name} utilizan el proyecto https://github.com/wapc[waPC], que proporciona un canal de comunicación bidireccional.

Por lo tanto, el lenguaje de programación que elijas debe disponer de un SDK para invitados waPC.
Si no es así, no dude en ponerse en contacto con nosotros.
El equipo del proyecto puede ayudarle a superar esta limitación.
