include::partial$variables.adoc[]
= Metadatos políticos
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure los metadatos de la política en el archivo metadata.yaml para definir la configuración de la política, la información del autor y los permisos de los recursos.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "policy-metadata"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes policy development", "policy metadata"]
:current-version: {page-origin-branch}

El archivo de metadatos de {project-name}, `+metadata.yaml+`, es un archivo de configuración que contiene información y ajustes importantes relacionados con las políticas utilizadas en {short-project-name}.
Esta documentación es un resumen de la finalidad y el uso del archivo de metadatos.

El archivo de la política `+metadata.yaml+` contiene los valores predeterminados de la política, así como metadatos como el autor y la descripción, establecidos por el autor de la política.
El comando `+kwctl annotate+` utiliza el archivo para anotar el archivo `+.wasm+` que contiene la política.
Por lo tanto, toda la información pertinente necesaria para ejecutar la política está disponible.
Encontrará más información sobre cómo anotar la política en la guíaxref:../../explanations/distributing-policies.adoc[Distribuir políticas].

Cuando los usuarios de una política desean utilizarla, generan un manifiesto YAML utilizando `+kwctl scaffold+`.
Este comando lee los metadatos de política incrustados en el módulo Wasm enviado, realiza comprobaciones y devuelve un manifiesto YAML que el autor puede utilizar tal cual o modificar.

Como autor de la política, puede adaptar el archivo `+metadata.yaml+` proporcionado durante el andamiaje de su política.

Véase el siguiente ejemplo de `+metadata.yaml+`:

[subs="+attributes",yaml]
----
rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations: ["CREATE"]
mutating: false
contextAwareResources: []
executionMode: kubewarden-wapc
policyType: kubernetes
backgroundAudit: true
annotations:
  # kubewarden specific:
  io.kubewarden.policy.title: My policy
  io.kubewarden.policy.version: 0.1.0 # should match the OCI tag
  io.kubewarden.policy.description: Short description
  io.kubewarden.policy.author: myself
  io.kubewarden.policy.url: https://github.com/yourorg/my-policy
  io.kubewarden.policy.source: https://github.com/yourorg/my-policy
  io.kubewarden.policy.license: Apache-2.0
  # The next two annotations are used in the policy report generated by the
  # Audit scanner. Severity indicates policy check result criticality and
  # Category indicates policy category. See more here at docs.kubewarden.io
  io.kubewarden.policy.severity: medium
  io.kubewarden.policy.category: Resource validation
  # artifacthub specific: (optional, to release in Artifact Hub)
  io.kubewarden.policy.ociUrl: ghcr.io/myorg/my-policy
  io.artifacthub.displayName: Policy Name
  io.artifacthub.resources: Pod
  io.artifacthub.keywords: pod, cool policy, kubewarden
----

== Activación de las comprobaciones de auditoría de antecedentes

El archivo de metadatos incluye un indicador, `+backgroundAudit+`, que activa las comprobaciones de auditoría en segundo plano para una política específica.
Por defecto, este indicador está en `+true+`.

Hay pólizas que, por su funcionamiento o por el tipo de eventos a los que se refieren, deben tener este campo configurado en `+false+`.
Puede encontrar más información en laxref:explanations/audit-scanner/limitations.adoc[documentación del escáner de] auditoría, en la sección de limitaciones.

== Definición de los recursos de Kubernetes a los que pueden acceder las políticas

Dentro del archivo de metadatos, utilizando el campo `+contextAwareResources+`, los usuarios pueden definir a qué recursos de Kubernetes puede acceder la política.
Por ejemplo, si la política necesita acceder al recurso `+Namespace+`.
El autor de la política puede definir la `+contextAwareResources+` como:

[subs="+attributes",yaml]
----
[...]
contextAwareResources:
  - apiVersion: v1 kind: Namespace
[...]
----

== Especificar políticas como mutantes o no mutantes

El archivo de metadatos tiene un indicador, `+mutating+`, que permite a los usuarios configurar una política como mutante o no mutante.
Una política mutante modifica las solicitudes entrantes o los recursos gestionados.
Una política no mutante observa y aplica las restricciones sin realizar ningún cambio.
Esta distinción es crucial para determinar cómo interactúan las políticas con los recursos de Kubernetes y su impacto en el clúster.

== Especifique el tipo de política como Kubernetes o Raw

El archivo de metadatos tiene un indicador, `+policyType+`, que permite a los usuarios marcar una política como `+kubernetes+` o `+raw+`.
Una política de Kubernetes es una política que valida los recursos de Kubernetes.
Una política Raw es una política que valida documentos JSON arbitrarios.
Por defecto, si el usuario no lo especifica, este campo se establece en `+kubernetes+` al anotar una política.
Si desea más información, consulte la sección xref:../../howtos/raw-policies.adoc[Políticas en bruto].

== Definición de objetivos de tipo de recurso

El archivo de metadatos ofrece a los usuarios la posibilidad de definir las reglas dentro del campo `+rules+`, que determina los tipos de recursos a los que se aplica la política.
Esta función permite a los usuarios ejercer un control preciso sobre la aplicación de las políticas, garantizando que éstas sólo se apliquen a los tipos de recursos previstos.
Con este control tan preciso, los usuarios pueden garantizar que las políticas se orientan con precisión, se ajustan a sus requisitos específicos y evitan la aplicación involuntaria de políticas a tipos de recursos no relacionados.
