= Glosario
:revdate: 2025-11-14
:page-revdate: {revdate}

== Índice

[cols=14*]
|===
| xref:./glossary.adoc#_a[A]
| xref:./glossary.adoc#_b[B]
| xref:./glossary.adoc#_c[C]
| xref:./glossary.adoc#_f[F]
| xref:./glossary.adoc#_i[I]
| xref:./glossary.adoc#_k[K]
| xref:./glossary.adoc#_m[M]
| xref:./glossary.adoc#_n[N]
| xref:./glossary.adoc#_o[O]
| xref:./glossary.adoc#_p[P]
| xref:./glossary.adoc#_r[R]
| xref:./glossary.adoc#_s[S]
| xref:./glossary.adoc#_t[T]
| xref:./glossary.adoc#_w[W]
|===

== A

=== Complementos

Los servicios van más allá de los componentes fundamentales necesarios para desplegar un clúster conforme con Kubernetes y se clasifican en dos tipos:

* *Complementos básicos*: Complementos necesarios para desplegar un clúster compatible con Kubernetes: DNS, kube-proxy, CNI.
* *Complementos adicionales*: Complementos que no son necesarios para un clúster conforme con Kubernetes (por ejemplo, métricas/Heapster, Dashboard).

=== Entorno ventilado

Configuración y ejecución de clústeres Kubernetes sin acceso directo a Internet.

== B

=== Bootstrap

El proceso de convertir un servidor en un nodo Kubernetes. Esto puede implicar la recopilación de datos para proporcionar al crear el servidor que respalda la Máquina, así como la configuración en tiempo de ejecución del software que se ejecuta en ese servidor.

=== Agrupación Bootstrap

Un clúster temporal que se utiliza para aprovisionar un clúster de Target Management.

=== Proveedor de Bootstrap

Se refiere a un <<_provider,proveedor>> que implementa una solución para el proceso de <<_bootstrap,arranque>>.

== C

=== CAPI

API del clúster central

=== CAPA

Proveedor de API de clústeres AWS

=== CAPD

Proveedor de API de clúster Docker

=== CAPG

Cluster API Google Cloud Provider

=== CAPIO

Operador API de clúster

=== CAPRKE2

Cluster API Provider RKE2. Para obtener información detallada sobre CAPRKE2, consulte su documentación https://caprke2.docs.rancher.com[aquí].

=== CAPV

Proveedor de API de clúster vSphere

=== CAPZ

Proveedor de API de clúster Azure

=== Proveedor CAPI

Una API pública que facilita el aprovisionamiento y las operaciones sobre los recursos <<_cluster_api_operator,CAPI Operator>> y <<_cluster_api,Cluster API>>.

=== Grupo de niños

Término comúnmente utilizado indistintamente con el <<_workload_cluster,clúster de carga de trabajo>>.

=== Grupo

Un despliegue completo de Kubernetes. Véase Clúster de gestión y Clúster de carga de trabajo.

=== ClusterClass

Una colección de plantillas que definen una topología (plano de control y trabajadores) que se utilizará para reconciliar continuamente uno o más Clusters.
Véase xref:../user/clusterclass.adoc[ClusterClass]

=== API de clúster

O *proyecto Cluster API*

El Cluster API es un subproyecto del SIG-cluster-lifecycle. También se utiliza para referirse a los componentes de software, las API y la comunidad que los produce.

Ver <<_core_provider,proveedor principal>>

=== Operador API de clúster

O *proyecto Operador de API de clúster*

El Cluster API Operator es un subproyecto del SIG-cluster-lifecycle. Está diseñado para permitir a los administradores de clústeres gestionar el ciclo de vida de los proveedores de API de clúster dentro de un clúster de gestión mediante un enfoque declarativo.

=== Proveedor de API de clúster RKE2

Cluster API <<_caprke2,Provider RKE2>> es una combinación de dos tipos de proveedores: un Cluster API Control Plane Provider para aprovisionar nodos del plano de control de Kubernetes y un Cluster API Bootstrap Provider para arrancar Kubernetes en una máquina en la que se utiliza <<_rke2,RKE2>> como distro de Kubernetes.

=== Plano de control

Conjunto de servicios Kubernetes que forman la base de un clúster. Véase también https://kubernetes.io/docs/concepts/#_kubernetes-control-plane Existen dos variantes:

* *Autoabastecimiento*: Un plano de control de Kubernetes formado por pods o máquinas gestionadas en su totalidad por una única implementación de Cluster API.
* *Externo* o *gestionado*: Un plano de control ofrecido y controlado por algún sistema distinto de la API de clúster (por ejemplo, GKE, AKS, EKS, IKS).

=== Proveedor del plano de control

Se refiere a un <<_provider,proveedor>> que implementa una solución para la gestión de un <<_control_plane,plano de control>> de Kubernetes.

Véase <<_caprke2,CAPRRKE2>>, <<_kcp,KCP>>.

=== Proveedor principal

Se refiere a un <<_provider,proveedor>> que implementa los controladores del núcleo de la Cluster API; si se tiene en cuenta que el primer proyecto que debe desplegarse en un Cluster de gestión es la propia Cluster API, debería quedar claro por qué el proyecto Cluster API también se denomina proveedor del núcleo.

Véase <<_cluster_api,CAPI>>.

== F

=== Flota

ifeval::["{build-type}" == "product"]
Un motor de gestión y despliegue de contenedores diseñado para ofrecer a los usuarios un mayor control sobre el clúster local y una supervisión constante a través de GitOps. Eche un vistazo a https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/index.html/[la documentación de] para saber más sobre Fleet.
endif::[]
ifeval::["{build-type}" == "community"]
Un motor de gestión y despliegue de contenedores diseñado para ofrecer a los usuarios un mayor control sobre el clúster local y una supervisión constante a través de GitOps. Eche un vistazo a https://fleet.rancher.io/[la documentación de] para saber más sobre Fleet.
endif::[]

== I

=== Proveedor de infraestructuras

Se refiere a un <<_provider,proveedor>> que implementa el aprovisionamiento de infraestructura/recursos computacionales requeridos por el Cluster o por las Máquinas (por ejemplo, VMs, redes, etc.).
Los proveedores de infraestructura de nube incluyen AWS, Azure o Google; mientras que VMware, MAAS o metal3.io pueden definirse como proveedores de metal desnudo.

=== Proveedor de IPAM

Se refiere a un <<_provider,proveedor>> que permite Cluster API para interactuar con soluciones IPAM.
La interacción del proveedor IPAM con la API Cluster se basa en los tipos de API `+IPAddressClaim+` y `+IPAddress+`.

== K

=== Kubernetes-conformant

O *compatible con Kubernetes*

Un clúster que supera las pruebas de conformidad de Kubernetes.

=== Kubernetes Operator

Un Operador Kubernetes es un método de empaquetado, despliegue y gestión de una aplicación Kubernetes. Consulte también https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ para más información.

=== k/k

Hace referencia al https://github.com/kubernetes/kubernetes[repositorio git principal de Kubernetes de] o al proyecto principal de Kubernetes.

=== KCP

Proveedor de plano de control Kubeadm

== M

=== Máquina

O *Recurso Máquina*

El recurso personalizado para Kubernetes que representa un componente de infraestructura que aloja un nodo de Kubernetes.

=== Gestionar un clúster

Realiza operaciones de creación, escalado, actualización o destrucción del clúster.

=== Kubernetes gestionados

Kubernetes gestionado hace referencia a cualquier abstracción de aprovisionamiento y mantenimiento de clústeres Kubernetes, normalmente expuesta como API, que esté disponible de forma nativa en un proveedor de nube. Por ejemplo: https://aws.amazon.com/eks/[EKS], https://www.oracle.com/cloud/cloud-native/container-engine-kubernetes/[OKE], https://azure.microsoft.com/en-us/products/kubernetes-service[IBM Cloud Kubernetes Service] AKS, https://cloud.google.com/kubernetes-engine[DOKS] GKE, https://www.ibm.com/cloud/kubernetes-service[], https://www.digitalocean.com/products/kubernetes[], y muchos más en todo el ecosistema Kubernetes Cloud Native.

=== Topología gestionada

Ver <<_topology,Topología>>

=== Grupo de gestión

El clúster donde se ejecutan uno o más Proveedores de Infraestructura, y donde se almacenan los recursos (por ejemplo, Máquinas). Normalmente se utiliza cuando se aprovisionan varios clústeres de carga de trabajo.

== N

=== Grupos de nodos

Un pool de nodos es un grupo de nodos dentro de un cluster que tienen todos la misma configuración.

== O

=== Sistema operativo

O *SO*

Una combinación genéricamente entendida de un núcleo y una interfaz de espacio de usuario a nivel de sistema, como Linux o Windows, en contraposición a una distribución concreta.

== P

=== Pivot

Pivot es un proceso para mover los componentes del proveedor y los recursos de cluster-api declarados de un cluster de Gestión de Origen a un cluster de Gestión de Destino.

El proceso de pivoteo también se utiliza para eliminar un clúster de gestión y también podría utilizarse durante una actualización del clúster de gestión.

=== Proveedor

O *proveedor de API de clúster*

Este término se utilizó originalmente como abreviatura de <<_infrastructure_provider,proveedor de Infraestructura>>, pero actualmente se utiliza para referirse a cualquier proyecto que pueda ser desplegado y proporcione funcionalidad al Cluster de gestión de APIs de Cluster.

Véase <<_bootstrap_provider,Proveedor de arranque>>, <<_control_plane_provider,Proveedor de plano de control>>, <<_core_provider,Proveedor de núcleo>>,<<_infrastructure_provider,Proveedor de infraestructura>>, <<_ipam_provider,Proveedor de IPAM>>, <<_runtime_extension_provider,Proveedor de extensión en tiempo de ejecución>>.

=== Componentes del proveedor

Se refiere al artefacto YAML publicado como parte del proceso de lanzamiento de <<_provider,proveedores>>; normalmente incluye definiciones de recursos personalizadas (CRD), despliegues (para ejecutar el gestor de controladores), RBAC, etc.

En algunos casos, se utiliza la misma expresión para referirse a las instancias de los componentes anteriores desplegadas en un clúster de gestión.

Ver <<_provider_repository,Repositorio de proveedores>>

=== Repositorio de proveedores

Se refiere a la ubicación donde se aloja el YAML de <<_provider_components,los>> componentes del proveedor; normalmente un repositorio de proveedores aloja muchas versiones de componentes de proveedores, una por cada versión publicada.

== R

=== Ranchero

 de código abierto https://www.rancher.com/[Plataforma] diseñada para simplificar la implantación y gestión de clústeres Kubernetes.

=== Agente Rancher Cluster

Un componente desplegado por Rancher en cada clúster Kubernetes que gestiona. Su función principal es establecer un canal de comunicación seguro entre el servidor Rancher y el clúster Kubernetes, permitiendo a Rancher gestionar e interactuar con el clúster.

=== Administrador de ranchos

El Rancher Manager (o Rancher Server) es donde se alojan la interfaz de usuario y la API de Rancher, y se comunica con los clusters gestionados a través de componentes como el <<_rancher_cluster_agent,Rancher Cluster Agent>>. Permite a los usuarios gestionar sus clústeres Kubernetes, aplicaciones y recursos específicos de Rancher como Catálogos, Usuarios, Roles Globales y más.

=== RKE2

ifeval::["{build-type}" == "product"]
La distribución de Kubernetes de nueva generación y totalmente conforme de Rancher que se centra en la seguridad y el cumplimiento dentro de EE. UU. Sector de la Administración Federal. Consulte https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html[la documentación de] para más detalles.
endif::[]
ifeval::["{build-type}" == "community"]
La distribución de Kubernetes de nueva generación y totalmente conforme de Rancher que se centra en la seguridad y el cumplimiento dentro de EE. UU. Sector de la Administración Federal. Consulte https://docs.rke2.io/[la documentación de] para más detalles.
endif::[]

=== Extensión de tiempo de ejecución

Un componente externo que forma parte de un sistema construido sobre la API de Cluster que puede gestionar peticiones de un Runtime Hook específico.

=== Proveedor de extensiones en tiempo de ejecución

Se refiere a un <<_provider,proveedor>> que implementa una o más <<_runtime_extension,extensiones en tiempo de ejecución>>.

== S

=== Escala

A menos que se especifique lo contrario, se refiere a la escala horizontal.

=== Plano de control apilado

Un nodo de plano de control en el que etcd está colocado con el servidor API de Kubernetes y se ejecuta como un pod estático.

=== Servidor

La infraestructura que respalda un <<_machine,recurso de máquina>>, normalmente una instancia de nube, una máquina virtual o un host físico.

=== {product_name}

Un <<_kubernetes_operator,operador de Kubernetes>> que proporciona integración entre Rancher Manager y Cluster API (CAPI) con el objetivo de llevar el soporte completo de CAPI a Rancher.

== T

=== Topología

Campo de la especificación del objeto Cluster que permite definir y gestionar la forma del plano de control del Cluster y las máquinas trabajadoras desde un único punto de control. La topología del Cluster se basa en una <<_clusterclass,ClusterClass>>.
A veces también se denomina topología gestionada.

Véase <<_clusterclass,ClusterClass>>

ifeval::["{build-type}" == "product"]
=== Tortugas

Se refiere a <<_suse_rancher_prime_cluster_api,{product_name}>>
endif::[]

ifeval::["{build-type}" == "community"]
=== Tortugas

Se refiere a <<_rancher_turtles,{product_name}>>
endif::[]

== W

=== Clúster de carga de trabajo

Un clúster creado por un controlador ClusterAPI, que _no_ es un clúster de arranque, y está destinado a ser utilizado por los usuarios finales, en contraposición a las herramientas CAPI.

=== WorkerClass

Una colección de plantillas que definen un conjunto de nodos trabajadores en el clúster. Una ClusterClass contiene cero o más definiciones de WorkerClass.

Véase <<_clusterclass,ClusterClass>>
