include::../common/generic-attributes.adoc[]

[#pr-helm-chart-override]
== Substituindo o grûÀfico {productname} {helm}
:revdate: 2025-10-15
:page-revdate: {revdate}

O grûÀfico {productname} ({productnameshort}) {helm} ûˋ entregue com valores padrûÈo.
Vocûˆ pode ajustar a instalaûÏûÈo do grûÀfico {helm} de uma das seguintes maneiras:

* Anexe parûÂmetros especûÙficos û s flags `+--set+` na linha de comando `+helm install+`, por exemplo:
[source]
$ helm install <RELEASE_NAME> \
oci://registry.suse.com/private-registry/private-registry-helm \
--namespace <PRIVATE_REGISTRY_NAMESPACE> \
--set harborAdminPassword=<MY_PASSWORD> \
--set externalURL=https://<PRIVATE_REGISTRY_FQDN> \
--set expose.ingress.hosts.core=<PRIVATE_REGISTRY_FQDN>
* Create a {suse} custom `+suse_registry_override.yaml+` file and pass it to the `+--f+` flag, for example:
[source]
  $ helm install <RELEASE_NAME> \
  oci://registry.suse.com/private-registry/private-registry-helm \
  --namespace <PRIVATE_REGISTRY_NAMESPACE>
  -f suse_registry_override.yaml

[#pr-helm-chart-override-examples]
=== Exemplos de arquivos de substituiûÏûÈo {sregistry} {helm}
.ImplantaûÏûÈo mûÙnima com {ingress}
[example]
----
expose:
  type: ingress //<1>
  ingress:
    hosts:
      core: <PRIVATE_REGISTRY_FQDN> //<2>

externalURL: https://<PRIVATE_REGISTRY_FQDN> //<3>

harborAdminPassword: "<MY_PASSWORD>" //<4>

database:
  internal:
    password: "<MY_PASSWORD_POSTGRESQL>"

redis:
  internal:
   password: "<MY_PASSWORD_REDIS>"
----
[callouts]
<1> Como {sregistry} ûˋ exposto. Pode ser `+ingress+`, `+loadBalancer+`, `+nodePort+` ou `+clusterIPhis+`. O padrûÈo ûˋ `+ingress+`.
<2> Nome de host para a configuraûÏûÈo de rede interna do {kube}.
<3> URL onde o aplicativo {sregistry} ûˋ executado. û usado para gerar links na interface do usuûÀrio, redirecionamentos e tambûˋm para respostas da API.
<4> A senha do administrador para o aplicativo.

.ImplantaûÏûÈo tûÙpica com `+loadBalancer+`
[example]
----
expose:
  type: loadBalancer //<1>
  tls:
    enabled: true
    certSource: secret //<2>
    secret:
      secretName: <SECRET_NAME>

    auto:
      commonName: <PRIVATE_REGISTRY_FQDN> //<3>

externalURL: https://<PRIVATE_REGISTRY_FQDN> //<4>

harborAdminPassword: "<MY_PASSWORD>" //<5>

database:
  internal:
    password: "<MY_PASSWORD_POSTGRESQL>"

redis:
  internal:
   password: "<MY_PASSWORD_REDIS>"
----
[callouts]
<1> Como {sregistry} ûˋ exposto. Pode ser `+ingress+`, `+loadBalancer+`, `+nodePort+` ou `+clusterIP+`. O padrûÈo ûˋ `+ingress+`.
<2> Pode ser `+auto+`, `+secret+` ou `+none+`. Dependendo da opûÏûÈo, pode ser necessûÀrio incluir valores adicionais.
<3> Ao usar a criptografia TLS, este campo deve corresponder ao valor `+externalURL+`.
<4> URL onde o aplicativo {sregistry} ûˋ executado. û usado para gerar links na interface do usuûÀrio, redirecionamentos e tambûˋm para respostas da API.
<5> A senha do administrador para o aplicativo.

[#pr-helm-chart-override-parameters]
=== Substituindo os parûÂmetros e valores do grûÀfico {helm}

As tabelas a seguir listam todos os parûÂmetros com descriûÏûçes que vocûˆ pode usar para substituir os valores de instalaûÏûÈo padrûÈo.

.ParûÂmetros globais
`+global.imageRegistry+`:: Define uma substituiûÏûÈo global para o registro de imagens do contûˆiner usado para todas as imagens.
`+global.imagePullSecrets+`:: Define segredos globais de pull para acessar o registro de imagens do contûˆiner.

.ParûÂmetros comuns
`+harborAdminPassword+`:: Define a senha inicial para o administrador {harbor}. Altere-a pelo portal apû°s a implantaûÏûÈo. O padrûÈo ûˋ `+Harbor12345+`.
`+externalURL+`:: Especifica a URL externa para o serviûÏo `+harbor-core+`. O padrûÈo ûˋ `+\https://core.harbor.domain+`.
`+existingSecretAdminPasswordKey+`:: Define o nome da chave no segredo que contûˋm a senha do administrador {harbor}. O padrûÈo ûˋ `+HARBOR_ADMIN_PASSWORD+`.
`+imagePullSecrets+`:: Define os nomes `+imagePullSecrets+` para todas as implantaûÏûçes.
`+updateStrategy.type+`:: Define a estratûˋgia de atualizaûÏûÈo para implantaûÏûçes com volumes persistentes. Aceita `+RollingUpdate+` ou `+Recreate+`. Use `+Recreate+` quando RWM para volumes nûÈo for suportado. O padrûÈo ûˋ `+RollingUpdate+`.
`+logLevel+`:: Define o nûÙvel de log para os serviûÏos {harbor}. Aceita `+fatal+`, `+error+`, `+warn+`, `+info+`, `+debug+` ou `+trace+`. O padrûÈo ûˋ `+debug+`.
`+enableMigratehelmHook+`:: Executa a tarefa de migraûÏûÈo do banco de dados via o gancho {helm}. Quando `+true+`, separa a tarefa de migraûÏûÈo de `+harbor-core+`. O padrûÈo ûˋ `+false+`.
`+caSecretName+`:: Especifica o nome do segredo que contûˋm a chave `+ca.crt+`.

.ParûÂmetros de proxy
`+proxy.httpProxy+`:: Especifica a URL do servidor proxy HTTP. O padrûÈo ûˋ `+""+`.
`+proxy.httpsProxy+`:: Especifica a URL do servidor proxy HTTPS. O padrûÈo ûˋ `+""+`.
`+proxy.noProxy+`:: Define URLs que ignoram a configuraûÏûÈo do proxy. O padrûÈo ûˋ `+127.0.0.1,localhost,.local,.internal+`.
`+proxy.components+`:: Define componentes que utilizam a configuraûÏûÈo do proxy. O padrûÈo ûˋ `+["core","jobservice","trivy"]+`.

.ParûÂmetros de exposiûÏûÈo
`+expose.type+`:: Especifica o tipo de exposiûÏûÈo do serviûÏo: `+ingress+`, `+clusterIP+`, `+nodePort+` ou `+loadBalancer+`. O padrûÈo ûˋ `+ingress+`.
`+expose.tls.enabled+`:: Habilita TLS. O padrûÈo ûˋ `+true+`.
`+expose.tls.certSource+`:: Define a fonte do certificado TLS como `+auto+`, `+secret+` ou `+none+`. O padrûÈo ûˋ `+auto+`.
`+expose.tls.auto.commonName+`:: Define o nome comum do certificado quando o tipo nûÈo ûˋ `+ingress+`.
`+expose.tls.secret.secretName+`:: Especifica o nome do segredo que contûˋm `+tls.crt+` (certificado) e `+tls.key+` (chave privada).
`+expose.ingress.hosts.core+`:: Define o host do serviûÏo kernel {harbor} na regra {ingress}. O padrûÈo ûˋ `+core.harbor.domain+`.
`+expose.ingress.controller+`:: Define o tipo de controlador {ingress}. Suporta `+default+`, `+gce+`, `+alb+`, `+f5-bigip+` e `+ncp+`. O padrûÈo ûˋ `+default+`.
`+expose.ingress.kubeVersionOverride+`:: Substitui a versûÈo {kube} para a template {ingress}.
`+expose.ingress.annotations+`:: Define as anotaûÏûçes {ingress}.
`+expose.ingress.labels+`:: Define os rû°tulos especûÙficos de {ingress}. O padrûÈo ûˋ `+{}+`.
`+expose.clusterIP.name+`:: Define o nome do serviûÏo ClusterIP. O padrûÈo ûˋ `+harbor+`.
`+expose.clusterIP.annotations+`:: Define as anotaûÏûçes do serviûÏo ClusterIP. O padrûÈo ûˋ `+{}+`.
`+expose.clusterIP.ports.httpPort+`:: Define a porta do serviûÏo HTTP. O padrûÈo ûˋ `+80+`.
`+expose.clusterIP.ports.httpsPort+`:: Define a porta do serviûÏo HTTPS. O padrûÈo ûˋ `+443+`.
`+expose.clusterIP.labels+`:: Define os rû°tulos especûÙficos do ClusterIP. O padrûÈo ûˋ `+{}+`.
`+expose.nodePort.name+`:: Define o nome do serviûÏo NodePort. O padrûÈo ûˋ `+harbor+`.
`+expose.nodePort.ports.http.port+`:: Define a porta do serviûÏo HTTP. O padrûÈo ûˋ `+80+`.
`+expose.nodePort.ports.http.nodePort+`:: Define a porta do nû° HTTP. O padrûÈo ûˋ `+30002+`.
`+expose.nodePort.ports.https.port+`:: Define a porta do serviûÏo HTTPS. O padrûÈo ûˋ `+443+`.
`+expose.nodePort.ports.https.nodePort+`:: Define a porta do nû° HTTPS. O padrûÈo ûˋ `+30003+`.
`+expose.nodePort.annotations+`:: Define as anotaûÏûçes do NodePort.
`+expose.nodePort.labels+`:: Define os rû°tulos especûÙficos do NodePort. O padrûÈo ûˋ `+{}+`.
`+expose.loadBalancer.name+`:: Define o nome do serviûÏo. O padrûÈo ûˋ `+harbor+`.
`+expose.loadBalancer.IP+`:: Define o IP do loadBalancer quando a atribuiûÏûÈo de IP ûˋ suportada. O padrûÈo ûˋ `+""+`.
`+expose.loadBalancer.ports.httpPort+`:: Define a porta do serviûÏo HTTP. O padrûÈo ûˋ `+80+`.
`+expose.loadBalancer.ports.httpsPort+`:: Define a porta do serviûÏo HTTPS. O padrûÈo ûˋ `+30002+`.
`+expose.loadBalancer.annotations+`:: Define as anotaûÏûçes do serviûÏo loadBalancer. O padrûÈo ûˋ `+{}+`.
`+expose.loadBalancer.labels+`:: Define os rû°tulos especûÙficos do loadBalancer. O padrûÈo ûˋ `+{}+`.
`+expose.loadBalancer.sourceRanges+`:: Especifica intervalos de endereûÏos IP para loadBalancerSourceRanges. O padrûÈo ûˋ `+[]+`.

[#helm-persistence-parameters]
.ParûÂmetros de persistûˆncia
`+persistence.enabled+`:: Habilita ou desabilita a persistûˆncia de dados. O padrûÈo ûˋ `+true+`.
`+persistence.resourcePolicy+`:: `+keep+` impede a remoûÏûÈo de PVCs durante uma operaûÏûÈo de exclusûÈo {helm}. Valor vazio exclui PVCs apû°s a exclusûÈo do grûÀfico. O padrûÈo ûˋ `+keep+`.
`+persistence.persistentVolumeClaim.registry.existingClaim+`:: O PVC existente que deve ser criado manualmente antes da vinculaûÏûÈo. Requer uma especificaûÏûÈo de subPath se o PVC for compartilhado com outros componentes.
`+persistence.persistentVolumeClaim.registry.storageClass+`:: O `+storageClass+` que provisiona o volume.
`+persistence.persistentVolumeClaim.registry.subPath+`:: O subpath no volume.
`+persistence.persistentVolumeClaim.registry.accessMode+`:: O modo de acesso do volume. O padrûÈo ûˋ `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.registry.size+`:: O tamanho do volume. O padrûÈo ûˋ `+5Gi+`.
`+persistence.persistentVolumeClaim.registry.annotations+`:: As anotaûÏûçes do volume.
`+persistence.persistentVolumeClaim.jobservice.jobLog.existingClaim+`:: O PVC existente que deve ser criado manualmente antes da vinculaûÏûÈo. Requer uma especificaûÏûÈo de subPath se o PVC for compartilhado com outros componentes.
`+persistence.persistentVolumeClaim.jobservice.jobLog.storageClass+`:: O `+storageClass+` que provisiona o volume.
`+persistence.persistentVolumeClaim.jobservice.jobLog.subPath+`:: O subpath no volume.
`+persistence.persistentVolumeClaim.jobservice.jobLog.accessMode+`:: O modo de acesso do volume. O padrûÈo ûˋ `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.jobservice.jobLog.size+`:: O tamanho do volume. O padrûÈo ûˋ `+1Gi+`.
`+persistence.persistentVolumeClaim.jobservice.jobLog.annotations+`:: As anotaûÏûçes do volume.
`+persistence.persistentVolumeClaim.database.existingClaim+`:: O PVC existente que deve ser criado manualmente antes da vinculaûÏûÈo. Requer uma especificaûÏûÈo de subPath se o PVC for compartilhado com outros componentes.
`+persistence.persistentVolumeClaim.database.storageClass+`:: O `+storageClass+` que provisiona o volume.
`+persistence.persistentVolumeClaim.database.subPath+`:: O subpath no volume. Ignorado quando um banco de dados externo ûˋ utilizado.
`+persistence.persistentVolumeClaim.database.accessMode+`:: O modo de acesso do volume. Ignorado quando um banco de dados externo ûˋ utilizado. O padrûÈo ûˋ `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.database.size+`:: O tamanho do volume. Ignorado quando um banco de dados externo ûˋ utilizado. O padrûÈo ûˋ `+1Gi+`.
`+persistence.persistentVolumeClaim.database.annotations+`:: As anotaûÏûçes do volume.
`+persistence.persistentVolumeClaim.redis.existingClaim+`:: O PVC existente que deve ser criado manualmente antes da vinculaûÏûÈo. Requer uma especificaûÏûÈo de subPath se o PVC for compartilhado com outros componentes.
`+persistence.persistentVolumeClaim.redis.storageClass+`:: O `+storageClass+` que provisiona o volume. Usa a StorageClass padrûÈo se nûÈo for especificada.
`+persistence.persistentVolumeClaim.redis.subPath+`:: O subpath no volume. Ignorado quando um {valkey} externo ûˋ utilizado.
`+persistence.persistentVolumeClaim.redis.accessMode+`:: O modo de acesso do volume. Ignorado quando um {valkey} externo ûˋ utilizado. O padrûÈo ûˋ `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.redis.size+`:: O tamanho do volume. Ignorado quando um {valkey} externo ûˋ utilizado. O padrûÈo ûˋ `+1Gi+`.
`+persistence.persistentVolumeClaim.redis.annotations+`:: As anotaûÏûçes do volume.
`+persistence.persistentVolumeClaim.trivy.existingClaim+`:: O PVC existente que deve ser criado manualmente antes da vinculaûÏûÈo. Requer uma especificaûÏûÈo de subPath se o PVC for compartilhado com outros componentes.
`+persistence.persistentVolumeClaim.trivy.storageClass+`:: O `+storageClass+` que provisiona o volume. Usa a StorageClass padrûÈo se nûÈo for especificada.
`+persistence.persistentVolumeClaim.trivy.subPath+`:: O subpath no volume.
`+persistence.persistentVolumeClaim.trivy.accessMode+`:: O modo de acesso do volume. O padrûÈo ûˋ `+ReadWriteOnce+`.
`+persistence.persistentVolumeClaim.trivy.size+`:: O tamanho do volume. O padrûÈo ûˋ `+1Gi+`.
`+persistence.persistentVolumeClaim.trivy.annotations+`:: As anotaûÏûçes do volume.
`+persistence.imageChartStorage.disableredirect+`:: Controla a gestûÈo de redirecionamentos de back ends de conteû¤do. Defina como verdadeiro para desabilitar redirecionamentos para back ends nûÈo suportados. O padrûÈo ûˋ `+false+`.
`+persistence.imageChartStorage.caBundleSecretName+`:: O nome do segredo contendo o pacote CA para certificados de serviûÏo de armazenamento autoassinado.
`+persistence.imageChartStorage.type+`:: O tipo de armazenamento para imagens e grûÀficos: `+filesystem+`, `+azure+`, `+gcs+`, `+s3+`, `+swift+` ou `+oss+`. O padrûÈo ûˋ `+filesystem+`.
`+persistence.imageChartStorage.gcs.existingSecret+`:: O nome do segredo existente contendo a chave JSON da conta de serviûÏo GCS. A chave deve ser `+gcs-key.json+`. O padrûÈo ûˋ `+""+`.
`+persistence.imageChartStorage.gcs.useWorkloadIdentity+`:: Habilita o uso de identidade de carga de trabalho em um cluster GKE. O padrûÈo ûˋ `+false+`.

.ParûÂmetros {nginx}
[options="header"]
`+nginx.image.repository+`:: O repositû°rio de imagens para {nginx}. O padrûÈo ûˋ `+private-registry/harbor-nginx+`.
`+nginx.image.tag+`:: A tag da imagem para {nginx}.
`+nginx.replicas+`:: O nû¤mero de rûˋplicas a serem executadas. O padrûÈo ûˋ `+1+`.
`+nginx.revisionHistoryLimit+`:: O nû¤mero mûÀximo de revisûçes antigas de `+ReplicaSet+` a serem mantidas. O padrûÈo ûˋ `+10+`.
`+nginx.resources+`:: Os recursos de computaûÏûÈo alocados para o contûˆiner. O padrûÈo ûˋ `+undefined+`.
`+nginx.automountServiceAccountToken+`:: Controla a montagem automûÀtica do token da conta de serviûÏo. O padrûÈo ûˋ `+false+`.
`+nginx.nodeSelector+`:: Os rû°tulos do nû° usados para a atribuiûÏûÈo de pods. O padrûÈo ûˋ `+{}+`.
`+nginx.tolerations+`:: As tolerûÂncias de atribuiûÏûÈo de pods. O padrûÈo ûˋ `+[]+`.
`+nginx.affinity+`:: As regras de afinidade de nû° ou pod. O padrûÈo ûˋ `+{}+`.
`+nginx.topologySpreadConstraints+`:: As regras para espalhar pods por domûÙnios de falha, como regiûçes ou zonas de disponibilidade. O padrûÈo ûˋ `+[]+`.
`+nginx.podAnnotations+`:: As anotaûÏûçes adicionadas ao {nginx} pod. O padrûÈo ûˋ `+{}+`.


.ParûÂmetros do portal
`+portal.image.repository+`:: LocalizaûÏûÈo do repositû°rio para a imagem do portal. O padrûÈo ûˋ `+private-registry/harbor-portal+`.
`+portal.image.tag+`:: Tag para a imagem do portal. O padrûÈo ûˋ `+3.11+`.
`+portal.replicas+`:: Nû¤mero de rûˋplicas a serem criadas. O padrûÈo ûˋ `+1+`.
`+portal.revisionHistoryLimit+`:: Nû¤mero mûÀximo de revisûçes antigas de `+ReplicaSet+` a serem mantidas. O padrûÈo ûˋ `+10+`.
`+portal.resources+`:: Recursos alocados para o contûˆiner. O padrûÈo ûˋ `+undefined+`.
`+portal.automountServiceAccountToken+`:: Controla a montagem automûÀtica do token da conta de serviûÏo. O padrûÈo ûˋ `+false+`.
`+portal.nodeSelector+`:: Rû°tulos de nû° usados para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+{}+`.
`+portal.tolerations+`:: TolerûÂncias usadas para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+[]+`.
`+portal.affinity+`:: ConfiguraûÏûçes de afinidade de nû° e pod. O padrûÈo ûˋ `+{}+`.
`+portal.topologySpreadConstraints+`:: Define a distribuiûÏûÈo de pods entre domûÙnios de falha, como regiûçes ou zonas de disponibilidade. O padrûÈo ûˋ `+[]+`.
`+portal.podAnnotations+`:: AnotaûÏûçes adicionadas ao pod do portal. O padrûÈo ûˋ `+{}+`.
`+portal.serviceAnnotations+`:: AnotaûÏûçes adicionadas ao serviûÏo do portal. O padrûÈo ûˋ `+{}+`.
`+portal.priorityClassName+`:: Nome da classe de prioridade para execuûÏûÈo do pod.
`+portal.initContainers+`:: Contûˆineres init a serem executados antes que o contûˆiner do controlador inicie. O padrûÈo ûˋ `+[]+`.


.ParûÂmetros principais
`+core.image.repository+`:: O repositû°rio para a {harbor} imagem do kernel. O padrûÈo ûˋ `+private-registry/harbor-core+`.
`+core.image.tag+`:: A tag para a {harbor} imagem do kernel. O padrûÈo ûˋ `+2.11+`.
`+core.replicas+`:: O nû¤mero de rûˋplicas. O padrûÈo ûˋ `+1+`.
`+core.revisionHistoryLimit+`:: O limite de histû°rico de revisûçes. O padrûÈo ûˋ `+10+`.
`+core.startupProbe.initialDelaySeconds+`:: O atraso inicial em segundos para a verificaûÏûÈo de inicializaûÏûÈo. O padrûÈo ûˋ `+10+`.
`+core.resources+`:: Os recursos a serem alocados para o contûˆiner. O padrûÈo ûˋ `+undefined+`.
`+core.automountServiceAccountToken+`:: Monta o token da conta de serviûÏo. O padrûÈo ûˋ `+false+`.
`+core.nodeSelector+`:: Os rû°tulos de nû° para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+{}+`.
`+core.tolerations+`:: As tolerûÂncias para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+[]+`.
`+core.affinity+`:: As afinidades de nû° ou pod. O padrûÈo ûˋ `+{}+`.
`+core.topologySpreadConstraints+`:: As restriûÏûçes que definem como os pods sûÈo distribuûÙdos entre domûÙnios de falha, como regiûçes ou zonas de disponibilidade. O padrûÈo ûˋ `+[]+`.
`+core.podAnnotations+`:: As anotaûÏûçes a serem adicionadas ao pod kernel. O padrûÈo ûˋ `+{}+`.
`+core.serviceAnnotations+`:: As anotaûÏûçes a serem adicionadas ao serviûÏo kernel. O padrûÈo ûˋ `+{}+`.
`+core.configureUserSettings+`:: Uma string JSON na variûÀvel de ambiente CONFIG_OVERWRITE_JSON para configurar as configuraûÏûçes do usuûÀrio.
`+core.quotaUpdateProvider+`:: O provedor para atualizar o uso da cota do projeto, as opûÏûçes sûÈo `+redis+` ou `+db+`. O padrûÈo ûˋ `+db+`.
`+core.secret+`:: Usado quando o servidor kernel se comunica com outros componentes.
`+core.secretName+`:: O nome de um {kube} segredo para usar seu prû°prio certificado TLS e chave privada para a criptografia ou descriptografia de token.
`+core.tokenKey+`:: A chave privada RSA formatada em PEM usada para assinar tokens de serviûÏo.
`+core.tokenCert+`:: O certificado formatado em PEM assinado por `+core.tokenKey+` usado para validar tokens de serviûÏo.
`+core.xsrfKey+`:: A chave XSRF, gerada automaticamente se nûÈo for especificada.
`+core.priorityClassName+`:: A classe de prioridade para executar o pod.
`+core.artifactPullAsyncFlushDuration+`:: A duraûÏûÈo do tempo para atualizar assûÙncronamente o tempo de pull de artefatos e a contagem de pull do repositû°rio.
`+core.gdpr.deleteUser+`:: Habilita a exclusûÈo de usuûÀrios em conformidade com o GDPR. O padrûÈo ûˋ `+false+`.
`+core.gdpr.auditLogsCompliant+`:: Habilita a conformidade com o GDPR para logs de auditoria, alterando o nome de usuûÀrio para seu valor CRC32 se esse usuûÀrio foi excluûÙdo do sistema. O padrûÈo ûˋ `+false+`.
`+core.initContainers+`:: Os contûˆineres init a serem executados antes que o contûˆiner do controlador inicie. O padrûÈo ûˋ `+[]+`.


.ParûÂmetros do serviûÏo de trabalho.
`+jobservice.image.repository+`:: O repositû°rio para a imagem do serviûÏo de trabalho. O padrûÈo ûˋ `+private-registry/harbor-jobservice+`.
`+jobservice.image.tag+`:: A tag para a imagem do serviûÏo de trabalho. O padrûÈo ûˋ `+2.11+`.
`+jobservice.replicas+`:: O nû¤mero de rûˋplicas. O padrûÈo ûˋ `+1+`.
`+jobservice.revisionHistoryLimit+`:: O limite de histû°rico de revisûçes. O padrûÈo ûˋ `+10+`.
`+jobservice.maxJobWorkers+`:: O nû¤mero mûÀximo de worker de trabalho. O padrûÈo ûˋ `+10+`.
`+jobservice.jobLoggers+`:: Os registradores para trabalhos: `+file+`, `+database+` ou `+stdout+`. O padrûÈo ûˋ `+[file]+`.
`+jobservice.loggerSweeperDuration+`:: A duraûÏûÈo em dias para manter os logs de trabalho (ignorados se `+jobLoggers+` estiver definido como `+stdout+`). O padrûÈo ûˋ `+14+`.
`+jobservice.notification.webhook_job_max_retry+`:: O nû¤mero mûÀximo de tentativas para o envio de notificaûÏûçes via webhook. O padrûÈo ûˋ `+3+`.
`+jobservice.notification.webhook_job_http_client_timeout+`:: O tempo limite do cliente HTTP em segundos para o envio de notificaûÏûçes via webhook. O padrûÈo ûˋ `+3+`.
`+jobservice.reaper.max_update_hours+`:: O tempo mûÀximo em horas para aguardar a conclusûÈo de uma tarefa. Se a tarefa nûÈo for concluûÙda apû°s as horas especificadas, ela ûˋ marcada como um erro, mas continua em execuûÏûÈo. O padrûÈo ûˋ `+24+`.
`+jobservice.reaper.max_dangling_hours+`:: O tempo mûÀximo em horas para execuûÏûÈo em estado de execuûÏûÈo sem uma nova tarefa criada. O padrûÈo ûˋ `+168+`.
`+jobservice.resources+`:: Os [recursos] a serem alocados para o contûˆiner. O padrûÈo ûˋ `+undefined+`.
`+jobservice.automountServiceAccountToken+`:: Monta o token da conta de serviûÏo. O padrûÈo ûˋ `+false+`.
`+jobservice.nodeSelector+`:: Os rû°tulos de nû° para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+{}+`.
`+jobservice.tolerations+`:: As tolerûÂncias para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+[]+`.
`+jobservice.affinity+`:: As afinidades de nû° ou pod. O padrûÈo ûˋ `+{}+`.
`+jobservice.topologySpreadConstraints+`:: As restriûÏûçes que definem como os pods sûÈo distribuûÙdos entre domûÙnios de falha, como regiûçes ou zonas de disponibilidade. O padrûÈo ûˋ `+[]+`.
`+jobservice.podAnnotations+`:: As anotaûÏûçes a serem adicionadas ao pod do serviûÏo de trabalho. O padrûÈo ûˋ `+{}+`.
`+jobservice.priorityClassName+`:: A classe de prioridade para executar o pod.
`+jobservice.secret+`:: O segredo usado quando o serviûÏo de trabalho se comunica com outros componentes. Se uma chave secreta nûÈo for especificada, {helm} a gera. Deve ser uma string de 16 caracteres.
`+jobservice.initContainers+`:: Os contûˆineres init a serem executados antes que o contûˆiner do controlador inicie. O padrûÈo ûˋ `+[]+`.


.ParûÂmetros do registro
`+registry.registry.image.repository+`:: A localizaûÏûÈo do repositû°rio para a imagem do registro. O padrûÈo ûˋ `+private-registry/harbor-registry+`.
`+registry.registry.image.tag+`:: A tag para a imagem do registro. O padrûÈo ûˋ `+2.11+`.
`+registry.registry.resources+`:: Os [recursos] a serem alocados para o contûˆiner. O padrûÈo ûˋ `+undefined+`.
`+registry.controller.image.repository+`:: A localizaûÏûÈo do repositû°rio para a imagem do controlador do registro. O padrûÈo ûˋ `+private-registry/harbor-registryctl+`.
`+registry.controller.image.tag+`:: A tag para a imagem do controlador do registro. O padrûÈo ûˋ `+2.11+`.
`+registry.controller.resources+`:: Os [recursos] a serem alocados para o contûˆiner. O padrûÈo ûˋ `+undefined+`.
`+registry.replicas+`:: O nû¤mero de instûÂncias replicadas. O padrûÈo ûˋ `+1+`.
`+registry.revisionHistoryLimit+`:: O nû¤mero mûÀximo de revisûçes a serem mantidas no histû°rico. O padrûÈo ûˋ `+10+`.
`+registry.nodeSelector+`:: Os rû°tulos de nû° para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+{}+`.
`+registry.automountServiceAccountToken+`:: Controla se deve montar o token da conta de serviûÏo. O padrûÈo ûˋ `+false+`.
`+registry.tolerations+`:: As tolerûÂncias para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+[]+`.
`+registry.affinity+`:: As afinidades de nû° ou pod. O padrûÈo ûˋ `+{}+`.
`+registry.topologySpreadConstraints+`:: As restriûÏûçes que definem a distribuiûÏûÈo de pods entre domûÙnios de falha, como regiûçes ou zonas de disponibilidade. O padrûÈo ûˋ `+[]+`.
`+registry.middleware+`:: Suporte a middleware para um CDN entre o armazenamento de back end e {docker} destinatûÀrio de pull.
`+registry.podAnnotations+`:: As anotaûÏûçes a serem adicionadas ao pod do registro. O padrûÈo ûˋ `+{}+`.
`+registry.priorityClassName+`:: A classe de prioridade para a execuûÏûÈo do pod.
`+registry.secret+`:: O segredo que protege o estado de upload entre o cliente e o armazenamento do registro back end.
`+registry.credentials.username+`:: O nome de usuûÀrio para acesso ao registro interno do kernel {harbor}. O padrûÈo ûˋ `+harbor_registry_user+`.
`+registry.credentials.password+`:: A senha para acesso ao registro interno do kernel {harbor}. O padrûÈo ûˋ `+harbor_registry_password+`.
`+registry.credentials.existingSecret+`:: Um segredo existente contendo a senha para acesso û  instûÂncia do registro no modo de autenticaûÏûÈo htpasswd. O padrûÈo ûˋ `+""+`.
`+registry.credentials.htpasswdString+`:: O login e a senha no formato de string htpasswd. Exclui `+registry.credentials.username+` e `+registry.credentials.password+`. O padrûÈo ûˋ `+undefined+`.
`+registry.relativeurls+`:: Retorna URLs relativas nos cabeûÏalhos de LocalizaûÏûÈo quando verdadeiro. NecessûÀrio se {harbor} estiver atrûÀs de um proxy reverso. O padrûÈo ûˋ `+false+`.
`+registry.upload_purging.enabled+`:: Habilita a purgaûÏûÈo de diretû°rios de upload. O padrûÈo ûˋ `+true+`.
`+registry.upload_purging.age+`:: O perûÙodo de tempo apû°s o qual os arquivos nos diretû°rios de upload sûÈo removidos, o padrûÈo ûˋ uma semana. O padrûÈo ûˋ `+168h+`.
`+registry.upload_purging.interval+`:: O intervalo de tempo entre operaûÏûçes de purgaûÏûÈo. O padrûÈo ûˋ `+24h+`.
`+registry.upload_purging.dryrun+`:: Habilita o modo de simulaûÏûÈo para purgaûÏûÈo de uploads. O padrûÈo ûˋ `+false+`.
`+registry.initContainers+`:: Os contûˆineres init que sûÈo executados antes do inûÙcio do contûˆiner do controlador. O padrûÈo ûˋ `+[]+`.


.ParûÂmetros {trivy}
`+trivy.enabled+`:: Habilita ou desabilita o {trivy} scanner. O padrûÈo ûˋ `+true+`.
`+trivy.image.repository+`:: O repositû°rio para a {trivy} imagem do adaptador. O padrûÈo ûˋ `+private-registry/harbor-trivy-adapter+`.
`+trivy.image.tag+`:: A tag para a {trivy} imagem do adaptador. O padrûÈo ûˋ `+2.11+`.
`+trivy.resources+`:: Os recursos a serem alocados para o {trivy} contûˆiner do adaptador. O padrûÈo ûˋ `+undefined+`.
`+trivy.automountServiceAccountToken+`:: Se deve montar o token da conta de serviûÏo. O padrûÈo ûˋ `+false+`.
`+trivy.replicas+`:: O nû¤mero de rûˋplicas do Pod. O padrûÈo ûˋ `+1+`.
`+trivy.debugMode+`:: Habilita o modo remover {trivy} para soluûÏûÈo de problemas. O padrûÈo ûˋ `+false+`.
`+trivy.vulnType+`:: Lista de tipos de vulnerabilidades separados por vûÙrgula (`+os+` e `+library+`). O padrûÈo ûˋ `+os,library+`.
`+trivy.severity+`:: Lista de severidades de vulnerabilidades a serem verificadas, separadas por vûÙrgula. O padrûÈo ûˋ `+UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL+`.
`+trivy.ignoreUnfixed+`:: Exibe apenas vulnerabilidades corrigidas. O padrûÈo ûˋ `+false+`.
`+trivy.insecure+`:: Ignora a verificaûÏûÈo do certificado do registro. O padrûÈo ûˋ `+false+`.
`+trivy.skipUpdate+`:: Desabilita downloads de banco de dados {trivy} do GitHub. O padrûÈo ûˋ `+false+`.
`+trivy.skipJavaDBUpdate+`:: Requer download manual do arquivo `+trivy-java.db+` quando habilitado. O padrûÈo ûˋ `+false+`.
`+trivy.offlineScan+`:: Impede que {trivy} envie solicitaûÏûçes de API para identificar dependûˆncias. O padrûÈo ûˋ `+false+`.
`+trivy.securityCheck+`:: Lista de problemas de seguranûÏa a serem detectados, separados por vûÙrgula. O padrûÈo ûˋ `+vuln+`.
`+trivy.timeout+`:: O tempo de espera para a conclusûÈo da varredura. O padrûÈo ûˋ `+5m0s+`.
`+trivy.gitHubToken+`:: O token de acesso do GitHub necessûÀrio para downloads de banco de dados. O padrûÈo ûˋ `+undefined+`.
`+trivy.priorityClassName+`:: A classe de prioridade para executar o pod. O padrûÈo ûˋ `+undefined+`.
`+trivy.topologySpreadConstraints+`:: Define restriûÏûçes de distribuiûÏûÈo do pod entre domûÙnios de falha. O padrûÈo ûˋ `+undefined+`.
`+trivy.initContainers+`:: Lista de contûˆineres init a serem executados antes do contûˆiner principal iniciar. O padrûÈo ûˋ `+[]+`.

.ParûÂmetros do banco de dados
`+database.type+`:: O tipo de banco de dados. Defina como `+external+` ao usar um banco de dados externo. O padrûÈo ûˋ `+internal+`.
`+database.internal.image.repository+`:: O repositû°rio para a imagem do banco de dados. O padrûÈo ûˋ `+private-registry/harbor-db+`.
`+database.internal.image.tag+`:: A tag para a imagem do banco de dados. O padrûÈo ûˋ `+2.11+`.
`+database.internal.password+`:: A senha para o banco de dados interno. O padrûÈo ûˋ `+changeit+`.
`+database.internal.shmSizeLimit+`:: O limite de tamanho da memû°ria compartilhada para {postgresql} (tipicamente 50% do limite de memû°ria do contûˆiner). O padrûÈo ûˋ `+512Mi+`.
`+database.internal.resources+`:: Os recursos alocados para o contûˆiner do banco de dados. O padrûÈo ûˋ `+undefined+`.
`+database.internal.automountServiceAccountToken+`:: Controla se o token da conta de serviûÏo ûˋ montado. O padrûÈo ûˋ `+false+`.
`+database.internal.initContainer.migrator.resources+`:: Os recursos alocados para o contûˆiner de inicializaûÏûÈo do migrador de banco de dados. O padrûÈo ûˋ `+undefined+`.
`+database.internal.initContainer.permissions.resources+`:: Os recursos alocados para o contûˆiner de inicializaûÏûÈo das permissûçes do banco de dados. O padrûÈo ûˋ `+undefined+`.
`+database.internal.nodeSelector+`:: Os rû°tulos de nû° para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+{}+`.
`+database.internal.tolerations+`:: As tolerûÂncias para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+[]+`.
`+database.internal.affinity+`:: As configuraûÏûçes de afinidade do nû° ou pod. O padrûÈo ûˋ `+{}+`.
`+database.internal.priorityClassName+`:: A classe de prioridade para executar o pod. O padrûÈo ûˋ `+undefined+`.
`+database.internal.livenessProbe.timeoutSeconds+`:: O tempo limite em segundos para a liveness probe (intervalo: 1-5s). O padrûÈo ûˋ `+1+`.
`+database.internal.readinessProbe.timeoutSeconds+`:: O tempo limite em segundos para a verificaûÏûÈo de prontidûÈo (intervalo: 1-5s). O padrûÈo ûˋ `+1+`.
`+database.internal.extrInitContainers+`:: Contûˆineres de inicializaûÏûÈo adicionais que sûÈo executados antes do contûˆiner do banco de dados iniciar. O padrûÈo ûˋ `+[]+`.
`+database.external.host+`:: O nome de host do banco de dados externo. O padrûÈo ûˋ `+192.168.0.1+`.
`+database.external.port+`:: O nû¤mero da porta do banco de dados externo. O padrûÈo ûˋ `+5432+`.
`+database.external.username+`:: O nome de usuûÀrio para o banco de dados externo. O padrûÈo ûˋ `+user+`.
`+database.external.password+`:: A senha para o banco de dados externo. O padrûÈo ûˋ `+password+`.
`+database.external.coreDatabase+`:: O nome do banco de dados usado pelo serviûÏo kernel. O padrûÈo ûˋ `+registry+`.
`+database.external.existingSecret+`:: O segredo existente contendo a senha do banco de dados. A chave deve ser `+password+`. O padrûÈo ûˋ `+""+`.
`+database.external.sslmode+`:: O mûˋtodo de conexûÈo para o banco de dados externo. OpûÏûçes: `+require+`, `+verify-full+`, `+verify-ca+`, `+disable+`. O padrûÈo ûˋ `+disable+`.
`+database.maxIdleConns+`:: O nû¤mero mûÀximo de conexûçes ociosas no pool (0 ou menos significa que nenhuma conexûÈo ociosa ûˋ mantida). O padrûÈo ûˋ `+50+`.
`+database.maxOpenConns+`:: O nû¤mero mûÀximo de conexûçes abertas ao banco de dados (0 ou menos significa ilimitado). O padrûÈo ûˋ `+100+`.
`+database.podAnnotations+`:: As anotaûÏûçes a serem adicionadas ao pod do banco de dados. O padrûÈo ûˋ `+{}+`.


.{valkey} / {redis} parûÂmetros
`+redis.type+`:: O tipo de implantaûÏûÈo {redis}. Defina como `+external+` para {redis} externo. O padrûÈo ûˋ `+internal+`.
`+redis.internal.image.repository+`:: O repositû°rio da imagem {redis}. O padrûÈo ûˋ `+private-registry/harbor-redis+`.
`+redis.internal.image.tag+`:: A tag da imagem {redis}. O padrûÈo ûˋ `+7.2+`.
`+redis.internal.resources+`:: Os recursos alocados para o contûˆiner {redis}. O padrûÈo ûˋ `+undefined+`.
`+redis.internal.automountServiceAccountToken+`:: Controla se o token da conta de serviûÏo ûˋ montado. O padrûÈo ûˋ `+false+`.
`+redis.internal.nodeSelector+`:: Os rû°tulos de nû° para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+{}+`.
`+redis.internal.tolerations+`:: As tolerûÂncias para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+[]+`.
`+redis.internal.affinity+`:: As configuraûÏûçes de afinidade do nû° ou pod. O padrûÈo ûˋ `+{}+`.
`+redis.internal.priorityClassName+`:: A classe de prioridade para executar o {redis} pod. O padrûÈo ûˋ `+undefined+`.
`+redis.internal.jobserviceDatabaseIndex+`:: O ûÙndice do banco de dados para o jobservice. O padrûÈo ûˋ `+1+`.
`+redis.internal.registryDatabaseIndex+`:: O ûÙndice do banco de dados para o registry. O padrûÈo ûˋ `+2+`.
`+redis.internal.trivyAdapterIndex+`:: O ûÙndice do banco de dados para o {trivy} adaptador. O padrûÈo ûˋ `+5+`.
`+redis.internal.harborDatabaseIndex+`:: O ûÙndice do banco de dados para a {harbor} lû°gica de negû°cios diversa. O padrûÈo ûˋ `+0+`.
`+redis.internal.cacheLayerDatabaseIndex+`:: O ûÙndice do banco de dados para a camada de cache de {harbor}. O padrûÈo ûˋ `+0+`.
`+redis.internal.initContainers+`:: Os contûˆineres init que sûÈo executados antes do {redis} contûˆiner iniciar. O padrûÈo ûˋ `+[]+`.
`+redis.external.addr+`:: O endereûÏo da {redis} instûÂncia externa. O padrûÈo ûˋ `+192.168.0.2:6379+`.
`+redis.external.sentinelMasterSet+`:: O nome do {redis} conjunto mestre Sentinel (se aplicûÀvel). O padrûÈo ûˋ `+undefined+`.
`+redis.external.coreDatabaseIndex+`:: O ûÙndice do banco de dados para o kernel. O padrûÈo ûˋ `+0+`.
`+redis.external.jobserviceDatabaseIndex+`:: O ûÙndice do banco de dados para o jobservice. O padrûÈo ûˋ `+1+`.
`+redis.external.registryDatabaseIndex+`:: O ûÙndice do banco de dados para o registry. O padrûÈo ûˋ `+2+`.
`+redis.external.trivyAdapterIndex+`:: O ûÙndice do banco de dados para o {trivy} adaptador. O padrûÈo ûˋ `+5+`.
`+redis.external.harborDatabaseIndex+`:: O ûÙndice do banco de dados para a {harbor} lû°gica de negû°cios diversa. O padrûÈo ûˋ `+0+`.
`+redis.external.cacheLayerDatabaseIndex+`:: O ûÙndice do banco de dados para a camada de cache de {harbor}. O padrûÈo ûˋ `+0+`.
`+redis.external.username+`:: O nome de usuûÀrio para {redis} autenticaûÏûÈo externa. O padrûÈo ûˋ `+undefined+`.
`+redis.external.password+`:: A senha para {redis} autenticaûÏûÈo externa. O padrûÈo ûˋ `+undefined+`.
`+redis.external.existingSecret+`:: O segredo existente contendo a {redis} senha. A chave deve ser `+REDIS_PASSWORD+`. O padrûÈo ûˋ `+""+`.
`+redis.podAnnotations+`:: As anotaûÏûçes a serem adicionadas ao {redis} pod. O padrûÈo ûˋ `+{}+`.

.ParûÂmetros do exportador
`+exporter.replicas+`:: O nû¤mero de rûˋplicas a serem executadas. O padrûÈo ûˋ `+1+`.
`+exporter.revisionHistoryLimit+`:: O limite do histû°rico de revisûçes. O padrûÈo ûˋ `+10+`.
`+exporter.podAnnotations+`:: AnotaûÏûçes a serem adicionadas ao pod do exportador. O padrûÈo ûˋ `+{}+`.
`+exporter.image.repository+`:: O repositû°rio para a imagem do exportador. O padrûÈo ûˋ `+private-registry/harbor-exporter+`.
`+exporter.image.tag+`:: A tag para a imagem do exportador. O padrûÈo ûˋ `+2.11+`.
`+exporter.nodeSelector+`:: Rû°tulos de nû° para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+{}+`.
`+exporter.tolerations+`:: TolerûÂncias para atribuiûÏûÈo de pod. O padrûÈo ûˋ `+[]+`.
`+exporter.affinity+`:: Afinidades de nû° ou pod. O padrûÈo ûˋ `+{}+`.
`+exporter.topologySpreadConstraints+`:: RestriûÏûçes que definem como os Pods se espalham por domûÙnios de falha, como regiûçes ou zonas de disponibilidade. O padrûÈo ûˋ `+[]+`.
`+exporter.automountServiceAccountToken+`:: Controla se deve montar o serviceAccountToken. O padrûÈo ûˋ `+false+`.
`+exporter.cacheDuration+`:: A duraûÏûÈo do cache para informaûÏûçes coletadas pelo exportador. O padrûÈo ûˋ `+30+`.
`+exporter.cacheCleanInterval+`:: O intervalo de limpeza do cache para informaûÏûçes coletadas pelo exportador. O padrûÈo ûˋ `+14400+`.
`+exporter.priorityClassName+`:: A classe de prioridade para executar o pod. O padrûÈo ûˋ `+undefined+`.

.ParûÂmetros de mûˋtricas.
`+metrics.enabled+`:: Habilita {harbor} mûˋtricas. O padrûÈo ûˋ `+false+`.
`+metrics.core.path+`:: O caminho da URL para mûˋtricas do kernel. O padrûÈo ûˋ `+/metrics+`.
`+metrics.core.port+`:: A porta para mûˋtricas do kernel. O padrûÈo ûˋ `+8001+`.
`+metrics.registry.path+`:: O caminho da URL para mûˋtricas do registry. O padrûÈo ûˋ `+/metrics+`.
`+metrics.registry.port+`:: A porta para mûˋtricas do registry. O padrûÈo ûˋ `+8001+`.
`+metrics.exporter.path+`:: O caminho da URL para mûˋtricas do exportador. O padrûÈo ûˋ `+/metrics+`.
`+metrics.exporter.port+`:: A porta para mûˋtricas do exportador. O padrûÈo ûˋ `+8001+`.
`+metrics.serviceMonitor.enabled+`:: Habilita a criaûÏûÈo de um {prometheus} ServiceMonitor (requer {prometheus} CRDs). O padrûÈo ûˋ `+false+`.
`+metrics.serviceMonitor.additionalLabels+`:: Rû°tulos adicionais a serem aplicados ao manifesto do ServiceMonitor. O padrûÈo ûˋ `+""+`.
`+metrics.serviceMonitor.interval+`:: O intervalo de coleta para mûˋtricas de {harbor}. O padrûÈo ûˋ `+""+`.
`+metrics.serviceMonitor.metricRelabelings+`:: As regras de reetiquetagem para mûˋtricas antes da ingestûÈo. O padrûÈo ûˋ `+[]+`.
`+metrics.serviceMonitor.relabelings+`:: As regras de reetiquetagem para mûˋtricas antes da coleta. O padrûÈo ûˋ `+[]+`.

.ParûÂmetros de rastreamento
`+trace.enabled+`:: Habilita a funcionalidade de rastreamento. O padrûÈo ûˋ `+false+`.
`+trace.provider+`:: O provedor de rastreamento (`+jaeger+` ou `+otel+`). A versûÈo do Jaeger deve ser 1.26 ou superior. O padrûÈo ûˋ `+jaeger+`.
`+trace.sample_rate+`:: A taxa de amostragem para dados de rastreamento. `+1+` amostra 100%, `+0.5+` amostra 50%. O padrûÈo ûˋ `+1+`.
`+trace.namespace+`:: O namespace para diferenciar diferentes serviûÏos de {harbor}.
`+trace.attributes+`:: Um dicionûÀrio de chave-valor para atributos definidos pelo usuûÀrio na inicializaûÏûÈo do provedor de rastreamento.
`+trace.jaeger.endpoint+`:: O endpoint para rastreamento do Jaeger. O padrûÈo ûˋ `+\http://hostname:14268/api/traces+`.
`+trace.jaeger.username+`:: O nome de usuûÀrio para autenticaûÏûÈo do Jaeger.
`+trace.jaeger.password+`:: A senha para autenticaûÏûÈo do Jaeger.
`+trace.jaeger.agent_host+`:: O host do agente para o Jaeger.
`+trace.jaeger.agent_port+`:: A porta do agente para o Jaeger. O padrûÈo ûˋ `+6831+`.
`+trace.otel.endpoint+`:: O endpoint para rastreamento de {otelemetry}. O padrûÈo ûˋ `+hostname:4318+`.
`+trace.otel.url_path+`:: O caminho da URL para {otelemetry}. O padrûÈo ûˋ `+/v1/traces+`.
`+trace.otel.compression+`:: Habilita a compressûÈo para {otelemetry}. O padrûÈo ûˋ `+false+`.
`+trace.otel.insecure+`:: Estabelece uma conexûÈo insegura para {otelemetry}. O padrûÈo ûˋ `+true+`.
`+trace.otel.timeout+`:: O tempo limite em segundos para {otelemetry}. O padrûÈo ûˋ `+10+`.

.ParûÂmetros de cache
`+cache.enabled+`:: Habilita a camada de cache. O padrûÈo ûˋ `+false+`.
`+cache.expireHours+`:: O tempo de expiraûÏûÈo em horas para a camada de cache. O padrûÈo ûˋ `+24+`.
