include::partial$variables.adoc[]
= 用語集
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 詳細については、Kubernetes環境の{project-name} ポリシーに関連する主要なリソースと構成を参照してください。
:doc-persona: ["kubewarden-all"]
:doc-topic: ["glossary"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "glossary"]
:sidebar_label: 用語集
:sidebar_position: 90
:current-version: {page-origin-branch}

== A

=== アドミッションポリシー

名前空間全体のリソース。ポリシーは、AdmissionPolicyが定義されている名前空間をターゲットとする リクエストのみを処理する。

== C

=== ClusterAdmissionPolicy

クラスタ全体のリソースを対象とする<<_admissionpolicy,AdmissionPolicy>>。

=== クラスターレポート

<<_report,Reportと>>ClusterReportはポリシースキャンの結果を保存します。どちらを使うかは、リソースのスコープによる。

== K

=== kwctl

KubernetesのYAMLファイルを生成し、ポリシーのデプロイメントをテストするためのCLIツール。

== M

=== MutatingWebhookConfiguration

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[]Kubernetes {short-project-name} コントローラーによって作成され、Kubernetesに`+AdmissionReview+` を送信する場所を知らせる。
言い換えれば、これは{short-project-name} コントローラーがKubernetesに、リソースを変異させるポリシーがどこにあるかを通知する方法である。

== P

=== レポート

Reportと<<_clusterreport,ClusterReportは>>ポリシースキャンの結果を保存します。どちらを使うかは、リソースのスコープによる。

[#_policy_server]
=== PolicyServer

PolicyServerは、リクエストに対して{short-project-name} ポリシーを実行することにより、受信リクエストを検証します。

== V

=== ValidatingWebhookConfiguration

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[]Kubernetes {short-project-name} コントローラーによって作成され、Kubernetesに`+AdmissionReview+` を送信する場所を知らせる。
言い換えれば、これは{short-project-name} 、Kubernetesにリソースを検証するポリシーがどこにあるかを通知する方法だ。

== W

=== waPC

WebAssembly プロシージャコール。 https://wapc.io.

=== WASI

WebAssembly システムインターフェース。 https://wasi.dev.

=== ワスム

スタックベースの仮想マシン用のバイナリ命令フォーマット。ウェブ展開用に設計されています。 https://webassembly.org.

=== ワズムタイム

WebAssemblyのランタイム。 https://wasmtime.dev.
