= Coletor de telemetria aberto
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

O OpenTelemetry Collector oferece uma implementação independente de fornecedor para receber, processar e exportar dados de telemetria. Os aplicativos instrumentados com Open Telemetry SDKs podem usar o coletor para enviar dados de telemetria para o SUSE Observability (rastreamentos e métricas).

Seus aplicativos, quando configurados com SDKs do OpenTelemetry, podem usar o coletor para enviar dados de telemetria, como rastreamentos e métricas, para o SUSE Observability ou outro coletor (para processamento posterior). O coletor está configurado para receber esses dados por padrão via OTLP, o protocolo nativo de telemetria aberta. Ele também pode receber dados em outros formatos fornecidos por outros SDKs de instrumentação, como Jaeger e Zipkin para rastreamentos, e Influx e Prometheus para métricas.

O coletor está sendo executado próximo ao seu aplicativo, no mesmo cluster Kubernetes, na mesma máquina virtual, etc. Isso permite que os SDKs descarreguem rapidamente os dados para o coletor, que pode então fazer transformações, agrupamento e filtragem. Ele pode ser usado por vários aplicativos e permite alterações fáceis em seu pipeline de processamento de dados.

Para obter guias de instalação, use os diferentes xref:/setup/otel/getting-started/README.adoc[guias de introdução]. Os guias de introdução fornecem uma configuração básica do coletor para começar, mas, com o tempo, você desejará personalizá-la de acordo com suas necessidades e adicionar receptores, processadores e exportadores adicionais para personalizar o pipeline de ingestão de acordo com suas necessidades.

== Configuração

A configuração do coletor define pipelines para processar os diferentes sinais de telemetria. Os componentes do pipeline de processamento podem ser divididos em várias categorias, e cada componente tem sua própria configuração. Aqui, daremos uma visão geral das diferentes seções de configuração e como usá-las.

=== Receptores

Os receptores aceitam dados de telemetria de aplicativos instrumentados, aqui via OTLP:

[,yaml]
----
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
----

Há muitos outros receptores que aceitam dados por meio de outros protocolos, por exemplo, rastreamentos Zipkin, ou que coletam ativamente dados de várias fontes, por exemplo:

* Métricas do host
* Métricas do Kubernetes
* Métricas do Prometheus (OpenMetrics)
* Bancos de dados

Alguns receptores suportam todos os 3 sinais (traços, métricas, registros), outros suportam apenas 1 ou 2, por exemplo, o receptor Prometheus só pode coletar métricas. O repositório opentelemetry-collector-contrib tem https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver[todos os receptores] com documentação sobre sua configuração.

=== Processadores

Os dados dos receptores podem ser transformados ou filtrados por processadores.

[,yaml]
----
processors:
  batch: {}
----

O processador em lote agrupa todos os três sinais, melhorando a compactação e reduzindo o número de conexões de saída. O repositório opentelemetry-collector-contrib tem https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[todos os processadores] com documentação sobre sua configuração.

=== Exportadores

Para enviar dados para o backend do SUSE Observability, o coletor tem exportadores. Há exportadores para diferentes protocolos, baseados em push ou pull, e diferentes backends. Usando os protocolos OTLP, também é possível usar outro coletor como destino para processamento adicional.

[,yaml]
----
exporters:
  # The gRPC otlp exporter
  otlp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp endpoint
    endpoint: <otlp-suse-observability-endpoint>
    # Use snappy compression, if no compression specified the data will be uncompressed
    compression: snappy
----

O exportador do SUSE Observability requer autenticação usando uma chave api, para configurar que uma <<_extensions,extensão de autenticação>> seja usada. O repositório opentelemetry-collector-contrib tem https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter[todos os exportadores] com documentação sobre sua configuração.

Se o exportador gRPC não funcionar para você (consulte também a xref:/setup/otel/troubleshooting.adoc#_some_proxies_and_firewalls_dont_work_well_with_grpc[solução de problemas]), é possível mudar para o protocolo OTLP over HTTP, um pouco menos eficiente, usando o exportador `otlphttp`. Substitua todas as referências a `otlp/suse-observability` nas seções `pipelines` e `exporter` por `otlphttp/suse-observability` e certifique-se de atualizar a configuração do exportador para:

[,yaml]
----
exporters:
  # The gRPC otlp exporter
  otlphttp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp HTTP endpoint
    endpoint: <otlp-http-suse-observability-endpoint>
    # Use snappy compression, if no compression specified the data will be uncompressed
    compression: snappy
----

[CAUTION]
====
O ponto de extremidade HTTP OTLP para o SUSE Observability é diferente do ponto de extremidade OTLP. Use as xref:/setup/otel/otlp-apis.adoc[APIs do OTLP] para encontrar o URL correto.
====


=== Tubulação de serviço

Para cada sinal de telemetria, um pipeline separado é configurado. Os pipelines são configurados na seção `service.pipeline` e definem quais receptores, processadores e exportadores devem ser usados e em que ordem. Antes de usar um componente no pipeline, ele deve primeiro ser definido em sua seção de configuração. O processador `batch`, por exemplo, não tem nenhuma configuração, mas ainda precisa ser declarado na seção `processors`. Os componentes configurados, mas não incluídos em um pipeline, não estarão ativos.

[,yaml]
----
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, spanmetrics, otlp/suse-observability]
    metrics:
      receivers: [otlp, spanmetrics, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlp/suse-observability]
----

=== Extensões

As extensões não são usadas diretamente em pipelines para processamento de dados, mas ampliam os recursos do coletor de outras maneiras. Para o SUSE Observability, ele é usado para configurar a autenticação usando uma chave api. As extensões devem ser definidas em uma seção de configuração antes de poderem ser usadas. Semelhante aos componentes do pipeline, uma extensão só fica ativa quando é ativada na seção `service.extensions`.

[,yaml]
----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
service:
  extensions: [ bearertokenauth ]
----

O repositório opentelemetry-collector-contrib tem https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension[todas as extensões] com documentação sobre sua configuração.

== Transformando a telemetria

Há muitos processadores no https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[repositório]. Aqui tentamos dar uma visão geral dos processadores comumente usados e seus recursos. Para obter mais detalhes e muitos outros processadores, use o https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor[repositório].

=== Filtragem

Algumas instrumentações ou aplicativos podem gerar muitos dados de telemetria que são ruidosos e desnecessários para o seu caso de uso. O https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor[processador de filtro] pode ser usado para descartar os dados que você não precisa no coletor, para evitar o envio dos dados ao SUSE Observability. Por exemplo, para descartar todos os dados de um serviço específico:

[,yaml]
----
processors:
  filter/ignore-service1:
    error_mode: ignore
    traces:
      span:
        - resource.attributes["service.name"] == "service1"
----

O processador de filtros usa o https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md[Open Telemetry Transformation Lanuage (OTTL)] para definir os filtros.

=== Adição, modificação ou exclusão de atributos

O https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor[processador de atributos] pode alterar atributos de períodos, registros ou métricas.

[,yaml]
----
processors:
  attributes/accountid:
    actions:
      - key: account_id
        value: 2245
        action: insert
----

O https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor[processador de recursos] pode modificar os atributos de um xref:/setup/otel/concepts.adoc#_resources[recurso]. Por exemplo, para adicionar um nome de cluster do Kubernetes a cada recurso:

[,yaml]
----
  processors:
    resource/add-k8s-cluster:
      attributes:
      - key: k8s.cluster.name
        action: upsert
        value: my-k8s-cluster
----

Para alterar nomes de métricas e outras informações específicas de métricas, há também o https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor[transformador de métricas].

=== Transformações

O https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor[processador de transformação] pode ser usado para, por exemplo, definir um status de amplitude:

[,yaml]
----
processors:
  transform:
    error_mode: ignore
    trace_statements:
      - set(span.status.code, STATUS_CODE_OK) where span.attributes["http.request.status_code"] == 400
----

Ele suporta muitas outras transformações, como a modificação do nome do intervalo, a conversão de tipos de métricas ou a modificação de eventos de registro. Consulte https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor[o readme do site] para conhecer todas as possibilidades. Ele usa o https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md[Open Telemetry Transformation Lanuage (OTTL)] para definir os filtros.

== Dados de sensibilidade à abrasão

O coletor é o local ideal para remover ou ofuscar dados confidenciais, porque ele fica entre seus aplicativos e o SUSE Observability e tem processadores para <<_transforming_telemetry,filtrar e transformar seus dados>>. Além dos recursos de filtragem e transformação já discutidos, há também um https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/redactionprocessor[processador de redação] disponível que pode mascarar os valores de atributos que correspondem a uma lista de blocos. Ele também pode remover atributos que não correspondam a uma lista especificada de atributos permitidos; no entanto, o uso desse recurso pode resultar rapidamente na eliminação da maioria dos atributos, resultando em recursos de observabilidade muito limitados. Observe que ele não processa atributos de recursos.

Um exemplo que mascara apenas atributos e/ou valores específicos:

[,yaml]
----
processors:
  redaction:
    allow_all_keys: true
    # attributes matching the regexes on the list are masked.
    blocked_key_patterns:
      - ".*token.*"
      - ".*api_key.*"
    blocked_values: # Regular expressions for blocking values of allowed span attributes
      - '4[0-9]{12}(?:[0-9]{3})?' # Visa credit card number
      - '(5[1-5][0-9]{14})' # MasterCard number
    summary: debug
----

== Experimentando o coletor

Os guias de introdução mostram como implantar o coletor no Kubernetes ou usar pacotes do Linux para uma configuração pronta para produção. Também é possível executá-lo, por exemplo, para testes, diretamente como um contêiner do docker para experimentá-lo:

[,bash]
----
docker run \
  -p 127.0.0.1:4317:4317 \
  -p 127.0.0.1:4318:4318 \
  -v $(pwd)/config.yaml:/etc/otelcol-contrib/config.yaml \
  ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
----

Isso usa a imagem do coletor contrib, que inclui todos os componentes contribuídos (receptores, processadores etc.). Uma versão menor e mais limitada da imagem também está disponível, mas ela tem apenas um conjunto muito limitado de componentes disponíveis:

[,bash]
----
docker run \
  -p 127.0.0.1:4317:4317 \
  -p 127.0.0.1:4318:4318 \
  -v $(pwd)/config.yaml:/etc/otelcol/config.yaml \
  ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest
----

Observe que a instalação do Kubernetes tem como padrão a distribuição do Kubernetes da imagem do coletor, `ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s`, que tem mais componentes do que a imagem básica, mas menos do que a imagem contrib. Se você encontrar componentes ausentes com essa imagem, poderá simplesmente alterá-la para usar a imagem do contrib, `ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib`, em vez disso.

== Solução de problemas

=== As solicitações HTTP do exportador são muito grandes

Em alguns casos, as solicitações HTTP para dados de telemetria podem se tornar muito grandes e podem ser recusadas pelo SUSE Observability. O SUSE Observability tem um limite de 4 MB para o protocolo gRPC. Se você se deparar com limites de solicitações HTTP, poderá reduzir o tamanho das solicitações alterando o algoritmo de compactação e limitando o tamanho máximo do lote.

==== Compactação de solicitações HTTP

Os guias de introdução habilitam a compactação `snappy` no coletor, que não é a melhor compactação, mas usa menos recursos da CPU do que `gzip`. Se você removeu a compactação, poderá ativá-la novamente ou mudar para um algoritmo de compactação que ofereça uma melhor https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md#_compression_comparison[taxa de compactação]. Os mesmos tipos de compactação estão disponíveis para os protocolos gRPC e HTTP.

==== Tamanho máximo do lote

Para reduzir o tamanho das solicitações HTTP, é possível adicionar uma configuração ao processador `batch`, limitando o tamanho do lote:

[,yaml]
----
processor:
  batch: {}
    send_batch_size: 8192 # This is the default value
    send_batch_max_size: 10000 # The default is 0, meaning no max size at all
----

O tamanho do lote é definido em número de períodos, pontos de dados métricos ou registros de log (não em bytes), portanto, talvez seja necessário fazer algumas experiências para encontrar a configuração correta para a sua situação. Para obter mais detalhes, consulte a https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/README.md[documentação do processador em lote].

== Recursos relacionados

A documentação do Open Telemetry fornece muito mais detalhes sobre a configuração e as opções alternativas de instalação:

* Abra a configuração do coletor de telemetria: https://opentelemetry.io/docs/collector/configuration/
* Instalação do coletor no Kubernetes: https://opentelemetry.io/docs/kubernetes/helm/collector/
* Usar o operador do Kubernetes em vez do gráfico do Helm do coletor: https://opentelemetry.io/docs/kubernetes/operator/
* Abra a amostragem de telemetria: https://opentelemetry.io/blog/2022/tail-sampling/
