= ランダムテンプレート変数
:revdate: 2025-09-08
:page-revdate: {revdate}

ランダムテンプレート変数は、要素演算子に組み込まれている。

xref:label-templates/label-templates.adoc[カスタムラベルテンプレートに]ランダムな`Int` 、`Hex` 、`UUID` の値を含めることができます。

この値は、`label template variables` レンダリング中にオンザフライで計算される。

[IMPORTANT]
.ランダムラベルのテンプレートは一度だけレンダリングされる
====

Random変数を含むラベルテンプレートは、登録ホストのxref:references/machineinventory-reference.adoc[MachineInventoryに]そのラベルの値がまだない（同じキーを持つラベルがないか、その値が空である）場合にのみレンダリングされます。

つまり、Random変数を持つラベル・テンプレートがレンダリングされるのは、以下の3つの場合である：

. の場合、ホストは初めて登録され、xref:references/machineinventory-reference.adoc[MachineInventory]は新たに作成される。
. ラベルテンプレートは、ホストが前回（再）登録した後、MachineRegistrationに追加された。
. ラベルテンプレート（同じラベルキー）に一致するxref:references/machineinventory-reference.adoc[MachineInventory]ラベルが手動で削除されたか、その値がクリアされた。
====


|===
| 可変 | 説明 | より

| `${Random/UUID}`
| ランダムUUID (例: fd95324a-c26b-4e28-8727-1dcec293a0ec)
| 1.7.0

| `${Random/Hex/[1-32]}`
| 指定された長さのランダムな16進文字列（最小1、最大32）
| 1.7.0

| `${Random/Int/[MAXINT]`
| ランダムな整数（最小 0、最大 MAXINT-1）
| 1.7.0
|===

[NOTE]
.レンダリング例
====
|===
| テンプレート値 | レンダリング値の例

| `${Random/UUID}`
| fd95324a-c26b-4e28-8727-1dcec293a0ec

| `${Random/Hex/12}`
| acd231f222b8

| `${Random/Int/10000}` 
| 9432

|===
====


ランダムテンプレート変数は、登録ホストに割り当てるカスタムホスト名を生成するのに便利です。

ホスト名は一意でなければならず、xref:references/machineregistration-reference.adoc[MachineRegistration] `spec.machineName` フィールドを通して割り当てられるので、同じカスタム接頭辞や接尾辞を共有するホストグループの一意性を保証するためにランダム変数を使用することができます。

詳しくは、xref:installation/hostname.adoc[HowTo/ホスト名のカスタマイズの]セクションをご覧ください。

.登録例 ランダムテンプレート変数
[,yaml]
----
include::example$quickstart/registration-random-hostname.yaml[]
----
