= 設定オプション
:page-languages: [en、ja、ko、zh]。
:revdate: 2026-03-03
:page-revdate: {revdate}

このページでは、K3を初めてセットアップする際によく使用されるオプションに焦点を当てています。詳細については、xref:advanced.adoc[Advanced Options and Configuration（詳細オプションと設定]）のドキュメント、およびxref:cli/server.adoc[サーバーと] xref:cli/agent.adoc[エージェントの]コマンドのドキュメントを参照してください。

[#_configuration_with_install_script]
== インストールスクリプトによる設定

xref:quick-start.adoc[クイックスタートガイドで]述べたように、https://get.k3s.io で利用可能なインストールスクリプトを使用して、systemd および openrc ベースのシステムにサービスとして K3s をインストールすることができます。

`INSTALL_K3S_EXEC` 、`K3S_` 環境変数、コマンド・フラグを組み合わせて、サービス・コンフィギュレーションにコンフィギュレーションを渡すことができる。
プレフィックス付きの環境変数、`INSTALL_K3S_EXEC` の値、および末尾のシェル引数はすべて、サービス構成に永続化される。
インストール後、環境ファイルを編集したり、サービス設定を編集したり、 あるいは単に新しいオプションを指定してインストーラを再実行することで、 設定を変更することができる。
{k3s-product-name} の場合は、https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL]を指す`INSTALL_K3S_ARTIFACT_URL` を使用する必要があります。

これを説明するために、以下のコマンドはすべて、フランネルなしで、トークンを使ってサーバーを登録するのと同じ動作になる：

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_EXEC="server" sh -s - --flannel-backend none --token 12345
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_EXEC="server --flannel-backend none" K3S_TOKEN=12345 sh -s -
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_TOKEN=12345 sh -s - server --flannel-backend none
# server is assumed below because there is no K3S_URL
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_EXEC="--flannel-backend none --token 12345" sh -s -
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - --flannel-backend none --token 12345
----

エージェントを登録する場合、以下のコマンドはすべて同じ動作になります：

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_EXEC="agent --server https://k3s.example.com --token mypassword" sh -s -
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_EXEC="agent" K3S_TOKEN="mypassword" sh -s - --server https://k3s.example.com
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_URL=https://k3s.example.com sh -s - agent --token mypassword
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_URL=https://k3s.example.com K3S_TOKEN=mypassword sh -s - # agent is assumed because of K3S_URL
----

すべての環境変数の詳細については、xref:reference/env-variables.adoc[環境変数を]参照してくださいxref:reference/env-variables.adoc[。]

[IMPORTANT]
.注
====
インストールスクリプトの実行時に設定を行い、インストールスクリプトの再実 行時に再度設定を行わなかった場合、元の値は失われます。

<<_configuration_file,設定ファイルの>>内容は、インストー ルスクリプトでは管理されません。
設定をインストールスクリプトから独立させたい場合、環境変数や引数をインストー ルスクリプトに渡すのではなく、設定ファイルを使用する必要があります。
====


== バイナリによる構成

インストールスクリプトは、K3sがシステムサービスとして実行されるように設定することに主眼を置いています。インストールスクリプトを使用しない場合は、https://github.com/k3s-io/k3s/releases/latest[GitHubリリース]ページからバイナリをダウンロードし、パスに置いて実行するだけでK3sを実行することができます。これは、永続的なインストールには特に有用ではないが、K3をシステムサービスとして管理する価値がないような迅速なテストを実行する場合には有用であろう。

[,bash]
----
curl -Lo /usr/local/bin/k3s <PRIME-ARTIFACTS-URL>/k3s/v1.35.1%2Bk3s1/k3s; chmod a+x /usr/local/bin/k3s
----

`K3S_` 環境変数を設定することで、コンフィギュレーションを渡すことができる：

[,bash]
----
K3S_KUBECONFIG_MODE="644" k3s server
----

あるいはコマンドフラッグ：

[,bash]
----
k3s server --write-kubeconfig-mode=644
----

k3sエージェントもこのように設定できる：

[,bash]
----
k3s agent --server https://k3s.example.com --token mypassword
----

K3sサーバーの設定の詳細については、xref:cli/server.adoc[`k3s server` のドキュメントを]参照してください。 +
K3sエージェントの設定の詳細については、xref:cli/agent.adoc[`k3s agent` ドキュメントを]参照してください。 +
また、`--help` フラグを使えば、利用可能なすべてのオプションと、それに対応する環境変数のリストを見ることができる。

[IMPORTANT]
.マッチングフラッグ
====
サーバーノードの重要なフラグを一致させることが重要です。例えば、マスター・ノードでフラグ`--disable servicelb` または`--cluster-cidr=10.200.0.0/16` を使用し、他のサーバー・ノードで設定しなかった場合、そのノードは参加に失敗します。などのエラーが表示される：
`failed to validate server configuration: critical configuration value mismatch.`
どのフラグをサーバーノードで同じように設定しなければならないかについての詳細は、（上記リンク先の）サーバー設定ドキュメントを参照してください。
====

== コンテナイメージによる構成

K3sコンテナイメージ（https://hub.docker.com/r/rancher/k3s[\`docker.io/rancher/k3s`]）は、GitHubリリースページで利用可能なバイナリと同じ設定方法をサポートしています。

[#_configuration_file]
== 設定ファイル

環境変数やCLI引数によるK3sの設定に加えて、K3sは設定ファイルを使用することもできます。設定ファイルは、K3sのインストール方法や実行方法に関係なくロードされます。

デフォルトでは、コンフィギュレーションは`/etc/rancher/k3s/config.yaml` からロードされ、ドロップインファイルは`/etc/rancher/k3s/config.yaml.d/*.yaml` からアルファベット順にロードされる。
このパスは、`--config` CLIフラグまたは`K3S_CONFIG_FILE` env varで設定できる。
デフォルトのコンフィグファイル名を上書きする場合、ドロップインディレクトリのパスも変更されます。

基本的な`server` 設定ファイルの例を以下に示す：

[,yaml]
./etc/rancher/k3s/config.yaml
----
write-kubeconfig-mode: "0644"
tls-san:
  - "foo.local"
node-label:
  - "foo=bar"
  - "something=amazing"
cluster-init: true
----

これは以下のCLI引数と同等である：

[,bash]
----
k3s server \
  --write-kubeconfig-mode "0644"    \
  --tls-san "foo.local"             \
  --node-label "foo=bar"            \
  --node-label "something=amazing"  \
  --cluster-init
----

一般的に、CLI 引数はそれぞれの YAML キーにマップされ、繰り返し可能な CLI 引数は YAML リストとして表現されます。ブール値のフラグは YAML ファイルにおいて`true` もしくは`false` で表されます。

また、設定ファイルとCLI引数の両方を使用することも可能です。このような状況では、値は両方のソースからロードされるが、CLIの引数が優先される。`--node-label` のような繰り返し可能な引数の場合、CLI引数はリスト内のすべての値を上書きする。

=== バリュー・マージ・ビヘイビア

複数のファイルに存在する場合、与えられたキーに対して最後に見つかった値が使われる。キーに`+` を付加することで、既存の文字列やスライスを置き換える代わりに、その値を付加することができる。それ以降のファイルでこのキーが出現する場合は、蓄積された値の上書きを防ぐため、`+` 。

複数の設定ファイルからマージされた値の例を以下に示す：

[,yaml]
./etc/rancher/k3s/config.yaml
----
token: boop
node-label:
  - foo=bar
  - bar=baz
----

[,yaml]
./etc/rancher/k3s/config.yaml.d/test1.yaml
----
write-kubeconfig-mode: 600
node-taint:
  - alice=bob:NoExecute
----

[,yaml]
./etc/rancher/k3s/config.yaml.d/test2.yaml
----
write-kubeconfig-mode: 777
node-label:
  - other=what
  - foo=three
node-taint+:
  - charlie=delta:NoSchedule
----

この結果、最終的なコンフィギュレーションはこうなる：

[,yaml]
----
write-kubeconfig-mode: 777
token: boop
node-label:
  - other=what
  - foo=three
node-taint:
  - alice=bob:NoExecute
  - charlie=delta:NoSchedule
----

== すべてをまとめる

上記のオプションはすべて、ひとつの例にまとめることができる。

`/etc/rancher/k3s/config.yaml` に`config.yaml` ファイルが作成される：

[,yaml]
----
token: "secret"
debug: true
----

その後、環境変数とフラグを組み合わせてインストールスクリプトを実行する：

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server" sh -s - --flannel-backend none
----

または、すでにK3sバイナリをインストールしている場合：

[,bash]
----
K3S_KUBECONFIG_MODE="644" k3s server --flannel-backend none
----

この結果、サーバーは

* パーミッションを持つkubeconfigファイル `644`
* フランネル・バックエンド `none`
* に設定されたトークン。 `secret`
* デバッグログを有効にする

== Kubelet 設定ファイル

Kubernetesは、CLIフラグと設定ファイルの両方によるkubeletの設定をサポートしている。CLIフラグによるkubeletの設定は長い間非推奨でしたが、現在もサポートされており、基本オプションを設定する最も簡単な方法です。一部の高度なkubelet構成は、configファイルを介してのみ設定できます。詳細については、https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/[]kubeletのKubernetesドキュメントおよびhttps://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/[設定ファイルによるkubeletパラメータの]設定を参照してください。

kubelet ドロップイン構成ファイルまたは構成ファイル (以下のオプション 1 および 2) のサポートは、v1.32 以降でのみ利用可能です。古いリリースの場合は、kubelet argsを直接使用してください（以下のオプション番号3）。

K3sは、`/var/lib/rancher/k3s/agent/etc/kubelet.conf.d/00-k3s-defaults.conf` に格納されているデフォルトのkubelet設定を使用します。デフォルトのコンフィギュレーション・パラメーターを変更したい場合、3つの方法がある：

. `/var/lib/rancher/k3s/agent/etc/kubelet.conf.d/` にドロップイン設定ファイルを置く*（推奨）*。
. フラグ`--kubelet-arg=config=$PATHTOFILE` 、`$PATHTOFILE` は kubelet コンフィグパラメータを含むファイルへのパス (例:`/etc/rancher/k3s/kubelet.conf`) またはフラグ`--kubelet-arg=config-dir=$PATHTODIR` 、`$PATHTODIR` は kubelet コンフィグパラメータを含むファイルを含むことができるディレクトリへのパス (例:`/etc/rancher/k3s/kubelet.conf.d`) を使用します。
. フラグ`--kubelet-arg=$FLAG` を使用します。`$FLAG` は kubelet コンフィギュレーション・パラメーターです（例:`image-gc-high-threshold=100` ）。

kubelet CLI フラグと構成ファイルのドロップインを混在させる場合は、https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#kubelet-configuration-merging-order[の優先順位に]注意してください。
