= 埋め込みレジストリミラー
:page-languages: [en、ja、ko、zh]。
:revdate: 2026-01-05
:page-revdate: {revdate}

[IMPORTANT]
.バージョン・ゲート
====
Embedded Registry Mirrorは、2024年1月リリースのv1.26.13+k3s1、v1.27.10+k3s1、v1.28.6+k3s1、v1.29.1+k3s1、および2024年12月リリースのGA：v1.29.12+k3s1、v1.30.8+k3s1、v1.31.4+k3s1では実験的機能として利用可能です。
====

K3sはhttps://github.com/XenitAB/spegel[Spegelを]組み込み、Kubernetesクラスタ内のノード間でコンテナイメージをピアツーピアで共有できるステートレス分散OCIレジストリミラーです。分散レジストリのミラーはデフォルトでは無効になっている。K3sがこれを活用するには、以下のサブセクションで説明するように、xref:#_enabling_the_distributed_oci_registry_mirror[分散OCIレジストリミラーと] xref:#_enabling_registry_mirroring[レジストリミラーリングの]両方を有効にする必要があります。

[#_enabling_the_distributed_oci_registry_mirror]
== 分散OCIレジストリミラーの有効化

埋め込みレジストリミラーを有効にするには、サーバーノードを`--embedded-registry` フラグ、または設定ファイルに`embedded-registry: true` を指定して起動する必要があります。
このオプションは、クラスタ内のすべてのノードで使用する埋め込みミラーを有効にします。

クラスタレベルで有効にすると、すべてのノードはポート6443でローカルのOCIレジストリをホストし、ポート5001でピアツーピアネットワークを介して利用可能なイメージのリストを公開します。
どのノードのcontainerdイメージストアでも利用可能なイメージは、外部レジストリにアクセスすることなく、他のクラスタメンバーから引き出すことができる。
xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[air-gapイメージtarファイル]経由でインポートされたイメージは、利用可能な状態を維持し、Kubeletガベージコレクションによって刈り込まれないようにするため、containerdにpinされる。

ピアツーピアポートは、K3sサービスの環境変数`K3S_P2P_PORT` を設定することで、5001から変更できます。ポートはすべてのノードで同じ値に設定する必要があります。
ポートの変更はサポートされておらず、推奨されていません。

=== 必要条件

埋め込みレジストリのミラーリングが有効になっている場合、すべてのノードは、TCPポート5001と6443の内部IPアドレスを介して互いに到達できなければならない。
ノードが互いに到達できない場合、イメージのプルには時間がかかるかもしれません。なぜなら、他のエンドポイントにフォールバックする前に、containerdがまず分散レジストリを試すからです。

[#_enabling_registry_mirroring]
== レジストリのミラーリングを有効にする

レジストリのミラーリングを有効にすると、ノードはそのレジストリから他のノードからイメージを取得したり、レジストリのイメージを他のノードと共有したりできるようになります。
レジストリのミラーリングが有効なノードと無効なノードがある場合、そのレジストリが有効なノードだけがそのレジストリからイメージを交換します。

アップストリーム・コンテナ・レジストリからのイメージのミラーリングを有効にするには、ノードが`registries.yaml` の`mirrors` セクションにそのレジストリのエントリを持つ必要があります。
レジストリにエンドポイントが登録されている必要はない。
たとえば、`docker.io` と`registry.k8s.io` からのイメージの分散ミラーリングを有効にするには、すべてのクラスタノードで次の内容で`registries.yaml` を設定します：

[,yaml]
----
mirrors:
  docker.io:
  registry.k8s.io:
----

レジストリのミラー用エンドポイントも通常通り追加できる。
以下の構成では、イメージのプルはまず埋め込みミラーを試み、次に`mirror.example.com` 、最後に`docker.io` ：

[,yaml]
----
mirrors:
  docker.io:
    endpoint:
      - https://mirror.example.com
----

プライベートレジストリを、アップストリームレジストリのミラーとしてではなく、直接使用している場合、パブリックレジストリを有効にするのと同じ方法で、分散ミラーリングを有効にすることができます：

[,yaml]
----
mirrors:
  mirror.example.com:
----

[IMPORTANT]
.バージョン・ゲート
====
ワイルドカードのサポートは2024年3月のリリースで利用可能：v1.26.15+k3s1、v1.27.12+k3s1、v1.28.8+k3s1、v1.29.3+k3s1
====


`"*"` ワイルドカードミラーエントリーを使用して、すべてのレジストリーの分散ミラーリングを有効にすることができる。アスタリスクは必ず引用符で囲むこと：

[,yaml]
----
mirrors:
  "*":
----

ノード上でミラーリングのために有効になっているレジストリがない場合、そのノードはいかなる能力においても分散レジストリに参加しない。

`registries.yaml` ファイルの構造の詳細については、xref:installation/private-registry.adoc[プライベートレジストリ設定を]参照のこと。

=== デフォルトのエンドポイント・フォールバック

デフォルトでは、ミラーエンドポイントが設定されているレジストリからプルする場合、containerdはデフォルトのエンドポイントにフォールバックする。これを無効にし、設定されたミラーや埋め込みミラーからのみ画像を取り出したい場合は、プライベートレジストリ設定ドキュメントのxref:installation/private-registry.adoc#_default_endpoint_fallback[デフォルトエンドポイントフォールバックセクションを]参照してください。

`--disable-default-registry-endpoint` オプションを使用していて、特定のレジストリからの直接引き抜きを許可し、それ以外は許可しない場合は、エンドポイントを明示的に指定することで、画像の引き抜きをレジストリ自体にフォールバックさせることができることに注意してください：

[,yaml]
----
mirrors:
  docker.io:           # no default endpoint, pulls will fail if not available on a node
  registry.k8s.io:     # no default endpoint, pulls will fail if not available on a node
  mirror.example.com:  # explicit default endpoint, can pull from upstream if not available on a node
    endpoint:
      - https://mirror.example.com
----

=== 最新タグ

コンテナ・イメージにタグが指定されていない場合、暗黙のデフォルト・タグは`latest` です。このタグは頻繁に更新され、最新バージョンの画像を指すようになる。このタグは、引き出されるタイミングによって画像の異なるリビジョンを指すため、分散レジストリは他のノードから`latest` タグを*引き出さない*。このため、containerdは、`latest` タグが指すものの一貫性を確保するために、アップストリームレジストリまたはレジスト リミラーにアクセスすることになる。

これは、コンテナイメージに`latest` タグを使用した場合にKubernetesで観測されるhttps://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting[特別な`imagePullPolicy` デフォルトと]一致している。

K3sサービスの環境変数`K3S_P2P_ENABLE_LATEST=true` を設定することで、`latest` タグのミラーリングを有効にすることができます。
これはサポートされておらず、上述の理由から推奨されていない。

== セキュリティ

=== 認証

組み込みミラーのレジストリ API にアクセスするには、クラスタのクライアント認証局によって署名された有効なクライアント証明書が必要です。

分散ハッシュテーブルのピアツーピアネットワークへのアクセスには、サーバーノードが管理する共有鍵が必要である。
ノードは共有鍵とクラスタ認証局によって署名された証明書の両方を使用してお互いを認証します。

=== 潜在的な懸念

[CAUTION]
====
分散レジストリはピアツーピアの原則に基づいて構築され、すべてのクラスタ・メンバー間で等しいレベルの特権と信頼を前提としています。
これがクラスタのセキュリティ態勢と一致しない場合は、埋め込み分散レジストリを有効にすべきではありません。
====


埋め込みレジストリは、ノードが他の方法ではアクセスできないような画像を利用できるようにするかもしれない。
例えば、イメージの一部がKubernetes Image Pull Secretsや`registries.yaml` の認証情報を介して認証を必要とするレジストリ、プロジェクト、またはリポジトリからプルされている場合、分散レジストリは上流のレジストリに認証情報を提供することなく、他のノードがそれらのイメージを共有できるようにします。

あるノードでcontainerdイメージストアにイメージをプッシュするアクセス権を持つユーザは、これを使用して他のクラスタノードにイメージを「ポイズン（毒）」することができます。
画像の完全性が重要であれば、タグの代わりに画像ダイジェストを使うべきである。

== エアギャップまたは手動で読み込んだ画像の共有

画像共有はソースレジストリに基づいて制御される。
xref:installation/airgap.adoc#_tabs_1_manually_deploy_images_method[air-gap tarball を使って] containerd に直接ロードされたイメージ、xref:add-ons/import-images.adoc#_pre_import_images[事前にインポートされた]イメージ、または`ctr` コマンドラインツールを使って containerd のイメージストアに直接ロードされたイメージは、ミラーリングが有効になっているレジストリからのものとしてタグ付けされている場合、ノード間で共有されます。

イメージの出所と思われるアップストリームレジストリが実際に存在したり、到達可能であったりする必要はないことに注意してください。
例えば、イメージを架空のアップストリーム・レジストリのものであるとタグ付けし、そのイメージをcontainerdのイメージストアにインポートすることができる。
に登録されている限り、すべてのクラスタメンバーからこれらのイメージを引き出すことができます。 `registries.yaml`

== イメージを押し出す

埋め込みレジストリは読み取り専用で、`docker push` や、OCIレジストリとやりとりする他の一般的なツールを使って直接プッシュすることはできない。

画像は、`ctr -n k8s.io image pull` を実行して画像を取り込むか、`docker save` で作成した画像アーカイブを`ctr -n k8s.io image import` コマンドまたはxref:add-ons/import-images.adoc#_pre_import_images[事前インポート機能で]読み込むことで、埋め込みレジストリ経由で手動で利用できるようになります。
なお、`ctr` 経由で画像を管理する場合は、kubelet で画像を表示するために`k8s.io` ネームスペースを指定する必要があります。
