= サーバーロールの管理
:page-languages: [en、ja、ko、zh]。
:revdate: 2026-03-03
:page-revdate: {revdate}

`--cluster-init` 、K3sサーバーを起動すると、apiserver、controller-manager、scheduler、etcdを含むすべてのコントロールプレーンコンポーネントが実行される。コントロールプレーンとetcdの役割を別々のノードに分割するために、特定のコンポーネントを無効にすることができる。

[IMPORTANT]
====
このドキュメントは、埋め込みetcdを使用する場合にのみ関連する。組み込みetcdを使用しない場合、すべてのサーバーはコントロールプレーンの役割を持ち、コントロールプレーンのコンポーネントを実行する。
====


== `etcd` 専用ノード

`etcd` の役割のみを持つサーバーを作成するには、すべてのコントロールプレーンコンポーネントを無効にしてK3sを起動する：

----
curl -fL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server --cluster-init --disable-apiserver --disable-controller-manager --disable-scheduler
----
`INSTALL_K3S_ARTIFACT_URL` はhttps://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts のURL]。

この最初のノードがetcdを起動し、追加の`etcd` および/または`control-plane` ノードが参加するのを待つ。クラスタは、`control-plane` コンポーネントを有効にしたサーバーを追加参加させるまで使用できません。

== `control-plane` 専用ノード

[NOTE]
====
専用の`control-plane` ノードをクラスタの最初のサーバーにすることはできません。専用の`control-plane` ノードに参加する前に、`etcd` の役割を持つ既存のノードが存在する必要があります。
====


`control-plane` の役割のみを持つサーバーを作成するには、etcdを無効にしてk3sを起動する：

[,bash]
----
curl -fL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server --token <token> --disable-etcd --server https://<etcd-only-node>:6443
----

専用サーバーノードを作成すると、選択したロールが`kubectl get node` に表示されます：

[,bash]
----
$ kubectl get nodes
NAME           STATUS   ROLES                       AGE     VERSION
k3s-server-1   Ready    etcd                        5h39m   v1.20.4+k3s1
k3s-server-2   Ready    control-plane,master        5h39m   v1.20.4+k3s1
----

== 既存のサーバーにロールを追加する

既存の専用ノードにロールを追加するには、無効化フラグを削除してK3を再起動します。例えば、`etcd` 専用ノードに`control-plane` の役割を追加したい場合は、systemd ユニットまたは config ファイルから`--disable-apiserver --disable-controller-manager --disable-scheduler` フラグを削除し、サービスを再起動する。

== 設定ファイルの構文

他のすべてのCLIフラグと同様に、CLIフラグとしてオプションを渡す代わりに、xref:installation/configuration.adoc#_configuration_file[構成ファイルを]使用してコンポーネントを無効にすることができます。例えば、`etcd` 専用ノードを作成するには、`/etc/rancher/k3s/config.yaml` に以下の値を入れます：

[,yaml]
----
cluster-init: true
disable-apiserver: true
disable-controller-manager: true
disable-scheduler: true
----
