= Configuración de SUSE Observability para notificaciones por correo electrónico
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado

[CAUTION]
====
Los usuarios SaaS de SUSE Observability pueden utilizar notificaciones por correo electrónico sin necesidad de configuración adicional. Esta guía sólo es aplicable a instalaciones autoalojadas de SUSE Observability que tengan previsto utilizar el canal de notificación por correo electrónico.
====


Antes de poder utilizar el canal de notificación por correo electrónico en SUSE Observability, deberá seguir los pasos siguientes:

== Configurar SUSE Observability con la configuración SMTP

SUSE Observability debe configurarse con credenciales para conectarse al servidor SMTP. Puede hacerlo añadiendo lo siguiente al archivo `values.yaml` de su instalación de SUSE Observability:

[,yaml]
----
stackstate:
  email:
    enabled: true
    sender: "<stackstate@example.com>"
    server:
      host: "<smtp.example.com>"
      auth:
        username: "<user name>"
        password: "<user password>"
----

Esto utilizará el puerto `587` en el servidor SMTP y utiliza el comando `STARTTLS` para establecer una conexión segura. Estas son las demás opciones que se pueden personalizar:

[,yaml]
----
stackstate:
  email:
    additionalProperties:
      # Add needed Java email properties for your mail server (use string values), defaults are:
      "mail.smtp.auth": "true"
      "mail.smtp.starttls.enable": "true"
    server:
      protocol: smtp
      port: 587
----

=== Utilizar un secreto externo

Cuando el nombre de usuario y la contraseña no puedan proporcionarse en los valores, sino que deban proceder de un secreto externo, siga xref:/setup/security/external-secrets.adoc#_getting_username_and_password_for_email_sending_from_an_external_secret[estos pasos]
