include::partial$variables.adoc[]
= Introducción a Open Policy Agent
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aprenda cómo el Agente de Políticas Abiertas utiliza el lenguaje Rego para escribir políticas que evalúan y producen resultados para una toma de decisiones segura.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "open-policy-agent", "introduction"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "open policy agent", "opa", "rego"]
:sidebar_label: Introducción
:current-version: {page-origin-branch}

[NOTE]
====
A partir de estas versiones se ha introducido la compatibilidad con Open Policy Agent:

* kwctl: v0.2.0
* servidor de políticas: v0.2.0
====


Open Policy Agent (OPA) es un marco de políticas de propósito general que utiliza el lenguaje Rego para escribir políticas.

== Introducción

Las políticas de Rego funcionan recibiendo una entrada para evaluarla y produciendo una salida como respuesta.
En este sentido, OPA no dispone de herramientas específicas para la escritura de políticas para Kubernetes.

Específicamente, las políticas en OPA reciben una entrada JSON y producen una salida JSON.
El servidor OPA está configurado para recibir solicitudes de revisión de admisión de Kubernetes.
Las políticas reciben un objeto Kubernetes `+AdmissionReview+` en formato JSON.
Deben devolver un objeto `+AdmissionReview+` válido como resultado de la evaluación.

== Compatibilidad con las políticas existentes

Todas las políticas pueden compilarse en el destino `+wasm+` (WebAssembly) con la herramienta CLI oficial `+opa+`.

En cuanto a la ejecución de políticas, puede obtener más información sobre el xref:tutorials/writing-policies/rego/02-builtin-support.adoc[soporte integrado de OPA] implementado en {short-project-name}.
