= Gespeicherte Daten löschen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

Die Daten in SUSE Observability sind in vier verschiedene Gruppen unterteilt:

* Elasticsearch-Daten
* Kafka Thema Daten
* StackGraph-Daten
* Metrische Daten

Bei so vielen Daten, die gespeichert werden müssen, ist es wichtig, dass man die Möglichkeit hat, sie zu verwalten. In SUSE Observability ist standardmäßig eine 30-tägige Datenaufbewahrungsfrist festgelegt. Dies kann mithilfe der SUSE Observability CLI nach Ihren Bedürfnissen konfiguriert werden. Erfahren Sie mehr über die xref:/setup/data-management/data_retention.adoc[Datenaufbewahrung von SUSE Observability].

== Daten manuell löschen

Um gespeicherte Daten in SUSE Observability unter Kubernetes zu löschen, wird empfohlen, eine Neuinstallation durchzuführen:

. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_un_install_the_helm_chart[SUSE Observability deinstallieren]
. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_remaining_resources[Alle PVCs entfernen]
. Installieren Sie SUSE Observability erneut mit der gleichen Konfiguration wie zuvor auf xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Kubernetes] oder xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[OpenShift].
