= 認証オプション
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability セルフホスト

SUSE Observabilityは、インストール時にxref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[設定された]adminユーザとランダムパスワードによるxref:/setup/security/authentication/file.adoc[シングルパスワード認証で]設定されています。これは、サーバー上の単純な秘密を使ってユーザーを認証するものである。しかし、これは本番用のセットアップではない。

セキュリティを向上させるために、SUSE Observabilityは次の認証メカニズムのうち1つを使用するように設定できます(標準の管理ユーザを置き換えます)：

* xref:/setup/security/authentication/single_password.adoc[シングルパスワード]
* xref:/setup/security/authentication/file.adoc[ファイルベース]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[オープンIDコネクト（OIDC）]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak（OIDCの特殊版）]

[NOTE]
====
認証設定はHelmチャートの一部であり、変更があれば、それを必要とするポッドの再起動が自動的にトリガーされます。
====


== ユーザーの役割

ユーザが認証されると、そのユーザの権限は通常、そのユーザが持つロールに基づいて割り当てられる。特定の認証メカニズムのドキュメントには、外部システムのロールまたはグループをSUSE Observabilityの4つの標準ロールにマッピングする方法の例も記載されています：

* *ゲスト*- 情報を見ることはできるが、変更はできない。
* *Kubernetes Troubleshooter*- すべての情報を見ることができ、モニターやメトリックの設定を見たり変更したりできる。
* *パワーユーザー*- すべての設定を確認、変更し、StackPacksをインストールすることができます。
* *管理者*- SUSE Observabilityの内容を確認および変更できます。例えば、すべての設定の確認、StackPacksのインストール、ユーザー権限の付与と取り消し、（新しいバージョンの）StackPacksのアップロードなどです。

ユーザーに割り当てるロールを決定する際には、プラットフォーム管理者と管理者のみを少人数で構成することを強くお勧めします。たとえば、SUSE Observabilityのインストールと初期設定を担当するエンジニアのみ。管理者ユーザは、SUSE Observabilityへのアクセスを管理し、使用できるStackPackを決定できます。StackPacksのインストールやその他の設定の微調整を、Power Userロールを持つより多くのユーザーに委任することができます。プラットフォーム管理者ユーザーは、データベースのクリア、データ保持設定の変更、ログの表示、その他のプラットフォーム管理タスクを実行できます。

さらにロールを追加することも可能です。xref:/setup/security/rbac/rbac_roles.adoc[「ロール（RBAC）」の]ページや、その他のxref:/setup/security/rbac/README.adoc[RBACドキュメントのページを]参照してください。
