= CLI: sts
:revdate: 2025-07-29
:page-revdate: {revdate}
:description: {stackstate-product-name}

== Visão geral

A CLI do {stackstate-product-name} `+sts+` oferece acesso fácil à funcionalidade fornecida pelas APIs do {stackstate-product-name}. Ele pode ser usado para automação usando dados do {stackstate-product-name}, para configurar o {stackstate-product-name} e para desenvolver StackPacks.

== Pré-requisitos

* **{stackstate-product-name} URL** - O URL da sua instância {stackstate-product-name} (o mesmo URL usado para acessar a interface da Web).
* **Token de API** - Um token de API válido para autenticação, que pode ser recuperado na página *da CLI* em sua instância {stackstate-product-name}.

Para obter seu token de API:

. Faça login em sua instância {stackstate-product-name}.
. Navegue até o *menu principal* > *CLI*.
. Copie o token de API exibido na página.

== Início rápido

A maneira mais rápida de instalar e configurar a CLI do `+sts+` é usar os comandos pré-preenchidos disponíveis em sua instância do {stackstate-product-name}:

. Faça login em sua instância {stackstate-product-name}.
. Navegue até o *menu principal* > *CLI*.
. Copie o comando para seu sistema operacional e execute-o em um terminal.

Esses comandos são pré-preenchidos com o URL e o token de API corretos para sua instância específica do {stackstate-product-name}, tornando a instalação e a configuração uma única etapa.

== Faça o download da CLI

[tabs]
====
Windows::
+
--
Abra um terminal *do Powershell* (versão 5.1 ou posterior) e execute as etapas abaixo. Isso pode ser feito em uma etapa de cada vez ou em um único script. Após a instalação, o comando `+sts+` estará disponível para o usuário atual no terminal do Powershell e no prompt de comando (cmd.exe).

. Defina a versão de origem e o caminho de destino para a CLI:
+
[,powershell]
----
$CLI_PATH = $env:USERPROFILE +"\stackstate-cli"
If (!(test-path $CLI_PATH)) { md $CLI_PATH }
Invoke-WebRequest https://dl.stackstate.com/stackstate-cli/LATEST_VERSION -OutFile $CLI_PATH\VERSION
$VERSION=type $CLI_PATH\VERSION
$VERSION=$VERSION -replace "[v]"
$CLI_DL = "https://dl.stackstate.com/stackstate-cli/v$VERSION/stackstate-cli-$VERSION.windows-x86_64.zip"
echo "Installing {stackstate-product-name} CLI v$VERSION to: $CLI_PATH"
----

. Faça o download e descompacte a CLI no caminho da CLI de destino. Remova os artefatos restantes:
+
[,powershell]
----
Invoke-WebRequest $CLI_DL -OutFile $CLI_PATH\stackstate-cli.zip
Expand-Archive -Path "$CLI_PATH\stackstate-cli.zip" -DestinationPath $CLI_PATH -Force
rm $CLI_PATH\stackstate-cli.zip, $CLI_PATH\VERSION
----

. Registre o caminho da CLI no PATH do usuário atual. Isso tornará o comando `+sts+` disponível em todos os lugares:
+
[,powershell]
----
$PATH = (Get-ItemProperty -Path "Registry::HKEY_CURRENT_USER\Environment" -Name PATH).Path
if ( $PATH -notlike "*$CLI_PATH*" ) {
  $PATH = "$PATH;$CLI_PATH"
  (Set-ItemProperty -Path "Registry::HKEY_CURRENT_USER\Environment" -Name PATH –Value $PATH)
  $MACHINE_PATH = (Get-ItemProperty -Path "Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment" -Name PATH).path
  $env:Path = "$PATH;$MACHINE_PATH"
}
----

. Verifique se a CLI funciona:
+
[,powershell]
----
sts version
----
--

macOS::
+
--
Abra um terminal e execute as etapas abaixo. Isso pode ser feito em uma etapa de cada vez ou em um único script. Após a instalação, o comando `+sts+` estará disponível para o usuário atual.

. Faça o download da versão mais recente da CLI para x86_64 (Intel) ou arm64 (M1).
+
[,bash]
----
(VERSION=`+curl https://dl.stackstate.com/stackstate-cli/LATEST_VERSION+` &&
  VERSION=${VERSION#v} &&
  ARCH=`+uname -m+` &&
  curl https://dl.stackstate.com/stackstate-cli/v$VERSION/stackstate-cli-$VERSION.darwin-$ARCH.tar.gz | tar xz --directory /usr/local/bin)
----

. Verifique se a CLI funciona:
+
[,bash]
----
sts version
----
--

Linux::
+
--
Abra um terminal e execute as etapas abaixo. Isso pode ser feito em uma etapa de cada vez ou em um único script. Após a instalação, o comando `+sts+` estará disponível para o usuário atual.

. Faça o download e descompacte a versão mais recente para x86_64:
+
[,bash]
----
(VERSION=`+curl https://dl.stackstate.com/stackstate-cli/LATEST_VERSION+` && VERSION=${VERSION#v} &&
curl https://dl.stackstate.com/stackstate-cli/v$VERSION/stackstate-cli-$VERSION.linux-x86_64.tar.gz | tar xz --directory /usr/local/bin)
----

. Verifique se a CLI funciona:
+
[,bash]
----
sts version
----
--

Docker::
+
--
Para executar a versão mais recente da CLI usando o Docker, execute:

[,bash]
----
docker run stackstate/stackstate-cli2
----

Como alternativa, acesse a página *da CLI* na interface do usuário {stackstate-product-name} e copie o comando de *instalação rápida* do *Docker* - ele é pré-preenchido com os endereços corretos `+<URL>+` e `+<API-TOKEN>+` necessários para configurar a CLI para sua instância {stackstate-product-name}.

Agora você pode executar comandos da CLI anexando-os ao final do comando `+docker run+` (por exemplo, `+docker run stackstate/stackstate-cli2 version+`).
--
====

== Configurar a CLI

=== Autenticação

==== Token de API

Por padrão, a CLI será autenticada usando o token de API que você forneceu quando a configuração da CLI foi salva.

[CAUTION]
====
A maneira mais segura de usar seu token de API é por meio de uma variável de ambiente. Você pode armazenar o token da API com um gerenciador de segredos e injetá-lo como uma variável de ambiente em seu shell.
====

[tabs]
====
Windows / macOS / Linux::
+
--
. Na interface do usuário {stackstate-product-name}, vá para *Main menu* > *CLI* e copie seu token de API.
. Execute o comando abaixo, em que `+<URL>+` é o URL da sua instância {stackstate-product-name} e `+<API-TOKEN>+` é o token de API que você copiou da página da CLI na interface do usuário {stackstate-product-name}:
+
[,bash]
----
sts context save --name <NAME> --url <URL> --api-token <API-TOKEN>
----

. A conexão com sua instância {stackstate-product-name} será testada e um arquivo de configuração será armazenado em `+~/.config/stackstate-cli/config.yaml+`.
--

Docker::
+
--
A versão Docker da CLI não pode ser configurada com um arquivo de configuração. Especifique a configuração de sua instância do {stackstate-product-name} usando variáveis de ambiente e passe-as para o Docker:

* `+STS_CLI_URL+` - o URL de sua instância {stackstate-product-name}.
* `+STS_CLI_API_TOKEN+` - o token de API obtido na página {stackstate-product-name} UI *Main menu* > *CLI*.
* `+STS_CA_CERT_PATH+` - caminho para um arquivo de certificado CA codificado em PEM para servidores que usam certificados autoassinados. O diretório que contém o certificado deve ser montado no contêiner do Docker.
* `+STS_CA_CERT_BASE64_DATA+` - dados de certificado CA codificados em base64 para servidores que usam certificados autoassinados (ignorados se `+STS_CA_CERT_PATH+` for especificado).
* `+STS_SKIP_SSL+` - desativa a validação do certificado SSL (ignora as configurações do certificado, use com cuidado).

Por exemplo:

[,bash]
----
docker run \
   -v /path/to/certs:/certs \
   -e STS_CLI_URL \
   -e STS_CLI_API_TOKEN \
   -e STS_CA_CERT_PATH=/certs/ca.crt \
   stackstate/stackstate-cli2 settings list --type Layer
----
--
====

==== Tokens de serviço

Opcionalmente, você pode usar a CLI para criar um ou mais tokens de serviço para autenticação com as APIs {stackstate-product-name} Base e Admin. Por exemplo, um token de serviço pode ser usado para autenticação em cenários de CI (Integração Contínua) em que nenhum usuário real está realizando as operações na instância {stackstate-product-name}.

Para criar um token de serviço, execute o comando abaixo:

[,bash]
----
sts service-token create --name <NAME> --roles <ROLE(s)> [--expiration <yyyy-MM-dd>]
----

Isso criará um novo token de serviço e o imprimirá. O parâmetro `+--expiration+` é opcional e pode ser usado para definir a data de expiração do token de serviço.

Depois de obter isso, você pode configurar a CLI para usá-lo:

[,bash]
----
sts context save --name <NAME> --service-token <TOKEN> --url <URL>
----

=== Gerenciar vários contextos

A CLI do `+sts+` oferece suporte à configuração e ao gerenciamento de diferentes contextos (de autenticação). Isso permite alternar facilmente entre um usuário administrativo e um usuário comum, ou alternar entre diferentes instâncias do {stackstate-product-name}. Por exemplo, você pode usar um contexto diferente para uma instância de teste e de produção do site {stackstate-product-name}. Você pode listar, salvar, excluir, definir e validar contextos na CLI do `+sts+`. Execute `+sts context -h+` para obter detalhes sobre os comandos disponíveis e sua utilização.

=== Opções de configuração

Você não precisa de um arquivo de configuração para executar a CLI do `+sts+`. Você também pode configurar a CLI por meio de uma combinação de variáveis de ambiente e sinalizadores.

Se vários tipos de configuração forem apresentados à CLI, a ordem de processamento será a seguinte:

. Bandeiras
. Variáveis de ambiente
. Arquivo de configuração

|===
| Variável de ambiente | Flag | Descrição

| `+STS_CLI_URL+`
| `+--url+`
| URL para sua instância {stackstate-product-name}.

| `+STS_CLI_API_TOKEN+`
| `+--api-token+`
| token de API para sua instância {stackstate-product-name}. A maneira mais segura de usar seu token de API é por meio de uma variável de ambiente. Você pode armazenar o token da API com um gerenciador de segredos e injetá-lo como uma variável de ambiente em seu shell.

| `+STS_CLI_SERVICE_TOKEN+`
| `+--service-token+`
| Um token de serviço para sua instância {stackstate-product-name}. A maneira mais segura de usar seu token de serviço é por meio de uma variável de ambiente. Você pode armazenar o token de serviço com um gerenciador de segredos e injetá-lo como uma variável de ambiente em seu shell.

| `+STS_CA_CERT_PATH+`
| `+--ca-cert-path+`
| Caminho para um arquivo de certificado de CA codificado em PEM para servidores que usam certificados autoassinados ou certificados de uma CA privada.

| `+STS_CA_CERT_BASE64_DATA+`
| `+--ca-cert-base64-data+`
| Dados de certificado de CA codificados em base64 para servidores que usam certificados autoassinados ou certificados de uma CA privada. Ignorado se `+STS_CA_CERT_PATH+` for especificado.

| `+STS_SKIP_SSL+`
| `+--skip-ssl+`
| Desativa a validação do certificado SSL. Quando definido como `+true+`, a CLI não validará os certificados SSL e ignorará as configurações `+STS_CA_CERT_PATH+` e `+STS_CA_CERT_BASE64_DATA+`. Use com cuidado, pois isso reduz a segurança.

| `+STS_CLI_API_PATH+`
| n/a
| O caminho anexado ao final do URL para obter o ponto de extremidade da API. (O padrão é `+/api+`)

| `+STS_CLI_CONTEXT+`
| `+--context+`
| O nome do contexto a ser usado.
|===

Além de substituir partes específicas do arquivo de configuração, também é possível substituir o local padrão do arquivo de configuração. Isso é feito por meio do sinalizador `+--config <PATH>+`.

== Comandos disponíveis

A CLI do `+sts+` fornece os seguintes comandos de nível superior:

|===
| Comando | Descrição

| agente
| Gerenciar {stackstate-product-name} agentes

| conclusão
| Gerar scripts de autocompletar para shells

| contexto
| Gerenciar os contextos e as configurações da CLI

| painel de controle
| Gerenciar painéis

| saúde
| Comandos relacionados à sincronização de saúde

| licença
| Gerenciar informações de licença do {stackstate-product-name} 

| monitor
| Gerenciar monitores e configurações de monitoramento

ifdef::ss-ff-stackpacks2_enabled[]
| otel-component-mapping*
| Gerenciar mapeamentos de componentes do OpenTelemetry

| mapeamento de relações de hotéis*
| Gerenciar mapeamentos de relações OpenTelemetry
endif::ss-ff-stackpacks2_enabled[]

| rbac
| Gerenciar o RBAC

| service-token
| Gerenciar tokens de serviço.

| configurações
| Gerenciar definições e configurações da instância

| mochila
| Gerenciar e carregar StackPacks

| tópico
| Gerenciar tópicos do Kafka

| sincronização de topologia
| Gerenciar a sincronização da topologia

| sessão de usuário
| Inspecionar sessões de usuário

| versão
| Exibir informações sobre a versão
|===

ifdef::ss-ff-stackpacks2_enabled[]
{empty}* Comandos experimentais que exigem a ativação da variável de ambiente `+STS_EXPERIMENTAL_OTEL_MAPPING=true+`.

Exemplo de uso:

[,bash]
----
STS_EXPERIMENTAL_OTEL_MAPPING=true sts otel-component-mapping --help
----
endif::ss-ff-stackpacks2_enabled[]

Todos os comandos aceitam o sinalizador `+--help+`, que documenta o uso de cada comando.

Para obter informações detalhadas sobre qualquer comando e seus subcomandos, execute:

[,bash]
----
sts [command] --help
----

== Atualização

Para atualizar para a versão mais recente da CLI do `+sts+`, <<_quick_start, execute o comando de instalação novamente>>.

Você pode verificar a versão da CLI do `+sts+` que está sendo executada no momento com o comando `+sts version+`.

== Desinstalação

[tabs]
====
Windows::
+
--
[discrete]
=== Desinstalação rápida

Abra um terminal *do Powershell* e execute:

[,powershell]
----
. { iwr -useb https://dl.stackstate.com/stackstate-cli/install.ps1 } | iex; uninstall
----

A CLI do `+sts+` e todas as configurações associadas são agora removidas para o usuário atual.

[discrete]
=== Desinstalação manual

Abra um terminal *do Powershell* e execute cada etapa uma a uma ou todas de uma vez. A CLI do `+sts+` e todas as configurações associadas serão removidas para o usuário atual.

. Remover binário:
+
[,powershell]
----
$CLI_PATH = $env:USERPROFILE+"\stackstate-cli"
rm -R $CLI_PATH 2>1  > $null
----

. Remover configuração:
+
[,powershell]
----
rm -R $env:USERPROFILE+"\.config\stackstate-cli" 2>1  > $null
----

. Remova a CLI do caminho do ambiente:
+
[,powershell]
----
$PATH = (Get-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Environment' -Name PATH).Path
$i = $PATH.IndexOf(";$CLI_PATH")
if ($i -ne -1) {
  $PATH = $PATH.Remove($i, $CLI_PATH.Length+1)
  (Set-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Environment' -Name PATH –Value $PATH)
}
----
--

macOS::
+
--
[discrete]
=== Desinstalação rápida

Abra um terminal e execute:

[,bash]
----
curl -o- https://dl.stackstate.com/stackstate-cli/uninstall.sh | bash
----

A CLI do `+sts+` e todas as configurações associadas são agora removidas para o usuário atual.

[discrete]
=== Desinstalação manual

. Abra um terminal.
. Para remover a CLI do `+sts+`, execute o comando:
+
[,bash]
----
rm -r /usr/local/bin/sts
----

. Para remover a configuração da CLI do `+sts+`, execute o comando:
+
[,bash]
----
rm -r ~/.config/stackstate-cli
----

A CLI do `+sts+` e todas as configurações associadas são agora removidas para o usuário atual.
--

Linux::
+
--
[discrete]
=== Desinstalação rápida

Abra um terminal e execute:

[,bash]
----
curl -o- https://dl.stackstate.com/stackstate-cli/uninstall.sh | bash
----

A CLI do `+sts+` e todas as configurações associadas são agora removidas para o usuário atual.

[discrete]
=== Desinstalação manual

. Abra um terminal.
. Para remover a CLI do `+sts+`, execute o comando:
+
[,bash]
----
rm -r /usr/local/bin/sts
----

. Para remover a configuração da CLI do `+sts+`, execute o comando:
+
[,bash]
----
rm -r ~/.config/stackstate-cli
----

A CLI do `+sts+` e todas as configurações associadas são agora removidas para o usuário atual.
--

Docker::
+
--
Para remover a imagem da CLI e os contêineres, execute:

[,bash]
----
docker rmi -f stackstate/stackstate-cli2
----
--
====

== Código aberto

A CLI do {stackstate-product-name} `+sts+` é de código aberto e pode ser encontrada no GitHub em:

* https://github.com/stackvista/stackstate-cli
