ifdef::ss-ff-stackpacks2_enabled[]
= Schema und Referenz für metrische Bindungen
:revdate: 2026-01-09
:page-revdate: {revdate}
:description: SUSE Observabilität

== Übersicht

Auf dieser Seite werden die Schemata für eine `+MetricBinding+` beschrieben, zusammen mit ausführlichen Erläuterungen zu Konstrukten, Ausdruckssyntax und Semantik.

== Schema für die metrische Bindung

Jede metrische Bindung:

* Wählt Komponenten aus, auf die es angewendet werden kann
* Definiert PromQL-Abfragevorlagen zum Abrufen von Daten
* Gibt an, wie die resultierenden Daten gerendert werden müssen
* Enthält Layout-Hinweise zur Auswahl einer geeigneten Stelle in der Benutzeroberfläche für die Anzeige des Diagramms

[,yaml]
----
_type: "MetricBinding"
name: string
chartType: "line"                     # "line" is the only type for now
unit?: string
scope: string                         # Topology scope - components to bind to
enabled: boolean                      # default: true
description?: string
valuation?: "higher-is-better" | "lower-is-better"
priority?: "HIGH" | "MEDIUM" | "LOW" | "NONE"    # deprecated
queries:
  - _type: "MetricBindingQuery"
    expression: string                # promql query
    alias: string                     # name in legend
    componentIdentifierTemplate?: string    # URN template for linking
    primary?: boolean                 # is this query the primary one
tags:
  <key>: <value>
layout?:                              # where should chart be shown
  metricPerspective?:                 # the metrics perspective for a component
    tab: string
    section: string
    weight?: integer
  componentHighlight?:                # highlight perspective of a component
    section: string
    weight?: integer
  componentSummary?:                  # summary - supporting panel on the right
    weight?: integer
identifier?: string
----

* `+_type+`{stackstate-product-name} muss wissen, dass es sich um eine metrische Bindung handelt, daher muss der Wert immer `+MetricBinding+`
* `+name+`: Der Name für die metrische Bindung
* `+chartType+`{stackstate-product-name} wird verschiedene Diagrammtypen unterstützen (`+line+`, `+bar+`, etc.), derzeit wird nur `+line+` unterstützt
* `+unit+`: Die Einheit der Werte in der von der/den Abfrage(n) zurückgegebenen Zeitreihe, die für die Darstellung der Y-Achse des Diagramms verwendet wird. Siehe die Referenz der xref:/develop/reference/k8sTs-chart-units.adoc[unterstützten Einheiten] für alle Einheiten
* `+scope+`: Der Topologiebereich der metrischen Bindung, eine Topologieabfrage, die die Komponenten auswählt, für die diese metrische Bindung angezeigt werden soll
* `+enabled+`: Setzen Sie den Wert auf `+false+`, um die metrische Bindung beizubehalten, sie aber den Benutzern nicht anzuzeigen.
* `+description+`: Optionale Beschreibung, die über dem Namen angezeigt wird
* `+valuation+`: Ob höhere oder niedrigere Werte "besser" sind
* `+priority+`: [Veraltet] Eines von `+HIGH+`, `+MEDIUM+`, oder `+LOW+`. Hauptsortierreihenfolge für Metriken einer Komponente (in der Reihenfolge, in der sie hier aufgeführt sind), sekundäre Sortierreihenfolge ist die `+name+`.
* `+queries+`: Eine Liste von Abfragen, die im Diagramm für die Metrikbindung angezeigt werden sollen (siehe xref:/setup/custom-integrations/metric-bindings/writing-promql.adoc[Schreiben von PromQL-Abfragen])
** `+expression+`: Die (vorgefertigte) promql-Abfrage
** `+alias+`: Name für die Abfrage in der Legende
** `+componentIdentifierTemplate+`: Vorlage für den Bezeichner der zugehörigen Komponente, gefüllt mit den Bezeichnungen der Zeitreihen, die sich aus der Abfrage ergeben
** `+primary+`: Ist diese Anfrage die wichtigste?
* `+tags+`: Wird verwendet, um die Metriken in der Benutzeroberfläche zu organisieren, kann leer gelassen werden, indem `+{}+`
* `+layout+`: Gruppierung von Diagrammen in verschiedenen Perspektiven, z. B. in der xref:/use/views/k8s-metrics-perspective.adoc[Metrik-Perspektive]
** `+metricPerspective+` - Definiert die Metriken, die auf `+Metrics Perspective+` angezeigt werden sollen. Die Metriken sind in Registerkarten und dann in Abschnitte gruppiert.
*** `+tab+` - Tab-Name. Registerkarten sind alphabetisch sortiert
*** `+section+` - Name der Sektion. Die Abschnitte sind alphabetisch geordnet
*** `+weight+` - Metriken innerhalb eines Abschnitts werden in erster Linie nach Gewicht (aufsteigend) und in zweiter Linie nach Namen (alphabetisch) sortiert.
** `+componentHighlight+` - Definiert die Metriken, die auf `+Component Highlight+` angezeigt werden sollen. Die Metriken sind in Abschnitten gruppiert.
*** `+section+` - Name der Sektion. Die Abschnitte sind alphabetisch geordnet
*** `+weight+` - Metriken innerhalb eines Abschnitts werden in erster Linie nach Gewicht (aufsteigend) und in zweiter Linie nach Namen (alphabetisch) sortiert.
** `+componentSummary+` - Legt die Metriken fest, die bei Auswahl einer Komponente in der Seitenleiste von `+Components details+` angezeigt werden. Diagramme erscheinen nur, wenn diese Eigenschaft definiert ist.
*** `+weight+` - Dies stellt das Gewicht der Karte dar. Die Diagramme werden in aufsteigender Reihenfolge nach Gewicht sortiert und zeigen dann die ersten drei Diagramme an.
* `+identifier+`: Ein URN (Universal Resource Identifier), der als eindeutiger Bezeichner der Metrikbindung verwendet wird. Er muss mit `+urn:stackpack:<stackpack-name>:metric-binding:+` beginnen, der Rest ist frei wählbar, solange er unter allen metrischen Bindungen eindeutig ist.

endif::ss-ff-stackpacks2_enabled[]
