= Detener los K3
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-26
:page-revdate: {revdate}

Para permitir una alta disponibilidad durante las actualizaciones, los contenedores K3s siguen funcionando cuando se detiene el servicio K3s.

== Servicio K3s

Detener y reiniciar K3s es soportado por el script de instalación para systemd y OpenRC.

[tabs]
======
systemd::
+
--
Para detener servidores:

[,sh]
----
sudo systemctl stop k3s
----

Para reiniciar servidores:

[,sh]
----
sudo systemctl start k3s
----

Para detener a los agentes:

[,sh]
----
sudo systemctl stop k3s-agent
----

Para reiniciar los agentes:

[,sh]
----
sudo systemctl start k3s-agent
----
--

OpenRC::
+
--
Para detener servidores:

[,sh]
----
sudo rc-service k3s stop
----

Para reiniciar servidores:

[,sh]
----
sudo rc-service k3s restart
----

Para detener a los agentes:

[,sh]
----
sudo rc-service k3s-agent stop
----

Para reiniciar los agentes:

[,sh]
----
sudo rc-service k3s-agent restart
----
--
======

== Guión Killall

Para detener todos los contenedores K3s y restablecer el estado containerd, se puede utilizar el script `+k3s-killall.sh+`.

El script killall limpia los contenedores, los directorios K3s y los componentes de red a la vez que elimina la cadena iptables con todas las reglas asociadas. Los datos del clúster no se borrarán.

Para ejecutar el script killall desde un nodo servidor, ejecute:

[,bash]
----
/usr/local/bin/k3s-killall.sh
----
