include::partial$variables.adoc[]
= ポリシー設定の定義
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: settings.goファイルのコードを修正して、正規表現をマーシャリングおよびアンマーシャリングするカスタム関数の実装を含む、ポリシー設定を定義する。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "go", "defining-policy-settings"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"ポリシー設定の定義"、"Go"]]。
:sidebar_label: ポリシー設定の定義
:sidebar_position: 24
:current-version: {page-origin-branch}

まず、ポリシー設定を保持する構造を定義する必要があります。

これは、`settings.go` ファイル（ローカル版の Go ポリシー テンプレート）のコードを変更することで行います。
`import` セクションに2行追加し、`Settings` 構造を変更し、`RegularExpression` 構造を追加する必要がある。

以下のコードと一致するはずだ：

[,go]
----
import (
    "encoding/json"
    "fmt"
    "regexp"

    mapset "github.com/deckarep/golang-set/v2"
    kubewarden "github.com/kubewarden/policy-sdk-go"
    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
)

type Settings struct {
    DeniedLabels      mapset.Set[string]            `json:"denied_labels"`
    ConstrainedLabels map[string]*RegularExpression `json:"constrained_labels"`
}

type RegularExpression struct {
    *regexp.Regexp
}
----

[NOTE]
====
`DeniedNames` は、`settings.go` で定義されている`Settings` 構造ではもはや必要ない。

`DeniedNames` はもう定義されていないので、`settings.go` の関数`IsNameDefined` も削除する必要がある。
また、`settings_test.go`,`TestIsNameDenied` でこの関数を参照している関数も削除する必要がある。
====


正規表現オブジェクトを扱うために`regexp` パッケージを使用し、拒否されたラベルのリストを格納するためにhttps://github.com/deckarep/golang-set[`mapset.Set`]型を使用しています。

`regexp.Regexp` はデシリアライズを処理しないので、正規表現のマーシャリングとアンマーシャリングを処理するカスタム関数を定義する必要があります：

[,go]
----
// UnmarshalText satisfies the encoding.TextMarshaler interface,
// also used by json.Unmarshal.
func (r *RegularExpression) UnmarshalText(text []byte) error {
    nativeRegExp, err := regexp.Compile(string(text))
    if err != nil {
        return err
    }
    r.Regexp = nativeRegExp
    return nil
}

// MarshalText satisfies the encoding.TextMarshaler interface,
// also used by json.Marshal.
func (r *RegularExpression) MarshalText() ([]byte, error) {
    if r.Regexp != nil {
        return []byte(r.Regexp.String()), nil
    }

    return nil, nil
}
----

また、`Settings` 構造体のデシリアライズを処理するには、`UnmarshalJSON` メソッドが必要である：

[,go]
----
func (s *Settings) UnmarshalJSON(data []byte) error {
    rawSettings := struct {
        DeniedLabels      []string          `json:"denied_labels"`
        ConstrainedLabels map[string]*RegularExpression `json:"constrained_labels"`
    }{}

    err := json.Unmarshal(data, &rawSettings)
    if err != nil {
        return err
    }

    s.DeniedLabels = mapset.NewThreadUnsafeSet[string](rawSettings.DeniedLabels...)
    s.ConstrainedLabels = rawSettings.ConstrainedLabels

    return nil
}
----

== `Settings` インスタンスの構築

{short-project-name} ポリシーは、ポリシー設定を入力として受け取る2つの異なる関数を公開する：

* `validate`:Kubernetesオブジェクトがポリシーによる検証を必要とする場合にこの関数を使用します。
設定はhttps://pkg.go.dev/github.com/kubewarden/policy-sdk-go@v0.2.1/protocol#ValidationRequest[`ValidationRequest`]オブジェクトの一部です。
* `validate_settings`:ポリシーが{short-project-name} によって最初にロードされるときに、この関数を呼び出します。
この関数は、ポリシー設定を入力として受け取り、有効性をチェックする。

JSONペイロードから`Settings` オブジェクトを作成するヘルパー関数を作成する必要があります：

[,go]
----
func NewSettingsFromValidationReq(validationReq *kubewarden_protocol.ValidationRequest) (Settings, error) {
    settings := Settings{}
    err := json.Unmarshal(validationReq.Settings, &settings)
    if err != nil {
        return Settings{}, err
    }

    return settings, nil
}
----

[NOTE]
====
すべての`mapset.Set` オブジェクトは、https://pkg.go.dev/github.com/deckarep/golang-set?utm_source=godoc#NewThreadUnsafeSet[スレッドセーフでないバリアントを]使用して作成されます。
WebAssemblyコードはシングルスレッドで実行されるため、同時実行の問題はありません。

WebAssembly標準はまだスレッドをカバーしていない。
詳細はhttps://github.com/WebAssembly/threads[公式プロポーザルを]参照。
====


== `Settings` バリデーションの実装

すべての{short-project-name} ポリシーは、設定の検証を実装しなければならない。

そのためには、`Settings` インスタンスに`Valid` メソッドを追加する：

[,go]
----
func (s *Settings) Valid() (bool, error) {
    constrainedLabels := mapset.NewThreadUnsafeSet[string]()

    for label := range s.ConstrainedLabels {
        constrainedLabels.Add(label)
    }

    constrainedAndDenied := constrainedLabels.Intersect(s.DeniedLabels)
    if constrainedAndDenied.Cardinality() != 0 {
        return false,
            fmt.Errorf("These labels cannot be constrained and denied at the same time: %v", constrainedAndDenied)
    }

    return true, nil
}
----

`Valid` 、"拒否された "ラベルが "制約された "マップに含まれないことを保証する。
`mapset.Set` が提供する`Intersect` メソッドを使用すると、チェックが簡単になる。

[NOTE]
====
`Valid` メソッド呼び出しは、すでにインスタンス化された`Setting` オブジェクトに対して行われる。
これは、ユーザーによって提供された正規表現の検証が、`Settings` unmarshalerですでに行われたことを意味する。
====


最後に、足場が提供する`validateSettings` 関数を以下のように変更する必要がある：

[,go]
----
func validateSettings(payload []byte) ([]byte, error) {
    settings := Settings{}
    err := json.Unmarshal(payload, &settings)
    if err != nil {
        return kubewarden.RejectSettings(
            kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
    }

    valid, err := settings.Valid()
    if valid {
        return kubewarden.AcceptSettings()
    }

    return kubewarden.RejectSettings(
        kubewarden.Message(fmt.Sprintf("Provided settings are not valid: %v", err)))
}
----

この関数はhttps://github.com/kubewarden/policy-sdk-go[{short-project-name} のSDKが]提供するヘルパー関数を利用していることがわかる。

== 設定コードのテスト

書いたコードのテスト・カバレッジを良くすることは重要だ。
あなたが使っているコードには、雛形から、`settings_test.go` ファイルに定義された一連のユニットテストが付属しています。

`Settings` クラスの新しい動作を反映させるために、このファイルの内容を変更しなければならない。

使用しているGoパッケージを含める：

[,go]
----
import (
    "testing"

    "encoding/json"

    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
)
----

まずは、`ValidationRequest` オブジェクトから`Settings`インスタンスを代入できることを確認するユニットテストを書くことから始めましょう：

[,go]
----
func TestParseValidSettings(t *testing.T) {
    settingsJSON := []byte(`
        {
            "denied_labels": [ "foo", "bar" ],
            "constrained_labels": {
                    "cost-center": "cc-\\d+"
            }
        }`)

    settings := Settings{}
    err := json.Unmarshal(settingsJSON, &settings)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    expected_denied_labels := []string{"foo", "bar"}
    for _, exp := range expected_denied_labels {
        if !settings.DeniedLabels.Contains(exp) {
            t.Errorf("Missing value %s", exp)
        }
    }

    re, found := settings.ConstrainedLabels["cost-center"]
    if !found {
        t.Error("Didn't find the expected constrained label")
    }

    expected_regexp := `cc-\d+`
    if re.String() != expected_regexp {
        t.Errorf("Expected regexp to be %v - got %v instead",
            expected_regexp, re.String())
    }
}
----

次に、ユーザーが壊れた正規表現を提供したときに、`Settings` インスタンスが生成されないことをチェックするテストが必要です：

[,go]
----
func TestParseSettingsWithInvalidRegexp(t *testing.T) {
    settingsJSON := []byte(`
        {
            "denied_labels": [ "foo", "bar" ],
            "constrained_labels": {
                    "cost-center": "cc-[a+"
            }
        }`)

    err := json.Unmarshal(settingsJSON, &Settings{})
    if err == nil {
        t.Errorf("Didn't get expected error")
    }
}
----

これで、`validate_settings` エントリ・ポイントの動作をチェックするテストを定義できる。

`validateSettings` 関数から返された`SettingsValidationResponse` オブジェクトを見る：

[,go]
----
func TestDetectValidSettings(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar" ],
        "constrained_labels": {
            "cost-center": "cc-\\d+"
        }
    }`)

    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if !response.Valid {
        t.Errorf("Expected settings to be valid: %s", *response.Message)
    }
}
----

最後に、`validateSettings` 関数が正しいメッセージとともに無効な設定を拒否することをチェックするために、さらに2つのテストを書く：

[,go]
----
func TestDetectNotValidSettingsDueToBrokenRegexp(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar" ],
        "constrained_labels": {
            "cost-center": "cc-[a+"
        }
    }
    `)

    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if response.Valid {
        t.Error("Expected settings to not be valid")
    }

    if *response.Message != "Provided settings are not valid: error parsing regexp: missing closing ]: `[a+`" {
        t.Errorf("Unexpected validation error message: %s", *response.Message)
    }
}

func TestDetectNotValidSettingsDueToConflictingLabels(t *testing.T) {
    settingsJSON := []byte(`
    {
        "denied_labels": [ "foo", "bar", "cost-center" ],
        "constrained_labels": {
            "cost-center": ".*"
        }
    }`)
    responsePayload, err := validateSettings(settingsJSON)
    if err != nil {
        t.Errorf("Unexpected error %+v", err)
    }

    var response kubewarden_protocol.SettingsValidationResponse
    if err := json.Unmarshal(responsePayload, &response); err != nil {
        t.Errorf("Unexpected error: %+v", err)
    }

    if response.Valid {
        t.Error("Expected settings to not be valid")
    }

    if *response.Message != "Provided settings are not valid: These labels cannot be constrained and denied at the same time: Set{cost-center}" {
        t.Errorf("Unexpected validation error message: %s", *response.Message)
    }
}
----

さて、ここまで定義したテストを実行するには、以下のコマンドを使用する：

[subs="+attributes",shell]
----
go test -v settings.go settings_test.go
----

すべてのテストは以下の出力でパスする：

[subs="+attributes",shell]
----
=== RUN   TestParseValidSettings
--- PASS: TestParseValidSettings (0.00s)
=== RUN   TestParseSettingsWithInvalidRegexp
--- PASS: TestParseSettingsWithInvalidRegexp (0.00s)
=== RUN   TestDetectValidSettings
--- PASS: TestDetectValidSettings (0.00s)
=== RUN   TestDetectNotValidSettingsDueToBrokenRegexp
--- PASS: TestDetectNotValidSettingsDueToBrokenRegexp (0.00s)
=== RUN   TestDetectNotValidSettingsDueToConflictingLabels
--- PASS: TestDetectNotValidSettingsDueToConflictingLabels (0.00s)
PASS
ok      command-line-arguments    0.002s
----

次のセクションで、実際の検証コードを実装することができる。
