include::partial$variables.adoc[]
= JSONクエリを使用した検証
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: KubernetesオブジェクトのJSON表現から関連データを抽出し、JSONクエリを使用して検証ロジックを実装する。
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "validation-using-json"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"JSONクエリを使った検証"]]。
:current-version: {page-origin-branch}

先のセクションでは、Kubernetesオブジェクトを記述するGo型を使ってxref:tutorials/writing-policies/go/04-validation.adoc[検証]ポリシーを書く方法を紹介した。

検証ロジックを記述するには、アドホッククエリを使用してJSONドキュメントから関連データを抽出する方法もあります。

この_"jqのような "_アプローチは、ポリシーがKubernetesオブジェクトの内部を深く探さなければならないときに便利だ。
特にオプションのインナーオブジェクトを扱うときに役立つ。

このドキュメントでは、JSONペイロードをGo型にアンマーシャリングする代わりに、JSONクエリーを使用して以前のコードを再実装しています。

== `validate` 関数

先ほど作成したポリシーを使用し、`validate` 関数を変更して、Kubernetes オブジェクトを定義する Go タイプを使用しないようにすることができます。

代わりにhttps://github.com/tidwall/gjson[`gjson`]ライブラリを使って生のJSONオブジェクトからデータを抽出することができます。

まず、要求項目を変更する必要がある。
コードはこのようになるはずだ：

[,go]
----
import (
    "encoding/json"
    "fmt"

    mapset "github.com/deckarep/golang-set/v2"
    kubewarden "github.com/kubewarden/policy-sdk-go"
    kubewarden_protocol "github.com/kubewarden/policy-sdk-go/protocol"
    "github.com/tidwall/gjson"
)
----

`validate` 関数を次のように変更する：

.`validate` 機能
[%collapsible]
======

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // Create a ValidationRequest instance from the incoming payload
    validationRequest := kubewarden_protocol.ValidationRequest{}
    err := json.Unmarshal(payload, &validationRequest)
    if err != nil {
        return kubewarden.RejectRequest(
            kubewarden.Message(err.Error()),
            kubewarden.Code(400))
    }

    // Create a Settings instance from the ValidationRequest object
    settings, err := NewSettingsFromValidationReq(&validationRequest)
    if err != nil {
        return kubewarden.RejectRequest(
            kubewarden.Message(err.Error()),
            kubewarden.Code(400))
    }

    // Access the **raw** JSON that describes the object
    podJSON := validationRequest.Request.Object

    // NOTE 1
    data := gjson.GetBytes(
        podJSON,
        "metadata.labels")

    var validationErr error
    labels := mapset.NewThreadUnsafeSet[string]()
    data.ForEach(func(key, value gjson.Result) bool {
        // NOTE 2
        label := key.String()
        labels.Add(label)

        // NOTE 3
        validationErr = validateLabel(label, value.String(), &settings)

        // keep iterating if there are no errors
        return validationErr == nil
    })

    // NOTE 4
    if validationErr != nil {
        return kubewarden.RejectRequest(
            kubewarden.Message(validationErr.Error()),
            kubewarden.NoCode)
    }

    // NOTE 5
    for requiredLabel := range settings.ConstrainedLabels {
        if !labels.Contains(requiredLabel) {
            return kubewarden.RejectRequest(
                kubewarden.Message(fmt.Sprintf("Constrained label %s not found inside of Pod", requiredLabel)),
                kubewarden.NoCode)
        }
    }

    return kubewarden.AcceptRequest()
}
----

======

`validate` 関数の最初の部分は以前と同様である。
「NOTE'S マーク・ザ・チェンジ。

. リクエストに埋め込まれたオブジェクトが提供する`label` マップを取得するには、`gjson` セレクタを使用します。
. クエリーの結果を反復処理するには、`gjson` ヘルパーを使用する。
クエリーの結果がない場合、ループは実行されない。
. `validateLabel` 、ラベルとその値を検証する。
また、Podで見つけたラベルを、以前に定義した`mapset.Set` 。
. バリデーションでエラーが発生した場合は、直ちにバリデーション拒否の返答を返します。
. 先ほどと同じように、`constrainedLabels` を繰り返し、すべてがポッドに指定されていることを確認します。
以前に入力した`mapset.Set` を利用するため、コードが若干変更されている。

== 検証コードのテスト

ユニットテストとエンドツーエンドテストは変更する必要はなく、以前と同じように実行できる：

[subs="+attributes",console]
----
make test
----

[subs="+attributes",console]
----
go test -v
=== RUN   TestParseValidSettings
--- PASS: TestParseValidSettings (0.00s)
=== RUN   TestParseSettingsWithInvalidRegexp
--- PASS: TestParseSettingsWithInvalidRegexp (0.00s)
=== RUN   TestDetectValidSettings
--- PASS: TestDetectValidSettings (0.00s)
=== RUN   TestDetectNotValidSettingsDueToBrokenRegexp
--- PASS: TestDetectNotValidSettingsDueToBrokenRegexp (0.00s)
=== RUN   TestDetectNotValidSettingsDueToConflictingLabels
--- PASS: TestDetectNotValidSettingsDueToConflictingLabels (0.00s)
=== RUN   TestValidateLabel
--- PASS: TestValidateLabel (0.00s)
PASS
ok      github.com/kubewarden/go-policy-template    0.002s
----

[subs="+attributes",console]
----
make e2e-tests
----

[subs="+attributes",console]
----
bats e2e.bats
e2e.bats
 ✓ accept when no settings are provided
 ✓ accept because label is satisfying a constraint
 ✓ accept labels are not on deny list
 ✓ reject because label is on deny list
 ✓ reject because label is not satisfying a constraint
 ✓ reject because constrained label is missing
 ✓ fail settings validation because of conflicting labels
 ✓ fail settings validation because of invalid constraint

8 tests, 0 failures
----

すべてのテストは期待通りに機能している。
