= 数据保留
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自助托管

== 概述

SUSE Observability 设置了数据保留限制，以节省存储空间并提高性能。您可以配置数据保留期，以便在存储的数据量与 SUSE Observability 性能和数据可用性之间取得平衡。

== 保留拓扑图数据

默认情况下，拓扑图数据将保留 30 天。这样，拓扑图的最新状态将始终保留；只有超过 30 天的历史记录才会被删除。
在某些情况下，将历史数据保存超过 30 天或减少到 30 天以内以节省磁盘空间可能是有用的。拓扑保留可通过舵手图进行配置：

[,yaml]
----
stackstate:
  topology:
    # Retention set to 1 week
    retentionHours: 144
----

需要注意的是，数据保留时间越长，存储的数据量也就越大，需要的存储空间也就越大。这也可能会影响《意见》的性能。

当降低保留期时，可能需要一些时间才能释放磁盘空间（至少 15 分钟）。

=== 解决拓扑磁盘空间问题
如果遇到磁盘空间问题，命名节点中会出现一行日志 -`Not enough replicas was chosen. Reason: {NOT_ENOUGH_STORAGE_SPACE=1` 。请按照以下步骤处理这种情况：

* 降低保留率，让实例做好立即恢复磁盘空间的准备，并触发舵机升级：
[,yaml]
----
stackstate:
  topology:
    # Retention set to 1 week in case you are running with the default 1 month
    retentionHours: 144
hbase:
  console:
    enabled: true
    replicaCount: 1
  hdfs:
    datanode:
      extraEnv:
        open:
          HDFS_CONF_dfs_datanode_du_reserved_pct: "0"
----

[NOTE]
====
等待所有 hbase 和 hdfs pod 稳定后，再进行下一步。
====

* 触发历史数据的压缩：
[,bash]
----
kubectl exec -t --namespace suse-observability  $(kubectl get pods --namespace suse-observability --no-headers | grep "console" | awk '{print $1}' | head -n 1) -- /bin/bash -c "stackgraph-console run println\(retention.removeExpiredDataImmediately\(\)\)"
----

* 使用
----
kubectl exec -t --namespace suse-observability  $(kubectl get pods --namespace suse-observability --no-headers | grep "console" | awk '{print $1}' | head -n 1) -- /bin/bash -c "stackgraph-console run println\(retention.removeExpiredDataImmediatelyStatus\(\)\)"
----

* 如果预算的磁盘空间不足，请联系<support-portal-link> 。

* 恢复设置。一旦状态不再是进行中 -`Status(inProgress = false, lastFailure = null)` ，就会触发舵机升级，将新的保留作为价值的一部分。
[,yaml]
----
stackstate:
  topology:
    # Retention set to 1 week in case you are running with the default 1 month
    retentionHours: 144
----

== 事件和日志的保存

=== SUSE Observability 数据存储

如果您使用的是 SUSE Observability 提供的事件/日志存储，数据默认保留 30 天。在大多数情况下，默认设置足以将所有索引存储这么长的时间。

==== 为 Elasticsearch 配置磁盘空间

在某些情况下，可能有必要调整 Elasticsearch 可用的磁盘空间以及分配给日志和事件的方式，例如，如果你预计会有大量特定数据类型的数据到达。

下面是 Elasticsearch 磁盘空间和保留配置的完整片段，包括默认值。

[,yaml]
----
elasticsearch:
  volumeClaimTemplate:
    resources:
      requests:
        storage: 250Gi
stackstate:
  components:
    receiver:
      esDiskSpaceShare: 70
      # Number of days to keep the logs data on Es
      retention: 7
    e2es:
      esDiskSpaceShare: 30
      # Number of days to keep the events data on Es
      retention: 30
----

Elasticsearch 可用的磁盘空间通过`elasticsearch.volumeClaimTemplate.resources.requests.storage` 密钥配置。在初始安装后更改该值需要一些xref:/setup/data-management/data_retention.adoc#_resizing_storage[额外步骤]。

NOTE: 是每个 ElasticSearch 实例的磁盘空间。对于非 HA，这是总可用磁盘空间，但对于 HA，有 3 个实例，复制因子为 1。最终结果是，可用的 Elasticsearch 存储总量将为`(250Gi * 3) / 2 = 375Gi` 。
根据`esDiskSpaceShare` 和`retention` ，为每种数据类型保留一部分 Elasticsearch 磁盘空间。

== 保留衡量标准

SUSE Observability 使用 VictoriaMetrics 来存储指标。配置的默认保留时间为 30 天。舵手图为 1 或 2 个维多利亚度量实例分配磁盘空间并配置保留期，就像这样：

----
victoria-metrics-0:
  server:
    persistentVolume:
      size: 250Gi
    retentionPeriod: 1 # month
# For HA setups:
victoria-metrics-1:
  server:
    persistentVolume:
      size: 250Gi
    retentionPeriod: 1 # month
----

初始安装后，要更改加密卷的大小，xref:/setup/data-management/data_retention.adoc#_resizing_storage[还需要]一些xref:/setup/data-management/data_retention.adoc#_resizing_storage[额外的步骤]。

要更改保留期，请在自定义值.yaml 中使用相同的值覆盖`retentionPeriod` 关键字，并xref:/setup/data-management/data_retention.adoc#_update_stackstate[更新 SUSE Observability]：

* 支持以下可选后缀：h（小时）、d（天）、w（周）、y（年）。如果未设置后缀，则持续时间以月为单位。
* 最短保留时间为 24 小时或 1 天。

== 更新 SUSE Observability

更改 values.yaml 后，需要更新 SUSE Observability，以便将这些更改应用到运行时。这可能会在服务重新启动时造成短暂停机。要更新 SUSE Observability，请使用与安装 SUSE Observability 时相同的命令，并确保包含相同的配置文件，包括已做的更改：

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[OpenShift]

== 调整存储空间大小

在大多数群集中，持久卷创建后可以调整其大小，而且完全不会中断应用程序的运行。不过，这不是简单地更改 SUSE Observability Helm 图表 values.yaml 中的配置存储大小就能实现的。相反，需要采取几个步骤：

. 验证所用存储类的大小是否可以调整
. 调整卷的大小
. 更新 values.yaml 并应用更改（可选但建议使用）

下面的示例以 VictoriaMetrics 存储为例。SUSE Observability 安装在`suse-observability` 命名空间中。卷的大小将调整为 500Gi。

=== 验证存储类是否支持调整大小

使用以下`kubectl` 命令获取使用的存储类，并检查`allowVolumeExpansion` 是否设置为 true。

[,bash]
----
# Get the PVC's for SUSE Observability
kubectl get pvc --namespace suse-observability

# There is a storage class column in the output, copy it and use it to describe the storage class
kubectl describe storageclass <storage-class-name>
----

验证输出是否包含这一行：

----
AllowVolumeExpansion:  True
----

如果该行不存在或设置为`False` ，请咨询 Kubernetes 管理员是否支持调整大小并可以启用。

=== 调整卷的大小

SUSE Observability Helm 图表会创建一个有状态集，其中有一个创建持久卷主张（PVC）的模板。该模板仅用于创建 PVC 一次，之后将不再使用，也不允许更改。因此，要使 PVC 变大，需要对 PVC 本身进行编辑。

要更改 PVC 大小，请使用以下命令。

[,bash]
----
# Get the PVC's for SUSE Observability, allows us to check the current size and copy the name of the PVC to modify it with the next command
kubectl get pvc --namespace suse-observability

# Patch the PVC's specified size, change it to 500Gi
kubectl patch pvc server-volume-stackstate-victoria-metrics-0-0 -p '{"spec":{"resources": { "requests": { "storage": "500Gi" }}}}'

# Get the PVC's again to verify if it was resized, depending on the provider this can take a while
kubectl get pvc --namespace suse-observability
----

=== 更新 values.yaml 并应用更改

对持久卷要求（PVC）所做的更改将在 PVC 的生命周期内保留，但在进行清洁安装时，这些更改将丢失。但更重要的是，在调整了 PVC 的大小后，集群状态与 values.yaml 中定义的理想状态之间出现了差异。因此建议同时更新 values.yaml。要规避这种不允许的更改，首先要删除有状态设置（但保持 pod 运行），然后用新设置重新创建。

[NOTE]
====
此步骤不会改变 PVC 本身的大小，因此仅执行此步骤不会对运行环境造成任何改变。
====


首先编辑您的 values.yaml，更新刚刚调整过大小的 PVC 的卷大小。请参阅 "xref:/setup/data-management/data_retention.adoc#_retention_of_metrics[指标 "]或 "xref:/setup/data-management/data_retention.adoc#_retention_of_events_traces_and_logs[事件和日志]"章节。

现在删除存储已更改的应用程序的有状态设置：

[,bash]
----
# List all stateful sets, check that all are ready, if not please troubleshoot that first
kubectl get statefulset --namespace suse-observability

# Delete the
kubectl delete statefulset --namespace suse-observability stackstate-victoria-metrics-0 --cascade=orphan
----

最后用新设置xref:/setup/data-management/data_retention.adoc#_update_[更新 SUSE Observability]。
