= Fehlerbehebung bei der Wiederherstellung
:revdate: 2025-07-03
:page-revdate: {revdate}

[WARNING]
====
Wenn eine Wiederherstellung durchgeführt wird, starten Sie die `rancher-system-agent` auf elementaren Knoten nicht neu, da sie veralten und mit dem folgenden Fehler enden kann:

`panic: error while connecting to Kubernetes cluster: the server has asked for the client to provide credentials`

Wenn Sie dieses Problem haben, gehen Sie bitte wie folgt vor.
====


Bevor Sie eine Wiederherstellung einleiten, müssen Sie `/var/lib/rancher/agent/rancher2_connection_info.json` vom Elementarknoten an einen Ort kopieren, auf den Sie mit Rancher UI Zugriff haben.

Sobald die Datei kopiert ist, laden Sie das Skript `rancher-agent-token-update.sh` aus dem https://github.com/rancher/elemental[Repository]

[,shell]
----
wget -q https://raw.githubusercontent.com/rancher/elemental/main/scripts/rancher-agent-token-update && chmod +x rancher-agent-token-update
----

Führen Sie das Skript ohne zusätzliche Optionen aus:

[,shell]
----
./rancher-agent-token-update
----

Nachdem die Wiederherstellung erfolgreich abgeschlossen wurde, kopieren Sie `rancher2_connection_info.json` zurück in den elementaren Knoten in den Pfad`/var/lib/rancher/agent/rancher2_connection_info.json`. Starten Sie abschließend den Dienst `rancher-system-agent` neu:

[,shell]
----
systemctl restart rancher-system-agent
----
