= k8s カスタム・シークレット・マネジメント
:revdate: 2025-10-27
:page-revdate: {revdate}

== 概要

SUSE Observability Agentでは、APIキーとクラスタ認証トークンを含むカスタムシークレットの名前を指定できます。この機能は、自分自身で秘密を管理し、Helmチャートによる秘密の自動作成を避けたいユーザーに便利です。

NOTE: *以前はこの指定方法がありましたが、現在はxref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[非推奨となって]います。*

== ヘルムチャート

=== 設定オプション

* `+global.apiKey.fromSecret+`:同じ名前空間に存在する、`+STS_API_KEY+` フィールドに api キーを含む既存の秘密名を指定する。
* `+global.clusterAgentAuthToken.fromSecret+`:クラスタ・エージェントとノード・エージェント間の接続を保護するためのトークンを含む`+STS_CLUSTER_AGENT_AUTH_TOKEN+` フィールドを含む、同じネームスペースに存在する既存の秘密名を指定します。

=== 行動説明

* *秘密の自動作成*：デフォルトでは、チャートは`+stackstate.apiKey+` を指定する必要があり、それ自身でシークレットを作成する。`+STS_CLUSTER_AGENT_AUTH_TOKEN+` は自動的に生成される。
* *カスタム・シークレット・マネジメント*`+fromSecret+` フィールドをオーバーライドする場合、api キーとクラスタ認証トークンはこれらのシークレットから取得されます。
* *暗黙の省略*：自分の秘密を管理したいと指定した場合、チャートは`+stackstate.apiKey+` と`+stackstate.cluster.authToken+` の値を無視する。

== values.yamlの使い方

. *自動秘密作成を使用する（デフォルト）*：
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *自らの秘密を管理する*
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
