= 网络配置 {elemental-product-name}
:revdate: 2025-09-08
:page-revdate: {revdate}


[CAUTION]
.警告
====
声明式联网处于*技术预览*状态，支持有限。
因此，不建议在生产环境中使用。
====

xref:references/machineregistration-reference.adoc[机器注册]支持声明式联网并与https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220125-ipam-integration.md#ipam-provider[IPAM 提供商] CAPI集成。

== 先决条件

* 首次启动注册和重置机器仍然需要 DHCP 服务器。因此，可以尽量缩短租用时间，因为在机器的整个生命周期内，都将使用 IPAM 驱动的 IP 地址。
* 在 Rancher 管理群集上安装您选择的 IPAM 提供程序。
例如https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster[InCluster IPAM Provider]。
* https://networkmanager.dev[NetworkManager]需要安装在操作系统镜像上，并可直接使用`nmconnections` 网络<<_configurators,配置器>>进行配置。
已包含在元素提供的图片中。
* (可选择）https://github.com/suse-edge/nm-configurator/releases[]nmc 与`nmc` 网络<<_configurators,配置器>>一起使用。
* (可选择）https://github.com/nmstate/nmstate/releases[]nmstatectl 与`nmstate` 网络<<_configurators,配置器>>一起使用。

=== 在操作系统映像上安装 nmc 或 nmstatectl

使用`nmc` 或`nmstate` 配置器时，需要在机器上安装https://github.com/suse-edge/nm-configurator/releases[] nmc 或https://github.com/nmstate/nmstate/releases[] nmstatectl 工具。

目前，可以通过自定义命令来xref:operator-operational-tasks/custom-images.adoc#_remastering_an_os_image_with_a_custom_dockerfile[定制 Elemental OS 镜像]：

[tabs]
======
nmc::
+
--
[,yaml]
----
# Install nmc
RUN curl -LO https://github.com/suse-edge/nm-configurator/releases/download/v0.3.3/nmc-linux-x86_64 && \ install -o root -g root -m 0755 nmc-linux-x86_64 /usr/sbin/nmc
----
--

nmstatectl::
+
--
[,yaml]
----
# Install nmstatectl
RUN curl -LO https://github.com/nmstate/nmstate/releases/download/v2.2.40/nmstatectl-linux-x64.zip && \ unzip nmstatectl-linux-x64.zip && \ chmod +x nmstatectl && \ mv ./nmstatectl /usr/sbin/nmstatectl && \ rm nmstatectl-linux-x64.zip
----
--
======

=== 如何安装 CAPI IPAM 提供程序

将任何 CAPI 提供程序安装到 Rancher 的推荐方法是使用https://documentation.suse.com/cloudnative/cluster-api/v0.22/en/index.html[Turtles] Rancher。

Rancher Turtles 允许用户安装和管理任何 CAPI 提供程序的生命周期。请按照https://documentation.suse.com/cloudnative/cluster-api/v0.22/en/tutorials/quickstart.html[Turtles 安装文档] Rancher在系统上进行安装。

安装 Rancher Turtles 后，可以应用以下资源安装 IPAM CAPI 提供程序，例如https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster[InCluster IPAM 提供]程序：

[,yaml]
----
kind: CAPIProvider
metadata:
  name: in-cluster
  namespace: default
spec:
  name: in-cluster
  type: ipam
  fetchConfig:
    url: "https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases"
  version: v0.1.0
----

==== 没有牧场主乌龟

安装 CAPI IPAM 提供程序的另一个选择是直接在 Rancher 集群中应用清单。

请注意，这种解决方案最终可能会导致与已应用的 CRD 和资源发生冲突，因为它们需要手动应用和维护。

. `ipaddresses.ipam.cluster.x-k8s.io` 和`ipaddressclaims.ipam.cluster.x-k8s.io` CRD 必须安装在 Rancher 管理集群上：
+
[,bash]
----
 kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
 kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
----

[IMPORTANT]
.info
====
预计这些 CRD 最终将成为 Rancher 的一部分，无需手动安装。见： https://github.com/rancher/rancher/issues/46385
====


. 从发布的清单中安装https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster[InCluster IPAM Provider]：
+
[,bash]
----
 kubectl apply -f https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/download/v0.1.0/ipam-components.yaml
----

=== 配置网络

`MachineRegistration` 的`network` 部分允许用户定义：

. IPPool 引用地图。
. 网络配置模板（本例中使用`nmc` configurator）。

.使用声明式网络的机器注册示例
[,yaml]
----
include::example$network/machineregistration.yaml[]
----

在这里，我们可以看到，由于本例中使用的是https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster[InCluster IPAM Provider]，因此已经定义了一个`InClusterIPPool` 。

接下来，我们将在`MachineRegistration` 中引用 IPPool。此引用的关键字是`inventory-ip` ，我们只需要每个注册机器一个 IP。如果您的机器有多个网卡，您可以定义更多的引用，例如使用不同的 IPPool：

[,yaml]
----
ipAddresses:
  main-nic-ip:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: elemental-inventory-pool
  secondary-nic-ip:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: elemental-inventory-pool
  private-nic-ip:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: elemental-private-pool
----

每个已定义的 IPPool 引用密钥都可用于网络配置模板：

[,yaml]
----
config:
  dns-resolver:
    config:
      server:
      - 192.168.122.1
      search: []
  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-interface: eth0
      next-hop-address: 192.168.122.1
      metric: 150
      table-id: 254
  interfaces:
    - name: eth0
      type: ethernet
      description: Main-NIC
      state: up
      ipv4:
        enabled: true
        dhcp: false
        address:
        - ip: "{inventory-ip}"
          prefix-length: 24
      ipv6:
        enabled: false
----

上面的代码段几乎与https://github.com/suse-edge/nm-configurator?tab=readme-ov-file#unified-configurations[语法] nm-configurator 的完全一致，唯一的例外是`{inventory-ip}` 占位符。在 Elemental 机器的安装或重置阶段，`elemental-operator` 将从引用的 IP 池中获取一个 IP 地址，并用真实 IP 地址代替`{inventory-ip}` 占位符。

=== 已申请的 IP 地址

`IPAddressClaim` 将跟踪`MachineInventory` 的整个生命周期，确保为每台注册机器分配唯一的 IP。每个索赔都以使用该索赔的`MachineInventory` 命名，例如`$MachineInventoryName-$IPPoolRefKey` ：

[,yaml]
----
apiVersion: ipam.cluster.x-k8s.io/v1beta1
kind: IPAddressClaim
metadata:
  finalizers:
    - ipam.cluster.x-k8s.io/ReleaseAddress
  name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c-inventory-ip
  namespace: fleet-default
  ownerReferences:
    - apiVersion: elemental.cattle.io/v1beta1
      kind: MachineInventory
      name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: elemental-inventory-pool
status:
  addressRef:
    name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c-inventory-ip
----

只要删除`MachineInventory` ，就会恢复默认（DHCP）网络配置，删除机器上的任何网络配置文件并重启网络堆栈。最后，分配的 IP 将被释放。

有关如何排除故障的详细信息，请参阅《xref:troubleshooting/troubleshooting-network.adoc[声明式联网故障排除》文档]。

=== 配置器

在 Elemental 机器上，`elemental-register` 可以用不同的方式配置`NetworkManager` 。使用的配置器在xref:references/machineregistration-reference.adoc#_config_network[机器注册.spec.network] 中定义：

* https://github.com/suse-edge/nm-configurator[nmc]
* https://nmstate.io/[nmstate]
* https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/nm-settings-keyfile.html[nmconnections]

[tabs]
======
nmc::
+
--
`nmc` 配置器使用https://github.com/suse-edge/nm-configurator?tab=readme-ov-file#unified-configurations[统一语法] nm-configurator生成 NetworkManager 的连接文件。

.使用 nmc 配置器进行机器注册的示例
[,yaml]
----
include::example$network/machineregistration-nmc.yaml[]
----

--

nmstate::
+
--
`nmstate` 配置器使用https://nmstate.io/examples.html[语法] nmstate生成 NetworkManager 的连接文件。请注意，需要在 Elemental 系统上安装https://github.com/nmstate/nmstate/releases[] nmstatectl 才能使用该配置器。Elemental 图像中默认不包含此功能，但可以在构建xref:operator-operational-tasks/custom-images.adoc[自定义图像]时安装。

.使用 nmstate 配置器进行机器注册的示例
[,yaml]
----
include::example$network/machineregistration-nmstate.yaml[]
----

--

nmconnections::
+
--
`nmconnections` 配置器是最简单的选项，允许用户直接写入`nmconnection` 文件。为复杂的网络设置定义这些文件可能具有挑战性，但始终可以使用https://networkmanager.dev/docs/api/latest/nmcli.html[] nmcli，甚至https://nmstate.io[] nmstate 或 [nm-configurator](https://github.com/suse-edge/nm-configurator)，并将生成的`nmconnection` 文件作为模板。该配置器只需要`NetworkManager` ，不需要任何额外的依赖关系。使用 nmconnections 配置器进行机器注册的示例。

.单击此处查看使用 nmstate 配置器进行机器注册的示例
[%collapsible]
====
[,yaml]
----
include::example$network/machineregistration-nmconnections.yaml[]
----
====

--
======
