= k3sサーバー
:page-languages: [en、ja、ko、zh]。
:revdate: 2025-05-26
:page-revdate: {revdate}

このセクションでは、K3sサーバーの設定方法について説明します。

サーバーもエージェントを実行するので、xref:cli/agent.adoc[`+k3s agent+` のドキュメントに]記載されているすべての設定オプションは、サーバーでもサポートされていることに注意してください。

オプションはCLIフラグとしてこのページに記述されているが、設定ファイルのオプションとして渡すこともできる。YAML設定ファイルの使い方の詳細については、xref:installation/configuration.adoc#_configuration_file[設定ファイルの]ドキュメントを参照してください。

== 重要な設定値

以下のオプションは、クラスタ内のすべてのサーバで同じ値に設定する必要があります。これを行わないと、組み込みetcdを使用している場合に新しいサーバーがクラスタに参加できなくなったり、外部データストアを使用している場合にクラスタが正しく動作しなくなったりします。

* `+--agent-token+`
* `+--cluster-cidr+`
* `+--cluster-dns+`
* `+--cluster-domain+`
* `+--disable-cloud-controller+`
* `+--disable-helm-controller+`
* `+--disable-network-policy+`
* `+--disable=servicelb+` _注：その他のパッケージ・コンポーネントは、サーバーごとに無効にすることができます。_
* `+--egress-selector-mode+`
* `+--embedded-registry+`
* `+--flannel-backend+`
* `+--flannel-external-ip+`
* `+--flannel-ipv6-masq+`
* `+--secrets-encryption+`
* `+--secrets-encryption-provider+`
* `+--service-cidr+`

== よく使われるオプション

=== データベース

|===
| フラッグ | 環境変数 | デフォルト | 説明

| `+--datastore-endpoint+` 価値
| `+K3S_DATASTORE_ENDPOINT+`
|
| etcd、NATS、MySQL、Postgres、SQLiteのいずれかのデータソース名を指定する。

| `+--datastore-cafile+` 価値
| `+K3S_DATASTORE_CAFILE+`
|
| データストアのバックエンド通信を保護するために使用されるTLS認証局ファイル

| `+--datastore-certfile+` 価値
| `+K3S_DATASTORE_CERTFILE+`
|
| データストアのバックエンド通信を保護するために使用されるTLS認証ファイル

| `+--datastore-keyfile+` 価値
| `+K3S_DATASTORE_KEYFILE+`
|
| データストアのバックエンドの通信を保護するために使用されるTLSキーファイル。

| `+--etcd-expose-metrics+`
|
| 擬似
| etcdのメトリクスをクライアントインターフェースに公開する

| `+--etcd-disable-snapshots+`
|
| 擬似
| 自動 etcd スナップショットを無効にする

| `+--etcd-snapshot-name+` 価値
|
| "etcd-snapshot-<unix-timestamp>"
| etcd スナップショットのベース名を設定する。

| `+--etcd-snapshot-schedule-cron+` 価値
|
| "0 */12 * * *"
| スナップショット間隔の時間（cron仕様）。

| `+--etcd-snapshot-retention+` 価値
|
| 5
| 保持するスナップショット数

| `+--etcd-snapshot-dir+` 価値
|
| ${data-dir}/db/snapshots
| DBスナップショットを保存するディレクトリ

| `+--etcd-s3+`
|
|
| S3へのバックアップを有効にする

| `+--etcd-s3-endpoint+` 価値
|
| "s3.amazonaws.com"
| S3エンドポイントのURL

| `+--etcd-s3-endpoint-ca+` 価値
|
|
| S3 エンドポイントに接続するための S3 カスタム CA 証明書

| `+--etcd-s3-skip-ssl-verify+`
|
|
| S3 SSL証明書の検証を無効にする

| `+--etcd-s3-access-key+` 価値
| `+AWS_ACCESS_KEY_ID+`
|
| S3アクセスキー

| `+--etcd-s3-secret-key+` 価値
| `+AWS_SECRET_ACCESS_KEY+`
|
| S3の秘密鍵

| `+--etcd-s3-bucket+` 価値
|
|
| S3バケット名

| `+--etcd-s3-region+` 価値
|
| "us-east-1"
| S3リージョン/バケットロケーション（オプション）

| `+--etcd-s3-folder+` 価値
|
|
| S3フォルダ

| `+--etcd-s3-proxy+`
| 
| 
| S3への接続時に使用するプロキシサーバーで、プロキシ関連の環境変数を上書きする。

| `+--etcd-s3-config-secret+`
| 
| 
| etcd-s3が有効であり、他のetcd-s3オプションが設定されていない場合に、S3の構成に使用されるkube-system名前空間内のsecretの名前


| `+--etcd-s3-insecure+`
|
|
| S3 over HTTPSを無効にする

| `+--etcd-s3-timeout+` 価値
|
| 5分
| S3のタイムアウト（デフォルト：5m0s)
|===

[#_cluster_options]
=== クラスターオプション

|===
| フラッグ | 環境変数 | 説明

| `+--token+` 値、`+-t+` 値
| `+K3S_TOKEN+`
| サーバまたはエージェントをクラスタに参加させるために使用される共有シークレット

| `+--token-file+` 価値
| `+K3S_TOKEN_FILE+`
| クラスター・シークレット/トークンを含むファイル

| `+--agent-token+` 価値
| `+K3S_AGENT_TOKEN+`
| エージェントをクラスタに参加させるための共有秘密。

| `+--agent-token-file+` 価値
| `+K3S_AGENT_TOKEN_FILE+`
| エージェントシークレットを含むファイル

| `+--server+` 価値
| `+K3S_URL+`
| クラスタに参加するための接続先サーバ

| `+--cluster-init+`
| `+K3S_CLUSTER_INIT+`
| 組み込みEtcdを使用した新しいクラスタの初期化

| `+--cluster-reset+`
| `+K3S_CLUSTER_RESET+`
| すべての仲間を忘れ、新しいクラスタの唯一のメンバーになる
|===

=== 管理Kubeconfigオプション

|===
| フラッグ | 環境変数 | 説明

| `+--write-kubeconfig value, -o+` 価値
| `+K3S_KUBECONFIG_OUTPUT+`
| 管理クライアント用のkubeconfigをこのファイルに書き込む

| `+--write-kubeconfig-mode+` 価値
| `+K3S_KUBECONFIG_MODE+`
| このhttps://en.wikipedia.org/wiki/Chmod[モードで]kubeconfig を書き込むkubeconfigファイルはrootが所有し、デフォルトのモード600で書き込まれます。モードを644に変更すると、ホスト上の他の非特権ユーザーによる読み取りが可能になる。

| `+--write-kubeconfig-group+` 価値
| `+K3S_KUBECONFIG_GROUP+`
| kubeconfigグループを書き込む。`+--write-kubeconfig-mode+` と組み合わせることで、k3s管理者がkubeconfigファイルにアクセスできるようになりますが、ファイルの所有者はrootになります。
|===

== 高度なオプション

=== ロギング

|===
| フラッグ | デフォルト | 説明

| `+--debug+`
| N/A
| デバッグログをオンにする

| `+-v+` 価値
| 0
| ログレベルの冗長性を表す数値

| `+--vmodule+` 価値
| N/A
| ファイルフィルターされたロギングのFILE_PATTERN=LOG_LEVEL設定のカンマ区切りリスト

| `+--log value, -l+` 価値
| N/A
| ファイルへのログ

| `+--alsologtostderr+`
| N/A
| ファイルだけでなく、標準エラーにもログを記録する（設定されている場合）
|===

=== リスナー

|===
| フラッグ | デフォルト | 説明

| `+--bind-address+` 価値
| 0.0.0.0
| k3sバインドアドレス

| `+--https-listen-port+` 価値
| 6443
| HTTPSリッスンポート

| `+--advertise-address+` 価値
| node-external-ip/node-ip
| apiserverがそのサービス・エンドポイント用にアドバタイズするIPv4/IPv6アドレス。 +
プライマリ`+service-cidr+` IP範囲は、アドバタイズされたアドレスと同じアドレスファミリーでなければならないことに注意してください。

| `+--advertise-port+` 価値
| listen-port/0
| apiserverがクラスタのメンバーにアドバタイズするために使用するポート

| `+--tls-san+` 価値
| N/A
| TLS証明書のサブジェクト代替名として、ホスト名またはIPv4/IPv6アドレスを追加する。

| `+--tls-san-security+`
| 真の
| kubernetesのapiserverサービス、サーバーノード、またはtls-sanオプションの値に関連しないSubject Alternative Namesの追加を拒否して、サーバーのTLS証明書を保護する。 
|===

=== データ

|===
| フラッグ | デフォルト | 説明

| `+--data-dir value, -d+` 価値
| `+/var/lib/rancher/k3s+` root でない場合は`+${HOME}/.rancher/k3s+` 
| 状態を保持するフォルダ
|===

=== 秘密の暗号化

|===
| フラッグ | デフォルト | 説明

| `+--secrets-encryption+`
| 擬似
| シークレット暗号化の有効化

| `+--secrets-encryption-provider+`
| エーエスシー
| 使用する暗号化プロバイダー
|===

=== ネットワーキング

|===
| フラッグ | デフォルト | 説明

| `+--cluster-cidr+` 価値
| "10.42.0.0/16"
| ポッドIPに使用するIPv4/IPv6ネットワークCIDR

| `+--service-cidr+` 価値
| "10.43.0.0/16"
| サービスIPに使用するIPv4/IPv6ネットワークCIDR

| `+--service-node-port-range+` 価値
| "30000-32767"
| NodePortの可視性を持つサービスに予約するポート範囲

| `+--cluster-dns+` 価値
| "10.43.0.10"
| corednsサービスのIPv4クラスタIP。サービス・シードルの範囲内であるべきだ

| `+--cluster-domain+` 価値
| "cluster.local"
| クラスタードメイン

| `+--flannel-backend+` 価値
| "vxlan"
| none'、'vxlan'、'ipsec'(非推奨)、'host-gw'、'wireguard-native'、'wireguard'(非推奨) のいずれか。

| `+--flannel-ipv6-masq+`
| 「該当なし
| ポッドのIPv6マスカレードを有効にする

| `+--flannel-external-ip+`
| 「該当なし
| フランネル・トラフィックにノードの外部IPアドレスを使用する

| `+--servicelb-namespace+` 価値
| "kube-system"
| servicelb コンポーネントのポッドの名前空間

| `+--egress-selector-mode+` 価値
| "agent"
a| 以下のいずれかに該当すること：

* を無効にした：apiserverはノードとの通信にエージェント・トンネルを使用しない。サーバーがエージェントを実行し、エージェント上のkubeletに直接接続できる必要があります。さもないと、apiserverはサービス・エンドポイントにアクセスしたり、kubectl execやkubectl logsを実行したりできません。
* エージェントだ：apiserverはノードとの通信にエージェント・トンネルを使用する。ノードはループバックアドレスからのトンネル接続を許可する。サーバーもエージェントを実行している必要があり、そうでないとapiserverはサービス・エンドポイントにアクセスできない。k3sの歴史的なデフォルト。
* ポッドapiserverはエージェント・トンネルを使用してノードやサービス・エンドポイントと通信し、エンドポイント接続をノード監視によって正しいエージェントにルーティングします。ノードはループバックアドレス、または自分のノードに割り当てられたCIDRからのトンネル接続を許可する。
* クラスターである：apiserverはエージェント・トンネルを使ってノードやサービス・エンドポイントと通信し、エンドポイントの接続をEndpointsを見て正しいエージェントにルーティングします。ノードはループバックアドレス、または設定されたクラスタCIDR範囲からのトンネル接続を許可します。
|===

=== ストレージクラス

|===
| フラッグ | 説明

| `+--default-local-storage-path+` 価値
| ローカル・プロビジョナ・ストレージ・クラスのデフォルト・ローカル・ストレージ・パス
|===

=== Kubernetesコンポーネント

|===
| フラッグ | 説明

| `+--disable+` 価値
| xref:installation/packaged-components.adoc#_using_the_disable_flag[ `+--disable+` フラグの使用]」を参照。

| `+--disable-scheduler+`
| Kubernetesのデフォルト・スケジューラを無効にする

| `+--disable-cloud-controller+`
| k3のデフォルトのクラウドコントローラーマネージャーを無効にする

| `+--disable-kube-proxy+`
| 実行中のkube-proxyを無効にする

| `+--disable-network-policy+`
| k3sデフォルトのネットワークポリシーコントローラーを無効にする

| `+--disable-helm-controller+`
| Helmコントローラを無効にする
|===

=== Kubernetesプロセス用にカスタマイズされたフラグ

|===
| フラッグ | 説明

| `+--etcd-arg+` 価値
| etcd プロセスのカスタマイズフラグ

| `+--kube-apiserver-arg+` 価値
| kube-apiserverプロセスのカスタマイズフラグ

| `+--kube-scheduler-arg+` 価値
| kube-schedulerプロセスのカスタマイズフラグ

| `+--kube-controller-manager-arg+` 価値
| kube-controller-managerプロセスのカスタマイズフラグ

| `+--kube-cloud-controller-manager-arg+` 価値
| kube-cloud-controller-managerプロセスのカスタマイズフラグ

| `+--kubelet-arg+` 価値
| キューブレットプロセス用カスタマイズフラッグ

| `+--kube-proxy-arg+` 価値
| kube-proxyプロセスのカスタマイズフラグ
|===

=== 実験的オプション

|===
| フラッグ | 説明

| `+--rootless+`
| 根無し草を走らせる

| `+--enable-pprof+`
| スーパーバイザポートで pprof エンドポイントを有効にする

| `+--docker+`
| containerdの代わりにcri-dockerdを使用する。

| `+--prefer-bundled-bin+`
| ホスト・バイナリよりもバンドルされたユーザー空間バイナリを優先する

| `+--disable-agent+`
| xref:advanced.adoc#_running_agentless_servers_experimental[エージェントレスサーバーの実行]" を参照。

| `+--embedded-registry+`
| xref:installation/registry-mirror.adoc[埋め込みレジストリミラー]" を参照。

| `+--vpn-auth+`
| xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental[Tailscale VPNプロバイダーとの統合]" を参照。 

| `+--vpn-auth-file+`
| xref:networking/distributed-multicloud.adoc#_integration_with_the_tailscale_vpn_provider_experimental[Tailscale VPNプロバイダーとの統合]" を参照。 
|===

=== 非推奨オプション

|===
| フラッグ | 環境変数 | 説明

| `+--no-flannel+`
| N/A
| 用途 `+--flannel-backend=none+`

| `+--no-deploy+` 価値
| N/A
| 用途 `+--disable+`

| `+--cluster-secret+` 価値
| `+K3S_CLUSTER_SECRET+`
| 用途 `+--token+`

| `+--flannel-backend+` ワイヤーガード
| N/A
| 用途 `+--flannel-backend=wireguard-native+`

| `+--flannel-backend+` value=option1=value
| N/A
| `+--flannel-conf+` を使って、フランネルのコンフィグファイルをバックエンドのコンフィグと一緒に指定する。
|===

== K3s サーバー CLI ヘルプ

____
オプションが`+[$K3S_TOKEN]+` のように括弧で括られている場合は、そのオプションをその名前の環境変数として渡すことができることを意味する。
____

[,bash]
----
NAME:
   k3s server - Run management server

USAGE:
   k3s server [OPTIONS]

OPTIONS:
   --config FILE, -c FILE                     (config) Load configuration from FILE (default: "/etc/rancher/k3s/config.yaml") [$K3S_CONFIG_FILE]
   --debug                                    (logging) Turn on debug logs [$K3S_DEBUG]
   -v value                                   (logging) Number for the log level verbosity (default: 0)
   --vmodule value                            (logging) Comma-separated list of FILE_PATTERN=LOG_LEVEL settings for file-filtered logging
   --log value, -l value                      (logging) Log to file
   --alsologtostderr                          (logging) Log to standard error as well as file (if set)
   --bind-address value                       (listener) k3s bind address (default: 0.0.0.0)
   --https-listen-port value                  (listener) HTTPS listen port (default: 6443)
   --advertise-address value                  (listener) IPv4/IPv6 address that apiserver uses to advertise to members of the cluster (default: node-external-ip/node-ip)
   --advertise-port value                     (listener) Port that apiserver uses to advertise to members of the cluster (default: listen-port) (default: 0)
   --tls-san value                            (listener) Add additional hostnames or IPv4/IPv6 addresses as Subject Alternative Names on the server TLS cert
   --tls-san-security                         (listener) Protect the server TLS cert by refusing to add Subject Alternative Names not associated with the kubernetes apiserver service, server nodes, or values of the tls-san option (default: true)
   --data-dir value, -d value                 (data) Folder to hold state default /var/lib/rancher/k3s or ${HOME}/.rancher/k3s if not root [$K3S_DATA_DIR]
   --cluster-cidr value                       (networking) IPv4/IPv6 network CIDRs to use for pod IPs (default: 10.42.0.0/16)
   --service-cidr value                       (networking) IPv4/IPv6 network CIDRs to use for service IPs (default: 10.43.0.0/16)
   --service-node-port-range value            (networking) Port range to reserve for services with NodePort visibility (default: "30000-32767")
   --cluster-dns value                        (networking) IPv4 Cluster IP for coredns service. Should be in your service-cidr range (default: 10.43.0.10)
   --cluster-domain value                     (networking) Cluster Domain (default: "cluster.local")
   --flannel-backend value                    (networking) Backend (valid values: 'none', 'vxlan', 'host-gw', 'wireguard-native' (default: "vxlan")   --flannel-ipv6-masq                        (networking) Enable IPv6 masquerading for pod
   --flannel-external-ip                      (networking) Use node external IP addresses for Flannel traffic
   --egress-selector-mode value               (networking) One of 'agent', 'cluster', 'pod', 'disabled' (default: "agent")
   --servicelb-namespace value                (networking) Namespace of the pods for the servicelb component (default: "kube-system")
   --write-kubeconfig value, -o value         (client) Write kubeconfig for admin client to this file [$K3S_KUBECONFIG_OUTPUT]
   --write-kubeconfig-mode value              (client) Write kubeconfig with this mode [$K3S_KUBECONFIG_MODE]
   --write-kubeconfig-group value             (client) Write kubeconfig with this group [$K3S_KUBECONFIG_GROUP]
   --helm-job-image value                     (helm) Default image to use for helm jobs
   --token value, -t value                    (cluster) Shared secret used to join a server or agent to a cluster [$K3S_TOKEN]
   --token-file value                         (cluster) File containing the token [$K3S_TOKEN_FILE]
   --agent-token value                        (cluster) Shared secret used to join agents to the cluster, but not servers [$K3S_AGENT_TOKEN]
   --agent-token-file value                   (cluster) File containing the agent secret [$K3S_AGENT_TOKEN_FILE]
   --server value, -s value                   (cluster) Server to connect to, used to join a cluster [$K3S_URL]
   --cluster-init                             (cluster) Initialize a new cluster using embedded Etcd [$K3S_CLUSTER_INIT]
   --cluster-reset                            (cluster) Forget all peers and become sole member of a new cluster [$K3S_CLUSTER_RESET]
   --cluster-reset-restore-path value         (db) Path to snapshot file to be restored
   --kube-apiserver-arg value                 (flags) Customized flag for kube-apiserver process
   --etcd-arg value                           (flags) Customized flag for etcd process
   --kube-controller-manager-arg value        (flags) Customized flag for kube-controller-manager process
   --kube-scheduler-arg value                 (flags) Customized flag for kube-scheduler process
   --kube-cloud-controller-manager-arg value  (flags) Customized flag for kube-cloud-controller-manager process
   --datastore-endpoint value                 (db) Specify etcd, NATS, MySQL, Postgres, or SQLite (default) data source name [$K3S_DATASTORE_ENDPOINT]
   --datastore-cafile value                   (db) TLS Certificate Authority file used to secure datastore backend communication [$K3S_DATASTORE_CAFILE]
   --datastore-certfile value                 (db) TLS certification file used to secure datastore backend communication [$K3S_DATASTORE_CERTFILE]
   --datastore-keyfile value                  (db) TLS key file used to secure datastore backend communication [$K3S_DATASTORE_KEYFILE]
   --etcd-expose-metrics                      (db) Expose etcd metrics to client interface. (default: false)
   --etcd-disable-snapshots                   (db) Disable automatic etcd snapshots
   --etcd-snapshot-name value                 (db) Set the base name of etcd snapshots (default: etcd-snapshot-<unix-timestamp>) (default: "etcd-snapshot")
   --etcd-snapshot-schedule-cron value        (db) Snapshot interval time in cron spec. eg. every 5 hours '0 */5 * * *' (default: "0 */12 * * *")
   --etcd-snapshot-retention value            (db) Number of snapshots to retain (default: 5)
   --etcd-snapshot-dir value                  (db) Directory to save db snapshots. (default: $\{data-dir}/db/snapshots)
   --etcd-snapshot-compress                   (db) Compress etcd snapshot
   --etcd-s3                                  (db) Enable backup to S3
   --etcd-s3-endpoint value                   (db) S3 endpoint url (default: "s3.amazonaws.com")
   --etcd-s3-endpoint-ca value                (db) S3 custom CA cert to connect to S3 endpoint
   --etcd-s3-skip-ssl-verify                  (db) Disables S3 SSL certificate validation
   --etcd-s3-access-key value                 (db) S3 access key [$AWS_ACCESS_KEY_ID]
   --etcd-s3-secret-key value                 (db) S3 secret key [$AWS_SECRET_ACCESS_KEY]
   --etcd-s3-bucket value                     (db) S3 bucket name
   --etcd-s3-region value                     (db) S3 region / bucket location (optional) (default: "us-east-1")
   --etcd-s3-folder value                     (db) S3 folder
   --etcd-s3-proxy value                      (db) Proxy server to use when connecting to S3, overriding any proxy-releated environment variables
   --etcd-s3-config-secret value              (db) Name of secret in the kube-system namespace used to configure S3, if etcd-s3 is enabled and no other etcd-s3 options are set
   --etcd-s3-insecure                         (db) Disables S3 over HTTPS
   --etcd-s3-timeout value                    (db) S3 timeout (default: 5m0s)
   --default-local-storage-path value         (storage) Default local storage path for local provisioner storage class
   --disable value                            (components) Do not deploy packaged components and delete any deployed components (valid items: coredns, servicelb, traefik, local-storage, metrics-server, runtimes)
   --disable-scheduler                        (components) Disable Kubernetes default scheduler
   --disable-cloud-controller                 (components) Disable k3s default cloud controller manager
   --disable-kube-proxy                       (components) Disable running kube-proxy
   --disable-network-policy                   (components) Disable k3s default network policy controller
   --disable-helm-controller                  (components) Disable Helm controller
   --embedded-registry                        (experimental/components) Enable embedded distributed container registry; requires use of embedded containerd; when enabled agents will also listen on the supervisor port
   --supervisor-metrics                       (experimental/components) Enable serving k3s internal metrics on the supervisor port; when enabled agents will also listen on the supervisor port
   --node-name value                          (agent/node) Node name [$K3S_NODE_NAME]
   --with-node-id                             (agent/node) Append id to node name
   --node-label value                         (agent/node) Registering and starting kubelet with set of labels
   --node-taint value                         (agent/node) Registering kubelet with set of taints
   --image-credential-provider-bin-dir value  (agent/node) The path to the directory where credential provider plugin binaries are located (default: "/var/lib/rancher/credentialprovider/bin")
   --image-credential-provider-config value   (agent/node) The path to the credential provider plugin config file (default: "/var/lib/rancher/credentialprovider/config.yaml")
   --docker                                   (agent/runtime) (experimental) Use cri-dockerd instead of containerd
   --container-runtime-endpoint value         (agent/runtime) Disable embedded containerd and use the CRI socket at the given path; when used with --docker this sets the docker socket path
   --default-runtime value                    (agent/runtime) Set the default runtime in containerd
   --image-service-endpoint value             (agent/runtime) Disable embedded containerd image service and use remote image service socket at the given path. If not specified, defaults to --container-runtime-endpoint.
   --disable-default-registry-endpoint        (agent/containerd) Disables containerd fallback default registry endpoint when a mirror is configured for that registry
   --nonroot-devices                          (agent/containerd) Allows non-root pods to access devices by setting device_ownership_from_security_context=true in the containerd CRI config
   --pause-image value                        (agent/runtime) Customized pause image for containerd or docker sandbox (default: "rancher/mirrored-pause:3.6")
   --snapshotter value                        (agent/runtime) Override default containerd snapshotter (default: "overlayfs")
   --private-registry value                   (agent/runtime) Private registry configuration file (default: "/etc/rancher/k3s/registries.yaml")
   --system-default-registry value            (agent/runtime) Private registry to be used for all system images [$K3S_SYSTEM_DEFAULT_REGISTRY]
   --node-ip value, -i value                  (agent/networking) IPv4/IPv6 addresses to advertise for node
   --node-external-ip value                   (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
   --node-internal-dns value                  (agent/networking) internal DNS addresses to advertise for node
   --node-external-dns value                  (agent/networking) external DNS addresses to advertise for node
   --resolv-conf value                        (agent/networking) Kubelet resolv.conf file [$K3S_RESOLV_CONF]
   --flannel-iface value                      (agent/networking) Override default flannel interface
   --flannel-conf value                       (agent/networking) Override default flannel config file
   --flannel-cni-conf value                   (agent/networking) Override default flannel cni config file
   --vpn-auth value                           (agent/networking) (experimental) Credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH]
   --vpn-auth-file value                      (agent/networking) (experimental) File containing credentials for the VPN provider. It must include the provider name and join key in the format name=<vpn-provider>,joinKey=<key>[,controlServerURL=<url>][,extraArgs=<args>] [$K3S_VPN_AUTH_FILE]
   --kubelet-arg value                        (agent/flags) Customized flag for kubelet process
   --kube-proxy-arg value                     (agent/flags) Customized flag for kube-proxy process
   --protect-kernel-defaults                  (agent/node) Kernel tuning behavior. If set, error if kernel tunables are different than kubelet defaults.
   --secrets-encryption                       Enable secret encryption at rest
   --enable-pprof                             (experimental) Enable pprof endpoint on supervisor port
   --rootless                                 (experimental) Run rootless
   --prefer-bundled-bin                       (experimental) Prefer bundled userspace binaries over host binaries
   --selinux                                  (agent/node) Enable SELinux in containerd [$K3S_SELINUX]
   --lb-server-port value                     (agent/node) Local port for supervisor client load-balancer. If the supervisor and apiserver are not colocated an additional port 1 less than this port will also be used for the apiserver client load-balancer. (default: 6444) [$K3S_LB_SERVER_PORT]
----
