= Options avancées / Configuration
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Cette section contient des informations avancées décrivant les différentes manières d'exécuter et de gérer K3s, ainsi que les étapes nécessaires pour préparer le système d'exploitation hôte à l'utilisation de K3s.

== Gestion des certificats

=== Certificats d'autorité de certification

K3s génère des certificats d'autorité de certification (CA) auto-signés lors du démarrage du premier nœud de serveur. Ces certificats d'autorité de certification sont valables 10 ans et ne sont pas renouvelés automatiquement.

Pour plus d'informations sur l'utilisation de certificats d'autorité de certification personnalisés ou sur le renouvellement des certificats d'autorité de certification auto-signés, consultez la xref:cli/certificate.adoc#_certificate_authority_ca_certificates[documentation de la commande`k3s certificate rotate-ca` ].

=== Certificats du client et du serveur

Les certificats clients et serveurs de K3 sont valables pendant 365 jours à compter de leur date d'émission. Tous les certificats expirés ou en passe d'expirer dans les 90 jours sont automatiquement renouvelés à chaque démarrage de K3s.

Pour plus d'informations sur la rotation manuelle des certificats client et serveur, voir la xref:cli/certificate.adoc#_client_and_server_certificates[documentation de la commande`k3s certificate rotate` ].

== Gestion des jetons

Par défaut, K3s utilise un seul jeton statique pour les serveurs et les agents. Avec prudence, ce jeton peut faire l'objet d'une rotation une fois que le cluster a été créé.
Il est également possible d'activer un deuxième jeton statique qui ne peut être utilisé que pour rejoindre des agents, ou de créer des jetons de jonction temporaires de type `kubeadm` qui expirent automatiquement.
Pour plus d'informations, voir la xref:cli/token.adoc#_k3s_token_1[documentation de la commande`k3s token` ].

== Configuration de la résolution DNS

=== Contrôles de viabilité des serveurs de noms

Au démarrage, chaque nœud vérifie les fichiers `/etc/resolv.conf` et `/run/systemd/resolve/resolv.conf` pour y trouver des serveurs de noms de bouclage, de multidiffusion ou de liaison locale. 
Si de telles entrées sont présentes, le fichier de configuration n'est pas utilisé, car elles ne fonctionneraient pas correctement dans les pods qui https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy[héritent de la configuration de la résolution de noms de] leur nœud.
Si aucun fichier resolv.conf utilisable n'est trouvé, K3s affiche un message d'avertissement dans les journaux et génère un fichier resolv.conf fictif qui utilise `8.8.8.8` et `2001:4860:4860::8888` comme serveurs de noms.

Si vous souhaitez fournir à K3s une autre configuration de résolveur sans modifier les fichiers de configuration du système, vous pouvez utiliser l'option `--resolv-conf` pour spécifier le chemin d'accès à un fichier approprié.
Les fichiers de configuration du résolveur spécifiés manuellement ne sont pas soumis aux contrôles de viabilité.

=== Importations de configurations personnalisées CoreDNS

Afin de personnaliser la configuration de CoreDNS, vous pouvez créer un ConfigMap nommé `coredns-custom` dans l'espace de noms `kube-system`.
Les clés correspondant à `*.override` sont importées dans le bloc serveur `:.53`.
Des blocs serveurs supplémentaires peuvent être placés dans les clés correspondant à `*.server`.
Du contenu supplémentaire (fichiers de zone, etc.) peut également être présent et est monté sous `/etc/coredns/custom` dans les pods coredns.

Voici un exemple de ConfigMap qui transmet les consultations de `example.com` à un serveur de noms situé à `10.0.0.1`, et qui dessert `example.net` à partir d'un fichier texte https://datatracker.ietf.org/doc/html/rfc1035#section-5[1035] conforme à la RFC:

[,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  example-com.override: |
    forward example.com 10.0.0.1
  example-net.server: |
    example.net:53 {
      log
      errors
      file /etc/coredns/custom/db.example.net
    }
  db.example.net: |
    $ORIGIN example.net.
    @       3600 IN SOA    sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600
            3600 IN NS     a.iana-servers.net.
            3600 IN NS     b.iana-servers.net.
    www          IN A      127.0.0.1
                 IN AAAA   ::1
----

== Configuration d'un proxy HTTP

Si vous utilisez K3s dans un environnement qui ne dispose d'une connectivité externe qu'à travers un proxy HTTP, vous pouvez configurer vos paramètres de proxy sur le service systemd de K3s. Ces paramètres de proxy seront ensuite utilisés dans les K3 et transmis au containerd et au kubelet intégrés. 

[NOTE]
====
La configuration du proxy et les autres variables d'environnement de l'hôte ne sont PAS transmises aux Pods.
====

Le script d'installation de K3s prendra automatiquement les variables `HTTP_PROXY`, `HTTPS_PROXY` et `NO_PROXY`, ainsi que les variables `CONTAINERD_HTTP_PROXY`, `CONTAINERD_HTTPS_PROXY` et `CONTAINERD_NO_PROXY` du shell actuel, si elles sont présentes, et les écrira dans le fichier d'environnement de votre service systemd, généralement :

* `/etc/systemd/system/k3s.service.env`
* `/etc/systemd/system/k3s-agent.service.env`

Bien entendu, vous pouvez également configurer le proxy en modifiant ces fichiers.

K3s ajoutera automatiquement les plages d'IP de Pod et de Service internes du cluster et le domaine DNS du cluster à la liste des entrées `NO_PROXY`. Vous devez vous assurer que les plages d'adresses IP utilisées par les nœuds Kubernetes eux-mêmes (c'est-à-dire les IP publiques et privées des nœuds) sont incluses dans la liste `NO_PROXY`, ou que les nœuds peuvent être atteints par le biais du proxy.

----
HTTP_PROXY=http://your-proxy.example.com:8888
HTTPS_PROXY=http://your-proxy.example.com:8888
NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
----

Si vous souhaitez configurer les paramètres du proxy pour containerd sans affecter K3s et le Kubelet, vous pouvez préfixer les variables avec `CONTAINERD_`:

----
CONTAINERD_HTTP_PROXY=http://your-proxy.example.com:8888
CONTAINERD_HTTPS_PROXY=http://your-proxy.example.com:8888
CONTAINERD_NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
----

== Utiliser Docker comme moteur d'exécution du conteneur

K3s inclut et utilise par défaut https://containerd.io/[containerd], un moteur d'exécution de conteneur standard.
Depuis Kubernetes 1.24, le Kubelet n'inclut plus dockershim, le composant qui permet au kubelet de communiquer avec dockerd.
K3s 1.24 et plus incluent https://github.com/Mirantis/cri-dockerd[cri-dockerd], qui permet une mise à jour transparente depuis les versions précédentes de K3s tout en continuant à utiliser le runtime de conteneur Docker.

Pour utiliser Docker au lieu de containerd :

. Installer Docker sur le nœud K3s. L'un des Docker de Rancher https://github.com/rancher/install-docker[scripts d'installation de] peut être utilisé pour installer Docker :
+
[,bash]
----
curl https://releases.rancher.com/install-docker/20.10.sh | sh
----

. Installez les K3 en utilisant l'option `--docker`:
+
[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - --docker
----

. Confirmez que le cluster est disponible :
+
[,bash]
----
$ sudo k3s kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-6d59f47c7-lncxn   1/1     Running     0          51s
kube-system   metrics-server-7566d596c8-9tnck          1/1     Running     0          51s
kube-system   helm-install-traefik-mbkn9               0/1     Completed   1          51s
kube-system   coredns-8655855d6-rtbnb                  1/1     Running     0          51s
kube-system   svclb-traefik-jbmvl                      2/2     Running     0          43s
kube-system   traefik-758cd5fc85-2wz97                 1/1     Running     0          43s
----

. Confirmez que les conteneurs Docker sont en cours d'exécution :
+
[,bash]
----
$ sudo docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED              STATUS              PORTS               NAMES
3e4d34729602        897ce3c5fc8f              "entry"                  About a minute ago   Up About a minute                       k8s_lb-port-443_svclb-traefik-jbmvl_kube-system_d46f10c6-073f-4c7e-8d7a-8e7ac18f9cb0_0
bffdc9d7a65f        rancher/klipper-lb        "entry"                  About a minute ago   Up About a minute                       k8s_lb-port-80_svclb-traefik-jbmvl_kube-system_d46f10c6-073f-4c7e-8d7a-8e7ac18f9cb0_0
436b85c5e38d        rancher/library-traefik   "/traefik --configfi…"   About a minute ago   Up About a minute                       k8s_traefik_traefik-758cd5fc85-2wz97_kube-system_07abe831-ffd6-4206-bfa1-7c9ca4fb39e7_0
de8fded06188        rancher/pause:3.1         "/pause"                 About a minute ago   Up About a minute                       k8s_POD_svclb-traefik-jbmvl_kube-system_d46f10c6-073f-4c7e-8d7a-8e7ac18f9cb0_0
7c6a30aeeb2f        rancher/pause:3.1         "/pause"                 About a minute ago   Up About a minute                       k8s_POD_traefik-758cd5fc85-2wz97_kube-system_07abe831-ffd6-4206-bfa1-7c9ca4fb39e7_0
ae6c58cab4a7        9d12f9848b99              "local-path-provisio…"   About a minute ago   Up About a minute                       k8s_local-path-provisioner_local-path-provisioner-6d59f47c7-lncxn_kube-system_2dbd22bf-6ad9-4bea-a73d-620c90a6c1c1_0
be1450e1a11e        9dd718864ce6              "/metrics-server"        About a minute ago   Up About a minute                       k8s_metrics-server_metrics-server-7566d596c8-9tnck_kube-system_031e74b5-e9ef-47ef-a88d-fbf3f726cbc6_0
4454d14e4d3f        c4d3d16fe508              "/coredns -conf /etc…"   About a minute ago   Up About a minute                       k8s_coredns_coredns-8655855d6-rtbnb_kube-system_d05725df-4fb1-410a-8e82-2b1c8278a6a1_0
c3675b87f96c        rancher/pause:3.1         "/pause"                 About a minute ago   Up About a minute                       k8s_POD_coredns-8655855d6-rtbnb_kube-system_d05725df-4fb1-410a-8e82-2b1c8278a6a1_0
4b1fddbe6ca6        rancher/pause:3.1         "/pause"                 About a minute ago   Up About a minute                       k8s_POD_local-path-provisioner-6d59f47c7-lncxn_kube-system_2dbd22bf-6ad9-4bea-a73d-620c90a6c1c1_0
64d3517d4a95        rancher/pause:3.1         "/pause"
----

== Utiliser etcdctl

etcdctl fournit une interface de commande pour interagir avec les serveurs etcd. K3s n'intègre pas etcdctl.

Si vous souhaitez utiliser etcdctl pour interagir avec le etcd intégré de K3s, installez etcdctl en utilisant la https://etcd.io/docs/latest/install/[documentation officielle de].

[,bash]
----
ETCD_VERSION="v3.5.5"
ETCD_URL="https://github.com/etcd-io/etcd/releases/download/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-amd64.tar.gz"
curl -sL ${ETCD_URL} | sudo tar -zxv --strip-components=1 -C /usr/local/bin
----

Vous pouvez ensuite utiliser etcdctl en le configurant pour qu'il utilise les certificats et les clés gérés par K3s pour l'authentification :

[,bash]
----
sudo etcdctl version \
  --cacert=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt \
  --cert=/var/lib/rancher/k3s/server/tls/etcd/client.crt \
  --key=/var/lib/rancher/k3s/server/tls/etcd/client.key
----

== Configuration de containerd

[IMPORTANT]
.Version Gate
====
K3s inclut containerd 2.0 à partir des versions de février 2025 : v1.31.6+k3s1 et v1.32.2+k3s1.
Sachez que containerd 2.0 préfère la version 3 de la configuration, tandis que containerd 1.7 préfère la version 2 de la configuration.
====

K3s génère un fichier de configuration pour containerd à l'adresse `/var/lib/rancher/k3s/agent/etc/containerd/config.toml`, en utilisant des valeurs spécifiques à la configuration actuelle du cluster et des nœuds.

Pour une personnalisation avancée, vous pouvez créer un modèle de configuration containerd dans le même répertoire :

* Pour containerd 2.0, placez un modèle de configuration de la version 3 dans `config-v3.toml.tmpl`.
+
Voir la https://github.com/containerd/containerd/blob/release/2.0/docs/cri/config.md[documentation de] pour plus d'informations.
* Pour containerd 1.7 et les versions antérieures, placez un modèle de configuration de la version 2 dans `config.toml.tmpl`.
+
Voir la https://github.com/containerd/containerd/blob/release/1.7/docs/cri/config.md[documentation] pour plus d'informations.

Containerd 2.0 est rétrocompatible avec les versions antérieures de la configuration, et k3s continuera à rendre la configuration de l'ancienne version 2 à partir de `config.toml.tmpl` si `config-v3.toml.tmpl` n'est pas trouvé.

Le fichier modèle est rendu dans la configuration de containerd à l'aide de la bibliothèque https://pkg.go.dev/text/template[`text/template`] bibliothèque.
Voir `ContainerdConfigTemplateV3` et `ContainerdConfigTemplate` dans https://github.com/k3s-io/k3s/blob/main/pkg/agent/templates/templates.go[`templates.go`] pour le contenu du modèle par défaut.
Le modèle est exécuté avec une https://github.com/k3s-io/k3s/blob/main/pkg/agent/templates/templates.go#L22-L33[`ContainerdConfig`] comme valeur de point (argument de données).

### Modèle de base

Vous pouvez étendre le modèle de base de K3s au lieu de copier-coller le modèle de stock complet à partir du code source de K3s. C'est utile si vous avez seulement besoin de compléter la configuration existante en ajoutant quelques lignes supplémentaires avant ou après les valeurs par défaut.

[,toml]
./var/lib/rancher/k3s/agent/etc/containerd/config-v3.toml.tmpl
----
{{ template "base" . }}

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.'custom']
  runtime_type = "io.containerd.runc.v2"
[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.'custom'.options]
  BinaryName = "/usr/bin/custom-container-runtime"
  SystemdCgroup = true
----

[WARNING]
====
Pour obtenir les meilleurs résultats, ne vous contentez PAS de copier une page `config.toml` dans le modèle et d'y apporter les modifications souhaitées. Utilisez le modèle de base ou fournissez un modèle complet basé sur les valeurs par défaut de k3s mentionnées ci-dessus.
====

== Prise en charge de l'exécution des conteneurs alternatifs

K3s détectera automatiquement les exécutions de conteneurs alternatifs s'ils sont présents lors du démarrage de K3s. Les moteurs d'exécution de conteneurs pris en charge sont les suivants :

----
crun, lunatic, nvidia, nvidia-cdi, nvidia-experimental, slight, spin, wasmedge, wasmer, wasmtime, wws
----

K3s utilise la variable d'environnement `PATH` du service pour rechercher les exécutables du conteneur.
Si un moteur d'exécution de conteneur installé n'est pas détecté par K3s, assurez-vous qu'il est présent dans un chemin d'accès au système, qui comprend généralement :
`/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin`

=== NVIDIA Container Runtime

Les GPU NVIDIA nécessitent l'installation du NVIDIA Container Runtime afin de planifier et d'exécuter des charges de travail accélérées dans les pods. Pour utiliser les GPU NVIDIA avec les K3, procédez comme suit :

. Installez le dépôt de paquets nvidia-container sur le nœud en suivant les instructions à l'adresse suivante :
 https://nvidia.github.io/libnvidia-container/
. Installez les paquets d'exécution du conteneur nvidia. Par exemple :
`apt install -y nvidia-container-runtime cuda-drivers-fabricmanager-515 nvidia-headless-515-server`
. xref:installation/installation.adoc[Installez K3s], ou redémarrez-le s'il est déjà installé.
. Confirmez que l'exécution du conteneur nvidia a été trouvée par k3s :
 `grep nvidia /var/lib/rancher/k3s/agent/etc/containerd/config.toml`

Si ces étapes sont suivies correctement, K3s ajoutera automatiquement les runtimes NVIDIA à la configuration du conteneur, en fonction des exécutables trouvés.
2 K3s inclut des définitions de Kubernetes RuntimeClass pour tous les runtimes alternatifs pris en charge. Vous pouvez sélectionner l'un d'entre eux pour remplacer `runc` en tant que durée d'exécution par défaut sur un nœud en définissant la valeur `--default-runtime` via l'interface CLI de k3s ou le fichier de configuration.

Si vous n'avez pas modifié la durée d'exécution par défaut sur vos nœuds GPU, vous devez demander explicitement la durée d'exécution NVIDIA en définissant `runtimeClassName: nvidia` dans la spécification Pod :

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nbody-gpu-benchmark
  namespace: default
spec:
  restartPolicy: OnFailure
  runtimeClassName: nvidia
  containers:
  - name: cuda-container
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody
    args: ["nbody", "-gpu", "-benchmark"]
    resources:
      limits:
        nvidia.com/gpu: 1
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: all
----

Notez que le NVIDIA Container Runtime est également fréquemment utilisé avec https://github.com/NVIDIA/k8s-device-plugin/[NVIDIA Device Plugin], avec des modifications pour s'assurer que les spécifications du pod incluent `runtimeClassName: nvidia`, comme mentionné ci-dessus.

[#_running_agentless_servers_experimental]
== Exécution de serveurs sans agent (expérimental)

WARNING: Cette fonctionnalité est expérimentale.

Lorsqu'ils sont démarrés avec l'option `--disable-agent`, les serveurs n'exécutent pas de kubelet, de runtime de conteneur ou de CNI. Ils n'enregistrent pas de ressource Node dans le cluster et n'apparaissent pas dans les résultats de `kubectl get nodes`.
Parce qu'ils n'hébergent pas de kubelet, ils ne peuvent pas exécuter de pods ou être gérés par des opérateurs qui s'appuient sur l'énumération des nœuds du cluster, y compris le contrôleur etcd intégré et le contrôleur de mise à niveau du système.

L'exécution de serveurs sans agent peut être avantageuse si vous souhaitez empêcher les agents et les charges de travail de découvrir vos nœuds du plan de contrôle, au prix d'une augmentation de la charge administrative due à l'absence d'assistance de l'opérateur de la grappe.

Par défaut, l'apiserver sur les serveurs sans agent ne pourra pas établir de connexions sortantes avec les webhooks d'admission ou les apiservices agrégés fonctionnant au sein du cluster. Pour remédier à ce problème, définissez l'indicateur de serveur `--egress-selector-mode` sur `pod` ou `cluster`. Si vous modifiez cet indicateur sur un cluster existant, vous devrez redémarrer tous les nœuds du cluster pour que l'option prenne effet.

== Exécution de serveurs sans racine (expérimental)

WARNING: Cette fonctionnalité est expérimentale.

Le mode sans racine permet d'exécuter les serveurs K3s en tant qu'utilisateur non privilégié, de manière à protéger la racine réelle de l'hôte contre d'éventuelles attaques par effraction des conteneurs.

Voir https://rootlesscontaine.rs/ pour en savoir plus sur Rootless Kubernetes.

[#_known_issues_with_rootless_mode]
=== Problèmes connus avec le mode sans racine

* *Ports*
+
Lors d'un fonctionnement sans racine, un nouvel espace de noms réseau est créé.  Cela signifie que l'instance de K3 fonctionne avec un réseau relativement détaché de l'hôte.
Le seul moyen d'accéder aux services exécutés dans K3s à partir de l'hôte est de mettre en place des transferts de port vers l'espace de noms du réseau K3s.
Le K3s sans racine comprend un contrôleur qui liera automatiquement le port 6443 et les ports de service inférieurs à 1024 à l'hôte avec un décalage de 10000.
+
Par exemple, un service sur le port 80 deviendra 10080 sur l'hôte, mais 8080 deviendra 8080 sans décalage. Actuellement, seuls les services LoadBalancer sont automatiquement liés.

* *Cgroups*
+
Cgroup v1 et Hybrid v1/v2 ne sont pas pris en charge ; seul Cgroup v2 est pris en charge. Si K3s ne démarre pas en raison de cgroups manquants lorsqu'il est exécuté sans racine, il est probable que votre nœud soit en mode hybride et que les cgroups "manquants" soient toujours liés à un contrôleur v1.

* *Cluster multi-nœuds/multi-processus*
+
Les grappes sans racine à plusieurs nœuds, ou plusieurs processus k3s sans racine sur le même nœud, ne sont pas pris en charge actuellement. Voir https://github.com/k3s-io/k3s/issues/6488#issuecomment-1314998091[] #6488 pour plus de détails.

=== Démarrage des serveurs sans racine

* Activer la délégation du cgroup v2, voir https://rootlesscontaine.rs/getting-started/common/cgroup2/.
Cette étape est nécessaire ; le kubelet sans racine ne pourra pas démarrer si les bons cgroups ne sont pas délégués.
* Télécharger `k3s-rootless.service` à partir de https://github.com/k3s-io/k3s/blob/main/k3s-rootless.service[`https://github.com/k3s-io/k3s/blob/<VERSION>/k3s-rootless.service`].
Veillez à utiliser la même version de `k3s-rootless.service` et `k3s`.
* Installer `k3s-rootless.service` sur `~/.config/systemd/user/k3s-rootless.service`.
L'installation de ce fichier en tant que service à l'échelle du système (`/etc/systemd/...`) n'est pas prise en charge.
En fonction du chemin du binaire `k3s`, il se peut que vous deviez modifier la ligne `ExecStart=/usr/local/bin/k3s ...` du fichier.
* Exécuter `systemctl --user daemon-reload`
* Exécuter `systemctl --user enable --now k3s-rootless`
* Lancez `KUBECONFIG=~/.kube/k3s.yaml kubectl get pods -A`, et assurez-vous que les pods sont en cours d'exécution.

NOTE: N'essayez pas d'exécuter `k3s server --rootless` sur un terminal, car les sessions de terminal ne permettent pas la délégation de cgroup v2.
Si vous avez vraiment besoin de l'essayer sur un terminal, utilisez `systemd-run --user -p Delegate=yes --tty k3s server --rootless` pour l'intégrer dans un champ d'application systemd.

=== Configuration avancée sans racine

Rootless K3s utilise https://github.com/rootless-containers/rootlesskit[rootlesskit] et https://github.com/rootless-containers/slirp4netns[slirp4netns] pour communiquer entre les espaces de noms de l'hôte et de l'utilisateur.
Certaines des configurations utilisées par rootlesskit et slirp4nets peuvent être définies par des variables d'environnement. La meilleure façon de les définir est de les ajouter au champ `Environment` de l'unité systemd k3s-rootless.

|===
| Variable | Défaut | Description

| `K3S_ROOTLESS_MTU`
| 1500
| Définit le MTU pour les interfaces virtuelles slirp4netns.

| `K3S_ROOTLESS_CIDR`
| 10.41.0.0/16
| Définit le CIDR utilisé par les interfaces virtuelles de slirp4netns.

| `K3S_ROOTLESS_ENABLE_IPV6`
| autotélique
| Active la prise en charge de slirp4netns IPv6. Si elle n'est pas spécifiée, elle est automatiquement activée si K3s est configuré pour un fonctionnement en double pile.

| `K3S_ROOTLESS_PORT_DRIVER`
| builtin
| Sélectionne le pilote de port sans racine ; soit `builtin` ou `slirp4netns`. Builtin est plus rapide, mais masque l'adresse source originale des paquets entrants.

| `K3S_ROOTLESS_DISABLE_HOST_LOOPBACK`
| vrai
| Contrôle si l'accès à l'adresse loopback de l'hôte via l'interface de la passerelle est activé ou non. Il est recommandé de ne pas modifier ce paramètre pour des raisons de sécurité.
|===

=== Résolution des problèmes liés à l'absence de racines

* Exécutez `systemctl --user status k3s-rootless` pour vérifier l'état du démon
* Exécutez `journalctl --user -f -u k3s-rootless` pour voir le journal du démon
* Voir aussi https://rootlesscontaine.rs/

== Étiquettes de nœuds et taches

Les agents K3s peuvent être configurés avec les options `--node-label` et `--node-taint` qui ajoutent une étiquette et une taint au kubelet. Les deux options n'ajoutent des étiquettes et/ou des taints qu'au moment xref:cli/agent.adoc#_node_labels_and_taints_for_agents[de l'enregistrement], de sorte qu'elles ne peuvent être définies que lorsque le nœud est joint pour la première fois à la grappe.

Toutes les versions actuelles de Kubernetes empêchent les nœuds de s'enregistrer avec la plupart des étiquettes avec les préfixes `kubernetes.io` et `k8s.io`, y compris l'étiquette `kubernetes.io/role`. Si vous tentez de démarrer un nœud avec une étiquette non autorisée, les K3 ne démarreront pas. Comme l'indiquent les auteurs de Kubernetes :

____
Les nœuds ne sont pas autorisés à revendiquer leurs propres étiquettes de rôle. Les rôles des nœuds sont généralement utilisés pour identifier les types de nœuds privilégiés ou du plan de contrôle, et le fait de permettre aux nœuds de s'étiqueter eux-mêmes dans ce pool permet à un nœud compromis d'attirer de manière triviale des charges de travail (comme des démons du plan de contrôle) qui confèrent un accès à des informations d'identification à privilèges plus élevés.
____

Voir https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/279-limit-node-access/README.md#proposal[SIG-Auth KEP 279] pour plus d'informations.

Si vous souhaitez modifier les étiquettes de nœuds et les taches après l'enregistrement du nœud, ou ajouter des étiquettes réservées, vous devez utiliser `kubectl`. Reportez-vous à la documentation officielle de Kubernetes pour plus de détails sur l'ajout de https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[node labels.] taints et https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#add-a-label-to-a-node[]

== Démarrer le service avec le script d'installation

Le script d'installation détectera automatiquement si votre système d'exploitation utilise systemd ou openrc et activera et démarrera le service dans le cadre du processus d'installation.

* Lors de l'exécution avec openrc, les journaux seront créés à l'adresse `/var/log/k3s.log`.
* Lorsqu'ils sont exécutés avec systemd, les journaux sont créés à l'adresse `/var/log/syslog` et consultés à l'adresse `journalctl -u k3s` (ou `journalctl -u k3s-agent` sur les agents).

Exemple de désactivation du démarrage automatique et de l'activation des services à l'aide du script d'installation :

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_SKIP_START=true INSTALL_K3S_SKIP_ENABLE=true sh -
----

[#_running_k3s_in_docker]
== Exécution de K3s dans Docker

Il existe plusieurs façons d'exécuter les K3 dans Docker :

[tabs]
======
K3d::
+
--
https://github.com/k3d-io/k3d[k3d] est un utilitaire conçu pour faire fonctionner facilement des clusters K3s multi-nœuds dans Docker.

k3d permet de créer très facilement des clusters k3s à un ou plusieurs nœuds dans docker, par exemple pour le développement local sur Kubernetes.

Voir la documentation d' https://k3d.io/#installation[installation] pour plus d'informations sur l'installation et l'utilisation de k3d.
--

Docker::
+
--
Pour utiliser Docker, des images `rancher/k3s` sont également disponibles pour exécuter le serveur et l'agent K3s.
En utilisant la commande `docker run`:

[,bash]
----
sudo docker run \
  --privileged \
  --name k3s-server-1 \
  --hostname k3s-server-1 \
  -p 6443:6443 \
  -d rancher/k3s:v1.24.10-k3s1 \
  server
----

[NOTE]
=====
Vous devez spécifier une version K3s valide comme balise ; la balise `latest` n'est pas gérée. +
Les images Docker n'autorisent pas le signe `+` dans les balises, utilisez plutôt `-` dans la balise.
=====

Une fois que K3s est opérationnel, vous pouvez copier l'admin kubeconfig hors du conteneur Docker pour l'utiliser :

[,bash]
----
sudo docker cp k3s-server-1:/etc/rancher/k3s/k3s.yaml ~/.kube/config
----
--
======

[#_selinux_support]
== Support SELinux

Si vous installez K3s sur un système où SELinux est activé par défaut (comme CentOS), vous devez vous assurer que les politiques SELinux appropriées ont été installées.

[tabs]
======
Installation automatique::
+
Le xref:installation/configuration.adoc#_configuration_with_install_script[script d'installation installera] automatiquement le RPM SELinux à partir du dépôt Rancher RPM s'il se trouve sur un système compatible et s'il ne s'agit pas d'une installation air-gapped. L'installation automatique peut être ignorée en réglant `INSTALL_K3S_SKIP_SELINUX_RPM=true`.

Installation manuelle::
+
--
Les politiques nécessaires peuvent être installées à l'aide des commandes suivantes :

[,bash]
----
yum install -y container-selinux selinux-policy-base
yum install -y https://rpm.rancher.io/k3s/latest/common/centos/9/noarch/k3s-selinux-1.6-1.el9.noarch.rpm
----

Pour forcer le script d'installation à enregistrer un avertissement plutôt qu'un échec, vous pouvez définir la variable d'environnement suivante : `INSTALL_K3S_SELINUX_WARN=true`.
--
======

=== Activation de la mise en œuvre de SELinux

Pour tirer parti de SELinux, spécifiez le drapeau `--selinux` lors du démarrage des serveurs et agents K3s ou définissez la variable d'environnement `K3S_SELINUX=true`\...

Cette option peut également être spécifiée dans le xref:installation/configuration.adoc#_configuration_file[fichier de configuration de] K3s.

----
selinux: true
----

L'utilisation d'une adresse `--data-dir` personnalisée sous SELinux n'est pas prise en charge. Pour la personnaliser, vous devrez probablement rédiger votre propre politique. Pour vous guider, vous pouvez vous référer au dépôt https://github.com/containers/container-selinux[containers/container-selinux], qui contient les fichiers de politique SELinux pour les Container Runtimes, et au dépôt https://github.com/k3s-io/k3s-selinux[] k3s-io/k3s-selinux, qui contient la politique SELinux pour K3s.

== Activation de l'extraction paresseuse d'eStargz (expérimental)

=== Qu'est-ce que le lazy pulling et l'eStargz ?

L'extraction des images est l'une des étapes les plus fastidieuses du cycle de vie des conteneurs.
Selon https://www.usenix.org/conference/fast16/technical-sessions/presentation/harter[Harteret, al..,]

____
le retrait des paquets représente 76 % du temps de démarrage des conteneurs, mais seulement 6,4 % de ces données sont lues
____

Pour résoudre ce problème, k3s prend en charge, à titre expérimental, l'_extraction paresseuse du_ contenu des images.
Cela permet à k3s de démarrer un conteneur avant que l'image entière n'ait été tirée.
Au lieu de cela, les morceaux de contenu nécessaires (par exemple, des fichiers individuels) sont récupérés à la demande.
Cette technique permet de réduire le temps de latence au démarrage du conteneur, en particulier pour les images de grande taille.

Pour permettre l'extraction paresseuse, l'image cible doit être formatée comme suit https://github.com/containerd/stargz-snapshotter/blob/main/docs/stargz-estargz.md[_eStargz_].
Il s'agit d'un format d'image alternatif à l'OCI mais compatible à 100 % avec l'OCI pour le lazy pulling.
En raison de la compatibilité, eStargz peut être poussé vers des registres de conteneurs standard (par exemple ghcr.io) et _peut être exécuté_ même avec des moteurs d'exécution agnostiques à eStargz.

eStargz est développé sur la base du https://github.com/google/crfs[format], mais il est doté de fonctionnalités pratiques telles que la vérification du contenu et l'optimisation des performances.
Pour plus de détails sur le lazy pulling et eStargz, veuillez vous référer au https://github.com/containerd/stargz-snapshotter[dépôt du projet].

=== Configurer le k3s pour l'extraction paresseuse de l'eStargz

Comme indiqué ci-dessous, l'option `--snapshotter=stargz` est nécessaire pour le serveur et l'agent k3s.

[,bash]
----
k3s server --snapshotter=stargz
----

Avec cette configuration, vous pouvez effectuer une extraction paresseuse pour les images formatées eStargz.
L'exemple suivant de manifeste Pod utilise l'image `node:13.13.0` (`ghcr.io/stargz-containers/node:13.13.0-esgz`) formatée par eStargz.
Lorsque le snapshotter stargz est activé, K3s effectue un lazy pulling pour cette image.

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nodejs
spec:
  containers:
  - name: nodejs-estargz
    image: ghcr.io/stargz-containers/node:13.13.0-esgz
    command: ["node"]
    args:
    - -e
    - var http = require('http');
      http.createServer(function(req, res) {
        res.writeHead(200);
        res.end('Hello World!\n');
      }).listen(80);
    ports:
    - containerPort: 80
----

[#_additional_logging_sources]
== Sources d'enregistrement supplémentaires

https://documentation.suse.com/cloudnative/rancher-manager/latest/en/observability/logging/logging-helm-chart-options.html[journalisation Rancher]La  pour les K3 peut être installée sans utiliser Rancher. Pour ce faire, il convient d'exécuter les instructions suivantes :

[,bash]
----
helm repo add rancher-charts https://charts.rancher.io
helm repo update
helm install --create-namespace -n cattle-logging-system rancher-logging-crd rancher-charts/rancher-logging-crd
helm install --create-namespace -n cattle-logging-system rancher-logging --set additionalLoggingSources.k3s.enabled=true rancher-charts/rancher-logging
----

== Enregistrement supplémentaire de la politique de réseau

Les paquets abandonnés par les politiques de réseau peuvent être enregistrés. Le paquet est envoyé à l'action NFLOG d'iptables, qui affiche les détails du paquet, y compris la politique de réseau qui l'a bloqué.

Si le trafic est important, le nombre de messages de journal peut être très élevé. Pour contrôler le taux de journalisation par politique, définissez les paramètres `limit` et `limit-burst` iptables en ajoutant les annotations suivantes à la politique de réseau en question :

* `kube-router.io/netpol-nflog-limit=<LIMIT-VALUE>`
* `kube-router.io/netpol-nflog-limit-burst=<LIMIT-BURST-VALUE>`

Les valeurs par défaut sont `limit=10/minute` et `limit-burst=10`. Consultez le https://www.netfilter.org/documentation/HOWTO/packet-filtering-HOWTO-7.html#:~:text=restrict%20the%20rate%20of%20matches[manuel] pour plus d'informations sur le format et les valeurs possibles de ces champs.

Pour convertir les paquets NFLOG en entrées de journal, installez ulogd2 et configurez `[log1]` pour lire sur `group=100`. Ensuite, redémarrez le service ulogd2 pour que la nouvelle configuration soit prise en compte.
Lorsqu'un paquet est bloqué par les règles de la politique de réseau, un message apparaît sur `/var/log/ulog/syslogemu.log`.

Les paquets envoyés au socket netlink de NFLOG peuvent également être lus en utilisant des outils en ligne de commande comme tcpdump ou tshark :

[,bash]
----
tcpdump -ni nflog:100
----

Bien que plus facilement disponible, tcpdump n'indiquera pas le nom de la politique de réseau qui a bloqué le paquet. Utilisez plutôt la commande tshark de wireshark pour afficher l'en-tête complet du paquet NFLOG, y compris le champ `nflog.prefix` qui contient le nom de la politique.

La journalisation des paquets abandonnés dans le cadre de la stratégie réseau ne prend pas en charge les https://github.com/k3s-io/k3s/issues/8008[stratégies] adresse. Si vous comptez sur l'enregistrement des paquets abandonnés à des fins de diagnostic ou d'audit, assurez-vous que vos politiques incluent un sélecteur de pods qui correspond aux pods concernés.
