= {k3s-product-name}
:page-languages: [en, ja, ko, zh]
:revdate: 2024-10-23
:page-revdate: {revdate}
:page-role: -toc

K3s est un projet sandbox officiel https://www.cncf.io[CNCF] qui fournit une distribution Kubernetes certifiée légère mais puissante, conçue pour les charges de travail de production à travers des ressources limitées, des sites distants ou sur des appareils IoT. Utilisé avec SUSE® Rancher Prime, K3s est une distribution Kubernetes simple à installer, légère mais à haute disponibilité, qui peut être facilement gérée au sein de la plate-forme d'orchestration Rancher.

== Caractéristiques principales

* Distribué sous la forme d'un binaire unique ou d'une image conteneur minimale.
* Stockage de données léger basé sur sqlite3 comme backend de stockage par défaut. etcd3, MySQL, et Postgres sont également disponibles.
* Enveloppé dans un lanceur simple qui gère une grande partie de la complexité de TLS et des options.
* Sécurisé par défaut avec des valeurs par défaut raisonnables pour les environnements légers.
* Le fonctionnement de tous les composants du plan de contrôle de Kubernetes est encapsulé dans un seul binaire et un seul processus, ce qui permet à K3s d'automatiser et de gérer des opérations de cluster complexes comme la distribution de certificats.
* Les dépendances externes ont été réduites au minimum ; les seules exigences sont un noyau moderne et des montages cgroup.
* Compile les dépendances nécessaires pour faciliter la création d'un cluster "batteries incluses" :
 ** containerd / cri-dockerd container runtime (CRI)
 ** Interface de réseau de conteneurs Flannel (CNI)
 ** CoreDNS Cluster DNS
 ** Contrôleur Traefik Ingress
 ** Contrôleur ServiceLB Load-Balancer
 ** Contrôleur de politique réseau Kube-router
 ** Local-path-provisioner Contrôleur de volume persistant
 ** Miroir de registre d'images de conteneurs distribués Spegel
 ** Utilitaires pour les hôtes (iptables, socat, etc.)

== Idéal pour :

* Bord
* Homelab
* Internet des objets (IoT)
* Intégration continue (CI)
* Développement
* Ordinateurs monocartes (ARM)
* Environnements à air comprimé
* K8s embarqués
* Situations dans lesquelles un doctorat en clusterologie K8s n'est pas envisageable
