= Guide de démarrage rapide
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Ce guide vous aidera à lancer rapidement un cluster avec les options par défaut. Assurez-vous que vos nœuds répondent aux xref:installation/requirements.adoc[exigences] avant de poursuivre.

* Consultez la page xref:installation/installation.adoc[Installation] pour plus de détails sur l'installation et la configuration de K3s.
* Pour plus d'informations sur la manière dont les composants de K3s fonctionnent ensemble, consultez la page xref:architecture.adoc[Architecture.] 
* Si vous ne connaissez pas Kubernetes, les https://kubernetes.io/docs/tutorials/kubernetes-basics/[documents officiels de Kubernetes (] contiennent d'excellents tutoriels couvrant les bases avec lesquelles tous les administrateurs de clusters devraient être familiarisés.

[IMPORTANT]
====
Vous pouvez utiliser n'importe quelle version de K3s Prime listée sur l'URL Prime Artifacts pour les actifs mentionnés dans ces étapes. Pour en savoir plus sur l'URL Prime Artifacts, consultez notre https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[documentation]. L'authentification est requise. Utilisez vos identifiants SUSE https://scc.suse.com/home[Customer Center (SCC)] pour vous connecter.
====


== Script d'installation

{k3s-product-name} fournit un script d'installation qui est un moyen pratique de l'installer en tant que service sur les systèmes basés sur systemd ou openrc. Ce script est disponible à l'adresse https://get.k3s.io. Pour installer {k3s-product-name} à l'aide de cette méthode, procédez comme suit :

Exécutez le programme d'installation, où `INSTALL_K3S_ARTIFACT_URL` est l' https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[URL de] et `INSTALL_K3S_CHANNEL` est un canal de diffusion auquel vous pouvez vous abonner et qui est par défaut `stable`. Dans cet exemple, `INSTALL_K3S_CHANNEL="latest"` vous donne la dernière version de {k3s-product-name}.

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL="latest" sh -
----
Si vous souhaitez spécifier une version, définissez la variable d'environnement `INSTALL_RKE2_VERSION`:

[,bash]
----
curl -sfL https://get.k3s.io/ | sudo INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION="<VERSION>" sh -
----

Après avoir exécuté cette installation :

* Le service K3s sera configuré pour redémarrer automatiquement après le redémarrage du nœud ou si le processus se bloque ou est tué.
* Des utilitaires supplémentaires seront installés, notamment `kubectl`, `crictl`, `ctr`, `k3s-killall.sh`, et `k3s-uninstall.sh`
* Un fichier https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[] kubeconfig sera écrit sur `/etc/rancher/k3s/k3s.yaml` et le kubectl installé par {k3s-product-name} l'utilisera automatiquement.

Une installation de serveur à nœud unique est un cluster Kubernetes entièrement fonctionnel, comprenant tous les composants de datastore, de control-plane, de kubelet et d'exécution de conteneur nécessaires pour héberger des pods de charge de travail. Il n'est pas nécessaire d'ajouter des nœuds de serveurs ou d'agents supplémentaires, mais vous pouvez le faire pour augmenter la capacité ou la redondance de votre cluster.

Pour installer des nœuds d'agent supplémentaires et les ajouter au cluster, exécutez le script d'installation avec les variables d'environnement `K3S_URL` et `K3S_TOKEN`. Voici un exemple montrant comment rejoindre un agent :

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken sh -
----

La définition du paramètre `K3S_URL` permet au programme d'installation de configurer K3s en tant qu'agent et non en tant que serveur. L'agent K3s s'enregistre auprès du serveur K3s qui écoute l'URL fournie. La valeur à utiliser pour `K3S_TOKEN` est stockée à `/var/lib/rancher/k3s/server/node-token` sur votre nœud de serveur.

[NOTE]
====
Chaque machine doit avoir un nom d'hôte unique. Si vos machines n'ont pas de nom d'hôte unique, passez la variable d'environnement `K3S_NODE_NAME` et fournissez une valeur avec un nom d'hôte valide et unique pour chaque nœud.
====


Si vous souhaitez disposer d'un plus grand nombre de nœuds de serveur, consultez les pages xref:datastore/ha-embedded.adoc[High Availability Embedded etcd] et xref:datastore/ha.adoc[High Availability External DB] pour plus d'informations.
