= Configuration du réseau avec {elemental-product-name}
:revdate: 2025-09-08
:page-revdate: {revdate}


[CAUTION]
.avertissement
====
La mise en réseau déclarative est à l'état d'*avant-première technologique* avec un support limité.
Il n'est donc pas recommandé pour les environnements de production.
====

Le xref:references/machineregistration-reference.adoc[MachineRegistration] prend en charge la mise en réseau déclarative et l'intégration avec https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220125-ipam-integration.md#ipam-provider[CAPI IPAM Providers].

== Conditions préalables

* Un serveur DHCP est toujours nécessaire pour l'enregistrement et la réinitialisation des machines au premier démarrage. C'est pourquoi la durée du bail peut être réduite au minimum, étant donné que les adresses IP pilotées par IPAM seront utilisées tout au long du cycle de vie de la machine.
* Un fournisseur IPAM de votre choix est installé sur le cluster de gestion Rancher.
Par exemple, https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster[InCluster IPAM Provider].
* https://networkmanager.dev[NetworkManager] doit être installé sur les images du système d'exploitation et peut être configuré directement à l'aide du <<_configurators,configurateur de>> réseau `nmconnections`.
Déjà inclus dans les images fournies par Elemental.
* (en option) https://github.com/suse-edge/nm-configurator/releases[nmc] peut être utilisé avec `nmc` network <<_configurators,configurator>>.
* (optionnellement) https://github.com/nmstate/nmstate/releases[nmstatectl] peut être utilisé avec `nmstate` network <<_configurators,configurator>>.

=== Installation de nmc ou nmstatectl sur les images du système d'exploitation

Lorsque vous utilisez les configurateurs `nmc` ou `nmstate`, les outils https://github.com/suse-edge/nm-configurator/releases[nmc] ou https://github.com/nmstate/nmstate/releases[nmstatectl] doivent être installés sur la machine.

Actuellement, il est possible de le faire en xref:operator-operational-tasks/custom-images.adoc#_remastering_an_os_image_with_a_custom_dockerfile[personnalisant une image Elemental OS] à l'aide d'une commande personnalisée :

[tabs]
======
nmc::
+
--
[,yaml]
----
# Install nmc
RUN curl -LO https://github.com/suse-edge/nm-configurator/releases/download/v0.3.3/nmc-linux-x86_64 && \ install -o root -g root -m 0755 nmc-linux-x86_64 /usr/sbin/nmc
----
--

nmstatectl::
+
--
[,yaml]
----
# Install nmstatectl
RUN curl -LO https://github.com/nmstate/nmstate/releases/download/v2.2.40/nmstatectl-linux-x64.zip && \ unzip nmstatectl-linux-x64.zip && \ chmod +x nmstatectl && \ mv ./nmstatectl /usr/sbin/nmstatectl && \ rm nmstatectl-linux-x64.zip
----
--
======

=== Comment installer le fournisseur IPAM de l'ICPA

La méthode recommandée pour installer un fournisseur CAPI dans Rancher est d'utiliser https://documentation.suse.com/cloudnative/cluster-api/v0.22/en/index.html[Turtles] Rancher.

Rancher Turtles permet à l'utilisateur d'installer et de gérer le cycle de vie de n'importe quel fournisseur CAPI. Pour l'installer sur votre système, veuillez suivre la https://documentation.suse.com/cloudnative/cluster-api/v0.22/en/tutorials/quickstart.html[documentation d'installation de] Rancher.

Une fois Rancher Turtles installé, l'installation d'un IPAM CAPI Provider, par exemple le https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster[InCluster IPAM Provider], peut être réalisée en appliquant la ressource suivante :

[,yaml]
----
kind: CAPIProvider
metadata:
  name: in-cluster
  namespace: default
spec:
  name: in-cluster
  type: ipam
  fetchConfig:
    url: "https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases"
  version: v0.1.0
----

==== Sans les tortues Rancher

Une autre option pour installer un fournisseur CAPI IPAM est d'appliquer directement le manifeste dans le cluster Rancher.

Il convient de noter que cette solution peut éventuellement entraîner des conflits avec les CRD et les ressources appliqués, étant donné qu'ils doivent être appliqués et maintenus manuellement.

. Les CRD `ipaddresses.ipam.cluster.x-k8s.io` et `ipaddressclaims.ipam.cluster.x-k8s.io` doivent être installés sur le cluster de gestion Rancher :
+
[,bash]
----
 kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
 kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
----

[IMPORTANT]
.info
====
Ces CRD devraient à terme faire partie de Rancher et ne pas nécessiter d'installation manuelle. Voir : https://github.com/rancher/rancher/issues/46385
====


. Installez le https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster[InCluster IPAM Provider] à partir du manifeste publié :
+
[,bash]
----
 kubectl apply -f https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/download/v0.1.0/ipam-components.yaml
----

=== Configuration du réseau

La section `network` du site `MachineRegistration` permet aux utilisateurs de définir :

. Une carte des références IPPool.
. Un modèle de configuration réseau (dans ce cas, le configurateur `nmc` est utilisé).

.exemple de MachineRegistration utilisant Declarative Networking
[,yaml]
----
include::example$network/machineregistration.yaml[]
----

Ici, nous pouvons observer qu'un seul `InClusterIPPool` a été défini, puisque nous utilisons le https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster[InCluster IPAM Provider] pour cet exemple.

Ensuite, nous allons référencer cet IPPool dans le site `MachineRegistration`. La clé de cette référence est `inventory-ip`, et nous n'aurons besoin que d'une IP par machine enregistrée. Si votre machine possède plus d'un NIC, vous pouvez définir plus de références et utiliser différents IPPools, par exemple :

[,yaml]
----
ipAddresses:
  main-nic-ip:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: elemental-inventory-pool
  secondary-nic-ip:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: elemental-inventory-pool
  private-nic-ip:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: elemental-private-pool
----

Chaque clé de référence IPPool définie peut être utilisée pour le modèle de configuration du réseau :

[,yaml]
----
config:
  dns-resolver:
    config:
      server:
      - 192.168.122.1
      search: []
  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-interface: eth0
      next-hop-address: 192.168.122.1
      metric: 150
      table-id: 254
  interfaces:
    - name: eth0
      type: ethernet
      description: Main-NIC
      state: up
      ipv4:
        enabled: true
        dhcp: false
        address:
        - ip: "{inventory-ip}"
          prefix-length: 24
      ipv6:
        enabled: false
----

L'extrait ci-dessus est presque identique à la https://github.com/suse-edge/nm-configurator?tab=readme-ov-file#unified-configurations[syntaxe de], à la seule exception de l'espace réservé à `{inventory-ip}`. Pendant les phases d'installation ou de réinitialisation des machines Elemental, le site `elemental-operator` réclamera une adresse IP du pool d'adresses IP référencé et remplacera l'adresse `{inventory-ip}` par une adresse IP réelle.

=== Adresses IPA réclamées

Le site `IPAddressClaim` suivra l'ensemble du cycle de vie du site `MachineInventory`, en veillant à ce que chaque machine enregistrée se voie attribuer des adresses IP uniques. Chaque revendication est nommée d'après le site `MachineInventory` qui l'utilise, comme `$MachineInventoryName-$IPPoolRefKey`, par exemple :

[,yaml]
----
apiVersion: ipam.cluster.x-k8s.io/v1beta1
kind: IPAddressClaim
metadata:
  finalizers:
    - ipam.cluster.x-k8s.io/ReleaseAddress
  name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c-inventory-ip
  namespace: fleet-default
  ownerReferences:
    - apiVersion: elemental.cattle.io/v1beta1
      kind: MachineInventory
      name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: elemental-inventory-pool
status:
  addressRef:
    name: m-e5331e3b-1e1b-4ce7-b080-235ed9a6d07c-inventory-ip
----

Chaque fois qu'un site `MachineInventory` est supprimé, la configuration réseau par défaut (DHCP) est rétablie, ce qui entraîne la suppression de tout profil réseau sur la machine et le redémarrage de la pile réseau. Enfin, les adresses IP attribuées seront libérées.

Pour plus d'informations et de détails sur la manière de résoudre les problèmes, veuillez consulter la xref:troubleshooting/troubleshooting-network.adoc[documentation "Troubleshooting Declarative Networking" (Résolution des problèmes liés à la mise en réseau déclarative]).

=== Configurateurs

Sur la machine Elemental, `elemental-register` peut configurer le site `NetworkManager` de différentes manières. Le configurateur utilisé est défini dans le fichier xref:references/machineregistration-reference.adoc#_config_network[MachineRegistration.spec.network]:

* https://github.com/suse-edge/nm-configurator[nmc]
* https://nmstate.io/[état-nucléaire]
* https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/nm-settings-keyfile.html[nmconnections]

[tabs]
======
nmc::
+
--
Le configurateur `nmc` utilise la https://github.com/suse-edge/nm-configurator?tab=readme-ov-file#unified-configurations[syntaxe unifiée de] pour générer les fichiers de connexion de NetworkManager.

.Exemple d'enregistrement de machine à l'aide du configurateur nmc
[,yaml]
----
include::example$network/machineregistration-nmc.yaml[]
----

--

état-nucléaire::
+
--
Le configurateur `nmstate` utilise la https://nmstate.io/examples.html[syntaxe] pour générer les fichiers de connexion de NetworkManager. Notez que https://github.com/nmstate/nmstate/releases[nmstatectl] doit être installé sur le système Elemental pour utiliser ce configurateur. Il n'est pas inclus par défaut dans les images Elemental, mais peut être installé lors de la création d'une xref:operator-operational-tasks/custom-images.adoc[image personnalisée].

.exemple de MachineRegistration utilisant le configurateur nmstate
[,yaml]
----
include::example$network/machineregistration-nmstate.yaml[]
----

--

nmconnections::
+
--
Le configurateur `nmconnections` est l'option la plus simple disponible et permet à l'utilisateur d'écrire directement des fichiers `nmconnection`. La définition de ces fichiers pour des configurations réseau complexes peut s'avérer difficile, mais il est toujours possible d'utiliser https://networkmanager.dev/docs/api/latest/nmcli.html[nmcli], ou même https://nmstate.io[nmstate], ou [nm-configurator](https://github.com/suse-edge/nm-configurator), et d'utiliser les fichiers `nmconnection` générés comme modèle. Ce configurateur n'a besoin que de `NetworkManager`, sans aucune dépendance supplémentaire. Exemple de MachineRegistration utilisant le configurateur nmconnections.

.Cliquez ici pour un exemple de MachineRegistration utilisant le configurateur nmstate
[%collapsible]
====
[,yaml]
----
include::example$network/machineregistration-nmconnections.yaml[]
----
====

--
======
