= クラスターアクセス
:page-languages: [en、ja、ko、zh]。
:revdate: 2025-09-15
:page-revdate: {revdate}

`/etc/rancher/k3s/k3s.yaml` 、Kubernetesクラスタへのアクセスを提供するために保存されたadmin kubeconfigファイルを使用することができる。このファイルは、`system:admin` ユーザーと`system:masters` グループとしてアクセスを許可します。これは、クラスタ内のすべてのリソースに無制限にアクセスできるようにKubernetesによってハードコードされています。

K3sに付属する`kubectl` コマンドは、デフォルトでこのパスからコンフィギュレーションをロードするように設定されている。kubectlやHelmのようなアップストリームのKubernetesコマンドラインツールをインストールした場合は、正しいkubeconfigパスで設定する必要がある。これは、`KUBECONFIG` 環境変数をエクスポートするか、`--kubeconfig` コマンドラインフラグを起動することで実行できる。詳細は以下の例を参照。

* KUBECONFIG環境変数をエクスポートする：
+
[,bash]
----
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
kubectl get pods --all-namespaces
helm ls --all-namespaces
----

* コマンドでkubeconfigファイルの場所を指定する：
[,bash]
----
kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get pods --all-namespaces
helm --kubeconfig /etc/rancher/k3s/k3s.yaml ls --all-namespaces
----

== kubectlで外部からクラスタにアクセスする

クラスタ外のマシンに`~/.kube/config` として`/etc/rancher/k3s/k3s.yaml` をコピーする。次に、`server` フィールドの値を K3s サーバの IP または名前で置き換えます。`kubectl` これで K3s クラスタを管理できるようになります。

[NOTE]
====
K3sは起動するたびに、管理者のkubeconfig内の証明書を自動的に更新します。このファイルのコピーを作成する場合は、インライン証明書の有効期限が切れないように、それらのコピーを手動で更新する必要がある。
====
