= Backup
:revdate: 2025-11-06
:page-revdate: {revdate}

Como o {elemental-product-name} é executado como parte do Rancher, os recursos do {elemental-product-name} são agrupados no backup do Rancher.
Para obter mais detalhes sobre as opções de backups, restauração e recuperação de desastres do Rancher, siga a oficial https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.html[documentação] Rancher.

== Instalar o operador do rancher-backup para o Rancher

Siga o https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up.html[guia de backup do] Rancher para saber como instalar e configurar o operador de backup do Rancher.


== Backup {elemental-product-name} com o operador do rancher-backup

Crie um `backup object` (adaptado às suas necessidades) para fazer backup do Rancher em execução em um cluster do Kubernetes.

[,yaml]
----
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: rancher-backup
spec:
  resourceSetName: rancher-resource-set
  schedule: "10 3 * * *"
  retentionCount: 10
----

O operador do rancher-backup oferece várias opções de agendamento, criptografia e classes de armazenamento.
Você pode explorar todas as opções lendo https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.html[a documentação oficial do].

Verifique os registros do operador do rancher-backup.

[,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

Verifique se o arquivo de backup foi criado no Persistent Volume.

[,shell]
----
...
INFO[2022/10/17 07:45:04] Finding files starting with /var/lib/backups/rancher-backup-430169aa-edde-4a61-85e8-858f625a755b*.tar.gz
INFO[2022/10/17 07:45:04] File rancher-backup-430169aa-edde-4a61-85e8-858f625a755b-2022-10-17T05-15-00Z.tar.gz was created at 2022-10-17 0
...
----
