= Configurar endereĂ§os IP internos e externos do K3s e do RKE2
:revdate: 2025-09-08
:page-revdate: {revdate}

O K3s e o RKE2 permitem especificar os endereĂ§os IP internos e externos de um nĂł por meio dos parĂąmetros `--node-ip` e `--node-external-ip`.

O Rancher Provisioning permite preencher esses parĂąmetros coletando o endereĂ§o IP da interface de rede de cada nĂł.

De qualquer forma, os mĂ©todos para coletar essas opĂ§Ă”es de ip para _Custom_ Rancher Clusters e _Elemental_ Rancher Clusters sĂŁo diferentes.

== ConfiguraĂ§ĂŁo de endereĂ§os IP internos e externos do K3s e do RKE2 no provisionamento do Rancher Cluster

O provisionamento do Rancher permite especificar na seĂ§ĂŁo Rancher Agent as interfaces de rede que devem ser vinculadas aos endereĂ§os IP internos e externos de cada nĂł provisionado.

Isso Ă© feito adicionando os nomes das interfaces de rede das quais os endereĂ§os IP devem ser extraĂ­dos nas variĂĄveis de ambiente do agente `CATTLE_INTERNAL_ADDRESS` e `CATTLE_ADDRESS` (https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/rancher-agent-options#ip-address-options [consulte os documentos do Rancher]).

[NOTE]
====
As variĂĄveis de ambiente `CATTLE_INTERNAL_ADDRESS` e `CATTLE_ADDRESS` Agent podem ser preenchidas diretamente com os endereĂ§os IP desejados. De qualquer forma, como os endereĂ§os IP internos e externos sĂŁo _por nĂł_, isso sĂł funcionaria em clusters de nĂł Ășnico.
====


[CAUTION]
====
Embora durante a criaĂ§ĂŁo de um cluster elementar seja possĂ­vel adicionar variĂĄveis de ambiente do agente, as variĂĄveis `CATTLE_ADDRESS` e `CATTLE_INTERNAL_ADDRESS` sĂŁo ignoradas e nĂŁo resultariam na configuraĂ§ĂŁo dos endereĂ§os IP internos e externos dos nĂłs provisionados.
====


== Configurar endereĂ§os IP internos e externos do K3s e do RKE2 em clusters elementares

O Elemental permite configurar os endereĂ§os IP internos e externos dos nĂłs do cluster, anexando os rĂłtulos `elemental.cattle.io/InternalIP` e `elemental.cattle.io/ExternalIP` aos recursos xref:references/machineinventory-reference.adoc[do MachineInventory] que rastreiam os nĂłs de destino.

Esses rĂłtulos, quando anexados a um recurso xref:references/machineinventory-reference.adoc[MachineInventory], sĂŁo usados para preencher os endereĂ§os IP internos e externos dos nĂłs associados.

Os rĂłtulos podem ser adicionados aos campos xref:references/machineregistration-reference.adoc[MachineRegistration] `machineInventoryLabels`, usando as variĂĄveis de endereĂ§o IP xref:label-templates/label-templates-network.adoc[do Network Label Template] como valores, para permitir a coleta dos endereĂ§os IP de cada nĂł.

Exemplo: xref:references/machineregistration-reference.adoc[MachineRegistration], em que os nĂłs terĂŁo o endereĂ§o IP interno definido a partir da interface eth0 e o endereĂ§o IP externo a partir da eth1.

.registration.yaml
[,yaml]
----
include::example$labeltemplates/registration.yaml[]
----
