= Gerenciamento de componentes empacotados
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}

== Manifestos de implantação automática (AddOns)

Nos nós do servidor, qualquer arquivo encontrado em `+/var/lib/rancher/k3s/server/manifests+` será automaticamente implantado no Kubernetes de maneira semelhante a `+kubectl apply+`, tanto na inicialização quanto quando o arquivo for alterado no disco. A exclusão de arquivos desse diretório não excluirá os recursos correspondentes do cluster.

Os manifestos são rastreados como recursos personalizados do `+AddOn+` no namespace `+kube-system+`. Quaisquer erros ou avisos encontrados ao aplicar o arquivo de manifesto podem ser vistos usando `+kubectl describe+` no `+AddOn+` correspondente, ou usando `+kubectl get event -n kube-system+` para visualizar todos os eventos desse namespace, inclusive os do controlador de implantação.

=== Componentes embalados

O K3s vem com vários componentes empacotados que são implantados como AddOns por meio do diretório de manifestos: `+coredns+`, `+traefik+`, `+local-storage+`, e `+metrics-server+`. O controlador incorporado do `+servicelb+` LoadBalancer não tem um arquivo de manifesto, mas pode ser desativado como se fosse um `+AddOn+` por motivos históricos.

Os manifestos de componentes empacotados são gerenciados pelos K3s e não devem ser alterados. Os arquivos são regravados no disco sempre que o K3s é iniciado, a fim de garantir sua integridade.

=== Complementos do usuário

Você pode colocar arquivos adicionais no diretório de manifestos para implantação como um `+AddOn+`. Cada arquivo pode conter vários recursos do Kubernetes, delimitados pelo separador de documentos `+---+` YAML. Para obter mais informações sobre como organizar recursos em manifestos, consulte a seção https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/[Managing Resources] da documentação do Kubernetes.

==== Requisitos de nomenclatura de arquivos

O nome `+AddOn+` de cada arquivo no diretório do manifesto é derivado do nome base do arquivo.
Certifique-se de que todos os arquivos dentro do diretório de manifestos (ou dentro de quaisquer subdiretórios) tenham nomes exclusivos e sigam as do Kubernetes https://kubernetes.io/docs/concepts/overview/working-with-objects/names/[restrições de nomenclatura de objetos].
Deve-se tomar cuidado também para não entrar em conflito com os nomes em uso pelos componentes padrão do pacote K3s, mesmo que esses componentes estejam desativados.

Aqui está um exemplo de um erro que seria relatado se o nome do arquivo contivesse sublinhados:

____
`Falha ao processar a configuração: falha ao processar /var/lib/rancher/k3s/server/manifests/example_manifest.yaml:
   Addon.k3s.cattle.io "example_manifest" é inválido: metadata.name: Valor inválido: "exemplo_manifesto": um subdomínio RFC 1123 em minúsculas deve consistir em caracteres alfanuméricos em minúsculas, '-' ou '.', e deve começar e terminar com um caractere alfanumérico (por exemplo, 'example.com', o regex usado para validação é '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`
____

[WARNING]
====
Se você tiver vários nós de servidor e colocar manifestos adicionais do AddOn em mais de um servidor, é sua responsabilidade garantir que os arquivos permaneçam sincronizados entre esses nós. O K3s não sincroniza o conteúdo do AddOn entre os nós e não pode garantir o comportamento correto se servidores diferentes tentarem implantar manifestos conflitantes.
====


== Desativação de manifestos

Há duas maneiras de desativar a implementação de conteúdo específico do diretório de manifestos.

[#_using_the_disable_flag]
=== Usando o sinalizador `+--disable+` 

Os AddOns para os componentes empacotados listados acima, além dos AddOns para quaisquer manifestos adicionais colocados no diretório `+manifests+`, podem ser desativados com o sinalizador `+--disable+`. Os AddOns desativados são desinstalados ativamente do cluster e os arquivos de origem são excluídos do diretório `+manifests+`.

Por exemplo, para desativar a instalação do traefik em um novo cluster ou para desinstalá-lo e remover o manifesto de um cluster existente, você pode iniciar o K3s com `+--disable=traefik+`. Vários itens podem ser desativados separando seus nomes com vírgulas ou repetindo o sinalizador.

=== Uso de arquivos .skip

Para qualquer arquivo em `+/var/lib/rancher/k3s/server/manifests+`, você pode criar um arquivo `+.skip+` que fará com que o K3s ignore o manifesto correspondente. O conteúdo do arquivo `+.skip+` não importa, apenas sua existência é verificada. Observe que a criação de um arquivo `+.skip+` depois que um AddOn já tiver sido criado não o removerá nem modificará os recursos criados; o arquivo é simplesmente tratado como se não existisse.

Por exemplo, a criação de um arquivo `+traefik.yaml.skip+` vazio no diretório de manifestos antes de o K3s ser iniciado pela primeira vez fará com que o K3s ignore a implantação do `+traefik.yaml+`:

[,bash]
----
$ ls /var/lib/rancher/k3s/server/manifests
ccm.yaml      local-storage.yaml  rolebindings.yaml  traefik.yaml.skip
coredns.yaml  traefik.yaml

$ kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   local-path-provisioner-64ffb68fd-xx98j   1/1     Running   0          74s
kube-system   metrics-server-5489f84d5d-7zwkt          1/1     Running   0          74s
kube-system   coredns-85cb69466-vcq7j                  1/1     Running   0          74s
----

Se o Traefik já tiver sido implantado antes da criação do arquivo `+traefik.skip+`, o Traefik permanecerá como está e não será afetado por atualizações futuras quando o K3s for atualizado.

== Complementos do Helm

Para obter informações sobre o gerenciamento de gráficos do Helm por meio de manifestos de implantação automática, consulte a seção sobre o xref:add-ons/helm.adoc[Helm.]
