= Documentación de SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}

Esta es la documentación más reciente de SUSE Observability. Seleccione los temas en el menú de contenidos de la izquierda.

Para versiones anteriores de la documentación, utilice el https://archivedocs.stackstate.com[archivo].

== Empezar

Visite la xref:/k8s-suse-rancher-prime.adoc[guía de inicio de Rancher] Prime si es usuario de Rancher Prime, si es usuario de SUSE Cloud Observability visite laxref:/k8s-quick-start-guide.adoc[guía de inicio rápido], si está ejecutando SUSE Cloud Observability en AWS consulte laxref:/suse-cloud-observability-quick-start-guide.adoc[guía de inicio rápido de SUSE Cloud Observability].

== ¿No encuentra algo?

Utilice la barra de búsqueda de la parte superior derecha. Si cree que falta documentación, háganoslo saber en https://scc.suse.com/[sitio de soporte de SUSE Observability].

== Solución de problemas y asistencia

¿Alguna pregunta? Podemos ayudarle. Encuentre al equipo de asistencia en elhttps://scc.suse.com/[sitio de asistencia de] SUSE.

== SUSE Observability autoalojado

Utilice SUSE Observability Self-hosted para observar un amplio conjunto de tecnologías desde sus propios centros de datos o la nube.

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability autoalojado]

== SUSE Cloud Observability

Utilice SUSE Cloud Observability para observar tecnologías en la nube, como Kubernetes y servicios de AWS.

xref:/suse-cloud-observability/user-management.adoc[Documentación sobre SUSE Cloud Observability]
