= k8s カスタム秘密設定 (非推奨)
:revdate: 2025-10-27
:page-revdate: {revdate}

== 概要

SUSE Observabilityエージェントは、APIキーとクラスタ認証トークンを含むカスタムシークレットの名前の指定をサポートしています。この機能は、自分自身で秘密を管理し、Helmチャートによる秘密の自動作成を避けたいユーザーに便利です。

[CAUTION]
====
*秘密をカスタマイズするこの方法は非推奨であり、RBAC機能とは互換性がない。*

外部秘密の使用にはxref:/setup/agent/k8s-custom-secrets-setup.adoc[新しい方法を]使用してください。
====


== ヘルムチャート

=== 設定オプション

* `stackstate.manageOwnSecrets`:ユーザが自分の秘密を管理したいかどうかを決定するブーリアン・フラグ。デフォルト値は`false` 。
* `stackstate.customSecretName`:(オプション) ユーザーが作成するカスタム秘密の名前。`stackstate.manageOwnSecrets` が`true` に設定されている場合は必須。
* `stackstate.customApiKeySecretKey`:(オプション) カスタムシークレット内のAPIキーのキー名。`stackstate.manageOwnSecrets` が`true` に設定されている場合は必須。
* `stackstate.customClusterAuthTokenSecretKey`:(オプション）カスタム秘密内のクラスタ認証トークンのキー名。`stackstate.manageOwnSecrets` が`true` に設定されている場合は必須。

=== 行動説明

* *秘密の自動作成*：デフォルトでは、`stackstate.manageOwnSecrets` が`false` に設定されている場合、チャートは以前と同様にシークレットを自動的に作成し続ける。
* *カスタム・シークレット・マネジメント*`stackstate.manageOwnSecrets` が`true` に設定されている場合、チャートはユーザーがカスタムシークレットの名前(`stackstate.customSecretName`)とAPIキーと認証トークンのキー( それぞれ`stackstate.customApiKeySecretKey` と`stackstate.customClusterAuthTokenSecretKey`)を提供することを期待する。
* *暗黙の省略*：自分の秘密を管理したいと指定した場合、チャートは`stackstate.apiKey` と`stackstate.cluster.authToken` の値を無視する。
+
== values.yamlでの使用方法

. *自動秘密作成を使用する（デフォルト）*：
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *自らの秘密を管理する*
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
