= Secrets Cryptage Config
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

K3s permet d'activer le cryptage des secrets au repos. Lors du premier démarrage du serveur, l'option `--secrets-encryption` permet d'effectuer automatiquement les opérations suivantes :

* Générer une clé AES-CBC
* Générer un fichier de configuration du chiffrement avec la clé générée
* Transmettre la configuration à l'interface KubeAPI en tant que encryption-provider-config

[TIP]
====
Le cryptage des secrets ne peut pas être activé sur un serveur existant sans le redémarrer. +
Utilisez `curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server --secrets-encryption` si vous installez à partir d'un script, ou d'autres méthodes décrites dans les xref:installation/configuration.adoc#_configuration_with_install_script[options de configuration].
====

== Choix du fournisseur de cryptage

[IMPORTANT]
.Version Gate
====
Disponible à partir des versions d'avril 2025 : v1.30.12+k3s1, v1.31.8+k3s1, v1.32.4+k3s1, v1.33.0+k3s1.
====

En utilisant le drapeau `--secrets-encryption-provider`, vous pouvez choisir parmi les fournisseurs de cryptage suivants pris en charge par K3 :

* `aescbc`: AES-CBC avec remplissage PKCS#7. Il s'agit du fournisseur par défaut.
* `secretbox`: XSalsa20 et Poly1305

### Migration des fournisseurs

Vous pouvez migrer du fournisseur `aescbc` vers le fournisseur `secretbox` en suivant les étapes suivantes :

. Assurez-vous que le fournisseur `secretbox` est pris en charge par votre version de K3s.
. Mettez à jour/ajoutez le drapeau `secrets-encryption-provider` dans votre fichier de configuration K3s pour `secretbox`.
. Effectuez une rotation des clés de chiffrement, en suivant la section xref:cli/secrets-encrypt.adoc#_encryption_key_rotation[Rotation des clés de chiffrement] ci-dessous.

== Fichier de configuration du chiffrement généré

Lorsque vous démarrez le serveur avec `--secrets-encryption`, K3s génère un fichier de configuration de cryptage à `/var/lib/rancher/k3s/server/cred/encryption-config.json`.

Voici un exemple du fichier de configuration de chiffrement généré avec le fournisseur par défaut `aescbc`:

[,json]
----
{
  "kind": "EncryptionConfiguration",
  "apiVersion": "apiserver.config.k8s.io/v1",
  "resources": [
    {
      "resources": [
        "secrets"
      ],
      "providers": [
        {
          "aescbc": {
            "keys": [
              {
                "name": "aescbckey",
                "secret": "xxxxxxxxxxxxxxxxxxx"
              }
            ]
          }
        },
        {
          "identity": {}
        }
      ]
    }
  ]
}
----

== Outil de cryptage des secrets

K3s contient un outil `secrets-encrypt`, qui permet de contrôler automatiquement les éléments suivants :

* Désactivation/activation du cryptage des secrets
* Ajout de nouvelles clés de chiffrement
* Rotation et suppression des clés de chiffrement
* Recryptage des secrets

Pour plus d'informations, voir la xref:cli/secrets-encrypt.adoc[documentation de la commande`k3s secrets-encrypt` ].
