= Inventarverwaltung
:revdate: 2025-08-15
:page-revdate: {revdate}

Der Betreiber von {elemental-product-name} kann ein Inventar der Maschinen und die Zuordnung der Maschine zu ihrer Konfiguration und dem zugewiesenen Cluster führen.

== MachineInventory

Die Website `+MachineInventory+` enthält alle relevanten Informationen zu einer registrierten Maschine. +
Nach erfolgreicher Registrierung erbt die `+MachineInventory+` alle `+machineInventoryLabels+`, die in der zugehörigen `+MachineRegistration+` definiert sind. +
Außerdem wird die Maschine `+annotations+` bei jeder erfolgreichen Registrierung aktualisiert.

Standardmäßig versucht {elemental-product-name} alle 24 Stunden, die Registrierung zu aktualisieren, um Etiketten und Anmerkungen zu aktualisieren.

=== Referenz

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  # Machine annotations can be useful to identify hosts
  annotations:
    elemental.cattle.io/auth: tpm
    elemental.cattle.io/registration-ip: 192.168.122.152
  labels:
    # A label inherited from the MachineRegistration definition
    element: fire
    # Generic SMBIOS labels that are typically populated with
    # the MachineRegister approach
    machineUUID: f266c64b-3972-40e7-9937-3dc4a311436c
    manufacturer: QEMU
    productName: Standard-PC-Q35-ICH9-2009
    serialNumber: Not-Specified
    # Custom labels can be applied to each MachineInventory
    myCustomLabel: foo
  name: m-479ab68e-00ff-4081-a731-5b1a76610289
  # The namespace must match the namespace of the cluster
  # assigned to the clusters.provisioning.cattle.io resource
  namespace: fleet-default
  # A reference to the MachineInventorySelector that links the
  # machine to a Cluster definition
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: MachineInventorySelector
    name: fire-machine-selector-qcn7d
    uid: 0a1f751e-4ca9-4a0d-919a-97ba1f434d12
spec:
  # The hash of the TPM EK public key. This is used if you are
  # using TPM2 to identify nodes. Nodes can report their TPM
  # hash by using the MachineRegistration.
  tpmHash: d68795c6192af9922692f050b...
----

== MachineRegistration

`+MachineRegistration+` enthält Informationen über die Installation, das Zurücksetzen und die Konfiguration aller angeschlossenen {elemental-product-name} Geräte.

Es ist möglich, `+spec.machineInventoryLabels+` und `+spec.machineInventoryAnnotations+` zu aktualisieren, und dies wird dann auf alle registrierten Geräte angewendet.
Standardmäßig versucht {elemental-product-name} alle 24 Stunden, die Registrierung zu aktualisieren, um Etiketten und Anmerkungen zu aktualisieren.

Es ist zwar möglich, die Definition von `+spec.config+` zu ändern, aber Aktualisierungen von `+spec.config+` werden von Rechnern, die die Installation bereits abgeschlossen haben, ignoriert.
Rechner, die die Installation nicht abschließen konnten, versuchen es alle 30 Minuten erneut, indem sie die Remote-Definition `+MachineRegistration+` neu laden. Dies kann nützlich sein, um `+spec.config+` Fehler zu korrigieren, die eine erfolgreiche Installation verhindern (z. B. `+spec.config.elemental.install.device+`), ohne eine neue `+MachineRegistration+` und eine neue ISO erstellen zu müssen.

=== Referenz

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  # The namespace must match the namespace of the cluster
  # assigned to the clusters.provisioning.cattle.io resource
  namespace: fleet-default
spec:
  # The cloud config that will be used to provision the node
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
      reset:
        enabled: true
        debug: true
        reset-persistent: true
        reset-oem: true
        reboot: true
  # Labels to be added to the created MachineInventory object
  machineInventoryLabels:
    element: fire
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
  # Annotations to be added to the created MachineInventory object
  machineInventoryAnnotations: {}
----
