= ManagedOSVersionChannel-Referenz
:revdate: 2025-09-08
:page-revdate: {revdate}

Die Ressource `+ManagedOSVersionChannel+` ist für die Definition des OS Image Channels zuständig.

Es gibt mehrere Schlüssel, die unter einer `+ManagedOSVersionChannel+` resource spec konfiguriert werden können.

.managedosversionchannel-example.yaml
[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-channel
  namespace: fleet-default
spec:
  options:
    image: registry.suse.com/rancher/elemental-channel:1.4.2
  syncInterval: 1h
  type: custom
----

== `+ManagedOSVersionChannelSpec+` Referenz

|===
| Schlüssel | Typ | Standardwert | Beschreibung

| Optionen
| Objekt
| null
| Definiert die optionalen Informationen, die in einem OS-Kanal hinzugefügt werden können

| syncInterval
| String
| 1h
| Legt fest, wann der OS-Kanal synchronisiert werden soll

| Typ
| String
| leer
| Definiert den Kanaltyp, nur `+custom+` wird jetzt unterstützt

| upgradeContainer
| Objekt
| null
| Ein Upgrade-Container, der definiert werden kann. Siehe <<_upgradecontainer,Referenz>>

| deleteNoLongerInSyncVersions
| bool
| falsch
| Automatisches Löschen veralteter Betriebssystemversionen, die nicht mehr im Channel enthalten sind

| aktiviert
| bool
| true
| Aktiviert diesen Kanal. Ermöglichung der Synchronisierung von Betriebssystemversionen.
|===

== `+upgradeContainer+`

Dies ermöglicht das Überschreiben des Standardfeldes `+upgrade+` von System Upgrade Controller-Plänen (siehe xref:rancher-os-management/upgrade-lifecycle.adoc#_components[Upgrade-Komponenten]), die auf dieser ManagedOSVersion basieren.
Diese Schlüssel werden vom System Upgrade Controller in eine Kubernetes https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container[Container-Spezifikation] übersetzt.
Dies ist der Container, der für die Durchführung eines Betriebssystem-Upgrades verantwortlich ist.
