= 术语表
:revdate: 2025-11-14
:page-revdate: {revdate}

== 目录

[cols=14*]
|===
| xref:./glossary.adoc#_a[A]
| xref:./glossary.adoc#_b[B]
| xref:./glossary.adoc#_c[C]
| xref:./glossary.adoc#_f[F]
| xref:./glossary.adoc#_i[I]
| xref:./glossary.adoc#_k[K]
| xref:./glossary.adoc#_m[M]
| xref:./glossary.adoc#_n[N]
| xref:./glossary.adoc#_o[O]
| xref:./glossary.adoc#_p[P]
| xref:./glossary.adoc#_r[R]
| xref:./glossary.adoc#_s[S]
| xref:./glossary.adoc#_t[T]
| xref:./glossary.adoc#_w[W]
|===

== A

=== 附加组件

服务超出了部署符合 Kubernetes 标准的集群所需的基本组件，可分为两种类型：

* *核心附加组件*：部署符合 Kubernetes 标准的集群所需的附加组件：DNS、kube-proxy、CNI。
* *附加组件*：符合 Kubernetes 标准的集群不需要的附加组件（如 metrics/Heapster、Dashboard）。

=== 气隙环境

在无法直接访问互联网的情况下建立和运行 Kubernetes 集群。

== B

=== 引导

将服务器转化为 Kubernetes 节点的过程。这可能涉及在创建支持机器的服务器时需要提供的数据，以及服务器上运行的软件的运行时配置。

=== 引导式集群

用于配置目标管理群集的临时群集。

=== Bootstrap 提供商

指为<<_bootstrap,引导>>过程<<_provider,提供>>解决方案的<<_provider,提供>>程序。

== C

=== CAPI

核心集群应用程序接口

=== CAPA

集群 API 提供商 AWS

=== CAPD

集群 API 提供商 Docker

=== CAPG

群集 API 谷歌云计算提供商

=== CAPIO

集群 API 操作员

=== CAPRKE2

集群 API 提供商 RKE2。有关 CAPRKE2 的详细信息，请查看其文档https://caprke2.docs.rancher.com[点击此处] 。

=== CAPV

集群 API 提供商 vSphere

=== CAPZ

集群 API 提供商 Azure

=== CAPI 提供商

公共应用程序接口（API），可促进<<_cluster_api_operator,CAPI 操作员>>和<<_cluster_api,集群应用程序接口>>资源的配置和操作。

=== 儿童群组

通常与<<_workload_cluster,工作负载集群>>互换使用。

=== 群组

完整的 Kubernetes 部署。请参阅管理群集和工作负载群集。

=== ClusterClass

定义拓扑（控制平面和工作站）的模板集合，用于连续调节一个或多个集群。
参见xref:../user/clusterclass.adoc[集群类]

=== 集群应用程序接口

或*集群应用程序接口项目*

集群应用程序接口是 SIG-cluster-lifecycle 的一个子项目。它还用于指软件组件、应用程序接口和产生这些组件的社区。

参见<<_core_provider,核心供应商>>

=== 集群 API 操作员

或*集群 API 操作员项目*

集群应用程序接口操作员是 SIG-cluster-lifecycle 的一个子项目。它旨在授权群集管理员使用声明式方法处理管理群集内群集 API 提供程序的生命周期。

=== 集群应用程序接口提供程序 RKE2

<<_caprke2,集群 API 提供程序 RKE2>>是两种提供程序类型的组合：用于配置 Kubernetes 控制平面节点的集群 API 控制平面提供程序（Cluster API Control Plane Provider）和用于在使用<<_rke2,RKE2>>作为 Kubernetes 发行版的机器上启动 Kubernetes 的集群 API 引导提供程序（Cluster API Bootstrap Provider）。

=== 控制平面

构成集群基础的一组 Kubernetes 服务。另请参见https://kubernetes.io/docs/concepts/#_kubernetes-control-plane 有两种变体：

* *自备*：Kubernetes 控制平面，由完全由单个集群 API 部署管理的 pod 或机器组成。
* *外部*或*托管*：由集群 API 以外的系统（如 GKE、AKS、EKS、IKS）提供和控制的控制平面。

=== 控制平面提供商

指实施 Kubernetes<<_control_plane,控制平面>>管理解决方案的<<_provider,提供商>>。

参见<<_caprke2,CAPRRKE2>>、<<_kcp,KCP>>。

=== 核心供应商

指实现 Cluster API 核心控制器的<<_provider,提供>>程序；如果考虑到必须在管理集群中部署的第一个项目就是 Cluster API 本身，那么就应该明白为什么 Cluster API 项目也被称为核心提供程序了。

参见<<_cluster_api,CAPI>>。

== F

=== 舰队

ifeval::["{build-type}" == "product"]
容器管理和部署引擎，旨在通过 GitOps 为用户提供对本地集群的更多控制和持续监控。请查看https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/index.html/[Fleet 文档]，了解有关 Fleet 的更多信息。
endif::[]
ifeval::["{build-type}" == "community"]
容器管理和部署引擎，旨在通过 GitOps 为用户提供对本地集群的更多控制和持续监控。请查看https://fleet.rancher.io/[Fleet 文档]，了解有关 Fleet 的更多信息。
endif::[]

== I

=== 基础设施提供商

指实施群集或机器（如虚拟机、网络等）所需基础设施/计算资源调配的<<_provider,提供商>>。
云基础设施提供商包括 AWS、Azure 或 Google；而 VMware、MAAS 或 metal3.io 可定义为裸机提供商。

=== IPAM 提供商

指允许集群 API 与 IPAM 解决方案交互的<<_provider,提供商>>。
IPAM 提供商与群集 API 的交互基于`IPAddressClaim` 和`IPAddress` API 类型。

== K

=== 符合 Kubernetes 标准

或*与 Kubernetes 兼容*

通过 Kubernetes 一致性测试的集群。

=== Kubernetes 操作员

Kubernetes 操作员是一种打包、部署和管理 Kubernetes 应用程序的方法。更多信息，另请参见https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ 。

=== k/k

指https://github.com/kubernetes/kubernetes[主 Kubernetes git 仓库]或主 Kubernetes 项目。

=== KCP

Kubeadm 控制平面提供商

== M

=== 机器

或*机器资源*

Kubernetes 的自定义资源，表示托管 Kubernetes 节点的基础设施组件。

=== 管理群集

对群集执行创建、扩展、升级或销毁操作。

=== 托管的 Kubernetes

托管 Kubernetes 是指云提供商原生提供的任何 Kubernetes 集群供应和维护抽象，通常作为 API 公开。例如https://aws.amazon.com/eks/[EKS]、https://www.oracle.com/cloud/cloud-native/container-engine-kubernetes/[OKE]、https://azure.microsoft.com/en-us/products/kubernetes-service[] AKS、https://cloud.google.com/kubernetes-engine[] GKE、https://www.ibm.com/cloud/kubernetes-service[] IBM、https://www.digitalocean.com/products/kubernetes[Cloud Kubernetes Service]，以及整个 Kubernetes 云原生生态系统中的更多系统。

=== 管理拓扑

参见 "<<_topology,拓扑>>

=== 管理组群

运行一个或多个基础架构提供程序以及存储资源（如机器）的集群。通常在配置多个工作负载群集时使用。

== N

=== 节点池

节点池是群集中一组配置相同的节点。

== O

=== 操作系统

或*操作系统*

一般理解为内核与系统级用户界面的组合，如 Linux 或 Windows，而不是特定的发行版。

== P

=== 枢轴

Pivot 是将提供程序组件和声明的群集应用程序资源从源管理群集移动到目标管理群集的过程。

枢轴进程还可用于删除管理群集，也可在升级管理群集时使用。

=== 提供商

或*集群 API 提供商*

该术语最初是<<_infrastructure_provider,基础设施提供者>>的缩写，但目前用于指任何可部署并为集群 API 管理集群提供功能的项目。

请参见<<_bootstrap_provider,引导提供程序>>、<<_control_plane_provider,控制平面提供>>程序、<<_core_provider,核心提供>>程序、<<_infrastructure_provider,基础架构提供>>程序、<<_ipam_provider,IPAM 提供>>程序、<<_runtime_extension_provider,运行时扩展提供程序>>。

=== 提供商组件

指作为<<_provider,提供>>程序发布流程的一部分而发布的 YAML 工件；通常包括自定义资源定义 (CRD)、部署（用于运行控制器管理器）、RBAC 等。

在某些情况下，同一表达式用于指在管理群集中部署的上述组件实例。

参见<<_provider_repository,提供商存储库>>

=== 提供商存储库

指托管<<_provider_components,提供程序组件>>YAML 的位置；通常一个提供程序存储库托管多个版本的提供程序组件，每个发布的版本都有一个。

== R

=== 牧场主

https://www.rancher.com/[]是一个开源，旨在简化 Kubernetes 集群的部署和管理。

=== 牧场主集群代理

Rancher 在其管理的每个 Kubernetes 集群中部署的组件。它的主要作用是在 Rancher 服务器和 Kubernetes 集群之间建立安全通信通道，使 Rancher 能够管理集群并与之交互。

=== 牧场经理

Rancher 管理器（或 Rancher 服务器）是托管 Rancher UI 和 API 的地方，它通过<<_rancher_cluster_agent,Rancher 集群代理>>等组件与托管集群通信。它允许用户管理 Kubernetes 集群、应用程序和特定于 Rancher 的资源，如目录、用户、全局角色等。

=== RKE2

ifeval::["{build-type}" == "product"]
Rancher 的下一代完全兼容 Kubernetes 发行版，专注于美国境内的安全性和合规性。联邦政府部门。详情请参见https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html[文档]。
endif::[]
ifeval::["{build-type}" == "community"]
Rancher 的下一代完全兼容 Kubernetes 发行版，专注于美国境内的安全性和合规性。联邦政府部门。详情请参见https://docs.rke2.io/[文档]。
endif::[]

=== 运行时扩展

外部组件，是建立在集群 API 之上的系统的一部分，可处理特定运行时钩子的请求。

=== 运行时扩展提供商

指实现一个或多个<<_runtime_extension,运行时扩展的>> <<_provider,提供>>程序。

== S

=== 缩放

除非另有说明，否则指的是水平缩放。

=== 堆叠控制平面

控制平面节点，etcd 与 Kubernetes API 服务器同处一地，并作为静态 pod 运行。

=== 服务器

支持<<_machine,机器资源>>的基础设施，通常是云实例、虚拟机或物理主机。

=== {product_name}

<<_kubernetes_operator,Kubernetes 操作员>>，提供 Rancher 管理器和集群 API (CAPI) 之间的集成，目的是为 Rancher 提供全面的 CAPI 支持。

== T

=== 拓扑结构

群集对象规格中的一个字段，用于从单一控制点定义和管理群集控制平面和工作机的形状。群集的拓扑结构基于<<_clusterclass,ClusterClass>>。
有时也称为托管拓扑。

参见<<_clusterclass,集群类>>

ifeval::["{build-type}" == "product"]
=== 海龟

指 <<_suse_rancher_prime_cluster_api,{product_name}>>
endif::[]

ifeval::["{build-type}" == "community"]
=== 海龟

指 <<_rancher_turtles,{product_name}>>
endif::[]

== W

=== 工作量集群

由 ClusterAPI 控制器创建的集群，它_不是_引导集群，旨在供最终用户使用，而不是供 CAPI 工具使用。

=== WorkerClass

定义集群中一组工作节点的模板集合。一个 ClusterClass 包含零个或多个 WorkerClass 定义。

参见<<_clusterclass,集群类>>
