= Importar imagens
:page-languages: [en, ja, ko, zh]
:revdate: 2026-01-05
:page-revdate: {revdate}
:page-aliases: importar-imagens.adoc

As imagens de contêineres são armazenadas em cache localmente em cada nó pelo armazenamento de imagens containerd. As imagens podem ser extraídas do registro conforme necessário pelos pods, pré-carregadas por meio de image pull ou importadas de um tarball de imagens.

== Extração de imagens sob demanda

O Kubernetes, por padrão, extrai automaticamente as imagens quando um Pod as requer, se a imagem ainda não estiver presente no nó. Esse comportamento pode ser alterado usando o campo https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy[image pull policy] do Pod. Ao usar a política padrão `+IfNotPresent+`, o containerd extrairá a imagem do upstream (padrão) ou do seu xref:installation/private-registry.adoc[registro privado] e a armazenará em seu armazenamento de imagens. Os usuários não precisam aplicar nenhuma configuração adicional para que a extração de imagens sob demanda funcione.


== Imagens pré-importadas

[IMPORTANT]
.Versão Gate
====
O recurso de pré-importação de imagens enquanto o K3s está em execução está disponível a partir das versões de janeiro de 2025: v1.32.0+k3s1, v1.31.5+k3s1, v1.30.9+k3s1, v1.29.13+k3s1. Antes disso, o K3s pré-importava as imagens somente durante a inicialização.
====

A pré-importação de imagens para o nó é essencial se você configurar o `+imagePullPolicy+` do Kubernetes como `+Never+`. Você pode fazer isso por motivos de segurança ou para reduzir o tempo necessário para que os nós do K3s sejam ativados.

O K3s inclui dois mecanismos para pré-importar imagens para o armazenamento de imagens do containerd:

[tabs,sync-group-id=import-images]
======
Importação de imagens on-line::
+
--

Os usuários podem acionar um pull de imagens no armazenamento de imagens do containerd colocando um arquivo de texto contendo os nomes das imagens, um por linha, no diretório `+/var/lib/rancher/k3s/agent/images+`. O arquivo de texto pode ser colocado antes de o K3s ser iniciado, bem como criado ou modificado enquanto o K3s estiver em execução. O K3s extrai sequencialmente as imagens por meio da API CRI, opcionalmente usando a configuração xref:installation/private-registry.adoc[registries.yaml].

Por exemplo:

[,bash]
----
mkdir /var/lib/rancher/k3s/agent/images
cp example.txt /var/lib/rancher/k3s/agent/images
----

Onde `+example.txt+` contém:

----
docker.io/library/redis:latest
docker.io/library/mysql:latest
----

Após alguns segundos, as imagens `+redis+` e `+mysql+` estarão disponíveis no armazenamento de imagens do containerd do nó. 

Use `+sudo k3s ctr images list+` para consultar o armazenamento de imagens do containerd.
--

Importação de imagens off-line::
+
--
Os usuários podem importar imagens diretamente para o armazenamento de imagens do containerd colocando tarballs de imagens no diretório `+/var/lib/rancher/k3s/agent/images+`. O tarball pode ser colocado antes de o K3s ser iniciado, bem como criado ou modificado enquanto o K3s estiver em execução. O K3s descompacta o tarball da imagem, se necessário, extrai as imagens e as carrega no armazenamento de imagens do containerd.

Por exemplo:

[,bash]
----
mkdir /var/lib/rancher/k3s/agent/images
curl  https://github.com/k3s-io/k3s/releases/download/v1.33.1%2Bk3s1/k3s-airgap-images-amd64.tar.zst -O  /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.zst
----

Após alguns segundos, as imagens incluídas no tarball de imagens estarão disponíveis no armazenamento de imagens do containerd do nó. 

Use `+sudo k3s ctr images list+` para consultar o armazenamento de imagens do containerd.

Esse é o método usado em ambientes com porta de ar. Siga a xref:installation/airgap.adoc[documentação de instalação do air-gap] para obter informações detalhadas.
--
======

== Configure um registro de imagem

O K3s oferece suporte a duas alternativas para registros de imagens:

* O xref:installation/private-registry.adoc[Private Registry Configuration] abrange o uso do site `+registries.yaml+` para configurar a autenticação e o espelhamento do registro de imagens de contêineres.
* xref:installation/registry-mirror.adoc[O Embedded Registry Mirror] mostra como ativar o espelho de registro de imagem distribuído incorporado, para compartilhamento ponto a ponto de imagens entre nós.
