include::partial$variables.adoc[]
= Configuración de políticas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure políticas seleccionando Namespaces específicos o estableciendo mensajes de rechazo personalizados, y anule los resultados utilizando AdmissionPolicyGroup.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "policies"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "policies", "ClusterAdmissionPolicies", "AdmissionPolicies", "configuration", "namespaces"]
:sidebar_label: Configuración de políticas
:sidebar_position: 90
:current-version: {page-origin-branch}

== Omisión de espacios de nombres para una política específica

Por defecto, las políticas se aplican a todos los espacios de nombres para los que está configurado `+PolicyServer+`.
Si desea que una política se dirija únicamente a espacios de nombres específicos, puede desplegar varios `+AdmissionPolicies+` en cada espacio de nombres.

Otra opción es configurar `+ClusterAdmissionPolicies+` estableciendo su`+spec.namespaceSelector+` (consulte xref:reference/CRDs.adoc#clusteradmissionpolicy[los documentos CRD]). En`+spec.namespaceSelector+` se decide si se ejecuta la política en un objeto, en función de si el espacio de nombres de ese objeto coincide con el selector.

Por ejemplo, ésta es una política que sólo afecta a los espacios de nombres `+kube-system+` y `+my-namespace+`:

[subs="+attributes",yaml]
----
---
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-privileged-namespaces
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v1.0.3
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["namespaces"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: In
        values: [kube-system, my-namespace]
  settings:
    modes:
      enforce: "privileged"
----

A continuación se muestra una política dirigida a todos los espacios de nombres, además de `+kube-system+` y `+my-namespace+`:

[subs="+attributes",yaml]
----
---
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psa-enforcer-default-mode
spec:
  module: registry://ghcr.io/kubewarden/policies/psa-label-enforcer:v1.0.3
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["namespaces"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: NotIn
        values: [kube-system, my-namespace]
  settings:
    modes:
      enforce: "restricted"
----

== Mensaje de rechazo personalizado

Cuando una política rechaza un recurso, el mensaje que se muestra al usuario es el escrito por el autor de la política. A veces, los operadores de clúster pueden querer establecer un mensaje de rechazo personalizado. Por ejemplo, se puede utilizar para apuntar a un wiki interno o para proporcionar un código de error más específico.

Para ello puede utilizarse el campo `+message+` de los tipos `+ClusterAdmissionPolicy+` y `+AdmissionPolicy+`.

[NOTE]
====
`+ClusterAdmissionPolicyGroup+` y `+AdmissionPolicyGroup+` ya disponen de un campo`+message+` que se comporta de la misma manera.
====

El campo `+message+` permite a los operadores de clúster definir un mensaje de rechazo personalizado que anule el devuelto por la política. Cuando se utiliza esta configuración, el mensaje de rechazo original se puede encontrar en el campo `+causes+` de la respuesta.

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: pod-privileged-with-message
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:1.0.2
  policyServer: default
  mode: protect
  message: "Nops! You cannot do that"
  settings: {}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - "*"
      operations:
        - CREATE
  mutating: false
----

Puede obtener los detalles completos de una solicitud de admisión rechazada aumentando el nivel de verbosidad de kubectl:

[subs="verbatim,attributes"]
----
$ kubectl -v4 run pod-privileged2 --image=registry.k8s.io/pause --privileged
I0612 16:32:43.647601   48424 cert_rotation.go:137] Starting client certificate rotation controller
I0612 16:32:43.662550   48424 helpers.go:246] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "admission webhook \"clusterwide-pod-privileged-with-message.kubewarden.admission\" denied the request: Nops! You cannot do that",
  "details": {
    "causes": [
      {
        "message": "Privileged container is not allowed"
      }
    ]
  },
  "code": 400
}]
----

== Negar un resultado de política envolviéndolo en un PolicyGroup

A veces, al utilizar una política, ésta aún no implementa la lógica inversa de lo que necesitas.

Por ejemplo, desea utilizar el enlace:https://artifacthub.io/packages/kubewarden/priority-class-policy/priority-class-policy[`+priority-class+`policy] para rechazar un conjunto de clases prioritarias. Pero en el momento de escribir esto, la política de`+priority-class+` sólo admite allowlists, no denylist.

Un patrón común es envolver la política en `+AdmissionPolicyGroup+` o `+ClusterAdmissionPolicyGroup+`, y negar el resultado de la política en `+spec.expression+`.

Por ejemplo, supongamos que queremos que los usuarios utilicen todas las clases de prioridad definidas dentro del clúster excepto una de las siguientes: `+low-priority+`,`+med-priority+` y `+high-priority+`.

Actualmente, la configuración de la política sólo permite expresar la lista de clases de prioridad permitidas. La siguiente política de grupo supera esta limitación.

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: AdmissionPolicyGroup
metadata:
  name: priority-class-denylist
  namespace: your-namespace # or use a CLusterAdmissionPolicyGroup and set spec.namespaceSelector
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["replicationcontrollers"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["batch"]
      apiVersions: ["v1"]
      resources: ["jobs", "cronjobs"]
      operations: ["CREATE", "UPDATE"]
  policies:
    is_a_denied_priority_class:
      module: ghcr.io/kubewarden/policies/priority-class-policy:v1.0.4
      settings:
        allowed_priority_classes:
          - low-priority
          - med-priority
          - high-priority
  expression: "!is_a_denied_priority_class()" # negated result
  message: "the Pod is using a priorityClass that is not allowed"
----