= Personalice la instalación de {elemental-product-name} 
:revdate: 2025-09-08
:page-revdate: {revdate}

{elemental-product-name} (Elemental) instaladas se pueden personalizar de diferentes maneras.

Una opción es remasterizar las imágenes del sistema operativo del contenedor utilizando simplemente una compilación Docker. Las imágenes de SL Micro son imágenes de contenedor normales, por lo que es absolutamente posible crear una nueva imagen utilizando un Dockerfile basado en SLE Micro. Consulte la sección xref:operator-operational-tasks/custom-images.adoc[Crear imágenes de SO personalizadas] para obtener más detalles, esta es la opción preferida.

Alternativamente, también es posible proporcionar recursos adicionales y configuración dentro de los medios de instalación para que durante la instalación, o eventualmente en el momento del arranque, se puedan incluir binarios adicionales como controladores o archivos de configuración extra.

Esta sección se centra en cómo personalizar el proceso de instalación a partir de una imagen de SO determinada.

== Opciones de personalización

La instalación Elemental puede personalizarse de tres formas distintas no exclusivas. En primer lugar, mediante la inclusión de archivos adicionales cloud-config en el sistema instalado, en segundo lugar, mediante la inclusión de archivos adicionales cloud-config en los medios de instalación y, por último, mediante la adición de un archivo personalizado de configuración de cliente Elemental (`+/etc/elemental/config.yaml+`).

. Los archivos adicionales cloud-config incluidos en el sistema instalado son útiles para ejecutar operaciones personalizadas en el momento del arranque. Consulte la xref:references/cloud-config-reference.adoc[Referencia de configuración de la nube].

. Los archivos cloud-config adicionales en los medios de instalación son útiles para ejecutar operaciones personalizadas en el momento de la instalación o para personalizar el entorno de instalación para que se ajuste a ciertas necesidades específicas.

. Un archivo de configuración personalizado del cliente Elemental se encuentra, por defecto, en `+/etc/elemental/config.yaml+` y también se puede dividir en varios archivos yaml en el directorio `+/etc/elemental/config.d+`. Consulte la https://rancher.github.io/elemental-toolkit/docs/customizing/general_configuration/[referencia del archivo de configuración].

Un patrón común es combinar las tres formas descritas anteriormente en función de las necesidades específicas.

=== Añadir archivos cloud-config adicionales en el sistema operativo instalado

Para incluir archivos cloud-config adicionales durante la instalación es necesario añadirlos a los datos de instalación en el recurso MachineRegistration. La forma más sencilla de conseguirlo es añadiendo la configuración de nube deseada directamente como parte de la xref:references/machineregistration-reference.adoc#_config_cloud_config[sección dedicada] MachineRegistration. Véase el siguiente ejemplo


[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  ...
  config:
    ...
    cloud-config:
      stages:
        boot:
        - name: "Adding 'admin' user"
          users:
            admin:
              passwd: mysecretpasswd
----

Como alternativa, también se puede hacer referencia explícita a la ruta de los archivos cloud-config, de modo que no sea estrictamente necesario que la configuración esté dentro del propio recurso MachineRegistration. La sección `+config-urls+` del MachineRegistration se utiliza exactamente para este propósito. Véase la página de xref:references/machineregistration-reference.adoc[referencia MachineRegistration].

`+config-urls+` es una lista de literales de cadena donde cada elemento es una URL HTTP o una ruta local que apunta a un archivo cloud-config. La ruta local se evalúa durante la instalación, por lo que debe existir en el medio de instalación, normalmente una imagen ISO.

Por defecto, los sistemas Elemental live montan la raíz ISO en `+/run/initramfs/live+` que es también la ruta por defecto establecida para `+config-url+` en `+MachineRegistrations+`. Véase el ejemplo siguiente:

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  ...
  config:
    ...
    elemental:
      ...
      install:
        ...
        config-urls:
        - "/run/initramfs/live/oem/custom_config.yaml"
----

Elemental live ISOs, cuando arranca, tiene la raíz ISO montado en `+/run/initramfs/live+`. Según esto, se espera que la ISO del ejemplo anterior incluya el archivo `+/oem/custom_config.yaml+`.

[NOTE]
====
`+/run/initramfs/live+` es un punto de montaje de sólo lectura y no es una ruta apropiada para contenido generado dinámicamente en el arranque ISO.
====

=== Añadir archivos cloud-config adicionales en los medios de instalación

Para configurar el entorno de instalación (por ejemplo, establecer la conectividad de red para el registro) o proporcionar algunos xref:references/cloud-config-reference.adoc#_elemental_client_cloud_config_hooks[ganchos de instalación] para ejecutar lógica personalizada durante la propia instalación, puede ser necesario añadir archivos cloud-config adicionales en los medios de instalación.

En Elemental los recursos xref:references/seedimage-reference.adoc[SeedImage] son los responsables de manejar los medios de instalación. Así pues, el lugar más sencillo para incluir datos adicionales de configuración de la nube es dentro del soporte de instalación, añadiéndolos a la xref:references/seedimage-reference.adoc#_seedimagespec_reference[sección`+cloud-config+` ]. De este modo, la configuración de la nube se evaluará desde el primer arranque del medio de instalación y también se respetará durante la fase de instalación en caso de que se proporcione algún gancho de instalación. Considere el siguiente ejemplo:

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: custom-seed
  namespace: fleet-default
spec:
  ...
  cloud-config:
    stages:
      post-install:
      - name: "Run custom script after installation"
        commands:
        - |
          echo "This is a custom script"
          echo "For instance, this could be used to handle extra drives for an LVM group"
      boot:
      - name: "Add proxy setup for the installation media"
        files:
        - path: /etc/sysconfig/proxy
          permissions: 0664
          content: |
            PROXY_ENABLED="yes"
            HTTP_PROXY=http://<MY_PROXY>:<MY_PORT>
            HTTPS_PROXY=https://<MY_PROXY>:<MY_PORT>
            NO_PROXY="localhost, 127.0.0.1"
----

=== Archivo de configuración del cliente {elemental-product-name} personalizado

https://github.com/rancher/elemental-toolkit/blob/main/docs/elemental.md[cliente elemental]Los comandos de  `+install+`, `+upgrade+` y `+reset+` pueden configurarse con un https://rancher.github.io/elemental-toolkit/docs/customizing/general_configuration/[archivo de configuración personalizado] ubicado por defecto en `+/etc/elemental/config.yaml+`. Si tiene varios archivos yaml, debe añadirlos en el directorio `+/etc/elemental/config.d+`.

El siguiente ejemplo establece una partición adicional extra durante la instalación:

[,yaml]
----
install:
  extra-partitions:
  - size: 10240
    fs: ext4
    label: EXTRA_PARTITION
----

Para que esté disponible en el momento de la instalación, puede añadir el archivo adicional como parte de la configuración en la nube del recurso SeedImage, tal y como se describe en la sección anterior de esta página. Veamos un ejemplo:

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: custom-seed
  namespace: fleet-default
spec:
  ...
  cloud-config:
    stages:
      boot:
      - name: "Add Elemental client configuration file"
        files:
        - path: /etc/elemental/config.d/extra-partition.yaml
          permissions: 0664
          content: |
            install:
              extra-partitions:
              - size: 10240
                fs: ext4
                label: EXTRA_PARTITION
----