include::partial$variables.adoc[]
= Problema de rotación de certificados del servidor de políticas para la versión ≤ v1.16.0
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Resolución de problemas de rotación de certificados de servidores de políticas en {project-name}, a partir de la versión 1.16.
:doc-persona: ["kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["howto", "workarounds", "policy server certificates"]
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "policy server certificates"]
:sidebar_label: Rotación de certificados
:sidebar_position: 10
:current-version: {page-origin-branch}

[IMPORTANT]
.Solución para {project-name} v1.16.0 y anteriores
====

Esta solución sólo es necesaria para {short-project-name} v1.16.0 y versiones anteriores.
A partir de la versión 1.17.0, el controlador renueva automáticamente los certificados del servidor de políticas.

====

Durante el proceso de publicación de la versión 1.14, {short-project-name} descubrió un error relacionado con la rotación de certificados del servidor de políticas. La configuración de la CA raíz tiene una caducidad de 10 años, pero cada secreto de certificado de servidor de políticas tiene una caducidad de un año. Sin embargo, actualmente el controlador no puede renovarlos automáticamente.

En la versión v1.14, {short-project-name} se ha asegurado de que los secretos del servidor de políticas se creen con una caducidad de 10 años.

Existe un proceso de renovación automatizado para la versión ≥ v1.16.0.

Hasta entonces, los usuarios pueden eliminar manualmente el secreto del certificado caducado (policy-server-default) y activar una reconciliación del controlador. Esto se hace añadiendo, eliminando o actualizando una política o ajustando el número de réplicas de un PolicyServer.
