include::partial$variables.adoc[]
= {project-name} arquitectura
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Descubra cómo {project-name} utiliza las funciones principales de Kubernetes para integrarse perfectamente en su clúster.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["architecture"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "architecture"]
:sidebar_label: Arquitectura
:sidebar_position: 61
:current-version: {page-origin-branch}

{project-name} es un motor de políticas de Kubernetes.
Utiliza políticas escritas en un lenguaje de programación de su elección.
Este lenguaje debe generar un binario WebAssembly para que {project-name} lo utilice.

== ¿Qué _es_ una política?

Una política es un artefacto de (OCI) https://opencontainers.org/[la Iniciativa de Contenedores Abiertos]. Contiene un módulo WebAssembly, el código de la política y los metadatos que necesita PolicyServer para realizar las validaciones y mutaciones de las solicitudes de admisión.

[NOTE]
====

Al igual que https://kubernetes.io/docs/contribute/style/style-guide/[] Kubernetes,{project-name} utiliza los términos "PolicyServer" cuando se habla del servidor de políticas {project-name}y `+policy-server+` cuando se habla de Pod o despliegue de un{project-name} PolicyServer.

====


== Principios de diseño

=== Utilización de las funciones básicas de Kubernetes

El equipo diseñó {project-name} para utilizar funciones básicas de Kubernetes, sin reinventar la rueda.
El proyecto utiliza una combinación de:

* Kubernetes Controllers
* Definiciones personalizadas de recursos (CRD)
* Webhooks (validación y mutación)
* el sistema de notificación de eventos del Plano de Control

=== Utiliza eficazmente la arquitectura Kubernetes

{project-name} funciona a la perfección dentro del ecosistema Kubernetes. En esencia, el controlador {project-name} es un controlador de Kubernetes, que supervisa{project-name} Custom Resource Definitions (CRDs) y configura los recursos de Kubernetes para ejecutarlos. Esta integración garantiza que {project-name} utilice los mecanismos incorporados de Kubernetes, como controladores y CRD, para vigilar, gestionar y aplicar políticas de seguridad de forma eficiente.

=== Definición extensible de políticas

{project-name} emplea CRD para definir y gestionar los recursos de {project-name}, que especifican las reglas para las validaciones de las solicitudes de admisión. Este diseño permite a los usuarios ampliar las capacidades de Kubernetes con controles de admisión personalizados, garantizando que la aplicación de las políticas de seguridad y cumplimiento sea coherente en todo el clúster.

=== Control de admisión directo

Cuando es configurado por el controlador {project-name}, el Servicio de servidor de políticas recibe solicitudes de admisión directamente del plano de control de Kubernetes, utilizando`+ValidationWebhooks+` y `+MutatingWebhooks+`. Esta interacción directa agiliza el proceso de control de admisión, reduciendo la latencia y aumentando la eficacia en la aplicación de las políticas.

WebAssembly ofrece un entorno de ejecución aislado, lo que garantiza que las políticas se ejecuten de forma aislada, mejorando así la seguridad y la estabilidad del mecanismo de aplicación de políticas. Este aislamiento impide que las políticas interfieran entre sí o con el sistema anfitrión, mitigando el riesgo de ejecución de código malicioso.
WebAssembly es portátil y eficiente, lo que permite que las políticas se ejecuten en distintos entornos sin modificaciones. Esta compatibilidad entre plataformas garantiza que las políticas de {project-name} sean versátiles, de modo que pueda distribuirlas y ejecutarlas en diversos clústeres de Kubernetes.

=== Artefactos normativos basados en OCI

Las políticas en {project-name} son artefactos OCI (Open Container Initiative). Esta estandarización facilita la distribución y el versionado de las políticas. Las políticas contienen tanto los módulos WebAssembly para la lógica de aplicación como los metadatos necesarios para el funcionamiento del PolicyServer. El uso de artefactos OCI fomenta la interoperabilidad y la facilidad de gestión dentro de los ecosistemas de nube.

=== Aplicación de políticas precisas

{project-name} asocia políticas con su propio webhook de "validación" o "mutación", lo que permite una aplicación detallada de los controles de admisión. Esta flexibilidad permite a los administradores adaptar la aplicación de políticas en función de las necesidades específicas, lo que mejora la seguridad y el cumplimiento del clúster Kubernetes.

== La pila {project-name} 

{project-name} consta de estos componentes:

* {project-name} Los recursos personalizados sonhttps://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Kubernetes Custom Resources] que simplifican el proceso de gestión de políticas.
+
{project-name} se integra con Kubernetes utilizandohttps://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/[Dynamic Admission Control]. En concreto, {project-name} funciona como un Webhook de Admisión de Kubernetes. El `+policy-server+` es el punto final Webhook llamado por el servidor API Kubernetes para validar las solicitudes.

* El https://github.com/kubewarden/kubewarden-controller[{project-name}controller] es un controlador Kubernetes que reconcilia {project-name}'s Custom Resources. Este controlador crea partes de la pila {project-name}.
También traduce la configuración de {project-name} en directivas de Kubernetes.
+
`+kubewarden-controller+` registra los objetos`+MutatingWebhookConfiguration+` o `+ValidatingWebhookConfiguration+` necesarios en el servidor API de Kubernetes.

* xref:../tutorials/writing-policies/index.adoc[{project-name} Las políticas] son módulos WebAssembly que contienen la lógica de validación o mutación. Los módulos de WebAssembly tienen documentación detallada en las secciones dexref:../tutorials/writing-policies/index.adoc[políticas de escritura].

* El https://github.com/kubewarden/policy-server[PolicyServer] recibe solicitudes de validación. Valida las solicitudes ejecutando las políticas de{project-name}.

* El https://github.com/kubewarden/audit-scanner[escáner de auditoría] inspecciona los recursos que ya se encuentran en el clúster. Identifica a quienes infringen las políticas de{project-name}.
+
xref:/explanations/audit-scanner/audit-scanner.adoc[El escáner de auditoría] comprueba constantemente los recursos declarados en el clúster, marcando los que ya no se adhieren a las políticas desplegadas {project-name}.
+
.Arquitectura
[mermaid]
....
%%{
  init: {
    "flowchart": {
      "htmlLabels": false,
    }}}%% graph LR accTitle: Arquitectura del controlador de admisión accDescr: Diagrama que muestra la arquitectura de los componentes de Admission Controller.
    subgraph " " direction LR subgraph " " direction LR k8s(("Kubernetes")) registry[("OCI registry")] end subgraph kw[&quot;`+**Admission Controller**+`&quot;] controller(&quot;`+**Controller**+`&quot;) subgraph policy-server[&quot;`+**policy-server**+`&quot;] direction LR kw-policy-1{{"Policy 1"}} kw-policy-2{{"Policy 2"}} kw-policy-3{{"Policy 3"}} end webhooks(["ValidationWebhooks and\nMutatingWebhooks"]) audit-scanner["escáner de auditoría KW"] end end policy-server -->|"descargas\npolíticas de"| -->|"vigila eventos"| controlador k8s -->|"crea"| controlador webhooks -->|"crea instancias de servidor de políticas"| servidor de políticas k8s -. "-> webhooks webhooks -. "sent admission\nnrequests from K8s" .-> policy-server audit-scanner -->|"sends audit\nadmission requests"| policy-server
....

== El viaje de una política {project-name} 

=== Servidor de políticas predeterminado

En un cluster nuevo, los componentes {project-name} definidos son:

* Definiciones personalizadas de recursos (CRD)
* El despliegue `+kubewarden-controller+` 
* Un recurso personalizado de PolicyServer denominado `+default+`.

Cuando `+kubewarden-controller+` detecta el recurso PolicyServer por defecto, crea un despliegue `+policy-server+` del componente PolicyServer.

{project-name} funciona como un Webhook de Admisión de Kubernetes. Kubernetes especifica el uso de https://en.wikipedia.org/wiki/Transport_Layer_Security[Transport Layer Security] (TLS) para asegurar todos los puntos finales de Webhook. `+kubewarden-controller+`establece esta comunicación segura:

. Generación de una autoridad de certificación autofirmada
. Utilice esta CA para generar una clave de certificado TLS para el servicio `+policy-server+`.

Todos estos objetos se almacenan como recursos `+Secret+` en Kubernetes.

Por último, `+kubewarden-controller+` crea el despliegue `+policy-server+` y un servicio Kubernetes ClusterIP para exponerlo dentro de la red del clúster.

=== Definir la primera política

[NOTE]
====

Una política debe definir en qué `+policy-server+` debe ejecutarse. *Se vincula* a una instancia de`+policy-server+`. Puede tener diferentes políticas con el mismo módulo Wasm y la misma configuración ejecutándose en muchos PolicyServers. Sin embargo, no se puede tener una única definición de política que se ejecute en muchos PolicyServers.

====

El `+kubewarden-controller+` se da cuenta del nuevo recurso `+ClusterAdmissionPolicy+` y así encuentra el `+policy-server+` vinculado y lo reconcilia.

=== Conciliación de un `+policy-server+`

Al crear, modificar o suprimir un `+ClusterAdmissionPolicy+` o`+AdmissionPolicy+`, se activa un bucle de reconciliación en `+kubewarden-controller+`, para el `+policy-server+` propietario de la política. Este bucle de reconciliación crea una`+ConfigMap+` con todas las políticas vinculadas a la `+policy-server+`. A continuación, se inicia el despliegue de `+policy-server+`. De este modo, se inicia la nueva instancia de `+policy-server+` con la configuración actualizada.

En el momento del arranque, `+policy-server+` lee su configuración del ConfigMap y descarga todas las políticas {project-name} especificadas. Puede descargar las políticas de{project-name} desde servidores HTTP remotos y registros de contenedores.

Los parámetros de configuración de las políticas se utilizan para ajustar su comportamiento. Tras el arranque y la descarga de la política, `+policy-server+` comprueba si la configuración de la política proporcionada por el usuario es válida.

`+policy-server+` valida la configuración de las políticas invocando la función`+validate_setting+` expuesta por cada política. Hay más documentación en la sección de xref:../reference/spec/01-intro-spec.adoc[referencia de especificaciones] de la documentación.

Si alguna política recibe parámetros de configuración erróneos de la especificación de la política del usuario, cualquier solicitud de admisión evaluada por esa política devolverá un error.

Cuando {project-name} ha configurado todas las políticas, `+policy-server+` genera un grupo de subprocesos de trabajo para evaluar las solicitudes entrantes utilizando las políticas de {project-name}especificadas por el usuario.

Por último, `+policy-server+` inicia un servidor HTTPS, a la escucha de las solicitudes de validación entrantes. {project-name} utiliza la clave TLS y el certificado creados por el controlador {project-name} para proteger el servidor web.

El servidor web expone cada política mediante una ruta dedicada que sigue la convención de nomenclatura: `+/validate/<policy ID>+`.

=== Hacer que Kubernetes conozca la política

Todas las instancias de `+policy-server+` tienen unhttps://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/`[Readiness Probe+`], que +`kubewarden-controller`+ utiliza para comprobar cuando el `+despliegue`del servidor de políticas está listo para evaluar unhttps://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#webhook-request-and-response[`+AdmissionReview+`].

Una vez que {project-name} marca el despliegue `+policy-server+` como "únicamente accesible" o `+Ready+`, `+kubewarden-controller+` hace que el servidor API de Kubernetes conozca la nueva política. Para ello, cree un objeto`+MutatingWebhookConfiguration+` o `+ValidatingWebhookConfiguration+`. En este contexto, "únicamente accesible" significa que todas las instancias PolicyServer del clúster tienen instalada la última configuración de políticas. La distinción, es un punto fino, pero es necesario, debido a cómo funciona el despliegue de PolicyServers.
Es posible tener la misma política, en diferentes PolicyServers con diferentes configuraciones.

Cada política tiene un `+MutatingWebhookConfiguration+` dedicado o`+ValidatingWebhookConfiguration+` que apunta al punto final Webhook servido por`+policy-server+`. El punto final es accesible en la URL `+/validate/<policy ID>+`.

=== La política en acción

Ahora que toda la fontanería necesaria está completa, Kubernetes comienza a enviar solicitudes de Revisión de Admisión a los puntos finales correctos de `+policy-server+`.

Un `+policy-server+` recibe el objeto Solicitud de Admisión y, basándose en el endpoint que recibió la solicitud, utiliza la política correcta para evaluarla.

{project-name} evalúa cada política dentro de su propia caja de arena WebAssembly. La comunicación entre una instancia de `+policy-server+` (el "host") y la política WebAssembly (el "guest") utiliza el protocolo de comunicación waPC. La descripción del protocolo forma parte de la documentación dexref:../tutorials/writing-policies/index.adoc[las políticas de redacción].
Las políticas también pueden utilizar las interfaces proporcionadas por laxref:../tutorials/writing-policies/wasi/01-intro-wasi.adoc[Web Assembly System Interface] (WASI).

== Cómo {project-name} maneja muchos PolicyServer y políticas

Un cluster puede tener muchos PolicyServers y {project-name} políticas definidas.
Tener muchos PolicyServers tiene sus ventajas:

* Puede aislar del resto del clúster los namespaces o tenants ruidosos, o los que generan muchas evaluaciones de políticas, para no afectar negativamente a otras operaciones del clúster.

* Puede ejecutar políticas de misión crítica en un grupo dedicado de PolicyServer, haciendo que su infraestructura sea más resistente.

Un recurso PolicyServer define cada `+policy-server+` y un recurso`+ClusterAdmissionPolicy+` o `+AdmissionPolicy+` define cada política.

Un `+ClusterAdmissionPolicy+` y un `+AdmissionPolicy+` se unen a un `+policy-server+`.
Cualquier `+ClusterAdmissionPolicy+` que no especifique un `+policy-server+` se vincula al PolicyServer predeterminado. Si un `+ClusterAdmissionPolicy+` hace referencia a un`+policy-server+` que no existe, su estado es `+unschedulable+`.

Cada `+policy-server+` define muchos puntos finales de validación, uno para cada política definida en su archivo de configuración. Puede cargar la misma política varias veces, con diferentes parámetros de configuración.

Los recursos `+ValidatingWebhookConfiguration+` y `+MutatingWebhookConfiguration+`hacen que el servidor API de Kubernetes conozca estas políticas. A continuación,`+kubewarden-controller+` mantiene sincronizados el servidor API y los recursos de configuración.

El servidor API de Kubernetes envía las solicitudes de admisión entrantes al punto final de validación correcto expuesto por `+policy-server+`.
