= Senden von Gesundheitsdaten über HTTP
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

== Übersicht

SUSE Observability kann Gesundheitsinformationen aus Ihren eigenen Datenquellen entweder über HTTP oder die xref:/setup/cli/cli-sts.adoc[SUSE Observability-CLI] synchronisieren.

== SUSE Observability-Empfänger-API

Die SUSE Observability Receiver API akzeptiert Topologie, Metriken, Ereignisse und Zustandsdaten in einem gemeinsamen JSON-Objekt. Der Standardspeicherort für die Empfänger-API ist die `+<STACKSTATE_RECEIVER_API_ADDRESS>+`, die mit Hilfe von `+<STACKSTATE_BASE_URL>+` und ``<+STACKSTATE_RECEIVER_API_KEY>+`` erstellt wird.

Die `+<STACKSTATE_RECEIVER_API_ADDRESS>+` für SUSE Observability, das auf Kubernetes oder OpenShift eingesetzt wird, lautet:

[,text]
----
https://<STACKSTATE_BASE_URL>/receiver/stsAgent/intake?api_key=<STACKSTATE_RECEIVER_API_KEY>
----

`+<STACKSTATE_BASE_URL>+` und `+<STACKSTATE_RECEIVER_API_KEY>+` werden während der Installation von SUSE Observability festgelegt. Einzelheiten finden Sie unter xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_generate_values_yaml[Kubernetes-Installation - Konfigurationsparameter].

== JSON

=== Gemeinsames JSON-Objekt

Topologie-, Telemetrie- und Gesundheitsdaten werden per HTTP POST an die Empfänger-API gesendet. Es gibt ein gemeinsames JSON-Objekt, das für alle Nachrichten verwendet wird.

[,javascript]
----
{
  "collection_timestamp": 1548855554, // the epoch timestamp for the collection
  "events": {}, // used to send events data
  "internalHostname": "localdocker.test", // the host sending this data
  "metrics": [], // used to send metrics data
  "service_checks": [],
  "topologies": [], // used to send topology data
  "health": // used for sending health data
}
----

=== JSON-Nutzdaten zur Gesundheit

SUSE Observability akzeptiert Gesundheitsdaten auf der Grundlage eines ausgewählten xref:/configure/health/health-synchronization.adoc#_consistency_models[Konsistenzmodells]. Die Nachrichten, die für jedes Modell gesendet werden können, werden auf den folgenden Seiten beschrieben:

* xref:/configure/health/send-health-data/repeat_snapshots.adoc[Schnappschüsse wiederholen JSON]
* xref:/configure/health/send-health-data/transactional_increments.adoc[Transaktionsbezogene Inkremente JSON]

== Siehe auch

* xref:/setup/cli/cli-sts.adoc[Installieren Sie die SUSE Observability CLI]
