= Meilleures pratiques GitOps pour les tortues et l'ICPA
:revdate: 2025-10-02
:page-revdate: {revdate}

ifeval::["{build-type}" == "product"]
Cette section présente les meilleures pratiques pour la mise en œuvre de GitOps avec Turtles et Cluster API (CAPI), en se concentrant sur l'utilisation de https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/index.html[Continuous Delivery] en combinaison avec le *Cluster API Addon Provider Fleet*(`+CAAPF+`) pour automatiser le provisionnement des agents et l'intégration dans l'écosystème `+CAPI+`.
endif::[]
ifeval::["{build-type}" == "community"]
Cette section présente les meilleures pratiques pour la mise en œuvre de GitOps avec Turtles et Cluster API (CAPI), en se concentrant sur l'utilisation de https://fleet.rancher.io/[Fleet] en combinaison avec le *Cluster API Addon Provider Fleet*(`+CAAPF+`) pour automatiser le provisionnement des agents et l'intégration dans l'écosystème `+CAPI+`.
endif::[]

Ces conseils sont transférables et peuvent être appliqués même si vous utilisez une solution GitOps différente.

== Conseils courants

ifeval::["{build-type}" == "product"]
- **Séparer les clusters CAPI et les configurations ClusterClass :**
  Les configurations des clusters CAPI (`+clusters/+`) doivent être distinctes des définitions CAPI `+ClusterClass+` (`+templates/+`). Cette séparation permet de provisionner plusieurs clusters à partir de modèles partagés tout en réduisant le risque de modifications involontaires de l'infrastructure.
- **Isoler les configurations des modules complémentaires :**
  Stocker les manifestes d'application dans `+applications/+`, en veillant à ce qu'ils soient indépendants de `+Clusters+` et `+ClusterClasses+`. Cela permet un approvisionnement sélectif ou groupé en fonction de la demande de l'utilisateur ou de sélecteurs correspondants, évitant ainsi toute interférence avec l'infrastructure du cluster. Veuillez noter que les dépendances de la carte Helm doivent être https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/gitrepo-content.html#_fleet_yaml[actualisées à l'adresse] avant le provisionnement de l'addon.
- **Utiliser des ressources GitRepo imbriquées :**
  Exploiter les ressources https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/gitrepo-content.html#_nested_gitrepo_crs[] imbriquées `+GitRepo+` dans Fleet pour structurer efficacement le contenu du référentiel. Cette approche permet un provisionnement modulaire, combinant les définitions de `+ClusterClass+`, les addons/applications nécessaires et les configurations de grappes tout en maintenant la séparation des préoccupations.
- **Utiliser les outils d'intégration GitOps lorsqu'ils sont disponibles :**
  Lors de la configuration de GitOps, il convient de prendre en compte les outils disponibles et les fonctionnalités qu'ils offrent. En voici un exemple https://rancher.github.io/cluster-api-addon-provider-fleet/00_intro.html[`+CAAPF+`]qui automatise l'installation de Fleet GitOps sur les clusters `+CAPI+` et offre une automatisation pratique.
- **Appliquer les superpositions Kustomize pour une personnalisation spécifique à l'environnement :**
  Utilisez `+overlays/+` pour stocker les superpositions Kustomize pour différents environnements. Cela garantit que les changements de configuration, tels que les ajustements d'échelle, les modifications de réseau ou les mises à niveau de composants, peuvent être appliqués de manière dynamique sans modifier les manifestes de base.
- **Utiliser les patchs de comparaison :**
  Fleet permet d'ignorer sélectivement les différences de ressources si la liasse contient des règles appropriées pour la https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/troubleshooting.html#_suse_rancher_prime_continuous_delivery_deployment_stuck_in_modified_state[détection de] Cela permettrait d'éviter que les liasses soient bloquées dans un état modifié.
endif::[]
ifeval::["{build-type}" == "community"]
- **Séparer les clusters CAPI et les configurations ClusterClass :**
  Les configurations des clusters CAPI (`+clusters/+`) doivent être distinctes des définitions CAPI `+ClusterClass+` (`+templates/+`). Cette séparation permet de provisionner plusieurs clusters à partir de modèles partagés tout en réduisant le risque de modifications involontaires de l'infrastructure.
- **Isoler les configurations des modules complémentaires :**
  Stocker les manifestes d'application dans `+applications/+`, en veillant à ce qu'ils soient indépendants de `+Clusters+` et `+ClusterClasses+`. Cela permet un approvisionnement sélectif ou groupé en fonction de la demande de l'utilisateur ou de sélecteurs correspondants, évitant ainsi toute interférence avec l'infrastructure du cluster. Veuillez noter que les dépendances de la carte Helm doivent être https://fleet.rancher.io/gitrepo-content#fleetyaml[actualisées à l'adresse] avant le provisionnement de l'addon.
- **Utiliser des ressources GitRepo imbriquées :**
  Exploiter les ressources https://fleet.rancher.io/gitrepo-content#nested-gitrepo-crs[] imbriquées `+GitRepo+` dans Fleet pour structurer efficacement le contenu du référentiel. Cette approche permet un provisionnement modulaire, combinant les définitions de `+ClusterClass+`, les addons/applications nécessaires et les configurations de grappes tout en maintenant la séparation des préoccupations.
- **Utiliser les outils d'intégration GitOps lorsqu'ils sont disponibles :**
  Lors de la configuration de GitOps, il convient de prendre en compte les outils disponibles et les fonctionnalités qu'ils offrent. En voici un exemple https://rancher.github.io/cluster-api-addon-provider-fleet/00_intro.html[`+CAAPF+`]qui automatise l'installation de Fleet GitOps sur les clusters `+CAPI+` et offre une automatisation pratique.
- **Appliquer les superpositions Kustomize pour une personnalisation spécifique à l'environnement :**
  Utilisez `+overlays/+` pour stocker les superpositions Kustomize pour différents environnements. Cela garantit que les changements de configuration, tels que les ajustements d'échelle, les modifications de réseau ou les mises à niveau de composants, peuvent être appliqués de manière dynamique sans modifier les manifestes de base.
- **Utiliser les patchs de comparaison :**
  Fleet permet d'ignorer sélectivement les différences de ressources si la liasse contient des règles appropriées pour la https://fleet.rancher.io/troubleshooting#fleet-deployment-stuck-in-modified-state[détection de] Cela permettrait d'éviter que les liasses soient bloquées dans un état modifié.
endif::[]

== Stratégie de séparation des dossiers

Un référentiel bien structuré simplifie la gestion et améliore la clarté. La stratégie suivante de séparation des dossiers est recommandée :

----
repo-root/
│── fleet/
│   ├── providers/         # CAPIProvider files to use with templates
│   │   ├── core/          # Core provider configuration
│   │   ├── infra-docker/  # Docker provider configuration
│   │   ├── infra-aws/     # AWS provider configuration
│   ├── clusters/          # Cluster-specific configurations
│   │   ├── prod/          # Production clusters
│   │   ├── staging/       # Staging clusters
│   │   ├── dev/           # Development clusters
│   ├── addons/            # Application-specific manifests focused on cluster bootstrapping, like CNI, CCM, CPI configurations.
│   │   ├── cni/           # Group applications based on purpose. Provide fleet.yaml per each sub-directory to maintain bundle separation.
│   │   ├── ccm/
│   ├── templates/         # CAPI ClusterClass templates for cluster provisioning
│   ├── fleet.yaml         # Fleet bundle configuration
│── overlays/              # Kustomize overlays for different environments
│   ├── prod/.             # Kustomize overlays for production environments
│   ├── staging/.          # Kustomize overlays for staging environments
│   ├── dev/.              # Kustomize overlays for development environments
----

== Configuration des fournisseurs

Les fournisseurs CAPI définissent les composants de l'infrastructure nécessaires à l'approvisionnement des clusters. Une configuration simple peut ressembler à ce qui suit :

----
repo-root/
│── fleet/
│   ├── providers/
│   │   ├── core/
│   │   |   ├── core.yaml  # Core `+CAPIProvider+` definition
│   │   |   ├── fleet.yaml # Fleet.yaml definition for the provider setup
----

où se trouve le fournisseur de base :

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: cluster-api
spec:
  type: core
----

== Configuration des modèles

Spécifiez `+dependsOn+` dans `+fleet.yaml+` pour des paquets spécifiques `+CAPIProvider+` ou des composants externes `+GitRepo+`. Cela permet de garantir que les modèles sont déployés dans le bon ordre et d'éviter les problèmes lorsque des contrôleurs de composants manquent ou ne sont pas prêts à accepter les définitions de `+ClusterClass+`.

[source,yaml]
----
namespace: capa-clusters
dependsOn:
  - name: core      # Ensure core bundle is installed first
  - name: infra-aws # Wait for AWS provider installation
----

== Configuration des clusters

Utilisez des étiquettes pour faire correspondre dynamiquement les grappes avec les modules complémentaires requis, ce qui permet de déployer uniquement les charges de travail nécessaires.

Exemple d'utilisation de l'étiquette :

[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aws-cluster
  labels:
    cni: calico
    ccm: aws
    env: dev
----

[WARNING]
====
Il est recommandé de séparer les définitions de grappes des modèles, car la suppression des grappes permet au contrôleur CAPI de traiter la suppression dans le bon ordre. L'élimination simultanée des sites `+Clusters+` et `+ClusterClasses+` peut donner des résultats inattendus.
====

== Configuration de l'addon

La configuration des addons est essentielle pour rationaliser le provisionnement des clusters et garantir qu'ils atteignent l'état `+Ready+` sans intervention manuelle ni outil tiers.

Les modules complémentaires pour les grappes doivent définir des règles de sélection précises afin d'établir des correspondances avec des grappes correctement étiquetées.

L'exemple ci-dessous présente un cluster qui nécessite l'installation de `+Calico+` CNI et de `+AWS+` Cloud Controller Manager (CCM) :

[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aws-cluster
  labels:
    cni: calico
    ccm: aws
----

Cette configuration nécessite deux ressources `+GitRepo+`, chacune responsable de l'approvisionnement en modules d'extension sur la base d'étiquettes spécifiques - l'une pour `+cni: calico+` et l'autre pour `+ccm: aws+`.

Voici un exemple de ressource `+GitRepo+` pour le déploiement de la CNI `+Calico+`:

[source,yaml]
----
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: calico
spec:
  branch: main
  paths:
  - /fleet/applications/calico
  repo: https://github.com/rancher-sandbox/cluster-api-addon-provider-fleet.git
  targets:
  - clusterSelector:
      matchLabels:
        cni: calico
        env: dev
----

Cela garantit que la CNI `+Calico+` n'est déployée que sur les clusters étiquetés `+cni: calico+` et `+env: dev+`, ce qui permet un approvisionnement sélectif de l'environnement.

=== Template des valeurs du tableau de bord

La configuration de l'addon doit ajuster dynamiquement la charge de travail de `+Calico+` en fonction de la définition du cluster correspondant et de l'état spécifique du cluster. Pour ce faire, il est possible d'utiliser une configuration `+fleet.yaml+`, similaire à la structure suivante :

----
repo-root/
│── fleet/
│   ├── applications/
│   │   ├── calico/
│   │   │   ├── fleet.yaml # Fleet configuration for the Calico setup
----

Le fichier `+fleet.yaml+` définit les règles de modélisation et `+comparePatches+` afin de garantir un déploiement harmonieux, indépendamment de la configuration du cluster. Pour en savoir plus sur le modèle `+CAAPF+`, qui est utilisé ici, consultez la officielle https://rancher.github.io/cluster-api-addon-provider-fleet/04_reference/02_templating-strategy.html[documentation].

[source,yaml]
----
helm:
  releaseName: projectcalico
  repo: https://docs.tigera.io/calico/charts
  chart: tigera-operator
  templateValues:
    installation: |-
      cni:
        type: Calico
        ipam:
          type: HostLocal
      calicoNetwork:
        bgp: Disabled
        mtu: 1350
        ipPools:
          ${- range $cidr := .ClusterValues.Cluster.spec.clusterNetwork.pods.cidrBlocks }
          - cidr: "${ $cidr }"
            encapsulation: None
            natOutgoing: Enabled
            nodeSelector: all()${- end}

diff:
  comparePatches:
  - apiVersion: operator.tigera.io/v1
    kind: Installation
    name: default
    operations:
    - {"op":"remove", "path":"/spec/kubernetesProvider"}
----
