= ランチャーのセットアップ
:revdate: 2026-02-18
:page-revdate: {revdate}

== Rancherのインストール

_すでにRancher v2.13以降を実行している場合は、このセクションを飛ばしてxref:tutorials/first-cluster.adoc[Your First Clusterに]ジャンプできます。_

[NOTE]
====
Rancher v2.13から、{product_name} がRancherシステムチャートとしてプリインストールされました。{product_name} を別途インストールする必要はなくなった。Rancher v2.13以降をインストールするだけで、Cluster API (CAPI)を使い始めることができます。

====

既存または新規のKubernetesクラスタにRancherをインストールするには、Helmが推奨される。

ifeval::["{build-type}" == "product"]
[TIP]
====
Rancherの公式https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/installation-and-upgrade.html[インストールガイドの]いずれかに従ってください。
====
endif::[]
ifeval::["{build-type}" == "community"]
[TIP]
====
Rancherの公式https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade[インストールガイドの]いずれかに従ってください。
====
endif::[]

以下は、Helmを使ってRancherをインストールする最小限の例だ：

[source,bash]
----
helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --create-namespace \
    --set hostname=<rancher-hostname> \
    --version <rancher-version> \
    --wait
----

`<rancher-hostname>` を Rancher サーバーの実際のホスト名に置き換え、`--version` を使用して`v2.13.0` 以降の Rancher バージョンを指定します。

== インストールされるもの

Rancher v2.13以降がインストールされると、{product_name} は`cattle-turtles-system` ネームスペースにシステムコンポーネントとして自動的にデプロイされる。これには以下が含まれる：

* すべてのCAPI関連リソースを処理する`rancher-turtles-controller-manager` ポッド
* コアCAPI CRDとコアCAPIコントローラ
* CAPI プロバイダを宣言的に定義できる`CAPIProvider` カスタムリソース。

[NOTE]
====
中核となるCAPIコントローラー・マニフェストはConfigMapに組み込まれており、エアギャップ環境での操作を簡素化する。
====

== CAPIプロバイダのインストール

Rancherに組み込まれた{product_name} 、CAPIプロバイダーはデフォルトではバンドルされなくなった。プロバイダは、`CAPIProvider` カスタムリソースを使用して宣言的に管理され、認定プロバイダをインストールするために別のプロバイダチャートが利用可能です。プロバイダー・チャートの詳細については、xref:user/providers.adoc[Install certified providersを]参照のこと。

例えば、プロバイダーを定義する：

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws
  namespace: cattle-turtles-system
spec:
  type: infrastructure
  name: aws
----

設定オプションの完全なリストについては、xref:reference/capiprovider.adoc[CAPIProviderリファレンスを]参照してください。

これで{product_name} を使う準備は整った！🎉