= Comment ajouter des disques de groupes de volumes LVM supplémentaires pendant l'installation ?
:revdate: 2025-09-08
:page-revdate: {revdate}

Cet exemple couvre la configuration d'un hôte avec plusieurs disques dont certains sont utilisés dans le cadre d'une configuration LVM.

Par exemple, nous avons un hôte avec trois disques (`/dev/sda`, `/dev/sdb` et `/dev/sdc`). 

Le premier disque est utilisé pour une installation normale d'Elemental et les deux autres sont utilisés dans le cadre d'un groupe LVM où des volumes logiques arbitraires sont créés, formatés et montés au moment du démarrage via un fichier étendu `fstab`.

Dans cet exemple, les étapes de configuration du nuage sont nécessaires à deux stades différents. Tout d'abord, certains xref:references/cloud-config-reference.adoc#_elemental_client_cloud_config_hooks[crochets d'installation] sont nécessaires pour préparer et gérer les volumes LVM pendant l'installation. Deuxièmement, une configuration du nuage est nécessaire au moment du démarrage pour s'assurer que les volumes LVM créés sont inclus dans `/etc/fstab` et par conséquent montés.

Les crochets d'installation peuvent être inclus dans la section `SeedImage.spec.cloud-config` avec quelque chose comme :

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: custom-seed
  namespace: fleet-default
spec:
  ...
  cloud-config:
    name: "Create LVM logic volumes over some physical disks"
    stages:
      post-install:
      - name: "Create physical volume, volume group and logical volumes"
        if: '[ -e "/dev/sdb" ] && [ -e "/dev/sdc" ]'
        commands:
        - | 
          # Create the physical volume, volume group and logical volumes
          pvcreate /dev/sdb /dev/sdc
          vgcreate elementalLVM /dev/sdb /dev/sdc
          lvcreate -L 8G -n elementalVol1 elementalLVM
          lvcreate -l 100%FREE -n elementalVol2 elementalLVM
          # Trigger udev detection
          if [ ! -e "/dev/elementalLVM/elementalVol1" ] || [ ! -e "/dev/elementalLVM/elementalVol2" ]; then
            sleep 10
            udevadm settle
          fi
          # Ensure devices are already available
          [ -e "/dev/elementalLVM/elementalVol1" ] || exit 1
          [ -e "/dev/elementalLVM/elementalVol2" ] || exit 1
          # Format logical volumes with a known label for later use in fstab
          mkfs.xfs -L eVol1 /dev/elementalLVM/elementalVol1
          mkfs.xfs -L eVol2 /dev/elementalLVM/elementalVol2
----

Les périphériques LVM sont créés et formatés comme souhaité. C'est un bon exemple de crochet d'installation, car cette configuration n'est nécessaire qu'une seule fois, au moment de l'installation. Une autre solution consisterait à effectuer la même action au premier démarrage, mais cela nécessiterait une logique plus sophistiquée pour s'assurer qu'elle n'est appliquée qu'une seule fois au premier démarrage. Enfin, les données de configuration du nuage au démarrage contiennent les paramètres du point de montage pour déclencher les montages. Le fichier Elemental OS `fstab` est éphémère et créé dynamiquement au moment du démarrage. C'est pourquoi il n'existe pas pendant l'installation et ne peut pas être utilisé dans un crochet d'installation.

L'exemple suivant permet de personnaliser le fichier `/etc/fstab` à l'aide de la section `cloud-config` d'une ressource MachineRegistration :

[,yaml]
----
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: my-nodes
  namespace: fleet-default
spec:
  ...
  config:
    ...
    cloud-config:
      stages:
        initramfs:
        - name: "Extend fstab to mount LVM logical volumes at boot"
          commands:
          - |
            echo "LABEL=eVol1 /run/elemental/eVol1  xfs defaults  0 0" >> /etc/fstab
            echo "LABEL=eVol2 /run/elemental/eVol2  xfs defaults  0 0" >> /etc/fstab
----

[NOTE]
====
L'xref:references/cloud-config-reference.adoc[étape] `initramfs` est la dernière étape avant de passer à l'arbre racine proprement dit. À ce stade, le fichier `/etc/fstab` existe déjà et peut être adapté avant de changer de racine. Une fois l'arbre racine final exécuté, SystemD se chargera du reste de l'initialisation et l'appliquera.
====