= Configurar endereços IP internos e externos do K3s e do RKE2
:revdate: 2025-09-08
:page-revdate: {revdate}

O K3s e o RKE2 permitem especificar os endereços IP internos e externos de um nó por meio dos parâmetros `+--node-ip+` e `+--node-external-ip+`.

O Rancher Provisioning permite preencher esses parâmetros coletando o endereço IP da interface de rede de cada nó.

De qualquer forma, os métodos para coletar essas opções de ip para _Custom_ Rancher Clusters e _Elemental_ Rancher Clusters são diferentes.

== Configuração de endereços IP internos e externos do K3s e do RKE2 no provisionamento do Rancher Cluster

O provisionamento do Rancher permite especificar na seção Rancher Agent as interfaces de rede que devem ser vinculadas aos endereços IP internos e externos de cada nó provisionado.

Isso é feito adicionando os nomes das interfaces de rede das quais os endereços IP devem ser extraídos nas variáveis de ambiente do agente `+CATTLE_INTERNAL_ADDRESS+` e `+CATTLE_ADDRESS+` (https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/rancher-agent-options#ip-address-options [consulte os documentos do Rancher]).

[NOTE]
====
As variáveis de ambiente `+CATTLE_INTERNAL_ADDRESS+` e `+CATTLE_ADDRESS+` Agent podem ser preenchidas diretamente com os endereços IP desejados. De qualquer forma, como os endereços IP internos e externos são _por nó_, isso só funcionaria em clusters de nó único.
====


[CAUTION]
====
Embora durante a criação de um cluster elementar seja possível adicionar variáveis de ambiente do agente, as variáveis `+CATTLE_ADDRESS+` e `+CATTLE_INTERNAL_ADDRESS+` são ignoradas e não resultariam na configuração dos endereços IP internos e externos dos nós provisionados.
====


== Configurar endereços IP internos e externos do K3s e do RKE2 em clusters elementares

O Elemental permite configurar os endereços IP internos e externos dos nós do cluster, anexando os rótulos `+elemental.cattle.io/InternalIP+` e `+elemental.cattle.io/ExternalIP+` aos recursos xref:references/machineinventory-reference.adoc[do MachineInventory] que rastreiam os nós de destino.

Esses rótulos, quando anexados a um recurso xref:references/machineinventory-reference.adoc[MachineInventory], são usados para preencher os endereços IP internos e externos dos nós associados.

Os rótulos podem ser adicionados aos campos xref:references/machineregistration-reference.adoc[MachineRegistration] `+machineInventoryLabels+`, usando as variáveis de endereço IP xref:label-templates/label-templates-network.adoc[do Network Label Template] como valores, para permitir a coleta dos endereços IP de cada nó.

Exemplo: xref:references/machineregistration-reference.adoc[MachineRegistration], em que os nós terão o endereço IP interno definido a partir da interface eth0 e o endereço IP externo a partir da eth1.

.registration.yaml
[,yaml]
----
include::example$labeltemplates/registration.yaml[]
----
