= Restaurar
:revdate: 2025-09-08
:page-revdate: {revdate}

Siga este guia para restaurar uma configuração do {elemental-product-name} a partir de um backup com o Rancher.

== Preparar o operador do rancher-backup e os arquivos de backup para restauração

Acesse a oficial https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher[documentação] Rancher e certifique-se de que o `+rancher-backup operator+` esteja instalado e tenha acesso aos arquivos de backup.

Primeiro, você deve seguir esta xref:operator-operational-tasks/backup.adoc[documentação] para fazer um backup dos recursos do {elemental-product-name}.

== Restaurar a configuração do {elemental-product-name} com o operador do rancher-backup

Crie um `+restore object+` (adaptado às suas necessidades) para restaurar o tarball de backup.

[,yaml]
----
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: elemental-restore
spec:
  backupFilename: rancher-backup-430169aa-edde-4a61-85e8-858f625a755b-2022-10-17T05-15-00Z.tar.gz
----

Aplique o manifesto no Kubernetes.

[,shell]
----
kubectl apply -f elemental-restore.yaml
----

Verifique os registros do operador do rancher-backup.

[,shell]
----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

Verifique se o arquivo de backup foi restaurado com êxito.

[,shell]
----
...
INFO[2022/10/31 06:34:50] Processing controllerRef apps/v1/deployments/rancher
INFO[2022/10/31 06:34:50] Done restoring
...
----

Continue com o procedimento da https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster[documentação do] Rancher
