= Registrar um sistema operacional não gerenciado
:revdate: 2025-09-08
:page-revdate: {revdate}

Normalmente, o {elemental_operator_url}[{elemental_operator_name}] gerencia os sistemas operacionais que são instalados e configurados pelo {elemental_toolkit_url}[{elemental_toolkit_name}]. +
Por exemplo, para automatizar a instalação, o upgrade e a redefinição do sistema operacional, o `+elemental-register+` conta com a CLI do `+elemental+` para executar essas operações.

No entanto, também é possível registrar e fornecer sistemas {elemental-product-name} "Toolkitless".

Nesse cenário, xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_register_command_line_tool[o elemental-register] precisa ser instalado no sistema. +
Opcionalmente, o xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] pode ser instalado. Observe que, sem o `+elemental-system-agent+`, o {elemental_operator_name} não poderá provisionar nenhum cluster do k8s na máquina. Nesse caso, o site {elemental_operator_name} só pode ser usado para fins de inventário do sistema operacional.

Por fim, no cluster de gerenciamento, o `+MachineRegistration+` deve ativar o sinalizador `+spec.config.elemental.registration.no-toolkit+`.

Quando o `+no-toolkit+` estiver ativado no `+MachineRegistration+` e ocorrer um novo registro usando o `+elemental-register --install+` no sistema, um novo `+MachineInventory+` será criado no cluster de gerenciamento:

[,bash]
----
kubectl -n fleet-default describe machineinventory my-unmanaged-os-machine
----

O site `+MachineInventory+` será anotado com a anotação `+elemental.cattle.io/os.unmanaged: "true"+`, destacando que essa máquina não é gerenciada e tem funcionalidade limitada.

No sistema, após o registro bem-sucedido, os arquivos `+/etc/rancher/elemental/agent/config.yaml+` e `+/var/lib/elemental/agent/elemental_connection.json+` são criados automaticamente para configurar o `+elemental-system-agent+`.
O componente `+elemental-system-agent+` é necessário para o provisionamento de K8s e acionadores de reinicialização.

Quando uma xref:node-operational-tasks/reset.adoc[reinicialização da máquina] é acionada, por exemplo, com a exclusão direta do `+MachineInventory+`, o `+elemental-system-agent+` executará um plano de reinicialização simples que criará o arquivo sentinela `+/var/lib/elemental/.unmanaged_reset+`. +
A presença desse arquivo indica que a máquina precisa ser reiniciada. Isso pode envolver a interrupção de serviços, a desinstalação de pacotes, a formatação de dispositivos e assim por diante, dependendo de como a máquina é gerenciada de forma personalizada.

== Recursos suportados

* Registro de um `+MachineInventory+`
* Provisionamento do K8s (quando o xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] está instalado e em execução na máquina)
* Acionadores de reinicialização (quando o xref:rancher-os-management/architecture/architecture-components.adoc#_elemental_system_agent_daemon[elemental-system-agent] está instalado e em execução na máquina)

== Recursos sem suporte

* xref:references/cloud-config-reference.adoc[Configuração] orientada por inicialização na nuvem
* xref:node-operational-tasks/upgrade.adoc[Atualizações] do sistema operacional
* xref:node-operational-tasks/reset.adoc[Reinicialização] do sistema operacional
