= 配置 SDK 输出程序
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 可观察性

要向 SUSE Observability 发送数据，用于检测应用程序的 SDK 会使用内置的导出器。生产就绪设置使用靠近仪器应用程序的<<_with_a_collector_production_setup,收集器>>将数据发送到 SUSE Observability，但也可以让仪器应用程序<<_without_a_collector,直接将>>遥测数据<<_without_a_collector,发送到>>SUSE Observability。

== 带收集器（生产设置）

=== 用于 Kubernetes 的 SDK 导出器配置

所有 SDK，无论使用哪种语言，都使用相同的基本配置来定义 Open Telemetryhttps://opentelemetry.io/docs/concepts/glossary/#_service[服务名称]和输出端点（即遥测数据的发送位置）。

这些可以通过设置仪器应用程序的环境变量来配置。

在 Kubernetes 中，在工作负载的清单中设置这些环境变量（用应用服务的名称替换`<the-service-name>` ）：

[,yaml]
----
...
spec:
  containers:
  - env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317
    - name: OTEL_SERVICE_NAME
      value: <the-service-name>
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: grpc
...
----

示例中指定的端点假定收集器是按照xref:/setup/otel/collector.adoc[安装指南]中的默认值安装的。它使用`4317` 端口，该端口使用`gRPC` 版本的 OTLP 协议。有些仪器只支持 HTTP，在这种情况下，请使用`4318` 端口。

服务名称也可以从可能已经存在的 Kubernetes 标签中导出。例如

[,yaml]
----
spec:
  containers:
  - env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['app.kubernetes.io/component']
----

=== 用于其他安装的 SDK 导出器配置

要配置 SDK，请为您的应用程序设置这些环境变量：

[,bash]
----
export OTEL_EXPORTER_OTLP_ENDPOINT="http://<the-host-for-the-collector>:4317"
export OTEL_EXPORTER_OTLP_PROTOCOL="grpc"
export OTEL_SERVICE_NAME="<the-service-name>"
export OTEL_RESOURCE_ATTRIBUTES='service.namespace=<the-namespace>'
----

示例使用`4317` 端口，该端口使用`gRPC` 版本的 OTLP 协议。有些仪器只支持 HTTP，它使用`4318` 端口，协议设置为`http` 。请使用您语言的 SDK 文档来查看 SDK 支持哪种协议。`OTEL_EXPORTER_OLTP_ENDPOINT` 和`OTEL_EXPORTER_OTLP_PROTOCOL` 可以省略，它们的默认值是将数据发送到本地主机上的首选端点。

`OTEL_RESOURCE_ATTRIBUTES` 是可选项，除了定义服务命名空间外，还可用逗号分隔的列表设置更多资源属性。

=== gRPC vs HTTP

开放遥测协议 OTLP 支持 gRPC 和 HTTP 上的 protobuf。在上一节中，输出协议被设置为`gRPC` ，这通常能提供最佳性能。除了 SDK 不支持 gRPC 之外，还有其他原因导致人们更倾向于使用 HTTP：

* 某些防火墙的设置无法处理 gRPC
* (如果不进行额外配置，（反向）代理和负载平衡器可能不支持 gRPC
* gRPC 的长期连接可能会在负载平衡时造成问题。

要切换到 HTTP 而不是 gRPC，请将协议更改为`http` _，并_使用端口`4318` 。

总之，如果 gRPC 不适合您，您可以尝试使用 HTTP：

* `grpc` 协议使用收集器上的`4317` 端口
* `http` 协议使用收集器上的`4318` 端口

== 没有收集器

在小型测试设置中，直接从仪器应用程序向 SUSE Observability 发送数据可能会很方便。与上述收集器设置的唯一区别是使用了不同的`OTEL_EXPORTER_OTLP_ENDPOINT` 值：

* 关于 gRPC，请使用 SUSE Observability 的 OTLP 端点，参见xref:/setup/otel/otlp-apis.adoc[OTLP API 页面]。
* 要在 HTTP 中使用 SUSE Observability 的 OTLP over HTTP 端点，请参阅xref:/setup/otel/otlp-apis.adoc[OTLP API 页面]。

[NOTE]
====
用 SUSE Observability 端点替换收集器 URL*和*端口。根据您的 SUSE Observability 安装情况，端口会有所不同。
====

