= FAQ
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

As perguntas frequentes são atualizadas periodicamente e foram criadas para responder às perguntas que nossos usuários fazem com mais frequência sobre o K3.

== O K3s é um substituto adequado para o Kubernetes?

O K3s é uma distribuição do Kubernetes certificada pelo CNCF e pode fazer tudo o que é necessário para um cluster padrão do Kubernetes. É apenas uma versão mais leve. Consulte a página xref:introduction.adoc[principal] da documentação para obter mais detalhes.

== Como posso usar meu próprio Ingress em vez do Traefik?

Basta iniciar o servidor K3s com `--disable=traefik` e implementar seu ingresso.

== O K3s é compatível com o Windows?

No momento, o K3s não oferece suporte nativo ao Windows, mas estamos abertos a essa ideia no futuro.

== O que são exatamente servidores e agentes?

Para obter informações detalhadas sobre os componentes que formam um servidor e um agente, consulte a xref:architecture.adoc[página Arquitetura].

== Como posso criar a partir do código-fonte?

Consulte o K3s https://github.com/k3s-io/k3s/blob/main/BUILDING.md[BUILDING.md] com instruções.

== Onde estão os registros dos K3s?

O local dos registros do K3s varia de acordo com a forma como você executa o K3s e o sistema operacional do nó.

* Quando executado a partir da linha de comando, os registros são enviados para stdout e stderr.
* Quando executado em openrc, os registros serão criados em `/var/log/k3s.log`.
* Quando executados no Systemd, os registros serão enviados para o Journald e poderão ser visualizados usando `journalctl -u k3s`.
* Os registros de pods podem ser encontrados em `/var/log/pods`.
* Os registros do Containerd podem ser encontrados em `/var/lib/rancher/k3s/agent/containerd/containerd.log`.

É possível gerar logs mais detalhados usando o sinalizador `--debug` ao iniciar o K3s (ou `debug: true` no arquivo de configuração).

O Kubernetes usa uma estrutura de registro conhecida como `klog`, que usa uma única configuração de registro para todos os componentes de um processo.
Como o K3s executa todos os componentes do Kubernetes em um único processo, não é possível configurar diferentes níveis de registro ou destinos para componentes individuais do Kubernetes.
O uso dos args dos componentes `-v=<level>` ou `--vmodule=<module>=<level>` provavelmente não terá o efeito desejado.

Consulte xref:advanced.adoc#_additional_logging_sources[Fontes adicionais de registro] para obter ainda mais opções de registro.

== Posso executar o K3s no Docker?

Sim, há várias maneiras de executar o K3s no Docker. Consulte xref:advanced.adoc#_running_k3s_in_docker[Advanced Options] para obter mais detalhes.

== Qual é a diferença entre o servidor K3s e os tokens de agente?

Para obter mais informações sobre o gerenciamento de tokens de associação de K3s, consulte a xref:cli/token.adoc[documentação do comando`k3s token` ].

== Qual é a compatibilidade das diferentes versões do K3?

Em geral, aplica-se https://kubernetes.io/docs/setup/release/version-skew-policy/[a política de distorção de versão do].

Em resumo, os servidores podem ser mais novos que os agentes, mas os agentes não podem ser mais novos que os servidores.

== Estou com um problema, onde posso obter ajuda?

Se estiver tendo problemas com a implementação de K3s, você deve:

. Verifique a página de xref:known-issues.adoc[problemas conhecidos].
. Verifique se você resolveu qualquer xref:installation/requirements.adoc#_operating_systems[preparação adicional do sistema operacional]. Execute o site `k3s check-config` e certifique-se de que ele seja aprovado.
. Pesquise no K3s https://github.com/k3s-io/k3s/issues[Issues] e https://github.com/k3s-io/k3s/discussions[Discussions] para encontrar um que corresponda ao seu problema.
. Entre no canal K3s https://slack.rancher.io/[do Slack do] Rancher para obter ajuda.
. Envie um https://github.com/k3s-io/k3s/issues/new/choose[New Issue] no Github do K3s descrevendo sua configuração e o problema que está ocorrendo.
