= Projetos relacionados
:page-languages: [en, ja, ko, zh]
:revdate: 2025-03-31
:page-revdate: {revdate}

Os projetos que implementam a distribuição de K3s são acréscimos bem-vindos para ajudar a expandir a comunidade. Esses projetos ajudam a:

* Explore os recursos e os possíveis aplicativos do K3.
* Ampliar a funcionalidade do K3 em diferentes plataformas e ambientes.
* Simplifique o processo de criação de grandes clusters K3s de alta disponibilidade (HA).

== k3s-ansible

Para os usuários que desejam inicializar um cluster K3s de vários nós e estão familiarizados com o ansible, dê uma olhada no repositório https://github.com/k3s-io/k3s-ansible[] k3s-io/k3s-ansible. Esse conjunto de playbooks do Ansible oferece uma maneira conveniente de instalar o K3s em seus nós, permitindo que você se concentre na configuração do cluster em vez de no processo de instalação.

== k3sup

Outro projeto que simplifica o processo de configuração de um cluster K3s é o https://github.com/alexellis/k3sup[] k3sup. Esse projeto, escrito em golang, requer apenas acesso ssh aos seus nós. Ele também oferece uma maneira conveniente de implementar K3s com datastores externos, não apenas com o etcd incorporado.

== autok3s

Outra ferramenta de provisionamento, https://github.com/cnrancher/autok3s[autok3s], fornece uma GUI para provisionar o cluster k3s em uma variedade de provedores de nuvem, VMs e máquinas locais. Essa ferramenta é útil para usuários que preferem uma interface gráfica para fornecer clusters K3s.

== hetzner-k3s

Para usuários que implementam na Hetzner Cloud, dê uma olhada em link:https://github.com/vitobotta/hetzner-k3s[hetzner-k3s]. Essa ferramenta CLI, escrita em Crystal, lida com as etapas adicionais necessárias para configurar um cluster K3s na Hetzner Cloud.
