ifdef::ss-ff-stackpacks2_enabled[]
= Topologie von OpenTelemetry
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Topologie von OpenTelemetry

{stackstate-product-name} kann die Anwendungs- und Infrastrukturtopologie automatisch aus OpenTelemetry (OTel)-Telemetriedaten ableiten.
Dies wird durch OpenTelemetry-Topologie-Mappings erreicht, die Trace- und metrische Signale deklarativ in Topologiekomponenten (Vertices) und Relationen (Edges) umwandeln.

== Übersicht

Im Großen und Ganzen funktioniert die Topologieerstellung aus OpenTelemetry wie folgt:

* OpenTelemetry-Telemetrie (Metriken und/oder Traces) wird vom Collector empfangen.
* Der OTel-Kollektor verwendet einen Topologie-Konnektor, der die konfigurierten Zuordnungen anhand der Telemetrie auswertet.
* Wenn die Mapping-Bedingungen mit der Telemetrie übereinstimmen, werden Komponenten und/oder Relationen erzeugt.
* Diese Topologieobjekte werden vom Dienst `+sync+` abgefragt und in den Topologiediagramm zusammengeführt.
* Mappings sind deklarativ, YAML-basiert und werden kontinuierlich ausgewertet, während Telemetrie durch das System fließt.

Derzeit unterstützte Signale:

* Metriken
* Spurensuche

[NOTE]
====
Die protokollbasierte Topologieerstellung wird noch nicht unterstützt.
====

Weitere Informationen zu Komponenten- und Beziehungsmappings finden Sie auf der Seite xref:/setup/custom-integrations/otelmappings/concepts.adoc[Konzepte].

endif::ss-ff-stackpacks2_enabled[]
