include::partial$variables.adoc[]
= Renforcement de la sécurité
:revdate: 2026-03-18
:page-revdate: {revdate}
:sidebar_label: Renforcement de la sécurité
:sidebar_position: 50
:description: Sécurisez les sites {project-name} grâce à des conseils de renforcement et à des pratiques d'excellence pour atténuer les menaces.
:keywords: ["{project-name}", kubewarden, kubernetes, security]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manuel de l'opérateur, sécurité

{project-name} s'efforce d'être sûr avec peu de configuration. Dans cette section et ses sous-pages, vous trouverez des conseils de renforcement (avec leurs compromis) pour sécuriser {short-project-name} lui-même.

Veuillez vous référer au xref:/reference/threat-model.adoc[modèle de menace pour] plus d'informations.

== `kubewarden-defaults` Tableau de bord

Les opérateurs peuvent obtenir un déploiement sécurisé en installant toutes les cartes {short-project-name} Helm. Il est recommandé d'installer la carte `kubewarden-defaults` Helm et d'activer les politiques recommandées avec :

[source,console]
----
helm install --wait -n kubewarden kubewarden-defaults kubewarden/kubewarden-defaults \
  --set recommendedPolicies.enabled=True \
  --set recommendedPolicies.defaultPolicyMode=protect
----

Cela permet d'avoir un PolicyServer par défaut et des politiques par défaut, en mode protection, pour garantir que la pile {short-project-name} est à l'abri des autres charges de travail.

== Vérification des artefacts {short-project-name} 

Reportez-vous au didacticiel xref:/tutorials/verifying-kubewarden.adoc[Vérifier{short-project-name}].

== RBAC

{short-project-name} décrit les configurations RBAC dans différentes sections _Explications._ Les utilisateurs peuvent affiner les autorisations nécessaires pour la fonction d'xref:/explanations/audit-scanner/audit-scanner.adoc#_permissions_and_serviceaccounts[analyse d'audit], ainsi que xref:/explanations/context-aware-policies.adoc[par] compte de service du xref:/explanations/context-aware-policies.adoc[serveur de stratégie] pour la fonction de prise en compte du contexte.

Pour afficher tous les rôles :

[source,console]
----
kubectl get clusterroles,roles -A | grep kubewarden
----

== Autorisations par politique

Pour les politiques contextuelles, les opérateurs spécifient des autorisations fines pour chaque politique sous `spec.contextAwareResources`, et celles-ci fonctionnent en conjonction avec le compte de service configuré pour le serveur de politiques sur lequel la politique s'exécute.

== Couverture de la charge de travail

Par défaut, {short-project-name} exclut certains espaces de nommage de la couverture de{short-project-name}. Cela permet de simplifier la première utilisation et l'interopérabilité avec d'autres charges de travail.

Les opérateurs soucieux de la sécurité peuvent régler cette liste d'espaces de nommage via la valeur`.global.skipNamespaces` pour les tableaux de bord `kubewarden-controller` et`kubewarden-defaults`.

== Admission à la sécurité des pods

À partir de la version 1.23, la pile de {short-project-name} est capable de fonctionner dans un espace de nommage où leshttps://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted[`restricted`` Pod Security Standards] sont en place, avec les meilleures pratiques actuelles de durcissement des pods.

Pour ce faire, vous devez ajouter le label `pod-security.kubernetes.io/enforce : restricted` à l'espace de nommage du déploiement {short-project-name}.

```console
kubectl label namespace kubewarden pod-security.kubernetes.io/enforce=restricted --overwrite
```

Pour plus de détails, consultez le sitehttps://kubernetes.io/docs/concepts/security/pod-security-admission/[documentation officielle] de l'admission à la sécurité des pods de Kubernetes.

=== SecurityContexts

Le diagramme de Helm `kubewarden-controller` configure les SecurityContexts et les expose dans son site `values.yaml`.

Le tableau de bord `kubewarden-defaults` permet de configurer le serveur de politiques par défaut `.spec.securityContexts` sous `.Values.policyServer.securityContexts`.

Pour les serveurs de politiques gérés par des opérateurs, vous pouvez les configurer via leurxref:/reference/CRDs.adoc#_policyserversecurity[`spec.securityContexts`].