include::partial$variables.adoc[]
= Enregistrement
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configurez l'initialisation de l'enregistreur pour l'enregistrement structuré dans votre politique en utilisant l'intégration Go SDK du projet oneLog.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "golang", "logging"].
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "golang", "go", "logging"].
:current-version: {page-origin-branch}

Le SDK Go s'intègre au projethttps://github.com/francoispqt/onelog[`onelog`]presque d'emblée.
// TODO: Last release 2019. Still good?

Le projet a choisi cette bibliothèque car :

* Il fonctionne avec les binaires WebAssembly.
Les autres solutions de journalisation courantes ne peuvent pas compiler pour cibler WebAssembly.
* Il fournit https://github.com/francoispqt/onelog#benchmarks[de bonnes performances.]
* Il prend en charge la journalisation structurée.

== Initialisation de l'enregistreur

Vous devez initialiser une structure d'enregistrement.
En effectuant cette initialisation dans une variable globale, vous pouvez vous connecter à partir des deux principaux points d'entrée de la politique : `validate` et`validate_settings`.

Dans le paquet principal, `main.go`, il y a une initialisation pour le logger :

[,go]
----
var (
    logWriter = kubewarden.KubewardenLogWriter{}
    logger    = onelog.New(
        &logWriter,
        onelog.ALL, // shortcut for onelog.DEBUG|onelog.INFO|onelog.WARN|onelog.ERROR|onelog.FATAL
    )
)
----

== Consommer l'enregistreur

Vous pouvez maintenant utiliser l'objet `logger` pour vous connecter à partir de n'importe quel endroit requis par votre politique :

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.Info("validating request")
    // ...
}
----

Vous pouvez ajouter une journalisation structurée :

[,go]
----
func validate(payload []byte) ([]byte, error) {
    // ...
    logger.WarnWithFields("logging something important", func(e onelog.Entry) {
        e.String("one_field", "a value")
        e.String("another_field", "another value")
    })
    // ...
}
----

Vous pouvez vous référer à lahttps://pkg.go.dev/github.com/francoispqt/onelog?utm_source=godoc[documentation]

L'enregistrement de la politique est confié à l'évaluateur de la politique (par exemple, `kwctl` ou `policy-server`), qui l'enregistre au nom de la politique.
Ils utilisent des mécanismes interopérables avec d'autres composants permettant le traçage distribué, tels quehttps://www.jaegertracing.io/[] Jaeger.
