include::partial$variables.adoc[]
= Sugerir uma melhoria na documentação
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Inicie uma melhoria na documentação abrindo um problema no GitHub com detalhes claros sobre o que está faltando, desatualizado, errôneo ou que requer uma revisão de qualidade.
:doc-persona: ["kubewarden-developer", "kubewarden-operator", "kubewarden-manager"]
:doc-topic: ["contribution-guide", "docs-contribution", "improvement"]
:doc-type: ["howto"]
:keywords: ["kubewarden", "documentation", "suggesting an improvement"]
:sidebar_label: Sugestão de melhorias no documento
:sidebar_position: 8
:current-version: {page-origin-branch}

Se você notar um problema na documentação do {short-project-name} ou quiser sugerir um novo conteúdo, abra um problema. Você só precisa ter acesso a uma do GitHubhttps://github.com/join[conta] e a um navegador.

Normalmente, qualquer novo trabalho de documentação para {short-project-name} começa com um problema no GitHub.
ifeval::["{build-type}" == "community"]
A equipe de documentação do https://github.com/orgs/kubewarden/teams/kubewarden-documentation[{short-project-name} os analisa, categoriza e marca. equipe de documentação] os analisa, categoriza e marca. ]] 
endif::[]
ifeval::["{build-type}" == "product"]
A equipe de documentação do https://github.com/orgs/rancher/teams/docs[{short-project-name} os analisa, categoriza e marca. equipe de documentação] os analisa, categoriza e marca. ]] 
endif::[]
Todos são bem-vindos para trabalhar em qualquer questão, inclusive o repórter, mas você deve atribuí-la a si mesmo antes de iniciar qualquer trabalho para evitar esforços duplicados.

== Abrir um problema

Para sugerir melhorias no conteúdo da documentação existente ou relatar um erro, abra um problema.

* Clique no ícone do GitHub Octocat na parte superior. Isso redireciona você para o
ifeval::["{build-type}" == "community"]
  https://github.com/kubewarden/docs[repositório de documentação para {short-project-name}].
endif::[]
ifeval::["{build-type}" == "product"]
  https://github.com/rancher/kubewarden-product-docs[repositório de documentação para {short-project-name}].
endif::[]
* Navegue até a guia Issues (Problemas) e clique em *New issue (Novo problema*).
* Descreva o problema ou a sugestão de melhoria. Quanto mais detalhes, melhor.
* Clique em *Submit new issue (Enviar nova edição*).
* Depois de enviar o problema, você pode atribuí-lo a si mesmo ou aguardar que um membro da comunidade o resolva. Os membros da equipe de documentação e da comunidade podem solicitar esclarecimentos antes de resolverem o seu problema. Você deve verificar ativamente seu problema ou https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications[ativar as notificações do GitHub].

== Sugestões de novos conteúdos

Para sugerir novos conteúdos, registre um problema usando um desses mecanismos:

* Escolha uma página existente na seção à qual você acha que o conteúdo pertence e clique em *Criar um problema*. OU
ifeval::["{build-type}" == "community"]
* Navegue até https://github.com/kubewarden/docs/issues/new/choose[] GitHub e registre o problema diretamente.
endif::[]
ifeval::["{build-type}" == "product"]
* Navegue até https://github.com/rancher/kubewarden-product-docs/issues/new/choose[] GitHub e registre o problema diretamente.
endif::[]

== Como você pode fazer uma contribuição valer a pena?

Nenhuma contribuição é grande ou pequena demais. Entretanto, para que a comunidade obtenha o máximo de valor, solicitamos que você siga as instruções abaixo ao relatar um problema:

* Concentre-se em fornecer uma descrição clara do problema. Alguns pontos importantes a serem considerados seriam descrever o que está faltando, o que está desatualizado, o que está errado ou o que requer melhorias qualitativas e técnicas.
* Descreva o impacto específico que o problema tem sobre os usuários.
* Limite o escopo da questão. Se o escopo for grande, divida-o em tarefas menores dentro de um problema. Por exemplo, "Criar um Guia de Contribuição" tem um escopo amplo, pois haveria várias tarefas associadas ao problema.
  No entanto, "Corrigir um erro gramatical na página Quickstart" é um problema de escopo mais restrito que exigiria apenas um único pull request.
* Verificação cruzada de problemas existentes para evitar trabalho duplicado.
* Verifique se há um pull request ou problema existente. Verifique se você faz referência ao problema existente ou à pull request dentro do problema que está abrindo para dar contexto aos colaboradores que possam querer trabalhar nele.
