= Configuración del ranchero
:revdate: 2026-02-18
:page-revdate: {revdate}

== Instalación de Rancher

_Si ya está ejecutando Rancher v2.13 o posterior, puede omitir esta sección y saltar a xref:tutorials/first-cluster.adoc[Su Primer Cluster]._

[NOTE]
====
A partir de Rancher v2.13, {product_name} está preinstalado como carta del sistema Rancher. Ya no es necesario instalar {product_name} por separado. Basta con instalar Rancher v2.13 o posterior para empezar a utilizar Cluster API (CAPI).

====

Helm es la forma recomendada de instalar Rancher en un clúster Kubernetes existente o nuevo.

ifeval::["{build-type}" == "product"]
[TIP]
====
Asegúrese de seguir una de las oficiales de https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/installation-and-upgrade.html[guías de instalación] para Rancher.
====
endif::[]
ifeval::["{build-type}" == "community"]
[TIP]
====
Asegúrese de seguir una de las oficiales de https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade[guías de instalación] para Rancher.
====
endif::[]

He aquí un ejemplo mínimo de instalación de Rancher con Helm:

[source,bash]
----
helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --create-namespace \
    --set hostname=<rancher-hostname> \
    --version <rancher-version> \
    --wait
----

Sustituya `+<rancher-hostname>+` por el nombre de host real de su servidor Rancher y utilice `+--version+` para especificar una versión de Rancher de `+v2.13.0+` o posterior.

== Qué se instala

Cuando se instala Rancher v2.13 o posterior, {product_name} se despliega automáticamente como un componente del sistema en el espacio de nombres `+cattle-turtles-system+`. Esto incluye:

* El pod `+rancher-turtles-controller-manager+`, que gestiona todos los recursos relacionados con CAPI.
* Core CAPI CRDs y el controlador core CAPI
* El recurso personalizado `+CAPIProvider+`, que permite la definición declarativa de proveedores CAPI.

[NOTE]
====
El núcleo del manifiesto del controlador CAPI está integrado en un ConfigMap, lo que simplifica el funcionamiento en entornos con cortafuegos.
====

== Instalación de proveedores CAPI

Con {product_name} integrado en Rancher, los proveedores CAPI ya no se incluyen por defecto. Los proveedores se gestionan de forma declarativa mediante el recurso personalizado `+CAPIProvider+`, y existe una tabla de proveedores independiente para instalar proveedores certificados. Para más información sobre el cuadro de proveedores, consulte xref:user/providers.adoc[Instalar proveedores certificados].

Por ejemplo, para definir un proveedor:

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws
  namespace: cattle-turtles-system
spec:
  type: infrastructure
  name: aws
----

Consulte la lista completa de opciones de configuración en la xref:reference/capiprovider.adoc[referencia CAPIProvider].

¡Ya está listo para utilizar {product_name}! 🎉