ifdef::ss-ff-stackpacks2_enabled[]
= 自定义集成概述
:revdate: 2026-01-06
:page-revdate: {revdate}
:description:  自定义集成概述

[IMPORTANT]
====
自定义集成是一项预生产、未发布的功能，因此随着功能的发展，可能会出现破坏性更改。它不用于生产。但可以在非生产环境中进行测试。
====

== 概述

定制集成利用 Open Telemetry 从各种来源收集和发送遥测数据（指标、跟踪、日志）到{stackstate-product-name} 。通过使用 Open Telemetry，用户可以检测其应用程序和服务，从而深入了解性能、可靠性和运行状况。
在{stackstate-product-name} 一侧，xref:setup/custom-integrations/otelmappings/README.adoc[开放式遥测映射]处理传入的遥测数据，应用必要的转换，并将其映射到{stackstate-product-name} 中的适当实体。可xref:use/alerting/k8s-add-monitors-cli.adoc[使用 CLI]、xref:setup/custom-integrations/metric-bindings/index.adoc[度量绑定]和xref:setup/custom-integrations/ui-presentation/README.adoc[用户界面显示] xref:use/alerting/k8s-add-monitors-cli.adoc[添加监控器]，以便在用户界面中显示摄取的遥测数据，添加警报和可观察性。所有东西都会被装在一个xref:setup/custom-integrations/develop.adoc[背包]里，以便分发。

== 开发设置

定制集成应针对{stackstate-product-name} 平台的预生产部署进行开发。要获得预生产设置以开始开发自定义集成，有两个选项：

=== SaaS 实例（推荐）：
对于内部 SUSE 团队，我们建议向{stackstate-product-name} 团队申请 SaaS 实例。这些实例已启用自定义集成，至少在每次发布新版本时都会自动更新，有时还会收到包含重要错误修复或实验功能增量的预发布版本。
通过专用通道联系我们（待定）。

=== 自我托管：
您可以在通过 helm 安装时设置一些功能标志，在自己托管的{stackstate-product-name} 安装中启用自定义集成：

    . 生成`custom_integrations_values.yaml` 。本指南假设您将其保存在 `$VALUES_DIR`

+
.$VALUES_DIR/custom_integrations_values.yaml
[,yaml]
----
global:
  features:
    experimentalStackpacks: true
----
+

    . 部署{stackstate-product-name} 舵图，生成的值加上 `.$VALUES_DIR/custom_integrations_values.yaml`

+
.helm_deploy.sh
[,text]
----
helm upgrade --install \
    --namespace suse-observability \
    --create-namespace \
    --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
    --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
    --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
    --values $VALUES_DIR/custom_integrations_values.yaml \
    suse-observability \
    suse-observability/suse-observability
----
+

endif::ss-ff-stackpacks2_enabled[]
