include::partial$variables.adoc[]
= ¿Qué es {project-name}?
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Obtenga información sobre el papel de {project-name} en la gestión de políticas de Kubernetes, que incluye la aplicación del cumplimiento y la optimización de recursos.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["introduction"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "cncf", "cncf sandbox", "kubernetes", "admission policy manager"]
:sidebar_label: Introducción
:sidebar_position: 1
:slug: /
:current-version: {page-origin-branch}

{project-name} es un motor de políticas de Kubernetes.
Pretende ser el motor de políticas universal para Kubernetes.

{intro-paragraph}

== ¿Cómo ayuda {project-name}?

{short-project-name} ofrece flexibilidad para la admisión y aplicación de políticas en un entorno Kubernetes.

=== Beneficios y valor

- Utilice cualquier lenguaje de programación que genere binarios https://webassembly.org[WebAssembly] para escribir sus directivas.
- WebAssembly permite la compatibilidad de políticas entre procesadores y sistemas operativos.
- Reutilización de políticas de otros motores de políticas sin necesidad de reescribirlas.
- Distribuya las políticas mediante mecanismos estándar y seguros, como los registros compatibles con OCI https://opencontainers.org[de].
- La aplicación de políticas en la admisión garantiza que sólo se ejecuten las cargas de trabajo conformes.
- El escáner de auditoría {short-project-name} comprueba de forma activa y continua el cumplimiento de las políticas a lo largo del tiempo.
- Verifique las políticas utilizando las herramientas y prácticas de https://slsa.dev[SLSA] (Supply Chain Levels for Software Artifacts).
- {project-name} ofrece un enfoque global de la gestión de la política de admisión.
- La pertenencia al CNCF y una creciente comunidad y ecosistema de código abierto ayudan a {short-project-name} con transparencia, colaboración y mejora.

=== Casos prácticos

- Fortalecimiento de la seguridad. Por ejemplo, aplicar políticas que restrinjan los privilegios de los contenedores, aplicar políticas de red o bloquear registros de imágenes inseguros.
- Auditoría de conformidad. Garantizar que las cargas de trabajo cumplen las normas y mejores prácticas organizativas o reglamentarias.
- Optimización de recursos. Aplicar límites y cuotas de recursos.

Hay más documentación sobre casos de uso en la página de xref:use-cases.adoc[casos de uso].

== ¿Es nuevo en {short-project-name}?

Si eres nuevo en el proyecto {short-project-name}, empieza por la xref:quick-start.adoc[guía de inicio rápido] y la página de xref:explanations/architecture.adoc[arquitectura].
Luego depende de adónde te lleven tus intereses. Para los desarrolladores de políticas hay secciones específicas de idiomas en los tutoriales. Para integradores y administradores hay una sección de instrucciones. La sección de explicaciones contiene material de referencia útil. También hay un xref:glossary.adoc[glosario].

== ¿Qué es WebAssembly?

Como se indica en el https://webassembly.org/[sitio web oficial de]:

____
WebAssembly (abreviado Wasm) es un formato de instrucciones binarias para una máquina virtual basada en pila. Wasm está diseñado como un objetivo de compilación portátil para lenguajes de programación, permitiendo el despliegue en la web de aplicaciones cliente y servidor.
____

Wasm se concibió originalmente como una "extensión" del navegador. Sin embargo, la comunidad WebAssembly está realizando esfuerzos para permitir la ejecución de código Wasm fuera de los navegadores.

== ¿Por qué utilizar WebAssembly?

Los usuarios pueden escribir políticas de Kubernetes utilizando su lenguaje de programación favorito, siempre que su cadena de herramientas pueda generar binarios Wasm.

Los módulos Wasm son portátiles, una vez construidos pueden ejecutarse en cualquier tipo de arquitectura de procesador y sistema operativo. Por ejemplo, una política desarrollada y construida en Apple Silicon puede ejecutarse en AMD64/Intel64 Linux sin necesidad de conversión.

Los autores de las políticas pueden reutilizar sus conocimientos, herramientas y buenas prácticas. Las políticas son programas "tradicionales" que pueden tener bloques reutilizables (bibliotecas normales). Puede probarlos e integrarlos en los flujos de trabajo actuales de CI y CD.

== Distribución de políticas

Puede servir las políticas de {short-project-name} utilizando un servidor web estándar o, mejor aún, puede publicarlas en un registro compatible con OCI como OCIhttps://github.com/opencontainers/artifacts[artefactos].

ifeval::["{build-type}" == "community"]

== Neutralidad de los proveedores

{short-project-name} es un proyecto \link:https://contribute.cncf.io/maintainers/community/vendor-neutrality/[vendor neutral] según la definición del CNCF.

endif::[]
