= Cluster-Zugang
:page-languages: [en, ja, ko, zh]
:revdate: 2025-09-15
:page-revdate: {revdate}

Die Datei admin kubeconfig, die auf `+/etc/rancher/k3s/k3s.yaml+` gespeichert ist, kann für den Zugriff auf den Kubernetes-Cluster verwendet werden. Diese Datei gewährt den Zugriff als Benutzer `+system:admin+` und als Gruppe `+system:masters+`, die von Kubernetes so kodiert sind, dass sie uneingeschränkten Zugriff auf alle Ressourcen innerhalb des Clusters haben.

Der mit K3s gelieferte Befehl `+kubectl+` ist so konfiguriert, dass er standardmäßig Konfigurationen aus diesem Pfad lädt. Wenn Sie Upstream-Kubernetes-Kommandozeilen-Tools wie kubectl oder Helm installiert haben, müssen Sie diese mit dem richtigen kubeconfig-Pfad konfigurieren. Dazu kann entweder die Umgebungsvariable `+KUBECONFIG+` exportiert oder das Kommandozeilenflag `+--kubeconfig+` aufgerufen werden. Einzelheiten finden Sie in den nachstehenden Beispielen.

* Exportieren Sie die Umgebungsvariable KUBECONFIG:
+
[,bash]
----
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
kubectl get pods --all-namespaces
helm ls --all-namespaces
----

* Geben Sie den Speicherort der kubeconfig-Datei in dem Befehl an:
[,bash]
----
kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get pods --all-namespaces
helm --kubeconfig /etc/rancher/k3s/k3s.yaml ls --all-namespaces
----

== Zugriff auf den Cluster von außen mit kubectl

Kopieren Sie `+/etc/rancher/k3s/k3s.yaml+` auf Ihren Rechner, der sich außerhalb des Clusters befindet, als `+~/.kube/config+`. Ersetzen Sie dann den Wert des Feldes `+server+` durch die IP oder den Namen Ihres K3s-Servers. `+kubectl+` kann nun Ihren K3s-Cluster verwalten.

[NOTE]
====
K3s aktualisiert bei jedem Start automatisch die Zertifikate in der Admin-Kubeconfig. Wenn Sie eine Kopie dieser Datei erstellen, müssen Sie diese Kopien manuell aktualisieren, um sicherzustellen, dass die Inline-Zertifikate nicht ablaufen.
====
