= FAQ
:page-languages: [en, ja, ko, zh]
:revdate: 2024-09-11
:page-revdate: {revdate}

Die FAQ werden regelmäßig aktualisiert und sollen die Fragen beantworten, die unsere Benutzer am häufigsten zu K3 stellen.

== Ist K3s ein geeigneter Ersatz für Kubernetes?

K3s ist eine CNCF-zertifizierte Kubernetes-Distribution und kann alles, was von einem Standard-Kubernetes-Cluster verlangt wird. Es handelt sich lediglich um eine leichtere Version. Weitere Einzelheiten finden Sie auf der Seite mit den xref:introduction.adoc[Hauptdokumenten].

== Wie kann ich mein eigenes Ingress anstelle von Traefik verwenden?

Starten Sie einfach K3s Server mit `+--disable=traefik+` und stellen Sie Ihren Ingress bereit.

== Unterstützt K3s Windows?

Derzeit unterstützt K3s Windows nicht von Haus aus, aber wir sind offen für diese Idee in der Zukunft.

== Was genau sind Server und Agenten?

Eine Aufschlüsselung der Komponenten, aus denen ein Server und ein Agent bestehen, finden Sie auf der xref:architecture.adoc[Seite Architektur].

== Wie kann ich aus den Quellen bauen?

Bitte beziehen Sie sich auf die K3s https://github.com/k3s-io/k3s/blob/main/BUILDING.md[BUILDING.md] mit Anweisungen.

== Wo sind die K3-Protokolle?

Der Speicherort der K3s-Protokolle hängt davon ab, wie Sie K3s ausführen und welches Betriebssystem der Knoten hat.

* Bei Ausführung über die Befehlszeile werden die Protokolle an stdout und stderr gesendet.
* Wenn es unter openrc läuft, werden die Protokolle unter `+/var/log/k3s.log+` erstellt.
* Wenn sie unter Systemd laufen, werden die Protokolle an Journald gesendet und können mit `+journalctl -u k3s+` eingesehen werden.
* Die Protokolle der Pods finden Sie unter `+/var/log/pods+`.
* Containerd-Logs können unter `+/var/lib/rancher/k3s/agent/containerd/containerd.log+` abgerufen werden.

Sie können ausführlichere Protokolle erstellen, indem Sie beim Starten von K3s das Flag `+--debug+` verwenden (oder `+debug: true+` in der Konfigurationsdatei).

Kubernetes verwendet ein Logging-Framework namens `+klog+`, das eine einzige Logging-Konfiguration für alle Komponenten innerhalb eines Prozesses verwendet.
Da K3s alle Kubernetes-Komponenten innerhalb eines einzigen Prozesses ausführt, ist es nicht möglich, unterschiedliche Protokollebenen oder Ziele für einzelne Kubernetes-Komponenten zu konfigurieren.
Die Verwendung der Komponentenargumente `+-v=<level>+` oder `+--vmodule=<module>=<level>+` wird wahrscheinlich nicht die gewünschte Wirkung haben.

Siehe xref:advanced.adoc#_additional_logging_sources[Zusätzliche Protokollierungsquellen] für noch mehr Protokollierungsoptionen.

== Kann ich K3s in Docker ausführen?

Ja, es gibt mehrere Möglichkeiten, K3s in Docker auszuführen. Siehe xref:advanced.adoc#_running_k3s_in_docker[Erweiterte Optionen] für weitere Einzelheiten.

== Was ist der Unterschied zwischen K3s Server- und Agententoken?

Weitere Informationen zur Verwaltung von K3s Join-Tokens finden Sie in der xref:cli/token.adoc[Dokumentation zum Befehl`+k3s token+` ].

== Wie kompatibel sind die verschiedenen Versionen von K3s?

Im Allgemeinen gilt die https://kubernetes.io/docs/setup/release/version-skew-policy/[Richtlinie] Kubernetes.

Kurz gesagt, Server können neuer sein als Agenten, aber Agenten können nicht neuer sein als Server.

== Ich habe ein Problem, wo kann ich Hilfe bekommen?

Wenn Sie ein Problem mit der Bereitstellung von K3s haben, sollten Sie das tun:

. Prüfen Sie die Seite xref:known-issues.adoc[Bekannte Probleme].
. Vergewissern Sie sich, dass Sie alle xref:installation/requirements.adoc#_operating_systems[zusätzlichen OS-Vorbereitungen] gelöst haben. Führen Sie `+k3s check-config+` aus und vergewissern Sie sich, dass die Prüfung erfolgreich war.
. Suchen Sie in den K3s https://github.com/k3s-io/k3s/issues[Issues] und https://github.com/k3s-io/k3s/discussions[Discussions] nach einem Eintrag, der Ihrem Problem entspricht.
. Treten Sie dem https://slack.rancher.io/[Slack] Rancher K3s-Kanal bei, um Hilfe zu erhalten.
. Reichen Sie einen https://github.com/k3s-io/k3s/issues/new/choose[New Issue] auf K3s Github ein, in dem Sie Ihr Setup und das Problem beschreiben.
