= Quick-Start-Anleitung
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

Dieser Leitfaden hilft Ihnen, schnell einen Cluster mit Standardoptionen zu starten. Stellen Sie sicher, dass Ihre Knoten die xref:installation/requirements.adoc[Anforderungen] erfüllen, bevor Sie fortfahren.

* Auf der Seite xref:installation/installation.adoc[Installation] finden Sie weitere Informationen zur Installation und Konfiguration von K3s.
* Informationen darüber, wie die Komponenten von K3 zusammenarbeiten, finden Sie auf der Seite xref:architecture.adoc[Architektur].
* Wenn Sie Kubernetes noch nicht kennen, finden Sie in den unter https://kubernetes.io/docs/tutorials/kubernetes-basics/[offiziellen Kubernetes-Dokumenten] großartige Tutorials zu den Grundlagen, mit denen alle Cluster-Administratoren vertraut sein sollten.

[IMPORTANT]
====
Sie können jede K3s Prime-Version verwenden, die auf der Prime Artifacts URL für die in diesen Schritten erwähnten Assets aufgeführt ist. Um mehr über die Prime Artifacts URL zu erfahren, lesen Sie unsere https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime-only Dokumentation]. Eine Authentifizierung ist erforderlich. Verwenden Sie Ihre https://scc.suse.com/home[Customer Center (SCC)-] SUSE Zugangsdaten, um sich anzumelden.
====


== Skript installieren

{k3s-product-name} bietet ein Installationsskript, das eine bequeme Möglichkeit darstellt, es als Dienst auf systemd- oder openrc-basierten Systemen zu installieren. Dieses Skript ist unter https://get.k3s.io. verfügbar. Um {k3s-product-name} mit dieser Methode zu installieren, gehen Sie wie folgt vor:

Führen Sie das Installationsprogramm aus, wobei `+INSTALL_K3S_ARTIFACT_URL+` die https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[URL von] und `+INSTALL_K3S_CHANNEL+` ein Veröffentlichungskanal ist, den Sie abonnieren können und der standardmäßig auf `+stable+` eingestellt ist. In diesem Beispiel erhalten Sie mit `+INSTALL_K3S_CHANNEL="latest"+` die neueste Version von {k3s-product-name}.

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_CHANNEL="latest" sh -
----
Wenn Sie eine Version angeben möchten, setzen Sie die Umgebungsvariable `+INSTALL_RKE2_VERSION+`:

[,bash]
----
curl -sfL https://get.k3s.io/ | sudo INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s INSTALL_K3S_VERSION="<VERSION>" sh -
----

Nach der Ausführung dieser Installation:

* Der K3s-Dienst wird so konfiguriert, dass er nach einem Neustart des Knotens oder wenn der Prozess abstürzt oder beendet wird, automatisch neu startet.
* Es werden zusätzliche Dienstprogramme installiert, darunter `+kubectl+`, `+crictl+`, `+ctr+`, `+k3s-killall.sh+`, und `+k3s-uninstall.sh+`
* Eine https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[] kubeconfig-Datei wird auf `+/etc/rancher/k3s/k3s.yaml+` geschrieben und das von {k3s-product-name} installierte kubectl wird sie automatisch verwenden

Eine Ein-Knoten-Server-Installation ist ein voll funktionsfähiger Kubernetes-Cluster, einschließlich aller Komponenten für Datenspeicher, Steuerungsebene, Kubelet und Container-Laufzeit, die zum Hosten von Workload-Pods erforderlich sind. Es ist nicht notwendig, zusätzliche Server- oder Agentenknoten hinzuzufügen, aber Sie können dies tun, um Ihrem Cluster zusätzliche Kapazität oder Redundanz zu verleihen.

Um weitere Agentenknoten zu installieren und dem Cluster hinzuzufügen, führen Sie das Installationsskript mit den Umgebungsvariablen `+K3S_URL+` und `+K3S_TOKEN+` aus. Das folgende Beispiel zeigt, wie man einem Agenten beitritt:

[,bash]
----
curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken sh -
----

Wenn Sie den Parameter `+K3S_URL+` setzen, konfiguriert das Installationsprogramm K3s als Agent und nicht als Server. Der K3s-Agent registriert sich bei dem K3s-Server, der die angegebene URL abhört. Der für `+K3S_TOKEN+` zu verwendende Wert ist unter `+/var/lib/rancher/k3s/server/node-token+` auf Ihrem Serverknoten gespeichert.

[NOTE]
====
Jeder Rechner muss einen eindeutigen Hostnamen haben. Wenn Ihre Rechner keine eindeutigen Hostnamen haben, übergeben Sie die Umgebungsvariable `+K3S_NODE_NAME+` und geben Sie einen Wert mit einem gültigen und eindeutigen Hostnamen für jeden Knoten an.
====


Wenn Sie an mehreren Serverknoten interessiert sind, finden Sie weitere Informationen auf den Seiten xref:datastore/ha-embedded.adoc[Hochverfügbarkeit mit eingebettetem etcd] und xref:datastore/ha.adoc[Hochverfügbarkeit mit externer DB].
