include::partial$variables.adoc[]

= Divulgação de segurança
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Pesquisadores de segurança investigativos trabalham com a equipe do {project-name} para identificar vulnerabilidades usando protocolos de divulgação responsável.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["security", "disclosure"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "kubernetes", "security", "disclosure"]
:sidebar_label: Divulgação de segurança
:sidebar_position: 80
:current-version: {page-origin-branch}

A equipe do {project-name} aprecia o trabalho investigativo sobre vulnerabilidades de segurança realizado por pesquisadores de segurança bem-intencionados e éticos. O {short-project-name}segue a prática da [divulgação responsável] (https://en.wikipedia.org/wiki/Responsible_disclosure) para proteger melhor a base de usuários do {short-project-name} do impacto dos problemas de segurança. No lado do{short-project-name}, isso significa:

* {short-project-name} responde a incidentes de segurança com prioridade.
* {short-project-name} lança correções para os problemas assim que possível, priorizando-os de acordo com o risco.
* {short-project-name} sempre informa a comunidade de forma transparente sobre qualquer incidente que a afete.

Se você encontrou uma vulnerabilidade de segurança em {short-project-name}, a maneira mais fácil de relatar uma vulnerabilidade é por meio do sitehttps://github.com/kubewarden/community/security/advisories[guia Segurança no GitHub]. Esse mecanismo permite que os mantenedores se comuniquem de forma privada com você, e você não precisa criptografar suas mensagens.

Como alternativa, você pode divulgá-lo de forma responsável enviando um e-mail paraxref:mailto:cncf-kubewarden-maintainers@lists.cncf.io.adoc[cncf-kubewarden-maintainers@lists.cncf.io]em uma mensagem *não criptografada*. Não discuta possíveis vulnerabilidades em público sem antes validar conosco.

Você também pode vir conversar em nossahttps://kubernetes.slack.com/archives/C03L52JRAFM[sala de slack] no servidor Slack do Kubernetes.

Ao receber a equipe de segurança:

* Analisa o relatório, verifica a vulnerabilidade e responde com confirmação e/ou solicitações de informações adicionais.
* Depois de solucionar o bug de segurança relatado, o site {short-project-name} notifica o pesquisador, que pode, opcionalmente, divulgá-lo publicamente.

Consulte https://github.com/kubewarden/community[repositório da comunidade] para saber mais sobre a Política de Segurança e Governança do projeto.
