include::partial$variables.adoc[]
= Glossário
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Explore os principais recursos e configurações relacionados às políticas do {project-name} em ambientes Kubernetes para obter mais informações.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["glossary"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "glossary"]
:sidebar_label: Glossário
:sidebar_position: 90
:current-version: {page-origin-branch}

== A

=== Política de admissão

Um recurso que abrange todo o namespace. A política processa somente as solicitações que têm como alvo o namespace no qual a AdmissionPolicy está definida.

== C

=== ClusterAdmissionPolicy

Uma <<_admissionpolicy,AdmissionPolicy>> que tem como alvo os recursos de todo o cluster.

=== ClusterReport

Um <<_report,Report>> e um ClusterReport armazenam os resultados das varreduras de políticas. Qual deles é usado depende do escopo do recurso.

== K

=== kwctl

Uma ferramenta CLI para gerar e testar arquivos YAML do Kubernetes para implantação de políticas.

== M

=== MutatingWebhookConfiguration

Umhttps://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[recurso do Kubernetes]criado pelo controlador {short-project-name} para permitir que o Kubernetes saiba para onde enviar um `+AdmissionReview+`.
Em outras palavras, é assim que um controlador {short-project-name} informa ao Kubernetes onde encontrar uma política de mutação de recursos.

== P

=== Relatório

Um Report e um <<_clusterreport,ClusterReport>> armazenam os resultados das varreduras de políticas. Qual deles é usado depende do escopo do recurso.

[#_policy_server]
=== PolicyServer

Um PolicyServer valida as solicitações de entrada executando as políticas do {short-project-name} em relação às solicitações.

== V

=== ValidatingWebhookConfiguration

Umhttps://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[recurso do Kubernetes]criado pelo controlador {short-project-name} para permitir que o Kubernetes saiba para onde enviar um `+AdmissionReview+`.
Em outras palavras, é assim que o {short-project-name} informa ao Kubernetes onde encontrar uma política de validação de recursos.

== W

=== waPC

Chamadas de procedimento do WebAssembly. https://wapc.io.

=== WASI

Interface do sistema WebAssembly. https://wasi.dev.

=== Wasm

Um formato de instrução binária para uma máquina virtual baseada em pilha. Projetado para implantação na Web. https://webassembly.org.

=== Hora do banho

Um tempo de execução para o WebAssembly. https://wasmtime.dev.
