include::partial$variables.adoc[]

= Scanner d'audit
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Vérifiez l'état de conformité de vos clusters à l'aide de la fonction Audit Scanner du site {project-name}, afin de vous assurer qu'ils sont correctement configurés.
:doc-persona: ["kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-topic: ["howto", "audit-scanner-installation"]
:doc-type: ["howto"]
:keywords: ["{project-name}", " kubewarden ", " kubernetes ", " audit scanner "].
:sidebar_label: Scanner d'audit
:sidebar_position: 70
:current-version: {page-origin-branch}

À partir de la version `v1.7.0`, {project-name} dispose d'une nouvelle fonctionnalité appelée "Audit Scanner". Un nouveau composant, appelé "audit-scanner", vérifie en permanence les ressources déclarées dans le cluster, en signalant celles qui ne respectent pas les politiques déployées sur {project-name} et en enregistrant ces résultats dans un rapport spécifique intitulé Custom Resources.

Les politiques évoluent au fil du temps : vous déployez de nouvelles politiques et mettez à jour les politiques existantes. La version et les paramètres de configuration changent. Cela peut conduire à des situations où les ressources déjà présentes dans le cluster ne sont plus conformes.

La fonction d'analyseur d'audit fournit aux administrateurs Kubernetes un outil pour vérifier de manière cohérente l'état de conformité de leurs clusters.

Le scanner d'audit peut enregistrer ses résultats soit dans des définitions de ressources personnalisées (CRD) OpenReports delink:https://openreports.io[openreports.io](paramètre par défaut depuis la version 1.33), soit dans des PolicyReports duKuberneteslink:https://github.com/kubernetes-sigs/wg-policy-prototypes[groupe de travail sur les politiques](marqués comme dépréciés depuis la version 1.30, non installés ni créés par défaut depuis la version 1.30, dont la suppression est prévue dans une version ultérieure).

== Installation

Le scanner d'audit est disponible depuis {short-project-name} `v1.7.0`.
Par conséquent, assurez-vous que vous installez la carte Helm avec la version de l'application`v1.7.0` ou une version plus récente.

. Installez la carte `kubewarden-crds` Helm. La carte installe par défaut les CRDs`PolicyReport` nécessaires.
+
[subs="+attributes",console]
----
helm install kubewarden-crds kubewarden/kubewarden-crds
----
+

[NOTE]
====
Avec Kubewarden 1.33, la fonction Audit Scanner enregistre par défaut les rapports dans des CRD OpenReports à partir de [openreports.io] (https://openreports.io).

Les CRDslink:https://htmlpreview.github.io/?https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/045372e558b896695b2daae92e8c7a04d4d40282/policy-report/docs/index.html[PolicyReport]du groupe de travail K8s Policy ne sont pas installés par défaut, sont marqués comme dépréciés et seront supprimés dans une prochaine version.

Les utilisateurs qui souhaitent continuer à utiliser les PolicyReports dépréciés, c'est-à-dire le comportement antérieur à la version 1.33, doivent :- Changer la valeur du diagramme de Helm `kubewarden-crds` de `.Values.install.installPolicyReportCRDs` à `true`- Changer la valeur du diagramme de Helm `kubewarden-controller` de `.Values.auditScanner.reportCRDsKind` de `openreports` à `policyreport`.
====
+
[CAUTION]
====
Pour stocker les résultats des rapports de stratégie, vous devez disposer des définitions de ressources personnalisées (CRD) PolicyReport. Si les CRD PolicyReport nécessaires se trouvent déjà dans le cluster, vous ne pouvez pas les installer à l'aide de la carte kubewarden-crds. Dans ce cas, vous pouvez désactiver l'installation des CRD d'OpenReport en réglant `installOpenReportCRDs` sur`false` dans le tableau (ou `installPolicyReportCRDs` sur `false` si vous utilisez les PolicyReports obsolètes).
Cela signifie que la pile Kubewarden ne gérera pas ces CRD, et que la responsabilité en incombe aux administrateurs.

Pour plus d'informations sur les CRD, consultez le sitelink:https://github.com/kubernetes-sigs/wg-policy-prototypes[du groupe de travail sur les politiques (].

====


. Installez la carte `kubewarden-controller` Helm.
+
[subs="+attributes",console]
----
helm install kubewarden-controller kubewarden/kubewarden-controller
----
+

[NOTE]
====
Le scanner d'audit est activé par défaut. Pour le désactiver, réglez le paramètre`auditScanner.enable=false`.
====
+
[NOTE]
====
Si vous souhaitez que le Scanner d'audits enregistre ses rapports dans les CRD PolicyReports (marqués comme dépréciés) au lieu des CRD OpenReports par défaut, définissez `auditScanner.reportCRDsKind="policyreport"`.
====

Pour plus d'informations sur l'installation de {short-project-name}, voir lexref:quick-start.adoc[guide de démarrage rapide.]

Par défaut, le scanner d'audit est implémenté sous la forme d'un Cronjobhttps://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs[] déclenché toutes les 60 minutes. Vous pouvez ajuster ce paramètre et d'autres paramètres de l'analyseur d'audit en modifiant le graphique kubewarden-controllerhttps://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/values.yaml[values.yaml].

Voir xref:explanations/audit-scanner/audit-scanner.adoc[ici] plus d'informations sur le scanner d'audit.

=== Interface utilisateur du rapporteur de politique (facultatif)

La carte `kubewarden-controller` est accompagnée d'une sous-carte duhttps://kyverno.github.io/policy-reporter[Policy Reporter]. Il est désactivé par défaut et activé par le paramètre `auditScanner.policyReporter=true`. Les valeurs du sous-graphe Policy Reporter se trouvent sous la clé `policyReporter` des valeurs`kubewarden-controller`.

Ceci n'installe qu'une partie du diagramme en amont du rapporteur de politiques, l'interface utilisateur, qui fournit une visualisation des rapports de politiques et des rapports de politiques de grappes dans une grappe. Voir xref:explanations/audit-scanner/audit-scanner.adoc[Audit Scanner]pour plus d'informations sur l'interface utilisateur de Policy Reporter.

Par défaut, l'interface utilisateur de Policy Reporter n'est exposée que sous la forme d'un service ClusterIP portant le nom `kubewarden-controller-ui` dans l'espace de noms d'installation de

`kubewarden-controller` a été installé.

==== Entrée

Les utilisateurs peuvent fournir leur propre configuration d'entrée ou activer une entrée via la configuration de la sous-cartehttps://github.com/kyverno/policy-reporter/blob/policy-reporter-2.19.4/charts/policy-reporter/charts/ui/values.yaml#L172-L189[ici.]

Voir cet exemple de configuration Ingress via le sous-graphe :

[subs="+attributes",yaml]
----
auditScanner:
  policyReporter: true
policy-reporter: # subchart values settings
  ui:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - host: "*.local" # change this to your appropriate domain
          paths:
            - path: /
              pathType: ImplementationSpecific
----

==== Transfert de port

Pour un examen rapide ou un débogage, on peut configurer une redirection de port vers le service avec :

[subs="+attributes",console]
----
kubectl port-forward service/kubewarden-controller-ui 8082:8080 -n kubewarden
----

L'interface utilisateur de Policy Reporter est donc disponible à l'adresse `\http://localhost:8082`.

== Déclenchement de l'exécution manuelle

L'analyseur d'audit est mis en œuvre sous la forme d'un Cronjob qui s'exécute par défaut toutes les 60 minutes. Il est possible de déclencher une exécution manuelle en exécutant la commande suivante :

[subs="+attributes",bash]
----
kubectl create job \
    --namespace kubewarden \
    --from cronjob/audit-scanner \
    audit-scanner-manual-$(date +%Y-%m-%d-%H-%M-%S)
----

Vous pouvez vérifier l'état de la tâche à l'aide de :

[subs="+attributes",console]
----
kubectl get -n kubewarden jobs
----
