include::partial$variables.adoc[]
= Autorités de certification personnalisées
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configurez des autorités de certification personnalisées à utiliser avec les installations {project-name} pour garantir une communication et une authentification sécurisées.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"].
:doc-topic: ["distributing-policies", "custom-certificate-authorities"].
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "custom certificate authorities"]
:sidebar_label: Autorités de certification personnalisées
:sidebar_position: 50
:current-version: {page-origin-branch}

Avec `kwctl` et `policy-server`, vous pouvez tirer des politiques des registres de l'Open Container Initiative (OCI) et des serveurs HTTP.
Vous ne pouvez envoyer des politiques qu'aux registres OCI.
Par défaut, HTTPS est utilisé avec une vérification TLS de l'hôte.

Le magasin de l'autorité de certification (CA) du système est utilisé pour valider la chaîne de confiance des certificats du registre OCI.
Dans une installation standard de {project-name}, `policy-server` utilise le magasin d'AC fourni avec son conteneur Linux.
Côté client, `kwctl` utilise le magasin CA de votre système d'exploitation.

Si vous utilisez lehttps://github.com/kubewarden/kubewarden-controller[contrôleur], vous pouvez configurer le PolicyServer via sesxref:/howtos/policy-servers/01-custom-cas.adoc[champs`spec` ].

[NOTE]
====

Le comportement par défaut de `kwctl` et `policy-server` impose l'utilisation de HTTPS avec des certificats approuvés correspondant au magasin de l'autorité de certification du système.
Vous pouvez interagir avec les registres en utilisant des certificats non fiables ou même sans TLS, en utilisant le paramètre `insecure_sources`.
Il est clair qu'il ne s'agit pas d'un environnement de production.
====


== Le fichier `sources.yaml` 

Vous pouvez régler le comportement push-pull de `kwctl` et `policy-server` à l'aide du fichier `sources.yaml`.

Pour les détails de la référence, consultez la xref:../reference/sources_yaml.adoc[`sources.yaml`] référence.
