include::partial$variables.adoc[]

= Configuration du proxy
:description: Utilisation de proxies avec {project-name}.
:keywords: ["{project-name}", "kubewarden", "kubernetes", "proxy", "proxies"]
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"].
:doc-type: ["howto"]
:doc-topic: ["operator-manual", "proxy"]

Pour `kwctl` et `policy-server`, vous pouvez configurer des proxys HTTP et HTTPS, ainsi qu'exempter des domaines de cette configuration de proxy.

Vous pouvez le faire de deux manières :* En définissant les variables d'environnement `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`(et leurs équivalents en minuscules) pour `kwctl` ou `policy-server`.
  Pour configurer un PolicyServer CR, définissez son tableau `spec.env`.* En fournissant un fichier `sources.yaml` via l'argument `--sources-path`.
  Un fichier `sources.yaml` a la priorité sur les variables d'environnement.
  La consommation de cette configuration via le champ `spec` n'est pas encore exposée dans les CR de PolicyServer.

La mise en place d'une configuration de proxy influence :

* Politique pull, push et pull-and-run depuis et vers le registre du BCI.
* Capacités de l'hôte à partir d'appels contextuels, tels que :
** Registre des conteneurs, comme l'obtention d'un manifeste OCI ou d'un résumé de manifeste.
   Au lieu d'accéder directement au registre OCI, le trafic sera acheminé via les serveurs mandataires configurés.
** Capacités Sigstore, comme la vérification d'une signature sans clé.
   Au lieu d'utiliser les services définis par Sigstore, le trafic sera acheminé via les serveurs mandataires configurés.

== Exemple

Vous pouvez définir les variables d'environnement suivantes pour `kwctl` ou`policy-server` (par l'intermédiaire du PolicyServer `spec.env`) :

[source,bash]
----
HTTP_PROXY="http://proxy.corp:3128"
https_proxy="http://proxy.corp:3129"
NO_PROXY="localhost,.corp"
----

Avec cette configuration :* Le trafic non sécurisé via HTTP, tel que celui en provenance et à destination d'un registre OCI non sécurisé, est acheminé via `\http://proxy.corp:3128`.
  Cela affecte les politiques d'extraction et les politiques appelant des capacités contextuelles qui ont des condensés de manifeste d'image OCI pour les conteneurs dans ce référentiel.* Le trafic chiffré via HTTPS est acheminé via `\https://proxy.corp:3129`.
  Par exemple, il s'agit de tirer et de pousser des politiques vers n'importe quel registre OCI sécurisé, et les capacités contextuelles mentionnées des politiques.* Le trafic vers et depuis localhost ou tout domaine sous `.corp` est exempté des configurations précédentes.


== Le fichier `sources.yaml` 

Pour plus de détails, consultez la xref:/reference/sources_yaml.adoc[`sources.yaml`] référence.