include::partial$variables.adoc[]
= Gestion de {project-name} avec Rancher Fleet
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Gérer les cartes {project-name} Helm en utilisant Rancher Fleet et Kubernetes Custom Resource Definitions (CRDs) pour mettre en œuvre une approche GitOps.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "rancher-fleet"]
:doc-type: ["howto"]
:keywords: ["{project-name}", " kubernetes ", " kubewarden ", " rancher fleet "].
:sidebar_label: Flotte de Rancher
:sidebar_position: 130
:current-version: {page-origin-branch}

Vous pouvez gérer les cartes {project-name} Helm, comme les autres cartes Helm, avec https://fleet.rancher.io/[Fleet] Rancher.
Rancher Fleet utilise les CRD de Kubernetes pour définir une approche GitOps de la gestion des clusters Kubernetes.
Pour ce faire, il définit https://fleet.rancher.io/concepts[Fleet Bundles].

== Installation

Les cartes {short-project-name} sont des cartes standard, elles dépendent transitivement les unes des autres :

`kubewarden-crds` ← `kubewarden-controller` ← `kubewarden-defaults`

Voir la xref:/quick-start.adoc[documentation de démarrage rapide]pour plus d'informations.

Avec Rancher Fleet, vous pouvez coder les dépendances des graphiques en utilisant`dependsOn` dans le fichier https://fleet.rancher.io/ref-fleet-yaml[`fleet.yaml`] dans le fichier

Des erreurs transitoires peuvent apparaître jusqu'à ce que les graphiques soient prêts :

[subs="+attributes",console]
----
ErrApplied(1) [Cluster fleet-local/local: dependent bundle(s) are not ready:
[kubewarden-example-helm-kubewarden-controller]]
----

Ces erreurs ne signifient pas qu'il y a un problème, et une fois que le déploiement des cartes est terminé, elles n'apparaissent plus.

== Suppression

[CAUTION]
====

Lors de la suppression de la GitRepo, les 3 graphiques {short-project-name} sont supprimés en même temps.
Cela signifie que la carte `kubewarden-crds` est supprimée.

{short-project-name} utilise un job de hook de helm pré-suppression dans `kubewarden-controller` chart qui supprime le serveur de politique par défaut.
Ce crochet de pré-suppression est nécessaire pour vider les webhooks des politiques avant de supprimer le PolicyServer.
C'est le cas pour tous les moteurs de politiques.
Si ce n'est pas le cas, le cluster peut avoir des webhooks pour des politiques qui n'existent plus, rejetant ainsi tout et se trouvant dans un état d'échec.

La suppression de la GitRepo, et donc du graphique `kubewarden-crds`, en même temps que celle du graphique `kubewarden-controller` fait échouer le travail de crochet de pré-suppression.
Cela signifie que l'élimination est incomplète et qu'il reste des "débris" dans la grappe.
====


La désinstallation automatique des CRD n'est normalement prise en charge par aucun outil, et Rancher Fleet ne fait pas exception à la règle.

Pour effectuer une suppression correcte, assurez-vous d'abord de supprimer l'offre groupée pour `kubewarden-defaults` du cluster.
Pour ce faire, il convient d'enregistrer ces modifications dans le référentiel contenant la configuration Fleet et d'attendre qu'elles soient appliquées.
Ensuite, supprimez `kubewarden-controller` de la même manière, et enfin, supprimez `kubewarden-crds`.

Une autre option consiste à ajouter 2 GitRepos, l'un pour les CRD uniquement, et l'autre pour le reste des graphiques {short-project-name}.
Cela vous permet de supprimer les graphiques {short-project-name} en premier et les CRD {short-project-name} en dernier.

== Exemple

Pour un exemple de définitions de bundle de flotte, voirhttps://github.com/kubewarden/fleet-example[.com/kubewarden/fleet-example.] github
