= ランチャーのOS管理
:revdate: 2026-01-16
:page-revdate: {revdate}

{elemental-product-name} は、Kubernetesによる一元的で完全なクラウドネイティブOS管理を可能にするソフトウェアスタックである。

xref:release-notes.adoc[**最新リリース：v1.8.0**]

{elemental-product-name} スタックは、SLEマイクロの上にある一握りのパッケージで構成されている：

* *elemental-toolkit*- コンテナによる OS 管理を可能にする OS ユーティリティ一式。dracutモジュール、ブートローダーの設定、cloud-initスタイルの設定サービスなどが含まれる。
* *elemental-operator*- Rancher Manager に接続し、MachineRegistration と MachineInventory CRD を処理する。
* *elemental-register*- machineRegistrations経由でマシンを登録し、elemental-cli経由でインストールする。
* *elemental-cli*- elemental-toolkit ベースの派生ツールをインストールします。基本的には、私たちのA/Bインストールとアップグレードシステムに基づいたインストーラーです。
* *rancher-system-agent*- インストールされたシステム上で実行され、Rancher Managerからシステムに何をインストールして実行するかの指示（"計画"）を得る。

クラスターノードOSは、{elemental_cli_name} を通してコンテナイメージによってビルドされ、メンテナンスされる。https://www.rancher.com/products/rancher[]Rancher用の{elemental_ui_url}[{elemental_ui_name}]、または{elemental_cli_url}[{elemental_cli_name}]を使って新しいホストにインストールできる。

{elemental_operator_url}[{elemental_operator_name}] と{ranchersystemagent_url}[{ranchersystemagent_name}] により、Rancher Manager はノードへの OS のインストールと管理から、新しい K3 や RKE2 クラスタのプロビジョニングまで、{elemental-product-name} クラスタを一元的に制御することができます。

== {elemental-product-name} x86-64ハードウェア上

{elemental-product-name} は、Rancher v2.7.0からx86-64で生産準備が整い、完全にサポートされています。

== {elemental-product-name} ARMハードウェア上

ARM (aarch64)は開発段階で機能的である。ARMは現在、k3s 1.24.8（またはそれ以降）を搭載したRaspberry Pi 4 Model Bでのみテストされています。フィードバックは大歓迎だ。

== {elemental-product-name} 他のハードウェアで

{elemental-product-name} は現在「エッジ」シナリオをターゲットにしているため、他のハードウェアはサポートしていない。市場の進展に応じて再評価する。

== 試してみる？

お好みの方法で{elemental-product-name} クラスタを立ち上げ、実行する。

* Rancher managerxref:quickstarts/quickstart-ui.adoc[{elemental-product-name} プラグイン]
* xref:quickstarts/quickstart-cli.adoc[{elemental-product-name} CLI]

[NOTE]
.次はどうする？
====
もっと詳しく知りたい？xref:rancher-os-management/architecture/architecture.adoc[建築]セクションをご覧になるか、{elemental_slack_url}[{elemental_slack_name}]までご連絡ください。
====

