= k8s Gestión personalizada de secretos
:revdate: 2025-10-27
:page-revdate: {revdate}

== Visión general

El agente de SUSE Observability permite especificar el nombre de un secreto personalizado que contiene la clave de API y el token de autorización de clúster. Esta función es útil para los usuarios que deseen gestionar sus propios secretos y evitar la creación automática de secretos por parte del gráfico de Helm.

NOTE: *Había un método anterior para especificar esto que ahora está obsoleto, véase el xref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[método obsoleto].*

== El cuadro de mando

=== Opciones de configuración

* `global.apiKey.fromSecret`: Especifique un nombre secreto preexistente que resida en el mismo espacio de nombres y que contenga un campo `STS_API_KEY` que contenga la clave api.
* `global.clusterAgentAuthToken.fromSecret`: Especifique un nombre secreto preexistente que resida en el mismo espacio de nombres y que contenga un campo `STS_CLUSTER_AGENT_AUTH_TOKEN` con un token para proteger las conexiones entre el clúster y los agentes de nodo.

=== Descripción del comportamiento

* *Creación automática de secretos*: Por defecto, el gráfico requiere que se especifique un `stackstate.apiKey` y creará un secreto por sí mismo. La dirección `STS_CLUSTER_AGENT_AUTH_TOKEN` se genera automáticamente.
* *Gestión de secretos personalizada*: Al sobrescribir los campos `fromSecret`, la clave api y el token de autenticación del clúster se tomarán de esos secretos.
* *Omisión implícita*: Al especificar que desea gestionar sus propios secretos, el gráfico ignorará los valores de `stackstate.apiKey` y `stackstate.cluster.authToken`.

== Cómo utilizar en values.yaml

. *Uso de la creación automática de secretos (por defecto)*:
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *Gestión de secretos propios*:
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
