include::partial$variables.adoc[]
= Políticas en bruto
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Conozca las políticas sin procesar que evalúan documentos JSON arbitrarios, y vea ejemplos de implementación de políticas en Rust.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["writing-policies", "rust", "raw-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "raw policies", "rust"]
:sidebar_label: Políticas en bruto
:current-version: {page-origin-branch}

Las políticas raw son políticas que pueden evaluar documentos JSON arbitrarios.
Para más información sobre las pólizas xref:howtos/raw-policies.adoc[brutas], consulte la página de xref:howtos/raw-policies.adoc[pólizas brutas].

== Ejemplos

Los siguientes ejemplos deberían resultarle familiares si ha completado la página de xref:tutorials/writing-policies/rust/05-mutation-policy.adoc[validación] de este tutorial.

[NOTE]
====
Recuerde marcar la política como `raw` utilizando el campo `policyType` en la configuración de `metadata.yml`.
Para más información, consulte la especificación de xref:tutorials/writing-policies/metadata.adoc[metadatos].
====


=== Validación

Escribamos una política que acepte una solicitud con el siguiente formato:

[subs="+attributes",json]
----
{
  "request": {
    "user": "alice",
    "action": "delete",
    "resource": "products"
  }
}
----

y lo valida:

* `user` está en la lista de usuarios válidos
* `action` está en la lista de acciones válidas
* `resource` está en la lista de recursos válidos

Comience por andamiar la política utilizando la óxido https://github.com/kubewarden/rust-policy-template[plantilla de política de].

En primer lugar, definimos los tipos que representan la carga útil de la solicitud.
Vamos a declarar un tipo personalizado `RawValidationRequest` que contiene el `Request` y el `Settings`, en lugar de utilizar el tipo `ValidationRequest` que es proporcionado por el SDK:

[subs="+attributes",rust]
----
/// RawValidationRequest represents the request that is sent to the validate function by the Policy Server.
#[derive(Deserialize)]
pub(crate) struct RawValidationRequest {
    pub(crate) request: Request,
    pub(crate) settings: Settings,
}

#[derive(Serialize, Deserialize)]
/// Request represents the payload of the request.
pub(crate) struct Request {
    pub(crate) user: String,
    pub(crate) resource: String,
    pub(crate) action: String,
}
----

A continuación, tenemos que definir el tipo `Settings` e implementar el rasgo `Validatable`:

[subs="+attributes",rust]
----
/// Settings represents the settings of the policy.
#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(default, rename_all = "camelCase")]
pub(crate) struct Settings {
    pub(crate) valid_users: Vec<String>,
    pub(crate) valid_actions: Vec<String>,
    pub(crate) valid_resources: Vec<String>,
}

impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        info!(LOG_DRAIN, "starting settings validation");

        if self.valid_users.is_empty() {
            return Err("validUsers cannot be empty".to_string());
        }

        if self.valid_actions.is_empty() {
            return Err("validActions cannot be empty".to_string());
        }

        if self.valid_resources.is_empty() {
            return Err("validResources cannot be empty".to_string());
        }

        Ok(())
    }
}
----

Por último, definimos la función `validate`:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: RawValidationRequest =
        if let Ok(validation_request) = serde_json::from_slice(payload) {
            validation_request
        } else {
            return kubewarden::reject_request(
                Some("cannot unmarshal request".to_string()),
                None,
                None,
                None,
            );
        };

    info!(LOG_DRAIN, "starting validation");

    let request = validation_request.request;
    let settings = validation_request.settings;

    if settings.valid_users.contains(&request.user)
        && settings.valid_actions.contains(&request.action)
        && settings.valid_resources.contains(&request.resource)
    {
        info!(LOG_DRAIN, "accepting resource");
        kubewarden::accept_request()
    } else {
        kubewarden::reject_request(
            Some("this request is not accepted".to_string()),
            None,
            None,
            None,
        )
    }
}
----

=== Mutación

Modifiquemos el ejemplo anterior para mutar la solicitud en lugar de rechazarla.
En este caso, la configuración contendrá `defaultUser`, `defaultAction` y `defaultRequest` que se utilizarán para mutar la solicitud si el usuario, la acción o el recurso no son válidos.

Tenemos que actualizar el tipo `Settings` con los nuevos campos:

[subs="+attributes",rust]
----
/// Settings represents the settings of the policy.
#[derive(Serialize, Deserialize, Default, Debug)]
#[serde(default, rename_all = "camelCase")]
pub(crate) struct Settings {
    pub(crate) valid_users: Vec<String>,
    pub(crate) valid_actions: Vec<String>,
    pub(crate) valid_resources: Vec<String>,
    pub(crate) default_user: String,
    pub(crate) default_action: String,
    pub(crate) default_resource: String,
}

impl kubewarden::settings::Validatable for Settings {
    fn validate(&self) -> Result<(), String> {
        info!(LOG_DRAIN, "starting settings validation");

        if self.valid_users.is_empty() {
            return Err("validUsers cannot be empty".to_string());
        }

        if self.valid_actions.is_empty() {
            return Err("validActions cannot be empty".to_string());
        }

        if self.valid_resources.is_empty() {
            return Err("validResources cannot be empty".to_string());
        }

        if self.default_user.is_empty() {
            return Err("defaultUser cannot be empty".to_string());
        }

        if self.default_action.is_empty() {
            return Err("defaultAction cannot be empty".to_string());
        }

        if self.default_resource.is_empty() {
            return Err("defaultResource cannot be empty".to_string());
        }

        Ok(())
    }
}
----

y la función `validate` para introducir la mutación:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: RawValidationRequest =
        if let Ok(validation_request) = serde_json::from_slice(payload) {
            validation_request
        } else {
            return kubewarden::reject_request(
                Some("cannot unmarshal request".to_string()),
                None,
                None,
                None,
            );
        };

    info!(LOG_DRAIN, "starting validation");

    let request = validation_request.request;
    let settings = validation_request.settings;

    if settings.valid_users.contains(&request.user)
        && settings.valid_actions.contains(&request.action)
        && settings.valid_resources.contains(&request.resource)
    {
        info!(LOG_DRAIN, "accepting request");
        return kubewarden::accept_request();
    }

    info!(LOG_DRAIN, "mutating request");
    let mut request = request;

    if !settings.valid_users.contains(&request.user) {
        request.user = settings.default_user;
    }

    if !settings.valid_actions.contains(&request.action) {
        request.action = settings.default_action;
    }

    if !settings.valid_resources.contains(&request.resource) {
        request.resource = settings.default_resource;
    }

    let mutated_request = serde_json::to_value(request)?;
    kubewarden::mutate_request(mutated_request)
}
----
