= Depurar a sincronização de integridade
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

A xref:/setup/cli/cli-sts.adoc[CLI do SUSE Observability] pode ser usada para solucionar problemas de sincronização de integridade e corrigir problemas que possam impedir que os dados de integridade sejam corretamente ingeridos e exibidos no SUSE Observability. Esta página descreve as etapas gerais de solução de problemas a serem seguidas ao depurar uma sincronização de integridade, bem como os comandos da CLI usados e uma descrição das mensagens de erro retornadas.

== Etapas gerais de solução de problemas

Ao depurar a sincronização de integridade, há algumas etapas comuns de verificação que podem ser realizadas, independentemente do problema específico:

. xref:/configure/health/debug-health-sync.adoc#_list_streams[Verifique se o fluxo existe].
. Se estiver usando subfluxos, xref:/configure/health/debug-health-sync.adoc#_list_sub_streams[verifique se o subfluxo existe]. A resposta também mostrará o número de estados de verificação no subfluxo. Isso permite que você saiba se os dados estão sendo ingeridos e processados.
. Investigue mais:
 ** *Stream present (Presença de* fluxo) - xref:/configure/health/debug-health-sync.adoc#_show_stream_status[Verifique o status do fluxo], o que mostrará a latência métrica do fluxo e quaisquer xref:/configure/health/debug-health-sync.adoc#_error_messages[erros].
 ** *Fluxos/subfluxos presentes, mas não há estados de verificação* - Confirme se a carga útil enviada à API do receptor está de acordo com a xref:/configure/health/send-health-data/send-health-data.adoc[especificação da carga útil de saúde].
 ** *Nenhum fluxo/subfluxo está presente* - Use o comando CLI abaixo para verificar se os dados de integridade enviados à API do receptor estão chegando ao SUSE Observability:

[,sh]
----
$ sts topic describe --name sts_health_sync
----

== Problemas comuns

=== Estado de verificação não visível no componente

Pode haver dois motivos para um estado de verificação não ser exibido em um componente no SUSE Observability:

* O estado de verificação de integridade não foi criado. Siga as xref:/configure/health/debug-health-sync.adoc#_general_troubleshooting_steps[etapas gerais de solução de problemas] para confirmar que o fluxo/subfluxo foi criado e que os dados estão chegando ao SUSE Observability.
* O estado de verificação de integridade foi criado, mas seu endereço `+topologyElementIdentifier+` não corresponde a nenhum `+identifiers+` da topologia do SUSE Observability. Use o comando da CLI xref:/configure/health/debug-health-sync.adoc#_show_substream_status[show substream status] para verificar se há algum `+Check states with identifier which has no matching topology element+`.

=== Estado de verificação lento para atualização no SUSE Observability

O principal motivo para isso é que a latência da sincronização de integridade é maior do que o esperado. Use o comando da CLI xref:/configure/health/debug-health-sync.adoc#_show_stream_status[show stream status] para confirmar a latência do fluxo, bem como a taxa de transferência de mensagens e operações de verificação específicas. Pode ser necessário ajustar os dados enviados para a sincronização de saúde ou a frequência com que os dados são enviados.

== Comandos úteis da CLI

=== Fluxos de listagem

Retorna uma lista de todos os fluxos de integridade sincronizados atuais e o número de subfluxos incluídos em cada um.

[,sh]
----
$ sts health list
STREAM URN                                              | STREAM CONSISTENCY MODEL | SUB STREAM COUNT
urn:health:sourceId:streamId                            | REPEAT_SNAPSHOTS         | 1
----

=== Listar subfluxos

Retorna uma lista de todos os subfluxos de um determinado URN de fluxo, juntamente com o número de estados de verificação em cada um deles.

[,sh]
----
$ sts health list -u urn:health:sourceId:streamId
SUB STREAM ID  | CHECK STATE COUNT
subStreamId1   | 1
subStreamId2   | 1
----

=== Mostrar status do fluxo

O comando de status do fluxo retorna as métricas agregadas de latência e taxa de transferência do fluxo. Isso é útil ao depurar o motivo pelo qual uma verificação de integridade leva muito tempo para chegar aos elementos de topologia esperados. Isso ajudará a diagnosticar se a frequência dos dados enviados ao SUSE Observability deve ser ajustada. A saída inclui uma seção `+Errors for non-existing sub streams:+`, pois alguns erros são relevantes apenas quando não foi possível criar um subfluxo, por exemplo, `+StreamMissingSubStream+`. Os erros de subfluxo podem ser qualquer uma das xref:/configure/health/debug-health-sync.adoc#_error_messages[mensagens de erro] documentadas.

[,sh]
----
$ sts health status -u urn:health:sourceId:streamId
----

=== Mostrar status do subfluxo

O status do subfluxo fornece informações úteis para verificar se o SUSE Observability pode vincular estados de verificação enviados de um sistema externo a elementos de topologia existentes. Essas informações são úteis para depurar por que uma verificação específica não está visível no elemento de topologia esperado.

[,sh]
----
$ sts health status -u urn:health:sourceId:streamId -sub-stream-urn subStreamId3
----

[NOTE]
====
Um status de subfluxo mostrará os metadados relacionados ao modelo de consistência:

* *Repetição de instantâneos* - Mostra o intervalo de repetição e a expiração
* *Incrementos transacionais* - Mostra o deslocamento do ponto de verificação e o índice do lote do ponto de verificação
====


O status do subfluxo pode ser expandido para incluir detalhes de estados de verificação combinados e não combinados usando o argumento de linha de comando `+-t+`. Isso é útil para identificar quaisquer estados de integridade que não estejam vinculados a um elemento de topologia.
No exemplo abaixo, `+checkStateId2+` está listado em `+Check states with identifier which has no matching topology element+`. Isso significa que não foi possível fazer a correspondência entre o estado de verificação e um elemento de topologia com o identificador `+server-2+`.

[,sh]
----
$ sts health status -u urn:health:sourceId:streamId -sub-stream-urn subStreamId3 -t
----

=== Excluir um fluxo de saúde

A funcionalidade de fluxo `+delete+` é útil ao configurar uma sincronização de integridade no SUSE Observability. Você pode usá-lo para fazer experimentos, excluir os dados e começar tudo de novo. Você também pode excluir um fluxo e descartar seus dados quando tiver certeza de que não deseja continuar a usá-lo.

[,sh]
----
$ sts health delete -u urn:health:sourceId:streamId
----

=== Limpar erros de fluxo de saúde

A opção `+clear-errors+` remove todos os erros de um fluxo de integridade. Isso é útil ao configurar uma sincronização de integridade no SUSE Observability ou, no caso do modelo de consistência `+TRANSACTIONAL_INCREMENTS+`, quando alguns erros não podem ser removidos organicamente. Por exemplo, uma solicitação para excluir um estado de verificação pode gerar um erro se o estado de verificação não for conhecido pelo SUSE Observability. A única maneira de suprimir esse erro seria usar o comando `+clear-errors+`.

[,sh]
----
$ sts health clear-error -u urn:health:sourceId:streamId
----

== Mensagens de erro

[NOTE]
====
Os erros serão fechados quando o problema descrito tiver sido corrigido.

Por exemplo, um `+SubStreamStopWithoutStart+` será fechado quando a sincronização de integridade observar uma mensagem de início de instantâneo seguida de uma mensagem de parada de instantâneo.
====


|===
| Erro | Descrição

| *StreamMissingSubStream*
| Gerada quando a sincronização de integridade recebe mensagens sem uma mensagem de configuração de fluxo anterior como `+start_snapshot+` ou `+expiry+`.

| *StreamConsistencyModelMismatch*
| Gerado quando é recebida uma mensagem que pertence a um modelo de consistência diferente daquele especificado quando o fluxo foi criado.

| *StreamMissingSubStream*
| Gerado quando a sincronização de integridade recebe mensagens com um instantâneo de início anterior em vigor.

| *SubStreamRepeatIntervalTooHigh*
| Gerado quando a sincronização de integridade recebe um `+repeat_interval_s+` maior do que o máximo configurado de 30 minutos.

| *SubStreamStartWithoutStop*
| Gerada quando a sincronização de integridade recebe uma segunda mensagem para abrir um instantâneo quando um instantâneo anterior ainda estava aberto.

| *SubStreamCheckStateOutsideSnapshot*
| Gerado quando a sincronização de integridade recebe estados de verificação externos sem abrir previamente um instantâneo.

| *SubStreamStopWithoutStart*
| Gerada quando a sincronização de integridade recebe uma mensagem de parada de instantâneo sem ter iniciado um instantâneo.

| *SubStreamMissingStop*
| Gerada quando a sincronização de integridade não recebe um instantâneo de parada após um período de tempo limite de duas vezes o `+repeat_interval_s+` estabelecido na mensagem de início de instantâneo. Nesse caso, será aplicado um instantâneo de parada automática.

| *SubStreamExpired*
| Gerada quando a sincronização de integridade para de receber dados em um determinado subfluxo por mais tempo do que o configurado `+expiry_interval_s+`. Nesse caso, o subfluxo será excluído.

| *SubStreamLateData*
| Gerada quando a sincronização de integridade não recebe um instantâneo completo em tempo hábil com base no estabelecido `+repeat_interval_s+`.

| *SubStreamTransformerError*
| Gerado quando a sincronização de integridade não consegue interpretar a carga útil enviada ao receptor. Por exemplo, "Missing required field 'name'" com payload `+{"checkStateId":"checkStateId3","health":"deviating","message":"Unable to provision the device. ","topologyElementIdentifier":"server-3"}+` e transformação `+Default Transformation+`.

| *SubStreamMissingCheckpoint*
| Gerada quando um subfluxo de incrementos transacionais observou anteriormente um ponto de verificação, mas a mensagem recebida não tem o `+previous_checkpoint+`

| *SubStreamInvalidCheckpoint*
| Gerada quando um subfluxo de incrementos transacionais observou anteriormente um ponto de controle, mas a mensagem recebida tem um `+previous_checkpoint+` que não é equivalente ao último observado.

| *SubStreamOutdatedCheckpoint*
| Levantada quando um subfluxo de incrementos transacionais observou anteriormente um ponto de controle, mas a mensagem recebida tem um `+checkpoint+` que precede o último observado, o que significa que seus dados já foram recebidos pelo SUSE Observability.

| *SubStreamUnknownCheckState*
| Levantado quando a exclusão de um Transactional incrementa check_state e o `+check_state_id+` não está presente no substream.
|===

== Veja também

* xref:/setup/cli/cli-sts.adoc[Instalar a CLI do SUSE Observability]
