= Guias de início rápido do SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE
:doctype: book

== Visão geral

Quando a instância do SUSE Observability SaaS tiver sido instalada e configurada, você receberá um e-mail do SUSE Observability com os detalhes de login necessários. Este guia de início rápido o ajudará a começar e a colocar seus próprios dados na instância do SUSE Observability SaaS.

Para integrar seu(s) cluster(s) ao SUSE Observability, você pode seguir um destes guias para seu ambiente apropriado.

* <<_amazon_eks,Amazon EKS>>
* <<_azure_aks,Azure AKS>>
* <<_google_gke,Google GKE>>
* <<_kubernetes,Kubernetes>>
* <<_kops,KOPS>>
* <<_openshift,OpenShift>>
* <<_self_hosted,Auto-hospedado>>


== Kubernetes

Configure uma integração do Kubernetes para coletar dados de topologia, eventos, registros, alterações e métricas de um cluster do Kubernetes e disponibilize-os no SUSE Observability.

=== Versões suportadas

|===
| Versão do Kubernetes compatível

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
|===

=== Tempo de execução suportado

|===
| Tempo de execução suportado

| ContêinerD
| CRI-O
|===

=== Pré-requisitos para o Kubernetes

Para configurar uma integração do SUSE Observability Kubernetes, você precisa ter:

* Um cluster Kubernetes em funcionamento.
* Helm versão 3.13.1 ou superior.
* Um usuário com permissão para `+create privileged pods+`, `+ClusterRoles+` e `+ClusterRoleBindings+`:
 ** O ClusterRole e o ClusterRoleBinding são necessários para conceder permissões aos SUSE Observability Agents para acessar a API do Kubernetes.
 ** Os SUSE Observability Agents precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações de host.

=== Configurar uma integração do Kubernetes

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_kubernetes,pré-requisitos do Kubernetes>>.
====


Para obter dados de um cluster Kubernetes no SUSE Observability, siga as etapas descritas abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do usuário do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e acesse `+StackPacks+` > `+Kubernetes+`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especificar um *nome de cluster do Kubernetes*
  *** Esse nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o SUSE Observability Agent, o Cluster Agent, o Checks Agent e o kube-state-metrics em seu cluster usando o comando helm fornecido na interface do usuário do SUSE Observability depois de instalar o StackPack.
 ** Depois que os agentes forem implantados, eles começarão a coletar dados e a enviá-los para o SUSE Observability

[CAUTION]
====
Ao executar em um ambiente auto-hospedado com air-gap, prepare a instalação do agente primeiro com as xref:/k8s-suse-rancher-prime-agent-air-gapped.adoc[instruções do air-gap].
====


== OpenShift

Configure uma integração do OpenShift para coletar dados de topologia, eventos, registros, alterações e métricas de um cluster do OpenShift e disponibilize-os no SUSE Observability.

=== Versões suportadas

|===
| Versão do OpenShift | Versão do Kubernetes compatível | Fim do suporte do OpenShift

| OpenShift 4.17
| Kubernetes 1.30
| 1º de abril de 2026

| OpenShift 4.16
| Kubernetes 1.29
| 27 de dezembro de 2025

| OpenShift 4.15
| Kubernetes 1.28
| 27 de agosto de 2025

| OpenShift 4.14
| Kubernetes 1.27
| 1º de maio de 2025

| OpenShift 4.13
| Kubernetes 1.26
| 17 de novembro de 2024

| OpenShift 4.12
| Kubernetes 1.25
| 17 de julho de 2024

| OpenShift 4.11
| Kubernetes 1.24
| 10 de fevereiro de 2024

| OpenShift 4.10
| Kubernetes 1.23
| 10 de setembro de 2023

| OpenShift 4.9
| Kubernetes 1.22
| 18 de abril de 2023
|===

=== Tempo de execução suportado

|===
| Tempo de execução suportado

| ContêinerD
| CRI-O
|===

=== Pré-requisitos para o OpenShift

Para configurar uma integração do SUSE Observability OpenShift, você precisa ter:

* Um cluster OpenShift em funcionamento.
* Helm versão 3.13.1 ou superior.
* Um usuário com permissão para `+create privileged pods+`, `+ClusterRoles+` e `+ClusterRoleBindings+`:
 ** O ClusterRole e o ClusterRoleBinding são necessários para conceder permissões aos SUSE Observability Agents para acessar a API do Kubernetes.
 ** Os SUSE Observability Agents precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações de host.

=== Configurar uma integração do OpenShift

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_openshift,pré-requisitos do Kubernetes>>.
====


Para obter dados de um cluster Kubernetes no SUSE Observability, siga as etapas descritas abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do usuário do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e acesse `+StackPacks+` > `+Integrations+` > `+Kubernetes+`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especificar um *nome de cluster do Kubernetes*
  *** Esse nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o SUSE Observability Agent, o Cluster Agent, o Checks Agent e o kube-state-metrics em seu cluster usando o comando helm fornecido na interface do usuário do SUSE Observability depois de instalar o StackPack.
 ** Depois que os agentes forem implantados, eles começarão a coletar dados e a enviá-los para o SUSE Observability


== Amazon EKS

Configure uma integração do Amazon EKS para coletar dados de topologia, eventos, registros, alterações e métricas de um cluster do Amazon EKS e disponibilize-os no SUSE Observability.

=== Versões suportadas

|===
| Kubernetes version | Lançamento do Amazon EKS | Fim do suporte do Amazon EKS | Fim do suporte estendido do Amazon EKS

| 1.32
| 23 de janeiro de 2025
| 23 de março de 2026
| 23 de março de 2027

| 1.31
| 26 de setembro de 2024
| 26 de novembro de 2025
| 26 de novembro de 2026

| 1.30
| 23 de maio de 2024
| 23 de julho de 2025
| 23 de julho de 2026

| 1.29
| 23 de janeiro de 2024
| 23 de março de 2025
| 23 de março de 2026

| 1.28
| 26 de setembro de 2023
| 01 de novembro de 2024
| 26 de novembro de 2025

| 1.27
| 24 de maio de 2023
| Julho de 2024
| 24 de julho de 2025

| 1.26
| 11 de abril de 2023
| Junho de 2024
| 11 de junho de 2025

| 1.25
| 21 de fevereiro de 2023
| Maio de 2024
| 1º de maio de 2025

| 1.24
| 15 de novembro de 2022
| Janeiro de 2024
| 31 de janeiro de 2025

| 1.23
| 11 de agosto de 2022
| 11 de outubro de 2023
| 11 de outubro de 2024

| 1.22
| 4 de abril de 2022
| 4 de junho de 2023
| 1º de setembro de 2024

| 1.21
| 19 de julho de 2021
| 15 de fevereiro de 2023
| 15 de julho de 2024

| 1.20
| 18 de maio de 2021
| 1º de novembro de 2022
| N/A

| 1.19
| 16 de fevereiro de 2021
| 1º de agosto de 2022
| N/A

| 1.18
| 13 de outubro de 2020
| 15 de agosto de 2022
| N/A
|===

=== Tempo de execução suportado

|===
| Tempo de execução suportado

| ContêinerD
| CRI-O
|===

=== Pré-requisitos para o Amazon EKS

Para configurar uma integração do SUSE Observability Amazon EKS, você precisa ter:

* Um cluster Amazon EKS em funcionamento.
* Helm versão 3.13.1 ou superior.
* Um usuário com permissão para `+create privileged pods+`, `+ClusterRoles+` e `+ClusterRoleBindings+`:
 ** O ClusterRole e o ClusterRoleBinding são necessários para conceder permissões aos SUSE Observability Agents para acessar a API do Kubernetes.
 ** Os SUSE Observability Agents precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações de host.

=== Configurar uma integração com o Amazon EKS

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_amazon_eks,pré-requisitos do Kubernetes>>.
====


Para obter dados de um cluster Kubernetes no SUSE Observability, siga as etapas descritas abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do usuário do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e acesse `+StackPacks+` > `+Integrations+` > `+Kubernetes+`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especificar um *nome de cluster do Kubernetes*
  *** Esse nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o SUSE Observability Agent, o Cluster Agent, o Checks Agent e o kube-state-metrics em seu cluster usando o comando helm fornecido na interface do usuário do SUSE Observability depois de instalar o StackPack.
 ** Depois que os agentes forem implantados, eles começarão a coletar dados e a enviá-los para o SUSE Observability


== Google GKE

Configure uma integração do Google GKE para coletar dados de topologia, eventos, registros, alterações e métricas de um cluster do Google GKE e disponibilize-os no SUSE Observability.

=== Versões suportadas

|===
| Kubernetes Version | Lançamento do Google GKE | Fim do suporte do Google GKE | Fim do suporte estendido do Google GKE

| 1.32
| Fevereiro de 2025
| Q2, 2026
| Q1, 2027

| 1.31
| 22 de outubro de 2024
| 22 de dezembro de 2025
| 22 de outubro de 2026

| 1.30
| 30 de julho de 2024
| 30 de setembro de 2025
| 30 de julho de 2026

| 1.29
| 25 de janeiro de 2024
| 21 de março de 2025
| 25 de janeiro de 2026

| 1.28
| 4 de dezembro de 2023
| 4 de fevereiro de 2025
| 4 de dezembro de 2025

| 1.27
| 14 de junho de 2023
| 31 de agosto de 2024
| 14 de junho de 2025

| 1.26
| 14 de abril de 2023
| 30 de junho de 2024
| N/A
|===

=== Tempo de execução suportado

|===
| Tempo de execução suportado

| ContêinerD
| CRI-O
|===

=== Pré-requisitos para o Google GKE

Para configurar uma integração do SUSE Observability com o Google GKE, você precisa ter:

* Um cluster do Google GKE em pleno funcionamento.
* Helm versão 3.13.1 ou superior.
* Um usuário com permissão para `+create privileged pods+`, `+ClusterRoles+` e `+ClusterRoleBindings+`:
 ** O ClusterRole e o ClusterRoleBinding são necessários para conceder permissões aos SUSE Observability Agents para acessar a API do Kubernetes.
 ** Os SUSE Observability Agents precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações de host.

=== Configurar uma integração com o Google GKE

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_google_gke,pré-requisitos do Kubernetes>>.
====


Para obter dados de um cluster Kubernetes no SUSE Observability, siga as etapas descritas abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do usuário do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e acesse `+StackPacks+` > `+Integrations+` > `+Kubernetes+`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especificar um *nome de cluster do Kubernetes*
  *** Esse nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o SUSE Observability Agent, o Cluster Agent, o Checks Agent e o kube-state-metrics em seu cluster usando o comando helm fornecido na interface do usuário do SUSE Observability depois de instalar o StackPack.
 ** Depois que os agentes forem implantados, eles começarão a coletar dados e a enviá-los para o SUSE Observability


== Azure AKS

Configure uma integração do Azure AKS para coletar dados de topologia, eventos, registros, alterações e métricas de um cluster do Azure AKS e disponibilize-os no SUSE Observability.

=== Versões suportadas

|===
| Kubernetes Version | AKS GA | Fim da vida útil do Azure AKS | Suporte à plataforma

| 1.32
| Junho de 2024
| Março de 2026
| Até a versão 1.36 GA

| 1.31
| Novembro de 2024
| Novembro de 2025
| Até 1.35 GA

| 1.30
| Junho de 2024
| Julho de 2025
| Até a versão 1.34 GA

| 1.29
| Março de 2024
| Janeiro de 2025
| Até a versão 1.33 GA

| 1.28
| Novembro de 2023
| Novembro de 2024
| Até a versão 1.32 GA

| 1.27
| Julho de 2023
| Julho de 2024
| Julho de 2025
|===

=== Tempo de execução suportado

|===
| Tempo de execução suportado

| ContêinerD
| CRI-O
|===

=== Pré-requisitos para o Azure AKS

Para configurar uma integração do SUSE Observability Azure AKS, você precisa ter:

* Um cluster do Azure AKS em pleno funcionamento.
* Helm versão 3.13.1 ou superior.
* Um usuário com permissão para `+create privileged pods+`, `+ClusterRoles+` e `+ClusterRoleBindings+`:
 ** O ClusterRole e o ClusterRoleBinding são necessários para conceder permissões aos SUSE Observability Agents para acessar a API do Kubernetes.
 ** Os SUSE Observability Agents precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações de host.

=== Configurar uma integração do Azure AKS

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_azure_aks,pré-requisitos do Kubernetes>>.
====


Para obter dados de um cluster Kubernetes no SUSE Observability, siga as etapas descritas abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do usuário do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e acesse `+StackPacks+` > `+Integrations+` > `+Kubernetes+`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especificar um *nome de cluster do Kubernetes*
  *** Esse nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o SUSE Observability Agent, o Cluster Agent, o Checks Agent e o kube-state-metrics em seu cluster usando o comando helm fornecido na interface do usuário do SUSE Observability depois de instalar o StackPack.
 ** Depois que os agentes forem implantados, eles começarão a coletar dados e a enviá-los para o SUSE Observability


== KOPS

Configure uma integração KOPS para coletar dados de topologia, eventos, registros, alterações e métricas de um cluster KOPS e disponibilize-os no SUSE Observability.

=== Versões suportadas

|===
| Versão do Kubernetes compatível

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Tempo de execução suportado

|===
| Tempo de execução suportado

| ContêinerD
| CRI-O
|===

=== Pré-requisitos para o KOPS

Para configurar uma integração do SUSE Observability KOPS, você precisa ter:

* Um cluster KOPS em funcionamento.
* Helm versão 3.13.1 ou superior.
* Um usuário com permissão para `+create privileged pods+`, `+ClusterRoles+` e `+ClusterRoleBindings+`:
 ** O ClusterRole e o ClusterRoleBinding são necessários para conceder permissões aos SUSE Observability Agents para acessar a API do Kubernetes.
 ** Os SUSE Observability Agents precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações de host.

=== Configurar uma integração KOPS

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_kops,pré-requisitos do Kubernetes>>.
====


Para obter dados de um cluster Kubernetes no SUSE Observability, siga as etapas descritas abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do usuário do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e acesse `+StackPacks+` > `+Integrations+` > `+Kubernetes+`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especificar um *nome de cluster do Kubernetes*
  *** Esse nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o SUSE Observability Agent, o Cluster Agent, o Checks Agent e o kube-state-metrics em seu cluster usando o comando helm fornecido na interface do usuário do SUSE Observability depois de instalar o StackPack.
 ** Depois que os agentes forem implantados, eles começarão a coletar dados e a enviá-los para o SUSE Observability


== Auto-hospedado

Configure uma integração auto-hospedada para coletar dados de topologia, eventos, registros, alterações e métricas de um cluster auto-hospedado e disponibilize-os no SUSE Observability.

=== Versões suportadas

|===
| Versão do Kubernetes compatível

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Tempo de execução suportado

|===
| Tempo de execução suportado

| ContêinerD
| CRI-O
|===

=== Pré-requisitos para hospedagem própria

Para configurar uma integração SUSE Observability Self-hosted, você precisa ter:

* Um cluster auto-hospedado em funcionamento.
* Helm versão 3.13.1 ou superior.
* Um usuário com permissão para `+create privileged pods+`, `+ClusterRoles+` e `+ClusterRoleBindings+`:
 ** O ClusterRole e o ClusterRoleBinding são necessários para:
  *** Conceder permissões aos SUSE Observability Agents para acessar a API do Kubernetes
  *** Gerar um segredo para o webhook de validação mutante que faz parte do xref:/setup/agent/k8sTs-agent-request-tracing.adoc[rastreamento de solicitações]
 ** Os SUSE Observability Agents precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações de host.

=== Configurar uma integração auto-hospedada

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_self_hosted,pré-requisitos do Kubernetes>>.
====


Para obter dados de um cluster Kubernetes no SUSE Observability, siga as etapas descritas abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do usuário do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e acesse `+StackPacks+` > `+Integrations+` > `+Kubernetes+`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especificar um *nome de cluster do Kubernetes*
  *** Esse nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o SUSE Observability Agent, o Cluster Agent, o Checks Agent e o kube-state-metrics em seu cluster usando o comando helm fornecido na interface do usuário do SUSE Observability depois de instalar o StackPack.
 ** Depois que os agentes forem implantados, eles começarão a coletar dados e a enviá-los para o SUSE Observability


== O que vem a seguir?

* xref:/k8s-getting-started.adoc[Passo a passo do SUSE Observability]
