include::partial$variables.adoc[]
= Redação de políticas para {project-name} 
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Desenvolva políticas de controle de admissão expondo funcionalidades bem definidas por meio de uma API específica usando qualquer linguagem de programação compatível.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "políticas de escrita"].
:sidebar_label: Políticas de redação
:current-version: {page-origin-branch}

Esta seção apresenta as políticas do {project-name} usando analogias tradicionais da computação.

Uma política {short-project-name} é como um programa que faz um trabalho.
Ele recebe dados de entrada, executa cálculos com esses dados e retorna um resultado.

Os dados de entrada são solicitações de admissão do Kubernetes.
O resultado do cálculo é uma resposta de validação, que informa ao Kubernetes se deve aceitar, rejeitar ou alterar os dados de entrada, a solicitação de admissão.

O componente https://github.com/kubewarden/policy-server[policy-server]do site {short-project-name} realiza essas operações.

O servidor de políticas não inclui nenhum recurso de processamento de dados.
Você adiciona recursos de processamento em tempo de execução com add-ons.
Esses complementos são as políticas do {short-project-name}.

Portanto, uma política {short-project-name} é como umhttps://en.wikipedia.org/wiki/Plug-in_%28computing%29[plug-in tradicional]do programa "servidor de políticas".

Para recapitular:

* {short-project-name} As políticas são plug-ins que expõem um conjunto de funcionalidades bem definidas (validam um objeto de solicitação do Kubernetes, validam as configurações de política fornecidas pelo usuário e outras funções) usando uma API bem definida
* O servidor de políticas é o programa "principal" que carrega os plug-ins (também conhecidos como políticas) e usa suas funcionalidades expostas para aceitar, rejeitar ou alterar as solicitações do Kubernetes

Escrever as políticas do {short-project-name} consiste em escrever a lógica comercial de validação e, em seguida, expô-la por meio de uma API bem definida.

== Requisitos de linguagem de programação

Você fornece as políticas do {short-project-name} como binárioshttps://webassembly.org/[do].

Os autores de políticas podem escrever políticas usando qualquer linguagem de programação que ofereça suporte ao WebAssembly como destino de compilação.
A lista de linguagens compatíveis está em constante evolução, https://github.com/appcypher/awesome-wasm-langs[. Esta página] oferece uma boa visão geral do cenário do WebAssembly.

Atualmente, o WebAssembly não tem uma maneira oficial de compartilhar tipos de dados complexos entre o host e um convidado do WebAssembly.
Para superar essa limitação, as políticas do {short-project-name} usam o projeto https://github.com/wapc[waPC], que fornece um canal de comunicação bidirecional.

Portanto, a linguagem de programação de sua escolha deve ter um SDK de convidado waPC disponível.
Se esse não for o caso, sinta-se à vontade para entrar em contato.
A equipe do projeto pode ajudá-lo a superar essa limitação.
