include::partial$variables.adoc[]
= Audit Scanner - Beschränkungen
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie mehr über die Einschränkungen bei der Verwendung des Audit-Scanners zur Bewertung von Richtlinien und Ereignistypen in einer Kubernetes-Umgebung, einschließlich der Verwendung zur Bewertung von Richtlinien und Ereignistypen.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["explanations", "audit-scanner", "limitations"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "kubernetes", "audit scanner"]
:sidebar_label: Beschränkungen
:current-version: {page-origin-branch}

== Unterstützte Ereignistypen

Richtlinien können die Ereignisse `+CREATE+`, `+UPDATE+` und `+DELETE+` überprüfen.

Der Audit-Scanner kann keine `+UPDATE+` Ereignisse simulieren, da er nicht weiß, welcher Teil der Ressource geändert werden muss.

Der Audit-Scanner ignoriert also eine Richtlinie, die sich nur mit `+UPDATE+` Ereignissen befasst. scannen.

[NOTE]
====

Die Version v1.7.0 des Audit-Scanners unterstützt nur `+CREATE+` Ereignisse. Die Bearbeitung von`+DELETE+` Ereignissen wird in Kürze erfolgen.

====


== Richtlinien, die sich auf Benutzer- und Benutzergruppeninformationen stützen

Jedes Kubernetes-Zulassungsanforderungsobjekt enthält Informationen darüber, welcher Benutzer (oder ServiceAccount) das Ereignis ausgelöst hat und zu welcher Gruppe er gehört.

Alle vom Audit-Scanner simulierten Ereignisse stammen von demselben fest kodierten Benutzer und derselben Gruppe. Aus diesem Grund werden Maßnahmen, die sich bei ihren Entscheidungen auf diese Werte stützen, keine sinnvollen Ergebnisse liefern.

Konfigurieren Sie in diesen Fällen die Richtlinie als nicht prüfbar. checks.

== Politische Maßnahmen, die sich auf externe Daten stützen

Die Politik kann bei der Durchführung einer Bewertung externe Daten anfordern und verwenden. Sie können diese Maßnahmen mit Hilfe von Audit-Prüfungen bewerten, aber ihre Ergebnisse können sich je nach den externen Daten ändern.

== Verwendung von `+*+` durch die Politik

Sowohl die benutzerdefinierten Ressourcen `+AdmissionPolicy+` als auch `+ClusterAdmissionPolicy+` haben die folgenden Felder:

[subs="+attributes",yaml]
----
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
----

Die Attribute `+apiGroups+`, `+apiVersions+` und `+resources+` können den Platzhalter`+*+` verwenden. Dieses Platzhaltersymbol bewirkt, dass die Richtlinie auf alle in diesem Feld verwendeten Werte passt. Der Audit-Scanner ignoriert Richtlinien, die das Symbol `+*+` verwenden.
