= 关于 StackPacks
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自助托管版 v5.1.x

== 概述

StackPacks 可扩展 SUSE Observability 功能，并提供与外部系统的自动集成。它们可以通过 SUSE Observability 的 StackPacks 页面轻松安装和卸载。

StackPack 有两种类型：附加组件和集成。可用的 StackPack 附加组件和集成可在 SUSE Observability UI 的*StackPacks*页面上找到。

== 安装或卸载堆栈包

可以通过 SUSE Observability 中的*StackPacks*页面安装和卸载*StackPacks*。提供了安装和卸载 StackPack 的完整说明。

[NOTE]
====
*请注意*

* 堆栈包可能需要*手动*安装步骤或配置外部系统。请仔细阅读提供的说明。
* 卸载 StackPack 或 StackPack 实例时，*SUSE Observability 将删除通过 StackPack（实例）接收的所有数据。*
* 在外部系统中（手动）配置或安装 StackPack 组件可能需要单独卸载。

====


=== 堆栈包实例

某些 StackPack 允许您连接外部系统上的多个账户。每个账户都在单独的 StackPack 实例中配置。

例如，AWS StackPack 可以连接多个 AWS 账户，并将所有账户的信息整合到 SUSE Observability 中。对于每个账户，都会为一个单独的 SUSE Observability 实例配置从 AWS 账户接收数据所需的信息。

== 升级堆栈包

[CAUTION]
====
升级*StackPack* 时，*对该 StackPack 配置项所做的任何更改都将被覆盖*。有关详情，请参阅xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[锁定的配置项目]。
====


如果有新的 StackPack 版本，SUSE Observability UI StackPack 页面会显示提示，您可以选择查看升级详情并阅读发布说明。如果新版本与当前安装的版本相比只是小幅升级，也可以从这里升级 StackPack。

=== 新的次要 StackPack 版本

要升级到 StackPack 的新次要版本，请单击 SUSE Observability UI 中 StackPack 页面上的*UPGRADE NOW*。

请注意，升级时所有 StackPack 配置项都将被覆盖。要继续使用对这些配置所做的任何更改，请在升级 StackPack 时选择*保留*现有配置。有关详情，请参阅xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[锁定的配置项目]。

=== 新的主要 StackPack 版本

[CAUTION]
====
升级*StackPack* 时，*对该 StackPack 配置项所做的任何更改都将被覆盖*。有关详情，请参阅xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[锁定的配置项目]。
====


要升级到某个 StackPack 的新主要版本，请xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[卸载并重新安装]该 StackPack。

[TIP]
====

升级后继续使用对自定义 StackPack 配置项所做的更改：

. 升级前，请导出每个自定义项目：
 ** 转到 SUSE Observability UI 的*设置*页面。
 ** 单击 *...*每个自定义项目的菜单。
. 升级 StackPack（卸载并重新安装）。
. 更改每个导出项目的`name` 和`identifier` ：
 ** 用文本编辑器打开导出文件。
 ** 编辑顶层`name` 和`identifier` 字段。
 ** 保存导出。
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[导入]更新的导出文件。
. 定制的配置项现在可在 SUSE Observability 中使用，并可复制到新安装的 StackPack 配置项中。

====


== 锁定的配置项

StackPack 包含 SUSE Observability 的配置信息，在安装 StackPack（实例）时安装。其中包括组件模板、功能、组件操作和视图。升级 StackPack 时，*旧版本 StackPack 安装的配置项将被新版本 StackPack 的配置项覆盖。*这意味着在升级 StackPack 时，对这些配置项所做的任何手动更改都将被覆盖。

为防止用户更改由 StackPack 安装的配置项（这些配置项将在升级时被覆盖），这些配置项默认是*锁定的*。这意味着它们受到保护，用户无法更改，必须明确*解锁*后才能更改。

[TIP]
====

您可以xref:/setup/data-management/backup_restore/configuration_backup.adoc[备份配置项目]。请注意，配置项的锁定状态不会作为配置备份的一部分导出。
====

