= Erste Schritte mit Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

image::otel/open-telemetry.svg[Open Telemetry Collector und 2 instrumentierte Anwendungen, die Metriken und Traces an SUSE Observability senden]

SUSE Observability unterstützt https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry ist eine Reihe von standardisierten Protokollen und ein Open-Source-Framework zur Erfassung, Umwandlung und Übermittlung von Telemetriedaten wie Traces, Metriken und Protokollen. Die offene Telemetrie unterstützt eine Vielzahl von Programmiersprachen und Plattformen.

SUSE Observability unterstützt sowohl Metriken als auch Traces und fügt die Open Telemetry-Metriken und Traces zu den (Kubernetes-)Topologiedaten hinzu, die vom SUSE Observability-Agent bereitgestellt werden. Daher ist es weiterhin erforderlich, auch den SUSE Observability-Agenten zu installieren. Unterstützung für Protokolle und die Verwendung von Open Telemetry ohne den SUSE Observability-Agenten ist in Kürze verfügbar.

Open Telemetry besteht aus mehreren verschiedenen Komponenten. Für die Verwendung mit SUSE Observability sind die xref:/setup/otel/languages/README.adoc[SDKs] zur Instrumentierung Ihrer Anwendung und der xref:/setup/otel/collector.adoc[Open Telemetry-Kollektor] die wichtigsten Bestandteile. Wir zeigen Ihnen, wie Sie beide für die Verwendung mit SUSE Observability konfigurieren.

Wenn Ihre Anwendung bereits mit Open Telemetry oder einer anderen von Open Telemetry unterstützten Bibliothek wie Jaeger oder Zipkin instrumentiert ist, kann der Collector verwendet werden, um diese Daten an SUSE Observability zu übermitteln, ohne dass eine zusätzliche Instrumentierung erforderlich ist.

Für SUSE Observability muss der Collector mit bestimmten Prozessoren und Authentifizierung konfiguriert werden, um sicherzustellen, dass alle von SUSE Observability verwendeten Daten verfügbar sind.

== Referenzen

* https://opentelemetry.io/docs/collector/[Öffnen Sie den Telemetrie-Kollektor] in der Dokumentation Open Telemetry
* https://opentelemetry.io/docs/languages/[SDKs für die Instrumentierung Ihrer Anwendung] in der Open Telemetry-Dokumentation
