= Erste Schritte mit Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

image::otel/open-telemetry.svg[Open Telemetry Collector und 2 instrumentierte Anwendungen, die Metriken und Traces an SUSE Observability senden]

SUSE Observability unterstützt https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry ist eine Reihe von standardisierten Protokollen und ein Open-Source-Framework zur Erfassung, Umwandlung und Übermittlung von Telemetriedaten wie Traces, Metriken und Protokollen. Die offene Telemetrie unterstützt eine Vielzahl von Programmiersprachen und Plattformen.

SUSE Observability unterstützt sowohl Metriken als auch Traces. Bei Verwendung in Kombination mit dem Kubernetes-Stackpack werden die Kubernetes-Pods mit Traces angereichert, wenn diese verfügbar sind. Durch die Installation des Open Telemetry Stackpacks werden neue Übersichtsseiten für Services und Service-Instanzen verfügbar, die Zugang zu Traces und Span Metrics bieten. Open Telemetry-Metriken können in Monitoren und Metrik-Bindungen verwendet werden. Das Stackpack enthält metrische Bindungen für Span-Metriken und .NET- und JVM-Speichermetriken. Es gibt auch sofort einsatzbereite Monitore für Spannenfehlerraten und Dauer.

Für die Verwendung mit SUSE Observability wird empfohlen, Anwendungen mit den entsprechenden Open xref:/setup/otel/instrumentation/README.adoc[Telemetry-SDKs] zu instrumentieren und den xref:/setup/otel/collector.adoc[Open Telemetry-Collector] in der Nähe der instrumentierten Anwendungen zu installieren, um die Daten vorzuverarbeiten (Anreicherung mit Kubernetes-Labels, Sampling auf Traces usw.) und die Daten an SUSE Observability zu senden. Der Open Telemetry Collector kann auch dazu verwendet werden, Metriken von vielen Arten von Telemetriequellen zu sammeln, ohne die Anwendungen mit den SDKs zu instrumentieren. Unter https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry Collector-Integrationen] finden Sie weitere Informationen und erfahren, ob Ihre Datenbank oder Ihr Telemetrieprotokoll unterstützt wird.

Folgen Sie der Anleitung für xref:/setup/otel/getting-started/README.adoc[die ersten Schritte], um alles so einzurichten, dass es optimal mit SUSE Observability funktioniert.

== Referenzen

* https://opentelemetry.io/docs/collector/[Öffnen Sie den Telemetrie-Kollektor] in der Dokumentation Open Telemetry
* https://opentelemetry.io/ecosystem/registry/?language=collector[Offene Telemetrie-Kollektor-Integrationen]
* https://opentelemetry.io/docs/instrumentation/README.md[SDKs für die Instrumentierung Ihrer Anwendung] in der Open Telemetry-Dokumentation
