= Probenahme
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

Sampling wird eingesetzt, um das Datenvolumen, das an SUSE Observability exportiert wird, zu reduzieren und gleichzeitig die Qualität der Telemetriedaten so wenig wie möglich zu beeinträchtigen. Der Hauptgrund für die Anwendung von Stichproben ist die Senkung der Kosten (für Netz, Speicherung usw.).

Wenn Ihre Anwendungen nur wenige Daten generieren, besteht keine Notwendigkeit für Stichproben, und es kann sogar die Beobachtbarkeit aufgrund fehlender Telemetriedaten behindern. Wenn Ihre Anwendung jedoch ein erhebliches Verkehrsaufkommen hat, z. B. mehr als 1000 Spans pro Sekunde, kann es bereits sinnvoll sein, Sampling anzuwenden.

Es gibt 2 Haupttypen von Stichproben: Kopfproben und Schwanzproben.

== Kopfprobe

Bei der Kopfstichprobe wird die Entscheidung über die Stichprobenziehung (ob die Daten exportiert werden sollen oder nicht) so früh wie möglich getroffen. Daher kann die Entscheidung nicht auf der Grundlage der gesamten Spur getroffen werden, sondern nur auf der Grundlage der sehr begrenzten Informationen, die verfügbar sind. Der otel Kollektor verfügt über den https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/probabilisticsamplerprocessor[probabilistischen Sampling-Prozessor], der Consistent Probability Sampling implementiert. Der Sampler ist konfigurierbar und trifft eine Sampling-Entscheidung auf der Grundlage der Trace-ID (nützlich für Traces) oder eines Hashes eines Attributs (nützlich für Logs). Auf diese Weise wird sichergestellt, dass immer alle Zeitspannen für eine Ablaufverfolgung erfasst werden und Sie über vollständige Ablaufverfolgungen in SUSE Observability verfügen.

Die Vorteile der Kopfprobe sind:

* Leicht zu verstehen
* Effiziente
* Einfach zu konfigurieren

Ein Nachteil ist jedoch, dass es nicht möglich ist, Stichprobenentscheidungen für eine gesamte Spur zu treffen, z. B. alle fehlgeschlagenen Spuren und nur eine kleine Auswahl der erfolgreichen Spuren zu prüfen.

Um das Head-Sampling zu aktivieren, konfigurieren Sie den Prozessor und schließen ihn in die Pipelines ein. In diesem Beispiel wird anhand der Trace-ID 1 von 4 Traces ausgewählt:

[,yaml]
----
processors:
  probabilistic_sampler:
    sampling_percentage: 25
    mode: "proportional"
----

== Schwanzprobenahme

Beim Tail Sampling wird die Entscheidung über die Probenahme verschoben, bis eine Spur (fast) vollständig ist. Dadurch kann der Tail-Sampler Entscheidungen über die Probenahme auf der Grundlage der gesamten Kurve treffen, z. B. immer ausgefallene Kurven und/oder langsame Kurven zu nehmen. Es gibt noch viele weitere Möglichkeiten, z. B. Stichproben auf der Grundlage bestimmter Merkmale oder der Teilnahme an Dienstleistungen.

Der OpenTelemetry Collector bietet einen https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor[Tail Sampling Prozessor], der zur Anwendung von Tail Sampling Richtlinien verwendet werden kann.

Der Hauptvorteil des Tail Samplings ist die zusätzliche Flexibilität, die es bietet, wenn es darum geht, Stichprobenentscheidungen auf der Grundlage vollständiger Spurdaten zu treffen, anstatt auf der Grundlage von Teilinformationen, die bei der Erstellung einzelner Spans verfügbar sind.


[WARNING]
====
Obwohl dies vorteilhaft ist, hat das Tail Sampling die folgenden Nachteile:

* Schwerer zu konfigurieren und zu verstehen.
* Muss zustandsabhängig sein, um die Spans für Traces zu speichern, bis eine Stichprobenentscheidung getroffen wird.
* Daher auch (viel) mehr Ressourcenverbrauch
* Der Probenehmer kann unter Umständen nicht mithalten und benötigt deshalb zusätzliche Überwachung und Skalierung
====

Um das Tail-Sampling zu aktivieren, konfigurieren Sie den Prozessor und fügen Sie ihn in die Pipelines ein.

[,yaml]
----
processors:
  tail_sampling:
    decision_wait: 10s
    policies:
    - name: rate-limited-composite
      type: composite
      composite:
        max_total_spans_per_second: 500
        policy_order: [errors, slow-traces, rest]
        composite_sub_policy:
        - name: errors
          type: status_code
          status_code:
            status_codes: [ ERROR ]
        - name: slow-traces
          type: latency
          latency:
            threshold_ms: 1000
        - name: rest
          type: always_sample
        rate_allocation:
        - policy: errors
          percent: 33
        - policy: slow-traces
          percent: 33
        - policy: rest
          percent: 34
----

Das Beispiel zeigt:

* Maximal 500 Spannen pro Sekunde
* alle Spannen in Kurven, die Fehler bis zu 33% des maximalen Wertes aufweisen
* alle Spans in Traces, die langsamer als 1 Sekunde sind, bis zu 33 % der maximalen
* andere Zeiträume bis zum zulässigen Höchstsatz

Weitere Einzelheiten zu den Konfigurationsoptionen und verschiedenen Richtlinien finden Sie in der https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor[Readme-Datei].

Sie ist jedoch nicht völlig einsatzbereit und vergesslich. Wenn die Ressourcennutzung zunimmt, müssen Sie mehrere Collectors einsetzen, um das Tail-Sampling zu bewältigen, was dann auch https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/routingconnector/README.md[Routing] erfordert, um den Datenverkehr auf der Grundlage der Trace-ID weiterzuleiten.

== Abtastspuren in Kombination mit Spannenmetriken

Im Abschnitt "Erste Schritte" enthält die Kollektorkonfiguration keine Probenahme. Bei der Hinzufügung von Stichproben sollte darauf geachtet werden, dass die aus Traces berechneten Metriken so genau wie möglich sind. Insbesondere das Tail-Sampling kann zu sehr verzerrten Metriken führen, da der relative Anteil der Fehler in der Regel viel höher ist. Um dies zu vermeiden, teilen wir die Leiterbahnen in mehrere Teile auf und verbinden sie mit dem Vorwärtsverbinder. Ändern Sie die Konfiguration, um den zusätzlichen Anschluss und den Sampling-Prozessor einzubeziehen. Und ändern Sie die Pipelines wie hier gezeigt:

[,yaml]
----
connectors:
  # enable the forwarder
  forward:
processors:
  # Configure the probabilistic sampler to sample 25% of the traffic
  probabilistic_sampler:
    sampling_percentage: 25
    mode: "proportional"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource]
      exporters: [forward]
    traces/spanmetrics:
      receivers: [forward]
      processors: []
      exporters: [spanmetrics]
    traces/sampling:
      receivers: [forward]
      processors: [probabilistic_sampler, batch]
      exporters: [debug, otlp/stackstate]
    metrics:
      receivers: [otlp, spanmetrics, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlp/stackstate]
----

Im Beispiel wird der probabilistische Sampler verwendet, der so konfiguriert ist, dass 25 % des Datenverkehrs abgetastet werden. Wahrscheinlich werden Sie den Prozentsatz für Ihre Situation anpassen oder stattdessen zum <<_tail_sampling,Tail Sampler>> wechseln wollen. Das Pipeline-Setup ist das gleiche für den Tail-Sampler, ersetzen Sie einfach den Verweis auf die `probabilistic_sampler` mit `tail_sampling`.
