include::partial$variables.adoc[]
= 重复使用验证入场策略
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 了解如何使用{project-name}'s (cel-policy) 在 Kubernetes 中重用和验证准入策略。
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "ValidatingAdmissionPolicies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "ValidatingAdmissionPolicies"]
:sidebar_label: 重复使用 VAP
:current-version: {page-origin-branch}

Kubernetes 香草https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy[验证策略] 由以下资源组成：

* ValidatingAdmissionPolicy：描述 CEL 中的逻辑。它还可选择接受`+spec.paramKind+` 中的参数。
* ValidatingAdmissionPolicyBinding: 扩展策略范围。

让我们来看一个具体的例子。使用{project-name} 的`+cel-policy+` ，只需花很少的力气就可以重复使用这些和其他功能。

== ValidatingAdmissionPolicy

以下 ValidatingAdmissionPolicy 改编自https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#creating-a-validatingadmissionpolicy[Kubernetes docs]。

该策略会检查部署中的副本数量是否小于或等于默认的`+maxreplicas+` 5。用户可以在每个命名空间或部署中覆盖此默认值，并通过使用参数选择一个较小的数字。

它与`+ValidatingAdmissionPolicyBinding+` 绑定。因此，它只影响标签`+environment+` 设置为`+test+` 的命名空间。

../vap-policy-example.yaml
[,yaml]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "replicalimit-policy.example.com"
spec:
  failurePolicy: Fail # (1)
  matchConstraints: # (2)
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  variables: # (3)
    - name: maxReplicas # hardcoded global default
      expression: int(5)
  paramKind: # (4)
    apiVersion: v1
    kind: ConfigMap # user-provided override
  validations: # (5)
    - expression: |
        object.spec.replicas <= (
          has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
          ? int(params.data.overrideReplicas)
          : variables.maxReplicas
        )
      messageExpression: |
        'The number of replicas must be less than or equal to ' +
        string( has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
          ? int(params.data.overrideReplicas)
          : variables.maxReplicas)
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "replicalimit-binding-test.example.com"
spec:
  policyName: "replicalimit-policy.example.com"
  validationActions: [Deny] # (7)
  matchResources: # (8)
    namespaceSelector:
      matchLabels:
        environment: test
  paramRef: # (4)
    name: "replica-limit-override"
    namespace: "test"
    parameterNotFoundAction: Deny
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replica-limit-override
  namespace: test
data:
  overrideReplicas: "3"
----

在这里，我们有一个同等的{short-project-name} 政策：

### {short-project-name}'s `+cel-policy+`

../cel-policy-example.yaml
[,yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: Resource validation # (9)
    io.kubewarden.policy.severity: low # (9)
  name: "cel-policy-replica-example"
spec:
  module: registry://ghcr.io/kubewarden/policies/cel-policy:v1.4.0
  failurePolicy: Fail # (6). Webhook behavior. Defaults to "Fail"
  mode: protect # (7). Defaults to "protect"
  rules: # (2)
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["deployments"]
  contextAwareResources: # (10). Fine-grained perms for accessing resources
    - apiVersion: v1
      kind: ConfigMap
  settings:
    failurePolicy: Fail # (1). CEL behavior. Defaults to "Fail"
    variables: # (3)
      - name: "replicas"
        expression: "object.spec.replicas"
      - name: maxReplicas
        expression: int(5)
    paramKind: # (4)
      apiVersion: v1
      kind: ConfigMap # user-provided override
    paramRef: # (4)
      name: "replica-limit-override"
      namespace: "test"
      parameterNotFoundAction: Deny
    validations: # (5)
      - expression: |
          object.spec.replicas <= (
            has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
            ? int(params.data.overrideReplicas)
            : variables.maxReplicas
          )
        messageExpression: |
          'The number of replicas must be less than or equal to ' +
          string( has(params.data.overrideReplicas) && int(params.data.overrideReplicas) < variables.maxReplicas
            ? int(params.data.overrideReplicas)
            : variables.maxReplicas)
  backgroundAudit: true # (9). Defaults to "true"
  namespaceSelector: # (8)
    matchLabels:
      environment: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replica-limit-override
  namespace: test
data:
  overrideReplicas: "3"
----

注意这两个 YAML 清单上的注释数字。让我们继续讨论：

[cols="1,1,1,3", options="header"]
|===
| #   | VAP 领域                         | `+cel-policy+` 领域                       | 说明

| 1   | `+failurePolicy+`                   | `+settings.failurePolicy+`                 | CEL 行为，用于 CEL 表达式求值为 false、CEL 运行时出错、CEL 无效或配置错误的情况。例如，CEL 表达式返回 false、缺少参数或缺少变量。不要与（6）混淆。
| 2   | `+matchConstraints+`                | `+rules+`                                  | 两者都接受相同的https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#rulewithoperations-v1-admissionregistration[] RuleWithOperations，以告知该策略适用于哪种资源。
| 3   | `+variables+`                       | `+settings.variables+`                     | 在{short-project-name} 的`+cel-policy+` 中，定义变量的表达式在`+settings.variables+` 中。除此之外，它们是等价的。
| 4   | `+paramKind+`,`+paramRef+`            | `+settings.paramKind+`,`+settings.paramRef+` | 在{short-project-name} 的`+cel-policy+` 中，参数定义在`+settings.paramKind+`,`+settings.paramRef+` 中。除此之外，它们是等价的。
| 5   | `+validations+`                     | `+settings.validations+`                   | 在{short-project-name} 的`+cel-policy+` 中，定义验证的表达式在`+settings.validations+` 中。除此之外，它们是等价的。
| 6   | `+---+`                             | `+failurePolicy+`                          | Webhook 行为，用于 Kubernetes API Webhook 错误或超时，或用于 matchConditions 评估。不要与（1）混淆。
| 7   | `+validationActions+`               | `+mode+`                                   | `+mode+` `+protect+` 和`+monitor+` 选项。{short-project-name} 中的审计功能更加全面，见 (9)。
| 8   | `+matchResources+`                  | `+namespaceSelector+`, `+objectSelector+`   | 使用 "选择器 "定义约束方式。{short-project-name}"策略 "中的 "选择器 "分别为`+namespaceSelector+` 和`+objectSelector+` 。
| 9   | `+auditAnnotations+` 无图 | `+backgroundAudit+`，注释           | 使用{short-project-name} 字段来设置xref:explanations/audit-scanner/audit-scanner.adoc[审计扫描器]中的策略用法，以及 OpenReports 中的策略类别和严重程度。
|10|`+---+`|`+contextAwareResources+` 权限|{short-project-name}} 的策略具有读取集群资源的细粒度权限。此处用于读取参数。
|     | `+matchConditions+`                 | `+matchConditions+`                        | {short-project-name}的政策有`+matchConditions+` （本例中未显示）。
|     | `+---+`                             | {short-project-name}-仅功能                 | 有关其他功能，请参阅 CEL 示例教程的其他部分。
|===

[TIP]
====

您可以使用`+kwctl+` 工具将 VAP 策略迁移到{short-project-name} 。

本xref:howtos/vap-migration.adoc[VAP 迁移手册]介绍了如何进行xref:howtos/vap-migration.adoc[迁移]。

====


=== 尚未实施的等价物

有些 VAP 功能尚未实现。如果您对它们充满期待，请与我们联系。它们是

* VAPhttps://pkg.go.dev/k8s.io/apiserver/pkg/cel/library#Authz[授权程序库]。
* VAPhttps://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/[审计注释]（当 ValidatingAdmissionPolicyBinding`+spec.validationActions+` 设置为"时，ValidatingAdmissionPolicy`+spec.auditAnnotations+` ）。
{short-project-name} 的 "xref:explanations/audit-scanner/audit-scanner.adoc[审计扫描器"（Audit Scanner]）和 "策略报告"（PolicyReports）可以审计集群中已有的资源。
* CELhttps://kubernetes.io/docs/reference/using-api/cel/#resource-constraints[资源限制和估计费用限制]。
这属于{short-project-name} 的一般xref:reference/policy-evaluation-timeout.adoc[政策超时保护]范围。

== 适用政策

像往常一样，我们可以通过实例化清单来部署策略：

[subs="+attributes",console]
----
$ kubectl apply -f ./cel-policy-example.yaml
----

然后通过实例化部署对其进行测试：

[subs="+attributes",console]
----
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    environment: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
EOF

namespace/test created
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-cel-policy-replica-example.kubewarden.admission" denied the request:
  The number of replicas must be less than or equal to 5
----
