include::partial$variables.adoc[]
= Was ist der Audit Scanner?
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie mehr über die Rolle des Audit-Scanners bei der kontinuierlichen Überprüfung der Einhaltung der Richtlinien des Admission Controllers in Ihren Clustern.
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-policy-developer", "kubewarden-integrator"]
:doc-topic: ["explanations", "audit-scanner"]
:doc-type: ["explanation"]
:keywords: ["{project-name}", "kubewarden", "audit scanner", "kubernetes"]
:sidebar_label: Audit-Scanner
:sidebar_position: 50
:current-version: {page-origin-branch}

[NOTE]
====

Die Funktion Audit Scanner ist ab der Version {project-name} 1.7.0 verfügbar.

====


Die Komponente `audit-scanner` überprüft ständig die Ressourcen im Cluster. Es markiert diejenigen, die sich nicht an die {short-project-name} Richtlinien halten, die im Cluster eingesetzt werden.

Politiken entwickeln sich im Laufe der Zeit weiter. Es werden neue Richtlinien eingeführt und aktualisiert.
Versionen und Konfigurationseinstellungen ändern sich. Dies kann dazu führen, dass Ressourcen, die sich bereits innerhalb des Clusters befinden, nicht mehr konform sind. Mit der Audit-Scan-Funktion steht Kubernetes-Administratoren ein Tool zur Verfügung, das den Compliance-Status ihrer Cluster ständig überprüft.

Um die Verwendung des Audit-Scanners in {short-project-name} zu erklären, betrachten Sie das folgende Szenario.

Angenommen, Bob stellt einen WordPress-Pod im Cluster bereit. Bob ist neu in Kubernetes, macht einen Fehler und setzt den Pod als privilegierten Container ein. Zu diesem Zeitpunkt gibt es keine Richtlinie, die dies verhindert, so dass der Pod erfolgreich im Cluster erstellt wird.

Ein paar Tage später setzt Alice, die Kubernetes-Administratorin, eine Richtlinie {short-project-name}durch, die die Erstellung von privilegierten Containern verbietet. Der von Bob bereitgestellte Pod läuft im Cluster weiter, da er bereits existiert.

Anhand eines vom Audit-Scanner erstellten Berichts kann Alice alle Workloads identifizieren, die gegen die Erstellungsrichtlinien verstoßen. Dazu gehört auch der von Bob erstellte WordPress-Pod.

Der Audit-Scanner funktioniert wie folgt:

* Identifizierung aller zu prüfenden Ressourcen
* für jede Ressource wird eine synthetische Zulassungsanfrage mit den Daten der Ressource erstellt
* er sendet jede Zulassungsanfrage an einen Policy-Server-Endpunkt, der nur für Prüfungsanfragen vorgesehen ist

Für die Politik, die den Antrag bewertet, gibt es keine Unterschiede zwischen echten und Prüfungsanträgen. Dieser Endpunkt des Auditing-Policy-Servers ist mit Instrumenten ausgestattet, um Daten über die Bewertung zu sammeln. Die Benutzer können also ihre Überwachungswerkzeuge verwenden, um die Daten des Audit-Scanners zu analysieren.

== Audit-Scanner einschalten

Sie können den Audit-Scanner ab der Version {short-project-name} 1.7.0 aktivieren.

Detaillierte Installationsanweisungen finden Sie in derxref:howtos/audit-scanner.adoc[Anleitung zum Audit-Scanner].

== Politiken

Standardmäßig wertet der Audit-Scanner jede Richtlinie aus. Betreiber, die eine Richtlinienauswertung im Audit-Scanner überspringen möchten, müssen das Feld`spec.backgroundAudit` in der Richtliniendefinition auf `false` setzen.

Außerdem unterstützen die Richtlinien in {short-project-name} jetzt zwei optionale Anmerkungen:

* Mit dem Vermerk `io.kubewarden.policy.severity` können Sie den Schweregrad des Richtlinienverstoßes angeben, z. B. `critical`, `high`, `medium`, `low` oder `info`.
* Mit dem Vermerk `io.kubewarden.policy.category` können Sie die Richtlinie auf der Grundlage eines bestimmten Bereichs oder Zwecks kategorisieren, z. B. `PSP`, `compliance` oder `performance`.

Weitere Informationen finden Sie in derxref:tutorials/writing-policies/index.adoc[Dokumentation] der Richtlinienautoren.

== Berechtigungen und ServiceAccounts

Der Audit-Scanner in {short-project-name} erfordert bestimmte RBAC-Konfigurationen (Role Based Access Control), um Kubernetes-Ressourcen scannen und die Ergebnisse speichern zu können. Bei der Installation wird ein korrektes Standarddienstkonto mit diesen Berechtigungen erstellt. Der Benutzer kann seinen eigenen ServiceAccount erstellen, um den Zugriff auf Ressourcen zu konfigurieren.

Der Standard-Audit-Scanner `ServiceAccount` bindet sich an die von Kubernetes bereitgestellte `view` `ClusterRole`. Diese `ClusterRole` ermöglicht den Nur-Lese-Zugriff auf eine Vielzahl von Kubernetes-Ressourcen innerhalb eines Namespaces. Weitere Einzelheiten zu dieser Rolle finden Sie in derhttps://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles[Kubernetes-Dokumentation].

Der Audit-Scanner bindet sich an eine `ClusterRole`, die Lesezugriff auf {short-project-name} Ressourcentypen und Lese- und Schreibzugriff auf die`PolicyReport` CRDs gewährt.  Mit diesen Berechtigungen kann der Scanner Ressourcen für die Durchführung von Audit-Bewertungen und die Erstellung von Richtlinienberichten auf der Grundlage der Bewertungsergebnisse abrufen.
