= Buenas prácticas de GitOps para Tortugas y CAPI
:revdate: 2025-10-02
:page-revdate: {revdate}

ifeval::["{build-type}" == "product"]
Esta sección proporciona las mejores prácticas para implementar GitOps con Turtles y Cluster API (CAPI), centrándose en el uso de https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/index.html[Continuous Delivery] en combinación con *Cluster API Addon Provider Fleet*(`+CAAPF+`) para automatizar el aprovisionamiento de agentes y la integración en el ecosistema `+CAPI+`.
endif::[]
ifeval::["{build-type}" == "community"]
Esta sección proporciona las mejores prácticas para implementar GitOps con Turtles y Cluster API (CAPI), centrándose en el uso de https://fleet.rancher.io/[Fleet] en combinación con *Cluster API Addon Provider Fleet*(`+CAAPF+`) para automatizar el aprovisionamiento de agentes y la integración en el ecosistema `+CAPI+`.
endif::[]

Estos consejos son transferibles y pueden aplicarse incluso cuando se utiliza una solución GitOps diferente.

== Consejos comunes

ifeval::["{build-type}" == "product"]
- **Clusters CAPI separados y configuraciones ClusterClass:**
  Mantenga las configuraciones de cluster CAPI (`+clusters/+`) distintas de las definiciones CAPI `+ClusterClass+` (`+templates/+`). Esta separación permite aprovisionar varios clústeres a partir de plantillas compartidas, reduciendo al mismo tiempo el riesgo de cambios involuntarios en la infraestructura.
- **Aislar configuraciones de addons:**
  Almacene los manifiestos de aplicación en `+applications/+`, asegurándose de que son independientes de `+Clusters+` y `+ClusterClasses+`. Esto permite el aprovisionamiento selectivo o agrupado en función de la demanda del usuario o de selectores coincidentes, evitando interferencias con la infraestructura del clúster. Tenga en cuenta que las dependencias del gráfico de Helm deben https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/gitrepo-content.html#_fleet_yaml[actualizarse en] antes del aprovisionamiento del complemento.
- **Utilizar recursos GitRepo anidados:**
  Aproveche los recursos anidados de https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/gitrepo-content.html#_nested_gitrepo_crs[] `+GitRepo+` en Fleet para estructurar eficazmente el contenido del repositorio. Este enfoque permite el aprovisionamiento modular, combinando las definiciones de `+ClusterClass+`, los complementos/aplicaciones necesarios y las configuraciones de clúster, al tiempo que se mantiene la separación de preocupaciones.
- **Utiliza las herramientas de integración de GitOps cuando estén disponibles:**
  Al configurar un sistema GitOps, ten en cuenta las herramientas disponibles y las funciones que ofrece. Un ejemplo de ello es https://rancher.github.io/cluster-api-addon-provider-fleet/00_intro.html[`+CAAPF+`]que automatiza la instalación de Fleet GitOps en los clústeres de `+CAPI+` y proporciona una cómoda automatización.
- **Aplique Kustomize Overlays para una personalización específica del entorno:**
  Utiliza `+overlays/+` para almacenar superposiciones Kustomize para distintos entornos. Esto garantiza que los cambios de configuración, como ajustes de escala, modificaciones de red o actualizaciones de componentes, puedan aplicarse dinámicamente sin alterar los manifiestos base.
- **Utilizar parches de comparación:**
  Fleet permite ignorar selectivamente las diferencias de recursos si el paquete contiene reglas adecuadas para la https://documentation.suse.com/cloudnative/continuous-delivery/v0.12/en/troubleshooting.html#_suse_rancher_prime_continuous_delivery_deployment_stuck_in_modified_state[detección de] Así se evitaría que los paquetes se quedaran bloqueados en un estado modificado.
endif::[]
ifeval::["{build-type}" == "community"]
- **Clusters CAPI separados y configuraciones ClusterClass:**
  Mantenga las configuraciones de cluster CAPI (`+clusters/+`) distintas de las definiciones CAPI `+ClusterClass+` (`+templates/+`). Esta separación permite aprovisionar varios clústeres a partir de plantillas compartidas, reduciendo al mismo tiempo el riesgo de cambios involuntarios en la infraestructura.
- **Aislar configuraciones de addons:**
  Almacene los manifiestos de aplicación en `+applications/+`, asegurándose de que son independientes de `+Clusters+` y `+ClusterClasses+`. Esto permite el aprovisionamiento selectivo o agrupado en función de la demanda del usuario o de selectores coincidentes, evitando interferencias con la infraestructura del clúster. Tenga en cuenta que las dependencias del gráfico de Helm deben https://fleet.rancher.io/gitrepo-content#fleetyaml[actualizarse en] antes del aprovisionamiento del complemento.
- **Utilizar recursos GitRepo anidados:**
  Aproveche los recursos anidados de https://fleet.rancher.io/gitrepo-content#nested-gitrepo-crs[] `+GitRepo+` en Fleet para estructurar eficazmente el contenido del repositorio. Este enfoque permite el aprovisionamiento modular, combinando las definiciones de `+ClusterClass+`, los complementos/aplicaciones necesarios y las configuraciones de clúster, al tiempo que se mantiene la separación de preocupaciones.
- **Utiliza las herramientas de integración de GitOps cuando estén disponibles:**
  Al configurar un sistema GitOps, ten en cuenta las herramientas disponibles y las funciones que ofrece. Un ejemplo de ello es https://rancher.github.io/cluster-api-addon-provider-fleet/00_intro.html[`+CAAPF+`]que automatiza la instalación de Fleet GitOps en los clústeres de `+CAPI+` y proporciona una cómoda automatización.
- **Aplique Kustomize Overlays para una personalización específica del entorno:**
  Utiliza `+overlays/+` para almacenar superposiciones Kustomize para distintos entornos. Esto garantiza que los cambios de configuración, como ajustes de escala, modificaciones de red o actualizaciones de componentes, puedan aplicarse dinámicamente sin alterar los manifiestos base.
- **Utilizar parches de comparación:**
  Fleet permite ignorar selectivamente las diferencias de recursos si el paquete contiene reglas adecuadas para la https://fleet.rancher.io/troubleshooting#fleet-deployment-stuck-in-modified-state[detección de] Así se evitaría que los paquetes se quedaran bloqueados en un estado modificado.
endif::[]

== Estrategia de separación de carpetas

Un repositorio bien estructurado simplifica la gestión y mejora la claridad. Se recomienda la siguiente estrategia de separación de carpetas:

----
repo-root/
│── fleet/
│   ├── providers/         # CAPIProvider files to use with templates
│   │   ├── core/          # Core provider configuration
│   │   ├── infra-docker/  # Docker provider configuration
│   │   ├── infra-aws/     # AWS provider configuration
│   ├── clusters/          # Cluster-specific configurations
│   │   ├── prod/          # Production clusters
│   │   ├── staging/       # Staging clusters
│   │   ├── dev/           # Development clusters
│   ├── addons/            # Application-specific manifests focused on cluster bootstrapping, like CNI, CCM, CPI configurations.
│   │   ├── cni/           # Group applications based on purpose. Provide fleet.yaml per each sub-directory to maintain bundle separation.
│   │   ├── ccm/
│   ├── templates/         # CAPI ClusterClass templates for cluster provisioning
│   ├── fleet.yaml         # Fleet bundle configuration
│── overlays/              # Kustomize overlays for different environments
│   ├── prod/.             # Kustomize overlays for production environments
│   ├── staging/.          # Kustomize overlays for staging environments
│   ├── dev/.              # Kustomize overlays for development environments
----

== Configuración de proveedores

Los proveedores CAPI definen los componentes de infraestructura necesarios para el aprovisionamiento de clusters. Una configuración sencilla puede tener este aspecto:

----
repo-root/
│── fleet/
│   ├── providers/
│   │   ├── core/
│   │   |   ├── core.yaml  # Core `+CAPIProvider+` definition
│   │   |   ├── fleet.yaml # Fleet.yaml definition for the provider setup
----

que contiene el proveedor principal:

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: cluster-api
spec:
  type: core
----

== Configuración de plantillas

Especifique `+dependsOn+` en `+fleet.yaml+` para paquetes específicos `+CAPIProvider+` o componentes externos `+GitRepo+`. Esto garantiza que las plantillas se desplieguen en el orden correcto y evita problemas cuando faltan controladores de componentes o no están preparados para aceptar definiciones de `+ClusterClass+`.

[source,yaml]
----
namespace: capa-clusters
dependsOn:
  - name: core      # Ensure core bundle is installed first
  - name: infra-aws # Wait for AWS provider installation
----

== Configuración de clusters

Utilice etiquetas para emparejar dinámicamente los clústeres con los complementos necesarios, lo que permite desplegar sólo las cargas de trabajo necesarias.

Ejemplo de uso de la etiqueta:

[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aws-cluster
  labels:
    cni: calico
    ccm: aws
    env: dev
----

[WARNING]
====
Se recomienda separar las definiciones de clúster de las plantillas, ya que la eliminación del paquete de clústeres permitiría al controlador CAPI procesar la eliminación en el orden correcto. La eliminación simultánea de `+Clusters+` y `+ClusterClasses+` puede producir resultados inesperados.
====

== Configuración del addon

La configuración de complementos es esencial para agilizar el aprovisionamiento de clústeres, garantizando que alcancen el estado `+Ready+` sin intervención manual ni herramientas de terceros.

Los complementos de clúster deben definir reglas de selección precisas para comparar con clústeres debidamente etiquetados.

El siguiente ejemplo muestra un clúster que requiere la instalación de `+Calico+` CNI y `+AWS+` Cloud Controller Manager (CCM):

[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aws-cluster
  labels:
    cni: calico
    ccm: aws
----

Esta configuración requiere dos recursos `+GitRepo+`, cada uno responsable del aprovisionamiento de complementos basados en etiquetas específicas: uno para `+cni: calico+` y otro para `+ccm: aws+`.

He aquí un ejemplo de recurso `+GitRepo+` para desplegar el CNI `+Calico+`:

[source,yaml]
----
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: calico
spec:
  branch: main
  paths:
  - /fleet/applications/calico
  repo: https://github.com/rancher-sandbox/cluster-api-addon-provider-fleet.git
  targets:
  - clusterSelector:
      matchLabels:
        cni: calico
        env: dev
----

Esto garantiza que el CNI `+Calico+` se despliegue únicamente en clústeres etiquetados con `+cni: calico+` y `+env: dev+`, lo que permite un aprovisionamiento selectivo del entorno.

=== Plantillas de valores del gráfico Helm

La configuración del complemento debe ajustar dinámicamente la carga de trabajo de `+Calico+` en función de la definición del clúster correspondiente y del estado específico del clúster. Para ello se puede utilizar una configuración de `+fleet.yaml+`, similar a la siguiente estructura:

----
repo-root/
│── fleet/
│   ├── applications/
│   │   ├── calico/
│   │   │   ├── fleet.yaml # Fleet configuration for the Calico setup
----

El archivo `+fleet.yaml+` define las reglas de planificación y `+comparePatches+` para garantizar un despliegue sin problemas, independientemente de la configuración del clúster. Para obtener más información sobre las plantillas de `+CAAPF+`, que se utilizan aquí, consulte la oficial https://rancher.github.io/cluster-api-addon-provider-fleet/04_reference/02_templating-strategy.html[documentación].

[source,yaml]
----
helm:
  releaseName: projectcalico
  repo: https://docs.tigera.io/calico/charts
  chart: tigera-operator
  templateValues:
    installation: |-
      cni:
        type: Calico
        ipam:
          type: HostLocal
      calicoNetwork:
        bgp: Disabled
        mtu: 1350
        ipPools:
          ${- range $cidr := .ClusterValues.Cluster.spec.clusterNetwork.pods.cidrBlocks }
          - cidr: "${ $cidr }"
            encapsulation: None
            natOutgoing: Enabled
            nodeSelector: all()${- end}

diff:
  comparePatches:
  - apiVersion: operator.tigera.io/v1
    kind: Installation
    name: default
    operations:
    - {"op":"remove", "path":"/spec/kubernetesProvider"}
----
