include::partial$variables.adoc[]
= Spezifikation der Host-Fähigkeiten
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Machen Sie sich während der Evaluierung mit den Host-Funktionen vertraut, die die Umgebung für die Richtlinien von {project-name} bietet.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "introduction"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "policy specification", "host capabilities"]
:sidebar_label: Spezifikation der Host-Fähigkeiten
:current-version: {page-origin-branch}

Während der Evaluierung können die Richtlinien von {project-name} auf zusätzliche Funktionen zugreifen, die von der Host-Umgebung angeboten werden.
Dieser Mechanismus verwendet einen ähnlichen Ansatz wie die traditionellehttps://en.wikipedia.org/wiki/Remote_procedure_call[] RPC.

Dies ist der Fall, wenn ein Antrag von einer {short-project-name} -Police gestellt wird:

* {short-project-name} Politik:
 ** Ruft die von der Host-Umgebung angebotene Fähigkeit auf.
 ** Der Aufruf ist ein blockierender Vorgang, d. h. der Richtliniencode wartet, bis der Host eine Antwort gibt.
* Host-Umgebung:
 ** Ein Fähigkeitsaufruf wird empfangen.
 ** Der Host führt den Vorgang aus.
 ** Der Gastgeber gibt eine Antwort auf die Richtlinie, die entweder ein Erfolg oder ein Misserfolg sein kann.
* {short-project-name} Politik:
 ** Der Code erhält die Antwort vom Host und setzt die Ausführung fort.
 ** Die Antwort des Hosts wird entsprechend behandelt.

Die Funktion der Host-Fähigkeiten wird mithttps://wapc.io/[waPC] implementiert.
Jede Fähigkeit verwendet diese Details:

* Name der waPC-Funktion: Der Name der vom Host zur Verfügung gestellten Fähigkeit.
* Eingabe-Nutzlast: Der Hauptteil des Antrags, der von der Richtlinie gestellt wird.
Diese wird immer im JSON-Format kodiert.
* Ausgabe-Nutzlast: Der Text der Antwort, die vom Host kommt. Diese wird immer im JSON-Format kodiert.

Wenn etwas schief geht, antwortet der Host mit einer Fehlermeldung.
Dies geschieht unter Verwendung des Fehlertyps der von der Richtlinie verwendeten Programmiersprache.
Der Fehler ist eine UTF-8-Zeichenfolge, die eine Erklärungsmeldung enthält.
