include::partial$variables.adoc[]
= Richtlinien für die Unterschriftenprüfung
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Implementieren Sie sichere Richtlinien für Ihren Cluster mit der mitgelieferten Überprüfungsrichtlinie oder bauen Sie darauf mit dem SDK Ihrer Sprache auf.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "signature-verifier-policies"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "policy specification", "signature verifier"]
:sidebar_label: Richtlinien für die Unterschriftenprüfung
:current-version: {page-origin-branch}

{project-name} implementiert Unterstützung für dashttps://www.sigstore.dev/[Sigstore-Projekt].
Dies ermöglicht die Implementierung einer "sicheren Lieferkette" für Ihr Cluster.

Ein Teil der Funktion der sicheren Lieferkette besteht darin, sicherzustellen, dass alle im Cluster laufenden Container-Images signiert und verifiziert sind.
Dies beweist, dass sie von den angegebenen Autoren stammen und nicht manipuliert wurden.
Weitere Informationen finden Sie in den Dokumenten zurxref:/howtos/security-hardening/secure-supply-chain.adoc[Implementierung einer sicheren Lieferkette für die Richtlinien selbst].

Sigstore-Signaturen werden in den Container-Registries neben dem zu signierenden OCI-Objekt gespeichert.
Dabei kann es sich um ein Container-Image oder ein allgemeineres OCI-Artefakt handeln, z. B. eine {short-project-name} -Richtlinie.
Wenn ein Objekt signiert wird, werden seine Signaturen als Schichten eines von Sigstore erstellten OCI-Objekts gespeichert.
Richtlinien, die die Signaturen von Containern prüfen müssen, müssen diese Schichten prüfen und die Signaturschichten ziehen, um die Signaturen selbst zu prüfen.

Das Abrufen und Arbeiten mit diesen OCI-Schichten muss außerhalb des WebAssembly-Gastes (der Richtlinie) erfolgen.
Daher wird dies von der WebAssembly-Laufzeit,{short-project-name}'s `+policy-server+` oder `+kwctl+` getan.

Die verschiedenen Sprach-SDKs für {short-project-name} Policen kümmern sich um diese Aufgabe.
Sie bieten Funktionen zur Überprüfung von Container-Images,{short-project-name} Policies, Helm-Charts und anderen Arten von OCI-Artefakten.
Dies gewährleistet einen sicheren und getesteten Codepfad für die Überprüfung.

Das Abrufen von Daten aus einer Registrierung und die kryptografische Überprüfung von Signaturen kann zeit- und rechenaufwändig sein, weshalb die WebAssembly-Laufzeitumgebung (PolicyServer, `+kwctl+`) sicherstellt, dass sowohl das Abrufen von Signaturen als auch die Verifizierungsberechnungen zwischengespeichert werden.
Die zwischengespeicherten Einträge werden automatisch nach 60 Sekunden gelöscht, um zu verhindern, dass veraltete Daten geliefert werden.

== Caching

Die Ergebnisse der Signaturprüfung werden für eine Minute zwischengespeichert.

Die SDKs bieten ähnliche Funktionen wie die folgenden:

* {blank}
+
[subs="+attributes",rust]
----
verify_pub_keys_image(
    image_url: string,
    vector_of_pub_keys: vector<string>,
    vector_of_sigstore_annotations: Vector<(key, value: string)>
    )
    returns (is_trusted: bool, digest_of_verified_image: string)
----

* {blank}
+
[subs="+attributes",rust]
----
verify_keyless_exact_match(
    image_url: string,
    vector_of_tuples_issuer_and_subject: vector<(issuer, subject: string)>,
    vector_of_sigstore_annotations: vector<(key, value: string)>
    )
    returns (is_trusted: bool, digest_of_verified_image: string)
----

Beide Funktionen überprüfen, ob das Bild signiert ist und die Bedingungen erfüllt.

[NOTE]
====
Bei Erfolg geben die Funktionen den Digest des verifizierten Bildes zurück.
Es liegt nun in der Verantwortung der Richtlinie, sicherzustellen, dass Container auf der Grundlage dieser Prüfsumme instanziiert werden und nicht auf der Grundlage eines Tags, das möglicherweise nicht mit der Prüfsumme übereinstimmt (und daher kompromittiert ist).
====


== Ein Beispiel

Das Team von {short-project-name}https://github.com/kubewarden/verify-image-signatures[ bietet eine Verifizierungsrichtlinie], die Sigstore-Signaturen für alle Container erzwingt.
Es wurde mit Rust und dem Rust SDK entwickelt.
Die Richtlinie stellt sicher, dass die Container signiert sind, und mutiert optional die Anfragen. Bei der Mutation wird die geprüfte Prüfsumme an den Tag des Bildes angehängt.
Weitere Informationen finden Sie in der Dokumentation.

Diese Richtlinie kann alle Ihre Bedürfnisse abdecken, aber falls Sie eine andere UX bevorzugen, können Sie natürlich darauf oder auf eines der anderen SDKs aufbauen.

== WaPC-Protokoll-Vertrag

Falls Sie Ihr eigenes Sprach-SDK implementieren, sind dies die Funktionen, die eine Richtlinie, die Signaturen prüft, verwenden kann:

=== waPC-Funktion - `+v2/verify+`

==== `+SigstorePubKeyVerify+` Eingabe

[,hcl]
----
{
  type: "SigstorePubKeyVerify",

  # **mandatory**: image URI to verify
  "image": string,
  "pub_keys": [
    # PEM-encoded public keys
    string
    ],
  # optional:
  "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
}
----

==== `+SigstorePubKeyVerify+` Ausgabe

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessVerify+` Eingabe

[,hcl]
----
{
  type: "SigstoreKeylessVerify",

  # mandatory: image URI to verify
  "image": string,
  "keyless": [
    # list of (issuer, subject) tuples
    {
      # OIDC issuer
      "issuer": string,
      # signature subject (mail, CI URL, ...)
      "subject": string
    }
  ],
  # optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreKeylessVerify+` Ausgabe

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessPrefixVerify+` Eingabe

[,hcl]
----
{
  type: "SigstoreKeylessPrefixVerify",

  # mandatory: image URI to verify
  "image": string,
  "keyless_prefix": [
    # list of (issuer, url_prefix) tuples
    {
      # OIDC issuer
      "issuer": string,
      # URL Prefix of subject (CI URL, ...)
      "url_prefix": string
    }
  ],
  # optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreKeylessPrefixVerify+` Ausgabe

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreGithubActionsVerify+` Eingabe

[,hcl]
----
{
  type: "SigstoreGithubActionsVerify",

  # mandatory: image URI to verify
  "image": string,
  # GitHub owner
  "owner": string,
  # optional:
  # GitHub repository
  "repo": string
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreGithubActionsVerify+` Ausgabe

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreCertificateVerify+` Eingabe

[,hcl]
----
{
  type: "SigstoreCertificateVerify",

  # mandatory: image URI to verify
  "image": string,
  # PEM-encoded certificated used to
  # verify the signature.
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM encoded
  # certificate string.
  "certificate": [byte(int), ..., byte(int)],
  # Optional - certificate chain used to
  # verify the provided certificate.
  # When not specified, the certificate
  # is assumed to be trusted.
  # The certificate is UTF-8 encoded.
  # It's an array of bytes of the unicode code pointers of a PEM encoded
  # certificate string.
  "certificate_chain": [
    [byte(int), ..., byte(int)],
    ...
    [byte(int), ..., byte(int)]
  ],
  # Require the signature layer to have
  # a Rekor bundle.
  # Having a Rekor bundle allows further
  # checks to be performed, e.g. ensuring
  # the signature has been produced during
  # the validity time frame of the cert.
  # Recommended to set to `+true+`
  require_rekor_bundle: bool,
  # Optional:
  "annotations": [
    # signature annotations
    {
      "key": string,
      "value": string
    },
  ]
}
----

==== `+SigstoreCertificateVerify+` Ausgabe

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

=== waPC-Funktion - `+v1/verify+`

==== `+SigstorePubKeyVerify+` Eingabe

[,hcl]
----
{
  "SigstorePubKeyVerify": {
    # **mandatory**: image URI to verify
    "image": string,
    "pub_keys": [
      # PEM-encoded public keys
      string
    ],
    # optional:
    "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
  }
}
----

==== `+SigstorePubKeyVerify+` Ausgabe

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----

==== `+SigstoreKeylessVerify+` Eingabe

[,hcl]
----
{
  "SigstoreKeylessVerify": {
    # mandatory: image URI to verify
    "image": string,
    "keyless": [
      # list of (issuer, subject) tuples
      {
        # OIDC issuer
        "issuer": string,
        # signature subject (mail, CI URL, ...)
        "subject": string
      }
    ],
    # optional:
    "annotations": [
      # signature annotations
      {
        "key": string,
        "value": string
      },
    ]
  }
}
----

==== `+SigstoreKeylessVerify+` Ausgabe

[,hcl]
----
{
   # true if image verified
   "is_trusted": boolean,
   # digest of verified image
   "digest": string
}
----
