include::partial$variables.adoc[]
= Fähigkeiten des Netzes
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Lernen Sie die Netzwerkfähigkeiten kennen und erfahren Sie, wie Sie die Hostfunktionen für DNS-Suchvorgänge und Kommunikationsprotokolle nutzen können.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "host-capabilities", "network-capabilities"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "policy specification", "network capabilities"]
:sidebar_label: Fähigkeiten des Netzes
:current-version: {page-origin-branch}

{project-name} Richtlinien können keine Netzwerkanfragen aus dem WebAssembly-Ausführungskontext heraus stellen.

Netzwerkoperationen können durch die Nutzung einer Reihe von Fähigkeiten durchgeführt werden, die der Host zur Verfügung stellt.

== DNS-Hostabfrage

Diese Funktion führt eine DNS-Suche ausgehend von dem in der Richtlinie angegebenen FQDN durch.

=== Caching

Nachschlageergebnisse werden 1 Minute lang zwischengespeichert.

=== Kommunikationsprotokoll

Dies ist die Beschreibung des waPC-Protokolls, das verwendet wird, um diese Fähigkeit darzustellen:

==== waPC-Funktion - `+v1/dns_lookup_host+` Eingabe

[,hcl]
----
# hostname - JSON encoded string
string
----

==== waPC-Funktion - `+v1/dns_lookup_host+` Ausgabe

[,hcl]
----

{
  # list of IPs
  "ips": [string]
}
----

Alle IP-Adressen, die mit dem angegebenen FQDN verbunden sind, werden als Zeichenketten in der Antwort zurückgegeben.
Sowohl IPv4- als auch IPv6-Einträge werden als Teil der gleichen Antwort zurückgegeben.

Bei der Abfrage des Manifest-Digest des`+busybox:latest+` -Images würden die Nutzdaten beispielsweise wie folgt lauten:

* Eingabe-Nutzlast: `+"google.com"+`
* Ausgabe-Nutzlast: `+{ "ips": ["127.0.0.1"]}+`
