= Monitores
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

O SUSE Observability tem as práticas recomendadas codificadas por meio de monitores. Os monitores do SUSE Observability não apenas monitoram métricas, eventos ou registros, mas também podem monitorar a topologia e os metadados para detectar problemas comuns, garantindo a conformidade e a adesão aos padrões do setor.
Combinando monitores com nossa exclusiva inteligência de solução de problemas, o SUSE Observability detecta rapidamente problemas relacionados e orienta sobre como corrigi-los. Essa abordagem proativa reduz o risco de problemas não detectados e ajuda a manter um ambiente Kubernetes saudável e robusto.
Os monitores são acompanhados de guias de correção específicos para o recurso alertado e para a condição monitorada, a fim de orientar nossos usuários na solução de problemas.

== Monitorar resultados

Os resultados do monitor são exibidos em dois locais:

. Nas páginas de destaque de todos os recursos para ver imediatamente o que está acontecendo e como corrigi-lo.
. No painel do lado direito, se você selecionar um elemento na topologia, terá uma indicação rápida dos problemas desse componente.

== Guias de remediação

Os guias de correção são mostrados na gaveta Status do Monitor, que é exibida se você abrir um monitor clicando na mensagem na perspectiva de Destaque de um recurso.

== Veja também

* xref:/use/alerting/kubernetes-monitors.adoc[Monitores prontos para uso no Kubernetes]
