= Monitores de limiar dinâmico
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

== Visão geral

Para métricas que variam significativamente ao longo do tempo e diferem de serviço para serviço, um monitor Dynamic Threshold oferece detecção de anomalias simples e eficiente.  Ele usa dados de 1, 2 ou 3 semanas atrás, além do passado recente, como contexto para comparar os dados atuais.

Os dados da "janela de verificação" são comparados com os dados fornecidos pelo contexto histórico usando o teste de Anderson-Darling.  Isso impõe muito poucas suposições sobre a distribuição de dados.  O teste é particularmente sensível a valores discrepantes nas extremidades superior e inferior da distribuição.  A métrica pode ser suave, pontiaguda ou ter alguns "níveis". Como os valores dos dados são comparados diretamente, sem nenhum ajuste de modelo, o monitor Dynamic Threshod é muito robusto.

Para métricas que variam suavemente ao longo do tempo (por exemplo, em uma escala de tempo de 5 minutos), o número efetivo de pontos de dados é menor do que o número bruto.  O DT compensa isso para que o mesmo monitor possa ser usado para uma ampla gama de métricas sem a necessidade de ajustar seus parâmetros.

Há alguns parâmetros que podem ser definidos para a função de monitor:

* `+falsePositiveRate+`: digamos `+!!float 1e-8+` - a sensibilidade do monitor a desvios de comportamento.  Um valor mais baixo suprime mais (falsos) positivos, mas também pode levar a falsos negativos (anomalias não percebidas).
* `+checkWindowMinutes+`: digamos `+10+` minutos - a janela de verificação precisa ser equilibrada entre alertas rápidos (valores pequenos) e anomalias corretamente identificadas (valores altos).  Um punhado de pontos de dados funciona bem na prática.
* `+historicWindowMinutes+`: digamos `+120+` (2 horas) - entre parênteses em torno do horário atual, mas uma ou mais semanas atrás - portanto, de 1 hora antes do horário atual a 1 hora depois.  Também são usadas as duas horas anteriores à janela de verificação.  O monitor de limite dinâmico compara a distribuição desses dados históricos com os pontos de dados na janela de verificação.
* `+historySizeWeeks+`: diga `+2+` - o número de semanas das quais os dados são extraídos para o contexto histórico.  Pode ser `+1+`, `+2+` ou `+3+`.
* `+removeTrend+`Para métricas que têm comportamento de tendência (por exemplo, número de solicitações), de modo que o valor absoluto difere de uma semana para outra, essa tendência (o valor médio) pode ser levada em conta.
* `+includePreviousDay+`: normalmente `+false+` - para métricas que não têm um padrão semanal, mas apenas diário, isso permite o uso de dados mais recentes

== Exemplo de monitor de limiar dinâmico

Um Monitor implementado usando a função Dynamic Threshold tem a seguinte aparência:

----
  - _type: "Monitor"
    name: "<name of the monitor>"
    identifier: "urn:custom:monitor:<identifier for the monitor>"
    status: "DISABLED"
    description: "<description>"
    function: {{ get "urn:stackpack:aad-v2:shared:monitor-function:dt" }}
    arguments:
      telemetryQuery:
        query: "<metric to bind to component>"
        unit: s
        aliasTemplate: "<name for the metric>"
      topologyQuery: <topology query for the components to bind to>
      falsePositiveRate: <floating point number, e.g. !!float 1e-8>
      checkWindowMinutes: <integer, e.g. 10>
      historicWindowMinutes: <integer, e.g. 120>
      historySizeWeeks: <integer: 1, 2 or 3>
      includePreviousDay: <boolean>
      removeTrend: <boolean>
    intervalSeconds: 60
    remediationHint: "<how to remediate deviating states>"
----

O monitor pode ser implementado usando o guia em xref:/use/alerting/k8s-add-monitors-cli.adoc[Adicionar um monitor de limite aos componentes usando a CLI]
