= カスタムメトリックチャートのトラブルシューティング
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 概要

* <<_the_metric_chart_doesnt_show_on_the_highlights_page_of_a_component,コンポーネントのハイライト・ページにメトリクス・チャートが表示されない>>
* <<_the_metric_chart_doesnt_show_on_the_metrics_perspective_of_a_component,コンポーネントのメトリクス・パースペクティブにメトリクス・チャートが表示されない。>>
* <<_the_metric_chart_on_a_component_remains_empty_no_data,コンポーネントのメトリクスチャートが空のまま（「データがない」）。>>

== コンポーネントのハイライト・ページにメトリクス・チャートが表示されない

現時点では、コンポーネント・ハイライト・ページに表示される指標チャートをカスタマイズすることはできません。カスタムメトリックバインディングのチャートは、Metricsパースペクティブにのみ表示されます。

== コンポーネントのメトリクス・パースペクティブにメトリクス・チャートが表示されない。

メトリックバインディングの`scope` クエリは、コンポーネントがメトリックバインディングを表示するかどうかを決定するために使用される。コンポーネントがメトリックバインディングを示さない場合は、スコープ内のトポロジークエリーがコンポーネントにマッチするかどうかをチェックする。

名前とタイプは一番上にあり、ラベルは "About "セクションにあります。ラベル名や値にスペルミスがないことを確認する。

スコープクエリが正しい構文であることを確認する：

. メニューの "Views "と右側の青い "Explore "ボタンからエクスプローラービューを開く。またはURLから直接： `https://<your-stackstate-instance>/#/views/explore`
. フィルターを開き `switch to STQL`
. スコープからSTQLフィールドにクエリをコピー/ペーストし、クエリを実行します。

概要には、クエリにマッチし、チャートを取得するすべてのコンポーネントが表示されます。

== コンポーネントのメトリクスチャートが空のまま（「データがない」）。

データが期待されていたのにデータがないメトリックス・チャートについては、インスペクタ（チャートの右上隅にあるアイコン）を開く。クエリを表示するには、"クエリを表示 "ボタンを切り替えます。

クエリにパラメータが含まれていないことを確認してください（つまり、`${tags.cluster-name}` や`${name}` のようなすべての値が、コンポーネントの値に置き換えられています）。クエリにいくつかのパラメータが残っていた場合、ラベルはこのコンポーネントでは使用できません。そのため、使用されている名前（この例では`cluster-name` ）と、コンポーネント上で使用可能なラベルを照合する。また、名前に誤字がないことも確認する。

すべてのパラメータが入力されている場合、PromQLクエリに問題がある可能性があります。これを調べるには、PromQLクエリをコピーして、Metricsエクスプローラを開きます（SUSE Observabilityのメインメニューから）。クエリをメトリックエクスプローラに貼り付けて実行する。これでも空の結果が出るはずだ。

メトリックが存在しないか、ラベルが1つもないか、ラベルは存在するがその値に一致する時系列がないかのいずれかである。これを解決する最速の方法は、クエリをメトリック名だけに書き換えて実行することです。テーブルの結果は、使用されるラベルがすべて存在することを確認するためにも使用できる。ここにも誤字がないように。

結果はあるが、ラベルの特定の値（例えば、`pod_name` ）に対するものではない場合、クエリはOKだが、この特定のコンポーネントのこの特定の指標の時系列はない。この場合、確認すべきことがある：

* このコンポーネントのデータは収集されていますか(SUSE Observabilityエージェントまたはその他の手段で)。
* そのコンポーネントはその指標を報告しているのか？

これをどのように行うかは、データ収集がどのように設定されているかによる。
