include::partial$variables.adoc[]
= Registro
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure las capacidades de registro para su política utilizando la integración de {project-name} con la biblioteca SLOG e inicializando.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "logging"]
:doc-type: ["tutorial"]
:keywords: ["{project-name}", kubewarden, "kubernetes", "logging"]
:sidebar_label: Registro
:current-version: {page-origin-branch}

Puede hacer que su política realice el registro.
`+policy-server+` o `+kwctl+` reenvía esas entradas de registro con la información adecuada.

La biblioteca de registro elegida para el SDK de Rust eshttps://github.com/slog-rs/slog[`+slog+`].
Es un cajón popular y bien conocido y se integra limpiamente con {project-name}.

== Inicializar registrador

El proyecto recomienda crear un sumidero global al que se pueda acceder, desde donde sea necesario en su política.
Para ello, utilice la caja `+lazy_static+`:

[subs="+attributes",rust]
----
use slog::{o, Logger};

lazy_static! {
    static ref LOG_DRAIN: Logger = Logger::root(
        logging::KubewardenDrain::new(),
        o!("policy" => "sample-policy")
    );
}
----

== Consumir el registrador

Ahora, desde las funciones `+validate+`, o `+validate_settings+`, puede registrar utilizando las macros exportadas por `+slog+` que coincidan con cada nivel de registro admitido:

[subs="+attributes",rust]
----
use slog::{info, o, warn, Logger};

fn validate(payload: &[u8]) -> CallResult {
    // ...
    info!(LOG_DRAIN, "starting validation");
    // ...
    warn!(
        LOG_DRAIN, "structured log";
        "some_resource_name" => &some_resource_name
    );
    // ...
}
----

La biblioteca `+slog+` envía todos los registros al sumidero inicializado en la variable global.
Esto se sincroniza con el evaluador de políticas que ejecuta la política.
Esto es `+kwctl+` o el `+policy-server+`.
A continuación, el evaluador de políticas registra esta información, añadiendo más información contextual conocida, como la solicitud de Kubernetes `+uid+`.

Encontrará más información sobrehttps://docs.rs/slog/2.7.0/slog/macro.log.html[las macros de registro]que ofrece slog en suhttps://docs.rs/slog/2.7.0/slog/index.html[].
