include::partial$variables.adoc[]
= Elaboración y distribución de políticas
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Siga estos pasos esenciales para crear y distribuir políticas de forma eficaz para su configuración de {project-name}.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "build-and-distribute"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "rust", "build and distribute"]
:sidebar_label: Elaboración y distribución de políticas
:current-version: {page-origin-branch}

== Construir la política

Hasta ahora, has construido la política con un objetivo de compilación del mismo sistema operativo y arquitectura de tu máquina de desarrollo.

Ahora es el momento de construir la política como un binario WebAssembly, un archivo `+.wasm+`.

Utiliza el comando:

[subs="+attributes",console]
----
make policy.wasm
----

Este comando construye el código en modo release, con un objetivo de compilación WebAssembly.

La compilación produce un archivo `+policy.wasm+`:

[subs="+attributes",console]
----
$ file policy.wasm
policy.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
----

== Difusión de la política

{project-name} documenta la distribución de políticas en la sección dexref:../../../explanations/distributing-policies.adoc[distribución de políticas].

== Más ejemplos

Puedes encontrar más políticas de Rust {short-project-name} en {short-project-name}'s GitHub space.https://github.com/search?l=Rust&q=topic%3Apolicy-as-code+org%3Akubewarden&type=Repositories[Esta consulta] puede ayudarte a encontrarlas.

Los repositorios de políticas {short-project-name}, mostrados por esa consulta, tienen Acciones GitHub que automatizan las siguientes tareas:

* Ejecutar pruebas unitarias y el código de pelusa en pull requests y después de las fusiones de código en la rama principal.
* Cree la política en el modo `+release+` y envíela a un registro OCI como artefacto.
