= Exposer SUSE Observability en dehors de la grappe
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Auto-hébergé

== Vue d'ensemble

{stackstate-product-name} peut être exposée avec une ressource Kubernetes Ingress. Les exemples de cette page montrent comment configurer un contrôleur Traefik ou Nginx Ingress à l'aide de xref:/setup/install-stackstate/kubernetes_openshift/ingress.adoc#_configure_ingress_via_the_suse_observability_helm_chart[Helm pour SUSE Observability fonctionnant sur Kubernetes]. Cette page indique également la combinaison service/port à exposer en cas d'utilisation d'une méthode différente de configuration du trafic entrant.

En observant le cluster qui héberge également {stackstate-product-name}, le trafic de l'agent peut être maintenu entièrement dans le cluster lui-même en xref:/setup/install-stackstate/kubernetes_openshift/ingress.adoc#_agents_in_the_same_cluster[changeant la configuration de l'agent] lors de son installation.

== Configurer l'entrée via le tableau {stackstate-product-name} Helm

La carte {stackstate-product-name} Helm présente une section `ingress` dans ses valeurs. Cette fonction est désactivée par défaut. Les exemples ci-dessous montrent comment utiliser le tableau Helm pour configurer un contrôleur d'entrée avec le cryptage TLS activé. Il est à noter que la configuration du contrôleur lui-même et des certificats dépasse le cadre de ce document.

Pour configurer l'entrée pour {stackstate-product-name}, créez un fichier `ingress_values.yaml` avec un contenu comme ci-dessous. Remplacez `MY_DOMAIN` par votre propre domaine (qui est lié à votre contrôleur d'entrée) et définissez le nom correct pour `tls-secret`. Consultez la documentation de votre contrôleur d'entrée pour connaître les annotations correctes à définir. Tous les champs ci-dessous sont facultatifs. Par exemple, si le protocole TLS n'est pas utilisé, omettez cette section, mais sachez que {stackstate-product-name} ne crypte pas non plus le trafic.

[CAUTION]
====
Notez que la configuration de TLS est nécessaire pour l'utilisation de l'extension rancher UI.
====

[tabs]
====
Traefik::
+
--
.Problèmes connus
[WARNING]
=====
Assurez-vous d'utiliser Traefik < 3.6.3 or >= 3.6.7 (avec la version de la carte Helm >= 39.0.0), car les versions 3.6.3 à 3.6.6 ont un problème qui provoque des erreurs sur certains points d'extrémité de l'API. En particulier, les pages de mise en évidence des composants ne se chargent pas car les appels API sont bloqués par Traefik avec une erreur `400 Bad Request`.
=====

[,text]
----
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: suse-observability.MY_DOMAIN
  tls:
    - hosts:
        - suse-observability.MY_DOMAIN
      secretName: tls-secret
----
--

Nginx Ingress::
+
--
[NOTE]
=====
Le projet Ingress Nginx https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/[est]. Il est conseillé aux utilisateurs d'envisager des solutions alternatives telles que Traefik.
=====

[,text]
----
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: suse-observability.MY_DOMAIN
  tls:
    - hosts:
        - suse-observability.MY_DOMAIN
      secretName: tls-secret
----

Ce qui ressort de ce fichier, c'est l'annotation de Nginx visant à augmenter la valeur autorisée de `proxy-body-size` à `50m` (plus grande que toute demande attendue). Par défaut, Nginx autorise des corps d'une taille maximale de `1m`. {stackstate-product-name} Les agents et autres fournisseurs de données peuvent parfois envoyer des demandes beaucoup plus importantes. C'est pourquoi vous devez vous assurer que la taille du corps autorisée est suffisamment grande, que vous utilisiez Nginx ou un autre contrôleur d'entrée.
--
====

Veillez à mettre à jour l'adresse `baseUrl` dans le fichier de valeurs généré lors de l'installation initiale, car elle sera utilisée par {stackstate-product-name} pour générer des instructions d'installation pratiques pour l'agent.

Les exemples utilisent le champ `ingressClassName` pour spécifier l' https://kubernetes.io/docs/concepts/services-networking/ingress/#_ingress_class[entrée] au lieu de l'annotation obsolète `kubernetes.io/ingress.class`. Si une classe d'entrée par défaut est définie dans votre cluster, le champ "ingress class name" (nom de la classe d'entrée) peut être omis.
Les exemples utilisent le champ `ingressClassName` pour spécifier l' https://kubernetes.io/docs/concepts/services-networking/ingress/#_ingress_class[entrée] au lieu de l'annotation obsolète `kubernetes.io/ingress.class`. Si une classe d'entrée par défaut est définie dans votre cluster, le champ "ingress class name" (nom de la classe d'entrée) peut être omis.

Incluez le fichier `ingress_values.yaml` lorsque vous exécutez la commande `helm upgrade` pour déployer {stackstate-product-name}:

[,text]
----
helm upgrade --install \
  --namespace "suse-observability" \
  --values "ingress_values.yaml" \
  --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
suse-observability \
suse-observability/suse-observability
----

[NOTE]
====
Cette étape suppose que xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_generate_baseconfig_values.yaml_and_sizing_values.yaml[Generate `baseConfig_values.yaml` et `sizing_values.yaml`] a déjà été exécuté.
====

== Configuration de la règle d'entrée pour la télémétrie ouverte

La carte {stackstate-product-name} Helm expose un service `opentelemetry-collector` dans ses valeurs où un `ingress` dédié peut être créé. Cette fonction est désactivée par défaut. L'entrée nécessaire pour `opentelemetry-collector` doit prendre en charge le protocole GRPC. Il est à noter que la configuration du contrôleur lui-même et des certificats dépasse le cadre de ce document.

Pour configurer l'entrée `opentelemetry-collector` pour {stackstate-product-name}, créez un fichier `ingress_otel_values.yaml` dont le contenu est le suivant. Remplacez `MY_DOMAIN` par votre propre domaine (qui est lié à votre contrôleur d'entrée) et définissez le nom correct pour `otlp-tls-secret`. Consultez la documentation de votre contrôleur d'entrée pour connaître les annotations correctes à définir. Tous les champs ci-dessous sont facultatifs. Par exemple, si le protocole TLS n'est pas utilisé, omettez cette section, mais sachez que {stackstate-product-name} ne crypte pas non plus le trafic.

[tabs]
====
Traefik::
+
--
.Problèmes connus
[WARNING]
=====
Assurez-vous d'utiliser Traefik < 3.6.3 or >= 3.6.7 (avec la version de la carte Helm >= 39.0.0), car les versions 3.6.3 à 3.6.6 ont un problème qui provoque des erreurs sur certains points d'extrémité de l'API. En particulier, les pages de mise en évidence des composants ne se chargent pas car les appels API sont bloqués par Traefik avec une erreur `400 Bad Request`.
=====

[NOTE]
=====
L'exposition du point d'extrémité OpenTelemetry Collector GRPC via Traefik est prise en charge à partir de {stackstate-product-name} Helm chart version v2.8.0.

Notez que l'entrée de l'hôte GRPC nécessite une adresse explicite `serviceName: suse-observability-otel-collector-grpc` pour acheminer le trafic vers le bon service de base.
=====

[,text]
----
opentelemetry-collector:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: otlp-suse-observability.MY_DOMAIN
        paths:
          - path: /
            pathType: Prefix
            serviceName: suse-observability-otel-collector-grpc
            port: 4317
    tls:
      - hosts:
          - otlp-suse-observability.MY_DOMAIN
        secretName: otlp-tls-secret
    additionalIngresses:
      - name: otlp-http
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: otlp-http-suse-observability.MY_DOMAIN
            paths:
              - path: /
                pathType: Prefix
                port: 4318
        tls:
          - hosts:
              - otlp-http-suse-observability.MY_DOMAIN
            secretName: otlp-http-tls-secret
----
--

Nginx Ingress::
+
--
[NOTE]
=====
Le projet Ingress Nginx https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/[est]. Il est conseillé aux utilisateurs d'envisager des solutions alternatives telles que Traefik.
=====

[,text]
----
opentelemetry-collector:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
    hosts:
      - host: otlp-suse-observability.MY_DOMAIN
      - host: otlp-suse-observability.MY_DOMAIN
        paths:
          - path: /
            pathType: Prefix
            port: 4317
    tls:
      - hosts:
          - otlp-suse-observability.MY_DOMAIN
          - otlp-suse-observability.MY_DOMAIN
        secretName: otlp-tls-secret
    additionalIngresses:
      - name: otlp-http
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        hosts:
          - host: otlp-http-suse-observability.MY_DOMAIN
          - host: otlp-http-suse-observability.MY_DOMAIN
            paths:
              - path: /
                pathType: Prefix
                port: 4318
        tls:
          - hosts:
              - otlp-http-suse-observability.MY_DOMAIN
              - otlp-http-suse-observability.MY_DOMAIN
            secretName: otlp-http-tls-secret
----

Ce qui ressort de ce fichier, c'est l'annotation de Nginx visant à augmenter la valeur autorisée de `proxy-body-size` à `50m` (plus grande que toute demande attendue). Par défaut, Nginx autorise des corps d'une taille maximale de `1m`. {stackstate-product-name} Les agents et autres fournisseurs de données peuvent parfois envoyer des demandes beaucoup plus importantes. C'est pourquoi vous devez vous assurer que la taille du corps autorisée est suffisamment grande, que vous utilisiez Nginx ou un autre contrôleur d'entrée.
--
====

Veillez à mettre à jour l'adresse `baseUrl` dans le fichier de valeurs généré lors de l'installation initiale, car elle sera utilisée par {stackstate-product-name} pour générer des instructions d'installation pratiques pour l'agent.

Les exemples utilisent le champ `ingressClassName` pour spécifier l' https://kubernetes.io/docs/concepts/services-networking/ingress/#_ingress_class[entrée] au lieu de l'annotation obsolète `kubernetes.io/ingress.class`. Si une classe d'entrée par défaut est définie dans votre cluster, le champ "ingress class name" (nom de la classe d'entrée) peut être omis.
Les exemples utilisent le champ `ingressClassName` pour spécifier l' https://kubernetes.io/docs/concepts/services-networking/ingress/#_ingress_class[entrée] au lieu de l'annotation obsolète `kubernetes.io/ingress.class`. Si une classe d'entrée par défaut est définie dans votre cluster, le champ "ingress class name" (nom de la classe d'entrée) peut être omis.

Incluez le fichier `ingress_otel_values.yaml` lorsque vous exécutez la commande `helm upgrade` pour déployer {stackstate-product-name}:

[,text]
----
helm upgrade \
  --install \
  --namespace "suse-observability" \
  --values "ingress_otel_values.yaml" \
  --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
suse-observability \
suse-observability/suse-observability
----

[NOTE]
====
Cette étape suppose que xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_generate_baseconfig_values.yaml_and_sizing_values.yaml[Generate `baseConfig_values.yaml` et `sizing_values.yaml`] a déjà été exécuté.
====

== Configuration à l'aide d'outils externes

Pour rendre {stackstate-product-name} accessible en dehors du cluster Kubernetes dans lequel il est installé, il suffit d'acheminer le trafic vers le port `8080` du service `<namespace>-stackstate-k8s-router`. L'interface utilisateur de {stackstate-product-name} est accessible directement sous le chemin racine de ce service (c'est-à-dire `http://<namespace>-stackstate-k8s-router:8080`), tandis que les agents utiliseront le chemin `/receiver` (`http://<namespace>-stackstate-k8s-router:8080/receiver`).

Veillez à mettre à jour l'adresse `baseUrl` dans le fichier de valeurs généré lors de l'installation initiale, car elle sera utilisée par {stackstate-product-name} pour générer des instructions d'installation pratiques pour l'agent.

[NOTE]
====
Lorsque vous configurez manuellement un serveur Nginx ou un serveur HTTP similaire en tant que proxy inverse, assurez-vous qu'il peut également servir de proxy pour les websockets. Pour Nginx, cela peut être configuré en incluant les directives suivantes dans la directive `location`:

[,text]
----
proxy_set_header Upgrade                 $http_upgrade;
proxy_set_header Connection              "Upgrade";
----

====


[CAUTION]
====
{stackstate-product-name} lui-même n'utilise pas de trafic crypté TLS, le cryptage TLS est censé être pris en charge par le contrôleur d'entrée ou les équilibreurs de charge externes.
====


== Agents dans le même cluster

Les agents déployés sur le même cluster que {stackstate-product-name} peuvent bien sûr utiliser l'URL externe sur laquelle {stackstate-product-name} est exposée, mais il est également possible de configurer l'agent pour qu'il se connecte directement à l'instance {stackstate-product-name} via le réseau interne de Kubernetes uniquement. Pour ce faire, remplacez la valeur de `'stackstate.url'` dans la commande `helm install` de l'xref:/k8s-quick-start-guide.adoc[installation Kubernetes de l'agent] par l'URL interne du cluster pour le service de routeur (voir également ci-dessus) : `http://<namespace>-suse-observability-router.<namespace>.svc.cluster.local:8080/receiver/stsAgent` (les sections `<namespace>` doivent être remplacées par l'espace de noms de {stackstate-product-name}).


== Transfert du port de service du routeur {stackstate-product-name} 

Par défaut, le diagramme {stackstate-product-name} Helm déploie un pod et un service de routeur. Ce service expose le port `8080`, qui est le seul point d'entrée qui doit être exposé via Ingress.
Vous pouvez également accéder à {stackstate-product-name} via une redirection de port ; dans ce cas, vous devez autoriser localhost comme origine de la requête.

[WARNING]
====
* L'autorisation de `localhost` dans `stackstate.allowedOrigins` n'est prévue que pour le développement local ou le débogage lors de l'utilisation du transfert de port.
* Il *ne* s'agit *pas* d'une installation de production. Supprimez cette origine autorisée lorsque vous exposez {stackstate-product-name} via Ingress.
====

Pour accéder à l'interface utilisateur sans configurer l'entrée, transférez le port de service du routeur :

[,text]
----
kubectl port-forward service/<helm-release-name>-suse-observability-router 8080:8080 --namespace suse-observability
----

Lorsqu'il accède à {stackstate-product-name} via une redirection de port, le navigateur utilise `http://localhost:8080` comme origine de la requête.
Pour autoriser les requêtes provenant de cette origine, ajoutez-la à la liste `stackstate.allowedOrigins` dans les valeurs Helm, ou transmettez-la directement à la commande Helm: :

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
  --set stackstate.allowedOrigins={"http://localhost:8080"} \
suse-observability \
suse-observability/suse-observability
----


== Voir aussi

* https://learn.microsoft.com/en-us/azure/aks/ingress-tls?tabs=azure-cli[AKS (learn.microsoft.com)]
* https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html[Documentation officielle de l'EKS] (n'utilisant pas nginx)
* https://aws.amazon.com/blogs/opensource/network-load-balancer-nginx-ingress-controller-eks/[Article du blog d'EKS] (utilisant nginx)
* https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/[Traefik Kubernetes Ingress (doc.traefik.io)]
* https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/[Traefik Kubernetes Ingress (doc.traefik.io)]
