include::partial$variables.adoc[]
= Crear y ejecutar una política Gatekeeper
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Desarrolle e implemente una política Gatekeeper utilizando sintaxis y herramientas Rego conocidas para aplicar el control de admisión en entornos Kubernetes.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "rego", "gatekeeper", "build-and-run"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "gatekeeper policy", "rego"]
:sidebar_label: Construir y ejecutar
:current-version: {page-origin-branch}

Puede crear y ejecutar la política exactamente del mismo modo que una política de Rego dirigida a Open Policy Agent.
La estructura de tu proyecto es:

----
.
├── data
│   ├── default-ns.json
│   └── other-ns.json
└── policy.rego

1 directory, 3 files
----

== Construya

Construya la política ejecutando el comando `opa`:

[subs="+attributes",shell]
----
$ opa build -t wasm -e policy/violation policy.rego
----

Esto construye la política de rego, con:

* `target`: `wasm`. Queremos construir la política para el objetivo `wasm`.
* `entrypoint`: `policy/violation`. El punto de entrada es la regla `violation`dentro del paquete `policy`.
* `policy.rego`: cree e incluya el archivo `policy.rego`.

El comando anterior genera un archivo `bundle.tar.gz`.
Puedes extraer de él el módulo Wasm:

[subs="+attributes",shell]
----
$ tar -xf bundle.tar.gz /policy.wasm
----

El árbol de proyectos tiene el siguiente aspecto:

----
.
├── bundle.tar.gz
├── data
│   ├── default-ns.json
│   └── other-ns.json
├── policy.rego
└── policy.wasm

1 directory, 5 files
----

Ahora puede ejecutar su política.

== Ejecutar

Utilice `kwctl` para ejecutar su política de la siguiente manera:

 $ kwctl run -e gatekeeper --request-path data/other-ns.json policy.wasm | jq
 {
   "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
   "allowed": true
 }

Este es su recurso creado en el espacio de nombres llamado `other`, es aceptado, como se esperaba.

Ahora puede ejecutar una solicitud rechazada por la política:

[subs="+attributes",console]
----
$ kwctl run -e gatekeeper --request-path data/default-ns.json policy.wasm | jq
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "allowed": false,
  "status": {
    "message": "it is forbidden to use the default namespace"
  }
}
----

Puede ver su política Gatekeeper rechazado este recurso.
