include::partial$variables.adoc[]
= {project-name} em um ambiente de grande escala
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configure o {project-name}s com o {project-name} para garantir alta disponibilidade e desempenho em ambientes exigentes de grande escala.
:keywords: [kubewarden, "{project-name}", kubernetes, policyservers, production]
:doc-persona: kubewarden-operator, kubewarden-integrator
:doc-type: howto
:doc-topic: manual do operador, servidores de polĂ­ticas, produĂ§ĂŁo
:sidebar_label: ImplementaĂ§ĂŁo em escala
:sidebar_position: 21

Esta seĂ§ĂŁo detalha uma implementaĂ§ĂŁo real do {project-name} em um ambiente exigente e de grande escala. Ele ilustra como configurar o site {short-project-name} para obter alta disponibilidade e desempenho e o que esperar sob carga pesada.

[IMPORTANT]
====
Se vocĂŞ quiser ver mais dicas sobre como executar o {short-project-name} na produĂ§ĂŁo, consulte a documentaĂ§ĂŁo sobre xref:/howtos/production-deployments.adoc[implantaĂ§Ăµes de produĂ§ĂŁo].
====

== VisĂŁo geral do ambiente

A infraestrutura consiste em aproximadamente 20 clusters Kubernetes. Os maiores desses clusters sĂŁo caracterizados por tamanho e volume de recursos significativos:

* NĂłs: ~400
* Namespaces: ~4.000
* Recursos gerenciados:
** Pods: 10,000
** RoleBindings: 13,000
** Ingressantes: 12,000
** ImplantaĂ§Ăµes: 8,000
** ServiĂ§os: 13,000

== {short-project-name} ConfiguraĂ§ĂŁo

Para atender Ă s demandas desse ambiente, o {short-project-name} Ă© configurado com foco no isolamento da carga de trabalho e na alta disponibilidade.

* AplicaĂ§ĂŁo da polĂ­tica: 22 `ClusterAdmissionPolicies` sĂŁo aplicadas em todos os clusters, sem nenhum namespace especĂ­fico `AdmissionPolicies`.
* Arquitetura do PolicyServer: Duas implementaĂ§Ăµes separadas do `PolicyServer` sĂŁo usadas para isolar as cargas de trabalho:
** Um site `PolicyServer` Ă© dedicado exclusivamente a polĂ­ticas com reconhecimento de contexto.
** Um segundo site `PolicyServer` lida com todas as outras polĂ­ticas sem reconhecimento de contexto.
* Escalabilidade e recursos:
** RĂ©plicas: Cada implementaĂ§ĂŁo do `PolicyServer` executa 15 rĂ©plicas para lidar com o alto volume de solicitaĂ§Ăµes.
** AlocaĂ§ĂŁo de recursos: A cada rĂ©plica sĂŁo alocados 300 MB de memĂłria e 4 nĂşcleos de CPU.

== MĂ©tricas de desempenho

Essa configuraĂ§ĂŁo gerencia com ĂŞxito uma alta taxa de solicitaĂ§Ăµes de admissĂŁo e mantĂ©m um desempenho previsĂ­vel.

* Taxa de transferĂŞncia da solicitaĂ§ĂŁo de admissĂŁo: Os clusters processam atĂ© 300 solicitaĂ§Ăµes de admissĂŁo por segundo (incluindo validaĂ§Ăµes de webhook e varreduras de auditoria).
* LatĂŞncia da polĂ­tica:
** LatĂŞncia tĂ­pica: As polĂ­ticas com reconhecimento de contexto geralmente levam cerca de 500 ms para serem executadas.
** Intervalos: Nesse ambiente de alto rendimento, os tempos limite do webhook sĂŁo configurados em 2,5 segundos, enquanto o tempo limite do `PolicyServer` Ă© definido em 10 segundos. Embora a maioria das solicitaĂ§Ăµes seja rĂˇpida, a infraestrutura foi criada para lidar com operaĂ§Ăµes lentas ocasionais sem comprometer a estabilidade do servidor de API.

== Auditoria do desempenho do scanner

O scanner de auditoria Ă© utilizado para garantir a conformidade contĂ­nua em um grande nĂşmero de recursos.

* FrequĂŞncia: Uma auditoria em todo o cluster Ă© realizada a cada 4 horas.
* ConfiguraĂ§ĂŁo: O trabalho de auditoria Ă© ajustado para obter o mĂˇximo de paralelismo e reduzir o tempo de execuĂ§ĂŁo:

[source,shell]
----
--parallel-namespaces: "10"
--parallel-resources: "20"
--parallel-policies: "20"
--page-size: "1000"
----

* DuraĂ§ĂŁo da auditoria: Mesmo no maior cluster com dezenas de milhares de recursos, um trabalho de auditoria completo Ă© concluĂ­do em
