include::partial$variables.adoc[]

= Configuração de proxy
:description: Uso de proxies com {project-name}.
:keywords: ["{project-name}", "kubewarden", "kubernetes", "proxy", "proxies"]
:doc-persona: ["kubewarden-user", "kubewarden-operator", "kubewarden-distributor", "kubewarden-integrator"]
:doc-type: ["howto"]
:doc-topic: ["operator-manual", "proxy"]

Em `kwctl` e `policy-server`, você pode configurar proxies HTTP e HTTPS, bem como isentar domínios dessa configuração de proxy.

Você pode fazer isso de duas maneiras:* Definindo as variáveis de ambiente `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`(e suas contrapartes em minúsculas) para `kwctl` ou `policy-server`.
  Para configurar um CR do PolicyServer, defina sua matriz `spec.env`.* Fornecendo um arquivo `sources.yaml` por meio do argumento `--sources-path`.
  Um arquivo `sources.yaml` tem precedência sobre as variáveis de ambiente.
  O consumo dessa configuração por meio do campo `spec` ainda não está exposto nos CRs do PolicyServer.

A definição de uma configuração de proxy influencia:

* Política pull, push e pull-and-run de e para o registro OCI.
* Recursos de host de chamadas com reconhecimento de contexto, como:
** Registro de contêineres, como a obtenção de um manifesto OCI ou resumo de manifesto.
   Em vez de acessar o registro OCI diretamente, o tráfego será roteado por meio dos proxies configurados.
** Recursos do Sigstore, como a verificação de uma assinatura sem chave.
   Em vez de atingir os serviços definidos pela Sigstore, o tráfego será roteado por meio dos proxies configurados.

== Exemplo

Você pode definir as seguintes variáveis de ambiente para `kwctl` ou`policy-server` (por meio do PolicyServer `spec.env`):

[source,bash]
----
HTTP_PROXY="http://proxy.corp:3128"
https_proxy="http://proxy.corp:3129"
NO_PROXY="localhost,.corp"
----

Com essa configuração:* O tráfego não seguro via HTTP, como o tráfego de e para um registro OCI inseguro, é roteado por meio do site `\http://proxy.corp:3128`.
  Isso afeta as políticas de extração e as políticas que chamam recursos com reconhecimento de contexto que têm resumos de manifesto de imagem OCI para contêineres nesse repositório.* O tráfego criptografado via HTTPS é roteado por meio do site `\https://proxy.corp:3129`.
  Por exemplo, isso inclui a extração e o envio de políticas para qualquer registro seguro da OCI e os recursos de políticas com reconhecimento de contexto mencionados.* O tráfego de e para o localhost ou qualquer domínio em `.corp` está isento das configurações anteriores.


== O arquivo `sources.yaml` 

Para obter mais detalhes, consulte a xref:/reference/sources_yaml.adoc[`sources.yaml`] referência.