include::partial$variables.adoc[]
= Utilisation d'autorités de certification personnalisées
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Configurer PolicyServer pour qu'il utilise des autorités de certification personnalisées ou des sources non sécurisées en conjonction avec les registres spécifiés.
:doc-persona: ["kubewarden-operator", "kubewarden-integrator"]
:doc-topic: ["operator-manual", "policy-servers", "custom-certificate-authorities"].
:doc-type: ["howto"]
:keywords: ["{project-name}", "kubewarden", "kubernetes", "custom certificate authorities"]
:sidebar_label: Utilisation d'AC personnalisées
:current-version: {page-origin-branch}

== Autorités de certification personnalisées pour les registres de politiques

Il est possible de spécifier et de configurer les autorités de certification qu'un PolicyServer utilise lorsqu'il extrait les artefacts ClusterAdmissionPolicy du registre des politiques. Les champs `spec` suivants configurent l'exécutable`policy-server` déployé à cet effet.

=== Sources peu sûres

[IMPORTANT]
====

Le comportement par défaut de `kwctl` et `policy-server` est d'appliquer HTTPS avec des certificats de confiance correspondant au magasin de l'autorité de certification du système. Vous pouvez interagir avec les registres en utilisant des certificats non fiables ou même sans TLS, en utilisant le paramètre`insecure_sources`. Cette approche est *fortement déconseillée* pour les environnements proches de la production.

====

Pour configurer le PolicyServer afin qu'il accepte les connexions non sécurisées à des registres spécifiques, utilisez le champ `spec.insecureSources` du PolicyServer. Ce champ accepte une liste d'URI non sécurisés. Par exemple :

[subs="+attributes",yaml]
----
spec:
  insecureSources:
    - localhost:5000
    - host.k3d.internal:5000
----

Voir xref:howtos/custom-certificate-authorities.adoc[Custom Certificates Authority] pour plus d'informations sur la manière dont l'exécutable `policy-server` traite les URI non sécurisés.

=== Autorités de certification personnalisées

Vous pouvez configurer le PolicyServer avec une chaîne de certificats personnalisée composée d'un ou plusieurs certificats pour un URI spécifique. Pour ce faire, vous utilisez le champ`spec.sourceAuthorities`.

Ce champ est une carte d'URI, chacun avec sa propre liste de chaînes contenant des certificats codés en PEM (Privacy Enhanced Mail). Par exemple :

[subs="+attributes",yaml]
----
spec:
  sourceAuthorities:
    "registry-pre.example.com":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-1 PEM cert
        -----END CERTIFICATE-----
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre1-2 PEM cert
        -----END CERTIFICATE-----
    "registry-pre2.example.com:5500":
      - |
        -----BEGIN CERTIFICATE-----
        ca-pre2 PEM cert
        -----END CERTIFICATE-----
----

Voir xref:howtos/custom-certificate-authorities.adoc[Autorités de certification personnalisées] pour plus d'informations sur la façon dont l'exécutable `policy-server` les traite.
