include::partial$variables.adoc[]
= Verfassen von {project-name} Richtlinien
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Entwickeln Sie Richtlinien für die Zulassungssteuerung, indem Sie genau definierte Funktionalitäten über eine spezifische API mit einer beliebigen unterstützten Programmiersprache bereitstellen.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies"]
:sidebar_label: Schreibrichtlinien
:current-version: {page-origin-branch}

In diesem Abschnitt werden die Richtlinien von {project-name} anhand von Analogien zu herkömmlichen Computern vorgestellt.

Eine {short-project-name} Politik ist wie ein Programm, das eine Aufgabe erfüllt.
Sie empfängt Eingabedaten, führt mit diesen Daten Berechnungen durch und gibt ein Ergebnis zurück.

Die Eingabedaten sind Kubernetes-Zulassungsanfragen.
Das Ergebnis der Berechnung ist eine Validierungsantwort, die Kubernetes mitteilt, ob die Eingabedaten, die Zulassungsanfrage, akzeptiert, abgelehnt oder geändert werden sollen.

Die Komponente https://github.com/kubewarden/policy-server[policy-server]von {short-project-name} führt diese Vorgänge aus.

Der Richtlinienserver verfügt über keinerlei Datenverarbeitungsfunktionen.
Mit Add-ons fügen Sie zur Laufzeit Verarbeitungsfunktionen hinzu.
Diese Zusätze sind die {short-project-name} Politik.

Eine {short-project-name} Richtlinie ist also wie einhttps://en.wikipedia.org/wiki/Plug-in_%28computing%29[traditionelles Plug-in]des Programms "Policy Server".

Um es kurz zu machen:

* {short-project-name} Richtlinien sind Plug-ins, die eine Reihe von genau definierten Funktionen (Validierung eines Kubernetes-Anfrageobjekts, Validierung der vom Benutzer bereitgestellten Richtlinieneinstellungen und andere Funktionen) über eine genau definierte API bereitstellen.
* Der Policy Server ist das "Hauptprogramm", das die Plug-ins (auch Policies genannt) lädt und deren exponierte Funktionalitäten nutzt, um Kubernetes-Anfragen zu akzeptieren, abzulehnen oder zu verändern

Das Schreiben von {short-project-name} Richtlinien besteht darin, die Geschäftslogik für die Validierung zu schreiben und sie dann über eine klar definierte API zugänglich zu machen.

== Anforderungen an die Programmiersprache

Sie liefern {short-project-name} Richtlinien alshttps://webassembly.org/[WebAssembly-Binärdateien].

Richtlinienautoren können Richtlinien mit jeder Programmiersprache schreiben, die WebAssembly als Kompilierungsziel unterstützt.
Die Liste der unterstützten Sprachen wird ständig erweitert, https://github.com/appcypher/awesome-wasm-langs[. Diese Seite] bietet einen guten Überblick über die WebAssembly-Landschaft.

Derzeit gibt es in WebAssembly keine offizielle Möglichkeit, komplexe Datentypen zwischen dem Host und einem WebAssembly-Gast freizugeben.
Um diese Einschränkung zu überwinden, verwenden die Richtlinien von {short-project-name} das Projekt https://github.com/wapc[waPC], das einen bidirektionalen Kommunikationskanal bietet.

Die von Ihnen gewählte Programmiersprache muss also über ein waPC-Gast-SDK verfügen.
Wenn das nicht der Fall ist, können Sie sich gerne an uns wenden.
Das Projektteam kann Ihnen helfen, diese Einschränkung zu überwinden.
