include::partial$variables.adoc[]
= Sugerir una mejora de la documentación
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Inicie una mejora de la documentación abriendo una incidencia en GitHub con detalles claros sobre lo que falta, está obsoleto, es erróneo o requiere una revisión de calidad.
:doc-persona: ["kubewarden-developer", "kubewarden-operator", "kubewarden-manager"]
:doc-topic: ["contribution-guide", "docs-contribution", "improvement"]
:doc-type: ["howto"]
:keywords: ["kubewarden", "documentation", "suggesting an improvement"]
:sidebar_label: Sugerir mejoras en los documentos
:sidebar_position: 8
:current-version: {page-origin-branch}

Si detectas algún problema en la documentación de {short-project-name} o quieres sugerir nuevos contenidos, abre una incidencia. Sólo necesitas acceso a una GitHubhttps://github.com/join[cuenta de] y un navegador.

Normalmente, cualquier nuevo trabajo de documentación para {short-project-name} comienza con una incidencia en GitHub.
ifeval::["{build-type}" == "community"]
El equipo de https://github.com/orgs/kubewarden/teams/kubewarden-documentation[documentación de] 
endif::[]
ifeval::["{build-type}" == "product"]
El equipo de https://github.com/orgs/rancher/teams/docs[documentación de] 
endif::[]
Todo el mundo es bienvenido a trabajar en cualquier tema, incluido el reportero, pero debes asignártelo a ti mismo antes de empezar a trabajar para evitar duplicar esfuerzos.

== Abrir una edición

Para sugerir mejoras en el contenido de la documentación existente o notificar un error, abra una incidencia.

* Haz clic en el icono GitHub Octocat de la parte superior. Esto le redirige a la página
ifeval::["{build-type}" == "community"]
  https://github.com/kubewarden/docs[repositorio de documentación para {short-project-name}].
endif::[]
ifeval::["{build-type}" == "product"]
  https://github.com/rancher/kubewarden-product-docs[repositorio de documentación para {short-project-name}].
endif::[]
* Vaya a la pestaña Emisiones y haga clic en *Nueva emisión*.
* Describa el problema o la sugerencia de mejora. Cuantos más detalles, mejor.
* Haga clic en *Enviar nueva edición*.
* Tras enviar la incidencia, puedes asignártela a ti mismo o esperar a que la recoja un miembro de la comunidad. Es posible que los miembros del equipo de documentación y la comunidad soliciten aclaraciones antes de poder actuar sobre su problema. Deberías comprobar activamente tu incidencia o https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications[activa las notificaciones de GitHub].

== Nuevas sugerencias de contenidos

Para sugerir nuevos contenidos, presente un problema utilizando uno de estos mecanismos:

* Elija una página existente en la sección a la que cree que pertenece el contenido y haga clic en *Crear una edición*. O
ifeval::["{build-type}" == "community"]
* Navegue hasta https://github.com/kubewarden/docs/issues/new/choose[] GitHub y presente la incidencia directamente.
endif::[]
ifeval::["{build-type}" == "product"]
* Navegue hasta https://github.com/rancher/kubewarden-product-docs/issues/new/choose[] GitHub y presente la incidencia directamente.
endif::[]

== ¿Cómo puede hacer que su contribución cuente?

Ninguna contribución es demasiado grande o pequeña. Sin embargo, para que la comunidad obtenga el máximo valor, le pedimos que siga las siguientes indicaciones cuando comunique un problema:

* Concéntrese en proporcionar una descripción clara del problema. Algunos puntos clave a tener en cuenta serían describir lo que falta, está obsoleto, es erróneo o requiere mejoras cualitativas y técnicas.
* Describa el impacto específico del problema en los usuarios.
* Limite el alcance de la cuestión. Si el alcance es grande, divídalo en tareas más pequeñas dentro de una cuestión. Por ejemplo, "Crear una guía de contribuciones" tiene un alcance amplio, ya que habría múltiples tareas asociadas a la cuestión.
  Sin embargo, "Corregir un error gramatical en la página de inicio rápido" es una cuestión de alcance más limitado que requeriría una única solicitud de pull.
* Comprobación cruzada de los problemas existentes para evitar la duplicación del trabajo.
* Compruebe si existe una solicitud de pull o una incidencia. Comprueba que haces referencia a la incidencia o pull request existente dentro de la incidencia que estás abriendo para dar contexto a los colaboradores que quieran trabajar en ella.
