= Secretos externos
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Secretos externos de SUSE Observability

== Visión general

SUSE Observability puede tomar secretos como la clave de licencia, la clave api y las claves de autenticación a través de la instalación de helm, pero también puede tomarlos de secretos ya proporcionados.

Aquí se describe cómo configurarlo.

== Obtener la clave de licencia de un secreto externo

Cree un secreto en el espacio de nombres en el que está instalado SUSE Observability, de la siguiente forma, rellenando los espacios en blanco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

Añade lo siguiente a tu comando helm install para utilizar el secreto:

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== Obtener el nombre de usuario y la contraseña para las notificaciones por correo electrónico de un secreto externo

Cree un secreto en el espacio de nombres en el que está instalado SUSE Observability, de la siguiente forma, rellenando los espacios en blanco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

Añade lo siguiente a tu comando helm install para utilizar el secreto:

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== Obtener la clave api de un secreto externo

Cree un secreto en el espacio de nombres en el que está instalado SUSE Observability, de la siguiente forma, rellenando los espacios en blanco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

Añade lo siguiente a tu comando helm install para utilizar el secreto:

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== Obtener datos de autenticación de un secreto externo

Cree un secreto en el espacio de nombres en el que está instalado SUSE Observability, de la siguiente forma.

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

En función del método de autenticación elegido, el campo `default_password` se sustituye por datos diferentes. Consulte las xref:/setup/security/authentication/authentication_options.adoc[opciones de autenticación] para obtener más información. En este ejemplo se utiliza la configuración de xref:/setup/security/authentication/single_password.adoc[Contraseña única].

Añade lo siguiente a tu comando helm install para utilizar el secreto:

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
