= Configuração do agente Kubernetes do SUSE Observability para conexões de proxy
:revdate: 2025-07-10
:page-revdate: {revdate}

O SUSE Observability Kubernetes Agent permite que você defina as configurações de proxy HTTP ou HTTPS para as conexões que ele inicia.

== Proxy para comunicação com o SUSE Observability

Para configurar o agente para fazer conexões de proxy com o backend do SUSE Observability, você pode usar a configuração do Helm.

=== Configuração do leme

==== Via `values.yaml` File

. Abra o arquivo do gráfico do Helm `values.yaml`.
. Localize a configuração `global.proxy.url` e especifique o URL do proxy:
+
[,yaml]
----
 global:
   proxy:
     url: "https://proxy.example.com:8080"
----

. Opcionalmente, se o proxy não tiver um certificado assinado, desative a verificação SSL definindo `global.skipSslValidation` como `true`:
+
[,yaml]
----
 global:
   skipSslValidation: true
----

==== Via sinalizador de linha de comando

. Durante a instalação do Helm chart, use o sinalizador `--set` para especificar o URL do proxy:
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.proxy.url="https://proxy.example.com:8080"
----

. Para desativar a validação SSL por meio da linha de comando, use:
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.skipSslValidation=true
----
