= Certificados para injeção de sidecar de rastreamento de solicitações
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Observabilidade do SUSE

O xref:/setup/agent/k8sTs-agent-request-tracing.adoc#_enabling_the_trace_header_injection_sidecar[mecanismo de injeção sidecar], que é ativado quando se usa `--set httpHeaderInjectorWebhook.enabled=true` ao instalar o agente, cria um certificado autoassinado e usa um `ClusterRole` que concede acesso de gravação aos objetos `Secret` e `MutatingWebhookConfiguration` no cluster do Kubernetes.

Se, por motivos de segurança, não for desejável criar o site `ClusterRoles` que concede direitos de gravação em todo o cluster, ou se houver maneiras alternativas de fornecer um certificado:

. Gerar um certificado autoassinado <<_generate_a_certificate_locally,localmente>>.
. Use o k8s https://cert-manager.io/[cert-manager] (se ele já estiver no cluster) <<_generate_a_certificate_using_the_cert_manager,com um `ClusterIssuer`>>.

== Gerar um certificado localmente

Para gerar um certificado localmente, execute as etapas a seguir:

. Faça o download do script de geração de certificado e execute-o para produzir um arquivo de valores de timão (`tls_values.yaml`) com o certificado correto:
+
----
wget https://raw.githubusercontent.com/StackVista/http-header-injector/main/scripts/generate_ca_cert.sh
chmod +x generate_ca_cert.sh
./generate_ca_cert.sh <helm-agent-release-name> <helm-agent-namespace>
----
+
Certifique-se de usar o nome da versão que será usado no comando helm e o namespace, caso contrário, o certificado será inválido.

. Instale o agente adicionando a configuração adicional, adicionando `--set httpHeaderInjectorWebhook.enabled=true -f tls_values.yaml` ao comando de invocação do helm

== Gerar um certificado usando o gerenciador de certificados

Se o seu cluster tiver o https://cert-manager.io/[cert-manager] instalado e um `ClusterIssuer` configurado, será possível usar o certificado emitido pelo `ClusterIssuer` no agente para o injetor sidecar. Para fazer isso, adicione os seguintes argumentos de linha de comando para instalar o agente: `--set httpHeaderInjectorWebhook.enabled=true --set-string httpHeaderInjectorWebhook.webhook.tls.mode="cert-manager" --set-string httpHeaderInjectorWebhook.webhook.tls.certManager.issuer="<my-cluster-issuer>"`. Certifique-se de substituir my-cluster-issuer pelo nome do emissor em seu cluster.
