= Geheimnisse Verschlüsselung Konfig
:page-languages: [en, ja, ko, zh]
:revdate: 2026-03-03
:page-revdate: {revdate}

K3s unterstützt die Aktivierung der Verschlüsselung von Geheimnissen im Ruhezustand. Beim ersten Start des Servers wird durch die Angabe des Flags `--secrets-encryption` automatisch folgendes getan:

* Erzeugen eines AES-CBC-Schlüssels
* Erzeugen einer Verschlüsselungskonfigurationsdatei mit dem erzeugten Schlüssel
* Übergeben Sie die Konfiguration als encryption-provider-config an die KubeAPI

[TIP]
====
Die Verschlüsselung von Geheimnissen kann auf einem bestehenden Server nicht aktiviert werden, ohne ihn neu zu starten. +
Verwenden Sie `curl -sfL https://get.k3s.io | INSTALL_K3S_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/k3s sh -s - server --secrets-encryption`, wenn Sie von einem Skript aus installieren, oder andere unter xref:installation/configuration.adoc#_configuration_with_install_script[Konfigurationsoptionen] beschriebene Methoden.
====

== Auswahl des Verschlüsselungsanbieters

[IMPORTANT]
.Version Tor
====
Verfügbar ab April 2025: v1.30.12+k3s1, v1.31.8+k3s1, v1.32.4+k3s1, v1.33.0+k3s1.
====

Mit dem Flag `--secrets-encryption-provider` können Sie zwischen den folgenden von K3 unterstützten Verschlüsselungsanbietern wählen:

* `aescbc`: AES-CBC mit PKCS#7-Polsterung. Dies ist der Standardanbieter.
* `secretbox`: XSalsa20 and Poly1305

### Migration von Providern

Sie können vom Anbieter `aescbc` zum Anbieter `secretbox` migrieren, indem Sie die folgenden Schritte ausführen:

. Stellen Sie sicher, dass der Anbieter `secretbox` von Ihrer K3s-Version unterstützt wird.
. Aktualisieren Sie das `secrets-encryption-provider` Flag in Ihrer K3s-Konfigurationsdatei auf `secretbox`.
. Drehen Sie die Verschlüsselungsschlüssel wie im Abschnitt xref:cli/secrets-encrypt.adoc#_encryption_key_rotation[Drehen der Verschlüsselungsschlüssel] beschrieben.

== Erstellte Verschlüsselungskonfigurationsdatei

Wenn Sie den Server mit `--secrets-encryption` starten, erzeugt K3s eine Verschlüsselungskonfigurationsdatei unter `/var/lib/rancher/k3s/server/cred/encryption-config.json`.

Nachstehend finden Sie ein Beispiel für die generierte Verschlüsselungskonfigurationsdatei mit dem Standardanbieter `aescbc`:

[,json]
----
{
  "kind": "EncryptionConfiguration",
  "apiVersion": "apiserver.config.k8s.io/v1",
  "resources": [
    {
      "resources": [
        "secrets"
      ],
      "providers": [
        {
          "aescbc": {
            "keys": [
              {
                "name": "aescbckey",
                "secret": "xxxxxxxxxxxxxxxxxxx"
              }
            ]
          }
        },
        {
          "identity": {}
        }
      ]
    }
  ]
}
----

== Secrets Verschlüsselungstool

K3s enthält ein Hilfsprogramm `secrets-encrypt`, das eine automatische Kontrolle der folgenden Punkte ermöglicht:

* Deaktivieren/Aktivieren der Verschlüsselung von Geheimnissen
* Hinzufügen neuer Verschlüsselungscodes
* Rotieren und Löschen von Verschlüsselungsschlüsseln
* Geheimnisse wieder verschlüsseln

Weitere Informationen finden Sie in der xref:cli/secrets-encrypt.adoc[Dokumentation zum Befehl`k3s secrets-encrypt` ].
