// This file was converted from Markdown to AsciiDoc.

include::partial$variables.adoc[]
= kwctl CLI
:revdate: 2026-03-18
:page-revdate: {revdate}
:title: kwctl CLI
:description: Erkunden Sie das Befehlszeilen-Tool \`kwctl`, um {project-name} Richtlinien zu verwalten und Aufgaben wie das Laden von Richtlinien durchzuführen.
:keywords: cli, referenz, kwctl
:doc-persona: kubewarden-operator
:doc-type: Referenz
:doc-topic: Bedienungshandbuch

== Kommandozeilen-Hilfe für `kwctl`

Dieses Dokument enthält den Inhalt der Hilfe für das Befehlszeilenprogramm `kwctl`.

*Befehlsübersicht:*

* <<kwctl,`kwctl`>>
* <<kwctl-annotate,`kwctl annotate`>>
* <<kwctl-bench,`kwctl bench`>>
* <<kwctl-completions,`kwctl completions`>>
* <<kwctl-digest,`kwctl digest`>>
* <<kwctl-docs,`kwctl docs`>>
* <<kwctl-info,`kwctl info`>>
* <<kwctl-inspect,`kwctl inspect`>>
* <<kwctl-load,`kwctl load`>>
* <<kwctl-policies,`kwctl policies`>>
* <<kwctl-pull,`kwctl pull`>>
* <<kwctl-push,`kwctl push`>>
* <<kwctl-rm,`kwctl rm`>>
* <<kwctl-run,`kwctl run`>>
* <<kwctl-save,`kwctl save`>>
* <<kwctl-scaffold,`kwctl scaffold`>>
* <<kwctl-scaffold-admission-request,`kwctl scaffold admission-request`>>
* <<kwctl-scaffold-artifacthub,`kwctl scaffold artifacthub`>>
* <<kwctl-scaffold-manifest,`kwctl scaffold manifest`>>
* <<kwctl-scaffold-vap,`kwctl scaffold vap`>>
* <<kwctl-scaffold-verification-config,`kwctl scaffold verification-config`>>
* <<kwctl-verify,`kwctl verify`>>

[[kwctl]]
=== `kwctl`

Tool zur Verwaltung von {project-name} Richtlinien

*Verwendung:* `kwctl [OPTIONS] <COMMAND>`

==== Unterbefehle

* `annotate` - Hinzufügen von {short-project-name} -Metadaten zu einem WebAssembly-Modul
* `bench` - Benchmarks a {short-project-name} Politik
* `completions` - Erzeugen von Shell-Vervollständigungen
* `digest` - Abruf der Zusammenfassung aus dem OCI-Manifest einer Richtlinie
* `docs` - Erzeugt die Markdown-Dokumentation für kwctl-Befehle
* `info` - Systeminformationen anzeigen
* `inspect` - Überprüfen Sie die {short-project-name} Politik
* `load` - Richtlinien aus einer tar.gz-Datei laden
* `policies` - Listet alle heruntergeladenen Richtlinien auf
* `pull` - Ruft eine {short-project-name} Richtlinie von einer bestimmten URI ab.
* `push` - Übergibt eine {short-project-name} Richtlinie an ein OCI-Register
* `rm` - Entfernt eine {short-project-name} Richtlinie aus dem Speicher
* `run` - Führt eine {short-project-name} Richtlinie von einem bestimmten URI aus
* `save` - Richtlinien in einer tar.gz-Datei speichern
* `scaffold` - Gerüst einer Kubernetes-Ressource oder Konfigurationsdatei
* `verify` - Überprüfen Sie eine {short-project-name} Richtlinie von einem bestimmten URI mit Sigstore

==== Optionen

* `-v`, `--verbose <VERBOSE>` - Ausführlichkeit erhöhen
* `--no-color <NO-COLOR>` - Farbige Ausgabe deaktivieren

[[kwctl-annotate]]
=== `kwctl annotate`

Hinzufügen von {short-project-name} -Metadaten zu einem WebAssembly-Modul

*Verwendung:* `kwctl annotate [OPTIONS] --metadata-path <PATH> --output-path <PATH> <wasm-path>`

==== Argumente

* `<WASM-PATH>` - Pfad zum WebAssembly-Modul, das mit Anmerkungen versehen werden soll

==== Optionen

* `-m`, `--metadata-path <PATH>` - Datei mit den Metadaten
* `-o`, `--output-path <PATH>` - Ausgabedatei
* `-u``--usage-path <PATH>` - Datei mit den Nutzungsinformationen der Richtlinie

[[kwctl-bench]]
=== `kwctl bench`

Benchmarks eine {short-project-name} Politik.

Die Richtlinie kann auf die folgenden Arten angegeben werden:- URI: z. B. `registry://ghcr.io/kubewarden/policies/psp-policy:latest` oder `\https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm`- SHA-Präfix: z. B. `c3b80a10f9c3` (setzt voraus, dass die Richtlinie bereits abgerufen wurde) - Lokale WASM-Datei: z. B. `file://home/tux/new-policy/psp-policy.wasm`- Lokale YAML-Datei: z. B. `file://home/tux/cluster-admission-policy.yaml` (enthält Deklarationen von {short-project-name} Custom Resources wie `ClusterAdmissionPolicy`, `AdmissionPolicy` usw.)

Standard-Verhalten:
Wenn das Schema nicht angegeben wird, wird `file://` angenommen, das im aktuellen Verzeichnis verwurzelt ist.

Hinweise zu {short-project-name} Benutzerdefinierte Ressourcen:- Die Flags `--request-path`, `--settings-path` und `--settings-json` werden ignoriert; die Einstellungen werden aus der Definition der Custom Resource gelesen.- Das Flag `--execution-mode` gilt für alle Policies in der YAML-Datei.- Das Flag `--raw` kann nicht verwendet werden, da die Custom Resources von {short-project-name} keine `raw` Richtlinien unterstützen.

Nur die folgenden Attribute der Custom Resource Definition (CRD) werden ausgewertet:- Richtlinienmodul - Richtlinieneinstellungen - kontextabhängige Ressourcen, auf die die Richtlinie zugreifen kann

Andere Felder, wie `rules`, `matchConditions`, `objectSelector` und `namespaceSelector`, werden ignoriert.

Eine YAML-Datei kann mehrere Custom Resource-Deklarationen enthalten. In diesem Fall bewertet `kwctl` jede Richtlinie in der Datei, wobei bei jeder Bewertung dieselbe Anfrage verwendet wird.

*Verwendung:* `kwctl bench [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>`

==== Argumente

* `<URI_OR_SHA_PREFIX_OR_YAML_FILE>` - Richtlinien-URI, SHA-Präfix oder YAML-Datei mit {short-project-name} Richtlinienressourcen. Unterstützte Schemata: registry://, https://, file://. Wird schema weggelassen, wird file:// angenommen, bezogen auf das aktuelle Verzeichnis.

==== Optionen

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Gewähren Sie Zugriff auf die Kubernetes-Ressourcen, die im Abschnitt `contextAwareResources` der Richtlinie definiert sind. Achtung: Überprüfen Sie die Liste der Ressourcen sorgfältig, um Missbräuche zu vermeiden. Standardmäßig deaktiviert
* `--cert-email <VALUE>` - Erwartete E-Mail im Fulcio-Zertifikat
* `--cert-oidc-issuer <VALUE>` - Erwarteter OIDC-Emittent in Fulcio-Zertifikaten
* `--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>` - Verwendung des Wasmtime-Caches ausschalten
* `--docker-config-json-path <PATH>` - Pfad zu einem Verzeichnis, das die Docker-Datei "config.json" enthält. Kann zur Angabe von Registrierungsauthentifizierungsdetails verwendet werden
* `--dump-results-to-disk <DUMP_RESULTS_TO_DISK>` - Legt die Ergebnisse in target/tiny-bench/label/\... ab, wenn das Ziel gefunden werden kann. wird zum Vergleich früherer Läufe verwendet
* `-e``--execution-mode <MODE>` - Die Laufzeit, die für die Ausführung dieser Richtlinie verwendet wird +
  Mögliche Werte: `opa`, `gatekeeper`, `kubewarden`, `wasi`
* `--github-owner <VALUE>` - GitHub-Besitzer wird in den in CD-Pipelines generierten Zertifikaten erwartet
* `--github-repo <VALUE>` - GitHub-Repository, das in den in CD-Pipelines generierten Zertifikaten erwartet wird
* `--measurement-time <SECONDS>` - Wie lange der Bench 'laufen soll', num_samples wird priorisiert, so dass das Benching länger dauert, um num_samples sammeln zu können, wenn der zu benchmarkende Code langsamer ist als dieses Zeitlimit erlaubt
* `--num-resamples <NUM>` - Wie viele erneute Stichproben sollten durchgeführt werden?
* `--num-samples <NUM>` - Wie viele Wiederholungsstichproben sollten durchgeführt werden. Empfohlen werden mindestens 50, mehr als 100 scheinen kein signifikant anderes Ergebnis zu bringen.
* `--raw <RAW>` - Eine rohe Anfrage validieren +
  Standardwert: `false`
* `--record-host-capabilities-interactions <FILE>` - Zeichnet die gesamte Kommunikation der Richtlinien und Host-Fähigkeiten in der angegebenen Datei auf. Nützlich für die spätere Kombination mit dem Flag '--replay-host-capabilities-interactions'.
* `--replay-host-capabilities-interactions <FILE>` - Während des Austauschs von Richtlinien und Host-Fähigkeiten gibt der Host die in der bereitgestellten Datei gefundenen Antworten wieder. Dies ist nützlich, um Richtlinien auf reproduzierbare Weise zu testen, da keine externen Interaktionen mit OCI-Registrierungen, DNS und Kubernetes durchgeführt werden.
* `-r``--request-path <PATH>` - Datei mit dem Objekt der Kubernetes-Zulassungsanfrage im JSON-Format
* `--settings-json <VALUE>` - JSON-String mit den Einstellungen für diese Richtlinie
* `-s`, `--settings-path <PATH>` - Datei mit den Einstellungen für diese Richtlinie
* `--sigstore-trust-config <PATH>` - JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschließlich der URIs, die für den Zugriff auf die CA- und Artefakttransparenzdienste verwendet werden, sowie die kryptografische Vertrauensbasis selbst
* `--sources-path <PATH>` - YAML-Datei mit Quellinformationen (https, Registry unsichere Hosts, benutzerdefinierte CAs...)
* `-a``--verification-annotation <KEY=VALUE>` - Anmerkung im Format Schlüssel=Wert. Kann mehrmals wiederholt werden
* `--verification-config-path <PATH>` - YAML-Datei mit Informationen zur Verifikationskonfiguration (Signaturen, öffentliche Schlüssel...)
* `-k`, `--verification-key <PATH>` - Pfad zum Schlüssel, der zur Überprüfung der Richtlinie verwendet wird. Kann mehrmals wiederholt werden
* `--warm-up-time <SECONDS>` - Wie lange die Bank aufwärmen sollte

[[kwctl-completions]]
=== `kwctl completions`

Erzeugen von Shell-Vervollständigungen

*Verwendung:* `kwctl completions --shell <VALUE>`

==== Optionen

* `-s`, `--shell <VALUE>` - Muschelart +
  Mögliche Werte: `bash`, `elvish`, `fish`, `powershell`, `zsh`

[[kwctl-digest]]
=== `kwctl digest`

Abruf der Zusammenfassung aus dem OCI-Manifest einer Richtlinie

*Verwendung:* `kwctl digest [OPTIONS] <uri>`

==== Argumente

* `<URI>` - Politik URI

==== Optionen

* `--docker-config-json-path <PATH>` - Pfad zu einem Verzeichnis, das die Docker-Datei "config.json" enthält. Kann zur Angabe von Registrierungsauthentifizierungsdetails verwendet werden
* `--sources-path <PATH>` - YAML-Datei mit Quellinformationen (https, Registry unsichere Hosts, benutzerdefinierte CAs...)

[[kwctl-docs]]
=== `kwctl docs`

Erzeugt die Markdown-Dokumentation für kwctl-Befehle

*Verwendung:* `kwctl docs --output <FILE>`

==== Optionen

* `-o`, `--output <FILE>` - Pfad, in dem die Dokumentationsdatei gespeichert wird

[[kwctl-info]]
=== `kwctl info`

Systeminformationen anzeigen

*Verwendung:* `kwctl info`

[[kwctl-inspect]]
=== `kwctl inspect`

Überprüfen Sie die {short-project-name} Politik

*Verwendung:* `kwctl inspect [OPTIONS] <uri_or_sha_prefix>`

==== Argumente

* `<URI_OR_SHA_PREFIX>` - Richtlinien-URI oder SHA-Präfix. Unterstützte Schemata: registry://, https://, file://. Wird schema weggelassen, wird file:// angenommen, bezogen auf das aktuelle Verzeichnis.

==== Optionen

* `--docker-config-json-path <PATH>` - Pfad zu einem Verzeichnis, das die Docker-Datei "config.json" enthält. Kann zur Angabe von Registrierungsauthentifizierungsdetails verwendet werden
* `-o`, `--output <FORMAT>` - Ausgabeformat +
  Mögliche Werte: `yaml`
* `--show-signatures <SHOW-SIGNATURES>` - Signaturen anzeigen
* `--sources-path <PATH>` - YAML-Datei mit Quellinformationen (https, Registry unsichere Hosts, benutzerdefinierte CAs...)

[[kwctl-load]]
=== `kwctl load`

Richtlinien aus einer tar.gz-Datei laden

*Verwendung:* `kwctl load --input <input>`

==== Optionen

* `--input <INPUT>` - Richtlinien aus dem Tarball laden

[[kwctl-policies]]
=== `kwctl policies`

Listet alle heruntergeladenen Richtlinien auf

*Verwendung:* `kwctl policies`

[[kwctl-pull]]
=== `kwctl pull`

Ruft eine {short-project-name} Richtlinie von einer bestimmten URI ab.

*Verwendung:* `kwctl pull [OPTIONS] <uri>`

==== Argumente

* `<URI>` - Politik URI. Unterstützte Schemata: registry://, https://, file://

==== Optionen

* `--cert-email <VALUE>` - Erwartete E-Mail im Fulcio-Zertifikat
* `--cert-oidc-issuer <VALUE>` - Erwarteter OIDC-Emittent in Fulcio-Zertifikaten
* `--docker-config-json-path <DOCKER_CONFIG>` - Pfad zu einem Verzeichnis, das die Docker-Datei "config.json" enthält. Kann zur Angabe von Registrierungsauthentifizierungsdetails verwendet werden
* `--github-owner <VALUE>` - GitHub-Besitzer wird in den in CD-Pipelines generierten Zertifikaten erwartet
* `--github-repo <VALUE>` - GitHub-Repository, das in den in CD-Pipelines generierten Zertifikaten erwartet wird
* `-o`, `--output-path <PATH>` - Ausgabedatei. Wenn keine Angaben gemacht werden, werden sie in den {short-project-name} Store heruntergeladen.
* `--sigstore-trust-config <PATH>` - JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschließlich der URIs, die für den Zugriff auf die CA- und Artefakttransparenzdienste verwendet werden, sowie die kryptografische Vertrauensbasis selbst
* `--sources-path <PATH>` - YAML-Datei mit Quellinformationen (https, Registry unsichere Hosts, benutzerdefinierte CAs...)
* `-a``--verification-annotation <KEY=VALUE>` - Anmerkung im Format Schlüssel=Wert. Kann mehrmals wiederholt werden
* `--verification-config-path <PATH>` - YAML-Datei mit Informationen zur Verifikationskonfiguration (Signaturen, öffentliche Schlüssel...)
* `-k`, `--verification-key <PATH>` - Pfad zum Schlüssel, der zur Überprüfung der Richtlinie verwendet wird. Kann mehrmals wiederholt werden

[[kwctl-push]]
=== `kwctl push`

Übergibt eine {short-project-name} Richtlinie an ein OCI-Register

*Verwendung:* `kwctl push [OPTIONS] <policy> <uri>`

Die in den Metadaten der Richtlinie enthaltenen Anmerkungen werden Teil des OCI-Manifests sein.
Die mehrzeiligen Anmerkungen werden übersprungen, da sie nicht mit der OCI-Spezifikation kompatibel sind.
Die Annotation 'io.kubewarden.policy.source' wird als 'org.opencontainers.image.source' propagiert, damit Werkzeuge wie renovatebot Richtlinienaktualisierungen erkennen können.

==== Argumente

* `<POLICY>` - Politik zum Anschieben. Kann der Pfad zu einer lokalen Datei, ein Richtlinien-URI oder das SHA-Präfix einer Richtlinie im Speicher sein.
* `<URI>` - Politik URI. Unterstützte Schemata: registry://

==== Optionen

* `--docker-config-json-path <PATH>` - Pfad zu einem Verzeichnis, das die Docker-Datei "config.json" enthält. Kann zur Angabe von Registrierungsauthentifizierungsdetails verwendet werden
* `-f``--force <FORCE>` - Schieben Sie auch eine Politik, die nicht vermerkt ist
* `-o`, `--output <PATH>` - Ausgabeformat +
  Standardwert: `text` +
  Mögliche Werte: `text`, `json`
* `--sources-path <PATH>` - YAML-Datei mit Quellinformationen (https, Registry unsichere Hosts, benutzerdefinierte CAs...)

[[kwctl-rm]]
=== `kwctl rm`

Entfernt eine {short-project-name} Richtlinie aus dem Speicher

*Verwendung:* `kwctl rm <uri_or_sha_prefix>`

==== Argumente

* `<URI_OR_SHA_PREFIX>` - Richtlinien-URI oder SHA-Präfix

[[kwctl-run]]
=== `kwctl run`

Führen Sie eine oder mehrere {short-project-name} Richtlinien lokal aus.

Die Richtlinie kann auf die folgenden Arten angegeben werden:- URI: z. B. `registry://ghcr.io/kubewarden/policies/psp-policy:latest` oder `https://example.com/kubewarden/policies/main/psp-policy/psp-policy.wasm`- SHA-Präfix: z. B. `c3b80a10f9c3` (setzt voraus, dass die Richtlinie bereits abgerufen wurde) - Lokale WASM-Datei: z. B. `file://home/tux/new-policy/psp-policy.wasm`- Lokale YAML-Datei: z. B. `file://home/tux/cluster-admission-policy.yaml` (enthält Deklarationen von {short-project-name} Custom Resources wie `ClusterAdmissionPolicy`, `AdmissionPolicy` usw.)

Standard-Verhalten:
Wenn das Schema nicht angegeben wird, wird `file://` angenommen, das im aktuellen Verzeichnis verwurzelt ist.

Hinweise zu {short-project-name} Benutzerdefinierte Ressourcen:- Die Flags `--request-path`, `--settings-path` und `--settings-json` werden ignoriert; die Einstellungen werden aus der Definition der Custom Resource gelesen.- Das Flag `--execution-mode` gilt für alle Policies in der YAML-Datei.- Das Flag `--raw` kann nicht verwendet werden, da die Custom Resources von {short-project-name} keine `raw` Richtlinien unterstützen.

Nur die folgenden Attribute der Custom Resource Definition (CRD) werden ausgewertet:- Richtlinienmodul - Richtlinieneinstellungen - kontextabhängige Ressourcen, auf die die Richtlinie zugreifen kann

Andere Felder, wie `rules`, `matchConditions`, `objectSelector` und `namespaceSelector`, werden ignoriert.

Eine YAML-Datei kann mehrere Custom Resource-Deklarationen enthalten. In diesem Fall bewertet `kwctl` jede Richtlinie in der Datei, wobei bei jeder Bewertung dieselbe Anfrage verwendet wird.

*Verwendung:* `kwctl run [OPTIONS] --request-path <PATH> <uri_or_sha_prefix_or_yaml_file>`

==== Argumente

* `<URI_OR_SHA_PREFIX_OR_YAML_FILE>` - Richtlinien-URI, SHA-Präfix oder YAML-Datei mit {short-project-name} Richtlinienressourcen. Unterstützte Schemata: registry://, https://, file://. Wird schema weggelassen, wird file:// angenommen, bezogen auf das aktuelle Verzeichnis.

==== Optionen

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Gewähren Sie Zugriff auf die Kubernetes-Ressourcen, die im Abschnitt `contextAwareResources` der Richtlinie definiert sind. Achtung: Überprüfen Sie die Liste der Ressourcen sorgfältig, um Missbräuche zu vermeiden. Standardmäßig deaktiviert
* `--cert-email <VALUE>` - Erwartete E-Mail im Fulcio-Zertifikat
* `--cert-oidc-issuer <VALUE>` - Erwarteter OIDC-Emittent in Fulcio-Zertifikaten
* `--disable-wasmtime-cache <DISABLE-WASMTIME-CACHE>` - Verwendung des Wasmtime-Caches ausschalten
* `--docker-config-json-path <PATH>` - Pfad zu einem Verzeichnis, das die Docker-Datei "config.json" enthält. Kann zur Angabe von Registrierungsauthentifizierungsdetails verwendet werden
* `-e``--execution-mode <MODE>` - Die Laufzeit, die für die Ausführung dieser Richtlinie verwendet wird +
  Mögliche Werte: `opa`, `gatekeeper`, `kubewarden`, `wasi`
* `--github-owner <VALUE>` - GitHub-Besitzer wird in den in CD-Pipelines generierten Zertifikaten erwartet
* `--github-repo <VALUE>` - GitHub-Repository, das in den in CD-Pipelines generierten Zertifikaten erwartet wird
* `--raw <RAW>` - Eine rohe Anfrage validieren +
  Standardwert: `false`
* `--record-host-capabilities-interactions <FILE>` - Zeichnet die gesamte Kommunikation der Richtlinien und Host-Fähigkeiten in der angegebenen Datei auf. Nützlich für die spätere Kombination mit dem Flag '--replay-host-capabilities-interactions'.
* `--replay-host-capabilities-interactions <FILE>` - Während des Austauschs von Richtlinien und Host-Fähigkeiten gibt der Host die in der bereitgestellten Datei gefundenen Antworten wieder. Dies ist nützlich, um Richtlinien auf reproduzierbare Weise zu testen, da keine externen Interaktionen mit OCI-Registrierungen, DNS und Kubernetes durchgeführt werden.
* `-r``--request-path <PATH>` - Datei mit dem Objekt der Kubernetes-Zulassungsanfrage im JSON-Format
* `--settings-json <VALUE>` - JSON-String mit den Einstellungen für diese Richtlinie
* `-s`, `--settings-path <PATH>` - Datei mit den Einstellungen für diese Richtlinie
* `--sigstore-trust-config <PATH>` - JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschließlich der URIs, die für den Zugriff auf die CA- und Artefakttransparenzdienste verwendet werden, sowie die kryptografische Vertrauensbasis selbst
* `--sources-path <PATH>` - YAML-Datei mit Quellinformationen (https, Registry unsichere Hosts, benutzerdefinierte CAs...)
* `-a``--verification-annotation <KEY=VALUE>` - Anmerkung im Format Schlüssel=Wert. Kann mehrmals wiederholt werden
* `--verification-config-path <PATH>` - YAML-Datei mit Informationen zur Verifikationskonfiguration (Signaturen, öffentliche Schlüssel...)
* `-k`, `--verification-key <PATH>` - Pfad zum Schlüssel, der zur Überprüfung der Richtlinie verwendet wird. Kann mehrmals wiederholt werden

[[kwctl-save]]
=== `kwctl save`

Richtlinien in einer tar.gz-Datei speichern

*Verwendung:* `kwctl save --output <FILE> <policies>...`

==== Argumente

* `<POLICIES>` - Liste der zu speichernden Policen

==== Optionen

* `-o``--output <FILE>` - Pfad, in dem die Datei gespeichert werden soll

[[kwctl-scaffold]]
=== `kwctl scaffold`

Gerüst einer Kubernetes-Ressource oder Konfigurationsdatei

*Verwendung:* `kwctl scaffold <COMMAND>`

==== Unterbefehle

* `admission-request` - Gerüst für ein AdmissionRequest-Objekt
* `artifacthub` - Ausgabe einer artifacthub-pkg.yml-Datei aus einer metadata.yml-Datei
* `manifest` - Ausgabe eines Kubernetes-Ressourcenmanifests
* `vap` - Konvertieren Sie eine Kubernetes `ValidatingAdmissionPolicy` in eine {short-project-name} `ClusterAdmissionPolicy`
* `verification-config` - Ausgabe einer Standardkonfigurationsdatei für die Sigstore-Verifikation

[[kwctl-scaffold-admission-request]]
=== `kwctl scaffold admission-request`

Gerüst für ein AdmissionRequest-Objekt

*Verwendung:* `kwctl scaffold admission-request [OPTIONS] --operation <TYPE>`

==== Optionen

* `--object <PATH>` - Die Datei, die das neu zuzulassende Objekt enthält
* `--old-object <PATH>` - Die Datei, die das vorhandene Objekt enthält
* `-o`, `--operation <TYPE>` - {short-project-name} Benutzerdefinierter Ressourcentyp +
  Mögliche Werte: `CREATE`

[[kwctl-scaffold-artifacthub]]
=== `kwctl scaffold artifacthub`

Ausgabe einer artifacthub-pkg.yml-Datei aus einer metadata.yml-Datei

*Verwendung:* `kwctl scaffold artifacthub [OPTIONS]`

==== Optionen

* `-m``--metadata-path <PATH>` - Datei mit den Metadaten der Richtlinie
* `-o`, `--output <FILE>` - Pfad, in dem die Datei artifact-pkg.yml gespeichert wird
* `-q``--questions-path <PATH>` - Datei mit dem Inhalt der Fragen-ui der Police
* `-v``--version <VALUE>` - Semver-Version der Police

[[kwctl-scaffold-manifest]]
=== `kwctl scaffold manifest`

Ausgabe eines Kubernetes-Ressourcenmanifests

*Verwendung:* `kwctl scaffold manifest [OPTIONS] --type <VALUE> <uri_or_sha_prefix>`

==== Argumente

* `<URI_OR_SHA_PREFIX>` - Richtlinien-URI oder SHA-Präfix. Unterstützte Schemata: registry://, https://, file://. Wird schema weggelassen, wird file:// angenommen, bezogen auf das aktuelle Verzeichnis.

==== Optionen

* `--allow-context-aware <ALLOW-CONTEXT-AWARE>` - Verwendet die Metadaten der Richtlinie, um zu definieren, auf welche Kubernetes-Ressourcen die Richtlinie zugreifen kann. Achtung: Überprüfen Sie die Liste der Ressourcen sorgfältig, um Missbräuche zu vermeiden. Standardmäßig deaktiviert
* `--cert-email <VALUE>` - Erwartete E-Mail im Fulcio-Zertifikat
* `--cert-oidc-issuer <VALUE>` - Erwarteter OIDC-Emittent in Fulcio-Zertifikaten
* `--docker-config-json-path <DOCKER_CONFIG>` - Pfad zu einem Verzeichnis, das die Docker-Datei "config.json" enthält. Kann zur Angabe von Registrierungsauthentifizierungsdetails verwendet werden
* `--fulcio-cert-path <PATH>` - Der Weg zum Fulcio-Zertifikat. Kann mehrmals wiederholt werden
* `--github-owner <VALUE>` - GitHub-Besitzer wird in den in CD-Pipelines generierten Zertifikaten erwartet
* `--github-repo <VALUE>` - GitHub-Repository, das in den in CD-Pipelines generierten Zertifikaten erwartet wird
* `--rekor-public-key-path <PATH>` - Pfad zum öffentlichen Schlüssel von Rekor. Kann mehrmals wiederholt werden
* `--settings-json <VALUE>` - JSON-String mit den Einstellungen für diese Richtlinie
* `-s`, `--settings-path <PATH>` - Datei mit den Einstellungen für diese Richtlinie
* `--sigstore-trust-config <PATH>` - JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschließlich der URIs, die für den Zugriff auf die CA- und Artefakttransparenzdienste verwendet werden, sowie die kryptografische Vertrauensbasis selbst
* `--sources-path <PATH>` - YAML-Datei mit Quellinformationen (https, Registry unsichere Hosts, benutzerdefinierte CAs...)
* `--title <VALUE>` - Titel der Politik
* `-t`, `--type <VALUE>` - {short-project-name} Benutzerdefinierter Ressourcentyp +
  Mögliche Werte: `ClusterAdmissionPolicy`, `AdmissionPolicy`
* `-a``--verification-annotation <KEY=VALUE>` - Anmerkung im Format Schlüssel=Wert. Kann mehrmals wiederholt werden
* `--verification-config-path <PATH>` - YAML-Datei mit Informationen zur Verifikationskonfiguration (Signaturen, öffentliche Schlüssel...)
* `-k`, `--verification-key <PATH>` - Pfad zum Schlüssel, der zur Überprüfung der Richtlinie verwendet wird. Kann mehrmals wiederholt werden

[[kwctl-scaffold-vap]]
=== `kwctl scaffold vap`

Konvertieren Sie eine Kubernetes `ValidatingAdmissionPolicy` in eine {short-project-name} `ClusterAdmissionPolicy`

*Verwendung:* `kwctl scaffold vap [OPTIONS] --binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml> --policy <VALIDATING-ADMISSION-POLICY.yaml>`

==== Optionen

* `-b`, `--binding <VALIDATING-ADMISSION-POLICY-BINDING.yaml>` - Die Datei, die die ValidatingAdmissionPolicyBinding-Definition enthält
* `--cel-policy <URI>` - Das zu verwendende CEL-Richtlinienmodul +
  Standardwert: `ghcr.io/kubewarden/policies/cel-policy:latest`
* `-p``--policy <VALIDATING-ADMISSION-POLICY.yaml>` - Die Datei, die die Definition der ValidatingAdmissionPolicy enthält

[[kwctl-scaffold-verification-config]]
=== `kwctl scaffold verification-config`

Ausgabe einer Standardkonfigurationsdatei für die Sigstore-Verifikation

*Verwendung:* `kwctl scaffold verification-config`

[[kwctl-verify]]
=== `kwctl verify`

Überprüfen Sie eine {short-project-name} Richtlinie von einem bestimmten URI mit Sigstore

*Verwendung:* `kwctl verify [OPTIONS] <uri>`

==== Argumente

* `<URI>` - Politik URI. Unterstützte Schemata: registry://

==== Optionen

* `--cert-email <VALUE>` - Erwartete E-Mail im Fulcio-Zertifikat
* `--cert-oidc-issuer <VALUE>` - Erwarteter OIDC-Emittent in Fulcio-Zertifikaten
* `--docker-config-json-path <PATH>` - Pfad zu einem Verzeichnis, das die Docker-Datei "config.json" enthält. Kann zur Angabe von Registrierungsauthentifizierungsdetails verwendet werden
* `--github-owner <VALUE>` - GitHub-Besitzer wird in den in CD-Pipelines generierten Zertifikaten erwartet
* `--github-repo <VALUE>` - GitHub-Repository, das in den in CD-Pipelines generierten Zertifikaten erwartet wird
* `--sigstore-trust-config <PATH>` - JSON-formatierte Datei, die der ClientTrustConfig-Nachricht in den Sigstore-Protobuf-Spezifikationen entspricht. Diese Datei konfiguriert den gesamten Zustand der Sigstore-Instanz, einschließlich der URIs, die für den Zugriff auf die CA- und Artefakttransparenzdienste verwendet werden, sowie die kryptografische Vertrauensbasis selbst
* `--sources-path <PATH>` - YAML-Datei mit Quellinformationen (https, Registry unsichere Hosts, benutzerdefinierte CAs...)
* `-a``--verification-annotation <KEY=VALUE>` - Anmerkung im Format Schlüssel=Wert. Kann mehrmals wiederholt werden
* `--verification-config-path <PATH>` - YAML-Datei mit Informationen zur Verifikationskonfiguration (Signaturen, öffentliche Schlüssel...)
* `-k`, `--verification-key <PATH>` - Pfad zum Schlüssel, der zur Überprüfung der Richtlinie verwendet wird. Kann mehrmals wiederholt werden

'''

Dieses Dokument wurde automatisch erstellt von https://crates.io/crates/clap-markdown[`clap-markdown`].
