include::partial$variables.adoc[]
= Upgrade-Pfad
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Aktualisieren Sie Ihren {project-name} Stack mit Hilfe von unterstützten Versionsstrategien und Kompatibilitätsregeln zwischen seinen Komponenten.
:doc-persona: ["kubewarden-operator"]
:doc-topic: ["operator-manual", "upgrade-path"]
:doc-type: ["reference"]
:keywords: ["Upgrade-Pfad", "Unterstützung"]
:sidebar_label: Upgrade-Pfad
:sidebar_position: 20
:current-version: {page-origin-branch}

== {project-name} Stapelversionierung

Das Projekt {short-project-name} verwendet https://semver.org/[Semantische Versionierung], um die "Stack"-Version aller seiner Komponenten zu definieren: die Version folgt dem Muster`MAJOR.MINOR.PATCH`. Die unterstützte Version ist die neueste Version.

Die Komponenten von {short-project-name}, die den Regeln für die "Stack"-Version entsprechen, sind:

* `kubewarden-crds` in ihrem appVersion-Feld.

* `kubewarden-controller` in ihrem appVersion-Feld.

* `kubewarden-defaults` in ihrem appVersion-Feld.

* `policy-server` Bild-Tag für manuell bereitgestellte Bilder. Die Ressource für den Standard wird bereits von der Karte `kubewarden-defaults` verwaltet.

* `kwctl` binär.

== Kompatibilität der Stack-Versionen zwischen den Komponenten

Die Diagramme `kubewarden-crds`, `kubewarden-controller`,`kubewarden-defaults`, jedes manuell bereitgestellte `policy-server` -Image und`kwctl` sollten die gleiche `MAJOR`.`MINOR`.`PATCH` -Version verwenden.

Wenn also `kubewarden-controller` in der Version `1.1.2` läuft, sollten auch der``policy-server+s`` und +`kwctl`+ in der Version`+1.1.2` verwendet werden.

== Versionen der Steuerkarte

Helmkarten definieren das Feld `version` und das Feld `appVersion`. Das Feld`appVersion` informiert über die bereits erwähnte {short-project-name} "Stack"-Version. Das Feld `version` folgt ebenfalls https://semver.org/[semantische Versionierung] und beschreibt rückwärtskompatible Änderungen in den Diagrammvorlagen und `values.yaml`.

== Upgrade-Pfade

Wenn Sie Komponenten aktualisieren, können Sie mehrere `PATCH` Stack-Versionen in einem einzigen Vorgang aktualisieren. Das Upgrade mehrerer `MAJOR` oder `MINOR` Stack-Versionen in einem einzigen Upgrade wird jedoch *nicht* unterstützt.

Sie können zum Beispiel Komponenten von der Version `1.1.10` auf `1.1.nn` in einem einzigen Upgrade aktualisieren. Aber das Upgrade von `1.1.10` auf `1.5.0` wird nicht unterstützt. In diesen Fällen müssen Sie zwischen den beiden Versionen einzeln auf jede `MAJOR`/`MINOR` Version aktualisieren. Daher ist es notwendig, `1.1.10` auf`1.2.0`, dann `1.3.0`, dann `1.4.0` und schließlich `1.5.0` zu aktualisieren. Um eine`MAJOR` Version auf eine andere zu aktualisieren, müssen Sie alle `MINOR` Updates zwischen den beiden `MAJOR` Versionen anwenden.

.Beispiel für einen Upgrade-Pfad-Unterstützungsgraphen
[mermaid]
....
%%{init: "theme": "neutral"}%% Flussdiagramm LR; accTitle: Upgrade path support graph accDescr: Ein Diagramm mit empfohlenen und unterstützten Upgrade-Pfaden für {short-project-name}.
  1.0.0(1.0.0)-->1.0.1(1.0.1); 1.0.1-->1.0.2(1.0.2); 1.0.2-->1.1.0(1.1.0); 1.1.0-->1.1.2(1.1.2); 1.1.0-->1.1.1; 1.1.1-->1.1.2; 1.1.2-->|Nicht empfohlen|1.2.0(1.2.0); 1.0.2-->|Nicht unterstützt|1.2.0(1.2.0); 1.1.2-->1.2.1(1.2.1); 1.2.0-->1.2.1; linkStyle 6 color:brown,stroke-width:2px,stroke-dasharray: 3 5 linkStyle 7 color:red,stroke-width:2px,stroke-dasharray: 3 5
....

== Upgrade-Bestellung

{short-project-name} Die Benutzer sollten den Stapel zuerst mit der Karte `kubewarden-crds`und dann mit der Karte `kubewarden-controller` aktualisieren. Danach aktualisieren Sie die`policy-server` (über `kubewarden-defaults` chart oder bumping the images of custom ones) und `kwctl`.

== Herabstufungen

Downgrades werden *nicht* unterstützt, und {short-project-name} testet sie nicht. Dennoch besteht die berechtigte Erwartung, dass sie funktionieren sollten.

== SDKs, Richtlinien

Policy SDKs für die verschiedenen Sprachen und Policies, die vom{short-project-name} Team gepflegt werden, folgen ihrer eigenen semantischen Versionierung. {short-project-name} unterstützt die neueste Version. Für sie ist kein Upgrade-Pfad erforderlich, sondern nur ein Wechsel auf die neueste Version.

Änderungen am {short-project-name} Stack können dazu führen, dass Richtlinien und SDKs aktualisiert werden, um die neuesten Funktionen von {short-project-name} zu nutzen. {short-project-name} achtet darauf, diese Aktualisierungen abwärtskompatibel durchzuführen.

Zum Beispiel bedeutet eine kleinere Version von {short-project-name}, die Unterstützung für Audit Scanner (`v1.7.0`) hinzufügt, dass Richtlinien ein neues Feld `spec.backgroundAudit` erhalten. Dies ist optional, abwärtskompatibel und standardmäßig auf `true` eingestellt.
