= Telemetrie-Kollektor als Proxy öffnen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observabilität

Die normale Konfiguration des Opentelemetry Collectors für Tail-Sampling Traces finden Sie xref:/setup/otel/collector.adoc[hier]

Die nachstehende Konfiguration beschreibt eine Bereitstellung, bei der nur die Stapelverarbeitung erfolgt und keine weitere Verarbeitung von Traces, Metriken oder Protokollen.  Es ist als Sicherheits-Proxy gedacht, der außerhalb des SUSE Observability-Clusters, aber innerhalb einer vertrauenswürdigen Netzwerkinfrastruktur existiert.  Die Sicherheits-Credentials für den Proxy und SUSE Observability können separat eingerichtet werden, wodurch eine zusätzliche Authentifizierungsebene hinzugefügt wird, die nicht beim Aufrufer, sondern beim Host liegt.

image::otel/aws_nodejs_otel_proxy_collector_configuration.svg[AWS Lambda-Instrumentierung mit Opentelemetrie über Proxy-Kollektor]

[tabs]
====
Traefik (Standard)::
+
--

.otel-collector.yaml
[,yaml]
----
mode: deployment
presets:
   kubernetesAttributes:
      enabled: true
      # You can also configure the preset to add all the associated pod's labels and annotations to you telemetry.
      # The label/annotation name will become the resource attribute's key.
      extractAllPodLabels: true
extraEnvsFrom:
   - secretRef:
        name: open-telemetry-collector
image:
   repository: "otel/opentelemetry-collector-k8s"

config:
   receivers:
      otlp:
         protocols:
            grpc:
               endpoint: 0.0.0.0:4317
            http:
               endpoint: 0.0.0.0:4318

   exporters:
      # Exporter for traces to traffic mirror (used by the common config)
      otlp:
         endpoint: <url for opentelemetry ingestion by suse observability>
         auth:
            authenticator: bearertokenauth

   extensions:
      bearertokenauth:
         scheme: SUSEObservability
         token: "${env:API_KEY}"

   service:
      extensions: [health_check, bearertokenauth]
      pipelines:
         traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-traefik-external
    traefik.ingress.kubernetes.io/ingress.class: ingress-traefik-external
    traefik.ingress.kubernetes.io/backend-protocol: GRPC
    # "12.34.56.78/32" IP address of NatGateway in the VPC where the otel data is originating from
    #  traefik.ingress.kubernetes.io/whitelist-source-range: "12.34.56.78/32"
  hosts:
    - host: "otlp-collector-proxy.${CLUSTER_NAME}"
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: 4317
  tls:
    - secretName: ${CLUSTER_NODOT}-ecc-tls
      hosts:
        - "otlp-collector-proxy.${CLUSTER_NAME}"
----
--

Nginx::
+
--
[NOTE]
=====
Das Ingress-Nginx-Projekt https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/[wird aufgegeben]. Den Nutzern wird empfohlen, Alternativen wie Traefik in Betracht zu ziehen.
=====

.otel-collector.yaml
[,yaml]
----
mode: deployment
presets:
   kubernetesAttributes:
      enabled: true
      # You can also configure the preset to add all the associated pod's labels and annotations to you telemetry.
      # The label/annotation name will become the resource attribute's key.
      extractAllPodLabels: true
extraEnvsFrom:
   - secretRef:
        name: open-telemetry-collector
image:
   repository: "otel/opentelemetry-collector-k8s"

config:
   receivers:
      otlp:
         protocols:
            grpc:
               endpoint: 0.0.0.0:4317
            http:
               endpoint: 0.0.0.0:4318

   exporters:
      # Exporter for traces to traffic mirror (used by the common config)
      otlp:
         endpoint: <url for opentelemetry ingestion by suse observability>
         auth:
            authenticator: bearertokenauth

   extensions:
      bearertokenauth:
         scheme: SUSEObservability
         token: "${env:API_KEY}"

   service:
      extensions: [health_check, bearertokenauth]
      pipelines:
         traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    # "12.34.56.78/32" IP address of NatGateway in the VPC where the otel data is originating from
    #  nginx.ingress.kubernetes.io/whitelist-source-range: "12.34.56.78/32"
  hosts:
    - host: "otlp-collector-proxy.${CLUSTER_NAME}"
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: 4317
  tls:
    - secretName: ${CLUSTER_NODOT}-ecc-tls
      hosts:
        - "otlp-collector-proxy.${CLUSTER_NAME}"
----
--
====

[discrete]
=== Whitelisting des Eingangsquellenbereichs

Um die Rolle des Proxy-Kollektors als Sicherheitsmaßnahme zu unterstreichen, wird empfohlen, eine Whitelist für den Quellbereich zu verwenden, um Daten aus nicht vertrauenswürdigen und/oder unbekannten Quellen herauszufiltern. Im Gegensatz dazu muss der SUSE Observability-Ingestion-Collector unter Umständen Daten aus mehreren Quellen akzeptieren, so dass eine Whitelist auf dieser Ebene nicht gut skalierbar ist.
